### ISSUE TITLE
[ SOLVED ] Can't connect to docker daemon from CLI

### ISSUE THREAD

**Issue by MrMic** [docker/for-mac#10]
### Information

Diagnostic ID: 6C65A543-4C30-4C8D-8AFF-195FF9E218D8
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
 
I create a container (nginx) for test and the spawn a terminal for a CLI.
docker --version is OK ...
But when i run:  

$: docker ps -a                                                                                                                         15:18:09
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Seems that i can't find the socket of docker.
A ny idea where i can configure this ?

Another infos on docker process:

=== 8< =================================== >8 ===

ps -ef | grep -i docker                                                                                                              15:13:58
  501 15479     1   0  2:37   ??         0:13.08 /Applications/Docker.app/Contents/MacOS/Docker -psn_0_1401174
    0 15496     1   0  2:38   ??         0:00.01 /Library/PrivilegedHelperTools/com.docker.vmnetd
  501 15504 15479   0  2:39   ??         0:00.05 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
  501 15506 15504   0  2:39   ??         0:00.08 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
  501 15507 15504   0  2:39   ??         0:01.15 com.docker.db --url fd:3 --git /Users/mic/Library/Containers/com.docker.docker/Data/database
  501 15508 15504   0  2:39   ??         0:00.82 com.docker.osxfs --address fd:3 --connect /Users/mic/Library/Containers/com.docker.docker/Data/@connect --control fd:4 --volume-control fd:5 --database /Users/mic/Library/Containers/com.docker.docker/Data/s40
  501 15509 15504   0  2:39   ??         0:00.49 com.docker.slirp --db /Users/mic/Library/Containers/com.docker.docker/Data/s40 --ethernet fd:3 --port fd:4 --vsock-path /Users/mic/Library/Containers/com.docker.docker/Data/@connect --max-connections 900
  501 15510 15504   0  2:39   ??         0:00.41 com.docker.osx.hyperkit.linux
  501 15511 15504   0  2:39   ??         0:00.46 com.docker.driver.amd64-linux -db /Users/mic/Library/Containers/com.docker.docker/Data/s40 -osxfs-volume /Users/mic/Library/Containers/com.docker.docker/Data/s30 -slirp /Users/mic/Library/Containers/com.docker.docker/Data/s50 -vmnet /var/tmp/com.docker.vmnetd.socket -port /Users/mic/Library/Containers/com.docker.docker/Data/s51 -vsock /Users/mic/Library/Containers/com.docker.docker/Data -docker /Users/mic/Library/Containers/com.docker.docker/Data/s60 -addr fd:3 -debug
  501 15512 15510   0  2:39   ??         0:00.05 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux
  501 15513 15511   0  2:39   ??         0:00.04 /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db /Users/mic/Library/Containers/com.docker.docker/Data/s40 -osxfs-volume /Users/mic/Library/Containers/com.docker.docker/Data/s30 -slirp /Users/mic/Library/Containers/com.docker.docker/Data/s50 -vmnet /var/tmp/com.docker.vmnetd.socket -port /Users/mic/Library/Containers/com.docker.docker/Data/s51 -vsock /Users/mic/Library/Containers/com.docker.docker/Data -docker /Users/mic/Library/Containers/com.docker.docker/Data/s60 -addr fd:3 -debug
  501 15514 15511   0  2:39   ??         0:18.94 /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2G -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=22fc5061-4e8d-4a2b-9692-92cd1754c495,path=/Users/mic/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/mic/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/mic/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2,format=qcow -s 4,virtio-9p,path=/Users/mic/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/mic/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/mic/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/mic/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/mic/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac -F /Users/mic/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
  501 18656 15479   0  3:17   ??         0:00.01 /Applications/Docker.app/Contents/Resources/bin/com.docker.frontend {"action":"vmstateevent","args":{"vmstate":"running"}}
  501 18657 18656   0  3:17   ??         0:00.01 /Applications/Docker.app/Contents/Resources/bin/com.docker.frontend {"action":"vmstateevent","args":{"vmstate":"running"}}
  501 18659 17456   0  3:17   ttys002    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i docker

=== 8< =================================== >8 ===

Thanks for the reply !

Rgds,

another info

**Comment by samoht** [comment]
Can you check that you have unset all `DOCKER_` environment variables in your shell? See https://docs.docker.com/docker-for-mac/troubleshoot/#workarounds-for-common-problems

**Comment by MrMic** [comment]
Yes, you are darn right !
I forgot that i have something in my zshrc ...

It seems OK now !
You can closed.

Thanks for the quick and wise support.

Rgds,
