### ISSUE TITLE
docker-machine ls returns the exception

### ISSUE THREAD

**Issue by caigang78** [docker/for-mac#100]
docker-machine ls

### Expected behavior
response the machines

### Actual behavior
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1d8742]

goroutine 1 [running]:
panic(0x1221540, 0xc82000c0b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/machine/libmachine/host.MigrateHostV2ToHostV3(0xc82023e200, 0xc820242000, 0x4f, 0x24f, 0x15889c0, 0x1, 0x0)
	/go/src/github.com/docker/machine/libmachine/host/migrate_v2_v3.go:26 +0x882
github.com/docker/machine/libmachine/host.MigrateHost(0xc820146960, 0xc820242000, 0x4f, 0x24f, 0x24f, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/host/migrate.go:109 +0xf89
github.com/docker/machine/libmachine/persist.Filestore.loadConfig(0xc820137ee0, 0x1b, 0xc820240000, 0x21, 0xc820240000, 0x21, 0xc820146960, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/persist/filestore.go:122 +0x245
github.com/docker/machine/libmachine/persist.Filestore.Load(0xc820137ee0, 0x1b, 0xc820240000, 0x21, 0xc820240000, 0x21, 0xc820240175, 0x7, 0xc820137f20, 0x0, ...)
	/go/src/github.com/docker/machine/libmachine/persist/filestore.go:158 +0x2f2
github.com/docker/machine/libmachine.(*Client).Load(0xc820145310, 0xc820240175, 0x7, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/libmachine.go:92 +0x71
github.com/docker/machine/libmachine/persist.LoadHosts(0x27d5a78, 0xc820145310, 0xc82013bb60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x5)
	/go/src/github.com/docker/machine/libmachine/persist/store.go:29 +0x14e
github.com/docker/machine/libmachine/persist.LoadAllHosts(0x27d5a78, 0xc820145310, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/persist/store.go:45 +0xf7
github.com/docker/machine/commands.cmdLs(0x27d5990, 0xc8201420a8, 0x27d5a10, 0xc820145310, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:83 +0x144
github.com/docker/machine/commands.runCommand.func1(0xc820233200)
	/go/src/github.com/docker/machine/commands/commands.go:163 +0x5e3
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x1590938, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15a3d90, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x1081
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc820232ea0, 0xc82000a1c0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0xffa
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:163 +0xcc0

### Information

  Docker for Mac: version: win-beta-v1.12.0-rc5-beta21-73-g9cd1dc2
OS X: version 10.11.4 (build: 15E65)
logs: /tmp/0B2D8DAD-3D19-4496-82E0-5018FE19CB4D/20160803-175537.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by caigang78** [comment]
I reset the docker to factory mode following this: https://github.com/docker/for-mac/issues/46. 

And then I re-installed the docker 1.1.12. It's the same....

**Comment by djs55** [comment]
I think this might be an issue with the `docker-machine` tool when loading its configuration from disk. Could you try moving your current configuration to a backup directory e.g.
```
mv ~/.docker ~/.docker.backup
```
and seeing if the panic on `docker-machine ls` is gone? If so I recommend filing an issue on https://github.com/docker/machine with details of the `docker-machine` configuration.

**Comment by mchiang0610** [comment]
@caigang78 Looks like a problem with Docker-machine.
