### ISSUE TITLE
Docker for OSX, maven download slow

### ISSUE THREAD

**Issue by Noodle05** [docker/for-mac#1002]
I'm trying to create a java project building docker, it will use svn checkout project and use maven to build it.

Same docker image works pretty good on Linux host, but maven download extremely slow/stucks on OSX host.

I tried to check network connection status from inside the container when it stuck, and find that maven TCP connection stuck at SYN_SENT state for very long time. This is not always happen. For example, after I restart Docker engine on OSX, it will run fine for a while. If I wait long enough, it will slowly move and then run fine for a while too. But if your have lot dependencies, it will happen almost every time.

While maven download stuck, I still can download with "curl" even from same maven repo host.

Not sure if this is maven issue or Docker issue, but since same docker running fine on Linux host, I guess this maybe a xhyve network issue on OSX?

OSX version: 10.11.6

docker info
```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 23.5 GiB
Name: moby
ID: xxxxxxxxxxxxxxxxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 91
 System Time: 2016-12-01T19:32:03.128567602Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by Noodle05** [comment]
Copied from: https://github.com/docker/docker/issues/29037

**Comment by justincormack** [comment]
cc @djs55 @yomimono any ideas?

**Comment by rogaha** [comment]
@Noodle05 can you please run the `diagnose & upload` from `Docker for Mac`? Also, can you please upgrade your `Docker for Mac` application and confirm that the issue persists? We had lots of `DNS/networking` improvements along with the latest updates.

**Comment by Noodle05** [comment]
I'm getting following error:

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/9199E220-1C69-4214-9FFF-CDFCA9EFEF1B/20161206-110323.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by rogaha** [comment]
@Noodle05 can you please install the latest `beta` version? it looks like you are using the `stable` version. Link: https://download.docker.com/mac/beta/Docker.dmg

**Comment by Noodle05** [comment]
The beta having same issue. Uploaded diagnostic

Diagnostic ID: 5A7D84F4-40A1-4A9E-994A-B9D7D3168ACA

**Comment by djs55** [comment]
@Noodle05 thanks for the new diagnostic. Unfortunately I can't spot an obvious problem in the logs, but it could be some kind of connection leak. Could you provide me a simple Dockerfile/compose file/set of instructions to reproduce this problem with `maven`?

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
