### ISSUE TITLE
Allow User to define Folder/Location where Docker stores Files, Images, Containers

### ISSUE THREAD

**Issue by SimonHoenscheid** [docker/for-mac#1003]
### Information

 I'm very happy with Docker for Mac. But I'm missing a feature to choose the Folder where Docker stores Containers, Files etc.

**Comment by rogaha** [comment]
@SimonHoenscheid just a heads up, we are planning to add that feature to the next `beta` release. We will keep you posted.

**Comment by SimonHoenscheid** [comment]
Thx!!!

**Comment by dsheets** [comment]
This shipped in Beta 33 and will reach stable in the next release in a week or two.

**Comment by samoht** [comment]
The fix is now released on both the beta and stable channels so I am closing the issue. Please re-open (or open a new one) with a new diagnostic ID you still have that problem.
