### ISSUE TITLE
Container silently stops while filling MySQL db using InnoDB

### ISSUE THREAD

**Issue by sandertan** [docker/for-mac#1004]
### Expected behavior
I'm using Docker to fill a MySQL database using the InnoDB Storage Engine. Doing this locally does not lead to errors. Also performs flawless in Docker on Ubuntu 16.04.

### Actual behavior
Without any error message, Docker activity goes to 0 in all activity monitors, without completing the task. Practically no CPU activity and no disk read/write.

### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/30B596D8-F844-4A48-9588-E2288A208539/20161202-123850.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
I'm using Docker to fill a MySQL database using the InnoDB Storage Engine.

  1. Download the database schema, and 2 files containing the contents for the database, from https://github.com/cBioPortal/datahub/tree/master/seedDB
  2. Start a Docker container with Mysql, and give the 3 files to initiate filling the database (in a specific order), using -v to mount a volume. I also mount seperate folder to save the mysql database files locally. This is useful for when I want to start the database faster in the future. I use the following command:
```### First time 1-3-1
docker run -d --name "cbioDB" \
 --restart=always \
 --net=cbio-net \
 -p 8306:3306 \
 -e MYSQL_ROOT_PASSWORD=Examplepw1@ \
 -e MYSQL_USER=cbio \
 -e MYSQL_PASSWORD=Examplepw1@ \
 -e MYSQL_DATABASE=cbioportal \
 -v /Users/sander/Data/Seed-DB/1-3-1/db_files:/var/lib/mysql/ \
 -v /Users/sander/Data/Seed-DB/1-3-1/cgds.sql:/docker-entrypoint-initdb.d/01_cgds.sql:ro \
 -v /Users/sander/Data/Seed-DB/1-3-1/seed-cbioportal_no-pdb_hg19.sql.gz:/docker-entrypoint-initdb.d/02_seed.sql.gz:ro \
 -v /Users/sander/Data/Seed-DB/1-3-1/seed-cbioportal_only-pdb.sql.gz:/docker-entrypoint-initdb.d/03_seed.sql.gz:ro \
mysql
```
 3. After a couple minutes the activity goes to zero.

The third database file `seed-cbioportal_only-pdb.sql.gz` is quite big, and it should take some time to load. When I only load the second file `seed-cbioportal_no-pdb_hg19.sql.gz` the loading does not crash. 

Used on a Macbook Pro (Early 2015) with 16GB RAM. I tried with several Docker CPU configurations and RAM settings (for example, 3 CPUs and 14GB RAM). The activity monitors never show more than a couple GB RAM usage.

**Comment by djs55** [comment]
Thanks for the bug report. I ran these instructions with the latest beta 34 of Docker for Mac and it seemed to complete.

While it was running I could see this:
```
$ docker top 82bd52f5d4e5
PID                 USER                TIME                COMMAND
29380               999                 0:00                {docker-entrypoi} /bin/bash /usr/local/bin/docker-entrypoint.sh mysqld
29447               999                 14:25               mysqld --skip-networking --socket=/var/run/mysqld/mysqld.sock
29503               999                 0:15                gzip -d -c /docker-entrypoint-initdb.d/03_seed.sql.gz
29504               999                 0:31                mysql --protocol=socket -uroot -hlocalhost --socket=/var/run/mysqld/mysqld.sock -px xxxxxxxxx cbioportal
```
and when it had finished I could see this:
```
$ docker top 82bd52f5d4e5
PID                 USER                TIME                COMMAND
29380               999                 0:01                mysqld
```
-- it looks like it has completed the import and now the daemon is running. My `db_files` directory is now 15G in size.

There have been lots of improvements to the volume sharing in recent betas. Could you try again in beta 34 (or later) and let me know if it still reproduces for you?

**Comment by sandertan** [comment]
@djs55 Great! I tested with Beta Version 1.13.0-rc4-beta34.1 (14853) and it indeed completes successfully! 

Thanks for testing :) Any idea when this update will be in the stable release?

You may close this Issue.

**Comment by djs55** [comment]
Thanks!
