### ISSUE TITLE
com.docker.driver.amd64-linux -db is not running

### ISSUE THREAD

**Issue by pranittrivedi** [docker/for-mac#1006]
### Information

Diagnostic ID: 5EF2BF6D-10C4-419A-B74E-9C9FC7E2509E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.1 (Build 16B2555)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/pranittrivedi/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/pranittrivedi/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by rogaha** [comment]
cc @samoht  any ideas?

**Comment by rogaha** [comment]
@pranittrivedi  can you please try to install the `newer` version from scratch, if possible?

**Comment by pranittrivedi** [comment]
@rogaha I tried that multiple times. Set bash profiles a few times too. But in the end, just re-installing it didn't fix it, you had to hit the "reset to factory defaults" to ensure it cleaned out all the old files. 

Thanks though.

**Comment by ubuntudroid** [comment]
Just click on "reset" did the trick for me as well - no reinstall needed. You just have to be really fast when clicking through the reset buttons to be faster than the error message of the booting docker container because the error dialog blocks all other input.
