### ISSUE TITLE
beta31 docker-compose overlay2: invalid argument

### ISSUE THREAD

**Issue by algesten** [docker/for-mac#1007]
### Expected behavior

`./docker-compose up -d` works fine in stable channel. Because of the VPN issue I tried the beta.

### Actual behavior

```
$ ./docker-compose -f docker-compose-core.yml -f docker-compose-devbox.yml up -d
Creating network "stack_default" with the default driver
ERROR: readlink /var/lib/docker/overlay2: invalid argument
```

This is after it downloaded all images from my private registry.

### Information

There is no fancy networking in my docker-compose files. Just plain links in the default network.

```
Docker for Mac: version: 1.13.0-rc2-beta31 (de6f6c2)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/3B3B818E-A3EA-4BF1-BF95-F55DE52CC902/20161203-111716.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by justincormack** [comment]
Did you do a factory reset when you switched channels?

**Comment by algesten** [comment]
On installation it told me it needed to reset everything, and I agreed. It then asked for privileges. After that I had to download all my images again on first run – so I assumed it was an implicit reset. I never tried a manual one.

**Comment by rogaha** [comment]
@algesten can you please try it manually and check if that works? Thanks

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
