### ISSUE TITLE
Auto Detect Proxy Issue

### ISSUE THREAD

**Issue by ibigbug** [docker/for-mac#1008]
### Expected behavior

Docker for Mac can detect proxy correctly from Network Preferences, eg, my LAN ip like 10.x.x.x or please do not auto fill proxy settings in the Docker for Mac settings pane.

### Actual behavior

It's detecting the proxy as 127.0.0.1:port which is obviously unusable by the docker daemon in the  HyperKit vm. What's worse is I can not change the proxy settings for Docker for Mac manually.

### Information

![image](https://cloud.githubusercontent.com/assets/543405/20885474/efd6b26c-bb2b-11e6-9aa3-a763759f1e3a.png)

![image](https://cloud.githubusercontent.com/assets/543405/20885442/bf871cfa-bb2b-11e6-8c43-20f07d035391.png)

This software wont' diagnose.

### Steps to reproduce the behavior

  1. set http_proxy and https_proxy to `127.0.0.1:3128` in Mac network preference pane
  2. start Docker for Mac 
  3. check the proxy settings in Docker for Mac

**Comment by rogaha** [comment]
@ibigbug can you please confirm the `version` of your `Docker for Mac` application?

**Comment by ibigbug** [comment]
@rogaha The version is:

![image](https://cloud.githubusercontent.com/assets/543405/20925867/5307e054-bbf4-11e6-89e6-32974e3fd6cf.png)

**Comment by rogaha** [comment]
@ibigbug this is fixed on the `beta` channel (https://download.docker.com/mac/beta/Docker.dmg) and it will be fixed on the next `stable` release. Thanks for reporting the issue!

**Comment by ibigbug** [comment]
@rogaha Great to hear that. Thanks for your work!
