### ISSUE TITLE
authentication failed after correct login on mac

### ISSUE THREAD

**Issue by DavidCervigni** [docker/for-mac#101]
### Expected behavior
push success
### Actual behavior
MacBook-Pro-3:imageU1 david$ docker push ubuntu:latest
The push refers to a repository [docker.io/library/ubuntu]
9a39129ae0ac: Preparing
98305c1a8f5e: Preparing
0185b3091e8e: Preparing
ea9f151abb7e: Preparing
unauthorized: authentication required

### Information

Diagnostic ID: D3867370-897A-412A-A605-0ABBC67E8BEE
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
If you are trying to push that image to a private registry, you need to re-tag it first.
If you are tyring to push to Docker Hub, the tag should be `<your_username>/ubuntu:latest`
As it stands, that error is expected as you don't have permissions to push to `library/ubuntu`

**Comment by mchiang0610** [comment]
Closing.
