### ISSUE TITLE
How can I configure the default bridge network

### ISSUE THREAD

**Issue by hector70** [docker/for-mac#1011]
I need to change the default bridge network since the one provided by default is used inside my intranet. Where is something like config.json in Docker for MAC 1.12.3

**Comment by rogaha** [comment]
@hector70 the `bridge` network is not exposed through `Docker for Mac` (see docs https://docs.docker.com/docker-for-mac/networking/#/there-is-no-docker0-bridge-on-macos). Can you please clarify what's the issue you are experiencing?

**Comment by hector70** [comment]
Actually I was experimenting the problems isssued in the link you gave me.

2016-12-06 13:54 GMT+01:00 Roberto Gandolfo Hashioka <
notifications@github.com>:

**Comment by rogaha** [comment]
@hector70 which one exactly? I'm trying to understand your `use-case`.

**Comment by hector70** [comment]
The use case is simple: I want some container to connect to the company
intranet, which reaches a network with the same address of the default
docker bridge network through a router so only the default gateway knows
about its existance, that's why I wanted to change the default bridge
network address. I solved the problem attacching container to a
user-defined bridge network but I would like this behavious to be the
default.

2016-12-09 11:45 GMT+01:00 Roberto Gandolfo Hashioka <
notifications@github.com>:

**Comment by djs55** [comment]
In the beta version of Docker for Mac it's possible to customise the `daemon.json`. The `daemon.json` has lots of options which correspond to the daemon's command line arguments: https://docs.docker.com/engine/reference/commandline/dockerd/

This should be in the 1.13 stable release due out early in the new year.

**Comment by samoht** [comment]
The fix is now released on both the beta and stable channels so I am closing the issue. Please re-open (or open a new one) with a new diagnostic ID you still have that problem.
