### ISSUE TITLE
Can't find suitable config for file 

### ISSUE THREAD

**Issue by heyeon** [docker/for-mac#1012]
### Expected behavior
Docker executes the command

### Actual behavior
docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
### Information
  - Need to reset factory defaults everytime to get docker to run

### Steps to reproduce the behavior

  1. Run any Docker Compose command
  2. Using Docker for Mac 1.12.3

**Comment by rogaha** [comment]
@heyeon can you please try that with the `latest` beta version (https://download.docker.com/mac/stable/Docker.dmg)?

**Comment by heyeon** [comment]
Thanks! Works.

**Comment by djs55** [comment]
Thanks for the update!

**Comment by balrajsingh** [comment]
Thanks for the report and thanks for confirming that it works now.  Closing.

**Comment by MatxBerg** [comment]
I still have this issue. Docker-compose worked for a while but then stopped by always returning the error below no matter the command, ps, rm etc. I even tried to upgrade to the edge channel but I still have the issue.

```
Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?

Supported filenames: docker-compose.yml, docker-compose.yaml

```

MacOS Version: 10.12.5
Docker Version: 17.06.0-ce-mac17

**Comment by patrickmaynard** [comment]
In Version 17.06.0-ce-mac19 (stable channel), this behavior still appears to exist.

Furthermore, "reset to factory defaults" does not appear to solve the problem any longer.

**Comment by dsheets** [comment]
@patrickmaynard could you please open a new issue with as much detail as you can provide including software versions and reproduction steps? Thanks!

**Comment by patrickmaynard** [comment]
To be frank, I think I'm actually just misunderstanding a workflow. Sorry about that.

**Comment by patrickmaynard** [comment]
... and thanks for the super-speedy response on a Friday!

**Comment by sampiecz** [comment]
What workflow were you misunderstanding?  I think I'm having the same misunderstanding.

**Comment by MatxBerg** [comment]
I still get this error with docker Version 17.07.0-ce-rc1-mac21 (18848)
MacOS version : 10.12.6

Can't get a simple command like the following to work

> docker-compose ps

I always get

> Can't find a suitable configuration file in this directory or any
>         parent. Are you in the right directory?

I did try the factory reset thing

**Comment by agusddt** [comment]
I'm having the same issue here. Using MacOS Sierra 10.12.6 (16G1114) and docker-compose version 1.18.0, build 8dd22a9.
I've tried reinstalling, reseting, etc and still not working, allways same error:

`Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?

Supported filenames: docker-compose.yml, docker-compose.yaml
`

Any help?

**Comment by JasperKirton** [comment]
Same problem. Feeling a bit confused....

**Comment by coomrade** [comment]
i'm not mac,but same problem,wth...

**Comment by RJ722** [comment]
Hey, I'm also facing the same issue (on Mac).

Here's the output from `docker-compose version`:
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

Any idea how to get around this?
