### ISSUE TITLE
Fatal Error: vmstateevent invalid json: 

### ISSUE THREAD

**Issue by ksokolovic** [docker/for-mac#1013]
### Expected behavior

Update is downloaded and installed.

### Actual behavior

While downloading the update, **Fatal Error** dialog is shown with the following message: *vmstateevent invalid json:*

### Information

Diagnostic ID: 4FBB527A-564D-423E-8360-C4DDB3957985
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.1 (Build 16B2555)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Try to download latest updates
2. Download progresses
3. When trying to install updates, the **Fatal Error** occurs, failing to update.

**Comment by rogaha** [comment]
@ksokolovic can you please try to `uninstall` and they install the latest version? it might be an issue with the `1.12.0-a` version specifically. 

<img width="380" alt="screen shot 2016-12-06 at 4 56 44 am" src="https://cloud.githubusercontent.com/assets/4483394/20926298/6db5fd70-bb70-11e6-9ee1-49b637311a00.png">

**Comment by ksokolovic** [comment]
@rogaha Fresh (re)install worked like a charm. Thanks!

**Comment by rogaha** [comment]
awesome! Thanks for the update @ksokolovic
