### ISSUE TITLE
No Docker support on 2010 MacPro5,1

### ISSUE THREAD

**Issue by tmcsys** [docker/for-mac#1021]
### Actual behavior

Stable release

Unable to obtain diagnostic report

Incompatible CPU detected.

Diagnose * Feedback...
Diagnose and upload 

failure: Optional("diagnostic: response is not valid JSON")

### Information

10.11.6
VirtualBox Version 5.1.10 r112026 (Qt5.6.2)

kern.hv_support: 0

Model Name:	Mac Pro (Mid 2010)
Model Identifier:	MacPro5,1
Processor Name:	Quad-Core Intel Xeon
Processor Speed:	3.2 GHz

machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz

CPU appears to conform to requirements for Apple Hypervisor framework:
http://ark.intel.com/products/39721/Intel-Xeon-Processor-W3565-8M-Cache-3_20-GHz-4_80-GTs-Intel-QPI

### Steps to reproduce the behavior

Launch Docker app

**Comment by jeanlaurent** [comment]
Hi @tmcsys  which version of Docker for Mac are your trying to run ?

**Comment by tmcsys** [comment]
Sorry.   Dumb of me not to include that information, but on reflection it's not exactly easy to come by.

The image downloaded as "docker.dmg", so that doesn't help much.

The App crashes so there's no "About" information.

Digging into the Docker.Contents:

Most of the first-level files are dated Nov. 8 2016 12:36 PM.

Oddly, when digging around the image, I encountered this message: "Pacifist was unable to open the file 'initrd.img'. Please make sure this is a file type that Pacifist understands.

Possibly a corrupt .dmg image?

info.plist

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>15G1108</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Docker</string>
	<key>CFBundleExecutable</key>
	<string>Docker</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>com.docker.docker</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Docker</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.12.3</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>13776</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8A218a</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16A300</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0800</string>
	<key>DTXcodeBuild</key>
	<string>8A218a</string>
	<key>DockerChannel</key>
	<string>stable</string>
	<key>DockerKitematicMinVersion</key>
	<string>0.10.4</string>
	<key>HockeyAppId</key>
	<string></string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.developer-tools</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.10</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2016 Docker Inc. All Rights Reserved.</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSUserNotificationAlertStyle</key>
	<string>alert</string>
	<key>SMPrivilegedExecutables</key>
	<dict>
		<key>com.docker.vmnetd</key>
		<string>identifier "com.docker.vmnetd" and certificate leaf[subject.CN] = "Developer ID Application: Docker Inc (9BNSXJN65R)"</string>
	</dict>
	<key>SUAllowsAutomaticUpdates</key>
	<false/>
	<key>SUEnableAutomaticChecks</key>
	<false/>
	<key>SUEnableSystemProfiling</key>
	<false/>
</dict>
</plist>
```

**Comment by jeanlaurent** [comment]
Thanks for the info @tmcsys, but I'm sorry I got bad news.

In the [Apple Hypervisor Framework](https://developer.apple.com/reference/hypervisor) Supported Hardware section they state :

> Supported Hardware
> Generally, machines with an Intel VT-x feature set that includes Extended Page Tables (EPT) and Unrestricted Mode are supported. 

And the Intel(R) Xeon(R) CPU W3565 running your mac pro has VTX with EPT but not Unrestricted Mode. 

Unrestricted mode was introduced in the next microarchitecture family ( Westmere ) while your processor is from the previous one ( Nehalem ). Thx to @rneugeba for this information.

You can still runs docker with [Docker Toolbox](https://www.docker.com/products/docker-toolbox).

We opened an issue in our internal tracker to update our documentation accordingly.

**Comment by tmcsys** [comment]
Who knew about "Unrestricted Mode"?  No doubt I am guilty of wishfully thinking that the processor met Apple's requirements.

Amending the documentation will certainly help, but this in itself will not correct the fact that Docker crashes very ungracefully on this platform without generating a meaningful error message.

Thanks very much for looking into this.

**Comment by opsline-patrick** [comment]
@tmcsys have you tried upgrading your processor?  Xeon Westmere X5670 currently runs under $40 on Amazon, I have the same machine so I'm considering the upgrade so virtualization tech like Docker for Mac is compatible.

**Comment by charEtoile** [comment]
@opsline-patrick Did you the CPU of your Mac Pro ?

**Comment by tmcsys** [comment]
I had completely forgotten about this until a couple of weeks ago when I found myself missing a current Docker.

Has anyone successfully upgraded their iMac CPU to take advantage of hardware virtualization? 

Is the CPU upgrade a big deal?

I have been inside the iMac to install a SSD, but never considered a CPU upgrade.

Actually, was just thinking about a new Mac today.


>
