### ISSUE TITLE
Docker spontaneously does not respond

### ISSUE THREAD

**Issue by muenalan** [docker/for-mac#1022]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MagnusS** [comment]
I'm closing this issue as there is not enough information in it to reproduce or debug. Please file a new issue with more information about how the issue occurred and a diagnostics ID if available.
