### ISSUE TITLE
Fresh install - error: Could not read CA  certificate ".../machine/machines/default/ca.pem" no such file...

### ISSUE THREAD

**Issue by davidmpatterson** [docker/for-mac#1023]
### Expected behavior
The "hello-world" should download and run.

### Actual behavior
Could not read CA certificate "/.../.docker/machine/machines/default/ca.pem": open /Users/.../.docker/machine/machines/default/ca.pem: no such file or directory

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/EA783946-4C4D-4B77-A8FA-C411594EC29E/20161207-120152.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
1. Install Docker onto a Mac (El Capitan).
2. At the command line, type: docker info.
3. Error above.

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
See above.
  1. ...
  2. ...

**Comment by rogaha** [comment]
@davidmpatterson it looks like the `docker` client is pointing to `docker-machine` configurations. Can you please verify if you have environment variables forcing that `path`?

**Comment by murphyke** [comment]
The same thing happened to me, and it turned out that I had `DOCKER*` environment variables set in my environment from much earlier experiments. When I did away with these, things started working.

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
