### ISSUE TITLE
My main disk is almost full... 😰

### ISSUE THREAD

**Issue by TofPlay** [docker/for-mac#1024]
Hi
My main disk is almost full. Can I move docker images to another disk?

**Comment by SimonHoenscheid** [comment]
Refers to #1003

**Comment by rogaha** [comment]
@TofPlay  just a heads up, we are planning to add that feature to the next `beta` release. We will keep you posted.

**Comment by rogaha** [comment]
It's worth mentioning this issue https://github.com/docker/for-mac/issues/371 is fixed in the latest `beta` version.

**Comment by TofPlay** [comment]
@rogaha I do not know if it's a coincidence or not but I have used Docker quite intensively lately. 2 days ago my mac started to stop seeing my disks and have strange behavior. It had never happened before. To restore the system I was obliged to reinstall a backup. Since then I hesitate to reuse Docker. Can Docker make my config unstable?

**Comment by TofPlay** [comment]
> It's worth mentioning this issue #371 is fixed in the latest beta version.
@rogaha thank you for following 🙂

**Comment by dsheets** [comment]
This was fixed in Beta 33 and should reach the stable channel in the next release in a week or two.
