### ISSUE TITLE
Throw error when users add the protocol to the start of insecure registries

### ISSUE THREAD

**Issue by kwerey** [docker/for-mac#1026]
When adding insecure registries in Docker for Mac, the daemon expects input in the format  'mydomain.com:5000'. If a user adds an insecure registry through the Docker for Mac UI in the format 'https://mydomain.com:5000', that endpoint will be added to the list of insecure registries, but the daemon will not actually disable certificate verification for the host - it doesn't understand input with a protocol at the start. This means the user will still get certificate errors. 

### Expected behavior

If a user doesn't read the example 'mydomain.com:5000' very closely, just copies and pastes the registry endpoint as 'https://mydomain.com:5000', the Docker client should:

* EITHER parse that value to strip off the protocol before passing as the --insecure-registries flag, then successfully treats that registry as insecure
* OR throw an error when saving that user input asking them to provide the registry in HOSTNAME:PORT format.
 
### Actual behavior

Docker accepts the input without erroring, but will still throw a certificate error when you attempt to login in to the registry.

Passing the registry endpoint with the protocol on docker login does actually work, so it's not intuitive that giving docker 'https://mydomain.com:5000' is a valid parameter for the login but not for the --insecure-registries flag.

### Information

Docker for Mac:
Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

Given an entry formatted like 'https://mydomain.com:5000' under Insecure Registries, I get output that looks like this

    $ docker login -uexample https://mydomain.com:5000
    Password:
    Error response from daemon: Get https://mydomain.com:5000/v1/users/: x509: certificate signed by unknown authority

### Steps to reproduce the behavior

  1. Add a registry with a cert Docker doesn't recognise to 'Insecure Registries' with HTTPS prefix.
  2. Restart docker daemon
  3. Attempt docker login

You will see a certificate error: 'Error response from daemon: Get ${reponame}/v1/users/: x509: certificate signed by unknown authority'

### As a user hitting this error, how do I fix it?

It's easy! There isn't any missing functionality here, it's just that it's easy to enter the registry in a format Docker for Mac doesn't understand, and it can be figure that that's what's happened:

1. In the 'Insecure Registries' tab on the GUI, remove the protocol ('https://') from the start of your registry, leaving just 'myregistry.domain.com:port'.
2. click 'apply and restart' and wait for the docker daemon to get up and running again.

**Comment by kzettlmeier** [comment]
I also have the same issue on our end.  We run an internal docker server via Nexus and the registry is signed by an internal CA certificate.  The same steps @kwerey provided give me the same error message from the daemon.

**Comment by kwerey** [comment]
Since my bug report is long: if you're getting that error, the fix for you as an end user is this:

1. remove the protocol ('https://') from the start of your registery, leaving just 'myregistry.domain.com:port'. 
2. click 'apply and restart' and wait for the docker daemon to get up and running again.

There isn't any missing functionality, and this is exactly what the interface and examples tell you to do.

It's just that if you're new to docker and if you don't think of 'URLs' and 'the hostname & port' as two different things, it's easy to enter the registry wrong and hard to pin down the error after the fact.

**Comment by kzettlmeier** [comment]
@kwerey Thank you for the fix.

**Comment by justincormack** [comment]
This looks somewhat like this Go bug fixed in 1.7.5 https://github.com/golang/go/issues/18688

**Comment by kwerey** [comment]
That'd definitely fixes the root cause of me having to add a registry as insecure - nice.

The go fix will mean I'm not fussed about where this report ends up, but I'll leave it open for now because it's kinda orthogonal to this bug.

This one is suggesting clearer error handling when users enter the endpoint for their registry with a protocol to start with, so it'll still be relevant for users who haven't added their registry's issuing CA as trusted. Feel free to close this as trivial or leave it as a tiny beginner-level UI fix as you so desire, fine by me either way.

**Comment by justincormack** [comment]
The go update will be in 1.13.1
