### ISSUE TITLE
Docker uninstallation failure

### ISSUE THREAD

**Issue by EvanZhouTHU** [docker/for-mac#1027]
### Information

Diagnostic ID: 95A5BACD-4CFB-4C80-B92A-86477A07F33F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.1 (Build 16B2555)

### Steps to reproduce

1. ...
2. ...

**Comment by rogaha** [comment]
@EvanZhouTHU do you mind trying to perform a `reset to factory` before doing the `uninstalling`?

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by dsheets** [comment]
Docker for Mac 1.12.0-a is not supported on macOS Sierra 10.12. Please upgrade to a newer version.

**Comment by EvanZhouTHU** [comment]
I tried to upgrade from Docker, however, it would fail. So I removed the docker and reinstall a new one. I am having fun with Docker now. Many thanks!
