### ISSUE TITLE
All docker-cli commands failing: Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by gmgauthier** [docker/for-mac#1028]
### Expected behavior
proper responses from cli

### Actual behavior
Error response from daemon: Bad response from Docker engine

### Information
OSX Dock icon is permanently "starting" state. 

- Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.10.5 (build: 14F1909)
logs: /tmp/BB8A3D3E-6BA4-4FDA-8330-84A1E1B58347/20161209-133458.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
The logs in the VM have:
```
time="2016-12-09T13:34:30.956982390Z" level=debug msg="Using graph driver aufs" 
...
time="2016-12-09T13:34:31.330155576Z" level=debug msg="Failed to load layer sha256:d7660965c52051da7cc5830daea13ba7c9187135cad050f3c61507febdb93b28: failed to get diff id for sha256:d7660965c52051da7cc5830daea13ba7c9187135cad050f3c61507febdb93b28: invalid checksum digest format" 
time="2016-12-09T13:34:31.338409141Z" level=debug msg="Max Concurrent Downloads: 3" 
time="2016-12-09T13:34:31.339143809Z" level=debug msg="Max Concurrent Uploads: 5" 
time="2016-12-09T13:34:31.402313618Z" level=debug msg="Cleaning up old mountid : start." 
time="2016-12-09T13:34:31.403436333Z" level=fatal msg="Error starting daemon: layer does not exist" 
```
Unfortunately the data in `aufs` in `/var/lib/docker` seems to have become corrupted and this prevents the docker daemon from starting. Could you try "Whale menu" -> "Preferences" -> "Reset" -> "Reset to factory defaults"? Unfortunately your containers and images will need to be rebuilt.

Unfortunately this can happen (occasionally) with `aufs` but in the future we should be switching to `overlay2` which should be more reliable. Sorry for the inconvenience. Let me know if it happens again.
