### ISSUE TITLE
Docker swarm service died with "context deadline exceeded", can't recover again with reinstall or upgrade to 1.12.3

### ISSUE THREAD

**Issue by diameter2000** [docker/for-mac#1030]
### Expected behavior
Docker swarm service should be always up and running per defined replication instances

### Actual behavior

Docker version: 1.12.1 

The docker service can't run and reported "context deadline exceeded", upgraded to docker 1.12.3, it is a little better doesn's show this error but service instance always shows 0 and always in preparing. After serveral rounds quit and restart docker service, the docker service can't be launch anymore even with reinstallation. 

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.10.5 (build: 14F27)
logs: /tmp/C154D448-9E97-42C6-8C42-678E66DF165F/20161211-220450.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
Diagnostic ID:
C154D448-9E97-42C6-8C42-678E66DF165F

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

Initially we are creating swarm service on docker 1.12.1, it is a single node environment (one single node as worker and manager), it is a normal service which run official redis/postgres/mongo something like below:

docker service create  --network mss_overlay_network --name mongo --mount src=vol_mss_mongo,dst=/data/db --replicas 1  -p 27017:27017  mongo
docker service create --network mss_overlay_network --name redis   --mount src=vol_mss_redis,dst=/data --replicas 1  -p 6379:6379 redis redis-server --appendonly yes
docker service create --network mss_overlay_network --name postgres --mount src=vol_mss_postgres,dst=/var/lib/postgresql/data/pgdata  --replicas 1   -p 5432:5432  -e PGDATA=/var/lib/postgresql/data/pgdata -e POSTGRES_PASSWORD=Igtcorp123 postgres
docker service create --network mss_overlay_network --name rabbitmq --replicas 1   -p 5672:5672 rabbitmq

which ran well before and then went into the unrecoverable state without much touch(Except containers stop and start), reports ""context deadline exceeded" for any service related operation, just like other people met(https://forums.docker.com/t/how-to-kill-a-broken-swarm/19352/5). 

Then I updated to latest version 1.12.3, it doesn't report the previous error, but the related service instance can't be started and always in preparing state when I check with "docker service ps", even I remove the service and recreate them, the service can't be launched succesfully. When I did that several times, I found the docker service become to always in "starting" status and can't restart correctly, uninstall docker and reinstall can't resolve the problem.
[20161120-225143.tar.gz](https://github.com/docker/for-mac/files/644494/20161120-225143.tar.gz)
[20161211-220450.tar.gz](https://github.com/docker/for-mac/files/644498/20161211-220450.tar.gz)
[Uploading 20161211-220450.tar.gz…]()

**Comment by djs55** [comment]
To completely reinstall Docker for Mac you need to:

- open the Whale menu in the menu bar, click on "Preferences...", click on "Reset" and then "Reset to factory defaults"
- select "Reset docker"
- select "Restart"
- when prompted, authenticate so Docker can install the privileged helper
- say "No" when asked about importing from docker toolbox

The result should be a completely clean system, with no swarm configuration. It's not enough to drag Docker to the trash because the VM's disk would survive, containing the swarm configuration. I recommend also not importing a disk from toolbox, because that may also have an old swarm configuration on it.

Could you let me know if that helps? If not, could you upload a fresh diagnostics report from after the reinstall?

Thanks for your report!

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
