### ISSUE TITLE
Docker exits suddenly on MAC

### ISSUE THREAD

**Issue by chengxing1987** [docker/for-mac#1032]
### Information

Diagnostic ID: 0A658CB1-B1FF-4313-A376-1BAB469AAAAD
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.1 (Build 16B2555)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by jeanlaurent** [comment]
Hi @chengxing1987 OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.
