### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ranbrandes** [docker/for-mac#1033]
### Information

Diagnostic ID: C137575F-207A-4009-8A3F-29258F9ACC6E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by jeanlaurent** [comment]
Hi @ranbrandes, there is not much description, and it seems you didn't upload the report.
Not much we can do with that information.

Please re-open with the diagnostic info uploaded or a more descriptive text of the issue you're facing.
