### ISSUE TITLE
Docker for Mac crashes when run overnight

### ISSUE THREAD

**Issue by bmbroom** [docker/for-mac#1034]
### Expected behavior

Docker for Mac cli is responsive after being left running overnight.  Restarting Docker for Mac (and all the running containers) should not be required.

### Actual behavior

Docker for Mac is completely unresponsive after being left running overnight.  Requires restart.

### Information

Hardware Overview:

  Model Name:	Mac Pro
  Model Identifier:	MacPro6,1
  Processor Name:	Quad-Core Intel Xeon E5
  Processor Speed:	3.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	10 MB
  Memory:	64 GB
  Boot ROM Version:	MP61.0116.B11
  SMC Version (system):	2.20f18
  Illumination Version:	1.4a6
  Serial Number (system):	F5KML0BJF9VM
  Hardware UUID:	FAF3C81A-8A1F-56D4-B494-255322B454AA

System Software Overview:

  System Version:	OS X 10.10.3 (14D136)
  Kernel Version:	Darwin 14.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	BCBMH01281J1EUE
  User Name:	
  Secure Virtual Memory:	Enabled
  Time since boot:	4 days 2:32

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.0-rc3-beta32 (9cf974f9e)
OS X: version 10.10.3 (build: 14D136)
logs: /tmp/9518ADD2-2AEF-434A-9083-6DC4A695530D/20161212-094311.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Leave Docker for Mac running overnight / over the weekend.
  2. Attempt to execute docker cli command.

This problem has been going on for a very long time (many beta releases).

**Comment by ottumm** [comment]
I am seeing this also.

**Comment by djs55** [comment]
@bmbroom I notice these on the VM's console:
```
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [dockerd:1837]
BUG: workqueue lockup - pool cpus=0-3 flags=0x4 nice=0 stuck for 211544s!
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1837]
BUG: workqueue lockup - pool cpus=0-3 flags=0x4 nice=0 stuck for 211574s!
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1837]
```
There have been some recent bugs in the block layer of the hypervisor which could cause deadlock when the VM tries to free space using TRIM. These could manifest as a `soft lockup` kernel error. Could you try to reproduce on the latest beta (33.1 is out and beta 34 is due out later today)/

**Comment by bmbroom** [comment]
@djs55 I've been on beta34 since I saw your comment.  So far no lockups or messages on the console.  I'll update again next week unless I see something earlier.

**Comment by djs55** [comment]
Thanks for letting me know-- I'm glad it's working so far!

**Comment by bmbroom** [comment]
@djs55 Still no lockups or messages on the console.  Good news I guess.  Did something relevant change in beta34?

**Comment by djs55** [comment]
Between beta 32 and 34 we upgraded the Linux kernel from 4.8.12 to 4.8.15, Docker from 1.13.0-rc3 to 1.13.0-rc4 and fixed some performance issues with TRIM which could result in deadlocks (which could manifest as a "soft lockup").

Given that all looks good now I'll close this issue. Please reopen if it recurs!
