### ISSUE TITLE
Disk Out of Space Issues (was: GUI preferences restart behavior ) 

### ISSUE THREAD

**Issue by safaci2000** [docker/for-mac#1036]
### Expected behavior

Ideally I should be able to save the preferences on the GUI and apply once I'm done with all my changes.

### Actual behavior

If I make a change in any of the tabs it forces a docker restart.  Example.  Change Memory Allocation to 4 GB, restart, Add an insecure registry , restart.

It would be nice if you could apply all the settings you want w/o having to restart for every setting you change.

### Steps to reproduce the behavior

1.  Change a setting in one tab
2. Go to a different tab and not have to restart.

**Comment by jeanlaurent** [comment]
We understand that you are forced to restart many time when you're adding many settings at once. 
are you regularly channng many settings in different panels often ?

Can you give us a few examples ?

**Comment by safaci2000** [comment]
Part of the issue is that, one of my containers is around 30 gb or so once it's built. Since I'm having issue cleaning up unused space. If I build the image twice docker is out of space and I'm forced to do a factory reset. 

At that point the pattern above kicks in fairly regularly. I'd say 2-3 times a week I go through today process. 

Another solution would be the ability to export settings and import settings from a JSON file.

**Comment by safaci2000** [comment]
I commented on this thread but for reference regarding the out of space issue.  

https://forums.docker.com/t/consistently-out-of-disk-space-in-docker-beta/9438

**Comment by djs55** [comment]
Regarding the out-of-space issue: are you using the stable or the beta channel? The beta channel has a number of space-related fixes including

- `docker image prune`: to delete dangling images
- `fstrim` every 15 minutes and the disk is compacted on shutdown

Could you share reproduction steps which demonstrate the problem? If not could you share the output of
- `docker ps -a`: list all (including stopped) containers
- `docker image ls`: list all images

It sounds like the space issue is the root cause of the problem-- if we can fix that then perhaps the UI change becomes less essential.

**Comment by safaci2000** [comment]
I'm on the beta version.  I'll try the mentioned fixes.  I think docker image prune might do it if it works as advertised.

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by safaci2000** [comment]
This is still an issue for me.  Sorry fro the delay in response.

I run the following before building:

docker_image_cleanup.sh 

#!/usr/bin/env bash

for item in $(docker ps -aq); do
    docker stop $item
    docker rm $item
done

for item in $(docker images --filter dangling=true -q); do
    docker rmi $item
done

and when I try to build again.

Stopping postgresql-9.5-5433 service: [  OK  ]
ERROR: Service 'demodata' failed to build: Error processing tar file(exit status 1): write /postgresql/pg_data/9.5/base/16384/882255: no space left on device
make: *** [demodata] Error 1

My docker version is:  Version 1.13.0-rc5-beta35 (14875)  The initial ticket is misleading for this issue, but the out of space issue is still a problem at least for me.

**Comment by dsheets** [comment]
@safaci2000 could you please run `docker run --rm alpine df -h` and report the results? It would also be helpful to run :whale: ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload` and report the diagnostic ID back here. Thanks!

**Comment by safaci2000** [comment]
@dsheets it usually takes a few days to re-generate the error, I'll run the command you requested as soon as I see the symptoms again.

For reference the image I'm using is about 20GB.

ms/db                    demodata            6d92afe20c5e        6 hours ago         20.9 GB

it's probably a bit bigger then the average docker container size, which might be why i'm seeing this more then others?

**Comment by dsheets** [comment]
With images that big, you may be interested in increasing your disk image size. See <https://github.com/docker/for-mac/issues/371#issuecomment-262826610> for work-around instructions until the GUI for disk image management is ready.

**Comment by safaci2000** [comment]
@dsheets Thanks for that link.  I added that to our internal doc.  I've increased the disk size and will let it go for a few days.  Give me a few days to confirm and we can close out this issue.  

Thanks for your help with this issue.

**Comment by safaci2000** [comment]
This is looking better.  You can close it.  Thanks for referencing me to the instructions on how to increase the disk size, though I wish it was a bit easier to do that.
