### ISSUE TITLE
Initial Disk Size

### ISSUE THREAD

**Issue by safaci2000** [docker/for-mac#1037]
### Expected behavior

Allow the user to customize what the size of qcow disk image.

### Actual behavior

Extending the initial size beyond the default is .. annoyingly difficult under the best of circumstances.

### Information

I understand that growing the file size can be tedious / difficult but I should have the option to specify a larger size if I accept that all my docker images will be wiped out.

### Steps to reproduce the behavior

Docker factory reset and validate that there is no option to override the default disk size.

**Comment by jeanlaurent** [comment]
We're currently working on UI element to enable that more easily. 
In the next couple betas you should have it.

**Comment by Eyesonly88** [comment]
@jeanlaurent is there a way to do it from the command line (for now until the UI elements are shipped)?

**Comment by tompetersjr** [comment]
This is great.  As of right now it looks like this feature is capped at 64 GB.  Are there plans to go higher?  I currently have a use case for 120 GB.

**Comment by pgayvallet** [comment]
@tompetersjr We are limiting the cap depending on your actual free space. If you remove data from your disk you should be able to increase the disk size more.

**Comment by pgayvallet** [comment]
This is actually available on latest edge & stable.

Closing.
