### ISSUE TITLE
Show the number of running containers in Docker OS X menu tool

### ISSUE THREAD

**Issue by RickWong** [docker/for-mac#1038]
### Expected behavior

Docker menu tool should show the number of containers that is currently runnning.

### Actual behavior

Docker just says it's running.

![screen shot 2016-12-13 at 11 31 47](https://cloud.githubusercontent.com/assets/40102/21136871/c05ee07a-c127-11e6-9cf9-48d05c29d33e.png)

Bonus: Clicking on the status opens Kitematic.

Thanks for reading!

**Comment by sic2** [comment]
Having a list of docker images could be helpful too

**Comment by jeanlaurent** [comment]
We have plan to give easier access to those informations.
No release date as of yet as we're working on it.

**Comment by RickWong** [comment]
For anyone interested in this. I built "_Captain_" a menu bar app for Docker on Mac. 

**Link**
https://getcaptain.co/

**Screenshot**
<img width="399" alt="screen shot 2017-02-06 at 16 38 46" src="https://cloud.githubusercontent.com/assets/40102/22655548/c7f76b9c-ec90-11e6-89ac-7f916bb648ea.png">

**Comment by sic2** [comment]
I would keep this issue opened, since there are plans to have this feature within the docker desktop app anyway.

**Comment by mcahornsirup** [comment]
I'am using captain for some time and it is really useful. Merge captain into the docker app, please

**Comment by alex-mohemian** [comment]
I would also vote for reopening this.
