### ISSUE TITLE
Can't disable usage statistics

### ISSUE THREAD

**Issue by ofrzeta** [docker/for-mac#1039]
### Expected behavior

user should be able to disable usage statistics (or even better Docker should be shipped with stats disabled – I think it's also the law in the EU)

### Actual behavior

"Send usage statistics" is grayed out but the radio button is checked. Post install dialog says "we send usage statistics". 

### Information

Version 1.13.0-rc3-beta32 (14523)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jeanlaurent** [comment]
Hi @ofrzeta,

you're on the `beta` channel, if you want to do so, please use the `stable` channel

On the `beta` channel this is disabled as we are gathering feedbacks has this version contains new features we are working on, but is not necessarily fully tested and bugs, crashes and issues are more likely to occur with the beta app.

Check the FAQ on [stable and beta channels](https://docs.docker.com/docker-for-mac/faqs/#stable-and-beta-channels)
