### ISSUE TITLE
Docker for Mac crashes with NGINX

### ISSUE THREAD

**Issue by hashneo** [docker/for-mac#104]
### Expected behavior
Docker should not crash

### Actual behavior
Docker crashes (regularly) and restarts

### Information

Diagnostic ID: CA6649CD-A92B-47D5-94D1-D088B724951A
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
I'm running multiple NGINX containers, 1 is using a mounted volume to serve web content. Changing the web content and reloading the pages frequently sometimes causes hyperkit to terminate  

[com.docker.hyperkit_2016-08-03-073017_STEVENT-MBP.crash.txt](https://github.com/docker/for-mac/files/399682/com.docker.hyperkit_2016-08-03-073017_STEVENT-MBP.crash.txt)
[com.docker.hyperkit_2016-08-03-072741_STEVENT-MBP copy.crash.txt](https://github.com/docker/for-mac/files/399684/com.docker.hyperkit_2016-08-03-072741_STEVENT-MBP.copy.crash.txt)

2. ...

**Comment by dsheets** [comment]
@ijc25 this looks like an `abort` in the `vsock:tx` thread.

**Comment by ijc25** [comment]
`docker-system.log` in the diagnostics contains:

> TX: select() failed 9: Bad file descriptor

Meaning the `select()` in the tx thread had returned `EBADF`.

Right before that is:
> [com.docker.slirp][2573] <Error>: Socket.Pipe.write /Users/staylor/Library/Containers/com.docker.docker/Data/*@*connect: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
> [com.docker.slirp][2573] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")

Which might also be related.
