### ISSUE TITLE
Docker crashes under heavy load

### ISSUE THREAD

**Issue by bunchjesse** [docker/for-mac#1040]
I'm seeing docker crash when doing a lot of FS work through host mounts (like developing a CMS-based web site locally).

Here is the error I get:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 197, in watch_events
  File "compose/project.py", line 343, in events
  File "site-packages/docker/client.py", line 259, in _stream_helper
  File "json/__init__.py", line 338, in loads
  File "json/decoder.py", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 2 column 656 (char 668 - 1323)
```

At this point, my containers stop and the Docker app reports that Docker is "restarting". After a restart and I start my containers again, things return to normal until the next crash. This happens several times per day.

### Information

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/0877108C-FF1A-48CE-BAFE-3AFE4C521EA1/20161213-103742.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by dsheets** [comment]
Hi @bunchjesse, that sounds very frustrating and I apologize that this defect is effecting your work so much. I've identified the issue and written a patch that I believe will fix it. I'll let you know when it reaches the Beta channel (likely beta 34 or 35).

**Comment by bunchjesse** [comment]
Thanks, @dsheets. I appreciate your work!

**Comment by dsheets** [comment]
The fix was released in Beta 34. Please open a new issue if you continue to experience problems.
