### ISSUE TITLE
Doesn't keep docker-compose up to date 

### ISSUE THREAD

**Issue by avindra** [docker/for-mac#1041]
Redirecting from https://github.com/docker/compose/issues/4244

1. DFM version:

![screen shot 2016-12-13 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/126848/21161227/b480d528-c155-11e6-882b-b84b56388301.png)

2. Checking for updates:

![screen shot 2016-12-13 at 5 01 03 pm](https://cloud.githubusercontent.com/assets/126848/21161243/c63ecc8e-c155-11e6-948a-c28b248218b5.png)

3. 
```
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
```

**Comment by justincormack** [comment]
There will be a stable release with 1.9.0 shortly.

**Comment by avindra** [comment]
Thanks. So, is the documentation incorrect in saying that d4m will keep compose up to date?

It seems the releases are just bundled together ?

**Comment by jeanlaurent** [comment]
Docker for mac by updating itself, keep the components it bundle up to date.
In other words : You won't have an update of compose without an update of Docker for mac.

**Comment by avindra** [comment]
@jeanlaurent : Understood. Is there any plan to enhance the update check for a future release?

**Comment by dsheets** [comment]
Docker Compose 1.9.0 was bundled with Docker for Mac 1.12.5.

**Comment by avindra** [comment]
Eh, bundling doesn't really address the problem of being able to update before a bundled release. But good to have this issue for documentation sake. It's not very clear in the UI.
