### ISSUE TITLE
Docker cannot resolve proxy 

### ISSUE THREAD

**Issue by kaskavalci** [docker/for-mac#1042]
### Expected behavior
Resolving proxy addresses both in Docker configuration and containers

### Actual behavior
Docker cannot resolve proxy when connected to VPN. My proxy server can only be resolved when using VPN's DNS servers but docker is unable to resolve them.

```
$ docker pull redis
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: http: error connecting to proxy http://proxy.company.io:8080: dial tcp: lookup proxy.company.io on 192.168.65.1:53: read udp 192.168.65.2:42562->192.168.65.1:53: i/o timeout
```
When changing proxy to IP address in docker config, pulling is successful. 

### Information
It seems docker cannot even upload diagnostic but here is the Diagnostic ID: `4C9609A6-3859-4678-883C-F52E59A7EE8C` 

```
Docker for Mac: version: 1.13.0-rc3-beta32 (9cf974f9e)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/4C9609A6-3859-4678-883C-F52E59A7EE8C/20161214-153554.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior

1. Set a proxy in docker config. (I also use VPN, which means proxy can only be resolved with VPN's DNS server)
2. Try to pull any image

**Comment by djs55** [comment]
Thanks for making the separate ticket. As you say, the diagnostics upload also failed. Could I ask you some questions instead?

Could you show me the output of the following commands (feel free to anonymise, I don't need the specific addresses):
```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ git reset --hard
HEAD is now at 8c2aab6 last-start-time changed at 1481728664
$ cat com.docker.driver.amd64-linux/slirp/dns 
# { Addresses: 10.14.32.10; Order: 0; Zones:  }
nameserver 10.14.32.10
order 0
timeout 2000
# { Addresses: 10.10.0.1; Order: 100000; Zones: example.com }
nameserver 10.10.0.1
zone example.com
order 100000
timeout 2000
```
Do you see the VPN DNS servers listed in that file?

If not:
- do they appear in `scutil --dns`?

If yes:
- there may be a problem with the `zone` `order` or `timeout` keys.

BTW for debugging, it's possible to modify that file and then

```
$ git add com.docker.driver.amd64-linux/slirp/dns
$ git commit -s -m 'temporary DNS update'
```
A change can be tested, although it will be overwritten the next time the network settings on the Mac change.

**Comment by kaskavalci** [comment]
Hi @djs55 thanks for your quick reply. VPN DNS servers appear in the file. I added comments there as well, to indicate public DNS and VPN DNS servers

```
$  cat com.docker.driver.amd64-linux/slirp/dns
# { Addresses: xx.xx.xx.xx, yy.yy.yy.yy; Order: 0; Zones:  } # This is public DNS
nameserver xx.xx.xx.xx
order 0
timeout 2000
nameserver yy.yy.yy.yy
order 0
timeout 2000
# { Addresses: zz.zz.zz.zz, kk.kk.kk.kk; Order: 0; Zones: xxx } # This is VPN DNS
nameserver zz.zz.zz.zz
zone xxx
order 0
timeout 2000
nameserver kk.kk.kk.kk
zone xxx
order 0
timeout 2000
```

I commented out the public dns and left only VPN DNS however pulling still doesn't seem to work. I'm open for other suggestions.

**Comment by djs55** [comment]
In the error message `http://proxy.company.io:8080: dial tcp` -- is `proxy.company.io` related to the `zone xxx` in the file?

For example if the file had `zone company.io` then it should have sent queries for `proxy.company.io` to the VPN DNS.

If the `zone xxx` is unrelated to the query `proxy.company.io` then it should have sent queries in priority order (lowest first). However I notice both your servers have priority `0`. This is a bit suspicious. Could you check what order they are listed in `System Preferences` -> `Network` on the list down the left?

I believe the priorities come from the System Config database on the Mac. Could you show me the shape of:

The global DNS settings:
```
$ echo show State:/Network/Global/DNS | scutil
<dictionary> {
  DomainName : cam.docker.com
  ServerAddresses : <array> {
    0 : 10.14.32.10
  }
}
```
and then the per-service DNS settings: ( I don't need the UUIDs themselves, but it's a two step process to look up the DNS settings )
```
$ echo list | scutil | grep DNS | grep Service
  subKey [77] = State:/Network/Service/D1B8B972-4B47-424E-80B6-B56665D0C3EB/DNS
  subKey [80] = State:/Network/Service/F15B7CDE-7AF8-44B5-9423-D6649AC15754/DNS
```
for each UUID:
```
$ echo show State:/Network/Service/D1B8B972-4B47-424E-80B6-B56665D0C3EB/DNS | scutil
<dictionary> {
  SearchDomains : <array> {
    0 : example.com
  }
  ServerAddresses : <array> {
    0 : 10.10.0.1
  }
  SupplementalMatchDomains : <array> {
    0 : example.com
  }
  SupplementalMatchOrders : <array> {
    0 : 100000
    1 : 100000
    2 : 100000
  }
}
```

If you want to make an experimental modification, try deleting the lines starting `zone` and make the public DNS server have `order 1000`. This ought to prioritise the VPN servers for all traffic.

**Comment by kaskavalci** [comment]
Hi, 

sorry for bad masking. Yes zone is like `tlv.company.io` and proxy `proxy.company.io`. In my system preferences only open DNS is listed. Here is the commands you asked. `
F5NetworksServicePPP` is my VPN service. 

```
$ echo show State:/Network/Global/DNS | scutil
<dictionary> {
  ServerAddresses : <array> {
    0 : 208.67.222.222
    1 : 208.67.222.220
  }
}
$ echo list | scutil | grep DNS | grep Service
  subKey [81] = State:/Network/Service/0947909A-15BD-4490-B3F9-CF7A33C6CDAF/DNS
  subKey [88] = State:/Network/Service/F5NetworksServicePPP/DNS
$ echo show State:/Network/Service/0947909A-15BD-4490-B3F9-CF7A33C6CDAF/DNS | scutil
<dictionary> {
  ServerAddresses : <array> {
    0 : 208.67.222.222
    1 : 208.67.222.220
  }
}
$ echo show State:/Network/Service/F5NetworksServicePPP/DNS | scutil
<dictionary> {
  ServerAddresses : <array> {
    0 : z.z.z.z
    1 : k.k.k.k
  }
  SupplementalMatchDomains : <array> {
    0 : tlv.company.io
    1 :
  }
}
```

**Comment by kaskavalci** [comment]
When leaving order as is and removing zone seems to solved it. Again my proxy and zone is something like this:

Zone: `tlv.company.io`
Proxy: `proxy.company.io`

**Comment by samoht** [comment]
@kaskavalci would you be able to test your VPN with the latest release of Docker for Mac? Both the beta and stable channels have seen multiple improvements related to DNS handling of VPN networks. Thanks!

**Comment by kaskavalci** [comment]
@samoht I'm using 1.13.0 stable channel and confirm that docker cannot access to Internet when VPN is on and proxy is configured. 
```
Error response from daemon: Get https://registry-1.docker.io/v2/: http: error connecting to proxy http://proxy.wdf.sap.corp:8080: dial tcp: lookup proxy.company.io on 192.168.65.1:53: no such host
```
When connected to corporate network with proxy, docker can establish internet access.

**Comment by dave-tucker** [comment]
@kaskavalci TBH this looks like it could be a problem with your VPN configuration in OSX.
With the settings you have listed, only DNS requests for hosts in the domain `tlv.company.io` will be sent to your VPN DNS servers.

E.g

- `proxy.company.com` will use public DNS
- `proxy.tlv.company.com` will use VPN DNS

**Comment by dave-tucker** [comment]
As a follow up to the above comment, I just noticed that there is an empty record in `SupplementalMatchDomains` that follows `tlv.company.io`
@djs55 could this have special meaning? E.g use this server for ALL queries?

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
