### ISSUE TITLE
Provide a stop button

### ISSUE THREAD

**Issue by asarkar** [docker/for-mac#1045]
### Expected behavior
A stop button to stop the docker daemon without having to quit the Docker app.
### Actual behavior
No stop button, only restart. The only way to stop Docker daemon is to quit the app.
### Information
Docker for Mac Version 1.12.3 (13776)
### Steps to reproduce the behavior

  1. Start the app.
  2. Look for stop option.

**Comment by jeanlaurent** [comment]
hi @asarkar this is by design, see https://github.com/docker/for-mac/issues/665#issuecomment-262561042

**Comment by asarkar** [comment]
@jeanlaurent Looks like I'm not the only one looking for this feature. I understand that the original design decision but the best design provides features that the users want, not what you think they don't want.
Can we reopen this ticket and bring it up for discussion?
