### ISSUE TITLE
Docker gets stuck restarting

### ISSUE THREAD

**Issue by jefflage** [docker/for-mac#1047]
### Expected behavior
Anytime I restart my machine, or restart Docker, it should successfully start.

### Actual behavior
Randomly and occasionally, Docker fails to restart.  It stays for ever in the 'starting' state.  Reseting to factory defaults does not resolve it.  Only an uninstall and reinstall does.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/61EED1DB-2F04-4078-842C-6AE336877E01/20161215-114901.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by Chive** [comment]
@jefflage rolling back to 1.13.0-rc3-beta32 worked for me - you can still get it from here: https://download.docker.com/mac/beta/Docker.dmg

**Comment by raysuliteanu** [comment]
I started having a similar problem with Docker stuck starting ever since I applied a recent macOs update.

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/5A2D1C0A-6A54-40D0-82BD-A9032AD95974/20161215-164209.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by gcoonrod** [comment]
I am seeing the same behaviour.

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/29E49AF1-13AC-4EAD-BD0D-EC57A7A4605E/20161219-125915.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by djs55** [comment]
@jefflage I think the volume sharing daemon failed during application start:
```
Dec 15 11:48:32 hse-nyc-hd-04 Docker[com.docker.osxfs][6764] <Error>: Fatal unexpected exception: (Failure int_of_string)
```
and then unsurprisingly we have the corresponding error on the VM console
```
 * ERROR: transfused failed to start
```
I notice you're using 1.12.3. Could you reproduce with the most recent version of the code in beta 34 and upload a fresh diagnostics?

**Comment by djs55** [comment]
I think the other issues reported here are actually different problems that superficially look the same. Could everyone else file a fresh ticket with diagnostics? Thanks!

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
