### ISSUE TITLE
Docker Cli: No response after abort docker-compose build

### ISSUE THREAD

**Issue by irgalieri** [docker/for-mac#1048]
### Expected behavior

After abort ```docker-compose build```, I expect the docker cli response. For example if I run ```docker --help```, I expect see the output.

### Actual behavior

The docker cli, freeze after abort ```docker-compose build```

### Information

Screen Shots:

**Runnig Docker cli and wait 10s, then abort:**
![screen shot 2016-12-15 at 13 30 07](https://cloud.githubusercontent.com/assets/10157258/21236896/bee7bdda-c2ca-11e6-8ec0-b5b634b7814b.png)

**Diagnose & Feedback Screen:**
![screen shot 2016-12-15 at 13 25 21](https://cloud.githubusercontent.com/assets/10157258/21236681/1059d168-c2ca-11e6-9fc9-73bbc8370f7c.png)
![screen shot 2016-12-15 at 13 25 34](https://cloud.githubusercontent.com/assets/10157258/21236682/105d2b1a-c2ca-11e6-95f5-a021d179b50f.png)

### Steps to reproduce the behavior

  1. run ```docker-compose build```
  2. before this process finish, abort the process
  3. the try to run ```docker --help```

**Comment by jeanlaurent** [comment]
For future references this is `6CF2BFB4-4034-4442-934C-5F98BFAA6656`

**Comment by jeanlaurent** [comment]
We actually release beta33 yesterday, and we pulled it off, because of a bug you're suffering from.

Our goal is to release a beta33.1 with a fix for your very specific issue within the day.
If you want to continue working right now, I suggest you install [beta32](https://download.docker.com/mac/beta/1.13.0.14523/Docker.dmg).

We'll keep you posted here of the resolution anyway.

**Comment by irgalieri** [comment]
Thx so much.

**Comment by jeanlaurent** [comment]
Beta 33.1, containing a fix for your issue is now available.

**Comment by irgalieri** [comment]
I tested the version beta 33.1 and the problem was resolved. Thx so much.

**Comment by balrajsingh** [comment]
Thanks for the report and thanks for confirming that it is fixed.  Closing.
