### ISSUE TITLE
docker for mac crash after run a while

### ISSUE THREAD

**Issue by wenpp** [docker/for-mac#1055]
### Information

Diagnostic ID: 3D5E526F-AB57-4A01-A2FD-FB718A335825
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.1 (Build 16B2555)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
I notice you're using macOS 10.12.1 but Docker for Mac version 1.12.0.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

**Comment by djs55** [comment]
BTW where did you get your `Docker.dmg` file? Is it a cached copy? the current stable version on the website is currently 1.12.5 -- I'd like to make sure the web download is working properly. Thanks!
