### ISSUE TITLE
Docker 'run nginx' hangs

### ISSUE THREAD

**Issue by dgonzalez** [docker/for-mac#1056]
### Expected behavior

Container nginx runs

### Actual behavior
Frozen terminal. I can ctrl + C but container does not run (verified with docker ps in another terminal).

### Information

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/DD580A5E-4F93-48DB-928C-036CE3326B92/20161219-110531.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Run `docker run nginx` (will pull the image but wont run it.

**Comment by dgonzalez** [comment]
factory reset few times gets it working again but I'd be curious to see why this keeps happening so please, if you need more info I will do what you require.

**Comment by djs55** [comment]
Thanks for your report. Unfortunately the latest upload must have failed -- I can only find a diagnostics upload with id `DD580A5E-4F93-48DB-928C-036CE3326B92/20161219-105822`. Could you try re-uploading a diagnostics when the problem is manifesting?

In the `20161219-105822` diagnostics it seems like the container is running (at least inside the VM):
```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
dbbca02d6459        nginx               "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp     big_panini
```

**Comment by dgonzalez** [comment]
I will. Should I keep this open or open a new one when it happens?

**Comment by djs55** [comment]
I don't mind. Perhaps let's keep this one open since it's fairly low-noise and high-signal. Thanks!

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
