### ISSUE TITLE
Unable to use experimental daemon metrics API

### ISSUE THREAD

**Issue by thaJeztah** [docker/for-mac#1058]
Docker 1.13 adds an experimental feature to expose a daemon metrics API, see [Daemon Metrics](https://github.com/docker/docker/blob/v1.13.0-rc4/docs/reference/commandline/dockerd.md#daemon-metrics), and the pull request https://github.com/docker/docker/pull/25820

On Docker for Mac, this API cannot be exposed, as the port is not opened to be accessible on the host.

### Expected behavior

```
/ # curl localhost:1337/metrics
# HELP engine_daemon_container_actions_seconds The number of seconds it takes to process each container action
# TYPE engine_daemon_container_actions_seconds histogram
engine_daemon_container_actions_seconds_bucket{action="changes",le="0.005"} 1
engine_daemon_container_actions_seconds_bucket{action="changes",le="0.01"} 1
...
```

### Actual behavior

![screen shot 2016-12-20 at 12 23 03](https://cloud.githubusercontent.com/assets/1804568/21349095/661d3ce0-c6b0-11e6-8d1a-35b7f8ab0461.png)

### Information

```
Version 1.13.0-rc4-beta34 (14831)
Channel: Master
5987079516
```

### Steps to reproduce the behavior

1. Set the following `daemon.json` and restart docker;

  ```json
  {
    "debug": true,
    "experimental": true,
    "metrics-addr": "0.0.0.0:1337"
  }
  ```

2. Open http://localhost:1337/metrics in your browser

  "this site can't be reached"

3. Try accessing the metrics API from inside the D4M VM to confirm it's running;

  ```bash
  docker run --rm --network=host alpine sh -c 'apk add --no-cache -q curl && curl localhost:1337/metrics'
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 2# HELP engine_daemon_container_actions_seconds The number of seconds it takes to process each container action
  # TYPE engine_daemon_container_actions_seconds histogram
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.005"} 1
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.01"} 1
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.025"} 1
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.05"} 1
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.1"} 1
  engine_daemon_container_actions_seconds_bucket{action="changes",le="0.25"} 1
  ```

**Comment by friism** [comment]
I believe this was fixed: https://github.com/docker/pinata/issues/6243#issuecomment-278712832
