### ISSUE TITLE
Unable to run 'docker deploy' from 1.13 clients against 1.12 experimental daemons

### ISSUE THREAD

**Issue by JamesDawson** [docker/for-mac#1060]
### Expected behavior
To successfully deploy a container bundle from a Mac running the beta/experimental version of Docker for Mac to a remote docker swarm manager running an experimental version of Docker 1.12.

If this is expected behaviour, then arguably the error message should be updated to more clearly communicate that this feature is not backwards-compatible rather than describing it as a stable vs. experimental issue.

### Actual behavior
The `docker deploy` command fails with the `only supported with experimental daemon` error message, when run from a client running Docker 1.13.

### Information
- Docker for Mac version info: `1.13.0-rc3-beta33.1 (14779)`
- Remote docker version info: `1.12.5, build 7392c3b, experimental`

##### Starting in a fresh terminal on a system with Docker for Mac installed:
1. `docker deploy --help` (observe this works)
1. `export DOCKER_HOST=<remote-ip>:2376`
1. `docker deploy --help` (observe this returns the error shown above)

##### Log onto remote docker host:
1. `docker deploy --help` (observe this works)

##### Testing Linux 1.13-rc client:
1. `docker run -it docker:1.13-rc /bin/sh`
1. `export DOCKER_HOST=<remote-ip>:2376`
1. `docker deploy --help` (observe this returns the error shown above)

##### Testing Linux 1.12 client:
1. `docker run -it docker:1.12-experimental /bin/sh`
1. `export DOCKER_HOST=<remote-ip>:2376`
1. `docker deploy --help` (observe this works)

**Comment by JamesDawson** [comment]
Apologies... I only discovered it wasn't limited to Docker for Mac whilst writing-up the issue, but didn't think to log the issue in a different repo until after I'd posted it.

Let me know if I should re-open it elsewhere.

**Comment by dsheets** [comment]
Hi @JamesDawson, sorry for the long delay in response.

If this issue isn't Docker for Mac specific, I recommend re-opening it on https://github.com/docker/docker/issues if it still occurs.

If you still feel the issue should be tracked here, feel free to re-open.

Thanks for using Docker for Mac!
