### ISSUE TITLE
1.13.0-rc4-beta34 (14840)  can't  build image.

### ISSUE THREAD

**Issue by airforce-captain** [docker/for-mac#1063]
when I run command:
--------------------------------------------
docker build -t nginx-php .

I got some error:
--------------------------------------------
Sending build context to Docker daemon 31.23 kB
Error response from daemon: Unknown instruction: &&

I sure my Dockefile no syntax error , in other linux machine build image is ok.
my machine info:
OS: MacOS 10.12.2
docker for MAC version: 1.13.0-rc4-beta34 (14840)
--------------------------------------------

**Comment by djs55** [comment]
Could you upload a diagnostics report? In the "Whale menu" it's under "Diagnose & Feedback..." -> "Diagnose & Upload". Make sure you quote the diagnostic id in the issue.

**Comment by kevingimbel** [comment]
I'm seeing the same/similar issue with building images or creating new networks with `docker-compose`. Already existing networks (?) start fine when I run `docker-compose up` but anything that needs to build does not run. 

My Diagnostic ID is `19199382-66A3-483E-AB0F-2F65B01EEB11`

I'm also seeing the following issue when running `docker-compose --verbose up`: 

```
ERROR: compose.cli.errors.exit_with_error: Couldn't connect to Docker daemon. You might need to start Docker for Mac.
```

Docker is running as per the menu bar entry. Restarting it from the menu bar or restarting the system doesn't seem to "fix" anything. For now I'll go back to stable and see if the stable works.

**Comment by kevingimbel** [comment]
Apparently it was my mistake. 
[This issue and comment on docker-compose](https://github.com/docker/compose/issues/3719#issuecomment-232173509) got me in the right direction to check what I am actually doing and it turned out I had two 6GB sql dumps laying around in the directory which were not covered by my `.dockerignore` file.

So what I did was sending +13GB to the docker daemon which made it "hang up"/take a lot of time. So, my issue is not related/the same - Sorry! ❤️

**Comment by airforce-captain** [comment]
Sorry, I forgot to provide these important information.


My Diagnostic ID is:   `BDDEAF50-E190-47B2-A056-F71B56AD0381`

```
Docker for Mac: version: 1.13.0-rc4-beta34 (264590153)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/BDDEAF50-E190-47B2-A056-F71B56AD0381/20161222-091210.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by justincormack** [comment]
@airforce-captain that sounds like a parsing issue with your Dockerfile. There were some parsing issues in the 1.13 rc releases but they should have been fixed. Can you include your Dockerfile?

**Comment by airforce-captain** [comment]
@justincormack
thank you for  reply.

I upgrade to Version 1.13.0-rc4-beta34.1 (14853) , has been OK. I think the issue already fixed.

**Comment by justincormack** [comment]
Ok cool, I will close this then, glad that fixed it and sorry there was a issue.
