### ISSUE TITLE
The beta version is always "staring..." on MacOS 

### ISSUE THREAD

**Issue by thomasz-nyt** [docker/for-mac#1064]
### Expected behavior
Starting normally

### Actual behavior
Always "Starting..." and in the latest beta version, the error message shows

com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Docker for Mac: version: 1.13.0-rc4-beta34 (264590153)
OS X: version 10.12.3 (build: 16D12b)
logs: /tmp/BBDA5AAD-C068-4EDB-9C70-01E23BBFA241/20161221-140905.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/thomas/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/thomas/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/thomas/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Just upgrade to latest beta, happened for about a week

**Comment by jesperronn** [comment]
Happens for me after upgrading beta33 to beta34

Diagnostics while docker says "starting...":
```
Docker for Mac: version: 1.13.0-rc4-beta34 (264590153)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/D4AAF01E-61F9-47FB-8ABB-98B0B7FA673C/20161221-084057.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by djs55** [comment]
@thomasz-nyt in beta 34 we added extra integrity checks to look for problems in the `Docker.qcow2` before starting the VM. I see in your logs:
```
block device raised exception: (Failure "Found two references to cluster 214223: 98.50816 and 7.4760")
```
This means that two 64KiB regions of the disk (clusters) are mapped to the same physical part of the file, so that one write will also overwrite the other. It would be unsafe to write to the disk in this state. It's possible this happened in the past and has only been noticed after the beta 34 upgrade.

I recommend that you make a backup of your `Docker.qcow2` by:
```
mv ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 Docker.qcow2.backup
```
and then restart the app. I recommend not importing any old containers from toolbox, just in case the problem is caused by the import. Unfortunately your containers and images will need to be rebuilt.

If you wish to try to recover the contents from the backed up `Docker.qcow2`, try this:
```
/Applications/Docker.app/Contents/MacOS/qemu-img check -r all Docker.qcow2
```
Note it's expected to print a lot of lines of the form
```
ERROR cluster 152878 refcount=0 reference=1
```
to reflect the fact that we use lazy refcounting and hence the refcounts are all 0-- these errors can be ignored. Once repaired, the file can be moved back and the app started again.

If you try any of that and it doesn't work, please let me know. Sorry for the inconvenience!

**Comment by djs55** [comment]
@jesperronn your symptoms are different. I see in your logs that your VM did start (and therefore your `Docker.qcow2` is intact) but the docker engine didn't start. The VM console has:
```
✓ Process dockerd running: dockerd --pidfile=/run/docker.pid -H unix:///var/run/docker.sock --swarm-default-advertise-addr=eth0 --userland-proxy-path /usr/bin/slirp-proxy --debug --experimental --storage-driver overlay2
✓ Process containerd running: docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc --debug
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
✗ Docker ps failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
The docker engine seems to have segfaulted:
```
Dec 21 06:41:07 moby root: unexpected fault address 0x7f59b0143e20 
Dec 21 06:41:07 moby root: fatal error: fault 
Dec 21 06:41:07 moby root: unexpected fault address 0x7f59b01491b9 
Dec 21 06:41:07 moby root: unexpected fault address 0x7f59b01434e9 
Dec 21 06:41:07 moby root: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f59b0143e20 pc=0x7b21b6] 
Dec 21 06:41:07 moby root: goroutine 119 [running]: 
Dec 21 06:41:07 moby root: runtime.throw(0x19749f9, 0x5) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4203ee5c0 sp=0xc4203ee5a0 
Dec 21 06:41:07 moby root: runtime.sigpanic() 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4203ee618 sp=0xc4203ee5c0 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).literalStore(0xc4204a45a0, 0x7f59b0143e20, 0x42, 0x60, 0x16bbee0, 0xc42014cde0, 0x198, 0x7ae700) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:824 +0x856 fp=0xc4203ee958 sp=0xc4203ee618 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).literal(0xc4204a45a0, 0x16bbee0, 0xc42014cde0, 0x198) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:759 +0xd3 fp=0xc4203ee9b0 sp=0xc4203ee958 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).value(0xc4204a45a0, 0x16bbee0, 0xc42014cde0, 0x198) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:371 +0x306 fp=0xc4203eea30 sp=0xc4203ee9b0 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).object(0xc4204a45a0, 0x166b300, 0xc42014cde0, 0x16) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:696 +0x1080 fp=0xc4203eecc0 sp=0xc4203eea30 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).value(0xc4204a45a0, 0x166b300, 0xc42014cde0, 0x16) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:368 +0x2cc fp=0xc4203eed40 sp=0xc4203eecc0 
Dec 21 06:41:07 moby root: encoding/json.(*decodeState).unmarshal(0xc4204a45a0, 0x166b300, 0xc42014cde0, 0x0, 0x0) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:169 +0x1fa fp=0xc4203eedb8 sp=0xc4203eed40 
Dec 21 06:41:07 moby root: encoding/json.Unmarshal(0x7f59b0143e18, 0x68, 0x68, 0x166b300, 0xc42014cde0, 0x0, 0x0) 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/encoding/json/decode.go:97 +0x102 fp=0xc4203eee00 sp=0xc4203eedb8 
Dec 21 06:41:07 moby root: github.com/docker/docker/volume/store.(*VolumeStore).restore.func2(0xc42023d0e0, 0xc42006df80, 0xc4200f1a40, 0xc42035bc20) 
Dec 21 06:41:07 moby root: ^I/go/src/github.com/docker/docker/volume/store/restore.go:35 +0x995 fp=0xc4203eef90 sp=0xc4203eee00 
Dec 21 06:41:07 moby root: runtime.goexit() 
Dec 21 06:41:07 moby root: ^I/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4203eef98 sp=0xc4203eef90 
Dec 21 06:41:07 moby root: created by github.com/docker/docker/volume/store.(*VolumeStore).restore 
Dec 21 06:41:07 moby root: ^I/go/src/github.com/docker/docker/volume/store/restore.go:78 +0x16b 
```
I suspect this is being caused by a lack of error handling while loading json from disk. Looking at the VM's console before the upgrade it has:
```
 * Unmounting filesystems
 *   Unmounting /port ... [ ok ]
 *   Unmounting /Database ... [ ok ]
 *   Unmounting /Users ... [ ok ]
 *   Unmounting /Volumes ... [ ok ]
 *   Unmounting /tmp ... *   in use but fuser finds nothing
 [ !! ]
 *   Unmounting /private ... [ ok ]
 *   Unmounting /host_docker_app ... [ ok ]
 *   Unmounting /tmp ... *   in use but fuser finds nothing
 [ !! ]
 *   Unmounting /var ... *   in use but fuser finds nothing
 [ !! ]
 * Stopping busybox mdev ... [ ok ]
 * Setting hardware clock using the system clock [UTC] ... [ ok ]
 * Terminating remaining processes ... [ ok ]
 * Killing remaining processes ... [ ok ]
 * Saving dependency cache ... [ ok ]
 [ ok ]
 * Remounting remaining filesystems read-only ... *   Remounting /tmp read only ... [ ok ]
 *   Remounting /tmp read only ... [ ok ]
 *   Remounting /var read only ... *   in use but fuser finds nothing
 [ !! ]
 *   Remounting / read only ... [ ok ]
 [ !! ]
 * ERROR: mount-ro failed to start
^MThe system is going down NOW!
^MSent SIGTERM to all processes
^MSent SIGKILL to all processes
^MRequesting system poweroff
reboot: Power down
```
-- it looks like `/var` was unmounted uncleanly (possibly leaving some json metadata truncated?) which then prevented the daemon from starting properly.

It may be possible to clear out the broken volume metadata in the VM. First take a backup of the `~/Library/Containers/com.docker.docker/com.docker.driver.amd64-linux/Docker.qcow2` file, then start the app, then run `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` and at the prompt `rm -rf /var/lib/docker/volumes/`, then `sync`. Restart the app and see what happens.

I'll report this bug upstream as the code which reads the metadata should probably not cause a segfault.

**Comment by aPoCoMiLogin** [comment]
@djs55 have same issue as @jesperronn after few app restarts it's working. So did run diagnose and all was green.

Previous had only error at `docker ps` section. unfortunately it was only "diagnose" without upload. This is my diagnose ID: `DBF29DB5-FF4C-42B0-B76B-A5CDC891F7F3` from next diagnose I did, maybe you can check any logs that I can't see from the diagnose interface.

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
