### ISSUE TITLE
Docker update window steals focus

### ISSUE THREAD

**Issue by Zert** [docker/for-mac#1065]
### Expected behavior

I can use any other applications while docker for mac updating itself

### Actual behavior

I cannot use any other applications while docker for mac updating itself because it steals focus

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
I can't, because docker for mac steals focus

  - A reproducible case if this is a bug, Dockerfiles FTW
No Dockerfile involved

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. See docker for mac update window
  2. Press Install Update
  3. Now you cannot use any other application during docker for mac update downloading

**Comment by jeanlaurent** [comment]
Hi @Zert,

What's your macOS version and Docker for mac version ?

**Comment by Zert** [comment]
macOS: 10.12.2
Version 1.13.0-rc4-beta34 (14840)
Channel: Beta
2645901539

**Comment by jeanlaurent** [comment]
You were updating from beta33 ?

**Comment by Zert** [comment]
May be, I don't know what is my previous version. Now I have this issue anyway.

**Comment by jeanlaurent** [comment]
We'll work something out.

Thanks for you report.

**Comment by avsm** [comment]
Marking this is as a duplicate of https://github.com/docker/for-mac/issues/1482
