### ISSUE TITLE
Docker for Mac in App Store

### ISSUE THREAD

**Issue by vsipuli** [docker/for-mac#1069]
### Expected behavior

Docker for Mac is available from the Mac App Store

### Actual behavior

Docker for Mac is _not_ available from the Mac App Store

### Information

Getting Docker for Mac from the App Store has several advantages:

- It is a convenient and natural way to discover and install applications for Mac users
- Provides automatic updates (if user wants), without having to prompt the user to install them
- Guarantees a sandboxed application, making the application more trustable

So it would be great if it was available for download and installation there. Would it please be possible to publish Docker for Mac on the App Store?

### Steps to reproduce the behavior

1. Open the App Store application in macOS
2. Enter "Docker" into the search field
3. Observe the search results

**Comment by jeanlaurent** [comment]
Hi @vsipuli,

Putting Docker for Mac in the App Store has several advantages and constraints.

There is no short term plan of putting Docker for Mac in the App Store.
