### ISSUE TITLE
Fatal Error: Communication with networking components failed.

### ISSUE THREAD

**Issue by af608** [docker/for-mac#107]
### Actual behavior

Docker does not start after clean install.

<img width="304" alt="screen shot 2016-08-03 at 8 13 45 am" src="https://cloud.githubusercontent.com/assets/3190283/17370827/6e1e17d2-5952-11e6-8d6c-8c553e9b9d5f.png">

<img width="710" alt="screen shot 2016-08-03 at 8 13 14 am" src="https://cloud.githubusercontent.com/assets/3190283/17370828/71f8de3c-5952-11e6-9c44-44fc1460c5d5.png">

Most specific failure is: com.docker.slirp is not running

> ./docker-diagnose 
OS X: version 10.11.6 (build: 15G31)
Docker.app: version: win-beta-v1.12.0-rc5-beta21-73-g9cd1dc2
Running diagnostic tests:
[ERROR]   docker-cli       /var/run/docker.sock does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /var/run/docker.sock
[ERROR]   docker-cli       /Users/afrank/Library/Containers/com.docker.docker/Data/s60 does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /Users/afrank/Library/Containers/com.docker.docker/Data/s60
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]   Moby booted      /Users/afrank/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]   driver.amd64-linux Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
[ERROR]   vmnetd           Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
[ERROR]   vmnetd           /private/tmp/vmnetd/com.docker.vmnetd is not running
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   db               /Users/afrank/Library/Containers/com.docker.docker/Data/s40 does not exist
[ERROR]   db               Unexpected error (No such file or directory) connecting to /Users/afrank/Library/Containers/com.docker.docker/Data/s40
[ERROR]   db               com.docker.db is not running
[ERROR]   slirp            /Users/afrank/Library/Containers/com.docker.docker/Data/s51 does not exist
[ERROR]   slirp            Unexpected error (No such file or directory) connecting to /Users/afrank/Library/Containers/com.docker.docker/Data/s51
[ERROR]   slirp            com.docker.slirp is not running
Error exec: ./../../../Contents/MacOS/qemu-img check /Users/afrank/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/82E832BB-8F8E-43A8-A6D3-82B3ACEF3874/20160803-080433/qemu-img-check.stdout 2> /tmp/82E832BB-8F8E-43A8-A6D3-82B3ACEF3874/20160803-080433/qemu-img-check.stderr: exit 1
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
Error docker ps: got timeout (docker ps: exit 1)
Most specific failure is: com.docker.slirp is not running
Docker logs are being collected into /tmp/82E832BB-8F8E-43A8-A6D3-82B3ACEF3874/20160803-080433.tar.gz

### Information

Diagnostic ID: 82E832BB-8F8E-43A8-A6D3-82B3ACEF3874
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/afrank/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/82E832BB-8F8E-43A8-A6D3-82B3ACEF3874/20160803-080005/qemu-img-check.stdout 2> /tmp/82E832BB-8F8E-43A8-A6D3-82B3ACEF3874/20160803-080005/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/afrank/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/afrank/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/afrank/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/afrank/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/afrank/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce
1. Mac OSX El Capitan Version 10.11.6
2. Install Docker from here: https://download.docker.com/mac/stable/Docker.dmg
3. Launch Docker from: Applications > Docker

Note: ... beta release was installed before, but was uninstalled before the new release was installed.

Aug  3 07:54:05 Docker[3717]: Application version: 1.12.0 (10871)
Aug  3 07:54:05 Docker[3717]: Administrator user: true
Aug  3 07:54:05 Docker[3717]: OSX Version: Version 10.11.6 (Build 15G31)
Aug  3 07:54:05 Docker[3717]: migrator: start migration process
Aug  3 07:54:05 Docker[3717]: migrator: previous install detected
Aug  3 07:54:05 Docker[3717]: migrator: previous version is 1.12.0-beta21
Aug  3 07:54:05 Docker[3717]: migrator: no migration needed, you are good to go!
Aug  3 07:54:05 Docker[3717]: migrator: successfully updated from version 1.12.0-beta21 to 1.12.0
Aug  3 07:54:05 Docker[3717]: migrator: end of migration process
Aug  3 07:54:05 Docker[3717]: event tracker initialized
Aug  3 07:54:05 Docker[3717]: Bundle path: /Applications/Docker.app
Aug  3 07:54:05 Docker[3717]: com.docker.vmnetd component is missing and will be installed

**Comment by af608** [comment]
Found fix:

sudo chown root:wheel  /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist

cd /Library/LaunchDaemons
ln -s /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist

**Comment by djs55** [comment]
Thanks for the report! (For my future reference: this looks like a similar failure to #8.)
