### ISSUE TITLE
Docker doesn't like Unauthenticated system proxies

### ISSUE THREAD

**Issue by takuhii** [docker/for-mac#1072]
I am using Docker behind a proxy, at I have to manually update the proxy settings, as we use a PAC based proxy. If I am logged in to the system, via Active Directory, then I am ok. The problem lies in that Web Browsers are ok, any thing on the command line has to be authenticated and allowed through the proxy manually.

Despite have a proxy BASH script to allow for this it would seem that Docker STILL doesn't understand the "Use System Proxy" option, as it isn't being authenticated through the proxy automatically, but an option to do it manually isn't presented either, so you can't use that option behind certain Proxy setups. You have to revert to Manual Proxy setup...

I am using OS X Sierra 10.12.1 on a 15" Macbook Pro Retina

**Comment by djs55** [comment]
Thanks for your report. We'd like to improve this aspect of Docker for Mac over the next few releases -- I'd really like to understand your workflow better. When you say "anything on the command line has to be authenticated and allowed through the proxy manually": could you show me what that looks like? Do you have to supply a username and password on the command-line for commands like `curl`?

I'd like to understand more about how your system is setup. Could you upload a diagnostic report and quote the diagnostic id on the ticket?

**Comment by djs55** [comment]
We're planning the HTTP proxy improvements for 1.14 at the moment, so any detail you could provide would be greatly appreciated.

**Comment by yallop** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by djs55** [comment]
@takuhii one possibility is to run your own unauthenticated proxy on `127.0.0.1` on your Mac and then set your Docker for Mac to use the special hostname `docker.for.mac.localhost` available in the latest "edge" builds. All traffic from containers would then go via the unauthenticated `127.0.0.1` proxy which could authenticate to the external proxy.
