### ISSUE TITLE
start/stop daemon from the commandline

### ISSUE THREAD

**Issue by dalin-** [docker/for-mac#1073]
### Expected behavior
The ability to start/stop the docker daemon from the commandline.

### Actual behavior
AFICT this ability doesn't exist.  Or if it does, it isn't documented anywhere that Google knows about.

**Comment by dalin-** [comment]
Actually, this works:

```
killall Docker
```

It gracefully shuts down all of the related processes like hyperkit too.

**Comment by djs55** [comment]
Yes, that should be fine. The backend processes have a pipe connection to the GUI `Docker` process and automatically shutdown when they detect the pipe has been closed.
