### ISSUE TITLE
Unable to start Postgres image that works in docker toolbox

### ISSUE THREAD

**Issue by ikbenben** [docker/for-mac#1076]
We have a docker environment that is working with docker toolbox and are we are trying to migrate to Docker for Mac.

I'm creating a new issue as I encountered a new issue while trying to test feedback from issue #986 . The new issue is that I'm not able to bring an image up into a container while using the Beta version of Docker for Mac (as requested in the original issue)

### Expected behavior

To be able to run `docker-compose up` and bring up Postgres container

### Actual behavior

Postgres container closes immediately with exit code 0. I've attached a verbose output from running `docker-compose up`
[docker-compose-log.txt](https://github.com/docker/for-mac/files/670852/docker-compose-log.txt)

### Information

**Diagnostic**
ID: A89166C4-467A-4187-ACB2-A3EB43852500
tar: [20161223-142138.tar.gz](https://github.com/docker/for-mac/files/670850/20161223-142138.tar.gz)
```
Docker for Mac: version: 1.13.0-rc4-beta34.1 (b4ff3714d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/A89166C4-467A-4187-ACB2-A3EB43852500/20161223-142138.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

1. extract the following db-init.sh, Dockerfile and docker-compose.yml files into a folder
[docker-files.zip](https://github.com/docker/for-mac/files/670863/docker-files.zip)

2. run docker-compose up

**Comment by justincormack** [comment]
Unfortunately this is another case of https://github.com/docker/for-mac/issues/1085 - there is a bug in 1.13.0-rc4 if `WORKDIR` is the last line of the Dockerfile it overrides `CMD` so nothing happens. This will be fixed in -rc5 this week.

If you duplicate the `ENV APP_HOME /fitmo-db` line at the end of the Dockerfile it gives a temporary workaround (or add any other command after `WORKDIR`). Sorry about this.

**Comment by dsheets** [comment]
This should have been fixed in Beta 35. Beta 36 is current. If you still have this problem, please feel free to re-open this issue.

Thanks for using Docker for Mac!

**Comment by ikbenben** [comment]
Hi @dsheets @justincormack 

Sorry, I've been focused on some other stuff so didn't get a chance to check the fix out. I tried with rc7-beta37 and I'm still getting the same result. I've also tried the workaround that Justin suggest by duplicating the `ENV APP_HOME /fitmo-db` to the end of the Dockerfile and it still exited immediately

cheers

**Comment by dsheets** [comment]
When I run your example with beta 37, I see

```
db_1  | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/db-init.sh
db_1  | CREATE ROLE
db_1  | CREATE DATABASE
db_1  | GRANT
db_1  | CREATE DATABASE
db_1  | GRANT
db_1  |
db_1  | LOG:  received fast shutdown request
db_1  | LOG:  aborting any active transactions
db_1  | LOG:  autovacuum launcher shutting down
db_1  | waiting for server to shut down...LOG:  shutting down
db_1  | .LOG:  database system is shut down
db_1  |  done
db_1  | server stopped
db_1  |
db_1  | PostgreSQL init process complete; ready for start up.
db_1  |
db_1  | LOG:  database system was shut down at 2017-01-17 12:35:15 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  autovacuum launcher started
db_1  | LOG:  database system is ready to accept connections
```

which I believe to indicate success. Have you rebuilt your images under beta 37?

**Comment by ikbenben** [comment]
@dsheets You are correct. I deleted all my previous containers and images and rebuilt from scratch and it is working as expected. Thanks
