### ISSUE TITLE
Docker wont restart after update

### ISSUE THREAD

**Issue by mohankrishna** [docker/for-mac#1077]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Please open a fresh ticket with a "diagnostics id". Without the diagnostic information there's nothing I can do to help.

From the "whale menu", choose "Diagnose & Feedback..." and then choose "Diagnose and Upload"
