### ISSUE TITLE
Docker 1.12.5 deamon doesn't start even if it's state is started

### ISSUE THREAD

**Issue by ccgagnon** [docker/for-mac#1078]
### Expected behavior
Docker deamon to run

### Actual behavior
Docker deamon is not running

### Information
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/3952EC32-1063-4E38-B780-985AE375DFA2/20161223-102023.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/cgagnon/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/cgagnon/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/cgagnon/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

Install or update to 1.12.5 (14777)
Try use docker in the terminal.

**Comment by dsheets** [comment]
Hi @ccgagnon, it looks like you upgraded from beta 17 to stable 1.12.5. Unfortunately, Beta 17 was released before we began testing for cross-channel upgrades which we don't currently support. Could you try reinstalling 1.12.5 from :whale: ➡️ `Preferences...` ➡️ `Reset` ➡️ `Reset to factory defaults` to see if that corrects the issue?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
