### ISSUE TITLE
Can't change daemon options during restart

### ISSUE THREAD

**Issue by cirocosta** [docker/for-mac#1081]
### Expected behavior

Should be possible to change daemon options during reboot. 

### Actual behavior

Changing is not allowed.

<div align="center"><img width="492" alt="screen shot 2016-12-23 at 14 56 08" src="https://cloud.githubusercontent.com/assets/3574444/21458719/fcb63564-c91f-11e6-9bcc-283bfc874ed5.png"></div>

### Information

```
Docker for Mac: version: 1.13.0-rc4-beta34.1 (b4ff3714d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/38558249-050D-4919-B121-744B4F7A788D/20161223-145708.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

1. Go to `preferences -> daemon -> advanced`, insert a valid json with an invalid `daemon.json` configuration.
2. Restart docker
3. docker will keep trying to start but it won't ever finish.
4. You're only able to change the configuration by reseting to factory defaults

**Comment by cirocosta** [comment]
Not strictly related, is `-H tcp://0.0.0.0:2375` is going to be reconsidered as daemon options become more open? 
Thx!

**Comment by peterbollen** [comment]
Is there an option to reset/edit the daemon.json configuration without reseting to factory defaults?

**Comment by samoht** [comment]
This should be fixed in the upcoming Beta40.

**Comment by cirocosta** [comment]
![image](https://cloud.githubusercontent.com/assets/3574444/23363636/6b8e98e4-fcda-11e6-8814-f17ffe51a82a.png)

fixed right? 😁

**Comment by Nemesis9765** [comment]
Doesn't work for me.  I click the button and it still retains the same invalid configuration which created the issue to begin with.
