### ISSUE TITLE
Intalling  last version failed to restart

### ISSUE THREAD

**Issue by LmpOSX** [docker/for-mac#1083]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Please could you upload a diagnostic id in a fresh ticket? Without more information there's nothing I can do to help :(
