### ISSUE TITLE
Docker not starting after the update

### ISSUE THREAD

**Issue by mohankrishna** [docker/for-mac#1084]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.13.0-rc4-beta34.1 (b4ff3714d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/D98E75BB-C77E-4833-BF5B-9B8AD003A125/20161226-085328.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mohan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mohan/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mohan/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mohan/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mohan/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mohan/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by sam3d** [comment]
I am also getting the behaviour: `93EABBAC-0C17-4FE2-AB5F-D1E105213F2A`.

**Comment by NealSr** [comment]
I had similar errors after updating (console-ring does not exist).  It looks like you can clear your library and it fixes it but that might remove a lot of configurations, so I don't recommend it.

```
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/F42ADDC6-9A6C-48F9-988C-01799C896594/20161227-141630.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/<username>/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by djs55** [comment]
@mohankrishna unfortunately your diagnostic upload seems to have failed. Could you try again?

@NealSr you're running a different version (stable 1.12.5 versus beta 34.1 with 1.13.0-rc4)-- I think your problem is different. Looking at your diagnostics I think you have too many `hyperkit` processes. There were some bug fixes in the latest beta channel for this (which will soon be released in stable). If you have time, could you give beta 34.1 a try? It's available from https://download.docker.com/mac/beta/Docker.dmg If the new version fails to start then you might need to delete your `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` (which contains your containers and images) since it may have become corrupted.

@sam3d your problem is also different. It looks like the docker daemon segfaulted:
```
Dec 27 03:09:23 moby root: unexpected fault address 0x7fa61c6b12fb 
Dec 27 03:09:23 moby root: fatal error: fault 
Dec 27 03:09:23 moby root: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa61c6b12fb pc=0x46bb61] 
Dec 27 03:09:23 moby root: goroutine 1 [running]: 
Dec 27 03:09:23 moby root: runtime.throw(0x19749f9, 0x5) 
Dec 27 03:09:23 moby root: ^I/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420584ee0 sp=0xc420584ec0 
Dec 27 03:09:23 moby root: runtime.sigpanic() 
Dec 27 03:09:23 moby root: ^I/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc420584f38 sp=0xc420584ee0 
Dec 27 03:09:23 moby root: runtime.memmove(0xc420437c40, 0x7fa61c6b12fb, 0x40) 
Dec 27 03:09:23 moby root: ^I/usr/local/go/src/runtime/memmove_amd64.s:176 +0x331 fp=0xc420584f40 sp=0xc420584f38 
Dec 27 03:09:23 moby root: runtime.slicebytetostring(0xc420584fc8, 0x7fa61c6b12fb, 0x40, 0x40, 0xc420585018, 0x436ca3) 
Dec 27 03:09:23 moby root: ^I/usr/local/go/src/runtime/string.go:94 +0x7e fp=0xc420584f98 sp=0xc420584f40 
Dec 27 03:09:23 moby root: github.com/docker/docker/volume/store.(*VolumeStore).restore.func3(0xc4200ea8c0, 0x1a93ef0, 0xc4200ea8c0) 
Dec 27 03:09:23 moby root: ^I/go/src/github.com/docker/docker/volume/store/restore.go:85 +0xce fp=0xc420585028 sp=0xc420584f98 
Dec 27 03:09:23 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4203bad20, 0xc4205850d8, 0x0, 0x0) 
Dec 27 03:09:23 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:595 +0xb5 fp=0xc420585078 sp=0xc420585028 
Dec 27 03:09:23 moby root: github.com/docker/docker/volume/store.(*VolumeStore).restore(0xc420311ef0) 
```
I think this is #1064, reported and fixed upstream as [docker/docker#29636] which is being considered for cherry-picking into 1.13.0 stable due out soon.

**Comment by dsheets** [comment]
@mohankrishna are you still experiencing this issue?

**Comment by mohankrishna** [comment]
@dsheets Not anymore. Its working fine after the uninstall and reinstall.
