### ISSUE TITLE
docker daemon does not start after update to release 1.12.0

### ISSUE THREAD

**Issue by douglaspaulino** [docker/for-mac#109]
### Expected behavior
Docker deamon started
### Actual behavior
docker daemon does not start
### Information

Diagnostic ID: F6AB7257-6374-4F51-9981-9E64D30764BC
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/douglasp/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/F6AB7257-6374-4F51-9981-9E64D30764BC/20160803-132900/qemu-img-check.stdout 2> /tmp/F6AB7257-6374-4F51-9981-9E64D30764BC/20160803-132900/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. just uninstalled the beta version and installed the release version.
2. Now my docker daemon does not start
[20160803-132950.tar.gz](https://github.com/docker/for-mac/files/399903/20160803-132950.tar.gz)

**Comment by douglaspaulino** [comment]
I just run: 

> sudo rm -rf /Users/[user]/Library/Containers

and seemingly this ok now... until the end of the week remain ok, I shut the issue

tks!

**Comment by willbar** [comment]
I had the same problem and deleting my existing containers worked as well.

**Comment by MagnusS** [comment]
@douglaspaulino thanks for the report! Did you uninstall the beta using the `Uninstall` button in preferences?

**Comment by douglaspaulino** [comment]
@MagnusS I did not use the uninstall option. :(

**Comment by mchiang0610** [comment]
merging with #119 and #601

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in F6AB7257-6374-4F51-9981-9E64D30764BC/20160803-132950.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  3 11:36:46 MACCIT012409CPS-6.local Docker[com.docker.osxfs][1419] <Notice>: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
Aug  3 11:36:46 MACCIT012409CPS-6.local Docker[com.docker.osxfs][1419] <Notice>: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Mac
Aug  3 11:36:46 MACCIT012409CPS-6.local Docker[com.docker.slirp][1420] <Notice>: Using protocol TwoThousand msize 8192
Aug  3 11:36:56 MACCIT012409CPS-6.local Docker[com.docker.driver.amd64-linux][1421] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-218841088")
Aug  3 11:37:52 MACCIT012409CPS-6.local Docker[com.docker.osx.hyperkit.linux][1378] <Notice>: Received SIGTERM, shutting down
Aug  3 11:37:52 MACCIT012409CPS-6.local Docker[com.docker.osx.hyperkit.linux][1378] <Notice>: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 1421)
Aug  3 11:37:52 MACCIT012409CPS-6.local Docker[com.docker.osx.hyperkit.linux][1378] <Notice>: Signal terminated to com.docker.driver.amd64-linux (pid 1421)
Aug  3 11:37:52 MACCIT012409CPS-6.local Docker[com.docker.driver.amd64-linux][1421] <Notice>: sending SIGTERM to com.docker.hyperkit pid 1423
```
