### ISSUE TITLE
Container stopped responding and could not be stopped or killed

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1092]
### Expected behavior
Container kept working and could be stopped.

### Actual behavior
Container stopped responding and could not be stopped or killed.

### Information
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.12.2 (build: 16C68)
logs: /tmp/960549A5-E20C-4E41-B51B-FA16000C14C6/20161229-090754.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

I saved the .tar.gz file and could upload it, if necessary.

### Steps to reproduce the behavior
It happened and I'm not sure how to reproduce it.

**Comment by 12789** [comment]
Same issue.

> Docker for Mac: version: 1.12.5 (3e6f00c1d)
> OS X: version 10.12.2 (build: 16C67)
> logs: /tmp/FC38F72F-F3D2-4474-8E42-641EE30A228A/20161231-002041.tar.gz
> failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
> [OK]     vmnetd
> [OK]     dns
> [OK]     driver.amd64-linux
> [OK]     virtualization VT-X
> [OK]     app
> [OK]     moby
> [OK]     system
> [OK]     moby-syslog
> [OK]     db
> [OK]     env
> [OK]     virtualization kern.hv_support
> [OK]     slirp
> [OK]     osxfs
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          docker ps failed
> [OK]     menubar
> [OK]     disk
> Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by lbialy** [comment]
Same issue, can't event uninstall docker.

**Comment by dsheets** [comment]
@daveisfera it looks like somehow the file system sharing node table has become corrupted. I've escalated this issue to our file system team. Thanks for your report!

@12789 I don't see any obvious faults in your logs. If you continue to experience the problem, could you please open a new bug report with a fresh diagnostic upload?

@lbialy please open a new bug report with the diagnostic ID from 🐳 ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload`.

**Comment by lbialy** [comment]
Too late, purged docker from OS and reinstalled it, sorry. Needed it for work.

**Comment by ijc25** [comment]
We are consolidating the `forget-not-found` issue into ticket https://github.com/docker/for-mac/issues/1265 to track it in a single place please subscribe there for further updates.
