### ISSUE TITLE
5F82AEBB-6C74-4453-9DE7-59328948531E

### ISSUE THREAD

**Issue by 1flywind** [docker/for-mac#1096]
### Expected behavior
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.10.5 (build: 14F1808)
logs: /tmp/5F82AEBB-6C74-4453-9DE7-59328948531E/20161231-084303.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")

### Actual behavior
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
The only error I see in your log is:
```
Dec 31 08:34:42 ... Docker[com.docker.docker][345] <Warning>: Sparkle: ===== Docker =====
Dec 31 08:34:42 ... Docker[com.docker.docker][345] <Warning>: Sparkle: Error: An error occurred while downloading the update. Please try again later. (null) (URL https://download.docker.com/mac/stable/1.12.5.14777/Docker.dmg)
Dec 31 08:34:42 ... Docker[com.docker.docker][345] <Warning>: Sparkle: Error: The network connection was lost. (null) (URL https://download.docker.com/mac/stable/1.12.5.14777/Docker.dmg)
```
Superficially it looks like the network connection was lost while the app was downloading an update (to latest stable 1.12.5).

Could you try re-running with a stable network connection and let me know what happens?

If it still doesn't work could you try downloading it from a terminal via

```
curl -v https://download.docker.com/mac/stable/1.12.5.14777/Docker.dmg -o Docker.dmg
```
If it downloads successfully then you can open the `Docker.dmg` and drag `Docker` to `Applications` manually. Let me know if the `curl` command fails. For reference mine looks like this:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 54.192.9.101...
* TCP_NODELAY set
* Connected to download.docker.com (54.192.9.101) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.docker.com
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Server certificate: Starfield Services Root Certificate Authority - G2
> GET /mac/stable/1.12.5.14777/Docker.dmg HTTP/1.1
> Host: download.docker.com
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: binary/octet-stream
< Content-Length: 111169735
< Connection: keep-alive
< Date: Thu, 29 Dec 2016 15:48:35 GMT
< Last-Modified: Fri, 16 Dec 2016 13:55:05 GMT
< ETag: "df7dfe895b33d995451aead70b488969-22"
< Accept-Ranges: bytes
< Server: AmazonS3
< Age: 46
< X-Cache: Hit from cloudfront
< Via: 1.1 3965285cac2a9323992ecbe26f94d453.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: SRnYVyuVZk1YNoqOroMG8FMspbBSaxx9sCPpwlV3N71tacE7llyZow==
< 
```

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
