### ISSUE TITLE
Docker hangs in "starting" mode

### ISSUE THREAD

**Issue by hrishikeshvganu** [docker/for-mac#1098]
### Expected behavior
Docker starts
### Actual behavior
Docker hangs in "starting" mode
### Information
Docker for Mac: version: 1.13.0-rc3-beta32 (9cf974f9e)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/754CE15C-9165-4FF2-88E3-1B655BDEB62B/20170101-101332.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Start docker from the menu bar

**Comment by djs55** [comment]
Thanks for your report. Unfortunately the diagnostics failed to upload so I can't see in detail what went wrong, however there have been recent important bugfixes in the beta channel. I notice you are already on beta 32. Could you upgrade to beta 34.1 via

https://download.docker.com/mac/beta/Docker.dmg

and try uploading a fresh diagnostics if the issue persists?

Note that some of the recent bugs in the beta channel could occasionally cause corruption of the `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` file. In the most recent beta 34.1 these should be fixed and a disk integrity-check has been added on every VM start to catch further problems. If beta 34.1 fails to start then you may need to reset to factory defaults, or delete the `Docker.qcow2` file. Unfortunately in this case your containers and images will need to be rebuilt.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
