### ISSUE TITLE
ss

### ISSUE THREAD

**Issue by liulinwj** [docker/for-mac#1099]
### Information

Diagnostic ID: EAFE614A-9C4D-4D71-859E-DE5763EBC2E2
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.1 (Build 16B2555)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by liulinwj** [comment]
jjjj

**Comment by djs55** [comment]
OSX Sierra (10.12) is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
