### ISSUE TITLE
Docker stuck on start stage

### ISSUE THREAD

**Issue by fortianyou** [docker/for-mac#1100]
### Information

Diagnostic ID: EC549A72-7EE2-4B4D-BC3D-A459A9BE5C08
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
It looks like the docker daemon failed to start inside the VM. Version 1.12.0-a is quite old now -- the latest stable is 1.12.5. Could you upgrade and upload a fresh diagnostics? There are many bug fixes in the latest stable and the diagnostics are better.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
