### ISSUE TITLE
Docker fails to start w/ native virt if Virtualbox has ever been installed (and removed)

### ISSUE THREAD

**Issue by sammcj** [docker/for-mac#1101]
### Expected behavior

Docker starts VM using xhyve / built in native virtualisation.

### Actual behavior

Docker crashes complaining about Virtualbox version, however no Virtualbox is installed.

### Information

```
Docker for Mac: version: 1.13.0-rc4-beta34.1 (b4ff3714d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/5E44D03C-0E1E-4117-9952-7D82C66A81F4/20170103-184040.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/samm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/samm/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/samm/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/samm/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/samm/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/samm/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

### Steps to reproduce the behavior

  1. Install Virtualbox
  2. Remove Virtualbox (including cleaning plists etc... if you wish)
  3. Try to run Docker

You can also remove the following files / directories but the problem still occurs:

```
/Users/$HOME/Library/Containers/com.docker.docker
/Library/LaunchDaemons/org.virtualbox_kaopu.startup.plist "/Library/Application Support/VirtualBox_KaoPu/LaunchDaemons/org.virtualbox_kaopu.startup.plist"
/Users/$HOME/.docker
```

**Comment by djs55** [comment]
It might be that the virtual box kernel driver is still installed? Perhaps try uninstalling via the [uninstall script described in the VirtualBox manual](https://www.virtualbox.org/manual/ch02.html#idm871) and see whether it helps? I suspect a reboot may also be required.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by ddhirajkumar** [comment]
I am having the same problem. 
I used to have VirtualBox and uninstalled it. But docker fails to start complaining that I still have VirtualBox uninstalled. 
This is on my mac version : Yosemite 10.10.5

<img width="607" alt="image" src="https://cloud.githubusercontent.com/assets/6774758/22227644/20b027d0-e181-11e6-873b-e0619b4a2781.png">

**Comment by ddhirajkumar** [comment]
I was able to resolve this issue. 
Looks like the uninstallation wasn't clean when I had just removed the .app file into Trash. 


I installed VirtualBox again and installed it using the Uninstall Tool provided by them. 
And then when I started Docker it started successfully.
