### ISSUE TITLE
"OS X" should now be "macOS"

### ISSUE THREAD

**Issue by halprin** [docker/for-mac#1107]
### Expected behavior
The operating system should be referenced as "macOS".
### Actual behavior
The operating system is currently referenced as "OS X".
### Information
The name of the Mac operating system is now "macOS" and so the Docker for Mac application should reference the operating system correctly.  Let me know if you really want the diagnose information; I decided not to include it since this is mostly a Mac and GUI issue.  There are at least two locations in the Docker for Mac GUI that use the "OS X" name instead of "macOS".
  - The File Sharing area of the preferences.
![screen shot 2017-01-04 at 10 37 11 pm](https://cloud.githubusercontent.com/assets/16943066/21670312/7b88994a-d2d0-11e6-8bf9-a1fe7e4bd8ae.png)

  - The second line in the log that is displayed in the Diagnose & Feedback window.
![screen shot 2017-01-04 at 10 49 14 pm](https://cloud.githubusercontent.com/assets/16943066/21670322/86e0f9ea-d2d0-11e6-8ce3-743519594c02.png)

### Steps to reproduce the behavior

  1. *Whale menu* -> Preferences...
  2. Select "File Sharing" in the toolbar.
  3. Notice the static text that starts as "These **OS X** directories..."
  4. *Whale menu* -> Diagnose & Feedback
  5. Click the "Diagnose Only" button.
  6. Wait for the diagnosing to complete.
  7. Notice the second line in the log to the left.

**Comment by MagnusS** [comment]
Thanks for the report. This issue will be fixed in the upcoming beta 36 release.
