### ISSUE TITLE
Docker OS X freezes up during Android AOSP repo sync 

### ISSUE THREAD

**Issue by odbol** [docker/for-mac#111]
### Expected behavior

Docker should work
### Actual behavior

It freezes for a while, then gives an error message:

`Error response from daemon: dial unix /Users/xxx/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused`
### Information

Diagnostic ID: 332F0CD7-984D-4B23-8989-FB76DC9EA015
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Have 8 gigs of RAM.
2. Install repo: https://source.android.com/source/downloading.html
3. repo init -u https://android.googlesource.com/platform/manifest
4. repo sync -j3 [where "3" is your number of processor cores + 1]
5. Leave the computer alone so display goes to sleep (computer does not go to sleep)

**Comment by ijc25** [comment]
Hi @odbol thanks for your report and sorry for the rather lengthly delay getting back to you.

Are you able to reproduce this with the latest stable release (1.12.3 at time of writing)?

Your logs show symptoms of various things which have been resolved or improved in more recent versions (#7, #785). It's also possible that you would benefit from the fix described in https://github.com/docker/for-mac/issues/933#issuecomment-260311428, after upgrading you could apply the change of default as described there but given the aufs errors I see in your logs (relating to #7) a factory reset might be a better approach (be aware that this will destroy all of your existing containers though).

If you can reproduce with latest stable then please do a new diagnostic upload, we have improved the data collection there as well.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
