### ISSUE TITLE
failed: port is already allocated

### ISSUE THREAD

**Issue by donhuvy** [docker/for-mac#1114]
### Expected behavior
Run Oracle 11g Express success
### Actual behavior
Cannot run https://github.com/wnameless/docker-oracle-xe-11g

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Diagnostic ID: 20EB9506-CC72-4093-8A15-60E05A841ED1
Before that, I run success. But today it isn't.

```
Last login: Sat Jan  7 22:42:11 on ttys000
➜  ~ docker run -d -p 49160:22 -p 49161:1521 wnameless/oracle-xe-11g
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
➜  ~ docker run -d -p 49160:22 -p 49161:1521 wnameless/oracle-xe-11g
043d8caecbb45d6e2e5999b69a2f760c20d53ff3aa2fad78cb1eb70acb058a1f
docker: Error response from daemon: driver failed programming external connectivity on endpoint serene_lalande (08bb0bd9684c0f92db7b736986bf894d3a57a714324405823496d13e175e7491): Error starting userland proxy: Bind for 0.0.0.0:49161 failed: port is already allocated.
➜  ~ netstat -anp tcp | grep 49161                                  
tcp4       0      0  192.168.1.2.49161      17.188.166.13.5223     ESTABLISHED
➜  ~ docker --version
Docker version 1.12.5, build 7392c3b
➜  ~ 

```
I also post question to: http://stackoverflow.com/questions/41523285/failed-port-is-already-allocated

**Comment by dsheets** [comment]
Do you already have a container running that has bound that port? Have you experienced the issue since you initially filed this ticket? Are you running some other program that has bound the port? It looks like 49161 is in use outbound to an Apple server on port 5223. Perhaps you need to select a different port to bind so you don't collide with outbound allocations?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by jakesyl** [comment]
I'm having the same issue here.
