### ISSUE TITLE
Can I run docker within docker for docker for mac?

### ISSUE THREAD

**Issue by k2xl** [docker/for-mac#1115]
Since that `/var/run/docker.sock:/var/run/docker.sock` won't work unless on linux, how can I run a docker container within a container on docker for mac?

**Comment by justincormack** [comment]
Yes, `-v /var/run/docker.sock:/var/run/docker.sock` will work fine, as `/var` is not defined as a shared directory with OSX, so it uses the Linux path (this is a bit confusing, but generally works ok). So it should work as expected.

**Comment by dsheets** [comment]
@k2xl I believe your question was answered and Docker-in-Docker should work with Docker for Mac. Please feel free to re-open this issue if you have related questions or open a new issue for other matters. Thanks for using Docker for Mac!
