### ISSUE TITLE
Diagnostics incorrectly fails when Application path contains a space

### ISSUE THREAD

**Issue by Pike** [docker/for-mac#1117]
### Expected behavior
Diagnose & Feedback succeeds with no errors

### Actual behavior
Docker.qcow2 fails, diagnostic ID: E3CEC369-1E66-4D1A-906B-4E2DA2E40711

### Information
I have already run a reset-to-factory-defaults, and then do nothing but to run the diagnostics:

Docker for Mac: version: 1.13.0-rc5-beta35 (25211e84d)
OS X: version 10.12.2 (build: 16C68)
logs: /tmp/E3CEC369-1E66-4D1A-906B-4E2DA2E40711/20170109-143011.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

### Steps to reproduce the behavior

  1. Update to beta, reset to factory defaults, startup, run diagnose & feedback.

**Comment by djs55** [comment]
Thanks for your report. Apart from this problem with the diagnostics program itself, are there any other symptoms?

It looks like the diagnostics program fails when there is a space in the path name :(

```
$ ls -l qemu-img-check.std*
-rw-r--r--  1 djs  staff  46  9 Jan 13:30 qemu-img-check.stderr
-rw-r--r--  1 djs  staff   0  9 Jan 13:30 qemu-img-check.stdout

$ cat qemu-img-check.stderr 
/bin/sh: /Applications/Docker: is a directory
```

**Comment by Pike** [comment]
I had tons of network errors when trying to do `docker-compose build` with timeouts trying to download stuff.

Renaming "Docker Beta.app" to "Docker_Beta.app" indeed fixes the self test, and I can't reproduce the download issues anymore.

Does it make sense to keep this issue open for the space issue?

(also back to testing my original issue for the other ticket)

**Comment by djs55** [comment]
Yes, let's make this issue the space issue. I'm testing a patch to fix it atm. (Thanks again for the report!)

**Comment by djs55** [comment]
This has now been fixed in master and should be released in beta 37 (in a couple of weeks)

**Comment by samoht** [comment]
Closing as both the beta and stable channels should now have the fix.
