### ISSUE TITLE
1.13.0-rc5-beta35 causes docker to corrupt the disk image

### ISSUE THREAD

**Issue by udnaan** [docker/for-mac#1118]
### Expected behavior
Start normally

### Actual behavior
Images gets corrupted, preventing startup of docker daemon

### Information
Docker for Mac: version: 1.13.0-rc5-beta35 (25211e84d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/B572C5FE-A091-4AB2-8030-5B654BA3F5F3/20170109-113725.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/nan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/nan/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/nan/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/nan/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/nan/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/nan/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

### Steps to reproduce the behavior

    rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
    restart docker
    /Applications/Docker.app/Contents/MacOS/qemu-img resize ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 150G
    restart docker
    crash

**Comment by djs55** [comment]
Unfortunately it's not safe to run `qemu-img resize` while the application is running :( It's difficult even to run it safely after exiting the app because the hypervisor doesn't exit until some time after the app exits. I suspect concurrent file modification triggered the corruption.

However there is built-in support for resizing the .qcow2 safely -- could you try the following:

```
$ cd ~/Library/Containers/com.docker.docker/Data/database/                                                                             

$ git reset --hard                               
HEAD is now at c435935 Settings Changed 09 Jan 17 20:28 +0000

$ cat com.docker.driver.amd64-linux/disk/size 
65536

# number is in MiB so 150G should be 153600:
$ echo 153600 > com.docker.driver.amd64-linux/disk/size

$ git add com.docker.driver.amd64-linux/disk/size 

$ git commit -s -m 'New target disk size'
```
and then
```
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
and restart docker? Unfortunately there's no UI support for this -- we're still thinking about the best way to present it.

**Comment by udnaan** [comment]
Does this only work for the beta version or should it also work for stable?

**Comment by udnaan** [comment]
Never mind that. I got my answer. 
This seems to only work for beta version.

Definitely an improvement on the hacky way I was using. Thanks for the tip!
