### ISSUE TITLE
8F962F77-8651-40D3-A581-C19BAC0A435C

### ISSUE THREAD

**Issue by yeli88** [docker/for-mac#1119]
### Information
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/8F962F77-8651-40D3-A581-C19BAC0A435C/20170109-150249.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by balrajsingh** [comment]
Could you please upgrade to the latest version of Docker for Mac and retry.  If it still fails please open a new issue with steps to reproduce the problem.  
The latest version can be downloaded from https://download.docker.com/mac/stable/Docker.dmg
