### ISSUE TITLE
Docker CLI failure

### ISSUE THREAD

**Issue by braingraze** [docker/for-mac#112]
### Information

Diagnostic ID: 35FB232B-BFFE-4A7E-9EC7-A652CACF6150
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in 35FB232B-BFFE-4A7E-9EC7-A652CACF6150/20160803-133813.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  3 13:24:19 jfgmbp Docker[com.docker.osxfs][50780] <Notice>: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
Aug  3 13:24:19 jfgmbp Docker[com.docker.osxfs][50780] <Notice>: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Mac
Aug  3 13:24:19 jfgmbp Docker[com.docker.slirp][50781] <Notice>: Using protocol TwoThousand msize 8192
Aug  3 13:24:20 jfgmbp Docker[com.docker.driver.amd64-linux][50783] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-95744")
Aug  3 13:25:00 jfgmbp Docker[com.docker.docker][50763] <Warning>: Sparkle: ===== Docker =====
Aug  3 13:25:00 jfgmbp Docker[com.docker.docker][50763] <Warning>: Sparkle: Extracting /Users/Julian/Library/Caches/com.docker.docker/Sparkle/Docker 11019/Docker.dmg as a DMG
Aug  3 13:25:02 jfgmbp kernel[kern][0] <Notice>: hfs: mounted Docker on device disk3s1
Aug  3 13:25:03 jfgmbp Docker[com.docker.docker][50763] <Warning>: Sparkle: copyItemAtPath:/Volumes/7A1FC483-6AB0-47D6-AD1C-11F5E675E736/.background toPath:/Users/Julian/Library/Caches/com.docker.docker/Sparkle/Docker 11019/.background
```
