### ISSUE TITLE
inodes filling up on aufs volume

### ISSUE THREAD

**Issue by brandones** [docker/for-mac#1122]
### Expected behavior

I have a node project with ~50k files in a docker project. I expect to be able to build my image after it's already been built once.

### Actual behavior

```
Building web
Step 1 : FROM mhart/alpine-node:6
 ---> d448eac1cfdb
Step 2 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7c9025947cf4
Step 3 : COPY . .
ERROR: Service 'web' failed to build: Error processing tar file(exit status 1): open /client/node_modules/react-scripts/node_modules/caniuse-db/features-json/document-currentscript.json: no space left on
 device
```

`docker run -it d448eac1cfdb /bin/df -i` outputs

```
Filesystem              Inodes      Used Available Use% Mounted on
none                   1026000    981539     44461  96% /
tmpfs                   255697        18    255679   0% /dev
tmpfs                   255697        15    255682   0% /sys/fs/cgroup
/dev/vda2              1026000    981539     44461  96% /etc/resolv.conf
/dev/vda2              1026000    981539     44461  96% /etc/hostname
/dev/vda2              1026000    981539     44461  96% /etc/hosts
shm                     255697         1    255696   0% /dev/shm
tmpfs                   255697        18    255679   0% /proc/kcore
tmpfs                   255697        18    255679   0% /proc/timer_list
tmpfs                   255697        18    255679   0% /proc/sched_debug
```

Which is not enough inodes to build my project again.

There are no volumes, let alone dangling ones...

```
$ docker volume ls -qf dangling=true
$ docker volume ls
DRIVER              VOLUME NAME
$
```

Nothing even particularly large in docker images...

```
$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
gcr.io/news-proj/web              latest              7607db77d8dc        About an hour ago   466 MB
mongoclient/mongoclient             latest              6992c01f8dd8        3 days ago          1.092 GB
mhart/alpine-node                   6                   d448eac1cfdb        4 days ago          49 MB
mhart/alpine-node                   base-6              e191e7c48991        4 days ago          37.51 MB
us.gcr.io/news-proj/website_web   latest              2cf68b265e4f        5 weeks ago         880.2 MB
website_web                         latest              2cf68b265e4f        5 weeks ago         880.2 MB
gcr.io/news-proj/web              v1                  a49b2b31faf9        5 weeks ago         837.4 MB
news-web                          latest              a49b2b31faf9        5 weeks ago         837.4 MB
node                                6                   00673888c33c        6 weeks ago         651.3 MB
mvertes/alpine-mongo                latest              22c3837e225f        11 weeks ago        75.33 MB
martin/docker-cleanup-volumes       latest              8c41df286c03        8 months ago        22.14 MB
```

I know it's not supposed to for my version of docker, but `martin/docker-cleanup-volumes` didn't do anything either.

The only way I've been able to successfully free inodes is with
```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```
which is not a great workaround.

Docker version 1.12.5, build 7392c3b
macOS Sierra 10.12.2

### Information

Diagnostic ID: 8746BCFF-72E3-4451-94C1-88A7905E3F32

### Steps to reproduce the behavior

Get on my mac, try to build an image.

**Comment by dsheets** [comment]
The only easy way we have to increase the size of the inode space is to switch from the `aufs` graph driver to the `overlay2` graph driver which is now default. To do this, you simply need to delete your `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` file. Unfortunately, this will delete all of your containers, images, and Docker volumes. There are methods to keep this data and transfer it (e.g. `docker export` and `docker import`) if you need to do that.

With `overlay2`, I have 3940352 inodes by default. Could you try this and see if it fixes your build issue? If that isn't sufficient, we can look at ways to make the file system on the virtual disk image more configurable.

Thanks for your report and for using Docker for Mac!

**Comment by dsheets** [comment]
It looks like I was confused and `overlay2` is only supported on the Beta channel at the moment. If you feel comfortable running the Beta channel, that should solve your issue. Otherwise, a new stable release should be available in the next week or two.

**Comment by samoht** [comment]
1.13 with overlay2 is now released on the stable channel. Please upgrade and tell us if that works better for you. Thanks!

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
