### ISSUE TITLE
Docker Volume NFS issue

### ISSUE THREAD

**Issue by kotowick** [docker/for-mac#1124]
Hello,

Since i/o for mounting OSX volume to docker is terrible, I am taking another approach.
Has any one tried to use a NFS docker volume with OSX? I can't seem to get it to work.

**Steps**
1. On OSX, add this to /etc/exports: `/Users -alldirs -network 172.18.0.0/16 -rw -mapall=root`
2. run "docker volume create --driver local --opt type=nfs --opt o=addr=<mac_ip_address>,rw --opt device=:/Users/<user>/<folder_to_mount> --opt  --name local/nfs
3. docker run -it -v local/nfs:/webapp <docker_image> bash

**Errors:**
docker: Error response from daemon: error while mounting volume with options: type='nfs' device=':/Users/<user>/<folder_to_mount>' o='addr=<mac_ip_address>,rw': permission denied

**Reference:**
https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by barat** [comment]
I tried https://github.com/stephank/docker-for-mac-nfs ... it works, but unfortunately NFS in this way is still slow for big Symfony project ... plus is, that this docker-for-mac-nfs will allow You to mount any folder under /Users/ like "docker run -v hostdir:guestdir :) 
If You can use docker-compose then I recommend docker-sync

**Comment by samoht** [comment]
NFS is probably not the right solution unless you use the `async` mode where you trade consistency for speed. If you use NFS, you won't have `inotify` support (filesystem event notifications used by most build systems) and `guid/uid` automatic mapping. And you won't be able to control which path you want to expose to `docker` using the native UI.

However, If you want to use NFS anyway, you are very welcome to use and contribute to community projects :-)
