### ISSUE TITLE
CA3F03B0-4AA6-4AC0-9DD8-E75141F293AF

### ISSUE THREAD

**Issue by Anubhav2205** [docker/for-mac#1127]
### Information
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/CA3F03B0-4AA6-4AC0-9DD8-E75141F293AF/20170111-144113.tar.gz
failure: com.docker.slirp is not running
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/wingify/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/wingify/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/wingify/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Started Wasabi and then it asked for Authorisation.
  2. ...

**Comment by dsheets** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in CA3F03B0-4AA6-4AC0-9DD8-E75141F293AF/20170113-012042.

The UI failed to communicate with the networking helper process.

Try the following steps:
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac

Hopefully this will (re-)install the networking helper process properly. Please let us know if this works for you. :-)

May be related to docker/for-mac#61.

**Comment by Anubhav2205** [comment]
@dsheets 
This worked perfectly for me. 
Thanks for the help

**Comment by Anubhav2205** [comment]
@dsheets Hi David,
It seems the problem has re-appeared. Now I am not able to find this file 
/Library/PrivilegedHelperTools/com.docker.vmnetd

Do you want me to create a fresh issue ? CA3F03B0-4AA6-4AC0-9DD8-E75141F293AF - This is Diagnostic ID. I am sorry I am new to this stuff. I am trying to install Docker for Wasabi.
