### ISSUE TITLE
Docker app for Mac hangs on startup, version 1.12.6 Stable, on OS/X 10.10.5

### ISSUE THREAD

**Issue by joannbrereton** [docker/for-mac#1129]
### Expected behavior
1.  Start Docker app (from Spotlight)
2.  Docker should start and should show "Docker has started."

### Actual behavior
1. Start Docker app (from Spotlight)
2. Docker starts but never gets to "Docker has started.", remains at "Docker is starting...." indefinitely.

### Information

Diagnostic ID : D897C31F-66C2-49D9-BAEA-B3A991735CD6

### Steps to reproduce the behavior

See above.

**Comment by jpallas** [comment]
Saw this on 10.11.6 El Capitan on a MacBook Pro (Retina, 15-inch, Late 2013).  After force quitting com.docker.hyperkit it started up normally.

**Comment by joannbrereton** [comment]
This is happening after rebooting osx too though.

**Comment by joannbrereton** [comment]
Fixed with re-install of Docker for Mac stable.
