### ISSUE TITLE
Issue while starting docker

### ISSUE THREAD

**Issue by mustafa3009** [docker/for-mac#113]
### Information

Diagnostic ID: 96AE0861-D56A-4DED-B206-0C89402C651F
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/mustafakhokhawala/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/96AE0861-D56A-4DED-B206-0C89402C651F/20160803-175724/qemu-img-check.stdout 2> /tmp/96AE0861-D56A-4DED-B206-0C89402C651F/20160803-175724/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mustafa3009** [comment]
Steps to reproduce
1. Install docker as per the instructions provided at docs.docker.com/docker-for-mac
2. After docker starts up then go to "Diagnose and Feedback" and then this issue crops up

**Comment by mchiang0610** [comment]
merging with #601
