### ISSUE TITLE
Docker for Mac won`t start anymore

### ISSUE THREAD

**Issue by christianpetrin** [docker/for-mac#1133]
### Expected behavior
Docker will start

### Actual behavior
Docker says "Docker starting" but never starts (staying in starting forever)

### Information

Docker for Mac was working perfectly for me, until I rebooted my machine. Unexpectedly after that the docker daemon won`t start anymore and any docker command I try such as "docker ps" gives me a "Error response from daemon: Bad response from Docker engine" error message.

Diagnostic output
---------------------------
Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.11.6 (build: 15G1212)
logs: /tmp/14DA7BCC-7832-4A20-9804-8D0ED2632773/20170112-102253.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

System logs show below (ran "syslog -k Sender Docker")
----------------------------------
Jan 11 14:40:09 LMDV-PetrinC Docker[33101] <Notice>: Negotiated transfuse notification channel for /host_docker_app
Jan 11 14:40:09 LMDV-PetrinC Docker[33101] <Notice>: sending continue to client
Jan 11 14:40:09 LMDV-PetrinC Docker[33102] <Notice>: Using protocol TwoThousand msize 8192
Jan 11 14:40:12 LMDV-PetrinC Docker[33103] <Notice>: Docker is responding
Jan 11 14:40:12 LMDV-PetrinC Docker[3271] <Notice>: VM started at 2017-01-11 14:40:12 -0800 PST
Jan 11 14:43:00 LMDV-PetrinC Docker[33102] <Error>: Socket.TCPV4.read tcp:68.178.213.160:10002: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
Jan 11 14:43:01 LMDV-PetrinC Docker[33102] <Error>: Socket.TCPV4.read tcp:68.178.213.160:443: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
--- last message repeated 2 times ---
Jan 11 15:34:07 LMDV-PetrinC Docker[2574] <Notice>: Analytics: Sent heartbeat event.
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Creating resource Entry(tcp:0.0.0.0:15672:tcp:172.19.0.2:15672)
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Write offset=0 data=[tcp:0.0.0.0:15672:tcp:172.19.0.2:15672] to file
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: attempting a best-effort bind of ::1:15672
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Created instance tcp:0.0.0.0:15672:tcp:172.19.0.2:15672
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Creating resource Entry(tcp:0.0.0.0:5672:tcp:172.19.0.2:5672)
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Write offset=0 data=[tcp:0.0.0.0:5672:tcp:172.19.0.2:5672] to file
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: attempting a best-effort bind of ::1:5672
Jan 11 15:49:18 LMDV-PetrinC Docker[33102] <Notice>: Created instance tcp:0.0.0.0:5672:tcp:172.19.0.2:5672
Jan 11 15:53:10 LMDV-PetrinC Docker[2574] <Notice>: HyperkitLinux: Closing com.docker.osx.hyperkit.linux wathdog pipe
Jan 11 15:53:10 LMDV-PetrinC Docker[2574] <Notice>: AppDelegate: applicationWillTerminate
Jan 11 15:53:10 LMDV-PetrinC Docker[3234] <Notice>: EOF on watchdog pipe: shutting down
Jan 11 15:53:10 LMDV-PetrinC Docker[3234] <Notice>: Received SIGTERM, shutting down
Jan 11 15:53:10 LMDV-PetrinC Docker[3234] <Notice>: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 33103)
Jan 11 15:53:10 LMDV-PetrinC Docker[3234] <Notice>: Signal terminated to com.docker.driver.amd64-linux (pid 33103)
Jan 11 15:53:10 LMDV-PetrinC Docker[33103] <Notice>: sending SIGTERM to com.docker.hyperkit pid 33107
Jan 11 16:33:59 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: ===== Docker =====
Jan 11 16:33:59 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: Extracting /Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/Docker.dmg as a DMG
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/.background toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/.background
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/.DS_Store toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/.DS_Store
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/.fseventsd toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/.fseventsd
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/.VolumeIcon.icns toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/.VolumeIcon.icns
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/Applications toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/Applications
Jan 11 16:34:04 LMDV-PetrinC Docker[1004] <Warning>: Sparkle: copyItemAtPath:/Volumes/716AB8F0-7FC0-4CDE-9465-234FAB9B9EB9/Docker.app toPath:/Users/cpetrin/Library/Caches/com.docker.docker/Sparkle/Docker 14937/Docker.app
Jan 12 10:19:01 LMDV-PetrinC Docker[1566] <Notice>: SC database lists no DNS servers: removing overrides from db
Jan 12 10:19:01 LMDV-PetrinC Docker[1564] <Notice>: remove resolver override
Jan 12 10:19:01 LMDV-PetrinC Docker[1564] <Notice>: using default DNS on
Jan 12 10:19:03 LMDV-PetrinC Docker[1566] <Notice>: SC database lists no DNS servers: removing overrides from db
Jan 12 10:19:03 LMDV-PetrinC Docker[1566] <Notice>: SC database lists DNS servers: 172.31.250.11, 172.31.251.11
Jan 12 10:19:03 LMDV-PetrinC Docker[1566] <Notice>: SC database lists search domains: jomax.paholdings.com dc1.corp.gd int.godaddy.com prod.mesa1.gdg prod.mesa1.secureserver.net mesa1.secureserver.net gdhosting.gdg phx3.gdhosting.gdg ams1.gdhosting.gdg sin2.gdhosting.gdg
Jan 12 10:19:03 LMDV-PetrinC Docker[1564] <Notice>: updating search domains to jomax.paholdings.com dc1.corp.gd int.godaddy.com prod.mesa1.gdg prod.mesa1.secureserver.net mesa1.secureserver.net gdhosting.gdg phx3.gdhosting.gdg ams1.gdhosting.gdg sin2.gdhosting.gdg
Jan 12 10:19:03 LMDV-PetrinC Docker[1564] <Notice>: updating resolvers to nameserver 172.31.250.11#53
	nameserver 172.31.251.11#53
Jan 12 10:19:03 LMDV-PetrinC Docker[1564] <Notice>: using DNS forwarders on 172.31.250.11#53; 172.31.251.11#53
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: System wants to wake up
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: Asking com.docker.hyperkit to thaw vcpus
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: vcpu 0 received signal, resuming
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: vcpu 1 received signal, resuming
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: vcpu 2 received signal, resuming
Jan 12 10:19:30 LMDV-PetrinC Docker[1566] <Notice>: vcpu 3 received signal, resuming
Jan 12 10:19:36 LMDV-PetrinC Docker[1566] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
--- last message repeated 1 time ---
Jan 12 10:19:53 LMDV-PetrinC Docker[1455] <Warning>: TextView: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
Jan 12 10:19:58 LMDV-PetrinC Docker[1566] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
--- last message repeated 1 time ---
Jan 12 10:20:10 LMDV-PetrinC Docker[3310] <Notice>: EOF reading packet from Unix domain socket: closing
Jan 12 10:20:10 LMDV-PetrinC Docker[1564] <Error>: failed to establish 9P connection: Caught EOF on underlying FLOW
Jan 12 10:20:10 LMDV-PetrinC Docker[3310] <Critical>: Failed to read hello from client
Jan 12 10:20:19 LMDV-PetrinC Docker[1566] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s

### Steps to reproduce the behavior

  1. Just try to start docker for Marc

**Comment by christianpetrin** [comment]
Doing a factory reset and removing and reinstalling docker from scratch doesn`t solve the issue.

**Comment by christianpetrin** [comment]
Just tried doing a factory reset, rebooted the machine and now docker is back working.

**Comment by sono-bfio** [comment]
Same issue - "Docker starting..."  but never starts after updating to latest.

Tried a couple things, in both cases the issue is not resolved. 
- Quit docker followed by starting it again and it stays in the "Docker starting..." state
- Rebooting (same thing)

Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.10.5 (build: 14F1808)
logs: /tmp/D5BEFD42-040B-4C4E-9B4E-76744203ED2E/20170112-225510.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote

**Comment by peterbollen** [comment]
Having the same issue here after installing the update of version 1.12.6 (14937).

**Comment by peterbollen** [comment]
And now it works :-) Although I did not do anything special afterwards.

**Comment by dsheets** [comment]
@christianpetrin unfortunately, your Docker disk image was using AUFS and became irrecoverably corrupted. Your reset has now switched your disk image to the overlay2 graph driver which has had fewer corruption issues.

@sono-bfio unfortunately, your Docker disk image using AUFS has also become corrupted possibly due to an unclean shutdown or other malfunction of Docker for Mac. The only remedy for this situation is to delete `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` which will remove all of your (corrupted) containers, images, and Docker volumes. I'm sorry this is the best solution for now.

@peterbollen I'm glad Docker for Mac is now working for you.

All, please open a new issue for further problem reports.
