### ISSUE TITLE
8134785A-86E3-4B78-A650-D875B73C4C5E

### ISSUE THREAD

**Issue by coke** [docker/for-mac#1137]
### Expected behavior

Able to start Docker Beta

### Actual behavior

Error on startup:

com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Docker for Mac: version: 1.13.0-rc5-beta35 (25211e84d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/8134785A-86E3-4B78-A650-D875B73C4C5E/20170113-144940.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/williamcoleda/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/williamcoleda/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/williamcoleda/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/williamcoleda/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/williamcoleda/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/williamcoleda/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by dsheets** [comment]
It looks like your diagnostic bundle failed to upload -- we only have a report from 22 August. Could you please try to upload again?

**Comment by coke** [comment]
I'm stuck behind a work firewall, so probably not.

If you can tell me where to find the file to upload, I can attach it to the ticket directly.

**Comment by dsheets** [comment]
The path to the file is printed in the `Diagnose & Feedback` screen under `logs`:

```
Docker for Mac: version: 1.13.0-rc7-beta37 (f2c3d3454)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/D241C935-6656-46CB-B7EE-3D082ACB8474/20170119-121710.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

In this case, the file is at `/tmp/D241C935-6656-46CB-B7EE-3D082ACB8474/20170119-121710.tar.gz`. It contains a lot of diagnostic information and application logs so you may not be comfortable posting it publicly (it could leak project names, company names, usernames, etc). The relevant file will be called `docker-system.log` and should contain some error messages from `com.docker.osx.hyperkit.linux` regarding why it failed to start.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
