### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by johnmcconnell** [docker/for-mac#1138]
### Expected behavior
I expected docker for mac to start normally

### Actual behavior
It crashed

### Information

Diagnostic ID: B6F4DBD1-FFDB-48FD-940D-A5CC5241F671
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.2 (Build 16C67)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/john/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/john/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Docker for Mac 1.12.0-a did not support macOS Sierra 10.12. Support for Sierra arrived in Docker for Mac 1.12.1 and later. The current version of Docker for Mac stable channel is 1.12.6. Please upgrade to this version. Uninstallation of 1.12.0-a on Sierra may be broken but installation of 1.12.6 over the top should succeed.

Out of curiosity, did you recently upgrade macOS (but not Docker for Mac)? Or did you get the old version from somewhere?

Thanks for using Docker for Mac!
