### ISSUE TITLE
Timeout on docker-cli on Mac OS X: 10.11.6

### ISSUE THREAD

**Issue by jvcastaneda** [docker/for-mac#114]
### Information

Diagnostic ID: 08368D01-3F63-48EC-9E5B-B4CB7A65BBCF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in 08368D01-3F63-48EC-9E5B-B4CB7A65BBCF/20160803-154641.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  2 17:45:35 0078-JCAS-MBP15R Docker[com.docker.osxfs][3442] <Notice>: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Mac
Aug  2 17:45:35 0078-JCAS-MBP15R Docker[com.docker.osxfs][3442] <Notice>: osxfs tracing: OFF
Aug  2 17:45:35 0078-JCAS-MBP15R Docker[com.docker.slirp][3443] <Notice>: Using protocol TwoThousand msize 8192
Aug  2 17:45:35 0078-JCAS-MBP15R kernel[kern][0] <Notice>: Sandbox: com.docker.osxfs(3442) System Policy: allow(0) file-write* /private
Aug  2 17:45:37 0078-JCAS-MBP15R Docker[com.docker.driver.amd64-linux][3445] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-181760")
Aug  2 17:46:29 0078-JCAS-MBP15R Docker[com.docker.driver.amd64-linux][3445] <Notice>: sending SIGTERM to com.docker.hyperkit pid 3448
Aug  2 17:46:38 0078-JCAS-MBP15R Docker[com.docker.docker][3409] <Notice>: dockerState = Starting
Aug  2 18:05:54 0078-JCAS-MBP15R Docker[com.docker.driver.amd64-linux][3445] <Notice>: System wants to go to sleep
Aug  2 18:05:54 0078-JCAS-MBP15R Docker[com.docker.driver.amd64-linux][3445] <Notice>: Asking com.docker.hyperkit to freeze vcpus
```
