### ISSUE TITLE
8C096899-15C5-4A37-9EC6-946D17BD57DD8C096899-15C5-4A37-9EC6-946D17BD57DD

### ISSUE THREAD

**Issue by viptech** [docker/for-mac#1140]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

 Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.12.2 (build: 16C68)
logs: /tmp/8C096899-15C5-4A37-9EC6-946D17BD57DD/20170114-193207.tar.gz
failure: /private/tmp/vmnetd/com.docker.vmnetd is not running
[ERROR]  vmnetd
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by dsheets** [comment]
Could you please be more specific about the issue you are experiencing? I see recent evidence of a crashing bug that was fixed in Beta 34 and the fix for which has just reached the stable channel in 1.13.0. You could try upgrading to 1.13.0 and see if that fixes your issue.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
