### ISSUE TITLE
Failure to start after upgrading, maybe related to "no space left on device"

### ISSUE THREAD

**Issue by rubyisbeautiful** [docker/for-mac#1142]
### Expected behavior

Docker for Mac starts up normally after upgrading to 1.13.0-rc6-beta36(14969)

### Actual behavior

Docker does not start up, moby just spins forever 

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

id is FCEED13F-190F-4B6F-B7D1-EAE5B5C0B23C
```
Docker for Mac: version: 1.13.0-rc6-beta36 (a158c69c7)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/FCEED13F-190F-4B6F-B7D1-EAE5B5C0B23C/20170114-140030.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW

I have one restart=always container running, standard library image, mysql:5.7
Before the upgrade, I also had redis:3 running and was building (and failing) something.  The failure was "no space left on device":

```
Building foreman
ERROR: Error processing tar file(exit status 1): write /vendor/assets/stylesheets/jquery-ui/jquery-ui.theme.min.css: no space left on device
```

  - Page URL if this is a docs issue or the name of a man page
N/A

### Steps to reproduce the behavior

  1. Be running last 1.12.x version of Docker beta for Mac
  2. get a failure building
  3. Click the Docker icon in tray to look for something having to do with disk space
  4. Get prompted to upgrade, and follow prompts to do the upgrade

I'm not really sure if I can remove any files to free up disk space (as Docker sees it), or really do anything.  The inner working of Docker on Mac are a bit more mysterious to me then it is on Linux, and it was already a bit mysterious.  Happy to have any suggestions or provide more info to get it going again and not lose containers... data *should* all be ok on volumes, assuming no corruption on disk, etc.  Thanks!

**Comment by rubyisbeautiful** [comment]
FYI, I upgraded to 1.13.0-rc7-beta37 (15013), and no change in (mis)behavior.

**Comment by dsheets** [comment]
@rubyisbeautiful did you import your disk from Toolbox/Virtualbox? It looks like your disk image is only 15GB and is indeed full:

```
Filesystem                Size      Used Available Use% Mounted on
/dev/sda2                15.3G     15.2G         0 100% /var
```

This could cause the Docker daemon to fail to start. Fortunately, I don't see other problems in the logs at a glance. Could you try moving the `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` file to another location (maybe next to it as `Docker.qcow2.bak` or similar) and see if Docker then starts? The newly created disk image should have a maximum size of 64GB -- 4x larger than your current disk image. If that solves the problem, you could then move the disk image back and use `docker export` to save any containers you care about for later running through `docker import`. Once you delete your old, smaller disk image, all of your containers, images, and Docker volumes will be lost.

Could you try that and let me know how it goes? I've opened an internal ticket to make sure that the out-of-disk experience is better in the future.

**Comment by rubyisbeautiful** [comment]
@dsheets Thanks for the info.  I think you're right, when I upgraded it migrated the old Docker stuff for me.  I doubt I'm clever enough to have done it me self.
I had to do **something** because I was kind of blocked by this, so I ended up switching to the stable channel.  I think the "this will reset your whole thing" probably accomplished something similar to what you suggested, since `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` was quite small when I looked.  For good measure, I did move it though, and then re-upgraded to the latest beta37 just now.  I re-created all the containers needed (all data saved via volumes whew!) and no problems.  That file is now less then 2GB, but I admit I'm too ignorant to know how to find the size of `/dev/sda2` from Docker engine's perspective.  
I look forward to the "disk full" enhancement you suggested.  Maybe a simple health check could prevent the user from upgrading (like me) -- "uh oh, looks like you're not ready to upgrade, yada yada..."  Thank you very much for the fast response and the awesome product!  Wish I could do more to help!

**Comment by dsheets** [comment]
Running something like `docker run alpine df -h` will give you some information about Docker's disk image:

```
Filesystem                Size      Used Available Use% Mounted on
none                     59.0G    191.5M     55.8G   0% /
tmpfs                   998.8M         0    998.8M   0% /dev
tmpfs                   998.8M         0    998.8M   0% /sys/fs/cgroup
/dev/vda2                59.0G    191.5M     55.8G   0% /etc/resolv.conf
/dev/vda2                59.0G    191.5M     55.8G   0% /etc/hostname
/dev/vda2                59.0G    191.5M     55.8G   0% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   998.8M         0    998.8M   0% /proc/kcore
tmpfs                   998.8M         0    998.8M   0% /proc/timer_list
tmpfs                   998.8M         0    998.8M   0% /proc/sched_debug
```

I'm on Stable 1.12.6 right now (just installed to check some other support tickets) so the relevant device is `/dev/vda2` which has 191.5M used out of 59G of file system space.

If I run `$ ls -lh ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, I can see the space on my OS X file system that the image takes up:

```
-rw-r--r--  1 dsheets  staff   1.2G Jan 18 10:14 /Users/dsheets/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

This is larger than the in-VM space due to the file system writing to otherwise "empty" blocks that cause our qcow2 implementation's lazy allocator to expand the disk image.

On the Beta channel, the device is `/dev/sda1`:

```
Filesystem                Size      Used Available Use% Mounted on
overlay                  62.7G      1.1G     58.5G   2% /
tmpfs                   999.4M         0    999.4M   0% /dev
tmpfs                   999.4M         0    999.4M   0% /sys/fs/cgroup
/dev/sda1                62.7G      1.1G     58.5G   2% /etc/resolv.conf
/dev/sda1                62.7G      1.1G     58.5G   2% /etc/hostname
/dev/sda1                62.7G      1.1G     58.5G   2% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   999.4M         0    999.4M   0% /proc/kcore
tmpfs                   999.4M         0    999.4M   0% /proc/timer_list
tmpfs                   999.4M         0    999.4M   0% /proc/sched_debug
tmpfs                   999.4M         0    999.4M   0% /sys/firmware
```
