### ISSUE TITLE
Docker run tensorflow errors.

### ISSUE THREAD

**Issue by Robinwho** [docker/for-mac#1145]
### Expected behavior
Follow the tips by the link:
https://github.com/Robinwho/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#optional-setup-gpu-for-mac
>After Docker is installed, launch a Docker container with the TensorFlow binary image as follows.
>**$ docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow**

### Actual behavior
>**$ docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow**

### Information
GET THE ERRORS:

>Unable to find image 'gcr.io/tensorflow/tensorflow:latest' locally
>docker: Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 64.233.189.82:443: i/o timeout.
>See 'docker run --help'.

Is this the problem of proxy? Coz when I run:
>**ping google.com**

Then printing the infos:

>PING google.com (172.217.24.14): 56 data bytes
>Request timeout for icmp_seq 0
>Request timeout for icmp_seq 1
>Request timeout for icmp_seq 2
>Request timeout for icmp_seq 3

I have tried many ways, but doesn't work. How to fix it?

**Comment by Robinwho** [comment]
Refer to #3834, add this to the hosts. But it doesn't work.

#TensorFlow start
64.233.188.121  www.tensorflow.org
#TensorFlow end

When using traceroute [www.tensorflow.org](url),  it stoped at:
14  209.85.245.68 (209.85.245.68)  55.119 ms
    216.239.50.47 (216.239.50.47)  60.914 ms  56.543 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *

and using whois to check the two IPs, both of them are Google Inc.

**Comment by Robinwho** [comment]
Finally finding this:

>> $ docker run -d -p 8888:8888 tensorflow/tensorflow

**Comment by dsheets** [comment]
@Robinwho are you behind a proxy? Could you please run :whale: :arrow_right: `Diagnose & Feedback...` :arrow_right: `Diagnose & Upload` and post the diagnostic ID back here? What version of Docker for Mac are you running?

**Comment by Robinwho** [comment]
@dsheets Hi, this is the infomation:
ID number:
**C7372342-B3A9-471E-B630-323F623D5181**
version:
> Docker for Mac: version: 1.12.6 (a3b0f1129)
>OS X: version 10.10.5 (build: 14F2109)

**Comment by dsheets** [comment]
Are you behing a proxy? Have you configured the proxy in the Docker settings?

**Comment by Robinwho** [comment]
I've configured the proxy. But it doesn't work. So I've closed it.

**Comment by dsheets** [comment]
What doesn't work with the proxy? Do you have a proxy that you need to use? Are you in China? Many Google domains are blocked in China.

**Comment by Robinwho** [comment]
Yes, I'm in China. It doesn't work means that:
**$ docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow**
Unable to find image 'gcr.io/tensorflow/tensorflow:latest' locally
docker: Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 74.125.23.82:443: i/o timeout.

**Comment by dsheets** [comment]
I believe you will need to configure a VPN on your machine or a proxy that helps you get access to the regular internet outside of the Great Firewall. Unless you are already tunneling outside of the GFW somehow, I don't think this is a Docker for Mac issue.

**Comment by Robinwho** [comment]
I've configured a VPN. But it still doesn't work, like this:
$ pc docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.12/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.12

**Comment by Robinwho** [comment]
When curling the site, it returns OK.

$ pc curl gcr.io
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.12/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  gcr.io:80  ...  OK
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://gcr.io/">here</A>.
</BODY></HTML>

**Comment by Robinwho** [comment]
@dsheets thanks a lot :)

**Comment by dsheets** [comment]
@Robinwho the `docker run` command is a client to the docker daemon running inside of a small Linux VM. This VM then has a virtual network device that is used for internet-bound traffic that is connected to a process called `com.docker.slirp` that then performs OS X socket operations as your user to make connections. You could try running the Docker for Mac application itself under `pc` to see if the shared library preloading gets inherited by `com.docker.slirp`. We've only ever tested with system-wide VPNs so there is no special-purpose configuration for per-process VPNs.

**Comment by Robinwho** [comment]
$ ps -ef|grep slirp
  501  1899  1893   0  8:26下午 ??         0:00.24 com.docker.slirp --db /Users/robin/Library/Containers/com.docker.docker/Data/s40 --ethernet fd:3 --port fd:4 --introspection fd:5 --vsock-path /Users/robin/Library/Containers/com.docker.docker/Data/@connect

**Comment by dsheets** [comment]
@Robinwho I'm not sure what your last message means. That is the `com.docker.slirp` process I was referring to.

**Comment by Robinwho** [comment]
hi @dsheets , it's a pretty tough problem. The past few days I've tried a variety of ways. But all of them didn't work, although we know it's cause of GFW. Finally with the help of these two [](links(http://blog.csdn.net/chenming_hnu/article/details/54600270) & [](https://github.com/tensorflow/tensorflow/issues/1273)), the problem is fixed!
Again, thanks a lot:)
