### ISSUE TITLE
docker won't upgrade 

### ISSUE THREAD

**Issue by brjmac** [docker/for-mac#1152]
### Actual behavior
Diagnostic ID EE2679E3-D2B3-4DAD-A92C-B16513FA7649

docker get's error when trying to upgrade or start up

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.13.0-rc4-beta34.1 (b4ff3714d)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/EE2679E3-D2B3-4DAD-A92C-B16513FA7649/20170117-225009.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/bmcfadden/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/bmcfadden/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bmcfadden/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/bmcfadden/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/bmcfadden/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/bmcfadden/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Try to upgrade docker version

**Comment by robertoandrade** [comment]
For some reason it seems to believe the stable version is still installed even though it was removed via `brew cask uninstall docker` and the processes were all killed.

**Comment by robertoandrade** [comment]
In my case I'm on OSX 10.11.6

**Comment by dsheets** [comment]
@brjmac, I see in your logs what looks like disk image corruption:
```
2017-01-17 22:49:48-08 nb141-mac Docker[com.docker.driver.amd64-linux][693] <Notice>: com.docker.hyperkit: [INFO] discard requested and lazy_refcounts is disabled: erasing refcount table and enabling lazy_refcounts
2017-01-17 22:49:48-08 nb141-mac Docker[com.docker.driver.amd64-linux][693] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Invalid_argument "Cstruct.sub: [0,65536](1048576) off=0 len=-735182848")
2017-01-17 22:49:48-08 nb141-mac Docker[com.docker.driver.amd64-linux][693] <Notice>: Mirage-block error: Unknown (Invalid_argument "Cstruct.sub: [0,65536](1048576) off=0 len=-735182848")
2017-01-17 22:49:48-08 nb141-mac Docker[com.docker.driver.amd64-linux][693] <Notice>: Could not open mirage-block device: Invalid argument
```

There were issues in some older betas that could cause unexpected crashes and disk image corruption as well as unexpected system shutdown (e.g. an OS X kernel panic). Unfortunately, I the only way forward is to delete `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` which will remove any images, containers, and Docker volumes you may have been using. Installing Beta 37 on top of your current installation should clear up the problem. I'm sorry for this inconvenience. We've improved in this area recently but are always looking for ways to make this kind of thing less common. Thanks for your report and for using Docker for Mac!

@robertoandrade I don't know what `brew cask uninstall docker` does but we recommend uninstalling through :whale: ➡️ `Preferences...` ➡️ `Uninstall / Reset` ➡️ `Uninstall` to be sure that the software is removed fully. Please open a new issue for this or any other problem. Thanks!
