### ISSUE TITLE
Unable to run 'docker deploy' from 1.13 clients against 1.13 experimental daemons - Need more elaborated error description  

### ISSUE THREAD

**Issue by UttamKiran** [docker/for-mac#1154]
### Expected behavior
docker deploy --help should run successfully .
### Actual behavior
 docker deploy --help
**only supported with experimental daemon**

### Information

Docker Deployed on : Ubuntu 16.04.1 LTS 
Docker Version :1.13.0-rc7, build 48a9e53 
Docker-compose version 1.10.0, build 4bd6f1a
### Steps to reproduce the behavior
1. docker deploy --help    command is prompting "only supported with experimental daemon" 
2.  docker deploy --compose-file docker-compose.yml <yourstackname> also giving the same error

**Comment by dsheets** [comment]
Are you using Docker for Mac? How? I don't think `docker deploy` will be out of experimental in 1.13 (see docker/docker#28839).
