### ISSUE TITLE
Docker 1.12.6 hangs on startup on sierra

### ISSUE THREAD

**Issue by welchwilmerck** [docker/for-mac#1158]
Just accepted update to 1.12.6. Now, docker hangs on start. Have restarted mac, to no avail.

Same as https://github.com/docker/for-mac/issues/546.

OS X: version 10.12.2 (build: 16C67)
Docker.app: version: 1.12.6 (a3b0f1129)
Local time: Thu Jan 19 10:38:54 EST 2017
UTC:        Thu Jan 19 15:38:54 UTC 2017
Timestamp:  20170119-103854
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
Error docker ps: timeout after 8.81s
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      slirp
/bin/sh: line 1:  8717 Killed: 9               /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/welchwil/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/AA0953FE-3212-40F6-9258-34D551E20290/20170119-103854/qemu-img-check.stdout 2> /tmp/AA0953FE-3212-40F6-9258-34D551E20290/20170119-103854/qemu-img-check.stderr
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Most specific failure is: docker ps failed: (Failure "docker ps: timeout after 10.00s")
Docker logs are being collected into /tmp/AA0953FE-3212-40F6-9258-34D551E20290/20170119-103854.tar.gz
Would you like to upload log files? [Y/n]: Y

Your unique id is: AA0953FE-3212-40F6-9258-34D551E20290
Please quote this in all correspondence.

**Comment by welchwilmerck** [comment]
Installed beta and it starts.

940FD6A3-2DCB-4602-9B9A-6025E8E2A548

Then, reinstalled production. Seemed to get all the right prompts for a change. Now, it's OK.

**Comment by dsheets** [comment]
It looks like you encountered #1143 which corrupted your disk image. Changing channels wiped your disk image and 'corrected' the problem. We are investigating the root cause of #1143.
