### ISSUE TITLE
Errors after upgrade to 0.13.0

### ISSUE THREAD

**Issue by HerbCSO** [docker/for-mac#1159]
### Expected behavior
Upgraded to 0.13.0 - expected no issues

### Actual behavior
Errors below happened. Same on restart of Docker. Completely fails to start right now, can't even get to UI to do a reset.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1108)
logs: /tmp/8EF9FB70-3D32-4C32-9D4D-9808DA04B18C/20170119-175953.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/carsten.dreesbach/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Upgrade from 0.12.5 to 0.13.0

**Comment by MikeRankin** [comment]
This is getting pretty irritating.  2 out of the last 3 updates had this sort of failure for me.

**Comment by justincormack** [comment]
@MikeRankin have you got a similar issue? if so could you add a diagnostic code if the issue is identical or open a new issue.

**Comment by MikeRankin** [comment]
Identical problem.  Diagnostic ID: F8A7AC15-69B4-48EC-8A86-B79643400E82

**Comment by willgorman** [comment]
I had the same problem as well. Diagnostic ID: 0DCB2ECC-C178-4B31-BF4B-A268D053305F.  I ended up just doing a  clean reinstall after running `/Applications/Docker.app/Contents/MacOS/Docker --uninstall`.

**Comment by MikeRankin** [comment]
That works.  Thanks for the uninstall command!

**Comment by FrenchBen** [comment]
@MikeRankin a `Reset` under the Moby -> Preferences will also do it

**Comment by HerbCSO** [comment]
Except I can't even get to the Preferences because it crashes before I can get there. 

I'll try out the uninstall when I'm back at my computer tomorrow. Thanks for that @willgorman

**Comment by djs55** [comment]
I had a look in the diagnostics `0DCB2ECC-C178-4B31-BF4B-A268D053305F` `F8A7AC15-69B4-48EC-8A86-B79643400E82` and `8EF9FB70-3D32-4C32-9D4D-9808DA04B18C`-- they all show the same symptom. From beta 34.1 and 1.13 stable we added a startup check to make sure the `Docker.qcow2` file is intact, a bit like `fsck` under Linux. In these 3 cases the existing `Docker.qcow2` has some damage and `Docker.app` concludes that it wouldn't be safe to write to the file, hence the startup failed. In previous versions the file locking around the `Docker.qcow2` was inadequate and in rare cases this allowed the VM to start twice, both instances writing to the file simultaneously-- I suspect this happened in the past, caused some silent corruption and is only now being detected. The latest versions are much more careful to manage the file lock properly.

As a workaround I recommend either

- uninstall/reinstall or
- `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 ` and restart the app.

Unfortunately containers and images will need to be rebuilt.

I apologise for the inconvenience this has caused.

**Comment by HerbCSO** [comment]
FYI, the `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` seems to have worked for now. Thanks!

**Comment by HerbCSO** [comment]
I haven't had any further issues with this after the `rm`, so from my perspective this can be closed.
