### ISSUE TITLE
Cant run "docker ps & docker images"

### ISSUE THREAD

**Issue by alex77lee** [docker/for-mac#116]
### Information

Diagnostic ID: 1467F36E-BA92-42E9-B87E-1E77DFC6C8A6
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/lidan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/1467F36E-BA92-42E9-B87E-1E77DFC6C8A6/20160804-091114/qemu-img-check.stdout 2> /tmp/1467F36E-BA92-42E9-B87E-1E77DFC6C8A6/20160804-091114/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119 and #601
