### ISSUE TITLE
Tell beta channel users when stable has been upgraded

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1164]
Stable is now at 1.13.0? The release notes have not been updated, still show 1.12.5.  
https://docs.docker.com/docker-for-mac/release-notes/#/stable-release-notes
UPDATE: release notes were updated shortly after I filed.

Since people often only use beta for a bug fix, please let them know when stable has been upgraded to a new version, rather than only telling them to apply the next beta (e.g. I was just upgraded to 1.13.0-rc7 even though 1.13.0 is on stable).

Also please keep Docker for Mac release notes up to date or better yet switch to the Release tab in github like your other products.

**Comment by dsheets** [comment]
Thanks for your report! The stable notes have been updated and the beta notes should be online later today. I've made a note on our stable release procedure about notifying users that the stable is synchronizing with the beta.
