### ISSUE TITLE
Mac OS Sierra Docker problem

### ISSUE THREAD

**Issue by lamlephamngoc** [docker/for-mac#1165]
### Information

Diagnostic ID: 0F17F940-D1E9-4F8C-A42A-FBC0367100A5
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
