### ISSUE TITLE
Crashing due to HyperKit exit_reason 2 (triple fault)

### ISSUE THREAD

**Issue by dsheets** [docker/for-mac#1170]
### Expected behavior

Docker for Mac does not crash.

### Actual behavior

Docker for Mac crashes due to `com.docker.hyperkit` aborting with `exit_reason` 2 (triple fault).

### Information

Reported by @vitage in #1110 with diagnostic bundle 856C709F-35EA-469D-8883-5BB1B0991B1D.

### Steps to reproduce the behavior

Unknown

**Comment by dsheets** [comment]
@vitage it looks like you are running OS X 10.10 which we know has various problems with its `Hypervisor.framework` which we use for virtualization. It is likely that these issues are causing the hypervisor to crash and consequently corrupting your disk image preventing your Docker for Mac installation from starting. We recommend upgrading your OS X installation to 10.11 or 10.12 for a more stable experience. In the next few months, we will be deprecating support for 10.10 for exactly these stability reasons.

Anyone else: Faults with similar symptoms (`exit_reason 2`) can occur on other versions of OS X/macOS. We are using this ticket to track those reports.

**Comment by ijc25** [comment]
Anyone who is experiencing this issue should also subscribe to #1176 since I believe they are likely to have the same underlying cause. I'm not actually closing this as a dup (for now) since the symptom (exit 2/triple fault here and exit 48/ept fault on #1176) are not actually the same.
