### ISSUE TITLE
Excessive use of CPU time (E09D5C15-6E6D-40C7-BA75-BEAE5DA83F6C)

### ISSUE THREAD

**Issue by emreboga** [docker/for-mac#1178]
### Expected behavior

Docker for Mac using a reasonable amount of CPU time.

### Actual behavior

com.docker.hyperkit consuming ~300% of CPU time, literally blocking almost everything else.

### Information

Here is the diagnose output:

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/E09D5C15-6E6D-40C7-BA75-BEAE5DA83F6C/20170120-130159.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

To reproduce run ~60 containers on Docker for Mac simultaneously. You can active this by running saas-mega setup locally. Please contact me or #saas for assistance.

**Comment by justincormack** [comment]
Are you out of memory? If it starts swapping it will use a lot of CPU, you may need to allocate more memory.

**Comment by emreboga** [comment]
@justincormack It's not the memory, I have enough memory, but the CPU usage is is high that `docker-compose` almost stopped responding at some point.

**Comment by dsheets** [comment]
The memory allocated to Docker is capped by the Docker for Mac preferences (:whale: ➡️ `Preferences...` ➡️ `Advanced` ➡️ `Memory`). If your containers collectively need more than 2GB of memory and you have only granted 2GB to Docker, your containers will make the Linux VM swap even if you have plenty of spare memory on the host. Could you check how much memory you have allocated to Docker?

Similarly, if the operation you are performing is expected to be heavy, and you don't want it to dominate the CPU on your machine, you can reduce the number of vCPUs allocated to Docker to prevent it from using 300% or 400% CPU (with possible performance trade-off).

Finally, we can take a look at your use case and track down any bottlenecks or pathological Docker for Mac behavior. Thanks for the report!

**Comment by emreboga** [comment]
@dsheets That makes sense now. Memory allocation is at the default 2gbs, I'll increase it gradually and test with the same number of containers I used before.

**Comment by samoht** [comment]
@emreboga: were you able to test with more memory?

**Comment by emreboga** [comment]
@samoht Things look better after increasing the dedicated memory.
