### ISSUE TITLE
Error response from daemon: target is unknown

### ISSUE THREAD

**Issue by alledm** [docker/for-mac#1179]
I am downloading from the EU repository of google cloud. When I run the command I get:
```
docker pull eu.gcr.io/<project-name>/image
Error response from daemon: target is unknown
```

### Expected behavior
Image gets pulled

### Actual behavior
```Error response from daemon: target is unknown```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.0-beta38 (9c31a154d)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/0185876F-2793-4BB1-B03D-FEEA3A3EEF21/20170120-231147.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. docker pull eu.gcr.io/<project-name>/image
 Error response from daemon: target is unknown

**Comment by justincormack** [comment]
I believe this is this issue https://github.com/docker/docker/issues/30083

This should be fixed in 1.13.1. Unfortunately there is no convenient workaround, other than use a different registry (eg a local cache should be ok), ask Google to fix theirs, or downgrade temporarily.

**Comment by sebgoa** [comment]
same error here.

fwiw, it has nothing to do with GCR in my view, it is really a backward incompatible change.

**Comment by justincormack** [comment]
@sebgoa I am still trying to get to the bottom of how it happened, but it seems that some registry software such as Google's accepted or set this content type; the Docker registry does not, so it is a combination of bugs. 1.13.1 should be out shortly to fix this.

**Comment by sebgoa** [comment]
thanks. fwiw, I can pull without problems from 1.11.1 but not from 1.13.0-beta38
