### ISSUE TITLE
Docker doesn't start on macOS Sierra

### ISSUE THREAD

**Issue by dtd12** [docker/for-mac#1182]
### Expected behavior
Docker starts

### Actual behavior
Docker doesn't start mit Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information
C5C89DDB-09A3-4D44-8C1D-0A2F3C7FDE90

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/C5C89DDB-09A3-4D44-8C1D-0A2F3C7FDE90/20170121-110604.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/thomas/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/thomas/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/thomas/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Start Docker from Programs folder

**Comment by davidfauth** [comment]
Seeing the same error. 
:(

**Comment by TerryFranklin** [comment]
Likewise getting the same error, OS X Sierra 10.12.1

**Comment by yallop** [comment]
@dtd12, this has symptoms similar to the problem described here:

    https://github.com/docker/for-mac/issues/1159#issuecomment-273899215

but I don't see any direct evidence in the logs that the underlying problem is the same.  Could you please check whether the workarounds in that issue (either uninstalling and reinstalling, or removing the file `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` and restarting) fix things for you?

**Comment by dtd12** [comment]
It seems that deleting the Docker.qcow2 file solved my problem.
Thanks.

**Comment by samoht** [comment]
Glad to see that everything is working fine now!
