### ISSUE TITLE
Unable to start Dokcer for Mac.

### ISSUE THREAD

**Issue by ManikantThakur** [docker/for-mac#1186]
Diagnostic ID: EE77373D-1C00-4601-926E-F965FDA5630A

### Expected behavior
Docker daemon should start.

### Actual behavior
Docker daemon isn't starting.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
***********************************************************************************************
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/EE77373D-1C00-4601-926E-F965FDA5630A/20170123-112249.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

  - Syslog messages
***********************************************************************************************
Jan 23 11:20:23 EAGLE-EYE Docker[2945]: Client reports version 1, commit 0c6d765c5482987c547f4b2b68f04167ebd3f352
Jan 23 11:20:23 EAGLE-EYE Docker[2945]: EOF reading packet from Unix domain socket: closing
Jan 23 11:20:23 EAGLE-EYE Docker[2945]: Failed to read command from client
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Client reports version 1, commit 0c6d765c5482987c547f4b2b68f04167ebd3f352
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: client with uid 501 requests com.docker.vmnetd install symlinks
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /usr/local/bin/docker is a symlink
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Client supplied container path /Users/eagle/Library/Containers/com.docker.docker/Data
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /var/run/docker.sock is a symlink or a socket
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Symlinking /var/run/docker.sock to /Users/eagle/Library/Containers/com.docker.docker/Data/s60
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /usr/local/bin/docker-compose is a symlink
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Client supplied container path /Users/eagle/Library/Containers/com.docker.docker/Data
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /var/run/docker.sock is a symlink or a socket
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Symlinking /var/run/docker.sock to /Users/eagle/Library/Containers/com.docker.docker/Data/s60
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /usr/local/bin/notary is a symlink
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Client supplied container path /Users/eagle/Library/Containers/com.docker.docker/Data
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /var/run/docker.sock is a symlink or a socket
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Symlinking /var/run/docker.sock to /Users/eagle/Library/Containers/com.docker.docker/Data/s60
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /usr/local/bin/docker-machine is a symlink
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Client supplied container path /Users/eagle/Library/Containers/com.docker.docker/Data
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: File /var/run/docker.sock is a symlink or a socket
Jan 23 11:20:23 EAGLE-EYE Docker[2946]: Symlinking /var/run/docker.sock to /Users/eagle/Library/Containers/com.docker.docker/Data/s60
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Acquired task manager lock
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Maximum number of file descriptors is 10240
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Removing leaked pidfile com.docker.hyperkit
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Starting com.docker.db, com.docker.osxfs, com.docker.slirp, com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Start com.docker.db (pid 2949)
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Start com.docker.osxfs (pid 2950)
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Start com.docker.slirp (pid 2951)
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Start com.docker.osx.hyperkit.linux (pid 2952)
Jan 23 11:20:23 EAGLE-EYE Docker[2950]: Logging to Apple System Log
Jan 23 11:20:23 EAGLE-EYE Docker[2947]: Start com.docker.driver.amd64-linux (pid 2953)
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: Logging to Apple System Log
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: Setting handler to ignore all SIGPIPE signals
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: vpnkit version c5bdb42fbb8c6af51f9a158e491d3dae89caae85 with hostnet version   uwt version 0.0.3 hvsock version 0.11.2
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: starting port forwarding server on port_control_url:fd:4 vsock_path:/Users/eagle/Library/Containers/com.docker.docker/Data/@connect
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: Add(2): DNS configuration changed to: nameserver 202.83.21.12#53
	order 0
	nameserver 202.83.21.2#53
	order 0
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: hosts file has bindings for localhost broadcasthost localhost abhi vm mysql elasticsearch
Jan 23 11:20:23 EAGLE-EYE Docker[2952]: API server starting
Jan 23 11:20:23 EAGLE-EYE Docker[2952]: 🍀 socket path is: /Users/eagle/Library/Containers/com.docker.docker/Data/s20
Jan 23 11:20:23 EAGLE-EYE Docker[2952]: API socket removed
Jan 23 11:20:23 EAGLE-EYE Docker[2952]: VM shutdown at 2017-01-23 11:20:04 +0530 IST
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Acquired hypervisor lock
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Docker is not responding: Get http://./info: dial unix /Users/eagle/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused: waiting 0.5s
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: OSX version = 10.12.2, default value of on-sleep = no not freeze
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: hypervisor: native
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: filesystem: osxfs
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: network: hybrid
Jan 23 11:20:23 EAGLE-EYE Docker[2950]: Using protocol TwoThousand msize 16384
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Hypervisor: native; BootProtocol: direct; UefiBootDisk: /Users/eagle/UefiBoot.qcow2
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Syslog socket is /Users/eagle/Library/Containers/com.docker.docker/Data/*00000002.00000202
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Logfile is /Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/syslog
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: Launched[2959]: /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2048M -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=304b45a6-6049-4ba4-a00b-b1a064ba3957,path=/Users/eagle/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,ahci-hd,file:///Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=0 -s 4,virtio-9p,path=/Users/eagle/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/eagle/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/eagle/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac vsyscall=emulate -F /Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: SC database lists search domains:
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: SC database includes DNS service: { Addresses: 202.83.21.12, 202.83.21.2; Order: 200000; Zones:  }
Jan 23 11:20:23 --- last message repeated 1 time ---
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: SC database has domain name: domain.name
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: attempting to reconnect to database
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: reconnected transport layer
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: updating connection limit to 900
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: allowing binds to any IP addresses
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: updating resolvers to nameserver 202.83.21.12#53
	timeout 2000
	order 200000
	nameserver 202.83.21.2#53
	timeout 2000
	order 200000
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: Add(3): DNS configuration changed to: nameserver 202.83.21.12#53
	timeout 2000
	order 200000
	nameserver 202.83.21.2#53
	timeout 2000
	order 200000
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: Creating slirp server pcap_settings:disabled peer_ip:192.168.65.2 local_ip:192.168.65.1 domain_search:
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: PPP.negotiate: received ((magic VMN3T)(version 1)(commit 0c6d765c5482987c547f4b2b68f04167ebd3f352))
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: virtio-net-vpnkit: magic=VMN3T version=1 commit=0123456789012345678901234567890123456789
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: TCP/IP ready
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: stack connected
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: starting introspection server on: fd:5
Jan 23 11:20:23 EAGLE-EYE Docker[2951]: starting diagnostics server on: fd:6
Jan 23 11:20:23 EAGLE-EYE Docker[2953]: mirage_block_open: block_config = file:///Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1 and qcow_config = discard=true;compact_after_unmaps=0
Jan 23 11:20:24 EAGLE-EYE Docker[2953]: mirage_block_open: block_config = file:///Users/eagle/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1 and qcow_config = discard=true;compact_after_unmaps=0 returning 0
Jan 23 11:20:24 EAGLE-EYE Docker[2953]: com.docker.hyperkit: [INFO] image has 0 free sectors and 149855 used sectors
Jan 23 11:20:24 EAGLE-EYE Docker[2953]: mirage_block_stat
Jan 23 11:20:24 EAGLE-EYE Docker[2953]: vsock init 7:0 = /Users/eagle/Library/Containers/com.docker.docker/Data, guest_cid = 00000003
Jan 23 11:20:26 EAGLE-EYE Docker[2953]:
	rdmsr to register 0x34 on vcpu 0
Jan 23 11:20:26 EAGLE-EYE Docker[2953]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Jan 23 11:20:33 --- last message repeated 12 times ---
Jan 23 11:20:33 EAGLE-EYE com.apple.xpc.launchd[1] (com.apple.nowplayingtouchui): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 23 11:20:33 EAGLE-EYE Docker[2953]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Jan 23 11:20:33 --- last message repeated 1 time ---
Jan 23 11:20:33 EAGLE-EYE Docker[2951]: BOOTREQUEST from c0:ff:ee:c0:ff:ee
Jan 23 11:20:33 EAGLE-EYE Docker[2951]: BOOTREPLY to c0:ff:ee:c0:ff:ee yiddr 192.168.65.2 siddr 192.168.65.1 dns 192.168.65.1 router 192.168.65.1 domain domain.name
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Users
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Volumes
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /tmp
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /host_docker_app
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: Negotiated transfuse notification channel for /Users
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: Negotiated transfuse notification channel for /Volumes
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: Negotiated transfuse notification channel for /tmp
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: Negotiated transfuse notification channel for /private
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: Negotiated transfuse notification channel for /host_docker_app
Jan 23 11:20:34 EAGLE-EYE Docker[2950]: sending continue to client
Jan 23 11:20:34 EAGLE-EYE Docker[2951]: Using protocol TwoThousand msize 8192
Jan 23 11:20:35 EAGLE-EYE Docker[2953]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
***********************************************************************************************

### Steps to reproduce the behavior

  1. Upgrade Docker to version: 1.13.0 (0c6d765c5) {macOS}
  2. Start Docker. It will fail to start.

**Comment by samoht** [comment]
This looks a bit suspicious:

```
 [INFO] image has 0 free sectors and 149855 used sectors
```

Did you do something special before having that error? Your `/var/log/docker.log` shows more errors:

```
Jan 23 05:50:34 moby root: Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/9163307731da7d417d4a81d07abdea634915b2cc1c585c417211834c48c1e763/config.json: open /var/lib/docker/plugins/9163307731da7d417d4a81d07abdea634915b2cc1c585c417211834c48c1e763/config.json: no such file or directory
```

which probably indicates a disk corruption inside the VM. If should be able to reset to factory default to be able to restart from a fresh install, although you will loose all you containers and image. Sorry about the inconvenience and thanks again for you report.

**Comment by ManikantThakur** [comment]
I dont rebember exactly if I did anything special. I just updated the Docker for Mac.
I reverted my installation, and Docker for Mac was up.

Reverted to Docker version:

Version 1.12.5 (14777)
Channel: Stable
3e6f00c1dc

**Comment by ijc25** [comment]
@ManikantThakur did you try a factory reset (on the latest stable) like @samoht suggested?

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
