### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by yunghoy** [docker/for-mac#1187]
This is a crazy bug.
After upgrading docker 1.12.6 to 1.13.0, I got the next errors when I launching docker images.

$ docker -v
Docker version 1.13.0, build 49bf474
$ docker-compose -v
docker-compose version 1.10.0, build 4bd6f1a

$ sudo netstat -natop | grep 6379
tcp6       0      0 :::6379                 :::*                    LISTEN      696/dockerd    off (0.00/0/0)

$ docker service ls
ID  NAME  MODE  REPLICAS  IMAGE
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker-compose -f dc-extern.yml up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "dl_default" with the default driver
Creating dl_redis_1

ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint dl_redis_1 (5726fd29068d284e2fe1d0041d12043e6862a1baf8b4e0c33a882dfe47e77121): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in us

**Comment by yunghoy** [comment]
Sorry, wrong section. It has to be closed.

**Comment by yallop** [comment]
Closing, as superseded by https://github.com/docker/docker/issues/30358.
