### ISSUE TITLE
F1E9756F-FC60-4A47-8FE7-02A38057FADC

### ISSUE THREAD

**Issue by juanyeo** [docker/for-mac#1196]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
Thanks for the report.

From the information in the logs it appears that your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install for more information.
