### ISSUE TITLE
4CB22601-4929-4E1B-BAD8-35A7DFA28329

### ISSUE THREAD

**Issue by tianweiying** [docker/for-mac#1199]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
Thank you for the report.  Unfortunately there isn't enough information here to identify the problem, so I'm closing the issue.  Please feel free to open a new issue with additional information.
