### ISSUE TITLE
Network is unreachable error for all docker commands

### ISSUE THREAD

**Issue by mgartner** [docker/for-mac#12]
### Expected behavior

Docker commands (e.g. `docker images`, `docker ps`) should be working as expected.

### Actual behavior

Docker commands error due to network issues.

```
$ docker images

An error occurred trying to connect: Get https://192.168.59.103:2376/v1.24/images/json: dial tcp 192.168.59.103:2376: getsockopt: network is unreachable

$ docker ps

An error occurred trying to connect: Get https://192.168.59.103:2376/v1.24/containers/json: dial tcp 192.168.59.103:2376: getsockopt: network is unreachable
```

### Information

Diagnostic ID: B05ACE3C-2617-4A74-81F9-62001BFEE9BE
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install docker for mac.
2. Run any docker commands.

**Comment by FrenchBen** [comment]
Out of curiosity what is the output of:
`env | grep -i "docker"`

**Comment by mgartner** [comment]
```
DOCKER_CERT_PATH=/Users/marcus/.boot2docker/certs/boot2docker-vm
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
```

**Comment by mgartner** [comment]
Fixed this by unsetting these environment variables. 

I think I added these when using docker on virtualbox. I'd recommend documenting this (or automating their removal) for anyone who switches to docker for mac.

**Comment by FrenchBen** [comment]
That's exactly what I had in mind - the big tell-tell was the IP you showed. 
Happy to hear this was resolved.
