### ISSUE TITLE
Renaming Mac home directory results in docker for mac failing to start

### ISSUE THREAD

**Issue by jlk** [docker/for-mac#1209]
### Expected behavior
Upon [renaming a Mac user's home folder](https://support.apple.com/en-us/HT201548), Docker for Mac should continue to work after logging into the renamed account, or have a (relatively) easy way for users to update paths used by d4m, without having to delete ~/Library/Containers/com.docker.docker

### Actual behavior
Currently after renaming a user's home directory, rebooting, and logging back in, the user will find Docker for Mac will no longer start.

### Information
    Docker for Mac: version: 1.13.0 (0c6d765c5)
    macOS: version 10.12.2 (build: 16C68)
    logs: /tmp/6984B826-6208-4A6E-AE9D-3F39830AD8C4/20170124-143308.tar.gz
    failure: com.docker.slirp is not running
    [OK]     vmnetd
    [OK]     dns
    [ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
    [OK]     virtualization VT-X
    [OK]     app
    [ERROR]  moby
         /Users/newuser/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
    [OK]     system
    [OK]     moby-syslog
    [ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/newuser/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
    [OK]     env
    [OK]     virtualization kern.hv_support
    [ERROR]  slirp
         Unexpected error ((Failure
      "Error connecting socket to 9p endpoint unix:/Users/newuser/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/newuser/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
      "Error connecting socket to 9p endpoint unix:/Users/newuser/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
    [ERROR]  osxfs
         com.docker.osxfs is not running
    [OK]     moby-console
    [OK]     logs
    [ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/newuser/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
    [OK]     menubar
    [OK]     disk`

diagnostic ID: 6984B826-6208-4A6E-AE9D-3F39830AD8C4

### Steps to reproduce the behavior

1. While logged in to a user account on a mac, install Docker for Mac
2. Once installed and verified as working, log out of that account, into another, and rename the prior account and it's home directory, following directions on https://support.apple.com/en-us/HT201548
3. After completing step 2, reboot the system and login to the renamed account, and attempt start Docker if it does not attempt to start automatically. 
4. The result will be an error "com.docker.osx.hyperkit.linux failed to start Exit code 1"

**Comment by jlk** [comment]
In case others run into this, `rm -rf ~/Library/Containers/com.docker.docker/Data` resolves this at the cost of the moby image, but that's recreated when Docker is restarted.

It'd be nice if we could just edit a config file to straighten this out, though...even if that's a plist.

**Comment by samoht** [comment]
Thanks for your report! I am not very surprised this breaks as we don't test it at all and renaming the home directory is not something that we should expect to happen very often ... Anyway, I have escalated the issue to our UI team and we will keep you updated about the progress.

**Comment by jeanlaurent** [comment]
We're not going to support this, for a foreseeable future. 

We're adding an FAQ entry though, to better guide users.
