### ISSUE TITLE
DNS resolution in container not working as expected

### ISSUE THREAD

**Issue by dwatrous** [docker/for-mac#1210]
### Expected behavior
when I create a new container, I expect to be able to resolve DNS the same as the host on which I'm running docker.  This worked as expected before the 1.13 release. Now I have to create a network and attach the container to the network before I can properly resolve DNS.

### Actual behavior
When I create a new container I cannot resolve DNS for my local network.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1108)
logs: /tmp/DB766255-8B7B-40D9-8A71-0138CC98099A/20170124-180857.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. create a new container
  2. attempt to access a host by hostname that does resolve  on the docker host machine
```
root@3deb602cef90:/# cat /etc/resolv.conf
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
search ad.corp.local ux.corp.local trinet.com trinetgroup.com gevityhr.com accordhr.com soi.com dmz.abovenet ambrosegroup.com
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
root@5b940befb1dc:/# dig devops.trinet.com @192.168.65.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> devops.trinet.com @192.168.65.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 65209
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;devops.trinet.com.		IN	A

;; AUTHORITY SECTION:
trinet.com.		60	IN	SOA	ns1.trinet.com. hostmaster.trinet.com. 2017012402 10800 3600 604800 60

;; Query time: 47 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Tue Jan 24 23:59:35 UTC 2017
;; MSG SIZE  rcvd: 97

MC02RX1B6G8WL:~ dwatrous$ docker network create resolvetest
af2b9bde71aef430afc878386ca43d122692c148f5b47c5ce6a1676cf88a0f75
MC02RX1B6G8WL:~ dwatrous$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
5b940befb1dc        openstack-cli       "/bin/bash"         7 minutes ago       Up 7 minutes                            competent_booth
MC02RX1B6G8WL:~ dwatrous$ docker network connect af2b9bde71aef430afc878386ca43d122692c148f5b47c5ce6a1676cf88a0f75 5b940befb1dc

root@5b940befb1dc:/# cat /etc/resolv.conf
search ad.corp.local ux.corp.local trinet.com trinetgroup.com gevityhr.com accordhr.com soi.com dmz.abovenet ambrosegroup.com
nameserver 127.0.0.11
options ndots:0
root@5b940befb1dc:/# dig devops.trinet.com @127.0.0.11

; <<>> DiG 9.10.3-P4-Ubuntu <<>> devops.trinet.com @127.0.0.11
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57820
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;devops.trinet.com.		IN	A

;; ANSWER SECTION:
devops.trinet.com.	3600	IN	A	192.168.12.31

;; Query time: 55 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Wed Jan 25 00:03:58 UTC 2017
;; MSG SIZE  rcvd: 62
```

Notice that before creating the network, I can't resolve the host, but after creating a network I can.

**Comment by djs55** [comment]
When I try this locally I only ever see `NXDOMAIN`, on host, in container and in container with attached network.

Do you have a private nameserver which has an `A` record for this name? Perhaps Docker for Mac is randomly choosing the wrong nameserver to query?

Unfortunately I can't find the diagnostics bundle associated with `DB766255-8B7B-40D9-8A71-0138CC98099A`. We've just released beta 39 which has some DNS fixes. Could you install beta 39, reproduce the problem again and upload a fresh set of diagnostics? The logs would probably show what was going on.

Alternatively, could you show me your Docker for Mac DNS configuration? It's in:

```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ git reset --hard
HEAD is now at 5650795 last-start-time changed at 1485271462
$ cat com.docker.driver.amd64-linux/slirp/dns 
# { Addresses: 10.14.32.10; Order: 200000; Zones:  }
nameserver 10.14.32.10
order 200000
timeout 2000
```
Would any of the listed IP addresses resolve this name properly? Is it an ordering problem? Is an upstream server missing compared with `scutil --dns`?

Thanks for the report!

**Comment by dwatrous** [comment]
I may not have uploaded the diagnostic. I just ran a new diagnostic here:
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1108)
logs: /tmp/DB766255-8B7B-40D9-8A71-0138CC98099A/20170125-085809.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

When I tried to reproduce my workaround of creating a network, it no longer worked, so the only option I have is to manually modify the resolv.conf file.

We do have a nameserver locally that resolves that domain.

I'm happy to try a beta version of Docker. Are there instructions for installing it?

**Comment by dwatrous** [comment]
I have installed Docker beta 39 for mac and the issue I reported appears to be resolved. Here is a diagnostic.

```
Docker for Mac: version: 1.13.0-beta39 (5e9e408b0)
macOS: version 10.11.6 (build: 15G1108)
logs: /tmp/C63744D0-D156-4354-AF2F-BBFC199F86A3/20170125-090807.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

I'm not sure if that means this issue can be closed or if you want to do further review. I suppose I can keep using the beta version until the next release where this fix will be included in the stable branch.

**Comment by djs55** [comment]
Sorry I should have included the link -- the beta version is available from here: https://download.docker.com/mac/beta/Docker.dmg

**Comment by dwatrous** [comment]
I did find the beta version. It appears to fix the problem and I included diagnostics above. I'm just not sure if I should close this issue or not.

**Comment by dwatrous** [comment]
I'm closing this issue since I assume the fix in the beta version will carry through to the next release.
