### ISSUE TITLE
in need of a "docker-machine env" replacemenet refering to #938

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [docker/for-mac#1212]
I opened this issue earlier #938, it was closed after telling me that I do not need to set the version.

Well, guess what I use the go docker client package from a go program. The client will fail until the right server version is provided.

It just happened, I had to pull out the version with some string matching from
```
docker version
```

Kindly the string has changed ( added (minimum version 1.12) to it), that broke the string matching.

My program failed and I had to fix it, could you please reintroduce a way to safely extract the docker version, now I am not compatible over several docker for mac versions, and simply because I can not get the server version. 

```
██ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
is a shitty way to get ther server version.

**Comment by yallop** [comment]
@morriswinkler-simplesurance, can we close this now that @justincormack has shown how to extract the version using `docker version --format` (https://github.com/docker/for-mac/issues/938#issuecomment-275082867)?

**Comment by morriswinkler-simplesurance** [comment]
shure
