### ISSUE TITLE
Docker agent not starting after installing latest version

### ISSUE THREAD

**Issue by mukteshkrmishra** [docker/for-mac#1218]
### Expected behavior
Docker agent should be starting.
### Actual behavior
It is not starting and gives a very weird error about linux VM.

### Information

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/22098C8E-2816-4176-ACDE-16B5A7021B40/20170125-111627.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mark/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mark/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mark/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mark/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/gdx432/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/gdx432/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Diag ID: 22098C8E-2816-4176-ACDE-16B5A7021B40

**Comment by yallop** [comment]
Thanks for the report, @mukteshkrmishra.  The problem you're seeing may be due to new integrity checks on a corrupt `Docker.qcow2` file.  If that's the case then the workaround suggested in #1159 may fix things: https://github.com/docker/for-mac/issues/1159#issuecomment-273899215

**Comment by mukteshkrmishra** [comment]
Thanks. The solution you have suggested is what I have figured out beforehand and tried. Unfortunately, it removed all my containers and stuff :( :( , but agent has started now :) .

Thanks for your help.

**Comment by samoht** [comment]
Glad to see things are now working properly, although I am sorry that you lost all your containers. Thanks again for your report!
