### ISSUE TITLE
gcloud docker push is very slow or fails

### ISSUE THREAD

**Issue by lwdye** [docker/for-mac#1221]
1.13.0-beta39 (15140)

osx

**Comment by yallop** [comment]
Thanks for the report, @lwdye.  Could you please provide a diagnostic id (from the "Diagnose & Feedback..." -> "Diagnose & Upload" menu option) to help us investigate further?

**Comment by lwdye** [comment]
C251A20E-F39D-4584-A65C-4FFF4CFFF4FB

**Comment by samoht** [comment]
Your log files contains some "interesting" lines:

```
[com.docker.osxfs][79547] <Warning>: UNEXPECTED event message 33 (6) FUSE_GETXATTR.p1378.u0.g0 FIX ME
[com.docker.osxfs][79547] <Error>: transfused: Event mkdir /private/tmp/KSOutOfProcessFetcher.Cc21DAhLsh error: Resource busy
```

But it is not clear if this is the cause of the issue you are having or not (probably not).

Which error do you see when a push is failing?

**Comment by lwdye** [comment]
The docker image that I attempted to push was about 5G and it didn't fail with an error but showed almost no progress.  The connection is 130/5 and otherwise solid but when push happens all other internet connections timeout.  My guess would be some issue with buffering introduced recently.

**Comment by samoht** [comment]
Was it working with a previous version of Docker for Mac? Does it only happen when you push to gcloud? I bet you will have the same issue if you try to ssh a big file to your local host. 

In any case, I will try to reproduce locally: we used to test the transfer of big files, but maybe not 5G files :-)

**Comment by samoht** [comment]
I confirm that running `scp` from a container to a local SSH server of a big file (10G) takes forever (sometime it got stuck at ~20% of the transfer, sometimes ~85%). 

Thanks again for your report, I will escalate this issue to our networking team.

**Comment by robertoandrade** [comment]
wondering if this is the same issue or similar (as I'm seeing it both on push and pulls) to moby/moby#35074

**Comment by robertoandrade** [comment]
per what I described of my findings in moby/moby#35074, it looks like there's a correlation between the amount of memory you allocate to the docker VM (provided by `hyperkit` on macOS) and the maximum amount of optimal data flow, once you transfer up to that amount, it seems to slow the process down considerably, wondering if it's working with swap at that point and why doesn't it discard whatever was pushed already from memory. Do we need allocate as much memory to the process as the biggest layer we want to push/pull?

**Comment by robertoandrade** [comment]
Another thing I noticed seemed to be slowing down not just the build and push process but also the pull was how the qcow file that represents the virtual disk for the hyperkit VM was being expanded. while researching other user's problems with High I/O operations in a container in Docker for Mac, it looks like it has something to do with the `fsync` operations the processes running in the container perform. See https://github.com/docker/for-mac/issues/668#issuecomment-280017422

After following some of the advice there my workloads started working much faster. Wondering what's the best default for that disk option. Right now I'm using `os` which seems to have helped.
