### ISSUE TITLE
Copyright uses wrong year (1.13.0-beta39)

### ISSUE THREAD

**Issue by kevingimbel** [docker/for-mac#1222]
It's just a minor thing, but I noted the copyright in the "About Docker" screen in Docker for Mac is wrong. Should be `2017` instead of `2016`.

![screen shot 2017-01-26 at 08 10 47](https://cloud.githubusercontent.com/assets/2161714/22322838/10fcda20-e39f-11e6-86a8-b691f15b12c1.png)

**Comment by samoht** [comment]
Thanks for the report, time definitely flies too quickly and we need to catch up :-)

**Comment by samoht** [comment]
This should be fixed in the upcoming Beta40.

**Comment by kevingimbel** [comment]
Can confirm it's fixed in Beta40! 🎉 

![screen shot 2017-02-03 at 07 05 52](https://cloud.githubusercontent.com/assets/2161714/22581312/409125a2-e9df-11e6-91f5-7ec3a6d7292d.png)

I'll close this issue since it's fixed.
