### ISSUE TITLE
Cannot run `docker ps` it 'runs' forever

### ISSUE THREAD

**Issue by stanisfun** [docker/for-mac#1225]
Has been used: docker-machine-driver-xhyve
played a bit with kubernates.
then docker ps just wont work.
uninstalled docker-machine-driver-xhyve and docker.
And installed new docker.
So nothing changed. On `docker ps` it hangs on.

```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/55349B71-BC59-400D-957A-C47593C86073/20170126-142143.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by samoht** [comment]
Did you reset your environment variables in your shell? `docker-machine` needs sets up `DOCKER_HOST` and other `DOCKER_*` environment variables whereas Docker for Mac don't need them. See https://docs.docker.com/docker-for-mac/docker-toolbox/#setting-up-to-run-docker-for-mac for more details.

**Comment by anentropic** [comment]
@samoht I think I have similar problem... I previously installed docker-machine the 'old' way, with virtualbox etc

after installing Docker for Mac it reports that docker is running, diagnostics all ok, but:
```
$ ⮀docker info
Cannot connect to the Docker daemon at tcp://192.168.99.100:2376. Is the docker daemon running?
```

this appears to be the virtualbox ip for docker-machine

obviously I need to change some env vars, but I am saying Docker for Mac should diagnose this problem and prompt to fix it

**Comment by anentropic** [comment]
running `unset ${!DOCKER_*}` as suggested in the link above fixed it

I had not thought to look in docker-toolbox docs for a remedy, would be helpful if Docker for Mac UI could suggest this somewhere

**Comment by ijc25** [comment]
Glad things are working for you. Your suggestion re the UI has been added to an internal ticket, thanks!
