### ISSUE TITLE
Fatal Error com.docker.osx.hyperkit.linux failed to start Exit code 1

### ISSUE THREAD

**Issue by ZherebcovSergey** [docker/for-mac#1226]
MacOS Sierra 10.12.2 (16C67)

Diagnostics BA3EF875-A019-4578-9D7C-C0212AA758F2

**Comment by juliuskabugu** [comment]
frustrating. have you found a workaround yet?

**Comment by juliuskabugu** [comment]
https://github.com/docker/for-mac/issues/1198

**Comment by yallop** [comment]
The logs show what appear to be a repeat of https://github.com/docker/hyperkit/issues/50:

```
Assertion failed: (!REPLY_RING_EMPTY(sc)), function send_response_common, file src/lib/pci_virtio_sock.c, line 934.
```

**Comment by ZherebcovSergey** [comment]
Unfortunately there is no time to understand the nature of the problem, because is a workflow, I just put this version (Version 1.13.0-beta39 (15140)) and threw a log file.

**Comment by ijc25** [comment]
@ZherebcovSergey do you have any steps to reproduce the issue please?

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
