### ISSUE TITLE
Docker-machine ls all my machines 7 in all report timeout and generate this error

### ISSUE THREAD

**Issue by dmccullo** [docker/for-mac#1233]
### Actual behavior
NAME      ACTIVE   DRIVER      STATE     URL                        SWARM   DOCKER    ERRORS
EXT1               openstack   Timeout
EXT2               openstack   Timeout
EXTA1              amazonec2   Timeout
INT1               openstack   Timeout
INT2               openstack   Timeout
INTA1              amazonec2   Timeout
INTA2              amazonec2   Timeout
Error attempting call to get driver name: connection is shut down
Error attempting call to get driver name: connection is shut down
Error attempting call to get driver name: connection is shut down
Error attempting call to get driver name: connection is shut down
Error attempting call to get driver name: connection is shut down
Error attempting call to get driver name: connection is shut down
### Information

macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/0D8AD6CC-418D-4808-B3E7-EE36B25DF659/20170127-091022.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behaviour
I just logged in this morning and did a docker-machine ls after upgrading.
I have tried resetting, restoring factory defaults and removing and reinstalling docker.
I have also tried docker-machine regenerate-certs EXT1
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

when I run docker-machine status EXT1                             ▸▸▸▸▸▸▸▸▸▸
Running
docker-machine ssh EXT1 also works.
just cannot list machines I have created......
any help would be appreciated!

**Comment by dmccullo** [comment]
docker-machine ls -t 30 resolves this, upgrading all my machines to current docker machine code with
docker-machine upgrade 'machine name'
then have to regenerate certs but once that is done all is working as long as i use -t 30!

**Comment by dmccullo** [comment]
This all started with Docker 1.13 love the new features not sure why the timeout has started occurring.

**Comment by samoht** [comment]
Thanks for your report! I am glad that you found a workaround, but if you might want to open an issue on https://github.com/docker/machine which is the tracker for docker-machine. Thanks!

**Comment by AshleyAitken** [comment]
Seems to be working again with: Docker version 17.06.0-ce, build 02c1d87
Now have to get upgrade working again...
