### ISSUE TITLE
Problem with docker cp on Docker for Mac

### ISSUE THREAD

**Issue by srinathanand** [docker/for-mac#1234]
### Expected behavior
File gets copied into the container using "docker cp".
### Actual behavior
File timestamp does not change and get an error when trying to delete the file.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
    `0ED4508C-A52C-4EC7-8CE6-E764944F7CC6`
  - A reproducible case if this is a bug, Dockerfiles FTW
docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64
 
Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

### Steps to reproduce the behavior

  1. Trying to copy a .class file from the host to the container (when server is not running) using       `docker cp <file_on_host> <container>:<file_path_inside_container>`

The timestamp inside the container does not change and when trying to rm the file get an error -
`rm: cannot remove '<file_name>': Stale file handle`

**Comment by samoht** [comment]
@srinathanand are you able to reproduce that behaviour reliably? I tried on a simple example and all seems to work fine.

**Comment by srinathanand** [comment]
Yes we are able to reproduce the problem reliably. We can show you if needed through a screen share if needed.

**Comment by samoht** [comment]
Can you provide the precise steps to reproduce the issue? That would be very useful for us to try to understand what happens!

**Comment by srinathanand** [comment]
Sure, here are the steps -

1. We have a typical Java application running inside a container. It runs in JBoss and connects to a database.
2. A developer makes changes to a class file and wants to test this new class file inside the container by just copying the file over to the container.
3. He stops the container, uses docker cp to copy over the latest class file. The class file does not get copied over since the timestamp does not change. 
4. Trying to remove the file throws a "Stale File Handle". However, if he tries to rm some other file that wasn't touched then it works fine. So that proves that the state of the class file that was trying to be copied over using docker cp isn't looking good.

Let me know if you need more information.

**Comment by samoht** [comment]
@srinathanand Thanks. Unfortunately, the steps are not precise enough for me to reproduce the issue as I don't have your JBoss image, etc. It would be very helpful if you can try to help us to pin down that issue:
- does it happens when you run docker on Linux?
- are you able to reproduce it with a smaller example, which do not contain closed-source code and that you would be able to share it with us?
- could you try to reproduce the problem again and upload a new diagnostic bundle just after the error? The logs in the previous diagnostic are unfortunately incomplete due to log rotation.

**Comment by srinathanand** [comment]
- This happens when we are running Docker for Mac using Ubuntu trusty as a base image.
- We are not using a JBoss image. We are deploying a monolith inside a container and JBoss is started up when the container starts. We start off with Ubuntu trusty and build a base image and install a service release of our product on top of it. 
- I don't think we can share anything with you as far as closed source code but can definitely show you via a screen share or one of those methods.
- Sure, we will try and reproduce the problem again and send you the diagnostic bundle.

**Comment by srinathanand** [comment]
A new diagnostic has been created and uploaded - 0ED4508C-A52C-4EC7-8CE6-E764944F7CC6.
Update:
It seems that it happens with a text file as well and not limited to .class files. 

Thanks

**Comment by samoht** [comment]
Thanks, I am looking at your diagnostic. Does the size of the copied file makes a difference by any chance? Can you share the exact command that you run so I can try to find hints of what could have been going wrong in your logs? Thanks!

**Comment by srinathanand** [comment]
The size doesn't matter. In the most recent example it was a simple text file that was copied with the same results.

**Comment by samoht** [comment]
@srinathanand have you created your container with `-v` options? Do you try to copy the file into one of the shared directories?

**Comment by srinathanand** [comment]
No we haven't created it with the -v options. It is not a shared directory.

**Comment by samoht** [comment]
Can you reproduce this with an other container as well? As I cannot reproduce your error myself, any hint would help. The best thing would be to come up with the exact steps for me to follow to reproduce your issue on a minimal example (e.g. run: `docker pull xxxx &&& docker cp xxx yyy` where `xxx` and `yyy` are actually things than I can run on my computer).

**Comment by srinathanand** [comment]
We have one reported incident of this issue so far. We haven't tried it on another container but we definitely can try. Will get you the exact steps as well.

**Comment by srinathanand** [comment]
I have heard back from the person who reported the incident. It seems it is not reproducible now after pulling in a latest image of the product. Closing this issue.
