### ISSUE TITLE
Docker for mac falling to launch after update

### ISSUE THREAD

**Issue by yerinle** [docker/for-mac#1239]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cliffrowley** [comment]
This worked for me https://github.com/docker/for-mac/issues/1198

**Comment by yerinle** [comment]
Thanks also worked for me
