### ISSUE TITLE
Error when start Mac

### ISSUE THREAD

**Issue by AlfaIrawan** [docker/for-mac#1241]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Start Mac
  2. Login User

**Comment by samoht** [comment]
Please provide more information, as explained on https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues
