### ISSUE TITLE
Latest stable docker for mac: Communication with networking component failed.

### ISSUE THREAD

**Issue by iplantemn** [docker/for-mac#1245]
### Expected behavior

After an installation of Docker, it should start successfully

### Actual behavior

It asks for elevated privileges to install network components, and then shows a **Fatal Error** dialog with the following message:

Communication with networking component failed.

### Information

```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/8D5BA28D-C82C-4AF9-9621-F7A1FE51365A/20170201-093024.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/uplanis/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/uplanis/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/uplanis/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/uplanis/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/uplanis/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/uplanis/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

### Steps to reproduce the behavior

  1. Install Docker
  2. Start Docker
  3. Enter password to elevate privileges

**Comment by iplantemn** [comment]
Things I've tried:

- Completely uninstalling and reinstalling
- Installing the latest beta
- Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application

A few more things:

```
$ ls /Users/uplanis/Library/Containers/ | grep docker
com.docker.docker
com.docker.helper
$ ls -la /private/tmp/vmnetd/
ls: /private/tmp/vmnetd/: No such file or directory
```

**Comment by samoht** [comment]
Thanks for your report? When did you get this error? Did you upgrade from 1.12?

I can see in your logs a trace of qcow2 data corruption 2 days ago:

```
2017-01-26 09:25:05-06 BGTMNML-C67FFFT Docker[com.docker.driver.amd64-linux][2475] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure
2017-01-26 09:25:05-06 BGTMNML-C67FFFT Docker[com.docker.driver.amd64-linux][2475] <Notice>:   "Found a reference to cluster 75821 outside the file (max cluster 75817) from cluster 74.1152")
```

which is probably an old disk corruption that we are now detecting in 1.13 as we are running more aggressive disk checks. This lead to other issue with the install/upgrade. To fix your immediate issue try the following steps:

- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac

Hopefully this will (re-)install the networking helper process properly.

May be related to docker/for-mac#61

**Comment by iplantemn** [comment]
@samoht, I have tried deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting Docker, and the issue still occurs.

I completely uninstalled an older version of Docker, and upon installing this the latest (1.13) is when I get this error. I installed 1.13 today.

**Comment by samoht** [comment]
Ha sorry our messages crossed. Can you try `sudo launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist`

**Comment by iplantemn** [comment]
No worries, thanks for the help @samoht 

```
$ sudo launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
Password:
/Library/LaunchDaemons/com.docker.vmnetd.plist: Could not find specified service
```

**Comment by samoht** [comment]
By any chance, are you trying to run `Docker.app` out of your `/Applications` folder?

**Comment by iplantemn** [comment]
Yes, @samoht

**Comment by samoht** [comment]
Can you try to move `Docker.app` in `/Applications` and see if it's better? I am not sure why this is failing in your case, but it will probably help.

**Comment by iplantemn** [comment]
@samoht Sorry, I misread the question. I am running it from `/Applications` already.

I did try moving it out and launching the app from another directory, same issue. It's back in `/Applications`.

**Comment by samoht** [comment]
Ok thanks. Can you try to follow the instructions from https://github.com/docker/for-mac/issues/570#issuecomment-245966262 to try to uninstall the application fully?

**Comment by iplantemn** [comment]
That worked, @samoht! Thank you!
