### ISSUE TITLE
Diagnose or Diagnose & Upload fail immediately

### ISSUE THREAD

**Issue by mfeblowitz** [docker/for-mac#1247]
### Expected behavior
Diagnose produces diagnostics 
### Actual behavior
Window immediately shows
```
failure: Optional("diagnostic: response is not valid JSON")
```
in red.

### Information
Might be due to memory issue. Stopping all containers makes symptom disappear.

Version 1.13.0 (15072)
Channel: Stable
0c6d765c54

**Comment by samoht** [comment]
Can you share the output of:

```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose --json -n
```

This is not supposed to fail! :-)

**Comment by CvX** [comment]
I had the same issue when trying to report what I found to be #1315. Apparently when docker isn't able to launch, the `docker-diagnose --json -n` gives no output at all.
