### ISSUE TITLE
Error starting userland proxy, address already in use.

### ISSUE THREAD

**Issue by perrohunter** [docker/for-mac#1248]
So I had a bizarre bug trying to link two containers, I ended up install docker beta for mac (`1.13.1-rc1-beta40 (15241)`) and now I can't start previous containers I had because it thinks a certain port is in use. Going back to docker `1.13` for mac seems to do nothing

I'm trying to run nats
```
$ docker run -it -d --name nats -p 8222:8222 -p 4222:4222 -p 6222:6222 nats:0.9.6
```

I'm getting an error 

```
Error starting userland proxy: listen tcp 0.0.0.0:4222: bind: address already in use.
```

this also happens with other containers I have, that were working fine on docker 1.13 but not on beta.

things I've tried

* reset docker
* uninstall docker - restart machine - install docker
* remove container and re-add it
* netstat the port (nothing is using the port)
* lsof port (nothing is using the port)

How can I debug this issue? it's driving me crazy

Diagnostic: 2BED4C41-6BE3-4B66-8CEC-7E7202AB300A

full error

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint nats (3a9a552c3f3ddbd1a3ea32a0ac1f09f96e0971a0d3f28a59b87958ac8c1165e4): Error starting userland proxy: listen tcp 0.0.0.0:4222: bind: address already in use.
```

**Comment by samoht** [comment]
Thanks for your report!  Port 4222 is already bound inside the VM (that's the default containers listen port). We will fix that in the next release, but meanwhile you can try to configure `nats` to listen on a different port?

**Comment by perrohunter** [comment]
Switching to stable channel fixes this issue.

**Comment by justincormack** [comment]
Will be fixed in the beta channel in the release today.
