### ISSUE TITLE
docker for mac login registry 2.1 use v1 api lead to login failed !

### ISSUE THREAD

**Issue by linsheng9731** [docker/for-mac#125]
### Expected behavior
login private registry v 2.1 successed .
### Actual behavior
login registry with v1 api failed .
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

 The registry log : 
```
10.0.1.170 - user [04/Aug/2016:10:45:21 +0000] "GET /v1/repositories/growing_backen_kube/images HTTP/1.1" 404 19 "-" "docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.4.15-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \x5C(darwin\x5C))" "-"
```
### Steps to reproduce the behavior

  1. deploy docker registry 2.1
  2. use docker for mac try to login 
  3. the server return 404 , because the docker for mac use v1 api !

**Comment by samoht** [comment]
Could you tell us how to reproduce the issue? We are not shipping the registry in Docker for Mac, so I am a bit puzzled by your report.

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
