### ISSUE TITLE
Container linking not resolving with name. Can be influenced by /etc/hosts

### ISSUE THREAD

**Issue by perrohunter** [docker/for-mac#1250]
This is a hard one as this bug only happens on some machines, on some of my devs machines and not on other machines. Everyone is running macOS Sierra and latest stable channel 1.13.0

Upon creating a container with a link to another container, within the new container the name of the linked container cannot be resolved.

For example:

I created a `nats` container

```
docker run -it -d --name nats -p 8222:8222 -p 4222:4222 -p 6222:6222 nats:0.9.6
```
then had a custom application try to link it
```
docker run -p 8484:8484 --link nats  my-app
```
inside of my new container I can't reach `nats` by name, however I can access it by IP.

More over this strange behavior happens, if I have `nats` as a loopback interface in my `/etc/hosts` in the **host machine**, the name `nats` will try to resolve to 127.0.0.1, if I don't it tries to resolve to some other IP

With `127.0.0.1 nats` in `/etc/hosts` in the host machine 
**some golang code to get http://nats:8222/varz**
```
2017/02/02 17:47:32 Get http://nats:8222/varz: dial tcp 127.0.0.1:8222: getsockopt: connection refused
```

without `127.0.0.1 nats` in the `/etc/hosts` in the host machine
```
2017/02/02 17:42:14 Get http://nats:8222/varz: dial tcp 198.105.254.130:8222: i/o timeout
```

**Why is `/etc/hosts` influencing the resolve of names inside the container?**
**Why is the alias not working?**

To add weird to this issue I tried the following 

1.- Create a pure ubuntu container and link nats container
```
docker run -it --link nats ubuntu:14.04 bash
```
2.- install curl and get the desired url
```
# apt-get update
# apt-get install curl
# curl http://nats:8222/varz
```

This works as expected, the nats container gets linked and I can access it by name.

extra notes:
the `my-app` container was used building `FROM golang` then copying the binary into a `FROM tianon/true` container to create a lean container size.

**Comment by perrohunter** [comment]
I've created a sample project that reproduces this issue, clone this project, then execute `make`, run the `nats` container and then run the container with the link

https://github.com/perrohunter/lean-golang-docker-container

**Comment by perrohunter** [comment]
When deploying this containers to `kubernetes` they work as expected.

I've also found that if I change `tianon/true` to `alpine` it doesn't work, but using `ubuntu` does make the built container work as expected on **mac**

**Comment by ijc25** [comment]
@perrohunter thank for the repro. I did `make` in `lean-golang-docker-container` then:
```
docker run -it -d --name nats -p 8222:8222 -p 4222:4222 -p 6222:6222 nats:0.9.6
```
(cut and paste from above).

Then:
```
$ docker run -p 8484:8484 --link nats lean-golang-docker-container
{
  "server_id": "Ai6uMlBCagVNQj9cvmhZXd",
  "version": "0.9.6",
  "go": "go1.7.4",
  "host": "0.0.0.0",
  "auth_required": false,
  "ssl_required": false,
  "tls_required": false,
  "tls_verify": false,
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 1024,
  "cluster": {
    "addr": "0.0.0.0",
    "cluster_port": 6222,
    "auth_timeout": 2
  },
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2017-02-20T11:53:22.444749218Z",
  "now": "2017-02-20T11:54:04.889587907Z",
  "uptime": "42s",
  "mem": 5312512,
  "cores": 2,
  "cpu": 0,
  "connections": 0,
  "total_connections": 0,
  "routes": 0,
  "remotes": 0,
  "in_msgs": 0,
  "out_msgs": 0,
  "in_bytes": 0,
  "out_bytes": 0,
  "slow_consumers": 0,
  "subscriptions": 0,
  "http_req_stats": {
    "/": 0,
    "/connz": 0,
    "/routez": 0,
    "/subsz": 0,
    "/varz": 1
  }
}2017/02/20 11:54:04 nats-x
2017/02/20 11:54:04 1020
2017/02/20 11:54:05 Get http://nats-x:8222/varz: dial tcp: lookup nats-x on 192.168.65.1:53: no such host
2017/02/20 11:54:06 &{0xc420122000 0x844628}
```
(adjusted from above)

I think this means it is working? The first JSON blob is from `http.Get("http://nats:8222/varz")` while the failure to talk to `nats-x` is expected and the final `&{0xc420122000 0x844628}` is the result of the successful `nats.Connect("nats://nats:4222")` at the end?

This was with 1.13.1-beta42. Stable release 1.13.1 was based on beta42 so that ought to be fixed as well. Can you confirm? I'll close on that assumption, please reopen if I am wrong.
