### ISSUE TITLE
Docker cannot launch after upgrade. 

### ISSUE THREAD

**Issue by hrqiang** [docker/for-mac#1251]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Upgrade to new version of docker 
  2. On launch there is an error saying xfce driver and the application quit.

**Comment by samoht** [comment]
Can you please add a diagnostic ID as described in https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues? Thanks!

**Comment by samoht** [comment]
I am closing this issue for lack of information that we can use to help you, but please feel free to create a new ticket more more info and a diagnostic ID.
