### ISSUE TITLE
docker-compose really really slow

### ISSUE THREAD

**Issue by sthakor1** [docker/for-mac#1252]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Can you please re-open an issue with more details, as described in https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues.

Thanks!
