### ISSUE TITLE
Terrible 1.13.0 performance compared to 1.12.6

### ISSUE THREAD

**Issue by virusdave** [docker/for-mac#1253]
### Expected behavior
1.13.0 is about as performant as 1.12.6

### Actual behavior
1.13.0 is much, much worse.

### Information
Running the same docker container in both (a postgres DB), the container is live and accepting connections in ~1.5s in 1.12.6, but takes ~45s to do so with 1.13.0

This is on a relatively new macbook w/ 16GB ram and a SSD.

Let me know what info would help debug this.

**Comment by samoht** [comment]
Could you also try to enable the "fast but unsafe" flush workaround described in https://github.com/docker/for-mac/issues/668#issuecomment-250406582 and see if that makes a difference?

If not, could you provide a diagnostic ID taken just after your postgress container has started?

Thanks!

**Comment by virusdave** [comment]
Sure, will do this when i have a chance.

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
