### ISSUE TITLE
Just a note to say High CPU usage on OSX seems fixed (macOS 10.12.3)

### ISSUE THREAD

**Issue by aphillipo** [docker/for-mac#1257]
### Expected behavior

Docker doesn't use much CPU when polling/watching/etc.

### Actual behavior

Docker used to use lots of CPU on this MacBook as soon as you watched files either inside or outside the container.

### Information

I guess I'm leaving this here as a note to anyone using docker for Mac and experiencing high cpu usage.

### Steps to reproduce the behavior

  1. Pre 10.12.3 -> High CPU
  2. After 10.12.3 -> Low/No CPU.

Well played docker team!  Feel free to close this but it's nice to see it fixed at the OS level and isn't your code!

**Comment by samoht** [comment]
Thanks very much, it is nice to hear about positive feedback too! I am closing the issue, but I will notify the team that their hard work is paying off :-)
