### ISSUE TITLE
Docker can't start after update

### ISSUE THREAD

**Issue by AlexTes** [docker/for-mac#126]
### Information

Diagnostic ID: 143DACEA-3743-439F-8632-AD4CE1EE5A0E
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Update docker to the latest version
2. Start docker

CLI commands now fail as follows.
`docker version` outputs:
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine
```

**Comment by ch2ch3** [comment]
Same issue. I had to reset Docker to factory settings to get around it.

**Comment by AlexTes** [comment]
Thanks so much @ch2ch3! I didn't know the option or any other options for that matter lived outside the cli. A reset, handful of sigkills and a reboot later my docker seems to be back. 

I'll leave this open. Maybe the docker team can learn from it still and more users will likely update and run into this.

**Comment by mchiang0610** [comment]
Merging with #119
