### ISSUE TITLE
Crash after reboot...

### ISSUE THREAD

**Issue by Angelfirenze01** [docker/for-mac#1267]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

4038DBDB-0A30-42B4-A8B5-8AEA6FB1683A

**Comment by dave-tucker** [comment]
This issue has been identified as being of poor quality. It's an > 89% match to our issue template. Please see [this document](https://docs.docker.com/docker-for-mac/troubleshoot) for instructions on how to open a well formatted issue. Please be sure to include your Diagnostic ID as well as any reproduction steps, including Dockerfiles or docker-compose.yml if necessary.

**Comment by Angelfirenze01** [comment]
I'll delete this issue and write a proper new one.
