### ISSUE TITLE
failed to start when starting the laptop

### ISSUE THREAD

**Issue by norris-zhang** [docker/for-mac#1269]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
Thanks for the report, @norris-zhang.  Unfortunately, without more information (such as a diagnostic id) there's nothing we can do to investigate.  If the problem persists, could you please open a fresh issue with more information?

There are some details about investigating and reporting problems here:

   https://docs.docker.com/docker-for-mac/troubleshoot/

**Comment by norris-zhang** [comment]
Thanks. The problem disappeared when I quit the app and started again. Then I don't have problem again the next time I start my laptop. So it might be because of my sudden unstable env like network env or something. Don't worry about it at the moment. I will report with detailed info next time. Thank you for your time.

Sent from my iPhone

On 10 Feb 2017, at 00:04, yallop <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1269<https://github.com/docker/for-mac/issues/1269>.
