### ISSUE TITLE
Can't ping or access HTTP server on a docker container

### ISSUE THREAD

**Issue by sylvaindeloux** [docker/for-mac#127]
### Expected behavior
Installed a simple HTTP server (debian + nginx), but can't access.

### Actual behavior
Host not found.

### Information
```
Diagnostic ID: 18549C22-058F-4D55-9D2B-B59CF9230CE2
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

### Steps to reproduce

1. Build a nginx (stable) container
2. Run (with port 80 exposed)
3. Can't open nginx default page on `127.0.0.1`, `localhost` or even `172.17.0.…` (given by `docker inspect` command)

As seen on many forum posts, I've already tried to reinstall Docker, reboot, etc

**Comment by dsheets** [comment]
Could you please post the exact commands you are using to build and run the container?

**Comment by sylvaindeloux** [comment]
The simplest test I've made : 

    docker run -t -i nginx

The `docker ps` command gives me :

    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    c3f226db226a        nginx               "nginx -g 'daemon off"   5 minutes ago       Up 5 minutes        80/tcp, 443/tcp     amazing_yonath

I retrieve the IP with `docker inspect amazing_yonath | grep -i IPAddress` : 

    ...
    "IPAddress": "172.17.0.3",
   ...

But can't access this IP or even ping it.

**Comment by dsheets** [comment]
I believe you need to run `docker run -it -p 80:80 nginx` and this behavior is the same on Linux.

**Comment by dsheets** [comment]
See also: https://docs.docker.com/engine/reference/builder/#expose
