### ISSUE TITLE
requested access to the resource is denied

### ISSUE THREAD

**Issue by StokeMasterJack** [docker/for-mac#1271]
I am running the push command same as I always do:

  docker push stokemasterjack/ramko-tomcat:106

and I am now getting the error:

  denied: requested access to the resource is denied

I ran Diagnose & Upload and got this ID:

  F3ED1A4F-46DF-432B-8B08-317485AC504E

The only thing that I can think may have changed: I may have said YES to a docker update.

My last successful push was 2 months ago. I am currently using:

Docker version 1.13.0, build 49bf474

**Comment by StokeMasterJack** [comment]
Duh. I needed to login again. Perhaps a better error message would be helpful. Like: you are no longer logged in.

**Comment by sg1970** [comment]
Iam facing the exact same issue and re-logging in again did not help for me. My last succesful push was about a month or so ago.

-----------
c:\Docker>docker push myiis
The push refers to a repository [docker.io/library/myiis]
47f5e43a4809: Preparing
b06178850402: Preparing
5b4aace84103: Preparing
1f2f3eb32edc: Preparing
0451551dda21: Preparing
c28d44287ce5: Skipped foreign layer
f358be10862c: Skipped foreign layer
denied: requested access to the resource is denied

c:\Docker> docker version
---------------
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      windows/amd64
 Experimental: true

**Comment by yallop** [comment]
I'm closing this, since it's a general Docker issue, rather than something specific to Docker for Mac.  If you'd like to continue the discussion, could you please open an issue upstream (https://github.com/docker/docker/issues)?

**Comment by MikeAshby** [comment]
How can you close this? Docker is unusable?

**Comment by mrcoles** [comment]
Slight variation of this happened to me. The account had an expired credit card on it, and it appears that it automatically dropped to the "free" plan from a paid plan. So, despite entering a new card, it was still on the free plan and would no longer let me push new images until I updated that on the billing page 😮
