### ISSUE TITLE
Having an existing DOCKER_HOST variable messes things up

### ISSUE THREAD

**Issue by igmar** [docker/for-mac#1274]
### Expected behavior

Warning / error on install

### Actual behavior

It tried to connect to the host configured in DOCKER_HOST

### Steps to reproduce the behavior

Set DOCKER_HOST to host without docker on it, the cmdline then appears to be hanging.

**Comment by guillaumerose** [comment]
Is there a specific command that hangs ? I tried `DOCKER_HOST=blah docker ps` and it fails instantly.
