### ISSUE TITLE
docker beta for osx not working

### ISSUE THREAD

**Issue by nelsonenzo** [docker/for-mac#1276]
### Expected behavior
docker to work locally on my mac

### Actual behavior
- says that it is running in the top menu bar.
- docker ps works (in this instance, but not always) 
- docker build . just hangs there.  fun times.

I have to quit docker and restart it to work again.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. run docker beta on your macbook
  2. close the lid for just a bit
  3. open the lid
  4. try to do something with docker.  it might work....it might not!  fun times.
  5. Diagnostic says everything is "ok"

**Comment by yallop** [comment]
Thanks for the report, @nelsonenzo.  Could you please provide a diagnostic ID so that we can investigate the problem?  There's more information about reporting issues here: https://docs.docker.com/docker-for-mac/troubleshoot/

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
