### ISSUE TITLE
Docker issue on start

### ISSUE THREAD

**Issue by pablohpsilva** [docker/for-mac#1280]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
I'm closing this because there's nothing to investigate here.  If you'd like to report an issue, please provide at least a [diagnostic id](https://docs.docker.com/docker-for-mac/troubleshoot/) and a description of the problem.
