### ISSUE TITLE
Mapping a host system file to a container creating a directory

### ISSUE THREAD

**Issue by dmccullo** [docker/for-mac#1282]
### Expected behaviour
In 1.12.* this command mapped two files on my host machine to files inside the container.
docker run --name dba2 **-v /MYSQL-CFG/my-sync-conf.cfg:/etc/my_new.cnf** **-v /MYSQL-CFG/home_my_cnf:/root/home_my.cnf** -v /media/data/:/var/lib/mysql/ -P -p 3306:3306 -e MYSQL_ROOT_PASSWORD=******** -d --restart=always mysql/mysql-server:5.6
### Actual behaviour
in 1.13.* this command now creates a directory with the file name as the name of the directory.

### Information
here is what is happening in the container:
in /root/
**drwxr-xr-x  2 root root 4096 Feb  9 20:23 home_my.cnf**
in /etc/
**drwxr-xr-x  2 root root   4096 Feb  9 20:23 my_new.cnf**

### Steps to reproduce the behavior

  1. Create a directory on the host with these two files in it.
  2. run this command on 1.12.* docker for mac 
it will create a file in /root named home_my.cnf in the container dba2
it will create a file in /etc named my_new.cnf in the container of dba2
 3. upgrade to 1.13.* and 
it will create a directory in /root named home_my.cnf in the container dba2
it will create a directory in /etc named my_new.cnf in the container of dba2

This makes it impossible to deploy a mysql database container following Oracles best practices.

**Comment by yallop** [comment]
Thanks for the report, @dmccullo.  Can you confirm that the files

```
/MYSQL-CFG/my-sync-conf.cfg
/MYSQL-CFG/home_my_cnf:/root/home_my.cnf
```
exist on the host?

**Comment by dmccullo** [comment]
Figured it out!  docker-machine sip created directories LOL
