### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by mirajshah05** [docker/for-mac#1285]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dave-tucker** [comment]
This issue has been identified as being of poor quality. It's an > 88% match to our issue template. Please see [this document](https://docs.docker.com/docker-for-mac/troubleshoot) for instructions on how to open a well formatted issue. Please be sure to include your Diagnostic ID as well as any reproduction steps, including Dockerfiles or docker-compose.yml if necessary.
