### ISSUE TITLE
Docker push is super slow to remote repositories

### ISSUE THREAD

**Issue by buchireddy** [docker/for-mac#1286]
Pushing a Docker image of 200MB is taking forever.

### Expected behavior
The docker push to be done in few seconds.

### Actual behavior
The push takes forever to finish.

### Information
Diagnostic ID: F92BFE0F-0D16-4A4D-A9BE-15646CD666BC

### Steps to reproduce the behavior
The push was working fine a while ago and suddenly it started happening. I tried to increase the CPU and memory for Docker daemon, restarted it, upgraded to the latest version, restarted my Mac but none of it has helped. A colleague of mine had similar issue few days ago and it was fixed for him when he upgraded Docker to latest version.

**Comment by dave-tucker** [comment]
Thanks for opening the issues @buchireddy
I've taken a look at the logs and unfortunately this looks like a connectivity issues to your registry provider. I see multiple TCP Zero Window packets sent to our network stack from ECR which means that it's unable to receive any more data. The problem appears to be their side, or somewhere en-route.

I also see in the logs repeated entries along the lines of `"Attempting next endpoint for push after error: denied: Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one."` in the logs. I can't say for certain when this happens but it's worth noting that this may be a cause of failed pushes.

It would be helpful to us to know if it's just one network location in particular that's giving you trouble and also when you experience a slow push to ECR whether pushes to Docker Hub are slow too (any image will do). This would help rule out Docker for Mac as the source of the issue.

**Comment by buchireddy** [comment]
Thanks for checking out the logs @dave-tucker 

I have experienced the slowness to yet another private Docker registry during that window. Did you see any errors related to slowness in pushing to a registry with "gitlab" in the URL? I've not tried pushing to public Docker Hub but I'll try that and update this issue.

Reg the token expiration, this is being taken care and it's only one off issue because the token keeps on expiring every day.

**Comment by buchireddy** [comment]
Hi @dave-tucker 

I've tried to push image to Docker Hub. Though the rate at which the push to Docker Hub was marginally faster than pushing to ECR, I think it was very slow as per the usual speeds.

I have tried uninstalling Docker completely and re-installed it but it still didn't help. Weirdly, Diagnose & Feedback is taking forever and isn't uploading the logs now. I've gathered some logs from Docker. Please check if these will be of any help.

```2/13/17 10:49:09.816 PM Docker[88893]: BOOTREQUEST from c0:ff:ee:c0:ff:ee
2/13/17 10:49:09.817 PM Docker[88893]: BOOTREPLY to c0:ff:ee:c0:ff:ee yiddr 192.168.65.2 siddr 192.168.65.1 dns 192.168.65.1 router 192.168.65.1 domain 
2/13/17 10:49:09.890 PM Docker[88892]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /host_docker_app
2/13/17 10:49:09.891 PM Docker[88892]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
2/13/17 10:49:09.892 PM Docker[88892]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /tmp
2/13/17 10:49:09.893 PM Docker[88892]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Volumes
2/13/17 10:49:09.895 PM Docker[88892]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Users
2/13/17 10:49:09.895 PM Docker[88892]: Negotiated transfuse notification channel for /host_docker_app
2/13/17 10:49:09.895 PM Docker[88892]: Negotiated transfuse notification channel for /private
2/13/17 10:49:09.895 PM Docker[88892]: Negotiated transfuse notification channel for /tmp
2/13/17 10:49:09.895 PM Docker[88892]: Negotiated transfuse notification channel for /Volumes
2/13/17 10:49:09.895 PM Docker[88892]: Negotiated transfuse notification channel for /Users
2/13/17 10:49:09.895 PM Docker[88892]: sending continue to client
2/13/17 10:49:09.959 PM Docker[88895]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
2/13/17 10:49:10.078 PM Docker[88893]: Using protocol TwoThousand msize 8192
2/13/17 10:49:11.970 PM Docker[88895]: Docker is responding
2/13/17 10:49:11.981 PM Docker[88894]: Failed to read the last-shutdown-time key: 9p: No such file or directory
2/13/17 10:49:11.981 PM Docker[88894]: VM started at 2017-02-13 22:49:11 -0800 PST
2/13/17 10:50:16.198 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:50:16.199 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:50:16.199 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:05.120 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:05.120 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:05.120 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:45.266 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:45.266 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:51:45.266 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:53:56.668 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:53:56.668 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:53:56.668 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:54:11.337 PM Docker[88865]: TextView: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
2/13/17 10:54:11.559 PM Docker[88865]: Analytics: Sent actionMenuFeedback event.
2/13/17 10:54:14.136 PM Docker[89251]: EOF reading packet from Unix domain socket: closing
2/13/17 10:54:14.137 PM Docker[89251]: Failed to read hello from client
2/13/17 10:54:14.137 PM Docker[88893]: Using protocol TwoThousandU msize 8215
2/13/17 10:54:52.200 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:54:52.200 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
2/13/17 10:54:52.200 PM Docker[88893]: 127.0.0.1:0: dispatcher shutting down: read: Eof
```

**Comment by buchireddy** [comment]
I think I was running into #1268, because of which the Diagnose & Feedback wasn't working.

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by buchireddy** [comment]
@rogaha I have provided more information after the status was changed. Wasn't it helpful? I don't think this issue is resolved. Almost all of my colleagues are running into this exact same issue.

**Comment by rogaha** [comment]
@buchireddy I'm re-opening it. Sorry about that, I was using a new `internal` support tool and closed it by mistake!

**Comment by MagnusS** [comment]
@buchireddy Are you still experiencing this with the latest version of Docker for Mac? (currently 17.03-ce-mac2)

The issue reported in #1268 is a log problem with a beta version of macOS Sierra 10.12.4. If you are running 10.11.x (as reported in the logs) this issue is probably unrelated.

**Comment by buchireddy** [comment]
@MagnusS I haven't got a chance to try out yet with the latest Docker update. I've just updated to the latest version. I'll update this issue if I run into any issues.

**Comment by avsm** [comment]
@buchireddy - I just wanted to check in to see if you have seen this issue in the past couple of weeks since the update or not?

**Comment by buchireddy** [comment]
@avsm I've not run into this issue recently. I can update here if I face this issue again.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
