### ISSUE TITLE
Apt get references ubuntu xenial however uname is moby

### ISSUE THREAD

**Issue by bootstraponline** [docker/for-mac#1289]
### Expected behavior

Apt get install succeeds.

### Actual behavior

Apt get install fails.

### Steps to reproduce the behavior

-     1. RUN DEBIAN_FRONTEND=noninteractive apt-get install -y linux-image-extra-`uname -r`
-     2. Unable to locate package linux-image-extra-4.9.8-moby

This seems like a common issue however I didn't find a solution online. The image is suppose to be for Ubuntu xenial however uname returns moby.

**Comment by justincormack** [comment]
Yes, that only works on a Debian system. You need to look up the actual available packages.

**Comment by bootstraponline** [comment]
Is there any guidance on how to do that? I'm guessing that involves hard coding package names

Or is it better to just run docker in a Ubuntu VM?

**Comment by bootstraponline** [comment]
`lsb_release -cs` seems to be a good work around.

https://github.com/bitrise-docker/bitrise-base/pull/80
