### ISSUE TITLE
Docker daemon crashed after system started

### ISSUE THREAD

**Issue by piyushkv1** [docker/for-mac#1291]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.5 (build: 15F34)
logs: /tmp/4AD6C936-87D2-4F38-B82E-62A862C22EE2/20170212-105847.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/piyushv/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/piyushv/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/piyushv/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/piyushv/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/piyushv/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by dave-tucker** [comment]
@piyushkv1 Could you provide some more information about this issue?
What were you doing when Docker crashed? How did it crash?
Where you able to workaround it?

**Comment by michaelarichard** [comment]
Same issue. Worked fine previously. Restarted mac, and now docker will not run. Reinstalled, no change. Rebooted again. No change. 

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/063EF47C-2C64-4B54-AE7F-B8EB1B32C219/20170213-110544.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mrichard/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mrichard/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mrichard/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mrichard/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mrichard/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mrichard/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by ijc25** [comment]
@piyushkv1 I noticed in your logs:
```
2017-02-12 10:58:30+05:30 piyushv-m02 Docker[com.docker.docker][1051] <Notice>: CrashReport: stderr redirected to /var/folders/k5/8bp7t7x10qqdl8b2_97s9hg000_z3l/T/Dockererr.txt
```
which is something in common with #1312. Please could you have a look in that file and send us its contents.

It would also be useful if you could also answer the various questions in https://github.com/docker/for-mac/issues/1312#issuecomment-281412663

@michaelarichard I'm afraid your diagnostic ball didn't make it to our server so I can't tell if you have the same issue (the symptom of not starting is common to several issues). Could you please run Diagnose & Feedback from the :whale: menu, select Diagnose & Upload and open a fresh ticket with your details.

**Comment by ijc25** [comment]
Please disregard the questions in https://github.com/docker/for-mac/issues/1312#issuecomment-281412663 mentioned above. I think all we actually need to make progress is the contents of `/var/folders/k5/8bp7t7x10qqdl8b2_97s9hg000_z3l/T/Dockererr.txt`, this turns out to be one of our logs but which is not collected by our diagnostics process (I've created an internal issue for this).

**Comment by michaelarichard** [comment]
/var/folders/k5/: No such file or directory

063EF47C-2C64-4B54-AE7F-B8EB1B32C219

**Comment by michaelarichard** [comment]
➜  folders ls -lisa ./6_/bc05gkx93n10t1phsk4mq1zhs9dh0n/T/Dockererr.txt
7589951 0 -rw-r--r--  1 mrichard  AMER\Domain Users  0 Feb 22 11:42 ./6_/bc05gkx93n10t1phsk4mq1zhs9dh0n/T/Dockererr.txt
➜  folders cat ./6_/bc05gkx93n10t1phsk4mq1zhs9dh0n/T/Dockererr.txt
➜  folders pwd
/var/folders

**Comment by ijc25** [comment]
@michaelarichard your issue is something else, see docker/for-mac#1315.

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
