### ISSUE TITLE
Docker stalls

### ISSUE THREAD

**Issue by himslm01** [docker/for-mac#1292]
### Expected behavior
docker CLI does not hang.

### Actual behavior
docker CLI hangs.

### Information
I have been using Docker for Mac all day, but after building many gigabytes of images, the CLI just hangs. Docker.qcow2 is 66GB - but I'd expect that because of the size and number of images I've built.

Docker for Mac: version: 1.13.1-beta42 (2ffb2b491)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/AB00D26A-D315-419D-BFAF-F495C67D4E9A/20170212-193531.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk

**Comment by dave-tucker** [comment]
@himslm01 thanks for the report. I've checked the logs and I don't see anything suspicious. It looks as if the docker process may have crashed in the VM (after it had started successfully) but unfortunately the logs needed to debug are missing from the diagnostic bundle 😖

Have you tried resetting Docker for Mac (from the 🐳 menu)?

It would also be interesting to know what commands are hanging...
The new `docker container prune` and `docker image prune` may also help in keeping the size of your disk image down.

**Comment by ijc25** [comment]
@himslm01 please could you attach the contents of `/var/folders/t5/_zdhlxzd0n1_pf8s9kqm32wm0000gn/T/Dockererr.txt` to this ticket.

**Comment by seehuhn** [comment]
This may be the same issue as #1337?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
