### ISSUE TITLE
Cannot update Docker from behind a proxy on OS X Sierra.

### ISSUE THREAD

**Issue by erip** [docker/for-mac#1295]
### Expected behavior

Should be able to update docker daemon from menu bar.

### Actual behavior

> Update Error!
> 
> An error occurred in retrieving update information. Please try again later.

### Information

Diagnose:

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/F267A384-D7B2-4044-B377-C906928C65E1/20170213-111920.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Syslog (relevant errors):

![help](http://i.imgur.com/5QCnZEq.png)

### Steps to reproduce the behavior

1. Be behind proxy
2. Manually set proxy variables.
3. Try to update with menu bar
4. ???
5. (Don't) profit.

**Comment by erip** [comment]
FWIW, I can successfully pull images from external docker repos. The proxy issue is only when trying to update.

**Comment by dave-tucker** [comment]
@erip can you try browsing to https://download.docker.com/mac/beta/appcast.xml and let me know what happens? It looks like it could be being blocked by your proxy server (Note: The GUI doesn't use the proxy settings in the Docker for Mac preferences, it call's OSX's API's directly which handle all of that for you).

**Comment by erip** [comment]
@dave-tucker Thanks for the response. I was able to hit the XML in the browser just fine. 

```<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
<channel>
<title>Docker for Mac</title>
<link>
https://download.docker.com/mac/beta/15350/Docker.dmg
</link>
<item>
<title>1.13.1-beta42 (15350)</title>
<description>
<![CDATA[
<ul> <li>Upgrades <ul> <li><a href="https://github.com/docker/docker/releases/tag/v1.13.1">Docker 1.13.1</a></li> <li><a href="https://github.com/docker/compose/releases/tag/1.11.1">Docker Compose 1.11.1</a></li> </ul></li> </ul>
]]>
</description>
<pubDate>2017-02-09T21:56:45Z</pubDate>
<enclosure url="https://download.docker.com/mac/beta/15350/Docker.dmg" sparkle:version="15350" sparkle:shortVersionString="1.13.1-beta42" length="110942449" type="application/octet-stream"/>
</item>
</channel>
</rss>
```

I also checked `$http_proxy`, `$https_proxy`, `$HTTP_PROXY`, and `$HTTPS_PROXY` -- all set to the correct corporate proxy address.

**Comment by ijc25** [comment]
Hi @erip,

I can't find your diagnostics on our server. Could you please run Diagnose & Feedback from the :whale: menu, select Diagnose & Upload again, and paste the results of the new diagnostic run (including diagnostic ID) back here?

Did you use Safari to fetch the XML you pasted above? I wouldn't expect it to care about any of the `$http_proxy` env vars but instead to use whatever is in the MacOS preference panel, although I expect that is also correct given you can fetch the file.

**Comment by erip** [comment]
I hadn't uploaded before -- just diagnosed. 

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/F267A384-D7B2-4044-B377-C906928C65E1/20170222-101456.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

Diagnostic ID: _**F267A384-D7B2-4044-B377-C906928C65E1**_

**Comment by ijc25** [comment]
Thanks, but:
> Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

:-(.

This is no doubt down to the same proxy issue. I see now that we have an internal ticket open on the subject of diagnostics vs proxies, sorry for the run around. I've flagged this issue on that.

I can't see an existing update vs proxy issue internally so I'm going to open one on the basis of the information you've provided so far.

Thanks for your report.

**Comment by erip** [comment]
No problem at all! Look forward to the fix. 😄 Wish I could of more help. Glad that the proxy works when pulling images at least.

Cheers.

**Comment by erip** [comment]
Found the problem... I'm embarrassed to admit it was a very silly one.

In `System Preferences > Network > Advanced > Proxies`, I accidentally added `http://` to both the HTTP and HTTPS proxies. This caused some problems, but seems to work now.
