### ISSUE TITLE
Docker for Mac hanging, maybe due to too many containers?

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1296]
### Expected behavior

Docker for Mac should remain responsive even if under stress.

### Actual behavior

Was starting up my containers and the env seems to be hung (`docker ps` hangs).

### Information

Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/556C7035-A293-4F5F-BE74-926C77AF8030/20170213-103152.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Don't know will try upgrading to new release.

**Comment by EdvardM** [comment]
I've had similar behaviour every now and then, ie. `docker ps` never returns. Restarting docker has fixed the issue though. I don't have many images/containers, I love to run docker-clean tool pretty often.

**Comment by ijc25** [comment]
@jamshid,

thanks for your report. The diagnostic output seems to think everything is OK and I don't see anything untoward in the logs. Please could you try and gather a diagnostic while the issue is occurring (or ASAP afterwards) and post the new diagnostic id here.

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
