### ISSUE TITLE
Dialog boxes in wrong workspace and unclickable

### ISSUE THREAD

**Issue by kojiromike** [docker/for-mac#13]
### Expected behavior

When I try to interact with a dialog box it should stay put and be interactive.
### Actual behavior

Under certain conditions, dialog boxes stay in inaccessible workspaces and don't respond to input.
### Information

Diagnostic ID: 9BE8F762-EE93-4099-906F-7AA69C221050
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. If I open a dialog box (Preferences, for example) while in a full screen workspace, I get switched to the desktop workspace, but the dialog box stays in the other workspace.
2. If I switch back to the workspace with the dialog box and try to click on it, I get switched back to the desktop workspace again.
3. If I switch back to the workspace with the dialog box, make the underlying application not fullscreen, then the Docker dialog box moves to the desktop workspace, but I still cannot interact with it. I can't even close the dialog box or access the Docker quit menu at that point.

**Comment by dave-tucker** [comment]
Thanks for the issue report! We're tracking this and hope to have a resolution soon!

**Comment by djs55** [comment]
This still reproduces for me too.

**Comment by ijc25** [comment]
Our internal issue tracking this was closed in mid-September, so the fix should be in all recent betas and stable releases. Closing, please reopen if it is not fixed for you.
