### ISSUE TITLE
com.docker.hyperkit high CPU and containers randomly die

### ISSUE THREAD

**Issue by jwalton** [docker/for-mac#1308]
### Expected behavior

Docker for Mac shouldn't randomly terminate containers, shouldn't take up all the CPU, and shouldn't make my Mac sound like a jetplane.

### Actual behavior

Not the expected behavior.  If you run through the "Steps to Reproduce" below, you'll try to set up Consul server and an ELK stack.  You'll get high CPU usage, and elasticsearch will be terminated for seemingly no reason.

Weirdly, if you change the order of the commands below to run Consul last instead of first, elasticsearch will not be terminated (even though Consul and ES are running on different networks and don't interact with each other), although you'll still end up with com.docker.hyperkit at > 160% CPU, and a Mac that will melt through your desk.

I've confirmed this problem on both my machine and a co-workers machine.

### Information

  - Diagnostic ID: 520CF407-A49D-4A4C-A4EB-FFEF79182548

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.4 (build: 15E65)
logs: /tmp/520CF407-A49D-4A4C-A4EB-FFEF79182548/20170215-165821.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

* Reset docker (v1.13.1 stable) to factory defaults (Docker -> Preferences -> Reset -> Reset to factory defaults).
* Open the activity monitor and find com.docker.hyperkit in the CPU tab (easy to find when you start running commands below - it'll be near the top.)
* Run

        docker run --name consul -d -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h $(hostname -s) progrium/consul \
                -server -advertise 127.0.0.1 -bootstrap-expect 1 -ui-dir /ui
        docker network create elk
        docker run -it -d --net elk --name elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.0.2

* Wait for com.docker.hyperkit CPU usage to fall back to single digits.

* Run

        docker run -it -d --net elk --name logstash -p 9998:9998 logstash:5.0.2 \
            -e 'input { tcp { port => "9998" codec => json } } output { elasticsearch { hosts => "elasticsearch" } }'

* com.docker.hyperkit CPU usage will spike (on my machine into the high 200s low 300s) and then fall to a new "stable" (on my machine, around 170%).

* Run

        docker run -it -d --net elk --name kibana -e ELASTICSEARCH_URL=http://elasticsearch:9200 -p 5601:5601 kibana:5.0.2

* As soon as kibana starts up, com.docker.hyperkit's CPU usage will fall back into the single digits, but running `docker ps` reveals that the elasticsearch container has died.  `docker logs elasticsearch` shows that elasticsearch didn't output any errors.

**Comment by jwalton** [comment]
Confirmed that this issue does not occur on https://download.docker.com/mac/stable/1.12.6.14937/Docker.dmg.

**Comment by dave-tucker** [comment]
@jwalton Could try to enable the "fast but unsafe" flush workaround described in #668 (comment) and see if that makes a difference? Re: random container termination have you checked that you have enough memory allocated to Docker in "🐳 -> Preferences". From your logs, I see our oom killer reaping containers as there isn't enough memory!

**Comment by jwalton** [comment]
Under docker 1.12.6, I'm running the same setup (with some actual data in Elasticsearch) and if I use `screen` to attach to the VM and run top:

```
Mem: 1923852K used, 121716K free, 43776K shrd, 7056K buff, 94568K cached
```

So, there's certainly not a ton of memory free.

I tried running with the "fast but unsafe" flush (from [this comment](https://github.com/docker/for-mac/issues/668#issuecomment-250406582) right?) and bumped up the VM to 3GB of RAM, and it seems to have helped.

**Comment by dave-tucker** [comment]
@jwalton yes that was the link - sorry! Glad it's helped. Keep an eye on and if it dies again for any reason let us know.

**Comment by macpham** [comment]
FYI Dave I'm Jason's co-worker and your suggestion above seems to be working well for both of us.

**Comment by dave-tucker** [comment]
Great, in that case I'm going to go ahead and close this issue - we're currently tracking an enhancement where we'll send you a notification if your containers are using too much memory but currently no ETA for that as yet! Hopefully it will be coming to a CHANGELOG near you in the near future.
