### ISSUE TITLE
Provide a "Reset Containers/Image" button

### ISSUE THREAD

**Issue by errordeveloper** [docker/for-mac#1309]
### Expected behavior

Memory and CPU settings persisted on reset.

### Actual behavior

Memory and CPU settings are reset and it take another restart to change these, easy to forget when resetting in anger.

**Comment by justincormack** [comment]
Part of the point of reset is total reset though; it is hard to tell what is "safe". What are you trying to reset in anger? eg you could just delete the qcow file to remove all Docker state without affecting host state...

**Comment by dave-tucker** [comment]
@errordeveloper based on @justincormack's comments I'm tempted to close as a `wontfix`.
Resetting in anger sucks - we know that - but what we want to do is to make it so you don't need to do it so often. A "Reset image/container storage" button might be the happy middle ground but I'll wait to hear from you to see what you think.

**Comment by errordeveloper** [comment]
> eg you could just delete the qcow file to remove all Docker state without affecting host state...

Ah, ok, that'll do 👍 

Thansk @justincormack and @dave-tucker :)

**Comment by errordeveloper** [comment]
> A "Reset image/container storage" button might be the happy middle ground but I'll wait to hear from you to see what you think.

I think it'd be great to have this button.

**Comment by dave-tucker** [comment]
Ok, it's now on the internal tracker tagged for attention from the UI team.
We'll post back here when we have an update!
