### ISSUE TITLE
App Crashes on macOS 10.12 (Sierra) - Beta 4

### ISSUE THREAD

**Issue by mfinholt** [docker/for-mac#131]
### Expected behavior
App runs as expected

### Actual behavior
Every time I start the app, it crashes at random intervals with a "CMSTATEEVENT INVALID JSON" error. Note that I am not doing anything with the app when it crashes (no containers running or anything).

I am running the Beta 4 version of macOS Sierra so I'm not surprised about this behavior but you'lll probably want to look into it prior to the release of the new macOS in a month or two

### Information

Diagnostic ID: 1A450397-D79B-442A-B388-48010826C978
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f) - BETA 4
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install app (stable or beta)
2. wait for it to error out

**Comment by mfinholt** [comment]
I closed this issue because it's well documented already within the issues list. Sorry that I didn't see that prior to posting

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
