### ISSUE TITLE
VPN DNS resolution not respecting dnsmasq

### ISSUE THREAD

**Issue by bkad** [docker/for-mac#1310]
### Expected behavior

At my company, we have a hostname that resolves differently depending on whether you're in the VPN or not. There's a public CNAME record for it and a dnsmasq rule on our VPN instance that routes it to an internal IP. On Docker for Mac stable, this routing works correctly in containers and resolves to our internal IP. 

### Actual behavior

In the Docker for Mac Beta channel, the hostname in question routes to the public CNAME. I was trying to figure out what was happening with a guy who knows more about our VPN setup and he says he can see the DNS request from the container come into the VPN instance and return with a correct response but the container gets another a different response as well and uses the public CNAME record.

The hostname resolves correctly if I pass the `--dns` flag specifying our internal DNS instance (which already appears in my OS X resolv.conf), so I do have a workaround.

### Information

Diagnostic ID: F634E433-5608-4633-93C0-D300BD1E9E29

```
Docker for Mac: version: 1.13.1-beta42 (2ffb2b491)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/F634E433-5608-4633-93C0-D300BD1E9E29/20170216-130412.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. In your VPN add a dnsmasq entry for a hostname with a public DNS record routing to your internal network.
  2. `docker run -it --rm azukiapp/dig dig YOURHOSTNAME`
  3. Observe the resolution is different on the Docker for Mac beta channel vs stable for the step \#2.

**Comment by ijc25** [comment]
Hi @bkad,

Thanks for your report.

Looking at your logs I see you seem to have (at least) two IPv4 DNS servers. I guess one of them is your internal dnsmasq and the others are maybe your upstream providers public DNS or something else? Weirdly I see one of those two in your scdata base, but a different second one is configured there, which is an odd inconsistency. Also none of the above are the same as the one mentioned in your `resolv.conf` which is unused by d4m AFAICT.

I believe (and I hope @djs55) can confirm or deny that the current behaviour of docker 4 macs DNS resolution code is to ask all of the configured servers in parallel and to accept the first valid/positive result. I can see in the logs that we are indeed asking the two servers (one of them twice for some reason, so 3 queries in total) and that they are giving different responses, one is an RFC 1918 address and the other is a public cloud (the duplicate query+answer). We are responding to the container with the public answer.

So I think what is happening is that there is a race between your internal dnsmasq and the other server (which is serving the public result). Does this fit with what you know about your DNS configuration on your mac? Do you expect to have such a split DNS configuration or are you expecting all traffic to be routed via dnsmasq?

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by bkad** [comment]
I had a misconfigured `/etc/resolver` pushed by an old VPN configuration. It was not a docker-for-mac issue, sorry about the report!
