### ISSUE TITLE
Docker errors

### ISSUE THREAD

**Issue by SivakumarRamakrishnan** [docker/for-mac#1312]
I got this error while installing docker for mac. i need to install openfoam on my mac. please help.

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.1 (build: 16B2657)
logs: /tmp/87E92F5C-8346-4E48-8D88-E8A5044C0BBC/20170218-085250.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/apple/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/apple/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/apple/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/apple/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/apple/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/apple/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by ijc25** [comment]
Thanks for your report. Your diagnostics exhibit a set of symptoms which I've not yet come across. I'm afraid it is probably going to take some digging to get to the bottom of this.

Looking at your logs it appears that several components of docker for mac and silently and mysteriously failing to start.

How did you start `Docker.app`? By clicking on the icon in finder or spotlight or by some other mechanism? I notice that the Docker application has been given a command line parameter which is not something I would normally expect.

Are you running Docker as the currently logged in user via the UI?

When you first started `Docker.app` were you initially presented with the "Weclome to Docker for Mac! We are whaly happy to have you dialog"? Was that followed by a "Docker needs privileged access." dialog? Was _that_ then followed by password prompt?

Do you have any third party security software (antivirus/malware etc) installed which may be preventing these processes from starting?

Is this a corporate laptop which might have other restrictions on what can be run?

I notice that you appear to have something called "Spigot/ApplicationManager" running. A quick web search suggests that this might be malware. I don't know if this would interfere with d4m but maybe it is something worth cleaning up anyway.

In the logs I see this:
```
Docker[29243]: [com.docker.docker.] CrashReport: stderr redirected to /var/folders/f1/p0433fh171vdlcn1p88h_vmr0000gn/T/Dockererr.txt
```
Could you please check that that file does not contain anything too sensitive and if it does not attach it to this ticket.

**Comment by ijc25** [comment]
Actually the most important thing we need to make progress is the contents of `/var/folders/f1/p0433fh171vdlcn1p88h_vmr0000gn/T/Dockererr.txt`, this turns out to be one of our logs but which is not collected by our diagnostics process (I've created an internal issue for this).

You can ignore the other question in my previous comment for now.

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
