### ISSUE TITLE
Docker for Mac should be able to deploy DABs without requiring user to manually setup new VMs

### ISSUE THREAD

**Issue by jwfehr** [docker/for-mac#1314]
### Expected behavior
User is developing an application to be deployed with swarm. The user wants to test locally. Docker for Mac (and Windows) should be able to automatically provision more vms and setup the networking.

### Actual behavior
Currently if a user wants to test a swarm deployment of a distributed application bundle, he/she is required to setup host vms to put the services unto. 

### Information

https://docs.docker.com/engine/swarm/swarm-tutorial/#/three-networked-host-machines

**Comment by friism** [comment]
@jwfehr swarm-mode works great with default Docker for Mac and Windows. Simply run `docker swarm init` and you're good to go. Then you can deploy distributed apps with both `docker stack deploy --compose-file` and with a bundle file.
