### ISSUE TITLE
Qcow corruption error "Found a reference to cluster 32575 outside the file"

### ISSUE THREAD

**Issue by massimov** [docker/for-mac#1315]
### Expected behavior
docker client should start automatically at boot time, and add the whale icon to the others.

### Actual behavior
docker presents a popup saying:
com.docker.osx.hyperkit.linux failed to start
Exit code 1
and offering to make a diagnosis of the problem.
Whale icon appears halved until one closes the diagnosis window, and entirely disappears afterwards.
I tried manually invoking docker-machine start at a terminal window, and the command output looks fine.

### Information
Please take note that the mode of the diagnosis window severely interferes with the user interface, thus making it extremely difficult to cut and paste text.

This is the key to the uploaded info
CA4CBA13-E333-489A-926D-BD8D45863324

This is the text shown in the left-side pane of the diagnosis window:
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/CA4CBA13-E333-489A-926D-BD8D45863324/20170220-143810.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/massimo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/massimo/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/massimo/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/massimo/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/massimo/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/massimo/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

### Steps to reproduce the behavior

  1. start docker client, either automatically at boot time or manually via launch pad afterwards
  2. docker presents a popup saying:
com.docker.osx.hyperkit.linux failed to start
Exit code 1
and offering to performa a diagnosis

**Comment by adamlunn** [comment]
Exact same issue here

**Comment by ijc25** [comment]
@massimov thanks for your report. Unfortunately there seems to be a bug in the qcow code which can lead to corruption which in turns prevents docker from starting.

I've escalated this to an internal ticket.

In the meantime the only workaround I'm aware of is to perform a factory reset, which should fix things until you are unfortunate to hit it again. Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has/will cause.

Our theory is that this is most likely to be due to the qcow trimming code added recently (for #371). **If** that is the case then it should be possible to disable the trim code with something like:
```
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset --hard
echo false > com.docker.driver.amd64-linux/disk/trim 
git commit -m "disable trim" com.docker.driver.amd64-linux/disk/trim
```

I'm unsure right now if the above will disable compaction entirely or just the online mode, and whether the offline compaction (which happens only at start of day) is susceptible to this issue. Updates when I know more.

@adamlunn you may or may not have the same cause for your symptoms, please open a separate issue with your own diagnostic upload.

**Comment by ijc25** [comment]
Apparently online compaction is already disabled, the key is `com.docker.driver.amd64-linux/disk/compact-after` and it defaults to 0. The `com.docker.driver.amd64-linux/disk/trim` control also controls the offline (boot or shutdown time compaction). Our storage backend expert thinks the issue might be in the regular write path though, and neither of these settings would help with that.

If you have a method of reliably reproducing the corruption that would be useful, so far it seems to mostly be random.

**Comment by austinpray** [comment]
I tried running:

```
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset --hard
echo false > com.docker.driver.amd64-linux/disk/trim 
git commit -m "disable trim" com.docker.driver.amd64-linux/disk/trim
```

And got:

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/21F6F5A7-3EB4-4D32-88C2-B45E7BC04CC4/20170222-155834.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/austinpray/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/austinpray/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/austinpray/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/austinpray/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

id: 21F6F5A7-3EB4-4D32-88C2-B45E7BC04CC4

**Comment by ijc25** [comment]
@austinpray a factory reset is required first, from your new logs it doesn't look like you did that.

The git commands in https://github.com/docker/for-mac/issues/1315#issuecomment-281422975 which you mention are intended to (hopefully) reduce the chance of the issue reoccuring while we work on a fix.

If you (or anyone) are able to reliably reproduce after a factory reset then detailed steps on how to achieve that would be gratefully received.

**Comment by austinpray** [comment]
How do I run a factory reset? I understand there is an option in the preference menu, but I can't get to it since the app crashes immediately.

**Comment by ijc25** [comment]
@austinpray in this case removing the qcow backing file important part of the factory reset. The default path is `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` (it can be changed in the preferences but I presume you would then know where it was).

**Comment by opichon** [comment]
I uninstalled docker for mac completely, and even removed the ~/Library/Containers/com.docker.docker, then reinstalled. Docker for max still won't launch at startup. When launched manually it works file though.

**Comment by frogred8** [comment]
it works to me. thanks.
```
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset --hard
echo false > com.docker.driver.amd64-linux/disk/trim 
git commit -m "disable trim" com.docker.driver.amd64-linux/disk/trim
```
