### ISSUE TITLE
Qcow corruption: Mirage-block error: Unknown (Invalid_argument "Qcow_bitmap.set 985337 >= 985336")

### ISSUE THREAD

**Issue by rjurney** [docker/for-mac#1318]
### Expected behavior

Docker starts.

### Actual behavior

Docker dies.

### Information

Diagnostic ID 1C23A9C6-3EA6-4853-A697-8B38CACF2196

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/1C23A9C6-3EA6-4853-A697-8B38CACF2196/20170221-111800.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rjurney/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/rjurney/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rjurney/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rjurney/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/rjurney/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rjurney/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start Docker
  2. Watch in frustration as it fails to start

**Comment by robsonsnjr** [comment]
Try to remove the "Docker.qcow2" file.
It solved my problem.

**Comment by samart** [comment]
removing Docker.qcow2 sorted this for me as well.  thanks.

**Comment by ijc25** [comment]
@rjurney thanks for your report. Your logs contain:
```
2017-02-21 11:17:54-08 [...] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Invalid_argument "Qcow_bitmap.set 985337 >= 985336")
2017-02-21 11:17:54-08 [...] <Notice>: Mirage-block error: Unknown (Invalid_argument "Qcow_bitmap.set 985337 >= 985336")
```
This is a recently introduced issue which we are tracking internally.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

It's possible that the same workaround suggested in https://github.com/docker/for-mac/issues/1315#issuecomment-281422975 might apply here too although the caveats in https://github.com/docker/for-mac/issues/1315#issuecomment-281632103 would also apply.
