### ISSUE TITLE
Can not pull image from Docker Hub from CLI

### ISSUE THREAD

**Issue by LevonBecker** [docker/for-mac#1322]
### Expected behavior
* ```docker login``` authenticates with Docker Hub
* ```docker pull amazonlinux``` pulls down image

### Actual behavior
* ```docker login``` fails 
* ```docker pull amazonlinux``` fails
    * https://hub.docker.com/r/_/amazonlinux/ 
* ```docker pull ubuntu``` fails
* ```docker pull library/ubuntu``` worked
* ```docker pull nginx``` fails
* ```docker pull library/nginx``` fails

##### Examples
```bash
# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: *********
Password: *********
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving
```

```bash
# docker pull amazonlinux
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/amazonlinux/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Famazonlinux%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: server misbehaving
```

```bash
# docker pull centos
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: server misbehaving
```

```bash
# docker pull library/centos
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/centos/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fcentos%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.65.1:53: server misbehaving
```

### Diagnostic Summary
* Diagnostic ID: 20996A0F-9C84-4A0F-8517-DF27C97A6CD5
* Docker for Mac: version: 1.13.1 (94675c5a7)
* macOS: version 10.12.3 (build: 16D32)
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Information
* Had Docker Toolbox installed awhile ago, been removed and replaced with the Docker.dmg
* Worked on a lower version, been awhile since I have tried to pull an image
* Nuked all and did fresh install
* I have GO Lang and Glide installed with Homebrew
* Am not setting any Docker env vars in my shell
* Not on VPN or behind proxy
* Tested with DNS 8.8.8.8 and get the same results
* I have the latest version of Virtualbox installed, but not using Toolbox anymore... it's for other usage.
* Firewall enabled with Docker.app added (Did after diag)
* File encryption enabled on HD
* Kitematic currently not installed
* ChefDK install and set as default Ruby/Gems
* Homebrew installed and updated mostly for awscli
* Groovy, Gradle, Maven installed with SDKMan
* Java 1.8 Oracle installed
* Have not rebooted since fresh install of Docker.dmg
* Nothing shows for docker in env vars

### Steps to reproduce the behavior

  1. Install Docker.dmg Version 1.13.1 (15353)
  2. Try to pull a Docker Image from Docker Hub on CLI

**Comment by LevonBecker** [comment]
Also, I tried on another "work" Macbook running El Capitan and get the same errors. The interesting thing is adding an internal Dockyard registry and pulling an image from it over VPN, through Proxy etc. works, but can't pull from Docker hub.

**Comment by ijc25** [comment]
Hi @LevonBecker, thanks for your report.

I took a look at your logs and it seems you have a DNS configuration which we (or at least I) have not come across yet.

You system seems to be configured to use three DNS servers, `8.8.8.8` and two RFC1918 addresses ending `.10` and `.11` respectively.

I can see each request coming in from the docker engine into the docker4mac DNS stack and being forwarded to each of the 3 servers. We only once saw a response from the `8.8.8.8` out of many requests, (if it was none I'd suggest firewalls, but one coming through is strange..).

For `AAAA` (IPv6) mostly only `.10` replies (`.11` sometimes responds "Refused" but mostly doesn't answer at all) and for `A` (IPv4) lookups mostly only `.11` replies (`.10` rarely replies).

All of the `AAAA` replies from `.10` for valid queries include an Authority RR SOA response but _not_ an answer to the query, i.e. they are a cacheable negative response to the query. I think this is expected -- I don't see any `AAAA` records for `registry-1.docker.io` etc either and the replies I see look similar to what you are getting.

All of the `A` replies from `.11` are code 5 "Refused" and do not contain any answers. I can see that your host DNS resolver is also "penalizing" (whatever that means) `.11` for that. On the odd occasions when `.10` replies to an `A` query it looks to be giving valid answers, but mostly it doesn't reply.

All of this is a bit strange to me, perhaps you are on an IPv6 only network, including DNS set to (mostly) deny IPv4 queries? (Although the occasional `A` responses from `.10` are a bit odd in that case).

Can you confirm that regular web browsing work fine for you for both IPv4 and IPv6 websites? Are you able to browse in Safari to https://registry-1.docker.io/v2/ (you should get a splodge of JSON back, mine says "unauthorized" but I am at least talking to the server). Similarly can you reach https://auth.docker.io/token (another splodge of JSON, maybe with a token). Can you `curl` those same URLs from a MacOS command line (I think that'll even tell you whether it does v4 or v6, which might be interesting to know)

There are some changes/improvements to our DNS handling code in the latest betas compared with stable, it would be worth trying that and sending a new diagnostic if it still doesn't work (to be honest, I'm not hopeful this will help, but it would be good to be looking at the most current code).

**Comment by paupino** [comment]
I had a similar issue with the 1.13 issue which I fixed with the instructions found within [this comment](https://github.com/docker/for-mac/issues/1103#issuecomment-272413466).  It sounds like this has not been fixed in 1.13.1 yet - fortunately, the same instructions from above should resolve this albeit temporarily.

**Comment by LevonBecker** [comment]
Thanks @paupino and @djs55! Following that slirp.zip fix worked!

@ijc25 adding the com.docker.slirp binary from @djs55 [Post](https://github.com/docker/for-mac/issues/1103#issuecomment-272413466) Fixed the issue!

# Answers
I switched back to the 10/11 DNS. I'm on IPv4 network. Usually, disable IPv6. I can get to https://registry-1.docker.io/v2/ and yes I get the same 
```json
{
errors: [
{
code: "UNAUTHORIZED",
message: "authentication required",
detail: null
}
]
}```

I can get to https://auth.docker.io/token as well.

I'm using Chrome.

**Comment by LevonBecker** [comment]
# Beta Fixes the issue
I uninstalled the release version and installed the beta version without the slirp fix and the problem is resolved.

```
# docker version
Client:
 Version:      17.03.0-ce-rc1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce-rc1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Bharathkumarraju** [comment]
Hi team,

I am also unable to pull images....how can change the docker registry in mac.. I have account in dockerhub...but in my mac it is saying docker registry as docker.io...can anyone help me on this?

```
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: unauthorized: incorrect username or password
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: AV33:ZWKT:44GD:YGUO:W2FH:ABUH:DDAF:P3SE:GTMD:3VQ6:7476:KPS5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 29
 System Time: 2017-10-11T15:15:46.843513848Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$
```

**Comment by Bharathkumarraju** [comment]
```
i found it  and it worked as below

bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker login --username=bharathkumarraju
Password:
Login Succeeded
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
88286f41530e: Pull complete
Digest: sha256:f006ecbb824d87947d0b51ab8488634bf69fe4094959d935c0c103f4820a417d
Status: Downloaded newer image for alpine:latest
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              76da55c8019d        4 weeks ago         3.97MB
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$

```

**Comment by 00caue** [comment]
Hi Guys!

Just use the login cmd before any "docker run"

type:
>docker login

Type you username:
Username (00caue): <docker_username_here>

hit <enter>

Password: <type_your_docker_password>

hit <enter>

After this you are able to download anything!

**Comment by glamrock** [comment]
@00caue Thanks! I just ran into this issue and `docker login` solved the issue entirely.

**Comment by ursomniac** [comment]
Logging in to Docker just before the % docker run has absolutely no effect.
I still get docker: Error response from daemon: manifest for (username)/(docker_image):(tagname) not found.

If this error is this common, shouldn't the solution be well-documented by now?

**Comment by loulouX** [comment]
same here

docker has no effects

PS C:\WINDOWS\***> docker login
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://192.*.*.*:2376/v1.**/info: dial tcp 192.*.*.*:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.). Using system default: https://index.docker.io/v1/
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (****): ****
Password:****
error during connect: Post https://192.*.*.*:2376/v1.**/auth: dial tcp 192.*.*.*:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

help please
