### ISSUE TITLE
Intermittent Private DNS issue

### ISSUE THREAD

**Issue by yanatan16** [docker/for-mac#1324]
### Expected behavior

```
$ docker pull private-dns-private-registry/image:tag
<regular pull success>
```

### Actual behavior

Intermittently fails:

```
$ docker pull private-dns-private-registry/image:tag
Pulling repository private-dns-private-registry/image:tag
Error while pulling image: Get http://private-dns-private-registry/v1/repositories/image-name/images: dial tcp: lookup private-dns-private-registry on 192.168.65.1:53: no such host
```

### Information

Diagnostic ID: BF2DED66-B0D5-459B-8C80-02523791468A

The private dns registry is only available to my VPN dns server and anything forwarding that server. The private dns works fine on my host. It intermittently fails on the docker host.

I'm running dnsmasq locally which can see the private dns registry:

```
$ dig private-dns-private-registry @localhost

; <<>> DiG 9.8.3-P1 <<>> private-dns-private-registry @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31713
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;private-dns-private-registry.	IN	A

;; ANSWER SECTION:
gsas-registry.activision.com. 3600 IN	CNAME	amazon-elb-url.us-west-2.elb.amazonaws.com.
amazon-elb-url.us-west-2.elb.amazonaws.com. 60 IN A 172.29.101.250
amazon-elb-url.us-west-2.elb.amazonaws.com. 60 IN A 172.29.101.4

;; Query time: 158 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Feb 22 12:52:43 2017
;; MSG SIZE  rcvd: 149
```

### Questions

Is there some configuration that would point the docker for mac dns server to the host dnsmasq all the time?

**Comment by ijc25** [comment]
Docker for mac will use whichever DNS servers are configured on the host. I can see that you have 1 server which looks to be from your ISP and 2 which look to be your corporate DNS, the latter two appear to be associated with your VPN. The ISP one fails to lookup your internal registry (as is expected).

I believe there have been some improvements in the latest beta releases which should improve handling in this scenario (specifically preferring successful queries over first responder). Please could you try that and let us know if it works (if it doesn't then a new diagnostic upload would be useful).

**Comment by MagnusS** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
