### ISSUE TITLE
Docker fails to run on iMac 2010 with Intel i7 processor

### ISSUE THREAD

**Issue by kureci** [docker/for-mac#1325]
### Expected behavior
Docker to run on iMac 27" Mid-2010, Intel i7 processor with virtualisation support

### Actual behavior
Docker says CPU incompatible

### Information
Done some research and it looks like my iMac should have support for virtualisation. 

The list of CPU features shows VMX, which I read that indicates support for virtualisation.

machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL **VMX** SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT

Output of the command `kextstat | grep intel`
```
135    0 0xffffff7f8386a000 0x14000    0x14000    **com.intel.kext.intelhaxm** (6.0.3) 50449AFC-F7C6-38A0-B820-233E8A050FD6 <7 5 4 3 1>
```

And this is dump of the diagnostics:

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/E39CEB84-057F-48A3-8963-7C0D0F62135B/20170222-221307.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jahidkureci/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/jahidkureci/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jahidkureci/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jahidkureci/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/jahidkureci/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/jahidkureci/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

```

### Steps to reproduce the behavior

1. Installed fresh copy of macOS Sierra on my new SSD
2. Downloaded Docker and moved it to Applications folder
3. Opening Docker fails

I would love to hear that my iMac should actually be compatible but just needs something done somewhere!

**Comment by ijc25** [comment]
> The list of CPU features shows VMX, which I read that indicates support for virtualisation.

Unfortunately it is more complicated than that, as well as requiring other h/w feature (second level paging AKA MMU virtualisation) it also requires support from firmware and from the host operating system as well.

Your logs indicate `kern.hv_support: 0` which means that the MacOS kernel has not enabled virtualisation support (`Hypervisor.framework`) on your platform. Unfortunately there is nothing which docker for mac can do about this and `Hypervisor.framework` support is a hard requirement for d4m.

You might find an option your firmware configuration to enable this or you might find a firmware update enables this functionality on your system. Apple should be able to provide further guidance on this matter.

See the "important notes" at https://docs.docker.com/docker-for-mac/install/ for more information.

Also "HAXM" (shown in your kext output) is a different 3rd party hypervisor technology (part of an Android SDK from Intel AIUI). At one point HAXM was incompatible with `Hypervisor.framework` on systems which support `Hypervisor.framework`. This is not your issue right now but I mention this as a heads up in case you are somehow able to enable `Hypervisor.framework` on your platform.
