### ISSUE TITLE
Docker doesn't start (no GUI)

### ISSUE THREAD

**Issue by adriel** [docker/for-mac#1326]
Used to run an older version of docker (think it was in beta then), been at least a few months since I updated (or used) Docker on the Mac, so today I downloaded the latest (1.13.1)  and copied it over the old Docker.app but it just hangs when I try to open it, I get no GUI at all, so can't do any of the reset or uninstall stuff from the GUI.
I tried the uninstall via the command line but it also hangs.
I've done a search for anything with "docker" and removed it, I've also run [this uninstall script](https://github.com/docker/toolbox/blob/master/osx/uninstall.sh), none of which done much.

### Expected behavior
Docker should open.

### Actual behavior
Docker hangs. (I've waited for 15mins)

### Information

**Console messages (starting Docker.app after reboot)**

    default	12:20:28.916714 +1300	DockerHelper	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
    default	12:20:28.990690 +1300	DockerHelper	AppDelegate: launching...
    error	12:20:28.993537 +1300	DockerHelper	Failed to read values in CFPrefsPlistSource<0x7fe57541bfb0> (Domain: group.com.docker, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
    default	12:20:29.008941 +1300	DockerHelper	AppDelegate: bundle path: /Applications/Docker.app/Contents/Library/LoginItems/DockerHelper.app
    default	12:20:29.008980 +1300	DockerHelper	AppDelegate: auto start: true
    default	12:20:29.009009 +1300	DockerHelper	AppDelegate: launch path: /Applications/Docker.app
    error	12:20:29.420450 +1300	Docker	Failed to read values in CFPrefsPlistSource<0x6080000ef480> (Domain: group.com.docker, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
    default	12:20:29.437609 +1300	DockerHelper	AppDelegate: Docker.app sucessfully launched from: /Applications/Docker.app
    default	12:20:29.438253 +1300	Docker	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
    default	12:20:29.438924 +1300	DockerHelper	AppDelegate: terminating...
    default	12:20:29.459614 +1300	Docker	CrashReport: stderr redirected to /var/folders/vz/vxdtfyls7256g74b_66vn66m0000gn/T/Dockererr.txt
    default	12:20:29.474161 +1300	Docker	AppDelegate: Application version: 1.13.1 (15353)
    default	12:20:29.474401 +1300	Docker	AppDelegate: Administrator user: true
    default	12:20:29.474524 +1300	Docker	OSX Version: Version 10.12.3 (Build 16D32)
    default	12:20:29.729962 +1300	Docker	AppDelegate: new version detected: 1.13.1
    default	12:20:29.756613 +1300	Docker	AppDelegate: Bundle path: /Applications/Docker.app
    default	12:20:29.760580 +1300	Docker	subsystem: com.apple.libsqlite3, category: logging, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.764620 +1300	Docker	Faulting in NSHTTPCookieStorage singleton
    default	12:20:29.764646 +1300	Docker	Faulting in CFHTTPCookieStorage singleton
    default	12:20:29.764661 +1300	Docker	Creating default cookie storage with process/bundle identifier
    default	12:20:29.766523 +1300	Docker	subsystem: com.apple.securityd, category: secpref, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767049 +1300	Docker	subsystem: com.apple.securityd, category: integrity, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767190 +1300	Docker	subsystem: com.apple.securityd, category: handleobj, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767275 +1300	Docker	subsystem: com.apple.securityd, category: MDS_Scan, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767414 +1300	Docker	subsystem: com.apple.securityd, category: MDS_API, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767514 +1300	Docker	subsystem: com.apple.securityd, category: SSclnt, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767881 +1300	Docker	subsystem: com.apple.securityd, category: MDS_IO, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.767979 +1300	Docker	subsystem: com.apple.securityd, category: mdslock, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.768116 +1300	Docker	subsystem: com.apple.securityd, category: security_exception, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.768242 +1300	Docker	UNIX error exception: 17
    default	12:20:29.768379 +1300	Docker	subsystem: com.apple.securityd, category: DBOpen, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.768458 +1300	Docker	subsystem: com.apple.securityd, category: dbsession, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.768630 +1300	Docker	subsystem: com.apple.securityd, category: atomicfile, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.768669 +1300	Docker	0x6080002664c0 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
    default	12:20:29.768755 +1300	Docker	0x6080002664c0 closed /private/var/db/mds/system/mdsDirectory.db
    default	12:20:29.769929 +1300	Docker	UNIX error exception: 17
    default	12:20:29.770074 +1300	Docker	subsystem: com.apple.securityd, category: dynamic, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.770193 +1300	Docker	subsystem: com.apple.securityd, category: callback, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.770291 +1300	Docker	subsystem: com.apple.securityd, category: cssm, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.770393 +1300	Docker	UNIX error exception: 17
    default	12:20:29.770542 +1300	Docker	UNIX error exception: 17
    default	12:20:29.770847 +1300	Docker	UNIX error exception: 17
    default	12:20:29.770985 +1300	Docker	UNIX error exception: 17
    default	12:20:29.771088 +1300	Docker	0x618000079380 opened /Users/adriel/Library/Keychains/login.keychain-db: 1084152 bytes
    default	12:20:29.771766 +1300	Docker	0x618000079380 closed /Users/adriel/Library/Keychains/login.keychain-db
    default	12:20:29.772781 +1300	Docker	loading /Users/adriel/Library/Keychains/login.keychain-db
    default	12:20:29.775318 +1300	Docker	subsystem: com.apple.securityd, category: kcreferral, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.775666 +1300	Docker	0x600000072f80 opened /Library/Keychains/System.keychain: 106784 bytes
    default	12:20:29.775779 +1300	Docker	0x600000072f80 closed /Library/Keychains/System.keychain
    default	12:20:29.776756 +1300	Docker	loading /Library/Keychains/System.keychain
    default	12:20:29.779748 +1300	Docker	subsystem: com.apple.network, category: , enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:29.779807 +1300	Docker	TIC TCP Conn Start [1:0x61000018f7d0]
    default	12:20:29.965747 +1300	Docker	TIC TCP Conn Event [1:0x61000018f7d0]: 1 Err(0)
    default	12:20:29.965775 +1300	Docker	TIC TCP Conn Connected [1:0x61000018f7d0]: Err(0)
    default	12:20:29.965894 +1300	Docker	TIC Enabling TLS [1:0x61000018f7d0]
    default	12:20:30.145957 +1300	Docker	TIC TLS Event [1:0x61000018f7d0]: 2, Pending(0)
    default	12:20:30.147676 +1300	Docker	TIC TLS Event [1:0x61000018f7d0]: 11, Pending(0)
    default	12:20:30.147815 +1300	Docker	subsystem: com.apple.securityd, category: dateparse, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:30.148038 +1300	Docker	UNIX error exception: 17
    default	12:20:30.148198 +1300	Docker	UNIX error exception: 17
    default	12:20:30.148403 +1300	Docker	subsystem: com.apple.securityd, category: SecImpExp, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
    default	12:20:30.148668 +1300	Docker	TIC TLS Event [1:0x61000018f7d0]: 12, Pending(0)
    default	12:20:30.148694 +1300	Docker	TIC TLS Event [1:0x61000018f7d0]: 14, Pending(0)
    default	12:20:30.150976 +1300	Docker	TIC TLS Trust Result [1:0x61000018f7d0]: 0
    default	12:20:30.329110 +1300	Docker	TIC TLS Event [1:0x61000018f7d0]: 20, Pending(0)
    default	12:20:30.329363 +1300	Docker	TIC TCP Conn Event [1:0x61000018f7d0]: 8 Err(0)
    default	12:20:30.329380 +1300	Docker	TIC TLS Handshake Complete [1:0x61000018f7d0]
    default	12:20:30.524676 +1300	Docker	Analytics: Sent heartbeat event.
    default	12:20:30.528955 +1300	Docker	Analytics: Sent appLaunched event.
    default	12:20:31.074225 +1300	Docker	subsystem: com.apple.securityd, category: kcnotify, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0

    default	12:23:30.599133 +1300	Docker	TIC TCP Conn Event [1:0x61000018f7d0]: 2 Err(0)
    error	12:23:30.599168 +1300	Docker	TIC Read Error [1:0x61000018f7d0]: 1:57
    error	12:23:30.599183 +1300	Docker	TIC Read Error [1:0x61000018f7d0]: 1:57
    error	12:23:30.599214 +1300	Docker	TIC Read Error [1:0x61000018f7d0]: 1:57
    default	12:23:30.599291 +1300	Docker	TIC TCP Conn Cancel [1:0x61000018f7d0]

**Dockererr.txt (is empty)**

    Adriels-iMac:~ adriel$ cat /var/folders/vz/vxdtfyls7256g74b_66vn66m0000gn/T/Dockererr.txt
    Adriels-iMac:~ adriel$ 

**Trying to uninstall Docker (while Docker.app is hung or force quit, same output)**
The command just hangs.

    Adriels-iMac:~ adriel$ /Applications/Docker.app/Contents/MacOS/Docker --uninstall
    cat^C

    error	12:25:00.623624 +1300	Docker	Failed to read values in CFPrefsPlistSource<0x7fbd50605bf0> (Domain: group.com.docker, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
    default	12:25:00.637717 +1300	Docker	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
    default	12:25:00.648843 +1300	Docker	CrashReport: stderr redirected to /var/folders/vz/vxdtfyls7256g74b_66vn66m0000gn/T/Dockererr.txt
    default	12:25:00.657616 +1300	Docker	disabling logs

Dockererr.txt is empty.

  **docker-diagnose (while Docker is hanging)**

    Adriels-iMac:~ adriel$ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose 
    Error exec: plutil -extract appVersionHistory xml1 "/Users/adriel//Library/Group Containers/group.com.docker/Library/Preferences/group.com.docker.plist" -o -: exit 1
    macOS: version 10.12.3 (build: 16D32)
    Docker.app: version: 1.13.1 (94675c5a7)
    Local time: Thu 23 Feb 2017 12:23:53 NZDT
    UTC:        Wed 22 Feb 2017 23:23:53 UTC
    Timestamp:  20170223-122353
    Running diagnostic tests:
    [ERROR]   docker-cli       cannot find docker
    Error docker -v: timeout after 10.00s
    [ERROR]   Moby booted      /Users/adriel/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
    [ERROR]   driver.amd64-linux com.docker.driver.amd64-linux -db is not running
    [ERROR]   vmnetd           /private/tmp/vmnetd/com.docker.vmnetd is not running
    [ERROR]   osxfs            com.docker.osxfs is not running
    [ERROR]   db               /Users/adriel/Library/Containers/com.docker.docker/Data/s40 does not exist
    [ERROR]   db               Unexpected error (No such file or directory) connecting to /Users/adriel/Library/Containers/com.docker.docker/Data/s40
    [ERROR]   db               com.docker.db is not running
    [ERROR]   slirp            Unexpected error ((Failure
      "Error connecting socket to 9p endpoint unix:/Users/adriel/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/adriel/Library/Containers/com.docker.docker/Data/s51
    [ERROR]   slirp            com.docker.slirp is not running
    Error docker -v: got timeout (docker -v: exit 127)
    [ERROR]   disk             Docker.qcow2 missing: the VM has never been started
    [OK]      menubar
    [OK]      environment
    [OK]      Docker
    [OK]      VT-x
    [OK]      kern.hv_support
    Most specific failure is: Docker.qcow2 missing: the VM has never been started
    Docker logs are being collected into /tmp/F03C2497-9577-401D-9684-E8D98DB7067A/20170223-122353.tar.gz
    Would you like to upload log files? [Y/n]: Y

    Your unique id is: F03C2497-9577-401D-9684-E8D98DB7067A

### Steps to reproduce the behavior

  1. Open Docker.app

**Comment by superandrew** [comment]
I can essentially quote everything. Docker for mac was working, today I launched and with the same errors, it just hangs. Tried to uninstall, delete preferences and every file related to docker, restart docker just doesn't work. Ugly

**Comment by ijc25** [comment]
@adriel this is an odd one. In your logs I see:
```
localhost Docker[415]: [com.docker.docker.] Install: com.docker.vmnetd is too old for automatic upgrade.
```
Does running `sudo rm /Library/PrivilegedHelperTools/com.docker.vmnetd` and then relaunching `Docker.app` then try and perform a fresh install (i.e. ask for your password etc) and allow you to make progress?

What does `sudo launchctl list | grep com.docker` say?

Do you recall which beta version you were running before (or the approximate time you were running it)?

FYI the [uninstall script](https://github.com/docker/toolbox/blob/master/osx/uninstall.sh) you tried is for Docker Toolbox and doesn't seem to uninstall any of the interesting parts of docker for mac other than the `/usr/local/bin` symlinks.

@superandrew please open a separate issue with your own diagnostics upload.

**Comment by adriel** [comment]
Legend, thank you for looking into this @ijc25 

I couldn't delete `/Library/PrivilegedHelperTools/com.docker.vmnetd` since the file didn't exist, but doing a `find` I did find 2 similar files which I deleted and now Docker opens fine, and after entering the admin pass everything looks to be working as expected.

**Comment by smallnest** [comment]
I have met the same issue and solution of adriel has fixed this issue. Thanks
