### ISSUE TITLE
Every restart generates a new docker id

### ISSUE THREAD

**Issue by matti** [docker/for-mac#1328]
```
$ docker info
[clipped]
Name: moby
ID: PHNW:GV3Y:JTME:BE7X:JH6V:WRKX:Y2YX:OKQL:ZIKL:2LO3:OQ75:UMBL
```

restart docker for mac

```
$ docker info
Name: moby
ID: S4AE:D5XK:KQ2R:SWVL:V4MB:SPV6:QDKG:B3ZW:ECJS:SEVA:5EXJ:Q7EG
```

running Version 17.03.0-ce-rc1-mac1 (15471)

**Comment by ijc25** [comment]
Thanks for your report. I see the same phenomenon.

Is there some particular use case which you have in mind which requires this ID to be stable? I'm going to raise this as an internal regardless, but it would be good to know some concrete use cases.

**Comment by matti** [comment]
kontena.io agent thinks that it's a new node. makes running kontena (docker orchestrator) really hard

**Comment by ijc25** [comment]
Thanks, I added that to the ticket I just created.
