### ISSUE TITLE
Docker fails to respond after killing a session

### ISSUE THREAD

**Issue by spedapalli** [docker/for-mac#1331]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Initialized installation of Eclipse Che using the command docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /Users/<me>/eclipse_che:/data eclipse/che start
  2. Used Ctrl +c to kill it since I had to shut down the system
  3. Retry the command in (1) and there is no response.

**Comment by ijc25** [comment]
Please use the :whale: menu :arrow_right: Diagnose and Feedback to upload a diagnostic and paste the full output into this ticket.

Did you shutdown or reboot the system between step 2. and step 3.? Did you restart `Docker.app` afterwards and was the :whale: icon present in your toolbar?

**Comment by spedapalli** [comment]
I did restart Docker, and Docker went in a spin without starting.
Ended up Quitting it completely and starting it again. That worked.

Regards
Samba

**Comment by rogaha** [comment]
This issue has been identified as being incomplete. It's an > 80% match to our issue template. Please see [this document](https://docs.docker.com/docker-for-mac/troubleshoot) for instructions on how to open a well formatted issue. Please be sure to include your Diagnostic ID as well as any reproduction steps, including Dockerfiles or docker-compose.yml if necessary.
