### ISSUE TITLE
unable to resolve DNS entries over VPN

### ISSUE THREAD

**Issue by llamahunter** [docker/for-mac#1332]
### Expected behavior

Docker engine is able to resolve dns entries on company intranet over VPN

### Actual behavior

Docker engine is not able to resolve private DNS entries over VPN

### Information

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/E52BC1B4-D772-4BFC-8921-2E6D6811A667/20170223-154825.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

VPN software is Juniper Networks Pulse Secure v. 5.2.5 (897)

This previously worked fine before a recent docker engine update to 1.13.1. Can't say for certain that it worked in 1.13.0, but definitely worked in 1.12.x

### Steps to reproduce the behavior

  1. Connect using VPN
  2. Try to do a 'docker pull' from a private registry, e.g. 'docker pull docker.tivo.com/tivo'
  3. Get a DNS failure

Problem seems intermittent.  Restarting the docker engine and waiting a while seems to fix things.  Does not work immediately after docker engine restart, tho... as though something is cached?

**Comment by ijc25** [comment]
Perhaps this is similar to #1322? Please could you either try the beta branch or if you like you could try the instructions in https://github.com/docker/for-mac/issues/1103#issuecomment-272413466 to add a newer vpnkit to your existing install.

**Comment by llamahunter** [comment]
Hit this again. Uploaded a new diagnostic.  E52BC1B4-D772-4BFC-8921-2E6D6811A667

**Comment by llamahunter** [comment]
I tried the slirp.zip patch, and it seemed to fix things, for now.

**Comment by djs55** [comment]
Thanks for trying the `slirp.zip`. There are several DNS fixes due for release in the edge channel shortly. I'll resolve this ticket as fixed but please do open a fresh ticket if the new build (due out this week) still has problems.
