### ISSUE TITLE
docker for mac does not launch at startup

### ISSUE THREAD

**Issue by opichon** [docker/for-mac#1333]
### Expected behavior
Docker for mac should launch at startup

### Actual behavior
Docker for mac doesn't launch at startup

### Information
diagnostic id: 6D2D7812-0903-4464-A679-BE8740361F21

### Steps to reproduce the behavior

  1. start computer 
  2. ...

**Comment by ijc25** [comment]
Detected symptom of problem 'qcow2-cluster-outside-file' in 6D2D7812-0903-4464-A679-BE8740361F21/20170224-094613.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

May be related to docker/for-mac#1315, closing as a dup, please subscribe there for updates.
