### ISSUE TITLE
Docker hard hang

### ISSUE THREAD

**Issue by z3ndrag0n** [docker/for-mac#1337]
### Expected behavior
Expect "docker ps" to give me output - instead hangs. com.docker.hyperkit is using 299.5% CPU.
### Actual behavior
"docker ps" hangs diagnostic fails checking docker-cli.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.13.1-beta42 (2ffb2b491)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/93B9F680-4B21-4E1F-8621-EF466EF0E865/20170225-095313.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
I had danielguerra/alpine-xfce4-xrdp and (I believe though can't check at the moment) that the other may have been rigormortiz/ubuntu-xrdp-mate
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Fire up containers described above
  2. Wait. Eventually you will get connections from 91.195.103.162, 134.249.165.109
nslookup 134.249.165.109
109.165.249.134.in-addr.arpa	name = 134-249-165-109.broadband.kyivstar.net.

Authoritative answers can be found from:

nslookup 91.195.103.162
162.103.195.195.91.in-addr-arpa        name=hostby.fastvps.cz

Allow time to pass.

Then things will get interesting.

**Comment by seehuhn** [comment]
I have similar issues.  Docker on Mac is running happily for a while, and then suddenly hangs.  `docker ps -a` also hangs then, and the "Diagnose & Feedback" window says `failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")`.

**Comment by rogaha** [comment]
@z3ndrag0n I'm not sure if it's related to the `hanging` issue, but it looks like you have configured an `Ipv6` in the DNS and that's is causing some issues: 

```
2017-02-18 16:48:49+11 www Docker[com.docker.driver.amd64-linux][1194] <Notice>: SC database lists search domains:
2017-02-18 16:48:49+11 www Docker[com.docker.driver.amd64-linux][1194] <Notice>: SC database includes DNS service: { Addresses: 2001:44b8:4140:a000:eafc:afff:fef8:4bdc, 10.0.0.2; Order: 200000; Zones:  }
2017-02-18 16:48:49+11 www Docker[com.docker.driver.amd64-linux][1194] <Notice>: SC database includes DNS service: { Addresses: 10.0.0.2, 2001:44b8:4140:a000:eafc:afff:fef8:4bdc; Order: 200000; Zones:  }
2017-02-18 16:48:49+11 www Docker[com.docker.driver.amd64-linux][1194] <Notice>: SC database has domain name:
2017-02-18 16:48:49+11 www Docker[com.docker.slirp][1192] <Error>: failed to parse com.docker.driver.amd64-linux/slirp/dns: Failed to parse configuration: Ipaddr.Parse_error("invalid character ':' at 4", "2001:44b8:4140:a000:eafc:afff:fef8:4bdc")
2017-02-24 21:54:57+11 www Docker[com.docker.slirp][2238] <Error>: Socket.UDPv6.write udp:2001:44b8:4140:a000:eafc:afff:fef8:4bdc:53: caught host is unreachable returning Eof
```

**Comment by z3ndrag0n** [comment]
Thanks for bringing that up - that connection is dual stack - does docker (for Mac) have issues with IPv6?

Cheers,
Barry

**Comment by z3ndrag0n** [comment]
I'd never had a hard hang before - I'm going to upgrade to CE and keep an eye on it.

Cheers,
Barry

**Comment by seehuhn** [comment]
Maybe this is the same problem as in issue docker/docker#31487 ?

**Comment by manasRK** [comment]
A system restart did the trick. Would wait for the hotfixes from Docker.

**Comment by MagnusS** [comment]
@z3ndrag0n did upgrading to the latest version of Docker for Mac fix the issue?

**Comment by albizures** [comment]
@MagnusS for me the issue started with the update to 17.03-ce-mac2

**Comment by djs55** [comment]
Unfortunately symptoms like `docker ps` hanging can have many completely different causes. @albizures could you file a fresh ticket with diagnostics after you experience your failure?

@z3ndrag0n there are some IPv6 bugs (support for v6 is not yet complete) but it doesn't explain the hang. Looking in the VM's console logs I see a lot of:
```
NMI watchdog: BUG: soft lockup - CPU#3 stuck for 22s! [khugepaged:39]
NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [DOM Worker:18913]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [DOM Worker:18979]
```
which suggests the kernel got stuck. So I think this case is different to the docker/docker issue, although other instances of `docker ps` hanging could well be the engine issue.

Unfortunately the stuck kernel also means the in-VM logs are missing.

@z3ndrag0n since we've not heard from you for over 14 days I'll assume the upgrade to the later version has fixed the problem and I'll close the ticket. If this is wrong, let me know.

Everyone else who has a similar-looking problem, please create a fresh ticket with diagnostics!

Thank you (all) for your report and for using Docker for Mac!
