### ISSUE TITLE
docker for mac using 100% CPU with no containers running

### ISSUE THREAD

**Issue by glyph** [docker/for-mac#1338]
### Expected behavior

When idle, docker for mac should be idle.

### Actual behavior

When idle, sometimes it shows up on the host as consuming 100% CPU.

### Information

  - Diagnostic ID: FBA29BC9-1700-4888-9B44-54EB63DDCD2C
  - Running `docker run --rm --privileged --pid=host -it ubuntu /bin/top` shows me a clear culprit:

```
  255 root      20   0       0      0      0 R 100.0  0.0   6:38.99 kworker/u8:5                                      
```

Sadly I don't know how to interpret this, however.

### Steps to reproduce the behavior

Unknown. Sometimes this happens with no provocation.

**Comment by dsheets** [comment]
When it happens again, grabbing and posting the contents of `/proc/PID/stack` (where `PID` is the offending process ID) would be helpful.

**Comment by yallop** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
