### ISSUE TITLE
Docker Startup reported error

### ISSUE THREAD

**Issue by rdoraiswamy** [docker/for-mac#1342]
**Diagnostic Id: 613BDC9F-E999-4D1B-8FD1-F816C734E3C8**

### Expected behavior
Docker Startup normal
### Actual behavior
Docker Startup reported error

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/613BDC9F-E999-4D1B-8FD1-F816C734E3C8/20170226-075842.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/**/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/**/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/**/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/**/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rdoraiswamy/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ... Normal boot of Mac and this error popped up.
  2. ...

**Comment by higashijima-masaya** [comment]
I get same diagnostics on macOS version 10.12.3(build:16D32), today.  Diagnostic says "Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)", so I paste that data here.

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/3CA51989-657F-4C8A-ABC5-348CF4A7ECB3/20170301-092928.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/sur0634/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/sur0634/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/sur0634/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/sur0634/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/sur0634/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by kitgrose** [comment]
Same exact error log for me (diagnostic ID: 0259F747-8B92-485A-A484-8F5662B957E1).

I'm running macOS v10.12.2 though.

**Comment by MagnusS** [comment]
@rdoraiswamy thanks for the report - do you have the error message that was reported on startup? Did relaunching the application fix the issue?

@kitgrose from your logs looks like the issue reported in docker/for-mac#1315. You should be able to recover with a "Reset to factory settings" (this will remove your containers and settings) or by following the instructions for removing the image in that issue. 

@higashijima-masaya the symptoms look similar, but it's difficult to tell without access to the logs - it may help to remove the image file / reset to factory defaults in your case as well (note that this will remove all containers). If you still have the issue could you please open a new github issue with a diagnostic ID? Thanks

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
