### ISSUE TITLE
docker run hello-world results in i/o timeout

### ISSUE THREAD

**Issue by stitchdad** [docker/for-mac#1346]
### Expected behavior
`docker run hello-world` downloads and runs the latest hello-world image when not found locally.

### Actual behavior
`docker run hello-world` results in a i/o timeout error.

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:55563->192.168.65.1:53: i/o timeout.
See 'docker run --help'.
```

`docker login` has the same results:

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to XXX//hub.docker.com to create one.
Username:
Password:
Error response from daemon: Get XXX//registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:60958->192.168.65.1:53: i/o timeout

```

Was requested by support to try the following:
- `docker pull busybox`
- `docker pull ubuntu`

both resulted in the same error.

### Information

  - Diagnostic ID:  7B2C4A32-D87B-4141-814D-DB4136B697F3
 
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/7B2C4A32-D87B-4141-814D-DB4136B697F3/20170227-063631.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - OS Version/build

 ```
System Version: macOS 10.12.3 (16D32)
 Kernel Version: Darwin 16.4.0
```

  - App version:

  ```
  $ docker version
    Client:
    Version: 1.13.1
    API version: 1.26
    Go version: go1.7.5
    Git commit: 092cba3
    Built: Wed Feb 8 08:47:51 2017
    OS/Arch: darwin/amd64

    Server:
    Version: 1.13.1
    API version: 1.26 (minimum version 1.12)
    Go version: go1.7.5
    Git commit: 092cba3
    Built: Wed Feb 8 08:47:51 2017
    OS/Arch: linux/amd64
    Experimental: true
```

  - dig results

```
$ dig registry-1.docker.io

; <<>> DiG 9.8.3-P1 <<>> registry-1.docker.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4982
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;registry-1.docker.io.		IN	A

;; ANSWER SECTION:
registry-1.docker.io.	60	IN	A	52.72.139.208
registry-1.docker.io.	60	IN	A	54.236.131.143
registry-1.docker.io.	60	IN	A	52.201.90.157

;; Query time: 2452 msec
;; SERVER: 192.168.55.1#53(192.168.55.1)
;; WHEN: Mon Feb 27 06:47:01 2017
;; MSG SIZE  rcvd: 86
```

### Steps to reproduce the behavior

  1. Install the latest version of docker
  2. run `docker run hello-world`

**Comment by guizmaii** [comment]
Hi, 

Same problem here :/

**Comment by mshack70** [comment]
Same problem here. was working yesterday now can't pull any images from docker hub.

**Comment by vovimayhem** [comment]
Not related to docker for Mac, but rather a service outage - see http://status.docker.com

**Comment by stitchdad** [comment]
I first posted on the docker forums and contacted docker support with this issue 10 days ago.  Has the registry service been out that long?

**Comment by justincormack** [comment]
@stitchdad no, it has not been down that long, but we cannot look at the original issue right now.

**Comment by stitchdad** [comment]
@justincormack thanks for the update.

**Comment by chinchang** [comment]
I think its related to the S3 being down right now. Is it?

**Comment by MagnusS** [comment]
@stitchdad Thanks for the report. 

From the logs it looks like the DNS request was correctly forwarded to your DNS server at 192.168.55.1, but that the query timed out or the response was lost. There is a new version of Docker for Mac available (17.03-ce-mac2) which contains several improvements to DNS - would you be able to try that and see if it helps?

https://download.docker.com/mac/stable/Docker.dmg ([release notes](https://download.docker.com/mac/stable/15654/NOTES))

(I removed the link to the logs from your message. When you have uploaded them to us we can retrieve them with the ID)

@chinchang @vovimayhem @mshack70 @guizmaii if you still have this problem (now that S3 is back up again) please file separate issues with diagnostic IDs so we can take a look at the logs. Thanks!

**Comment by chinchang** [comment]
@MagnusS Yeah. Now everything works fine 👍

**Comment by stitchdad** [comment]
@MagnusS Tried it out with Version 17.03.0-ce-mac2 (15654) and everything seems to work fine now!  Thanks!

**Comment by djs55** [comment]
Thanks for confirming that everything now works. I'll close the ticket for you -- feel free to open new tickets if you have any other problems.

Thanks for your report and for using Docker for Mac!

**Comment by luisflsmarques** [comment]
hi all - getting this same error on windows 10 docker CE both edge and stable. Anytime I try to do a docker pull mysql for example it results in: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:46290->192.168.65.1:53: i/o timeout
