### ISSUE TITLE
1.13.1 Networking Issue

### ISSUE THREAD

**Issue by mesquka** [docker/for-mac#1350]
### Expected behavior
Docker Installs

### Actual behavior
Docker Fails to connect to networking links

### Information

88668E1D-6E6C-4499-B4C1-134136B5018B
```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/88668E1D-6E6C-4499-B4C1-134136B5018B/20170228-095752.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Permission denied (EACCES) connecting to /var/tmp/com.docker.vmnetd.socket: check permissions
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mesquka/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/mesquka/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/mesquka/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mesquka/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/mesquka/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mesquka/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/mesquka/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/mesquka/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

I have tried the fixes in #8 to no success.

**Comment by MagnusS** [comment]
Thanks for the report @mesquka. 

I see in the logs that you have removed some of the files and changed permissions, which looks like it triggered a reinstall of `vmnetd` - but there's still a permission denied shown for the socket:

```
2017-02-28 09:57:42.372287+0800  localhost Docker[3442]: [com.docker.docker.] Install: privileged installation of com.docker.vmnetd successful
2017-02-28 09:57:42.418539+0800  localhost com.docker.vmnetd[3453]: com.docker.vmnetd starting
2017-02-28 09:57:47.378014+0800  localhost Docker[3442]: [com.docker.docker.] UnixDomainSocket: Failed to connect to /var/tmp/com.docker.vmnetd.socket: Permission denied
2017-02-28 09:57:47.378032+0800  localhost Docker[3442]: [com.docker.docker.] Terminator: Communication with networking components failed.
```

Could you run  `stat /var/tmp /private/tmp /var/tmp/com.docker.vmnetd.socket` to check the permissions on the socket and tmp directories?

If you haven't tried it yet it could help with a complete uninstall, reboot and reinstall of the latest version (currently 17.03.0-ce-mac2). You can uninstall without the UI using `/Applications/Docker.app/Contents/MacOS/Docker --uninstall`. Note that this command will remove all your Docker for Mac settings and containers as well.

**Comment by mesquka** [comment]
Did a complete uninstall and reboot.
Output of `stat /var/tmp /private/tmp /var/tmp/com.docker.vmnetd.socket` is:
`16777220 2350401 drwx------ 5 root wheel 0 170 "Feb 28 02:51:35 2017" "Mar  9 23:17:58 2017" "Mar  9 23:17:58 2017" "Feb 27 00:00:59 2017" 4096 0 0 /var/tmp
16777220 944951 drwxrwxrwt 13 root wheel 0 442 "Mar  9 06:55:30 2017" "Mar  9 23:14:18 2017" "Mar  9 23:14:18 2017" "Sep 29 07:16:14 2016" 4096 0 0 /private/tmp
stat: /var/tmp/com.docker.vmnetd.socket: stat: Permission denied`
and when run as root:
`16777220 2350401 drwx------ 5 root wheel 0 170 "Feb 28 02:51:35 2017" "Mar  9 23:17:58 2017" "Mar  9 23:17:58 2017" "Feb 27 00:00:59 2017" 4096 0 0 /var/tmp
16777220 944951 drwxrwxrwt 13 root wheel 0 442 "Mar  9 06:55:30 2017" "Mar  9 23:14:18 2017" "Mar  9 23:14:18 2017" "Sep 29 07:16:14 2016" 4096 0 0 /private/tmp
16777220 3269767 srw-rw-rw- 1 root daemon 0 0 "Mar  9 23:17:58 2017" "Mar  9 23:17:58 2017" "Mar  9 23:17:58 2017" "Mar  9 23:17:58 2017" 4096 0 0 /var/tmp/com.docker.vmnetd.socket`

**Comment by mesquka** [comment]
Things appear to be working now. I allowed r/w to /var/tmp, a script I was using for doing packet inspection on my network had messed around with the permissions on that directory.

**Comment by MagnusS** [comment]
@mesquake thanks for the update - great that it's working now!
