### ISSUE TITLE
After update, memory params are reset

### ISSUE THREAD

**Issue by wascou** [docker/for-mac#1354]
When I update Docker For Mac, params are often reset to default (2GB for memory).
And it is very annoying as I am not informed by this change.
And it is causing bad behaviour from some of my containers.
And it is difficult to diagnose and makes me lose a lot of time.
And I correct the bas behaviour by setting again the original values.
So please, STOP this.

**Comment by dirkjonker** [comment]
Yes, this is very annoying, I need 4GB memory to run a Microsoft SQL Server container, and every time I update docker I need to go to preferences and reset it.

**Comment by jeanlaurent** [comment]
Thanks for the report @wascou and @dirkjonker we're going to investigate and fix this.

It's now on the internal tracker tagged for attention from the dev team.
We'll post back here when we have an update.

**Comment by dirkjonker** [comment]
Seems to be fixed here, after the last update the settings remained intact!

**Comment by djs55** [comment]
@dirkjonker thanks for the confirmation!

For reference I've created a PR to enhance the configuration database upgrade mechanism (the thing which mis-fired and triggered this bug). The future system will allow us to change the default settings of parameters while preserving user overrides. I'm hoping to merge this shortly after the next edge release.
