### ISSUE TITLE
Docker for Mac: manifests not found after rmi -f

### ISSUE THREAD

**Issue by rickmendes** [docker/for-mac#1356]
### Expected behavior

After removing an image, I expect to be able to pull other images without error.

### Actual behavior

After removing a tagged alpine image this morning, every pull or run I do responds with a manifest not found message.

Ex:
```
docker pull python
Using default tag: latest
Error response from daemon: manifest for python:latest not found
```

### Information

 Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/5D48BF5B-ABAB-411C-944F-649B358769F1/20170228-105256.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

 1. docker pull alpine
 2. docker tag alpine my.repo.domain/my-org/my-alpine:v1
 3. docker rmi -f alpine my.repo.domain/my-org/my-alpine
 4. docker pull python

Restarting and stopping/starting Docker for Mac did not resolve the problem.

**Comment by eheuje** [comment]
The same for me since a few minutes

**Comment by jiridj** [comment]
Same here. Has been driving me mad!

**Comment by kpbhiper** [comment]
+1

**Comment by justincormack** [comment]
See http://status.docker.com/ the Hub is currently down, although it is coming back up now I believe.

**Comment by rickmendes** [comment]
Thanks @justincormack. Looking at the AWS S3 issues today, I am going to guess the hub registry backs up to S3.

**Comment by rickmendes** [comment]
S3 is back up and my docker client is working normally again. Closing this as it was not a docker for mac issue after all.
