### ISSUE TITLE
credential helpers are used even if they are not configured

### ISSUE THREAD

**Issue by remickTF** [docker/for-mac#1359]
### Expected behavior
credential helper should only be used if config.json "credsStore" value declares it.

### Actual behavior
credential helper is used whenever it is discovered on $PATH

### Information

osxkeychain was configured, but then wanted another form of credential management. removed "credsStore:"osxkeychain" from config.json, but docker continued to refrence keychain until the docker-credential-osxkeychain was removed.   

### Steps to reproduce the behavior

see above

**Comment by remickTF** [comment]
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/32D5C614-A380-409B-952A-DD7CCC992263/20170228-174418.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by ebriney** [comment]
@remickTF : Unfortunately it is the engine default behaviour, if it finds `docker-credential-osxkeychain` in the `PATH` it will automatically use it and insert `"credsStore": "osxkeychain"` in config.json.

What we can do is to add an option in the settings so the symlink is not added to the path and so it uses the old base64 management.

As a workaround for now, unlink the credential-helper, remove `"credsStore": "osxkeychain"` from config.json and do a login is working.
The link is re-created every time you launch the app so adding something like `unlink $(which docker-credential-osxkeychain)` to your `.bash_profile` can help

**Comment by iangkent** [comment]
As we are calling docker-py within a python docker container based on alpine the docker-pycreds package used by docker-py cannot execute the docker-credential-osxkeychain executable from host. We would like the ability to configure docker on mac to use base64 encoded creds in config.json by default.

**Comment by dimaspivak** [comment]
Same issue on our end. We run a Docker client inside a Docker container that talks to the host's `/var/run/docker.sock` and have previously passed credentials in by mounting in the `~/docker` directory from the host into the container.

**Comment by jeanlaurent** [comment]
We're going to add some sort of graphical element, so you can opt-out of using the native credential store. This would be probably on by default, you'll have to uncheck it.

**Comment by naphthalene** [comment]
Seems like a reasonable compromise :+1:

**Comment by jeanlaurent** [comment]
Well, this is actually shipped in 17.05 edge and 17.06 stable.

<img width="429" alt="screen shot 2018-03-23 at 10 37 23" src="https://user-images.githubusercontent.com/197016/37822353-7e1536ce-2e86-11e8-89f8-f3169e4face1.png">

Closing.
