### ISSUE TITLE
docker run - command not found

### ISSUE THREAD

**Issue by sharlynx** [docker/for-mac#1361]
### Expected behavior
docker run, docker info, docker or any other basic command

### Actual behavior
-bash: docker: command not found

### Information
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/766F7CBC-0D8D-4BDB-9162-1BD2D1C7E19D/20170301-221015.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Install stable docker version on Mac
Open docker
docker run on terminal

### Have tried the following:

```
ls -l /usr/local/bin/docker
lrwxr-xr-x  1 xieyin  staff  66  2 28 20:03 /usr/local/bin/docker -> /Users/xieyin/Library/Group Containers/group.com.docker/bin/docker

sudo ls -la /usr/local/
total 0
drwxr-xr-x   9 root  wheel   306  2 26 00:35 .
drwxr-xr-x@ 13 root  wheel   442  1 21  2016 ..
drwxr-xr-x  77 root  wheel  2618  2 28 20:03 bin
drwxr-xr-x  13 root  wheel   442  5  5  2016 git
drwxr-xr-x  29 root  wheel   986  6 22  2016 include
drwxr-xr-x  21 root  wheel   714  6 23  2016 lib
drwxr-xr-x   5 root  wheel   170  3 30  2013 man
drwxr-xr-x   3 root  wheel   102  2 15 06:03 remotedesktop
drwxr-xr-x   6 root  wheel   204  1 20  2016 share

sudo ls -la /usr
total 8
drwxr-xr-x@   13 root  wheel    442  1 21  2016 .
drwxr-xr-x    32 root  wheel   1156 12 22 20:23 ..
drwxr-xr-x     5 root  wheel    170  8 23  2015 X11
lrwxr-xr-x     1 root  wheel      3 10 21  2015 X11R6 -> X11
drwxr-xr-x     3 root  wheel    102  8 27  2015 adic
drwxr-xr-x  1056 root  wheel  35904 12 22 20:23 bin
drwxr-xr-x   258 root  wheel   8772 12 17 20:50 include
drwxr-xr-x   288 root  wheel   9792 12 22 20:24 lib
drwxr-xr-x   187 root  wheel   6358 12 22 20:24 libexec
drwxr-xr-x     9 root  wheel    306  2 26 00:35 local
drwxr-xr-x   243 root  wheel   8262 12 22 20:23 sbin
drwxr-xr-x    46 root  wheel   1564  1 21  2016 share
drwxr-xr-x     4 root  wheel    136  9 17  2015 standalone

yins-MBP:~ xieyin$ ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
ln: /usr/local/bin/docker: File exists

/Users/xieyin/Library/Group\ Containers/group.com.docker/bin/docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by rogaha** [comment]
@sharlynx can you please confirm if the ` /usr/local/bin/` directory is in your `$PATH`? also can you try this: `$/usr/local/bin/docker ps`?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by dinana** [comment]
Facing the same issue on Mac OS X 10.10.5:

docker -ps
-bash: docker: command not found

echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

/usr/local/bin/docker
-bash: /usr/local/bin/docker: Permission denied

ls -ltr /usr/local/bin/docker      
lrwxr-xr-x  1 dishasha  staff  68 Aug  7 01:48 /usr/local/bin/docker -> /Users/dishasha/Library/Group Containers/group.com.docker/bin/docker

ls -ltr "/Users/dishasha/Library/Group Containers/group.com.docker/bin/docker"
lrwxr-xr-x  1 dishasha  staff  54 Aug  7 01:48 /Users/dishasha/Library/Group Containers/group.com.docker/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker

ls -ltr /Applications/Docker.app/Contents/Resources/bin/docker
-rwxr-xr-x@ 1 dishasha  admin  0 Aug  7 09:44 /Applications/Docker.app/Contents/Resources/bin/docker

**Comment by Anchit-Sood-100990** [comment]
I had the similar issue. I am sharing below what worked for me:
Try echo "$PATH"
`echo "$PATH"`
In case you don't have /usr/local/bin in it, try the following : 

`PATH=/usr/local/bin:$PATH
hash -r
docker run --rm hello-world`

In case you have /usr/local/bin in it, try the following : ****
`hash -r
docker run --rm hello-world`

I got the below output after running the above commands. (Hope this helps)

`Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
d172******2d: Pull complete 
Digest: ****************
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/`


-----end of output-----
