### ISSUE TITLE
F623A4E8-B31B-49A6-A29F-E42D92BF9492 com.docker.osx.hyperkit.linux failed to start

### ISSUE THREAD

**Issue by talliujobs** [docker/for-mac#1362]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

when WebStorm starts,  docker crashes.
```
F623A4E8-B31B-49A6-A29F-E42D92BF9492 com.docker.osx.hyperkit.linux failed to start
Exit code 9
```
```
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/F623A4E8-B31B-49A6-A29F-E42D92BF9492/20170301-224443.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by rogaha** [comment]
@talliujobs I wasn't able to pull the `log` files with that id `F623A4E8-B31B-49A6-A29F-E42D92BF9492/20170301-224443`. Can you please run & upload the `diagnostics` again?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
