### ISSUE TITLE
docker-compose froze when running down

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1363]
960549A5-E20C-4E41-B51B-FA16000C14C6

**Comment by rogaha** [comment]
@daveisfera it looks like the `container` is trying to delete a `directory` but the path doesn't exist anymore. 

```
2017-02-27 18:58:15-07  Docker[com.docker.osxfs][1098] <Warning>: dropped event syscall rmdir for /Users/dlj/projects/numetric/web/node_modules/babel-plugin-transform-react-jsx-self/node_modules/babel-runtime/core-js/json (bad lookup path)
```

Can you try to fix it and see if the issue persists?

**Comment by ijc25** [comment]
@rogaha Likely to be be the same underlying issue as @daveisfera is suffering from in #1265 I would imagine, which is something to do with osxfs's internal datamodel/event stream handling I think, not a container behaviour.

**Comment by rogaha** [comment]
@dave-tucker are you able to reproduce this issue?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by daveisfera** [comment]
@rogaha I don't have a deterministic reproducer, but this issue does happen.
