### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.

### ISSUE THREAD

**Issue by levibostian** [docker/for-mac#1365]
# Expected behavior

Docker compose starts. 

# Actual behavior

Docker on Mac starts, begins to build image on my Mac and seems to work, but after a few seconds starting on docker-compose it throws this error:

```
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.
Docker Version:
```

I have a docker-compose.yml file in my current directory that I try to start with: `docker-compose up --build`. Docker compose starts, downloads images I need, and begins to build an image for the Dockerfile in the directory. I see the status: `Building app` for about 18 seconds I counted last time  before it exited and threw the error: `ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.`

Docker version 1.13.1 (15353) Channel: Stable 94675c5a76
docker-compose version 1.11.1, build 7c5d5e4

Diagnostic ID: 07EC77E6-5C2A-4182-8A55-07C9EA8D3AF2

Output from: `ls -l /var/run/docker.sock`
lrwxr-xr-x  1 root  daemon  64 Feb 28 17:48 /var/run/docker.sock -> /Users/levibostian/Library/Containers/com.docker.docker/Data/s60

**Comment by MagnusS** [comment]
@levibostian thanks for the report. From your logs it looks like you ran out of disk space while writing to the qcow2 file. Have you tried to run "Reset to factory defaults" from preferences? This would recreate the disk image (note that this will also remove all images and containers).

**Comment by levibostian** [comment]
@MagnusS yes, I have run Reset to factory settings.

**Comment by levibostian** [comment]
Running out of storage could be a possibility. For the past few weeks my mac was low on disk storage but last week I cleared about 20gb. That could easily have been the issue when I created this issue but should not be an issue anymore. 

Also, interesting note: Last week I was having issues with starting and running Android emulators on my Mac. I had to re-install Intel HAXM on my machine to get Android emulators to work again (as explained [here](https://stackoverflow.com/questions/28955391/android-studio-error-with-hamx/28955775#comment72361921_28955775)). Perhaps that is also a reason this was not working?

**Comment by MagnusS** [comment]
HAXM doesn't work well with applications that use Hypervisor.framework unfortunately (like Docker for Mac), so this could be related - see https://code.google.com/p/android/issues/detail?id=198497.

**Comment by levibostian** [comment]
Seems about right.

**Comment by djs55** [comment]
@levibostian it sounds like out of disk space explains the original failure and then the HAXM incompatibility explains the remaining problems.

For reference there is a note in the [Known Issues](https://docs.docker.com/docker-for-mac/troubleshoot/#known-issues) of the docs which suggests that it's sufficient to exit Docker for Mac while using HAXM -- do you think this needs to be rewritten to say HAXM must be reinstalled after using Docker for Mac?

Since I think Docker for Mac is working as expected I'll close this ticket. Thanks for your report and for using Docker for Mac!

**Comment by xuan-yue** [comment]
Not sure if this is relevant for the memory issue, but I was getting the same error and unable to get the docker daemon to run. This helped to solve the issue:

sudo nohup docker daemon -H http://tcp://0.0.0.0:2375 -H http://unix:///var/run/docker.sock
