### ISSUE TITLE
Missing clock synchronization between osx and alpine docker-server

### ISSUE THREAD

**Issue by venth** [docker/for-mac#1367]
### Expected behavior
internal clock of alpine is synchronized
### Actual behavior
the clock it's unsynchronized
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. wait with docker running few days
  2. screen to alpine
  3. date (indicates that clock is unsynchronized

Temporal workaround:
hwclock -s 

called manually

**Comment by rogaha** [comment]
@venth it seems to be an issue related to the `sleep` function in `OSX`, it seems that the current 'best' workaround is this: 
```
brew install sleepwatcher
brew services start sleepwatcher
echo /usr/local/bin/docker run --rm --privileged alpine hwclock -s > ~/.wakeup
chmod +x ~/.wakeup
```

@justincormack  is there something else that we can do here?

**Comment by rogaha** [comment]
@venth is that approach a viable option for you?

**Comment by rogaha** [comment]
I'm closing this in favor of https://github.com/docker/for-mac/issues/17, @venth let's keep the discussions on the other thread, so people can benefit from it.
