### ISSUE TITLE
What version of Docker am I running now?

### ISSUE THREAD

**Issue by fideloper** [docker/for-mac#1368]
### Expected behavior

`docker version` command should show Docker version (e.g. 1.13.x), should be latest stable.

### Actual behavior

```bash
fideloper@host~ docker version

Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

I have it marked to only get stable versions. Note that is says "Experimental: true" above.

![image](https://cloud.githubusercontent.com/assets/467411/23511416/9679181e-ff22-11e6-866b-51cfeb2847d8.png)

### Steps to reproduce the behavior

I received an notification of an application update this morning and followed the steps to update.

**Comment by rogaha** [comment]
@fideloper thanks for reaching out. We are going to have the `experimental` features enabled by default on both channels (`stable` and `edge -- a.k.a beta`). The experimental features usually, only give you extra options, so you won't be impacted if you are not using them. In any case, you can easily disable it here (see below)
![screen shot 2017-03-02 at 7 53 33 am](https://cloud.githubusercontent.com/assets/4483394/23514833/5fa9b550-ff1d-11e6-894c-e3311406ccb5.png)
: 

Please let us know if you have any other questions. here is the link to the `experimental` features documentation: https://github.com/docker/docker/tree/master/experimental#docker-experimental-features

**Comment by fideloper** [comment]
Thanks. The main issue here was Docker version, but that was before the blog post was out (before I found it, rather) explaining the changes in the Docker version.

Thanks!

**Comment by rogaha** [comment]
awesome, sorry I forgot to share the link to the `blog post` (https://blog.docker.com/2017/03/docker-enterprise-edition/). Thanks @fideloper!
