### ISSUE TITLE
Update to Version 17.03.0-ce-mac1 unusable

### ISSUE THREAD

**Issue by adacey** [docker/for-mac#1370]
### Expected behavior

Existing containers be able to start properly.

### Actual behavior

Failures to start, docker daemon crashing.

### Information

$ docker start plex plexcleaner openvpn sabnzbd transmission sonarr couchpotato nginx muximux
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
Error response from daemon: Mounts denied: closed
nginx
Error response from daemon: Mounts denied: closed
Error: failed to start containers: plex, plexcleaner, openvpn, sabnzbd, transmission, sonarr, couchpotato, muximux
$ docker ps
Error response from daemon: Bad response from Docker engine

Reboot and re-attempt:

$ docker start plex plexcleaner openvpn sabnzbd transmission sonarr couchpotato nginx muximux
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error response from daemon: ContainerInspect failed
Error: failed to start containers: plex, plexcleaner, openvpn, sabnzbd, transmission, sonarr, couchpotato, nginx, muximux
$ docker rm plex
Error response from daemon: Bad response from Docker engine

### Steps to reproduce the behavior

Installed update, tried to start containers. Then performed a reboot and attempted a 2nd time. Rolled back to 1.13.1, works fine.

**Comment by dylanscott** [comment]
I'm running into similar issues. Sometimes my containers start but have hugely degraded performance (in-container builds that usually take 1 minute taking 7), and eventually crash, or the docker daemon hangs.

How can I roll back to 1.13.1? I don't have time machine backups unfortunately. I can't find an old installer.

**Comment by vovimayhem** [comment]
Have you tried the "Reset to factory defaults" option?

I did this right after installing the update. I didn't even tried to run any of the previous containers.

I've been working without problems during the day. I did notice however one teammate having problems with compose, tho.

**Comment by dylanscott** [comment]
I managed to get an installer to roll back to 1.13.1 but I actually think I may have been just running into #1354. I'm holding off on upgrading just to be safe but I think my issues were memory related.

**Comment by rogaha** [comment]
@adacey can you please try to `upgrade` it again and run the `diagnostics`? It would help us to identify the issue.

**Comment by rogaha** [comment]
@vovimayhem can you please raise an issue related to the `compose` error your teammate is seeing?

**Comment by vovimayhem** [comment]
@rogaha unfortunately, I was in a hurry and didn't took notes about the precise error python was throwing. I do remember that had something to do with 'docker-py', something about having old versions of something, and that compose was suggesting uninstalling docker (or something related to) via pip and re-installing it again.

This was on one of our interns' machine. I had to follow instructions quickly :( Sorry 'bout that.

No problems in my machine, tho.

**Comment by vovimayhem** [comment]
@rogaha I might have a chance to check the intern's machine later to get exactly which command I ran to fix that, later in the afternoon

**Comment by rogaha** [comment]
sounds good! thanks @vovimayhem, I appreciate it!

**Comment by adacey** [comment]
Diagnostic ID DE7F89AF-97A3-4E1A-84D9-903808F3281F

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/DE7F89AF-97A3-4E1A-84D9-903808F3281F/20170304-124108.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

That's straight from rerunning the upgraded version of Docker (I'd kept it and just pulled the old version out of the trash). I've noticed that even running docker ps kills docker.

**Comment by adacey** [comment]
Correction, Docker is dying even if I just leave my system idle with no containers running. I can try a factory reset, but frankly this is the "stable" channel and it's utterly ridiculous that a recommended upgrade from the previous stable release would be completely unusable without having to blow away all of my containers yet again.

**Comment by xpert13** [comment]
@ dylanscott Hi. Where did you find 1.13.1 installer? I would be very grateful for a link.

**Comment by rogaha** [comment]
@xpert13, thanks for sharing the link! That one is the latest `1.31.1` stable release. @adacey let us know if that solves the `instability` issues, we are working hard to fix them. Thanks for the uploading the `diagnostics` files!

**Comment by dsheets** [comment]
@adacey the issue is a change in the Linux distribution we ship that now puts something in the `/mnt` directory in the VM (compared to 1.12.6 where it was empty). If you change your file system export settings in :whale: ➡️ `Preferences...` ➡️ `File Sharing` and remove `/mnt` and then re-add more specific directories (e.g. `/mnt/mydrive`) it should resume working.

This is the same issue as #1379. I've opened an issue to track handling export directory invalidation over Linux upgrades. Thanks for your report and I'm sorry for the inconvenience this has caused. We're improving our component integration to reduce incidents like these in the future.

**Comment by adacey** [comment]
Hi, yes sorry I'd been offline for a few days with a move. I did upgrade again and caught the file sharing issue after resetting to factory defaults. That forced me to recreate my containers (fortunately, I have all of those definitions saved) so I can't say for certain if just fixing the file sharing would have resolved the issue without the reset.

**Comment by rubyisbeautiful** [comment]
I don't know if this issue does or does not have enough info needed.  I also upgraded from the last pre ce-mac to `17.03.0-ce-mac2 (15657)` and got the python errors:

```
$ docker-compose rm
ERROR: Dependency conflict: an older version of the 'docker-py' package is polluting the namespace. Run the following command to remedy the issue:
pip uninstall docker docker-py; pip install docker
```

I can (but haven't) attached the various errors from me trying to follow that advice...it didn't work and I didn't really expect it to.  Here is my diagnostic ID D4CE69E8-9652-4435-9FD7-67FBC00E7667 as well.  I hope this help.

**Comment by dsheets** [comment]
We believe we have fixed this issue. If you are still experiencing this problem or a similar problem, please open a new issue with a detailed description and reproduction of the problem. Thanks for your reports!
