### ISSUE TITLE
docker for mac accessing RANDOM keychain elements

### ISSUE THREAD

**Issue by zenspider** [docker/for-mac#1371]
### Expected behavior

Create your own keychain item, leave everything else alone

### Actual behavior

I just tried to build an image and a security dialog came up asking for docker to access a locked keychain (I have several) for the application password for Echofon. I don't even have echofon anymore, but it is bewildering why you would ask for that. I denied and the image built fine.

The _real problem_ is that this happens on **every build**. Now it is asking for flickr. This is a clear security violation and a severe annoyance if it is just going to keep picking random keychain items each time and ask for clearance for every build.

### Information

![screen shot 2017-03-02 at 1 09 47 pm](https://cloud.githubusercontent.com/assets/9832/23527167/b564db2e-ff49-11e6-8989-06a60c0e66a0.png)

![screen shot 2017-03-02 at 1 09 55 pm](https://cloud.githubusercontent.com/assets/9832/23527173/b96b9230-ff49-11e6-92b7-96b3acc6923f.png)

### Steps to reproduce the behavior

  1. run docker for mac
  2. lock your keychains
  3. `docker build --rm -t $IMAGE_NAME .`

**Comment by zenspider** [comment]
I've rolled back to the previous version via Time Machine. Probably running the newer linux image as a side-effect, but that's fine. This behavior is untenable and scary.

**Comment by ebriney** [comment]
@zenspider : I just looked at the code of credential helper and it seems that it doesn't specify the login keychain when it is trying to retrieve your password using `SecKeychainFindInternetPassword`. So the default behaviour is to look into every registered user keychains. I'll add an issue and fix it ASAP.
Thanks for the reporting.

**Comment by zenspider** [comment]
@jeanlaurent not sure what labels you have but `kind/bug` seems like a pretty lax severity, no?

A friend brought up that this issue might not be a big deal as it is hitting your local docker server... but it might be worse if you're using swarm (tho I'm not).

Is there an ETA on this fix?

**Comment by jeanlaurent** [comment]
@zenspider Root issue is https://github.com/docker/docker/issues/31517

Tentative fix is in : https://github.com/docker/docker-credential-helpers/issues/46 for now.

No ETA on release yet. Will keep you posted.

**Comment by rajatjindal83** [comment]
I ran into this issue too. got worried for a second as to why docker was asking permissions for my banking credentials

**Comment by ericparton** [comment]
Is this going to be released in the near future? I'm trying to move some mac using developers over to docker but this is really freaking people out.

**Comment by avsm** [comment]
Aiming for a release this week. Apologies for the delay!

**Comment by jeanlaurent** [comment]
A fix has been made in [docker credentials helper v0.5.0](https://github.com/docker/docker-credential-helpers/releases/tag/v0.5.0) which is now bundled into all Docker for Mac and Docker for Windows available versions :
* Since last week in [17.03.1-ce-rc1-mac3](https://download.docker.com/mac/edge/Docker.dmg) on the edge channel
* A few hours ago on [17.03.1-ce-mac5](https://download.docker.com/mac/stable/Docker.dmg) on the stable channel

Auto-update should get you the latest version or you get download links above.

Closing, as we believe this is fixed, but feel free to re-open if we missed something.

Thanks

**Comment by lindseyspratt** [comment]
This problem appears to still be occurring. I ran version:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

running:
docker login -u USER -p PASS HOST:8443
causes docker to ask to access the KeyChain for a randomly chosen entry.
If I deny the request, then the command fails with:
"error getting credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`"
If I allow the request, then the command fails with:
"Error saving credentials: error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.`"

**Comment by zenspider** [comment]
@lindseyspratt I don't think that's the same issue.

**Comment by lindseyspratt** [comment]
I agree. It did not occur to me that it might be a different problem until after I made the initial comment, so I created the new issue #1540 and noted the connection.
