### ISSUE TITLE
Error response from daemon: Mounts denied: closed

### ISSUE THREAD

**Issue by PHPiotr** [docker/for-mac#1379]
### Expected behavior
Docker container (created from library/mysql) should start. It was working normally until yesterday when I updated docker for mac.
docker -v
Docker version 17.03.0-ce, build 60ccb22

### Actual behavior
docker start mysql-5.7.17
Error response from daemon: Mounts denied: closed
Error: failed to start containers: mysql-5.7.17

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnstic ID: 955F29A7-6274-471F-A253-066FC7877A82
Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.2 (build: 16C67)
logs: /tmp/955F29A7-6274-471F-A253-066FC7877A82/20170303-115450.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

1. I created mysql container and mounted some volumes this way: -v /my/own/datadir:/var/lib/mysql
- I do not remember the exact run command but it certainly included mounting in the exact folders as described above (maybe it relates to https://forums.docker.com/t/getting-mounts-denied-on-previously-working-container-after-upgrading-to-v1-12-0-beta18-3-gec40b14/17546/5 ?) 
2. It was working fine until recent update

**Comment by dsheets** [comment]
@PHPiotr the issue is a change in the Linux distribution we ship that now puts something in the `/mnt` directory in the VM (compared to 1.12.6 where it was empty). If you change your file system export settings in :whale: ➡️ `Preferences...` ➡️ `File Sharing` and remove `/mnt` and then re-add more specific directories (e.g. `/mnt/mydrive`) it should resume working.

I've opened an issue to track handling export directory invalidation over Linux upgrades. Thanks for your report!

**Comment by PHPiotr** [comment]
Hi,

thanks.

I actually did it.
I mean I have reset docker, then re-run my containers with more specific
directories mounted, for example /mnt/tools /mnt/misc etc.

And indeed it works.

Regards

Piotr
