### ISSUE TITLE
traceroute (udp) impossible to reach

### ISSUE THREAD

**Issue by ale-batt** [docker/for-mac#1381]
Hello, I am having an issue using docker for mac, i think is the udp packet who can't reach my target.
this is a exemple:

$ docker run --rm -it debian:8 /bin/bash
$ apt-get update && apt-get install traceroute
$ traceroute docker.com

```
traceroute to docker.com (54.87.209.221), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.035 ms  0.016 ms  0.025 ms
 2  * * *
 3  * * *
 4  * * *
 ...
 30 * * *
```
i tried with `--net=host` and `--net=bridge` but it's not working either.
Of course it working well outside of a docker container

With the `-I` option, (` -I  Use ICMP ECHO instead of UDP datagrams.`) i have no issue
```
$ traceroute -I docker.com
traceroute to docker.com (54.87.209.221), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.033 ms  0.010 ms  0.009 ms
 2  ec2-54-87-209-221.compute-1.amazonaws.com (54.87.209.221)  0.181 ms  0.155 ms  0.712 ms
```

docker for mac 1.13.1 (15353)

**Comment by ale-batt** [comment]
I'm not the only one : https://forums.docker.com/t/traceroute-from-docker-for-mac-and-docker-for-windows-never-traces/24033

**Comment by MagnusS** [comment]
Thank you for the report @ale-batt. 

This is currently a limitation of `vpnkit`, used by Docker for Mac to provide networking. The ICMP messages are not forwarded to/from the external network, so the ICMP replies you see within the container are actually local replies. It appears to work, but the destination is always reached in one hop and the results are unfortunately incorrect. The TTL on packets going out of the container is also not preserved, so currently `traceroute` would be unable to find the route even if the ICMP messages came back correctly.

I've opened issues in the `vpnkit` repo for the TTL value (docker/vpnkit#193) and ICMP messages (docker/vpnkit#194)

**Comment by ethanmick** [comment]
Hello, just wanted to report that I ran into this same issue just now. Is there any estimated time for when this will be fixed? Thank you!

**Comment by BrendonW** [comment]
I'd suggest you follow the two vpnkit issues and ask there? That is what needs to move before this can be resolved.

You can probably do a workaround by setting up an ssh tunnel to the host...

**Comment by arpadkun** [comment]
I also ran into this problem. I have not seen much movement on the two other tickets, will follow up there as well. Help is appreciated.

**Comment by arpadkun** [comment]
Btw, the same problem exists with TCP as well:

```
root@moby:/# tcptraceroute github.com    
Selected device eth0, address 192.168.65.2, port 44773 for outgoing packets
Tracing the path to github.com (192.30.253.112) on TCP port 80 (http), 30 hops max
 1  lb-192-30-253-112-iad.github.com (192.30.253.112) [open]  155.522 ms  152.432 ms  150.071 ms
root@moby:/# 

```

The latency is accurate, the number of hops are not. :)

**Comment by djs55** [comment]
There are some experimental fixes in `vpnkit` for ICMP and UDP (not yet TCP). They're not in a current Docker for Mac build, but you can experiment as follows:

- Download [vpnkit.zip](https://github.com/docker/for-mac/files/1440331/vpnkit.zip)
- `unzip vpnkit.zip`
- check the checksum with
```
$ sha1sum Contents/Resources/bin/vpnkit 
fc6703018187057a374af60ce32b8dd5529f662d  Contents/Resources/bin/vpnkit
```
- backup your existing file `cp /Applications/Docker.app/Contents/Resources/bin/vpnkit /Applications/Docker.app/Contents/Resources/bin/vpnkit.backup`
- `cp Contents/Resources/bin/vpnkit /Applications/Docker.app/Contents/Resources/bin/vpnkit `
- restart Docker for Mac

I tested this against edge build `Version 17.10.0-ce-mac36 (19824)` by running
```
docker run -it alpine traceroute -n www.google.com
```
and comparing the results to the same `trace route -n www.google.com` on my Mac -- they looked similar.

Let me know what you think!

**Comment by arpadkun** [comment]
Thank you very much! Works like a charm, really appreciate your help!

**Comment by jzck** [comment]
any way to know when this fix will be released in mainline docker for mac? unfortunately I don't have admin rights to change the vpnkit at my school...

**Comment by dynamicdeploy** [comment]
I am facing the same issue in Docker for Windows. When I run docker run -it alpine traceroute -n www.google.com
It never resolves

C:\datafiles\onerowconsole>docker run -it alpine traceroute -n www.google.com
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
df20fa9351a1: Pull complete                                                                                             Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
traceroute to www.google.com (172.217.5.100), 30 hops max, 46 byte packets
 1  172.17.0.1  0.013 ms  0.006 ms  0.006 ms
 2  *  *  *
 3  *  *  *
 4  *  *  *
 5  *  *  *
 6  *  *  *
 7  *  *  *
 8  *  *  *

goes on..
