### ISSUE TITLE
Issue with Docker start on Mac

### ISSUE THREAD

**Issue by jeanclam** [docker/for-mac#1382]
Diagnostic ID:
6FAA919A-07D1-43F9-AD51-3C956CD491A1

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.11.5 (build: 15F34)
logs: /tmp/6FAA919A-07D1-43F9-AD51-3C956CD491A1/20170303-074530.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jeanlam/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/jeanlam/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jeanlam/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jeanlam/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/jeanlam/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jeanlam/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mloayzagahona** [comment]
I have a similar issue

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/8E086851-9791-4672-96BD-1982E3713165/20170303-130120.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/nzw118/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/nzw118/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/nzw118/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/nzw118/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/nzw118/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/nzw118/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by idris** [comment]
Having the same issue as well.  Even on today's version: Version 17.03.0-ce-mac2 (15654)

**Comment by MagnusS** [comment]
Thanks for the report @jeanclam. Unfortunately it looks like your disk image contains errors. Your logs contain:
```
2017-03-03 07:39:30-06 Jeans-MacBook-Air Docker[com.docker.driver.amd64-linux][919] <Notice>: com.docker.hyperkit: [ERROR] Found two references to cluster 101234: 60069.36728 and 60069.34544
2017-03-03 07:39:30-06 Jeans-MacBook-Air Docker[com.docker.driver.amd64-linux][919] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure
2017-03-03 07:39:30-06 Jeans-MacBook-Air Docker[com.docker.driver.amd64-linux][919] <Notice>:   "Found two references to cluster 101234: 60069.36728 and 60069.34544")
```
This may have been caused by a bug in an earlier version of Docker for Mac which could silently corrupt the disk image. To recover you can "Reset to factory defaults" or remove the disk image manually (`rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`) - note that both solutions will remove all images and containers. I'm very sorry for the inconvenience. 

@mloayzagahona @idris please open new tickets with a diagnostic ID so we can take a look at your issues! Thanks

**Comment by mloayzagahona** [comment]
I have removed all the content of the folde ~/Library/Containers/com.docker.docker and after this I was able to install and start docker after very long time.

Thanks

**Comment by MagnusS** [comment]
@mloayzagahona thanks for the update and good to hear it's working again
