### ISSUE TITLE
Docker For Mac Not Starting

### ISSUE THREAD

**Issue by lgwaustralia** [docker/for-mac#1384]
### Expected behavior
Docker should start normally after upgrade
### Actual behavior
Docker shows orange staring signal and never completes
### Information
Docker for Mac: version: 17.03.0-ce-mac1 (05a8abd30)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/B6C114FE-C805-4C52-B2F6-37FEFE477CAF/20170304-034503.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

 Upgrade from previous version

**Comment by lgwaustralia** [comment]
- I uninstalled, reset to factory settings
- Still no startup
- I noticed that containers were trying to start without any commands run by me

$ docker ps

- Did factory reset again but did not copy images over
- Started successfully
_Now attempting to download my images again_

**Comment by rogaha** [comment]
@lgwaustralia I'm glad it finally worked. We are investigating internally why this is happening. Thanks for reaching out to us!
