### ISSUE TITLE
Cannot connect to daemon on fresh install: Cannot connect to the Docker daemon at tcp://192.168.59.103:2376. Is the docker daemon running?

### ISSUE THREAD

**Issue by jaredonline** [docker/for-mac#1386]
### Expected behavior

`docker run hello-world` runs the hello world app and works immediately after installing docer.

### Actual behavior

```sh
$ docker run hello-world
docker: Cannot connect to the Docker daemon at tcp://192.168.59.103:2376. Is the docker daemon running?.
See 'docker run --help'
```

### Information

Output of diagnostics:

```
Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/7F4A8A8E-8CC9-4E9B-B357-E48062E96875/20170304-125817.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostic ID:

```
7F4A8A8E-8CC9-4E9B-B357-E48062E96875
```

### Steps to reproduce the behavior

  1. Install Docker for Mac on OS X Yosemite 10.10.5
  2. Open iTerm 2
  3. Run `docker run hello-world`

**Comment by jaredonline** [comment]
FWIW, I'm also experiencing #1385 as well (I plus-oned it there).

**Comment by jessethegame** [comment]
I had the same issue today

I had used `boot2docker` in the past and found out it was deprecated, so I installed docker for mac and upgraded OSX to 10.10.5

It turned out that the old configuration in my `~/.bashrc` had a few `DOCKER_` env vars, one of which `DOCKER_HOST=tcp://192.168.59.103:2376`.

Removing the env vars from my `.bashrc` solved the problem for me.

**Comment by MagnusS** [comment]
Thanks for the report @jaredonline. As @jessethegame mentions above this looks like there are left over `DOCKER_` environment variables that are set incorrectly. Removing these should fix the issue. 

I'm closing this issue for now, but please let us know if this didn't resolve the issue.

**Comment by jaredonline** [comment]
Thanks @jessethegame and @MagnusS [= This worked for me =D

**Comment by hannesa2** [comment]
Thanks to @jessethegame I uninstalled `boot2docker` and I removed the `DOCKER*` viariables from `.bash_profile` and now it works properly
