### ISSUE TITLE
Upgrade uses disruptive modal dialog box

### ISSUE THREAD

**Issue by tripleee** [docker/for-mac#1389]
I got prompted to upgrade to a new version and clicked OK.

### Expected behavior

I expected the download to proceed in the background and somehow request my attention when it's required (to type in passwords etc)

### Actual behavior

The download dialog box grabbed focus and prevented me from doing anything else with my computer during the download.

### Information

I seem to have upgraded to 17.03.0-ce-mac1 (15583) just now.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Diagnostic ID: C5C066EB-0EAB-48FF-80A4-1D614FB88C1F

  - A reproducible case if this is a bug, Dockerfiles FTW

I assume this is reproducible at will by having an older version and attempting to use your computer.

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MagnusS** [comment]
Thank you for the report @tripleee. I've added your feedback to our internal issue tracking improvements to the upgrade process, so I'll close this issue.

**Comment by tripleee** [comment]
I can confirm that the latest upgrade no longer had this behavior.  Thanks for the quick fix!
