### ISSUE TITLE
Limiting docker container access to fixed ip address

### ISSUE THREAD

**Issue by bikashmishra100** [docker/for-mac#1390]
We use docker on mac to process cordova build requests. The entire build happens inside docker container. We want to restrict the resources the build process can access. So we want to configure docker container to be able to talk to a fixed ip address and port. The target IP address and port has [Squid](https://en.wikipedia.org/wiki/Squid_(software)) proxy installed.

Is there any way i can achieve this? I tried creating different docker bridge networks but could not limit the access.

**Comment by avsm** [comment]
It sounds like you could use the new "docker build --network" feature to do this.  Create an isolated network for the build with "docker network", and then have a Squid container that is on both the default network (with Internet access) and the new isolated build one. 

See https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-without-using-user-defined-networks for how to link containers to make this possible.

**Comment by bikashmishra100** [comment]
thanks @avsm. Can i run Squid in standalone (on the mac host, not in the docker container) and achieve this?

**Comment by justincormack** [comment]
I don't think there is currently a way to provide only firewalled access to a container.

**Comment by bikashmishra100** [comment]
Actually we did it with docker on rhel where we could define rules on the docker0 interface with iptables. The missing docker0 interface on mac makes it difficult to achieve.

**Comment by justincormack** [comment]
@bikashmishra100 the "missing docker0 interface on mac" makes no difference as you do not want to add the firewalling on the mac. You can add host firewall rules on `docker0` with `--net=host` and sufficient privileges.

**Comment by bikashmishra100** [comment]
I worked on suggestions given by @avsm.

1. Created isolated network.
```
docker network create isolated_nw --internal
```
2. Started squid. Here i am using busybox as an example squid implementation.
```
docker run --rm --name=squid -it busybox
```
3. Connected squid to the isolated network.
```
docker network connect isolated_nw squid
```
4. Ran ifconfig in squid container to check the configuration.
```
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1050 (1.0 KiB)  TX bytes:858 (858.0 B)

eth1      Link encap:Ethernet  HWaddr 02:42:AC:12:00:02
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1360 (1.3 KiB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
5. Ran build service in isolated_nw.
```
docker run --rm --name=build1 --net=isolated_nw -it busybox
```
6. Ran ifconfig in the build1 container.
```
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:03
          inet addr:172.18.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:508 (508.0 B)  TX bytes:508 (508.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
7. Ping results from build1 container. External ip is blocked and squid is reachable.
```
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
/ # ping squid
PING squid (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.143 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.211 ms
64 bytes from 172.18.0.2: seq=2 ttl=64 time=0.198 ms
^C
--- squid ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.143/0.184/0.211 ms
```
8. Ping result from squid container where external ip is reachable.
```
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=37 time=0.810 ms
64 bytes from 8.8.8.8: seq=1 ttl=37 time=0.585 ms
64 bytes from 8.8.8.8: seq=2 ttl=37 time=0.654 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.585/0.683/0.810 ms
```

@avsm thank you for the directions. I am able to achieve it.
@justincormack I will try out your suggestions and post the results here tomorrow morning.

**Comment by avsm** [comment]
@bikashmishra100 great, thanks for posting the results on this issue as well -- very helpful for any other users searching for guidance on the same setup.

**Comment by bikashmishra100** [comment]
@justincormack I tried your method and below are the results. It worked. Thank you for the details. I feel it is hacky to tweak the moby linux. What is your opinion?

1. Started alpine linux in privileged mode with --net=host option.
```
docker run --rm --privileged --net=host -it alpine sh
```
2. Installed iptables.
```
apk add -U iptables
```
3. Ran separate container.
```
docker run --rm -it alpine sh
```
4. Installed curl in second container.
```
apk add -U curl
```
5. Tested curl in second container. Output truncated below for brevity.
```
curl -v http://t.co
...
< HTTP/1.1 200 OK
< Content-Length: 3154
< Content-Type: text/html; charset=utf-8
< Date: Tue, 07 Mar 2017 10:55:34 GMT
< Server: tsa_o
...
```
6. Ran below command in first container to block connections.
```
iptables -I FORWARD -i docker0 -j REJECT
```
7. Tried curl again in second container.
```
curl -v http://t.co
* Rebuilt URL to: http://t.co/
* getaddrinfo(3) failed for proxy:8080
* Couldn't resolve proxy '(nil)'
* Closing connection 0
curl: (5) Couldn't resolve proxy '(nil)'
```

**Comment by justincormack** [comment]
@bikashmishra100 at present there is no easy way to supply a set of iptables rules that will not be overridden by Docker; there is an issue tracking this https://github.com/docker/docker/issues/24848 if that is implemented we could provide a way to configure a set of iptables rules for the VM automatically, but without that it is a little difficult.

**Comment by bikashmishra100** [comment]
@justincormack i have got all the information. I am not sure if you would like to keep this issue open, i saw the triage label. Just one last question. Will we be able to see darwin/osx containers in future?

**Comment by justincormack** [comment]
@bikashmishra100 it is pretty difficult to make darwin/osx containers unfortunately. There are licensing issues, and the OS does not have the right sort of tooling.
