### ISSUE TITLE
Cannot start container on port 8080

### ISSUE THREAD

**Issue by cherealnice** [docker/for-mac#1393]
### Expected behavior
My container running on port 8080 should run
### Actual behavior
Fails to start, saying that port 8080 is in use
### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.3 (build: 16D32)
logs: /tmp/EC6FB6BB-0E6B-4FA9-B7F4-20D774988BDB/20170306-111126.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

- `docker ps` shows no processes on 8080

- `sudo lsof -i :8080 `
```COMMAND    PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 8047 cherealnice   20u  IPv4 0xe1953651b1fdcda9      0t0  TCP *:http-alt (LISTEN)
com.docke 8047 cherealnice   21u  IPv6 0xe1953651bd639799      0t0  TCP localhost:http-alt (LISTEN)
```

### Steps to reproduce the behavior

  1. Try to start a container on port 8080
  2. Open issue and let people smarter than me look at it ;)

**Comment by cherealnice** [comment]
Update to `17.03.0-ce-mac2 (15654)` fixed the issue

**Comment by cherealnice** [comment]
Thought an update fixed the issue, but did not

**Comment by MagnusS** [comment]
Thanks for the report. Unfortunately it looks like your logs were not uploaded correctly. Could you try  "Diagnose & Upload" again to upload the logs and post the new ID here? Thanks

**Comment by cherealnice** [comment]
@MagnusS Thanks for the reply.  I wound up resetting to factory defaults and rebuilding everything which solved the issue for me.  I'll close this issue and reopen if I run into it again.
