### ISSUE TITLE
Can't push to local private registry running as a swarm mode service

### ISSUE THREAD

**Issue by hairyhenderson** [docker/for-mac#1394]
### Expected behavior

When running a local `registry:2` service in a local swarm on Docker for Mac, I expect that this will succeed:

```console
$ docker push localhost:5000/alpine:3.5
```

### Actual behavior

But, it hangs here:

```console
$ docker push localhost:5000/alpine:3.5
The push refers to a repository [localhost:5000/alpine]

```

### Information

- Diagnostic ID: 671C7B17-2FE1-47BF-8394-AEDF4A759214

### Steps to reproduce the behavior

1. create a volume:
```console
$ docker volume create registry
registry
```
2. pull `alpine:3.5` (for example)
```console
$ docker pull alpine:3.5
...
Status: Downloaded newer image for alpine:3.5
```
3. re-tag `alpine:3.5` to go to the local registry
```console
$ docker tag alpine:3.5 localhost:5000/alpine:3.5
```
4. now create a registry service
```console
$ docker service create --name registry --mount type=volume,source=registry,target=/var/lib/registry -p 5000:5000 registry:2
cg0yskdpno8p43yyzobp1h22q
```
5. make sure it's listening
```console
$ docker service logs registry | tail -n1
registry.1.uyr3538m0vwg@moby    | time="2017-03-06T16:19:45Z" level=info msg="listening on [::]:5000" go.version=go1.7.3 instance.id=59f0b41a-1c7d-4e0e-8463-1a8ce27276fd version=v2.6.0 
```
6. make sure it's reachable on port 5000
```console
$ curl -i http://localhost:5000/v2/
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Mon, 06 Mar 2017 16:20:49 GMT

{}
```
7. Now try to push the previously-tagged image
```console
$ docker push localhost:5000/alpine:3.5
The push refers to a repository [localhost:5000/alpine]

```

**Comment by BretFisher** [comment]
I can confirm this is still an issue on macOS with today's 17.03.0-ce-mac2 (15657) beta.

Seems to be confined to macOS, 17.03.0, and Swarm Services.

Note a workaround is if you replace `localhost` in `tag` and `push` with `127.0.0.1`. I noticed @jpetazzo [swapped these in the workshop repo](https://github.com/jpetazzo/orchestration-workshop/commit/44f40179927ad2e56f056d76123b79246b1e0be0), so maybe he has some more t/s info.

Tried it with `docker run` and without swarm init on macOS and it *works* with localhost.

Tried it on Mint Linux with `17.03.0-ce` and swarm service and it *works* with localhost.

**Comment by hairyhenderson** [comment]
Ok, this workaround works:

```console
$ docker tag alpine:3.5 127.0.0.1:5000/library/alpine:3.5
$ docker push 127.0.0.1:5000/library/alpine:3.5
The push refers to a repository [127.0.0.1:5000/library/alpine]
23b9c7b43573: Pushed 
3.5: digest: sha256:d0a670140e7d73562b401819f88fb68edca8aed45f4d2f835edb294e4a7a152a size: 528
```

Thanks for the tip, @BretFisher!

I did neglect to mention that this worked fine when running the registry with `docker run` for me as well.

I've had `localhost` vs `127.0.0.1` issues recently in totally unrelated contexts, and sometimes IPv6 is the culprit... I'll keep digging into this, maybe there's something to it...

**Comment by djs55** [comment]
Thanks for your report.

I suspect you're right that it's a confusion between IPv6 and IPv4. The docker.log shows that the string `localhost:5000` is sent from the client to the docker engine. However inside the Moby VM if I use `curl` to connect to `localhost:5000` it connects to `::1` and hangs:
```
# curl -v http://localhost:5000
* Rebuilt URL to: http://localhost:5000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.52.1
> Accept: */*
> 
^C
```
while if I connect to `127.0.0.1` then it works:
```
 curl -v http://127.0.0.1:5000
* Rebuilt URL to: http://127.0.0.1:5000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Wed, 22 Mar 2017 16:27:54 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```
So I think this is a duplicate of https://github.com/docker/docker/issues/24379 -- service ports are published on IPv4 only.

I recommend sticking with your workaround until the engine issue is fixed. I'll move this ticket to the acknowledged state in the meantime.

Thanks again for your report and your interest in Docker for Mac!

**Comment by hairyhenderson** [comment]
This is still an issue in D4Mac `18.03.0-ce-rc1-mac54`:

```
Get http://localhost:5000/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by guillaumerose** [comment]
I can reproduce the behavior @djs55 mentioned on a Linux machine with docker 18.02.0-ce. It's an issue with upstream moby/moby. We can't do anything here in Docker for Mac, sorry.

**Comment by hairyhenderson** [comment]
Ok, thanks @guillaumerose - I'll follow moby/moby#24379 👍
