### ISSUE TITLE
"Insecure registries" setting from the preferences doesn't work

### ISSUE THREAD

**Issue by syedwasimali** [docker/for-mac#1400]
### Expected behavior
By adding exceptions in the Docker/Preferences/Daemon/Insecure registries, and restarting docker, push to an insecure registry should be allowed.

### Actual behavior

doesn't work. I experience the following error: 

$ docker push 192.168.99.100:5000/mongo:3.2.10
The push refers to a repository [192.168.99.100:5000/mongo]
Get https://192.168.99.100:5000/v1/_ping: http: server gave HTTP response to HTTPS client

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/AFF365F3-E0BE-4813-9F93-1A53533E12AF/20170306-195922.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. try to push the 'tag'ged image to the private repository running in the VM started thru docker-machine.
$ docker push 192.168.99.100:5000/mongo:3.2.10
The push refers to a repository [192.168.99.100:5000/mongo]
Get https://192.168.99.100:5000/v1/_ping: http: server gave HTTP response to HTTPS client

  2. From the Docker pull-down menu, go to Docker/Preferences/Daemon/Insecure registries and add "192.168.99.100:5000" to the 'Insecure registries' list.

  3. Press "Apply & Restart"

  4. After Docker has restarted, try to repeat step 1. above.

  5. The same error is reproduced.

Tested this "Insecure Registries" feature on CentOS 7.3 running Docker version 1.12.5 by manual edit of /etc/docker/daemon.json and it works.

**Comment by MagnusS** [comment]
Thanks for the report @syedwasimali. Unfortunately I'm unable to find the diagnostic data you uploaded - could you please upload them again using "Diagnose & Upload"?

The error message sounds like you may be using HTTPS to contact an HTTP server, could that be the problem?

**Comment by MagnusS** [comment]
Sorry - I was a bit quick to respond. I guess the HTTPS/HTTP issue is indeed the problem :-) Please let me know when the diagnostic data has been uploaded and I'll take a look at the logs. Thanks!

**Comment by LongLiveCHIEF** [comment]
related to #1348

**Comment by avsm** [comment]
I've filed an internal issue to reconfirm the manual tests for insecure registries are functional (and also to fix the related https://github.com/docker/for-mac/issues/1477 to this functionality).  This bug has been idle for 21 days and so we cannot make further progress without more information aside from manual testing of the base functionality.  Please feel free to reopen if this is not the case!
