### ISSUE TITLE
Fatal error at start

### ISSUE THREAD

**Issue by Guillaume-Mayer** [docker/for-mac#1402]
### Expected behavior
 
Should open at startup without problem

### Actual behavior

Fatal error at start

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/7884BDE5-202C-419A-8105-9300A454DC11/20170307-104104.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/guillaumemayer/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/guillaumemayer/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/guillaumemayer/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/guillaumemayer/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/guillaumemayer/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Push the power button
  2. Wait a little, push it again

7884BDE5-202C-419A-8105-9300A454DC11

**Comment by MagnusS** [comment]
@Guillaume-Mayer Thanks for the report. Do you have the error message that was shown on startup as well?

**Comment by Guillaume-Mayer** [comment]
Yes, on startup, I restarted, docker did its upgrade and it's working fine now

**Comment by MagnusS** [comment]
I'll close the issue as it is resolved, but we will look into what may have caused it. Thanks for the update.
