### ISSUE TITLE
D3B50AEC-EBF8-47D6-B1F9-15D9F97B1634

### ISSUE THREAD

**Issue by santhosh288** [docker/for-mac#1403]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by MagnusS** [comment]
I'm closing this issue as it is incomplete. Please include information about what went wrong, what was expected and (if possible) a way to reproduce the issue. Thanks
