### ISSUE TITLE
taskgated complains about com.docker.frontend processes, they quickly die and are restarted every 10 seconds

### ISSUE THREAD

**Issue by beamso** [docker/for-mac#141]
### Expected behavior

No complaints in /var/log/system.log about:

`<time> taskgated[279]: no application identifier provided, can't use provisioning profiles [pid=<pid>]`

from the process, with arguments:

`/Applications/Docker.app/Contents/Resources/bin/com.docker.frontend {"action":"vmstateevent","args":{"vmstate":"running"}}`

### Actual behavior

Plenty of complaints in /var/log/system.log about it. Two instances of the com.docker.frontend process are created by the Docker application.  They quickly die, and then new replacement processes are created.

Performing a Factory Reset appears to have no effect on the issue.

Nothing is logged by the com.docker.frontend processes or the Docker process in either /var/log/system.log or any of the logs in ~/Library/Containers/com.docker.docker/data/com.docker.driver.amd64-linux/log/ .

### Information

Diagnostic ID: DCED1E65-BC6E-4B21-8927-B89CAA5C6C3A
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start docker.
2. Eventually the logs start appearing.

**Comment by dsheets** [comment]
We're working on fixing this. Thanks for your report!

**Comment by dave-tucker** [comment]
Closing as this was fixed in Beta 22 and 1.12.1 stable
