### ISSUE TITLE
update prompt steals input focus

### ISSUE THREAD

**Issue by RubyTuesdayDONO** [docker/for-mac#1412]
### Expected behavior

Users are unobtrusively notified that updates are available, with macOS notifications (preferred) or a bouncing dock icon (okay, but somewhat annoying).

### Actual behavior

Docker for Mac "randomly" displays an "update available" dialog that steals input focus. If the user were in the middle of typing paragraphs, the Enter key could unintentionally initiate an update (maybe I don't want to do it now, or at all), besides being generally annoying by stealing input focus and forcing me to re-type everything between the popup's onset and me noticing the theft.

### Information

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.3 (build: 16D32)
Diagnostic ID: 3708E098-8A4A-42DB-8B4B-4761AD3C10D4

### Steps to reproduce the behavior

  1. Install Docker for Mac and start the service.
  2. Go about your business, using other programs — especially those involving textual input.
  3. When Docker detects that an update is available, it will pop-up a dialog into the foreground, stealing input focus.

**Comment by MagnusS** [comment]
Thank you for the feedback @RubyTuesdayDONO. I've added your suggestions to our internal ticket tracking updater improvements, so I'm closing this issue for now.
