### ISSUE TITLE
Docker fails to run after install

### ISSUE THREAD

**Issue by ElaWeinsberg** [docker/for-mac#1413]
### Expected behavior
Starting docker

### Actual behavior
com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/54BCEE5D-C254-434E-AC34-C39E84A64F1C/20170309-143612.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ela/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ela/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ela/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ela/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/ela/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ela/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Open docker
  2. Crashing...

**Comment by imajus** [comment]
Same here. I've uploaded logs, Diagnostic ID is `B57C5789-D662-4FB8-8856-7D6B561F028C`.

**Comment by xicubed** [comment]
I get this too...

**Comment by xicubed** [comment]
I disabled SIP, rebooted, everything worked. I've had to do this before as my user directory is on an external drive. Seems to interfere.

**Comment by djs55** [comment]
@xicubed that's very interesting information, thanks.

@ElaWeinsberg looking at the diagnostics I see the error
```
2017-03-09 14:35:44-08 ... Docker[com.docker.osxfs][16154] \
    <Error>: Fatal unexpected exception: Unix.Unix_error(Unix.EACCES, "stat", \
    "/Users/.../Library/Containers/com.docker.docker/Data")
```
The directory `$HOME/Library/Containers/com.docker.docker/Data` is where Docker for Mac tries to put all of its configuration and files. Could you check the user and group ownership of that directory? For reference mine is owned by my login user id, with group "staff". If it's set incorrectly, could you try something like
```
chown -R username ~/Library/Containers/com.docker.docker/Data
chgrp -R staff ~/Library/Containers/com.docker.docker/Data
```
and try again?

This is similar to a few other reports where a system directory is missing or has the wrong permissions. I'm not sure what the root cause(s) are.

Thanks for your report and for using Docker for Mac!

**Comment by xicubed** [comment]
Mines set to:

`drwxr-xr-x   24 myusername  MYDOMAIN\Domain Users `

with "myusername (Me)" having read and write and "MYDOMAIN\Domain Users" and "everyone" read only.

I was thinking the SIP disable was needed from an earlier problem I was having... see my last note in issue #720

**Comment by avsm** [comment]
I've filed an internal bug to improve the diagnostics tracking of incorrect usernames.

@ElaWeinsberg are you still having this issue? If you could try

```
chown -R username ~/Library/Containers/com.docker.docker/Data
chgrp -R staff ~/Library/Containers/com.docker.docker/Data
```

and see if you can start, that would be much appreciated.

**Comment by ElaWeinsberg** [comment]
@avsm, @djs55  This didn't resolve it, however it looks like my ~/Library got corrupted.
I re-installed docker on another machine (same configuration) and I don't have this issue, thanks for looking into that.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
