### ISSUE TITLE
8012A960-35C6-47D1-95C7-EDFBFC3D3BFA

### ISSUE THREAD

**Issue by glyqi2015** [docker/for-mac#1414]

**Comment by MagnusS** [comment]
This issue has been identified as being incomplete. Please see [this document](https://docs.docker.com/docker-for-mac/troubleshoot) for instructions on how to open a well formatted issue. Please be sure to include your Diagnostic ID as well as any reproduction steps, including Dockerfiles or docker-compose.yml if necessary.
