### ISSUE TITLE
Docker daemon crash on osx sierra

### ISSUE THREAD

**Issue by harshakhegde** [docker/for-mac#1416]
### Information

Diagnostic ID: DCFECEBB-CDFF-42EE-BACF-7F9BC43D7925
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.3 (Build 16D32)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by MagnusS** [comment]
Thanks for the report. This issue is incomplete and unfortunately I can't locate the diagnostic ID on our server. Please open a new issue which also includes a description of the issue, your Diagnostic ID (after Diagnose & Upload) as well as any reproduction step (including Dockerfiles or docker-compose.yml if necessary). Thanks!

**Comment by MagnusS** [comment]
Sorry, I may have closed this issue too quickly. From the version numbers in the issue it looks like you are running macOS Sierra which is only supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Upgrading to the latest stable or beta release (currently 17.03.0-ce-mac2) should solve the issue.

Was this a version you downloaded recently?

**Comment by harshakhegde** [comment]
The docker version that was crashing I got it from cask. Now i downloaded from the docker site in installed and it works. Version is 17.03.0-ce-mac2. Thanks for looking into this
