### ISSUE TITLE
Docker4Mac can't handle simultaneous TCP connections

### ISSUE THREAD

**Issue by rreinurm** [docker/for-mac#1417]
I tried different solutions to overcome parallel TCP connections issue. But previous solutions haven't had any effect so I suspect issue might be something different.

I have tried to increase maximum number of connections with moderate change from 1200 until to 10000. Also tried out increasing kernel parametrs
```
$ sysctl kern.maxfiles
kern.maxfiles: 524288
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 64000
```
 
### Expected behavior
I should see all requests are succesful

### Actual behavior
```
curclu:r l(:5 6(c5)u6 r)Rl e:c Rcue(rcvl5v c6 :u)frf a laiRi(:lel5 uuc6(rvr)e 5:e6 f C)aoR:i ne nRcleeCvuccort evni :nfofenac ait Ciiorllonueursrneeene:t:   crC tboeiCyso nenot pn eenrbceetrsi
neoeytnc  tpb iyroe eenpsre e
etrr e
bsye tp ebeyr
peceru
rl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peceurr
l: (56) Recv failure: Connection reset by peer
```

### Information
**12CB4B63-7AE2-4F86-B681-92F8B6B77436**
```
Docker for Mac: version: 17.03.0-ce-mac2 (32de84251)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/12CB4B63-7AE2-4F86-B681-92F8B6B77436/20170310-140854.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
Summary: start an apache container serving up a file. Run multiple curl instances in parallel. Note all of the networking errors.

```
dd if=/dev/zero of=zero.txt bs=1000 count=1
docker run -dit -p 8888:80 --name apache -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
for i in {1..100}; do curl -s -S -0 --no-keepalive "http://127.0.0.1:8888/zero.txt?[1-100]" > /dev/null & done; wait
```
Note all of the (possibly-interleaved) errors printed out by curl.

**Comment by djs55** [comment]
Thanks for the report and the reproduction steps. If I understand the test code correctly it spawns 100 instances of the `curl`, each of which performs 100 TCP connections in series. I ran the test on my host and see the same failures as you. I don't see any signs of hitting the network connection limit on the host -- when this happens it is clearly logged.

When I run the same test in the moby VM via a root shell it works perfectly. This is interesting because it includes the docker userspace proxy but cuts out the hyperkit/virtio-vsock transport. I suspect the hyperkit/virtio-vsock transport is unable to cope with the connection rate. I'll escalate this ticket to our hypervisor team.

**Comment by rreinurm** [comment]
Thanx for confirming it @djs55, I did similar tests inside moby VM and had same experience.

**Comment by avsm** [comment]
We're still investigating how to fix the virtio-vsock transport to eliminate this restriction. The bug is still active.

**Comment by thejosh00** [comment]
Just wanted to chime in that I believe this defect is affecting us at my job. We have a development environment that involves running all of our components in docker containers using docker for mac. 

For some workloads that involve a large number of simultaneous connections we will start  getting tons of "Connection reset by peer" errors. If I go back to using boot2docker the problem disappears.
