### ISSUE TITLE
DNS issue 17.03.0

### ISSUE THREAD

**Issue by ragboy** [docker/for-mac#1418]
### Expected behavior
Docker build and push normally work just fine.
### Actual behavior
Right after update, I noticed that I could not pull from my local repository during docker build. So I went in to daemon advanced, and I added this to make sure my internal DNS servers were prioritized first.

`{
  "dns" : [
    "10.0.2.10",
    "10.0.2.11",
    "8.8.8.8",
    "8.8.4.4"
  ],
  "experimental" : false,
  "dns-search" : [
    "bighead.net"
  ]
}`

This resolved the pull issue, but when I tagged the new image, to then push to the repo, it times out. The docker client is not using the right DNS. All of this worked fine in 1.13.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by matthewbarr** [comment]
You may find issue #1397 similar.

**Comment by djs55** [comment]
May also be covered by https://github.com/docker/for-mac/issues/988 -- the `docker` CLI uses a different DNS to the engine (at the moment).

Could you confirm that using an IP address directly makes it work?

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
