### ISSUE TITLE
..

### ISSUE THREAD

**Issue by adilrehan** [docker/for-mac#1419]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
I'm closing this issue because it doesn't contain any information.  @adilrehan, if you have a  problem to report, could you please include a description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
