### ISSUE TITLE
Unable to find prior docker for mac versions.

### ISSUE THREAD

**Issue by phoefgen** [docker/for-mac#1421]
### Expected behavior
Because of issue #1397, I am unable to interact with remote docker servers from my local workstation. I should be able to roll back docker for mac to a prior version when  a new version breaks my workflows.

### Actual behavior
Previous stable versions are/have been removed from view. The only alternate install is docker toolbox. 

It's currently only possible to download docker for mac 17.03.0-ce-mac2, I need to install docker for mac 1.13.1 until https://github.com/docker/for-mac/issues/1397 is resolved. 

### Information
This page does not have docker downloads: https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac

### Steps to reproduce the behavior

Try to download docker for mac 1.13.1

**Comment by yallop** [comment]
Thanks for the report, @phoefgen.  We're tracking this request internally, and we already have a similar public issue open: https://github.com/docker/for-mac/issues/1120.  I'm closing this as a duplicate, and recommend subscribing to #1120 to receive updates.
