### ISSUE TITLE
Docker on MAC crashed

### ISSUE THREAD

**Issue by rdoraiswamy** [docker/for-mac#1423]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
I'm closing this issue because it doesn't contain enough information for us to investigate.  @rdoraiswamy, could you please open a new issue with a description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?
