### ISSUE TITLE
docker-for-mac becomes unresponsive to docker commands and running services hang

### ISSUE THREAD

**Issue by paul-callahan** [docker/for-mac#1425]
### Expected behavior

all containers and docker commands work normally

### Actual behavior

all containers and docker commands hang.

### Information

Log file:  [20170312-181936.tar.gz](https://github.com/docker/for-mac/files/837079/20170312-181936.tar.gz)
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/D7144C6A-5AFF-4D79-A0E7-6DD56699B37F/20170312-181936.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

I was running an I/O intensive container with a volume mounted from the host, compiling clojure code.   About 6 other containers were running including 2 databases that had volumes mounted from the host.   All were launched via docker-compose.

At some point, the docker-compose logging output for all the containers just stopped.   All docker commands (ps, exec, etc) would just hang.   Containers that were acting as servers stopped responding on their exposed ports.

This happens about 2-3 times a week of heavy usage in a development environment.

Also looks like this time docker-for-mac isn't restarting.   Just sitting there with the animated whale for 20 minutes.

**Comment by paul-callahan** [comment]
[20170312-181936.tar.gz](https://github.com/docker/for-mac/files/837081/20170312-181936.tar.gz)

**Comment by djs55** [comment]
There's quite a lot of network-related log spam which is annoying, but this doesn't explain everything freezing.
```
Docker[com.docker.slirp][488] <Notice>: 127.0.0.1:0: caught read: Eof writing request, attempting to reconnect
Docker[com.docker.slirp][488] <Notice>: 127.0.0.1:0 0031: disconnect: failing request for question input-rest. <A|IN>
Docker[com.docker.slirp][488] <Error>: Socket.UDPv4.write udp:192.168.74.100:19322: caught network is unreachable returning Eof
...
 Docker[com.docker.slirp][81813] <Error>: Socket.UDPv4.write udp:192.168.99.101:19322: caught unknown uv error returning Eof
```
I notice the in-VM diagnostics .tar is empty which is usually a sign that the VM is very unhappy. There's nothing interesting on the VM console unfortunately. Unfortunately there are no logs from the VM.

It's a bit of a long shot but I've seen the VM freeze before after the laptop was sleeping for a while. Do you know if these events are correlated with the laptop going to sleep? In the case I saw, the in-VM diagnostics were empty but I left the machine for 30 minutes and it seemed to have recovered, and a second attempt to get the diagnostics succeeded.

**Comment by daveisfera** [comment]
At least once a week mine locks up like this as well. Here's the ID: 960549A5-E20C-4E41-B51B-FA16000C14C6

**Comment by avsm** [comment]
@daveisfera I've looked at your diagnostic logs and it definitely appears to be the osxfs issue in https://github.com/docker/pinata/issues/5908. That issue is still open, and this is appears to be more network-related.

**Comment by dsheets** [comment]
I don't see any recent evidence of docker/pinata#5908 (publicly tracked by @daveisfera's previous #1265). I believe #1265 has been re-opened and so any further information you can provide there to help us in reproducing the issue would be very appreciated.

**Comment by eatdrinksleepcode** [comment]
Also seeing the same behavior after waking, docker-cli becomes unresponsive and running containers stop responding.

Diagnostic ID: 81067891-8389-44D3-AD2E-1E76C4BC58F8

**Comment by ebriney** [comment]
Thanks for your @eatdrinksleepcode, it is still under investigation

**Comment by daveisfera** [comment]
91BA0B97-2185-40E4-8CF7-F4C94774E732

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by eatdrinksleepcode** [comment]
@jasonbivins more info _was_ given; the ```status/0-more-info-needed``` label should have been removed but wasn't. the issue seems to have been abandoned by the team.

**Comment by grimwinoleader** [comment]
Same problem here.
