### ISSUE TITLE
Docker App crash on startup

### ISSUE THREAD

**Issue by ubege** [docker/for-mac#1427]
### Expected behavior
Docker to start.

### Actual behavior
Docker app crashes on startup

### Information
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/F6A6143E-5760-4B92-90D9-4C13666BF50C/20170313-131113.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/uris/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/uris/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/uris/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/uris/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/uris/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/uris/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Upgrading docker didn't help.

**Comment by ydelgadom** [comment]
I am experiencing the same problem in macOS 10.11.5.   Both Docker stable and Docker edge apps  crash on start up and produce the same diagnostic.

**Comment by ubege** [comment]
I managed to get docker working. "Uninstall" / Reinstall (with the uninstall BASH script and using AppCleaner) had no effect. However:
- Installed the Beta version. It asks if it can "reset everything"
- Installed the stable version. It asks if it can "reset" everything - and i guess that did the trick. 
I lost all the VMs but at least docker is working.
