### ISSUE TITLE
docker-compose fails to execute, even the --version option

### ISSUE THREAD

**Issue by davejcowen** [docker/for-mac#1428]
### Expected behavior
Build using docker-compose
### Actual behavior
docker-compose fails every command even the --version option.
### Information
~/composetest @ renegade-15 (dcowen) 
| => docker --version
Docker version 17.03.0-ce, build 60ccb22
________________________________________________________________________________
| ~/composetest @ renegade-15 (dcowen) 
| => docker-machine --version
docker-machine version 0.10.0, build 76ed2a6
________________________________________________________________________________
| ~/composetest @ renegade-15 (dcowen) 
| => docker-compose --version
Traceback (most recent call last):
  File "docker-compose", line 2, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-build-MW5H3j/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "compose/cli/__init__.py", line 16, in <module>
  File "subprocess.py", line 711, in __init__
  File "subprocess.py", line 1343, in _execute_child
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Failed to execute script docker-compose
________________________________________________________________________________
| ~/composetest @ renegade-15 (dcowen) 
| => 

Even sudo docker-compose --version fails
Running on macOS Sierra Version 10.12.3

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...  docker-compose --version
  2. ...

**Comment by ekiwok** [comment]
Does it work for you with the internet connection turned off?

It looks similar to the issue I've just reported: #1435

**Comment by davejcowen** [comment]
No, same error with or without wifi.  The most basic --version command won't work.

**Comment by djs55** [comment]
Could there be a clash between the `docker-compose` installed via Docker for Mac and another copy on the system? Does something like
```
$ pip uninstall docker
$ pip uninstall docker-py
```
make any difference?

**Comment by chbuck** [comment]
same problem having only one version installed via Docker

**Comment by davejcowen** [comment]
No change.  I didn't use Python to install it and don't have pip installed.  I used the docker engine macOS installer.

**Comment by GWeisenfeld** [comment]
I also have exactly the same issue. I completely uninstalled docker using the apps uninstall, then re installed and i'm still getting the same issue. same docker and docker-machine versions as op.

**Comment by davejcowen** [comment]
No, I've done all the same steps and still can't get compose to working.

**Comment by djs55** [comment]
Since it seems to be a `docker-compose`-specific error I've created the ticket [docker/compose#4663]. I'll set this ticket to acknowledged in the meantime. Thanks for your report!

**Comment by avsm** [comment]
There is a fix for this in docker-compose 1.12.0-rc2.  We are now bundling that into a Docker for Mac release and will let you know when an update ships.

**Comment by davejcowen** [comment]
Fantastic, thanks and look forward to availability.

**Comment by piotr-galas** [comment]
@avsm but hot to install docker-compose  1.12.0-rc2?  on mac?

**Comment by carvilsi** [comment]
Hi @piotr-galas 
Go to this url: https://github.com/docker/compose/releases
And execute the commands that they expose there:

```
curl -L https://github.com/docker/compose/releases/download/1.14.0-rc2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
``` 
Good luck!

**Comment by nehalv** [comment]
Thanks for the update. I was facing a similar issue with 'docker for mac'. The 1.14.0-rc2 version fixed the issue.
