### ISSUE TITLE
Run Docker in Mac Pro 2008

### ISSUE THREAD

**Issue by adepolas** [docker/for-mac#1429]
### Expected behavior
Run Docker

### Actual behavior
Having error : 
> Incompatible CPU detected.

Docker requires a processor with virtualization capabilities.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

> Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
> macOS: version 10.11.6 (build: 15G1010)
> logs: /tmp/526F2FA1-D925-45BD-9594-06C39E83AB24/20170314-120910.tar.gz
> failure: sysctl -a reports no hypervisor support
> [ERROR]  vmnetd
>          /var/tmp/com.docker.vmnetd.socket does not exist
>          Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
>          /private/tmp/vmnetd/com.docker.vmnetd is not running
> [OK]     dns
> [ERROR]  driver.amd64-linux
>          com.docker.driver.amd64-linux -db is not running
> [OK]     virtualization VT-X
> [OK]     app
> [ERROR]  moby
>          /Users/adeline/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
> [OK]     system
> [OK]     moby-syslog
> [ERROR]  db
>          /Users/adeline/Library/Containers/com.docker.docker/Data/s40 does not exist
>          Unexpected error (No such file or directory) connecting to /Users/adeline/Library/Containers/com.docker.docker/Data/s40
>          com.docker.db is not running
> [OK]     env
> [ERROR]  virtualization kern.hv_support
>          sysctl -a reports no hypervisor support
> [ERROR]  slirp
>          Unexpected error ((Failure
>   "Error connecting socket to 9p endpoint unix:/Users/adeline/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/adeline/Library/Containers/com.docker.docker/Data/s51
>          com.docker.slirp is not running
>          slirp check failed with: (Failure
>   "Error connecting socket to 9p endpoint unix:/Users/adeline/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
> [ERROR]  osxfs
>          com.docker.osxfs is not running
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          cannot find docker
>          docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
> [OK]     menubar
> [ERROR]  disk
>          Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. Open Docker under Mac Pro (2008)

**Comment by dimaspivak** [comment]
From the Important Notes on the [Install page](https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac): "Docker for Mac requires OS X El Capitan 10.11 or newer macOS release running on a 2010 or newer Mac, with Intel’s hardware support for MMU virtualization."

I don't think this can be fixed. Sorry.

**Comment by barat** [comment]
You can try toolbox, but I'm not sure if it uses 32bit or 64bit OS in virtualbox:
https://docs.docker.com/toolbox/overview/

If it is 64bit then still no go - vtx is required for 64bit guests.

**Comment by djs55** [comment]
Unfortunately the other comments are correct -- Docker for Mac requires hardware with virtualisation support (specifically VT-x). I also recommend giving toolbox a try -- I believe virtualbox and vmware fusion both predate hardware virtualisation support and may be able to run a VM in software.

Thanks for your support and interest in Docker for Mac, sorry it didn't work for you.

**Comment by GmanBB** [comment]
It ran for me, when I install Linux Ubuntu server on mac pro 2008. Linux has native support for Docker and then CPU is not a problem anymore. Enjoy!
