### ISSUE TITLE
Using Curl or SDK cannot get token via /auth or pull private image

### ISSUE THREAD

**Issue by ericvn** [docker/for-mac#1431]
### Expected behavior

I am using two curl commands (tried first with GO SDK but that failed in the same way so using curl for reproducibility) to do an `/auth`. I can pull an image `/create?fromImage` from DockerHub if I use the `X-REGISTRY-AUTH` with the BASE64-ENCODED

{
  "username": "string",
  "password": "string",
  "email": "string",
  "serveraddress": "string"
}

I cannot use this second `curl` to pull an image from the IBM Container Registry/

### Actual behavior

The curl, `/auth` returns `LoginSucceeded` but no `IdentityToken`. I would expect the IdentityToken to be populated.
The curl, `create?fromImage`, succeeds for DockerHub but not for the IBM Container registry service. I would expect this to work for both registries (since the `/auth` succeeds.

### Information

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/E77976A2-D502-46D8-AD9F-F30C0A4E42EA/20170314-091858.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

- Have a private registry to host some docker images. I used my DockerHub and an IBM Container Service on Bluemix registry.

DockerHub
- Do a curl `/auth/ to login using user which has access to private repository
`curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -d '{"username": "<user>", "password": "<password>", "serveraddress": "https://index.docker.io/v1/"}'   -X POST http:/1.26/auth`
returns `{"IdentityToken":"","Status":"Login Succeeded"}`

- Do a curl to pull image
`curl -i --unix-socket /var/run/docker.sock -X POST "http:/v1.26/images/create?fromImage=<private_image>" -H "X-REGISTRY-AUTH: <base64_encoded_full_struct>"`
works.

IBM Container Service

`curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -d '{"username": <name>, "password": <password>, "serveraddress": "registry.ng.bluemix.net"}'   -X POST http:/1.26/auth`

returns `{"IdentityToken":"","Status":"Login Succeeded"}`

curl -i --unix-socket /var/run/docker.sock -X POST "http:/v1.26/images/create?fromImage=registry.ng.bluemix.net/<namespace>/<image>" -H "X-REGISTRY-AUTH: <base64_encoded_full_struct>"

returns:

`{"status":"Pulling repository registry.ng.bluemix.net/<namespace>/<image>error":"Error: image <namespace>/<image> not found"}`

I create the BASE64 encoding using the same json as in the -d for the `/auth` curls.

I do see the same behavior on a Linux VSI with Docker 17.03 installed.

**Comment by ericvn** [comment]
Maybe from https://github.com/docker/docker/issues/26000 this is expected and the private registry should not contain the `IdentityToken`?

**Comment by ericvn** [comment]
Additionally, I have tried this against the IBM container registry in Bluemix.

In this case, the first `curl` behaves similarly and I get back `{"IdentityToken":"","Status":"Login Succeeded"}`

However I am unsuccessful getting the second `curl` to work trying to pass in the full json with user/pass/server on the X-REGISTRY-AUTH:
```{"status":"Pulling repository registry.ng.bluemix.net/<namespace>/<image>"}
{"errorDetail":{"message":"Error: image <namespace>/<image> not found"},"error":"Error: image <namespace>/<image> not found"}```

So I am able to workaround the issue with DockerHub by simply having the auth on the pull, I cannot do the same for the IBM Registry (although the auth says successful with the same json).

**Comment by djs55** [comment]
Thanks for your report. I think if you see the same issue on Linux with 17.03 then it's at least not specific to the Mac version of Docker. I'm not familiar enough with the registry protocol to know whether the bug is in the Docker engine client or the Bluemix registry server. WDYT @thaJeztah?

**Comment by thaJeztah** [comment]
Hm, no, really the expert on this one; perhaps @estesp is able to tell more for the blue mix settings, otherwise I can try to get someone from the "distribution" team

**Comment by avsm** [comment]
@thaJeztah someone from the distribution team would be helpful. This does not seem to be a Mac-specific issue and I'm not familiar enough with the registry code to be helpful I think.

**Comment by estesp** [comment]
I'm not an expert on any special auth for the IBM private container registry service; but I can see that when using the `bx cr login` command for the Bluemix container registry plugin, it sets a long **bearer token** in `~/.docker/config.json` under the `auths` entry for the Bluemix private registry server. I assume that in your `curl` case, that bearer token is not part of the registry HTTP interaction, and why your second curl against the Bluemix registry doesn't work as you aren't "authed" to your private namespace?

Apologize if I misunderstood and you are getting that bearer token from some output of the first curl and using it and still having a failure.

**Comment by avsm** [comment]
Thanks very much for the clarification @estesp.

@ericvn I've looked at the logs again to verify that this isn't a Docker for Mac specific bug.  If the comments above are not sufficient, you may want to open up a Bluemix support query at https://console.ng.bluemix.net/docs/support/index.html#getting-customer-support

If you are noticing that this only happens on Docker for Mac, then please do feel free to reopen this ticket.

**Comment by erwinverdonk** [comment]
I have the same experience as the author of this post. This is indeed not a Docker for Mac issue. It appear you do not get a IdentityToken, which is not what one would expect. Instead, what does work, you have to pass the whole auth JSON block as 'X-REGISTRY-AUTH' header with every Docker API call.
