### ISSUE TITLE
Cant configure docker daemon through json on MacOS

### ISSUE THREAD

**Issue by rawjeev** [docker/for-mac#1443]
### Expected behavior
Docker should restart successfully and listen on a TCP port as well as unix socket.

### Actual behavior
**Docker fails to start after changing JSON**

### Information
- Diagnostic ID: F4504B5F-38B8-4561-8EDE-0C94CAFAED00

- Docker Community Edition
- Version 17.03.0-ce-mac2 (15654)
-  Channel: stable
- macOS Sierra 10.12.3 (16D32)

### Steps to reproduce the behavior

1. Navigate to *Preference > Daemon > Advanced*
2. Add the following JSON
<code>
{
"hosts":["0.0.0.0:2375","unix:///var/run/docker.sock"]
}
</code>   
      
3. Click **Apply & Restart** button

**Comment by djs55** [comment]
Thanks for your report.

I believe this is very similar to https://github.com/docker/for-mac/issues/1156 and has already been escalated to the engineering team. I'll resolve this ticket as a duplicate.

To work around a problem with the `.json` file, see https://github.com/docker/for-mac/issues/1156#issuecomment-273539868

If you would like to expose your docker daemon over TCP, see https://github.com/docker/for-mac/issues/1156#issuecomment-273764881
