### ISSUE TITLE
[ERROR]  docker-cli          /var/run/docker.sock does not exist

### ISSUE THREAD

**Issue by henfee** [docker/for-mac#1445]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/D3E621CF-236C-4F01-9D2B-F8BBBDF5F367/20170320-105439.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by djs55** [comment]
Thanks for your report.

I notice this error in the logs:
```
com.docker.vmnetd[1324]: Path /Volumes/BenHome/Library/Containers/com.docker.docker/Data is owned by uid 99, but we're talking to uid 501
```
-- could you check the owner/group of your home directory? Ideally it would be owned by the same user id as your logged in user.

**Comment by avsm** [comment]
Hi @henfee, have you had a chance to check the ownership of your home directory? You can open up Terminal and run `ls -la /Users` and paste the output here.

**Comment by avsm** [comment]
I've filed an internal bug report to add more checks to the ownership of directories.  I'll go ahead and close this out now as we do not have enough new information to determine the precise cause of the bug, but @henfee please reopen if you get a chance to answer the question above.  Thanks again for the original bug report and logs!
