### ISSUE TITLE
Where can i download an older version ?

### ISSUE THREAD

**Issue by morriswinkler-simple** [docker/for-mac#1448]
One of my containers started to behave differently, I would like to install an earlier release Docker for Mac 1.13.1, 2017-02-09 (stable). Tried to find a download for that, couldn't find it, why don't you use the release tab from GitHub for this.

**Comment by djs55** [comment]
Thanks for your report.

We don't currently have an index of previous versions, however it is possible to download the appcast XML used by the auto-update to download and cache previous versions yourself -- see this comment https://github.com/docker/for-mac/issues/1053#issuecomment-268124918

The previous stable is https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg 

This is related to docker/for-mac#1053

I've escalated this as a request for a general mechanism to download previous versions and included your suggestions about github releases.

If you find bugs in the stable version, please do report them separately on other tickets. Thanks!

**Comment by avsm** [comment]
Regarding:
> One of my containers started to behave differently

Is there any particular different behaviour that we can help diagnose, that is causing you difficulty?

**Comment by thisisthekap** [comment]
The ability to download previous versions would be very helpful. E.g. I experienced https://github.com/Microsoft/mssql-docker/issues/235 where my intermediate workaround is just a downgrade. So I had to figure out where to get a previous version from.

So a previous versions download page would help us to update Docker more frequently, because we would not have to be scared of broken setups that much (cause we can easily revert them).

**Comment by akimd** [comment]
The download links are in the release notes.
- https://docs.docker.com/docker-for-mac/release-notes/
- https://docs.docker.com/docker-for-mac/edge-release-notes/
- https://docs.docker.com/docker-for-windows/release-notes/
- https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by hussainakram** [comment]
Here is also good list for old versions: 

- https://gist.github.com/franklinyu/5e0bb9d6c0d873f33c78415dd2ea4138
