### ISSUE TITLE
Docker for Mac crashes at startup

### ISSUE THREAD

**Issue by rdoraiswamy** [docker/for-mac#1450]
### Expected behavior
Normal startup of Docker
### Actual behavior
I get the attached error.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...Normal boot of Mac
  2. ...

## Error message
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.10.5 (build: 14F2109)
logs: /tmp/613BDC9F-E999-4D1B-8FD1-F816C734E3C8/20170320-105800.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/*****/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/*****/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rdoraiswamy/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/*****/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/****/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by djs55** [comment]
Thanks for your report.

The logs show this:
```
2017-03-20 09:01:30-07 ... Docker[com.docker.osx.hyperkit.linux][408] <Notice>: Acquired task manager lock
2017-03-20 09:01:30-07 ... Docker[com.docker.osx.hyperkit.linux][408] <Notice>: Maximum number of file descriptors is 10240
2017-03-20 09:01:30-07 ... Docker[com.docker.osx.hyperkit.linux][408] <Notice>: Removing leaked pidfile com.docker.driver.amd64-linux
2017-03-20 09:01:30-07 ... Docker[com.docker.osx.hyperkit.linux][408] <Notice>: Removing leaked pidfile com.docker.hyperkit
2017-03-20 09:01:30-07 ... Docker[com.docker.osx.hyperkit.linux][408] <Notice>: Signal terminated to com.docker.osxfs (pid 408)
2017-03-20 09:01:30-07 ... Docker[com.docker.docker][383] <Notice>: HyperkitLinux: Notified of termination of com.docker.osx.hyperkit.linux
2017-03-20 09:01:30-07 ... Docker[com.docker.docker][383] <Critical>: Terminator: com.docker.osx.hyperkit.linux failed to start
        Exit code 15
```
-- when the app restarts it tries to clean up some leaked processes using pid files. Unfortunately the pid has been re-used by the app itself and so it self-destructs. I think this is the same as https://github.com/docker/for-mac/issues/1256 and has already been escalated to the hypervisor team.

Could you check whether the leaked pidfile has been removed: `~/Library/Containers/com.docker.docker/Data/tasks/com.docker.hyperkit`? Provided it's gone then the app should start up safely.

Thanks for your report and your interest in Docker for Mac!

**Comment by rdoraiswamy** [comment]
Thanks Dave. I ended up upgrading to macOS Sierra on my Mac. Also I shut docker down, deleted the ~/Library/Containers/com.docker.docker/Data/tasks/com.docker.hyperkit file and restarted Docker and this error seems to be gone.

Much appreciate your help.
