### ISSUE TITLE
docker for mac open failed

### ISSUE THREAD

**Issue by quaker1** [docker/for-mac#1452]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Please upload diagnostics from the Whale menu -> Diagnose & Feedback... -> Diagnose & Upload.

If the UI doesn't appear then try running `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u` and copy the text into a fresh ticket.

Thanks for your interest in Docker for Mac!
