### ISSUE TITLE
ERRO[4334] error getting events from daemon: EOF

### ISSUE THREAD

**Issue by BenjiKCF** [docker/for-mac#1454]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

Hello everyone, after following the google codelabs, [Codelabs](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#3) I have received an error  `ERRO[4334] error getting events from daemon: EOF`  after `Creating bottleneck at /tf_files/bottlenecks/roses/13231224664_4af5293a37.jpg.txt` 

Update:
I reran it and this shows up
`ERRO[53469] error getting events from daemon: EOF `

**Steps to reproduce the issue:**
1.
```
 python tensorflow/examples/image_retraining/retrain.py \
> --bottleneck_dir=/tf_files/bottlenecks \
> --how_many_training_steps 500 \
> --model_dir=/tf_files/inception \
> --output_graph=/tf_files/retrained_graph.pb \
> --output_labels=/tf_files/retrained_labels.txt \
> --image_dir /tf_files/flower_photos

```

**Describe the results you received:**
`ERRO[4334] error getting events from daemon: EOF`

**Describe the results you expected:**
`Finish the retraining`

**Output of `docker version`:**

`Docker version 1.13.1, build 092cba3`

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: UNXQ:IPAT:2ZHG:3443:M7XI:M3FW:W7Q7:G4HV:IKKW:W5TU:72TI:SH3G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-02-21T14:43:50.071749826Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS X with python 2.7, 
and this shows up
`W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Thank you so much`

**Comment by djs55** [comment]
It looks from your report that there's a bug in the code labs / tensorflow software you're using. The error "ERRO[53469] error getting events from daemon: EOF" doesn't come from Docker. I recommend reporting this somewhere related to tensorflow as I don't think anyone here understands tensorflow enough to help you.

Sorry I couldn't be much help -- good luck with the lab.

**Comment by BenjiKCF** [comment]
Thank you djs55, I will try to update my solution when I fix it.

**Comment by BenjiKCF** [comment]
By increasing the number of CPU and ram, the error didn't occur.
