### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by jamesm-kudos** [docker/for-mac#1457]
### Expected behavior

Should be able to run docker commands

### Actual behavior

# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Information

9D524069-3453-4EC4-B564-4872DC3EC6B6

there is no /var/run/docker.sock, logs show nothing

### Steps to reproduce the behavior

  1. install and run docker
  2. run docker ps

**Comment by djs55** [comment]
This looks similar to #1413 -- something is unexpected with the file permissions:
```
2017-03-22 19:22:27-06 ... Docker[com.docker.vmnetd][33280] <Notice>: Client supplied container path /Users/.../Library/Containers/com.docker.docker/Data
2017-03-22 19:22:27-06 ... Docker[com.docker.vmnetd][33280] <Critical>: Path /Users/.../Library/Containers/com.docker.docker/Data is owned by uid 99, but we're talking to uid 502
```

Could you check the owner/group information of the path `$HOME/Library/Containers/com.docker.docker/Data`? Assuming your userid is `502`, could you `chown` the `Data` directory to `502` and then restart Docker for Mac?

I'm not sure what causes this. Could you describe your setup a little? Are you in a corporate environment, attached to a domain? Is your home directory on some network share or other external storage device?

**Comment by jamesm-kudos** [comment]
My home directory is an external device, but all permissions look good.  The log says that the Data dir is owned by uid 99, but it's not.  What command is being used to expose the permissions of that dir?

Also not sure how my home directory permissions would affect /var/run/docker.sock...?

**Comment by jamesm-kudos** [comment]
Update:  

found this line in the log:

Docker is not responding: Get http://./info: dial unix /Users/.../Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused: waiting 0.5s

so I set my DOCKER_HOST to:

DOCKER_HOST="unix:///Users/.../Library/Containers/com.docker.docker/Data/*00000003.00000948"

and so far the first few docker commands seem to be working.

**Comment by djs55** [comment]
The code creates creates a symlink from `/var/run/docker.sock` to the Unix domain socket in `$HOME/Library/Containers/com.docker.docker/Data/` which forwards to the docker engine. It checks the owner of the target directory as a sanity-check before creating the symlink. To determine the owner it uses `stat(2)` on the `Data` directory and reads the `st_uid` field.

I'm not sure what's going on. Could you post the output of `stat -r $HOME/Library/Containers/com.docker.docker/Data`? On my laptop uid `99` is user `_unknown`. I wonder if the volume mount has some kind of userid remap.

**Comment by jamesm-kudos** [comment]
stat -r Data/
16777225 1469827 040755 24 502 20 0 816 1490287640 1490284714 1490284714 1490232134 4096 0 0 Data/

**Comment by djs55** [comment]
Thanks, that does indeed look fine. The `stat` is actually running in a privileged helper process -- it's possible that `stat` returns a different value in that context. I'll try to reproduce with a USB stick and will get back to you.

**Comment by jamesm-kudos** [comment]
running as root:

stat -r Data/
16777225 1469827 040755 24 99 99 0 816 1490287640 1490284714 1490284714 1490232134 4096 0 0 Data/

I did not expect that...

**Comment by djs55** [comment]
A colleague of mine pointed me at this: http://apple.stackexchange.com/questions/92226/mac-external-drive-file-rights -- it looks like file ownership on external volumes often does look different to `root` versus other users. The comment at the bottom suggests that Finder -> control+Click -> Get Info might offer a useful option:

> If it's in Mac OS X Extended format (or a variant), expand the Sharing & Permissions section of the info window, and see if it has an "Ignore ownership and permissions" option at the very bottom. If it's there and enabled, click the padlock and authenticate as an administrator, then disable the "Ignore..." option.

Let me know if that makes any difference.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by invertigo** [comment]
I have this exact problem.  Attached a screenshot of the Get Info window requested.  It doesn't appear to be the case that "ignore ownership and permissions" is enabled.
<img width="349" alt="screen shot 2017-05-02 at 15 03 38" src="https://cloud.githubusercontent.com/assets/389982/25641358/8ca751b0-2f48-11e7-9163-ec3ab8eaf595.png">

**Comment by invertigo** [comment]
Just to confirm details for the ticket, when I run "docker ps" I get this:

$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Running "stat" on the Data dir as root vs as myself gives the same results as above.

**Comment by yitam** [comment]
@dsheets please reopen this issue as I also encounter the same error message when running `docker ps` (as myself or as root): `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

FYI, I'm running El Cap with docker-17.05.0 installed via Brew

**Comment by dsheets** [comment]
@invertigo @yitam please open new tickets with a description of the problem you are experiencing and diagnostic ID from :whale: ➡️ `Diagnose and Feedback...` ➡️ `Diagnose & Upload`. It's very hard for us to keep track of multiple users' issues that have the same symptoms but possibly different causes in a closed issue. You may be experiencing exactly this issue (feel free to reference #1457) but it's much easier if we can help you individually.

Thanks!

**Comment by yitam** [comment]
Thanks @dsheets 
What I'm trying to do is to install docker using Brew in a travis CI Mac OS build environment. Any documentation you can point me to is much appreciated. Thanks.
