### ISSUE TITLE
Docker for Mac violates semantic versioning

### ISSUE THREAD

**Issue by bbaassssiiee** [docker/for-mac#1459]
Docker created an ecosystem. OpenShift is just an example of a product using Docker.

Semantic Versioning (http://semver.org) helps integrating different pieces from different places: 

In the world of software management there exists a dread place called “dependency hell.” The bigger your system grows and the more packages you integrate into your software, the more likely you are to find yourself, one day, in this pit of despair.

Expected behavior
OpenShift cluster starts in Docker Mac

Actual behavior
Error: Minor number must not contain leading zeroes "03"

Information

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/CB007BB5-67E7-44BB-B46E-49C5BEAAEFC7/20170323-124805.tar.gz
[OK] vmnetd
[OK] dns
[OK] driver.amd64-linux
[OK] virtualization VT-X
[OK] app
[OK] moby
[OK] system
[OK] moby-syslog
[OK] db
[OK] env
[OK] virtualization kern.hv_support
[OK] slirp
[OK] osxfs
[OK] moby-console
[OK] logs
[OK] docker-cli
[OK] menubar
[OK] disk

Steps to reproduce the behavior

Install Docker mac 17.03.0-ce-mac2
sudo gem install rhc
rhc setup
oc cluser up

**Comment by justincormack** [comment]
This is not a Docker for Mac issue, we use the version numbers of the upstream product.

The command line and so the release version is not the stable API, the REST API is, and there is a proposal to move to semver for that here https://github.com/docker/docker/issues/31842 please comment if that would be helpful to you.
