### ISSUE TITLE
Docker unresponsive after starting large compose file

### ISSUE THREAD

**Issue by edwinv** [docker/for-mac#146]
### Expected behavior

I'm starting a large compose file with 8 services defined. This starts just fine in our Linux environment.

### Actual behavior

`docker-compose up` crashes with 8 comparable error messages:

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/edwin/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```

After this, `docker ps` is unresponsive.

### Information

Diagnostic ID: 8E8C4890-46AA-422E-BE8F-A4D414BBDB7E
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Compose file contains a lot of private information and references to our private Docker images, therefore no easy way to reproduce this.

**Comment by edwinv** [comment]
Restart of Docker daemon via the Docker menu `restart` button also failed. Factory reset solved the issue.

**Comment by mchiang0610** [comment]
Seems like it's related to #119 given your diagnostic report errors. 

Would love to receive a sanitized version of what you are trying to run if possible or just verbally getting it on GitHub on what your stack looks like.

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in 8E8C4890-46AA-422E-BE8F-A4D414BBDB7E/20160805-153804.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-08-05T13:21:11.319817071Z" level=debug msg="Using default logging driver json-file"
time="2016-08-05T13:21:11.320474492Z" level=debug msg="Golang's threads limit set to 13950"
time="2016-08-05T13:21:11.321150482Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-08-05T13:21:11.325124481Z" level=debug msg="Using graph driver aufs"
time="2016-08-05T13:21:11.680798456Z" level=debug msg="Failed to load mount 2fe619b40535004556ee686c1456500d136bfd05b3056b519cb1d686aef1797f: invalid mount id value"
time="2016-08-05T13:21:11.682601492Z" level=debug msg="Failed to load mount 70563bf3061af07307d4b50f6df53b5ff38a8e5d5b59ca59506a1808f4805213: invalid mount id value"
time="2016-08-05T13:21:11.683215365Z" level=debug msg="Failed to load mount 97c18bb0cd3a904c8fcb0feecb9ff6570382839e5d89a21028a93ce6e25f284f: invalid mount id value"
time="2016-08-05T13:21:11.684775648Z" level=debug msg="Failed to load mount f80d08dcdd0e9e23d6d9d162db74073ac679d8ca52e9db0813071e6af0daad06: invalid mount id value"
```
