### ISSUE TITLE
No value for $DOCKER_HOST

### ISSUE THREAD

**Issue by benjaminapetersen** [docker/for-mac#1460]
I was expecting that `echo $DOCKER_HOST` would give me the IP address for my running docker containers so I could figure out how to access them via a browser. This variable is empty.  When I was previously running docker by other means, I would get a value.  Is this expected behavior?

Thanks!

**Comment by benjaminapetersen** [comment]
Btw, I suspect it should just be `localhost` or `0.0.0.0` as I can see my containers here.  I'm just not sure if it **should** have a value, or if it is intentionally empty.

**Comment by djs55** [comment]
It's intentionally empty. When you install `docker` on Linux, the CLI uses the local engine via a default Unix domain socket `/var/run/docker.sock` and ports are exposed on local interfaces.

We wanted Docker for Mac to behave as much like native Linux as possible, so the docker CLI connects to `/var/run/docker.sock` and ports are also exposed on the host so 
- `-p 127.0.0.1:80:80` means expose on localhost only
- `-p 80:80` means expose on `0.0.0.0` on the host (i.e. all interfaces)

This is different to (but hopefully simpler than) using toolbox on the Mac which uses Virtualbox/VMware fusion to run a helper VM and which doesn't relay from `/var/run/docker.sock` and doesn't bind ports on the host and which therefore requires `DOCKER_HOST` to point at the IP address of the VM.

I hope this answers your question and adequately explains the rationale. I'll close this ticket but feel free to ask more questions or ask for more clarification. Thank you for your interest in Docker for Mac!

**Comment by benjaminapetersen** [comment]
Sounds good, thanks for the explanation!
