### ISSUE TITLE
After latest update docker doesn't start on Mac version 10.11.3 (build: 15D21)

### ISSUE THREAD

**Issue by BadNews87** [docker/for-mac#1462]
### Expected behavior

Docker should start

### Actual behavior

Fatal Error

com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.11.3 (build: 15D21)
logs: /tmp/519B4622-F58D-49F3-951B-56531BBF8D07/20170324-103652.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/user/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/user/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/user/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/user/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/user/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/user/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start Mac OS docker client

**Comment by djs55** [comment]
Looking at the logs:
```
2017-03-24 10:35:13+01 ... Docker[com.docker.driver.amd64-linux][71250] <Notice>: com.docker.hyperkit: [ERROR] Found two references to cluster 91595: 6620.36608 and 6620.36352
2017-03-24 10:35:13+01 ... Docker[com.docker.driver.amd64-linux][71250] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure "Found two references to cluster 91595: 6620.36608 and 6620.36352")
2017-03-24 10:35:13+01 ... Docker[com.docker.driver.amd64-linux][71250] <Notice>: Mirage-block error: Block device is disconnected
```
Unfortunately this means that the `Docker.qcow2` file has become corrupted while running the previous version, and this was detected after upgrade. It's not safe to write to the file in this state :( The only workaround is to delete the file
```
rm -f ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
Unfortunately this means that your containers and images will need to be rebuilt.

The latest version has more sanity-checks in the qcow2 layer and so hopefully will be more reliable.

I'm sorry for the inconvenience this has caused. Thank you for your report and for using Docker for Mac!
