### ISSUE TITLE
OSX docker containers not being recognised.. but are being listed. but can't update or remove them

### ISSUE THREAD

**Issue by crislar** [docker/for-mac#1463]
### Expected behavior
stop - > remove container  

### Actual behavior
b7ae849839a2        mysql:5.7                                                                                          "docker-entrypoint..."   2 hours ago          Up 2 hours          3306/tcp               b7ae849839a2_wptest_db_1
Christians-MacBook-Pro:wp-test alternative$ docker update b7ae849839a2 --restart=no
Error response from daemon: Cannot update container b7ae849839a2111ac0f227a3effb7023f5face4cd90f8e3a8276e020f9f5666e: rpc error: code = 2 desc = containerd: container not found
Christians-MacBook-Pro:wp-test alternative$ docker rm b7ae849839a2_wptest_db_1
Error response from daemon: You cannot remove a running container b7ae849839a2111ac0f227a3effb7023f5face4cd90f8e3a8276e020f9f5666e. Stop the container before attempting removal or use -f
Christians-MacBook-Pro:wp-test alternative$ docker update b7ae849839a2_wptest_db_1 --restart=no
Error response from daemon: Cannot update container b7ae849839a2111ac0f227a3effb7023f5face4cd90f8e3a8276e020f9f5666e: rpc error: code = 2 desc = containerd: container not found
Christians-MacBook-Pro:wp-test alternative$ docker stop b7ae849839a2_wptest_db_1 --restart=no
unknown flag: --restart
See 'docker stop --help'.
Christians-MacBook-Pro:wp-test alternative$ docker stop b7ae849839a2_wptest_db_1
b7ae849839a2_wptest_db_1
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

This is happening on several containers. that are stopped. 

Some docker-compose yaml files have restart to yes. 
These are proving hard to remove. 

  1. ...
  2. ...

**Comment by avsm** [comment]
Thanks for filing the issue. Unfortunately, it's difficult to diagnose what your issue is without a diagnostic tarball upload.  The issue template has instructions for this ("Diagnose & Feedback" from the whale menu), which will create a fresh issue with the information we need.

I'll close this one for now, but please do feel free to open a new ticket with the diagnostic logs so that we can track down the problem. Thanks!
