### ISSUE TITLE
UDP NAT not working properly

### ISSUE THREAD

**Issue by jstoja** [docker/for-mac#1464]
### Expected behavior

When sending UDP packets from a docker container on Docker for mac, to an UDP server, the UDP packets should be received (most).

### Actual behavior

The server receives no packets.
Whereas the same tests outside of the container work perfectly.

### Information

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/D8FEE5E8-24D6-4440-AAB0-8B9246BD299D/20170324-163223.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run on a server/laptop on the same subnet a UDP server (`nc -u -l 4242`) (in our examples, the server ip is 192.168.0.2)
  2. On another server/laptop run the following: `docker run -it --rm appropriate/nc 192.168.0.2 4242`

I assume this is related to some UDP NAT issues with the hypervisor running the docker daemon.

**Comment by avsm** [comment]
Thanks for the report! I debugged this with @djs55 and were unable to reproduce it. We tried:

```
$ docker run -it appropriate/nc -u 172.16.13.205 4242
hello world
```

and confirmed it was received on another laptop. You can also just try installing `bind-tools` on Alpine and doing a `dig @8.8.8.8 docker.com` which also uses UDP.

Did you forget the `-u` to your netcat? That forces UDP.

**Comment by avsm** [comment]
@jstoja just wanted to ping you to find out if you are still having this issue. See above for our repro attempt.

**Comment by jstoja** [comment]
Hello @avsm !
I checked again to be sure and... it worked.
The only thing that changed is that now I use the 17.03.1-ce-mac4 (16021).
I tried with and without host networking and it seems all good.

I ask my friend if he can also reproduce, in the meantime I close since I cannot. Sorry if this was a real false alarm!

**Comment by avsm** [comment]
No problem, glad it's working ok for you now. If you run into any more issues, please do create a fresh bug report here for us to look at.
