### ISSUE TITLE
F9C6EB96-A5D3-4B11-99B0-832CE92E21FC

### ISSUE THREAD

**Issue by dodalovic** [docker/for-mac#1465]
### Actual behavior

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/F9C6EB96-A5D3-4B11-99B0-832CE92E21FC/20170324-174613.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/dusan.odalovic/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/dusan.odalovic/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/dusan.odalovic/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/dusan.odalovic/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/dusan.odalovic/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Just logged in, and saw this.

**Comment by avsm** [comment]
Thanks for the bug report!

I've looked through the logs and cannot spot any bad behaviour.  It looks like the application was exited, and the services all shut down cleanly.  Was there any unexpected behaviour from the application that led you to file this bug report?  Where did you see the logs above when you logged in?

**Comment by dodalovic** [comment]
@avsm I just logged in to my workstation and immediately got popup window stating that there was an issue starting docker (if I recall correctly). Then I ran diagnostics with results pasted here.

**Comment by avsm** [comment]
@dodalovic thanks -- if I happens again, another Diagnostic and Feedback report would be much appreciated. We've improved the logs gathering to get more information in the next release, and so hopefully we'll be able to track down the issue if it happens again. In the meanwhile, I hope a restart fixed the issue for you.  If not, please do feel free to reopen this issue.
