### ISSUE TITLE
3428FE91-D565-4202-B3CB-E4948C3B50E9

### ISSUE THREAD

**Issue by rodrigomilfont** [docker/for-mac#1467]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by avsm** [comment]
I can't find an actual bug report here, so closing it in the assumption that the bug was filed in error.  If there is a real problem, please do feel free to open up a new issue again!
