### ISSUE TITLE
Failt after last update 

### ISSUE THREAD

**Issue by Macbets** [docker/for-mac#147]
### Information

Diagnostic ID: 6EFEFD74-D2EA-41E8-A67D-0D5DC01ED044
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/daniilkivenko/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/daniilkivenko/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@Macbets Sorry about this. Are you still seeing the same issues with the latest beta or stable versions?  Please try resetting to factory defaults, and issues still arise, let us know! 

Thank you so much, and sorry for the issues.
