### ISSUE TITLE
Cannot run docker after reinstallation

### ISSUE THREAD

**Issue by tcorvazier** [docker/for-mac#1470]
### Expected behavior
Docker daemon should start. This happens since I had downloaded a newer version of docker, docker has been running ok on my mac el capitan for months. I had tried to uninstall docker before but would not help.

### Actual behavior
Fails with an error at start-up

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by avsm** [comment]
Apologies for the inconvenience. Unfortunately, without any logs we cannot diagnose the problem further.  If you are still running into it, please follow the instructions in the "Information" section of the report to create a fresh issue that has those included.

You just need to go to the "Diagnose & Feedback" menu in the whale menu and upload a report.

In the event that you cannot run the menu app at all, then the Terminal will also work: `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u` and then paste in the UUID that is output to a GitHub issue. Hopefully the menu should work most of the time though!

I hope we can help you track down the cause of this error, sorry again that you're running into a failure!
