### ISSUE TITLE
Crash at startup with error about vpnkit

### ISSUE THREAD

**Issue by mathieufrh** [docker/for-mac#1472]
### Expected behavior

Docker start.

### Actual behavior

Docker crash while starting.

### Information

This is the trace from the beta version but I got the same with the stable version.
I already try removing Docker.qcow2, fully installing and cleaning the app but every time I reinstall I got the same issue:

```
Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/16E0DE19-FD6B-4304-8117-E843C683CE29/20170327-214615.tar.gz
failure: vpnkit is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mathieu/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mathieu/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mathieu/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mathieu/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/mathieu/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mathieu/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Start docker

**Comment by avsm** [comment]
Thanks for the bug report! I've run some analysis on the logs you uploaded, and detected: a symptom of problem 'processor-not-supported' in 16E0DE19-FD6B-4304-8117-E843C683CE29/20170327-214615.

Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/install/#/what-to-know-before-you-install for more information.

The log in docker-system.log matches:
```

2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.driver.amd64-linux][6240] <Notice>: watcher.Add(/etc/resolver) failed: &os.PathError{Op:"lstat", Path:"/etc/resolver", Err:0x2}
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.driver.amd64-linux][6240] <Warning>: Failed to watch /etc/resolver: &os.PathError{Op:"lstat", Path:"/etc/resolver", Err:0x2}: if this is needed, create the directory and restart the app
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.driver.amd64-linux][6240] <Notice>: vmx_init: processor not supported by Hypervisor.framework
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.driver.amd64-linux][6240] <Notice>: Unable to create VM (-85377018)
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.driver.amd64-linux][6240] <Notice>: Hypervisor subprocess has shutdown
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.osx.hyperkit.linux][6234] <Notice>: Reap com.docker.driver.amd64-linux (pid 6240): exit status 0
2017-03-27 21:20:20+02 shllghst-iMac Docker[com.docker.osx.hyperkit.linux][6239] <Notice>: VM shutdown at 2017-03-27 21:20:20 +0200 CEST
```

However, the odd thing is that your macOS system kernel reports that the Hypervisor.framework is available (`kern.hv_support: 1`).  What revision of Mac are you running Docker for Mac on?

**Comment by mathieufrh** [comment]
Hello and thank you very much for your answer.
Sorry I should have add my Mac OS version. I'm on Sierra but I do not know the revision number since I'm not on the computer right now.
What is strange is that it used to work. I do not remember upgrading docker or anything and I'm 100% sure that I do not change my CPU.

**Comment by avsm** [comment]
Thanks for the followup.  If it used to work, then it definitely isn't a hardware compatibility issue. One other reason that `vmx_init` might fail is because you are running some other software that has taken the hardware lock, and so cannot interoperate.  Have you recently started running any software such as an Android development environment that might be using the same hardware resources that Docker for Mac also needs?

**Comment by mathieufrh** [comment]
Mhh... unfortunately, I never use such a software, I just start the system and run docker, without starting any particular application before.

**Comment by avsm** [comment]
Ok, it _might_ be an issue with the amount of memory being assigned to the application.  Rather than just guess though, we have improved our diagnostics and should have a hotfix in the next couple of days that will gather sufficient extra information for us to be able to pin down the issue.  I will update this when this happens, hopefully on Thursday.  Thanks for your patience!

**Comment by mathieufrh** [comment]
Thank you for your reply. Unfortunately I still have the same error. Tell me if I can give you more debugging information.

**Comment by Authorlove** [comment]
Run into the same problem with the same Mac OS
