### ISSUE TITLE
docker-credential-osxkeychain insatiably thirsts for all my secrets

### ISSUE THREAD

**Issue by glyph** [docker/for-mac#1473]
### Expected behavior

I run `docker` and it asks for, like, my https://hub.docker.com ID, or maybe some private registry passwords or something.

### Actual behavior

I run `docker` and I always get popups about it asking for random other passwords in my keychain, particularly those associated with https://www.omnigroup.com/omnifocus

I then have to dismiss this dialog once or twice per run:

![screen shot 2017-03-27 at 1 05 37 pm](https://cloud.githubusercontent.com/assets/716529/24376170/c91e3598-12ef-11e7-83d5-b8ad43831a5c.png)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu: F19EBFB4-AB68-426B-8828-AE7E54769B88

### Steps to reproduce the behavior

I'm not sure _exactly_ what reproduces this; on different machines it seems to prompt for a different set of secrets, and after being annoyed by this in a few places I have allowed access to them and am not sure how to turn access off so I can test again.  But making an OmniFocus sync account and then attempting to use `docker build` seems to reliably do the trick.

**Comment by cyli** [comment]
This is related to https://github.com/docker/docker/issues/31517, and should be fixed in the next update as per https://github.com/docker/docker/issues/31517#issuecomment-289400160.

**Comment by glyph** [comment]
Thanks! Should this just be closed as a duplicate?

**Comment by cyli** [comment]
Yep, probably more discussion should happen in the other issue, particularly if it still occurs in the next desktop release.  Thank you!  (I do not actually have permissions to close this issue, though :))

**Comment by glyph** [comment]
Just confirming: `docker build` happily succeeded without prompting me after I revoked access to all relevant secrets in Keychain Access; so this is definitely resolved.

**Comment by glyph** [comment]
(After the 17.03.1-ce-mac5 update.)
