### ISSUE TITLE
docker crashes when preferences is selected while preference window is in edit mode of insecure registries

### ISSUE THREAD

**Issue by schatt** [docker/for-mac#1477]
### Expected behavior
Should bring the preference window to the foreground.

### Actual behavior
Dialog pops up with "Fatal Error Segmentation violation exception"

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/D5617CDF-F769-44CA-951E-490C8AF2CAF4/20170327-212546.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
  - A reproducible case if this is a bug, Dockerfiles FTW
To reproduce, on Mac OS X 10.12.4 (not sure if OS version specific):
• go to the docker icon, select preferences.
• go to the daemon tab
• click the plus under add an insecure registry
• don't type anything, but don't exit the window or edit box
• Go to the docker icon in the menu bar, and select preferences again.
• observe crash dialog.

### Steps to reproduce the behavior

To reproduce, on Mac OS X 10.12.4 (not sure if OS version specific):
• go to the docker icon, select preferences.
• go to the daemon tab
• click the plus under add an insecure registry
• don't type anything, but don't exit the window or edit box
• Go to the docker icon in the menu bar, and select preferences again.
• observe crash dialog.

**Comment by avsm** [comment]
Thank you for reporting this bug, and for the detailed reproduction instructions.  I have confirmed this on build Version 17.03.1-ce-rc1-mac3 (15924) and filed an internal GUI issue.  We will update this ticket as soon as a fix is shipped on the Edge channel.
