### ISSUE TITLE
Crash on macos 10.12.4

### ISSUE THREAD

**Issue by vladislav-sidorovich** [docker/for-mac#1479]
### Information

 I updated my macos to the latest and get docker crash

### Steps to reproduce the behavior

  1. open docker
  2. crash

Info:
Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/7290904E-9D81-4A10-982E-D9D57DA57806/20170328-213938.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/vladislavsidorovich/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by avsm** [comment]
Thanks for the bug report. It looks like there is a crash in osxfs here:

```
Docker[com.apple.libsystem.libdispatch][26176] <Notice>: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Docker[com.docker.osxfs][26194] <Error>: Fatal unexpected exception: Failure("osxfs_control: eof reading header from socket")
```

Do you have any containers that are autostarting, or is the problem happening with no containers on a fresh startup of Docker for Mac?

**Comment by avsm** [comment]
This is unlikely to be a crash in osxfs, since those log entries are it shutting down in response to something else triggering the application shutdown.

**Comment by vladislav-sidorovich** [comment]
I didn't have any other containers. But I updated to 
`Version 17.03.1-ce-rc1-mac3 (15924)
Channel: edge
1795b358d5`
and actually all works fine

**Comment by dsheets** [comment]
Glad to hear that the problem seems to have disappeared. Thanks for your report!
