### ISSUE TITLE
Crash on startup with El Capitan 10.11.6

### ISSUE THREAD

**Issue by jeanphi6** [docker/for-mac#1481]
### Expected behavior
Docker start correctly.

### Actual behavior
Docker has an error on startup

### Information

  - Mac OS El Capitan 10.11.6
  - Docker Community Edition for Mac latest version

### Steps to reproduce the behavior

Launch Docker.app

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/E19FACD3-37EE-46E0-A825-5D9F36326B24/20170329-094531.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         Unexpected error (Socket operation on non-socket) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/JeanPhi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/JeanPhi/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/JeanPhi/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/JeanPhi/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/JeanPhi/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/JeanPhi/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

Diagnostic id : E19FACD3-37EE-46E0-A825-5D9F36326B24

No files like .docker in my files as i can see on other issues.

Thanks.

**Comment by avsm** [comment]
Thank you for the bug report.  We detected symptoms of the problem that your Mac's processor is not recent enough to run Docker For Mac, in the E19FACD3-37EE-46E0-A825-5D9F36326B24/20170329-094531 logs.

Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/install/#/what-to-know-before-you-install for more information.

The log in sysctl-a matches:
```
kern.hv_support: 0
```

**Comment by jeanphi6** [comment]
Thanks.
