### ISSUE TITLE
Notifications beep, interrupt me, and have no way to be disabled

### ISSUE THREAD

**Issue by katef** [docker/for-mac#1482]
### Actual behavior

Docker's mac app produces its own dialog boxes, which pop up and beep. That's really very annoying, and doesn't fit with the rest of the feel of macos.

### Expected behavior

Use MacOS's usual notification system instead. Then I can configure it to be quieter.

**Comment by avsm** [comment]
Thank you for the report, @katef!  To help me file a more specific bug report, are there any particular dialogs that are interrupting you in this fashion?  Are they happening from the background (e.g. the update dialog) or after you take some user action?

**Comment by jeanlaurent** [comment]
@katef is this the new version available dialog you're referring to ?

**Comment by katef** [comment]
From the background, yes - things that pop up with no cause from me.

The update dialog was one. There was another, but I was in the middle of typing something in another program, that appeared, took focus, and my typing dismissed it before I had chance to see what that was. Maybe it was the same thing?

**Comment by avsm** [comment]
Thank you for the clarification, @katef.  It is almost certainly the update dialog that popped up the second time. I have filed an internal issue requesting this enhancement with our GUI team -- when the code was first written in the macOS 10.9/10.10 days, the Mac notifications mechanism was not as sophisticated as it is today, so we did not make use of it.

I'll go ahead and close this issue now as there is not much point holding it open as we have an internal issue, but if you do notice any other dialogs that are troubling you, please feel free to file another one or reopen this issue with more details.

**Comment by katef** [comment]
Thanks
