### ISSUE TITLE
Docker for Mac installation failed

### ISSUE THREAD

**Issue by klee-broadsoft** [docker/for-mac#1484]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. following instruction https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install
  2. got error as in diagnostic id 6075F0ED-D1D1-4F85-9198-BFA4B0449C06

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.5 (build: 15F34)
logs: /tmp/6075F0ED-D1D1-4F85-9198-BFA4B0449C06/20170329-105308.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/klee/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/klee/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/klee/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/klee/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/klee/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/klee/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults

**Comment by klee-broadsoft** [comment]
Prior to diagnostic message shows

Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1

**Comment by klee-broadsoft** [comment]
I found a posting

"Whale menu" -> "Preferences..." -> "Reset" -> "Reset to factory defaults"
This worked for me but you need to be fast before the window above appears otherwise there is no way to open Preferences... #usability

This worked for me too after several trial to do it before Fatal window appears
There should be a way to "reset" on Fatal window...

**Comment by avsm** [comment]
Thanks for the bug report. I've filed a GUI enhancement request regarding improving the "move fast to reset" issue you noted. With regards to why it crashed, I have found a few things in your logs.

There is some evidence of block corruption:

```
Docker[com.docker.driver.amd64-linux][67963] <Notice>: com.docker.hyperkit: [ERROR] Found two references to cluster 34764: 76.33640 and 76.18632
Docker[com.docker.driver.amd64-linux][67963] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure "Found two references to cluster 34764: 76.33640 and 76.18632")
```

Did you do an upgrade of Docker for Mac recently before the app stopped working?

**Comment by avsm** [comment]
I'm going ahead and closing this issue as an instance of block corruption in https://github.com/docker/for-mac/issues/1159.  If you do have a reliable reproduction that isn't an upgrade, please do file an issue to let us know.

**Comment by klee-broadsoft** [comment]
Yes i think I may have tried upgrade by accepting "YES" on upgrade
suggestion by docker.
thanks

On Wednesday, March 29, 2017, Anil Madhavapeddy <notifications@github.com>
wrote:
> Thanks for the bug report. I've filed a GUI enhancement request regarding
improving the "move fast to reset" issue you noted. With regards to why it
crashed, I have found a few things in your logs.
>
> There is some evidence of block corruption:
>
> Docker[com.docker.driver.amd64-linux][67963] <Notice>:
com.docker.hyperkit: [ERROR] Found two references to cluster 34764:
76.33640 and 76.18632
> Docker[com.docker.driver.amd64-linux][67963] <Notice>:
com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Failure
"Found two references to cluster 34764: 76.33640 and 76.18632")
>
> Did you do an upgrade of Docker for Mac recently before the app stopped
working?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/sRTxag6fufaNYoca5pk9kMSGGN7UtdzRcoBaEcfF8k4qSsDceOgcrZ70bjacQwMN1CJEbFtvgENlm5tIJre6bXviryI8zCQvK_d7m98Xvw9VmmoBymrphPbbSS3hw55Kk93VHFubUE6d9TB9aGHATi6AeAZ2pQ=s0-d-e1-ft#https://github.com/notifications/beacon/AVua8XMjiatwTGwKJljjW8kb3KrJVhVjks5rquXUgaJpZM4MtWCh.gif>

-- 


This email is intended solely for the person or entity to which it is 
addressed and may contain confidential and/or privileged information. If 
you are not the intended recipient and have received this email in error, 
please notify BroadSoft, Inc. immediately by replying to this message, and 
destroy all copies of this message, along with any attachment, prior to 
reading, distributing or copying it.

Ce message confidentiel  et les éventuelles pièces jointes sont à l’usage 
exclusif de son ou de sa destinataire. Il est interdit, pour toute autre 
personne, de le distribuer, d’en dévoiler le contenu ou de le reproduire. 
Si vous avez reçu cette communication par erreur, veuillez en informer 
immédiatement l’expéditeur par courrier électronique et détruire l’original 
de ce message ainsi que toute copie.
