### ISSUE TITLE
How to install docker beta 32

### ISSUE THREAD

**Issue by etienneroudeix** [docker/for-mac#1488]
I need to run ```docker run --rm -it --privileged --pid=host walkerlee/nsenter -t 1 -m -u -i -n fstrim /var``` to lower my ```Docker.qcow2``` size.

But it returns me with ```fstrim: ioctl 0xc0185879 failed: Not supported```

I found out [here](https://www.reddit.com/r/docker/comments/5h6qen/shrink_your_virtual_hard_drive_file_in_docker_for/) that I have to use beta v32.

I cannot manage tu do it.

I actually run docker on channel edge :
<img width="620" alt="docker" src="https://cloud.githubusercontent.com/assets/2012682/24502021/472ddfa2-154c-11e7-8743-d29e887a0e42.png">

I can't find any dmg or any way to switch on beta channel.

**Comment by avsm** [comment]
@etienneroudeix Please find the instructions for doing this on 17.03.1-ce-rc1-mac3 over at https://github.com/docker/for-mac/issues/371#issuecomment-290408295

It will hopefully be unnecessary soon, but this should let it work for you on the current Edge release!

**Comment by etienneroudeix** [comment]
awesome thank you very much
