### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aungkozinoway** [docker/for-mac#1490]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by avsm** [comment]
Hi @aungkozinoway -- we do need to have the UUID of the logs given to you in the Diagnose and Feedback dialog, as well as a brief description of your problem before we can fix the bug.  Thanks very much, and of course feel free to reopen this issue with that information.
