### ISSUE TITLE
Upgrade to 17.03.1-ce-mac5 seems to cause hangs

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1493]
### Actual behavior
Upgrading to Version 17.03.1-ce-mac5 (16048) from previous version seems to have made my system unstable -- e.g. a docker build is hung at a "gcc", and this command is stuck at exit.
```
docker run -ti --rm --privileged debian:jessie df -h $*
```
Other than those two hung processes, docker seems  to be fine, e.g. it responds to "docker ps". I'm going to restart docker and see if the problems continue, but maybe there's something useful to you in the logs.

### Information

76F01000-B098-4F09-B140-3E70120D2248

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/76F01000-B098-4F09-B140-3E70120D2248/20170330-175620.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by avsm** [comment]
Thanks for the bug report. I'm looking at the logs and not seeing anything too unusual except for some soft lockups:

```
NMI watchdog: BUG: soft lockup - CPU#0 stuck for 523s! [kswapd0:162]
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 524s! [kswapd0:162]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 524s! [java:6141]
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 523s! [kswapd0:162]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 523s! [java:14268]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 268s! [java:20207]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 523s! [java:6127]
NMI watchdog: BUG: soft lockup - CPU#0 stuck for 524s! [khugepaged:33]
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 524s! [java:20604]
```

Were you running containers that were particularly CPU heavy or memory intensive?  You may just have been running out of memory inside the container. 

If you can reproduce the hang, try increasing the amount of memory and/or vCPUs in the preferences menu to see if it goes away.  I'll keep looking through the logs to see if I can spot anything else unusual.

**Comment by yallop** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
