### ISSUE TITLE
Fresh install of Docker crashes after sometime

### ISSUE THREAD

**Issue by tiferrei** [docker/for-mac#1495]
### Expected behavior
Not crash... Really haven't done anything yet, fresh install.
### Actual behavior
Crashes (something failed to start)
### Information

0394A251-2EF7-4A3A-A2B9-167E50C344F7

### Steps to reproduce the behavior

  1. Launch Docker
  2. Wait
  3. Crashes

**Comment by avsm** [comment]
Thanks for the bug report.  Did you see any dialogs pop up when the crash occurred?  I'm seeing this trace in your logs:

```
Docker[com.docker.driver.amd64-linux][56542] <Notice>: System wants to wake up
Docker[com.docker.driver.amd64-linux][56542] <Notice>: com.docker.hyperkit is already running so nothing to do
Docker[com.docker.slirp][56540] <Error>: dispatcher caught Caught EOF on underlying FLOW: no more responses will be handled
Docker[com.docker.slirp][56540] <Notice>: Sending disconnection to request with tag 1
Docker[com.docker.slirp][56540] <Notice>: transport layer has disconnected
Docker[com.docker.slirp][56540] <Notice>: attempting to reconnect to database
Docker[com.docker.driver.amd64-linux][56542] <Notice>: Error from config.Wait: EOF
Docker[com.docker.driver.amd64-linux][56542] <Notice>: I should reboot
Docker[com.docker.driver.amd64-linux][56542] <Notice>: Error from config.Wait: EOF
Docker[com.docker.driver.amd64-linux][56542] <Notice>: I should reboot
Docker[com.docker.driver.amd64-linux][56542] <Notice>: Error from config.Wait: EOF
Docker[com.docker.driver.amd64-linux][56542] <Notice>: I should reboot
Docker[com.docker.driver.amd64-linux][56542] <Notice>: virtio-9p: unexpected EOF reading -- did the 9P server crash?
Docker[com.docker.osx.hyperkit.linux][56541] <Notice>: Failed to watch for updates: EOF
```

@djs55 does this look like a slirp crash to you?  I'm continuing to hunt through the logs.

**Comment by djs55** [comment]
The `transport layer has disconnected` message means slirp's connection to `com.docker.db` has failed. Perhaps `com.docker.db` has crashed? I think slirp is still alive for the moment, but `com.docker.driver.amd64-linux` also lost the database connection (`config.Wait` reads the database) and it probably responds by rebooting the VM and killing slirp at that point. I suspect the root cause is `com.docker.db` going away.

**Comment by avsm** [comment]
I confirm this -- there are multiple other entries suggesting that database connections have failed on reconnection.

@tiferrei can you reliably reproduce this crash on every single start of the application?

**Comment by tiferrei** [comment]
@avsm Yes, and may I say it isn't only present on the latest version, I have also tried reinstalling (twice) and the same thing happens. I have not used docker at all yet (apart from running it initially) and the same thing happens. The bug should happen again anytime, I'll be sure to take a screenshot of the message. Meanwhile it is working, (almost) everything seems fine:
```
Error exec: plutil -extract appVersionHistory xml1 "/Users/tiferrei//Library/Group Containers/group.com.docker/Library/Preferences/group.com.docker.plist" -o -: exit 1
macOS: version 10.12.5 (build: 16F43c)
Docker.app: version: 17.03.1-ce-mac5 (b18e2a50c)
Local time: Fri Mar 31 15:45:51 BST 2017
UTC:        Fri Mar 31 14:45:51 UTC 2017
Timestamp:  20170331-154551
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      slirp
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/0394A251-2EF7-4A3A-A2B9-167E50C344F7/20170331-154551.tar.gz
Your unique id is: 0394A251-2EF7-4A3A-A2B9-167E50C344F7
Please quote this in all correspondence
```

**Comment by avsm** [comment]
Thanks for the clarification @tiferrei. We're about to ship a new hotfix version that preserves the database as well and help us narrow down the issue.

**Comment by gusjimenez** [comment]
I have the same issue in a fresh install, here is my log file, hope it helps.

![screen shot 2017-03-31 at 9 44 29 am](https://cloud.githubusercontent.com/assets/15126407/24560678/7fa490ea-15f8-11e7-82cd-0342e9964a55.png)

[20170331-094441.tar.gz](https://github.com/docker/for-mac/files/886411/20170331-094441.tar.gz)

Diagnosis:
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/BFE7978B-40A2-4B88-89DF-82D067D633FA/20170331-094441.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/gustavo.jimenez/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by tiferrei** [comment]
My error message is the same as @gusjimenez

**Comment by gusjimenez** [comment]
There is a work around about this problem.

NOTE: you should do steps 1 to 5 before the error occurs to be able to reset to factory defaults.
`Steps:

1.Run docker
2.Go to Preferences (Command+,)
3.Go to Reset Tab
4.Hit Reset to factory defaults
5.New window should appear, Hit "Reset Docker"
6.It may ask for password, provide password to reset.
7.Hit Restart button at the end if message "Docker has reset successfully. The application will restart now."
8.Start docker and continue the normal process to finish set up properly.
9.Then: Voilà
`
![screen shot 2017-04-06 at 4 36 42 pm](https://cloud.githubusercontent.com/assets/15126407/24779787/50d9322c-1ae7-11e7-8a27-e5316e1d251b.png)

**Comment by dsheets** [comment]
@tiferrei it sounds like you're no longer experiencing the issue. If you have any further problems with Docker for Mac, please don't hesitate to open a new issue. Thanks!

@gusjimenez I think you have experienced a different problem. Recent releases (beta 34.1 and 1.13 stable onwards) check the integrity of the `Docker.qcow2` file at startup and refuse to start if the file is corrupt.  The logs suggest that in this case the existing `Docker.qcow2` file has some damage, most likely caused by silent corruption in an earlier version due to inadequate locking when accessing the file.

As a workaround we recommend either uninstalling and reinstalling the application or `rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`, then restarting.

Unfortunately containers and images will need to be rebuilt.  I apologise for the inconvenience this has caused.

The issue docker/for-mac#1159 has more information.

**Comment by tiferrei** [comment]
@dsheets nothing changed. The issue is still here, it keeps crashing. Here's another: `0394A251-2EF7-4A3A-A2B9-167E50C344F7`
I was just waiting for that fix that @avsm mentioned:
>We're about to ship a new hotfix version that preserves the database as well and help us narrow down the issue.

**Comment by dsheets** [comment]
@tiferrei sorry about that. I'll take a look.

**Comment by ebriney** [comment]
@avsm do we have merged the changes on master?
@tiferrei the next stable version will be in june. Did you try the edge [version](https://download.docker.com/mac/edge/Docker.dmg)?

**Comment by tiferrei** [comment]
Haven't tried the edge version, will do, how long should I wait for the issue to potentially reoccur?

**Comment by tiferrei** [comment]
@ebriney Been running for a while and seems fine (6A457096-6184-4495-BA67-DBE16E8861FA).
Closing this one as the issue has been fixed. Will reopen if the problem reappears in the edge version.

**Comment by tiferrei** [comment]
@ebriney Nope, here we are again: `6A457096-6184-4495-BA67-DBE16E8861FA`

**Comment by tiferrei** [comment]
Still happening... `955917B0-94B0-4BFA-A0A6-668E2A6F196B`
