### ISSUE TITLE
Docker timeout starting/stopping containers after going to sleep

### ISSUE THREAD

**Issue by 0xCMP** [docker/for-mac#1496]
### Expected behavior
Docker Compose should be able to start new containers and stop it's existing containers

### Actual behavior
Docker Compose has timeouts (60s) trying to stop a container. Using the docker command does not make a difference. However I can do `docker ps` and it shows those containers are still running.

### Information

`70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

```
Docker for Mac: version: 17.03.1-ce-mac4 (f7a7acb1e)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170331-133934.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

Not positive, but here is my general idea

  1. Start Docker for Mac
  1. Launch a project using `docker-compose`
  1. Put mac to sleep overnight (hibernate?)
  1. Open the mac back up and try to use service
  1. Try to start any other docker-compose'd project (failure)
  1. Try to stop first project's docker-compose containers (failure)

**Comment by florrain** [comment]
Same, I can upload my diagnostic ID next time it occurs. I tried to run a SQL import overnight and docker was unresponsive after that. (same thing with native docker for mac or docker-machine and virtualbox)

**Comment by 0xCMP** [comment]
I haven't seen this in the later versions so I'll assume this is fixed
