### ISSUE TITLE
Crash on mac 10.11.6

### ISSUE THREAD

**Issue by jdenyc** [docker/for-mac#1498]
failure to start docker

### Information
Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 10.11.6 (build: 15G1502)
logs: /tmp/DD376A0B-AAE3-4937-8A8C-734F21567FFF/20170401-010445.tar.gz
failure: vpnkit is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jone/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/jone/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jone/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jone/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/jone/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jone/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         disk check failed with: (Failure
  "exec: \"/Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qcow-tool\" check \"/Users/jone/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2\" > /tmp/DD376A0B-AAE3-4937-8A8C-734F21567FFF/20170401-010445/qcow-tool-check.stdout 2> /tmp/DD376A0B-AAE3-4937-8A8C-734F21567FFF/20170401-010445/qcow-tool-check.stderr: exit 1")

**Comment by FutureSharks** [comment]
I have the same problem. The error message is `Fatal Error: com.docker.osx.hyperkit.linux failed to start. Exit code 1`

**Comment by sielay** [comment]
This helped https://github.com/docker/for-mac/issues/1198#issuecomment-274844146

**Comment by jdenyc** [comment]
so removing the Docker qcow image:
rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
and updating seemed to fix it

**Comment by FutureSharks** [comment]
This did NOT solve it for me. I still have the same problem after removing this file and Docker creates a new one on startup (and then fails to start)

**Comment by dsheets** [comment]
@FutureSharks please open a new issue with diagnostic ID from :whale: ➡️ `Diagnose and Feedback...` ➡️ `Diagnose & Upload`

**Comment by FutureSharks** [comment]
I think my issue is the same as https://github.com/docker/for-mac/issues/1508 so I'll watch that one. Thanks!
