### ISSUE TITLE
need information for run gui app

### ISSUE THREAD

**Issue by KiYugadgeter** [docker/for-mac#1500]
### Expected behavior
Run gui app on Docker for Mac

### Information
There is a way for do it in forum [How to run GUI apps in containiers in osx? (docker for mac) - Docker for Mac - Docker Forums](https://forums.docker.com/t/how-to-run-gui-apps-in-containiers-in-osx-docker-for-mac/17797/13).
I tried running GUI app running based on information in forum.
But it does not work correctly.
so would you mind providing documentation about it?

**Comment by jeanlaurent** [comment]
Hi @KiYugadgeter, Docker does not provide official documentation to run gui app in Docker for Mac at the moment.

I'll add a ticket to track that down, and could be a nice entry into the official [Docker for Mac FAQ](https://docs.docker.com/docker-for-mac/faqs/). 

Thanks.
