### ISSUE TITLE
Docker push timeouts

### ISSUE THREAD

**Issue by tachyon1337** [docker/for-mac#1501]
After installing the latest Sierra update, a docker push to my private repos on docker hub timeouts with the error:

`dial tcp: lookup auth.docker.io on 192.168.65.1:53: read udp 192.168.65.2:56033->192.168.65.1:53: i/o timeout`

### Expected behavior: 
`docker push <repo>/<image>:latest`

pushes the image to docker hub
 
### Actual behavior:

pushing layers < 100MB will upload and then rather than display "pushed status" will reset/retry. Layers > 100MB will stall. Eventually the command exits with the error message above. 

### Information
Build: 17.03.1-ce-mac5 (16048)
Diagnostic ID:  9EE99567-6F59-471B-A9E1-3D7F65D4125B

(b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/9EE99567-6F59-471B-A9E1-3D7F65D4125B/20170401-134024.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

 

### Additional Info

This issue has has been a minor annoyance since installing Docker for Mac. However, running the docker push command in succession(2 or 3 attempts) after failure would eventually push the image up. However, since installing the latest docker for mac build and the latest sierra update, I am no longer able to update my private images.

**Comment by jordan-wester** [comment]
Happening for me as well.  I was able to try multiple push attempts and eventually get my image uploaded to DockerHub but that hasn't worked since installing 17.03.1-ce.  I've tried the following:
- Disabling the proxy
- Setting the concurrent uploads to 2
- Adding `nameserver 8.8.8.8` to `/etc/resolv.conf`

Nothing seems to make a difference when doing a `docker push`

**Comment by jeanlaurent** [comment]
@tachyon1337 sounds like you're having DNS issues with your system, your tried to add a few but all seems more or less blocked.

Are you running through a proxy or vpn ?

**Comment by tachyon1337** [comment]
@jeanlaurent No, not running through a proxy or VPN. Nor do I have any DNS issues w/ my system. However, I did retry today  and was able to successfully push my images to docker hub.

**Comment by jeanlaurent** [comment]
Thanks.

I got that message on a flaky internet connection and trying to push a private image, could it be that your connection at that time, was even partially faulty ?

**Comment by tachyon1337** [comment]
@jeanlaurent 

No, not flaky. Upstream is only 1Mbps, which is not the fastest in the world. I do have a static IP, tho.

**Comment by benjefferies** [comment]
Also seeing this on a slow connection pushing to the public repo

**Comment by tecnobrat** [comment]
I wonder if this is related? https://github.com/docker/for-mac/issues/1554
