### ISSUE TITLE
Failed to start Docker for Mac after install

### ISSUE THREAD

**Issue by aaawtest** [docker/for-mac#1503]
C2F74579-7D24-47F0-8680-5A3721A6CC85

**Comment by jeanlaurent** [comment]
@aaawtest thanks for your report.

This seems to be datakit subprocess not starting on your system, for an unknown reason.

Did you upgrade from a previous version ?

**Comment by ebriney** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
