### ISSUE TITLE
Installed the latest stable docker tools, doesn't work now

### ISSUE THREAD

**Issue by andy-siemer-volusion** [docker/for-mac#1506]
### Expected behavior

Run docker tools at start up, docker runs

### Actual behavior
When starting docker tools from task bar...eventually get the below issue:

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/3E950FF1-21BE-4D10-B247-7AA25A49E7A7/20170403-145036.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/andy_siemer/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/andy_siemer/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy_siemer/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/andy_siemer/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/andy_siemer/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/andy_siemer/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. [cmd] [space]
  2. type docker
  3. latest docker tools app shows
  4. select docker tools
  5. icon shows in task bar
  6. starting
  7. fails with the exception data above

3E950FF1-21BE-4D10-B247-7AA25A49E7A7

**Comment by dsheets** [comment]
It looks like there is an issue with loading the disk image:

```
2017-04-03 14:41:09-05 * Docker[com.docker.driver.amd64-linux][10260] <Notice>: com.docker.hyperkit: [ERROR] Mirage block device raised exception: (Invalid_argument Interval.make)
2017-04-03 14:41:09-05 * Docker[com.docker.driver.amd64-linux][10260] <Notice>: Mirage-block error: Block device is disconnected
2017-04-03 14:41:09-05 * Docker[com.docker.driver.amd64-linux][10260] <Notice>: Could not open mirage-block device: Invalid argument
2017-04-03 14:41:09-05 * Docker[com.docker.driver.amd64-linux][10260] <Notice>: Could not open backing file: Invalid argument
```

The first occurrence of this is preceded by

```
2017-04-03 14:40:53-05 * CylanceSvc[user][72] <Alert>: Process:terminated path:/Applications/Docker.app/Contents/MacOS/qemu-img pid: violation:None occurences:1 SHA:
2017-04-03 14:40:57-05 * CylanceSvc[user][72] <Alert>: process Terminated by policy - path:/Applications/Docker.app/Contents/MacOS/qemu-img pid:10231 violation:StackPivot occurrences:1 SHA:E70F698B925A1D4F9E95C7F4E35200EEE3725FB8928E96AEE4D4619E0AF72CC4
2017-04-03 14:40:57-05 * CylanceUI[com.cylance.CylanceUI][1220] <Warning>: Processing {/Applications/Docker.app/Contents/MacOS/qemu-img102313}, state(p)=3
```

which looks like an anti-virus tool assassinating a process that was modifying the disk image. Had you just installed Docker for Mac? Did you upgrade? From what? Did you opt to migrate a Toolbox disk image? Any additional information you can provide about your environment would be helpful.

In the mean-time, you may be able to work-around this issue by removing `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` and restarting Docker for Mac. It may be the case that you either have to opt *not* to import a Toolbox disk image (if applicable) while running Cylance or turn off Cylance (maybe not possible). Thanks for using Docker for Mac.

**Comment by ebriney** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
