### ISSUE TITLE
Docker daemon won't start 

### ISSUE THREAD

**Issue by bluehallu** [docker/for-mac#1507]
### Expected behavior

The daemon starts and I can use docker.

### Actual behavior

The daemon gets stuck, the docker icon doesn't stop it's "in progress" animation and it says "docker is starting" forever. I need to reset to factory defaults to get a working docker environment.

### Information

Diagnostic ID C6246CE0-9B5C-40F9-9C72-9ADF996B6205

### Steps to reproduce the behavior

Install docker on a mac, use it for some days, watch it get stuck.

**Comment by dsheets** [comment]
Are you using swarm mode or Docker Cloud swarm features?

I see Docker errors in your logs like:

> Apr  4 11:09:59 moby root: time="2017-04-04T11:09:59.887083791Z" level=error msg="cluster exited with error: can't initialize raft node: rpc error: code = 2 desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = 14 desc = grpc: the connection is unavailable"
> Apr  4 11:09:59 moby root: time="2017-04-04T11:09:59.887153077Z" level=fatal msg="Error creating cluster component: swarm component could not be started: can't initialize raft node: rpc error: code = 2 desc = could not connect to prospective new cluster member using its advertised address: rpc error: code = 14 desc = grpc: the connection is unavailable"

**Comment by dsheets** [comment]
Any more information you can provide about your configuration and the features you are using would be helpful.

**Comment by bluehallu** [comment]
@dsheets I did try to join our office swarm at some point to test if the feature was now available with the latest release (can't find any documentation on its supported status). Nothing else out of the ordinary as far as I can tell

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
