### ISSUE TITLE
Docker crashes at startup

### ISSUE THREAD

**Issue by ZillaG** [docker/for-mac#1508]
### Expected behavior
Docker would load at startup

### Actual behavior
Docker crashes

### Information
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/EC488E15-65DB-4AFA-A01D-5B55C5A60BBF/20170404-084845.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/cf186025/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/cf186025/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/cf186025/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/cf186025/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/cf186025/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dsheets** [comment]
Thanks for your report.

The logs show this:
```
2017-04-04 08:48:28-04 ... Docker[com.docker.osx.hyperkit.linux][908] <Notice>: Acquired task manager lock
2017-04-04 08:48:28-04 ... Docker[com.docker.osx.hyperkit.linux][908] <Notice>: Maximum number of file descriptors is 10240
2017-04-04 08:48:28-04 ... Docker[com.docker.osx.hyperkit.linux][908] <Notice>: Removing leaked pidfile com.docker.driver.amd64-linux
2017-04-04 08:48:28-04 ... Docker[com.docker.osx.hyperkit.linux][908] <Notice>: Signal terminated to com.docker.hyperkit (pid 908)
2017-04-04 08:48:28-04 ... Docker[com.docker.docker][889] <Notice>: HyperkitLinux: Notified of termination of com.docker.osx.hyperkit.linux
2017-04-04 08:48:28-04 ... Docker[com.docker.docker][889] <Critical>: Terminator: com.docker.osx.hyperkit.linux failed to start
        Exit code 15
```

-- when the app restarts it tries to clean up some leaked processes using pid files. Unfortunately the pid has been re-used by the app itself and so it self-destructs. I think this is the same as #1256 and #1450 and has already been escalated to the hypervisor team. I will increase the priority of our fix.

Could you check whether the leaked pidfile has been removed: `~/Library/Containers/com.docker.docker/Data/tasks/com.docker.driver.amd64-linux`? Provided it's gone then the app should start up safely.

Thanks for your report and your interest in Docker for Mac!
