### ISSUE TITLE
Confusion when Moby runs out of disk space

### ISSUE THREAD

**Issue by mistyhacks** [docker/for-mac#1512]
### Expected behavior

I get some warning or pop-up when Moby is getting low on space

Bonus points for a GUI version of `docker system prune` that lets me see what is taking all the room and selectively remove things

### Actual behavior

I was happily building an image and I got the following error:

```
Step 52/52 : COPY . /go/src/github.com/docker/docker
Error processing tar file(exit status 1): write /go/src/github.com/docker/docker/.git/objects/pack/pack-90bae0bc9bbe5faf16ae4436bc8aeded83f7d3b5.pack: no space left on device
make: *** [build] Error 1
```

At first, I thought my actual system disk had filled up, and that was very surprising indeed. I had just moved to a new laptop and thought I might have messed something up with the restore process. But that wasn't the case.

I had no idea how to see how much disk space Moby had left, so I asked @thajeztah for help. He told me that in order to see this, I actually had to start a container and run `df -h` from within it. I was skeptical that a container would even start but it did:

```
docker run --rm busybox df -h
```

```
Filesystem                Size      Used Available Use% Mounted on
overlay                  62.7G     62.5G         0 100% /
tmpfs                   999.5M         0    999.5M   0% /dev
tmpfs                   999.5M         0    999.5M   0% /sys/fs/cgroup
/dev/sda1                62.7G     62.5G         0 100% /etc/resolv.conf
/dev/sda1                62.7G     62.5G         0 100% /etc/hostname
/dev/sda1                62.7G     62.5G         0 100% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   999.5M         0    999.5M   0% /proc/kcore
tmpfs                   999.5M         0    999.5M   0% /proc/timer_list
tmpfs                   999.5M         0    999.5M   0% /proc/sched_debug
tmpfs                   999.5M         0    999.5M   0% /sys/firmware
```

He then told me I needed to run `docker system prune`. I did and it removed 44GB worth of stuff. I have no idea what it removed, but he did say I would lose my build cache. I guess it's fine? 🤷‍♀️ I doubt that any "average user" without access to a Docker engineer would have been able to figure out what to do in this situation.

### Information

  - n/a

### Steps to reproduce the behavior

  1. Build a lot of huge images, I guess?
  2. ...

**Comment by jeanlaurent** [comment]
Thank you @mstanleyjones 

We opened a couple of tickets in the development repository to track your suggestion.

**Comment by thaJeztah** [comment]
For people arriving here, there's an issue in the public roadmap that's partially related; https://github.com/docker/roadmap/issues/13
