### ISSUE TITLE
Docker does not start on Mac after restart

### ISSUE THREAD

**Issue by artsf** [docker/for-mac#1514]
### Expected behavior
Starts after restart

### Actual behavior
Does not start

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Mac OS X 10.11.6

Docker:
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

go version go1.8 darwin/amd64

Log:
```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/2439AFEC-179A-4471-9766-DEEE420D4146/20170405-112410.tar.gz
failure: com.docker.osxfs is not running
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk
```

**Comment by jeanlaurent** [comment]
thanks @artsf  for your report.

That seems to be osxfs subprocess not coming back after restart.

I'll ping the revelant people and report back here.

**Comment by jeanlaurent** [comment]
After further review, we can make only guess to what happened. We suspect the hypervisor died, but we have no precise information so as why.

I opened a ticket in the development team to improve the logging of such scenario.

Thanks again for your report, and sorry I couln't be more precise.

**Comment by artsf** [comment]
Can I help anyhow with more logs or something?

**Comment by ebriney** [comment]
Do you still have the issue @artsf?

**Comment by artsf** [comment]
No, it resolved itself. I think it was related to me playing with plugins.
