### ISSUE TITLE
Old mac sometimes reacts this way

### ISSUE THREAD

**Issue by ldath** [docker/for-mac#1517]
### Expected behavior

Starting without error

### Actual behavior

Sometimes crashed when starting

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Diagnostic ID:
0C0D695C-5DE7-4980-88BE-8D0F136B9E40

### Steps to reproduce the behavior

  1. You need a old Mac 2011
  2. Work from battery

**Comment by jeanlaurent** [comment]
I don't find much in your logs.

The only merely suspicious thing, is that there seem to be a DNS change while you're not connected to the internet ?


Does that ring a bell ? Not sure I can dig more without some input on your side on what you were doing at that time ?

**Comment by ldath** [comment]
Is possible. System was just starting and my company have own DNS for
internall domain.

Is also possible that when mac starts and on the start list is to many
applications like chrome, Skype, Skype for Business it is just too slow.

If There is too less details please close this issue and when this will
occur again I'll try to send more like logs for example.

Kind Regards
Arkadiusz

06.04.2017 15:51 "Jean-Laurent de Morlhon" <notifications@github.com>
napisał(a):

**Comment by ebriney** [comment]
I close the issue for now. But if you have more informations feel free to re-open it @ldath.
