### ISSUE TITLE
Error opening Docker for Mac

### ISSUE THREAD

**Issue by firstpixel** [docker/for-mac#1518]
### Expected behavior
Open Docker
### Actual behavior
Error on diagnostic

### Information

Docker for Mac: version: 17.03.0-ce-mac2 (1d7d97bbb)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/0061F1A6-C4C9-4459-AEFA-EE22B3D833FB/20170406-102642.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/username/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/username/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/username/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/username/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/username/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/username/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/username/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/username/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
### Steps to reproduce the behavior

Run docker app

**Comment by jeanlaurent** [comment]
Hi @firstpixel, thanks for your report.

Looks like your your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/install/#/what-to-know-before-you-install for more information

At least that's what I find in the logs. On which hardware are you trying to run Docker for Mac ?

**Comment by Chewbone** [comment]
I'm having the same problem running Docker.  I'm running it on a Mac Pro (MacPro4,1) with Quad-Core Intel Xeon (E5520).  OSX 10.11.6.  My debugging report also complains about no hypervisor support, but it has no problem running virtual machines using VMWare Fusion or Virtualbox.

**Comment by balrajsingh** [comment]
@Chewbone: The Apple Hypervisor.framework requires additional hardware support that VMWare Fusion or Virtualbox don't yet require.  See the 'systems requirements' section of https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install which says, the `Mac must be a 2010 or newer model, with Intel’s hardware support for memory management unit (MMU) virtualization; i.e., Extended Page Tables (EPT) and Unrestricted Mode`.  

I think the E5520 does not have the required `Unrestricted Guest Mode.`  

I'm going to close this issue now, but please feel free to reopen if needed.
