### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by allenyang79** [docker/for-mac#152]
### Information

Diagnostic ID: 2F9CBE9C-3EE5-4EC7-9B5B-49F671D17050
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/macuser/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/2F9CBE9C-3EE5-4EC7-9B5B-49F671D17050/20160806-151209/qemu-img-check.stdout 2> /tmp/2F9CBE9C-3EE5-4EC7-9B5B-49F671D17050/20160806-151209/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
merging with #119 and #601

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in 2F9CBE9C-3EE5-4EC7-9B5B-49F671D17050/20160806-151242.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-06-11T04:14:04.709026001Z" level=debug msg="Golang's threads limit set to 6750"
time="2016-06-11T04:14:04.709600554Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-06-11T04:14:04.710765470Z" level=debug msg="received past containerd event: &types.Event{Type:\"live\", Id:\"\", Status:0x0, Pid:\"\", Timestamp:0x575b900c}"
time="2016-06-11T04:14:04.718014302Z" level=debug msg="Using graph driver aufs"
time="2016-06-11T04:14:04.980286048Z" level=debug msg="Failed to load mount b3245c3f8b09e33ecbac70eed41d8903a396f1919dfa0d07a30b6f71ea2de236: invalid mount id value"
time="2016-06-11T04:14:05.002247314Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-06-11T04:14:05.002763569Z" level=debug msg="Option DefaultDriver: bridge"
time="2016-06-11T04:14:05.003157566Z" level=debug msg="Option DefaultNetwork: bridge"
time="2016-06-11T04:14:05.011098813Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.4.11-moby`, error: exit status 1"
```
