### ISSUE TITLE
UI supports email login but command line does not

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1522]
### Expected behavior
Login with email is supported in both or neither.

### Actual behavior
UI lets you login with email but then command line actions fail.

### Information
Version 17.04.0-ce-mac7 (16352)
Channel: edge
b598153e23

### Steps to reproduce the behavior
  1. Login through UI with email
  2. Run docker command that requires credentials

**Comment by jeanlaurent** [comment]
Hi @daveisfera, thanks for your report. We agree, that's odd.

We have opened an issue in the development team issue tracker to investigate further how we should solve that.

We will let you know in there, how we intent to solve that.

**Comment by jeanlaurent** [comment]
Well the resolution is pretty much that this needs be done in docker/cli

**Comment by ebriney** [comment]
I created an issue in docker/cli#961, we can close it in favor of this one, no?
