### ISSUE TITLE
Docker won't run - 2757FFD9-5CFB-4FE4-9488-377380B8257B

### ISSUE THREAD

**Issue by surfyogi** [docker/for-mac#1523]
### Expected behavior

Install and start up Docker for Mac

### Actual behavior
Install appears successful at first. Asked me if I want to keep my old toolbox. First time I said yes, then next time I said no, seems like both installs failed.
Now, when I start docker, it fails, and I ran the diagnostic. 
I have a dockerid and password, downloaded the app, now this..

### Information

It first complained about Blue Stacks being installed on my machine. 
So, I uninstalled it, and rebooted.
It failed several times after that, so I started uninstalling anything I could think of, including:
- VMware for Mac - 
- etc
- I have Parallels installed, I won't uninstall it but it's not running right now, Docker still fails to start.
- rebooted again after uninstalling all apps I have not run for the past several months.
- I looked at my processes, I don't have anything too weird running..
- I'm running a late-2013 Macbook Pro 15 with 8gb memory on i7 chip

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/2757FFD9-5CFB-4FE4-9488-377380B8257B/20170407-203125.tar.gz
failure: vpnkit is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Jeff/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/Jeff/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Jeff/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/Jeff/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/Jeff/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Jeff/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         disk check failed with: (Failure
  "exec: \"/Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qcow-tool\" check \"/Users/Jeff/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2\" > /tmp/2757FFD9-5CFB-4FE4-9488-377380B8257B/20170407-203125/qcow-tool-check.stdout 2> /tmp/2757FFD9-5CFB-4FE4-9488-377380B8257B/20170407-203125/qcow-tool-check.stderr: exit 1")

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. See above

**Comment by dsheets** [comment]
It looks like in the process of uninstalling and re-attempting installation, the Docker for Mac disk image was corrupted. Could you try removing `/Users/Jeff/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` and starting the app?

**Comment by Martindelataille** [comment]
@dsheets I have some problem and removing `/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` fix the issue.

**Comment by surfyogi** [comment]
I checked the version; somehow I was originally attempting to install an
old Beta version I found a link to online. When I uninstalled it, then
installed current version it worked ok.

thanks
Jeff-
