### ISSUE TITLE
Error after waking up mac:  [ERROR]  driver.amd64-linux

### ISSUE THREAD

**Issue by ccjon** [docker/for-mac#1524]
### Expected behavior
expected no feedback from docker

### Actual behavior
error message 
### Information
After waking up from sleep, dialog with error appeared....

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu:
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.10.5 (build: 14F2315)
logs: /tmp/B65ACC4B-C81D-4C42-B06E-4354B711BBB2/20170409-160628.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ccjon/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ccjon/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/ccjon/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ccjon/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
Just woke up from overnight sleep: closed cover (portable)

### Steps to reproduce the behavior

see above

**Comment by gcalex5** [comment]
Had the same problem as you tried all the uninstall/remove specific file solutions that popped up. but what worked for me was issue #3 here https://thecodecentral.com/ with needing to do the accepted solution here http://stackoverflow.com/questions/28063598/error-while-executing-plist-file-path-had-bad-ownership-permissions

**Comment by dsheets** [comment]
It looks like you've encountered a Hypervisor.framework bug in OS X 10.10. We recommend running OS X 10.11.3 or higher with Docker for Mac. There's nothing we can do to fix this and Apple is unlikely to release a patch for 10.10 so upgrading your OS is the best option. Thanks for using Docker for Mac!
