### ISSUE TITLE
Mac unable to sleep

### ISSUE THREAD

**Issue by mikesir87** [docker/for-mac#1525]
### Expected behavior

When putting my machine to sleep, I'd expect it to go to sleep.

### Actual behavior

Machine is unable to sleep.  But, after being in my backpack for a short time, the fans are going crazy.  Looking at the console logs, I see the following repeated over and over again.

### Information

- Running on Edge, currently 14.04.0-ce-mac7 (16352)
- All diagnostics are passing and containers start up/tear down normally. Diagnostic ID: C13D32E0-A906-4474-AFFF-DFE54ACF8DC9
- Lack of sleep is experienced even when running no containers

```
Apr  9 18:18:55 my-machine Docker[11617]: System wants to go to sleep
Apr  9 18:18:55 my-machine Docker[11617]: com.docker.hyperkit is running and not shutting down because on-sleep = no not freeze
Apr  9 18:18:57 my-machine Docker[11617]: System wants to wake up
Apr  9 18:18:57 my-machine Docker[11617]: com.docker.hyperkit is already running so nothing to do
Apr  9 18:19:44 my-machine Docker[11617]: System wants to go to sleep
Apr  9 18:19:44 my-machine Docker[11617]: com.docker.hyperkit is running and not shutting down because on-sleep = no not freeze
Apr  9 18:19:45 my-machine Docker[11617]: System wants to wake up
Apr  9 18:19:45 my-machine Docker[11617]: com.docker.hyperkit is already running so nothing to do
```

Not sure what else you might need.  Feel free to let me know.

**Comment by mikesir87** [comment]
Just happened again on me on my walk home. This time, had two containers that were actively running (node and Chrome selenium containers). Same messages in the system.log file.  

Forgot to mention earlier... running Mac OSX 10.12.4

**Comment by dsheets** [comment]
Do you experience the same insomnia without Docker for Mac running? Are you running Caffeine, `caffeinate`, KeepingYouAwake or similar?

**Comment by mikesir87** [comment]
I am running KeepingYouAwake on my machine. If I quit Docker, it goes to
sleep as expected.

**Comment by dsheets** [comment]
If you run Docker and quit KeepingYouAwake do you still experience the insomnia?

**Comment by amir-hadi** [comment]
I have absolutely the same problem and was wondering why my Macbook Pro has a drained battery in the morning. I found the exact same log lines and now, when I shutdown docker before going to bed, everything is fine.

**Comment by dsheets** [comment]
@amir-hadi could you please run :whale: ➡️ `Diagnose and Feedback...` ➡️ `Diagnose & Upload` and post the resulting diagnostic ID back here? Thanks!

**Comment by amir-hadi** [comment]
@dsheets Here is my diagnostic ID: EFDDAC57-4FC3-4F9E-A6E0-E895987A0A51.

**Comment by dsheets** [comment]
@amir-hadi your specific symptoms look slightly different to @mikesir87's. While @mikesir87 appears to have sleep/wake events rapidly triggered (sleep with immediate wake followed by a ~1min pause before trying to sleep) you seem to have a machine that wakes up in the middle of the night *without* triggering sleep/wake events. Did you experience the problem the night of 12 April?

Here's the logs from the VM process the night of 12 April:

```
2017-04-12 23:23:21+02 Amirs-MBP Docker[com.docker.driver.amd64-linux][805] <Notice>: System wants to go to sleep
2017-04-12 23:23:21+02 Amirs-MBP Docker[com.docker.driver.amd64-linux][805] <Notice>: com.docker.hyperkit is running and not shutting down because on-sleep = no not freeze
2017-04-13 10:20:02+02 Amirs-MBP Docker[com.docker.driver.amd64-linux][805] <Notice>: System wants to wake up
```

and here's the (edited) logs from the host system:

```
2017-04-12 23:12:38.725104+0200  localhost Docker[781]: [com.docker.docker.] Analytics: Sent heartbeat event.
2017-04-13 02:24:53.379874+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000001639f, Description: Loading Preferences From System CFPrefsD For Search List
2017-04-13 02:24:53.379955+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000001cda0, Description: Loading Preferences From User CFPrefsD For Search List
2017-04-13 02:24:58.241172+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000001cda1, Description: Loading Preferences From System CFPrefsD For Search List
2017-04-13 02:24:58.241263+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000001cda2, Description: Loading Preferences From User CFPrefsD For Search List

...

2017-04-13 03:48:05.928543+0200  localhost Docker[781]: (Security) [com.apple.securityd.atomicfile] 0x60000027c640 opened /Users/ahadi/Library/Keychains/login.keychain-db: 404764 bytes
2017-04-13 03:48:05.937637+0200  localhost Docker[781]: (Security) [com.apple.securityd.atomicfile] 0x600000277c00 opened /Library/Keychains/System.keychain: 70960 bytes
2017-04-13 03:48:06.152678+0200  localhost Docker[781]: [com.docker.docker.] Analytics: Sent heartbeat event.
2017-04-13 03:48:09.190752+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000002779c, Description: Loading Preferences From System CFPrefsD For Search List

...

2017-04-13 06:12:25.369091+0200  localhost symptomsd[230]: (SymptomEvaluator) [com.apple.symptomsd.netepochs] ticker check tickerFatal PASSED on <private>, fatal not running, event by: TrackedFlow at 0x7fbae62205f0 com.docker.docker 5 type 1 timestamps 2017-04-13 04:12:25 +0000  2017-04-13 04:12:25 +0000 duration 0.164709 key <502132e6 ba7f0000> wifi rx 4403 tx 1145 pkts rx 9 tx 11 errs (0 0 0 32) (0 0 0 0)

...

2017-04-13 06:51:00.577604+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000003f440, Description: Loading Preferences From User CFPrefsD For Search List
2017-04-13 10:20:02.593711+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000003f441, Description: Loading Preferences From System CFPrefsD For Search List
2017-04-13 10:20:02.594364+0200  localhost Docker[781]: (Docker) Created Activity ID: 0x800000000003f442, Description: Loading Preferences From User CFPrefsD For Search List
2017-04-13 10:20:04.135928+0200  localhost com.docker.driver.amd64-linux[805]: (com.docker.driver.amd64-linux) Created Activity ID: 0x8000000000014915, Description: Loading Preferences From System CFPrefsD For Search List
2017-04-13 10:20:04.136069+0200  localhost com.docker.driver.amd64-linux[805]: (com.docker.driver.amd64-linux) Created Activity ID: 0x8000000000014916, Description: Loading Preferences From User CFPrefsD For Search List
```

We only collect logs that we believe will be relevant to diagnosing issues with Docker for Mac so your system may contain more logs from the night of 12 April that could help explain why it was waking without triggering sleep/wake events -- another process may be implicated. Could you check those logs in `Console.app` for events between 2017-04-12 23:23:21+02 and 2017-04-13 10:20:02+02? There are possibly messages during that time that are very interesting. If you're comfortable sharing the logs, you can either upload them here or send them to <david.sheets@docker.com>.

Additionally, I would try disabling (temporarily) `Wake for Wi-Fi network access` in `System Preferences` ➡️ `Energy Saver` and `Allow Bluetooth devices to wake this computer` in `System Preferences` ➡️ `Bluetooth` ➡️ `Advanced...`. Do you use Bluetooth peripherals?

Was your machine plugged into a power outlet last night? macOS has a feature called Power Nap that allows the machine to partially wake and perform background activities.

**Comment by amir-hadi** [comment]
Hi David,

I know about Power Nap, but since my MacBook Pro isn't plugged into a power outlet at home, that shouldn't be the problem. To be honest I guess I was doing a false alarm, because tonight I had the same issue, but I am sure that I've terminated the Docker.app before going to sleep. In the morning I had a drained battery once again.

I will send you the requested logs to your email address, but I don't see anything docker related in the between 2017-04-12 23:23:21+02 and 2017-04-13 10:20:02+02. The majority of log entries log like this:

```Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67722.957 [DFR] [deviceTerminate] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67722.957 [DFR] [_DFRDisplayDeviceRemoved] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67722.974 [DFR] [___DFRDisplayDeviceRemoved_block_invoke] calling client detach callback
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67722.974 [DFR] [_DFRDisplayClose] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.377 [DFR] [deviceMatch] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.377 [DFR] [_DFRDisplayDeviceAdded] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.379 [DFR] [_DFRDisplayUsbStart] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.379 [DFR] [_DFRDisplayOpen] 
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.382 [DFR] [_DFRDisplayOpen] sending GetInfo
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.383 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 0
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.383 [DFR] [_DFRDisplayHandleVendorPacket] calling client attach callback
Apr 13 05:19:33 Amirs-MBP WindowServer[165]: 67723.383 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 1
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67793.957 [DFR] [deviceTerminate] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67793.961 [DFR] [_DFRDisplayDeviceRemoved] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67793.964 [DFR] [___DFRDisplayDeviceRemoved_block_invoke] calling client detach callback
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67793.964 [DFR] [_DFRDisplayClose] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.377 [DFR] [deviceMatch] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.377 [DFR] [_DFRDisplayDeviceAdded] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.378 [DFR] [_DFRDisplayUsbStart] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.378 [DFR] [_DFRDisplayOpen] 
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.379 [DFR] [_DFRDisplayOpen] sending GetInfo
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.380 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 0
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.380 [DFR] [_DFRDisplayHandleVendorPacket] calling client attach callback
Apr 13 05:20:44 Amirs-MBP WindowServer[165]: 67794.380 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 1
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67900.973 [DFR] [deviceTerminate] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67900.973 [DFR] [_DFRDisplayDeviceRemoved] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67900.976 [DFR] ERR [_DFRDisplaySendPacket] WritePipe failed 0xe00002c0
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67900.976 [DFR] [___DFRDisplayDeviceRemoved_block_invoke] calling client detach callback
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67900.976 [DFR] [_DFRDisplayClose] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.390 [DFR] [deviceMatch] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.391 [DFR] [_DFRDisplayDeviceAdded] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.391 [DFR] [_DFRDisplayUsbStart] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.391 [DFR] [_DFRDisplayOpen] 
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.393 [DFR] [_DFRDisplayOpen] sending GetInfo
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.394 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 0
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.394 [DFR] [_DFRDisplayHandleVendorPacket] calling client attach callback
Apr 13 05:22:31 Amirs-MBP WindowServer[165]: 67901.395 [DFR] [_DFRDisplayHandleVendorPacket] kDFRDisplayCommandGetInfo ready: 1
```

Unfortunately I can't remember since when this problem occurred, that would make it much easier to find the issue.

**Comment by amir-hadi** [comment]
@dsheets Hello David, short update. Maybe I was not right and Docker did not shutdown properly or I've forgot to shut it down. Tonight I was especially careful to shut it down and check the Activity Log to ensure that it is not running anymore. Result: Good battery.

What I also disabled is Power Nap on Battery. I am not sure if this is enabled by default or disabled. In the system.log files it still looks like it's waking up in the night, but not every minute. If you want to, I can send you the log files, too.

**Comment by balrajsingh** [comment]
@mikesir87 @amir-hadi: could you reconfirm that you are still experiencing this issue and also that nothing else is running that could interfere with good sleep.

**Comment by mikesir87** [comment]
@balrajsingh - Yes. It has still been an issue.  Even on my walk into work this morning, I see messages in my Mac Console (system.log)...

```
May  3 08:10:19 Docker[96447]: System wants to go to sleep
May  3 08:10:19 Docker[96447]: com.docker.hyperkit is running and not shutting down because on-sleep = no not freeze
May  3 08:10:21 Docker[96447]: System wants to wake up
May  3 08:10:21 Docker[96447]: com.docker.hyperkit is already running so nothing to do
```

**Comment by ijc25** [comment]
@mikesir87 those message indicate that hyperkit is not suspending the processes associated with the _virtual_ CPUs (which was a workaround for bugs in early versions of `Hypervisor.framework` and no longer necessary). This should have no effect on whether the physical system suspends or not.

**Comment by mikesir87** [comment]
Interesting @ijc25 . I've looked through the logs and don't see anything else that might be interfering with sleep. I haven't noticed sleep issues when Docker is not running.  But, I can try to pay more attention to it.  Any other pointers on where to look?

**Comment by ijc25** [comment]
I don't have much insight into macOS in general I'm afraid, I didn't see an answer to https://github.com/docker/for-mac/issues/1525#issuecomment-293533064 though.

**Comment by mikesir87** [comment]
I had tried with Docker running and KeeingYouAwake not running and it failed to sleep.  But, that was before DockerCon, so I'll give it another shot over the next day or two.

**Comment by mikesir87** [comment]
Just had Docker running with KeepingYouAwake not, and the system did not go to sleep.  The only messages I saw during my walk home in the `system.log` were the same Docker events mentioned earlier.

**Comment by dsheets** [comment]
@mikesir87 could you please upload a diagnostic bundle immediately after observing this behavior without KeepingYouAwake running? After upload, please post your diagnostic ID back here.

Thanks!

**Comment by andrewgiessel** [comment]
I have a similar problem- but I don't see `com.docker.hyperkit is running and not shutting down because on-sleep = no not freeze` in my system.log.  However, I *do* see the WindowServer errors, the exact same ones.  I do have docker for mac installed.

@mikesir87 by any chance did you install DisplayLink drivers or use a USB-C hub?

I'll try shutting down Docker before putting the laptop to sleep, as well.

**Comment by mikesir87** [comment]
@andrewgiessel - I don't have any drivers and my MBP is pre-USB-C, so no hub here.

**Comment by mikesir87** [comment]
@dsheets - just had it happen again, although KeepingYouAwake was running too this time (sorry). But, here's the diagnostic ID: EBC4E1D5-3B4B-4898-992A-B4FC1558D019

**Comment by mikesir87** [comment]
Here's another one - EBC4E1D5-3B4B-4898-992A-B4FC1558D019. Interesting that I just did a new diagnostic and got the same ID. Is that to be expected at all?

**Comment by amir-hadi** [comment]
Happend to me again, but not sure what is causing it: EFDDAC57-4FC3-4F9E-A6E0-E895987A0A51

**Comment by amir-hadi** [comment]
I did go the painful way of a clean install and didn't have the issue since then. Now I reinstalled docker. If it occurs again in the next 5 days I guess I can be sure that it is caused by Docker.app.

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by donatoaz** [comment]
I'm running on edge and am getting this same issue... I generally ride a bike to work and one day it started feeling oddly hot in my back... guess what... Anyways, I got in the habit of quitting docker altogether at end of day to prevent this.
