### ISSUE TITLE
Docker whale icon on menu bar lost its eye :(

### ISSUE THREAD

**Issue by wickedpatrick** [docker/for-mac#1527]
### Expected behavior
Whale icon on menu bar should have eye.

### Actual behavior
Whale icon on menu bar doesn't have eye.

### Steps to reproduce the behavior
1. Install latest version of Docker and run.
2. Whale's eye is missing.

**Comment by dsheets** [comment]
This change is part of a subtle rebranding we've recently done. Look at the whale at the top left of <https://www.docker.com/> which is now also eye-less. I hear from the Interweb that logo simplification is a common technique to make brands more timeless and instantly recognizable. Hopefully your containers keep working even if the whale is blind. Good luck!

**Comment by dlgoodchild** [comment]
+1 for bringing back the eye. It gives the wee guy character.

**Comment by flynniec6** [comment]
+1 for bringing back the eye. Feels like **docker** didn't start up correctly. And it's sad. Poor whale.

**Comment by e-stefan** [comment]
+1 for bringing back the eye. It's an essential detail of a whale to have. For me the journey of a blind whale would be kind of unpredictable, that's most likely not what a logo should tell.

**Comment by xbx** [comment]
The Docker Hub's logo still has its eye:

![image](https://user-images.githubusercontent.com/396104/29379463-ef8444ca-8298-11e7-9cb9-1352ab4db1c9.png)

**Comment by e-stefan** [comment]
Yes, fortunately the eye has not been wiped out everywhere, my favourite one is the tiny little one of that happy whale:
![docker_whale_with_eye_mini](https://user-images.githubusercontent.com/5851901/29409864-ca461616-8356-11e7-9f8f-bdb174575c41.png)

**Comment by kenahoo** [comment]
Kind of impossible to tell it's actually a whale without the eye.
