### ISSUE TITLE
Docker puts User-modifiable symlinks on $PATH

### ISSUE THREAD

**Issue by halosteve** [docker/for-mac#1528]
### Expected behavior

The symlinks Docker uses to add its commands to `$PATH` should be owned by the user that installed Docker, and should point directly to the `/Application/Docker.app` binaries.  The symlinks should be owned at least by the user that installed the Docker app, or root.

### Actual behavior

Docker installs symlinks in `/usr/local/bin` that point to a set of symlinks in `~/Library/Group Containers/group.com.docker/bin`, which in turn point to the binaries in `/Application/Docker.app/Contents/Resources/bin/`

It sets up this configuration every time it starts, and makes the links all owned by the user that is running the Docker process.  _It does this even if the links are owned by root, and does so without notifying the user._ - see [https://github.com/docker/for-mac/issues/455](https://github.com/docker/for-mac/issues/455)

### Information

This configuration seems insecure.  Any process running as the user could change what these symlinks point to, resulting in the user potentially running a `docker` binary different from the one installed.

Is this set-up necessary?  Is there a way to prevent Docker from changing to it each time it runs?

### Steps to reproduce the behavior

  1. Install Docker as an administrator
  2. Change the symlinks in `/usr/local/bin` to point directly to the Docker binaries and be owned by root, e.g. `sudo ln -fs /Application/Docker.app/Contents/Resources/bin/docker /usr/local/bin/docker`
  3. Change users and log in as a non-admin user.
  4. Run the Docker app
  5. The symlinks in `/usr/local/bin` will now point to symlinks in `~/Library/Group Containers/group.com.docker/bin`, and both will be owned by the non-admin user.

**Comment by dsheets** [comment]
Thanks for your report! We recognize that this is an issue and have an internal ticket open to improve this behavior from #455. I'm going to increase the priority of that work and point the responsible developers here. I'm leaving this open as this issue is narrower in scope than #455.
