### ISSUE TITLE
17.04.0-ce-mac7: run container from CLI hangs after job completes

### ISSUE THREAD

**Issue by vielmetti** [docker/for-mac#1529]
### Expected behavior

Running a container from the CLI finishes cleanly after the job runs.

e.g.
```
% docker run --rm -it aarch64/ubuntu:latest apt-get update
```
### Actual behavior

Command runs properly but at the end of the command, it does not terminate. ^C and ^Z do not affect it. I can stop the command by sending a kill signal from another terminal.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

```
Docker for Mac: version: 17.04.0-ce-mac7 (b598153e2)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/E0936CCF-861A-496D-AA07-B105AC4314C5/20170410-171041.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

```
% ps auxw | grep -i aarch64
emv             81445   0.0  0.0 556644128    228 s003  S+   12:40PM   0:00.09 docker run --rm -it aarch64/ubuntu:latest apt-get update
```

### Steps to reproduce the behavior

  1.  docker run --rm -it aarch64/ubuntu:latest apt-get update
  2A. On an aarch64 machine (Packet Type 2A), it runs to completion and exits.
  2B. On a Mac running 10.11.6, described above, it runs to completion and hangs.
  2C. On a Mac running 10.12.4, described below, it runs to completion and exits.

### Notes

This is a test case for https://github.com/docker-library/official-images/issues/2804

**Comment by tophj-ibm** [comment]
I am unable to reproduce this, the container exits normally for me. I'm on the same docker version, but on a different macos version.

```
Docker for Mac: version: 17.04.0-ce-mac7 (b598153e2)
macOS: version 10.12.4 (build: 16E195)
```

**Comment by dsheets** [comment]
I cannot reproduce this on OS X 10.11.6 with the system `bash`:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

What shell are you using?

**Comment by vielmetti** [comment]
Bash is 

```
Edwards-MacBook-Air:~ emv$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

However - I installed the latest Apple security patch, 2007-001, and now I can't reproduce it; the containers that used to hang are now running just fine.

Thanks everyone for helping me sort this out.
