### ISSUE TITLE
Watching files has stopped working with latest docker update (17.04.0-ce-mac7)

### ISSUE THREAD

**Issue by aphillipo** [docker/for-mac#1530]
### Expected behavior

Watching files with things like webpack --watch works fine.  Used to work perfectly on this machine.

### Actual behavior

Watching files doesn't work when they change no rebuild of the JS happens.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.04.0-ce-mac7 (b598153e2)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/8F0C8DE6-BFA5-497F-B983-3DE6F16F450D/20170411-105559.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW

I don't have time to do this but now.

### Steps to reproduce the behavior

  1. Watch files
  2. Change them from outside the container
  3. Nothing happens
  4. Previous version notices the change and rebuilds.

**Comment by geekus** [comment]
I experienced the same issue after updating, but a system reboot fixed it.

**Comment by iJebus** [comment]
Same issue, however rebooting the host did not resolve the issue. I am on Version 17.03.1-ce-mac5 (16048) however, not 17.04.

**Comment by aphillipo** [comment]
Yes for me a reboot also doesn't solve this 😞

**Comment by dsheets** [comment]
Are you still experiencing this issue?

**Comment by aphillipo** [comment]
I’ve updated and it’s fine now!
