### ISSUE TITLE
Clean Mac OS from Docker toolbox to install Docker for Mac

### ISSUE THREAD

**Issue by laptevn** [docker/for-mac#1534]
Docker for Mac doesn't work for me at all. There are numerous timeout errors.
Docker toolbox was installed initially.
I tried to remove Docker toolbox (according to https://docs.docker.com/toolbox/toolbox_install_mac/#how-to-uninstall-toolbox) before installing Docker for Mac, but got timeout errors.
Docker toolbox works fine. Docker for Mac doesn't work at al because of timeout errors while pulling and pushing.
I'm ok with System Requirements for Docker for Mac.

How can I clean my Mac OS from Docker toolbox to install Docker for Mac?

**Comment by laptevn** [comment]
The history is the following:
1 I had Docker toolbox installed and running fine.
2 I remove the toolbox and installed Docker for Mac. It worked fine.
3 Recently I got numerous timeout errors and decided to clean system from Docker and install everything from scratch.
4 Only Docker toolbox works now.

**Comment by dsheets** [comment]
What specific errors do you see? Could you please upload your diagnostics and post your diagnostic ID from :whale: ➡️ `Diagnose and Feedback...` ➡️ `Diagnose & Upload`?

**Comment by laptevn** [comment]
@dsheets you can just google for "Docker timeout". Everybody has the same issue.
I tried Edge version of Docker for Mac and it works fine.
That may mean that a stable version will also contain the fix soon.

**Comment by dsheets** [comment]
"Docker timeout" is a generic symptom of possibly many different problems. If you're happy running Edge and don't want to supply diagnostic information, I'm afraid there's not much more that can be done to determine the cause of the problem.
