### ISSUE TITLE
Cannot access all organizations

### ISSUE THREAD

**Issue by jsouth** [docker/for-mac#1538]
### Expected behavior
As a user: I would expect to be able to view all organizations that I belong to : and select the org to work on/under for my Docker projects. Currently the ui displays 10 orgs(not allowing the user to select orgs 11+). It would be expected to display a "view all" link to allow users to select the desired org.

Furthermore: since users cannot delete Docker organizations(separate legacy issue), this issue will become more noticeable over time for our users.

### Actual behavior
Currently the ui displays 10 orgs(not allowing the user to select orgs 11+).

### Screenshot

![orgs](https://cloud.githubusercontent.com/assets/657082/24971724/c09ac8ca-1f6d-11e7-8e6c-5461e8ec9793.png)

thanks!

**Comment by dsheets** [comment]
Thanks for your report! I've escalated the issue to the GUI team.

**Comment by guillaumerose** [comment]
This is fixed since last June. Thanks for the report!
