### ISSUE TITLE
Container could not be stopped or killed

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#1539]
### Expected behavior
It can be stopped (or at least killed).

### Actual behavior
It's stuck and I have to restart Docker.

### Information
91BA0B97-2185-40E4-8CF7-F4C94774E732

**Comment by techmaniack** [comment]
How do I reproduce this?

**Comment by daveisfera** [comment]
I don't have a consistent way to reproduce it. It just happens once or twice a week while I'm using Docker.

**Comment by jamesgallagher-ie** [comment]
Fwiw I'm seeing a similar issue and can't figure out how I'd reproduce it on demand (01678987-9334-4716-A2E5-EBF1710BE9B6 is the diagnose ID I got when I discovered this instance of the issue but I couldn't see anything obvious in the logs). I'm seeing the issue with the same containers each time but it's happening anywhere between 6 and ~36 hours after a Docker restart (as best I can tell - will look to see if I can get more specific information)

**Comment by akimd** [comment]
Please tell us if you still have this problem with the latest releases.
