### ISSUE TITLE
63570BA3-242B-4FA3-8845-119F7B772F6D

### ISSUE THREAD

**Issue by cosma** [docker/for-mac#1543]
### Expected behavior
open docker in macos 
### Actual behavior
crashed
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. open my mac after shutdown
  2. ...

**Comment by ebriney** [comment]
It seems that the app crashed on osx side but we don't have enough informations to find where it comes from.
Did a `reset to factory` fix the situation?

**Comment by guillaumerose** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
