### ISSUE TITLE
Swarm Opens in Mac Terminal

### ISSUE THREAD

**Issue by bah2830** [docker/for-mac#1546]
### Expected behavior
When clicking a swarm from the taskbar it should open in the systems default terminal.

### Actual behavior
Opens in the built in mac terminal

### Information
This was an issue for kitematic at one point as well and has since been fixed. It now exists for swarms.

This is in the edge channel so it may be known and being worked on.

**Comment by ebriney** [comment]
Thanks Brent for the report, we have an open issue to implement it but it is not done yet.

**Comment by timmyers** [comment]
As a workaround, I found this link https://superuser.com/questions/379342/setting-iterm2-as-the-default-terminal-osx-lion to be helpful.

Download and install http://www.rubicode.com/Software/RCDefaultApp/.  Then in UTI's, change `com.apple.terminal.shell-script to the application of your choice (I'm using Hyper and worked perfectly).

**Comment by hallazzang** [comment]
I'm waiting for this issue to be resolved!

**Comment by bynarlogic** [comment]
@timmyers Is there a way to have it open up in zsh mode instead of bash?

**Comment by timmyers** [comment]
It's been a while since I have been using this at all, but I think it used zsh for me (with Hyper) due to the fact I was setting my `shell: '/usr/local/bin/zsh` in `.hyper.js`.

Beyond that I'm not sure at this point, sorry!

**Comment by akimd** [comment]
Docker Cloud is phased out.
