### ISSUE TITLE
Docker doesn't start after hard reboot

### ISSUE THREAD

**Issue by xarg** [docker/for-mac#1547]
### Expected behavior

Expected docker daemon to start.

### Actual behavior

Didn't start and showed this error:

```
Fatal Error

com.docker.osx.hyperkit.linux failed to start
Exit code 1
```

### Information

Diagnostic ID: 6CD9C794-D408-45C2-AF3F-B49C76331CB9

```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/6CD9C794-D408-45C2-AF3F-B49C76331CB9/20170419-150306.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/a/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/a/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/a/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/a/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/a/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/a/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

```

### Steps to reproduce the behavior

  1. I just held the power to reboot my macbook pro.
  2. Booted
  3. Docker doesn't start anymore.

**Comment by xarg** [comment]
Reseting to factory settings fixed the issue (but I lost all my images/containers/etc..). Not a big issue since it's a developer machine, but still very frustrating that I now have to re-download everything. Sorry I couldn't wait to debug this.

**Comment by ebriney** [comment]
Thanks Alex for the report. It seems that your qcow2 disk had been corrupted. We are working on fixing this error, your disk should not have this errors even on hard reboot.

> Found a reference to cluster 502479 outside the file (max cluster 502478) from cluster 258097.51880

We have #1315 as the public tracking issue. Please subscribe to #1315 for further updates.

**Comment by Mohammed-Nawazuddin** [comment]
docker doesn't start instead it says permission denied for my mac os seria .
mds-MacBook-Pro:~ mdnawazuddin$ ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
ln: /usr/local/bin/docker: File exists
mds-MacBook-Pro:~ mdnawazuddin$ ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
-bash: /Users/mdnawazuddin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2: Permission denied
mds-MacBook-Pro:~ mdnawazuddin$
