### ISSUE TITLE
 Expected behavior

### ISSUE THREAD

**Issue by wlazlowski** [docker/for-mac#1549]
### Information

Diagnostic ID: 2A8912D4-CB01-4D0F-832B-3D9A798CC173
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.4 (Build 16E195)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/tomaszwlazlowski/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/tomaszwlazlowski/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/2A8912D4-CB01-4D0F-832B-3D9A798CC173/20170420-144021/qemu-img-check.stdout 2> /tmp/2A8912D4-CB01-4D0F-832B-3D9A798CC173/20170420-144021/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/tomaszwlazlowski/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/tomaszwlazlowski/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by yallop** [comment]
1.12.0 is a pretty old version of Docker for Mac -- so old, in fact, that it doesn't support OSX Sierra.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.
