### ISSUE TITLE
Passing multiple builtin build-args fails build

### ISSUE THREAD

**Issue by shomron** [docker/for-mac#1550]
### Expected behavior

Passing multiple builtin build-args (e.g. `http_proxy` + `https_proxy`) should not cause the build to fail.

### Actual behavior

...but it does, silently.

#### Multiple args, fails:

```
$ docker build --build-arg http_proxy=foo --build-arg https_proxy=foo .
Sending build context to Docker daemon   16.9kB
Step 1/2 : FROM alpine:3.4
 ---> 0766572b4bac
Step 2/2 : RUN touch /tmp/foobar
 ---> Running in 1e1f4d11c58a
```

#### One renamed:

```
$ docker build --build-arg http_proxy=foo --build-arg renamed_https_proxy=foo .
Sending build context to Docker daemon   16.9kB
Step 1/2 : FROM alpine:3.4
 ---> 0766572b4bac
Step 2/2 : RUN touch /tmp/foobar
 ---> Running in bf03d1f69a80
 ---> c042f55add5e
Removing intermediate container bf03d1f69a80
[Warning] One or more build-args [http_proxy renamed_https_proxy] were not consumed
Successfully built c042f55add5e
```

#### The other renamed:

```
$ docker build --build-arg renamed_http_proxy=foo --build-arg https_proxy=foo .
Sending build context to Docker daemon   16.9kB
Step 1/2 : FROM alpine:3.4
 ---> 0766572b4bac
Step 2/2 : RUN touch /tmp/foobar
 ---> Running in 2fdaa9a16682
 ---> f7194379edfe
Removing intermediate container 2fdaa9a16682
[Warning] One or more build-args [https_proxy renamed_http_proxy] were not consumed
Successfully built f7194379edfe
```

### Information

Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/294E57EF-27BD-49FA-B56A-324F1011913D/20170420-111325.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Simple `Dockerfile` (didn't reproduce without at least a `RUN`):

```
FROM alpine:3.4
RUN touch /tmp/foobar
```

1. Try to build, passing multiple builtin build-args:
    `docker build --build-arg http_proxy=foo --build-arg https_proxy=foo .`
or
`docker build --build-arg http_proxy=foo --build-arg no_proxy=foo .`
2. You will not get a `Successfully built ....` message.

**Comment by djs55** [comment]
@shomron thanks for the report and the clear reproduction.

It reproduces for me on `17.05.0-ce-rc1` and @dave-tucker reports that it works correctly on `17.04.0-ce`. Since it reproduces for me inside the Linux VM, it must be a bug in the engine. I'll open a ticket on moby/moby (the new docker/docker) and link it back here.

**Comment by djs55** [comment]
@dave-tucker has created a PR to fix the bug: https://github.com/moby/moby/pull/32763 and requested that it be cherry-picked into the next RC.

**Comment by alexellis** [comment]
This is a blocker for me.. what should I do, switch to stable?

**Comment by dave-tucker** [comment]
@alexellis yes that's the best advice I can offer for now. If you can help with the PR getting merged in moby/moby that'd be wonderful!

**Comment by dave-tucker** [comment]
Closed via https://github.com/moby/moby/pull/32763
