### ISSUE TITLE
Unable to "exec bash" in a running container that was previously responsive

### ISSUE THREAD

**Issue by jwhitlock** [docker/for-mac#1551]
### Expected behavior

``docker -D exec -it kuma_web_1 bash`` should open a bash shell in the container, for a container started w/ ``docker-compose``.

### Actual behavior

```
rpc error: code = 2 desc = containerd: container did not start before the specified timeout
DEBU[0179] [hijack] End of stdout                       
DEBU[0179] Error resize: Error response from daemon: rpc error: code = 2 desc = containerd: process not found for container 
```
``docker ps`` reports that the container is running and has been up for 2 days.  I was in the middle of an interactive bash session which became non-responsive

### Information

Diagnostic info, ID 7B1A493C-1D61-49DE-9A89-DEC81DDAEA22
```
Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/7B1A493C-1D61-49DE-9A89-DEC81DDAEA22/20170420-102007.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

No clear reproduction steps.  Containers are responsive for hours, overnight, after sleep, and then become randomly non-responsive during regular usage.  I do not recall this issue with previous releases.

A Restart via the Docker menu never completes.

Quiting Docker via the menu, waiting for a full shutdown (``ps -ef | grep -i docker``), and restarting Docker works.  A host system reboot also works.

**Comment by jwhitlock** [comment]
Perhaps related - it appears the computing resources reset to 2 GB / 2 processors.  I'll monitor if the issue returns now that I'm at 12 GB / 6 cores

**Comment by jwhitlock** [comment]
Another non-responsive container, diagnostic ID 7B1A493C-1D61-49DE-9A89-DEC81DDAEA22:

* Ran ``docker-compose up -d``, running a container ``kuma_web_1`` among others.
* Entered interactive session with ``docker exec -it kuma_web_1 bash``
* Ran some commands, tests, etc. for about 1 hour
* Typed ``./man`` and then TAB, to auto-complete Django's ``./manage.py`` with bash completion.
* Interactive session freezes and is non-responsive.  Container is running a web server on host port 8000, which is also unresponsive.
* Other containers running web servers on exposed ports are unresponsive.  Cannot enter an interactive bash session with any, or run a simple command like ``ls``, error is ``rpc error: code = 2 desc = containerd: container did not start before the specified timeout``.
* ``docker ps`` shows all containers are running.
* ``docker-compose stop`` times out with error:
```
ERROR: for kuma_worker_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

ERROR: for kuma_web_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
* "Restart" via the docker menu does not complete in 60 seconds.
* "Quit" via the docker menu quits, takes about 60 seconds to shutdown background processes
* On restart of Docker, entered a bash session again, ``./man`` + TAB has expected expansion.

**Comment by gaspar1423** [comment]
I'm having exact same issue described above but on ubuntu 16.04.2 LTS.

**Comment by jwhitlock** [comment]
This has not repeated for me in a long time.  On Docker Community Edition, 17.03.1-ce-mac12 (17661), stable channel. Updating to 17.06.0-ce-mac18 🤞
