### ISSUE TITLE
Complaint re VirtualBox even though uninstalled

### ISSUE THREAD

**Issue by danielsoutar** [docker/for-mac#1553]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.10.5 (build: 14F27)
logs: /tmp/830D5159-1281-410B-8D31-DE9E2D4AFAB5/20170421-122603.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/soutar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/soutar/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/soutar/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/soutar/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/soutar/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/soutar/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

830D5159-1281-410B-8D31-DE9E2D4AFAB5

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi Daniel, thanks for the report.
We had a new message in last edge version:

> Docker does not rely on VirtualBox but may not work properly on systems with VirtualBox versions prior to v%d.%d.%d
> VirtualBox v%d.%d.%d is currently installed.
> Please upgrade or uninstall VirtualBox.
> 
> Deleting the application will not unload the conflicting kernel extensions.
> For uninstall instructions, see the [VirtualBox documentation](https://www.virtualbox.org/manual/ch02.html#idm856).
> 

Did you do a full uninstall?

**Comment by danielsoutar** [comment]
Hi there,

Thanks for your reply. I hadn't, VirtualBox just proved to be difficult to
uninstall. After following their instructions and forcing a delete I
reinstalled and had no issues doing so.

Thanks again!

Daniel
