### ISSUE TITLE
Upgrading to OSX Sierra breaks 192.168.65.1 IP

### ISSUE THREAD

**Issue by tecnobrat** [docker/for-mac#1554]
### Expected behavior
The 192.168.65.1 IP should be mounted on the host

```
ifconfig |grep 192.168.65.1
    inet 192.168.65.1 netmask 0xffffff00 broadcast 192.168.65.255
```

### Actual behavior

```
ifconfig |grep 192.168.65.1
```

The IP is not mounted, and not available from the host.

### Information

Tested with both latest stable, and latest edge.

Stable: Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)

Diag output on edge:

Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/0CB9B61F-581E-4272-8B49-EC2E92AA9C58/20170421-083752.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run docker for mac on OSX `10.11.6`
  2. Run `ifconfig |grep 192.168.65.1`
  3. Upgrade to OSX `10.12.4`
  4. Run `ifconfig |grep 192.168.65.1`

**Comment by tecnobrat** [comment]
In the `system.log` in Console.app I found:

`Apr 21 08:50:47 walrus Docker[2708]: Creating slirp server peer_ip:192.168.65.2 local_ip:192.168.65.1 domain_search: mtu:1500 bridge:true`

So it looks like its trying?

**Comment by BrendonW** [comment]
IT looks like I have exactly the same problem and the result is that I'm dead in the water because none of my containers or Docker itself seem to be able to resolve any addresses.

**Comment by tecnobrat** [comment]
@ebriney can you give me an idea of what the status of this is? Looks like not many commits are happening on this repo, and with the rename of all of the things, I'm not sure I'm even in the right place anymore.

I'm happy to try to help diagnose this more or provide any information thats needed to move the needle, unfortunately I don't know where to begin.

**Comment by BrendonW** [comment]
On this issue, I just upgraded another Mac to 10.12.4 and then installed and started Docker.

On checking right after the install, there is no 192.168.65.1 at all.

Here is the Diagnose ID from that machine: AF917A30-F86F-4DDA-AE76-87E342532074

**Comment by djs55** [comment]
Hi,

Unfortunately the IP `192.168.65.1` exists only in the userspace network stack running inside the Docker for Mac application (specifically inside the `vpnkit` process). Unfortunately since Docker for Mac doesn't use the macOS kernel network stack to talk to the Linux VM it means the IP is invisible to `ifconfig` on the host. It does exist though, from the point of view of the VM.

If you run a container you should be able to `ping 192.168.65.1` and connect to services on it e.g.:
```
$ docker run -it alpine sh
/ # ping 192.168.65.1
PING 192.168.65.1 (192.168.65.1): 56 data bytes
64 bytes from 192.168.65.1: seq=0 ttl=37 time=0.364 ms
^C
--- 192.168.65.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.364/0.364/0.364 ms

/ # apk update && apk add openssh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
v3.5.2-71-g1050b6acec [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
v3.5.2-70-gec9876f375 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
OK: 7961 distinct packages available
(1/3) Installing openssh-client (7.4_p1-r0)
(2/3) Installing openssh-sftp-server (7.4_p1-r0)
(3/3) Installing openssh (7.4_p1-r0)
Executing busybox-1.25.1-r0.trigger
OK: 8 MiB in 14 packages

/ # ssh djs@192.168.65.1
The authenticity of host '192.168.65.1 (192.168.65.1)' can't be established.
ECDSA key fingerprint is SHA256:aEy53CPLfIOIvMITndxO2hynuZXpWwHgjdBNJusvmz4.
Are you sure you want to continue connecting (yes/no)? no
Host key verification failed.
```

If you need to connect to containers, I recommend exposing a port for example with `docker run -p 8080:80 nginx`.

If you need a container to connect to the host then this can be done by connecting either to
- an external IP of the host (e.g. a wired or wireless adapter IP address)
- the magic internal `192.168.65.1`, but this will only work on Docker for Mac and Windows

Is this sufficient for your needs? If not, could you explain your use case a little more?

Sorry for the confusion! Note we did use to have a different style of networking a while ago where an IP address did appear on the host -- we switched away from that because it wasn't reliable enough.

**Comment by tecnobrat** [comment]
@djs55 why does it work pre-sierra and then break on upgrade?

It does not work for my use-case.  I need a consistent IP address to be able to access the exposed container from both inside and outside other containers.  With the old docker toolbox 192.168.99.100 worked, and as long as the port was exposed, I could use that IP.

We run microservices, with many separated `docker-compose` setups, they each setup their own network, due to the way docker-compose works, so we cannot access container <-> container from each service.

Using `localhost` outside the container works, but I cannot do that inside containers, so its not consistent.

Docker for windows allows me to define the network range, so I can set the network to `192.168.65.0`, and get the same behaviour.

Docker for mac pre-sierra exposes `192.168.65.1` and that works perfectly.

Docker for mac on sierra no longer has `192.168.65.1`, which feels like a bug.

**Comment by djs55** [comment]
I genuinely don't know what created the IP `192.168.65.1` on the Mac host on Sierra on your system. Perhaps some other software or script had created an IP alias? I've considered doing exactly that within Docker for Mac to solve this exact problem, but it requires running `ifconfig` as root and we try to minimise the amount of code which runs with that level of privilege.

For example if you run this on the host:
```
$ sudo ifconfig en0 alias 192.168.65.1 255.255.255.0
$ docker run -p 80:80 nginx
```
and then `curl http://192.168.65.1` should work both from inside a container and on the host.

Does this work for you in the meantime? If so then I'll log an internal ticket to get us to think about this again.

Note Windows is slightly different as there are 2 virtual NICs: the user space one as on the Mac but also a regular Hyper-V NIC. I believe setting the IP address range to `192.168.65.0` on Windows configures this second NIC, which would work as you expect.

**Comment by tecnobrat** [comment]
@djs55 to be clear, this works if you have OSX pre-sierra.  If you upgrade your machine to sierra, the IP disappears (and do nothing else).  I have installed docker on a fresh pre-sierra machine, it has the IP, upgrade, and the IP goes away.  No other changes.

So something is clearly broken JUST on Sierra.  I did nothing to have that IP added.

**Comment by djs55** [comment]
@tecnobrat I installed `10.11.6`:
```
Dockers-Mac:~ docker$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```
then installed Docker CE stable `Version 17.03.1-ce-mac5 (16048)` from https://store.docker.com/editions/community/docker-ce-desktop-mac:
```
Dockers-Mac:~ docker$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Dockers-Mac:~ docker$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
and I don't have a `192.168.65.1` IP on the host:
```
Dockers-Mac:~ docker$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether 00:0c:29:e8:28:49 
	inet6 fe80::20c:29ff:fee8:2849%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.237.231 netmask 0xffffff00 broadcast 192.168.237.255
	nd6 options=1<PERFORMNUD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
```
-- this is what I would expect.

For your use-case, try the `ifconfig en0 alias` I described above -- I'm genuinely curious, since we have considered adding that as a feature.

**Comment by andrewgdavis** [comment]
Was there any follow up on lock pools for locksmithd?   Or was that ruled out...

**Comment by zx1986** [comment]
`192.168.65.1` won't work anymore .... :-(

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
        inet 127.0.0.1 netmask 0xff000000
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC1: flags=0<> mtu 0
XHC20: flags=0<> mtu 0
XHC0: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether 78:4f:43:90:5a:a9
        inet6 fe80::40a:770b:36cf:88b2%en0 prefixlen 64 secured scopeid 0x8
        inet 192.168.31.140 netmask 0xffffff00 broadcast 192.168.31.255
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active
```

**Comment by zx1986** [comment]
I think this will help: https://github.com/docker/for-mac/issues/2373

**Comment by djs55** [comment]
I think recent edge and stable builds are working correctly, provided the DNS names are used rather than hardcoding IPs. I'll close this issue but please do open another if you have further problems. Thanks for your reports!

**Comment by tarzan** [comment]
I think I've been having the same issues as described here. My docker image was able to access my webapplication on `http://192.168.65.1` when I last tried a year ago, but doesn't today.
I was able to run this:
```bash
seluser@81cd0a0f472e:/$ ping docker.for.mac.localhost
PING docker.for.mac.localhost (192.168.65.2) 56(84) bytes of data.
64 bytes from 192.168.65.2: icmp_seq=1 ttl=37 time=0.457 ms
64 bytes from 192.168.65.2: icmp_seq=2 ttl=37 time=0.534 ms
64 bytes from 192.168.65.2: icmp_seq=3 ttl=37 time=0.334 ms
64 bytes from 192.168.65.2: icmp_seq=4 ttl=37 time=0.551 ms
64 bytes from 192.168.65.2: icmp_seq=5 ttl=37 time=0.522 ms
64 bytes from 192.168.65.2: icmp_seq=6 ttl=37 time=0.519 ms
64 bytes from 192.168.65.2: icmp_seq=7 ttl=37 time=0.383 ms
```
Which tells me the host's IP address has changed from **192.168.65.1** to **192.168.65.2** for some reason!
