### ISSUE TITLE
Get https://registry-1.docker.io/v2/: dial tcp [::1]:443: getsockopt: connection refused

### ISSUE THREAD

**Issue by Maghraby** [docker/for-mac#1556]
Trying to build everytime i get this error.
Get https://registry-1.docker.io/v2/: dial tcp [::1]:443: getsockopt: connection refused
i tried to change the DNS server to 8.8.8.8 but not working.

**Comment by ebriney** [comment]
Hi Mahmoud , can you give use more informations doing a `Diagnose and Feedback` in the menu and uploading a report?

**Comment by guillaumerose** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
