### ISSUE TITLE
macbook pro install docker.dmg error

### ISSUE THREAD

**Issue by hbyscl** [docker/for-mac#1558]
### Information

Diagnostic ID: 365C245F-539C-4120-9A84-A3312EE645EA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.4 (Build 16E195)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/chengli/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/365C245F-539C-4120-9A84-A3312EE645EA/20170423-231856/qemu-img-check.stdout 2> /tmp/365C245F-539C-4120-9A84-A3312EE645EA/20170423-231856/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/chengli/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/chengli/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/chengli/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/chengli/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/chengli/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by ebriney** [comment]
Hi Li. This version is very old, we don't support it anymore.
Why don't you use [last stable one](https://download.docker.com/mac/stable/Docker.dmg)?
