### ISSUE TITLE
Just installed Docker on Mac but it is not working. Keeps "Docker starting..."

### ISSUE THREAD

**Issue by flaviostutz** [docker/for-mac#156]
### Information

Diagnostic ID: 982DA316-5943-4DE5-A478-2FAC26B801A8
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'daemon-didnt-start' in 982DA316-5943-4DE5-A478-2FAC26B801A8/20160806-121954.

The docker daemon inside the VM failed to start.

The following log matches:
```
time="2016-08-06T15:17:26.845113928Z" level=debug msg="Golang's threads limit set to 27990"
time="2016-08-06T15:17:26.845798685Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-08-06T15:17:26.852062016Z" level=debug msg="Using graph driver aufs"
time="2016-08-06T15:17:26.852690448Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-06T15:17:26.852969525Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-06T15:17:26.881668384Z" level=debug msg="Cleaning up old mountid : start."
time="2016-08-06T15:17:26.882493676Z" level=fatal msg="Error starting daemon: readdirent: not a directory"
```

@justincormack any idea what this `readdirent` things is about?
