### ISSUE TITLE
Docker failed to start

### ISSUE THREAD

**Issue by daemonofchaos** [docker/for-mac#1560]
### Expected behavior
Docker daemon to start without error

### Actual behavior
Received message that Docker was unable to start

### Information

  - Diagnostic ID 4A4837D0-D8B8-474B-A6F4-C7E1A9EB7506

### Steps to reproduce the behavior

  1. Login to mac and will receive error message that Docker was unable to start.

**Comment by ebriney** [comment]
Hi Jim. It seems that the moby disk has been corrupted but you have many others errors.
Is it working again when you `reset to defaults`?

**Comment by EugenMayer** [comment]
@ebriney its the usual thing when you use https://gist.github.com/EugenMayer/55fe8c7a3e8c27ecf6a9a52f58a64be8 .. if you irregulary shutdown you mac, sleep / battery issue, the FS is corrupted every single time. 

Reset helps, but its really anoying to get there if the error modal blocks you. You have to be fast to get there, before it shows up. Please make the error modal not "modal"

**Comment by ebriney** [comment]
In the next version you will a `reset to defaults` button in the modal!
It is already in the edge channel version.

**Comment by EugenMayer** [comment]
@ebriney you are aware, that the fix does no longer really work for edge, right? There is no on-flush and as far as i can see, edge is performing a lot worse as stable + the fix.

Any thoughts?

**Comment by ebriney** [comment]
@EugenMayer : Why edge is worse than stable? We plan to bump stable with the current edge so it's good to know if there is some blockers.
Can you give me some feedbacks?

**Comment by ebriney** [comment]
@djs55 Do we still have the on-flush on edge or must we use the new mount attributes?

**Comment by ebriney** [comment]
Humm, it concerns qcow disk so there is no way to add mount attributes, sorry.

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
