### ISSUE TITLE
SCTP kernel support in the HyperkitVM

### ISSUE THREAD

**Issue by razaborg** [docker/for-mac#1561]
I noticed the absence of the kernel SCTP support in the Docker for mac Hyperkit VM running on Alpine, which prevent SCTP to work in any containers...
(whereas other SCTP-related functionnalities are enabled in the kernel...)

### 1. a pull-request related to linuxkit kernel
After looking for a solution, I finally submited a PR in the linuxkit repo: https://github.com/linuxkit/linuxkit/pull/1675

They (cc @avsm ) suggested me to open an issue here : 
> @razaborg this LGTM, but if you need it in a Docker for Mac release could you also open up an issue on https://github.com/docker/for-mac/issues and reference this one? This way we can update that issue whenever it actually ships in a release downstream of Docker for Mac.

### 2. SCTP support in port expose functionnality

And I take the opportunity to ask you about the SCTP support in docker : 
The architecture of Docker for Mac prevent us to do traffic scan between all containers directly from the host (docker0) as we can do on a Linux-based system.
The most given solution consist in exposing ports directly to the host.

But port exposure functionnality does not support SCTP protocol (only tcp/udp).
- So my first question is  : Why ? 
- and secondly : Could it be an upcoming feature ?

PS: I'm not really aware of the issue process here, so if you prefer me to split this issue, just say it :)

**Comment by ebriney** [comment]
Thanks Razaborg. I think the reason is that we can add flags when launching the vm with hyperkit in D4M but I'm not an expert on that part :)  (cc @djs55) 
An issue has been added in Docker for Mac repo.

**Comment by djs55** [comment]
The network traffic in Docker for Mac is tunnelled to the host and proxied at the application level through the host's socket API -- the goal is to make it look like traffic originates from the Docker application on the host, so that it is processed by VPN software reliably. There is proxy code for UDP and TCP but no SCTP.

I'd like to understand your use-case a little more. Would it be enough to expose a UDP port and tunnel the SCTP over it?

**Comment by razaborg** [comment]
> I'd like to understand your use-case a little more. Would it be enough to expose a UDP port and tunnel the SCTP over it?

You mean establish an UDP socket and send the SCTP traffic into the UDP data field ? Or something like an over-UDP VPN ? That seems to be an overkill fix, don't you think ?

My use-case is the following: I use Docker for Mac and need to implement a telco test lab (using Diameter protocol, which uses SCTP as transport layer), so my containers need to exchange using the SCTP transport protocol (I fixed this point by enabling the option in the hyperkit vm kernel). 
And now, to analyze easily what's going on between my containers, I need to be able to do traffic scan on a bridge interface (or, either, expose the SCTP traffic to the host).

I can scan the bridge interface in CLI directly inside the Hyperkit VM, but it's really uncomfortable, and anyway, I think a full SCTP support for Docker would be great (especially for telco needs) :)

**Comment by faizann** [comment]
I have been also waiting for a while now for SCTP support. SCTP support would allow telco products to be put on docker.
