### ISSUE TITLE
2C2CE23F-8FF5-44FA-9DA8-766714A8D4D1

### ISSUE THREAD

**Issue by yhgstudy0** [docker/for-mac#1563]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @yhgstudy0, can you give a description of your problem? There is nothing suspicious in the report you provide.

**Comment by yallop** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
