### ISSUE TITLE
ptrace disabled

### ISSUE THREAD

**Issue by rappdw** [docker/for-mac#1564]
### Expected behavior
Able to enable ptrace with either `--privileged` or `--sercurity-opt=seccom:unconfied` or `--cap-add SYS_PTRACE`

### Actual behavior
ptrace remains disabled regardless of options tried

### Information

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/734969CB-B2F1-42D5-9B22-BCFEDBF605D6/20170424-192201.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

With this Dockerfile: 
```
FROM python:3.6.1

RUN apt-get update && apt-get install -y \
        gdb \
    && apt-get clean \
    && rm -rf /var/tmp /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && pip install git+git://github.com/lmacken/pyrasite.git@d0c90ab38a8986527c9c1f24e222323494ab17a2#egg=pyrasite

ENTRYPOINT ["pyrasite", "--list-payloads"]
```
  1. `docker build -t no_ptrace .`
  2. run one of the following:
* `docker run --security-opt=seccomp:unconfined no_trace`
* `docker run --privileged no_trace`
* `docker run --cap-add SYS_PTRACE no_trace`

All forms result in:
```
WARNING: ptrace is disabled. Injection will not work.
...
```

**Comment by jedbrown** [comment]
I'm not a Mac user, but trying to solve exactly this problem for a student. These options work on Linux.

**Comment by jamshid** [comment]
Same problem here, I guess a new issue has to be created since this one auto-closed?
/remove-lifecycle stale
