### ISSUE TITLE
Docker for Mac 100% CPU consumption

### ISSUE THREAD

**Issue by oscarrenalias** [docker/for-mac#1568]
### Expected behavior

CPU consumption is very low, or zero, when no containers are running.

### Actual behavior

Docker for Mac is currently consuming 100% of CPU (1 full core) on a 4-core mid-2014 Retina MBP 15". There are no containers running, and even old containers that were in stopped status have been removed. 

### Information

Diagnostic ID DF2FCECB-CD24-4209-BF81-04FCDC2D55D3.

### Steps to reproduce the behavior

No clear steps available. Docker for Mac has been running for some time, always successfully, but a couple of hours ago started to show high CPU consumption. Tried restarting but the problem does not go away.

**Comment by zjjw** [comment]
I think I am having the same problem. 

I am running OSX Yosemite (10.10.5) on a mid-2014 MBP, and whenever I start docker the CPU is more or less immediately pinned at 100% with no containers running. The process primarily consuming the CPU is `com.docker.hyperkit`.

Docker version 17.03.1-ce, build c6d412e

Diagnostic ID: 9E2A24E0-970D-4B07-97E8-3CB72F9ABF7F

**Comment by egglang** [comment]
I am also having the same on Mid-2012 MBP.

**Comment by mizuluffyhwang** [comment]
I have the same issue with my 2016 MBP 15 with touch bar. Had a look at the process list, find "**Hyperkit**" had more than 200% CPU utilization even without any workload.

**Comment by AlbertoBarba** [comment]
Same issue on my mid 2014 MBP 15

**Comment by wolraich** [comment]
Same issue on mid-2012 MBP 15, El Capitan 10.11.6.

With no containers running, com.docker.hyperkit bursts over 150% cpu, and com.docker.osxfs runs up to 90%.

**Comment by wolraich** [comment]
Follow-up: I upgraded to Sierra 10.12.5 but still see the issue. Com.docker.hyperkit jumped us high as 298%. I try to avoid using docker with battery because it drains very quickly.

**Comment by jedie** [comment]
I can confirm this, and many other users, too, see: many "confirm" posts here: https://forums.docker.com/t/com-docker-hyperkit-up-cpu-to-340/13057

or:
https://github.com/moby/hyperkit/issues/58
https://github.com/docker/for-mac/issues/1759

Any work-a-round?

**Comment by aurea-vijay** [comment]
Force killing the hyperkit process and restarting docker seems to have fixed the problem for me.

YMMV.

**Comment by akimd** [comment]
Please try a more recent version of Docker for Mac.

**Comment by glyph** [comment]
I have this same issue.  Not only does it use 100% CPU and murder my battery, it also seems to be preventing sleep, causing my laptop to get very hot and then hibernate with the lid closed.

**Comment by glyph** [comment]
Diagnostic ID: 1D83BF2B-37CD-4516-9408-59A7F75F39AB/20180527-230130

**Comment by henryL1N** [comment]
Same. Version 18.03.0-ce-mac60 (23751)
Diagnostic ID: A94EC7C5-B2D2-4CE5-A6F6-50BDFCBB8076

**Comment by rrdlpl** [comment]
its 2020 is there any fix for this?
