### ISSUE TITLE
Docker for mac not starting

### ISSUE THREAD

**Issue by iamShantanu101** [docker/for-mac#1571]
### Expected behavior
Docker for mac should start after installing.

### Actual behavior
Docker for mac is stuck on "Docker starting.."
OS: MacOs Sierra version 10.12.2

**Comment by arthurpsmith** [comment]
Hey @iamShantanu101 - I'm seeing the same thing, what was your solution? I had docker-machine from a year or so ago, but it wasn't working after I updated to Sierra. So I downloaded Docker for Mac and it's been stuck on "Docker starting..." for several hours now - ???

**Comment by iamShantanu101** [comment]
@arthurpsmith Well, I just restarted the system and it worked. Which one are you installing? Stable or Edge?

**Comment by arthurpsmith** [comment]
I had stable installed; I just updated to edge and the problem seems to be fixed (Docker is Up and Running after just a minute). A little annoying though.
