### ISSUE TITLE
Docker-compose slow (and diagnostics slow)

### ISSUE THREAD

**Issue by dodalovic** [docker/for-mac#1575]
When I run Diagnose & Feedback - takes 7,8 minutes to complete.

Diag ID: `F9C6EB96-A5D3-4B11-99B0-832CE92E21FC`

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/F9C6EB96-A5D3-4B11-99B0-832CE92E21FC/20170427-172517.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

[20170427-172517.tar.gz](https://github.com/docker/for-mac/files/962103/20170427-172517.tar.gz)

MacOS Sierra 10.12.4 (16E195)

**Comment by EugenMayer** [comment]
```
docker prune images
docker prune container
docker prune volume
```
Mainly the reason behind that is the amount of images you have. If you pull updated :latest one, the old is kept with a no-tag and needs to be cleared. You can also reset docker, will have the same effect.

In addition, if you are actually on stable, use https://gist.github.com/EugenMayer/55fe8c7a3e8c27ecf6a9a52f58a64be8 - it will restart you docker for mac - then you should see a huge boost.

**Comment by dodalovic** [comment]
Thanks, will try these out!
