### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 15

### ISSUE THREAD

**Issue by robmarkcole** [docker/for-mac#1579]
### Expected behavior

Uneventful launch of Mac

### Actual behavior

Fatal error popup on Mac boot. Docker runs when manually launched

### Information

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/1F0AE7AD-B89C-469F-83B7-DC632706DE92/20170430-062554.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/robincole/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/robincole/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/robincole/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/robincole/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/robincole/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Restarted my Mac, error on boot

**Comment by cjcjameson** [comment]
@larham @melanieplageman @chibin we just saw a similar issue:

- Same high level error message
- Exit code 1, not 15
- Same version of Docker for Mac, and same version of macOS Sierra
- Didn't get the logs
- Happened in the "run of play", not specifically at startup
- Might be connected with us sharing a volume into a container?
- Nuked our user's whole home directory `/Users/username/*`

**Comment by dsheets** [comment]
@cjcjameson to be clear, did your user's home directory disappear or did you delete it? Do you think Docker for Mac caused data loss?

**Comment by cjcjameson** [comment]
@dsheets thanks for following up. Our bad -- not a Docker-side issue.

**Comment by CatinhoCR** [comment]
This just recently happened to me after I was trying to fix an external hard drive and killed some processes from the terminal, it seems I killed daemon and haven't found a way to fix this. Will probably re install to see if it helps.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
