### ISSUE TITLE
Corrupted installation after issuing a docker-compose restart

### ISSUE THREAD

**Issue by madmax76** [docker/for-mac#158]
### Expected behavior

Docker to start normally, but after executing

# docker-compose restart

my system hang and rebooted.

### Actual behavior

after executing

# docker-compose restart

my system hang and rebooted.

Running any containers or apps gives the following error:
docker: Error response from daemon: Bad response from Docker engine.

### Information

Diagnostic ID: 0EC6304D-EECA-40FA-A211-3A2DC83E7ED5
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. docker-compose restart

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in 0EC6304D-EECA-40FA-A211-3A2DC83E7ED5/20160806-182809.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  6 18:21:40 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Mirage-block error: Unknown write: End_of_file at file /Users/max/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 offset 6209777664 with buffer of length 20480
Aug  6 18:21:40 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  6 18:21:40 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-31170560")
Aug  6 18:21:40 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  6 18:21:41 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  6 18:21:41 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  6 18:21:42 mbp-2 Docker[com.docker.driver.amd64-linux][869] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
```
