### ISSUE TITLE
E19D356A-C3AC-4257-A8AF-70019F8A7591

### ISSUE THREAD

**Issue by KitamuraTakashi** [docker/for-mac#1581]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by balrajsingh** [comment]
Could you describe the symptoms you are experiencing.

**Comment by guillaumerose** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
