### ISSUE TITLE
CA6B66D5-8C95-40E1-B6EE-D80E1F24E15A

### ISSUE THREAD

**Issue by tdeshu** [docker/for-mac#1583]
### Information

CA6B66D5-8C95-40E1-B6EE-D80E1F24E15A

**Comment by balrajsingh** [comment]
Could you describe the symptoms you are experiencing.

**Comment by guillaumerose** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
