### ISSUE TITLE
Disable credsStore?

### ISSUE THREAD

**Issue by olalonde** [docker/for-mac#1584]
I'm trying to follow the following instructions for K8s: https://kubernetes.io/docs/concepts/containers/images/#bypassing-kubectl-create-secrets

However, I'm not able to complete the instructions because my docker config looks like this:

```json
{
        "auths": {
                "MY_AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com": {}
        },
        "credsStore": "osxkeychain"
}
```

I was wondering if it was possible to disable the credsStore so that I can get the old style config file?

Repost from: https://github.com/moby/moby/issues/32733#issuecomment-298803697

Using this as a workaround: https://gist.githubusercontent.com/olalonde/263e33b50e8c7a8fa98bc0f42a07ba58/raw/c7666a101d5cfe0403ffc4f5e8dfcf258c51c822/apply-registry-secret.sh

**Comment by balrajsingh** [comment]
If you just want to use the old style config you could do a `docker login` on a linux machine and copy the config.json file over to the mac (if you don't have easy access to a linux machine, use the docker in docker image - docker:dind, and do it all on the mac itself).

Note that the old style config will have your `username:password` base64 encoded and inserted directly in the config.json file, so please be aware of the risk.

**Comment by olalonde** [comment]
Yes... or use my workaround.

**Comment by charlesmims** [comment]
python3 -c "import base64; print(base64.b64encode(b'username:password').decode('utf-8'))"

**Comment by aayars** [comment]
There really needs to be a non-hacky way to turn this off. Keychain integration is undesirable in many situations.

**Comment by wuestkamp** [comment]
So I solved this on OSX by disabling the keychain password storage:

1. `rm ~/.docker/config.json`
2. in Docker for Mac preferences, untick "Securely store Docker logins in macOS keychain"
3. restart Docker for Mac
4. `docker login`

Or for glcoud and pushing to gcr:
`gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io`

now your `~/.docker/config.json` should contain base64 encoded passwords. Working, not safe though!

If someone gets the keychain storage to work that would be nice...

**Comment by eselkin** [comment]
> So I solved this on OSX by disabling the keychain password storage:
> 
> 1. `rm ~/.docker/config.json`
> 2. in Docker for Mac preferences, untick "Securely store Docker logins in macOS keychain"
> 3. restart Docker for Mac
> 4. `docker login`
> 
> Or for glcoud and pushing to gcr:
> `gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io`
> 
> now your `~/.docker/config.json` should contain base64 encoded passwords. Working, not safe though!
> 
> If someone gets the keychain storage to work that would be nice...

No longer seems to work, osxkeychain remains checked and rechecks itself when attempting login again even on command line.

**Comment by obedparla** [comment]
For me deleting the line containing the `credsStore` and then logging back in `docker login` fixed the issue for me. (After disabling it on the preferences and restarting Docker)

**Comment by eselkin** [comment]
That did not work for me... after multiple attempts at every conceivable way to login, close, restart... etc... it always reselected it. 2.1.0.1 fixed this issue.

**Comment by ericvicenti** [comment]
[New issue here](https://github.com/docker/for-mac/issues/4100), because this one was autoclosed..
