### ISSUE TITLE
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 0.0.3.179:443: connect: invalid argument.

### ISSUE THREAD

**Issue by dasu126** [docker/for-mac#1585]
### Expected behavior
docker run hello-world
### Actual behavior
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 0.0.3.179:443: connect: invalid argument.
See 'docker run --help'.
### Information
Diagnostic ID
F7DDFDC5-56BB-4292-B211-A40A60CEEBEB

**Comment by aviadpines** [comment]
+1 Encountering the same issue
