### ISSUE TITLE
When pulling the "sath89/oracle-12c" image, I get "no space left on device"

### ISSUE THREAD

**Issue by jsi** [docker/for-mac#1587]
### Expected behavior
When I do:
`docker pull sath89/oracle-12c`
The image should download without problems.

### Actual behavior
```
>docker pull sath89/oracle-12c
Using default tag: latest
latest: Pulling from sath89/oracle-12c
863735b9fd15: Pull complete 
4fbaa2f403df: Pull complete 
44be94a95984: Pull complete 
a3ed95caeb02: Pull complete 
b8bc6e8767ee: Pull complete 
c918da326197: Pull complete 
448e1619a038: Pull complete 
faadd00cf98e: Downloading 2.768 GB/2.768 GB
88db86b58dda: Download complete 
write /var/lib/docker/tmp/GetImageBlob207148979: no space left on device
```

When I retry, I get a slightly different error message:
```
...
faadd00cf98e: Extracting 2.768 GB/2.768 GB
88db86b58dda: Download complete 
failed to register layer: Error processing tar file(exit status 1): write /u01/app/oracle-product/12.1.0/xe/jlib/orai18n-collation.jar: no space left on device
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu.
  -- Diagnostics does not show anything wrong.
  -- Diagnostics ID: 799276A0-12A2-4437-9E6D-1D0FDAA23B14
  - I have deleted all tangled volumes and unnecessary images.  There about 1.6Gb of images in the installation, but 130Gb of disk free on the harddisk.
  - Docker have 8Gb of memory available for use.

Is there some other secret place where the disk fills up that I can clean up?

### Steps to reproduce the behavior

`docker pull sath89/oracle-12c`

**Comment by jsi** [comment]
There seems to be different error messages each time, but allways "no space left on device".

**Comment by djs55** [comment]
Looking inside the VM I see:
```
$ cat df\ -h.stdout 
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     3.9G    153.0M      3.7G   4% /
tmpfs                   797.3M    208.0K    797.1M   0% /run
cgroup_root              10.0M         0     10.0M   0% /sys/fs/cgroup
dev                      10.0M         0     10.0M   0% /dev
shm                       3.9G         0      3.9G   0% /dev/shm
/dev/vda1                18.2G     16.6G    609.9M  97% /var
tmpfs                   464.8G    333.5G    131.0G  72% /tmp
tmpfs                     3.9G    168.0K      3.9G   0% /Database
osxfs                   464.8G    333.5G    131.0G  72% /Users
osxfs                   464.8G    333.5G    131.0G  72% /Volumes
osxfs                   464.8G    333.5G    131.0G  72% /tmp
osxfs                   464.8G    333.5G    131.0G  72% /private
osxfs                   464.8G    333.5G    131.0G  72% /host_docker_app
/dev/vda1                18.2G     16.6G    609.9M  97% /var/lib/docker/aufs
```
-- in particular your `/dev/vda1` seems very small (18.2G) and it's still using `aufs` rather than `overlay2`. A fresh install of Docker for Mac would create a 64G `overlay2` filesystem for containers. Do you remember when you installed, whether you selected the "import from toolbox" option? If you had a toolbox/boot2docker VM with an 18G disk, it could have been copied.

This is related to #1512 -- confusion when the VM runs out of disk space

It should be possible to dynamically increase the disk size, although there is no UI element for this:
```
$ cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux
$ git checkout master
Already on 'master'
$ git reset --hard
HEAD is now at 5c4e9cc Setting certificates
$ echo -n 131072 > disk/size
$ git add disk/size 
$ git commit -s -m 'Resize disk to 128GiB'
[master bb07286] Resize disk to 128GiB
 1 file changed, 1 insertion(+)
 create mode 100644 com.docker.driver.amd64-linux/disk/size
```
The VM should reboot and then:
```
$ docker run alpine df -h /var
Filesystem                Size      Used Available Use% Mounted on
overlay                 125.7G      4.8G    114.6G   4% /
```
With this much free space available I was able to `docker pull sath89/oracle-12c` as expected.

**Comment by jsi** [comment]
Wow.  Thanks for a quick response.  😊

That first command failed.  I have the folder `~/Library/Containers/com.docker.docker/Data/database/`, but it is empty.  Do you see that folder in the uploaded diagnosis?  I have removed several images after I did the Diagnose, could that have removed the "com.docker.driver.amd64-linux" folder?

I did think about uninstalling Docker to reinstall it, but that does not seem to be an easy operation.

**Comment by jsi** [comment]
Actually, `~/Library/Containers/com.docker.docker/Data/database/` is not completely empty.  It contains a `.git` folder, but the project is not connected to a remote repository anymore:

Still, checking out master seems to have helped:
```
jsi>ll
total 0
drwxr-xr-x   3 jsi  staff  102 17 okt  2016 ./
drwxr-xr-x  24 jsi  staff  816  4 mai 10:28 ../
drwxr-xr-x   7 jsi  staff  238 17 okt  2016 .git/
jsi>git checkout master
Already on 'master'
jsi>git status
On branch master
nothing to commit, working directory clean
jsi>ll
total 0
drwxr-xr-x   4 jsi  staff  136  4 mai 14:31 ./
drwxr-xr-x  24 jsi  staff  816  4 mai 10:28 ../
drwxr-xr-x   9 jsi  staff  306  4 mai 14:31 .git/
drwxr-xr-x  22 jsi  staff  748  4 mai 14:31 com.docker.driver.amd64-linux/
```

After running the instructions you gave, then waiting a minute, I still get:

```
jsi>docker run alpine df -h /var
Filesystem                Size      Used Available Use% Mounted on
none                     18.2G     14.7G      2.5G  86% /
```

**Comment by djs55** [comment]
Sorry for the buggy instructions -- I forgot the `git checkout master` was needed to create the `com.docker.driver.amd64-linux` directory.

I think at this point the easiest thing to do is to remove the file containing the images and containers and let it create a fresh empty one from scratch. If you run:
```
rm -f ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 
```
and then restart the app it should re-initialise.

Unfortunately this means that containers and images will need to be rebuilt. If there are some you would like to keep they could either be pushed to a remote registry and then re-pulled afterwards, or perhaps you could use `docker export` and then `docker import` afterwards-- I'm sorry for the inconvenience.

Thanks again for your report!

**Comment by jsi** [comment]
Nice!  -  That did it:
```
Filesystem                Size      Used Available Use% Mounted on
overlay                 125.5G      1.6G    117.4G   1% /
```

And pulling the oracle-image also succeeded!

Thank you so much for your help, Dave!  -  Made my day!

**Comment by djs55** [comment]
I'm glad it's working properly now.

I'll close this issue but feel free to open another if something else goes wrong.

Thanks for using Docker for Mac!
