### ISSUE TITLE
Docker daemon restarting under load

### ISSUE THREAD

**Issue by Woodham** [docker/for-mac#1588]
### Expected behavior

With two docker containers running using docker-compose, sometimes when one is under load, the whole of docker restarts.

### Actual behavior

Docker should not restart.

### Information

Diagnose ID: 71F076C7-36D7-4EF9-9B5D-5A9E1CF1F22B

Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/71F076C7-36D7-4EF9-9B5D-5A9E1CF1F22B/20170504-172245.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Can't reliably reproduce.

**Comment by yallop** [comment]
Looking at the logs, the symptoms are somewhat similar to #1110 and #1176, i.e.:

```
exit_reason	48
```
