### ISSUE TITLE
Docker App is not working

### ISSUE THREAD

**Issue by bstarr322** [docker/for-mac#1589]
### Expected behavior
I want to start/run Docker App.
### Actual behavior
Docker App can not be started.
### Information
Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/9D7A14E7-0246-4813-BE0D-3E4007648727/20170504-200135.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/n2me/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/n2me/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/n2me/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/n2me/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/n2me/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/n2me/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/n2me/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/n2me/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

VirtualBox version is v5.3.x.
### Steps to reproduce the behavior

  1. I tried to install Docker Stable and Edge.
  2. I tried to start the Docker App, but failed, so opened this issue.

Thank you in any advance.

**Comment by balrajsingh** [comment]
@bstarr322 : From you report it looks like your CPU does not have the necessary support to run Docker 4 Mac.

Please see the system requirements in https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install for more information.

If you think your Mac meets these requirements could you provide hardware details including the exact version of your machine.

**Comment by bstarr322** [comment]
Thank you @balrajsingh for the reply.
iMac (21.5-inch, Late 2009)
Processor 3.06 GHz Intel Core 2 Duo
Memory 8GB 1067 MHz DDR3
Startup Disk     SYSTEM
Graphics     NVIDIA GeForce 9400 256MB
Serial Number     W8952DVK5PC

Looking forward to the solution.

Best

**Comment by thaJeztah** [comment]
@bstarr322 ;

> Mac must be a 2010 or newer model, with Intel’s hardware support for memory management unit (MMU) virtualization; i.e., Extended Page Tables (EPT) and Unrestricted Mode.

Looks like your hardware is too old for Docker for Mac to run. As an alternative, you can install Docker Toolbox, which uses VirtualBox to run the Docker daemon in https://www.docker.com/products/docker-toolbox

**Comment by bstarr322** [comment]
@thaJeztah 
Thanks for your detailed info. I have tried it with new MAC and it worked well, 
Thank you !
