### ISSUE TITLE
Docker push is hanging.

### ISSUE THREAD

**Issue by briprowe** [docker/for-mac#159]
### Expected behavior

The command `docker push` completes.

### Actual behavior

It actually hangs:

```
$ docker push <tag>
The push refers to a repository [docker.io/<tag>]
188671646eb7: Pushing [===>                                               ] 984.1 kB/14.07 MB
188671646eb7: Pushing [========>                                          ] 2.295 MB/14.07 MB
6049ea1266c7: Pushing [=>                                                 ] 5.386 MB/140.1 MB
4fe15f8d0ae6: Pushing [============================>                      ] 2.777 MB/4.799 MB
4fe15f8d0ae6: Pushed
```

### Information

Diagnostic ID: CDF0A6F9-022C-467C-82F8-40293E796CC9
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. `docker push <tag>`

**Comment by mchiang0610** [comment]
Merging with #281
