### ISSUE TITLE
Docker for Mac not starting up

### ISSUE THREAD

**Issue by daviddumonde** [docker/for-mac#1590]
### Expected behavior
Docker for Mac starting up
### Actual behavior
Docker for Mac failing to start up, and showing error message:
com.docker.osx.hyperkit.linux failed to start Exit code 1
http://drp.mk/i/QzgqjN59jP

### Information
NOTE: I'm posting this as a separate issue because I think it is related to the fact that I changed my username on MacOS earlier today, which is probably different than other reports.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

`Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/D83B2490-3D0A-4ED7-993F-7F2891F14492/20170504-155334.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ddumonde/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ddumonde/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ddumonde/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ddumonde/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/ddumonde/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ddumonde/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
`

### Steps to reproduce the behavior

1. Earlier today I changed the username on my Mac following these directions: https://support.apple.com/en-us/HT201548
2. I'm running macOS Sierra 10.12.4 (16E195) on a MacBook Pro (Retina, 13-inch, Early 2015).
3. Now when I launch Docker for Mac, I get the error above.
4. I tried deleting Docker for Mac, and downloaded the stable release from https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac
5. The result is the same error.

Again, I'm hoping you can help resolve this because the username change makes me think that is the cause in this case, but I don't know how to fix this issue relative to D4M.

Thanks.

<img width="594" alt="screenshot 2017-05-04 15 46 57" src="https://cloud.githubusercontent.com/assets/1297037/25725041/de10968c-30e3-11e7-9018-84b971e242ef.png">

**Comment by EugenMayer** [comment]
Start it, reset it before the error shows up.. so start and quick prefrences reset, reset. You need to have this done before the modal pops up. Confirm it.

After it resets things will be back to normal.

Reasons: filesystem corruption due to the new fsync mode - this will happen to you a lot more often then you find it funny ( and to me )

**Comment by daviddumonde** [comment]
Thank you. That worked, but wow that’s tough to do!

David
