### ISSUE TITLE
Incompatible CPU detected.  Docker requires a processor with virtualization capabilities.

### ISSUE THREAD

**Issue by oprisk** [docker/for-mac#1591]
### Expected behavior
Successful installation of docker
Hardware: iMac 11.3   Mid 2010  Intel Core i7, 20Gb Memory
Software: MacOS Sierra v10.12.5 Beta (16F71b)  
Note: same issue with v10.12.5 non-beta

### Actual behavior
Installation Error: 
Incompatible CPU detected.
Docker requires a processor with virtualization capabilities.

### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.5 (build: 16F71b)
logs: /tmp/45EDD60D-8698-4E46-84B1-2B3480B3E93E/20170504-183626.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/paolo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/paolo/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/paolo/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/paolo/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/paolo/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/paolo/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. Download Docker.dmg
  2. run installation - move docker to /Applications
  3. run /Applications/docker.app
  4. Fatal Error reported

**Comment by balrajsingh** [comment]
@oprisk: From you report it looks like your CPU does not have the necessary support to run Docker 4 Mac.

Please see the system requirements in https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install for more information.

If you think your Mac meets these requirements could you provide hardware details including the exact version of your machine.

**Comment by gtardif** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
