### ISSUE TITLE
Unable to detach from a container

### ISSUE THREAD

**Issue by viveknangal** [docker/for-mac#1598]
### Expected behavior
Should be able to exist the container on pressing ctrl P+Q
### Actual behavior
On being attached to the Detached container, unable to exit the container.
### Information

  -  I'm running a Docker version(Docker version 17.03.1-ce, build c6d412e) on mac ,& i m facing an issue on exiting the container on attaching it manually , Steps to reproduce are mentioned below

### Steps to reproduce the behavior

  1. Create a docker file & script (as enclosed)
`FROM ubuntu 
  MAINTAINER  test@gmail.com 
 WORKDIR /home/app/   
 COPY test.sh /home/app/ .  
  EXPOSE 8080
 CMD ./test.sh`

test.sh script as follows:-

`while(1>0)
do
date
sleep 3
done`

  2.  Run the build command to create an Image (eg: docker build -t ubuntu_16.04 .)
  3.  Run the container in detached mode (eg: docker run -d ubuntu_16.04)
   4. Attach to the container ( eg: docker attach <Container_id>)
  5. Once attached to the container, able to see the output of script & unable to exit the container even on pressing ctrl P+Q .

**Comment by viveknangal** [comment]
any update on this .. pls suggest

**Comment by rajat1saxena** [comment]
I am also facing the same issue.

**Comment by BrendonW** [comment]
Have you guys tried to kill the attach command from another window? Could your signals be going to the wrong place?

**Comment by viveknangal** [comment]
kill from other window is able to kill the attach command but that is not the point . we should be able to detach from the container when attached ..

**Comment by shtratos** [comment]
Posted a workaround here: https://stackoverflow.com/a/48957587/7417402

```
docker attach --sig-proxy=false <Container_id>
```

Then `Ctrl+C` will detach from container without killing it.

**Comment by oh54** [comment]
Had the same issue on RHEL 7.5 albeit on an older Docker version (1.12.6).

Workaround by shtratos worked fine.

**Comment by masterkain** [comment]
same issue, iTerm2 on Mac connected to a remote ubuntu server via ssh which is running docker, once I attach to some container I can't detach. will try sig-proxy

**Comment by elielr01** [comment]
Same issue here. The workaround of `--sig-proxy=false` works for me tho.

**Comment by mikebranski** [comment]
Keeping this alive as it is still occurring with Docker for Mac Version 2.0.0.3 (31259) in both iTerm2 (Build 3.2.8) and the built-in Terminal (Version 2.9.5 (421.2)).

/remove-lifecycle stale

**Comment by IAMtheIAM** [comment]
`--sig-proxy=false` is the solution - but it shouldn't be needed IMO - it should default to FALSE and be an option to turn TRUE

**Comment by pirate-matt** [comment]
`--sig-proxy=false`, then `ctrl-c` is functioning as a workaround.

But I'm curious, has anyone uncovered why the standard isn't working on OSX? Is `ctrl+p ctrl+q` bound to something else, or is this a deeper problem?
