### ISSUE TITLE
Docker Mac Error

### ISSUE THREAD

**Issue by alexncus** [docker/for-mac#16]
### Information

Diagnostic ID: C35AE4C4-DD0E-4544-84E6-7D7E5259D786
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/master/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Please can you provide the missing information:
- Expected behavior
- Actual behavior
- Steps to reproduce
