### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 1

### ISSUE THREAD

**Issue by isalomanto** [docker/for-mac#1600]
**Expected behavior**
Run docker on Mac 10.12.4

**Actual behavior**
Unable to start even after uninstalling/reinstalling and trying:
`rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`

![screen shot 2017-05-08 at 17 48 05](https://cloud.githubusercontent.com/assets/7438173/25812655/41735e9a-3417-11e7-8a56-da2a1036fbf0.png)

**Information**

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu:
```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/0BA30333-4C24-4438-ACF6-DC224384CCFE/20170508-174609.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/isabella/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/isabella/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/isabella/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/isabella/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/isabella/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/isabella/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

```
- Diagnostic ID:
**0BA30333-4C24-4438-ACF6-DC224384CCFE**

**Steps to reproduce the behavior**

  1. Start Docker for Mac

**Comment by isalomanto** [comment]
Well for the time being I went back to an older version  [https://download.docker.com/mac/stable/1.12.6.14937/Docker.dmg](https://download.docker.com/mac/stable/1.12.6.14937/Docker.dmg) as suggested in #1120

**Comment by 24king** [comment]
`rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 `

works for me well, thank you

**Comment by Ahmed-Mosharafa** [comment]
Rest Docker to Factory settings: Whale icon -> Preferences -> Reset -> Reset to factory defaults.
This worked for me!

**Comment by gsafcik** [comment]
Unfortunately, I also had to factory reset as @Ahmed-Mosharafa points out above.

**Comment by lqpLee** [comment]
@24king f**k you，You let me lose all the images and the container

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
