### ISSUE TITLE
Docker registry timeout

### ISSUE THREAD

**Issue by c0nscience** [docker/for-mac#1601]
### Expected behavior
Pulling an image should download all layers and extract them.

### Actual behavior
Receiving an connection timeout e.g. `docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

### Information
Diagnostics ID: `3A52BFB0-C6E9-46B0-A4F8-2025D5CB051E`
Diagnostics Output:

```
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
I also tried everything from here: https://github.com/docker/for-mac/issues/1317 and from my other ticket here: https://github.com/moby/moby/issues/32270

Environment:
macOS 10.12.4
```
~ » docker version                                                                                                                                                 
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Steps to reproduce the behavior

  1. docker pull hello-world

**Comment by c0nscience** [comment]
Ok I have no idea why, but installing the current edge version:
```Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
And it works just as a couple month ago.

**Comment by semmasodo** [comment]
Hey, same Problem for Windows. Some people wrote to delete dns 8.8.8.8 from resolve.conf
But i added this dns to my Settings (right click on docker icon -> Network -> Set DNS to Fixed (8.8.8.8)
Perharps you can find a similiar option on linux.

**Comment by razaborg** [comment]
I had the same issue and solved it by forcing the google DNS servers in the daemon config [as advised here](https://github.com/moby/moby/issues/32270#issuecomment-290829987)
And disabling the IPv6 in my network perferences (switched the config from automatic to manual)

Even if I'm pretty sure that IPv6 is the cause of the problem, forcing the daemon to use  Google's DNS can't be a bad thing...

**Comment by MKhalusova** [comment]
Hi @c0nscience! I've had the same issue, and was able to solve it by adding nameserver 8.8.8.8 to resolv.conf. Hope it helps.

**Comment by thalesfsp** [comment]
I've tried many solutions and what @razaborg pointed out **is the correct one**. I also suggest adding `8.8.8.8` to your network configuration. Don't do what @MKhalusova said, for this reason:

```
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
```

The correct way is `System Preferences` -> `Network` -> `Wi-fi` (or whatever are you using) -> `Advanced` -> `DNS` and add there.

**Comment by sohailalam2** [comment]
Just FYI if someone stumbled upon this issue and was running Docker on *Windows* (like myself), then 

`Open Network and Sharing Center` -> `select the correct network` -> `Properties` -> `Select TCP/IPv4` -> `Properties` and add 8.8.8.8 and 8.8.4.4 to the DNS server addresses

Adding Google DNS to the network TCP/IP v4 properties resolves the issue.

**Comment by sztomi** [comment]
I would argue that the above is just a workaround and the real issue should be addressed. I had other DNS entries and browsers were able to resolve domain names, unlike docker.

**Comment by DrStrangepork** [comment]
I have been having a similar problem with AWS ECR for months. DNS is not the issue: the ECR DNS name is resolvable using our private and the public nameservers, and adding DNS IP addresses to either /etc/resolve.conf or the dockerd config don't resolve the problem.

**Comment by argiris-mat** [comment]
I'm facing the same issue and DNS entries does not solve it for me. I have a registry on artifactory behind an AWS ELB.

![screen shot 2018-04-03 at 17 31 15](https://user-images.githubusercontent.com/34026614/38263327-bb657f54-3767-11e8-90de-12b9534b4de7.png)

API endpoint seems to work as it suppose to do. My osx has the google dns entries.

![screen shot 2018-04-03 at 17 51 05](https://user-images.githubusercontent.com/34026614/38263355-ce843238-3767-11e8-8fc4-652b906a4a5b.png)

Same behaviour through an ubuntu box.

**Comment by iameronmosele** [comment]
i have the same issues as @argiris-mat

**Comment by Nolli9** [comment]
I am having the exact problem...talk about a waste of valuable time. Switched between stable and edge still problems...DNS 8.8.8.8 doesn't resolve the issue either.
Docker for Mac: version: 18.04.0-ce-rc2-mac61 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/9490201B-9F6B-41DA-8A8D-07AEA0A8C2F6/20180412-093012.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs

**Comment by osvald** [comment]
I'm having the same problem with version 18.*, latest one i tried:
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: 2NFI:4VMQ:QCE3:KDGD:QXX2:JJAO:4EOR:X55V:PHPE:RBDU:YIBV:J5MW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 39
 System Time: 2018-04-24T18:19:11.797234332Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

I suspect the issue is with the HTTP Proxy setting. 

After a full day of trying different options, i was not able to find a workaround for the latest versions so sadly for now I'm going back to version 17.03.0-ce which is working for me.

**Comment by SG5** [comment]
Same issue, change DNS doesn't help
`Version 18.03.0-ce-mac60 (23751)`
```docker run -it --rm debian
Unable to find image 'debian:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).```

**Comment by nooks** [comment]
Fixed this issue disabling **IPv6**!

**Comment by SG5** [comment]
I've fixed issue with factory reset

**Comment by atul1989** [comment]
how to find default registry config file location in mac book pro?

**Comment by atul1989** [comment]
i was to use my private repo to push and pull images but it is not working ... how to configure private registry url to push pull images in mac os ..?

**Comment by karippery** [comment]
it work when I follow this doc:  [](https://docs.docker.com/config/daemon/systemd/)
