### ISSUE TITLE
Docker networks connections all timeout after running through the night...

### ISSUE THREAD

**Issue by vgoklani** [docker/for-mac#1606]
I'm running the EDGE version of Docker on Sierra. I ran several containers via compose, that are all either processing streaming data or making http requests. I started the session last night, and everything ran fine. When I woke up in the morning, the sessions were all throwing networking errors. This has happened every single day for the past few weeks. Restarting the Docker daemon temporarily fixes the issue. I moved from the stable to the beta Docker version yesterday (hoping for a miraculous solution), but no luck. These are the errors: 

Network error: Couldn't resolve host '.......'
concurrent.futures._base.TimeoutError

When I hopped into a container, popped open a python shell, and pinged http://www.nytimes.com, i saw this:
 
    ConnectionError: HTTPConnectionPool(host='www.nytimes.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f02b280f898>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

I checked the Diagnose & Feedback option in the Docker client, and I see this:

	Docker for Mac: version: 17.05.0-ce-rc1-mac8 (73d01bb48)
	macOS: version 10.12.4 (build: 16E195)
	logs: /tmp/38D064E2-33F1-4B31-95FE-72F254784D42/20170509-073733.tar.gz
	failure: Unexpected error ((Failure "Caught EOF on underlying FLOW")) connecting to /Users/vgoklani/Library/Containers/com.docker.docker/Data/s51
	[OK]     db.git
	[OK]     vmnetd
	[OK]     dns
	[OK]     driver.amd64-linux
	[OK]     virtualization VT-X
	[OK]     app
	[OK]     moby
	[OK]     system
	[OK]     moby-syslog
	[OK]     db
	[OK]     env
	[OK]     virtualization kern.hv_support
	[ERROR]  slirp
	         Unexpected error ((Failure "Caught EOF on underlying FLOW")) connecting to /Users/vgoklani/Library/Containers/com.docker.docker/Data/s51
	[OK]     osxfs
	[OK]     moby-console
	[OK]     logs
	[OK]     docker-cli
	[OK]     menubar
	[OK]     disk

Everything runs fine in the host OS, i.e. my mac. What's going on here?

**Comment by vgoklani** [comment]
bump

**Comment by th3w4y** [comment]
bump

**Comment by SodiSV** [comment]
Hi,

check issue #1374.

There are a lot of people facing connections problems. You can check easily for a connection problem with "nettop" command. Just hit p-Key and remove processes from the view with "space", except the docker ones. Search for connections in Close or FinWait2 state.

Info: There is a connection limit of 2000 connections. Somehow there is a bug in connection handling for the docker process. The connections stuck in Close or FinWait2 state. The processes in the container just require new connections until all 2000 are gone. So, the containers are running but no way to connect to them ... Only a restart of the docker process helps.

Regards,
SodiSV

**Comment by daveanderson** [comment]
This may be addressed by the fix to https://github.com/docker/for-mac/issues/1374 listed in the release notes for Docker 17.09.0-ce-mac33.

**Comment by wivaku** [comment]
I still see the issue in 17.09.0-ce-mac35
