### ISSUE TITLE
Add kernel module CONFIG_TASK_IO_ACCOUNTING

### ISSUE THREAD

**Issue by brmzkw** [docker/for-mac#1608]
### Expected behavior

Since there is AFAIK no easy way to connect to the Docker host, I want to debug the host from a container.

I want to be able to run iotop but the kernel needs to have some modules included.

### Actual behavior

```
$> docker run --rm -ti --pid=host --uts=host --userns=host --net=host --privileged ubuntu sh -c 'apt-get update -qq && apt-get install -y iotop > /dev/null && iotop'
debconf: delaying package configuration, since apt-utils is not installed
Could not run iotop as some of the requirements are not met:
- Linux >= 2.6.20 with
  - I/O accounting support (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING)
```

```
root@moby:/# zcat /proc/config.gz | grep CONFIG_TASKSTATS
CONFIG_TASKSTATS=y
root@moby:/# zcat /proc/config.gz | grep CONFIG_TASK_DELAY_ACCT
CONFIG_TASK_DELAY_ACCT=y
root@moby:/# zcat /proc/config.gz | grep CONFIG_TASK_IO_ACCOUNTING
root@moby:/#
```

**Comment by frivoire** [comment]
Hello,

Any news on this change ?
It would be very usefull to diagnose performances of a docker host.

Thanks !

**Comment by frivoire** [comment]
Hello,

Any news on this change ?
It would be very usefull to diagnose performances of a docker host.

Thanks !

**Comment by frivoire** [comment]
Anything new about this request ?
Thanks.

**Comment by djs55** [comment]
Sorry for the delay in replying. We're hoping to use the [LinuxKit kernel](https://github.com/linuxkit/linuxkit/tree/master/kernel) in future Docker for Mac versions (possibly with a few small tweaks). Perhaps try making a pull request or issue [on the LinuxKit repo](https://github.com/linuxkit/linuxkit). If the LinuxKit kernel gains a patch or feature then Docker for Mac will get it in future too.

**Comment by djs55** [comment]
See https://github.com/linuxkit/linuxkit/issues/2495

**Comment by justincormack** [comment]
This is merged in LinuxKit. Docker for Mac is switching over to LinuxKit soon.

**Comment by FrenchBen** [comment]
Merged also for the Docker for Mac kernel

**Comment by frivoire** [comment]
I'm just testing `iotop` with the last Docker for Mac release (17.09.0-ce-mac35), and it's working properly.
Thanks for this improvement !

@brmzkw : this issue can be closed now, right ?

**Comment by brmzkw** [comment]
thanks a lot!

**Comment by tagirb** [comment]
What about the latest Docker Edge? Somehow it seems to be having an older Linux kernel version:
```
$ docker --version && docker run -it --rm busybox sh -c 'uname -a'
Docker version 17.11.0-ce-rc3, build 5b4af4f
Linux be0eb6008fef 4.9.44-linuxkit-aufs #1 SMP Fri Aug 25 10:00:41 UTC 2017 x86_64 GNU/Linux
```

**Comment by djs55** [comment]
@tagirb Sorry, there was a kernel version regression in edge when we switched to LinuxKit. I've just fixed it and added a test case. The next edge version should have `4.9.60` with `CONFIG_TASK_IO_ACCOUNTING` enabled.

**Comment by tagirb** [comment]
Wow, that was fast, thanks @djs55!
