### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by joellove** [docker/for-mac#161]
Joel@Joelsui-MacBook-Pro:~$ docker info
Error response from daemon: Bad response from Docker engine
Joel@Joelsui-MacBook-Pro:~$ docker images
Error response from daemon: Bad response from Docker engine
Joel@Joelsui-MacBook-Pro:~$ 

### Information

Diagnostic ID: C09207EB-E494-43C3-AC74-A7DBA108A165
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in C09207EB-E494-43C3-AC74-A7DBA108A165/20160807-131806.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  1 15:51:01 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:01 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:02 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:02 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-79360")
Aug  1 15:51:02 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:03 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:03 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 15:51:04 Joelsui-MacBook-Pro Docker[com.docker.driver.amd64-linux][1077] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
```
