### ISSUE TITLE
Unable to start Thingsboard

### ISSUE THREAD

**Issue by digitib** [docker/for-mac#1610]
Hi,
I followed installation procedure to run Thingsboard (https://thingsboard.io/docs/user-guide/install/docker/) without success.
### Expected behavior
Run Thingsboard
### Actual behavior
Error report in Terminal:
ERROR: for db  Cannot start service db: Mounts denied: 
.
OR 
The path /home/docker/cassandra_volume
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
ERROR: Encountered errors while bringing up the project.
### Information
Diagnose & Feedback ID: 93D72F99-AD60-45EC-AFA7-C21D8038CAD8
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/93D72F99-AD60-45EC-AFA7-C21D8038CAD8/20170511-183233.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
1/ Download and Install the stable Docker for Mac DMG file -> Docker installing fine. 

2/ Download the following files from thingsboard repo (see https://thingsboard.io/docs/user-guide/install/docker/) to a user_me/the-docker-folder-I-created: 
- docker-compose.yml - main docker-compose file.
- docker-compose.random.yml - overwrite docker-compose file with thirdparty ports configuration.
- .env - main env file that contains default location of cassandra data folder.
- thingsboard.env - default thingsboard environment variables.
- thingsboard-db-schema.env - default db-schema environment variables.

3/ Then run on terminal:
curl -L https://raw.githubusercontent.com/thingsboard/thingsboard/release-1.2/docker/docker-compose.yml > docker-compose.yml
curl -L https://raw.githubusercontent.com/thingsboard/thingsboard/release-1.2/docker/docker-compose.random.yml > docker-compose.random.yml
curl -L https://raw.githubusercontent.com/thingsboard/thingsboard/release-1.2/docker/.env > .env
curl -L https://raw.githubusercontent.com/thingsboard/thingsboard/release-1.2/docker/thingsboard.env > thingsboard.env
curl -L https://raw.githubusercontent.com/thingsboard/thingsboard/release-1.2/docker/thingsboard-db-schema.env > thingsboard-db-schema.env

**Comment by guillaumerose** [comment]
You should change your .env file with a directory from your home. 

```
CASSANDRA_DATA_DIR=some-directory-in-your-home
```

Let me know if it works.

**Comment by digitib** [comment]
Hi Guillaume, 
Thanks for your reply.
The point is, I don't know the format to use:
The folder containing the files is called xxx and is in my <user> directory.
Do you know how ?
Thanks

---
TdL

**Comment by guillaumerose** [comment]
For my case, I used ```CASSANDRA_DATA_DIR=/Users/guillaume/cassandra/```.

I've created the directory before running docker-compose.

**Comment by digitib** [comment]
Thanks guys, I will try and let you know.
---
TdL

**Comment by guillaumerose** [comment]
I'm closing the ticket. Feel free to reopen it if you have troubles.

**Comment by zeshanmusawar** [comment]
ADD_SCHEMA_AND_SYSTEM_DATA=true ADD_DEMO_DATA=true bash -c 'docker-compose up -d tb'
Removing dockerfolder_tb_1
Starting fb9177f9092c_dockerfolder_tb_1 ... error
how to fix this issue
