### ISSUE TITLE
update kills currently running containers without warning

### ISSUE THREAD

**Issue by boulabiar** [docker/for-mac#1616]
### Expected behavior
Ask the user if he wants to kill the running containers and lose information before stopping them and applying the update.

### Actual behavior
Running a security update just run and kill all running containers. Even if they are not persistent and will lose information.
No warning or verification is made!

### Steps to reproduce the behavior
run non persistent container (default use of docker), apply a security update.

**Comment by guillaumerose** [comment]
Thanks for you report and sorry for the lost. I've added your issue to our internal tracker.
