### ISSUE TITLE
Upgrade causes the daemon to loose time periodically

### ISSUE THREAD

**Issue by buchs** [docker/for-mac#1617]
### Expected behavior
The containers I run should track local system time.

### Actual behavior
They containers time becomes skewed wrt local system time.

### Information

I regularly run containers which perform operations on AWS. If the time for transactions is ahead of AWS time, they can fail. I found that once the daemon is running for something > 15 minutes, the time can be off and commands to AWS fail. If I stop and restart the daemon, this problem is immediately resolved. This ill behavior seemed to start with a recent update of Docker for Mac.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/24349EED-8987-48B0-87C7-F6D14028C0ED/20170515-090951.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. have the daemon running for some time > 15 minutes
  2. run a container and observe the time is skewed

**Comment by buchs** [comment]
Diagnostic ID: 24349EED-8987-48B0-87C7-F6D14028C0ED

**Comment by adrienjoly** [comment]
*As posted on https://github.com/docker/for-mac/issues/2076#issuecomment-353313773*:

Same problem on Version 17.09.1-ce-mac42 (21090), Channel: stable, 3176a6af01.

My PostgreSQL container's clock gains several seconds in the future every time I wake up my MacBook Pro from sleep. I love Docker, but having to restart it so often is really annoying...

Let me know if I can help in any way.
