### ISSUE TITLE
after ±20 hours: containers still running, but not available through port

### ISSUE THREAD

**Issue by wivaku** [docker/for-mac#1622]
### Expected behavior

Applications can always be reached from the host.

### Actual behavior

Every time after ±20-24 hours (estimate), the containers are still running, but the ports are not available.
E.g. this still works:
```
$ docker exec -it jiracore curl -f http://localhost:8080

<!DOCTYPE html>
<html lang="en">
<head>
[...]
```

And this does not:
```
$ curl -f http://localhost:8080
curl: (52) Empty reply from server
```

Same for my other containers (in total: 2x Jira and 1x MySQL).

### Information

diagnostic ID:
3F60B89B-5D96-4794-9200-AA9CE929F116

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/3F60B89B-5D96-4794-9200-AA9CE929F116/20170517-064254.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                 PORTS                    NAMES
00afb592f83d        cptactionhank/atlassian-jira:latest   "/docker-entrypoin..."   2 days ago          Up 3 hours (healthy)   0.0.0.0:8080->8080/tcp jira1
8582e4b804fd        cptactionhank/atlassian-jira:latest   "/docker-entrypoin..."   2 days ago          Up 3 hours (healthy)   0.0.0.0:8081->8080/tcp   jira2
f8dfb221c4bf        mysql:5.6                             "docker-entrypoint..."   2 days ago          Up 3 hours (healthy)   0.0.0.0:3307->3306/tcp   mysql
```

```
$ lsof -Pn -i4 | grep LISTEN | grep com.dock
com.docke 17517 username   41u  IPv4 0xce...bc4bcd      0t0  TCP *:3307 (LISTEN)
com.docke 17517 username   43u  IPv4 0xce...2bfbcd      0t0  TCP *:8080 (LISTEN)
com.docke 17517 username   45u  IPv4 0xce...6d2d5      0t0  TCP *:8081 (LISTEN)
```

### Steps to reproduce the behavior

  1. start Docker
  2. docker-compose up [starts 1x MySQL and 2x Jira]
  3. wait 20-24 hours (estimate)
  4. applications are still running, but not available from the host
  5. restart Docker and restart containers
  6. applications are running, and available from the host

Observed on two systems.
Happens using a) manually creating docker network and docker run's and/or b) docker-compose with implicit bridge network.

Sounds similar: https://github.com/docker/for-mac/issues/1606

**Comment by dazzla76** [comment]
I've got exactly the same behavior.  Running on the latest beta, MacOS 10.12.5 and various containers from linuxserver.io

Did you manage to get anywhere with fixing it?

**Comment by th3w4y** [comment]
bump!  I have the same issue

**Comment by th3w4y** [comment]
I found it to be related with the slirp/max-connections in my case
```
23:10 $ grep Docker /var/log/system.log| grep 900
Jun  5 22:52:59 mnemosyne Docker[25142]: exceeded maximum number of forwarded connections (900)
Jun  5 22:53:30 mnemosyne Docker[25142]: exceeded maximum number of forwarded connections (900)
(anaconda3) (root) ✔ ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp [master L|✔] 
23:10 $ cat max-connections 
900
(anaconda3) (root) ✔ ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp [master L|✔] 
23:10 $ pwd
/Users/oghinet/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp
(anaconda3) (root) ✔ ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp [master L|✔] 
23:10 $ echo 1200 > max-connections 
23:10 $ git commit -a -m 'Update the maximum number of connections'
[master 2475e70] Update the maximum number of connections
 1 file changed, 1 insertion(+), 1 deletion(-)
(anaconda3) (root) ✔ ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp [master L|✔] 
23:11 $ grep Docker /var/log/system.log| grep update
Jun  5 23:06:39 mnemosyne Docker[25142]: updating connection limit to 1200
```

After this manoeuvre the network connectivity of the docker is recovered.

**Comment by th3w4y** [comment]
Looks like the slip-up connections are stacked in CLOSE_WAIT
```
16:09 $ ps -ef | grep 40749
  501 40749  1213   0 11:20PM ??         2:48.47 com.docker.slirp --db /Users/oghinet/Library/Containers/com.docker.docker/Data/s40 --ethernet fd:3 --port fd:4 --introspection fd:5 --diagnostics fd:6 --vsock-path /Users/oghinet/Library/Containers/com.docker.docker/Data/@connect
  501 52565 50976   0  4:09PM ttys000    0:00.00 grep 40749
(anaconda3) (root) ✔ ~ 
16:09 $ lsof  -p 40749| grep CLOSE_WAIT| wc -l
    2347
(anaconda3) (root) ✔ ~ 
16:09 $ 
```

**Comment by TheFox** [comment]
I have a pretty similar issue under Linux host.

When I want to access the Apache port via 127.0.0.1 on the host system some requests timeout. This happens after the container is running several days. I have a Apache Reverse Proxy infront of the container which is listening on `127.0.0.1:32000:80`.

When I access the Apache port using `curl` via the `docker0` internal container address (using `docker inspect -f '{{ .NetworkSettings.IPAddress }}' CONTAINER_ID`) I never have this problems. It always works.

### Solutions

* I don't want to create a cronjob which is restarting the container or the docker daemon. This solution should be the last.
* A better solution would be to get the internal IP address of the container. Then writing the IP address to `/etc/hosts` and use this host in my Apache Reverse Proxy configuration. This is also not a good solution but I don't know a better one.
