### ISSUE TITLE
Automatically start containers

### ISSUE THREAD

**Issue by motherwaym** [docker/for-mac#1624]
### Expected behavior

My container would return to the previous running state after a reboot.

### Actual behavior

Container is stopped after a reboot and I need to manually start it.

### Information

- Mac OS 10.12.4
- Docker 1.13.1-beta42
- Running SQL Server per https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker

### Steps to reproduce the behavior

  1. Start a container
  2. Reboot mac

**Comment by guillaumerose** [comment]
Thanks for the report. I will add your feature request in our internal issue tracker.

**Comment by guillaumerose** [comment]
You can use ```--restart=always``` when you first start your container. After each reboot, the container will be restarted. See https://docs.docker.com/engine/reference/run/#restart-policies---restart

Please note that you use a old version of Docker for Mac. You may need to upgrade.
