### ISSUE TITLE
Unable to connect to docker registry

### ISSUE THREAD

**Issue by technoweenie** [docker/for-mac#1625]
### Expected behavior

Docker commands should access the default registry.

### Actual behavior

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: therealtechnoweenie
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp [::1]:443: getsockopt: connection refused
```

### Information

Diagnostic ID: 5A82E371-D13C-49D1-A417-B34760461F1F

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/5A82E371-D13C-49D1-A417-B34760461F1F/20170517-114836.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

* Cloak is installed, but not enabled on my work network.
* Viscosity is installed, but no connections are active
* Advanced daemon properties sets up google dns:

```json
{
  "dns" : [
    "8.8.8.8",
    "8.8.4.4"
  ]
}
```

Docker registry url is accessible:

```sh
$ curl -i https://registry-1.docker.io/v2/
HTTP/1.1 401 Unauthorized
```

### Steps to reproduce the behavior

1. Install Docker for Mac

**Comment by ttaylorr** [comment]
I was able to reproduce this issue as well, and both @technoweenie and I were able to resolve it after _enabling_ Cloak.

This happened after installing Docker for Mac for the first time on a brand new computer. In the same case on my previous laptop which shipped with OS X El Capitan, this issue did not occur. Perhaps there is some new networking default in Sierra that is overridden by tool(s) like Cloak?

**Comment by spicydonuts** [comment]
I'm also seeing this.  Unable to pull any images after updating to macOS 10.13.  I did reinstall Docker before confirming whether I could pull images to switch to the beta.  I switched to the beta due to #1960, but that did not resolve that issue.  I incorrectly assumed the stable version was not compatible with 10.13 because of the immediate crash.

```
macOS: version 10.13 (build: 17A344b)
Docker.app: version: 17.07.0-ce-rc2-mac22 (69202b202f497d4b6e627c3370781b9e4b51ec78)
Local time: Tue Aug 15 15:45:07 MDT 2017
UTC:        Tue Aug 15 21:45:07 UTC 2017
Timestamp:  20170815-154507
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      vpnkit
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/80923F54-8FC7-47CF-AEFB-05DFE3EA28EB/20170815-154507.tar.gz
Your unique id is: 80923F54-8FC7-47CF-AEFB-05DFE3EA28EB
Please quote this in all correspondence.
```

**Comment by spicydonuts** [comment]
Reverted to stable and it's working again.
```
macOS: version 10.13 (build: 17A344b)
Docker.app: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
Local time: Tue Aug 15 16:06:36 MDT 2017
UTC:        Tue Aug 15 22:06:36 UTC 2017
Timestamp:  20170815-160636
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      vpnkit
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/8F2585D5-071B-4539-9869-139F673490BF/20170815-160636.tar.gz
Your unique id is: 8F2585D5-071B-4539-9869-139F673490BF
Please quote this in all correspondence.
```

**Comment by kishaningithub** [comment]
This fixed the issue for me..
In the "Proxies" tab i changed it from using "System Proxy" to "No Proxy"

<img width="376" alt="screen shot 2017-09-20 at 9 59 30 am" src="https://user-images.githubusercontent.com/763760/30626897-aabafdf8-9dea-11e7-8e2d-8302883f2dee.png">
