### ISSUE TITLE
Can we delete Volumes from /var/lib/docker/volumes for containers which are stopped?

### ISSUE THREAD

**Issue by shahmaulikn** [docker/for-mac#1626]
### Expected behavior
Do we have any solution ? 
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...Run Docker 
  2. ...Perform few steps
  3.  Run another docker with same name so older one will be dangling 
4. new volume will be created at /var/lib/docker/volumes location
5. Now stop the docker which was running 

Volume still exist and if we want to delete, we can remove using below command
for i in $(docker volume ls -f dangling=true  | awk '{print $2}'); do sudo test -d "/var/lib/docker/volumes/$i/_data" || docker volume rm $i; done

If we want to set cronjob or any method which delete the volume which was created after step 1 and 3 do we have any solution?

**Comment by guillaumerose** [comment]
Hello,
I'm not sure of what you are talking about. Do you use Docker for Mac or just Docker on Linux ?
Thanks

**Comment by shahmaulikn** [comment]
It is for Linux , but may be applicable to OS X also as using same platform. You can move this ticket to linux

Problem is, I want to delete volume copy of containers which are stopped

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
