### ISSUE TITLE
[ Fatal error ]com.docker.osx.hyperkit.linux failed to start Exit code 1

### ISSUE THREAD

**Issue by pullareddy009** [docker/for-mac#1628]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by guillaumerose** [comment]
Could you give us a diagnostic ID and describe the symptoms ? Thanks.

**Comment by pullareddy009** [comment]
Re-installed docker today and it worked. nv:)
