### ISSUE TITLE
Docker hangs

### ISSUE THREAD

**Issue by carloscasalar** [docker/for-mac#163]
### Expected behavior
I were trying to run a command inside a container like this `docker run --rm -v /Users/myusername/nodes/rgt-fantasy-calendar:/data --net=host dockerfile/nodejs-bower-gulp nam install`
after several minutes it looks like hangs. Then I try to stop it. First i wish to do a `docker ps` in order to perform a `docker kill` but wen i try to run a `docer ps` it hangs.

### Information

Diagnostic ID: 140AF387-3B48-4503-8361-AEC989534296
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by mchiang0610** [comment]
Merging with #119
