### ISSUE TITLE
docker not running

### ISSUE THREAD

**Issue by kamelotnsk** [docker/for-mac#1630]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kamelotnsk** [comment]
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/26D18A02-759F-4C26-89A4-7C2B7928681A/20170519-111736.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[ERROR]  virtualization VT-X
         No VMX in machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH MMX FXSR SSE SSE2 HTT SSE3 MON CX16 SSE4.1 SSE4.2 POPCNT
[OK]     app
[ERROR]  moby
         /Users/Joe/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/Joe/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Joe/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Joe/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/Joe/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/Joe/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by gtardif** [comment]
Hi, 
Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/install/#/what-to-know-before-you-install for more information.

The log in sysctl-a matches:
```

kern.timer_coalesce_ts_ns_max: 1000000
kern.timer_coalesce_tier0_scale: 3
kern.timer_coalesce_tier0_ns_max: 1000000
kern.timer_coalesce_tier1_scale: 2
kern.timer_coalesce_tier1_ns_max: 5000000
kern.timer_coalesce_tier2_scale: 1
kern.timer_coalesce_tier2_ns_max: 20000000
kern.timer_coalesce_tier3_scale: -2
kern.timer_coalesce_tier3_ns_max: 75000000
kern.timer_coalesce_tier4_scale: -15
kern.timer_coalesce_tier4_ns_max: 10000000000
kern.timer_coalesce_tier5_scale: -15
kern.timer_coalesce_tier5_ns_max: 10000000000
kern.hv_support: 0
kern.memorystatus_purge_on_warning: 2
kern.memorystatus_purge_on_urgent: 5
kern.memorystatus_purge_on_critical: 8
kern.msgbuf: 16384
kern.coalitions: 273 0
kern.coalition_roles: 0 -1
kern.coalition_page_count: 11462 0
kern.coalition_pid_list: 631 643 748 749
kern.secure_kernel: 0
kern.interrupt_timer_coalescing_enabled: 1
kern.timer_coalesce_idle_entry_hard_deadline_max: 5000000
kern.pmtimeout: 0
vm.loadavg: { 2.98 2.82 2.09 }
vm.swapusage: total = 0.00M  used = 0.00M  free = 0.00M  (encrypted)
```
In particular I think kern.hv_support: 0 means no hypervisor support.

Although Docker for Mac requires hardware virtualisation support (i.e. VT-x) it's worth seeing if you can run VMs with Virtualbox or with VMware fusion. If either of those work then you can still run docker via Docker toolbox: https://www.docker.com/products/docker-toolbox

Thanks for your report and your interest in Docker for Mac.
