### ISSUE TITLE
 Fatal Error: com.docker.osx.hyperkit.linux failed to start

### ISSUE THREAD

**Issue by AaronBDC** [docker/for-mac#1631]
### Expected behavior
Booting up docker for mac.

### Actual behavior
Docker for Mac crashes with exit code 1 when attempting to start.

### Information
![dockercrashedsucks](https://cloud.githubusercontent.com/assets/25655625/26270840/85e68d3c-3ccc-11e7-91d6-bffb03df0cf0.png)

After installing version 17.03.1-ce-mac12, opening the app yields a fatal error.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/81A22455-79DC-4BA2-9E4C-6A46EDEEDD18/20170519-191704.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/likesdat/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/likesdat/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/likesdat/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/likesdat/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/likesdat/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/likesdat/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

  - Page URL if this is a docs issue or the name of a man page
https://github.com/docker/for-mac/issues/1071

### Steps to reproduce the behavior

  1. Start Docker for Mac OS Sierra.

rm -fr ~/Library/Containers/com.docker.docker/Data/*
reboot...no dice

rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
reboot...no dice

**Comment by AaronBDC** [comment]
Hardware virtualization is not enabled but I will verify and test.

**Comment by AaronBDC** [comment]
@yallop you like?

**Comment by gtardif** [comment]
Thx for the report @AaronBDC 
It seems that your diags have not been uploaded ; could you please run "Diagnose & Upload" and update the diagnostic output (especially the diagnostic ID).

Also, you can try to uninstall / reinstall Docker for Mac (with  `/Applications/Docker.app/Contents/MacOS/Docker --uninstall` to uninstall without starting docker)
Let us know if this helps
