### ISSUE TITLE
AE4EB025-B42C-455A-A357-CA206C770F61

### ISSUE THREAD

**Issue by hrandiac** [docker/for-mac#1634]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.10.5 (build: 14F2315)
logs: /tmp/AE4EB025-B42C-455A-A357-CA206C770F61/20170521-111441.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/hrandiac/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/hrandiac/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/hrandiac/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/hrandiac/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/hrandiac/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/hrandiac/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

  2. ...

**Comment by hrandiac** [comment]
I had an earlier version of Docker that was not compatible with Yosemite.  I deleted that version from the system with AppCleaner. I have gone through "Get started with Docker for Mac". I could not fdiscover a solution.
Thank you for your help, Ivan Craig

**Comment by gtardif** [comment]
Hi Ivan, 
Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/install/#/what-to-know-before-you-install for more information.

The log in sysctl-a matches:
```

kern.timer_coalesce_ts_ns_max: 1000000
kern.timer_coalesce_tier0_scale: 3
kern.timer_coalesce_tier0_ns_max: 1000000
kern.timer_coalesce_tier1_scale: 2
kern.timer_coalesce_tier1_ns_max: 5000000
kern.timer_coalesce_tier2_scale: 1
kern.timer_coalesce_tier2_ns_max: 20000000
kern.timer_coalesce_tier3_scale: -2
kern.timer_coalesce_tier3_ns_max: 75000000
kern.timer_coalesce_tier4_scale: -15
kern.timer_coalesce_tier4_ns_max: 10000000000
kern.timer_coalesce_tier5_scale: -15
kern.timer_coalesce_tier5_ns_max: 10000000000
kern.hv_support: 0
kern.memorystatus_purge_on_warning: 2
kern.memorystatus_purge_on_urgent: 5
kern.memorystatus_purge_on_critical: 8
kern.msgbuf: 16384
kern.secure_kernel: 0
kern.interrupt_timer_coalescing_enabled: 1
kern.timer_coalesce_idle_entry_hard_deadline_max: 5000000
vm.loadavg: { 1.91 2.19 2.39 }
vm.swapusage: total = 0.00M  used = 0.00M  free = 0.00M  (encrypted)
vm.cs_force_kill: 0
vm.cs_force_hard: 0
vm.cs_debug: 0
vm.cs_all_vnodes: 0
vm.cs_enforcement: 0
vm.cs_enforcement_panic: 0
vm.sigpup_disable: 0
```
In particular I think kern.hv_support: 0 means no hypervisor support.

Although Docker for Mac requires hardware virtualisation support (i.e. VT-x) it's worth seeing if you can run VMs with Virtualbox or with VMware fusion. If either of those work then you can still run docker via Docker toolbox: https://www.docker.com/products/docker-toolbox

Thanks for your report and your interest in Docker for Mac.
