### ISSUE TITLE
I have no idea what to say about this.  

### ISSUE THREAD

**Issue by SyntaxChris** [docker/for-mac#1636]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
I'm closing this because the description lacks too much information. If you want to reopen it, please run and upload diagnostics, and provide a diagnostic ID in the issue.
