### ISSUE TITLE
Container wouldn't restart, couldn't be killed and now Docker won't restart.

### ISSUE THREAD

**Issue by BrendonW** [docker/for-mac#1637]
### Expected behavior
Container restarts when you do a `docker stack deploy`

### Actual behavior
One of the containers continued to run and any command trying to stop or kill the container just hung.

### Information

Diagnostic ID: 07DC8946-60D1-4612-8928-A3F0082F575E

### Steps to reproduce the behavior

  1. Unknown at this time.

**Comment by gtardif** [comment]
Is it just the container that won't restart, or also Docker ? 
(I'm not sure from the title, maybe reformulate as "Docker container won't restart")
Can you provide logs of the faulty container ? (with `docker logs <container>`)
You can try to stop Docker for mac (`quit docker` in the whale menu the restart Docker in /Application), and restart your containers.

**Comment by BrendonW** [comment]
I tried to restart Docker after I found the container that would not restart. At that point, Docker needed to be killed with a force-kill (well, `kill -9`)  before I could restart it.

I'm unfortunately unable to get the logs from the container now... unless there is a way to access logs from the Mac file system.

In general, is there a best place to monitor the Docker for Mac logs of all containers and Docker itself?

**Comment by BrendonW** [comment]
If you could give me a rundown of where all Docker-related logs may be found on the Mac, then I'd be happy to close this issue for the moment... that knowledge would allow me to copy all those logs out of VMs or wherever if this happens again to preserve possible clues.

Thanks.
