### ISSUE TITLE
Random crash/restart of Docker for Mac

### ISSUE THREAD

**Issue by 0xCMP** [docker/for-mac#1638]
### Expected behavior
- No unexpected restarts

### Actual behavior
- Sudden restart causing running containers to be killed and docker-compose to get 500 errors

### Information
I did a diagnostic after the reboot finished to hopefully capture and logs I could about the problem. I started trying to boot my containers again before I realized that might pollute the logs and then killed that process to prevent that any further.

```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170522-183312.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostic ID: `70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

### Steps to reproduce the behavior
I wasn't doing anything but just using my containers and it restarted for some reason.

**Comment by gtardif** [comment]
I didn't see anything useful in the diagnostic infos related to this crash. Let us know if this reproduces, and if there are more info about the context when this happens.

**Comment by 0xCMP** [comment]
It happened again only a few minutes ago (I'm guessing. Didn't notice until I tried to reload my page)

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170523-183100.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostic ID: `70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

**Comment by 0xCMP** [comment]
Is there some way I can get into the VM or see more logs that I can look at or post somewhere?

Seems like this is mostly related to the VM. I have a feeling that it's running out of memory or running into some weird networking bug either through the internal network or via the exposed port.

**Comment by 0xCMP** [comment]
Just happened again, tried starting diag while it was booting up.

`70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170526-121819.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by jasonbivins** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by 0xCMP** [comment]
Hi @jasonbivins and @gtardif, I tried to provide more information, but I'm not sure what I need to do or where I need to look for that information. I've continued to report the multiple times it happened to help find a pattern. I have not seen the problem very recently because I aggressively restart Docker to prevent slowing my work down.
