### ISSUE TITLE
Docker for Mac stalled...

### ISSUE THREAD

**Issue by hairyhenderson** [docker/for-mac#1639]
### Expected behavior

Docker for Mac should start up...

### Actual behavior

It sits there with the continual progress indicator on the toolbar...

### Information

  - 671C7B17-2FE1-47BF-8394-AEDF4A759214

**Comment by hairyhenderson** [comment]
Just as a follow-up, force-quitting and restarting changed nothing in the behaviour (that was 35mins ago at this point).

I've done a factory reset and it's now running. But I'm still concerned about the fact that it stalled, so I'm going to keep this issue open...

**Comment by gtardif** [comment]
Thanks @hairyhenderson for the report. It seems that your qcow2 disk had been corrupted. We are working on fixing this error, your disk should not have this errors.
(Lots of `Inode 3557232 ref count is 2, should be 1`)
Indeed a factory reset deletes this files and creates a new one.

We have #1315 as the public tracking issue. Please subscribe to #1315 for further updates.

**Comment by hairyhenderson** [comment]
@gtardif thanks - I didn't think it was involved, but I _did_ use a custom `qcow-tool` to compact the disk the other day. The custom build was sent to me by @djs55 over the Community Slack a few days ago, in response to an issue I had when `qcow-tool` was hanging after an update.
