### ISSUE TITLE
docker info->Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by tangdodo** [docker/for-mac#164]
### Information

Diagnostic ID: 920D3181-D44C-408F-9F66-E154313DE117
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.3 (Build 15D21)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@tangdodo Curious if you have had previously scripted docker-machine? If so, please remove it. The status for Docker for Mac seems to be okay. 

Let me know if we can help you troubleshoot this further. 

Thanks!
