### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by anotheral** [docker/for-mac#1641]
### Expected behavior

Running `docker ps` shows a list of running containers

### Actual behavior

Get the error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

### Information

  - Diagnostic ID is EF9ED451-E8A4-4CC3-85EB-4D1C9C923431

### Steps to reproduce the behavior

  1. Install docker 17.03.1-ce-mac12 on OS X 10.12
  2. run "docker ps"

**Comment by asuh** [comment]
I have the same issue and I'm running the same OS. I first used Homebrew, `brew install docker`, to install Docker, the uninstalled it and tried `brew cask install docker-toolbox`. Same result for both.

The same "Actual behavior" as above happened when I ran `docker version` in my terminal in either installation.

This video gave me a way around it:
https://www.youtube.com/watch?v=1Xx1xSPyvXI

Why must Docker Quickstart Terminal be run to get past this error? This is non-intuitive.

**Comment by gtardif** [comment]
Hi @asuh, Docker for mac (https://docs.docker.com/docker-for-mac/install/) is now the recommended way to use docker (over docker toolbox). It will provide a better integration and will not need a specific terminal.
(it will try to migrate things from toolbox, but if you don't have specific data to migrate like docker images or containers, you might be better off uninstalling toolbox first, with https://github.com/docker/toolbox/blob/master/osx/uninstall.sh)

**Comment by gtardif** [comment]
Hi @anotheral, your diagnostics seem OK regarding the VM that host the docker Daemon ; can you try stopping the Docker for Mac App (`Quit Docker`menu), and restart it from /Applications ?

**Comment by nimdajitam** [comment]
I was experiencing exactly the same problem as OP (using brew). Using Docker CE for Mac works fine.
