### ISSUE TITLE
Docker is not woking on MAC

### ISSUE THREAD

**Issue by installvirtual** [docker/for-mac#165]
### Information

Diagnostic ID: 9531B204-6B6E-4C7A-B309-55EA14E13303
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in 9531B204-6B6E-4C7A-B309-55EA14E13303/20160808-121522.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug  1 09:49:57 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:49:57 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:49:58 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:49:58 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-40965632")
Aug  1 09:49:58 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:49:59 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:49:59 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Aug  1 09:50:00 cka Docker[com.docker.driver.amd64-linux][489] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
```
