### ISSUE TITLE
9495EC34-C691-451E-9D82-D2D2DFDEE8AD

### ISSUE THREAD

**Issue by nothing49199** [docker/for-mac#1659]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Closing, we need more information. Upload a new diagnose if problem persists.
