### ISSUE TITLE
Datetime inside docker container doesn't match hosts

### ISSUE THREAD

**Issue by jgworks** [docker/for-mac#1663]
### Expected behavior
Docker should have the correct datetime.
### Actual behavior
The datetime within docker drifts behind the actual time.

### Information
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/50695675-0D9F-4BE9-AA84-A8B996BD8F8A/20170531-115127.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

$ date -u
Wed May 31 15:52:34 UTC 2017
$ docker run -it fedora date -u
Wed May 31 15:16:54 UTC 2017

### Steps to reproduce the behavior

No specific steps, but I am running docker on a laptop that i put to sleep often. Restarting docker from the menubar fixes the issue.

**Comment by adrienjoly** [comment]
*As posted on https://github.com/docker/for-mac/issues/2076#issuecomment-353313773*:

Same problem on Version 17.09.1-ce-mac42 (21090), Channel: stable, 3176a6af01.

My PostgreSQL container's clock gains several seconds in the future every time I wake up my MacBook Pro from sleep. I love Docker, but having to restart it so often is really annoying...

Let me know if I can help in any way.
