### ISSUE TITLE
888086B0-666F-4BBA-94E7-FE7579AEAECB

### ISSUE THREAD

**Issue by alilah** [docker/for-mac#1666]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Closing, a new diagnose with more information would be helpful :)
