### ISSUE TITLE
docker-compose: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by jaredallard** [docker/for-mac#1667]
### Expected behavior

`docker-compose` works

### Actual behavior

```bash
$ docker-compose up 

ERROR: readlink /var/lib/docker/overlay2: invalid argument
```

### Information

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/7B5AA8CD-A727-4D6F-8430-B944630D0DD6/20170531-211517.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostics ID: `7B5AA8CD-A727-4D6F-8430-B944630D0DD6`

### Steps to reproduce the behavior

  1. Computer hard shutdown while running docker-compose 
  2. ... stop working

**Comment by jaredallard** [comment]
Resolved with the steps in #1396

**Comment by jaredallard** [comment]
Closing in favor of #1396.

**Comment by IlyaVorozhbit** [comment]
Why, just say, why your Docker is **[трахает мне мозги]** / not working stable  on windows?

To begin to work I must do about 3-5 restarts, reinstall docker, delete all containers, to sleep 7 days, to pray 10 days, and after that restart docker, and MAYBE it will work.

Why?

**Comment by Andremoniy** [comment]
> Why, just say, why your Docker is **[трахает мне мозги]** / not working stable on windows?
> 
> To begin to work I must do about 3-5 restarts, reinstall docker, delete all containers, to sleep 7 days, to pray 10 days, and after that restart docker, and MAYBE it will work.
> 
> Why?

The very same problem happens under MacOS X :(
