### ISSUE TITLE
Docker for mac is failed to start

### ISSUE THREAD

**Issue by houming-wang** [docker/for-mac#1669]
### Diagnostic ID
33B04325-D993-44A1-8A60-4CE0515982BC

### Information

Docker for Mac: version: 17.06.0-rc1-ce-mac13 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/33B04325-D993-44A1-8A60-4CE0515982BC/20170601-171857.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/houming/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/houming/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/houming/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/houming/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/houming/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by raptium** [comment]
I have the same problem, Diagnostic ID: B16C69CF-980D-4DF6-9D42-5AB17A12CDBC

**Comment by SantoDE** [comment]
Me 2.

**Comment by ebriney** [comment]
Thanks. We found the bug, it will be fixed on the next version. If it's a blocker for you can use this preview build and tell me if it worked:
https://download.docker.com/mac/edge/18207/Docker.dmg

**Comment by SantoDE** [comment]
Thanks @ebriney . Tested the preview on my mac and it's working fine now :)
