### ISSUE TITLE
When will multi-stage / 17.05+ be released for Mac?

### ISSUE THREAD

**Issue by mcandre** [docker/for-mac#1673]

**Comment by thaJeztah** [comment]
Docker 17.05 is available on the "edge" channel for Docker for Mac follow the installation instructions for installing "edge" releases here; https://docs.docker.com/docker-for-mac/install/

**Comment by conner** [comment]
Is there a public release schedule for releases moving from edge to stable? Even more broadly how does a release get promoted to the stable channel (are tires still getting kicked or is the time lag more of a process or developer time thing)?

We're interested in making use of the multistage builds and would want to wait if those features will make it into the stable channel shortly. We're reluctant to move our mac-based developers over to the edge channel, so we might use an alternative approach if the change is further out.

all the best, and thanks! // C

**Comment by conner** [comment]
I just noticed the copy under the download link for stable: _**Stable builds are released once per quarter._**

given that 17.03 was released quite recently, I would expect the next bump to stable in the fall?

**Comment by djs55** [comment]
@conner 17.03 was released in March, 17.06 is due for release very soon now.

**Comment by thaJeztah** [comment]
Looks like this can be closed, because all current versions now support this
