### ISSUE TITLE
Incorrect behaviour in terminal

### ISSUE THREAD

**Issue by Morendil** [docker/for-mac#1674]
When running `docker run -it busybox` on a fresh (data erased) install of Docker for Mac 17.06 (build 18169) on MacOS Sierra (under iTerm2 v3):

### Expected behavior

Empty command lines line up on left side of terminal window:

![screen shot 2017-06-01 at 19 09 11](https://cloud.githubusercontent.com/assets/216452/26691625/25898746-46fe-11e7-8536-04d389df22ff.png)

### Actual behavior

Command prompt lines up with rightmost character of previous command line.

![screen shot 2017-06-01 at 14 00 32](https://cloud.githubusercontent.com/assets/216452/26691737/87afe410-46fe-11e7-8ea4-fe5f9c970502.png)

### Information

Diagnostic ID E313D157-57F3-4768-BBCF-2C9B322C3E54

### Steps to reproduce the behavior

Just run busybox.

**Comment by philipmat** [comment]
I can confirm this with the ubuntu image (or any other image I tried:

```sh
$ docker run -ti --rm ubuntu /bin/bash
root@f019b6a58314:/# 
                     root@f019b6a58314:/# 
                                          root@f019b6a58314:/# 
                                                               root@f019b6a58314:/# 
                                                                                    root@f019b6a58314:/# 
                                                                                                         root@f019b6a58314:/# 
  root@f019b6a58314:/# 
                       root@f019b6a58314:/# 
                                            root@f019b6a58314:/# 
                                                                 root@f019b6a58314:/# exit
                                                                                          [ ~/Projects/setup-scripts ]  (develop) 12:20:23 philip@Philips-MacBook-Air
$ docker version
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:00:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by philipmat** [comment]
Seems a duplicate of #1671 and #1672

**Comment by Morendil** [comment]
Yep.
