### ISSUE TITLE
No carriage returns when working interactively inside a container

### ISSUE THREAD

**Issue by leonboot** [docker/for-mac#1678]
### Expected behavior

When running an interactive shell inside a container, a carriage return should be done after each newline. So `ls -1` should produce something like:

```
file1
file2
file3
...
```

### Actual behavior

Line breaks get a newline, but no carriage return. The command `ls -1` produces:

```
file1
     file2
          file3
```

### Information

  - Edge version 17.06.0-rc1-ce-mac13 (18169)
  - Diagnostic ID: 1A51357B-1DE7-4A23-A1B4-2D251FA7D0C8

### Steps to reproduce the behavior
  1. Make sure you're on Edge version 17.06.0-rc1-ce-mac13 (18169)
  2. Spin up an interactive shell in a docker container: `docker run --rm -it alpine:latest sh`
  3. run `ls -1 /` in the container
  4. Note that each new line starts on a new line, but at the colum the last line ended.

**Comment by amancevice** [comment]
This looks like a dup of #1671 and #1672

**Comment by leonboot** [comment]
@amancevice you're absolutely right. Guess I should rub that sand out of my eyes before reporting an issue. I'll close it.
