### ISSUE TITLE
17.06.0-rc1-ce-mac13 (18169) keeps crashing

### ISSUE THREAD

**Issue by sylv3r** [docker/for-mac#1683]
### Expected behavior

Usual behavior

### Actual behavior

It crashes

### Information

Diagnose ID  : 7E8475C9-8A6C-4048-AF66-EBB13C69B8D0

### Steps to reproduce the behavior

  1. update to 17.06.0-rc1-ce-mac13 (18169)
  2. wait about 3 to 10 minutes of normal usage and it crashes. Putting the mac in sleep mode  or closing a laptop is an immediate crash too.

UPDATE : 
switching network makes it crash instantly too.

**Comment by linsfg** [comment]
Diagnose ID : 61A1EC29-033E-4AF8-96E2-78690C9FBDF9

com.docker.osx.hyperkit.linux failed to start
Exit code 1

**Comment by ericparton** [comment]
I just wanted to add that I also have this problem when stopping containers via docker-compose. (Same version of docker and all that)

**Comment by AndreiRailean** [comment]
Also, Kitematic cannot start any docker container.
Once a container is started via `docker start` it shows as running in Kitematic.

**Comment by thorstensiefert** [comment]
>Putting the mac in sleep mode or closing a laptop is an immediate crash too.

To be a little bit more specific:  

Case 1:  

If I use the hibernation mode from the menu <= 15 minutes - Docker stays "awake" and all containers (I usually use compose) are running. Even when the lid is closed _after_ activating the hibernation mode

Case 2:  

If I close the lid  of my MacBook Pro for a break or so docker restarts after opening the lid. All containers are stopped, of course. `docker-compose up -d` makes them start again - no dataloss.

```
Version 17.06.0-rc1-ce-mac13 (18169)
Channel: edge
```

**Comment by zhouyixiang** [comment]
Docker for mac crash during startup, here is my diagnose info

``` 
Docker for Mac: version: 17.06.0-rc1-ce-mac13 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/6E217091-91B9-4E28-9FA7-2E9268372E4A/20170607-080436.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/xxx/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/xxx/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/xxx/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/xxx/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/xxx/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by josja** [comment]
Version 17.06.0-rc2-ce-mac14 (18280) (Edge channel)

Noticed since a week, that after returning from lunch all my docker-composed containers have crashed. Smells like sleep/hibernation related. I hoped the update today fixed things but alas. 

```Unexpected API error for *** (HTTP code 502)
Response body:
Bad response from Docker engine```

Noticed when I accidentally quit the docker tray app I get the same errors (but I am not sure if previous versions gracefully stopped the containers before quitting).

**Comment by thorstensiefert** [comment]
> Smells like sleep/hibernation related.  

I'am quit sure that it is.

>  I hoped the update to RC2 today fixed things but alas.

I hoped that too - but the issue still occurs as described in https://github.com/docker/for-mac/issues/1683#issuecomment-306561345. Bummer!

**Comment by shillem** [comment]
I confirm. Ever since I switched to 17.06 rc1 and rc2 I get **Bad response from Docker engine** when the machine wakes up from sleep is pretty much guarateed

**Comment by josja** [comment]
Guaranteed not so sure: regarding my 17.06.0-rc2-ce-mac14 (18280) version, I don't seem to be able to reproduce this issue, all containers are still up & running since I started them yesterday morning. Also tried forcing sleep n stuff... think maybe the complete shutdown of my laptop during my long weekend helped.

**Comment by thorstensiefert** [comment]
Just ran into the issue again :(   

Docker for Mac: version: 17.06.0-rc2-ce-mac14 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)

Diagnostic ID: 6620CFC8-18BC-459F-AA45-870C9CE28203

**Comment by bwhitty** [comment]
Running
```
Version 17.06.0-rc2-ce-mac14 (18280)
Channel: edge
e4067577a3
```
and have the same issues with sleep / idle.
```
Unexpected API error for *** (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by thorstensiefert** [comment]
The hibernation issue is still in RC4. 
Docker does a restart - and the containers are stopped.

```
Docker for Mac: version: 17.06.0-rc4-ce-mac15 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
```

Diagnostic ID:  6620CFC8-18BC-459F-AA45-870C9CE28203

**Comment by josja** [comment]
After a week with no crashes I like RC5.  17.06.0-ce-rc5-mac16 (18400)

**Comment by bramus** [comment]
Running into likewise issues with `17.06.0-ce-mac18`. After my macbook resumes from hibernation all docker containers have been stopped.
