### ISSUE TITLE
Docker build fails to pull image from Google Private Registry

### ISSUE THREAD

**Issue by BrendonW** [docker/for-mac#1689]
### Expected behavior
If I have logged into the repository, I expect to be able to pull images when building an image.

### Actual behavior
`docker pull` works fine, but `docker build` fails if the image is not already local.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
07DC8946-60D1-4612-8928-A3F0082F575E

  - Results result from bash:
```
Firefly:redis brendon$ time docker build -f docker_redis.yml -t us.gcr.io/tfhp-chess/redis:latest .
Sending build context to Docker daemon  4.096kB
Step 1/14 : FROM us.gcr.io/tfhp-chess/alpine-base
repository us.gcr.io/tfhp-chess/alpine-base not found: does not exist or no pull access

real	1m13.665s
user	0m27.320s
sys	0m8.874s
Firefly:redis brendon$ time docker pull us.gcr.io/tfhp-chess/alpine-base
Using default tag: latest
latest: Pulling from tfhp-chess/alpine-base
Digest: sha256:0b94d1d1b5eb130dd0253374552445b39470653fb1a1ec2d81490948876e462c
Status: Downloaded newer image for us.gcr.io/tfhp-chess/alpine-base:latest

real	0m4.820s
user	0m0.358s
sys	0m0.121s
Firefly:redis brendon$ time docker build -f docker_redis.yml -t us.gcr.io/tfhp-chess/redis:latest .
Sending build context to Docker daemon  4.096kB
Step 1/14 : FROM us.gcr.io/tfhp-chess/alpine-base
 ---> a41a7446062d
Step 2/14 : RUN addgroup -S redis && adduser -S -G redis redis
<deleted>
```
### Steps to reproduce the behavior

This is a simple example of how to recreate, actual URL to GCR will change depending on account, etc.

  1. `docker pull alpine`
  2. `docker tag alpine:latest us.gcr.io/tfhp-chess/alpine-base:3.6`
  3. `docker push us.gcr.io/tfhp-chess/alpine-base:3.6`
  4. Use the Google Cloud Registry console to add the tag `latest` (_basically so you don't have the image locally_)
  5. `docker build` any image that starts with `FROM: push us.gcr.io/tfhp-chess/alpine-base`
  6. `docker pull`
  7. Repeat the `docker build` which now will work.

**Comment by mattKaczorowski** [comment]
I am experiencing the same issue using Ubuntu 14.04. The issue is not limited to DFM.

**Comment by mattKaczorowski** [comment]
A co-worker has pointed me to `gcloud docker -a`, which authorizes docker for a short period of time. It seems to do the trick :smile:. I was able to properly build images, even from docker-compose. Not sure if you have tried that or if it works with DFM. @BrendonW

**Comment by jgrabenstein** [comment]
Hit this on Debian 8 (Jessie). 

Luckily was able to use @mattKaczorowski 's workaround on our build servers.
