### ISSUE TITLE
Docker upgrade failed

### ISSUE THREAD

**Issue by prao-kr** [docker/for-mac#1690]
### Information

Diagnostic ID: AD4035B6-3E73-425F-99B1-7FF913AA6A34
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. 
2.

**Comment by djs55** [comment]
`Docker for Mac: 1.12.0 (Build 10871)` is a very old version. Could you manually download either a "stable" version or "edge" version from https://docs.docker.com/docker-for-mac/install/ and try again?
