### ISSUE TITLE
Uninstall Docker fails

### ISSUE THREAD

**Issue by prao-kr** [docker/for-mac#1691]
### Information

Diagnostic ID: AD4035B6-3E73-425F-99B1-7FF913AA6A34
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)

### Steps to reproduce

1. Uninstall Docker since I am unable to upgrade it
2. ...Failed with this error

**Comment by akimd** [comment]
Hi!

This version of Docker is old, and there are not many details on the effective failure.
