### ISSUE TITLE
Error when starting up Docker daemon

### ISSUE THREAD

**Issue by nolanerck** [docker/for-mac#1693]
### Expected behavior
I tried started up Docker Daemon app. Expecting it to start as normal so I can run my projects.  I've done this dozens of times on this machine.

### Actual behavior:  I received the following diagnostic output:

Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/C69AA556-2AC7-477E-BF8A-B18ECD3BF7FC/20170605-100345.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/nolanerck/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/nolanerck/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/nolanerck/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/nolanerck/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/nolanerck/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ... Try starting the Docker Daemon app
  2. ... Everything fails.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
