### ISSUE TITLE
Broken output in terminal when accessing the container via "docker exec -it"

### ISSUE THREAD

**Issue by Krzysiaczek-at-theFoundry** [docker/for-mac#1705]
### Expected behavior
I've replaced all spaces with underline to better illustrate the problem and use simple ls on main unix folder to illustrate the problem

$_docker_exec_-it_effdrop_app_1_bash
root@e2b8693ed96b:/var/www/html# ls /
bin__boot__dev_etc__home__lib__lib64__media__mnt__opt__proc__root__run__sbin__srv__sys__tmp__usr__var
root@e2b8693ed96b:/var/www/html#

### Actual behavior
$_docker_exec_-it_effdrop_app_1_bash
root@e2b8693ed96b:/var/www/html# ls /
_____________________________________bin__boot__dev_etc__home__lib__lib64__media__mnt__opt__proc__root__run__sbin__srv__sys__tmp__usr__var
______________________________________________________________________________________________________________________________________________root@e2b8693ed96b:/var/www/html#

### Information
It seems to happen after last update Version 17.06.0-rc1-ce-mac13 (18169)
however I'm not sure if there are any other factors

### Steps to reproduce the behavior

  1. docker exec -it container_name bash (or zsh the same)
  2. ls anyfolder

It's even much worse with ls -la /

root@e2b8693ed96b:/var/www/html# ls -la /
______________________________________________________________total_72
______________________________________________________________________drwxr-xr-x___1_root_root_4096_May_25_14:27_.
__________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_25_14:27_..
_______________________________________________________________________________________________________________________________________________________________-rwxr-xr-x___1_root_root____0_May_25_14:27_.dockerenv
____________________________________________________________________________________________________________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_12_23:58_bin
______________________________________drwxr-xr-x___2_root_root_4096_Apr_20_21:43_boot
_____________________________________________________________________________________drwxr-xr-x___5_root_root__340_Jun__8_09:54_dev
___________________________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_25_14:27_etc
_________________________________________________________________________________________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_Apr_20_21:43_home
____drwxr-xr-x___1_root_root_4096_May_13_00:10_lib
__________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:55_lib64
__________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:54_media
__________________________________________________________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:54_mnt
________________________________________________________________________________________________________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:54_opt
__________________dr-xr-xr-x_211_root_root____0_Jun__8_09:54_proc
_________________________________________________________________drwx------___1_root_root_4096_May_25_14:53_root
________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_13_00:10_run
______________________________________________________________________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:56_sbin
_____________________________________________________________________________________________________________________________________________________________________________________________________________drwxr-xr-x___2_root_root_4096_May__8_21:54_srv
_______________________________dr-xr-xr-x__13_root_root____0_Jun__8_09:54_sys
_____________________________________________________________________________drwxrwxrwt___1_root_root_4096_Jun__8_10:16_tmp
___________________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_13_00:55_usr
_________________________________________________________________________________________________________________________________________________________________________drwxr-xr-x___1_root_root_4096_May_13_00:52_var
_______________________________________________________________________________________________________________________________________________________________________________________________________________________root@e2b8693ed96b:/var/www/html# 

I've run Diagnostic which shows everything OK and ID is: 
[20170608-124659.tar.gz](https://github.com/docker/for-mac/files/1060778/20170608-124659.tar.gz)
1D9A1D5F-E95F-45B8-BD9D-E7B6A4D5B7E9

**Comment by deborasetton** [comment]
Looks like a duplicate of https://github.com/docker/for-mac/issues/1672

**Comment by franklinyu** [comment]
@Krzysiaczek-at-theFoundry Please verify whether this has been fixed in latest release.

**Comment by Krzysiaczek-at-theFoundry** [comment]
Yes, it looks OK.
I am on Version 17.06.0-ce-mac17 (18432) now.
Thanks
