### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 9

### ISSUE THREAD

**Issue by maxming2333** [docker/for-mac#1708]
### Actual behavior

When I open `Intellij idea 2017.1`, docker-mac immediately pop up the wrong window, on my computer is 100% reproduce the drop

like this :(

![image](https://user-images.githubusercontent.com/8816730/26941721-11a486d6-4cb2-11e7-8208-7cc3780e1ed4.png)

I tried #1198 and #1071 ，But it does not work for me

----

Now my computer docker-mac and Intellij idea can only choose one :(

### Information

```docker
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/980C3666-ED04-4546-AC66-194193916BF3/20170609-011629.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

```

### Steps to reproduce the behavior

  1. Start `docker` app
  2. Wait for the docker state to switch to `running`
  3. Start `Intellij idea 2017.1` app
  4. And then an error message will pop up

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
