### ISSUE TITLE
docker on mac Fatal Error: Communication with networking components failed.

### ISSUE THREAD

**Issue by aishenghuomeidaoli** [docker/for-mac#1711]
### Actual behavior
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/1A4A615C-7C71-4823-A781-26026910D4B3/20170609-150202.tar.gz
failure: com.docker.slirp is not running
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/zhujiawei/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/zhujiawei/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/zhujiawei/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/zhujiawei/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         wrong Docker version: 17.05.0-ce (expected 17.03.1-ce)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/zhujiawei/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. start docker client, 'Docker needs privileged access', click ok
  2. input password

**Comment by mattmadhavan** [comment]
Hello,
I have the same issues. Any resolution?

Thanks
Matt

**Comment by aishenghuomeidaoli** [comment]
@mattmadhavan I installed [boot2docker](http://boot2docker.io/).
Before to start docker, you need:
`boot2docker start`
`eval "$(boot2docker shellinit)"`
I didn't find a more convenient way, however it works anyway.
