### ISSUE TITLE
Docker Mac disk check failed with: Failure

### ISSUE THREAD

**Issue by glynjackson** [docker/for-mac#172]
Restarting Docker for Mac produces and error and crashes, running diagnostic shows below. 
Tested on demo machine running Mac: 1.12.0-beta21 (Build 11019).

### Information
```
Diagnostic ID: 2E233303-9DA3-4031-A85A-E482D78CC019
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/user/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/2E233303-9DA3-4031-A85A-E482D78CC019/20160808-133035/qemu-img-check.stdout 2> /tmp/2E233303-9DA3-4031-A85A-E482D78CC019/20160808-133035/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by glynjackson** [comment]
Fixed by running virtual box remove tool https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Installer/darwin/DiskImage/VirtualBox_Uninstall.tool

Related to https://github.com/docker/for-mac/issues/4

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
