### ISSUE TITLE
Docker registry Keychain credentials have weird "Where" value

### ISSUE THREAD

**Issue by intgr** [docker/for-mac#1721]
### Expected behavior

Docker registries are using HTTPS, so I would expect a value of https://REGISTRY_NAME

### Actual behavior

The "Where" field in Keychain contains "http:///" -- which suggests insecure HTTP and has three slashes -- not a valid URL.

### Information

See screenshot:
![screen shot 2017-06-12 at 13 53 26x](https://user-images.githubusercontent.com/137616/27039894-058b5e5e-4f98-11e7-9c97-e00e3b4546ff.png)

### Steps to reproduce the behavior

  1. Run command line: docker login REGISTRY_NAME
  2. Look at the "Docker Credentials" entry in macOS Keychain.

**Comment by jeremie-olivier** [comment]
Same for me

**Comment by intgr** [comment]
I looked into how the Keychain database works and it seems two changes need to be made:

1. "ptcl" field should be "htps" (yes, single t) fot HTTPS.
2. For the hostname, you should use the "srvr" field instead of "path"

```
% security find-internet-password -l "Docker Credentials"
keychain: "/Users/XXXXXXXXXX/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="Docker Credentials"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="XXXXXXXXXX"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303137303631353037313032385A00  "20170615071028Z\000"
    "crtr"<uint32>="aapl"
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303137303631353037313032395A00  "20170615071029Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>="docker.XXXXXXXXXXXXXX"   // <--- Docker hostname is stored here
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>="http"                  // <--- Wrong protocol
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>=<NULL>                    // <--- Hostname should be here instead
    "type"<uint32>=<NULL>
```

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/docker-credential-helpers/pull/72 (osx-keychain-helper 0.5.2), which will be part of docker for mac 17.06 (rc4 coming soon)

You can probably download and install the updated version of the helper from https://github.com/docker/docker-credential-helpers/releases/tag/v0.5.2 to resolve before that

**Comment by intgr** [comment]
Sorry, I confirm that this was fixed in 2017 already. Closing.
