### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by cptaffe** [docker/for-mac#1722]
### Expected behavior

Docker starts when I open it

### Actual behavior

Docker crashes with 'unable to start' popup

### Information

Diagnostic ID: 11166ED7-A8F2-4379-BBE2-438888D842FA

Output:

Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/11166ED7-A8F2-4379-BBE2-438888D842FA/20170612-102126.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/connortaffe/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/connortaffe/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/connortaffe/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/connortaffe/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/connortaffe/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/connortaffe/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

1. Uninstall Docker Edge, Install regular Docker (because crashes)
2. Open it two or three times

**Comment by xuqingkuang** [comment]
I have the same issues.

**Comment by jimagic** [comment]
Get same issues too.

**Comment by cptaffe** [comment]
Uninstalling docker, rebooting, then reinstalling docker and doing a factory reset of docker resolved this for me. Factory resets before I rebooted didn't help.

**Comment by akimd** [comment]
That's weird...  But solved :)  Thanks!
