### ISSUE TITLE
ONBUILD no such image

### ISSUE THREAD

**Issue by raymondhardy** [docker/for-mac#1723]
### Expected behavior
   When an image has an ONBUILD ADD . step it should add files from the build dir

### Actual behavior

   Docker errors with No such image

### Information

  - Diagnostic ID 10F66607-FA9F-4A92-8F96-695DE6789E1D
  - MY docker file
     FROM mattoddie/hugo:latest

  - Also happens on LINUX 17.06.0-ce-rc2-dind
### Steps to reproduce the behavior

  1. Try to build a container from a docker image that has an ONBUILD ADD commend
  2. Watch docker spew error at you

**Comment by shin-** [comment]
I can confirm this also happens with 17.06.0 RC2 on Ubuntu 16.04

Tested with `mattoddie/hugo:latest` and `node:0.10-onbuild`

**Comment by dnephin** [comment]
Fixed by https://github.com/moby/moby/pull/33500 , will be in rc3

**Comment by pgayvallet** [comment]
Seems fixed. Closing.
