### ISSUE TITLE
Can not restart Docker

### ISSUE THREAD

**Issue by 0xCMP** [docker/for-mac#1729]
### Expected behavior
After docker has issue previously reported (#1582 #1496)

Go to menu -> Restart -> See "Restarting..." -> See "Running" -> Able to use docker again

### Actual behavior
Go to menu -> Restart -> See "Running" (No change)

### Information

Diagnostic ID: `70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170613-180921.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

1. Go to menu bar
1. Click "Restart" button
1. See "Running" (No change)

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
