### ISSUE TITLE
Docker-cli slowly and busy

### ISSUE THREAD

**Issue by latyshas** [docker/for-mac#173]
### Information

Diagnostic ID: 2D0530A0-B759-454E-BD52-377BD1D33511
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
1. I had integration tests which used docker images for running app. 
2. I started 2 instances: 1. for app, 1 for DB.
3. I start and remove this instances more than 10 times in day, and after it sometimes docker-cli can't answer on my commands, like this: docker ps - result "command frozen"

**Comment by mchiang0610** [comment]
Merging with #119
