### ISSUE TITLE
Docker attempting to access other credential keychain

### ISSUE THREAD

**Issue by t3h2mas** [docker/for-mac#1731]
### Expected behavior
Docker only requires sudo access for updates

### Actual behavior
Docker attempts to access other osx keychain credentials

### Information

Version: 17.06.0-ce-rc2, build 402dd4a

<img width="437" alt="cred" src="https://user-images.githubusercontent.com/598146/27137192-84959fb4-50da-11e7-86a4-b2a8b704c7e8.png">

### Steps to reproduce the behavior

Happens after boot

I hope this **is** Docker and not a malicious agent...

**Comment by ebriney** [comment]
@t3h2mas : Yes, this is from Docker :) We are investigating this issue but don't find where it comes from for now. Did you logout in cloud federation or hub previously?

**Comment by t3h2mas** [comment]
@ebriney I'm not %100 sure what those are, but I don't think so.
