### ISSUE TITLE
Error while pushing images to registry: `dial tcp: lookup registry on 192.168.65.1:53: no such host`

### ISSUE THREAD

**Issue by aliksend** [docker/for-mac#1733]
### Expected behavior

Image successfully sent to registry. 

### Actual behavior

An error
```
The push refers to a repository [registry:5000/test_image]
Get https://registry:5000/v1/_ping: dial tcp: lookup registry on 192.168.65.1:53: no such host
```

### Information

  - _Full output of the diagnostics from "Diagnose & Feedback" in the menu._ 

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/F68FB852-1DA3-4C86-98A7-0393B6CE4B5A/20170615-024242.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
Also I have a Diagnostic ID: `F68FB852-1DA3-4C86-98A7-0393B6CE4B5A`

  - _A reproducible case if this is a bug, Dockerfiles FTW_

I think [minimal configuration that I can provide](https://github.com/aliksend/docker-test) is it:
1. I want to build docker images inside docker container (`builder`) and sent it to registry container (`registry`). I want to use `docker-compose` to work with. So my `docker-compose.yml` is 
```
version: '3'
services:
  registry:
    image: registry
    ports:
      - 5000:5000

  builder:
    build: ./builder
    volumes:
      - ./test_image:/workdir/image:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - registry
```
2. My `builder`'s image Dockerfile
```
FROM alpine

RUN apk add --update docker

WORKDIR /workdir
ADD run.sh .
RUN chmod +x run.sh
VOLUME /workdir/image

CMD ["./run.sh"]
```
and script `run.sh` that actually builds image
```
#!/bin/sh
cd /workdir/image
docker build -t registry:5000/test_image .
docker push registry:5000/test_image
```
3. My `test_image`'s Dockerfile
```
FROM alpine
CMD ["echo", "Hello world"]
```

  - _Page URL if this is a docs issue or the name of a man page_ 

I found such issues like mine, but its not solves my problem.

### Steps to reproduce the behavior

```
> docker-compose up --build
... (some logs about build process)
Attaching to dockertest_registry_1, dockertest_builder_1
... (some logs about starting registry_1)
builder_1   | Sending build context to Docker daemon  2.048kB
builder_1   | Step 1/2 : FROM alpine
builder_1   |  ---> a41a7446062d
builder_1   | Step 2/2 : CMD echo Hello world
builder_1   |  ---> Running in 6ddc6cc4e1c9
builder_1   |  ---> 7c436e915696
builder_1   | Removing intermediate container 6ddc6cc4e1c9
builder_1   | Successfully built 7c436e915696
builder_1   | The push refers to a repository [registry:5000/test_image]
builder_1   | Get https://registry:5000/v1/_ping: dial tcp: lookup registry on 192.168.65.1:53: no such host
dockertest_builder_1 exited with code 1
```

I think I should specify that `registry` successfully `ping`'s from `builder`, also I can't find any IP like `192.168.65.x` neither on my mac, nor in `docker network`, nor inside any container. But `192.168.65.1` successfully `ping`'s from builder.

**Comment by ebriney** [comment]
Hi, from the doc [here](https://docs.docker.com/registry/#alternatives), you must not tag your images with the name of the container running the registry but the `name/ip:port` of the registry host.
Using `0.0.0.0:5000`, `localhost:5000` is working for me.

**Comment by ebriney** [comment]
From [here](https://docs.docker.com/registry/introduction/) too:
Image names as used in typical docker commands reflect their origin:

`docker pull ubuntu` instructs docker to pull an image named ubuntu from the official Docker Hub. This is simply a shortcut for the longer `docker pull docker.io/library/ubuntu command`

`docker pull myregistrydomain:port/foo/bar` instructs docker to contact the registry located at `myregistrydomain:port` to find the image `foo/bar`

**Comment by aliksend** [comment]
Running registry on host and pushing there is working good for me.
The problem arises when I try to push image from docker container to registry also launched using docker.
I tried to do like described in [this doc](https://docs.docker.com/registry/#tldr):
```
docker build -t test_image .
docker tag test_image registry:5000/test_image
docker push registry:5000/test_image
```
but result is same.

About naming all is ok, I use name `registry:5000/test_image` that mean that I want use image `test_image` from host `registry:5000` and it is all true.

Error was while connecting to `192.168.65.1:53`, this port is used by DNS, I think that docker tries to get IP for hostname `registry` using DNS server on `192.168.65.1`. This IP is inside `/etc/resolv.conf`:
```
> cat /etc/resolv.conf
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain AsusRouter
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
```
(my mac connects to internet through my Asus router, but it uses `192.168.1.x` net).
I will dig later to find source of problem.

**Comment by aliksend** [comment]
I also tries (according to [docs about DNS in containers](https://docs.docker.com/engine/userguide/networking/configure-dns/)) to 
```
echo 'nameserver 127.0.0.11' > /etc/resolv.conf
```
and `google.com` and `registry` still pings ok
I also tries (according to `127.18.0.1` is gateway for that container) to
```
echo 'nameserver 172.18.0.1' > /etc/resolv.conf
```
and now `google.com` and `registry` isn't pings at all (I now have error `ping: bad address 'google.com'`).
But in both configuration `docker push` still gives me error 
`dial tcp: lookup registry on 192.168.65.1:53: no such host`.
My host's `/etc/resolv.conf` is 
```
domain AsusRouter
nameserver 192.168.1.1
```
I can not understand where the docker takes that ip – `192.168.65.1`.

**Comment by aliksend** [comment]
If I correctly understand [this topic](https://news.ycombinator.com/item?id=11352594) then I can say that source of problem is inside Linux that runned into xhyve on Mac machine. But I'm not sure that I can change something in it, docker official site says nothing about how Docker for Mac works and how it can be configured.
Adding `"dns" : [ "127.0.0.11"  ],` to Docker –> Preferences –> Daemon –> Advanced has no effect.

**Comment by aliksend** [comment]
So I was fixed it but I don't like this fix.

I just changed from `registry:5000` to `localhost:5000` because of my docker daemon runned on host and when it tries to connect to registry it tries to find that hostname not in builder (container) environment, but in host's environment. Now the host's docker daemon tries to connect to host's registry (that in fact registry runned in container with mapped ports) and works good.

But I think that will be more intuitively to use registry container without mapping to host and refer to it from containers using hostname. But in fact, not container's docker binary connects to registry, but docker daemon, that runs in host...

FTW, it is so hard to decide. Nevertheless, the problem is solved. Thank you all.

UPD: Thanks @ebriney, I understand your first comment only now.

**Comment by head1328** [comment]
I had the same problems and fixed it by using dnsmasq. Unfortunately it was not possible to use *.local domains - I don't know why. So I switched to .dev domains for local development.

    brew install dnsmasq
    echo 'address=/dev/127.0.0.1' > $(brew --prefix)/etc/dnsmasq.conf
    sudo cp $(brew --prefix dnsmasq)/homebrew.mxcl.dnsmasq.plist /Library/LaunchDaemons
    sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    sudo mkdir -v /etc/resolver
    sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/dev'
    sudo bash -c 'echo "domain dev" >> /etc/resolver/dev'
    sudo bash -c 'echo "search_order 1" >> /etc/resolver/dev'

After that something like this `docker push anything.anything.dev:5000/jenkins-master:1.0.0` works like a charme.

**Comment by bbaassssiiee** [comment]
I have a multihomed linux host for docker and an internal registry on another host. Enabling the``` --insecure-registry``` based on a **hostname** got me the same ```no such host``` error. 

- [x] When I used the **ip address** it worked. 

- [ ] Docker pull's host resolution does not honor `/etc/nsswitch.conf`
