### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by lisettemazure** [docker/for-mac#1734]
Since a few days, when I'm running docker, several times a day I get this error:
**Error response from daemon: Bad response from Docker engine**

After getting this error, I have to redo pygmy up + docker-compose up -d
(using pygmy gem Version: 0.9.7 and amazee with docker.)

I already did a reset to factory defaults, but this didn't seem to help.

Ran the diagnose to see if there is any issue, but it seems all is ok

Docker for Mac: version: 17.06.0-rc2-ce-mac14 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/826EC446-14F3-49AC-BE78-5F052948CCBC/20170615-094401.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Does anyone have an idea what's happening and how I can fix this? Thanks

**Comment by ahnick** [comment]
This same thing is happening to me as well and making Docker unusable.  I even updated to the latest version of Edge again today and it is still happening.  No idea how to fix.

Version 17.06.0-rc4-ce-mac15
Mac OS X: Version 10.11.6

**Comment by albertocap** [comment]
it happened to me too. But after 10-15 minutes from restart worked without doing anything. Slow start?

**Comment by lisettemazure** [comment]
It looked to me the issue was somewhat ok with 1 update (Got to keep it running for an entire day without error), but this morning it asked to update again and now the issue occurs again.
Version 17.06.0-ce-rc5-mac16

**Comment by jbw976** [comment]
I'm seeing this with the following version:
```
> docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64
Error response from daemon: Bad response from Docker engine
```
Quitting docker for mac and relaunching it will make it OK again but after a few minutes it returns to this bad response state.  Any ideas on how to debug further?

**Comment by Xs-and-10s** [comment]
@jbw976 I'm seeing the exact same thing
