### ISSUE TITLE
Connection refused error in Docker on Mac startup

### ISSUE THREAD

**Issue by brian-macdonald-zonar** [docker/for-mac#1736]
### Expected behavior
Docker should start without issues when I start my Mac (Mac OS X, macOS Sierra, MacBook Pro, Processor 2.2 GHz Intel Core I7, Memory 16GB, Graphics, Intel Iris Pro 1536 MB)
### Actual behavior
Docker popped up a "Error loading Docker" modal dialog window (paraphrasing the message) followed by a Diagnose window. I chose to do so, and afterward, I clicked Open Issues and this is where I ended up.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/20EB9428-0E87-4D3C-B482-65709CDB24BF/20170615-081914.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/brian.macdonald/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/brian.macdonald/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/brian.macdonald/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/brian.macdonald/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/brian.macdonald/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Installed Docker (Version 17.03.1-ce-mac12 (17661), channel: stable)
  2. Shutdown Mac
  3. Start up Mac

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
