### ISSUE TITLE
Mariadb image shuts down inexpectedly after some working with "Unexpected API error" Version 17.06.0-rc2-ce-mac14 (18280) Mac OSx 10.12.5 (16F73)

### ISSUE THREAD

**Issue by drummerroma** [docker/for-mac#1737]
Version 17.06.0-rc2-ce-mac14 (18280)
Mac OSx 10.12.5 (16F73)

dbthema    | 2017-06-15 17:46:02 139650368064256 [Note] mysqld: Normal shutdown
dbthema    |
dbthema    | 2017-06-15 17:46:02 139650368064256 [Note] Event Scheduler: Purging the queue. 0 events
dbthema    | 2017-06-15 17:46:02 139649603303168 [Note] InnoDB: FTS optimize thread exiting.
dbthema    | 2017-06-15 17:46:02 139650368064256 [Note] InnoDB: Starting shutdown...
dbthema    | 2017-06-15 17:46:04 139650368064256 [Note] InnoDB: Shutdown completed; log sequence number 22716437
dbthema    | 2017-06-15 17:46:04 139650368064256 [Note] mysqld: Shutdown complete
dbthema    |
Unexpected API error for dbthema (HTTP code 502)
Response body:
Bad response from Docker engine

**Comment by ahnick** [comment]
I'm also getting this and I upgraded to the latest version of Docker For Mac Edge () and it is still happening.  This issue looks to be the same as this one here https://github.com/docker/for-mac/issues/1734.  There is some major issue going on with the latest Docker For Mac Edge builds as this was not happening a few releases back.

**Comment by ahnick** [comment]
I have temporarily gone back to Docker For Mac stable and I am no longer having the issue.  Docker For Mac edge is unusable for me until this is resolved.

**Comment by pgayvallet** [comment]
@ahnick is the issue still present in the latest stable ?

If so, could you provide a reproduction scenario ?
