### ISSUE TITLE
com.docker.osxfs is not running

### ISSUE THREAD

**Issue by emberdyn** [docker/for-mac#174]
### Information

Diagnostic ID: 5313C906-8AAF-4C31-93AC-5E88F95289DB
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Thanks for your report. This is a previously unknown issue.

**Comment by emberdyn** [comment]
I completely removed virtual box and now I get this.  

`Docker for Mac: version: mac-v1.12.0-beta21.1
OS X: version 10.12 (build: 16A270f)
logs: /tmp/AD6703D2-F16D-4028-A352-299C5E7A3D49/20160808-133613.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
`

But I get the error:

vmstateevent invalid json:

**Comment by dsheets** [comment]
That error is tracked by #64.

**Comment by scls19fr** [comment]
Similar issue with a fresh install of macOS Sierra - public beta 6
(no update)

```
Diagnostic ID: 7042297D-E3AA-461E-9981-92F96B1B9C04
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
```

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
