### ISSUE TITLE
After sleeping, client loses connection

### ISSUE THREAD

**Issue by 0xCMP** [docker/for-mac#1741]
### Expected behavior
When I go to sleep and turn the computer back on if my terminal looks the same it is still connected.

If Docker is running it is still working. If I can access the service running in Docker then there is not an issue.
### Actual behavior
The connection appears lost. I was running a `./manage.py shell_plus` command in Docker and trying to exit it has hung for almost 5 minutes now.

Took a seemingly long time to get diagnostic data
### Information

Diagnostic ID: `70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5`

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/70A09CB7-F1E2-4655-94CB-D54F3BEBA6F5/20170616-162818.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
1. Run a container with something like IPython with a connection to another container (DB in this case)
1. Run a few commands
1. Put computer to sleep
1. Wait about an hour (go to lunch)
1. Come back and bring computer back
1. Do something else (browse HN, etc.)
1. Attempt to stop the running container

The container should stop responding but with no error. Docker should report no errors. All diagnostic so apparently be great except the fact that all input is accepted but ignored.

**Comment by xmjiao** [comment]
I am having the same issue after upgrading to Docker Version 17.06.0-ce-mac18 on macOS 10.12.5.  Never had issues with 17.03.1 though.

**Comment by 0xCMP** [comment]
I haven't seen this in the later versions so I'll assume this is fixed
