### ISSUE TITLE
Link to experiemental features documentation is broken in latest rc4 on docker for mac

### ISSUE THREAD

**Issue by beenanner** [docker/for-mac#1744]
### Expected behavior
Link out to documentation should not return a page not found. 
### Actual behavior
Returns a page not found.
### Information

The link on Docker for Mac for the Experimental features in the settings point to moby/moby instead of docker/cli where the docs now live. It appears it was caused by https://github.com/moby/moby/commit/b5579a4ce33af4c1f67118e11b5a01008a36d26a

### Steps to reproduce the behavior

  1. Install Docker for Mac ("17.06.0-rc4-ce-mac15")
  2. Open preferences
  3.  Click on daemon settings
  4. Click the Basic tab
  3. Click the "features" link for viewing experimental features.

**Comment by gtardif** [comment]
Fixed with 17.06.0 final (mac & win)

**Comment by beenanner** [comment]
Sweet thanks @gtardif!
