### ISSUE TITLE
Docker for Mac Failed to Start: com.docker.osx.hyperkit.linux failed to start Exit code 1

### ISSUE THREAD

**Issue by lonedevel** [docker/for-mac#1745]
### Expected behavior

Docker should start up.

### Actual behavior

Docker not starting and raises error: Fatal Error:  com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Diagnostic ID 033F3C3F-C6B7-42D8-89EE-3DEC9991E15B

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/033F3C3F-C6B7-42D8-89EE-3DEC9991E15B/20170617-150323.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rmichaud/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/rmichaud/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmichaud/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rmichaud/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/rmichaud/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rmichaud/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

Just  trying to start up Docker.

**Comment by lonedevel** [comment]
Apologies for the fire drill.   This was a **User Error** (namely, me).    I have my Docker.qcow2 file on an external drive and the drive wasn't mounted after I rebooted my system.   Its resolved now.  You can close this issue.

**Comment by kizbitz** [comment]
Thanks for the update. Closing
