### ISSUE TITLE
When I update to mac osx 10.12.5, docker has error with virtualbox

### ISSUE THREAD

**Issue by tuan072090** [docker/for-mac#1755]
When I start docker, I get this error "Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30 VirtualBox v4.3.28 is currently installed. Please upgrade or uninstall Virtualbox" 

Anyone has the same issue?

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by slchorne** [comment]
same problem here.
and virtual box isn't installed on my mac, unless there is a lingering file somewhere.

**Comment by b3nzchr3ur** [comment]
Same problem. Virtualbox was present originally. After removing it and all related files in ~/Library, and system restart the issue is still there.

**Comment by tuan072090** [comment]
I installed virtualbox again and the problem was fixed.

**Comment by dsheets** [comment]
You must either use the VirtualBox uninstaller or upgrade VirtualBox. Incomplete uninstallations of VirtualBox can leave the kernel module still loaded which will cause Docker for Mac to refuse to start.
