### ISSUE TITLE
Unable to add privileges to helpers on initial startup

### ISSUE THREAD

**Issue by hachi8833** [docker/for-mac#1760]
### Expected behavior

On launching Docker for Mac, enter your admin name and password into the dialog to add privileges to Docker's helpers, and then starts Docker for Mac

### Actual behavior

On launching Docker for Mac, enter your admin name and password into the dialog, and the same dialog shows again. Cannot proceed from here.

### Information

  - Unable to execute "Diagnose & Feedback" in the menu yet.
  - Tried with several versions of Docker for Mac, including stable and edge versions, but all the results are the same.
  - Uninstalling Docker for Mac completely, including all configs, does not change the behavior.
  - I suspect that some system configurations for adding privileges to Docker for Mac might have been break a little bit. I'd be glad if someone tell me how to cleanup the very system configuration for Docker for Mac.

### Steps to reproduce the behavior

  n/a

**Comment by hachi8833** [comment]
From console:

> Failed to read values in CFPrefsPlistSource<0x6080000ee600> (Domain: group.com.docker, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
> 2017-06-21 23:13:59.512 Docker[36127:1549905] Could not connect action, target class Docker.StatusItem does not respond to -DockerIDActionReceived:

**Comment by hachi8833** [comment]
Quite similar to #1753 and #1520

**Comment by dkfx** [comment]
I have the same issue. The fix for #1520 didn't resolve the issue for me.

**Comment by hachi8833** [comment]
Finally the issue has been resolved by performing an OS clean-installation.
