### ISSUE TITLE
uploading to amazon ecr hangs

### ISSUE THREAD

**Issue by jimzucker** [docker/for-mac#1762]
### Expected behavior
running 
$(aws ecr get-login --region us-west-2 --profile production)
successfully logs into docker

### Actual behavior
Odd the other day it is hanging, now I get this error.

➜  docker git:(FP-802_new_wire_instructions) ✗ $(aws ecr get-login --region us-west-2 --profile fundpaas-demo)
unknown shorthand flag: 'e' in -e
See 'docker login --help'.

On a linux machine that we have not changed in many weeks it is still working as expected. It was working on the mac until the recent update.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
       497982F9-E3EA-4047-A1F9-D07F360DE7E1

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

AWS CLI Version
➜  aws ecr --version
aws-cli/1.11.75 Python/2.7.11 Darwin/16.6.0 botocore/1.5.38

Command generated by AWS ECR
aws ecr get-login --region us-west-2 --profile fundpaas-demo
docker login -u AWS -p xxxxxxxxxx    == -e none https://xxxxxxx.dkr.ecr.us-west-2.amazonaws.com

### Steps to reproduce the behavior

  1. execute $(aws ecr get-login --region us-west-2 --profile production)
  2. ...

**Comment by jimzucker** [comment]
I tested removing the -e and it works

I am checking to see if I can update AWS CLI

**Comment by jimzucker** [comment]
Updated AWS CLI but issue persists

➜  /tmp curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8584k  100 8584k    0     0  2807k      0  0:00:03  0:00:03 --:--:-- 2808k
➜  /tmp unzip awscli-bundle.zip

Archive:  awscli-bundle.zip
  inflating: awscli-bundle/install
  inflating: awscli-bundle/packages/jmespath-0.9.3.tar.gz
  inflating: awscli-bundle/packages/argparse-1.2.1.tar.gz
  inflating: awscli-bundle/packages/six-1.10.0.tar.gz
  inflating: awscli-bundle/packages/ordereddict-1.1.tar.gz
  inflating: awscli-bundle/packages/colorama-0.3.7.zip
  inflating: awscli-bundle/packages/futures-3.1.1.tar.gz
  inflating: awscli-bundle/packages/docutils-0.13.1.tar.gz
  inflating: awscli-bundle/packages/simplejson-3.3.0.tar.gz
  inflating: awscli-bundle/packages/python-dateutil-2.6.0.tar.gz
  inflating: awscli-bundle/packages/PyYAML-3.12.tar.gz
  inflating: awscli-bundle/packages/awscli-1.11.110.tar.gz
  inflating: awscli-bundle/packages/botocore-1.5.73.tar.gz
  inflating: awscli-bundle/packages/s3transfer-0.1.10.tar.gz
  inflating: awscli-bundle/packages/virtualenv-15.1.0.tar.gz
  inflating: awscli-bundle/packages/rsa-3.4.2.tar.gz
  inflating: awscli-bundle/packages/pyasn1-0.2.3.tar.gz
➜  /tmp sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

Password:
Sorry, try again.
Password:
Running cmd: /usr/local/opt/python/bin/python2.7 virtualenv.py --python /usr/local/opt/python/bin/python2.7 /usr/local/aws
Running cmd: /usr/local/aws/bin/pip install --no-index --find-links file:///private/tmp/awscli-bundle/packages awscli-1.11.110.tar.gz
Symlink already exists: /usr/local/bin/aws
Removing symlink.
You can now run: /usr/local/bin/aws --version
➜  /tmp aws ecr --version
aws-cli/1.11.110 Python/2.7.11 Darwin/16.6.0 botocore/1.5.73
➜  /tmp $(aws ecr get-login --region us-west-2 --profile fundpaas-demo)
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
➜  /tmp

**Comment by kinghuang** [comment]
The `-e/--email` flag on `docker login` was [deprecated in Docker 1.11.0](https://docs.docker.com/engine/deprecated/#-e-and---email-flags-on-docker-login), and removed in Docker 17.06.0. You should have received an email and [notification](https://phd.aws.amazon.com/phd/home#/event-log?Event%20ARN=arn:aws:health:global::event/AWS_ECR_OPERATIONAL_NOTIFICATION_81c4627f-d164-4f90-9eba-0bbad31e9fd2&eventID=arn:aws:health:global::event/AWS_ECR_OPERATIONAL_NOTIFICATION_81c4627f-d164-4f90-9eba-0bbad31e9fd2&eventTab=details&layout=vertical) from Amazon around May 23 about the new `--no-include-email` flag on `aws ecr get-login` for compatibility with 17.06.0.

Here's the corresponding issue in aws-cli: aws/aws-cli#1926.

**Comment by jimzucker** [comment]
@kinghuang We can use your solution like this: $(aws ecr get-login --region us-west-2 --profile fundpaas-demo --no-include-email)

Before we close the ticket, how can we get this published by AWS for ECR I got this command from them. Let me run a test and confirm they dont pass it on new setups.

**Comment by jimzucker** [comment]
We can close this creating a new repo gives the correct command.  Not sure if there are release notes someplace for docker that should note it.

![image](https://user-images.githubusercontent.com/14372687/27417577-5b7b5286-56ca-11e7-9b00-4ab6204fe46e.png)

**Comment by duginivijay** [comment]
Installing or upgrading AWSCLI doesn't prevent from throwing the error. We still got to use the command as below.

$ aws ecr get-login --no-include-email
