### ISSUE TITLE
Unable to use the dockerd config json to add hosts

### ISSUE THREAD

**Issue by briantd** [docker/for-mac#1765]
### Expected behavior
Docker-for-mac restarts with new dockerd settings -- namely having dockerd listen on a port (e.g. 127.0.0.1:9999)

### Actual behavior
Docker-for-mac restarts and hangs indefinitely

`cat ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring`
shows that the client cannot listen to the docker `unix:///var/run/docker.sock`

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Diagnostic ID = 21F1FD09-A99B-4ECD-9301-1BB2A8431127

```
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/21F1FD09-A99B-4ECD-9301-1BB2A8431127/20170622-132302.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
### Steps to reproduce the behavior

  1. Click menubar icon -> Preferences -> Daemon -> Advanced
  2. Try editing the text window to change the "hosts" setting:
E.g.
```
{
    "hosts": [ "unix:///var/run/docker.sock" ]
}
```
or
```
{
    "hosts": [ ]
}
```
or
```
{
    "hosts": [ "unix:///var/run/docker.sock", "tcp://127.0.0.1:9999"]
}
```

The dialog box accepts these as valid JSON.

**Comment by elmigranto** [comment]
@briantd and everyone interested in the workaround for this

```
brew install socat
socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock
```

More info https://stackoverflow.com/a/2150188
