### ISSUE TITLE
docker-diagnose exit code is 1

### ISSUE THREAD

**Issue by Roybaka** [docker/for-mac#1769]
### Actual behavior

docker-diagnose exit code is 1

### Information

Diagnostic ID: 1FD9FCD6-E117-4DBA-BCC8-6AA7CD59FBB9

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/1FD9FCD6-E117-4DBA-BCC8-6AA7CD59FBB9/20170623-162716.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/BlackSwan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/BlackSwan/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/BlackSwan/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/BlackSwan/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/BlackSwan/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/BlackSwan/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Start Docker app
  2. ...

**Comment by jasonbivins** [comment]
Hi @Roybaka are you able to get into the Docker GUI at all? If so, please try the Reset to factory defaults feature to clear out the settings.

**Comment by Roybaka** [comment]
Hi @jasonbivins Thanks to help me. Sorry for my late response
I don't able to get into the Docker GUI.
I just can a docker-diagnostic.
Do you have a idea ?
