### ISSUE TITLE
Containers are stopped after Mac "awakes" of hibernation

### ISSUE THREAD

**Issue by thorstensiefert** [docker/for-mac#1772]
Leaving the hibernation mode I expected that the containers should be in the same state as before. Started containers should still be started.  

Actually the containers, which where running before entering the hibernation mode, are stopped and Docker is restarting. So I have to do a `docker-compose up -d` to get my containers back to work. The containers are fully functional. There is no data loss. But this behavior is "a little bit" annoying.

### Information
Diagnostic ID = 6620CFC8-18BC-459F-AA45-870C9CE28203  

```
Docker for Mac: version: 17.06.0-ce-rc5-mac16 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/6620CFC8-18BC-459F-AA45-870C9CE28203/20170624-093535.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Excerpt from `system.log` :

```
Jun 24 09:34:55 MBP Docker[4608]: Volume.stop 14aa295b59329c2b24953568419a191e804e9c167312db0b838dce394db5a45f (paths = [PATH:state=default])
Jun 24 09:34:55 MBP Docker[4608]: Volume.stop 193f550844dc496148a3b117e310f97830ddc2829fadda5f97d8635a4a9a8603 (paths = [PATH:state=default])
Jun 24 09:34:59 MBP Docker[4609]: While watching /etc/resolv.conf: ENOENT
Jun 24 09:35:06 MBP Docker[4608]: Fatal unexpected exception: Socket.Closed
Jun 24 09:35:10 MBP Docker[4748]: Logging to Apple System Log
Jun 24 09:35:10 MBP Docker[4749]: Logging to Apple System Log
Jun 24 09:35:10 MBP Docker[4749]: Setting handler to ignore all SIGPIPE signals
Jun 24 09:35:10 MBP Docker[4749]: vpnkit version bf12479503927f871e6f0199ee124f2187615991 with hostnet version   uwt version 0.1.0 hvsock version 0.13.0 
Jun 24 09:35:10 MBP Docker[4749]: System SOMAXCONN is 128
Jun 24 09:35:10 MBP Docker[4749]: Will use a listen backlog of 32
Jun 24 09:35:10 MBP Docker[4749]: starting port forwarding server on port_control_url:fd:4 vsock_path:PATH/Containers/com.docker.docker/Data/connect
Jun 24 09:35:10 MBP Docker[4749]: DNS names  will map to local IP 192.168.65.1
Jun 24 09:35:10 MBP Docker[4749]: 2 upstream DNS servers are configured
Jun 24 09:35:10 MBP Docker[4749]: attempting to reconnect to database
```

### Steps to reproduce the behavior

  1. Set Mac to hibernation via menu or just close the lid on MB
  2. Wait....
  3. Wake Mac up - Docker is restarting - Containers are stopped
  4. `docker-compose up -d` restarts them.

**Comment by hwong** [comment]
Running into the same issue on `Docker version 17.06.0-ce-rc5, build b7e4173` and 10.12.5.

**Comment by matthewberryman** [comment]
+1 
Docker 
Version 17.06.0-ce-rc5-mac16 (18400)
Channel: edge
6cc0236e3b

macOS 10.12.6 Beta (16G18a)

**Comment by zorfling** [comment]
Seeing the same issue when disconnecting from Cisco AnyConnect VPN. 

Seems like the change to the networking stack is fatal-ing or something? Interestingly it doesn't occur on connection to VPN which you'd expect might do the same.

**Comment by djs55** [comment]
Thanks for the report and the uploaded logs. The logs have:

```
 Triggering a VM reboot because proxy settings changed from mai
n.proxySettings{http:"", https:"", exclude:""} to main.proxySettings{http:"", https:"", exclude:"*.local, 169.254/16"}
```

This appears to be the same as #1809

HTTP proxies are configured by modifying the environment variables inside the VM, which requires a VM restart whenever the variables change. In this case perhaps it's unnecessary to reboot when the exclude changes, when there is no actual proxy set.

As a workaround try setting: Whale Menu -> Proxies -> No proxies.

**Comment by djs55** [comment]
The unnecessary reboot caused by the `exclude` changing when there is no proxy set has been cherry-picked into the branch for 17.06.1, which should hopefully be released later this week. Thanks for your report!

**Comment by thorstensiefert** [comment]
[This](https://github.com/docker/for-mac/issues/1772#issuecomment-312611741) seems to work at the moment. Tested it yesterday evening and today. 

Hopefully 17.06.1 will be released quite soon. 😉 
I think we can close this issue for now. 
Thanks for the support guys!
