### ISSUE TITLE
MacOS com.docker.driver.amd64-linux -db is not running

### ISSUE THREAD

**Issue by Jason-Bai** [docker/for-mac#1774]
### Information

Diagnostic ID: 092AABE6-9E35-457D-9DBB-2F112644FF95
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.5 (Build 16F73)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
