### ISSUE TITLE
macOS Docker Image Size At First Run

### ISSUE THREAD

**Issue by loretoparisi** [docker/for-mac#1782]
At very first docker startup, my docker image has been created, and keep growing up to 2,2-2,4GB.
I do not have any container built, and no image downloaded or layer.
```
ls -lh /Users/loretoparisi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 
-rw-r--r--@ 1 loretoparisi  staff   2,3G 27 Giu 17:35 /Users/loretoparisi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

I have Version 17.03.1-ce-mac12 (17661)

What's the reason of this size?

**Comment by pgayvallet** [comment]
At first vm startup, we are doing a few things requiring space (starting by creating a 1gig swap). 2.2gig is actually the standard size on a fresh vm disk. 

Closing
