### ISSUE TITLE
Docker install / run fails

### ISSUE THREAD

**Issue by chimaerase** [docker/for-mac#1786]
### Expected behavior
Docker starts, or installs successfully 

### Actual behavior
I left docker for mac running on my Macbook Pro last night, disconnected from home monitors, came into work this morning, reconnected to work monitors, and the CLI was unable to connect to the Docker daemon.  

After restarting and retrying, I reasoned that I should reinstall Docker for Mac.  Now fresh installs, preceded or followed by system restarts consistently give me a "fatal error: Symlink /usr/local/bin/docker is not linked to ...." message, though I can confirm via Terminal that the symlink in fact exists.  It appears that the installation process itself may fail in the middle-- I think there are one or more final steps in the install process that I'm not seeing after providing my password.

I previously had Docker Toolbox installed on this machine, but untill recently, Docker for Mac has been working fine.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ... Install or run Docker for Mac following the initial error

**Comment by EvelynLiu** [comment]
Same as I wrote in issue#2037
I fixed the problem by removing the original bin file and creating new symbolic link
p.s. you need to make sure it is safe for you to remove your bin

```cd /usr/local
sudo rm bin
sudo mkdir bin
ln -s /Applications/Docker.app/Contents/Resource/bin/notary.bin
