### ISSUE TITLE
Ability to set DNS search domain on daemon

### ISSUE THREAD

**Issue by andrewgodwin** [docker/for-mac#179]
### Expected behavior

To have an options pane in the Docker for Mac preferences window where I can either DNS search domains explicitly or, like Docker for Windows, a place where I can put in arbitrary daemon options to achieve the same effect.
### Actual behavior

DNS search domain cannot be set, meaning we cannot switch to Docker for Mac from our previous solution of Vagrant + Docker, as our build processes require it (and we cannot use FQDNs as the search domain used to resolve the repository servers varies based on build environment)
### Information

Occurs on OSX El Capitan, 10.11.5, with both Docker for Mac stable (0.12.0) and beta (1.12.0-beta21, build 11019)

**Comment by djs55** [comment]
Search domains configured in the Mac network settings (in the Advanced -> DNS window) are now monitored and the VM is updated when they change. This change will be in beta 25 on the Mac. The patches for Windows are almost ready too.

Beta 25 will hopefully be released on the week beginning 2016-09-05 (next week). Let me know if this works for you, please re-open the issue if not.

**Comment by sfrench** [comment]
I'm having this same issue.  I've tried to get it working on both beta 25 and beta 26, to no avail.   Local resolv.conf shows my search domain, but the containers do not seem to have copied it down into them.

**Comment by nailor** [comment]
Yup, same here.

**Comment by cjw296** [comment]
Pretty unbelievable that this functionality wasn't added before pinata was removed.
This used to be fine to set with pinata...

**Comment by reallistic** [comment]
Can we re-open this? I think it got closed accidentally. More-so, this still does not work

**Comment by reallistic** [comment]
@djs55 I just realized that my docker hadn't updated in sometime (it wouldn't let me check auto-update either). I've updated manually now and it has fixed my specific issue. I'm not sure however if the `dns` configuration works because I did not need it. It seems something stopped working with my dns synchronization.

**Comment by djs55** [comment]
@reallistic thanks for the update, I'm glad your specific issue is fixed.

I believe the current state in the beta channel is:
- the daemon config file can be edited via the UI
- DNS search domain information is propagated to the VM, but only on restart. At one point it was "live" but that change had to be rolled-back unfortunately.

I'll close this issue again for now, but please do comment if something goes wrong or if there are still problems.
