### ISSUE TITLE
Docker daemon does not start and responds "Bad response"

### ISSUE THREAD

**Issue by maciejjaskowski** [docker/for-mac#1791]
### Expected behavior
`docker ps` should print all running docker containers

### Actual behavior
`docker ps` outputs 

```Error response from daemon: Bad response from Docker engine```

### Information
Docker for Mac: version: 17.06.0-ce-mac17 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.2 (build: 15C50)
logs: /tmp/657462E4-C433-4560-AD31-2162780BFA02/20170629-154034.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

I am not sure how this started. 

What eventually helped was moving from edge version to stable (which cleared all images and containers).

Restarting Docker daemon (either by killing all docker ralated processes or manually via Restart Button was not helping - the docker remained in the "yellow" state. Restarting MacOSX didn't change the way Docker behaved either.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
