### ISSUE TITLE
gcloud docker -- push with latest version 18432: fails

### ISSUE THREAD

**Issue by alexvanboxel** [docker/for-mac#1792]
as asked by @dgageot I'll post my gcloud + docker push problem

### Expected behavior
Push image to private registry 

### Actual behavior
Error response from daemon: login attempt to https://appengine.gcr.io/v2/ failed with status: 404 Not Found

### Information
Version 17.06.0-ce-mac17 (18432)
Channel: edge
4bb7a7dfa0

### Steps to reproduce the behavior

  1. gcloud docker -- push <private images>
  2. FAIL
  3. disable store in Store keys in MacOS keychain
  4. gcloud docker -- push <private images>
  5. WORKS

I've asked the windows users to post and issue as well

**Comment by mpskovvang** [comment]
I'm having the same issue with Docker for Windows 17.06.0-ce-win18 stable.

Additional info:
Errlor loading config file [...]: The process cannot access the file because it is being used by another process.

**Comment by blixt** [comment]
On Mac I could solve this error by unchecking the "Securely store docker logins in macOS keychain" checkbox in the Docker client settings.

<img width="492" alt="screen shot 2017-07-05 at 3 48 25 pm" src="https://user-images.githubusercontent.com/158591/27882153-7878e0b8-6199-11e7-85d1-e9e7d5bcddf4.png">

**Comment by groob** [comment]
Same issue here.

**Comment by dgageot** [comment]
When "Securely store docker logins in macOS keychain" is ticked, Docker for Mac makes sure all the credentials in `~/config.json` are moved to the keychain.
Unfortunately, `gcloud` seems to use some python code underneath that doesn't support the keychain.

Short term, we are going to leave the credentials related to any `gcr.io` subdomain in the `config.json` file. cc @ebriney 

Longer term, we are going to try to fix `docker-py` library. Not sure that's the one used by `gcloud` though.

**Comment by dgageot** [comment]
Related: https://github.com/docker/compose/issues/4948

**Comment by dgageot** [comment]
And https://github.com/docker/compose/issues/4885

**Comment by dgageot** [comment]
And the fix in `docker/docker-py`: https://github.com/docker/docker-py/pull/1662

**Comment by dgageot** [comment]
@alexvanboxel do you know who should be pinged at Google to make their CLI use a more recent version of `docker-py`?

**Comment by mikelambert** [comment]
According to https://serverfault.com/a/864971 , this is fixed in gcloud 164.0.0:

>       ▪ Removed appengine.gcr.io from the list of default repositories that
>     gcloud docker authenticates for.

**Comment by johnlabarge** [comment]
None of the mentioned solutions have worked for me so far.  Boot2Docker still seems to work though :/
