### ISSUE TITLE
Can't start Docker after upgrade

### ISSUE THREAD

**Issue by poblish** [docker/for-mac#1793]
### Expected behavior

Docker startup (upgrade from 17.03.1-ce, build c6d412e)

### Actual behavior

Message Box from Docker:
"Fatal Error: com.docker.osx.hyperkit.linux failed to start ... Exit code 1"

### Information

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/C934A8EA-9851-4801-8826-2028C61570C0/20170629-194226.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/andrewregan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/andrewregan/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/andrewregan/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/andrewregan/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/andrewregan/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

- Diagnosis code: C934A8EA-9851-4801-8826-2028C61570C0 (from first time I saw this)
- Downgrading works fine.
- See also: https://github.com/docker/for-mac/issues/1783

### Steps to reproduce the behavior

  1. Upgrade Docker from 17.03.1-ce, build c6d412e

**Comment by thovden** [comment]
I get the same error during upgrade - same details. 

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)

Diagnosis code: F5DBEA60-F219-4A2D-BF2D-7FB1A9FC75B9

**Comment by poblish** [comment]
Thanks. I expect resetting to factory defaults would resolve my issue, if I knew the scope of what was actually getting reset... I'd hope that if I had a problematic setting then 17.06 would find some way of telling me rather than just failing to start.

**Comment by poblish** [comment]
I'm very reluctant to reset all my images and containers. However, I disabled 'Experimental features', and reset my Daemon JSON in 17.03 before re-trying the upgrade to 17.06.0-ce-mac18. This failed as before. The diagnostic code: **C934A8EA-9851-4801-8826-2028C61570C0**

**Comment by poblish** [comment]
Still the case with the latest 17.06.1-ce-mac24: C934A8EA-9851-4801-8826-2028C61570C0

**Comment by poblish** [comment]
A (reluctant) factory reset fixed this, so closing.
