### ISSUE TITLE
Docker daemon restarts after Cisco AnyConnect connected to VPN

### ISSUE THREAD

**Issue by denbilyk** [docker/for-mac#1796]
### Expected behavior
Docker daemon doesn't restart
### Actual behavior
Docker daemon restarts after Cisco AnyConnect connected to VPN
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  0. Update docker for mac to 17.06.0-ce-mac18 (18433)  
  1. Start docker daemon
  2. Start some of containers with docker-compose 
  3. Connect to VPN by Cisco AnyConnect

Docker daemon will be restarted

Diagnose ID:
0DD43AC6-B6D6-4025-ACF6-9D8B50010BEA

**Comment by murrayju** [comment]
I'm seeing a very similar issue. I run `docker-compose up` and everything is fine, but as soon as I *disconnect* the Cisco AnyConnect VPN, docker restarts and I see:
```
Unexpected API error for mything_web_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by sebastian-curland** [comment]
This happens also with Checkpoint VPN.
As soon as I connect/disconnect from VPN, docker engine restarts.

**Comment by djs55** [comment]
The uploaded log lines are full of
```
Triggering a VM reboot because proxy settings changed from main.proxySettings{http:"", https:"", exclude:""} to main.proxySettings{http:"", https:"", exclude:"*.local, 169.254/16"}
```
-- this is the same as #1801. The fix should be in the latest stable patch:
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
If there are still problems, could you upload a fresh set of diagnostics and let me know?

Thanks for your reports.
