### ISSUE TITLE
push to local registry failed with error: getsockopt: no route to host

### ISSUE THREAD

**Issue by Diluka** [docker/for-mac#1797]
### Expected behavior
push successful
### Actual behavior
push failed
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/DD18080C-77CE-4235-A276-14C957B3F8F4/20170630-163037.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
  - ~~A reproducible case if this is a bug, Dockerfiles FTW~~
  - ~~Page URL if this is a docs issue or the name of a man page~~

### Steps to reproduce the behavior

  1. pull an image
```sh
$ docker pull hello-world
```
```
Using default tag: latest
latest: Pulling from library/hello-world
b04784fba78d: Pull complete 
Digest: sha256:f3b3b28a45160805bb16542c9531888519430e9e6d6ffc09d72261b0d26ff74f
Status: Downloaded newer image for hello-world:latest
```
  2. tag a name
```sh
$ docker tag hello-world 192.168.65.80:5000/test/hello
```
 3. push to registry
```sh
$ docker push 192.168.65.80:5000/test/hello
```
```
The push refers to a repository [192.168.65.80:5000/test/hello]
Get http://192.168.65.80:5000/v2/: dial tcp 192.168.65.80:5000: getsockopt: no route to host
```
  4. I do exactly **the same** on **ubuntu** and succeeded!
```
The push refers to a repository [192.168.65.80:5000/test/hello]
45761469c965: Pushed 
latest: digest: sha256:9fa82f24cbb11b6b80d5c88e0e10c3306707d97ff862a3018f22f9b49cef303a size: 524
```
*mac, ubuntu and registry there have different IPs, but in the same local network.*

**Comment by djs55** [comment]
Thanks for your report.

I believe this is the same as #1803: there is a clash between the internal network used by Docker for Mac and a network in your environment. In the short term, here are some [instructions](https://github.com/docker/for-mac/issues/1803#issuecomment-312372876) describing how to customise the network used by Docker for Mac. The upcoming 17.07 edge release should have a UI element in the preferences which makes this easier.

**Comment by Diluka** [comment]
still failed 

```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A405)
logs: /tmp/F7F6CDCA-01F1-4E9E-A84A-0F804EC19308/20171012-154615.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by nado18** [comment]
I had the same issue with 17.09.0-ce-mac35, I installed docker-edge instead (17.09.0ce-mac34) and now I can get back to work.

**Comment by tboyce** [comment]
Same issue. Had no network conflict here. Just switching to edge also worked for me.

**Comment by djs55** [comment]
@Diluka thanks for the report. I had a look and unfortunately discovered a bug in the implementation and a missing test case for the "Docker IP" feature. I've fixed the bug and implemented the test case, so hopefully the Preferences menu -> Advanced -> Docker IP settings should be working in the next edge release. Sorry for the confusion!
