### ISSUE TITLE
Performance degradation between 17.04 and 17.05/06

### ISSUE THREAD

**Issue by markfoodyburton** [docker/for-mac#1799]
### Expected behavior

Same (or better) performance from 17.04 to 17.05/6
I am using : Docker 17.06.0-ce-mac17

### Actual behavior

in 17.04, I saw something like a 20x improvement of speed when I added :delegated to my docker 
e.g. between:
   docker run --privileged --rm -it -v ~/:/home/me/  /bin/bash
and
   docker run --privileged --rm -it -v ~/:/home/me/:delegated  /bin/bash

On upgrading to 17.05 and then 6, I see no performance gain from :delegated.

To replicate this, I should downgrade to docker 17.04, and re-run the exact same tests (which I did not do - I tested stuff which isn't reproducible outside my environment, so it doesn't help).

Is there a simple way to revert to a previous docker version? (I dont see any release tags in the git?)

### Information

So - I did the following as a sort of simple test - these are executed inside the guest, within a directory that is mapped to the host.

First without any :delegated
time dd if=/dev/zero of=./tmpfoo bs=1024 count=10000
10000+0 records in
10000+0 records out
10240000 bytes (10 MB) copied, 2.08529 s, 4.9 MB/s

real	0m2.090s
user	0m0.000s
sys	0m0.250s
mark@e893a3d178f6:~$ time cat tmpfoo 

real	0m0.451s
user	0m0.000s
sys	0m0.070s

Now run with :delegated

time dd if=/dev/zero of=./tmpfoo bs=1024 count=10000
10000+0 records in
10000+0 records out
10240000 bytes (10 MB) copied, 2.66631 s, 3.8 MB/s

real	0m2.672s
user	0m0.080s
sys	0m0.210s
mark@53d6c0bbd416:~$ time cat tmpfoo 

real	0m0.500s
user	0m0.000s
sys	0m0.070s

Seems like :delegated (which apparently is currently the same as :cached) is depredating the performance slightly.

That is perfectly reasonable, but what I dont get is why it 'worked' in 17.04 ???

What can I do to debug this?

Cheers
Mark.

**Comment by yallop** [comment]
Thanks for the report, @markfoodyburton . As you say, the 17.04 results are the surprising thing here.  No released version of Docker for Mac has included the write optimizations that `delegated` allows, so it's difficult to see where the 20x improvement could come from.

I wonder if the tests against 17.04 were somehow writing to a directory outside a mounted volume.  (It's easy to see how such a thing could happen -- for example, inadvertently changing `:` to some other character would lead to the host directory being mounted at a different location, and there are many other similar possibilities.)

17.06 does contain some smaller performance improvements over previous releases, of the order of 20% improvement for some workloads.  We don't expect any degradation in performance with bind-mounted directories in 17.06.

(The question of downgrading to previous releases is discussed in #1120.)

**Comment by markfoodyburton** [comment]
Yallop, thats for the feedback. I agree, the question is why did I seem to get such good performance with 17.04. I will try and replicate, thats clearly the next step.

In terms of finding  the right version, I dont have the build number - and I dont seem to be able to find a reference for it? - could you provide the right number for 17.04?

(BTW, in my case, I'm bind-mounting a large working directory, that contains itself a lot of large files (linux builds, VM's, gcc builds, etc) - which I dont want to 'sync' across to the docker... - hence my interest in this, rather than, for instance docker-sync. But maybe I'm mistaken about what docker-sync does?)

Cheers
Mark.

**Comment by markfoodyburton** [comment]
If anybody else finds this and wants to know: 
Version 17.04.0-ce-mac7 (16352)
https://download.docker.com/mac/edge/16352/Docker.dmg



This issue can be closed - sorry for the noise.
Below are the details of the tests I did. I believe when I first threw the :delegated switch, the test I did was - for some reason - 'lucky'. There is a lot of variability in the tests. Presumably due to caching effects etc.

In any case, 17.04 is not fantastically better compared to 17.06. On the country, just as predicted, if anything, its slightly better in general.

Cheers
Mark.

```Version

 17.04.0-ce-mac7 (16352)
https://download.docker.com/mac/edge/16352/Docker.dmg

docker run --privileged --rm -it -v ~/:/home/whoami

mark@23aa7c3fbe1a:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 27.9032 s, 3.7 MB/s

real	0m27.908s
user	0m0.150s
sys	0m2.110s
mark@23aa7c3fbe1a:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 30.9935 s, 3.3 MB/s

real	0m31.017s
user	0m0.110s
sys	0m2.400s

mark@23aa7c3fbe1a:~$ time cat tmpfoo > /dev/null

real	0m0.425s
user	0m0.000s
sys	0m0.050s
mark@23aa7c3fbe1a:~$ time cat tmpfoo > /dev/null

real	0m0.263s
user	0m0.000s
sys	0m0.060s

docker run --privileged --rm -it -v /:/home/whoami:delegated
mark@007a6b7f3234:$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 21.1934 s, 4.8 MB/s

real	0m21.212s
user	0m0.160s
sys	0m0.590s
mark@007a6b7f3234:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 20.4818 s, 5.0 MB/s

real	0m20.504s
user	0m0.060s
sys	0m0.660s

mark@007a6b7f3234:~$ time cat tmpfoo > /dev/null

real	0m0.013s
user	0m0.000s
sys	0m0.010s
mark@007a6b7f3234:~$ time cat tmpfoo > /dev/null

real	0m0.013s
user	0m0.000s
sys	0m0.010s

Version 17.06.0-ce-mac17 (18432)
docker run --privileged --rm -it -v ~/:/home/whoami

mark@c966688493e4:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 21.1647 s, 4.8 MB/s

real	0m21.193s
user	0m0.220s
sys	0m1.850s
mark@c966688493e4:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 14.6583 s, 7.0 MB/s

real	0m14.685s
user	0m0.070s
sys	0m0.650s

mark@c966688493e4:~$ time cat tmpfoo > /dev/null

real	0m0.219s
user	0m0.000s
sys	0m0.040s
mark@c966688493e4:~$ time cat tmpfoo > /dev/null

real	0m0.215s
user	0m0.000s
sys	0m0.050s

docker run --privileged --rm -it -v /:/home/whoami:delegated
mark@30f7f372bbee:$ time cat tmpfoo > /dev/null

mark@30f7f372bbee:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 20.4115 s, 5.0 MB/s

real	0m20.424s
user	0m0.340s
sys	0m1.690s
mark@30f7f372bbee:~$ time dd if=/dev/zero of=./tmpfoo bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 17.85 s, 5.7 MB/s

real	0m17.873s
user	0m0.020s
sys	0m1.230s

real	0m0.015s
user	0m0.000s
sys	0m0.010s
mark@30f7f372bbee:~$ time cat tmpfoo > /dev/null

real	0m0.018s
user	0m0.000s
sys	0m0.010s
```

**Comment by yallop** [comment]
Thanks for the update and performance figures!   It's good to have confirmation that everything's working as expected.
