### ISSUE TITLE
OOM killer kills transfused

### ISSUE THREAD

**Issue by johanneswuerbach** [docker/for-mac#18]
### Expected behavior

Containers inside the VM are killed first, crucial services last. An error message that the VM hit an oom error and the allocated memory should be increased.
### Actual behavior

transfused seems to be killed by the oom killer and the docker vm is restarting.

```
2016-07-29 17:09:06 +0000 UTC daemon.crit /sbin/transfused: /Users: error writing:
2016-07-29 17:09:06 +0000 UTC daemon.crit /sbin/transfused: Out of memory
```
### Information
- 259D4E40-1478-48B5-B004-7E5688B30B30
- OS X 10.11.6 MacBook Pro (Retina, 13-inch, Early 2015)
### Steps to reproduce the behavior
1. Consume more memory then the VM has configured
2. Docker VM is restarting without further notice

**Comment by dsheets** [comment]
I actually don't think this is oomkiller... it looks like it's due to `ENOMEM` being returned from a syscall rather than a deadly signal. It may be due to a memory leak in Moby or `transfused` specifically. In any event, we should definitely handle this eventuality better.

**Comment by justincormack** [comment]
Its kind of odd, overcommit is set to 0 which is:
```
0	-	Heuristic overcommit handling. Obvious overcommits of
		address space are refused. Used for a typical system. It
		ensures a seriously wild allocation fails while allowing
		overcommit to reduce swap usage.  root is allowed to 
		allocate slightly more memory in this mode. This is the 
		default.
```

Which basically means that `transfused` is perhaps asking for an "obvious overcommit", otherwise memory would have been allocated and it would have segfaulted. Or the kernel is out of memory (odd, would be something in logs perhaps?)

**Comment by petrklus** [comment]
I believe I may be seeing the same as well: https://dl.dropboxusercontent.com/u/7395199/dockerlogs.zip

The error I am seeing in the webserver log is the following:

    OSError: [Errno 107] Transport endpoint is not connected: 'filename_varies_here.py'

**Comment by dsheets** [comment]
@petrklus could you please open a new issue with the output of `Diagnose & Feedback` ➡️ `Diagnose & Upload` including the diagnostic ID that is generated?

@justincormack This could easily occur if `transfused` reads corrupt data from the vsock due to an overfull ring or similar.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
