### ISSUE TITLE
docker 17.06 keeps restarting on n/w status change

### ISSUE THREAD

**Issue by kvahuja** [docker/for-mac#1801]
### Expected behavior
It should keep running and not restart when i turn off my network

### Actual behavior
when I connect or DC my WIFI, docker engine resarts

### Steps to reproduce the behavior

  1. Start Docker
  2. Turn off WIFI
  3. Docker Restarts
  4. Once Docker is running, turn on WIFI - it restart again

There is a bug in docker-compose where I can't run the command as it hangs when I am connected to a n/w. So this pretty much means, Docker is useless for me. 

how do i run docker-compose while connected to the n/w?? or why is docker restarting all the time. I could earlier just clos emy MAC and bring it back-up and everythign was running. now i have to restart everything all the time,

is this a Bug? i hope this is a bug?

**Comment by siosphere** [comment]
Same here with latest update:

Docker version 17.06.0-ce, build 02c1d87

OSX El Capitan 10.11.6

**Comment by tanmng** [comment]
I'm experiencing the same issue

**Comment by siosphere** [comment]
This is related to #1796

**Comment by djs55** [comment]
Please upload diagnostics (from the Whale menu -> Diagnose and Feedback ...). Without the uploaded logs it will be hard to correctly diagnose the issue.

**Comment by tanmng** [comment]
@djs55 After some restarts, Docker for Mac now appears to be stable again and I don't experience the issue any longer

Is it still necessary to upload my diagnostics?

**Comment by djs55** [comment]
@tanmng if it's stabilised don't worry about it. FYI there should be a 17.06.1 with some fixes in this area this week. Let me know if you have any further problems!

**Comment by gow** [comment]
Still happening with me. Here is my diagnostic ID: 5795AC98-CB11-4D02-B390-2F894381D185
Build:
Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0

**Comment by zambotn** [comment]
Same problem here!
[6B5763CA-409E-4B0F-8A85-B0D251744997](https://github.com/docker/for-mac/files/1134661/20170710-151127.tar.gz)

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)

**Comment by coladarci** [comment]
Same here...
C2C5057A-146F-4E2B-B29B-51786494B6B9
```
Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0
```

**Comment by djs55** [comment]
The fix for this should be in the latest stable patch:
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
If there are still problems, could you upload a fresh diagnostic and let me know?

Thanks for your reports.
