### ISSUE TITLE
Docker push to secure remote private repository using squid as system-proxy fails

### ISSUE THREAD

**Issue by redskate** [docker/for-mac#1808]
### Expected behavior
After image building and tagging, push image to remote repository succeeds
### Actual behavior
After image building and tagging, push image to remote repository fails

### Information

docker version (of my home and remote servers)
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker info of home site:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: WO5G:N34F:7GH2:3M5Z:A2CI:MBXT:TENV:KJUS:OFCO:MIJ6:R6GX:6CN6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-07-02T17:45:18.0886912Z
 EventsListeners: 1
Http Proxy: http://docker.for.mac.localhost:3128
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 ch.semweb.ch:18324
 127.0.0.0/8
Live Restore Enabled: false
```
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/D4474002-821F-4408-8D7D-E845DCF3370C/20170702-194441.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```
As you can see, the docker database of the home docker installation was moved to be on another mounted medium. The database seems to work fine (I never use docker on a default in-disk database, because it can run out of space killing the operating system). It is not "missing", otherwise no images could have been built (or ????).

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Hi, I have spent now nearly one whole day only setting up a "more-or-less" secured private remote repository on my site (different than my home docker site). That repository worked fine `accepting pushes` until I have secured it via TLS and basic authentication (the SSL (with a from godaddy purchased certificate) was not recognised (by docker login) as trustful (X509), so I "had" to insert that repo url into the "insecure" repositories of my home docker).  I have searched the internet for "similar" issues, there are a bunch regarding push, but none of the solutions offered in those issues helped me. Therefore again one issue on push. Please try not to tag this as another issue of the same push issue. It seems (to me) that this issue be still open, maybe because of the high number of operating systems that can be used with docker 👍 

**The steps:**
1. build an image on OSX with `docker build -t sksblazegraph .` successful.
2. tagging that image using docker tag `sksblazegraph ch.semweb.ch:18324/sksblazegraph` successful
3. logging in with `docker login -u <name> -p <passwd>` - succeeded
4. pushing image with `docker push ch.semweb.ch:18324/sksblazegraph` - unsuccessful!
That same push command - and a subsequent `docker-compose up` action using that remote image `ch.semweb.ch:18324/sksblazegraph` worked well for me once the remote repository was not secured and not protected.

The output was this:
```
The push refers to a repository [ch.semweb.ch:18324/sksblazegraph]
32ac4d2166a7: Retrying in 5 seconds 
32ac4d2166a7: Retrying in 1 second 
fb335d23bdbb: Retrying in 1 second 
419def581879: Retrying in 1 second 
ed7c5a67d822: Retrying in 1 second 
c7a26174b988: Retrying in 1 second 
7156a2d25bdb: Waiting 
76219bfb88d4: Waiting 
6be1741be005: Waiting 
7492fc210222: Waiting 
7965d94b3fd0: Waiting 
95074c100793: Waiting 
7af2af3384f8: Waiting 
73f99492b3a5: Waiting 
a33ef7cdcb48: Waiting 
d80f7572acd3: Waiting 
5e420ef7f4a5: Waiting 
1f872fa9a24c: Waiting 
3670ccb1f662: Waiting 
9f154a8a3c87: Waiting 
504b7d2e0ef9: Waiting 
f3c7536252d6: Waiting 
362ed0033c5c: Waiting 
a56217ad4142: Waiting 
156545607418: Waiting 
80bee1a65ead: Waiting 
0583af55a445: Waiting 
1ae7b18f5354: Waiting 
d69122875478: Waiting 
32ceb20ee08e: Waiting 
d1de89c613d4: Waiting 
71ce2dc7f761: Waiting 
0d960f1d4fba: Waiting 

received unexpected HTTP status: 200 OK
```
In the logs (`tail -f /var/log/system.log | grep docker`) of the home docker I found nothing, and the same is valid for the remote docker service.

There are NO firewalls running, neither on the home machine nor on the remote machine.
Just a SQUID on port 3128 - see above. 

**What am I doing here wrong?** 
**How can I get also the push running for a secured remote private repository ?**

(Please tell me what other information I should upload to complete the picture.)

Thanks a lot in advance!

**Comment by redskate** [comment]
The problem was the SQUID proxy, installed via OSX as web-proxy and configured in DOCKER as `use system proxy`.  Stopping squid, removing the proxy network configuration and setting in DOCKER No proxy solved my push problem.

Do we want it so? I guess something should be done in order to work WITH a proxy and being able to push images.

**Comment by soumypau1** [comment]
We are facing the same issue with docker client version 17.12.1-CE on ubuntu 16.04
