### ISSUE TITLE
Containers fail to keep running since latest Docker update

### ISSUE THREAD

**Issue by noefingway** [docker/for-mac#1809]
### Expected behavior
docker app runs until I stop it
### Actual behavior
all containers fail after several hours, this has only started since the latest update
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/EDB656CD-E5D0-4093-9592-E5B2D11106B8/20170702-182642.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Seems happen to any container I run.

**Comment by junian** [comment]
Happened to me, too. I run a mysql container. Usually it's running without problem. Now it's closing every time I sleep my Mac.

**Comment by djs55** [comment]
In the logs for EDB656CD-E5D0-4093-9592-E5B2D11106B8:
```
<Warning>: Triggering a VM reboot because proxy settings changed from 
main.proxySettings{http:"", https:"", exclude:""} to main.proxySettings{http:"", https:"", exclude:"*.local, 169.254/16"}
```
HTTP proxies are configured by modifying the environment variables inside the VM, which requires a VM restart whenever the variables change. In this case perhaps it's unnecessary to reboot when the `exclude` changes, when there is no actual proxy set.

As a workaround try setting: Whale Menu -> Proxies -> No proxies.

**Comment by vyscond** [comment]
Sounds like this trick from @djs55 also resolves the annoying reboot that happens every single time i switch from network.

**Comment by thaJeztah** [comment]
@djs55 something for the troubleshooting section in the documentation perhaps?

**Comment by djs55** [comment]
The unnecessary reboot caused by the `exclude` changing when there is no proxy set has been cherry-picked into the branch for 17.06.1, which should hopefully be released later this week. Thanks for your report!

**Comment by noefingway** [comment]
Setting "No Proxies" appears to have solved the problem. thx!

**Comment by timothyallan** [comment]
Hopefully this also fixes the issue of restarting Docker when stopping/starting Charles Proxy!

**Comment by vyscond** [comment]
@timothyallan It does. Just confirmed it.

**Comment by timothyallan** [comment]
@vyscond Hmmm, yours doesn't do this if you're using the system proxy?
 
https://github.com/docker/for-mac/issues/1873#issuecomment-317186469
