### ISSUE TITLE
docker does not start up

### ISSUE THREAD

**Issue by lodatol** [docker/for-mac#181]
### Information

Diagnostic ID: 2353BBF8-7CC8-4ECB-BAE7-52B753E17636
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by FrenchBen** [comment]
Can you make sure that there are no pop-up window waiting for your acknowledgement? This is typically the case when you're asked for your admin password and click away to another app (such as chrome)

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in 2353BBF8-7CC8-4ECB-BAE7-52B753E17636/20160808-220325.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: virtio-9p: initialising path=/Users/lodwork/Library/Containers/com.docker.docker/Data/s51,tag=port
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: linkname /Users/lodwork/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: COM1 connected to /dev/ttys000
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: COM1 linked to /Users/lodwork/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: received sigusr1, pausing
Aug  8 19:33:48 Lodatos-MacBook-Pro Docker[com.docker.driver.amd64-linux][454] <Notice>: received sigusr2, unpausing
```
