### ISSUE TITLE
`docker cp` is not setting the right UID & GID to the destination file

### ISSUE THREAD

**Issue by rbelouin** [docker/for-mac#1814]
### Expected behavior

According to [the documentation](https://docs.docker.com/engine/reference/commandline/cp/#extended-description), I expect the destination file to have `root:root` as an owner.

### Actual behavior

The destination file is set with `501:dialout` as an owner. 501 is the UID of my local user, the one actually invoking `docker cp`.

### Information

Diagnostic ID: 2641786D-4283-438C-A772-0741838174DE

Unfortunately, I'm not sure whether I am allowed to share the Dockerfile publicly.

### Steps to reproduce the behavior

```
[rbelouin dev(authorized-keys-owner)]% echo $UID $GID
501 20
[rbelouin dev(authorized-keys-owner)]% echo plop > plop.txt
[rbelouin dev(authorized-keys-owner*)]% docker cp plop.txt $(docker-compose ps -q website):/root/plop.txt
[rbelouin dev(authorized-keys-owner*)]% docker-compose exec website bash
root@4a53e665800d:~# ls -l
total 8
drwxr-xr-x 2 root root    4096 Apr 27 21:23 keys
-rw-r--r-- 1  501 dialout    5 Jul  3 11:18 plop.txt
root@4a53e665800d:~#
```

**Comment by dsheets** [comment]
I can't seem to reproduce this issue using `alpine:3.6` -- the copied file is always owned `root:root`. Could you please try to reduce the test case the exhibits the problem and post a complete reproduction here?

**Comment by rbelouin** [comment]
Sure!

**Comment by dsheets** [comment]
It looks like there have been some changes and issues related to this functionality recently: see https://github.com/moby/moby/pull/34099 and related issues/PRs. Maybe you have encountered one of these issues/changes?

**Comment by rbelouin** [comment]
This could be related indeed, I'm gonna try to reproduce tomorrow. I'll keep you posted.

**Comment by rbelouin** [comment]
I could reproduce it using `ubuntu:trusty` by following the steps below:

**Docker version:**
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Pull and run the image:**
```
$ docker pull ubuntu:trusty
trusty: Pulling from library/ubuntu
7ee37f181318: Pull complete
df5ffabe5e97: Pull complete
ae2040ed51a1: Pull complete
3ce7010d244b: Pull complete
2538b201d2a6: Pull complete
Digest: sha256:13eecbc0e57928c1cb3ccca3581e2a6f4b0f39c1acf5a279e740e478accd119b
Status: Downloaded newer image for ubuntu:trusty

$ docker images
REPOSITORY                                         TAG                 IMAGE ID            CREATED             SIZE
…
ubuntu                                             trusty              54333f1de4ed        5 days ago          188MB
…

$ docker run -it ubuntu:trusty bash
root@e308875092e5:/#
```

**Get the ID of the created container:**
```
$ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS                                        NAMES
e308875092e5        ubuntu:trusty                                     "bash"                   26 seconds ago      Up 25 seconds                                                    lucid_benz
```

**Create a random text file and copy it to the container:**
```
$ echo plop > plop.txt
$ docker cp plop.txt e308875092e5:/root/plop.txt
```

**Confirm the file doesn't have the right UID/GUID:**
```
root@e308875092e5:/# ls -l /root
total 4
-rw-r--r-- 1 501 dialout 5 Jul 26 13:23 plop.txt
```

**Comment by rbelouin** [comment]
I also could reproduce it with `alpine:3.6` by following the same steps (you just need to use `sh` instead of `bash`)

**Comment by rbelouin** [comment]
Some further info about Docker for mac:

```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```

```
Docker 17.06.0-ce-mac19 is currently the newest version available.
```

**Comment by mkrawetko** [comment]
It still seems to be the problem on macOs High Sierra :(

Docker for mac 
Version 17.09.0-ce-mac33 (19543)
Channel: stable
e2f2204fde

**Comment by dismantl** [comment]
I am able to reproduce the bug on Ubuntu Xenial using @rbelouin's steps above, so it's not just macOS High Sierra. No matter whether I use the "-a" flag or not for docker cp, the copied files always have the UID/GID of the host user.

**Comment by ivanlawrence** [comment]
/remove-lifecycle stale
I'm getting a similar result:
`ivan.lawrence@lap $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036`

`ivan.lawrence@lap $ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
`
`ivan.lawrence@lap $ docker cp export_bamboo.zip competent_borg:/var/atlassian/bamboo/backups/`
`/var/atlassian/bamboo/backups $ stat export_bamboo.zip 
  File: export_bamboo.zip
  Size: 36156801  	Blocks: 70624      IO Block: 4096   regular file
Device: 801h/2049d	Inode: 1707265     Links: 1
Access: (0600/-rw-------)  Uid: (260102358/ UNKNOWN)   Gid: (   20/ dialout)
Access: 2018-03-17 07:50:43.000000000
Modify: 2018-03-17 07:50:43.000000000
Change: 2018-03-29 08:47:46.000000000`

**Comment by jeffgran** [comment]
I believe @dsheets is right. https://github.com/moby/moby/pull/34099 seems to be the fix for this issue.

**Comment by completenovice** [comment]
We are experiencing the same issue. The cp command appears to always uses the --archive flag when copying files to running containers. 

Local UID & GID
`
➜  ~ id
uid=501(completenovice) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
➜  ~ touch file.txt
`
tomcat:8.0-jre8 (CentOS):
`
➜  ~ docker cp file.txt b25bc50ccd97:/etc/file.txt
➜  ~ docker exec -it b25bc50ccd97 bash
[root@b25bc50ccd97 /]# ls -l /etc/file.txt
-rw-r--r-- 1 501 games 0 Jul 17 09:55 /etc/file.txt
[root@b25bc50ccd97 /]# cat /etc/group | grep games
games:x:20:
[root@b25bc50ccd97 /]#
`
ubuntu:latest
`
➜  ~ docker cp file.txt 1cb7904f2219:/etc/file.txt
➜  ~ docker exec -it 1cb7904f2219 bash
root@1cb7904f2219:/# ls -l /etc/file.txt
-rw-r--r-- 1 501 dialout 0 Jul 17 09:55 /etc/file.txt
root@1cb7904f2219:/# cat /etc/group | grep dialout
dialout:x:20:
root@1cb7904f2219:/#
`
and if we change that files' local owner:
`
➜  ~ sudo chown 22:22 file.txt
➜  ~ docker cp file.txt 1cb7904f2219:/etc/file.txt
➜  ~ docker exec -it 1cb7904f2219 bash
root@1cb7904f2219:/# ll /etc/file.txt
-rw-r--r-- 1 22 voice 0 Jul 17 09:58 /etc/file.txt
root@9a962dfc1c6a:/# cat /etc/group | grep voice
voice:x:22:
root@1cb7904f2219:/#
`

docker version:
`➜  ~ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true`
docker info:
`➜  ~ docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: OW5C:6KDG:EV4R:DRRD:R3IS:EPZZ:66JI:CJWD:7JSU:KTO2:XGR7:RVFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 47
 Goroutines: 75
 System Time: 2018-07-17T09:54:54.33070856Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

If I can provide more information please let me know

**Comment by mguimas** [comment]
I am interested on this issue so /lifecycle frozen

**Comment by unguiculus** [comment]
Still an issue on MacOS Mojave and Docker 19.03.5.

**Comment by axcasella** [comment]
Also an issue on MacOS Catalina with Docker version 19.03.2, build 6a30dfc

**Comment by hitriyvalenok** [comment]
Have this issue with Ubuntu 18, docker 17.05.0-ce

**Comment by daksishere** [comment]
Have the same issue in MacOS Catalina and docker 19.03.4.
To bypass the issue i copied the file in the container volume location itself. it worked.

**Comment by hitriyvalenok** [comment]
I found the safe solution of copying from host to volume with inheriting:
```
sudo docker run --name in_volume_dumper -v <volume>:/data -t -d ubuntu 
sudo tar -C <host_path> -cv . | sudo docker exec -i in_volume_dumper tar x -C /data
sudo docker stop in_volume_dumper && sudo docker rm in_volume_dumper
```

P.S. Do not copy in volume through active container! You will have crazy conflicts with mounted volumes. Do copy in volume through "clean" container.

**Comment by axcasella** [comment]
I did find another solution, you can copy to a temporary location inside the container, then copy from that tmp location to the desired final location. It's one more step but will give you the right UID & GID
