### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by gkalele** [docker/for-mac#1816]
### Actual behavior
Docker for Mac fails to start

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/5DD34A84-F60F-4C0D-92DA-D5BF83C6EEE9/20170703-115554.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users//Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users//Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users//Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users//Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users//Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users//Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Diagnostic ID:
5DD34A84-F60F-4C0D-92DA-D5BF83C6EEE9

**Comment by gkalele** [comment]
I downloaded the latest version manually and it also failed to start.
However, it had an extra button "Reset to Factory Defaults" - once I clicked that, Docker started right up.

Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0

**Comment by gkalele** [comment]
Reset to Factory Defaults also blew away my old qcow image with all the cached layers/images..I will have to download the entire 3-4GB of Docker Hub images all over again.

**Comment by yallop** [comment]
Thanks for the report, @gkalele.  I'm sorry that your settings were lost while fixing the problem.

I'm closing this issue, since your initial problem is now resolved.
