### ISSUE TITLE
Periodic errors from Docker Cloud Swarm terminal, clear up on its own: Error response from daemon: {"detail": "Incorrect authentication credentials."}

### ISSUE THREAD

**Issue by bloo** [docker/for-mac#1817]
### Expected behavior

Commands executed against Docker Cloud Swarm work as they should.

- docker service ls
- docker node ls
- docker info

etc - basic commands.

### Actual behavior

Often, every command will fail with this as the output:

```
Error response from daemon: {"detail": "Incorrect authentication credentials."}
```

Waiting between 15 seconds or 10 minutes and trying again will go back to normal - until it happens again.

### Information

Diagnostic ID: ??? (never returned)

Swarm is hosted on AWS, provisioned by custom Terraform. Port 2376 is accessible. Swarm operates fine from any of the Swarm Manager nodes.

### Steps to reproduce the behavior

  1. install Docker Edge
  2. log in
  3. switch your login to the organization you've registered your Swarm too
  4. select Swarm from menu and let it open up a terminal window
  5. operate docker commands against your Swarm until they start failing

**Comment by vpetroff** [comment]
Having the same problem, not on Edge but on the Stable channel, version 17.06.0-ce build 02c1d87

**Comment by bloo** [comment]
I switched from Edge to Stable and also still get these errors.

**Comment by ebriney** [comment]
I think it's fixed now on stable and edge (mac 19 and 20), can you confirm?

**Comment by vpetroff** [comment]
Yes, I believe this works now, I haven't had any issues since the latest releases of Docker for Mac and Docker for AWS. I think it was related to this issue on DockerAWS - https://github.com/docker/for-aws/issues/66

**Comment by bloo** [comment]
@ebriney will test over the next few days and confirm. @vpetroff I'm using BYOS (but hosted on AWS).
