### ISSUE TITLE
D4M Restart hangs

### ISSUE THREAD

**Issue by hitthecode** [docker/for-mac#1819]
### Expected behavior
When Docker 4 Mac seems to hang the expected behavior should be to restart when 'Restart' is clicked

### Actual behavior
Stays in a perpetual 'restarting' status

### Information

> Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
> macOS: version 10.12.5 (build: 16F73)
> logs: /tmp/6861C53B-75AD-4CF9-BAA8-AB486192D428/20170703-143917.tar.gz
> failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
> [OK]     vmnetd
> [OK]     dns
> [OK]     driver.amd64-linux
> [OK]     virtualization VT-X
> [OK]     app
> [OK]     moby
> [OK]     system
> [OK]     moby-syslog
> [OK]     db
> [OK]     env
> [OK]     virtualization kern.hv_support
> [OK]     slirp
> [OK]     osxfs
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          docker ps failed
> [OK]     menubar
> [OK]     disk
> 

### Steps to reproduce the behavior

  1. Docker hangs
  2. 'Restart Docker' fails to restart

**Comment by axsuul** [comment]
I'm experiencing this as well

**Comment by taiidani** [comment]
I’ve seen this too on the newer client builds. Possibly related to #1728?

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
