### ISSUE TITLE
Docker timing out

### ISSUE THREAD

**Issue by stonefury** [docker/for-mac#182]
### Expected behavior
Just run!

### Actual behavior

Last operation I was running I was trying to push to a private registry that wasn't setup right, so it was hanging. But I rebooted my mac.  The private registry is up now. But that shouldn't matter as to starting docker right?  Now I can't get the darn thing up again.

### Information

Diagnostic ID: 4A709BC1-5F4D-496A-B061-62936CAE15E7
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ... Reboot the macbook pro
2. ... docker ps hangs
3. Try to restart docker via status bar icon
4. Nothin.

**Comment by stonefury** [comment]
Used the reset to defaults which did a automatic reinstall. FIxed the issue. Was fine since I didn't have any important images.

**Comment by anarcher** [comment]
I reset to defaults but I have same issue.

**Comment by anarcher** [comment]
After reset, docker looks fine. Thanks!

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 4A709BC1-5F4D-496A-B061-62936CAE15E7/20160808-164557.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug  3 09:09:00 pet-bfleming Docker[com.docker.vmnetd][55386] <Notice>: User 501 has container folder /Users/bfleming/Library/Containers/com.docker.docker/Data/s60
Aug  3 09:09:00 pet-bfleming Docker[com.docker.vmnetd][55386] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  3 09:09:00 pet-bfleming Docker[com.docker.vmnetd][55386] <Notice>: User 501 has container folder /Users/bfleming/Library/Containers/com.docker.docker/Data/s60
Aug  3 09:09:00 pet-bfleming Docker[com.docker.vmnetd][55386] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  3 09:09:00 pet-bfleming Docker[com.docker.docker][55366] <Error>: Symlinks are not correctly installed.
Aug  3 09:09:00 pet-bfleming Docker[com.docker.docker][55366] <Notice>: com.docker.osx.hyperkit.linux launched with PID 55390
Aug  3 09:09:00 pet-bfleming Docker[com.docker.osx.hyperkit.linux][55390] <Notice>: Acquired task manager lock
Aug  3 09:09:00 pet-bfleming Docker[com.docker.frontend][55389] <Critical>: dial unix /Users/bfleming/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Aug  3 09:09:00 pet-bfleming Docker[com.docker.osx.hyperkit.linux][55390] <Notice>: Maximum number of file descriptors is 10240
```
