### ISSUE TITLE
Docker cannot start

### ISSUE THREAD

**Issue by Ailsa84** [docker/for-mac#1823]
### Expected behavior
Docker should start succesfully
### Actual behavior
Docker cannot start
### Information
Diagnostic ID: 9EE4D60B-2002-4B6C-A8E0-263DD230ED85
Docker for Mac: version: 17.06.0-rc1-ce-mac13 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/9EE4D60B-2002-4B6C-A8E0-263DD230ED85/20170704-140035.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ailsa/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/ailsa/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ailsa/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ailsa/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/ailsa/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/ailsa/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ailsa/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

I tried latest stable build and edge build, both fail.
### Steps to reproduce the behavior

  1. Download CE build
  2. Install it
  3. Open Docker from Applications

**Comment by cdiam** [comment]
i have the same issue. Opened a ticket already #1818!

**Comment by Ailsa84** [comment]
I re-installed my Mac, then install stable docker, it works fine. 
I think maybe the issue is related with account permission, because before re-install my Mac, I created new admin account, and deleted old admin account, then installed docker, the issue happened.
