### ISSUE TITLE
config.json still contains "credsStore" : "osxkeychain" after disabling "Securely store docker logins in macOS keychain" feature

### ISSUE THREAD

**Issue by ryanmcginnis** [docker/for-mac#1826]
(Please let me know if I misunderstand the functionality of this feature!)

### Expected behavior
Docker should not store credentials in the macOS keychain when the feature is disabled.

### Actual behavior
Even after disabling the feature, Docker appears to continue using the macOS keychain to store credentials

### Information
macOS 10.12.5 (16F73)
Docker 17.06.0-ce-mac18

### Steps to reproduce the behavior

  1. While the feature is enabled, read ~/.docker/config.json and observe that `"credsStore" : "osxkeychain"` is included in the file.
  2. Disable the feature from Docker > Preferences menu.
  3. Read config.json again. Observe that `"credsStore" : "osxkeychain"` is still there.
  4. Manually remove the line and save the file.
  5. Open Preferences menu and enable the feature again.
  6. Read config.json again. Observe that `"credsStore" : "osxkeychain"` is has returned.
  7. Again, manually remove the line and save the file.
  8. Open Preferences menu. Observe that "Securely store docker logins in macOS keychain" is still enabled.

**Comment by qayshp** [comment]
Using `Version 18.03.0-ce-mac60 (23751)` I don't see this repro.

**Comment by ryanmcginnis** [comment]
Great!

**Comment by jasongoodwin** [comment]
I perennially find this issue w/ use osx keystore unchecked...

**Comment by agparadiso** [comment]
Im experiencing the same @jasongoodwin have you found any solution?

**Comment by agparadiso** [comment]
@jasongoodwin I was having the same problem with version `19.03.05` and downgrading to `19.03.04` solved it. 
you can find the previous versions in the release-notes: https://docs.docker.com/docker-for-mac/release-notes/
specifically for 1.9.04 is: https://download.docker.com/mac/stable/39773/Docker.dmg
