### ISSUE TITLE
Docker daemon restarts when loosing internet connectivity

### ISSUE THREAD

**Issue by matteosilv** [docker/for-mac#1828]
### Expected behavior

Docker daemon does NOT restarts

### Actual behavior

With "Use system proxy" option enabled if you loose internet connectivity by detaching the ethernet cable or shutting down the wifi, the docker daemon restarts itself. The same behavior occurs when you attach back the ethernet cable.

### Information

I don't have any system wide proxy configured ("Use system proxy" is the default option). If i switch to "No proxy" the daemon does not restarts anymore.

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Activate "Use system proxy option" under Proxy preferences
  2. Detach ethernet cable (or shut down wifi)

DIagnostic ID: E3C8F3A8-6D09-4A7C-984B-9D4D05A933DB

**Comment by binhnv** [comment]
The same issue happens to me too

**Comment by djs55** [comment]
Thanks for your report. I think this is the same issue as https://github.com/docker/for-mac/issues/1809. There's a fix scheduled to be released in 17.06.1 which is due to be released very soon. I'm sorry for the inconvenience in the meantime.
