### ISSUE TITLE
docker-machine's bash autocompletion errors

### ISSUE THREAD

**Issue by jakirkham** [docker/for-mac#1830]
When trying to `source` the `docker-machine` autocompletion script in `bash` on macOS 10.11, it encounters an error. Given that macOS uses a very old version of `bash`, it is quite possible there is syntax being used here that is simply unsupported instead of just being a bug. Am running Docker for Mac 17.06.0-ce-mac18 (18433) on macOS 10.11. More details below.

```bash
$ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
$ source /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion
-bash: /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion: line 86: syntax error in conditional expression: unexpected token `('
-bash: /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion: line 86: syntax error near `@($'
-bash: /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion: line 86: `    [[ ${words[$glob_pos]} == @($glob) ]] && echo "$key"'
```

**Comment by jakirkham** [comment]
Seems this is the same as issue ( https://github.com/docker/machine/issues/4126 ). Appears PR ( https://github.com/docker/machine/pull/4141 ) should fix this.

**Comment by febLey** [comment]
Means that we have to wait for an update, right?

**Comment by romanrev** [comment]
experiencing the same issue here, had to comment the 
```
[[ ${words[$glob_pos]} == @($glob) ]] && echo "$key"
```
out. 
On a personal note I would advise against using bashisms in shell scripts wherever possible. Or test for their applicability before using them at least.
Mac OS 10.12.5 and
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by jakirkham** [comment]
This appears to be solved now.

**Comment by jakirkham** [comment]
Reopening as am seeing this in the Docker Edge ( 18.03.0-ce-rc1-mac54 (23022) ). Line number is now 73, but is otherwise the exact same problem.
