### ISSUE TITLE
Failure to Start Docker Mac for first time using DMG installer

### ISSUE THREAD

**Issue by splash111** [docker/for-mac#1832]
### Expected behavior
Initial start 
### Actual behavior
Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/F8625B3F-9C18-43CF-B5E1-5AB7CFF02C0A/20170707-010901.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Volumes/1.5 TB Data Dock/Home_Folders/wbrown/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. ... Follow instructions to install Mac OS DMG
  2. ...Open Docker.app

Please note that I followed instructions  to remove old docker and kinematic app
Previous version information
MacMini15:~ wbrown$ docker --version
Docker version 1.8.2, build 0a8c2e3
MacMini15:~ wbrown$ docker-compose --version
docker-compose version: 1.4.1
MacMini15:~ wbrown$ docker-machine --version
docker-machine version 0.4.1 (e2c88d6)
MacMini15:~ wbrown$

**Comment by tmhudg** [comment]
FWIW, I just decided to try Docker and am getting this same error. I'm running MacOS 10.11.6 but I'm on a Hackintosh that I built myself. No idea if that is part of the problem but figured I'd mention it.

**Comment by splash111** [comment]
Tried using the edge version of Docker for Mac with the same error results.
Waiting for solution for the error I am receiving, but have uninstalled Docker for Mac and installed Docker version 17.05.0-ce, build 89658be docker toolbox. Hope solution comes soon as I would like to stay current with the Docker for Mac

**Comment by splash111** [comment]
Tried using the edge version of Docker for Mac with the same error results.
Waiting for solution for the error I am receiving, but have uninstalled Docker for Mac and installed Docker version 17.05.0-ce, build 89658be docker toolbox. Hope solution comes soon as I would like to stay current with the Docker for Mac
