### ISSUE TITLE
Docker restarting multiple times/day

### ISSUE THREAD

**Issue by Ranbato** [docker/for-mac#1833]
### Expected behavior
Containers would stay up.
### Actual behavior
Ever since upgrading last week, Docker and/or the containers stop multiple times/day.  Nothing else has changed materially.  Sleeping the machine seems to trigger it every time.

### Information
A900440C-6C99-4AE8-838C-CBAF642EB40D

Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/A900440C-6C99-4AE8-838C-CBAF642EB40D/20170707-112111.tar.gz
[20170707-111927.tar.gz](https://github.com/docker/for-mac/files/1131801/20170707-111927.tar.gz)
[20170707-111927.tar.gz](https://github.com/docker/for-mac/files/1131805/20170707-111927.tar.gz)

failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run my images
  2. Wait

**Comment by djs55** [comment]
Thanks for your report. I think this is the same issue as https://github.com/docker/for-mac/issues/1809. There's a fix scheduled to be released in 17.06.1 which is due to be released very soon. I'm sorry for the inconvenience in the meantime.

**Comment by djs55** [comment]
As a temporary workaround, try setting: Whale menu -> Preferences... -> Proxy -> No Proxy. Let me know if that helps.

**Comment by Ranbato** [comment]
Thanks, I'll try it

**Comment by djs55** [comment]
The bug which caused the VM to reboot too often should have been fixed in the latest patch release:
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
If it still manifests, could you upload a fresh diagnostic and let me know?

Thanks for your report.
