### ISSUE TITLE
docker.for.mac.localhost does not get setup in all containers

### ISSUE THREAD

**Issue by duro** [docker/for-mac#1836]
### Expected behavior

That no matter what, the `docker.for.mac.localhost` hostname is exposed in all containers

### Actual behavior

Some of my containers have the `docker.for.mac.localhost` hostname available, and others do not

### Information

I am using a tool called Praxis (v2 of Convox). It has the ability to start containers and also run a test command on containers. For some reason the `docker.for.mac.localhost` hostname is available in containers started with some commands but not others.

Can someone give me some insight into how `docker.for.mac.localhost` is set inside a container so I can further debug why certain run commands get the host name but not others?

**Comment by duro** [comment]
We were able to figure this out on our end. Closing

**Comment by sa-jbrooks** [comment]
@duro, can you expand on that? Your solution may be helpful to others (like me) who are having issues with docker.for.mac.localhost.

**Comment by awdng** [comment]
@duro having issues with this too, could you post your solution ?

**Comment by duro** [comment]
@sa-jbrooks and @awdng Our issue was with a local development tool we were using called Praxis (aka Convox 2.0). It was doing some magic with local and container DNS that was causing my issue. The developers of the tool figured out what was going on, and once they made the fix, it started working. I wish I knew more about what they did. But it may not be anywhere near close to related to the issues you guys are experiencing.
