### ISSUE TITLE
use something else other than .localhost at the end of docker.for.mac.localhost

### ISSUE THREAD

**Issue by andrewchen5678** [docker/for-mac#1837]
### Expected behavior
docker.for.mac.localhost works on guest's Chrome browser

### Actual behavior
docker.for.mac.localhost doesn't work on Chrome because .localhost is strictly reserved for local ips and Chrome won't try to resolve the hostname

### Suggestion
Use something else other than .localhost for tld for the special Mac-only DNS name docker.for.mac.localhost because .localhost is supposed to be reserved for local only traffic. See https://en.wikipedia.org/wiki/.localhost

**Comment by speigg** [comment]
I'm seeing this problem too. How about `docker.for.mac.local`... or just `docker.local` ?

**Comment by atuttle** [comment]
A container-internal hostname that is dependent on the host OS is the wrong solution. If I write code that depends on there being a `docker.for.mac.localhost` host available, then hand that container over to a linux or windows user, it will not function properly. A cross-platform solution is necessary.

**Comment by chevell** [comment]
Agreed @atuttle, some kind of `docker.host.local` solution is needed

**Comment by jtneal** [comment]
This also isn't working for me. Anything .localhost in my container resolves to 127.0.0.1 - localhost of the container, not the IP of the host machine.

> docker exec -it my_container getent ahosts docker.for.mac.localhost
> 127.0.0.1
>
> docker exec -it my_container getent ahosts whatever.i.want.localhost
> 127.0.0.1

**Comment by cllovatto** [comment]
If anyone hasn't come across it yet, a workaround would be to use IP address **192.168.65.1** 
This resolves to the mac host.
Original post:
https://github.com/moby/moby/issues/22753#issuecomment-282725489

**Comment by HaysHopkins** [comment]
I'm not seeing any question quite like this and this seems as good of a place as any to ask, so:

I can ping `docker.for.mac.localhost` and `192.168.65.1` just fine.  I know my non-docker service is running there just fine.  I can reach it at `localhost.mywebsite.com:9999` in chrome just fine.  However, I can't just do `docker.for.mac.localhost.mywebsite.com:9999`.  

It's driving me crazy!  Any suggestions to reach this address? (changing it is not an option for me)

**Comment by atuttle** [comment]
@HaysHopkins unless you've setup DNS or a hosts file entry for that address, you shouldn't expect it to work. You can configure the website to respond for `docker.for.mac.localhost` in addition to `localhost.mywebsite.com` or make it reply with your website regardless of the domain name (i.e. the default if no host match is found) ~~ e.g. anything hitting port 9999 gets your website regardless of hostname. This is the default setup in most cases if only one website is being served by the server.

If you can't ping `docker.for.mac.localhost.mywebsite.com` from inside the container then the request will never leave the container.

**Comment by aleksandrs-ledovskis** [comment]
This issue has been fixed in [17.12.0-ce-mac46](https://github.com/docker/docker.github.io/blob/master/docker-for-mac/release-notes.md#docker-community-edition-17120-ce-mac46-2018-01-09-stable) release

**Comment by atuttle** [comment]
"Fixed" is arguable as the container still needs to know that it's running on docker for mac; as noted [in October](https://github.com/docker/for-mac/issues/1837#issuecomment-336996473).

**Comment by pgayvallet** [comment]
Using `docker.for.mac.host.internal` fixes the author issue.

Discussions about how a container should know if it should interract with the effective host (mac) or the actual host (vm) is out of the scope.

Closing
