### ISSUE TITLE
Docker for Mac on High Sierra with APFS

### ISSUE THREAD

**Issue by lvnilesh** [docker/for-mac#1838]
### Expected behavior
I expect docker to work but know that I am using high sierra with APFS which is probably not supported yet. 
 
### Actual behavior

APFS performance impressed me but build context in gigabytes and still adding... WHOA!

### Information

```
docker build .
Sending build context to Docker daemon  2.676GB
^C
```
### Steps to reproduce the behavior

  1. Get high sierra and use APFS
  2. docker build something

**Comment by hgl** [comment]
I'm also using High Sierra with APFS. For me, my keystrokes would be eaten intermittently when docker (latest edge version, I have docker uninstalled right now, so don't have the version number) is running. Quitting it and restarts the mac fixes the problem. I wonder if that's the case for you too @lvnilesh ?

I'm using iMac (27-inch, Mid 2011)

**Comment by lvnilesh** [comment]
I haven't thoroughly verified this yet but mac OS Hig Sierra 10.13 Beta (17A306f) with APFS and Docker version 17.06.0-ce, build 02c1d87 seems to have resolved the issue I noted.

**Comment by OskarStark** [comment]
Can you say something about the performance @lvnilesh ?

Docker for Mac OSXFS <> Docker for Mac APFS?

**Comment by mikl** [comment]
Just for clarity, the old filesystem for macOS is [HFS+](https://en.wikipedia.org/wiki/HFS_Plus).

**Comment by OskarStark** [comment]
> Just for clarity, the old filesystem for macOS is HFS+.

Yes I know...

**Comment by lvnilesh** [comment]
Hard to quantify because I do not have a similar HFS+ system but docker disk performance seems super snappy on the latest available fully configured iMac running docker version 17.07.0-ce-rc2, build 36ce605 with MacOS High Sierra 10.13 Beta (17A344b) Darwin iMac.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 10 17:58:14 PDT 2017; root:xnu-4570.1.43~2/RELEASE_X86_64 x86_64

**Comment by OskarStark** [comment]
Thank you for your feedback, will wait for the official High Sierra release and try again with APFS 👍

**Comment by Briones** [comment]
Seems like Apple has released the GM version of High Sierra, anyone has tried if this resolves the performance issue in Docker for Mac?

**Comment by pfx2** [comment]
No, I’m on High Sierra GM with APFS and volumes are still slow as hell...
But maybe the Docker team will be able to improve the performance of volumes based on APFS features. We have to give them time as APFS is not documented well.

**Comment by bjoern-flagbit** [comment]
i can tell the same ... the performance is still slow as hell ...

**Comment by VincentClair** [comment]
I had the same problem (high sierra and before)

But i resolved it this day by using https://github.com/EugenMayer/docker-sync.
And for me, it works as heaven \o/

**Comment by pfx2** [comment]
I had many with Docker sync.
First, it is slow as hell, when you have more than 10 volumes and a lot of files on volumes, your project can take up to 2 minutes to start.
More importantly I had issues with syncing that let with corrupted MariaDB database.

**Comment by VincentClair** [comment]
My use case:
- an image with Symfony project
- little database stored as sqlite in a data folder for dev

Here is the config file:
```
version: '2'

syncs:
  back-sync:
    src: '../../back'
    sync_excludes: ['docs', 'var']
  data-sync:
    notify_terminal: true
    src: '../../data'
    sync_excludes: ['default']
  public-sync:
    src: '../../data/public'
```

For my knowledge, which use case/project to you try docker-sync ? Is it Symfony too ?

**Comment by pfx2** [comment]
Yes I tried with recent versions.
I used with Symfony projects with MariaDB, RabbitMQ, Nginx.

With SQLlite you should not have any problem since the integrity of the DB is contained inside the file.
