### ISSUE TITLE
Docker Engine Logs are Missing

### ISSUE THREAD

**Issue by afrazkhan** [docker/for-mac#1857]
### Expected behavior
Log files to be present in `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/`

### Actual behavior
No logfiles are created.

### Information
Up until some time ago (?), the folder `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/` contained logs produced by the Docker engine, as specified in the documentation. It no longer creates these, making docker engine debugging impossible.

My version:
```
Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0
```

### Steps to reproduce the behavior
1. Add `debug: true` to your Docker config
2. Create a container
3. Watch there be no logs for Docker engine activity in `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/`

**Comment by jolson490** [comment]
+1

**Comment by afrazkhan** [comment]
Oh cool, the workaround where I attached screen to the tty of the VM no longer works either :D

**Comment by djs55** [comment]
Thanks for your report -- sorry the logs are currently not available on the host.

For a workaround, I installed the latest stable version
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
and ran this on the host:
```
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty 
```
and this inside the tty:
```
/ # tail -f /var/log/docker.log
...
Jul 17 14:48:16 moby root: time="2017-07-17T14:48:16.353249141Z" level=debug msg="Calling GET /_ping"  
Jul 17 14:48:16 moby root: time="2017-07-17T14:48:16.354762611Z" level=debug msg="Calling GET /v1.30/containers/json"  
```

**Comment by pgayvallet** [comment]
Logs are available inside the vm
`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`
then
`tail -f /var/log/docker-ce.log`

Closing.
