### ISSUE TITLE
No Docker for Mac access

### ISSUE THREAD

**Issue by alexellis** [docker/for-mac#1858]
## Actual behavior

I can't start Docker for Mac - 755DFA5D-214D-48F0-978F-1730FFC692B9

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Click the Moby icon.
  2. Cannot communicate with Docker etc.. 

Edit: Diagnostic didn't upload.. who can I email it to?

**Comment by djs55** [comment]
Could you email it to me? <github username>@docker.com.

**Comment by pgayvallet** [comment]
@alexellis any news on this ?

**Comment by alexellis** [comment]
I wasn't able to upload the diagnostics. It's working now.. I mean this was over half a year go.. I guess I switched to stable at the time.
