### ISSUE TITLE
registry mirrors missing in 17.06.0

### ISSUE THREAD

**Issue by warroyo** [docker/for-mac#1862]
### Expected behavior

when setting a registry mirror it should appear in the output of `docker info` as well as work as a mirror.

### Actual behavior

mirrors are missing from the `docker info` and are not being used.

**Comment by domdorn** [comment]
+1 I'm affected by this too!

**Comment by yfoelling** [comment]
+1 affected too.
docker pull etc. do not respect the Registrys provided in the ".docker/config.json" or in the docker for mac GUI

**Comment by domdorn** [comment]
In my case, the error was because of this:
I had a login stored for dockers main registry 
This login was sent to my mirror, which checked the credentials against its DB, but couldn't find them. Then it said BAD_CREDENTIALS and went on to the next "mirror" which was the official registry, where the image in question was not found. 

docker logout

solved it for me.

**Comment by thaJeztah** [comment]
Did you specify the registry as `example.com:5000` or as `https://example.com:5000` ?

 I see the "example" input in  the UI is misleading, as it states `mydomain.com:5000`, without `https://`

<img width="380" alt="screen shot 2017-08-10 at 13 59 16" src="https://user-images.githubusercontent.com/1804568/29170773-61baf0b6-7dda-11e7-8f2f-a17262d46be3.png">


I checked the code, and it looks like an invalid mirror is _validated_ during startup, but silently ignored if the value is not correct; I opened an issue for that here: https://github.com/moby/moby/issues/34476

I'll also open an issue internally to have the misleading example value in the configuration panel fixed.

**Comment by dtmistry** [comment]
On the latest docker for mac, the insecure registries are not listed on the `docker info`. I've added the insecure registry on the Daemon option

```
10:56 $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by andrevtg** [comment]
I had to do "docker logout" and "docker logout my_mirror_url". I also disabled the "securely store docker logins in osx keychain" and repeated the "docker logout" commands. Worked!
