### ISSUE TITLE
More restrictive networking/ulimit in 17.06.0-ce-mac19?

### ISSUE THREAD

**Issue by jabley** [docker/for-mac#1863]
### Expected behaviour

I have a Go code base which is built and tested in Docker. It used to work in 17.03 Docker for Mac. I upgraded to 17.06, and now the tests fail.

The same version of the code still works fine in CI. (Docker on Linux)

The tests creates a server, then creates clients which interact with the server.

### Actual behaviour

When it tries to create the clients, I see:

--- FAIL: TestSlowRetrIsLogged/failure (2.57s)
        Error Trace:    server_test.go:67
    	            	server_test.go:786
    	            	server_test.go:753
    	Error:      	Unable to connect to server
    	Messages:   	dial tcp [::]:39405: connect: cannot assign requested address

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/F92B257A-0F65-4D2F-A8EA-B998D4783ADA/20170713-190353.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behaviour

I would like to be able to downgrade to Docker 17.03 and verify that the only thing which has changed is the version of Docker. But I don't see download links to the old version?

**Comment by cswank** [comment]
I'm also seeing this problem after upgrading to 17.06.  In my case a ruby Sinatra web service bombs out with:

Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "localhost" port 50061

I have golang web apps that are running in the same container and they can start up just fine with "localhost:<PORT>" and "0.0.0.0:<PORT" and "127.0.0.1:<PORT>".  I'm not sure what the difference is between the go web apps and the ruby sinatra ones.

**Comment by jabley** [comment]
Added a test case to https://github.com/jabley/docker-networking-repro which I think reproduces the problem.

**Comment by mattbostock** [comment]
@jabley: The Git history for the Homebrew Cask recipe is a good source for old download links:
https://github.com/caskroom/homebrew-cask/commits/master/Casks/docker.rb

**Comment by mattbostock** [comment]
Some additional info:

If you change `tcp` to `tcp4` in the [test case](https://github.com/jabley/docker-networking-repro), the issue does not occur. `tcp` and `tcp6` both trigger the issue.

I was testing on:

```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.6 (build: 15G1421)
```

**Comment by jsstrn** [comment]
If you have issues with `Docker for Mac: Version 17.06.0-ce-mac19 (18663)`, then try downloading [`Docker for Mac: Version 17.03.1-ce-mac12 (17661)`](https://download.docker.com/mac/stable/17661/Docker.dmg). This worked for me.

**Comment by cswank** [comment]
I just upgraded to 17.09.0-ce-mac33 (19543) and this problem still persists, just in case anyone is wondering.

**Comment by jabley** [comment]
Problem still there in 17.12.0-ce-mac47 (21805) too.

Is there some configuration thing that will make this work? `features.support-ip6-names: true` or something?

**Comment by jabley** [comment]
`docker build --network host .` works in my test case repository. I no longer work on the code base where I encountered the initial instance of the problem, so I can't say whether it fixes the problem there too (proprietary code for a previous client).
