### ISSUE TITLE
Slow Restarts

### ISSUE THREAD

**Issue by delmartechdude** [docker/for-mac#1864]
### Expected behavior
Docker for Mac restarts in less than 30 seconds.

### Actual behavior
Docker for Mac hangs in the "restart" phase seemingly forever.

### Information

```Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/41559239-93CA-4843-95F4-F59CC8EFF1D6/20170712-165957.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```
Diagnostic ID: `41559239-93CA-4843-95F4-F59CC8EFF1D6`

### Steps to reproduce the behavior

  1. From the menu bar, click "Restart"
  2. Hangs (not always, but often)

**Comment by eexit** [comment]
Yes, I find it also very slow lately :(

**Comment by YRM64** [comment]
Delmartechdude,

Thank you so much for your contribution on why Docker-for-Mac hangs or restarts slowly.  You indicated your working on replacing Docker-for-Mac with vagrant images running the Docker Daemon.  Can you please shed a little bit more light on when that replacement will occur, and will this be an edge or stable version release, and how will the change affect Docker-for-Mac users in the development community.

Thanks

**Comment by YRM64** [comment]
Delmartechdude,

Thank you so much for that point of clarification.  I'm interested in knowing how that turns out.  Can you please in your spare time drop us a post, and let us know what it's like working with Vagrant images, and how your project turned out (inquiring minds want to know 😊).
