### ISSUE TITLE
Cannot connect to hosts over VPN from inside docker container

### ISSUE THREAD

**Issue by stantonk** [docker/for-mac#1865]
### Expected behavior
Hosts on the other end of a VPN can be accessed from containers.

### Actual behavior
Hosts not found.

### Information

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.6 (build: 15G1510)
logs: /tmp/33A6B91C-DBD5-479A-9E6A-91702C6AEFC2/20170713-223246.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

1. Connect to a VPN.
2. Try to run any command inside any container that tries to access a hostname that should be available via DNS over the VPN.
3. Get a host not found error.

**Comment by stantonk** [comment]
I reverted to ```Version 1.12.5 (14777)
Channel: Stable
3e6f00c1dc``` and it works fine.

**Comment by stantonk** [comment]
Please let me know how else I can help diagnose!

**Comment by jasonbivins** [comment]
Hi @stantonk 
Can you provide a few examples of the commands you were using so I can try to repro this?

**Comment by stantonk** [comment]
@jasonbivins my apologies, I tried reinstalling 17.06.0-ce-mac19 and it works now. Closing
