### ISSUE TITLE
Get https://registry-1.docker.io/v2/: dial tcp []:443: getsockopt: connection refused

### ISSUE THREAD

**Issue by jsaraiya1** [docker/for-mac#1866]
### Expected behavior
I am not able to pull or build any docker images. Getting getsockopt connection refused error.
### Actual behavior
when I try 
_docker pull hello-world_

I get the Error
Using default tag: latest
**Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 52.44.30.97:443:** getsockopt: connection refused

### Information
Using Docker Version:  Docker version 17.06.0-ce, build 02c1d87
MacOS : 10.12.4
  How do I run  "Diagnose & Feedback" ?

**Comment by jasonbivins** [comment]
Hi @jsaraiya1   what happens when you run the docker login command?

**Comment by kuznero** [comment]
Same issue here. All of a sudden it started showing this error.

**Comment by arturo-cobos** [comment]
same issue here.

**Comment by abienkowski** [comment]
Just got into the same issue on one of my VMs; any resolution or debugging suggestions?  docker login throws the same error.

**Comment by Vsap** [comment]
Same, one more time
