### ISSUE TITLE
Docker 17.06.0-ce-mac19 does not start

### ISSUE THREAD

**Issue by vasya10** [docker/for-mac#1868]
### Expected behavior

Docker engine must be running

### Actual behavior
Upon system restart, Docker engine does not seem to start. The menu is accessible, whale icon keeps animating, status is always "Docker starting..."

### Information

(I noticed in issue #1801 this was fixed in mac19, but I am still seeing the issue).

Diagnostic ID: 536AC21D-6FB8-4153-8189-121D520BAEBC

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/536AC21D-6FB8-4153-8189-121D520BAEBC/20170715-085839.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

Both docker images and docker ps -a commands return "Error response from daemon: Bad response from Docker engine"

### Steps to reproduce the behavior

Just restart system ("Start Docker when you log in" is enabled)

**Comment by vasya10** [comment]
I did a complete uninstall of my previous docker (17.06.0-mac18, this one has the restarting issue too) by using this script https://raw.githubusercontent.com/docker/toolbox/master/osx/uninstall.sh and removing Docker.app from Applications. Removed the related config/prop files too. The docker VMs were gone, but this was okay for me. 

Installed again from https://docs.docker.com/docker-for-mac/install/#where-to-go-next and I do not see the above issue any more.

So I guess the restarting issue appears specifically when from upgrading from 17.03 to 17.06 (18/19).

**Comment by natemurthy** [comment]
I also did the same as @vasya10 using the same script to uninstall (and also removing `/Applications/Docker.app` but it too just hangs in 'Docker starting...' state. Here's my diagnostic:
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/716DBF29-C5E8-4D8A-92F8-CBEE248D0AE5/20170715-120905.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by vasya10** [comment]
@natemurthy after uninstalling ensure its really gone (run docker cmd to ensure command not found. I had to run twice for some reason). Then also remove the *docker* preference files. Ensure your MacOS is up-to-date (mine's 10.12.5)

**Comment by chris-aeviator** [comment]
same here, just updated docker on osx 10.10.5 and docker won't start up anymore.

**Comment by jasonbivins** [comment]
Try  stopping Docker, and then delete this file, then restarting.
 - please be warned that doing this will delete ALL containers and images: 
Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux Docker.qcow2

**Comment by saouddk** [comment]
Had the same issue when upgrading from 17.03 to 17.06 (Edge), I solved the problem by doing the following:
sudo pkill -f Docker -9
sudo pkill -f docker -9

Confirm no docker process is running:
ps aux | grep docker

Then launch Docker.app, and it should launch the daemon successfully.

**Comment by Pithikos** [comment]
None of the above worked for me on Sierra. Solution was to go on the menu of "Docker for Mac" and click on "Clear all data"

**Comment by ksorathiya** [comment]
Not just clearing data, resetting to factory default worked for me. But I have to lose all my container and images in the process, that's too painful
![image](https://user-images.githubusercontent.com/19905441/34401766-56dd324c-ebc3-11e7-9f02-8d1cb072b4a4.png)
