### ISSUE TITLE
http refuses connection on port 80 except when specifying port 8080

### ISSUE THREAD

**Issue by christianLuis** [docker/for-mac#1869]
### Expected behavior 
Receive data from docker on port 80, because it is running without errors and listens on port 80

### Actual behavior 
Refuses connection on port 80 when port 80 is specified. When specifying port 8080, I receive data on port 80 and port 8080. So localhost and localhost:8080 both work fine then. 

### Attempts to get it working
- Removed all data via Docker interface (Preferences >Reset > Remove all data)
- Installed latest stable and edge Version 
- Tried different docker images (nginx and apache)
- Tried it on another mac machine and it did work fine

### Information
Diagnostic-ID: 1C2EFE4C-30B0-47D5-83EA-B3A553AF6995

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/1C2EFE4C-30B0-47D5-83EA-B3A553AF6995/20170715-212631.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker run -d -p 80:80 nginx
1038a81b722d4627f6feaec3260f1625c20a5acfc5e41b56f5340f228674d47d

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
1038a81b722d        nginx               "nginx -g 'daemon ..."   19 seconds ago      Up 17 seconds       0.0.0.0:80->80/tcp   gallant_bhabha

$ curl -I localhost
curl: (7) Failed to connect to localhost port 80: Connection refused

$ docker stop gallant_bhabha
gallant_bhabha

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                     PORTS               NAMES
1038a81b722d        nginx               "nginx -g 'daemon ..."   About a minute ago   Exited (0) 7 seconds ago                       gallant_bhabha

$ docker run -d -p 8080:80 nginx
ef62ae0d2b743363f48e324a1f01a1197f0a0e3ebec7ba601147e83b0dd2ad72

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                  NAMES
ef62ae0d2b74        nginx               "nginx -g 'daemon ..."   24 seconds ago      Up 23 seconds                   0.0.0.0:8080->80/tcp   clever_turing
1038a81b722d        nginx               "nginx -g 'daemon ..."   2 minutes ago       Exited (0) About a minute ago                          gallant_bhabha

$ curl -I localhost
HTTP/1.1 200 OK
Server: nginx/1.13.3
Date: Sat, 15 Jul 2017 19:29:09 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 11 Jul 2017 13:06:07 GMT
Connection: keep-alive
ETag: "5964cd3f-264"
Accept-Ranges: bytes

$ curl -I localhost:8080
HTTP/1.1 200 OK
Server: nginx/1.13.3
Date: Sat, 15 Jul 2017 19:29:29 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 11 Jul 2017 13:06:07 GMT
Connection: keep-alive
ETag: "5964cd3f-264"
Accept-Ranges: bytes
```

**Comment by jasonbivins** [comment]
Hi @christianLuis I can't repro this on a vanilla install - and you mentioned that it worked on another machine. had you made any changes to your proxy settings, or the daemon on this machine?

**Comment by leglands** [comment]
I've got the same problem. It was an old apache brew install which put a  co.echo.httpdfwd.plist
in /Library/LaunchDaemons which contains :
 sh -c 'echo "rdr pass proto tcp from any to any port {80,8080} -> 127.0.0.1 port 8080" | pfctl -a "com.apple/260.HttpFwdFirewall" -Ef - && echo "rdr pass proto tcp from any to any port {443,8443} -> 127.0.0.1 port 8443" | pfctl -a "com.apple/261.HttpFwdFirewall" -Ef - && sysctl -w net.inet.ip.forwarding=1'

i've removed and restarted macosx

**Comment by christianLuis** [comment]
Thanks @leglands that did the job!
