### ISSUE TITLE
docker restarts itself *every time* I connect to VPN with Viscosity

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1872]
### Expected behavior
I want to connect and disconnect my work VPN (using Viscosity) without Docker for Mac getting screwed up or requiring a few minutes of restarts.
### Actual behavior
Docker for Mac won't respond after I connect VPN and eventually seems to restart itself (little icon animates for minutes).

### Information
```
Docker for Mac: version: 17.06.0-ce-mac17 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F2073)
logs: /tmp/D6C0858E-2E0F-4F48-AE9C-7E68EE9E2F13/20170717-113826.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Use docker for mac
  2. Work requires VPN, use Viscosity.

**Comment by djs55** [comment]
Thanks for your report. I suspect this is the same issue as #1801 which has been fixed in the most recent patch release on the stable branch.

Could you check for updates and try again with this version:
```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```
Let me know what happens!

**Comment by jamshid** [comment]
Closing, don't see this problem with Version 17.06.0-ce-mac19 (18663).
