### ISSUE TITLE
Docker Restarts on Open/Close of Charles Proxy

### ISSUE THREAD

**Issue by timothyallan** [docker/for-mac#1873]
Still getting proxy related reboots using Version 17.06.0-ce-mac19 (18663) on macOS 10.12.5

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Expected behavior
Docker stays running as it has in the majority of previous versions.

### Actual behavior
Docker restarts and borks all my running containers.

### Information
Assuming this is related to the potential fix mentioned in #1789 

### Steps to reproduce the behavior
  1. Open Charles Proxy, and/or
  2. Close Charles Proxy

**Comment by jasonbivins** [comment]
Hi @timothyallan   Can you please update your version and try again?  The latest version might take care of this for you -  Version 17.06.0-ce-mac19 (18663)

**Comment by timothyallan** [comment]
For those visual orientated folks....

![docker proxy restart](https://user-images.githubusercontent.com/1995135/28491894-f7575882-6eb5-11e7-9dd4-bc5aad6f3a58.gif)

**Comment by UnitySteven** [comment]
Any updates on this?

**Comment by jackalcooper** [comment]
Any updates on this?

**Comment by jechol** [comment]
I'm experiencing same issue.

**Comment by emmaf-eb** [comment]
I'm also experiencing this issue. 

Docker:
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c

OS:
macOS 10.12.6

**Comment by takc923** [comment]
I've resolved this with https://github.com/docker/for-mac/issues/2039#issuecomment-340369638

**Comment by jimfrenette** [comment]
I'm still experiencing this issue with 17.09.1-ce-mac42 (21090)

**Comment by jimfrenette** [comment]
Yay! latest Docker for Mac fixes Charles Proxy reboot issue plus a lot of other stuff, including the VM file resize and location. Version 17.12.0-ce-mac46 (21698)
