### ISSUE TITLE
debug options yield no additional log output for docker login

### ISSUE THREAD

**Issue by jolson490** [docker/for-mac#1878]
### Expected behavior

I'm guessing there should be some amount of additional log output when running the `docker login` command with various debug options?

### Actual behavior

The log output is the same regardless of how many debug options I provide.

### Information

Diagnostic ID: FCA54731-DF12-4345-9599-D3BD87DFE4D3

And here's some of the key details from running the diagnostic (on my MacBook Pro):
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/FCA54731-DF12-4345-9599-D3BD87DFE4D3/20170718-075857.tar.gz
```

### Steps to reproduce the behavior

  1. Under `Docker`, `Preferences`, `Daemon`, `Advanced`, I specified:
```
{
  "debug" : true
}
```

  2. I ran into the [1857](https://github.com/docker/for-mac/issues/1857) issue ("Docker Engine Logs are Missing"), but I was able to use the [workaround](https://github.com/docker/for-mac/issues/1857#issuecomment-315778206) to view the `docker.log` via `tty`.

  3. I did the following command: `docker --debug=true --log-level=debug login -u AWS -p <password> https://<account>.dkr.ecr.us-east-1.amazonaws.com` (and the only output to my terminal from that command is `Login Succeeded`)

  4. Then I check the `docker.log` and the output is:
```
Jul 18 13:10:31 moby root: time="2017-07-18T13:10:31.803688731Z" level=debug msg="Calling GET /_ping"
Jul 18 13:10:43 moby root: time="2017-07-18T13:10:43.815101656Z" level=debug msg="Calling GET /_ping"
Jul 18 13:10:43 moby root: time="2017-07-18T13:10:43.816653353Z" level=debug msg="Calling GET /v1.30/info"
Jul 18 13:10:43 moby root: time="2017-07-18T13:10:43.972783735Z" level=debug msg="Calling POST /v1.30/auth"
Jul 18 13:10:43 moby root: time="2017-07-18T13:10:43.972945167Z" level=debug msg="form data: {\"password\":\"*****\",\"serveraddress\":\"<account>.dkr.ecr.us-east-1.amazonaws.com\",\"username\":\"AWS\"}"
Jul 18 13:10:44 moby root: time="2017-07-18T13:10:44.164876612Z" level=debug msg="hostDir: /etc/docker/certs.d/<account>.dkr.ecr.us-east-1.amazonaws.com"
Jul 18 13:10:44 moby root: time="2017-07-18T13:10:44.165006837Z" level=debug msg="attempting v2 login to registry endpoint https://<account>.dkr.ecr.us-east-1.amazonaws.com/v2/"
```

But even without the `--debug=true --log-level=debug` and without the `"debug" : true`, the output to the `docker.log` is the same.

Any assistance/suggestions would be greatly appreciated. (If my expectations are inaccurate or if I'm doing something wrong, please let me know.) Thanks!

**Comment by s50600822** [comment]
I got the same issue with Auth.
So I got a file called cred with content
> {"username":<USER>,"password":"<PASS>","serveraddress":"<PRIVATE REGISTRY>"}

This supposed to work (it does on most machines)
> curl -X POST -H "Content-Type: application/json" -H "X-Registry-Auth: $(base64 -i cred)"  --unix-socket /var/run/docker.sock http://localhost:80/images/create\?fromImage\=....

However on certain machine it always fails with Auth. This is the way Java client interact with Docker deamon. On the same machine, native docker pull itself works perfectly. I really need the detail from native docker client "pull" command for comparison. Can we reopen this.
