### ISSUE TITLE
:cached file mounts don't update at all; restart impossible

### ISSUE THREAD

**Issue by Nemo64** [docker/for-mac#1879]
### Expected behavior
A cache mount should get changes from the host ~ even a little delayed, that's fine.

### Actual behavior
Cached mounts stop updating after a long running time.
Restarting the deamon in this situation is impossible though the gui.
Only kill -9 helps to restart the deamon after which it works again for a day or 2.

### Information

Diagnostic id: ED0DC8BA-76DB-421D-B170-5E1C8624CE6B
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)

### Steps to reproduce the behavior

1. use a cached mount for a few hours/days regularly (i'm developing php applications)
2. see mounts not getting updated.

**Comment by dsheets** [comment]
When you say "restarting the daemon in this situation is impossible through the GUI" what do you mean? What happens when you try to restart the daemon? Is there an error?

**Comment by Nemo64** [comment]
My input is ignored. No restart is happening.
If I Quit the Application, the deamon will continue to run and when I start the Application again, it will try to start the already running deamon forever. If i kill all docker processes, then the start works flawless again and I'm save for a few days.
I haven't checked for a log file but I ran the diagnostic before killing everything.

**Comment by kevinsimper** [comment]
I also experience this that files does not get updated, that the cached call is too long even though it is changed on the host machine.

Change `package.json` on my mac, `cat package.json` and don't see it update also after 30 seconds.
