### ISSUE TITLE
can not execute docker command

### ISSUE THREAD

**Issue by battegoal** [docker/for-mac#188]
### Information

Diagnostic ID: 928AE1CB-A2F6-41FD-B45F-1984EAFC6318
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 928AE1CB-A2F6-41FD-B45F-1984EAFC6318/20160809-155533.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug  8 17:16:38 wave Docker[com.docker.vmnetd][52122] <Notice>: User 501 has container folder /Users/Wave/Library/Containers/com.docker.docker/Data/s60
Aug  8 17:16:38 wave Docker[com.docker.vmnetd][52122] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  8 17:16:38 wave Docker[com.docker.vmnetd][52122] <Notice>: User 501 has container folder /Users/Wave/Library/Containers/com.docker.docker/Data/s60
Aug  8 17:16:38 wave Docker[com.docker.vmnetd][52122] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  8 17:16:38 wave Docker[com.docker.docker][52026] <Error>: Symlinks are not correctly installed.
Aug  8 17:17:00 wave Docker[com.docker.docker][52026] <Notice>: progress 0.00
Aug  8 17:17:02 wave Docker[com.docker.docker][52026] <Notice>: progress 1.00
Aug  8 17:17:02 wave Docker[com.docker.docker][52026] <Notice>: progress 2.00
Aug  8 17:17:03 wave Docker[com.docker.docker][52026] <Notice>: progress 3.00
Aug  8 17:17:03 wave Docker[com.docker.docker][52026] <Notice>: progress 4.00
Aug  8 17:17:03 wave Docker[com.docker.docker][52026] <Notice>: progress 5.00
Aug  8 17:17:04 wave Docker[com.docker.docker][52026] <Notice>: progress 6.00
```
