### ISSUE TITLE
Occasional hanging during qcow2 compaction

### ISSUE THREAD

**Issue by buu700** [docker/for-mac#1880]
[The patch](https://github.com/docker/for-mac/issues/371#issuecomment-315385246) for #371 seems to be working pretty well for the most part. However, I've had Docker hang for a long period of time (maybe an hour) during or after a compaction on two occasions.

This didn't happen the second time, but the first time I killed Docker it started back up in a weird state (RAM limit increased from 4 GB to 1PB, possibly other settings lost):

<img width="602" src="https://user-images.githubusercontent.com/415435/28239138-cb510162-6932-11e7-82ce-9b9c77434a0e.png">

Diagnostic ID, if needed: D77B9D9C-8B21-4C19-8CDD-78649134265A

**Comment by phanigadde** [comment]
Hi, I got the same issue when using the online compaction patch.
