### ISSUE TITLE
Docker operations don't work with credStore line in the config.json

### ISSUE THREAD

**Issue by toli** [docker/for-mac#1881]
### Expected behavior
docker push/login should work
### Actual behavior
all of my operations error out:
```
$ docker login
error getting credentials - err: exit status 1, out: `One or more parameters passed to a function were not valid.`
```

### Information
I have `"credsStore" : "osxkeychain"` in the `~/.docker/config.json` file
ran `go get github.com/docker/docker-credential-helpers` and copied the resulting binary into `/usr/local/bin/`
it created a symlink to `~/Library/Group\ Containers/group.com.docker/bin/docker-credential-osxkeychain`
Running that command with `list` produces output:
```
$ ~/Library/Group\ Containers/group.com.docker/bin/docker-credential-osxkeychain list
{"http://192.168.24.128":"admin","http://192.168.24.129":"admin","http://192.168.99.100":"\u003ctoken\u003e","http://cdn-registry-1-stage.docker.io":"toli","http://dtr-internal.caas.docker.io":"\u003ctoken\u003e","http://dtr.demo.dckr.org":"\u003ctoken\u003e","http://dtr.us-west.dcus17.dckr.org":"toli","http://pod2-dtr.boothdemo.com":"admin","http://quay.io":"tolik@cs.stanford.edu","http://registry-1-stage.docker.io":"toli","http://registry-staging.docker.io":"toli","http://registry.dev.docker.com":"toli","https://54.71.151.14:12392":"admin","https://dtr-internal.caas.docker.io":"\u003ctoken\u003e","https://index.docker.io/v1/":"toli","https://registry-1-stage.docker.io":"toli"}
```
regardless, whenever i try doing `docker push` or `docker login` i'd get errors above.

removed the `credStore` line from `config.json` and was able to login and push repos again.
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.06.1-ce-rc1-mac20 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/BB7E601B-9710-43B7-BD9B-7AE525868235/20170718-151813.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

version:
```
Version 17.06.1-ce-rc1-mac20 (18682)
Channel: edge
28a0bb200d
```

### Steps to reproduce the behavior
install above version of docker4mac, enjoy

**Comment by n4ss** [comment]
1) does the command succeed when you unlock the keychain which contains your Docker credentials? to find it, simply open your keychain app, and search for "Docker Credentials", Keychain is the right-most column

2) Can you check that the credentials for "https://index.docker.io" are in the "login" keychain?

3) Can you pm me the content of your `config.json` file without the passwords if you have any in it?

**Comment by toli** [comment]
i unlocked the key for `index.docker.io` in Keychain directly and everything started working.

closing this.
