### ISSUE TITLE
Quickly slows down to become unusable

### ISSUE THREAD

**Issue by akimd** [docker/for-mac#1886]
### Expected behavior

I upgraded today to the latest version (yesterday I was on the previous most-recent version) and everything became barely usable.  The first commands inside the container did succeed (ls), but then the following ones either did not finish, or were so slow that I lost patience.

### Information

Diagnostic ID: A60BFBD8-8029-48F3-8C1A-7B65C21640B6

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Although I have no container running, Hyperkit is still consuming more than 2 cores.  Now that I have quit Docker, it still does.  I will leave it running, and see if it pacifies at some point.

**Comment by akimd** [comment]
It stopped after a couple of minutes.

**Comment by akimd** [comment]
I installed `Version 17.06.1-ce-rc1-mac20 (18682)`, and it works well.

**Comment by akimd** [comment]
OK, so I had not realised I installed the same version.  Yet it works now.  I guess there was some background process (qcow compaction?) that was running behind the scenes, without telling me anything about it, that slowed everything down to become unusable.

Close when you want.

**Comment by nchazlett** [comment]
Thanks for the update.

closing.
