### ISSUE TITLE
Unexpected API error (HTTP code 502): Bad response from Docker engine

### ISSUE THREAD

**Issue by jameslk** [docker/for-mac#1887]
### Expected behavior

`docker-compose up` runs continuously.

### Actual behavior

After about 30 minutes or so, my Docker container crashes with a 502 error. Here's the output I see:

```bash
$ docker-compose up
Starting adbuilder_db_1 ... 
Starting adbuilder_db_1 ... done
Attaching to adbuilder_db_1
db_1  | LOG:  database system was interrupted; last known up at 2017-07-19 00:13:13 UTC
db_1  | LOG:  database system was not properly shut down; automatic recovery in progress
db_1  | LOG:  invalid record length at 0/1B0B728: wanted 24, got 0
db_1  | LOG:  redo is not required
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  autovacuum launcher started
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  received smart shutdown request
db_1  | LOG:  autovacuum launcher shutting down
Unexpected API error for adbuilder_db_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

### Information

  - Diagnostic ID: `A177EE6F-72EA-41B6-BE04-9B3FF18C95DB`

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 17.06.0-ce-mac18 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.2 (build: 15C50)
logs: /tmp/A177EE6F-72EA-41B6-BE04-9B3FF18C95DB/20170719-131231.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW

docker-compose.yml
```
version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
```

### Steps to reproduce the behavior

  1. `docker-compose up`
  2. ???
  3. Failure!

**Comment by spikeheap** [comment]
Hi, I'm seeing the same issue on 17.06.0-ce-mac19 (18663), diagnostic ID `E4C59BBF-32B2-4F5C-A460-71CA3E00EC16`.

**Comment by nano4711** [comment]
Same here! It's very hard to reproduce as it happens randomly. My behaviour is that it's more often after hibernation.

Docker Version: 17.06.0-ce-mac19 (18663)

I've noticed that behavior since version 17.03.0-ce for the Mac. Before my compose was much more stable.

**Comment by Benjamin-Dobell** [comment]
Only just started running into this in recent Docker For Mac versions:

```
docker version
Client:
 Version:      17.09.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:25:36 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce-rc1
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Benjamin-Dobell** [comment]
Upgrading my version of `docker-compose` with:

```
pip install --upgrade docker-compose
```

_seems_ to have resolved the issue. However, the errors were somewhat sporadic, but at least for now that seems to have done the trick. I recommend others at least give it a try.

**Comment by Benjamin-Dobell** [comment]
Nope, sorry, still broken even after updating `docker-compose` 😞

**Comment by jinxuunity** [comment]
I got same issue on _17.06.2.-ce-mac27_ on Osx.  
I run the exactly same docker compose on Windows too, but I never saw this error.

**Comment by thaJeztah** [comment]
not able to reproduce this on docker for mac 17.09.0-ce-rc2, docker-compose version 1.16.1, build 6d1ac21

**Comment by Benjamin-Dobell** [comment]
@thaJeztah Confirmed.

Just upgraded Docker for Mac to `17.09.0-ce-rc2` and it's all clear thus far. Thanks!

**Comment by thaJeztah** [comment]
I'll keep this issue open for now, to see if it's resolved for everyone. Curious what may cause this issue (if it's an issue specific to Docker for Mac (possible) or the Docker Engine itself)

**Comment by jinxuunity** [comment]
when will the codes in _17.09.0-ce-rc2_ be released in the stable version?

**Comment by thaJeztah** [comment]
When it's ready :smile:

**Comment by Benjamin-Dobell** [comment]
I actually started running into this again today 😞 

Version 17.09.0-ce-mac31 (19478)

**Comment by sergioregueira** [comment]
I had this issue two months ago and it was fixed. Nevertheless, today it started to happen again.

As @jameslk commented, it fails when I use `docker-compose` to startup the containers.

**Docker version:**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Diagnose & Feedback:**
```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/D56FD221-FC7F-472E-9997-F9128ECC2398/20171106-160854.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Diagnostic ID:**
```
D56FD221-FC7F-472E-9997-F9128ECC2398
```

**Comment by Matheusbafutto** [comment]
Getting same problem here. Using 
Mac OSX 10.13.1
docker version 17.12.0-ce
```
Unexpected API error for [container] (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by AmazingTurtle** [comment]
Same issue on windows.

```
Unexpected API error for address_migration_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

Don't let this become stale:(

**Comment by alexbezhan** [comment]
Same issue on `High Sierra 10.13.6`:
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false
Error response from daemon: Bad response from Docker engine
```
