### ISSUE TITLE
docker install for mac fail

### ISSUE THREAD

**Issue by sheldon9527** [docker/for-mac#1892]
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G1212)
logs: /tmp/ADE8FE24-C223-4BE9-8E63-655783C9B2AA/20170721-143017.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Sheldon/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/Sheldon/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Sheldon/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Sheldon/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/Sheldon/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/Sheldon/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         wrong Docker version: 1.13.0 (expected 17.03.1-ce)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/Sheldon/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Sheldon/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by danielrafferty** [comment]
Try deleting the docker container file, located here: 
`/Users/My_User/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`

**Comment by yallop** [comment]
17.03.1-ce-mac12 is now an outdated release.  Could you try installing a more recent version to see whether the problem persists?  Please open a fresh issue if you encounter further problems.
