### ISSUE TITLE
Incompatibility of saved docker image between 17.03 and 17.06

### ISSUE THREAD

**Issue by bdharrington7** [docker/for-mac#1895]
I built an image in D4M 17.03.1-ce-mac12 (17661), and then saved the tarball with `docker save -o image.tar docker.mycompany.com/team/node:exp`. Then I proceeded to push it to the repository. With a different D4M client (Version 17.06.0-ce-mac19 (18663)), I pull the image down, and try to save this same image the same way: `docker save -o image-pulled.tar docker.mycompany.com/team/node:exp`
I'm getting the sha256 sum of each package to prove that they have the same contents. 

### Expected behavior
`docker save -o image-pulled.tar docker.mycompany.com/team/node:exp` on the pulled image will not result in an error. 

### Actual behavior
`docker save -o image-pulled.tar docker.mycompany.com/team/node:exp` results in a fatal error:

```
Error response from daemon: open /var/lib/docker/overlay2/194f5e58c74f556b2e2005d8ddea8e1eb674da3a07b65ec3e1363fe0c0170cf4/merged/usr/local/lib/node_modules/nodemon/node_modules/randomatic/node_modules/is-number/node_modules/kind-of/LICENSE: no such file or directory
```

Note that if I do this same process with the same 17.03 client, it works fine.

### To Reproduce: 
1. Build an image in D4M 17.03.1
2. push to a registry
3. pull from the registry using D4M 17.06.0
4. Save the pulled image with D4M 17.06.0: `docker save -o tarball.tar docker.mycompany.com/team/image:tag`

**Comment by dsheets** [comment]
Could you please reduce your regression reproduction and post a series of explicit steps and/or a script? We'd be very appreciative of an easy way to observe what you are observing.

**Comment by ijc** [comment]
Looks like quite a long path is involved, could this be related to https://github.com/moby/moby/issues/34092 ? A good explanation/summary of that one is in https://github.com/moby/moby/issues/34092#issuecomment-31523172.

**Comment by bdharrington7** [comment]
@ijc Nice find! That actually looks exactly like what's happening here.
