### ISSUE TITLE
High HyperKit CPU usage after upgrade

### ISSUE THREAD

**Issue by mbentley** [docker/for-mac#1897]
### Expected behavior
The `hyperkit` process shouldn't be attempting to turn my laptop into a mini hover craft :)

### Actual behavior
Seeing high CPU usage by HyperKit after upgrade on `edge` release.  After the update to `17.06.1-ce-rc1-mac20 (18682)`.  Diag id while high CPU usage was occurring: `6CA458F5-5F01-4E0D-AFF5-6593FD82B14F`

Everything checks out OK but I can't start any of my containers or run docker commands.

### Information
 - In case it does help or matter, I just upgraded my MacOS to the latest update: `10.12.6 (16G29)`. 
 Besides that, I didn't do anything specifically beside upgrade and have d4m come up; no containers are scheduled to start on daemon start.
  - Restarting Docker for Mac seems to bring it back to normal usage but I wanted to report just in case it was common.

### Steps to reproduce the behavior

  1. Upgrade to `17.06.1-ce-rc1-mac20 (18682)`

**Comment by tony19** [comment]
Same issue here for diag id: `6787B6DF-AB14-4590-BBAD-844F3C234480` after upgrading to `17.06.0-ce-mac19 (18663)` (stable @ `c98c1c25e0`).

**Comment by mbentley** [comment]
@tony19 - is it still happening for you?  Could you check activity monitor for disk i/o?

/cc @dsheets

**Comment by tony19** [comment]
Unfortunately not. I restarted Docker (by clicking the "Restart" button from the status bar menu), and now it's stuck in the "Starting" state. It's been like that for a few minutes now.

**Comment by mbentley** [comment]
I did the same thing.  I only ask as it was mentioned to me that is might be compaction of the qcow2 disk image file.

**Comment by drozzy** [comment]
This is happening to me only when I mount "named" volumes with docker compose.

**Comment by drakmail** [comment]
Have almost same problem (about 30% CPU usage by hyperkit after macOS reboot, not always able to run docker containers) with 17.06.0-ce-mac19 (18663 @c98c1c25e0). macOS version: 10.12.6 (my colleague with 10.12.5 have no problems with docker).

<img width="811" alt="screen shot 2017-08-21 at 17 52 02" src="https://user-images.githubusercontent.com/869453/29524856-a58cf34e-8699-11e7-88f6-9f12c287d0f4.png">

**Comment by drozzy** [comment]
Are you guys running Java containers? (Because this started happening to me when I started running JVM 8, I think). In which case I think Java 10 will maybe fix some of these problems:
https://www.opsian.com/blog/java-on-docker/

**Comment by drakmail** [comment]
@drozzy no, just node / nginx containers
