### ISSUE TITLE
Unable to access localhost network inside a container

### ISSUE THREAD

**Issue by kmsheng** [docker/for-mac#1898]
### Expected behavior
I expected to connect localhost redis (127.0.0.1:6379)

### Actual behavior
Unable to connect to localhost redis

### Information
  9BAD0FCF-E327-428B-B3E8-FD85193BCFAC

**Comment by kmsheng** [comment]
Problem solved.

1. https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container Add a network alias, for example `sudo ifconfig lo0 alias 123.123.123.123/24`
2. edit /usr/local/etc/redis.conf, make sure redis listens to 123.123.123.123 ( If you're using mysql, you probably have to edit my.cnf and add a mysql user to access 123.123.123.123 )

**Comment by meritozh** [comment]
Using `docker.for.mac.localhost` instead of `localhost` or `127.0.0.1` is a better way.

**Comment by thaJeztah** [comment]
@meritozh if you have a StackOverflow account, could you add that to the accepted answer? https://stackoverflow.com/a/31328031/1811501 - you can also add a link to the [I want to connect from a container to a service on the host](https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) section in the documentation

**Comment by qoomon** [comment]
I've created a docker container to access host ports => https://github.com/qoomon/docker-host

**Comment by HiuKwok** [comment]
@meritozh Finally reach here after half day of googling. Thx mate

**Comment by gauravmehla** [comment]
@meritozh Thanks man!! worked like charm

    location /dev {
        if ($host = "domain.com") {
            return 200 $host;
            add_header Content-Type text/plain;    
        }

        if ($host = "first_app.domain.com") {
            proxy_pass http://docker.for.mac.localhost:3000;  
        }

        if ($host = "second_app.domain.com") {
            proxy_pass http://docker.for.mac.localhost:3001;  
        }

        if ($host = "third_app.domain.com") {
            proxy_pass http://docker.for.mac.localhost:3002;  
        }

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade; 
    }

**Comment by maxp-edcast** [comment]
What's the point of this? Why not just support 127.0.0.1 or localhost?

**Comment by thaJeztah** [comment]
@maxp-edcast containers (by default) have their own networking namespace (it's what's makes them a container). 127.0.0.1 or localhost are localhost of the _container_, not of the _host_

**Comment by nigel-dewar** [comment]
I dont understand why I cant use localhost or 127.0.0.1 ? just makes things hard for no point

**Comment by thaJeztah** [comment]
> I dont understand why I cant use localhost or 127.0.0.1 ? just makes things hard for no point

See my comment above yours; when connecting to `127.0.0.1` or `localhost` inside a container your connecting to the localhost of the container itself, not the host (so not your Mac)

**Comment by JuanjoFR** [comment]
Thanks @meritozh.

`host.docker.internal` works for me on Mac.
