### ISSUE TITLE
osxfs:cached does not work with named volumes

### ISSUE THREAD

**Issue by lmakarov** [docker/for-mac#1899]
### Expected behavior

Cached flag should apply when set for a named (bind mounted) volume.

### Actual behavior

When using named volumes, the `cached` flag does not apply.

### Information

Diagnostic ID: 6CF6F893-8C12-4325-9733-0847F3114B13

```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/6CF6F893-8C12-4325-9733-0847F3114B13/20170724-145905.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

This does not work:

```
$ docker volume create --name project_root -o type=none -o device=$(pwd) -o o=bind
$ docker run -d --name cached-test -v project_root:/project-root:rw,cached alpine top -b
$ /Applications/Docker.app/Contents/MacOS/com.docker.osxfs state | grep $(basename $(pwd))
```

This works:

```
$ docker run -d --name cached-test -v $(pwd):/project-root:rw,cached alpine top -b
$ /Applications/Docker.app/Contents/MacOS/com.docker.osxfs state | grep $(basename $(pwd))
```

Related to #1592. CC @dsheets

**Comment by dsheets** [comment]
@lmakarov thanks for the report. inotify event delivery also does not occur with `local` docker volumes from bind mounts. To fix this, we will require moby/moby#33375.

**Comment by lmakarov** [comment]
@dsheets the upstream PR you referenced (https://github.com/moby/moby/pull/33375) was closed (not merged) yesterday. Does that mean there will be no solution for this issue in the near future?

**Comment by djs55** [comment]
@lmakarov sorry for the delay and thanks for your patience. I have a candidate fix for this issue which is being tested internally. I'll let you know how it goes.

**Comment by achekulaev** [comment]
I wonder if the fix is getting into the next Docker for Mac release?

**Comment by djs55** [comment]
@achekulaev could you try the latest edge release? https://docs.docker.com/docker-for-mac/edge-release-notes/ -- it should be fixed there and the same fix will be released on the stable branch soon.

**Comment by lmakarov** [comment]
I can confirm this now works as expected. Thanks!
Checked with Docker for Mac 18.06.0-ce-mac70 (26399).

**Comment by lmakarov** [comment]
@djs55 looks like this is not fully done. 

We are now getting the following error with Docker for Mac 18.06.0 when a container with a named volume and the `cached` flag cannot be recreated (e.g. any docker-compose configuration change). Here's the error:

```
Recreating drupal8_cli_1 ... error

ERROR: for drupal8_cli_1  Cannot start service cli: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/drupal8_project_root/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/6943a3faf71d8343605d386262051716639d48e15a49df27ca42bbed8a377274/merged\\\" at \\\"/var/lib/docker/overlay2/6943a3faf71d8343605d386262051716639d48e15a49df27ca42bbed8a377274/merged/var/www\\\" caused \\\"no such file or directory\\\"\"": unknown

ERROR: for cli  Cannot start service cli: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/drupal8_project_root/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/6943a3faf71d8343605d386262051716639d48e15a49df27ca42bbed8a377274/merged\\\" at \\\"/var/lib/docker/overlay2/6943a3faf71d8343605d386262051716639d48e15a49df27ca42bbed8a377274/merged/var/www\\\" caused \\\"no such file or directory\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

This only happened when the volume is defined as:

```
- project_root:/var/www:cached
```

The following two versions work without issues:

```
- project_root:/var/www
```

```
/host/path/to/project_root:/var/www:rw,cached
```
