### ISSUE TITLE
docker-entrypoint-initdb.d is ignored/skipped on docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by giginos** [docker/for-mac#190]
### Expected behavior
When starting via "docker-compose up" and not-existing DB (MySQL), Docker should mount local dir to /docker-entrypoint-initdb.d and import SQL-File from mounted, local dir. We use the "standard" mysql:5.7 docker-image for this.
NOTE: This does work with Docker Beta e.g. Version 1.12.0-rc2-beta17 (build: 9779)!

### Actual behavior
When starting docker via "docker-compose up" the step is skipped (I get a notice like "Skipping / Ignoreing docker-entrypoint-initdb.d"). No Database is imported so i have to do this manually.

### Information
  - Docker Version: 1.12.0 (build: 10871)
  - Diagnostic ID: F456E894-4499-4CD4-952E-B361387E5467
  - host distribution and version: (OSX 10.11.6 (15G31))

 **Sample-Start**
```
mysql:
  build: mysql/
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 1234
  volumes:
    - ./mysql/fixtures:/docker-entrypoint-initdb.d
```
 **Sample-End**

### Steps to reproduce the behavior

  1. Install Docker 1.12.0 (build: 10871) on Mac
  2. Try to install a mysql-image based on  mysql:5.7 with importing local mysql-file

**Comment by FrenchBen** [comment]
@giginos It looks like you're using a custom mysql image - I would look at that first. 
I did the following to try and replicate your issue:
```
$ mkdir -p mysql/fixtures
```
used a sample sakila db from: https://dev.mysql.com/doc/sakila/en/sakila-installation.html
```
$ cd mysql/fixtures && curl -sSLO https://mariadb.atlassian.net/secure/attachment/36318/sakila-schema.sql
```
Modified your docker-compose file to use the `mysql:5.7` image
```
mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 1234
  volumes:
    - ./mysql/fixtures:/docker-entrypoint-initdb.d
```

Output of `docker-compose up`:
```
$ docker-compose up
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
357ea8c3d80b: Already exists
256a92f57ae8: Pull complete
d5ee0325fe91: Pull complete
a15deb03758b: Pull complete
7b8a8ccc8d50: Pull complete
1a40eeae36e9: Pull complete
833539b56478: Pull complete
4f350efbb7e5: Pull complete
266f161e49c6: Pull complete
2d0f7f51c888: Pull complete
13b44531c4a7: Pull complete
Digest: sha256:e6dc999f4e2d5982e74a008ff08c0641f0832e19339aaf4f4c2bc2ca426e96c6
Status: Downloaded newer image for mysql:5.7
Creating test_mysql_1
Attaching to test_mysql_1
mysql_1  | Initializing database
mysql_1  | Database initialized
mysql_1  | MySQL init process in progress...
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  |
mysql_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/sakila-schema.sql
mysql_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1  |
mysql_1  |
mysql_1  |
mysql_1  | MySQL init process done. Ready for start up.
mysql_1  |
```

**Comment by giginos** [comment]
Hi @FrenchBen ,
thanks for your fast reply.

We use the image in our company and all employees with older docker versions have no problems - so another reason could be the update from beta to final version.

I'll remove docker itself and also recreate my docker-containers to test, if it does work in a clean environment.

If i'll still get the problem i'll reopen that issue.

BTW: Thanks for supporting this amazing software! Helps us a lot! :-)

Regards,
Rafael
