### ISSUE TITLE
Docker hangs and I cannot use it.

### ISSUE THREAD

**Issue by ruyrocha** [docker/for-mac#1900]
### Expected behavior
Docker starts properly and I can use it.

### Actual behavior
Docker starts BUT I cannot connect to it. This behavior started after last Sierra & Docker upgrades.

### Information

Fixed the issue this way:

```shell
➜  ~ docker ps
error during connect: Get https://192.168.99.101:2376/v1.30/containers/json: dial tcp 192.168.99.101:2376: connect: host is down
➜  ~ docker ps
^C
➜  ~ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64
error during connect: Get https://192.168.99.101:2376/v1.30/version: dial tcp 192.168.99.101:2376: connect: host is down
➜  ~ docker-machine env default
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate is valid for 192.168.99.101, not 192.168.99.100
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

➜  ~ docker-machine regenerate-certs default
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
➜  ~ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/ruyrocha/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $(docker-machine env default)
➜  ~ docker ps
^C
➜  ~ export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/ruyrocha/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
➜  ~ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜  ~
```

When you see the first `error during connect: Get https://192.168.99.101:2376/v1.30/containers/json: dial tcp 192.168.99.101:2376: connect: host is down`, I manually _quit_ Docker.

If I'm in the wrong place, please disregard this issue.

### Steps to reproduce the behavior

  1. Upgrade Docker to **17.06.0-ce**
  2. Upgrade Sierra to **10.12.6**
  3. After reboot, try to use Docker.

**Comment by 885783558** [comment]
I have the same problem, waiting for the official website to update

**Comment by jamshid** [comment]
I'm also having problems with Docker for Mac on latest Sierra, but @ruyrocha are you sure you're using Docker for Mac?

It seems you're using docker-machine which creates a VirtualBox docker, probably based on boot2docker.iso. That way of running a docker server is totally unrelated to this project, Docker for Mac which uses xhyve.

**Comment by retemaadi** [comment]
I also having the same issue, is it to possible to role back to previous version of Docker until the fix arrives?

**Comment by aquinofb** [comment]
Same issue after update to Mac **Sierra 10.12.6**. Any updates for this thread?
Docker version **17.06.0-ce**

**Comment by sslgeorge** [comment]
Same issue after installing xhyve

**Comment by aj07mm** [comment]
`docker-machine start <your-machine-name>`
