### ISSUE TITLE
Docker is not starting in Mac 

### ISSUE THREAD

**Issue by badtux** [docker/for-mac#1902]
### Expected behavior
When i turn my Mac on, the Whale should stop juggling containers and stay steady with green docker status light.  CLI should respond to commands. 

### Actual behavior
Running Version 17.06.0-ce-mac19 (18663) Channel: stable c98c1c25e0 on Mac OS Siera 10.12.5. the Whale keeps on juggling. Restart does not help. 

in syslog, it does show nothing beyond, Using protocol TwoThousand msize 8192

Jul 26 11:13:38 Anthonys-iMac com.docker.vmnetd[1673]: no path for address 0x11ae88000
Jul 26 11:13:38 Anthonys-iMac com.docker.vmnetd[1681]: no path for address 0x11ae88000
Jul 26 11:13:39 Anthonys-iMac Docker[1690]: Logging to Apple System Log
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Logging to Apple System Log
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Setting handler to ignore all SIGPIPE signals
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: vpnkit version befe8be9b45f6c4d50cf7c8105bfdf101dfe8982 with hostnet version   uwt version 0.2.0 hvsock version 0.13.0 
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: System SOMAXCONN is 128
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Will use a listen backlog of 32
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: starting port forwarding server on port_control_url:fd:4 vsock_path:/Users/virajabayarathna/Library/Containers/com.docker.docker/Data/connect
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: DNS names  will map to local IP 192.168.65.1
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: 2 upstream DNS servers are configured
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: attempting to reconnect to database
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Add(2): DNS configuration changed to: use upstream DNS servers nameserver 8.8.8.8#53
	order 0
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: reconnected transport layer
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: hosts file has bindings for <removed-host-entries>
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: updating connection limit to 900
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: allowing binds to any IP addresses
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: updating resolvers to use upstream DNS servers nameserver 8.8.8.8#53
	timeout 2000
	order 200000
	nameserver 0.0.0.0#53
	timeout 2000
	order 200000
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Add(3): DNS configuration changed to: use upstream DNS servers nameserver 8.8.8.8#53
	timeout 2000
	order 200000
	nameserver 0.0.0.0#53
	timeout 2000
	order 200000
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: DNS names docker.for.mac.localhost will map to local IP 192.168.65.1
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: 2 upstream DNS servers are configured
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: updating resolvers to use host resolver
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Remove(3): DNS configuration changed to: use upstream DNS servers nameserver 8.8.8.8#53
	order 0
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Add(3): DNS configuration changed to: use host resolver
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: DNS names docker.for.mac.localhost will map to local IP 192.168.65.1
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Will use the host's DNS resolver
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Disabling transparent HTTP redirection
Jul 26 11:13:40 Anthonys-iMac Docker[1691]: Creating slirp server peer_ip:192.168.65.2 local_ip:192.168.65.1 domain_search: mtu:1500 bridge:true
Jul 26 11:13:43 Anthonys-iMac com.apple.xpc.launchd[1] (com.apple.quicklook[1694]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: PPP.negotiate: received { magic = VMN3T; version = 1; commit = 272951d647566a657ee63b2e8da309b176dfe129 }
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: PPP.negotiate: received Ethernet c800df6c-95fd-49ba-9651-c8660c19902b
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: PPP.negotiate: sending { mtu = 1500; max_packet_size = 1550; client_macaddr = 02:50:00:00:00:01 }
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: Client mac: 02:50:00:00:00:01 server mac: f6:16:36:bc:f9:c6
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: TCP/IP ready
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: stack connected
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: starting introspection server on: fd:5
Jul 26 11:13:48 Anthonys-iMac Docker[1691]: starting diagnostics server on: fd:6
Jul 26 11:14:00 Anthonys-iMac Docker[1691]: BOOTREQUEST from 02:50:00:00:00:01
Jul 26 11:14:00 Anthonys-iMac Docker[1691]: BOOTREPLY to 02:50:00:00:00:01 yiddr 192.168.65.2 siddr 192.168.65.1 dns 192.168.65.1 router 192.168.65.1 domain unknown
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /private
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /tmp
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Volumes
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: transfused: mount /bin/fusermount -o allow_other,max_read=1048576,subtype=osxfs /Users
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: Negotiated transfuse notification channel for /private
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: Negotiated transfuse notification channel for /tmp
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: Negotiated transfuse notification channel for /Volumes
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: Negotiated transfuse notification channel for /Users
Jul 26 11:14:01 Anthonys-iMac Docker[1690]: sending continue to client
Jul 26 11:14:02 Anthonys-iMac Docker[1691]: Using protocol TwoThousand msize 8192

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/784B5DD4-1E19-443B-A7FF-21D2B8D42F3F/20170726-115321.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

This happens every time i start. I suspect this is after i updating to a minor version last night.

Reset is not an option as i'm trying to save my containers which are with config settings (i have not taken any backups recently!!)

**Comment by dsheets** [comment]
The docker engine appears to have panicked:

```
Jul 26 06:22:20 moby root: time="2017-07-26T06:22:20.584912527Z" level=debug msg="Network (fc2ed73) not found for restored bridge endpoint (764d3a4)"  
Jul 26 06:22:20 moby root: time="2017-07-26T06:22:20.585005023Z" level=debug msg="Deleting stale bridge endpoint (764d3a4) from store"  
Jul 26 06:22:20 moby root: panic: invalid childAt(1) on a leaf node 
Jul 26 06:22:20 moby root: goroutine 1 [running]: 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).childAt(0xc4202f5ab0, 0x1, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:75 +0x142 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).nextSibling(0xc4202f5ab0, 0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:100 +0x7c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).rebalance(0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:466 +0x16a 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).rebalance(0xc4202f5ab0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:507 +0x3f2 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).rebalance(0xc420431bc0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:636 +0x97 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).rebalance(0xc4200127f8) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:639 +0x114 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4200127e0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/tx.go:156 +0xd9 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4202db680, 0xc4204ea3f0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:602 +0xf7 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicDelete(0xc420257090, 0xc4202f5880, 0x65, 0xc420232f30, 0x0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:345 +0x19c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic(0xc4204317c0, 0x27123a0, 0xc420266aa0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:623 +0x25c 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).storeDelete(0xc420100dc0, 0x27123a0, 0xc420266aa0, 0x1, 0x1) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:120 +0x65 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateEndpoints(0xc420100dc0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:87 +0x426 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0xc420100dc0, 0xc420103cb0, 0x0, 0xc4202a9350) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:40 +0x245 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0xc420100dc0, 0xc420103cb0, 0xc420103d10, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:417 +0x1ce 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x26f9e20, 0xc420118600, 0xc420103cb0, 0x0, 0xffffffffffffffff) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:151 +0xe2 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(0xc420118600, 0x1a9fba1, 0x6, 0x1b29978, 0xc420103cb0, 0xc4201095e0, 0xc4204eaad0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72 +0x46 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc420118500, 0x8, 0x8, 0xc42043f020, 0xc4202956e0, 0xc420118500, 0x8) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:208 +0x570 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc4204bc000, 0xc420375680, 0xc4202956e0, 0xc4204bc000, 0xc420272a00, 0xc4202956e0, 0xc4202956b0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon_unix.go:736 +0xa7 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.(*Daemon).restore(0xc4204bc000, 0x26ee320, 0xc4204bc000) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:288 +0x777 
Jul 26 06:22:20 moby root: github.com/docker/docker/daemon.NewDaemon(0xc420375680, 0x2713020, 0xc420439d90, 0x26ff520, 0xc42043ba00, 0xc42043f020, 0x0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/daemon/daemon.go:747 +0x2116 
Jul 26 06:22:20 moby root: main.(*DaemonCli).start(0xc42043e450, 0x0, 0x1ac1337, 0x17, 0xc420375200, 0xc420430e40, 0xc4200113b0, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:214 +0x1223 
Jul 26 06:22:20 moby root: main.runDaemon(0x0, 0x1ac1337, 0x17, 0xc420375200, 0xc420430e40, 0xc4200113b0, 0x8, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x8c 
Jul 26 06:22:20 moby root: main.newDaemonCommand.func1(0xc42033dd40, 0xc4203a1900, 0x0, 0x8, 0x0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc42033dd40, 0xc4200100a0, 0x8, 0x8, 0xc42033dd40, 0xc4200100a0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42033dd40, 0x186de40, 0x1, 0xc420438cb0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349 
Jul 26 06:22:20 moby root: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42033dd40, 0xc420438cb0, 0x0) 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b 
Jul 26 06:22:20 moby root: main.main() 
Jul 26 06:22:20 moby root: ^I/go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0xe6 
```

We're investigating. Thanks for your report!

**Comment by dsheets** [comment]
I've escalated this issue to moby/moby#34256.
