### ISSUE TITLE
Can't start docker after following the install networking components instruction

### ISSUE THREAD

**Issue by evenhumble** [docker/for-mac#1903]
### Expected behavior
start docker successfully

### Actual behavior
can't start docker. When try to start docker, it said: need to install network component but can't install successfully.

### Information
diagnostic logs:

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.5 (build: 16F73)
logs: /tmp/BF6A0274-00AF-44F7-AFE6-22DF7194237D/20170726-143854.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/patrick/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/patrick/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/patrick/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         /Users/patrick/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/patrick/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. download latest docker for mac, install it
  2. start docker from application
  3. a message pops up:
```
Docker needs privileged access.
Docker for Mac needs privileged access to install its networking components and links to the Docker apps.

You will be asked for your password.
```
4. click OK, and input the root user password for toolhelper
5. After a while, then get the Fatal Error message:
```
Communication with networking components failed.
```

**Comment by stevenodb** [comment]
+1

I'm having the same issue. 
- The "Docker needs privileged access" dialog appears after starting Docker for the first time.
- I hit OK.
- I input my password in the toolhelper privilege escalation prompt.
- The Add Helper prompt disappears.
- The "Docker needs privileged access" dialog remains on screen.
- repeat, until you press exit, then Docker quits.

**Comment by mrichman** [comment]
Same issue, even on Docker Edge.

**Comment by jrolfs** [comment]
Thanks @mrichman that worked for me in a pinch. When I have time I'm going to go back and try to determine what exactly was causing the issue. I have a feeling it may have just been permissions on the **launchd** `plist`.

**Comment by Zenexer** [comment]
Having this issue; request to reopen.

**Comment by JKair** [comment]
@stevenodb +1 and you can run it now?

**Comment by stevenodb** [comment]
I don't remember what I did exactly, but it involved manually removing every trace of Docker on my system. After which the installer worked.

**Comment by JKair** [comment]
I try to remove it again and it work,[remove](https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/)

**Comment by Zenexer** [comment]
Docker should automatically detect this and provide you with instructions for a workaround per #3035.  I don't know if it's made it into a stable release yet.  If anyone else is looking for the instructions, they're in that issue.

**Comment by yufengyuanx** [comment]
I got same issue, and I tried update my mac system, reinstall docker, etc., but not work.
Then I tried this way and it works now, but Idk why.
Open terminal

`cd /Applications/Docker.app/Contents/MacOS && ./Docker`

I hope this one can help you guys, good luck

**Comment by JoostK** [comment]
I had the same issue after updating from El Capitan (10.11) to Mojave (10.14), with neither of the above suggestions working. The console was full of errors:

```
error	19:10:34.774315 +0200	authd	Unable to get details for right @\M- +\^G\^A
error	19:10:34.775581 +0200	authd	Fatal: authorization denied (DW) (engine 241)
```

After force quitting `authd` Docker was able to start again, showing a helpful dialog of Terminal commands to execute. After having done so, everything is back to normal again.

**Comment by davidgilbertson** [comment]
@JoostK I had tried everything in all the other issues and force quitting authd is the one that worked for me. Thanks!

**Comment by DNXie** [comment]
having the same issue. It does not show anything after pressing OK repeatedly

**Comment by texpert** [comment]
Found that the com.docker.vmnetd was missing in /Library/PrivilegedHelperTools

So, after adding to @mrichman 's list of commands, the following, everything went smooth:

`sudo cp $(mdfind Docker.app)/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools/com.docker.vmnetd`

**Comment by tuananhpham2008** [comment]
> @JoostK I had tried everything in all the other issues and force quitting authd is the one that worked for me. Thanks!

how to quit force authd ? please , tks u
