### ISSUE TITLE
db.git          db.git check failed 

### ISSUE THREAD

**Issue by aparvar** [docker/for-mac#1905]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ... run hello_world from command line 
  2. ... get permission  error 
  3 .... run dignastic and here is the result 

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/AADF6356-7C06-41C2-ABD0-0BDA85AF9B6B/20170726-163652.tar.gz
[ERROR]  db.git
         db.git check failed with: (Failure
  "exec: cd \"/tmp/AADF6356-7C06-41C2-ABD0-0BDA85AF9B6B/20170726-163652/database\" && git checkout master: exit 1")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by morgankevinj** [comment]
Open a terminal and see if you can run git. If you get this error "xcrun: error: invalid active developer path" then you need to install xcode by running "sudo xcode-select --install" in the terminal.

**Comment by pgayvallet** [comment]
No reply from author for a long time.

Closing, please reopen if still present.
