### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io

### ISSUE THREAD

**Issue by vernonstinebaker** [docker/for-mac#1906]
### Expected behavior

docker pull alpine 

results in alpine:latest being pulled down

### Actual behavior

docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:55651->192.168.65.1:53: i/o timeout

### Information

Docker for Mac: version: 17.06.1-ce-rc1-mac20 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A315i)
logs: /tmp/8EE46382-7643-4D36-B611-0D0C4D9DD1F4/20170727-213209.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Type in "docker pull alpine" (or any other pull)

Same problem on a MacBook running the current non-Beta version of macOS. 

In the forums I saw someone commenting about uninstalling and reinstalling. I did that on the MacBook and got the same results.

I also saw another forum entry about stopping Docker, turning off WiFi, restarting Docker and then restarting WiFi. I tried this and it also didn't make a difference.

I checked http://status.docker.com and it shows "All Systems Operational".

### Diagnostic ID

8EE46382-7643-4D36-B611-0D0C4D9DD1F4

**Comment by alexei-led** [comment]
I'm experiencing the same issue: "cannot pull image"
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)

Adding DNS (8.8.8.8/4) to Docker VM `/etc/resolv.conf` fixes (partially - not working with multi-stage build) issue till report
**Diagnostic ID: 448D78B5-FDF6-4CD8-8C38-D8C13A88FB15**

**Comment by vernonstinebaker** [comment]
Adding the Google DNS isn't an option for me. I'm in China most of the time, and Google properties are blocked. Things used to work fine. Hopefully any resolution will bring things back to that working state. I also hope that some automated regression testing for this issue might be instituted. As I searched the forum this isn't the first time the problem has manifested or, apparently, been resolved.

**Comment by beeradb** [comment]
I had this issue as well. I was able to gain a shell to the xhyve host via the following command:

`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`

From there I was able to edit the `/etc/resolv.conf` file to update the nameserver. This fixed the issue for me.

**Comment by alexei-led** [comment]
In my case, it was my fault. 
I tried to setup transparent connection to K8s (minikube) using `/Library/Preferences/com.apple.mDNSResponder.plist AlwaysAppendSearchDomains -bool YES` and custom DNS resolvers. As described in https://stevesloka.com/2017/05/19/access-minikube-services-from-host/.
Docker for Mac does not work if you have additional DNS resolvers and DNS servers from these resolvers are not running (for example `minikube` instance stopped).

**Comment by tadeoos** [comment]
I am experiencing the same issue, my diagnostic id is 5097A63C-66C6-48D0-B012-8AB17609C1E6.
Tried copule of fixes mentioned [here](https://github.com/moby/moby/issues/32270#issuecomment-290829987) but none of them worked, unfortunately.

**Comment by konsalex** [comment]
Any workarounds yet? I have the same problem . Cannot even pull hello world.

**Comment by sankarcule** [comment]
Facing the same issue. Diagnostic id: ADC9DB8C-DEDC-46E4-8453-7FE92311B590

**Comment by tadeoos** [comment]
Hey guys, I know how it sounds, but have you tried restarting your machine? :D 
My problem just went away after some time. I can't remember exactly if the restart did it or a bit of patience. Good luck!

**Comment by waleCloud** [comment]
Help with docker for Ubuntu 16.04 having the below error:

Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: read udp 127.0.0.1:41613->127.0.1.1:53: i/o timeout

**Comment by vhosakot** [comment]
I saw the same error too when I ran `docker build -t hello-node:v1 .` in the tutorial https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/#create-a-docker-container-image on Mac OS X Sierra (`10.12.6`), Docker version `17.12.0-ce`, minikube version `v0.25.0`, xhyve version `0.2.0` and kubernetes version `v1.9.0`:

```
$ docker build -t hello-node:v1 .
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM node:6.9.2
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.3:37095->192.168.64.1:53: read: connection refused
```

Switching to **virtualbox**  fixed this issue for me.

I stopped minikube, deleted it, started it without `--vm-driver=xhyve` (minikube uses virtualbox driver by default), and then `docker build -t hello-node:v1 .` worked fine without errors:

```
minikube stop
eval $(minikube docker-env -u)
minikube delete

minikube start (without --vm-driver=xhyve)

eval $(minikube docker-env)
docker build -t hello-node:v1 .

$ docker images | grep hello
hello-node                                    v1                  9cc51aa82a30        39 seconds ago      655MB
```

I do see the `kube-dns` pod running:

```
$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube             1/1       Running   0          1m
kube-system   kube-dns-54cccfbdf8-vmvjm               3/3       Running   0          1m
kube-system   kubernetes-dashboard-77d8b98585-5mbcf   1/1       Running   0          1m
kube-system   storage-provisioner                     1/1       Running   0          1m
```

This issue does look like an `xhyve` issue not seen with virtualbox. My virtualbox version is `5.2.6r120293`:

```
$ VBoxManage --version
5.2.6r120293
```

**Comment by javajon** [comment]
With Windows 10 + VirtualBox 5.2.8 + Minikube 0.25.2 I was pulling images from DockerHub without error.  Suddenly, for some undetermined reason, images stopped pulling with this message:

> Failed to pull image "jenkins/jenkins:2.113-alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:56815->10.0.2.3:53: i/o timeout

A simple minikube stop and start resolved the issue.

**Comment by curtistee** [comment]
VPNs can cause no end of havoc working with Minikube (I'm on a Mac). For work, my Maven repo requires I'm on their VPN to pull deps when building. Minikube & its Docker implementation definitely do _not_ like that. Under these circumstances I need to build with the work VPN running (assuming deps need to be downloaded), shut down the VPN, bounce Minikube & "re-eval" Minikube's docker-env. 

HTH

**Comment by YRM64** [comment]
Developers, for those still experiencing error responses from daemon, try a couple troubleshooting techniques, one at a time.

Try removing firewall, or adding exceptions to it.
Try disabling experimental features, and then restart Docker.
Restarting Docker.
Restarting the Docker Daemon.
Creating an account at the Docker Hub.
Logging into Docker from Shell, insert username and password.
Try invoking - Web Request: https://registry-1.docker.io/v2/ from Powershell
Try changing DNS (Google, open dns & others); that is of course if you don't spend a lot of time in 
   China 😆

**Comment by michaelhou** [comment]
In China, Add 114.114.114.114 to resolv.conf fixed it.
`sudo echo "nameserver 114.114.114.114" >> /etc/resolv.conf`

**Comment by ccu-de** [comment]
possible VPN or limited network traffic issue.
