### ISSUE TITLE
Some problems in host network packet forwarding

### ISSUE THREAD

**Issue by naiba** [docker/for-mac#1908]
### My laptop
- osx 10.12.5
- docker-ce last version
### Trouble shooting
My contribution is [stacker](http://github.com/maxlab/stacker), which has a **dnsmasq** container and a **web** container.When a DNS request in the web container is forwarded to the dnsmasq container by the host, there is a problem.
### Reproduction
1. Clone stacker
    ```sh
    $git clone https://github.com/naiwa/stacker.git
    $cd stacker&&cp .env.dist .env
    ```
2. Modify some files for debugging
    **docker-compose.yml** : remove dns option.
    ```sh
    php7console:
        env_file: .env
        build:
            args:
                - TZ=${TZ}
            context: ./conf/php7console 
        container_name: php7console 
        image: maxlab/php7console
        restart: always        
        volumes_from:
            - php7xdebug 
        tty: true
    ```
    **conf/dnsmasq/dnsmasq.conf** : enable log output , do not delete the blank lines of the tail.
    ```sh
    no-hosts
    no-resolv
    strict-order
    log-queries
    log-facility=/dev/stdout

    address=/.dev/127.0.0.1

    all-servers

    ```
2. Build stacker
    you have to add **stacker/bin** to your PATH.
    ```sh
    $stacker build&&stacker up
    ```
    **!!important!!** then , set your local dns to 127.0.0.1.
3. Use of Wireshark capture &&view dnsmasq's log
    set `dns` in filter
    ```sh
    $stacker logs -f dnsmasq
    ```
3. Make a DNS request
    ```sh
    $stacker console
    $ping google.com
    ```
3. End
As you can see, a large number of DNS requests have been generated and corresponding, but the container did not get any results. At the same time, the dnsmasq container cannot respond to other requests.

**Comment by naiwa** [comment]
hello?

**Comment by naiwa** [comment]
hello？

**Comment by jamshid** [comment]
IDK hopefully someone from Docker responds, but I think I've noticed Docker for Mac has problems if you change your local macOS DNS to use a dnsmasq running in a container. Maybe changing your Mac's DNS causes Docker for Mac to reset _its_ DNS, and it doesn't handle that correctly when the DNS server is in a container?

**Comment by naiwa** [comment]
@jamshid yes, DNS server is in a container, and the other container can not get a successful DNS response from it.

**Comment by naiwa** [comment]
any body?

**Comment by naiwa** [comment]
lol

**Comment by naiwa** [comment]
balabala

**Comment by naiwa** [comment]
What !!

**Comment by jamshid** [comment]
FWIW I'm using Version 17.07.0-ce-mac26 (19053) and setting macOS Network => Advanced => DNS to `127.0.0.1` works when I have a dnsmasq container running, publishing port 53:
```
    ports:
      - "53:53/tcp"
      - "53:53/udp"
```
But I had to hardcode Docker for Mac DNS to 8.8.8.8 in Daemon, Advanced.
```
 "dns" : [
    "8.8.8.8"
  ],
```
I believe this is required because otherwise D4M tries to reset its networking and root DNS when you change the macOS DNS, and it gets confused when that DNS is itself a container.
PS: Ideally I could use a container publishing to an arbitrary port, but I couldn't figure out how to make macOS (Sierra) use a DNS server on a non-standard port.

**Comment by naiba** [comment]
@jamshid use container ping `docker.for.mac.localhost`, It's not work. thanks.

**Comment by jamshid** [comment]
I also noticed that documented (experimental?) hostname does not work, but I'm not relying on it for my DNS solution.

**Comment by naiba** [comment]
@jamshid If container used a custom DNS server, then it no longer connects to the host host (for example, using the host's MySQL service). But to use a container as a DNS server, you must also use the custom DNS for the container. Isn't that a problem?
