### ISSUE TITLE
Docker for Mac is increasing unstable, 3rd uninstall in 3 weeks

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#1909]
### Expected behavior
Docker for Mac is usable and more stable with each release. If a macOS update breaks docker, hopefully it's identified by someone testing macOS betas so that a for-mac fix is available immediately.

Rant: c'mon folks, this project is many users first introduction to Docker. Its growing instability and slowing fixes seriously turns people off on the technology and shuts down efforts to promote use of Docker within a company. 

### Actual behavior
This is the third time I'm having to uninstall and reinstall Docker for Mac in three weeks. I did upgrade macOS to latest Sierra patch a day ago, but docker _was_ working after that for a while.

### Information

```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/581CDA20-C738-4D01-BE16-26480E1FCB1A/20170728-112017.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```
### Steps to reproduce the behavior

  1. idk hopefully you can identify the problem from the diagnostics. My docker for mac just seems to get into a bad unrecoverable state. I don't see any logging or error messages to help diagnose the spinning toolbar icon.

**Comment by jamshid** [comment]
Again I have to do a full reset. Can anyone identify the cause of my hung startup below? Are these issues fixed in any available beta? Edge release notes show nothing since 2017-06-28 over a month ago.
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/D045F1B2-4CA9-43D2-B259-BAA97AE21A4C/20170807-113357.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by vovimayhem** [comment]
Have you tried resetting to factory defaults?
<img width="380" alt="screen shot 2017-08-07 at 2 41 08 pm" src="https://user-images.githubusercontent.com/1915931/29042900-90d476a0-7b7e-11e7-8845-847f2d54f448.png">

I've never had a problem updating my macOS.

**Comment by jamshid** [comment]
> Have you tried resetting to factory defaults?

Yes, that's what I meant by "Again I have to do a full reset." 

I'm now on Edge -  Version 17.07.0-ce-rc4-mac25 (18986) and it seems to be more stable, so closing this. And looks like a new version just came out today, so will use that too.
