### ISSUE TITLE
Report of CPU incompatibility

### ISSUE THREAD

**Issue by kow-k** [docker/for-mac#1911]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Startup Docker on MacBook Pro 2009

*************************

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/44B81819-7CF2-4244-91F4-4D178C5C2D7F/20170729-154606.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/kowk/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/kowk/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/kowk/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/kowk/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/kowk/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/kowk/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/kowk/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by deepio** [comment]
Same issue #1938 #1911 #1871 - Intel® Xeon® Processors E5520. 
I can run docker inside a VM, but at that point I might as well use the VM... 

> Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
> macOS: version 10.11.6 (build: 15G1010)
> logs: /tmp/D4FC797F-CCC5-4409-ADD6-201A3D7B46A0/20170817-184216.tar.gz
> failure: sysctl -a reports no hypervisor support
> [OK]     db.git
> [ERROR]  vmnetd
>          /var/tmp/com.docker.vmnetd.socket does not exist
>          Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
>          /private/tmp/vmnetd/com.docker.vmnetd is not running
> [OK]     dns
> [ERROR]  driver.amd64-linux
>          com.docker.driver.amd64-linux is not running
> [OK]     virtualization VT-X
> [OK]     app
> [ERROR]  moby
>          /Users/alex/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
> [OK]     system
> [OK]     moby-syslog
> [ERROR]  db
>          /Users/alex/Library/Containers/com.docker.docker/Data/s40 does not exist
>          Unexpected error (No such file or directory) connecting to /Users/alex/Library/Containers/com.docker.docker/Data/s40
>          com.docker.db is not running
> [OK]     env
> [ERROR]  virtualization kern.hv_support
>          sysctl -a reports no hypervisor support
> [ERROR]  slirp
>          Unexpected error ((Failure
>   "Error connecting socket to 9p endpoint unix:/Users/alex/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/alex/Library/Containers/com.docker.docker/Data/s51
>          com.docker.vpnkit is not running
>          slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
> [ERROR]  osxfs
>          com.docker.osxfs is not running
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          /var/run/docker.sock does not exist
>          Unexpected error (No such file or directory) connecting to /var/run/docker.sock
>          /Users/alex/Library/Containers/com.docker.docker/Data/s60 does not exist
>          Unexpected error (No such file or directory) connecting to /Users/alex/Library/Containers/com.docker.docker/Data/s60
>          docker ps failed
> [OK]     menubar
> [ERROR]  disk
>          Docker.qcow2 missing: the VM has never been started
>

**Comment by SangheeKim** [comment]
The Hypervisor Framework generally supports machines with the Intel VT-x feature set including Extended Page Tables (EPT) and **Unlimited Mode.**
CPU i7 2.93 GHz and i5 2.80 do not work on iMac 2010 mid. 
That's because the CPU does not support Unlimited Mode.

**Comment by djkinkle** [comment]
So in this case, does that mean people who have this set up and problem are just out of luck. It won't run at all?

**Comment by deepio** [comment]
@djkinkle Not true, what you do instead is use docker toolkit. 

https://docs.docker.com/toolbox/toolbox_install_mac/

**Comment by djkinkle** [comment]
@deepio you're the best. thanks

**Comment by deepio** [comment]
Any issue with docker toolbox should be on that repository.
Someone with the authority to do so should close these issues.

__Solution__:
- People running with these processors need to run docker toolbox instead of docker.
