### ISSUE TITLE
Spinlock in d4mac

### ISSUE THREAD

**Issue by cpuguy83** [docker/for-mac#1912]
### Expected behavior
d4mac doesn't spinlock randomly.

### Actual behavior
d4mac appears to be spinlocked in some way.
"hyperkit" is using 100% CPU, dockerd is inaccessible for anything (even `docker version`).

I wasn't even using it... there may have been a container (deb:jessie) running bash and nothing else that was running before I put the laptop to bed last night.
I only noticed because I was on my laptop and it was hot for no good reason, so I checked activity monitor and saw hyperkit pegged at 100%:

<img width="881" alt="screen shot 2017-07-29 at 10 31 59 am" src="https://user-images.githubusercontent.com/799078/28745588-2e93eade-7449-11e7-84c3-44dd53ac0821.png">

It has stayed consistently at 102%, without wavering.

### Information
```
Docker for Mac: version: 17.06.0-ce-mac17 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/2D788FFC-5A9A-47B5-94BE-554E76FBEE15/20170729-102350.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

???

**Comment by akimd** [comment]
Not observed in ages, probably fixed now.
