### ISSUE TITLE
Docker Fails to start on macOS High Sierra 17A315i

### ISSUE THREAD

**Issue by SConaway** [docker/for-mac#1913]
### Expected behavior
Docker starts at boot **even when** 'Start Docker when you log in' is ticked.
### Actual behavior
Docker **does not** start at boot when 'Start Docker when you log in' is ticked.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install Docker for mac
  2. Reboot computer

Full Output of `Diagnose & Feedback`:

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A315i)
logs: /tmp/423332C8-CDC9-4D46-9498-E566A87793E7/20170729-094543.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Diagnostic ID:

423332C8-CDC9-4D46-9498-E566A87793E7

**Comment by shouze** [comment]
I also have High Sierra `17A315i` and I don't reproduce.

**Comment by SConaway** [comment]
Ok That was weird. For the past few days nothing but macOS started at boot, but now it all starts.
