### ISSUE TITLE
Crash on laptop resume with 17.07.0-ce-rc1-mac21

### ISSUE THREAD

**Issue by shouze** [docker/for-mac#1920]
### Expected behavior

Docker exited when I unlock my laptop after some time of hibernation/inactivity.

### Actual behavior

Docker should not exit/crash.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Diagnostic ID: 39A10146-9070-480D-B7D0-E97B30D3F106

Docker for Mac: version: 17.07.0-ce-rc1-mac21 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A315i)
logs: /tmp/39A10146-9070-480D-B7D0-E97B30D3F106/20170731-201209.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/shouze/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/shouze/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/shouze/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/shouze/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/shouze/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

1. Close my laptop screen.
2. Open up my laptop screen & unlock my user session.

**Comment by jamshid** [comment]
Curious, how do you get 17.07? Latest Docker for Mac Edge is 17.06.0-ce-mac17 on  2017-06-28
https://docs.docker.com/docker-for-mac/release-notes/#edge-release-notes

**Comment by shouze** [comment]
It was till few hours

**Comment by shouze** [comment]
I got an automatic update
