### ISSUE TITLE
Docker crashes after few seconds of starting 

### ISSUE THREAD

**Issue by beingkaran** [docker/for-mac#1923]
### Information

Diagnostic ID: BB49A37B-87EF-4698-A18C-F4A404BD9EE7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.6 (Build 16G29)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Hello, please install a newer version of Docker for Mac. The version you are running, 1.12.0-a, is very old and is not compatible with macOS 10.12. Thanks!
