### ISSUE TITLE
17.07.0-ce-rc1-mac21 resets computing resources to default

### ISSUE THREAD

**Issue by kinghuang** [docker/for-mac#1926]
### Description

I'm on the edge releases and was prompted to upgrade to Docker for Mac 17.07.0-ce-rc1-mac21 (18848). After upgrading, the computing resources assigned to Docker for Mac was reset to 2 CPUs and 2 GB RAM.

### Expected behavior

The previously set values (4 CPUs and 12 GB RAM in my case) should be maintained.

### Actual behavior

The values for CPUs and Memory were reset to their default values.

### Information

```
Docker for Mac: version: 17.07.0-ce-rc1-mac21 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/33E6F7AB-801E-4FF4-B4F9-DA98039B05F7/20170801-134416.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. From Docker for Mac 17.06.0, upgrade to Docker for Mac 17.07.0-ce-rc1-mac21 (18848).

**Comment by akalipetis** [comment]
This actually happens for all the settings, like Docker ID, proxy configuration, etc.
