### ISSUE TITLE
docker won't start

### ISSUE THREAD

**Issue by alljoynsville** [docker/for-mac#1928]
Diagnostic ID : A92928BF-B0F7-4E87-B514-E93288AED93A

it started by freezing docker apps while I work, so I rebooted my mac and now docker wont start...

**Comment by tanadeau** [comment]
I'm seeing this too after updating to the latest edge release.

**Comment by alljoynsville** [comment]
im looking at: ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring 
last message is:
* Configuring host block device ...boot2docker-data: recovering journal

another potential problem:
size of Docker.qcow2 is: 158,947,344,384 - this is big! is this ok?
