### ISSUE TITLE
Storage-driver specification NOT accepted anymore

### ISSUE THREAD

**Issue by zrml** [docker/for-mac#1933]
I'd expect to be able to change the storage-driver

The new Version 17.07.0-ce-rc1-mac21 (18848) just installed says I cannot specify a storage-driver and this is terrible as the default overlayFS has issues and when starting the DB it cannot open the DB files and it locks up.

We have too many developers working on Mac & Windows and this feature is of paramount importance lest leave Docker behind.

I hope it is just a "feature" of the edge channel. I'll now have to go back and install the default.

**Comment by djs55** [comment]
Thanks for your report -- could you describe your overlay2 issue in more detail? Do you know if it has been filed elsewhere? Do you have any repro steps that I could try?

**Comment by ebriney** [comment]
Ok ,I'll change this validation. You can manually edit `~/.docker/daemon.json` for now.

**Comment by djs55** [comment]
@zrml At the moment we're planning which storage drivers to officially support in future stable versions. In particular we'd like to remove the AUFS driver if we can. If you are using AUFS because of `overlay2` bugs, could you share a repro case that demonstrates problems with `overlay2`? If we can reproduce the problems in-house we should be able to fix them or provide a suitable workaround.

**Comment by zrml** [comment]
Sorry I'm late on this one. Just got back from a long flight from Australia.
There is an issue with the way overlay FS and overlay2 FS handle files in the lower layers.
When we start the DB instance it cannot open the DBs files. A simple workaround is to touch the files we need to open but, IMHO it's just unacceptable as it slows the container startup time. 

-the workaround that is implemented over the original executable.
https://github.com/zrml/ccontainermain/blob/master/dockerfile/Cach%C3%A9%2BSSH/ccontrol-wrapper.sh
-the dockerfile (see like 55)
https://github.com/zrml/ccontainermain/blob/master/dockerfile/Cach%C3%A9%2BSSH/Dockerfile

Let me check if I can get the right bug for you.
I think you should allow people to chose the storage driver. In general people don't play with it unless they need it (on a client like mac or Windows) while in production is a different story and one looks for performance & stability.

Thanks guys

**Comment by zrml** [comment]
OK found it.
Please see the un-posix overlay FS behaviour.  It has to do with file descriptors that point to different files when open a file on what is an expected coding practise.
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#image-and-container-layers-on-disk

yum and many other tools & software solution -I suspect, are effected.

Issues like this one
https://github.com/moby/moby/issues/10180
are closed incorrectly IMO as the known issue is described above as a known fallacy but all we are left with is a the touch dirty workaround.

Thank you

**Comment by friism** [comment]
cc @thaJeztah @aluzzardi

**Comment by zrml** [comment]
FWIW even for the EE version AUFS is supported on Ubuntu. In general I'd say it's not a bad drive
https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/
Grazie Andrea :)

**Comment by pgayvallet** [comment]
@friism @djs55 can i close that ?

**Comment by djs55** [comment]
I think the storage driver validation has been fixed so this issue can be closed. Thanks for your report! Feel free to open another issue if you have further problems!

**Comment by zrml** [comment]
@djs55 Thanks for this. Does this mean that you guys settled on the fact that we can specify a storage driver vs you hardcoding only 1 specific one? Thank you

**Comment by zrml** [comment]
So it finally appears that you've decided to remove support for AUFS despite the non-POSIX behavior of overlay (as per your documentation)...

**Comment by zrml** [comment]
@djs55 Understood for Linux platforms but Mac and Win? Anyway, we're looking at reviewing our "opening".
@thaJeztah sure. Completely understand that. We are opening config files and libs and the layering system can be a pain as observed in your doc on overlay non-compliant POSIX.
Maybe you should push hard with the overlay team to abide to the standard.
Anyway, Thanks for answering.
