### ISSUE TITLE
Docker container has unexpected directory structure

### ISSUE THREAD

**Issue by vistradi** [docker/for-mac#1934]
I am experiencing a strange behaviour using Docker for Mac:

1. I downloaded and ran a docker image A on an Ubuntu 16.04 machine with Docker 17.03.1-ce installed on it. When I examine the directory structure of the resulting container, everything is ok.

2. I downloaded and ran the same docker image A on my personal Mac (MacOS Sierra 10.12.5 with Docker for Mac 17.06.0-ce installed on it). When I examine the directory structure of the resulting container, it does not match the expected directory structure of the container running on the Ubuntu 16.04 machine (see point 1 above). In fact, some files have been placed directly under the root directory ("/") instead of being placed under the right sub folders. As a result, my application does not start because these files are "missing" (more precisely, the files do not exist at the expected location).

Many of the files on the screenshot below should be placed in application sub folders, but they are placed on the root folder.
 
<img width="793" alt="screen shot 2017-08-04 at 12 00 52" src="https://user-images.githubusercontent.com/13589167/28964344-aa885126-790c-11e7-87f4-8a1dd160668d.png">

### Extra info:

- I used the same docker command to run the containers on both machines. This command did not contain any extra options (ie, no volume was mounted).
- The image I ran is a custom image with a "Red Hat Enterprise Linux Server 7.3" operating system and JBoss running on it. This image was built on Docker 1.10.3.

Stackoverflow post: https://stackoverflow.com/questions/45484210/docker-container-has-unexpected-directory-structure.

Can someone help me with this issue? Any help would be much appreciated.

**Comment by dsheets** [comment]
This is a bug in 17.06.0 tracked by moby/moby#29360 due to a bug introduced in Go's standard library recently. It should be fixed in 17.06.1 and 17.08 (edge).

**Comment by vistradi** [comment]
Thank you for your answer. I will wait for version 17.06.1. Do you have an idea when this release will be available?
