### ISSUE TITLE
Docker won't open and throws this error

### ISSUE THREAD

**Issue by bjcatar** [docker/for-mac#1935]
### Information

Diagnostic ID: 75E08680-EE71-450A-8A79-905DA346BF69
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12.6 (Build 16G29)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by yallop** [comment]
You appear to be using a rather old version of Docker for Mac (1.12.0-a).  Could you please try upgrading to a more recent version?  If the problem persists, please submit a fresh issue.
