### ISSUE TITLE
Incorrect time on docker for Mac

### ISSUE THREAD

**Issue by demokedes** [docker/for-mac#1940]
### Expected behavior
Time shoud be ok
### Actual behavior
Incorrect time on docker for Mac and on all containers. I have problem because I can not run some services because container is out of sync. What can I do, to configure time on docker correctly?
### Information
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/9F1429FC-E849-494E-9C64-1A58FB8BD946/20170807-102345.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
17.03. is quite an old version.  Could you try upgrading to fix the problem?  There was a fix for this issue in 17.05 (edge) and 17.06 (stable): see https://github.com/docker/for-mac/issues/17#issuecomment-300734810.
