### ISSUE TITLE
ERRO[106389] error waiting for container: EOF 

### ISSUE THREAD

**Issue by gillez** [docker/for-mac#1941]
### Expected behavior
Docker image container to run continuously for a long period

### Actual behavior
At some point it exited with the following error:
ERRO[106389] error waiting for container: EOF 

The process was started on Friday morning and the error was noticed on Monday morning so the error happened at some point on Friday or over the weekend.  The system wasn't in use over this time and there's no timestamp so I can't say exactly how long it was up for before this happened.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnostics have been uploaded.  The ID is:
01D84A34-736C-471B-BA62-EEA240BB287C
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/01D84A34-736C-471B-BA62-EEA240BB287C/20170807-095022.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

The image is not uploaded anywhere so you won't be able to run the same image.  
But the steps were just to run the image with "docker run" and leave it for a day or two.
As I'm not expecting anyone to reproduce this I would really just like to know what the "error waiting for container" EOF error means, and whether the diagnostics show anything.

**Comment by evilstreak** [comment]
I also had my container terminating with `ERRO[…] error waiting for container: EOF`.

It was fine running a low intensity task, but when running something that used more CPU it failed on every run. Increasing the amount of available CPU (from 1 to 3) and memory (from 2G to 8G) through the Docker For Mac preferences resolved the issue.

I could see no indication anywhere that resource limits were the issue; if that is the issue it would be great if that was made clearer.

This is just anecdotal, but hopefully it helps for you!

**Comment by filipesperandio** [comment]
Faced the same problem a bunch of times over the past few days, always running variations of the same container. High intense CPU and RAM (container limited to 512M) and lots of console output.

**Comment by port80labs** [comment]
I have the same issue and it just started recently - may be after the update? also another similarity with OP, my image is also a private custom image. I dont know if this would be relevant but a point of consideration.

**Comment by StefanoFioravanzo** [comment]
I have been trying to run a Django web app inside a docker container for the past few days, after some time (it may be hours or days) it crashes with `ERRO[203312] error waiting for container: unexpected EOF`

There is neither high CPU/Mem usage nor lots of console output, so I don't think this is a resource limit issue. Also, I am not limiting the resources used by the container.

**Comment by gillez** [comment]
Our behaviour is similar to Stefano.  Increasing the resources doesn't help.    Does anyone know what this error actually means? 

Also, is Docker on Mac suitable and recommended for production?

**Comment by filipesperandio** [comment]
> Also, is Docker on Mac suitable and recommended for production?

I use it for development, but considering it for production would freak me out

**Comment by Drwhit** [comment]
I just started getting this error yesterday too.  I am using Rstudio R notebooks.  Whether I have one or two containers running at the same time, they both crash.

**Comment by alexgorbatchev** [comment]
FWIW Seeing the same on Windows 10 host.

**Comment by antonkulaga** [comment]
I have the same issue on Ubuntu (on Azure VM) when running containers that consume a lot of cores/memory. Looks like it is general docker issue

**Comment by feisuzhu** [comment]
We are experiencing this on a Mesos/Marathon (Linux cluster, not on Mac).

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     4  100     4    0     0    850      0 --:--:-- --:--:-- --:--:--  1000
pong  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     4  100     4    0     0    802      0 --:--:-- --:--:-- --:--:--  1000
pong  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     4  100     4    0     0    786      0 --:--:-- --:--:-- --:--:--  1000
pong**time="2017-11-29T18:37:45+08:00" level=error msg="error waiting for container: unexpected EOF"**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     4  100     4    0     0    829      0 --:--:-- --:--:-- --:--:--  1000
pongW1129 18:38:45.278836 13917 main.cpp:380] Health check failed Command check failed with reason: status still pending after timeout 30secs

**Comment by melissachang** [comment]
I am seeing this on Debian Google Compute Engine VM.

melchang@elasticsearch-not-cos:~$ docker -v
Docker version 17.12.0-ce, build c97c6d6
melchang@elasticsearch-not-cos:~$ uname -a
Linux elasticsearch-not-cos 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

I wonder if there's an earlier version of docker that won't have this issue.

**Comment by DmitryMandrik** [comment]
Hi guys! Are there any news about this ticket?

**Comment by melissachang** [comment]
GCE VM host when I saw this problem: 2 VCPU, 10.5 TB memory
GCE VM host when I don't see this problem: 12 VCPU, 31 GB memory

**Comment by Miserlou** [comment]
I updated Docker to the latest today and am now seeing this error every few minutes, corresponding with a Docker for Mac restart or total crash.

**Comment by DmitryMandrik** [comment]
to the latest stable 17.12.0-ce-mac55?

**Comment by Miserlou** [comment]
I think my error (and maybe this error?) is related to: https://github.com/docker/for-mac/issues/2690

**Comment by DmitryMandrik** [comment]
I have the error ERRO[106389] error waiting for container: EOF. BTW I ran my framework with Docker on Ubuntu and there was no error.

**Comment by akimd** [comment]
Hi guys!  As of today this issue has no Diagnostics from a recent version of Docker for Mac.  Unless someone provides some, I'll close this issue.

https://download.docker.com/mac/edge/Docker.dmg

**Comment by DmitryMandrik** [comment]
Hi guys! Is there any new workaround to avoid this issue?

**Comment by DmitryMandrik** [comment]
@akimd, here is the issue reproduced on the edge version 18.03.0-ce-rc4-mac57 (23360)
ID: C9ECD2DB-9976-4F64-BFDF-BBB3DC40E18E
```
Docker for Mac: version: 18.03.0-ce-rc4-mac57 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/C9ECD2DB-9976-4F64-BFDF-BBB3DC40E18E/20180326-030754.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/wheniwork/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/wheniwork/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/wheniwork/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```

**Comment by DmitryMandrik** [comment]
@akimd do you have any news? When do you plan to proceed with the issue?

**Comment by akimd** [comment]
I had a look, and it doesn't not ring any bell.  Others might have better ideas.

**Comment by edupo** [comment]
Same here with this random error. Docker 17.12.0-ce

**Comment by wkoziej** [comment]
Hi
I had similar error. 
Docker version 17.12.1-ce, build 7390fc6
Docker had crushed after several days running tensorboard

**Comment by letmaik** [comment]
Same issue here on 18.06.1-ce-win73.

**Comment by yucolabjames** [comment]
Running into the same problem here. But I can see docker is still working when i run `htop`.

**Comment by simonm3** [comment]
Same problem. On windows. Docker still running. Can still "docker ps -a". Container still running but can't exec into it.

**Comment by Thf772** [comment]
I have run into that problem today when trying to run pi-gen on Windows. Afterwards, I couldn't use any `docker` command either from Powershell or WSL Bash.

    Error response from daemon: L’adresse demandée n’est pas valide dans son contexte.
    Error response from daemon: Requested address is not valid in its context.

**Comment by DarrienG** [comment]
This happens sometimes when docker crashes or is stopped. It isn't necessarily indicative of a failure.

**Comment by RobertoDonPedro** [comment]
Same issue here on GKE running Docker version 18.09.7

> ERRO[0209] error waiting for container: unexpected EOF  

Neither CPU nor Memory reach their limits. The node logs just say 

> FrequentDockerRestart
FrequentKubeletRestart

Any ideas how to find the cause of this issue?
