### ISSUE TITLE
Can't find download links for old versions

### ISSUE THREAD

**Issue by adamdicarlo** [docker/for-mac#1943]
### Expected behavior

* https://github.com/docker/for-mac/releases, and/or
* https://docs.docker.com/docker-for-mac/release-notes/

contain build numbers and links to download old versions

### Actual behavior

No links are present. No build numbers are present, so manually constructing a link is not possible without finding someone running the version you want and having them open the "About" window to find out the build number and send it to you.

When `-mac19` version was pulled, this was especially annoying, as I needed to downgrade to -`mac18`, and even though it was the latest still-published stable version, there was no download link.

Now I'm having problems with `mac18` and realize I need to downgrade to `mac12`...

### Information

* https://github.com/docker/for-mac/releases
* https://docs.docker.com/docker-for-mac/release-notes/

### Steps to reproduce the behavior

n/a

**Comment by yallop** [comment]
This is tracked under #1120.
