### ISSUE TITLE
Docker treads wrong volumes paths

### ISSUE THREAD

**Issue by industral** [docker/for-mac#1945]
In Mac, by fault filesystem is case insensitive. Imagine, we have `/Data/MyProject`, and I try to mount it like `-v /data/projects:/data`, it will fails, with error:

`
docker: Error response from daemon: Mounts denied:
The path /data/projects not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
`

But, if you point `-v /Data/Projects:/data` it will work.

### Expected behavior

Docker should respect case insensitive of OS FS

### Actual behavior

Looks like Docker compared paths in case sensitive way, instead of following by OS FS

### Information

Reproducible both on stable & edge versions.

### Steps to reproduce the behavior

1. Create directory `MyDir`
2. Try to run any container with `-v /path/to/mydir:/some/path`
3. It will fails, even when in `Preferences -> File Sharing` you have that path.

Now, try the same but with `-v /path/to/MyDir:/some/path`, and it will work.

That's an issue, because from terminal, you can go to a directory like `/path/to/mydir` and then using `pwd` as reference for current dir, and that will not work...

**Comment by dsheets** [comment]
Thanks for your report! This is indeed a current limitation and will be fixed (along with many other issues) when moby/moby#33375 lands.
