### ISSUE TITLE
Docker engine does not support the parameter "--security-opt seccomp=" when executing command "docker build"

### ISSUE THREAD

**Issue by chenquanzhao** [docker/for-mac#1946]
### Expected behavior
The command "docker build" can support the parameter "--security-opt seccomp=\<SECCOMP PROFILE\>" when building docker image from Dockerfile in the macOS or Linux system.

### Actual behavior
But the fact that it emits the following error message when I build docker image in the macOS or Linux system:
**Error response from daemon: the daemon on this platform does not support --security-opt to build**

Otherwise, I saw the docker engine source code (v17.06), and it has been set the SecurityOpt in HostConfig when executing **RUN** instruction. However, why should check the runtime OS type, and it must be windows platform in the ```newImageBuildOptions``` method?

The code is：
```go
if runtime.GOOS != "windows" && options.SecurityOpt != nil {
	return nil, fmt.Errorf("the daemon on this platform does not support --security-opt to build")
}
```
```go
func (b *Builder) create(runConfig *container.Config) (string, error) {
	resources := container.Resources{
		CgroupParent: b.options.CgroupParent,
		CPUShares:    b.options.CPUShares,
		CPUPeriod:    b.options.CPUPeriod,
		CPUQuota:     b.options.CPUQuota,
		CpusetCpus:   b.options.CPUSetCPUs,
		CpusetMems:   b.options.CPUSetMems,
		Memory:       b.options.Memory,
		MemorySwap:   b.options.MemorySwap,
		Ulimits:      b.options.Ulimits,
	}

	// TODO: why not embed a hostconfig in builder?
	hostConfig := &container.HostConfig{
		SecurityOpt: b.options.SecurityOpt,
		Isolation:   b.options.Isolation,
		ShmSize:     b.options.ShmSize,
		Resources:   resources,
		NetworkMode: container.NetworkMode(b.options.NetworkMode),
		// Set a log config to override any default value set on the daemon
		LogConfig:  defaultLogConfig,
		ExtraHosts: b.options.ExtraHosts,
	}

	// Create the container
	c, err := b.docker.ContainerCreate(types.ContainerCreateConfig{
		Config:     runConfig,
		HostConfig: hostConfig,
	})
	if err != nil {
		return "", err
	}
	for _, warning := range c.Warnings {
		fmt.Fprintf(b.Stdout, " ---> [Warning] %s\n", warning)
	}

	b.tmpContainers[c.ID] = struct{}{}
	fmt.Fprintf(b.Stdout, " ---> Running in %s\n", stringid.TruncateID(c.ID))
	return c.ID, nil
}
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by YRM64** [comment]
Tagged #1946 and #34454 (github)

**Comment by vabburi** [comment]
Any update on this issue?

**Comment by leighmcculloch** [comment]
I'm also seeing `docker run` on docker-for-mac not supporting this field either. I specify the field, but it doesn't seem to have the effect I'm expecting or seeing others having on Linux.

**Comment by jamshid** [comment]
ptrace not working in Docker for Mac was also mentioned in the auto-closed:
https://github.com/docker/for-mac/issues/1564

**Comment by jamshid** [comment]
Found what appears to be a workaround on Docker for Mac, hope this helps someone else...
Just run this before starting your container with capability `sys_ptrace`:
```
docker run -ti --privileged centos bash -c 'echo 0 | tee /proc/sys/kernel/yama/ptrace_scope'
```
Now you can `docker exec` into your container running a hung python process and pass its pid, e.g.
`pyrasite 12 dump_stacks.py`
The output will be in the container's stdout.
