### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by superandrew** [docker/for-mac#1949]
### Expected behavior
Installing from the official docker image, Docker should install the helper and end installation successfully
### Actual behavior
No matter how many times I reset every docker file, restart, the installer asks for password, and once provided gets stuck here:
![screen shot 2017-08-09 at 17 10 17](https://user-images.githubusercontent.com/71364/29128948-a296564e-7d25-11e7-8e71-b4d89dd05350.jpg)
I can click OK countless times in an infinite loop.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Clean a previous working installation
  2. Delete ~/Library/Containers/com.docker*
  3. Delete /Library/LaunchDaemons/*docker
  4. Delete /Library/PrivilegedHelperTools/*docker
  5. Download and install Docker for Mac

I have this error logged in the console:

![screen shot 2017-08-09 at 17 18 41](https://user-images.githubusercontent.com/71364/29129371-e10d8e32-7d26-11e7-8650-a62ba40fb771.jpg)

**Comment by jasonbivins** [comment]
hi @superandrew   Have you tried using a different version?

**Comment by superandrew** [comment]
yes, my problem was not having anymore the `/private/var/tmp/com.docker.vmnetd.socket` file. Once restored, it began working, or so I guess. I don't know why it didn't simply recreate it.

see https://github.com/docker/for-mac/issues/570

**Comment by pgayvallet** [comment]
Seems fixed seeing last comment.

Closing, please reopen if still present.
