### ISSUE TITLE
Docker CLI commands are timing out

### ISSUE THREAD

**Issue by sdball** [docker/for-mac#195]
### Expected behavior

Docker CLI commands should run. Especially after I've restarted Docker via the toolbar menu option.

### Actual behavior

Docker CLI commands hang and eventually timeout.

### Information

Diagnostic ID: 12FF9AB1-FA6A-4E7F-8241-907BFC608755
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Have Docker for Mac running
2. Try to run Docker CLI commands

**Comment by sdball** [comment]
I switch the VM memory from 2GB to 4GB and after that restart the docker CLI commands are working again.

**Comment by mchiang0610** [comment]
Merging with #119
