### ISSUE TITLE
Docker commands hangs because of the moby vm 

### ISSUE THREAD

**Issue by kmala** [docker/for-mac#1950]
### Expected behavior

Docker commands should not timeout/hang. 

### Actual behavior
All the docker commands hang as the moby VM is hanged and i see soft lock up in the logs.
```
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [runc:[2:INIT]:30406]
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [runc:[2:INIT]:30382]
NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [kworker/0:1:8285]
NMI watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [runc:[2:INIT]:30406]
NMI watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [runc:[2:INIT]:30382]
```
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/EAF3A9CE-9873-446C-9AAE-55A811135BD6/20170809-103414.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. This happens when i run some heavy loads on the docker like running around 6 containers.

**Comment by djs55** [comment]
Thanks for the report and the diagnostics. Unfortunately the main Moby logs are missing (since the VM is in a bad state). Could you describe your workload in any detail? Was there lots of disk I/O? I/O to the host filesystem? Or network I/O? If you have any clues that would help us reproduce it, let me know.

One possibility is that disk I/O was delayed due to an online compaction of the .qcow2 file. To rule this out, try disabling TRIM by typing into a terminal on the host:
```
cd ~/Library/Containers/com.docker.docker/Data/database/
git checkout master
mkdir -p com.docker.driver.amd64-linux/disk
echo -n false > com.docker.driver.amd64-linux/disk/trim
git add com.docker.driver.amd64-linux/disk/trim 
git commit -s -m 'Disable TRIM'
```
and then restart the app.

**Comment by kmala** [comment]
There is a lot of network I/O as i am running a CI container which builds a node app and there are some other containers which are pretty much idle.

**Comment by djs55** [comment]
@kmala The next time this happens, could you upload a diagnostics after restarting the app? The VM logs are stored in the VM on the disk (the same disk as the containers and images) and should be retrievable when the VM is rebooted.

In the meantime I'm working on improving the logging -- I'd like the logs to be streamed to the Mac host so they are always accessible, even when the VM is stuck.
