### ISSUE TITLE
Seems docker for mac still can not resolve private dns domain with suffix ".local"

### ISSUE THREAD

**Issue by szyhf** [docker/for-mac#1951]
### Expected behavior

```
docker login my.office.local
Login success
```

### Actual behavior

```
Error response from daemon: Get http://my.office.local/v2/: dial tcp: lookup my.office.local on 192.168.65.1:53: read udp 192.168.65.2:57574->192.168.65.1:53: i/o timeout
```

Due to this DNS problem I can't push or pull any image from my private registry.

BTW, my private registry work well on other machine in the same office on CentOS 7.2

### Information

Looks like the same problem in #1827, when I changed my DNS server and switch my local domain to "my.office", remove the ".local", it works well ( Not any problem with login, push or pull ) . But #1827 said that this problem is fix in `Version 17.06.0-ce-mac19 (18663)`, my version is the latest version download yesterday:

By About Docker:

```
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```

By Docker Version:

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

My mac version:

macOS Sierra 10.12.6 (16G29)

**Comment by szyhf** [comment]
@djs55 Please review it, thanks a lot.

**Comment by djs55** [comment]
@szyhf could you reproduce the bug again and then upload diagnostics from:

- Whale menu
- Diagnose and Feedback...
- Diagnose & Upload

and quote the diagnostics ID? The logs should have some useful information.

Could you also try running `docker login` from a shell inside the Linux VM? To login to the Linux VM run a command like:
```
docker run --rm --net=host --pid=host --privileged -it justincormack/nsenter1 /bin/sh
```

**Comment by szyhf** [comment]
Sure, I'll try them ~

**Comment by szyhf** [comment]
Diagnostic ID: `E41E2E68-5DAD-4C7F-838E-E7567B2E38EA`

Command and resp: 
```
docker login reg.lfeng.local
Username: admin
Password:
Error response from daemon: Get https://reg.lfeng.local/v2/: Get https://reg.lfeng.local/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp: lookup reg.lfeng.local on 192.168.65.1:53: read udp 192.168.65.2:53568->192.168.65.1:53: i/o timeout
```

**Comment by szyhf** [comment]
While using the docker vm with command: 

```
docker run --rm --net=host --pid=host --privileged -it justincormack/nsenter1 /bin/sh
```

Run and resp:

```
docker login reg.lfeng.local
Username: admin
Password:
Error response from daemon: Get http://reg.lfeng.local/v2/: dial tcp: lookup reg.lfeng.local on 192.168.65.1:53: read udp 192.168.65.2:48423->192.168.65.1:53: i/o timeout
```
