### ISSUE TITLE
Docker freezes when I'm run it

### ISSUE THREAD

**Issue by jtprog** [docker/for-mac#1957]
MacBook Pro 15" Early 2011
macOS Sierra 10.12.6
How I'm reinstalling a Docker?
[Выборка «Docker».txt](https://github.com/docker/for-mac/files/1220867/Docker.txt)

**Comment by jackxb** [comment]
`/Applications/Docker.app/Contents/MacOS/Docker --uninstall` also not working.
How to completely remove Docker to reinstall?
