### ISSUE TITLE
Can't stop or kill container

### ISSUE THREAD

**Issue by Nemo64** [docker/for-mac#1959]
### Expected behavior
docker kill xxx should stop any container

### Actual behavior
The container isn't killed. The cli process stops with this error message
```
ERROR: for [container_name]  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
I can still stop or kill other containers so the connection is fine, it's just this one container.

### Information

ID: ED0DC8BA-76DB-421D-B170-5E1C8624CE6B
I did run the diagnostic right after I noticed that i can't stop the container. It isn't the first time this happened.

Here is an exact docker file (lengthy)
```
FROM php:7.0.13-fpm-alpine

#everything for php extensions
RUN apk add --update --no-cache --virtual build-depencencies \
    autoconf \
    expat-dev \
    freetype-dev \
    icu-dev \
    libc-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libstdc++ \
    libxml2-dev \
    libgcc \
    make \
    musl-dev \
    openssl-dev \
    pcre \
    re2c \
 && apk add --no-cache \
    binutils \
    binutils-libs \
    coreutils \
    file \
    g++ \
    gcc \
    gmp \
    icu-libs \
    isl \
    libatomic \
    libcurl \
    libgomp \
    libltdl \
    mpc1 \
    mpfr3 \
    openssl
RUN docker-php-ext-install \
    bcmath \
    iconv \
    intl \
    json \
    mbstring \
    mysqli \
    opcache \
    soap \
    xml \
    zip

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
 && docker-php-ext-install gd

# Install APCu
RUN pecl install apcu-5.1.6 \
 && docker-php-ext-enable apcu

# imagemagick
RUN apk add --no-cache imagemagick

RUN apk del build-depencencies \
 && rm -rf /tmp/pear

# copy configuration
COPY php.ini /usr/local/etc/php/conf.d

# change www-data user id
RUN sed -i s/www-data:x:82:82/www-data:x:1000:1000/g /etc/passwd
```

### Steps to reproduce the behavior

This happened with the php `php:7.0.13-fpm-alpine` image after some time with heavy io. To be more precise, it was a typo3 project. However It is a private project so I can't post an exact test case. But I tend to believe it has something to to with the `:cached` volume mount. I'm not sure, I can't reliably reproduce it.

**Comment by patakijv** [comment]
I am seeing now this with an image in development for a custom rails application image/container that has been using docker as development environment for over a year without this problem. 

I first noticed this problem when trying to just run `docker stop CONTAINER` and it will just hang there and any future attempts to stop or kill the container just hang. If I restart docker using the "Restart" button, it doesn't seem to have any change. I must quit docker and start anew to be able to successfully run and stop/kill again - which works at least once ... up to a few more times... then it returns to this new behavior of unable to stop or kill-then-start. I think that if I have used `kill` vs `stop` in those first few times, then I notice the problem will occur upon a next `start` attempt and I will see the error message posted from the OP. Once I see that message, it is the same as if it hangs after trying to stop, I can't go forward with trying to `run` again until a full stop and starting up again of Docker.

> ERROR: for pnd  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for app  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

If it helps:
- The current version in use is Version 17.09.0-ce-mac35 (19611) Channel: Stable and I think this started either with this version or a recent prior version 
- The base image of our rails app image uses `phusion/passenger-ruby22` base image
- Our scripted solution for propping up our development environment uses `d4m-nfs` and `docker-compose` version 1.16.1, build 6d1ac21 when starting up containers.
- Macbook Pro running version 10.11.6 (15G1611)
