### ISSUE TITLE
After closing/opening Mac Book Docker should run without problems

### ISSUE THREAD

**Issue by dkdndes** [docker/for-mac#1960]
### Expected behavior

After closing the Mac Book and opening Docker should still run

### Actual behavior

Crash

### Information

Docker for Mac: version: 17.07.0-ce-rc1-mac21 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A330h)
logs: /tmp/44C7680E-53E4-428C-9176-D71D42A92DDE/20170815-072137.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/peter/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/peter/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/peter/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/peter/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/peter/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
### Steps to reproduce the behavior

  1. Not regular, but multiple times. Hard to guess

**Comment by jasonbivins** [comment]
Hi @dkdndes   To my knowledge, this is a Mac limitation.  I'm not aware of a way to prevent a Mac from sleeping when you close the lid.   Docker requires a constant network connection to it's VM, and will have to be restarted if the connection does drop, which is what you're most likely experiencing when your machine goes to sleep

**Comment by spicydonuts** [comment]
Also seeing this on macOS 10.13.  I did not see it on 10.12.

**Comment by ebriney** [comment]
@djs55 : Do we have any way to test it? It seems to be a `High Sierra` specific issue
