### ISSUE TITLE
ABF1E88E-D914-4D2F-BEF2-6DDE9E4186A9

### ISSUE THREAD

**Issue by Atriny** [docker/for-mac#1963]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Atriny** [comment]
ABF1E88E-D914-4D2F-BEF2-6DDE9E4186A9 
Diagnostic ID
help needed. thx

**Comment by pgayvallet** [comment]
Closing. Please reopen with actual problem description if still occuring.
