### ISSUE TITLE
Docker for Mac Fails to Create Subdir inside of Mounted Volume

### ISSUE THREAD

**Issue by cfriedt** [docker/for-mac#1964]
### Expected behavior

Create a subdirectory inside of a mounted volume (Note: this works perfectly well under Linux).

### Actual behavior

mkdir: cannot create directory '/root/build/conf': Permission denied

mkdir fails with errno == EPERM when it should be perfectly free to create a directory inside of a mounted volume

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/243C2860-1222-40A4-8500-F43B6D1A9BF7/20170816-192826.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW

sudo rm -Rf docker-test
mkdir docker-test
cd docker-test
sudo mkdir -p build
cat << EOF > Dockerfile
FROM ubuntu:xenial
ARG HOME=/root
WORKDIR /
RUN mkdir -p ${HOME}/build
EOF
docker build -t foo .
docker run -v ${PWD}/build:/root/build -it foo:latest mkdir -p /root/build/conf

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. run the exact commands above

**Comment by dsheets** [comment]
> `sudo mkdir -p build`

Docker for Mac runs as your user and not root. Creating `${PWD}/build` as root will make it owned by root but the container will run "as you" from a shared file system perspective. Because of this, you get `EPERM`. Simply run `mkdir -p build` on the host or nothing as `-v` will automatically create a source path that doesn't exist.

**Comment by cfriedt** [comment]
Hmm... that's an unfortunate inconsistency..
