### ISSUE TITLE
com.docker.driver.amd64-linux uses 530G of virtual memory.

### ISSUE THREAD

**Issue by steffenix** [docker/for-mac#1966]
### Expected behavior
Virtual memory should not exceed few GB.
### Actual behavior
I am experiencing some issues with my containers they seems to hang. When trying to stop them, I have a timeout, docker takes few minutes to execute. I have tried to reset/reinstall docker. The only thing that I can see is the virtual memory used by com.docker.driver.amd64-linux  is 530 gb.

<img width="656" alt="screen shot 2017-08-17 at 3 48 06 pm" src="https://user-images.githubusercontent.com/2143646/29401374-8172bf72-8363-11e7-9f5b-9bdb7ab1668d.png">

### Information

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/E5C997C7-D95B-46E9-81B9-D9C14BF4C936/20170817-154207.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by numbnut** [comment]
Same (532GB) for me on 
osx 10.13.2
docker for mac 17.12.0-ce-mac46 (21698)
