### ISSUE TITLE
docker pull fails when connected with VPN

### ISSUE THREAD

**Issue by koehnlein** [docker/for-mac#1968]
I'm connected with my company's network via VPN. Everything works fine, but `docker pull` fails since a few days or weeks. It worked fine already a long time. But maybe there were any changes in current version?

### Actual behavior

    $ docker pull docker.private/renfert/typo3
    Using default tag: latest
    Error response from daemon: Get http://docker.private/v2/: dial tcp 192.168.2.110:80: getsockopt: no route to host

### Information

  - My network range at home is 192.168.1.x
  - The company's network range is 192.168.2.x

**Comment by ecoffman** [comment]
No word on this?

**Comment by koehnlein** [comment]
I switched from "edge" to "stable", that solved the problem for me.
