### ISSUE TITLE
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/...N.../merged: no such file or directory.

### ISSUE THREAD

**Issue by russelljjarvis** [docker/for-mac#1974]
### Actual behavior
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/ea64c7b8ec8ea39764172a790efc7fb761e59b15915a45354fa692cec07519fb-init/merged: no such file or directory.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
   C8C96F85-04EB-4846-A24A-F2F95F3C072F
  - A reproducible case if this is a bug, Dockerfiles FTW
I suspect not a bug, but a duplicated user caused issue, that is difficult to solve.

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bencoder** [comment]
see #1396

**Comment by MasterCATZ** [comment]
have this issue on Ubuntu when pointing to a MergerFS
