### ISSUE TITLE
Docker build no longer works, just hangs.

### ISSUE THREAD

**Issue by ashesfall** [docker/for-mac#1979]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by d-Pixie** [comment]
I'm seeing the same.

Diagnosis ID: 497E340F-0368-4A6B-BDD6-674F148ED6C1

```
Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/497E340F-0368-4A6B-BDD6-674F148ED6C1/20170822-111701.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
I'm building a simple Alpine based Nginx container, build context is about 500kB, and after you hit return on the build command it just sits there for 2.5 minutes (I timed it) before the build starts, when the build does start it executes at normal speed.

Not changed anything locally that should affect this and the network works fine for other things so ...
