### ISSUE TITLE
Docker Composer not finding running Docker for Mac

### ISSUE THREAD

**Issue by cguess** [docker/for-mac#198]
### Expected behavior

docker-compose should build and run the images in my docker-compose.yml file. This was working just fine for weeks and it all of a sudden stopped.

### Actual behavior

docker-compose returns error "ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac."

### Information

Diagnostic ID: DAA0DC79-B826-41B8-A8D9-9E23D93C10C4
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1.) Start docker for Mac
2.) Navigate to folder with my docker-compose.yml file
3.) run "docker-compose up"

### Other information

Docker itself works fine, and can build and attach without a problem. I've restarted my machine and reinstalled Docker for Mac, no change in behavior.

**Comment by cguess** [comment]
When running 'docker-compose ps --verbose' the following happens
`docker.auth.auth.parse_auth: Found entry (registry=u'registry.heroku.com', username=u'_')
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 110, in perform_command
  File "compose/cli/command.py", line 35, in project_from_options
  File "compose/cli/command.py", line 110, in get_project
  File "compose/cli/command.py", line 85, in get_client
  File "site-packages/docker/api/daemon.py", line 76, in version
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 140, in _get
  File "site-packages/requests/sessions.py", line 477, in get
  File "site-packages/requests/sessions.py", line 465, in request
  File "site-packages/requests/sessions.py", line 573, in send
  File "site-packages/requests/adapters.py", line 415, in send
requests.exceptions.ConnectionError: ('Connection aborted.', error(22, 'Invalid argument'))
docker-compose returned -1`

**Comment by cguess** [comment]
I figured the problem out. I had the following environment variable:

`COMPOSE_HTTP_TIMEOUT=1000000000`

Changing it to

`COMPOSE_HTTP_TIMEOUT=60`

Solves this problem.

**Comment by cguess** [comment]
Looked in a little more, the magic number of seconds is 100,000,000

This works:
`COMPOSE_HTTP_TIMEOUT=100000000`

This does not:
`COMPOSE_HTTP_TIMEOUT=100000001`

**Comment by rvarbanov** [comment]
Removing all containers and images fixed the issue for me.

**Comment by cguess** [comment]
@rvarbanov I'm not sure what to say, the problem I was having is the timeout is oddly set, which I figured out. Removing all containers and images is sort of the nuclear option for something like this (which I attempted, and didn't solve my problem, because it's a bug in the handling of the timeout integer).

**Comment by rvarbanov** [comment]
I posted that here because although I did not have the same issue I had the same error message ("ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.")

Maybe not the best place to post that, but when searching Google for that message I get this issue page, so I might help someone like me if I post it here...

**Comment by mchiang0610** [comment]
I'm closing the issue here as it's not a Docker for Mac problem. Will relay to the Compose team. 

Thanks!

**Comment by SyntaxStacks** [comment]
I was having the same issue, I had a local `.env` file that was causing the issue. After deleting the file I was able to get `docker-compose` working again. Hope this helps someone that's tried all the steps above.

**Comment by remie** [comment]
Might also be related to the lack of read permissions on one of the files/folders in the build context. See https://github.com/docker/compose/issues/4462 for more information on this issue.

**Comment by xuan-yue** [comment]
This worked for me:

`sudo nohup docker daemon -H http://tcp://0.0.0.0:2375 -H http://unix:///var/run/docker.sock`
