### ISSUE TITLE
Docker daemon.json validation not working properly

### ISSUE THREAD

**Issue by rreinurm** [docker/for-mac#1983]
### Expected behavior
It should be possible to edit configuration of daemon.json to modify "userns-remap" or "default-runtime" from UI by following steps Preferences -> Daemon -> Advance and filling in proper config.

### Actual behavior
UI shows json validation error like `"userns-remap" : Must be a string`. If I leave `"userns-remap" : ""` then validation succeeds and I could save the configuration.
Current workaroud is to modify `~/.docker/daemon.json` directly. I haven't tested out all keys, there might be more.
![screen shot 2017-08-22 at 13 02 16](https://user-images.githubusercontent.com/4215660/29561147-129252c4-873d-11e7-8cbd-67dea3d78f77.png)

### Information
Version 17.07.0-ce-rc3-mac23 (18949)
Channel: edge
ead952bbb0

**Comment by gtardif** [comment]
This has been fixed in 17.07.0-rc4
