### ISSUE TITLE
Docker can't read logs

### ISSUE THREAD

**Issue by jnmandal** [docker/for-mac#1984]
### Expected behavior

Be able to read docker logs, despite any error messages. `docker events` command should work or display some human-readable error

### Actual behavior

When docker container is not stopped gracefully (ie computer is shut down while containers running), logs become corrupt and can no longer be read. Error message:
```
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```
Seems to be related to: https://forums.docker.com/t/docker-daemon-error-invalid-character-x00-looking-for-beginning-of-value/18072/4

The command `docker events` will run forever without exiting or outputting anything.

My workaround so far has been to use "Remove all data" feature under "Reset" in preferences, but its frustrating to reinstall all containers whenever I forget to stop containers or computer auto-updates.

### Information

Docker for Mac: version: 17.06.0-ce-mac19 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/A2C0DE10-7188-4A98-93D8-9EAD1A849527/20170822-104841.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. run containers
  2. shut down computer (w/o stopping them)
  3. start up and run containers
  4. attempt to access logs

**Comment by nobuf** [comment]
I have faced the same error message. I'm not 100% sure if it's related, but I did restart forcefully my Mac earlier today.

`docker stop the-container` → `docker rm the-container` then start it again solved the problem in my case though. (`docker logs the-container` works)

```
$ docker version
Client:
 Version:      17.07.0-ce-rc4
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   fe143e3
 Built:        Tue Aug 22 22:25:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.07.0-ce-rc4
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   fe143e3
 Built:        Tue Aug 22 22:30:35 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by OmgImAlexis** [comment]
Getting the same issue here on macOS 10.12.6 (16G29).

```
➜  amon git:(master) ✗ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by drorwolmer** [comment]
```sh
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by bichotll** [comment]
I also got the same problem. The docker container stopped all of the sudden without any trace or clue of the reason.

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Kshitiz-Sharma** [comment]
Facing this issue with version `Docker version 17.09.0-ce, build afdb6d4`

error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

**Comment by bluecatchbird** [comment]
I can reproduce this error when i have a container with a lot of log output and i remove the power cable from the computer. After 5-10 times docker logs ends with the error.
Then you can see theres some garbage(^@) in the container log file(/var/lib/docker/containers/\<CONTAINER-ID>/\<CONTAINER-ID>-log.json)

Here is a workaround:
```
$ systemctl stop docker.socket
$ vim /var/lib/docker/containers/<CONTAINER-ID>/<CONTAINER-ID>-log.json # remove all garbage(^@) from log file
$ systemctl start docker.socket
```

A simple solution would be, to fix the json file automaticly.

**Comment by TelpeNight** [comment]
Facing the same issue on Ubuntu after hard reboot of the server.
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

```
uname -r
4.4.0-109-generic
```

```
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by asifakb** [comment]
I'm also getting this problem Error grabbing logs: unexpected EOF.

Background: My broker container was shutdown by saying no more space left on the disk. 
Stopped all containers and ssh into my docker-machine host and removed the logs manually (
root@confluent:~# rm -rf /var/lib/docker/containers/*/*-json.log ) and then restarted using docker-compose up -d command. After that I never had my broker up at all not matter how many restarts I do the server stops indefinitely by throwing Error grabbing logs: unexpected EOF error. PLEASE HELP.

![image](https://user-images.githubusercontent.com/12346995/43470830-244f2f98-94af-11e8-8dd7-7f3dabaf2d01.png)

**Comment by ulidtko** [comment]
FWIW, this happens to me on Linux 17.05.0-ce as well.

Since viewing container logs is **essential functionality**, this issue shouldn't be auto-closed; freezing it against the bot.

**Comment by garland** [comment]
FWIW,
I am also experiencing same behaviour on:
Ubuntu 18.04.1 LTS
Docker version 17.12.0-ce, build c97c6d6
