### ISSUE TITLE
can u tell me why this bitbucket webhook always invalid url?

### ISSUE THREAD

**Issue by tagiris123** [docker/for-mac#1985]
![4](https://user-images.githubusercontent.com/30254340/29608389-8f9070e6-8826-11e7-990f-9ea274dd3863.png)
![5](https://user-images.githubusercontent.com/30254340/29608391-8fb2402c-8826-11e7-85cb-d9befca196c7.png)
![6](https://user-images.githubusercontent.com/30254340/29608392-8fb6243a-8826-11e7-9f1f-193676a2cd71.png)

**Comment by tagiris123** [comment]
@nchazlett how can i add 0-triage in status?

**Comment by askmike** [comment]
@tagiris123 from the perspective of bitbucket `localhost` does not refer to you but to there own servers. You need to provide bitbucket either an url with either a domain name or an IP address. This is not a docker issue.

**Comment by tagiris123** [comment]
@askmike thanks for your cooperation sir, but actually i solved my problem i think last 19days. i just install ngrok.io for new proxy server base on this conversation channel https://community.atlassian.com/t5/Bitbucket-questions/Bit-Bucket-Jenkins-Integration/qaq-p/219232

**Comment by askmike** [comment]
Great, ngrok is a good solution for this. If this is solved you can close the issue!
