### ISSUE TITLE
RequestCoreException: cURL resource: Resource id #159; cURL error: Failed to connect to docker.for.mac.localhost port 8888: Connection refused (7)

### ISSUE THREAD

**Issue by CGerAJ** [docker/for-mac#1986]
### Expected behavior
connect sucess!
### Actual behavior
error 
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

yesterday! I updated my macOS to 10.12.6  So I suspect that the system is updated

Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/3ED12588-CFC1-4E1F-9993-FE48501B7A42/20170823-175149.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by toby-griffiths** [comment]
@CGerAJ I'm seeing this problem today. Did you manage to resolve this?

**Comment by nicoburns** [comment]
A QA tester at my company hit against this today. Doing 'Reset All Data' from the preferences UI seemed to fix the problem.

**Comment by AkiraXue** [comment]
i get  good after  'Reset All Data' from the preferences' after listening the Solution by  @nicoburns ， but  i don't know the reason for  question's Principle, if anyone has the idea, please show me, thank you
