### ISSUE TITLE
Include Docker Machine v.0.12.2

### ISSUE THREAD

**Issue by brandontamm** [docker/for-mac#1989]
Docker-machine version is severely outdated, yet I noticed Docker-for-Mac was just updated and did not include the most recent version of docker-machine.

Can we please provide update as there are many backwards-compatible issues that have been fixed with v0.12.2?

**Comment by twang2218** [comment]
The outdated issue has been reported before: https://github.com/docker/for-mac/issues/1875

I hope someone here can do something about it, or clarify what's stopping the upgrade.

**Comment by timothyallan** [comment]
I used brew to install the latest version of Docker Machine to fix a bunch of issues, just overwrite the old version.

**Comment by gtardif** [comment]
This has been updated in the latest Docker For Mac / Windows release today (17.06.2)
