### ISSUE TITLE
Cannot pull images from Docker hub

### ISSUE THREAD

**Issue by 0x434D53** [docker/for-mac#199]
### Expected behavior

I can pull images from docker hub.

### Actual behavior
> docker pull ubuntu

Using default tag: latest
Pulling repository docker.io/library/ubuntu
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.

It does not matter if have my firewall on or off. Docker itself work, i can run containers etc. 

https://index.docker.io/v1/ is reachable, when i curl it i get a 200 with 
"Docker Registry API"

. So my netwwork is working.

I had this problem before in one of the early docker for mac beta but it disappeared. I try to reset Docker for Mac, Reinstall, and i tried the current beta: Same result. I cannot pull images.

### Information

Diagnostic ID: 272CC3FE-5C3E-4E32-944E-1EB2DD3C42FC
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by 0x434D53** [comment]
Additional observation: I use a MacBook. Every other Application has network connection when i am on WIFI only. Only docker pull does not work.
If i plug in the cable (Thunderbolt to Ethernet) also Pull works. Do you eventually bind to a certain network interface?

**Comment by Kyle-Falconer** [comment]
I'm also having a similar issue to this on my MacBook Pro when trying to pull from Ubuntu, but with different error, so I don't know if it's related:

```
$ docker build ./
Sending build context to Docker daemon 208.5 MB
Step 1 : FROM ubuntu:14.04
Pulling repository docker.io/library/ubuntu
Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp 52.22.190.106:443: getsockopt: connection refused
```

I am behind a proxy, but even if I set the proxy through the Docker settings, it still fails. All other applications have internet access and I am able to access that URL from within Chrome.

Diagnostic ID: 406672C1-D897-45BC-9739-03ADA0DA73BF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by 0x434D53** [comment]
Update: As expected from the release notes, the issue is still there in v1.12.0.1

**Comment by 0x434D53** [comment]
Update: Issue seems to be solved in 1.12.0-beta22 (build:11222).

**Comment by Bharathkumarraju** [comment]
Hi team,

I am also unable to pull images....how can change the docker registry in mac.. I have account in dockerhub...but in my mac it is saying docker registry as docker.io...can anyone help me on this?

```
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: unauthorized: incorrect username or password
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: AV33:ZWKT:44GD:YGUO:W2FH:ABUH:DDAF:P3SE:GTMD:3VQ6:7476:KPS5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 29
 System Time: 2017-10-11T15:15:46.843513848Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$
```

**Comment by Bharathkumarraju** [comment]
I found it and it worked as below.

```
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker login --username=bharathkumarraju
Password:
Login Succeeded
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
88286f41530e: Pull complete
Digest: sha256:f006ecbb824d87947d0b51ab8488634bf69fe4094959d935c0c103f4820a417d
Status: Downloaded newer image for alpine:latest
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              76da55c8019d        4 weeks ago         3.97MB
bharathkumars-MacBook-Air:Downloads bharathkumardasararaju$
```
