### ISSUE TITLE
unable to connect to port after resume from sleep

### ISSUE THREAD

**Issue by snstanton** [docker/for-mac#1990]
### Expected behavior
I have a container running mysql with the port exposed as 9306:3306.  I would expect the port to be accessible after a resume from sleep.

### Actual behavior

Attempts to connect like:  
 `mysql -h 127.0.0.1 -u root --password=<pw> --port 3306`
result in:
`ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)`

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/AADE8522-3004-4B98-A057-734DE4573073/20170823-092324.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
see docker-compile file for the setup

### Steps to reproduce the behavior

```
docker swarm init || true
docker network create --driver overlay --attachable ownet || true
docker stack deploy -c docker-compose.yaml dev
```
Suspend the machine, then resume.  Most of the time, one or more of the exposed ports will inaccessible, although often at least one will still work.

[Archive.zip](https://github.com/docker/for-mac/files/1246238/Archive.zip)

**Comment by snstanton** [comment]
I have found that every morning when I resume from sleep, the overlay network is always broken.  If I quit Docker and then launch it, the stack comes up properly and is 100% functional.  Nothing else seems to reliably fix the problem.

**Comment by natew** [comment]
Also get this, have to restart docker ~10 times a day due to closing laptop.

**Comment by snstanton** [comment]
As of 17.12.0-ce-mac55 (23011), I have not seen this behavior.

**Comment by baronfel** [comment]
I run into this issue as well. The scenario is

- Connect to work VPN (we use Cisco AnyConnect)
- Start containers
- Sleep machine
- Wake machine
- VPN disconnects
- Containers are non-responsive and attempting restart results in the docker app crashing.

`Diagnostic ID`: `5EA8A028-1AFD-4A09-9F1C-638CADF50026`

Diagnostics Logs:
```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/5EA8A028-1AFD-4A09-9F1C-638CADF50026/20180328-101512.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/chethusk/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/chethusk/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/chethusk/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```

**Comment by havenchyk** [comment]
I have the same error with `Engine: 18.09.0`. Could you guys please reopen this issue?

**Comment by snstanton** [comment]
Agreed.  This wasn't a problem for a long time until it resurfaced in 18.09.0.

**Comment by snstanton** [comment]
I am currently using the latest edge release:  
```
Version 2.0.0.0-mac82 (29268)
Engine: 18.09.0
Compose: 1.23.2
Machine: 0.16.0
```

**Comment by vnagendra** [comment]
Same issue observed on macOS High Sierra with the following docker. Issue details - 

1. OS goes to sleep 
2. After wake up, the connectivity to docker containers is lost
3. Restarting the containers doesn't help 
4. Restarting the *engine* and then the containers, seems to bring everything back up. 

Diff between sleep/wake is not immediate -- it's only after a few hours. The same behavior happens when I change networks (in a matter of 30 minutes to 1 hour typically). I don't have a way of confirming if the network change is causing the issue or general sleep is causing the issue. Even without a network change after a few hours same behavior occurs (overnight for example)

Was definitely *not* a problem until the 18.09 upgrade.

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by clareecker** [comment]
Experiencing this with VM Ware on Windows, with docker `18.09.0`, restarting my VM after my machine has been asleep resolves the problem. Internet access in the VM works fine, but docker network seems stuck.

**Comment by askabelin** [comment]
I have the same issue. Maybe it will be useful. If I do `network disconnect <network> <container>` and then `network connect <network> <container>` I get the following error:

> Error response from daemon: driver failed programming external connectivity on endpoint blahblah (de17641e5de4): Error starting userland proxy: Bind for 0.0.0.0:8600: unexpected error Host.Sockets.Too_many_connections

**Comment by keksa** [comment]
I have the same issue on Windows 10 Pro (v1809) Docker Desktop 2.0.0.3 (engine 18.09.2). Happens after waking up from hibernation. `docker-compose restart` fixes the problem for me.

**Comment by keksa** [comment]
Found a solution, that worked for me on Windows. I did the steps from this answer on SO, only with Hyper-V interfaces, instead of VirtualBox - https://stackoverflow.com/a/32997115/7457614 and everything works like a charm.

**Comment by jayofdoom** [comment]
I can confirm I'm seeing the same issue as keksa, after device goes to sleep, all container shared ports are inaccessible. Restarting from the Docker Desktop menu resolves the issue.

**Comment by samuelchen** [comment]
I have the same issue on MacOS 10.14.5.

**Comment by trenner02** [comment]
I see this issue on Docker 19.03.1, build 74b1e89.  I am running Docker in a CentOS 7 VM and if I suspend the VM, then power it back on, connections no longer work.  Restarting the Docker daemon isn't enough to fix it, I have to tear down my stack of containers and re-start them.  docker-compose down, then up will work, as will docker-compose restart.

I don't see packets making it all the way through via IP Tables.  The rules are there for the running containers, but there are no hits on the DOCKER chain.  In fact, in the FORWARD chain, I don't see any packets being sent to the DOCKER chain.

**Comment by altjx** [comment]
Same issue here. Extremely annoying. Have to reboot the VM several times a day.

**Comment by malchikserega** [comment]
I have same problem with my docker-container. After few hours of sleeping, script from container can't connect to my external server(

**Comment by nhanledev** [comment]
I am experiencing the same problem. I use Ubuntu 18 VM in VmWare and every single time I resume it, the docker network stop working, and I have to reboot.

**Comment by dennis-benzinger-hybris** [comment]
> I am experiencing the same problem. I use Ubuntu 18 VM in VmWare and every single time I resume it, the docker network stop working, and I have to reboot.

Try `systemctl restart NetworkManager docker` instead of a reboot.

**Comment by mloyat** [comment]
Not exactly the same issue but somehow related, with ubuntu 19.10 when resuming from sleep, my containers can't reach external network (communication between containers still works). 
A reboot or a `systemctl restart NetworkManager docker` makes it work again.
thx @dennis-benzinger-hybris

**Comment by juha-pmg** [comment]
Same problem here, running 19.03

**Comment by woutslakhorst** [comment]
Same problem, 19.03.5 on Catalina (10.15.3)

**Comment by holgerbrandl** [comment]
The solution `systemctl restart NetworkManager docker` restores the to access ports in containers, BUT also quits all running containers unless they have a restart policy. This does not seem to be a good workaround to me, so I wonder if there a different way to keep all containers up and running and just restart/reconfigure the network.

The best reference is https://kb.vmware.com/s/article/1923 which the root cause is explained. however, there is no working fix in this article either.

**Comment by guytet** [comment]
Seeing the same issue on FedoraWorkstation with Docker version 19.03.13, build 4484c46d9d . 

When the bare metal system goes to sleep (this isn't a VM, it's an Intel NUC), `docker0` does not come back up with an IP address, and all the containers loose external connectivity outside their own network - as there is no default gateway (Which would have been iface `docker0`). 

`systemctl restart NetworkManager docker` does restore connectivity, however as mentioned - containers that are not `--restart always` get removed.

**Comment by Kradepon** [comment]
Seeing this issue onLinux Mint 20, Docker 19
