### ISSUE TITLE
Docker install issue on MAC 

### ISSUE THREAD

**Issue by Ricigliano** [docker/for-mac#1991]
Diagnostic ID: D22C329F-9BAD-4028-8A35-6F1911CAA627

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
![image](https://user-images.githubusercontent.com/28021664/30949499-bbd70ac8-a3e4-11e7-9f6b-5433a90c557c.png)
