### ISSUE TITLE
Docker mac bip option does not work.

### ISSUE THREAD

**Issue by rhyas** [docker/for-mac#1997]
### Expected behavior
Setting {"bip":"192.168.254.1/24"} in the advanced config should set the docker network to 192.168.254.0/24.

### Actual behavior
This appears to do nothing. Still defaults to 172.17.0.0/16

### Information
Version 17.06.1-ce-mac24 (18950)
Channel: stable
54dc09c3e3

**Comment by 510908220** [comment]
how to solve?
