### ISSUE TITLE
Docker update dialog is too ostentatious 

### ISSUE THREAD

**Issue by bdharrington7** [docker/for-mac#1999]
I get that you would want users to keep up to date with the latest and greatest. But this is a humble request that D4M not be so in my face about it, grabbing the screen focus.

If I want to be notified of updates, it would be nice if it were more subtle. Something like how Google Chrome does it, a little dot or something where you can see at a glance that there's an update, and I can get to it when I'm ready, rather than a jarring, `alert('New update available!')` type of notice. Sometimes, in certain environments, an immediate upgrade is not desired, especially in mission-critical situations where you need to know your dev environment works. 

Thanks for listening. 

Docker 17.06.1

**Comment by bdharrington7** [comment]
This is really annoying, and has become apparent again after the recent update (2.1.0.0) is being picked up by my different machines. 

Please consider a notification that's perhaps in the doc icon?

**Comment by bdharrington7** [comment]
This still happens on 2.1.0.3, asking me to upgrade to 2.1.0.4

**Comment by rollcat** [comment]
I normally avoid "me too" kind of comments but just came here to report this. This is annoying. Please do not steal focus from my work.

**Comment by bdharrington7** [comment]
I think around version 3, when the new UI was deployed, this is no longer a problem, and update notifications are a nice little icon on the menubar. Thanks!
