### ISSUE TITLE
Automatically start Docker when you log in doesn't work (not sudo?)

### ISSUE THREAD

**Issue by henvic** [docker/for-mac#2]
### Expected behavior
Let me choose to update or not docker automatically.

### Actual behavior
docker for Mac doesn't let me tick the option / opt in auto update.

### Information
Chances are I have some config broken that is not restored by the 'reset' functionality (as I have used it a lot) or it is related with my user not being a sudoer / Admin.

Currently running Version 1.12.0-rc4-beta20 (build: 10404) 32ce3bdb164320603f1c2d1fb2ba32a43477ef3d, but this problem happened with older versions (at least, beta14).

$ uname -a
Darwin henvic.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

<img width="492" alt="docker-for-mac-no-update" src="https://cloud.githubusercontent.com/assets/936421/17235219/018540c6-54f4-11e6-9b67-aa8ae6a68cfd.png">

### Steps to reproduce the behavior

  1. notice I never get to see auto update modals
  2. try to update on the app itself

**Comment by henvic** [comment]
I have updated by downloading the .dmg. Now I can check / uncheck the "Automatically check for updates" icon. Maybe you can just close this as it seems to be fixed.

<img width="492" alt="docker-for-mac-stable" src="https://cloud.githubusercontent.com/assets/936421/17238249/007129a0-550f-11e6-9b91-a4567228410a.png">


After updating:
Diagnostic ID: 2803944F-0CF2-46D6-B84D-CFC08B753B65
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by samoht** [comment]
Thanks for the report. Please re-open the issue again if you can reproduce.
