### ISSUE TITLE
docker-for-mac issue

### ISSUE THREAD

**Issue by avijitsarkar123** [docker/for-mac#200]
### Information

Diagnostic ID: EF1C717D-4310-4841-9211-CA87FBC9D925
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/len980/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/EF1C717D-4310-4841-9211-CA87FBC9D925/20160809-140804/qemu-img-check.stdout 2> /tmp/EF1C717D-4310-4841-9211-CA87FBC9D925/20160809-140804/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119 and #601
