### ISSUE TITLE
"reset your daemon settings" doesn't reset the json configuration

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#2001]
### Expected behavior
I could be wrong, but I think the "reset your daemon settings" link on Preferences => Daemon => Advanced does not work. 
### Actual behavior
I had a `"dns" : ["8.8.8.8"],` setting in the json, pressed the reset link, it restarted Docker for Mac. But when I went back to check the setting was still there. Removing it manually and Apply did work.
### Information

```
Docker for Mac: version: 17.07.0-ce-rc4-mac25 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/DC64A1DC-F988-49BE-A3A4-D978E266218C/20170826-155526.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Fixed on stable and edge. Closing
