### ISSUE TITLE
Can't ping (using curl, ab etc) freshly deployed service until d4m is restarted

### ISSUE THREAD

**Issue by anokun7** [docker/for-mac#2004]
### Expected behavior
I'm deploying a very simple [microservices app](https://github.com/anokun7/counter-demo). This app has worked for the last 3-4 months at least. I use a script under `/test/run.sh` to bring up the application. This is my standard testing app & I have run the application against the latest UCP & previous versions of UCP as well as d4m, without any issues.

Once `run.sh` is run it brings up the application and on d4m, different versions (4 versions) of the application can be accessed on several ports (typically 30000-30003). So you would access one of the versions using http://localhost:30000/ for example. The `run.sh` script displays all that and also  tests the applications by running load to generate stats & traffic.

### Actual behavior

Since the last update of d4m, the `run.sh` script deploys and I can see the application come up but I am not able to ping any of the versions of the application using `curl` or `ab`. This gets fixed once I restart d4m

### Information
Diagnostic ID:
FBBA120B-FDA1-4C52-AB90-D76328028D56

### Steps to reproduce the behavior

  1. git clone https://github.com/anokun7/counter-demo
  2. cd test
  3. run `dockerid=<dockerid> ./run.sh`
  4. Follow the output until the last step, it hangs (should have printed `=_=_`
  5. Click on the d4m icon in the task tray and hit `Restart`
  6. Once d4m restarts, the hits would go through.

**Comment by djs55** [comment]
Thanks for the report and the repro steps. I tried fresh installs of 17.06.1 (stable) and 17.07.0-ce-rc4-mac25 (edge) and both seemed to work ok: I got lots of `=_=_`, an exit code of 0 and the URLs worked from my browser.

I'll have a look to see if I can see anything specific in your logs.

Does it always fail in the same way? If you don't mind rebuilding your images, could you try a factory reset: whale menu -> Preferences -> Reset -> Reset to factory defaults?

**Comment by anokun7** [comment]
@djs55 Thank you for looking into this. Looks like I can't repro the issue myself. I'll keep this open for today & close it tomorrow if I can't repro it.
