### ISSUE TITLE
Updated, docker images lost

### ISSUE THREAD

**Issue by danki** [docker/for-mac#2005]
Updated: 30min later after posting this issue.
i just discovered that ALL my images are GONE.. !
Just like it happend [issue#935](https://github.com/docker/for-mac/issues/935)

... now ... how the heck do i restore them !?!?

### Expected behavior
Docker in general should work.

### Actual behavior
Restarting Docker does not complete, seems to get stuck at "starting docker...".
Tried to restart containers, docker and finally computer, no effect.

### Information

  - Diagnostic ID: 31C89822-8E30-48FF-B66A-3B11F107E2DD

### Steps to reproduce the behavior

1. No specific, have only restarted Docker and computer as well but no result.

These problems started after update to: **_Docker version 17.06.1-ce, build 874a737_**

Duplicate: 
#1998 - possibly related
#1992 - probably related

**Comment by danki** [comment]
Additional info:

Output from terminal
```bash 
deko:lib deko$ docker info | grep Root
Docker Root Dir: /var/lib/docker
deko:lib deko$ ls /var/lib
postfix
```

Screenshots
![qcow2 - preferences](http://i.imgur.com/OoUJ86X.png)
![qcow2 - file info](http://i.imgur.com/IqLgfia.png)

**Comment by remones** [comment]
the same problem, I lost all my images after Docker version changed, but the Docker.qcow2 already exists.
