### ISSUE TITLE
Docker  hangs after latest update

### ISSUE THREAD

**Issue by hardikgw** [docker/for-mac#2007]
### Expected behavior
docker-compose brings up containers
### Actual behavior
docker-compose and docker-compose build hangs
### Information
compose file: https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/docker-compose.yml
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. install Version 17.06.1-ce-mac24 (18950)
Channel: stable
54dc09c3e3
  2. Run docker-compose up

**Comment by cpuguy83** [comment]
Is only the docker-compose hung or all of docker... for example can you open another terminal and run normal docker commands?
Can you also make sure to provide the `Diagnose & Feedback` details from the Docker menu?

Thanks, again!

**Comment by hardikgw** [comment]
docker pull works. docker ps and docker-compose up hangs. Diagnose & Feedback is stuck at Diagnosing....

**Comment by hardikgw** [comment]
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/1EBD0F43-AB69-4648-BFC9-D9E5ABF24CAA/20170828-095001.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by hardikgw** [comment]
[20170828-095001.tar.gz](https://github.com/docker/for-mac/files/1256954/20170828-095001.tar.gz)

**Comment by hardikgw** [comment]
Issue resolved after "delete all data"

**Comment by vgoklani** [comment]
Why do you have to "delete all data" which presumably means rebuild all your containers to fix this?
