### ISSUE TITLE
Cannot login if password contains a special character

### ISSUE THREAD

**Issue by travsoule** [docker/for-mac#2008]
### Expected behavior

There are no special character rules when changing the password on cloud.docker.com, so a user should be able to create a password with them.

### Actual behavior

Passwords that include the `:` character will fail without giving the user an explanation.

### Information

Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/6831EA5A-C199-4A5B-AFF5-3AB770545986/20170828-172459.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Change account password to include a `:`
  2. Use password from Step 1 to log into cloud.docker.com - should be successful
  3. Log out of Docker for Mac (if not automatically logged out)
  4. Log in to Docker for Mac using account password from Step 1 - should fail

**Comment by khou** [comment]
Second this, my pw contained `:^)` and it kept failing

**Comment by edvald** [comment]
Just ran into this. In my case the `docker login` command worked and returned `Login successful` but any subsequent attempt to access my private repos failed with a permission error (e.g. `Error response from daemon: repository <...> not found: does not exist or no pull access`).

**Comment by dgilling** [comment]
Second this issue. Even docker support didn't know why I couldn't get authenticated.

**Comment by thaJeztah** [comment]
I can confirm; logging in works, but pushing after that fails, unless the password is updated to not include a `:`.

ping @n4ss @simonferquel @tych0 PTAL

**Comment by n4ss** [comment]
Having a look now!

**Comment by thaJeztah** [comment]
Looks like the password is not stored/updated in the keychain after successful login

**Comment by n4ss** [comment]
We found the source of the bug, working on the patch.

**Comment by n4ss** [comment]
This issue is fixed in the latest release.

**Comment by thaJeztah** [comment]
Closing because this should be fixed
