### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start, exit code 9

### ISSUE THREAD

**Issue by dayongchan** [docker/for-mac#2009]
### Expected behavior
Docker daemon keep running
### Actual behavior
Docker daemon quit
![image](https://user-images.githubusercontent.com/19189308/29812076-1318dcd6-8cd8-11e7-99c4-ae1a1c387492.png)

### Information
  - Docker version 17.06.1-ce, build 874a737
  - Intellij idea 2017.2.2
  - Macbook infomation
![image](https://user-images.githubusercontent.com/19189308/29811937-a848af6c-8cd7-11e7-94e3-e09699cd4a77.png)

### Steps to reproduce the behavior

  1. Start docker daemon
  2. Start intellij idea 2017.2.2
  3. Docker daemon quit and alert "com.docker.osx.hyperkit.linux failed to start, exit code 9"

**Comment by hegoku** [comment]
+1

**Comment by wxh2013** [comment]
+1

**Comment by lqpLee** [comment]
+1
