### ISSUE TITLE
Host's /etc/hosts content is available in containers

### ISSUE THREAD

**Issue by maitre-hibou** [docker/for-mac#2014]
Hello there,

When running and image on Docker for Mac, it seems that host's content of /etc/hosts is available in launched containers.

### Expected behavior

In the container command `ping this-domain-exists-on-host` should return something like `ping: bad address 'this-domain-exists-on-host'`

### Actual behavior

Ping is able to reach `this-domain-exists-on-host` on 127.0.0.1 in the container

### Steps to reproduce the behavior

1. Setup a custom localhost entry in host machine `/etc/hosts`. For example:
```
127.0.0.1 this-domain-exists-on-host
```

2. Run an alpine container :
```
docker run --rm -it alpine bash
```

3. Run a ping to custom domain in the container
```
ping this-domain-exists-on-host
```

This behavior is problematic when, for example in a docker-compose file, a domain present in host's `/etc/hosts` is mapped as alias in the `links` entry for a service.

Using Docker on Linux, everything works as expected.

Cheers !

**Comment by new-guy** [comment]
I'm experiencing issues with this as well.  Does anyone know of a good workaround?
