### ISSUE TITLE
Failed to login via GUI when password has special chars

### ISSUE THREAD

**Issue by caarlos0** [docker/for-mac#2016]
### Expected behavior

I click in the tray menu, login, write user and pwd, and it logs in.

### Actual behavior

It always says my password is invalid. Logging in via `docker login` works with the same user/pwd.

I also logged in with another account and it works.

I believe that the chars that make the password not work are one of those: `<>:),-`
The password that worked has special chars too, like `_` and `;`, and it works, so I'm assuming the problem is with the other chars.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

<details>

```
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/5CD1370B-0EFF-4504-A731-23FA8B386B2F/20170830-143904.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

```

</details>

  - A reproducible case if this is a bug, Dockerfiles FTW

n/a

  - Page URL if this is a docs issue or the name of a man page

n/a

### Steps to reproduce the behavior

  1. Login via the tray icon menu item with a password having these chars: `<>:),-`
  2. that's it

**Comment by danlsgiga** [comment]
Same thing here! Lost my last 2 days trying to figure this out!

**Comment by danlsgiga** [comment]
And I just confirmed, if you have : in your password it fails!

**Comment by kevlarr** [comment]
Brilliant, this has been blocking me for several days...

Although I seem to be different in that `docker login` was having issues for me as well. It would say "Login succeeded" but would fail to push because of access restrictions. Removing the `:` from my password made both `docker` and Docker for Mac log in properly.

**Comment by caarlos0** [comment]
@kevlarr yeah seems like `docker login` via the cmd is ignored and what matter is logging in via the GUI...

**Comment by n4ss** [comment]
This issue is fixed in the latest release.

**Comment by caarlos0** [comment]
thanks!

**Comment by jdbohrman** [comment]
Broken again......

**Comment by concrain** [comment]
yup..    denied: requested access to the resource is denied

**Comment by CRIZN** [comment]
Yeah same here unfortunately.

**Comment by bilal-khan** [comment]
Same here ☹️

**Comment by sheezyontrack** [comment]
I am having this issue now.

**Comment by ramanurs** [comment]
Any updates on this issue? I am facing same issue.
I do not have ":" in my password and it does say I am logged in successfully but push fails.

**Comment by ramanurs** [comment]
Yes I figured out that yesterday that my github repo is private and could not be used to push or pull images. Once I made it public it started working. But it was confusion as I am able to login but not able to push or pull images.

**Comment by hbirkdale** [comment]
I'm seeing this now too on my new Mac Book pro. My password does not contain any special characters, but I did notice that, although logging in through the CLI appears to work, logging in through menu does not work at all.

**Comment by mtapia79** [comment]
Ensure, you don't have special character in your password. I was this problem with jenkins at time to push image in Docker Hub.

**Comment by kamlekar** [comment]
In my case, the mac docker app was logged out. I just needed to login which fixed the issue.

**Comment by olwend** [comment]
After creating a public repo push gave 'denied: requested access to the resource is denied' error.
'docker logout' then 'docker login' on CLI resolved this.

**Comment by davegill** [comment]
Docker sends me here when I have this trouble from a Mac command line:
```
denied: requested access to the resource is denied
```
I am running Mac Mojave 10.14.6 with
```
docker --version
Docker version 17.12.0-ce, build c97c6d6
```

I have tried most of the suggestions from
https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker

1. Logout and then log back in.
2. Change the password to not have any special characters.
3. Specifically try -`-username=` and `--email=`. Perhaps my version is too old to support the `--email= option`.
4. I retried the logout/login/tag/push.
5. Used docker.io with the login command.
6. My docker image is public. I did not try to toggle back and forth between private and public. 
7. When I tried to use the Mac Docker Cloud app to login, it repeatedly says my password is wrong. I can go to cloud.docker.com and login with that password without any troubles.
<img width="492" alt="Screen Shot 2019-12-23 at 6 25 20 PM" src="https://user-images.githubusercontent.com/12666234/71387568-b8515b00-25b1-11ea-839c-070a5d2484e1.png">


Here's what I see:
```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
davegill/wrf-coop   sixthtry            153b4dcce135        About an hour ago   5.32GB
wrf-coop            latest              153b4dcce135        About an hour ago   5.32GB
centos              7                   5e35e350aded        6 weeks ago         203MB
```
```
docker login docker.io --username=davegill
Password: 
Login Succeeded
```
```
docker push davegill/wrf-coop:sixthtry
The push refers to repository [docker.io/davegill/wrf-coop]
aec11f36ca16: Preparing 
dcf5a9eb6119: Preparing 
3067e4c8a333: Preparing 
e7cf4fec39f7: Preparing 
8322bbc3ea9b: Preparing 
7a14c9ecfc89: Waiting 
5a3bd67311bc: Waiting 
2c3d0c8a6114: Waiting 
1c5ca571fb20: Waiting 
57a0bd0f18ff: Waiting 
631a0ca34e38: Waiting 
aa813be0d896: Waiting 
a33612b5aa1b: Waiting 
1a78ddd7082c: Waiting 
f3172e6970da: Waiting 
3a22c132a5a2: Waiting 
b04306fd0c56: Waiting 
058ce0ec5c56: Waiting 
0991eeb3b5cc: Waiting 
5b7ff53b0d05: Waiting 
be43ee1aece0: Waiting 
bd5e26c38ee4: Waiting 
65de77d148ad: Waiting 
61d649aff3e8: Waiting 
1c9f03b2f1a4: Waiting 
96c1843bb9cb: Waiting 
a2b1a7d67ce0: Waiting 
14401de444cd: Waiting 
2c6d1c92d170: Waiting 
c14a50d18598: Waiting 
6de599a698e2: Waiting 
b0438b745f9a: Waiting 
da24a7d8569f: Waiting 
7a42dc5208b2: Waiting 
f73428ecad23: Waiting 
77b174a6a187: Waiting 
denied: requested access to the resource is denied
```

**Comment by ragsarang** [comment]
Updating to latest did not fix the issue. 
password does not have ':'.
Logging into Mac Docker app fixed issue for me.

**Comment by FlorinAndrei** [comment]
3 year later and we still have this issue. :(

**Comment by axebox** [comment]
I just changed my password omitting special characters (is this for real?). Still not able to pull without getting resource denied.

**Comment by berkobob** [comment]
Cannot push "denied: requested access to the resource is denied"
