### ISSUE TITLE
Docker hangs when running nginx image

### ISSUE THREAD

**Issue by bunchjesse** [docker/for-mac#2017]
Docker hangs when running this very simple command:

```
docker run -it --rm -p 8080:80 nginx
```

It seems to be network related. If I disconnect from the network, I get the following error:

```
docker: Error response from daemon: dial unix /Users/jessebunch/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused.
```

> Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
> macOS: version 10.13 (build: 17A356)
> logs: /tmp/ED3557FF-2728-403B-804F-BC1CD36CE3D1/20170830-112412.tar.gz
> [OK]     db.git
> [OK]     vmnetd
> [OK]     dns
> [OK]     driver.amd64-linux
> [OK]     virtualization VT-X
> [OK]     app
> [OK]     moby
> [OK]     system
> [OK]     moby-syslog
> [OK]     db
> [OK]     env
> [OK]     virtualization kern.hv_support
> [OK]     slirp
> [OK]     osxfs
> [OK]     moby-console
> [OK]     logs
> [OK]     docker-cli
> [OK]     menubar
> [OK]     disk
>

**Comment by jotunskij** [comment]
I'm also having this, but I'm still on 10.12.

```
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/B3A2C59F-08F8-4E54-9654-43FDCA0BA94E/20170929-084816.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by jotunskij** [comment]
No change when switching to edge.

```
Docker for Mac: version: 17.09.0-ce-rc3-mac30 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/293A2D8B-6255-41B4-8262-3B52FFE0CB11/20170929-091648.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
