### ISSUE TITLE
Docker for Mac fails to first run on an Xserve 3,1 (2009)

### ISSUE THREAD

**Issue by nuxnix** [docker/for-mac#2018]
### Expected behavior
The app should run.
### Actual behaviour
Fatal Error: Incompatible CPU detected
### Information
Diagnostic ID: E5A1DD7F-523B-4FFC-A324-577404422D0A

'Docker requires a processor with virtualisation capabilities' is perhaps the wrong message because it does have them. 'Docker requires Apple Hypervisor Support' might be a better message.

Really although old, this machine should work and there is some other issue.

Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/E5A1DD7F-523B-4FFC-A324-577404422D0A/20170830-202513.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/angusf/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/angusf/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/angusf/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/angusf/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/angusf/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/angusf/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/angusf/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

  
### Steps to reproduce the behavior

  1. ... Install Docker for Mac on an Xserve 3,1 (2009) Running Either El Capitan or Sierra with the last known EFI firmware 1.2 
  2. ...Note that sysctl kern.hv_support reports kern.hv_support: 0
  3. ...Note that sysctl -a | grep machdep.cpu.feature reports VMX
  4. ...Note that this computer runs 64Bit VMware fusion VM's so virtualisation is not in question.

**Comment by nuxnix** [comment]
I have now tested my theory that the CPU is compatible with Docker by installing Ubuntu Linux 16.04 in a VMware Fusion VM on the same computer and running Docker there. I have been able to successfully launch a container. So again I feel the native Docker MacOS app should work, or the error message should be made more pertinent to the dependency on Apples Hypervisor

**Comment by neoneddy** [comment]
+1 on this.
