### ISSUE TITLE
Fatal error: failed migration: failed to update app version history

### ISSUE THREAD

**Issue by tosh** [docker/for-mac#202]
Just downloaded Docker beta for Mac and opened it for the first time after copying it to the Applications directory.

<img width="595" alt="screen shot 2016-08-09 at 9 14 06 pm" src="https://cloud.githubusercontent.com/assets/14825/17530072/43c9055e-5e76-11e6-9677-b2491dca9587.png">

### Information

Diagnostic ID: 2DB159CF-0CBF-464E-8E06-A5AAD9A6B862
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/tosh/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/2DB159CF-0CBF-464E-8E06-A5AAD9A6B862/20160809-210942/qemu-img-check.stdout 2> /tmp/2DB159CF-0CBF-464E-8E06-A5AAD9A6B862/20160809-210942/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/tosh/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/tosh/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/tosh/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/tosh/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/tosh/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Thank you for your report(s). We are investigating the issue.

**Comment by ununseptium** [comment]
You should try to just start docker beta app again. It worked for me and i had almost the same Error log like you have.

**Comment by quozd** [comment]
Same issue after upgrade to Sierra beta5
3FD82765-A7D2-4683-A463-296745ACCD93

**Comment by toffaletti** [comment]
It looks like the beta is still built with go 1.6.3, which isn't going to work on macOS Sierra. Docker needs to build with go 1.7.

```
$ docker version
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true
```

**Comment by shawnzhu** [comment]
I had the exact sample problem and fixed it by removing file `/usr/local/bin/docker` **before** starting docker app. The reason I did this because I found the target file that `/user/local/bin/docker` pointed to does not exists anymore.

After starting beta docker app, it will create symbol link `/usr/local/bin/docker` again.

**Comment by dsheets** [comment]
This problem should be fixed in the just released Beta 25. Please report back here if you continue to experience this problem

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
