### ISSUE TITLE
Services created by docker-compose unreachable by name

### ISSUE THREAD

**Issue by mshappe** [docker/for-mac#2020]
### Expected behavior

Given a service defined in a `docker-compose.yml`, the service should be available to other services by name, e.g. a service named `db` should be reachable by the hostname `db`.

### Actual behavior

The service is not reachable--the name never gets 'registered' internally.

### Information

First of all: this **was** working. It worked for several days. Then...it stopped. And once it stopped, nothing fixed it. Not rebuilding the VM, not resetting to factory defaults. Even uninstalling and re-installing did not fix it.

This also **never** worked with the non-edge version, which is why I upgraded to the edge version in the first place. Which was working, until yesterday, when it inexplicably stopped.

```
Docker for Mac: version: 17.07.0-ce-rc4-mac25 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/CEBD4957-14AE-4038-B2CC-E5F5C284A0E4/20170831-124801.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by mshappe** [comment]
As a sanity check, I fired up a Linux box, installed the current docker-ce there along with the latest docker-compose, and ran the same configuration up the flagpole. It worked as expected and as it had been working before this anomaly.

**Comment by mshappe** [comment]
Closing the issue myself. Someday I will learn that sudden unexplained anomalies are probably something I did wrong, after all 🐑

**Comment by djs55** [comment]
Thanks for closing the issue promptly (and don't worry about it -- this kind of sudden unexplained anomaly happens to all of us from time to time ...)

Thanks for using Docker for Mac!
