### ISSUE TITLE
All network communications from D4M containers not destined for local bridge is looped back from macOS host

### ISSUE THREAD

**Issue by cwwade** [docker/for-mac#2021]
### Expected behavior
Container communications to IP addresses not on the local bridge0 interface (i.e., routed via Moby's default gateway address) should be NAT'ed out via the macOS host's IP address onto its primary "real" network interface. This seems to be expected behavior for all other Docker environments, though the container obviously has to be configured to allow this.
### Actual behavior
Any container communications directed to IP addresses (e.g., 8.8.8.8) other than for bridge0 (e.g., 172.17.0.0/16) will be looped back to the sending container. This appears to be a consequence of using the macOS loopback interface (lo0) for communications from the host to containers via published ports. There are many other posts that discuss the awkward constraints imposed by this Mac specific approach that make it difficult for the host to communicate directly with containers via the container IP addresses. However, I have not seen any reference to this problem where containers are not able to communicate beyond the macOS host. 
This is a significant limitation for users of the new Docker for Mac package. The older Docker Toolbox system does not have this problem. An example use case is that I have a SmokePing container that is useless under Docker for Mac, since every IP address is mere microseconds away. (Also, there are also no unreachable IP addresses.)
### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/52541FC4-2556-4664-87FD-35130A9741ED/20170831-164030.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
see below...
  - Page URL if this is a docs issue or the name of a man page
Since I suspect that the response to this issue is unfortunately going to be "that's just the way it is," then this problem should be addressed under "Known Limitations..." on this doc page:
[https://docs.docker.com/docker-for-mac/networking/](url)

### Steps to reproduce the behavior

1) Build a container with the busybox image. 
2) Run this container's busybox shell and perform these commands:
`ifconfig
route
ping 8.8.8.8
traceroute 8.8.8.8`
3) The results from the above will look like this:
`/ # ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:03  
          inet addr:172.17.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5477 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:181950 (177.6 KiB)  TX bytes:5476 (5.3 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:176 (176.0 B)  TX bytes:176 (176.0 B)

/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 eth0
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=37 time=0.541 ms
64 bytes from 8.8.8.8: seq=1 ttl=37 time=0.363 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.363/0.452/0.541 ms
/ # traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 46 byte packets
 1  172.17.0.1 (172.17.0.1)  0.010 ms  0.007 ms  0.003 ms
 2  *  *  *
 3  *  *^C
`

If there is some workaround, or I'm not doing something correctly, then I'd really like to find out what can be done. After all, the ability to build containers that can perform live network operations is a primary use case for Docker.

**Comment by djs55** [comment]
Thanks for the report. `ping` is currently buggy in the stable version, see #57. As you observe, the responses come back from the local host rather than the remote machine.

The networking component was fixed in moby/vpnkit#271 and this fix was released in the `edge` version `17.07.0-ce-rc3-mac23`. Could you try installing the latest `edge` version and seeing if that fixes the problem you're seeing?

**Comment by cwwade** [comment]
Thank you, @djs55 ! Things definitely appear to be working better, and I'm successfully able to communicate to remote hosts on the Internet from a D4M container. That was certainly a fast turnaround, and much appreciated. 

I am seeing some other networking oddities, though, which I will report on after I've further analyzed the situation with this new edge version (17.07.0-ce-rc4). 

For the record, what I'd really love to be able to do would be to map a container directly to an address on a real network interface; something I do all the time with other VMs in the heavyweight virtualization systems. I'm really hoping that Docker's promise holds up, because this really could be a much better way to maintain network tools and applications. I do realize that Docker is constrained by some of the platform issues.
