### ISSUE TITLE
bind: cannot assign requested address

### ISSUE THREAD

**Issue by 357589873** [docker/for-mac#2027]
### Information

Once I bind success,but oneday docker crashed for unknown reason.where restart,bind function seem do not work.

docker run -it -p 127.0.0.0:8080:80 wanghaodvwa:v2 /bin/sh
docker: Error response from daemon: driver failed programming external connectivity on endpoint mystifying_jang (317beffd952ac8a3054e2d6f2eb5a0fa9590dc9829f1dba49a1212476643d918): Error starting userland proxy: listen tcp 127.0.0.0:8080: bind: cannot assign requested address.  - A 

There is no container running background.
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by TanLingxiao** [comment]
You can add ' --net=host ' to your command

**Comment by FLGMwt** [comment]
I stumbled onto this issue trying to create an ssh tunnel from within a container (running on a linux host) to an external machine.

Attempted (within container): 

```
ssh -i key.pem -NL 5555:localhost:5555 user@host
```

Without any networking arguments to `docker run`, this gave me:

```
bind: Cannot assign requested address
channel_setup_fwd_listener_tcpip: cannot listen to port: 5555
Could not request local forwarding.
```

I added `--net=host` to `docker run` and tried it again, and it worked (shrug). Not directly related to original issue, but I just wanted to say thanks @TanLingxiao

**Comment by YRM64** [comment]
There's a healthy discussion on the above stated issue at https://serverfault.com/questions/444295/ssh-tunnel-bind-cannot-assign-requested-address.
