### ISSUE TITLE
Creating custom network causes Docker For Mac restart to hang

### ISSUE THREAD

**Issue by ChadJMiller** [docker/for-mac#203]
### Expected behavior

create custom network:
$ docker network create -o com.docker.network.bridge.default_bridge=true -o com.docker.network.bridge.enable_icc=true -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.bridge.host_binding_ipv4=0.0.0.0 -o com.docker.network.bridge.name=docker0 -o com.docker.network.driver.mtu=1500 --subnet=10.0.0.0/8 --gateway=10.0.0.1 my-network
46de8dafcb74871402d89bfcc31090c7920a79c33fe3c4edee2da96c92cb1a89

Then restarting Docker For Mac should simply restart.
### Actual behavior

create custom network:
$ docker network create -o com.docker.network.bridge.default_bridge=true -o com.docker.network.bridge.enable_icc=true -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.bridge.host_binding_ipv4=0.0.0.0 -o com.docker.network.bridge.name=docker0 -o com.docker.network.driver.mtu=1500 --subnet=10.0.0.0/8 --gateway=10.0.0.1 my-network
46de8dafcb74871402d89bfcc31090c7920a79c33fe3c4edee2da96c92cb1a89

Restarting Docker For Mac after having created my-network will hang.
### Information

Diagnostic ID: 0EFA2B2E-6F5B-476E-854D-E2E7FA189A1D
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Create a custom network:
   create custom network:
   $ docker network create -o com.docker.network.bridge.default_bridge=true -o com.docker.network.bridge.enable_icc=true -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.bridge.host_binding_ipv4=0.0.0.0 -o com.docker.network.bridge.name=docker0 -o com.docker.network.driver.mtu=1500 --subnet=10.0.0.0/8 --gateway=10.0.0.1 my-network
2. Restart Docker For Mac

**Comment by mchiang0610** [comment]
Seems related to #119

**Comment by dsheets** [comment]
This seems pretty specific as to cause of the issue -- we should keep it open to track this reproduction.

**Comment by ijc25** [comment]
Logs contain
```
time="2016-08-09T19:18:53.556082042Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to allocate gateway (10.0.0.1): Address already in use" 
```
So it seems like the new network is conflicting with something.

@ChadJMiller are you able to reproduce with the latest stable (1.12.3 at time of writing)? If so then please could you upload a fresh diagnostic take with that version -- we now collect more useful and relevant info which I hope will give a clue what is conflicting and why.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
