### ISSUE TITLE
Docker crashes - not useable

### ISSUE THREAD

**Issue by rubyisbeautiful** [docker/for-mac#2034]
### Expected behavior

Docker is useable

### Actual behavior

Docker starts after a reboot and crashes, gives beachball in menu, hangs, must be killed

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
This is only available from a running Docker
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  Start Docker

Here is my system info:

MacOS 10.12.6 on brand new MBP, 16GB.  This laptop basically has nothing on it, Docker worked for `hello-world` once yesterday, and never since.  Docker version 17.06.2-ce-mac27 

Console.app has some Docker output which may be useful, attached.  You'll see the version change... that was my attempt to fix by installing a newer version.  The older version (24) crashed, and so does the new version (27)

<img width="1155" alt="screen shot 2017-09-06 at 8 51 07 am" src="https://user-images.githubusercontent.com/1908/30115677-0afdee1a-92e1-11e7-8ceb-93bcfa58b93e.png">

Possible related to #2032 #2033

**Comment by rubyisbeautiful** [comment]
I `rm -rf` ed everything I could find related to the Docker install, and re-installed, and Docker started.  I quickly ran the diagnostic, in the hope that it would show something useful to you all before it (if it happens) becomes unusable again.

5EC65613-1ED2-48AD-B233-9D014A38D5F7

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/5EC65613-1ED2-48AD-B233-9D014A38D5F7/20170907-073806.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Not sure why it can't upload...daemon uses proxy, which is setup correctly and works (for rest of OS and applications).  It allowed me to sign in to docker registry and pulled my repos.

Hope this helps

**Comment by rubyisbeautiful** [comment]
This has happened again.  Now that it has I can see a pattern.  In both instances, it happened on the reboot after a hard reboot.  The cause of the reboot, while I can't definitely say was Docker, was probably Docker, because I'm hardly running anything else.  Each lockup was that the system became completely unresponsive to any input, keyboard, mouse, ssh, etc...  I hard-restarted with touch/power button.  When it came back up, Docker was no longer useable (hence my original misreporting it as "crashes on startup").  

So once again, Docker is no longer useable.

**Comment by rubyisbeautiful** [comment]
More information... I've simplified and clarified the steps to get it running again:

1.  `sudo rm -rf /var/tmp/com.docker.vmnetd.socket`
2. start Docker (previously had killed it from Activity Monitor / top)

**Comment by shovon** [comment]
Can confirm, killing Docker first, and then force deleting `/var/tmp/com.docker.vmnetd.socket` worked for me!
