### ISSUE TITLE
Docker does not come up after upgrade on osx

### ISSUE THREAD

**Issue by hgehrts** [docker/for-mac#2036]
### Expected behavior
Docker should start

### Actual behavior
it does not start, the icon in my taskbar constantly cycles the containers on the whale.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/27AF5BB8-8670-43BA-9F1D-0AF28562F1B1/20170906-181043.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
[20170906-181043.tar.gz](https://github.com/docker/for-mac/files/1282320/20170906-181043.tar.gz)

**Comment by Siebjee** [comment]
I have the same issue..

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/A2CDDD8A-1607-4B59-A7BA-FC419BDE1DD3/20170912-183831.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
**[ERROR]  docker-cli
         docker ps failed**
[OK]     menubar
[OK]     disk

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
