### ISSUE TITLE
Docker consumes all disk space

### ISSUE THREAD

**Issue by lucrocha** [docker/for-mac#2038]
Hi,

### Symptoms

The following Dockerfile causes docker on my OS X causes the docker build to get stuck and Docker.qcow2 to grow uncontrollably until I stop docker. Restarting docker *resumes* the unbound growth of Docker.qcow2.

### Dockerfile

```
FROM library/fedora:latest
RUN dnf -y install \
	pidgin pidgin-privacy-please pidgin-logviewer purple-plugin_pack-pidgin pidgin-otr pidgin-toobars pidgin-libnotify \
	aspell-pt_PT aspell-nl aspell-en hunspell-pt hunspell-nl hunspell-hr hunspell-es hunspell-fr hunspell-en-US hunspell-en-GB \
	findutils \
	procps \
	strace telnet socat nc \
	bitstream-vera-sans-fonts \
	bitstream-vera-sans-mono-fonts \
	bitstream-vera-serif-fonts \
	dejavu-lgc-sans-fonts \
	dejavu-lgc-sans-mono-fonts \
	dejavu-lgc-serif-fonts \
	dejavu-sans-fonts \
	dejavu-sans-mono-fonts \
	dejavu-serif-fonts \
	google-droid-sans-fonts \
	liberation-mono-fonts \
	liberation-sans-fonts \
	liberation-serif-fonts
RUN echo 1b74afe80eb00119c75f0835ab010a9d > /etc/machine-id
RUN fc-cache
ARG uid
ARG gid
RUN adduser -u $uid pidgin
```

### Command

And the command I run is: `docker build --build-arg uid=$UID -t pidgin .`

Where `$UID` is: 846525074

If I remove the `adduser` line from the Dockerfile the build completes and if I run the `adduser` command inside a container there is no issue.

And if instead I run with uid=500, it also works. ($UID comes from AD integration, I can't control it.)

Results of qemu-img info:
```
$ /Applications/Docker.app/Contents/MacOS/qemu-img info /Users/lrocha/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
image: /Users/lrocha/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
file format: qcow2
virtual size: 64G (68719476736 bytes)
disk size: 8.8G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
    refcount bits: 16
    corrupt: false
```

If I boot SystemRescueCd and access the qcow2, and I see one overlay in `/lib/docker/overlay2` using all the space (which was 6.6GB in this instance), which is in a single file: `diff/var/log/lastlog`

And the file is full of only `\000`.

#### With an empty qcow2
```
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/3185702C-A6C5-4E85-9DE4-2FACCD2DFEA6/20170907-171656.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

#### With unbound growth of qcow2

Docker never completes the diagnostics before I run out of disk space.

### Recovery

I need to stop docker, wait for the hyperkit process to exit, and remove the `Docker.qcow2` file.

**Comment by lucrocha** [comment]
The same Dockerfile crashes a linux VM (CentOS 7), dockerd at 100% and the thin pool also 100% full.

**Comment by djs55** [comment]
Thanks for your report.

As an experiment I tried switching to `aufs` but with similar results:
```
/var/lib/docker/aufs/diff/.../var/log # ls -lh
total 32063064
-rw-r--r--    1 root     root       30.6G Sep  7 16:43 lastlog
```
While the build is in progress the process writing to the file is:
```
/var/lib/docker/aufs/diff/.../var/log # fuser lastlog 
2941 
/var/lib/docker/aufs/diff/.../var/log # ps uax | grep 2941
 2941 root       0:40 {exe} docker-untar /var/lib/docker/aufs/diff/...
```

I trimmed your `Dockerfile` down to:
```
FROM library/fedora:latest
RUN adduser -u 846525074 pidgin
```
Since the `docker-untar` process seems to be going wrong I've filed [moby/moby#34769]

**Comment by djs55** [comment]
It turns out this is a duplicate of https://github.com/moby/moby/issues/5419 -- the problem is that `adduser` seeks to an offset in `/var/log/lastlog` based on the `uid`, which is ok since the file can be sparse. Unfortunately the current Go .tar implementation doesn't fully support sparseness and the file gets expanded to full size, allocating lots of space.

I believe the Go .tar implementation is being worked on upstream: https://github.com/golang/go/issues/13548

As a workaround could you try this suggestion: https://github.com/moby/moby/issues/5419#issuecomment-41478290
i.e. change the command to `adduser -l -u 846525074 pidgin` -- the `-l` or `-no-log-init` will prevent the `/var/log/lastlog` being populated.

Thanks again for your interesting report. I found it very educational! :)

**Comment by lucrocha** [comment]
Hi,

Thanks, the '-l' option prevents the issue, thanks!

As it's a duplicate, I'm closing this ticket.

Thanks again,
Luc
