### ISSUE TITLE
Docker crashes again....

### ISSUE THREAD

**Issue by vgoklani** [docker/for-mac#2040]
### Expected behavior
Docker for mac should run without crashing

### Actual behavior
Containers stop working. 
### Information
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/E17EB389-8730-4DC2-81C8-B67378BDA900/20170908-012927.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Run Docker containers

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
