### ISSUE TITLE
If my hypervisor is doomed on mac is docker doomed as well?

### ISSUE THREAD

**Issue by alexKheirallah** [docker/for-mac#2043]
When I check the `hc_support` on my mac I get 0:
```
iMac$> sysctl kern.hv_support
kern.hv_support: 1
```
Does this mean there is no way my Mac can be compatible with Docker (due to hardware)?

**Comment by jasonbivins** [comment]
Hi @alexKheirallah   You are correct, you won't be able to use Docker for Mac on your machine  :(

We do have a legacy option though that should get you most of what you need though [Docker Toolbox. ](https://docs.docker.com/toolbox/toolbox_install_mac/) 

This doesn't use the Hypervisor framework, so some functions are limited, but it should get you up and running.
