### ISSUE TITLE
Docker crashes on first run

### ISSUE THREAD

**Issue by svdvonde** [docker/for-mac#2045]
### Expected behavior

No crash

### Actual behavior

Docker (17.06.2-ce-mac27) crashes on first run after entering the administrator password. 

### Information
Docker version: 17.06.2-ce-mac27
Mac version: 10.12.6 (build: 16G29)
Diagnostic ID: C380BA22-545E-4C77-97A0-390A9F783E55

Parallels desktop 13 is also installed on this computer (not running when installing Docker)
 
### Steps to reproduce the behaviour

  1. Open the docker image & drag to applications
  2. Open docker from applications folder
  3. Enter administrator password when it asks to do that
  4. Diagnostics dialog opens.

**Comment by svdvonde** [comment]
Issue is similar to https://github.com/docker/for-mac/issues/107, but the proposed solution does not work.

**Comment by svdvonde** [comment]
Fix found in issue https://github.com/docker/for-mac/issues/1859

**Comment by lunks** [comment]
Thanks @svdvonde but I do have `/var/tmp` folder already.
