### ISSUE TITLE
Crashes on High Sierra with total data loss after wake up

### ISSUE THREAD

**Issue by NoComment73** [docker/for-mac#2052]
### Expected behavior
No crash when resuming my Mac from sleep
### Actual behavior
Docker crashes and loses all existing images (at least they don't show up anymore)

### Information
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A360a)
logs: /tmp/A8E4D4FA-B1CC-4377-84AF-811C9C9F0F93/20170914-105041.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/gwieser/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/gwieser/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/gwieser/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/gwieser/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/gwieser/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Put Mac to sleep
  2. Wake it up again, most likely docker will crash (it doesn't matter if any instance is running or not)

**Comment by akimd** [comment]
Sorry about this :/

Please, try a more recent version of Docker for Mac.

**Comment by NoComment73** [comment]
Can confirm, this is no longer happening with the latest version (at least not on my machine).

**Comment by akimd** [comment]
Excellent, thanks!
