### ISSUE TITLE
Docker daemon crashes?  Or at least docker cli no longer functions - even after cpu restart

### ISSUE THREAD

**Issue by sdupont73** [docker/for-mac#2056]
### Expected behavior
docker ps returns valid running containers

### Actual behavior
docker ps fails

CLI:~ $ docker images
Error response from daemon: Bad response from Docker engine

### Information

0D77E56F-06F5-43A6-92F0-7F148A9ADD3A

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/0D77E56F-06F5-43A6-92F0-7F148A9ADD3A/20170914-153219.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ... I don't know how to reproduce this.  I was rebuilding a docker container and it suddenly hung.  I tried to retry, restart docker, reboot and then retry, all to no avail.
  2. ...

**Comment by drakmail** [comment]
Have absolutely same problem (my Diagnostic ID: ADC82CA9-D9F7-4E77-ABBA-AE7F9519C086).

Maybe a duplicate of #2042

**Comment by kurguzov** [comment]
Same problem. Diagnostic ID: 145EC511-0989-47BC-98F9-47B67E19F13C

**Comment by majorvms** [comment]
The same thing. Diagnostic ID: 8CC1242B-3C6A-4507-82BE-8CDC2D258637

**Comment by kurguzov** [comment]
Is there any news? We actually stopped using multi-container environment due to this problem and waiting for resolution, so it's not "stale", it is "major" for my case.
