### ISSUE TITLE
Error when I am trying to pull Datapower

### ISSUE THREAD

**Issue by sudhakar9g** [docker/for-mac#2060]
### Information
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/F4937353-BE08-4898-82E1-371B682CFB6D/20170916-135600.tar.gz
[ERROR]  db.git
         db.git check failed with: (Failure
  "exec: cd \"/tmp/F4937353-BE08-4898-82E1-371B682CFB6D/20170916-135600/database\" && git checkout master: exit 1")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
![screen shot 2017-09-16 at 1 57 40 pm](https://user-images.githubusercontent.com/28962093/30514656-977a6d1a-9ae7-11e7-9e5e-c51fea0897f1.png)

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
