### ISSUE TITLE
Docker when waking up computer

### ISSUE THREAD

**Issue by rabkins** [docker/for-mac#2062]
### Expected behavior
Kepp docker running after waking up mac.

### Actual behavior
Docker crashes when the computer wakes up.

### Information

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A362a)
logs: /tmp/BE9A1BD5-6AAD-4670-8A15-FEFE9E7C8E04/20170918-095408.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/rabkins/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/rabkins/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/rabkins/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/rabkins/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/rabkins/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start container
  2. Put computer to sleep
  3. Wake up computer

**Comment by seanfisher** [comment]
Same here. 

Diagnostic ID `526432AD-00A1-4D8A-880D-D9CEFEF2BD17`.

Exactly the same diagnostic output except for the header (macOS build is slightly different, and of course logs).

> Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
> macOS: version 10.13 (build: 17A360a)
> logs: /tmp/526432AD-00A1-4D8A-880D-D9CEFEF2BD17/20170918-215806.tar.gz
