### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by mrfoh** [docker/for-mac#2063]
### Expected behavior
Docker will start
### Actual behavior
Docker says "Docker starting" but never starts (staying in starting forever)
### Information
Docker for Mac was working perfectly for me, until I rebooted my machine. Unexpectedly after that the docker daemon won`t start anymore and any docker command I try such as "docker ps" gives me a "Error response from daemon: Bad response from Docker engine" error message.

### Diagnostic ID
8FAC6E48-35AE-45FF-B53A-9E367E78337B

### Diagnostic Log
Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/8FAC6E48-35AE-45FF-B53A-9E367E78337B/20170918-093812.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by Epsichaos** [comment]
@mrfoh I have got the same issue for 2 days. My docker daemon is also very unstable. I can run docker containers, but they freeze in 5 minutes. docker ps also timed out. 

Reinstalling docker solved the issue for now.

**Comment by mrfoh** [comment]
I wiped the data and it works now.
