### ISSUE TITLE
build image over docker API via docker unix socket fails with connection closed

### ISSUE THREAD

**Issue by renewooller** [docker/for-mac#2067]
### Expected behavior
Can build over unix socket via Docker API. 
### Actual behavior
Connection closes.
### Information
This command to build an image via the Docker API works on Ubuntu 14.04 running docker 17, however on Docker for Mac it fails. 

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. open terminal, CD to a directory that has the Dockerfile. 
  2. Run:
```
tar c . | curl -v --data-binary @- --header 'Content-Type: application/x-tar' --dump-header - --no-buffer --unix-socket /var/run/docker.sock http:/v1.30/build?t=build_remote:a
```
  3. Get the output:
```
*   Trying /var/run/docker.sock...
* Connected to http (/Users/renewooller/Library/Containers/com.doc) port 80 (#0)
> POST /v1.30/build?t=build_remote:a HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/x-tar
> Content-Length: 169512960
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue
< Date: Tue, 19 Sep 2017 05:23:43 GMT
Date: Tue, 19 Sep 2017 05:23:43 GMT
< Connection: close
Connection: close

* We are completely uploaded and fine
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

**Comment by anuruddhal** [comment]
Any update on this issue?
