### ISSUE TITLE
Docker installer has weird offset blank button instead of OK when asking for password

### ISSUE THREAD

**Issue by zekink** [docker/for-mac#2075]
### Expected behavior
Normal OK button when asking password to make changes.

### Actual behavior
The installer has an offset, blank button that can be seen here.
![screenshot 2017-09-20 17 29 33](https://user-images.githubusercontent.com/13997056/30658619-ff30e1dc-9e43-11e7-9408-5939539e8404.png)

### Information
Downloaded Docker normally from the official site to install on a fresh work machine. Encountered the issue. The work computer is a Mac with Touch Bar, and on the Touch Bar the buttons were labeled "Cancel" and "Button". Redownloaded the .dmg and got a normal OK button instead. Unfortunately didn't save the original .dmg.

Then had to uninstall and reinstall Docker on my personal machine because of issues, and ran into the same thing. Again redownloading the .dmg and running the installer again it worked as intended.

Now that malware has been discovered in Transmission and more recently CCleaner, something like this happening in conjunction of asking the user password feels suspicious. Probably just an UI glitch though.

### Steps to reproduce the behavior

  1. Download Docker
  2. Run installer
  3. Maybe run into the issue

**Comment by jasonbivins** [comment]
Hi @zekink   I was able to reproduce this today when upgrading to the Edge version, and it has been reported as a bug

Thanks!
