### ISSUE TITLE
How docker decide which registry will be used when `docker push`? Does anyone know the exact rules?

### ISSUE THREAD

**Issue by biblesyme** [docker/for-mac#2079]
For example, 
If I tag a image as follow
1. a/b/c/d:latest
2. a.c/b/c/d:latest
3. a/b.c.d/c:latest
4. a.b.c.d:latest

How did I know where my Image will be pushed? Is there a REGEX to decide it?

**Comment by BrendonW** [comment]
What problem are you trying to solve?
