### ISSUE TITLE
Docker consumes energy when no containers are running

### ISSUE THREAD

**Issue by astyagun** [docker/for-mac#2081]
### Expected behavior

Docker not consuming energy when it's not running any containers

### Actual behavior

Docker's "Energy impact" in Activity Monitor ranges from 3 to 7 in my case

![terminal_ _tmux_attach-session_ _80x23_ _ 1_ _activity_monitor__applications_in_last_8_hours_](https://user-images.githubusercontent.com/158815/30745260-18a15e6a-9fae-11e7-9a98-83752d953d5c.jpg)

### Information

```
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/63369929-BC19-40C2-B1E6-8A96EA850149/20170922-155418.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

I assume, that it is this way always when there are no containers running

**Comment by jarlefosen** [comment]
Happens on `version/18.01.0-ce-mac48` as well.

Hyperkit uses about just above 30% CPU and Docker has an average energy impact of about 30. No containers are running.

<img width="425" alt="screen shot 2018-01-23 at 13 31 16" src="https://user-images.githubusercontent.com/2993240/35276087-705ad254-0042-11e8-8bbb-46a82e114272.png">

Diagnostics looks fine

```
Docker for Mac: version: 18.01.0-ce-mac48 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.12.6 (build: 16G1114)
logs: /tmp/5F73B1D4-3EBF-408F-95D6-E28BDE7A7CEF/20180123-133451.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

I am running on macOS Sierra with a Macbook Pro Retina mid 2015.

**Comment by astyagun** [comment]
I've recently learned, that you can `screen` into the VM with this command:

```
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
```

And then run `top` in there to see which processes consume the most CPU. 

I'm currently running version 17.09.1-ce-mac42 (21090). Energy impact is around 3 and `top` shows, that all processes inside the VM consume 0% CPU. Not a big energy impact, but why should there be any when no containers are running?

@jarlefosen it may be useful if you post the output of `top` in your case. Also, just a thought, because energy impact is so different, your issue may be unrelated to the one I've described.

**Comment by jarlefosen** [comment]
Cool, did not know about that one.

I restarted Docker+Kubernetes between this post and the last.

Docker - Energy Impact: 32
hyperkit - CPU usage: 24 %

Here's the raw output:

```
Mem: 1957524K used, 89424K free, 3160K shrd, 16336K buff, 1409540K cached
CPU:   2% usr   1% sys   0% nic  96% idle   0% io   0% irq   0% sirq
Load average: 0.23 0.20 0.16 1/500 4197
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2203  2182 root     S     119m   6%   0   1% kube-controller-manager --address=
 2140  2114 root     S     322m  16%   1   1% kube-apiserver --admission-control
 1115  1089 root     S     136m   7%   0   0% kubelet --kubeconfig=/etc/kubernet
 1017   982 root     S     507m  25%   1   0% /usr/local/bin/dockerd --config-fi
 2241  2216 root     S   10293m 513%   0   0% etcd --listen-client-urls=http://1
 2171  2156 root     S    42964   2%   0   0% kube-scheduler --leader-elect=true
 2758  2743 root     S    46020   2%   1   0% /compose-controller --kubeconfig
 2452  2435 root     S    40796   2%   0   0% /usr/local/bin/kube-proxy --kubeco
 2584  2568 root     S    38252   2%   0   0% /kube-dns --domain=cluster.local.
 2711  2697 65534    S    35768   2%   1   0% /sidecar --v=2 --logtostderr --pro
  859     1 root     S    28608   1%   0   0% /usr/bin/containerd
 1093  1017 root     S     282m  14%   0   0% docker-containerd --config /var/ru
 2656  2641 root     S    32164   2%   1   0% /dnsmasq-nanny -v=2 -logtostderr -
 1116  1089 root     S    13140   1%   0   0% /usr/bin/kube-setup-server
 1016  1014 root     S    12712   1%   1   0% /usr/bin/transfused
 1319  1281 root     S    11380   1%   1   0% /vsudd -inport 2376:unix:/var/run/
 1118   859 root     S    10816   1%   0   0% containerd-shim -namespace service
 1172   859 root     S    10816   1%   0   0% containerd-shim -namespace service
  906   859 root     S    10816   1%   0   0% containerd-shim -namespace service
  989   859 root     S    10816   1%   0   0% containerd-shim -namespace service
```

The VM reports CPU idle 96%. Could be an issue where even though the VM is idling it still has a negative effect on the host?

Just out of interest I tried to check the energy impact of Docker and the CPU usage of hyperkit with different numbers of CPU cores for the Docker VM. My system has 8 CPU cores, and I varied the number of cores to the VM between 1,2 and 4. Always 2 GB RAM.

Checking the impact with different number of cores:
* **1 core**
  * hyperkit cpu usage: ~16%
  * Docker energy impact: 24
* **2 cores**
  * hyperkit cpu usage: ~24%
  * Docker energy impact: 32
* **4 cores**
  * hyperkit cpu usage: ~25%
  * Docker energy impact: 35

Looks like the energy impact and cpu usage decreases noticeably when I only allow 1 core. Between 2 and 4 cores I see no noticeable difference.

@astyagun you are probably right, with such a big difference in energy consumption between me and you these may be completely different issues.

**Comment by jhogervorst** [comment]
I have the same issue. Docker's energy impact is continuously between 2 and 5, while no containers are running. I’m running Docker for Mac 18.06.0-ce-mac70 (26399).

![schermafbeelding 2018-08-03 om 22 29 06](https://user-images.githubusercontent.com/304065/43664291-b70fef2e-976c-11e8-9790-5617f3753d43.png)

**Comment by adrianlshaw** [comment]
Same here on an MBP 2015 with 10.14.5 and Docker Desktop 2.0.0.3. Energy rating of around 60.

<img width="832" alt="Screenshot 2019-06-10 at 22 56 22" src="https://user-images.githubusercontent.com/762640/59229794-4dbb6d80-8bd3-11e9-9afd-ec28cad39148.png">

**Comment by ianhinder** [comment]
This is happening to me as well.  com.docker.hyperkit has energy impact 8.9 with no containers running.
```
Docker version 18.09.2, build 6247962
```
/remove-lifecycle stale

**Comment by drdaz** [comment]
I'm not sure if this is related, but it smells like it might be.

I'm getting a lot of .wakeups_resource.diag files generated about hyperkit in System Reports (in Console). They look like this:

```
Date/Time:       2019-06-13 23:10:03 +0200
End time:        2019-06-13 23:12:44 +0200
OS Version:      Mac OS X 10.14.5 (Build 18F203)
Architecture:    x86_64h
Report Version:  28
Incident Identifier: 52BFBF16-8AF9-4AE2-9B56-5DCD307EE1B3

Data Source:     Microstackshots
Shared Cache:    0x10427000 F621D494-EE4D-32BB-96AA-9254C56E8F73

Command:         com.docker.hyperkit
Path:            /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
Version:         ??? (???)
PID:             566

Event:           wakeups
Action taken:    none
Wakeups:         45001 wakeups over the last 166 seconds (272 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:   45000
Limit duration:  300s
Wakeups caused:  45001
Duration:        160.94s
Steps:           40

Hardware model:  MacBookPro15,3
Active cpus:     16


Heaviest stack for the target process:
  40  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff67e4440d]
  40  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff67e48249]
  40  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff67e452eb]
  37  vcpu_thread + 1213 (com.docker.hyperkit + 1871990) [0x102a49076]
  24  xh_vm_run + 343 (com.docker.hyperkit + 1759971) [0x102a2dae3]
  24  vmx_run + 1718 (com.docker.hyperkit + 1722321) [0x102a247d1]
  24  hv_vcpu_run + 13 (Hypervisor + 5071) [0x7fff3e47e3cf]


Powerstats for:  com.docker.hyperkit [566]
UUID:            71246D3E-B4F4-34BA-9BE4-201218570ACE
Path:            /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
Architecture:    x86_64
Parent:          UNKNOWN [532]
Responsible:     UNKNOWN [479]
UID:             501
Footprint:       138.70 MB -> 3273.90 MB (+3135.20 MB)
Start time:      2019-06-13 23:10:03 +0200
End time:        2019-06-13 23:12:44 +0200
Num samples:     40 (100%)
CPU Time:        14.621s
Primary state:   34 samples Non-Frontmost App, Non-Suppressed, Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:   0 samples Idle, 40 samples Active
Power Source:    0 samples on Battery, 40 samples on AC
  40  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff67e4440d]
    40  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff67e48249]
      40  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff67e452eb]
        37  vcpu_thread + 1213 (com.docker.hyperkit + 1871990) [0x102a49076]
          24  xh_vm_run + 343 (com.docker.hyperkit + 1759971) [0x102a2dae3]
            24  vmx_run + 1718 (com.docker.hyperkit + 1722321) [0x102a247d1]
              24  hv_vcpu_run + 13 (Hypervisor + 5071) [0x7fff3e47e3cf]
          5   xh_vm_run + 1335 (com.docker.hyperkit + 1760963) [0x102a2dec3]
            5   __psynch_cvwait + 10 (libsystem_kernel.dylib + 18538) [0x7fff67d8986a]
          5   xh_vm_run + 3704 (com.docker.hyperkit + 1763332) [0x102a2e804]
            4   vmm_emulate_instruction + 3228 (com.docker.hyperkit + 1770837) [0x102a30555]
              2   vlapic_icrlo_write_handler + 498 (com.docker.hyperkit + 1746316) [0x102a2a58c]
                1   vlapic_calcdest + 205 (com.docker.hyperkit + 1746646) [0x102a2a6d6]
                  1   <User mode>
                1   vlapic_calcdest + 195 (com.docker.hyperkit + 1746636) [0x102a2a6cc]
                  1   <User mode>
              1   vlapic_write + 379 (com.docker.hyperkit + 1749087) [0x102a2b05f]
                1   vlapic_icrtmr_write_handler + 157 (com.docker.hyperkit + 1744534) [0x102a29e96]
                  1   <User mode>
              1   vlapic_icrlo_write_handler + 586 (com.docker.hyperkit + 1746404) [0x102a2a5e4]
                1   vcpu_notify_event + 104 (com.docker.hyperkit + 1756334) [0x102a2ccae]
                  1   __psynch_cvsignal + 10 (libsystem_kernel.dylib + 21954) [0x7fff67d8a5c2]
            1   vmm_emulate_instruction + 1007 (com.docker.hyperkit + 1768616) [0x102a2fca8]
              1   <User mode>
          1   xh_vm_run + 362 (com.docker.hyperkit + 1759990) [0x102a2daf6]
            1   vcpu_require_state + 15 (com.docker.hyperkit + 1756468) [0x102a2cd34]
              1   vcpu_set_state + 50 (com.docker.hyperkit + 1755430) [0x102a2c926]
                1   _pthread_mutex_firstfit_lock_slow + 222 (libsystem_pthread.dylib + 5325) [0x7fff67e434cd]
                  1   __psynch_mutexwait + 10 (libsystem_kernel.dylib + 16134) [0x7fff67d88f06]
          1   xh_vm_run + 314 (com.docker.hyperkit + 1759942) [0x102a2dac6]
            1   vcpu_require_state + 15 (com.docker.hyperkit + 1756468) [0x102a2cd34]
              1   pthread_mutex_unlock + 89 (libsystem_pthread.dylib + 5463) [0x7fff67e43557]
                1   <User mode>
          1   vmx_getreg + 0 (com.docker.hyperkit + 1730240) [0x102a266c0]
            1   <User mode>
        1   blockif_thr + 1924 (com.docker.hyperkit + 1781614) [0x102a32f6e]
          1   readv + 10 (libsystem_kernel.dylib + 131118) [0x7fff67da502e]
        1   callout_thread_func + 217 (com.docker.hyperkit + 1767299) [0x102a2f783]
          1   vlapic_callout_handler + 92 (com.docker.hyperkit + 1744908) [0x102a2a00c]
            1   vcpu_notify_event + 104 (com.docker.hyperkit + 1756334) [0x102a2ccae]
              1   __psynch_cvsignal + 10 (libsystem_kernel.dylib + 21954) [0x7fff67d8a5c2]
        1   callout_thread_func + 169 (com.docker.hyperkit + 1767251) [0x102a2f753]
          1   __psynch_cvwait + 10 (libsystem_kernel.dylib + 18538) [0x7fff67d8986a]

  Binary Images:
           0x102880000 -        0x102ac2fff  com.docker.hyperkit (0)             <71246D3E-B4F4-34BA-9BE4-201218570ACE>  /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
        0x7fff3e47d000 -     0x7fff3e481fff  com.apple.Hypervisor 1.0 (1)        <3C8DEC44-3FF8-3D20-8021-CCFA3F1E00DD>  /System/Library/Frameworks/Hypervisor.framework/Versions/A/Hypervisor
        0x7fff67d85000 -     0x7fff67dadfff  libsystem_kernel.dylib (4903.261.4) <7B0F52C4-4CC9-3282-8457-C18C6FE1B99E>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff67e42000 -     0x7fff67e4cfff  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7>  /usr/lib/system/libsystem_pthread.dylib

```

**Comment by arnavs** [comment]
This is still happening to me (Catalina, `Docker version 18.09.1, build 4c52b90`.)

Has there been any fix?

**Comment by aaronpark** [comment]
Still happening to me

- Catalina 10.15.1 Beta (19B77a)
- Docker version 19.03.2, build 6a30dfc

**Comment by kuhmuh** [comment]
I have the same problem. Just found out that everything gets "normal" if I disable Kubernetes local cluster.

- docker desktop version 2.1.0.3 (38240)
- Kubernetes v1.14.6

**Comment by sergeevpasha** [comment]
energy impact on my macbook is 136%... With no docker container is running. I have no idea what to do, starting to think to switch back to virtualbox =(
Maybe there is a manual workaround?

**Comment by arnavs** [comment]
See also https://github.com/docker/for-mac/issues/3218, which has some more info for Catalina.

**Comment by DevNaga** [comment]
would like to know whats causing the power consumption ? is it the Go's GC ?

**Comment by thellimist** [comment]
why is this closed? @samoht

**Comment by samoht** [comment]
No idea :-) I no longer work at Docker.

**Comment by MarounMaroun** [comment]
It's 202 guys, still happening.

**Comment by orthodoX** [comment]
@MarounMaroun Totally agree with you. Docker is definitely my main battery consumer, even if it's just running in the background with no containers active. I always need to turn it off when I'm on battery and not working with it. And then casual facepalms with `ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.` when I forget to turn it back on, you feel me 😅

**Comment by MarounMaroun** [comment]
@orthodoX Happens to me as well. I miss Linux, where Docker directly leverages the kernel of the host. In Mac, it starts a VM :(

**Comment by drdaz** [comment]
For a while I've been wondering if it would improve power usage to run a Linux guest on my Mac in VMware in which I run Docker. Which is convoluted and rather sad.

**Comment by horodchukanton** [comment]
P.P.S Guys in another issue have found a workaround

**Comment by orthodoX** [comment]
@horodchukanton But how did it actually impact your Docker performance when you downgraded cores to two? 🤔 I work on projects which have more than 6 services connected through docker-compose, I guess that building and executing tasks/tests in the containers will be much slower. What is your experience?

**Comment by orthodoX** [comment]
Yeah as I expected, the difference is big, really. When I run a test suite in the container for a massive rails app (around 2200 tests) when the cores are downgraded to 2, the fans start to spin on max speed right away. But when I reverted back to 6, the MacBook is silent while the tests run. So, that's not working out for me. I guess we'll just have to wait for this issue to be fixed properly by the Docker dev team 🤞
