### ISSUE TITLE
Software Update when MacBook is using battery as power source

### ISSUE THREAD

**Issue by pcgeek86** [docker/for-mac#2082]
### Expected behavior

When my MacBook Pro is using its battery as its power source, don't present the `Software Update` window.

### Actual behavior

When I'm on battery, and an update to Docker for Mac is available, the `Software Update` window pops up. I really want to confirm the update, but typically choose to prioritize battery preservation until I can get back to a charger.

### Steps to reproduce the behavior

  1. Keep a MacBook Pro running off its battery.
  2. Wait for a Docker for Mac update to come out.

Cheers,
Trevor Sullivan

**Comment by jasonbivins** [comment]
Hi @pcgeek86   I went ahead and entered this in as an enhancement request for you.


Thanks!
