### ISSUE TITLE
doesn't work on hackintosh

### ISSUE THREAD

**Issue by alexey-sh** [docker/for-mac#2086]
### Expected behavior
Launch app
### Actual behaviour
Crash
### Information

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.11.2 (build: 15C50)
logs: /tmp/73B00577-3588-4A77-B2E9-8BB1E8268B64/20170926-062709.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/alexeysh/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/alexeysh/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/alexeysh/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/alexeysh/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/alexeysh/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. download dmg, copy to apps folder
  2. launch app

**Comment by ducthinh2410** [comment]
same here

**Comment by ducthinh2410** [comment]
Hi, I fixed the problem by enabling Intel Virtualization Technology as well as VT-d in BIOS settings. Hope this helps!

**Comment by alexey-sh** [comment]
I tried virtualbox and it says "VT-x is disabled in the BIOS for all CPU modes". It seems like @ducthinh2410 right.

**Comment by ducthinh2410** [comment]
What do you mean by virtualbox? Did you install mac OS on virtual machine?

**Comment by alexey-sh** [comment]
1. download virtualbox
2. install it
3. run it
4. ???
5. got the "VT-x is disabled in the BIOS for all CPU modes"

>Did you install mac OS on virtual machine?
No.

**Comment by ducthinh2410** [comment]
Why do you have to install virtual box?

**Comment by alexey-sh** [comment]
To be sure that VT-x is disabled.

**Comment by ducthinh2410** [comment]
Intel Virtualization Technology and VT-d should be enable in order to get Docker running properly on a hackintosh(mine is 10.12.6). I think you don't have to sure VT-d/VT-x enabled as long as you have set it in your BIOS. This is how you enable Intel Virtualization Technology: https://www.youtube.com/watch?v=emKQ7MSRit8 . It might be a bit different with your BIOS. The same thing with VT-d.

**Comment by alexey-sh** [comment]
> I think you don't have to be sure VT-d/VT-x enabled

Why do you think so? Virtualbox displays the error correctly(unlike docker).

**Comment by alexey-sh** [comment]
Close since VT-x should be enabled.
