### ISSUE TITLE
Fatal error on mac

### ISSUE THREAD

**Issue by gagmgm** [docker/for-mac#2087]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
![image](https://user-images.githubusercontent.com/28021664/30949184-e9152f1c-a3e2-11e7-87a6-41b289550040.png)
