### ISSUE TITLE
docker for Mac crashed ( macOS High Sierra ? )

### ISSUE THREAD

**Issue by MacFlurry** [docker/for-mac#2091]
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A365)
logs: /tmp/759E0169-685B-49F9-BFF1-42682DC714AD/20170927-085728.tar.gz
[20170927-085728.tar.gz](https://github.com/docker/for-mac/files/1336112/20170927-085728.tar.gz)

failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/vegasus/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/vegasus/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/vegasus/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

759E0169-685B-49F9-BFF1-42682DC714AD

**Comment by clearcss** [comment]
same issue as well.  just upgraded to high Sierra.  also apart from the crash, in the middle of a running container, all of a sudden, the container is no longer running, have to restart the container. 

ID: 52EB773E-F9BF-4A28-A752-0AFB62D0FD69

**Comment by MacFlurry** [comment]
1. I uninstalled Docker for Mac
2. I reinstalled Docker for Mac .

Everything is back to normal.

**Comment by michael-younkin** [comment]
After upgrading, we see Docker for Mac crashing. We reset it and then it will startup again so it's usable, but it still crashes periodically. Containers also seem to be dying off from time to time without crashing Docker for Mac.

**Comment by qrpike** [comment]
Also seeing this only after upgrading to High Sierra. Never had this issue a single time before.

**Comment by pamelus** [comment]
Same here. I think it may be related more to APFS than to macOS by itself. On my old MacBook Pro with spinning drive, which wasn't converted to APFS, everything seems to work as expected.

**Comment by MacFlurry** [comment]
Very unstable. 
Back from standby crashed Docker for Mac.

😭😭😭😭

**Comment by steffenhaak** [comment]
Same problem here. Also starting with High Sierra Update / APFS....

**Comment by juvenal** [comment]
Same here, but I was unable to confirm the claim from @pamelus, since I don't have a machine with High Sierra and a spinning drive (the machines that I upgraded to HS, all have SSD drives, so they were migrated to APFS).

**Comment by jghankins** [comment]
Same here.  Beta and now release version.  Intermittent crashes post High Sierra Upgrade.

**Comment by akamanocha** [comment]
Same here. Does anybody got any workaround?

**Comment by asabi** [comment]
Same here. No comments on this one ?

**Comment by jsgalan** [comment]
Still not working on High Sierra, how should i procced?

**Comment by MacFlurry** [comment]
I'm using the edge version now and no more pb. :-)

thanks

**Comment by MacFlurry** [comment]
this was my issue, may I close it ?
 :-)

**Comment by jsgalan** [comment]
Sure, please proceed to close it.
