### ISSUE TITLE
Docker crashes after upgrade to High Sierra ( when awaking from sleep )

### ISSUE THREAD

**Issue by qrpike** [docker/for-mac#2095]
### Expected behavior
When I open my mac laptop docker should continue running as usual

### Actual behavior
Crashes with "com.docker.osx.hyperkit.linux failed to start. Exit code 1"

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.09.0-ce-rc3-mac30 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/379BE19F-6A1A-4A78-87ED-6240A5FDC84E/20170927-212258.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/qrpike/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/qrpike/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/qrpike/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/qrpike/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/qrpike/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

This has only happened after the upgrade to High Sierra. Possibly the filesystem change?

This is *VERY* inconvenient, hopefully it gets solved soon.

**Comment by dmitrios** [comment]
+1 same behavior here

**Comment by jasonbivins** [comment]
@qrpike @dmitrios 
Have you tried updating to the latest Edge version?

**Comment by davehun** [comment]
getting this with Docker 17.09.0-ce-rc3-mac30

**Comment by dmitrios** [comment]
The only work around from Docker fatal error when MacOS is coming up from sleep mode is to restart Docker. This worked fine before the MacOS upgrade to High Sierra.

**Comment by Jasrags** [comment]
Same here `0D86BA64-FB3E-4F84-85B0-6CFD2B084BD9`

**Comment by kallard1** [comment]
Hi,

I've the same issue `9CEF067F-A72B-478C-A181-EC3C1D83340F`

`Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A365)
logs: /tmp/9CEF067F-A72B-478C-A181-EC3C1D83340F/20170929-091717.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/allardk/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/allardk/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/allardk/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/allardk/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/allardk/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
`

**Comment by dmitrios** [comment]
This appears to be fixed in subsequent edge and stable versions.

**Comment by baronfel** [comment]
I think I'm seeing this on latest (apologies for the cross-post from another closed issue)

I run into this issue as well. The scenario is

- Connect to work VPN (we use Cisco AnyConnect)
- Start containers (in my case just running `eventstore/eventstore`)
- Sleep machine
- Wake machine
- VPN disconnects
- Containers are non-responsive and attempting restart results in the docker app crashing.

`Diagnostic ID`: `5EA8A028-1AFD-4A09-9F1C-638CADF50026`

Diagnostics Logs:
```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/5EA8A028-1AFD-4A09-9F1C-638CADF50026/20180328-101512.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/chethusk/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/chethusk/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/chethusk/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```

**Comment by phuhnGithub** [comment]
same for me. Docker crashes after waking from sleeping mode on macOs High Sierra. ID 36FFA2E0-28CA-4C2E-83CD-59E06CED5308/20190607063708
Is there any solution?
