### ISSUE TITLE
:cached volume and case-insensitive filename

### ISSUE THREAD

**Issue by Nondv** [docker/for-mac#2096]
Hello!
I have a bug to report.

I mount my project to container via docker-compose (but I guess it's not compose related):

```
volumes:
  -'.:/project:cached'
```

Let's do this:

```
echo content > Whatever
# content
docker-compose exec SERVICE_NAME cat whatever

echo 'another content' > Whatever

# content
docker-compose exec SERVICE_NAME cat whatever
# another content
docker-compose exec SERVICE_NAME cat Whatever
```

### Expected behavior

I expect caching to work with case-insensitivity:)

### Actual behavior

See the example

**Comment by thaJeztah** [comment]
The exec command is executed inside a linux container; Linux is case sensitive, so this is expected, not a bug

**Comment by Nondv** [comment]
If you are interested in my case:

I edited my `Rakefile` but rake didnt see changes.
So I looked at rake code and discovered that it looks for `rakefile` at first

**Comment by Nondv** [comment]
@thaJeztah 
you sure? I thought linux is... linux. And mounted FS is case-insensitive.

**Comment by Nondv** [comment]
https://github.com/docker/for-mac/issues/320

**Comment by Nondv** [comment]
https://docs.docker.com/docker-for-mac/osxfs/

So case-insensitivity is a feature here but caching it has a bug:)

**Comment by dsheets** [comment]
Local modifications with alternative casing don't properly expire the Linux read cache. Thanks for your report.

**Comment by Nondv** [comment]
NOOOO!
/lifecycle frozen

**Comment by Nondv** [comment]
@thaJeztah  hi!
Can you reopen this issue, please?
