### ISSUE TITLE
macOS fails to start after sleep

### ISSUE THREAD

**Issue by ogr3** [docker/for-mac#2100]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
![image](https://user-images.githubusercontent.com/28021664/31041321-4eb98910-a561-11e7-849d-64e3db549c2e.png)
