### ISSUE TITLE
docker causing sponanteous reboot of MacOS

### ISSUE THREAD

**Issue by paul94010** [docker/for-mac#2101]
### Expected behavior

Normal running of docker in MacOS

### Actual behavior

MacOS spontaneously reboots until docker is stopped.

### Information

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A365)
logs: /tmp/222949AA-98F5-4C8E-B377-C7816AE07435/20170928-173442.tar.gz
[ERROR]  db.git
         db.git check failed with: (Failure
  "exec: cd \"/tmp/222949AA-98F5-4C8E-B377-C7816AE07435/20170928-173442/database\" && git checkout master: exit 1")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

 Install MacOS 10.13 (High Sierra)

**Comment by esetnik** [comment]
I think I have the same issue but I don't have the same diagnostic error. My mac is spontaneously rebooting too and I have not reproduced this when I stop docker.

```
Docker for Mac: version: 17.09.0-ce-mac33 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/F21AE249-0660-47F4-B3FF-A9F8BF532D1F/20171003-120657.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by paul94010** [comment]
I seemed to have fixed the problem by removing the current docker,  installing the latest MacOS update (1.3 called High Sierra), and then reinstalling docker (Version 17.09.0-ce-mac32 (19506), which has a bug fix for MacOS.  Here is the new docker release summary:

### 2017-10-02 17.09.0-ce-mac32 "17.09.0-ce-mac32"

* Upgrades
  - [Docker 17.09.0-ce](https://github.com/docker/docker-ce/releases/tag/v17.09.0-ce)
  - [Docker compose 1.16.1](https://github.com/docker/compose/releases/tag/1.16.1)
  - [Docker Machine 0.12.2](https://github.com/docker/machine/releases/tag/v0.12.2)  
  - [Docker Credential Helpers 0.6.0](https://github.com/docker/docker-credential-helpers/releases/tag/v0.6.0)
  - Linux Kernel 4.9.49
  - AUFS 20170911
  - DataKit update (fix instability on High Sierra)

So far no more spontaneous reboots.

On 3 Oct 2017, at 9:09 AM, Ethan Setnik <notifications@github.com> wrote:

I think I have the same issue but I don't have the same diagnostic error. My mac is spontaneously rebooting too and I have not reproduced this when I stop docker.

Docker for Mac: version: 17.09.0-ce-mac33 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/F21AE249-0660-47F4-B3FF-A9F8BF532D1F/20171003-120657.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by akimd** [comment]
Thanks for the report!
