### ISSUE TITLE
docker requires sudo

### ISSUE THREAD

**Issue by imorti** [docker/for-mac#2102]
### Expected behavior
I used to be able to run 
```
docker run -it whatever
```

### Actual behavior
```
docker anything
```
Just hangs. I have to run 
```
sudo docker <command>
``` 

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by postmillenial** [comment]
Had the same issue. Ran ```unset DOCKER_HOST``` based on [this answer](https://stackoverflow.com/questions/40325352/why-am-i-forced-to-run-docker-with-sudo-on-os-x) and deleted the entry out of my .profile.local file and that fixed it for me.

**Comment by imorti** [comment]
Yeah was just about to comment the same thing. Thanks!
