### ISSUE TITLE
Docker installs without error, but won't run

### ISSUE THREAD

**Issue by DeCaMil** [docker/for-mac#2103]
[20170929-082424.tar.gz](https://github.com/docker/for-mac/files/1344341/20170929-082424.tar.gz)

### Expected behavior
After installation:
* the docker menu will work.
* the docker command line will work
### Actual behavior
The top level menu opens, but no menu item does anything.
The terminal reports: docker: command not found
### Information

$ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
macOS: version 10.12.6 (build: 16G29)
Docker.app: version: 17.09.0-ce-rc3-mac30 (69202b202f497d4b6e627c3370781b9e4b51ec78)
Local time: Fri Sep 29 08:24:24 EDT 2017
UTC:        Fri Sep 29 12:24:24 UTC 2017
Timestamp:  20170929-082424
Running diagnostic tests:
[ERROR]   docker-cli       cannot find docker
[ERROR]   docker-cli       /var/run/docker.sock does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /var/run/docker.sock
[ERROR]   docker-cli       /Users/dmiller/Library/Containers/com.docker.docker/Data/s60 does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /Users/dmiller/Library/Containers/com.docker.docker/Data/s60
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[ERROR]   Moby booted      /Users/dmiller/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   db               /Users/dmiller/Library/Containers/com.docker.docker/Data/s40 does not exist
[ERROR]   db               Unexpected error (No such file or directory) connecting to /Users/dmiller/Library/Containers/com.docker.docker/Data/s40
[ERROR]   db               com.docker.db is not running
[ERROR]   vpnkit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/dmiller/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/dmiller/Library/Containers/com.docker.docker/Data/s51
[ERROR]   vpnkit           com.docker.vpnkit is not running
Error docker ps: got timeout (docker ps: exit 127)
[ERROR]   disk             Docker.qcow2 missing: the VM has never been started
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Error exec: /usr/bin/log show --style syslog --last 1d | grep -i docker > "/tmp/44D9061F-77B0-4FE4-8BC5-4E38A756C04B/20170929-082424/docker-system-os.log": exit 1
Most specific failure is: Docker.qcow2 missing: the VM has never been started
Docker logs are being collected into /tmp/44D9061F-77B0-4FE4-8BC5-
[20170929-082424.tar.gz](https://github.com/docker/for-mac/files/1344335/20170929-082424.tar.gz)
4E38A756C04B/20170929-082424.tar.gz
Your unique id is: 44D9061F-77B0-4FE4-8BC5-4E38A756C04B
Please quote this in all correspondence.
[29-09-17@08:24:37] dmiller@Devons-Macbook ~
$ echo $?
2
### Steps to reproduce the behavior
I downloaded the Mac stable Docker.dmg
No errors were displayed during the install.
The icon appears in the menu bar and the top-level menu displays, but nothing else works.

So far, I have tried:
* Updating Virtual box (5.0.30 to 5.1.29)
* Uninstalling Docker, rebooting and installing Docker Edge
* Rebooting again

**Comment by alotufo** [comment]
This was the solution for me. The /usr/local/bin was a file not a directory.

https://github.com/docker/for-mac/issues/1453#issuecomment-288416400

**Comment by DeCaMil** [comment]
Thanks @alotufo that pointed me in the right direction.
/usr/local/bin was a directory, but the mode was 0700 and my account was not the owner.
I changed the mode to 0755 and Docker is working.

The installer should probably check the permissions on /usr/local/bin and issue a warning if it's not readable/traversable by the user running the installer.
