### ISSUE TITLE
fails to start docker Incompatible CPU detected.

### ISSUE THREAD

**Issue by rogerwilco3** [docker/for-mac#2105]
### Expected behavior
Running but not yet configured 
### Actual behavior
Fatal Error
Incompatible CPU detected.

Docker requires a processor with virtualization capabilities.

To learn more about this issue see:

### Information
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.10.5 (build: 14F2511)
logs: /tmp/57908263-3C12-440C-B435-FB17F8869F4D/20170930-180623.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/images/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/images/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/images/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/images/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/images/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/images/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/images/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. in system information 
Hypervisor:

  Versie:	1,0
  from:	Apple
  Latest update:	30-09-17 00:33
  Soort:	Intel
  64-bits (Intel):	yes
  Ondertekend door:	Software Signing, Apple Code Signing Certification Authority, Apple Root CA
  Location:	/System/Library/Frameworks/Hypervisor.framework
  Privaat:	Nee
  2.   Modelnaam:	iMac
  Model:	iMac10,1
  Processorname:	Intel Core 2 Duo
  Processorspeed:	3,06 GHz
  Processors:	1
  Totaal cores:	2
  L2-cache:	3 MB
  memory:	4 GB
  Busspeed:	1,07 GHz
  Opstart-ROM-versie:	IM101.00CC.B00
  SMC-version (system):	1.52f9

**Comment by djs55** [comment]
Thanks for your report.

It seems that your macOS kernel doesn't have hardware virtualisation enabled according to
```
sysctl -a | grep 'kern.hv_support:'
```
This could be because your hardware is too old, or perhaps the machine is running in safe mode?

Unfortunately Docker for Mac requires macOS to have hardware virtualisation enabled and so the error message is expected. You can still run `docker` in a VM using virtualbox/VMware fusion -- take a look at [Docker toolbox](https://docs.docker.com/toolbox/toolbox_install_mac/)
