### ISSUE TITLE
Some stranger thing happening after updated OSX to High Sierra

### ISSUE THREAD

**Issue by anzileiro** [docker/for-mac#2107]
### Expected behavior
DIAGNOSTIC ID 51D902F8-1159-4F3E-98BB-02E788FBB22F
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

I really don't know what's happening. I just updated OSX to High Sierra. Shit!

Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A365)
logs: /tmp/51D902F8-1159-4F3E-98BB-02E788FBB22F/20170930-221932.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  db.git
         db.git check failed with: (Failure
  "exec: cd \"/tmp/51D902F8-1159-4F3E-98BB-02E788FBB22F/20170930-221932/database\" && git checkout master: exit 1")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/anzileiro/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/anzileiro/Library/Containers/com.docker.docker/Data/s40: check if service is running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/anzileiro/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/anzileiro/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/anzileiro/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

<img width="1280" alt="screen shot 2017-09-30 at 23 35 10" src="https://user-images.githubusercontent.com/3415671/31051197-29a7b732-a638-11e7-802a-1e9498e3e1f9.png">

**Comment by kgrachev96** [comment]
9CDF2B87-0F40-4EB0-853D-36AEE4AAAB36

**Comment by nxmohamad** [comment]
Have you tried Uninstalling then reinstalling Docker?

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
