### ISSUE TITLE
Failed to set up pidfile

### ISSUE THREAD

**Issue by davidcittadini** [docker/for-mac#2109]
System was working well on macOS and then suddenly when I run `linuxkit run linuxkit` I get the following:

Failed to set up pidfile
pidfile error -1
FATA[0000] Cannot run hyperkit: exit status 1

I have:
- Deleted Docker.qcow2
- Reset
- Reinstalled
- Installed latest Stable and Edge versions

Nothing fixes this.

**Comment by inge4pres** [comment]
Hi @davidcittadini same just happened to: I fixed it deleting the `IMAGENAME-state` folder created by HyperKit alongside the images built by moby and re-launching `linuxkit run ...`

**Comment by inge4pres** [comment]
Confirmed on a second image 😃 try it out

**Comment by davidcittadini** [comment]
That works 😃 . Well done!!

**Comment by inge4pres** [comment]
@davidcittadini you can close this issue

**Comment by sjtindell** [comment]
For others who find this, if you're using a specific IP with your instance, be sure to move the uuid.vpnkit file out then delete the state directory, move it back it, and then do linuxkit run.
