### ISSUE TITLE
Container migration not working when updating to 17.09.0

### ISSUE THREAD

**Issue by tobiasorth** [docker/for-mac#2111]
### Expected behavior
All existing containers are copied

### Actual behavior
Only the latest containers used are copied

### Information

When updating from 17.03.? to Version 17.09.0-ce-mac32 (19506) the migration of old containers isn't working as intended. After getting asked if the containers should be copied the process succeeds only migrating the last used containers.

```
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/9A0840B6-C754-4B79-B614-AFC63ACB0C42/20171002-133547.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by grantila** [comment]
#2118 and #2113 are related and/or duplicates.

**Comment by daddytli** [comment]
In my case, nothing is copied and is as if I just installed the product and **did not** click on copy.
