### ISSUE TITLE
Docker doesn't start after last update

### ISSUE THREAD

**Issue by jean-felipe** [docker/for-mac#2112]
### Expected behavior
Start docker

### Actual behavior
I am using mac sierra, after last update on docker ir does not start.

### Information
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/CA8230EC-D1DB-4C0E-A962-ED7E97B3D997/20171002-090259.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/beautydate/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/beautydate/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/beautydate/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/beautydate/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/beautydate/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. Just applied last update
  2. try to start.

**Comment by tylerrichey** [comment]
Same issue, same versions for me. Tried a factory reset and the edge version and still no luck getting it started after update.

**Comment by jean-felipe** [comment]
I think that is not the best solution, but i'd installed an older version from this link: 
https://download.docker.com/mac/stable/1.12.6.14937/Docker.dmg 
as suggested in #1600

**Comment by petersondmg** [comment]
Same here

**Comment by jean-felipe** [comment]
guys, i found a solution, download this edge version:
https://download.docker.com/mac/edge/18207/Docker.dmg
as #1669 , that old version not work for me.

**Comment by pure4499** [comment]
I have same issue. 
Cannot start service smbp-web1: driver failed programming external connectivity on endpoint docker_smbp-web1_1 (2d0af66828382e0479379f1850b8b79dd9af132c3fbc8a898738f814640262ab): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

ERROR: for docker_smbp-web1_1  Cannot start service smbp-web1: driver failed programming external connectivity on endpoint docker_smbp-web1_1 (ab5badd430883b4150d1a2c92705cb346d00df058397ee3a2fd65a57a26b151a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

**Comment by jean-felipe** [comment]
The new updates fixed the problem, i will close the issue.
