### ISSUE TITLE
Migration to 17.09.0-ce-mac32 did not copy existing containers

### ISSUE THREAD

**Issue by daddytli** [docker/for-mac#2113]
### Expected behavior
All existing containers are copied

### Actual behavior
No containers were copied.

### Information

  Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/D3CE39EB-BC6F-42D8-AF92-95D1A0B8FE7B/20171002-135503.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install docker update
  2. Select "Copy"
  3. docker ps -a (no containers found)
  4. docker images (no images exist)

**Comment by daddytli** [comment]
I have Time Machine backup. Is there a way to restore my old image/containers?

**Comment by ThirstyMelonSeed** [comment]
@daddytli Much too late, but maybe if someone else comes across a similar issue.  If ever you lose all your images or containers, the thing you want to restore from Time Machine is the docker vm.  Path is "/Users/USERNAME/.docker/machine/machines".  I restored the "default" machine and ta-da!
