### ISSUE TITLE
docker run with bind mounts prints wrong error with --mount for unpermitted directories

### ISSUE THREAD

**Issue by slpsys** [docker/for-mac#2114]
### Expected behavior
`docker run ... --mount type=bind,source=/data,target=/data`, for a directory that is *not* permitted via Docker for Mac's File Sharing settings, should print the informative message about File Sharing that is emitted when running the equivalent command via `-v`. The command using `-v` yields:

```
docker: Error response from daemon: Mounts denied:
The path /data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

Which makes the problem, and the solution, obvious.

### Actual behavior

Running the above command with `--mount` yields:
```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist.
See 'docker run --help'.
```

This is not only less informative, but misleading, given that the same error is emitted when binding to paths that _do_ and do not exist on the host.

### Information

  - This is discussed [in more detail in an issue I opened in the main docker repo](https://github.com/docker/docker.github.io/issues/4709).
  - This doesn't appear to be specific to any particular Dockerfile, any `docker run` command should do
  - I also found it somewhat misleading that the [bind mounts documentation](https://docs.docker.com/engine/admin/volumes/bind-mounts/) includes the line `The file or directory does not need to exist on the Docker host already`, which is described later to only the case for `-v` and not `--mount`. That the behavior is qualified later is fine, but the original sentence is a topic sentence, and unqualified, which makes it misleading, in my opinion.

### Steps to reproduce the behavior

  1. Pick a directory that is *not* set up for File Sharing in the Docker for Mac settings.
  2. Run `docker run` with a `--mount type=bind,source=/data,target=/data` option, where `/data` is an example of a directory not in File Sharing settings.

As an example, I was running this:

```
docker run -d \
  -it \
  --rm \
  -p 8888:8888 \
  --name exploratorium \
  --mount type=volume,source=exploratorium,target=/exploratorium \
  --mount type=bind,source=/data,target=/data \
  IMAGE_NAME
```

**Comment by gabrielgradinaru** [comment]
I am facing this issue and wasted about an hour due to wrong error message.
Not sure if relevant but I also got this error when running:
 `docker stack ps --no-trunc getstartedlab`
