### ISSUE TITLE
docker-17.09 not working. BLOCKER......

### ISSUE THREAD

**Issue by sappalaneni2** [docker/for-mac#2115]
This is Frustrating as I can't use latest stable 17.09. and I can't download older versions of Docker to continue  my work. 

### Expected behavior
After downloading stable version of docker 17.09 CE for MAC, when I deploy a stack all the services listed in YAML file should be starting. 

### Actual behavior
But all the services are struck in pending state.

### Information
when I run docker inspect <taskID>, this is what I see in "status"

        "Status": {
            "Timestamp": "2017-10-02T20:12:12.660081869Z",
            "State": "pending",
            "Message": "missing plugin on 1 node",
            "ContainerStatus": {},
            "PortStatus": {}
        }

I have not installed any plugins on my Docker for mac.

### Steps to reproduce the behavior
download docker for mac 17.09.0-ce
deploy a stack.
Services goes into pending state.

**Comment by djs55** [comment]
I attempted to reproduce this on
```
Version 17.09.0-ce-mac32 (19506)
Channel: stable
cb86d843ba
```
but failed. I cloned https://github.com/dockersamples/example-voting-app then created a swarm and then ran `docker stack deploy --compose-file docker-stack.yml vote`. I now have:
```
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                          PORTS
w593nbw5tvi7        vote_db             replicated          1/1                 postgres:9.4                                   
xy46v8hxkmnr        vote_redis          replicated          1/1                 redis:alpine                                   *:30000->6379/tcp
xv7s56gok4r5        vote_result         replicated          1/1                 dockersamples/examplevotingapp_result:before   *:5001->80/tcp
q80v1fszsgti        vote_visualizer     replicated          1/1                 dockersamples/visualizer:stable                *:8080->8080/tcp
rwkflwzta33p        vote_vote           replicated          2/2                 dockersamples/examplevotingapp_vote:before     *:5000->80/tcp
106epl4wb3tk        vote_worker         replicated          1/1                 dockersamples/examplevotingapp_worker:latest   
```
and the app appears to be working.

Could you share a cut-down version of your app which demonstrates the problem? Could you also upload diagnostics (Whale menu -> Diagnose and Feedback ... Diagnose & Upload) and quote the diagnostics id here?

Thanks for your report!

**Comment by sappalaneni2** [comment]
Diagnostic ID:
-------------
4B1AB972-2563-4892-ADA1-C4F9F72E1150

Sorry, I forgot to mention this version info earlier:

DockerVersion 17.09.0-ce-mac31 (19478)
Channel: edge
ff8d09a229

**Comment by sappalaneni2** [comment]
I am not having issue with docker-stack.yml from example-voting-app. But I am still having same issue with my yaml file. we are using overlay network with encryption. here i out network config.
```

networks:
    agility:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: "10.0.1.0/24"
        driver_opts:
            encrypted: "true"
```

**Comment by sappalaneni2** [comment]
I've tried the same thing with "Stable" version. result is similar.  here is info with stab;e version.

```
Docker Version 17.09.0-ce-mac33 (19543)
Channel: stable
e2f2204fde
```
From Docker inspect <taskid>

```
"Status": {
            "Timestamp": "2017-10-03T16:47:54.571978937Z",
            "State": "pending",
            "Message": "no suitable node (missing plugin on 1 node)",
            "ContainerStatus": {},
            "PortStatus": {}
        }
```

Diagnostic ID: 4B1AB972-2563-4892-ADA1-C4F9F72E1150
-------------

**Comment by hallvar** [comment]
I have the same issue on the same version:
Version 17.09.0-ce-mac33 (19543)
Channel: stable
e2f2204fde

Additionally I have the same issue on latest docker-ce package for Ubuntu 16.04 (17.09). Running in an Azure VM.

**Comment by sappalaneni2** [comment]
I've just figured out that the following config is causing the issue.

```
        logging:
            options:
                max-size: "1g"
                max-file: "5"
```

**Comment by hallvar** [comment]
I can confirm that this also caused the issue on my side. When the entire logging section was removed and I redeployed the stack then the containers started as normal.

I also tried to explicitly set "driver: json-file", and also "driver: journald", but still had the same issue as before.

**Comment by sappalaneni2** [comment]
it is working for me when I explicitly set driver: "json-file"

```
        logging:
            driver: "json-file"
            options:
                max-size: "1g"
                max-file: "5"
```

**Comment by hallvar** [comment]
Ah, indeed, I must have put the driver section under options. Thank you for the work around!

**Comment by kostasns** [comment]
Can confirm this worked for me as well. 
after adding logging driver was able to start services successfully.

**Comment by pgilad** [comment]
What a weird bug! I can also confirm the exact same solution (adding `driver: 'json-file` to logging) solved the issue for me as well.

Besides solving this weird issue, I think there should also be a better way to debug this, the mysterious `missing plugin on 1 node` was not helpful at all discovering which plugin was missing (I suspect the default logging driver has changed or was empty)

**Comment by leonardseymore** [comment]
Woooooo! Thanks a mil. This workaround worked on Ubuntu aswell. I wouldve never figured it out. Thanks
