### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by awesomejerry** [docker/for-mac#2117]
### Expected behavior
Start docker daemon

### Actual behavior
Docker is always starting.

### Information

```
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/1CEA1F9B-22E1-48EA-AC89-BB2F7ECA7915/20171003-112611.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

Diagnostic ID: 1CEA1F9B-22E1-48EA-AC89-BB2F7ECA7915

### Steps to reproduce the behavior

Start Docker.app

**Comment by nodesocket** [comment]
Also seeing this upon upgrading to latest version of Docker for Mac on iMac Mid 2010 running High Sierra `10.13`.

```
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/10AA16C3-2273-4534-B55F-E0024D1A09C9/20171002-204044.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/justin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/justin/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/justin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/justin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/justin/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

**Comment by vbkunin** [comment]
I have the same on iMac Mid 2010 with Sierra 10.12.6.
Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
Diagnostic ID: CE9A0474-C075-4659-9E67-090364F77235

**Comment by gtardif** [comment]
Hi @vbkunin, @nodesocket, We're having a hard time reproducing his bug, but we might have a fix based on the info in the logs ; could you try to install this version and let me know if this works better : 
https://download.docker.com/mac/stable/19597/Docker.dmg
(@awesomejerry I think you problem is different, sorry if this does not fix your case at the moment)

**Comment by nodesocket** [comment]
@gtardif that new build https://download.docker.com/mac/stable/19597/Docker.dmg worked. Quick question, is that a stable build? If I run that will I continue to get updates?

**Comment by awesomejerry** [comment]
Right, the new build doesn't work for me. Is there anyway to delete all docker-related files (containers, images, volumes and network...) so that I can give it a new installation?

**Comment by gtardif** [comment]
@nodesocket Thanks for he feedback. Yes in this case, this was a release candidate so you should continue to get updates on the stable channel. We just released a fix today.

**Comment by gtardif** [comment]
@awesomejerry you can try to delete : 
```
~/.docker
~/Library/Containers/com.docker.docker
~/Library/Group\ Containers/group.com.docker
~/Library/Caches/com.docker.docker
/Library/PrivilegedHelperTools/com.docker.vmnetd```

**Comment by vbkunin** [comment]
Hi @gtardif! I've just updated to 17.09.0-ce-mac35 and seems it works fine. Thanks!

**Comment by awesomejerry** [comment]
@gtardif After a new clean installation, it works again!

**Comment by logicminds** [comment]
I click the upgrade button and now Docker will not start.


```
Version 17.09.1-ce-mac42 (21090)
Channel: stable
3176a6af01

```

**Comment by rbiq** [comment]
I downloaded the latest version for mac last night and was stuck on docker is starting... I've tried it several times  to reinstall however in vain. Can anyone help me understand what is going on?

**Comment by param0091** [comment]
Hi @gtardif 
 I have installed docker stable on mac OS X 10.13.3 and my container exit automatically with error 255.

i Have my custom server image which is working fine on OS X version 10.13.2 and lower but not working on 10.13.3 , When i am trying to start the container it exit automatically with error 255. Is there any solution to get rid off this issue. Docker Info -: Version 17.12.0-ce-mac49 (21995) Channel: stable f50f37646d . Also i have attached my custom DockerFile
Dockerfile.txt

and these are the commands Im executing

1. docker load -i server.tar

2. docker run -d --name name_your_container -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=P@55w0rd' -e 'MSSQL_PID=Developer' -p 1433:1433 server

3. docker cp /Users/param/Desktop/bak/AdventureWorks2012.bak jklaws:/tmp/

4.docker exec jklaws /opt/mssql-tools/bin/sqlcmd -U sa -P P@55w0rd -Q "RESTORE DATABASE [AdventureWorks2012] FROM DISK='/tmp/AdventureWorks2012.bak' WITH MOVE 'AdventureWorks2012_Data' TO '/var/opt/mssql/data/AdventureWorks2012_Data.mdf', MOVE 'AdventureWorks2012_log' TO '/var/opt/mssql/data/AdventureWorks2012_log.ldf' "

Also some times command 1 fails with error like (diff in layer 15 sum is 23424757 should be 3248935897 ) and the 4th command failed as well (error-: restore detected an error on page 1213424 in database as read from the backup set )

Earlier all these commands are working fine in OS X lower that 10.13.3

Let me know if i have to change anything.
Thanks

**Comment by balaji-b-v** [comment]
i had accidentally deleted the /private/vars/tmp folder. And then had pulled few Sierra updates. After that docker wouldnt start.

steps that helped resolve this.
1) create /tmp folder in /private/vars
2) chmod 777

5) rm -rf ~/.docker
6) rm -rf ~/Library/Containers/com.docker.docker
7) rm -rf ~/Library/Group\ Containers/group.com.docker
8) rm -rf ~/Library/Caches/com.docker.docker
9) sudo rm -rf /Library/PrivilegedHelperTools/com.docker.vmnetd
10) brew update && brew upgrade docker-clean
11) brew doctor - this gave few instructions reg missing dependencies 
12) installed those dependencies
13) export HOMEBREW_TEMP=/tmp
14) brew update
15) brew missing - this gave indication on world read/write on /tmp
16 ) sudo chmod +t /tmp - to adjust the correct permission on tmp folder
17) brew prune
18 ) brew cask install docker
19) brew doctor - this indicated missing python@2
20) brew install python@2

and docker started correctly after a number of restarts.

**Comment by akilanarasu1994** [comment]
@gtardif 's answer works! I think it was just a matter of deleting the ~/Library/Caches/com.docker.docker and /Library/PrivilegedHelperTools/com.docker.vmnetd

Needed this as I renamed the home folder on my Mac. Tested on macOS High Sierra 10.13.3.
Thanks @gtardif

**Comment by chrisleekr** [comment]
@akilanarasu1994 

Thank you. 

`sudo rm -r ~/Library/Preferences/com.docker.docker.plist` worked for me.

**Comment by YRM64** [comment]
Thanks to all who contributed to this thread 👍🏼

**Comment by andyfischer** [comment]
Hi all, I had this same issue using version Version 18.03.1-ce-mac65 (24312)

I deleted the files mentioned but this command did NOT fix it for me:

    sudo rm -rf ~/.docker ~/Library/Containers/com.docker.docker ~/Library/Group\ Containers/group.com.docker ~/Library/Caches/com.docker.docker /Library/PrivilegedHelperTools/com.docker.vmnetd

There was another folder that I needed to delete (I found this folder by running `opensnoop`). Deleting this folder DID fix it for me:

    sudo rm -rf /var/folders/kb/4cxq1c355qg06zjbgzd78hmw0000gp/C/com.docker.docker

I don't know if that filename would be the same for everyone. Hope that helps someone

**Comment by Jasonyou1995** [comment]
Thanks a lot the `sudo rm -r ~/Library/Preferences/com.docker.docker.plist` perfectly solved my problem ;)!

**Comment by oliverjar** [comment]
Go to the activity monitor and manually quit the docker process and try to re run docker instance again. This is the only thing that worked for me.
