### ISSUE TITLE
Images and Containers are not copied after upgrade to 17.09.0

### ISSUE THREAD

**Issue by umedjan** [docker/for-mac#2118]
### Expected behavior
All existing containers and images copied

### Actual behavior
No existing images and containers copied

### Information

Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/6A608D89-AFD8-411F-9DFA-570398A6DD64/20171003-102502.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Upgrade docker
  2. Press "Copy"

**Comment by grantila** [comment]
In my case, I has images and containers I use regularly, but I also have old "docker machine" images laying around. My new ones are replaced with the old ones. This is a massive data loss. I **certainly** hope docker didn't remove them permanently. This is a **serious** bug.

**Comment by fabm22** [comment]
I +1 this. Also, there is *some* containers/images still accessible in the form of a renamed .bkp file as you can see in this image:
<img width="693" alt="docker upgrade" src="https://user-images.githubusercontent.com/143132/31118245-0c7fb64a-a82d-11e7-86e6-834812eacf46.png">

Renaming it removing the .bkp provided access to *some* old images back.

**Comment by ThirstyMelonSeed** [comment]
Exact same situation here as @grantila
