### ISSUE TITLE
update to 17.09.0-ce-mac32 (19506) custom image location lost and image/containers/volume data loss

### ISSUE THREAD

**Issue by pyseed** [docker/for-mac#2119]
### Expected behavior

keep using custom disk image location and images/containers after update

### Actual behavior

after update, previous custom disk image location is reset to default Libray path /Users/[user]/Library/Containers/com.docker.docker/Data/com.docker.driver.amd

no idea if previous disk image at custom location was updated, indeed file modification date was update

clicking move disk image AND 'use it' (not replace) and docker ps -a still display no containers
images and containers appear to be lost

### Steps to reproduce the behavior

  1. image in a custom location (external disk)
  2. update docker for mac
  3. docker ps: no container
  4. preferences, advanced tab, disk location is reset to default Libray path
  5. move disk image, select previous custom image + use it
  6. docker ps -a not any container
  7. docker images: no images

**Comment by pyseed** [comment]
after i have tested 'replace it' instead 'use it' to recreate a new fresh disk image, file was not reset (keeps size of previous disk location) 

if you try to set in another new path to force a fresh disk image location, there is a popup error (“Docker.qcow2” couldn’t be removed.)

**Comment by mathieubodin** [comment]
Hi,
Same issue for me.
The worst is that I manage to recover my custom disk image by removing the newest a copying the older. It's the only "fast" way I found to start working.
It's an annoying waste of time and disk space. Next update, I'll wait until the migration job is done properly.

**Comment by pyseed** [comment]
Hi, 

Update to Version 17.09.0-ce-mac33 (19543) Channel: stable
(have seen "Do not show Toolbox migration assistant when there are existing Docker For Mac data" in changlog)

for info,

disk image location still reset to /Users/[user]/Library/Containers/com.docker.docker/Data/com.docker.driver.amd
after update

back to custom location + 'use it' OK, do not loss data rebuild yesterday, containers functional.

**Comment by pyseed** [comment]
hi,

for info since
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c

my previous lost images/containers/volumes are back by selected custom location again + use it after 17.09.0-ce-mac35 (19611) update. So many thanks!
