### ISSUE TITLE
"docker pull" and "docker login" command failed ,When logging in the Docker ID(Using High Sierra 10.13.0)

### ISSUE THREAD

**Issue by ytooyama** [docker/for-mac#2124]
Docker for mac on High Sierra,
"docker pull" and "docker login" command failed ,When logging in the Docker ID(Using High Sierra 10.13.0).

### Expected behavior
Docker for mac are good work on the High Sierra

### Actual behavior
But not work ,When logging in the Docker ID.

### Information

```
Docker for Mac: version: 17.09.0-ce-mac33 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/2AF508E6-9ABB-41FE-947A-E2DB0E99E927/20171004-094014.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Sign in Docker ID on "Docker for mac" , Also not Sign in Error.
  2. Using docker command or Kitematic , then This error.

```
% docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: unauthorized: incorrect username or password
```
  3. Log Out the Docker ID
  4. Using docker command or Kitematic , then successful .

```
% docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
88286f41530e: Pull complete 
Digest: sha256:f006ecbb824d87947d0b51ab8488634bf69fe4094959d935c0c103f4820a417d
Status: Downloaded newer image for alpine:latest
```

**Comment by ytooyama** [comment]
Sorry, When Using Docker ID (Not Email address) then docker command successful .
https://github.com/docker/hub-feedback/issues/935

**Comment by kingbuzzman** [comment]
@ytooyama close the issue then. :P
