### ISSUE TITLE
New Install - Failure to Start

### ISSUE THREAD

**Issue by brundlemac** [docker/for-mac#2126]
### Expected behavior
Starting Docker for Mac for the first time I expected it to run

### Actual behavior
Started the initialisation process after I'd entered my password. A dialog was displayed showing:
Fatal Error
com.docker.osx.hyperkit.linux failed to start
Exit code 1

### Information
Diagnostics Id: 27E008F8-BC01-4322-98FE-F111373F948C

Diagnostic output:
Docker for Mac: version: 17.09.0-ce-mac31 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/27E008F8-BC01-4322-98FE-F111373F948C/20171004-152148.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/pjmitchell/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/pjmitchell/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/pjmitchell/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/pjmitchell/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/pjmitchell/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

Install latest Docker for Mac from the website (either stable or edge behaves the same). 
Open DMG and drag app to Applications. 
Run Docker.app. 
While initialising, enter password as requested.
thinks about things for a bit
Failure dialog shown

Same behaviour for both the Stable and Edge versions. Resetting results in the same error when reinitialising.

**Comment by EricSites** [comment]
I am having the same issue. I think it started after a Visual Studio code update or a Docker update.

**Comment by buliverd53** [comment]
Same problem here...

**Comment by gtardif** [comment]
This should be fixed with the latest version (17.09.0-ce-mac34 on edge channel, mac35 on stable channel)
