### ISSUE TITLE
Docker crash on macOS Beta 3

### ISSUE THREAD

**Issue by ruifilipeasilva** [docker/for-mac#213]
### Information

Diagnostic ID: BE66D145-6FA8-45C5-B98A-D15DE16BC4E7
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ruifilipesilva/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Open Docker and wait for the service start
2. Before it was ready, show the errors

**Comment by sanshilei** [comment]
Same as you do

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
