### ISSUE TITLE
"docker-credential-osxkeychain": executable file not found (17.09.0 mac33)

### ISSUE THREAD

**Issue by hyperknot** [docker/for-mac#2131]
### Expected behavior
"docker login" should work without storing in keychain

### Actual behavior

```
error getting credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: ``
```

### Information

```
Docker for Mac: version: 17.09.0-ce-mac33 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/589E492D-E0B3-43CC-91C3-1BC01E5CE929/20171006-125426.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostic ID: 589E492D-E0B3-43CC-91C3-1BC01E5CE929

### Steps to reproduce the behavior

1. install Docker for Mac
2. log in
3. pull doesn't work for specific repos
4. uncheck "Securely store docker logins in macOS keychain"
5. try log in, receive error message

**Comment by hyperknot** [comment]
OK, what triggers it seems to be the first login, which is stored in keychain.

If I do:
1. full reset
2. disable store in keychain
3. log in
It works.

**Comment by n4ss** [comment]
@hyperknot this is not a proper fix as it disables secure credentials storing. Did you install docker4mac through `brew` or our website? I think I saw an issue where brew was installing `docker-credential-osxkeychain` wrong. Can you check that you have the binary at  `$HOME/Library/Group Containers/group.com.docker/bin/docker-credential-osxkeychain` ?

**Comment by pgensler** [comment]
@n4ss  I am having the same issue, except when I go to login to GitLab

docker login registry.gitlab.com

 I get this error:
```
`error getting credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: ```
```

When I try to go into the folder you specified, I can't open the docker-credential-osxkeychain file.
I just re-installed Docker yesterday, so maybe my keys are not setup properly?
![image](https://user-images.githubusercontent.com/7308115/32072297-b14cd716-ba57-11e7-8233-ae6f14d6a7d6.png)

**Comment by n4ss** [comment]
@pgensler no, Docker Toolbox is a legacy app. Please use Docker4Mac

**Comment by pgensler** [comment]
@n4ss why is Docker Toolbox considered legacy? I use Docker quickstart terminal all the time, and it seems like it's no longer included in Docker4Mac? 

When I tried to click on the files(10/26), it said the files were aliases, and asked me to point to where the real file lived on my machine. Now (10/27), when I click on the files, I get pointed to this:
![image](https://user-images.githubusercontent.com/7308115/32122626-9eec0a22-bb26-11e7-92ce-2face69e8c81.png)

 
I'm pretty sure that's where my password is being stored, as when I go into Keychain Access, search for docker, I get this: 
![image](https://user-images.githubusercontent.com/7308115/32122028-9caf22c8-bb24-11e7-8995-9c58d94eea2e.png)
which corresponds directly to the file above : "docker-credential-osxkeychain"

Yesterday, I fixed this by deleting the lines:

```
,
"credsStore" : "osxkeychain"
```
from  ~/config.json in that folder. This is what my ```config.json``` looked like:
```
{
{
	"auths": {
		"https://index.docker.io/v1/": {

		}
	}
}
```
 and I was able to login to gitlab using :


```
docker login registry.gitlab.com
```
Now, trying to login to Gitlabs, I'm able to using:
docker login registry.gitlab.com -u petergensler -p <my_pw>
and my docker ```config.json``` looks different:

{
	"auths": {
		"https://index.docker.io/v1/": {},
		"registry.gitlab.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.09.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}



However, I tried installing the Docker4Mac earlier, and I was asked to update, and I get this error now:


![image](https://user-images.githubusercontent.com/7308115/32122279-70aad96e-bb25-11e7-9fdc-334345afcce7.png)

**Comment by lovepocky** [comment]
i meet the same error. 
and resolved by 
`brew install docker-credential-helper`
hope this helps

**Comment by iromeo** [comment]
`docker login` works ok on my machine,  MacOS 10.13.1,  Docker version 17.09.0-ce, build afdb6d4

**Comment by secangkirkopipanas** [comment]
Faced same issue, but the solution from @lovepocky saved my life.

**Comment by navidwang** [comment]
the way @lovepocky post works for me!

**Comment by jamiethompson** [comment]
Fresh install - had this issue. The solution offered by @lovepocky solved this for me.
