### ISSUE TITLE
Cannot connect to the Docker daemon at tcp://192.168.64.2:2376. Is the docker daemon running?

### ISSUE THREAD

**Issue by paul-hammant** [docker/for-mac#2132]
### Expected behavior

Docker to connect to daemon, given the little Whale is up in the menu bar (MacOS 10.12.6) and "running". 

### Actual behavior

(in terminal) Cannot connect to the Docker daemon at tcp://192.168.64.2:2376. Is the docker daemon running?

### Information

Diagnostic ID: 2A88D3DA-9B10-4821-B432-E990A954D8E5

This is a new Mac. Docker wasn't on it. It was on my old Mac, and I had used TimeMachine to move documents to this mac, but chose to homebrew reinstall what I could in preference to TM moving apps.

### Steps to reproduce the behavior

Pretty much anything but `docker pull hello-world` will suffice.

### Attempts to self-help

1. No, I'm not running a firewall - I just double checked.
2. Tried the script at https://github.com/docker/toolbox/blob/master/osx/uninstall.sh before reinstalling.
3. Read every issue here that started "Cannot connect to the Docker daemon"
4. As #3 but "Is the docker daemon running?" - a similar result set
5. Tried to find a canonical page for this but could not.
6. Tried to telnet to `telnet 192.168.64.2 2376` but could not.

**Comment by bschwartz757** [comment]
Having the same issue here - suddenly started having issues with Docker while working on a minikube project (seemed like the issues started soon after installing a recommended upgrade to minikube v0.23.0). After uninstalling/re-installing with homebrew, I can't login to docker or run `docker info`. The docker app *appears* to be running fine, but I noticed on the Advanced tab it lists `Docker subnet: 192.168.65.0/24` - could that be a clue?

**Comment by thaJeztah** [comment]
Docker for Mac does not use a tcp connection to the daemon, but connects using a socket (/var/run/docker.sock); check if there's no `DOCKER_HOST` environment variable set in your shell that overrides the default connection.

**Comment by bschwartz757** [comment]
Ah thank you - I'll check that. I'm also thinking this could be a bug with the latest version of minikube.

**Comment by paul-hammant** [comment]
Problem went away for me after upgrading MacOS to High-Sierra and reinstalling XCode in order to be able to refresh HomeBrew

**Comment by bschwartz757** [comment]
@thaJeztah I ended up filing a [bug report](https://github.com/kubernetes/minikube/issues/2180) with Kubernetes after much troubleshooting failed to resolve the issue. Interestingly, `/var/run/docker.sock` now appears to be empty (It says "permission denied" even when I try to sudo vim it, but is empty.) I've now uninstalled and re-installed Docker several times (tried using homebrew, which only made matters worse, and the docker toolbox installation I unwittingly created by running `docker-machine create default`. I have Docker for Mac re-installed and working fine on my desktop, as well as Minikube, but when I try to pull images from Docker Hub inside the minikube context I get the same error I experienced before:
```docker pull hello-world                                                                        
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

**Comment by thaJeztah** [comment]
Hm, yes, that sounds like something with minikube. t.b.h. not entirely sure how they set up things.

**Comment by krmayankk** [comment]
it seems minikube overrides the default docker settings by setting these three variables
```
DOCKER_HOST=
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/some/certs
```
I unset these and stopped `minikube stop` and that did the trick and docker for mac started working
