### ISSUE TITLE
Unexpected Storage Size inside Docker container on Mac OS X 10.13

### ISSUE THREAD

**Issue by der-onkel** [docker/for-mac#2136]
### Expected behavior
Expect the same  results for syscall.Statfs native on Mac OS X and inside Docker container

### Actual behavior

Native on Mac OS X 10.13
```
Max OS X Total:    244093681664
Max OS X Free:      82487795712
```
Inside Docker on Mac OS X 10.13
```
Docker Total:   249951930023936
Docker Free:     84383058886656
```
### Information

**Example Code**
```golang
package main

import (
    "fmt"
    "syscall"
)

func main() {
    // Path inside docker container
    path := "/mnt"
    // Path on Mac OS X
    //path := "/Users/dukat/Desktop/minio"
    s := syscall.Statfs_t{}
    err := syscall.Statfs(path, &s)
    if err != nil {
        return
    }
    fsReservedBlocks := uint64(s.Bfree) - uint64(s.Bavail)
    fmt.Println("Block Size: ", uint64(s.Bsize))
    fmt.Println("Total:      ", uint64(s.Bsize)*(uint64(s.Blocks)-fsReservedBlocks))
    fmt.Println("Free:       ", uint64(s.Bsize)*uint64(s.Bavail))
}
```

### Steps to reproduce the behavior

**Docker Command:**
```bash
docker run --rm -it -v /Users/dukat/Desktop/minio:/mnt  golang go run /mnt/main.go
```
**Run on Mac***
```bash
cd /Users/dukat/Desktop/minio
go run main.go
```
Same Problem on macOS 10.12 Sierra
The block size inside the container seems to be multiplied by 1024.
:confused:

**Comment by dsheets** [comment]
I believe this is the result of using `f_bsize` rather than `f_frsize` for the block size as the meaning of `f_blocks` is `size of fs in f_frsize units`.

**Comment by harshavardhana** [comment]
> I believe this is the result of using f_bsize rather than f_frsize for the block size as the meaning of f_blocks is size of fs in f_frsize units.

frsize is the "fundamental block size": the size of the smallest independently addressable/allocatable data block on the storage.

bsize is the "preferred block size": the system will attempt to do all operations in multiples of this size unless it absolutely must do otherwise. I would expect bsize to be always equal or greater than frsize.

Is it the implementation problem to not return the proper bsize? @dsheets

**Comment by dsheets** [comment]
The implementation returns the proper bsize.

See https://linux.die.net/man/2/statvfs for the defined meaning of the `f_blocks` field which I quoted.

See http://pubs.opengroup.org/onlinepubs/009604599/basedefs/sys/statvfs.h.html for the meaning of `f_blocks` according to POSIX.

See http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/fsusage.c;h=b670c0c43a1cbf7d536684863d9b8bde17c8feb0;hb=HEAD#l127 for the method by which the GNU library used by coreutils computes the block size of a file system. Compare your results with the results from GNU `df` and note that GNU `df` returns the expected results.

It may be worth noting that macOS has both `statfs` and `statvfs`. `statfs` (BSD/macOS specific)  uses `bsize` as `statvfs` (POSIX standard) uses `frsize` and `iosize` as `statvfs` uses `bsize`. This is how it is implemented in Docker for Mac.

**Comment by harshavardhana** [comment]
Yes but how can the same code be so different on native v/s inside docker? I am unable to understand this discrepancy other than some implementation issue at FUSE driver. 

```
Native on Mac OS X 10.13

Max OS X Total:    244093681664
Max OS X Free:      82487795712
Inside Docker on Mac OS X 10.13

Docker Total:   249951930023936
Docker Free:     84383058886656
```

**Comment by dsheets** [comment]
> It may be worth noting that macOS has both `statfs` and `statvfs`. `statfs` (BSD/macOS specific)  uses `bsize` as `statvfs` (POSIX standard) uses `frsize` and `iosize` as `statvfs` uses `bsize`. This is how it is implemented in Docker for Mac.

Misunderstanding the semantics of golang's `statfs` syscall binding explains the discrepancy. The standard library function that has consistent semantics on both macOS and Linux is `statvfs`. Here are the results of my tests:

```
$ make
go build statfs_osx.go
./statfs_osx
bsize: 4096
iosize: 1048576
cc -o statfs statfs_osx.c
./statfs
statfs bsize: 4096
statfs iosize: 1048576
cc -o statvfs statvfs.c
./statvfs
statvfs bsize: 1048576
statvfs frsize: 4096
docker run -v `pwd`:/src -w /src alpine ash -c "apk add --no-cache build-base go && make linux"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/21) Upgrading musl (1.1.16-r10 -> 1.1.16-r14)
(2/21) Installing binutils-libs (2.28-r3)
(3/21) Installing binutils (2.28-r3)
(4/21) Installing gmp (6.1.2-r0)
(5/21) Installing isl (0.17.1-r0)
(6/21) Installing libgomp (6.3.0-r4)
(7/21) Installing libatomic (6.3.0-r4)
(8/21) Installing pkgconf (1.3.7-r0)
(9/21) Installing libgcc (6.3.0-r4)
(10/21) Installing mpfr3 (3.1.5-r0)
(11/21) Installing mpc1 (1.0.3-r0)
(12/21) Installing libstdc++ (6.3.0-r4)
(13/21) Installing gcc (6.3.0-r4)
(14/21) Installing musl-dev (1.1.16-r14)
(15/21) Installing libc-dev (0.7.1-r0)
(16/21) Installing g++ (6.3.0-r4)
(17/21) Installing make (4.2.1-r0)
(18/21) Installing fortify-headers (0.8-r0)
(19/21) Installing build-base (0.5-r0)
(20/21) Installing go (1.8.4-r0)
(21/21) Upgrading musl-utils (1.1.16-r10 -> 1.1.16-r14)
Executing busybox-1.26.2-r5.trigger
OK: 338 MiB in 30 packages
go build statfs_linux.go
./statfs_linux
bsize: 1048576
frsize: 4096
cc -o statfs statfs_linux.c
./statfs
statfs bsize: 1048576
statfs frsize: 4096
cc -o statvfs statvfs.c
./statvfs
statvfs bsize: 1048576
statvfs frsize: 4096
```
[go-statfs-test.tar.gz](https://github.com/docker/for-mac/files/1457812/go-statfs-test.tar.gz)

**Comment by harshavardhana** [comment]
> It may be worth noting that macOS has both statfs and statvfs. statfs (BSD/macOS specific) uses bsize as statvfs (POSIX standard) uses frsize and iosize as statvfs uses bsize. This is how it is implemented in Docker for Mac.

So from what i read on macOS man pages for statfs it indicates that 

```
struct statfs { /* when _DARWIN_FEATURE_64_BIT_INODE is NOT defined */
         short   f_otype;    /* type of file system (reserved: zero) */
         short   f_oflags;   /* copy of mount flags (reserved: zero) */
         long    f_bsize;    /* fundamental file system block size */
```

f_bsize to be fundamental file system block size. 

where as  man statvfs says

```
IMPLEMENTATION NOTES
     The statvfs() and fstatvfs() functions are implemented as wrappers around the statfs() and fstatfs() functions, respectively.  Not all the information
     provided by those functions is made available through this interface.
```

So it would seem using f_bsize should work on macOS and can be considered as an alternative for f_frsize?  This is the latest macOS btw

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

**Comment by harshavardhana** [comment]
Similarly looking at Linux man pages statfs and statvfs meaning is consistent 

man statfs
```
           struct statfs {
               __fsword_t f_type;    /* Type of filesystem (see below) */
               __fsword_t f_bsize;   /* Optimal transfer block size */
               fsblkcnt_t f_blocks;  /* Total data blocks in filesystem */
               fsblkcnt_t f_bfree;   /* Free blocks in filesystem */
               fsblkcnt_t f_bavail;  /* Free blocks available to
                                        unprivileged user */
               fsfilcnt_t f_files;   /* Total file nodes in filesystem */
               fsfilcnt_t f_ffree;   /* Free file nodes in filesystem */
               fsid_t     f_fsid;    /* Filesystem ID */
               __fsword_t f_namelen; /* Maximum length of filenames */
               __fsword_t f_frsize;  /* Fragment size (since Linux 2.6) */
               __fsword_t f_flags;   /* Mount flags of filesystem
                                        (since Linux 2.6.36) */
```

man statvfs
```
      struct statvfs {
               unsigned long  f_bsize;    /* Filesystem block size */
               unsigned long  f_frsize;   /* Fragment size */
               fsblkcnt_t     f_blocks;   /* Size of fs in f_frsize units */
               fsblkcnt_t     f_bfree;    /* Number of free blocks */
               fsblkcnt_t     f_bavail;   /* Number of free blocks for
                                             unprivileged users */
               fsfilcnt_t     f_files;    /* Number of inodes */
               fsfilcnt_t     f_ffree;    /* Number of free inodes */
               fsfilcnt_t     f_favail;   /* Number of free inodes for
```

Meaning f_frsize is optimal to be used on Linux as you mentioned rather than bsize so it means that bsize is the correct value for macOS shouldn't the above program work fine? @dsheets

**Comment by dsheets** [comment]
@harshavardhana I am not sure what your question is any longer. I've shown you POSIX, Linux, and macOS documentation and written and provided a set of example programs that demonstrates the actual, real world behavior of these system calls. The meaning of `bsize` from `statfs` on macOS is not consistent with the meaning of `bsize` in Linux or on macOS with `statvfs`. This is not a problem with Docker for Mac.

**Comment by harshavardhana** [comment]
> @harshavardhana I am not sure what your question is any longer. I've shown you POSIX, Linux, and macOS documentation and written and provided a set of example programs that demonstrates the actual, real world behavior of these system calls. The meaning of bsize from statfs on macOS is not consistent with the meaning of bsize in Linux or on macOS with statvfs. This is not a problem with Docker for Mac.

@dsheets you haven't read my comment properly you can see statvfs on macOS is a wrapper for statfs()  they do not have f_frsize field instead f_bsize is used as ` fundamental file system block size `.

From the `statvfs` man page on macOS
```
f_frsize   The size in bytes of the minimum unit of allocation on this file system.  (This corresponds to the f_bsize member of struct statfs.)
```

If you implemented lets say statvfs then f_bsize should also have the right value for macOS.  Inconsistency does exist from Linux to macOS since Linux for example has f_frsize which is different with f_bsize clearly explained in the man page.  

Here is the list of all operating systems which provide f_frsize. 

Linux statvfs() f_frsize
Solaris statvfs() f_frsize

macOS statvfs() f_frsize - wrapper to statfs() --> f_bsize
> f_frsize   The size in bytes of the minimum unit of allocation on this file system. (This corresponds to the f_bsize member of struct statfs.) - https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/statvfs.3.html

FreeBSD statvfs() f_frsize - wrapper to statfs() --> f_bsize
> f_frsize   The size in bytes of the minimum unit of allocation on this file system. (This corresponds to the f_bsize member of struct statfs.) - https://www.freebsd.org/cgi/man.cgi?query=statvfs

DragonflyBSD statvfs() f_frsize
OpenBSD statvfs() f_frsize

**Comment by dsheets** [comment]
@harshavardhana please see the example code I provided you. You are calling `statfs` and not `statvfs`. As you point out, `statfs` on macOS has a different meaning for `bsize` from `statvfs`. This explains the discrepancy you observe.

**Comment by harshavardhana** [comment]
> @harshavardhana please see the example code I provided you. You are calling statfs and not statvfs. As you point out, statfs on macOS has a different meaning for bsize from statvfs. This explains the discrepancy you observe.

There is no different meaning @dsheets it says exactly the opposite, statfs (f_bsize) and statvfs (f_frsize) are same.  IMO i think the implementation here has a bug if you see if statvfs is simply a wrapper to statfs so statfs bsize and statvfs frsize should interchangeably the same - i don't see why would you have different values. 

 > f_frsize The size in bytes of the minimum unit of allocation on this file system. (This corresponds to the f_bsize member of struct statfs.)

Specifically the above line ^^  and read the subsequent line 

> f_bsize    The preferred length of I/O requests for files on	this file system.  (Corresponds to the	f_iosize member of struct statfs.)

Now if a caller calls syscall.Statfs() then he is ought to get f_bsize to be correct value corresponding to the f_frsize which is implemented under statvfs() call. 

Now Go syscall implements only Statfs() with this in mind alone it implements one call to combine the features into one Statfs_t  and there is no frsize field for darwin/freebsd. The reason for this omit is perhaps the reasoning I gave already that frsize is same as bsize on macOS and FreeBSD if you use Statfs() call.

**Comment by dsheets** [comment]
@harshavardhana I really think you should read and understand the output of the example code I provided. macOS's `statfs` `bsize` and Linux's `statfs` `bsize` have very different semantics. If you read the code that I provided you, you will see that macOS provides an `iosize` field in the `statfs` struct instead of a `frsize` field. I cannot afford to continue this discussion until you demonstrate that an issue exists that is independent from your confusion about the difference between `bsize` fields in the `statfs` struct on macOS vs Linux.

**Comment by harshavardhana** [comment]
> $ make
> go build statfs_osx.go
> ./statfs_osx
> bsize: 4096
> iosize: 1048576
> cc -o statfs statfs_osx.c
> ./statfs
> statfs bsize: 4096
> statfs iosize: 1048576
> cc -o statvfs statvfs.c
> ./statvfs
> statvfs bsize: 1048576
> statvfs frsize: 4096

So here is my confusion here Statfs and Statvfs is same for bsize, frsize which concurs with the documentation. 

> package main
> 
> import (
>     "fmt"
>     "syscall"
> )
> 
> func main() {
>     // Path inside docker container
>     path := "/mnt"
>     // Path on Mac OS X
>     //path := "/Users/dukat/Desktop/minio"
>     s := syscall.Statfs_t{}
>     err := syscall.Statfs(path, &s)
>     if err != nil {
>         return
>     }
>     fsReservedBlocks := uint64(s.Bfree) - uint64(s.Bavail)
>     fmt.Println("Block Size: ", uint64(s.Bsize))
>     fmt.Println("Total:      ", uint64(s.Bsize)*(uint64(s.Blocks)-fsReservedBlocks))
>     fmt.Println("Free:       ", uint64(s.Bsize)*uint64(s.Bavail))
> }

We are using Statfs() here, are you saying that your implementation returns Statvfs() ? for Statfs() instead? so that the iosize would have overridden the bsize value for Statfs() call?

**Comment by dsheets** [comment]
>> $ make
>> go build statfs_osx.go
>> ./statfs_osx
>> bsize: 4096
>> iosize: 1048576
>> cc -o statfs statfs_osx.c
>> ./statfs
>> statfs bsize: 4096
>> statfs iosize: 1048576
>> cc -o statvfs statvfs.c
>> ./statvfs
>> statvfs bsize: 1048576
>> statvfs frsize: 4096
>
>So here is my confusion here Statfs and Statvfs is same for bsize, frsize which concurs with the documentation.

`statfs` and `statvfs` do not return the same value for `bsize` on macOS:

>> statfs bsize: 4096
>> statvfs bsize: 1048576

Compare this with the later results from `make` for `statfs` and `statvfs` on Linux which do have the same value.

> We are using Statfs() here, are you saying that your implementation returns Statvfs() ? for Statfs() instead? so that the iosize would have overridden the bsize value for Statfs() call?

I am saying that the implementation in Docker for Mac behaves as a normal Linux file system behaves. `Statfs` binds directly to `statfs(2)` which is not POSIX and is not standard across operating systems. `statvfs` is the POSIX standard interface for this information and behaves identically on macOS and Linux w.r.t. `bsize`.

I am saying that your software has misunderstood the semantics of `syscall.Statfs` and made the assumption that the meaning of `bsize` is consistent across operating systems.
