### ISSUE TITLE
Database is not created during initialization of MySQL

### ISSUE THREAD

**Issue by pistatium** [docker/for-mac#214]
Starting from the docker-compose, database is not made.

When I test the same docker-compose.yml in docker machine(VM), it will work as expected.
However, when I start with docker for mac, despite mysql is started, the database is not made.

### Expected behavior
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| sample            |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```
### Actual behavior
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```
### Information

Diagnostic ID: 5951BFFE-4EDB-4C02-9BD0-CABE2ABF49E3
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

```docker-compose.yml
#docker-compose.yml
version: "2"
services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
```

```
docker-compose up -d
mysql -u root -p -h 0.0.0.0
> show databases;
```

**Comment by pistatium** [comment]
Sorry, I misunderstood.

**Comment by dsheets** [comment]
Thank you for closing the issue when you realized the problem was elsewhere. :-)
