### ISSUE TITLE
failure: com.docker.vpnkit is not running

### ISSUE THREAD

**Issue by dagraphix** [docker/for-mac#2140]
I am not sure what I did. The com.docker.vpnkit is not running and the console-ring does not exist.
Advice will be appreciated. I might just uninstall and reinstall my docker env once again.

### Expected behavior
Start my containers.

### Actual behavior
[ERROR] moby
[ERROR] db
[ERROR]slirp
[ERROR] docker-cli

### Information

**Full output of the diagnostics from "Diagnose & Feedback" in the menu** 

 Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/E1BBC1C7-8BA0-41E5-87BD-1C7DEB15AD8A/20171009-121108.tar.gz

failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app

**[ERROR]  moby
         /Users/Debs/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist**

[OK]     system
[OK]     moby-syslog

****[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/Debs/Library/Containers/com.docker.docker/Data/s40: check if service is running**
[OK]     env
[OK]     virtualization kern.hv_support**

**[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/Debs/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/Debs/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")**

[OK]     osxfs
[OK]     moby-console
[OK]     logs

**[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Debs/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed**

[OK]     menubar
[OK]     disk

Diagnostic ID: E1BBC1C7-8BA0-41E5-87BD-1C7DEB15AD8A
### Steps to reproduce the behavior

I'm a new docker user and sadly cant reproduce the behavior. :(

**Comment by Horat1us** [comment]
I have same behavior after install.

**Comment by bosson** [comment]
Same issue here.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac, and create a new issue if the trouble remains.  Thanks!
