### ISSUE TITLE
hyperkit high cpu

### ISSUE THREAD

**Issue by bluehz** [docker/for-mac#2141]
for no apparent reason, after several days of uneventful running - hyper kit is stuck at 125% plus cpu.

**Comment by blasterpal** [comment]
This issue has started for me in the last day for no apparent reason. I did
update to the latest Docker this week but problems did not occur directly
afterward. Still happens after fresh shut down and start (mostly).

`Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c`

I have a strong feeling that it is related to mounted volumes, but I've not been able to prove 100%.
