### ISSUE TITLE
DOCKER_API_VERSION not working.

### ISSUE THREAD

**Issue by rayjohnson** [docker/for-mac#2143]
I ad configured docker-machine to talk to a docker daemon on my qnap server.  Was working working great.  Then docker for mac auto upgraded me to a new version of docker.  Now I can't talk to the qnap docker daemon.

Looked around and found I should be able to set DOCKER_API_VERSION to handle the issue.
export DOCKER_API_VERSION=1.23

### Expected behavior

I expect to be able to use docker to talk to the daemon on my qnap server.

### Actual behavior

I still get the same message:
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

env | grep DOCK*
DOCKER_HOST=tcp://qnapstore:2376
DOCKER_API_VERSION=1.23
DOCKER_MACHINE_NAME=qnap
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/rayj/.docker/machine/machines/qnap

docker ps
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

**Comment by brandon-arnold** [comment]
This used to work up until recently. Now it doesn't anymore.

**Comment by creib** [comment]
Same problem here. Trying to build a docker image in a jenkins-build running in docker.

**Comment by ebriney** [comment]
There is open issue upstream, see [here](https://github.com/docker/cli/issues/613).
Until it is fixed you can use a previous version, which channel are you using?

**Comment by thaJeztah** [comment]
Yes, looks related to https://github.com/moby/moby/pull/35008 which is included in docker 17.10; https://github.com/docker/docker-ce/blob/17.10/components/cli/vendor/github.com/docker/docker/client/client.go#L252

**Comment by bholloway** [comment]
Thanks @thaJeztah for pointing to 17.10.

I worked around this by switching to the `edge` stream which has already shipped said 17.10 version.

I observer there is no mention of this bug in the [17.10 (edge) release notes](https://docs.docker.com/docker-for-mac/release-notes/#edge-release-notes). But I am the naive user and may be looking in the wrong spot.

**Comment by thaJeztah** [comment]
This should be fixed in 17.09.1 and up
