### ISSUE TITLE
Can not use registry mirror

### ISSUE THREAD

**Issue by schmunk42** [docker/for-mac#2146]
### Expected behavior

Use registry mirror

### Actual behavior

Docker complains about "No certs for ...." in Settings > Daemon.

Registry can be used with docker-machine provisioned host. Certs are valid.

### Information

```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/CBDD2A14-B751-43EC-9420-1C5C993BBF2B/20171011-205936.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Set mirror in "Insecure registries" and "registry mirrors" (with and without https://"
  2. docker pull .. docker rmi ... docker pull (no speed gain)

Related https://github.com/docker/for-mac/issues/1862

**Comment by MichaelSp** [comment]
same here
`Version 17.09.0-ce-mac32 (19506)`

**Comment by MichaelSp** [comment]
Is it possible that this prevents me to login to my registry?

```
docker login hostname:port
error getting credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`
```

note: I wasn't even asked to provide credentials

**Comment by andrevtg** [comment]
Got the same issue here. Done this a gazzilion times before, not working in:
Version 17.11.0-ce-rc3-mac38 (20152)
Channel: edge
a091b4ad0a

**Comment by jfroment** [comment]
Ran into this issue too... Workaround seems to be to **uncheck** "Securely store docker logins in macOs keychain" in Docker > Preferences. An update (macOs or Docker, don't know) might have broken the stored credentials. Tried again to log into the registry and it worked!

**Comment by CyrilSiman** [comment]
Hi same issue for me with : 

_Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c_

_Registry Mirror : Nexus 3 OSS (3.6.1-02), Correctly configured and working with all my linux computers_

To check and understand what append in Moby (xhyve VM), I inspect it with this command : 

`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty 2`
Inside Moby I follow this two files /etc/docker/daemon.json and  /var/log/docker.log

Default value for my daemon.json
```
{
  "debug" : true,
  "experimental" : true
}
```

Behaviour :

In Docker Preference > Daemon > Basic, if I add my registry mirrors, I'have an error about **No certs** , however if I Apply and Restart Docker : 

Inside Moby
```
cat /etc/docker/daemon.json 
{
  "debug" : true,
  "experimental" : true,
  "registry-mirrors" : [
    "https://YYY.XXX.com:WWW"
  ]
}
```
_of course YYY, XXX, WWW are the right values_

I'm not login in the registry : Inside or outside Moby 
```
docker logout https://XXX.YYY.com:WWW
Not logged in to XXX.YYY.com:WWW
```

Still inside Moby (with screen command), I try to pull image present in my mirror 

```
docker pull debian:9
tail -f /var/log/docker.log
...
Nov 23 10:20:39 moby root: time="2017-11-23T10:20:39.427751871Z" level=debug msg="Trying to pull debian from https://YYY.XXX.com:WWW/ v2"
Nov 23 10:20:39 moby root: time="2017-11-23T10:20:39.504525934Z" level=debug msg="Increasing token expiration to: 60 seconds"
Nov 23 10:20:39 moby root: time="2017-11-23T10:20:39.557142694Z" level=debug msg="Pulling ref from V2 registry: debian:9"
Nov 23 10:20:39 moby root: time="2017-11-23T10:20:39.563128160Z" level=debug msg="pulling blob \"sha256:3e17c6eae66cd23c59751c8d8f5eaf7044e0611dc5cebb12b1273be07cdac242\""
...
```

It works, Docker used my mirror registry (quick download) 

**But if in my Mac :**

I will try to pull the same image (just after deleted it of course)

```
docker rmi debian:9      # outside or inside Moby
docker pull debian:9 .     # outside Moby, directly on my mac
tail -f /var/log/docker.log # inside Moby
...
Nov 23 10:30:18 moby root: time="2017-11-23T10:30:18.223947255Z" level=debug msg="Trying to pull debian from https://XXX.YYY.com:WWW/ v2"
Nov 23 10:30:18 moby root: time="2017-11-23T10:30:18.269647437Z" level=info msg="Attempting next endpoint for pull after error: Get https://XXX.YYY.com:WWW/v2/library/debian/manifests/9: unauthorized: authentication required"
Nov 23 10:30:18 moby root: time="2017-11-23T10:30:18.269791494Z" level=debug msg="Trying to pull debian from https://registry-1.docker.io v2"
Nov 23 10:30:19 moby root: time="2017-11-23T10:30:19.396022498Z" level=debug msg="Pulling ref from V2 registry: debian:9"
Nov 23 10:30:19 moby root: time="2017-11-23T10:30:19.396196444Z" level=debug msg="docker.io/library/debian:9 resolved to a manifestList object with 7 entries; looking for a os/arch match"
...
```

This time docker can't pull image from my registry and use docker.io instead (low download). 
I've _unauthorized: authentication required_ error

**Comment by CyrilSiman** [comment]
Me again, 

[andrevtg](https://github.com/andrevtg) 's workaround works for me : https://github.com/docker/for-mac/issues/1862#issuecomment-343303119

Step 1 = Disabled the "securely store docker logins in osx keychain"
Step 2 = docker logout
Step 3 = docker logout https://myMirror

**Comment by CMYanko** [comment]
Maybe it's just me but I'm seeing this now:

"registry mirrors" : No certs for ycompany.com:18443

...as if the the forward slash in https:// is 'escaping' the 'm' ?? Tried an extra slash too

**Comment by double16** [comment]
I'm seeing the same as @CMYanko. However, mirroring is working for me.

**Comment by schmunk42** [comment]
Someone else please check this, I am not a Mac anymore...

**Comment by MichaelSp** [comment]
I can verify that deleting all `docker` entries from *keychain access* solved it for me.

**Comment by kaanozcan** [comment]
I am having the same issue after upgrading to Version 18.03.1-ce-mac65 (24312) stable.

Unchecking securely store docker logins in macOS keychaing option doest seems to be working either. I'm just getting ```ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)``` instead. It wouldn't find our private image there anyways. It looks like its ignoring mirror. 

Any other solution for this?

**Comment by hbokh** [comment]
The issue as described by @CMYanko drove me to this issue.
It (still) exists in Docker for Mac CE 2.0.0.0-beta1-mac75 (27117).

```
"registry-mirrors":
  No certs for egistry.example.com:5000
```
The "r" is dropped, but the mirror works.

**Comment by gmshake** [comment]
Still exists in Docker for Mac version 19.03.2, build 6a30dfc

**Comment by fhefh2015** [comment]
Still exists in Docker version 19.03.4, build 9013bf5

![](https://cdn.jsdelivr.net/gh/just4picbed/oss@master//20191111102522-j70MAI.png)

![](https://cdn.jsdelivr.net/gh/just4picbed/oss@master//20191111102542-h8UZml.png)

![](https://cdn.jsdelivr.net/gh/just4picbed/oss@master//20191111102429-9QHKtI.png)

**Comment by fhefh2015** [comment]
Still exists in Docker version 19.03.4, build 9013bf5

**Comment by figroc** [comment]
Still exists in Docker Desktop Community 2.1.0.5 (40693): 
```
Engine: 19.03.5, Notary: 0.6.1, Compose: 1.24.1, Credential Helper: 0.6.3, Kubernetes: v1.14.8, Machine: 0.16.2
```

**~/.docker/daemon.json**:
```json
{
  "registry-mirrors" : [
    "https://f62945bb.mirror.aliyuncs.com"
  ],
  "experimental" : true,
  "debug" : true
}
```

**~/.docker/config.json**:
```json
{
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credSstore" : "osxkeychain",
  "credsStore" : "desktop",
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.03.1-ce (darwin)"
  }
}
```

**docker info**:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 32
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: OJ5O:XUAJ:BQUE:B5C2:FTXY:NHIP:JM3J:MFBB:WS2G:TQHM:XJ6S:3HMP
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 29
  Goroutines: 45
  System Time: 2019-12-24T09:41:03.040653211Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://f62945bb.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by elafontaine** [comment]
Why was this closed?  Is it addressed?  Not going to be addressed?  

I've been avoiding commenting for the last 6 months in the hope it was going to be resolved (and worked around the limitations I had).
