### ISSUE TITLE
Can't find the path to volume on my computer 

### ISSUE THREAD

**Issue by luzonghaoa** [docker/for-mac#2147]
I inspect a 'redis' container which is running and get these information:
**"Mounts": [
            {
                "Type": "volume",
                "Name": "902993c1defe757564057445e9bce217146e442573a8a70a8cb86b3c1a969b79",
                "Source": "/var/lib/docker/volumes/902993c1defe757564057445e9bce217146e442573a8a70a8cb86b3c1a969b79/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ]**
But, I can't find this **"/var/lib/docker/volumes/902993c1defe757564057445e9bce217146e442573a8a70a8cb86b3c1a969b79/_data"**
on my computer, I even can't find /var/lib/docker. 

When I ran this container, I did not use -v option, but I think this image(redis) can create a volume automatically.

**Comment by kinghuang** [comment]
The referenced path is within the xhyve VM running Docker, not literally on the path hierarchy of your Mac.

**Comment by ebriney** [comment]
Hi @luzonghaoa.
What do you want to do exactly?
You can do `docker exec -it <container_id> /bin/sh` to get a shell in your redis container.
If you want to do a copy of data folder on your mac you can do:
 `docker exec -v <mac folder>:/dest <container_id> cp /data /dest`
