### ISSUE TITLE
Unable to pull from local registry

### ISSUE THREAD

**Issue by sitase** [docker/for-mac#2148]
### Expected behavior

docker pull should pull image

### Actual behavior

$ docker pull docker.st.assaabloy.net/rocket/smb:2017-10-12.2569-4335_basemessage_serialization

Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"

### Information

A46BC86B-1162-4A2F-BEA9-F60BA3A3ECFD

When listing the tags through the API it is there:

https://docker.st.assaabloy.net/v1/repositories/rocket/smb/tags/2017-10-12.2569-4335_basemessage_serialization

"84d464ddd50ffa83b14bc87ef8c1665d7e1ef24be9a2ed83a04a680f965c053b"

And it is possible to download  the layer at 
https://docker.st.assaabloy.net/v1/images/84d464ddd50ffa83b14bc87ef8c1665d7e1ef24be9a2ed83a04a680f965c053b/layers

### Steps to reproduce the behavior

  1. ...
  2. ...
[20171012-152241.tar.gz](https://github.com/docker/for-mac/files/1379463/20171012-152241.tar.gz)

**Comment by rseek** [comment]
same problem here

**Comment by kinghuang** [comment]
The response shows a 404 Not Found. Is there a type in the image name or tag? Or, perhaps you need to authenticate before pulling the image?
