### ISSUE TITLE
Incorrect Symlink

### ISSUE THREAD

**Issue by bshoemaker136** [docker/for-mac#2149]
### Error:
Symlink /usr/local/bin/docker is not linked to Library/Group Containers/group.com.docker/bin/docker

### Information

  - Issue began after a recent failed docker update on the stable channel, and persists on the edge channel.
  - Symlinks have double-slashes - not sure if that matters for parsing?  
The symlink still works:
docker -> /Users/myuser//Library/Group Containers/group.com.docker/bin/docker
 - I attempted to fix the symlink, but it was immediately replaced with the double-slash when I ran the docker app.

**Comment by bshoemaker136** [comment]
I'd just like to say that reverting to a previous build *did* resolve the issue.
This appears to be a legitimate bug, and not a configuration issue on my end.
I'm running macOS Sierra 10.12.6

**Comment by ebriney** [comment]
Hi @bshoemaker136.
Which version have this?
I checked with `17.09.0-ce-mac35 (19611)` (last stable) and don't have the double slashes.
