### ISSUE TITLE
zsh completion files are not bundled

### ISSUE THREAD

**Issue by norio-nomura** [docker/for-mac#215]
### Expected behavior
zsh completion files would be bundled as following:
```
Contents/Resources/etc/docker-compose.zsh-completion
Contents/Resources/etc/docker-machine.zsh-completion
Contents/Resources/etc/docker.zsh-completion
```
### Actual behavior
zsh completion files are not bundled.

### Information

Diagnostic ID: 4A502A3E-664A-47DA-8119-1148F2CBD9B7
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
This should arrive in Beta 23 and later in 1.12.1.

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Comment by franklinyu** [comment]
It would be nice if the Zsh completions are named with Zsh convention, that is

```text
Contents/Resources/etc/zsh-completion/_docker-compose
Contents/Resources/etc/zsh-completion/_docker-machine
Contents/Resources/etc/zsh-completion/_docker
```

so that we can easily pick up those completions with

```zsh
fpath+=/Applications/Docker.app/Contents/Resources/etc/zsh-completion
autoload -Uz compinit
compinit -i
```
