### ISSUE TITLE
Docker restarted while being used

### ISSUE THREAD

**Issue by 0xCMP** [docker/for-mac#2154]
### Expected behavior
Docker runs until I restart, update, or stop it.

### Actual behavior
While using it (making a request to a container) Docker refused `docker-compose` requests and restarted.

### Information
`4B5D1AE1-0986-459B-88E2-019AE7E67A4E`

There may be something in the logs?

```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/4B5D1AE1-0986-459B-88E2-019AE7E67A4E/20171016-113532.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
I'm not sure, I just refreshed my page which made a request and it restarted. I tried to diagnose as quickly as possible since I'm not sure where else to check.

**Comment by westandskif** [comment]
The same thing is happening more or less randomly with me. 
I ran 4 containers: pg9.6, redis, webpack, "python + selenium + chrome + chromedriver".
Definitely there are no OOMs (<1gb in use, while the limit is 6gb) and fork bombs (pids num < 110).

**Comment by 0xCMP** [comment]
I haven't seen this in the later versions so I'll assume this is fixed
