### ISSUE TITLE
4222BAEE-FC2D-4CDE-A89C-16FE321CA256

### ISSUE THREAD

**Issue by aydincan1** [docker/for-mac#2161]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing. Please reopen with proper description if issue still present.
