### ISSUE TITLE
unable to install rancher

### ISSUE THREAD

**Issue by anuhappy** [docker/for-mac#2163]
### Expected behavior
install rancher

### Actual behavior
unable to install rancher
### Information

Unable to find image 'rancher/server:v1.0.1' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.2:45261->192.168.65.1:53: i/o timeout.

**Comment by ebriney** [comment]
Hi @anuhappy.
From [hub](https://hub.docker.com/r/rancher/server/tags/), there is no 1.0.1 tag.
From the rancher [doc](http://rancher.com/docs/rancher/latest/en/installing-rancher/installing-server/) :
```
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
```
works for me and I have access to rancher in my browser with `localhost:8080`
