### ISSUE TITLE
 mac docker error

### ISSUE THREAD

**Issue by hqman** [docker/for-mac#2164]
### Information

Diagnostic ID: E094AB35-979E-48BF-A6DA-8F84E8EEF495
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.13 (Build 17A405)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/hqman/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/E094AB35-979E-48BF-A6DA-8F84E8EEF495/20171022-204149/qemu-img-check.stdout 2> /tmp/E094AB35-979E-48BF-A6DA-8F84E8EEF495/20171022-204149/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/hqman/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/hqman/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
