### ISSUE TITLE
Waiting for SSH to be available...

### ISSUE THREAD

**Issue by maheshrajannan** [docker/for-mac#2166]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/CE377E00-2379-4A4C-A6A9-024413A93524/20171022-150848.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Maheshs-MacBook-Pro-2:~ maheshrajannan$ docker --version
could not read CA certificate "/Users/maheshrajannan/.docker/machine/machines/default/ca.pem": open /Users/maheshrajannan/.docker/machine/machines/default/ca.pem: no such file or directory
Maheshs-MacBook-Pro-2:~ maheshrajannan$ 

Maheshs-MacBook-Pro-2:~ maheshrajannan$ docker-machine regenerate-certs
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...

<<Just stuck here....>

Oh GOSH!!

**Comment by thaJeztah** [comment]
It looks like your shell is configured to use a VM created by docker-machine, instead of the Docker for Mac installation; Docker for Mac does not require SSH access to a VM.

Try running `docker-machine env --unset` and follow the instructions printed by that command; after that, the shell should no longer be configured to connect to the VM created by Docker Machine, and use the Docker for Mac installation.

**Comment by hard-fault** [comment]
Hi Sebastiaan,

Facing similar issue. (I am using a Mac. I am trying to create a custom overlay network over ec2. )

BleedBlue:~ Shreyas$ docker-machine create -d amazonec2 infra-aws
Running pre-create checks...
Creating machine...
(infra-aws) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...

Last login: Thu Feb 1 12:17:22 on ttys002
BleedBlue:~ Shreyas$ docker-machine ls
NAME ACTIVE DRIVER STATE URL SWARM DOCKER ERRORS
infra-aws amazonec2 Timeout

**Comment by NaitikShah** [comment]
@hard-fault did you get any solution for the same?

**Comment by hard-fault** [comment]
@NaitikShah I didn't continue with docker-machine. I instead wrote my own scripts to login to ec2 and install docker.

**Comment by NaitikShah** [comment]
Oh okay, Can u share with me if they are generic enough? @hard-fault

**Comment by hard-fault** [comment]
@NaitikShah Here is my project - https://github.com/dream-lab/VIoLET
It isn't very straightforward but you can reach me out for any doubts.

**Comment by NaitikShah** [comment]
Hey great Man !! @hard-fault  Thanks :+1:

**Comment by krzysztof-callstats** [comment]
Facing something similar right now

```
docker-machine restart
Restarting "default"...
Waiting for SSH to be available...

Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```
