### ISSUE TITLE
Docker error pulling image configuration

### ISSUE THREAD

**Issue by kksandyrox** [docker/for-mac#2167]
### Expected behavior
The image should be successfully pulled.

### Actual behavior
`mac_mini4:abcd mac-mini-4$ docker pull node` 
`Using default tag: latest`
`latest: Pulling from library/node`
`85b1f47fba49: Pulling fs layer `
`5409e9a7fa9e: Pulling fs layer `
`661393707836: Pulling fs layer `
`1bb98c08d57e: Waiting `
`f957ac1b6e47: Waiting `
`166b7c18b759: Waiting `
`02cb65a8d0f6: Waiting `
`9052b6207e12: Waiting `
`error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ba/badd967af535567f92c04665ccbf4ccf63f58960e38a43f611b1b19ca3a713e7/data?Expires=1508747774&Signature=itXcTt8IGLoxsACN4OJMgmRgUfrEOE3i9J6g8ooOV9AANUAQgXnJb6Rme48DxjzCLTWnKKLQqASNNa2fNuxCCy9X6qVSBZGazxNktOwWe70fjIqR5ojTQG5GtaZUsoL0k6we~gPQXKMIBdZfGu33YeMPD7CymCow4Ww4dwwvPgo_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 192.168.65.1:443: getsockopt: connection refused`
`mac_mini4:abcd mac-mini-4$ `

Occurs with other images too..

### Information
 - OS : MacOS Seirra 10.12.6
 - Docker Version 17.09.0-ce-mac35 (19611) Channel: stable a98b7c1b7c
 - When I try to pull any images I get the above Behaviour
 - What I have tried? 
a) Added dns under daemon tab of docker . `"dns" : [
    "8.8.8.8",
    "8.8.4.4"
  ]`
b) Added DNS Servers `"8.8.8.8" and "8.8.4.4"` under Network Preferences -> Advanced -> DNS tab
 - Images: https://ibb.co/n2zCVm and https://ibb.co/g6HcwR

I checked some other posts and saw some users facing this similar issue. But they could resolve it just by setting up the DNS servers to 8.8.8.8, which unfortunately not working for me.
Can anyone please help?

What could be possibly wrong here in my steps? PS*: new to Docker here.
If you think I have not provided enough information, please let me know. I will update accordingly.

**Comment by adam-golab** [comment]
Try with adding:
```
127.0.0.1 localunixsocket
```
To your `/etc/hosts` file
