### ISSUE TITLE
Docker is not starting

### ISSUE THREAD

**Issue by AmanHardaha** [docker/for-mac#217]
### Expected behavior
Docker is running & up
### Actual behavior
stuck in docker startinh
### Information

Diagnostic ID: 29BB1A6F-EF92-4A24-9B8F-97B108E59A3F
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.1 (Build 15B42)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/awtech022/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Download Docker for mac
2. Install it

**Comment by andreyz** [comment]
Same for me.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'processor-not-supported' in 29BB1A6F-EF92-4A24-9B8F-97B108E59A3F/20160810-173019.

Your system do not satisfy the hardware requirements of Docker for Mac. nSee https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install for more information.
