### ISSUE TITLE
Docker for Mac: Docker.qcow2 couldn't be removed.

### ISSUE THREAD

**Issue by ChaosCA** [docker/for-mac#2170]
### Expected behavior
The Docker file should move to the new location specified.
### Actual behavior
In the preferences for Docker, I am attempting to move my Docker Images location and every time I do I get the error `Docker.qcow2 couldn't be removed.`
### Information

Diagnostics ID: 394963E7-3580-477B-B492-9590A2DE2101
Everything says okay.

### Steps to reproduce the behavior

  1. Click the Docker icon
  2. Choose preferences
  3. Navigate to Advanced
  4. Choose a new location for Docker Images and hit `apply and restart`
  5. Fails.

**Comment by ChaosMTA** [comment]
As a temporary solution I moved the file myself, set the new location and clicked "use it" when I selected the new location and Docker detected the file.

For whatever reason Docker can't move the file by itself, I have to do it in Finder and then apply it.

**Comment by gtardif** [comment]
Thanks for your report ; this bug has been identified and fixed in the latest edge release.

**Comment by lzantal** [comment]
@ChaosMTA thanks for the remp fix. It worked for me. However I had to do it before I create any image. It works now so I am happy 👍

**Comment by adityasrivastava** [comment]
@ChaosMTA Thanks works great.
