### ISSUE TITLE
docker-sync stopped to work with recent release of Docker for Mac

### ISSUE THREAD

**Issue by Krzysiaczek-at-theFoundry** [docker/for-mac#2171]
### Expected behavior
It was all fine until yesterday when I agreed to update Docker for Mac

### Actual behavior
Today it fails when try to execute `docker-sync start`

I've already tried `docker pull eugenmayer/unison` but this didn't help
### Information
Docker for Mac: version: 17.10.0-ce-mac36 (a38d9cd48bd0ee31ec82c59b783aa2f2817bfb92)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/148B7441-2799-4D9E-9368-F08DDAFEFAEC/20171025-103639.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

```
$ docker-sync start
        info  Not running any precondition checks since you have no brew and that is unsupported. Is all up to you know.
        info  Not running any precondition checks since you have no brew and that is unsupported. Is all up to you know.
        info  Not running any precondition checks since you have no brew and that is unsupported. Is all up to you know.
        info  Not running any precondition checks since you have no brew and that is unsupported. Is all up to you know.
        info  Not running any precondition checks since you have no brew and that is unsupported. Is all up to you know.
          ok  Starting unison for sync web-sync
          ok  web-sync container still running, restarting unison in container
     command  docker exec web-sync supervisorctl restart unison
          ok  starting initial sync of web-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' web-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' web-sync
       error  Error getting mapped port, exit code 0
     message  Template parsing error: template: :1:3: executing "" at <index (index .Networ...>: error calling index: index of untyped nil
     command  unison -testserver /app_sync "socket://:"
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in `block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:107:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:92:in `block in start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:166:in `daemonize'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```

**Comment by Krzysiaczek-at-theFoundry** [comment]
I've removed Docker for Mac Edge version and installed stable one.

On `docker-sync start` a new version of `eugenmayer/unison:hostsync_0.2` has been downloaded and everything looks good now but I can't tell if the version I downloaded a few hours earlier was the same as currently downloaded (hostsync_0.2). 

So I'm not sure if they have fixed and released a new version already in the meantime or is it the same version working properly with the stable version of Docker for Mac.

**Comment by Krzysiaczek-at-theFoundry** [comment]
It looks like hostsync_0.2 is 6 months old already so it must be something wrong with recent not stable version of Docker for Mac 17.10.0-ce-mac36.

I am running now 17.09.0-ce-mac35 stable which is alright.

**Comment by tripox** [comment]
https://github.com/EugenMayer/docker-sync/pull/478

**Comment by tripox** [comment]
@Krzysiaczek-at-theFoundry - have you seen my comment? :)

**Comment by Krzysiaczek-at-theFoundry** [comment]
Hi, yes, but I'm not sure what do you want me to do about it? I've already reported the solution so it was fixed for me.

Currently, I'm running docker-sync version 0.5.2 with the same version of DFM: Version 17.09.0-ce-mac35 (19611) Stable due to some other sync problems with recent versions.

I can only report that when I start docker-sync for the very first time it shows some errors but later it's working OK

$ docker-sync start
Error response from daemon: manifest for eugenmayer/unison:hostsync_0.2 not found
Error response from daemon: manifest for eugenmayer/unison:hostsync_0.2 not found
          ok  Starting native_osx for sync app-sync
          ok  app-sync container not running
          ok  starting app-sync container
     command  docker start app-sync && docker exec app-sync supervisorctl restart unison
app-sync
unix:///tmp/supervisor.sock refused connection
          ok  starting initial sync of app-sync
     success  Sync container started
     success  Starting Docker-Sync in the background

**Comment by tripox** [comment]
@Krzysiaczek-at-theFoundry, they changed the output of `docker info | grep 'Operating System'` so it returns: "Operating System: Docker for Mac" - that made `docker-sync` use the `unison strategy` which seemed broken at the time, instead of the nativeosx sync.

Newest version of Docker for Mac (stable and edge) works with docker-sync 0.5.7 and the nativeosx strategy which is default. 😊

**Comment by tripox** [comment]
Regardless this is a Docker for Mac related issue.
