### ISSUE TITLE
Fatal error printed (MSpanList_Insert) on docker build; High Sierra, go 1.9

### ISSUE THREAD

**Issue by delsvr** [docker/for-mac#2173]
When I run `docker build`--and only `docker build` (i.e. no issues with other docker commands like `start`, `info`, `rm`, `run`)--I get the fatal trace below. Possibly because some component of `docker build` is still built with go 1.6?

My locally installed `go` is 1.9.1, and this occurs with the latest stable docker-ce build:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64
```

The `docker build` still succeeds despite the printed error; i.e. the image is built. 

This only started to happen when I upgraded to High Sierra (10.13).

Occurs with both the stable and edge builds from the docker website. I am surprised there isn't already an issue for this? Is it just my environment?

### Expected behavior
Builds without error

### Actual behavior
Error printed to console:

```
$ docker build .
failed MSpanList_Insert 0x4384000 0x120351726dd0c 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x4164a40, 0x10)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfef80 sp=0x7ffeefbfef68
runtime.(*mSpanList).insert(0x420eea8, 0x4384000)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbfefb0 sp=0x7ffeefbfef80
runtime.(*mheap).freeSpanLocked(0x420e6a0, 0x4384000, 0x100, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff018 sp=0x7ffeefbfefb0
runtime.(*mheap).grow(0x420e6a0, 0x8, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff070 sp=0x7ffeefbff018
runtime.(*mheap).allocSpanLocked(0x420e6a0, 0x1, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff0c8 sp=0x7ffeefbff070
runtime.(*mheap).alloc_m(0x420e6a0, 0x1, 0x15, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff0f8 sp=0x7ffeefbff0c8
runtime.(*mheap).alloc.func1()
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff128 sp=0x7ffeefbff0f8
runtime.systemstack(0x7ffeefbff148)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff130 sp=0x7ffeefbff128
runtime.(*mheap).alloc(0x420e6a0, 0x1, 0x10000000015, 0x400ebdf)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff178 sp=0x7ffeefbff130
runtime.(*mcentral).grow(0x42102a0, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff1e0 sp=0x7ffeefbff178
runtime.(*mcentral).cacheSpan(0x42102a0, 0x420b2c8)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff220 sp=0x7ffeefbff1e0
runtime.(*mcache).refill(0x4380000, 0x15, 0x7ffeefbff288)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff258 sp=0x7ffeefbff220
runtime.mallocgc.func2()
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff278 sp=0x7ffeefbff258
runtime.systemstack(0x7ffeefbff318)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff280 sp=0x7ffeefbff278
runtime.mallocgc(0x180, 0x4147ac0, 0x0, 0x800000000)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff358 sp=0x7ffeefbff280
runtime.newobject(0x4147ac0, 0x420b570)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff380 sp=0x7ffeefbff358
runtime.malg(0x8000, 0x420b7e0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbff3b8 sp=0x7ffeefbff380
runtime.mpreinit(0x420bb20)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbff3d0 sp=0x7ffeefbff3b8
runtime.mcommoninit(0x420bb20)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbff418 sp=0x7ffeefbff3d0
runtime.schedinit()
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbff460 sp=0x7ffeefbff418
runtime.rt0_go(0x7ffeefbff4a0, 0x2, 0x7ffeefbff4a0, 0x0, 0x7fff78ff2145, 0x0, 0x2, 0x7ffeefbff6b0, 0x7ffeefbff6ce, 0x0, ...)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbff468 sp=0x7ffeefbff460
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A405)
logs: /tmp/FAF09885-A656-4666-A22D-BD6332BC06A6/20171025-225441.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW
Any empty Dockerfile works:
```
FROM debian:testing
```

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. `docker build .`

**Comment by delsvr** [comment]
Anyone have any ideas here? As I mentioned, the `docker build` succeeds, so which process is running before `docker build` here and crashing?

**Comment by delsvr** [comment]
See https://github.com/docker/cli/issues/676; feel free to close.

**Comment by ryantxr** [comment]
docker-machine does the same thing.
Upgraded to High Sierra. Now docker-machine outputs:
$ docker-machine
failed MSpanList_Insert 0x2707000 0x108b79b9e3329 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x16e41e0, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff580 sp=0x7ffeefbff568
runtime.(*mSpanList).insert(0x22a0ca8, 0x2707000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff5b0 sp=0x7ffeefbff580
runtime.(*mheap).freeSpanLocked(0x22a04a0, 0x2707000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff618 sp=0x7ffeefbff5b0
runtime.(*mheap).grow(0x22a04a0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff670 sp=0x7ffeefbff618
runtime.(*mheap).allocSpanLocked(0x22a04a0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff6c8 sp=0x7ffeefbff670
runtime.(*mheap).alloc_m(0x22a04a0, 0x1, 0x15, 0x0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff6f8 sp=0x7ffeefbff6c8
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff728 sp=0x7ffeefbff6f8
runtime.systemstack(0x7ffeefbff748)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff730 sp=0x7ffeefbff728
runtime.(*mheap).alloc(0x22a04a0, 0x1, 0x10000000015, 0x12b1f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff778 sp=0x7ffeefbff730
runtime.(*mcentral).grow(0x22a20a0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff7e0 sp=0x7ffeefbff778
runtime.(*mcentral).cacheSpan(0x22a20a0, 0x229a9a8)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff820 sp=0x7ffeefbff7e0
runtime.(*mcache).refill(0x2703000, 0x15, 0x7ffeefbff888)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff858 sp=0x7ffeefbff820
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff878 sp=0x7ffeefbff858
runtime.systemstack(0x7ffeefbff918)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff880 sp=0x7ffeefbff878
runtime.mallocgc(0x180, 0x1549460, 0x0, 0x800000000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff958 sp=0x7ffeefbff880
runtime.newobject(0x1549460, 0x229b090)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff980 sp=0x7ffeefbff958
runtime.malg(0x8000, 0x229b560)
	/usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbff9b8 sp=0x7ffeefbff980
runtime.mpreinit(0x229bd20)
	/usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbff9d0 sp=0x7ffeefbff9b8
runtime.mcommoninit(0x229bd20)
	/usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbffa18 sp=0x7ffeefbff9d0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffa60 sp=0x7ffeefbffa18
runtime.rt0_go(0x7ffeefbffa98, 0x1, 0x7ffeefbffa98, 0x0, 0x0, 0x1, 0x7ffeefbffbc8, 0x0, 0x7ffeefbffbd7, 0x7ffeefbffbf3, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffa68 sp=0x7ffeefbffa60
