### ISSUE TITLE
Docker Crash Immediately After Login

### ISSUE THREAD

**Issue by almostsultry** [docker/for-mac#2181]
### Information

Diagnostic ID: 552E6F28-DC3E-4658-ABE5-488D2AA536F2
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.13 (Build 17A365)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/BenjaminRutledge/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/BenjaminRutledge/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
