### ISSUE TITLE
Crashed on macOS Sierra

### ISSUE THREAD

**Issue by hgezim** [docker/for-mac#219]
I two containers using `docker-compose`. Shortly after I started using the app, docker crashed with this error:

Fatal Error:

vmstateevent invalid json:

### Information

Diagnostic ID: CD16A08F-1EB9-4145-AA09-90196EA5A24C
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A284a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by hgezim** [comment]
Duplicate of #64.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
