### ISSUE TITLE
Authorization Plugins don't work

### ISSUE THREAD

**Issue by lox** [docker/for-mac#2191]
### Expected behavior

Enabling an authorization plugin from the Mac side of docker for mac should enable it for use with the daemon in the VM.

### Actual behavior

No log messages, no interaction with the authorization plugin.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
macOS: version 10.12.6 (build: 16G29)
Docker.app: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
Local time: Wed  1 Nov 2017 15:02:11 AEDT
UTC:        Wed  1 Nov 2017 04:02:11 UTC
Timestamp:  20171101-150211
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      vpnkit
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/3AE2C057-4CA2-483D-B2D9-96E6354F680A/20171101-150211.tar.gz
Your unique id is: 3AE2C057-4CA2-483D-B2D9-96E6354F680A
Please quote this in all correspondence.
```

  - A reproducible case if this is a bug, Dockerfiles FTW

See https://github.com/buildkite/docker-buildkite-authorization-plugin.

  - Page URL if this is a docs issue or the name of a man page

**Comment by lox** [comment]
Turns out `authorization-plugin` was needed in the `daemon.json` apologies for the noise!

**Comment by dsheets** [comment]
This is a usability problem with the moby engine authz plugin system. https://github.com/moby/moby/pull/33658 will fix this issue if merged.
