### ISSUE TITLE
How do you set VPNKit: slirp/port-max-idle-timeout to disabled?

### ISSUE THREAD

**Issue by genei09** [docker/for-mac#2197]
### Expected behavior
Documentation to describe the method

### Actual behavior
Unable to locate documentation

### Information

17.09.0 build 35

**Comment by genei09** [comment]
This seems to work for setting it very high, but I would like the value to disable
`cd ~/Library/Containers/com.docker.docker/Data/database/`
`echo 200000 > com.docker.driver.amd64-linux/slirp/port-max-idle-time`
`git add com.docker.driver.amd64-linux/slirp/port-max-idle-time`
`git commit -s -m 'increase timeout'`

**Comment by squ74** [comment]
Can someone help me changing this value in Docker Community Edition 17.12.0-ce-win47 2018-01-12 (Stable) ?

**Comment by djs55** [comment]
Thanks for the report. The configuration mechanism changed in `17.12` to use a file:
```
~/Library/Group\ Containers/group.com.docker/settings.json
```
To modify it, try a command like:
```
jq .vpnKitMaxPortIdleTime=300 ~/Library/Group\ Containers/group.com.docker/settings.json > settings.json.2
mv settings.json.2 ~/Library/Group\ Containers/group.com.docker/settings.json
```
and restart the app.

I'm hoping to fix the problem with network timeouts more generally, so it won't be necessary to tweak the timeout.

**Comment by rhift** [comment]
hey @djs55 - I think that you might have accidentally inverted some words:

`vpnKitMaxPortIdleTime` should be `vpnKitPortMaxIdleTime`

Or at least that worked for me. =) ty btw, this solved my issue perfectly!

**Comment by aaron-sua** [comment]
the relevant question still remains, how to disable

**Comment by jessetan** [comment]
According to https://github.com/moby/vpnkit/pull/272, using a value of <= 0 should disable it.

A negative setting in `~/Library/Group\ Containers/group.com.docker/settings.json` crashes VPNKit when I restart Docker.
`"vpnKitPortMaxIdleTime" : 0` works OK

**Comment by ltammariello** [comment]
Any info. on how to set this value on Windows?
