### ISSUE TITLE
Enabling userns-remap causes a boot loop

### ISSUE THREAD

**Issue by nikovirtala** [docker/for-mac#2198]
### Expected behavior
Docker for Mac VM starts properly.

### Actual behavior
Docker for Mac VM is in a boot loop.

### Information

Docker for Mac: version: 17.11.0-ce-rc2-mac37 (a38d9cd48bd0ee31ec82c59b783aa2f2817bfb92)
macOS: version 10.13.1 (build: 17B48)
logs: /tmp/D631AF3C-0255-4C1A-94CD-7873E6539C9B/20171104-132514.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

Diagnostic ID: D631AF3C-0255-4C1A-94CD-7873E6539C9B

### Steps to reproduce the behavior

  1. Install Docker for Mac Version 17.11.0-ce-rc2-mac37 (20033) Channel: edge d7d657d636
  2. Enter "userns-remap" : "default", in to docker daemon configuration file.
  3. Click 'Apply & Restart'

**Comment by triha74** [comment]
Im experiencing the same issue with version 17.12.0-ce-mac49

Any update?
