### ISSUE TITLE
Error response from daemon: Bad response from Docker engine, see diagnostics

### ISSUE THREAD

**Issue by Ir1sh** [docker/for-mac#22]
### Information

Diagnostic ID: D5A3393D-36ED-457C-AD24-E37C701B8123
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by boris** [comment]
I'm having the same issue here with Docker version 1.12.0-beta21 (Build 10868).

Here's the output of Diagnose & Feedback tool:
```
Docker for Mac: version: win-beta-v1.12.0-rc5-beta21-68-g5b59d37
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/060DF166-B54A-4415-81F7-32C02F4DD60D/20160731-211010.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by samoht** [comment]
Hi, could you please provide more information so we can help you. Which steps of the installation process succeeded, which didn't. What is the state of Docker in the 🐳 menu. What does `docker version` says? Closing that issue for now, but please re-open when you can give use more information.
