### ISSUE TITLE
Issue on macOS Sierra Bata 4

### ISSUE THREAD

**Issue by thatGuy0923** [docker/for-mac#220]
### Expected behavior
Boot up docker app and run docker.

### Actual behavior
Fails on the build of osxfs, db, slirp and docker cli

### Information
Diagnostic ID: E9677F52-FD1F-4369-A9DF-9076A2590E17
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A270f)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/evanowen/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/evanowen/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/evanowen/Library/Containers/com.docker.docker/Data/s51: check if service is running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Download the most recent docker beta
2. Remove the current docker beta 
3. Copy the beta to applications
4. Run the beta
5. After the failure I attempted to fix the cli by running sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist

**Comment by sanshilei** [comment]
Same as you do

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
