### ISSUE TITLE
Command docker not found when locally ssh into machine

### ISSUE THREAD

**Issue by PixellUp** [docker/for-mac#2202]
### Expected behavior
Display any docker command

### Actual behavior
Return following text `zsh:1: command not found: docker `
### Information

**Diagnostic ID: 70EEA298-69D8-4923-990E-69F785466F37**
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A405)
logs: /tmp/70EEA298-69D8-4923-990E-69F785466F37/20171106-204054.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. use https://github.com/phpseclib/phpseclib package
  2. successfully connect to localhost server
  3. run `ssh->exec('docker');`

I can easily use docker command everywhere with the terminal, but when I ssh into my local machine this happens.

**Comment by PixellUp** [comment]
More information - https://stackoverflow.com/questions/47158644/docker-command-not-found-when-using-phpseclib

**Comment by mks-d** [comment]
I encountered a similar issue when using [heredoc](https://www.gnu.org/software/bash/manual/bashref.html#Here-Documents) with SSH. Using a logging shell worked. So from the container:
```bash
ssh user@host bash --login <<EOF
docker -v
EOF
```

I know that my problem was specific to SSH and profile sourcing, but just in case someone else lands here upon Googling...

**Comment by ankanch** [comment]
I have the same problem, whereby I try to execute docker command from windows 10 to Docker on OS X 10.

as below:

```sh
kanch@LAPTOP-KANCH:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS           NAMES
kanch@LAPTOP-KANCH:~$ docker -H tcp://192.168.1.104:2375 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS             NAMES
kanch@LAPTOP-KANCH:~$  docker -H ssh://platform@192.168.1.104 ps
error during connect: Get http://docker/v1.40/containers/json: command [ssh -l platform 192.168.1.104 -- docker system dial-stdio] has exited with exit status 127, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=zsh:1: command not found: docker
```

tcp:// just won't works as the reason is command docker not found.

why???
