### ISSUE TITLE
Docker for Mac crashing with error: dial unix connect: connection refused

### ISSUE THREAD

**Issue by BenEinwechter** [docker/for-mac#2207]
**Diagnostic ID: 0F96BFAD-94C3-476E-A4F3-81CD1F5C41ED**

I'm using Docker for Mac for a Rails app development environment. When I run my integration tests, Docker for Mac will often crash and reboot with these errors:

```
Unexpected API error for [redacted]vm_cc_1 (HTTP code 500)
Response body:
dial unix /Users/bene/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused

Unexpected API error for [redacted]vm_db_1 (HTTP code 500)
Response body:
dial unix /Users/bene/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused

Unexpected API error for [redeacted]vm_boss_1 (HTTP code 500)
Response body:
dial unix /Users/bene/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused

Unexpected API error for [redacted]vm_redis_1 (HTTP code 500)
Response body:
dial unix /Users/bene/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused
```

### Information

```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.11.6 (build: 15G17023)
logs: /tmp/0F96BFAD-94C3-476E-A4F3-81CD1F5C41ED/20171107-145607.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Run my integration tests suite which runs for ~10 minutes, so that presumably produces a fair amount of load.
  2. Part way through the test suite run, Docker for Mac crashes.

So far, I'm the only one on my team having this problem.

**Comment by BenEinwechter** [comment]
These crashes happen regularly when I have 4+ CPUs enabled for Docker. When I dropped the CPU count to one, the problem seems to go away. As soon as I increase the CPUs to 2 or more, the crashes start happening again.

I'm running a **MacBook Pro (Retina, 15-inch, Mid 2014)**

Here are my specs:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0142.B00
  SMC Version (system):	2.19f12
```

```
  System Version:	OS X 10.11.6 (15G17023)
  Kernel Version:	Darwin 15.6.0
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
```

**Comment by zhanglongyang** [comment]
Had exactly the same issue here, however after running `docker system prune` which saved +8G disk space and restarting docker, it started to work again for me.

Not 100% sure whether it's related though. :)

**Comment by cosimaradu** [comment]
I am also getting 
>["API` error (502): Bad response from Docker engine\n" "API error (500): dial unix /Users/cradu/Library/Containers/com.docker.docker/Data/00000003.00000948: connect: connection refused\n"]

during integration tests.

My specs:
MacBook Pro (Retina, 15-inch, Mid 2014) with macOS 10.13.1 (17B1003)
Docker: Version 17.09.1-ce-mac42 (21090) Channel: stable 3176a6af01
Storage Driver: overlay2

**Comment by BenEinwechter** [comment]
@cosimaradu Does the problem go away when you reduce Docker for Mac's CPUs to 1? `Docker for Mac menu > Preferences > Advanced`

Certainly not an ideal solution because everything runs slower, but at least it resolves the problem for me.

**Comment by cosimaradu** [comment]
It does go away, but it's not an acceptable solution.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac and reopen if the problem persists.
