### ISSUE TITLE
0B8B0774-DB0A-4091-BBE5-5C2E60B45AE4

### ISSUE THREAD

**Issue by zombiegit** [docker/for-mac#2212]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing. Please reopen with proper description if issue still present.
