### ISSUE TITLE
Docker does not download any image

### ISSUE THREAD

**Issue by pablobastidasv** [docker/for-mac#222]
### Expected behavior
After try to download 'jhipster/jhipster-registry:v2.3.0' image, when I do a docker pull <image>, must be downloaded a image normally

### Actual behavior
Docker does not download any image, just show me the next error:

    Using default tag: latest
    Pulling repository docker.io/library/mongo
    Tag latest not found in repository docker.io/library/mongo

### Information

Diagnostic ID: BD65D1FF-D0ED-4718-9686-9ACFEA546CB6
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. With docker started execute 'docker pull mongo'

**Comment by Nihisil** [comment]
I have same problem on the latest stable and beta version (Docker for Mac: version: abf019d)

**Comment by Nihisil** [comment]
I have tried to run docker in the Ubuntu virtual machine and it is working fine. So, issue not in my internet connection.

```
(env)vagrant@vagrant-ubuntu-trusty-64:/vagrant/project$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c04b14da8d14: Pull complete
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
...
```

**Comment by pablobastidasv** [comment]
I will try to do it in a VM with ubuntu, because I did the pull with other internet and works fine. I thought the problem was my internet, but with you comment I have to try that before to call my Internet provider.

**Comment by pablobastidasv** [comment]
Today in a research about the problem, I found this https://forums.docker.com/t/auth-docker-io-on-192-168-65-1-53-no-such-host/16801/12 maybe could help you.
