### ISSUE TITLE
Mac OS screen to docket tty messy code

### ISSUE THREAD

**Issue by Mararesliu** [docker/for-mac#2222]
On Mac OS I use screen command to tty, cannot interact correcttly, but messy code.Any way to correct it?I set screen’s to utf8,but make not effect

**Comment by thaJeztah** [comment]
Can you add some more information, as I requested in your previous issue? https://github.com/docker/docker.github.io/issues/5283#issuecomment-343725770

> I'm guessing you mean the screen command to get access to the VM in which the daemon runs?
> 
> If so; that option is really just for debugging; not developed as a feature for regular use of docker.

(....)

> If you still think there's a bug at hand, you can open a bug report in the Docker for Mac issue tracker; https://github.com/docker/for-mac/issues, but if you do, make sure to provide the _exact_ steps to reproduce.

**Comment by Mararesliu** [comment]
restart docker can temporary fixed

**Comment by adamdicarlo** [comment]
I've seen that. I think you mean the screen output looks garbled _after the first time_ you connect via screen. It's something to do with not properly unattaching the first screen session or something.

**Comment by Mararesliu** [comment]
ok,thx

**Comment by djs55** [comment]
To avoid using `screen`, try a command like
```
docker run -it --privileged --pid=host justincormack/nsenter1
```
As @adamdicarlo says, the console will be garbled if the first screen session is not properly shutdown. I sometimes use `killall SCREEN` for this.
