### ISSUE TITLE
Dokcer version not responding

### ISSUE THREAD

**Issue by ashokkavuri** [docker/for-mac#2226]
### Expected behavior
docker --version
Docker version 17.03.0-ce, build 60ccb22

### Actual behavior
docker version
-bash: docker: command not found
### Information

Docker for Mac: version: 17.11.0-ce-rc3-mac38 (b2149617ed8d7263c9c035e25fe71d147169348c)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/A8A2C6C8-F301-46F8-9A6A-3FD6E74B63C8/20171113-095534.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

   

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by khs1994** [comment]
`$ echo $PATH` output?
