### ISSUE TITLE
Docker build hangs on macosx 

### ISSUE THREAD

**Issue by marcosrmendezthd** [docker/for-mac#2227]
### Expected behavior

`docker build .` should provide feedback.

### Actual behavior

It looks like it just hangs and doesn't do anything.

### Information

Diagnostic ID: 66837698-6B14-4D31-8C4D-06521882F8E6

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/66837698-6B14-4D31-8C4D-06521882F8E6/20171113-101830.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. echo "FROM scratch" > Dockerfile.scratch
  2. docker build -f Dockerfile.scratch .

Docker command: pull, info and run work.

docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: UVP3:NWNN:OMNP:XBRN:LRWY:KM7F:LW7V:ABV7:GXGO:PBLC:2TP7:ZERL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 80
 System Time: 2017-11-13T15:25:53.584293915Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by marcosrmendezthd** [comment]
i'm able to reproduce this on the following build after upgrading to High Sierra as well:

Version 17.11.0-ce-rc3-mac38 (20152)
Channel: edge
a091b4ad0a

**Comment by akimd** [comment]
I can't reproduce today.

Please, try a more recent version of Docker for Mac.
