### ISSUE TITLE
06987E3C-3DF0-4690-AA1C-C1AF953199B9

### ISSUE THREAD

**Issue by soufianedIonicDev** [docker/for-mac#2238]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing. Please reopen with proper description if issue still present.
