### ISSUE TITLE
Docker CE VM root filesystem is read-only

### ISSUE THREAD

**Issue by spkane** [docker/for-mac#2243]
### Expected behavior

I teach classes about `Docker` and spend some time showing Windows and Mac users some of the underlying components that make Docker work on their platforms. During the part of class about resource limiting, I having historically used `htop` on the underlying VM to demonstrate how limiting CPU impacts the underlying processes. However, this does not seem to be possible anymore. Even trying to remount the root filesystem `rw` fails. It looks like it might be some sort of ISO image now.

Is there any way to make apk work again, via advanced settings or something, for those of us who understand the risks? Or can there be an option added, to make this possible?

```
docker run -it --privileged   --pid=host debian nsenter -t 1 -m -u -n -i sh
apk update
apk add htop
```

### Actual behavior

```
docker run -it --privileged   --pid=host debian nsenter -t 1 -m -u -n -i sh
apk update
ERROR: Unable to lock database: Read-only file system
ERROR: Failed to open apk database: Read-only file system
```

### Steps to reproduce the behavior

1. docker run -it --privileged   --pid=host debian nsenter -t 1 -m -u -n -i sh
2. apk update

**Comment by djs55** [comment]
Thanks for your report and sorry for the inconvenience.

If it's just the processes you need to view, would this work:
```
docker run -it --privileged --pid=host alpine sh
apk update
app add htop
```
-- this will create a privileged container with a read/write filesystem but it will share the host `pid` namespace so you can see all the processes. Is this sufficient for your needs or is there something else missing?

**Comment by spkane** [comment]
@djs55 You are completely correct. That will do the job. I should of jumped right to this, since I use CoreOS all the time, but for some reason I was just focused on VM filesystem.

Thank you. That gives me a good solution to work with.
