### ISSUE TITLE
Use on demand loading for com.docker.vmnetd?

### ISSUE THREAD

**Issue by pixlwave** [docker/for-mac#2244]
### Expected behavior
With `Start Docker when you log in` disabled, the process com.docker.vmnetd is started when the machine starts up.

### Actual behavior
With `Start Docker when you log in` disabled, the process com.docker.vmnetd should not be started until the Docker app is opened.

### Information

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13.1 (build: 17B48)
logs: /tmp/9D4A1311-279D-4F87-9C78-CBD7C1C4BE21/20171119-224846.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Uncheck `Start Docker when you log in` in Docker preferences.
  2. Reboot your mac.
  3. Open Activity Monitor and search for com.docker.vmnetd

### Discussion

I believe that this could be fixed simply by setting `RunAtLoad` to `false` in the LaunchDaemons com.docker.vmnetd.plist file and instead setting `OnDemand` to `true`, although there may be a specific reason I'm unaware of for not using on demand loading.

**Comment by akimd** [comment]
vmnetd is really lightweight and design to run all the time.

Thanks!
