### ISSUE TITLE
Docker release 17.09 not stable for Mac OS High Sierra ?

### ISSUE THREAD

**Issue by cheenamalhotra** [docker/for-mac#2246]
### Expected behavior
Docker latest Stable release not available for download or doesn't work.
### Actual behavior
Should be able to download and install docker on Mac OS High Sierra 10.13.1
### Information
1. Tried to download Docker for Mac from this URL:
https://download.docker.com/mac/stable/19661/Docker.dmg which doesn't work.
Found on this page: https://docs.docker.com/docker-for-mac/release-notes/#stable-release-notes
2. Downloaded Docker.dmg from this page: https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac
but downloaded dmg has no fish icon and fails to install. 
This is what the downloaded Docker.app looks like:
![screen shot 2017-11-19 at 10 08 34 pm](https://user-images.githubusercontent.com/13396919/33004546-429a23a0-cd76-11e7-89dc-d197b475770c.png)
### Steps to reproduce the behavior
  1. Use Mac OS High Sierra (with all latest updates) - v10.13.1
  2. Attempt to download docker from both pages
  3. Not able to install Docker successfully.

**Comment by zhihongzeng2002** [comment]
Same problem here. 
After update to 10.13.1.
$docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I tried several ways by googling around, and failed to fix it

**Comment by nataliemona** [comment]
Same issue here!
Stuck on "Docker needs privileged access." with a beachball.
