### ISSUE TITLE
docker ps hangs on macOS

### ISSUE THREAD

**Issue by mcqj** [docker/for-mac#2252]
### Expected behavior
docker ps should return a list of running containers

### Actual behavior
docker ps hangs forever

### Steps to reproduce the behavior

Unknown - happens after docker containers have been running for some time.

### Docker Version
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c

### macOS Version
10.13.1

**Comment by boss94** [comment]
+1 same here

**Comment by akimd** [comment]
Please try more recent releases (https://docs.docker.com/docker-for-mac/install/), and report if you still have problems.
