### ISSUE TITLE
Fresh install of Docker for Mac from website installs out of date docker-compose

### ISSUE THREAD

**Issue by skylerbunny** [docker/for-mac#2253]
### Expected behavior
Installing Docker for Mac from https://download.docker.com/mac/stable/Docker.dmg (via https://store.docker.com/editions/community/docker-ce-desktop-mac ) installs Docker 17.09.X (newest stable), and installs docker-compose version 1.17.1, build 6d101fb, either because it's part of the dmg, or because searching for updates should identify a newer version of (only) docker-compose to install.

### Actual behavior
Installing Docker for Mac from https://download.docker.com/mac/stable/Docker.dmg (via https://store.docker.com/editions/community/docker-ce-desktop-mac ) installs docker-compose version 1.16.1, build 6d1ac21 and makes no attempt to update docker-compose.

### Information

  - Docker-compose 1.17.X is needed to process docker-compose files with version 3.4 compose syntax. The minimum required version to use v3.4 is Docker 17.09.X, as per https://docs.docker.com/compose/compose-file/ .
  - Since Docker for Mac purports to 'keep docker-compose up to date' without user intervention, and minimum requirements in the form of Docker Engine 17.09.X are met by Docker for Mac, for docker-compose 1.17.X, I expect that Docker-compose should be updated when I 'check for updates', since its syntax and underlying functionality should be available.

Ref: https://github.com/docker/compose/releases: "If you're a Mac or Windows user, the best way to install Compose and keep it up-to-date is Docker for Mac and Windows."

I contend that this is not "up-to-date" by definition.

### Steps to reproduce the behavior

  1. Install Docker for Mac from the Docker Store.
  2. 'Check for Updates'.
  3. No updates are processed.

**Comment by gtardif** [comment]
Hi @skylerbunny, We'll have a stable release coming next week that should include docker-compose update, as well as a few bug fixes.
If you want to keep up to date with the latest docker versions available, you can also switch to the edge channel, where releases are happening more frequently.
