### ISSUE TITLE
"Your feedback is important to us" dialog appears every time the Mac boots

### ISSUE THREAD

**Issue by weeix** [docker/for-mac#2254]
### Expected behavior
Docker asks for feedback **only once**

### Actual behavior
Docker asks for feedback every time the Mac boot

![Picture of "Your feedback is important to us" dialog](https://user-images.githubusercontent.com/6592791/33106150-69215c7a-cf63-11e7-8438-69ec9b817acb.png)

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

    > Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
    > macOS: version 10.12.6 (build: 16G1036)
    > logs: [/tmp/FF801849-C579-4C21-B119-B0F40E47136B/20171122-084924.tar.gz](https://github.com/docker/for-mac/files/1493638/20171122-084924.tar.gz)
    > [OK]     db.git
    > [OK]     vmnetd
    > [OK]     dns
    > [OK]     driver.amd64-linux
    > [OK]     virtualization VT-X
    > [OK]     app
    > [OK]     moby
    > [OK]     system
    > [OK]     moby-syslog
    > [OK]     db
    > [OK]     env
    > [OK]     virtualization kern.hv_support
    > [OK]     slirp
    > [OK]     osxfs
    > [OK]     moby-console
    > [OK]     logs
    > [OK]     docker-cli
    > [OK]     menubar
    > [OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install/Reinstall Docker

**Comment by gtardif** [comment]
Hi @weeix , I could not download your diagnostics mentioned above, did you upload them ? could you try uploading diagnostics once more ? 
And you might want to try removing the file : ` ~/Library/Group Containers/group.com.docker/npsId` that will reset the feedback process.

**Comment by weeix** [comment]
Hi @gtardif , sure: [20171122-084924.tar.gz](https://github.com/docker/for-mac/files/1499022/20171122-084924.tar.gz)

I'll try your solution. Thanks!

**Comment by akimd** [comment]
Could you please try with the current Stable release?  And reopen if the trouble persists.
