### ISSUE TITLE
ve images

### ISSUE THREAD

**Issue by ksowa** [docker/for-mac#2259]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by subfuzion** [comment]
![hate-when-this-happens](https://user-images.githubusercontent.com/159738/33231671-2c56a8b6-d1ae-11e7-83ad-f63d6c35f492.jpg)

**Comment by thaJeztah** [comment]
Looks like this was opened by accident; closing
