### ISSUE TITLE
Error running from Launchpad and command line on macOS High Sierra

### ISSUE THREAD

**Issue by rupe120** [docker/for-mac#2266]
### Expected behavior
I just tried to open the Docker app from Launchpad on macOS High Sierra

I also can't run Docker from the command line

### Actual behavior
I received the following trying to open the Docker app from Launchpad on macOS High Sierra

From the command line I receive a segmentation fault 11 error when I try to do anything

### Information

Diagnostic ID: A97438CB-3B0F-46D6-B0B0-7200C6586258
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.13.1 (Build 17B48)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/joshuarusso/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/A97438CB-3B0F-46D6-B0B0-7200C6586258/20171124-172604/qemu-img-check.stdout 2> /tmp/A97438CB-3B0F-46D6-B0B0-7200C6586258/20171124-172604/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/joshuarusso/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/joshuarusso/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/joshuarusso/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/joshuarusso/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/joshuarusso/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Go to Luanchpad 
2. Run Docker

**Comment by nxmohamad** [comment]
Have you tried reinstalling?

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
