### ISSUE TITLE
macOS Beta 5  failed migration: failed to update app version history

### ISSUE THREAD

**Issue by glynjackson** [docker/for-mac#227]
Testing Docker on macOS: Version 10.12 (Build 16A286a) Beta 5. Opened Docker for mac and crashes. Cannot start Docker or reinstall anymore. Error given

**failed migration: failed to update app version history**

Upgraded from macOS Beta 4 to Beta 5 when this happened.

### Information
```
Diagnostic ID: 0A077EB2-AA15-4AA4-9ED5-01CE87D361B0
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/glyn/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/glyn/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/glyn/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
```
### Steps to reproduce

1. Upgrade from Mac Beta 4 to 5
2. Start Docker for mac from applications

**Comment by mprokopov** [comment]
I've had success with docker for mac stable

**Comment by glynjackson** [comment]
Tried both, afraid. This issue I assume is still down to the ``Go`` in that Docker needs to be built against the 1.7 version. Still, after the update to Beta 5 of the os (test mac)  more things are failing i.e now, I cannot start Docker without a crash, just in case this is a new issue I decided to post

**Comment by glynjackson** [comment]
Actually, beginning to think this is another issue. The error is 'failed migration: failed to update app version history' where before the update this was working. Problem is I cannot reinstall.

**Comment by glynjackson** [comment]
Deleted Docker For Mac including ``~/Library/Containers/com.docker.docker`` then installed and managed to get back in )

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
