### ISSUE TITLE
No way to hide menu bar icon

### ISSUE THREAD

**Issue by Aquilosion** [docker/for-mac#2272]
### Expected behavior

There should be an option in Docker's preferences to show or hide the menu bar icon.

### Actual behavior

There is no such preference, and it is very difficult if not impossible to hide the icon while keeping the Docker daemon running.

### Information

Any application which places an icon in the menu bar should provide an option to hide it, else someone with many necessary daemons running which come with unremovable menu bar icons would end up with a cluttered menu bar.

If the menu bar was hidden, one could access the preferences dialog by 'opening' the Docker application again while it was already running. Other options which are currently revealed under Docker's menu bar icon can be moved to the standard menu bar items on the left-hand-side of the screen when the preferences window is visible.

**Comment by pgayvallet** [comment]
The docker app is not only the preferences dialog. There are other windows that can currently only be opened from the menu bar. Anyway, this is a won't do.

Closing.

**Comment by kenahoo** [comment]
I came here to request the same thing, I'm disappointed that it's been rejected.  

I don't think Docker needs to put stuff in my menu bar any more than Apache HTTPD or any other daemon does.  Additionally, it's confusing to me that launching the "Docker" application in /Applications doesn't actually appear to do anything visually when I launch it.  And since it doesn't really look like a whale anymore (no eye, no color, a bunch of squares and a semicircle?) it's not even really clear what application it belongs to at first.

I would prefer Docker to just stay out of the menu bar, but failing that, I like @Aquilosion's suggestion of putting the menu icon's functionality into the app that gets foregrounded when looking at the preferences dialog.  I'd add a request to open that when launching /Applications/Docker.app .

**Comment by ahtcx** [comment]
I think the icon should be optional, the icon and menu doesn't offer anything that a simple UI couldn't and as @kenahoo said - it's confusing there's no UI when launching the application.

I hate clutter on my menu-bar and Docker isn't important enough to have a spot there.

**Comment by raxod502** [comment]
@pgayvallet 

Would you mind providing an explanation for why

> this is a won't do

?

Clearly it's not because

> There are other windows that can currently only be opened from the menu bar

since an alternative way to open these other windows could be implemented.

**Comment by slezica** [comment]
I would also like to see this feature. I _never_ use the menu button other than to open the dashboard ("Preferences"), and simply running the application would do for that use-case.

**Comment by slezica** [comment]
Having this would be nice. I already have enough icons as it is, and I _very_ rarely use the Docker item (other than to open Preferences).

In my opinion, running the application should be the way to access functionality. 99% of the time I have nothing to tell the docker daemon other than "keep running".

**Comment by rodcheater** [comment]
Not providing an option to remove the menu bar extra is in violation of the macOS human interface guidelines.

https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/

**Comment by fulldecent** [comment]
I don't want a daemon at all. I don't want "start up at login" or all these other anti-features.

Instead I want it to work exactly like `ssh`. You ssh into a host, now you're connected. Then you exit and you are no longer connected -- nothing is running.

I have lived many years without an "ssh connection manager" or a "start at login" ssh client.

**Comment by abathingchris** [comment]
Please reconsider this, or answer some of the concerns if you can.  It's strange that we have to pay for third party utilities to hide menu bar items that are suppose to be handled by the actual app providing the menu bar item.

**Comment by sifex** [comment]
> Please reconsider this, or answer some of the concerns if you can. It's strange that we have to pay for third party utilities to hide menu bar items that are suppose to be handled by the actual app providing the menu bar item.

Even then, Bartender is incompatible with removing Docker. There is literally no way to remove it.

**Comment by danepowell** [comment]
I found that https://github.com/Mortennn/Dozer (a free alternative to Bartender) can remove ill-behaving ilk such as the Docker icon.

**Comment by sifex** [comment]
@danepowell I found that on OS Catalina with Bartender 3 and Docker 2.0.4.1, docker seems to behave itself. Not sure what solves it though :S

**Comment by joeltornatore** [comment]
+1 to this. i don't want the icon in the menu bar.

**Comment by woodcockjosh** [comment]
This is stupid. you're forcing a space in my dock to be used for something that runs in the background. Cool politics losers.

**Comment by woodcockjosh** [comment]
Hey looks like latest version doesn't force a tray icon. Thanks @pgayvallet!

**Comment by abathingchris** [comment]
Thank you very much.

**Comment by kenahoo** [comment]
Still no way to get it out of the menu bar though, right?

**Comment by rokcarl** [comment]
I have icons in my menu bar that actually matter and I actively check.
* What's the time?
* How much time is left in my pomodoro timer?
* Am I still connected to my mobile hotspot?
* What's the ping to google (will my audio/video chat stutter)?

And then there's Viber. And Docker. Can you make it optional?

**Comment by theory** [comment]
> Hey looks like latest version doesn't force a dock icon. Thanks @pgayvallet!

Don't see a preference for this. I'm running 2.2.0.5 (43884). Could have sworn I used to have a way to hide the Dock icon when Docker was running.

**Comment by theory** [comment]
Woah, wait, I just quick Docker and started it again, and now the Dock icon is gone. 🤯 🥳

**Comment by skylerrichter** [comment]
I'm OCD and the Docker icon in the menu bar hurts my brain. Please give me the option to hide the icon and cure my OCD.

**Comment by theory** [comment]
LOL @skylerrichter, I have the same desire for a clean menu bar, and Docker's far from the only offender here. But this week I learned about [Bartender](https://www.macbartender.com) and my menu bar has never been so delightfully clean.
