### ISSUE TITLE
Docker - Not starting

### ISSUE THREAD

**Issue by guninkhanna** [docker/for-mac#2273]
### Information

- I have been trying to debug this issue for a while now, I have tried to uninstall docker ( using the uninstall script in the toolbox) 
- I'm not able to access any options ( like preferences , check for updates etc) from the menu bar
- I have also tried to manually remove `com.docker.docker` to resolve any conflicts
- Factory reset opens a prompt which results in a not responding state

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A405)
logs: /tmp/76D5DE63-480D-454C-BC34-5D950284B318/20171128-130936.tar.gz
failure: Docker.qcow2 missing: the VM has never been started 
[ERROR]  db.git
         db.git check failed with: (Failure
  "exec: cd \"/tmp/76D5DE63-480D-454C-BC34-5D950284B318/20171128-130936/database\" && git checkout master: exit 128")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to 
         /Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:
Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to 
        /Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by dinamic** [comment]
Same issue here after upgrading to the most up to date version.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
