### ISSUE TITLE
COPY failed while building image via Dockerfile

### ISSUE THREAD

**Issue by arinto** [docker/for-mac#2277]
### Expected behavior
Given this line in Dockerfile:
`COPY requirements.txt /`

Docker should successfully copy the file.

### Actual behavior
COPY failed: stat /var/lib/docker/tmp/docker-builder773763859/requirements.txt: no such file or directory

### Information
Diagnostic ID:4C165E27-690A-40D7-A517-1D689D63B8FB
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/4C165E27-690A-40D7-A517-1D689D63B8FB/20171129-155949.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Create Dockerfile which has `COPY` line
  2. Run docker build - < Dockerfile

**Comment by arinto** [comment]
Docker for Mac uses [virtualization](https://docs.docker.com/docker-for-mac/docker-toolbox/#the-docker-for-mac-environment). I'm thinking to [go inside the VM]() and build my Dockerfile there. What do you think?

**Comment by riveryc** [comment]
try use ```docker build .```
see what happen.

**Comment by csfercoci** [comment]
Can you pleas reopen . On macos Catalina 10.15.5  appear the same 

```
FROM oracle/graalvm-ce:20.1.0-java11

COPY . /build
COPY pom.xml /build/
```
end with 
`COPY failed: stat /var/lib/docker/tmp/docker-builder651829165/pom.xml: no such file or directory
` 
Command was 
`docker build  .  -t csfercoci/quarkus 
`

version 
`Docker version 19.03.8, build afacb8b
`
