### ISSUE TITLE
Error while running on idle on macOS Beta 5

### ISSUE THREAD

**Issue by ChrJantz** [docker/for-mac#229]
### Expected behavior
No error occurance

### Actual behavior
Error message thrown 

### Information

Diagnostic ID: 5F9F59D4-0737-426F-95EA-EA0365221E64
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A286a)

### Steps to reproduce

1. Have docker for mac running
2. Read websites on Google Chrome
3. Error happened

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
