### ISSUE TITLE
Docker for Mac crash computer - possibly?

### ISSUE THREAD

**Issue by Krzysiaczek-at-theFoundry** [docker/for-mac#2292]
I'm not sure if the crash of Mac was caused by the running Docker but Docker was a victim of some other problems. 

I run about dozen containers including 3 docker-sync, 3 MySQL DB, 1 java server with selenium for Behat testing and a few PHP-apache ones. 

Today there was an update of Docker-sync to 0.52 version (I'm not sure if this might be related).

Suddenly everything became frozen (in OS) and I had to hard reset the whole system.

After the restart, the only thing complained about the problems was Docker. I've tried to run diagnostic but even this has failed. I had to restore to default (factory) setting so I was able to run diagnostics (which took an enormous amount of time this time) and to file this report. 

The report looks OK but maybe someone will find something useful in the uploaded files:

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/148B7441-2799-4D9E-9368-F08DDAFEFAEC/20171206-125848.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by Krzysiaczek-at-theFoundry** [comment]
Here are the screenshots from docker stage after restart of the system and reporting falling down
![screenshot 2017-12-06 12 52 15](https://user-images.githubusercontent.com/15616262/33670952-2d679956-da9e-11e7-8406-a0697b85a002.png)
<img width="1026" alt="screenshot 2017-12-06 12 54 23" src="https://user-images.githubusercontent.com/15616262/33670961-344e66dc-da9e-11e7-9f31-59f311f01662.png">

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
