### ISSUE TITLE
Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.` when using docker login -u _json_key -p "$(cat developer-key.json)" https://gcr.io

### ISSUE THREAD

**Issue by mantenamanoj007** [docker/for-mac#2295]
### Expected behavior
Should login into gcr.io 

### Actual behavior
Throwing Error when Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`

All the keys and are correct and the same command is getting executed in some other system but not in my system.

**Error**
Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`

### Information

  - Admins-MacBook-Pro:conf admin$ docker login -u _json_key -p "$(cat developer-key.json)" https://gcr.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`

  - can use some key in json format which named developer-key.json

### Steps to reproduce the behavior

  1. Login in Docker Hub Using the Password as json using docker login -u _json_key -p "$(cat developer-key.json)"

**Comment by jfpucheu** [comment]
same pb , It works 1 time and now impossible to push

**Comment by terry-xiaoyu** [comment]
same problem, the 'docker login' never works on my Mac. I am using the version: 17.12.0-ce-mac46.

**Comment by terry-xiaoyu** [comment]
Finally I solved my problem by deleting the /usr/local/bin/docker-credential-osxkeychain. But I don't know why. 😂

https://github.com/docker/docker-credential-helpers/issues/65

**Comment by lexuszhi1990** [comment]
@terry-xiaoyu nice try

**Comment by zhang-zedong** [comment]
another trouble: `error getting credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: `

**Comment by terry-xiaoyu** [comment]
@zhang-zedong 
Then how about this? https://github.com/docker/for-mac/issues/1540#issuecomment-304280880
Remove the line "credsStore": "osxkeychain" from ~/.docker/config.json.
It works on my Mac.

**Comment by lotusbaba** [comment]
Deleting the file /usr/local/bin/docker-credential-osxkeychain worked for me

**Comment by naydoummar** [comment]
Unchecking "Securely store docker logins in macOS keychain" in Docker preferences did it for me.

**Comment by ndbroadbent** [comment]
Thanks @lotusbaba, that was what fixed it for me.

**Comment by sluo668899** [comment]
Thanks rm /usr/local/bin/docker-credential-osxkeychain fixed it for me.

**Comment by ianpojman** [comment]
@naydoummar 's fix worked for me as well

**Comment by Inon-zhang** [comment]
Remove the line "credsStore": "osxkeychain" from ~/.docker/config.json.
It works on my Mac too.
But delete /usr/local/bin/docker-credential-osxkeychain in Mac is not OK.

**Comment by tatharoy** [comment]
Unchecking "Securely store docker logins in macOS keychain" in Docker preferences and removing the line "credsStore": "osxkeychain" from ~/.docker/config.json did it for me. Thanks everyone

**Comment by lawtech0902** [comment]
`rm /usr/local/bin/docker-credential-osxkeychain`  worked for me. thx

**Comment by fxfactorial** [comment]
This is still an issue, please fix.

**Comment by amitkrout** [comment]
Deselecting "Securely store docker logins in macOS keychain" in Docker preferences and to apply the changes do the Docker restart also works for me

**Comment by Argonus** [comment]
Deselecting `Securely store docker logins in macOS keychain` helped but I had to also remove all containers, restart docker and sign in using an app instead of a console.

**Comment by dkdhinakaran** [comment]
worked, 

as per 

Remove the line "credsStore": "osxkeychain" from ~/.docker/config.json.
It works on my Mac too.
But delete /usr/local/bin/docker-credential-osxkeychain in Mac is not OK.

**Comment by reza** [comment]
just remove the `osxkeychain` from `~/.docker/config.json` as below:

`"credsStore": ""`

**Comment by ry4nz** [comment]
the problem is still seen 18.06.1-ce-mac73 (26764)  fixed by ```
rm /usr/local/bin/docker-credential-osxkeychain
```

**Comment by sherghan** [comment]
In my case (_18.06.1-ce, build e68fc7a_):
* `mv /usr/local/bin/docker-credential-osxkeychain /usr/local/bin/docker-credential-osxkeychain.bkp`
...failed to solve the problem.
* `sed -i.bkp -e 's/\("credsStore": \)"osxkeychain"/\1""/' ~/.docker/config.json`
...did solve the problem.

Important thing to note is that problem appeared when I was trying to do things remotely (via SSH).

**Comment by jiangnight** [comment]
@sherghan 
my case (18.06.1-ce , build e68fc7a) worked: 
* first rm /usr/local/bin/docker-credential-osxkeychain
* modify ~/.docker/config.json    "credsStore": ""
* restart docker

**Comment by marcoferra** [comment]
> Unchecking "Securely store docker logins in macOS keychain" in Docker preferences did it for me.

works for me

**Comment by pgun9476** [comment]
> Finally I solved my problem by deleting the /usr/local/bin/docker-credential-osxkeychain. But I don't know why. 😂
> 
> [docker/docker-credential-helpers#65](https://github.com/docker/docker-credential-helpers/issues/65)
> 
> **Edited**:
> Removing "credsStore": "osxkeychain" from ~/.docker/config.json instead.

terry-xiaoyu, Thank you Sir!

**Comment by CoreyCole** [comment]
I did `rm /usr/local/bin/docker-credential-osxkeychain` and now when I try to `docker login`:
```
Error saving credentials: error storing credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: ``
```
😢

**Comment by Ilyes512** [comment]
I have never seen so much BAD information/advice. You dont just delete a binary or save your password unencrypted in a plain text file...

**Comment by programingnotes** [comment]
@Ilyes512 we can't really blame them. Most folks using docker aren't sysadmins or DevOps so won't really understand the security implication. 

The folks at fault are the ones writing the software ... the entire use experience for non-enterprise users of Docker suite of services is HORRIBLE; security flaws galore, no response to issues, and documentation filled with gapping holes. 

What they need to do is make it clear that their products shouldn't be used in production by beginners or even those with intermediate experience, that they do not provide support for ce (non-enterprise) services.

**Comment by Ilyes512** [comment]
@SelinGungor Thats indeed the original issue with the answer.

**Comment by gatkinso** [comment]
> @zhang-zedong
> Then how about this? [#1540 (comment)](https://github.com/docker/for-mac/issues/1540#issuecomment-304280880)
> Remove the line "credsStore": "osxkeychain" from ~/.docker/config.json.
> It works on my Mac.

This seems to be a good immediate workaround.

**Comment by akalankapagoda** [comment]
> Finally I solved my problem by deleting the /usr/local/bin/docker-credential-osxkeychain. But I don't know why. 
> 
> [docker/docker-credential-helpers#65](https://github.com/docker/docker-credential-helpers/issues/65)
> 
> **Edited**:
> Removing "credsStore": "osxkeychain" from ~/.docker/config.json instead.

FYI : This works for Ubuntu as well. Just that the name might be different than "osxkeychain". Mine was just "pass". Removed this line and now everything's good.

**Comment by danilomagalhaes** [comment]
> Finally I solved my problem by deleting the /usr/local/bin/docker-credential-osxkeychain. But I don't know why. 
> 
> [docker/docker-credential-helpers#65](https://github.com/docker/docker-credential-helpers/issues/65)
> 
> **Edited**:
> Removing "credsStore": "osxkeychain" from ~/.docker/config.json instead.

Solve my problem on Ubuntu 18.04. Thank you!

**Comment by Cosmos-it** [comment]
> Deleting the file /usr/local/bin/docker-credential-osxkeychain worked for me

This worked. 💯

**Comment by kennycontreras** [comment]
`rm /usr/local/bin/docker-credential-osxkeychain` worked for me too! thanks.-

**Comment by jacobtani** [comment]
rm /usr/local/bin/docker-credential-osxkeychain worked for me too! 
Thank you!

**Comment by ryanisnan** [comment]
This is still an issue, and the command `rm /usr/local/bin/docker-credential-osxkeychain` worked as well.

**Comment by ivanilves** [comment]
Worked for me as well on MacOSX Mojave! 👍

**Comment by atg-abhishek** [comment]
I had to run this`rm /usr/local/bin/docker-credential-osxkeychain`, remove "credsStore": "osxkeychain" from ~/.docker/config.json and deselect "Securely store docker logins in macOS keychain" in Docker preferences (yes, needed to do all 3) before the login worked. Also, remember to restart Docker after doing all this.

**Comment by dustinrue** [comment]
Hey everyone. Here is the proper solution to this issue. The problem depends on how you are accessing your mac. If for some reason you are opening a terminal window that isn't creating your shell correctly or you are using ssh to access a remote mac your keychain will not be unlocked. You can unlock it like this

`security unlock-keychain`

You will be prompted for your password. Enter that and docker login will then work properly.

**Comment by jlsubia404** [comment]
I had the same problem on my mac, I fix it with this tutorial https://www.cnblogs.com/robinunix/p/11304237.html

**Comment by dahu33** [comment]
> I had the same problem on my mac, I fix it with this tutorial https://www.cnblogs.com/robinunix/p/11304237.html

Locking and Unlocking the keychain solved the issue for me as well...

**Comment by glongh** [comment]
Removing "credsStore": "desktop" from ~/.docker/config.json worked for me.

**Comment by tnixa** [comment]
I had a similar problem on Windows and the workaround was to delete the following files...
C:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.exe
C:\Program Files\Docker\Docker\resources\bin\docker-credential-wincred.exe

**Comment by psytron** [comment]
> @zhang-zedong
> Then how about this? [#1540 (comment)](https://github.com/docker/for-mac/issues/1540#issuecomment-304280880)
> Remove the line "credsStore": "osxkeychain" from ~/.docker/config.json.
> It works on my Mac.

This was only working solution on OSX Mojave

**Comment by psanders** [comment]
The only solution that worked for me was to:

Try opening Keychain Access
Right-click on the login keychain
Lock it and then unlock it again

Credits to: [@dennislky ](https://github.com/aws/aws-cli/issues/3264)

**Comment by pswargam** [comment]
> I solved by doing:
> 
>     1. Factory reset of docker for mac
> 
>     2. `docker login` succeeded

This worked for me

**Comment by sgtsquiggs** [comment]
In my case this was caused by a system password change. Locking/unlocking the "login" keychain resolved this issue for me, as @psanders, @dustinrue, and @Ilyes512 have all reported.

Don't follow the bad advice here - just lock/unlock your keychain.
