### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by iformacio** [docker/for-mac#230]
### Expected behavior
Docker starts
### Actual behavior
Docker doesn't start
### Information

Diagnostic ID: D9F4AFA2-14F8-4C98-976D-F3B0467B6D77
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start docker
2. Nothing happens.

**Comment by iformacio** [comment]
Reset to defaults and it worked.

**Comment by ajthenewguy** [comment]
How do you reset to defaults??
