### ISSUE TITLE
Docker 1.12.3 not working on OSX 10.13.2 (17C88)

### ISSUE THREAD

**Issue by abhaynahar** [docker/for-mac#2303]
### Information

Diagnostic ID: 8FE5F2E2-9C32-4EE8-AE4A-C66D8A04F77F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.13.2 (Build 17C88)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/abhaykumar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/8FE5F2E2-9C32-4EE8-AE4A-C66D8A04F77F/20171211-114322/qemu-img-check.stdout 2> /tmp/8FE5F2E2-9C32-4EE8-AE4A-C66D8A04F77F/20171211-114322/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/abhaykumar/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/abhaykumar/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/abhaykumar/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/abhaykumar/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/abhaykumar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. On OSX 10.13.2 (17C88)
2. Install Docker 1.12.3
3. Try to start docker, you will face the above error.

**Comment by akimd** [comment]
Please, try a more recent version of Docker for Mac.
