### ISSUE TITLE
Hyperkit eating resources

### ISSUE THREAD

**Issue by bob22cat22** [docker/for-mac#2307]
### Expected behavior
My machine to not act posessed

### Actual behavior
Hyperkit eating resources leaving docker dead and mac very very slow

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Restart my mac with Docker enabled
  2. after a few mins, hyperkit takes over CPU and starts writing to disk
  3. can't restart docker because it hangs, have to use activity manager to kill process
  4. running several small containers and can't use 'docker ps' to see because it hangs

**Comment by bob22cat22** [comment]
Also, diagnostic hangs so can't proceed with that either.

**Comment by usuhamlet** [comment]
I am having a similar issue. I have a late 2015 iMac with 4 GHz Intel Core i7 processor, 24 GB 1600 MHz DDR3 memory and running mac os High Sierra (10.13.2). The last couple of days I have come in to find my machine has shutdown unexpectedly. I run Docker CE 17.12.0-ce-mac46 (21698). When I check CPU and memory usage hyperkit is using around 1% CPU and 1.2 GB of memory without running any containers. I ran the Docker diagnostics and the report came back stating that everything was okay. I am hoping that shutting Docker down over night will keep my machine from shutting down.

**Comment by nmccready** [comment]
To reiterate with more detail. My system runs 10 fold better with all my docker resources running under a virtual box alpine VM than directly on my mac.
