### ISSUE TITLE
Please support . thanks 

### ISSUE THREAD

**Issue by feiout** [docker/for-mac#2312]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Hi!

What exactly do you mean?

**Comment by pgayvallet** [comment]
No reply from author. 

Closing. Please reopen with proper description and diagnostic id if necessary.
