### ISSUE TITLE
DNS resolver doesn't work in pods

### ISSUE THREAD

**Issue by jpetazzo** [docker/for-mac#2316]
I do this:

```
kubectl run -ti --restart=Never--image=alpine pingpong$$ ping goo.gl
```

### Expected behavior

`ping` runs in the pod and pings `goo.gl`

### Actual behavior

```
ping: bad address 'goo.gl'
```

### Information

Diagnostic ID: 396C6F15-9F0E-41D5-8FE9-93440261F5A8

### Keywords

dns resolver resolving nameserver

(Because just "DNS" doesn't quite help ;-))

**Comment by guillaumerose** [comment]
Thanks for reporting. I can reproduce. We will look at it now.

**Comment by guillaumerose** [comment]
This is due to bridge network. We are looking at a solution.

**Comment by guillaumerose** [comment]
@ijc found the solution. The fix should be available in the next release (with rc3 I suppose).

**Comment by guillaumerose** [comment]
The fix is available now. Just update to the latest edge version.

**Comment by jpetazzo** [comment]
Confirming all good with version 17.12.0-ce-rc3-mac43 (21270). Thank you!
