### ISSUE TITLE
[macos sierra] docker gets unresponsive after a while

### ISSUE THREAD

**Issue by kesselborn** [docker/for-mac#232]
### Expected behavior
Docker should not stop working after a while

### Actual behavior
docker gets unresponsive after a while (where this can be a few minutes to a few hours), restarting does not work ... quitting and starting works until it stalls next time. 
The behaviour happens faster when using more complex docker-compose setups. When using compose, the error is usually 

Bad response from Docker engine

### Information

Diagnostic ID: 69B3996E-DCEC-4FCD-94A2-D24366F89F85
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

start and stop instances on macos sierra ... note: this has been happening to me throughout the beta phase as well but as docker & macos were beta I ignored the fact.

**Comment by glynjackson** [comment]
could be related to https://github.com/docker/for-mac/issues/64

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
