### ISSUE TITLE
docker ps filter for started state stopped working on edge(k8s) version

### ISSUE THREAD

**Issue by lalyos** [docker/for-mac#2324]
### Expected behavior
list containers in "started" state

### Actual behaviorexit code:1 with an error message
```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/json?filters=%7B%22status%22%3A%7B%22started%22%3Atrue%7D%7D: EOF
```

### Information

I have updated my edge version to the latest to play around with k8s,
and one of my bash aliases stopped working:

```
docker ps -q --filter=status=started
```

### Steps to reproduce the behavior

  1. Run the command: `docker ps -q --filter=status=started`

**Comment by pgayvallet** [comment]
Reproduced, thanks, gonna look into it.

**Comment by pgayvallet** [comment]
Fixed on latest edge.
