### ISSUE TITLE
Docker for Mac update error

### ISSUE THREAD

**Issue by electricsrini** [docker/for-mac#2332]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SalvatorePollaci** [comment]
Same here. Had to reset docker to factory settings after latest update!

**Comment by pgayvallet** [comment]
Closing.

Please reopen with proper description and diagnostic if still occurring.
