### ISSUE TITLE
Failed to update machine migration state

### ISSUE THREAD

**Issue by Lucifer** [docker/for-mac#234]
### Expected behavior

Installation without error.

### Actual behavior

Failed installation

### Information

Diagnostic ID: CEF03A9C-7ED0-4D97-98E3-3379FA5F035E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A286a)

### Steps to reproduce

1. ...Run Docker to install
2. ...Type password to elevate installation privileges 
![screen shot 2016-08-11 at 11 14 10 am](https://cloud.githubusercontent.com/assets/1987900/17593811/2a816a24-5fb5-11e6-8ed8-c980b80d2c2f.png)
![screen shot 2016-08-11 at 11 15 47 am](https://cloud.githubusercontent.com/assets/1987900/17593826/343e3786-5fb5-11e6-851a-2dec06fc820f.png)

**Comment by Lucifer** [comment]
Attempted to relaunch Docker in order to effect a complete and clean uninstall using the Docker uninstall button.
![screen shot 2016-08-11 at 11 20 13 am](https://cloud.githubusercontent.com/assets/1987900/17594052/e0c22ee0-5fb5-11e6-9187-16aa235b8783.png)

![screen shot 2016-08-11 at 11 20 26 am](https://cloud.githubusercontent.com/assets/1987900/17594058/e4781860-5fb5-11e6-814c-3534c16114f6.png)

**Comment by davzie** [comment]
Any luck on solving this? I am also having these odd issues.

**Comment by dsheets** [comment]
At least some of this is due to #64. I am closing this until that issue is resolved and then we can investigate any other problems you report. Sorry for the inconvenience -- golang and macOS Sierra **Beta** haven't been playing well together.

**Comment by davzie** [comment]
@dsheets No worries, thanks for all the work you do! :)

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
