### ISSUE TITLE
Docker refuses to start after update

### ISSUE THREAD

**Issue by Adeynack** [docker/for-mac#2343]
### Expected behavior

Docker starts.

### Actual behavior

Docker tries to start and then pops an error window proposing to reset to factory default and reset. After doing so, it is failing in the same manner again.

#### Diagnostic ID
DA65FF1E-2003-4643-A241-AD9C6772ABA7

#### Output of the diagnostic

```
Docker for Mac: version: 17.12.0-ce-rc3-mac43 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/DA65FF1E-2003-4643-A241-AD9C6772ABA7/20171218-113224.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ddufourboivi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ddufourboivi/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ddufourboivi/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ddufourboivi/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Upgrade _Docker_ to the last Mac version
  2. Start _Docker_

**Comment by Adeynack** [comment]
# Solved my problem

I realised after posting this issue that I upgraded to an _EDGE_ version of _Docker_. I uninstalled the _EDGE_ version and went for the latest stable one and it then started gracefully.

I will leave this open in case you do want to investigate that diagnostic (may reveal interesting things about the latest _EDGE_ version, could be useful). Feel free to close it.

**Comment by opalenet-yann** [comment]
I have a similar issue also on Edge, my diagnostic id is:
 ACD67E3A-CC3D-40A5-A103-BBC4D0406F63
However, If I just exit Docker after the error and launch it again. It then starts without issue.
For information my docker folder (containing the qcow) is on an external drive, don't know if it's related.

Hope that helps you find the bug.
Thanks for all the work accomplished and for the great tools you're offering to the community.

**Comment by opalenet-yann** [comment]
Fixed by  17.12.0-ce-rc4-mac44 (21438), at least for me.
Thanks for all.

**Comment by henrebotha** [comment]
I am experiencing the same problem. Simply quitting the error message and attempting to relaunch does not work. "Diagnose & feedback" takes too long to work — I left it running for maybe 10 minutes, to no effect. I'm now attempting to reset to factory defaults. This is also taking a long time.

**Comment by henrebotha** [comment]
I eventually had to force quit Docker and relaunch. It now seems to be working.

**Comment by akimd** [comment]
Please try more recent releases (https://docs.docker.com/docker-for-mac/install/), and report if you still have problems.
