### ISSUE TITLE
Performance degradation after disabling k8s

### ISSUE THREAD

**Issue by carlfischer1** [docker/for-mac#2344]
### Expected behavior
D4M + k8s should result in some perf impact. Disabling k8s should return performance to standard D4M levels.

### Actual behavior
After enabling k8s in 17.12.0-ce-rc3 my Mac is crushed to the point where keypresses and window updates are noticeably delayed. After disabling k8s performance remains degraded.

### Information
I don't recall seeing the same performance impact with 17.12.0-ce-rc1, but am not sure I was doing all the same things. It was definitely not occurring pre-k8s on 17.11.

### Steps to reproduce the behavior

1. Upgrade to 17.12.0-ce-rc3
2. Enable k8s
3. Experiment with k8s
4. Use Mac for other stuff

Observe perf degrade to the point of being unusable

5. Disable k8s
6. Verify k8s is no longer running via docker ps
7. Hope perf improves
8. Sadly perf does not improve

Diagnostic, taken after step 8: 07F17941-04C5-4401-A84C-EEB1BC8B4BC0

9. Quit Docker via tray menu

Perf returns to normal

10. Start Docker via Launchpad

Perf remains normal

**Comment by pgayvallet** [comment]
Hello,

is this still occurring in latest edge ?

**Comment by carlfischer1** [comment]
Tested with 18.02.0-ce-rc2, no longer repro's
