### ISSUE TITLE
Can't ping specific subnet from within a Docker container On macOS

### ISSUE THREAD

**Issue by MatanRubin** [docker/for-mac#2345]
### Expected behavior
I should be able to ping from within a container whatever server the host can ping.

### Actual behavior
Almost all servers I tried to ping work as expected, but servers starting with 172.20.\*.\* are unreachable (while the host can reach them without an issue).

### Information

Diagnostic ID: 72CEAFC7-61B3-4FE5-9E92-D3568802EDFF
After creating a container (doesn't really matter which one) I enter the container using:

`docker exec -it <container_name> /bin/bash`

From with the container I can ping google.com, as well as almost every server on my workplace network. However, for some reason I cannot ping servers with IP starting with 172.20.\*.\*.

For example, I tried multiple servers with IPs such as 10.0.\*.\*, 10.50.\*.\* and everything worked fine. Servers starting with 172.20 are unreachable. From the Mac host I can ping all these servers without an issue. I tried the same thing on a Linux machine and a Windows machine and could not reproduce the issue.

I'm assuming it's something to do with the way Docker routes the connection through the host. It might have something to do with the fact that the docker network is usually on 172.18.\*.\*. However, I could not figure it out.

Here's the routing table from within the container:

```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.18.0.1      0.0.0.0         UG    0      0        0 eth0
172.18.0.0      *               255.255.0.0     U     0      0        0 eth0
```

Running macOS High Sierra with Docker CE 17.09.1-ce-mac42 (21090).

Any idea what's going on?

**Comment by GitPaddo** [comment]
I noticed the same behaviour for docker version 17.12.0-ce-mac47 (21805) and also a version before the latest update.
I can reach all pages that are accessible from my host machine except those in the subnet starting with 172.18.*.* in my case. Traceroute also only performs one hop:
```
traceroute to 172.18."*"."*" (172.18."*"."*"), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.084 ms  0.013 ms  0.009 ms
 2  * * *
 ...
```

Same behaviour for High Sierra 10.13.1 and 10.13.2.

**Comment by GitPaddo** [comment]
After comparing several settings with a colleague we found out that a new bridge network is installed in the current docker version (17.12.0-ce-mac47 (21805)) called docker_gwbridge:

```
~ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
468ffbe23344        bridge              bridge              local
1f2aff966cea        docker_gwbridge     bridge              local
f42795d9b32d        host                host                local
2eb9b39ceb06        none                null                local
```

As my colleagues do not have this bridge in their settings I removed it via `docker network rm <NETWORK-ID>` and could ping the 172.18.x subnet as well as connect via ssh. I do not know the purpose of this bridge and neither if any other problems will arise by removing it. Hope it still helps.

**Comment by MatanRubin** [comment]
Still seeing the same behaviour with docker 18.03.1-ce, build 9ee9f40

**Comment by YRM64** [comment]
Just in case you experience any difficulty as a result of removing docker_gwbridge with the source code you provided, success.docker.com indicates the docker_gwbridge should be removed with:
docker network rm docker_gwbridge.

You wanted to know the reason for the gateway.  The docker_gwbridge interface serves the purpose of providing the default gateway functionality for all containers attached to the docker_gwbridge network, and that's the reason for the source code above.  I'm sure you're aware, when you remove gwbridge, your removing a network.

To alter the subnet of the interface, you have to create the subnet, and then stop the containers that were attached to docker_gwbridge; remove the network, and then re-add it with the appropriate address.  Last, re-start containers.  There are additional instructions for stopping all containers, listing all containers with docker_gwbridge, defining your variables, re-creating the docker_gwbridge, and lots more at success.docker.com.

**Comment by hixus** [comment]
I had the same issue as @GitPaddo. Pinging 172.18.*.* did not work within any container. Docker for mac factory reset worked. 

I did not check network settings before reset so I don't know if I had docker_gwbridge network installed. After reset it doesn't seem to be. My Docker Desktop OSX version is 2.0.0.3
