### ISSUE TITLE
Docker.qcow2 missing: the VM has never been started.

### ISSUE THREAD

**Issue by hasanovk** [docker/for-mac#2347]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  
### Steps to reproduce the behavior

  1. Preferences -> Advanced -> Change the Disk Image Location
  2. Restrat and run the Diagnose:
----------- Results --------
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.11.6 (build: 15G18013)
logs: /tmp/CD9763E5-CF62-4E77-A1BA-C130932083D0/20171222-014425.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
--------------------------
3. It says the "Docker is running"
How to get rid off this ERROR?

**Comment by akimd** [comment]
Please try more recent releases (https://docs.docker.com/docker-for-mac/install/), and report if you still have problems.

**Comment by ryanfb** [comment]
Just experienced this with latest stable (`17.12.0-ce-mac55`), but switching to edge (`18.03.0-ce-rc1-mac54`) and doing the same thing resolved it.

**Comment by akimd** [comment]
Thanks!
