### ISSUE TITLE
Docker qcow2 grows to an enormous size over time

### ISSUE THREAD

**Issue by jackmahoney** [docker/for-mac#2348]
### Expected behavior
Docker qcow2 image should not change size

### Actual behavior
After installing Docker for mac, the bundled qcow2 image/container grows indefinitely in size until it fills up my harddrive. It is 20GB as I write this issue. This happens continuously and I need to delete the image routinely. This is a serious bug.

### Information
![A screenshot of diskutility showing the image size](https://user-images.githubusercontent.com/1240270/34320285-095032e2-e7f7-11e7-9494-da449f583cd9.png)

### Version
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c
Mac OSX El Capitain

### Steps to reproduce the behavior

  1. Install docker for mac
  2. Wait a month
  3. Inspect your disk and see an enormous qcow2 image

**Comment by thaJeztah** [comment]
The `.qcow` image is where all your containers, volumes, container logs, and images are stored, so it's expected to grow if you use Docker, and pull, build, run containers.

**Comment by jackmahoney** [comment]
This seems like a poor naming choice. What does `qcow` have to do with where I keep my docker images?

**Comment by thaJeztah** [comment]
Qcow is the disk image format; https://en.m.wikipedia.org/wiki/Qcow

**Comment by jackmahoney** [comment]
Ok fair enough. I have learned something today! Sorry about the false issue.

**Comment by thaJeztah** [comment]
No problem! The Qcow disk format was selected because Apple's hfs filesystem doesn't support "sparse files"

Note that if you're on OS X "high Sierra", and use the new APFS filesystem, a `.raw` disk image will now be used; some information about that can be found in the FAQ (see this pull request https://github.com/docker/docker.github.io/pull/5504)
