### ISSUE TITLE
Update to Docker on Mac removed all images and containers

### ISSUE THREAD

**Issue by wpnzach** [docker/for-mac#2355]
### Expected behavior
Docker containers and images should remain after upgrade
### Actual behavior
Update to Version 17.09.1-ce-mac42 (21090) on Mac has removed all images and containers. Ran the update update a few days ago, containers and images are gone today.
### Information

AA699A1A-7F2A-4F14-B57B-12C4C18CB268

Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/AA699A1A-7F2A-4F14-B57B-12C4C18CB268/20180102-162238.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Update Docker with existing images and containers.  I am not sure what other things might be unique to my environment.

**Comment by pgayvallet** [comment]
We apologize for the inconvenience. There was an issue in vm disk migration during switch from old VM to linuxkit which failed to handle some cases, and an issue that caused disk corruption in the way to were shutting down the VM when performing upgrade, causing disk reformat. Both these issues has been fixed on latest stable and edge version, and this should not happens again. 

Closing
