### ISSUE TITLE
Unable to Start Docker on MacOS High Sierra 10.13.1

### ISSUE THREAD

**Issue by JonMLangel** [docker/for-mac#2357]
### Expected behavior

Docker would build/run. 

### Actual behavior

Docker fails to run.

### Information

**Diagnostic ID**: 1BDE2BDC-62DC-47CC-9001-932B5E801F17

**Diagnostics Log**: 
`Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/1BDE2BDC-62DC-47CC-9001-932B5E801F17/20180103-112751.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jonathonlangel/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/jonathonlangel/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jonathonlangel/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jonathonlangel/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jonathonlangel/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
 `

This was also reproduced with the Docker Edge version as well with the same diagnostic log.

### Steps to reproduce the behavior

  1. Install Docker
  2. Run Docker

**Comment by blipson** [comment]
I'm also seeing this issue with 10.13.2

**Comment by djs55** [comment]
Thanks for your report. In the log I see:
```
2018-01-03 11:27:33.573858-0600  localhost com.docker.driver.amd64-linux[6198]: vmx_init: processor not supported by Hypervisor.framework
```
What kind of hardware are you running on?

**Comment by JonMLangel** [comment]
Your question solved the issue. I was booting the Mac in safe mode due to an erroneous issue outside of this, which limited the Mac's resources. After booting normally, Docker seems to work just fine. Thank you for the quick response.

**Comment by djs55** [comment]
Ah interesting -- I'd never considered trying Docker in safe mode. Perhaps that should be added to the troubleshooting guide somewhere.

Thanks for letting me know!
