### ISSUE TITLE
docker not booting

### ISSUE THREAD

**Issue by samifruit514** [docker/for-mac#236]
### Expected behavior
docker starts properly
### Actual behavior
docker seems to keep booting, the docker icon on top is always animating
### Information

Diagnostic ID: 0CC76138-3864-4C83-BDE2-DB548159E345
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. boot the computer

**Comment by mchiang0610** [comment]
#119  Merging.
