### ISSUE TITLE
Docker will not start

### ISSUE THREAD

**Issue by bewing** [docker/for-mac#2363]
### Expected behavior
Docker starts
docker-cli works

### Actual behavior
Docker always says "Docker starting"
docker-cli hangs

### Information
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/D25F64DB-5953-466C-B133-52F0041E6E0F/20180105-094123.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Restart Mac
  2. Uninstall Docker
  3. Restart Mac
  4. Install Docker
  5.  Wait 10 minutes then run diagnostics

**Comment by shbi** [comment]
I am having the same error.

➜  ~ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
macOS: version 10.13.2 (build: 17C88)
Docker.app: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
Local time: Fri Jan  5 13:33:51 EST 2018
UTC:        Fri Jan  5 18:33:51 UTC 2018
Timestamp:  20180105-133351
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
Error docker ps: got timeout (docker ps: exit 1)

**Comment by Rydgel** [comment]
In my case, an old Docker process was still running in background.

**Comment by shbi** [comment]
An update:
I am no longer having this issue. I tried a few things. restarting docker, restarting my machine.
Eventually I just reset my data (sad but nothing crucial was lost) and after it started working again.
