### ISSUE TITLE
Fatal Error: com.docker.osx.hyperkit.linux failed to start 

### ISSUE THREAD

**Issue by skazancev** [docker/for-mac#2364]
### Information
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/9FA50894-2517-4A30-8288-4B10A90AA33C/20180106-000940.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/skazancev/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/skazancev/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/skazancev/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/skazancev/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/skazancev/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Run docker
  2. rm ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
  3. restart
  4. rm -fr ~/Library/Containers/com.docker.docker/Data/*
  5. restart

**Comment by skazancev** [comment]
@alepee Solved!
VT-d and VT-x (Intel Virtualization Technology) must be enabled in BIOS for docker to start a virtual env. Docker Mac is said to be native, but it relies on mac os virtualization capabilities.

**Comment by pgayvallet** [comment]
@skazancev was this fixed ? should I close ?

**Comment by skazancev** [comment]
@pgayvallet yes, sure. It was in my BIOS settings.
