### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start

### ISSUE THREAD

**Issue by xmoney** [docker/for-mac#2367]
my computer:
macbook pro 2013 late  macos 10.13.2
kern.hv_support: 1

### Information

Diagnostic ID: D18D6548-BCEC-4B68-BD1B-378F61F75EBB
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.13.2 (Build 17C88)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/aisyer/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/D18D6548-BCEC-4B68-BD1B-378F61F75EBB/20180106-163755/qemu-img-check.stdout 2> /tmp/D18D6548-BCEC-4B68-BD1B-378F61F75EBB/20180106-163755/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/aisyer/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/aisyer/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/aisyer/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/aisyer/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/aisyer/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by akimd** [comment]
Hi!

This version is ancient.  Please try a more recent release.
