### ISSUE TITLE
4523FCED-32ED-47DE-B429-12D471DC65AA

### ISSUE THREAD

**Issue by safafield** [docker/for-mac#2369]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Hi!

Could you please provide us with more details?

**Comment by pgayvallet** [comment]
Closing.

Please reopen with proper issue description if necessary.
