### ISSUE TITLE
Crash after upgrade

### ISSUE THREAD

**Issue by elsonwu** [docker/for-mac#237]
### Steps to reproduce

My Macbook Pro is running macOS 10.12 beta 16A286a
1. Before this crash, I am working with Docker 1.12.0-beta21.
2. The update popup appear automatically after I open Docker, it shows a update release 1.12.0-beta22.
3. Click update, update and restart.
4. Then crash.

### Expected behavior

Should start as usual

### Actual behavior

Crash

### Information

```
Diagnostic ID: 7DF7CDE9-3A11-49CC-88D5-DEA08F4D2A68
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     menubar
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/elsonwu/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/elsonwu/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by glynjackson** [comment]
related to https://github.com/docker/for-mac/issues/64

**Comment by mchiang0610** [comment]
Please update to beta 25. Sierra issues are being resolved.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
