### ISSUE TITLE
Docker edge unable to start when insecure registry is added

### ISSUE THREAD

**Issue by fritzb** [docker/for-mac#2370]
### Expected behavior

insecure registry gets added

### Actual behavior

docker never start, and requires factory reset and reboot followed by reinstall

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/8EC91E4D-933D-428F-9540-C846780A050E/20180106-091037.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

8EC91E4D-933D-428F-9540-C846780A050E

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Enable kubernetes
  2. Add an entry to insecure registry, and then click apply
  3. Docker will crash and prompt for factory reset

**Comment by bkomraz1** [comment]
+1

**Comment by bencao** [comment]
stable version  17.12.0-ce-mac46 (21698) have similar issue, once added `"disable-legacy-registry" : false` we are unable to start docker .

**Comment by bencao** [comment]
Found the following from documentation https://docs.docker.com/engine/deprecated/#interacting-with-v1-registries

> Starting with Docker 17.12, support for V1 registries has been removed, and the --disable-legacy-registry flag can no longer be used, and dockerd will fail to start when set.

**Comment by drewwells** [comment]
Docker released 17.12 won't start if you set insecure registries. It requires a factory reset which hangs.

**Comment by arunvelsriram** [comment]
Am able to workaround this by following these steps:
- Install docker-edge
- Preferences -> Daemon -> Uncheck Experimental features
- Apply & Restart
- Preferences -> Daemon -> Add the insecure registry
- Apply & Restart
- Preferences -> Daemon -> Check Experimental features
- Apply & Restart

**Comment by YRM64** [comment]
Troubleshooting tips for testing an insecure registry:

While it's recommended to secure your registry using TLS, other option(s) include using a self-signed certificate, or using your registry over an unencrypted HTTP connection.  Both require additional configuration, and as always, in a developers world of uncertainty,  there are "security trade-offs".

First, configure your Docker Engine daemon; pulling from a registry that isn't using TLS results in an error message.  Even when you use authentication Docker may still complain.  After the configuration, restart Docker for the changes to take place.  If you decide to use a self-signed certificate, you can always create your own certificate commencing with mkdir -p certs.  Be certain to provide an appropriate name, such as myregistrydomain.com as a CN.  Additional helpful information can be found at https://docs.docker.com/registry/insecure.
