### ISSUE TITLE
always hanging installing process when i enable kubernetes module

### ISSUE THREAD

**Issue by xiaods** [docker/for-mac#2372]
### Expected behavior
kubernetes have installed done.
### Actual behavior
the installation process is hang.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. screenshot here:
<img width="502" alt="2018-01-07 7 43 49" src="https://user-images.githubusercontent.com/37678/34645031-a1091274-f37e-11e7-8515-89e7fe8a6f4d.png">

  2. ...

**Comment by pgayvallet** [comment]
Hello,

Is this still happening in lastest edge ?

**Comment by djs55** [comment]
Could be a duplicate of #2990
