### ISSUE TITLE
PostgreSQL seg fault on edge 17.12.0-ce-mac45

### ISSUE THREAD

**Issue by davidwheeler123** [docker/for-mac#2377]
### Expected behavior
postgres binary executes and prints
`postgres (PostgreSQL) 10.1`

### Actual behavior
Postgres seg faults and returns status code 139

### Information
Diagnostic ID: DBF38F8A-1F76-4068-940F-05F04E21B0AD

Dockerfile: [Dockerfile.zip](https://github.com/docker/for-mac/files/1614023/Dockerfile.zip)
docker-entrypoint.sh (not used - just make it an empty file if needed)

I can see the following line in docker vm's dmesg
`[17742.735401] postgres[31558]: segfault at 8 ip 00007efe0df28311 sp 00007fff80bc9050 error 4 in ld-2.23.so[7efe0df1c000+26000]`

### Steps to reproduce the behavior

`docker build -t pgsql-test; docker run -it pgsql-test /usr/lib/postgresql/10/bin/postgres -V || echo $?`

On linux & mac non-edge (17.09) it works, but on my edge installation (17.12.0-ce-mac45) it fails. 

Hope that's all you need

**Comment by gtardif** [comment]
Thanks for the report. I can't reproduce this, but will dig in the diagnostics

**Comment by davidwheeler123** [comment]
OK well that's good news I guess. Is it worth me doing a factory reset and see if the issue persists after that? Or would you prefer for me to keep the system as it is so I can do further testing?

**Comment by davidwheeler123** [comment]
I have just run this locally and it works also. However when I use an image built on our CI (Linux, AWS, Jenkins) server it breaks. Unfortunately the image built on CI has some proprietary stuff in it so I can't just provide it, but I'll try to build a clean one and if that has the issue I'll provide that.

**Comment by davidwheeler123** [comment]
OK I think something must have changed upstream. I rebuilt the troublesome image on our CI server (no changes at our end) and it's working now. Thanks for your help anyway.
