### ISSUE TITLE
Docker for mac fails to start after upgrading supplemental security update on High Sierra 10.13.2

### ISSUE THREAD

**Issue by aruld** [docker/for-mac#2380]
### Expected behavior
Start Docker after reboot

### Actual behavior
Diagnostic ID: B7CEC68A-E104-488A-85C6-7CCC53198F5D
Docker for Mac: version: 17.12.0-ce-mac46 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/B7CEC68A-E104-488A-85C6-7CCC53198F5D/20180109-074108.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/arul/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/arul/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/arul/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by aruld** [comment]
Restarting the mac fixed it.

**Comment by djs55** [comment]
@aruld thanks for the update. I'm going to install the supplemental update on my machine now and see if I can reproduce.

Let us know if you have any other problems!
