### ISSUE TITLE
Infinity loading

### ISSUE THREAD

**Issue by litruk** [docker/for-mac#2381]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing

Please reopen with proper description and diagnostic id if still occuring.
