### ISSUE TITLE
china -> add aliyun`s registry-mirrors  restart faild

### ISSUE THREAD

**Issue by uighurbabbage** [docker/for-mac#2385]
### Expected behavior
in the last update add china aliyun registory-mirrors restart fail
no the problem befor, i am update docker Yesterday and the problem come out

**Comment by elvizlai** [comment]
same issue

**Comment by uighurbabbage** [comment]
Today, the problem is solved。I am not what the big move， The registry-mirrors address I got before was like this `adsfasda234.mirror.aliyuncs.com` add this docker connot restart and let me reset with force。 Today, I've made up for the address prefix and try to restart and I found the problem disappearing。

**Comment by mrdulin** [comment]
the issue still there. 

Version 17.12.0-ce-mac46 (21698)

**Comment by uighurbabbage** [comment]
macOS High Sierra 10.13.2  use 

> http://56px195b.mirror.aliyuncs.com

 this address no the problem.
You go to get an address，it is maybe like this 

> 56px195b.mirror.aliyuncs.com

you add the http prefix and that likes

>  http://56px195b.mirror.aliyuncs.com

 and restart ,I don't have this problem now.
please Then add this address and try it again `http://56px195b.mirror.aliyuncs.com`

**Comment by elvizlai** [comment]
@uighurbabbage Using `http` can not turbo pull speed.Need using `https` instead.

**Comment by wangle201210** [comment]
my address is https://pive4fte.mirror.aliyuncs.com
but can not restart too?

**Comment by uighurbabbage** [comment]
Have you updated it? The last update of the day before may be restarted. I'm now the latest version. And I use HTTPS.
my docker info : Version 17.12.0-ce-mac47 (21805)

**Comment by elvizlai** [comment]
this solved using latest version.
