### ISSUE TITLE
Removing volume with Disk Image Location prevents VM from starting

### ISSUE THREAD

**Issue by Mikulas** [docker/for-mac#2390]
I store the docker Disk Image on a SD card and sometimes, it gets yanked out. The docker engine obviously fails at that point, but it does come back up when restarting the engine after plugging the SD card back in.

### Expected behavior

Docker should start (restart) properly after the volume has been reattached.

### Actual behavior

Docker is unable to find the Docker.qcow2 file, even though it was mounted again.

### Information

Diagnostics:
```
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A365)
logs: /tmp/FC60898F-894E-48ED-86C4-F6E125EE436D/20180110-103514.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/mikulas/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mikulas/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mikulas/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mikulas/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --style syslog --last 1d | grep -i docker > \"/tmp/FC60898F-894E-48ED-86C4-F6E125EE436D/20180110-103514/docker-system-os.log\": exit 1")
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mikulas/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
```

### Steps to reproduce the behavior

  1. Move Docker Disk Image to a external volume (this is option in Docker for Mac settings)
  2. Yank the volume out
  3. at this point docker is not working, as expected
  4. Attach the volume back to the computer
  5. Restart Docker for Mac
  6. Docker Engine will not start, but it should

**Comment by YRM64** [comment]
I think a good response to this issue is to work with Docker's 1.9 Volume Management System.  There's also a script available that will clean everything without impacting VMs.  The script available at https://lebkowski.name/docker-volumes/ allegedly does a clean swipe of everything not needed; leaving in place "used containers, images, and volumes".  In fact, included is a notation at the end of the script "cleanup-docker.sh hosted with ❤️ By Github." There's an additional option to view the script in raw format.

**Comment by Mikulas** [comment]
> work with Docker's 1.9 Volume Management System

That is irrelevant. This is a bug report.
