### ISSUE TITLE
Download old release of Edge channel

### ISSUE THREAD

**Issue by franklinyu** [docker/for-mac#2394]
It would encourage people to use Edge channel. Currently only Stable channel provides old release (thank you for your work in #1120).

**Comment by franklinyu** [comment]
My bad. Didn't see them.

**Comment by franklinyu** [comment]
I’m not sure what I saw on January 10, but I can’t see it again. Maybe I drunk at that day.

**Comment by isaacuribe** [comment]
Downloading of previous edge releases is available from https://docs.docker.com/docker-for-mac/edge-release-notes
It's been there for a while now, is that what you are looking for?

**Comment by franklinyu** [comment]
@isaacuribe I believe it wasn’t there on February 12<sup>th</sup> but I cannot prove it.
