### ISSUE TITLE
Adding a worker node to Kubernetes

### ISSUE THREAD

**Issue by mrichman** [docker/for-mac#2397]
How can I add a worker node to a Kubernetes cluster running in Docker for Mac?

I'm using the following version:

```text
Docker for Mac: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.12.6 (build: 16G1204)
logs: /tmp/47B1B818-3DC4-4915-830B-C8D77852154E/20180110-110431.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Someone in the Slack channel suggested <https://github.com/linuxkit/kubernetes> which is apparently the upstream of this project. 

Is this the recommended solution? If not, would an alternative like <https://github.com/kubernetes/minikube> be a viable option?

**Comment by christopherL91** [comment]
I think the only viable options is to run something like kubeadm [Using kubeadm to Create a Cluster](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)

Minikube and docker for mac with kubernetes integration is really just for single node setups (ideally for development purposes)

**Comment by sarjeet2013** [comment]
+1, This will be a nice feature request to add more worker node (if require) for Docker for Mac with Kubernetes. 

Also, Is there a way to manage the worker node i.e. login, install packages, ssh etc on mac?

**Comment by pgayvallet** [comment]
Adding nodes to the cluster is not supported, and there is atm no intention to provide such feature.

**Comment by qiyongxiao** [comment]
现在可以添加node节点了吗？
