### ISSUE TITLE
On latest macOS 10.12 beta, docker of Mac continue crashed after started

### ISSUE THREAD

**Issue by smoothdvd** [docker/for-mac#240]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 4B34F262-386F-4D76-9387-F403AB8920E5
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by semiwhale** [comment]
same.

macOS 10.12 Beta (16A286a)

**Comment by smoothdvd** [comment]
Stop ntpd service.

**Comment by glynjackson** [comment]
could be related to https://github.com/docker/for-mac/issues/64

**Comment by mchiang0610** [comment]
Beta 25 solves most of the sierra issues: https://download.docker.com/mac/beta/Docker.dmg

Stable release should follow soon!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
