### ISSUE TITLE
Bug after upgrading to 2018-01-08 17.12.0-ce-mac46 "17.12.0-ce-mac46"

### ISSUE THREAD

**Issue by micalexander** [docker/for-mac#2401]
### Expected behavior
No errors

### Actual behavior
I updated yesterday (### 2018-01-08 17.12.0-ce-mac46 "17.12.0-ce-mac46") and noticed a bug. After running docker exec into a running container and exiting I get this error `Error response from daemon: Bad response from Docker engine` and all running containers are nuked. The only way to fix this issue is to quit Docker and start it again being the restart button is removed from the little applet in the menu bar.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Currently downgraded. I will add to this once I have time to upgrade and  "Diagnose & Feedback"

UPDATE: So I have skipped a release or 2 and just updated to 17.12.0-ce-mac49 and the same problem occurs. Below is the "Diagnose & Feedback" obtained.

Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/6250B23E-4287-469A-B558-98A65997B17B/20180122-214512.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

Diagnostic ID: 6250B23E-4287-469A-B558-98A65997B17B

### Steps to reproduce the behavior
After running docker exec into a running container and exiting I get this error `Error response from daemon: Bad response from Docker engine`

**Comment by YRM64** [comment]
Have you tried re-setting Docker to factory default settings?  Caution:  when you reset to factory default settings, local images will be lost.  Remember to always push and commit images you want to save prior to the reset.

**Comment by micalexander** [comment]
I have done a fresh install on multiple boxes and the issue still persists.

**Comment by YRM64** [comment]
Mic Alexander, ok, try restarting Docker.  Others have found success (Mac 47) with just restarting Docker - noting that the second attempt was successful.  

And, most important, have you performed any upgrade tests?  Upgrade tests normally check to see if you're running the correct addons, and the correct versions for those addons.  Upgrade tests ensure that there aren't any old addons hanging around interfering with your start-up.  Let me know if this helps.
