### ISSUE TITLE
Please bring back restart button

### ISSUE THREAD

**Issue by amancevice** [docker/for-mac#2407]
### Expected behavior

The old menu bar menu included a "Restart" button next to the docker daemon status.

### Actual behavior

No way to restart Docker from the menu bar/preferences pane

### Information

Version 17.12.0-ce-mac46 (21698)

**Comment by ballantyno** [comment]
I know it's not really ideal, but there is a restart button under the reset 'tab' inside preferences.
<img width="495" alt="docker-restart" src="https://user-images.githubusercontent.com/8126518/34881345-53b7c1b2-f781-11e7-8c55-d1c4319c75d9.png">

**Comment by akimd** [comment]
That button was quite useful when Docker for Mac was unstable, but it should no longer be so frequent to have to restart.

Do you do that often?

**Comment by amancevice** [comment]
Sure, all the time. Sometimes as a shortcut to stop all running containers, sometimes when hyper kit seemed to be hogging lots of memory, sometimes as a first-response to an unknown error.

**Comment by akimd** [comment]
If the feature were to come back, it would certainly be as a regular menu item, say right above "Quit Docker".  That would be OK with you?

**Comment by amancevice** [comment]
Yeah, sure. As long as it's in the menu.

**Comment by matthewbarr** [comment]
We use it when we add new registries.

**Comment by akimd** [comment]
@matthewbarr What do you mean?  When you add new registries in the preferences the app forces the restart on you ("Apply and Restart").

**Comment by BrendonW** [comment]
If I leave my development swarm running for days on end, the webservers sometimes stop responding to traffic because docker seems to forget about delivering network traffic. Or the web server can't talk to the database. The quickest way to recover is to bounce Docker.

**Comment by matthewbarr** [comment]
We use Client certs auth for registries internally.  That means adding certs to the disk, so they can be picked up at app restart.

We also have seen a few high load hyperkits, and it’s easiet to restart as a first trouble shooting effort.  I was surprised he button went away,  but quit and start again isn't that much harder.

**Comment by barat** [comment]
+1 for this. I use it quite often when my Symfony dev app start to render response in 20-25s (and after restart - 1-1.5s). I don't even know what was the reason for this.
Until bind-mounting performance will be solved this option should be easily available.

**Comment by amancevice** [comment]
A co-worker of mine brought up a good point and that is a) docker for mac may not be as stable for all users as it is for the QA team at Docker, and b) it's a little bold to assume that *all* future releases will be just as bug-free.

**Comment by akimd** [comment]
Of course I wouldn't claim that.  And I guess no serious software engineer would claim that.  Yet there are not many programs that have a Reset button.  We do.  

We will add a menu item, but not a button as it was originally.

**Comment by bfred-it** [comment]
> there are not many programs that have a Reset button

All VM programs have reset buttons, Docker has to be compared to those, not Word.

**Comment by pjar** [comment]
I have to restart my rails & docker environment when I leave it running overnight. The cause is that Rails starts to complain about some desynchronization of time between Rails server and its container.

**Comment by ahl** [comment]
I restart Docker on Mac at least once/day due to random unresponsiveness and nebulous network issues. I'm sure you can gather data about how frequently people push this button; perhaps you could bring it back until it's no longer needed.

**Comment by akimd** [comment]
You seem to have missed the fact that we already acknowledged to restore it as a menu item.

**Comment by bfred-it** [comment]
*We* who? Your messages have no “Collaborator/Owner” tag so they don’t look “official”

**Comment by akimd** [comment]
@bfred-it Sorry about that.  I do see a "Member" tag to my answers, but maybe you don't?  To be clear, the menu item is merged, and will show in the next Edge.

**Comment by bfred-it** [comment]
It means you're set to "private" in the docker org. You can change it in the sidebar here https://github.com/docker

**Comment by orbfish** [comment]
I also use it for when hyperkit starts grabbing 6GB - is there a way to get the older build? I got a new computer and my workflow is impacted.

**Comment by akimd** [comment]
Sorry, I was on vacations.  But what is the question?  I can see the Restart in 18.02 for instance.

**Comment by ktiedt** [comment]
That was the question, what version it would be in because its been on Edge for quite awhile now and there have since been at least 2 updates to CE Stable since then but it still hadn't showed up there.

Is there a release date for 18.02 for stable CE?

**Comment by akimd** [comment]
There will be a Stable 18.03.

**Comment by ktiedt** [comment]
But *when* is the question... 
months of jumping through hoops that should have never existed is time consuming...
