### ISSUE TITLE
OS X El Capitan 10.11.6 Install Fatal Error, Failed to install symlinks in /usr/local/bin (stage 4)

### ISSUE THREAD

**Issue by jheasly** [docker/for-mac#2410]
### Expected behavior

Docker launches

### Actual behavior

Fatal Error Failed to install symlinks in /usr/local/bin (stage 4)

### Information

Docker for Mac: version: 17.12.0-ce-mac46 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.11.6 (build: 15G18013)
logs: /tmp/146D36B0-5EE6-4B2C-BC79-5A3BF6E384BF/20180111-130921.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jheasly/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jheasly/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/jheasly/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/jheasly/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jheasly/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

### Steps to reproduce the behavior

  1. Download Docker for Mac CE .dmg
  2. Drag app to Applications, launch

**Comment by jheasly** [comment]
With latest release `17.12.0-ce-mac47` Docker.app just hangs:  
```
UnixDomainSocket: Failed to connect to /Users/foo/Library/Containers/com.docker.docker/Data/s20: No such file or directory
```

**Comment by jheasly** [comment]
For the record, did a clean install of El Capitan, 10.11.6, and `17.12.0-ce-mac47` installed just fine.

**Comment by LexBel-co** [comment]
The same here: Fatal Error: cannot install symlinks in /usr/local/bin (stage 4)
