### ISSUE TITLE
Fatal error on startup, first install

### ISSUE THREAD

**Issue by toribr** [docker/for-mac#2411]
### Expected behavior
Installed for the first time, tried to open app
### Actual behavior
Fatal error com.docker.supervisor failed to start
Exit code 1
### Information

Docker for Mac: version: 17.12.0-ce-mac46 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/7002ED9C-8880-4470-8BC5-FEE30377787E/20180111-174132.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/breitlingt/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/breitlingt/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/breitlingt/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/breitlingt/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wuqiang3424** [comment]
reboot mac

**Comment by wuqiang3424** [comment]
Similar fault, I restart the mac accidentally resolved

**Comment by toribr** [comment]
I tried that. Sadly that did not work. Same fatal error.

**Comment by loganwilliams** [comment]
This seems like the same as issue #2383.

**Comment by toribr** [comment]
This was resolved by making spotlight re-index, thus reporting the correct amount of disk space, and allowing Docker to install without issue.
