### ISSUE TITLE
No performance improvement in 17.12.0-ce-mac46

### ISSUE THREAD

**Issue by mnabialek** [docker/for-mac#2418]
I was using 17.09.-ce-mac42 and upgraded to 17.12.0-ce-mac46

In changelog there is:

> For systems running APFS on SSD on High Sierra, use raw format VM disks by default. This improves disk throughput (from 320MiB/sec to 600MiB/sec in dd on a 2015 MacBook Pro) and disk space handling.
> Existing disks are kept in qcow format, if you want to switch to raw format you need to “Remove all data” or “Reset to factory defaults”. See https://docs.docker.com/docker-for-mac/faqs/#disk-usage

So maybe I'm wrong but I was expecting better performance.

To test performance I've used test suite (almost 1700 tests) in PHP.

| Type | Previous version | Current version |
|---|---|---|
| Pure docker | 10.7 minutes | 10.53 minutes - 11 minutes |
| Docker + docker sync | 2.3 minutes | 2.5 minutes - 3 minutes |

Looking at results I don't see any performance improvement as I expected looking at the changelog (in some cases performance is worse than it was before).

To make sure new format is used I've chosen Reset -> Remove all data.

I was testing with 4 cores and 2 GB ram (that was the best setting when testing in previous version) and also with 2 cores and 2 GB ram - for both I don't see performance improvement.

I'm using MacBook Pro 2015 with High Sierra installed (with APFS).

**Comment by gil0mendes** [comment]
This is a recurrent problem with Docker on macOS. There is issues on this matter created around  2016 or maybe before, but no solutions are pointed out. Now, with the last Docker version not even the Docker Sync works properly! :( 

Looking for this almost 700 open issues counter the near 100 on Linux, looks like no one cares about macOS.

**Comment by albertski** [comment]
FYI I recently switched from using docker sync to pure docker in version Version 17.12.0-ce-mac49.  I am using High Sierra.

I had to update my docker-compose php volume to:
```
- ./:/var/www/html:cached
```

I don't have any performance numbers but it seems to be faster than docker sync.

**Comment by gil0mendes** [comment]
@albertski That has speeded up the reloads a bit, very thanks for the tip 😉
