### ISSUE TITLE
Docker for Mac stuck on "is starting"

### ISSUE THREAD

**Issue by hpartidas** [docker/for-mac#2420]
### Expected behavior
Docker starts

### Actual behavior
Stuck at "Docker is starting"

### Information
```
 Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/FC062A3A-FD90-4B2A-9045-0DC20D9B956C/20180112-151659.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```
Diagnostic ID: FC062A3A-FD90-4B2A-9045-0DC20D9B956C

### Steps to reproduce the behavior

- Start Docker

**Comment by karlgroves** [comment]
+1 to this issue.

**Comment by sstepanovvl** [comment]
+1
mac os high sierra 10.13.2

**Comment by souljacker** [comment]
+1 here

**Comment by skander1406** [comment]
+1

**Comment by skander1406** [comment]
+1

**Comment by udisun** [comment]
+1

**Comment by hanafiah** [comment]
+1

**Comment by shadedesignz** [comment]
+1

**Comment by FrankKair** [comment]
+1

**Comment by salmaanrizvi** [comment]
+1

**Comment by gtardif** [comment]
I can't reproduce the issue ATM. But the logs in the diagnostics indicate that the Docker4mac app has been quarantined for some reason. 
Can you try `xattr -d -r -s com.apple.quarantine /Applications/Docker.app` and restart Docker For Mac to see if this solves the issue on your side ?

**Comment by souljacker** [comment]
@gtardif for me it didn't do nothing :(

**Comment by Fochest** [comment]
Same here since updating to 10.13.2

**Comment by hanafiah** [comment]
I just revert back to previous version for the interim solution. 
1. uninstall current version
2. download and install previous version https://download.docker.com/mac/stable/21090/Docker.dmg

this not solve current issue but at least I can continue my work. will help debugging current issue once I got some time.

**Comment by shadedesignz** [comment]
Uninstall Docker then reinstall seemed to work as a temporary workaround for me

**Comment by iKettles** [comment]
I can confirm I was able to get the latest stable version working by installing the previous version @hanafiah linked to and then updating from within Docker.

**Comment by akimd** [comment]
Could you please check if the following image fixes your problems? You might need to reset to factory defaults...

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again. Thanks!

**Comment by hanafiah** [comment]
@akimd . I just tested and its working on my end.

**Comment by akimd** [comment]
Excellent, thanks!

**Comment by akimd** [comment]
Thanks!

**Comment by fomars** [comment]
Same issue occurring in version 18.06.1-ce

**Comment by andre487** [comment]
The same issue. 

macOS 10.12.6 (16G1510)
Docker 18.06.1-ce

**Comment by zgc** [comment]
+1
macOS:10.14
Docker:18.09.0-ce-beta1

**Comment by christoph-metzger** [comment]
Found a workaround on macOS here: https://pitman.io/posts/fix-docker-wont-start-error-on-mac-os/

Remove or rename following file:
`mv ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2.bkp`
The disadvantage is that

**Comment by bicepjai** [comment]
I still the same issue with 

Docker 2.0.0.3
Mac 10.14.4

**Comment by AlShelley** [comment]
+1

**Comment by gsampaio-rh** [comment]
+1

**Comment by teehamaral** [comment]
+1

**Comment by Maksclub** [comment]
+1

**Comment by gsampaio-rh** [comment]
I rolled back to 17.09.0-ce-mac33 (19597) and it's working.

**Comment by ricardo-aguiar** [comment]
+1
this worked as a workaround for me https://github.com/docker/for-mac/issues/2420#issuecomment-439819670

**Comment by iamcgn** [comment]
+1 

I had BlueStacks installed and clicked the "Start Anyway" button. After Docker wouldn't work I decided to uninstall BlueStacks. After that, when starting Docker, it brought up a permissions prompt to install something network related. Might be a red herring but it seems the BlueStacks dialog somehow prevented the permissions prompt and stalled the setup. I'm back up and running now.

Version 2.1.0.1 (37199)
Engine: 19.03.1
macOS: 10.14.5

**Comment by rafunchik** [comment]
same as above, had BlueStacks installed and Docker used to run fine (with a warning message), updated Docker and now would get stuck whilst starting. 
Removing BlueStacks and restarting Docker seems to have fixed it, thanks!

**Comment by HenrikEckermann** [comment]
have the same issue on all newest version... Any solutions to this? Did already reinstall without help...

**Comment by Maksclub** [comment]
> same as above, had BlueStacks installed and Docker used to run fine (with a warning message), updated Docker and now would get stuck whilst starting.
> Removing BlueStacks and restarting Docker seems to have fixed it, thanks!

The solution helped me: https://github.com/docker/for-mac/issues/2420#issuecomment-439819670
(I made alias for this command and use it when necessary)

**Comment by Kachilero** [comment]
I don't know why this issue is closed, this is still very much happening on

**Docker Version:** 2.1.0.5 (40693)
**Engine:** 19.03.5
**macOS:** 10.14.6

The thing that works for me is [SagidM's](https://github.com/docker/for-mac/issues/2420#issuecomment-439819670) solution from above **BUT** only after forcibly killing docker and resetting to factory settings.

Otherwise the issue persists.

**Comment by unlikelyzero** [comment]
Happened to me when I updated to Catalina. [This solution worked once](https://github.com/docker/for-mac/issues/2420#issuecomment-439819670). Now I had to revert back to an install from Jan 2018

**Comment by jnoorbak** [comment]
I'm having the same problem as well

**Comment by Savinda** [comment]
Same issue here, trying to install prev version :(
