### ISSUE TITLE
#1175 should not be closed

### ISSUE THREAD

**Issue by quaeler** [docker/for-mac#2422]
#1175 is not fixed - the upgrade to 17.12.0-ce-mac47 (21805) has lost all of my containers (and, as evidenced by people still adding comments to that issue, I am not a unique case.)

Please re-open #1175.

**Comment by akimd** [comment]
Actually, that issue was closed by asking people to create new bug reports.  Could you provide more information about your own case?  Diagnostics would be most useful.

**Comment by quaeler** [comment]
Yes, i appreciate that diagnostics would be useful - and had i been expecting such an event, i would have been pedantic in capturing a before state; the after state is that of no longer existent volumes and images.

If there is a suggested command i can now run to be helpful, i'll gladly run it.

**Comment by akimd** [comment]
You could try to generate the diagnostics via "Diagnose and Feedback" in the menu, but I'm not sure we'll find enough details in there.

**Comment by quaeler** [comment]
Done - id is E951C920-40D3-453C-859D-559DF3D191EB

**Comment by robmcdan** [comment]
+1, this is not a unique issue

B129992F-7110-4216-959B-B00BDBCE0B5A

**Comment by pgayvallet** [comment]
We apologize for the inconvenience. There was an issue in vm disk migration during switch from old VM to linuxkit which failed to handle some cases, and an issue that caused disk corruption in the way to were shutting down the VM when performing upgrade, causing disk reformat. Both these issues has been fixed on latest stable and edge version, and this should not happens again. 

Closing
