### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by tamanishi** [docker/for-mac#243]
### Steps to reproduce

1. installed update.

### Expected behavior

normal end.

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 1EFB6B72-786E-414C-9A52-F1971CA7276E
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
