### ISSUE TITLE
After upgrading to 17.12.0-ce-mac47 my app can not send out http request

### ISSUE THREAD

**Issue by qiulang** [docker/for-mac#2431]
I upgraded to 17.12.0-ce-mac47 and I found my app cannot send out http request now. I have tried several machines to confirm it is the upgraded version caused the problem. 
I downgraded one of the machines to 17.06.2-ce-mac27 and everything works fine.

Is there any configuration I need to set for the laster version?

**Comment by zikphil** [comment]
Yes latest upgrade also broke docker.for.mac.localhost for me. It seems like none of my containers can reach out to my host anymore, everything hangs... Not sure what happened there. Downgrading fixed it for me.

**Comment by gorillagroup** [comment]
@zikphil From the release notes: 

>   - DNS name `docker.for.mac.host.internal` shoud be used instead of `docker.for.mac.localhost` (still valid) for host resolution from containers, since since there is an RFC banning the use of subdomains of localhost (See https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06).

I suppose somehow "docker.for.mac.localhost" ended up being broken. I pinged the **docker.for.mac.host.internal** domain and it's now resolved to 192.168.65.2 whereas previously I had 192.168.65.1...

**Comment by qiulang** [comment]
@zikphil a related question is how can we install the previous version? It seems that it is no "official" way to do that. I search my trash can (on several machines) to finally find a previous installer. :(

**Comment by seven1m** [comment]
@qiulang you can download previous releases from the release notes here: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by qiulang** [comment]
@seven1m Thanks! I did not know that! I

**Comment by qiulang** [comment]
@akimd Why did you close the issue. Is this problem confirmed? And how do I fix my problem if I want to use the latest version?

**Comment by akimd** [comment]
@qiulang I might have been too fast: I had the impression your problem was that you were still using `docker.for.mac.localhost`.  If I'm wrong, please, tell me.  However, please wait for the forthcoming update of Docker for Mac 17.12: it will include fixes that are likely to solve your issue.  Expect it RSN.

**Comment by qiulang** [comment]
@akimd my app will connect from a container to a service on a **remote server**, so I don't think I use docker.for.mac.localhost.But I know little about docker.for.mac.localhost, I could be wrong.

**Comment by neoblackcap** [comment]
I use 17.12-ce, but i find docker.for.mac.host.internal is not working but docker.for.mac.localhost do
