### ISSUE TITLE
Version 17.12.0-ce-mac47 (21805) seems to remove /rootfs/usr/bin/findmnt 

### ISSUE THREAD

**Issue by mfojtik** [docker/for-mac#2433]
### Expected behavior

Previous version of Docker for Mac VM included the `/usr/bin/findmnt`, the latest version based on LinuxKit seems to drop them. 

These binaries are required for kubelet to run in a container: https://github.com/mfojtik/kubernetes/blob/fd520aef61996c213a960e1ea933def56dec17f6/pkg/util/nsenter/nsenter.go#L71

### Actual behavior

Kubernetes can't start containers and they are stuck in ContainerCreating as the `findmnt` binary is not found.

**Comment by justincormack** [comment]
Why can't you put the binaries in the container you are actually trying to run, rather than assuming you can bind mount from the host?

**Comment by justincormack** [comment]
As we already run a containerised kubelet on Docker for Mac if you enable Kubernetes, it also cannot be the case that these are required. The host environment is out of scope for containers, and you rely on it at your own risk. So I am going to close this.

**Comment by mfojtik** [comment]
@justincormack well if you want to run custom containerized kubelet and not the one shipped with Docker for Mac (for example in OpenShift the `oc cluster up` will run the kubelet), then you need `findmnt` binary otherwise the containers will fail to start.

I found that the `findmnt` binary is present in `/bin/findmt` in the Docker VM, and if I copy it into `/containers/services/docker-ce/rootfs/bin` then the problem seems to be fixed.

**Comment by mfojtik** [comment]
It seems like the binary is present for Docker kubelet:

```
linuxkit-025000000001:~# find /containers/services/ | grep findmnt
/containers/services/kubelet/lower/bin/findmnt
/containers/services/kubelet/rootfs/bin/findmnt
/containers/services/trim-after-delete/lower/bin/findmnt
/containers/services/trim-after-delete/rootfs/bin/findmnt
```

@justincormack any reason why not just symlink it to standard docker-ce/rootfs?

**Comment by justincormack** [comment]
You can't use symlinks, these are independent containers. Docker does not require a `findmnt` binary, so it does not have one in the container. We put `findmnt` in the kubelet because it is required there, you should be able to do the same in your `kubelet` container. If you need something in a container, just put it there, stop requesting host system changes because things are missing from your container.
