### ISSUE TITLE
Freeze and never run

### ISSUE THREAD

**Issue by yudao** [docker/for-mac#2435]
Hi,

I can't run docker for mac app it freeze and stay stuck.

### Expected behavior

Run app

### Actual behavior

- See icon tray but with inifinite loader when mouse is on
- See Docker (not responding) into Activity Monitor. Need to force kill to quit it.

### Information
```
 yudao$ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
macOS: version 10.13.2 (build: 17C205)
Docker.app: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
Local time: Lun 15 jan 2018 15:51:23 CET
UTC:        Lun 15 jan 2018 14:51:23 UTC
Timestamp:  20180115-155122
Running diagnostic tests:
[ERROR]   docker-cli       cannot find docker
[ERROR]   docker-cli       /var/run/docker.sock does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /var/run/docker.sock
[ERROR]   docker-cli       /Users/yudao/Library/Containers/com.docker.docker/Data/s60 does not exist
[ERROR]   docker-cli       Unexpected error (No such file or directory) connecting to /Users/yudao/Library/Containers/com.docker.docker/Data/s60
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[ERROR]   Moby booted      /Users/yudao/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[ERROR]   vmnetd           /private/tmp/vmnetd/com.docker.vmnetd is not running
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   vpnkit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/yudao/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/yudao/Library/Containers/com.docker.docker/Data/s51
[ERROR]   vpnkit           com.docker.vpnkit is not running
Error docker ps: got timeout (docker ps: exit 127)
[ERROR]   disk             No Docker.qcow2 or Docker.raw found: the VM has never been started
Error exec: /usr/local/bin/kubectl --context docker-for-desktop-context get nodes > /tmp/C95969CD-22A3-4F2B-998E-63C00F53602A/20180115-155122/kubectl-get-nodes: exit 127
Error exec: /usr/local/bin/kubectl --context docker-for-desktop-context describe nodes > /tmp/C95969CD-22A3-4F2B-998E-63C00F53602A/20180115-155122/kubectl-describe-nodes: exit 127
Error exec: /usr/local/bin/kubectl --context docker-for-desktop-context describe pods --all-namespaces > /tmp/C95969CD-22A3-4F2B-998E-63C00F53602A/20180115-155122/kubectl-describe-pods: exit 127
[OK]      kubectl
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Most specific failure is: No Docker.qcow2 or Docker.raw found: the VM has never been started
Docker logs are being collected into /tmp/C95969CD-22A3-4F2B-998E-63C00F53602A/20180115-155122.tar.gz
Your unique id is: C95969CD-22A3-4F2B-998E-63C00F53602A
Please quote this in all correspondence.
```

**Comment by akimd** [comment]
Could you please try this modified version of Docker 17.12? Hopefully it should fix your issue. If it does, we will soon release an official stable image which includes the fix. Once you tested it, be sure to reinstall a "real" stable release.

https://download-stage.docker.com/mac/pr/21923/Docker.dmg

**Comment by yudao** [comment]
Hi @akimd and thx for your quick reply!

Unfortunately, after deinstall my Docker app version, download your version and reinstall it, I see the same error with same behavior unless no icon tray exists (I expect it's totally normal with edge version).

**Comment by akimd** [comment]
Could you please check if the following image fixes your problems?  You might need to reset to factory defaults...

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again. Thanks!

**Comment by akimd** [comment]
Also, I see you are running the version *-mac45: you should at least have been running *-mac47.

**Comment by yudao** [comment]
Thx @akimd. No always same thing append. 

<img width="599" alt="capture d ecran 2018-01-18 a 13 52 55" src="https://user-images.githubusercontent.com/1303599/35099451-553b7f70-fc58-11e7-942a-7d35465f2f9c.png">

<img width="1165" alt="capture d ecran 2018-01-18 a 13 53 31" src="https://user-images.githubusercontent.com/1303599/35099452-554e508c-fc58-11e7-8eb7-1248a85b2c97.png">

I'm in version *-mac49
https://gist.github.com/yudao/961b88eccc98f71991c638667b929c05

**Comment by akimd** [comment]
Actually the logs I have received from your run is about version mac47.  Could you please to _install_ the version I sent, make sure no other is running, and give that version a try?  A full reset might be needed.  If it does not work, be sure to "Diagnose and Feedback", in the Docker menu.

Thanks!

**Comment by yudao** [comment]
@akimd How can I do a "full reset"? I'm only deleting the Docker Mac App. Is there something else to do to reset?  I can't access to Docker menu via the app cause she stuck. The diagnose is sent by command line.

**Comment by akimd** [comment]
Docker menu, preferences, reset, reset to factory defaults.

**Comment by yudao** [comment]
@akimd, I do not have access to Docker menu, cause Docker app do not responding and is completely freezing on start.

**Comment by akimd** [comment]
Ah, sorry about that.  Usually the menu is available even before it finished its initialization.

Beware that you will lose all your Docker settings and images, but try this:
```sh
$ rm -rf ~/Library/Containers/com.docker.docker
$ rm -rf ~/Library/Group\ Containers/group.com.docker
```

**Comment by yudao** [comment]
@akimd. 
Same.
My last Diagnose BC83180F-9037-427B-8314-31A7D680A02E

**Comment by akimd** [comment]
I guess it is related to this:
```
2018-01-18 15:42:23.085533+0100  localhost taskgated-helper[32197]: (ConfigurationProfiles) [com.apple.ManagedClient:ProvisioningProfiles] Checking profile: Docker Application
2018-01-18 15:42:23.085561+0100  localhost taskgated-helper[32197]: (ConfigurationProfiles) [com.apple.ManagedClient:ProvisioningProfiles] allowing entitlement(s) for com.docker.docker due to provisioning profile (isUPP: 1)
2018-01-18 15:42:23.092682+0100  localhost taskgated-helper[32197]: (ConfigurationProfiles) [com.apple.ManagedClient:ProvisioningProfiles] Checking profile: Docker Application
2018-01-18 15:42:23.092691+0100  localhost taskgated-helper[32197]: (ConfigurationProfiles) [com.apple.ManagedClient:ProvisioningProfiles] com.docker.docker: Unsatisfied entitlements: com.apple.security.application-groups
2018-01-18 15:42:23.092692+0100  localhost taskgated-helper[32197]: (ConfigurationProfiles) [com.apple.ManagedClient:ProvisioningProfiles] Disallowing: com.docker.docker
```
Does it ring any bell to you?

**Comment by akimd** [comment]
Could you please try to disable MacBooster to see if it would be the cause?  Then try again.

**Comment by yudao** [comment]
Completely removed. Same. 0980C515-2805-46E1-ABFF-2A1AE66EAF4C

**Comment by kcampos** [comment]
I'm seeing the same symptoms, can't get Docker to launch. Started clean, installed `17.12.0-ce-mac49` and the "next" button initial "whaly happy to see you" splash screen just hangs -> `993A423A-258C-464F-AD96-4CB61B97AB8A`

Installed the `17.12.0-ce-mac49 (72b93a017350990850ddc37cd341bd16fce3e911)` build you linked and that failed the same. -> `D6248E8F-3A18-4FBA-8E62-374AA530254C` as well as your second test link `08B66784-8702-484E-BC0C-C53DF17414CF`

**Comment by akimd** [comment]
I'm sorry for not being active in this issue.  So far I am clueless.  We are preparing the next releases which possibly could help us track down the issue thanks to even more logs.

**Comment by Meyfarth** [comment]
Hello @akimd ,

I got the same issue since this morning.

Some info:
Got High Sierra since few weeks ago
Using filevault

Yesterday:
- My docker crashed yesterday, I couldn't even quit it, had to kill the process
- I installed the latest stable version (I didn't know about the factory reset, or else I would've tried that!)

This morning:
- My computer stopped by itself overnight (as usual, thx MAC for your wonderful battery management)
- I changed my password due to company policies
- My VPN told me that a secure port was already used when it started, I terminated it
- Docker freezes on startup (exactly the same behavior described by my fellow githubers)
- I tried both versions you linked above, neither of them worked
- I don't know how I can send report or see logs about docker (nothing in `/var/log/system.log`)

😭

**Comment by akimd** [comment]
Hi guys,

Please try https://download.docker.com/mac/edge/23022/Docker.dmg, and have it report diagnostics.  Thanks in advance.

**Comment by yudao** [comment]
Hi Akimd!

Thanks a lot for the notification.

Unfortunately doesn't work yet:
```
9CB22E19-7DE4-4737-AA40-2DA2054E0AAC/20180306-155750
```

Thanks.

**Comment by akimd** [comment]
@yudao According to your logs, the installation of Docker seems very incomplete.  I would recommend running the full Uninstall cycle, and start anew.

**Comment by yudao** [comment]
@akimd I've uninstalled the app with AppCleaner, deleted all docker system directories:
```sh
$ rm -rf ~/Library/Containers/com.docker.docker
$ rm -rf ~/Library/Group\ Containers/group.com.docker
```
All is ok! Thanks a lot for your work!

Yu.

**Comment by ikvasnica** [comment]
I had the same problem - corrupt installation and the new one was freezing at start time.

The solution is to follow the steps from https://github.com/docker/for-mac/issues/2435#issuecomment-374148250, thanks @yudao a lot for saving me from system reinstall!

**Comment by yudao** [comment]
@ikvasnica thx. But many thanks to the team for their efforts ;)
