### ISSUE TITLE
17.12.0-ce-mac47 with raw VM disk - invalid ELF header without factory reset

### ISSUE THREAD

**Issue by OscarBarrett** [docker/for-mac#2439]
e.g. when trying to run curl in an elasticsearch image.
`docker run docker.elastic.co/elasticsearch/elasticsearch:6.1.1 curl`

### Expected behavior
`curl: try 'curl --help' or 'curl --manual' for more information`

### Actual behavior
`curl: error while loading shared libraries: /lib64/libkrb5.so.3: invalid ELF header`

### Information
Diagnostic ID: C389B635-CB72-4209-BF80-541A3B0ADF61

### Steps to reproduce the behavior
1. Update to 17.12.0-ce-mac47
2. Reset -> Remove all data
3. `docker run docker.elastic.co/elasticsearch/elasticsearch:6.1.1 curl`

It works after a full reset (`Reset -> Reset to factory defaults`).

**Comment by hyleung** [comment]
We had the same problem here (it's reproducible with the base OpenJDK image too). Reset to factory defaults also fixed it. Machine is running OS X High Sierra.

**Comment by zhaojunmo** [comment]
I have the same problem. 
At first, everything works fine for me, and suddenly it just doesn't work anymore, I don't know what caused it.

`
docker run -ti --rm r-base bash
root@8e726e7947aa:/# R
/usr/lib/R/bin/exec/R: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libquadmath.so.0: invalid ELF header
 `
macOS High Sierra version 10.13.3(17D47) -iMac (Retina 5K, 27-inch, 2017)
Docker Version 17.12.0-ce-mac49 (21995)

Diagnostic ID: 475DD677-FADB-4714-AC47-817B73BFAE66

@hyleung Do you mean that I have to reset my machine to factory defaults?

**Comment by shushenghong** [comment]
same problem,

docker logs mysql
/bin/bash: error while loading shared libraries: /lib64/libtinfo.so.5: invalid ELF header

docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

**Comment by maxweber** [comment]
I had a similar problem:

    /usr/bin/google-chrome-unstable: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libxcb.so.1: invalid ELF header

In my case it also helped to remove the image with `docker rmi` and pull it again.
