### ISSUE TITLE
Unable to pull image using proxy

### ISSUE THREAD

**Issue by Tony-Proum** [docker/for-mac#2440]
### Expected behavior

Unable to pull debian image through a proxy

### Actual behavior

getting this output : 

_> docker pull debian
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: unexpected EOF

### Information

Unable to reproduce using 17.12.0-ce-mac45,21669

Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/754F6905-076C-47E1-8529-811C20EE9598/20180116-164209.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. docker pull <an_image>

**Comment by Tony-Proum** [comment]
Today, I've been able to pull and image using the same proxy. Issue should be related to my own environment / proxy settings.

I close this issue as I'm not able to reproduce

**Comment by endzyme** [comment]
We have also received this sporadically on 17.12 with large image pulls (2GB+). It's inconsistent though.

**Comment by kbsivacse** [comment]
I have same problem to pull image of size 2GB+ on v17.12 in Windows platform. Any solution to this?
