### ISSUE TITLE
Docker won't start after update to latest docker. 

### ISSUE THREAD

**Issue by coreysnyder** [docker/for-mac#2441]
### Expected behavior
Docker starts.

### Actual behavior
Docker fails to start. It just loads forever. 

### Information
  Mac High Sierra - SSD - APFS Volume

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/63940DEC-A36F-4820-A2C6-EA377FC562B0/20180116-122708.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Update docker
  2. Docker failed to restart successfully
  3. I rebooted the mac
  4. I tried to start docker and it just loads forever.

**Comment by perayoss** [comment]
might be the same issue https://github.com/docker/for-mac/issues/2370

**Comment by akimd** [comment]
Please, see https://github.com/docker/for-mac/issues/2383#issuecomment-358246040.  Does that match your problems?

**Comment by akimd** [comment]
Could you please try this modified version of Docker 17.12? Hopefully it should fix your issue. If it does, we will soon release an official stable image which includes the fix. Once you tested it, be sure to reinstall a "real" stable release.

https://download-stage.docker.com/mac/pr/21923/Docker.dmg

**Comment by gtardif** [comment]
A small fix on this test build, if you get a chance you should rather uninstall and then try this build: https://download-stage.docker.com/mac/pr/21935/Docker.dmg. 
Keep in mind this is a test build, ignore any update it might propose, and after the test you will have to reinstall an Edge or Stable version to get proper updates again

**Comment by akimd** [comment]
Could you please check if the following image fixes your problems?  You might need to reset to factory defaults...

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again. Thanks!

**Comment by oliverfriedmann** [comment]
The live update was crashing my Docker, too, but this latest test build is working now on my Mac.

**Comment by akimd** [comment]
Great, thanks!

**Comment by gtardif** [comment]
We just released 17.12.0-ce-mac49 on the Stable channel that contains the fix mentioned above. (and 18.01 on the Edge channel also fixes this)

**Comment by coreysnyder** [comment]
Just grabbed the latest version. I got stuck in "starting" a handful of times. I initiated a factory reset which got stuck here for about 3 minutes: 
![screen shot 2018-01-22 at 12 09 14 pm](https://user-images.githubusercontent.com/17259723/35233817-2d88ffd0-ff6d-11e7-8f36-94ac97b824c9.png)

I actually typed all of this up but it eventually completed. After factory reset it it correctly started.
