### ISSUE TITLE
Periodic CPU spikes whilst "sleeping" and massive CPU spike after wake, with no containers running

### ISSUE THREAD

**Issue by mattdarveniza** [docker/for-mac#2444]
### Expected behaviour
With docker running and no containers active, CPU usage should be effectively null, and computer should be able to sleep without periodic wakes and CPU spikes, and should be able to fully wake without a huge CPU spike that renders the computer unresponsive for up to 5 minutes

### Actual behaviour
On a freshly rebooted machine, with docker started, but no containers running, whenever computer is put to sleep, it seems to periodically wake the machine and spike the CPU. I put my computer to sleep and checked it periodically, and the computer was noticeably hot to touch each time I checked it over the course of about 4 hours, indicating that even while supposedly in sleep mode, it was waking and using CPU.

Upon actually lifting the lid and unlocking the machine, CPU usage spikes to a full 100% (of all cores), rendering the machine almost unusable for about 5 minutes until it recovers, and generating an immense amount of heat in the process.

Note that none of this behaviour occurs when docker is not launched after boot.

### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/C451037C-E816-46D4-B2B8-2F18D67376BC/20180117-101118.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
No docker containers required to be running to make bug occur, so docker files not relevant

Included graphs of CPU spikes during sleep and after launch:
<img width="634" alt="screen shot 2018-01-17 at 10 08 42 am" src="https://user-images.githubusercontent.com/946261/35017378-b7d8272a-fb70-11e7-8d0e-92de7d1f41d8.png">

Note that from 9:08 to 10:03, the machine was supposedly "sleeping", however was waking with spikes every 5 minutes or so. I'm not clear if this is waking due to the PowerNap feature in macOS or not, however that usually isn't accompanied by such large spikes. Planning to test what happens with power nap turned off later today.

From 10:03 to 10:08 is when the machine was awake, with very large spikes.

From what I'm able to tell, kernal_task is the main cause of CPU spikes, the hyperkit being the secondary culprit. Again however, this doesn't occur when docker isn't launched.

### Steps to reproduce the behavior

1. Take a fresh computer running macOS 10.13.2 (with APFS if that makes a difference)
2. Install docker-mac 17.12.0-ce-mac45 and launch it
3. Sleep computer, and observe notable rise in temperature presumably from CPU usage
4. Wake computer, and note high cpu usage and subsequent unresponsiveness for about 5 minutes.

**Comment by mattdarveniza** [comment]
This actually turned out to be a hardware bug unrelated to Docker, so disregard. Closing.

**Comment by subfuzion** [comment]
@mattdarveniza I have the same issue. What was the hardware bug you identified?

**Comment by earlevel** [comment]
Guessing it's was a faulty surge protector. My old Mac Pro started glitching my power recently on wake (lights dim briefly, computer might fully restart, other things in the room might restart). I'm almost certain the power distribution box with surge protector is the fault, but so far just set my cpu to not sleep (drives ok to sleep) till I have time to replace it. It's been in service for years, I suppose it's gone bad. Typically, this kind of surge protector shorts to ground on a spike or surge, hence the symptoms.

**Comment by mattdarveniza** [comment]
In my case it was a hardware issue with the logic board. Not sure exactly what, one of those cases where Apple just replaced the whole thing and was good after that.
