### ISSUE TITLE
App won't start. Communication with networking components failed

### ISSUE THREAD

**Issue by QinMing** [docker/for-mac#2447]
### Expected behavior
Docker app starts.
### Actual behavior
When launching Docker app, I got error message saying "Communication with networking components failed"

### Information

**Diagnostic ID**:
`2D9AA290-507E-4D26-9352-3654CE1D1D80`

**Full output of the diagnostics**:
```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/2D9AA290-507E-4D26-9352-3654CE1D1D80/20180116-223632.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ming.qin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ming.qin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/ming.qin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/ming.qin/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ming.qin/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

```

**Screenshots**
![image](https://user-images.githubusercontent.com/8622078/35029145-692ef764-fb0e-11e7-9be9-7892851e3834.png)
![image](https://user-images.githubusercontent.com/8622078/35029153-7891f3dc-fb0e-11e7-8661-5594a06e5441.png)

**Additional Info when running some commands on terminal**
```sh
$ ls -l /Library/PrivilegedHelperTools/com.docker.vmnetd
-r-xr--r--@ 1 root  wheel  44512 Jan 16 22:49 /Library/PrivilegedHelperTools/com.docker.vmnetd

$ sudo launchctl list | grep com.docker
748	0	com.docker.vmnetd

$ ps uax | grep /Library/PrivilegedHelperTools/com.docker.vmnetd
root               748   0.0  0.0  4298828   4604   ??  Ss   10:49PM   0:00.01 /Library/PrivilegedHelperTools/com.docker.vmnetd
```
The above seems normal but the following one doesn't look right. As @djs55 said on https://github.com/docker/for-mac/issues/644#issuecomment-247569281 , the file `/var/tmp/com.docker.vmnetd.socket` should exist.
```sh
$ ls -l /var/tmp/com.docker.vmnetd.socket                                                                                                                                                                                     10:57:19
ls: /var/tmp/com.docker.vmnetd.socket: No such file or directory
```

### Steps to reproduce the behavior

1. Installed Docker for Mac and open it.
1. Type in password as it prompts.
1. The error will show up.

One day, I quit the Docker app from the menu bar. Since then, I can't start the app again.

### Things I have tried

1. Reboot. Re-install Docker for Mac.
1. Tried older versions, including `17.09.1-ce-mac42` and `17.06.2-ce-mac27`.
1. Tried removing `/Library/PrivilegedHelperTools/com.docker.vmnetd`

**Comment by hakamadare** [comment]
installing 18.01.0-ce-rc1-dev from the Edge channel resulted in a Docker for Mac that was able to launch successfully; switching back from Edge to Stable resulted in the same problem recurring.

**Comment by QinMing** [comment]
I tried the test build that @akimd provided in https://github.com/docker/for-mac/issues/2452#issuecomment-358378624 , but it didn't help. I also did the factory reset.

Here's the new diagnostics:

Diagnostic ID: `2D9AA290-507E-4D26-9352-3654CE1D1D80`

```
Docker for Mac: version: 17.12.0-ce-mac49 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/2D9AA290-507E-4D26-9352-3654CE1D1D80/20180117-202353.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ming.qin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ming.qin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/ming.qin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/ming.qin/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ming.qin/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

```

**Comment by akimd** [comment]
Could you please check if the following image fixes your problems?  You might need to reset to factory defaults...

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again. Thanks!

**Comment by QinMing** [comment]
@akimd I tried that exact build yesterday. See my previous comment
![image](https://user-images.githubusercontent.com/8622078/35117849-c2a0d4fc-fc44-11e7-9c6c-c35dac8e1e1a.png)

**Comment by QinMing** [comment]
Facepalm. I fixed it myself. It was on me.
I don't have the folder `/var/tmp/`
So I just `sudo mkdir /var/tmp/`, and that fixed it. 
Maybe Docker app should be more robust about that?

**Comment by akimd** [comment]
Can you show me (`ls -ld /var/tmp`) what owner/rights you gave that directory?

It's kind of funny not to have this directory.  I would expect more problems with other software.

**Comment by QinMing** [comment]
This is for the newly created folder
`drwxr-xr-x  3 root  wheel  96 Jan 18 17:00 /var/tmp`

**Comment by akimd** [comment]
Closing this issue because there's not much we can do actually (the way services are launched on the Mac allows to create sockets, but not create directories.  However:
- now we have a clean diagnostic when it happens
- maybe we'll move the socket elsewhere and avoid these issues.
