### ISSUE TITLE
Unable to upgrade/migrate to newest version, did work earlier.

### ISSUE THREAD

**Issue by zyxep** [docker/for-mac#245]
### Steps to reproduce

1. 
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Stopped NTP to get Docker for Mac to start but it crashed, i tried to reset to factory settings and then i got the information below.

I have tried to uninstall Docker for mac completely with `/Applications/Docker.app/Contents/MacOS/Docker --uninstall` and then install Docker for Mac again, no luck there.

### Information

```
Diagnostic ID: 3698B9C7-4253-4DCB-80C6-519E6047128F
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     dns
[OK]     moby-syslog
[OK]     app
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     virtualization
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     menubar
[ERROR]  db
         /Users/zyxep/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/zyxep/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/zyxep/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/zyxep/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     moby-console
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/zyxep/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
Does beta 25 help with this?  A lot of the sierra bugs have been addressed. 

Sorry about the problems you've been having.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
