### ISSUE TITLE
All my containers, images and volumes gone after update

### ISSUE THREAD

**Issue by cfrancio** [docker/for-mac#2451]
### Expected behavior
NO issues with upgrade
### Actual behavior
All images, containers and volumes disappear 
### Information
Diag ID: ADD76AEF-3688-409B-9DC5-816EC803988B

Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/
ADD76AEF-3688-409B-9DC5-816EC803988B/20180117-114954.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Click upgrade and restart after docker for Mac OS started.

**Comment by kyunam** [comment]
I just ran into the same problem.

~$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

**Comment by garystv** [comment]
Same issue here..

Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.11.6 (build: 15G17023)
logs: /tmp/A93E14A3-93FF-4C50-83D6-65DD14A486DA/20180119-105637.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk


~$ docker version                                                                                                                                                                                                                          
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by pgayvallet** [comment]
We apologize for the inconvenience. There was an issue in vm disk migration during switch from old VM to linuxkit which failed to handle some cases, and an issue that caused disk corruption in the way to were shutting down the VM when performing upgrade, causing disk reformat. Both these issues has been fixed on latest stable and edge version, and this should not happens again. 

Closing

**Comment by peanball** [comment]
The same still just happened to me with -mac55

Diagostics ID: 4B65461B-03DA-4096-A334-D4081A15788D

(18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/4B65461B-03DA-4096-A334-D4081A15788D/20180323-093002.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk

**Comment by tanmng** [comment]
This just happened to me today. Any chance of restoring the data?

**Comment by glemercier** [comment]
Same just happened to me after upgrading to version 2.0.0.0-mac78. Am I the only one?

**Comment by AlexDag** [comment]
I have a same happiness : OSX , updated to 18.09.0 and lost ALL of my images,

**Comment by mario-paniccia** [comment]
Same problem for me on my Mac after updgrade to docker 18.0

**Comment by lincoln310** [comment]
Same issue:

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: ELGC:OQOL:6YBN:LT5O:IPBY:X5ZL:ZAO7:6OVA:6YX2:K7HX:YHRD:IGJG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-05-09T03:49:41.758476507Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by PeGa** [comment]
I can't really believe the answer from @pgayvallet . "We messed up, we promise it won't gonna happen again"? I mean, all these people (including me, Gentoo 17.0) suffered the same symptom, and all data was casually lost, and the answer is "oops"? How this even got to production state?

**Comment by ballcap231** [comment]
It happened to me just yesterday - on windows 10. After updating to latest docker version.
