### ISSUE TITLE
Docker Won't start, stuck in "Docker is starting..."

### ISSUE THREAD

**Issue by ankitjamuar** [docker/for-mac#2453]
### Expected behavior
It should start normally and should go into running mode

### Actual behavior
Docker is stuck in  "Docker is starting..." message and do nothing

### Information

Diagnostic  (00DE7C3E-9B01-4BC7-B566-DF650320ACDF):
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/00DE7C3E-9B01-4BC7-B566-DF650320ACDF/20180117-203327.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ankitsinha/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ankitsinha/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/ankitsinha/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ankitsinha/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

Install Docker on MacOS High Sierra 10.13.2 and start docker

**Comment by Conrix** [comment]
I have exactly the same issue. 
I'am on Sierra 10.12.6 (16G1114)

**Comment by akimd** [comment]
Hi!

Could you please try this modified version of Docker 17.12? Ignore upgrades it might propose. Hopefully it should fix your issue. If it does, we will soon release an official stable image which includes the fix. Once you tested it, be sure to reinstall a "real" stable release.

https://download-stage.docker.com/mac/pr/21923/Docker.dmg

**Comment by jordanrw** [comment]
I just tried this version and it eventually worked for me. However, upon the first time opening the application, I received the error message: 
`Error dialog: "Fatal Error com.docker.supervisor failed to start
Exit code 1"`
I clicked restart 3 times. Then finally I quit Docker (instead of simply restarting). Upon re-opening it, it worked.

**Comment by vitorreis** [comment]
I am experiencing a similar issue with the version ` 17.12.0-ce-mac47 (21805)` it's crashing and giving timeouts after a few minutes... the edge version seems to have fixed it.

**Comment by ankitjamuar** [comment]
Yes, the edge version is working fine

**Comment by akimd** [comment]
It would be really great if one of you guys could validated the following image.  Both with an existing image, and from scratch, if possible.

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again.  Thanks!

**Comment by gtardif** [comment]
We just released 17.12.0-ce-mac49 on the Stable channel that contains the fix mentioned above. (and 18.01 on the Edge channel also fixes this)
