### ISSUE TITLE
Docker daemon not start

### ISSUE THREAD

**Issue by chenzi2015** [docker/for-mac#2455]
Hi,
I downloaded the latest version  and install， but daemon don't start.

I got `This can prevent Docker from starting, reset your daemon settings if it hangs.`   error .

**Look at this picture:** 
<img width="500" alt="wx20180118-111724 2x" src="https://user-images.githubusercontent.com/12816465/35079285-0864600e-fbcc-11e7-9e31-e5de91f13c6b.png">

**Comment by akimd** [comment]
What version?

**Comment by chenzi2015** [comment]
Version    17.12.0-ce

**Comment by akimd** [comment]
I suppose you mean 17.12.0-ce-mac47.  Please try the latest release.
