### ISSUE TITLE
17.12.0-ce-mac46+ breaks mounting /etc/passwd or /etc/group

### ISSUE THREAD

**Issue by krenor** [docker/for-mac#2458]
### Expected behavior

I should be able to mount `/etc/passwd` or `/etc/group`.

### Actual behavior

```
docker: Error response from daemon: Mounts denied:
The path /etc/passwd
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

Adding `/etc/passwd` to the file sharing:
```
docker: Error response from daemon: error while creating mount source path '/etc/passwd': mkdir /etc/passwd: file exists.
```
### Information

Diagnostic ID: 41845C20-9A15-4DBC-9726-9A6BA4B350B2

### Steps to reproduce the behavior

  1. `docker run -it -v /etc/passwd:/etc/passwd:ro alpine /bin/sh`

I had to downgrade to **17.09.1-ce-mac42** to get it back working.

**Comment by c4tz** [comment]
This is pretty bad, because the official composer docker image is using those paths:

https://hub.docker.com/_/composer/

> When combining the use of private repositories with running Composer as another (local) user, you might run into non-existant user errors (thrown by ssh). To work around this, simply mount the host passwd and group files (read-only) into the container:

```
docker run --rm --interactive --tty \
    --volume $PWD:/app \
    --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --user $(id -u):$(id -g) \
    --env SSH_AUTH_SOCK=/ssh-auth.sock \
    composer install
```

**Comment by vrcAlbert** [comment]
Hi 👋 

Is there any possibility to fix this mounting problem without downgrading ?

I updated to High Sierra in order to use `.raw` format coming with "17.12.0-ce-mac46". Now that I've migrated I would prefer not to roll back if possible :)

**Comment by madnight** [comment]
`Is there any possibility to fix this mounting problem without downgrading ?`
No, downgrade and wait for a fix is the only solution at the moment.

**Comment by shadyoak** [comment]
@vrcAlbert On macOS, the `/etc` directory is symlinked to `/private/etc`. So, as a workaround, you can bind mount to the `/private/etc` location. For example:

`docker run -it -v /private/etc/passwd:/etc/passwd:ro alpine /bin/sh`

Will that work for you?

**Comment by vrcAlbert** [comment]
Hi @shadyoak, thanks for that info. 

Unfortunately I cannot reproduce the problem at the moment : we updated our images to avoid using that very specific folder (`/etc`).
However, `private` folder is already shared in default configuraiton. I guess it does not solve my original problem.

I'll let you know if I find the time to reproduce it.

Thanks again.

**Comment by shadyoak** [comment]
@vrcAlbert  - The following will still fail (as @krenor posted above):

`docker run -it -v /etc/passwd:/etc/passwd:ro alpine /bin/sh`

However, this command is functionally equivalent and will succeed:

`docker run -it -v /private/etc/passwd:/etc/passwd:ro alpine /bin/sh`

The `/etc/passwd` and `/private/etc/passwd` paths point to the same file on macOS.

**Comment by lucymhdavies** [comment]
Docker for Mac v18.03 has different behaviour to what was originally reported.
(Not sure which version added this behaviour)

It no longer gives you that `Mounts denied` error when attempting to bind `/etc/group`.

However, it does result in some interesting behaviour:

```
🐳 :~ lucy $ cat /etc/passwd | grep apple
_appleevents:*:55:55:AppleEvents Daemon:/var/empty:/usr/bin/false

🐳 :~ lucy $ cat /etc/passwd | wc -l
      96

🐳 :~ lucy $ docker run -it -v /etc/passwd:/etc/passwd:ro alpine /bin/sh
/ # cat /etc/passwd | grep apple
/ #

/ # cat /etc/passwd | wc -l
29
```

i.e. while it's no longer complaining that you can't bind these files, if you're relying on them for your images, you may be in for a surprise.

As has been pointed out, `/etc` on macOS is a symlink to `/private/etc`, so if you cannot avoid binding these files, then you'll need the `/private` versions:

```
🐳 :~ lucy $ docker run -it -v /private/etc/passwd:/etc/passwd:ro alpine /bin/sh
/ # cat /etc/passwd | grep apple
_appleevents:*:55:55:AppleEvents Daemon:/var/empty:/usr/bin/false
/ # cat /etc/passwd | wc -l
96
```

Personally, I try to avoid binding them entirely if I can avoid it.

**Comment by mgpoly** [comment]
Same problem when trying to mount /home.  This behavior change breaks EXISTING DinD scenarios.  Programmers "know what they're doing" and so Docker should not be so restrictive.

Needs to be fixed/reverted.
