### ISSUE TITLE
Docker update broke Docker

### ISSUE THREAD

**Issue by NicTorgersen** [docker/for-mac#2459]
### Expected behavior
Update and restart docker and then continue working.

### Actual behavior
Docker updated itself, asked for my password as it needed elevated permissions. On restart of the Docker service it crashes with the error: `com.docker.supervisor failed to start Exit code 1`.

### Information

  - Diagnostic ID: AA0E9CC4-B394-4E00-B2BF-79CEE3F2F4F1
  - When the update was downloading, the service was still starting up. Not sure if the service was actually running or not when the update happened.

**Comment by akimd** [comment]
If that Docker for Mac 17.12, could you please check if the following image fixes your problems? You might need to reset to factory defaults...

https://download-stage.docker.com/mac/pr/21949/Docker.dmg

This is a test build. Ignore any update it might propose, and after testing, reinstall an Edge or Stable version to get proper updates again. Thanks!

**Comment by NicTorgersen** [comment]
Will test in a bit, thanks for the swift answer :D

**Comment by NicTorgersen** [comment]
This is Docker 17.12.0-ce-mac47 (21805) for Mac, yes :)

I'll test and get back to you.

**Comment by NicTorgersen** [comment]
That fixed my issue!

**Comment by akimd** [comment]
Great!  Expect a fix release of 17.12 soon.

**Comment by gtardif** [comment]
We just released 17.12.0-ce-mac49 on the Stable channel that contains the fix mentioned above. (and 18.01 on the Edge channel also fixes this)
