### ISSUE TITLE
Docker not running

### ISSUE THREAD

**Issue by MilindAtGithub** [docker/for-mac#246]
### Expected behavior
Docker should start
### Actual behavior
getting error:

Error response from daemon: Bad response from Docker engine
### Information

Diagnostic ID: 3F059C8C-14A0-48BE-95B6-A2E900048316
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.1 (Build 15B42)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/milinddeobhankar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/3F059C8C-14A0-48BE-95B6-A2E900048316/20160812-170216/qemu-img-check.stdout 2> /tmp/3F059C8C-14A0-48BE-95B6-A2E900048316/20160812-170216/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

**Comment by mchiang0610** [comment]
@MilindAtGithub Can you try resetting to factory defaults? Would like to see if it is still causing problems after. 

Closing until reply.
