### ISSUE TITLE
Docker Mac app quits with no error/warning 

### ISSUE THREAD

**Issue by Nowaker** [docker/for-mac#2461]
Diagnostic ID: E4FFEC36-E84A-4989-9B75-CA9BB822A9B0

### Expected behavior

Docker app doesn't die.

### Actual behavior

Docker app dies. Not the VM/Hyperkit - but the whole Mac App. At some point, usually in 5-15 minutes after I start the app, it disappears, and is no longer visible in the top menu:

![image](https://user-images.githubusercontent.com/611746/35111754-9d6f4a40-fc41-11e7-87a3-3f22a06e3bdf.png)

There's no error message of any sort. The app disappears, I start it again, it starts its internal VM, and Docker works again, until it quits again. When it quits, its VM is shut down too, and any `docker run -it` process quits too. Console output: `ERRO[0056] error waiting for container: EOF`.

#### Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/E4FFEC36-E84A-4989-9B75-CA9BB822A9B0/20180118-111555.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

#### A reproducible case if this is a bug, Dockerfiles FTW

Not related to building. Not related to any image. The app will quit after 5-15 minutes even when I don't spin up any container.

### Steps to reproduce the behavior

Unknown. 

This was happening on a previous version of Docker app. I upgraded but the problem still occurs.

**Comment by akimd** [comment]
Please try a more recent version of Docker for Mac.

**Comment by Nowaker** [comment]
Upgraded to Docker 17.12.0-ce-mac49.

New diagnostic ID: E4FFEC36-E84A-4989-9B75-CA9BB822A9B0

Please reopen, @akimd. Thanks!

**Comment by akimd** [comment]
```
2018-01-23 09:10:25.986900-0600  localhost com.docker.vmnetd[24525]: com.docker.vmnetd starting
2018-01-23 09:10:26.943585-0600  localhost com.docker.vmnetd[24526]: Client reports version 1, commit f50f37646dc326edce3ac0edfd617323a846d8fb
2018-01-23 09:10:26.944128-0600  localhost com.docker.vmnetd[24526]: EOF reading packet from Unix domain socket: closing
2018-01-23 09:10:26.944516-0600  localhost com.docker.vmnetd[24526]: Failed to read command from client
```
For some reason, vmnetd fails to install itself.  I expected the forthcoming 18.03 to have fixed issues in this area.  Sorry for keeping you waiting :(

**Comment by Nowaker** [comment]
@akimd Is this really what makes the Docker app quit? Please note the app quits 5-15 minutes after running without any issues. If this is the cause, how to fix it? How to debug it?

**Comment by Nowaker** [comment]
I've just spotted a new version. Experiencing the same problem - app quits with no error/warning after some time. **Please re-open this ticket.**

New diagnostic ID: E4FFEC36-E84A-4989-9B75-CA9BB822A9B0

**Comment by Nowaker** [comment]
CC @djs55 @gtardif
