### ISSUE TITLE
Docker fail on start

### ISSUE THREAD

**Issue by pisupatisukumar** [docker/for-mac#2468]
### Expected behavior
Docker for Mac should be running

### Actual behavior
Docker for Mac is installed and failed to start.

### Information
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/93372CB3-06EE-410F-91FF-F0F60BA5FE54/20180119-060027.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/bobby/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bobby/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/bobby/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/bobby/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
1. Download and Install Docker for Mac .dmg
2. Start Docker from Applications Menu
3. Give the Admin password during first time startup
4. Error message about Docker unable to start and message dump.

**Comment by ogroleg** [comment]
same for me

**Comment by gtardif** [comment]
We just released 17.12.0-ce-mac49 on the Stable channel that contains a fix for this. (and 18.01 on the Edge channel also fixes this)
