### ISSUE TITLE
Docker for mac - docker engine isn't starting.

### ISSUE THREAD

**Issue by brooksjbr** [docker/for-mac#247]
### Expected behavior
`$ docker ps` 
Return list of running docker containers
### Actual behavior
`$ docker ps`
Error response from daemon: Bad response from Docker engine
### Information
Updated to version 1.12.0-a, docker doesn't start.
Diagnostic ID: 58B2AF8B-854C-42AA-BE58-2432BA20015C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in 58B2AF8B-854C-42AA-BE58-2432BA20015C/20160812-074055.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-08-11T11:38:03.062158378Z" level=debug msg="Using default logging driver json-file"
time="2016-08-11T11:38:03.063008432Z" level=debug msg="Golang's threads limit set to 13950"
time="2016-08-11T11:38:03.063718880Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-08-11T11:38:03.068706465Z" level=debug msg="Using graph driver aufs"
time="2016-08-11T11:38:03.286777955Z" level=debug msg="Failed to load mount 1eb407d9533ab5199b92686d8cfec90e3dcea9d638e75c443520a3d11512c906: invalid mount id value"
time="2016-08-11T11:38:03.303872538Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-11T11:38:03.304249899Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-11T11:38:03.418729201Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-08-11T11:38:03.422728549Z" level=debug msg="Loaded container 02df4d2e0906da568bf84c10bdbf756070c0d310e8449a7909ecc3ba4c70ca69"
time="2016-08-11T11:38:03.425226411Z" level=debug msg="Loaded container 0e0289a4d6dbfa540cfe8079461b6f751cfe29042c8ad14a015b54c459a86a58"
```
