### ISSUE TITLE
Inconsistent network settings prevent good proxy configuration

### ISSUE THREAD

**Issue by loganmzz** [docker/for-mac#2470]
### Expected behavior
I'm using a local CNTLM proxy in order to connect my mac with corporation proxy.

With Docker 17.09, I used to set Docker proxy settings using `docker.for.mac.localhost` as hostname. Which used to work both from Docker engine (host) and from containers.

After migration to Docker 17.12, `docker.for.mac.localhost` is not longer supported from Docker host.

### Actual behavior
I can't figure out how to configure network as same proxy can be used from both Docker host and inside containers.

I tried to add host alias from `docker.for.mac.localhost` to `127.0.0.1` into `/etc/hosts` from my local machine but then containers are unable to resolve `docker.for.mac.localhost`

### Information

* Engine: 17.12.0-ce
* Compose: 1.18.0
* Machine: 0.13.0
* Notary: 0.4.3
* Credential Helper: 0.6.0

### Steps to reproduce the behavior

1. Sets up a local proxy
2. Configures Docker 17.12 to use local proxy (`127.0.0.1` address)
3. Tries to access Internet address from a container

**Comment by Abiwax** [comment]
Any solution to this yet ?

**Comment by loganmzz** [comment]
For the moment:
* I have configured Docker to use system proxy which points to my local proxy
* I have created a `~/.docker/env`with my environment variables shared by all containers
* I create/run containers always with a `--env-file ~/.docker/env` parameter.

Note: Supporting this feature: moby/moby#16699 would have been perfect !
A bash function is provided but I don't find its a good solution, just a temporary workaround ...

**Comment by djs55** [comment]
Thanks for your report.

There's a bug in the current shipping versions which prevents HTTP proxies on `docker.for.mac.localhost` from working properly.

I've made a prototype of a fix -- if you'd like to try it it's available from https://download-stage.docker.com/mac/bysha1/8bf53acf91f089aa8e14f2f8720b12d144bd195b/Docker.dmg

The build identifies as `Version 18.03.0-ce-rc2-mac56 (23056)`

To test it, I set the HTTP and HTTPS proxies in Whale menu -> Preferences -> Proxies to `http://docker.for.mac.localhost:8080` and ran a proxy on `127.0.0.1:8080` on the host. When I performed an HTTP transaction in a container, I saw the traffic on the proxy as expected.

Note this is an experimental build and shouldn't be used for anything other than testing. It may offer an auto-update -- don't accept, as the updated version would not have the prototype fix in it.

Let me know if this makes any difference for you. If not, could you upload a set of diagnostics (Whale menu -> Diagnose and Feedback..) and quote the id? The logs inside the diagnostics bundle should help me understand what's going on.

**Comment by loganmzz** [comment]
@djs55 I have Mac only on Thursday and Friday.￼ So I will do the test on 2018-03-08.

**Comment by loganmzz** [comment]
I have tried with proxy set in Docker for mac preferences. But it doesn't work:
https://asciinema.org/a/WvlYYKOUqIKfnuaaVtnPM8rOg

Same problem with build:
https://asciinema.org/a/Zq7ojwhYbvXcZWWjbNkkl6JOh

Docker pull works fine. I have same behaviour using system proxy in Docker preferences.

**Comment by djs55** [comment]
@loganmzz Thanks for the attempt and recording the demonstration!

In the first example:
```
bash-3.2$ docker run --rm -ti node curl http://www.google.com                                                                                                                                               
curl: (6) Could not resolve host: www.google.com                                                                                                                                                            
```

It looks like you don't have working DNS -- unfortunately the transparent proxy requires DNS because the HTTP requests are sent *after* the DNS lookup.

Could you try one more experiment for me? Try editing your `~/.docker/config.json` to look like this:

```
$ cat ~/.docker/config.json
{
  "auths" : {

  },
  "proxies": {
    "default": {
      "httpProxy": "http://docker.for.mac.host.internal:3128",
      "httpsProxy": "http://docker.for.mac.host.internal:3128",
      "noProxy": "",
      "ftpProxy": ""
    }
  }
}
```

This should set the environment variables in `docker run` and `docker build`, for example:

```
$ docker run -it alpine sh -c set
HOME='/root'
HOSTNAME='5071db83142d'
HTTPS_PROXY='http://docker.for.mac.host.internal:3128'
HTTP_PROXY='http://docker.for.mac.host.internal:3128'
IFS='
'
OPTIND='1'
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PPID='0'
PS1='\w \$ '
PS2='> '
PS4='+ '
PWD='/'
SHLVL='1'
TERM='xterm'
http_proxy='http://docker.for.mac.host.internal:3128'
https_proxy='http://docker.for.mac.host.internal:3128'
```

**Comment by loganmzz** [comment]
Nice ! It works on `18.03.0-ce-rc2-mac56 (23188)`

**Comment by djs55** [comment]
@loganmzz thanks for the confirmation. I've labelled this ticket as `kind/docs` since I think we should document this case a bit more.

**Comment by DanJSuciu** [comment]
I am still not able to connect out to the internet after updating the `~/.docker/config.json`, after the updates suggested above I am getting the following output...
```
[danielsuciu : ~]$ docker run --rm -ti node curl http://www.google.com
curl: (7) Failed to connect to docker.for.mac.host.internal port 3128: Connection refused
```
Here are my docker version and info outputs...
```
[danielsuciu : ~]$ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
[danielsuciu : ~]$ docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 58
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TSDX:ZEAN:2PRY:RLEJ:22QG:ONLY:2SMO:RQRL:RJDQ:ZYZC:LFG5:WRGS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-04-04T13:40:55.536572538Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by kevinojt** [comment]
I have the same problem.  I ran "docker run hello-world" after a fresh installation and got this output:

Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
9bb5a5d4561a: Pulling fs layer
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/e3/e38bc07ac18ee64e6d59cf2eafcdddf9cec2364dfe129fe0af75f1b0194e0c96/data?Expires=1524071230&Signature=cX-XWhxK-I3mEgtio9pwvBQ~A4revgWK8sevFpOqxhM5cdfTLNncOytYz483JiamTtUWOEPUIK959N7h1PclVS3203ft0WBo6wiAcRSikOd9MGBu5jlVqbLoRCBTuH6ICm3ib4pq8lO3TNFSZkI1z1T28GY5xX1XUZ3ns9ej0Ug_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.


Here is the docker info output
----------------------------------------------
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: KKAR:5LVZ:NE3C:O455:BI5S:TBK2:XSOU:QR4A:VBJT:NCLE:RRU2:UFME
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 39
 System Time: 2018-04-18T05:09:41.559413806Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
