### ISSUE TITLE
Upgrade/download/relaunch/crash/download/relaunch/crash loop

### ISSUE THREAD

**Issue by paul-hammant** [docker/for-mac#2472]
### Expected behavior

Docker Mac upgrades itself when it said it would, after I pressed a button saying to do that

### Actual behavior

Crash - in a loop

### Information

![docker_err](https://user-images.githubusercontent.com/82182/35182761-bc170a06-fda8-11e7-8747-1c33cb66d257.png)

### Steps to reproduce the behavior

 Can't reproduce for now - it sorted itself out, but only after immediately re-downloading a god chunk of the 350MB download. This is the second upgrade that this has happened for me - hence I was ready to take a screenshot.

The problem may never reoccur of course, **I just wanted to snap the two dialogs in play for posterity**, and the slight confusing choices for the end user. I pressed Exit every time, and as I say it eventually got itself in order.  Feel free to insta-close this issue.

**Comment by pgayvallet** [comment]
For posterity, thanks.
