### ISSUE TITLE
Feature request - Providing kubernetes container images in Docker Hub

### ISSUE THREAD

**Issue by denverdino** [docker/for-mac#2474]
The gcr.io is not accessible in China.  So when enabling Kubernetes, it is stuck . Can we provide kubernetes container images in Docker Hub? Thanks a lot

**Comment by pgayvallet** [comment]
Seems doable using an environnement variable : kubernetes/kubeadm#182

**Comment by pgayvallet** [comment]
Except... the images in https://hub.docker.com/r/googlecontainer are not up too date... version v1.9.2 is missing for example... We can't pull from there.

**Comment by denverdino** [comment]
https://github.com/denverdino/k8s-for-docker-desktop

I create the helper scripts to download the gcr.io images from image mirrors of Alibaba Cloud
