### ISSUE TITLE
Docker fails to start after upgrade

### ISSUE THREAD

**Issue by magnusaxelqvist** [docker/for-mac#2477]
### Expected behavior

Docker starts after upgrade without errors.

### Information

Diagnostic ID: 0C0C35C1-2450-43A6-8D0A-8CB02F898A78

### Steps to reproduce the behavior

  1. Start Docker after the upgrade

**Comment by corbs9** [comment]
I had the same issue but I had to remove all traces from my mac. I first uninstalled the docker application, then I cleaned out the following directories/files:

* ${HOME}/Library/Group Containers/group.com.docker
* ${HOME}/Library/Containers/com.docker.docker
* /Library/LaunchDaemons/com.docker.vmnetd.plist
* /usr/local/bin/docker
* /usr/local/bin/docker-compose

**Comment by akimd** [comment]
We just released 17.12.0-ce-mac49 on the Stable channel that is likely to fix this (and also 18.01 on the Edge channel).

Please them and reopen this issue if needed.
