### ISSUE TITLE
Docker crashes after adding insecure registry

### ISSUE THREAD

**Issue by wittlesouth** [docker/for-mac#2478]
### Expected behavior
Should be able to add localhost:5000 as an insecure registry without crashing

### Actual behavior
After adding localhost:5000 to the insecure registry, Docker crashes on start

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
     - I left the "Diagnosing" window up for about 5 minutes with no result, so I gave up. If the diagnostics are supposed to take that long or longer, I suppose I can do this again.
  - A reproducible case if this is a bug, Dockerfiles FTW
     - Not needed AFAIK, as it seems to be just a docker config issue
  - Page URL if this is a docs issue or the name of a man page
     - N/A

### Steps to reproduce the behavior

  1. Open Preferences
  2. Click Daemon header
  3. Click the plus button in the "insecure registries" section
  4. Enter localhost:5000
  5. Click save
  6. Agree to restart
  7. Docker crashes

I don't know if the fact that I have a kubectl proxy running on localhost:5000 already is relevant, but I would hope not... :-)

Config: High Sierra 10.13.2

Unfortunately this does not seem to be repeatable after reset to factory defaults.

**Comment by wittlesouth** [comment]
Additional comment, it turns out that this is repeatable, the key is to not press return after entering the value for the insecure registry; click save without hitting return. I suspect this results in an empty value in the insecure registry list, since the entry was not 'completed'. If you hit return so that the insecure registry value is no longer an editable field, then it seems to work fine.

**Comment by chris-goodchild** [comment]
I can confirm this behaviour also occurs on the following system:

OS: OSX El Capitan 10.11.6
Docker: Version 17.12.0-ce-mac49 (21995)
Channel: stable

Steps to reproduce are as above, although unlike @wittlesouth it doesn't matter if I avoid hitting enter or not, the issue happens either way.

**Comment by tfedyanin** [comment]
confirm
OS: OSX highSierra 10.13.2 (17C205)
Docker: Version 17.12.0-ce-mac49 (21995)
Channel: stable

On edge it's ok

**Comment by multipathmaster** [comment]
Instead of looking at the basic tab, click on advanced and put it as follows:
```
{
  "debug" : true,
  "experimental" : true,
  "insecure-registries" : [
    "server.domain.com:5000"
  ]
}
```
or substitute a FQDN for localhost.
this worked for me as a work around!!!

**Comment by pgayvallet** [comment]
Issue will be fixed on next edge / stable.

For now, please use @multipathmaster's workaround.

**Comment by doug-fish** [comment]
I had this problem even using a FQDN instead of localhost (I was using a server.domain.com type url). @multipathmaster 's workaround of configuring on the advanced tab worked for me, however,  I thought the statement "or substitute the FQDN for localhost" meant I could use the basic tab since I wasn't using localhost. I had to use the advanced tab even though I used the FQDN.

**Comment by letmelearncode** [comment]
for me...I added it in advance tab but could only get a crash report saying Time out has expired and the operation has not been completed. From the logs I could find "fatal: invalid mirror: unsupported scheme "xxx.aa.xxxxx.com" in "xxx.aa.xxxxx.com:port""
