### ISSUE TITLE
No longer able to manage TCP packet flow (iptables) in DockerForMac VM 

### ISSUE THREAD

**Issue by chroto** [docker/for-mac#2489]
### Expected behavior
1. Connect to DockerForMac VM via screen
2. Run the following command: `/sbin/iptables --append PREROUTING --destination 169.254.169.254 --protocol tcp --dport 80 --in-interface docker0  --jump DNAT --table nat --to-destination 127.0.0.1:8169 --wait`
3. TCP traffic destined for 169.254.169.254:80 are re-routed to 127.0.0.1:8169

### Actual behavior
1. -sh: iptables: not found

### Information

***NOTE*** This was working prior to upgrading to 17.12.0-ce-mac47

```
Docker for Mac: version: 17.12.0-ce-mac47 (72b93a017350990850ddc37cd341bd16fce3e911)
macOS: version 10.12.6 (build: 16G1114)
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

```
#!/bin/bash
DOCKER_TTY=~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
MY_AWS_CREDS="${AWS_CREDS:=$HOME/.aws/credentials}"

if ! screen -list | grep -q "dockermachine"; then
    screen -d -m -S dockermachine $DOCKER_TTY
fi

# stuff in a newline to start
screen -L -S dockermachine -p 0 -X stuff "$(printf \\r)"

# add IPTABLES rule to send packets going to 169.254.169.254 to 127.0.0.1:8169
echo "Setting IPTABLES rule for the Docker VM tcp:169.254.169.254:80 -> tcp:127.0.0.1:8169"
screen -L -S dockermachine -p 0 -X stuff $'\n\n/sbin/iptables --append PREROUTING --destination 169.254.169.254 --protocol tcp --dport 80 --in-interface docker0 --jump DNAT --table nat --to-destination 127.0.0.1:8169 --wait\n\n'
echo '.'

# Tell the kernel to all  routing for loopback interface/"localnet" (disabled by default)
echo "Setting kernel networking config to allow for localhost routing"
screen -L -S dockermachine -p 0 -X stuff $'\n\nsysctl -w net.ipv4.conf.all.route_localnet=1\n\n'
echo '..'

# Fetch the metadataproxy image
docker pull lyft/metadataproxy

# Run the Metadata Mock
echo "Using the credentials file at ${MY_AWS_CREDS}"
echo '...'
echo "Launched the lyft/metadataproxy container.  Access logs will start streaming here"
echo '....'
echo "Ctrl+c to stop the server"
docker run --net=host -it -e PORT=8169 -e MOCK_API=true -v /var/run/docker.sock:/var/run/docker.sock -v "${MY_AWS_CREDS}:/root/.aws/credentials" lyft/metadataproxy

```

**Comment by chroto** [comment]
It may help to explain that I am configuring the DockerForMac VM to mock an external prod or pre-prod environment (in this case, AWS EC2) so we can test how a container image will behave once it's deployed.

**Comment by pgayvallet** [comment]
@chroto iptables is not available on the vm host. But it's present on the docker container.
from inside the vm, to enter the container : 
`ctr -n services.linuxkit tasks exec --tty --exec-id ssh-$(hostname)-$$ docker-ce ash -l`

(or maybe `ctr tasks exec --tty --exec-id ssh-$(hostname)-$$ docker-ce ash -l`, or `ctr tasks exec --tty --exec-id ssh-$(hostname)-$$ docker ash -l`)

```
linuxkit-025000000001:/# iptables
iptables v1.6.1: no command specified
```

Can you try see if you can achieve what you want ?

**Comment by chroto** [comment]
@pgayvallet thanks for the reply.  I should have a chance to try that out soon.  

From your reply it sounds like that linuxkit container on the VM is actually hosting the Docker daemon.  Is that correct?  and is that what was meant in that Changelog item from this update?

> VM entirely built with Linuxkit

**Comment by dsolsona** [comment]
@pgayvallet thanks! that worked for me
```
/ # iptables
/bin/sh: iptables: not found

/ # ctr -n services.linuxkit tasks exec --tty --exec-id ssh-$(hostname)-$$ docker-ce ash -l
linuxkit-025000000001:/# iptables --version
iptables v1.6.2
```

**Comment by slotrans** [comment]
I'm not the issue opener (he and I worked together at the time) but I was able to get our script working by changing
```/sbin/iptables <args>```
to
```ctr -n services.linuxkit tasks exec --exec-id ssh-$(hostname)-$$ docker-ce iptables <args>```

Still not really clear...
1. what that command does
1. how one would discover that this is necessary
1. why iptables isn't present on the host VM in the first place

...but at least our script is now working with Docker for Mac 18

**Comment by jayavanth** [comment]
Docker-ce container is no longer available in the vm. Does anyone know if it was moved/removed/renamed?

**Comment by jayavanth** [comment]
Huh? ^

**Comment by jayavanth** [comment]
I don't know how I managed to do that ^
