### ISSUE TITLE
Docker on Mac osx 10.12 fails to start

### ISSUE THREAD

**Issue by kevarley** [docker/for-mac#249]
### Information

Diagnostic ID: 0E38B06A-D33E-4193-8370-56228B17D764
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A284a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by glynjackson** [comment]
related to https://github.com/docker/for-mac/issues/64

**Comment by mchiang0610** [comment]
Beta 25 solves most of the sierra issues: https://download.docker.com/mac/beta/Docker.dmg

Stable release should follow soon!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
