### ISSUE TITLE
Download error on update attempt to  upgrade from Version 17.12.0-ce-mac47 (21805) to 17.12.0-ce-mac49

### ISSUE THREAD

**Issue by londoncalling** [docker/for-mac#2490]
### Expected behavior

Successful download and install.

### Actual behavior

Download fails.

### Information

See pix.
  
### Steps to reproduce the behavior

  1. Choose to `Install Update` either from `Check for Updates..` menu or upon auto-prompt. 
  2. Download fails.

### Screen snaps

![docker-update-prompt](https://user-images.githubusercontent.com/11660803/35292678-1fab382e-0026-11e8-9d78-0c29ad8c5c24.png)

![docker-download-error](https://user-images.githubusercontent.com/11660803/35292684-227be0e4-0026-11e8-971d-1882d1ffb4dd.png)

**Comment by akimd** [comment]
Please try more recent releases.  I think you've just been unlucky in the timing.

**Comment by elison-chen** [comment]
I am receiving the same issue @londoncalling have you been able to update in the end?

I just tried checking for newest update today and was seeing the same thing. 'Check for Updates' should find the most recent release right?

**Comment by VickyAtThoughtSpot** [comment]
@elison-chen , well  I just went to the download site and downloaded the latest version :-)  Now all seems to be fine with upgrades. I'm glad it worked for you!

[Docker for Mac Install](https://docs.docker.com/docker-for-mac/install/)

[Docker for Windows install](https://docs.docker.com/docker-for-windows/install/)
