### ISSUE TITLE
Kubernetes context selector doesn't work

### ISSUE THREAD

**Issue by dgageot** [docker/for-mac#2495]
### Expected behavior

`18.01.0-ce-mac48` comes with a UI selector to select a Kubernetes context. I expect that when I click on the Docker whale, I see a `Kubernetes` menu to select a context.

### Actual behavior

The `Kubernetes` menu entry is displayed but doesn't have an arrow and doesn't open a sub menu to choose the context.

I tried deleting my `~/.kube/config` file and let Docker recreate one. It did recreate one but the menu still won't work.

<img width="242" alt="screen shot 2018-01-23 at 1 26 20 pm" src="https://user-images.githubusercontent.com/153495/35302350-f4f4e856-0042-11e8-8d05-61d118ec670a.png">

**Comment by akimd** [comment]
This is a known issue, and the fix is in flight.  https://github.com/docker/pinata/pull/8675

Thanks for the report!

**Comment by Runrioter** [comment]
looking forward to next release

**Comment by dgageot** [comment]
This is fixed in `mac50`. Thank you!
