### ISSUE TITLE
Docker starting error

### ISSUE THREAD

**Issue by IgorRatynski** [docker/for-mac#2498]
### Expected behavior
Docker should start up

### Actual behavior
Docker is not setting up

### Information

Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/65B96676-483B-4678-B037-3589D727FFB7/20180124-055203.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/igorratynski/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/igorratynski/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/igorratynski/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/igorratynski/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/igorratynski/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

### Steps to reproduce the behavior

  1. It's docker 18.01.0-ce version. Also I had try install from https://download.docker.com/mac/stable/Docker.dmg and had same result.
  2. ...

**Comment by phyber** [comment]
This has happened to me every time I've upgraded Docker for Mac recently. It gets stuck in the starting state, and even trying to "Diagnose" gets stuck, so I cannot get output like the above. Rebooting allows Docker to start correctly until the next update.

**Comment by tedmiston** [comment]
Possible dupe - https://github.com/docker/for-mac/issues/2502

**Comment by pgayvallet** [comment]
Hello,

```
[ERROR] virtualization kern.hv_support
sysctl -a reports no hypervisor support
```

in the diag is the root cause of the other errors, and means that your hardware (cpu) is not compatible with docker for mac.

We added more explicit error messages in last edge regarding this.
