### ISSUE TITLE
Docker won't start. Probably something with my 2 harddrives and spaces in the disk names

### ISSUE THREAD

**Issue by Behendri** [docker/for-mac#25]
### Information

Diagnostic ID: 06B5623F-C787-4790-A610-2C1DD056E058
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Volumes/Macintosh HD/Users/BHendriksen/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/06B5623F-C787-4790-A610-2C1DD056E058/20160730-005353/qemu-img-check.stdout 2> /tmp/06B5623F-C787-4790-A610-2C1DD056E058/20160730-005353/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Can you give us more information on what worked and what didn't during the install process? Which dialogs did you see? Spaces in disk name should be supported. I am closing this issue for now on, but please re-open when you have more information.
