### ISSUE TITLE
Incompatible CPU: Requires Virtualization

### ISSUE THREAD

**Issue by brandontamm** [docker/for-mac#250]
I have been using Docker with Virtualbox on this PC for years and I tried the "Docker for Mac" application that is suggested by Docker. Apparently this doesn't work on a 2010 Intel-based Mac running 8gb, 2.3ghz, Intel Core i7, 4-core...virtualization isn't a problem. I don't understand the limitation... 

**Diagnostics Copy/Paste:**
### Information

Diagnostic ID: C66B2825-CA73-4B9E-948E-007A4A7FFC0A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         wrong Docker version: 1.11.1 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/btamm/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/btamm/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/btamm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/C66B2825-CA73-4B9E-948E-007A4A7FFC0A/20160812-091510/qemu-img-check.stdout 2> /tmp/C66B2825-CA73-4B9E-948E-007A4A7FFC0A/20160812-091510/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/btamm/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/btamm/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/btamm/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/btamm/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/btamm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by brandontamm** [comment]
sysctl kern.hv_support
kern.hv_support: 0

So hypervisor is a hard requirement? Any possibility of overcoming this without a laptop upgrade? Still waiting for Apple to release an updated Macbook since last fall :( ... and waiting...

**Comment by brandontamm** [comment]
Intel VT-xxx Virtualization is listed as "Yes" for this CPU:
http://ark.intel.com/products/41316/Intel-Core-i7-860-Processor-8M-Cache-2_80-GHz

Is there a way to enable Hypervisor if this is currently just disabled? BIOS setting?

**Comment by brandontamm** [comment]
Please see post here as well - https://forums.docker.com/t/fatal-error-incompatible-cpu-detected/9162/14

There has to be a super simple solution to flip this configuration switch - I am fully supported but it is disabled by default.. *thanks Apple*!

**Comment by mchiang0610** [comment]
Given that this is a laptop at the cut-off, it should work if you are not receiving a warning that says incompatible CPU. 

Please try resetting to factory defaults within the app. Give it another try, and we will see how to troubleshoot this further. 

Thanks1

**Comment by brandontamm** [comment]
I can assure you that this is exactly what happens - even on a fresh OS X El Capitan install 

Brandon Tamm

**Comment by brandontamm** [comment]
Please see my comment and reopen - this issue is very much alive affects a large user base. Please see the two example links for an idea of the velocity of the issue..
