### ISSUE TITLE
Docker crashes after update

### ISSUE THREAD

**Issue by chermed** [docker/for-mac#2502]
### Expected behavior
Can start after update

### Actual behavior
Can not start, it requests a factory reset

FATAL ERROR
com.docker.supervisor failed to start
Exit code 1

### Information
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/1AF723C3-31C1-40BD-8EF4-EFFF61DA2672/20180124-200112.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/USER/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/USER/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/USER/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Update to the last release  17.12.0-ce-mac49

**Comment by skkannan21** [comment]
same issue, any solution

**Comment by miensol** [comment]
I think we're having the same issue
```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/D377F57B-4DB1-46D5-ACBC-058D52B632FB/20180125-103437.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/macmini/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/macmini/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/macmini/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

**Comment by tedmiston** [comment]
I'm getting this as well as only on a machine behind VPN.  On my other machine the k8s install took a couple minutes but worked fine.

I've uninstall and reinstalled 3+ times today to no avail.  Kubernetes fails to enable every time on this machine.

Anyone know if it's possible to download a binary install of the previous release?  That one worked fine on my corporate machine.

**Comment by TimDAdams** [comment]
Ditto here.

macOS: version 10.12.6 (build: 16G1114)
Docker.app: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
Local time: Fri Jan 26 09:32:55 PST 2018
UTC:        Fri Jan 26 17:32:55 UTC 2018
Timestamp:  20180126-093255
Running diagnostic tests:
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /Users/tim/Library/Containers/com.docker.docker/Data/s60: check if service is running
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   vpnkit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/tim/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/tim/Library/Containers/com.docker.docker/Data/s51
[ERROR]   vpnkit           com.docker.vpnkit is not running
Error docker ps: got timeout (docker ps: exit 1)

**Comment by gregmacfarlane** [comment]
I have this issue as well, but I am not running a VPN at all.

**Comment by kutenai** [comment]
Is there no solution here?
I rely on Docker for all of my development. Just updated to 10.13.4, and now docker errors out when starting. I've reset re-installed. So far, nothing works. This really puts a damper on my development workflow... geeze.

**Comment by tedmiston** [comment]
I haven't tested the new Docker release that just came out last week yet.  AFAIK this is an open issue.  I currently run an old build `Version 18.03.0-ce-mac58 (23607)` on edge channel.
