### ISSUE TITLE
HyperKit consuming 300%+ of CPU resources

### ISSUE THREAD

**Issue by kyleknighted** [docker/for-mac#2503]
### Expected behavior
For my laptop not to become a jet engine. :) 

### Actual behavior
After a few hours of running a Rails server within Docker, hyperkit goes into hyper-space and consumes all of the CPU

### Information

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/AB3CA78B-7A35-4E88-8B31-C6BE5FC4E1D1/20180124-142520.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Diagnostic ID: `AB3CA78B-7A35-4E88-8B31-C6BE5FC4E1D1`
<img width="1034" alt="docker" src="https://user-images.githubusercontent.com/122591/35356256-7c549120-0115-11e8-9109-576bcbfb7f3e.png">

### Steps to reproduce the behavior

1. Run `docker-compose up -d`
2. Wait a minute or two
3. Fans spin up into a jet engine
4. CPU spikes and never comes down

**Comment by asakaev** [comment]
Version 18.01.0-ce-mac48 (22004) same issue.

**Comment by vielmetti** [comment]
Version 18.02.0-ce-rc2-mac51 (22446) same issue. Resolved at least temporarily with "Restart" (Cmd-R) from the Docker menu.

**Comment by shin1x1** [comment]
I also seen same issue at Version 18.03.0-ce-mac60 (23751).
Using `Reset to factory defaults` at `Preferences - Rest` solve the problem.

**Comment by VonUniGE** [comment]
Switching from my ISP DNS to OpenDNS solved for me a similar issue.
