### ISSUE TITLE
All images have dissappeared after upgrade

### ISSUE THREAD

**Issue by beveridj** [docker/for-mac#2504]
### Expected behavior
Docker version is upgraded with all existing images intact.
### Actual behavior
All images are missing.
### Information
Diagnostic ID:946EFE5B-C5E9-40D6-AB56-7709F99A9E88

### Steps to reproduce the behavior

  1. Upgrade to version: 17.12.0-ce-mac49 (21995)
  2. docker images

**Comment by pgayvallet** [comment]
We apologize for the inconvenience. There was an issue in vm disk migration during switch from old VM to linuxkit which failed to handle some cases, and an issue that caused disk corruption in the way to were shutting down the VM when performing upgrade, causing disk reformat. Both these issues has been fixed on latest stable and edge version, and this should not happens again. 

Closing
