### ISSUE TITLE
No Proxy configuration is ignored since v46

### ISSUE THREAD

**Issue by Tony-Proum** [docker/for-mac#2506]
### Expected behavior
```
docker info
```
this command should show the No Proxy: section set in docker4mac preferences. And this No Proxy: section should be used in running containers

### Actual behavior

Unable to bypass proxy for a specific domain in a running container using docker4mac

### Information
```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/754F6905-076C-47E1-8529-811C20EE9598/20180125-111543.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

Set a http_proxy, https_proxy and a bypass domain name in docker4mac preferences. tip `docker info` in a command line. This command should list the bypassed domain used in configuration. And obviously this bypassed domain should be used in running containers

### Note 

This issue have been reproduced on v46 and v49. but v35 works fine.

**Comment by djs55** [comment]
Thanks for your report.

Could you give an example where a container is unable to bypass a proxy, despite the proxy bypass being set perhaps with `wget` or `curl`?

The settings in `docker info` are expected because there is a proxy builtin to Docker for Mac, which connects either to an upstream proxy (if configured) or the origin server (if unconfigured, or if it matches the bypass settings).

**Comment by Tony-Proum** [comment]
Hello, 

I'm able to reproduce using Version 18.03.0-ce-mac59 (23608) 

you can see here the result of docker info command :

```
docker info
Containers: 117
 Running: 0
 Paused: 0
 Stopped: 117
Images: 69
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: YLBM:N57A:D5LG:GPOL:QTVR:KZRN:L7RD:JXAI:I5DV:EEDM:BWDY:PYCP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 53
 System Time: 2018-04-11T07:43:27.4565082Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I'm not able to pull some dependency on a running container (e.g: maven dependency on an internal repository) when those dependencies need to bypass proxy settings using no_proxy configuration (e.g: `docker run mvn clean install`). Also, I'm able to do a curl on this dependencies (bypassing the proxy)  outside the container.

The proxy settings (and bypass option) are used and works when building a container using `docker build ...`

**Comment by laugimethods** [comment]
How that months old issue could still be on hold? Why "more info needed"?
That's a regression bug that should be addressed quickly since it affect at least OpenShift on Mac (https://forums.docker.com/t/no-proxy-no-longer-working-in-mac-17-12-0/44126/6).

**Comment by laugimethods** [comment]
Using `System proxy` (https://docs.docker.com/docker-for-mac/#proxies) is also broken...
