### ISSUE TITLE
Kubectl is removed when disabling Kubernetes

### ISSUE THREAD

**Issue by Gisleburt** [docker/for-mac#2508]
### Expected behavior

When I disable kubernetes in docker for mac, I should still be able to use kubectl to access my other (non-local) clusters.

### Actual behavior

Disabling kubernetes in docker for mac, removes kubectl.

### Information

Related to #2368

### Steps to reproduce the behavior

  1. With kubernetes enabled run `kubectl` and you will see the help information
  2. Disable kubernetes in docker for mac, run `kubectl` and you will get `command not found: kubectl`
  3. Renable kubernetes in docker for mac and `kubectl` is restored.

**Comment by akimd** [comment]
If you install kubectl (say from brew for instance), we restore it when you quit.  We try to cohabit nicely in such scenarios.  So I guess I mean "that's a feature".

**Comment by Gisleburt** [comment]
Hmm, kubectl was originally installed from homebrew. 

```bash
$ brew search kubectl
==> Searching local taps...
kubectl ✔
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
```

I only disabled kubernetes through the preferences though, I left Docker running. 

<img width="507" alt="screen shot 2018-01-25 at 15 15 48" src="https://user-images.githubusercontent.com/2369524/35395588-b0ef468c-01e2-11e8-932c-a3af0bc667fb.png">

Just noticed it's still in "starting" mode too...

**Comment by akimd** [comment]
Actually my answer is about the current development of Docker, sorry.  The forthcoming release _will_ restore the original kubectl when you quit Docker for Mac.  WRT the "Starting..." issue, please check again when you move to the next release.

**Comment by gmatev** [comment]
@akimd not sure which release you are referring to above. I was just able to repro for 18.03.0-ce-rc1-mac54 (23022). 

This behavior is pretty impactful since, I do regularly disable my local Docker Kubernetes instance through Preferences (for battery life reasons) but still use kubectl to connect to other remote clusters.

**Comment by akimd** [comment]
The current (desired) behaviour is that kubectl is uninstalled if Kube is disabled.  My comments were referring to the fact that existing installations of kubectl were broken.  AFAICT, when we disable (Docker for Mac's) kubectl, then the previously installed one is restored.

Do you see something different?
Do you expect something different?

**Comment by jmcclell** [comment]
@akimd Why is that the current desired behavior? It's nonsensical to me. I want kube installed (and I'm happy to have Docker be the ones to do it), but I don't necessarily need it *running* all the time. I don't see why the installation of kube and the running state are tied together as a single concept. It's entirely unintuitive. I would much rather be able to "Stop Kubernetes" and "Uninstall Kubernetes" as separate concepts.

**Comment by gmatev** [comment]
@jmcclell what you describe as "Stop" is actually the current behavior. Under Preferences -> Kubernetes you can disable and enable K8s. It does not uninstall but just stops your cluster.
