### ISSUE TITLE
vpnkit Dropping TTL exceeded

### ISSUE THREAD

**Issue by asakaev** [docker/for-mac#2511]
System hang after some time after docker-compose

macOS Console logs:
default	16:11:44.101524 +0300	vpnkit	Dropping TTL exceeded src' = 127.0.0.1 dst' = 127.0.0.1; src = 127.0.0.1:50821; dst = 127.0.0.1:8092
default	16:11:44.101585 +0300	vpnkit	Dropping TTL exceeded src' = 127.0.0.1 dst' = 127.0.0.1; src = 127.0.0.1:50821; dst = 127.0.0.1:8092
default	16:11:44.101647 +0300	vpnkit	Dropping TTL exceeded src' = 127.0.0.1 dst' = 127.0.0.1; src = 127.0.0.1:50821; dst = 127.0.0.1:8092

a lot of same logs.

Terminal not responding. Spinning wheel.
Force quit terminal close terminal window but it's impossible to open terminal again.
Activity Monitor window is empty inside all tabs.

Docker restart does not help.
Docker Diagnose hangs on Diagnosing...

Version 18.01.0-ce-mac48 (22004), Stable channel same issue.
After High Sierra update.

**Comment by akimd** [comment]
According to @djs55 the TTL messages are just warnings, the trouble is elsewhere.

Diagnosing can be extremely slow, especially if the machine is loaded (which does not appear to be the case, granted).

Have you tried to uninstall and reinstall?

**Comment by asakaev** [comment]
Yea. Reinstalling doesn't help. Is there are any logs to check when and what makes Docker to hang?

**Comment by akimd** [comment]
I would recommend starting Console, setting "Docker" in the search field, and make it "Process" filter.

Could you by any chance try a more recent version of Docker for Mac?

**Comment by stromnet** [comment]
I've seen these to, even on a freshly booted machine with no docker containers running at all (but Docker itself is running).
The machine is not unstable though, but it would be nice go get an explanation on what this actually means.

In my case it is `Docker: Dropping TTL exceeded src'=<local gw ip> dst'=<host ip>; src = <host ip>:60074; dst = <local gw ip>:192`. 
According to $internet port 192 is `Apple AirPort Base Station PPP status or discovery (certain configurations), AirPort Admin Utility, AirPort Express Assistant`. I do have Airport express admin utility installed, but what does this have to do with Docker??


Docker 17.12.0-ce-mac55 (23011)
