### ISSUE TITLE
Java JRE headless - can't load classes

### ISSUE THREAD

**Issue by gebele** [docker/for-mac#2512]
`Exception in thread "main" java.lang.NoClassDefFoundError`

For some reason I get this exception everytime I try to run a jar file inside my containers.
Tried with Arch, Alpine, Debian containers and jre7-openjdk-headless, jre8-openjdk-headless.

Version 17.12.0-ce-mac49 (21995)
os sierra 10.12.6

On servers using Docker I never run into this ?
Which further information is needed ?

**Comment by pgayvallet** [comment]
Please provide an image and run command that fails on D4M but succeed on the same docker version on linux
