### ISSUE TITLE
Ping/ICMP not working in 17.12.0-ce-mac49 (21995)

### ISSUE THREAD

**Issue by tkeeler33** [docker/for-mac#2513]
### Expected behavior
Ping/ICMP should show a valid ping response 
### Actual behavior
Running `ping example.org` or `ping [LAN IP]` inside of a container times out.  
### Information

  - Ping inside a container successfully works in `17.09.1-ce-mac42 (21090)`
  - Ping still works after an upgrade to `17.12.0-ce-mac49 (21995)`
  - Performing a clean install or reset to create a new VM will prevent ping from working

### Steps to reproduce the behavior

  1. Fresh install of `17.12.0-ce-mac49 (21995)` or perform a `Remove all data`/`Reset` after upgrading
  2. Execute `ping example.org` or any valid network address inside of a container and it will time out

**Comment by pgayvallet** [comment]
Hello.

```
docker run alpine ping www.google.fr
PING www.google.fr (216.58.204.99): 56 data bytes
64 bytes from 216.58.204.99: seq=0 ttl=37 time=4.765 ms
64 bytes from 216.58.204.99: seq=1 ttl=37 time=5.793 ms
64 bytes from 216.58.204.99: seq=2 ttl=37 time=6.989 ms
64 bytes from 216.58.204.99: seq=3 ttl=37 time=5.153 ms
64 bytes from 216.58.204.99: seq=4 ttl=37 time=5.061 ms
^C
--- www.google.fr ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 4.765/5.552/6.989 ms
```

seems to work fine with direct access. 

What is your network/proxy configuration ?

**Comment by tkeeler33** [comment]
Okay this is a bizarre one. I just upgraded back to `-mac49` to reproduce the issue and it is working fine now. The bizarre part is that this issue affected 3 devs on our team (on different systems).  For what its worth we are using `docker-compose` with the default network config on a direct network (no proxies). Perhaps something happened during our upgrades, but there was one developer with a clean install. 

I will close this out and monitor the situation. If the issue comes back I will report back with additional info.
