### ISSUE TITLE
Question: restart menu obfuscation

### ISSUE THREAD

**Issue by ktiedt** [docker/for-mac#2519]
What is the reasoning behind the horrid UX decision to move the top level "restart" option behind the "Reset [BOMB]" tab that includes destructive options unrelated to restarting? Not only making it harder to find but also doubling the amount of user interactions required to facilitate a restart...

On MacOS a restart is often necessary to prevent several issues (like inability to bind ports)... why can't a sensible menu option stay in a sensible location?

**Comment by akimd** [comment]
Duplicates https://github.com/docker/for-mac/issues/2407.
