### ISSUE TITLE
[18.02.0-ce-rc1-mac50] Kubernetes starting...

### ISSUE THREAD

**Issue by Runrioter** [docker/for-mac#2521]
### Expected behavior
Kubernetes works well
### Actual behavior
Kubernetes starting... all the time
### Information
```
Diagnostic ID: CE4A2914-3014-4028-87A4-C82AF91C5DFD
Docker for Mac: version: 18.02.0-ce-rc1-mac50 (e1912a8c46ae6f60a85d277f7b8d210dc9670b28)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/CE4A2914-3014-4028-87A4-C82AF91C5DFD/20180127-130501.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

![image](https://user-images.githubusercontent.com/1078011/35468914-1f5ae9d2-0364-11e8-9da6-2bde90cc7576.png)

At the same time, toggle <kbd>Enable Kubernetes</kbd>, <kbd>Apply</kbd> below always is disabled.

**Comment by ns7381** [comment]
@Runrioter I also have this problem. Please tell me how to resolve this

**Comment by Runrioter** [comment]
@ns7381  Run `docker images` in ternimal, then paste output here.

**Comment by ns7381** [comment]
@Runrioter 
`➜  ~ docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
ubuntu                                                   latest              0458a4468cbc        3 days ago          112MB
docker/kube-compose-controller                           v0.3.0-rc1          d099699fac52        5 days ago          25.8MB
docker/kube-compose-api-server                           v0.3.0-rc1          6c13a6358efa        5 days ago          39MB
busybox                                                  latest              5b0d59026729        5 days ago          1.15MB
gcr.io/google_containers/kube-apiserver-amd64            v1.8.2              6278a1092d08        3 months ago        194MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.8.2              5eabb0eae58b        3 months ago        129MB
gcr.io/google_containers/kube-scheduler-amd64            v1.8.2              b48970f8473e        3 months ago        54.9MB
gcr.io/google_containers/kube-proxy-amd64                v1.8.2              88e2c85d3d02        3 months ago        93.1MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.5              fed89e8b4248        4 months ago        41.8MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.5              512cd7425a73        4 months ago        49.4MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.5              459944ce8cc4        4 months ago        41.4MB
gcr.io/google_containers/etcd-amd64                      3.0.17              243830dae7dd        11 months ago       169MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        21 months ago       747kB
➜  ~`

**Comment by ns7381** [comment]
@Runrioter 
<img width="580" alt="2018-01-29 8 46 36" src="https://user-images.githubusercontent.com/5730585/35511176-8f4296de-04c0-11e8-85aa-a8d42f902551.png">

**Comment by ns7381** [comment]
@Runrioter 
<img width="888" alt="2018-01-29 8 46 48" src="https://user-images.githubusercontent.com/5730585/35511189-9f818672-04c0-11e8-8c65-949d6dbed934.png">

**Comment by Runrioter** [comment]
@ns7381  You have the right suit of images. I doubt that if they are downloaded manually. If so, make docker of mac download them.

**Comment by ns7381** [comment]
@Runrioter They are downloaded automatically by docker of mac, not manually

**Comment by ns7381** [comment]
<img width="711" alt="2018-01-30 6 48 02" src="https://user-images.githubusercontent.com/5730585/35538661-552d44cc-0514-11e8-81cb-ed8b0671be6b.png">
@Runrioter I restart docker for mac. It display kubernetes is running, but it is actually not.Run `kubectl cluster-info` in terminal,here is all output
<img width="1279" alt="2018-01-30 6 38 46" src="https://user-images.githubusercontent.com/5730585/35538655-4fe04ff0-0514-11e8-8d5d-58702d2bb802.png">

**Comment by ns7381** [comment]
@Runrioter I restart docker for mac. It display kubernetes is running, but it is actually not.Run `kubectl cluster-info` in terminal,here is all output
<img width="1279" alt="2018-01-30 6 38 46" src="https://user-images.githubusercontent.com/5730585/35538694-6a2c3a18-0514-11e8-924d-d69dd3fe1957.png">
<img width="711" alt="2018-01-30 6 48 02" src="https://user-images.githubusercontent.com/5730585/35538704-7089c4c0-0514-11e8-96cf-9b4746d5f519.png">

**Comment by ns7381** [comment]
@Runrioter This is error message.
<img width="1256" alt="2018-01-31 7 59 51" src="https://user-images.githubusercontent.com/5730585/35598202-8c844bfe-05e7-11e8-9f6c-1803d898e2e0.png">

**Comment by ns7381** [comment]
@Runrioter This is error message.
<img width="1266" alt="2018-01-31 8 01 57" src="https://user-images.githubusercontent.com/5730585/35598229-b93b7dc0-05e7-11e8-87da-4055fddc9867.png">
