### ISSUE TITLE
Allow for uploading of diagnosis without rerunning

### ISSUE THREAD

**Issue by su-narthur** [docker/for-mac#2525]
### Expected behavior

Diagnose, then decide whether or not to upload after diagnose has run

### Actual behavior

Software forces me to rerun diagnosis if I didn't initially choose to upload it

### Steps to reproduce the behavior

  1. Open Docker toolbar menu
  2. Click "Diagnose and Feedback..."

**Comment by akimd** [comment]
That was fixed in recent releases.
