### ISSUE TITLE
Failure to install Docker under Sierra

### ISSUE THREAD

**Issue by briantopping** [docker/for-mac#253]
### Expected behavior
The web page for Docker states that it is for Yosemite 10.10.3 or later. I am running Sierra as noted below. 

On first install, I got the following errors. After launching a second time, it appears to have run cleanly. Just learning Docker, so I don't have a good idea whether the install is fully operational, but on the second launch I got a dialog stating Docker is up and running and the menu bar icon is present.

### Information

Diagnostic ID: 9BA08C8A-DC0D-40B5-AC0D-A65203A783CB
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A284a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/btopping/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/9BA08C8A-DC0D-40B5-AC0D-A65203A783CB/20160812-123536/qemu-img-check.stdout 2> /tmp/9BA08C8A-DC0D-40B5-AC0D-A65203A783CB/20160812-123536/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/btopping/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/btopping/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/btopping/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/btopping/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/btopping/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Beta 25 solves most of the sierra issues: https://download.docker.com/mac/beta/Docker.dmg 

Stable release should follow soon!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by briantopping** [comment]
Got it, thank you!
