### ISSUE TITLE
Docker fails to start after reboot

### ISSUE THREAD

**Issue by marnen** [docker/for-mac#2531]
### Expected behavior
Docker starts normally.

### Actual behavior
I get the error "com.docker.supervisor failed to start".

### Information

Diagnostic output:

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.12.6 (build: 16G1114)
logs: /tmp/EE9AF3CF-30A8-4913-9CDF-C8C63C0B9763/20180129-124022.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/marnen/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/marnen/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --style syslog --last 1d | grep -i docker > \"/tmp/EE9AF3CF-30A8-4913-9CDF-C8C63C0B9763/20180129-124022/docker-system-os.log\": exit 1")
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/marnen/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Shut down machine abnormally (i.e. hold down power button to turn off).
  2. Reboot and log in.
  3. Attempt to launch Docker app.
  It fails nearly every time under these circumstances.

**Comment by akimd** [comment]
Docker tried hard to launch, but to no avail.  The logs are almost empty!

have you tried to uninstall and try again?

**Comment by marnen** [comment]
@akimd I could try reinstalling, but this is a brand new Docker installation: I never had Docker on this computer till last week. Also, once Docker fails, it prompts to reset to factory defaults, and in the course of that, it *appears* to do at least *some* reinstallation; at least, it asks me for an admin password and *claims* to be reinstalling some stuff...

**Comment by akimd** [comment]
Gee...  We'll have to spend more time on your logs then...

Maybe you could try to generate logs again?  Those ones really say nothing (al least to me...).

**Comment by akimd** [comment]
So we agree Docker never ever worked correctly on this machine?

**Comment by marnen** [comment]
@akimd No, Docker works beautifully on this machine—right up to the point where I have to do an abnormal reboot, as described above.

**Comment by marnen** [comment]
(The abnormal reboots were due to an unrelated issue, not Docker's fault, AFAIK)

**Comment by marnen** [comment]
So let me restate the problem differently. Docker works nicely on my computer until I have to reboot it as described above. Once I reboot, I have to go through the cycle of "failed to start"/"reset to defaults". If I do that, it again works beautifully...till the next time I need to do an abnormal reboot.

**Comment by marnen** [comment]
One other piece of possibly useful info: when I start the Docker app, it takes a *very long* time before it switches from "Docker is starting" to "Docker is running". Is there a log I can watch during that time so I can see what it's doing?

**Comment by marnen** [comment]
You know, that makes me think I should try a reinstallation. But why should I need one after only a week? Is the fact that I'm using Docker from a non-admin account giving it problems?

**Comment by marnen** [comment]
Following the [instructions](https://docs.docker.com/docker-for-mac/#uninstall-or-reset) to uninstall. Will reinstall and see what happens.

**Comment by marnen** [comment]
OK, having reinstalled Docker: I haven't yet had occasion to do an abnormal reboot, but I did find something:

1. Launch newly reinstalled Docker. Use it for a couple of hours with no problems (except for docker-compose starting very slowly).
2. Quit Docker.
3. Reopen Docker.

I'd have expected it to launch without much problem (or immediately give an error), but after 10 minutes or so of "Docker is starting…", I gave up.

There's clearly something that Docker doesn't like about my configuration, but how would I go about finding out what it is?

**Comment by marnen** [comment]
This part of it looks like a similar issue to https://github.com/docker/for-mac/issues/119.

**Comment by akimd** [comment]
Hi @marnen.  Please, do "Report and diagnose" a second time to see what going on.

If you want to see logs, run the "Console" application, in the search field type "docker" <ENTER> and turn it into "Process" filtering.  Then maybe the logs might show something.

But that's roughly what "Diagnose and report" will do.

**Comment by marnen** [comment]
@akimd:
> Please, do "Report and diagnose" a second time to see what going on.

OK, I'll do that when I'm back at my computer. 

> If you want to see logs, run the "Console" application, in the search field type "docker" and turn it into "Process" filtering

Would that do anything different than `syslog -k Sender Docker` (the method recommended in the docs), which gives nothing?

**Comment by marnen** [comment]
Of course, by Murphy's Law, the next time I started the Docker application, it loaded quickly. :P I'll post logs when this problem recurs.

**Comment by akimd** [comment]
I believe that `syslog` is phased out by macOS.  Besides, I find Console quite convenient (once you started using it :).

**Comment by akimd** [comment]
I'll close this issue.  Feel free to reopen if you manage to reproduce.

**Comment by marnen** [comment]
That's fine. I was about to do the same thing myself. :)

**Comment by marnen** [comment]
@akimd:

> I believe that `syslog` is phased out by macOS. 

I suspect you're right, but that's what the Docker documentation still recommends for viewing logs. 

> Besides, I find Console quite convenient (once you started using it :)

I agree with you. My question about whether it would do anything different was simply because I had already run `syslog` and didn't want to do the same thing twice.
