### ISSUE TITLE
v18.02.0-ce-rc1-mac50 (22256) docker-compose very slow

### ISSUE THREAD

**Issue by josja** [docker/for-mac#2534]
Just updated and noticed the slow down of the commands docker-compose up & stop.

When booted the containers are running smoothly and hyperkit sits idle around 4% CPU but using  docker-compose is very slow. When upping Hyperkit sits for two minutes on 4% then spikes to 300% for 30 seconds but most of the time it is just sitting there doing nothing (4%) on docker-compose up. When docker-compose is slow I expect my hardware to be the bottleneck.

### Expected behavior
- Boot my 8 containers around 1 minute. 

### Actual behavior
- Boots my 8 containers around 4 minutes

### Information
- Diag ID: 0B4CB049-BB4B-42C0-9264-AA9990330117
- Apple OSX 10.13.2
- Edge 18.02.0-ce-rc1-mac50 (22256)

### Steps to reproduce the behavior
- ```sudo docker-compose stop```
- Update Docker to Edge 18.02.0-ce-rc1-mac50 (22256)
- ```sudo docker-compose up``` / ```sudo docker-compose stop```

**Comment by thinkspill** [comment]
Also seeing this on:

Version 18.02.0-ce-rc1-mac50 (22256)
macOS 10.13.2 (17C2120)

I'm waiting minutes for a `docker-compose up -d` to complete, which it eventually does.

**Comment by nei** [comment]
Also seeing this and the memory usage is very high.

Version 18.02.0-ce-rc1-mac50
MacOs 10.13.2

**Comment by josja** [comment]
Just updated to Version 18.02.0-ce-rc2-mac51 (22446). Looks good so far, CLI feels faster.

**Comment by thinkspill** [comment]
Same here, containers starting much faster after upgrading to (22446).

**Comment by jankyupeblik** [comment]
So ...is this resolved by having actually determined the problem and having it fixed, or not? Mostly just curious, but it's definitely annoying to have to deny Docker's update dialog every day because I don't want to blow an hour realizing a new version is unusable.

**Comment by jankyupeblik** [comment]
...yomama's stale, robot.
