### ISSUE TITLE
Docker can't start after add new mirrors  to the "Registry mirrors"

### ISSUE THREAD

**Issue by BadTudou** [docker/for-mac#2537]
### Expected behavior
Docker can't start after add new mirrors  to the "Registry mirrors"

### Information
macOS High Sierra 10.13.3

Community Edition
Version 17.12.0-ce-mac49 (21995)
Channel: stable
f50f37646d
### Steps to reproduce the behavior

  1. Add a new registry-mirrors to Docker, **Keep the input box to get the focus**, then click "Apply & Restart" button
![image](https://user-images.githubusercontent.com/4954182/35567587-83f16d78-0600-11e8-8310-a15cd2bdc7d8.png)
  2. Docker auto restart, got the error
![image](https://user-images.githubusercontent.com/4954182/35567618-9cd3bcb0-0600-11e8-9049-6d67d57d391a.png)
 3. After that, the content of ' ~/.docker/daemon.json' was:
```
{
  "debug" : true,
  "registry-mirrors" : [
    ""
  ],
  "experimental" : true
}
```

### Manual repair
1.
```
vi ~/.docker/daemon.json
```
2. Add new registry-mirrors to the ' ~/.docker/daemon.json', like this:
```
{
  "debug" : true,
  "registry-mirrors" : [
    "http://4e05aeb3.m.daocloud.io"
  ],
  "experimental" : true
}
```
3. Restart Docker, There's nothing wrong with it

**Comment by hoiyd** [comment]
Having exactly the same issue

macOS Sierra
version 10.12.6

Community Edition
Version 17.12.0-ce-mac49 (21995)
Channel: stable
f50f37646d

**Comment by akimd** [comment]
Good catch!  I can reproduce it.

**Comment by akimd** [comment]
@aduermael Could you have a look at the GUI side of it?  I'll see if I can do something about the daemon being broken.

**Comment by aduermael** [comment]
@akimd I'm on it!

**Comment by akimd** [comment]
You're fast :)

**Comment by aduermael** [comment]
I opened a PR to fix the issue on the UI side.

But discovered something else:
- Enter a fake registry mirror (e.g. `foo`)
- Apply changes

The daemon can't start, the panel remains disabled so there's no way to update the value... (only option is to manually edit `daemon.json`). 

The daemon should be able to inform the GUI when it can't start. When in that situation, the daemon settings should be accessible. (I opened an internal issue to discuss this @akimd)

**Comment by pgayvallet** [comment]
@aduermael what do you mean "fake" registry mirror ? if that's juste invalid format, we should be able to perform simple validation, no ?

**Comment by pgayvallet** [comment]
Fixed in latest edge (18.02.0-ce-mac52)

**Comment by ifeengwd2012** [comment]
Thanks!

**Comment by akimd** [comment]
Let's close this, thanks for having checked!

**Comment by razertory** [comment]
It's exactly an UI bug
