### ISSUE TITLE
Time is wrong in my container after reboot on OSX

### ISSUE THREAD

**Issue by randy98** [docker/for-mac#254]
### Information

Diagnostic ID: 5A3A17A1-03C9-4108-8CC0-36DA1F7EB99D
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. install docker 1.12
2. docker pull ubuntu
3. run with restart=yes
4. reboot OSX
5. time is now off by 2 hours

Confirmed that my time on my laptop is correct.  Not sure how to get into docker-machine VM to check its time.  All connectivity to the internet is fine too.  I can't seem to run ntp inside the container...I guess that's a host/kernel setting perhaps?  I'm not too much of an expert in containers.

**Comment by mchiang0610** [comment]
@randy98 Thanks for reporting. This seems like a docker/docker issue.  

Thanks!

**Comment by dsheets** [comment]
See also #17 and #500.
