### ISSUE TITLE
docker image corruption

### ISSUE THREAD

**Issue by tjamet** [docker/for-mac#2542]
Hi,

As discussed in [slack](https://dockercommunity.slack.com/archives/C2TJ8FEJY/p1517221420000160) and in https://github.com/moby/moby/issues/36135 I had a corruption in some base images using docker for mac with raw virtual drive.

**Steps to reproduce the issue:**
There is unfortunately no clearly identified step to reproduce the issue

**Describe the results you received:**
The corruption is visible when saving the image:

```
docker save openjdk:8-jdk-alpine -o /dev/null
Error response from daemon: file integrity checksum failed for "usr/lib/jvm/java-1.8-openjdk/lib/tools.jar"
```

as well as when running the image:

```
docker pull openjdk:8-jdk-alpine; docker run --rm -ti openjdk:8-jdk-alpine javac -help
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:c5c705b462abab858066d412b3f871865684d8f837571c98b68e78c505dc7549
Status: Image is up to date for openjdk:8-jdk-alpine
Error: Could not find or load main class com.sun.tools.javac.Main
```

**Describe the results you expected:**

```docker pull openjdk:8-jdk-alpine; docker run --rm -ti openjdk:8-jdk-alpine javac -help
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:c5c705b462abab858066d412b3f871865684d8f837571c98b68e78c505dc7549
Status: Image is up to date for openjdk:8-jdk-alpine
Usage: javac <options> <source files>
where possible options include:
  -g                         Generate all debugging info
  -g:none                    Generate no debugging info
  -g:{lines,vars,source}     Generate only some debugging info
  -nowarn                    Generate no warnings
  -verbose                   Output messages about what the compiler is doing
  -deprecation               Output source locations where deprecated APIs are used
  -classpath <path>          Specify where to find user class files and annotation processors
  -cp <path>                 Specify where to find user class files and annotation processors
  -sourcepath <path>         Specify where to find input source files
  -bootclasspath <path>      Override location of bootstrap class files
  -extdirs <dirs>            Override location of installed extensions
  -endorseddirs <dirs>       Override location of endorsed standards path
  -proc:{none,only}          Control whether annotation processing and/or compilation is done.
  -processor <class1>[,<class2>,<class3>...] Names of the annotation processors to run; bypasses default discovery process
  -processorpath <path>      Specify where to find annotation processors
  -parameters                Generate metadata for reflection on method parameters
  -d <directory>             Specify where to place generated class files
  -s <directory>             Specify where to place generated source files
  -h <directory>             Specify where to place generated native header files
  -implicit:{none,class}     Specify whether or not to generate class files for implicitly referenced files
  -encoding <encoding>       Specify character encoding used by source files
  -source <release>          Provide source compatibility with specified release
  -target <release>          Generate class files for specific VM version
  -profile <profile>         Check that API used is available in the specified profile
  -version                   Version information
  -help                      Print a synopsis of standard options
  -Akey[=value]              Options to pass to annotation processors
  -X                         Print a synopsis of nonstandard options
  -J<flag>                   Pass <flag> directly to the runtime system
  -Werror                    Terminate compilation if warnings occur
  @<filename>                Read options and filenames from file
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This specific image seems to have been somehow corrupted, without - yet? - the ability to understand how

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:05:58 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:13:12 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: WGMZ:MYN5:2BRJ:UEGK:XKYU:37RV:U6ZT:KWCK:SLOP:MINR:JMNU:ZYHG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-29T10:39:28.482351117Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jimjkelly** [comment]
So I had a developer on our team experience something similar.  Tests were failing in the container with errors similar to this:

```
tests/integration/annotator_test.py:4: in <module>
   from ultimate_parser.scripts import group
src/ultimate_parser/scripts/__init__.py:4: in <module>
   from . import annotator
src/ultimate_parser/scripts/annotator.py:3: in <module>
   from ultimate_parser.annotator import main
src/ultimate_parser/annotator/main.py:57: in <module>
   from . import utils
src/ultimate_parser/annotator/utils.py:5: in <module>
   from ..utils.address import getPostcode
src/ultimate_parser/utils/address.py:5: in <module>
   from nltk.util import ngrams
/usr/local/lib/python3.6/site-packages/nltk/__init__.py:128: in <module>
   from nltk.chunk import *
/usr/local/lib/python3.6/site-packages/nltk/chunk/__init__.py:157: in <module>
   from nltk.chunk.api import ChunkParserI
/usr/local/lib/python3.6/site-packages/nltk/chunk/api.py:13: in <module>
   from nltk.parse import ParserI
/usr/local/lib/python3.6/site-packages/nltk/parse/__init__.py:79: in <module>
   from nltk.parse.transitionparser import TransitionParser
/usr/local/lib/python3.6/site-packages/nltk/parse/transitionparser.py:22: in <module>
   from sklearn import svm
/usr/local/lib/python3.6/site-packages/sklearn/svm/__init__.py:13: in <module>
   from .classes import SVC, NuSVC, SVR, NuSVR, OneClassSVM, LinearSVC, \
/usr/local/lib/python3.6/site-packages/sklearn/svm/classes.py:6: in <module>
   from ..linear_model.base import LinearClassifierMixin, SparseCoefMixin, \
E   ValueError: source code string cannot contain null bytes
```

or sometimes building the container would fail in random places.  I was a bit baffled as the error was inside the container from an installed python package, not in our source code mounted as a volume.  This all built and ran fine for me, and and ran fine on CI.  I asked her to run `docker save` for me so I could get a look at it all on my machine, but she got an error running that,

```
Error response from daemon: file integrity checksum failed for “usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so”
```

And that eventually led me here - and on a hunch I had her roll back to an older Docker version and that seems to have resolved the issue, specifically she's now using `qcow2` instead of `raw`.

When she got the error she was running `17.12.0-ce-mac49 (21995)` on macOS `10.13.2 (17C88)`.  Having her roll back to `17.09.0-ce-mac35` and completely blow out her settings fixed everything.

A conjecture based on some observed patterns with her issue and seeing a couple other reports that may be similar - @tjamet - on this machine did you upgrade from a previous version of Docker for Mac and convert your installation to a raw one, or did you install this version new on the machine?  My dev installed hers new, and I feel like I've seen at least one other report that sounded similar to this somewhere (unfortunately I can't find it again now) that implied it was a new installation.  Certainly I am not having any issues running a raw image on 17.12, having upgraded from a previous version.  Not sure if that's baseless though.

**Comment by jdelStrother** [comment]
I believe I'm also seeing this corruption, manifesting as `error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libzmq.so.5: invalid ELF header` while trying to run ffprobe.  Upon further inspection, libzmq.so.5.1.1 is the correct size (564864 bytes), but contains nothing but zeros.

Rebuilding with `--no-cache` 'fixed' the issue.

docker info: 
```
Containers: 54
 Running: 11
 Paused: 0
 Stopped: 43
Images: 176
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: H7F7:UNWU:DOET:U6OG:ITRV:SYOO:MFTY:IB4G:X7WB:6KGX:V5PT:IIFP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 129
 Goroutines: 182
 System Time: 2018-02-09T13:41:52.466881636Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jimjkelly** [comment]
Further information - I'm now seeing something similar myself (macOS `10.13.3 (17D47)`, Docker for Mac `17.12.0-ce-mac49 (21995)`, using the raw image format).  When trying to push a 3GB image it will fail, with messages similar to:

```
file integrity checksum failed for "libpostal/src/address_parser_train-unicode_scripts.o"
```

The exact file can change from time to time.  I'll probably bounce back to the previous Docker version, but I'm happy to go back to this one to provide any troubleshooting information I can.

```
Containers: 13
 Running: 6
 Paused: 0
 Stopped: 7
Images: 128
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.787GiB
Name: linuxkit-025000000001
ID: RDTG:YG2H:BADN:JRAZ:Y54O:CVCA:4PTO:NNI6:LGTN:4VOI:KUON:AXY4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 83
 Goroutines: 118
 System Time: 2018-02-10T12:23:49.589454831Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by kriansa** [comment]
I'm also having the same issue. If it's any help, the particular layer that I'm trying to push has 9gb.

I see that there is a similarity with the following issues:
* https://github.com/moby/moby/issues/33991 (see comments after the ticket was closed)
* https://github.com/moby/moby/issues/35306
* https://github.com/kubernetes/kubernetes/issues/58588
* https://github.com/docker/for-mac/issues/2497

In all cases, people are trying to upload a reasonably large image to the registry using Docker for mac. It would be more helpful if we could centralize these discussions in the same issue.

**Comment by jdelStrother** [comment]
I've only been using Docker for local builds - no pushing - and having been seeing corruption in my local layer cache (https://github.com/docker/for-mac/issues/2542#issuecomment-364437804), for images around 1GB in size.

It's possible my issue is totally unrelated, but if not we can rule out the problem being due to issues in pushing over a network 🤷‍♂️

**Comment by jdelStrother** [comment]
If you are getting errors while pushing, I'd be curious to see if this shows anything interesting when run on your image:

```sh
docker run IMAGE_ID bash -c 'sudo find /usr /lib /etc -type f -size +100  \( -exec grep -q -P "[^\0]" {} \; -o -print \) | head'
```

It looks for files that consist entirely of null bytes, which is the type of corruption I'm seeing.  It's not very bulletproof - it only searches a handful of directories and relies on the installed version of grep supporting `-P`.

**Comment by glyph** [comment]
I wasn't seeing this issue.  Then I roughly doubled the size of our images by adding a few other stacks that we run as subprocesses to our base image, and I started seeing it pretty regularly, on a diversity of different computers.

The type of corruption that I'm seeing includes files full of completely random data and truncated files.  I'm not seeing "null bytes only".

**Comment by glyph** [comment]
Is there any easy way to switch back to a qcow2 image with a current version of docker for mac to try and narrow this down?  (I don't mind completely blowing away my disk image.)

**Comment by fcheung** [comment]
I've also seen this from images that I've just pulled from dockerhub, for example at the moment:

```
docker save -o test.tar ruby:2.5.0-stretch
Error response from daemon: file integrity checksum failed for "usr/lib/python2.7/lib-dynload/_codecs_cn.x86_64-linux-gnu.so"
```

So probably not directly related to pushing or building images. Removing the image & pulling it again solved the issue so it's probably nothing specific to this image (& I've seen the issue with other images previously).

I'd never encountered this pre 17.12 (unfortunately my upgrade to 17.12 coincided with my upgrade to High Sierra, so can't say which is responsible. I also blew away my existing qcow2 image at the same time).

**Comment by magoo** [comment]
Ran into this problem. Similar platform as mentioned above (OS X 10.13.3, MBP, Docker for Mac 17.12.0-ce-mac49 (21995))

Downgraded to 17.09 here and we're working again: https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17120-ce-mac46-2018-01-09-stable

**Comment by raphaeljoie** [comment]
Got the same issue. Retrying 5 times a >400Mo layer, always failed at 362Mo, then (on the last time) jump to 100% with "file integrity checksum failed" error


<img width="889" alt="screen shot 2018-03-05 at 09 57 40" src="https://user-images.githubusercontent.com/9681129/36967750-e4ccc8de-2060-11e8-8dfc-197915be6901.png">

@magoo's solution worked fine for me : uninstall Docker then install 17.09

**Comment by jimjkelly** [comment]
Kind of disappointing that they didn't mention it on the related issues - but based on the release notes it seems they've reverted to qwo2 in the latest version of Docker because of this issue, so should be able to keep using the latest now (of course you'll need to blow out your underlying image just as you would when going to 17.09.

**Comment by Giaco9** [comment]
At my company, we have the same issue pulling an image of 3GB. Is a Postgres image and sometimes the extract phase ends successfully but some of the tables are corrupted. As far as I know, docker has recognized the bug and has restored the old virtual drive _.qcow2_ as default but we would like to be able to use the _.raw_ format because is more lightweight. We tried to pull the image in a Linux pc and everything goes well.

Is there any news to understand when is this problem will be fixed? In order to be updated about the fix what should I do? Follow this issue or another one?

Thanks!

**Comment by jimjkelly** [comment]
Is this fixed?  I thought I saw that `qcow2` had been deprecated, so I'd hope so?

**Comment by davidwheeler123** [comment]
> Is this fixed? I thought I saw that qcow2 had been deprecated, so I'd hope so?
https://github.com/docker/for-mac/issues/2625 is closed, which I think is the same issue

**Comment by tjamet** [comment]
I confirm I did not encounter this problem another time since then. I will close this issue.
