### ISSUE TITLE
C1910544-340F-4516-A6A1-DAF3634C746F

### ISSUE THREAD

**Issue by lauborges** [docker/for-mac#2543]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

A diagnostic is a good start, but please provide a description of the issue you are encountering please. What is happening ?

**Comment by pgayvallet** [comment]
Closing, please reopen with proper description if issue still present.
