### ISSUE TITLE
Docker hangs on start

### ISSUE THREAD

**Issue by joaocc** [docker/for-mac#2548]
### Expected behavior
Docker start normally

### Actual behavior
Docker hangs on startup

### Information

Docker diagnostic ID:
D8B7470C-189A-40B0-B363-212D8B4772C3

```
Docker for Mac: version: 18.02.0-ce-rc1-mac50 (e1912a8c46ae6f60a85d277f7b8d210dc9670b28)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/D8B7470C-189A-40B0-B363-212D8B4772C3/20180201-201440.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
 Start Docker for mac

**Comment by akimd** [comment]
Was it the first time you ran Docker for Mac?  Is it after upgrade?  Have you tried a reset to factory?

**Comment by joaocc** [comment]
This is the 1st time I ran after the upgrade. I have not tried reset to factory. Will try that.

**Comment by joaocc** [comment]
Well, I am told there is a new version (...-mac51). Will try upgrading to that one first. thx

**Comment by joaocc** [comment]
Upgraded to -mac51. Hangs on start. Started reset factory defaults. Reset process hangs...

**Comment by joaocc** [comment]
Well, after killing a few docker processes as `/Applications/Docker.app/Contents/MacOS/com.docker.supervisor -watchdog fd:0 -max-restarts 0 -restart-seconds 300` the reset process happily communicated it had finished.
Starting docker again solved it.
So, everything is great now.
Sorry for not having more data. Thx

**Comment by pgayvallet** [comment]
We have a bug (fixed on master) that was causing the reset to factory to sometimes hang because some processes were not killed correctly.

**Comment by joaocc** [comment]
This is solved on my machine. Feel free to close the issue if a fix has been shipped. Thx
