### ISSUE TITLE
Setting an insecure registry on mac results in failure to restart

### ISSUE THREAD

**Issue by jasondenton** [docker/for-mac#2550]
### Expected behavior
After adding an insecure registry in the daemon tab of preference and pressing Apply & Restart, the docker daemon restarts without issue.

### Actual behavior
The docker daemon fails to restart, and prompts to Reset Factory defaults. Choosing to reset factory defaults results in a total hang of docker, requiring a Force Quit to kill the resulting modal dialog.

### Information
After choosing diagnois and feedback, the system gets stuck at "Diagnosing..." and never finished. A force quit is required.
### Steps to reproduce the behavior

  1. Open preferences.
  2. Choose daemon tab.
  3. Add an insecure registry.
  4. Apply & Restart.

**Comment by akimd** [comment]
Sorry about this.  The forthcoming Edge (*-mac51) release fixes several issues in this area.  Please reopen this issue if you can reproduce the issue with it.
