### ISSUE TITLE
Stalling and high memory usage during kubernetes start

### ISSUE THREAD

**Issue by ManoMarks** [docker/for-mac#2551]
### Expected behavior
Docker starts, and Kubernetes starts soon after.

### Actual behavior
Docker starts, Kubernetes stalls out and doesn't start. Memory usage for hyperkit shoots up to 1.7GB. Docker stalls and is unable to run diagnosis.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Unable to run

  - Docker for Mac version
Version 18.02.0-ce-rc1-mac50 (22256)

### Steps to reproduce the behavior

  1. Start Docker or reboot machine

**Comment by akimd** [comment]
Please, provide us with "Diagnose & report".

**Comment by ManoMarks** [comment]
Diagnose & Feedback is unable to run. Docker for Mac freezes up

**Comment by scwagner** [comment]
I am having the same issue as described, running on `-mac51` version.  I can open a separate issue if you'd rather, but here is the output of my "Diagnose & Feedback":

`Docker for Mac: version: 18.02.0-ce-rc2-mac51 (1179f458c5db5072781101144a8d7e017fcb568c)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/5E66006C-192A-4082-A238-ABD268E79637/20180202-114915.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
`

**Comment by scwagner** [comment]
Building on my previous comment, I have found the error message in the logs generated by the Diagnose & Feedback section:

```
error: context "docker-for-desktop-context" does not exist
Error in configuration: context was not found for specified context: docker-for-desktop-context
Error in configuration: context was not found for specified context: docker-for-desktop-context
Error in configuration: context was not found for specified context: docker-for-desktop-context
```

Sure enough, the context is named `docker-for-desktop`, not `docker-for-desktop-context`.  I don't remember editing the name of the context manually.

**Comment by pgayvallet** [comment]
@scwagner These errors are actually caused by the diagnostic tool that was using the old context name

**Comment by akimd** [comment]
The attached `docker-diagnose` fixes that issue.
Run as
```
./docker-diagnose --last 1d
```
[docker-diagnose.zip](https://github.com/docker/for-mac/files/1695522/docker-diagnose.zip)

**Comment by scwagner** [comment]
I was able to use the updated `docker-diagnose` and get the logs out.  I have one pod that is a `CrashLoopBackOff` state:

```kube-system   kube-controller-manager-docker-for-desktop   0/1       CrashLoopBackOff   37         3d```

Looking at the logs for the pod, I see that it has an x509 error: 

```E0205 18:32:10.892589       1 controllermanager.go:486] Error starting "resourcequota"
F0205 18:32:10.892647       1 controllermanager.go:155] error starting controllers: failed to discover resources: unable to retrieve the complete list of server APIs: compose.docker.com/v1beta1: an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"compose-api-ca\")'\nTrying to reach: 'https://10.103.54.17:443/apis/compose.docker.com/v1beta1'") has prevented the request from succeeding, compose.docker.com/v1beta2: an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"compose-api-ca\")'\nTrying to reach: 'https://10.103.54.17:443/apis/compose.docker.com/v1beta2'") has prevented the request from succeeding```

I have uploaded the logs and my unique ID is `5E66006C-192A-4082-A238-ABD268E79637`

Please let me know what additional information I can provide to assist with resolving the issue.  Thanks!

**Comment by ManoMarks** [comment]
I ran docker-diagnose. I've attached the file it created.
[20180205-110254.tar.gz](https://github.com/docker/for-mac/files/1696408/20180205-110254.tar.gz)

**Comment by scwagner** [comment]
For what it's worth, selecting the `Reset Kubernetes cluster` button in the `Reset` tab ended up fixing my issue - my Kubernetes is now marked as running with a green dot.

**Comment by ManoMarks** [comment]
I was not able to click Reset to Kubernetes Cluster, it was grayed out. But Remove All Data I was able to click and that did fix the issue. Obviously this isn't an ideal solution.

**Comment by wfrank2509** [comment]
`Remove all data` and `Reset Kubernetes cluster` were the only options for me to make it work.

**Comment by akimd** [comment]
Hi guys!

Usual demand: could you please give a try (and submit diagnostics) to the latest release?  Thanks in advance!
https://download.docker.com/mac/edge/23022/Docker.dmg

**Comment by jakirkham** [comment]
Have ran into this problem a few times. None of the solutions proposed work for me. Have to select `Reset to factory defaults` to get things working again.
