### ISSUE TITLE
failed to start already exited containers.

### ISSUE THREAD

**Issue by airforce-captain** [docker/for-mac#2552]
### Information

when I try start already exited containers,  get some error:

```
$ docker ps -a --filter "name=mariadb"
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                    NAMES
83a7208d6b68        mariadb             "docker-entrypoint.s…"   2 days ago          Exited (255) 2 hours ago   0.0.0.0:3306->3306/tcp   mariadb


$docker start mariadb
Error response from daemon: container "83a7208d6b68d3d97be501b47d6a4bb28245b086f25eda819dec93a8d40320a3": already exists
Error: failed to start containers: mariadb
```

Diagnostic ID:  1DD8F9E2-418D-4726-9F00-DE6C68876A7C
Docker for Mac: version: 18.02.0-ce-rc1-mac50 (e1912a8c46ae6f60a85d277f7b8d210dc9670b28)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/1DD8F9E2-418D-4726-9F00-DE6C68876A7C/20180202-143741.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1.  run docker for mac ,  start one container  ,  reboot MacOS machine .
```
$docker run -d --name mariadb -p 3306:3306 -v ~/mysql:/var/lib/mysql  -e MYSQL_ROOT_PASSWORD='xxx' mariadb

$sleep 30
$sudo reboot
```
  2.  start MacOS machine ,  run docker for mac ,  start one container , and get start error.
```
$docker start mariadb
Error response from daemon: container "83a7208d6b68d3d97be501b47d6a4bb28245b086f25eda819dec93a8d40320a3": already exists
Error: failed to start containers: mariadb
```

**Comment by tillgschwend** [comment]
I have the same issue

**Comment by cmoiccool** [comment]
Same problem here with Version 18.02.0-ce-rc1-mac50 (22256)
Each time my macbook runs out of battery i have this error message when trying to start container, it was not happening in earlier version of Docker for mac.

**Comment by akimd** [comment]
I'm not sure I understand what you expected.  You created a container and this container is still there when you come back (as `docker ps -a` would show).  The reboots of the Mac (or simply quitting and relaunching Docker for Mac) does not remove any image or container.  You can remove the container when you no longer want it: `docker rm mariadb`.

**Comment by fbcouch** [comment]
(This is also happening to for me on  Docker version 18.02.0-ce-rc1, build 5e1d90a for mac)

The issue is that we often need to restart the same container - for example, a database container that isn't using a separate data volume

**Comment by matthewberryman** [comment]
@akimd yes the container is still there, but it cannot be restarted using `docker start` , [expected behaviour from the documentation](https://docs.docker.com/engine/reference/commandline/container_start/), as outlined above. 

Also happening for me (Version 18.02.0-ce-rc2-mac51 (22446) on macOS 10.13.3)

**Comment by khs1994** [comment]
Me,too.Docker for Windows and Mac have same issue.

**Comment by jerry153fish** [comment]
Me too
```
Docker Version 18.02.0-ce-rc2-mac51 (22446)
MacOS High Sierra Version: 10.13.3 (17D47)
```

**Comment by cnjack** [comment]
me too 
```
Docker Version 18.02.0-ce-rc2-mac51 (22446)
```

**Comment by pgayvallet** [comment]
Easy to reproduce : 

`docker run -d --name foo alpine sleep 30000`

then exit/restart docker4mac

```
docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                            PORTS               NAMES
849b146eedea        alpine                   "sleep 30000"            2 minutes ago       Exited (255) About a minute ago                       foo
```

```
docker start foo
Error response from daemon: container "849b146eedeaa2aedd21a4b036f86282b2d8217dec64801d388d70dc442d7989": already exists
Error: failed to start containers: foo
```

**Comment by pgayvallet** [comment]
Original issue on the for-linux repo : https://github.com/docker/for-linux/issues/211#issuecomment-363192969

**Comment by cpuguy83** [comment]
moby/moby#36249 fixes it.

**Comment by khs1994** [comment]
v18.03-rc1 work

**Comment by akimd** [comment]
I guess we can close now.  Thanks for checking.

**Comment by poldim** [comment]
Is there any workaround that allows you to not remove the container but still get it started in v18.02?

**Comment by sunilthemaster** [comment]
Am able to replicate the issue in 18.03 also.

**Comment by keyapi** [comment]
got this issue too. 
Restart Docker Desktop as Administrator solved my problem.

**Comment by ddohcim** [comment]
> got this issue too.
> Restart Docker Desktop as Administrator solved my problem.

how did you restarted it as administartor?
