### ISSUE TITLE
Upgrading to Kubernetes 1.9.2 fails

### ISSUE THREAD

**Issue by dgageot** [docker/for-mac#2553]
### Expected behavior

I install mac-51 on top of the previous version and K8s should be updated and up and running.

### Actual behavior

After the update, Docker is running (green dot), Kubernetes is stopped (red dot).
Plus, I'm unable to reset K8s to its default. It always fails stopping k8s (which the UI says is stopped).
Had to reset the whole thing to factory defaults.

**Comment by pgayvallet** [comment]
Hello @dgageot, and thanks for the issue. Maybe, as an experienced developer, you had the idea to perform diagnostic after the failed upgrade to help us find the root cause ?

**Comment by dgageot** [comment]
:trollface: No, I forgot to do so. I'll try to reproduce tomorrow and keep you posted. Can you give me a url for the previous version?

**Comment by pgayvallet** [comment]
sure, https://download.docker.com/mac/edge/22256/Docker.dmg (18.02.0-ce-rc1-mac50)

**Comment by pgayvallet** [comment]
Also if you're able to reproduce, please use this to diagnose : https://github.com/docker/for-mac/files/1695522/docker-diagnose.zip  ( using `docker-diagnose --last 1d --upload` )

**Comment by dgageot** [comment]
Sorry, I tried but couldn't reproduce it
