### ISSUE TITLE
On the new welcome whale, unable to log in with return key

### ISSUE THREAD

**Issue by dgageot** [docker/for-mac#2554]
### Expected behavior

On the new Welcome whale, I type my `Docker ID` and `Password` and hit return and I logged in.

### Actual behavior

On the new Welcome whale, I type my `Docker ID` and `Password` and I have to click on `Log In` button.

<img width="402" alt="screen shot 2018-02-02 at 5 07 29 pm" src="https://user-images.githubusercontent.com/153495/35761289-c47df590-083b-11e8-9505-b2bd2e8b8c52.png">

**Comment by aduermael** [comment]
Thank you @dgageot !
I fixed the issue and a few other details on that popover.
