### ISSUE TITLE
MacMini 2010 - unable to run docker

### ISSUE THREAD

**Issue by rnagineni** [docker/for-mac#2556]
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/0D90F311-59FC-47CA-BFBA-5DB2922F50F6/20180203-102448.tar.gz
failure: sysctl -a reports no hypervisor support
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/ramananagineni/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/ramananagineni/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/ramananagineni/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/ramananagineni/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ramananagineni/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

**Comment by rnagineni** [comment]
I can see that Virtulization is OK but still unable to run docker.

**Comment by PixellUp** [comment]
Same issue - 4CEBC6BA-2507-44BD-9B61-1A9053B1EDCF. I'm running macOS: version 10.13 (build: 17A405). This issue happen when I updated docker for mac to `17.12.0-ce-mac49` and restarted the mac.

**Comment by pgayvallet** [comment]
@rnagineni It's seems we got an issue detecting if the cpu is compatible as application startup, but the

```
[ERROR] virtualization kern.hv_support
sysctl -a reports no hypervisor support
```

in the diagnostic seems to show that your hardware is not compatible, which seems the case from a 2010 mini.

**Comment by rnagineni** [comment]
that's what  I thought too but the following line confusing me. Anyway closing this 
[OK] virtualization VT-X

**Comment by pgayvallet** [comment]
@rnagineni just to dig a little on our startup detection, can you confirm or infirm that you made the diagnostic from this error popin that appeared at application startup ? 
 
<img width="607" alt="capture d ecran 2018-02-05 a 17 25 02" src="https://user-images.githubusercontent.com/1532934/35815747-87f6abc0-0a99-11e8-84c8-9389bc0e56d1.png">

**Comment by rnagineni** [comment]
@pgayvallet 
I got same error message first, and in the Diagnose & Feedback message was pasted.

**Comment by pgayvallet** [comment]
I'm sorry I'm not sure to understand your answer. Did you see the error message about incompatible cpu at startup or not ?

**Comment by rnagineni** [comment]
yes

**Comment by pgayvallet** [comment]
Ok, thanks you for your answers
