### ISSUE TITLE
Won't even start

### ISSUE THREAD

**Issue by jeregrine** [docker/for-mac#256]
### Expected behavior
Docker runs

### Actual behavior

Instantly crashes. 

### Information

Diagnostic ID: 90077C4F-8F63-488D-A80F-74313C2EBB1A
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.12 (Build 16A286a)

### Steps to reproduce

1. Open Docker Beta
2. Crashes

I don't know how it got into this state to be honest. Had a command line tools update, rebooted my computer. Wouldn't work after.

**Comment by glynjackson** [comment]
Could be related to https://github.com/docker/for-mac/issues/64

**Comment by dsheets** [comment]
There are known issues on macOS Sierra Beta. See #64.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
