### ISSUE TITLE
Diagnose new issues

### ISSUE THREAD

**Issue by Sarahkh83** [docker/for-mac#2561]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing. Please reopen another ticket with proper title and description if necessary.
