### ISSUE TITLE
Docker asks endlessly for admin password, will not proceed with setup

### ISSUE THREAD

**Issue by tla** [docker/for-mac#2562]
### Expected behavior

Docker should complete installation and start up.

### Actual behavior
Docker asks endlessly for an administrator password, and never starts. If I exit, and try starting Docker from the command line with sudo, I get a "Fatal Error: Failed to register new version" and the following diagnostic. If I choose "reset to factory defaults" and restart, it asks repeatedly for an administrator password again, and there is no way to produce a diagnostic.

### Information

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/51F8A3EE-8A08-4BE7-A8F2-ECE3E304EBE8/20180204-203917.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /var/root/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/var/root/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /var/root/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         cannot find docker
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /var/root/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /var/root/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started
```
### Steps to reproduce the behavior

  1. Click on the Docker app
  2. Input admin user/password when prompted

**Comment by akimd** [comment]
Could you check that you do have a `/var/tmp` directory?

**Comment by tla** [comment]
Yep - 

```
tla$ ls -l /var/tmp
total 0
srw-rw-rw-  1 root  daemon  0 Feb  4 20:35 com.barebones.authd.socket
srw-r--r--  1 tla   wheel   0 Feb  4 20:35 filesystemui.socket```

**Comment by akimd** [comment]
Docker needs to grant one of its components, vmnetd, special rights, for instance to be able to create a socket in `/var/tmp`.  Your problem is that the procedure fails.

Could you:
1. uninstall docker
2. reinstall it
3. run the diagnostic *and upload the results*, we really need them.

Thanks!

**Comment by tla** [comment]
OK done - ID is 51F8A3EE-8A08-4BE7-A8F2-ECE3E304EBE8 .

**Comment by ClaudioAlbertin** [comment]
@tla This may be a long shot, but I had the same issue as you and accidentally resolved it as follows:
1. Remove Docker for Mac, including deleting `~/.docker`
2. Install Docker for Mac
3. Start Docker for Mac, again being prompted for privileged access
4. Enter password and confirm, seemingly to no avail as the privileged access modal won't close
5. Click exit
6. Delete `~/.docker` again, which at this point only contained `daemon.json` for me
7. Start Docker for Mac, which now works normally (Ironically this seems to recreate the same `daemon.json`)

I see no logical reason why this would fix the problem, but it did the trick for me.

**Comment by tla** [comment]
@ClaudioAlbertin No such luck when I tried that, but thanks for the tip - hopefully it will help someone else.

**Comment by akimd** [comment]
I am closing this issue because forthcoming 18.03 has fixes in this area.  Please open a new issue if 18.03 still does not help.
