### ISSUE TITLE
vpnkit takes over port 80

### ISSUE THREAD

**Issue by rymcol** [docker/for-mac#2563]
### Expected behavior
To be able to use port 80 on my localhost

### Actual behavior
vpnkit takes over port 80 on Docker startup, and you can no longer bind to port 80

### Information

Docker for Mac: version: 18.02.0-ce-rc2-mac51 (1179f458c5db5072781101144a8d7e017fcb568c)
macOS: version 10.13.4 (build: 17E139j)
logs: /tmp/1CD2EB82-8841-48C3-B115-BAA8321C51CD/20180204-175645.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Install Docker for Mac: version: 18.02.0-ce-rc2-mac51
  2. Start Docker
  3. run `lsof -n -i:80 | grep LISTEN` to see if vpnkit has overtaken port 80

**Comment by pgayvallet** [comment]
Probably because you started a container or deployed a service on kube that's bound to port 80

what does `docker ps` and `kubectl get services --all-namespaces` tells you ?
