### ISSUE TITLE
Cannot stop docker containers after Mac restart

### ISSUE THREAD

**Issue by PeterLappo** [docker/for-mac#2564]
### Expected behaviour
After a system restart expect to delete any running containers / pods in Docker

### Actual behavior 
After a system restart delete any running pods in Docker

### Information

Docker for Mac: version: 18.02.0-ce-rc2-mac51 (1179f458c5db5072781101144a8d7e017fcb568c)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/14DBF6F7-32DE-4921-8318-92D2AC2B38BB/20180204-230837.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior
Docker for mac
OS performed a software update and the machine restarted
Since the kubernetes restart old pods cannot be deleted 
Upgraded to latest version of docker and Kubernetes failed to start
Cannot stop docker containers after Mac restart, they just restart, including the system ones
Cannot access UI

**Comment by pgayvallet** [comment]
Which containers exactly are you trying to kill ? Containers created via `docker run` ? via stack deploy ? kube internals pod's containers ?

**Comment by PeterLappo** [comment]
The containers were my own in a pod, a pypi server and mysql. The kept reappearing even when "properly" deleted with kubectl.

Since then have got it working. Re-installed which didn't help much and Kubernetes failed to start but now after a reset to factory defaults and re-enabling Kubernetes it now works.
