### ISSUE TITLE
File corruption using ADD or docker cp

### ISSUE THREAD

**Issue by dgay-appd** [docker/for-mac#2567]
### Expected behavior

MD5 checksums would be the same

### Actual behavior

File is corrupted/MD5 checksum is off

### Information

The file in question is a large shell script (2.4GB) with embedded binary compressed data.  Using Dockerfile ADD command or `docker cp` of the file to container, then running `md5sum` results in different checksums than source.  Also errors consistent with corruption when trying to decompress embedded tar.  File size appears exactly the same.

Accessing file via volume mount in container doesn't have these problems.  Checksums and decompression work.

### Steps to reproduce the behavior

  1. checksum on Mac
  2. `docker cp` file to container
3. attach to container
4. checksum on container doesn't match

**Comment by tristanpemble** [comment]
I think this is some kind of issue with locales, and I've only started to notice it recently. I see it mainly when copying files between build stages.

Are the files filed with gibberish? [Try this at the beginning of your Dockerfile](http://jaredmarkell.com/docker-and-locales/), does it fix it?

**Comment by akimd** [comment]
@dgay-appd Hi!

Could you upload diagnostics and report their ID here?  We don't know what version of Docker for Mac you ran, whether raw or qcow format, etc.

Thanks!

**Comment by bskrtich** [comment]
I am having this same issue. I have a 3.4gb zip file that does not always copy over to the container correctly. The sha1 that I calculate on my mac vs in the container are different. 

Here is my diagnostics id 1C506BD3-7810-4842-A5DA-30EB8944A2EC

**Comment by akimd** [comment]
Your disk image is in raw format, which, unfortunately, relies on new APFS features that are not working properly.  So until APFS is fixed, we recommend updating to a recent Docker for Mac, and start from scratch, so that your disk image is in qcow2 format.

```
  "diskPath" : "/Users/skrbr01/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.raw",
```

**Comment by bskrtich** [comment]
I went in to Reset and "Remove All Data" and that seemed to recreate my disk image in the correct format and fixed my issues. Thank you for your help!

**Comment by akimd** [comment]
Thanks for the report.
