### ISSUE TITLE
Windows 10 (host), VirtualBox 5.2.6, and Mac OS 10.13.3 (guest) with i76600U virtualization error

### ISSUE THREAD

**Issue by brehma100** [docker/for-mac#2569]
### Expected behavior
Docker should startup and run

### Actual behavior
Docker errors out

###### System Information

- Lenovo T460s
- Dual core
- i7-6600U
- Virtualbox Environment (5.2.6 r120293)
- Guest Additions (5.2.6-120293)
- Windows 10 (host, 64-bit)
- Mac OS (High Sierra 10.13.3, 64-bit)

I have verified this processor does have VT-x and VT-d capabilities

###### Diagnostic Log
*Full output of the diagnostics from "Diagnose & Feedback" in the menu*
[DockerDiagnosticID.txt](https://github.com/docker/for-mac/files/1697072/DockerDiagnosticID.txt)

### Steps to reproduce the behavior

  1. Install Docker Stable from [https://docs.docker.com/docker-for-mac/docker-toolbox/]
  2. Start the Docker from the 'Applications' folder

**Comment by pgayvallet** [comment]
Hello,

```
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support

```

in the diag means that your hardware (CPU) is not compatible to launch docker for mac / docker for win

On mac, you should have be getting this popin at application startup, which is pretty self explaining :

<img width="607" alt="capture d ecran 2018-02-05 a 17 25 02" src="https://user-images.githubusercontent.com/1532934/35849483-03046248-0b22-11e8-958f-499bc71e38b1.png">

Can you confirm you actually got this error popin at startup ?

**Comment by brehma100** [comment]
Yes, I do get the error at startup. I think I may have forgot to mention the OSX is a guest running via Box on the Windows 10 Host. I understand the error is clearly stated, according to the Intel site, the chip specs say the virtualization requirements are supported.

**Comment by akimd** [comment]
@brehma100 Yes, but it appears that the features exposed by your Virtual Box does not include this feature.  Maybe you there are settings you should look for, but as far as Docker is concerned, this "box" cannot run it.

**Comment by brehma100** [comment]
I hadn't thought of VBox blocking it for some reason. I'll check that out, thanks.
