### ISSUE TITLE
kubernetes openid auth

### ISSUE THREAD

**Issue by rucas** [docker/for-mac#2570]
### Expected behavior

I know in minikube you can start the [kube-apiserver with additional configs](https://jtway.co/minikube-1-7-0-with-openid-and-rbac-2d3327414fff). Is there anyway to do this currently on docker-for-mac?

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Unfortunately, we currently do not provide any way to customise the cluster configuration or version. If you need that kind of features, Minikube is probably still the way to go for now.

**Comment by danielfbm** [comment]
+1 for this feature. 
minikube can still be used, but would really appreciate if this could be somehow configured using the UI or even a CLI.
