### ISSUE TITLE
Docker Fatal Error on start

### ISSUE THREAD

**Issue by PixellUp** [docker/for-mac#2571]
### Expected behavior
Docker start normally

### Actual behavior
Docker hangs/crash on startup
### Information

Docker diagnostic ID:
4CEBC6BA-2507-44BD-9B61-1A9053B1EDCF

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13 (build: 17A405)
logs: /tmp/4CEBC6BA-2507-44BD-9B61-1A9053B1EDCF/20180206-120302.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/teo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/teo/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/teo/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/teo/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```
Video preview : https://youtu.be/K7RAG6SO1N0
### Steps to reproduce the behavior

Start Docker for mac

**Comment by pgayvallet** [comment]
Was it working at some point ? We have an issue on your d4m version where the app processes do not stop correctly, which block from restarting the app.

Can you, after having the error and clicking exit on the error popup, exec the following command : `ps aux | grep com.docker` to see what is still running ?

**Comment by PixellUp** [comment]
Running previews version `v17.09.1` everything was fine. After updating to `v17.12.0` was working fine initially. After about a week off mac, starting the mac I was greeted with this popup error. 


Result from executing `ps aux | grep com.docker` after clicking on exit popup
```

ps aux | grep com.docker
teo                552   0.0  0.0  4276968    908 s000  S+    5:23PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn com.docker
root                75   0.0  0.1  4287532   4484   ??  Ss    5:21PM   0:00.01 /Library/PrivilegedHelperTools/com.docker.vmnetd
```

**Comment by pgayvallet** [comment]
Got this in the system logs : 

```
2018-02-06 12:02:54.757819+0200  localhost com.docker.driver.amd64-linux[1569]: vmx_init: processor not supported by Hypervisor.framework
2018-02-06 12:02:54.757859+0200  localhost com.docker.driver.amd64-linux[1569]: Unable to create VM (-85377018)
```

which ultimately leads to 

```
18-02-06 12:02:55.249881+0200  localhost com.docker.driver.amd64-linux[1569]: Hypervisor subprocess has shutdown
2018-02-06 12:02:55.250336+0200  localhost Docker[1549]: [Docker.] DockerState: stopped
2018-02-06 12:02:55.253066+0200  localhost com.docker.supervisor[1566]: Reap com.docker.driver.amd64-linux (pid 1569): exit status 0
```

The important info there is `vmx_init: processor not supported by Hypervisor.framework` very strange as `kern.hv_support` check seems good and you're saying it was working at some point.

Did you do anything system-related between the working and broken state (os update or other ?)

**Comment by pgayvallet** [comment]
@PixellUp is this a iMac15,1 as stated in hardware desc, or is it another model / hackintosh ?

**Comment by pgayvallet** [comment]
VM creation (`hv_vm_create` call, https://developer.apple.com/documentation/hypervisor/1441424-hv_vm_create ) is failing with a `HV_NO_DEVICE` code, indicating (from the apple doc, https://developer.apple.com/documentation/hypervisor/hv_no_device) : 

> Indicates that the operation was unsuccessful due to no Hypervisor [...] being available.

no idea what may be causing this on your system

**Comment by PixellUp** [comment]
Somehow Intel VT was turned off, either from silent Apple security updated (i doubt ) or just random issue happened while I was off for about week. 
Following Apple article, https://support.apple.com/en-us/HT204063 and plugin of the iMac (power cord) for about 30 minutes fixes the issue.

**Comment by akimd** [comment]
Hi @PixellUp!

Could you please run the following experiment?  We are trying to catch this kind of failures earlier.

1. Please, disable virtualization again.
2. Download this version of [Docker for Mac](https://download-stage.docker.com/mac/pr/23315/Docker.dmg), and check that it correctly reports that Virtualization is disabled.
3. Download this version of [docker-diagnose](https://github.com/docker/for-mac/files/1811081/docker-diagnose.zip) and run it as `./docker-diagnose -n -l 1m`, and please paste here what it displayed (it should also report that Virtualisation is disabled).
4. Restore virtualization :-)

Thanks in advance!
