### ISSUE TITLE
Docker fail to start after having added a repository into my preferences.

### ISSUE THREAD

**Issue by boutinjerome** [docker/for-mac#2572]
### Expected behavior
Docker should start
### Actual behavior
Docker fail to start
### Information
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/EDFB194D-F0AA-4FC1-8D67-29C5FAC40B9C/20180206-060759.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jboutin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jboutin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jboutin/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

Diagnostic ID: EDFB194D-F0AA-4FC1-8D67-29C5FAC40B9C
### Steps to reproduce the behavior

  1. start docker
  2. log an incident as it fail to start.

**Comment by pgayvallet** [comment]
Could you give me your docker and daemon configs ? ( `cat ~/.docker/config.json` & `cat ~/.docker/daemon.json`)

**Comment by boutinjerome** [comment]
cat ~/.docker/config.json
{
  "auths" : {

  }
}

{
  "debug" : true,
  "experimental" : true
}

**Comment by dparkerfmts** [comment]
I believe I was having the same issue. When trying to add an insecure repository via the GUI, after I click `Apply & Restart` I get a message saying the Docker daemon failed to start and I have to reset Docker to defaults.

Solution: I quit out of Docker and edited my `~/.docker/daemon.json` file directly as explained here: https://docs.docker.com/registry/insecure/
Then start docker and it was OK.

**Comment by pgayvallet** [comment]
Can't seems to reproduce that.

After adding insecure registry from the UI, daemon config file seems to be correctly updated.

```
{
  "debug" : true,
  "insecure-registries" : [
    "localhost:5000"
  ],
  "experimental" : true
}

```

@dparkerfmts are you able to get to a state where the daemon failed to start, and tells me what's inside the daemon.json file ? (`cat ~/.docker/daemon.json`)

@boutinjerome would be wonderful if you could actually explain your whole reproduction scenario. As you are stating that you went to error state after adding a repo, I strongly doubt that
```
start docker
log an incident as it fail to start.
```
was the whole thing. Also your daemon.json appears to be valid. I guess you reseted. Could you provide the content of the file AFTER going to error state. Thanks.

**Comment by pgayvallet** [comment]
Possible duplicate of https://github.com/docker/for-mac/issues/2537

**Comment by boutinjerome** [comment]
Thanks, I use this format and now my docker installation is working fine.
