### ISSUE TITLE
Error after upgrade to Mac Sierra Beta 5

### ISSUE THREAD

**Issue by jimzucker** [docker/for-mac#258]
### Steps to reproduce

1. I had beta 21 installed no issues
2. Installed the Sierra beta 4 last week - still OK
3. Upgraded to Beta 5 today, now I errors.  
4. Tried upgrading to beta 22 but now I get this error.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: B22742E9-6EA0-4C87-987D-724DB69E9238
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     menubar
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/jaz/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/jaz/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
Beta 25 should have solved most of the Sierra bugs: https://download.docker.com/mac/beta/Docker.dmg 

Stable will be released soon.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
