### ISSUE TITLE
Using LinuxKit generated ISO in Docker For Mac

### ISSUE THREAD

**Issue by thomasantony** [docker/for-mac#2580]
### Information

I am trying to compile a new linux image using linuxkit and use it with Docker for Mac. The goal is to eventually enable some kernel flags that are currently disabled in the kernel used by D4M. I am not sure if the strategy described here is the valid one. 

### Steps to reproduce the behavior

1. Install `linuxkit` and clone [https://github.com/linuxkit/linuxkit](https://github.com/linuxkit/linuxkit)
2. Create new docker-for-mac ISO using `linuxkit build -format iso-efi examples/docker-for-mac.yml`.
3. Copy `docker-for-mac-efi.iso` to `/Applications/Docker.app/Contents/Resources/linuxkit/docker-for-mac.iso`
4. Start Docker.app

### Expected behavior
Docker starts up with the new image (possibly with new kernel flags enabled if I had changed those).

### Actual behavior
Docker doesn't start up. The menu bar icon stays in its "loading" state.

Possibly related to #1561

**Comment by pgayvallet** [comment]
The steps seems actually correct in the idea.

I'm afraid the example file from linuxkit repository is missing some (privates) parts we are using in our D4M iso though.

**Comment by pgayvallet** [comment]
The D4M iso have private bits since the beginning, so this won't be working with older version either.

What flags do you need to enable and what for ? We are based on the linuxkit kernel (https://github.com/linuxkit/linuxkit). You could PR there.

**Comment by thomasantony** [comment]
I wanted to enable SocketCAN. I finally got it to work using `docker-machine` and building my own boot2docker ISO with the flags enabled.

**Comment by thomasantony** [comment]
@arashd  You can probably use `docker-machine` and boot2docker to incorporate whatever changes you want into the linux kernel used by Docker. I wrote an article about this:

https://medium.com/@tantony/using-virtualcan-inside-docker-on-macos-cfa10f7e75d6

You can do something similar and add the binary you want rather than changing a kernel config flag.

**Comment by MaxHorstmann** [comment]
@arashd 

> I'm trying to do something similar: including a criu binary into the d4m vm to make the checkpoint/restore feature work on a mac. 

did you find a way to achieve this? Trying to figure out the same thing.

**Comment by arashd** [comment]
Unfortunately not. We abandoned the project we needed this for, but I'll update you if I do come back to it.
