### ISSUE TITLE
Resetting Factory settings uninstalls existing kubectl

### ISSUE THREAD

**Issue by fosrias** [docker/for-mac#2581]
### Expected behavior
I have installed `kubectl` independent of docker k8s. I reset factory settings and `kubectl` is still available.

### Actual behavior
Restetting factory settings  and not turning on k8s again (and I presume turning off k8s, though did not try) uninstalls `kubectl` completely. Even when it was independently installed (months before using Docker k8s).

```
$ which kubectl                                                                                                                                                                              
kubectl not found
```
### Information

ID: DBE70B17-5C2C-4586-B6AB-AA33502479B1

[20180207-132916.tar.gz](https://github.com/docker/for-mac/files/1704835/20180207-132916.tar.gz)

### Steps to reproduce the behavior

  1. Install kubectl independently.
  2. Use kubectl happily (even after installing docker k8s after using kubectl).
  3. Reset factory settings and don't turn on kubernetes.
  4. Not use kubectl happily. It is gone.

**Comment by pgayvallet** [comment]
How what the initial `kubectl` installed ? Brew I guess ?

**Comment by fosrias** [comment]
Was months ago. Can't remember.

**Comment by akimd** [comment]
I am closing this ticket because we have fixed issues in Docker for Mac about this.  This will show in the forthcoming Stable and Edge releases.  Please, open a new issue if the problem happens again with them.

Thanks for the report!
