### ISSUE TITLE
HyperKit high cpu consumption 

### ISSUE THREAD

**Issue by bypotatoes** [docker/for-mac#2582]
### Expected behavior
To have cpu level pretty same for dockerized app and not

### Actual behavior
When rails app handles request level of cpu increases to 150-280% depends on how heavy page is, after few seconds it returns to normal level, instead of #2503 and similar where cpu level is permanently high

### Information
```
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/89DC5C0F-2ED3-4106-AEFB-5D79EC2AC30B/20180208-023454.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
 
### Steps to reproduce the behavior

  1. create rails application with compose, e.g follow [official guide](https://docs.docker.com/compose/rails/)
  2. check effect for welcome page in new rails up(cpu will up to 50% what is pretty high for super simple page)
  3. to make effect more noticeable add db volume and fill db with data
  4. make request to page that request data from db

**Comment by javajosh** [comment]
I'm getting the same thing, and it looks like this has been a problem for a long time, all the way back to #82 or so. `docker stats` show that the containers themselves are using very little CPU, which implies that the load is in the parent `hyperkit` process itself. Personally, I've attempted to give more CPU cores, more RAM, and limit the potential bind mount options but it's still using a lot of CPU, and my fan is spinning. 

If we can't fix this we can't have devs running docker. We will have to switch away from using docker for development and just use manually run our processes (which does not, of course, have this issue).

**Comment by gamort** [comment]
I have had good luck simply brute-forcing around this issue.   I installed cputhrottle http://www.willnolan.com/cputhrottle/cputhrottle.html and run a bash script whenever I restart docker to locate the hyperkit process pid and throttle it to 60%[on a 4 core system].

I have not had any issues with files being synced and performance is now decent.

I lack the time and energy to dig into yet another new framework to figure out why this is happening, cputhrottle made all our dev systems usable and I moved on.

My guess is that the stupid thing is using a huge number of file watches,  by default it will scan every single hard drive and when a lot of changes happen at once, it will happily grab every single cpu just to determine that "nope, none of those files are of interest to me"

**Comment by artyfarty** [comment]
It's related to heavy I/O of rails app. If you mount the whole app directory inside a container, it will spend a considerable time on sync. I've mounted rails temp/cache directories to tmpfs in compose file and also heavily use cached or delegated mount modes to bring app speed back on earth levels.

**Comment by barat** [comment]
@artyfarty does even :delegated work? I think, that docker team hasn't made an implementation yet so :delegated is an alias for :cached right now ...

**Comment by artyfarty** [comment]
@barat i dunno. I believe in it :(

**Comment by artyfarty** [comment]
docker-sync has it's own reliability issues on large projects.

**Comment by axsuul** [comment]
@artyfarty Could you possibly share your `docker-compose.yml` for your Rails app? ❤️

**Comment by artyfarty** [comment]
@axsuul turned put tmpfs is unreliable crap too. In the end a've gone to nfs.
here you go:
https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc

**Comment by ruslyrossi47** [comment]
When I start my **Docker Desktop community Version 2.0.0.0-mac78 (28905)**, I can see this process  _com.docker.hyperkit_ will consume more than 100% of CPU, so I solve this by kill all my containers and start again one by one.

**Comment by brandonbai** [comment]
When I run jenkins with docker, the hyperkit takes up more than 300% of the cpu. But when I run other services(redis, mysql ...), everything works fine.

-|version
-|-
os|macOS Mojave 10.14.2
docker|18.09.0
jenkins|latest

**Comment by davidkrcil** [comment]
After 5 months I have finally resolved this pain for me. I have used http://www.willnolan.com/cputhrottle/cputhrottle.html and run command: sudo ./cputhrottle 4634 50
My Mac is again my frined with no running fan.

**Comment by michaelbutler** [comment]
My docker for mac (version 18.09.1 Edge) takes a constant 50-80% CPU _even when all containers are deleted and docker ps shows nothing running_

**Comment by alexbaumgertner** [comment]
@michaelbutler try to run
```
docker volume ls
```
Maybe some volumes still exists and doing sync.

**Comment by Jvlythical** [comment]
I was able to solve it by raising the available memory for the Docker daemon from the default 2GB. If your machine has more memory available, you can use 'docker info' to see how much memory is available to the daemon. You can change the available memory in Preferences > Advanced.

**Comment by axsuul** [comment]
I've had great success with delegated volumes 👍My fan still comes on but it's at least 10x better

**Comment by wuestkamp** [comment]
@michaelbutler do you have the local Kubernetes cluster enabled via Docker for Mac? Once I enable it I have constant CPU of 50%

**Comment by JamesonNetworks** [comment]
There is another issue tracking at https://github.com/docker/for-mac/issues/1759, they seem related

**Comment by r9software** [comment]
I have the same issue docker takes over 140% in a laravel API with client frontend running in the same container, I read somewhere that if you increase the number of files that mac can open at the same time to millions then it should decrease the problem and it happened that way, but I can't find the command anymore, and I don't believe that is the right way to do it, does anyone has a better way of dealing with this?

**Comment by alexbaumgertner** [comment]
@r9software try this
https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/

**Comment by r9software** [comment]
hey @alexbaumgertner  I tried it but it is not working on Mojave, the error is invalid property list, not sure what is wrong, I copy pasted the content from the site

**Comment by maxfenton** [comment]
Wayback Machine link for that blog post above: https://web.archive.org/web/20161223195250/https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/
