### ISSUE TITLE
latest edge update sees docker continually starting

### ISSUE THREAD

**Issue by efx** [docker/for-mac#2583]
### Expected behavior
To restart and run succesfully
### Actual behavior
Docker icon shows it restarting
### Information
Diagnostic ID: 6B3BBEAC-A047-4E5B-B24F-CC2C3624397E
```
Docker for Mac: version: 18.02.0-ce-rc2-mac51 (1179f458c5db5072781101144a8d7e017fcb568c)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/6B3BBEAC-A047-4E5B-B24F-CC2C3624397E/20180208-170852.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. updated to edge 18.02.0-ce-rc2-mac51 (22446) 504ab35201
  2. restart the docker for mac app

**Comment by akimd** [comment]
Hi!

18.02.0-ce-mac53 was released, please try with that one and report whether it fixed your issue.

**Comment by efx** [comment]
hi @akimd, I actually had to revert to the stable channel. So I'll close this as running 17.12.0-ce-mac49 (21995) + a reset fixed things.
