### ISSUE TITLE
Kubernetes failed to start

### ISSUE THREAD

**Issue by GuillaumeMorini** [docker/for-mac#2585]
### Expected behavior

Kubernetes should start normally

### Actual behavior

Kubernetes failed to start

### Information

Diagnostic ID: 7E8BB07F-8CDC-44D1-BD51-9A3B1654BFFE
Docker for Mac: version: 18.02.0-ce-rc2-mac51 (1179f458c5db5072781101144a8d7e017fcb568c)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/7E8BB07F-8CDC-44D1-BD51-9A3B1654BFFE/20180209-115951.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Just installed version Version 18.02.0-ce-rc2-mac51 (22446)
Channel: edge

**Comment by pgayvallet** [comment]
Hi,

What does `kubectl get nodes` is telling you ?

**Comment by GuillaumeMorini** [comment]
In fact, it just worked after a reload of my Mac

Thanks and sorry for this false issue





On Feb 9, 2018, at 15:01, Pierre Gayvallet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

What does kubectl get nodes is telling you ?

**Comment by pgayvallet** [comment]
Depending on the network, the init can be quite slow ( +- 250mb to download). Guess it's only that, if simple reload fixed it.

Anyway, closing.
