### ISSUE TITLE
Any saved image isn't working anymore

### ISSUE THREAD

**Issue by superandrew** [docker/for-mac#2588]
### Expected behavior
I have many images stored on ECS that don't work anymore after a few months from last launch.
```docker images
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
123820204514.dkr.ecr.eu-west-1.amazonaws.com/playoff   olympus-1.0.0       2a85acdb96d0        9 months ago        691MB
```

`docker run <imageid>` runs a container
### Actual behavior

```
➜ docker run 2a85acdb96d0

docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/bin/start\": stat /usr/bin/start: no such file or directory": unknown.
ERRO[0001] error waiting for container: context canceled
```
### Information
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/2F95E3E7-A87C-4239-9B5F-AF0A3A1F31A2/20180209-185420.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Reinstall Docker for Mac, completely
  1. Pull an image
  2. run the image.

I am able to run "standard" images like `docker run nginx` but that's it. Any of my previous images isn't working on my computer or my colleagues computer, same error.

**Comment by pgayvallet** [comment]
Hello,

- Is the image working on a standard docker (on linux) ?
- Was the image correctly running on a previous version of docker 4 mac ?
- what does `docker run 2a85acdb96d0 ls /usr/bin/` tells you ?

We have no other reports of non-"backward" compatible issue of this kind. Also the error message `/usr/bin/start: no such file or directory` and the fact that your colleagues reproduce the issue, make me really thing of an issue with your image (data corruption / wrong run command) than a bug in docker.

**Comment by superandrew** [comment]
After many checks, I discovered the problem wasn't related to docker. Sorry and thank you.
