### ISSUE TITLE
Mac Sleeps Docker Swarm Mode - Error response from daemon: This node is not a swarm manager.

### ISSUE THREAD

**Issue by vibe** [docker/for-mac#2589]
### Expected behavior
Expected to be able to continuously execute my docker swarm commands after wake up.
*mac wakes up*
`docker stack` and other docker swarm mode commands should work. 
### Actual behavior
Only local swarm node.
After mac goes to sleep and wakes up, the previously deployed stack (locally) is still running.

But commands fail and can say it is not a node manager however it is the ONLY node and a manager node which started the existing running stack.
```

➜   docker stack ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
➜  docker swarm init
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
➜  docker stack ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

```

### Information
Diagnostic ID: 1E9822CA-E507-4EDD-BBF0-9E9E90E60190
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.4 (build: 17E150g)
logs: /tmp/1E9822CA-E507-4EDD-BBF0-9E9E90E60190/20180209-132838.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

### Steps to reproduce the behavior

  1. Init swarm mode
  2. Run a stack
  3. let your mac sleep
  4. Come back , wake up mac
  5. realize you can no longer run docker swarm commands, but stack is still running

**Comment by pgayvallet** [comment]
Hi,

Can't seem to reproduce, either on 17.12-stable or on latest edge, and either on Sleep or SafeSleep modes.

Are you sure the computer didnt simply restart ? If not, any clue on how to reproduce this ?
