### ISSUE TITLE
Bad response from Docker Engine

### ISSUE THREAD

**Issue by ruddra** [docker/for-mac#259]
### Expected behavior
`docker ps`
Showing running container list.
### Actual behavior
Error response from daemon: Bad response from Docker engine
### Information

Diagnostic ID: 264E4F98-E2B7-4A81-8EC1-E83244C56F55
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Forcibly stop Mac
2. Start Mac Normally
3. Start Docker
4. Run `docker ps`

**Comment by loopmode** [comment]
I am experiencing the same problem and am currently unable to work on my projects.
I have this since I allowed docker to update this morning. My current docker version is `Version 1.12.1-rc1-beta23 (build: 11375)`

**Comment by dsheets** [comment]
@loopmode could you please post your diagnostic ID and *at least click* the `Open Issues` button (that's the only way it uploads right now).

**Comment by loopmode** [comment]
@dsheets Sorry I was assigned to a different project this week, and totally forgot about this one.
I did as suggested, see https://github.com/docker/for-mac/issues/433

However, I will probably do the setup from scratch again (docker plkus project), as I need to be working on the docker-based project again. I hope it will work fine that way.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by xjiahang** [comment]
Hi.Factory Reset can fix the things.
