### ISSUE TITLE
Resetting Docker to Factory Defaults is taking a LONG time

### ISSUE THREAD

**Issue by egilchri** [docker/for-mac#2590]
### Expected behavior
Rapid reset to factory defaults.
### Actual behavior
Window  saying "Resetting to factory defaults just sitting there
### Information

  I was installing Docker on my Macbook Pro and everything was going fine, I  restarted several times as I filled out my Docker preferences. Then I got to the insecure registries section and typed in a bad value, and restarted.

At that point I got a fatal error, with the only choice being to reset to factory defaults. Fine, I pressed that button and now it's just sitting there. I am reluctant to do anything further, like force quit, until I know what's going on.

### Steps to reproduce the behavior

  1. Install docker
  2. Edit prefereces
  3. Put in incorrect value for insecure registries
  4. Restart

**Comment by egilchri** [comment]
Nevermind. I still get the fatal error even when I type in the insecure registry correctly. So my problems go deeper than I first thought.

**Comment by egilchri** [comment]
Closing until I figure more out about this. By the way, I ended up killing the Docker process from the command line in order to get rid of that "Resetting to Factory Defaults" window

**Comment by TobiasRath** [comment]
Why is this closed? I had the same Problem on Mac

Mac OS Sierra 10.12.6
Docker Version 17.12.0-ce-mac55 (23011)

Problem: If i put in a mirror url not starting with http*:// the Daemon crashed and try to reset to factory setting. This takes more one minute.

**Comment by okgolove-rf** [comment]
Same problem.

**Comment by YRM64** [comment]
Were you ever able to run a diagnostic log, if so, what did your diagnostic log provide?  And, can you please provide that log here on this posting.
