### ISSUE TITLE
Kubernetes fails to start

### ISSUE THREAD

**Issue by chris-camm** [docker/for-mac#2592]
### Expected behavior

Kubernetes should start in Docker

### Actual behavior

Kubernetes does not start.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/D78A759F-4490-4156-B85C-D48622A337C7/20180212-095402.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. ... Reboot the Mac
  2. ... Launch Docker

**Comment by rgardam** [comment]
seems to have started after the latest update.

**Comment by leecade** [comment]
same here.

**Comment by leecade** [comment]
Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.13.3 (build: 17D47)

**Comment by pgayvallet** [comment]
@leecade If got something that could appear to be the same issue, please perform and provide a diagnostic here.

@chris-camm was this an upgrade or a clean install ? if upgrade, was it working before it ?

**Comment by chris-camm** [comment]
I have had Docker and kubernetes running separately for over a year. I uninstalled kubernetes when docker introduced this to the docker package. This was working when initially installed. The latest update has stopped this from working for me.

**Comment by iloveyo123u1** [comment]
same here.

Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.13.3 (build: 17D47)

**Comment by kevineaton** [comment]
I can confirm. I had it working and have used it for a demonstration, but the latest build seems to have broken the Kubernetes instance. What's interesting is that the diagnostic shows [OK] for Kubernetes, but the menu shows Kubernetes failed to start.

Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/1F71C7B0-5128-4141-996F-E4F526F58430/20180218-152340.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by mqy** [comment]
Same here. Diagonose shows error:

[ERROR] kubernetes
#ffb2b2# kubernetes check failed with: (Failure
"exec: /usr/local/bin/kubectl --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}

Docker 18.02.0-ce-mac53 (22617)
macOS 10.13.3  (build: 17D47)

I had docker edge for mac updated for several times since first install months ago.
macOS has been updated to 10.13.3 before enabling and running k8s for the first time.

**Comment by chris-camm** [comment]
This is still an issue with Version 18.03.0-ce-rc4-mac57 (23360)

**Comment by marcpar** [comment]
Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/6D20E659-BB72-480E-83A8-CF9D35374A96/20180427-162043.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

**Comment by YRM64** [comment]
Troubleshooting tips:

After the upgrade, did your environment change, what environment is kubectl pointing to?  And, what about the context?  If you don't know:
                                                          Kubectl confit get-contexts

**Comment by YRM64** [comment]
Troubleshooting Tip:

After the upgrade did anything change in your environment, and what environment is Kubectl pointing to?  What about your context, if you don't know:

                                                Kubectl config get-contexts
