### ISSUE TITLE
Struck at 'docker is starting' on MaxOS High Sierra

### ISSUE THREAD

**Issue by yaneshtyagi** [docker/for-mac#2597]
### Expected behavior
Docker should run

### Actual behavior
Docker is not starting

### Information
Diagnostic ID: 57A579B9-8602-46AA-90C8-F0B7387D0575

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/57A579B9-8602-46AA-90C8-F0B7387D0575/20180213-004120.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install Docker for Mac
  2. Run docker from launchpad

**Comment by SakalAndrej** [comment]
Same Error!

**Comment by jeffxf** [comment]
I was getting the same error. I uninstalled docker and downloaded a bit older version mentioned here: https://github.com/docker/for-mac/issues/2611#issuecomment-366290734

Installing that version worked. I then accepted the update prompt just to see what would happen and it surprisingly updated fine to the newest version and is working.
