### ISSUE TITLE
Docker crash report

### ISSUE THREAD

**Issue by sundarshankar** [docker/for-mac#2598]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hi,

Closing. Please reopen with proper diagnosticId and description if still present.
