### ISSUE TITLE
Docker4Mac upgrade issue - docker won't start after upgrade

### ISSUE THREAD

**Issue by othews** [docker/for-mac#260]
### Steps to reproduce

1. Start previous version of docker
2. Accept to update to latest version of docker
3. after restarting the Docker service (by upgrade service itself) - service creates an issue report

### Expected behavior

Docker service should startup.

### Actual behavior

Docker creates an issue report. Docker cannot startup after upgrade.
[20160813-095754.tar.gz](https://github.com/docker/for-mac/files/416469/20160813-095754.tar.gz)
[20160813-095754.tar.gz](https://github.com/docker/for-mac/files/416470/20160813-095754.tar.gz)

### Information

```
Diagnostic ID: F5F395DE-3FC5-411D-9A8F-8D3A01D12215
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/othews/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     menubar
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/othews/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/othews/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
