### ISSUE TITLE
Container in Kubernetes edge cannot resolve itself

### ISSUE THREAD

**Issue by bajohns** [docker/for-mac#2604]
### Expected behavior

A container should resolve to a valid IP address. Many applications expect to be able to resolve a machine hostname (JVM frameworks specifically). Even if this resolved locally it would resolve these issues. 

I am not aware of a way to set the hostname in Kubernetes and/or set an static host files entry.

root@data-7b7ccd9b47-6xcqp:/# dig `hostname`
; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> data-7b7ccd9b47-6xcqp
.....
;; QUESTION SECTION:
data-7b7ccd9b47-6xcqp. 0	IN	A	X.X.X.X
....

### Actual behavior

root@data-7b7ccd9b47-6xcqp:/# dig `hostname`
; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> data-7b7ccd9b47-6xcqp
....
;; QUESTION SECTION:
data-7b7ccd9b47-6xcqp.	IN	A
.....

### Information

 Docker for Mac: version: 18.02.0-ce-mac53 (60e488931a12eeba773efb9e92be068a3c081758)
macOS: version 10.13.4 (build: 17E150g)
logs: /tmp/20C1C749-5B61-4C20-9545-F86F4476103F/20180214-014506.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Start a container with dig installed
  2. Run dig `hostname`

**Comment by pgayvallet** [comment]
Hello,

How is this related to Docker4Mac and not only a Kubernetes issue / question ? Is this behaving as you would expect in another k8s cluster outside of d4m ?

**Comment by bajohns** [comment]
@pgayvallet Looks like I jumped to conclusion here. I compared the d4m to a freestanding k8s cluster I have and dig fails to resolve in both BUT the both have an /etc/hosts entry with the correct ip address set.

The situation is that I have a helm chart that runs correctly in a k8s cluster but fails to run in the d4m cluster. I will dig back in to understand why this failure is happening.

Closing.
