### ISSUE TITLE
679CCEF7-A525-4BA4-A242-D1F607BAD813

### ISSUE THREAD

**Issue by JoseRodi** [docker/for-mac#2605]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Not enough details on the actual failure, closing.
