### ISSUE TITLE
Excessive amount of files in database folder

### ISSUE THREAD

**Issue by stepmuel** [docker/for-mac#2607]
### Information

On my system, `~/Library/Containers/com.docker.docker/Data/database/.git` contains 379810 files, which is over 15% of all other files combined. Having so many files within the home folder slows down many operations like incremental backups or calculating folder size. 

### Steps to reproduce the behavior

`find ~/Library/Containers/com.docker.docker/Data/database/.git -type f | wc -l`

**Comment by pgayvallet** [comment]
Hi,

Indeed, this is never cleaned.

If you are on a version >= 17.09, you can safely stop docker, delete `database/*` and then restart. Worse thing that should happen is loosing your shared folder info (only need to re-add them from the settings).
