### ISSUE TITLE
Override --max-connections configuration

### ISSUE THREAD

**Issue by kondratovich** [docker/for-mac#2610]
### Expected behavior
For some time, there was an option to configure some properties for Docker. You could place file at path `~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp/max-connections` to override max connections.

### Actual behavior
Currently, seems it's not working anymore. First, there is no such folder after some update. My docker containers start to drop connections at about 2000. The same configuration I can found for `vpnkit` from command line.

```
andrew           11782   0.0  0.1  4394256  16776   ??  S    11:58AM   0:00.46 com.docker.vpnkit --ethernet fd:3 --port fd:4 --introspection fd:5 --diagnostics fd:6 --vsock-path /Users/andrew/Library/Containers/com.docker.docker/Data/connect --host-names docker.for.mac.localhost,docker.for.mac.host.internal --gateway-names docker.for.mac.gateway.internal,docker.for.mac.http.internal --listen-backlog 32 --mtu 1500 --allowed-bind-addresses 0.0.0.0 --http /Users/andrew/Library/Group Containers/group.com.docker/http_proxy.json --dhcp /Users/andrew/Library/Group Containers/group.com.docker/dhcp.json --port-max-idle-time 300 --max-connections 2000 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.254 --log-destination asl
```

I could not find the way to override it. Where is new database location? Does command line flags have more priority? How to override `vpnkit` launch flags?

### Information

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/C6F63F2B-3E7B-432B-AC93-83FF0C3424CD/20180215-120659.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by pgayvallet** [comment]
Hi.

We are not using the DB anymore.

You can still change the setting, though, by adding/editing the `vpnKitMaxConnections` property in the `~/Library/Group\ Containers/group.com.docker/settings.json` file and restarting the app. This will override the default (2000) value for the `--max-connections` flag.
