### ISSUE TITLE
Docker dies after installing latest update on Mac High Sierra

### ISSUE THREAD

**Issue by Johnb6262** [docker/for-mac#2611]
### Expected behavior
Docker actually starting after an update
### Actual behavior
After installing the latest updated today, Docker won't start and cannot diagnose or reset to factory defaults
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Nothing - it just hangs
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install the latest update on a Mac OS High Sierra machine
  2. Watch Docker fail to start, fail to diagnose and fail to reset to factory defaults

**Comment by pgayvallet** [comment]
Hi,

- From/To which version are you updating ?

- With the docker app closed, can you `ps aux | grep com.docker` and tell me the result ? If some processes are alive, can you try killing them all and then start the app ?

**Comment by Johnb6262** [comment]
I'm not sure about the version numbers.

I uninstalled what I had and installed the latest stable version and it
still didn't work.

I talked to some people at my company and they confirmed that something is
broken and advised me to go back to an earlier version - which I did.  Even
that version hung until I rebooted the box and tried again - then it worked.

So I'm good for now - on an earlier version.

**Comment by pgayvallet** [comment]
I guess that's good news.

Still, any info on the issue would help us reproduce it and avoid other users have the same problem.

Do you know which version you did get back to ?

**Comment by Johnb6262** [comment]
I'll go look...

In a nutshell - even the very latest stable version downloaded and
installed from your website hung.  I did reboot once in that process and it
still hung.

I downgraded to: https://download.docker.com/mac/stable/21090/Docker.dmg

This was a link given me by one of our Docker "experts"

Ping me back if I can help - I cut my teeth in support and QA before
becoming a developer...
