### ISSUE TITLE
Another day, another error...

### ISSUE THREAD

**Issue by vgoklani** [docker/for-mac#2612]
### Expected behavior
Docker for mac should be stable, like it was last December...
### Actual behavior

Docker freezes after running for two days. I've reset it from scratch, multiple times. This is crashing on ALL my macs, and is frankly exhausting. 

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/D5801DD2-9EEA-4DB7-A57D-171424CC5AA4/20180215-193113.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/vgoklani/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/vgoklani/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/vgoklani/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
```
### Steps to reproduce the behavior

Install the stable version of Docker for mac, and just let it run. It will crash after two days...

**Comment by akimd** [comment]
Hi @vgoklani,

I can understand the frustration, sorry about that.  Docker for Desktop is not trivial.

Could you please try the Edge version and see if it addresses your concerns?

**Comment by akimd** [comment]
No answer.

**Comment by vgoklani** [comment]
Sorry I missed your response. Is the Edge version more stable? I thought it would contain more experimental features?

**Comment by akimd** [comment]
Yes, it contains more experimental features, yet in my experience it is not less stable.
