### ISSUE TITLE
~/Library/Containers/com.docker.docker/Data/database has broken .git directory

### ISSUE THREAD

**Issue by lexicalunit** [docker/for-mac#2619]
### Expected behavior

We expect `~/Library/Containers/com.docker.docker/Data/database` to be a valid repository with a valid `.git` directory. You should be able to enter that directory and run `git` commands such as `git status`.

### Actual behavior

```
$ cd ~/Library/Containers/com.docker.docker/Data/database
$ ls -la .git
total 8.0K
drwxr-xr-x 5 me staff 160 Feb 19 12:49 ./
drwxr-xr-x 4 me staff 128 Feb 19 12:35 ../
-rw------- 1 me staff  22 Jan 30 14:23 HEAD
-rw-r--r-- 1 me staff 363 Feb 19 12:49 sourcetreeconfig
drwxr-xr-x 2 me staff  64 Jan 30 14:23 tmp/
$ git status
fatal: Not a git repository (or any of the parent directories): .git
```

### Information

**Full output of the diagnostics from "Diagnose & Feedback" in the menu**

```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/223A2FE5-C871-4397-A714-C977831DFE77/20180219-131016.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**git version**

```
$ git --version
git version 2.16.1
```

### Steps to reproduce the behavior

1. Install Docker for Mac.
2. `cd` to the mentioned directory.
3. Try to run any `git` command, such as `git status`. It will fail because the `.git` directory is not valid.

**Comment by pgayvallet** [comment]
Hello,

Since 17.12, we are no longer using the git-ish DB. We just forget to clean it up during the update.

**Comment by lexicalunit** [comment]
@pgayvallet does this mean that modifying a file in this directory no longer has any real effect? In my case I'm looking at the file `com.docker.driver.amd64-linux/disk/on-flush` and putting the text `os` into it. Is that just not used anymore or is it just that it's no longer a git repo?

**Comment by hkirsman** [comment]
Would also like to know

**Comment by rmahnovetsky** [comment]
+1

**Comment by micschro-os** [comment]
+1

**Comment by raxod502** [comment]
@pgayvallet I need to increase the number of allowed file descriptors. According to https://github.com/docker/for-mac/issues/1009#issuecomment-264874864, I need to edit a file in this Git repository, but as you point out it no longer exists. What's the replacement?

**Comment by hendrysadrak** [comment]
+1

**Comment by manelclos** [comment]
+1
