### ISSUE TITLE
unable to build images

### ISSUE THREAD

**Issue by massimov** [docker/for-mac#262]
### Expected behaviour
being able to pull images and create new ones, as usual

### Actual behaviour
cannot pull/create new images.
error message says "no space left on device", but there should be plenty of space on disk for wanted images.
here is a sample session:

Massimos-MacBook-Pro:docker massimo$ docker build --tag mv/uvl .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM python:3.6
3.6: Pulling from library/python
357ea8c3d80b: Pull complete
52befadefd24: Pull complete
3c0732d5313c: Pull complete
ceb711c7e301: Downloading [==================================================>] 129.7 MB/129.7 MB
4211bb537697: Download complete
a3160ac922b2: Download complete
761c54ecf966: Download complete
write /var/lib/docker/tmp/GetImageBlob722528026: no space left on device
Massimos-MacBook-Pro:docker massimo$ df -h
Filesystem                          Size   Used  Avail Capacity   iused    ifree %iused  Mounted on
/dev/disk1                         465Gi  401Gi   64Gi    87% 105092795 16746791   86%   /
devfs                              332Ki  332Ki    0Bi   100%      1152        0  100%   /dev
map -hosts                           0Bi    0Bi    0Bi   100%         0        0  100%   /net
map auto_home                        0Bi    0Bi    0Bi   100%         0        0  100%   /home
localhost:/y6p6LrYigqKnn-It3_whEu  465Gi  465Gi    0Bi   100%         0        0  100%   /Volumes/MobileBackups
/dev/disk2                         2.0Mi  140Ki  1.9Mi     7%        33      477    6%   /private/var/folders/xf/gx4m_5s937n0_f1tf0mspqr80000gn/T/NVProtectedEditingSpace
/dev/disk3s1                       236Mi  216Mi   20Mi    92%     55247     5157   91%   /Volumes/Docker
Massimos-MacBook-Pro:docker massimo$

### Information
I have been using Docker toolbox without problems on my Mac for more than a year. About one week ago I installed Docker for Mac. Since then, I have been unable to build any images (both new ones and recreating older ones that I have been running for quite a while). I think that there must be some really important piece of information that I'm missing.

Diagnostic ID: ABE3331B-ED26-4A8C-AF7F-575C9BC4DC7C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
There is currently a limit on the size of moby (~65gb).
You can remove your current images, which should free up some space, via:
```
docker images rmi $(docker images -q)
```

**Comment by mchiang0610** [comment]
let us know if it's not working, and we'll reopen the issue. 

Thanks!

**Comment by massimov** [comment]
yes, it is working now.
the solution, in the end, was simple (albeit unintuitive): when installing docker native, it asks if you want to migrate existing containers (built with docker toolbox).
Don't do that: if you do, you will have the problems described above.
After several fruitless attempts, I choose not to migrate containers and now I can do what is normal for work.
