### ISSUE TITLE
CPU compatibility issue?

### ISSUE THREAD

**Issue by ludoplex** [docker/for-mac#2620]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

9DA3E0EA-EE03-46BA-9FCE-2DD85BF50FF8

**Comment by pgayvallet** [comment]
Closing.

Please reopen with proper description and diag summary.
