### ISSUE TITLE
Docker for Mac

### ISSUE THREAD

**Issue by giuseppezileni** [docker/for-mac#2621]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Closing.

Please reopen with proper description or/and diagnostic if necessary.
