### ISSUE TITLE
Fatal Error com.docker.supervisor failed to start 

### ISSUE THREAD

**Issue by ingared8** [docker/for-mac#2623]
### Expected behavior
Expecting to start after reboot.

### Actual behavior
Throwing Fatal Error 
(com.docker.supervisor failed to start
Exit code 1)

### Information
Diagnostics Information
macOS: version 10.11.6 (build: 15G18013)
Docker.app: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
Local time: Tue Feb 20 11:37:50 PST 2018
UTC:        Tue Feb 20 19:37:50 UTC 2018
Timestamp:  20180220-113750
Running diagnostic tests:
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s60: check if service is running
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   vpnkit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/thomas/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/thomas/Library/Containers/com.docker.docker/Data/s51
[ERROR]   vpnkit           com.docker.vpnkit is not running
Error exec: /usr/sbin/lsof -n -P | grep LISTEN > /tmp/0F40857B-CB36-438E-B74C-25B28937E413/20180220-113750/"lsof -n -P": exit 1
Error docker ps: got timeout (docker ps: exit 1)
  

### Steps to reproduce the behavior

  1.  Shut down your mac
  2. Start your mac

**Comment by djs55** [comment]
@ingared8 unfortunately there's nothing I can do unless the diagnostics are uploaded and the ID quoted here. I'll close this ticket but feel free to open a fresh one!
