### ISSUE TITLE
Keychain secrets / certificates to docker containers

### ISSUE THREAD

**Issue by matthewbarr** [docker/for-mac#2629]
It would be amazing to offer a way to give containers secrets from the Keychain on the mac.  Ideally, similar to the swarm secrets.

(This is not for the use of the docker daemon, but for processes running in the containers to use.)

**Comment by JeremyIglehart** [comment]
I agree, I've been working on trying to find a way to do this.  Is anyone else out there working on this?

**Comment by eedgar** [comment]
Has anyone figured out a good way to pass this through to the containers?
