### ISSUE TITLE
com.docker.supervisor failed to start

### ISSUE THREAD

**Issue by benjy** [docker/for-mac#2641]
### Expected behavior

Docker should start

### Actual behavior

Docker fails to start, can only access the Diganose & Feedback screen. The diagnosis gives me only the following output: `Failure: diagnostic: response is not valid JSON`. Full CLI output below.

### Information

```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
macOS: version 10.12.6 (build: 16G1212)
Docker.app: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
Local time: Mon 26 Feb 2018 10:00:43 AWST
UTC:        Mon 26 Feb 2018 02:00:43 UTC
Timestamp:  20180226-100043
Running diagnostic tests:
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /Users/bendougherty/Library/Containers/com.docker.docker/Data/s60: check if service is running
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   vpnkit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/bendougherty/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/bendougherty/Library/Containers/com.docker.docker/Data/s51
[ERROR]   vpnkit           com.docker.vpnkit is not running
Error docker ps: got timeout (docker ps: exit 1)
```
This seems to happen whenever my Mac crashes. This happens quite a lot for me due a bug with an external display, it often kernel panics and switches off. Then when I switch back on, Docker is broken pretty reliably. Only a factory reset fixes the issue so far.

**Comment by akimd** [comment]
Please try a more recent version of Docker.  For instance https://download.docker.com/mac/edge/23022/Docker.dmg.

**Comment by benjy** [comment]
I've disabled the sleep settings on my mac which seems to have fixed the crashing of the Mac so hopefully that will prevent me "corrupting" docker to begin with.

I didn't want to move back to edge because I was using Docker for something important, hopefully the fix will make it to the stable branch.

**Comment by akimd** [comment]
FWIW, I personally don't think Edge releases are less stable than Stable releases.
