### ISSUE TITLE
Fresh install Docker, stay at "Docker is starting"

### ISSUE THREAD

**Issue by zhaoxixin** [docker/for-mac#2642]
### Expected behavior
run Docker
### Actual behavior
stay at "Docker is starting"
### Information

diagnostic ID
72C7D5D9-8663-4DBF-B6B0-93626C92E4AB

Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/72C7D5D9-8663-4DBF-B6B0-93626C92E4AB/20180226-151156.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. download Docker
  2. install
  3. start Docker
  4. Docker is starting....
  5.wating....

**Comment by zhaoxixin** [comment]
Solved refer to /issues/2633
reset to factory default
![image](https://user-images.githubusercontent.com/31915085/36658448-83349372-1b0b-11e8-9b83-034075b5b45d.png)

Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/72C7D5D9-8663-4DBF-B6B0-93626C92E4AB/20180226-153802.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by tylerssn** [comment]
@alycda  - any progress here?
