### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by ding** [docker/for-mac#2643]
### Expected behavior
Start docker with double click the docker.app

### Actual behavior
Docker is always starting...

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
>Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/701E2DCA-D569-4A8A-87B0-27F6D9A79B6C/20180226-233920.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

Diagnostic ID: 701E2DCA-D569-4A8A-87B0-27F6D9A79B6C

**Comment by Sam-Houlahan** [comment]
Same issue here.
