### ISSUE TITLE
Docker for Mac won't stop starting...

### ISSUE THREAD

**Issue by obotor** [docker/for-mac#2645]
### Expected behavior
Docker should start on app invocation or on machine boot.

### Actual behavior
The docker stucks in starting mode. 'docker ps' will timeout.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Diagnosis:
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/9E447198-3ED2-4269-AAF2-34238A653276/20180226-175512.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

Reboot computer / quit & reopen Docker app.

**Comment by kruny1001** [comment]
@obotor I have a same issue. It takes forever to start up daemon with 17.12.0-ce-mac49

**Comment by Sam-Houlahan** [comment]
Same here reinstalled Docker as well. Been waiting for it to start for over 15 mins now.

**Comment by dsuckau** [comment]
For me and my co-workers the same with 17.12.0-ce-mac49. But since weeks it happened again and again with previous versions as well.
