### ISSUE TITLE
osxfs volume wrong permissions when using -u

### ISSUE THREAD

**Issue by c4tz** [docker/for-mac#2647]
Hey there,

there seems to be a faulty behavior in oxfs when using the `-u` option with docker for mac.

### Expected behavior

Command:
`docker run -it -u $(id -u):$(id -g) -v $HOME:/test alpine:latest touch /test/file`

Output:
` ` (exit code 0)

### Actual behavior

Command:
`docker run -it -u $(id -u):$(id -g) -v $HOME:/test alpine:latest touch /test/file`

Output:
`touch: /test/file: Permission denied` (exit code 1)

### Information

When running the same command without `-u` (`docker run -it -v $HOME:/test alpine:latest touch /test/file`), it works. On the host, the $HOME folder is owned by 503:20, but in the container it is owned by 1000:50, which causes the example case to fail.

I would expect the folder to have the same owner inside the container as on the host (or at least the given one by `-u`).

**Comment by pgayvallet** [comment]
Users and groups are not shared between the host and the vm. This is not something we are going to do.

Closing.

**Comment by c4tz** [comment]
Okay, but maybe the `-u` flag should be just omitted in case it is set?
