### ISSUE TITLE
Docker starting... Docker starting...  Docker starting... 

### ISSUE THREAD

**Issue by pventuri** [docker/for-mac#2649]
### Diagnostic ID

Juste try to run "docker" on my MAC ?

### Actual behavior

Docker for Mac: version: 17.09.0-ce-mac32 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/F92B6817-8EC7-4C63-BE07-DC8418A8D096/20180228-100619.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --style syslog --last 1d | grep -i docker > \"/tmp/F92B6817-8EC7-4C63-BE07-DC8418A8D096/20180228-100619/docker-system-os.log\": exit 1")
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

?

**Comment by guillaumerose** [comment]
Hi @pventuri. You are using an old version of Docker for Mac. Can you please try the latest release ?
