### ISSUE TITLE
Docker fails to start after update

### ISSUE THREAD

**Issue by xkizer** [docker/for-mac#2651]
### Expected behavior
Docker should start up

### Actual behavior
Docker fails to start with message 
```
com.docker.supervisor failed to start
Exit code 1
```

### Information

Diagnostics ID: 69026DC2-7E81-47EB-9589-2EB47E82BB01

Diagnostics output:
````
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/69026DC2-7E81-47EB-9589-2EB47E82BB01/20180301-105818.tar.gz
failure: Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/conuegbu/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/conuegbu/Library/Containers/com.docker.docker/Data/s51
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/conuegbu/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/conuegbu/Library/Containers/com.docker.docker/Data/s51
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[ERROR]  moby
         /Users/conuegbu/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/conuegbu/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
````

**Comment by crashGoBoom** [comment]
I am experiencing this same issue. Removed 17.12.0-ce-mac55 and installed 18.03.0-ce-rc1-mac54 from the [edge](https://download.docker.com/mac/edge/Docker.dmg) channel as a workaround for today. Hopefully this gets solved asap.

**Comment by aidankomalley** [comment]
I am experiencing the same issue.
Diagnositc Id is : B0E916FE-F9BC-4AE7-ACD3-CCC5C329E4E8

**Comment by DukeXar** [comment]
Same issue: 085306AA-8327-4A30-B99D-E30AB8E8C6D6

**Comment by antonin07130** [comment]
Same issue, crashGoBoom solution worked for me : it seems to have been corrected on Edge version.

**Comment by justin-pierce** [comment]
I had a similar issue and it was because virtualization had been disabled in my bios (hackintosh running Sierra)

**Comment by psisodia** [comment]
A3732DEA-5620-4FC1-9412-3616ED4B268D

Same issue on Mac

**Comment by YRM64** [comment]
xkizer,

I think guillaumerose labeled it correctly on March 8, 2018.  There seems to be an on-going problem with Docker version 17.12.0 on Mac operating systems.  Folks experiencing Docker failure after updates, or otherwise, are advised to try a more recent version of Docker.  

Most folks who are experiencing this type of problem are downloading the Edge version 18.02.0-ce-rc1-Mac.

However, this is not an official diagnosis for this use case.
