### ISSUE TITLE
React Hot Module Reload (HMR) Not Working Without Docker-Sync

### ISSUE THREAD

**Issue by taufek** [docker/for-mac#2652]
### Behavior with Docker-Sync
I've ReactJs project that I've setup with HMR with webpack and [wepback-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware).

I've mounted the application volume to Docker container via Docker-Sync to improve file-sync performance.

Step 1. When I booted the application I will see below in chrome dev console indicating that HMR is connected.

![connected](https://user-images.githubusercontent.com/10803354/36880446-aba7467e-1e03-11e8-8fa5-e012f38c6637.png)

Step 2. I run `webpack --watch` and made a code change and webpack will pick up the changes and triggers a recompilation as shown below:

![recompile](https://user-images.githubusercontent.com/10803354/36880464-c9a21334-1e03-11e8-91fd-b57862db734f.png)

Step 3. back in chrome dev console, I will see HMR is rebuilding the component based on the changes:

![rebuilding](https://user-images.githubusercontent.com/10803354/36880492-ec43bd70-1e03-11e8-81ee-6f95ad45bcd9.png)

### Behavior without Docker-Sync

When I swapped Docker-Sync with [Docker Volume Cached Flag](https://docs.docker.com/docker-for-mac/osxfs-caching/#cached), it does not work properly as the previous steps.

Without Docker-Sync, I will only get Step 1 (HMR Connected) and Step 2 (Webpack trigger recompilation) but it didn't trigger step 3 which my application does not get rebuild on code change. 

Hope someone can shed some light on this problem that I'm facing.

**Comment by taufek** [comment]
Found out it work if I made the file change directly in docker container it triggered the HMR to rebuild the component.

But when I made the file change from the host it does not trigger HMR to rebuild. But the changes does reflected in the container.

**Comment by taufek** [comment]
Found a solution in https://github.com/glenjamin/webpack-hot-middleware/issues/139

**Comment by blueabysm** [comment]
> Found out it work if I made the file change directly in docker container it triggered the HMR to rebuild the component in step 3.
> 
> But when I made the file change from the host it does not trigger HMR to rebuild. But the changes does reflected in the container. Then in the container if I execute `touch` on the changed file, it will trigger HMR to rebuild.

Hi taufek, I ran into the same issue to you. Recent google searches told me that [docker team fixed this inotify issue and patched it into edge channel about two months ago](https://forums.docker.com/t/inotify-events-are-not-stop-working-from-host-to-container/19010/2). I tried this solution , everything works fine.

FYI :)
