### ISSUE TITLE
docker doesn't encode url when pull/push to docker registry with S3 storage driver

### ISSUE THREAD

**Issue by xuhuijun** [docker/for-mac#2653]
### Expected behavior
when pull/push to docker registry with s3 storage driver, the value of **X-Amz-Credential** should be encoded ("/" character should be encoded as %2F.

please refer to s3 spec for detail [Authenticating Requests: Using Query Parameters (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)

### Actual behavior
pull failed with error message 
> error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code>..

the log of nginx show  X-Amz-Credential is not encoded.
![image](https://user-images.githubusercontent.com/19244989/36891214-cf056870-1e3b-11e8-9ff2-90563839ab32.png)

### Information

  - docker version is 1.18.02-ce
  - docker registry storage is s3

### Steps to reproduce the behavior

  1. on centos 7 host, setup docker registry with s3 storage. 
  2. on macbook with docker 1.18.02-ce, try to pull image from this docker registry
  3. pull command failed with message <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code>

**Comment by frostynova** [comment]
still met this problem, with Docker version 18.06.1-ce, build e68fc7a

**Comment by liuerfire** [comment]
+1 with Docker version 18.03.1-ce, build 9ee9f40

**Comment by k7** [comment]
+1 

Diagnostic ID `1972DFEA-5B6B-4223-A9AE-10AC3A9A33BE/20180928094750`

I capture http network, and found docker sent http request to our private s3 storage.

```
# It does not work.
# sent by docker-for-mac
GET http://172.1.1.5:1340/python-some-ne-bucket2/docker/registry/v2/blobs/sha256/25/256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=CYZ4ZCKMCLJLIK9QJ3KU/20180928/some-zonegroup/s3/aws4_request&X-Amz-Date=20180928T093703Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=47c17a4c87855c105de9acd093102a0d07a80d1ce67a996a974ebc4086f4d2eb HTTP/1.1
```

and return 
```xml
<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx0000000000000000aad8f-005badfa68-69f7-tupu-zone1</RequestId><HostId>69f7-tupu-zone1-tupu-zonegroup</HostId></Error>
```


I try emulated it via curl, by encode `/` to `%2F` , [aws doc](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)
```
# It works.
curl -X GET "http://172.1.1.5:1340/python-some-ne-bucket2/docker/registry/v2/blobs/sha256/25/256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=CYZ4ZCKMCLJLIK9QJ3KU%2F20180928%2Fsome-zonegroup%2Fs3%2Faws4_request&X-Amz-Date=20180928T093703Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=47c17a4c87855c105de9acd093102a0d07a80d1ce67a996a974ebc4086f4d2eb"
```

docker-for-mac, signed s3 using [Authenticating Requests: Using Query Parameters (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)

When I use docker in centos, I found that it signed s3 using another method: [Authenticating Requests: Using the Authorization Header (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html)

**Comment by tankery** [comment]
+1 Docker 18.09.0 on Mac still has this issue.
And just like @k7 said, encode the X-Amz-Credential parameter can fix this.

**Comment by justincormack** [comment]
Please open an issue on https://github.com/moby/moby/issues this does not sound like a docker for mac specific issue. It might also be an issue in github.com/docker/distribution it is not clear.

**Comment by frostynova** [comment]
@justincormack We did some tests with s3 storage driver:

CentOS, docker-ce 18.x  OK
macOS, docker for mac 17.x OK
macOS, docker for mac 18.x Failed

I doubt if docker for mac using an unstable docker version?

**Comment by vidarinho** [comment]
@justincormack - I urge you to reopen, we are seeing the exact same behaviour on S3 based docker registry. Requests to the S3 instance are missing encoded "/" in `X-Ams-Credential` query parameter, and fails authentication. No such problem on windows or linux. Let me know if you need an account to test against our repo, . If the problem lies elsewhere then docker for mac, please advise.

**Comment by danielmt** [comment]
macOS Docker version 18.09.2, build 6247962 Failing with the same issue.
Please, reopen this.

**Comment by frostynova** [comment]
Docker Desktop 2.1.0.4 39773, still failing
Please, reopen this.
