### ISSUE TITLE
Docker for mac "Kubernetes starting" never finishes

### ISSUE THREAD

**Issue by sjoerd-michels** [docker/for-mac#2654]
### Expected behavior
Kubernetes starts

### Actual behavior
"Kubernetes starting" never finishes

### Information
Diagnostic output

Docker for Mac: version: 18.03.0-ce-rc1-mac54 (e22e653363ad9e0f458ab38d464ab106d30a72b2)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/6E9495E2-975E-445A-96AC-BB4B17CF79A8/20180302-144658.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

**Comment by sjoerd-michels** [comment]
Reset Docker and tried again. This time is succeeded ... ?

**Comment by abdennour** [comment]
I fixed it.

# Brief

Add the following lines in `/etc/hosts` if it is empty.

```
127.0.0.1 localhost
::1       localhost
```

# Details:
1. Display the [log of docker](https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs):

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

2. Analyze the log: 
Found
```
2018-11-30 08:33:37.468984+0300  localhost com.docker.driver.amd64-linux[38047]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: dial tcp: lookup localhost: no such host
```
It means, it cannot resolve `localhost` ???!!

3. Check `/etc/hosts`

Oops! it is empty. 

4. Remediation

```
# cat /etc/hosts

127.0.0.1 localhost
::1       localhost
 ```

5. Watch the log again:

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

🎉 It works. k8s is now up and running with docker-for-mac.
