### ISSUE TITLE
Docker won't start - Version 18.03.0-ce-rc1-mac54 (23022)

### ISSUE THREAD

**Issue by cch0** [docker/for-mac#2655]
### Expected behavior

docker starts successfully

### Actual behavior

stuck with 'docker is starting'

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 18.03.0-ce-rc1-mac54 (e22e653363ad9e0f458ab38d464ab106d30a72b2)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/7C5B37F3-0F63-406E-B6B1-C4C928CC8C86/20180302-080536.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

### attempts have tried

pkill docker and delete Data folder under ~/Library/Containers/com.docker.docker

### Steps to reproduce the behavior

start Docker

**Comment by alycda** [comment]
I am having the same issue.

OSX 10.13.3 (17D102)

Diagnostic ID: 62F58FE7-C42C-4771-96DD-06DC45ACCD29

**Comment by djs55** [comment]
@cch0 thanks for your report.

Your logs show that the docker engine hasn't started and the following message is on the VM console:

```
                                                         This selection will
                                                         take you to the
                                                         Device Manager
```

I'm not sure what state the VM is in. If this is still reproducing, could you try running `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` and try interacting with it? I'm not sure whether this is a BIOS/UEFI-level screen or a Linux user space program.

Thanks!

**Comment by djs55** [comment]
@alycda thanks also for your report.

Your logs show a very similar symptom with a slightly different message
```

                                                         This selection will
                                                         direct the system to
                                                         continue to booting
                                                         process
```

I believe the error is coming from UEFI: I suspect it's failing to find the boot media.

Could you check whether the following paths exist? Also is there anything special about them (e.g. are they on an external drive?)

- /Applications/Docker.app/Contents/Resources/linuxkit/docker-for-mac.iso
- /Users/alyda/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/database.iso

Could you also try reading those paths (e.g. with `less`) to check the permissions?

Thanks!

**Comment by cch0** [comment]
@djs55 

Not sure if I can reproduce it again.  I just tried edge Version 18.03.0-ce-rc4-mac57 (23360) and it didn't have the same issue. Also CE stable version also works fine. 

I can only assume the previous edge version I had has issue.

**Comment by djs55** [comment]
@cch0 thanks for letting me know.

I tried to reproduce this myself but failed. Since neither of us can reproduce it I will close this ticket, but let me know if you have any further problems.

Thanks for your report!

**Comment by tylerssn** [comment]
I am experiencing the same symptoms.

**Comment by CedricFinance** [comment]
I have the same problem.

I ran `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` and got the following result:

![Capture d’écran 2019-09-23 à 13 42 13](https://user-images.githubusercontent.com/3935032/65422994-3d3ca500-de08-11e9-8b98-269511c6c654.png)

I have selected 'English' and then 'Continue' and then I have the bootlogs of the VM.

```
Welcome to GRUB!
  Booting `LinuxKit ISO Image'

[    0.000000] Linux version 4.9.184-linuxkit (root@a8c33e955a82) (gcc version 8.3.0 (Alpine 8.3.0) ) #1 SMP Tue Jul 2 22:58:16 UTC 2019
[    0.000000] Command line: BOOT_IMAGE=/boot/kernel console=ttyS0 console=ttyS1 page_poison=1 vsyscall=emulate panic=1 root=/dev/sr0 text
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000007eaa6fff] usable
[    0.000000] BIOS-e820: [mem 0x000000007eaa7000-0x000000007eab7fff] reserved
[    0.000000] BIOS-e820: [mem 0x000000007eab8000-0x000000007fb37fff] usable
[    0.000000] BIOS-e820: [mem 0x000000007fb38000-0x000000007fb8ffff] reserved
[    0.000000] BIOS-e820: [mem 0x000000007fb90000-0x000000007fb97fff] ACPI data
[    0.000000] BIOS-e820: [mem 0x000000007fb98000-0x000000007fb9bfff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x000000007fb9c000-0x000000007ffcffff] usable
[    0.000000] BIOS-e820: [mem 0x000000007ffd0000-0x000000007ffeffff] reserved
[    0.000000] BIOS-e820: [mem 0x000000007fff0000-0x000000007fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
```
...
```
<--DOCKER-->{"command":"dockerstate","setstate":"check for upgrade"}

/usr/bin/transfused: initialized logging system
/usr/bin/transfused: starting server
INFO[2019-09-23T11:45:25.611388982Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/kmsg/shim.sock" debug=false pid=1333
INFO[2019-09-23T11:45:25.825880866Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/sntpc/shim.sock" debug=false pid=1401
INFO[2019-09-23T11:45:26.941494645Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/socks/shim.sock" debug=false pid=1514
[   24.722682] Initializing XFRM netlink socket
INFO[2019-09-23T11:45:27.161047263Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/trim-after-delete/shim.sock" debug=false pid=1871
[   24.823596] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
INFO[2019-09-23T11:45:27.330361141Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/vpnkit-forwarder/shim.sock" debug=false pid=2002
INFO[2019-09-23T11:45:27.523917315Z] shim containerd-shim started                  address="/containerd-shim/services.linuxkit/write-and-rotate-logs/shim.sock" debug=false pid=2059

<--DOCKER-->{"command":"dockerstate","setstate":"running"}
```

After that docker is working.

When I restart docker, I have the same problem. I don't always manage to get the interactive menu with screen.

Sometimes, I have a black screen and a message like this "failed ioctl: interrupted system call" at the bottom of the terminal.

Sometimes, I have some garbage output. But I manage to boot the VM by blindly hitting up arrow / down arrow and enter.

I have docker desktop 2.1.0.1 (37199) on macOS 10.14.6.

**Comment by CedricFinance** [comment]
I have uploaded diagnostics data and logs here: https://github.com/docker/for-mac/issues/3921

**Comment by djs55** [comment]
@CedricFinance thanks for the report -- I've re-opened the ticket.

So far I've still not been able to reproduce this myself  :( However the screenshot is very interesting -- how does it know to offer a choice between English and French (and not any other language) I wonder?

I'm not 100% sure where the code for this menu lives. If it were in the hypervisor layer i.e. https://github.com/moby/hyperkit then it might be inheriting some locale environment variables but looking at the screenshot it seems like it's running inside the VM itself which suggests it might be code within the UEFI boot ROM. However if it's in the VM it will have really limited visibility into the host configuration unless we're somehow passing through locale settings through an ACPI table? This is all just guesswork -- clearly I'll have to investigate further!

**Comment by CedricFinance** [comment]
It's seems related to UEFI, I've found the top right message here: https://github.com/tianocore/edk2/blob/3806e1fd139775610d8f2e7541a916c3a91ad989/MdeModulePkg/Application/UiApp/FrontPageStrings.uni#L47

**Comment by djs55** [comment]
That link is very enlightening, thanks. I notice that they only define
```
#langdef   en-US "English"
#langdef   fr-FR "Français"
#langdef   en    "Standard English"
#langdef   fr    "Standard Français"
```
i.e. it seems that English and French are hardcoded and so there's no magic query of the host locale.

The fact that you can make the machine boot by selecting an option suggests that there is no filesystem corruption -- disproving my previous theory of a corrupted .iso image.

As to why the machine gets stuck at the menu screen when it should boot: this is still a mystery. Maybe the "interrupted system call" is a bug in the `hyperkit` virtual hardware which is confusing the UEFI when it tries to decide what to boot?

We're currently using `bhyve`'s UEFI from this branch https://github.com/freebsd/uefi-edk2/commits/bhyve/UDK2014.SP1 which, according to http://bhyvecon.org/bhyveconOttawa2019-DScott.pdf , is an implementation of the UEFI 2.4B specification. I noticed we're a few commits behind the most recent on that branch so I've rebuilt the file and enabled `DEBUG`, just in case it helps.

[uefi.zip](https://github.com/docker/for-mac/files/3643170/uefi.zip)

For future reference this was built with the `Dockerfile`:
```
FROM debian:jessie

ENV UEFI_REPO           https://github.com/freebsd/uefi-edk2.git
ENV UEFI_BRANCH         bhyve/UDK2014.SP1
ENV UEFI_COMMIT         aa8d718a5013d20295ec531ce82e84a0cf409bba
                        # Really "anything >= 49"
ENV UEFI_TOOLCHAIN      GCC49
                        # DEBUG or RELEASE
ENV UEFI_BUILD          DEBUG

RUN apt-get update && apt-get -y upgrade && apt-get -y install \
        build-essential \
        iasl \
        git \
        nasm \
        python \
        uuid-dev \
&& rm -rf /var/lib/apt/lists/*

RUN git clone -b "$UEFI_BRANCH" "$UEFI_REPO" /uefi && \
    cd /uefi && \
    git checkout -q "$UEFI_COMMIT"

RUN cd /uefi && \
    find . -name License.txt | while read l ; do \
        echo $l ; echo ; cat $l ; echo ; echo ; \
    done > /LICENSE

RUN jobs=$(nproc) && \
    cd /uefi && \
    make -C BaseTools

# EDK build requires bash
RUN /bin/bash -c 'jobs=$(nproc) && \
    cd /uefi && \
    . ./edksetup.sh && \
    build -a X64 -b "$UEFI_BUILD" -t "$UEFI_TOOLCHAIN" -p BhyvePkg/BhyvePkgX64.dsc && \
    cp Build/BhyveX64/"$UEFI_BUILD"_"$UEFI_TOOLCHAIN"/FV/BHYVE.fd /UEFI.fd'
```
It's a bit of a long shot but could you try replacing the file `/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd` and restarting Docker to see if it's any better or whether it includes more useful logs?

**Comment by CedricFinance** [comment]
It's not better.

I'm managed to have this menu. We see BHYVE 1.00.

![image](https://user-images.githubusercontent.com/3935032/65452312-4b5ae780-de41-11e9-9189-16af77f38064.png)

**Comment by CedricFinance** [comment]
I've changed some strings in the UEFI firmware and rebuilt it. I confirm that menu comes from the UEFI firmware.

Now, we have to figure out why the menu appears or why we get stuck at this menu.

**Comment by CedricFinance** [comment]
I have a quick hack to skip the menu.

https://github.com/CedricFinance/uefi-edk2/commit/272b43066033612668079057469c156f0fad481c

**Comment by CedricFinance** [comment]
Here is the firmware built with the above hack.

[UEFI.fd.zip](https://github.com/docker/for-mac/files/3646242/UEFI.fd.zip)

**Comment by djs55** [comment]
@CedricFinance thanks very much for the quick hack! If that has worked around the issue for you then I'm inclined to ship the patch.

I still don't know why the menu gets activated only on some machines / for some people -- but since the menu is of no real use we might as well programmatically skip it.

**Comment by CedricFinance** [comment]
@djs55 It worked for me and two of my colleagues who got the same problem.

**Comment by djs55** [comment]
@CedricFinance I've created a PR for the edge version of desktop with your UEFI patch. If you have a moment could you try: https://download-stage.docker.com/mac/edge/38511/Docker.dmg just to check I haven't messed up the build somehow.

**Comment by CedricFinance** [comment]
@djs55 It's working. I have restarted Docker for Mac 10 times and got no problems.

**Comment by djs55** [comment]
The PR is merged and the fix should be in the next edge release, due next week.

There should be a changelog entry
> - Mac: always skip UEFI boot menu so that the VM boot doesn't hang in some rare cases. Many thanks to Cédric Finance for suggesting a patch. [docker/for-mac#2655] [docker/for-mac#3921]


Thanks again for the report, patch and test!

**Comment by dev-xu** [comment]
@djs55 This is still happening in the new versions. Was it patched in new stable release? I am using docker desktop ce for mac v2.1.0.4.

**Comment by ql-eilde** [comment]
@dev-xu This issue is fixed in Docker for Mac Edge v2.1.4.0. See [edge release notes](https://docs.docker.com/docker-for-mac/edge-release-notes/)

**Comment by mpanighetti** [comment]
When is the fix being applied to the stable releases?

**Comment by ryanissamson** [comment]
Yes, this works for me, coming from [#4062](https://github.com/docker/for-mac/issues/4062). Looking forward to a stable release of this fix.
