### ISSUE TITLE
docker on Mac OS High Sierra is so slow: 20 time slower than Ubuntu

### ISSUE THREAD

**Issue by mingl2000** [docker/for-mac#2659]
### Expected behavior
     Similar speed as Ubuntu
### Actual behavior
   20 times slower.
    It looks 42 min to start 6 docker instances for hyper ledger fabric first network
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
As described in the issue template, please provide

- Full output of the diagnostics from "Diagnose & Feedback" in the menu
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page

Unfortunately without more information there's nothing we can do to help :(

**Comment by alexbaumgertner** [comment]
It's probably related to https://github.com/docker/for-mac/issues/2582
@mingl2000 do your containers make a lot of I/O operations?

**Comment by abdrmdn** [comment]
https://medium.com/@abidul.rmdn/a-team-of-mac-book-docker-users-amazing-solution-fe9592247d21
