### ISSUE TITLE
Parsing of key-value build args in docker-compose not working

### ISSUE THREAD

**Issue by bilow-factual** [docker/for-mac#2661]
### Expected behavior

Should be able to specify build args as key-value pairs, strings with assignment, or strings without assignment, as in: https://docs.docker.com/compose/compose-file/#args

### Actual behavior
Error below when passing build args as key-value pairs. See Dockerfile + docker-compose.yml below for more information:

`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.dev.build.args contains {"goodbye": "bye"}, which is an invalid type, it should be a string`

### Information

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/F873DA0F-6DAF-44C1-A4D4-5154F96751D5/20180304-185129.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

Here's my `docker-compose.yml`
```bash
version: '3'
services:
  dev:
    build:
      context: .
      args:
        - hello=hi
        - goodbye: bye
```

and my `Dockerfile`
```bash
FROM ubuntu
ARG hello
ARG goodbye
RUN echo $hello
RUN echo $goodbye
```

  1. `docker-compose up` yields the error above, complaining about the type of the 'goodbye' build arg.

**Comment by thaJeztah** [comment]
The build args can be _either_ provided as a _list_, or as a _mapping_; referring to the docs:


> Then specify the arguments under the build key. You can pass either a mapping or a list:
> 
> ```yaml
> build:
>   context: .
>   args:
>     buildno: 1
>     password: secret
> 
> build:
>   context: .
>   args:
>     - buildno=1
>     - password=secret
> ```
> 
> You can omit the value when specifying a build argument, in which case its value at build time is the value in the environment where Compose is running.
> 
> ```yaml
> args:
>   - buildno
>   - password
> ```


So either specify (list of strings):

```yaml
args
  - key=value
  - key2
```

Or (mapping)

```yaml
args
  key: value
```


The reason it's failing in your case is because you're trying to use a "map" (`key: value`) inside a list (starting with `- `)


Change your compose file to:

```yaml
version: '3'
services:
  dev:
    build:
      context: .
      args:
        hello: hi
        goodbye: bye
```


Or

```yaml
version: '3'
services:
  dev:
    build:
      context: .
      args:
        - hello=hi
        - goodbye=bye
```

And it should work

I'm closing this issue, because this doesn't look like a bug, but feel free to continue the conversation 👍
