### ISSUE TITLE
Docker daemon not start

### ISSUE THREAD

**Issue by chenzi** [docker/for-mac#2662]
### Expected behavior
Docker daemon  shout start

### Actual behavior

Docker daemon not start

### Information

Docker for Mac: version: 18.03.0-ce-rc1-mac54 (e22e653363ad9e0f458ab38d464ab106d30a72b2)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/BA687474-41FB-4ECA-A840-823EA98FEEC4/20180305-165433.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

### Steps to reproduce the behavior
1. download docker install files
2. install docker program

**Comment by chenzi** [comment]
<img width="500" alt="wx20180118-111724 2x" src="https://user-images.githubusercontent.com/5486633/36966637-063313ae-2023-11e8-9542-976b25dd03f5.png">

**Comment by chenzi** [comment]
<img width="225" alt="b0cd2f60-9503-469a-940e-4a2c2bf460cb" src="https://user-images.githubusercontent.com/5486633/36966713-4bff442a-2023-11e8-880f-ecdd99bc3a0f.png">

**Comment by chenzi** [comment]
I try to remove all data and rest to factory defaults is not work...

**Comment by akimd** [comment]
What is exactly your problem?  Everything you showed proves that it works.

**Comment by chenzi** [comment]
@akimd Though docker is runing but it's is gray color

**Comment by DanielSchwiperich** [comment]
It is running. the gray / transparent just indicates it's not clickable like `Repositories` and `Swarms`. This just how mac os renders such menu entries. 

You have the same for example at your Wifi menu
<img width="169" alt="screen shot 2018-03-06 at 17 04 45" src="https://user-images.githubusercontent.com/2045722/37043269-84ef32f2-2160-11e8-81c3-d65aba2cfaa2.png">

**Comment by akimd** [comment]
@DanielSchwiperich Thanks for your help!
I venture we can close this issue.
