### ISSUE TITLE
docker ps failed

### ISSUE THREAD

**Issue by SanjeevOfBcs** [docker/for-mac#267]
### Expected behavior
docker ps should have listed the containers
### Actual behavior
it doesn't return anything on the terminal
### Information

Diagnostic ID: 5CFB6B94-07FB-4B35-88ED-6F4C7AD194DB
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
Earlier it used to return the list correctly. Yesterday I forced quit docker. I guess I am not getting result after that.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in 5CFB6B94-07FB-4B35-88ED-6F4C7AD194DB/20160814-000756.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Aug 13 23:07:18 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.driver.amd64-linux][48454] <Warning>: VM: 2016-08-13 17:37:18 +0000 UTC kern.warn kernel: RDX: ffffea000007f6e0 RSI: 0000000000000042 RDI: ffffea0041070001
Aug 13 23:07:18 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.driver.amd64-linux][48454] <Warning>: VM: 2016-08-13 17:37:18 +0000 UTC kern.warn kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Aug 13 23:08:18 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.driver.amd64-linux][48454] <Error>: VM: 2016-08-13 17:38:18 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 14 00:02:27 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.driver.amd64-linux][48454] <Notice>: sending SIGTERM to com.docker.hyperkit pid 48457
Aug 14 00:03:06 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.docker][48410] <Notice>: applicationWillTerminate
Aug 14 00:03:06 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.osx.hyperkit.linux][48424] <Notice>: EOF on watchdog pipe: shutting down
Aug 14 00:03:06 SymMacToolkit-C02NKAB8G3QD Docker[com.docker.osx.hyperkit.linux][48424] <Notice>: Received SIGTERM, shutting down
```
