### ISSUE TITLE
D91313E1-FF50-46B3-8F85-DA3DD867930D

### ISSUE THREAD

**Issue by Kshitiz-1989** [docker/for-mac#2685]
### Actual behaviour
When 'mvn fabric8:build' command is executed, I get below 
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.49:build (default-cli) on project demo: I/O Error executing build for image [example/demo:snapshot-180310-203849-0595] "spring-boot":io.fabric8.maven.docker.access.DockerAccessException: Unable to pull 'fabric8/java-alpine-openjdk8-jdk:1.1.11': received unexpected HTTP status: 500 Server Error (Internal Server Error: 500) -> [Help 1]

The diagnostics of Docker For Mac shows error with Kubernetes as mentioned below:
```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.11.6 (build: 15G1611)
logs: /tmp/D91313E1-FF50-46B3-8F85-DA3DD867930D/20180310-204322.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk
Diagnostic ID - D91313E1-FF50-46B3-8F85-DA3DD867930D
```
Are these two errors connected? 

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version : Version 17.12.0-ce-mac55 (23011)

```
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ... man fabric8:build command within a maven based spring boot java project
  2. ... Click diagnose and feedback on Docker for Mac.

**Comment by pgayvallet** [comment]
Hello,

The k8s error is not related here (we just forgot to disable k8s diag when k8s is disabled)

This doesn't really look likes docker is the faulty one here. Got a 500 response from wherever the maven plugin is trying to pull the image from.

Are you able to pull the image manually (`docker pull fabric8/java-alpine-openjdk8-jdk:1.1.11`)  ?

**Comment by Kshitiz-1989** [comment]
The issues were not related. My fabric8 command executed fine after I upgraded my Java version from 1.8_112 to jdk 9. 
The docker diagnostics although shows the error. But its not an issue as this is not affecting anything and I am able to pull it manually, that works well. 
Thanks for the help.
