### ISSUE TITLE
vmnetd fails

### ISSUE THREAD

**Issue by sblepa** [docker/for-mac#2686]
I've installed the latest stable macOS version and when I ran the diagnostics the vmnetd check fails with status:
[ERROR]  vmnetd
/private/tmp/vmnetd/com.docker.vmnetd is not running

### Expected behavior
When I run diagnostics all checks should pass
### Actual behavior
The vmnetd check fails
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/60224E4B-EA9B-4001-8C59-9EAFA4EB099F/20180312-001337.tar.gz
failure: /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     vpnkit
[ERROR]  vmnetd
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk

```
 Diagnostic ID: 60224E4B-EA9B-4001-8C59-9EAFA4EB099F

### Tried solutions 
I've tried chmod 600 on the /Library/LaunchDaemons/com.docker.vmnetd.plist file and also removing it
###

P.S:
The issue is also reproducible in the edge version

**Comment by akimd** [comment]
Try to `sudo rm /var/tmp/com.docker.vmnetd.socket` and try again.  Keep us informed please.

**Comment by akimd** [comment]
@sblepa Ping!
