### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by lvnilesh** [docker/for-mac#269]
### Expected behavior

Need docker to run but

### Actual behavior

it crashes.

### Information

Diagnostic ID: D5D29120-8778-423E-84EA-186E52B31B77
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A286a)

### Steps to reproduce

1. ...
2. ...

**Comment by glynjackson** [comment]
dup of https://github.com/docker/for-mac/issues/64

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
