### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by baddooz** [docker/for-mac#2692]
### Information

Diagnostic ID: 20B9EF74-E58D-41DF-B89A-92E06A9E21E4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.13.3 (Build 17D102)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/mile/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/mile/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
The Docker for Mac version `1.12.0-a (Build 11213)` is very old and doesn't work on macOS High Sierra (10.13.*). Do you remember where you got this version from? There might be a stale link somewhere that we could correct.

Please download a recent version from the [Docker Store](https://store.docker.com/editions/community/docker-ce-desktop-mac)

Duplicate of #561
