### ISSUE TITLE
I need you help me

### ISSUE THREAD

**Issue by tony-liuql** [docker/for-mac#27]
### Information

Diagnostic ID: 9A75CADC-A905-4520-8F64-C0D1256CDC78
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         wrong Docker version: 1.9.1 (expected 1.12.0)
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by ishouvik** [comment]
Have you tried installing the latest version of Docker toolbox?

**Comment by samoht** [comment]
```
wrong Docker version: 1.9.1 (expected 1.12.0)
```

This means that you have toolbox installed. Please either remove Toolbox or be sure to run `Docker.app` again to fix your installation.
