### ISSUE TITLE
Docker fails to restart after adding an insecure registry on mac

### ISSUE THREAD

**Issue by stevef1uk** [docker/for-mac#2701]
Just upgraded to Version 17.12.0-ce-mac55 (23011) 

Trying to add 172.30.0.0/16 as insecure registry

Docker tries to restart & fails. I tried the reset to factory defaults option but that hangs

**Comment by pgayvallet** [comment]
Hello,

We have a UI bug when adding insecure registry in 17.12-X, causing the config file to contains an empty entry (this is fixed on edge)

You can edit `~/.docker/daemon.json` to remove the faulty entry from the `insecure-registries` property, then restart docker.

**Comment by ljf1239848066** [comment]
Or edit ~/.docker/daemon.json to add the registries if there is an empty string in the "registry-mirrors" tag.
