### ISSUE TITLE
They're close, but "docker.for.mac.host.*" and "docker.for.win.*" should be better

### ISSUE THREAD

**Issue by atrauzzi** [docker/for-mac#2705]
When running Docker for Windows and Docker for macOS, we get these handy aliases like `docker.for.mac.localhost`, `docker.for.mac.internal`, `docker.for.win.localhost` and `docker.for.win.internal`.

Unfortunately, when my projects are being worked on between macOS and Windows, someone has to go changing any of these host names for the specific platform they're on, despite the premise of the two being the same!  The fact that these two things that accomplish the exact same outcome are named differently is unhelpful.

Is there any way we can get a new convention like `docker.internal` and `docker.localhost`? Would it also be possible to simply have them resolve `localhost` when used on Linux which obviously doesn't have the extra layer going on?

The name of the game here is that I need my containers to have a consistent way to reference not the VM, but the actual physical hardware they're running on. Bonus points if it's a consistent IP address so that I can configure my own DNS aliases!

Moreover, would it be possible either with or without my suggested change to get all these magic hostnames documented somewhere? They seem to be rather un-googleable and largely defined by anecdotal knowledge rather than being clearly offered.

cc.
 - https://github.com/moby/moby/issues/36625
 - https://github.com/docker/for-win/issues/1855

**Comment by akimd** [comment]
In recent releases (18.03.0-ce-rc1-mac54 for instance), we provide `host.docker.internal`.  We were clearly wrong to use mac/win in the first place.

About the documentation part, you are right. we will do this.  Currently this is "documented" in the ChangeLogs :)

**Comment by atrauzzi** [comment]
Oh jeez, so I'm just late to the party then?!?  😉 

#slowpokealex

**Comment by akimd** [comment]
Done.

**Comment by devsnacks** [comment]
Great to see. This makes things a lot simpler for us. Does it work on linux too? Would be great if we could get rid of special cases in the development configuration and have a single dns for all environments (win, mac, linux).

**Comment by atrauzzi** [comment]
Yeah, the linux case is especially important.

**Comment by tenoriojuann** [comment]
Seeing an issue after upgrading, neither host.docker.internal or gateway.docker.internal resolve when making a request within the containers to a service running on the host machine. Also the old docker.for.mac.host.internal does not work.

I am running Version 18.03.0-ce-mac60 (23751)

**Comment by Dominik-K** [comment]
@tenoriojuann Can't confirm your bug (exact same version). What does `docker run --rm alpine nslookup host.docker.internal` return?

**Comment by tenoriojuann** [comment]
@Dominik-K 

The given command returns:

nslookup: can't resolve '(null)': Name does not resolve

Name:      host.docker.internal
Address 1: 192.168.65.2



My mac's IP address starts with 135.198.X.X so that 192.X.X.X is completely off

**Comment by atrauzzi** [comment]
@akimd - Any chance we can ensure this works on linux hosts as well?  Just ran on ubuntu:

```
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
ff3a5c916c92: Pull complete 
Digest: sha256:7df6db5aa61ae9480f52f0b3a06a140ab98d427f86d8d5de0bedab9b8df6b1c0
Status: Downloaded newer image for alpine:latest

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'host.docker.internal': Name does not resolve
```
