### ISSUE TITLE
DD55A039-C2E2-4BBA-A5B6-5ED7D7010034

### ISSUE THREAD

**Issue by ayyavoosuresh** [docker/for-mac#2712]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

Closing. Please reopen with proper description if issue is still present.
