### ISSUE TITLE
Latest Docker for Mac has docker-compose version not corresponding to docs

### ISSUE THREAD

**Issue by testower** [docker/for-mac#2713]
After installing latest stable version of Docker for Mac.

### Expected behavior

Acccording to your documentation in https://docs.docker.com/docker-for-mac/, under the heading "Get started with Docker for Mac", sub-heading "Check versions":

```
$ docker-compose --version
docker-compose version 1.20.0, build 8dd22a9
```

### Actual behavior

```
$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```

**Comment by pgayvallet** [comment]
Hello

The whole block from your link is actually  

```
$ docker --version
Docker version 18.03, build c97c6d6

$ docker-compose --version
docker-compose version 1.20.1, build 8dd22a9

$ docker-machine --version
docker-machine version 0.14.0, build 9ba6da9
```

So,
- On 18.03, we are shipping compose 1.20.X (the version from the doc)
- Lastest stable is 17.12, we were shipping compose 1.18.X (your versions)

Also, in the same section, you probably did read : 

> Your output may differ if you are running different versions.

Closing.
