### ISSUE TITLE
Docker for Mac ignores proxy settings

### ISSUE THREAD

**Issue by erip** [docker/for-mac#2715]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
    - impossible since I can't upload the diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior

Docker should reflect my proxy settings when they're set either manually or in the System Preferences

### Actual behavior

Docker ignores the settings

### Information

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/65F37B23-7A1F-4110-BFEA-61285F53B809/20180322-112528.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

You can also run diagnostics manually :
$ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
```

### Steps to reproduce the behavior

  1. Be behind a proxy
  2. Set HTTP and HTTPS proxy in `System Preferences -> Network -> Advanced... -> Proxies`
  3. 🐋 -> Preferences -> Proxies -> Use system proxies; Apply & Restart
  4. `docker info | grep -i proxy # HTTP Proxy: docker.for.mac.http.internal:3128, HTTPS Proxy: docker.for.mac.http.internal:3129`
  5. Get mad
  6. Regroup
  7. 🐋 -> Preferences -> Proxies -> Manual proxy configuration; Apply & Restart
  8. `docker info | grep -i proxy # HTTP Proxy: docker.for.mac.http.internal:3128, HTTPS Proxy: docker.for.mac.http.internal:3129`
  9. Get mad
  10. Try this all again with (or without) http://
  11. Get mad
  
I've also found that the proxy information doesn't propagate into containers, confirming my suspicion: 

```
$ docker run -it alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=71b470d8dfac
TERM=xterm
HOME=/root
```

**Comment by pgayvallet** [comment]
Hello,

Docker is running inside a VM. It proxy is always `docker.for.mac.http.internal:3128`, which is our vpnkit proxy, which is the one actually proxying correctly depending on the actual proxy settings from the UI.

Anyway, what is the actual issue here ?

**Comment by erip** [comment]
There are a related few issues.

- Inability to upload diagnoistics 
- Cascading x509 errors when using various tools (like k8s) resulting from this when attempting to connect to various registries
- [Incorrect documentation](https://docs.docker.com/docker-for-mac/networking/#httphttps-proxy-support)
- (Seemingly) undocumented `~/.docker/config.json` for proxy information.

A combination of updating to an edge release and adding `~/.docker/config.json` with appropriate information has "solved" this.

**Comment by stianlp** [comment]
+1

I am having similar issues. I've set a bunch of http(s)_proxy env variables. Unless I add proxy settings manually in Preferences > Proxies, Docker cannot pull images.

However, when adding proxy settings manually in Preferences > Proxies, no_proxy is not honored (I've seen others issues on this specific problem also).

I'll try updating to an edge version and adding proxy settings in ~/.docker/config.json.

**Comment by kastork** [comment]
This should still be open as there's been no effective action taken on it and it still presents in 18.06.1-ce-mac74 (26766)

**Comment by marnett** [comment]
I can confirm that this issue still exists on 18.06.1-ce-mac73 (26764). Manually adding the proxy password both as `!` and as `%21` did not result in proper functionality. Had to change the password to get password functionality. 

Please fix the issue or fix the error message.

**Comment by alvaromuir** [comment]
> I can confirm that this issue still exists on 18.06.1-ce-mac73 (26764). Manually adding the proxy password both as `!` and as `%21` did not result in proper functionality. Had to change the password to get password functionality.
> 
> Please fix the issue or fix the error message.

Same here, I usually escape my password characters with a backslash

**Comment by errodrigues** [comment]
How can we reopen this issue???

**Comment by dhanush-ai1990** [comment]
I am still facing this issue on MacOS high Sierra behind a proxy.

**Comment by ulm0** [comment]
I'm experiencing this in production servers running `18.06.1-ce` on ubuntu, had to downgrade to `17.12.1-ce`

**Comment by aseempatni** [comment]
Any updates on this? With Auto Proxy Discovery in system settings and System Proxy in docker settings, I'm not able to pull images from public docker registry.

**Comment by jonathanunderwood** [comment]
This really needs reopening, it's not resolved.

**Comment by cgironda** [comment]
Guys any update about this issue?. Any help would be deeply appreciated.

**Comment by mingz2013** [comment]
Guys any update about this issue?. Any help would be deeply appreciated. Date: 2019/05/27

**Comment by AnthonyoscarOkoth** [comment]
Any news on this?

**Comment by johnschult** [comment]
Still happening, and the problem in my case is that no matter what is set in MacOS network preferences, when using Cisco AnyConnect, it forces MacOS to use an auto-proxy config file, which seemingly Docker for Mac ignores.

**Comment by primat** [comment]
Confirmed. DO YOU TEST?

**Comment by primat** [comment]
Confirmed. Do you even test AT ALL? 

Try this: https://docs.docker.com/network/proxy/

**Comment by philipwofford** [comment]
On the bright side, this really never gets old 😂🤣

![image](https://user-images.githubusercontent.com/39059603/61130158-0fd89000-a484-11e9-8dca-cc95e43bd9a4.png)
