### ISSUE TITLE
Block/disallow --net=host (host networking) on Mac OS

### ISSUE THREAD

**Issue by vhosakot** [docker/for-mac#2716]
**Description**

https://docs.docker.com/network/network-tutorial-host/ says:
> The host networking driver only works on Linux hosts, and is not supported on Docker for Mac

`--net=host` (host networking) does not work on Mac as it is not supported on Mac. https://forums.docker.com/t/should-docker-run-net-host-work/14215 also says that `--net=host` is not supported on Mac.

Hence, `--net=host` should be blocked/disallowed on Mac and an error like `--net=host (host networking) is not supported on Mac` should be displayed if `--net=host` is used on Mac. This way, users on Mac know that `--net=host` is not supported on Mac and will not waste time debugging host networking issues on Mac.

**Steps to reproduce the issue:**
1. Run any docker container with `--net=host` (host networking) on Mac.
    ```
    docker run -d --name docker-nginx --net=host -p 80:80 nginx
    ```
2. Check if the container's port can be accessed on the Mac host.
    ```
    $ curl localhost:80
    curl: (7) Failed to connect to localhost port 80: Connection refused
    ```

**Describe the results you received:**

Not able to access the container's port on the Mac host when `--net=host` is used on Mac.

**Describe the results you expected:**
```
$ docker run -d --name docker-nginx --net=host -p 80:80 nginx
ERROR: --net=host (host networking) is not supported on Mac.
```

**Additional information you deem important:**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: QWYO:HNLA:VPRN:ZTTG:YUNW:CO37:BWYB:L4Z5:CFDY:JC3H:A6DD:RQDM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 49
 System Time: 2018-03-22T04:19:59.058199778Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

Mac OS Sierra (version 10.12.6)

**Comment by vhosakot** [comment]
Opened this issue per suggestion in https://github.com/moby/moby/issues/36666#issuecomment-375193118.

**Comment by pgayvallet** [comment]
As you probably know, on D4M, docker is running inside a VM.
So "`-net=host`  is not working" is subject to interpretation : it's working in the fact that the container uses the VM network, it's not in the fact that the VM network is not the host network.

However, in some use case, the actual behaviour is the one expected. That's why we just can't simply disable the whole option on D4D, as it would break for some of our users using it.

The solution is probably more on documentation than on blocking the option.

**Comment by vhosakot** [comment]
@pgayvallet Thanks for the info. Yes, good documentation and an example about how to access the container's port on the VM network from inside the VM on a Mac would be very helpful. The documentation could also include the step to setup port-forwarding on the Mac to the VM's port so that the container's port can be accessed directly from the Mac.

Also, can you send me the steps to access the container's port on the VM network from inside the VM on Mac? I was not able to find them online.

**Comment by jakirkham** [comment]
Looks related to issue ( https://github.com/docker/for-mac/issues/68 ).

**Comment by zhouxiangxiang** [comment]
I have spend days for debugging network issues on mac.
And now I found this issue. 
It should post some information tell user it's not supported on mac

**Comment by sregger** [comment]
> As you probably know, on D4M, docker is running inside a VM.

Had no idea this was the case until I started searching for why 

    docker --net=host

was not work. This is a confusing User Experience and should be improved. Appreciate there is room for interpretation. But common sense usage should win out. I don't think that's currently the case.

**Comment by fgarcia** [comment]
I always thought that there should be another option like `--net=host-virtual` or something like that. Then `host` would work only in Linux and `host-virtual` in non Linux environments. Failing on non supported option would encourage users to read the manual, not to explore github issues

**Comment by jumpkick** [comment]
I've probably just wasted 3 days trying to get 2 different applications (home-assistant and mythtv) that will never work without a real implementation of host network because I had guessed given that -p ports are published that the host networking should also work...

Please don't tell me host networking does work but only for the VM, host networking means binding directly to the physical network / physical NIC, the VM doesn't do that and I can't even figure out how to access the VM (docker-machine doesn't seem to do anything on OSX)...  

 I can't imagine how much time people have collectively wasted troubleshooting this!

Invoking docker with --net=host should fail with an ERROR when started from non-linux OSes.

**Comment by vhosakot** [comment]
Very happy to see this issue is helping many people! 😄

**Comment by jumpkick** [comment]
@vhosakot This issue isn't really *helping* anyone...  😉 

But anyway...  For those struggling with this problem here's something that will actually help;  I've been able to work around 'docker for mac's limitation by the following:

* uninstall 'Docker for Mac'
* install 'Docker Toolbox' for mac
* create the docker machine VM
* run this script which adds a bridged NIC to virtualbox's docker VM (https://raw.githubusercontent.com/blueimp/shell-scripts/df2eaf79ad7935bfb4b6d5834895d4912d6df4ea/bin/docker-machine-bridge.sh)
* capture the IP address by rerunning the script a second time (export CONTAINER_IP=$(docker-machine-bridge.sh))
* start containers with --net=host
* connect to the container at the IP address captured

Since using a Vbox bridged nic puts the docker-machine host VM directly on the network at it's own IP, network=host works from there at it's new IP.

**Comment by elver** [comment]
This is the most absurdly simple "bug" I've seen where fixing it should take a developer literally minutes, but nobody has done it for over half a year.

**Comment by kazzkiq** [comment]
Users should at least be warned when trying to use networking in Docker since it's capped in macOS and Windows.

At least a message like:

```
[Docker Networking]:
We detected you're fiddling with networking, but sadly it's only supported in Linux.
```

would be enough.

Also, it's 2019. Honestly, buy some macs and PCs and enforce them on your team so they actually see the issues we're having. That would do wonders for QA.

**Comment by DonGiulio** [comment]
There's indeed some lack of documentation here,

is there a way I can connect to the docker virtual machine so that I could check things before I deploy to prod (which is a Linux system)?

**Comment by kojustin** [comment]
I just wasted a day of time thinking that this worked the same that it does on Linux.

**Comment by vhosakot** [comment]
> I just wasted a day of time thinking that this worked

@kojustin Wasting just a day on this issue is very productive lol 😉

**Comment by mtlott** [comment]
And I just wasted 2 hours on this. So I guess I am more productive than the last guy.

But Really???!!???

I don't work with docker day in and out. There should be error or warning message on D4M that reminds about these nuances. My use case is usually picking up a working compose stack and bringing it locally to a Mac to make some tweaks. A little warning that says this one won't work here would have been nice.

**Comment by dave-dm** [comment]
> And I just wasted 2 hours on this. So I guess I am more productive than the last guy.
> 
> But Really???!!???
> 
> I don't work with docker day in and out. There should be error or warning message on D4M that reminds about these nuances. My use case is usually picking up a working compose stack and bringing it locally to a Mac to make some tweaks. A little warning that says this one won't work here would have been nice.

same

**Comment by danielo515** [comment]
Ok, It is very disappointing that this does not work, but I can understand it.
What it is very frustrating is to waste time thinking that the command you just launched works but in reality it does not.
At least a warning is required, please.

**Comment by Pasukaru** [comment]
I also spent a few hours on this. Once you know why, it makes sense. 

However, it should definitely throw an error and not continue without any message whatsoever, making users (including me) think the command will work.

**Comment by alex-lechner** [comment]
Can someone of the Docker core development team explain to us what the motivation behind  _"The `--network host` functionality will be exclusively for Linux"_ is? Does it make any sense in terms of UX? Is it considered best practice to release a product and have an exclusive feature for one OS only?

**Comment by danielo515** [comment]
Alex, it is not intentional, it is a OS limitation

**Comment by alex-lechner** [comment]
@danielo515 Okay, thank you for the clarification! Is there any workaround? I need to access `127.0.0.1` from the host machine during Docker build.

**Comment by bilal-fazlani** [comment]
@alex-lechner this was very helpful, but are you able to access the container now? if yes, and how?

**Comment by danielo515** [comment]
Hey, that was something I didn't know.
Maybe documentation should mention those things instead of pretending this issue does not exist.

**Comment by BKJackson** [comment]
host.docker.internal worked from me.
It was never clear how to use that, but http://host.docker.internal:10000 literally worked from within the container without having to install anything.

**Comment by cicorias** [comment]
has anyone articulated the steps as @pgayvallet alludes to and @vhosakot has asked for? I'd like to see how from the HOST to hit the container - the opposite of `host.docker.internal`

**Comment by danielo515** [comment]
Oh no, is the attack of the bots again

**Comment by disposedtrolley** [comment]
I just finished spending an afternoon and evening troubleshooting this :'(

Would've been really nice to see a warning from the CLI.

**Comment by dmead** [comment]
is there an official reason this isn't supported other than nobody has put in the time?

**Comment by allthatjazzleo** [comment]
hope someday it will support mac

**Comment by stevemao** [comment]
http://host.docker.internal:10000 doesn't work for me.

**Comment by Grafikart** [comment]
This option should throw a warning if docker is runing on a . system that doesn't support this feature. This would avoid lots of troubles. (The warning could inclure some explanation, and a link to the doc and would avoid issue like this one)

**Comment by amalmurali47** [comment]
Spent 4 hours trying to debug this shit. It should throw a warning if it's unsupported. The developer shouldn't have to rely on horoscope and stars and google for hours to find out their script isn't working because this option itself is unsupported.

**Comment by alcastic** [comment]
Not sure if this is the right place to put my question:
So, given this case, what happens with containers running on the VM of docker daemon which need consume services that host-machine has access through VPN?
Currently I have this issue and I arrived here finding out what is happening with host networking driver.

**Comment by kanhu** [comment]
As per this link you should able to use the HOST VPN from the container. 
https://docs.docker.com/docker-for-mac/networking/

**Comment by thomasbiddle** [comment]
Damn. Was hoping we'd have a solution for this by now. Walked away from my tech career for 2 years and just had some motivation to jump into some hobby projects. Was hoping to use some software that requires local network device discovery.

**Comment by Diamg** [comment]
My workaround for device discovery: use another VM with linux guest and launch dockers there.

**Comment by deftdawg** [comment]
@Diamg the workaround is called Docker Toolbox for Mac, which does exactly that, it sets up a Virtualbox VM that can be bridged to expose it's own IP

**Comment by jjmerri** [comment]
Days wasted on this. I can't believe there is no indication that this isn't supported. We probably could have cured Coronavirus with the number of man-hours wasted on this because it doesn't provide any messaging.

**Comment by rssh** [comment]
+ 3 hours

**Comment by mbilbiesi** [comment]
1 day

**Comment by shrekwang** [comment]
1 day

**Comment by CongAn** [comment]
Thank you. Find this issue in five minutes!

**Comment by rafaelkarstadidas** [comment]
> @vhosakot This issue isn't really _helping_ anyone... 😉
> 
> But anyway... For those struggling with this problem here's something that will actually help; I've been able to work around 'docker for mac's limitation by the following:
> 
> * uninstall 'Docker for Mac'
> * install 'Docker Toolbox' for mac
> * create the docker machine VM
> * run this script which adds a bridged NIC to virtualbox's docker VM (https://raw.githubusercontent.com/blueimp/shell-scripts/df2eaf79ad7935bfb4b6d5834895d4912d6df4ea/bin/docker-machine-bridge.sh)
> * capture the IP address by rerunning the script a second time (export CONTAINER_IP=$(docker-machine-bridge.sh))
> * start containers with --net=host
> * connect to the container at the IP address captured
> 
> Since using a Vbox bridged nic puts the docker-machine host VM directly on the network at it's own IP, network=host works from there at it's new IP.

yes it is impressively absurd being forced to do such thing, its unpractical to stablish a pattern for local development for a whole team, forcing everyone to comply to this right? Also docker-compose is not practical all the time, or you end up yourself building many different docker-composes, anyway its not practical way of development and testing software... docker really should do something about this, its such a simple networking issue

**Comment by vhosakot** [comment]
@rafaelkarstadidas yeah, I know this issue isn't really helping anyone lol and still got more than 100 👍s lol 🤣 🤣

**Comment by dbux** [comment]
/remove-lifecycle stale

> @vhosakot This issue isn't really _helping_ anyone... 😉
> 
> But anyway... For those struggling with this problem here's something that will actually help; I've been able to work around 'docker for mac's limitation by the following:
> 
> * uninstall 'Docker for Mac'
> * install 'Docker Toolbox' for mac
> * create the docker machine VM
> * run this script which adds a bridged NIC to virtualbox's docker VM (https://raw.githubusercontent.com/blueimp/shell-scripts/df2eaf79ad7935bfb4b6d5834895d4912d6df4ea/bin/docker-machine-bridge.sh)
> * capture the IP address by rerunning the script a second time (export CONTAINER_IP=$(docker-machine-bridge.sh))
> * start containers with --net=host
> * connect to the container at the IP address captured
> 
> Since using a Vbox bridged nic puts the docker-machine host VM directly on the network at it's own IP, network=host works from there at it's new IP.

Unfortunately this no longer seems to work in macOS Big Sur as it cannot run Docker Toolbox for Mac.

**Comment by pretzelhammer** [comment]
Also commenting to say I lost a few hours trying to debug this until I found this issue. Despite this small comment being in [the docs](https://docs.docker.com/network/network-tutorial-host/):

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

If it's not supported then passing `--network host` to the docker CLI should emit a warning or error on non-Linux hosts, it shouldn't be ignored silently, which is the current behavior.

**Comment by stefannilsson** [comment]
Fired up a container on Docker for Mac with the --net=host and had to troubleshoot for quite some time before I found it's apparently not supported.
So, I think this argument to Docker on a Mac should definetly error/warn the user (if still not possible to solve on macOS).

**Comment by mahanh** [comment]
Spent a couple of days to troubleshoot why Apache Beam doesn't connect to local Spark Job Server!
Then found out it's not supported on Mac OS to use --net=host!
docker cli should warn or even raises an error when we use this flag on any host but Linux!

**Comment by SKY3AU** [comment]
Docker for Mac on Big Sur works great and I understand it has limited networking options but not having a simple --net=host option available really lets the entire App down. Almost pointless to develop on this platform at all if you can't run simple networking modules. I hope it gets a serious look in upcoming releases.

**Comment by dmead** [comment]
I want this fixed so I stop getting notifications about it. free me from
this hell, docker.

**Comment by dionjwa** [comment]
An error or warning would be great since it confuses people in far away places: https://community.home-assistant.io/t/docker-on-mac-install-front-end-nowhere-to-be-found/5553/10

**Comment by dreamer2q** [comment]
I just kept typing `ifconfig` `ifconfig` and `ifconfig` in my container with `--net=host` ...
Cant figure out why its outputs so strange untill I found out this issue.

**Comment by dmead** [comment]
unsubscribing from this topic, because it just won't die.

**Comment by jkneer** [comment]
Please fix this.

**Comment by developedsoftware** [comment]
Have also wasted days on this! Can host networking be implemented on Mac OSX?

**Comment by haydin505** [comment]
I have wasted 2 days on this. Please fix it or log an error message.

**Comment by jmo-qap** [comment]
I also just wasted a bunch of time.

**Comment by m4heshd** [comment]
Glad to know that I cannot take the last 30 hours I wasted on this back. What is so damn difficult about adding a simple console output?

**Comment by lukeenglish** [comment]
Why is —net=host not supported on a Mac?

**Comment by FarhanSajid1** [comment]
Does this have an ETA?

**Comment by mrajancsr** [comment]
Lol.  This was raised 4 years ago.

**Comment by alexandertsukanov** [comment]
Hey, guys any response to this issue?

**Comment by dseevr** [comment]
Someone please bug bounty this.  lmao

**Comment by andbi** [comment]
You must be kidding. I've just spent hours trying to resolve this 4yo issue. Add a warning or be damned! :-)

**Comment by ajaymalikbol** [comment]
Let's target to close this issue by the End of this week 😁😁😁

**Comment by ryanmccartney** [comment]
6 hours of debugging later I've reached this issue. Add a warning for goodness sake!

**Comment by enriverd** [comment]
Thousands of people are saying they have lost hours for the lack of clarity regarding the --network=host parameter accross the Internet, and you still believe that a warning is not needed. If you guys don't see it, you are beyond helping.

**Comment by nicks** [comment]
We are researching this. stay tuned!

**Comment by jmo-qap** [comment]
@nicks on the scene! Thanks!

**Comment by danperks** [comment]
Very excited to hear there's some motion in the ocean on this! Subscribe to the thread, good luck brave devs!

**Comment by carlosbaraza** [comment]
What a sink of dev time for not implementing a warning, which would take 5 minutes to someone experienced with the docker for mac codebase... I was trapped like so many other people in this thread...

**Comment by sudoerD1** [comment]
At this point is getting comical

**Comment by shatacheruvu** [comment]
fixed all my sins all this while but this issue is still open.

**Comment by ItsTarik** [comment]
Is this a payed feature ? LOOL

**Comment by kopax-polyconseil** [comment]
Lucky to learn it now after a few days configuring a platform install. Cannot do as planned, any plan to resolve this ? :laughing:

**Comment by andbi** [comment]
During these five years I've turned 50, became a grandfather, survived COVID, and bought a house. Anyone else care to share their stories while the issue is being actively resolved? :-)

**Comment by kopax-polyconseil** [comment]
> During these five years I've turned 50, became a grandfather, survived COVID, and bought a house. Anyone else care to share their stories while the issue is being actively resolved? :-)

It took me a bit less to understand this comment is outdated: https://github.com/docker/for-mac/issues/2716#issuecomment-456233826

I have hit this error: https://forums.virtualbox.org/viewtopic.php?f=8&t=107680

```bash

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: Failed to execute '/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdpCtl add 2>&1' - exit status: 34304
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
```

So there's definitely no way now to run a container with host network ?

**Comment by fwnan** [comment]
fuck the network_mode host in wsl2

**Comment by jwoodrow** [comment]
The only way I managed to get it to work is to run docker using devcontainers which somehow makes things work out. But this is ridiculous. I understand things aren't simple and you've had to deal with a lot of mac issues what with all the Apple Silicon changes.

But it can't honestly take 5 years to either:
- add an error message on non-linux machines 
- Find a solution to make this work on macs

Docker is meant to be a solution to standardize how developers collaborate and run projects on whichever platform they want. But in reality that isn't the case because some options just won't work on other systems and rather than say so directly and reject the command you prefer to have your users rip their hair out of frustration debugging known issues.

**Comment by nicks** [comment]
Making Host OS networking work on MacOS is tracked here: https://github.com/docker/roadmap/issues/238

Blocking this with an error message is not really on the table, because there are lots of legitimate use-cases for binding to the Host VM network (rather than the Host OS network). For example, Telepresence uses --net=host and _wants_ to bind to the VM network, here's a good post on it: https://www.getambassador.io/kubernetes-learning-center/telepresence-docker-extension

There's been some discussion about making it a warning or having a way to disambiguate like --net=host-os or --net=host-vm, but there are concerns about portability.

**Comment by deftdawg** [comment]
There should've been a warning when Docker for Mac was first released.    At least the command line `docker` command should warn *something* about it, even if the Docker for Mac GUI people can't figure out how to handle it. 

Besides the 100 or so folks who've found this thread and commented, think of *all the other people* who give up trying to run a tutorial or a product installation on mac that includes `--net=host` because it appears to be **silently broken**.

It would take what to implement a warning?   An OS check (docker mac cli), a docker version check (< whatever version will eventually implement it) and a `printf`?

> Blocking this with an error message is not really on the table, because there are lots of legitimate use-cases for binding to the Host VM network (rather than the Host OS network). For example, Telepresence uses --net=host and _wants_ to bind to the VM network, here's a good post on it: https://www.getambassador.io/kubernetes-learning-center/telepresence-docker-extension
> 
> There's been some discussion about making it a warning or having a way to disambiguate like --net=host-os or --net=host-vm, but there are concerns about portability.

**Comment by disposedtrolley** [comment]
cc @davidlopezre

**Comment by ryanmccartney** [comment]
Happy 5th Birthday to this issue 🍰

**Comment by vhosakot** [comment]
yay, happy 5th Birthday all! 🍰

**Comment by pjamessteven** [comment]
Happy birthday :(

**Comment by yrik** [comment]
So, what are the workarounds for now?

**Comment by bsnk-dev** [comment]
If you want docker containers to be able to access a specific application running on say, 127.0.0.1:3000, one solution is to run a proxy inside the container to the host.docker.internal network bridge. You can do so with a utility called socat.

An example so the docker container can access 127.0.0.1:3000 on your machine:

```
apt-get update && apt-get install -y socat
socat TCP-LISTEN:3000,fork TCP:host.docker.internal:3000
```

**Comment by yafetnid** [comment]
all I have to say is: lol

**Comment by phiberber** [comment]
I'm almost sure the entire team unsubscribed from this Issue, thankfully I got to find out it doesn't work by using Docker Desktop and "lsof" seeing there was no port open, we're near the 6th birthday!

**Comment by eshaan-deepsource** [comment]
I was here.

**Comment by cristiano182** [comment]
> @danielo515Ok, obrigado pelo esclarecimento! Existe alguma solução alternativa? Preciso acessar `127.0.0.1`da máquina host durante a construção do Docker.
> 
> EDITAR: Não importa. Acabei de descobrir que você pode usar `http://host.docker.internal:<your-port>`para acessar a máquina host em vez de `http://127.0.0.1:<your-port>`durante a construção.

thank you

**Comment by akerouanton** [comment]
We added a "host networking" beta feature to Docker Desktop 4.29. You can find more details on this page: https://docs.docker.com/network/drivers/host/#docker-desktop.

Let me close this ticket as 'won't fix'.
