### ISSUE TITLE
Kubernetes on Mac is stuck very often. Needs restart all the time.

### ISSUE THREAD

**Issue by muranant** [docker/for-mac#2717]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
issue id: B9CA6ADD-C7FA-404D-84BC-C2F6D41D08C1

### Information

```
Docker for Mac: version...
CE: Version 18.03.0-ce-rc4-mac57 (23360)
Channel: edge


```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hi,

Could you explain with a little more details what exactly is happening ?

**Comment by AlexGilleran** [comment]
I'll jump on because I assume I'm seeing the same thing - this has started happening for me today after docker for mac initially working perfect with Kubernetes.

Essentially with any decent-sized workload Kubernetes will just stop responding (helm and kubectl just timeout if you try to do anything with them however simple). E.g.

```
kubectl get pods
Unable to connect to the server: unexpected EOF
```
or 
```
>kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```

It comes back after you restart, or if you wait like 15 minutes or so. However usually in both cases it'll stop responding again a few minutes after that.

I can pretty reliably reproduce this if I try to install any reasonably-sized workload with helm - e.g. an elasticsearch setup with multiple data and master nodes. I'm seeing it with the elasticsearch workload in https://github.com/TerriaJS/magda, but it's pretty much the same as https://github.com/pires/kubernetes-elasticsearch-cluster in that respect.

Diagnostic ID: 5F442AE0-2758-4A8C-94A8-42FF18261D4B
```
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
```

**Comment by AlexGilleran** [comment]
... actually having switched to minikube I'm seeing the same issues with the same workload, so this might not be anything specific to do with docker for mac.

**Comment by muranant** [comment]
I think it has to do with the resource available for the workload. When I
keep the workload low, it is stable.

**Comment by jpswade** [comment]
I also have the same issue:

```
$ kubectl cluster-info
Kubernetes master is running at https://localhost:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF

$ kubectl cluster-info dump
Unable to connect to the server: EOF
```

**Comment by leapingbytes** [comment]
Same problem... I have 18 services in my stack, pretty much all of them tomcat:apline + my WAR... works without any problems when I run 12 of them... but if I try to run all 18, after a very short while, `kubectl` stop responding... getting `Unable to connect to the server: net/http: TLS handshake timeout`... `minikube dashboard` does not work either... getting 
```
minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://192.168.64.16:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: net/http: TLS handshake timeout
```
and `hyperkit` process CPU consumption goes through the roof 

I m  running latest version of everything...

```
minikube version
minikube version: v0.28.0
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server 192.168.64.16:8443 was refused - did you specify the right host or port?
```
my minikube cluster was created:
```
minikube start --vm-driver hyperkit --cpus 8 --memory 8096  --disk-size 100g
```

This is extremely annoying... I know for the fact that I can run the same stack using docker-composer without any problems... 

Any advice would be highly appreciated.

**Comment by yuukiii** [comment]
I have the same issue
`kubectl get pods
Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout`

**Comment by yuukiii** [comment]
I just fixed it by upgrading homebrew.
Run: `brew update && brew upgrade`
Then to upgrade minikube run:
`brew cask reinstall minikube`

**Comment by jbenetti10** [comment]
I am seeing the same EOF errors when running kubectl commands against Kubernetes for Docker.  It will recover, when I restart Docker, for some amount of time.  I reinstalled Docker last week hoping it was an issue with my installation.

Diagnostic ID:  CB270843-2273-4006-82C9-894CA37B3075/20181001185705

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by kalexmills** [comment]
I am seeing the same issue with a not-very-large deployment which is running one tomcat container, a few microservices, an LDAP server, and MySQL. After a short while with all of these guys running, the ingress controller begins crashing and kubectl becomes unresponsive.

Our initial use-case for docker-for-mac/kubernetes is to simplify the set up of new local dev environments. However if the current implementation is unstable even on medium-sized deployments, it seems like it might save some headache just to go with a remote dev cluster instead... this would certainly improve dev/prod parity, in any case.

One final note. The issue only began showing up for me once I deployed my first multi-container pod. I wonder if this might be a clue, or just a coincidence.

**Comment by Vishdock** [comment]
Same problem for me.  I am on macbook pro running High Sierra. I first thought this started happening  after I upgraded minikube to 0.30.0. But no, I went back to 0.29.0 and the whole thing suddenly stalls.

I am running a few pods with kafka images (2 replicas each for kafka and zook) and a couple of tomcats for kafka producer / consumer testing.

Only a few minutes of uptime and then this happens:
$ mk dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://192.168.203.158:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: dial tcp 192.168.203.158:8443: connect: connection refused

Or, 

$ kubectl exec -it kafka-0 -- /bin/bash
Unable to connect to the server: net/http: TLS handshake timeout

Or,

$ kc get service
Unable to connect to the server: unexpected EOF

and so on. Then I stop the minikube and restart it, it takes a few minutes to come up, and then a few minutes later again the same story... 

What is going on? Can someone throw some light please?

**Comment by jbenetti10** [comment]
This might be a networking issue.  I noticed that when my Docker is in this state, docker build fails because the build is unable to access remote resources (NuGet).

**Comment by kalexmills** [comment]
Everytime I have seen unexpected EOF the solution for me has been to reboot Docker for Mac and (if that fails to resolve it) reset the Kubernetes cluster.

But I am a bit confused, you mentioned minikube, but this is the Docker for Desktop (mac version) issue tracker. Does it use k8s behind the scenes?

**Comment by Vishdock** [comment]
@kalexmills, I am using minikube running on VMWare Fusion on my mac to deploy my containers into kube cluster that I created locally... if that makes it clear. Regarding your first suggestion, rebooting the docker and reseting the kube cluster (and rebooting my mac itself to clean out the VMWare fusion) all I have tried. It just happens every time - just in 5-10 minutes of my kube cluster coming up and running. Then I repeat the whole cycle... It is kind of frustrating. :-(

**Comment by kalexmills** [comment]
@vishdock you might try the minikube repo for support.

iirc when I tried setting up minikube it was difficult. I found Docker for Mac to be a much easier way to achieve local k8s development. ymmv

**Comment by Vishdock** [comment]
That is very interesting... I am seeing this post here: https://github.com/docker/for-mac/issues/2717 
This user moved from dock for mac to minikube and describing the same problem. So doesn;t look like a minikube issue? It may be resources...

**Comment by atombender** [comment]
Check your disk space. I've been getting this today — the API server abruptly stops responding, and all `kubectl` invocations fail with `Unable to connect to the server: EOF`. Just before this happens, I get a lot of evictions, and `kubectl get events` reports stuff like this:

```
11m         11m          1         slash-84f765689-trvrh.155f23dca4fb453a                                             Pod          spec.containers{slash}                      Normal    Created                 kubelet, docker-for-desktop   Created container
11m         11m          1         slash-84f765689-trvrh.155f23dcb7cc89b1                                             Pod          spec.containers{slash}                      Normal    Started                 kubelet, docker-for-desktop   Started container
9m          9m           1         slash-84f765689-trvrh.155f23f34fba4c01                                             Pod                                                      Warning   Evicted                 kubelet, docker-for-desktop   The node was low on resource: imagefs.
9m          9m           1         slash-84f765689-trvrh.155f23f35c4c1b64                                             Pod          spec.containers{slash}                      Normal    Killing                 kubelet, docker-for-desktop   Killing container with id docker://slash:Need to kill Pod
```

Note the error: `The node was low on resource: imagefs`. Increasing the VM image size (under Preferences) seems to have solved it.

**Comment by benjamin658** [comment]
I try to increase the Docker available Memory from 2GB to 8GB, and Swap from 1GB to 4GB, and it seems better now...
<img width="530" alt="2018-11-01 4 44 03" src="https://user-images.githubusercontent.com/4233028/47844842-645c4380-ddfe-11e8-84b2-edbe7f491d5a.png">

**Comment by kalexmills** [comment]
@benjamin658 this solved the problem for me.

**Comment by karumgua** [comment]
@benjamin658 after searching the forums for half a day, your fix is what helped me to. The errors weren't very informative except, 
`The connection to the server localhost:6443 was refused - did you specify the right host or port?`
It was very frustrating, to say the least. 

Increasing the Docker available memory to 8 Gb did it. Thank You.
