### ISSUE TITLE
Docker starts but Kubernetes does not

### ISSUE THREAD

**Issue by ravipinto** [docker/for-mac#2718]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge) - Edge
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue - BA9D2AD7-02B8-46A4-A3FC-254D93ED8907

### Expected behavior
Docker should start and Kubernetes should start

### Actual behavior
Docker starts but Kubernetes does not

### Information

```
Docker for Mac: version: 18.03.0-ce-rc4-mac57 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/BA9D2AD7-02B8-46A4-A3FC-254D93ED8907/20180323-065324.tar.gz
[20180323-065324.tar.gz](https://github.com/docker/for-mac/files/1839946/20180323-065324.tar.gz)

[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior
Nothing to reproduce since K8s is not starting.
Please note the K8s context has already been set to "docker-for-desktop"
The status is stuck on "Kubernetes starting"

**Comment by guillaumerose** [comment]
I can see in your logs that in the VM everything is fine but we fail to expose the apiserver port on the host.  

```
2018-03-22 09:35:09.485511+0530  localhost com.docker.supervisor[58205]: com.docker.driver.amd64-linux: stderr: 2018/03/22 09:35:09 Expose tcp:0.0.0.0:6443:tcp:192.168.65.3:6443
2018-03-22 09:35:09.485633+0530  localhost com.docker.supervisor[58205]: com.docker.driver.amd64-linux: stderr: 2018/03/22 09:35:09 Failed to walk to [tcp:0.0.0.0:6443:tcp:192.168.65.3:6443] 9p: file not found
2018-03-22 09:35:09.486664+0530  localhost com.docker.supervisor[58205]: com.docker.driver.amd64-linux: stderr: 2018/03/22 09:35:09 Expose tcp:0.0.0.0:6443:tcp:192.168.65.3:6443: succeeded with tcp:0.0.0.0:6443:tcp:192.168.65.3:6443
```

```
2018-03-22 16:10:27.190337+0530  localhost com.docker.driver.amd64-linux[69074]: Node status error: Get https://localhost:6443/api/v1/nodes: dial tcp: lookup localhost: no such host
```

Do you have a specific configuration for localhost ? What's the output of `nslookup localhost` and your /etc/hosts file ?

cc @djs55

**Comment by ravipinto** [comment]
Hi @guillaumerose, sorry for delay on responding to the thread. My /etc/hosts was indeed empty (not sure if it is standard MacOS feature?! I have since upgraded to latest Edge release (apart from fixing hosts file) and now docker + k8s is working fine.

**Comment by ravipinto** [comment]
Closing the issue, since this is now resolved

**Comment by abdennour** [comment]
I fixed it.

# Brief

Add the following lines in `/etc/hosts`.

```
127.0.0.1 localhost
::1       localhost
```

# Details:
1. Display the [log of docker](https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs):

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

2. Analyze the log: 
Found
```
2018-11-30 08:33:37.468984+0300  localhost com.docker.driver.amd64-linux[38047]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: dial tcp: lookup localhost: no such host
```
It means, it cannot resolve `localhost` ???!!

3. Check `/etc/hosts`

Oops! it is empty. 

4. Remediation

```
# cat /etc/hosts

127.0.0.1 localhost
::1       localhost
 ```

5. Watch the log again:

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

🎉 It works. k8s is now up and running with docker-for-mac.
