### ISSUE TITLE
Docker for Mac: Kubernetes stuck at "Kubernetes starting..." (18FAB5DC-FAEE-40A4-8802-3D8BEE7DDA42)

### ISSUE THREAD

**Issue by kari-sutelapp** [docker/for-mac#2720]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue: 18FAB5DC-FAEE-40A4-8802-3D8BEE7DDA42

### Expected behavior

Enabling Kubernetes starts Kubernetes.  Docker icon shows Kubernetes is running

### Actual behavior

Kubernetes remains in "Kubernetes starting..." state.  
[20180323-140055.tar.gz](https://github.com/docker/for-mac/files/1841414/20180323-140055.tar.gz)

### Information

Docker for Mac: version: 18.03.0-ce-rc4-mac57 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/18FAB5DC-FAEE-40A4-8802-3D8BEE7DDA42/20180323-140055.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

from the kubelet container logs, the cluster seems to be correctly started 

```
I0323 11:56:13.580960    1093 kubelet_node_status.go:82] Attempting to register node docker-for-desktop
I0323 11:56:17.599187    1093 kubelet_node_status.go:127] Node docker-for-desktop was previously registered
I0323 11:56:17.599209    1093 kubelet_node_status.go:85] Successfully registered node docker-for-desktop
```

but the socket connection to retrieve the configuration faills

```
2018-03-23 13:46:50.560665+0200  localhost com.docker.driver.amd64-linux[28190]: Failed to update the host kube config: Post http://unix/init: EOF
2018-03-23 13:46:50.560702+0200  localhost com.docker.driver.amd64-linux[28190]: Error while setting up kubernetes: Post http://unix/init: EOF. Retrying in 1s
```

and I got no log from the process actually listening on this socket on the vm side (not even init logs), it's like it failed silently.

Was this an upgrade ? has it been working for the previous version ?

**Comment by xiaods** [comment]
any update for this issue. based in beijing. 
<img width="501" alt="2018-04-27 4 04 17" src="https://user-images.githubusercontent.com/37678/39351750-14b23cca-4a35-11e8-8dab-639fa26bfcce.png">

**Comment by nrser** [comment]
I'm seeing this same issue. Things were working fine for me on `18.03.0-ce-mac58 (23607)`, then I upgraded *I think* to `Docker 18.05.0-ce-rc1-mac63` and Kuber wouldn't start, as well as a 10-20 second beach ball when I would click the Docker for Mac menu tray icon that would lock my keyboard focus.

I downgraded back to `18.03.0-ce-mac58 (23607)` 'cause I still had the `.dmg` and I'm still having trouble getting Kubernetes to start, though I can click the Docker for Mac tray icon now without getting that beach ball.

@xiaods I'm also in Beijing. When Kubernetes starts the first time it downloads a ton of stuff from Google domains. You need to have a network connection that can access those domains. If seems like if it can't reach those domains it just hangs and doesn't say anything. This took me a little bit to figure out.

It also seems like you want to have your networking set up to be able to access Google domains *before* you start Docker for Mac / Kubernetes - if I switch my network routing while Kubernetes is trying to start it doesn't seem to pick up the changes.

This makes me think that maybe part of my problem was Docker for Mac starting at login and never picking up the network routing changes after that?

**Comment by nrser** [comment]
Update - Docker for Mac says Kubernetes is up and running!

@xiaods - what worked for me:

1.  Make sure you can access domains like `storage.googleapis.com` and `gcr.io` *before* you start Docker for Mac.
2.  When you start Docker for Mac (and enable Kubernetes) it should go into "starting" state. You should see a large amount of download traffic on your network interface and some logs (though not many) like `HTTP proxy --> 74.125.197.82:443 Host:gcr.io:443 (Origin): CONNECT` in the Console app.
3.  If the download traffic stops for a prolonged period restart Docker for Mac and it should start back up.
4.  I had to restart Docker for Mac several times. Kubernetes can take a **long** time to finish setting up, probably 2-3 hours.

**Comment by xiaods** [comment]
hi docker for mac team, could you please provide http://hub.docker.com/ domain to replace google and gcr.io domain. it always blocks in china network.

**Comment by ximenpo** [comment]
docker/kube-compose-api-server
docker/kube-compose-controller 
gcr.io/google_containers/etcd-amd64
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64 
gcr.io/google_containers/k8s-dns-kube-dns-amd64
gcr.io/google_containers/k8s-dns-sidecar-amd64
gcr.io/google_containers/kube-apiserver-amd64
gcr.io/google_containers/kube-controller-manager-amd64
gcr.io/google_containers/kube-proxy-amd64
gcr.io/google_containers/kube-scheduler-amd64
gcr.io/google_containers/pause-amd64

**Comment by YoungHu** [comment]
for china network we need use vpn to speed the kubernetes download. I use shadowsocks for proxy and set it at the proxies card, then restart the docker for mac. then the download speed become faster.
![1529585418346](https://user-images.githubusercontent.com/7418602/41720200-e34557f4-7594-11e8-9fc7-ebfd93f18a53.jpg)

**Comment by YoungHu** [comment]
for china network we need use vpn to speed the kubernetes download. I use shadowsocks for proxy and set it at the proxies card, then restart the docker for mac. then the download speed become faster.
![image](https://user-images.githubusercontent.com/7418602/41720364-6a39a846-7595-11e8-98fa-27fb830a231f.png)

**Comment by deepybee** [comment]
I solved this by spawning a new disk image as described in my comment on #2985.

Hopefully that helps people here also.

**Comment by YoungHu** [comment]
@deepybee that is work for me, thanks

**Comment by ralf0131** [comment]
@YoungHu I followed your comments, and it did work for me.

Additional comments: If you are using shadowsocks, you have enable a http proxy before your shadowsocks proxy. See this [blog](https://v2mm.tech/topic/320/%E5%B0%86socks%E4%BB%A3%E7%90%86-shadowsocks-%E8%BD%AC%E6%8D%A2%E4%B8%BAhttp%E4%BB%A3%E7%90%86) for more details.

**Comment by jingslunt** [comment]
china：
gcr.mirrors.ustc.edu.cn
quay.mirrors.ustc.edu.cn

**Comment by leizongmin** [comment]
I just met the same problem. If your are using Shadowsocks, set to Global Proxy Mode, it works for me.

**Comment by deepybee** [comment]
Still seeing this on more recent edge releases.

**Comment by yexushiran** [comment]
Minor tips: for those who are in China and use Shadowsocks as VPN, you may need to reset to factory default and configure proxy before enabling Kubernates, otherwise the proxy setting seems no effect even quit and restart Docker Desktop.

**Comment by Walther** [comment]
Confirming this bug on
- Docker Desktop Community, Version 2.0.0.2 (30215) Channel: stable 0b030e17ca
- Engine: 18.09.1
- Kubernetes: v1.10.11
- macOS Mojave 10.14.2 (18C54)

I'm on a fast network connection, so downloading assets shouldn't be a factor. I can access storage.googleapis.com and gcr.io, and I'm not using a proxy.

<img width="612" alt="screen shot 2019-01-29 at 10 56 32" src="https://user-images.githubusercontent.com/2943750/51932717-9147d480-23b4-11e9-9287-a8b12de67fbf.png">

Let me know if I can help by providing more information.

**Comment by dataich** [comment]
It's stack on my env too

**Comment by dataich** [comment]
`Reset Kubernetes cluster` solved this problem for me.

**Comment by wheelq** [comment]
still the same, even after 'Reset Kubernetes cluster'

**Comment by jp-gorman** [comment]
On docker for Mac and I've had this on Edge and on Stable. I've wiped all, reset all disks, kubernetes, factory reset, changed DNS, localhost settings checked the access to used domains by kubernetes...etc.etc.

The odd thing is that it appeared to come up for a few minutes one time and I installed Helm and it installed a chart, then the whole thing happened all over again with no changes - Spurious Quality. Logs continue to show API server is not loading as nmap shows no 6443 port running and continued "EOF" error on requests. TLS handshake issues also appear.

Looks to me like API server is failing to bring up secure service port erhaps due to TLS error...

**Comment by BrunoWinck** [comment]
same here, in France

**Comment by xie905528463** [comment]
> I just met the same problem. If your are using Shadowsocks, set to Global Proxy Mode, it works for me.

hello, Shadowsocks is  setted  to Global Proxy Mode,but no work,  do you know the others method?

**Comment by xie905528463** [comment]
> I just met the same problem. If your are using Shadowsocks, set to Global Proxy Mode, it works for me.

hello, Shadowsocks is setted to Global Proxy Mode,but no work, do you know others method?

**Comment by juanjoDiaz** [comment]
Having the same problem.

**Comment by sh00tg0a1** [comment]
Same in Germany

**Comment by fourirakbar** [comment]
same in indonesia
