### ISSUE TITLE
Docker for Mac + PHP + xdebug + Laravel Eloquent greatly degrades performance

### ISSUE THREAD

**Issue by sinbino** [docker/for-mac#2722]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
Similar performance in all environments. 
Acceptable performance degradation of PHP xdebug.

### Actual behavior
Laravel Eloquent's query greatly degrades performance only when Docker for Mac and PHP and xdebug are combined.
This happens without using shared folders.
This happens even if xdebug is disabled in php configuration, if xdebug.so is loaded.

Database query test of 50000 rows at Laravel Eloquent

Docker for Mac
　WITHOUT xdebug - 0.284 seconds
　WITH xdebug - 8.596 seconds

Docker on VirtualBox CentOS7 Guest on MacOS Host
　WITHOUT xdebug - 0.286 seconds
　WITH xdebug - 1.604 seconds

Docker on Google Compute Engine Container-Optimized OS 64
　WITHOUT xdebug - 0.712 seconds
　WITH xdebug - 2.497 seconds

In my survey two methods seem to consume most of the time.
newInstance method - [Illuminate/Database/Eloquent/Model.php](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Model.php)  
fireModelEvent method - [Illuminate/Database/Eloquent/Concerns/HasEvents.php](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php)

### Information

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/16C255DF-4CE2-4FE6-9EAB-889F88F2765E/20180326-100240.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

I have created a test project that simplifies the problem to reproduce.

  1. git clone git@github.com:sinbino/docker-for-mac-xdebug-issue.git
  2. run script run_test.sh

**Comment by pgayvallet** [comment]
Hello,

First of all, thanks for the reproduction scenario.

Just tried on latest stable (18.03.0), with 4 cpus, 2gig ram and 1gig swap, and got : 

```
docker run --rm issue-without-xdebug
50000 object readed.
time=0.32847905158997
```

```
docker run --rm issue-with-xdebug
50000 object readed.
time=1.4905250072479
```

Which seems normal compared to your other benchs

Could you pick the last stable and try it ?

**Comment by sinbino** [comment]
I updated docker to 18.03.0-ce-mac59 and tried the test.
Performance is good.
Thank you!

**Comment by sinbino** [comment]
This issue recurred in 18.03.0-ce-mac59.
Performance degradation ceased when docker was restarted.
This issue seems not to be solved by upgrading docker.
The cause of this issue seems to be long-term continuous operation of docker.

**Comment by Mult1Hunter** [comment]
Hello there! Did you find any viable solution for performance issues? I found couple of tips online, will try to implement them tomorrow. In my case, artisan command in php bash takes almost 30 seconds, which is ridiculous.
