### ISSUE TITLE
docker container is not reachable after 12 hours

### ISSUE THREAD

**Issue by nancyyaweili** [docker/for-mac#2725]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - I have tried with the latest version of my channel (Stable or Edge)
  - I have submitted Diagnostics
  - I have included the Diagnostics ID in this Issue: 851419AD-D016-4EA3-81F5-C774844CFA2F

### Expected behavior
Able to log onto docker container by `docker exec -it container bash`

### Actual behavior
no response from the docker exec command. 

I used to be able to run docker container for weeks but after the recent upgrade from probably a few weeks ago, I have to restart docker/laptop every 2 or 3 days. And this time, the container is only up by 12 hours and the container is not reachable again. 

 I can't do `docker exec -it container bash` to log onto the container but the web server hosted by the container seems to be working fine. 

### Information

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/851419AD-D016-4EA3-81F5-C774844CFA2F/20180326-215813.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior

 The issues happens fair often nowadays, probably every 2 or 3 days after docker is started.

**Comment by akimd** [comment]
Hi!  We just released a new Stable version, could you give it a try?

**Comment by nancyyaweili** [comment]
Sorry my mistake. I'm installing latest version now and will the test this behavior.
