### ISSUE TITLE
Volumes mounted readonly can be written to

### ISSUE THREAD

**Issue by platy** [docker/for-mac#2726]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Expected behavior
Readonly volumes cannot be written to by containers

### Actual behavior
I can create and delete files on volumes mounted readonly

### Information

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/D5ABA745-AB71-41B6-B51E-06B332DE756E/20180326-163342.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[OK]     osxfs
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Start a container and mount the filesytem readonly
```
docker run --rm -it -v /:/hostroot:ro alpine sh
```
  2. Create and delete files (eg. in `/hostroot/Users` which is mounted by default)

**Comment by pgayvallet** [comment]
Hi,

Tested on latest stable,

```
$ docker run --rm -it -v /Users/docker:/hostroot:ro alpine sh
$ touch /hostroot/dummy
touch: /hostroot/dummy: Read-only file system
```

Seems to be working just fine. Are you modifying from the host side ? If so, this is the expected behaviour to see the modifications inside the container.

**Comment by platy** [comment]
I did a little more testing and I was only able to write if I mount root into the container, and then write into a directory shared from macos such as my home directory or /tmp:

```
  $ docker run --rm -it -v /Users/macbook13:/hostroot:ro alpine touch /hostroot/dummy
touch: /hostroot/dummy: Read-only file system
  $ docker run --rm -it -v /Users:/hostroot:ro alpine touch /hostroot/macbook13/dummy
touch: /hostroot/macbook13/dummy: Read-only file system
  $ docker run --rm -it -v /:/hostroot:ro alpine touch /hostroot/Users/macbook13/dummy
  $ ls -l dummy 
-rw-r--r--  1 macbook13  staff  0 Mar 27 12:01 dummy
```
`macbook13` is my username
