### ISSUE TITLE
Docker for Mac

### ISSUE THREAD

**Issue by YRM64** [docker/for-mac#2729]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
dupe of #2730 i guess, closing
