### ISSUE TITLE
I'm not able to run docker ps and docker image , they hang up !

### ISSUE THREAD

**Issue by yoogodong** [docker/for-mac#273]
### Information

Diagnostic ID: 2D062CEB-FD03-44D8-BA23-B4525E1300AF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by glynjackson** [comment]
could be related to https://github.com/docker/for-mac/issues/64

**Comment by dsheets** [comment]
This issue is not related to #64 as it occurs on OS X 10.11.6.

**Comment by mchiang0610** [comment]
Merging with #119
