### ISSUE TITLE
Docker/ for Mac

### ISSUE THREAD

**Issue by YRM64** [docker/for-mac#2730]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by YRM64** [comment]
I've read previous and similar issues filed with Github; especially with regards to the issue tagged #2727.  My issue is very similar but not exactly.

Expected Behavior:  that Docker for Mac (version 17.12.0) would complete the download process and operate as designed to do so.

Actual Behavior:  Docker for Mac never opened up, providing a Docker Menu, preferences, updates, diagnose and feedback, about Docker, Docker Store, etc.

Information:  Diagnostic ID#: 880A8FA1-D109-4112-B979-CC09EC2B7830
                       Docker-for-Mac:  Version 17.12.0-ce-mac55    (18467c0ae7afb7a736e304f991ccc1a61d67a4ab).
MacOs:  version 10.12.6 (build: 16G1114)
logs: /tmp/880A8FA1-D109-4112-B979-CC09EC2B7830/20180326-132818.tar.gz
Failure:  com.docker.vpnkit is not running
[ERROR] vpnkit
   Unexpected error ((Failure "Error connecting socket to 9p endpoint unix:/Users/yvonnemcginnis/Library/Containers/com.docker.docker.Data/s51:
Unix.Unix_error(Unix.ECONNREFUSED, \"connect\",\"\")) connecting to /Users/yvonnemcginnis/Library/Containers/com.docker.docker/Data/s51
com.docker.vpnkit is not running vpnkit check failed with:  Unix.Unix_error(Unix.ECONNREFUSED, "connect","")
[OK] vmnetd
[OK] dns
[ERROR]  driver.amd64-linux
    com.docker.driver.amd64-linux
 [OK] App
[OK]  virtualization VT-X
[OK]  Moby
[OK]  System
[OK]  Moby-syslog
[OK]  Kubernetes
[OK]  Env
[OK]  Virtualization kern.hv_support
[OK]  Moby-console
[ERROR]  osxfs
   com.docker.osxfs is not running
[OK] logs
[ERROR]. docker-cli
   Connection refused (ECONNREFUSED)
connecting to /var/run/docker.sock: check if service is running.
   Connection refused (ECONNREFUSED) connecting to /Users/yvonnemcginnis/Library/Containers/com.docker.docker/Data/s60: check if service is running.
   docker ps failed
[OK]  disk
Steps to Reproduce Behavior:
1.  Docker- (17.12) for-Mac was installed on 3 separate occasions, and each time the reproduced behavior was consistent.  Docker-for-Mac never opened up but once for a matter of a couple of seconds; then closed and never opened back up again. No announcements about an 18.03 updated version, however, I had read that there was such a version.  Not sure whether updating to the newer version would actually solve the problem.
2.  Click the download for Docker-for-Mac (17.12.0) and follow the installation instructions.  No opening of Docker Menu Bar, no Docker Engine, no Docker CLI, no Docker-Machine, no Kitematic, and no Docker-Compose.  I don't have access to a diagnose and feedback menu to begin a communicative dialogue with Docker Team for MacOs (as I read on Git-hub's troubleshooting steps to take).

Respectfully,

Yvonne R. McGinnis
"The Purple Rose"

**Comment by gtardif** [comment]
Your `settings.json` file (in ~/Library/Group Containers/group.com.docker/) seems incomplete, either it has been modified manually or existed from a much older version ? 
You can try to quit Docker for Mac, remove this file and restart Docker for Mac. 
Otherwise you might need to Reset to factory defaults or uninstall / reinstall. 
I don't understand " I don't have access to a diagnose and feedback menu" : how did you manage to upload diagnostics that are shown above ?

**Comment by YRM64** [comment]
I conducted a diagnostic test and upload results.  The diagnostics you see above are the results of that testing/diagnostics.  Thanks gtardif.  I will try this approach.
