### ISSUE TITLE
Command-line access to docker preferences

### ISSUE THREAD

**Issue by estahn** [docker/for-mac#2733]
We install docker for mac via brew. We also install our internal dev toolkit via brew. As part of this process, we would like to add "`/usr/local/Cellar/<our tool>`" to the "File Sharing" section. 

### Expected behavior
Expose some way to configure preferences via CLI.

### Actual behavior
Functionality not available.

### References
* https://forums.docker.com/t/command-line-access-to-docker-preferences/40544

**Comment by pgayvallet** [comment]
Hello,

We are not providing a command-line tool to edit the configuration.

However, you can manually edit the config file (`~/Library/Group\ Containers/group.com.docker/settings.json`) and then restart the app to apply the changes

**Comment by jurgenweber** [comment]
is there a way you can 'apply' without restarting from the CLI?
