### ISSUE TITLE
Parameter for Docker Daemon 'dns-opt' is different to documentation

### ISSUE THREAD

**Issue by TristanPeers** [docker/for-mac#2734]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Expected behavior
Parameter is the same name as the documentation -> `dns-opt` ( https://docs.docker.com/engine/reference/commandline/dockerd/ )
### Actual behavior
In Mac Docker, parameter is actually named `dns-opts`
### Information

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1212)
```
  - Page URL if this is a docs issue or the name of a man page
  https://docs.docker.com/engine/reference/commandline/dockerd/

### Steps to reproduce the behavior

  1. Open preferences, click 'Daemon', 'Advanced'
  2. Try to add `"dns-opt" : [],` to json:

![screen shot 2018-03-27 at 08 50 22](https://user-images.githubusercontent.com/9379533/37953845-f8a8ff98-319b-11e8-85ec-c505bd790536.png)

3. Change it to `dns-opts` works:

  
![screen shot 2018-03-27 at 08 50 35](https://user-images.githubusercontent.com/9379533/37953900-18b9f8fa-319c-11e8-9355-f8bf8d05f1de.png)

**Comment by pgayvallet** [comment]
Hello,

You are looking at the command line arguments, not the setting file options.

On the same page you linked (https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file):

```json
This is a full example of the allowed configuration options on Linux:

{
	"authorization-plugins": [],
	"data-root": "",
	"dns": [],
	"dns-opts": [], // <--- right here.
}
```

Closing

**Comment by TristanPeers** [comment]
Oops - sorry, I need another coffee.
