### ISSUE TITLE
618994A5-CED9-4941-AD39-AC8F4B56685A

### ISSUE THREAD

**Issue by saurabh1312** [docker/for-mac#2735]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hello,

Closing. Please reopen with a proper description if necessary.
