### ISSUE TITLE
how can I change the hostname of docker daemon

### ISSUE THREAD

**Issue by lawrsp** [docker/for-mac#2736]
I am trying to test swarm mode between mac's , and found, all the node's hostname is 

```
linuxkit-025000000001
```

Could I config this ?

**Comment by guillaumerose** [comment]
You can't configure this at the moment. Sorry.

Perhaps you can run after the VM is started:
`docker run -it --privileged --pid=host justincormack/nsenter1 /bin/sh -c "hostname foobar"`

**Comment by lawrsp** [comment]
OK, it works, thanks
