### ISSUE TITLE
docker cli commands are hanging indefinitely after upgrading to 18.03.0-ce-mac59 (23608)

### ISSUE THREAD

**Issue by agis** [docker/for-mac#2737]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior

Commands like `docker (ps|image|build|etc.)` should run successfully.

### Actual behavior

Commands are hanging. After about 2mins. they do not produce any output.

Even a plain `docker` is hanging.

### Information

This happened after I upgraded to the latest stable (18.03.0-ce-mac59 (23608)).

Diagnostics ID: A452BAB2-959E-4B64-A4A4-DC80CC294F40

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/A452BAB2-959E-4B64-A4A4-DC80CC294F40/20180327-130009.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk
```

Tracing the process shows the following:

```
# ...
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
sigreturn(0xC420009F48, 0x1E, 0x0)               = 0 Err#-2
sigreturn(0xC420009F48, 0x1E, 0x0)               = 0 Err#-2
sigreturn(0xC420009F48, 0x1E, 0x0)               = 0 Err#-2
gettimeofday(0xC42049AEC8, 0x0, 0x0)             = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x7FFEEFBFF7E8)               = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
gettimeofday(0xC42049AEC8, 0x0, 0x0)             = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x7FFEEFBFF7E8)               = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
sigreturn(0xC420009F48, 0x1E, 0x0)               = 0 Err#-2
gettimeofday(0xC42049AEC8, 0x0, 0x0)             = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
kevent(0x4, 0x0, 0x0)            = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
gettimeofday(0xC42049A520, 0x0, 0x0)             = 0 0
kevent(0x4, 0x0, 0x0)            = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000830CDC0)               = 0 0
```

It seems that FD 0 is polled indefinitely. However, fd 0 seems to be the wrong FD to poll:

```
COMMAND  PID USER   FD     TYPE             DEVICE   SIZE/OFF       NODE NAME
docker  1785 root  cwd      DIR                1,4       1056 8594800788 [REDACTED]
docker  1785 root  txt      REG                1,4   38267536 8595012550 /Applications/Docker.app/Contents/Resources/bin/docker
docker  1785 root  txt      REG                1,4     837248 8592376464 /usr/lib/dyld
docker  1785 root  txt      REG                1,4 1156890624 8593228790 /private/var/db/dyld/dyld_shared_cache_x86_64h
docker  1785 root    0u     CHR               16,9   0t130823        671 /dev/ttys009
docker  1785 root    1u     CHR               16,9   0t130823        671 /dev/ttys009
docker  1785 root    2u     CHR               16,9   0t130823        671 /dev/ttys009
docker  1785 root    3r     CHR               14,1     0t4096        587 /dev/urandom
docker  1785 root    4u  KQUEUE                                          count=0, state=0xa
docker  1785 root    5u    unix 0xb73c79dfce57dcb3        0t0            ->0xb73c79dfce57cb83
```

### Steps to reproduce the behavior

N/A

**Comment by nojacko** [comment]
I have same issue. 

The latest versions of Docker for Mac have not worked for me in a long time. Having to use a version over 6 months old.

**Comment by tecnom1k3** [comment]
Having exactly same issues when I upgraded to  18.03.0-ce-mac59 yesterday

Diagnostic ID: B6111AAC-7B70-488C-8681-A112317C1B87

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/B6111AAC-7B70-488C-8681-A112317C1B87/20180327-134703.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk
```

![image](https://user-images.githubusercontent.com/1458333/37994276-eb21832a-31c5-11e8-9446-659f6d235ae8.png)

**Comment by agis** [comment]
Restarting my machine didn't help. However, restarting Docker specifically did help.

**Comment by mdotson** [comment]
I'm having this issue as well. My flow that is being interrupted is using `docker-compose up -d`, however, gradually `docker` commands like `docker ps` get slower, after a couple minutes, they are unresponsive. Restarting docker does help, however, I'm unable to do much during the ~2 mins before docker is unresponsive. After 5 minutes, even restarting docker does not help and it asks me to reset to factory defaults.

And as other posters have mentioned, this started a few months ago, as all recent releases have had this issue. I'm forced to use a version about a year old (17.03).

**Comment by flux627** [comment]
I'm having the exact same problems as @mdotson above.

**Comment by tecnom1k3** [comment]
just as @mdotson says, problem surfaces mainly while doing a docker-compose up -d  I have to lift 5 or 6 containers to get my application stack working, so you will understand my pain.  if I leave it as it is for 30 minutes or more, docker will stabilize and run again, but it is pain so I have to docker-compose down/restart/up fequently to develop and test my applications and wait ~30 mins for things to stabilize...

**Comment by nojacko** [comment]
Anyone using a third party SSD? Try checking if TRIM is enabled. I found that TRIM was off and by turning it on everything seems to be working perfectly. My Mac as a whole is running so much smoother!

https://www.maketecheasier.com/enable-trim-for-3rd-party-ssds-mac/

**Comment by tecnom1k3** [comment]
I tried reset to defaults, I tried to use virtualbox option, none of this worked.  I was able to get 7 containers up and running without any workload on them, but as soon as I performed and action, firing workload on the containers, again docker became unresponsive, having to restart docker again...  it would seem that when heavy reading/writing is done inside the containers, the issue arises, supporting what @agis reported initially

**Comment by rclarkburns** [comment]
This sounds like a dupe of #1835

**Comment by tecnom1k3** [comment]
so I downgraded the docker for mac app, with no success... I noticed that the hyperkit process is CPU hungry and making my containers to hang... I increased memory from 2 to 4GB and apparently that did the trick...

**Comment by mdotson** [comment]
@tecnom1k3 while that indeed is an issue (if you don't give enough resources for docker to run the containers, it can hang). I am having this issue with 12gb allocated to docker.

**Comment by toymachiner62** [comment]
@tecnom1k3 having the same issue. docker-compose up with like 5 - 6 containers. I have to restart docker b/c i'm too impatient.
