### ISSUE TITLE
Docker Won't Finish Starting

### ISSUE THREAD

**Issue by yahehe** [docker/for-mac#2738]
- [x] I have tried with the latest version of my channel (Stable AND Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
Docker starts and docker-cli is usable

### Actual behavior
Docker doesn't start, and any `docker x` commands hang until a manual quit is triggered.

### Information
Diagnostic ID: 336ED674-EAEB-4538-A2D5-A54985BED839

I've tried fresh installs of the current Stable (18.03.0-ce-mac59) and Edge (18.03.0-ce-mac58 (23607)), as well as version 17.12.0-ce-mac55 (23011), as well as installs using brew, and so far I've seen the same error every time. I'm running High Sierra 10.13.3.

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/336ED674-EAEB-4538-A2D5-A54985BED839/20180327-152722.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. Download and install Docker
  2. Wait for Docker to finish starting

**Comment by JuliaRechkunova** [comment]
@yahehe Reset to factory defaults helped me to fix it

**Comment by yahehe** [comment]
I tried that for every installation and no luck. Also tried rebooting every time and that didn't work either.

**Comment by jeffxf** [comment]
I'm having the same issue and it's driving me insane. @yahehe I kept installing older versions until I found one that worked (17.09.1-ce-mac42 2017-12-11): https://download.docker.com/mac/stable/21090/Docker.dmg

**Comment by CMYanko** [comment]
reset the image 2.0.0-mac81 and reset factory defaults got it to start.
