### ISSUE TITLE
Error MySQL:: read error database name upper case... (Docker Community Edition 18.03.0-ce-mac59 2018-03-26)

### ISSUE THREAD

**Issue by c3stream** [docker/for-mac#2740]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
MySQL upper case database name.
Can read a table of data base successfully.

### Actual behavior
Can't read a table of data base.
MySQL upper case database name.

### Information

```
Docker for Mac: version...
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E190a)
logs: /tmp/E12065C4-3C6C-4B74-B055-9CF7A5EA091D/20180328-225315.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

MySQL database name "UserData"...etc

```
Docker for Mac: version...
Docker Community Edition 18.03.0-ce-mac59 2018-03-26
```

### Steps to reproduce the behavior

  1. Update (Docker Community Edition 17.12.0-ce-mac55 2018-02-27) to (Docker Community Edition 18.03.0-ce-mac59 2018-03-26)
  2. docker restart or docker quit.
When I repeated several times, I couldn't read the db.
  
macOS High Sierra
10.13.3 and 10.13.4
MySQL version is 5.6

Is OK!  (Docker Community Edition 17.12.0-ce-mac55 2018-02-27)  
A strange thing is happening, but I hope it will be solved.

**Comment by pgayvallet** [comment]
Hello,

Could you please provide a reproduction scenario for your issue ?

**Comment by c3stream** [comment]
Update  (Docker Community Edition 17.12.0-ce-mac55 2018-02-27) to (Docker Community Edition 18.03.0-ce-mac59 2018-03-26)

docker restart or docker quit.
When I repeated several times, I couldn't read the db.

macOS High Sierra
10.13.3 and 10.13.4

**Comment by c3stream** [comment]
MySQL version is 5.6

**Comment by c3stream** [comment]
I fix it back to the old version.
Old version  (Docker Community Edition 17.12.0-ce-mac55 2018-02-27)

**Comment by c3stream** [comment]
@pgayvallet
Need more information?

**Comment by c3stream** [comment]
MySQL > DB mysql
Table: innodb_index_stats
Table: innodb_table_stats

rows DB name lower_case.... changed...Oh..


```
 mysql:
    restart: always
    image: mysql:5.6
    container_name: xxx-mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
```

**Comment by avifried1** [comment]
We're experiencing issues too, specifically with mysql containers. The case-insensitivity of Mac OS isn't detected consistently when restarting the mysql container. 
The last docker build we've seen to not be having this issue is 17.12.0-ce-mac45 2018-01-05

To reproduce on current versions, run a mysql container of any version, and check with mysql client:
`SHOW VARIABLES LIKE 'lower%'`

On the old docker engine version, the container correctly sets the variables:

```
lower_case_file_system	ON
lower_case_table_names	2
```

But on newer releases this is usually set to:
```
lower_case_file_system	OFF
lower_case_table_names	0
```

While inconsistently detecting  `lower_case_file_system` as `ON` sometimes...

**Comment by rickshawhobo** [comment]
+1 on this issue. Started noticing it with version 18-ce as well as the edge version

**Comment by dcardozo** [comment]
+1. I'm also experiencing this issue after upgrading to latest Docker for Mac version: 

Here is how to reproduce:

1) First, using Docker for Mac 17.12.0-ce-mac55 (23011) - _**works as expected**_:

Start the database:
```
$ mkdir /temp/mysqldata
$ docker run --name mysql --rm -p 3306:3306 -v /temp/mysqldata:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mysql:5.7
```

In a separate terminal window, run mysql client and query for the interesting variables (_**values are as expected**_):
```
$ docker run -it --link mysql:mysql --rm mysql:5.7 sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" -e "SHOW VARIABLES LIKE \"lower%\""'
mysql: [Warning] Using a password on the command line interface can be insecure.
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | ON    |
| lower_case_table_names | 2     |
+------------------------+-------+
```

Remove the database container and data directory
```
$ docker rm -f mysql
$ rm -rf /temp/mysqldata
```

2) Upgrading and using Docker for Mac 18.06.0-ce-mac70 (26399) - **_does not work as expected_**:

Start the database:
```
$ mkdir /temp/mysqldata
$ docker run --name mysql --rm -p 3306:3306 -v /temp/mysqldata:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mysql:5.7
```

In a separate terminal window, run mysql client and query for the interesting variables (_**values are different from above**_):
```
$ docker run -it --link mysql:mysql --rm mysql:5.7 sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" -e "SHOW VARIABLES LIKE \"lower%\""'
mysql: [Warning] Using a password on the command line interface can be insecure.
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 0     |
+------------------------+-------+
```

Remove the database container
```
$ docker rm -f mysql
```

**Comment by rickshawhobo** [comment]
This issue is still marked as needing info. Is there any more info we can provide? It’s been 4 months and it’s still a blocker to upgrading.

**Comment by rickshawhobo** [comment]
The audience of people who use docker for mac with mysql with case sensitive tables must be very small, because this is pretty broken to be acceptable.

**Comment by javierenciso** [comment]
Hitting this issue on mac, with a shared volume to the host. The table is generated by Magento with CamelCase, can't rename it...
Any chance to reopen this? Any alternative solution?
```
 mysql:
    image: mysql:5.7
    volumes:
        - ./volumes/mysql:/var/lib/mysql:delegated
```
```
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | ON    |
| lower_case_table_names | 2     |
+------------------------+-------+
```


Docker version 19.03.1, build 74b1e89 / mac os mojave 10.14.6

/thanks
/javier

**Comment by gsomersbb** [comment]
This is still an issue on 19.03.1, is anyone going to look at it ?

**Comment by idoberko2** [comment]
Does anyone in this thread has a workaround for this issue? It drives me crazy...

**Comment by rickshawhobo** [comment]
There's no hope in anyone fixing it. I did a workaround by making a case sensitive mac volume and putting mysql on it

**Comment by idoberko2** [comment]
Thanks... Since this project is in an early stage and we are able to, we decided to rename the DB and tables.

**Comment by danielrivera** [comment]
What's the ETA on a fix for this?
