### ISSUE TITLE
2DA642F2-F32F-4BE6-A247-F06469E19B0A

### ISSUE THREAD

**Issue by innnzzz6** [docker/for-mac#2745]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Hello, 

Sorry but issue doesn't have enough information for us to investigate. Feel free to reopen it with a proper description if the issue is still present.
