### ISSUE TITLE
clocksource fails over to 'hpet' after resume from sleep

### ISSUE THREAD

**Issue by revolutionate** [docker/for-mac#2747]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior

After resuming from sleep, clocksource remains as 'tsc', and my application (PHP's Xdebug extension, making heavy use of timing syscalls) is still fast.

### Actual behavior

Clocksource fails over to 'hpet', as reported in output of `dmesg`:
```
[  872.777059] clocksource: timekeeping watchdog on CPU2: Marking clocksource 'tsc' as unstable because the skew is too large:
[  872.778234] clocksource:                       'hpet' wd_now: 8cddf09 wd_last: 7832acf mask: ffffffff
[  872.779403] clocksource:                       'tsc' cs_now: 1a1732a0c3cd cs_last: 1a160708bcdd mask: ffffffffffffffff
[  872.783568] clocksource: Switched to clocksource hpet
```

'hpet' is significantly more expensive to query, so this makes PHP requests take 3x as long. Once marked as unstable, I can't switch back to 'tsc' without restarting the docker daemon.

Manually switching the clocksource to 'hpet' has the same adverse effect on performance.

### Information

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/DE549936-F812-4B65-A680-F08959BFFA75/20180329-222042.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```
### Steps to reproduce the behavior

  1. Restart Docker for Mac. 
  2. `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`
  3. `cat /sys/devices/system/clocksource/clocksource0/current_clocksource`
   (should say 'tsc')
  4. Put the mac to sleep, wait a few moments, then resume
  5. Observe message in console. Repeat step 3 and see that clocksource is now 'hpet'

**Comment by mattjtodd** [comment]
I can verify that this issue is still present in the latest version of Docker for mac 18.06.1-ce-mac74 (26766) (68d201c1b7).

Should I raise a new issue?

**Comment by joniklas** [comment]
I can confirm this isssue is still present in the latest version of Docker for mac 18.09.2. 
System: macOS 10.14.3. MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports).

```
cat /sys/devices/system/clocksource/clocksource0/available_clocksource
hpet acpi_pm
```
So the "tsc" cloucksource is even not available.
```
cat /sys/devices/system/clocksource/clocksource0/current_clocksource
hpet
```

**Comment by ralph** [comment]
For everyone trying this, the path to the tty seems to have changed. At least it's the following on my installation (Docker Desktop for Mac 2.2.0.3):

```
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
```
