### ISSUE TITLE
Error while starting up Docker on MacBook pro startup

### ISSUE THREAD

**Issue by sbasheer** [docker/for-mac#2748]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Sorry we can't investigate without any version or diagnostics. Closing
