### ISSUE TITLE
don't show kubernetes tab 

### ISSUE THREAD

**Issue by opertat** [docker/for-mac#2749]
<img width="1087" alt="screen shot 2018-03-29 at 10 31 53 pm" src="https://user-images.githubusercontent.com/37922710/38125807-0f673752-33a1-11e8-8ca3-3df8a40365fd.png">
 and I have Macos high Sierra 10.13.4

**Comment by guillaumerose** [comment]
This issue has been fixed in the latest release. The root cause is that we download a file at application startup which contains activated features.
Sometimes in corporate network, the download fails and the feature Kubernetes doesn't appear.
