### ISSUE TITLE
Docker for mac crashes while playing with https://github.com/microservices-demo/microservices-demo/tree/master/deploy/swarmkit

### ISSUE THREAD

**Issue by martinborgman** [docker/for-mac#275]
Docker for mac seems to have a problem when playing with https://github.com/microservices-demo/microservices-demo/tree/master/deploy/swarmkit.

After starting a single node docker swarm, I started the application with ./start-swarmkit-services.sh.

Docker doesn't seam to crash using a specific command, but it does crash after running the application for a while.

### Steps to reproduce

Docker crashes after a while.

### Expected behavior

docker should continue running

### Actual behavior

docker crashes

### Information

```
Diagnostic ID: 2CD38D77-67BD-4FE9-AAC0-10440BA0B4FD
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[ERROR]  disk
         Docker.qcow2 is corrupt: reset to factory defaults is required
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
This seems like a sierra issue, please update to the latest beta (25) that tries to resolve sierra issues. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
