### ISSUE TITLE
Docker fails to start after upgrade

### ISSUE THREAD

**Issue by dustinleblanc** [docker/for-mac#2750]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
After upgrading Docker from v17.12.0-ce-mac55 (23011) to v18.03.0-ce-mac59 I expect Docker to properly start
### Actual behavior
Starting Docker app after upgrade results in 
![image](https://user-images.githubusercontent.com/3948808/38143650-7ddee482-340f-11e8-8de2-8ab2bc8aa34c.png)

`Symlink /usr/local/bin/hyperkit doesn't exist`

### Information
Diagnostics
```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/0D960A78-8F2A-43F0-A5FA-F68784614315/20180330-113303.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/dustinleblanc/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/dustinleblanc/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/dustinleblanc/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

```
This issue surfaced by a few users our application (lando/lando) during the upgrade from our beta 37 to beta 38 that we just cut last night. 

Completely uninstalling Docker and reinstalling alleviates the issue, but figured this was worth reporting anyway.

**Comment by trops** [comment]
yes, this happened to me too, but don't want to reinstall or I will lose my images. Any suggestions on how to move forward with this?

**Comment by vincenzo** [comment]
The very same thing just happened to me when upgrading from very same mac55 to mac60 (Version 18.03.0-ce-mac60 (23751)).
