### ISSUE TITLE
The Kubernetes Metrics Server / HPA Custom Metrics Support

### ISSUE THREAD

**Issue by diclophis** [docker/for-mac#2751]
### Expected behavior

I would like to be able to develop in my docker-for-mac kubernetes cluster features like the "Kubernetes Metrics Server" ( https://github.com/kubernetes-incubator/metrics-server ) and "Custom/External Metrics" for the HPA modules ( https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#requirements )

### Actual behavior

I am unable to configure these features

### Information

```
Version 18.03.0-ce-mac58 (23607)
```

**Comment by mac2000** [comment]
Will be also nice if metrics server and heapster will be shipped by default, e.g. to make environment as close as possible to what we get in GCP/AWS/Azure

e.g. at moment, locally I can not play with horizontal pod autoscaler because it can not collect current cpu usage from deployment

**Comment by diclophis** [comment]
@mac2000 Indeed, either by default, or via some gui checkboxes that allow finer tuned control over the kubelet and apiserver flags would be great!

**Comment by jasonwc** [comment]
@mac2000 @diclophis did you ever figure out how to get heapster installed and reporting on Docker for Mac? Just ran into the same issue. Huge bummer cause I was hoping to demonstrate auto scaling locally for a talk I'm giving.

**Comment by jasonwc** [comment]
Running Version 18.04.0-ce-mac62 (23965)

**Comment by YRM64** [comment]
Configure Kubernetes with Autoscaling with Custom Metrics (docs.bitnami.com).  If you haven't seen it yet, this article discusses how to configure Kubernetes with autoscaling, Kubernetes Aggregator Layer, Prometheus, Cluster Configuration, Checking the Status of the Cluster, Cluster Configuration, Deploying a Prometheus Monitoring System, Deploying a Custom API Server, and Deploying a Sample Application, with a Summary.  I hope this helps; let me know if you're still experiencing configuration issues.

**Comment by jasonwc** [comment]
Thanks those are some great resources!

I ended up getting it to work by setting up the metrics-server instead. Would be cool if that shipped by default like most standard `kube-up` setups, but you can go [here](https://github.com/kubernetes-incubator/metrics-server) to clone it and deploy it as a workaround.

**Comment by YRM64** [comment]
Thanks Jasonwc for your contribution.

**Comment by diclophis** [comment]
/remove-lifecycle stale

Is there any chance we can see this be included by default with docker-for-mac ?

**Comment by paultiplady** [comment]
I'm hitting certificate validation issues running the latests metrics-server (v0.3.0) against a Docker for Mac k8s cluster (Kubernetes: v1.10.3, Engine: 18.06.1-ce). 

The error is this one: https://github.com/kubernetes-incubator/metrics-server/issues/133 - 

`unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:docker-for-desktop: unable to fetch metrics from Kubelet docker-for-desktop (docker-for-desktop): Get https://docker-for-desktop:10250/stats/summary/: x509: certificate signed by unknown authority`

Seems like the Docker for Mac node might not be wired up to the cluster CA properly? (Either that or it's a metrics-server bug).

Anyone else seen this / found a workaround?

**Comment by vfarcic** [comment]
I just experienced the same issue. I know that it worked recently so my best guess is that something changed in the latest Docker For Mac update. I'm deploying the same version of the Metrics Server (as a Helm chart) so that shouldn't be the issue.

**Comment by vfarcic** [comment]
I have the same issue as @paultiplady. Last time I used Metrics Server (a few weeks ago), it worked. Now it doesn't. I'm installing the same Metrics Server version now as before so I guess that's not the issue. My best guess is that my Docker For Mac was upgraded since the last time I run Metrics Server successfully.

**Comment by marcellodesales** [comment]
@paultiplady @vfarcic Any solutions on this? I'm hitting the same roadblock :(

**Comment by paultiplady** [comment]
@marcellodesales I gave up on Kubernetes for Docker for Mac, and went back to Minikube.

**Comment by fallwith** [comment]
@paultiplady @vfarcic @marcellodesales - I was able to get past the cert verification issue that exists between `metrics-server` and a Docker based instance of Kubernetes via the instructions found at `https://qiita.com/rk05231977/items/64825c095a6ec37e49f8`

Here are the full steps I took to get things working:

1. Have Kubernetes running within Docker
2. Delete any previous instance of `metrics-server` from your Kubernetes instance with `kubectl delete -n kube-system deployments.apps metrics-server`
3. Clone `metrics-server` with `git clone https://github.com/kubernetes-incubator/metrics-server.git`
4. Edit `deploy/1.8+/metrics-server-deployment.yaml` to override the default command by adding a `command` section that didn't exist before. The new section will instruct `metrics-server` to allow for an insecure communications session (don't verify the certs involved). Do this only for Docker, and not for production deployments of `metrics-server`:
  ```shell
  % git diff
  diff --git a/deploy/1.8+/metrics-server-deployment.yaml b/deploy/1.8+/metrics-server-deployment.yaml
  index ad2abaf..517166b 100644
  --- a/deploy/1.8+/metrics-server-deployment.yaml
  +++ b/deploy/1.8+/metrics-server-deployment.yaml
  @@ -30,6 +30,9 @@ spec:
        containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server-amd64:v0.3.1
  +        command:
  +          - /metrics-server
  +          - --kubelet-insecure-tls
          imagePullPolicy: Always
          volumeMounts:
          - name: tmp-dir
  ```
4. Add `metrics-server` to your Kubernetes instance with `kubectl create -f deploy/1.8+`

It would ne nice if Docker (for any OS) bundled `metrics-server`, but I don't think anything needs to be done on the Docker side to make `metrics-server` work. Docker is correctly using a cert, and `metrics-server` needs to either be taught to trust that cert or bypass verification entirely.

Recommendations:

* Close this issue
* Open a new Docker issue (not just for Mac) to propose the bundling of `metrics-server`
* Create an issue with `kubernetes-incubator/metrics-server` to trust Docker's cert or perhaps recognize Docker and automatically pass `--kubelet-insecure-tls`

**Comment by narg95** [comment]
@fallwith thanks it worked like a charm, you saved me a lot of time :) The `metrics-server` docu does not mention how to apply  those flags.  

In my case I just apply the new deployment since I had it already installed manually since *docker-for-desktop` does not come with the `metrics-server`. So, after modifing the `metrics-server-deployment.yaml` file I did: `kubectl apply -f deploy/1.8+/`

**Comment by bitsofinfo** [comment]
I've followed @fallwith example (thanks) and I no longer see the TLS errors

I'm running latest edge for mac (k8 1.13)

`kubectl top pod` shows my pod CPU and MEMORY fine

Created my hpa with `kubectl autoscale rs my-app --min=1 --max=5 --cpu-percent=1`

The logs for the metrics-server look ok, I see HPA requests returning 200's

But my HPA doesn't ever have any data, I just get this for a `kubectl describe hpa my-app`.

Any thoughts?

```
Name:                                                  my-app
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 07 Feb 2019 09:30:51 -0700
Reference:                                             ReplicaSet/my-app
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 1%
Min replicas:                                          1
Max replicas:                                          5
ReplicaSet pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       4s (x8 over 109s)  horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  4s (x8 over 109s)  horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu
```

**Comment by secat** [comment]
You could also use the official helm chart [stable/metrics-server](https://github.com/helm/charts/tree/master/stable/metrics-server) using the following `values.yaml` file:

```yaml
args:
  - --logtostderr
# enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  - --kubelet-insecure-tls

hostNetwork:
  # Specifies if metrics-server should be started in hostNetwork mode.
  #
  # You would require this enabled if you use alternate overlay networking for pods and
  # API server unable to communicate with metrics-server. As an example, this is required
  # if you use Weave netwok on EKS
  enabled: true
```

The node metrics works:
```shell
$ kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes" | jq
```

will return:
```json
{                                                                       
  "kind": "NodeMetricsList",                                            
  "apiVersion": "metrics.k8s.io/v1beta1",                               
  "metadata": {                                                         
    "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes"                    
  },                                                                    
  "items": [                                                            
    {                                                                   
      "metadata": {                                                     
        "name": "docker-desktop",                                       
        "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/docker-desktop",
        "creationTimestamp": "2019-03-20T13:26:15Z"                     
      },                                                                
      "timestamp": "2019-03-20T13:25:52Z",                              
      "window": "30s",                                                  
      "usage": {                                                        
        "cpu": "521240620n",                                            
        "memory": "3148748Ki"                                           
      }                                                                 
    }                                                                   
  ]                                                                     
}                                                                       
```

However, the pod metrics doesn't work with error type like:
```
E0320 13:21:08.077551       1 reststorage.go:144] unable to fetch pod metrics for pod [...] : no metrics known for pod
```

**Comment by jianglijie** [comment]
@fallwith After I follow the steps，metrics-server is runing, also I can use `kubectl get pod` and `kubectl get node`  But I cant kubectl apply anything. It report `error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup_v2): invalid object doesn't have additional properties` 
the docker-for-mac-desktop version is 2.0.0.3 and k8s version is 1.10.11

**Comment by gaurish** [comment]
@secat I was about to reach to the solution where host metrics work but pod metrics are not working. Wondering, if you or anyone else was able to make progress to get pod metrics working?
