### ISSUE TITLE
Fatal Error Docker Starting (com.docker.supervisor failed to start Exit code 1)

### ISSUE THREAD

**Issue by rollinroy** [docker/for-mac#2752]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
When I took my laptop running docker and containing some docker images from home (on my local network) to work (running on another network) I expected docker to still work.
### Actual behavior
I received the docker error (diagnostic id included) which required me to reset docker (and lose whatever images I previously ran/downloaded.  Then when I returned home, I received the same docker error.
### Information
Diagnostic id: E2D53292-F135-4D48-BCF1-E742DAC514CB

Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/E2D53292-F135-4D48-BCF1-E742DAC514CB/20180330-132735.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/royboy/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/royboy/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/royboy/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

Docker for Mac: version...

10.13.3

### Steps to reproduce the behavior

  1. Run a docker image on laptop.  
  2. Shutdown laptop
  3. Go to another network
  4. Start laptop
  5. Docker reports error when starting.

**Comment by wonderffee** [comment]
I choose to reset docker, all images and containers are lost, be cautious!
