### ISSUE TITLE
Suddenly wont start

### ISSUE THREAD

**Issue by ajthenewguy** [docker/for-mac#276]
### Information

Diagnostic ID: 3E238EEF-5382-41FB-88A3-E23505DFF314
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.4 (Build 14E46)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Wake OS up from sleep
2. Attempt to use Docker

**Comment by glynjackson** [comment]
dup of https://github.com/docker/for-mac/issues/64

**Comment by dsheets** [comment]
This issue is not related to #64 as it occurs with OS X 10.10.4.

**Comment by chasegawa** [comment]
Similar for me. I was working along and Docker tried to restart itself and can't. Full restart of system and it won't start back up

Docker for Mac: version: abf019d
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/67B844AD-7745-4DB5-9D50-38CD4A1BD25B/20160815-164439.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by elgreg** [comment]
+1 Same issue here.

**Comment by ajthenewguy** [comment]
The only way I was able to get it back up again was to reset settings:

1. click the Docker icon and select Preferences... 
2. choose the Uninstall/Reset "tab"
3. click "Reset to factory defaults" button).

**THIS WILL DELETE ALL EXISTING IMAGES**, which sucks because I had several multi-GB images I had to re-pull.

If anyone knows how to back up images first, please comment with those instructions, because until they fix the underlying cause this _will_ happen again...

**Comment by elgreg** [comment]
I ended up doing the same and it did indeed work. I'd like to assume that there's a less scorched-earth approach, though.

**Comment by chasegawa** [comment]
Happening more often to me now with an update...

**Comment by mchiang0610** [comment]
Merging with #119
