### ISSUE TITLE
Docker for Mac no longer able to support IDE for Harvard's CS50 

### ISSUE THREAD

**Issue by Kyniska** [docker/for-mac#2760]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have submitted Diagnostics
  - [ x] I have included the Diagnostics ID in this Issue

### Expected behavior
activation of CS50 IDE container

### Actual behavior

Claim is site can't be reached.  I've been using Docker for this activity for over a year, so very surprised to see this.

### Information
ID: 119CA89-1E99-4C9D-B1C8-B28137B55C6C

This site can’t be reached
localhost refused to connect.
Search Google for localhost 5050
ERR_CONNECTION_REFUSED

```
Docker for Mac: 18.03.0-ce-mac60 (23751)
```

### Steps to reproduce the behavior

  1. Start Docker for Mac
  2. In browser (normally Chrome) type 'localhost:5050' (address is usually 'localhost:5050.ide.html'

**Comment by akimd** [comment]
Hi!  We need more details about your problems.  I guess you are running a container that exposes some ports and you are trying to connect to these ports?

Your logs seem to be missing, please run diagnostics again.

**Comment by Kyniska** [comment]
Hi Akimd,

The command for configuring the port is:
docker run --privileged -e "IP=127.0.0.1" -e "PORT=8080" --name ide50 -d -p 5050:5050 -p 8080-8082:8080-8082 cs50/ide

which is pulled from:
https://manual.cs50.net/ide/offline#mac

Diagnostic ID: 1119CA89-1E99-4C9D-B1C8-B28137B55C6C

Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/1119CA89-1E99-4C9D-B1C8-B28137B55C6C/20180403-113720.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

**Comment by djs55** [comment]
Closing as @Kyniska reports the issue was fixed. Please open a fresh issue if you encounter any other problems.

Thanks for your report!
