### ISSUE TITLE
docker-machine conflicts with native virtualization

### ISSUE THREAD

**Issue by jcwright77** [docker/for-mac#2761]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Expected behavior
docker run is able to start container from local image
### Actual behavior
Unable to find image 'xxx:latest' locally
docker: Error response from daemon: manifest for xxx:latest not found.

### Information

```
Docker for Mac: version...
This crashes on my mac with spinning beachball.

[]$docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: ZREP:LLEQ:KPIB:UODQ:XVGG:UB5P:CCHX:CQVA:FOQ7:HP53:6I73:662Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 57
 System Time: 2018-04-02T17:30:16.84018501Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior
docker build ...
docker-machine start default
eval $(docker-machine env default --shell=sh
docker run . . .

I am likely not understanding the purpose of having docker-machine when the system supports native virtualization. I came across this error when running and existing script to launch a docker image which assumed virtualbox would be used if not on a linux system. 

It seems with the docker-machine environment, image locations are confused between native and docker-machine support. Should docker-machine be removed from Mac native distributions? Or is there a use case?

**Comment by akimd** [comment]
As a developer of Docker for Mac, I would argue that Docker for Mac alone suffices.  Docker Machine made sense in the context of Docker Toolbox, which predates the technologies that drive Docker for Mac today.  See https://docs.docker.com/docker-for-mac/docker-toolbox/.

**Comment by jcwright77** [comment]
I agree. I had been using containers in a virtual box image before Docker for Mac became available, which was why virtualbox was present. I only installed Docker for Mac and not Docker Toolbox so the question really is should docker-machine come with native Docker for Mac? It caused me some confusion and errors until I figured out what the third party run script I was using was doing.  

-john

**Comment by akimd** [comment]
Get rid of Docker Toolbox and Docker Machine, use only Docker for Mac.

**Comment by jcwright77** [comment]
I never installed Docker toolbox. Just Docker for Mac, which apparently came with docker-machine

**Comment by jcwright77** [comment]
I think this should stay open. If docker-machine is shipping with docker for Mac, this is causing problems.  I tripped over this problem because another user's script was checking for docker-machine, which then launched the default image in my virtualbox installation. This should not have happened. I never installed docker-toolbox (which I use on a windows home laptop).

**Comment by akimd** [comment]
Yes, docker-machine is installed.  But if you don't need it, don't run it.  I thought you had installed docker-machine independently with Docker Toolbox.

Just use Docker for Mac as documented (https://docs.docker.com/docker-for-mac/).

**Comment by jcwright77** [comment]
Will do, just pointing out that some users test for docker-machine in their run scripts to make a portable container. If it is the case that virtual box is installed separately (which I think is not uncommon), then the script will start the container in the vbox default machine rather than natively leading to all sorts of confusion. This is not expected behavior. Better to not ship docker-machine if it should not be used. Unless you have a use case in mind I cannot see?

**Comment by faith-warwick** [comment]
Running into similar issue.. following has been working so far. Not great to have to run everytime I execute a start script though.  

unset ${!DOCKER_*}

https://docs.docker.com/docker-for-mac/docker-toolbox/#docker-toolbox-and-docker-for-mac-coexistence
