### ISSUE TITLE
Kuberetes is starting... forever upon install with 18.03.0-ce-mac58

### ISSUE THREAD

**Issue by kjkurtz** [docker/for-mac#2766]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

### Expected behavior
Install Kubernetes successfully.

### Actual behavior
Hangs on installation of Kubernetes.

### Information

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1212)
logs: /tmp/126DDAEE-5438-4E0A-B046-4D7CC0296CD7/20180403-112721.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Install Docker edge and it runs like normal
  2. Check the box to install Kubernetes, let it run in the background, and it never leaves `Kubernetes is starting...` state.

**Comment by liubin** [comment]
The same issue.

**Comment by liubin** [comment]
Update: 
* Only restart Docker for Mac not worked.
* Rest tab -> reset kubernetes cluster for some times, the k8s cluster is now in running status.

**Comment by xiaods** [comment]
interesting for reset some times for recover the k8s cluster.

**Comment by kjkurtz** [comment]
I can no longer duplicate this since I got a new laptop, but I can confirm with the same macOS config (same proxies, same network, same OS version, etc) that it is now working with version 18.04.0-ce

**Comment by xiaods** [comment]
@kjkurtz so close it.
