### ISSUE TITLE
Docker won't start on Mac

### ISSUE THREAD

**Issue by chrisid** [docker/for-mac#2767]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

Diagnostic ID: 89AF65B7-9E29-4D6D-ADED-9D33DBD95958

### Expected behavior
Docker to start

### Actual behavior
Error when open

### Information
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/89AF65B7-9E29-4D6D-ADED-9D33DBD95958/20180403-175539.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/christianpugliese/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/christianpugliese/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/christianpugliese/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

**Comment by btmurrell** [comment]
i'm getting this too, just starting today.  i was seeing it on `17.12.0-ce, build c97c6d6`, one issue i read said to upgrade to latest, try again, so upgraded my docker  to `18.03.0-ce, build 0520e24` just now, getting same error. here's the ouput from my `docker-diagnose -u`:

```
macOS: version 10.12.6 (build: 16G1114)
Docker.app: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
Local time: Tue Apr  3 13:09:51 PDT 2018
UTC:        Tue Apr  3 20:09:51 UTC 2018
Timestamp:  20180403-130951
Running diagnostic tests:
[OK]      Files
[ERROR]   Docker CLI       Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
[ERROR]   Docker CLI       Connection refused (ECONNREFUSED) connecting to /Users/brianmurrell/Library/Containers/com.docker.docker/Data/s60: check if service is running
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   VPNKit           Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/brianmurrell/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/brianmurrell/Library/Containers/com.docker.docker/Data/s51
[ERROR]   VPNKit           com.docker.vpnkit is not running
Error docker ps: got timeout (docker ps: exit 1)
```

**Comment by btmurrell** [comment]
update: read somewhere my state file was messed up (`Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`)

i renamed it, and docker started fine.  not sure how it got hosed.  but i lost all configs, images and containers.  pulling new images and building... just a matter of time.

**Comment by agparadiso** [comment]
I was having the same issue after updating, fixed by reseting to factory defaults. 
Preferences... -> reset -> reset to factory defaults
