### ISSUE TITLE
macOS sierra (10.12 beta) Docker Crash 

### ISSUE THREAD

**Issue by Alloctag** [docker/for-mac#277]
### Information

Diagnostic ID: E2700B2B-74FA-4DAC-85CC-74A15235FA37
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A269f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. open Docker.app
2. run `docker images`
3. docker crash and step 2 print below text:
`
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json: EOF
`

**Comment by mchiang0610** [comment]
beta 25 will have fixed most of the macOS sierra related issues: https://download.docker.com/mac/beta/Docker.dmg 

Stable should release soon. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
