### ISSUE TITLE
Updated MacOS to 10.13.4 and now Docker hangs or fails at start

### ISSUE THREAD

**Issue by larsgeorge** [docker/for-mac#2775]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

ID: 2D3407F8-DE55-4BFF-A64F-6B51828E9AF9

### Expected behavior

Docker starts as usual.

### Actual behavior

Either is fails with an error message that reports the supervisor failed, error code 1, or it starts and hangs. This depends on if I have reset the Docker setup or have killed and restarted the process.

### Information

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/2D3407F8-DE55-4BFF-A64F-6B51828E9AF9/20180405-170246.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/vms/0/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started
```
### Steps to reproduce the behavior

No idea, sorry.

I tried uninstalling Docker (using the command line switch), replace it with standard and edge, downloaded today (18.03.0-ce-mac60). Nothing changed the behavior.

Logs: [20180405-170246.tar.gz](https://github.com/docker/for-mac/files/1880610/20180405-170246.tar.gz)

![screenshot 2018-04-05 14 19 25](https://user-images.githubusercontent.com/84429/38374896-31e8104a-38f5-11e8-8a21-9b6eeb81391b.png)
![screenshot 2018-04-05 16 58 44](https://user-images.githubusercontent.com/84429/38374897-3211e7c6-38f5-11e8-9088-987f1719ec2a.png)
![screenshot 2018-04-05 17 04 39](https://user-images.githubusercontent.com/84429/38374898-32363586-38f5-11e8-822a-8eea0f3baf81.png)

**Comment by TheDegree0** [comment]
After a factory reset I was able to replicate the problem, here are the steps:
1. Restart MacOS
2. Login on a admin user and start docker
3. Leave that account open and switch to a non-admin user.
4. Start docker there too.
5. Boom, crash.

I think this will replicate the problem, it did for me.

**Comment by larsgeorge** [comment]
Just to chime in on @TheDegree0 observation, I am running as admin user and have no other users on my system. But from the error, it somehow seems that the unix domain socket bind fails, which I guess is what can happen with more than one instance running on the same machine. I checked with the Activity Monitor and "ps auxw" and I can only see 

root              2311   0.0  0.0  4287644   4708   ??  Ss    4:59PM   0:00.02 /Library/PrivilegedHelperTools/com.docker.vmnetd

and the "Docker" process running. Single instances of each. Not sure if that helps at all, but to be precise.

**Comment by larsgeorge** [comment]
Here is another attempt that I logged with console. Something about the UnixDomainSocket keeps failing.

[docker.log](https://github.com/docker/for-mac/files/1886203/docker.log)

I issued these delete commands before reinstalling Docker from the install DMG:

```
sudo rm -r /var/tmp/com.docker.vmnetd.socket                                                                                                                               gerrit_master b7bd4cf95 ✗
 sudo rm -r ~/Library/Application\ Scripts/com.docker.helper/
 sudo rm -r ~/Library/Containers/com.docker.*
 sudo rm -r ~/Library//Preferences/com.docker.docker.plist
 sudo rm -r ~/Library/Group\ Containers/group.com.docker/
 sudo rm -Rf /Applications/Docker*
 sudo rm -f /usr/local/bin/docker
 sudo rm -f /usr/local/bin/docker-machine
 sudo rm -f /usr/local/bin/docker-compose
 sudo rm -f /usr/local/bin/docker-credential-osxkeychain
 sudo rm -Rf ~/.docker
 sudo rm -Rf $HOME/Library/Containers/com.docker.docker
```

**Comment by larsgeorge** [comment]
Also, this is what I see on the file system:
```
/Volumes/Macintosh-HDD/projects/cerebro/cerebro
☺  ll /var/run/docker.sock                                                                                                                                                     gerrit_master b7bd4cf95 ✗
lrwxr-xr-x  1 root  daemon    85B Apr  7 10:34 /var/run/docker.sock -> /Volumes/Macintosh-HDD/Users/larsgeorge/Library/Containers/com.docker.docker/Data/s60

/Volumes/Macintosh-HDD/projects/cerebro/cerebro
☺  ll ~/Library/Containers/com.docker.docker/Data                                                                                                                              gerrit_master b7bd4cf95 ✗
total 8
lrwxr-xr-x  1 larsgeorge  staff     5B Apr  7 10:34 com.docker.driver.amd64-linux -> vms/0
-rw-r--r--  1 larsgeorge  staff     0B Apr  7 10:34 task.lock
drwxr-xr-x  2 larsgeorge  staff    68B Apr  7 10:34 tasks
drwxr-xr-x  3 larsgeorge  staff   102B Apr  7 10:34 vms

/Volumes/Macintosh-HDD/projects/cerebro/cerebro
☺  ll ~/Library/Containers/com.docker.docker/Data/vms                                                                                                                          gerrit_master b7bd4cf95 ✗
total 0
drwxr-xr-x  3 larsgeorge  staff   102B Apr  7 10:34 0

/Volumes/Macintosh-HDD/projects/cerebro/cerebro
☺  ll ~/Library/Containers/com.docker.docker/Data/vms/0                                                                                                                        gerrit_master b7bd4cf95 ✗
total 0
srwxr-xr-x  1 larsgeorge  staff     0B Apr  7 10:34 00000002.0000100
```
The symlink of the socket is pointing to "s60", which does not exist. Is that normal?

**Comment by larsgeorge** [comment]
The issue was the length of the domain socket path, as reported in other issues. I had 106 letters, and MacOS only allows 104. I renamed my HDD (painful but doable) to something shorter and now it works.

**Comment by akimd** [comment]
Could someone hit by the limitation of the length of $HOME try the following build of Docker for Mac?

https://download-stage.docker.com/mac/pr/23982/Docker.dmg

Please, report result (positive _or_ negative).  TIA!

**Comment by bsnodgrass** [comment]
I have the same issue.. my $HOME is /Users/bobsnodgrass assuming I qualify to test this I am game

Tried to restart numerous times and docker info reports:
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?

**Comment by bsnodgrass** [comment]
Negative

**Comment by bsnodgrass** [comment]
872A2CF8-3C58-4993-8D48-7900D2F21649

**Comment by akimd** [comment]
@bsnodgrass According to my reading of your logs, it worked, and then you used the previous version of Docker for Mac.  Could you please:
- use only the version I sent
- when it fails, generate a diagnostics
- and explain exactly what your problem is

**Comment by bsnodgrass** [comment]
@akimd 
Sorry I forgot I had reverted back to my original version. Both report the same error when using docker info or docker ps
$ docker ps
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
$ docker info
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?

I confirmed neither of my development tools using docker work. Diagnostics report all (OK) Following are two runs or the diagostics:

872A2CF8-3C58-4993-8D48-7900D2F21649

Docker for Mac: version: 18.04.0-ce-mac62 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/872A2CF8-3C58-4993-8D48-7900D2F21649/20180415-174150.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

872A2CF8-3C58-4993-8D48-7900D2F21649/20180415-174656

Docker for Mac: version: 18.04.0-ce-mac62 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/872A2CF8-3C58-4993-8D48-7900D2F21649/20180415-174656.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

I had issues with upgrading MacOS to High Sierra a week ago and have just completed another reinstall. I would be glad to attempt any correction suggestions you might have.

**Comment by akimd** [comment]
@bsnodgrass I don't know yet what your problem is, but it's unrelated to the lengths of the names of the sockets (you are comfortably in the safety zone: 85 characters).

The only thing a bit suspicious I see is
```
2018-04-15 15:20:06.385455-0500  localhost com.docker.vpnkit[955]: Failed to parse address 'host' from hosts file
2018-04-15 15:20:06.385491-0500  localhost com.docker.vpnkit[955]: Failed to parse address 'host' from hosts file
```

Does it ring any bell?

Do you have any suspicious in your environment variables?  `env | grep DOCKER`.  What does `which docker` give?

**Comment by bsnodgrass** [comment]
$ env | grep docker
DOCKER_CERT_PATH=/Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot
$ which docker
/usr/local/bin/docker

I had briefly used amazeeio-cachalot as an environment, and have not removed it. I will try that and see if it corrects.

Also I notice the following when trying to connect to remote environment using my auth token:
$ lando terminus auth:login --machine-token=6R...Jpu
Creating network "...r_default" with the default driver
Creating volume "...r_data" with default driver
Creating volume "...r_appserver" with default driver
Creating volume "...r_data_database" with default driver
Creating volume "...r_data_index" with default driver
Pulling database (mariadb:10.0)...
ERROR: Get https://registry-1.docker.io/v2/library/mariadb/manifests/10.0: unauthorized: incorrect username or password
Creating network "...r_default" with the default driver
Pulling database (mariadb:10.0)...

I will to create a new token and try that.

Open to any other suggestions.

**Comment by bsnodgrass** [comment]
I removed old amazeeio-cachalot 
Remove Docker and reinstalled stable release

Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

### Expected behavior
Set Memory to 3 GiB
Apply and Restart 
Expected to Start 

### Actual behavior
Did not start Diag shows docker ps timeout

### Information

872A2CF8-3C58-4993-8D48-7900D2F21649

Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/872A2CF8-3C58-4993-8D48-7900D2F21649/20180416-144305.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

**Comment by bsnodgrass** [comment]
I restarted once again and Diag shows clean
However I get the following:

$ docker ps
could not read CA certificate "/Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem": open /Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem: no such file or directory
seems like I am close, but I uninstalled Amazeeio and Docker and removed all associated files this is from a new install - Where is it getting instruction to look for that CA certificate?

**Comment by bsnodgrass** [comment]
Multiple attempts to remove and reinstall docker I end up with the same issue
Using the Lando dependencies 

I still get the same message on all docker commands:
could not read CA certificate "/Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem": open /Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem: no such file or directory

I seem to have some links still identified that were not removed in usr/local/bin:
$ ls -la docker*
lrwxr-xr-x  1 bobsnodgrass  staff        54 Apr 16 18:08 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x  1 bobsnodgrass  staff        62 Apr 16 18:08 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose
lrwxr-xr-x  1 bobsnodgrass  staff        80 Mar 30 16:55 docker-compose.backup -> /Users/bobsnodgrass/Library/Group Containers/group.com.docker/bin/docker-compose
lrwxr-xr-x  1 bobsnodgrass  staff        77 Apr 16 18:08 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
lrwxr-xr-x  1 bobsnodgrass  staff        95 Mar 30 16:55 docker-credential-osxkeychain.backup -> /Users/bobsnodgrass/Library/Group Containers/group.com.docker/bin/docker-credential-osxkeychain
lrwxr-xr-x  1 bobsnodgrass  staff        62 Apr 16 18:08 docker-machine -> /Applications/Docker.app/Contents/Resources/bin/docker-machine
-rwxr-xr-x  1 bobsnodgrass  admin  30191664 May  8  2017 docker-machine.backup
-rwxr-xr-x  1 bobsnodgrass  admin  16111056 May  5  2017 docker.backup

The last attempt I completely uninstalled docker and associated files.

**Comment by bsnodgrass** [comment]
Sorry for the cross-post, but I thought https://github.com/docker/for-mac/issues/2817 Remove reference to old CA Cert was a better title at this point as my issue has evolved. I will check to make sure they are both closed once I have resolution.
