### ISSUE TITLE
Docker does not finish starting

### ISSUE THREAD

**Issue by bmbroom** [docker/for-mac#2776]
From when I first upgraded to the latest stable version of Docker-ce for mac a few days ago until yesterday, everything was fine. This morning when I opened the lid (woke it up), the whale was flashing its containers and the daemon was not responsive.

I found many similar recent issues, but I'm not sure any are identical.

I have tried the following remedies suggested on those issues to no avail, including restarting Docker, restarting my mac, removing the qcow2 file, changing the location of the qcow2 file, resetting my preferences, and reinstalling Docker.  The previous version I have (17.12.0-ce-mac55) appears to work. Upgrading to the current version within Docker as well as stopping Docker and reinstalling the current version from the dmg file result in the same symptoms.

The log below says "No Docker.qcow2 or Docker.raw found: the VM has never been started". The Docker.qcow2 does exist.  If I remove it before starting Docker, it recreates it and starts writing it.  If I go into Preferences / Disk, the "Reveal in Finder" button is active and works as advertised.  The "Move disk image" button is inactive.

MacOS version is 10.12.6

Diagnostic id: 5C7F700D-A0B6-4C87-9AD9-5F527D99B9E8

Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue

### Expected behavior

Docker starts, the whale icon stops changing, and docker commands get a valid response.

### Actual behavior

Docker begins starting, the whale icon changes continuously, docker commands get an error response.

```
Error response from daemon: Bad response from Docker engine
```

### Information

```
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/5C7F700D-A0B6-4C87-9AD9-5F527D99B9E8/20180406-104204.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

```

I also see error messages like the following in the console log:
```
Apr  6 10:42:14 BCBMC02R82VUG8W com.docker.vmnetd[6876]: no path for address 0x10e2c1000
```
Over multiple restart attempts, the address above will stay the same, then change to a new value for multiple attempts, then change again etc.  Changes in the address may coincide with attempts to reset/change the qcow2 file and/or reinstalling Docker.

### Steps to reproduce the behavior

  1. Start docker

**Comment by polishExperiment** [comment]
I am curious if you managed to solve your problem. I have similar [issues](https://github.com/docker/for-mac/issues/2847) except your [ERROR] disk.
