### ISSUE TITLE
966A211A-57D6-47C6-B4C0-9C62375E3BB2

### ISSUE THREAD

**Issue by luhuadong** [docker/for-mac#2778]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info supplied, so closing. Please reopen if you can supply the requested info including repro steps, expected and actual behaviour, and diagnostics.
