### ISSUE TITLE
Connecting to host over VPN not working for d4mk

### ISSUE THREAD

**Issue by wenlock** [docker/for-mac#2779]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
This is very similar to this issue https://github.com/docker/for-mac/issues/1803, when I connect to the VPN, I'm hoping to reach host on the private network. Most of these host are on the `172.19` network.

### Actual behavior

I'm also having this issue with simple containers such as `docker run -it --rm debian:jessie sh`, then install curl for testing. When I try this command in the container I get these errors

```
ping app.privatedomain.com
PING internal-app.privatedomain.com.com (172.19.XX.XX): 56 data bytes
^C--- internal-app.privatedomain.comcom ping statistics ---
26 packets transmitted, 0 packets received, 100% packet loss
```

### Information

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/93BC38C4-ABB6-4C75-AA4F-1D0E4224CE02/20180407-111552.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior

  1. Configure docker for kubernetes
  2. Connect to VPN
  3. Start a new container `docker run -it --rm debian:jessie sh`
  4. Try pinging a server on the remote network over VPN

**Comment by wenlock** [comment]
I think I solved the issue for myself by changing the network settings:

![image](https://user-images.githubusercontent.com/1907138/38460077-a50f8a30-3a67-11e8-81f8-f0cc669bc756.png)

**Comment by wenlock** [comment]
Ervin, i’ve def not had this issue again even with the latest. Might need to start a new one with your specifics.

**Comment by insanj** [comment]
Getting this issue with the latest Docker. Changing Docker subnet address did not change anything.

```
Version 2.0.0.0-mac81 (29211)
Channel: stable
4271b9e6a8
Engine: 18.09.0
```

**Comment by insanj** [comment]
@wenlock @ervinjohnson Did anyone find a fix for the latest reappearance of this bug?
