### ISSUE TITLE
Docker for Mac 18.03 still uses pool.ntp.org

### ISSUE THREAD

**Issue by eproxus** [docker/for-mac#2786]
### Expected behavior

Docker without any started container only has a few outgoing connections.

### Actual behavior

Docker has 195 outgoing connections to IP numbers all over the world. It seems #2529 was not included in 18.03.

### Information

```
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/E1EF66F3-B5AD-4673-91BE-B76CDFAAB0A1/20180409-105344.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Start Docker for Mac
  2. Observe outgoing connections using Little Snitch

**Comment by papasax** [comment]
Docker for Mac 18.06 still uses pool.ntp.org

**Comment by da4089** [comment]
/remove-lifecycle stale

I'm still seeing this with v18.09.

Docker Desktop for Mac.
Little Snitch reports **_inbound_** ICMP packets from various IPs (Rackspace, Red Hat, Internet Archive, and Hostway).

**Comment by justincormack** [comment]
I believe this is fixed in Edge but maybe not stable?

If you run
```
docker run  --privileged --pid=host justincormack/nsenter1 ps auxww | grep ntp
```

on Edge you see `/usr/sbin/sntpc -v -i 30 gateway.docker.internal` in the output which is using an internal ntp server. Can you run this on the version you are running and check the output?

**Comment by djs55** [comment]
I've just tested the following versions:
- latest stable `Version 2.0.0.0-mac81 (29211)`
- latest edge `Version 2.0.0.0-mac82 (29268)`
- older stable `Version 18.06.1-ce-mac73 (26764)`

In all cases I ran
```
$ docker run  --privileged --pid=host justincormack/nsenter1 /bin/ps auxww | grep ntp
 1229 root      0:00 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/sntpc -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
 1256 root      0:00 /usr/sbin/sntpc -v -i 30 gateway.docker.internal
```
to verify the `sntpc` process is present (following @justincormack 's suggestion above). I also ran
```
$ docker run  --privileged --pid=host justincormack/nsenter1 /usr/bin/tail -f /var/log/sntpc.log
2019-01-04T14:51:28Z sntpc sntpc[1]: offset=0.290213, delay=0.002156
2019-01-04T14:51:58Z sntpc sntpc[1]: offset=-0.034212, delay=0.000789
2019-01-04T14:52:28Z sntpc sntpc[1]: offset=-0.033779, delay=0.000573
2019-01-04T14:52:58Z sntpc sntpc[1]: offset=-0.033825, delay=0.000843
2019-01-04T14:53:28Z sntpc sntpc[1]: offset=-0.033571, delay=0.001183
2019-01-04T14:53:58Z sntpc sntpc[1]: offset=-0.033983, delay=0.000904
2019-01-04T14:54:28Z sntpc sntpc[1]: offset=-0.033790, delay=0.000510
2019-01-04T14:54:58Z sntpc sntpc[1]: offset=-0.033759, delay=0.000901
2019-01-04T14:55:28Z sntpc sntpc[1]: offset=-0.033815, delay=0.000814
2019-01-04T14:55:58Z sntpc sntpc[1]: offset=-0.033828, delay=0.000934
```
to verify the process is working and then ran:
```
$ docker run --privileged --net=host djs55/tcpdump -n -i eth0
Unable to find image 'djs55/tcpdump:latest' locally
latest: Pulling from djs55/tcpdump
ff3a5c916c92: Pull complete
f23b05f6159a: Pull complete
Digest: sha256:5982d09e2c739e72c632e60960142da274339ba2c8ce75908db263679f75beb4
Status: Downloaded newer image for djs55/tcpdump:latest
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:52:58.883582 IP 192.168.65.3.56685 > 192.168.65.1.53: 48900+ A? gateway.docker.internal. (41)
14:52:58.883639 IP 192.168.65.3.56685 > 192.168.65.1.53: 64000+ AAAA? gateway.docker.internal. (41)
14:52:58.884038 IP 192.168.65.1.53 > 192.168.65.3.56685: 48900 1/0/0 A 192.168.65.1 (57)
14:52:58.884119 IP 192.168.65.1.53 > 192.168.65.3.56685: 64000 NXDomain 0/0/0 (41)
14:52:58.884277 IP 192.168.65.3.49992 > 192.168.65.1.123: NTPv4, Client, length 48
14:52:58.884935 IP 192.168.65.1.123 > 192.168.65.3.49992: NTPv4, Server, length 48
```
to verify all the traffic being sent from the VM is either ARP or destined for the host (`192.168.65.1` in my case).

The NTP client [source code](https://git.alpinelinux.org/hosted/sntpc/) doesn't mention `pool.ntp.org`. There's no mention in `/etc/` in the VM either.

@da4089 @papasax if you're still seeing the use of `pool.ntp.org` in the most recent Docker for Mac could you upload a set of diagnostics and a `tcpdump` trace? Thanks!

**Comment by adamgins** [comment]
What ever happened with this.. I just tried to update to version 2.2.0.5 and I got the Malware warning from Intego software that detected Malware with `docker-compose`

**Comment by djs55** [comment]
@adamgins could you open a fresh ticket describing what happened? (It might be that the issue will need to be escalated to Intego software in the end).
