### ISSUE TITLE
i got an error ,can not use Docker now

### ISSUE THREAD

**Issue by veryrich** [docker/for-mac#2803]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info supplied, so closing. Please reopen if you can supply the requested info including repro steps, expected and actual behaviour, and diagnostic id.
