### ISSUE TITLE
When Docker inspect is run under "Mounts" section, the mount type is missing

### ISSUE THREAD

**Issue by SathyaBhat** [docker/for-mac#2808]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

### Expected behavior

As per the [Documentation](https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount), once we create a bind mount and do a docker inspect, the Mounts section should show a `"Type": "bind",`. 

### Actual behavior

The Type field is missing.

Run a container

```
docker run -d \
  -it \
  --name devtest \
  --mount type=bind,source="$(pwd)"/target,target=/app \
  nginx:latest
````

Use `docker inspect` and check the Mounts section

```
docker inspect devtest | jq .[0].Mounts
[
  {
    "Source": "/Users/sabhat",
    "Destination": "/app",
    "Mode": "",
    "RW": false
  }
]
```

### Information

```
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)

240D24C2-E6E1-45A0-83BE-8FA9D29FF199/20180414-012306

```

### Steps to reproduce the behavior

1. Visit https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount
2. Run the steps mentioned in Actual behaviour

**Comment by guillaumerose** [comment]
I tried on the latest version 18.06.0-ce and this is fixed. Can you upgrade and try it ? Thanks.

**Comment by SathyaBhat** [comment]
Yep, can confirm it's working. 

```docker inspect devtest | jq .[0].Mounts
[
  {
    "Type": "bind",
    "Source": "/Users/sabhat/code/devops",
    "Destination": "/app",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  }
]```

closing the issue
