### ISSUE TITLE
Docker pull / push - slow

### ISSUE THREAD

**Issue by karolsojko** [docker/for-mac#281]
### Steps to reproduce
1. run `docker-compose build` on any image
### Expected behavior

I can properly build or pull an image
### Actual behavior

when I run `docker-compose build` it pulls the image and after downloading a couple of MB it freezes. Doesn't matter what image, always behaves the same.

Curiously engouh when using Docker Quickstart Terminal from Docker Toolbox it works fine, but that's a different thing completely.
### Information

```
Diagnostic ID: AD1A1043-CF95-46DE-AA1D-57EE6AD157E7
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
From @yakticus 

```
I am seeing extremely slow push times (i.e., 30 minutes or more just to push 40MB). speedtest.net says my upload speed is about 6Mbps. The details of this issue have been reported on the forum >1 month ago but there has been no response. See them here:

https://forums.docker.com/t/docker-push-is-cripplingly-slow/18289

I started experiencing extreme slowness even when pushing to AWS ECR. I stumbled upon the below thread which says to restart docker for mac. Sure enough, after restarting, the pushes became orders of magnitude faster. The relevant AWS thread is here:

https://forums.aws.amazon.com/thread.jspa?threadID=222834
```

**Comment by ghostganz** [comment]
Restarting the daemon (by clicking "restart" next to "Docker is running" in the menu) seems to fix it temporarily.

**Comment by jamesreggio** [comment]
Has anybody begun investigating this? Is there anybody with a hunch about where the problem may lie? (If you share your thoughts, I'd be happy to take up the torch and investigate... but right now, I wouldn't know where to begin.)

**Comment by justincormack** [comment]
@jamesreggio hi, it is on my TODO list but have not had a chance yet.

The best bet is to start by comparing `docker pull` performance to the same from the host, eg you can use something along the lines of https://github.com/justincormack/regextract which pulls locally. Compare with docker hub and a local repo perhaps, and then start to look at the differences, eg dump the network traffic and see if there is anything obvious. We don't have any obvious suspects right now...

**Comment by ijc25** [comment]
@justincormack did you get a chance to look into this? Do we have a corresponding internal ticket already?

**Comment by justincormack** [comment]
I can't replicate any difference with `pull` on my machine (with our reasonably fast internet connection at the office), downloading a single layer 250MB hub image with docker pull and with regextract, it is 29.203s vs 29.633s which is pretty close. So I don't really know how to investigate at this point either...

**Comment by karolsojko** [comment]
From that time I've installed a fresh OS X and a fresh Docker For Mac and seems to be fixed

thanks guys for looking into this

**Comment by cyrilchampier** [comment]
I am experiencing this problem, and restarting the (mac + daemon) did not improve performance.

5B735E32-3C6C-4BA9-AFA7-0F35A38C71C4
```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.12.2 (build: 16C68)
logs: /tmp/5B735E32-3C6C-4BA9-AFA7-0F35A38C71C4/20170202-110844.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by samoht** [comment]
@cyrilchampier can you try to use the `regextract` tool that @justincormack recommend above and see if that makes a difference? Thanks!

**Comment by cyrilchampier** [comment]
@samoht I retried this afternoon, with the exact same params, and it is now ok.
This morning, I tested on 2 different and unrelated networks, so it was not a pb from local side.
Maybe a problem on aws-ecr ...
Sorry for the false alarm.

**Comment by samoht** [comment]
No problem, thanks for the update and glad to see that everything is working well.

**Comment by ent1c3d** [comment]
I have same problem, sometimes it hangs on extraxting process, sometimes during download, do we have some fixes for this issue?

**Comment by Vallerious** [comment]
I get a lot of retries on some of the layers and a TLS handshake timeout after awhile...

**Comment by ReyRen** [comment]
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Still occur this issue frequently.

**Comment by dibyo09** [comment]
I am facing the same issue , Preparing->retrying-> hanging

The layer image size is 3.84 GB ...could this be a possible reason
