### ISSUE TITLE
Fatal Error:   Symlink /usr/local/bin/hyperkit doesn't exist

### ISSUE THREAD

**Issue by paul94010** [docker/for-mac#2823]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue

### Information

running this command:   docker status

environment:   MacOS 10.13.4

diagnostic ID:
13659098-1845-4973-86FE-97AD6225AE14

diagnostics:

<Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/13659098-1845-4973-86FE-97AD6225AE14/20180418-120824.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/paul/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/paul/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/paul/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
>

### Steps to reproduce the behavior

 1.  update docker
2.  run:  docker status

**Comment by MeyersEH** [comment]
I'm getting this same problem and I (and my professor) cannot figure out what the problem is.

**Comment by rikvdh** [comment]
This behavior is also seen with edge (18.05)

**Comment by justinbeckham** [comment]
same problem here:
chmod 755 /usr/local/bin 
fixed it

**Comment by MeyersEH** [comment]
Hey, so I'm in a class just learning this stuff for the first time, could you explain step by step to try out this fix to see if it works for me? That would be super helpful!

**Comment by justinbeckham** [comment]
I'm not sure what level of step by step you need. Essentially after installing just open a terminal window and type 'sudo chmod 755 /usr/local/bin'. Enter your password and it will modify the permissions. Then restart Docker and it shouldn't throw the error.

**Comment by MeyersEH** [comment]
Thank you!!!

**Comment by MeyersEH** [comment]
Yes, this worked like a charm!!! Thank you so so much!!!!
