### ISSUE TITLE
deploy stack deploy fail to work.

### ISSUE THREAD

**Issue by chrisLeeTW** [docker/for-mac#2825]
### Expected behavior
`docker stack deploy -c docker-compose.yml cnyes` should create stack successfully.

### Actual behavior
fail to create with error msg : `Stack.compose.docker.com "cnyes" is invalid: cnyes: Invalid value: "version: \"3.0\"\nservices:\n  localstack:\n    environment:\n      DEFAULT_REGION: ap-northeast-1\n      SERVICES: s3,sqs\n    image: localstack/localstack:0.8.6\nnetworks: {}\nvolumes: {}\nsecrets: {}\nconfigs: {}\n": parse error: configs Additional property configs is not allowed`

### Information

![2018-04-19 6 02 38](https://user-images.githubusercontent.com/1946961/38985420-dfeac69a-43fb-11e8-805b-74d8f438f108.png)

Diagnostic ID : 9BB247E9-F454-4658-806D-1745563B67E1

```
Docker for Mac: version: 18.04.0-ce-mac62 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/9BB247E9-F454-4658-806D-1745563B67E1/20180419-174058.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

docker-compose.yml
```
version: '3'
services:
  localstack:
    image: localstack/localstack:0.8.6
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=ap-northeast-1
```

### Steps to reproduce the behavior

  1. refresh-install docker-edge from brew `brew tap caskroom/cask; brew cask install docker-edge`
  2. start docker-for-mac & enable kubernetes 
  3. execute cmd `docker stack deploy -c docker-compose.yml cnyes`

### Note
I am doubt that is caused by missing of kubernetes custom resource definitions, when I executed cmd `kubectl get crd`, I got response `No resources found.`

**Comment by ashwinvenkatraman** [comment]
seeing the exact same issue

**Comment by YRM64** [comment]
ChrisLeeTW,

See #4305; let us know if you want to close #2825 after viewing #4305.  Thanks!

**Comment by mat007** [comment]
@YRM64 #4305 does not exist in this project.

**Comment by YRM64** [comment]
Forgive me if you inferred from my comments that #4305 was in this project.

**Comment by chrisLeeTW** [comment]
@YRM64 Hi, but I also can not found comment with #4305 or pull request #4305 in this project ? maybe due to lack of authorization ?

**Comment by awidjaja** [comment]
any solution?
