### ISSUE TITLE
Delete button should be on the right

### ISSUE THREAD

**Issue by Kwadz** [docker/for-mac#2827]
For Mac UX the main action is always on the right, like Cancel-OK (no OK-Cancel like Windows).

The UI issue is located in the reset menu:

<img width="616" alt="screen shot 2018-04-19 at 15 00 28" src="https://user-images.githubusercontent.com/1472599/38993036-c2a74158-43e2-11e8-8570-5a858c5496e7.png">

**Comment by akimd** [comment]
Fixed, and soon to be released.  Thanks for the report!
