### ISSUE TITLE
docker diagnostics fails with a kubernetes error

### ISSUE THREAD

**Issue by lakshmi-balakrishna** [docker/for-mac#2836]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Not enough details.  But I venture Kubernetes was not enabled, but the kubectl command was still visible.  This is annoying but not a sign of failure.
