### ISSUE TITLE
StackAPI displays "Unknown" under Docker for Mac 18.04 with GKE Cluster

### ISSUE THREAD

**Issue by ajeetraina** [docker/for-mac#2837]
I am running Docker for Mac 18.04 CE release with Kubernetes enabled. Here is the quick overview of my system configuration -

```
Docker for Mac: version...
18.04.0 CE
```

# Displaying Kubectl version

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

# Listing the Nodes under GKE
```
kubectl get nodes
NAME                                      STATUS    ROLES     AGE       VERSION
gke-k8s-lab1-default-pool-e0e7a263-99rd   Ready     <none>    8m        v1.8.8-gke.0
gke-k8s-lab1-default-pool-e0e7a263-jk17   Ready     <none>    8m        v1.8.8-gke.0
gke-k8s-lab1-default-pool-e0e7a263-s305   Ready     <none>    8m        v1.8.8-gke.0
```
# Displaying the version of Docker Engine
```
 docker version
Client:
 Version:   18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:13:16 2018
 OS/Arch:   darwin/amd64
 Experimental:  true
 Orchestrator:  kubernetes
 
Server:
 Engine:
  Version:  18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:    Tue Apr 10 18:23:05 2018
  OS/Arch:  linux/amd64
  Experimental: true
 Kubernetes:
  Version:  v1.8.8-gke.0
  StackAPI:     Unknown
```

## Expected behavior
StackAPI under docker version should show correct StackAPI version

## Actual behavior

StackAPI version goes missing under ```docker version```

# Is it affecting my application Deployment?

I am able to deploy Nginx application service on top of GKE cluster and you can find it under [this](https://github.com/ajeetraina/docker101/blob/master/play-with-kubernetes/gke-d4m.md) link.
But when I am using the below docker stack deploy command -

```
docker stack deploy -c docker-compose.yml myapp
```

It throws error "Failed to find Stack API version"

**Comment by kevinsuperped** [comment]
I am seeing the same behavior, running docker for mac on the edge branch.

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: true
 Orchestrator: kubernetes

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
 Kubernetes:
  Version:     v1.10.0
  StackAPI:                   Unknown
```

Seeing the exact same error running 

`docker stack deploy -c docker-compose.yml myapp`

**Comment by ajeetraina** [comment]
I see the similar issue with AWS Kubernetes cluster built using Kops. The "Unknown" StackAPI is not letting me to use docker stack deploy to build up services on k8s cluster. Refer : https://github.com/ajeetraina/docker101/tree/master/for-mac/aws

**Comment by garethr** [comment]
Hi @ajeetraina. The support for `docker stack deploy` relies on a serverside component that runs in Kubernetes. That component is currently only available in EE and Docker Desktop. Unfortunately that means at present this won't work with an arbitrary Kubernetes cluster like GKE, although that may change in the future. Checking the engine documentation that's not clear and we should look to fix that.

**Comment by ajeetraina** [comment]
@garethr I am currently using Docker for Mac 18.05 CE.

**Comment by thaJeztah** [comment]
@ajeetraina correct, but the kubernetes cluster you're connected to is not the built-in kubernetes cluster of Docker for Mac, but an external cluster; the Stack API component is not installed in that cluster, hence the message.

**Comment by collabnix** [comment]
This feature has been recently enabled in Docker Desktop and recently announced this DockerCon EU 2018. All you will have to install compose on k8s on your GKE cluster.

**Comment by abdennour** [comment]
this answer https://github.com/docker/compose-on-kubernetes/issues/35#issuecomment-455874623 will fix the issue
