### ISSUE TITLE
Memory leak in com.docker.osxfs

### ISSUE THREAD

**Issue by tverboon** [docker/for-mac#2839]
Very high memory usage:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/6871049/39166979-d4fe10fe-478c-11e8-8ab3-aeab4177b250.png">

I am running sabnzbd in a Docker container. It looks like all disk IO, that should be a stream, stays in Memory.

Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)

Referencing #1815. Although this is probably a new issue, previous version didn't cause excessive memory usage in my use case.

**Comment by djs55** [comment]
@tverboon thanks for your report! Could you provide reproduction steps to help me replicate this in-house? Ideally a `Dockerfile` or a `docker-compose.yml` or a script. Thanks!

**Comment by tverboon** [comment]
```bash
docker run -d --rm --name=sabnzbd \
-v /T5/nzbd/config:/config \
-v /T5/nzbd/complete:/complete \
-v /T5/nzbd/incomplete:/incomplete \
-v /T5/nzbd/watch:/watch \
-v /T5/nzbd/:/datadir \
-v /T5/nzbd/media:/media \
-p 8080:8080 \
sabnzbd/sabnzbd
```

But this is the easy part. To reproduce it, you need to download an NZB from a news server. Actually that's not easy to reproduce, unless you have access to a news server.

I tried to reproduce with curl in a vanilla debian container, but that didn't work. Memory grows, but shrinks also again, which looks normal buffering to me.

--
Trying to reproduce it with sabnzbd, but I see the same behaviour as with curl. Memory usage is between 700MB and 1GB, but not like yesterday where it kept growing.

I am sorry, but it seems I cannot consistently reproduce this.

**Comment by SalomonSmeke** [comment]
@tverboon happy to +1 here. Memory usage starts at 400 MB and slowly climbs without any activity in the container/server. Unfortunately not running anything that I can share :/

**Comment by zulli73** [comment]
I prepared a docker-compose with which I can reliably reproduce the issue on my system: https://github.com/zulli73/docker_issue_2839. Please check the README.md

It suspect that this issue is caused due to a kernel related resource leak, like unclosed file handles or the like as `kernel_task`'s memory consumption grows as well (see notes in `README.md`).

Probably needless to mention, but: Your system will "crash", so save any data before reproducing!

**Comment by zeyangl** [comment]
having the same issue here. Is there a gonna be a fix for this?
