### ISSUE TITLE
com.docker.vpnkit binds to ports 9701 and 9702

### ISSUE THREAD

**Issue by smithbk** [docker/for-mac#2842]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

### Expected behavior

I'm not expecting it to bind to ports 9701 or 9702

### Actual behavior

It is binding to both of these ports

### Information

I'm using Version 18.04.0-ce-mac62 (23965) of docker edge on mac.

The diagnostics ID is 7B9709CE-3B31-491F-AC68-921C495909A1

The com.docker.vpnkit process is binding to ports 9701 and 9702.
These are the two ports which another process tries to bind to by default.

What is causing com.docker.vpnkit to bind to ports 9701 and 9702?  Is there something I can disable?  This seems to have happened as soon as I upgraded docker edger to the version shown above.
```
keiths-mbp:scripts keith$ lsof -i tcp:9701
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 3808 keith   31u  IPv4 0x818cc8d50afc771d      0t0  TCP *:9701 (LISTEN)
com.docke 3808 keith   32u  IPv6 0x818cc8d508f73b55      0t0  TCP localhost:9701 (LISTEN)
keiths-mbp:scripts keith$ lsof -i tcp:9702
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 3808 keith   33u  IPv4 0x818cc8d50d3f1dbd      0t0  TCP *:9702 (LISTEN)
com.docke 3808 keith   34u  IPv6 0x818cc8d508f76395      0t0  TCP localhost:9702 (LISTEN)
keiths-mbp:scripts keith$ ps aux | grep 3808
root               249   0.0  0.0  4380888   5284   ??  Ss   Wed06PM   0:00.69 /usr/libexec/smd
keith            12833   0.0  0.0  4295416    952 s000  S+   12:41PM   0:00.00 grep 3808
keith             7391   0.0  0.1  4389876  13808   ??  S    10:58AM   0:00.54 /System/Library/CoreServices/CoreServicesUIAgent.app/Contents/MacOS/CoreServicesUIAgent
keith             3808   0.0  0.1  4395652  19876   ??  S     9:52AM   0:06.78 com.docker.vpnkit --ethernet fd:3 --port fd:4 --introspection fd:5 --diagnostics fd:6 --vsock-path /Users/keith/Library/Containers/com.docker.docker/Data/vms/0/connect --host-names host.docker.internal,docker.for.mac.host.internal,docker.for.mac.localhost --gateway-names gateway.docker.internal,docker.for.mac.gateway.internal,docker.for.mac.http.internal --vm-names docker-for-desktop --listen-backlog 32 --mtu 1500 --allowed-bind-addresses 0.0.0.0 --http /Users/keith/Library/Group Containers/group.com.docker/http_proxy.json --dhcp /Users/keith/Library/Group Containers/group.com.docker/dhcp.json --port-max-idle-time 300 --max-connections 2000 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.254 --log-destination asl
keiths-mbp:scripts keith$ docker ps -aq
keiths-mbp:scripts keith$ 
```

### Steps to reproduce the behavior

 I've tried restarting docker.  Simply starting docker causes com.docker.vpnkit to bind to ports 9701 and 9702.

**Comment by djs55** [comment]
@smithbk I can't spot the diagnostics ID in this issue -- it'll be difficult to understand what's going on without access to the logs. Do you still have the diagnostics ID somewhere?

**Comment by smithbk** [comment]
@djs55 Sorry, I just updated.  The diagnostics ID is 7B9709CE-3B31-491F-AC68-921C495909A1

Thanks

**Comment by djs55** [comment]
Thanks for the diagnostic upload. Looking at the k8s services it seems the ports are bound by 

```
Name:                     steward-service
Namespace:                default
Labels:                   <none>
...
Type:                     LoadBalancer
...
Port:                     validator  9701/TCP
TargetPort:               9701/TCP
NodePort:                 validator  32621/TCP
Endpoints:                <none>
Port:                     client  9702/TCP
TargetPort:               9702/TCP
NodePort:                 client  31188/TCP
```
I think if you remove that service then the port bindings will be removed.

**Comment by djs55** [comment]
I'll close this issue for now as I think it's working as expected. Let me know if you continue to have problems!
