### ISSUE TITLE
Docker for Mac "Diagnose & Feedback" dialog should have built-in bug/error reporting

### ISSUE THREAD

**Issue by mcollins** [docker/for-mac#2846]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ * ] I have tried with the latest version of my channel (Stable or Edge)
  - [ n/a ] I have submitted Diagnostics
  - [ n/a ] I have included the Diagnostics ID in this Issue

### Expected behavior

I clicked the button in the "Diagnose & Feedback" dialog after Docker had crashed unexpectedly, and expected it would send an error report to the Docker for Mac team.

### Actual behavior

I landed on the github new issues page with this template.

### Information

I experienced a crash running Docker for Mac Edge, and wanted to report the information from the "Diagnose & Feedback" dialog, but I didn't know I would need to save or copy/paste the output from the dialog.  So now I will have to wait until it crashes again before I can report a useful bug.

See the Mozilla Firefox crash handler dialog for an example of a crash dialog that sends a report automatically.

```
Docker for Mac: 18.04.0-ce-mac62 (23965)

```

### Steps to reproduce the behavior

  1. Have a Crash.
  2. Close the dialog before you copy the output.

**Comment by akimd** [comment]
Actually, if you look at your /tmp, you should find your diagnostic ID.
```
ls /tmp/????????-????-????-????-????????????/????????-??????.tar.gz
```
Send it if it is still there.  Thanks!
