### ISSUE TITLE
57FD501F-A1DE-4BCA-96F1-5A1E501956CF

### ISSUE THREAD

**Issue by deyikong** [docker/for-mac#2853]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
In order to investigate the issue we need more information, sorry!

Closing.
