### ISSUE TITLE
doest generate kubecontext

### ISSUE THREAD

**Issue by marcpar** [docker/for-mac#2854]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ EDGE ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

 [ERROR]  kubernetes
         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")

**Comment by psisoyev** [comment]
Same here. Diagnostic ID - 9FF0FB45-9F8F-4FCB-9A8F-98C96EDA280F

**Comment by akimd** [comment]
Have you enabled kubernetes in the Preferences?

**Comment by psisoyev** [comment]
@akimd that's another weird thing. For some reason, Kubernetes tab is missing. I thought it is some kind of update, but most probably it's related to the issue. 
<img width="497" alt="screenshot 2018-04-30 11 01 43" src="https://user-images.githubusercontent.com/1637013/39418954-03961168-4c66-11e8-9543-bf6c0daa7f49.png">

I tried to reset, re-install docker, install older versions - nothing helped.

**Comment by akimd** [comment]
Kube was not released on Stable yet, it's only on Edge releases.  Please confirm you run a Stable one.

**Comment by psisoyev** [comment]
Yes, I was using stable one. However moving to Edge didn't help, the issue with Kubernetes in diagnostics still there. Here is the new diagnostic id:
9FF0FB45-9F8F-4FCB-9A8F-98C96EDA280F

**Comment by psisoyev** [comment]
@akimd thanks for clearing this. Yes, indeed it was my fault - I was running stable release.

**Comment by akimd** [comment]
Thanks!
