### ISSUE TITLE
Add /lifecycle frozen comment, and/or \remove-lifecycle stale

### ISSUE THREAD

**Issue by YRM64** [docker/for-mac#2855]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue

### Expected behavior
No closing of an issue filed within 30 days that included a full diagnostic report of problem.

### Actual behavior
Github closed #2730 on the same day such issue was filed; indicating issues filed without diagnostics would be closed in 30 days.  A diagnostic report was attached to the filing of the issue (docker/ for-m ac) on March 26, 2018.
### Information

```
Docker for Mac: version...

```

https://github.com/docker/for-mac/issues/2730

### Steps to reproduce the behavior

  1. ...See #2730 for full filing, (March 26, 2018).  This is not an issue relative to a reproduction of behavior.
  2. ...

**Comment by akimd** [comment]
I don't see that #2730 was closed.
