### ISSUE TITLE
Diagnose and feed back crashes 

### ISSUE THREAD

**Issue by benoitdavidfr** [docker/for-mac#2857]
- [X] I have tried with the latest version of the Stable channel (18.03.1-ce-mac64 (24245)
  - [X] I can't submit Diagnostics because the Diagnoses menu crashes
  - [X] I can't include the Diadgnostics ID

I am on MacBook Pro using Mac OS 10.11.6

### Expected behavior
The app shoud start and the "Diagnose and feed back ..." menu should work properly

### Actual behavior
When I start Docker app the "Docker is running" is greyed.
When I click in the menu "Diagnose and feed back ...", the app crashes, in the Activity monitor it is said that it does't answer

**Comment by akimd** [comment]
Could you please launch Docker, and in the terminal run
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -l 1h -u
```
(with the right path for `Docker.app`) and report the results here.

Thanks.

**Comment by benoitdavidfr** [comment]
Bellow the result for: "/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -l 1h -u"

macOS: version 10.11.6 (build: 15G18013)
Docker.app: version: 18.03.1-ce-mac64 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
Local time: Lun 30 avr 2018 10:01:10 CEST
UTC:        Lun 30 avr 2018 08:01:10 UTC
Timestamp:  20180430-100110
Running diagnostic tests:
[OK]      Files
[OK]      Docker CLI
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      VPNKit
[OK]      disk
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/54ED154E-B94B-42FD-B3B7-F7041E8ED963/20180430-100110.tar.gz
Your unique id is: 54ED154E-B94B-42FD-B3B7-F7041E8ED963
Please quote this in all correspondence.

**Comment by akimd** [comment]
I think your system is in perfect shape.  The gray item menu is expected to be greyed.  The diagnostics seem to work fine.

Do you still experience crashes?
