### ISSUE TITLE
docker-compose up hangs

### ISSUE THREAD

**Issue by harelba** [docker/for-mac#286]
### Expected behavior
docker-compose up should bring the containers up. 

### Actual behavior
Hangs forever. ctrl-z + kill doesn't work - Need kill -9 to really remove process.

### Information

Diagnostic ID: D3922DD1-D900-404E-B9AC-EB67F38FA658
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by elgreg** [comment]
+1 seeing this as well as of today

**Comment by freegenie** [comment]
related to this https://github.com/docker/compose/issues/3419
solved by adding the following lines to /etc/hosts 

```
127.0.0.1 localunixsocket localunixsocket.local # these are for docker 
```

**Comment by mchiang0610** [comment]
@harelba Possible to give us a sanitized version of compose file for us to test against? Hard to reproduce like this. More details are required. 

(I'll open this with reply) 

Thanks!

**Comment by gmuc** [comment]
"127.0.0.1 localunixsocket localunixsocket.local # these are for docker"

great!!! It's help!

**Comment by namnn** [comment]
@freegenie massive thanks

**Comment by Mokto** [comment]
Thanks !

**Comment by janklan** [comment]
@freegenie thanks, worked

**Comment by yangm97** [comment]
Just had this issue today, and the workaround worked indeed, but shouldn’t this be fixed in docker-for-mac?
