### ISSUE TITLE
Geo-localized registries needs explicit login for each sub-domain

### ISSUE THREAD

**Issue by inge4pres** [docker/for-mac#2860]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have submitted Diagnostics
  - [] I have included the Diagnostics ID in this Issue

### Expected behavior
After adding an auth with 

```
docker login -u _json_key --password-stdin https://gcr.io < file.json
Login succeded
```
I can pull from _**eu**.gcr.io/project/image-name:tag_

### Actual behavior
```
➜  ~ docker pull eu.gcr.io/project/image-name:tag
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

### Information

```
Docker for Mac: 18.03.0-ce
Credential Helper: 0.6.0
```

I think the issue is in how the JSON credentials are stored and looked up for in keychain: when I manually update the entry in keychain to be used for _**eu**.gcr.io_ the pull works, as well if I run 

```
docker login -u _json_key --password-stdin https://eu.gcr.io < ...
```

the entry will be created properly.
Just curious if the lookup of the registry con be improved including subdomains?

Content of `~/.docker/config.json` does not need to have eu.gcr.io to work

```
{
	"auths": {
		"gcr.io": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```

### Steps to reproduce the behavior

  1. Create a service account in GCP and download the json auth file
  2. Execute docker login -u _json_key ....
  3. Try to pull an image from a geo-localized registry like eu.gcr.io

**Comment by groothuyse** [comment]
This is how google container registry works:

> Note: Specify one of the localized hostnames (such as us, eu, or asia) to store your data in a single specific location. gcr.io and us.gcr.io are not interchangeable.

See: https://cloud.google.com/container-registry/docs/pushing-and-pulling
