### ISSUE TITLE
Kubernetes stuck at "starting..." status after Docker upgrade

### ISSUE THREAD

**Issue by ckcheng1976** [docker/for-mac#2861]
### Expected behavior

Kubernetes should start up within a reasonable time.

### Actual behavior

Kubernetes is not starting - I have been waiting for more than 30 minutes.

### Information

Diagnostic ID = A7E106C1-0759-47AE-82BA-D08AC4FCA4BF
[20180430-160018.tar.gz](https://github.com/docker/for-mac/files/1960024/20180430-160018.tar.gz)

```
Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/A7E106C1-0759-47AE-82BA-D08AC4FCA4BF/20180430-160018.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Upgraded to Docker CE (Edge) 18.05.0-ce-rc1-mac63 (24246)
  2. Restart Docker. Docker is started within a minute
  3. Menu item shows that "Kubernetes starting...". Wait for more than 30 minutes, still the same
  4. From the Preferences menu, under the Reset tab, "Reset to factory defaults", Restart Docker. Same observation
  5. From the Preferences menu, under the Reset tab, "Uninstall", removed .kube and .docker from home directory, re-downloaded the Docker.dmg and re-installed Docker. Docker is started without issue. Enable Kubernetes from the Preferences menu, it stayed at the "Kubernetes starting..." again. So reinstalling also doesn't work for me.

**Comment by dorontal** [comment]
I had the EXACT same diagnostics report (with same error as above in the kubernetes step)

and I'm running an older version of Docker -- version 18.03.1-ce-mac65 (24312)

My "diagnostics report" which  the Docker asks to include on issues is

F17E1D57-93B5-4ACC-9A51-211B76640539

**Comment by ckcheng1976** [comment]
@dorontal I completely uninstalled this version and reinstalled the old one I had (Version 18.03.0-ce-rc1-mac54 (23022)) and it is working now. If you have an old installer image around you might want to try this?
