### ISSUE TITLE
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started

### ISSUE THREAD

**Issue by zeff013** [docker/for-mac#2862]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [+] I have tried with the latest version of my channel - Stable
  - [+] I have submitted Diagnostics
  - [+] I have included the Diagnostics ID in this Issue F4FE7C0B-6052-4426-B4A8-F5B552B634C2

### Expected behavior

Diagnose and Feedback reports no issues

### Actual behavior

failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[...]
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

### Information

Docker for Mac: version: 18.03.1-ce-mac64 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/F4FE7C0B-6052-4426-B4A8-F5B552B634C2/20180430-163044.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

### Steps to reproduce the behavior

Not sure how to reproduce.
Latest steps:
  1. Enable single node swarm mode
  2. Disable single node swam mode, by forcing manager to leave swarm

**Comment by djs55** [comment]
Ah, the diagnostics code doesn't realise that you're using a non-default disk location:
```
  "diskPath" : "/Volumes/Macintosh HD 2/Docker/Docker.qcow2"
```

**Comment by zeff013** [comment]
Ah! Thanks.
