### ISSUE TITLE
docker-compose failed if is in path what contains dir starting on `_`

### ISSUE THREAD

**Issue by ondraondra81** [docker/for-mac#2868]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
can run `docker-compose build` if `docker-compose.yml` is in `_docker` dir as in before version 
### Actual behavior
getting `ERROR: invalid reference format` 
when I rename dir `_docker` to `docker` everything run good

### Information
Diagnostic ID:  23FCDFD5-AE51-48CC-9117-94F8EE586C41

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/23FCDFD5-AE51-48CC-9117-94F8EE586C41/20180502-153428.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior

  1. move docker-compose.yml (contains service: build: .... ) to `_docker` dir 
  2. run docker-compose build

**Comment by akimd** [comment]
That would be a bug in compose.  Please report it there: https://github.com/docker/compose/issues.
Thanks!

**Comment by ondraondra81** [comment]
https://github.com/docker/compose/issues/5929
