### ISSUE TITLE
Cannot Connect to Remote Swarm

### ISSUE THREAD

**Issue by ingshtrom** [docker/for-mac#2869]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version: 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/571756/39538543-253b9fb2-4e0b-11e8-9e02-a94b8090e8a5.png">

### Expected behavior
I can run commands against a swarm remotely

### Actual behavior
Running any command like `docker node ls` or `docker service ls` doesn't work. It gives a similar error to `docker service ls is only supported on a Docker cli with swarm features enabled`.

Note that `docker ps` outputs the expected containers running in the swarm.

### Information

```
Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/56316A17-5478-4166-9C17-47CD9560DEAA/20180502-131419.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

I just noticed this on the latest Edge build where Kubernetes support was added. 

### Steps to reproduce the behavior

  1. Download the necessary certs to access a remote docker daemon (I am using UCP and downloaded the client bundle following [this guide](https://docs.docker.com/ee/ucp/user-access/cli/))
  2. Run `docker node ls` or `docker service ls`
  
### Workaround
Turn off kubernetes in the Docker for Mac Preferences, then re-run the command.

**Comment by mat007** [comment]
Hi,

I believe this is because enabling Kubernetes sets the orchestrator for the CLI:
```
$ cat ~/.docker/config.json
{
…
  "orchestrator": "kubernetes"
}
```
after which all issued commands will target that orchestrator.

You can override this with either:
```
$ docker --orchestrator=swarm node ls
```
or
```
$ DOCKER_ORCHESTRATOR=swarm docker node ls
```

**Comment by ingshtrom** [comment]
oh because we reuse the same commands for different orchestrators? I didn't think of that. Thank you!
