### ISSUE TITLE
Docker crashing frequently

### ISSUE THREAD

**Issue by shrikant-thd** [docker/for-mac#2872]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version: 10.13.4

### Expected behavior
Docker stops crashing

### Actual behavior
Docker has been crashing frequently as soon as I exit the container. I've been seeing this issue in 17.12.1-ce and 18.03.0-ce versions.

### Information

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/BAF9C956-C1D3-46DD-8778-66825F230644/20180502-152210.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/sxk2482/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/sxk2482/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
```

```
Diagnostic ID: BAF9C956-C1D3-46DD-8778-66825F230644
```

### Steps to reproduce the behavior

  1. Start a container
  2. Exit the container
  3. As soon as exit is entered in the terminal, docker crashes.
  
I've currently assigned 12 GB memory and 4 CPUs to Docker.

**Comment by djs55** [comment]
@shrikant-thd could you share an example (`docker-compose.yml`?) that triggers this crash for you?
