### ISSUE TITLE
No Docker.qcow2 or Docker.raw found: the VM has never been started

### ISSUE THREAD

**Issue by Zinger520** [docker/for-mac#2875]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Sorry, we can't investigate this issue without any diagnostics.
