### ISSUE TITLE
kuberenets is not showing anything

### ISSUE THREAD

**Issue by rrrangrej** [docker/for-mac#2882]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Expected behavior
kuberenets is  showing some context like docket-desktop
### Actual behavior
kuberenets is not showing anything

### Information

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...
  asd

**Comment by ajeetraina** [comment]
Hello @rrrangrej Kubernetes showing docker-desktop is expected behaviour. May I know what do you mean by Kubernetes not showing anything? What are you trying to achieve?

**Comment by rrrangrej** [comment]
Hi,

I was using Docker for Mac CE stable version as against expected Docker Edge version.
I am able to see kubernetes tab in preferences now.
Please close this ticket.

Regards
Raghavendra
