### ISSUE TITLE
Kubernetes not included with Docker for Mac (Edge, CE edition)

### ISSUE THREAD

**Issue by miikmaac** [docker/for-mac#2884]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - macOS Version: 10.13.4

### Expected behavior
Installed Docker CE Edge and expected Kubernetes options to appear in Docker > Preference menu.
 
### Actual behavior
Kubernetes is not present in Preference menu or 'About Docker' page. 
![screen shot 2018-05-07 at 12 36 58 pm](https://user-images.githubusercontent.com/20432078/39713080-5d09ffa6-51f3-11e8-86c9-f82843b20bee.png)

### Information

```
~$ cd /Applications/Docker.app/Contents/Resources/bin/
/Applications/Docker.app/Contents/Resources/bin$ ./docker-diagnose -u

{
  "os": "macOS: version 10.13.4 (build: 17E199)",
  "app": "version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)",
  "id": "EE656603-E8C1-4B4B-B31E-3DE47E5ADFF9",
  "timestamp": "20180507-133932",
  "logs": "/tmp/EE656603-E8C1-4B4B-B31E-3DE47E5ADFF9/20180507-133932.tar.gz",
  "tests": {
    "files": {
      "success": true,
      "message": []
    },
    "docker-cli": {
      "success": true,
      "message": []
    },
    "moby": {
      "success": true,
      "message": []
    },
    "driver.amd64-linux": {
      "success": true,
      "message": []
    },
    "vmnetd": {
      "success": true,
      "message": []
    },
    "osxfs": {
      "success": true,
      "message": []
    },
    "vpnkit": {
      "success": true,
      "message": []
    },
    "dns": {
      "success": true,
      "message": []
    },
    "disk": {
      "success": true,
      "message": []
    },
    "kubernetes": {
      "success": false,
      "message": [
        "kubernetes check failed with: (Failure\n   \"exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\\\n  \\n{{end}}': exit 1\")"
      ]
    },
    "env": {
      "success": true,
      "message": []
    },
    "app": {
      "success": true,
      "message": []
    },
    "virtualization VT-X": {
      "success": true,
      "message": []
    },
    "virtualization kern.hv_support": {
      "success": true,
      "message": []
    },
    "virtualization hypervisor": {
      "success": true,
      "message": []
    },
    "logs": {
      "success": true,
      "message": []
    },
    "app": {
      "success": true,
      "message": []
    },
    "moby-console": {
      "success": true,
      "message": []
    },
    "moby-syslog": {
      "success": true,
      "message": []
    },
    "moby": {
      "success": true,
      "message": []
    },
    "system": {
      "success": true,
      "message": []
    }

```

output of  `docker version`

```
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:58:56 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:06:49 2018
  OS/Arch:      linux/amd64
  Experimental: true

```

### Steps to reproduce the behavior

  1. Download Docker for Mac (Edge Edition): https://store.docker.com/editions/community/docker-ce-desktop-mac
  2. Install following instructions with DMG

**Comment by YRM64** [comment]
Miikmaac,

I would try reinstalling Docker for Mac.  Kubernetes has to be there as an icon  in the preference menu/configuration dialogue box.  You might have gotten ahold of a corrupted version of Docker.  You can go online to https://docs.docker.com and view just what the Docker Menu/dialogue configuration box looks like.  You will see kubernetes listed as an icon for you to access, click on, and set your configurations.

**Comment by miikmaac** [comment]
@YRM64 After uninstalling and trying a fresh install, I still am encountering the same problem with Kubernetes not appearing in the "Properties" menu or the "About Docker" page. the only difference now is that there's a Kubernetes drop down in the top menu, but it only lists different contexts and it seems the docker-for-desktop context is not present. How would I have gotten a corrupted download? I am downloading directly from the Docker website.

Thanks!
![screen shot 2018-05-08 at 7 23 12 am](https://user-images.githubusercontent.com/20432078/39754662-f4887914-5290-11e8-989a-2da40f6832a4.png)

**Comment by guillaume-eb** [comment]
Try signing in with your Docker account by clicking on "Sign in / Created Docker ID"

**Comment by YRM64** [comment]
Miikmaac, after following guilaume's comments, let me know if your still experiencing difficulty.

**Comment by YRM64** [comment]
Miikmaac, after following guilaume's advice, let me know if you're are still experiencing difficulty.

**Comment by miikmaac** [comment]
@guillaume-eb @YRM64 Thanks for the suggestion - actually, I have tried this quite a few times but I also cannot log into docker. I have tried changing passwords, etc... but the password is never accepted.

**Comment by mikecargal** [comment]
I am experiencing exactly the same issue.  (no Kubernetes tab, can't sign into Docker Hub, Kubernetes menu item, but no Docker for mac item)

FYI, in a corporate environment where an ntlm proxy frequently creates issues with these sorts of things.  Unfortunately, I can't find any sort of log messages to point in the direction of a resolution.

Going through the exact same process on my home machine worked just fine.

**Comment by mikecargal** [comment]
Update... My issue is definitely related to the ntlm proxy.  How can I identify what needs to be opened up through the proxy to allow for this to work?

**Comment by YRM64** [comment]
For those folks experiencing difficulty with Kubernetes, or for issues where Kubernetes is not showing up as an icon in the Docker menu/or Docker dialogue box, I'm providing information on how to install/set-up Kubernetes on your Mac operating system.  

1). Kubernetes is only available in Docker-for-Mac 17.12 CE and higher, ONLY on the edge channel.

2). Docker-for-Mac 17.12 CE and higher, Edge includes a standalone Kubernetes server that runs on Mac, so that you can test deploy your workloads on Kubernetes.  The client command, kubectl is included in your package and configured to connect to your Kubernetes server.  What most folks fail to do after installation is to check to verify that kubectl is installed and pointing to Docker-for desktop.  Sometimes, due to configurations, or due to mishaps, kubectl ends up pointing to the wrong environment, which could cause a whole host of issues.  If kubectl is pointing toward another environment you have to change context to get it pointing to the correct environment.  If you install kubectl with homebrew or some other method other than Docker-for-Mac, and you are experiencing difficulties, remove /usr/local/bin//kubectl.  To enable Kubernetes, click on enable Kubernetes, and click the apply and restart button.

3). For those of you not seeing a Kubernetes icon after installation, you can still install Kubernetes as a standalone, if need be, for developmental purposes only.  Install NodeJS & Docker Runtime for Mac.
4). Install Homebrew.
5). Install Xyve Driver (or Hyperkit Driver).
6). Install Minikube.
7). Install  Kubectl.
8). Start Minikube.
9). Access Kubernetes Dashboard.
10). Minikube Commands for Kubernetes.

For specific instructions on how to install, visit:  https://vitalflux.com/install-kubernetes-Mac-os-x/

Verify support of the above stated instructions through Github, or Docker-for-Mac.

**Comment by akimd** [comment]
Hi!
First of all I would like to thank @YRM64 for the time she gives to try to help Docker for Mac users, especially since there are too many issues for the Docker for Mac team to handle them alone.

The genuine problem (Kubernetes not enabled in 18.05) is due to the fact that Docker for Mac has not been able to reach some remote configuration file.  Please, make sure it can download `https://download.docker.com/mac/edge/appcast.xml`.

**Comment by mikecargal** [comment]
Thanks for the info.  However, I just tried that link (as well as all the addresses in that link), and when I try to do a Docker update, it still fails immediately.

If I could determine where more info was logged out, I'd be glad to scour the logs to track it down.  It's definitely hampering us.

**Comment by mikecargal** [comment]
I am successful in downloading the xml file you referenced.

features.json =>

{
    "banner": {
      "ratio": 1,
      "resources": {
        "expiration": "2018-06-01T00:00:00+0000",
        "image": "https://download.docker.com/mac/edge/dockercon-2018-banner.png",
        "key": "DockerCon 2018",
        "url": "https://dockercon18.smarteventscloud.com/portal/newreg.ww?utm_source=Docker%20desktop&utm_medium=banner&utm_campaign=DockerCon"
      }
    },
    "discoverEEV1": {
        "ratio": 1.0,
        "description": ""
    },
    "dockerCloudFederationV1": {
        "ratio": 1.0,
        "description": ""
    },
    "kubernetesV1": {
        "ratio": 1.0,
        "description": ""
    },
    "passthroughHTTPProxy": {
        "ratio": 1.0,
        "description": ""
    },
    "releaseNotesV1": {
        "ratio": 1.0,
        "description": ""
    },
    "swarmFederation": {
        "ratio": 1.0,
        "description": ""
    }
  }

**Comment by akimd** [comment]
Hum. Weird.

I need more information, please submit diagnostics.  You generated some, but did not upload them.

**Comment by mikecargal** [comment]
I'm not sure I'm going to be able to do that... sorry

I know that may leave you nothing to go on, but security here is really tight

**Comment by akimd** [comment]
@mikecargal I don't understand why Kube is not enabled for you: your features.json is fine, so you should see it.  Without diagnostics, I have no idea what's going on.

@miikmaac Yep, indeed, I was confused by your similar IDs :).  If you don't have the features.json file, then there is no way you'd have Kube.  I don't understand why your Windows coworker have it then.  And since you are able to download the app cast file, I don't understand why it wouldn't be able to fetch the features.json file...

**Comment by djs55** [comment]
@mikecargal you mention you have an `ntlm` proxy. Is it configured via Apple System Preferences -> Advanced -> Proxies or via the Docker Whale menu -> Proxies (or both?) Perhaps the Docker app is unable to fetch the `features.json` because it missed (or misunderstood) the proxy setting.

**Comment by akimd** [comment]
@miikmaac Diagnostics `EE656603-E8C1-4B4B-B31E-3DE47E5ADFF9/20180507-133932` have not been uploaded.  I can see you did pass `-u`, but the diagnostics are not were they should be, and it's quite unlikely that they have been erased.  So I guess there was a failure to upload them, and a failure to tell you so.

**Comment by mikecargal** [comment]
I'm using the System preferences Proxy config (with "System Config" checked in Docker prefs)

**Comment by miikmaac** [comment]
@akimd  do I need to run them again or will they still not be received by you?

**Comment by akimd** [comment]
@miikmaac I dunno :)  Try and post the ID please.

**Comment by miikmaac** [comment]
@akimd new diagnostics have the ID EE656603-E8C1-4B4B-B31E-3DE47E5ADFF9/20180514-140327

**Comment by mikecargal** [comment]
When I tried to run diagnostics to review the contents (to see if it would be acceptable to upload), I got a message about the upload failing.  (blocked network access is likely at the heart of this issue, so maybe not such a surprise)

——-
Side note... most apps that I’ve used to generate diagnostics give you a chance to look at the contents and then decide whether to upload.  There was no indication that it would automatically upload (that I noticed). For security minded companies, this is rather poor behavior on an app’s part.

**Comment by akimd** [comment]
@mikecargal FTR, we made changes yesterday about that (now you have to press a button for the diagnostics to be uploaded, will be part of 18.05), and I suggested an hour ago a "Reveal Diagnostics" button...

**Comment by mikecargal** [comment]
OK, I was able to get that run...  There are a LOT of files, so it'll take quite some time to determine if all are safe to upload (wherever).  Is there a particular place I should start looking?

**Comment by akimd** [comment]
I would check in HOME and Group_Containers first.

**Comment by mikecargal** [comment]
OK, I couple of things I've spotted so far...

**http-docker.err**
Get https://www.docker.com/: x509: certificate signed by unknown authority

**http-docker-ip**
```
The Internet Site you are trying to access has not been categorized by our proxy vendor and as such, access is blocked.  (for http://104.239.220.248//)
```
We'll need to know what this is to get it unblocked.

**DockerAppStderr.txt**
```
May  9 09:30:45  Docker [Sparkle][18383] <Error>: Error: An error occurred in retrieving update information. Please try again later. An SSL error has occurred and a secure connection to the server cannot be made. (URL https://download.docker.com/mac/edge/appcast.xml)
May  9 09:30:45  Docker [Sparkle][18383] <Error>: Error: An SSL error has occurred and a secure connection to the server cannot be made. (null) (URL https://download.docker.com/mac/edge/appcast.xml)
May  9 09:30:45  Docker [Sparkle][18383] <Error>: Error: An SSL error has occurred and a secure connection to the server cannot be made. (null) (URL https://download.docker.com/mac/edge/appcast.xml)
```
(We can hit this through the browser, and Docker is configured to use the System proxy settings)

**diagnose.err.log**
```
time="2018-05-17T13:23:24Z" level=warning msg="Get https://www.docker.com/: x509: certificate signed by unknown authority" package=gather type=http
```

**Comment by miikmaac** [comment]
Hi @akimd - looking through the folders you recommend, I see one error that stands out:

*Group_Containers/DockerAppStderr.txt*
`2018-05-21 10:47:56.180 Docker[33001:1386842] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)`

Also the HOME folder for me is actually empty - there's one directory inside HOME called dot-docker however this dir is also empty..

**Comment by akimd** [comment]
@miikmaac The most interesting file to understand the sequence of events is `docker-system-os.log`.  But it's very long.  Alternatively, you should look at the log in live.  See https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs.

**Comment by YRM64** [comment]
Akmid,

Thank you for thanking me.  I realize your case load is heavy, and I do what I can to ease that workload.  However, it's also a great way for me to stay actively engaged, while helping others, and it's a way for me to self-educate.  It's important for me to read how developers are doing, and how they feel about the status of their applications, and as an administrator, to listen to them express their feelings pertaining to their inability to access certain pertinent information.  It's been a pleasure to work on behalf of the community, and to aid in easing workloads for everyone involved.

**Comment by wskkirawang** [comment]
I got the same problem

mac: 10.13.4 high sierra
docker: 18.05.0-ce-mac67


install and uninstall many times,
still  can't see the kubernetes tab on the preference diagnose
..
I feel stressed

**Comment by giri786** [comment]
Workaround which worked for me.

Ran into same issue , using the apple console log application  filtering using "process:docker
error" saw SSL errors connecting to download.docker.com and api.segment.io.

using "nscurl --ats-diagnostics https://download.docker.com:443  --verbose" noticed that the default requests fail but pass when NSExceptionRequiresForwardSecrecy is false.

edited the /Applications/Docker.app/Contents/info.plist and added the following entry

<plist version="1.0">
<dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>api.segment.io</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>download.docker.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
...
