### ISSUE TITLE
Docker for mac host crashes - B6349DAD-3786-4A83-B9C8-B68F1C1A8A6C

### ISSUE THREAD

**Issue by melaniebdc** [docker/for-mac#2887]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version: version 10.13.4 (build: 17E202)

### Expected behavior
 not crashing
### Actual behavior
crashing
### Information

```
Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/B6349DAD-3786-4A83-B9C8-B68F1C1A8A6C/20180507-171108.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/mcalignon/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/mcalignon/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mcalignon/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. 
docker pull openjdk:9-jdk
docker pull redis
docker pull mysql
docker pull mongo
docker pull elasticsearch
docker pull tomcat
docker pull docker.bintray.io/jfrog/artifactory-oss:latest
  2. 
docker run -itdP -h redis --name redis redis
docker run -itdP -h mongo --name mongo mongo
docker run -itdP -h elasticsearch --name elasticsearch elasticsearch
docker run -itdP -h tomcat --name tomcat tomcat
docker run -itdP -h artifactory --name artifactory docker.bintray.io/jfrog/artifactory-oss 
docker run -itdP -h mysql --name mysql mysql

Wait a bit... then it just fails.
Updated my mac this morning. tried with both edge and non edge version :(

**Comment by adzfaulkner** [comment]
+1

**Comment by cannibal** [comment]
+1

**Comment by meodemsao** [comment]
+1

**Comment by jfeilbach** [comment]
+1

**Comment by YRM64** [comment]
Developers,

Crashes can occur on updates; when you spin up your containers all at once (suggestion: spin up containers one by one, providing long pauses in between), and if you have a ~/ .docker/certs.d folder containing symbolic links.  However, most crashes occur with updating to 17.06.2-CE-mac27 (19124) on MacOS 10.12.6.

Another reason for crashing involves running tests of Ansible roles using Docker containers that run systemd.  The effect of systemd inside the container ~ spawning getty instances.  The result - 
a recursion, causing the kernel to lock resulting in a crash of the Docker host.  Words of wisdom from joshbenner, "prevent the getty service from starting inside the container."
