### ISSUE TITLE
Stuck in "is starting"

### ISSUE THREAD

**Issue by salmiakki** [docker/for-mac#2889]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version: 10.13.3 (build: 17D47)

Diagnostic ID: CFEAD4F3-CEC7-49C3-A49C-CF0E590D33C5

### Expected behavior

Docker starts

### Actual behavior

Docker is stuck in "is starting"

### Information

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D47)
logs: /tmp/CFEAD4F3-CEC7-49C3-A49C-CF0E590D33C5/20180508-195728.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk


```

### Steps to reproduce the behavior

  1. Start Docker

If I reinstall Docker it might start. Or it might not. So I reinstall it until it starts (it takes half a dozen times if I'm lucky). If it starts, it works fine until reboot.

**Comment by YRM64** [comment]
Salmiakki,

Don't feel bad, if my laptop was up and running Docker would still be trying to finish starting, and I initially installed it a couple of months ago.  I reinstalled 3 times, and each time it produced the same behavior: Docker is still starting, hours, and hours after installation; it never did finish starting.  I was using MacOs, version 12.6.3.  I wish I could tell you that I finally got it up and fully running, but I've only had a taste of what Docker has to offer.  My endeavors is a work in progress.  Please report back to us what steps you taken to finally get Moby the whale up and moving.  Thanks!

**Comment by manibh** [comment]
I have the same issue 

Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/5AD42584-8C8F-43AF-97A1-41279E3CB3DC/20180510-101014.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")


[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##

**Comment by wx2228** [comment]
same issue here

**Comment by wx2228** [comment]
reinstalling docker solved this issue for me.
