### ISSUE TITLE
kubectl overrides /usr/local/bin/kubectl  when Kubernetes is enabled

### ISSUE THREAD

**Issue by xueshanf** [docker/for-mac#2890]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - macOS Version: 10.12.6

### Expected behavior
should not override existing /usr/local/bin/kubectl installation

### Actual behavior
/usr/local/bin/kubectl is replaced with docker's installation. The existing one is renamed to kubectl.backup.

### Steps to reproduce the behavior

  1. brew install kubectl

```console
$ ls -l  /usr/local/bin/kubectl
/usr/local/bin/kubectl -> ../Cellar/kubernetes-cli/1.10.1/bin/kubectl
```

  2. Install docker-for-mac edge, enable  kuberneters

```console
$ ls -l /usr/local/bin/kubectl
/usr/local/bin/kubectl -> /Applications/Docker.app/Contents/Resources/bin
/usr/local/bin/kubectl.backup ->  ../Cellar/kubernetes-cli/1.10.1/bin/kubectl
```
 
The version installed by Docker-for-Mac is v1.9.x,  it doesn't work with some features that requires v1.10.x, such as AWS authentication with heptio-aws-auth plugin. 

Maybe Docker-for-Mac installer should test existing /usr/local/bin/kubectl and not try to replace it, or at least gives users an option to override or not?

**Comment by YRM64** [comment]
Allegedly, Kubecti is no longer disabling Kubernetes (#2508).  If you are still experiencing difficulty  with Docker for Mac overwriting or deleting kubecti during the activation or disabling of kubernetes, hit me up here.

**Comment by xueshanf** [comment]
@YRM64 The issue is slightly different than #2508, I think. 

Before enable Docker-for-Mac with Kubernetes enabled:

```console$ ls -l /usr/local/bin/kubectl
lrwxr-xr-x  1 root  admin  43 May  2 14:51 /usr/local/bin/kubectl -> ../Cellar/kubernetes-cli/1.10.1/bin/kubect
```
After enabled Kubernetes in Docker-for-Mac:

```console
ls -l /usr/local/bin/kubectl*
lrwxr-xr-x  1 sfeng  staff  55 May  9 13:17 /usr/local/bin/kubectl -> /Applications/Docker.app/Contents/Resources/bin/kubectl
lrwxr-xr-x  1 root   admin  43 May  2 14:51 /usr/local/bin/kubectl.backup -> ../Cellar/kubernetes-cli/1.10.1/bin/kubectl
```
As you can see the binary installed by `brew` was replaced to a different binary, which breaks other functions that require the latest kubectl (1.10.1)

After  disabling  Kubernetes cluster in docker-for-mac:

```console
$ ls -l /usr/local/bin/kubectl*
lrwxr-xr-x  1 root  admin  43 May  2 14:51 /usr/local/bin/kubectl -> ../Cellar/kubernetes-cli/1.10.1/bin/kubectl
```
The brew installed kubectl is restored, which is #2508 talked about.

My issue is that the kubectl installed by user through other means in /usr/local/bin should not be replaced. It breaks functionality such as aws authentication use case.

Info about Docker-for-mac installation:

```console
$ ./docker-diagnose -u
macOS: version 10.12.6 (build: 16G1212)
Docker.app: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
```

**Comment by YRM64** [comment]
Thanks Xueshanf, will research this one, and will get back to you. Did you try removing /user/local/bin/kubectl?  I know if you install kubectl via Homebrew or other method, and start to experience issues such as replacing your binary, and impacting other functionalities, you're suppose to remove your /usr/local/bin/kubectl.  Please update me at your earliest convenience.

**Comment by xueshanf** [comment]
@YRM64 Yes, we are telling people who try Docker-for-Mac kubernees integration to remove /usr/local/bin/kubectl and do a `brew reinstall kubectl` as a workaround.

**Comment by YRM64** [comment]
Xueshanf, I'm going to give you a couple of troubleshooting tips:
1). If you still have kubectl installed, check to see what environment it's pointing to.  
2) if it's pointing to some other environment other than docker-for-desktop you have to change the 
     context.
3) run the following:  kubectl confit get-contexts
                                    Kubectl config use-context Docker-for-desktop
4) if you enable Kubernetes support, images are automatically downloaded and instantiated, and the 
     /user/local/bin/kubectl command is installed for you on you OS. 
5) docker service ls (kubernetes) won't show your containers because manual support is not 
    provided.  However, you can see them if you hit the advanced tab and select show system 
    containers.  Click apply, and restart.  Although, most users won't need to perform #5; since you're
    experiencing functionality issues, I would like for you to start over from scratch to see if you missed
    one of the steps listed above; if not, we can escalate your case up to a senior developer.

**Comment by YRM64** [comment]
General information when working with Kubernetes, on Docker for Mac. When you're utilizing kubectl, you install your binary on a UCP Manager or worker node.  You have to install the UCP client bundle to access cluster with kubectl . On any node in your cluster you can retrieve a kubectl binary:
Curl -LO https://storage.googleapis.com.  If your experiencing difficulty with Kubernetes, you have the option to override your default orchestrator.  Also, you must make sure that the kubectl version you've installed through methods outside of Docker is current and up-to-date.  If not, an outdated version will cause interruptions.

**Comment by YRM64** [comment]
General information when working with Kubernetes, on Docker for Mac. When you're utilizing kubectl, you install your binary on a UCP Manager or worker node.  You have to install the UCP client bundle to access cluster with kubectl . On any node in your cluster you can retrieve a kubectl binary:
Curl -LO https://storage.googleapis.com.  If your experiencing difficulty with Kubernetes, you have the option to override your default orchestrator.  Also, you must make sure that the kubectl version you've installed through methods outside of Docker is current and up-to-date.  If not, an outdated version will cause interruptions.

**Comment by YRM64** [comment]
General information when working with Kubernetes, on Docker for Mac. When you're utilizing kubectl, you install your binary on a UCP Manager or worker node.  You have to install the UCP client bundle to access cluster with kubectl . On any node in your cluster you can retrieve a kubectl binary:
Curl -LO https://storage.googleapis.com.  If your experiencing difficulty with Kubernetes, you have the option to override your default orchestrator.  Also, you must make sure that the kubectl version you've installed through methods outside of Docker is current and up-to-date.  If not, an outdated version will cause interruptions.

**Comment by xueshanf** [comment]
@YRM64 Maybe I did not  make myself clear. The Docker-for-Mac with Kubernetes function works fine. I can run guestbooks app, run kubeclt to get pods, switch context with kubectl config... tot a problem. 
The problem is kubectl v1.9.6 installed by Docker-for-Mac installation doesn't work with new features in v1.10.1, such as service port forwarding, heptio-aws-auth plugin etc.  I have to save another kubectl v1.10.1 to my home/bin directory in order to use it. That's a workaround, but not everyone in my team has $HOME/bin in their path..

I listed the steps so you can see that brew installed kubectl was replaced by Docker-for-Mac/kubernetes. All I ask is if Docker-for-Mac  does not replace existing kubectl, or use i's own path for kubectl installed by it.

**Comment by sohan** [comment]
Found some related, unresolved discussion here: https://github.com/docker/for-mac/issues/2368

I agree it's frustrating that D4M constantly overwrites your existing kubectl. Our team also needs features from kubectl v1.10+, but D4M keeps updating /usr/local/bin/kubectl with one that's v1.9.6

**Comment by akimd** [comment]
Hi all,
We also have many users who are very happy that we provide this kubectl.  What would you propose?  How about:
- we always install a /usr/local/bin/kubectl.docker
- if there is no /usr/local/bin/kubectl, we also install our symlink
?

**Comment by sohan** [comment]
Thanks @akimd for looking into this. Bringing your own kubectl is definitely not the common case, so I appreciate your time here!

> * we always install a /usr/local/bin/kubectl.docker
> * if there is no /usr/local/bin/kubectl, we also install our symlink

That proposal would work well for us!

**Comment by xueshanf** [comment]
@akimd I think this proposal should work. If users later time want to install kubectl with tools such as  brew, it will complain the link but it’s an easy fix. Thanks!

**Comment by YRM64** [comment]
Xueshanf, thank you for that point of clarification, it changes the focus of my research efforts.  Thanks so much.

**Comment by YRM64** [comment]
Xueshanf, 

I'm in support for a permanent fix for this issue for the following reasons:

First, there isn't any Kubernetes support for Docker-for-Mac, the stable release version.

Second, the Docker-for-Mac Kubernetes version is a bare-medal version that won't allow developers to access some of the latest features, and it poses significant issues when working with the Docker-for-Mac version of v1.9.6 and/or later versions.

Third, you are correct in your assertion that Docker-for-Mac could check/test for an existing binary (user/local//bin) to ascertain whether it's compatible with Docker-for-Mac's Kubernetes version, therefore, if it isn't, developers could be given the option to replace or remove their binary.  You're also correct in your position that Docker shouldn't automatically replace binaries; instead give users the option to decide how this issue is to be handled.

Fourth, the Kubernetes Server runs locally and is not configurable, leaving developers, such as yourself in a bind.

Your case is similar to #2368; the actual behavior is similar.  In the expected outcome, there are differences.  As #2368 stipulates, you have to be certain to uncheck the Kubernetes check box in Docker-for-Mac's preferences, or trouble lies ahead, especially when installing with Homebrew.

In terms of designing an override, we have several options.  One design could include a source code from the command line, overriding the default values of the Docker-for-Mac Kubernetes/Kubectl, and any corresponding environment variables.  Another option is a work-around, like installing Kubernetes with a different name.  As #2368 stated, we could add a Kubectl profile.  If I were designing based solely upon your specific facts and circumstances, I would design to override the default orchestrator (swarm, Kubernetes, etc.) of Docker-for-Mac.

**Comment by akimd** [comment]
@YRM64 I appreciate your spontaneous help, but note that the way you write might let people think you work for Docker.  Please, make your posts clearer on that regard.

**Comment by akimd** [comment]
I believe that https://download-stage.docker.com/mac/pr/24668/Docker.dmg should address your concerns.  Please confirm.

**Comment by YRM64** [comment]
akmid,

Ok, I will sign my postings with my official signature.  For purposes of clarification, I don't work for Docker, Microsoft, or Github.

**Comment by YRM64** [comment]
Akimd,

I couldn’t get that link to open from my cell
(the download stage.docker.com link).  I tried it 3 times.  My internet could have coincidentally went out when I tried it from my cell, so I’ll try it again later.

**Comment by akimd** [comment]
(FTR, my first name is Akim :).

I checked again, the link is still functional.

**Comment by akimd** [comment]
I'm closing this issue because I fixed this behavior.  I'd be happy to have user feedback though, so don't hesitate posting results here.

**Comment by Samox** [comment]
Is this problem related to this issue ? https://github.com/docker/for-mac/issues/3642
