### ISSUE TITLE
Docker fails to load DIAG ID: 862EC01A-0180-446A-BC6B-A8359A1FD7FD/20180509-074519

### ISSUE THREAD

**Issue by jmignault** [docker/for-mac#2891]
862EC01A-0180-446A-BC6B-A8359A1FD7FD/20180509-074519

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Information

```
Docker for Mac: version: 18.04.0-ce-rc2-mac61 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/862EC01A-0180-446A-BC6B-A8359A1FD7FD/20180509-074519.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jmignault/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jmignault/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jmignault/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
```
Docker for Mac: version...

```
<!--
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
  -->

### Steps to reproduce the behavior

  1. starting the application.
  2. ...

**Comment by YRM64** [comment]
A word of encouragement for developers.  You have entered a world where technology is rapidly advancing.  Your job is the wave of the future. Today, 20% of global enterprises run containerized applications according to Gartner Market Guide for Container Management Software (August 2017).  This all changes by 2020 ~ employers will be looking for folks who can build, orchestrate, develop and deploy.  In this field, patience, mental and physical disciple are significant skillsets.  IDC and Gartner says by 2021, "more than 95% of new microservices will be deployed in containers".

**Comment by akimd** [comment]
Hi @jmignault 
Your logs look not too bad, I don't see why it failed to start.  Have you tried several times?  Have you tried to reset?  Was it working before?  Did it appear since an update?

**Comment by akimd** [comment]
@jmignault ping.
