### ISSUE TITLE
9167B789-9698-4EC3-BA62-AAF5F8B4B0AD

### ISSUE THREAD

**Issue by asvechkar** [docker/for-mac#2893]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version:10.13.4

### Information

```
Docker for Mac: Version 18.05.0-ce-rc1-mac63 (24246)
Channel: edge
3b5a9a44cd
```

### Steps to reproduce the behavior

  Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/9167B789-9698-4EC3-BA62-AAF5F8B4B0AD/20180510-143742.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --debug --info --style syslog --last \"1d\" --predicate \"process matches \\\".*(ocker|vpnkit).*\\\" || (process in {\\\"taskgated-helper\\\", \\\"launchservicesd\\\", \\\"kernel\\\"} && eventMessage contains[c] \\\"docker\\\")\" >\"/tmp/9167B789-9698-4EC3-BA62-AAF5F8B4B0AD/20180510-143742/docker-system-os.log\" 2>&1: exit 65")
[OK]     docker-cli
[OK]     disk

**Comment by akimd** [comment]
The system logger seems unhappy:
```
log: warning: The log archive contains partial or missing metadata
log: cannot use --last when archive metadata is missing
```

but Docker for Mac seems to be fine.  Thanks for the report.
