### ISSUE TITLE
Kubernetes error on docker latest version

### ISSUE THREAD

**Issue by ananth777** [docker/for-mac#2901]
Hi There,

Any idea on the below error. May latest Mac is 10.13.3

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics EE996810-F5DC-4DC2-9F07-33E27953DD98
  - [ ] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Information
EE996810-F5DC-4DC2-9F07-33E27953DD98
<img width="832" alt="screen shot 2018-05-11 at 1 28 13 pm" src="https://user-images.githubusercontent.com/20490917/39917607-30ac4426-551f-11e8-93a2-e6ecbf53e1f4.png">

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by YRM64** [comment]
Without seeing expected and actual behavior, my response is to see my comments under #2884.

**Comment by akimd** [comment]
False positive: it is the diagnostic tool that was too zealous in trying to check kube support, although it is not enabled.  Sorry about that, we will fix it.  Thanks!
