### ISSUE TITLE
name : linuxkit-025000000001

### ISSUE THREAD

**Issue by chpiero** [docker/for-mac#2902]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - macOS Version:

### Information

```
Docker for Mac: version 18.03.1-ce

```

### Steps to reproduce the behavior

why the name is always linuxkit-025000000001
is possible to change? my hostname is different
Thanks

**Comment by akimd** [comment]
Please clarify.

**Comment by thaJeztah** [comment]
On Docker for Mac, the docker daemon runs in a lightweight VM that has its own hostname, so the hostname you see is the hostname of the VM;

```bash
docker node ls

ID                            HOSTNAME                STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
oifk2p0hd4tvlb62uf76womx0 *   linuxkit-025000000001   Ready               Active              Leader              18.05.0-ce-rc1
```   

It's possible to update the hostname by running a container that share's the host's uts namespace, and has capabilities to change the hostname.


The example below starts a container in the host's uts namespace, so changing the hostname inside the container, changes the hostname on the host (VM);


```bash
$ docker run -it --rm --uts=host --cap-add SYS_ADMIN busybox
hostname myhostname
exit
```

Now the hostname of the VM is updated;

```bash
docker node ls

ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
oifk2p0hd4tvlb62uf76womx0 *   myhostname          Ready               Active              Leader              18.05.0-ce-rc1
```

**Comment by akimd** [comment]
@thaJeztah Are you suggesting that D4D should do that by default?

**Comment by thaJeztah** [comment]
@akimd Mainly left the comment to explain why it didn't match the OS X host.

t.b.h., I'm not sure if it should automatically match the OS X host; could have side effects? (not sure)

**Comment by djs55** [comment]
Perhaps we should change it to something like `docker-for-desktop`?

**Comment by akimd** [comment]
I fear this might introduce confusion between host and guest.  Is it just a hostname, or can we do something composite like `guest.docker.internal`?  Or `vm.docker.internal` (or `0.vms.docker.internal` of course).

**Comment by orubel** [comment]
should match hostname; that way it shows up on networks/SWARMS/etc without confusion. Using OS makes it confusing as you will end up with 15 MAC and 20 WINDOWS on the same network.

Default it to hostname so swarms/networks can better identify machine and host with docker.

**Comment by orubel** [comment]
Oh I also just spotted this... the names need to have the PROC type at the end. I have mixed environment of Intel64 and ARM. 

So for the image name I would suggest 'hostname_64' or 'hostname_ARM'. This would save the most confusion in all environments.

**Comment by thaJeztah** [comment]
Don't think we should add architecture to those hostnames; it would be a sliding slope (next we would be adding memory, disk-type, etc etc)

**Comment by orubel** [comment]
I suppose thats true. Having 'hostname' alone, you should KNOW what your own architecture. And of course, you can always 'ping' it to get that data

**Comment by orubel** [comment]
I guess what I am saying is, having that in the name lets people know to deploy an appropriate image to the machine. You don't need mem, disk-type and all that because they don't help with deploying images. The proc type is VERY important for deploying images from a MASTER in a MIXED environment.

You have to look at this from the viepoint of a Docker Swarm Mixed Environment or just a Docker Mixed Environment.

And with Edge Computing this is becoming VERY common.

**Comment by shanekorbel** [comment]
> On Docker for Mac, the docker daemon runs in a lightweight VM that has its own hostname, so the hostname you see is the hostname of the VM;
> 
> ```shell
> docker node ls
> 
> ID                            HOSTNAME                STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
> oifk2p0hd4tvlb62uf76womx0 *   linuxkit-025000000001   Ready               Active              Leader              18.05.0-ce-rc1
> ```
> 
> It's possible to update the hostname by running a container that share's the host's uts namespace, and has capabilities to change the hostname.
> 
> The example below starts a container in the host's uts namespace, so changing the hostname inside the container, changes the hostname on the host (VM);
> 
> ```shell
> $ docker run -it --rm --uts=host --cap-add SYS_ADMIN busybox
> hostname myhostname
> exit
> ```
> 
> Now the hostname of the VM is updated;
> 
> ```shell
> docker node ls
> 
> ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
> oifk2p0hd4tvlb62uf76womx0 *   myhostname          Ready               Active              Leader              18.05.0-ce-rc1
> ```

How to persist this hostname when the system reboots?
