### ISSUE TITLE
Populating volume from container seems to be broken for files bigger than 2Gb

### ISSUE THREAD

**Issue by andrey-vorobiev** [docker/for-mac#2905]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - macOS Version: 10.13.4 (17E199)
  - Diagnostic ID: C7673E91-6CCC-4572-9084-B6C6C2B38BA0

### Expected behavior
File in volume has the same size that in container (2621440000 bytes) after copy.

### Actual behavior
File in volume has smaller size (only 2147479552 bytes).

### Information

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/C7673E91-6CCC-4572-9084-B6C6C2B38BA0/20180515-113656.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Create Dockerfile with following contents
      ```
      FROM oraclelinux:7
      RUN mkdir -p /opt/xxx
      RUN dd if=/dev/zero of=/opt/xxx/bigfile count=$((1024 * 2500)) bs=1024
      ```
  2. Build image
      ```
      docker build  -t xxx .
      ```
  3. Start container
      ```
      docker run --rm -it --name xxx --mount 'destination=/opt/xxx' xxx:latest
      ```
  4. Check size of '/opt/xxx/bigfile'
      ```
      ls -l /opt/xxx/bigfile
      ```
  6. It's only 2147479552 bytes but must be 2621440000 bytes.

### Additional info
- This behaviour is not MacOS specific and can reproduced at least at CentOS 7.
- It seems that such behaviour was introduced in '18.03.0-ce-mac59'  version or later.

**Comment by thaJeztah** [comment]
Trying to reproduce, but don't see this happening;

```bash
docker build --no-cache -<<'EOF'
FROM oraclelinux:7
RUN mkdir -p /opt/xxx
RUN dd if=/dev/zero of=/opt/xxx/bigfile count=$((1024 * 2500)) bs=1024 \
 && ls -l /opt/xxx/bigfile
RUN ls -l /opt/xxx/bigfile
EOF
```



```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM oraclelinux:7
7: Pulling from library/oraclelinux
1b19d6599a70: Pull complete 
Digest: sha256:6067eb9ac8edc2042508e2adfd00b9fb1cc1d38e708d0f5f98058a8740ba0661
Status: Downloaded newer image for oraclelinux:7
 ---> af8cf7fc5b7e
Step 2/4 : RUN mkdir -p /opt/xxx
 ---> Running in d52136d812f5
Removing intermediate container d52136d812f5
 ---> 2f3d5ee09aaa
Step 3/4 : RUN dd if=/dev/zero of=/opt/xxx/bigfile count=$((1024 * 2500)) bs=1024  && ls -l /opt/xxx/bigfile
 ---> Running in b8f2510fc77e
2560000+0 records in
2560000+0 records out
2621440000 bytes (2.6 GB) copied, 13.3427 s, 196 MB/s
-rw-r--r-- 1 root root 2621440000 May 16 10:34 /opt/xxx/bigfile
Removing intermediate container b8f2510fc77e
 ---> f4a1002e897f
Step 4/4 : RUN ls -l /opt/xxx/bigfile
 ---> Running in f1b9c9e0a2f8
-rw-r--r-- 1 root root 2621440000 May 16 10:34 /opt/xxx/bigfile
Removing intermediate container f1b9c9e0a2f8
 ---> 08a4cdbeb9c5
Successfully built 08a4cdbeb9c5
```

```bash
docker run --rm 08a4cdbeb9c5 ls -l /opt/xxx/bigfile
-rw-r--r-- 1 root root 2621440000 May 16 10:34 /opt/xxx/bigfile
```

**Comment by thaJeztah** [comment]
Oh, never mind; it's only in a volume (sorry); in the volume the size is indeed limited;

```
docker run --rm  --mount 'destination=/opt/xxx' 08a4cdbeb9c5 ls -l /opt/xxx/bigfile
-rw-r--r-- 1 root root 2147479552 May 16 10:34 /opt/xxx/bigfile
```

**Comment by thaJeztah** [comment]
Digging into what changed recently:

Relevant code is [`daemon.populateVolumes()`](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/daemon/create_unix.go#L65-L81)
- -> [1container.CopyImagePathContent()`](https://github.com/moby/moby/blob/6f68db8c7a94489b5e66bb828f748d0baa2e5c22/container/container_unix.go#L124-L152) (last updated 10 months ago)
- -> [`container.copyExistingContents()`](https://github.com/moby/moby/blob/6f68db8c7a94489b5e66bb828f748d0baa2e5c22/container/container_unix.go#L390-L402) (last updated 11 months ago)
- -> [`fs.CopyDir()`](https://github.com/moby/moby/blob/f0947a541866ca05b030afe07dd659887a655e3e/vendor/github.com/containerd/continuity/fs/copy.go#L19-L119)

Last one actually changed 3 months ago in https://github.com/moby/moby/commit/b3aab5e31faf04d8a29f17be55562e4d0c0cb364 (https://github.com/moby/moby/pull/36290), when we switched to use the https://github.com/containerd/continuity package

Possibly relevant; https://github.com/moby/moby/commit/f0947a541866ca05b030afe07dd659887a655e3e (https://github.com/moby/moby/pull/36339) ("Update containerd/continuity to fix ARM 32-bit builds")

**Comment by thaJeztah** [comment]
I suspect this line is the culprit: https://github.com/moby/moby/blob/f0947a541866ca05b030afe07dd659887a655e3e/vendor/github.com/containerd/continuity/fs/copy_linux.go#L52

```go
n, err := unix.CopyFileRange(int(src.Fd()), nil, int(dst.Fd()), nil, int(st.Size()), 0)
```

It's using `int` for the file-range, which is signed, 32-bit

**Comment by thaJeztah** [comment]
Hm, actually there's more code there to produce an error in those cases 🤔 

```go
if int64(n) != st.Size() {
	return errors.Wrapf(err, "short copy: %d of %d", int64(n), st.Size())
}
```

**Comment by thaJeztah** [comment]
I added some debugging lines to the code to see what happens;

```patch
diff --git a/vendor/github.com/containerd/continuity/fs/copy_linux.go b/vendor/github.com/containerd/continuity/fs/copy_linux.go
index cfab6756b8..9b02761074 100644
--- a/vendor/github.com/containerd/continuity/fs/copy_linux.go
+++ b/vendor/github.com/containerd/continuity/fs/copy_linux.go
@@ -1,6 +1,7 @@
 package fs
 
 import (
+       "fmt"
        "io"
        "os"
        "syscall"
@@ -49,6 +50,7 @@ func copyFileContent(dst, src *os.File) error {
                return errors.Wrap(err, "unable to stat source")
        }
 
+       fmt.Printf("DEBUGGING: Copying %s size: %d int32: %d\n", src.Name(), st.Size(), int(st.Size()))
        n, err := unix.CopyFileRange(int(src.Fd()), nil, int(dst.Fd()), nil, int(st.Size()), 0)
        if err != nil {
                if err != unix.ENOSYS && err != unix.EXDEV {
@@ -60,8 +62,9 @@ func copyFileContent(dst, src *os.File) error {
                bufferPool.Put(buf)
                return err
        }
-
+       fmt.Printf("DEBUGGING: copied: %d of %d\n", int64(n), st.Size())
        if int64(n) != st.Size() {
+               fmt.Printf("DEBUGGING: short copy: %d of %d\n", int64(n), st.Size())
                return errors.Wrapf(err, "short copy: %d of %d", int64(n), st.Size())
        }
```

Which produced:

```
DEBUGGING: Copying /var/lib/docker/overlay2/c2da15c3236b5e57cbacc56d3bf017639507a2f9666d9dd5dd656b6f8181a7db/merged/opt/xxx/bigfile size: 2621440000 int32: 2621440000
DEBUGGING: copied: 2147479552 of 2621440000
DEBUGGING: short copy: 2147479552 of 2621440000
```

So from the above:

- `st.Size()` and `int(st.Size()` both show the correct (`2621440000`) value
- Partial (short) copy happens in [`unix.CopyFileRange()`](https://github.com/moby/moby/blob/6f66ccaf507e58f3031a88ec85a84a77c0c3b928/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go#L465-L472) ([last updated 11 months ago](https://github.com/moby/moby/blame/6f66ccaf507e58f3031a88ec85a84a77c0c3b928/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go#L465-L472))
  -> gccgo [`Syscall6()`](https://github.com/moby/moby/blob/6f66ccaf507e58f3031a88ec85a84a77c0c3b928/vendor/golang.org/x/sys/unix/gccgo.go#L34-L39) -> [`gccgoRealSyscall()`](https://github.com/moby/moby/blob/6f66ccaf507e58f3031a88ec85a84a77c0c3b928/vendor/golang.org/x/sys/unix/gccgo_c.c#L24-L32) (both last updated over 2 years go)
- The `short copy: 2147479552 of 2621440000` error is somehow not showing up / trickling back to the user


ping @kolyshkin @cpuguy83 perhaps you have an idea?

**Comment by thaJeztah** [comment]
Orthogonal, but; `unix.CopyFileRange()` was added in https://github.com/golang/sys/commit/f845067cf72a21fb4929b0e6a35273bd83b56396#diff-f2044a23f1527d820f9695720e7d59be (by @dmcgowan)

From that commit's description:

```
Introduces the CopyFileRange syscall which first appears in Linux 4.5.
Allows copying file content between file descriptors within the kernel
without transferring data to user space. This syscall also allows the
kernel to take advantage of reflinking or other fast copy methods on
supported file systems.
http://man7.org/linux/man-pages/man2/copy_file_range.2.html
```

Wondering where we handle kernel < 4.5

**Comment by cpuguy83** [comment]
@thaJeztah It falls back to a userspace copy: https://github.com/containerd/continuity/blob/master/fs/copy_linux.go#L59

**Comment by thaJeztah** [comment]
Ah! Overlooked that one, thanks!

**Comment by justincormack** [comment]
Short copies need to be handled properly, the kernel will never copy more than 2GB in a single syscall...

**Comment by cpuguy83** [comment]
Working on a fix for this.

**Comment by cpuguy83** [comment]
Fix is here: https://github.com/containerd/continuity/pull/114

**Comment by jlabonski** [comment]
This has been driving me crazy with my sqlserver image as it straddles the 2GB boundary.

**Comment by thaJeztah** [comment]
Fix for this issue should be in all current releases, so let me close this one
