### ISSUE TITLE
Unable to start docker container

### ISSUE THREAD

**Issue by hpkulkarni** [docker/for-mac#2910]
Tracking id 038CDE2D-2A7B-49B6-AD50-CFEC964FAF37

Unable to start docker container 

Hrushikesh:~ hrushikesh$ sudo docker run docker run -d -p 8088:80 -p 3307:3306 tutum/lamp
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Hrushikesh:~ hrushikesh$ eval "$(docker-machine env default)"
Error checking TLS connection: Host is not running

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
This is 18.05.0-ce-rc1-mac63.  Please try a more recent version.
