### ISSUE TITLE
I don't find the docker0 interface on my Mac OSX High Sierra

### ISSUE THREAD

**Issue by cepsum** [docker/for-mac#2912]
Hello,

Normally, after the Docker installation, I should see a docker0 interface, but I don't see it and I don't now how I can create it.

Version:
- docker : Version 18.03.1-ce-mac65 (24312)
- Mac : 10.13.4 (17E202) High Sierra

I tried to uninstall and install
I tried to reset, but the problem is the same.

Another point that is important, I have another virtualization solutions like VMware Fusion and Virtualbox which create some other network interface.

Somebody know a solution for that.

Best regards.

**Comment by ajeetraina** [comment]
There is no docker0 bridge on macOS because of the way networking is implemented in Docker for Mac, you cannot see a docker0 interface on the host. This interface is actually within the virtual machine. Docker for Mac actually runs on  Linuxkit VM.

**Comment by cepsum** [comment]
Ah OK

Thank you for your answer.

Have a nice day...
