### ISSUE TITLE
Why is docker consuming so much VIRT memory?

### ISSUE THREAD

**Issue by pmatsinopoulos** [docker/for-mac#2919]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C893D868-D6A2-49E7-B9FC-74FDF5935938

[20180518-083024.tar.gz](https://github.com/docker/for-mac/files/2015567/20180518-083024.tar.gz)

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/C893D868-D6A2-49E7-B9FC-74FDF5935938/20180518-083024.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Description of problem

I am running docker on my Mac OS X: 2,5 GHz Intel Core i7, 16 GB 1600 MHz DDR3.

The point is that it seems to be consuming TOO much VIRT memory, if I am reading the htop output correctly.

<img width="1043" alt="4guxk" src="https://user-images.githubusercontent.com/898286/40217643-790b46de-5a76-11e8-86b0-c6b4b74dc6d5.png">

Is this normal? Or is there any problem behind it? My laptop is very slow.

Note that this report is the same even if I have the containers not running.

**Comment by akimd** [comment]
I have the same figures:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/232441/40704937-df44c804-63e9-11e8-9747-fa760f208a98.png">
but I wouldn't trust `htop` here.  Run the `Activity Monitor`, and you'll get more reasonable results.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/232441/40705019-0e48dc26-63ea-11e8-8d18-26cfe35342a1.png">
