### ISSUE TITLE
docker pull registry:latest Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for LOCAL-210235951510G5000118, not registry-1.docker.io

### ISSUE THREAD

**Issue by yangsf123** [docker/for-mac#2920]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yeluojun** [comment]
how to fix this ?
