### ISSUE TITLE
Time drifting

### ISSUE THREAD

**Issue by gundal** [docker/for-mac#2921]
I would like to reopen the following issue
https://github.com/docker/for-mac/issues/17

However I do not have permission to comment on it, as it has been limited to only collaborators.

This issue very much still exists in the latest version of docker for mac.

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false`

Reproduction steps

1. Start docker container
2. Sleep machine
3. Come back 30 mins later
4. docker exec [containerName] date -u
5. date -u on osX host
6. There will be 3-5 seconds of time drift, it will continue to get worse.

I am running a slack sdk bot in my container, and if time drift is greater then 8 seconds my bot cannot post messages to slack. This is VERY apparent, and easily reproducible.

As a workaround for now, I am using 
https://github.com/arunvelsriram/docker-time-sync-agent

which immediately rectifies the issue, on a running container, without restarting anything, just manually executing `update-docker-time` and the containers clock gets back in sync and slack messages are posted again.

**Comment by akimd** [comment]
Hi!

Please give a try to Docker for Mac Edge 18.05 mac66, it has fixes for time drifting issues.

**Comment by gundal** [comment]
Confirmed, it appears to be rectified on the latest edge build!
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

No issues yet, will test overnight as I have been mostly active since updating

**Comment by gundal** [comment]
After 24 hours of my macbook in sleep this problem is very much solved!
