### ISSUE TITLE
Proxy causing 502 in 18.03

### ISSUE THREAD

**Issue by UnGround** [docker/for-mac#2922]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 06E94576-2830-4754-8336-C8F32BD82C69

### Expected behavior

When trying to reach internal addresses behind a corporate (zscaler) proxy, it should work in a docker container.

### Actual behavior

Running commands such as curl against an https endpoint returns 502 from internal proxies, regardless of proxy/no_proxy environment variables in the container.

```
root@4f45c48a8ed7:~/# export no_proxy=*.company.com
root@4f45c48a8ed7:~/# curl -v https://internal.company.com/
*   Trying 10.214.43.100...
* TCP_NODELAY set
* Connected to internal.proxy.corporate.company.com (10.214.43.100) port 80 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to internal.company.com:443
> CONNECT internal.company.com:443 HTTP/1.1
> Host: internal.company.com:443
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 502 Bad Gateway
< connection: close
< content-type: text/html
< server: Zscaler/6.0
< 
* Received HTTP code 502 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 502 from proxy after CONNECT
```

When no_proxy is unset, we get different errors:
```
root@4f45c48a8ed7:~/# unset no_proxy
root@4f45c48a8ed7:~/# curl -v https://internal.company.com/
*   Trying 10.139.244.206...
* TCP_NODELAY set
* Connected to internal.company.com/ (10.139.244.206) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to internal.company.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to internal.company.com:443 
```

This worked normally with Docker 17.09.0-ce-mac35 (19611) and no longer works after upgrading to 10.13.4 (build: 17E202)

### Information

  - macOS Version: High Sierra 10.13.4 (17E202)

Not sure a dockerfile will help unless you also have a company proxy / zscaler. Here is the dockerfile in question. Runs fine until the maven command tries to pull from company hosted artifactory
```
FROM    ubuntu:bionic

ENV     http_proxy=http://internal.proxy.corporate.company.com:80
ENV     https_proxy=http://internal.proxy.corporate.company.com:80
ENV     HTTP_PROXY=http://internal.proxy.corporate.company.com:80
ENV     HTTPS_PROXY=http://internal.proxy.corporate.company.com:80

RUN     apt-get upgrade
RUN     apt-get update
RUN     apt-get -y install vim
RUN     apt-get -y install git
RUN     apt-get -y install maven
RUN 	apt-get install -y default-jre
RUN 	apt-get install -y default-jdk
RUN 	apt-get install -y unzip

####################################
# Company Cert install
####################################
COPY 		setup/CA_Certs_PEM.zip /root
WORKDIR		/root
RUN 		unzip CA_Certs_PEM.zip
RUN 		mv CA_Certs_PEM/*.crt /usr/local/share/ca-certificates
RUN 		rm CA_Certs_PEM.zip
RUN 		/usr/sbin/update-ca-certificates

####################################
# Maven setup & Project Build
####################################
RUN 		mkdir .m2
COPY 		setup/settings.xml /root/.m2/settings.xml
RUN 		mkdir app
COPY 		app/* app/
WORKDIR 	app
####################################
# ERROR on this line - maven settings contain repo's hosted at internal company
####################################
RUN 		mvn compile -Djava.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit dependency:resolve
```

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/06E94576-2830-4754-8336-C8F32BD82C69/20180518-171838.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior

  1. Be behind internal proxy using Docker for Mac
  2. Try to connect via SSL to internal service

**Comment by YRM64** [comment]
The 502 error code means 'you've' done nothing wrong.  There is also nothing wrong with your computer.  There is nothing you could've done to avoid 502. The 502 error signals that a remote problem exists.  It is the folks controlling the erring server that has the problem.  Code 502 signifies a "bad gateway", or "bad proxy."

What code 502 actually means is that "something went wrong between the gateway server and another server upstream -- which could be either the destination server or another gateway server."  502 is the status code that makes its way back to you when the aforementioned occurs.

Developers, users, administrators, and engineers will continue to face this issue until the folks controlling the server realizes that they have a problem, and commences to fix it.  

However, you aren't completely powerless to do something about it.  You may be able to take measures into your hands by by-passing, and even finding your own solution.

Troubleshooting Techniques:

When you encounter 502, hold down the "Ctrl" key on your keyboard and press "F5".  This clears the
cache, and downloads a fresh new copy.

Another option Is to load your site in a different browser to make sure your browser itself isn't problematic.

If the steps above prove fruitless, try rebooting your router, your modem, and finally computer.

Rebooting your devices can sometimes clear up errors that can ultimately lead to a 502.  And, guess what, if you feel technically-advanced, you can temporarily switch to a different DNS server.  You can get a free server, this will automatically bypass the 502.  A last ditch effort always work when you contact the server and let them know they have a problem.

**Comment by UnGround** [comment]
Thanks @YRM64 I would totally agree, except that this same dockerfile works reliably in version 17.09 but not on the latest version. We only discovered that fact while troubleshooting various possible causes and found that some team members could build the container without issue. They were on an older version that hadn't been updated in a little while, which is what made me think docker is doing something in this case.

**Comment by YRM64** [comment]
Unground, 

Thanks for the update.  Return to this post and I will provide you another response to your contribution. This is what I enjoy most, we have a real debate, discussion, and learning session for all of us.  That's why it's important to engage and make a contribution; like I said, as developers, you need one another.  Don't ever feel like you have to agree with me, if you do, you do, and if you don't you don't, but I approach everything from a factual perspective, providing information I read from the blog posts, success.docker.com, Github, stackflow, and Docker.com.  I try to mention the dates of the articles I read or make some reference as to how dated the material might be.  The catch 22 is that the facts can change quickly just in a new release, and I'm cognizant of that fact.

Again, thanks so much.  See you back at the post.

**Comment by YRM64** [comment]
Unground,

I'm back here again, all within minutes of our previous dialogue on proxy causing 502 in 18.03.  Wanted to let you know that I stand by my previous statements made.  If through testing, the Dockerfile is working, that could also IMPLY no server issues (gateway or upstream).  You have to troubleshoot each individual use case.  It's hard to know for sure if you don't provide testing results.  My source indicates this type of problem occurs 100% due to a server issue, and has nothing to do with a Dockerfile, or otherwise.

My position is clear, unwavering, and my statements were made entirely by a credible source.  
Thank you so much, as always, I appreciate your contribution.
