### ISSUE TITLE
docker mac HIGH cpu 

### ISSUE THREAD

**Issue by tzookb** [docker/for-mac#2926]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 434F29E0-4950-4E77-AF68-BC025586A32E/20180521-141829

### Expected behavior
not having huge 200%+ cpu when docker does nothing

### Actual behavior
high cpu of over 200%

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? cant see how
  - Is the problem new? just started paying attention as I need to restart my docker each time
  - Did the problem appear with an update? no
  - macOS Version: 10.13.4 (17E202)

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/434F29E0-4950-4E77-AF68-BC025586A32E/20180521-142416.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk


```

**Comment by akimd** [comment]
Which binary is eating your CPU?

**Comment by tzookb** [comment]
Mmm how can I get that :/

**Comment by djs55** [comment]
I notice from the diagnostics that there are 11 containers running. Perhaps use `docker ps` and `docker stop` to shut them down and see what happens? (Or if they were created with `docker-compose`, it might be easier to use `docker-compose down`)

You can also see the processes running inside the VM with a command like
```
docker run -it --privileged --pid=host justincormack/nsenter1 /usr/bin/top
```

**Comment by tzookb** [comment]
thanks @djs55 

I use all those containers :/

but most of time all is good
just from time to time it spikes to 200%

I look at "docker stats"
and all cpus and memories for containers look good :/

**Comment by atombender** [comment]
Duplicate of #1759, which has been open since June 2017.

**Comment by davidkrcil** [comment]
@atombender I am not as expert but this finally stopped my Mac from heating. I had go to security and there allow cputhrottle to run. Is this wrong way by your opinion?

**Comment by atombender** [comment]
I don't know, all I know is that the tool was [removed from Homebrew](https://github.com/Homebrew/homebrew-core/pull/36127) because it really doesn't work anymore. As far as I can see, it's the same tool.

**Comment by davidkrcil** [comment]
@atombender  I am just afraid from security reason. On the other hand .. this definitely work for me. Need to add that the performance is lover than before. But for local developmnet it is almost perfect.

**Comment by JamesonNetworks** [comment]
Possibly related to:
https://github.com/docker/for-mac/issues/1759
https://github.com/docker/for-mac/issues/2582
https://github.com/docker/for-mac/issues/2926
https://github.com/docker/for-mac/issues/3499
