### ISSUE TITLE
Accessing private registry with Docker for Mac client is unstable

### ISSUE THREAD

**Issue by ctcampbell** [docker/for-mac#2929]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E7CA3D4-B29D-43EA-80CE-E9300852731D

### Expected behavior

Push/pull from a private registry should work all of the time

### Actual behavior

Push/pull seems to work for a short period of time before getting 'service unavailable' when trying to use the repository. HTTPS service is still available on registry, restart of Docker for Mac on client allows registry access again.

### Information

  - macOS Version: 10.13.4

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/7E7CA3D4-B29D-43EA-80CE-E9300852731D/20180522-091421.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```
Note on the above - I am not currently using Kubernetes hence the error.

I also get this error in the MacOS console logs:

```
default	10:12:24.899690 +0100	com.docker.vpnkit	HTTP proxy: returning 503 Service_unavailable
```

### Steps to reproduce the behavior

```
1. $ docker pull registry.int/verademo-simple/develop
Error response from daemon: Get https://registry.int/v2/: Service Unavailable

2. Restart Docker for Mac

3. $ docker pull registry.int/verademo-simple/develop
latest: Pulling from verademo-simple/develop
Digest: sha256:4687715081ddf15f2ec478dcab5d8c9ddf797452081608685514a6cd50f60a39
Status: Image is up to date for registry.int/verademo-simple/develop:latest
```

**Comment by scream314** [comment]
>  Error response from daemon: Get https://registry.int/v2/: Service Unavailable

The same happened as I misconfigured my DNS and it could not return the right address for `registry.int`.
Could you please post the results of `nc -zv registry.int 443` and `curl https://registry.int/v2/` (executed at the same time `docker pull` returns with `503`)?

**Comment by bharathy** [comment]
Im also getting same error. 
**Mac OS version:** 10.13.4
**Docker version:**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

**response when I pull is**
`Using default tag: latest
Error response from daemon: Get https://registry.int/v2/: Service Unavailable`

**utility console log:**
`default	20:49:58.186565 +0100	com.docker.driver.amd64-linux	proxy >> GET /_ping
default	20:49:58.186633 +0100	com.docker.driver.amd64-linux	Dial Socket vms/0/00000003.00000948
default	20:49:58.187956 +0100	com.docker.driver.amd64-linux	proxy << GET /_ping
default	20:49:58.266835 +0100	com.docker.driver.amd64-linux	proxy >> POST /v1.37/images/create?fromImage=registry.int%2Fverademo-simple%2Fdevelop&tag=latest
default	20:49:58.266916 +0100	com.docker.driver.amd64-linux	Dial Socket vms/0/00000003.00000948
default	20:49:58.270056 +0100	com.docker.vpnkit	DNS lookup registry.int A: NoSuchRecord
default	20:49:58.271434 +0100	com.docker.vpnkit	DNS lookup registry.int.ten.thomsonreuters.com A: NoSuchRecord
default	20:49:58.272549 +0100	com.docker.vpnkit	DNS lookup registry.int A: NoSuchRecord
default	20:49:58.273670 +0100	com.docker.vpnkit	DNS lookup registry.int.ten.thomsonreuters.com A: NoSuchRecord
default	20:49:58.274772 +0100	com.docker.vpnkit	DNS lookup registry.int A: NoSuchRecord
default	20:49:58.275726 +0100	com.docker.vpnkit	DNS lookup registry.int.ten.thomsonreuters.com A: NoSuchRecord
default	20:49:58.276240 +0100	com.docker.vpnkit	DNS: docker.for.mac.http.internal is a builtin but there are no resource records for IPv6
default	20:49:58.276329 +0100	com.docker.vpnkit	DNS: docker.for.mac.http.internal is a builtin: docker.for.mac.http.internal <IN|0> [A (192.168.65.1)]
default	20:49:58.277238 +0100	com.docker.vpnkit	DNS lookup registry.int A: NoSuchRecord
default	20:49:58.277271 +0100	com.docker.vpnkit	HTTP proxy: returning 503 Service_unavailable
default	20:49:58.278033 +0100	com.docker.driver.amd64-linux	proxy << POST /v1.37/images/create?fromImage=registry.int%2Fverademo-simple%2Fdevelop&tag=latest
`

**Comment by bharathy** [comment]
See here...
`$ nc -zv registry.int 443 and curl https://registry.int/v2/`
nc: getaddrinfo: nodename nor servname provided, or not known

**Comment by bharathy** [comment]
All I'm trying is to pull docker image while I'm in VPN. I thought (verademo-simple/develop) is demo one, which I can pull and test...

**Comment by scream314** [comment]
@bharathy 
If there is no such host on your network, it won't work.
I have no idea what `verademo-simple/develop` is. Could you maybe provide a link where you got this from?

**Comment by bharathy** [comment]
Then, lets ignore that part. Today I tried from office network, I could able to login into docker and pull my docker image. So it is to do with vpn network at home. I will debug at home and get back to you. I guess its to do with network or dns issue...
