### ISSUE TITLE
--memory and --memory-swap limits not honored by Docker for Mac

### ISSUE THREAD

**Issue by geerlingguy** [docker/for-mac#2931]
- [x] I have tried with the latest version of my channel (Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior

Passing values like `--memory 256M` and `--memory-swap 256M` to the `docker run` command should result in Docker limiting the amount of memory and swap available inside the container (and setting both to the same value should result in swap being off inside the container).

### Actual behavior

After running the `docker run` command in the 'steps to reproduce' below to start a container, `free -h` displays the values for the global Docker engine/hypervisor on the Mac, as configured in the Docker for Mac global preferences:

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           3947         247        1522           1        2178        3430
Swap:          1023           0        1023
```

(Confirmed also by running `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` to drop into the hypervisor, then running `free -m` there.)

### Information

  - Is it reproducible? Yes.
  - Is the problem new? No.
  - Did the problem appear with an update? No.
  - macOS Version: 10.13.4

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/7712B988-055B-471B-8F5E-FC5805D7BCA4/20180522-195942.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Start a container using Docker for Mac with the command:

          docker run --memory 256M --memory-swap 256M -it ubuntu /bin/bash

  1. In the container, run `free -h` to check the total available memory and swap space.
  1. You should see total mem value of ~256M, and swap of ~256M.

**Comment by geerlingguy** [comment]
So... `docker stats` does show the limit:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
0d233342b7c4        unruffled_beaver    0.00%               732KiB / 256MiB       0.28%               928B / 0B           0B / 0B             1
```

I guess I've never really tried inspecting memory limits from _inside_ the container until now... but this came up twice in the past month as I'm trying to do two things:

  1. Test some Kubernetes configurations inside a Docker container; K8s really likes swap off, but because the system always shows 1 GB of swap, I have to mess with the K8s configs to get it to start kubelet.
  1. Test some swap file configuration management inside a Docker container; it's hard to see if anything's working if there's no easy way to check the actual swap and memory available inside a particular container (`free` and `cat /proc/meminfo` both seem to show the globally-available stats...).

Is there any way I could get things inside the container to reflect the limits being imposed by Docker for Mac (e.g. 256M memory limit and 0 swap)?

**Comment by geerlingguy** [comment]
Related:

  - https://github.com/moby/moby/issues/20688
  - https://stackoverflow.com/a/42187357/100134

**Comment by geerlingguy** [comment]
Feel free to close this out as it seems like it's not something easily (or maybe even _at all_) solvable by Docker itself, but rather a limitation of the way containers work at the core in terms of memory usage reporting with Linux.

**Comment by thaJeztah** [comment]
I saw this issue's title and thought I'd add a link to that ticket + blog, but good to see you found it.

Having said that, I think it would be good to have some of that information added to the ["Limit a container's resources" section in the documentation](https://docs.docker.com/config/containers/resource_constraints/)

- explain that even though memory accounting ("limiting") is enabled for a container, processes inside the container may still see the total amount of memory available on the machine (which is different than when running a VM)
- perhaps we should mention the problems that people can run into when running Java inside the container (at least older versions); https://github.com/moby/moby/issues/15020 (also see ["Make JVM respect CPU and RAM limits"](https://hub.docker.com/_/openjdk/) in the official OpenJDK image on Docker Hub)


@geerlingguy would you be interested in opening a ticket for that in the documentation repository (https://github.com/docker/docker.github.io/issues) - perhaps you're interested in contributing and helping out writing a section? 😇

**Comment by geerlingguy** [comment]
@thaJeztah - Definitely! Haven't had time but will see what I can do now.

**Comment by geerlingguy** [comment]
Opened https://github.com/docker/for-mac/issues/2931, and am closing this issue.

**Comment by toby5box** [comment]
(this _is_ #2931?!)

I guess I don't understand why this issue is not still relevant. I'm using Docker for Mac 18.06.1-ce and I see the same problem. With `-m 0.5g`, `free -h` reports as follows:

```
              total        used        free      shared  buff/cache   available
Mem:           2.0G        776M        137M        560K        1.1G        1.0G
Swap:          1.0G         52M        971M
```

So the swap and available RAM do not respect the limit, and worst of all, the container has been able to expand to 776m resident despite the 0.5g limit given to `docker run`. Can someone explain? (or provide the new issue reference)

**Comment by jamshid** [comment]
I think @geerlingguy meant that he opened a docs bug (now closed):
https://github.com/docker/docker.github.io/issues/6833

Is there really no way to enable cgroup for memory and swap accounting on Docker for Mac? 
This https://serverfault.com/questions/762206/cgroups-memory-limit-not-working describes how to enable it on a Linux docker server, using grub configuration. What is the Docker for Mac equivalent to `/etc/default/grub`? 

I'm just trying to make `/sys/fs/cgroup/memory/memory.usage_in_bytes` working in Docker for Mac containers, it doesn't seem reliable.

**Comment by thaJeztah** [comment]
@jamshid it's enabled on Docker for Mac;

```bash
docker run --rm --memory=100MB busybox sh -c 'cat /sys/fs/cgroup/memory/memory.limit_in_bytes' 
104857600
```

**Comment by jamshid** [comment]
Thanks I'm glad it is supported after all.
Btw I thought `memory.usage_in_bytes` was unreliable because I didn't realize it includes buffer/cache. I switched to monitoring `total_rss` in `sys/fs/cgroup/memory/memory.stat` for memory usage in a container.

**Comment by pai911** [comment]
I don't think this issue is completely resolved ...

The previous discussion was only about the memory limit on containers & how `free` will show the overall info on the OS.

But the problem is that when you set `--memory` and `--memory-swap` to the same value, the container still allows the process to use swap memory which doesn't behave as the [official doc](https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details).

I can see that my params are set correctly

```
$ sudo docker inspect 30309d07aa95 | grep Mem
    "Memory": 1073741824,
    "CpusetMems": "",
    "KernelMemory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 1073741824,
    "MemorySwappiness": null,
```

But when the container is up & running, my Java process still used a lot of swap memory

Within the container, run `cat /sys/fs/cgroup/memory/memory.stat`, i can see the following
```
cache 47161344
rss 404557824
rss_huge 0
shmem 0
mapped_file 38793216
dirty 122880
writeback 0
swap 366784512
...
total_swap 366784512
```

and on the host, I can see
```
$ grep --color VmSwap /proc/9683/status
VmSwap:   377172 kB
```
Could anyone shed some light on this problem?

Thank you!
