### ISSUE TITLE
errore . docker-cli

### ISSUE THREAD

**Issue by aparrac** [docker/for-mac#2937]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Sorry, we can't investigate this issue without any diagnostics.
