### ISSUE TITLE
docker diagnostic 

### ISSUE THREAD

**Issue by rezadj** [docker/for-mac#2946]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rezadj** [comment]
docker diagnostic error log

**Comment by mat007** [comment]
Sorry, we can't investigate this issue without any diagnostics.
