### ISSUE TITLE
Docker isn't working shows an connection error

### ISSUE THREAD

**Issue by abdullahrashid12** [docker/for-mac#2949]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Sorry, we can't investigate this issue without any diagnostics.
