### ISSUE TITLE
-bash: docker: command not found

### ISSUE THREAD

**Issue by cfengdev** [docker/for-mac#2950]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:E99A7230-2DD3-4357-98B0-E35CCD7C722D

### Expected behavior

docker version

....show info

### Actual behavior

docker version
-bash: docker: command not found

### Information

  - macOS Version:10.13.4 (17E202)

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/E99A7230-2DD3-4357-98B0-E35CCD7C722D/20180528-223929.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by akimd** [comment]
Please type:
```
echo "$PATH"
```
I suppose you don't have `/usr/local/bin` in it, so:
```
PATH=/usr/local/bin:$PATH
hash -r
docker run --rm hello-world
```

**Comment by cfengdev** [comment]
According to your method, the problem has been solved. Thank you very much.

**Comment by NajwaSM** [comment]
> echo "$PATH" i type echo "$PATH" and hit enter, and it shows me:
/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

then, i try to run docker run command again, still it does not work

**Comment by Manisha91p** [comment]
I am facing the same issue even though the path is added of /usr/local/bin 
Please someone suggest how to fix this issue as I am stuck in this issue form a long back

**Comment by Ekraam** [comment]
@Manisha91p this worked for me:
`brew link docker`
I had used brew to install docker and it was not linked to `/usr/local/Cellar/docker`
