### ISSUE TITLE
com.docker.supervisor uses > 100% CPU

### ISSUE THREAD

**Issue by tjamet** [docker/for-mac#2951]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E1244000-661A-4A9B-BA56-304C2347C01E/20180529-091232

### Expected behavior
The mac is silent, little CPU used

### Actual behavior
com.docker.supervisor uses > 100% CPU
<img width="796" alt="capture d ecran 2018-05-29 a 09 11 19" src="https://user-images.githubusercontent.com/6061440/40643801-77b62ec6-6321-11e8-9a61-29ad80e553ec.png">
Fans are running to cool down the mac

### Information

  - macOS Version: 10.13.4 (17E202)
  - It seems that killing docker and restarting it leads to the same problem
  - I have another similar mac for work that does not suffer the problem though

### Diagnostic logs

```
Docker for Mac: version: 18.05.0-ce-mac66 (07d57837a9c0ad813a1042c9dc39bbc5961d031d)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/E1244000-661A-4A9B-BA56-304C2347C01E/20180529-091232.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior
I don't have a clear idea on how to reproduce the behaviour.
All I can tell is that I have 64 images and 7 non-running containers
Kubernetes has been launched but is currently stopped
I have tried to kill docker and restart it, but have the same behaviour, even after few hours of having docker running

**Comment by akimd** [comment]
This is a known (and fixed) issue. Will be part of the next release.

Thanks for the report!

**Comment by mfriedman-upchain** [comment]
I currently have the latest release, and I have this problem also. In which release is this fixed specifically? And when will it be released? Thank you.

**Comment by rkingon** [comment]
i am experiencing this on `18.06.1-ce-mac73`

**Comment by snoblenet** [comment]
I am experiencing this on `Version 2.0.0.2 (30215)`
