### ISSUE TITLE
Fatal Error: com.docker.supervisor failed to start (Exit code 1)

### ISSUE THREAD

**Issue by brazenest** [docker/for-mac#2954]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 02282008-081E-4433-A120-0DF66E500069/20180529-093047

### Expected behavior

Upon running Docker for Mac, it should startup without error.

### Actual behavior

The program produces "Fatal Error: com.docker.supervisor failed to start (Exit code 1)"

### Information

  - macOS Version: 10.13.3

The problem currently is reproducible; it occurs whenever I startup Docker for Mac, even though I login/logout of my macOS acct and have done "Reset Docker to factory defaults"

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Launch Docker for Mac via Launchpad

**Comment by akimd** [comment]
I would think that it means that another user is already running Docker on this machine.  Unfortunately it does not work.
