### ISSUE TITLE
Upgrade causes Docker to not start

### ISSUE THREAD

**Issue by CSBaum** [docker/for-mac#2956]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 56EA5F0B-479F-4EE1-8778-11F75BFE5A99/20180529-165409

### Expected behavior
Post-upgrade, Docker should start as normal

### Actual behavior
Docker fails to start with the following error: "Failed to start local NTP server: lookup localhost: no such host"

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - macOS Version: 18.05.0-ce-mac66

### Diagnostic logs

```
Docker for Mac: version: 18.05.0-ce-mac66 (07d57837a9c0ad813a1042c9dc39bbc5961d031d)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/56EA5F0B-479F-4EE1-8778-11F75BFE5A99/20180529-165409.tar.gz
failure: No Docker.qcow2 or Docker.raw found: the VM has never been started
[ERROR]  vpnkit
         com.docker.vpnkit is not running
         Unexpected error connecting to /Users/SeanS/Library/Containers/com.docker.docker/Data/s51: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/SeanS/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/SeanS/Library/Containers/com.docker.docker/Data/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /Users/SeanS/Library/Containers/com.docker.docker/Data/docker.sock
[ERROR]  disk
         No Docker.qcow2 or Docker.raw found: the VM has never been started

```

### Steps to reproduce the behavior

  1. Upgrade to the latest Edge version of Docker
[20180529-165409.tar.gz](https://github.com/docker/for-mac/files/2050907/20180529-165409.tar.gz)

**Comment by mmerchant** [comment]
Same issue with same output log errors.

**Comment by NickJLange** [comment]
I have the same issue with my installation. Amazingly, my osx laptop did not have an entry for localhost in DNS - an entry like the below fixed the issue. 

```
$sudo vi /private/etc/hosts
$ cat /private/etc/hosts
127.0.0.1 localhost

$ sudo dscacheutil -flushcache
$  ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.038 ms

```
It's unclear from the great google machine if localhost should naturally resolv on OSX (or the implications of making it resolve...) -

**Comment by ospaarmann** [comment]
I had the same issue. Turns out my `/etc/hosts` was empty. For whatever reason...
