### ISSUE TITLE
hyperkit using 200% cpu while all containers are stopped

### ISSUE THREAD

**Issue by keturn** [docker/for-mac#2957]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics: [20180529-160916.tar.gz](https://github.com/docker/for-mac/files/2051702/20180529-160916.tar.gz)
  - Diagnostics ID: 006FA32B-FCFB-44FA-A071-8ED1256FDE1E/20180529-160916

### Expected behavior

hyperkit is idle after all docker containers are stopped.

### Actual behavior

com.docker.hyperkit using > 200% CPU and com.docker.osxfs using 25% CPU while `docker ps` shows no running containers.

### Information
  - macOS Version: 10.13.4

This happened after running my software project's build script, but I'm not quite sure why, since most of what that script does doesn't happen in docker.

I guess it does update a great number of files in a subdirectory that one of my services might have had mounted at the time. Or maybe pycharm helpers was running something that had that mounted.

hyperkit started using all that CPU, meanwhile `docker stats` was not showing more than 1% in any of the containers. So I stopped all the containers and the CPU usage still continued for minutes following.

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/006FA32B-FCFB-44FA-A071-8ED1256FDE1E/20180529-160916.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

**Comment by akimd** [comment]
What do you get with

```
docker run  --rm --privileged --pid=host justincormack/nsenter1 /usr/bin/top -b -n1
```

?

**Comment by tsuna** [comment]
/remove-lifecycle stale

I'm seeing this now too.  D4M version "2.0.0.0-mac77 (28700)" with k8s enabled but not actively doing anything in any of the containers.  Nothing using CPU on the HyperKit VM other than `transfused` and `kworker` as well.

What seems to have triggered this is running `dep status` in a project that is mounted in one of the containers, i.e. I started a container that has a volume that is mounting a Go source tree with osxfs in `:delegated` mode, and running `dep status` accessed (read-only) a lot of files (but from the Mac host!) and that somehow made osxfs freak out for a while.  Those source files are never modified from within the container.  So it's weird to me that read-only accesses from the macOS host to unchanged files would cause this, but that's the only explanation I've found so far.

**Comment by tsuna** [comment]
I can reproduce this easily BTW, even with a warm cache and not changing anything, just running `dep status` again causes the HyperKit VM to lock up briefly.  For example if I hit `<enter>` repeatedly in a shell, it stops printing a new prompt while `dep status` is running.  Again, this is running `dep status` _outside_ of any container, on the macOS host.  I'm not sure why read accesses to unmodified files are hurting so much, but boy that hurts.

**Comment by tsuna** [comment]
lol, I ran another `dep` command and saw hyperkit melt my CPU and looked in the VM and saw `transfused` at it again and Googled it, here I am again... so this is still an issue with D4M edge 2.1.3.0 (38275)
