### ISSUE TITLE
When mounting volume get error: “docker run” requires at least 1 argument

### ISSUE THREAD

**Issue by lewleib** [docker/for-mac#2959]
After successfully running Dockers tensorflow/tensorflow for a couple of months, I tried to create a jupyter/tensorflow_notebook in order to run Python 3. 

I successfully ran:
`docker run -it -p 8888:8888 -p 6006:6006 jupyter/tensorflow-notebook`
However, I need it to connect to my host machine, so I tried;
`LewIss-MacBook-Pro:Gorner_tensorflow-rnn lewleib$ docker run -it -p 8888:8888 -p 6006:6006 -v /User/lewleib/MyTensorFlow/Gorner_tensorflow-rnn:/jupyter/tensorflow-notebook`

and I got the message:
`“docker run” requires at least 1 argument.
See ‘docker run --help’.

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG…] [flags]

Run a command in a new container`

I then retried tensorflow/tensorflow:
`LewIss-MacBook-Pro:Gorner_tensorflow-rnn lewleib$ docker run -it -p 8888:8888 -p 6006:6006 -v /Users/lewleib/MyTensorFlow/Gorner_tensorflow-rnn:/notebooks tensorflow/tensorflow
`
It ran and connected to my host files.
I am running macOS Sierra 10.13.3 and Docker Client: Version: 18.03.1-ce
Any suggestions for the problem?
Thanks
Lew

**Comment by mat007** [comment]
```
$ docker run --help

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```
You're missing the `IMAGE`, try
```
$ docker run -it -p 8888:8888 -p 6006:6006 -v /User/lewleib/MyTensorFlow/Gorner_tensorflow-rnn:/jupyter/tensorflow-notebook tensorflow/tensorflow
```

**Comment by shrishail143** [comment]
shrishail@shrishail:~/shri$ docker run -d -p 90:80 --name mywebserver:v1

"docker run" requires at least 1 argument
See 'docker run --help

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARGUMEN


i am new in docker and getting above error could you plz suggestion thank you
