### ISSUE TITLE
[ERROR]  docker-cli docker ps failed

### ISSUE THREAD

**Issue by tranduchieu** [docker/for-mac#296]
### Information

Diagnostic ID: 6F0DF4EA-196C-4CDF-8922-9E0BF2C095C1
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by Gnito** [comment]
I have the same issue: 
### Information

Diagnostic ID: 738DF13F-CD2A-4E16-BCB5-9F3A102B68CF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'qcow2-corruption' in 6F0DF4EA-196C-4CDF-8922-9E0BF2C095C1/20160816-154421.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.osxfs][7941] <Notice>: Negotiated transfuse notification channel for /private
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.osxfs][7941] <Notice>: Negotiated transfuse notification channel for /host_docker_app
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.osxfs][7941] <Notice>: sending continue to client
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.slirp][7942] <Notice>: Using protocol TwoThousand msize 8192
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.driver.amd64-linux][7944] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-69632")
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.driver.amd64-linux][7944] <Notice>: VM: 2016-08-15 17:37:42 +0000 UTC daemon.info chronyd: chronyd version 2.3 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER -SECHASH +ASYNCDNS +IPV6 -DEBUG)
Aug 16 00:37:42 unixs-Mac-Pro Docker[com.docker.driver.amd64-linux][7944] <Warning>: VM: 2016-08-15 17:37:42 +0000 UTC daemon.warn chronyd: Could not open keyfile /etc/chrony/chrony.keys
Aug 16 00:37:43 unixs-Mac-Pro Docker[com.docker.driver.amd64-linux][7944] <Notice>: VM: 2016-08-15 17:37:43 +0000 UTC daemon.info vsudd: Connection 1 to: 2376 from: 00000000
```
