### ISSUE TITLE
Kubernets error on diagnostic

### ISSUE THREAD

**Issue by cbozzi** [docker/for-mac#2966]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Sorry, we can't investigate this issue without any diagnostics.
