### ISSUE TITLE
com.docker.supervisor uses 133% CPU when there are no containers running .

### ISSUE THREAD

**Issue by bplein** [docker/for-mac#2967]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 988A6800-32E2-4E08-98B3-F8FEA8F8C5E3/20180603-170721

### Expected behavior
Docker should run with minimal CPU when I have zero containers listed in "docker ps -a"
### Actual behavior
com.docker.supervisor uses from 133-149% CPU. Additional kernel task eating up 45-50% CPU. If I quit Docker then com.docker.supervisor stops and the kernel task usage disappears as well, meaning that this process is chewing up close to 2 cores at idle.

### Information
If I restart Docker then this behavior does NOT automatically restart, but I notice it happening every day or so, whether or not I used Docker on that system. I have seen this on both my iMac Pro and my 15" Macbook Pro.

I am not sure when I first saw it, but it was more than one update ago (I've seen it for several weeks). 
  - macOS Version: 10.13.4

### Diagnostic logs

```
Docker for Mac: version: 18.05.0-ce-mac66 (07d57837a9c0ad813a1042c9dc39bbc5961d031d)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/988A6800-32E2-4E08-98B3-F8FEA8F8C5E3/20180603-170721.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior
It reproduces over time, not after something I know how to do and trigger it.

**Comment by seank-com** [comment]
Same issue here.

```
Docker for Mac: version: 18.05.0-ce-mac66 (07d57837a9c0ad813a1042c9dc39bbc5961d031d)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/8776901D-39BC-463B-B066-D01BF5CC326C/20180605-090626.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

**Comment by flurdy** [comment]
Have you looked at https://github.com/docker/for-mac/issues/2923 ? It seems a later than edge build fixes it.

**Comment by akimd** [comment]
Indeed.  And we are about to make an Edge release which includes the fix.
