### ISSUE TITLE
Docker for mac stuck on starting

### ISSUE THREAD

**Issue by almoore** [docker/for-mac#2974]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1B9B1BAA-BEB8-48D6-8368-D8D03DD708FB/20180605-181540

### Expected behavior

Docker starts with daemon in background

### Actual behavior

Docker begins and the message "Docker is starting" never goes away

### Information

  - macOS Version:
High Sierra 10.13.5
MacBook Pro

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/1B9B1BAA-BEB8-48D6-8368-D8D03DD708FB/20180605-181540.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

**Comment by shershen08** [comment]
I had similar case, after full system restart I got all diagnostic checks green [OK]

**Comment by almoore** [comment]
I have restarted my machine and cleaned docker several times. It does not really help. I think it has something to do with the latest update on macOS and vpnkit or hyperkit. I do also see repeating logs like this. 

`
default	08:40:03.604132 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:03.604171 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:03.914178 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:03.956623 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:03.956719 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:04.364803 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:04.388416 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:05.430689 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:05.453367 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:05.453436 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:05.831492 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:06.307754 -0600	com.docker.vpnkit	Vmnet.Server.listen callback caught (Invalid_argument "option len is too big: 304")
default	08:40:08.509270 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:08.509366 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:08.509427 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:08.578420 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:08.578506 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:11.486236 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.455648 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.455781 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.455862 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.458087 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.637780 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.637858 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:12.639943 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:13.418340 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:13.455107 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:13.455166 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:13.657851 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:13.657926 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:14.126951 -0600	com.docker.driver.amd64-linux	com.docker.hyperkit: [INFO] Allocator: 34049 used; 0 junk; 0 erased; 255 available; 0 copies; 0 roots; 0 Copying; 0 Copied; 0 Flushed; 0 Referenced; max_cluster = 34051
default	08:40:14.127108 -0600	com.docker.driver.amd64-linux	com.docker.hyperkit: [INFO] Allocator: file contains cluster 0 .. 34306 will enlarge file to 0 .. 34818
default	08:40:14.127167 -0600	com.docker.driver.amd64-linux	com.docker.hyperkit: [INFO] resize: adding available clusters (Node ((x 34307) (y 34818) (l Empty) (r Empty) (h 1) (cardinal 512)))
default	08:40:20.338637 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:20.484869 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:20.484939 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:20.485890 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
default	08:40:20.534647 -0600	com.docker.vpnkit	Failed to forward unexpected ICMP datagram with type 5
`

**Comment by shershen08** [comment]
I didn't say it fixed all the problem to me ;(
just the fact that `[ERROR]  kubernetes` was gone and converted to `[OK]  kubernetes`

I also still have the hanging kubernetes startup
<img width="218" alt="screen shot 2018-06-06 at 17 03 09" src="https://user-images.githubusercontent.com/1363772/41046829-6b6aaefe-69ab-11e8-821b-e48554951b26.png">
