### ISSUE TITLE
docker won't start

### ISSUE THREAD

**Issue by malexzx** [docker/for-mac#2975]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 44CA60AB-2135-4CB5-A40F-0CDEBFF0E134

### Expected behavior
   - Docker running
### Actual behavior
   - Docker not running
### Information

  - macOS Version: 10.13.5

### Steps to reproduce the behavior

After MacOS upgraded to 10.13.5 version - docker won't start.

**Comment by darkgem666** [comment]
Same issue here, in activity monitor is just says not responding after the upgrade

**Comment by cortesben** [comment]
Was anyone able to solve this?

OSX 10.13.5

```STATE = sleeping *0[28]``` from running TOP

**Comment by cortesben** [comment]
I found a temp fix for this and it's now working for me. In your home directory `cd ~ && ls -al` you will see a .docker directory.

edit the file named daemon.json
```
{
  "debug" : true,
  "experimental" : false
}
```
I changed the experimental flag from true to false and it's working for me now.
