### ISSUE TITLE
Docker daemon does not start

### ISSUE THREAD

**Issue by eczex** [docker/for-mac#2977]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A007F17C-F2DB-48ED-A623-391C54C85CB4

### Expected behavior
Docker daemon is running
### Actual behavior
Docker daemon is starting continuosly
### Information

  - macOS Version: 10.13.4 (17E202)

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/A007F17C-F2DB-48ED-A623-391C54C85CB4/20180607-101411.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk


```

### Steps to reproduce the behavior

  1. Run Docker.app
  2. Wait...

**Comment by maxvipon** [comment]
Have the same on Mac OS version 10.12.6 (16G1408)

**Comment by eczex** [comment]
Sometimes it starts after reboot. But this is infrequent and unpredictable.
