### ISSUE TITLE
Cannot install on MacOS 10.14 Mojave 

### ISSUE THREAD

**Issue by gondalez** [docker/for-mac#2978]
### Expected behavior
* Running MacOS 10.14 Mojave (Dev  Beta 1)
* download https://download.docker.com/mac/edge/Docker.dmg
* drag to applications
* double click
* see 'Docker needs priveleged access' dialog
* click ok 
* password prompt, install succeeds

### Actual behavior
* no password prompt
* dialog stays open
* believe me, subsequent presses on ok do nothing either :)

### Information

  - macOS Version: MacOS 10.14 Mojave (Dev  Beta 1)

**Comment by joeabbey** [comment]
Was this on a Mac with a TouchBar?

**Comment by joeabbey** [comment]
I've tried on a 12" Macbook and a 13" Macbook with TouchBar.  Both with Mojave Dev Beta 1 installed.  I am unable to reproduce this behavior using https://store.docker.com/editions/community/docker-ce-desktop-mac.

Ah, but you are using the edge Docker.dmg

**Comment by gondalez** [comment]
Hi @joeabbey, yes it was a TouchBar Mac. 

Would you believe sleeping the system, sleeping the human and trying again solved it? It works this morning :)
The human also mentioned they did not reboot but had disabled dark mode and recents in the dock in the interim.

So I'll close this and put it down to the beta OS 🤷‍♂️

**Comment by tomsvogel** [comment]
for those who still face this problem ...
on first start use this command
`sudo /Applications/Docker.app/Contents/MacOS/Docker `
if Docker is running, stop it and after that you you should be able to start it normally

**Comment by ethantang93** [comment]
Hi @tomsvogel Thanks for the suggestion. This actually works for me.

**Comment by MihaelIsaev** [comment]
- see 'Docker needs priveleged access' dialog
- click ok
- password prompt, install succeeds **(this never happens)**

Mojave 18A384a

**Comment by imarco** [comment]
@tomsvogel Your solution actually works, thanks so much!

**Comment by kumarchatla** [comment]
Not worked for me. Cannot connect to the docker daemon at tcp://x.y.z.xy:1234. :(

**Comment by nateleavitt** [comment]
I also cannot connect to the docker daemon. 

macOS 10.14 (18A391)
Docker version 18.06.1-ce, build e68fc7a

Also tried @tomsvogel suggestion which didn't work.

`docker ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?`

**Comment by hedvigreut** [comment]
Also have the same problem. Using Mojave 10.14.6 and tried older version of v2.1.0.1 from https://docs.docker.com/docker-for-mac/release-notes/ but no change. The above methods doesn't work.
