### ISSUE TITLE
High CPU usage of com.docker.supervisor

### ISSUE THREAD

**Issue by dlouwers** [docker/for-mac#2980]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3E484435-2C29-400B-A6B0-FBE1FC2CD380/20180607-121710

### Expected behavior
CPU usage expected to be low when not running any containers

### Actual behavior
CPU usage very high (120%-ish) when not running any containers.

### Information

  - macOS Version: 10.13.4 high sierra
This happens after a day or so of using the laptop. I restart the docker process to 'reset'. Then it will happen again within 24 hours or so. Didn't have this problem before high sierra at least.

### Diagnostic logs
Uploaded

```
Docker for Mac: version: 18.05.0-ce-mac66 (07d57837a9c0ad813a1042c9dc39bbc5961d031d)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/3E484435-2C29-400B-A6B0-FBE1FC2CD380/20180607-132738.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

### Steps to reproduce the behavior
Just have to wait for the laptop to be up a while.

**Comment by djs55** [comment]
Thanks for your report. This is the same as #2967 and should be fixed in the [18.05.0-ce-mac67](https://download.docker.com/mac/edge/25042/Docker.dmg) build just released on the edge channel today. Please update and let me know what happens!
