### ISSUE TITLE
High CPU usage of com.docker.supervisor

### ISSUE THREAD

**Issue by gargola** [docker/for-mac#2982]
Just copy-pasted the descriptions from #2980 since it's the exact same problem, which apparently wasn't fixed in the latest release...

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `C4912CED-BC43-42B5-A405-90F80D28DBFA/20180608-091517`

### Expected behavior
CPU usage expected to be low when not running any containers.

### Actual behavior
CPU usage very high (103%-ish) when not running any containers.

### Information
  - macOS Version: 10.13.5 High Sierra

### Diagnostic logs
```
Docker for Mac: version: 18.05.0-ce-mac67 (1fa4e2acfc1a52f79623add2390604515d32297e)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/C4912CED-BC43-42B5-A405-90F80D28DBFA/20180608-091517.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior
Just have to wait for the laptop to be up a while.

**Comment by tuminoid** [comment]
Yup, I have this too. It also does something funny with the network, showing constant 5-6MB/s traffic (equal in and out, so must be local traffic).

**Comment by gargola** [comment]
Everything has been stable for the last week and a half. I'll go ahead and close this one, will reopen if needed though.
