### ISSUE TITLE
Problem starting Docker/Kubernetes after upgrade MacOS to 10.13.5

### ISSUE THREAD

**Issue by rcordoni** [docker/for-mac#2985]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 459DBC40-39A7-4D1D-B2B6-8F7DE23F3F15

### Expected behavior
Start or restart Docker will start both Docker for Mac and Kubernetes

### Actual behavior
Docker starts but Kubernetes reports "Kubernetes is starting ..." forever
[20180608-112126.tar.gz](https://github.com/docker/for-mac/files/2085626/20180608-112126.tar.gz)

### Information

  - macOS Version:
10.13.5

### Diagnostic logs

Note that a Console display of Docker logs shows the continuous adding of a error line "com.docker.driver.amd64-linux   Node status error: Unauthorized"```
Docker for Mac: version...
18.05.0-ce-mac67 (25042) (Edge)
```

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
-->

  1. Restart Docker or Reboot my Mac
  2.Docker starts but Kubernetes never starts - reports "Kubernetes is starting .." forever

**Comment by rcordoni** [comment]
I resolved the issue by resetting to factory defaults.  This means I get to re-create all my docker and kubernetes configurations (sigh).  I am not sure if this is a clue, but I noticed that my Mac disk image file was a qcow2 file and after resetting to factory defaults, it is a raw file.

**Comment by norbertmocsnik** [comment]
Same issue here after upgrading to macOS 10.13.5:

- "Kubernetes is starting" forever
- Docker diagnostics reports everything is OK
- In the Console app I can see a "Node status error: Unauthorized" error being logged by com.docker.driver.amd64-linux every second.

Docker 18.05.0-ce-mac67

**Comment by deepybee** [comment]
I had the same issue. I solved it by quitting Docker, then moved the `Docker.qcow2` disk image out of `$HOME/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/`, restarted Docker which spawned a new disk image and within a minute or so Kubernetes was showing as running again.

NB: make sure your existing containers are writing to explicitly defined volumes if you require persistent storage *before* doing this. Upon restart Docker will need to pull down the images again so make sure you've got any important data backed up. For me this was not a concern (thankfully).

**Comment by barshow** [comment]
I know this sounds really dumb, but some folks on my team ran the OSX migration assistant and ended up with an empty `/etc/hosts/` file.  Setting it to the default seemed to fix the issue.
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1    localhost
255.255.255.255    broadcasthost
::1             localhost
```

**Comment by spackle0** [comment]
Not dumb. Worked for me. I migrated between laptops and /etc/hosts was empty on the new one. Added the default content, restarted Docker, and Kubernetes started up in a few seconds.
