### ISSUE TITLE
failure: com.docker.vpnkit is not running [ERROR]  vpnkit

### ISSUE THREAD

**Issue by plutosolutions** [docker/for-mac#2987]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Unfortunately without more information and a set of diagnostic logs we can't investigate the issue :(

If the problem happens again, please create a fresh issue.
