### ISSUE TITLE
com.docker.driver.amd64-linux failed to start

### ISSUE THREAD

**Issue by toriningen** [docker/for-mac#2988]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: n/a, uploading manually [20180611-112423.tar.gz](https://github.com/docker/for-mac/files/2089642/20180611-112423.tar.gz)

### Expected behavior

Docker should have updated flawlessly.

### Actual behavior

Docker does not start due to "com.docker.driver.amd64-linux failed to start".

### Information
  - macOS Version: 10.13.3 (build: 17D102)
  - Is it reproducible? I don't know
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes

Has been using `18.04.0-ce-mac62 (23965) / Channel: edge / e0a85f64c1`
Updated to the latest `18.05.0-ce-mac67 (25042) / Channel: edge / 0c7f1aa2fa` via built-in updating mechanism.

After update, Docker couldn't start due to "com.docker.driver.amd64-linux failed to start". Offered to do factory reset, which didn't help, issue has been repeating.

Uploading Diagnostic never returned Diagnostic ID, so uploading file manually.

Issue has been circumvented by removing Docker.app manually, installing newest Docker for Mac, Edge channel (18.05.0-ce-mac67), running it, uninstalling it completely, then installing again from scratch.

### Diagnostic logs
```
Docker for Mac: version: 18.05.0-ce-mac67 (1fa4e2acfc1a52f79623add2390604515d32297e)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/EF38E307-6AFC-4DA8-A911-BCA302684620/20180611-112423.tar.gz
failure: com.docker.driver.amd64-linux is not running
[ERROR]  vpnkit
         Unexpected error connecting to /Users/lemberg/Library/Containers/com.docker.docker/Data/s51: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/lemberg/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/lemberg/Library/Containers/com.docker.docker/Data/docker.sock: check if service is running
         docker ps failed
[OK]     disk
```

**Comment by djs55** [comment]
It looks like the hypervisor failed to lock the disk image for writing:
```
2018-06-11 11:24:19.026939+0300  localhost com.docker.driver.amd64-linux[2687]: hyperkit: stderr: ^MCould not lock backing
 file: Resource temporarily unavailable
```
It looks like this is because a previous instance of `hyperkit` has leaked:
```
 2590   ??  S      0:37.94 com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 2 -m 8192M
```
I don't know what caused this -- we'll have to audit the task management code to look for problems. If it happens again let me know and try killing any stray `com.docker.hyperkit` processes.

Thanks for your report.

**Comment by modukar** [comment]
the same issue after I upgrade docker, but reinstall the old version, failed the same.
