### ISSUE TITLE
com.docker.driver.amd64-linux -db is not running

### ISSUE THREAD

**Issue by mfinholt** [docker/for-mac#299]
### Steps to reproduce

1. Install Stable or Beta release on MacOS 10.12 Beta 5
2. Start Docker
3. Run Diagnose and Feedback

### Expected behavior

Docker should start and run appropriately

### Actual behavior

The Docker Driver doesn't load and thus i get an error that docker ps failed

### Information

```
Diagnostic ID: 1A450397-D79B-442A-B388-48010826C978
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A286a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/mfinholt/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mfinholt** [comment]
Seems to be running fine after a restart

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
