### ISSUE TITLE
Docker failed during the execution. [ERROR]  vpnkit. Error connecting socket to 9p endpoint

### ISSUE THREAD

**Issue by AntonTutuka** [docker/for-mac#2992]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@AntonTutuka unfortunately there's nothing we can do without a set of diagnostics logs and/or a set of reproduction steps. There are some instructions here: https://docs.docker.com/docker-for-mac/troubleshoot/

In the meantime I'll close this ticket. Feel free to open a fresh one!
