### ISSUE TITLE
docker ps time out

### ISSUE THREAD

**Issue by SachinB2** [docker/for-mac#2995]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@SachinB2 unfortunately there's nothing we can do without more information, including a set of uploaded diagnostics (with the id quoted on the ticket so we can find them). I'll close this ticket for now but feel free to create another.
