### ISSUE TITLE
Docker is claiming my Macbook Pro Mid 2009 does not support Hypervisor

### ISSUE THREAD

**Issue by rponte** [docker/for-mac#3]
### Expected behavior
As far as I know my Macbook supports Hypervisor

### Actual behavior
Docker is claiming my Macbook Pro Mid 2009 does not support Hypervisor:

```
Incompatible CPU detected
Docker requires a processor with virtualization capabilities.
```
### Information

Diagnostic ID: 4C5B55F0-7F06-419C-903C-E7029E9EE155
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/rponte/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/4C5B55F0-7F06-419C-903C-E7029E9EE155/20160729-002736/qemu-img-check.stdout 2> /tmp/4C5B55F0-7F06-419C-903C-E7029E9EE155/20160729-002736/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/rponte/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/rponte/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/rponte/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/rponte/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/rponte/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Install Docker For Mac;
2. Run it;

**Comment by yallop** [comment]
> As far as I know my Macbook supports Hypervisor

Could you check by running `sysctl kern.hv_support`?  If your machine has hypervisor support you should see output like this:

```
$ sysctl kern.hv_support
kern.hv_support: 1
```

**Comment by amirmc** [comment]
The docs state that certain models from 2010 onwards should work.

*From https://docs.docker.com/docker-for-mac/*
- **System Requirements**: Docker for Mac will launch only if all these requirements are met.
  - Mac must be a 2010 or newer model, with Intel’s hardware support for memory management unit (MMU) virtualization; i.e., Extended Page Tables (EPT)
  - OS X 10.10.3 Yosemite or newer
  - At least 4GB of RAM
  - VirtualBox prior to version 4.3.30 must NOT be installed (it is incompatible with Docker for Mac)

**Comment by rponte** [comment]
Thanks. Unfortunately seems my Macbook doesn't support Docker for Mac. That's so sad :-(

**Comment by aurawindsurfing** [comment]
You need to install this version: https://docs.docker.com/toolbox/toolbox_install_mac/

**Comment by fabiocaccamo** [comment]
@aurawindsurfing from the linked docs: 

> If you have macOS 10.10.3 Yosemite or newer, consider using Docker Desktop for Mac instead. 

I have `OS X El Capitan 10.11.6` but it doesn't work.
