### ISSUE TITLE
Quitting Docker for Mac does not kill com.docker.vmnetd

### ISSUE THREAD

**Issue by mbertschler** [docker/for-mac#30]
### Expected behavior
Quitting Docker from the menu bar kills all Docker processes.

### Actual behavior
The `com.docker.vmnetd` process survives.

### Information

Diagnostic ID: D89032CA-B2D3-427F-8E06-66527CB81679
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start Docker for Mac.
2. Quit Docker for Mac via the icon in the menu bar.
3. Check for running processes that have `docker` in the name.

**Comment by dsheets** [comment]
Also observed in <https://forums.docker.com/t/issue-docker-app-after-quit-do-not-unload-com-docker-vmnetd-plist/19495>.

**Comment by djs55** [comment]
I took a quick look to see if we could switch to a more `inetd`-style mode of usage, but unfortunately start-and-run-forever seems to be `launchd`'s default *and* if the process exits too quickly `launchd` will refuse to spawn it again, assuming it has crashed. I think we just have to ignore this particular process. Note it is removed by the uninstall step.

I'll add a note to the docs.

**Comment by polishExperiment** [comment]
> Note it is removed by the uninstall step.

This is not true for Version 18.05.0-ce-rc1-mac63 (24246). I uninstalled docker for mac and vmnetd process was still there.

**Comment by lukaskuzmiak** [comment]
This causes MAJOR headache on macOS 10.14.x on `Version 18.06.1-ce-mac73 (26764)`, after quitting:

```
$ ps -ef | grep docker | grep -v grep
    0    79     1   0 11:14AM ??         0:00.02 /Library/PrivilegedHelperTools/com.docker.vmnetd
$
```

Trying to start a VMware Fusion VM:

![image](https://user-images.githubusercontent.com/6942669/47968849-3e17ed00-e024-11e8-9ff3-35a5b13b887f.png)

This helps unload it:
```
sudo launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
```

IMHO this is quite a big issue as on MacOS 10.14.x you can't run several hypervisors at once it seems and starting/stopping docker keeps blocking another hypervisor from starting.

**Comment by knightsc** [comment]
Shouldn't you just be able to change the

```
<key>RunAtLoad</key>
<true/>
```

key to 

```
<key>OnDemand</key>
<true/>
```

In the `com.docket.vmnetd.plist` file and things just work. `launchd` itself should then take care of creating the unix domain socket and when something tries to connect to it it will launch the daemon. The daemon itself then just needs to be made a little smarter and when it's idle for a certain amount of time it can just quit. launchd then takes care of launching it again as needed
