### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by telekid** [docker/for-mac#300]
Seems related to #246, #247, #276, #296

Note that this is macOS 10.11.6, not 10.12.x, so it is unlikely that this is related to #64 

The only way I was able to fix this was by using the Docker for Mac -> Preferences -> Reset feature. This is undesirable, as it meant that I had to rebuild all of my docker containers.

### Expected behavior
Opening docker for mac should start docker

### Actual behavior
Docker remains stuck in "docker starting…" state in menubar

### Information

Diagnostic ID: 7CF4BD4D-2188-483F-B5A8-0CE4D2A9D151
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in 7CF4BD4D-2188-483F-B5A8-0CE4D2A9D151/20160816-100814.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: VM: 2016-08-10 16:23:57 +0000 UTC daemon.info vsudd: 3752 Done. read: 188 written: 2463
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: VM: 2016-08-10 16:23:57 +0000 UTC daemon.info vsudd: 3753 Done. read: 188 written: 2383
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: VM: 2016-08-10 16:23:57 +0000 UTC daemon.info vsudd: 3756 Done. read: 188 written: 2463
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=4c5cb22f-f5f4-48f1-bdc9-c79dce54fada,path=/Users/jake/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/jake/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Aug 10 12:23:57 jake Docker[com.docker.driver.amd64-linux][15937] <Notice>: Interface will have uuid 4c5cb22f-f5f4-48f1-bdc9-c79dce54fada
```
