### ISSUE TITLE
docker gets super slow over time until factory reset on mac

### ISSUE THREAD

**Issue by vegivamp** [docker/for-mac#3001]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: macOS High Sierra 10.13.5

### Diagnostic logs

```
Docker for Mac: version 18.03.1-ce

```

### Steps to reproduce the behavior

  1. just do normal docker  opeations

**Comment by djs55** [comment]
@vegivamp unfortunately there's not much we can do without a set of diagnostics. Could you upload a fresh set of diagnostics after reproducing the issue and open a fresh ticket quoting the diagnostics id?

Thanks!
