### ISSUE TITLE
kubernetes check failed with

### ISSUE THREAD

**Issue by robertlcs** [docker/for-mac#3002]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@robertlcs unfortunately there's not much we can do without a diagnostics id or a set of repro instructions. I'll close this ticket for now but feel free to open a fresh one with new information.
