### ISSUE TITLE
kubernetes error in "Diagnose & Feedback" report

### ISSUE THREAD

**Issue by vasilaio** [docker/for-mac#3003]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BE72ACB6-E190-4F02-9666-6838A3278DCD

### Information

  - macOS Version: High Sierra 10.13.5
  - minikube version: v0.25.0 and 
  - kubectl version: Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/BE72ACB6-E190-4F02-9666-6838A3278DCD/20180615-171822.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk


```

### Steps to reproduce the behavior

  1. Just run "Diagnose & Feedback"
  2. ...

**Comment by djs55** [comment]
@vasilaio thanks for your report. The root case is that the diagnostics program detects `kubectl` and assumes that kubernetes must be enabled, even when it isn't. This has been fixed in the current edge and will be fixed in the next stable. The error is safe to ignore.
