### ISSUE TITLE
Docker vpn kit not running

### ISSUE THREAD

**Issue by shuoch** [docker/for-mac#3004]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 95D7AB13-16EB-4A5F-BF95-BC42D3DF006D

### Information

  - macOS Version: 10.12.6

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1314)
logs: /tmp/95D7AB13-16EB-4A5F-BF95-BC42D3DF006D/20180615-104806.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/shuo/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/shuo/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/shuo/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
It looks like the hypervisor crashed with an assertion failure:
```
2018-06-15 10:47:58.685794-0400  localhost com.docker.driver.amd64-linux[1949]: Assertion failed: (!REPLY_RING_EMPTY(sc)),
 function send_response_common, file src/lib/pci_virtio_sock.c, line 934.
```

**Comment by djs55** [comment]
I think this is a duplicate of #2872 

@shuoch do you have an easy way to reproduce this? Do you know anything which seems to trigger it?

**Comment by skeenan947** [comment]
I hit this too.  Multiple factory resets hasn't fixed it

**Comment by shuoch** [comment]
I'm not sure what triggers as Docker randomly would crash on occasion, next time it happens, I'll make a mental note to observe what I was doing right before then.

**Comment by rlbc** [comment]
Exact same problem. Happened two times. Both times a factory reset solved the problem.

**Comment by shuoch** [comment]
update on reproducing the error. I'm running [airflow](https://github.com/apache/incubator-airflow) on one of the containers. The crash happened right after I may have triggered too many requests by holding down cmd+r on the airflow webserver page in chrome.
