### ISSUE TITLE
com.docker.supervisor failed to start

### ISSUE THREAD

**Issue by dkkyeremateng** [docker/for-mac#3011]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@dkkyeremateng unfortunately there's not much we can do without a set of diagnostics. Could you either use the UI to upload a set of diagnostics or run the tool by hand with
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose
```
Could you then create a fresh ticket with the diagnostics id?

Thanks!
