### ISSUE TITLE
failure: com.docker.vpnkit is not running

### ISSUE THREAD

**Issue by dkkyeremateng** [docker/for-mac#3012]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: D955991D-44D7-4D63-A0F1-413BB7F7D5F7

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@dkkyeremateng thanks for your report.

Unfortunately the logs contain:
```
2018-06-18 16:59:20.739575+0000  localhost com.docker.driver.amd64-linux[4264]: Unable to create VM (-85377018)
2018-06-18 16:59:20.739605+0000  localhost com.docker.driver.amd64-linux[4264]: vmx_init: processor not supported by Hypervisor.framework
```
which means the hardware doesn't have the necessary support for virtualisation :( Have a look at the [system requirements page](https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install)

On this hardware you may be able to install VirtualBox and then [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_mac/), which still contains Docker but the experience is less smooth.

Sorry for the inconvenience.
