### ISSUE TITLE
[ERROR]  vpnkit, driver.amd64-linux, moby, osxfs, docker-cli

### ISSUE THREAD

**Issue by quangcuong10495** [docker/for-mac#3015]
- [ ] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 10.13.5

### Diagnostic logs

```
Docker for Mac: version 18.03.1-ce, build 9ee9f40

```

### Steps to reproduce the behavior

  Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/0E310343-6B23-4540-A060-6286D32472E9/20180619-175057.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/quangcuong10495/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/quangcuong10495/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns

**Comment by djs55** [comment]
The Apple `hypervisor.framework` failed to create a virtual machine:
```
2018-06-19 17:50:52.366940+0700  localhost com.docker.driver.amd64-linux[2472]: hv_vm_create failed
```
For reference the code is [here](https://github.com/moby/hyperkit/blob/753684065b518dca02cc991b759c7902bc40f964/src/lib/vmm/intel/vmx.c#L481).

Unfortunately the code doesn't log the exact error code -- I'll improve this.

@quangcuong10495 is there anything special about your hardware?

**Comment by djs55** [comment]
Also: does this happen every time, or is it intermittent?
