### ISSUE TITLE
docker login insists valid ID/Password is invalid

### ISSUE THREAD

**Issue by hskrasek** [docker/for-mac#3017]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 03B98C75-0224-4C5A-9CEC-54B4AFA27968

### Expected behavior
I'm able to login to Docker CLI with my correct user ID and password

### Actual behavior
Using the correct user ID and password, I am unable to login

### Information
  - macOS Version: 10.14

No matter what, even if I change my password to be something basic, I always get the following response: `Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password`.

I have tried everything I can think of, but cannot get the login to work. Unfortunately this is preventing me from being able to push an image to my private repository. Is there anyway around this?

### Diagnostic logs
```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.14 (build: 18A293u)
logs: /tmp/03B98C75-0224-4C5A-9CEC-54B4AFA27968/20180619-203406.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior
  1. Try to login with `docker login`
  2. Enter a valid user ID and password
  3. It fails. Always. Forever

**Comment by djs55** [comment]
@hskrasek thanks for your report. Unfortunately I can't find the diagnostics id in the system, although I found a timestamp which corresponds to this ticket so I think the upload may have been interrupted half way through. This means I can't really see what's going on :(

The latest version on the edge channel is [18.05.0-ce-mac67](https://download.docker.com/mac/edge/25042/Docker.dmg). Could you retry with that and then upload a fresh set of diagnostics?

Also could you let me know if you have a proxy set or not? Do normal `docker pull` commands work? Does networking in containers work ok? It's also worth checking that your shell does not have a `DOCKER_HOST` environment variable set, in case you're talking to the wrong engine + registry by accident.

**Comment by hskrasek** [comment]
@djs55 Just updated to `18.05.0-ce-mac67 (25042)` and no dice. No proxy set, I just did a `docker pull hello-world` which worked successfully. Oh and no `DOCKER_HOST` set. 

New diagnostic id: `03B98C75-0224-4C5A-9CEC-54B4AFA27968/20180624-104934`

Could this be caused by Mojave by any chance?

**Comment by djs55** [comment]
@hskrasek thanks for the update.

Looking in the logs I can see:

The CLI asks the docker daemon to `docker login`
```
2018-06-24 10:49:10.897075-0500  localhost com.docker.driver.amd64-linux[1795]: proxy << POST /v1.37/auth
```
The docker daemon establishes a TLS connection with `auth.docker.io`:
```
2018-06-24 10:49:10.688657-0500  localhost com.docker.vpnkit[1794]: DNS lookup auth.docker.io A: auth.docker.io <IN|22> [A (52.204.202.231)], auth.docker.io
<IN|22> [A (34.200.28.105)], auth.docker.io <IN|22> [A (35.169.231.249)], auth.docker.io <IN|22> [A (34.205.207.96)], auth.docker.io <IN|22> [A (34.200.90.16
)], auth.docker.io <IN|22> [A (52.22.181.254)], auth.docker.io <IN|22> [A (54.164.230.151)], auth.docker.io <IN|22> [A (52.54.216.153)]
2018-06-24 10:49:10.688688-0500  localhost com.docker.vpnkit[1794]: HTTP proxy --> 52.204.202.231:443 Host:auth.docker.io:443 (Origin): CONNECT
2018-06-24 10:49:10.737539-0500  localhost com.docker.vpnkit[1794]: HTTP proxy --> 52.204.202.231:443 Host:auth.docker.io:443 (Origin): Successfully connecte
d to 52.204.202.231:443
```
The docker engine performs a POST:
```
time="2018-06-24T15:49:10.233526291Z" level=debug msg="form data: {\"password\":\"*****\",\"serveraddress\":\"https://index.docker.io/v1/\",\"username\":\"...\"}"
time="2018-06-24T15:49:10.233697476Z" level=debug msg="attempting v2 login to registry endpoint https://registry-1.docker.io/v2/"
```
I omitted your username from the above log, but I had a quick look on the docker hub and I can't see it. For example my docker id is `djs55` and the URL https://hub.docker.com/u/djs55/ lists my repos. I couldn't see a public page corresponding to your username -- could you double-check it's correct? Make sure it's a username on the public registry and not a private one, or specify the name of the private registry on the `docker login` command-line (`docker login [SERVER]`)

**Comment by hskrasek** [comment]
@djs55 So I had a single private repo on my account, and that's why it wasn't working. The second I switched the repo over to public, I was able to login

**Comment by djs55** [comment]
@hskrasek thanks for the update. It sounds like a bug in the hub software -- perhaps file an issue on the [hub-feedback repo](https://github.com/docker/hub-feedback).

I'll close this issue as it appears not to be a bug in Docker for Mac, but if you do open an issue elsewhere please do link it to this one.

Thanks for your feedback.
