### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host? - OSX Docker 1.12.0-beta22

### ISSUE THREAD

**Issue by jeremyjjbrown** [docker/for-mac#302]
jeremybr@detritus:~ $ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### Steps to reproduce

1. any docker command on version Docker 1.12.0-beta22

### Expected behavior

The Docker Daemon should be running

### Actual behavior

The Daemon is not running in the vm or the client can not talk to it

### Information

```
Diagnostic ID: 79F83790-9198-4069-B6B9-C959591A25F7
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.11 (Build 15A284)
[OK]     docker-cli
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

Hyperkit looks normal

jeremybr@detritus:~ $ ps aux | grep hyperkit
jeremybr          450   0.1  1.1  4784304 184140   ??  S    10:32AM   0:10.66 /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2G -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=d19acc00-9942-4499-a70d-99e49d102bd7,path=/Users/jeremybr/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/jeremybr/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/jeremybr/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2,format=qcow -s 4,virtio-9p,path=/Users/jeremybr/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/jeremybr/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/jeremybr/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/jeremybr/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/jeremybr/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac -F /Users/jeremybr/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
jeremybr          447   0.0  0.0 573396512   5212   ??  S    10:32AM   0:00.01 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux
jeremybr          445   0.0  0.0 573426244   7888   ??  Ss   10:32AM   0:00.06 com.docker.osx.hyperkit.linux
jeremybr          440   0.0  0.0 573411872   5208   ??  S    10:32AM   0:00.02 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
jeremybr          439   0.0  0.0 573489580   7680   ??  S    10:32AM   0:00.04 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
jeremybr          981   0.0  0.0  2434836    780 s001  S+   10:36AM   0:00.00 grep hyperkit

**Comment by neilstepwd** [comment]
Remove Docker environment vars from your .bash_profile see 
https://docs.docker.com/docker-for-mac/troubleshoot/#workarounds-for-common-problems

**Comment by mwullink** [comment]
awesome, that fixed it.

**Comment by drcrallen** [comment]
I put stuff in so long ago I forgot I even did it. This post reminded me, thanks!
