### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by shmulya** [docker/for-mac#3025]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A7E04810-50EB-45A1-BD16-71C1BBD2D8FF

### Expected behavior
Docker have to start

### Actual behavior
Docker stuck at 'docker is starting'
Only one error in log: fcntl(F_PUNCHHOLE) failed: host filesystem does not support sparse files: Inappropriate ioctl for device

### Information

  - macOS Version: 10.12.6

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1314)
logs: /tmp/A7E04810-50EB-45A1-BD16-71C1BBD2D8FF/20180622-144143.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk
```

From system log:

Docker for Mac: version: 18.03.1-ce-mac65 

### Steps to reproduce the behavior

  1. Run docker
  2. Docker is starting
And it stuck on this state
![2018-06-22_14-51-04](https://user-images.githubusercontent.com/13420115/41775255-e6dd36c4-762b-11e8-9a94-334624e46eb6.png)

**Comment by djs55** [comment]
This looks the same as #2655 #3024 

Could you try with the most recent edge version [D4mac 18.05.0-ce-mac67](https://download.docker.com/mac/edge/25042/Docker.dmg). Does restarting the app fix it, or does it happen all the time?

**Comment by jimms** [comment]
@djs55 I have the same issue. The problem is still present on my computer after using edge version. I tried to restart 3 times, they are stuck in the starting status.

**Comment by djs55** [comment]
@jimms could you upload a diagnostic in that state? I'd like to have a look at the logs.

Thanks!

**Comment by jimms** [comment]
I have uploaded my diagnostic data. The diagnostic ID is `754C78EB-8E07-4580-9724-36236BBEDCA6/20180630-193056`

**Comment by mokhov** [comment]
@djs55 have the same issue, tried edge and got the same F7C074EF-3A35-4BA8-A0F7-FE877D79BB5B/20180711-114328

**Comment by jimms** [comment]
Docker is OK now. But I didn't upgrade it......
My Docker version is `Version 18.05.0-ce-mac67 (25042)`

**Comment by kenyee** [comment]
Same issue..clicked on diagnostic upload and ID is 79651593-B91C-4394-B74F-21280D99D87B/20180902000115
