### ISSUE TITLE
DOCKER HANGS WHEN DB2 DATA SERVER MANAGER STARTS

### ISSUE THREAD

**Issue by bscheken** [docker/for-mac#3026]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4B0D592-DF30-46BF-94E8-44F83F114F56

### Expected behavior
DB2 DATA SERVER MANAGER STARTS AND SHOW DATABASE CONNECTIONS
### Actual behavior
SPINS DURING DB2 DATA SERVER MANAGER START UP
### Information

  - macOS Version: 10.13.5

### Diagnostic logs

```
Docker for Mac: version 18.03.1-ce-mac65 (24312)

```

### Steps to reproduce the behavior

  1. START DB2 SERVER MANAGER

**Comment by djs55** [comment]
@bscheken unfortunately I can't find your diagnostics id in the list. Could you re-reproduce the problem and upload the diagnostics again? You can use either the Whale menu -> Diagnose and Feedback .. or the command-line:
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose --upload
```
Could you also describe the reproduction steps in more detail? Could you provide an example `Dockerfile` or `docker-compose.yml` that exhibits the problem?

Thanks in advance!
