### ISSUE TITLE
"Docker is starting" forever

### ISSUE THREAD

**Issue by diplay** [docker/for-mac#3028]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 66FB8925-D5B2-496C-9D3C-26E3CA593537

### Expected behavior
When i launch Docker app i expect it to work

### Actual behavior
"Docker is starting" status forever

### Information

  - macOS Version: 10.13.5
  - docker was working for a few days but after restart this problem appeared

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/66FB8925-D5B2-496C-9D3C-26E3CA593537/20180623-155123.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. Launch Docker app from Lauchpad
  2. Docker is starting forever

**Comment by diplay** [comment]
The same problem appears on Docker edge version

**Comment by oafashokov** [comment]
I have the same issue
Docker stable 
Version 18.03.1-ce-mac65 (24312)

**Comment by djs55** [comment]
This looks the same as #2655 -- the console has the same 
```
This selection will    ESC[09;58Htake you to the Boot   ESC[10;58HManager
```
text.

**Comment by djs55** [comment]
@diplay thanks for your report.

From the logs it looks like the `Docker.qcow2` was intact here:
```
2018-06-23 15:27:02.317170+0300  localhost com.docker.driver.amd64-linux[547]: HyperKit started (pid=559):...
2018-06-23 15:27:02.941941+0300  localhost com.docker.driver.amd64-linux[547]: com.docker.hyperkit: [INFO] Resized file to 267119 clusters (34191232 sectors)
2018-06-23 15:27:02.941997+0300  localhost com.docker.driver.amd64-linux[547]: com.docker.hyperkit: [INFO] block recycler starting with keep_erased = 2048
2018-06-23 15:27:02.944874+0300  localhost com.docker.driver.amd64-linux[547]: com.docker.hyperkit: [INFO] image has 0 free sectors and 267116 used sectors
com.docker.hyperkit: [INFO] block recycler: triggering background flush: 267116 used; 0 junk; 0 erased; 0 available; 0 copies; 0 roots; 0 Copying; 0 Copied; 0 Flushed; 0 Referenced; max_cluster = 267118
2018-06-23 15:36:55.298844+0300  localhost com.docker.driver.amd64-linux[547]: sending SIGTERM to com.docker.hyperkit pid: 559
```
and then
```
2018-06-23 15:38:49.735737+0300  localhost com.docker.driver.amd64-linux[1011]: HyperKit started (pid=1016):...
...
2018-06-23 15:38:49.752569+0300  localhost com.docker.driver.amd64-linux[1011]: com.docker.hyperkit: [INFO] image has 0 free sectors and 0 used sectors
```

Could you running
```
ls -l ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2
/Applications/Docker.app/Contents/MacOS/qcow-tool info ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2
```

After that, try moving that file somewhere else and then restarting the app -- hopefully it will restart with a fresh disk.

**Comment by ar0ne** [comment]
Hey @djs55, 
I had the same issue. I renamed this file and docker works now. Thanks!

**Comment by adib** [comment]
I'm also experiencing the same issue – docker won't start when the image file is moved to an external drive. Diagnostic ID: `84100E43-C696-4DC7-AB47-1D4CEBD1E59E/20190417065359`

**Comment by RiRa12621** [comment]
People are still experiencing this and constantly open new issues, maybe we should try to just keep one issue alive.

following up on what @djs55 was mentioning:
I am very much willing to help reproduce this issue.
Following up on the actual error message, which I was experiencing as well, I went into the actual vm 
via `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` and it kept flashing this message which is why the logs outside of the VM are polluted with it.
Here's what you get:
```
                                                         This selection will
                                                         direct the system to
                                                         continue to booting
                                                         process
```
once you actually press `enter` the VM starts up as expected.
I didn't have time yet to dig into where that signal would normally come from.
/remove-lifecycle stale
/lifecycle frozen
