### ISSUE TITLE
Insecure registries setting ignored for docker build?

### ISSUE THREAD

**Issue by colinjoy** [docker/for-mac#303]
### Expected behavior
build using image from private registry.

### Actual behavior
```
Step 1 : FROM docker.private.corp:50000/image:tag
Get https://docker.private.corp:50000/v1/_ping: x509: certificate signed by unknown authority
```
### Environment
Docker for mac
Docker version 1.12.0, build 8eab29e, experimental 
"Insecure registries" list in preferences ("Advanced" tab) includes `docker.private.corp`
`no_proxy` for `.private.corp` ist set and apparently honoured (otherwise it would not be able to find the registry at all)

**Comment by dsheets** [comment]
Are you using a domain name for your insecure registry? Is it a public domain name? Where is the expected DNS record for the domain held? Does your machine have custom DNS settings?

**Comment by colinjoy** [comment]
> Are you using a domain name for your insecure registry?

yes

> Is it a public domain name?

no

> Where is the expected DNS record for the domain held

see below

> Does your machine have custom DNS settings?

yes, see below

`host -a docker.private.corp`
```
Trying "docker.private.corp"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52772
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;docker.private.corp.		IN	ANY

;; ANSWER SECTION:
docker.private.corp.	3600	IN	CNAME	foo.private.corp.

;; AUTHORITY SECTION:
private.corp.		3600	IN	NS	dns02.private.corp.
private.corp.		3600	IN	NS	dns04.private.corp.
private.corp.		3600	IN	NS	dns01.private.corp.
private.corp.		3600	IN	NS	dns03.private.corp.

;; ADDITIONAL SECTION:
dns01.private.corp.	3600	IN	A	10.17.111.11
dns02.private.corp.	3600	IN	A	10.17.111.12
dns03.private.corp.	3600	IN	A	10.17.111.13
dns04.private.corp.	3600	IN	A	10.17.111.14
```
 
**OS X DNS settings:**
Search Domains: `private.corp`
DNS Servers: `10.17.111.11, 10.17.111.13`

**Comment by dsheets** [comment]
We don't yet support DNS search domains but it is on our roadmap and should be supported soon. Sorry for the inconvenience. 😕

**Comment by dsheets** [comment]
Also reported in #179.

**Comment by djs55** [comment]
Search domains configured in the Mac network settings (in the Advanced -> DNS window) are now monitored and the VM is updated when they change. This change will be in beta 25 on the Mac. The patches for Windows are almost ready too.

Beta 25 will hopefully be released on the week beginning 2016-09-05 (next week). Let me know if this works for you, please re-open the issue if not. Thanks for your patience!

**Comment by colinjoy** [comment]
this resolved the issue for us. 
thank you for the update!
