### ISSUE TITLE
Kubernetes is starting...

### ISSUE THREAD

**Issue by tinjaw** [docker/for-mac#3030]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2768739-92BF-4DBA-A584-E11FE04A5FA6/20180625-060635

### Expected behavior
That, eventually, Kubernetes will start

### Actual behavior
Kubernetese never starts completely

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version: 18.05.0-ce-mac67 (1fa4e2acfc1a52f79623add2390604515d32297e)
macOS: version 10.13.6 (build: 17G47b)
logs: /tmp/C2768739-92BF-4DBA-A584-E11FE04A5FA6/20180625-060635.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
         logs check failed with: (Failure
  "exec: /usr/bin/log show --debug --info --style syslog --last \"1d\" --predicate \"process matches \\\".*(ocker|vpnkit).*\\\" || (process in {\\\"taskgated-helper\\\", \\\"launchservicesd\\\", \\\"kernel\\\"} && eventMessage contains[c] \\\"docker\\\")\" >\"/tmp/C2768739-92BF-4DBA-A584-E11FE04A5FA6/20180625-060635/docker-system-os.log\" 2>&1: exit 65")
[OK]     docker-cli
[OK]     disk


```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@tinjaw thanks for your report. Unfortunately some of the logs are missing so I can't be sure but I suspect this is the same as #2990. If you would like to try a potential fix, there are some instructions here: https://github.com/docker/for-mac/issues/2990#issuecomment-398798486 -- let me know if this helps or not.

**Comment by tinjaw** [comment]
I tried disabling and then reenabling Kubernetes. Then I tried to Reset Kubernetes cluster. Then I reinstalled. That last task was the only thing that worked. Now I am back up and running. Thanks.
