### ISSUE TITLE
Docker for mac is slower than vmware fusion

### ISSUE THREAD

**Issue by evopen** [docker/for-mac#3032]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AD24CBDB-6B8C-48B9-9307-FD0927B44502

### Expected behavior
Docker runs faster than vmware fusion.

### Actual behavior
Docker is 23% slower than vmware fusion running Ubuntu 18.04 to build a linux kernel without cache, and 18% slower with cache.

### Information
I tried to build kernel on vmware and docker. with or without cache, the docker is slower than vmware fusion. Is this normal? 

I know mounting in docker for mac is extremely slow. I tried it. I did use a mount but my source code I'm trying to build is not in it. So I think this problem is not about the mount volume.

When building kernel using cache, vmware took 16 seconds with assigning all 8 vCPU to it. But Docker took 19 seconds to finish. 

And with a clean source folder(without cache), vmware fusion took 26 minutes while docker took 32 minutes to finish.

  - macOS Version: 10.13.5

### Diagnostic logs
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/AD24CBDB-6B8C-48B9-9307-FD0927B44502/20180626-153502.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
#ffb2b2#         logs check failed with: (Failure
  "exec: /usr/bin/log show --debug --info --style syslog --last \"1d\" --predicate \"process matches \\\".*(ocker|vpnkit).*\\\" || (process in {\\\"taskgated-helper\\\", \\\"launchservicesd\\\", \\\"kernel\\\"} && eventMessage contains[c] \\\"docker\\\")\" >\"/tmp/AD24CBDB-6B8C-48B9-9307-FD0927B44502/20180626-153502/docker-system-os.log\" 2>&1: exit 65")##
[OK]     docker-cli
[OK]     disk

```
Docker for Mac: Version 18.03.1-ce-mac65 (24312)

```

### Steps to reproduce the behavior

  1. Use the same flag for kernel makefile
  2. Assign all vCPU to vmware and docker.
  3. Build kernel separately with make -j vCPU number

**Comment by evopen** [comment]
@djs55 Thanks for your reply.
I noticed in the [faq](https://docs.docker.com/docker-for-mac/faqs/#qcow2-or-raw) page, there is no mention of raw file format only be used in edge version. I thought stable has it as well. Maybe the document needs an update if the latest edge won't roll out very soon.

I rerun the test with the mac67. And I got 34 min without cache, this might not accuracy because of the heat. But with cache I still got 19 seconds. Perhaps CPU utilization is the bottleneck? 

AD24CBDB-6B8C-48B9-9307-FD0927B44502/20180627-225045

**Comment by djs55** [comment]
@evopen thanks for the update. Unfortunately I couldn't find the diagnostic ID in the list -- do you recall if you uploaded it? The dialog for this has changed recently to require a separate confirmation for upload, as part of our GDPR compliance effort. If using the command-line it's possible to run
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose --upload
```
which should create the diagnostics and automatically upload it.

**Comment by evopen** [comment]
@djs55 I hit upload and it show me the ID. Maybe due to my proxy...

Here, AD24CBDB-6B8C-48B9-9307-FD0927B44502

**Comment by evopen** [comment]
I have a graph of CPU utilization from host OS.
![image](https://user-images.githubusercontent.com/1773234/41988540-05ee6406-7a6f-11e8-9efd-adfba3fbf10e.png)
It now very clear, I grab it from iStat. But you can see the first one is the docker allocated with 8 vCPU and run with 8 thread. The second one it the VM.
