### ISSUE TITLE
Fails to install without error if com.docker.vmnetd is disabled

### ISSUE THREAD

**Issue by Zenexer** [docker/for-mac#3035]
It's possible for the launchd daemon `com.docker.vmnetd` to be in a disabled state even when it doesn't exist on the system.  This persists after old versions of Docker are uninstalled.  Resetting Docker to defaults or completely reinstalling won't fix the issue.

When this happens, Docker won't proceed past the prompt to install the networking service.  It will prompt for credentials, but the dialog will not disappear.  Pressing OK again prompts for the credentials again.  There is no visible error, though the following will appear in Console.app:

```
Vmnetd: Cannot register new process: The operation couldn’t be completed. (CFErrorDomainLaunchd error 9.)
```

If the cause of this error is that `com.docker.vmnetd` is disabled, `launchctl print-disabled system` will output the following:

```
disabled services = {
	...
	"com.docker.vmnetd" => true
	...
}
```

If the value is `false` instead of `true`, or the entry is missing, the issue described here is not the cause of the error.

From Yosemite onward (at least as far as High Sierra), there is no direct way to completely restore this setting, such that the override entry is removed.  The only way to do so appears to be an offline edit of system files, typically via Single User Mode:

1. https://stackoverflow.com/questions/31206756/launchctl-remove-enabled-disabled-override
2. https://discussions.apple.com/thread/1872008

Since that's not something that the installer or troubleshooter can easily attempt, the next-best solution is to change the disabled override flag to `false`, either via:

```
sudo launchctl load -w /Library/LaunchDaemons/com.docker.vmnetd.plist
```

or:

```
sudo launchctl enable system/com.docker.vmnetd
```

`launchctl print-disabled system` will then look like this:

```
disabled services = {
	...
	"com.docker.vmnetd" => false
	...
}
```

In my case, to get Docker running, I had to completely restart the installation process, which involved:

```
sudo launchctl enable system/com.docker.vmnetd
sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist /Library/PrivilegedHelperTools/com.docker.vmnetd
open -a Docker
```

I was then prompted to install the networking service again, which succeeded.

This issue is probably the cause of these reports:

1. #61
2. #107
3. #644
4. #853
5. #866
6. #899
7. #903
8. #1903
9. ... and a lot more.  I got tired of searching through all of them.

Several of these report may alternatively have been caused by lack of a writable `/var/tmp/`, which is already mentioned in several places.

**Comment by djs55** [comment]
@Zenexer wow, thanks for such a thorough report! I'll see what we can do to handle this error better -- although we can't automatically run `sudo` I'm sure we could do a much better job of detecting this error and telling the user how to fix it.

**Comment by djs55** [comment]
The next version of edge and stable should detect this problem and prompt the user to fix it with

<img width="598" alt="capture d ecran 2018-05-28 a 14 21 25" src="https://user-images.githubusercontent.com/232441/40614892-dca5ceec-6284-11e8-9260-495d73722883.png">

I'll suggest adding the `sudo rm -f` to the dialog to make it more robust. I've also suggested adding the `launchctl print-disabled system` to the diagnostics report.

Also related to #2934 and #2687

**Comment by djs55** [comment]
The next version of edge and stable will have the `sudo rm -f` in the dialog too:

![screen shot 2018-06-27 at 16 25 22](https://user-images.githubusercontent.com/198586/41983753-e46327c4-7a26-11e8-8d02-934c1043c6b2.png)

@Zenexer thanks again for your help!
