### ISSUE TITLE
Yet another hanging DfM

### ISSUE THREAD

**Issue by steakknife** [docker/for-mac#3037]
Possibly related: https://github.com/docker/for-mac/issues/2984

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C0348288-C141-4E9F-8C60-652F99FE6A24

### Expected behavior

Not hanging.

### Actual behavior

Hangs on every `docker` command.

### Information
  - macOS Version: latest stable (10.13.5)
  - Docker for Mac: version: 18.03.1-ce-mac65
  - CPU utilization is high: other, unrelated processes
  - RAM utilization has at least 4 GiB free (16 GiB total on a A1278)
  - Storage has at least 14 GiB free
  - File handles open total: 15703, Docker and hyperkit file handles: 197, ulimit -nS: 65535

### Diagnostic logs
```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/C0348288-C141-4E9F-8C60-652F99FE6A24/20180626-192105.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk
```

### Steps to reproduce the behavior

Nondeterministic behavior, so no repeatable test-case.

**Comment by steakknife** [comment]
Installing Docker Edge...

**Comment by djs55** [comment]
The kernel logs show a timeout on the virtual disk:
```
[ 9009.610714] ata1.00: exception Emask 0x0 SAct 0x3fffe00 SErr 0x0 action 0x6 frozen
[ 9009.611601] ata1.00: cmd 61/e8:48:80:89:0b/00:00:01:00:00/40 tag 9 ncq dma 118784 out
[ 9009.611601]          res 40/00:00:00:00:00/00:00:00:00:00/00 Emask 0x4 (timeout)
```
I suspect it will work better with a "raw" formatted disk rather than a "qcow2" formatted one. For "raw" you need:
- latest edge
- macOS 10.13.4 or later
- hardware which supports APFS (i.e. has an SSD)
You might also need to reset to defaults if you currently have a "qcow2" since it will be preserved by default.
