### ISSUE TITLE
Cannot connect to the Docker daemon at tcp://localhost:2375.

### ISSUE THREAD

**Issue by girishkr** [docker/for-mac#3039]
$ docker ps
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
Diagnostics ID: 0AF160E1-002A-474F-815E-4045CABD1F25

**Comment by djs55** [comment]
@girishkr thanks for your report. When running Docker for Mac the daemon can be contacted on `/var/run/docker.sock`, which is the default path used by the `docker` CLI. I think you must have some `DOCKER_` environment variables set -- could you try
```
unset DOCKER_HOST
unset DOCKER_TLS_VERIFY
unset DOCKER_TLS_PATH
docker ps
```

**Comment by mopsyd** [comment]
@djs55 I have this same issue you had just mentioned on Arch Linux. Constantly.

**Comment by jeffery1992s** [comment]
@djs55  I also ran into this problem even though setting environment variables is not ok
And then we'll use this
sudo docker run -d dockerswarm/swarm:master join --advertise=192.168.188.130:2375 consul://192.168.188.130:8500

**Comment by baxhul** [comment]
Because of a similar problem I was using these variables. Since some days I started getting this problem. Removing these variables works fine. 
```
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay
```

**Comment by adammendoza** [comment]
> Because of a similar problem I was using these variables. Since some days I started getting this problem. Removing these variables works fine.
> 
> ```
>   DOCKER_HOST: tcp://localhost:2375
>   DOCKER_DRIVER: overlay
> ```

@baxhul Which file do we need to edit?

**Comment by codevanaco** [comment]
variables:
  DOCKER_HOST: tcp://docker:2375

**Comment by mrlinh9988** [comment]
> > Because of a similar problem I was using these variables. Since some days I started getting this problem. Removing these variables works fine.
> > ```
> >   DOCKER_HOST: tcp://localhost:2375
> >   DOCKER_DRIVER: overlay
> > ```
> 
> @baxhul Which file do we need to edit?

Thank you so much
