### ISSUE TITLE
v1.12.0-a (build:11213) won't start

### ISSUE THREAD

**Issue by dhawal55** [docker/for-mac#304]
### Expected behavior
docker should start in few seconds

### Actual behavior
docker fails to start

### Information

Diagnostic ID: D0C9A244-0E0C-4672-B3C4-76825350E06F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Update to latest docker v1.12.0-a
2. Start docker. it never starts.
[20160816-085919.tar.gz](https://github.com/docker/for-mac/files/420721/20160816-085919.tar.gz)

**Comment by subos2008** [comment]
Ditto for me. As per https://github.com/docker/for-mac/issues/300 resetting to factory defaults fixes it.

**Comment by dhawal55** [comment]
Yes, restting to factory default fixes it. Thanks.
