### ISSUE TITLE
Mac docker login failing

### ISSUE THREAD

**Issue by Algohash** [docker/for-mac#3040]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 9CD52279-3102-450E-9A16-07A7F6E98373

### Expected behavior
Trying to login to docker through "docker login" and also through docker gui in Mac. 

### Actual behavior
Login failure. Failure message
Error response from daemon: login attempt to https://registry-1.docker.io/v2/ failed with status: 401 Unauthorized

### Information
  - macOS Version: 10.12.6 (16G29)
  - docker works fine in my other Mac laptop, but in my office mac docker doest login. 
  - However, it worked once randomly, but after that I could never login to docker.

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/9CD52279-3102-450E-9A16-07A7F6E98373/20180627-200644.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

**Comment by djs55** [comment]
@Algohash thanks for your report. I can't find the diagnostics `9CD52279-3102-450E-9A16-07A7F6E98373/20180627-200644` in the list, but there is an earlier upload `9CD52279-3102-450E-9A16-07A7F6E98373/20180627-132502` so I had a look at that.

The docker engine logs have:
```
time="2018-06-27T14:29:38.110370400Z" level=debug msg="form data: {\"password\":\"...\",\"serveraddress\":\"https://index.docker.io/v1/\",\"username\":\"...\"}"
time="2018-06-27T14:29:38.110522300Z" level=debug msg="attempting v2 login to registry endpoint https://registry-1.docker.io/v2/"
time="2018-06-27T14:29:39.423577300Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: login attempt to https://registry-1.docker.io/v2/ failed with status: 401 Unauthorized"
```

Could you verify that you can log into the hub with this username and password: https://hub.docker.com

Assuming that works, could you try logging in from within the `docker` container inside the VM itself:
```
$ docker run -it --privileged --pid=host justincormack/nsenter1
/ # ctr -n services.linuxkit t exec -exec-id foo -t docker-ce sh
/ # docker login
```
Thanks!

**Comment by Algohash** [comment]
> Could you verify that you can log into the hub with this username and password: https://hub.docker.com
Yes. I can login to the hub with the same un/pw

> Assuming that works, could you try logging in from within the docker container inside the VM itself:
How should I do that? I simply copy paste the command you suggested.
`docker run -it --privileged --pid=host justincormack/nsenter1`
and its throwing an error

```
Unable to find image 'justincormack/nsenter1:latest' locally
docker: Error response from daemon: unauthorized: authentication required.
See 'docker run --help'.
```
Thanks.

**Comment by Algohash** [comment]
@djs55 since this is my office laptop, I'd tend to think that there might be. However, I can still login to hub.docker.com from the browser. If a proxy is blocking it, it should very well block the browser as well? Is it not?

**Comment by djs55** [comment]
@Algohash could you try running the login from a different network? Perhaps a guest network or a home network (if you're allowed to do that). 

It might also be worth capturing the HTTPS traffic on the Mac with a command like
```
sudo tcpdump -n -w /tmp/https.pcap -s 0 -i en0 port 443
```
I'd like to check whether the TLS certificate offered by the Docker login server matches the one we see from other places to check whether there is any MITM going on.

**Comment by KaiJunYan** [comment]
@djs55   that does not work ,any more suggestion ?    thanks

**Comment by subos2008** [comment]
I'm getting this today.

Is it still the case that the ```justincormack/nsenter1:latest``` image should be public and not even need auth? I've tried on two networks - cafe and telco and get the same behaviour on both:

```
$ docker login
Authenticating with existing credentials...
Stored credentials invalid or expired
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (docker@ryancocks.net):
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

 and

```
$ docker run -it --privileged --pid=host justincormack/nsenter1
Unable to find image 'justincormack/nsenter1:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/justincormack/nsenter1/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

If this is a blocked port or similar behaviour can we please get the error message improved?

**Comment by subos2008** [comment]
Oh so after this EPIC waste of time it turns out you just need to use your docker ID and not your email to login from the command line.

This is truly terrible user experience folks. You could at least abort login with a message if there in an '@' symbol in the ID.

**Comment by ytwu** [comment]
> Oh so after this EPIC waste of time it turns out you just need to use your docker ID and not your email to login from the command line.
> 
> This is truly terrible user experience folks. You could at least abort login with a message if there in an '@' symbol in the ID.

This is the right answer!
many users might confused by  the real docker id vs the account id;
usually the account id is an email address, but the docker id is the user name.

and you can login from docker desktop successfully with email id and password;
but when you pull images from command line, it returns with "auth error" and ask you to login with the right id & password.

**Comment by ytwu** [comment]
even today this bug is still open.
as I use the latest version of Docker for Mac Desktop, which is: Version 2.0.0.3 (31259)!

**Comment by Arconapalus** [comment]
Yea, I'm unable to login into the docker for mac desktop cli. I even changed my password and removed numbers and still login fails. I troubleshooted every topic that I Googled and then uninstalled and reinstalled and same error login failed

**Comment by Arconapalus** [comment]
I was able to use my email instead of username

**Comment by ebriney** [comment]
Hi, we did a check in the next edge and stable release to avoid this problem and you will get an error if you try to login with your email.
The real problem is that auth with email is not working in the cli and it will be fixed later.
Sorry for that.

**Comment by NextZeus** [comment]
# Test docker login With modify Docker General Config (macOS High Sierra 10.13.3 & Docker Engine:18.09.2)

## 1. With GUI Account login
![image](https://user-images.githubusercontent.com/10203487/60328422-d7837d00-99c0-11e9-8ae4-c5e3319f1769.png)

### 1.1 With General ->  Securely store Docker logins in macOS keychain (checked)
![image](https://user-images.githubusercontent.com/10203487/60328453-e36f3f00-99c0-11e9-87a3-0312fa67125e.png)

#### docker login failed
![image](https://user-images.githubusercontent.com/10203487/60328521-f97cff80-99c0-11e9-8581-f096483f14a5.png)

### 1.2 With General ->  Securely store Docker logins in macOS keychain (unchecked)
![image](https://user-images.githubusercontent.com/10203487/60328589-25988080-99c1-11e9-9ef4-48b8bf52ac4f.png)

#### docker login successed
![image](https://user-images.githubusercontent.com/10203487/60328627-3ea13180-99c1-11e9-88a7-daea257c8d4f.png)

**it will Authenticating with existing credentials**.

------------------------------------------------------------------------------------------------

## 2. With GUI Account logout
![image](https://user-images.githubusercontent.com/10203487/60328663-54aef200-99c1-11e9-8345-b91260816940.png)

### 2.1 With General ->  Securely store Docker logins in macOS keychain (checked)
#### docker login failed
![image](https://user-images.githubusercontent.com/10203487/60328751-81630980-99c1-11e9-9505-6b3e3b45d6ca.png)

### 2.2 With General ->  Securely store Docker logins in macOS keychain (unchecked)
#### docker login successed
![image](https://user-images.githubusercontent.com/10203487/60328776-9049bc00-99c1-11e9-9440-f03960c6de0f.png)



SO,

**unchecked** General->Securely store Docker logins in macOS keychain,  it solved my docker login failed problem

**Comment by carltonbrown** [comment]
Yes.   This was driving me crazy.   It worked when I unchecked:  General->Securely store Docker logins

**Comment by renatoathaydes** [comment]
The Mac's keychain seems to be having issues with Docker and other apps as well (I think my keybase app has the same issue)... not sure what can be causing these.

**Comment by pauleikis** [comment]
Unchecking General->Securely store Docker logins did not work for me, but appears that you cannot paste passwords into the login field, typing the password manually worked (pasting it in the web form worked though)

**Comment by capex** [comment]
This problem was solved for me by first entering my email in the DockerID field, getting an error message telling me that I need to enter my DockerID, and then entered the DockerID. Worked.

**Comment by e40** [comment]
@pauleikis typing the password didn't work for me.

@capex that trick didn't work for me, either.

**Comment by armchairdj** [comment]
Why on earth would pasting passwords be disabled? I need to type my 32-digit password manually when I have a perfectly good password manager to store it securely?

**Comment by ravidsinghbiz** [comment]
Weird but @capex solution worked for me as well with the same issue.

**Comment by hankchan101** [comment]
same issue
