### ISSUE TITLE
Another DfM hanging issue... Never completes startup process.

### ISSUE THREAD

**Issue by Marz-on-LendStreet** [docker/for-mac#3044]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 49ADC703-B5A0-47A8-B48C-B5A141CDD464

### Expected behavior
Docker is started

### Actual behavior
Docker is starting... forever.

### Information

  - macOS Version: 10.12.6

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1408)
logs: /tmp/49ADC703-B5A0-47A8-B48C-B5A141CDD464/20180629-170014.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. Double click Docker.app from Applications folder.
  2. ...

**Comment by razmser** [comment]
Same problem on `Version 18.05.0-ce-mac67 (25042)`

**Comment by Marz-on-LendStreet** [comment]
For some reason, this issue seems to have resolved itself for me. I left Docker alone for a while, and suddenly it started up fine. Not sure what that means to the bug report, but it can be closed.
