### ISSUE TITLE
docker-cli failed on docker-compose up

### ISSUE THREAD

**Issue by quantizer** [docker/for-mac#3054]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F237E67B-EEEE-42A4-B438-20558FD7116E/20180705-160506

### Information

  - macOS Version: 10.13.5 (17F77)

### Diagnostic logs

```
Docker for Mac: version: 18.05.0-ce-mac67 (1fa4e2acfc1a52f79623add2390604515d32297e)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/F237E67B-EEEE-42A4-B438-20558FD7116E/20180705-160506.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk
```

### Steps to reproduce the behavior

  1. Run `docker-compose up -d`
  2. Stuck on the step when images pulling, downloading and extracting

**Comment by imarsman** [comment]
I am having the same problem. I will be submitting diagnostics as well.
