### ISSUE TITLE
/etc/resolv.conf in container does not have search domains from host Mac

### ISSUE THREAD

**Issue by keepsimple1** [docker/for-mac#3057]
[20180705-142452.tar.gz](https://github.com/docker/for-mac/files/2168306/20180705-142452.tar.gz)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 75D348B2-67FD-4EDF-A24F-4EC1A6C57D91

### Expected behavior
/etc/resolv.conf file in Docker container has the search domain line (e.g. "search <...>")  inherited from the host (Mac). 

### Actual behavior
/etc/resolv.conf file in Docker container has no search domain line.

### Information

  - macOS Version: 10.13.5

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/75D348B2-67FD-4EDF-A24F-4EC1A6C57D91/20180705-142452.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Make sure host Mac has "search domains" set in Network Preferences. 
  2. docker run <...>
  3.  Check /etc/resolv.conf for the line starting with "search " .

**Comment by godbout** [comment]
Still struggling with this. Any solution?

**Comment by MalikKillian** [comment]
Experiencing this issue on Docker 18.06 for Mac.  Have confirmed exact same project (build script, Dockerfile, docker-compose) will generate a valid `/etc/resolv.conf` on Docker 1.12.3 for Mac.

Only workaround is to copy a new resolv.conf into the image and replace it as part of **CMD** instruction.

**Comment by timurkhisamov** [comment]
Up, I have same problem on `Docker version 19.03.5, build 633a0ea`. Any solution updates?
