### ISSUE TITLE
Docker Corruption after Mac Restore

### ISSUE THREAD

**Issue by drubarth** [docker/for-mac#306]
### Expected behavior
Docker was working fine.

### Actual behavior
After a restore it tries to start but never does completely.
I tried reinstalling, but that doesn't help.
I suspect I need to uninstall some extra files, but can't find any documentation on how to truly completely uninstall Docker from my Mac.

### Information

Diagnostic ID: A7E3B396-812F-4455-87FA-CE8799EDEA2D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/darryl/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
How did you attempt to reinstall? I recommend using the `Uninstall` and/or `Reset to Factory Defaults` buttons in `Preferences`.

**Comment by drubarth** [comment]
Docker attempts to start, but never gets past the "Docker is starting..." When I click on Preferences in the menu I get "Error Failed to retrieve settings values. failed to get memory setting". 

Is there a way from the command line to reset the settings to the factory defaults? I suspect that may get it working again. 

thanks, 
Darryl 

www.LabAnalytix.com 
775-996-5775 

| From: "David Sheets" <notifications@github.com>
| To: "docker/for-mac" <for-mac@noreply.github.com>
| Cc: "Darryl Rubarth" <dr@exyst.com>, "Author" <author@noreply.github.com>
| Sent: Wednesday, August 17, 2016 3:28:54 AM
| Subject: Re: [docker/for-mac] Docker Corruption after Mac Restore (#306)

| How did you attempt to reinstall? I recommend using the Uninstall and/or Reset
| to Factory Defaults buttons in Preferences .

| —
| You are receiving this because you authored the thread.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by dsheets** [comment]
Removing `~/Library/Containers/com.docker.docker` is almost equivalent to factory reset. Please give that a try and let us know how it goes.

**Comment by mchiang0610** [comment]
Closing for now due to non-reply. We will reopen this when we do. 

May be similar to #119 as well.

**Comment by marcheiligers** [comment]
I ran into a `Fatal Error: com.docker.osx.hyperkit.linux could not be started` error after upgrading to Docker Version 1.13.0 (15072) on OS X Version 10.11.6 (15G1217) today. `rm -rf ~/Library/Containers/com.docker.docker` resolved for me.
