### ISSUE TITLE
Unable to start Docker for mac

### ISSUE THREAD

**Issue by glambert22** [docker/for-mac#3063]
Diagnostic ID 6739408F-2352-45F0-9334-0449A6DD0812

  - [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6739408F-2352-45F0-9334-0449A6DD0812

### Information

  - macOS Version: 10.13.5 (build: 17F77)

### Diagnostic logs
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.5 (build: 17F77)
logs: /tmp/6739408F-2352-45F0-9334-0449A6DD0812/20180705-145653.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/gregorylambert/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/gregorylambert/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/gregorylambert/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ishtyaq** [comment]
use your docker login on CLI, it will work.

**Comment by bgrieder** [comment]
Ficed on my end; for some reason VT was deactivated in my BIOS

**Comment by glambert22** [comment]
appeared to be user error on my part.
