### ISSUE TITLE
Trouble

### ISSUE THREAD

**Issue by ultonic** [docker/for-mac#3072]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1BD10B76-E951-4587-8E29-759CC4B7914C

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Sorry, we need don't have enough information to investigate, so I'm closing this. You can open a new issue detailing your problem by following the [troublesooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
