### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by wungle** [docker/for-mac#3078]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Sorry we can't investigate without more information, if the issue persists, feel free to open a new issue with a diagnostics ID and more details.
