### ISSUE TITLE
Docker cannot start

### ISSUE THREAD

**Issue by mikewu1211** [docker/for-mac#3079]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
Sorry we  can't investigate without diagnostics, so I'm closing this. Feel free to open a new issue more information following the steps at https://docs.docker.com/docker-for-mac/troubleshoot/
