### ISSUE TITLE
Configure docker preferences programmatically

### ISSUE THREAD

**Issue by santiagocanti** [docker/for-mac#3081]
### Expected behavior
I've been trying to configure the number of CPUs and Memory used by Docker for mac in a programmatic way but with no success. In the past I was able to achieve this by following the steps mentioned [here](https://github.com/docker/for-mac/issues/1434), but now these files don't seem to be there anymore.

I expected there would be a way of changing these kind of settings in a programmatic way.

Is there any way I could change these settings in a programmatic way now or is it only possible via UI?
### Actual behavior
I'm not being able to find a way of achieving this. Been looking at the docs and old issues but couldn't find anything that works.

### Information
  - macOS Version: 10.13.5
  - Docker Version: 18.03.1-ce-mac65 (24312)

**Comment by derimagia** [comment]
Try the `~/Library/Group Containers/group.com.docker` directory, I believe that's where the config is now

**Comment by santiagocanti** [comment]
@derimagia it looks like the config is there, will try that and add my results here. Thanks a lot!

**Comment by santiagocanti** [comment]
@derimagia that works like a charm, and there is no need to do `git add` and `git commit` as stated by the original answer but you do have to restart docker in order to make the changes. Thanks!
