### ISSUE TITLE
sql server 

### ISSUE THREAD

**Issue by kishorevunna** [docker/for-mac#3086]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kishorevunna** [comment]
6BED23D8-2E26-4CB2-941F-32621CB8B523

**Comment by LoreenRH** [comment]
Sorry, we need don't have enough information to investigate, so I'm closing this. You can open a new issue detailing your problem by following the [troubleshooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
