### ISSUE TITLE
docker is starting(forever)

### ISSUE THREAD

**Issue by yutou** [docker/for-mac#3088]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
Diagnostics ID: FEBDBB49-5E61-4A2A-8967-E018F302CB05
Expected behavior

Actual behavior

Information

macOS Version: 10.13.5 (17F77)
Diagnostic logs

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.13.5 (build: 17F77)
logs: /tmp/FEBDBB49-5E61-4A2A-8967-E018F302CB05/20180717-133142.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by oafashokov** [comment]
have the same issue

Information

macOS Version: 10.13.6 (17G65)

Diagnostic logs
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.6 (build: 17G65)
logs: /tmp/5B0F0DDE-3E45-427D-9272-4B434A372457/20180719-190355.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

**Comment by azotova** [comment]
I seem to have the same issue #3109
