### ISSUE TITLE
Fatal Error when installed with Domain account

### ISSUE THREAD

**Issue by masonjm** [docker/for-mac#309]
### Expected behavior

Docker for Mac starts.
### Actual behavior

Fatal Error: com.docker.osx.hyperkit.linux failed to start. Exit code 1.
### Information

```
Diagnostic ID: 496D76E1-01C0-463C-832C-908ABED87B8D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/496D76E1-01C0-463C-832C-908ABED87B8D/20160816-094348/qemu-img-check.stdout 2> /tmp/496D76E1-01C0-463C-832C-908ABED87B8D/20160816-094348/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Domain/example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
```
### Steps to reproduce
1. Have a domain account
2. Install Docker for Mac
3. Try to start it
4. Get error dialog

I've been able to reproduce this on two iMacs (both Yosemite and El Capitan). Both macs have been setup as part of an ActiveDirectory domain, but I didn't do that setup so I'm not sure how it was done.

I do know that `$HOME` looks like `/Domain/example.com/Users/username` and `$USER` looks like `username@example.com`.

I also know that Directory Service is locked down more than usual (`chsh` and `chpass` are unable to change some values).

**Comment by ijc25** [comment]
Hi @masonjm thanks for the report and sorry for the delay in getting back to you.

Unfortunately your logs seem to consist of lots and lots (and lots!) of:

"TMCCFS 2916 ERROR needToScanThisExecve ==<VARIOUS DOCKER 4 MAC COMPONENT>" and similar needToScanThisClose. Seems like perhaps some antivirus or IDS is interfering with the operation of Docker?

Are you still seeing this with the latest stable version (1.12.3 at time of writing). If so would you be able to try a new diagnostic upload with that version since the current one is lacking lots of important pieces.

**Comment by ijc25** [comment]
Oh wait, or knew your nick was familiar, you have also reported #747. Given that in that issue you appear to have gotten further than you had in this ticket I suppose you managed to get past this issue. I'm going to close on that basis, but if there is stil something unique (i.e. not #747) here please do reopen.
