### ISSUE TITLE
Docker for mac becomes extremely slow at times and fan starts running loudly, all docker commands freeze

### ISSUE THREAD

**Issue by ranjanasim** [docker/for-mac#3097]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1606708A-6709-4BE3-9F9D-ECFF507D6B7C

### Expected behavior
Docker commands should run smooth
### Actual behavior
all docker commands and docker terminal freezes with fan running loud and macbook body emitting heat.
### Information

  - macOS Version:
10.12.6
### Diagnostic logs

```
Docker for Mac: version...
Version 18.03.1-ce-mac65 (24312)
```

### Steps to reproduce the behavior

  1. Happens all of a sudden, once in 2-3 days

**Comment by LoreenRH** [comment]
Sorry, we need don't have enough information to investigate, so I'm closing this. You can open a new issue detailing your problem with a _diagnostics ID_, or following the [troubleshooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
