### ISSUE TITLE
About and Diagnose & Feedback windows do not allow cmd + C

### ISSUE THREAD

**Issue by mbertschler** [docker/for-mac#31]
### Expected behavior
Copying version or debug information from these 2 windows by pressing `cmd` + `C` for including that information in an issue for example. 

### Actual behavior
Nothing gets copied to the clipboard. The text is selectable, but not copyable.

### Information
Diagnostic ID: D89032CA-B2D3-427F-8E06-66527CB81679
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK] docker-cli
[OK] app
[OK] moby-syslog
[OK] disk
[OK] virtualization
[OK] system
[OK] menubar
[OK] osxfs
[OK] db
[OK] slirp
[OK] moby-console
[OK] logs
[OK] vmnetd
[OK] env
[OK] moby
[OK] driver.amd64-linux

### Steps to reproduce the behavior

  1. Open *About Docker* or *Diagnose and Feedback...* from the Docker icon in the menu bar.
  2. Try to copy some text from the windows, nothing gets copied into the clipboard.

**Comment by gdevillele** [comment]
Thanks for reporting this issue.
A fix has been submitted. Should be fixed in `beta 22`.

**Comment by djs55** [comment]
Beta 22 has been released for a few weeks -- please re-open this issue if the problem persists.
