### ISSUE TITLE
IT's not starting

### ISSUE THREAD

**Issue by rahulreddyv** [docker/for-mac#3103]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Closing as there are no diagnostics or detailed info to investigate the issue
