### ISSUE TITLE
config.json reset after reboot, when "Securely store Docker logins in macOS keychain" is unticked.

### ISSUE THREAD

**Issue by brad-jones** [docker/for-mac#3104]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0FDB9650-36C0-48D5-AAB2-C8AF91388F5C/20180720061111

### Expected behavior
When _"Securely store Docker logins in macOS keychain"_ is unticked, I expect any docker logins stored in `~/.docker/config.json` to persist between reboots.

### Actual behavior
After restarting mac OS, the contents of `~/.docker/config.json` is reset and thus commands such as `docker pull` fail.

### Information
```
$ docker version
Client:
 Version:      18.06.0-ce-rc3
 API version:  1.38
 Go version:   go1.10.3
 Git commit:   cbfa3d9
 Built:        Thu Jul 12 05:15:46 2018
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Engine:
  Version:      18.06.0-ce-rc3
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   cbfa3d9
  Built:        Thu Jul 12 05:26:13 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

Starting with a config file that looks like:
```json
{
  "auths" : {
    "https://index.docker.io/v1/" : {
      "auth" : "..."
    }
  },
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.06.0-ce-rc3 (darwin)"
  },
  "experimental" : "enabled",
  "stackOrchestrator" : "swarm"
}
```

After a reboot it looks like:
```json
{
  "experimental" : "enabled",
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.06.0-ce-rc3 (darwin)"
  },
  "stackOrchestrator" : "swarm"
}
```

This was also happening with the previous edge version _18.05_

macOS Version:
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.5 (17F77)
      Kernel Version: Darwin 17.6.0
      Boot Volume: MacOs
      Boot Mode: Normal
      Computer Name: Brad’s MacBook Pro
      User Name: Brad Jones (brad)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 16 minutesbehavior
```

Possibly related to: https://github.com/docker/for-mac/issues/1826 As I have seen similar behavior.

**Comment by gtardif** [comment]
Thanks for your report @brad-jones, we can reproduce the issue and a fix will be included in the next release (available soon)
