### ISSUE TITLE
Docker for macOS 18.06.0-ce-rc3-mac68 breaks during update

### ISSUE THREAD

**Issue by jakirkham** [docker/for-mac#3105]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Unfortunately unavailable due to hang

### Expected behavior

Docker is able to start itself after updating.

### Actual behavior

Docker starts, asks for password, and runs into the dialog below. Selecting either "Diagnose & Feedback" will cause it to hang and use up CPU. Only force quitting will stop the problem. The "Exit" option just exits. "Resetting" has no effect on the problem.

<img width="710" alt="screen shot 2018-07-20 at 10 44 00" src="https://user-images.githubusercontent.com/3019665/43008754-db5b1b38-8c09-11e8-916f-b3f80582e232.png">

### Information

  - macOS Version: 10.11
  - Docker Channel: Edge
  - Docker Version: 18.06.0-ce-rc3-mac68

### Diagnostic logs

As noted above, "Diagnose & Feedback" hangs the app and requires a force quit. So can't provide the logs from there unfortunately. However macOS did generate a diagnostic report that it sent to Apple. Have attached that below.

[macOS System Report to Apple.txt](https://github.com/docker/for-mac/files/2214357/macOS.System.Report.to.Apple.txt)

### Steps to reproduce the behavior

  1. Allow Docker to update to 18.06.0-ce-rc3-mac68.
  2. Follow the usual dialogs.
  3. Attempt to get diagnostic information from Docker.

**Comment by jakirkham** [comment]
Should add this happens with a totally fresh download of Docker for macOS (Edge).

**Comment by jakirkham** [comment]
Installing Docker for macOS (Stable) 18.03.1-ce-mac65 fixed the problem. Though had to reset everything again as part of the install.

**Comment by gtardif** [comment]
Hi @jakirkham, we will soon release a stable release, very close to 18.06.0-ce-rc3-mac68, so it might be helpful to help you on this 18.06.0-ce-rc3-mac68 release. 
Could you run `log show --style syslog --last 3h --info --debug | grep Vmnetd` and attach the output in this issue, it might help us to debug this. 
(This should get logs from your previous install, or you can change the `--last 3h` to match the time you installed 18.06.0-ce-rc3-mac68 previously)

**Comment by jakirkham** [comment]
Thanks for looking into this, @gtardif.

Think I'm missing something. Ran the command, but there is no `log` command. Was there something that was supposed to proceed that?

**Comment by gtardif** [comment]
Ah, the `log` command was not available on OSX 10.11, didn't realise you were running this version. Can't remember now how to get OSX logs on this version via command line ; if you get a chance to try to restart Docker Desktop 18.06.0-rc3, open Console.app on the side, and filter log messages on "Vmnetd" while Docker is starting

**Comment by jakirkham** [comment]
Here's the output of `syslog | grep vmnetd` from July 20. Does that help?

```
Jul 20 10:24:05 kirkhamj-lm1 Docker[85680] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:24:42 kirkhamj-lm1 Docker[85697] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:28:04 kirkhamj-lm1 Docker[85750] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:28:27 kirkhamj-lm1 Docker[85766] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:28:34 kirkhamj-lm1 Docker[85766] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:28:39 kirkhamj-lm1 Docker[85766] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:28:44 kirkhamj-lm1 Docker[85766] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:29:04 kirkhamj-lm1 Docker[85785] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:31:35 kirkhamj-lm1 Docker[85804] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:35:26 kirkhamj-lm1 Docker[85828] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:38:26 kirkhamj-lm1 com.docker.vmnetd[89] <Notice>: /Library/PrivilegedHelperTools/com.docker.vmnetd starting
Jul 20 10:39:19 kirkhamj-lm1 Docker[761] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:43:56 kirkhamj-lm1 Docker[2413] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:54:06 kirkhamj-lm1 Docker[3683] <Error>: UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: No such file or directory
Jul 20 10:56:14 kirkhamj-lm1 com.docker.vmnetd[4158] <Notice>: Client reports version 1, commit 93354b38bd7210badafff8e0ce1f0be9a465be83
Jul 20 10:56:14 kirkhamj-lm1 com.docker.vmnetd[4158] <Notice>: client requests com.docker.vmnetd uninstall
Jul 20 10:56:14 kirkhamj-lm1 com.docker.vmnetd[4158] <Notice>: com.docker.vmnetd uninstall complete
Jul 20 10:56:14 kirkhamj-lm1 com.docker.vmnetd[4158] <Notice>: Deleted vmnetd socket /var/tmp/com.docker.vmnetd.socket
Jul 20 10:56:21 kirkhamj-lm1 com.apple.xpc.launchd[1] (com.docker.vmnetd) <Warning>: Unknown key for string: Version
Jul 20 10:56:21 kirkhamj-lm1 Docker[4164] <Notice>: /Library/PrivilegedHelperTools/com.docker.vmnetd starting
Jul 20 10:56:21 kirkhamj-lm1 Docker[4167] <Critical>: client with uid 208494839 requests com.docker.vmnetd install symlinks
Jul 20 10:58:51 kirkhamj-lm1 Docker[4240] <Critical>: client with uid 208494839 requests com.docker.vmnetd install symlinks
Jul 20 10:58:54 kirkhamj-lm1 Docker[4252] <Notice>: client requests com.docker.vmnetd uninstall
Jul 20 10:58:54 kirkhamj-lm1 Docker[4252] <Notice>: com.docker.vmnetd uninstall complete
Jul 20 10:58:54 kirkhamj-lm1 Docker[4252] <Notice>: Deleted vmnetd socket /var/tmp/com.docker.vmnetd.socket
Jul 20 10:59:04 kirkhamj-lm1 com.apple.xpc.launchd[1] (com.docker.vmnetd) <Warning>: Unknown key for string: Version
Jul 20 10:59:04 kirkhamj-lm1 Docker[4267] <Notice>: /Library/PrivilegedHelperTools/com.docker.vmnetd starting
Jul 20 10:59:04 kirkhamj-lm1 Docker[4279] <Critical>: client with uid 208494839 requests com.docker.vmnetd install symlinks
```

**Comment by ebriney** [comment]
Hi everybody.
Quit the app, then in a shell try that:

```
sudo launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo launchctl remove /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
```

Relaunch 18.06-ce-rc3-mac68, it should do the new install.

**Comment by axnsantana** [comment]
Worked like a charm!
Thanks a lot!

**Comment by jakirkham** [comment]
Guessing the combination of resetting to factory defaults, restarting my computer, and installing the stable Docker for macOS did that, correct?
