### ISSUE TITLE
stuck in "starting..." state

### ISSUE THREAD

**Issue by kevwil** [docker/for-mac#311]
### Expected behavior
Docker should start up cleanly and run
### Actual behavior
Docker icon animation never stops, always in a "starting ..." state.
### Information

Diagnostic ID: F52853AE-C9DB-4E20-8223-8EA5660F09DF
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ... Boot your machine and login.
2. ... Watch Docker fail to run.

**Comment by eranwitkon** [comment]
Same issue... any resolution?

**Comment by levans002** [comment]
Same issue here.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by jemattson** [comment]
Same issue, any updates from Docker on this?

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in F52853AE-C9DB-4E20-8223-8EA5660F09DF/20160816-133039.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-08-11T19:32:26.797122399Z" level=debug msg="Using default logging driver json-file"
time="2016-08-11T19:32:26.797655423Z" level=debug msg="Golang's threads limit set to 13950"
time="2016-08-11T19:32:26.797944781Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-08-11T19:32:26.801373329Z" level=debug msg="Using graph driver aufs"
time="2016-08-11T19:32:26.822363881Z" level=debug msg="Failed to load mount 3503bd5a1b72675ea7ffc120cc708b32cd4cdc21534a664eb76c30d2a7978251: invalid mount id value"
time="2016-08-11T19:32:26.828403253Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-11T19:32:26.828684761Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-11T19:32:26.852081848Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-08-11T19:32:26.854448855Z" level=debug msg="Loaded container 0dbffe77c588e22191eae8b3b4b1c30547aab8a29a222d0cb16599f8b2097f19"
time="2016-08-11T19:32:26.855346388Z" level=error msg="Failed to load container mount 3503bd5a1b72675ea7ffc120cc708b32cd4cdc21534a664eb76c30d2a7978251: mount does not exist"
```
