### ISSUE TITLE
Cannot connect to jupyter notebook inside container

### ISSUE THREAD

**Issue by lucianthorr** [docker/for-mac#3111]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostic ID: 631C9713-6408-467D-A0DD-8D2DDEE6E59F

### Expected behavior
I should be able to connect to the jupyter notebook running inside the container from my web-browser at http://localhost:8888
### Actual behavior
No connection
### Information

  - macOS Version:  10.13.6

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.6 (build: 17G65)
logs: /tmp/631C9713-6408-467D-A0DD-8D2DDEE6E59F/20180723-175738.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```
Diagnostic ID: 631C9713-6408-467D-A0DD-8D2DDEE6E59F

### Steps to reproduce the behavior

I have two macbooks running Docker for Mac.  (one work, one personal)
I can connect to the jupyter notebook on my work computer but running identical commands on my personal computer does not provide access.

Commands are as follows, starting from the repo:
```
1.  git clone https://github.com/pkmital/CADL.git
2.  cd CADL/
3.  docker build -t cadl .
4.  docker run -it -p 8888:8888 -p 6006:6006 -v /$(pwd)/session-1:/notebooks --name tf cadl /bin/bash
```
And then inside the container:
5.  `jupyter notebook --allow-root`
And then in the browser:
6.  `http://localhost:8888`

**Comment by xuyanMax** [comment]
Docker : docker run -it -p 8888:8888 image:version Container : jupyter notebook --ip 0.0.0.0 --no-browser 
Host : localhost:8888/tree‌​
