### ISSUE TITLE
Docker does not start: com.docker.supervisor failed to start

### ISSUE THREAD

**Issue by submediax** [docker/for-mac#3113]
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.6 (build: 17G65)
logs: /tmp/94425A8C-9ACA-4B14-9677-0A575C618247/20180724-075226.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Volumes/Data/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Volumes/Data/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Volumes/Data/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk
Diagnostic ID: 94425A8C-9ACA-4B14-9677-0A575C618247

**Comment by jonnyarnold** [comment]
I appreciate this isn't very helpful, but this issue resolved itself by starting Docker for Mac manually.

**Comment by adamkotecki** [comment]
I am not sure If I have the same issue - when I try to open my Docker.app on Mac my message is:
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 3417)
After pressing Diagnose and Feedback I see "Diagnosing..." but nothing changes after long time - only button Back and Exit are visible.
What can I do?

**Comment by artgoldberg** [comment]
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.6 (build: 17G65)
logs: /tmp/B33B66F4-22B1-430B-A0B7-E6E5375251EA/20181114-151828.tar.gz
failure: Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/arthur_at_sinai/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/arthur_at_sinai/Library/Containers/com.docker.docker/Data/s51
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/arthur_at_sinai/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/arthur_at_sinai/Library/Containers/com.docker.docker/Data/s51
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[ERROR]  logs
#ffb2b2#         logs check failed with: (Failure
  "exec: /usr/bin/log show --debug --info --style syslog --last \"1d\" --predicate \"process matches \\\".*(ocker|vpnkit).*\\\" || (process in {\\\"taskgated-helper\\\", \\\"launchservicesd\\\", \\\"kernel\\\"} && eventMessage contains[c] \\\"docker\\\")\" >\"/tmp/B33B66F4-22B1-430B-A0B7-E6E5375251EA/20181114-151828/docker-system-os.log\" 2>&1: exit 65")##
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/arthur_at_sinai/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

**Comment by artgoldberg** [comment]
The above error occurs after startup reports:

Fatal Error
com.docker.supervisor failed to start
Exit code 1

And click 'Diagnose & Feedback'.
Recommendations?

**Comment by artgoldberg** [comment]
Updating to Docker Community Edition 18.06.1-ce-mac73 2018-08-29 solves the problem.

**Comment by hktalent** [comment]
#3076

**Comment by gaofengz** [comment]
First  type ```sysctl -a | grep machdep.cpu.features```  to console then you will see 
```machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C```
if you can see VME,that means you have VT-X but not enabled,
then go to the bios, just enable the intel virtual technology, the problem solved for me

**Comment by dougbishop** [comment]
Having the same issue. @gaofengz please understand this is Docker for Mac, you dont need to enable anything in the bios for VT-X. I just updated to OS X 10.11.4 was working before the update, after the update no dice. I have removed docker completely as well as the lib folders and re-installed. Still doesn't work.

**Comment by gaofengz** [comment]
Yes, my OS X is 10.13.6, and my docker version is 18.09, and it worked when i enable the VT-X in the bios, before that `Fatal error: Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver` error occurred, maybe you can update the OS or docker, and have a try

**Comment by demonguru18** [comment]
The problem is caused because - In you Motherboards BIOS settings, you have Intel Virtualization Technology(VT-X) set as Disabled. Please set this option to Enabled and you will no longer see the Supervisor related error. Setting this to disabled, prevents VM's from using/sharing resources. **Basically, stops providing hardware assistance for processors running virtualization platforms.** If you have both the options VT-D and VT-X set both to Enabled. Im my Motherboard I set both to enabled. Hope this solves the problem, and you don't need to downgrade Docker.
