### ISSUE TITLE
stopped working, reports virtual box not installed

### ISSUE THREAD

**Issue by fighne** [docker/for-mac#3117]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
Please upload diagnostics and provide a diagnostic ID or we can't investigate the issue
