### ISSUE TITLE
553B94F9-15DA-495B-834C-570011DC3F47/20180727140516

### ISSUE THREAD

**Issue by nashCode** [docker/for-mac#3125]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
We need don't have enough information to investigate, so we are closing this. You can open a new issue with a fresh diagnostics ID detailing your problem, or try following the [troubleshooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
