### ISSUE TITLE
New d4m 18.06.0-ce-mac70 (26399) hangs

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#3127]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E75A2F4F-F2B0-4271-BAC5-0F025D1E3E20/20180727064753

### Expected behavior

My docker workload should run with the new docker like it did with 18.03.

### Actual behavior

Seems to hang, very slow, hoping there's some information or errors in the logs.

### Information
This environment (a compose file and some bash to initialize things) mostly worked in previous d4m assigned 4GB RAM + 1GB swap. Now it's hanging or very sluggish at best.

  - macOS Version: latest, 10.13.6

### Diagnostic logs

```
Docker for Mac: version...  18.06.0-ce-mac70 (26399)
Diagnose succeded```

### Steps to reproduce the behavior

Sorry no specific test, it's compose with several services. `docker exec` into one of them just hangs.

**Comment by pathornteng** [comment]
Got the same issue

**Comment by jmisur** [comment]
same issue here. completely blocked me from using docker on my mac.
