### ISSUE TITLE
Aiiiiiiiiiiiiiii :(

### ISSUE THREAD

**Issue by roussin** [docker/for-mac#3129]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CFAE7A92-B237-44B1-AA83-7E1732EDD7BA/20180728203542

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version... 18-06-0-ce-mac70 (26399)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
We need don't have enough information to investigate, so I'm closing this. You can open a new issue with a fresh diagnostics ID detailing your problem, or try following the [troubleshooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
