### ISSUE TITLE
Can I run multi containers on one server using --network=host mode?

### ISSUE THREAD

**Issue by Kisen-Chin** [docker/for-mac#3143]
Hi guys,
I'd like to ask just one question:  Can I run multi dockers which are all using "--network=host" mode on one server? As I know, if one docker using host mode, then it will the host server's network configuration. So if there are multi docker run on one server using host mode, will it be conflict on port or ip?
When I run cmd like this:
 docker run -d --name d1 --network=host -p 80:80 ca6
I got below warning:
WARNING: Published ports are discarded when using host network mode
So my confuse is, if I can't figure one port to this docker, how can my application connect to this docker using ip:port method? 
It seems like if I run docker using host mode, I can only run one docker on one server?

If the question is not clear, please ask me. Thanks!!

**Comment by ebriney** [comment]
Hi @Kisen-Chin -p is used to open/map a port in the host network from the container (it's like a proxy) so you don't need --network=host.
If you use --network=host, the process(es) in your container open port directly on host network so you cannot change the port number, it uses the one in the code.

**Comment by jxycbjhc** [comment]
thanks ,it saves me run elastalert in dockert success.

**Comment by maxkrylov** [comment]
Very thx, i too run elastalert in dockert success after this.
