### ISSUE TITLE
kubernetes never finishes 'starting'

### ISSUE THREAD

**Issue by kirbyclements** [docker/for-mac#3148]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  4C67AC08-5CC5-4055-A502-273269890D49/20180807162724

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by diamonddelt** [comment]
I ran into this before, and looked through a lot of the other related issues, but to no avail. I noticed the same behavior on Stable or Edge, and my Docker version was Version 18.06.0-ce-mac70 (26399).

The issue ended up being the fact that I had actually installed kubectl via homebrew and created a ~/.kube/config file manually, to connect to a remote kubernetes cluster.

When installing local kubernetes that comes with Docker in the latest versions, it automatically creates the ~/.kube/config file, and populates it with your `docker-for-desktop` context, along with client certificate and key data. 

My guess is, if you created that file by hand after manually installing kubectl through another means, the Docker+Kubernetes bundle install does not attempt to insert the `docker-for-desktop` context information into the existing file. You could verify you were in my situation if you saw `Kubernetes is starting...` which never went away, but on your terminal, you were able to interact with kubectl, and could still connect to whatever previous context you configured.

The solve was to simply move my old kubeconfig file to another location, stop Docker and restart it, and the installation finished with a minute (and wrote the kubeconfig file with the docker-for-desktop context, as expected). I then just needed to add my previous cluster context into that file.
