### ISSUE TITLE
Lost all data (volumes), containers and images

### ISSUE THREAD

**Issue by wassx** [docker/for-mac#3149]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
Docker Client crashed and mentioned to do a factory reset. Suddenly all data was gone.
There was no indicator, action which caused docker to crash.

  - macOS Version:
10.13.6 (17G65)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
@wassx sorry for that but if you do a factory reset it wiped the docker containers and images of course, because if there is a corruption in the files, it can prevent the app to start.
You can still provide a crashreport, so I can perhaps fix the initial error you got.
