### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by jpswade** [docker/for-mac#3151]
Enabling Kubernetes from command line should be an option

Adjusting the advanced settings, eg: CPU, memory, swap, etc...

**Comment by jpswade** [comment]
Revisiting this issue. I'd like to a way to "reset kubernetes cluster" from the command line.

**Comment by tellisnz** [comment]
until this exists, i'm getting by using scripts with something like the following:

```
osascript -e 'quit app "Docker"' &> /dev/null

sed -i.bak 's/"kubernetesEnabled" : false/"kubernetesEnabled" : true/g' ~/Library/Group\ Containers/group.com.docker/settings.json

osascript -e 'open app "Docker"' &> /dev/null
```
for the enable and the reverse sed for the disable.

seems to work ok.
