### ISSUE TITLE
How upgrade docker-compose (current version installed 1.22.0)

### ISSUE THREAD

**Issue by markitus83** [docker/for-mac#3156]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
Here is the project link: https://github.com/docker/compose
The documentation: https://docs.docker.com/compose

1.22.0 is the latest version, see https://github.com/docker/compose/releases
