### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by vasutha** [docker/for-mac#3158]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LoreenRH** [comment]
We need don't have enough information to investigate, so we're closing this. You can open a new issue with a fresh diagnostics ID detailing your problem, or try following the [troubleshooting guide for mac](https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshooting).
