### ISSUE TITLE
docker/mac: high cpu usage and unresponsive on wake

### ISSUE THREAD

**Issue by mhat** [docker/for-mac#316]
### Steps to reproduce

1. Have Docker running along with some container.
2. Close Laptop.
3. Go Home or Go to the Office.
4. Open Laptop.
5. Watch com.docker.hyperkit consume a majority of CPU until it's killed/restarted.

This has been going on since the private-beta. I assume it's not all that common or y'all would have fixed it by now. One possibility is that it's related to openvpn and having a active/open connection before closing the laptop. Then post-commute, on wake, the laptop is on a new network, openvpn shuts down the connection, etc.

It happens about twice a day. I'll update the issue tomorrow after I try to isolate if having the vpn up is really a factor or not. 

### Expected behavior

That com.docker.hyperkit doesn't consume all CPU when the laptop wakes up.

### Actual behavior

com.docker.hyperkit consumes a majority of CPU until it is killed/restarted. 

### Information

```
Diagnostic ID: FB4CED9F-EB70-4E7C-81DE-6C1C5302EFDE
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[OK]     disk
[OK]     system
[OK]     virtualization
[OK]     osxfs
[OK]     menubar
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mhat** [comment]
<img width="797" alt="screen shot 2016-08-16 at 8 06 18 pm" src="https://cloud.githubusercontent.com/assets/973/17723420/da9c0418-63ee-11e6-99b0-e9d6c8e47d78.png">

**Comment by mhat** [comment]
It seems to at least casually correlate to when I: have a vpn connection, close my laptop, and then hours later open my laptop in a new location on a new network with a different address range. E.g. commuting from home to the office and vice versa. 

Also, I'm now running Version 1.12.1-rc1-beta23 (build: 11375)
2f0427ac7d4d47c705934ae141c3a248ed7fff40.

**Comment by s2ugimot** [comment]
Hi I'm also facing the exact same problem and looking for a solution.
Tentatively going back to use docker-machine w/VirtualBox.

Version 1.12.0-a (build: 11213)
ad6ab836187e4111082447b7c0a6a74d01929a5c

**Comment by mchiang0610** [comment]
Merging with #82
