### ISSUE TITLE
Fatal error after update docker on Mac Os Sierra Public Beta 5

### ISSUE THREAD

**Issue by andmetoo** [docker/for-mac#317]
### Steps to reproduce

1. start docker 
2. update
3. diagnose

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 6B1ABC66-FAF4-4767-871B-1309982236F4
Docker for Mac: 1.12.0-beta22 (Build 11222)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         docker ps failed
[OK]     dns
[OK]     moby-syslog
[OK]     app
[ERROR]  disk
         Docker.qcow2 is corrupt: reset to factory defaults is required
[OK]     system
[OK]     virtualization
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     menubar
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/metoo/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/metoo/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     moby-console
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by kwojtaszek** [comment]
related to #64

**Comment by andmetoo** [comment]
`sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist`
thnx this work for me

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
