### ISSUE TITLE
docker unable to start

### ISSUE THREAD

**Issue by sexyhamster** [docker/for-mac#3170]
- [x] I have tried with the latest version of my channel (Stable or Edge) (and it freezes, even diagnostics could not run)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 768C42BA-6C18-4670-9E69-912A395F4EBD

### Expected behavior
start docker
### Actual behavior
docker unable to start, hyperkit consumed 1 cpu, nothing in console with "docker filter"

was running latest version, but ran into the same problem listed in several different issues about 
UEFI ("this selection take you to the Boot Manager")
### Information

  - macOS Version: High Siera 10.13.6 (17G65)

### Diagnostic logs

```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.6 (build: 17G65)
logs: /tmp/768C42BA-6C18-4670-9E69-912A395F4EBD/20180820-153553.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sexyhamster** [comment]
well, after a couple of restarts docker started, hope diagnostics will help to resolve issue in future, but i'll stay on this version for a while :)

**Comment by andreamaruccia** [comment]
I have the same issue on stable and edge, what did you do to fix it? How many restarts did you do?
