### ISSUE TITLE
Lost all Images and Containers after update

### ISSUE THREAD

**Issue by vspl-girish** [docker/for-mac#3172]
- [ x] I have tried with the latest version of my channel (Stable)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 6C246543-F199-4635-835A-CEB087536E62/20180821013437

### Expected behavior
Retain the existing images/containers

### Actual behavior
Lost all existing images and containers

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version...

`Version 18.06.0-ce-mac70 (26399)``

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
-->

  1. Update Docker
  2. ...

**Comment by AlexDag** [comment]
Good job!  I have the same movie > OSX, updating Docker to  18.09.0 and lost ALL my images...
