### ISSUE TITLE
Storage driver issue for docker version 18.06

### ISSUE THREAD

**Issue by krinjalpatel** [docker/for-mac#3175]
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/b2078c0d51f36f4e3276948b5ae44c30c87b3b5e3982608f7f84f462a19f7cfb/merged: no such file or directory

  - [Yes ] I have tried with the latest version of my channel (Stable or Edge)
Docker version - 18.06.0-ce, build 0ffa825
Mac version - macOS High Sierra Version 10.13.6 (17G65)

It is working with docker version 10.03

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
Hi @krinjalpatel. Can you send diagnostic?
