### ISSUE TITLE
docker-machine ip issue

### ISSUE THREAD

**Issue by code7885** [docker/for-mac#3178]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by code7885** [comment]
->docker-machine ip
Error: No machine name(s) specified and no "default" machine exists

->docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

->docker-machine ip default 
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

->docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                  NAMES
03b2b7804f32        ubuntu:14.04        "bash"              25 minutes ago      Up 25 minutes       0.0.0.0:45678-45679->45678-45679/tcp   echo-server

->docker -v
Docker version 18.06.0-ce, build 0ffa825

**Comment by code7885** [comment]
->docker-machine create default
Running pre-create checks...
Error with pre-create check: "exit status 126"

**Comment by guillaumerose** [comment]
This repository is about Docker Desktop, not docker-machine. Please take a look at https://github.com/docker/machine
