### ISSUE TITLE
Typo on El Capitan deprecation notice

### ISSUE THREAD

**Issue by raphaelyancey** [docker/for-mac#3181]
Not very important but still...

<img width="610" alt="capture d ecran 2018-08-27 a 10 39 17" src="https://user-images.githubusercontent.com/5130438/44650667-8b099280-a9e7-11e8-8185-bc1876c6276b.png">

It's *El Capitan*, not *El Captain* :)

**Comment by mat007** [comment]
@raphaelyancey thank you for the issue, this has now be fixed in the upcoming versions!
