### ISSUE TITLE
Include out-of-tree kernel modules in Docker for Mac

### ISSUE THREAD

**Issue by drajen** [docker/for-mac#3189]
I've written a Docker Volume plugin for OpenZFS. I have a legacy and V2 version locked and loaded. Ideally I want Docker for Mac users to be able to use this plugin natively with Docker for Mac without resorting to Docker Machine.

I'm merely looking at pointers at this time to try understand how others have solved similar problems. Is it possible to ship a LinuxKit compatible kernel module with my plugin and load it in the host OS with the right privileges set on the container using the entrypoint script to figure it out?

Since OpenZFS is riddled with FUD re: licensing and its absence in the Linux kernel upstream, I'm assuming this won't be easy.

**Comment by justincormack** [comment]
Edge now ships with a LinuxKit kernel, the kernel modules from the zfs linuxkit build should work. Stable will move to this in future.
