### ISSUE TITLE
Cannot upgrade Docker for Mac to 18.06.1

### ISSUE THREAD

**Issue by mresnickmdlive** [docker/for-mac#3190]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B9B0DBC0-056D-4821-9A15-0676ABED5195/20180830135738

### Expected behavior
I am able to update Docker for Mac to the latest stable version.
### Actual behavior
Docker for Mac client downloads the update successfully, but can't extract the archive. "An error occurred while extracting the archive. Please try again later."
<img width="1440" alt="extract_archive_error" src="https://user-images.githubusercontent.com/19688726/44857718-61967400-ac3e-11e8-9394-a14368bd0f6b.png">

### Information

  - macOS Version: Sierra, 10.12.6

### Diagnostic logs

The GUI doesn't return any of the typical diagnostic information, it just says "diagnose succeded[sic]".

### Steps to reproduce the behavior

  1. From the Docker for Mac main menu, click "Check for Updates"
  2. Click "Install Update"

**Comment by andtrobs** [comment]
Hi did you ever resolve this? I am experiencing the same. Thanks

**Comment by somahargitai** [comment]
Still have the same error

**Comment by mresnickmdlive** [comment]
@andtrobs @somahargitai I found out that in my case, this issue was caused by the company I work for applying a security policy to my Mac that prevents .dmg files from being extracted. Maybe check if any similar security policy has been applied to your machines.

**Comment by itsthomas** [comment]
Download Docker manually via browser and install it over your old Docker.
