### ISSUE TITLE
"Kubernetes is starting..." indefinitely

### ISSUE THREAD

**Issue by ebelisle** [docker/for-mac#3193]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 764BCE7A-3465-478C-AD68-9E0FE7930E47/20180902132223

### Expected behavior
Kubernets starts

### Actual behavior
"Kubernetes is starting..." indefinitely (10+ hours)

### Information
I was able to successfuly start Kubernetes on 2012 Macbook Pro.
Migrated machine to new 2018 Macbook Pro.
Kubernetes never finishes starting. (reasonable, migrations are hard to support)
Delete Docker.app, ~/.kube, ~/.docker
Reinstall Docker.
Turn on Kubernetes, switch orchestration to kubernetes
Kubernetes never finishes starting
 

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

Diagnose succeded
```

### Steps to reproduce the behavior

2. Deleted Docker.app, ~/.docker ~/.kube
3. Downloaded and reinstalled Docker
4. Turn on Kubernetes, switch orchestration to kubernetes
5. Kubernetes never starts

**Comment by ebelisle** [comment]
After looking at other similar issues, my migration may be unrelated to this issue.

**Comment by ebelisle** [comment]
Resolved:  Restored /etc/hosts from backup.

After migratating my laptop to a my new machine, my /etc/hosts was empty (wtf apple?).  Restored /etc/hosts from hosts~orig (thanks apple?) and docker for mac was able to start kubernetes.

Thanks to https://github.com/docker/for-mac/issues/2331#issuecomment-357519513 for the idea.

**Comment by scottming** [comment]
I have the same problem.

### system
* macOS: version: 10.14.6
* docker version: 2.2.1.0(42746)
* engine: 19.03.5
* kubernetes: v1.15.5

### images:

```
➜  ~ docker images


REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-apiserver            v1.15.5             e534b1952a0d        4 months ago        207MB
k8s.gcr.io/kube-controller-manager   v1.15.5             1399a72fa1a9        4 months ago        159MB
k8s.gcr.io/kube-proxy                v1.15.5             cbd7f21fec99        4 months ago        82.4MB
k8s.gcr.io/kube-scheduler            v1.15.5             fab2dded59dd        4 months ago        81.1MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        13 months ago       40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        15 months ago       258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        2 years ago         742kB
```
