### ISSUE TITLE
com.docker.osfx does not cleanup file descriptors

### ISSUE THREAD

**Issue by matslil** [docker/for-mac#3198]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 11C0A2D3-FF1B-43D2-8A73-A9686AC3216C/20180903142900

### Expected behavior

Be able to successfully execute a bitbake build (Yocto Project).

### Actual behavior

After a while, I get "[Errno 24] Too many open files". This problem persists until restarting the daemon.

### Information

  - macOS Version: 10.13.5 (17F77)

  - Is it reproducible? Yes
  - Is the problem new? Yes, but I'm also new with Docker for Mac.
  - Did the problem appear with an update? Not sure, I recently got an update but also did some changes.

I use Activity Monitor, and looks at tab "Open Files and Ports" for com.docker.osxfs process, and I have around 9000 entries similar to the following one:
"
197
->(none)
"

They are not removed by "docker rm -f <container>".

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Create a Dockerfile with "FROM crops/yocto:ubuntu-16.04-base". Add support for git.
  2. Open Disk Utility, create a new APFS volume (case-sensitive) sharing space with the main disk.
  3. Start container, sharing a directory on this new APFS volume.
  4. git clone https://git.yoctoproject.org/git/poky
  5. cd poky
  6. . ./oe-init-build-env
  7. bitbake core-image-sato

**Comment by matslil** [comment]
When running "docker info" I noticed I was using aufs. I changed to "overlay2", and also added "cached" to the bind mount. This did not change the behavior.

Note that the files not being closed is not immediately visible. It take a fair number of compiled packages to start occurring.

**Comment by fbucek** [comment]
I have exactly same results with  `gitlab/gitlab-ce` images

```
PID=`pgrep com.docker.osxfs`
echo "PID: $PID"
lsof -n -p $PID | wc
```

Number of opened files for this process is growing and growing up to 10240 and then `postgresql` starts to complain about `too many open files`
