### ISSUE TITLE
MacOS High Sierra - Docker allways crash at start up

### ISSUE THREAD

**Issue by LexBel-co** [docker/for-mac#3199]
The last versión of Docker for Mac is terrible, bassically i can not use it, i simply downloaded and installed, but Docker allways crash at start up, i have a MacOS High Sierra version 10.13.5, and this is the diagnostic ID: 047BAFAA-11A7-478D-BF0E-35A81D24AEEE/20180904123213 - I have a couple of months whit this trouble

**Comment by kg-ops** [comment]
Have the same issue on MacOS High Sierra version 10.13.6 and Version 18.06.1-ce-mac73 (26764)
Here is the docker diagnostic ID : `DAA64140-853D-4EFB-815A-3769CEAE383D/20180904220810`

**Comment by perryh** [comment]
Docker is crashing for me as well. It's crashing before I am even able to get a diagnostic id.
