### ISSUE TITLE
Bonjour/Avahi lookup does not work inside container

### ISSUE THREAD

**Issue by StefanScherer** [docker/for-mac#32]
### Expected behavior

```
$ ping -c 1 test.local
$ docker run -t alpine ping -c 1 test.local
```

Both commands should be able to ping the other device in local network.
### Actual behavior

```
$ ping -c 1 test.local
PING test.local (192.168.X.XXX): 56 data bytes
64 bytes from 192.168.X.XXX: icmp_seq=0 ttl=64 time=3.543 ms

--- test.local ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 3.543/3.543/3.543/0.000 ms

$ docker run -t alpine ping -c 1 test.local
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
e110a4a17941: Pull complete 
Digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a
Status: Downloaded newer image for alpine:latest
ping: bad address 'test.local'
```
### Information

Diagnostic ID: 5CEA5887-9236-445B-82C2-9A202A9DA0AA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Have a device running with avahi in your local network, eg. a Raspberry Pi with either Raspbian or HypriotOS
2. ping the device `test` with `ping test.local`
3. run the ping inside a container

```
$ docker run -t alpine ping -c 1 test.local
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
e110a4a17941: Pull complete 
Digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a
Status: Downloaded newer image for alpine:latest
ping: bad address 'test.local'
```

Yesterday I switch from a vmwarefusion docker machine to Docker for Mac and now this 😢 -- no problem 😆 Just starting to give feedback.

I just recreated a docker machine and tested if it worked previously. And yes using the name announced by avahi also works inside a container.

```
$ docker-machine create -d vmwarefusion --vmwarefusion-memory-size 2048 dev
$ eval $(docker-machine env dev)
$ docker run -t alpine ping -c 1 test.local
PING test.local (192.168.X.XXX): 56 data bytes
64 bytes from 192.168.X.XXX: seq=0 ttl=127 time=1.978 ms

--- test.local ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.978/1.978/1.978 ms
```

**Comment by djs55** [comment]
Thanks for the report!

Unfortunately we've not currently got support for IP multicast in the networking subsystem :( Depending on your use-case you might be able to workaround it by adding new entries to `/etc/hosts` on the Mac in beta 25 and later-- I'm sorry that's a bit ugly.

**Comment by dersimn** [comment]
> Yesterday I switch from a vmwarefusion docker machine to Docker for Mac

What type of (virtual) network adapter did you use for this VMware machine?

**Comment by StefanScherer** [comment]
Just the default. I can reproduce it with `docker-machine create -d vmwarefusion default`, then `eval $(docker-machine env default)` and finally `docker run -it alpine ping test.local` and it works.
The VMware VM uses the vmnet8 network.

**Comment by StefanScherer** [comment]
Seems to work with Docker for Mac 17.12.0-ce-mac55.
