### ISSUE TITLE
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died

### ISSUE THREAD

**Issue by loretoparisi** [docker/for-mac#3202]
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 1111)

  - [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died
<img width="627" alt="schermata 2018-09-05 alle 12 52 20" src="https://user-images.githubusercontent.com/163333/45088895-b6d4f880-b10a-11e8-91ea-d9e1ffdd4b73.png">

and Diagnosis fails (it stucks)

<img width="738" alt="schermata 2018-09-05 alle 12 52 15" src="https://user-images.githubusercontent.com/163333/45088918-c6544180-b10a-11e8-88cd-eda4f4654231.png">

### Information

  - macOS Version:
Version 18.06.1-ce-mac73 (26764)

### Diagnostic logs
Diagnostic hangs, no output - see above please.
Docker for Mac: Version 18.06.1-ce-mac73 (26764)

```

### Steps to reproduce the behavior
After this bug, try to generate diagnostic

**Comment by rodolfobubb** [comment]
+1, after energy down

**Comment by Sporky023** [comment]
@rodolfobubb  

> after energy down  

Do you mean this happens after the computer has slept?  Or after the computer's battery has been low?  Or do you mean something else?

**Comment by rodolfobubb** [comment]
@Sporky023 

> Do you mean this happens after the computer has slept? Or after the computer's battery has been low? Or do you mean something else?
I'm using an Imac, this error occured when started to rain and the power was out (blackout). 
Then, i turned on the computer and needed to reset docker to default (lost all mysql database).

**Comment by Sporky023** [comment]
I've added my +1 to your after energy down comment.  In my case it was after my laptops battery had drained and I had to charge it to start it up again.  I don't believe it did an actual boot sequence, but rather recovered from a very low battery state (somewhere between normal open-list wakeup and full system boot).

**Comment by JoeCotellese** [comment]
I'm having this same problem but it's on a desktop machine that doesn't sleep.

**Comment by hktalent** [comment]
me too,+1

**Comment by uterator** [comment]
The same issue, not a laptop. I have installed docker from scratch and can't get it working. It's just blocking me.
MacOS: 13.6

**Comment by edgarvonk** [comment]
Seems the same issue as: https://github.com/docker/for-mac/issues/3076 ?

**Comment by brampat** [comment]
+1 Fresh install using "brew cask install docker"

**Comment by freerobby** [comment]
I've hit this issue about a dozen times tonight. I'm on a laptop, but it's not low on power. I too tried doing diagnostics but it just hangs. I'm on the stable branch.

I installed Mac OS security update 2018-002 this morning and had not seen this issue prior to that update.

**Comment by kofronpi** [comment]
Same here on a fresh install of Docker CE on a macbook air - macOS mojave 10.14

**Comment by abdennour** [comment]
Same here after migrating from a MacBook pro to another MacBook. Both Macbook have the same criteria: MacBook Pro 2018, 2.6 GHz Intel Core i7, 16 GB 2400 MHz DDR4.

 I migrated everything (home directory, network setting, Application) except  "Other files".
I have now a doubt in the missing of "Other files" during the migration.

**Comment by roshsingh** [comment]
Same. Occurs when starting docker after the machine wakes up from sleep.

**Comment by hktalent** [comment]
ong long ago
the same........
same........same........same........same........same........same........same........
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.osxfs (pid: 3128)

**Comment by demonguru18** [comment]
The problem is caused because - In you Motherboards BIOS settings, you have **Intel Virtualization Technology(VT-X)** or set as Disabled. Please set this option to Enabled and you will no longer see the Supervisor related error. Setting this to disabled, prevents VM's from using/sharing resources. Basically, stops providing hardware assistance for processors running virtualization platforms. If you both the options **VT-D** and **VT-X** set both to Enabled. Im my Motherboard I set both to enabled. Hope this solves the problem, and you don't need to downgrade Docker.

**Comment by Paul-Wasilewski** [comment]
I have managed to solve the problem on OS X (Version 2.0.0.0-mac81) by removing all (my customs) Paths under File Sharing. I have a strong suggestion that it might be a problem when docker.sock is shared between the containers.

**Comment by wajiii** [comment]
I frequently get this when I first start my computer for the day. I typically shut it down every night, to get a fresh start every day, and often Docker gives me errors when I first log in. I have not been keeping close track of the error messages, but I am pretty sure I hsve seen this one before; today, it was:
> Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 959)

I try to have it run diagnostics each time, but it has only given results once or twice. I am usually in too''' much of a hurry to get started working to deal with it at the time, so I tell it to reset to defaults, and move on. Afterward, I have to recreate my containers, but we have build scripts to handle that, so it is really just a minor inconvenience...

**Comment by snoblenet** [comment]
Unfortunately, `brew cask install docker` did not fix it for me.

**Comment by demonguru18** [comment]
> Unfortunately, `brew cask install docker` did not fix it for me.

Did you try this - The problem is caused because - In your Motherboards BIOS settings, you have Intel Virtualization Technology(VT-X) set as Disabled. Please set this option to Enabled and you will no longer see the Supervisor related error.

**Comment by snoblenet** [comment]
@demonguru18 My understanding is that on Macs with that chipset, VT-X is enabled by default. But I also checked manually and it is enabled on my system.

**Comment by demonguru18** [comment]
> @demonguru18 My understanding is that on Macs with that chipset, VT-X is enabled by default. But I also checked manually and it is enabled on my system.

Actually, for me I have Hackintosh - Therefore I had to set two options  VT-D and VT-X  both to Enabled.(I have both these options on Asus Mobo)
I am not sure if you have VT-D enabled on real mac

**Comment by luckydonald** [comment]
I now have the same issue after upgrading from `2.0.0.2` -> `2.0.0.3` via the updater.

**Comment by loretoparisi** [comment]
I confirm that this issue is still there and that rebooting will fix it.

**Comment by mark-schulze** [comment]
> The problem is caused because - In your Motherboards BIOS settings, you have **Intel Virtualization Technology(VT-X)** set as Disabled. Please set this option to Enabled and you will no longer see the Supervisor related error. Setting this to disabled, prevents VM's from using/sharing resources. Basically, stops providing hardware assistance for processors running virtualization platforms. If you have both the options **VT-D** and **VT-X** set both to Enabled. Im my Motherboard I set both to enabled. Hope this solves the problem, and you don't need to downgrade Docker.

this solved it for me as well on a hackintosh.

**Comment by glc650** [comment]
Having this same issue on a 2018 Mac Mini with macOS 10.14.5 and Docker for Mac stable 2.0.0.3 (31259).  Purchased Mini in May and setup Docker right away but didn't have this issue until about 3 weeks ago.
