### ISSUE TITLE
Docker crash in High Sierra 10.13.6

### ISSUE THREAD

**Issue by Grhosso** [docker/for-mac#3207]
- I have downloaded the last version available in the website (Stable) then I tried the Edge. Both with same result.
  - Diagnostics ID: ??
  - macOS Version: 10.13.6
- After enter password for giving privileges, I get the message: "Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 3259)"

### Diagnostic logs
```
Diagnosing is not working, I do not get any log after a while... the app is frozen.

```

**Comment by yunake** [comment]
i'm seeing the same thing on Sierra 10.12.6

**Comment by yunake** [comment]
this is on b0f14f1dac, Version 18.06.1-ce-mac73 (26764) stable
