### ISSUE TITLE
Docker daemon occassionally unresponsive since updating docker

### ISSUE THREAD

**Issue by spectorar** [docker/for-mac#3208]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B3B68737-A20C-4886-B3F4-876FA1625C18/20180907050927

### Expected behavior

docker daemon should be responsive

### Actual behavior

docker daemon is unresponsive 

### Information
 
Running macOS `10.13.5 (17F77)`. 
Recently I have experienced docker just hanging when trying to run docker commands. Even something as simple as `docker ps -a`. Once it happens, all docker commands will hang, so it seems to be an issue with the daemon. It happened just now and I noticed that docker's CPU usage was quite high. Restarting docker fixes the problem. If I let the commands hang long enough I have seen them eventually complete. 

This seems to have started after I most recently updated docker for mac. Unfortunately I couldn't say for sure if I was on the next most recent version before upgrading.

I am typically running about 12 containers in this setup. Docker is limited to 4 CPUs and 4GB of memory with 1GB swap. Unfortunately I cannot give you more specific steps to reproduce the behavior. It doesn't seem to be trigger by a specific set of steps.

### Diagnostic logs
"Diagnose succeded" was the only output I received. Diagnostics were uploaded though.
```
Docker for Mac: version...
Version 18.06.1-ce-mac74 (26766)
```

**Comment by ebakke** [comment]
I'm experiencing the same with `18.06.0-ce-mac73`
![image](https://user-images.githubusercontent.com/383025/45459581-68dd6900-b6a5-11e8-8d52-4af6d94221e5.png)

Everything runs well for a while, and then *bam* CPU jumps and everything becomes unresponsive. Takes 5+ minutes for `docker stats` to return *anything* and when starts showing something, it's incomplete. `docker ps` takes several minutes to return.

Eventually (30-60 minutes, if left) it will clear out, the CPU will drop and things will return to normal. This was not the case for me on `18.06.0-ce-mac70`. A restart also brings me back to a functional state.

**Comment by spectorar** [comment]
Just to add, my coworker is experiencing this as well and he is on the stable release.
<img width="591" alt="screen shot 2018-09-13 at 2 17 27 pm" src="https://user-images.githubusercontent.com/5466857/45507375-f3829e80-b75f-11e8-80b5-67c036dcce23.png">
