### ISSUE TITLE
Kernel panic when using docker for mac

### ISSUE THREAD

**Issue by sandersonb** [docker/for-mac#3213]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1FF29D3B-D981-4E50-9D54-76442C001C9D/20180908044109

### Expected behavior
No kernel panic occurs when running a docker container.

### Actual behavior
My 2018 MBP experiences a kernel panic a variable amount of time after launching any container. 

### Information
When I run ANY docker container, a random amount of time later from 0 seconds - 3 minutes my system locks up, then restarts with a kernel panic. E.g I run:

`docker run -it rabbitmq:3.7-management`

I have tried it with at least 5 other public containers, each of which give the same behavior. The machine never locks up when JUST the hypervisor/VM is running; it is only after a container is run that it actually kernel panics.

The OSX kernel panic log starts with: 
```
{"caused_by":"macos","macos_system_state":"running","bug_type":"210","os_version":"Bridge OS 2.4.1 (15P6805)","timestamp":"2018-08-29 06:19:35.51 +0000","incident_id":"6F71E0EB-E950-49EA-9A92-C0E1BF15A8D5"}
```

My computer does not panic at any other time, such as a system sleep (which was infamously responsible for many kernel panics for 2018 MBP users). It is ONLY when I run docker that it kernel panics. And it ALWAYS happens when I do.

I have a 2018 MBP 15", i7, 32 GB RAM, running the latest Apple software available today (10.13.6 Supplemental Update 2). It is reproducible every time. 

Here's what I've done so far to try and drill in to the problem:

- I've tried the same command on various other 2018 MBPs (16 GB RAM) and I see no problems. Docker works flawlessly on my 2015 MBP.
- I have a ticket open with Apple. I passed on many logs including a screen capture of the panic, talked to many people. but nothing substantial has come of it yet.
- I've reformatted the machine to stock High Sierra, did nothing but download docker and run the provided command, and it still reproduced.
- The machine is new enough that I only ever tried it with MacOS 10.13.6, Supplemental 1 & 2. It did not seem to show up with a particular version of Mac OSX or Docker.
- I have turned Docker's "Experimental features" off and it seems to have no effect.
- I have connected to the Docker for Mac VM and tailed all available logs before the system freezes & after. There is nothing in those logs that indicates a failure right before the freeze, nor when the system comes back up.
- I have tried resetting, uninstalling/reinstalling Docker multiple times. Always the same result.
- It feels like an issue particular to my machine, but then again ... why only with docker?

### Diagnostic logs
All mine says is "Diagnose succeded" (typo BTW :) ) with no other output. I've uploaded the diagnostic data above. I am running:

Version 18.06.1-ce-mac73 (26764)
stable
b0f14f1dac

### Steps to reproduce the behavior
Run any container, e.g:

`docker run -it rabbitmq:3.7-management`

and wait between 0 seconds and 3 minutes.

I appreciate any guidance you can give me.

**Comment by sandersonb** [comment]
FWIW, I also tried on edge just now, same command, with exactly the same symptom. 

Diagnose ID: 1FF29D3B-D981-4E50-9D54-76442C001C9D/20180908055045

Version: 18.06.1-ce-mac74 (26766)

**Comment by sandersonb** [comment]
I got a replacement machine (same specs) and the problem is gone. Must have been a hardware issue.

**Comment by araujoantonio** [comment]
Same problem here 2019 MacBook Pro. Apple support is being super sluggish and unhelpful.
