### ISSUE TITLE
Docker upgrade failed on MacOS 10.12beta

### ISSUE THREAD

**Issue by d00rgaan** [docker/for-mac#322]
### Steps to reproduce

1. I used docker on my MacBook Pro 13 inch Retina on OSX

2. Started using a Mac OS Sierra 10.12 public beta

3. Docker upgrade failed

issue id:D559DD78-362A-46B2-B651-C57494F40645
Docker for Mac: version: 2f0427a
OS X: version 10.12 (build: 16A294a)
logs: /tmp/D559DD78-362A-46B2-B651-C57494F40645/20160817-141113.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Jeroen/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/Jeroen/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/Jeroen/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running

### Expected behavior

Well I would expect that after installing the upgrade I would be able to open docker again. ;-)

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: D559DD78-362A-46B2-B651-C57494F40645
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
```

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
