### ISSUE TITLE
Include linuxkit-aufs kernel headers in docker for mac distro

### ISSUE THREAD

**Issue by tekumara** [docker/for-mac#3223]
bcc requires kernel headers to run, but these don't appear to be shipped in the docker for mac distro, which is based on linuxkit but uses a custom kernel to enable AUFS. See https://github.com/iovisor/bcc/issues/1972

Can `/lib/modules/X.X.XX-linuxkit-aufs/` and `/usr/src/linux-headers-X.X.XX-linuxkit-aufs` be added to the distro? Or otherwise made available?

**Comment by justincormack** [comment]
The Edge version of Docker for Mac no longer has aufs support, it uses the LinuxKit kernel directly.

Stable will do, but yes should make these available cc @djs55

**Comment by tekumara** [comment]
/remove-lifecycle stale

Hiya, I'm now testing this with the latest stable version 2.1.0.5 (40693) and not seeing the kernel headers:
```
/ # ls -al /lib/modules/4.9.184-linuxkit/build
lrwxrwxrwx    1 root     root            39 Jul  2 22:59 /lib/modules/4.9.184-linuxkit/build -> /usr/src/linux-headers-4.9.184-linuxkit
/ # ls -al /usr/src
ls: /usr/src: No such file or directory
```
