### ISSUE TITLE
Docker cli unresponsive

### ISSUE THREAD

**Issue by ab9-er** [docker/for-mac#323]
### Expected behavior
`docker ps` to work

### Actual behavior
`Error response from daemon: Bad response from Docker engine`

### Information

Diagnostic ID: B3806294-C49C-4396-8DF1-B189C4880215
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Open Terminal
2. docker ps

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in B3806294-C49C-4396-8DF1-B189C4880215/20160817-144227.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Aug 10 10:13:44 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Notice>: Asking com.docker.hyperkit to thaw vcpus
Aug 10 10:13:44 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Notice>: vcpu 0 received signal, resuming
Aug 10 10:13:44 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Notice>: vcpu 1 received signal, resuming
Aug 10 10:13:45 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Error>: VM: 2016-08-09 18:36:18 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 10 10:13:45 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Error>: VM: 2016-08-09 18:36:18 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 10 10:13:45 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Error>: VM: 2016-08-09 18:36:18 +0000 UTC kern.error kernel: 	0-...: (1 GPs behind) idle=065/140000000000001/0 softirq=4378355/4378355 fqs=0
Aug 10 10:13:45 Nebuchadnezzar Docker[com.docker.driver.amd64-linux][77205] <Error>: VM: 2016-08-09 18:36:18 +0000 UTC kern.error kernel: 	1-...: (1 ticks this GP) idle=487/1/0 softirq=5016648/5016648 fqs=0
```
