### ISSUE TITLE
docker-diagnostic missing from docker 18.06.1-ce-mac73 (26764)

### ISSUE THREAD

**Issue by godbout** [docker/for-mac#3235]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 05B10A14-5C3D-4FF4-977E-31F3388CF00E/20180926150852

### Expected behavior

Diagnosing gives me a nice list, and a beautiful docker-diagnose is present.

### Actual behavior

No docker-diagnose executable. Can't diagnose.

### Information
  - macOS Version: 10.14 (18A391)

Actually I was coming here because I've been fighting for 2 full days with docker containers and my host VPN. The docker containers for whatever reason can't connect to my external services through the VPN (using IPs) while they can connect to the rest of the internet. When I decided to fill an issue, I realize that the docker-diagnose was missing.

I've uninstalled Docker fully, reinstalled, redownloaded and rebuilt all the images and container. Same thing (for the missing docker-diagnose. VPN might be solved, not sure yet.)

### Diagnostic logs

That's the whole point! No log.

```
Docker for Mac: Version 18.06.1-ce-mac73 (26764)

```

### Steps to reproduce the behavior

  1. On macOS Mojave, install Docker for Mac Version 18.06.1-ce-mac73 (26764). Look for docker-diagnose until infinity.

**Comment by godbout** [comment]
Nice pics to show I'm not a liar.

<img width="615" alt="screenshot 2018-09-26 at 23 06 52" src="https://user-images.githubusercontent.com/121373/46090814-10998180-c1e4-11e8-8380-350267d5e312.png">
<img width="788" alt="screenshot 2018-09-26 at 23 04 53" src="https://user-images.githubusercontent.com/121373/46090818-13947200-c1e4-11e8-9707-5541e29602f1.png">

**Comment by yunti** [comment]
I get a similar issue as posted in #3239 however nothing opens up when I click on the docker app icon, so this may not be exactly the same. (docker version and os version are the same as in this issue)
