### ISSUE TITLE
Docker fails to start after every reboot on Mojave; cannot install symlinks in /usr/local/bin (stage 4)

### ISSUE THREAD

**Issue by beaugunderson** [docker/for-mac#3236]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9D8C9FB0-9CAC-4054-9C6E-5350EC7DEE40/20180926154625

### Expected behavior

Docker can start after I reboot my macOS Mojave laptop.

### Actual behavior

I get this error on startup:

```
cannot install symlinks in /usr/local/bin (stage 4)
```

If I manually remove these symlinks Docker will create them and can start again without issue:

```
 ◼ theodore/beau home .../local/bin ls -al | grep Docker.app
lrwxr-xr-x    1 beau staff   54 09/25/18 12:04:01 PM  docker -> /Applications/Docker.app/Contents/Resources/bin/docker*
lrwxr-xr-x    1 beau staff   62 09/25/18 12:04:01 PM  docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose*
lrwxr-xr-x    1 beau staff   77 09/25/18 12:04:01 PM  docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain*
lrwxr-xr-x    1 beau staff   62 09/25/18 12:04:01 PM  docker-machine -> /Applications/Docker.app/Contents/Resources/bin/docker-machine*
lrwxr-xr-x    1 beau staff   67 09/25/18 12:04:01 PM  hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit*
lrwxr-xr-x    1 beau staff   54 09/25/18 12:04:01 PM  notary -> /Applications/Docker.app/Contents/Resources/bin/notary*
lrwxr-xr-x    1 beau staff   65 09/25/18 12:04:01 PM  vpnkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit*
```

This fixes the issue until the next reboot:

```
 ◼ theodore/beau home .../local/bin rm docker docker-compose docker-credential-osxkeychain docker-machine hyperkit notary vpnkit
```

### Information

  - problem appeared after upgrading to Mojave
  - happens on every reboot
  - I do have homebrew installed 
  - macOS Version: 10.14 (18A391)

### Diagnostic logs

(diagnostics ID included above)

### Steps to reproduce the behavior

  1. reboot computer
  2. start docker

**Comment by Rockncoder** [comment]
I am seeing the same issue. It began after the upgrade to Mojave.

**Comment by beaugunderson** [comment]
One update: I turned off "Start Docker when you log in" so that I could open Console.app and see if there were related log messages. I then restarted the computer and launched Docker, and for the first time it worked! So if you're trying to reproduce this (or narrow it down) it may only manifest itself when "Start Docker when you log in" is checked.

**Comment by eSeal44** [comment]
I turned off "Start Docker when you log in" while "Docker is starting" and it really starts working =)

**Comment by mkxml** [comment]
I'm having this issue too. Docker `18.06.1-ce-mac73 (26764)`

**Comment by iAmcR** [comment]
It seems the latest versions of Docker require Docker ID and Password to sign in along with Mac OS Mojave needing to give it privileges again. After resetting to defaults and giving the OS privileges, docker worked again.

**Comment by jsrice7391** [comment]
I used the method that @beaugunderson suggested and it worked for me. I did not have to do anything with Apple Keychain.

**Comment by marcosrocha85** [comment]
Confirmed on High Sierra 10.13.6 as well.

**Comment by lorensr** [comment]
Shows on restart:

![image](https://user-images.githubusercontent.com/251288/53590276-668d9f00-3b5f-11e9-86e1-1083cf513c2b.png)

![image](https://user-images.githubusercontent.com/251288/53590286-6a212600-3b5f-11e9-924f-a14ebe2f14c3.png)

**Comment by asfakAtGithub** [comment]
Got same issue like of lorensr. :(

**Comment by helipilot50** [comment]
Is there a timeframe for a real fix for this?

**Comment by Arelav** [comment]
`chown USERNAME /usr/local/bin` could help. I restarted just docker not system so it's not for 100%
