### ISSUE TITLE
diagnostics fail to run

### ISSUE THREAD

**Issue by yunti** [docker/for-mac#3239]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker app to open and be able to submit diagnostics
(needed for another issue on missing autocomplete in terminal)

### Actual behavior
Docker app does not open (does appear to start docker daemon)
Diagnostics cannot be run from docker app or terminal via..
(there are no contents in `/Applications/Docker.app/Contents/Resources/bin/`)

Logs generated via:
`$ show --debug --info --style syslog --last 1d --predicate "$pred" >/tmp/logs.txt`
just generate an empty file

### Information
Docker commands work fine as expected

docker version output is:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

Previosly tried to setup docker via brew with:
`brew install docker docker-compose`
This failed to launch the docker daemon correctly so uninstalled and installed the macos app via docker site.

  - macOS Version:
10.14 Mojave
### Diagnostic logs

```
Logs generated via:
`$ show --debug --info --style syslog --last 1d --predicate "$pred" >/tmp/logs.txt`
just generate an empty file


Docker for Mac: version...

```
Version:           18.06.1-ce

**Comment by yunti** [comment]
Looks like this might be a duplicate issue as other user on same docker version and os version.
#3235

**Comment by godbout** [comment]
Doesn't look the same as my issue; yours look worse 😂️ Seems you don't even have Docker installed at all.
