### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by HarryPatientPop** [docker/for-mac#3242]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I updated to the latest Docker Mac, and expected my existing images to continue working

### Actual behavior

After updating to the latest version of Docker Mac, I tried launching a container from an image, and it didn't launch.  In the `docker log container_name` logs I got got  `standard_init_linux.go:190: exec user process caused "permission denied"`.

### Information

  - macOS Version: 10.13.4

This does not happen for every image, just a specific one. 

Downgrading to the Docker version from around April 2018 causes the image to work again.

Not sure if relevant, but at the end of the image ends with an entrypoint script that's run by a non-root user (it's been appropriately chmodded).  In that script, a few sudo commands are called.  I mention this since other images do work, and not sure what other image-specific things could be causing this.

Another thing I'm doing in this image and not others is mounting directories from the host to the container, and also exposing ports.

### Diagnostic logs

```
Docker for Mac: version Docker 18.06.1-ce-mac73  (failing version)
Docker for Mac: version Docker 18.03.0-ce-mac60 (23751) (Working version)

```
I have downgraded Docker and don't have a test system set up to generate Diagnostic logs.

### Steps to reproduce the behavior

I cannot publicly share a Dockerfile, but I can answer questions about it.  Steps to reproduce is to create a container with this dockerfile with the aforementioned Docker For Mac version number.

**Comment by tiberiomoliveira** [comment]
Hi @HarryPatientPop, have you solved this problem?

I am having the same issue using the latest grafana image.

**Comment by acondrat** [comment]
Same issue with 18.09.0
