### ISSUE TITLE
How to make DFM recognize KUBECONFIG  environment changes

### ISSUE THREAD

**Issue by flangel** [docker/for-mac#3244]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

DFM respects the KUBECONFIG setting and displays different contexts immediately or even after restart

### Actual behavior

Changes to KUBECONFIG setting are ignored.
DOCKER FOR MAC *Version 18.06.1-ce-mac73 (26764)*

### Steps to reproduce the behavior

  1. Set KUBECONFIG using export KUBECONFIG
  2. Validate that setting is correct using kubectl config view to see the consolidated config
  3.  Restart Docker for Mac 
  4. Doubleckeck Kubernetes submenu --> NO additional Entry

**Comment by basz** [comment]
@flangel Did you solve this I have the same problem. 

here a solution to merge them: 

first:

```bash
mkdir ~/.kube/contexts
cp ~/.kube/config ~/.kube/contexts/docker-for-desktop-cluster.yaml
```

add any additional configurations to ~/.kube/contexts

create and execute the following script

```bash
#!/usr/bin/env bash

KUBECONFIG=""
for CONTEXT in ~/.kube/contexts/*; do
      KUBECONFIG=$CONTEXT:$KUBECONFIG
done

kubectl config view --flatten > ~/.kube/config

env -u KUBECONFIG

kubectl config view
```

**Comment by guillaumerose** [comment]
We can't get the value of KUBECONFIG automatically because the application doesn't know your shell. The best we could do is let you specify the targeted config file to use.
