### ISSUE TITLE
Cannot connect to docker demon

### ISSUE THREAD

**Issue by kumarchatla** [docker/for-mac#3246]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker version
Prints docker client and server Info

### Actual behavior
Client:
 Version:           18.06.1-ce
 API version:       1.22
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at tcp://10.x.xy.xy:2376. Is the docker daemon running?

### Information

  - macOS Version:

MacOS mojave
version 10.14
[20180928171905.zip](https://github.com/docker/for-mac/files/2429131/20180928171905.zip)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nateleavitt** [comment]
Also cannot connect on a new MacBook Pro

macOS 10.14 (18A391)
Docker version 18.06.1-ce, build e68fc7a

Also tried @tomsvogel suggestion in another topic to run `sudo /Applications/Docker.app/Contents/MacOS/Docker` which didn't work.

```shell
docker ps
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
```

**Comment by nateleavitt** [comment]
After doing some troubleshooting, I've found that if I run `sudo docker ps` it works. So this seems like a user permissions thing.

**Comment by Vallerious** [comment]
I had to reinstall Docker for Mac to be able to run docker without sudo...I think that happened after Mac OS update.
