### ISSUE TITLE
Docker stops responding after awhile > hyperkit high CPU usage

### ISSUE THREAD

**Issue by kemelinux** [docker/for-mac#3249]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8DC8A3B9-FC41-4C0C-B754-47F4DC37E039/20181001160309

### Expected behavior
Docker keeps on responding or the HyperKit reduces the CPU Load

### Actual behavior
Docker stops responding and I am unable to execute any docker command in the terminal.
Docker-diagnose does not respond either. I have to kill the hyperkit thread to stop Docker and restart it. This behaviour started a couple (2 or 3) versions earlier.

### Information

  - macOS Version: 10.13.6 (17G65)
[20181001160309.zip](https://github.com/docker/for-mac/files/2434744/20181001160309.zip)

**Comment by sbyrne-sugarcrm** [comment]
I have been experiencing this behavior for months.  So far, little rhyme or reason, other than other things on the Mac sometimes "lock up" for a time, and then get unstuck.  It's almost as if Docker cannot recover from being "stuck" (unable to run?) for a while, unlike other apps.
