### ISSUE TITLE
Not running on Mac OS Sierra Beta 6

### ISSUE THREAD

**Issue by marcelgoya** [docker/for-mac#325]
### Steps to reproduce

1. Open the app

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 30761230-5EFF-4FFB-8C88-09D26BCCF869
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by thatGuy0923** [comment]
It's dying for everyone, see [#64](https://github.com/docker/for-mac/issues/64l)

**Comment by dsheets** [comment]
@marcelgoya it appears that your disk image has been corrupted. We are working on disk image robustness and hope to have improvements on the stable channel soon. Unfortunately, the only ways to fix this problem are to either

1. Delete your `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` file which contains all of your containers, images, and Docker volumes

2. :whale: -> `Preferences...` -> `Uninstall/Reset` -> `Restore to Factory Defaults` which would do the same thing and reset all of the application settings

I'm sorry you experienced this issue. Please re-open if this doesn't solve your problem and thank you for your report!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
