### ISSUE TITLE
Unbale to bind the port to localhost on Mac

### ISSUE THREAD

**Issue by shridharkalagi** [docker/for-mac#3251]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 59265A60-8FB9-47F2-9B0E-7E6304A43167/20181003024435

### Information

  - macOS Version: MacOs Sierra 10.12.6

### Diagnostic logs

```
Diagnose succeded

```
Docker for Mac: Version 18.06.1-ce-mac73 (26764)
### Steps to reproduce the behavior

`docker pull citizenstig/nowasp`
`docker run -d -p 80:80 citizenstig/nowasp`

http://localhost doesn't open. Same steps work on Ubuntu OS

**Comment by gauravthadani** [comment]
1) you could check if `com.docker.vpnkit` is running as a process in your system. 
2) unset all docker env variables that might be set via profile etc

docker for mac no longer uses virtualbox etc (been a while), and there could be a conflict with docker-toolbox installation.
Take a look at docker-for-mac details here https://docs.docker.com/docker-for-mac/docker-toolbox/
