### ISSUE TITLE
Extra config option for kubernetes in Docker for Mac?

### ISSUE THREAD

**Issue by sznemeth** [docker/for-mac#3256]
Lads it's more like a question than an issue: is there a way to extra config options to Kubernetes in Docker for Mac? I'd like to enable anonymous requests for a small project but I cannot seems to find a way of any documentation on docker.io which would discuss this.

Apologies if this is not the right place to ask, please do direct me to a more appropriate forum if there's any so that I can pop my question.

Kind regards,
Zil

**Comment by guillaumerose** [comment]
For istio, if I remember correctly, all flags are correctly set. Is there something missing ?

**Comment by nomisbeme** [comment]
I missed that that defaults changed after 1.9, so I don't believe this is necessary for my specific case of Istio any more. Thanks for taking a look.
