### ISSUE TITLE
Allways have to set to factory defaults when rebooting

### ISSUE THREAD

**Issue by fincaminimo** [docker/for-mac#3257]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 43A144CA-F752-4722-B252-F0637AA33F12/20181004153505

### Expected behavior
Normal start up.
### Actual behavior
Can't start up Docker for Mac, and I have to reset to factory defaults each time I reboot the machine.
### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: all versions since two months (aproximately).

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kalexmills** [comment]
I have noticed some system instability between reboots as well. Are you using Kubernetes too? How are you using Docker and happens if you don't reset to defaults?
