### ISSUE TITLE
Error on Update

### ISSUE THREAD

**Issue by dheerajchand** [docker/for-mac#326]
### Steps to reproduce

1. Allow Update to run

### Expected behavior

Update will run correctly.

### Actual behavior

Update fails, returns this error.
### Information

```
Diagnostic ID: 3DBDE51C-28A2-4A17-9AE8-436D40D1C684
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
Beta 25 should have fixed most of the Sierra issues: https://download.docker.com/mac/beta/Docker.dmg 

Please help by updating to it or wait for the stable release of Sierra support on stable channel. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
