### ISSUE TITLE
Kubernetes with Docker for Mac not able to find metric-server api

### ISSUE THREAD

**Issue by vivekamin** [docker/for-mac#3260]
Kubernetes not able to find metric-server api.I am using Kubernetes with Docker on Mac. I was trying to do HPA from following example [https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/]. However, when I execute command `kubectl get hpa`, My target still was unknown. Then I tried, `kubectl describe hpa`. Which gave me output like below:

      Name:                                                  php-apache
      Namespace:                                             default
      Labels:                                                <none>
      Annotations:                                           <none>
      CreationTimestamp:                                     Sun, 07 Oct 2018 12:36:31 -0700
      Reference:                                             Deployment/php-apache
      Metrics:                                               ( current / target )
        resource cpu on pods  (as a percentage of request):  <unknown> / 5%
      Min replicas:                                          1
      Max replicas:                                          10
      Conditions:
        Type           Status  Reason                   Message
        ----           ------  ------                   -------
        AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
        ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API
      Events:
        Type     Reason                        Age               From                       Message
        ----     ------                        ----              ----                       -------
        Warning  FailedComputeMetricsReplicas  1h (x34 over 5h)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
        Warning  FailedGetResourceMetric       1m (x42 over 5h)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API

I am using [https://github.com/kubernetes-incubator/metrics-server] as suggested in Kubernetes documentation. I also tried doing same just using Minikube. But that also didn't work.

Running `kubectl get --raw /apis/metrics.k8s.io/v1beta1/nodes` outputs :

    {
      "kind": "NodeMetricsList",
      "apiVersion": "metrics.k8s.io/v1beta1",
      "metadata": {
        "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes"
      },
      "items": []
    }

### Information

  - macOS Version: Mojave version 10.14
  - Docker for Mac: 18.06.1-ce

```

**Comment by Jeffwan** [comment]
I have the same issue. looks like `kubelet` implementation is different. metrics-server might not able to fetch metrics from in-built cadvisor on node (Mac).

**Comment by vivekamin** [comment]
> I have the same issue. looks like `kubelet` implementation is different. metrics-server might not able to fetch metrics from in-built cadvisor on node (Mac).

https://stackoverflow.com/questions/52694238/kubectl-top-node-error-metrics-not-available-yet-using-metrics-server-as-he

**Comment by olereidar** [comment]
Any progress on this issue?

**Comment by ganga1980** [comment]
I have same issue cAdvisor endpoint not available on Kubernetes with Docker on Windows.  It will be  very helpful to get the perf metrics of the nodes and pods.
