### ISSUE TITLE
Docker Never Start on Mac

### ISSUE THREAD

**Issue by enka3** [docker/for-mac#3266]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C7B807BE-E978-4933-9FE5-EFAF193226AE/20181011053942

### Expected behavior
Docker to Run Smoothly on Mac using the lates Stable version
### Actual behavior
The Docker Status keep saying (Docker is starting) for ever
### Information

  - macOS Version: 10.14

### Diagnostic logs

```
Docker for Mac: version...Version 18.06.1-ce-mac73 (26764)

```

### Steps to reproduce the behavior

  1. ... Just Run the Docker

**Comment by seabirdman** [comment]
Same here.  When it runs it eats up the CPU.  Now it does not run at all.  Deleted and re downloaded and still not working.  Mac OS 10.14.1.  Cannot even use the self reporting diagnoses feature.  Unusable.

**Comment by kalexmills** [comment]
@seabirdman @enka3 Can you both check your preferences and see how much resources you are giving Docker?

**Comment by jurby** [comment]
+1
