### ISSUE TITLE
Fatal Error cannot install symlinks in /usr/local/bin (cannot handshake)

### ISSUE THREAD

**Issue by blouloudakis** [docker/for-mac#3269]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 8362FFEE-A10C-4AE5-9738-F2BADCD4F5EC/20181015222849

### Expected behavior
Docker for Mac should not require restart after being left for 12-16hrs 
### Actual behavior
If i leave my machine on overnight and return to work the next day i receive the "fatal error". im not sure if this is affecting any functionality
### Information

  - macOS Version: 10.14.1 Beta

### Diagnostic logs

```
Docker for Mac: version... 2.0.0.0-beta1-mac75 (27117) Edge

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by workdreamer** [comment]
Same here





  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

### Actual behavior

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior


  1. ...
  2. ...

**Comment by balsagoth** [comment]
Same as @workdreamer 

Diagnostics ID: E02C613D-E043-45AF-B5F3-E6F7D0D77583/20181128134146

**Comment by othelu** [comment]
Same issue for me : 916B3414-0065-4EA7-8243-436C5D8C3E1B/20181129125541

Version 2.0.0.0-mac78 (28905)

![image](https://user-images.githubusercontent.com/1157776/49223460-19265800-f3df-11e8-84fa-e9287ed525d4.png)

On MacOS Mojave but I already had this issue before migrating to Mojave

**Comment by alioguzhan** [comment]
Same Here.  -> 690140B3-955B-402C-AA72-F38D539C4357/20181204070923
Version 2.0.0.0-mac81 (29211)
Channel: stable

Don't know if it's related but I didn't have have this issue before Mojave btw.

**Comment by rajhub** [comment]
I have the same issue. I can reproduce this consistently by logging in as another user and then login back to the previous user.

**Comment by mkrakiewicz** [comment]
Same for me, happens when switching back to my user.

**Comment by larrybotha** [comment]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7A14AA53-AD7F-4788-B2F2-E3D56B1C7E44/20190110063725

### Information

  - this has only happened since upgrading to Mojave, and has happened twice
  - nothing particularly reproducible - issue has occurred both times after booting up from shutdown
  - macOS Version:10.14.2
  - Docker for Mac: 2.0.0.0-mac82

**Comment by rizwansaeed** [comment]
I have the same issue: switching between profiles consistently reproduces the problem

macOS 10.14.2 (18C54)

Docker Desktop
Version 2.0.0.2 (30215)
0b030e17ca

**Comment by marksy** [comment]
Agreed with many of the above. Switching user profiles on Mac OS seems to trigger `fatal error`. 
Mac OS 10.14.3 (18D109), Docker Desktop 2.0.0.2

**Comment by ldanilov** [comment]
Same issue after locking and unlocking OSX user.
Diagnostics ID: `6913EE64-3C79-4629-828C-574ADEFA4FA2/20190219221304`

**Comment by vsarpe** [comment]
Locking and unlocking OSX user (either manual or from inactivity)  produces this error.

Mac Mojave 10.14.3 (18D109), Docker Desktop Version 2.0.0.3 (31259).

Diagnostics ID: E4738960-4E29-4FAB-BE57-FA5E4A5F199C/20190222192806

**Comment by weyus** [comment]
Same here. After I log in from another user.

MacOS High Sierra (10.13.6), Docker Desktop Version 2.0.0.3 (31259).

Diagnostics ID: 35103BCD-721B-4874-95FD-7EAABA38C89E/20190226204535

**Comment by EricSocs** [comment]
Same here, right after resuming from sleep.
Docker left running overnight.

MacOS Mojave 10.14.2 (18C54)
Docker Version 2.0.0.3 (31259)
38E7C5E0-CA8F-4067-A165-728D968699ED/20190301085335

**Comment by IsaacInsoll** [comment]
I'm having the same issue on Mac 10.14.3 and Docker 2.0.0.3

**Comment by MatanRubin** [comment]
Having the same issue.
Diagnostics ID: CC79F954-200F-4BAE-94EF-664FA33DBA06/20190318063101

**Comment by mackjoner** [comment]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 148DB7C9-6D38-472F-84E6-4E3BF18AA005/20190401070000

### Expected behavior

### Actual behavior

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior


  1. ...
  2. ...

**Comment by ynarwal** [comment]
+1 on this

**Comment by vsevolodk** [comment]
+1 FA5D34D7-8284-492D-9360-5F4DCCB152CE/20190410144003

**Comment by NielsHaar** [comment]
+1 still occurs in Docker.app Version 2.0.0.3 and macOS Mojave Version 10.14.3 (18D109)

It doesn't happen consistently on unlocking the running session, but it's really annoying when it does.

**Comment by milojennings** [comment]
+1 happens to me whenever I unlock my computer in the morning for work.
Running High Sierra 10.13.6 (17G5019) and Docker 2.0.0.3 (31259)

**Comment by phoenixg** [comment]
+1, please fix this

**Comment by jeremywalter** [comment]
+1, would love to see a fix!

**Comment by albanh** [comment]
I'm also seeing this issue on Mojave 10.14.4 and Docker 2.0.0.3 (31259).

**Comment by djneely** [comment]
Still seeing this issue here as well.

**Comment by zorkoe-uho** [comment]
> I'm also seeing this issue on Mojave 10.14.4 and Docker 2.0.0.3 (31259).

+1

**Comment by SaneBow** [comment]
Same issue for me on Mojave 10.14.5 and Docker 2.0.0.3 (31259). Happened occasionally after unlock.

**Comment by njbagger** [comment]
> Same issue for me on Mojave 10.14.5 and Docker 2.0.0.3 (31259). Happened occasionally after unlock.

+1

**Comment by alanmoore** [comment]
It's not just Mohave, I get this issue on High Sierra 10.13.6 running Docker Desktop 2.0.0.3 (31259)

**Comment by hazelement** [comment]
Same issue here. But it only does it when I boot up the machine. If I close the message window and start docker again manually, the error doesn't appear.

**Comment by blouloudakis** [comment]
this seems to have gone away in later versions of docker for mac
