### ISSUE TITLE
Failed on startup: unable to create symlinks to /usr/local/bin

### ISSUE THREAD

**Issue by brendon9x** [docker/for-mac#3271]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6BE6CD69-C829-4AF2-9465-FB191984FFCC/20181016192639

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by msbit** [comment]
Also diagnostic ID 59C20769-798A-4947-9544-687285B7666D/20181206005315
