### ISSUE TITLE
docker for Mac hang after several hours

### ISSUE THREAD

**Issue by kkzz8888** [docker/for-mac#3274]
- [x ] I have tried with the latest version of my channel (Stable)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:5A4A3916-95C1-4328-8C75-2914BF632982/20181018002820

### Expected behavior
docker should keep running...
### Actual behavior
docker daemon not responding to any command after several hours of restart (close to 10 hrs)
### Information

  - macOS Version:10.14

### Diagnostic logs

```
Docker for Mac: version...

18.06.1-ce-mac73 (26764) stable 

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
-->

  Not sure, running a cluster of Kubernetes for several hours

**Comment by heihachi88** [comment]
It's because of memory leak on Mojave #178

**Comment by kalexmills** [comment]
How much system resources are you giving to Docker? I have found that hangs will occur when I have too many k8s containers running, and I have kept the settings set to the default of 2 GB of RAM.

**Comment by eddiemonge** [comment]
Most likely a memory issue and a duplicate of #3232 and #178 like @heihachi88 said . Check your memory usage in activity monitor
