### ISSUE TITLE
Cannot send traffic with raw sockets out of docker environment

### ISSUE THREAD

**Issue by Kkevsterrr** [docker/for-mac#3275]
Hi all - hoping you can help me with this issue I'm having with raw sockets. 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0E4A4ABC-3D3B-4447-A353-0275D92F3AA6/20181018040405

### Expected behavior
In a docker container, I can open a raw socket and send traffic outside the docker container. 

### Actual behavior
In a docker container, I can open a raw socket and send traffic to between docker containers. (I will include how I'm creating and sending packets w/ raw sockets below) I confirm packets arrives at the receiving container with a packet capture, and all is good. Each container is also fully able to access the internet - I can `wget` external websites no problem. For some reason, however, I am completely unable to send any packets using raw sockets outside of the docker environment. 

Example sending socket with raw packet: 
```
# scapy
>>> p = IP(src="<ip of container>", dst="<dst of packet>")/TCP(sport=1234, dport=8000, flags="S")
>>> send(p)
.
Sent 1 packets.
```

#### Docker configuration
I have tried to solve this problem multiple ways. First, I tried using a docker bridge, and sending traffic with that. Again, I can send traffic between containers with and without raw sockets, and I can send traffic out of the containers with regular sockets, but I cannot send traffic out of the container. I have tried with the `host` network (though that option doesn't seem to be functional on Macs regardless). 

Most confusingly, I also tried the following approach. I took two docker containers, set the second container to be the default gateway for the first, and set up NAT on the second container. 

*Container 1*: 
```
# ip route del default
# ip route add default via 172.17.0.2 <-- IP of second docker container
```
*Container 2*:
```
# iptables -t nat -A POSTROUTING -j MASQUERADE
```
At this point, I can communicate between containers fine, and container 1 can reach outside the docker network to the internet, and it's traffic traverses through container 2. I can verify this with packet captures on container 2. However, when I send traffic from a raw socket on container 1, it never seems to leave the container, and I do not understand why. 
 
### Information
This problem is reproducible, and may also affect docker on other platforms.
  - Engine: 18.06.1-ce
  - Compose: 1.22.0
  - Machine: 0.15.0
  - Notary: 0.6.1
  - Credential Helper: 0.6.0
  - Kubernetes: v1.10.3
  - macOS Version: 10.13.6 (17G65)

### Diagnostic logs
I have uploaded my diagnostic logs. The output of the pane on the side when I open "Diagnose & Feedback" is now only the following: 
```
Diagnose succeded
```

### Steps to reproduce the behavior
Create any docker container on a Mac. Create a packet and send using a raw socket to any public webserver. 

For example:
```
# dig +noall +answer google.com                                                                                                   [0:17:03]
google.com.		97	IN	A	172.217.3.46
# scapy
...
>>> p = IP(src="192.168.1.202", dst="172.217.3.46")/TCP(sport=1234, dport=80, flags="S")
>>> send(p)
.
Sent 1 packets.
>>>
```

In Wireshark, when I do the above on my Mac, I see a SYN packet leave, a SYN-ACK return (and then my computer sends an RST, as my kernel is unaware of the packet). When I run this command from inside the container, I don't see any traffic leaving my computer or returning. 

I'm highly suspect of docker's iptables routing rules - as raw sockets bypass the kernel's IP stack, they don't traverse or get seen by docker's iptables rules. 

Hopefully this helps - I'm game to provide any additional information as needed, or try to reproduce on other platforms.

**Comment by rasity** [comment]
Hi Kkevsterrr,

I have same issue. Did you find a solution ?

**Comment by Kkevsterrr** [comment]
Hi @rasity - 

Unfortunately, I never did - I had to remove docker from my project completely. I never heard back from the docker team about the issue either. If you do find a solution, please let me know!

**Comment by rasity** [comment]
Hi @Kkevsterrr,

Actually, the problem I observed is we can send packets with raw socket to outside of container even host but if packet's source ip is not spoofed. 

When packet's source ip is spoofed, source ip is overriden by host while packet pass throught host.
So, if you have this needs, you should connect your container directly physical NIC with macvlan option. 

[Macvlan](https://docs.docker.com/network/macvlan/)

If you have not this needs, you should give capabilities to your container. Maybe --priveleged parameter is an option.

[Run options](https://docs.docker.com/engine/reference/run/l)

But if your application will run on aws, Amazon ECS does not support macvlan :(

Best regards,
Raşit

**Comment by Kkevsterrr** [comment]
Hey @rasity - interesting! You were seeing raw socket traffic sent from inside the container being mangled by the host itself? (By 'host', also, do you mean moby, or the mac?). 

MacVlan sounds like a good solution - I'll check it out - thanks!!

**Comment by TheJYKoder** [comment]
Did the MacVlan work?
