### ISSUE TITLE
Docker stuck in Docker is starting

### ISSUE THREAD

**Issue by chateaufiesta** [docker/for-mac#3277]
I start the Docker App but it always says "Docker is starting"

Diagnose ID A75EF431-BFB8-4E46-AC4C-9F0EC3008FD8/20181018110236

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by texasbobs** [comment]
I have the same issue.  Just hangs with com.docker.hyper using 100% CPU and never finishes "starting".  Unable to get diagnostics, it never comes back.

**Comment by texasbobs** [comment]
Diag finished.  
Diagnostics ID: E890E6E6-50BE-4796-9A62-94877F2D6CB6/20181018143206

**Comment by ajitj** [comment]
I have the same issue

Diagnostics ID: 599B9DDB-7EBD-4186-95CA-DE082936D0C0/20181019120412

**Comment by webaholik** [comment]
Same issue,
Diagnostics ID: 919F1D76-2017-4301-8DB5-41C10A80185D/20181019133638

**Comment by andre487** [comment]
Same issue. Diagnostic without Docker start: 1798B4EB-495C-4A65-A97D-2CFFAF4C58DE/20181021070830

Diagnostic with try to start but restarted when start progress: 1798B4EB-495C-4A65-A97D-2CFFAF4C58DE/20181021071020

**Comment by janzahorak** [comment]
Preferences -> Reset -> Reset to faktory defaults

worked for me

**Comment by texasbobs** [comment]
Is anyone looking at this?  

Factory reset might work once, but not always and not often.

**Comment by chateaufiesta** [comment]
Tried Reset to factory defaults, had the same problem.
Uninstalled and installed, had the same problem.

**Comment by kalexmills** [comment]
How many resources are folks giving Docker in the preferences? Are folks using Kubernetes, if so, how many containers are they running?

I encountered a similar problem while running a few containers, and it was resolved by providing Docker with more memory and CPUs.

**Comment by kalexmills** [comment]
@Peccansy since you are the only one with this popup/privileged access issue, you may consider filing a separate ticket.

**Comment by sullenor** [comment]
Faced the similar issue. I tried factory reset and it didn't helped.

Diagnostics Bundle: /tmp/1C3F2F67-568E-4019-98DA-246E757B4899/20181106114842.zip
Diagnostics ID:     1C3F2F67-568E-4019-98DA-246E757B4899/20181106114842

**Comment by kalexmills** [comment]
@sullenor, how much resources are you providing to Docker? I have found that I need to provide Docker with more than the default 2GB of RAM in order for it to be stable.

**Comment by sullenor** [comment]
@kalexmills CPUs 2, Memory 2GiB, Swap 1GiB, Disk 16GiB.
I also cleaned cache before and reinstalled docker.

**Comment by sullenor** [comment]
I found few tips from my colleagues that during the start virtual machine may ask to set options and waits for inputs. Thus it doesn't receive any input and the docker hangs in starting state.

Connecting to terminal via `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty .` and hitting "enter" few times may help.

**Comment by directionless** [comment]
What is the state of this? My docker for mac is exhibiting this kind of problem. My current workaround is to use the above suggested screen command, every time docker restarts.

**Comment by groob** [comment]
Same issue here.

**Comment by underoot** [comment]
Using [`screen` for connecting to docker `tty`](https://github.com/docker/for-mac/issues/3277#issuecomment-436389874) is only one workaround but it weird!
