### ISSUE TITLE
vmstateevent invalid json:

### ISSUE THREAD

**Issue by michaelcurry** [docker/for-mac#328]
### Information

Diagnostic ID: 686FB687-9536-4908-9F04-547832A7C718
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/mc/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start Docker
2. Wait For Error (about 2 to 30 seconds) `vmstateevent invalid json:` 
3. be sad

**Comment by bunchjesse** [comment]
This was fixed in Beta 23. You need to upgrade to the latest version in the Beta channel: 

Version 1.12.1-rc1-beta23 (build: 11375)
https://docs.docker.com/docker-for-mac/#/download-docker-for-mac

**Comment by mchiang0610** [comment]
Closing because fixed in the beta 25

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
