### ISSUE TITLE
so slow

### ISSUE THREAD

**Issue by packlikez** [docker/for-mac#3284]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Please open a fresh ticket with steps to reproduce the behaviour and a set of diagnostic logs. Thanks!

**Comment by djs55** [comment]
Please open a fresh ticket with steps to reproduce the behaviour and a set of diagnostic logs. Thanks!
