### ISSUE TITLE
its slowing any containers in docker

### ISSUE THREAD

**Issue by thiagoguto** [docker/for-mac#3289]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...
30B49231-8473-4C0E-9AF2-5BD27D81195B/20181025102605
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by eddiemonge** [comment]
you did not fill out all the info. What version of Mac? What's the issue exactly? The title is vague
