### ISSUE TITLE
Crashes MacOS Mojave (system restarts) when using keras with CPU version 

### ISSUE THREAD

**Issue by stephanegaiffas** [docker/for-mac#3291]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4E6CEDB9-D7FF-41B8-970B-BA894BEDE65D/20181025194228

### Expected behavior

No MacOS crash :)

### Actual behavior

MacOS crashes

### Information

It can be reproduced using an image available at stephanegaiffas/formation_cnrs with a notebook that I can send if necessary

  - macOS Version: MacOS Mojave 10.14 (18A391)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

docker run -dt -v <PATH>:/formation_cnrs -p 4444:8888 formation_cnrs

and launching a notebook that I can send to you

**Comment by stephanegaiffas** [comment]
Turned out to be a problem with tensorflow !

**Comment by AlexVerine** [comment]
Hi Stephane,
Did you find a solution ? I admit that I don't know much and I may be stuck hard here.
Thanks

**Comment by stephanegaiffas** [comment]
Hi Alex,
turns out that it's actually coming from tensorflow, not docker....
Thanks !
