### ISSUE TITLE
All Docker commands are extremely slow. 

### ISSUE THREAD

**Issue by arnabsen1234** [docker/for-mac#3299]
Diagnostic id: C9C3CD6B-4BFD-473F-94D1-B95750E12125/20181030055715

  - [ X] I have tried with the latest version of my channel (Stable)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: C9C3CD6B-4BFD-473F-94D1-B95750E12125/20181030055715

### Expected behavior
Docker commands run instantly

### Actual behavior
Docker commands take huge time to respond. 

docker version takes ~2 mins to run. 
docker container run --publish 90:90 nginx takes more than 30 mins to complete. 

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes it is reproducible. 
  - Is the problem new? Yes. It used to work fine before. After installing latest version and installing mojave , docker became extremely slow. 
  - Did the problem appear with an update? Yes. 
  - macOS Version: 10.14 (18A391)

Docker for Mac: Version 18.06.1-ce-mac73 (26764)
[20181030055715.zip](https://github.com/docker/for-mac/files/2530061/20181030055715.zip)

**Comment by eddiemonge** [comment]
Most likely a memory issue and a duplicate of #3232 and #178 . Check your memory usage in activity monitor
