### ISSUE TITLE
Error to run docker commands

### ISSUE THREAD

**Issue by roneichiarandi** [docker/for-mac#33]
### Expected behavior
 run docker-compose up

### Actual behavior

$ docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1

### Information

The docker deamon doesnt strart 
Diagnostic ID: 285B74E3-14F5-4AED-83A9-263F76942063
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR] docker-cli
docker ps failed
[OK] app
[OK] moby-syslog
[OK] disk
[OK] virtualization
[OK] system
[OK] menubar
[OK] osxfs
[OK] db
[OK] slirp
[OK] moby-console
[OK] logs
[OK] vmnetd
[OK] env
[OK] moby
[OK] driver.amd64-linux

### Steps to reproduce the behavior

  1. docker-compose up

**Comment by friism** [comment]
@roneichiarandi thanks for reporting. Is the problem only with `docker-compose` or does `docker run hello-world` work?

**Comment by dialex** [comment]
@roneichiarandi try clicking the Docker for Mac icon, then go to Preferences, Uninstall, and then choose Restore Defaults (Reset). It worked for me.

**Comment by samoht** [comment]
Can you please provide the compose file where this is failing? The reproduction steps make it very hard for us to help. We are running docker-compose tests during our release process and they pass. 

Closing the issue for now on, but please re-open when you have more complete reproduction steps, that we can replicate and debug. Thanks!

**Comment by roneichiarandi** [comment]
Thanks @dialex it worked for me too! :smile:

**Comment by roneichiarandi** [comment]
@samoht The error occurred when I update to 1.12.0-beta21 and restart docker application. All docker commands didn't work before to restore default. Now it works. Thanks.
