### ISSUE TITLE
starting container failed: failed to initialize logging driver: Unix syslog delivery error

### ISSUE THREAD

**Issue by jfbelisle** [docker/for-mac#3303]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 90D098F2-2DA2-47BD-9E0E-C0EC9689510D/20181031142554

### Expected behavior
Docker container should start and foward log to syslog

### Actual behavior
The Docker container never starts, the startup just hangs

starting container failed: failed to initialize logging driver: Unix syslog delivery error

### Information

  - macOS Version: 10.14 (18A391)

### Diagnostic logs

```
Docker for Mac: 18.06.1-ce-mac73 (26764)

```

### Steps to reproduce the behavior

logging:
      driver: syslog
      options:
        syslog-facility: local0

**Comment by hrpatel** [comment]
+1 for fixing this issue

**Comment by papiveron** [comment]
Hi,

Please I'm having the same issue, how did you fix it? I don't see and understand what you did.

Thanks,
Eugène NG

**Comment by bharat-nain** [comment]
This issue still occurs!

**Comment by sebastianserrano** [comment]
I still have this issue also

**Comment by eivindml** [comment]
Yeah, I have  this issue on multiple projects now, where it never happened before. 
Only option for now is to disable logging.

```
logging:
      driver: none
```
