### ISSUE TITLE
Unexpected Docker crash, possibly when killing a running container

### ISSUE THREAD

**Issue by mor1** [docker/for-mac#3307]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CFA5DCCE-F8AE-401B-88A2-0349C99B3B9A/20181102154121

### Expected behavior

Docker not crashing

### Actual behavior

Docker crashed

### Information

  - macOS Version: 10.13.6 (17G65)

I have a number of command line utilities containerised. I was piping through my `jq` container (hub: `mor1/jq`) and ^C on the command appeared to trigger a Docker crash.

Creating diagnostic bundle through the UI didn't complete, so bundle was created via the CLI (which did seem to complete and upload).

### Diagnostic logs

```
Docker for Mac: 
Version 2.0.0.0-beta1-mac75 (27117)
Channel: edge
915f68b131
```

### Steps to reproduce the behavior

See above

**Comment by mor1** [comment]
Happened again. Dialog box popped up containing
```
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 15733)
```
Command line in progress at the time was:
```
cat FILENAME | jq .SystemState.Docker | less
```

Diagnosis via UI seemed to hang again. Issued via CLI instead, bundle ID `CFA5DCCE-F8AE-401B-88A2-0349C99B3B9A/20181102155809`.

**Comment by HazCod** [comment]
I've been encountering periodic crashes aswel, but since this is happening on a server I cannot pinpoint the cause..
