### ISSUE TITLE
"Symlink /usr/local/bin/kubectl.docker doesn't exist" when trying to enable Kubernetes

### ISSUE THREAD

**Issue by smoll** [docker/for-mac#3308]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F4B4C930-9A11-4898-A948-3BF21E1D40DD/20181102164111

### Expected behavior

Installing Kubernetes via Docker for Mac should work even with a preexisting `kubectl` install

### Actual behavior

After clicking `Install` I get the following error:

```
Fatal Error
Symlink /usr/local/bin/kubectl.docker doesn't exist
```

What should this symlink be pointing to?

### Information

It works fine on my other laptop with Docker for Mac installed, but that one doesn't have `kubectl` installed via `gcloud`. Even after removing the preexisting `kubectl` install with `gcloud components remove kubectl`, this problem persists, however.

### Diagnostic logs

```
Docker for Mac: version...
{"Platform":{"Name":""},"Components":[{"Name":"Engine","Version":"18.06.1-ce","Details":{"ApiVersion":"1.38","Arch":"amd64","BuildTime":"2018-08-21T17:29:02.000000000+00:00","Experimental":"true","GitCommit":"e68fc7a","GoVersion":"go1.10.3","KernelVersion":"4.9.93-linuxkit-aufs","MinAPIVersion":"1.12","Os":"linux"}}],"Version":"18.06.1-ce","ApiVersion":"1.38","MinAPIVersion":"1.12","GitCommit":"e68fc7a","GoVersion":"go1.10.3","Os":"linux","Arch":"amd64","KernelVersion":"4.9.93-linuxkit-aufs","Experimental":true,"BuildTime":"2018-08-21T17:29:02.000000000+00:00"}
```

### Steps to reproduce the behavior

  1. Install `kubectl` via `gcloud components install kubectl`
  2. Docker for Mac > `Preferences...`
  3. Under `Kubernetes` > `Enable Kubernetes` > `Apply`
  4. Click `Install` when it prompts you

**Comment by orkenstein** [comment]
Still an issue on restart
