### ISSUE TITLE
Memory leak with latest OSX and macbook pro

### ISSUE THREAD

**Issue by vitalii-fedoryshyn** [docker/for-mac#3323]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5BABB48A-A674-4482-93A9-069B02D2734C/20181108163259

### Expected behavior
Docker container should not allocate unneeded memory

### Actual behavior
On a latest macbook pro with a latest OSX an Docker for Mac version, com.docker.hyperkit took 2.77 Gb of RAM without any running containers.(default docker setting)

### Information

  - macOS Version: 10.14.1 (18B75)

### Diagnostic logs

```
Docker for Mac: 18.06.1-ce-mac73 (26764)

```

### Steps to reproduce the behavior

  1. By new macbook
  2. Install all updates
  3. Install docker for mac

**Comment by vitalii-fedoryshyn** [comment]
I don't know where is a bugs, is they part of new OSX or is they part of Docker for Mac(or on both side), but this issue is related to new OSX version. So I try to update OS on my old MacBook Pro(Mid 2014 16G RAM) and got next result(with default docker configuration and without runing docker images)

	macOS Version: 10.13.6 (17G3025)
	Docker for Mac: 18.06.1-ce-mac73 (26764)
	com.docker.hyperkit(memory usage after startup): 1.27G

	macOS Version: 10.14 (18A391)
	Docker for Mac: 18.06.1-ce-mac73 (26764)
	com.docker.hyperkit(memory usage after startup): 2.78G

	macOS Version: 10.14.1 (18B75)
	Docker for Mac: 18.06.1-ce-mac73 (26764)
	com.docker.hyperkit(memory usage after startup): 2.78G

**Comment by eddiemonge** [comment]
Duplicate of #178
