### ISSUE TITLE
Docker Desktop support for multi-node k8s cluster

### ISSUE THREAD

**Issue by iangkent** [docker/for-mac#3342]
Is it possible to create a multi-node kubernetes cluster using Docker Desktop for Mac?

* https://github.com/kubernetes/minikube/issues/94
* https://github.com/docker/for-mac/issues/67

**Comment by chezbut** [comment]
This should never have been closed - this is a hard requirement for many use cases.

**Comment by chezbut** [comment]
@docker-desktop-robot open
