### ISSUE TITLE
Docker for Mac 2.0.0.0-mac78 (28095) [Channel: stable] fails to launch

### ISSUE THREAD

**Issue by larrywest** [docker/for-mac#3349]
I upgraded to Docker for Mac 2.0.0.0-mac78 this morning on OS/X 10.13.6 ("macOS High Sierra") -- it lists engine 18.09.0.

The launch window includes this information:
```
2018-11-19T18:01:02Z docker + '[' -f /etc/kubernetes/kubelet.conf ]
2018-11-19T18:01:02Z docker + echo 'kubelet.sh: /etc/kubernetes/kubelet.conf has arrived'
2018-11-19T18:01:02Z docker kubelet.sh: /etc/kubernetes/kubelet.conf has arrived
2018-11-19T18:01:02Z docker + mkdir -p /etc/kubernetes/manifests
2018-11-19T18:01:02Z docker + exec kubelet '--kubeconfig=/etc/kubernetes/kubelet.conf' '--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf' '--pod-manifest-path=/etc/kubernetes/manifests' '--allow-privileged=true' '--cluster-dns=10.96.0.10' '--cluster-domain=cluster.local' '--cgroups-per-qos=false' '--enforce-node-allocatable=' '--network-plugin=cni' '--cni-conf-dir=/etc/cni/net.d' '--cni-bin-dir=/opt/cni/bin' '--cadvisor-port=0' '--kube-reserved-cgroup=podruntime' '--system-reserved-cgroup=systemreserved' '--cgroup-root=kubepods' '--hostname-override=docker-for-desktop' '--fail-swap-on=false'
2018-11-19T18:01:02Z docker 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Error starting daemon: error initializing graphdriver: driver not supported
2018-11-19T18:01:02Z docker + failed_to_start
2018-11-19T18:01:02Z docker 
  0     0    0     0    0     0+     tail   /var/log/docker.log0
2018-11-19T18:01:02Z docker       0 --:--:--  0:00:01 --:--:--     0
2018-11-19T18:01:02Z docker curl: (56) Recv failure: Connection reset by peer
```

I have tried the "Diagnose & Feedback" twice now, but it never seems to terminate (after 10 minutes minimum waiting on my part).

I did the manual `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload`, see below.

/Library/Logs/DiagnosticReports has a 3KB com.docker.hyperkit entry for each attempt. The only thing that stands out to me is exceeding the wakeup limit, but that happened a few times last week, too. I've pasted in the contents of one below.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] Diagnostics included
  - Diagnostics ID: `29F7B41C-CB2C-4456-94D2-43690B12E34A/20181119182739`

### Expected behavior

It would launch, as it did with the previous Stable Channel version on Friday.

### Actual behavior

It does not launch (after upgrading).

### Information

It is reproducible. It is new. No DockerFiles have changed.

  - macOS Version: 10.13.6

### Diagnostic logs 

From the manual upload: 
 - Diagnostics ID: `29F7B41C-CB2C-4456-94D2-43690B12E34A/20181119182739`

But the last lines of the output from that command look problematic:

```
time="2018-11-19T10:27:53-08:00" level=info msg="Getting Linux Diagnostics via a virtio socket: hyperkit:/Users/lwest/Library/Containers/com.docker.docker/Data/vms/0:62374" type=virtsock
time="2018-11-19T10:37:39-08:00" level=warning msg="Global command context: context deadline exceeded" type=list
INFO[0601] Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/29F7B41C-CB2C-4456-94D2-43690B12E34A/20181119182739.zip 
```

#### Other diagnostics

The contents of /Library/Logs/DiagnosticReports/com.docker.hyperkit_2018-11-19-100206_abcde181db0flb.wakeups_resource.diag:

```
Date/Time:       2018-11-19 10:00:10.155479 -0800
OS Version:      Mac OS X 10.13.6 (Build 17G3025)
Architecture:    x86_64
Report Version:  19

Command:         com.docker.hyperkit
Path:            /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
Version:         ??? (???)
Parent:          launchd [1]
Responsible:     Docker [8852]
PID:             9391

Event:           wakeups
Action taken:    none
Wakeups:         45001 wakeups over the last 113 seconds (397 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:   45000
Limit duration:  300s
Wakeups caused:  45001
Duration:        113.30s
Steps:           21

Hardware model:  MacBookPro11,5
Active cpus:     8

Fan speed:       5644 rpm


Powerstats for:  com.docker.hyper [9391]
UUID:            71246D3E-B4F4-34BA-9BE4-201218570ACE
Start time:      2018-11-19 10:00:31 -0800
End time:        2018-11-19 10:02:01 -0800
Parent:          launchd
Responsible:     Docker
Microstackshots: 21 samples (100%)
Primary state:   16 samples Non-Frontmost App, Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:   0 samples Idle, 21 samples Active
Power Source:    0 samples on Battery, 21 samples on AC
  21 thread_start + 13 (libsystem_pthread.dylib) [0x7fff5053bbf9]
    21 _pthread_start + 377 (libsystem_pthread.dylib) [0x7fff5053c50d]
      21 _pthread_body + 340 (libsystem_pthread.dylib) [0x7fff5053c661]
        20 vcpu_thread + 1213 (com.docker.hyperkit) [0x106377076]
          19 xh_vm_run + 343 (com.docker.hyperkit) [0x10635bae3]
            15 vmx_run + 1718 (com.docker.hyperkit) [0x1063527d1]
              15 hv_vcpu_run + 13 (Hypervisor) [0x7fff2a9242c4]
            2  hv_vmx_vcpu_read_vmcs + 23 (Hypervisor) [0x7fff2a92488f]
              2  <User mode>
            2  vmx_run + 1558 (com.docker.hyperkit) [0x106352731]
              2  vlapic_update_ppr + 97 (com.docker.hyperkit) [0x106358260]
                2  <User mode>
          1  xh_vm_run + 1335 (com.docker.hyperkit) [0x10635bec3]
            1  __psynch_cvwait + 10 (libsystem_kernel.dylib) [0x7fff50374a16]
              1  <User mode>
        1  callout_thread_func + 169 (com.docker.hyperkit) [0x10635d753]
          1  __psynch_cvwait + 10 (libsystem_kernel.dylib) [0x7fff50374a16]

  Binary Images:
         0x1061ae000 -        0x1063f0fff  com.docker.hyperkit (0) <71246D3E-B4F4-34BA-9BE4-201218570ACE> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
      0x7fff2a923000 -     0x7fff2a927fff  com.apple.Hypervisor 1.0 (1) <A696A85C-E23F-3DF4-A640-993D52622C62> /System/Library/Frameworks/Hypervisor.framework/Versions/A/Hypervisor
      0x7fff50358000 -     0x7fff5037eff7  libsystem_kernel.dylib (4570.71.13) <7601E31F-FC69-3FD9-B2F4-1BA00E0E4381> /usr/lib/system/libsystem_kernel.dylib
      0x7fff50539000 -     0x7fff50544fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
```

(But again, there are a few similar entries from earlier this month, before the upgrade.

### Steps to reproduce the behavior

1. Launch Docker for Mac after upgrading to 2.0.0.0-mac78.

**Comment by JLLeitschuh** [comment]
```
2018-11-19T18:53:30Z docker + grep -i ServerVersion
2018-11-19T18:53:30Z docker   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-11-19T18:53:30Z docker                                  Dload  Upload   Total   Spent    Left  Speed
2018-11-19T18:53:30Z docker 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Error starting daemon: error initializing graphdriver: driver not supported
2018-11-19T18:53:30Z docker 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-11-19T18:53:30Z docker curl: (5+ 6) Recvfailed_to_start fa
2018-11-19T18:53:30Z docker ilure: Connection reset by peer
2018-11-19T18:53:30Z docker + tail /var/log/docker.log
2018-11-19T18:53:30Z docker + :
2018-11-19T18:53:30Z docker + sleep 1
```

I'm experiencing the same symptoms, but with a different error.
Running `docker --version` I get the following:
```
Docker version 18.09.0, build 4d60db4
```

<img width="584" alt="screen shot 2018-11-19 at 1 56 04 pm" src="https://user-images.githubusercontent.com/1323708/48728414-e58b4700-ec02-11e8-8a23-1ba20796b3c1.png">

**Comment by jmpugh** [comment]
FWIW Similar error on High Sierra `10.13.5`:

![screen shot 2018-11-19 at 3 17 36 pm](https://user-images.githubusercontent.com/17254222/48732683-4b310080-ec0e-11e8-99cf-9e1acce70907.png)


```
2018-11-19T20:04:09Z docker  /var/run/docker.sock http/info
2018-11-19T20:04:09Z docker   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2018-11-19T20:04:09Z docker                                  Dload  Upload   Total   Spent    Left  Speed
2018-11-19T20:04:09Z docker 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Error starting daemon: error initializing graphdriver: driver not supported
2018-11-19T20:04:09Z docker + 
failed_to_start  
2018-11-19T20:04:09Z docker 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2018-11-19T20:04:09Z docker curl: (56) Recv failure: Connection reset by peer
2018-11-19T20:04:09Z docker + tail /var/log/docker.log
2018-11-19T20:04:09Z docker + :
2018-11-19T20:04:09Z docker + sleep 1
```

**Comment by sparticvs** [comment]
Same here. I've uploaded my diagnostics as well: AF04A412-DDDD-4CE5-BC5F-9F5B2C219F24/20181119202954

**Comment by larrywest** [comment]
As mentioned by @JLLeitschuh, by resetting to factory defaults, I was able to move past this and enable Kubernetes (using docker-for-desktop).

So I'm not blocked. 

I'm not sure what non-factory settings I had (other than K8s), though.

**Comment by patoi** [comment]
> Same issue on Mojave (10.14.1). Resetting to factory defaults fixed the starting, but the containers seem very slow in responding.

You have to set resources, memory.

![image](https://user-images.githubusercontent.com/1846548/48774403-7bd67000-ecca-11e8-869b-eeba8aac0986.png)

**Comment by sparticvs** [comment]
Factory reset worked for me as well.

**Comment by rquadling** [comment]
Would it be possible to have a report of the changes that will be made when calling "Factory Reset", i.e. You are going from 8 CPU to 4 CPU (as an example) or to be able to export current config as part of the reset. Something other than throwing all the previously working settings away and then trying to remember what they all are.

Config as code ... such a simple idea and a great way to share your settings without needing to trawl through pages of UI.

**Comment by dpursehouse** [comment]
It would have been nice to know that doing a factory reset would also wipe out containers and images.  I had expected it only to reset the settings.

**Comment by patoi** [comment]
I do a cold restart on MacOS and the problem is solved.

**Comment by javabrett** [comment]
@dpursehouse 

> It would have been nice to know that doing a factory reset would also wipe out containers and images. I had expected it only to reset the settings.

On my install the dialog text for _Reset to factory defaults_ says:

> Removes all settings and data. Just like new.

... and data, seems like it provides a warning, but I might be missing something.

**Comment by dpursehouse** [comment]
@javabrett it does on mine too, _if I go to the reset tab from the preferences dialog_.  However, when I ran into this problem docker had failed to start and only showed a window with the log file and a button to do the factory reset.  IIRC there was no such warning there.

**Comment by javabrett** [comment]
Fair enough.  Maybe there is a worth bug report there.  I wasn't aware of such a potent button on a log file window.

That said, [factory-reset](https://en.wikipedia.org/wiki/Factory_reset) usually works like - return it to the state it was from the factory, or so I could send it back to the factory, sans my data.

**Comment by bartkarp** [comment]
So to sum things up:

1. Updating to **stable** version bricks Docker for Mac.
2. Diagnose & Feedback seem to do nothing, the spinner there spins for 20 minutes already and nothing happens.
3. The only thing that seems to work requires reseting to default settings where Docker doesn't even tell you it's about to remove literally everything Docker-related including all of your images:

http://i.imgur.com/6CSf8xU.gif

:scream:

**Comment by JLLeitschuh** [comment]
@bartkarp Sadly yes

**Comment by bartkarp** [comment]
> @bartkarp Sadly yes

I'm wondering why there are no less drastic ways, I have countless containers and it takes literally days to set everything up properly once Docker resets itself. And I had to do that a few times in the past due to various bugs. It would be awesome to be able to perform "factory reset & automatic restore"/"settings reset only" or something like that.

**Comment by gbuckholtz** [comment]
I too am having problems starting up containers.  I ended up downgrading to 17.03.0-ce (my previous version of docker)  with partial success.  I noticed that if I tried to run a new container  it would immediately exit. HOWEVER,  if I start it using Kitematic it would go!  Even more interesting I could then start and stop the container to my heart's content via CLI.

**Comment by beniutek** [comment]
same issue. Something wrong with my graph driver, docker gives me an option either to diagnose or to reset **the settings** to factory status. Because diagnosing doesn't work at all I've chosen to reset the app to factory settings. Ended up loosing all the images & containers. There was no warning about that and term **settings** implies that only configuration is affected, not data.

**Comment by jon-heller** [comment]
Also had this problem, also lost all images after having no other option than a reset. Have had this happen with at least one other update in the past as well.

**Comment by cosmin** [comment]
Well this is pretty disappointing, I just got bit by this during a docker upgrade and it was the wrong time to lose and have to rebuild everything on my machine. This is not the type of behavior I was expecting from a stable release, I guess I'll have to be more careful about allowing docker upgrades in the future.

**Comment by henning** [comment]
Seems still to be the case for docker Desktop 2.0.0.2 on Mac Os 10.13.6 as I describe in #3491. I'm still looking for a way to fix this without a factory reset...

**Comment by javabrett** [comment]
Anyone seen this same problem yet with 2.0.0.3 (31259)?

/remove-lifecycle stale

**Comment by focux** [comment]
This just happened to me. I don't think that resetting to factory it's an acceptable solution.

/remove-lifecycle stale
