### ISSUE TITLE
docker 2.0.0.0-mac78 TooManyConnections error

### ISSUE THREAD

**Issue by ChesterEcwid** [docker/for-mac#3354]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior

Containers are working well and receive requests.

### Actual behavior

Containers have started but after trying to open some connections to them they become unresponsible. When I try to recreate container I get error
```
host-133:docker Yuri$ docker-compose up -d --force-recreate consul
Recreating local-consul ... error

ERROR: for local-consul  Cannot start service consul: driver failed programming external connectivity on endpoint local-consul: Error starting userland proxy: Bind for 0.0.0.0:8500: unexpected error Host.Sockets.Too_many_connections
```
The same behavior with postgres container.

I rolled back to 18.06.1-ce-mac73 and these errors disappeared.

### Information

  - macOS Version: High Sierra 10.13.6

### Diagnostic logs

```
Docker for Mac: 2.0.0.0-mac78
```

### Steps to reproduce the behavior

  1. Start container.
  2. Make some requests.

**Comment by Ky6uk** [comment]
May be related to #3350

**Comment by jesperborgstrup** [comment]
I also experience this issue in Docker Desktop Community Edition (`Version 2.0.0.3 (31259), 8858db33c8`).

My `uname -a`: 
```
Darwin my-machine.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

I have about 25 containers running on my machine. 

Looking at the logs (obtained as per https://stackoverflow.com/a/50545441/1319061) while running a `docker-compose up -d`, I get several lines like the following:
```
localhost com.docker.vpnkit[34028]: Hostnet_udp.input: bind raised Host.Sockets.Too_many_connections
localhost com.docker.vpnkit[34028]: Exceeded maximum number of forwarded connections (2000)
```

It should be noted that I'm currently on a VPN, and the issue seems to arise only when I'm connected to VPN (though I'm not 100% on this)

**Comment by MrBuddyCasino** [comment]
Same issue, using Tunnelblick: `docker: Error response from daemon: driver failed programming external connectivity on endpoint instana-hubforce (3a618dc8b767c3bc477ec47d42fdd7ccdaeb28399aea839f88658ec5a5699af4): Error starting userland proxy: Bind for 0.0.0.0:9888: unexpected error Host.Sockets.Too_many_connections.`

**Comment by luffyke** [comment]
Same issue.
> Version: 2.0.0.3 Engine: 18.09.2

Use below command get max-connection config for `vpnkit`.
```
ps -ef | grep docker

501 86429 86426   0   0:44.43 com.docker.vpnkit --ethernet fd:3 --port vpnkit.port.sock --port hyperkit://:62373/./vms/0 --diagnostics fd:4 --pcap fd:5 --vsock-path vms/0/connect --host-names host.docker.internal,docker.for.mac.host.internal,docker.for.mac.localhost --gateway-names gateway.docker.internal,docker.for.mac.gateway.internal,docker.for.mac.http.internal --vm-names docker-for-desktop --listen-backlog 32 --mtu 1500 --allowed-bind-addresses 0.0.0.0 --http /Users/kext/Library/Group Containers/group.com.docker/http_proxy.json --dhcp /Users/kext/Library/Group Containers/group.com.docker/dhcp.json --port-max-idle-time 300 --max-connections 2000 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.254 --log-destination asl --udpv4-forwards 123:127.0.0.1:53857 --gc-compact-interval 1800
```
--max-connections 2000

```
$ lsof -p $(pgrep vpnkit) | wc -l
    2017
```

most are CLOSED.
```
com.docke 86429 kext 2012u    IPv4 0x541b926840f2f9b      0t0        TCP localhost:6379->localhost:64873 (CLOSED)
```

I think it's a connection leak issue in `vipkit`, continuous concern.

**Comment by MrBuddyCasino** [comment]
Nice find! It rises to `2017`, but not further:
`lsof -p $(pgrep vpnkit) | wc -l   => 2017`
`lsof -p $(pgrep vpnkit) | grep CLOSE_WAIT | wc -l   => 1915`

**Comment by luffyke** [comment]
@MrBuddyCasino Hi, I don't think increase the limit would fix the issue if there is connection leak.

**Comment by MrBuddyCasino** [comment]
@luffyke that much is clear, but if it gets me over a working day that would have been an improvement.  Reverting to `18.06.0-ce-mac70 2018-07-25` fixed the issue for me.
