### ISSUE TITLE
The plain HTTP request was sent to HTTPS port on 2.0.0.0-mac78 (18.09)

### ISSUE THREAD

**Issue by danielbcorreia** [docker/for-mac#3359]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B8C00C49-3F08-4BE5-9153-CF8B5350F0BA/20181122154117

### Expected behavior
`docker pull` on an "insecure registry" should work.

### Actual behavior
Resulted in the following message (status 400 Bad Request):
"The plain HTTP request was sent to HTTPS port"

### Information
  - Reproduced the behaviour by updating from v1.8 (in which the docker pull command worked) to 2.0.0.0-mac78 (18.09)
  - macOS Version: High Sierra 10.13.3

### Steps to reproduce the behavior
  1. install docker for mac 18.06
  2. add insecure registry on the configuration
  3. `docker pull insecure.artifact.here:5003/someimage` - works
  4. update to docker for mac 2.0.0.0-mac78 (18.09)
  5. `docker pull insecure.artifact.here:5003/someimage` - fails with 400, html error message containing "The plain HTTP request was sent to HTTPS port"

**Comment by mihail-sky** [comment]
I've experienced the same issue with docker 2.0 and insecure Nexus

**Comment by ACouturier** [comment]
Appears to still be an issue in 2.0.0.2 (30125) from the Stable channel
