### ISSUE TITLE
Docker doesn't working on OS X Sierra

### ISSUE THREAD

**Issue by elfido** [docker/for-mac#336]
### Expected behavior
Docker up and running 

### Actual behavior
After rebooting the status remains as "Starting". Already tried to reinstall and reset settings.

### Information

Diagnostic ID: 5522EFD5-D72A-43AA-96BD-E3D6C4489A8F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A285a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install docker in Yosemite
2. Upgrade to OSX Sierra

**Comment by dsheets** [comment]
Some improvements for operation on OS X 10.12 Beta are current being evaluated in the Beta channel. Docker for Mac 1.12.1 due in a few weeks should have these improvements.

**Comment by mchiang0610** [comment]
Beta 25 aims to address these issues: https://download.docker.com/mac/beta/Docker.dmg 

Stable will be updated soon. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
