### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by hotzen** [docker/for-mac#3360]
- [X] I have tried with the latest STABLE version of my channel
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A7F21FC2-03AA-406D-B83B-822BF4822BE7/20181123082253

### Expected behavior
running local pg_restore into containerized postgres succeeds.

### Actual behavior
postgres-log in container:
```daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:00:33.352 UTC [1] LOG:  database system is ready to accept connections
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:05:57.709 UTC [23] LOG:  checkpoints are occurring too frequently (29 seconds apart)
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:05:57.709 UTC [23] HINT:  Consider increasing the configuration parameter "max_wal_size".
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:06:23.628 UTC [23] LOG:  checkpoints are occurring too frequently (26 seconds apart)
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:06:23.628 UTC [23] HINT:  Consider increasing the configuration parameter "max_wal_size".
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] LOG:  could not receive data from client: Connection reset by peer
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] CONTEXT:  COPY debt, line 2861916
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] STATEMENT:  COPY ...
daidalos-postgres_1_36312229a8b2 |
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] LOG:  incomplete message from client
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] CONTEXT:  COPY ...
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] STATEMENT:  COPY ...
daidalos-postgres_1_36312229a8b2 |
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] ERROR:  unexpected EOF on client connection with an open transaction
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] CONTEXT:  COPY ...
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.587 UTC [32] STATEMENT:  COPY ...
daidalos-postgres_1_36312229a8b2 |
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.592 UTC [32] FATAL:  terminating connection because protocol synchronization was lost
daidalos-postgres_1_36312229a8b2 | 2018-11-23 08:08:39.592 UTC [32] LOG:  could not send data to client: Broken pipe```

### Information
  - Is it reproducible?
yes, every time i do a pg-restore
already did 1) full-reset and even 2) uninstall/reinstall. nothing did help.

  - Is the problem new?
yes, since docker-for-mac 2.x

  - Did the problem appear with an update?
yes, since docker-for-mac 2.x

  - macOS Version:
macOS Mojave 10.14.1

### Diagnostic logs
```
Docker Desktop
Version 2.0.0.0-mac78 (28905)
Channel: stable
c404a62c3f
```

### Steps to reproduce the behavior
  1. do a ~50gb pg-restore into a postgres-container

**Comment by iamfeek** [comment]
Dropping by to also mention that a colleague and I are also facing this issue. 

We have the same exact setup the OP, only that our dataset is ~3gb.

**Comment by iamfeek-glints** [comment]
So my colleague and I reverted our versions to `Docker Community Edition 18.06.0-ce-mac70 2018-07-25`. That version is stable for what we needed to achieve.

The download link can be found at the [release notes](https://docs.docker.com/docker-for-mac/release-notes/#stable-releases-of-2018). 
but, [here is a direct link, to Docker For Mac, for convenience.](https://download.docker.com/mac/stable/26399/Docker.dmg)

**Comment by radiospiel** [comment]
I see the same here, with a 1.5GB psql dump

**Comment by hotzen** [comment]
we also did revert to Docker Community Edition 18.06.0-ce-mac70 2018-07-25, working flawlessly.

**Comment by davidoram** [comment]
I can confirm am getting the same issue with my setup. 
Diagnostics ID: 2DED6122-3304-4B87-BC1F-C19C21C40D39/20181218221203

**Comment by waTeim** [comment]
confirm this is still a problem with 2.0.0.3

**Comment by hotzen** [comment]
thanks for confirming, was just thinking about giving it a try ;)

**Comment by MarounMaroun** [comment]
Reproduces in 2.0.0.2.

**Comment by radiospiel** [comment]
docker for mac shipped quite a few updates since this ticket was opened. However, AFAICS the issue mentioned here was not adressed, according to changelogs and ticket activity. So I am still at 18.06 CE, and I think many others here as well.

Can someone from the @docker organisation pls shed some light on any progress on this issue?

**Comment by MarounMaroun** [comment]
I confirm. The issue mentioned here is still reproducible for me, I'm still on _Version 18.06.0-ce-mac70 (26399)_.

**Comment by radiospiel** [comment]
I can only repeat what I said on Sep 26th:

> docker for mac shipped quite a few updates since this ticket was opened. However, AFAICS the issue mentioned here was not adressed, according to changelogs and ticket activity. So I am still at 18.06 CE, and I think many others here as well.
> 
> Can someone from the @docker organisation pls shed some light on any progress on this issue?

Given that this issue makes @docker's sole product unusable for that subset of users which are using scenarios like database restores on a Mac database, I am horrified that @docker seems to think they a) don't need to address this, and b) think that it is somehow ok to silently close it. (or c) don't use the github bugtracker at all)

Personally you will see me leave the docker ecosystem.

**Comment by radiospiel** [comment]
This is getting ridiculous. @docker pls add a button to the Mac client which kets us reopen the supposedly "stale" issues.

**Comment by waTeim** [comment]
here is a bug the prevents Postgres operations introduced in version 2 100% reproducible has been around for almost a year now.

**Comment by radiospiel** [comment]
@waTeim this was originally filed Nov 23, 2018, so more than one and a half year already

**Comment by radiospiel** [comment]
we'll see how long until someone @ docker actually does something to address this issue. I am still on 18.06, and won't update to a newer version that might or might not work.

**Comment by kmandeville** [comment]
@radiospiel Me too! No idea what version they are even up to now. As soon as I upgraded from 18.06 (ce I think), it broke and I can't afford to have it not working. Never updated since
