### ISSUE TITLE
Docker Push to my-repo fails

### ISSUE THREAD

**Issue by ptamma** [docker/for-mac#3364]
Docker Push to my-repo fails
ref => https://success.docker.com/article/requested-access-to-the-resource-is-denied-when-pushing-image-via-cli
https://github.com/docker/for-mac/issues/2016

my user name and password doesn't have any special character. just alphanumeric.

  - [X] I have tried with the latest version of my channel (Stable )
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:91702197-A5DE-4C04-8064-AE9870BD92CD/20181124230925

### Expected behavior
should be able to push the image to personal repo
### Actual behavior
$ docker push xxxxxxxx/public/minio:latest
The push refers to repository [docker.io/xxxxxxxx/public/minio]
3ad9ef560f12: Preparing 
c5a04ee148b4: Preparing 
ebf12965380b: Preparing 
denied: requested access to the resource is denied

### Information

  - macOS Version: macOS Mojave 10.14.1 (18B75) 
MacBook Pro (15-inch, 2017)

### Diagnostic logs

```
Docker for Mac: version...
Docker Desktop Community
Version 2.0.0.0-mac78 (28905)
Channel: stable
c404a62c3f
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by praveenkumar** [comment]
Same here. I am also on mac `Mac version 10.14 (18A391)`

**Comment by erbas** [comment]
Same issue, suddenly I cannot authenticate to my docker hub account
Issue ID: 23CED42D-058E-443E-B4CE-F0D905588929/20190614194658

**Comment by berkobob** [comment]
I cannot push to my repo 
"denied: requested access to the resource is denied"
