### ISSUE TITLE
"cannot create symlinks in /usr/local/bin" error on startup

### ISSUE THREAD

**Issue by mjmare** [docker/for-mac#3365]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 8F1C50FA-3C15-46A8-BCD5-91A2A57CA757/20181125123144

### Expected behavior
Docker Desktop to start as usual

### Actual behavior
Error message: cannot create symlinks in /usr/local/bin

### Information
  - macOS Version: 10.14.1 (18B75)

Just starting up Mac and logging in. Docker Desktop fails to start. Gives the error message above and offers to do diagnostics. That failed (ie I killed it after 10 min). 
Reinstalled Docker. Seemed to work. 
Today started up Mac: same problem. This time the diagnostics succeeded. I terminated Docker Desktop. Restarted it. Works fine.  

### Diagnostic logs
```
Docker for Mac: version Version 2.0.0.0-mac78 (28905)
```

### Steps to reproduce the behavior
Just boot Mac and log in.

**Comment by msbit** [comment]
Also diagnostic ID 59C20769-798A-4947-9544-687285B7666D/20181206005315

**Comment by laszlo-kiss** [comment]
Also diagnostic ID EA0BF617-4A1C-4708-A8DA-C5CB370CFE63/20190223191706

**Comment by webuxr** [comment]
Another diagnostic ID: E1727E16-E658-4ED7-A8F6-CAC377C2534B/20190318131857
Same steps to reproduce as @mjmare.
