### ISSUE TITLE
Cannot seem to connect to any of my services from localhost

### ISSUE THREAD

**Issue by asikpradhan** [docker/for-mac#3366]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tyger** [comment]
Looks like related to https://github.com/docker/for-mac/issues/3350
