### ISSUE TITLE
2nd time in 2 days failed with having to reset

### ISSUE THREAD

**Issue by johnha** [docker/for-mac#3373]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
osx 10.14.1
### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pgayvallet** [comment]
Hi,

Please reopen with proper diagnostic.
