### ISSUE TITLE
Docker on Mac Mojava is using 4GB even though it's configured for 2GB

### ISSUE THREAD

**Issue by leandromoreira** [docker/for-mac#3377]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 12381BF6-921B-4FC8-8F3A-A688513B02B0/20181128162752

### Expected behavior
Docker daemon should be using 2GB
### Actual behavior
Docker daemon is using 4GB
### Information
  - macOS Version: 10.14 (18A391)
  - Docker Version: 2.0.0.0-mac78 (28905)

When you check the memory usage at the Mac **Activity Monitor** it shows 4GB instead of the configured 2GB.

![screen shot 2018-11-28 at 3 01 18 pm](https://user-images.githubusercontent.com/55913/49168386-82926200-f31e-11e8-92ad-cbf0667b5a76.png)

At first I thought it could be a **Activity Monitor** GUI problem and then I try to see memory footpring via ps. 

```
$ ps x -o rss,vsz,command | grep com.docker.hyperkit
2188996  6734344 com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 2 -m 2048M ...
```
The output shows that the rss memory (`the real memory (resident set) size of the process (in 1024 byte units)`) seems to point to the 2GB.

But at the same time the `vmmap` also shows a physical footprint of 4GB.

```
$ vmmap 10409
Process:         com.docker.hyperkit [10409]
Path:            /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
Load Address:    0x107278000
Identifier:      com.docker.hyperkit
Version:         ???
Code Type:       X86-64
Parent Process:  com.docker.driver.amd64-linux [10403]

Date/Time:       2018-11-28 09:59:43.425 -0200
Launch Time:     2018-11-28 09:55:21.895 -0200
OS Version:      Mac OS X 10.14 (18A391)
Report Version:  7
Analysis Tool:   /usr/bin/vmmap

Physical footprint:         4.1G
Physical footprint (peak):  4.1G
----
```

I tried to restart the Docker, the OS and **I even tried to change from 2GB to 1GB but it still doubles the configured RAM**.  Is anybody facing this same issue?

**Comment by leandromoreira** [comment]
I can't say for sure that the previous hasn't this issue but I remember to see the rigth memory footprint like in less than a month or two.

**Comment by leandromoreira** [comment]
https://github.com/docker/for-mac/issues/3232
https://github.com/moby/hyperkit/issues/231

**Comment by theecodedragon** [comment]
Any update on this, i have to completely remove docker. Using about 6.5GB memory while idle.

<img width="510" alt="screenshot 2018-11-30 at 11 31 29 pm" src="https://user-images.githubusercontent.com/9611106/49306423-2e42da00-f4f8-11e8-967d-48a57bf1ce7d.png">
<img width="568" alt="screenshot 2018-11-30 at 11 33 24 pm" src="https://user-images.githubusercontent.com/9611106/49306497-5a5e5b00-f4f8-11e8-9b30-dab6c62f3907.png">


Thanks.

**Comment by theecodedragon** [comment]
Sorry for posting in bits and pieces, I forgot to mention, I have memory configured for 2 GB as well.

**Comment by tingiris** [comment]
I'm having the same issue with macOS Mojave Version 10.14.2 (18C54) at idle it's using 2.85GB and climbs from there to > 4GB

![image](https://user-images.githubusercontent.com/1571217/51854299-7a43ac80-22f8-11e9-898b-11e8a121db10.png)

**Comment by jacksbox** [comment]
Similar issue here,
macOS 10.14.02
Docker Version 2.0.0.0-mac81 (29211)
* 14.3 GB instead to the 8 GB limit (with running containers)
* 8.52 GB even if *no* containers are running (this is also quite strange?)

see also: https://github.com/docker/for-mac/issues/781

**Comment by mgasner** [comment]
Same here

**Comment by ckanljung** [comment]
Same here, 4GB with no containers running. When restarting docker memory consumption quickly goes back to 4 GB (still no containers running).

MacOS 10.14, Docker Version 2.0.0.3 (31259)

**Comment by gihankarunarathne** [comment]
Same for me :( Configured to use 3GiB of Memory.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1858941/54108309-0adfd300-43f5-11e9-85f3-8125e795ca43.png">

**Comment by dawnerd** [comment]
Same, 2GB limit set, just about 3.95gb being used with no containers running. Previously if I had it set to 3GB it was using over 6GB. Lowering the limit doesn't reclaim any memory until docker is fully restarted. Really annoying.

**Comment by jameswmcnab** [comment]
Everyone here needs to read the following comments from the maintainers on this related issue:

- https://github.com/docker/for-mac/issues/3232#issuecomment-470896672
- https://github.com/docker/for-mac/issues/3232#issuecomment-471560033

**Comment by gihankarunarathne** [comment]
Refer to [stephen-turner](https://github.com/docker/for-mac/issues/3232#issuecomment-471560033) comment;

> Here's the report, from the engineer who has been investigating this: https://docs.google.com/document/d/17ZiQC1Tp9iH320K-uqVLyiJmk4DHJ3c4zgQetJiKYQM/edit?usp=sharing
> 
> We'll probably publish it as an official blog post later, but I wanted people watching this thread to see it as soon as possible.

**Comment by dperetti** [comment]
Awesome! Now we want the same investigation report for Kubernetes local cluster 😃.

**Comment by moltar** [comment]
My hunch is that it has something to do with Kubernetes. I think it was all fine, until I enabled Kubernetes and then disabled it. After that, I've been experiencing all sorts of memory issues and slow downs coming from Docker process. But could be a coincidence, of course.

**Comment by moltar** [comment]
I read the report referred by @gihankarunarathne and I understand the mem counting stuff it talks about.

So, maybe my issue is not related, and I just thought the mem was the symptom. But the reason I even looked a mem usage is that I am experiencing significant slowdown when running Docker on the latest MacBook Pro, like everything is becoming slower, even VS Code IntelliSense suggestions lag sometimes.

**Comment by iderets** [comment]
Same here (MacOS 10.14.5, Docker 2.0.0.3 (31259))

**Comment by roynasser** [comment]
MacOS 10.14.5
Docker 2.1.0.3 (38240 / 19.03.2)

4GB right after startup...

**Comment by ddurdle** [comment]
The latest docker requires a minimum 4GB of ram at all times.  If you try to install it on anything less, it will advise you of this fact.

**Comment by stephen-turner** [comment]
See the above link. It's a memory reporting bug in MacOS.

**Comment by alexpts** [comment]
> My hunch is that it has something to do with Kubernetes. I think it was all fine, until I enabled Kubernetes and then disabled it. After that, I've been experiencing all sorts of memory issues and slow downs coming from Docker process. But could be a coincidence, of course.

I think it is relate. I have a similar image

**Comment by qiangli** [comment]
> > My hunch is that it has something to do with Kubernetes. I think it was all fine, until I enabled Kubernetes and then disabled it. After that, I've been experiencing all sorts of memory issues and slow downs coming from Docker process. But could be a coincidence, of course.
> 
> I think it is relate. I have a similar image

happening to me too after enabling then disabling k8s as my disk or fan was spinning like crazy. reboot seems to bring down the memory usage to allocated size.
