### ISSUE TITLE
Kubernetes on docker-for-mac fails to pull images from ECR no basic auth credentials

### ISSUE THREAD

**Issue by innovia** [docker/for-mac#3381]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4495F17D-7E31-4851-98B9-A746C8230805/20181129144221

### Expected behavior
Pods should automatically login and pull images from ECR
### Actual behavior
ErrImagePull Get https://12345678912.dkr.ecr.us-west-2.amazonaws.com/v2/flask-demo-app/manifests/1.0.0: no basic auth credentials

### Information

  - macOS Version: 10.14.1

### Diagnostic logs

```
Docker for Mac: version...
Version 2.0.0.0-mac77 (28700)
```

### Steps to reproduce the behavior
apply a pod.yaml with an ECR image

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: web
    image: 12345678912.dkr.ecr.us-west-2.amazonaws.com/flask-demo-app:1.0.0
    command:
    - python
    args:
    - "app.py"
```

observe pod events - kubectl describe   pod flask-app
```
Events:
  Type     Reason                 Age                    From                         Message
  ----     ------                 ----                   ----                         -------
  Normal   Scheduled              4m57s                  default-scheduler            Successfully assigned flask-app to docker-for-desktop
  Normal   SuccessfulMountVolume  4m57s                  kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-9qmsp"
  Normal   Pulling                3m32s (x4 over 4m56s)  kubelet, docker-for-desktop  pulling image "12345678912.dkr.ecr.us-west-2.amazonaws.com/flask-demo-app:1.0.0"
  Warning  Failed                 3m31s (x4 over 4m55s)  kubelet, docker-for-desktop  Failed to pull image "12345678912.dkr.ecr.us-west-2.amazonaws.com/flask-demo-app:1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://12345678912.dkr.ecr.us-west-2.amazonaws.com/v2/flask-demo-app/manifests/1.0.0: no basic auth credentials
  Warning  Failed                 3m31s (x4 over 4m55s)  kubelet, docker-for-desktop  Error: ErrImagePull
  Normal   BackOff                3m4s (x6 over 4m54s)   kubelet, docker-for-desktop  Back-off pulling image "12345678912.dkr.ecr.us-west-2.amazonaws.com/flask-demo-app:1.0.0"
  Warning  Failed                 3m4s (x6 over 4m54s)   kubelet, docker-for-desktop  Error: ImagePullBackOff
```

```shell
docker pull 12345678912.dkr.ecr.us-west-2.amazonaws.com/flask-demo-app:1.0.0
1.0.0: Pulling from flask-demo-app
c67f3896b22c: Already exists
8ea0547d7723: Downloading [=====>                                             ]  33.28kB/308.3kB
c7e0a80da5a1: Pulling fs layer
48bd073cebaf: Download complete
ce8f54650fe7: Waiting
e5f0667fc6ac: Waiting
67470e7ecc24: Waiting
6fd141484534: Waiting
```

  1. ...
  2. ...

**Comment by jurgenweber** [comment]
you should be able to use the same tool as minikube, no? https://github.com/upmc-enterprises/registry-creds

**Comment by innovia** [comment]
I'll give it a try and update if it works

**Comment by jurgenweber** [comment]
I have it working, no problems.

**Comment by jeffmaher** [comment]
I'm having the exact same issue.
@innovia : Did you ever find a solution?

**Comment by BrayanArrieta** [comment]
Hello I have the same problem someone find a possible solution for this problem

**Comment by siliconavengers** [comment]
@BrayanArrieta for the `docker-for-desktop` k8s context, why not use local docker image?.

**Comment by doron-levi** [comment]
Sine no one (yet) posted a solution, I will donate my trivial workaround...

1. Pull the latest image using _docker pull_ (BTW I do manually _aws ecr get-login..._ on my mac every few hours)
2. Removed the _imagePullPolicy_ from the deployment yaml ( the default is that it will not try pull if image exists).

Now pods runs the latest...

**Comment by tzusman** [comment]
@innovia @BrayanArrieta @jeffmaher Did you find the solution?

@doron-levi Wasn't able to do it with your instruction.  Additionally, I rely on the imagePullPolicy in the production environment, so I can't remove it.

**Comment by BrayanArrieta** [comment]
Hello I tried to update to the last version, but the problem keeps. For that reason try some similar to @doron-levi.

1. Pull the image manually. Execute the aws login and pull the image.
2. Change the imagePullPolicy:ifNotPresent.

That cause that not download the image again, but in the case that you need upgrade. Must be manually again.

**Comment by tzusman** [comment]
@BrayanArrieta Thanks for the response.  That does work for me, the issue I have is when I want to do a rolling upgrade in production, changing it from `imagePullPolicy: Always` is not ideal.  But I suppose I can force it to pull the image some other way.

**Comment by jeffmaher** [comment]
@tzusman : It's been a bit, but I think the way my team wound up tackling this was with some instructions on using the local K8S secret store such that it could authenticate to ECR. I recall there being a chapter in [Kubernetes Cookbook](https://www.packtpub.com/virtualization-and-cloud/kubernetes-cookbook) to configure this. Sorry for not a ton of detail, but it was at a past gig and I don't have access to those configs to give you an easy to use example.

**Comment by rally25rs** [comment]
Anyone have a reliable way to fix this? A local `docker pull` works, but not from within k8s.

If the image is puled locally then I can get k8s to find it that way, as mentioned above, but that means I need to make some startup script that scans my yaml for images and pulls them. Seems less than ideal.

I'm guessing whatever k8s is using to pull images is just not working correctly with `"credsStore": "osxkeychain"`?

It'd be nice to have a clearly documented "this is the correct way for setting this up" like there is for docker.

**Comment by vineet3101** [comment]
nexus3ReleaseRegistry: "nexus3.abcde.org:10004"
abcdeQwertyFeImage: "abcde-qwerty-fe:2.2.22"

I was using this as in deployment.yaml as:
containers:
       - name: abcde
         image: {{ .Values.nexus3ReleaseRegistry }}/{{ abcdeQwertyFeImage }}

then i was getting error like below:

Events:
  Type     Reason     Age                    From                               Message
  ----     ------     ----                   ----                               -------
  Normal   Scheduled  9m9s                   default-scheduler                  Successfully assigned withhelm/abcde-d7669bf98-wvms9 to aks-agentpool-38663868-1
  Normal   Pulling    7m40s (x4 over 9m8s)   kubelet, aks-agentpool-38663868-1  pulling image "nexus3.abcde.org:10004/abcde-qwerty-fe:2.2.22"
  Warning  Failed     7m40s (x4 over 9m8s)   kubelet, aks-agentpool-38663868-1  Failed to pull image "nexus3.abcde.org:10004/abcde-qwerty-fe:2.2.22": rpc error: code = Unknown desc = Error response from daemon: Get https://nexus3.abcde.org:10004/v2/abcde-qwerty-fe/manifests/2.2.22: no basic auth credentials
  Warning  Failed     7m40s (x4 over 9m8s)   kubelet, aks-agentpool-38663868-1  Error: ErrImagePull
  Normal   BackOff    7m26s (x6 over 9m7s)   kubelet, aks-agentpool-38663868-1  Back-off pulling image "nexus3.abcde.org:10004/abcde-qwerty-fe:2.2.22"
  Warning  Failed     3m59s (x21 over 9m7s)  kubelet, aks-agentpool-38663868-1  Error: ImagePullBackOff
.
.
I have tried with the same docker credentials, however secrets are giving "no basic auth credentials" error.
