### ISSUE TITLE
Docker starting..... & Kubernetes is stopped

### ISSUE THREAD

**Issue by essien1990** [docker/for-mac#3383]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by abdennour** [comment]
`docker version` ?
`uname -a` ? (Darwin MacBook-Pro.local  ....)
`kubectl version` ?

**Comment by abdennour** [comment]
I fixed it.

# Brief

Add the following lines in `/etc/hosts` if it is empty.

```
127.0.0.1 localhost
::1       localhost
```

# Details:
1. Display the [log of docker](https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs):

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

2. Analyze the log: 
Found
```
2018-11-30 08:33:37.468984+0300  localhost com.docker.driver.amd64-linux[38047]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: dial tcp: lookup localhost: no such host
```
It means, it cannot resolve `localhost` ???!!

3. Check `/etc/hosts`

Oops! it is empty. 

4. Remediation

```
# cat /etc/hosts

127.0.0.1 localhost
::1       localhost
 ```

5. Watch the log again:

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

🎉 It works. k8s is now up and running with docker-for-mac.

**Comment by essien1990** [comment]
thankx  Buddy
