### ISSUE TITLE
ssh docker-for-desktop kubernetes  like "minikube ssh"

### ISSUE THREAD

**Issue by abdennour** [docker/for-mac#3384]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: No need as this is a feature request not a bug report.

### Expected behavior
There is a way to ssh to the kubernetes cluster "docker-for-desktop" similar to `minikube ssh`.

### Actual behavior
Struggling with finding a way to ssh to the kubernetes cluster created by "Docker for mac".

### Information
  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version 10.13.6 (17G2208)

```

**Comment by eliot1785** [comment]
I would also like to know this.

**Comment by droctothorpe** [comment]
Ditto

**Comment by Alyssa-Crawford** [comment]
Ditto

**Comment by dan-barrett** [comment]
+1 This would be great to have.

/remove-lifecycle stale

**Comment by NorseGaud** [comment]
Bump!
