### ISSUE TITLE
All container and images lost after upgrade

### ISSUE THREAD

**Issue by mario-paniccia** [docker/for-mac#3386]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by henning** [comment]
Same here!

I did the upgrade, then docker said it's unable to start... tried diagnostics, but nothing happened there for 3 minutes, then i went back to the previous screen.

It offered "reset to factory defaults" - and I assumed that was about *configuration* - not that it would delete *all* my data, images etc!

Good that I made a timemachine backup, but now I have to figure where the data exactly was that i need to restore.

Absolutely horrible.

**Comment by HeeJoon-Kim** [comment]
@henning  Exactly same! But, I could not find a data in my timemachine.. :(

**Comment by henning** [comment]
Where did you look and what did you look for @HeeJoon-Kim ?

**Comment by youssefgh** [comment]
Happened to me too but in linux
Turned out that i had previously moved /var/lib/docker to another directory and symlinked to the default directory, so i had to remove the new directory created as a result of the update and re-create my symlink
Hope this can help
