### ISSUE TITLE
cannot install symlinks in /usr/local/bin (stage 5)

### ISSUE THREAD

**Issue by mksrepo** [docker/for-mac#3389]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by msbit** [comment]
Also diagnostic ID 59C20769-798A-4947-9544-687285B7666D/20181206005315
