### ISSUE TITLE
Docker for Mac: version: mac-v1.12.0.1 OS X: version 10.11.6 (build: 15G31) logs: /tmp/8FE892D7-D420-4A69-A471-078E3208097D/20160818-104837.tar.gz failure: com.docker.slirp is not running

### ISSUE THREAD

**Issue by OSMeteor** [docker/for-mac#339]
### Information

Diagnostic ID: 8FE892D7-D420-4A69-A471-078E3208097D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         wrong Docker version: 1.7.0 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/meteor/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/meteor/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Volumes/Docker/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/meteor/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/8FE892D7-D420-4A69-A471-078E3208097D/20160818-104837/qemu-img-check.stdout 2> /tmp/8FE892D7-D420-4A69-A471-078E3208097D/20160818-104837/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/meteor/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/meteor/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/meteor/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/meteor/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/meteor/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
It looks like something has gone very wrong with your installation. Did you have another version of Docker installed or install another version on top of Docker for Mac? I see that the version of the command line tool is 1.7.0 which is quite old. Docker for Mac ships with 1.12.0. Have you tried uninstalling your previous Docker software and reinstalling Docker for Mac?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
