### ISSUE TITLE
Docker Not Installing Mac OS X 10.11

### ISSUE THREAD

**Issue by ujwalm** [docker/for-mac#34]
### Expected behavior
Docker CLI should have loaded.

### Actual behavior
docker is not usable from CLI

### Information

Diagnostic ID: 9E1DF185-6F1E-43F7-9A96-0935A3795F8B
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by ishouvik** [comment]
Do you have Docker toolbox installed?

**Comment by samoht** [comment]
What does `docker version` says? What is the status of Docker in the 🐳 icon? Do you have any `DOCKER_*` env variable set in you terminal? I am closing the issue for lack of information, but please re-open when you have more details so that we can help you.
