### ISSUE TITLE
Kubernetes stuck in "Kubernetes is Starting" status

### ISSUE THREAD

**Issue by xiaosongz** [docker/for-mac#3405]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D7A90969-76A1-41A5-9B09-FC3A3F556C36/20181213172113

### Expected behavior
Kubernetes ready to use.
### Actual behavior
Kubernetes stuck in "starting" stage forever. 
### Information

  - macOS Version: 10.14.2

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Walther** [comment]
Confirmed on Version 2.0.0.2 (30215), macOS Mojave 10.14.2 (18C54).

Installing Kubernetes gets stuck / doesn't seem to finish, no errors reported. Pressing "Run in background" just hides the modal but it never finishes.

Completely cleared & reinstalled Docker, still reproducible.

<img width="612" alt="screen shot 2019-01-29 at 14 47 58" src="https://user-images.githubusercontent.com/2943750/51945926-eeec1900-23d4-11e9-933c-b77f8cc6593a.png">

**Comment by ChrisJ60** [comment]
@dariodor How about telling us how you solved it?

**Comment by georgeaung** [comment]
same issue 
diagnostic ID : BB6DD2CA-B60A-4756-B4D5-615893004BEB/20190222153451

**Comment by rsnhk** [comment]
Same issue here. 
My diagnostic ID is 3A12DE83-9274-4A11-914E-BE1398EE1D88/20190309165524

**Comment by ascode** [comment]
same issue
diagnostic id: F2CE33EE-176E-4643-AADB-E153BB52F005/20190331131435
