### ISSUE TITLE
Error response from daemon: failed to prune build cache: Invalid filter 'label'

### ISSUE THREAD

**Issue by threewordphrase** [docker/for-mac#3407]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When I run `docker system prune --filter label=`, I expect to filter by label.

### Actual behavior

Docker returns an error that `label` is an invalid filter.

### Information

  - macOS Version: 10.14.1

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.0-mac81 (29211)

```

### Steps to reproduce the behavior

This issue appears to be being fixed upstream in https://github.com/docker/cli/issues/1512. Hopefully we can get that downstream asap?

**Comment by thaJeztah** [comment]
The upstream fix has not yet been released, but will be in the Docker 18.09.1 patch release.

**Comment by thaJeztah** [comment]
Docker 18.09.1 was released, so this should be fixed now
