### ISSUE TITLE
docker CLI is not working after rebooting

### ISSUE THREAD

**Issue by sehyoc** [docker/for-mac#341]
### Information

Diagnostic ID: 7931E462-1D4C-4998-B173-EE320E2DE23F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. reboot machine
2.open new terminal and type: 'docker'.

This is response:  'docker ps
Error response from daemon: Bad response from Docker engine'.

Docker works if you re-install docker from scratch

**Comment by sehyoc** [comment]
after quitting docker and restarting fixed the issue.
So docker is having problem if machine unexpectedly shutdown

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in 7931E462-1D4C-4998-B173-EE320E2DE23F/20160817-224448.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Notice>: vcpu 3 received signal, resuming
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Notice>: vcpu 2 received signal, resuming
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Notice>: vcpu 0 received signal, resuming
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Error>: VM: 2016-08-10 06:46:33 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Error>: VM: 2016-08-10 06:46:33 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Error>: VM: 2016-08-10 06:46:33 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 10 10:00:22 Sehyos-MacBook-Pro Docker[com.docker.driver.amd64-linux][17814] <Error>: VM: 2016-08-10 06:46:33 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
```
