### ISSUE TITLE
Docker does not start 

### ISSUE THREAD

**Issue by fdiazdelcastillo** [docker/for-mac#3413]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
To start normally

### Actual behavior
It does not start

### Information

  - macOS Version:
macOS Mojave Versión 10.14.1
### Diagnostic logs

```
Docker for Mac: Version 2.0.0.0-mac81 (29211)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: F1DBD432-1119-4851-A18E-B6F76681CDC6/20181217140510

**Comment by davyzhang** [comment]
rollback to older version 
![image](https://user-images.githubusercontent.com/576863/50272275-385e5580-0472-11e9-9380-2f67a60d13a3.png)

**Comment by SplitCane** [comment]
same issue with macOS Mojave Versión 10.14.2, 
BFBE2A21-D251-4B73-92AD-816A69080767/20190109150000

**Comment by furins** [comment]
same issue, OSX 10.14.2
9D43D506-1C60-4829-A73B-564D4E1A3E96/20190203151154
(this is the diagnostic for 18.06.1-ce, since I've tried to revert to older version without any luck.) Same issue with latest stable 2.0.0.2

**Comment by davyzhang** [comment]
1015C0E5-025D-4A72-82F2-55F3AB80158B/20190607152222

same problem
![image](https://user-images.githubusercontent.com/576863/59115293-2329a480-8988-11e9-92b3-d81facf29b59.png)

**Comment by phracek** [comment]
I have the same problem with `Docker version 18.09.2, build 6247962`. It shows "Docker is starting" and hangs

**Comment by phracek** [comment]
This issue seems to be solved by Docker version 19.03.1. Great!!!!!!
