### ISSUE TITLE
MacOS Mojave docker images start but wont react

### ISSUE THREAD

**Issue by audricd** [docker/for-mac#3417]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A837314B-EF44-437A-B1FF-037CAD8E68CF/20181219200221

### Expected behavior
e.g. portainer/portainer accessible at localhost:9000
### Actual behavior
cannot connect to server
### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes, every time
  - Tried AV (Dr.Web 11.1.1.201809040) ON and OFF, no changes
  - Tried ProtonVPN 1.3.0 ON and OFF, no changes
  - Is the problem new? brand new installation (OS too)
  - Did the problem appear with an update? no, everything new and fresh
  - macOS Version: Mojave

### Diagnostic logs
Diagnose succeded
Docker for Mac: 2.0.0.0-mac81 (29211) stable channel 4271b9e6a8

Steps to reproduce the behavior
1. docker pull portainer/portainer
2. docker run portainer/portainer
output is:
![screenshot 2018-12-19 at 21 33 18](https://user-images.githubusercontent.com/10130344/50246466-c3d5d900-03d5-11e9-993a-07487c3631da.png)

![screenshot 2018-12-19 at 21 34 06](https://user-images.githubusercontent.com/10130344/50246507-dea84d80-03d5-11e9-8e64-d9923caf0d45.png)

![screenshot 2018-12-19 at 21 30 56](https://user-images.githubusercontent.com/10130344/50246389-7e191080-03d5-11e9-9ba5-a50b3c9e48c3.png)

**Comment by onmomo** [comment]
We experience a similar issue. The containers are running and accessible from the host after some time (non deterministic), the host is no longer able to connect to the container. Only restarting Docker Desktop resolves the issue temporarily.

**Comment by ivester** [comment]
> We experience a similar issue. The containers are running and accessible from the host after some time (non deterministic), the host is no longer able to connect to the container. Only restarting Docker Desktop resolves the issue temporarily.
> Diagnostics ID: 2D80AB9C-9218-4705-933D-0B9B7525F15A/20190104105334

I have the same issue.

**Comment by audricd** [comment]
Unfortunately restarting docker for desktop doesnt do the trick in my case. Also, I am not convinced it is the same cause as #3448 , as in this issue it is explained, it is hard to reproduce. In this issue; it is every single time.

**Comment by guillaumerose** [comment]
You need to expose the portainer port to be able to reach it. `docker run -p 9000:9000  portainer/portainer`
