### ISSUE TITLE
Can't add /etc/hosts entries

### ISSUE THREAD

**Issue by garthk** [docker/for-mac#342]
### Expected behavior

* Ability to add entries to `/etc/hosts` in a persistent manner.

### Actual behavior

* No UI provided
* `docker run -t -i --rm -v /etc:/mnt/etc busybox vi /mnt/etc/hosts` can be used to make temporary changes to `/etc/hosts`
* Restarting Docker removes the changes

### Information

Diagnostic ID: 4168FFD0-2A6A-4390-B7B7-22F705F5FD3F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

N/A

**Comment by dsheets** [comment]
This was fixed in Beta 25 released on September 7. If you still encounter this problem, please re-open this issue. For other problems, please open a new issue. Thanks for using Docker for Mac!
