### ISSUE TITLE
Docker on Mac (Mojave) is stuck on "is starting"

### ISSUE THREAD

**Issue by TheInlineProject** [docker/for-mac#3427]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B0E0078C-AF36-45CD-A6DF-A514A2072519/20181225214357

### Actual behavior
Docker is stuck on "Docker desktop is starting" mode. 
Made few restarts and searched for other solutions here but nothing helped.
### Information

  - macOS Version: 10.14 (Mojave)

### Diagnostic logs

Diagnose succeded
```
Docker for Mac: version...
2.0.0.0-mac81
engine 18.09.0
```

### Steps to reproduce the behavior

  When simply starting Docker, it just stucks on starting mode.

**Comment by TK2575** [comment]
It appears I'm encountering the same issue. If helpful, here is an additional Diagnostic ID.
BED978B8-79D1-4D67-B6E1-3E0F12AAB084/20181227035831

**Comment by artworkjpm** [comment]
what do I do?
