### ISSUE TITLE
Can't add root certificates

### ISSUE THREAD

**Issue by garthk** [docker/for-mac#343]
### Expected behavior
- Ability to add root certificates in a persistent manner.
### Actual behavior

> ```
> $ docker pull cough:5000/whatever
> Error response from daemon: Get https://cough:5000/v1/_ping: x509: certificate signed by unknown authority`
> ```

`docker run -t -i --rm -v /etc:/mnt/etc -w /mnt/etc alpine sh` can be used to update `/etc/ssl/certs` as if `update-ca-certificates` had been run, but:
- it doesn't help Docker
- it disappears after restart

Similarly, dropping certificates into `/etc/docker/certs.d` under the `/mnt` doesn't help.
### Information

Diagnostic ID: 4168FFD0-2A6A-4390-B7B7-22F705F5FD3F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by kitsushadow** [comment]
The reference indicates docker for windows. Is the team working Docker for Mac and Docker for Windows one and the same? 

Also How far down the roadmap is this? It is critical functionality in secure workspaces.

**Comment by djs55** [comment]
We're all on the same team.

A scheme for persistent SSL certs is fairly high up our priority list. Are
these root certs in your Mac keychain (or could they be stored there?)
We're considering automatically importing root certs present on the
keychain into Moby.

**Comment by kitsushadow** [comment]
We can store the certs as part of the keychain, yes. I believe that is the intuitive "go-to" for Mac users. However, it may be easier to add them as part of the mount.

**Comment by kitsushadow** [comment]
Heard yesterday the beta update is scheduled for Sept 6 @garthk

**Comment by alvarow** [comment]
+1 here

**Comment by KevinVecchione** [comment]
Encountered this issue today on the stable track. Is this feature available in Beta as of today?

**Comment by kitsushadow** [comment]
pushed back to next beta release

**Comment by summerkai** [comment]
I also got similar issue on OSX. How to fix it?

**Comment by kitsushadow** [comment]
For now the simplest work around is to add the registries as insecure
registries.

**Comment by 486** [comment]
The access to my company's registry is only possible via HTTPS, and only with a Client Certificate. That's also a feature of `/etc/docker/certs.d` we would like to use on Mac and Windows.

**Comment by dsheets** [comment]
A patch for this is currently undergoing QA testing. Thanks for your patience.

**Comment by samoht** [comment]
Docker for Mac uses the host certificates since Beta27, so closing.

**Comment by kitsushadow** [comment]
Perhaps before closing it you could provide instructions on how to implement it...

**Comment by kitsushadow** [comment]
@samoht

**Comment by samoht** [comment]
@kitsushadow please see the docs: https://docs.docker.com/docker-for-mac/faqs/#/how-do-i-add-custom-ca-certificates

**Comment by gloomybrain** [comment]
@samoht the document you've provided says `Starting with Docker for Mac 1.12.1, 2016-09-16 (stable) ...`. I have a fresh docker installation on my Mac (1.12.1 build 12133) and I have our enterprise sertificate imported into Keychain and marked as "always trust". But I still do not have an ability to download a docker image from our private TLS-secured registry because of the `x509: certificate signed by unknown authority` error. 
Is the linked document wrong or it is a bug in the latest docker build? Or maybe there are some special (unspecified) requirements on cert importing?
Any information on this topic will be highly appreciated.

**Comment by samoht** [comment]
@gloomybrain sorry about that, our docs are wrong: CA integration with OSX keychain is only in the Beta channel (and will be in the next stable release next week).

**Comment by samoht** [comment]
I am re-opening the issue to keep track of fixing the docs.

**Comment by gloomybrain** [comment]
@samoht Thanks a lot!

**Comment by kitsushadow** [comment]
Thanks

**Comment by samoht** [comment]
btw, our docs are now hosted on https://github.com/docker/docker.github.io/tree/master/docker-for-mac so you are very welcome to open a PR to fix that error :p

**Comment by alvarow** [comment]
The docs state Docker for Mac creates a bundle based on Keychain trusted certs and passes that bundle to Moby... can you tell us how often does it do that? It is every time you start Docker for Mac, is it one time, or is it whenever it gets installed or updated?

Thanks

**Comment by ijc25** [comment]
I believe this fix was in the 1.12.3 stable release.

**Comment by valentin-krasontovitsch** [comment]
Unfortunately I'm gonna have to report on this again: original error appears with latest (at the moment) edge version, downgrade to stable fixes problem.

Unfortunately I have uninstalled edge, but if you need more information, let me know, I'll reinstall...

**Comment by tagirb** [comment]
Confirming this issue:
```
$ curl -I https://docker.<our_domain>/v2/
HTTP/2 200
...
$ docker pull docker.<our_domain>/<our_image>:latest
Error response from daemon: Get https://docker.<our_domain>/v2/: x509: certificate signed by unknown authority
$ docker --version
Docker version 17.10.0-ce, build f4ffd25
```

**Comment by SailingYYC** [comment]
I have the organizational root cert set to `Trust Always` in the `System` keychain (All Users).

I concur with @kitsushadow, Mac users and enterprises usually use mechanisms (MDM, EDM, GPO, etc.) to publish their organizational root certs into the OS's root store and should be the preferred location.

Confirming this issue as well:
```bash
$ curl -I https://docker.<our_domain>/v2/
HTTP/2 200 
...

$ docker login docker.<our_domain> -u ccyr
Password: 
Error response from daemon: Get https://docker.<our_domain>/v2/: x509: certificate signed by unknown authority

$ docker --version
Docker version 17.09.0-ce, build afdb6d4
```
