### ISSUE TITLE
Docker maxes out CPU when USB is unplugged

### ISSUE THREAD

**Issue by karimsa** [docker/for-mac#3432]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `D428E0A2-4066-4827-9DDD-A6A9D517C94D/20181231183718`

### Expected behavior

Docker realizes that the mounted volume is not available & crashes/exits.

### Actual behavior

Docker spins out of control and consumes all of the CPU on the device, freezing everything else on the computer.

### Information

  - macOS Version: `macOS Mojave (10.14.2)` (on a mid-2014 model).

### Diagnostic logs

N/a - docker is frozen. But diagnostics were manually uploaded from the shell.

### Steps to reproduce the behavior

  1. Plug in a USB drive / external HDD.
  2. Open Docker and request that the `Docker.raw` image is moved to the USB.
  3. Move the Docker app to the USB.
  4. Run docker off the USB.
  5. Unplug the USB (which sometimes automatically happens for some USB drives when the computer goes to sleep).
  6. Docker will freeze (whale icon becomes unresponsive) & if you check `top`/`htop`/activity monitor, all CPU cores are fully maxed out.

**Comment by pgayvallet** [comment]
Hello,

We are, indeed, not checking application files integrity at runtime.

Maybe just close the application before moving it ?

**Comment by karimsa** [comment]
That usually works out but is quite annoying.

I would assume that there must be file IO errors thrown within docker when this occurs, right? So is docker retrying reads continuously?
