### ISSUE TITLE
UI logged in but command line is not

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#3434]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20190102204227

### Expected behavior
Command line works with credentials from UI and `docker login` works

### Actual behavior
UI works but command line says that `docker login` needs to be run but that doesn't work

### Information
  - macOS Version: 10.14.2 (18C54)

### Diagnostic logs
```
Docker for Mac: 2.0.0.0-mac81 (29211)
```

### Steps to reproduce the behavior
  1. Run `docker login` with valid credentials (works with UI and at hub.docker.com)
  2. Observe that it says their invalid

Example:
```
> docker login -u davenm
Password: 
Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`
```

**Comment by selangh** [comment]
I just run into the same problem. 

### installed versions
```
macOS Version: 10.14.2 (18C54)
Docker for Mac: 2.0.0.2 (30215) from channel stable
docker engine: 18.09.1
```

Is there an already known workarround?

**Comment by sensay-nelson** [comment]
still having this issue also.  
docker version 18.09.02
