### ISSUE TITLE
Error when changing settings in macOS Sierra

### ISSUE THREAD

**Issue by dohzya** [docker/for-mac#344]
### Steps to reproduce

Go to the settings, check or uncheck the “Automatically start Docker when you log in” or “Automatically check for updates” checkbox.

Note: the button “Exclude VM from Time Machine backups” seems to work fine.

### Expected behavior

The checkbox state should be changed (and I hope some internal settings too) 🙂

### Actual behavior

An internal error popup appeared, with “internal error (autoStartOnLoginCheckButtonActionReceived)” or “internal error (autoCheckForUpdatesCheckButtonActionReceived)” message.

Note that after relaunching the app, the checkbox are in the desired state (uncheck if I unchecked it)

### Information

```
Diagnostic ID: 74C70E39-8070-4B90-909D-938F5F42E9DE (autoStartOnLogin)
Diagnostic ID: 8A0B09F1-F77D-4DA6-ABF5-31B60E535BA0 (autoCheckForUpdates)
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
```

**Comment by mchiang0610** [comment]
seems to be fixed in beta 25. 

We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
