### ISSUE TITLE
No execute permission on bash completion scripts

### ISSUE THREAD

**Issue by winstonhenke** [docker/for-mac#3440]
- [x] I have tried with the latest version of the Stable channel
  - [ ] I have uploaded Diagnostics

### Expected behavior

To be able to follow the directions here <https://docs.docker.com/docker-for-mac/#bash> to enable Bash completion for docker, docker-machine, and docker-compose on MacOS

### Actual behavior

/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion 
is the only script that has the execute permission flag enabled (-rwxr-xr-x)

Both
/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion
/Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion
do not have the execute permission enabled (-rw-r--r--) so they can not be executed on a new Bash session.

It's easy enough to enable the execute permission but it would likely be overridden on the next update.

### Information

  - macOS Version: 10.14.2

**Comment by guillaumerose** [comment]
Thanks for reporting, I added a ticket in our backlog. It should be fixed for the next release.

**Comment by winstonhenke** [comment]
Can just ignore this issue. They don't need the execute permission to be sourced from my .bashrc/.bash_profile. They just need the read flag which they seem to have. Not sure what I was doing when I created this.

**Comment by thaJeztah** [comment]
Yup,  correct, they don't  need to be executable 


Let me close this issue
