### ISSUE TITLE
Cant run docker after installation

### ISSUE THREAD

**Issue by Dorgalz** [docker/for-mac#3443]
### Expected behavior
working?

### Actual behavior

Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.vpnkit (pid: 2512)

### Information
Cant open docker right after installation.
Right after installation, opened and asked for privileged access to install its networking components and links to the Docker apps. After a few seconds it crash with this error message - 
Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.vpnkit (pid: 2512)

Tried to "Reset Docker to Factory defaults" - didnt helped.
Tried to check if my computer support virtualisation (as suggested from different issues) and it does.
Tried to remove and re-install multiple times - didn't helped.
Installed all mac updates - didn't helped.

  - macOS Version:

macBook pro
Os: Mojave
Processor: 2.9GHz i7
Memory: 16GB

### Diagnostic logs
Diagnostic returned nothing.

### Steps to reproduce the behavior
just installed the docker, and run it from Applications.

**Comment by kevinjayne** [comment]
Experiencing this exact issue, started yesterday, was working fine up until then...

**Comment by ekovacs** [comment]
it started and continue happening to me after jumping to latest Mac OS X Mojave. i might have to downgrade my os...
