### ISSUE TITLE
asked admin password and gave this error

### ISSUE THREAD

**Issue by dbcm** [docker/for-mac#345]
### Information

Diagnostic ID: 5B992DD9-9593-46F3-B02E-6569DF3108A3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Users/dbcm/MEOCloud/Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/dbcm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/5B992DD9-9593-46F3-B02E-6569DF3108A3/20160818-095036/qemu-img-check.stdout 2> /tmp/5B992DD9-9593-46F3-B02E-6569DF3108A3/20160818-095036/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/dbcm/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dbcm/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/dbcm/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dbcm/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/dbcm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. open Docker.app
2. enter admin password

**Comment by mchiang0610** [comment]
Sierra issues are being addressed by beta 25: https://download.docker.com/mac/beta/Docker.dmg 

We will move it into stable soon.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
