### ISSUE TITLE
Docker is not starting 

### ISSUE THREAD

**Issue by PODHUPU** [docker/for-mac#3452]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PODHUPU** [comment]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

### Actual behavior

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior


  1. ...
  2. ...

**Comment by cburman01** [comment]
Do you have an error to post?

**Comment by henning** [comment]
@PODHUPU Please, can you be more specific about what you try to achieve, what actions you take, what you expect to happen then, and what happens instead, that you classify as undesired behaviour(bug) instead? (there is also a form in the issue when you create it that is intended to be filled in...)

Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html as guidelines for reporting bugs in a way that people can help you better and improve their software.

**Comment by PODHUPU** [comment]
Hi team,

Thanks for replying.

Reason as follows.

I have update my docker and after doing that it went to starting face.

It stayed there .
Then I have uninstalled entire docker app from my Mac system and
reinstalled it.Now it works fine .


Thanks,
Avinash
