### ISSUE TITLE
Unable to start Docker

### ISSUE THREAD

**Issue by cburman01** [docker/for-mac#3454]
Expected Behavior: For docker to start 
Actual Behavior: It's not starting. 

Docker Version: 2.0.0.0-mac81 
Mac Version: 10.14.1 (18B75)

Error: 
> 2019-01-11T16:31:32Z docker + jq -e '."storage-driver"' /run/config/docker/daemon.json
> 2019-01-11T16:31:32Z docker + wait_docker_api
> 2019-01-11T16:31:32Z docker + :
> 2019-01-11T16:31:32Z docker + sleep 1
> 2019-01-11T16:31:32Z docker 2019/01/11 16:31:32 Failed to listen on AF_HVSOCK AF_HVSOCK not supported on this kernel (kernel too new?)
> 2019-01-11T16:31:32Z docker 2019/01/11 16:31:32 Listening on AF_VSOCK port ffffffff:f3a3
> 2019-01-11T16:31:32Z docker + '[' -d /var/lib/docker/aufs ]
> 2019-01-11T16:31:32Z docker + '[' -f /run/config/docker/redirect-logs ]
> 2019-01-11T16:31:32Z docker + /usr/local/bin/dockerd -H unix:///var/run/docker.sock --config-file /run/config/docker/daemon.json '--swarm-default-advertise-addr=eth0' --userland-proxy-path /usr/bin/vpnkit-expose-port
> 2019-01-11T16:31:32Z docker time="2019-01-11T16:31:32Z" level=warning msg="R

This happens on startup... I either get the option to restore to factory settings, or exit.  I was able to restore factory settings but lost all my containers and images.  After a day, I started getting this exact error again.

**Comment by fldharmabum** [comment]
Please unsubscribe me from all threads. I tried to mute the thread but it doesn’t work. Thanks.

**Comment by guillaumerose** [comment]
Can you try to create a diagnostic and submit it ? Thanks.

**Comment by cburman01** [comment]
Resolved. My docker daemon was out of space.. Increase it and it fixes the issue.
