### ISSUE TITLE
Docker for mac Extremely slow booting up on MacMojave

### ISSUE THREAD

**Issue by nezaboravi** [docker/for-mac#3456]
Docker for mac boots up extremely slow. It takes a few minutes to boot up.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6B7A992A-EC92-4AF1-BD9C-E01508A06236/25620113031819

### Expected behavior
To boot up withing second

### Actual behavior
STarting up takes few minutes

### Information

  - Is it reproducible? - every time i start docker
 
  - macOS Version: 10.14.2 MacOS Mojave

### Diagnostic logs

```
Docker for Mac: version Version 2.0.0.0-mac81 (29211)

```

### Steps to reproduce the behavior

  1. Start or restart docker for Mac

**Comment by akalata** [comment]
I'm having the same issue. After restarting my computer, Docker startup phase is at 20 minutes and counting.

- macOS version: 10.14.3
- Docker Desktop version: 2.0.0.3 (Engine 18.09.2)

**Comment by universonic** [comment]
Having same issue. Compares to older version, it seems that the boot up time is getting longer and longer by releases.

My Diagnostics ID: BBAC3948-791D-4479-95F0-D3870E79319B/20190530015653
