### ISSUE TITLE
Docker disk image corrupt after OS sleep

### ISSUE THREAD

**Issue by michalkarolik** [docker/for-mac#346]
### Actual behavior
I was just playing with docker-compose when it crashed ( I see icon in toolbar trying to restart docker.. but nothing happens.) Issue does not disappear after mac restart. 
### Information

Diagnostic ID: 22793DAD-DA1A-4151-9FD5-32FAE1C237D3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1713)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
1.Sorry, no idea ; / 
1.

**Comment by dsheets** [comment]
Unfortunately, it looks like your disk image has become corrupted. We are currently working on improving the robustness of that subsystem and so the best remedy I can offer in the meantime is `Reset to Factory Defaults`. 😕 It looks like perhaps you put your machine to sleep for about 9 minutes before the issue started occurring. Did the problem seem linked to that or was it just in the middle of a `docker-compose` run?

**Comment by michalkarolik** [comment]
"It looks like perhaps you put your machine to sleep for about 9" yes, it may be an issue here. `Reset to Factory Default` helped, good I was just playing around  ;)

**Comment by Nearhan** [comment]
This happens to mine all the time. After a couple hours of use it will start to crash. Its really annoying to download all the images again. Is there a workaround where we can reset factory settings and now have to download the images again.

Is there a lower level docker-machine type thing running so that we can just restart the VM or something. Anything would be better then to just hit reset and download all dependencies again. Big time sink

**Comment by samoht** [comment]
Detected symptom of problem 'auplink-segfault' in 22793DAD-DA1A-4151-9FD5-32FAE1C237D3/20160818-122937.

You hit an issue with the AUFS storage driver that we shipped in previous versions of Docker for Mac. You should upgrade to the latest version of the product which fixes this defect. Thanks!

May be related to docker/for-mac#7

The following log matches:
```
Aug 17 15:20:21 Michals-MacBook-Pro.local Docker[com.docker.driver.amd64-linux][15964] <Notice>: VM: 2016-08-17 13:20:21 +0000 UTC kern.info kernel: device veth86e539d left promiscuous mode
Aug 17 15:20:21 Michals-MacBook-Pro.local Docker[com.docker.driver.amd64-linux][15964] <Notice>: VM: 2016-08-17 13:20:21 +0000 UTC kern.info kernel: docker0: port 2(veth86e539d) entered disabled state
Aug 17 15:20:21 Michals-MacBook-Pro.local Docker[com.docker.driver.amd64-linux][15964] <Notice>: VM: 2016-08-17 13:20:21 +0000 UTC kern.info kernel: auplink[2591]: segfault at 7ffea3eb6198 ip 000000000043d049 sp 00007ffea3eb61a0 error 6 in auplink[400000+ca000]
Aug 17 15:20:21 Michals-MacBook-Pro.local iTerm2[com.googlecode.iterm2][255] <Warning>: Time to encode state for window <PseudoTerminal: 0x7fbfcd5bf580 tabs=3 window=<PTYWindow: 0x7fbfcd0d8080 frame=NSRect: {{2, 4}, {1915, 1170}} title=1. docker  /Users/michalkarolik/workspace/dockertutorial/mydockerbuild (docker) alpha=1.000000 isMain=1 isKey=1 isVisible=1 delegate=0x7fbfcd5bf580>>: 0.003953039646148682
Aug 17 15:20:21 Michals-MacBook-Pro.local Docker[com.docker.driver.amd64-linux][15964] <Warning>: VM: 2016-08-17 13:20:21 +0000 UTC kern.warn kernel: aufs au_plink_put:422:dockerd[1607]: pseudo-link is not flushed
```
