### ISSUE TITLE
host.docker.internal doesn't work

### ISSUE THREAD

**Issue by z2014** [docker/for-mac#3466]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
in docker container, i get `http://docker.for.mac.localhost:33333/detector/cb` or `http://host.docker.internal:33333/detector/cb`,
it should get a normal responsse
### Actual behavior
 it get response
```
{"statusCode":502,"
headers":{
"connection":"keep-alive",
"keep-alive":"timeout=10",
"x-powered-by":"TSW/Node.js",
"server":"TSW/1.2.2",
"cache-control":"no-cache",
"content-type":"text/html; 
charset=UTF-8","date":"Tue, 15 Jan 2019 12:00:07 GMT",
"transfer-encoding":"chunked"},
"request":{
"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"docker.for.mac.localhost:33333",
"port":"33333",
"hostname":"docker.for.mac.localhost",
"hash":null,
"search":null,
"query":null,
"pathname":"/detector/cb",
"path":"/detector/cb",
"href":"http://docker.for.mac.localhost:33333/detector/cb"},
"method":"POST",
"headers":{"content-type":"application/json","accept":"application/json","content-length":20967}}}
```
### Information

  - macOS Version: 10.13.4
  - docker version: 18.09.1 engine; 2.0.1.0 edge

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Matbj** [comment]
I have same problem but with the stable version 2.0.0.2 (30215) of Docker Desktop for Mac

**Comment by pgayvallet** [comment]
Hello,

```
"x-powered-by":"TSW/Node.js",
"server":"TSW/1.2.2",
```

This looks like a perfectly fine http response for a tsw server for me.

The 502 error is most certainly on your application side, not an issue on DD's dns.

**Comment by z2014** [comment]
maybe not，because i use tsw and docker on production which is built on linux is fine, the result is successfully send to host, but failed on my imac

**Comment by z2014** [comment]
when i post url `http://host.docker.internal:33333/detector/manage`, i get an error
`response============={"statusCode":502,"headers":{"connection":"keep-alive","keep-alive":"timeout=10","x-powered-by":"TSW/Node.js","server":"TSW/1.2.2","cache-control":"no-cache","content-type":"text/html; charset=UTF-8","date":"Wed, 23 Jan 2019 03:24:52 GMT","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"host.docker.internal:33333","port":"33333","hostname":"host.docker.internal","hash":null,"search":null,"query":null,"pathname":"/detector/cb","path":"/detector/cb","href":"http://host.docker.internal:33333/detector/cb"},"method":"POST","headers":{"content-type":"application/json","accept":"application/json","content-length":21413}}}`
