### ISSUE TITLE
Automatic update ("Check for Updates...") from 2.0.0.0-mac81 to 2.0.0.2 downloads malicious files

### ISSUE THREAD

**Issue by BjoernKW** [docker/for-mac#3467]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6A128C74-20FD-416E-B327-0CDB1BFD0DF6/20190115173538

### Expected behavior

Update only downloads actual Docker update files.

### Actual behavior

Update process downloads malicious files under ~/Library/Caches/com.docker.docker/org.sparkle-project.Sparkle/PersistentDownloads/zdGQwcZhk/Docker 30215/Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt

### Information

  - macOS Version: 10.14.2

### Diagnostic logs

```
Docker for Mac: Automatic update from 2.0.0.0-mac81 to 2.0.0.2

```

### Steps to reproduce the behavior

  1. Click "Check for Updates...".
  2. Suggested update to 2.0.0.2 comes up.
  3. Run update from 2.0.0.0-mac81 to 2.0.0.2
  4. Malicious files appear under ~/Library/Caches/com.docker.docker/org.sparkle-project.Sparkle/PersistentDownloads/

**Comment by n3dj0** [comment]
I cannot confirm this issue. However, I would appreciate a response by Docker

**Comment by BjoernKW** [comment]
It seems to have something to with the applications under /Applications. For some reason Docker (through Sparkle, an update framework for macOS) copies the applications under /Applications to its own cache folder. The file in question seems to be a legitimate framework used by the Bitcoin client for macOS. However, since it suddenly showed up in an expected folder I received a warning (because usually when these things happen they're cause for legitimate concern).

I'm not sure though why this behaviour is needed in the first place. After all, Docker shouldn't mess with apps installed on the local machine.
