### ISSUE TITLE
Latest Edge install breaks Kubernetes

### ISSUE THREAD

**Issue by rcordoni** [docker/for-mac#3468]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 459DBC40-39A7-4D1D-B2B6-8F7DE23F3F15/20190116002408

### Expected behavior
Upgrading from Docker for Mac (latest Edge version) to Docker Desktop 2.0.1.0 (30090) Edge should result in a working configuration where both Docker and Kubernetes are "Running".

### Actual behavior
Docker starts but Kubernetes hangs in "Kubernetes is starting" forever.

### Information

  - macOS Version:
Mojave 10.14.2

### Diagnostic logs

```
Docker for Mac: version...
Docker Desktop Community 2.0.1.0 (30090) Edge
[20190116002408.zip](https://github.com/docker/for-mac/files/2762143/20190116002408.zip)

```

### Steps to reproduce the behavior

  1. Upgrade to Docker Desktop 2.0.1.0 (30090).  Re-activate Kubernetes.  Kubernetes never starts
  2. ...

**Comment by rcordoni** [comment]
I tried to go back to the latest stable version (2.0.0.2) and I got the same problem - Kubernetes is starting but never actually starts.
I went back the the latest Edge version - this time not installing Kubernetes support.  I also deleted my ~/.kube directory in case previous settings were causing a problem.  I verified that Docker works with "docker hello-world".  It does.  I then tried to activate kubernetes.  Now it is "starting" but never starts.  Is there anything else I can try? - I am dead in the water now!

**Comment by onizo** [comment]
why did you close the issue? I'm experiencing the same problem on both stable and edge on three different newish macbook pros.

**Comment by rcordoni** [comment]
I accidentally closed this issue.  It is still a problem.  I also tried on my Macbook Pro with the same result.

**Comment by rcordoni** [comment]
I am almost certain it is the Kubernetes version 1.13.0.  One thing I noticed that even if you uninstall *everything*, Kubernetes still remains on your mac - even though there is no app - just command line.  When I try to install an earlier version of Docker for Mac, it does not overwrite the 1.13.0 version.

**Comment by rcordoni** [comment]
I found a way to go back to the stable Docker version and get back an older version of Kubernetes - WHICH WORKS.  For now, I have to stay away from Edge version 2.0.1.0/Kubernetes 1.13.  The trick to uninstall is to reset to factory defaults and then run uninstall Docker from the "Reset" screen in the Docker control panel.  Then delete Applications/Docker.app and just in case, delete ~/.docker and ~/.kube.  Now do a new install of latest stable Docker Desktop (this also has been renamed from Docker for Mac).  This time the install works and Kubernetes 1.10.11 is installed and working.

**Comment by rcordoni** [comment]
Same method works for my Macbook Pro - uninstall first and then install latest Stable 2.0.0.2.
I am still interested in finding the solution as now I am gun-shy of Edge releases.
