### ISSUE TITLE
Docker stops responding: docker-cli: docker ps failed

### ISSUE THREAD

**Issue by dunwho** [docker/for-mac#347]
### Expected behavior
Docker runs as normal, does not hang when running commands.

### Actual behavior
All commands hang indefinitely. 

### Information

Diagnostic ID: 416E671A-114C-46A7-BED1-EE802DD499F0
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Was restarting a container and it just hung there until I cancelled the action. After that, all other commands hung without response. 

Before this Docker was running without any issues. 

Restarting docker has no effect.

**Comment by dunwho** [comment]
Turning off and on docker resolved the issue. 

This involved exiting docker and then starting the app again. NOT the restart button on the docker UI

**Comment by davidlukac** [comment]
Similar behaviour here. Behaviour experienced after force-interrupting (ctrl+c) `docker-compose down` which was hanging. Turning off and back on Docker app didn't help, I had to manually kill `docker` related processes.

Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1909)

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in 416E671A-114C-46A7-BED1-EE802DD499F0/20160818-121100.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Warning>: VM: 2016-08-15 18:44:23 +0000 UTC daemon.warn chronyd: Forward time jump detected!
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Notice>: VM: 2016-08-15 18:44:23 +0000 UTC daemon.info chronyd: Can't synchronise: no selectable sources
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Error>: VM: 2016-08-15 18:44:23 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Error>: VM: 2016-08-15 18:44:23 +0000 UTC kern.error kernel: 	0-...: (1 ticks this GP) idle=ca7/1/0 softirq=6116260/6116260 fqs=0
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Error>: VM: 2016-08-15 18:44:23 +0000 UTC kern.error kernel: 	 (t=35989 jiffies g=4575742 c=4575741 q=0)
Aug 16 09:25:42 daviddonoghues-imac Docker[com.docker.driver.amd64-linux][78942] <Error>: VM: 2016-08-15 18:44:23 +0000 UTC kern.error kernel: rcu_sched kthread starved for 35989 jiffies! g4575742 c4575741 f0x0 s3 ->state=0x1
```
Analysing archive 416E671A-114C-46A7-BED1-EE802DD499F0/20160912-144801
