### ISSUE TITLE
Daemon fails with "Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9"

### ISSUE THREAD

**Issue by marcelloromani** [docker/for-mac#3473]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FDEB2B36-9E22-4A62-BD46-4B8E43938271/20190118121628

### Expected behavior
docker-compose running as usual

### Actual behavior
docker-compose runs starts the expected containers but crashes at random times with the following error message:
```
ERRO[0028] error waiting for container: EOF
ERROR: Bad response from Docker engine
```

When this happens, the docker daemon seems to have crashed: the icon in the tray bar at the top of the screen disappears and any further attempts to execute `docker` or `docker-compose` fail with the "can't connect to daemon" error message.

### Information

  - macOS Version: 10.13.6 (17G4015)

### Diagnostic logs

```
Docker for Mac: version...
Version 2.0.0.2 (30215)
Channel: stable
0b030e17ca
```

Log messages from the `Console` app:
```
fault	11:58:50.192474 +0000	Docker	CrashReport: report: Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9
error	11:58:50.418321 +0000	Docker	failed to read /System/Library/Preferences/Logging/Subsystems/com.apple.SystemConfiguration.plist: [24: Too many open files]
error	11:58:50.418365 +0000	Docker	failed to read /Library/Preferences/Logging/Subsystems/com.apple.SystemConfiguration.plist: [24: Too many open files]
default	11:58:50.419019 +0000	Docker	dnssd_clientstub ConnectToServer: socket failed 24 Too many open files
error	11:58:50.419427 +0000	Docker	nw_resolver_create_dns_service_locked DNSServiceCreateDelegateConnection failed: NoMemory(-65539)
error	11:58:50.453132 +0000	Docker	CrashReport: The operation couldn\U2019t be completed. (NSCocoaErrorDomain error 256.)
```

### Steps to reproduce the behavior

* Start Docker Desktop
* Start a container
* Expected: container runs to completion
* Actual: container starts and the daemon crashes after a pretty random amount of time. Sometimes the crash happens after a couple successful runs, sometimes it happens during the very first run after the docker daemon has been (re)started

**Comment by marcelloromani** [comment]
Reporting this made me focus on something I had overlooked at first:
```
dnssd_clientstub ConnectToServer: socket failed 24 Too many open files
```

After a bit of research on this I found:
https://github.com/mogui/MDWamp/issues/42
which in turn points to
https://forums.developer.apple.com/message/118647#118647

So it might not be a Docker issue after all, but something might be leaking file descriptor in my particular setup.

**Comment by vhf** [comment]
I'm having the exact same issue. I couldn't get a diagnostic because Docker for mac crashes before generating the diagnostic.

* Error: `Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9`
* System log
    `Jan 24 09:39:43 Docker[83830]: BUG in libdispatch client: kevent add: "Bad file descriptor" - 0x9 { 0x6000037126c0[read], ident: 4294967295 / 0xffffffff, handler: 0x7fff3c90bf18 }`
* MacOS Version: `10.14.3 (18D42)`
* Docker for mac versions that crash with this error message:
  * 2.0.0.0
  * 2.0.0.2

**Comment by ivangorbachev** [comment]
I've got the same issue after updating macos to 10.14.3 (18D109). Is there any estimation on when it'll be fixed or maybe there's a workaround?

**Comment by simula67** [comment]
Facing same issue for me also

**Comment by marcelloromani** [comment]
Installed Docker for Mac
Version 2.0.0.3 (31259)

I haven't seen the issue since then.

**Comment by sameergarg** [comment]
I am seeing this issue for Version 2.0.0.3 (31259)

**Comment by dgresko** [comment]
Not sure if this will help anyone, but I had changed the password on my machine without restarting and I think this was potentially the cause of it.  After restarting my mac, docker started working.

**Comment by yolossn** [comment]
Facing same issue in Version 2.0.0.3

**Comment by marcelloromani** [comment]
I'm wondering if this error is in some (obscure) way related to https://github.com/docker/for-mac/issues/3557#issuecomment-502324468

**Comment by kxxoling** [comment]
Meet this issue while upgrade my Macbook to macOS 10.15. Seems it's all right now after uninstall and reinstalled Docker for Mac.

**Comment by glyph** [comment]
Had this same issue a little while after updating to Catalina. Also can't generate diagnostics because the UI to do it is obscured.  It's happening with both edge and stable (started on Edge, downgraded to stable), after a factory reset and a manual factory reset (deleting Library/Containers/com.docker.docker/Data and ~/.docker entirely.)

Going to try

**Comment by marcelloromani** [comment]
Update: I'm not seeing the bug any more since installing:
Docker desktop 2.1.0.4 (39773)
macOS: 10.14.6 (18G103)

Will reopen if I see the bug again.

**Comment by Andremoniy** [comment]
It started happen again when trying to update Docker on MacOS Catalina (10.15.2 (19C57)).

**Comment by ed0906** [comment]
I am having the same issue as @Andremoniy 
I uninstalled and downloaded the latest version which didn't help

Docker version: 2.2.0.4
Engine version 19.03.8
OS: Catalina 10.15.3

**Comment by superman-lopez** [comment]
Docker version 19.03.8, build afacb8b
OS: Catalina 10.15.3

Same problem

**Comment by tgsmith61591** [comment]
@marcelloromani is it worth leaving this open as so many others continue to have this issue?

**Comment by gvazqu1** [comment]
I'm having same issue, started today

docker: 2.2.0.5
os: 10.15.4

**Comment by donvito** [comment]
I am getting this error just now and docker won't even start. Any ideas how to resolve this?

Catalina 10.15.3
I got the latest version from https://hub.docker.com/editions/community/docker-ce-desktop-mac

**Comment by marcelloromani** [comment]
Haven't seen the issue myself for a while, but reopening as it seems to affect quite a lot of people.

**Comment by abhayverma** [comment]
Facing this issue from yesterday. How do you fix it?

**Comment by ed0906** [comment]
I got rid of this error by restarting my machine. 
I’m guessing a file handle gets locked or something

**Comment by curtisdf** [comment]
I mysteriously began seeing this error today.  I don't know what I did because I didn't install any upgrades to anything, and although I was using Docker as normal (software development), same as I have been for years, I wasn't mucking with settings or doing anything unusual.

Restarting my machine did NOT help.  I got the error immediately upon booting up and logging into my desktop.

My Docker version is 2.3.0.3. While Docker is booting (but before the error appears), I'm able to do the Check for Updates option, and it says this is the latest version.

**Comment by seohyun0120** [comment]
Hi, I am facing same issue here.
Docker desktop : 2.3.0.3 (45519)
Docker engine: 19.03.8
Mac OS: Catalina 10.15.5

I also tried reinstalling and restarting docker desktop but shows the same error.

**Comment by ArseniyBorezkiy** [comment]
I have the same issue:
Docker version 19.03.8, build afacb8b
Mac OS: Catalina 10.15.5 (and not only last this last version, 3 month before updated version too had his error after docker updates in background). Docker reinstallation doest helps.

**Comment by anil-roy** [comment]
In my case

This file
~/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw

is listed as 64GB.  But it is a sparse file that reserves a quota but doesn't actually use all that space.  It can grow to that size.  

But when I did:
du -h Docker.raw

It shows up as 56GB

By doing:
docker system prune 

I ended up deleting a lot of cruff that was occupying "real" bytes on the disk.  And the update then just worked without any issues.

**Comment by warrenronsiek** [comment]
Seeing the same thing, docker version 2.3.0.4, MacOS 10.14.6.
```
lsof_docker_1598282633.log     1860
lsof_docker_1598282678.log     2735
lsof_docker_1598282725.log     3620
lsof_docker_1598282773.log     4501
lsof_docker_1598282804.log       29 << crash
lsof_docker_1598282825.log        4
lsof_docker_1598282847.log        4
lsof_docker_1598282872.log        4
lsof_docker_1598282889.log        4
lsof_docker_1598282910.log       14
lsof_docker_1598282938.log       84
lsof_docker_1598282993.log     1045
lsof_docker_1598283036.log     1803
lsof_docker_1598283077.log     2605
lsof_docker_1598283121.log     3424
lsof_docker_1598283155.log     4076
lsof_docker_1598283204.log     5127
lsof_docker_1598283234.log        5 << crash
```

**Comment by jeremysf** [comment]
I'm seeing this too. Pruning did not help. Also, when I get the "Fatal Error" dialog box, weirdly, as long as I don't close the dialog box, I can continue to use docker, but of course, if I click "Exit" then it quits docker.
