### ISSUE TITLE
Docker is not starting on mac os 10.14.2

### ISSUE THREAD

**Issue by bromanov** [docker/for-mac#3477]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 073004A5-B98D-4784-B3AF-331937C5BDA9/20190121135448

### Expected behavior
Docker starts

### Actual behavior
Docker hangs indefinitely in starting state

### Information

- reproduces about 90%, sometimes it starts but it's really a rare thing
- problem appeared with new clean installation of docker, no previous versions were installed
- https://gist.github.com/bromanov/d5cd1c628a77c977970d870785207b51 mac console log if it helps
- macOS Version: 10.14.2

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.2 (30215) stable

```

### Steps to reproduce the behavior

  1. start docker

**Comment by Yelfive** [comment]
I have a similar problem here. The difference is, I can start my docker, and even run containers, but docker daemon dies frequently, and ask me if I want to reset factory settings, which I did and did not help at all. The previous version of docker works just fine.
