### ISSUE TITLE
option to collect less user data when uploading diagnostic data

### ISSUE THREAD

**Issue by timotheecour** [docker/for-mac#3482]
> Issues without logs and details cannot be debugged, and will be closed.

N/A since this issue is about having an option to collect less user data
  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
N/A

Docker desktop occasionally crashes; however I'm reluctant to upload the diagnostic data as it contains a whole lot of information (eg all user process with command line arguments and lots of other data that isn't directly relevant to solving user issues with docker, at least in 90% cases).

Even with the stated [policy](https://docs.docker.com/docker-for-mac/faqs/#how-is-personal-data-handled-in-docker-desktop) regarding data collection, this may not be ok for everyone.

Could we please have an option to specify what gets uploaded (even if defaults are same as current). Users can always upload more if deemed necessary for solving a particular issue.

Most analog data collection from other software upload much more restricted data (eg brew gistlogs, etc)

### Information
  - Is it reproducible?
yes

  - Is the problem new?
no

  - Did the problem appear with an update?
N/A

  - macOS Version:
10.14.1

### Diagnostic logs

Docker for Mac: version...
2.0.0.2 (30215)

**Comment by henning** [comment]
It also shows my username. Might not be extremely sensitive, still, I'd prefer not to upload such data.
