### ISSUE TITLE
Unable to create a persistent volume on local hard drive

### ISSUE THREAD

**Issue by JJonesAtAvaya** [docker/for-mac#3488]
Expected behavior

I should be able to mount a local directory as a persistent volume data folder for a mysql docker container running under minikube/kubernetes

    osx 10.13.6
    Docker Desktop Community version 2.0.0.2 (30215)
    Channel: stable
    0b030e17ca
    Engine 18.09.1
    Compose: 1.23.2
    Machine 0.16.1
    Kubernetes v1.10.11
    minikube version: v0.33.1

Actual behavior
    
volume is never created and mysql daemon shuts itself down

Information

A reproducible case if this is a bug, 

Page URL if this is a docs issue or the name of a man page

Steps to reproduce the behavior
    
    install docker and enable kubernetes

create a directory on the mac to be shared as the persistent volume storage, e.g.

    sudo mkdir -m 777 -p /usr/local/var/mysql_data

deployment.yml

    # For use on docker for mac
    kind: StorageClass
    apiVersion: storage.k8s.io/v1beta1
    metadata:
      name: localstorage
    provisioner: docker.io/hostpath
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: mysql
      name: mysql-pvc
    spec:
      storageClassName: localstorage
      accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
      resources:
        requests:
          storage: 20Gi
    ---
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mysql-pv
      labels:
        type: local
    spec:
      storageClassName: localstorage
      capacity:
        storage: 20Gi
      accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
      hostPath:
        # this is the path on laptop? 
        path: "/usr/local/var/mysql_data"
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql-service
    spec:
      type: NodePort
      selector:
        app: mysql-service
      ports:
        - port: 3306
          targetPort: 3306
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mysql-server
      labels:
        app: mysql-server
    spec:
      selector:
        matchLabels:
          app: mysql-server
      template:
        metadata:
          labels:
            app: mysql-server
        spec:
          containers:
          - name: mysql-server
            image: mysql:5.7
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            ports:
            - containerPort: 3306
              name: mysql
            volumeMounts:
            - name: mysql-pvc
              # this is the path on the pod container?
              mountPath: "/mnt/data"
          volumes:
          - name: mysql-pvc
            persistentVolumeClaim:
              claimName: mysql-pvc
    
kubectl get events:

    $ kubectl get events
    LAST SEEN   FIRST SEEN   COUNT     NAME                                             KIND                    SUBOBJECT                       TYPE      REASON                 SOURCE                        MESSAGE
    3s          3s           1         mysql-pvc.157d42e97c5f10d3                       PersistentVolumeClaim                                   Normal    ExternalProvisioning   persistentvolume-controller   waiting for a volume to be created, either by external provisioner "docker.io/hostpath" or manually created by system administrator
    3s          3s           1         mysql-server-6b64c4545f-2jkxg.157d42e982fd7bb7   Pod                                                     Normal    Scheduled              default-scheduler             Successfully assigned default/mysql-server-6b64c4545f-2jkxg to minikube
    2s          2s           1         mysql-server-6b64c4545f-2jkxg.157d42e9aba444c6   Pod                     spec.containers{mysql-server}   Normal    Pulled                 kubelet, minikube             Container image "mysql:5.7" already present on machine
    2s          2s           1         mysql-server-6b64c4545f-2jkxg.157d42e9ad56e017   Pod                     spec.containers{mysql-server}   Normal    Created                kubelet, minikube             Created container
    2s          2s           1         mysql-server-6b64c4545f-2jkxg.157d42e9b50119a0   Pod                     spec.containers{mysql-server}   Normal    Started                kubelet, minikube             Started container
    19s         19s          1         mysql-server-6b64c4545f-dvhgm.157d42e5d7bfbca9   Pod                     spec.containers{mysql-server}   Normal    Killing                kubelet, minikube             Killing container with id docker://mysql-server:Need to kill Pod
    3s          3s           1         mysql-server-6b64c4545f.157d42e9818d6f0d         ReplicaSet                                              Normal    SuccessfulCreate       replicaset-controller         Created pod: mysql-server-6b64c4545f-2jkxg
    3s          3s           1         mysql-server.157d42e980840859                    Deployment                                              Normal    ScalingReplicaSet      deployment-controller         Scaled up replica set mysql-server-6b64c4545f to 1

**Comment by JJonesAtAvaya** [comment]
@thaJeztah Thanks for that information. I was hoping that was going to be the simple solution, however, if I change the hostpath to one under /Users, or /tmp for example:

I can start up the pod, connect through mysql client, create a database, but when pod shuts down, the data does not persist and there is nothing written to the mounted data folder

    kubectl create -f deployment.yml
    kubectl port-forward mysql-server-6b64c4545f-kp7h9 3306:3306
    mysql -h 127.0.0.1 -P 3306 -u root
        mysql> create database foo;
    Query OK, 1 row affected (0.00 sec)
    
    mysql> show databases;
    +--------------------+
    | Database           |
    +--------------------+
    | information_schema |
    | foo                |
    | mysql              |
    | performance_schema |
    | sys                |
    +--------------------+
    5 rows in set (0.00 sec)

**Comment by rand99** [comment]
change the mountPath to "/var/lib/mysql/" in your deployment and you're good.
mysql doesn't save the database in "/mnt/data" per default.

**Comment by vhosakot** [comment]
As @thaJeztah mentioned in comment https://github.com/docker/for-mac/issues/3488#issuecomment-457792849 above, make sure that the path on host (that needs to be mounted inside the container) is added in the list in `Preferences --> File Sharing`:

![Screen Shot 2019-06-28 at 11 34 17 AM](https://user-images.githubusercontent.com/8882663/60353962-2d442f00-9999-11e9-9fe2-01d19fea85c6.png)
