### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by thecubancrazy82** [docker/for-mac#3489]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by henning** [comment]
@thecubancrazy82 what do you expect how people can help you with an error report with not the slightest info about what really happens, when, after which actions of yourself, while you are trying to achieve what exactly - beside "Fatal Error on Mac"?

**Comment by thecubancrazy82** [comment]
Sorry I thought it will auto generate the problem. I already fixed the problem. I read someone else had a similar problem. I used the fix he/she posted and I’m ready to go. 

Thank you and I will give more information next time. My apologies.

**Comment by thecubancrazy82** [comment]
I will close it. The issue is #2037 and it was solved.

**Comment by RoyAl82** [comment]
Close: #3489

**Comment by RoyAl82** [comment]
This issue is similar to #2037
Closes #3489

**Comment by RoyAl82** [comment]
Sorry I have no idea how to close this issue in GitHub. I'm a noob in GitHub issues. Some help will be appreciated.

**Comment by henning** [comment]
@RoyAl82 are you the original reporter,  but now acting with another user id?

Do you use the web interface or some GUI tool?

I think you must act as @thecubancrazy82, the original submitter, to be allowed to close it, then, in the web UI, you should have a "close" button somewhere.

**Comment by RoyAl82** [comment]
Thank you.
