### ISSUE TITLE
Upgrade/update to docker Desktop 2.0.0.2 for Mac results in non-starting docker daemon

### ISSUE THREAD

**Issue by henning** [docker/for-mac#3491]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics - *NOT POSSIBLE BECAUSE DIAGNOSTICS DONT FINISH*
  - Diagnostics ID:

### Expected behavior

The upgrade to docker Desktop 2.0.0.2 should work seemlessly.
When they are finished docker shall start and run and be ready to  be used  as before.

### Actual behavior

After upgrading Docker Desktop on Mac Os 10.13.6, as recommended by the dialog opened by the app, Docker won't start. It says "Fatal Error. Docker daemon startup failed".

And shows a log in the console:

```
2019-01-26T02:53:27Z docker time="2019-01-26T02:53:27.206839379Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42063cc90, CONNECTING" module=grpc
2019-01-26T02:53:27Z docker + + grep -i ServerVersion
2019-01-26T02:53:27Z docker curl --unix-socket /var/run/docker.sock http/info
2019-01-26T02:53:27Z docker   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-01-26T02:53:27Z docker                                  Dload  Upload   Total   Spent    Left  Speed
2019-01-26T02:53:28Z docker 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Error starting daemon: error initializing graphdriver: driver not supported
2019-01-26T02:53:28Z docker + 
  0     0    0     0    0     0      0     failed_to_start
2019-01-26T02:53:28Z docker +  0 --:tail /var/log/docker.log
2019-01-26T02:53:28Z docker --:-- --:--:-- --:--:--     0
2019-01-26T02:53:28Z docker curl: (56) Recv failure: Connection reset by peer
```

Instead it reports it cannot start and recommends to run diagnostics. 
But diagnostics never finish. Theres just a windows "Diagnosing..." which doesn't come to an end even after more than an hour.

### Information

  - macOS Version: 10.13.6 

### Diagnostic logs

```
Docker for Mac: version 2.0.0.2
Diagnosing...
```

### Steps to reproduce the behavior

  1. Have Docker Desktop installed in lower version ( after the fact I don't know exactly what version I had *before* because that is deleted.
  2. Run the Upgrade that is offered as a dialog window by Docker Desktop itself.

# Further info:

I tried to upgrade to some docker for mac 2.0.* version already a few weeks ago, and it failed in similar /the same way. Not having enough time to analyze, i just reverted from backup. Now I tried again, in the hope a later version would have solved the issue, but it didnt.

**Comment by henning** [comment]
Maybe it has something to do with that: https://github.com/moby/moby/issues/15651

Maybe it's the aufs issue, and the solution is to find a way how to migrate docker from aufs to another storage system.

**Comment by focux** [comment]
This just happened to me. I don't think that resetting to factory should be a solution.
