### ISSUE TITLE
Docker pull - unexpected EOF (sometimes)

### ISSUE THREAD

**Issue by blacktop** [docker/for-mac#3493]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 

### Expected behavior

I should be able to download images logged in or not.

### Actual behavior

```bash
$ docker logout
Not logged in to https://index.docker.io/v1/

$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io: unexpected EOF

$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:46e71df1e5191ab8b8034c5189e325258ec44ea739bba1e5645cff83c9048ff1
Status: Image is up to date for alpine:latest

$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:46e71df1e5191ab8b8034c5189e325258ec44ea739bba1e5645cff83c9048ff1
Status: Image is up to date for alpine:latest

$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io: unexpected EOF
```
### Information

  - macOS Version: 10.14.3

### Diagnostic logs

```
Diagnose succeded

```

### Steps to reproduce the behavior

  1. docker pull alpine

**Comment by blacktop** [comment]
Is this an issue with the dockerHUB network?

**Comment by gzres** [comment]
Hello, I had similar issue on my Mac. The root of issue was in certificates installed on my machine. Check there first.

**Comment by blacktop** [comment]
How do you mean?

**Comment by gzres** [comment]
I had similar problem after generating certificates for dotnet. When I removed all certificates for localhost it started to work again.

**Comment by blacktop** [comment]
Hmmm, I don't have any certs for localhost or 127.0.0.1 🤔

**Comment by hithwen** [comment]
I have the same issue on mac 10.14.6, docker 19.03.5

**Comment by gffuma** [comment]
> I have the same issue on mac 10.14.6, docker 19.03.5

@hithwen I have the same issue on the same docker mac version. After days of headache i simply burn all  images and everything goes ok:
```sh
docker image rm --force $(docker images -a -q)
```

**Comment by anandpaithankar1** [comment]
We have seen this issue on the Linux machines as well. Although the suggestion by @gffuma works but the issue surfaces again randomly.

**Comment by xiangwangcheng** [comment]
Same issue here on Mac.
I was usging minikue, still can not pull any image from docker hub though I have already set the proxy(and the proxy has no problem)

![image](https://user-images.githubusercontent.com/8049014/77714198-676b5b80-7013-11ea-86f4-01d00f7affe2.png)

**Comment by smarwei** [comment]
The problem seems to not only appear on Mac.
On Windows 10:
![image](https://user-images.githubusercontent.com/9263007/78420018-b6d10d80-764b-11ea-8700-a569ac586f51.png)
![image](https://user-images.githubusercontent.com/9263007/78420036-d9fbbd00-764b-11ea-83ae-5aaf020d27eb.png)

**Comment by BeatDirector** [comment]
I have this issue on Windows 10 only with LAN connection on my PC and laptop as well.
But no issues with WIFI connected to the same router. How is that possible?
I tried to use different LAN cables without success.

`$ docker run hello-world`
Got that error message:
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https:
//auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: unexpected EOF.
See 'docker run --help'.

**Comment by simonberger** [comment]
> I have this issue on Windows 10 only with LAN connection on my PC and laptop as well.
> But no issues with WIFI connected to the same router. How is that possible?
> I tried to use different LAN cables without success.

Interesting information. I am on Windows 10 as well and my PC has a WIFI card. I tried it and in my case it failed there as well.
I tried version 2.1.0.0, 2.2.0.0 2.2.3.0 always the same Unexpected EOF error.

**Comment by BeatDirector** [comment]
> > I have this issue on Windows 10 only with LAN connection on my PC and laptop as well.
> > But no issues with WIFI connected to the same router. How is that possible?
> > I tried to use different LAN cables without success.
> 
> Interesting information. I am on Windows 10 as well and my PC has a WIFI card. I tried it and in my case it failed there also.
> I tried version 2.1.0.0, 2.2.0.0 2.2.3.0 always the same Unexpected EOF error.

Thanks for testing Simon. I tried it in a different house with a different internet provider. Here at the other place it works both, LAN and WIFI. Looks like my Fritzbox 6591 cable or Vodafone is blocking LAN connection. Or maybe it's my LAN adapter Intel I219-V. What about your hardware, Simon? Who is your provider?

**Comment by simonberger** [comment]
@BeatDirector I have cable Vodafone as well and the new Fritzbox 6660 as my own router.
Today I'll try it on my laptop (on same internet).

**Comment by BeatDirector** [comment]
@simonberger Now that's interesting, Vodafone and Fritzbox on LAN doesn't work but 1&1 DSL on LAN works for me. Later I'll check in another Vodafone household with standard Unitymedia modem.

**Comment by simonberger** [comment]
Ok I now ran my notebook which has Windows Home. Docker 2.2.3 can run there bot only on Windows Build 19018. I updated to Windows Insider 2004 and it worked.
Unfortunately same error at the end !

Just to make sure. For my Wifi did and does not help on both machines.
I'll have a look what I can maybe change in the router.

**Comment by BeatDirector** [comment]
Just tested on a Vodafone connection with standard modem and it worked both LAN and WIFI. It looks like an issue with Fritzboxes as modem/router. Maybe firmware or some kind of filter/firewall issue. Would be great if we had more test candidates who could confirm issue with Vodafone, Fritzbox and LAN.

**Comment by simonberger** [comment]
I now started a mobile hotspot from my mobile phone with not the best LTE signal and I could pull the first image on my notebook.
This shows it is either the router or the cable internet provider.

**Comment by NoZomIBK** [comment]
I have the same Issue on Windows. Also Vodafone + Fritzbox + LAN.
using docker desktop 2.2.0.5

using browser or curl seems to return a proper json (auth and retrieving the image metadata with the auth token)

So either the docker client has some strange problem with these calls itself or the error happens on downloading the layers, which can not be presumed by the error message

Can someone reopen the issue, since it still seems to be a problem

**Comment by smarwei** [comment]
Interesting. My provider is Unitymedia which is now the same as vodafone. 
I also noticed, that I can login if I switch to Windows containers for some reason.

**Comment by BeatDirector** [comment]
Yes, Vodafone, Unitymedia and Kabel-BW is the same company. They are using branded Fritzbox router models which have modified firmware with less options. You can't update firmware by yourself to official AVM releases. Maybe there are some bugs or "features" provided by the company with current name Vodafone. I'm curious if this issue also happen to retail cable Fritzbox models with original AVM firmware. Would be great if someone could confirm.

**Comment by simonberger** [comment]
My router is no branded one. It is bought model in open market.

**Comment by simonberger** [comment]
Docker Desktop 2.2.0.5 on MAC works in the same network which means this is not the initial problem. We should continue this in https://github.com/docker/for-win/issues/6233 where I also uploaded a diagnostic ID.

**Comment by stephen-turner** [comment]
If it's being blocked by the router, I don't see what we can do. It sounds like you need to consult the manufacturers of the FritzBox.

**Comment by BeatDirector** [comment]
Got a brand new Fritzbox router today. Now everything is working fine over LAN and WIFI. Seems like hardware or firmware issue of Fritzbox.

**Comment by smarwei** [comment]
@BeatDirector Mine is about a month old. Did you get the 6591?

**Comment by BeatDirector** [comment]
> @BeatDirector Mine is about a month old. Did you get the 6591?

Yes, I got the 6591 cable again.

**Comment by jonas-jonas** [comment]
I have the Fritzbox 6591 too, as well as Vodafone ISP using internet via TP-Link DLAN adapters. Same issue. Do you have a workaround? I'm on a PC, so I can't use WIFI.

**Comment by stephen-turner** [comment]
Several reports in docker/for-win#6233 that restarting the FritzBox fixes it.

**Comment by hhauschild** [comment]
Using a VPN solved the problem for me. Just restarting the FritzBox did not help.

**Comment by gingters** [comment]
I figured out a work-around for me:

Go to FritzBox support options. Set view to advanced first (Ansicht: Erweitert), then go to table of contents (Inhalt) on the very bottom left menu, and on the bottom left of the ToC content area click on "FRITZ!Box Support".

On that page you'll see a section "Packet acceleration" (Paketbeschleunigung) with two option: Packet acceleration and hardware acceleration.

Try disabling hardware acceleration, save settings (button on the right), and then re-try downloading the image.

After the download make sure to enable hardware acceleration again, as this is limiting your available bandwidth (I went down to 150 mbs from 1gbps by disabling it).

Additional info: I figured that out after I noticed that not only docker image downloads have this issue, but also a game download where the game files are hosted on Amazon S3, and most of the requests timed out.

So there seems to be some issue with the Fritz!Box hardware packet acceleration handling packets that come from Amazon. With a VPN enabled the packets are tunneled and not directly seen by the chip. Vodafone (KabelBW) support said another customer reported that fixed after his FritzBox was changed, so it might be a faulty chip. I will get a new box too, so I'll report back when I got the replacement and tell if that helped or not.

**Comment by LazyProphet** [comment]
Awesome! You saved my day! Please report, if the replacement box is fixed.

**Comment by hlaebe** [comment]
I can confirm that it is due to the setting in question. However, this problem only occurs with Fritz OS 7.13, which came via auto update from Vodafone in the last days. With Fritz OS 7.03 I did not have this problem.

**Comment by gingters** [comment]
> Awesome! You saved my day! Please report, if the replacement box is fixed.

That's a negative. Got the new box, same issue. So I think it has something to do with the current firmware.
I'm going to contact AVM again on this. Last time they said I should try the latest lab firmware, but I can't due to the box being pre-provisioned by Vodafone. I will, however, provide them with detailed steps to reproduce and a video that show's the issue in detail.

**Comment by gingters** [comment]
> Update:
> It works on my linux box attached to the same Fritz box ! So, looks to me like it's more Windows related...

I pulled out the old mac I had lying around: With the mac it works. So it somehow is also related to Windows and the packet accelleration.
So far I did not hear back from AVM and Vodafone.

**Comment by simonberger** [comment]
I noticed this in https://github.com/docker/for-mac/issues/3493#issuecomment-609498175 as well.
Reason this should be further discussed in the windows issue and not here.
Unfortunately the issue had been closed as well. Yes the problems seem to exist only with Cable + Fritzbox but this does not mean the docker windows application has no problem.
My setup works after the router restart.

**Comment by arglgruml** [comment]
Using a Fritz!Box 6591 Cable, Firmware Version 7.13  I can confirm that turning off hardware packet acceleration immediatly fixes an EOL error when pulling an image. A restart of the FritzBox fixes the problem too, but only for a limited time.

I haven't had any problem with the previous firmware release - but noch up-/downgrades are possible because of the cable provider prohbiting firmware changes.

> So far I did not hear back from AVM and Vodafone.

I had a chat with a support technician and he told me:
> Bei der FRITZ!Box 6591 Cable wurden uns vereinzelt schon Hinweise gegeben, dass die Hardwarebeschleunigung dazu führt, dass Programme/Geräte teilweise nicht mehr funktionieren. 

> Roughly translated: "We had some reports that some programs dont work with activated hardware acceleration"

**Comment by arglgruml** [comment]
I recieved a reply from from AVM. They confirmed a known issue and promised a fix in an upcoming release.

@gingters @BeatDirector @simonberger

**Comment by LordReaver** [comment]
I don't know how I got here but finally after 10 hours of frustration and doubting myself and my whole existence I found this post and unchecking this function in my fritzbox did in fact solve all my issues.
Still can't believe it

**Comment by statist32** [comment]
@LordReaver same for me. I researched for about 5 hours ...

**Comment by hlaebe** [comment]
> I recieved a reply from from AVM. They confirmed a known issue and promised a fix in an upcoming release.

Well, then hopefully it doesn't take as long as usual for updating the box by my provider (vodafone) 🙄

**Comment by statist32** [comment]
They've rolled out a new version and now I am able to pull images with activated hardware acceleration

**Comment by pauschuu** [comment]
> They've rolled out a new version and now I am able to pull images with activated hardware acceleration

Hey, thanks for this information.
Can you clarify:
they = docker 
they = avm
?

**Comment by gingters** [comment]
They = avm.
Obviously AVM released a new (Lab- / Preview-?) Firmware for the router.
I hope for my Vodafone branded router (where I can't update manually) that the new version will be officially released and adopted by the cable provider soon to get rid of that issue.

**Comment by pauschuu** [comment]
Thanks for the clarification. Can anyone else confirm this maybe?

**Comment by LordReaver** [comment]
Sorry but I'm using a Vodafone branded box, too... it can take months or years for them to release the update.

**Comment by vietd24** [comment]
> They've rolled out a new version and now I am able to pull images with activated hardware acceleration

Which version are you currently on. I have a Fritzbox 6660 as well with version 7.15 and still have the same issues. (my linux server works somehow, windows fails as well) Only workaraound is disabling the hardware acceleration.

**Comment by statist32** [comment]
> 
> 
> > They've rolled out a new version and now I am able to pull images with activated hardware acceleration
> > @statist32
> 
> Which version are you currently on. I have a Fritzbox 6660 as well with version 7.15 and still have the same issues. (my linux server works somehow, windows fails as well) Only workaraound is disabling the hardware acceleration.

I can pull images via wsl2 and cmd. 

WindowsVersion: 10.0.19041 Build 19041 
DockerEngine: v19.03.08
Fritz: 6660 Cable with v7.15

**Comment by binaryangel-noa** [comment]
I installed the currently latest labs firmware version (7.19) and the problem still occurs. I am running Docker on Windows too and have this issue as well with the current stable version (7.15).

PS. Thanks for writting about this issue here and how to resolve it.
