### ISSUE TITLE
com.docker.hyperkit takes 40%-50% CPU to do absolutely nothing at all

### ISSUE THREAD

**Issue by joshuawwbrown** [docker/for-mac#3495]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 036983B4-5CCD-4822-B733-C8C05E9D6BCD/20190130101448

### Expected behavior

Docker should take little CPU when no containers are running and Kubernetes is not enabled

### Actual behavior

com.docker.hyperkit takes 40%-50% CPU to do absolutely nothing at all

### Information

Docker Desktop
Version 2.0.0.2 (30215)
Channel: stable
0b030e17ca
Engine: 18.09.1
Compose: 1.23.2
Machine: 0.16.1
Notary: 0.6.1
Credential Helper: 0.6.0
Kubernetes: v1.10.11

This is reproducible. It works every time.

**Comment by EduardoLeonMiranda** [comment]
+1

**Comment by im-kulikov** [comment]
looks like problem with `dockerd` / `containerd` inside `com.docker.hyperkit`

screenshot from docker-mac:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/888650/52532119-ac113600-2d30-11e9-904d-7a1769d639a7.png">

but I didn't run anything in the Docker.

**Comment by salokanto** [comment]
It's not quite that bad for me, but it's taking about 6% to 10% CPU all the time, no containers running. 

You don't notice that when running on AC power, but it drains battery pretty fast. Docker is constantly the no 1 on the Energy tab in Activity monitor.

Docker Desktop 2.0.0.2 (31259)
Channel: stable
8858db33c8

No containers running:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by vdboor** [comment]
It's even running 65-70% of CPU on my mac.

Opening the hidden hyperkit VM does not reveal that much either.
I've tried:

```
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
export COLUMNS=200 ROWS=80
pstree
top  # P for sorting by CPU
tail -f /var/log/*.log
````

(the screen can be closed with `ctrl` + `a \`)

When there are incomplete containers, kubelet does appear to be very occupied by this (running `docker system prune -f` fixed that). Yet my CPU usage remains at 65-70%
