### ISSUE TITLE
docker run doesn't work, keep issues "structure needs cleaning"

### ISSUE THREAD

**Issue by deadjoe** [docker/for-mac#35]
### Expected behavior

docker run -p 8080:8080 -p 50000:50000 -v /Users/joe/jenkins_home:/var/jenkins_home jenkins

### Actual behavior
docker run -p 8080:8080 -p 50000:50000 -v /Users/joe/jenkins_home:/var/jenkins_home jenkins
Unable to find image 'jenkins:latest' locally
latest: Pulling from library/jenkins
5c90d4a2d1a8: Pulling fs layer
ab30c63719b1: Pulling fs layer
c6072700a242: Pulling fs layer
5f444d070427: Waiting
620b5227cf38: Waiting
3cfd33220efa: Waiting
864a98a84dd2: Waiting
734cc28150de: Waiting
83a54d30c146: Waiting
ed85ef8f0008: Waiting
2a8cac69db6b: Waiting
48492da1052e: Waiting
ef7ab6cf01e2: Waiting
3ca6002e0b34: Waiting
52763f8fd3fb: Waiting
6f3d535bd7f9: Waiting
78ea3baad232: Waiting
4459c86d81aa: Waiting
**docker: open /var/lib/docker/tmp/GetImageBlob027034255: structure needs cleaning.**

### Information

Diagnostic ID: 1E7D444B-1C9A-4650-BE0C-9A866996623E
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. docker run -p 8080:8080 -p 50000:50000 -v /Users/joe/jenkins_home:/var/jenkins_home jenkins

**Comment by deadjoe** [comment]
the syslog -k Sender Docker output is as below:

Jul 31 11:52:52 bearbone-2 Docker[47021] <Notice>: Docker is responding
Jul 31 11:52:52 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:52 +0000 UTC daemon.info vsudd: Connection 2 to: 2376 from: 00000000
Jul 31 11:52:52 bearbone-2 Docker[47020] <Notice>: VM started at 2016-07-31 11:52:52 +0800 CST
Jul 31 11:52:52 bearbone-2 Docker[46992] <Notice>: dockerState = Starting
Jul 31 11:52:52 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:52 +0000 UTC daemon.info init: starting pid 1721, tty '/dev/ttyS0': '/sbin/getty -L 115200 ttyS0 vt100'
Jul 31 11:52:53 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:53 +0000 UTC daemon.info vsudd: Connection 3 to: 2376 from: 00000000
Jul 31 11:52:54 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:53 +0000 UTC daemon.info vsudd: Connection 4 to: 2376 from: 00000000
Jul 31 11:52:54 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:53 +0000 UTC daemon.info vsudd: 4 Done. read: 96 written: 141
Jul 31 11:52:54 bearbone-2 Docker[47045] <Notice>: EOF reading packet from Unix domain socket: closing
Jul 31 11:52:54 bearbone-2 Docker[47045] <Critical>: Failed to read hello from client
Jul 31 11:52:54 bearbone-2 Docker[47019] <Error>: failed to establish 9P connection: Caught EOF on underlying FLOW
Jul 31 11:52:54 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:54 +0000 UTC daemon.info diagnostics: Running /bin/cat
--- last message repeated 27 times ---
Jul 31 11:52:54 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:54 +0000 UTC daemon.info diagnostics: Running /usr/bin/tail
--- last message repeated 2 times ---
Jul 31 11:52:55 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:52:55 +0000 UTC daemon.info chronyd: Selected source 192.168.65.1
Jul 31 11:52:55 bearbone-2 Docker[47021] <Warning>: VM: 2016-07-31 03:52:55 +0000 UTC kern.warn kernel: Adjusting tsc more than 11% (7520935 vs 7184318)
Jul 31 11:53:24 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:24 +0000 UTC daemon.info vsudd: Connection 5 to: 2376 from: 00000000
Jul 31 11:53:24 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:24 +0000 UTC daemon.info vsudd: 5 Done. read: 8681 written: 190
Jul 31 11:53:24 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:24 +0000 UTC daemon.info vsudd: Connection 6 to: 2376 from: 00000000
Jul 31 11:53:24 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:24 +0000 UTC daemon.info vsudd: 6 Done. read: 85 written: 8989
Jul 31 11:53:24 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:24 +0000 UTC daemon.info vsudd: Connection 7 to: 2376 from: 00000000
Jul 31 11:53:41 bearbone-2 Docker[47021] <Error>: VM: 2016-07-31 03:53:41 +0000 UTC kern.crit kernel: EXT4-fs error (device vda2): ext4_find_dest_de:1809: inode #1179658: block 4726823: comm dockerd: bad entry in directory: rec_len is smaller than minimal - offset=0(0), inode=16877, rec_len=8, name_len=0
--- last message repeated 9 times ---
Jul 31 11:53:44 bearbone-2 Docker[47021] <Notice>: VM: 2016-07-31 03:53:44 +0000 UTC daemon.info vsudd: 7 Done. read: 308 written: 2814

**Comment by samoht** [comment]
This looks like a disk corruption issue. Do you have a way to reproduce that reliably? If you delete and re-create the image, does it work better? Did you try to change the underlying storage drivers?

**Comment by deadjoe** [comment]
On my mac it can be reproduce every time. When error happened, there is no any image downloaded successfully so there is no images reported by the command 'docker images'. I did not change the storage drivers, Just download the latest docker for mac, install to Application folder and use it directly in my console.

**Comment by deadjoe** [comment]
Today the docker for mac prompted upgrade and i did upgrade and tried again. The error still there. Below are my docker information for your reference.

![image](https://cloud.githubusercontent.com/assets/2519527/17595923/b9296a80-6021-11e6-9142-2b9e01f337ea.png)

~ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

~ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
➜  ~ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

~ docker pull jenkins
Using default tag: latest
latest: Pulling from library/jenkins

357ea8c3d80b: Pulling fs layer
52befadefd24: Pulling fs layer
3c0732d5313c: Pulling fs layer
557cb7f84eb9: Waiting
831d48be5871: Waiting
fecf7eeb197d: Waiting
b987bd349aa0: Waiting
cc0734289976: Waiting
7ac301e69a2b: Waiting
bfa103a9ed52: Waiting
e952ed582486: Waiting
2f00ad2280d4: Waiting
d0cde79aa7df: Waiting
035f426a7a34: Waiting
5ed1475e2cab: Waiting
f727a3a21c9a: Waiting
14319f547d4c: Waiting
00034ec7a38e: Waiting
cf8f8c6b4353: Waiting
open /var/lib/docker/tmp/GetImageBlob021059603: structure needs cleaning

**Comment by deadjoe** [comment]
~ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: RZWG:Y6WC:H7JB:CA53:7DI4:FD6T:M5A5:D55G:XPJE:V7EZ:64Z5:JHFA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2016-08-11T16:17:41.344969112Z
 EventsListeners: 1
No Proxy: 127.0.0.1,upaiyun.com,*.upaiyun.com,tmall.com,*.tmall.com,pps.tv,*.pps.tv,ku6cdn.com,*.ku6cdn.com,ess.apple.com,*.ess.apple.com,caing.com,*.caing.com,baixing.com,*.baixing.com,yihaodianimg.com,*.yihaodianimg.com,steampowered.com,*.steampowered.com,onlinedown.net,*.onlinedown.net,ioslb.net,*.ioslb.net,diandian.com,*.diandian.com,58.com,*.58.com,bilibili.tv,*.bilibili.tv,xiachufang.com,*.xiachufang.com,sfbuy.com,*.sfbuy.com,mediav.com,*.mediav.com,hao123.com,*.hao123.com,cnblogs.com,*.cnblogs.com,alipayobjects.com,*.alipayobjects.com,verisign.com,*.verisign.com,qq.com,*.qq.com,letv.com,*.letv.com,fengniao.com,*.fengniao.com,chinacache.net,*.chinacache.net,blogchina.com,*.blogchina.com,zaobao.com,*.zaobao.com,taobao.com,*.taobao.com,pcbeta.com,*.pcbeta.com,juetuzhi.net,*.juetuzhi.net,duapp.com,*.duapp.com,51job.com,*.51job.com,atpanel.com,*.atpanel.com,xitek.com,*.xitek.com,soku.com,*.soku.com,mzstatic.com,*.mzstatic.com,iask.com,*.iask.com,ctrip.com,*.ctrip.com,24quan.com,*.24quan.com,webscache.com,*.webscache.com,sandai.net,*.sandai.net,localhost,*.localhost,go2map.com,*.go2map.com,chiphell.com,*.chiphell.com,123cha.com,*.123cha.com,115img.com,*.115img.com,0.0.0.0/0,ttg.im,*.ttg.im,ppsimg.com,*.ppsimg.com,ku6img.com,*.ku6img.com,et8.org,*.et8.org,ccb.com,*.ccb.com,ykimg.com,*.ykimg.com,suning.com,*.suning.com,oopmei.com,*.oopmei.com,ip138.com,*.ip138.com,dianping.com,*.dianping.com,360buy.com,*.360buy.com,xiami.com,*.xiami.com,shifen.com,*.shifen.com,meishichina.com,*.meishichina.com,hi-pda.com,*.hi-pda.com,cntv.net,*.cntv.net,alipay.com,*.alipay.com,verycd.com,*.verycd.com,qqmail.com,*.qqmail.com,letvcdn.com,*.letvcdn.com,footprint.net,*.footprint.net,chinahr.com,*.chinahr.com,aliyuncs.com,*.aliyuncs.com,zdic.net,*.zdic.net,taobaocdn.com,*.taobaocdn.com,pchome.net,*.pchome.net,kaixin001.com,*.kaixin001.com,eastmoney.com,*.eastmoney.com,51.com,*.51.com,xunlei.com,*.xunlei.com,soso.com,*.soso.com,nbweekly.com,*.nbweekly.com,iciba.com,*.iciba.com,d4e.org,*.d4e.org,admin5.com,*.admin5.com,weibo.com,*.weibo.com,sanguosha.com,*.sanguosha.com,logmein.com,*.logmein.com,gokuai.com,*.gokuai.com,cmbchina.com,*.cmbchina.com,126.com,*.126.com,0.0.0.0/32,ttmimg.com,*.ttmimg.com,ppstream.com,*.ppstream.com,kuaidi100.com,*.kuaidi100.com,etao.com,*.etao.com,ccgslb.net,*.ccgslb.net,bjbus.com,*.bjbus.com,ynet.com,*.ynet.com,swan.im,*.swan.im,oschina.net,*.oschina.net,iqiyi.com,*.iqiyi.com,discuz.net,*.discuz.net,360buyimg.com,*.360buyimg.com,allyes.com,*.allyes.com,xiami.net,*.xiami.net,sicunxiang.com,*.sicunxiang.com,meituan.com,*.meituan.com,hiapk.com,*.hiapk.com,cnzz.com,*.cnzz.com,alimama.com,*.alimama.com,verylohas.com,*.verylohas.com,qunar.com,*.qunar.com,linode.com,*.linode.com,frdic.com,*.frdic.com,chinamobile.com,*.chinamobile.com,zhaopin.com,*.zhaopin.com,tdimg.com,*.tdimg.com,pcpop.com,*.pcpop.com,kandian.com,*.kandian.com,ecitic.com,*.ecitic.com,51cto.com,*.51cto.com,appinn.com,*.appinn.com,ydstatic.com,*.ydstatic.com,soufun.com,*.soufun.com,netease.com,*.netease.com,icloud.com,*.icloud.com,dangdang.com,*.dangdang.com,acfun.tv,*.acfun.tv,weiphone.com,*.weiphone.com,sdo.com,*.sdo.com,lxdns.com,*.lxdns.com,goodbabygroup.com,*.goodbabygroup.com,cmpay.com,*.cmpay.com,126.net,*.126.net,*.cn,images-amazon.com,*.images-amazon.com,tudou.com,*.tudou.com,pptv.com,*.pptv.com,lampdrive.com,*.lampdrive.com,eudic.net,*.eudic.net,cctv.com,*.cctv.com,bdstatic.com,*.bdstatic.com,youdao.com,*.youdao.com,synacast.com,*.synacast.com,p.net.co,*.p.net.co,it168.com,*.it168.com,donews.com,*.donews.com,56img.com,*.56img.com,xici.net,*.xici.net,sina.com,*.sina.com,mmstat.com,*.mmstat.com,highbd.net,*.highbd.net,comsenz.com,*.comsenz.com,aliimg.com,*.aliimg.com,vmall.com,*.vmall.com,qvbuy.com,*.qvbuy.com,lm.licenses.adobe.com,*.lm.licenses.adobe.com,ganji.com,*.ganji.com,chinanews.com,*.chinanews.com,baifubao.com,*.baifubao.com,zhi.hu,*.zhi.hu,tenpay.com,*.tenpay.com,pengyou.com,*.pengyou.com,kankan.com,*.kankan.com,edgens.com,*.edgens.com,51img1.com,*.51img1.com,baidupcs.com,*.baidupcs.com,yesky.com,*.yesky.com,soufunimg.com,*.soufunimg.com,niuza.com,*.niuza.com,idailyapp.com,*.idailyapp.com,daqi.com,*.daqi.com,abchina.com,*.abchina.com,womai.com,*.womai.com,serverspeeder.com,*.serverspeeder.com,manzuo.com,*.manzuo.com,gougou.com,*.gougou.com,cn.ls.apple.com,*.cn.ls.apple.com,aliyun.com,*.aliyun.com,tudouui.com,*.tudouui.com,qbox.me,*.qbox.me,lashou.com,*.lashou.com,everbox.com,*.everbox.com,cctvpic.com,*.cctvpic.com,youku.com,*.youku.com,t2io.com,*.t2io.com,paipai.com,*.paipai.com,jandan.net,*.jandan.net,douban.com,*.douban.com,39.net,*.39.net,blogbus.com,*.blogbus.com,xilu.com,*.xilu.com,sinaimg.com,*.sinaimg.com,mop.com,*.mop.com,huanqiu.com,*.huanqiu.com,csair.com,*.csair.com,alicdn.com,*.alicdn.com,vr.org,*.vr.org,qwapi.com,*.qwapi.com,lmlicenses.wip4.adobe.com,*.lmlicenses.wip4.adobe.com,gfan.com,*.gfan.com,chinaren.com,*.chinaren.com,zhihu.com,*.zhihu.com,tgbus.com,*.tgbus.com,phpwind.net,*.phpwind.net,kickoffapp.com,*.kickoffapp.com,elong.com,*.elong.com,blueidea.com,*.blueidea.com,yhd.com,*.yhd.com,speedtest.net,*.speedtest.net,nuomi.com,*.nuomi.com,img-space.com,*.img-space.com,dbank.com,*.dbank.com,265.com,*.265.com,baidu.com,*.baidu.com,wosign.com,*.wosign.com,sf-express.com,*.sf-express.com,mapabc.com,*.mapabc.com,gtimg.com,*.gtimg.com,cnberg.com,*.cnberg.com,alisoft.com,*.alisoft.com,uusee.com,*.uusee.com,qiyi.com,*.qiyi.com,lashouimg.com,*.lashouimg.com,eyoudi.com,*.eyoudi.com,china.com,*.china.com,10050.net,*.10050.net,yupoo.com,*.yupoo.com,tankr.net,*.tankr.net,paypal.com,*.paypal.com,jd.com,*.jd.com,dpfile.com,*.dpfile.com,56.com,*.56.com,xinhuanet.com,*.xinhuanet.com,sogou.com,*.sogou.com,mtime.com,*.mtime.com,hudong.com,*.hudong.com,csdn.net,*.csdn.net,alibaba.com,*.alibaba.com,wandoujia.com,*.wandoujia.com,renren.com,*.renren.com,local,*.local,gfw.io,*.gfw.io,chinaunix.net,*.chinaunix.net,zhimg.com,*.zhimg.com,tlgslb.com,*.tlgslb.com,pplive.com,*.pplive.com,ku6.com,*.ku6.com,emarbox.com,*.emarbox.com,bokee.net,*.bokee.net,bdimg.com,*.bdimg.com,yihaodian.com,*.yihaodian.com,static.hdslb.com,*.static.hdslb.com,ocsp.startssl.com,*.ocsp.startssl.com,infzm.com,*.infzm.com,dchina.org,*.dchina.org,91.com,*.91.com,x.com,*.x.com,sfbest.com,*.sfbest.com,mapbar.com,*.mapbar.com,guokr.com,*.guokr.com,cnbeta.com,*.cnbeta.com,163.com,*.163.com,vcimg.com,*.vcimg.com,qiyipic.com,*.qiyipic.com,letao.com,*.letao.com,fastif.net,*.fastif.net,chinabyte.com,*.chinabyte.com,115.com,*.115.com,yyets.com,*.yyets.com,tanx.com,*.tanx.com,paypalobjects.com,*.paypalobjects.com,jiepang.com,*.jiepang.com,dream4ever.org,*.dream4ever.org,51jobcdn.com,*.51jobcdn.com,10010.com,*.10010.com,xinnet.com,*.xinnet.com,sohu.com,*.sohu.com,mydrivers.com,*.mydrivers.com,hupan.com,*.hupan.com,ct10000.com,*.ct10000.com,aiyiqu.com,*.aiyiqu.com,baike.com,*.baike.com,wdjimg.com,*.wdjimg.com,rrimg.com,*.rrimg.com,local.,*.local.,gfw.so,*.gfw.so,chinaz.com,*.chinaz.com,bankcomm.com,*.bankcomm.com,*.bsgchina.com,*.hichina.com
Username: deadjoe
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by deadjoe** [comment]
Upate:

I have uninstall the docker for mac via kinda tool like CleanMyMac to ensure all the relative files and directories are removed completed. And then reinstall the latest bits. Now it is working without any error similar to previous report.

**Comment by lynxoid** [comment]
I am seeing this behavior as well:

```
$ docker pull sjackman/prokka
Using default tag: latest
latest: Pulling from sjackman/prokka
a3ed95caeb02: Pulling fs layer 
ef38b711a50f: Pulling fs layer 
e057c74597c7: Pulling fs layer 
666c214f6385: Waiting 
c3d6a96f1ffc: Waiting 
3fe26a83e0ca: Waiting 
721028a3343c: Waiting 
3443819e25d7: Waiting 
7181a876e357: Waiting 
95a126206854: Waiting 
a1399ca4b815: Waiting 
33cc337a2b03: Waiting 
dc4dd12d3871: Waiting 
4585f27c8e1c: Waiting 
200dbb3be85b: Waiting 
0da2f5d997db: Waiting 
b6b01d972e39: Waiting 
e62a16f3e4a2: Waiting 
open /var/lib/docker/tmp/GetImageBlob746257660: structure needs cleaning
```

System info:
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: DZMO:Y3OQ:2CFX:34F7:QGVR:55DN:CRBV:K6RF:UZJ7:KFHA:7BWN:AVQT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-11-16T18:32:10.694535732Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Comment by lynxoid** [comment]
Removing all docker files in `/Users/filippod/Library/Containers/com.docker.*` solved the issue.
