### ISSUE TITLE
kubernetes does not start

### ISSUE THREAD

**Issue by ravdocr** [docker/for-mac#3508]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B7B60654-0BBE-4695-8DE7-095B7F1DCA7D/20190206210357

### Information

  - macOS Version: 10.14.3 (18D42)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
We will investigate this bug in more detail, but I was able to run Kubernetes 1.13 with the last Edge version (2.0.2.0 - 30972).

**Comment by ravdocr** [comment]
Please close this  , not an issue anymore.

Thank you
