### ISSUE TITLE
Docker and osxfs crash with heavy writes to host mounted volume

### ISSUE THREAD

**Issue by dmfenton** [docker/for-mac#351]
### Expected behavior
Docker does not crash 
### Actual behavior
Docker crashes and process in container with mounted volume exits
### Information

Diagnostic ID: 4A1A849E-8CF4-45E0-95DF-D61CC9AB1543
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Unfortunately I cannot share the code, but I can describe our set up.

- Postgres container running with data dir volume mounted from the host
- Elasticsearch container with same set up
- Very high traffic between the containers
- Very high activity in the postgres databases

**Comment by dmfenton** [comment]
May be related to:
https://github.com/docker/hyperkit/issues/50
https://github.com/docker/for-mac/issues/104

**Comment by dsheets** [comment]
Does this occur if the postgres database is put in a Docker `volume` or stored in the VM tmpfs file system (e.g. under `/home`)?

**Comment by ijc25** [comment]
I'm afraid I don't see any sign of the docker/hyperkit#50 failure in any of the three diagnostics uploaded under 4A1A849E-8CF4-45E0-95DF-D61CC9AB1543, so this must be something else.

**Comment by dsheets** [comment]
This might be the same issue as #495 which should be fixed in Beta 28.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
