### ISSUE TITLE
Pulling images from google container registry (us.gcr.io) is very slow

### ISSUE THREAD

**Issue by snstanton** [docker/for-mac#3513]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 82AA1674-984E-4DAF-9ABF-A0166B8F4979/20190208192718

### Expected behavior

fast docker pull from us.gcr.io

### Actual behavior

When pulling an ubuntu image from a us.gcr.io repository, it takes about 42 s to transfer 88MB.  When I pull the same image from the standard docker repository, it takes 5.7s.  The gcr transfer starts off fast, but then rapidly slows down.  If I switch to a linux box and pull from gcr, I do not see the same slowdown.  It seems to be the combination of Docker for Mac and us.gcr.io that is slow.  Comparing a fast download with a slow download in wireshark on the same machine, the biggest thing I'm seeing is a tiny window size (245 vs 31744) that is killing performance.  Something is causing docker to back off and slow way down.

I can provide pcap files if requested (they are too large to attach here).
 
### Information
  - macOS Version:  Darwin Kernel Version 18.2.0

### Diagnostic logs

```
Docker for Mac: 2.0.2.0

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true


```

### Steps to reproduce the behavior
1. export GCR_PROJECT=us.gcr.io/_yourproject_
1. docker tag ubuntu $GCR_PROJECT/ubuntu
1. docker push $GCR_PROJECT/ubuntu
1. docker rmi ubuntu $GCR_PROJECT/ubuntu
1. time docker pull ubuntu
1. docker rmi ubuntu $GCR_PROJECT/ubuntu
1. time docker pull $GCR_PROJECT/ubuntu

**Comment by harmony-ek** [comment]
I am seeing this too.  Please let me know if there's anything I could help with.
