### ISSUE TITLE
Too many connections causes unresponsiveness

### ISSUE THREAD

**Issue by BEisem** [docker/for-mac#3518]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 1E67A154-BDD0-43AC-AC7B-18D0E2EE066D/20190211132615

### Expected behavior
Docker should be able to continue to run without having to restart periodically

### Actual behavior
Several restarts are required daily when Docker becomes unresponsive to local network requests

### Information

  - macOS Version:
10.14.2
### Diagnostic logs

```
Docker for Mac: version...
Version 2.0.0.2 (30215)
```

Note -- I have researched this issue and found older instances of this happening, but in all cases, the reports were 1-2 years old, and the resolution has always been that the problem was fixed with an update of Docker. I am running the latest version of Docker (which is supposed to contain the fix), but the problem still exists for me. I'm hoping my logs and diagnostics will contain some information so you can tell me whether this is related to those issues.

**Comment by andrey-mikhailov** [comment]
+1

**Comment by anorth2** [comment]
+1

**Comment by ruverav** [comment]
+1

**Comment by BEisem** [comment]
I have somewhat of a workaround for this, until a fix is issued. It's not particularly graceful, but it works, for now.

First, I created an Apple script with the following:

`do shell script "osascript -e 'quit app \"Docker\"' && open -a Docker"`

Then I used Lingon to schedule this to run every few hours. Essentially this just quits and restarts Docker before the number of connections gets too high.

Like I said, not the most graceful solution, but it's better than having Docker become unresponsive.

**Comment by ruverav** [comment]
Thanks. But I think it would better to check if a port is open and responsive via netcat or a similar command and, if not, quit and open Docker from a script. It makes more sense to me than restarting Docker every few hours without any specific reason, specially because Docker could drop connections just 10 minutes after restarting up and then stay without connectivity for the 100 remaining minutes.

**Comment by BEisem** [comment]
Thanks for that info! I'll look into it, but I'm no programmer so I don't know how to do what you're describing. Would you be willing to share an appropriate command to accomplish this?

**Comment by ruverav** [comment]
You can [install netcat via Homebrew](http://macappstore.org/netcat/) and then use something similar to this for your script:

`do shell script "nc -z localhost 80 ||  osascript -e 'quit app \"Docker\"' && open -a Docker"`

This means check if port `80` on `localhost` is open. If it's open, don't do anything, otherwise, quit Docker app and re-open again. I have not tried it yet though because I'm not in front of my Mac Mini.

**Comment by BEisem** [comment]
Excellent! I'm going to try this out, thanks. So then I guess I would schedule this to run periodically via Lingon, say every 10 minutes or so?

**Comment by BEisem** [comment]
I know we're getting away from the original message, but I think something is wrong with the command. I tried running it and even though the port is open, it still restarted Docker.

**Comment by ruverav** [comment]
I don't know why doesn't work for you. If I run the command in a ssh terminal works as expected.

My recommendation is to use Launchd instead of Lingo.

Create a bash shell script with the following content and name it `restart_docker.sh`:

```bash
#!/bin/bash
nc -z localhost 80 || (osascript -e 'quit app "Docker"' && open -a Docker)
```
Remember to change `localhost` and `80` for the `hostname` and `port` you want to check.

Then give it execute permission:

```bash
chmod +x restart_docker.sh
```

Create another file named `com.docker.monitor.restart.plist` with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.docker.monitor.restart</string>
    <key>ProgramArguments</key>
    <array>
        <string>/path/to/your/restart_docker.sh</string>
    </array>
    <key>StartInterval</key>
    <integer>600</integer>
</dict>
</plist>
```

You should change `/path/to/your/restart_docker.sh` for the path of your restart script and take into account `600` represents how many seconds you want it to wait between runnings.

Then, copy this file to `/Library/LaunchDaemon/`: 

```bash
sudo cp  com.docker.monitor.restart.plist /Library/LaunchDaemon/
````

Finally, load this daemon running the following command:

```bash
launchctl load -w /Library/LaunchDaemon/com.docker.monitor.restart.plist
```

**Comment by BEisem** [comment]
Thank you. I guess the question is, (going back to the original topic) ... which port would need to be checked when Docker fails like this? I suppose I could wait until the next time this happens, and then poll some ports to try and find out...

FWIW, this is all running on one machine. So it would most likely be `localhost` but I just don't know which port to look at.

**Comment by BEisem** [comment]
Also, in your examples, you are using `nc` instead of `netcat`. Is this a different version I should be using? When I installed netcat, the command to use is `netcat`.

**Comment by ruverav** [comment]
If you have a nginx proxy running in the port 80, just like me, test port 80 on localhost and you're good to go.

`nc` is the binary executable for netcat and if you have a `netcat` binary which does the same as the short one is just an alias or a symlink to the original binary. There is not a `netcat` command if you install netcat via Homebrew.

**Comment by BEisem** [comment]
Thank you! I have it running, and will monitor to see if it works (I'm sure it will). Thanks a million for your help!

For anyone monitoring this thread in the future ... the correct directory is `/Library/LaunchDaemons/` (there should be an "s" at the end of LaunchDaemons).

**Comment by BEisem** [comment]
And of course, Docker devs, PLEASE FIX THIS ISSUE SO WE DON'T NEED TO USE THIS HACK!

**Comment by ruverav** [comment]
Sorry for that typo, I already corrected it.

Anyways I'm not totally sure it will work when Docker reaches its TCP connection limit.

What I'm sure about is that if I manually close Docker (or stop the service running in port 80) and wait for the daemon to do it's magic, it automatically closes (if open) and opens Docker again. 

We will have to let this daemon run in the background for a while and see if it helps the next time.

**Comment by BEisem** [comment]
Ok, makes sense. I'm keeping my fingers crossed. For me it usually happens every 2-3 hours, so I should know fairly soon.

I think I posted this in a different thread, but when I run `lsof -p $(pgrep vpnkit) | wc -l` if the number returned is 2000 or higher, that's when Docker becomes unreachable. So I guess 2000 is the limit? I don't know. Anyway, right now it is at 699... as soon as I hit that limit, I'll see what happens and report back here.

**Comment by ruverav** [comment]
We could also use the output from that command to know when to restart Docker. Although I don't know if 2000 is a hard coded connection limit or depends on how you have configured your Mac or Docker instance. 

For the moment I will stick to the netcat solution and see what happens. 🤔

**Comment by BEisem** [comment]
Just curious, did your tests result in the correct result? For me, even though Docker is not responding, the script doesn't restart it. When I run `nc -z -v localhost 80` manually, it says the port is open. So apparently that is not what's causing the issue. Just wondering what you discovered?

**Comment by ruverav** [comment]
Same experience on my part. I came to the conclusion it's better to use `curl` because netcat only tests the tcp connection (which absurdly as it may seem, it's totally ok) but not if the web server itself is reachable.

So this is what I have now in my restart script:

```bash
#!/bin/bash
curl http://localhost:80 > /dev/null 2>&1 || (osascript -e 'quit app "Docker"' && open -a Docker)
```

It works as expected, it restarted Docker right now without touching anything.

**Comment by BEisem** [comment]
Fantastic! Thank you so much, this is a much more elegant solution, and actually even after the Docker devs fix this issue, your solution is probably very useful to have running in the background, in case any other issues ever happen to appear.

Thanks again!

**Comment by ruverav** [comment]
I made a repository to ease the process of configuring and installing this daemon, in case anybody needs it:

https://github.com/ruverav/docker-mac-restarter

**Comment by petrychenko** [comment]
this advice works for me, I increased it to 10000 and it is good for my setup

**Comment by ruverav** [comment]
@petrychenko Thanks, I added that value to my settings.json expecting it solves my problem.

Anyways I'm letting my daemon do his job in the background in case this change doesn't positively affect on my case (I rarely saw any value as high as 2000 when checking the open connections).

**Comment by petrychenko** [comment]
Sorry, @ruverav , seems it's just delay the error, not solving it. Mine has stopped working next day with the same error. Seems it's just a steady leak of connections that cannot be solved by increasing the limit

**Comment by skomarica** [comment]
Not sure if it's exactly the same problem, but we experience similar behaviour when running integration tests against services started with docker compose (localstack, postgres, elasticsearch). After some time, a service becomes unresponsive and we start getting `Refused connection`, `Socket timeout` or similar errors.

Everything worked perfectly well with older versions of Docker, so for the time being we stick to:

Docker
Community Edition
Version 18.06.1-ce-mac73 (26764)
Channel: stable
b0f14f1dac

**Comment by ruverav** [comment]
@skomarica I tried to downgrade my Docker to previous stable versions several weeks before opening this issue only to discover that it still happened to me, even after resetting Docker and starting from scratch. The only minor difference was it took a little longer to fail.

It's really confusing because I must say about half a year ago or so it didn't happen at all, even with the older versions that now don't seem to fix the problem. Could be somehow related to a recent MacOS update changing how Hyperkit and the Docker virtual machine manage the TCP connections between the OS and the VM? I really don't know but it's exasperating.

**Comment by coder-zhw** [comment]
@ruverav I think the problem is after install there always exists some unused networks, So, I Try to remove all unused networks pass the command `docker network prune`, It worked well to me

**Comment by ruverav** [comment]
@coder-zhw There are not unused networks in my case, just the default networks: "bridge", "host", "none" and the one I'm using for my stack of services: "docker_default".

**Comment by lhazlewood** [comment]
We're also experiencing these same issues after installing Docker for Mac 2.x.  We are seeing sockets left in `CLOSE_WAIT` and `FIN_WAIT_2` states and then the number of connections going up in our app's connection pools until vpnkit exceeds 2000 (ish).

At this point new TCP connections fail and our application experiences plenty of socket read timeout exceptions, like this:

```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out (RedisInputStream.java:202)
Caused by: java.net.SocketTimeoutException: Read timed out (Native Method)
```
and
```
org.springframework.jdbc.UncategorizedSQLException: Hibernate-related JDBC operation; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; Error checking connection out of pool for dataSource; nested exception is java.sql.SQLException: Error checking connection out of pool for dataSource (AbstractFallbackSQLExceptionTranslator.java:90)
Caused by: java.sql.SQLException: Error checking connection out of pool for eventuallyConsistentReadEntityDataSource (PooledDataSource.java:343)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out (Native Method)
```

#3350, while titled differently, is I think representative of this same issue.  The solution in that thread that appears to work is to downgrade Docker for Mac to version to Docker Community Edition `18.06.1-ce-mac73` 2018-08-29 (direct download link: https://download.docker.com/mac/stable/26764/Docker.dmg)

Interestingly, the `18.06.1-ce-mac73` release is the last stable release before the 2.x release train, which leads me to believe that 2.x isn't quite stable enough (at least until this connection issue is resolved).

@djs55 do you have any insight as to what might be going on between the two Docker for Mac versions?

**Comment by lhazlewood** [comment]
If anyone following this thread downgrades to `18.06.1-ce-mac73` per #3350 comments, could you please report back here if that solved your connection issues?

**Comment by skomarica** [comment]
@lhazlewood Yes, I already wrote [a couple of comments above](https://github.com/docker/for-mac/issues/3518#issuecomment-466637292) that the downgrade was the only solution that worked for us.

We spent days trying to debug and make different 2.x versions working without success, and all the time we would end up reverting it back to `18.06-1-ce-mac73`.

**Comment by PabloThiele** [comment]
I can add that still happen at `Version 18.06.1-ce-mac73 (26764)` after reach the "sweet spot" of 2000~2015 connections at vpnkit. 

Every single time that: `lsof -p $(pgrep vpnkit) | wc -l` reach these numbers I'll receive a connection reset. 

This version seems to be really better in comparison with the actual but in an intensive integration test it will eventually fail as well.

**Comment by yuhr** [comment]
#1132 #1374

**Comment by skomarica** [comment]
With the newest Docker Desktop community 2.1.0.1 (37199) the problems disappeared on my Mac OS 10.14.6. 🎉 

About Docker Desktop:
![Screenshot 2019-08-08 at 15 18 27](https://user-images.githubusercontent.com/4746434/62706712-61772a80-b9f0-11e9-98de-295b26857b15.png)

**Comment by ruverav** [comment]
I can confirm now it works flawlessly since I updated it.

Such a pitty because I already bought an Intel i-8500T 6 core MFF Dell Optiplex 3060 to replace my mid-2011 Mac Mini because I was reluctant to install GNU/Linux again (hw incompatibilities and misterious kernel panic crashes on the past) or Windows 10 Pro (unlicensed or pirated) on it.

**Comment by microtherion** [comment]
@kylepeeler: This issue is closed already, so maybe it would be best to either file a new one, or comment on one of the still pending versions of this issue, e.g. #4091
