### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use

### ISSUE THREAD

**Issue by HarryWeppner** [docker/for-mac#3522]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Container binds to host port `8080`.

### Actual behavior

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint nostalgic_shannon (ebbcb999408abe84034b8869720b1c7b1a081f5956239971613ff18604efdd25): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.
ERRO[0000] error waiting for container: context canceled
```

### Information

  - macOS Version: 10.14.3

After upgrading to 2.0.2.0 binding to host port 8080 failed claiming that the address is already in use. I verified that `lsof -i tcp:8080` did not show any macOS process listening on that port.

I bisected further and found that disabling Kubernetes made it work again!? Note that at that time no resources were created on K8S.

### Diagnostic logs

```
Docker for Mac: 2.0.2.0
```

### Steps to reproduce the behavior

1. `docker run -p 8080:80 nginxdemos/hello`

**Comment by djs55** [comment]
Thanks for your report. When Kubernetes is enabled the port 8080 is bound inside the helper VM -- though not on the host -- and this causes a clash with regular port forwarding. We're investigating possible fixes.

**Comment by guillaumerose** [comment]
This is related to https://github.com/docker/compose-on-kubernetes/issues/70

**Comment by HarryWeppner** [comment]
@djs55 is there any other info needed - it sounds like you've identified a feasible approach!?

**Comment by djs55** [comment]
Sorry for the delay getting back to you. The upstream issue is believed fixed and there is a workaround in the latest development builds if you'd like to try them: [Mac](https://download-stage.docker.com/mac/edge/31534/Docker.dmg) and [Win](https://download-stage.docker.com/win/edge/31536/Docker%20Desktop%20Installer.exe)

Otherwise the fix should be in the next edge and stable releases.

Thanks again for your report!

**Comment by youssame** [comment]
I started by this solution https://stackoverflow.com/questions/39632667/how-to-kill-the-process-currently-using-a-port-on-localhost-in-windows?answertab=votes#answer-39633428 
and then i restarted the docker. and it worked like charm

**Comment by alanamircruz** [comment]
Just adding this one (_only to notice for others and if needed then_), in my case even restarting did not fix this one... but I then remembered that I deployed an `ingress-controller` in the past without removing it (_my bad_). Anyways, regards.

```
C:\Users\me>helm list
NAME    REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
ingress 1               Tue Nov 26 15:47:23 2019        DEPLOYED        mme-charge-ingress-global-1.0.0 1.0             ingress

C:\Users\me>helm delete --purge ingress
release "ingress" deleted
```

**Comment by salmagomaa** [comment]
This was so helpful for me
https://stackoverflow.com/a/58795842/1770571

**Comment by mohit-bags** [comment]
Sometimes restarting the Docker also works. 
It worked for me.
