### ISSUE TITLE
Temp File Memory Leak 

### ISSUE THREAD

**Issue by alyssweissglass** [docker/for-mac#3524]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:C6B56FF7-12F8-4DDC-8285-9B08ED074016/20190213182911

### Expected behavior
 Normal docker usage

### Actual behavior
 Massive memory leaks of files that match `/private/var/folders/.../T/_MEI*`. Disk usage by these files is currently around 60gb, and rising at the steady rate of about .1 gb/min. Certain docker usages change the rate; I've observed rates as high as 2gb/min, but it always stays above that .1 baseline. Quitting docker stops the addition of new files, but does not clear out the old ones. 

I performed `Docker->Preferences->Reset->Reset disk image`, which appeared to solve the problem. However, after updating docker and OSX, the issue reappeared. I reset the disk image again, but the problem persisted this time.

### Information

  - macOS Version:10.14.3
  - Docker for Mac: Docker version 18.09.1, build 4c52b90
  - Note that I converted from `.gcow2` to `.raw` (stable -> edge) in an attempt to fix this error, but the behavior appears in both versions.
  - Macbook pro, 13 inch, 2018

### Steps to reproduce the behavior

Issue appears in normal usage, sometimes. It appears on my computer and several of my coworkers, but not for others. We have not identified any discernible pattern as to the cause.

**Comment by djs55** [comment]
Thanks for your report. To help me track it down, the next time this happens could you have a look at one of these files and see if it contains a recognisable pattern? I wonder if they contain logs or image data or something else.

**Comment by westrik** [comment]
```_bisect.so          _codecs_hk.so       _codecs_tw.so       _heapq.so           _multibytecodec.so  _random.so          _sha3.so            _struct.so          certifi             include             liblzma.5.dylib     readline.so         unicodedata.so
_blake2.so          _codecs_iso2022.so  _ctypes.so          _json.so            _opcode.so          _scproxy.so         _sha512.so          array.so            compose             jsonschema          libssl.1.1.dylib    resource.so         zlib.so
_bz2.so             _codecs_jp.so       _datetime.so        _lzma.so            _pickle.so          _sha1.so            _socket.so          base_library.zip    fcntl.so            lib                 math.so             select.so
_codecs_cn.so       _codecs_kr.so       _hashlib.so         _md5.so             _posixsubprocess.so _sha256.so          _ssl.so             binascii.so         grp.so              libcrypto.1.1.dylib pyexpat.so          termios.so```

Each `_MEI*` folder contains these files.

**Comment by alyssweissglass** [comment]
Cause found, it was an internal tool causing multiple versions of docker-compose to be instantiated, each with their own set of temp files.

**Comment by djs55** [comment]
@alyssweissglass thanks for letting me know!
