### ISSUE TITLE
Block in Kubernetes is starting...

### ISSUE THREAD

**Issue by baicaozb** [docker/for-mac#3527]
Block in Kubernetes is starting...

### Information
Diagnose info:
92D42756-8581-4452-9B90-5F0407119D8F/20190214085628

  - macOS Version: 10.13.5

![jietu20190214-170421](https://user-images.githubusercontent.com/14196538/52781423-7ef1ba00-3087-11e9-8965-a00e722eb915.jpg)

**Comment by ulrich** [comment]
Hello,

Unfortunately you can't access to **k8s.gcr.io** address needed by Kubernetes from your location. However, you can use [Docker Desktop Enterprise](https://goto.docker.com/Docker-Desktop-Enterprise.html) to run Kubernetes in Docker Deskop which allow you to work in Air gap mode.

`
2019-02-14 16:56:28.369379+0800  localhost com.docker.driver.amd64-linux[13856]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: EOF
2019-02-14 16:56:28.416133+0800  localhost com.docker.vpnkit[13855]: HTTP proxy --> 108.177.97.82:443 Host:k8s.gcr.io:443 (Origin): Failed to connect to 108.177.97.82:443
2019-02-14 16:56:28.416169+0800  localhost com.docker.vpnkit[13855]: HTTP proxy: returning 503 Service_unavailable
`

**Comment by cococomeon** [comment]
got the same issue, did you solve this yet?

**Comment by cococomeon** [comment]
> Hello,
> 
> Unfortunately you can't access to **k8s.gcr.io** address needed by Kubernetes from your location. However, you can use [Docker Desktop Enterprise](https://goto.docker.com/Docker-Desktop-Enterprise.html) to run Kubernetes in Docker Deskop which allow you to work in Air gap mode.
> 
> `2019-02-14 16:56:28.369379+0800 localhost com.docker.driver.amd64-linux[13856]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: EOF 2019-02-14 16:56:28.416133+0800 localhost com.docker.vpnkit[13855]: HTTP proxy --> 108.177.97.82:443 Host:k8s.gcr.io:443 (Origin): Failed to connect to 108.177.97.82:443 2019-02-14 16:56:28.416169+0800 localhost com.docker.vpnkit[13855]: HTTP proxy: returning 503 Service_unavailable`

please, i want to know what kubernetes need this host **k8s.gcr.io** for, so I can change it to other IP that can provide service like this by change /etc/hosts.

**Comment by ManiacDC** [comment]
I've tried various solutions in other threads, to no avail. My issue turned out to be that somebody has registered localhost.<domain>.com on our domain network. Fixing that fixed the issue.
