### ISSUE TITLE
No space left on device even after `system prune -a --force`

### ISSUE THREAD

**Issue by rawrgulmuffins** [docker/for-mac#3529]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 23B1CA2B-2812-4B75-B64C-4573FF32192D/20190215204442

### Expected behavior
Running `docker run -rm` commands won't cause disk full errors for all commands.

That `docker system prune -a --force` will free up said disk space issues.

### Actual behavior

executing a `docker run` command leads to this error

```
Error response from daemon: mkdir /var/lib/docker/tmp/docker-builder553623694: no space left on device
make: *** [env] Error 1
```

If I run `docker ls` I see a few orphaned images but not a huge amount.

```
alexl@MBP000413 ~/git/example :)% docker image ls
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
<none>                                                  <none>              b68ba6447529        8 hours ago         929MB
artifacts.dev.versive.com/docker-users-virtual/python   3                   ac069ebfe1e1        2 days ago          927MB
alexl@MBP000413 ~/git/example :)% docker image ls -a
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
<none>                                                  <none>              58244b31cc25        8 hours ago         929MB
<none>                                                  <none>              b68ba6447529        8 hours ago         929MB
<none>                                                  <none>              0f198fea228d        8 hours ago         929MB
<none>                                                  <none>              69868a8eab93        8 hours ago         927MB
artifacts.dev.versive.com/docker-users-virtual/python   3                   ac069ebfe1e1
```

Running `docker system prune -a -m` and re-running does not alleviate the issue.

#### Build Command
```
docker build -f Dockerfile \
            --build-arg SOURCE_IMAGE=python:3 \
            -t example_pytest .
```
#### Run Command
`docker run -a stdin -a stdout -a stderr --rm --mount source=example,target=/home/pytest example_pytest py.test --cov`
#### Dockerfile
```
# Original inspiration for this file from
# https://stackoverflow.com/questions/35322452/is-there-a-way-to-sandbox-test-execution-with-pytest-especially
ARG SOURCE_IMAGE
FROM ${SOURCE_IMAGE}

RUN adduser --disabled-password --gecos "" --uid 7357 pytest
COPY ./ /home/pytest
WORKDIR /home/pytest

# setup the python and pytest environments
RUN pip install --upgrade pip setuptools pytest
RUN pip install --upgrade -r requirements.txt
RUN pip install --upgrade -r requirements_dev.txt
RUN python setup.py develop

USER pytest
```
#### Deleting `Docker.raw` is a temporary fix

[This ticket](https://github.com/docker/for-mac/issues/2449) has a user delete the `Docker.raw` file as a work around for a similar issue. My Docker.raw file is 60Gb according to ls.

```
ls -lha ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw
-rw-r--r--  1 alexl  HQ\Domain Users    60G Feb 15 00:13 /Users/alexl/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw
```

Deleting the `Docker.raw  re-running the `run` command does fix my issue. For 2-3 runs fo the run command and then I'm back to getting disk space errors.

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? 
I have not attempted this on another computer yet.

  - Is the problem new?
Yes

  - Did the problem appear with an update?
 I did download the 2.0.0.3 update on the same day

  - macOS Version:
<img width="584" alt="screen shot 2019-02-15 at 12 11 37 am" src="https://user-images.githubusercontent.com/1521575/52883885-51594f00-3121-11e9-813e-9d7a18f74948.png">

![screen shot 2019-02-15 at 12 58 12 pm](https://user-images.githubusercontent.com/1521575/52883910-62a25b80-3121-11e9-93ad-2f33f16b8d93.png)

**Comment by newtack** [comment]
I have the same error message on windows

**Comment by gswallow** [comment]
Increasing the amount of memory allocated to Docker Engine alleviates this problem.  I increased from 2 GB to 12 and the containers I was running were able to grow from 3.1GB to 5.4GB in size, where they were killed prior.

**Comment by rawrgulmuffins** [comment]
Re-confirmed that this is still an open bug and it is not correct to close this.

**Comment by birgit-babbel** [comment]
I had the same issue today.
Running `docker system df` showed that for me the "Local Volumes" part took up the most space. `docker volume prune` solved it for me.

**Comment by rawrgulmuffins** [comment]
This issue still exists and should not be closed.

**Comment by ivanayov** [comment]
I have the same issue. What happens is that during a build a container is reaching full capacity of 174.9GB and docker goes out of memory. Not solved with `docker container prune`, as this is reproduced every time.
What's interesting is that I was building that image successfully before updating to docker 19.03.8, but I cannot say for sure that the problem has anything to do with the version.

**Comment by rawrgulmuffins** [comment]
I'm considering opening a new issue and pointing to this one since it seems like the project doesn't look at closed issues.

Opinions?
