### ISSUE TITLE
docker for mac not starting

### ISSUE THREAD

**Issue by thomas-b-jackson** [docker/for-mac#353]
## Steps to reproduce

1. Install and use successfully for a few weeks
2. Check for Updates
3. Install Updates

## expected behavior
Works just like before

## actual behavior
Engine can't start
See diagnostics below.

### Information

Diagnostic ID: 76FA3BD0-B64E-4A9A-A0EC-526ABF6AAC6C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by thomas-b-jackson** [comment]
Note that I also tried restarting my mac. 
Same behavior

**Comment by thomas-b-jackson** [comment]
[20160818-143229.tar.gz](https://github.com/docker/for-mac/files/425933/20160818-143229.tar.gz)
[20160818-141746.tar.gz](https://github.com/docker/for-mac/files/425935/20160818-141746.tar.gz)

**Comment by thomas-b-jackson** [comment]
attaching logs created by diagnostics

**Comment by thomas-b-jackson** [comment]
I found a workaround. I choose Preferences->Uninstall/Reset->Restore to Factory Defaults
After doing that I was able to get it working again.
I notice that my /Volumes/Docker is 91% used. Could this be a possible root cause?

``M00973008:/Users/x0ox/jira/db>` df -a
Filesystem    512-blocks     Used Available Capacity  iused    ifree %iused  Mounted on
/dev/disk1     487849984 91505368 395832616    19% 11502169 49479077   19%   /
devfs                372      372         0   100%      648        0  100%   /dev
map -hosts             0        0         0   100%        0        0  100%   /net
map auto_home          0        0         0   100%        0        0  100%   /home
map -fstab             0        0         0   100%        0        0  100%   /Network/Servers
/dev/disk2s1      483248   441968     41280    92%    55244     5160   91%   /Volumes/Docker
``

**Comment by dsheets** [comment]
I believe the root cause was that your `Docker.qcow2` disk image had somehow become corrupted. We are aware of robustness issues with unexpected application and system shutdown that can cause this kind of behavior and we are working to improve the robustness of that subsystem. The `/Volumes/Docker` mount that you see is actually the `Docker.dmg` application installation media that is still mounted.

I'm glad "Restore to Factory Defaults" worked for you. Hopefully you won't have to use it again. Thanks for your report!
