### ISSUE TITLE
Docker in starting state after latest update

### ISSUE THREAD

**Issue by gokskrish** [docker/for-mac#3538]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 987857B7-6861-4E63-8A31-BE57236AE209/20190221000145

### Actual behavior
It is in starting state

I tried fresh install as well.

### Information

  - macOS Version: 

### Diagnostic logs

```
Docker for Mac: 10.14.3

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by konjag** [comment]
I had the same issue. After resetting Docker to factory defaults it seems to work.
