### ISSUE TITLE
vmstateevent invalid json: Docker crashes on fresh install of MacOS Sierra

### ISSUE THREAD

**Issue by chyld** [docker/for-mac#354]
Docker version: Docker version 1.12.0, build 8eab29e
Mac Version: 10.12 Beta (Sierra) 16A293a

I have a fresh copy of the Beta MacOS Sierra installed. Docker installed with no issue. But it had trouble starting, and after starting it keeps crashing due to the vmstateevent invalid json error message.

**Comment by dsheets** [comment]
This was tracked by #64 and has been fixed in Beta 23. OS X 10.12 Beta is not stable and there are other known issues with Docker for Mac on Sierra Beta. See [Known Issues for Beta 23](https://docs.docker.com/docker-for-mac/release-notes/#/beta-23-release-notes-2016-08-16-1-12-1-rc1-beta23).

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
