### ISSUE TITLE
ERROR: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

### ISSUE THREAD

**Issue by asbjornu** [docker/for-mac#3540]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `04AFE3A0-C0AC-465E-9325-9EA43A0522C9/20190221112539`

### Expected behavior
`docker-compose down`, `docker-compose stop` and `docker stop <container_id>` should shut down the container.

### Actual behavior
When running `docker-compose down`, the operation times out with the following error message:

```
ERROR: for foo  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

The commands `docker-compose stop` and `docker stop` just halts forever, seemingly. 

### Information
  - macOS Version: 10.12.6

Restarting Docker for Mac helps, but after restarting the container a few times, the problem appears again requiring another restart.

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)
Engine: 18.09.2, build 6247962
Compose: 1.23.2, build 1110ad01
Machine: 0.16.1
Notary: 0.6.1
Credential Helper: 0.6.0
Kubernetes: v1.10.11
```

### Steps to reproduce the behavior

The `Dockerfile` which this occurs in can't be shared, unfortunately. It's a Java application, if that helps. I hope the provided diagnostics ID gives enough information to solve the problem.

**Comment by iRomain** [comment]
I had this issue and solved it by increasing the number of CPU's from 2 to 3 and the RAM from 2GB to 8GB in the Docker preferences
