### ISSUE TITLE
Docker crash sometimes (at least 1 or 2 times a day)

### ISSUE THREAD

**Issue by atalargo** [docker/for-mac#3543]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E1990F27-97F8-4972-9ACD-7CF411B693B6/20190222092554

### Expected behavior

Docker runs without crashing

### Actual behavior

Docker crash sometimes, after long time, after short time, after wakeup after a long or short sleep, etc

### Information

  - macOS Version: 10.14.3 Mojave

I update the system version from 10.11.X 1 week ago, and docker too, and this issue appears. Before, I didn't have crashes

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)

```

### Steps to reproduce the behavior

I can't give steps.

**Comment by Shabirmean** [comment]
I have observed the same issue. I don't know whether docker itself is crashing. It shows that the daemon is running. But all connections to containers is failing. I'm downgrading it for now.

**Comment by nelsonmora48** [comment]
I Have the same issue

**Comment by muhlman** [comment]
I am having the exact same issue, docker things its running but all connections to containers won't work, docker diags won't run until I restart the service etc. If I try and run diags before restarting the service it just sits there thinking its running and I have let it run for about 8 hours before giving up on it.

Not sure if it helps but an after restart diagnostic ID is: 6DF7D20F-239B-4244-AC2F-0B32FB6B2C1B/20190320103304

**Comment by zzarbi** [comment]
Having the same issue. On my side it might be related to waking-up the mac from sleep.
