### ISSUE TITLE
Docker can't start

### ISSUE THREAD

**Issue by jimmyli0010** [docker/for-mac#3547]
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.14.2 (build: 18C54)
logs: /tmp/41B51FCF-4200-40C8-8873-6803B6A5EC4A/20190225-112429.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/jimmy/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/jimmy/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/jimmy/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

**Comment by jcharnley** [comment]
Does it crash your system?

**Comment by ulrich** [comment]
Hello @jimmyli0010 

Can you try (if possible) with a fresh release of Docker Desktop?

Thank you,
