### ISSUE TITLE
DD2198E8-0791-4EB4-B523-F7BC122F250B/20190225091447

### ISSUE THREAD

**Issue by josuegomez** [docker/for-mac#3548]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @josuegomez 

Can you give us more explanation about your trouble?

Thank you,
