### ISSUE TITLE
Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by bdueck** [docker/for-mac#3551]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: DCC70C61-2061-4101-AAA7-3B7C93294110/20190225205910

### Expected behavior
Basic kubectl commands work.
### Actual behavior
Any kubectl command returns an error: Unable to connect to the server: EOF

### Information
  - macOS Version: 10.14.2

### Diagnostic logs
```
Docker for Mac: 2.0.2.1 (31274)

```

### Steps to reproduce the behavior
Not perfectly reproducible. It happens randomly after doing "normal" K8s activity (starting/stopping pods, etc.). After some time, (minutes, hours, days), kubectl is unable to connect to K8s.

**Comment by jonaseck2** [comment]
I'm playing around with google-microservices-demo and helm and frequently experience EOF errors. The logs show that the number of forwarded connections have been exceeded:

```
2019-03-10 11:43:27.078251+0100  localhost com.docker.vpnkit[56699]: Exceeded maximum number of forwarded connections (2000)
```
