### ISSUE TITLE
cp: cannot create hard link '*' to '*': Input/output error

### ISSUE THREAD

**Issue by iyadq** [docker/for-mac#3553]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:9F3CB6C4-8FC6-4204-9203-3CDBB5E64740/20190226195420

### Expected behavior
"cp -aufl" source destination should complete without error

### Actual behavior
cp: cannot create hard link 'root/libasound.so' to 'build/usr/lib/libasound.so': Input/output error

### Information

  - macOS Version: Mojave 10.14.3

### Diagnostic logs

```
Docker for Mac: version...
2.0.2.1(31274)
```

### Steps to reproduce the behavior

  1. docker build -t testimage .
	FROM centos:7
	RUN yum update -y
	CMD /bin/bash
  2. docker run --rm -it --name test6 -v $HOME:$HOME testimage /bin/bash
  3. The "/User" directory is mounted from host MacOS 
[root@249bc595b94b testdir]$ pwd
/Users/macuser/testdir

[root@249bc595b94b testdir]$ mkdir -p build/usr/lib/
[root@7e556cd973e1 testdir]# cp -a /usr/lib64/libz.so.1* build/usr/lib/
[root@7e556cd973e1 testdir]# ls -lR build/
build/usr/lib:
lrwxrwxrwx 1 root root    13 Dec  5 01:36 libz.so.1 -> libz.so.1.2.7
-rwxr-xr-x 1 root root 90248 Oct 30 20:24 libz.so.1.2.7
[root@7e556cd973e1 testdir]# 
[root@7e556cd973e1 testdir]# cp -aufl --parent build/usr/lib/* root/
cp: cannot create hard link 'root/build/usr/lib/libz.so.1' to 'build/usr/lib/libz.so.1': Input/output error
[root@7e556cd973e1 testdir]# ls -lR root/
root/build/usr/lib:
-rwxr-xr-x 3 root root 90248 Oct 30 20:24 libz.so.1
-rwxr-xr-x 3 root root 90248 Oct 30 20:24 libz.so.1.2.7
[root@7e556cd973e1 testdir]#

**Comment by billie-alsup** [comment]
I have a similar issue building a debian linux kernel package on Mac OS.  The problem appears to be that a hardlink to a symlink results in an error, although a hardlink is successfully created to the destination of the symlink.  for example:

$ touch a
$ ln -s a symlink_to_a
$ ln a hardlink_to_a
$ ln symlink_to_a hardlink_to_symlink_to_a
ln: failed to create hard link 'hardlink_to_symlink_to_a' => 'symlink_to_a': Input/output error
$ ls -li a sym* hard*
417926 -rw-r--r-- 3 balsup dialout 0 Apr 27 19:41 a
417926 -rw-r--r-- 3 balsup dialout 0 Apr 27 19:41 hardlink_to_a
417926 -rw-r--r-- 3 balsup dialout 0 Apr 27 19:41 hardlink_to_symlink_to_a
417927 lrwxrwxrwx 1 balsup dialout 1 Apr 27 19:41 symlink_to_a -> a
$ 

Running Docker Desktop 2.2.0.5.  It is important that the affected directories be mounted volumes and not an internally visible docker filesystem.  In my case, the mounted filesystem is of type APFS.  Doesn't matter if the volume is case sensitive or not.
