### ISSUE TITLE
Docker Desktop fails to start

### ISSUE THREAD

**Issue by marcelomelodf** [docker/for-mac#3555]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 118DEE9B-F4F1-400B-8356-438D5179D236/20190227191352

### Expected behavior
Docker desktop starts and runs.

### Actual behavior
Docker Desktop fails to start and shows the error: `Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.vpnkit`

### Information

  - macOS Version: 10.14.3

### Diagnostic logs

```
Docker for Mac: version 2.0.0.3 (31259)...

Diagnose & Feedback hangs, I've waited over 30 minutes and it just shows 'Diagnosing...'
```
Docker desktop won't start (always with the error: `Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.vpnkit`) and diagnostics would hang when I click on the 'Diagnose & Feedback' button.
Reading the troubleshoot I ran diagnostics through the command line (ID: ) and then I tried to run `/Applications/Docker.app/Contents/MacOS/Docker --version` to see if I could at least double check the installed docker desktop version and what was my surprise when docker started and ran without crashing!
I quit docker and tried running from Finder again, same thing, crashed with the same error. Quit and launched through CLI again: no crashes...
I am using Docker Desktop Version 2.0.0.3 (31259) and MacOS version 10.14.3

**Comment by pantoniotti** [comment]
I have the exact same issue. Same Mac OS version and Docker version
