### ISSUE TITLE
New installation on MacBook Pro fails. 

### ISSUE THREAD

**Issue by TheZoltan** [docker/for-mac#3566]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EDB98A16-7750-4512-A384-92D04A39B61E/20190306005407

### Expected behavior
Successful installation

### Actual behavior
Failed installation

### Information

  - macOS Version: 10.14.2

### Diagnostic logs

```
Docker for Mac: Latest stable version downloaded a few moments ago.

```

### Steps to reproduce the behavior

  1. ... On a Mac running 10.14.2 that has never had a previous version of Docker installed, attempt to install the latest Docker version.
  2. ... Installation fails, on first launch getting "Fatal Error  cannot install symlinks in /usr/local/bin (stage 5)"

**Comment by ebriney** [comment]
Hi @TheZoltan. It has been fixed on edge but not on master, sorry.
You just have to create the folder manually and it should work.
`sudo mkdir -p /usr/local/bin`

**Comment by TheZoltan** [comment]
Sounds good, thanks!
