### ISSUE TITLE
Docker engine is not headless. IE logging out stops Docker engine.

### ISSUE THREAD

**Issue by dlamblin** [docker/for-mac#3567]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I SSHed into my Mac and ran docker-compose in Screen. It did not work. So I logged into my mac to run the Docker.app, then I reconnected to my screen session to run docker-compose. This starts my container(s).
To me, logically I do not need to stay logged into the Mac to run this background service, so I log out of UI.
Note that I am still logged in as myself in a ptty in screen, running a docker container.
I expect that the container running detached or attached to a continuing ptty is going to keep running.

### Actual behavior
Later I connect to the Mac with SSH to see why the docker container's service isn't responding, and I find out that logging out stopped the Docker engine, its containers etc.
Also the engine apparently cannot be opened remotely over SSH without the same user also being actively logged into the OS X UI.

```
dlamblin@daniels-mini:~/docker-server$ screen -D -R
…
[2019-03-05 16:00:46 INFO] IPv4 supported, port: 19132
[2019-03-05 16:00:46 INFO] IPv6 not supported
[2019-03-05 16:00:47 INFO] Server started.
ERRO[11126] error waiting for container: EOF
ERROR: Bad response from Docker engine
dlamblin@daniels-mini:~/docker-server
{master *= 163ce5d}$ ./startserver.sh
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.
dlamblin@daniels-mini:~/docker-server
{master *= 163ce5d}$ open /Applications/Docker.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Docker.app.
dlamblin@daniels-mini:~/docker-server
{master *= 163ce5d}$ # Damn.
```
### Information
  - Is it reproducible? Yes, see above. `ERRO[11126]` must have been given after I logged out of the Mac UI (remember, I'm still logged in at the terminal however). The App was able to be started from the command line with open when logged into Mac UI, even though it was from a ptty started by ssh detached overall from that session. The App cannot be started after logging out of the Mac UI as shown by the error: `LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Docker.app`
  - Is the problem new? Unlikely. I mean, probably it wouldn't happen with docker-machine setup using VirtualBox, but I wanted the new-improved-method.
  - Did the problem appear with an update? I did just install the Docker Desktop for Mac that day.
  - A reproducible case if this is a bug, Dockerfiles FTW. I was using this dockerfile and docker-compose: http://github.com/BoxOfSnoo/docker-bedrockserver

  - macOS Version: 10.12 (I know its old, but I think this is a design issue with the App).

### Diagnostic logs

Hey so… remember how I was doing this remotely over SSH without being at the Mac UI?
So your https://docs.docker.com/docker-for-mac/troubleshoot/ suggests I gather the logs using the UI. Surely you must have a command line option to do the same. You do:
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload

Refer to:
Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/A36E434C-0948-42A1-BE84-E395B6FAF57A/20190306015046.zip

Diagnostics Bundle: /tmp/A36E434C-0948-42A1-BE84-E395B6FAF57A/20190306015046.zip
Diagnostics ID:     A36E434C-0948-42A1-BE84-E395B6FAF57A/20190306015046 (uploaded)

I mean, yeah the engine isn't running. I guess I just need a way to start the engine without the gui really. OH! and keep the engine alive without the GUI if it's started that way… um… optionally I suppose.

```
Docker for Mac: version... 18.9
```
I think
It's not pretty to try and find out either:
```
/Applications/Docker.app/Contents/MacOS/Docker --help
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
```

Or: ```
$ docker --version
Docker version 18.09.2, build 6247962```

### Steps to reproduce the behavior

  1. use http://github.com/BoxOfSnoo/docker-bedrockserver 's server-start.sh in an SSH session.
  2. log out of the Mac OS UI.
  3. watch your remote SSH session tell you the container is stopping because the engine stopped.

**Comment by ebriney** [comment]
Hi @dlamblin, Docker.app is not running as a service because it runs in user space.
It is a gui app that launch underlying components so you need to be logged in.

There is no way to launch them without the gui in the current version.
Sorry for that.

**Comment by dlamblin** [comment]
I get that it works this way now.
I don't think that's a good design choice.

**Comment by FranDepascuali** [comment]
I wrote about setting up docker headless in this post, it may be of help:
https://deep-thought.netlify.com/posts/using-docker-fastlane

**Comment by jankyupeblik** [comment]
>  It is a gui app that launch underlying components so you need to be logged in.
Is it? I don't ever use Docker's GUI. I have to VNC into a (macOS) computer just so the stupid thing will start at this point. Before I could ssh in and run it, no issue. This is asinine.
