### ISSUE TITLE
kubernetes couldn't start up while update completely

### ISSUE THREAD

**Issue by ascode** [docker/for-mac#3569]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F2CE33EE-176E-4643-AADB-E153BB52F005/20190306125610

### Expected behavior
When I have updated the docker to Version 2.0.0.3 (31259), the kubernetes can start up itself.
### Actual behavior
When I had updated the docker to Version 2.0.0.3 (31259), the kubernetes status stay on "Kubernetes is starting..." from then on.
### Information

  - macOS Version:
10.14.2 (18C54)

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)

```

**Comment by ebriney** [comment]
Hi @ascode .
Was it working before the upgrade?
Have you tried to `reset to defaults` if it's possible? (it will wipe yours containers)

**Comment by ascode** [comment]
> Hi @ascode .
> Was it working before the upgrade?
> Have you tried to `reset to defaults` if it's possible? (it will wipe yours containers)

Yes, it works well before.

**Comment by ascode** [comment]
> Hi @ascode .
> Was it working before the upgrade?
> Have you tried to `reset to defaults` if it's possible? (it will wipe yours containers)

I really not want it wipe my containers.

**Comment by dongfo** [comment]
i was the same to you . i had test my application for weeks ! But i's down and never end starting after update to 2.0.0.3/win

**Comment by ascode** [comment]
> i was the same to you . i had test my application for weeks ! But i's down and never end starting after update to 2.0.0.3/win

So, how did you solve it after this?

**Comment by ascode** [comment]
> Hi @ascode .
> Was it working before the upgrade?
> Have you tried to `reset to defaults` if it's possible? (it will wipe yours containers)

I have reset the docker for Mac to factory defaults and also have reinstalled it , and it also stuck in 'Kubernetes is starting...'

**Comment by dongfo** [comment]
i didn't solve it yet!

**Comment by ascode** [comment]
> i didn't solve it yet!

@dongfo How did you go on?
