### ISSUE TITLE
Docker crashes and delet all my containers every time I turn on my iMac

### ISSUE THREAD

**Issue by aadehamid** [docker/for-mac#3570]
- [ X] I have tried with the latest version of my channel (Stable)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 31C4924D-AABE-491A-9037-92742606E160/20190306163302

### Information

  - macOS Version: Mojave

### Diagnostic logs

```
Docker for Mac: version...

```
[log.txt.err.txt](https://github.com/docker/for-mac/files/2937349/log.txt.err.txt)
[diagnostics.log](https://github.com/docker/for-mac/files/2937353/diagnostics.log)
[log-asl.txt.err.txt](https://github.com/docker/for-mac/files/2937354/log-asl.txt.err.txt)

**Comment by ulrich** [comment]
Hello @aadehamid 

Do you use a cluster configuration (Swarm or Kubernetes)?
