### ISSUE TITLE
High CPU utilization after upgrade to 2.0.3.0 (31776) on OS/X 10.14

### ISSUE THREAD

**Issue by bryceryan-docker** [docker/for-mac#3571]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F37EA331-295C-413B-8187-850D6C808E81/20190306234901

### Expected behavior
reasonable cpu utilization, post-upgrade, when no containers are running

### Actual behavior
90-95% steady utilization by com.docker.hyperkit, no containers running.

### Information
I've been listening to the fan on my mac spooling endlessly for the last bit. this started immediately after upgrading docker for mac, and a simple check of the performance monitor shows com.docker.hyperkit consistently using 90%+ cpu on a macbook pro. i turned off all containers, and still utilization continues. I'll be downgrading or removing it shortly if it doesn't  go back to a reasonable usage. This is entirely new behavior, and has not occurred on any prior version of D4Mac

  - macOS Version: 10.14

### Diagnostic logs

Docker for Mac: version... 2.0.3.0 (31778) edge
[20190306234901.zip](https://github.com/docker/for-mac/files/2938823/20190306234901.zip)

### Steps to reproduce the behavior
upgrade to the latest edge version

**Comment by meteabogdan** [comment]
I'm experiencing the same behaviour! Looking forward to a fix :D

**Comment by bryceryan-docker** [comment]
In my case, it seems to have been a left-over hyperkit from the previous installation. i took the liberty of force-quitting the problematic com.docker.hyperkit process, and the cpu utilization dropped to normal levels, i was able to run containers with reasonable utilization, and no further instances of high cpu utilization.

since one other person mentioned this, i'll leave it open for now, but at least my issue is self-solved. though there's the potential for an issue during the upgrade itself.

**Comment by codingdash** [comment]
Experiencing the same issue when updated **Docker for mac(to 2.0.0.3 (31259))** on **macOS Mojave (10.14.3)**, and the `com.docker.hyperkit` process is running always even though I've not started the docker-for-mac. Explicitly killing the process solves the problem.

```bash
$ ps aux | grep docker
ritesh             719  50.8  8.2 12832920 1381896   ??  S     2:06AM   0:56.69 com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 2 -m 8192M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=vpnkit.eth.sock,uuid=12743cce-060d-470b-8cbf-3783a6a9fbc3 -U c2d5ad69-b795-4081-bedd-af57425cadc5 -s 2:0,ahci-hd,/Users/ritesh/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw -s 3,virtio-sock,guest_cid=3,path=vms/0,guest_forwards=2376;1525 -s 4,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker-for-mac.iso -s 5,ahci-cd,vms/0/config.iso -s 6,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker.iso -s 7,virtio-rnd -l com1,autopty=vms/0/tty,asl -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,

$ sudo kill -9 719
$ # problem solved
```

Also noticed that again if I start Docker for mac and exit it from the `Top bar -> Docker icon -> Quit Docker Desktop`, the `com.docker.hyperkit` process keeps running even though from the Top bar docker icon is removed.

**Comment by umrashrf** [comment]
<img width="596" alt="Screen Shot 2019-03-21 at 9 14 25 AM" src="https://user-images.githubusercontent.com/652326/54754435-e8e70d00-4bb9-11e9-86e0-91c00ec55eac.png">

**Comment by codingdash** [comment]
After killing all the docker process, still I see problem in the macOS system. That's giving me impression that something is going wrong in macOS itself.

Additionally, [the report](https://docs.google.com/document/d/17ZiQC1Tp9iH320K-uqVLyiJmk4DHJ3c4zgQetJiKYQM) from the engineers investing similar issue concludes same.

> Since the qemu and hyperkit processes show the same double-accounting problem in Activity Monitor despite them being completely separate codebases, we conclude the bug must be in macOS itself, probably the Hypervisor.framework. We have reported the bug to Apple as bug number 48714544.

**Comment by denieler** [comment]
Have exactly the same :( also huge memory usage

**Comment by texasbobs** [comment]
I had this a couple of months ago and then it stopped.  Suddenly it is back again and makes Docker unusable.  It does not ever respond to a command from a terminal. com.docker.hyperkit is using 100% of a cpu.

**Comment by texasbobs** [comment]
There have been several posts about this and they all seem to go stale and get deleted.  Any chance of this ever getting looked at?
