### ISSUE TITLE
Not able run docker with aws logging options on Mac

### ISSUE THREAD

**Issue by pgupta6** [docker/for-mac#3579]
Not able to set the aws credentials in the docker desktop for mac.
Docker Version : Version 2.0.0.3 (31259)
Mac OS Version : 10.14.2 (18C54)

I have created ~/.aws/credentials files with the  aws creds.
  aws_access_key_id : XXXXXXX,
  aws_secret_access_key" : XXXXXXXX

And in the Docker Daemon file put the aws logging options.
{
  "log-driver" : "awslogs",
  "log-opts" : {
    "awslogs-region" : "xxxx",
    "awslogs-group" : "xxxxx",
    "awslogs-stream" : "xxxxx"
  },

And while running the docker I am getting below error.

docker: Error response from daemon: failed to initialize logging driver: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
ERRO[0010] error waiting for container: context canceled

**Comment by kainoffke** [comment]
I am running into the same issue. Have you been able to solve this?

**Comment by pgupta6** [comment]
Nope, I moved from Mac to Ubuntu. It was easier to get the task done on Ubuntu compared to resolve things on Mac.

**Comment by kainoffke** [comment]
Thats sad ;) But thank you anyway

**Comment by shihangw** [comment]
same issue

**Comment by pcgeek86** [comment]
I've got the same issue here. According to the documentation for the `awslogs` log driver, you can use environment variables to configure the AWS IAM access key / secret key / session token. But, I can't figure out how to add system-wide environment variables to the Docker for Mac Linux virtual machine "moby". How can I do this?

**Comment by aetherical** [comment]
Having the same issue.

**Comment by juco** [comment]
same issue

**Comment by AusPrinzip** [comment]
Same issue!
