### ISSUE TITLE
Unable to install Docker on Mac: com.docker.docker Failed to install networking components.

### ISSUE THREAD

**Issue by fmq** [docker/for-mac#358]
### Steps to reproduce

1. Install Docker Beta on Mac OS Sierra Beta 5
2. Open Docker app
3. Enter password for user to install privileged  components

### Expected behavior

Docker should install itself and start running

### Actual behavior

Popup requesting password keeps appearing after I enter the correct password.

The following log is generated if ran from a command line:

fmq at tartarus in ~
$ /Applications/Docker.app/Contents/MacOS/Docker 
1471560805910375168 com.docker.docker Application version: 1.12.1-rc1-beta23 (11375)
1471560805910775040 com.docker.docker Administrator user: true
1471560805939816960 com.docker.docker OSX Version: Version 10.12 (Build 16A294a)
kern.hv_support: 1
1471560806132323072 com.docker.docker migrator: start migration process
1471560806136467968 com.docker.docker migrator: previous install detected
1471560806136608000 com.docker.docker migrator: previous version is 1.12.1-rc1-beta23
1471560806136774144 com.docker.docker migrator: no migration needed, you are good to go!
1471560806136793088 com.docker.docker migrator: end of migration process
1471560806209212160 com.docker.docker event tracker initialization failed
1471560806209858816 com.docker.docker could not track event: no UUID
1471560806209950976 com.docker.docker could not track event: no UUID
1471560811164512000 com.docker.docker failed to save docker app launch path
1471560811164534016 com.docker.docker Bundle path: /Applications/Docker.app
1471560811165190912 com.docker.docker com.docker.vmnetd component is missing and will be installed
1471560811167603968 com.docker.docker could not track event: no UUID
1471560817996492032 com.docker.docker Failed to install networking components.
1471560817998449920 com.docker.docker could not track event: no UUID
1471560823678100224 com.docker.docker applicationWillTerminate

### Information

```
Diagnostic ID: F1EC45AE-7F6A-4348-A8E7-1C44881911AB
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /var/root/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /var/root/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /var/root/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /var/root/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /var/root/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by fmq** [comment]
Hi

Running from command line (after a fresh install) gives me failed migration: failed to update app version history with the following log:

$ /Applications/Docker.app/Contents/MacOS/Docker
1472136153573133824 com.docker.docker Application version: 1.12.1-beta24 (11525)
1472136153573647872 com.docker.docker Administrator user: true
1472136153598170880 com.docker.docker OSX Version: Version 10.12 (Build 16A304a)
kern.hv_support: 1
1472136153791512064 com.docker.docker migrator: start migration process
1472136153797456896 com.docker.docker migrator: no previous version detected. This is a fresh install.
1472136153800883968 com.docker.docker migrator: failed to store cureent version in history (1.12.1-beta24) (failed to update app version history)
1472136153800905984 com.docker.docker failed migration: failed to update app version history

the second time around it goes back to the same message as reported:

fmq at tartarus in ~
$ /Applications/Docker.app/Contents/MacOS/Docker
1472136272024761856 com.docker.docker Application version: 1.12.1-beta24 (11525)
1472136272025170944 com.docker.docker Administrator user: true
1472136272050722048 com.docker.docker OSX Version: Version 10.12 (Build 16A304a)
kern.hv_support: 1
1472136272245285888 com.docker.docker migrator: start migration process
1472136272246885120 com.docker.docker migrator: previous install detected
1472136272246923008 com.docker.docker migrator: previous version is 1.12.1-beta24
1472136272246996992 com.docker.docker migrator: no migration needed, you are good to go!
1472136272247008000 com.docker.docker migrator: end of migration process
1472136272316516864 com.docker.docker event tracker initialization failed
1472136272317098240 com.docker.docker could not track event: no UUID
1472136272317154816 com.docker.docker could not track event: no UUID
1472136274427003904 com.docker.docker failed to save docker app launch path
1472136274427031040 com.docker.docker Bundle path: /Applications/Docker.app
1472136274427379968 com.docker.docker com.docker.vmnetd component is missing and will be installed
1472136274435819008 com.docker.docker could not track event: no UUID
1472136278859787008 com.docker.docker Failed to install networking components.
1472136278862360832 com.docker.docker could not track event: no UUID
1472136293646342144 com.docker.docker applicationWillTerminate

**Comment by dsheets** [comment]
The failed migration issue is tracked by #202. We are investigating the UDID issue.

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
