### ISSUE TITLE
com.docker.supervisor failed to start Exit code 1

### ISSUE THREAD

**Issue by arpit11193** [docker/for-mac#3580]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B37113B8-073D-4982-9B5F-55892F2B8955

### Expected behavior
Docker can be opened successfully
### Actual behavior
Docker throws this error when opened: "com.docker.supervisor failed to start Exit code 1"
### Information
**Is it reproducible?**
-> Yes, it is.
**Is the problem new?**
-> I don't think so
**Did the problem appear with an update?**
-> Yes, after I updated my Docker when it prompted me to update to latest version. But then it throws error "Incompatible macOS Version: 10.11.6. Docker requires macOS version 10.12.0 or higher.". So I downloaded an older stable version: "Docker Community Edition 17.12.0-ce-mac55 2018-02-27"

macOS Version: **version 10.11.6 (build: 15G22010)**

### Diagnostic logs

```
Docker for Mac: version: 17.12.0-ce-mac55 (18467c0ae7afb7a736e304f991ccc1a61d67a4ab)
macOS: version 10.11.6 (build: 15G22010)
logs: /tmp/B37113B8-073D-4982-9B5F-55892F2B8955/20190313-154948.tar.gz
failure: com.docker.vpnkit is not running
[ERROR]  vpnkit
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/abc/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/abc/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         vpnkit check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     app
[OK]     virtualization VT-X
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes
#ffb2b2#         kubernetes check failed with: (Failure
   "exec: /usr/local/bin/kubectl  --context docker-for-desktop --namespace docker get pods -o go-template='{{range .items}}{{.metadata.name}}\
  \n{{end}}': exit 1")##
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     moby-console
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/abc/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     disk

```

### Steps to reproduce the behavior

  1. Downloaded Docker stable version: Docker Community Edition 17.12.0-ce-mac55 2018-02-27
  2. Open Docker after installing the application

**Comment by djs55** [comment]
@arpit11193 thank you for your report. Unfortunately I couldn't find the diagnostics in the system. Could you reproduce the issue and upload another set of diagnostics?

**Comment by wajiii** [comment]
I get the same error dialog _very_ frequently when first booting my Mac  in the morning. I often have to start my day by resetting Docker to defaults and proceeding from there. 
It is no major loss, because I have learned that I cannot rely on Docker at all between work days, and our biuild systems and processess permit me to easily recreate any containers or uiimages I may need from day to day. 
My diagnostic ID for this morning is: 
"55168704-77B5-400E-BE02-507BB7CEA59A/20190516155654".
