### ISSUE TITLE
cannot bind files in the  /usr/local/bin

### ISSUE THREAD

**Issue by Ladicle** [docker/for-mac#3582]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 480A9FC0-73DA-48AD-9FFF-61D286A068E1/20190315014239

### Expected behavior

Docker command successfully binds files in the /usr/local/bin in the same way Docker on Linux.

```
$ docker run --rm -v /usr/local/bin/docker-slim-sensor:/tmp/docker-slim-sensor:ro nginx ls /tmp
docker-slim-sensor
```

### Actual behavior

When a docker command mounts with -v option, it shows the File Sharing error. 

```
$ docker run --rm \
          -v /usr/local/bin/docker-slim-sensor:/tmp/docker-slim-sensor:ro \
           nginx /tmp/docker-slim-sensor
docker: Error response from daemon: Mounts denied:
The path /usr/local/bin/docker-slim-sensor
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled
```

However, when it mounts with --mount option, it shows no such file or directory. 

```
docker run --rm \
      -it \
      --mount type=bind,source=/usr/local/bin/docker-slim-sensor,target=/tmp/docker-slim-sensor,readonly \
      nginx /tmp/docker-slim-sensor
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /usr/local/bin/docker-slim-sensor.
See 'docker run --help'.
```

In fact, the target directory which is bound /usr/local/bin did not any binaries in the source path(it does not occured outside of /usr/local/bin, and no problem on Linux).

```
$ ls /usr/local/bin/docker-slim-sensor
-rwxr-xr-x 1 aigarash 4362570 Feb  4 01:05 /usr/local/bin/docker-slim-sensor

$ docker run --mount type=bind,source=/usr/local/bin/,destination=/tmp,readonly nginx ls /
tmp
containerd
containerd-shim
ctr
docker
docker-init
docker-proxy
dockerd
runc
```

### Information

  - macOS Version: Mojave 10.14.3

### Diagnostic logs

```
Docker for Mac: Docker Desktop community Version 2.0.0.3 (31259)
Channel: stable
8858db33c8
```

### Steps to reproduce the behavior

  1. To put docker-slim-sensor to /usr/local/bin
  2. To run the following command

```
docker run --rm \
      -it \
      --name devtest2 \
      --mount type=bind,source=/usr/local/bin,target=/tmp/,readonly \
      nginx:latest /tmp/docker-slim-sensor
```

**Comment by djs55** [comment]
Docker Desktop on Mac has a whitelist of host directories which may be shared with containers. Since `/usr/local/bin` is not in your whitelist Docker prints the error
```
The path /usr/local/bin/docker-slim-sensor is not shared from OS X and is not known to Docker.
```
If you click on the whale menu -> Preferences you should be able to add `/usr/local/bin` to the whitelist and hopefully the `docker run -v` will work as expected. See the section on "File Sharing" in the [docs](https://docs.docker.com/docker-for-mac/).

Let me know if that makes it work as expected or if you're still having problems.

**Comment by Ladicle** [comment]
![image](https://user-images.githubusercontent.com/1159133/55449778-e3e97b00-5607-11e9-81dd-07fe0cdfb4b2.png)

I set `/usr/local/bin` to the file sharing path but it's still having problems.
```
$ docker run --mount type=bind,source=/usr/local/bin/,destination=/tmp,readonly nginx ls /tmp
containerd
containerd-shim
ctr
docker
docker-init
docker-proxy
dockerd
runc
```

**Comment by ramyavijayan** [comment]
I am facing the same issue. what is the resolution to this problem?

**Comment by srevenant** [comment]
I just upgraded to the latest edge, and i'm getting the same behavior.  However, to make it worse, the UI won't let me add /usr!  It uses the macos file browser, and /usr isn't even an option (even though it is there).  Has anybody made progress on addressing this?  Is there a file I can edit somewhere to add the folder?
