### ISSUE TITLE
Docker for Mac hangs

### ISSUE THREAD

**Issue by qnm** [docker/for-mac#3585]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6DCDEA20-C7CE-4C82-8A39-B672276FA99B/20190318052451

### Expected behavior

I can run my container without issues.

### Actual behavior

Container runs for a period but eventually 'hangs' and is unable to be stopped. `docker stop` also hangs. Computer fan engages.

Hyperkit is using 100% CPU and significant volumes of memory.

I've noted this odd behaviour and am thinking this is somehow filtersystem related:

```
root@8786ac8d0db5:/usr/share/dgvz# bundle
Traceback (most recent call last):
	9: from /usr/local/bin/bundle:23:in `<main>'
	8: from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	7: from /usr/local/lib/ruby/2.6.0/rubygems.rb:272:in `find_spec_for_exe'
	6: from /usr/local/lib/ruby/2.6.0/rubygems/dependency.rb:284:in `matching_specs'
	5: from /usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:45:in `filter!'
	4: from /usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:7:in `bundler_version'
	3: from /usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:22:in `bundler_version_with_reason'
	2: from /usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:68:in `lockfile_version'
	1: from /usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `lockfile_contents'
/usr/local/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
root@8786ac8d0db5:/usr/share/dgvz# cd
root@8786ac8d0db5:~# cd /usr/share/dgvERRO[5653] error waiting for container: EOF
```

The EOF was caused by me restarting Docker For Mac, but I hit TAB for completion of the path which caused the hang.

### Information
I have been using this app for a number of months and this has only recently become a problem.

  - macOS Version: 10.14.3 (18D109)

### Diagnostic logs
Uploaded as above.

```
Docker for Mac: Version 2.0.0.3 (31259)

```

### Steps to reproduce the behavior
Start my Ruby container. Use it for a while, maybe only 10 mins. Within ten mins the bash prompt will become unresponsive after executing a command e.g. `rm /tmp/thing.txt`.

**Comment by Bentipe** [comment]
Same for me with the same versions. I have to restart docker to solve it.

**Comment by Bentipe** [comment]
Withe edge version its not happening anymore for me

**Comment by ulrich** [comment]
Hello,

I don't see right now some trace of trouble in the logs. But, I did note that you had used your application with this version for a long time without trouble. Is it possible to reset to default factory you Docker Desktop?
Be careful because you will lost all Docker containers and images local to the machine.

**Comment by iMerica** [comment]
Docker is hanging for me on the latest version of Docker for Mac

![Screen Shot 2019-04-04 at 2 53 25 PM](https://user-images.githubusercontent.com/487897/55584245-6c8c1800-56e9-11e9-8e94-df711936484f.png)

**Comment by qnm** [comment]
@ulrich This seems to have resolved itself. I'm not sure if either MacOS or Docker have updated since.
