### ISSUE TITLE
Permit customizing arguments to the kube-apiserver (i.e. openid connect oid flags)

### ISSUE THREAD

**Issue by bitsofinfo** [docker/for-mac#3589]
Please add support to customize the `kube-apiserver`

Currently this seems to be impossible, even w/ altering the manifests in the VM and restarting docker. Zero clue where the actual manifest that gets deployed is actually being generated from.

```
    - --oidc-issuer-url=https://mydex:5554/dex
    - --oidc-client-id=my-kubernetes
    - --oidc-ca-file=/etc/kubernetes/manifests/my.pem
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
```

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
not stale

**Comment by orefalo** [comment]
same issue, can't install an oic provider on docker-for-mac

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
nobody cares, letting the issue die
