### ISSUE TITLE
Docker will not start after machine crash...Appears in hung state

### ISSUE THREAD

**Issue by jp-gorman** [docker/for-mac#359]
### Steps to reproduce

1. Start Machine Docker loads...
2. Machine crashed when docker was running
3. Start machine again and note docker hangs...

### Expected behavior

Tell us what should happen

Docker should start normally...ever after system reboot it does not start.

### Actual behavior

Tell us what happens instead

Hangs... Show "Docker Starting..." (see logs for more)

### Information

```
Diagnostic ID: F99F8B18-EA59-489A-B1BA-E63AA3FAB90A
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment]
Unfortunately, it appears that your `Docker.qcow2` disk image was corrupted during the machine crash. We are aware of some robustness issues with the disk subsystem and are working to improve both corruption detection and corruption prevention. The only remedy, unfortunately, is to run `Restore to Factory Defaults` from `Uninstall/Reset` in `:whale: -> Preferences...`. Alternately, you can simply delete your `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2` file which will (!) *delete all of your containers, images, and Docker volumes* but will not reset your preferences.

I'm sorry that you had to experience this issue but we do appreciate your issue report.
