### ISSUE TITLE
Docker for Mac crashes shortly after wake-up (Mojave)

### ISSUE THREAD

**Issue by webuxr** [docker/for-mac#3590]
### Diagnose & Feedback
  - [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E1727E16-E658-4ED7-A8F6-CAC377C2534B/20190322132220

### Expected behavior
When I wake my Mac from sleep (usually in the morning after getting into work), and login to start my day, I am able to go about my work using other apps on my iMac (27-inch, Late 2013). After several minutes, the Docker Desktop app shows the Diagnostic dialog box asking if I want to troubleshoot the issue or quit the Docker app.

### Actual behavior
All of the above, but Docker should not crash and should no-longer need to show the diagnostic dialog.

### Information
  - Logged-in to hub.docker.com via Docker Desktop app: Yes
  - Is it reproducible? Yes, daily
  - Is the problem new? No, then again, I just reinstalled 
  - Did the problem appear with an update? No
  - Docker for Mac: Version 2.0.0.3 (31259)
  - macOS Version: Mojave version 10.14.3 (18D109)
  - Processor: 3.5 GHz Intel Core i7
  - Memory: 32 GB 1600 MHz DDR3
  - Graphics: NVIDIA GeForce GTX 775M 2048 MB
  - ![about-docker-desktop-for-mac](https://user-images.githubusercontent.com/1559023/54829322-2617d180-4c84-11e9-9fe6-4179b6ff42ac.jpg)

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)
```

### Steps to reproduce the behavior

  1. With Mac started, user logged in to Mac desktop
  2. From menu bar, select Docker icon and notice that Docker is running 
  3. At 5pm, lock Mac screen (via top-right most Mac user menu and select "Login Window..."
  4. Go home for evening. The next morning return and wake Mac by pressing spacebar on keyboard.
  5. Log in to Mac as usual and start opening apps (Chrome, Outlook, Atom editor, etc.)
  6. Watch and wait for Docker Desktop to crash.

[20190322132220.zip](https://github.com/docker/for-mac/files/2996924/20190322132220.zip)

**Comment by webuxr** [comment]
Following up with this morning's crash event. Same as above.
Diagnostics ID: E1727E16-E658-4ED7-A8F6-CAC377C2534B/20190325130921
Diagnostic payload: [20190325130921.zip](https://github.com/docker/for-mac/files/3003377/20190325130921.zip)

Not sure if any of the above helps so let me know if I can provide any additional info.

**Comment by webuxr** [comment]
Following up (again) with another crash event. Same scenario as my previous 2 posts above.
Diagnostics ID: E1727E16-E658-4ED7-A8F6-CAC377C2534B/20190327131318
Diagnostic payload: [20190327131318.zip](https://github.com/docker/for-mac/files/3014475/20190327131318.zip)

**Comment by ulrich** [comment]
Hello @webuxr 

I think that you have a trouble with the vmnetd component of Docker Desktop. Can you find any trace of the vmnetd process with this command :

> sudo launchctl remove com.docker.vmnetd

**Comment by chezsmithy** [comment]
I am seeing the same issue with version/2.0.0.3. I confirmed that sudo launchctl list | grep com.docker is launched. I'll grab diagnostics as well.

**Comment by DenysVuika** [comment]
I have Version 2.0.0.3 (31259) and it crashes every single time my MacBook resumes from sleep or gets unlocked. The problem started right after upgrading to Mojave (have got 10.14.5 so far)

**Comment by webuxr** [comment]
@ulrich Not sure how I missed your comment nor how I happened to just see it now. My apologies!

To answer your question...
```
$ sudo launchctl list | grep com.docker
106	0	com.docker.vmnetd
```

What does this mean?

**Comment by webuxr** [comment]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E1727E16-E658-4ED7-A8F6-CAC377C2534B/20190920124826

### Expected behavior
Docker Desktop does not crash when I wake my Mac from sleep.

### Actual behavior
Docker Desktop crashes when I wake my Mac from sleep.

### Information
  - Is it reproducible? Yes, dail
  - Is the problem new? No, then again, I just reinstalled
  - Did the problem appear with an update? No
  - macOS Version: Mojave version 10.14.3 (18D109)
    - Processor: 3.5 GHz Intel Core i7
    - Memory: 32 GB 1600 MHz DDR3
    - Graphics: NVIDIA GeForce GTX 775M 2048 MB

### Diagnostic logs
```
  - Docker for Mac: Version 2.0.0.3 (31259)
  - See attached diagnostic logs
```

### Steps to reproduce the behavior
  1. While logged into Mac as primary user, at ~4:45pm, close all currently open applications (determined by dark-colored dot showing below each open application in Mac OS Dock), open Mac OS "Apple" menu (top-left of screen), and select "Restart...". Note: Any apps running as services are are running in the background are left alone.
  2. After Mac restarts, log in again as primary user and allow all startup apps, services, and background apps to finish loading. 
  3. At ~5pm, select "Login Window" from the Mac OS Fast User Switching menu (top-right of screen) ... computer shows login screen.
  4. At ~8am next morning, click mouse or press spacebar to wake Mac.
  5. Mac presents login screen. Login again as the primary user.
  6. Wait a minute or 2 and notice dialog box stating Docker Desktop crashed.

[20190920124826.zip](https://github.com/docker/for-mac/files/3635968/20190920124826.zip)
