### ISSUE TITLE
Docker stuck on starting status ...

### ISSUE THREAD

**Issue by mika1K** [docker/for-mac#3596]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: Macos Majove Version 10.14.3 (18D109)

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thedaviddias** [comment]
Same issue...

**Comment by markd315** [comment]
Same issue:

Mac osx 10.13.6 tried with whatever stable docker I had (2... something) and now 2.0.3.0 edge.



https://docker-pinata-support.s3.amazonaws.com/incoming/3/5968EF99-3F4B-451E-885A-5B0793455594/20190328203131.zip diagnostics

**Comment by thedaviddias** [comment]
I did a "Reset to factory defaults" in the reset menu and it's now working fine... I just needed to download some docker images again. Did you try that?

**Comment by markd315** [comment]
Yes, and it produced nothing.

I switched back to the stable version and am going to try again.

**Comment by mika1K** [comment]
In my case I was in a fresh install, Im new to docker virtualization
I stopped all containers :   
---> docker stop $(docker ps -q)
I deleted all images : 
 Commands i used to delete images:
   --->  docker images
   --->  docker rmi $(docker images -q)
   ---> docker rmi -f 644ca19cb10d <--- replace this letter and number sequence with the same you'll 
                                                                      see in the output of the precedent command
Then i deleted all containers :
 ---> docker rm $(docker ps -a -q)

I restarted docker then my Mac . I also stopped all other Vm's (virtualbox) before restarting it. 
After that It take for docker like 3 minutes to start or restart at every time I run it but it works fine after all these tribulations . Hope this helps

**Comment by djs55** [comment]
Thanks for your report. Unfortunately without a set of diagnostics we can't investigate the issue. Could you open a fresh ticket and quote the diagnostics id? If the UI isn't working you can also gather diagnostics via the command-line:
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
