### ISSUE TITLE
Sleep during pull may corrupt qcow2 volume (qemu-img check exit 3)

### ISSUE THREAD

**Issue by yongshin** [docker/for-mac#36]
### Expected behavior

I resumed my laptop after putting it to sleep and then tried running docker images. docker ps works fine but images just hangs. I believe the laptop went to sleep while it was still pulling down an image which led it to this state. 

### Actual behavior

docker images should show me my images and remove the undownloaded image that my laptop was retrieving before it went to sleep. 

### Information

Diagnostic ID: A64D5A2B-14F9-4BBC-81D6-03B2C8794F63
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/yongshin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/A64D5A2B-14F9-4BBC-81D6-03B2C8794F63/20160730-134655/qemu-img-check.stdout 2> /tmp/A64D5A2B-14F9-4BBC-81D6-03B2C8794F63/20160730-134655/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by yongshin** [comment]
Had to restore to factory defaults to get it to work.

**Comment by samoht** [comment]
We plan to add tools to detect (and if possible correct) such errors. Thanks for the report!
