### ISSUE TITLE
Issue restarting docker after machine restart

### ISSUE THREAD

**Issue by tsmcgrath** [docker/for-mac#3602]
Restarted Mac Pro. Which crashed Docker.

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tsmcgrath** [comment]
Error upon machine restart

**Comment by ulrich** [comment]
Hello,

Can you give us the diagnostics ID ?
