### ISSUE TITLE
UDP port forwarding not working

### ISSUE THREAD

**Issue by tiborvass** [docker/for-mac#3603]
- [x] I have tried with the latest version of my channel (**Stable**)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
UDP messages can be sent between host and container, just like TCP.

### Actual behavior
Only TCP works, not UDP.

### Information

  - macOS Version: mojave 10.14.3 (18D109)

### Steps to reproduce the behavior
Term window 1:
```
$ docker run -it -p 5000:5000 --rm tiborvass/netcat nc -l -u -p 5000
```

Term window 2:
```
$ nc -u localhost 5000
```

Start typing a newline-terminated message in term window 2.

If you remove `-u` from both, it works fine.

**Comment by tiborvass** [comment]
Ping @djs55

**Comment by djs55** [comment]
Try adding `/udp` to the `-p`:
```
docker run -it -p 5000:5000/udp --rm tiborvass/netcat nc -l -u -p 5000
```
and specifying `127.0.0.1` instead of `localhost`:
```
nc -u 127.0.0.1 5000
```
This seems to work for me with a recent developer build.

**Comment by tiborvass** [comment]
Thank you that worked. But it's still odd that it doesn't work without specifying `/udp` and doesn't work with `localhost`. @beriberikix let me know if changing localhost to 127.0.0.1 fixes your issue.

**Comment by beriberikix** [comment]
Using the netcat container from @tiborvass and the modifications by @djs55 worked for me running Docker Desktop Version 2.0.0.3 (31259) stable, Engine 18.09.2.

However, following similar steps with my demo server (see referenced issue above,) it is not working. We can probably close this issue as I try to figure out the differences in my project.

**Comment by djs55** [comment]
Thanks for the update. I'll close this issue as you suggest but feel free to open a new issue if you hit another problem with Docker Desktop.
