### ISSUE TITLE
kubernetes already started,but show kubernetes failed to start

### ISSUE THREAD

**Issue by qiyongxiao** [docker/for-mac#3604]
Hi,docker office:
   I am use docker-for-mac community v2.0.0.3. I enabled kubernetes, it install completed for many days. Someday I start kubernetes,it show "started failed",but the kubernetes has already started. I can not found any errors in it. Could help me?

I report an issus, the id is 

##DA8F51B6-4F9D-4A36-B902-0A0BB7756829/20190401033041

```
kubemacbookpro:~ miyamoto$ kubectl get node
NAME                 STATUS    ROLES     AGE       VERSION
docker-for-desktop   Ready     master    11d       v1.10.11
macbookpro:~ miyamoto$ kubectl get svc
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
database      NodePort    10.109.49.210   <none>        3306:30692/TCP   10d
http-srv      ClusterIP   10.97.100.41    <none>        80/TCP           9d
kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP          11d
nginxhttps    ClusterIP   10.98.154.228   <none>        443/TCP          9d
nginxv2-svc   ClusterIP   10.96.54.191    <none>        80/TCP           8d
```

**Comment by ulrich** [comment]
Hello @qiyongxiao 

Can you ensure you there is enough space disk and/or try to update the disk image size?

**Comment by qiyongxiao** [comment]
@ulri
hi, here is the screenshot of disk and memory. I try to adjust to larger, still failed
<img width="500" alt="memory" src="https://user-images.githubusercontent.com/7349963/55370712-ff805300-552d-11e9-9f62-d4b275100e54.png">
<img width="500" alt="disk" src="https://user-images.githubusercontent.com/7349963/55370733-13c45000-552e-11e9-940a-32cbe4f2a4e7.png">

**Comment by ulrich** [comment]
I see that your cluster is stuck. Can you reset your Kubernetes cluster by using the Docker Desktop button "Reset to factory defaults" in preferences. This will have the effect to delete your locales images (your InfluxDB and Grafana).
After that, start an image one after another to test the behavior of your cluster.

**Comment by qiyongxiao** [comment]
@ulrich I don't want to reset it. I do many thins in it. If did,will lose any data

**Comment by djs55** [comment]
I think in this case the "compose" component for kubernetes has failed to start. In the `docker` namespace I see:
```
Name:           compose-74649b4db6-4klrb
Namespace:      docker
Node:           docker-for-desktop/
Start Time:     Sat, 23 Mar 2019 00:11:10 +0800
Labels:         com.docker.default-service-type=
                com.docker.deploy-namespace=docker
                com.docker.fry=compose
                com.docker.image-tag=v0.4.12
                pod-template-hash=3020560862
Annotations:    <none>
Status:         Failed
```
Try running the following command to see if it fixes the component:
```
docker run -it --privileged --pid=host justincormack/nsenter1 /usr/bin/ctr -n services.linuxkit t exec -exec-id foo -t docker /usr/bin/ensure-kube-compose.sh
```

**Comment by qiyongxiao** [comment]
@djs55 There is five compose, 3 is failed in it
