### ISSUE TITLE
Meh, stopped working again

### ISSUE THREAD

**Issue by stonefury** [docker/for-mac#361]
### Expected behavior
Just to work.
### Actual behavior
Suddenly just can't do anything. I can docker ps, but docker start or running somethign new just hagns.
### Information

Diagnostic ID: 894F8067-8770-46E3-AA13-2A0A6A430C2D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
It looks like `iptables` in Linux segfaulted. Did normal function resume after restarting the app? What were you running (containers or other Docker-related software) at the time (if anything)?

**Comment by mv012004** [comment]
Try resetting the docker install

**Comment by stonefury** [comment]
Restart doesn't work. I had to do a revert to default.  I use iterm2, run
alfred3, MS office. I dunno, not much.

I made maybe one image but no container was running. I just wanted to start
a container.

**Comment by mchiang0610** [comment]
Merging with #119
