### ISSUE TITLE
Fatal Error: cannot install symlinks in /usr/local/bin (stage 4)

### ISSUE THREAD

**Issue by zachmihalko** [docker/for-mac#3614]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 5DF3DBFF-3E88-4606-9BA7-45C3F0570072/20190405135847

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by senlin** [comment]
same here, happened right after the latest macOS update to 10.14.4

**Comment by senlin** [comment]
Disabling "Start Docker when you log in" seems to solve the issue.

**Comment by kerrhome** [comment]
Still present with 10.14.5 update.
