### ISSUE TITLE
Kubernetes doesnt come up healthy after resetting cluster

### ISSUE THREAD

**Issue by tillepille** [docker/for-mac#3617]
- [x] I have tried with the latest version of my channel (Stable or **Edge**)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1CF411C4-A9BF-485B-BF50-193ACFD4EB00/20190409071648

### Expected behavior

When clicking Reset -> 'Reset Kubernetes Cluster' the cluster is resetted and starts fresh and healthy afterwards.

### Actual behavior

After clicking 'Reset Kubernetes cluster' the status stays at 'Kubernetes is starting...' with an orange circle next to it.

### Information

  - macOS Version: 10.14.4

### Diagnostic logs

```
Diagnose succeeded


$ docker version
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

### Steps to reproduce the behavior

1. I had some faulty namespaces wich couldn't be deleted, so I decided to reset the cluster.
2. So opened the UI, clicket 'Reset Kubernetes cluster'. 
3. After half an hour of no progress i restarted  Docker for Mac but still stays the same.  

Other containers are running just fine.  
Also I can't disable Kubernetes right now, all options are greyed out so I need to live with a useless CPU usage of 50% extra.

**Comment by demisx** [comment]
Was hitting the same issue today with the latest 2.1.0.1. Even after reinstalling Docker app and finally getting K8S green, I am still having issue deploying app to this cluster. It stops responding half way.
