### ISSUE TITLE
Launching Docker for the first time on MacOS crashes

### ISSUE THREAD

**Issue by marcus-crane** [docker/for-mac#362]
### Expected behavior
Docker launches?
### Actual behavior
This is after launching for the first time. I imagined it's due to running on the MacOS Beta.
### Information

Diagnostic ID: 1BA49C82-D1C2-4D8B-8575-67134C88CB20
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A284a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Sentry/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/1BA49C82-D1C2-4D8B-8575-67134C88CB20/20160819-105909/qemu-img-check.stdout 2> /tmp/1BA49C82-D1C2-4D8B-8575-67134C88CB20/20160819-105909/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/Sentry/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Sentry/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/Sentry/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Sentry/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/Sentry/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Installed Docker for the first time
2. Ran Docker

**Comment by dsheets** [comment]
A major macOS Sierra Beta issue was tracked by #64 and has now been fixed in Beta 23. This fix will reach the stable channel with 1.12.1 in a few weeks.

**Comment by marcus-crane** [comment]
Yup, just downloaded Beta 23 and I can confirm it's working

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
