### ISSUE TITLE
CLI calls fail, diagnostic returns OK for everything else

### ISSUE THREAD

**Issue by iancullinane** [docker/for-mac#363]
Docker for OS X was working fine for about a week before failing. Tried restarts, as well as a reinstall. Diagnose & Feedback states everything is OK except for the CLI. 

### Expected behavior

Command Line calls fail

### Actual behavior

`Error response from daemon: Bad response from Docker engine`

### Information

Diagnostic ID: 2893A6A0-FD2E-43C2-8582-B7A545FB8044
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by mchiang0610** [comment]
Merging with #119
