### ISSUE TITLE
dns failure

### ISSUE THREAD

**Issue by jeanlaurent** [docker/for-mac#3634]
1. Run once: `docker run --rm -v $(pwd):/code -w /code python:latest python main.py`
got a `<urlopen error [Errno -3] Temporary failure in name resolution>` 
2. Ran 
Ran again `docker run --rm python:latest curl https://www.docker.com` It worked.
3. Ran again step1 `docker run --rm -v $(pwd):/code -w /code python:latest python main.py` stopped again `<urlopen error [Errno -3] Temporary failure in name resolution>`
3. Ran again step 2 `docker run --rm python:latest curl https://www.docker.com`
Got
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: www.docker.com
```
Uploaded Diag data under Diagnostic ID:
10EA1EC7-9C08-4D8F-91CE-E32D05006EC5/20190424091553

**Comment by guillaumerose** [comment]
Can you attach main.py?
