### ISSUE TITLE
Enable Kubernetes programatically

### ISSUE THREAD

**Issue by lavoiesl** [docker/for-mac#3636]
Our team is building automation for developers, which relies on having Docker Desktop on their macs and having Kubernetes enabled. 

I would love to automate enabling the k8s services for them, but I can't find how.

I tried looking for Preferences and using `defaults`, to no avail.

Where are the settings stored? Is there a way to interact with the Desktop features from the command line?

/cc @donk-shopify

**Comment by lavoiesl** [comment]
/remove-lifecycle stale
I’m still interested in this feature; it would make for a much better experience for our developers.

**Comment by epotex** [comment]
We are in the same boat, We are building tools for our developers and we would love to be able to enable k8s programmatically

**Comment by lavoiesl** [comment]
@tanner-bruce found the config file 🎉 
```
#!/usr/bin/ruby

require 'json'
path = File.expand_path("~/Library/Group Containers/group.com.docker/settings.json")
json = JSON.parse(File.read(path))
json["kubernetesEnabled"] = true
File.write(path, JSON.pretty_generate(json))
```

Or:
```
/usr/bin/ruby -rjson -e 'path = File.expand_path("~/Library/Group Containers/group.com.docker/settings.json"); json = JSON.parse(File.read(path)); json["kubernetesEnabled"] = true; File.write(path, JSON.pretty_generate(json))'
```

Afterwards, Docker needs to be restarted.

https://stackoverflow.com/a/41449949/708082 suggested:
```
killall -HUP com.docker.hyperkit
```
But I’ve had inconsistent results and crashes.

Maybe a big hammer is better:
```
killall Docker
open /Applications/Docker.app
```

If someone has a better way to restart, I’m all ears.
