### ISSUE TITLE
Cannot find ps 

### ISSUE THREAD

**Issue by RobertFischer** [docker/for-mac#3637]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: EB3B66A2-84C8-4D32-BD12-29EDD989667A/20190426151853

### Expected behavior

In the `./sonarqube` directory, `docker run -it -v /tmp/docker-sonarqube:/var/sonarqube -p 9000:9000 -P dot/sonarqube` runs an instance of `dot/sonarqube`

### Actual behavior

```
+ docker run -it -v /tmp/docker-sonarqube:/var/sonarqube -p 9000:9000 -P dot/sonarqube
Unable to locate 'ps'.
Please report this message along with the location of the command on your system.
```

[Fully zipped up directory](https://github.com/docker/for-mac/files/3121930/error-report.zip)

**Comment by RobertFischer** [comment]
BTW:

```
➜ which ps
/bin/ps
➜ docker ps --help

Usage:	docker ps [OPTIONS]

List containers

Options:
  -a, --all             Show all containers (default shows just running)
  -f, --filter filter   Filter output based on conditions provided
      --format string   Pretty-print containers using a Go template
  -n, --last int        Show n last created containers (includes all states) (default -1)
  -l, --latest          Show the latest created container (includes all states)
      --no-trunc        Don't truncate output
  -q, --quiet           Only display numeric IDs
  -s, --size            Display total file sizes
➜ which docker
/usr/local/bin/docker
```

**Comment by RobertFischer** [comment]
I thought it might have something to do with using `/tmp`, but changing it to a file in the current directory does not change the behavior.

**Comment by tdensmore** [comment]
What is `dot/sonarqube`? Is this a custom Sonarqube image? 
If so, this might be part of your problem.

This is the command to pull the official sonarqube image: `docker pull sonarqube`

**Comment by RobertFischer** [comment]
Never mind, I'm an idiot: the problem is in Sonarqube's start script.  *It* can't find `ps`.
