### ISSUE TITLE
Error when restarting after enabling Kubernetes

### ISSUE THREAD

**Issue by Samox** [docker/for-mac#3642]
- [x] I have tried with the latest version of my channel (__Stable__ or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BFDBC990-9B85-44B1-83F1-8CDDFD00B84B/20190430140052

### Expected behavior
I installed Docker Desktop for mac. 
Then I installed gcloud CLI with [this](https://cloud.google.com/sdk/gcloud/) and kubectl (with brew).
Then I enabled Kubernetes for docker-desktop, all works well.

### Actual behavior
I installed Docker Desktop for mac. 
Then I installed gcloud CLI and kubectl (with brew). 
Then I enabled Kubernetes for docker-desktop. When I restart my computer, it says it can't find a file `kubectl`.

### Information

  - macOS Version: 10.14.4 
  - Google Cloud SDK 243.0.0
  - bq 2.0.43
  - core 2019.04.19
  - gsutil 4.38
  - kubectl 2019.04.19

### Diagnostic logs
Error when starting:
```
Symlink /usr/local/bin/kubectl.docker doesn't exist
```

Diagnostic ID:
BFDBC990-9B85-44B1-83F1-8CDDFD00B84B/20190430140052

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Install gcloud CLI with [this](https://cloud.google.com/sdk/gcloud/)
  3. Install kubectl with brew
  4. Launch Docker Desktop
  5. Enable kubernetes
  6. Restart Docker Desktop

**Comment by Samox** [comment]
Same issue as https://github.com/docker/for-mac/issues/3308

**Comment by orkenstein** [comment]
Experiencing the same.
Any fix?
