### ISSUE TITLE
Network connectivity issues. Docker restart is required.

### ISSUE THREAD

**Issue by h3x00r** [docker/for-mac#3647]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E37A2253-E455-4415-8FED-32401200765B/20190501031448
  - Second Diagnostics ID: E37A2253-E455-4415-8FED-32401200765B/20190501041509

### Expected behavior
Network connection to any container should not be lost randomly.

### Actual behavior
Network connection to any container is lost. The necessary amount of time for this to happen
varies from few minutes to few hours. Docker restart is required.

### Information

  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No, it is since installation
  - macOS Version: 10.14.4

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259) without Experimental features enabled
```

### Steps to reproduce the behavior

  1. Have few containers up representing various projects i.e. 1 x magento2, 3 x laravel/lumen, 1 x mysql, 1 x redis, 1 x rabbitmq etc.
  2. On host have nginx as proxy
  3. Debug any project 
  4. Randomly the network connectivity (to containers) is lost.

**Comment by h3x00r** [comment]
Another Diagnosing ID 
```
E37A2253-E455-4415-8FED-32401200765B/20190501113515
```

**Comment by h3x00r** [comment]
Another Diagnosing ID 
```
E37A2253-E455-4415-8FED-32401200765B/20190501115324
```

**Comment by h3x00r** [comment]
Another Diagnosing ID
```
E37A2253-E455-4415-8FED-32401200765B/20190501124806
```

**Comment by h3x00r** [comment]
This is getting very annoying... restarts everywhere!
```
E37A2253-E455-4415-8FED-32401200765B/20190508110201
```

**Comment by hughsw** [comment]
See also #3487

**Comment by randrus** [comment]
See also 850A8A7D-C993-4C0B-AAE0-A411FA6C420B/20190718002153

**Comment by rnorth** [comment]
By connectivity is lost, what do you mean specifically? e.g. if you use netcat/telnet to try and communicate with running containers, do you:

(a) get an immediate connection refused failure; or
(b) manage to open a connection, but one that is essentially 'hung' (no data actually reaches the container)

I'm trying to determine whether or not to raise a new issue here in relation to:
* testcontainers/testcontainers-java#1623
* https://forums.docker.com/t/port-forward-not-working-on-a-macos-installation-but-works-on-others/77401

**Comment by hughsw** [comment]
In  #3487 we saw a third behavior:
(c) connection times out -- "Note: The connections to the containers time out, they are not refused."

**Comment by randrus** [comment]
Sorry - didn't try that so I don't know - but I will try that next time it
occurs and update here.
