### ISSUE TITLE
docker-machine ssh is erroring out with exit status 255

### ISSUE THREAD

**Issue by apunraghu** [docker/for-mac#365]
### Expected behavior
Establish connection with Ubuntu Virtual box with ssh connectivity. 

### Information
bash-3.2$ whoami
raghu
bash-3.2$ ssh 192.168.56.101
raghu@192.168.56.101's password: 
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-34-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Last login: Thu Aug 18 22:58:53 2016 from 192.168.56.1
raghu@raghu-test-env:~$ ls -ltr
total 44
-rw-r--r-- 1 raghu raghu 8980 Aug 18 18:47 examples.desktop
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Videos
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Templates
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Public
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Pictures
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Music
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Downloads
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Documents
drwxr-xr-x 2 raghu raghu 4096 Aug 18 18:57 Desktop
raghu@raghu-test-env:~$ exit
logout
Connection to 192.168.56.101 closed.

Diagnostic ID: 60856709-A939-4E4B-A414-17FAB823F075
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
1. docker-machine create --driver none -url=tcp://<Ubuntu Virtual Box IP>:2376 raghu-docker-test
Running pre-create checks...
Creating machine...
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env raghu-docker-test

2. docker-machine env raghu-docker-test
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.56.101:2376": dial tcp 192.168.56.101:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

3. docker-machine regenerate-certs raghu-docker-test
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...

4. docker-machine -D ssh raghu-docker-test -vvv
Docker Machine Version:  0.8.0, build b85aac1
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver none
Plugin server listening at address 127.0.0.1:56981
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(raghu-docker-test) Calling .GetState
(raghu-docker-test) Calling .GetSSHHostname
(raghu-docker-test) Calling .GetSSHPort
(raghu-docker-test) Calling .GetSSHKeyPath
(raghu-docker-test) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none @ -p 0] /usr/bin/ssh <nil>}
&{/usr/bin/ssh [/usr/bin/ssh -F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none @ -p 0 -vvv] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
exit status 255

**Comment by apunraghu** [comment]
I have given ip address for this command docker-machine create --driver none -url=tcp://192.168.56.101:2376 raghu-docker-test

**Comment by dsheets** [comment]
Docker for Mac does not use `docker-machine`. See <https://docs.docker.com/docker-for-mac/docker-toolbox/>.

**Comment by apunraghu** [comment]
But if I execute docker-machine create -driver virtualbox I am able to ssh
to docker machine as I mentioned in information section

**Comment by dsheets** [comment]
This issue tracker is for Docker for Mac which does not use `docker-machine` or VirtualBox. I recommend reporting this issue somewhere else like <https://github.com/docker/machine/issues>.
