### ISSUE TITLE
Attempt kubernetes with k3s

### ISSUE THREAD

**Issue by ldelossa** [docker/for-mac#3656]
### Expected behavior
The kubernetes cluster running should not spike the the hyperkit VM to 75%+ utilization regularily.

### Actual behavior
When kubernetes cluster is enabled the cpu utilization of the hyperkit vm process is high almost all the time. Laptop gets hot and battery drains quickly. 

### Information
  - macOS Version: 10.14.4

### Diagnostic logs
Don't have

### Steps to reproduce the behavior
Turn on Docker4Mac kubernetes cluster. The issue scales down with the number of cores provided to the VM but this is not a sufficient solution. 

-----

I am not affiliated with Rancher at all. However I am curious if I as a user of D4M can attempt to use k3s as the kubernetes cluster. This distro replaces some of the more heavy weight components like etcd with sqlite. I see on D4M site you provide qemu image, but I am not sure how kubernetes install happens and if it's a scripted procedure.

Thanks.

**Comment by erikwilson** [comment]
I was also hoping that k3s would help prevent Docker for mac / hyperkit from consuming all CPU too (about %550 w/ 8 CPUs enabled), but alas that does not seem to be the case. I disabled the kubernetes distro built into Docker for mac and used k3d, but after a few days the CPU spiked again (w/ little to no use of the cluster). I removed all docker containers and the CPU usage has not gone down. Only restarting Docker caused the CPU usage to go back to normal. 

Diagnostic ID: 4592954A-F063-4C2D-9915-C1D78BAA98A0/20190703001504

**Comment by erikwilson** [comment]
btw, I was running etcd, mysql, & postgres in docker containers and testing with a k3s cluster running through virtualbox/vagrant. That setup seemed to work fairly well for a long time, and it wasn't until using k3d to install a k3s docker instance that CPU consumption started to be an issue after a few days. Looking at docker stats there was nothing out of the ordinary that would warrant hyperkit to consume so much CPU. 

So to me it looks like D4M has a bug which is triggered by any kubernetes distro after running for an extended period of time. I will try edge to see if the problem still pops up there but I suspect it does as this issue has existed for a long time.
