### ISSUE TITLE
Network connectivity issues. Docker restart is required.

### ISSUE THREAD

**Issue by h3x00r** [docker/for-mac#3657]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E37A2253-E455-4415-8FED-32401200765B/20190509115349

### Expected behavior
Network connection to any container should not be lost randomly.

### Actual behavior
Network connection to any container is lost. The necessary amount of time for this to happen
varies from few minutes to few hours. Docker restart is required.

### Information
  - macOS Version: 10.14.4

### Diagnostic logs

```
Docker for Mac: 2.0.4.0

```

### Steps to reproduce the behavior

1. Have few containers up representing various projects i.e. 1 x magento2, 3 x laravel/lumen, 1 x mysql, 1 x redis, 1 x rabbitmq etc.
2. On host have nginx as proxy
3. Debug any project
4. Randomly the network connectivity (to containers) is lost.

This is related to https://github.com/docker/for-mac/issues/3647 but affects the latest edge version.

**Comment by hughsw** [comment]
See also #3487

**Comment by microtherion** [comment]
See also #3518

**Comment by bacoboy** [comment]
Did a fix for this ever make it into the stable release?

**Comment by microtherion** [comment]
This issue appears to have been fixed in 2.1.0.1 or so. No more hangs for me.

**Comment by microtherion** [comment]
But in 2.1.0.5, I'm seeing it again, though not as frequently as before.
