### ISSUE TITLE
how to Add port mappings for containers that have already been created

### ISSUE THREAD

**Issue by CodeingMonkey** [docker/for-mac#3660]
- macOS Version: 10.14.4

### Diagnostic logs

```
Docker for Mac: version 2.0.0.3 
I have created a container, but I want to add port mapping for the container that  have already been created and running。
how to add port mappings for the container that have already been created and running。

```

**Comment by ToJen** [comment]
Did you figure it out? Trying this but with no success:

```go
	hostConfig := &container.HostConfig{
		PortBindings: nat.PortMap{
			"5984": {
				nat.PortBinding{
					HostIP:   "127.0.0.1",
					HostPort: "5984",
				},
			},
		},
	}

	ports1 := make(nat.PortSet)
	ports1[newPortNoError("tcp", "5984")] = struct{}{}

	resp, err := dockerClient.ContainerCreate(dockerContext, &container.Config{
		Image:        imageRef,
		ExposedPorts: ports1,
	}, hostConfig, nil, containerName)
	if err != nil {
		return "", err
	}
```

https://github.com/moby/moby/issues/39213

**Comment by CodeingMonkey** [comment]
No, I  haven't slove this question, my temporary scheme is recreateing a container that i want。
I saw the scheme that  can add the port mapping by changeing two files of your container
hostconfig.json and config.v2.json
![image](https://user-images.githubusercontent.com/20737017/57741898-65492880-76f1-11e9-84b5-43ca270deb0e.png)
![image](https://user-images.githubusercontent.com/20737017/57741920-75f99e80-76f1-11e9-9da7-34628ce39edb.png)
