### ISSUE TITLE
Docker Not Starting on Mac Startup (OSX 10.13.6)

### ISSUE THREAD

**Issue by smpablo** [docker/for-mac#3661]
I am reviewing the trouble shooting site, but was hoping there was a "quick" resolution. :) 

  - X I have tried with the latest version of my channel (Stable or Edge)
  - X I have uploaded Diagnostics
  - Diagnostics ID: 937203C7-6F34-4E2F-9174-51F8E1387C3D/20190514132803

### Expected behavior
Docker should startup on system startup.

### Actual behavior
Docker failed to start.

### Information
OSX 10.13.6

### Diagnostic logs
937203C7-6F34-4E2F-9174-51F8E1387C3D/20190514132803

### Steps to reproduce the behavior
Fresh startup.

**Comment by horsecoin** [comment]
Same here, hopefully it starts working.  Using Docker is one of my favorite hobbies, and now I cannot even pull a thing!
