### ISSUE TITLE
Update embedded Kubernetes to 1.14

### ISSUE THREAD

**Issue by dmaze** [docker/for-mac#3663]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D9916B2F-B4F2-4269-8B4D-C01C0D3A537B/20190515152144

### Expected behavior

If I click on (whale), Preferences, Reset, Reset Kubernetes cluster, then when the Kubernetes-in-Docker restarts, I am running a current version of Kubernetes, such as 1.14.

### Actual behavior

I am running Kubernetes 1.10.11, which is rather out of date at this point.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Information

I've had Kubernetes support enabled for a while, though prodding around at low-level details suggests that objects are in fact getting deleted and recreated.

```
kubectl get pod -n kube-system kube-apiserver-docker-for-desktop -o jsonpath='{$.metadata.name}  {$.metadata.creationTimestamp}  {$.spec.containers[0].image}'
kube-apiserver-docker-for-desktop  2019-05-15T15:08:03Z  k8s.gcr.io/kube-apiserver-amd64:v1.10.11
```

I've tried using the "Reset Kubernetes cluster" option.  I have not tried the bigger hammers.

  - macOS Version: macOS Mojave Version 10.14.4

### Diagnostic logs

```
Diagnose succeeded
```

### Steps to reproduce the behavior

  1. (whale), Preferences, Kubernetes, ✅ Enable Kubernetes
  2. (whale), Preferences, Reset, "Reset Kubernetes cluster"
  3. `kubectl version`

**Comment by EronWright** [comment]
Suggestions: add the 'area/kube' label and update the title to "Update Kubernetes to 1.1x".

Note that the Kubernetes versioning policy is -1/+1 between client and server; see [Version Skew Policy](https://kubernetes.io/docs/setup/version-skew-policy/#kubectl).

**Comment by alisondy** [comment]
running into this issue aswell, I also want to opt out of the prepackaged kubectl, as it's quite old, and conflicting with my dev env.  Not sure if that should be covered under here or a separate issue

**Comment by EronWright** [comment]
Note that Docker Desktop has been updated to Kubernetes 1.15.4 on Edge channel.
