### ISSUE TITLE
Update documentation to make it clear that no_proxy on OSX is currently ignored

### ISSUE THREAD

**Issue by jonathanunderwood** [docker/for-mac#3664]
Currently there are various bugs reported for the NO_PROXY env such as #2723 and #2732. It seems that progress on fixing the handling of NO_PROXY is slow, so in the meantime it would be better to improve the documentation as follows:

* State explicitly in the documentation that Docker on OSX doesn't honour the "Bypass proxy settings... " entry in the Docker prefernces dialogue
* State explicitly that If a proxy is set in the preferences dialogue, setting the environment variables `no_proxy` and `NO_PROXY` in the container during build will have no effect.

**Comment by primat** [comment]
Pure fucking bullshit. Just remove the option if you're not gonna do anything about it instead of wasting people's time. Of course software is gonna have bug. But do you even test your shit?

**Comment by primat** [comment]
Lame. Very lame. Just remove the option if you're not gonna do anything about it, instead of wasting people's time.

Or even better, link to this - it worked for me: https://docs.docker.com/network/proxy/
