### ISSUE TITLE
19.03 fails to mount ~/.npmrc as secret into build context (works w/18.09)

### ISSUE THREAD

**Issue by daldridge-cs** [docker/for-mac#3668]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A5972CED-4E3F-4C7C-9D02-3BB9EBE06493/20190516201942

### Expected behavior
Docker build with .npmrc mounted as a secret into the build context succeeds.

### Actual behavior
Docker build fails with 19.0/Edge.  Same cli arguments and Dockerfile builds fine on 18.9/Stable.

### Information

  - macOS Version: 10.14.5 (Mojave)

### Diagnostic logs

```
Docker for Mac: 2.0.4.1 (34207)

```

### Steps to reproduce the behavior

If you don't already have ~/.npmrc, you can reproduce this error with an empty one.
```
touch ~/.npmrc
```
Use this Dockerfile:
```
# syntax = docker/dockerfile:1.0-experimental
FROM jupyter/base-notebook:7d427e7a4dde
USER $NB_UID
RUN --mount=type=secret,id=npmrc,target=/home/$NB_USER/.npmrc \
    npm i -g cortex-cli
```
Use this command-line to initiate the build:
```
DOCKER_BUILDKIT=1 docker build --progress plain --secret id=npmrc,src=$HOME/.npmrc .
```

**Comment by daldridge-cs** [comment]
Hrmmm...  I removed the secret mounts and consumption from the Dockerfile, leaving just this Dockerfile (tried both with and without global/-g arg):
```
# syntax = docker/dockerfile:1.0-experimental
FROM jupyter/base-notebook:7d427e7a4dde
RUN npm i cortex-cli
```
Looks like the secret mounts are irrelevant to the problem, but something more general about home directory permissions?

Note that I can execute the npm install just fine with a docker run of the base image:
```
docker run --rm -it jupyter/base-notebook:7d427e7a4dde sh -c "npm i cortex-cli"
```

**Comment by ebriney** [comment]
Creating the file with `npm config set ...`, I got :
```
$ls -l ~/.npmrc
-r--------  1 user  staff  12 May 17 11:23 /Users/user/.npmrc
```

with this Dockerfile
```
# syntax = docker/dockerfile:1.0-experimental
FROM ubuntu
RUN --mount=type=secret,id=npmrc,target=/.npmrc,required /bin/sh -c 'cp /.npmrc /.npmrc2'
```
and 
```
DOCKER_BUILDKIT=1  docker build --no-cache --secret id=npmrc,src=$HOME/.npmrc -t test3668 .
```
the content is correctly copied in ` /.npmrc2`, so I don't see any issue on my side

**Comment by daldridge-cs** [comment]
Confirming that the stock ubuntu image has no difficulties.  This Dockerfile (modified to install nodejs first, in case that somehow was preventing ~/.nmprc) builds fine with the same invocation:
```
# syntax = docker/dockerfile:1.0-experimental
FROM ubuntu

# Install Node.js
RUN apt-get update && apt-get install -y nodejs npm

RUN useradd -ms /bin/bash newuser
USER newuser
RUN --mount=type=secret,id=npmrc,target=/home/newuser/.npmrc,required npm i cortex-cli
```
It must be something wonky with the jupyter/base-notebook image.  This issue can be closed.

**Comment by daldridge-cs** [comment]
Ran some more tests with the following Dockerfile:
```
# syntax = docker/dockerfile:1.0-experimental
FROM jupyter/base-notebook:7d427e7a4dde
USER root
RUN apt-get update
```
I ran the same build command with 18.09 and 19.03:
```
> DOCKER_BUILDKIT=1 docker build --progress plain -t sadness .
```
Both 18.09 and 19.03 build successfully, but there is a difference in resulting permissions of the `/home/jovyan` directory.

With the image built with 18.09, I get what I expect:
```
 > docker run --rm -it sadness bash -c "stat -c '%U %G' /home/jovyan"
jovyan users
```
With the image built with 19.03, I get unexpected results:
```
 > docker run --rm -it sadness bash -c "stat -c '%U %G' /home/jovyan"
root root
```
This unexpected change-permissions-to-root situation is what is causing the npm package installation issue for USER jovyan, as npm runs as jovyan, created ~/.npm, but cannot since ~/ is owned by root.
