### ISSUE TITLE
Docker for mac startup is incorrectly modifying ~/.docker/config.json

### ISSUE THREAD

**Issue by jtokoph** [docker/for-mac#3670]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2F1EAAB2-5C58-4895-83BE-24971BFBFF73/20190517171536

### Expected behavior

`~/.docker/config.json` shouldn't be modified incorrectly

### Actual behavior

`~/.docker/config.json` is modified incorrectly.

Before startup:

```json
{
  "credsStore" : "ecr-login",
  "stackOrchestrator" : "swarm",
  "auths" : {},
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.09.2 (darwin)"
  }
}
```

After startup

```json
{
  "credsStore" : "ecr-login",
  "stackOrchestrator" : "swarm",
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.09.2 (darwin)"
  },
  "credSstore" : "osxkeychain",
  "auths" : {
    "https://redacted.net" : {

    },
    "https://redacted.dkr.ecr.us-east-1.amazonaws.com" : {

    }
  }
}
```

Notice that it's adding a duplicate mis-cased version of `credsStore`, it's adding a new one which is `credSstore` with the wrong `s` being capitalized.

I noticed this after my `credsStore` setting has mysteriously disappeared after a MacOS update and restart.

### Information

  - macOS Version: 10.14.5
  - This happens every restart
  - This also wiped out my `credsStore` value previously.

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

1. Set config to my first sample above.
2. Quit and re-launch docker for mac.

**Comment by ryanwilsonperkin** [comment]
Now affecting us as well on 2.1.0.1, causing quite a lot of Docker builds to fail

**Comment by aryazar86** [comment]
Same as @ryanwilsonperkin!
