### ISSUE TITLE
Is Docker for Windows available for Windows 10 Enterprise - 10586 Build?

### ISSUE THREAD

**Issue by e211280** [docker/for-mac#3678]
For new Installer it is giving me following error even if virtualization is on:
Docker Desktop requires Windows 10 Pro or Enterprise version 14393 to run.

I am trying to find old which supports following:
![image](https://user-images.githubusercontent.com/10432777/58068292-6d500f00-7bae-11e9-96ee-a11c8352e666.png)

On Google searches, i am unable to find info about this old build but i am finding questions related to this which suggests that old installer exists. Can anyone provide link to same?

Note: This is my Office system, i am not suppose to update builds.

**Comment by ebriney** [comment]
Hi @e211280.
From https://docs.docker.com/docker-for-windows/release-notes/ you can find it in release notes and there is a download link : https://download.docker.com/win/stable/12627/Docker%20for%20Windows%20Installer.exe
