### ISSUE TITLE
SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by ghost** [docker/for-mac#3679]
- X I have tried with the latest version of my channel (Stable or Edge)
  - X I have uploaded Diagnostics
  - Diagnostics ID: 6557F3F5-9D7C-4A83-B243-B93FEDED0ECF/20190521041851

### Expected behavior
No Error.

### Actual behavior
`SSL SYSCALL error: EOF detected` after long (> ~5min) running psql query

### Information
It is reproducible. Neither the OS inside of docker (ubuntu), nor the OS outside of docker (OSX) is running out of disc space or memory.

### TCP settings

**inside container:**
```
docker exec -it 94c73320b50f bash
root@94c73320b50f:/src# cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
root@94c73320b50f:/src# cat /proc/sys/net/ipv4/tcp_keepalive_probes
9
root@94c73320b50f:/src# cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
```

**host (osx):**
```
sysctl net.inet.tcp | grep -E "keepidle|keepintvl|keepcnt"
net.inet.tcp.keepidle: 7200000
net.inet.tcp.keepintvl: 75000
net.inet.tcp.keepcnt: 8
```

### macOS Version:
Mojave 10.14.4 (18E226)

### Diagnostic logs
see above

### Docker for Mac: version
Version 2.0.0.3 (31259)

It might be related to previously discussed/reported issues, [here](https://forums.docker.com/t/17-12-dropping-external-connections/44369) and [here](https://github.com/docker/for-mac/issues/2442).

![Screen Shot 2019-05-21 at 2 25 57 pm](https://user-images.githubusercontent.com/5118530/58068349-61774380-7bd4-11e9-87d1-c7e0a2d66eff.png)

**Comment by kevart** [comment]
I have tried the same setup on an AWS linux box and it does not time out.

**Comment by Trollgeir** [comment]
I have the exact same issue on Docker for Windows when running locally (tried both old and new versions). When I run the same container on Kubernetes in the cloud this doesn't happen, even with less resources allocated.

**Comment by ngortheone** [comment]
I have the same problem. Happens only on OSX docker
Version 2.0.0.3 (31259)

**Comment by kevart** [comment]
@ngortheone did you try Windows? @Trollgeir I got side-tracked if I have time I will try from within Kubernetes and check if that makes a difference for me. Nice hint.

**Comment by ngortheone** [comment]
No, but it seems to be workung fine on latest Edge


On July 3, 2019 9:56:50 PM EDT, kev <notifications@github.com> wrote:
>@ngortheone did you try Windows? @Trollgeir I got side-tracked if I
>have time I will try from within Kubernetes and check if that makes a
>difference for me. Nice hint.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/docker/for-mac/issues/3679#issuecomment-508309668

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zbentzinger** [comment]
I have been dealing with this for a long time. My solution was to switch over to using docker machine instead.

**Comment by Trollgeir** [comment]
I finally managed to solve the problem for windows (sorry mac users) by using WSL2. No more timeouts! https://www.thomasmaurer.ch/2019/08/run-linux-containers-with-docker-desktop-and-wsl-2/

I suspect the underlying issue is related to TCP keepalive settings.

**Comment by paoloc0** [comment]
I have the same problem on Docker for Mac 2.1.0.3 - thought I had problem with MySQL client or server settings that were causing slow queries to time out after 5 minutes (`ERROR 2013 (HY000): Lost connection to MySQL server during query`), but it turned out to be specific to Docker on Mac.

Using the same technique as in the (very similar-looking) #3324, here is a nice, simple way to reproduce the problem:

Host machine (Mac):
```
$ nc -l 0.0.0.0 1234 &
 
$ docker run -it --rm alpine:latest sh
 
/ # apk add busybox-extras
 
/ # time telnet 192.168.72.21 1234   # IP address of your host machine
Connection closed by foreign host
Command exited with non-zero status 1
real    5m 4.26s
user    0m 0.00s
sys    0m 0.00s
```

**Comment by romanorac** [comment]
I also have this problem when querying redshift with psycopg2.

**Comment by raimonds1503** [comment]
Still no fixes for this? Both mac and windows lastest and edge versions still fail :(

**Comment by jasonprado** [comment]
I found a workaround that works with psycopg2/redshift on my macOS machine/debian container. I set an aggressive keepalive on the client's socket so it doesn't go idle. Maybe this can be set at a container level instead?

```
conn = psycopg2.connect(...)

    s = socket.fromfd(conn.fileno(),
                    socket.AF_INET, socket.SOCK_STREAM)
    # Enable sending of keep-alive messages
    s.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
    # Time the connection needs to remain idle before start sending
    # keepalive probes
    s.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 5)
    # Time between individual keepalive probes
    s.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 1)
    # The maximum number of keepalive probes should send before dropping
    # the connection
    s.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 5)
```

**Comment by romanorac** [comment]
@jasonprado thanks for the workaround. I tried it with python:3.7.3-slim docker image and it doesn't work. I am using 2.2.0.4 Docker for mac .

**Comment by jeffkstephens** [comment]
For anyone still facing connectivity issue with a long-running Redshift query from Docker for Mac in 2020.

Amazon guidance generally is to adjust client system level TCP keepalive configuration
https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-firewall-guidance.html#connecting-firewall-guidance.change-tcpip-settings

If using docker run, pass the --sysctl option setting the TCP keepalive values from above.
https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

If using docker-compose, add sysctls to your compose file:
https://docs.docker.com/compose/compose-file/#sysctls

Example for compose that worked for me.
```
    sysctls:
        - net.ipv4.tcp_keepalive_time=200
        - net.ipv4.tcp_keepalive_intvl=200
        - net.ipv4.tcp_keepalive_probes=5
```

Tested from Docker for Mac 2.2.0.5 (43884) hosting Ubuntu 16.04.

**Comment by paulo3011** [comment]
@jasonprado thanks for the workaround, works for me on docker for windows running a python:3.7.3-slim

**Comment by guanzo** [comment]
Getting this error consistently on Windows. I'm using psql via docker to talk to a remote postgres instance.

**Comment by paulo3011** [comment]
> Getting this error consistently on Windows. I'm using docker psql to talk to a remote postgres instance.

Have you try this:

`psql "host=127.0.0.1 dbname=myDB keepalives=1 keepalives_idle=30"`

seealso:
- https://www.postgresql.org/docs/current/libpq-connect.html
- https://dba.stackexchange.com/questions/169329/psqlrc-setting-keepalives-idle-connection-parameter

**Comment by cdabel** [comment]
This is driving me nuts. I'm on Docker for Mac, latest version, and still having this issue connecting to Redshift (postgres)
