### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by stgarf** [docker/for-mac#368]
### Expected behavior
Installation success

### Actual behavior
Installation failure

### Information

Diagnostic ID: 86414D39-8D9A-4E64-A0C1-C15A0BF9168C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A299)

### Steps to reproduce

1. ... Install docker.
2. ... Don't profit.

**Comment by dsheets** [comment]
There was a major issue with golang and macOS Sierra Beta that was tracked by #64 and is now resolved in Beta 23. We know of several other issues with macOS Sierra so if you encounter other problems after installing the beta or 1.12.1 (when it comes out in a few weeks), please report again.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
