### ISSUE TITLE
docker hung - restarting is required to allow containers to continue

### ISSUE THREAD

**Issue by mariosanchez23** [docker/for-mac#3683]
[dockernave.zip](https://github.com/docker/for-mac/files/3207046/dockernave.zip)
[20190522105159.zip](https://github.com/docker/for-mac/files/3207049/20190522105159.zip)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
ECF5F68F-FB93-47E4-9CEB-873898F7B4BA/20190522105159

### Expected behavior
Containers working.

### Actual behavior
The containers don't work (nginx,apache and vpn containers)
The docker app is running and green, but no containers are accesible. 

### Information

We can't reproduce it, as it happens once in a while (one or twice per week). 
Suddenly, we can't connect to running containers and a docker restart is enough to make them run again. 

  - macOS Version:
High Sierra

### Diagnostic logs

```
Diagnose succeed

```

### Steps to reproduce the behavior
We can't reproduce it. 

I hope the logs (taken when the docker was hung) helps to find the problem. 
If you are not able to see the logs, or you can't, I wouldn't mind to get a very basic rules (what are the main logs, etc... ) and will review by my own to see what is causing the problem.

**Comment by microtherion** [comment]
This sounds like #3518
