### ISSUE TITLE
Docker desktop stuck in "Kubernetes is starting" loop

### ISSUE THREAD

**Issue by martinsoender** [docker/for-mac#3689]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `63F4EA21-A7FD-4B23-92FD-E6A6DC89A521/20190528172336`

### Expected behavior
To start as normal. 

### Actual behavior
Stuck in the starting loop for kubernetes. 

### Information

  - macOS Version: macOS Mojave v10.14.5 (18F132)

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259) - channel stable
Diagnose succeded
```

### Steps to reproduce the behavior

  1. Open up docker desktop
  2. Enable 

[docker-diagnostic-20190528172336.zip](https://github.com/docker/for-mac/files/3228908/docker-diagnostic-20190528172336.zip)
[docker-log.zip](https://github.com/docker/for-mac/files/3228909/docker-log.zip)

**Comment by vanga** [comment]
Resetting kubernetes settings and/or resetting whole docker(loosing all images, containers) resolved this for me. I don't know if there is a better way.
