### ISSUE TITLE
Network Regression in 19.03.0 beta

### ISSUE THREAD

**Issue by theory** [docker/for-mac#3692]
A user of the [Sqitch Docker image](/sqitchers/docker-sqitch) reported via the [mail list](https://groups.google.com/d/msg/sqitch-users/ZWBuLgyo-3Y/C5HDmqubCwAJ) that the behavior of connecting to a network service in one container from another container has changed. They tested with the Sqitch image, but the behavior should be the same just using `psql` in a second image, like:

```
docker run -e POSTGRES_PASSWORD=1234 -p 5432:5432 -d postgres:10-alpine
docker run -e PGPASSWORD=1234 postgres:10-alpine psql -U postgres -h localhost
```

With 18.09.2, they found they can connect to localhost when `--network host` is passed to the client container and whether or not it was passed to the service container:

![image](https://user-images.githubusercontent.com/46604/58597869-ec48e580-8247-11e9-8f2d-1206d8318736.png)

(The `psql` row is a connection from the Mac to the service container, while the other rows are from a client container ("sqitch network param" is the label) attempting to connect to localhost or `0.0.0.0`.)

But with 19.03.0-beta3, they found that it only works when  `--network host` has been passed to both containers:

![image](https://user-images.githubusercontent.com/46604/58597841-ca4f6300-8247-11e9-8c53-fb8c82810cc5.png)

I assume something was changed to make things more consistent, but there are fewer workable methods now.

Even still, I find the differences with the use of `--network host` a bit confusing, since [the docs](https://docs.docker.com/network/host/) currently claim that it's unsupported on macOS. Has that changed? Do the docs need to be updated, or is this unexpected behavior?

-----

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Consistent connectivity with `--network host` between versions

### Actual behavior

Change in behavior of `--network host` sometime between 18.09.2 and 19.03.0-beta3.

### Information
  - macOS Version: 10.14

### Steps to reproduce the behavior

  1. Install 18.09.2
  2. Start a Postgres container with 5432 port mapped
  3. Start another container with `--network host` and connect to the first via localhost or 0.0.0.0
  4. Note successful connection
  5. Install 19.03.0-beta3 and repeat steps 2-3
  6. Note failed connection

**Comment by djs55** [comment]
Thanks for your report.

In general we don't give guarantees about the behaviour of things which are unsupported. In this case the architectural differences between Docker Desktop for Mac/Windows and Docker on Linux make it difficult for `--network host` to work the same way.

In this particular case you can use the DNS name `host.docker.internal` to connect to the exposed port, instead of `localhost`:
```
docker run -e PGPASSWORD=1234 postgres:10-alpine psql -U postgres -h host.docker.internal
```

Happily the issue which caused the change in behaviour of `--network host` has been fixed, although not yet released on the edge channel. It should behave again like it used to in 18.09.2 when the next edge version is released.

**Comment by theory** [comment]
Glad to hear the behavior has reverted. I think it would be useful, however, to spell out how these various options and configurations work on each platform. For example, when the docs say that `--network` is unsupported on macOS, I figure it's a no-op, not that its behavior is undefined and subject to change. Clearly it does do something in some cases, and clarifying what's expected and what's not, as well as what might change and what won't, would be very useful. Thanks!
