### ISSUE TITLE
Kubernetes :starting kubernetes always on status "kubernetes starting  

### ISSUE THREAD

**Issue by larryguo** [docker/for-mac#3695]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 25351817-BE9E-4FC9-B4BD-6FC0D7620250/20190531204131

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by masstamike** [comment]
I've had this issue twice now, and have had to "Reset disk image" both times to get it working again.
`Preferences... -> Reset -> 'Reset disk image'`
