### ISSUE TITLE
Stuck in "Docker desktop is starting"

### ISSUE THREAD

**Issue by davyzhang** [docker/for-mac#3701]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
1015C0E5-025D-4A72-82F2-55F3AB80158B/20190608021012

### Expected behavior
start normally
### Actual behavior
hangs

### Information
  - macOS Version: 10.14.5
### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)
```

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/576863/59140829-16399f00-89e2-11e9-897b-9475357f39fe.png)

  1. start docker.app
  2. hangs

**Comment by texasbobs** [comment]
I have had the same issue on an off for months.  Today it is stuck and will not start normally no matter what I do.  One process just sits in a loop using 100% of a CPU.

I have gone as far as to completely uninstall, reboot, reinstall and it still has the same behavior.

Diagnostics are at E890E6E6-50BE-4796-9A62-94877F2D6CB6/20190611142528.  

![image](https://user-images.githubusercontent.com/19479196/59281059-42486080-8c2c-11e9-8676-fc9dc5878438.png)

**Comment by texasbobs** [comment]
Same issue with the Edge.

![image](https://user-images.githubusercontent.com/19479196/59283769-b4bb3f80-8c30-11e9-9f86-9604589fda9a.png)

**Comment by davyzhang** [comment]
As far as I know, version Version 18.06.1-ce-mac73 (26764) is the latest one that runs no problem on Mac

![image](https://user-images.githubusercontent.com/576863/59318986-37fb9480-8d08-11e9-96c0-e01af1f5bcf4.png)

**Comment by joshuaja** [comment]
Has anyone found a fix for this? I'm running into the issue today and falling back to 18.06.01 does not fix the issue. On Mojave 10.14.5.

**Comment by davyzhang** [comment]
Works fine with 2.1.0.
![image](https://user-images.githubusercontent.com/576863/63634457-d061ae00-c695-11e9-9dd5-0544aca3eb1e.png)
