### ISSUE TITLE
Docker doesn't send SIGINT signal

### ISSUE THREAD

**Issue by nairihar** [docker/for-mac#3703]
- I have tried with the latest version of my channel (Stable or Edge)
- I have uploaded Diagnostics
Diagnostics ID: F29DA5B8-9D03-4220-AC78-4811D22DAADE/20190608134026

**Expected behavior**

`docker kill` or some `service` actions should send process signal to the individual process.
I've added a trigger and tried in multiple ways, Docker doesn't send any signals to that process.

**Actual behavior**
Docker just kills the process without any signal notification.

**Steps to reproduce the behavior**
Just create a simple container and try to kill it and handle the signal in the process.

btw, you can use this article
https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86

**Comment by thaJeztah** [comment]
Is your main process running in a shell? If so, it's likely that the shell doesn't forward the signal

**Comment by nairihar** [comment]
@thaJeztah thanks for the reply

Sorry I didn't quite understand it.

I've initialized swarm then create service with 4 replicas.
And opened a shall to watch the service logs.
Then in another shall I ran `service scale=2`, so it should shut down 2 containers. But in logs, there is no that part which handles the signal.

**Comment by nairihar** [comment]
I'm using `ENTRYPOINT`

```
FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
ENTRYPOINT [ "npm", "start" ]

```

**Comment by nairihar** [comment]
I'm using `ENTRYPOINT`

```
FROM node:8

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

STOPSIGNAL SIGINT

EXPOSE 8080
ENTRYPOINT [ "npm", "start" ]
```

**Comment by nairihar** [comment]
I found the problem, seems it's running in the background(not PID1)
why it can happen so? do you have any ideas?

**Comment by thaJeztah** [comment]
if it's not running as PID1, it likely runs in a shell inside the container (eg `sh -c 'myscript.sh`), in which case `sh` is PID1, and `sh` acts different when running as PID1 (not handling signals)

**Comment by nairihar** [comment]
thanks

**Comment by nairihar** [comment]
thanks
