### ISSUE TITLE
same-line comments in Dockerfile yield erratic behavior

### ISSUE THREAD

**Issue by stefjoosten** [docker/for-mac#3705]
This might seem silly but I fixed this issue yesterday by realizing that docker does not support same-line comments so

ADD /x/y/z # this line returns an error.

In his reaction to [an issue about COPY](https://github.com/docker/for-mac/issues/1922#issuecomment-446908706_) @estatematt pointed out that same-line comments might be the culprit: 

> This might seem silly but I fixed this issue yesterday by realizing that docker does not support same-line comments so
> 
> ADD /x/y/z # this line returns an error.

It was this reaction that pointed me towards the solution.  The same thing worked for me too. :-)

It seems to me that docker has an issue here. The copy statement with inline comment behaves erratically. It should either give an appropriate message about inline comments or accept the inline comment and behave correctly. So I suggest adapting the parser for Dockerfiles to either accept inline comments (seems the right thing to do here) or to forbid them with an appropriate message.

**Comment by stephen-turner** [comment]
That's a good observation, but in the Docker engine not Docker for Mac, so maybe you could file it in moby/moby.
