### ISSUE TITLE
Stable: Containers exposing ports eventually won't connect and hang forever

### ISSUE THREAD

**Issue by lindycoder** [docker/for-mac#3709]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 1C24239E-46FE-482F-9659-C5F6D83DF8D1/20190611172315

### Expected behavior

A successful response for a curl to a container bound on a port *works forever* :P

### Actual behavior

```
$ docker run -p 10000:80 httpd
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
[Tue Jun 11 17:28:37.081719 2019] [mpm_event:notice] [pid 1:tid 140173063110720] AH00489: Apache/2.4.39 (Unix) configured -- resuming normal operations
[Tue Jun 11 17:28:37.081923 2019] [core:notice] [pid 1:tid 140173063110720] AH00094: Command line: 'httpd -D FOREGROUND'
```

Then 
```
$ curl -vvv http://localhost:10000
* Rebuilt URL to: http://localhost:10000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 10000 (#0)
> GET / HTTP/1.1
> Host: localhost:10000
> User-Agent: curl/7.54.0
> Accept: */*
>
```

Hangs forever.

### Information

*Restarting docker-for-mac DOES fix the problem, i know this.  I think it is still an issue.*

This happens when my docker-for-mac stays up for a while and my make goes in and out of sleep, on and off network, changing IPs sometimes.

I hope the diagnostics brings some light into my situation.

If not please tell me steps i could do to give more information when the problem will come back

  - macOS Version: 10.14.4 (18E226)

### Diagnostic logs

```
Docker for Mac: 2.0.0.3 (31259)

Diagnose succeded
```

### Steps to reproduce the behavior

(Only happens after a long time docker for mac is running. a couple days)

  1. `docker run -p 10000:80 httpd`
  2. `curl -vvv http://localhost:10000`

**Comment by dzivalli** [comment]
Same, restart doesn't help:

```
