### ISSUE TITLE
Occasional 18.09.2 hang

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#3712]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: E75A2F4F-F2B0-4271-BAC5-0F025D1E3E20/20190613043309

### Expected behavior

docker does not hang

### Actual behavior

docker hangs

### Information
  - macOS Version: latest, 10.14.5

I'll be building images and running containers then it seems to hang, `docker info` hangs.

### Diagnostic logs

```
Docker for Mac: 2.0.0.3 (31259) stable

Diagnose succeded
```

### Steps to reproduce the behavior

IDK just started happening past day. Maybe I need to reset.

**Comment by esetnik** [comment]
I am seeing the same behavior. Diagnostic ID `F21AE249-0660-47F4-B3FF-A9F8BF532D1F/20190703145822`
