### ISSUE TITLE
EADDRINUSE on UDP Port

### ISSUE THREAD

**Issue by steeve** [docker/for-mac#3720]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `3C22C167-2930-4977-A0ED-7624FFDE0DA8/20190620110716`

### Expected behavior

Binding on port `53/udp` should work.

### Actual behavior

It is not always released.
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint k3s (a10529ba894050dbba47557267dd3fdfdd1d397238fade1b893ae03ff26496fa): Error starting userland proxy: Bind for 0.0.0.0:53: unexpected error (Failure EADDRINUSE).
```

At this point, the only thing working is to reboot he macOS host. Even resetting to factory defaults doesn't fix it.

### Information
  - macOS Version: 10.14.5
  - d4m: 2.0.0.3 stable (but edge as the same issue)

```
Darwin C02VK1C7HTDF 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

### Steps to reproduce the behavior
1. `docker run --rm -it -p 53:53/udp busybox`
2. `docker kill`
3. do it again, it tails at some point

Thank you!

**Comment by steeve** [comment]
Turns out I can find the process with `netstat` but not `lsof`.

The port was opened by `vpnkit` (unsurprisingly), which I killed. But then it stays open:
```
$ netstat -l -n -v -p udp | grep '53'
udp4       0      0  *.53                   *.*                                786896   9216   1672      0 0x0180 0x00000204
udp4       0      0  *.5353                 *.*                                786896   9216    868      0 0x0100 0x00000204
udp6       0      0  *.5353                                        *.*                                                       786896   9216    208      0 0x0100 0x00010200
udp4       0      0  *.5353                 *.*                                786896   9216    208      0 0x0100 0x00010200
$ ps aux | grep 1672
$
```

**Comment by steeve** [comment]
I tried to rebind the port with a simple python script to try and force close it:
```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(("0.0.0.0", 53))
s.close()
```

But it fails:
```
Traceback (most recent call last):
  File "gna.py", line 4, in <module>
    s.bind(("0.0.0.0", 53))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

**Comment by jeanlaurent** [comment]
Thanks, you provided a diagnostic (we could see if the `vpnkit-expose-port` is still running inside the VM) and a repro script, we will look into that.

**Comment by djs55** [comment]
I can't explain why the port would be not listed in `lsof`. For reference I normally use `lsof -p <vpnkit pid> -P | grep :53`

Looking in the diagnostic there's no sign of a `vpnkit-expose-port` process keeping the port open:
```
$ grep vpnkit-expose-port vm/system/ps.txt 
 1340 root      0:03 /usr/local/bin/dockerd -H unix:///var/run/docker.sock --config-file /run/config/docker/daemon.json --swarm-default-advertise-addr=eth0 --userland-proxy-path /usr/bin/vpnkit-expose-port
```
So I think this rules out the docker engine as the source of the leak -- it must be the `vpnkit` process somehow.

I'll investigate further.

**Comment by steeve** [comment]
Yes indeed the pid listed by netstat was vpnkit. It stays after vpnkit is closed.

**Comment by steeve** [comment]
@djs55 note that the port is open on macos only it seems

**Comment by danuddara** [comment]
Hi ,
Do we have any updates on this? I have updated my macOs to Version: 10.14.5 and have the same docker version. 
it gives the same error. I am trying to run nginx with 80:80 ports

even if you run the example command on docker you get this error: 
```
docker run --detach --publish=80:80 --name=webserver nginx
docker: Error response from daemon: driver failed programming external connectivity on endpoint webserver (**): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE).
```

Have you found any workarounds to get this working?

**Comment by steeve** [comment]
Sorry but this is still a problem :(
