### ISSUE TITLE
eGPU support inside Docker for Macos

### ISSUE THREAD

**Issue by simonefrancia** [docker/for-mac#3722]
After I bought an eGPU with Nvidia GTX 1080, I followed this guide

https://theunlockr.com/how-to-use-nvidia-cards-with-your-mac-egpu/

in order to support it inside my MacBookPro 2015 with High Sierra 10.13.6
and everything worked fine during the installation.
My Mac sees GPU as graphic card:

![Schermata 2019-06-21 alle 11 54 52](https://user-images.githubusercontent.com/7140210/59915382-c82e8d80-941c-11e9-97e7-3a0a92fbc52e.png)

Furthermore, I installed `cuda-smi`(https://github.com/phvu/cuda-smi) to monitor GPU memory inside Mac and here also the GPU is visible.
```Device 0 [PCIe 0:70:0.0]: GeForce GTX 1080 (CC 6.1): 7629.9 of 8191.8 MB (i.e. 93.1%) Free```

My job is Data Scientist and I usually use Nvidia Card for training Neural Networks.
So my purpose is to use cards with PyTorch or Tensorflow,. So I followed this guide
 
 https://www.cs.rochester.edu/u/kautz/Installing-Pytorch-Cuda-on-Macbook.html

in order to see GPU inside an Anaconda environment. Also in this case everything worked well and now I can see GPU with Pytorch and I can train models with that.

![Schermata 2019-06-21 alle 12 18 56](https://user-images.githubusercontent.com/7140210/59916186-c5cd3300-941e-11e9-908e-bbb72b9a3b11.png)

After this long premise, my last purpose is to use it inside a Docker container, but at the moment, I am not able to see the GPU.
So my question is how can I "export" from my host the GPU device (`--device` linux-style ) to my container, if this it can be done?
Actually I have `CUDA Driver Version: 418.168`.

Thanks

**Comment by simonefrancia** [comment]
Any advice before deleting the issue ? @ulrich

**Comment by briandilley** [comment]
/remove-lifecycle stale

I have the same question

**Comment by evolu8** [comment]
I'd love to see an answer to this. Anyone?
