### ISSUE TITLE
"Docker Desktop is starting" - never starts

### ISSUE THREAD

**Issue by farmaceut** [docker/for-mac#3724]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E053D157-4897-4ACF-A200-9EB98608A8DE/20190622085208

### Expected behavior
 Docker should start upon opening.
### Actual behavior
 Docker opens in tray but keeps starting ('Docker Desktop is starting') for about an hour. Nothing more happens.
### Information

  - macOS Version: Mojave 10.14.5

### Diagnostic logs

```
Docker for Mac: newest version 

```

### Steps to reproduce the behavior

  1. Start Docker...

**Comment by Martouta** [comment]
I have the same problem with the same version of macOS and Docker Desktop.

**Comment by farmaceut** [comment]
> I have the same problem with the same version of macOS and Docker Desktop.

I've temporary fixed the problem. Whenever my Docker stucks on _Docker Desktop is starting_ I forcefully quite it, reopen, reset do default settings and reopen. Somehow it starts within a seconds...

**Comment by jihed** [comment]
Did anyone manage to find a fix or workaround ? @farmaceut your method didn't work with my setup.

**Comment by rev3r4nt** [comment]
Exact same issue here.
Diagnostic ID: 7808111C-C08B-46B0-8209-2B80C7184A2B/20190711194208

Stuck on hyperkit process with 100% cpu.
I tried a lots of method (multiple reset, hard reset, force quit, reboot, uninstall, stable, edge, clean manually file system ...) from the many opened issues, but nothing really consistent (1 of 20 not more).

**Comment by DuncanDoyle** [comment]
Same problem. Sometimes I can get it to work by:
- Removing /var/db/dhcpd_leases
- Start minikube (which recreates that file)
- Stop minikube
- Start Docker Desktop

But it isn't consistent and still have to find an approach that works properly ... I've tried reinstalling hyperkit, completely reinstalling Docker Desktop, etc. .... and sometimes I get Docker to start, but most of the times it fails and 

I've got the feeling that it has something to do with Hyperkit not being able to get an IP for the Docker Desktop VM ...

**Comment by geoffatcircle** [comment]
same here

**Comment by teells** [comment]
This is still an issue.
