### ISSUE TITLE
Unable to start Docker - Incompatible CPU detected

### ISSUE THREAD

**Issue by EddieOlson** [docker/for-mac#373]
### Expected behavior
Able to start Docker without errors
### Actual behavior

> Fatal Error
> Incompatible CPU detected.
> Docker requires a processor with virtualization capabilities

### Information

`$ sysctl kern.hv_support`
`kern.hv_support: 1`
http://ark.intel.com/products/83503/Intel-Core-i7-4980HQ-Processor-6M-Cache-up-to-4_00-GHz

Diagnostic ID: B22ADAD1-6521-4B35-8947-2C0339B2F998
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/EddieOlson/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/B22ADAD1-6521-4B35-8947-2C0339B2F998/20160819-181024/qemu-img-check.stdout 2> /tmp/B22ADAD1-6521-4B35-8947-2C0339B2F998/20160819-181024/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/EddieOlson/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/EddieOlson/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/EddieOlson/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/EddieOlson/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/EddieOlson/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Download Docker.dmg
2. Open Docker.dmg
3. Move Docker.app to Applications/
4. Open Docker.app in Applications/
5. Fatal Error is shown

**Comment by mchiang0610** [comment]
We require laptop that's 2010 or newer due to the hardware specifications. 

If you are running a laptop newer, please reply, and I'll reopen. 

Thanks!

**Comment by maryam-taheri** [comment]
My 2015 MacBook has OS EI Capitan version 10.11.6. The hypervisor test is also positive:

$ sysctl kern.hv_support
kern.hv_support: 1

and yet I get the incompatibility error:

"Incompatible macOS Version: 10.11.6.

Docker requires macOS version 10.12.0 or higher."
