### ISSUE TITLE
Expose Kubernetes API 6443

### ISSUE THREAD

**Issue by esetnik** [docker/for-mac#3730]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F21AE249-0660-47F4-B3FF-A9F8BF532D1F/20190626172326

### Expected behavior
There should be a way to bind kubernetes api to all interfaces. It's currently only bound to localhost which makes it impossible to expose kubernetes api to the internet.

### Actual behavior
Cannot find any configuration option to bind kubernetes api to 0.0.0.0, but the local loopback is available. I do not want to use `kubectl proxy` because this will expose the api to the internet without authentication.

### Information
  - macOS Version: macOS X 10.14.5

### Diagnostic logs

```
F21AE249-0660-47F4-B3FF-A9F8BF532D1F/20190626172326
```

### Steps to reproduce the behavior

  1. Enable kubernetes
  2. Attempt to access cluster at https://0.0.0.0:6443

**Comment by esetnik** [comment]
Might be related to #3589

**Comment by davidamey** [comment]
Also related to #3840 I believe.

I run k8s on a server and want to control it from a client terminal via kubectx w/o having to ssh in. Used to work fine in older versions of Docker for Mac.
