### ISSUE TITLE
"Docker is starting" forever

### ISSUE THREAD

**Issue by danielpassos** [docker/for-mac#3737]
- [x] I have tried with the latest version (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 69BCA6A4-71A7-48F1-90AC-BB9EE897F5C9/20190701155218

### Expected behavior

Docker start

### Actual behavior

"Docker is starting" status forever

### Information

  - macOS Version: 10.14.5 (18F132)

### Diagnostic logs

```
Docker for Mac: Version 2.0.0.3 (31259)
Channel: stable
8858db33c8
```

**Comment by m1kola** [comment]
I'm having the same issue with the same versions of MacOS and Docker for Mac.

But additionally Diagnostics & Feedback doesn't give me any useful output.

**Comment by skabashnyuk** [comment]
If you have type-C ports on your mac. Try to unplug all of them including power adaptor,  reboot your mac and start docker.

**Comment by m1kola** [comment]
Thanks for the suggestion, but it didn't work for me.

**Comment by StefanSchwartze** [comment]
I am having the same issue with same versions.

**Comment by flashsphere** [comment]
https://github.com/docker/for-mac/issues/3390#issuecomment-510913015 is a workaround and works for me.

**Comment by m1kola** [comment]
This is very weird. I upgraded macOS from 10.14.5 (18F132) to 10.14.6 (18G84) couple of days ago and had the same issue after the upgrade. Today it works fine even without the workaround 🤨
