### ISSUE TITLE
Containers unreachable from host processes

### ISSUE THREAD

**Issue by DimitriHautot** [docker/for-mac#3740]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:50CEBFF4-8CE7-4803-B9C4-C84DF8E87C9B/20190702144853

### Expected behavior
Containers keep receiving network packets from Java processes running in the host.

### Actual behavior
After some (random?) time, my Java processes can't connect anymore to the Redis and/or RabbitMQ containers.

### Information
I have this problem for weeks on my machine.
I'm using the latest stable release, 2.0.0.3 (31259).
Please note that the `docker` command is still responsible, and that I am able to restart the containers. However, this doesn't fix the problem. Only restarting the whole Docker stack does the trick.
  - macOS Version:10.14.5

### Diagnostic logs
```
Diagnose succeded

```

### Steps to reproduce the behavior
Unfortunately, I haven't found yet a deterministic way to reproduce it.

**Comment by programmer-git** [comment]
I am also facing the same issue, any update on this ?. It just intermittently happens, it needs a docker restart to fix this until it breaks again.
