### ISSUE TITLE
docker: Error response from daemon: failed to create OCI runtime console socket: mkdir /tmp/pty891989927: permission denied: unknown.

### ISSUE THREAD

**Issue by ronenfreeman2** [docker/for-mac#3743]
Cannot create interactive shell with `docker run -it <image> bash`. This suddenly occurred and I am not sure what changed. It happens with any image.

Example:

`$ docker run -it ubuntu:18.04 bash`
> Output:
```
docker: Error response from daemon: failed to create OCI runtime console socket: mkdir /tmp/pty891989927: permission denied: unknown.
```

I'm not sure what permissions I need to change or if I can set Docker to create the socket in another location.

macOS Mojave
10.14.5

Docker Desktop 2.0.0.3
Engine: 18.09.2

**Comment by djs55** [comment]
@ronenfreeman2 could you upload a set of diagnostics after the failure with: whale menu -> Diagnose and Feedback and then upload the diagnostics and quote the id here?

**Comment by dwursteisen** [comment]
@djs55 I got the same issue. 

I tried to upload what you asked *but* I encounter some issue.

After clicking on Diagnose and feedback: 

<img width="832" alt="Capture d’écran 2019-07-09 à 16 28 51" src="https://user-images.githubusercontent.com/373097/60896538-d0812800-a266-11e9-9cd8-20643552c135.png">

After clicking on Upload: 

<img width="832" alt="Capture d’écran 2019-07-09 à 16 28 57" src="https://user-images.githubusercontent.com/373097/60896632-f8708b80-a266-11e9-8330-711442ce777a.png">


(nothing happened when I clicked on open)

I checked in the `/tmp` folder: I got no zip here…

**Comment by ronenfreeman2** [comment]
@djs55 I got the same problem as @dwursteisen trying to upload diagnostics.

**Comment by ulrich** [comment]
Hello @ronenfreeman2 did you tried to upload manually the diagnostic?

**Comment by ronenfreeman2** [comment]
Hi @ulrich. I had the same issue when trying manually

`Error uploading: open /tmp/AF14E1B2-AA72-448E-BE0D-D867212BC8D4/20190710124135.zip: no such file or directory`

**Comment by dwursteisen** [comment]
@ronenfreeman2 can you check your right on `/private/tmp` and `/tmp`?

on my computer it was: 
for `/tmp` (please note the link to `private/tmp`):
```
lrwxr-xr-x@    1 root  wheel     11  9 jan  2019 tmp -> private/tmp
```

for `/private/tmp`:
```
drwxr-xr-x    5 root  wheel   160 11 jul 09:35 tmp
```

For an unknown reason, the right are `755` on `/private/tmp`.

In this configuration, the command `docker run -it ubuntu:18.04 bash` failed.

```
docker: Error response from daemon: failed to create OCI runtime console socket: mkdir /tmp/pty136774337: permission denied: unknown.
```

By setting the right `777` on `/private/tmp` (and without touching on `/tmp`), the previous command is working as expected. So `sudo chmod 777 /private/tmp` fixed the issue.

Why the folder went from `755` to `777`? mystère et boule de gomme ! 🕵️‍♀️

**Comment by ulrich** [comment]
Hello,

On my laptop the rights are by default :

`
➜ pinata git: ✗ ll /private
total 0
drwxr-xr-x    6 root  wheel   192B Jan 25 15:17 .
drwxr-xr-x   28 root  wheel   896B Jun 20 15:09 ..
drwxr-xr-x  116 root  wheel   3.6K Jul 11 09:46 etc
drwxr-xr-x    2 root  wheel    64B Aug 18  2018 tftpboot
drwxrwxrwt   21 root  wheel   672B Jul 11 09:46 tmp
drwxr-xr-x   26 root  wheel   832B Jan 25 15:22 var
`

I don't understand why you have this permissions. I think the issue can be to close?

**Comment by dwursteisen** [comment]
> I don't understand why you have this permissions. I think the issue is resolved?

I don't understand neither. It's like a software with enough access (the OS? Docker?) change the permission on this folder.

For me, it's "solved". But I propose to wait the answer from @ronenfreeman2 if it fixed on his computer too. If no response is received by tomorrow, you can close this issue I think.

Thanks for your time.

**Comment by ronenfreeman2** [comment]
Thank you @dwursteisen. I have no idea how the permissions changed on that folder but changing them back to `777` solved the issue. @ulrich issue resolved thanks!

**Comment by ulrich** [comment]
Cool

**Comment by mpaw** [comment]
@dwursteisen @ronenfreeman2 By and chance are you on a mac and did this happen after an upgrade to Catalina?

**Comment by dwursteisen** [comment]
Yes on a Mac but no, not on Catalina (I didn't upgrade yet).

I don't think it was just after the previous OS upgrade 🤔

Le lun. 14 oct. 2019 à 18:37, Marcin Pawelek <notifications@github.com> a
écrit :

**Comment by mpaw** [comment]
I ran into this issue after a Catalina upgrade

**Comment by ronenfreeman2** [comment]
@mpaw it was before the upgrade was out. I found a piece of code I had written had changed the permissions of this folder accidentally

**Comment by lxiongh** [comment]
> @ronenfreeman2 can you check your right on `/private/tmp` and `/tmp`?
> 
> on my computer it was:
> for `/tmp` (please note the link to `private/tmp`):
> 
> ```
> lrwxr-xr-x@    1 root  wheel     11  9 jan  2019 tmp -> private/tmp
> ```
> 
> for `/private/tmp`:
> 
> ```
> drwxr-xr-x    5 root  wheel   160 11 jul 09:35 tmp
> ```
> 
> For an unknown reason, the right are `755` on `/private/tmp`.
> 
> In this configuration, the command `docker run -it ubuntu:18.04 bash` failed.
> 
> ```
> docker: Error response from daemon: failed to create OCI runtime console socket: mkdir /tmp/pty136774337: permission denied: unknown.
> ```
> 
> By setting the right `777` on `/private/tmp` (and without touching on `/tmp`), the previous command is working as expected. So `sudo chmod 777 /private/tmp` fixed the issue.
> 
> Why the folder went from `755` to `777`? mystère et boule de gomme ! 🕵️‍♀️

Change folder to `777` then **restart docker**

**Comment by Anishmourya** [comment]
sudo chmod 777 /private/tmp worked for me.

**Comment by phrfpeixoto** [comment]
I had this issue, but only then trying to map ports.
Solved like this: https://github.com/laradock/laradock/issues/1135
