### ISSUE TITLE
LAN is not accessible from containers

### ISSUE THREAD

**Issue by pomo-mondreganto** [docker/for-mac#3745]
I cannot connect to other hosts in LAN from inside of docker container when using Docker for Mac. I run any image and try to connect using `nc` to a listener on other host: 

Listener on `192.168.1.8`:

```
nc -nlvp 1337
```

On my MBP 2017: 

```
docker run -it alpine:3.8 sh
```

Then inside:

```
nc 192.168.1.8 1337
```

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A53EFD6A-065F-4CC9-876D-8CBEDCF7C153/20190707124536

### Expected behavior

Connection establishes.

### Actual behavior

Connection is never established, LAN hosts cannot be accessed.

### Information

  - macOS Version: 10.14.5

About 2 month ago there was no problem connecting to LAN hosts, but I can't point to an exact time it started (I rarely use such a feature). Problem is reproducible and occurs in all cases. 

All LAN hosts (including tested above) are accessible from the host machine (Mac OS). Moreover, when I run the same image (`alpine:3.8`) on another host running docker on raspbian, LAN can be accessed from inside the container.

### Diagnostic logs

```
Docker for Mac: 2.0.0.3 (31259)
Engine: 18.09.2
Machine: 0.16.1

Diagnose succeded

```

### Steps to reproduce the behavior

  1. `docker run -it alpine:3.8 sh`
  2. Connect from inside container to any host in LAN

**Comment by ericparton** [comment]
I'm having the exact same problem, but it only seems to occur when I turn on Kubernetes. Are you also using Kubernetes?

**Comment by ericparton** [comment]
I've also tried this on stable and edge and it doesn't make a difference. At first I thought it was DNS related, but commands like curl don't even work directly against the IP address.

**Comment by pomo-mondreganto** [comment]
No, I have never enabled Kubernetes on that host. After switching to Edge version the problem disappeared, so that's my solution for now.

**Comment by ericparton** [comment]
Hmmm, I still have the problem even on the Edge version. That being the case, I might create a different issue

**Comment by benjhess** [comment]
Same problem for me on 2.0.0.3. Uninstalling and Reinstalling fixed it for me
