### ISSUE TITLE
Mac OS Sierra Beta 6 issue 

### ISSUE THREAD

**Issue by viral-1** [docker/for-mac#375]
### Information

Diagnostic ID: 671E72CE-8A2D-405F-B028-AD96889D05EF
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Fixed with beta 25

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
