### ISSUE TITLE
Unable To Use Localhost Port 80 ; Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

### ISSUE THREAD

**Issue by TheSearcher** [docker/for-mac#3755]
I am using a Mac Book Pro

I need to use my localhost Port :80 but i keep getting this ERROR message:

```
Error response from daemon: driver failed programming external connectivity on endpoint nostalgic_ride : Error starting userland proxy:

Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE).
```

this issue arose because i tried to use docker to do this:

> docker run -it -p 80:80 -p 443:443 nginx

I did a search to see what is listening on all my ports:

> 
sudo lsof -nP | grep LISTEN

```

UserEvent   41               root  113u     IPv6 0xa09c168d9d24ed2f         0t0      TCP [fe80:8::aede:48ff:fe00:1122]:49153 (LISTEN)
UserEvent   41               root  114u     IPv6 0xa09c168d9d24e1af         0t0      TCP [fe80:8::aede:48ff:fe00:1122]:49154 (LISTEN)
UserEvent   41               root  115u     IPv6 0xa09c168d9d24dbef         0t0      TCP [fe80:8::aede:48ff:fe00:1122]:49155 (LISTEN)
UserEvent   41               root  116u     IPv6 0xa09c168d9d24f2ef         0t0      TCP [fe80:8::aede:48ff:fe00:1122]:49156 (LISTEN)
php-fpm     48               root    8u     IPv4 0xa09c168d9d7b322f         0t0      TCP 127.0.0.1:9000 (LISTEN)
php-fpm    221               _www    9u     IPv4 0xa09c168d9d7b322f         0t0      TCP 127.0.0.1:9000 (LISTEN)
php-fpm    222               _www    9u     IPv4 0xa09c168d9d7b322f         0t0      TCP 127.0.0.1:9000 (LISTEN)
EEventMan  351               tom    4u     IPv4 0xa09c168da7672eaf         0t0      TCP *:2968 (LISTEN)
java       648               tom   69u     IPv6 0xa09c168d9d24c4ef         0t0      TCP [fe80:1::1]:49185 (LISTEN)
LogiMgrDa  715               tom    4u     IPv4 0xa09c168da914f52f         0t0      TCP *:59866 (LISTEN)
httpd      860               root    4u     IPv6 0xa09c168da64892ef         0t0      TCP *:80 (LISTEN)
httpd      864               _www    4u     IPv6 0xa09c168da64892ef         0t0      TCP *:80 (LISTEN)
httpd      955               _www    4u     IPv6 0xa09c168da64892ef         0t0      TCP *:80 (LISTEN)
```
Questions:

It appears that there are 3 instances of httpd listening on Port 80. If so, does anyone know what these httpd are for and whether it's safe to remove them.
If so, how do I kill/remove them.

**ANSWER TO SIMILAR QUESTIONS ON THIS ISSUE:**

these answers do not help me beucase they all recommend simply changing the port. however i need port 80 for localhost development

**Comment by djs55** [comment]
The `httpd` processes are not part of Docker Desktop. Perhaps they are left over from a previous (non-Dockerised) run of an application.  Perhaps find the path to the `httpd` binary to see where it comes from-- perhaps it is installed from homebrew or Mac ports and can be uninstalled? It's also worth seeing whether it is set to auto-start from `launchd`: try `sudo launchctl list` and remove it from there just in case it is set to auto-start.

**Comment by TheSearcher** [comment]
hi @djs55 . thank you so much for your response. but what command do you use to find the path for the httpd binarys. i also did the sudo launchctl list and got this : 

> 
sudo launchctl lis

t 
```
PID     Status  Label
80      0       com.apple.coreservices.launchservicesd
```

first question about above; this seem to be somting to do with the mac.Accordinly, if i remove it will it affect anything on my laptop.

second question; how do i remove it. i mean, do you know the command to remover it

**Comment by petr-ujezdsky** [comment]
@TheSearcher 
I would recommend to **close this issue since it is not related to docker**. You have opened ports from another application that blocks docker to run your container.

I think the `httpd` process is spawned by the `php-fpm`. You can stop `httpd` via `kill <PID>`
```
$ kill 860
$ kill 864
$ kill 955
```
In case something stops working you should be able to just restart the mac and the services should be started again (since you do not know how to operate them).
