### ISSUE TITLE
Fatal Error: cannot install symlinks in /usr/local/bin (stage 4)

### ISSUE THREAD

**Issue by andyspicer** [docker/for-mac#3756]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6E07DD5C-2224-4CD5-A0B0-EC9C944C7EB3/20190717183632

### Expected behavior

Running Docker for Mac on Mac OS Version 10.14.6 Beta. Have Docker set to start with the OS.

### Actual behavior

Docker fails to launch during OS startup with the error: Fatal Error: cannot install symlinks in /usr/local/bin (stage 4)

### Information

  - macOS Version: 10.14.6 Beta
  - Error is reproducible. It occurs every time the OS is restarted and Docker tries to launch.
  - I am unable to pinpoint when the behavior began.
  - After Docker fails to launch at startup it is possible to then manually start it and that succeeds.

### Diagnostic logs

Docker for Mac: Version 2.0.0.3 (31259)
Channel: stable 8858db33c8  

[20190717183632.zip](https://github.com/docker/for-mac/files/3403391/20190717183632.zip)

**Comment by hendie** [comment]
Exact same behaviour for me.

- macOS 10.14.6 (just installed, first boot since upgrade)
- Docker for Mac 2.0.0.3 (31259)

I also starts fine with a manual restart after the initial failure.
