### ISSUE TITLE
exec fails if command is wrapped in double quotes.

### ISSUE THREAD

**Issue by pratiksanglikar** [docker/for-mac#3757]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:0812C24F-9741-4AD7-9140-27650550183D/20190718000410

### Expected behavior
`"docker" exec -i 08e42c8511ff "/bin/sh -c "echo Hello;echo yababa" --interpreter=vscode"`
Should print 
```
Hello
yababa
```
### Actual behavior
```
$  "docker" exec -i 08e42c8511ff "/bin/sh -c "echo Hello;echo yababa" --interpreter=vscode"
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"/bin/sh -c echo\": stat /bin/sh -c echo: no such file or directory": unknown
yababa --interpreter=vscode
$ 
```
### Information
  - Is it reproducible?
      Always reproducible.

  - Is the problem new?
      Not sure

  - Did the problem appear with an update?
      Not sure

  - A reproducible case if this is a bug, Dockerfiles FTW.
      `docker run -it mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine /bin/sh`
  - macOS Version: 
      macOS Mojave 10.14.5 (18F132)

### Diagnostic logs
```
Diagnose succeded
```

### Steps to reproduce the behavior

  1. `docker run -it mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine /bin/sh`
  2. Open another instance of the terminal and execute - `"docker" exec -i <container-id> "/bin/sh -c "echo Hello;echo yababa" --interpreter=vscode"`
  3. Notice the error.

**Comment by stephen-turner** [comment]
Isn't this just a shell parsing question, nothing to do with docker?

**Comment by pratiksanglikar** [comment]
I just realized, it is indeed shell parsing question!
