### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by sarawutymtz** [docker/for-mac#376]
### Information

Diagnostic ID: 3A44C33F-7DC4-4F27-AA32-0959EE950063
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.3 (Build 15D21)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 3A44C33F-7DC4-4F27-AA32-0959EE950063/20160820-134321.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.vmnetd][35017] <Notice>: User 501 has container folder /Users/David/Library/Containers/com.docker.docker/Data/s60
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.vmnetd][35017] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.vmnetd][35017] <Notice>: User 501 has container folder /Users/David/Library/Containers/com.docker.docker/Data/s60
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.vmnetd][35017] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.docker][34974] <Error>: Symlinks are not correctly installed.
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.docker][34974] <Notice>: com.docker.osx.hyperkit.linux launched with PID 35021
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.frontend][35022] <Critical>: dial unix /Users/David/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.osx.hyperkit.linux][35021] <Notice>: Acquired task manager lock
Aug 20 12:47:24 Sarawutymtz Docker[com.docker.osx.hyperkit.linux][35021] <Notice>: Maximum number of file descriptors is 10240
```
