### ISSUE TITLE
MacOS docker-machine env, eval permission denied (/Users/User/.docker/machine/machines/my-awesome-server/config.json: permission denied)

### ISSUE THREAD

**Issue by dongjae93** [docker/for-mac#3765]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7B4D80B1-15BB-4091-96D4-C9D45CD9FCA9/20190724183539

### Expected behavior
  docker-machine env my-awesome-server & 
 eval $(docker-machine env my-awesome-server)
to not give me permission error
### Actual behavior
open /Users/DJ/.docker/machine/machines/my-awesome-server/config.json: permission denied
### Information

  - macOS Version: 10.14.5

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ... if I run those command in my shell it'll say that error
  2. ...

**Comment by JairajJangleSLIOT** [comment]
Getting the same issue, running on macOS 10.14.6. I am a beginner and I've followed all the steps to setup docker for macOS as mentioned in the documentation. 

`WARNING: Error loading config file: /Users/myuser/.docker/config.json: open /Users/myuser/.docker/config.json: permission denied`
