### ISSUE TITLE
Does macOS Docker Desktop secretly mine Bitcoin in the background?

### ISSUE THREAD

**Issue by sterichards** [docker/for-mac#3767]
Running macOS Docker desktop brings an i7 with 32GB RAM to its knees

How is it possible that Docker can need so many system resources?

**Comment by zaoqi** [comment]
some Docker may need so many system resources

**Comment by wilomgfx** [comment]
> Running macOS Docker desktop brings an i7 with 32GB RAM to its knees
> 
> How is it possible that Docker can need so many system resources?

depends what you run m8

**Comment by sterichards** [comment]
A Symfony 2.7 REST API web service but the same system hog happens also using Symfony 3.4

Some days I only get the high latency, which i'm aware is due to Docker macOS having to launch a layer for every request made to the container

But, there are worse days when my whole system has a huge slowdown. It's a similar system slowdown you get when your IDE decides to re-index but it is multiple times worse
