### ISSUE TITLE
update processing occur error .

### ISSUE THREAD

**Issue by insight1989** [docker/for-mac#377]
### Information

Diagnostic ID: 355626BF-A9DD-4895-9645-E2AD1D38B084
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ... update . wait. 
2. ...click button update. then .....error ..

**Comment by coke** [comment]
I'm having a similar issue; it would be VERY helpful if there were diagnostics showing what sort of network activity was being attempted before failure. (so we could track down how to configure network/proxy etc.)

**Comment by mchiang0610** [comment]
For sierra related issues, beta 25 should fix most of them. Please update either to the beta channel. 

If you are uncomfortable updating to beta, we will be releasing stable version soon. 

https://download.docker.com/mac/beta/Docker.dmg

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
