### ISSUE TITLE
All images gone after upgrade to 2.1.0

### ISSUE THREAD

**Issue by huineng** [docker/for-mac#3772]
release notes says ..

```
This release contains a Kubernetes upgrade. Your local Kubernetes cluster will be reset after install.
```

but it also wiped out all of my images.

This is not the first time a major upgrade wipes out all images, very unreliable

stable version

**Comment by yamaszone** [comment]
I have been bitten by this issue as well. In addition to all image disappearance, the Docker Desktop interface is fully unresponsive; none of the options in the menu works (and can't even get the Diagnostic ID). Apparently this is a recurring issue without any real solutions: https://github.com/docker/for-mac/issues/1175. It looks like the maintainers are not tracking this issue yet. I have been using CoreOS (for it's battle-tested support for Docker) since 2013 until earlier this year to take advantage of ease of host directory mounts (compare to mounting host directories into guest VM via `vagrant`) during local development. It felt reliable for the most part (and helped me avoiding `vagrant` management headache) until I upgraded from `v2.0.x` to `v2.1.0`. This is definitely a disappointing experience forcing me to consider more reliable alternatives.

**Comment by jmalczak** [comment]
The same happened to me yesterday.

**Comment by markwilliams970** [comment]
Same thing happened during my upgrade from 2.0.0 to 2.1.0.1. Really disappointing to see this issue persist for years with no solution.

There really should be a rollback option.


  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FA85D5BE-D700-4EBE-9093-729914CE8A6E/20190824134213

### Expected behavior

Containers are preserved when upgrading from Desktop 2.0.0 to 2.1.0.1

### Actual behavior

All containers lost

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: version 2.1.0.1

```

**Comment by lovecactus** [comment]
Same here. 
Docker automatically check for updates and now I need to setup all env again.
Appreciate for teaching me how important to get everything backed up.

**Comment by davidbalzan** [comment]
Happened to me again for the second time when upgrading to version 2.1.0.4 without any visible warnings. I wonder how such an issue which seems like it's occurring to a lot of people keeps popping up version after version.

**Comment by ibrahim-aburajab** [comment]
Joining the upgrade game, any solution until now?

**Comment by huineng** [comment]
when i reported this issue, it was because all was gone
Then i had one or 2 upgrades and all stayed there
with the latest update 2.1.0.4 gone again

**Comment by huineng** [comment]
2.1.0.5  same story again... can someone now please confirm that updates to docker for mac deletes all from kubernetes

**Comment by jarrettj** [comment]
Same here! Just happened to me. :(

![Screenshot 2019-11-21 at 10 09 29](https://user-images.githubusercontent.com/777547/69319021-0ab3fa80-0c47-11ea-86b8-6f941ad8abf2.png)

**Comment by guineau** [comment]
Same here :(

**Comment by AnatolyR** [comment]
Update to 2.1.0.5 on Mac removed all containers :( total shit

**Comment by guineau** [comment]
Same here. Caught me by surprise when suddenly none of my services were working.

**Comment by antwal** [comment]
> Update to 2.1.0.5 on Mac removed all containers :( total shit

the same thing happened to me; I lost 120Gb of images and I couldn't even recover them from the backup

**Comment by vmassol** [comment]
Same here... happened again to me. Not from an upgrade but from clicking "Reset to factory defaults" after I made a config change that prevented Docker for Mac from restarting fine. And all I wanted was to remove the config I had set.... :( Very disappointing. Gigabytes and years of images and containers lost.

**Comment by hohwille** [comment]
Same happened to me. Any ideas how to recover? I hope that docker desktop did not wipe containers on purpose. So is the data still expected to be somewhere on my disc? Or did some bug cause to physically delete everything?
```
find Library/Containers/com.docker.docker/Data
Library/Containers/com.docker.docker/Data
Library/Containers/com.docker.docker/Data/filesystem-event.sock
Library/Containers/com.docker.docker/Data/filesystem-volume.sock
Library/Containers/com.docker.docker/Data/docker-api.sock
Library/Containers/com.docker.docker/Data/tasks
Library/Containers/com.docker.docker/Data/tasks/com.docker.vpnkit
Library/Containers/com.docker.docker/Data/tasks/vpnkit-bridge
Library/Containers/com.docker.docker/Data/tasks/com.docker.driver.amd64-linux
Library/Containers/com.docker.docker/Data/tasks/com.docker.osxfs
Library/Containers/com.docker.docker/Data/tasks/com.docker.hyperkit
Library/Containers/com.docker.docker/Data/docker.raw.sock
Library/Containers/com.docker.docker/Data/filesystem-export.sock
Library/Containers/com.docker.docker/Data/memlogdq.sock
Library/Containers/com.docker.docker/Data/vpnkit.diag.sock
Library/Containers/com.docker.docker/Data/default.profraw
Library/Containers/com.docker.docker/Data/backend-for-guest.sock
Library/Containers/com.docker.docker/Data/vpnkit.port.sock
Library/Containers/com.docker.docker/Data/lifecycle-server.sock
Library/Containers/com.docker.docker/Data/docker.sock
Library/Containers/com.docker.docker/Data/diagnosticd.sock
Library/Containers/com.docker.docker/Data/vpnkit.eth.sock
Library/Containers/com.docker.docker/Data/task.lock
Library/Containers/com.docker.docker/Data/vpnkit.data.sock
Library/Containers/com.docker.docker/Data/log
Library/Containers/com.docker.docker/Data/log/host
Library/Containers/com.docker.docker/Data/log/host/com.docker.backend.log
Library/Containers/com.docker.docker/Data/log/host/com.docker.diagnose.log
Library/Containers/com.docker.docker/Data/log/host/com.docker.supervisor.log
Library/Containers/com.docker.docker/Data/log/host/com.docker.driver.amd64-linux.log
Library/Containers/com.docker.docker/Data/log/host/vpnkit-bridge.log
Library/Containers/com.docker.docker/Data/log/host/docker-credential-desktop.log
Library/Containers/com.docker.docker/Data/log/vm
Library/Containers/com.docker.docker/Data/log/vm/onboot.009-mount-kube-images.log
Library/Containers/com.docker.docker/Data/log/vm/diagnose.log
Library/Containers/com.docker.docker/Data/log/vm/sntpc.log
Library/Containers/com.docker.docker/Data/log/vm/acpid.log
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.7
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.0
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.1
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.6
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.8
Library/Containers/com.docker.docker/Data/log/vm/kubelet.log
Library/Containers/com.docker.docker/Data/log/vm/onboot.005-extend.log
Library/Containers/com.docker.docker/Data/log/vm/sntpc.out.log
Library/Containers/com.docker.docker/Data/log/vm/docker.log.8
Library/Containers/com.docker.docker/Data/log/vm/socks.out.log
Library/Containers/com.docker.docker/Data/log/vm/docker.log.6
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log
Library/Containers/com.docker.docker/Data/log/vm/docker.log.1
Library/Containers/com.docker.docker/Data/log/vm/docker.log.0
Library/Containers/com.docker.docker/Data/log/vm/docker.log.7
Library/Containers/com.docker.docker/Data/log/vm/onboot.008-mount-docker.log
Library/Containers/com.docker.docker/Data/log/vm/onboot.004-format.log
Library/Containers/com.docker.docker/Data/log/vm/host-timesync-daemon.log
Library/Containers/com.docker.docker/Data/log/vm/memlogd.log
Library/Containers/com.docker.docker/Data/log/vm/kmsg.log
Library/Containers/com.docker.docker/Data/log/vm/diagnose.out.log
Library/Containers/com.docker.docker/Data/log/vm/trim-after-delete.log
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.3
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.4
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.5
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.log.2
Library/Containers/com.docker.docker/Data/log/vm/vpnkit-forwarder.log
Library/Containers/com.docker.docker/Data/log/vm/docker.out.log
Library/Containers/com.docker.docker/Data/log/vm/lifecycle-server.out.log
Library/Containers/com.docker.docker/Data/log/vm/docker.log
Library/Containers/com.docker.docker/Data/log/vm/onboot.000-metadata.log
Library/Containers/com.docker.docker/Data/log/vm/onboot.010-bridge.log
Library/Containers/com.docker.docker/Data/log/vm/docker.log.2
Library/Containers/com.docker.docker/Data/log/vm/docker.log.5
Library/Containers/com.docker.docker/Data/log/vm/docker.log.4
Library/Containers/com.docker.docker/Data/log/vm/docker.log.3
Library/Containers/com.docker.docker/Data/osxfs.sock
Library/Containers/com.docker.docker/Data/vpnkit.pcap.sock
Library/Containers/com.docker.docker/Data/vms
Library/Containers/com.docker.docker/Data/vms/0
Library/Containers/com.docker.docker/Data/vms/0/tty
Library/Containers/com.docker.docker/Data/vms/0/00000002.00001003
Library/Containers/com.docker.docker/Data/vms/0/config.iso
Library/Containers/com.docker.docker/Data/vms/0/00000002.00001002
Library/Containers/com.docker.docker/Data/vms/0/hyperkit.json
Library/Containers/com.docker.docker/Data/vms/0/00000002.0000f3a4
Library/Containers/com.docker.docker/Data/vms/0/hyperkit.pid
Library/Containers/com.docker.docker/Data/vms/0/00000002.000005f4
Library/Containers/com.docker.docker/Data/vms/0/guest.00000948
Library/Containers/com.docker.docker/Data/vms/0/lifecycle-server.sock
Library/Containers/com.docker.docker/Data/vms/0/00000003.000005f5
Library/Containers/com.docker.docker/Data/vms/0/00000002.00001000
Library/Containers/com.docker.docker/Data/vms/0/00000002.00001001
Library/Containers/com.docker.docker/Data/vms/0/guest.000005f5
Library/Containers/com.docker.docker/Data/vms/0/00000003.00000948
Library/Containers/com.docker.docker/Data/vms/0/log
Library/Containers/com.docker.docker/Data/vms/0/connect
Library/Containers/com.docker.docker/Data/vms/0/data
Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw
Library/Containers/com.docker.docker/Data/backend.sock
Library/Containers/com.docker.docker/Data/gui-api.sock
```
Mounted data is still in my custom `docker` folder. Still I am not sure if I can recreate containers with the same mounts and my DBs will pick up properly from there. At least I will not try without making additional backups before.

Just as a general feedback. Software of reasonable criticallity requires a proper QA process. It is actually incredible that it seems there was no process in place to first distribute an update to a small set of users before shipping out to the wild (canary deploys and all the valuable things we learned in the docker world are not applied to docker itself). It hope you will consider this for the future (if this is still maintained).

**Comment by lixiii** [comment]
Same thing happened to me when I upgraded to 2.2.0.3. Any updates to this problem at all?

**Comment by runnerlt** [comment]
Lost all my images yesterday. Unhappy.

**Comment by Myhael76** [comment]
Upgraded today to 2.3.0.4 (46911) and activated WSL2 support.
All contents were lost. Not a big deal for me, I consider them ephemeral, however I have no idea is the old content was cleaned up or leaked...

**Comment by William-J-Earl** [comment]
Upgraded to 2.4.0.0, and all images are still present, but all Kubernetes containers and persistent volumes are gone.   At the very least, the "upgrade" prompt should warn and require confirmation about deleting all Kubernetes resources.  No more upgrades for me.

**Comment by aijogja** [comment]
I also got the same problem :(
All my containers and images are gone after upgrade the docker to the latest version.

Diagnostic ID : 46837092-52B5-48EF-B1EB-684331C6DFF8/20201203030353
