### ISSUE TITLE
Fail to start Docker. Error:  Docker.VmnetdError error 1

### ISSUE THREAD

**Issue by Yeleni** [docker/for-mac#3776]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by backendschool** [comment]
@Yeleni how did you solve the issue?

**Comment by Yeleni** [comment]
@backendschool I just opened the docker from the launchpad menu and don't get the error.

**Comment by rakonsake** [comment]
For me, I just turned off SIP, then Docker can run freely. (But don't understand WHY?)
