### ISSUE TITLE
Fatal error: The operation couldn't be completed. (NIO.SocketAddressError error 3.)

### ISSUE THREAD

**Issue by dhakshin83** [docker/for-mac#3777]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 352EC71D-375A-4A93-9F4B-7374456B0FD2/20190801102316

### Expected behavior
Running auto-update from version 2.0.0.3 to 2.1.0.0 - expect the latest version to run on macOS Mojave 10.14.6

### Actual behavior
Get a fatal error: The operation couldn't be completed. (NIO.SocketAddressError error 3.)

### Information

  - macOS Version: macOS Mojave 10.14.6

### Diagnostic logs

```
[20190801102316.zip](https://github.com/docker/for-mac/files/3456212/20190801102316.zip)

Docker for Mac: 2.1.0

```

### Steps to reproduce the behavior
  1. Just starting the app, it tries to run the helper. Asks for the admin password and I get the fatal error stated above
[20190801102316.zip](https://github.com/docker/for-mac/files/3456211/20190801102316.zip)

**Comment by dhakshin83** [comment]
Looks like an issue with the latest Docker Desktop Community 2.1.0.0 running on macOS Mojave 10.14.6

I've regressed to the previous Docker Community Edition 2.0.0.3 2019-02-15 as it works fine.

**Comment by nandana** [comment]
I had the same issue with the latest Docker Desktop Community 2.1.0.0 running on `macOS Mojave 10.14.6`.

**Comment by sarinamcfarland** [comment]
I've had this issue running on Mojave 10.14.5

**Comment by nsecord** [comment]
I have this issue running on High Sierra 10.13.6

Diagnostic ID: 9653915B-2579-4B7F-A6E5-351617222E35/20190804092614

[20190804092614.zip](https://github.com/docker/for-mac/files/3464749/20190804092614.zip)

**Comment by SannhetJaeger** [comment]
Have this issue installing on Mac Mojave 10.14.6

**Comment by TechnoTaff** [comment]
Also having issues on 10.14.6, had to roll back.

**Comment by pxsocs** [comment]
Same issue. Looks like many are experiencing similar problems. 
In my case, I can't start docker, same error. But the Diagnose result is __succeed__ which makes it even stranger.

**Comment by LyndonArmitage** [comment]
Any updates?

**Comment by carloshs1993** [comment]
Hi, 

Are there any updates on this? Still having trouble to install Docker last versions on macOS 10.15.2.

**Comment by novasdream** [comment]
> Hi,
> 
> Are there any updates on this? Still having trouble to install Docker last versions on macOS 10.15.2.

I try last version but get 
```
com.docker.backend cannot start Exit code 1
```


I downgrade to version/2.1.0.1 and get 
The operation couldn’t be completed. (NIO.SocketAddressError error 3.)


I receive some sugestion to run it from brew 

```
brew cask install https://raw.githubusercontent.com/ahousseini/homebrew-cask/3d8ed99786fa59b9830f524ef3b1151e6098eedb/Casks/docker.rb
```

This version work to me.
