### ISSUE TITLE
All container and images disappeared

### ISSUE THREAD

**Issue by HcwvDl** [docker/for-mac#3778]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rmahroua** [comment]
Same here. All containers and images are gone.

**Comment by krumpak** [comment]
I have the same issue on Mac
