### ISSUE TITLE
Getting image from ECR - no basic auth credentials on Docker for Mac 2.1.0.0

### ISSUE THREAD

**Issue by joepagan** [docker/for-mac#3779]
### Information

This has only happened since upgrading to `2.1.0.0 Stable` this afternoon. Was previously on 2.0.0.* (I think)
**Update:**
Tried `2.1.0.0 Edge` and I experience the same problem.
Reverted to `2.0.0.3` and works fine...

  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 271F2E49-1032-42FD-ABF7-24405721D24F/20190801135830

### Expected behavior

Login to ECR `$(aws ecr get-login --no-include-email --region eu-west-1)`
Run `docker-compose up --build`
docker builds then runs.

### Actual behavior

Met with error: `no basic auth credentials` when running `docker-compose up --build`

### Information

  - macOS Version: 10.14.5

### Diagnostic logs

```
Docker for Mac: version...
2.1.0.0
```

### Steps to reproduce the behavior

```
docker-compose up --build
Building image
Step 1/2 : FROM ****.dkr.ecr.eu-west-1.amazonaws.com/app-base/image:latest
ERROR: Service 'image' failed to build: Get https://1****.dkr.ecr.eu-west-1.amazonaws.com/v2/app-base/image/manifests/latest: no basic auth credentials
```

**Comment by ramarnat** [comment]
I am seeing the same issue, downgrading

**Comment by grumpy** [comment]
Same issue.  I see it leaving off the https:// prefix in the auths entry in config.json.
If I add the https:// manually to the auths entry in the config it works until I run login again.

**Comment by rcousens** [comment]
Is there any fix to this besides downgrading? I don't use a docker config.json, I just run the command spat out by AWS CLI for ECR login in my current shell then run docker-compose. 

The docker-compose command currently fails with the same error trying to pull an image from ECR when prior to upgrading this process worked fine.

**Comment by joepagan** [comment]
@rcousens no fix yet. I haven't tried 2.1.0.1 have you if you've only just tried?

**Comment by rcousens** [comment]
@joepagan I have tried 2.1.0.1, no fix in there!

**Comment by joepagan** [comment]
Ok, still a bug then.

**Comment by ijaureguialzo** [comment]
> Same issue. I see it leaving off the https:// prefix in the auths entry in config.json.
> If I add the https:// manually to the auths entry in the config it works until I run login again.

Adding https:// as stated worked for me after upgrading to 2.1.0.1 broke the download from private registry.

**Comment by joepagan** [comment]
@ijaureguialzo isn't that only a temp fix and you will have to do it every time you login to ECR?

**Comment by ijaureguialzo** [comment]
> @ijaureguialzo isn't that only a temp fix and you will have to do it every time you login to ECR?

Yes, of course. It's just a fix in order not to have to downgrade.

**Comment by jondkelley** [comment]
How do we make docker never ask to upgrade again? Anyone know?

**Comment by EmmN** [comment]
When is this going to be fixed?

**Comment by joepagan** [comment]
It would certainly be nice to get a response from anyone on the Docker team for a way forward (even if they don't want to fix this), maybe they don't have people to manage the issues on their repos?

It's also likely that the Docker team simply just don't care about this as the issue is with images hosted on ECR (A third party Amazon service), not the official Docker hub (which likely works just fine).

Until then, I think our options are to: 

- Create an issue with Amazon support, if anyone actually pays the high prices for Technical support, can you please create an issue with them? https://console.aws.amazon.com/support/cases#/create?issueType=technical
- Tweet the hell out of them and tell them their service just isn't working... If anyone can retweet: https://twitter.com/lexbi/status/1186560309215006722

**Comment by rally25rs** [comment]
I just spent like 6 hours of my life trying to figure this out yesterday only to discover this is a known issue. A local `docker pull` works.

Docker for Mac v2.1.0.4
Kubernetes v1.14.7

**Comment by fernandodbc** [comment]
Same issue for me. To work just use `docker pull` before building. Thanks @rally25rs

**Comment by yylonly** [comment]
> Same issue. I see it leaving off the https:// prefix in the auths entry in config.json.
> If I add the https:// manually to the auths entry in the config it works until I run login again.

Can you tell me how to do this with Docker Desktop? Thanks

**Comment by realshadow** [comment]
> > Same issue. I see it leaving off the https:// prefix in the auths entry in config.json.
> > If I add the https:// manually to the auths entry in the config it works until I run login again.
> 
> Can you tell me how to do this with Docker Desktop? Thanks

In my ~/.docker/config.json were two lines in the auths section - one with https:// and one without. I have removed the one without https:// and docker pull worked again

**Comment by jayco** [comment]
I can confirm @realshadow suggestion worked for me.

**Comment by jtoberon** [comment]
Josh from ECR here. We will investigate.

**Comment by simonweil** [comment]
This solution worked for me:
`eval "$(aws ecr get-login --no-include-email | sed 's|https://||')"`

**Comment by Danushka96** [comment]
Same issue with Java API client for Docker

**Comment by steffenlyng** [comment]
@jtoberon How's the investigation going ?

**Comment by joepagan** [comment]
I can confirm that updating to docker v2.2.0.0 resolves this issue! 🎉 
@jtoberon

**Comment by doque** [comment]
Hi, I'm facing the same issue on v2.2.0.3:

```
$ Code ⟩ eval (aws ecr get-login --region eu-central-1 --no-include-email | sed 's|https://||')
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

$ Code ⟩ docker pull 669473935556.dkr.ecr.eu-central-1.amazonaws.com/next-web:latest                                                                                                      
Error response from daemon: Get https://669473935556.dkr.ecr.eu-central-1.amazonaws.com/v2/next-web/manifests/latest: no basic auth credentials

$ Code ⟩ cat ~/.docker/config.json
{
	"auths": {
		"669473935556.dkr.ecr.eu-central-1.amazonaws.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.5 (darwin)"
	},
	"credsStore": "osxkeychain"
}
```

**Comment by ghaed** [comment]
I am seeing the same issue in 2.2.0.4

**Comment by joepagan** [comment]
I'm now on 2.2.0.4 and just built an image using a private ECR base image... Logged in with `$(aws ecr get-login --no-include-email --region eu-west-1)` too.

The `FROM` in my dockerfile was: `FROM 123123123123.dkr.ecr.eu-west-1.amazonaws.com/base/php-image:0.0.11 AS php`.

**Comment by aberezin-acertus** [comment]
I am seeing the same issue in 2.2.0.4

**Comment by standev** [comment]
Still seeing the same issue in 2.3.1.0 (45408) on Mac. Please reopen.

**Comment by Georgian** [comment]
So I installed `aws-credentials-helper` by downloading the repo and compiling it myself. I discovered that I used the wrong compile command: `make docker` instead of `make docker TARGET_GOOS=darwin` (I'm on Mac). The resulting `bin/local/docker-credential-ecr-login` was not executable initially.
