### ISSUE TITLE
After upgrade to 2.1.0, containers won't start

### ISSUE THREAD

**Issue by gorandev** [docker/for-mac#3781]
I get "Error response from daemon: Mounts denied: no context set" on containers that were running perfectly before I updated. Should I downgrade? What changed?

Thanks for reading!

**Comment by gorandev** [comment]
I downgraded to 2.0.0.3 and everything went back to normal. What should I do to upgrade to 2.1.0?

**Comment by quinncomendant** [comment]
I had the same error:

<img width="884" alt="Screen Shot 2019-08-03 at 17 05 39" src="https://user-images.githubusercontent.com/6884276/62417248-f0f79480-b610-11e9-8bdb-64e27c10f998.png">

But after restarting Docker (Docker menu → Restart), I was able to start my containers.

In case it's helpful, I ran a diagnostic while I had the problem and uploaded it under this key: `89907598-8C84-4F68-9D36-B2C2E414BBD0/20190803220001`.

**Comment by sjuniorti** [comment]
I had the same issue, couldn't make it work without downgrade it to 2.0.0!

**Comment by moret** [comment]
I just had the same issue today, and restarting did seem to help.
