### ISSUE TITLE
ERROR: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3

### ISSUE THREAD

**Issue by ramazan86** [docker/for-mac#3782]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics

I have followed the following tutorial **https://docs.docker.com/compose/gettingstarted/**. 
After I run the command **docker-compose up** I become the failure: 
Confusing is the difference of the log-output between my terminal and from the the above related tutorial. 
In my terminal the first-line after the command (docker-compose up) is **Building web** and in the tutorial **Creating network "composetest_default" with the default driver**.

### Diagnostic logs

```
Step 5/9 : RUN apk add --no-cache gcc musl-dev linux-headers
 ---> Running in 7f7c5a2b45c3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: could not connect to server (check repositories file)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz: could not connect to server (check repositories file)
ERROR: unsatisfiable constraints:
  gcc (missing):
    required by: world[gcc]
  linux-headers (missing):
    required by: world[linux-headers]
  musl-dev (missing):
    required by: world[musl-dev]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3

```

### Information

  - macOS Version: macOs Mojave, 10.14.6 (18G84)

### Steps to reproduce the behavior

  1. Do all steps in the tutorial, which is mentioned

**Comment by guillaumerose** [comment]
The error seems related to network. It works on my machine. Can you retry ? Can you resolve `dl-cdn.alpinelinux.org` ? Can you get this page on your host machine ?

**Comment by harisamjad** [comment]
i run the command again "docker-compose up"...it works...its a network issue.

**Comment by prabhashibuddhima** [comment]
I'm facing the same issue and my network is finely working without no issues
