### ISSUE TITLE
Error with docker-compose: docker-credential-desktop not installed or not available in PATH

### ISSUE THREAD

**Issue by sirviot** [docker/for-mac#3785]
Cannot start containers any more after update. I don't know how the error `docker-credential-desktop not installed or not available in PATH` should be fixed.

I tried to remove the whole `~/.docker` directory and restart the Docker Desktop, but it didn't help.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86EC26ED-0429-4F94-8758-A71185F63B59/20190802103144

### Expected behavior
Should start to build image and start a container with `docker-compose up`

### Actual behavior
Starts the build but fails
```
Building server
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 301, in get_all_credentials
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/dockerpycreds/store.py", line 25, in __init__
dockerpycreds.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
[8929] Failed to execute script docker-compose
```

### Information
Problems started after updating 
 - Docker Desktop 2.1.0.0 (36874)
 - macOS Version: macOS Mojave 10.14.5

**Comment by sirviot** [comment]
Where/how on earth can I install the `docker-credential-desktop`?
Shouldn't it be part of the update?
On terminal
```
$ docker [tab]
docker          docker-compose  docker-machine 
```

**Comment by sirviot** [comment]
The files can be found under `/Applications`
```
$ find /Applications/Docker.app/Contents/ -name 'docker-credential-desktop'
/Applications/Docker.app/Contents//Resources/bin/docker-credential-desktop
```
For some reason these were not linked in the `/usr/local/bin`which was the cas on another computer.

**Comment by sirviot** [comment]
I figured that maybe a reinstall would be in place here. So I proceeded to uninstalled the whole Docker-thing. Did _not_ know that in order to download the latest Docker these days one needs to create a user account to Docker Hub.

**Comment by sirviot** [comment]
After furious account creating, downloading, installing and proxy-configuring the latest version of Docker was once again setup on my mac.

`docker-compose up` worked without any issues.

I thing the problem was (or is) that my installment of Docker dated back to times when it was called Docker Toolbox (and did not include the docker-credential-desktop). After several updates on top of one another, things started to turn south.

Should I mark this as closed now? Should the Docker Desktop be fixed to include required links when updated on top of Docker Toolbox?

**Comment by justinappler** [comment]
Try including `"credsStore": "osxkeychain"` or `"credsStore": "desktop"` in `~/.docker/config.json`. For some reason it got misspelled for me.

**Comment by sirviot** [comment]
The uninstallation of Docker and re-installing the latest one fixed the problem, so I'm not anymore able to test this workaround.

**Comment by JamesGuthrie** [comment]
I seem to be running into the same issue. It looks like I had the same typo in `~/.docker/config.json`, but fixing it doesn't resolve the `docker-credential-desktop not installed or not available in PATH`.

Interestingly enough it does seem to be available on _my_ path:

```
> which docker-credential-desktop
/usr/local/bin/docker-credential-desktop

> ls -l $(which docker-credential-desktop)
lrwxr-xr-x  1 root  admin  73 Jul 31 16:05 /usr/local/bin/docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop

**Comment by JamesGuthrie** [comment]
I seem to be running into the same issue. It looks like I had the same typo in `~/.docker/config.json`, but fixing it doesn't resolve the `docker-credential-desktop not installed or not available in PATH`.

Interestingly enough it does seem to be available on _my_ path:

```
> which docker-credential-desktop
/usr/local/bin/docker-credential-desktop

> ls -l $(which docker-credential-desktop)
lrwxr-xr-x  1 root  admin  73 Jul 31 16:05 /usr/local/bin/docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop
```

I also tried uninstalling and reinstalling docker for mac but that didn't seem to help much.

**Comment by ulrich** [comment]
@sirviot thank you for your feedback.
I can reproduce this issue by updating Docker Desktop stable/2.0.0.2 version to stable/2.1.0.0 version, but the problem seems that the shell context is not refresh. To fix that I updated my shell environment with the source shell command (e.g. : source ~/.zshrc) to have the path refreshed.

**Comment by JamesGuthrie** [comment]
@ulrich I just tried running `source ~/.bash_profile`, but it didn't make a difference for me.

**Comment by Chinow** [comment]
I had the same issue and noticed that there was a typo in the `~/.docker/config.json` :
`credSstore` instead of `credsStore` not sure where it was coming from though.

**Comment by virgil9306** [comment]
Indeed @Chinow has the right solution. Somehow there is a typo in that file.

**Comment by ulrich** [comment]
I tried to find the misconfiguration in the config.json file.

The file content under Docker Desktop stable/2.0.0.3 (31259) is:
`
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.2 (darwin)"
	},
	"credsStore": "osxkeychain",
	"stackOrchestrator": "swarm"
}%
`

The file content under Docker Desktop stable/2.1.0.0 (36876) is:
`
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.1 (darwin)"
	},
	"credsStore": "desktop",
	"stackOrchestrator": "swarm"
}%
`

**Comment by gdemacedo** [comment]
for me the fix was a combination of @Chinow's post and creating the link with the following command:

`ln -s "/Applications/Docker.app/Contents//Resources/bin/docker-credential-desktop" "/usr/local/bin/docker-credential-desktop"`

after that the issue was resolved.

**Comment by ulrich** [comment]
Thank you for your feedbacks all. We did investigate for finding the related issue for this trouble and we are working to improve the behavior of our migration tooling.

I opened an issue in the Docker Desktop issues tracker for the next release stable/edge releases.

**Comment by davidpelayo** [comment]
What [@ulrich says is](https://github.com/docker/for-mac/issues/3785#issuecomment-518286444) in fact what just happened to me a few minutes ago.

Still without solution. Exactly in the same situation as @JamesGuthrie posted [here](https://github.com/docker/for-mac/issues/3785#issuecomment-518191574).

**Comment by davidpelayo** [comment]
Downgrading is how I made it work.

1. Close any terminal you had opened.
2. Delete your previous Docker for Desktop from your system (by simply removing it from your Applications).
3. Download the latest stable release `Docker Community Edition 2.0.0.3 2019-02-15`: https://download.docker.com/mac/stable/31259/Docker.dmg.
4. (Be careful not to delete unwanted info from your config) Initialize your credentials configuration by running: `docker-credential-gcr configure-docker`

**Comment by lmakarov** [comment]
In my case, this issue was likely the result of upgrading to Docker Desktop 2.1.0.0 and then downgrading back to 2.0.0.3.

As @ulrich mentioned [here](https://github.com/docker/for-mac/issues/3785#issuecomment-518601167), the two versions use different credsStore values: `"credsStore": "desktop"` in 2.1.0.0 vs `"credsStore": "osxkeychain"` in prior versions.

2.1.0.0 comes with the `/Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop` binary, while 2.0.0.3 only has `/Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain`.

Downgrading from 2.1.0.0 to 2.0.0.3 does not revert the changes in `~/.docker/config.json`, so you have to do this manually. Here's a one-liner for that:

```
sed -i~ 's/"desktop"/"osxkeychain"/g' ~/.docker/config.json
```

**Comment by mbode** [comment]
2.1.0.1 seems to fix the problem for me.

**Comment by guillaumerose** [comment]
Yes, this is fixed in 2.1.0.1.

**Comment by markpradhan** [comment]
Manually replacing the executable and running `docker login` fixed it for me:
https://github.com/docker/docker-credential-helpers/releases

(The executable was located in `/usr/local/bin`.

**Comment by amodsrivastava** [comment]
@Chinow's post is working from me.
 There was a typo in the ~/.docker/config.json :
credSstore instead of credsStore not sure where it was coming from though.

**Comment by audhumla** [comment]
I have faced the same issue with docker desktop 2.1.0.3. In this version there is no typo in the `~/.docker/config.json`. During the execution of some tests written with [test-container](https://www.testcontainers.org) that were spinning up some docker-compose. The problem is occurring only if the user is login in the DockerHub. So, in my case the solution was simply logging out.

**Comment by john-n-smith** [comment]
> Manually replacing the executable and running `docker login` fixed it for me:

The binary was missing for me too. This was a fresh install of Docker Toolbox using `DockerToolbox-19.03.1.pkg`

**Comment by deveweber** [comment]
I had the same issue with docker-toolbox under Windows 10 (I am using the toolbox because I have to run VirtualBox for another project).

The workaround I found:
* download the latest windows version of Docker Credential Helpers https://github.com/docker/docker-credential-helpers/releases
* copy docker-credentials-wincred.exe in your Docker Toolbox installation folder (usually C:\Program Files\Docker Toolbox)
* rename docker-credentials-wincred.exe to docker-credentials-desktop.exe

Everything should work fine now :)

**Comment by devinbost** [comment]
I just got this issue after upgrading to 2.2.0.0, but I don't see any typos in my `~/.docker/config.json` file. The contents of that file are: 
```
{
  "stackOrchestrator" : "swarm",
  "auths" : {

  },
  "credsStore" : "desktop"
}
```

I'm not sure if auths is supposed to be empty like that though.

**Comment by qnub** [comment]
try to replace `desktop` with `osxkeychain`

**Comment by Goffen** [comment]
For me using docker-toolbox, changing to osxkeychain and linking it as gdemacedo said worked

**Comment by philippefutureboy** [comment]
For all of those falling on this in 2020 I got this resolved by doing the total opposite of the above - I remove the `"credsStore": ...` line from my config and then it started working.

**Comment by chadfrost** [comment]
Big thanks to @philippefutureboy as his solution solved my frustration (docker-toolbox, on Mac Mojave).

**Comment by rb-mica** [comment]
I found the typo in my `~/.docker/config.json` and the links for `docker-credential-osxkeychain` was correct, still getting 

`fatal error: Unable to locate credentials`

(MacOS 10.15.4, Docker Desktop 2.3.0.2)

**Comment by Hawkzed** [comment]
Deleting config.json worked for me. Running docker in Windows and a WSL2 ubuntu environment.

**Comment by grottah** [comment]
Hi, today is my first day into docker, i need to run some test using TestContainer.
I don't have the typo in ~/.docker/config.json and the link for docker-credential-desktop was correct. After delete the line "credsStore" : "desktop", i don't have the error.

Also the install from eclipse of TestContainer is not working, some timeout. Only "docker pull localstack/localstack:0.9.4" from command line works properly.
 
(MacOS 10.13.6, Docker Desktop 2.3.0.3, eclipse 202003)

**Comment by mohammedabdulmajid** [comment]
> Try including `"credsStore": "osxkeychain"` or `"credsStore": "desktop"` in `~/.docker/config.json`. For some reason it got misspelled for me.

It worked for me by includeing "credsStore": "desktop" in ~/.docker/config.json.
Thank you.

**Comment by alex-gru** [comment]
:point_up: this approach fixed it for me as well, thanks @sshniro. :v:

**Comment by fathanpranaya** [comment]
> Deleting config.json worked for me. Running docker in Windows and a WSL2 ubuntu environment.

this is the solution for WSL2 case

**Comment by oliver-com** [comment]
> Deleting config.json worked for me. Running docker in Windows and a WSL2 ubuntu environment.

Works for me too

**Comment by riteshpuj2013** [comment]
Deleting config.json worked for me. 
Mac OS Catalina 10.15.6 
Docker version: 2.3.0.4

**Comment by arunsathyanarayan** [comment]
I'm using docker 2.0.0.3 on MacOS. Apart from the spelling issue mentioned by contributors in earlier posts, in this version of docker, the config.json file had both entries: "credsStore": "osxkeychain",  "credsStore": "desktop". Knowing that you wouldn't expect to find "credsStore": "desktop" on macOS, I just had to remove that entry, leaving behind just "credsStore": "osxkeychain" which sorted it for me.

**Comment by marleyjaffe** [comment]
Signing out of Docker Hub in the app seems to have solved the issue for me... I also changed to `credsStore": "osxkeychain"`

Mac OS Catalina 10.15.6
Docker version: 2.3.0.4

**Comment by mike-boost** [comment]
I use WSL ubuntu,  and install docker desktop in windows 10.
Then I uninstall docker desktop, and then install docker-ce in Ubuntu. Then same issue happended.
So I delete the folder ~/.docker, then everything ok.

**Comment by jeetpatel** [comment]
The problem resolved after running the following command:
**sudo apt install golang-docker-credential-helpers**

**Comment by krumware** [comment]
did the same thing as @mike-boost on windows 10 with wsl. Everything ran fine from powershell, but not from within WSL. 
ran `mv ~/.docker ~/.docker_old` and everything worked fine, without a restart.

**Comment by rolandma** [comment]
I ran into the same problem in Windows 10 WSL 2 integration docker-desktop for windows.
I tried the suggested to rename ~/.docker/config.json , the error of can't find credential went away but I actually lost credential to the repository, did the docker login from windows powershell won't help, but in the wsl, I did a docker login, and it worked.

**Comment by krumware** [comment]
It may be worth mentioning that this is happening regularly in WSL 2, and needs to be re-done occasionally. Hopefully a permanent solution is found soon.

**Comment by rolandma** [comment]
I renamed config.json in WSL 2, Ubuntu distro, and did a `docker login sample.com -u username -p password` inside ubuntu, then I checked the .ssh folder, there's a new config.json generated with login info, then I can do the `docker pull`. I think you might need to update the credential occasionally?
