### ISSUE TITLE
Error starting Docker Desktop for Mac

### ISSUE THREAD

**Issue by brookegravitt** [docker/for-mac#3786]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: CFB814EA-9594-491E-9B27-C1C94496FD47/20190802135402

### Expected behavior
Docker Desktop will start and run

### Actual behavior
Error message:
<img width="666" alt="Screenshot 2019-08-02 09 56 30" src="https://user-images.githubusercontent.com/1420174/62375337-164eaa80-b50c-11e9-8462-22f5d92880b8.png">

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac:  uploaded

**Comment by borisnetweb** [comment]
Try open preferences, click reset, choose "Reset disk image".
