### ISSUE TITLE
Docker 2.1.0.0 doesn't work

### ISSUE THREAD

**Issue by andrewtrecha** [docker/for-mac#3788]
Upgraded docker from 2.0.0.3 to 2.1.0.0 and sites would not load.
Using with docksal version 1.86.2

### Expected behavior
Sites should load after fin start

### Actual behavior
Site's no longer load after project start

### Information
Problem started immediately after update. Tried reinstalling several times. Had to reinstall 2.0.0.3 in order for local dev sites to work as expected

  - macOS Version:
Mojave 10.14.6

### Diagnostic logs

```
Docker for Mac: version...

2.1.0.0

### Steps to reproduce the behavior
Update to 2.1.0.0 from 2.0.0.3

**Comment by borisnetweb** [comment]
Try open preferences, click reset, choose "Reset disk image".

**Comment by stephdavid** [comment]
Hello, I have the same problem as @andrewtrecha but can't cleanly uninstall docker 2.1.0.0 to allow me to return to an earlier version. I'm using macOS High Sierra. I've tried MAC uninstaller tools: AppCleaner, CleanMyMac 3, and FoneDog PowerMyMac but I'm still stuck with Version 2.1.0.0 with Engine 19.03.1 Hope someone can help.
