### ISSUE TITLE
Docker not responding anymore

### ISSUE THREAD

**Issue by maxfrigge** [docker/for-mac#379]
### Expected behavior
You can interact with docker.

### Actual behavior
You cannot interact with docker at all. Neither `docker-compose` nor a simple `docker ps` respond in any way. Restarting docker didn't help either.

### Information

Diagnostic ID: B2FA9766-A70D-47F1-8523-DA8B53B71397
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Can't say. It just happened after working normally for hours.

**Comment by mkucharek** [comment]
just happened to me as well
```
Docker for Mac: version: 2f0427a
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/32863210-995D-41C2-8FEE-B59822EBBD60/20160822-140830.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by elgreg** [comment]
See https://github.com/docker/for-mac/issues/350

Happened for me twice now and killing all docker processes and then restarting the docker app resolves it.

**Comment by maxfrigge** [comment]
Thanks @elgreg for letting us know. I will close this one, because it's a duplicate of #350
