### ISSUE TITLE
19.03.1 breaks ipv4 bindings

### ISSUE THREAD

**Issue by shmocs** [docker/for-mac#3792]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6A19A18E-AEAF-44A1-BA53-7E2837241074/20190802212757

### Expected behavior
[docker-compose up] should bind all ports of containers also to ipv4 (or only to ipv4)
### Actual behavior
[docker-compose up] binds all ports of containers ONLY to ipv6

### Information
  - it is reproductible. Going back to Docker 18.09.2 (as i had it before) everything works perfectly
  - the problem .. seems to be new
  - problem appeared after I upgraded to Docker 19.03.1
  - macOS Version: 10.14.6

### Diagnostic logs
```
Docker for Mac: 19.03.1
Provided Diagnostic ID with uploaded archive with every configuration it generated

```

### Steps to reproduce the behavior
clone https://github.com/cytopia/devilbox
docker compose up bind
no 53 port listening on ipv4 on mac host, only IPV6:53

Actually nothing of any kind is listening on Ipv4 on mac host... Everything broke up with latest Docker update.

Please help :(

**Comment by shmocs** [comment]
seems someone on cytopia already noted the same issue: https://github.com/cytopia/devilbox/issues/616

**Comment by guillaumerose** [comment]
Related to https://github.com/docker/for-mac/issues/3775
