### ISSUE TITLE
Copy Paste does not work in Docker Desktop 2.1.0.0 (36792) edge

### ISSUE THREAD

**Issue by sirkkalap** [docker/for-mac#3798]
- [X] I have tried with the latest version of my channel (Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E66478B3-894A-4250-B1D4-3ED04D539A08/20190805103527

### Expected behavior

Paste text to a field yields the text into the field

### Actual behavior

Nothing happens

### Information

  - macOS Version: 10.14.5

### Diagnostic logs

Sorry, no such menu in this new UI. Also if there were such menu, there would be no way to copy text from there.
```
Docker for Mac: Docker Desktop 2.1.0.0 (36792) Edge

```

### Steps to reproduce the behavior

  1. Open preferences
  2. Navigate to Docker Engine
  3. Try to paste text to docker.json textarea.

**Comment by guillaumerose** [comment]
Thanks for report! It's fixed in master and will land in next edge.
