### ISSUE TITLE
Docker.dmg checksum is wrong

### ISSUE THREAD

**Issue by skelliest** [docker/for-mac#3800]
The recent stable release of 2.1.0.0 pushed an artifact which does not match the published checksum.

### Steps to reproduce the behavior

```
curl -O https://download.docker.com/mac/stable/Docker.dmg
curl -O https://download.docker.com/mac/stable/Docker.dmg.sha256sum
shasum -c Docker.dmg.sha256sum
```

### Expected behavior
Checksum passes

```
Docker.dmg: OK
```

### Actual behavior
Checksum fails
```
Docker.dmg: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```

### Information
Build `2.0.0.3-ce-mac81,31259` of Docker.dmg from February 2019 has checksum 
```
a55462f153284ff212f8857945a69d4e128afb6753f5572984877f7b6fc3fc25
```
which is the currently published value. The release `2.1.0.0,36874` from a couple days ago has checksum
```
6571554a70dc5c5cea4f05c03038019411d5d8310fcea514a50110b038de715b
```

**Comment by guillaumerose** [comment]
Thanks for report, we changed the release process and it's clearly a mistake. Correct hash is `6571554a70dc5c5cea4f05c03038019411d5d8310fcea514a50110b038de715b`.

**Comment by guillaumerose** [comment]
It appears that `Docker.dmg.sha256sum` link is not in the documentation anymore. I removed the file on S3 to avoid confusion. 

If you want to verify the application, I suggest you use codesign tool directly:

```
$ codesign -dv --verbose=4 /Applications/Docker.app
Executable=/Applications/Docker.app/Contents/MacOS/Docker
Identifier=com.docker.docker
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=64817 flags=0x0(none) hashes=2018+5 location=embedded
VersionPlatform=1
VersionMin=658176
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=687fe9965fd05fece6872da0fd4360e67df507cf
CandidateCDHash sha256=065d2fd2737008357ae12997476723623c288cfc
Hash choices=sha1,sha256
Page size=4096
CDHash=065d2fd2737008357ae12997476723623c288cfc
Signature size=9000
Authority=Developer ID Application: Docker Inc (9BNSXJN65R)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=5 Aug 2019 at 16:14:02
Info.plist entries=45
TeamIdentifier=9BNSXJN65R
Sealed Resources version=2 rules=13 files=91
Internal requirements count=1 size=212
```

**Comment by rocketnova** [comment]
@guillaumerose I wonder if this is the link in the documentation you are referring to? https://docs.docker.com/v17.12/docker-for-mac/install/#download-docker-for-mac 

<img width="620" alt="Screen Shot 2019-10-08 at 5 13 45 PM" src="https://user-images.githubusercontent.com/67701/66442301-1331d800-e9ef-11e9-8980-f66cc8fa97b0.png">

Right now, when you click on the checksum links (for both edge and stable) in the documentation, you see this slightly alarming 404:
<img width="820" alt="Screen Shot 2019-10-08 at 5 14 53 PM" src="https://user-images.githubusercontent.com/67701/66442333-29d82f00-e9ef-11e9-85ce-c2cbbe890d1e.png">

I think either the checksum file should be added back to the S3 or link should be removed from the documentation (this option is less preferable I think).

**Comment by avolution** [comment]
What @rocketnova have reported is still the case.

Still 404

So there is currently no way to verify the download(?)
