### ISSUE TITLE
Cannot start docker on mac - Fatal Error - The operation couldn't be completed. (Docker.VmnetdError error1.)

### ISSUE THREAD

**Issue by khkiran** [docker/for-mac#3801]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F4297A5F-4C75-419C-9D7C-C2CABC7C3A67/20190806013954

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by khkiran** [comment]
I resolved this with brew cask install docker

**Comment by vinitkantrod** [comment]
@khkiran even with cask command its not working.
