### ISSUE TITLE
Fatal Error: one of the sub-processes failed: com.docker.driver.amd64-linux (pid: 6160)

### ISSUE THREAD

**Issue by caicanglun** [docker/for-mac#3802]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by maartenpaauw** [comment]
Received the same fatal error today. Just downloaded it (edge version).

![Screen Shot 2019-08-19 at 00 03 57](https://user-images.githubusercontent.com/4550875/63230963-fc53de00-c214-11e9-9d26-7744798717d9.png)

**Comment by maartenpaauw** [comment]
Here is the log that I found.

[com.docker.driver.amd64-linux.log](https://github.com/docker/for-mac/files/3513645/com.docker.driver.amd64-linux.log)

**Comment by zhuofanxu** [comment]
I just turn on the cpu virtualization on bios seting, and it works

**Comment by zhuofanxu** [comment]
Yes

发自我的 iPhone

在 2019年8月20日，16:25，Maarten Paauw <notifications@github.com<mailto:notifications@github.com>> 写道：


I just turn on the cpu virtualization on bios seting, and it works

I have enabled virtualization in the bios. Did not help me. Do you also use Hackintosh?

**Comment by zhuofanxu** [comment]
@maartenpaauw Yes

**Comment by yilikunNEO** [comment]
how to turn on virtualization?

**Comment by maartenpaauw** [comment]
> how to turn on virtualization?

You can enable this via the BIOS. It differs per motherboard where this option can be found. It is best to google this with: "Turn virtualisation on motherboard INSERT_YOUR_MOTHERBOARD".

**Comment by SlowFamily** [comment]
If using a hackintosh- I had similar issues, which were solved by enabling virtualization in the BIOS, and removing the dart=0 startup option

**Comment by joshkremer** [comment]
> If using a hackintosh- I had similar issues, which were solved by enabling virtualization in the BIOS, and removing the dart=0 startup option

I can confirm the same. I'm on a Hackintosh and after having the same issue and reading this comment, I went into my BIOS and turned off "Intel Virtualization" and that solved my issue. Thanks!

**Comment by PhilipFitzgerald** [comment]
Hi 

> > If using a hackintosh- I had similar issues, which were solved by enabling virtualization in the BIOS, and removing the dart=0 startup option
> 
> I can confirm the same. I'm on a Hackintosh and after having the same issue and reading this comment, I went into my BIOS and turned off "Intel Virtualization" and that solved my issue. Thanks!

Hi I do not know how to access BIOS or how to turn off intel virtualization. Could you provide me with the steps? I really need to get docker working on my Mac for class quickly

**Comment by joshkremer** [comment]
> Hi
> 
> > > If using a hackintosh- I had similar issues, which were solved by enabling virtualization in the BIOS, and removing the dart=0 startup option
> > 
> > 
> > I can confirm the same. I'm on a Hackintosh and after having the same issue and reading this comment, I went into my BIOS and turned off "Intel Virtualization" and that solved my issue. Thanks!
> 
> Hi I do not know how to access BIOS or how to turn off intel virtualization. Could you provide me with the steps? I really need to get docker working on my Mac for class quickly

Typically that would be achieved by restarting your machine and pressing the "Delete" button to open the BIOS, then look for something similar to "CPU virtualization" and disabling that. Good luck.

**Comment by PhilipFitzgerald** [comment]
> > Hi
> > > > If using a hackintosh- I had similar issues, which were solved by enabling virtualization in the BIOS, and removing the dart=0 startup option
> > > 
> > > 
> > > I can confirm the same. I'm on a Hackintosh and after having the same issue and reading this comment, I went into my BIOS and turned off "Intel Virtualization" and that solved my issue. Thanks!
> > 
> > 
> > Hi I do not know how to access BIOS or how to turn off intel virtualization. Could you provide me with the steps? I really need to get docker working on my Mac for class quickly
> 
> Typically that would be achieved by restarting your machine and pressing the "Delete" button to open the BIOS, then look for something similar to "CPU virtualization" and disabling that. Good luck.

I just tried what you suggested and unfortunately nothing happened. I don't know if its because my macbook pro is a 2012 version or what but I cant seem to fix this issue.

**Comment by esetnik** [comment]
I am having the same error today after updating to v2.2.0.3. Docker was working fine on this system prior to the update.

**Comment by chrisbarber86** [comment]
Had the same error upgrading to v2.2.0.3. Docker was working fine before the update. Restarting docker for mac did not seem to help. Resetting docker to factory defaults however did solve this issue for me.

**Comment by PhilipFitzgerald** [comment]
Nothing I tried fixed. One day I was telling someone about it and showed them it and it was working. Worked for about a month then when I closed it (left I running the entire time because I didn’t want to risk it not working) and opened it later it wasn’t working again and hasn’t worked for weeks now. Makes no sense.
