### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by budikpet** [docker/for-mac#3809]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DC3B4257-C82F-40E7-9EEC-7D6E69422ABD/20190807093855

### Expected behavior
Docker for Mac OS installed and run successfully.

### Actual behavior
Docker for Mac OS was installed using the "stable" version of the installation file. When I run the installed docker application this warning window appears:

    Docker Desktop needs privileged access.
    Docker Desktop needs privileged access to install its networking components and links to 
    the Docker apps.

    You will be asked for your password.

Once I do that, another window appears:

    Fatal Error
    The operation couldn’t be completed. (Docker.VmnetdError error 1.
    
    Reset Docker to factory settings                Diagnose            Exit

### Information

  - macOS Version: macOS Mojave 10.14.6

**Comment by budikpet** [comment]
The problem was that I needed to install the Docker app into a subfolder of the Apps folder. 
I was able to make the Docker app work when I installed it directly into the Apps folder.

**Comment by axmachina** [comment]
> The problem was that I needed to install the Docker app into a subfolder of the Apps folder.
> I was able to make the Docker app work when I installed it directly into the Apps folder.

I'm having similar issue... but don't understand your solution. Can explain please?

**Comment by axmachina** [comment]
Had ran into exact same issue and resolved by installing Docker via Homebrew:

https://stackoverflow.com/questions/40523307/brew-install-docker-does-not-include-docker-engine/43365425#43365425

Be sure to disable SIP and own /usr/local:

https://github.com/Homebrew/legacy-homebrew/issues/43855#issuecomment-141193186

**Comment by budikpet** [comment]
> > The problem was that I needed to install the Docker app into a subfolder of the Apps folder.
> > I was able to make the Docker app work when I installed it directly into the Apps folder.
> 
> I'm having similar issue... but don't understand your solution. Can explain please?

Basically instead of installing it directly to Applications folder I installed docker to Applications/Programming folder. After uninstalling and reinstalling it directly to Applications folder it worked well.

It's true that Homebrew is probably much better method of installation.
