### ISSUE TITLE
Fails just after launching Docker.app

### ISSUE THREAD

**Issue by npenzin** [docker/for-mac#381]
### Information

Diagnostic ID: 4293B61E-CD06-446C-8260-D5C3C61D36D7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/plptn/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/4293B61E-CD06-446C-8260-D5C3C61D36D7/20160821-204914/qemu-img-check.stdout 2> /tmp/4293B61E-CD06-446C-8260-D5C3C61D36D7/20160821-204914/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/plptn/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/plptn/Library/Containers/com.docker.docker/Data/s40
[ERROR]  slirp
         /Users/plptn/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/plptn/Library/Containers/com.docker.docker/Data/s51
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /Library/LaunchDaemons/com.docker.vmnetd.plist does not exist
[OK]     env
[ERROR]  moby
         /Users/plptn/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Download Docker for Mac
2. Launch it

**Comment by mchiang0610** [comment]
Possible to do a reset to factory default? let us know if you are still running into problems after. 

If you have Virtualbox 4.3.x installed, please update to the latest. 

Happy to reopen the issue if you are still running into problems.

**Comment by dsheets** [comment]
This issue does not contain enough information about what errors you have seen during run-time in order to determine if they have been resolved or not. Issues #64 and #202 are relevant with #64 being fixed in the beta channel several weeks ago and #202 fixed in the recent Beta 25 release.

If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg. Be sure to uninstall Docker for Mac before installing the Beta.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
