### ISSUE TITLE
Docker no starting

### ISSUE THREAD

**Issue by umarpahat** [docker/for-mac#3812]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by petr-ujezdsky** [comment]
?

**Comment by AndreyKrupskii** [comment]
Got the same issue. Report id - 27B6E148-025E-491B-8348-94FBD893D76B/20190809112334
