### ISSUE TITLE
Dropdown Menu misses 'disable local cluster'

### ISSUE THREAD

**Issue by tillepille** [docker/for-mac#3817]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B1A4414D-F0E4-4408-9D62-D558B4DF2988/20190808092400

### Expected behavior

Have a button In dropdown menu Kubernetes -> Disable local cluster

### Actual behavior

There is no button since a fresh install of Docker Desktop Edge.

### Information

  - macOS Version:  10.14.6

On another Mac where i just upgraded to version 2.1.0 the button is still there.

### Diagnostic logs

```
$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)

Server:
 Containers: 44
  Running: 38
  Paused: 0
  Stopped: 6
 Images: 27
 Server Version: 19.03.1
```

### Steps to reproduce the behavior

1. New MacOS
2. install docker for mac

**Comment by leonardinius** [comment]
I have exactly same issue
