### ISSUE TITLE
Unable to pull images from AWS ECR

### ISSUE THREAD

**Issue by garyrutland** [docker/for-mac#3818]
- [x] I have tried with the latest version of my channel (Stable `2.1.0.*`)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A7A65563-D213-4F95-9EA6-B7D3BEE139B0/20190808132543

### Expected behaviour

- Login to AWS ECR using `$(aws ecr get-login --no-include-email --region eu-west-1)`
- Pull Docker image successfully from AWS ECR

### Actual behaviour

- Login to AWS says it's successful `Login Succeeded`
- Pull Docker image fails with response `no basic auth credentials`

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - Docker version(s): 2.1.0.0, 2.1.0.1
  - macOS Version: 10.13.6

We use a third party tool called saml2aws to login to AWS for CLI etc which uses roles and STS rather than long life tokens, these are stored in `~/.aws/credentials`.
I don't think this makes a difference, but information for you just in case.

### Steps to reproduce the behavior

  1. `$(aws ecr get-login --no-include-email --region eu-west-1)`
  2. `docker pull __ACCOUNT_ID__.dkr.ecr.eu-west-1.amazonaws.com/__IMAGE_NAME__`

**Comment by garyrutland** [comment]
Update: Interestingly, if we try and run via `docker-compose up` which requires a build we get an error saying we are not authorised to do `ecr:BatchGetImage` instead of `no basic auth credentials`.

**Comment by ddnamanpatel** [comment]
I could work around it by creating a symlink for docker-credential-desktop -> docker-credential-osxkeychain. Somehow docker install does not do that.

**Comment by garyrutland** [comment]
We've been able to pin point a bit more exactly when this error occurs.
After a successful login to AWS ECR these are the following scenarios:

Successful: `docker pull **ACCOUNT_ID**.dkr.ecr.eu-west-1.amazonaws.com/**IMAGE_NAME**`

Successful: `docker-compose up --build` & `docker-compose pull`
```
version: "3.5"
services:
  app:
    image: **ACCOUNT_ID**.dkr.ecr.eu-west-1.amazonaws.com/**IMAGE_NAME**
```

Fails: `docker-compose up --build`
```
version: "3.5"
services:
  app:
    build: .
```
```
FROM **ACCOUNT_ID**.dkr.ecr.eu-west-1.amazonaws.com/**IMAGE_NAME**
```

Hope this helps.

**Comment by ryanwilsonperkin** [comment]
I can confirm that we also face this issue and can also resolve it by pulling manually. For now we've asked developers to pin back to v2.0.0 which doesn't seem to have this problem

**Comment by ParvJain** [comment]
This is a breaking change and is open for past 2 months, can someone expedite this?

**Comment by garyrutland** [comment]
There have now been 5 "stable" releases since this has been reported with what looks like no effort to resolve it.
I can confirm that version 2.1.0.5 still has the same issue.

Is there any news?

**Comment by guillaumerose** [comment]
Last time I tried, I couldn't reproduce it with my machine and an AWS account. This ticket https://github.com/docker/for-mac/issues/4018 makes me think it works for (most?) of users. I guess there is something different in your setup.

**Comment by ParvJain** [comment]
@guillaumerose The issue you're referring to is faced while pushing an image and is totally irrelevant to this issue, we've around ~12 devs in our team using Docker for Mac and all of them were facing the same issue until they disabled "Store password in Keychain" option and did docker login again, now they did able to pull using `docker pull <image_repo_url>` and once the image is locally available they can go ahead and do `docker-compose up` or `docker-compose build`, while I'm using Ubuntu and facing no such issues at all.

**Comment by guillaumerose** [comment]
@ParvJain credentials are both used for push and pull. So it's relevant. 

We are looking at removing the docker-credential-desktop binary. It was a bad idea after all: too many side effects sadly.

**Comment by garyrutland** [comment]
@guillaumerose Is there any kind of timeline on when this might happen?

I don't understand what might be different about our setup, we use Docker straight out of the box.
The only other thing I can see we've added that might add a difference is the usage of `saml2aws` for AWS authentication.

**Comment by riwiki** [comment]
This issue is reproducible just fine. Here is a minimal test case:

Dockerfile:
```
FROM <account-id>.dkr.ecr.<region>.amazonaws.com/repo:tag
RUN echo "moo"
```

docker-compose.yml:
```
version: '3.7'

services:
  service:
    image: service:latest
    build:
      context: .
```

Login to ECR via `aws ecr get-login ...`

Run `docker-compose build --pull`

Expected behavior: the base image stated in the Dockerfile can be pulled successfully.
Actual behavior: build fails with "no basic auth credentials" error.

However, it does work as expected when using `docker build --pull`. 

Suspected root cause:
```
cat ~/.docker/config.json
{
	"auths": {
		"<account-id>.dkr.ecr.<region>.amazonaws.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.5 (darwin)"
	},
	"credsStore": "desktop",
	"stackOrchestrator": "swarm"
}```

The `auths` entry does not contains `https://`. If you add `https://` in front of the ECR URL, docker-compose can pull the base image just fine.

Version info:
 * Docker version 19.03.5, build 633a0ea
 * docker-compose version 1.24.1, build 4667896b
 * aws-cli/1.16.301 Python/3.7.5 Darwin/18.7.0 botocore/1.13.37

I have no clue whether the error is due to docker-compose, aws-cli or a combination of all. Maybe it is a problem with the `credStore` and I can use a different one that will work? Any help much appreciated.

**Comment by riwiki** [comment]
It appears that the issue is resolved when upgrading to `docker-compose version 1.25.0, build b42d419`.

On macOS, e.g. via `pip3 install docker-compose`.

**Comment by garyrutland** [comment]
It would appear Docker Desktop 2.2.0.0 has resolve the issue.
