### ISSUE TITLE
Failed to launch Docker for Mac

### ISSUE THREAD

**Issue by JonnyWalker81** [docker/for-mac#382]
### Information

Diagnostic ID: AA6DC6EB-4B62-4FD0-A1BE-5D6A14D7E34D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A294a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/jonnywalker/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/AA6DC6EB-4B62-4FD0-A1BE-5D6A14D7E34D/20160821-150823/qemu-img-check.stdout 2> /tmp/AA6DC6EB-4B62-4FD0-A1BE-5D6A14D7E34D/20160821-150823/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/jonnywalker/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jonnywalker/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/jonnywalker/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jonnywalker/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/jonnywalker/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce
I am running macOS Sierra Public Beta 3
1. Download Docker for Mac
2. Drag to Applications folder
3. Launch Docker for Mac
4. Click through wizard and get an error

**Comment by mchiang0610** [comment]
Please try the latest beta 25, and see if that resolves the problems with Sierra: 

https://download.docker.com/mac/beta/Docker.dmg 

We will update the stable channel soon with official Sierra support. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
