### ISSUE TITLE
Kubernetes failed to start, no logs: C74B4BE4-1015-40C6-8ADB-FD3DED62EAFD/20190809192649

### ISSUE THREAD

**Issue by elonazoulay** [docker/for-mac#3823]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C74B4BE4-1015-40C6-8ADB-FD3DED62EAFD/20190809192649

### Expected behavior
Kubernetes cluster starts

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.1 (37199)

```

### Steps to reproduce the behavior

  1. Start docker
  2. Enable kubernetes cluster

**Comment by drenze** [comment]
I'm having this same issue with Mojave and 2.1.0.1.

**Comment by 1032120121** [comment]
I'm having the same issue with macOs:10.13.4

**Comment by 1032120121** [comment]
this is diagnostics.log

time="2019-08-18T20:09:58+08:00" level=warning msg="[/usr/local/bin/kubectl.docker --namespace docker get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2019-08-18T20:09:58+08:00" level=warning msg="Unable to connect to the server: EOF\n" type=kubernetes
time="2019-08-18T20:09:58+08:00" level=warning msg="[/usr/local/bin/kubectl.docker --namespace kube-system get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2019-08-18T20:09:58+08:00" level=warning msg="Unable to connect to the server: EOF\n" type=kubernetes
time="2019-08-18T20:09:58+08:00" level=info msg="Start gathering list of 72 elements (timeout=10m0s)" type=list
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sw_vers -productVersion]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sw_vers -buildVersion]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [uname -r]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sysctl kern.boottime]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sysctl hw.memsize]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [vm_stat]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sysctl machdep.cpu]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [uname -a]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [ps uax]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [dmesg]" type=cmd
time="2019-08-18T20:09:58+08:00" level=warning msg="[dmesg] exit status 1" type=cmd
time="2019-08-18T20:09:58+08:00" level=warning msg="[dmesg]: Unable to obtain kernel buffer: Operation not permitted\nusage: sudo dmesg\n" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [id]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [sysctl -a]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [mount]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [df -h]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [launchctl print-disabled system]" type=cmd
time="2019-08-18T20:09:58+08:00" level=info msg="Executing: [system_profiler SPHardwareDataType]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [ifconfig -a]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [netstat -ln]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [netstat -mm]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [netstat -nr]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2019-08-18T20:09:59+08:00" level=info msg="Gathering: /etc/hosts" type=file
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [scutil --dns]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [scutil --nc list]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [scutil --proxy list]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [system_profiler SPFirewallDataType]" type=cmd
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2019-08-18T20:09:59+08:00" level=info msg="Executing: [/bin/sh -c docker network inspect $(docker network ls -q)]" type=cmd
time="2019-08-18T20:09:59+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-08-18T20:09:59+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-08-18T20:10:00+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2019-08-18T20:10:00+08:00" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']" type=cmd
time="2019-08-18T20:10:08+08:00" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]" type=cmd
time="2019-08-18T20:10:11+08:00" level=warning msg="[syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]: NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.\n" type=cmd
time="2019-08-18T20:10:11+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]" type=cmd
time="2019-08-18T20:10:11+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]" type=cmd
time="2019-08-18T20:10:11+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]" type=cmd
time="2019-08-18T20:10:11+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]" type=cmd
time="2019-08-18T20:10:11+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]" type=cmd
time="2019-08-18T20:10:12+08:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)]" type=cmd
time="2019-08-18T20:10:12+08:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)] exit status 1" type=cmd
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:version" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configget-contexts" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configcurrent-context" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnodes" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnamespaces" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describenodes" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:cluster-infodump" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describeservices" type=kubectl
time="2019-08-18T20:10:12+08:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describestorageclass,pv,pvc" type=kubectl
time="2019-08-18T20:10:12+08:00" level=info msg="Executing: [ls -l /Users/yangyang65/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw]" type=cmd
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/already-enabled-features.json" type=file
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/dhcp.json" type=file
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/features.json" type=file
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/http_proxy.json" type=file
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/Library/Group Containers/group.com.docker/settings.json" type=file
time="2019-08-18T20:10:12+08:00" level=warning msg="/Users/yangyang65/Library/Preferences/group.com.docker.plist not included" type=file
time="2019-08-18T20:10:12+08:00" level=warning msg="exit status 1" type=directorylist
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/.docker/config.json" type=redacted-json
time="2019-08-18T20:10:12+08:00" level=info msg="Gathering: /Users/yangyang65/.docker/daemon.json" type=redacted-json
time="2019-08-18T20:10:12+08:00" level=info msg="Getting Linux Diagnostics via a virtio socket: hyperkit:/Users/yangyang65/Library/Containers/com.docker.docker/Data/vms/0:62374" type=virtsock
time="2019-08-18T20:10:49+08:00" level=info msg="All 72 gatherers finished" type=list

**Comment by Ognian** [comment]
Same
