### ISSUE TITLE
Missing reset menu in desktop application.

### ISSUE THREAD

**Issue by tmihalicka** [docker/for-mac#3831]
When I open docker application i can't see reset menu:

<img width="1152" alt="Screenshot 2019-08-12 at 13 40 09" src="https://user-images.githubusercontent.com/1620790/62862653-bbd0fd80-bd06-11e9-9706-169ff9de1e22.png">

This menu was in later version of docker in old UI. And now is missing so it's not possible to factory reset docker.

  - [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Reset menu appears in desktop application like in old UI.

![prefs-general](https://user-images.githubusercontent.com/1620790/62862767-1e29fe00-bd07-11e9-9f53-8646a35da7ce.png)

See reset menu.

### Actual behavior
Reset menu wont show in actual version of desktop UI.

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.1
```

### Steps to reproduce the behavior

1.  Open docker application preferencies

**Comment by stephen-turner** [comment]
It's moved to the Troubleshoot menu.

**Comment by tmihalicka** [comment]
> It's moved to the Troubleshoot menu.

So it's possible to provide troubleshoot menu link from preferences menu? This is bad UI/UX design.

**Comment by stephen-turner** [comment]
Yes, I'm not sure exactly what we'll do, but we will make it more findable, especially for people who were used to the previous location. You're not the first person to have had trouble finding where it has gone.

**Comment by tmihalicka** [comment]
Maybe update documentation will be enough :)

**Comment by stephen-turner** [comment]
It's in the Edge release notes already (https://docs.docker.com/docker-for-windows/edge-release-notes/). It will be in the main documentation when it reaches the Stable channel.

But I think we will have some additional UI not just documentation.

**Comment by reegnz** [comment]
The documentation notes did not land in the stable release notes (2.1.0.1), also no mention of the new UI in the stable release notes.
Had me scratching my head for a while, but luckily I found this github issue.

Please add this info to the stable release notes.

**Comment by stephen-turner** [comment]
That’s because it’s not in Stable yet. See my previous comment.

**Comment by reegnz** [comment]
That is indeed strange, because I am not running docker-edge on macOS, but stable, and I have the new UI:
![Screenshot 2019-09-04 at 13 08 49](https://user-images.githubusercontent.com/5672001/64249948-28f63e00-cf15-11e9-8cf4-cfbd19c6c519.png)

**Comment by stephen-turner** [comment]
Did you previously run Edge? (The code is present in both Edge and Stable, it’s just turned on/off with feature flags, so you may have an Edge feature flag hanging around).

**Comment by reegnz** [comment]
Yes, I ran edge previously, then purged edge and installed stable once I saw there was a new release.
A feature flag hanging around could explain all of this. Will have to check that.

**Comment by stephen-turner** [comment]
Good, thanks for testing and thanks for letting us know.
