### ISSUE TITLE
Could not install Docker on Mac

### ISSUE THREAD

**Issue by cksummers13** [docker/for-mac#3832]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  86007DE6-786C-43EE-AC20-F5A98E363F44/20190812144032

### Information

  - macOS Version:  10.14.6

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...Open Docker DMG
  2. ...Move Docker to Applications folder
  3. ...Open Docker

**Comment by alahalil** [comment]
I have the same issue. Did you have any chance or way to fix it?

**Comment by cksummers13** [comment]
Yes. I found the answer while searching the Net. If you go to Launchpad and have it launch Docker it works fine. Directly launching Docker does not seem to work. I don't know enough about "under-the-hood" workings of MacOS but I suspect that it is some type of environmental inheritance when Launchpad fork/exec Docker.

**Comment by rosman21** [comment]
that is really weird, using the launchpad works and not directly

**Comment by swoppy** [comment]
I had the same exact issue, It's weird it was not able to open directly.

MacOs: 10.15

**Comment by Srikanth9859** [comment]
Yes, it really wired, when tried lauching from launched pad working fine.
