### ISSUE TITLE
could not install Docker on Mac

### ISSUE THREAD

**Issue by viveksair** [docker/for-mac#3833]
Diagnostic ID: 844F36C5-9517-4B1C-A623-BF2998BD2F1A/20190812165140

Fatal error: The operation couldn’t be completed. (NIO.SocketAddressError error 3.)

 I have tried with the latest version (Stable or Edge)

**Comment by viveksair** [comment]
```
$ brew cask install https://raw.githubusercontent.com/ahousseini/homebrew-cask/3d8ed99786fa59b9830f524ef3b1151e6098eedb/Casks/docker.rb

$ docker -v
Docker version 18.09.2, build 6247962
```

working for me

**Comment by novasdream** [comment]
Old Versions work.



I try last version but get 
```
com.docker.backend cannot start Exit code 1
```


I downgrade to version/2.1.0.1 and get 
The operation couldn’t be completed. (NIO.SocketAddressError error 3.)


I receive some sugestion to run it from brew 

```
brew cask install https://raw.githubusercontent.com/ahousseini/homebrew-cask/3d8ed99786fa59b9830f524ef3b1151e6098eedb/Casks/docker.rb
```

This version work to me.
