### ISSUE TITLE
Unable to add insecure-registry with latest version of docker

### ISSUE THREAD

**Issue by thrawn01** [docker/for-mac#3834]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 82C60FDB-06B0-4EA4-B875-1E9C78AA941E/20190812180135

### Expected behavior
Add insecure-registry entry to docker engine via the docker engine daemon settings

### Actual behavior
Once I've entered the following JSON into the docker engine daemon settings via the UI.
```
{
  "debug": true,
  "experimental": false,
  "insecure-registry": [ "...", "..."]
}
```

I click "Apply & Restart" and I get a modal box with the following "Cannot change shared directories"

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? YES
  - Is the problem new? YES
  - Did the problem appear with an update? YES
  - macOS Version: 10.14.5

### Diagnostic logs
While clicking on the `Apply & Restart` button no log entries are observed when viewing via the `console` app and filtered by `process: docker` 

On a related note, why on earth is copy/paste disabled for the daemon config text box in the UI?

**Comment by isque03** [comment]
Btw I worked around this by editing ~/.docker/daemon.json manually. Then I restarted the docker daemon from the restart menu of docker desktop.
Also using 2.1.0.1 (37199) stable channel.

**Comment by ulrich** [comment]
Thank you for your report @thrawn01 and @isque03,

It seems you use Docker Desktop via the new UI only available on the Edge version (for the moment).

The new UI on the Stable version is not well supported and to get back on corresponding UI, you need to unset the feature flag in the following path:

> /Users/YOU/Group Containers/group.com.docker/already-enabled-features.json#"settingsV0 to false

Regarding the problem during the setting of insecure registry, you have to use the following key:

> "insecure-registries":["localhost:6000"]

Ulrich

**Comment by ulrich** [comment]
Any feedback about the issue?

Thank you!

**Comment by thrawn01** [comment]
@ulrich This would explain why downgrading from edge to stable didn't result in the old UI, which I found quite confusing. I ended up downloading 1.8.x and got the old UI back. 

Thank you for your help.

**Comment by thrawn01** [comment]
For anyone else with this issue, I found the file under the `~/Library` directory.

`/Users/YOU/Library/Group Containers/group.com.docker/already-enabled-features.json`

I reinstalled 2.0, changed the `settingsV0` to false and restarted docker and BINGO, old UI.

**Comment by ulrich** [comment]
Cool, thank you.
