### ISSUE TITLE
New Version of Docker can't run on OSX 

### ISSUE THREAD

**Issue by draculavlad** [docker/for-mac#384]
It said that 'Docker does not rely on Virtualbox'. So I just uninstalled my virtual box. And found that docker still can't run on my laptop. So could any one help me a little about this?

### Information

Diagnostic ID: E9C07756-DDA0-4CB3-9F88-39B07B79D6FB
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/suyu/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/E9C07756-DDA0-4CB3-9F88-39B07B79D6FB/20160822-102830/qemu-img-check.stdout 2> /tmp/E9C07756-DDA0-4CB3-9F88-39B07B79D6FB/20160822-102830/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/suyu/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/suyu/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/suyu/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/suyu/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/suyu/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@draculavlad Does performing factory reset to default settings work? 

Let us know if it's not working, and we'll troubleshoot further. Sorry about your experience with Docker so far.
