### ISSUE TITLE
QEMU+valgrind = segmentation fault

### ISSUE THREAD

**Issue by skissane** [docker/for-mac#3855]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 38FD67B8-A678-41FB-8B1B-1F2A7692E3BB/20190820133614

### Expected behavior
Able to run valgrind on a binary in an emulated architecture container.

### Actual behavior
valgrind always segfaults

### Information
  - macOS Version: 10.12.6

### Diagnostic logs
```
Docker for Mac: version 2.1.0.1 (37199)

```

### Steps to reproduce the behavior
The following commands work:
```
docker run amd64/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
docker run i386/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
```

Whereas the following all crash (segmentation fault in valgrind):
```
docker run arm32v7/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
docker run ppc64le/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
docker run s390x/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
docker run arm64v8/debian /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
```
(Note `valgrind` package not available on `arm32v5` Debian, so above test not applicable to it.)

Trying Ubuntu instead of Debian produces same result:
```
docker run arm64v8/ubuntu /bin/sh -c 'apt-get update && apt-get install -y valgrind && valgrind true'
```

Same with Fedora:
```
docker run s390x/fedora /bin/sh -c 'yum install -y valgrind && valgrind true'
```

So this doesn't appear to be distribution-specific. It appears to be a generic issue with running valgrind under qemu-user.

**Comment by guillaumerose** [comment]
ping @justincormack @djs55
