### ISSUE TITLE
Docker for Mac doesn't use cached layers and rebuilds the image from scratch every time

### ISSUE THREAD

**Issue by BurkovBA** [docker/for-mac#3856]
### Expected behavior
When I rebuild a Docker image and modify command 17, I expect that previous 16 layers are not re-built from scratch, but used from cache.  

### Actual behavior
All the previous 16 layers are built over from scratch, nothing is ever cached. Rebuilding and debugging Dockerfiles takes forever.

### Information
Running this on

MacOS X High Sierra 10.13.6, 10.13.4,
3 team members on similar Mac equipment (2017 models, 13 and 15 inch, various i5 processor versions) tried this. Caching of intermediate layers just doesn't work. 

### Diagnostic logs
Full diagnostic log:

```
Diagnose succeeded
```

Diagnostic ID: 
```
D261E8BC-FD61-4AA4-99C8-1EB16A4859FB/20190820152550
```

```
Docker for Mac: version 19.03.1

```

### Steps to reproduce the behavior

  1. Create any multi-step Dockerfile
  2. docker build -t .
  3. Modify step 17
  4. docker build -t . 

See that it rebuilds everything from scratch

**Comment by blar** [comment]
Your Dockerfile or version control may be are a part of your docker image. Add ``Dockerfile`` and ``.git`` to the .dockerignore, if you do something like ``COPY . /tmp``.
