### ISSUE TITLE
Trouble running docker on osx after a fresh install

### ISSUE THREAD

**Issue by mhgrove** [docker/for-mac#3861]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 624D4909-65BD-4EC6-9D88-C7E3A588408B/20190823135544

### Expected behavior
Docker runs after install

### Actual behavior
Docker crashes

### Information

  - macOS Version: 10.14.5

It's reproducible in that docker consistently doesn't run after install.

### Diagnostic logs

```
Docker for Mac: I'm not entirely sure, Docker won't run. I downloaded from: https://hub.docker.com/editions/community/docker-ce-desktop-mac

```

### Steps to reproduce the behavior

  1. Download from https://hub.docker.com/editions/community/docker-ce-desktop-mac
  2. Install
  3. Run, it will crash

ymmv, it could be an environmental thing. I doubt it's the case docker doesn't work on mac.

**Comment by mhgrove** [comment]
I get the error "Docker.VmnetdError error 1."; this occurs after providing my admin password for whatever thing Docker is trying to do to complete the install

**Comment by marcelloromani** [comment]
Might be related to the crash I'm seeing too #3873

**Comment by marcelloromani** [comment]
FWIW, The latest version of Docker Desktop for Mac is working for me

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Mac os version: 10.14.6 (18G1012)
