### ISSUE TITLE
Can't start any container after update to Docker Desktop for Mac 2.1.0.1(37199)

### ISSUE THREAD

**Issue by lsampaioweb** [docker/for-mac#3866]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 0CAA5EF6-2AFD-4969-BB0C-53C2AF421052/20190824194331

### Expected behavior
After I run the command: "docker-compose -f 01-traefik/docker-compose.yml up -d", the container would start.

### Actual behavior
docker-compose -f 01-traefik/docker-compose.yml up -d
Creating traefik ... error

ERROR: for traefik  Cannot start service traefik: b'Mounts denied: EOF'
ERROR: for traefik  Cannot start service traefik: b'Mounts denied: EOF'
ERROR: Encountered errors while bringing up the project.

### Information
  - Is it reproducible? Yes. Just update to the newest version. I am copying just one docker-compose file, but all my other containers are having the same problem.
  - Is the problem new? Yes. It just started. Everything was working before.
  - Did the problem appear with an update? Yes, after the update.
  - macOS Version: Mojave 10.14.6 (18G87)
  - Docker for Mac: version 2.1.0.1(37199)

### Steps to reproduce the behavior
My shared folders are:
/users, /Volumes, /private, /tmp and /var/db

This is one of my docker-compose files:
-----
version: "3.7"
services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - ${ETC_LOCALTIME}:/etc/localtime:ro
      - ./init/traefik.toml:/traefik.toml
    networks:
      - net-proxy
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:localhost
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.backend=traefik
      - traefik.port=8080
    command:
      - "--api"
      - "--docker"
      - "--docker.domain=aprendendo.com.br"
      - "--docker.exposedbydefault=false"
networks:
  net-proxy:
    external: true
-----

**Comment by danduh** [comment]
Same here.
Simple docker build takes 5-10 minutes to start!!

**Comment by lsampaioweb** [comment]
Just to let you guys know. I removed the latest version and installed the previous one and now everything is working as expected again.

More info:
$ docker --version
Docker version 18.09.2, build 6247962
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01

Now I can run the command:
$ docker-compose -f 01-traefik/docker-compose.yml up -d
Output:
Creating traefik ... done
