### ISSUE TITLE
Docker for mac crashes again after latest macOS update

### ISSUE THREAD

**Issue by marcelloromani** [docker/for-mac#3873]
- [x] I have tried with the latest version of my channel (Stable or Edge)

Restarted the mac after OS update: as I don't have Docker launch at startup, I manually launched it.
The Docker Update popup came up: wether I choose "Apply update" or "Remind me later" doesn't make any difference: docker starts and shortly after crashes.

  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `FDEB2B36-9E22-4A62-BD46-4B8E43938271/20190828164816`

### Expected behavior

Docker for mac starts and works normally.

### Actual behavior

Docker for mac starts, I am able to perform some commands (like `docker pull`, `docker-compose run --rm <something>` etc. but after a few minutes the server crashes.
Didn't do any exact measurements but I reckon it stays up between 1 and 2 minutes before crashing.

### Information
  - macOS Version: 10.14.6 (18G95)
  - docker version:
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by marcelloromani** [comment]
Maintainers: please remove the label version/10.14.6 as it's misleading.

**Comment by marcelloromani** [comment]
The crash happened also during an "image pull"
```
fc7181108d40: Already exists
01f3b6f74410: Already exists
163142c4383b: Already exists
eeed0da1db91: Already exists
ea6d6fd23371: Already exists
52f0c7b20cb8: Pull complete
6a579f60956c: Pull complete
1dcf7c70dd73: Pull complete
ed06228ccb06: Extracting [=========================>                         ]  20.87MB/40.33MB
ERROR: dial unix docker.raw.sock: connect: connection refused
```

**Comment by marcelloromani** [comment]
Deleted docker for mac, downloaded fresh copy from dockerhub, installed it.

Same buggy behaviour observed.

**Comment by marcelloromani** [comment]
Now Docker for Mac crashes after a couple minutes even without being used.
This is a blocker for me.

Have to revert to `docker-machine`, which is quite annoying.

**Comment by klimslim** [comment]
Same issues for me. Same Mac OS version. But I cannot even run Troubleshooting. It crashes in a minute after start.

**Comment by nigel-daniels** [comment]
HI Have this issue too :(  Is there a way to locate older dmg files to rollback the version?

**Comment by lsampaioweb** [comment]
> HI Have this issue too :( Is there a way to locate older dmg files to rollback the version?

I recently reported the same issue and the only solution was to remove the docker and install an earlier version.

Link to previous versions: https://docs.docker.com/docker-for-mac/release-notes/

My issue: https://github.com/docker/for-mac/issues/3866

**Comment by taiyodayo** [comment]
Hi. I'm also seeing sporadic crashes on Mac docker 19.03 series.
docker build command works fine for a few minutes, then randomly freezes.

Simplest reproducible code is:

for i in $(seq 100); do echo $i; echo FROM alpine | docker build -; done

This code runs fine on other *nixes, but only on a Mac it results in sporadic crashes.
today it froze at around every 15th execution. (ctrl-C kills the process and continues, then freeze again). Number of times it takes before crasheing seems random to me.

I have some batch scripts that regularly rebuilds containers, for now reverting to v.18 series.
I wonder if anyone else is experiencing the same symptoms.

**Comment by gabrieleCacciola** [comment]
Having the same issue, Docker for Mac v2.1.0.3 crashing after a minute.

**Comment by kns7** [comment]
Hello, 
Any news regarding this crash? It occurs on 10.5.4 also.

**Comment by wansiedler** [comment]
Havin the same issue.
Docker has been crashing dead my mac randomly for the last year.
I had to get a sever to build images there, cause I cant do this stable enough. Pleas help!

**Comment by wansiedler** [comment]
> Hi. I'm also seeing sporadic crashes on Mac docker 19.03 series.
> docker build command works fine for a few minutes, then randomly freezes.
> 
> Simplest reproducible code is:
> 
> for i in $(seq 100); do echo $i; echo FROM alpine | docker build -; done
> 
> This code runs fine on other *nixes, but only on a Mac it results in sporadic crashes.
> today it froze at around every 15th execution. (ctrl-C kills the process and continues, then freeze again). Number of times it takes before crasheing seems random to me.
> 
> I have some batch scripts that regularly rebuilds containers, for now reverting to v.18 series.
> I wonder if anyone else is experiencing the same symptoms.

+1 here!
