### ISSUE TITLE
Docker-Compose Error container already in use

### ISSUE THREAD

**Issue by jssnipes** [docker/for-mac#3882]
I am using Docker desktop v2.1.0.1(37199) and running a docker-compose that creates a container with a name that has previously been used.  
1) I check the 'docker ps -a | grep control' and can see the container it thinks is running and it is shown as exited 4 weeks ago.  
2) I tried to kill it by container ID and it tells me it is not running.  
3) I have tried restarting docker with no impact.  
4) I was able to rename the new container and get the docker-compose running, but would like to understand the issue.  

da0f38dca271        confluentinc/cp-enterprise-control-center:5.3.0       "/etc/confluent/dock…"   4 weeks ago         Exited (255) 4 weeks ago        0.0.0.0:9021->9021/tcp                                               control-center

 - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 6B5F358E-CE0A-44EB-B630-FADB5B10CC4C/20190904134719

### Expected behavior

docker-compose should create control-center container as expected

### Actual behavior

receive error 'ERROR: for control-center  Cannot create container for service control-center: Conflict. The container name "/control-center" is already in use by container "da0f38dca271a224fc4df9643fd7630d7cea9f5f8011aec611a42d619c1c3aa1". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.'

### Information

  - macOS Version: 10.14.3

Docker for Mac: version... v2.1.0.1(37199) 

### Steps to reproduce the behavior
run docker-compose up on .yml file containing 'container name: control-center'

**Comment by ulrich** [comment]
Hello @jssnipes 

As mentioned in the Docker documentation, a container name must to be uniq, even those stopped.

https://docs.docker.com/compose/compose-file/#container_name
