### ISSUE TITLE
New installation

### ISSUE THREAD

**Issue by oscarfuquen** [docker/for-mac#3885]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 0A48A217-2FCB-4D75-BBE0-BAF8539064B3/20190906053331

### Expected behavior
Install docker in mac 
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: latest

```

### Steps to reproduce the behavior

  1. . Try to install docker from the official documentation
  2. . Problem when a try to install

**Comment by dukemai** [comment]
we had the same problem with this version after upgrading and we needed to rollback to 2.1.0.1
