### ISSUE TITLE
The operation couldn’t be completed. (Docker.VmnetdError error 1.) 

### ISSUE THREAD

**Issue by wonderboy18** [docker/for-mac#3886]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wonderboy18** [comment]
Once downloaded Docker.dmg while trying to run it I would get Docker.VmnetdError error 1 and fail to install Docker , any help will be appreciated . 

Thank you .

**Comment by atai-apixio** [comment]
I got the same error.

**Comment by tina-trenkner** [comment]
Same error

**Comment by p-chandra** [comment]
Had the same issue. I used brew to install docker and it works. Hopefully this helps.

**Comment by p-chandra** [comment]
u

**Comment by zhou9110** [comment]
Hi, I can reproduce the issue by the clicking the `docker` icon directly in the window open up after click on the dmg file.

So make sure the docker application is moved to the 'Applications' folder, and run docker from the

**Comment by axmachina** [comment]
> Hi, I can reproduce the issue by the clicking the 'docker' icon directly in the window open up after opening the dmg file. This is not the standard way to run the application.
> 
> So the problem probably occurs when the docker application is **run outside the Application folder**.
> 
> ![http://g.recordit.co/FgWzem0vtb.gif](https://camo.githubusercontent.com/c5baa2a4e8dd5a3c4df33894ce4c8623ce2ab283/687474703a2f2f672e7265636f726469742e636f2f4667577a656d307674622e676966)
> 
> Instead, if we drag the docker application and drop to the 'Applications' folder, and run it from the 'Application' folder. No issues were found.
> 
> Also beware that the launchpad may launch the wrong application during searching, especially when the DMG file is opened but not yet rejected.

Doesn't solve for me. Getting same error running the app from the Applications folder. My luck :/

**Comment by axmachina** [comment]
Solved with this

https://github.com/docker/for-mac/issues/3809#issuecomment-557730621

**Comment by vladpetyuk** [comment]
It worked for me after I installed brew. Not docker through brew, but just brew. Somehow having brew just made docker happy enough to proceed without the problem.
