### ISSUE TITLE
while installing i get this Error "the operation couldn't be completed. (docker.vmnetd error error 1.)"

### ISSUE THREAD

**Issue by skbind** [docker/for-mac#3891]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C9B476C4-5F5F-4E74-893A-8D7BB5486BAA/20190911092919

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Graig123git** [comment]
i got this error just now too

**Comment by lvhuichao** [comment]
have u resolved it? i got this error now.can i got your help?

**Comment by skbind** [comment]
Can anyone help fix the issue or any work around to proceed ?

**Comment by toopa2002** [comment]
same issue

**Comment by skbind** [comment]
Can we expect any help from docker team ?

**Comment by toopa2002** [comment]
Move docker to applications folder, instead of double click to install solve my problem
