### ISSUE TITLE
Docker failed on start 

### ISSUE THREAD

**Issue by kledac** [docker/for-mac#3898]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BF37264A-5DF8-488D-ACBC-9E736992D733/20190914010732

### Information

This is a new docker installation and it's not starting after installation.
  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Download latest docker
  2. Copy to Applications
3. Try to run

**Comment by dsandrade** [comment]
same issue
