### ISSUE TITLE
Error response from daemon: dial unix ...: connect: connection refused

### ISSUE THREAD

**Issue by fangzhouxin** [docker/for-mac#39]
### Information

Diagnostic ID: C66DCF4E-ED06-4A88-83D6-0921B7A7582C
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by fangzhouxin** [comment]
The full error message is 
```
Error response from daemon: dial unix /Users/fzx/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Comment by samoht** [comment]
I am closing the issue, but please re-open it when you can provide more information

- Expected behavior
- Actual behavior
- Steps to reproduce

The more information you can give us, the easier it will be for us to help you. Thanks!

**Comment by feus4177** [comment]
I'm seeing this issue as well. During development I keep the containers open and periodically I will get kicked out of them with the above error message. Expected behavior is that I would stay attached. Actual behavior is that I'm getting kicked out. I don't know how you would go about reproducing though.

**Comment by dsheets** [comment]
@feus4177 could you please run `Diagnose & Feedback...`, upload your diagnostic bundle, and open a new issue with the details of the behavior you are seeing? It would be really helpful if you could also include any information related to events that occur just prior to the container failures.

**Comment by feus4177** [comment]
Alright, I've opened issue #568.

**Comment by ruandao** [comment]
I found the same error when i use docker to bench other app:
`CMD ["websocket-bench", "-g", "bench-generator.js", "-a", "60000", "-c", "1000", "http://10.10.60.189:1314"]`

**Comment by samoht** [comment]
@feus4177 could you please run Diagnose & Feedback..., upload your diagnostic bundle, and open a new issue with the details of the behavior you are seeing? Thanks!

**Comment by feus4177** [comment]
I did, it's in issue #568
