### ISSUE TITLE
[ERROR]  docker-cli          docker ps failed

### ISSUE THREAD

**Issue by bkarakashev** [docker/for-mac#390]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: F3F75424-03F7-4980-BEF5-91CC632E1F47
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by bkarakashev** [comment]
Fixed by deleting the docker container file

**Comment by ksom** [comment]
Hi @bkarakashev Can you tell me where is it ? I have this problem.

**Comment by bkarakashev** [comment]
@ksom its located here: /Users/My_User/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in F3F75424-03F7-4980-BEF5-91CC632E1F47/20160822-140029.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.driver.amd64-linux][2765] <Notice>: COM1 connected to /dev/ttys003
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.driver.amd64-linux][2765] <Notice>: COM1 linked to /Users/blago/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.driver.amd64-linux][2765] <Notice>: Error reading vsyslog length: EOF
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.driver.amd64-linux][2765] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.slirp][2763] <Notice>: PPP.listen: closing connection
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.osxfs][2762] <Error>: Fatal unexpected exception: Socket.Closed
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.osx.hyperkit.linux][2758] <Notice>: Reap com.docker.osxfs (pid 2762): exit status 1
Aug 22 13:52:43 MacBook-Pro-2 Docker[com.docker.osx.hyperkit.linux][2758] <Notice>: Reap com.docker.driver.amd64-linux (pid 2765): exit status 0
```

**Comment by zhaoxixin** [comment]
Hi @bkarakashev 
I also met this problem, But I did not find that file to delete
Diagnose details:
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.1 (build: 17B1003)
logs: /tmp/72C7D5D9-8663-4DBF-B6B0-93626C92E4AB/20180226-143419.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
--------------
directory:
![image](https://user-images.githubusercontent.com/31915085/36656851-1cdc016a-1b05-11e8-9efb-cabc810e00a5.png)

**Comment by zhaoxixin** [comment]
I sloved the problem aobut I mentioned,
please refer /issues/2642
thanks
