### ISSUE TITLE
Not able to run $docker version

### ISSUE THREAD

**Issue by tarnisharma** [docker/for-mac#391]
### Actual behavior
$docker version  does not return anything. Just hangs.
Similarly none of the other commands including $docker ps are working.
However
$docker --version works

### Information

Diagnostic ID: F2F453A6-DC2E-4D5E-AD44-A8F4F57D6C73
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)

Diagnostic Report : 
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/F2F453A6-DC2E-4D5E-AD44-A8F4F57D6C73/20160822-190906.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/tarni.sharma/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/F2F453A6-DC2E-4D5E-AD44-A8F4F57D6C73/20160822-190906/qemu-img-check.stdout 2> /tmp/F2F453A6-DC2E-4D5E-AD44-A8F4F57D6C73/20160822-190906/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by elgreg** [comment]
see https://github.com/docker/for-mac/issues/350

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in F2F453A6-DC2E-4D5E-AD44-A8F4F57D6C73/20160822-190922.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug 22 16:04:28 LAP0001937 Docker[com.docker.vmnetd][995] <Notice>: User 1641081875 has container folder /Users/tarni.sharma/Library/Containers/com.docker.docker/Data/s60
Aug 22 16:04:28 LAP0001937 Docker[com.docker.vmnetd][995] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 22 16:04:28 LAP0001937 Docker[com.docker.vmnetd][995] <Notice>: User 1641081875 has container folder /Users/tarni.sharma/Library/Containers/com.docker.docker/Data/s60
Aug 22 16:04:28 LAP0001937 Docker[com.docker.vmnetd][995] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 22 16:04:28 LAP0001937 Docker[com.docker.docker][980] <Error>: Symlinks are not correctly installed.
Aug 22 16:04:28 LAP0001937 Docker[com.docker.docker][980] <Notice>: com.docker.osx.hyperkit.linux launched with PID 999
Aug 22 16:04:30 LAP0001937 Docker[com.docker.frontend][998] <Critical>: dial unix /Users/tarni.sharma/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Aug 22 16:04:30 LAP0001937 Docker[com.docker.docker][980] <Error>: frontend process failed
Aug 22 16:04:30 LAP0001937 Docker[com.docker.osx.hyperkit.linux][999] <Notice>: Acquired task manager lock
```
