### ISSUE TITLE
Link to current Kitematic is broken

### ISSUE THREAD

**Issue by denisa** [docker/for-mac#3913]
**Given** Docker Desktop 2.1.0.3
**When** Kitematic is outdated
**Then** a dialog invites me to download latest Kitematic from 
https://download.docker.com/kitematic/Kitematic-Mac.zip

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5037BA86-65FE-4589-B002-D8F36803F26D/20190920113138

### Expected behavior
It downloads the latest version (0.17.8)

Better yet, updating Kitematic happens as Docker Desktop update, no 2nd step needed.

### Actual behavior
It downloads an outdated version (0.17.6)!

### Information
  - macOS Version: 10.14.6 (18G95)

**Comment by mat007** [comment]
Thank you for reporting this, this should be fixed now (it now correctly downloads the latest version).

**Comment by jim-obrien-orig** [comment]
This is a terribly insecure way to perform upgrades.

**Comment by denisa** [comment]
1/ it was indeed fixed
2/ and became obsolete with the introduction of the _Dashboard_
