### ISSUE TITLE
When attempting to launch Kitematic it's showing a version discrepancy.  Downloading & installing the latest version as requested it doesn't resolve.  Keeps prompting to update

### ISSUE THREAD

**Issue by blanczak** [docker/for-mac#3915]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by blanczak** [comment]
When attempting to launch Kitematic it's showing a version discrepancy. Downloading & installing the latest version as requested it doesn't resolve. Keeps prompting to update

**Comment by mat007** [comment]
This should have been fixed now, see #3913 
Sorry for the inconvenience.

**Comment by blanczak** [comment]
Awesome!  Yup it works perfect now, thanks again.
