### ISSUE TITLE
Docker for Mac unable to start

### ISSUE THREAD

**Issue by adericbourg** [docker/for-mac#3919]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5B33F7B0-5E1C-4D71-A2C3-5FB55E30F4E2/20190923093841

### Expected behavior
With a brand new installation of Docker or after a reset to factory default, Docker should start.

### Actual behavior
With a brand new installation, Docker is stuck in STARTING mode.

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.1, 2.1.0.2, 2.1.0.3
Diagnose succeeded
```

### Steps to reproduce the behavior

  1. Install latest (2.1.0.3) Docker for Mac 
  2. Start it

**Comment by sruthinagalla** [comment]
I have the same issue.
