### ISSUE TITLE
kubernetes is not starting anymore ... 

### ISSUE THREAD

**Issue by nauni77** [docker/for-mac#3920]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 07379A4A-D3D2-4771-960D-D44A1363D653/20190923104932

### Expected behavior
Docker and Kubernetes is running ...

### Actual behavior
Docker is started, but kubernetes is not starting ...

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: latest

```

### Steps to reproduce the behavior

  1. Use latest MacOSX
  2. Upgrade to latest Stable Docker4Mac

=> Kubernetes is not working anymore. Same behaviout on two different Devices.

**Comment by davidthewatson** [comment]
I'm having similar issues on macos 10.14.6:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Service Unavailable
```

This is after changing proxy settings from the preferences GUI and hitting the restart button.
