### ISSUE TITLE
Docker Desktop is starting forever

### ISSUE THREAD

**Issue by CedricFinance** [docker/for-mac#3921]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3372B352-41B8-419E-BDC6-37CF86038E71/20190923142149

### Expected behavior
Docker Desktop should start

### Actual behavior
Docker Desktop stays in "Docker Desktop is starting" forever

In the Console logs, I have the following logs: 
[logs-before-screen.txt](https://github.com/docker/for-mac/files/3642713/logs-before-screen.txt)

When I run: `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` and hit enter several times. The VM starts and I get these logs: 
[logs-after-screen.txt](https://github.com/docker/for-mac/files/3642710/logs-after-screen.txt)

When I run the screen command, I sometime get this:
![Capture d’écran 2019-09-23 à 13 42 13](https://user-images.githubusercontent.com/3935032/65435460-da0b3c80-de20-11e9-9df5-731882010f0f.png)

### Information
  - macOS Version: 10.14.6 (18G95)

### Diagnostic logs
```
Diagnose succeeded
```

### Steps to reproduce the behavior
  1. Install Docker For Mac 2.1.0.3
  2. Launch it

**Comment by EnFinlay** [comment]
Experiencing the same issue. Even if I uninstall Docker and download an older version, it refuses to start

**Comment by CedricFinance** [comment]
@EnFinlay You can find a quick hack [here](https://github.com/docker/for-mac/issues/2655) to help you use Docker for Mac, while the root issue is solved

**Comment by EnFinlay** [comment]
@CedricFinance installing the .dmg worked. Thank you!
