### ISSUE TITLE
can not start kubernetes

### ISSUE THREAD

**Issue by jomenxiao** [docker/for-mac#3927]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 2FF88BEF-D0EF-4798-B37C-6BCAE456DCCC/20190926094656

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by benjefferies** [comment]
Also seeing this. Seems to hang on startup and can't even disable it

**Comment by jwalton** [comment]
I'm running into this too.  (Also, this is a dupe of https://github.com/docker/for-mac/issues/3920.)
