### ISSUE TITLE
B6F73743-68CD-412A-8078-DB141438FB32/20190926143018

### ISSUE THREAD

**Issue by jaazevedo84** [docker/for-mac#3928]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by arishlabroo** [comment]
I had the same issue, this image works
https://github.com/docker/for-mac/issues/2655#issuecomment-534557308

**Comment by jaazevedo84** [comment]
Thx Arish I'll try it when i get a chance.
