### ISSUE TITLE
Docker for Mac nginx example (from the installation docs) doesn't run

### ISSUE THREAD

**Issue by zharvey-welltok** [docker/for-mac#393]
### Expected behavior
After installing Docker for Mac, running `docker run -d -p 80:80 --name webserver nginx` *should* run nginx and allow me to access the default/splash page when I point a browser to `http://localhost`.

### Actual behavior
I get normal/success console output but nothing is served back from `http://localhost`.

### Information
All information and steps to reproduce are in a StackOverflow question I previously asked (that has yet to be answered):

http://stackoverflow.com/questions/39082936/docker-for-mac-nginx-example-doesnt-run

As one user ('Nio') points out, you need to start the image with `-p 8080:80`, **not** `-p 80:80` like your example shows.

### Steps to reproduce the behavior
Just go to your own [Installation page](https://docs.docker.com/engine/installation/mac/) and follow the instructions down to Step 3. Try to run nginx using the exact same command as what is posted on that page and then point a browser to `http://localhost`. If it works for you, then there is something network-related (firewall?) on my side, but I feel that should be addressed in your docs.

If it doesn't work for you, you need to change you docs ASAP! Again, running it with `-p 8080:80` worked (but then require me to point my browser to `localhost:8080`).

Either way, I think Docker for Mac's instructions need to change (either provide a troubleshooting section if the nginx example - or any examples - don't work) or they are in need of correction.

**Comment by jclif** [comment]
I am seeing the same thing. The only way I can access the container is from 0.0.0.0.

**Comment by dsheets** [comment]
I cannot reproduce this behavior. What do you mean by "normal/success console output"? Are you running anything like a firewall on your machine? How is it configured?

**Comment by mchiang0610** [comment]
@zharvey-welltok Just tested this to be working on the latest Docker for Mac beta 25 and stable.

**Comment by etcetc** [comment]
I came across this because localhost didn't work for me with docker engine version 19.03.5 and docker client 18.06.1-ce.  It does work if I find the container ip address and use that.
