### ISSUE TITLE
Docker for mac does not start 

### ISSUE THREAD

**Issue by ncarenton** [docker/for-mac#3930]
Docker for mac is starting forever. I tried to reset disk image, factory defaults, uninstall.

BFCED27B-C610-4D13-AACC-B05F028BEB46/20190928195404

**Comment by maxberggren** [comment]
Same here, tried all the above.

ECE9AE9D-5598-4E11-8EF2-02E594C25776/20191004054253

**Comment by deepakcpakhale** [comment]
Same here, tried all the above.

B47EC774-3562-469D-992F-4AC0C866002C/20191007064958
