### ISSUE TITLE
Docker for Mac cannot upgrade past 18.06.1.  VPNKit Fatal Error

### ISSUE THREAD

**Issue by lucianthorr** [docker/for-mac#3934]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:  (Diagnostics window spins)

### Expected behavior

Docker for Mac starts successfully

### Actual behavior

<img width="987" alt="Screen Shot 2019-09-18 at 12 00 50 PM" src="https://user-images.githubusercontent.com/5907505/65882873-e84ae280-e363-11e9-89e1-ec7c3f448995.png">

* Reset Docker to factor defaults -> repeats the process, same error
* Diagnose & Feedback -> spins indefinitely
* Exit -> Exits

### Information

  - macOS Version: 10.14.6
On a clean 2018 Macbook.  
I can get Docker versions up to (and including) 18.06.1-ce-mac73 to install correctly.
Starting with Docker 2.0.0.0-mac78, the error begins.

I see in the 2.0.0.0 release notes:
`VPNKit: Improved scalability of port forwarding. Related to docker/for-mac#2841`
`VPNKit: Limit the size of the UDP NAT table. This ensures port forwarding and regular TCP traffic continue even when running very chatty UDP protocols.`

I don't know anything about VPNKit.  Is there some kind of configuration that I need to double check?

### Steps to reproduce the behavior

  1. Run Docker for Mac

**Comment by lucianthorr** [comment]
I'm going to close this because I was able to install newer versions of Docker after harassing my IT to loosen certain software restrictions.  I have Carbon Black's Cb Defense installed and I believe it was restricting certain processes involved in the installation.

**Comment by stephen-turner** [comment]
Thanks for the update.
