### ISSUE TITLE
MacOs 10.14.6 kernel panic

### ISSUE THREAD

**Issue by ipleten** [docker/for-mac#3935]
I'm not sure what is culprit. I'm trying to run 'telepresence' to connect to k8s cluster via VPN
`
telepresence --swap-deployment pipe-test-977 --namespace ps --docker-run --rm -it pipe-test --method container --expose --port 8080 `
It starts but after a few minutes I got kernel panic.
I'm using: docker-for-desktop edge 2.1.3.0(38275) version, but issue was reproducible on other  version.

**Comment by dalvizu** [comment]
`com.netskope.client.nsIPFilterNKE` - I wonder if this is related to netskope?
