### ISSUE TITLE
Can't start Docker on Catalina

### ISSUE THREAD

**Issue by tmsblgh** [docker/for-mac#3941]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5E9C3796-8DD7-4E9C-8D0E-88C81E080FA2/20190927193248

### Expected behavior
Docker can be started.

### Actual behavior
Docker cannot be started.

### Information
  - Is it reproducible?
Yes

  - Is the problem new?
Yes

  - Did the problem appear with an update?
Yes, with macOS update.

Note:Diagnosing not working from the app, just loading for hours... the above mentioned logs were collected through Terminal.

  - macOS Version:
macOS Catalina (Version 10.15 Beta (19A578c))

  - Docker for Mac: Latest stable, latest edge but fails with previous versions too.

### Steps to reproduce the behavior
  1. Start Docker for Mac

**Comment by tmsblgh** [comment]
Workaround:
Start it from /Applications/Docker.app/Contents/MacOS, hold Option and Command keys then click Docker (the Unix executable)

**Comment by guillaumerose** [comment]
If you open `Console` and filter with the keyword `kernel` and open Docker.app, what do you see ?
We tested on fresh Catalina and it worked for us.

**Comment by tmsblgh** [comment]
`default	20:16:54.042819+0200	kernel	[IGFB][INFO   ] [Set_attribute] (attribute=' bst', value=536)
default	20:16:54.830832+0200	kernel	[IGFB][INFO   ] [Set_attribute] (attribute=' bst', value=536)
default	20:16:55.165147+0200	kernel	ALF, old data swfs_pid_entry <private>, updaterules_msg <private>, updaterules_state <private>
default	20:16:55.378211+0200	kernel	ALF, hash_free: found kext_info <private>
default	20:16:55.834784+0200	kernel	[IGFB][INFO   ] [Set_attribute] (attribute=' bst', value=0)
default	20:16:56.442723+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:56.697417+0200	kernel	ALF, old data swfs_pid_entry <private>, updaterules_msg <private>, updaterules_state <private>
default	20:16:56.757353+0200	kernel	ALF, old data swfs_pid_entry <private>, updaterules_msg <private>, updaterules_state <private>
default	20:16:56.791604+0200	kernel	ALF, old data swfs_pid_entry <private>, updaterules_msg <private>, updaterules_state <private>
default	20:16:56.835330+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:16:56.953859+0200	kernel	ALF, hash_free: found kext_info <private>
default	20:16:56.956589+0200	kernel	ALF, hash_free: found kext_info <private>
default	20:16:57.135917+0200	kernel	ALF, hash_free: found kext_info <private>
default	20:16:57.441792+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:57.535165+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:16:58.013112+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:58.163593+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:16:58.445686+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:58.571110+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:16:59.012684+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:59.163604+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:16:59.445941+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:16:59.805071+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:00.729371+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:01.163975+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:01.445890+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:01.770791+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:01.998136+0200	kernel	ALF, old data swfs_pid_entry <private>, updaterules_msg <private>, updaterules_state <private>
default	20:17:02.036346+0200	kernel	ALF, hash_free: found kext_info <private>
default	20:17:02.444675+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:02.808371+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:03.298868+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:03.807985+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:04.449156+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:04.808095+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:05.190582+0200	kernel	Sandbox: 50 duplicate reports for com.apple.WebKit deny(1) mach-lookup com.apple.CoreDisplay.Notification
error	20:17:05.190593+0200	kernel	Sandbox: CoreSpotlightSer(1399) deny(1) process-info-dirtycontrol self
default	20:17:05.372081+0200	kernel	Sandbox: 4 duplicate reports for CoreSpotlightSer deny(1) process-info-dirtycontrol self
error	20:17:05.372093+0200	kernel	Sandbox: com.apple.WebKit(3584) deny(1) mach-lookup com.apple.CoreDisplay.Notification
default	20:17:05.599164+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:05.654097+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:05.883119+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:06.149735+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:06.298330+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:06.323647+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:06.732645+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:07.148351+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:07.884629+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:08.152195+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:08.300749+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:08.792236+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:09.302577+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:09.811440+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:10.019577+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:10.040570+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:10.302174+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:10.810950+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:11.302253+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:11.521462+0200	kernel	PMRD: setAggressiveness(0) kPMMinutesToSleep = 0
default	20:17:11.523255+0200	kernel	PMRD: aggressiveness changed: system 1->0, display 2
default	20:17:11.523262+0200	kernel	PMRD: idle time -> 0 secs (ena 0)
default	20:17:11.523264+0200	kernel	PMRD: idle sleep timer disabled
default	20:17:11.523266+0200	kernel	PMRD: changePowerStateToPriv(4)
default	20:17:11.523299+0200	kernel	PMRD: PowerChangeDone: ON_STATE->ON_STATE
default	20:17:11.776869+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:11.919298+0200	kernel	ACM: verifyPolicy: Verifying policy DeviceOwnerAuthenticationWithBiometrics, checkKeybagUUID = No, CS[109].
default	20:17:11.919313+0200	kernel	ACM: verifyPolicy: Policy satisfied = No, preflight = Yes, CS[109].
default	20:17:11.957019+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:11.977169+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:12.460053+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:12.542597+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:12.591358+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:12.607634+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:12.742537+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:12.758106+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:12.874943+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:12.891303+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:13.591363+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:13.607960+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:13.874588+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:14.158876+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:14.741270+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:15.159913+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:15.318603+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:15.343175+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:16.022835+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:16.158072+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:16.458060+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:16.783359+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:17.216809+0200	kernel	Sandbox: 26 duplicate reports for com.apple.WebKit deny(1) mach-lookup com.apple.CoreDisplay.Notification
error	20:17:17.216819+0200	kernel	Sandbox: swcd(437) deny(1) system-fsctl _IO('h', 47)
default	20:17:17.305820+0200	kernel	PMRD: setAggressiveness(0) kPMMinutesToSleep = 1
default	20:17:17.307651+0200	kernel	PMRD: aggressiveness changed: system 0->1, display 2
default	20:17:17.307660+0200	kernel	PMRD: idle time -> 0 secs (ena 1)
default	20:17:17.307661+0200	kernel	PMRD: idle sleep timer enabled
default	20:17:17.734910+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:17.904542+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
error	20:17:17.952591+0200	kernel	Sandbox: com.apple.WebKit(3587) deny(1) mach-lookup com.apple.CoreDisplay.Notification
default	20:17:18.257963+0200	kernel	Sandbox: 2 duplicate reports for com.apple.WebKit deny(1) mach-lookup com.apple.CoreDisplay.Notification
error	20:17:18.257972+0200	kernel	Sandbox: callservicesd(418) deny(1) mach-lookup com.apple.accountsd.accountmanager
error	20:17:18.285037+0200	kernel	Sandbox: QuickLookSatelli(1282) deny(1) mach-lookup com.apple.accountsd.accountmanager
default	20:17:18.486958+0200	kernel	Sandbox: 1 duplicate report for QuickLookSatelli deny(1) mach-lookup com.apple.accountsd.accountmanager
error	20:17:18.486969+0200	kernel	Sandbox: callservicesd(418) deny(1) mach-lookup com.apple.accountsd.accountmanager
default	20:17:18.700804+0200	kernel	Sandbox: 1 duplicate report for callservicesd deny(1) mach-lookup com.apple.accountsd.accountmanager
error	20:17:18.700817+0200	kernel	Sandbox: Mail(3529) deny(1) file-link /Users/tmsblgh/Library/Application Support/AddressBook/Sources/7A851EE4-AE27-458B-AD6F-96C42CDFB303/.AddressBook-v22_SUPPORT/_EXTERNAL_DATA/837F7243-6B53-47EA-B72C-D7D2082CA914
default	20:17:18.734205+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:18.792041+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:18.953948+0200	kernel	Sandbox: 1 duplicate report for Mail deny(1) file-link /Users/tmsblgh/Library/Application Support/AddressBook/Sources/7A851EE4-AE27-458B-AD6F-96C42CDFB303/.AddressBook-v22_SUPPORT/_EXTERNAL_DATA/837F7243-6B53-47EA-B72C-D7D2082CA914
error	20:17:18.953963+0200	kernel	Sandbox: com.apple.WebKit(3587) deny(1) mach-lookup com.apple.CoreDisplay.Notification
default	20:17:19.734072+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:19.833838+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:19.883620+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:19.899059+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:20.001507+0200	kernel	Starting poll type 4
default	20:17:20.001513+0200	kernel	Restarting poll type 4
default	20:17:20.016079+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:20.032314+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:20.038475+0200	kernel	SmartBattery: finished polling type 4
default	20:17:20.050487+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:20.082488+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:20.300214+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:20.326261+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:20.601242+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:20.921315+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:21.883686+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:21.900249+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:22.016913+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:22.033236+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:23.767082+0200	kernel	tx_flush:1028: xid 2749423 tx stats: # 3900 finish 3893 enter 694 wait 137 5861us close 77us flush 6322us
default	20:17:30.445766+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:30.461649+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:30.595546+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:30.612082+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:31.312242+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:31.329046+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:31.730206+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:31.805742+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:33.587888+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:33.813436+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
default	20:17:33.871032+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] Disabling Render Compression
default	20:17:34.021807+0200	kernel	[IGFB][INFO   ] [Flip_Transaction] CCS Param update: AuxOffset:0x0 AuxStride:0x0
`

**Comment by tmsblgh** [comment]
```sudo launchctl config user path $PATH``` solved the issue.

**Comment by fabien-chebel** [comment]
I ran into the same problem and managed to fix it by uninstalling docker manually:

- Removing `Docker.app` from `/Applications`
- Removing the following elements:
  - `~/.docker` directory
  - `~/Library/Preferences/com.docker.docker.plist`
  - `~/Library/Caches/com.docker.docker` directory
  - `~/Library/Containers/com.docker.docker` directory
  - `~/Library/Containers/com.docker.helper` directory
  - `~/Library/Group Containers/group.com.docker` directory
  -  `/Library/LaunchDaemons/com.docker.vmnetd.plist`

After that, I simply installed Docker again and was prompted for my user password to perform the install process upon first launch.

**Comment by jim-obrien-orig** [comment]
Also `/Library/PrivelegedHelperTools/com.docker.vmnetd`

**Comment by rpsu** [comment]
>sudo launchctl config user path $PATH solved the issue.
this seems to require reboot, but is there a way to overcome the restriction? I'd need to configure a CI job on catalina, which should be able to install and launch the Docker.app independently of user actions. AppleScript would require a password which I do not have for that environment.

**Comment by dougfarre** [comment]
If you installed with brew, you can do `brew cask uninstall docker` then `brew cask install docker`.  That fixed it for me.

**Comment by hodrigohamalho** [comment]
I'm with this error and none of those workarounds works for me :/

**Comment by Openwater-jfs** [comment]
Same problem. Tried all workarounds. Any other ideas?

**Comment by rkstamm** [comment]
I have a new mac with the latest Catalina, and I have tried all of these things. After installing, I run it, put in my password to allow changes, and it never runs, and sticks on the notification window. System log records this: com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.mdmclient.1894): Failed to bootstrap path: path = /usr/libexec/mdmclient, error = 108: Invalid path

Any ideas out there?

**Comment by hodrigohamalho** [comment]
@tmsblgh sorry, why this issue is closed?

**Comment by kevprice83** [comment]
I also have this issue and no way to fix this.

**Comment by Openwater-jfs** [comment]
fwiw (and, i feel boneheaded about this), the docker flags '-i', '-it' and '--interactive' are subtly different (see https://docs.docker.com/v17.12/edge/engine/reference/commandline/run/#examples). i was using '-i' and waiting for a prompt. no prompt. dr schitzengiggles asks, what happens if i type in 'ls'? voila .. file listing. used '-it' instead and got the prompt. note to self: rtfm. so really, no idea which, if any, of the above workarounds fixed the problem for me.

**Comment by kevprice83** [comment]
@Openwater-jfs the issue is not about starting a container but about starting the docker service. In my case the docker desktop app.

**Comment by akobyakov** [comment]
I can confirm it is still the case with 2.2.0.0,42247 on MacOS Catalina 10.15.2. 
I'm also experiencing the symptoms described by @rkstamm.
On top of that, installing docker makes the system unstable, eventually ending up in the state where no files can be _written_ (but not read) until a reboot.

**Comment by JoelMVanDyk** [comment]
I'm getting the same.  I've installed and de-installed 3xs now.  No luck.

**Comment by abiudrodas** [comment]
I have the same issue, somebody have fixed it some way?

**Comment by hodrigohamalho** [comment]
At least on my environment, the issue was caused by an enterprise firewall, I removed it and everything has been working fine.

**Comment by abiudrodas** [comment]
> I have the same issue, somebody have fixed it some way?

I couldn't use the last versión of Docker desktop, so I installed the version 2.0.0.3 and it works perfectly in Catalina
