### ISSUE TITLE
docker consistently crashes with "Docker.VmnetdError error 1.

### ISSUE THREAD

**Issue by nicks** [docker/for-mac#3943]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: AF9C5C2F-BE6A-42BE-8C2D-4CEA90FB05F8/20191002213000

### Expected behavior
docker starts

### Actual behavior
docker crashes

### Information
i'm not even able to get into the preferences pane

<img width="601" alt="Screen Shot 2019-10-02 at 2 27 42 PM" src="https://user-images.githubusercontent.com/278641/66083482-4113aa00-e521-11e9-8b86-b37efb8e01c6.png">

i've already done a factory reset on Docker a few times. It works until I restart the machine, and then it's failing again.

**Comment by zhou9110** [comment]
Have you moved the docker application to the Application folder? You can have a look at issue #3886, hopefully it can help.
