### ISSUE TITLE
Unable to install on mac os

### ISSUE THREAD

**Issue by swetharajendra05** [docker/for-mac#3946]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello,

We need more informations :)

Thank you,
