### ISSUE TITLE
Registry issue: certificate signed by unknown authority on a valid cert

### ISSUE THREAD

**Issue by ohlookemus** [docker/for-mac#395]
### Expected behavior

docker login to registry should work without having to set it as an insecure registry

### Actual behavior

x509: certificate signed by unknown authority

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

4BED4F38-02E4-40A9-844D-3FF643FA09F9

  - a reproducible case if this is a bug, Dockerfiles FTW

Valid SSL cert generated by goDaddy for a gitlab registry setup

  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

OSX 10.11.6

### Steps to reproduce the behavior

  1. Try to log into a registry setup on gitlab
  2. Error response from daemon: Get https://my_git_lab:4567/v1/users/: x509: certificate signed by unknown authority

Only way to get around right now is to just add this to the insecure registry list. I've tried adding the certificates to /etc/docker/certs.d (not sure if this is actually used on Mac). https://docs.docker.com/engine/security/certificates/#/troubleshooting-tips

**Comment by dsheets** [comment]
Could you please post the certificate somewhere if possible? We are using a standard set of CAs inside of Docker for Mac that should accept most certificates vouched for by mainstream web authorities. There is a custom CA feature currently in progress that would help you work around this issue but we'd be very interested in fixing our CA set. I'm sorry a response has taken so long -- we are still working on our issue triage and support processes. Thanks for using Docker for Mac!

**Comment by ohlookemus** [comment]
This actually ended up being a non-issue as it was an issue with the way that our certificate issuer issues certs. Those who use GoDaddy certs may run into this issue from what I've seen.

**Comment by stowns** [comment]
@ohlookemus can you please elaborate on what exactly was the issue w/ the way the cert was issued? others may run into this and not know where to start

**Comment by ohlookemus** [comment]
This was quite awhile back but from what I remember, GoDaddy issues certificates don't chain properly when used with some browsers and tools. Firefox for example is super strict and will fail/alert you on a bad cert. We had to chain our issued cert with the intermediate cert like so,

`cat mycert.crt gd_bundle-g2-g1.crt -> my-chained.crt`

Once we did that, everything worked fine.
