### ISSUE TITLE
`kubectl.docker` is added to PATH every time Docker for Mac starts up

### ISSUE THREAD

**Issue by patricklucas** [docker/for-mac#3952]
### Expected behavior

Docker for Mac does not persistently re-create `/usr/local/bin/kubectl.docker` owned by root even if Docker for Mac's Kubernetes features are not enabled.

### Actual behavior

Docker for Mac persistently re-creates `/usr/local/bin/kubectl.docker` owned by root even if Docker for Mac's Kubernetes features are not enabled.

This means that every time Docker for Mac starts, suddenly my shell completion for `kubectl` no longer has a space after it for a command to be added, and I have to run `sudo rm /usr/local/bin/kubectl.docker` which is pretty disruptive.

### Information

Ideally, this file is only created if and when Docker for Mac's Kubernetes features are enabled—or, probably for the better, not including copies of the Kubernetes CLI tools at all and letting users install them as they wish.

**Comment by max-rocket-internet** [comment]
See https://github.com/docker/for-mac/issues/3449

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 2.1.0.5 (40693).

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 2.2.0.3 (42716).

**Comment by max-rocket-internet** [comment]
Yes, it's super annoying. I run this after every docker start: `rm -f $(which kubectl.docker)`

**Comment by max-rocket-internet** [comment]
Same as https://github.com/docker/for-mac/issues/3449 https://github.com/docker/for-mac/issues/3380

**Comment by patricklucas** [comment]
@max-rocket-internet I thought I'd be clever and try `rm kubectl.docker; touch kubectl.docker; chflags uchg kubectl.docker` (similar to `chattr +i` on Linux) but then got this on Docker startup:

![Screen Shot 2020-02-13 at 13 29 35](https://user-images.githubusercontent.com/95053/74435629-26552880-4e65-11ea-871c-aec4dfc539c8.png)

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 2.2.0.5 (43884).

**Comment by max-rocket-internet** [comment]
It's still super annoying!

/remove-lifecycle stale

**Comment by max-rocket-internet** [comment]
@stephen-turner any chance of a fix for this?

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 2.3.0.3 (45519).

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 2.3.0.5 (48029).

**Comment by max-rocket-internet** [comment]
This bug still exists in Docker Desktop 2.4.0.4 (480506).

**Comment by max-rocket-internet** [comment]
It's not stale and it's super annoying

/remove-lifecycle stale

**Comment by max-rocket-internet** [comment]
It's not stale and it's super annoying

/remove-lifecycle stale

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 3.5.2 (66501).

/remove-lifecycle stale

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 3.6.0 (67351).

**Comment by patricklucas** [comment]
This bug still exists in Docker Desktop 4.4.2 (73305).

**Comment by skyreacher** [comment]
I tested this with Docker Desktop 4.4.2 yesterday and saw that Docker Desktop creates the link to kubectl during setup. But only if no kubectl is already installed on the system.

So I installed my desired kubectl version with MacPorts before installing Docker Desktop. It seems to work fine this way.
