### ISSUE TITLE
Unable to execute shell commands in docker containers after update to macOS catalina

### ISSUE THREAD

**Issue by jakeroam** [docker/for-mac#3962]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 792DEF4F-2F9D-4762-9BEC-A000FB1571DF/20191010224628

### Expected behavior
`docker exec -t container_name /bin/bash`
I should be able to execute shell commands in the named docker container after running this

### Actual behavior
No response from the container after getting shell access
![Screen Shot 2019-10-11 at 11 52 05 AM](https://user-images.githubusercontent.com/20271208/66612239-a3edfb00-ec1d-11e9-9e3a-0f696ba15653.png)

### Information
  - macOS Version: 10.15
Was working in 10.14.6

### Diagnostic logs

```
Docker for Mac: version 2.1.0.3

```

### Steps to reproduce the behavior

  1. run `docker exec -t container_name /bin/bash`
  2. try to run `ls` or any other commands inside the container

**Comment by ErenPhayte** [comment]
Still happens in latest Edge version Docker for Mac: version 2.1.4.0

It actually happens with any command inside the container making them unusable.

Any workaround to this in the meantime?

**Comment by jakeroam** [comment]
@ErenPhayte you need the `i` for `-it`  where the `i` is interactive.
I was not at the top of my game when I created this issue
