### ISSUE TITLE
internal error (autoStartOnLoginCheckButtonActionRequired)

### ISSUE THREAD

**Issue by themccallister** [docker/for-mac#397]
### Steps to reproduce

1. Installed Docker Beta on macOS Sierra
2. Open Docker preferences
3. Select or Deselect the open to start at login

### Expected behavior

Check box to be deselected and the work as normal

### Actual behavior

This message is displayed:

<img width="710" alt="screenshot 2016-08-22 19 04 36" src="https://cloud.githubusercontent.com/assets/5354908/17875175/2dae8c6c-689e-11e6-9a0c-dce60cbb3124.png">

Docker shuts down.

### Information

```
Diagnostic ID: E77E1BB7-FDEF-4CAF-9866-1F5C01CE8CAB
Docker for Mac: 1.12.1-rc1-beta23 (Build 11375)
macOS: Version 10.12 (Build 16A304a)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Please update to beta 25 as we have addressed many Sierra related bugs. https://download.docker.com/mac/beta/Docker.dmg 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
