### ISSUE TITLE
Start Docker Desktop when you login, not working on Catalina

### ISSUE THREAD

**Issue by sajidali** [docker/for-mac#3975]
I am only facing issue that the docker desktop does not start on login, even when I have set it up to run at login (using `Start Docker Desktop when you login`). Upon manual run (by clicking docker icon), it starts and works properly. I am just unable to get it to start automatically after login.

<img width="500" alt="Screenshot 2019-10-15 at 22 27 38" src="https://user-images.githubusercontent.com/1110072/66854809-7eede500-ef9b-11e9-8b73-91d770ce2ef4.png">

I have also tried disabling and re-enabling this checkbox and re-logged in to test, still not working.

Following option also does not work to run docker desktop at login.
<img width="359" alt="Screenshot 2019-10-15 at 22 34 25" src="https://user-images.githubusercontent.com/1110072/66855074-ff144a80-ef9b-11e9-8666-07adaef03c22.png">

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 57607F51-9561-4FFF-85FD-61F82A123790/20191015171526

### Expected behavior
Docker automatically starts up after login.

### Actual behavior
Docker not automatically starts after login.

### Information
  - macOS Version: 10.15 (19A583)

### Diagnostic logs
```
Docker for Mac: 2.1.0.3 (38240) is currently the newest version available.

```

### Steps to reproduce the behavior

Install Docker in Mojave, install docker desktop, upgrade to Catalina, enable `Start Docker Desktop when you login`

**Comment by sajidali** [comment]
from docs, this looks like it is known issue. 
`Docker does not auto-start on login even when it is enabled in whale menu > Preferences. This is related to a set of issues with Docker helper, registration, and versioning.`
ref: https://docs.docker.com/docker-for-mac/troubleshoot/

Any updates on this, is the fix for it planned in some way, or should I lose hope for a fix in near future? :)

**Comment by sajidali** [comment]
Docker for Mac: 2.1.0.3 (39773) is working fine, docker started when macos 10.15 (19A602) boots up.

**Comment by Daisuke-sama** [comment]
How did you run the docker desktop? It doesn't start for me just  "is starting" for hours

**Comment by rajiv-ranjan** [comment]
Docker desktop is not starting on my macbook too Os version 10.15.2 (19C57).
