### ISSUE TITLE
If you touch a submount point on the host the volume is unmounted in the container

### ISSUE THREAD

**Issue by macrael** [docker/for-mac#3976]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D00A45CC-810A-4813-99C7-8160321A4F86/20191016000827

### Expected behavior
It is [very](https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder) [common](https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html) [advice](https://dev.to/alex_barashkov/using-docker-for-nodejs-in-development-and-production-3cgp) to exclude a directory inside a bind-mount by mounting a volume over top of it. For instance, if you are developing a react app and you want to be able to preform live builds inside of a container, you could bind mount your repository into the dev container and then mount a named volume on top of node_modules. Now if you have modules that compile for specific architectures, you will have the right builds on each system.

Here is an invocation that should set this up correctly:

```
docker run \
  -d \
  --name code_dev
  --mount type=bind,source=.,destination/code \
  --mount type=volume,source=code_node_mods,destination=/code/node_modules \
  -w /code \
  my_ci_image \
  tail -f /dev/null
```

I would expect that volume mount to exist and contain the named volume's contents at all times while this container is running. Here's a test:

1. Run the above command in a directory that has node_modules
2. `touch node_modules/HOST.txt`
3. `docker exec code_dev touch node_modules/CONTAINER.txt`
4. `docker exec code_dev ls node_modules | grep txt`
5. `touch node_modules`
6. `docker exec code_dev ls node_modules | grep txt`

I would expect both `ls`s in the container to show the `CONTAINER.txt` file

### Actual behavior
Instead, when you run the above commands, the second `ls` in the container shows the `HOST.txt` file. 

At least on Docker for Mac, if you run `touch node_modules` on the host docker will silently unmount the named volume altogether in the container. This makes it immediately start mirroring all the contents of node_modules in the container, allowing you to ruin your build in both directions depending on what runs first. 

If you run findmnt on the container you will see that the volume mount is gone after you've touched node_modules on the host.

This is an immediate problem for me because some tools (at least gulp) touch node_modules as part of their normal operation, so I can't keep a long-running dev container around running webpack because node_modules will eventually get out of whack. 

### Information
- This problem is 100% reproducible 
- I don't know that it is a regression. I've encountered it with the following version:
MacOS: 10.14.6

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thaJeztah** [comment]
^^ @djs55 ptal

**Comment by thaJeztah** [comment]
(also, thanks for the report and clear reproduction steps!)

**Comment by LordGordonQ** [comment]
Same issue here: I just started yesterday experimenting with a node container, with docker compose, and it is driving me crazy. Here my `docker-compose.yml`:

```
version: "3"

volumes:
  node_modules:

...

  volumes:
        - /path/to/my/webapp:/webapp
        - node_modules:/webapp/node_modules/
```

As soon I start working on my source files on my Host in `/webapp` yet without _touching_ `node_modules`, the container `node_modules` is unmounted and got empty, breaking my work.

## Information
MacOS: 10.14.6

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by josh-byster** [comment]
Same here. I created an [issue](https://github.com/moby/moby/issues/40109) for the exact thing on Moby repo.  Seems to be the same as #3479.

**Comment by LordGordonQ** [comment]
Tested after Docker for Mac update. Issue is not resolved.

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by emaiax** [comment]
@LordGordonQ @josh-byster @thaJeztah @macrael have you guys found any workaround on this? I'm having the same situation running an Elixir app for development.

Using bind volumes is pretty slow on OSX for dependencies and files compilations.

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 1
  Paused: 0
  Stopped: 8
 Images: 15
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.934GiB
 Name: docker-desktop
 ID: ON7B:KAVC:6OG5:WVQV:5RSC:M6T3:ZUVK:7XP5:N4VS:PQOS:6A7F:KWPT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 58
  System Time: 2019-11-27T02:10:19.3995942Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by LordGordonQ** [comment]
@emaiax Unfortunately, no. Waiting for a fix.

**Comment by djs55** [comment]
@macrael thanks for the report and repro steps. Sorry for the delay getting back to you. It reproduces easily for me too.

If I look at the filesystem mounts inside the container:
```
/code # mount | grep code
osxfs on /code type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /code/node_modules type ext4 (rw,relatime)
```
-- the `/code` mount comes from the host via `osxfs` as expected whereas the volume comes from inside the VM `/dev/sda1` as expected.

If I `touch node_modules` -- this will inject a filesystem notify event -- and then look at the mounts again:
```
/code # mount | grep code
osxfs on /code type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
so yes indeed, one of them has disappeared as you report!

Since the only thing `touch node_modules` on the host is doing is injecting a file event in the container, the problem must be caused by the event injection. I think the event injection code doesn't check whether the path is actually a mountpoint -- perhaps these events need to be filtered out. I'll try to dig a little deeper tomorrow.

**Comment by djs55** [comment]
I've got a very early test patch if you'd like to try it. The binary isn't signed or notarized so it probably won't work on macOS Catalina (I'll have to wait for a full build to become ready) but it might work on earlier macOS versions, if you are feeling adventurous and want to experiment with it.

*However it might be buggy so I recommend backing up `Docker.app` before modifying it!*

I'm running Catalina so I can't personally test a mixture of a published notarized build and a custom binary. This means I've only tested it on completely local builds, which is a slightly different scenario to what I'm describing here.

To try the new binary:

1. Download the attached zip file: 
[osxfs.zip](https://github.com/docker/for-mac/files/3905714/osxfs.zip)
2. verify the `shasum`:
```
$ shasum osxfs.zip 
3828821ebb48a7c9f2f43c3a758bd2aa1bc10812  osxfs.zip
```
3. shut down the Desktop app
4. (for safety) take a backup of the `/Applications/Docker.app/` folder
5. unzip the `osxfs.zip` and copy the results to `/Applications/Docker.app`. It will overwrite `Contents/MacOS/com.docker.osxfs` and a few libraries in `Contents/Resources/lib`
6. restart the Desktop app

On my local system I see:
```
Dave-MBP:mounts djs$ rm -rf node_modules
Dave-MBP:mounts djs$ mkdir node_modules
Dave-MBP:mounts djs$ docker run \
>   -d \
>   --rm \
>   --name code_dev \
>   --mount type=bind,source=$(pwd),destination=/code \
>   --mount type=volume,source=code_node_mods,destination=/code/node_modules \
>   -w /code \
>   alpine \
>   tail -f /dev/null
91ad6d7e8fc159fab97253259a59725df43271cc1bef66563d5b2af15ac7fe44
Dave-MBP:mounts djs$ touch node_modules/HOST.txt
Dave-MBP:mounts djs$ docker exec code_dev touch node_modules/CONTAINER.txt
Dave-MBP:mounts djs$ docker exec code_dev ls node_modules | grep txt
CONTAINER.txt
Dave-MBP:mounts djs$ touch node_modules
Dave-MBP:mounts djs$ docker exec code_dev ls node_modules | grep txt
CONTAINER.txt
```
i.e. the in-container view remains authoritative and
```
Dave-MBP:mounts djs$ docker exec code_dev mount | grep /code
osxfs on /code type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /code/node_modules type ext4 (rw,relatime)
```
the container still has both mounts.

When a proper test build is ready I'll post the link here.

**Comment by djs55** [comment]
Here's a full Docker build with the proposed fix: https://download-stage.docker.com/mac/edge/41320/Docker.dmg . If anyone has the time to test it and provide feedback, let me know.

**Comment by LordGordonQ** [comment]
> Here's a full Docker build with the proposed fix: https://download-stage.docker.com/mac/edge/41320/Docker.dmg . If anyone has the time to test it and provide feedback, let me know.

I should be able to try it tomorrow.

**Comment by LordGordonQ** [comment]
I still have the issue. I'm running a docker-compose file. 

### Steps to reproduce
docker-compose.yaml:
```
version: "3.7"

volumes:
  node_modules:

...

services:
  webapp:

   ...

    volumes:
      - /host/full/path/webapp:/webapp:consistent
      - node_modules:/webapp/node_modules/

   ...
```

After docker-compose build & run, inside the **container**:

- `ls -lsa /webapp/node_modules` has the usual gargantuan number of directories, as expected;
- output of `mount | grep webapp` is

```
osxfs on /webapp type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /webapp/node_modules type ext4 (rw,relatime)
``` 

Then, from **host**: `touch ./webapp/some_existing_file` and `touch ./webapp/new_file` both work fine. Inside the **container** I see the `new_file` and the touched one.

Now, from **host**: `vim ./webapp/some_existing_file` (the same touched before) and save the changes.

Inside the **container**:

- `cat /webapp/some_existing_file` shows the edited file;
- `ls -lsa /webapp/node_modules` is empty;
- `mount | grep webapp` is

```
osxfs on /webapp type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
``` 

Let me know if I have to produce more details.

### Environment
```
Docker Desktop version 2.1.7.0 (41320)
Channel: edge
```

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.25.1-rc1, build d92e9bee
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Comment by LordGordonQ** [comment]
Replicated also with the following yaml:

```
version: "3.7"

volumes:
  node_modules:

...

services:
  webapp:

   ...

    volumes:
      - /host/full/path/webapp:/webapp
      - node_modules:/webapp/node_modules

   ...
```

**Comment by djs55** [comment]
@LordGordonQ thanks for the feedback. I attempted to reproduce the effect you saw but with no luck so far :( I've tried to convert your instructions into a script here: https://github.com/djs55/bug-event-delete-mountpoint -- could you let me know if the issue reproduces with that script? I added a log to the `README.md` showing the output which I think is all correct so far -- I can't get the second mountpoint to disappear :(

**Comment by josh-byster** [comment]
Just to chime in @djs55 thank you for pushing a fix. I have trouble in general reproducing most of the issues on my machine, but coworkers are running into difficulties using the same Compose file running the exact commands. This doesn’t seem like an issue where there’s always a consistent way to reproduce unfortunately, at least from my experience with the bug.

**Comment by rvolgers** [comment]
@djs55 Your build seems to work as advertised, I no longer see a nested mount immediately unmounting after I `touch` the mountpoint dir on the host side. To be honest though I feel like I should test this for longer, as I observed this originally as a random unmounting problem that occured about 0.5-4 times per day at times that did not seem to be correlated with anything, so I am not entirely convinced that I'm reproducing the root cause.

Also I can still make the unmount happen by *deleting* the mountpoint on the host, but I guess that's expected? For me personally it would be ideal if osxfs would just pretend that the mountpoint kept existing (it's kind of annoying to have mounts be so brittle), but I can understand that that would probably cause a whole lot of complications.

**Comment by LordGordonQ** [comment]
> @LordGordonQ thanks for the feedback. I attempted to reproduce the effect you saw but with no luck so far :( I've tried to convert your instructions into a script here: https://github.com/djs55/bug-event-delete-mountpoint -- could you let me know if the issue reproduces with that script? I added a log to the `README.md` showing the output which I think is all correct so far -- I can't get the second mountpoint to disappear :(

Sorry for the long delay, I was sick last week. I ran your script, it does not reproduce the issue. I looked at the script and it should have reproduced it. Here the output:

```
Building webapp
Step 1/4 : FROM alpine
latest: Pulling from library/alpine
89d9c30c1d48: Already exists
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
 ---> 965ea09ff2eb
Step 2/4 : COPY entrypoint.sh /
 ---> af0b5674fd05
Step 3/4 : RUN chmod +x /entrypoint.sh
 ---> Running in e7eefe615a6f
Removing intermediate container e7eefe615a6f
 ---> 016113100872
Step 4/4 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Running in a766060f5fc2
Removing intermediate container a766060f5fc2
 ---> 1f456b8ba946

Successfully built 1f456b8ba946
Successfully tagged compose_webapp:latest
Creating network "compose_default" with the default driver
Creating volume "compose_node_modules" with default driver
Creating compose_webapp_1 ... done
The container should have a populated /webapp/node_modules directory:
total 4
     4 drwxr-xr-x    2 root     root          4096 Dec  9 09:17 .
     0 drwxr-xr-x    6 root     root           192 Dec  9 09:17 ..
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-0
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-1
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-10
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-2
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-3
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-4
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-5
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-6
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-7
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-8
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-9
The container should show 2 mountpoints:
osxfs on /webapp type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /webapp/node_modules type ext4 (rw,relatime)
Touching some_existing_file and new_file.
The container should see the 2 new files:
total 16
-rwxr-xr-x    1 root     root            95 Dec  2 12:07 Dockerfile
-rwxr-xr-x    1 root     root           136 Dec  2 12:07 entrypoint.sh
-rw-r-----    1 root     root             0 Dec  9 09:17 new_file
drwxr-xr-x    2 root     root          4096 Dec  9 09:17 node_modules
-rw-r-----    1 root     root            17 Dec  9 09:17 some_existing_file
Modifying some_existing_file on the host.
The container should see the modification:
modified
The container should still have a populated /webapp/node_modules directory:
total 4
     4 drwxr-xr-x    2 root     root          4096 Dec  9 09:17 .
     0 drwxr-xr-x    7 root     root           224 Dec  9 09:17 ..
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-0
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-1
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-10
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-2
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-3
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-4
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-5
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-6
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-7
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-8
     0 -rw-r--r--    1 root     root             0 Dec  9 09:17 fake-node-modules-9
The container should show 2 mountpoints:
osxfs on /webapp type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/sda1 on /webapp/node_modules type ext4 (rw,relatime)
Stopping compose_webapp_1 ... done
Removing compose_webapp_1 ... done
Removing network compose_default
```

**Comment by rvolgers** [comment]
Update: unfortunately, spontaneous unmounts still seem to happen in my use case, although perhaps less often, and I cannot cause them by just touching `node_modules` anymore.

My scenario is similar to what many others have posted
* A host mount with node js source files
* Something is mounted on top of the `node_modules` directory in the project dir (i.e. on top of the host mount)
* At some random point, the `node_modules` mount disappears, and everything breaks because the container starts writing to / reading from the host directory that was masked by the mount
* The random unmount *might* be correlated with filesystem stress, but really not sure.
* In my case the `node_modules` mount is actually bind-mounted from elsewhere in the container's own filesystem, it's not an external volume or host mount.

**Comment by kzw** [comment]
This is still happening on both linux and mac host.

linux (ubuntu 20.04) Docker version 19.03.12, build 48a66213fe
mac (Darwin 19.5.) Docker version 19.03.8, build afacb8b

**Comment by thaJeztah** [comment]
@kzw So far (I think) all reports have been from users running docker for mac, which could be related to the filesystem mapping on Docker Desktop, and for which there's still an open issue in https://github.com/docker/for-mac/issues/2777 and https://github.com/docker/for-mac/issues/3479.

if you have exact steps to reproduce the issue on Linux, could you provide those steps? I tried reproducing the issue on an Ubuntu 20.04 machine with Docker 19.03.12, but didn't see this happen;

Starting from an empty situation (no `node_modules` present in local dir, no `code_node_mods` volume)

```bash
mkdir repro-3976 && cd repro-3976
```

Cleanup previous container and volume (if any)

```bash
docker rm -f code_dev
docker volume rm code_node_mods
```

Start the container

```bash
docker run \
  -dit \
  --name code_dev \
  --mount type=bind,source=$(pwd),destination=/code \
  --mount type=volume,source=code_node_mods,destination=/code/node_modules \
  -w /code \
  busybox
```

Create a file on the host inside `node_modules`, and verify it doesn't show up in the container:

```bash
touch node_modules/HOST.txt
docker exec code_dev ls node_modules | grep txt
# (empty)
```

Create a file inside the container in `node_modules` and verify it _does_ show up in the container:

```bash
docker exec code_dev touch node_modules/CONTAINER.txt
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
```

Touch the `node_modules` directory on the host, and verify nothing changed in the container:

```bash
touch node_modules
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
```

Stop, and remove the container, then start it again (this time files exist in `node_modules` on the host and in the volume)

```bash
docker rm -f code_dev
```

Start a new container

```bash
docker run \
  -dit \
  --name code_dev \
  --mount type=bind,source=$(pwd),destination=/code \
  --mount type=volume,source=code_node_mods,destination=/code/node_modules \
  -w /code \
  busybox
```

Check files in the node_modules directory inside the container to verify it still contains the file we created in the volume;

```bash
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
```

Create a file on the host inside `node_modules`, and verify it doesn't show up in the container:


```bash
touch node_modules/HOST2.txt
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
```

Create a file inside the container in `node_modules` and verify it _does_ show up in the container:

```bash
docker exec code_dev touch node_modules/CONTAINER2.txt
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
# CONTAINER2.txt
```

Touch the `node_modules` directory on the host, and verify nothing changed in the container:

```bash
touch node_modules
docker exec code_dev ls node_modules | grep txt
# CONTAINER.txt
# CONTAINER2.txt
```
