### ISSUE TITLE
Docker Multi Stage Build fails on catalina

### ISSUE THREAD

**Issue by lcrostarosa** [docker/for-mac#3979]
My Docker builds are failing on Mac OS Catalina, but succeeding on Mac OS Mojave and Linux Ubuntu. I have reduced the dockerfile to the least possible amount of docker config to see if someone else can reproduce the error.

I am working with [Appian's](https://docs.appian.com/suite/help/19.3/Installing_Appian_in_Docker_Containers.html) Docker setup (there is quite a bit of configuration needed with this project).

There are additional permission errors that keep happening, but do not have a quick way to reproduce it.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5F7741F4-DF2B-44EC-8D42-CE4F91DA7410/20191018014746

### Expected behavior
Multi Stage Build passes while running `docker-compose build`. Linux and Mojave do so fine.

### Actual behavior
Multi Stage Build fails with the following error
```
ERROR: Service 'base' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder078966315/build-files/installers: no such file or directory
```

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
    - Yes
  - Is the problem new?
    -yes
  - Did the problem appear with an update?
    -After upgrading to catalina, yesterday
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version:
    - 10.15

### Diagnostic logs

```
Docker for Mac: edge version 2.1.4.0

```

### Steps to reproduce the behavior
`DockerFile`
```
FROM centos:7 as installer-base

ENV APPIAN_USER_ID 9999

WORKDIR /tmp

# environment variables for build
ENV APPIAN_HOME /usr/local/appian/ae
ENV HOTFIX_PACKAGE *_Hotfix_Package_*.zip

RUN yum -y install unzip \
  && yum clean all \
  && rm -rf /var/cache/yum

RUN ls -lsa
#install Appian
RUN mkdir -p $APPIAN_HOME \
  && mkdir -p $APPIAN_HOME/services/data/data-server \
  && mkdir -p $APPIAN_HOME/services/data/kafka-logs

FROM centos:7

# environment variables
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV JDK_PACKAGE java-1.8.0-openjdk-devel
ENV APPIAN_HOME /usr/local/appian/ae
ENV CATALINA_HOME=${APPIAN_HOME}/tomcat/apache-tomcat
ENV PATH $JAVA_HOME/bin:$CATALINA_HOME/bin:$PATH
ENV READY_PORT 9355
ENV READY_TEXT ready

COPY --from=installer-base $APPIAN_HOME $APPIAN_HOME
COPY --from=installer-base $CATALINA_HOME $CATALINA_HOME

ENTRYPOINT [ "/usr/local/appian/ae/dockerize.sh" ]
```

  1. Create a Dockerfile with the docker code above
  2. `docker build .`
  3. Should get the error above

**Comment by StefanScherer** [comment]
@lcrostarosa have you checked Mojave and Linux with a fresh build? `docker-compose build  --no-cache` to run through the whole Dockerfile should verify that.

The stripped down Dockerfile is missing the `${APPIAN_HOME}/tomcat/apache-tomcat` folder, so it fails.

```
 ---> 94b7cd8a9e1d
Step 18/19 : COPY --from=installer-base $CATALINA_HOME $CATALINA_HOME
COPY failed: stat /var/lib/docker/overlay2/d0b86ec14ede43c902566d7ea474109259b1b93600b4bdd4d2a07967d9c27bd4/merged/usr/local/appian/ae/tomcat/apache-tomcat: no such file or directory
```

**Comment by jhabdas** [comment]
> I am working with Appian's Docker setup (there is quite a bit of configuration needed with this project).

Have you raised this issue with the Appian team? Personally I wouldn't consider installing Docker for Mac using anything but the [official installation instructions](https://docs.docker.com/docker-for-mac/install/), which suggest downloading  the Docker Desktop solution after logging into Docker Hub.
