### ISSUE TITLE
Unable to install Docker Desktop on Catalina

### ISSUE THREAD

**Issue by y-lakhdar** [docker/for-mac#3987]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 27756858-671E-470C-9894-187C4A6F67CB/20191021144857

### Expected behavior
Download the the Docker Desktop.

### Actual behavior
Getting a fatal error 
![image](https://user-images.githubusercontent.com/12199712/67216240-dbfcf700-f3f0-11e9-9ad1-e68d48d3e735.png)

### Information
  - Is it reproducible? **Yes**
  - Is the problem new? **Yes, I upgraded to Catalina and tried to install Docker. No luck since**
  - macOS Version: Catalina 10.15

### Diagnostic logs

```
Docker for Mac: version 2.1.0.3
```

### Steps to reproduce the behavior

  1. Download Docker Desktop from Docker Hub
  2. Install the .dmg file.

I still experience the issue after restarting the computer.

**Comment by kirankbee** [comment]
I am facing the same issue, any pointers?
