### ISSUE TITLE
'docker ps' Hangs

### ISSUE THREAD

**Issue by jliang87** [docker/for-mac#399]
### Information

Diagnostic ID: ED6920AF-A8BB-4D4F-B90D-198433EA9C41
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

My computer crashed after install Docker for Mac for the first time. After restarting, I can't do 'docker ps' no more.

**Comment by picrin** [comment]
duplicate of #404

**Comment by MagnusS** [comment]
Closing this in favour of #11
