### ISSUE TITLE
DNS resolution not respecting search domain - Docker for Mac

### ISSUE THREAD

**Issue by woiza** [docker/for-mac#3992]
### Expected behavior
/etc/resolv.conf in container should be identical to /etc/resolv.conf on host, except for localhost IP addresses as described in:
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/

### Actual behavior
"search" is missing.

Host:
> cat /etc/resolv.conf
search intra
nameserver 10.39.0.1

Container:
> cat /etc/resolv.conf
nameserver 10.39.0.1

macOS Version:
10.13.6

Docker for Mac: version
2.1.0.3

**Comment by djs55** [comment]
Thanks for the report.

The explanation for the current behaviour is as follows:
- On Mac and Windows we run the Docker engine inside a VM, so where the Docker engine docs refer to "host", confusingly the "host" is a Linux VM in this case
- Mac and Windows support quite complicated DNS resolution policy, supporting things like different DNS configurations per-domain used by VPN clients etc (e.g. on the Mac via `/etc/resolver` or the system configuration database)
- DNS resolvers in Linux are usually simpler and often don't support this kind of policy. The exact resolver and it's capability depends usually on the `libc` (`glibc` or `musl`) but sometimes it's builtin to the language runtime (e.g. Go) or can even be hand-written.
- We would like DNS resolution inside the container to follow the host policy as reliably as possible (regardless of `libc` or language runtime) so you can do things like access registries from internal domains associated with corporate VPNs.
- Therefore we assume the resolver in the container is very simple and we run a DNS proxy on the host which uses the host APIs to follow the host policy (including the search domains). We point the VM's `/etc/resolv.conf` (and therefore the container's `/etc/resolv.conf`) at our proxy.

So the result of this is that the `/etc/resolv.conf` in the container when using a docker `bridge` network type is the same as the `/etc/resolv.conf` in the VM but is different to the `/etc/resolv.conf` on the host but we try to apply the host's policy in the DNS proxy anyway.

Could you explain what you are trying to achieve in more detail?

**Comment by woiza** [comment]
I wrote a couple of docker images to test some applications which rely on "external" databases. A few months ago I could use something like "database = dev-postgres123". Now the hostname "dev-postgres123" cannot be resolved, however "dev-postgres123.intra" can be resolved...
Another options seams to be "docker run --dns-search="intra". Either way, I have to either rewrite our images or bash scripts (docker run).
When did you change this? I am rather confident that previous Docker for MacOS versions behaved differently and as described in the above linked documentation, i.e. having "search intra" in etc/resolv.conf.
