### ISSUE TITLE
error in opening docker

### ISSUE THREAD

**Issue by sahand12** [docker/for-mac#4]
### Expected behavior
It happened right after installation, it should open up the app but instead it opened a fatal error
window which said : 
"Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox       versions prior to v4.3.30
VirtualBox v4.3.28 is currently installed.
Please upgrade or uninstall Virtualbox."

I uninstalled the virtualbox but it didn't make any difference

### Information

Diagnostic ID: CF8ED858-FC2A-42E5-A548-C2C622BA2863
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/sahand/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/CF8ED858-FC2A-42E5-A548-C2C622BA2863/20160729-132918/qemu-img-check.stdout 2> /tmp/CF8ED858-FC2A-42E5-A548-C2C622BA2863/20160729-132918/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/sahand/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/sahand/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/sahand/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/sahand/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/sahand/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Can you please fill in the "Expected behavior", "Actual behavior" and "Steps to reproduce" fields. Closing until we get more information.

**Comment by sahand12** [comment]
I updated the information @samoht

**Comment by PierluigiRiti** [comment]
hello, I got the same error, i just install docker on my MacOS, and try to check and diagnostic

**Comment by dsheets** [comment]
How did you uninstall VirtualBox?

```sh
kextstat | grep -i virtualbox
```

should return nothing.

**Comment by rajegit** [comment]
`kextstat | grep -i virtualbox    `
If this has no return , docker should work , if yes than 

`rm -R * /Library/Application Support/VirtualBox`
Delete the .kext drivers , changes are that some of the drivers are loaded and you cannot unload them . Typicallay "sudo kextunload -b org.virtualbox.kext.VBoxNetDrv" should work , but even after deleting the folder , you are sill getting drivers listed by "kextstat | grep -i virtualbox " restart your machine.

**Comment by sahand12** [comment]
Thank you @rajegit ! You were right, I did not uninstall virtualBox properly; but after taking care of that everything works great, thanks man.

**Comment by Jaggle** [comment]
@rajeget this helped ,but now docker is stucked when opening it, with a whale icon in menu bar

**Comment by Jaggle** [comment]
fine, uninstall it and then install the lastest version.
