### ISSUE TITLE
buildctl not available

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4009]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20191030145042

### Expected behavior
`buildctl` can be run to [view size of mounts](https://github.com/moby/buildkit/issues/589#issuecomment-416403274)

### Actual behavior
`buildctl` is not available

### Information
  - macOS Version: 10.14.6

### Diagnostic logs
Not available in current version of Docker for Mac

### Steps to reproduce the behavior
1. Install Docker for Mac
2. Build an image using `buildkit` and `RUN --mount`
3. Try to [inspect the size using `buildctl`](https://github.com/moby/buildkit/issues/589#issuecomment-416403274)

**Comment by daveisfera** [comment]
It's still not available and since `buildkit` is being pushed as the future of docker, it feels like this should be a requirement

**Comment by daveisfera** [comment]
This is still an issue

**Comment by thaJeztah** [comment]
BuildKit is actually embedded in docker; if you set the `DOCKER_BUILDKIT=1` environment variable, `docker build` will be using the embedded buildkit builder.

`buildctl` is used when running BuildKit stand-alone 

Does that resolve your problem?

**Comment by daveisfera** [comment]
Yes, the [`docker system df -v` command](https://github.com/moby/buildkit/issues/589#issuecomment-416403274) provides the info that I was looking for
