### ISSUE TITLE
CPU 130% with no containers running

### ISSUE THREAD

**Issue by westandskif** [docker/for-mac#4011]
**Environment:**
MacBook Pro (Retina, 15-inch, Late 2013)
2.3 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3

OS X: 10.15.1 (19B88)
Docker desktop 2.1.0.4 (39773)
Engine: 19.03.4
Compose: 1.24.1
Kubernetes: v1.14.7
Notary: 0.6.1
Credential Helper: 0.6.3
Machine: 0.16.2
https://monosnap.com/file/eJLBr7QmEGdRMGRA3uCnRzMAb5pTTl

Config:
`{
  "debug" : true,
  "experimental" : false,
  "features" : {
    "buildkit" : true
  }
}`

Diagnostic ID: 7F34AE04-E04D-4C96-A6ED-E39C3FB9B1F8/20191031070559

Having no containers running, Docker is constantly loading CPU.
Please let me know what other info is needed.

**Comment by jhogervorst** [comment]
Same machine, same problem!

MacBook Pro (Retina, 15-inch, Early 2013)
2,7 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3

macOS: 10.15.1 (19B88)
Docker Desktop: 2.1.0.4 (39773)
Channel: stable
Engine: 19.03.4
Compose: 1.24.1
Kubernetes: v1.14.7
Notary: 0.6.1
Credential Helper: 0.6.3
Machine: 0.16.2

Diagnostics ID: AE5FE102-25E7-4211-BD72-4B912170BF73/20191101092805

**Comment by acdha** [comment]
Same issue on an iMac:

Diagnostic ID: 9DD81722-B609-495D-BEAF-260964764687/20191101201205

**Comment by fflo** [comment]
Did you enable Kubernetes? Or have you enabled Kubernetes in the past on the system affected?

**Comment by acdha** [comment]
I had previously enabled Kubernetes but disabling it did not resolve the problem. I was testing whether a reset did.

**Comment by fflo** [comment]
The high load with no containers running issue occurred the first time after enabling Kubernetes on my Docker Desktop setup. It seems that disabling Kubernetes does not restore the original behavior running Docker Desktop Mac without having Kubernetes enabled.

**Comment by westandskif** [comment]
I haven't ever enabled Kubernetes
