### ISSUE TITLE
Docker application failing to start

### ISSUE THREAD

**Issue by vivekkodira1** [docker/for-mac#402]
### Expected behavior
Docker application should start

### Actual behavior
Docker application does not start

### Information
Diagnostic ID: F7427C3F-5859-4184-94CF-21A364CABA1D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
NA

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in F7427C3F-5859-4184-94CF-21A364CABA1D/20160809-111413.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug  8 11:37:41 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: VM: 2016-08-08 06:07:41 +0000 UTC daemon.info vsudd: 124 Done. read: 96 written: 4249
Aug  8 11:37:49 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=6122602e-37ed-4d3d-b0fb-7ea4a4c27a81,path=/Users/vivekkodira/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/vivekkodira/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Aug  8 11:37:49 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug  8 11:37:49 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: Interface will have uuid 6122602e-37ed-4d3d-b0fb-7ea4a4c27a81
Aug  8 11:37:49 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: Connection established with MAC=c0:ff:ee:c0:ff:ee and MTU 1500
Aug  8 11:37:49 vivek Docker[com.docker.driver.amd64-linux][1476] <Notice>: virtio-9p: initialising path=/Users/vivekkodira/Library/Containers/com.docker.docker/Data/s40,tag=db
```
