### ISSUE TITLE
Docker ID

### ISSUE THREAD

**Issue by brumcmil** [docker/for-mac#4026]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
10.15.1

### Diagnostic logs

```
Docker for Mac: version...

2.1.0.4 (39773)

```

### Steps to reproduce the behavior

  1. ... Docker automatically starts with my Mac
  2. ...goto Sign in / Create Docker ID
  3. ...enter my Docker ID and password
  4. ...click sign in
  5. ...get message 'incorrect authentication credentials'
  6. ...I go to the Docker web site and login with the exact same credentials

**Comment by eleofil** [comment]
I have exactly same issue.
macOS 10.15.1 (19B88)
Docker 
2.1.0.4 (39773)
engine version 19.03.4, build 9013bf5

**Comment by eleofil** [comment]
Preferences>Reset>Reset to factory defaults and Restart Mac, fixed the issue for me.
