### ISSUE TITLE
Missing docker-machine binary in Docker Desktop Community 2.1.5.0 release

### ISSUE THREAD

**Issue by przemyslaw-szurmak** [docker/for-mac#4027]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: custom

### Expected behavior
`Docker-machine` binary will be attached into Docker release.

### Actual behavior
`Docker-machine` is not inside installation package.

### Information
**Reproduction rate**: 100%
**Is problem new**: seems like, with previous releases `docker-machine` was included, couldn't find information that it won't be there anymore.
**Did the problem appear with an update**: Yes
**macOS version**: 10.15

### Diagnostic logs
Well, as it's even before installing I'm posting result of `ls` command in `Docker.dmg` mounted image.

```
przemexus@PRSR-MBP bin % pwd
/Volumes/Docker/Docker.app/Contents/Resources/bin
przemexus@PRSR-MBP bin % ls -la
total 338080
drwxr-xr-x  10 przemexus  staff       340  4 lis 12:25 .
drwxr-xr-x  23 przemexus  staff       782  4 lis 12:25 ..
-rwxr-xr-x   1 przemexus  staff   4350096  4 lis 12:25 com.docker.hyperkit
-rwxr-xr-x   1 przemexus  staff  20509968  4 lis 12:25 com.docker.vpnkit
-rwxr-xr-x   1 przemexus  staff  61032480  4 lis 12:25 docker
-rwxr-xr-x   1 przemexus  staff   9735472  4 lis 12:25 docker-compose
-rwxr-xr-x   1 przemexus  staff  15948336  4 lis 12:25 docker-credential-desktop
-rwxr-xr-x   1 przemexus  staff   2550544  4 lis 12:25 docker-credential-osxkeychain
-rwxr-xr-x   1 przemexus  staff  49231680  4 lis 12:25 kubectl
-rwxr-xr-x   1 przemexus  staff   9720096  4 lis 12:25 notary

```

### Steps to reproduce the behavior

  1. Download latest (4th of Nov) release of Edge Docker -> Docker Desktop Community 2.1.5.0
  2. Mount image in mac
  3. Either install on your computer or just browse through content of mounted image
  2. Check if `docker-machine` is present where it was in previous releases -> `Docker.app/Contents/Resources/bin/docker-machine`

Side note -> `docker-compose` is still there

**Comment by stephen-turner** [comment]
Yes, you're right, we removed it from the Docker Desktop distribution in 2.1.4.0. It's still available for download separately, but we felt that it was unlikely that people would want to use both Desktop and Machine, so we didn't think it was worth bundling them together any more, and we'd rather reduce the download size. Did you have a reason why you'd want them bundled together?

**Comment by przemyslaw-szurmak** [comment]
hey @stephen-turner, thanks for quick reply.

So i use `docker-machine` for controlling my remote docker engines -> most of time I do set env variables for remote engine through `eval $(docker-machine env someRemoteDocker)`.

But you're right, I can just install it separately although I was confused by `docker-machine` docs that still mentions it as bundled together with Docker Desktop and at the same time, not mention in release notes of `docker-machine` removal.

**Comment by stephen-turner** [comment]
Oh, we should fix the docker machine docs then. Thanks. cc @usha-mandya

**Comment by stephen-turner** [comment]
Usha has reminded me of the reason why it's not in the docs yet. The change has only been made on the Edge channel at the moment, which is experimental, whereas the docs document the Stable channel. When the change reaches Stable, the docs will change. So I'll close this ticket now. Thanks for raising it.

**Comment by przemyslaw-szurmak** [comment]
If you could please add note to Release notes too. Thanks !

**Comment by stephen-turner** [comment]
Ah yes, I'll reopen this ticket.

**Comment by usha-mandya** [comment]
The note on Docker Machine has been added to the Edge release notes:

- https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2140
- https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2140

**Comment by usha-mandya** [comment]
I'll close this ticket. Thanks.
