### ISSUE TITLE
Not able to install Docker for Mac C93672BB-99BA-4D34-87BE-8B4DA090B12E/20191113104302

### ISSUE THREAD

**Issue by deep-patel** [docker/for-mac#4040]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C93672BB-99BA-4D34-87BE-8B4DA090B12E/20191113104302

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
