### ISSUE TITLE
Docker.VmnetdError error 1 on Mac OS Catalina version 10.15

### ISSUE THREAD

**Issue by money11maier** [docker/for-mac#4045]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 45C07A4F-48AC-432A-B8CD-0E398977F9F2/20191114184043

### Information

  - macOS Version: Catalina 10.15

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Download docker.dmg
  2. Install Docker
  3. Try to open Docker
  4. Receive error (Docker.VmnetdError error 1)

**Comment by bobobox** [comment]
I had this happening when accidentally launching Docker from the mounted disk image. Copied to local disk and it ran without issue.
