### ISSUE TITLE
Docker For Mac - Hyperkit VM issue after changing memory allocation

### ISSUE THREAD

**Issue by cscheib** [docker/for-mac#4046]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A - diagnostics wouldn't complete

### Expected behavior
Docker for Mac starts VM successfully

### Actual behavior
Docker for Mac VM startup sits and spins forever

### Information

  - macOS Version: 10.15.1 Catalina
  - reproducible: yes, steps at bottom of issue
  - the issue is new, I have not experienced this on my other Catalina/Docker install 
  - this laptop is brand new (13" MacBook Pro, 2019, 13", 4 TB3 ports), so I don't have any historical experience with this particular hardware

When diagnosing this, I connected `screen` to the docker tty (~/Library/Containers/com.docker.docker/Data/vms/0/tty)

While connected to the console, I observed that the Hyperkit VM appeared to be stuck at a boot menu of some sort.  I was able to select the "Continue" option, which seemingly resolved my issues.  Subsequent reboots of the Hyperkit VM were successful and did not stall on this boot menu.

Here is a screenshot of the terminal screen, from my terminal's scrollback buffer:
![image](https://user-images.githubusercontent.com/5832925/68915304-6a824100-072f-11ea-89c0-b9cc1a56cc44.png)

### Diagnostic logs

```
Docker for Mac: 2.1.0.4/stable

```

### Steps to reproduce the behavior

* on a clean system, install docker desktop
* start docker desktop and allow VM to initialize
* open preferences > advanced, set memory allocation to 4.0 GB (default is 2.0 GB)
* apply changes and wait for VM to restart

### Temporary Workaround/Resolution
Connect to VM tty device using a terminal emulator, select "Continue" option at menu

**Comment by michaelmccaskill** [comment]
👍 This is happening to me as well. I had to reset Docker to factory default and only then did the screen method work.
