### ISSUE TITLE
docker command not found in Jupyter notebook

### ISSUE THREAD

**Issue by eleofil** [docker/for-mac#4048]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 202303AF-45DD-4D3E-BF71-CCFEF6668931/20191115111824

### Expected behavior

In Jupyter notebook launched from JupyterLab
run a simulation file from docker container with
!docker run --rm -it -v $(pwd):/[my path]

### Actual behavior
/bin/sh: docker: command not found

### Information

  - macOS Version: 10.15.1 (19B88)
The issue is only in Jupyter notebook launch from JupyterLab (it is working in Jupyter notebook launched from Terminal)

### Diagnostic logs

Docker for Mac: version 2.1.0.4 (39773)
engine version 19.03.4, build 9013bf5
```

Steps to reproduce the behavior

1. In Jupyter notebook (from Jupyterlab) cell run:
!docker run --rm -it -v $(pwd):/[my path]

2. Output:
/bin/sh: docker: command not found

In Terminal: docker run --rm -it -v $(pwd):/[my path]  , it works!

**Comment by mdrmuhaimin** [comment]
I have similar issues as well. Any update on this?

**Comment by eleofil** [comment]
For me it turned out that the issue is using only when using JupyterLab, launching only Jupyter Notebook all is working.
