### ISSUE TITLE
ext4 filesystem isn't unmounted cleanly

### ISSUE THREAD

**Issue by vasi** [docker/for-mac#405]
### Expected behavior

When I quit Docker, the ext4 filesystem in Docker.qcow should have the "needs recovery" flag off.

### Actual behavior

The "needs recovery" flag remains on.

### Information

Diagnostic ID: 7A8563A7-8744-4714-B3AA-54A449FC68A4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Run Docker.app
2. Quit Docker.app
3. Run qemu, attaching it to the disk ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
4. Run `fsck.ext4` on the filesystem, it will be something like /dev/vda2.
5. It reports that it has to recover the filesystem.

### Notes

It looks like it's failing to unmount because some daemon is still running? I've attached the only screenshot I was able to get of the shutdown process. I'd appreciate any advice on how to do better diagnosis.

![dying2](https://cloud.githubusercontent.com/assets/3305/17893264/14755198-6913-11e6-988f-d8fa3486b602.png)

**Comment by vasi** [comment]
It looks like some services are never stopped, eg: docker-containerd. Kinda hard to see exactly which ones, I still don't have the hang of OpenRC.

**Comment by justincormack** [comment]
I think this was fixed a while back - can you check if it seems fixed now?

**Comment by vasi** [comment]
Would you like me to check on the stable or beta channel?

**Comment by justincormack** [comment]
beta channel. I can't remember if the fix was added to stable yet, it will definitely be in the next stable.

**Comment by justincormack** [comment]
@vasi should be in both channels now.

**Comment by vasi** [comment]
Ok, I'll try to get my qcow2 tools back into a sane state so I can actually check this :)

**Comment by dsheets** [comment]
Please re-open this issue if you still experience this problem. Thanks for using Docker for Mac!
