### ISSUE TITLE
docker version failed

### ISSUE THREAD

**Issue by souadmaniani** [docker/for-mac#4050]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by souadmaniani** [comment]
Error response from daemon: Bad response from Docker engine
and I can't reset  or make changes on docker because I should enter an administrator's password

**Comment by ulrich** [comment]
We need to enter on time the admin password for installing Docker Desktop.
