### ISSUE TITLE
Unable to launch docker in Mac

### ISSUE THREAD

**Issue by raunkeith** [docker/for-mac#4055]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by raunkeith** [comment]
Diagnostic ID

11119612-A573-4682-9A64-BDD654398AC3/20191120034544

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
