### ISSUE TITLE
crashing docker on mac

### ISSUE THREAD

**Issue by srinivasinf** [docker/for-mac#4056]
[20191120064040.zip](https://github.com/docker/for-mac/files/3867677/20191120064040.zip)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
