### ISSUE TITLE
Docker on Mac is not working

### ISSUE THREAD

**Issue by swiegandgi** [docker/for-mac#4057]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:536AA994-340E-4375-8F08-A580B21D9873/20191120094307

### Information

  - macOS Version:10.14.6

Docker for Mac: version...

Latest version > download from today

By opening docker it gets directly an "Fatal error"
The operation could‘t be completed. (DockerVmnetdError error1.)

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
