### ISSUE TITLE
Images wont start

### ISSUE THREAD

**Issue by ErikTech** [docker/for-mac#406]
### Information

Diagnostic ID: 3CBDB40A-A339-4123-969D-DAEA95F66FD6
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A304a)
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A304a)
logs: /tmp/3CBDB40A-A339-4123-969D-DAEA95F66FD6/20160823-154855.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

**Comment by mchiang0610** [comment]
Since this is on Sierra, we have beta 25 to try and address most of these issues: https://download.docker.com/mac/beta/Docker.dmg

We will move it to the stable channel soon. Please help test. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
