### ISSUE TITLE
docker desktop does not start after update to 19.03.5 from 19.03.4

### ISSUE THREAD

**Issue by harsimranmaan** [docker/for-mac#4061]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2FE7BF9-A7CF-4EA1-B857-EA6D1EC2F5B6/20191120212203

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 19.03.5

```

### Steps to reproduce the behavior

  1. ...
  2. ...

Same #4055, #4056, #4057, #4059

**Comment by oubiwann** [comment]
I'm seeing this same behaviour; every time I start up Docker I get prompted for the update, and every time it just re-downloads 19.03.5, quits, and then doesn't restart. This time, I'm clicking "Skip This Version" ...

**Comment by oubiwann** [comment]
Needing to get Docker running on my laptop, I gave 19.03.01 a try again tonight, and it's working. Not sure why? Or may better: not sure why it didn't work 2 weeks ago?

I'm going to wait until all the linked tickets have been resolved before I try updating Docker again ...
