### ISSUE TITLE
Docker desktop stuck at `Docker Desktop is starting`

### ISSUE THREAD

**Issue by amoghjagadale** [docker/for-mac#4062]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D5AF78B9-9CDD-43BA-8576-AC2B3A22AE89/20191121134859

### Expected behavior
Docker desktop starts normally like it was doing before this problem.

### Actual behavior
Stuck in the forever loop of `Docker Desktop is starting`
### Information

  - macOS Version: 10.14.6(18G1012)

### Additional information
Docker desktop was running fine before, couple of days back after host machine restart, it started showing this behaviour. I had 2.1.0.4 installed when it started this behaviour. As there was update available just to see if the update fixes the issue, I updated docker desktop  to 2.1.0.5, but no success. Same problem.

### Steps to reproduce the behavior

  1. Start Docker Desktop

**Comment by jrmacks** [comment]
I have this same issue on macOS 10.15.1

**Comment by fancyweb** [comment]
Just updated Docker to the latest version and I now have the same problem.
ID `208359E2-6EF7-4DB3-B1B0-E632D7B4D0E9/20191125091654`

**Comment by bric3** [comment]
You may want to update to the docker edge, this . could be the same issue as this https://github.com/docker/for-mac/issues/2655

**Comment by fancyweb** [comment]
For the record, the only way I fixed it was to uninstall Docker stable and reinstall the edge version.

**Comment by jrmacks** [comment]
FWIW SentinelOne was the cause of my issue. I worked with my security team to add an exclusion for docker and it went away.

**Comment by ryanissamson** [comment]
Edge version causes other issues for me. I gotta stop updating right away.

**Comment by amoghjagadale** [comment]
Thank you all and especially @bric3, for the link to [thread](https://github.com/docker/for-mac/issues/2655#issuecomment-534072309) 👍 
For others who are still facing this issue, here is the workaround in short.

### WORKAROUND INSTRUCTIONS:
1. Stop docker desktop.
2. Start docker.
3. **Very Important**: Wait for 1-2 Minuets (Otherwise workaround doesn't work)
4. Open terminal and run
```
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
```

> There should be some strange messages and cursor should be jumping like crazy if you followed everything correctly. if not, please read **RESET INSTRUCTIONS** below.
5. You can move cursor up/down with keys and make some text appear on the screen. This will show the boot options of LinuxKit.
6. Select `Continue` from list and press enter.
> VM will boot in next couple of minutes and docker desktop will start running. 🎆 

#### REST INSTRUCTIONS
1. Quit Docker desktop from status bar.
2. run `control + c` in the terminal.
3. run `reset` command in the terminal. (even if screen is blank don't worry, just type blindly and enter.) Do it couple of time if necessary.
4. Try **WORKAROUND INSTRUCTIONS** again from start.
