### ISSUE TITLE
Cannot modify preferences (edge)

### ISSUE THREAD

**Issue by seripap** [docker/for-mac#4063]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F2D01BEE-F974-469B-88C7-29D5994E8282/20191121201236

### Expected behavior

Ability to modify preferences

### Actual behavior

When attempting to edit preferences, dock is stuck in an infinity load screen. This could partially be because `kubernetes` is stuck on `starting...`, however, k8s shouldn't have a side-effect on modifying docker permissions.

<img width="1044" alt="Screen Shot 2019-11-21 at 3 10 29 PM" src="https://user-images.githubusercontent.com/683200/69373172-3a77f800-0c71-11ea-8364-34a16687dbc0.png">

### Information
  - macOS Version: Catalina (10.15.1)

### Diagnostic logs
(not sure what's needed here, can't find the Diagnose & Feedback output)

```
Docker for Mac: 2.1.6.0
{
  "id": "F2D01BEE-F974-469B-88C7-29D5994E8282",
  "date": "2019-11-21 20:12:36.59447 +0000 UTC",
  "os": "macOS 10.15.1",
  "os_label": "osx/10.15.x",
  "app_version": "2.1.6.0",
  "app_channel": "edge",
  "engine_version": "19.03.5",
  "compose_version": "1.25.0-rc4",
  "kubernetes_version": "v1.15.5",
  "credhelper_version": "0.6.3",
  "notary_version": "0.6.1",
  "vpnkit_version": "ea9dbeaf887f5dad8391f4a34d127501fb6bbf64",
  "hyperkit_version": "v0.20190802-4-g97f091"
}
```

### Steps to reproduce the behavior
1. Just edit docker settings

**Comment by jackharbinger** [comment]
Same issue here on Mojave 10.14.6. Kubernetes also stuck on starting, but never manages to run.

**Comment by seripap** [comment]
Just updating, problem still exists on 2.1.7.0 (41561)

**Comment by sebastien-A256** [comment]
Same problem here, Mac OS 10.15.3, Docker Desktop 2.2.0.3.
Until this is fixed this seem possible to update the preferences by updating the 
`~/Library/Group/Containers/group.com.docker/settings.json` file and by rebooting docker Desktop.

**Comment by seripap** [comment]
Still an issue via 2.3.0.1 (44875)

**Comment by tekumara** [comment]
Preferences will be stuck in the loading state while docker and Kubernetes are starting.

The root cause for me is #4624. 

So I disabled Kubernetes:
```
sed -i '' 's/kubernetesEnabled" : true/kubernetesEnabled" : false/' ~/Library/Group\ Containers/group.com.docker/settings.json
```
and then restarted and the preferences window is no longer stuck loading.

**Comment by seripap** [comment]
Thanks @tekumara, manually disabling kubernetes that was previously enabled from the docker CP fixes the problem.

**Comment by seripap** [comment]
See this for a fix: https://github.com/docker/for-mac/issues/4063#issuecomment-647075562
