### ISSUE TITLE
Docker using 92% cpu and crashing several times a day

### ISSUE THREAD

**Issue by KyeLani** [docker/for-mac#4068]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 8FE4BE54-49C6-439E-B02D-909D75EA1305/20191124171248

### Expected behavior
able to use docker for several hours
### Actual behavior
not able to use docker for several hours
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ... run a docker container for about an hour
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
