### ISSUE TITLE
Start daemon on macOS system boot

### ISSUE THREAD

**Issue by dachev** [docker/for-mac#4069]
Currently, the daemon is launched on user login which means that docker services are not available until a GUI session is established. This tight UI coupling is counter-intuitive, unnecessary, and limiting.

**Comment by dachev** [comment]
ref: https://github.com/moby/moby/issues/40239

**Comment by dachev** [comment]
smooth...

**Comment by harrv** [comment]
It's sad that a bot can decide that an issue can be closed when the devs choose to ignore it. This particular issue has been the most bothersome thing about Docker on the Mac -- for years. I have  never had any other problem with it but this, and dachev is right. It's limiting and seems unnecessary. It prevents me from being able to run an always-on service in Docker reliably. And as far as I've seen, it isn't a problem that Docker has on any other platform.
