### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [docker/for-mac#4073]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by UniBen** [comment]
You expect others to help you but can't even be bothered doing the issue template or an actual title. Issue should be closed.
