### ISSUE TITLE
com.docker.supervisor process has used cpu 300%

### ISSUE THREAD

**Issue by zjrstar** [docker/for-mac#4076]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:B1E128CB-9320-4988-A741-B456CCE85711/20191127065251
### Expected behavior

The process should not use cpu for a large load 

### Actual behavior

com.docker.supervisor process has used cpu 300%

### Information

  - macOS Version: 10.15.1 (19B88)

### Diagnostic logs

```
Docker for Mac: version...  2.1.6.0(40807)

```

### Steps to reproduce the behavior

  1. ... start docker desktop
  2. ... watch active monitor

**Comment by cyntl3r** [comment]
Yea, I have the same issue with Docker Desktop for Mac.
MacBook is overheating every time after run any containers.

macOS Catalina 10.15 (19A602) here.

**Comment by m8rge** [comment]
I think this is duplicate of https://github.com/docker/for-mac/issues/4064
