### ISSUE TITLE
Docker does not start on Mac

### ISSUE THREAD

**Issue by alexsimplex** [docker/for-mac#4077]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kornys** [comment]
I have same issue. Docker does not start and I'm not able to generate diagnose.

**Comment by aknapp112** [comment]
+1, had to switch to the Edge channel to get it to work on my mac.  Pls2fix

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
