### ISSUE TITLE
Docker Failed to Start on Mac

### ISSUE THREAD

**Issue by waseemahmad** [docker/for-mac#4079]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 59B3375A-4165-4DBA-BCE6-6918806004CB/20191128044208

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
