### ISSUE TITLE
Failure to install downloaded update

### ISSUE THREAD

**Issue by dheerajchand** [docker/for-mac#408]
### Steps to reproduce

1. Select option to download update and install
### Expected behavior

Download update, extract, install

### Actual behavior

All steps work till install, which fails
### Information

```
Diagnostic ID: 3DBDE51C-28A2-4A17-9AE8-436D40D1C684
Docker for Mac: 1.12.1-beta24 (Build 11508)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/dheerajchand/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
Sierra problems are being address with beta 25: https://download.docker.com/mac/beta/Docker.dmg 

We will release stable builds for Sierra once we validate bug fixes. 

Thanks!

**Comment by dheerajchand** [comment]
Except they’re not. Please see attached screenshot.

**Comment by mchiang0610** [comment]
@dheerajchand Thanks, I'm not seeing the attached screenshot. Is it the same problems that you are seeing?

**Comment by dheerajchand** [comment]
Hmm, looks like attachments from reply by email don't work! Here we go, the same symptoms of failure, attached.

<img width="1440" alt="screen shot 2016-09-12 at 10 44 14 pm" src="https://cloud.githubusercontent.com/assets/482844/18461037/d3847392-793b-11e6-9908-e1db401d6b5a.png">
<img width="1440" alt="screen shot 2016-09-12 at 10 53 20 pm" src="https://cloud.githubusercontent.com/assets/482844/18461038/d39b35be-793b-11e6-8016-094e987a4088.png">

Docker is still not able to run, although the installation of the update will complete

**Comment by mchiang0610** [comment]
Hi @dheerajchand It looks like it's not using Docker for Mac. It's using docker-machine that was previously scripted. Once the script is removed, it should work! 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
