### ISSUE TITLE
Unable to Install Docker Desktop on MacOS

### ISSUE THREAD

**Issue by benjaminfoden** [docker/for-mac#4083]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FBA3D8E8-C8AF-4D56-8751-F17ADB93FBF6/20191129155937

### Expected behavior
I am able to install Docker Desktop for Mac

### Actual behavior
I am unable to install Docker Desktop for Mac

### Information
  - macOS Version: 10.15.1 
The problem is reproducible.
Since owning this machine (past 3 months) I have been unable to successfully install Docker Desktop for Mac on my device (13" 2019 MBP)

### Diagnostic logs
time="2019-11-29T15:59:37Z" level=warning msg="[ --namespace docker get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: fork/exec : no such file or directory" type=kubernetes
time="2019-11-29T15:59:37Z" level=warning msg="[ --namespace kube-system get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: fork/exec : no such file or directory" type=kubernetes
time="2019-11-29T15:59:37Z" level=info msg="Start gathering list of 71 elements (timeout=10m0s)" type=list
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sw_vers -productVersion]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sw_vers -buildVersion]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [uname -r]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sysctl kern.boottime]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sysctl hw.memsize]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [vm_stat]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sysctl machdep.cpu]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [uname -a]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [ps uax]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [dmesg]" type=cmd
time="2019-11-29T15:59:37Z" level=warning msg="[dmesg] exit status 1" type=cmd
time="2019-11-29T15:59:37Z" level=warning msg="[dmesg]: Unable to obtain kernel buffer: Operation not permitted\nusage: sudo dmesg\n" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [id]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [sysctl -a]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [mount]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [df -h]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [launchctl print-disabled system]" type=cmd
time="2019-11-29T15:59:37Z" level=info msg="Executing: [system_profiler SPHardwareDataType]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [ifconfig -a]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [netstat -ln]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [netstat -mm]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [netstat -nr]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2019-11-29T15:59:38Z" level=info msg="Gathering: /etc/hosts" type=file
time="2019-11-29T15:59:38Z" level=info msg="Executing: [scutil --dns]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [scutil --nc list]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [scutil --proxy list]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="Executing: [system_profiler SPFirewallDataType]" type=cmd
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/version: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/info: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/containers/json?all=1: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/nodes: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/services: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2019-11-29T15:59:38Z" level=warning msg="Get http://localhost//v1.24/networks: dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2019-11-29T15:59:38Z" level=info msg="Executing: [/bin/sh -c docker network inspect $(docker network ls -q)]" type=cmd
time="2019-11-29T15:59:38Z" level=warning msg="[/bin/sh -c docker network inspect $(docker network ls -q)] exit status 127" type=cmd
time="2019-11-29T15:59:38Z" level=warning msg="[/bin/sh -c docker network inspect $(docker network ls -q)]: /bin/sh: docker: command not found\n/bin/sh: docker: command not found\n" type=cmd
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describepods" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describedeployments" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describepods" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="kubectl not found. Ignoring gatherer:describedeployments" type=kubectl
time="2019-11-29T15:59:38Z" level=warning msg="Failed to Dial vpnkit.diag.sock: dial unix vpnkit.diag.sock: connect: no such file or directory" type=vpnkit
time="2019-11-29T15:59:38Z" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]: NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]: lsof: no process ID specified\nlsof 4.91\n latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/\n latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ\n latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man\n usage: [-?abhlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[cgG]]\n [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+|-M] [-o [o]] [-p s]\n [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]\nUse the ``-h'' option to get more help information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]: lsof: no process ID specified\nlsof 4.91\n latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/\n latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ\n latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man\n usage: [-?abhlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[cgG]]\n [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+|-M] [-o [o]] [-p s]\n [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]\nUse the ``-h'' option to get more help information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]: lsof: no process ID specified\nlsof 4.91\n latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/\n latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ\n latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man\n usage: [-?abhlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[cgG]]\n [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+|-M] [-o [o]] [-p s]\n [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]\nUse the ``-h'' option to get more help information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]: lsof: no process ID specified\nlsof 4.91\n latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/\n latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ\n latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man\n usage: [-?abhlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[cgG]]\n [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+|-M] [-o [o]] [-p s]\n [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]\nUse the ``-h'' option to get more help information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]: lsof: no process ID specified\nlsof 4.91\n latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/\n latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ\n latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man\n usage: [-?abhlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[cgG]]\n [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+|-M] [-o [o]] [-p s]\n [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]\nUse the ``-h'' option to get more help information.\n" type=cmd
time="2019-11-29T15:59:53Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)]" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)] exit status 1" type=cmd
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:version" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:configget-contexts" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:configcurrent-context" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:getnodes" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:getnamespaces" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:describenodes" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:describepods" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:cluster-infodump" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:describeservices" type=kubectl
time="2019-11-29T15:59:53Z" level=warning msg="kubectl not found. Ignoring gatherer:describestorageclass,pv,pvc" type=kubectl
time="2019-11-29T15:59:53Z" level=info msg="Skipping empty file: /Users/benjaminfoden/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2019-11-29T15:59:53Z" level=info msg="Gathering: /Users/benjaminfoden/Library/Group Containers/group.com.docker/already-enabled-features.json" type=file
time="2019-11-29T15:59:53Z" level=warning msg="/Users/benjaminfoden/Library/Group Containers/group.com.docker/dhcp.json not included" type=file
time="2019-11-29T15:59:53Z" level=info msg="Gathering: /Users/benjaminfoden/Library/Group Containers/group.com.docker/features.json" type=file
time="2019-11-29T15:59:53Z" level=warning msg="/Users/benjaminfoden/Library/Group Containers/group.com.docker/http_proxy.json not included" type=file
time="2019-11-29T15:59:53Z" level=info msg="Gathering: /Users/benjaminfoden/Library/Group Containers/group.com.docker/settings.json" type=file
time="2019-11-29T15:59:53Z" level=warning msg="/Users/benjaminfoden/Library/Preferences/group.com.docker.plist not included" type=file
time="2019-11-29T15:59:53Z" level=warning msg="exit status 1" type=directorylist
time="2019-11-29T15:59:53Z" level=info msg="Gathering: /Users/benjaminfoden/.docker/config.json" type=redacted-json
time="2019-11-29T15:59:53Z" level=info msg="Gathering: /Users/benjaminfoden/.docker/daemon.json" type=redacted-json
time="2019-11-29T15:59:53Z" level=info msg="Getting Linux Diagnostics via a virtio socket: hyperkit:vms/0:62374" type=virtsock
time="2019-11-29T15:59:53Z" level=warning msg="Dial failed: failed to dial on vms/0/connect: dial unix vms/0/connect: connect: no such file or directory" type=virtsock
time="2019-11-29T15:59:53Z" level=info msg="All 71 gatherers finished" type=list

### Steps to reproduce the behavior
1) Download Docker Desktop for Mac from Docker Hub
2) Drag Docker app to Applications folder
3) Double click Docker app from Applications folder
4) On Privileged Access prompt, click OK
5) Enter Machine admin password
6) Error generated in Docker Desktop App

**Comment by mark-schulze** [comment]
Same here I think:
I get this message when starting Docker on macOS 10.15.1
![Bildschirmfoto 2019-12-04 um 22 54 09](https://user-images.githubusercontent.com/3390820/70185042-5d7ebf00-16e9-11ea-9bc4-e97cd8c8404a.png)

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
