### ISSUE TITLE
After a few hours not working with the workstation, containers are unreachables, and restart docker is needed.

### ISSUE THREAD

**Issue by corretge** [docker/for-mac#4091]
After a few hours not working with the workstation, containers are unreachables, and restart docker is needed.

I'm using docker for development pourposes, the version is:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/228097/70028712-ac234080-15a5-11ea-85ec-217fff0becff.png">

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: FB91B06E-C90A-4C08-984C-CD3862EEC3C6/20191203071500

### Expected behavior
Access to running containers.

### Actual behavior
Containers are unaccessible.

### Information

When I try to cancel the execution with ^C or docker-compose down, I get:

^CGracefully stopping... (press Ctrl+C again to force)
Killing home17_jekyll_1 ... 

ERROR: for home17_jekyll_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

When 

Seems that the issue is with the network interface after the sleepy mode. But I have the feeling that it happens more times recently.

  - macOS Version: 10.15.1 (19B88)

Docker for Mac: 2.1.0.5 (40693)

**Comment by esetnik** [comment]
I have the same issue as well as several coworkers. It seems related to the update to Catalina as the same project was not exhibiting these issues prior. We’ve also tried edge and can reproduce it there as well. This is a total productivity killer.

**Comment by kirupakaranh-opex** [comment]
Facing the same issue after upgrading to catalina

**Comment by a-nassif** [comment]
Same issue here with Catalina

**Comment by microtherion** [comment]
This behavior predates Catilina for me (I'm still on Mojave), see discussion in #3518 for instance. The frequency of occurrence seems to have decreased compared to a year ago, but it's still a regular occurrence.
