### ISSUE TITLE
docker desktop stuck at `Docker Desktop is starting` while changing disk image size

### ISSUE THREAD

**Issue by yanchao90** [docker/for-mac#4092]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:45F266EF-496F-4404-8886-77D02BCBD611/20191204012058

### Expected behavior
Docker desktop starts normally like it was doing before this problem.
### Actual behavior
Stuck in the forever loop of Docker Desktop is starting
### Information

  - macOS Version: Catalina 10.15.1

### Diagnostic logs

```
Diagnose succeeded

```

### Steps to reproduce the behavior

  1. Change disk image location
  2. Change Disk image size
  3. Docker restart automatically

**Comment by ulrich** [comment]
@yanchao90 Hello, what is the FS of the volume used for disk image exfat ? Can use apfs for your disk instead of ?

**Comment by yanchao90** [comment]
exfat
