### ISSUE TITLE
Can't run due to network error

### ISSUE THREAD

**Issue by okansahin** [docker/for-mac#4095]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E45A37A5-8131-4579-A078-2C7EDE8BCE2F/20191205014945

### Expected behavior
Running

### Actual behavior
After given the access which Docker needs an error occurs which titled 'Network Components'. If I even reset Docker to factory defaults this cycle begins from again. And reinstalling is not resolved the issue.

![Screen Shot 2019-12-05 at 05 08 02](https://user-images.githubusercontent.com/1966034/70197529-3c37c600-171d-11ea-933c-6d1ea04b01cb.png)

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.5

```
Things I have tried

https://github.com/docker/for-mac/issues/107#issuecomment-237320370

https://github.com/docker/for-mac/issues/1903#issuecomment-340914607

https://github.com/docker/for-mac/issues/1903#issuecomment-427100924

https://github.com/docker/for-mac/issues/3205#issuecomment-418862445

**Comment by ulrich** [comment]
@okansahin hello, your installations seems to be OK. Have you tried to uninstall Docker Desktop via Troubleshoot panel first ?

**Comment by okansahin** [comment]
Hello @ulrich, i have not got understand that what you mean with 'Troubleshoot panel' but tried to uninstall Docker.app by sending to trash. Then,

get pid with ps aux | grep docker and killed process
sudo rm /Library/LaunchDaemons/com.docker.vmnetd.plist 
sudo rm /Library/PrivilegedHelperTools/com.docker.vmnetd 

and install again. but still the same.

**Comment by okansahin** [comment]
Hello @ulrich,

Could you assist me about this? Because all of my work is disrupted. I tried to delete completely all folders but I cant do a fresh install. I always get the same error. I need to run Docker and need help for it. Is the only way a new OS?

Unloaded and deleted the LaunchDaemons,
'com.docker.helper'
'com.docker.vmnetd'

rm -rvf '/Library/PrivilegedHelperTools/com.docker.vmnetd'
rm -rvf '/private/var/tmp/com.docker.vmnetd.socket'
rm -rvf '/usr/local/bin/docker'
rm -rvf '/usr/local/bin/docker-compose'
rm -rvf '/usr/local/bin/docker-credential-desktop'
rm -rvf '/usr/local/bin/docker-credential-osxkeychain'
rm -rvf '/usr/local/bin/docker-machine'
rm -rvf '/usr/local/bin/hyperkit'
rm -rvf '/usr/local/bin/kubectl'
rm -rvf '/usr/local/bin/kubectl.docker'
rm -rvf '/usr/local/bin/notary'
rm -rvf '/usr/local/bin/vpnkit'

**Comment by okansahin** [comment]
Here is what I'm getting at system logs after giving the access,

/var/run/com.docker.vmnetd.sock refuses the connection but when I check the file it exists but I dont know why it refuses.

2019-12-06 16:58:07.675339+0300  localhost Docker[4457]: [Docker:] Vmnetd: registerProcess succeeded
2019-12-06 16:58:07.675412+0300  localhost Docker[4457]: [Docker:] Vmnetd: Privileged installation successful
**2019-12-06 16:58:12.683102+0300  localhost Docker[4457]: [Docker:] UnixDomainSocket: /var/run/com.docker.vmnetd.sock: failed connect: Connection refused**
2019-12-06 16:58:12.683429+0300  localhost Docker[4457]: (CoreFoundation) [com.apple.CFBundle:strings] Bundle: <private>, key: Docker.VmnetdError, value: Docker.VmnetdError, table: Error, localizationName: (null), result: Docker.VmnetdError
2019-12-06 16:58:12.683517+0300  localhost Docker[4457]: (CoreFoundation) [com.apple.CFBundle:strings] Bundle: <private>, key: The operation couldn\U2019t be completed. (%@ error %ld.), value: The operation couldn\U2019t be completed. (%@ error %ld.), table: Error, localizationName: (null), result: The operation couldn’t be completed. (%1$@ error %2$ld.)
2019-12-06 16:58:12.683764+0300  localhost Docker[4457]: (libsystem_trace.dylib) Created Activity ID: 0x5d4ca, Description: Activity for state dumps
2019-12-06 16:58:12.683866+0300  localhost Docker[4457]: [Docker:] Terminator: communication with networking components failed: The operation couldn’t be completed. (Docker.VmnetdError error 1.)

**Comment by okansahin** [comment]
Hello,

@ulrich was said the installation is OK, based on diagnostics. But when I inspect log-asl.txt I saw these lines,

> 2019-12-06 16: 29: 33 + 03 Okans-MacBook-Pro com.apple.xpc.launchd [user] [1] <Error>: Caller specified a plist with bad ownership / permissions: path = / Library / LaunchDaemons / com.docker.vmnetd.plist, caller = smd.244
> 2019-12-06 21: 22: 59 + 03 Okans-MBP com.apple.xpc.launchd [user] [1] <Error>: Caller specified a plist with bad ownership / permissions: path = / Applications / Docker. app / Contents / Resources / com.docker.vmnetd.plist, caller = launchctl.682

I tried all thing but I didn't resolve this issue.

I tried to change chmod to 600, 644, 755, 777. // Didn't work - Bad Permissions
I enabled root user on MacOS and tried to give root access to Docker. // Didn't Work - Bad Permissions
I tried a few old versions of Docker // Didn't work - Bad Permissions
Installed / uninstalled with brew cask // Didn't work - Bad Permissions
Tried to run Docker with root user // Docker declined to run with root user

and other things that I don't remember.
