### ISSUE TITLE
Not able to Install Docker on Mac

### ISSUE THREAD

**Issue by mayur29** [docker/for-mac#4096]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:71E24C52-B0DA-4D66-9FAB-F6A5E1D2C6BB/20191205101610

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
@mayur29 Hello, I seen that your disk are apparently full. Can you try to install Docker Desktop on a volume with enough capacity. By default Docker Desktop needs severals 10Go fore his raw file.

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
