### ISSUE TITLE
Docker Desktop Will Not Start On Mac Version 10.15.1

### ISSUE THREAD

**Issue by cbowland** [docker/for-mac#4097]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 61466FBB-E7A9-44C2-81C6-6B0B1DAF0C61/20191205134711

### Expected behavior
Docker Starts.

### Actual behavior
Animation continues and "Docker Desktop is starting message" appears but never progresses.

### Information

  - macOS Version: 10.15.1

### Diagnostic logs

```
Docker for Mac: version...
2.1.05 stable

```

### Steps to reproduce the behavior

  1. Click on Docker icon to run the app.
  2. Starting never completes

**Comment by MelissaFlinn** [comment]
I have the same problem with Mac 10.14.6 and the latest upgrade.

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
