### ISSUE TITLE
NIO.SocketAddressError error 3 still happening.

### ISSUE THREAD

**Issue by fjmcid** [docker/for-mac#4106]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A276473A-3864-4200-86C6-E7C83E76E618/20191207141041

### Expected behavior
Able to start a newly installed docker for desktop

### Actual behavior
A helper is needed installed. Credentials are asked and answer, and a nio.socketaddresserror error 3.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? since 2.1.X.X
  - Did the problem appear with an update? Yes, 2.1.0.0
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: 10.15.1

### Diagnostic logs
Docker for Mac: version 2.1.0.5

```

### Steps to reproduce the behavior
  1. Update/Install the newest version on a Mac Book Pro (15'', 2017 version).
  2. Try to install the helper on prompt.
  3. On credentials asked, fill.
  4. After entering and accepting, the error is prompt on installation.

**Comment by fjmcid** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2821906/70376108-09cbcb80-18cb-11ea-949b-0c37ebcff6ab.png">

**Comment by fjmcid** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/2821906/70376121-27993080-18cb-11ea-8905-d7d8a896a69d.png">

**Comment by vafrcor** [comment]
I had similar problem on Mac OS 10.12 (Sierra).
Hope there is a solution.
