### ISSUE TITLE
Changing Cpu/Memory settings casues settings to crash 

### ISSUE THREAD

**Issue by piotrb** [docker/for-mac#411]
### Expected behavior

it to open the settings page

### Actual behavior

Getting:

```
Failed to retrieve settings values.

failed to get memory setting
```

Error when opening the settings window.
Clicking Ok on the popup page closes the settings window

### Information

Diagnostic ID: 05C0C20F-CFD8-4AB1-947F-F300FE7FABA6

OSX 10.11.6

Originally Mistakenly reported as https://github.com/docker/docker/issues/25971

### Steps to reproduce the behavior

 1. Switch Memory/Cpu settings (I switches from 4 cores, 2Gigs to 8 cores, 4 gigs)
 2. Click Apply & Restart

**Comment by dsheets** [comment]
Thank you for your report. I've marked this as a P0.

**Comment by mchiang0610** [comment]
@piotrb This should be fixed in the latest build. I just tried it. 

Closing for now.
