### ISSUE TITLE
Docker Fails to Install MacOS 10.15.1

### ISSUE THREAD

**Issue by d3pr3553d** [docker/for-mac#4111]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 81A6DDF3-6353-4218-A614-9FA7A95DD202/20191209163424

### Expected behavior
Docker installs successfully on Mac.

### Actual behavior
Docker cannot install.

### Information

  - macOS Version: 10.15.1

### Diagnostic logs

```
Docker for Mac: version...

```

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
