### ISSUE TITLE
Docker Doesn't Start 

### ISSUE THREAD

**Issue by d3pr3553d** [docker/for-mac#4112]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 81A6DDF3-6353-4218-A614-9FA7A95DD202/20191209195510

### Expected behavior
Docker starts

### Actual behavior
Docker Doesn't Start

### Information

  - macOS Version: 10.15.1

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

 Install the dmg.
Wait for Docker to start.
Keep waiting.
It never starts. Power consumption spikes.

**Comment by tinsjourney** [comment]
have the  same issue. 
using "screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty", found the vms stuck at a bios prompt.
![Screenshot 2019-12-16 at 20 23 50](https://user-images.githubusercontent.com/12034408/70936358-6acd6f00-2042-11ea-91ec-afee4b44e7cf.jpg)

When selecting continue, Vm boot and everything work as usual.

**Comment by fdrennan** [comment]
I will say it is quite annoying that I have to run `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` each time I restart my computer on 10.15 Catalina.

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
