### ISSUE TITLE
Docker starts to get stuck and can never recover

### ISSUE THREAD

**Issue by FernandoArteaga** [docker/for-mac#4118]
### Description
I work daily with docker, luckily without any problems so far. It all started in the morning, when suddenly when deploying a stack, docker stopped responding from the command line or even from the Portainer interface.
The fans of my laptop began to work in signal of high consumption of resources, and it was like that, the process `com.docker.hyperkit` began to use more than 400% in the CPU.

- Docker version: **unknow**
- Portainer version: 1.22
- Mac version: 10.15.1

I restart the laptop (several times), restart docker (several times).
Even uninstall docker and reinstalled and it fallows the same behavior, first works and stops working randomly again

- Docker version: 19.03.5
- Portainer version: 1.23
- Mac version: 10.15.2

### Common factor
I'm always working with Portainer. Is Portainer braking docker??????

`com.docker.hyperkit`
<img width="914" alt="Screen Shot 2019-12-11 at 8 47 05 PM" src="https://user-images.githubusercontent.com/25615270/70675579-8bb74e00-1c57-11ea-8a11-69adba314555.png">

**Comment by FernandoArteaga** [comment]
# Update
After reinstalling it for n-time I received this message from docker
<img width="602" alt="Screen Shot 2019-12-11 at 8 47 32 PM" src="https://user-images.githubusercontent.com/25615270/70725806-0a999e80-1ccb-11ea-920a-81c950ae1ceb.png">

Being optimist I hope that resetting docker to factory default will fix everything but..... Surprise!!! It crashed again

**Comment by movd** [comment]
Looks like same error as mine #4088

**Comment by movd** [comment]
What kind of Mac are you running?

**Comment by leohmoraes** [comment]
Looks like same error as mine
macOS Catalina
Version: 10.15.3
MacBook Pro (Mid 2012) - i7 Dual Core - 16Gb Ram.
All updated! 
Two weeks without work!
