### ISSUE TITLE
Add perf to the linuxkit distro

### ISSUE THREAD

**Issue by tekumara** [docker/for-mac#4135]
I'd like to performance debug containers running on docker for mac.

Would it be possible to ship [perf with the linuxkit](https://github.com/linuxkit/linuxkit/blob/ef47cd9c98b76867673d112a42524ef68bcb36d1/docs/kernel-perf.md) distro that comes with docker for mac?

### Expected behavior

perf is shipped with docker for mac and so can be run via screen (or when entering pid 1)

### Actual behavior

perf isn't currently part of the docker for mac distribution

### Information

  - macOS Version: 10.14.6 (18G1012)

### Diagnostic logs

```
Docker for Mac: version... 2.1.0.5 (40693) 
Engine: 19.03.5
Machine: 0.16.2

Linux docker-desktop 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux

```

### Steps to reproduce the behavior

```
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
/ # perf
/bin/sh: perf: not found
```

**Comment by stephen-turner** [comment]
Could you please retest in Docker Desktop 2.5? As of 2.5, we are up to date with upstream LinuxKit, so any missing modules should be requested in the https://github.com/linuxkit/linuxkit repo.

**Comment by erszcz** [comment]
I'm also interested in using `perf` in a container on macOS. According to https://github.com/linuxkit/linuxkit/blob/master/docs/kernel-perf.md `perf` should be functional in linuxkit kernels, but within the container corresponding user-space tools have to be installed. In case of Ubuntu 20.04, `perf` tells me:

```
root@mongooseim-1:/# perf
WARNING: perf not found for kernel 5.4.39

  You may need to install the following packages for this specific kernel:
    linux-tools-5.4.39-linuxkit
    linux-cloud-tools-5.4.39-linuxkit

  You may also want to install one of the following packages to keep up to date:
    linux-tools-linuxkit
    linux-cloud-tools-linuxkit
```

But there's, obviously, no `linux-tools-5.4.39-linuxkit` in Ubuntu upstream repositories. How do I get the correct `perf` version for a linuxkit kernel (ideally for Ubuntu 20.04)?
