### ISSUE TITLE
Unable to install docker in MAC

### ISSUE THREAD

**Issue by ramanujadasu** [docker/for-mac#4136]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Need to install
### Actual behavior
Not install docker in my mac os
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...
Catalina
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Sorry, there is not any information in this bug report to triage it. Closing.
