### ISSUE TITLE
cannot install Docker for Mac on Catalina

### ISSUE THREAD

**Issue by mabraham** [docker/for-mac#4137]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: D02E1183-8154-4022-B591-37C85454A600/20191217134913

### Expected behavior

I expected Docker to install cleanly and run first time.

### Actual behavior

During initial installation on a Catalina Mac, or any subsequent launch of the Docker App, an error dialog pops up to say "Fatal error: The operation couldn’t be completed. (Docker.VmnetdError error 1.)" It offers the option to reset to factory defaults, but after this the error continues to occur. Docker never runs.

### Information

  - macOS Version: 10.15.1 (19B88)

### Diagnostic logs

```
Docker for Mac: latest stable. I can't specify any more, because it never runs and the download is automatically named "Docker.dmg"

```

### Steps to reproduce the behavior

  1. Download Docker for Mac from https://hub.docker.com/?overlay=onboarding
  2. Drag the dmg to Applications and install, providing password when prompted.
  3. Error pops up

**Comment by mabraham** [comment]
Duplicates #4111 and probably several others

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
