### ISSUE TITLE
docker ps is failing, can run application

### ISSUE THREAD

**Issue by HokiePedro** [docker/for-mac#414]
### Information

Diagnostic ID: 9F7F4ABD-F93A-4925-8139-55D20CBE352C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in 9F7F4ABD-F93A-4925-8139-55D20CBE352C/20160824-103232.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Notice>: vcpu 0 received signal, resuming
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Notice>: vcpu 1 received signal, resuming
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Notice>: vcpu 2 received signal, resuming
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Error>: VM: 2016-08-18 06:04:24 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Error>: VM: 2016-08-18 06:04:24 +0000 UTC kern.error kernel: INFO: rcu_sched detected stalls on CPUs/tasks:
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Error>: VM: 2016-08-18 06:04:24 +0000 UTC kern.error kernel: 	1-...: (1 GPs behind) idle=025/1/0 softirq=203990/203990 fqs=1
Aug 18 09:19:45 Pedros-MacBook-Pro Docker[com.docker.driver.amd64-linux][3348] <Error>: VM: 2016-08-18 06:04:24 +0000 UTC kern.error kernel: 	2-...: (6 GPs behind) idle=9ab/1/0 softirq=195677/195677 fqs=1
```
