### ISSUE TITLE
Not able to install in Mac

### ISSUE THREAD

**Issue by Developers-CareerGraph** [docker/for-mac#4141]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:F9DE065B-13FD-4EFA-910E-806CCA1536A3/20191219063455

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
