### ISSUE TITLE
Docker Desktop for Mac cannot login to Docker Hub

### ISSUE THREAD

**Issue by sergiks** [docker/for-mac#4143]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 24F01F53-12D2-4573-A4F8-4964714EEBAA/20191219083647

### Expected behavior
1. Sign in / Create Docker ID,
2. Enter my username, password (the pair lets me in at hub.docker.com)
3. Click Sign in
4. Log in

### Actual behavior

1. Sign in / Create Docker ID,
2. Enter my username, password (the pair lets me in at hub.docker.com)
3. Click Sign in
4. Window shakes, "Incorrect authentication credentials"

### Information
Fresh installation of Docker Desktop - just downloaded for the first time. 
Long time Docker CLI / Docker-Compose user.
Docker Hub account created back in 2015. After facing the login error, reset a password to a new one - that didn't change the situation.
Using 1Password manager for storing/generating passwords. Password is copy-pasted, not typed in.
Password is accepted at the web site, but not in the Docker Desktop for Mac app.

  - macOS Version:  macOS High Sierra 10.13.6

### Steps to reproduce the behavior
0. Fresh install Docker Desktop for Mac
1. Sign in / Create Docker ID,
2. Enter my username, password (the pair lets me in at hub.docker.com)
3. Click Sign in

**Comment by sergiks** [comment]
p.s. the username / password also lets me in from a command line `docker login` on the same Mac:
```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: ssokolov
Password: 
Login Succeeded
$ docker --version
Docker version 19.03.5, build 633a0ea

**Comment by sergiks** [comment]
In fact, after logging in from command-line `docker login` the DOcker Desktop for Mac is now also logged in.

So the only thing that didn't work is the login GUI form.

**Comment by eaylward8** [comment]
Just experienced the same issue and `docker login` on the command line worked for me as well.

**Comment by dan-teitsort** [comment]
I experienced the same issue with Docker Desktop for Mac as well, and had success with `docker login` as described above.

Docker Desktop community, version 2.1.0.5 (40693)
macOS Catalina version 10.15.2

Logging in via the website worked fine.

**Comment by mat007** [comment]
Thanks for the reports, I believe this has been fixed in the Edge channel already and should be available in the next Stable release next week.
