### ISSUE TITLE
Kubernetes show starting, and it hangs.

### ISSUE THREAD

**Issue by rogerpan** [docker/for-mac#4154]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rogerpan** [comment]
Kubernetes hangs on starting.

Diagnostic ID: 2B3DB60D-261C-4A66-9F33-57C8846E2736/20191224170615

**Comment by ClintCombs** [comment]
Same issue for this Diagnostic ID: 03914A0B-9E49-4FDA-B579-804F86AAC213/20200110022143

**Comment by sventech** [comment]
Same issue with version 2.2.0.0 (42247) on macOS 10.13.6 (High Sierra)

- used "Troubleshooting" option in menu -> "Reset Kubernetes cluster", "Reset disk image", "Reset to factory defaults" -- likely just the last one is needed

- under "settings" -> Kubernetes, select "enable kubernetes" and "deploy docker stacks to kubernetes by default" and both docker and kubernetes came up

**Comment by jeremyrdavis** [comment]
Same issue with version 2.2.0.3 (42716) stable
Also with 2.1.7.0 (41561) edge

I uninstalled minikube and installed Docker Desktop from both the dockerhub download and brew
[20200211225816.zip](https://github.com/docker/for-mac/files/4189025/20200211225816.zip)


Diagnostic ids from 2 different versions: 
3F329B76-2CD7-43DE-BAC4-F0C82D6A0B9F/20200211225816
34C5A5E9-A619-4B27-937B-69E99053FEC3/20200211114542
