### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by PokiFOX** [docker/for-mac#4155]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:8CCB520E-8281-45CB-B7FE-410B6D5DCCC3/20191225212835

### Information

  - macOS Version: macOS Catalina 10.15.1

### Diagnostic logs

```
Docker for Mac: version 2.1.7.0(41561)

```

### Steps to reproduce the behavior

![WechatIMG90](https://user-images.githubusercontent.com/46480047/71450717-22305700-27a2-11ea-8d01-7ba8b80a54b3.jpeg)

the status "starting" has lasted for several hours...
i try to run docker commands in terminal

docker config ls
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

Hmmmmm...

**Comment by novemberisms** [comment]
Getting the same error here. Any news on this?

**Comment by wadewilliams** [comment]
I have seen this _while docker is starting_ once it's started (the containers ontop the whale in the menu bar @ the top of the os will stop blinking) then it works.
