### ISSUE TITLE
Docker hangs on startup

### ISSUE THREAD

**Issue by jhume** [docker/for-mac#4157]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 42472C16-A90C-4320-B654-3B2EFA72E0DD/20191227135635

### Expected behavior
Docker starts as expected 

### Actual behavior
Docker hangs on startup - waiting 30 minutes and it still has not started. I recently ran `docker prune` and since then Docker refuses to start.  Everything was working fine previously.

### Information

  - macOS Version: 10.13.2

### Diagnostic logs

```
Docker for Mac: version 2.1.0.5 stable

```

time="2019-12-27T13:56:35Z" level=warning msg="[/usr/local/bin/kubectl.docker --namespace docker get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2019-12-27T13:56:35Z" level=warning msg="The connection to the server localhost:8080 was refused - did you specify the right host or port?\n" type=kubernetes
time="2019-12-27T13:56:35Z" level=warning msg="[/usr/local/bin/kubectl.docker --namespace kube-system get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2019-12-27T13:56:35Z" level=warning msg="The connection to the server localhost:8080 was refused - did you specify the right host or port?\n" type=kubernetes
time="2019-12-27T13:56:35Z" level=info msg="Start gathering list of 72 elements (timeout=10m0s)" type=list
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sw_vers -productVersion]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sw_vers -buildVersion]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [uname -r]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sysctl kern.boottime]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sysctl hw.memsize]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [vm_stat]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sysctl machdep.cpu]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [uname -a]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [ps uax]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [dmesg]" type=cmd
time="2019-12-27T13:56:35Z" level=warning msg="[dmesg] exit status 1" type=cmd
time="2019-12-27T13:56:35Z" level=warning msg="[dmesg]: Unable to obtain kernel buffer: Operation not permitted\nusage: sudo dmesg\n" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [id]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [sysctl -a]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [mount]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [df -h]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [launchctl print-disabled system]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [system_profiler SPHardwareDataType]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [ifconfig -a]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [netstat -ln]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [netstat -mm]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Executing: [netstat -nr]" type=cmd
time="2019-12-27T13:56:35Z" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2019-12-27T13:56:35Z" level=info msg="Gathering: /etc/hosts" type=file
time="2019-12-27T13:56:35Z" level=info msg="Executing: [scutil --dns]" type=cmd
time="2019-12-27T13:56:36Z" level=info msg="Executing: [scutil --nc list]" type=cmd
time="2019-12-27T13:56:36Z" level=info msg="Executing: [scutil --proxy list]" type=cmd
time="2019-12-27T13:56:36Z" level=info msg="Executing: [system_profiler SPFirewallDataType]" type=cmd
time="2019-12-27T13:56:36Z" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2019-12-27T13:56:41Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:56:41Z" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2019-12-27T13:56:46Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:56:46Z" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2019-12-27T13:56:51Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:56:51Z" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2019-12-27T13:56:56Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:56:56Z" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2019-12-27T13:57:01Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:57:01Z" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2019-12-27T13:57:06Z" level=warning msg="context deadline exceeded" type=http
time="2019-12-27T13:57:06Z" level=info msg="Executing: [/bin/sh -c docker network inspect $(docker network ls -q)]" type=cmd
time="2019-12-27T13:57:11Z" level=warning msg="[/bin/sh -c docker network inspect $(docker network ls -q)] (timeout: 5s) -> context deadline exceeded" type=cmd
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2019-12-27T13:57:12Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2019-12-27T13:57:12Z" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']" type=cmd
time="2019-12-27T13:58:15Z" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]" type=cmd
time="2019-12-27T13:58:22Z" level=warning msg="[syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]: NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.\n" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]" type=cmd
time="2019-12-27T13:58:22Z" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)]" type=cmd
time="2019-12-27T13:58:22Z" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)] exit status 1" type=cmd
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:version" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configget-contexts" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configcurrent-context" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnodes" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnamespaces" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describenodes" type=kubectl
time="2019-12-27T13:58:22Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2019-12-27T13:58:23Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:cluster-infodump" type=kubectl
time="2019-12-27T13:58:23Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describeservices" type=kubectl
time="2019-12-27T13:58:23Z" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describestorageclass,pv,pvc" type=kubectl
time="2019-12-27T13:58:23Z" level=info msg="Executing: [/Applications/Docker.app/Contents/MacOS/qcow-tool check /Users/johnhume/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2]" type=cmd
time="2019-12-27T13:58:24Z" level=warning msg="[/Applications/Docker.app/Contents/MacOS/qcow-tool check /Users/johnhume/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2]: qcow-tool: [INFO] image has 2048 free sectors and 997071 used sectors\n" type=cmd
time="2019-12-27T13:58:24Z" level=info msg="Skipping empty file: /Users/johnhume/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2019-12-27T13:58:24Z" level=info msg="Gathering: /Users/johnhume/Library/Group Containers/group.com.docker/already-enabled-features.json" type=file
time="2019-12-27T13:58:24Z" level=info msg="Gathering: /Users/johnhume/Library/Group Containers/group.com.docker/dhcp.json" type=file
time="2019-12-27T13:58:24Z" level=info msg="Gathering: /Users/johnhume/Library/Group Containers/group.com.docker/features.json" type=file
time="2019-12-27T13:58:24Z" level=info msg="Gathering: /Users/johnhume/Library/Group Containers/group.com.docker/http_proxy.json" type=file
time="2019-12-27T13:58:24Z" level=info msg="Gathering: /Users/johnhume/Library/Group Containers/group.com.docker/settings.json" type=file
time="2019-12-27T13:58:24Z" level=warning msg="/Users/johnhume/Library/Preferences/group.com.docker.plist not included" type=file
time="2019-12-27T13:58:25Z" level=warning msg="exit status 1" type=directorylist
time="2019-12-27T13:58:25Z" level=info msg="Gathering: /Users/johnhume/.docker/config.json" type=redacted-json
time="2019-12-27T13:58:25Z" level=info msg="Gathering: /Users/johnhume/.docker/daemon.json" type=redacted-json
time="2019-12-27T13:58:25Z" level=info msg="Getting Linux Diagnostics via a virtio socket: hyperkit:vms/0:62374" type=virtsock
time="2019-12-27T13:58:25Z" level=info msg="All 72 gatherers finished" type=list

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jhume** [comment]
Duplicate of https://github.com/docker/for-mac/issues/2420

**Comment by hixus** [comment]
+1
