### ISSUE TITLE
Upgrading to 1.12.1-beta24 failed

### ISSUE THREAD

**Issue by abh** [docker/for-mac#416]
### Steps to reproduce

Upgrading from an older beta to the latest one. Might be the same as #407, #413 or maybe even #409.

### Information

```
Diagnostic ID: 75A96AFE-D50A-48D1-8751-4B2567B1163F
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/ask/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/ask/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/ask/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by abh** [comment]
The first error showing up was "Fatal error - failed migration: failed to update app version history"

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
