### ISSUE TITLE
docker not starting. 5BBC9C28-86CD-4C88-8835-D94EC502E903/20191228120846

### ISSUE THREAD

**Issue by klawrenc** [docker/for-mac#4162]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
