### ISSUE TITLE
Docker Desktop for Mac fails to install persistently

### ISSUE THREAD

**Issue by codeperfector** [docker/for-mac#4164]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 65B92517-5B9A-41B2-B3B7-1A046427A3B9/20191228212707

### Expected behavior
Installer should not crash
### Actual behavior
Installer crashes with error VmNetdError: error 1
### Information

  - macOS Version: catalina 10.15.1 (19B88)

### Diagnostic logs

```
Docker for Mac: version...

Tried to install the latest versions from the website
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
Try....

I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109

**Comment by codeperfector** [comment]
Thank you ... the issue was that when I drag and drop, it created an alias instead of actually copying the application. When I copied the application, it just worked.
