### ISSUE TITLE
startup hangs on new mac

### ISSUE THREAD

**Issue by sreev** [docker/for-mac#4167]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: B3CC01C3-DD08-43F1-80EA-58236A95E997/20200102071204

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ckupe** [comment]
Version 2.1.7.0 from the Edge branch works on Catalina. https://docs.docker.com/docker-for-mac/edge-release-notes/
