### ISSUE TITLE
"Hang" during 'docker pull' extraction phase

### ISSUE THREAD

**Issue by garthk** [docker/for-mac#417]
### Expected behavior

`docker pull` makes continuous progress while `Extracting`; bar progresses to 100% before completion.

### Actual behavior

`docker pull` hangs for a minute, then reports `Pull complete` without apparently finishing extraction:

```
$ docker pull node:6
6: Pulling from library/node
357ea8c3d80b: Already exists 
52befadefd24: Already exists 
3c0732d5313c: Already exists 
ceb711c7e301: Already exists 
868b1d0e2aad: Already exists 
61d10f626f84: Extracting [======================================>            ] 10.49 MB/13.6 MB
```
… then, a minute or so later:
```
61d10f626f84: Pull complete 
Digest: sha256:12899eea666e85f23e9850bd3c309b1ee28dd0869f554a7a6895fc962d9094a3
Status: Downloaded newer image for node:6
```

### Information

Diagnostic ID: 4168FFD0-2A6A-4390-B7B7-22F705F5FD3F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)

**Comment by garthk** [comment]
See also #281?

**Comment by mchiang0610** [comment]
Thanks! Closing to merge with #281
