### ISSUE TITLE
Docker For mac Edge: Stuck at Kubernetes is starting...

### ISSUE THREAD

**Issue by theanam** [docker/for-mac#4170]
Docker for mac Edge. Kubernetes stuck at "Kubernetes is starting". I have tried reseting cluster, reseting docker for desktop.Nothing seems to work

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `9A41C2C4-753B-4DCE-9F9A-381CE1E3A753/20200104202035`

### Expected behavior
Kubernetes should start
### Actual behavior
Kubernetes is stuck at 
### Information

  - macOS Version: 10.15.2

**Comment by micksatana** [comment]
facing the same issue here

can you try run
```
pred='process matches ".*(ocker|vpnkit).*" || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")' /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

I'm getting this error repeatedly. is it the same on yours?
```
localhost com.docker.driver.amd64-linux[35450]: (libsystem_info.dylib) [com.apple.network.libinfo:getaddrinfo] nat64_v4_requires_synthesis(127.0.0.1) == false
```

**Comment by theanam** [comment]
Turns out it was due to the fact that `storage.googleapis.com` had been recently blocked in my country recently. Docker was attempting to download some files from there, and failing. Using a vpn during the download period solved my issue.
