### ISSUE TITLE
Diagnostic ID: E622E66B-507E-42CB-92C6-91450D543577

### ISSUE THREAD

**Issue by zhangda89** [docker/for-mac#418]
### Information

Diagnostic ID: E622E66B-507E-42CB-92C6-91450D543577
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Your diagnostic bundle did not upload (perhaps due to a known issue with diagnostic uploads not respecting system proxies and AWS access being blocked behind GFW). Does this issue still occur after uninstall/reinstall with Docker for Mac 1.12.1?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
