### ISSUE TITLE
Continual slowness and occasional crashes

### ISSUE THREAD

**Issue by rupertdance** [docker/for-mac#419]
### Steps to reproduce

1.  Install docker stable or beta for mac
2. Spin up local environment, in this case Drupal environments

### Expected behavior

Tell us what should happen
Sites should run fairly well

### Actual behavior

Tell us what happens instead
When not crashing - things work OK - but page load time is 20-30 seconds, frequent time outs.
I've tried multiple different versions of Docker, trashing my local environments, fresh installs etc. Same problem manifests.

### Information
 It began happening once I got my new iMac (5k retina late 2015 running 10.11.6 with 32gig memory, 3.2ghz i5, radeon R9 m390). So I wonder if there is possibly some strange conflict there.

I understand this is vague, but its consistent with whatever we run locally, and we have the same versions of docker running flawlessly elsewhere in the office on similar hardware.
```
Diagnostic ID: 854DD300-375F-42D9-A6A5-E375463D58AB
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment]
Do you still see this issue with more recent betas? Are you experiencing worse performance relative to other machines running Docker for Mac?

**Comment by samoht** [comment]
Detected symptom of problem 'auplink-segfault' in 854DD300-375F-42D9-A6A5-E375463D58AB/20160825-171803.

You hit an issue with the AUFS storage driver that we shipped in previous versions of Docker for Mac. You should upgrade to the latest version of the product which fixes this defect. Thanks!

May be related to docker/for-mac#7

The following log matches:
```
Aug 18 12:10:48 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:48 +0000 UTC kern.info kernel: device veth6d8c619 left promiscuous mode
Aug 18 12:10:48 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:48 +0000 UTC kern.info kernel: docker0: port 1(veth6d8c619) entered disabled state
Aug 18 12:10:49 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:49 +0000 UTC kern.info kernel: auplink[4452]: segfault at 7ffc00d204a8 ip 000000000043d049 sp 00007ffc00d204b0 error 6 in auplink[400000+ca000]
Aug 18 12:10:53 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Warning>: VM: 2016-08-18 02:10:53 +0000 UTC kern.warn kernel: aufs au_plink_put:434:dockerd[2687]: pseudo-link is not flushed
Aug 18 12:10:53 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:53 +0000 UTC kern.info kernel: auplink[4458]: segfault at 7fff74e264d8 ip 000000000043d049 sp 00007fff74e264e0 error 6 in auplink[400000+ca000]
Aug 18 12:10:54 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:54 +0000 UTC kern.info kernel: device veth7a4a769 entered promiscuous mode
Aug 18 12:10:54 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:54 +0000 UTC kern.info kernel: IPv6: ADDRCONF(NETDEV_UP): veth7a4a769: link is not ready
Aug 18 12:10:54 Ruperts-iMac Docker[com.docker.driver.amd64-linux][28068] <Notice>: VM: 2016-08-18 02:10:54 +0000 UTC kern.info kernel: IPVS: Creating netns size=2096 id=15
```
