### ISSUE TITLE
Kubernetes is running but Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by cxyfreedom** [docker/for-mac#4195]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E730280B-9470-468C-8D50-828F568DE7AF/20200115071330

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: version...
19.03.5
```

### Steps to reproduce the behavior

  1. kubectl version
  2. show `Unable to connect to the server: EOF`

**Comment by cxyfreedom** [comment]
conflict with minikube

**Comment by fayeah** [comment]
So did you resolve this? Did you try to remove minikube?
