### ISSUE TITLE
Docker hangs in a restarting state

### ISSUE THREAD

**Issue by sweetfa** [docker/for-mac#4196]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker goes to running state
### Actual behavior
Docker stays in restarting state permanently
### Information

  - macOS Version:
10.15

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
