### ISSUE TITLE
Can't open the Docker on Mac Catalina

### ISSUE THREAD

**Issue by caskercasker** [docker/for-mac#4197]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by srgkm** [comment]
It's broken on Catalina. Try this `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty`

**Comment by rajiv-ranjan** [comment]
I have the same issue on mac catalina. Diagnostic id is 19D43CD5-5040-4193-AF8A-347BDE97B517/20200121105257

**Comment by akobyakov** [comment]
Probably related to #3941.

**Comment by rajiv-ranjan** [comment]
After upgrading the docker desktop to 2.2.0.0 (42247) on mac catalina, issue is resolved. Thanks.

**Comment by GielVdh** [comment]
I am facing the same issue with docker desktop 2.2.0.0 on Catalina 10.15.3

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109

**Comment by ehontoria** [comment]
Facing the same issue, have tried multiple versions of the Docker for Mac with no results. 
ID: 77901649-4A44-49DD-BFC7-49F7FF8CC08A/20200302204146

**Comment by ehontoria** [comment]
Also ID: 77901649-4A44-49DD-BFC7-49F7FF8CC08A/20200302212132

**Comment by caskercasker** [comment]
thx for noticing me about my comment.
issue is Solved with update

**Comment by Moongazer** [comment]
This command `sudo launchctl config user path $PATH` (src #3941) solved it for me. After system restart I was able to run Docker.app. The first start asked for needed permissions and took over 3-4 minutes to finally come up. But now its working.

macOS Catalina v10.15.5
MacBook Pro, 500GB SSD, 8GB RAM
