### ISSUE TITLE
Docker is not starting

### ISSUE THREAD

**Issue by electriccode** [docker/for-mac#4198]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1B6904E4-A87A-4E47-A516-3E03F474DB8C/20200116073643

### Expected behavior
Docker process should start

### Actual behavior
Docker process is not starting

![image](https://user-images.githubusercontent.com/1471581/72508389-96bf5880-386b-11ea-8ddf-13d767a88c9e.png)

### Information

  - macOS Version: 10.15.1

### Diagnostic logs

```
Docker for Mac: 
```
![image](https://user-images.githubusercontent.com/1471581/72508464-b48cbd80-386b-11ea-9e14-9ecb4cd43a3c.png)

### Steps to reproduce the behavior

  1. Start docker

**Comment by leohmoraes** [comment]
the same
macOS Version: 10.15.3 (Catalina)
16gb (2Gb to Docker)
Diagnostics ID: 34714F24-7F93-496C-8F8B-61F2A18BA57B/20200206185056

![image](https://user-images.githubusercontent.com/5436213/73969879-f228b780-48fa-11ea-8183-02dd123848ce.png)

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
