### ISSUE TITLE
Failed to Open Docker.app on Mac Pro

### ISSUE THREAD

**Issue by dodoru** [docker/for-mac#420]
### Information

Diagnostic ID: A88E89B5-4435-4682-B0E5-3A2036E8A702
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11 (Build 15A284)
[ERROR]  docker-cli
         empty version
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/nico/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/nico/Library/Containers/com.docker.docker/Data/s60
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/nico/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/A88E89B5-4435-4682-B0E5-3A2036E8A702/20160825-153248/qemu-img-check.stdout 2> /tmp/A88E89B5-4435-4682-B0E5-3A2036E8A702/20160825-153248/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/nico/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/nico/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/nico/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/nico/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/nico/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@dodoru Possible to reset to factory default settings?  Does it exhibit the same behavior after? 

Do you have old versions of Virtualbox installed (4.3.x)? 

I'll reopen this once we get more details. Thanks!
