### ISSUE TITLE
Docker interaction with BlueStacks 4.140.12 on macOS 10.14.6

### ISSUE THREAD

**Issue by tomachinz** [docker/for-mac#4202]
Docker.app 2.1.0.5 (40693 stable)
docker -v 19.03.5
BlueStacks 4.140.12
macOS 10.14.6

   -[x] I have tried with the latest version of my channel (Stable or Edge)
   -[x] I have uploaded Diagnostics
   -[x] Diagnostics ID: 8AACD446-070E-4D72-92AF-4C2B397500A6/20200117014536

### Expected behaviour
Docker launches and does not display a warning regarding incompatibilities with BlueStacks (https://www.bluestacks.com/)

To be fair this is expected behaviour as a known issue exists with installing BlueStacks (android emulation platform) and Docker simultaneously on macOS. Docker reports this upon startup, so to resolve I should uninstall BlueStacks and try again. In my case, the Docker app was installed after BlueStacks. BlueStacks had been run only a little, having had around 5 apps installed. This issue from the uploaded diagnostic was from a cold boot, going straight to launch Docker first thing after login.

I intend to uninstall BlueStacks but thought I would post a diagnostic from my system to help others for what it is worth. Perhaps one day they can co-exist so I'm hoping posting this may help. 

### Actual behaviour
Upon launch, a modal alert appears:
_BlueStacks Detected
BlueStacks will crash the operating system if Docker runs in the same macOS boot session after BlueStacks has run. We recommend uninstalling BlueStacks in order to use the Docker Desktop.

[start anyway] [exit]

After clicking Start Anyway may exit Docker but upon starting again my issue is resolved.

Thus it is a transient issue apparently solved by:
- reboot
- run Docker app twice

### Information
 - To reproduce, I'd need to boot up BlueStacks 
 - I don't believe this is a new bug, it always was there since installing BlueStacks

**Comment by RobSjaras** [comment]
I'm experiencing the same inconvenience with my setup, even though I'm running a version of Bluestacks that doesn't interfere with Docker for Mac.

Seeing a solution to this problem would be really nice!
