### ISSUE TITLE
docker-machine not found after installing 2.2.0.0

### ISSUE THREAD

**Issue by Garito** [docker/for-mac#4208]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CDA0E3CE-9CCA-4C2F-9BF6-19CC93FFB44E/20200121180110

### Expected behavior
docker-machine execution on demand
### Actual behavior
docker-machine command not found
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Yes, this was intentional. (And is documented in the release notes). Docker machine was originally included purely for people transitioning to Docker for Mac when it was new. We don't feel it's useful to include it in the bundle for all Docker Desktop users, because if they have Docker Desktop they (almost certainly) don't need Docker Machine too. It's still available to download separately.

**Comment by Garito** [comment]
So, is there an alternative to connect with our servers or should we install it separately as you point out?
Or what is the rationale on this change?

**Comment by stephen-turner** [comment]
The rationale is to reduce the download size because almost nobody uses it. I'm not sure what your use case is, but if you need it you can install it separately.

**Comment by Garito** [comment]
Thanks

**Comment by bigelowcc** [comment]
It seems like Docker for Mac is uninstalling an existing docker-machine, is this the case?

After finding this thread I installed docker-machine from its releases page which was fine, but after updating Docker desktop today I found it was uninstalled again. It's going to be a pain if I have to reinstall docker-machine after every update.

**Comment by Garito** [comment]
It does
Everytime that the toolbox updates it deletes docker-machine even if you have installed manually

Is this an expected behavior? I hope not...

**Comment by stephen-turner** [comment]
This is not intentional. We'll look into it.

**Comment by Garito** [comment]
Thanks!

**Comment by mikeparker** [comment]
@Garito @bigelowcc you shouldnt need docker-machine any more, Docker Desktop is better and does everything you need (I hope!).

What are you trying to do?

**Comment by Garito** [comment]
I deploy directly to digital ocean

**Comment by bigelowcc** [comment]
Our local development setup uses docker-machine for a network of VMs. It could definitely be changed to Docker Desktop, but we haven't had the time to sit down and do that yet. So it's currently just a case of legacy support, not wanting it to be uninstalled.

**Comment by xorik** [comment]
if you have `brew` just run:
```
brew install docker-machine
```

**Comment by stephen-turner** [comment]
The bug of the Docker Desktop uninstaller also uninstalling Machine is now fixed. (We can't go back and change the uninstaller for previous versions of Desktop though).

**Comment by eshellman** [comment]
Is there any documentation for the docker-machine -> Docker Desktop migration? Google is failing me.

**Comment by Garito** [comment]
Hi
@stephen-turner: again, the last version removes it
I understand that there will be another way to do what we are doing with it but I have no time to change my workflows (I would need 2 more programmers that I don't have)
Could someone tell the docker toolbox ppl to stop this for once, please?
I suggest to put a checkbox or something on the installer

**Comment by stephen-turner** [comment]
Yes, sorry about this. As it explains in the 2.2.3.0 release notes (https://docs.docker.com/docker-for-mac/edge-release-notes/), it has to happen one last time because the damage is already done. We believe it won't happen again.

**Comment by Garito** [comment]
thanks
