### ISSUE TITLE
Docker startup hangs on macOS Sierra | Diagnostic ID: A3361697-158F-4AB1-8D6A-BC07361B3748

### ISSUE THREAD

**Issue by jakubriedl** [docker/for-mac#421]
### Expected behavior

Expected docker to start

### Actual behavior

Docker daemon does not start and hangs in "starting"

### Information

It happens after wake of macOS Sierra.

Diagnostic ID: A3361697-158F-4AB1-8D6A-BC07361B3748
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A285a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. with installed and running docker sleep & then wake up Mac

**Comment by fjoesne** [comment]
If this is a hackintosh you should be aware of the need for virtualization capabilities that is usually disabled by the bootloader and may cause some problems. Some hardware may support intel virtualization technology, enabling this in the bios (if you are running mac os x on a PC) may solve the issue :)

**Comment by jakubriedl** [comment]
This is not hackintosh its official beta version of macOS Sierra on MacBook Pro retina - late 2012

But also docker is correctly working until put into sleep mode. When I switched to VirtualBox it is working correctly

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
