### ISSUE TITLE
Docker uses 100% CPU after Catalina upgrade (no containers)

### ISSUE THREAD

**Issue by olbrich** [docker/for-mac#4216]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5520CC52-6D7E-45AB-B26C-E278B0B7A672/20200123130737
  - [x] I have tried a factory reset
  - [x] I have uninstalled / reinstalled with brew

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by barelnir** [comment]
also happen on my mac with OS version 10.14.3
anyone working on it?

**Comment by olbrich** [comment]
I am no longer experiencing this problem with 2.2.0.0 (42247) on Catalina 10.15.2.
