### ISSUE TITLE
Upgrading to v2.2.0.0 on - Docker hangs on "Docker Desktop is starting..." forever

### ISSUE THREAD

**Issue by pdolinaj** [docker/for-mac#4219]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FE4C7C68-2234-458C-98CB-D92ED73EFFFE/20200124103538

### Expected behavior
Docker desktop starts

### Actual behavior
Docker desktop is hanging with message "Docker Desktop is starting."
### Information

  - macOS Version: 10.15.2

### Diagnostic logs

```
Docker for Mac: v2.2.0.0

Diagnose succeeded

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @pdolinaj 

If possible, can you reset to the factory defaults Docker Desktop and restart it?

**Comment by pdolinaj** [comment]
I tried to reset it but no difference.

I also reinstalled it but still same. By reinstalling I only downloaded the Docker and then replaced the old one with the newly downloaded. Is there an uninstall which removes everything?

It worked perfectly fine up until the latest update.

**Comment by pdolinaj** [comment]
OK, I've uninstalled it completely via the Docker panel and reinstalled and now it works fine.
SOLVED
