### ISSUE TITLE
After updating, k8s can not start

### ISSUE THREAD

**Issue by csiiwmz** [docker/for-mac#4220]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you send diagnostic via the Troubleshoot > Run diagnostics button ?

**Comment by ulrich** [comment]
@csiiwmz for information, there is a major version update of Kubernetes with the new release (2.2.0.0). It could be necessary to reset your Kubernetes cluster as indicate in the release notes.
