### ISSUE TITLE
Dashboard logs unreadable in dark mode

### ISSUE THREAD

**Issue by champo** [docker/for-mac#4226]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Seeing logs for a service should be readable like in the terminal.

### Actual behavior
The background is black with dark text. Check the 2nd log line: 
<img width="1085" alt="Screen Shot 2020-01-25 at 15 19 52" src="https://user-images.githubusercontent.com/202728/73125537-90755e80-3f86-11ea-9333-ab7081584c44.png">

Love the new feature btw!

### Information
  - macOS Version: Mojave 10.14.5

### Steps to reproduce the behavior
  1. Set darkmode
  2. Use a colorful log scheme
  3. Open the logs in Dashboard

**Comment by trungutt** [comment]
Thanks for the report, and we love to hear that you like it. 

Could you please give us an example of the Docker container that gives this color ?
