### ISSUE TITLE
Docker Desktop for Mac Won't load

### ISSUE THREAD

**Issue by GitWonder** [docker/for-mac#4227]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6211995A-D661-4140-8430-35A9BB4A86E5/20200126003442

### Expected behavior
Docker for Desktop launches

### Actual behavior
Error 1 then reset restart loop resulting in same error
Fatal Error
The operation couldn't be completed. (Docker.VmnetdError error 1.)

### Information

  - macOS Version: 10.15.2

### Diagnostic logs

Not available - can't launch application
Docker for Mac: version...
10.15.2
```

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
-->

  1. Install DMG
  2. Launch
  3. Fail

**Comment by salimhb** [comment]
this resolved the issue for me `/Applications/Docker.app/Contents/MacOS/Docker --reset` it just reset some preference and login credentials, images remained intact.

**Comment by leohmoraes** [comment]
I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109
