### ISSUE TITLE
Docker allocates entire RAM after start

### ISSUE THREAD

**Issue by ChrisWun** [docker/for-mac#4229]
- have uploaded Diagnostics
  - Diagnostics ID: 54D73620-6B89-4B55-97D6-D558D27D8E6C/20200126121755

### Expected behavior
Docker does not allocate the entire RAM after start.

### Actual behavior
Docker allocates the entire RAM (which is set in the settings) after start.

### Information
  - Is it reproducible?
      -> Yes, on every Docker start. Even if no container is running.
  - Is the problem new?
      -> yes
  - Did the problem appear with an update?
      -> Maybe. I updated to 2.2.0.0 today.
  - macOS Version:
    -> macOS Catalina 10.15.2

**Comment by stephen-turner** [comment]
Yes, that's how virtualisation works on the Mac, unfortunately. There is no memory hotplug or memory ballooning in the Mac Hypervisor.framework. We're dependent on what the OS provides.

**Comment by RNPValinor** [comment]
This is definitely a change from version 2.1.0.5. Previously docker would allocate ~1GB of RAM on startup (no running containers), on version 2.2.0.0 it now allocated the full 8GB set in preferences.

A warning on update/in the change log would be nice, considering the potential performance impairment this can cause.

**Comment by stephen-turner** [comment]
Interesting, because we haven't (at least intentionally!) made any changes in this area. But I shall test it.

**Comment by stephen-turner** [comment]
Yes, I'm seeing this too. We believe that the memory will be swapped out again transparently if the system comes under memory pressure, so it shouldn't cause any degradation in performance, but we will still look into it to try and understand why there's a difference. Reopening.

**Comment by stephen-turner** [comment]
We have pinned this down to the fact that we have updated the Linux kernel in 2.2: if we try with 2.2 but with the older kernel, the old behaviour returns. It seems that the new kernel is handling memory management differently in some way.

We are looking into whether this can be configured at all, without a kernel patch. We still don't believe it will cause any performance problems, but the reported number is at best scary.

**Comment by akmalharith** [comment]
@stephen-turner Is it possible to downgrade docker-for-mac without losing any existing data? 2.2.0 is frying my RAM. Virtually unusable now.

**Comment by stephen-turner** [comment]
It is unlikely that memory is the problem. Is your Mac reporting that it's under memory pressure (red in the activity monitor)?

**Comment by akmalharith** [comment]
Actually I've got the same symptom as @ChrisWun with 8GB of RAM is always allocated all the time with no containers running. I didn't take a screenshot of it, unfortunately.

For whatever that it's worth I've, I think I have to share it here. 

I've downgraded to 2.1.0.5 and I much better performance now.
WIth 8GB allocated 
<img width="500" alt="Screenshot 2020-01-31 at 11 45 18 PM" src="https://user-images.githubusercontent.com/22504259/73552839-e9139280-4483-11ea-9e54-5efc9053e727.png">
Docker.app now uses only up to 1.72GB.
<img width="275" alt="Screenshot 2020-01-31 at 11 44 27 PM" src="https://user-images.githubusercontent.com/22504259/73552843-eca71980-4483-11ea-94bc-7f761374f5b8.png">

**Comment by stephen-turner** [comment]
I understand that the reported memory is higher in 2.2, but is it actually causing a problem? If the system can reclaim the memory when it comes under memory pressure, you will not see any performance degradation. It's only a problem if your system is in the red zone in the Activity Monitor and can't get out of it.

**Comment by akmalharith** [comment]
I understand. I believe I did not run a lot of other things that could actually trigger the memory reclaim. But my Mac did sound like it was taking off to the outer space though.

**Comment by stephen-turner** [comment]
I suspect that might be CPU problems rather than RAM, but it's hard to be sure as you've gone back to the previous version.

**Comment by ethan92429** [comment]
See the following screenshots:
<img width="699" alt="Screen Shot 2020-02-10 at 5 36 05 PM" src="https://user-images.githubusercontent.com/8585379/74196762-ee16d580-4c2b-11ea-881a-ed59a36e19df.png">
<img width="1677" alt="Screen Shot 2020-02-10 at 5 35 26 PM" src="https://user-images.githubusercontent.com/8585379/74196763-ee16d580-4c2b-11ea-9754-29abf6172357.png">

com.docker.hyperkit taking 19 GB + with only a max of 16 allocated. Noticeable performance decline (almost unusable with no other intensive processes running) .

**Comment by stephen-turner** [comment]
As explained in #3232, there is a bug in the Activity Monitor in recent versions of MacOS that it reports twice the amount of memory actually used, so you are actually only using 9.8GB in this case.

Performance problems are more likely to be due to CPU than RAM.

**Comment by 264nm** [comment]
I'm seeing this as well. This was after a daemon restart. Climbed to 4GB and then straight to 8GB which is the amount of I've allocated in the settings.
[
<img width="783" alt="Screen Shot 2020-02-18 at 11 35 17 am" src="https://user-images.githubusercontent.com/6218078/74694136-fcc04680-5242-11ea-8625-4564b9d05cbd.png">
](url)

Not only that but it takes me about 15-20minutes when I go to build a container before it starts sending to build context.

It just took me 20m47.017s to build a container that has a large amount of layers cached.

**Comment by c2nc** [comment]
Have same in Catalina 10.15.3 (19D76) DD 2.2.0.5 (43884)
Leacks up to 2 x limit value. 
docker stats show that all is ok inside engine
sad

**Comment by stephen-turner** [comment]
Interesting, @c2nc, we'll look into that.

**Comment by stephen-turner** [comment]
@c2nc Which symptom is fixed if you set `debug: false`? (1) That all the memory is allocated at startup, or (2) that Activity Monitor reports 2x the amount of memory actually used?

**Comment by jwelshiv** [comment]
I got similar behavior after downgrading from 2.3 to 2.1.0.5 until I switched debug to `false`. Once switched it started reporting much less memory used. (These are fresh installs no containers on first boot)

<img width="980" alt="Screen Shot 2020-07-02 at 10 34 50 PM" src="https://user-images.githubusercontent.com/49926/86442281-6a38b500-bcc2-11ea-92fe-6069a5ee0f67.png">

Here are same settings with latest version 2.3.0.3. debug has no effect with this version.

<img width="1291" alt="Screen Shot 2020-07-03 at 12 05 31 AM" src="https://user-images.githubusercontent.com/49926/86442279-69078800-bcc2-11ea-94ff-4067f44841b5.png">

Actual memory used about the same either way, but subjectively performance on my machine quite a bit better. Perhaps other memory hungry procs are conserving? 
<img width="970" alt="Screen Shot 2020-07-03 at 12 13 14 AM" src="https://user-images.githubusercontent.com/49926/86442288-6dcc3c00-bcc2-11ea-9fee-b12ba1914a72.png">

**Comment by anschwa** [comment]
Is there a way to change the docker resource limits without docker for mac running?

I can't launch docker for mac anymore because it will allocate more RAM on startup than my machine currently has. I recently had to downgrade from 64GB to 12GB, so it seems like I'm stuck.

**Comment by stephen-turner** [comment]
You can change it in the settings.json file. Sorry, I don't remember the exact path on Mac as I'm on a Windows machine, but I think you should be able to find it.
