### ISSUE TITLE
Docker crashes on Mac

### ISSUE THREAD

**Issue by NatasjaJones** [docker/for-mac#4231]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BEB2B5E4-C3F0-45E8-A2B5-36CD80F11BD1/20200127084621
### Expected behavior
start Docker
### Actual behavior
Fatal error: Operation couldn't be completed (Docker.VMnetError 1)
### Information

  - macOS Version: 10.15.1

### Diagnostic logs

```
Zip included
Docker for Mac: version...
[20200127084621.zip](https://github.com/docker/for-mac/files/4116259/20200127084621.zip)


```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by danilofaria** [comment]
I am also using docker on Mac with the latest version and it keeps on crashing. It is completely unusable.
I have also uploaded a diagnostics with id 1D856F67-90B7-4CA3-B5E2-79073FB527FC/20200129140236

**Comment by danilofaria** [comment]
for me restarting the computer fixed it 🤔

**Comment by NatasjaJones** [comment]
> for me restarting the computer fixed it 🤔

Tried restarting, Docker still didn't work. Also an update of MacOS Catalina to 10.15.3 did not help unfortunately.
