### ISSUE TITLE
Add RISC-V binfmt to allow cross-building images for this architecture

### ISSUE THREAD

**Issue by carlosedp** [docker/for-mac#4237]
After the merge of https://github.com/docker/binfmt/pull/21, it's possible to cross-build images for RISC-V architecture.

This could be added to Docker for Mac.

**Comment by carlosedp** [comment]
Any news about this?

**Comment by carlosedp** [comment]
Any help with this @tonistiigi , @thaJeztah @tiborvass ?

**Comment by tonistiigi** [comment]
I believe there was an issue with the release pipeline in `docker/binfmt` and the lastest image that was pushed in https://hub.docker.com/layers/docker/binfmt/a7996909642ee92942dcd6cff44b9b95f08dad64/images/sha256-7e54e474ac8998c01367f11edcbe2bbfcb38d9d8bd87defbc407edfa0fd6cca8?context=explore did not get signed properly for content trust. So if we require that, this pipeline issue needs to be figured out first @StefanScherer . If we don't care about the signature I can make a bump pr.


@carlosedp offtopic but did some wip work on multi-arch version of this image in https://github.com/tonistiigi/binfmt/blob/master/binfmt/Dockerfile https://gist.github.com/tonistiigi/3bde96a3f1a5d22b05c695d747853d59 , including riscv emulators, and emulators on riscv. Probably doesn't make sense for the for-mac defaults but good as external image.

**Comment by carlosedp** [comment]
Nice! I will try to use it as my builder image.
Having this and https://github.com/docker/cli/pull/2084 added to Docker would make cross-building images so much easier :)

**Comment by thaJeztah** [comment]
This should now be available in Docker Desktop Edge 2.3.3.x, but feel free to comment if that doesn't work 👍
