### ISSUE TITLE
Exposing 2 range of ports show "Ports are not available: /forwards/expose/port returned unexpected status: 500"

### ISSUE THREAD

**Issue by moylop260** [docker/for-mac#4240]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 59DAC767-3A9F-470C-A6F6-16E47D5108BF/20200129202001

### Expected behavior
Allow start container using a range of available ports

### Actual behavior
docker: Error response from daemon: Ports are not available: /forwards/expose/port returned unexpected status: 500.

### Information

  - macOS Version: 10.15.2 (19C57)

### Diagnostic logs

```
Docker for Mac: 2.2.0.0 (42247)
 - Channel: Stable

```

![Screen Shot 2020-01-29 at 15 11 12](https://user-images.githubusercontent.com/6644187/73397669-a5fdc780-42a9-11ea-8637-d06af69789eb.png)

### `docker version` output
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Steps to reproduce the behavior

  1. `docker run -p 2652-2699:5432 -p 2652-2699:5433 postgres`
  2. Output: `docker: Error response from daemon: Ports are not available: /forwards/expose/port returned unexpected status: 500.`

### Extra information
Using the same command from a remote docker server hosted in ubuntu linux xenial it is working fine.

```bash
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

I mean

| docker params                       | Mac   | Linux |
|-------------------------------------|-------|-------|
| -p 2652-2699:5432                   | done! 🍏  | done! 🍏 |
| -p 2652-2699:5432 -p 2652-2699:5433 | fail! 🔴  | done! 🍏 |

### Video
[![asciicast](https://asciinema.org/a/1vPfs0zbQ2F15f22darCbYWtL.svg)](https://asciinema.org/a/1vPfs0zbQ2F15f22darCbYWtL)

**Comment by moylop260** [comment]
FYI I just downloaded [Docker Desktop Community 2.1.0.5
](https://download.docker.com/mac/stable/40693/Docker.dmg) and this issue is not reproduced it

**Comment by moylop260** [comment]
UPDATE same using 

<details><summary>19.03.8</summary>
<p>


Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

</p>
</details>

**Comment by martinb3** [comment]
Just ran into this as well -- 2.2.0.5 is basically unusable for me. I had to roll back to something before 2.2 and everything works great.

**Comment by JoanComasFdz** [comment]
According to [this post](https://developercommunity.visualstudio.com/content/problem/769412/dockerfile-ignored-when-runnig-docker-profile.html), the VS team is preparing a fix for this issue in 16.5 version, meanwhile, you can add the property `"publishAllPorts": true` in your launchSettings.json, for example:

```
"Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:44374", #<== Set a fixed port
      "environmentVariables": {
        "ASPNETCORE_URLS": "https://+:44374;https://+:5000",
        "ASPNETCORE_HTTPS_PORT": "44374"
      },
      "publishAllPorts": true, #<== This is equivalent to the -P flag in 'docker run'
      "useSSL": true
    }
```


It worked for me with this setup:

- Windows 10 1709 Build 16299.1747 with _Fast Start_ **OFF**
- Docker Desktop 2.2.05 (43884)
- Docker Engine 19.03.8
- Visual Studio 2019 Enterprise 16.5.4

I realized that the command VS was creating, contained the -p parameter twice, one with the port I specified and another with port 80, like this: `-p 3010:80 -p 3010:3010`.

After adding `publishAllPorts` it now creates the container and I can remotely debug it.

**Comment by moylop260** [comment]
@JoanComasFdz 
I think the VSC issue is unrelated since that this issue is talking about a range of ports.
`-p 3010-3012:80 -p 3010-3012:3010`

Native linux docker choose the first port available and older version of docker-machine too.
But newer version has conflicts with these kind of range.

**Comment by moylop260** [comment]
@thaJeztah 
Who could help us for this issue?

**Comment by thaJeztah** [comment]
Don't think I'd be able to help; I suspect this may be because Docker Desktop needs addition things set up to proxy networking. IIUC, each port will be mapped to multiple ports for the container? So the intent is to make port `3010` on the host route to _both_ port `80` _and_ port `3010` of the container?

@djs55 may have more insight in what Docker Desktop needs to set up for that situation

**Comment by moylop260** [comment]
Thanks for reply @thaJeztah 

> each port will be mapped to multiple ports for the container?

It is not.

If you run in linux or older docker-for-mac version:
 - `docker run -p 3010-3020:80 -p 3010-3020:8080 ...`

The exposed port are:
`docker port CONTAINER1 80`
0.0.0.0:3011

`docker port CONTAINER1 8080`
0.0.0.0:3010

If you run again the same command:
`docker port CONTAINER1 80`
0.0.0.0:3012

`docker port CONTAINER1 8080`
0.0.0.0:3013

| container  | 8080 | 80   |
|------------|------|------|
| container1 | 3011 | 3012 |
| container2 | 3013 | 3014 |

Docker is looking for the enabled port automatically, we don't need take care about looking for a enabled port.

However, running the same command using a newer version:
 - `docker run -p 3010-3020:80 -p 3010-3020:8080 ...`

The result is an error:
 - `docker: Error response from daemon: Ports are not available: /forwards/expose/port returned unexpected status: 500.`

**Comment by thaJeztah** [comment]
Ah, you're right; had my wires crossed (I think this might be different for services 🤔); we only create a "range" if both sides are a range. No idea directly
