### ISSUE TITLE
Unable to add symbolic link directories to File Sharing list

### ISSUE THREAD

**Issue by pcrispim** [docker/for-mac#4247]
In Docker Desktop for Mac version **2.2.0.0 (42247)**, I'm unable of setting some paths in the _Preferences > Resources > File Sharing_, namely when the path corresponds to a symbolic link.

I have a build pipeline that generates files the temporary directory (which on macOS is in `/var/folders`) and a later step mounts the generated directory and files to a Docker container.

The mounting fails with the error:
```
Error response from daemon: Mounts denied:
The path /var/folders/lx/dl0nhlbd26b9cgdwjf3v01pr0000gn/T/services-Hcy6VH is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

In the latest version of Docker Desktop, it appears to be impossible to add `/var/folders` to the file sharing list.

In previous version of Docker Desktop it was possible to go to _Preferences > Resources > File Sharing_ and directly edit the list of directory paths for sharing — but with the latest update the browse window opens and the user is forced to navigate to the directory they want to share.

Furthermore, in the case of symbolic links Docker Desktop resolves them to the actual directory.
This means that in macOS (Catalina, Mojave) navigating to `/var/folders` and selecting that as the directory to share will effectively add `/private/var/folders` to the list.

And the error from above will persist — and the message is indeed accurate: the directory under `/var/folders/...` isn't shared with Docker.

Is there an alternative to the UI to set the directories to share with Docker?
Otherwise, this requires a downgrade...

### Expected behavior

Directories represented by symbolic links can be added to the list in _Preferences > Resources > File Sharing_, as in previous versions.

### Actual behavior

When opening directories that are symbolic links in _Preferences > Resources > File Sharing_, the original directory is added to the list instead of the selected path.

### Information
  - The issue is 100% reproducible.
  - macOS Version: 10.15.2 (19C57)

### Diagnostic logs
N/A

### Steps to reproduce the behavior
  1. Open Docker Desktop for Mac Preferences;
  2. Navigate to _Resources_ and _File Sharing_ then select the plus symbol to add a path to the sharing list;
  3. Go to `/var` — use the Cmd+Shift+G to type in `/var`;
  4. Select Open;
  5. The list now has `/private/var/folders`

**Comment by jacanales** [comment]
Having the same issue with mounted volumes in OSX Catalina using volumes mounted through /etc/synthetic.conf.

It is explained better here by another user: https://github.com/docker/compose/issues/7084

**Comment by hunts** [comment]
Ran into the exactly same issue after upgrade docker desktop to 2.2.0.3.

Is there a way to manually edit the configuration file directly to add /var/folders?

**Comment by pcrispim** [comment]
@hunts you can edit `~/Library/Group\ Containers/group.com.docker/settings.json`... it'll have a `filesharingDirectories` array; mine looks like this:
```json
"filesharingDirectories" : [
    "\/Users",
    "\/Volumes",
    "\/app",
    "\/private",
    "\/tmp",
    "\/var\/folders"
  ]
```
E.g., the `"\/app"` is a macOS symlink created using `/etc/synthetic.conf`.

Note that I actually installed an older v18 docker to add the paths then updated to latest and only later did I discovered this file... :(

Take care to back it up before editing.

**Comment by jacanales** [comment]
Right. I did what @pcrispim said and that worked for me.

**Comment by hunts** [comment]
It works for me as well. Thanks @pcrispim
