### ISSUE TITLE
Unable to install Docker in mac

### ISSUE THREAD

**Issue by vrajesh1989** [docker/for-mac#4253]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AF2E44D6-3AE7-4099-BC21-A57743813161/20200202173046

### Expected behavior
Docker should install.
### Actual behavior
Installation failed with error.
### Information

  - macOS Version:

### Diagnostic logs
The operation couldn’t be completed. (Docker.VmnetdError error 1.)
```
Docker for Mac: macOS mojave 10.14.6

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by charleswhchan** [comment]
I am also seeing this error when using latest version of Docker Desktop for Mac and OSX version. 
Diagnostics ID: B98B9755-5E53-47CB-83B9-D623DA1DB816/20200204060344

**Comment by lduparc** [comment]
Unable to install version 2.2.0.0 on mac os x Catalina 10.15.2 and 10.15.3.

Receive : `com.docker.backend cannot start`

**Comment by leohmoraes** [comment]
Try this

I have fix **Usage CPU**  and the **docker starting forever**
https://github.com/docker/for-mac/issues/4290#issuecomment-589674109

**Comment by scaszoo** [comment]
> #4290 (comment)

I see a downgrade, not a fix? Am I missing something?

**Comment by LoopBook** [comment]
I have the same problem

**Comment by kaschbacher** [comment]
I am also having this problem.  Is there a solution you could link to?
