### ISSUE TITLE
Hyperkit high memory usage

### ISSUE THREAD

**Issue by ingshtrom** [docker/for-mac#4256]
I'm not sure if this is a HyperKit bug, but https://github.com/moby/hyperkit/issues/231 seems to point at the source being Docker for Mac, so I'm posting here first. 

The title says it all. I'm seeing 4+ GB memory usage from hyperkit, which is being used by Docker for Mac, I believe. I'm not doing anything crazy, except some building and pushing of images. No Kubernetes, no debug mode, although I do have experimental mode turned on. After turning that flag off, nothing changes in terms of memory usage by hyperkit. 

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:5F75A309-9D06-465E-BD9A-76BC86C260B2/20200203193855

### Expected behavior
Maybe use 2GB, max. I am really hoping it's under a GB or so.

### Actual behavior
Using 4+GB memory. Just starting up Docker results in 3.8GB usage in hyperkit. 

### Information
This has been going on for a while, just got around to filing an issue for it
  - macOS Version: Catalina 10.15.3

### Diagnostic logs
see the ID posted above

### Steps to reproduce the behavior
1. start Docker for Mac

**Comment by stephen-turner** [comment]
Thanks for the report. This is normal, see the explanation at the top of #3232.
