### ISSUE TITLE
Dashboard: Cosmetic issue

### ISSUE THREAD

**Issue by burningalchemist** [docker/for-mac#4258]
<img width="640" alt="Screenshot 2020-02-04 at 16 59 30" src="https://user-images.githubusercontent.com/18210256/73762014-e2c93300-476f-11ea-9b1d-5b5c68ce89e3.png">

  - [x] I have tried with the latest version of my channel (Stable or Edge)

### Information
  - macOS Version: v10.15.3
  - Docker Desktop Version: v2.2.0.0 (Stable)

### Description
Missing whitespace in `Settings/Resources/File Sharing/`

**Comment by mat007** [comment]
Nice catch, thank you!

**Comment by burningalchemist** [comment]
@mat007 It looks fixed in `2.2.0.3`, just updated my instance. 👍🎉
