### ISSUE TITLE
docker push is incredibly slow

### ISSUE THREAD

**Issue by yakticus** [docker/for-mac#427]
I am seeing extremely slow push times (i.e., 30 minutes or more just to push 40MB). speedtest.net says my upload speed is about 6Mbps. The details of this issue have been reported on the forum >1 month ago but there has been no response. See them here:

https://forums.docker.com/t/docker-push-is-cripplingly-slow/18289

I started experiencing extreme slowness even when pushing to AWS ECR. I stumbled upon the below thread which says to restart docker for mac. Sure enough, after restarting, the pushes became orders of magnitude faster. The relevant AWS thread is here:

https://forums.aws.amazon.com/thread.jspa?threadID=222834

**Comment by bacheson** [comment]
+1

**Comment by yakticus** [comment]
For comparison, I pushed ~300MB of image layers directly to Amazon ECR in about a minute, using the same internet connection.

**Comment by Ralph-Zitz** [comment]
+1

**Comment by vitosans** [comment]
+1

**Comment by mchiang0610** [comment]
Merging with #281
