### ISSUE TITLE
Docker Desktop Dashboard open default terminal app

### ISSUE THREAD

**Issue by darit** [docker/for-mac#4273]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When clicking the Cli button the default terminal should open the shell session (iTerm2 in my case)

### Actual behavior

When clicking the Cli button the Mac terminal opens a new window.

### Information

  - macOS Version: 10.15.3

### Diagnostic logs

```
Docker for Mac: 2.2.0.0 (42247)

```

**Comment by Parahexen** [comment]
Same here, no answer yet.

**Comment by nebuk89** [comment]
Hey,

Thanks for raising this! As this is a feature request I have opened this as an item on our public roadmap :) this is where we are tracking our new feature requests !

ttps://github.com/docker/roadmap/issues/98

Feel free to vote it up there as well as here!

**Comment by aminalplanet** [comment]
I would love the ability to use iTerm2 as the default terminal as well. Even a solution like what Transmit 5 has done (https://library.panic.com/transmit/transmit5/open-in-terminal/) would be a step closer. Thanks for considering this!

**Comment by SourceCode** [comment]
This is pretty painful due to the default mac terminal being so poor.  In some cases I just replace the docker containers shell during development.

 Sharing a local configuration to your shell can be as easy as mapping the file in your docker-compose to the appropriate config

Consider something like this:
`RUN rm /bin/sh && ln -s /bin/bash /bin/sh`

**Comment by jasperf** [comment]
Would love to have this fixed as well. I would like to use iTerm and keep on getting basic macOS terminal loadeded. Did not see an option under preferences to choose the terminal.

**Comment by kid3night** [comment]
Please help to add this feature. Thanks!

**Comment by ychanaa** [comment]
+1 for this feature

**Comment by alexrosenfeld10** [comment]
+1 for this feature as well

**Comment by hurvajs77** [comment]
+1 for this feature

**Comment by StevenBlack** [comment]
This may be helpful for some:

In an iTerm window, use `docker attach`, for example

```bash
$ docker attach <name-or-id-of-your-container>
```

Documentation: [`docker attach`](https://docs.docker.com/engine/reference/commandline/attach/)

**Comment by aaznadi** [comment]
Would love to see this feature too. Should not be hard to implement.

**Comment by setuk** [comment]
+1 this would be very useful

**Comment by gstag** [comment]
+1

**Comment by 2yonghyun** [comment]
+1 for this feature

**Comment by Amar-Gill** [comment]
+1 for this feature

**Comment by yanbussieres** [comment]
+1

**Comment by frankvdp** [comment]
+1

**Comment by Jeffrey-Meesters** [comment]
+1

**Comment by jangaehler** [comment]
+1

**Comment by anegrin** [comment]
+1

**Comment by krishbin** [comment]
+1

**Comment by SachinShekhar** [comment]
Guys, any progress on this? People are switching to Podman already.

**Comment by aios** [comment]
+1

**Comment by ImFifa** [comment]
+1

**Comment by Bazindigo** [comment]
+1

**Comment by miloofcroton** [comment]
+1

**Comment by FaresKi** [comment]
+1

**Comment by anthonygrant** [comment]
+1

**Comment by TechAndres** [comment]
+1 🙏

**Comment by teefal** [comment]
+1 ... so painful to go back to Mac Terminal

**Comment by zLinz** [comment]
+1

**Comment by poplar89** [comment]
+1

**Comment by AaronDowdy** [comment]
+1

i'm only now seeing the usefulness of using the docker dashboard app, and i'd love a bit more customizeability for the terminal shortcut to be able to utilize iterm2/others

**Comment by strawberry-crisis** [comment]
+1 this would be so nice if we could set iTerm as default

**Comment by SteAckC** [comment]
+1 Really looking forward to the update on this quick path

**Comment by manueles95** [comment]
+1 for this feature

**Comment by michealy** [comment]
+1

**Comment by Ibsardar** [comment]
+1

For Windows, clicking the CLI button is doing something like:
```` cmd
start cmd /c "docker exec -it <container_id> /bin/sh"
````

If user could pick powershell instead of cmd, it would look something like:
```` powershell
start powershell -command "docker exec -it <container_id> /bin/sh"
````

So for this feature to be implemented for Windows, you would have to provide users options of choosing from a preset list of shells, where each option is paired with a parent command like `start powershell -command` and a child command like `docker exec -it <container_id> /bin/sh` to handle the different syntax for each type of shell. You could even go further and allow users to change the default command that is run in the container (like `/bin/bash` instead of `/bin/sh`). I believe something similar can be done for Mac.

**Comment by greg-owl** [comment]
+1

**Comment by IngmarBoddington** [comment]
+1!

**Comment by franckbrun** [comment]
Hello, this is my little "tricky" workaround (Docker Desktop version 3.1.0):
- Decompress `app.asar` in "Resources" folder of the app (in a work folder)
<pre>
npx asar extract app.asar app
</pre>
- Save file list ordering
<pre>
npx asar l app.asar > order.txt
</pre>
- Search `terminal.js` (app/src/remote)
- Change the parameters passed to `osascript` (I use a external script to open iTerm)
<pre>
...
 'osascript',
    [
      'path_to_the_script_file/open-default-terminal.scpt',
      `${command}`
      //'-e',
      //'tell application "iTerm" to activate',
      //'-e',
      //`tell application "iTerm" to do script "${command}; exit"`,
    ],
...
</pre>
- Compress the app folder (respecting file order)
<pre>
npx asar p --ordering ./order.txt app app.asar
</pre>
- Copy the new `app.asar` int the resource folder of Docker Desktop (save the old one).
- Now (normally) when clicking the CLI button your script will be launched (you will be prompted by macos for some permissions).

Sample of script:
<pre>
on run argv
	tell application "iTerm"
		activate
		set newWindow to (create window with default profile)
			tell current session of newWindow
				set command to item 1 of argv
				write text command
			end tell
	end tell
end run
</pre>

**Comment by placid2000** [comment]
+1

**Comment by jayjah** [comment]
+1

**Comment by franckbrun** [comment]
Perhaps using the env variable $TERM_PROGRAM should be a good starting point.

**Comment by darit** [comment]
I'm on version 3.2.2 and this has been added. Thanks  @stephen-turner and Docker team, you rock!

**Comment by hurvajs77** [comment]
I confirm too :-) It works correctly on Mac and version 3.2.2. Many thanks!

**Comment by allejo** [comment]
Because I was dumb and was looking for an option to enable/configure this feature in the settings, there's nothing to enable. It just somehow works magically ✨

**Comment by floatingpurr** [comment]
Here with docker 3.2.2 and iTerm2 3.4.4 it doesn't work. Docker CLI is opened in the legacy terminal of MacOS and not in iTerm2.
