### ISSUE TITLE
`vpnkit-bridge` uses more and more memory until OOM'd

### ISSUE THREAD

**Issue by dgholz** [docker/for-mac#4277]
Docker Desktop `2.2.0.0 (42247)`
macOS Catalina `10.15.3 (19D76)`

I was looking at why Docker Desktop (on macOS) was randomly crashing overnight, and traced it to the OOM killer (in the Linux VM) killing `vpnkit-bridge`. This surprised me, as I wouldn't expect the network bridge to use a lot of memory. More investigation revealed that an internal utility was requesting a list of the containers every second and was causing `vpnkit-bridge` to use more and more memory.

I replicated what the internal utility was doing by running:
`while true; do echo -e 'GET /containers/json?all=true HTTP/1.0\n' | nc -U /var/run/docker.sock >/dev/null; done`
and watching `vpnkit-bridge`'s memory use increase in Activity Monitor. No `sleep 1` so the memory usage increases fast enough for the naked eye. You can have more containers (running or stopped) to make it increase even faster: I ran `seq 1 100 | while read i; do docker run --name test_$i alpine:edge /bin/false; done` to quickly create a lot of containers. I noticed that this caused `com.docker.vpnkit` to allocate more memory.

I don't know how to install any edge versions of Docker Desktop, sorry!

My expected behaviour is for the `vpnkit` binaries to release memory and to avoid the wrath of the OOM killer.

**Comment by dgholz** [comment]
I updated to Docker Desktop `2.2.0.3 (42716)` and see the same behaviour.

**Comment by dgholz** [comment]
I've noticed that `vpnkit-bridge` releases some of the memory after about 2 hours, when no requests were made through the Docker socket.

**Comment by BasicBeluga** [comment]
I'm also experiencing this issue on `2.2.0.3 (42716)`

**Comment by chansonpax8** [comment]
I get the same on `2.2.0.5 (43884)`

**Comment by madison-ookla** [comment]
I'm also experiencing this on `2.2.0.5 (43884)`

**Comment by hoov** [comment]
Still happening for me twice or three times per day on `2.2.0.5 (43884)`. Anything we can do to help?

**Comment by thaJeztah** [comment]
Looks like this should be resolved in Docker Desktop 2.3.x; https://github.com/docker/for-win/issues/5841#issuecomment-617079716

**Comment by stephen-turner** [comment]
Thanks for linking, @thaJeztah. If someone could test it on the latest Edge release, that would be helpful.

**Comment by dgholz** [comment]
I'll install Edge now and test it overnight.

**Comment by hoov** [comment]
I've been running edge for 4 days straight without crashes.

**Comment by benoror** [comment]
Still experiencing the same on 2.2.0.5 (43884)

**Comment by dgholz** [comment]
I tried Edge `2.3.0.1 (44875)` and can see the memory usage for `com.docker.vpnkit` is holding steady around ~70MB while requesting a list of all running containers every second.

**Comment by stephen-turner** [comment]
Fixed in 2.3, closing this ticket.
