### ISSUE TITLE
Ports don't appear to support multiple connections correctly.

### ISSUE THREAD

**Issue by bfsrjose** [docker/for-mac#428]
### Expected behavior

Multiple connections to redis container should work on docker for mac as well as they do on docker machine/boot2docker.

### Actual behavior

Multiple connections error out, easily reproduced with the redis-benchmark below. Issues also seen in our own unit tests.

### Information

Diagnostic ID: FB59AED0-5FFE-427E-9E81-1665C633D143
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.3 (Build 15D21)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. brew install redis
2. docker pull redis
3. docker run -d -p 6379:6379 redis
4. redis-benchmark -h localhost -p 6379
5. "Error: Server closed the connection"
(setting the number of connections to 1 appears to work).

**Comment by dsheets** [comment]
I can reproduce this on 1.12.1 and Beta 26.1 but not on the Beta 27 master branch due out this week that includes a variety of TCP/IP fixes. I will post here again once Beta 27 is released so that you have a reminder to confirm that this issue is resolved in Beta 27. Thanks for using Docker for Mac!

**Comment by bfsrjose** [comment]
Awesome, thanks :-)

**Comment by dsheets** [comment]
Beta 27 has now been released. Could you give it a try and see if it resolves the issue for you?

**Comment by bfsrjose** [comment]
Will do, I'll report back in a  bit.

**Comment by bfsrjose** [comment]
Looks like it is working, thanks!
