### ISSUE TITLE
Can't attach remote debugger after Catalina Update

### ISSUE THREAD

**Issue by barrettmatthew2** [docker/for-mac#4286]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C76EA763-74B9-4147-8A2C-94B818E9FDDF/20200214212539

### Expected behavior
IntelliJ IDEA attaches remote debugger and break points catch.

### Actual behavior
IntelliJ IDEA reports remote debugger is connected but break points don't catch.
When I start my Java OpenJDK-11 app without docker `mvn spring-boot:run ...` and attach the debugger with IntelliJ, everything works as expected.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? Yes, this didn't happen before I updated the Mac OS.
  - Did the problem appear with an update?  Yes.  Updating to Mac OS Catalina.
  - macOS Version:  Catalina 10.15.3 (19D76)

### Diagnostic logs

```
Docker for Mac: Version 2.2.0.3 (42716)

```

### Steps to reproduce the behavior

  1. `docker-compose -f docker-compose.yml up --build`
  2. Attach debugger to `localhost:7000`
  3. `curl localhost:7000 -v`

Here is the Dockerfile:

    FROM jetty:9.4.26-jre11

    ENV SPRING_PROFILES_ACTIVE local

    RUN yes | java -jar "$JETTY_HOME/start.jar" --add-to- startd="server,http,deploy,jsp,jstl,ext,resources,websocket,logging-logback"

    ADD ./logback.xml /var/lib/jetty/resources/logback.xml
    ADD ./logback-${SPRING_PROFILES_ACTIVE}.xml /var/lib/jetty/resources/logback-${SPRING_PROFILES_ACTIVE}.xml
    ADD ./start-script.sh /start-script.sh

    USER root
    RUN chmod +x /start-script.sh

    ADD ./my-service.war /var/lib/jetty/webapps/ROOT.war

    USER jetty
    EXPOSE 7000
    EXPOSE 8080
    ENTRYPOINT ["/start-script.sh"]

The docker-compose file:

    version: '3'

    services:
      my-service:
        container_name: my-service
        build: my-service/conf/docker/app/
        hostname: my-service
        environment:
          - ENV=local
          - SPRING_PROFILES_ACTIVE=local
        ports:
          - '8080:8080'
          - '7000:7000'
        expose:
          - 8080
          - 7000

start-script.sh

    #!/bin/bash

    java -Dorg.eclipse.jetty.server.Request.maxFormContentSize=-1 \
       -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} \
       -Xdebug \
       -agentlib:jdwp=transport=dt_socket,address=*:7000,server=y,suspend=n \
       -jar $JETTY_HOME/start.jar &

    tail -f /dev/null

And the HeartbeatController.java file

    @Controller
    public class HeartbeatController {

      @RequestMapping(
          path = "/heartbeat",
          method = RequestMethod.GET
      )
      public ResponseEntity<Void> ok() {
        return ResponseEntity.ok().build();
      }

    }

**Comment by stephen-turner** [comment]
If it happened with a MacOS update, it doesn't sound like a Docker Desktop bug. I would suspect an interaction between MacOS and IntelliJ.

**Comment by barrettmatthew2** [comment]
> If it happened with a MacOS update, it doesn't sound like a Docker Desktop bug. I would suspect an interaction between MacOS and IntelliJ.

I also suspected that so I cut out Docker and the problem was resolved.  From the command line I execute

    mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"

and then I can attach the debugger.
