### ISSUE TITLE
Stucked at Docker Desktop is starting

### ISSUE THREAD

**Issue by tarikkavaz** [docker/for-mac#4290]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
B600329A-2465-4569-A15D-9FC2458C617E/20200217113817
### Actual behavior
Stucked at Docker Desktop is starting
### Information

  - macOS Version: 10.15.3

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leohmoraes** [comment]
Hi, 

Docker was starting forever....but I have finally fix all problems after 2 weeks!!

Uninstall Docker and install Docker Desktop Community 2.1.0.5
https://download.docker.com/mac/stable/40693/Docker.dmg

**My SETUP:**
MacOS: Catalina 10.15.3
![Captura de Tela 2020-02-21 às 10 56 39](https://user-images.githubusercontent.com/5436213/75040130-deec1f00-5498-11ea-8c8f-a53354d6020f.png)

**DOCKER:**
Engine: 19.03.1
Compose: 1.24.1
Notary: 0.6.1
Kubernetes: v1.14.3
Machine: 0.16.1
Credencial Helper: 0.63
![Captura de Tela 2020-02-21 às 10 39 06](https://user-images.githubusercontent.com/5436213/75039120-bc590680-5496-11ea-821d-36a930a49f12.png)

**Preferences > Docker:**
CPU: 1, Memory 2Gb, Disk Space: 32Gb.
Results: CPU (com.docker.hyperkit: 3%, memory: 3Gb

**High CPU Utilization of Hyperkit in Mac?**
Tips: https://github.com/docker/for-mac/issues/1759

![Captura de Tela 2020-02-21 às 10 52 45](https://user-images.githubusercontent.com/5436213/75039874-553c5180-5498-11ea-8b7d-e99870964e40.png)

**Comment by tarikkavaz** [comment]
I uninstalled docker and installed it again.  
then I changed my "resources" settings on docker desktop to memory:1GB and swap:2GB 
I have an iMac late 2013 i5 8gb memory 
after a restart docker started without a problem.

**Comment by mirek** [comment]
Had same issue, weirdly after 3rd attempt to reset to factory settings and system reboot it did work. Very strange.
