### ISSUE TITLE
Enabled Kubernetes : incoherent number of containers

### ISSUE THREAD

**Issue by pomverte** [docker/for-mac#4296]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1F54721F-DECB-45A5-84BB-7C5FE0CD18C1/20200219182135

### Expected behavior
Running containers showned by `docker info` and `docker container ls` is the same when Kubernetes is enabled.

### Actual behavior
Running containers showned by `docker info` and `docker container ls` are different when Kubernetes is enabled.

### Information
  - macOS Version: 10.14.6 (18G3020)

To show the 18 running containers : preferences in docker desktop >> `Show system containers (advanced)`

### Diagnostic logs

```
Docker for Mac: version 2.2.0.3 (42716)

```

### Steps to reproduce the behavior
  1. Enable Kubernetes >> Apply & Restart
  2. `docker info` => 18 containers
  3. `docker container ls --quiet | wc -l` => zero containers
  4. Docker Desktop >> Preferences >> `Show system containers (advanced)`
  5. Apply & Restart
  6. `docker info` => 18 containers
  7. `docker container ls --quiet | wc -l` => 18 containers

```
$ docker info
Client:
 Debug Mode: false
Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
...
$ docker container ls --quiet | wc -l
       0
```

**Comment by stephen-turner** [comment]
Have I understood your point here? You're complaining that Kubernetes system containers are hidden by default? That is by design.

**Comment by pomverte** [comment]
Not exactly, I've not problem that Kubernetes system containers are hidden by default, but shouldn't the information be coherent between docker info and docker container ls ?

**Comment by pomverte** [comment]
/remove-lifecycle stale

I've reproduce the issue with `Docker for Mac: version 2.3.0.3 (45519)`

**Comment by stephen-turner** [comment]
Won't fix. docker info is intentionally more low level.
