### ISSUE TITLE
Kitematic dmg damanged

### ISSUE THREAD

**Issue by aadamsx** [docker/for-mac#43]
The Kitematic link downloads a dmg.  This dmg, when trying to open, states its damaged.  I tried this more than once.

**Comment by samoht** [comment]
Please specify the version you are using as explained in the documentation. This will help us to help you.

**Comment by samoht** [comment]
Also, please try to remove the `dmg` image from your `~/Download` folder, and try to download it again. Please re-open if it still doesn't work and/if you have more information. Thanks!

**Comment by aadamsx** [comment]
Why did you close this when I haven't even responded?  Anyhow, of course I deleted the file and tried to download it again -- 3x in fact.

Docker:
Version 1.12.0 (build: 10871)
9cd1dc28d3ac81cb5177ff9728f65200304b36f6

**Comment by aadamsx** [comment]
I tried downloading and opening it again this morning -- same result:

![screen shot 2016-08-01 at 7 44 51 am](https://cloud.githubusercontent.com/assets/5341158/17294349/e854e8de-57bb-11e6-89af-0949734565a4.png)

**Comment by samoht** [comment]
Where did you download Kitematic from? Just tried to reproduce and I have:

```
$ curl -OL https://download.docker.com/kitematic/Kitematic-Mac.zip
$ shasum -a 256 Kitematic-Mac.zip
0d6770197ed1db1c9a653c78bc51bb0d1483882233cf2d2bf688609b1a5251ef  Kitematic-Mac.zip
```

Which seems to work fine on my machine.

**Comment by aadamsx** [comment]
I downloaded the new Docker 1.12 for the Mac.  And the link is embedded in the dropdown very prominently in the application.

![screen shot 2016-08-01 at 7 54 07 am](https://cloud.githubusercontent.com/assets/5341158/17294570/525b1fc2-57bd-11e6-9315-2480701e9b92.png)

**Comment by samoht** [comment]
Yes I know. I am just trying to help you ... 

Can you please verify the sha256 of the zip that you are trying to open, to verify that you are trying to open the right one.

**Comment by aadamsx** [comment]
> Can you please verify the sha256 of the zip that you are trying to open

I don't know how to do that.

**Comment by samoht** [comment]
Ok no problem. Can you first delete all the previous download of Kitematic in your `~/Download` folder:

```
$ rm -f ~/Downloads/Kitematic*
```

Then download the image again by clicking on the link (or by doing `cd ~/Downloads && curl -OL https://download.docker.com/kitematic/Kitematic-Mac.zip`).

Then check that the sha256 is correct:

```
$ shasum -a 256 ~/Downloads/Kitematic-Mac.zip

```

It should give you the line:

```
0d6770197ed1db1c9a653c78bc51bb0d1483882233cf2d2bf688609b1a5251ef  Kitematic-Mac.zip
```

Then you can double-click on the `.zip` and copy the `Kitermatic (Beta).app` in your `/Applications` folder.

Let me know if it worked.

**Comment by aadamsx** [comment]
I followed these instructions:

$ curl -OL https://download.docker.com/kitematic/Kitematic-Mac.zip
$ shasum -a 256 Kitematic-Mac.zip
0d6770197ed1db1c9a653c78bc51bb0d1483882233cf2d2bf688609b1a5251ef  Kitematic-Mac.zip

![screen shot 2016-08-01 at 8 05 06 am](https://cloud.githubusercontent.com/assets/5341158/17294842/c81dec52-57be-11e6-9d14-17fd5fa490cc.png)

And it downloads fine (as it does from within your software).

The problem is when I try to open it:

![screen shot 2016-08-01 at 8 06 29 am](https://cloud.githubusercontent.com/assets/5341158/17294847/def768b8-57be-11e6-91ec-d57f6b276fe0.png)

So even downloading it with curl doesn't help.  The binary must be corrupted.

**Comment by samoht** [comment]
Thanks for following these instructions. The binary works well in the different setups that we tested it. Which version of OSX are you running? I am wondering if this is maybe a signing issue, but @FrenchBen (one of the author or Kitematic) will know more.

**Comment by aadamsx** [comment]
![screen shot 2016-08-01 at 8 11 18 am](https://cloud.githubusercontent.com/assets/5341158/17294996/a3d96e1a-57bf-11e6-8603-7fa86d3f22d5.png)

**Comment by MagnusS** [comment]
It could be related to this kitematic issue: https://github.com/docker/kitematic/issues/1637

You can check if the `com.apple.quarantine` attribute is set with `ls -l@` to list the extended attributes.

**Comment by aadamsx** [comment]
Will you please type out the exact command as it is to be written on the command line?

**Comment by samoht** [comment]
Can you try what is described in https://github.com/docker/kitematic/issues/1637#issuecomment-210924052

```
xattr -rc /Applications/Kitematic\ \(Beta\).app
```

**Comment by aadamsx** [comment]
This worked, thanks.

**Comment by urkle** [comment]
please stop recommending that people remove the quarantine attribute off the app.. All that does is tell Gatekeeper to not check the app. That does not fix the actual issue.  The issue is that the binary is incorrectly signed.

```
$ codesign --verify --deep --verbose=2 Kitematic\ \(Beta\).app/

--prepared:Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
Kitematic (Beta).app/: invalid signature (code or signature have been modified)
In subcomponent: Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
```

I went through and REMOVED all the _CodeSignature folders and re-signed everything with my DeveloperID and it correctly passes now.

```
$ codesign --verify --deep --verbose=2 Kitematic.app/

--prepared:Kitematic.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:Kitematic.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
--prepared:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper EH.app/Contents/MacOS/Kitematic (Beta) Helper EH
--validated:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper EH.app/Contents/MacOS/Kitematic (Beta) Helper EH
--validated:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
--prepared:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper NP.app
--prepared:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper NP.app/Contents/MacOS/Kitematic (Beta) Helper NP
--validated:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper NP.app/Contents/MacOS/Kitematic (Beta) Helper NP
--validated:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper NP.app
--prepared:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper.app
--validated:Kitematic.app/Contents/Frameworks/Kitematic (Beta) Helper.app
--prepared:Kitematic.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:Kitematic.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:Kitematic.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:Kitematic.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--prepared:Kitematic.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:Kitematic.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
Kitematic.app/: valid on disk
Kitematic.app/: satisfies its Designated Requirement
```

I can provide scripts if desired..

**Comment by FrenchBen** [comment]
@urkle Could you open an issue in https://github.com/docker/kitematic with the above information and what you did to fix it?

Thanks for the help!

**Comment by urkle** [comment]
@FrenchBen sure thing.  I found the current open bug report up there and I'll add in info on what they need to adjust.
