### ISSUE TITLE
Fatal error when start up docker on mac

### ISSUE THREAD

**Issue by vipweihua** [docker/for-mac#430]
### Information

Diagnostic ID: 5F83CB0A-9011-4645-B94A-3C1CE3447472
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         wrong Docker version: 1.11.0 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/Weihua/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Weihua/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Weihua/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/5F83CB0A-9011-4645-B94A-3C1CE3447472/20160826-094218/qemu-img-check.stdout 2> /tmp/5F83CB0A-9011-4645-B94A-3C1CE3447472/20160826-094218/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/Weihua/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Weihua/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/Weihua/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Weihua/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/Weihua/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by vipweihua** [comment]
![image 16-8-26 at 9 46](https://cloud.githubusercontent.com/assets/6855767/17991522/04a90cbc-6b72-11e6-9f4b-1a04081cae60.jpg)

When I saw this error, I removed virtualbox. But the error still pops up even I restarted my mac. It doesn't work.

**Comment by MagnusS** [comment]
Thanks for the report. Did you uninstall Virtualbox with the uninstall tool (e.g. from the Virtualbox dmg)?

**Comment by mchiang0610** [comment]
Closing due to no reply. Will reopen when we get a reply.

**Comment by vipweihua** [comment]
Hey, Magnus, Thanks so much. Fortunately, I found the virtualbox dmg and it really has the uninstall tool. Generally, I uninstall apps through long-click and delete or drag and drop it to the recycle center. Let's close it. Thanks so much.
