### ISSUE TITLE
Images frequently disapear and need to be rebuilt or re pulled

### ISSUE THREAD

**Issue by robinbryce** [docker/for-mac#4300]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E735FA06-ABAA-454D-8BAD-6B45B674F458/20200220170711

### Expected behavior

Images don't disapear (without notice) after being pulled or built
### Actual behavior
Images frequently disapear and need to be recreated
### Information

  - macOS Version: 10.14.6 

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @robinbryce 

Can you give us more details about the profile of your images (size, volume, ...) ?

Thank you for your feedback.
