### ISSUE TITLE
D06812E7-538B-492E-93D2-AE47C8707C4B/20200224225405

### ISSUE THREAD

**Issue by kimchirice** [docker/for-mac#4304]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:D06812E7-538B-492E-93D2-AE47C8707C4B/20200224225405

### Information

  - macOS Version: 10.14.4

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @kimchirice 

Can you give us more information about your trouble please?
