### ISSUE TITLE
Unable to launch docker in Mac OS X Catalina

### ISSUE THREAD

**Issue by Subbuz1** [docker/for-mac#4307]
Unable to open docker after installing in Mac OS X Catalina. Getting error "Docker.VmnetdError error 1"
![Docker Error](https://user-images.githubusercontent.com/45069468/75315274-569abf00-5888-11ea-8560-19c13d11a654.jpg)

[20200226053104.zip](https://github.com/docker/for-mac/files/4253566/20200226053104.zip)
/issues for docker-compose
  - https://github.com/docker/machine/issues for docker-machine
  - https://github.com/moby/moby/issues for Docker daemon
  - https://github.com/docker/docker.github.io/issues for the documentation
-->

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ehontoria** [comment]
I have the same issue. I've uploaded my diagnostics under ID 77901649-4A44-49DD-BFC7-49F7FF8CC08A/20200302204146

**Comment by ehontoria** [comment]
I also tried on a previous version, and got the same issue.

ID: 77901649-4A44-49DD-BFC7-49F7FF8CC08A/20200302212132
