### ISSUE TITLE
Docker doesn't run on first go on macOS public beta 6

### ISSUE THREAD

**Issue by rangedsp** [docker/for-mac#431]
### Expected behavior
Run on first go

### Actual behavior
Fails for first run
Runs on second time

### Information

Diagnostic ID: DEB2C013-E451-4FFA-B59A-3ADCFC650B7C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/jonny/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/DEB2C013-E451-4FFA-B59A-3ADCFC650B7C/20160826-172811/qemu-img-check.stdout 2> /tmp/DEB2C013-E451-4FFA-B59A-3ADCFC650B7C/20160826-172811/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/jonny/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jonny/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/jonny/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jonny/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/jonny/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Install Docker stable
2. Launch Docker
3. Clicked Next
4. Enter password
5. "Fatal error"
6. Restart Docker and it works

**Comment by mchiang0610** [comment]
Sierra problems should be addressed in beta 25. We are still working on smoothing the experience. 

Please try it here: https://download.docker.com/mac/beta/Docker.dmg 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
