### ISSUE TITLE
What the f, guys?

### ISSUE THREAD

**Issue by sgammon** [docker/for-mac#4314]
### Expected behavior
The new UI should work

### Actual behavior
It's terrible and doesn't work

### Information
  - macOS Version: `10.15` (Catalina)

### Diagnostic logs
Has nothing to do with Docker itself

### Steps to reproduce the behavior
1. Try to use the new UI. I dare you
2. Especially, try to add a file sharing root. Good luck
3. If your file sharing root needs to be typed in manually, you're screwed. Sorry! Lol!
4. Why, in god's name, would you have a text field that shows a caret, like you can edit it, but then you can't? Magic!

No really though, why would you release this? It is an *enormous* - *devastating* step back from what you had before as UI. Was that not "pretty" enough to run Docker containers? There is no functional improvement in this new Mac UI. So why did you release it?

Please do better, you shoulder people's careers. Their projects, their dreams. You simply shouldn't be touching stuff in the name of aesthetics when it could put the functionality of your software at risk.

**Comment by sgammon** [comment]
By the way - for lots of mac users, the file dialog is completely broken which selects a shared folder. So that means you can't select one at all.

If other mac users find themselves here, you can work around Docker's terrible release like this:
1) restart into recovery mode (i.e. hold Ctrl+R during restart)
2) log-in (you *are* using FDE, right?) and open Terminal
3) enter `csrutil disable` to disable SIP
4) restart back into normal mode
5) add your Docker shared volumes (the dialog should work now)
6) restart back into recovery mode
7) re-enable SIP with `csrutil enable`

**Comment by stephen-turner** [comment]
Thank you for the report.

First, let me clarify that the new UI is not primarily there to look prettier. It also allows us to add a lot of additional functionality in the UI that was previously only available on the command line. A large (and increasing) proportion of our users are not regular or confident command line users, and have been begging us to add features such as the new container view so that basic container lifecycle operations are available in the GUI as well as on the CLI. Overall it has received very positive feedback.

Having said that, we will of course look at the specific bugs you mention. It would be helpful if you could upload a diagnostic bundle because it also contains UI logs not just docker engine logs.

**Comment by sgammon** [comment]
@stephen-turner it's not much of a bug report. I figured these issues are widespread with the Catalina problems being experienced widely.

I do understand what you're saying, but perhaps you should have waited to force this UI until the aforementioned bugs were ironed out? It is not usable. There's no amount of product management reasoning that accounts for broken software. As for feedback: yes, the UI looks great. But it is _broken_ which defeats the purpose of feedback, since it clearly isn't (1) covering the full set of use cases, or (2) centered on functionality but rather other aspects of the software.

How can these not be widespread issues? Unless people are just flying with SIP off (*uh oh*) or, they just got lucky by virtue of happening to use a pre-ordained spot on disk, or they happen not to need shared volumes at all?

In any case, forgive me, I can split this up into individual bug reports, each with the context you might need to track it down. That would include:
- No ability to add shared volumes that include symlinks
- No ability to add shared volumes via manual path (only OS dialog)
- OS dialog to select shared volume path is broken by default in most areas on-disk on macOS
- "Resources" menu does not properly open, and must be repeatedly clicked to open
  - Or it's so slow, that at first it appears not to contain any sub-nav at all, which loses users looking for any of (*disk*, *proxying*, or *networking)
- Shared volumes are matched literally with configured paths rather than as real-paths

**Comment by stephen-turner** [comment]
Of course, we never intend to introduce any regressions. However, I don't think these issues are widespread. At least, we're not seeing them reported on this repository.

**Comment by rumpl** [comment]
@sgammon thnaks for the detailed report, unfortunately I was unable to reproduce your issue.

I have:
```
❯ csrutil status
System Integrity Protection status: enabled.
```

And I can add a new directory to be shared just fine, I am on Catalina.

**Comment by sgammon** [comment]
@rumpl it depends where you are on the filesystem

in my case, i have what could be considered a nightmare for filesystem operations:

Real path:
```
/                     root disk
/Volumes 
/Volumes/X            encrypted volume on-disk, active and mounted
```

Symlink path:
```
/data                   symlink root, links to /Volumes/X
/data/config            folder i want to share with Docker
```

Starting Docker with `-v $(pwd):/config` (in which `$(pwd)` expands to `/data/config`) causes a permissions error saying that the folder `/data/config` is not shared/allowed. So, I go to add the folder in the Docker for Mac UI.

However, I can't add the folder because:
1) It is not possible (at least in the build I'm running) to add a shared path manually, only via the OS dialog
2) The OS dialog cannot browse to the location specified, it can only browse to the real path
3) So I cannot add the path and am effectively stuck, unless I move my files or eliminate the volume

**Comment by sgammon** [comment]
@rumpl then there's the problem of SIP / macOS Catalina permissions, which forbid access to sensitive areas on disk. so, if I'm running with SIP off, I can't browse to areas like `/usr` or the root, and additionally, with SIP active, the OS dialog frequently refuses to open entirely.

My guess would be that it's opening to a location it doesn't have access to. That would make sense as to why it's breaking by default. But I can't be sure because I don't have any output from the Docker for Mac app describing _why_ the OS dialog never opens.
