### ISSUE TITLE
Docker commands no longer working after installing docker for mac

### ISSUE THREAD

**Issue by hedefalk** [docker/for-mac#432]
### Expected behavior
docker commands to work

### Actual behavior
❯❯❯ docker ps                                                             ⏎ master
Error response from daemon: Bad response from Docker engine

### Information

Diagnostic ID: A6FD1B8B-00E4-486D-A62C-44374E570E76
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install old docker-machine stuff
2. Install new docker

**Comment by hedefalk** [comment]
I guess it's a cleanup issue since I've been using old docker engine / docker-machine stuff before, but I thought the installation of this newest and greatest should clean up or at least be compatible since it migrated images and containers ok.

**Comment by hedefalk** [comment]
~/d/p/ensime-node ❯❯❯ ll `which docker`                                                       master
lrwxr-xr-x  1 viktor  staff    66B 26 Aug 10:36 /usr/local/bin/docker@ -> /Users/viktor/Library/Group Containers/group.com.docker/bin/docker

**Comment by hedefalk** [comment]
Trying to follow instructions here:

https://docs.docker.com/docker-for-mac/docker-toolbox/#/docker-toolbox-and-docker-for-mac-coexistence

but don't even get any server version:


> ❯ docker version                                                         
> Client:
>  Version:      1.12.0
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   8eab29e
>  Built:        Thu Jul 28 21:15:28 2016
>  OS/Arch:      darwin/amd64
> Error response from daemon: Bad response from Docker engine

**Comment by hedefalk** [comment]
> ❯ docker-machine ls                                                     ⏎ master
> NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
> default   -        virtualbox   Stopped                 Unknown

**Comment by hedefalk** [comment]
Did a factory reset on docker for mac and now it seems to work:

❯ docker version                                                          master
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64


However, it did before too so I'm not sure it will last…

**Comment by mchiang0610** [comment]
merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in A6FD1B8B-00E4-486D-A62C-44374E570E76/20160826-103917.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug 25 21:30:59 viktors-mbp Docker[com.docker.vmnetd][33066] <Notice>: User 501 has container folder /Users/viktor/Library/Containers/com.docker.docker/Data/s60
Aug 25 21:30:59 viktors-mbp Docker[com.docker.vmnetd][33066] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 25 21:30:59 viktors-mbp Docker[com.docker.vmnetd][33066] <Notice>: User 501 has container folder /Users/viktor/Library/Containers/com.docker.docker/Data/s60
Aug 25 21:30:59 viktors-mbp Docker[com.docker.vmnetd][33066] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 25 21:30:59 viktors-mbp Docker[com.docker.docker][33045] <Error>: Symlinks are not correctly installed.
Aug 25 21:31:20 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
Aug 25 21:31:22 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
Aug 25 21:31:24 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
Aug 25 21:31:25 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
Aug 25 21:31:25 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
Aug 25 21:31:25 viktors-mbp Docker[com.docker.docker][33045] <Notice>: progress 0.00
```
