### ISSUE TITLE
Failed to set posix_spawn_file_actions for fd -1 (errno 9)

### ISSUE THREAD

**Issue by sgammon** [docker/for-mac#4320]
### Expected behavior
Using Docker for Mac preferences to perform basic actions should be usable. In my case, I was adding a shared volume path with the OS dialog.

### Actual behavior
Docker for Mac spuriously emits the following error. I do not know if it is related to shared volumes or not.

<img width="820" alt="Screen Shot 2020-02-28 at 11 55 20 AM" src="https://user-images.githubusercontent.com/171897/75582888-6568a980-5a21-11ea-9f67-3751f8e30fa3.png">

### Information
  - **Is it reproducible?** No idea.
  - **Is the problem new?** Yes.
  - **Did the problem appear with an update?** Yes, although it could have been the update to Catalina, or Docker's updates. Hard to say.
  - **macOS Version:** `10.15.3` (Catalina)

### Diagnostic logs
I don't have diagnostic logs because they won't run (see #4319).

```
Docker for Mac: 2.2.0.3 (42716)
Engine: 19.03.5
Notary: 0.6.1
Compose: 1.25.4
Kubernetes: v1.15.5
Credential Helper: 0.6.3
```

### Steps to reproduce the behavior
Unclear yet but the error code above should be enough to diagnose, since it is internal to Docker for Mac's code.

(encountered while researching #4319 / #4318 and #4314)

**Comment by karthikarul20** [comment]
Facing the same issue after upgrading my macOS to `10.15.3 (19D76)` (Catalina)

![image](https://user-images.githubusercontent.com/5412806/76179364-a452e800-61f5-11ea-9dc0-b3b49580b78a.png)

`$docker --version`
`Docker version 19.03.5, build 633a0ea`

**Comment by zapodot** [comment]
Same issue here. Tried both restarting MacOS and reinstalling Docker Desktop. So far no luck. This totally sucks as Docker is now totally unusable

**Comment by ed0906** [comment]
Same issue here. Also tried reinstalling Docker for Desktop with no luck.

**Comment by karthikarul20** [comment]
> Same issue here. Also tried reinstalling Docker for Desktop with no luck.
> 
> Docker version: 2.2.0.4
> Engine version 19.03.8
> OS: Catalina 10.15.3

Instead if reinstalling, you can try this. 
`cd ~/Library/Containers/com.docker.docker/`
rename the "Data"
`mv Data Data-old`
or delete the whole folder if you dont care about your local docker containers. 
`rm -rf Data`
Then restarting docker will create the Data folder again.
Docker should be working, but the only difficulty is to rebuild all your local containers.

**Comment by ed0906** [comment]
> > Same issue here. Also tried reinstalling Docker for Desktop with no luck.
> > Docker version: 2.2.0.4
> > Engine version 19.03.8
> > OS: Catalina 10.15.3
> 
> If you have decided to reinstall, you can try this instead.
> `cd ~/Library/Containers/com.docker.docker/`
> rename the "Data" Folder
> `mv Data Data-old`
> or delete the whole folder if you dont care about your local containers.
> `rm -rf Data`
> Then restarting docker will create the Data folder again.
> Docker should be working, but the only difficulty is to rebuild all your local containers.

I gave it a go but the `Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9` still comes back :(

**Comment by ed0906** [comment]
Can confirm restarting my **Macbook** seems to have helped

**Comment by jdato** [comment]
Same issue. I've experienced that problem ever since moving to Catalina.
Restarting does not work, always comes back a few minutes after starting Docker desktop.

`Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9`

<img width="604" alt="Bildschirmfoto 2020-03-17 um 11 59 19" src="https://user-images.githubusercontent.com/22294144/76849987-bd3b4900-6846-11ea-90c8-99fbaed253a7.png">

**Comment by haroon-sheikh** [comment]
> > Same issue here. Also tried reinstalling Docker for Desktop with no luck.
> > Docker version: 2.2.0.4
> > Engine version 19.03.8
> > OS: Catalina 10.15.3
> 
> If you have decided to reinstall, you can try this instead.
> `cd ~/Library/Containers/com.docker.docker/`
> rename the "Data" Folder
> `mv Data Data-old`
> or delete the whole folder if you dont care about your local containers.
> `rm -rf Data`
> Then restarting docker will create the Data folder again.
> Docker should be working, but the only difficulty is to rebuild all your local containers.

This fixed the issue for me.

**Comment by gvazqu1** [comment]
Removing cd ~/Library/Containers/com.docker.docker/Data and restarting my mac seems to have solved the issued.

docker desktop: 2.3.0.2 
catalina: 10.15.4

**Comment by spoco2** [comment]
I get this also. Any word on a fix?

**Comment by jdato** [comment]
I get it pretty much after every Docker Desktop update... Always have to delete my `~/Library/Containers/com.docker.docker/Data` folder too. That works, is just annoying with large and often used images that I need to rebuild after that.
