### ISSUE TITLE
Very high energy and CPU consumption

### ISSUE THREAD

**Issue by dwamara** [docker/for-mac#4329]
- [ x] I have tried with the latest version of my channel (Stable)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 86EFE1EA-C363-4F32-8A30-631E91ADAE84/20200301215028

### Actual behavior
My problem is the same as https://github.com/docker/for-mac/issues/4323 adding the fact that the CPU consumption is crazy, so crazy that I can't call UIs like portainer.
Calling "docker ps" lasts at least 3 minutes before getting anything back.

<img width="333" alt="Screenshot 2020-03-01 22 49 54" src="https://user-images.githubusercontent.com/7215870/75634784-e89c2200-5c10-11ea-9cac-b0cf153dc552.png">

### Information
  - Is it reproducible? yes
  - Is the problem new? occurs since 4 days
  - Did the problem appear with an update? no
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: 10.15.3
  - Docker for Mac: version 2.2.0.3 (42716)

**Comment by radutopala** [comment]
Had the same issue.

Running `docker system prune`, setting it to run on 1 CPU and restarting it, had taken the CPU usage to <1% of CPU and energy impact also <1.

**Comment by dwamara** [comment]
It does improve the CPU consumption but not very much. I'll close the issue.
