### ISSUE TITLE
Docker makes my mac run hot while not in use

### ISSUE THREAD

**Issue by HaterMonestary** [docker/for-mac#4331]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

B29C0548-5C2C-4190-BE5E-491E3108FA18/20200302001743

### Expected behavior
docker should run without any load when nothing is running on the system
### Actual behavior
docker runs my machine hot periodically, not constantly but several times a day. the fans are running at full speed, and the energy consumption is high. 
### Information
I only use docker for creating authentication credentials for a okta, the container immediately exits on completion. the use of docker on my activity monitor is not directly tied to the use of the auth container. I need to auth occasionally, but I have this issue with docker often. 
im not sure what triggers it, but my machine will run at full load with docker running for some time and my fans will run at full speed. its noisy and uses up all my battery in no time.

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

Catalina Version 10.15.3 (19D76)

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB



```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cculianu** [comment]
I get the exact same behavior. All containers are stopped.  Nothing is going on.  The docker process just wakes up every few seconds and eats 20% CPU for no reason. This happens all day, every day.  I have decided to no longer start docker at boot.

I use docker for building/compiling C++ apps on a Linux guest anyway, so it doesn't need to be up all day.  I have resorted to only starting docker itself when I use it then killing it when done.

**Comment by mahirrudin** [comment]
related to this https://github.com/docker/for-mac/issues/4331

**Comment by HaterMonestary** [comment]
> related to this #4331

thats this issue?

**Comment by chezhiane** [comment]
ANY updates on this ? It is taking quite a lot of memory even when no container is running

**Comment by gaoxiaosong** [comment]
same here, docker desktop for mac 2.3.0.3(45519) stable.
always take 30% of 6 cpus to run it when there is no running container

**Comment by slconley** [comment]
I have this issue too.  I like to have Docker always ready, but for now am running it only when I need it.

**Comment by papiro** [comment]
I was having the same issue where my MacBook Pro sounded like it was preparing for takeoff and I had a couple tabs open in Chrome, VSCode, and Slack open and literally nothing else. I checked the Activity Monitor and was shocked to see Docker eating up 100%+ (don't ask me how) of my CPU resources! The problem was Docker Desktop, which I quit and my laptop slowed back down into a peaceful state. I am still able to run docker commands in the command-line even without Docker Desktop running 💯

**Comment by gnapse** [comment]
realted and/or duplicate of #3499?
