### ISSUE TITLE
diagnostic [ERROR] disk

### ISSUE THREAD

**Issue by mediafigaro** [docker/for-mac#434]
### Information

Diagnostic ID: D7FE8BC6-292C-44C0-8F89-2D202D714E8B
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/xxx/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/D7FE8BC6-292C-44C0-8F89-2D202D714E8B/20160826-171841/qemu-img-check.stdout 2> /tmp/D7FE8BC6-292C-44C0-8F89-2D202D714E8B/20160826-171841/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

tried this https://github.com/docker/for-mac/issues/172

**Comment by mchiang0610** [comment]
#601
