### ISSUE TITLE
 Docker For Mac new UI restricts using synthetic.conf links

### ISSUE THREAD

**Issue by federico-piazza** [docker/for-mac#4341]
### Description

Using the new UI of Docker for Mac restricts the usage synthetic links in Mac Catalina.

On the previous Docker For Mac UI, we were able to set a manual path for `Resource -> File Sharing`. However after the new re-skin when we set up a path, the UI automatically expand the path when they are symbolic links.

For the case of Mac Catalina, when we use synthetic links (through synthetic.conf) then the UI expand the link to the real folder breaking this way the logic we have. However, the old UI allowed manual entry without expanding the link and it allowed us to work.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
We should be able to use a symbolic link in `File Sharing` and avoid the link to be expanded.

### Actual behavior
On the new Docker for Mac UI, when we start our docker compose it says that it cannot mount the directory on `/datadrive/aerospike` and we must add it to File Sharing (but we cannot add it because of the automatic link expansion)

### Information

  - macOS Version: 10.15.3

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior
1. In Mac Catalina, create a file `synthetic.conf` inside `/etc`
2. Add a synthetic link on the root directory like this (below creates the symbolic link `/datadrive` pointing to my home directory): 

```
datadrive	System/Volumes/Data/Users/federicop/datadrive
```

3. Create any mount directory using `/datadrive`. For instance in our docker compose we used:

```
  aerospike:
    image: "aerospike/aerospike-server:${AEROSPIKE_VERSION:-4.2.0.4}"
    volumes:
      - /datadrive/aerospike:/opt/aerospike/data
```

This behavior has appeared after the new UI release. I have found a [post in SO](https://stackoverflow.com/questions/57819352/docker-desktop-for-macos-cant-add-usr-local-folder-in-preferences-file-sharing) where the guy mentions:
>Update I've downgraded progressively up to Docker Community Edition 2.0.0.3 2019-02-15. That seems to be the last version with the old user interface. With this version the folder browser dialog from file sharing displays all the folders and also manual editing of the file paths works. On versions Docker Desktop Community 2.1.0.1 and Docker Desktop Community 2.1.0.2, which have the new UI, it doesn't work.

**Comment by thaJeztah** [comment]
Looks the same / similar to https://github.com/docker/for-mac/issues/4325 ?

**Comment by federico-piazza** [comment]
@thaJeztah that seems actually the opposite behavior. What I can understand is that in that post the guy want the link to be expanded to real directory, but for my issue I want exactly the opposite... when I use a sym link I create them to simulate a specific directory. This is mandatory for Catalina since Apple add this weird volume systems.

**Comment by federico-piazza** [comment]
I could bypass the UI by editing this file:

```
~/Library/Group Containers/group.com.docker/settings.json
```

Then added my synthetic link there and fortunately that made the trick:

```
{
  "filesharingDirectories" : [
    "\/Users",
    "\/Volumes",
    "\/datadrive",
    "\/private",
    "\/tmp"
  ],
```

**Comment by sgammon** [comment]
@federico-piazza no i want to use the symlink too, i am filing the bug because i am _forced_ to use the realpath because of docker's ui (actually, this seems related to #4318)

thank you for sharing this snippet this helps a lot. this should definitely be documented somewhere by the Docker for Mac team

**Comment by seantcanavan** [comment]
This workaround worked for me as well. The UI was adding the symlink target directory and not the symlink itself which was causing docker permission errors when building code.
