### ISSUE TITLE
Kubernetes stuck on startup 

### ISSUE THREAD

**Issue by dbroker13** [docker/for-mac#4342]
I tried reinstalling, restarting, removing .kube directory, changing the host file and nothing has worked yet
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on 192.168.1.1:53: no such host
815F4464-057A-403F-9C2A-B36A96C70927/20200306175803

**Comment by clodoaldopaiva** [comment]
Anyone faced this issue? can help here

**Comment by madebymtr** [comment]
currently happening for me @clodoaldopaiva

**Comment by johnschult** [comment]
Same...  I have not seen any responses about this in any of the other issues that are related.
