### ISSUE TITLE
com.docker.supervisor cannot start exit code 9

### ISSUE THREAD

**Issue by alanlonglong** [docker/for-mac#4354]
when i boot webstorm 2019.2.3 and docker 2.2.0.3(42716) shutdown 
![image](https://user-images.githubusercontent.com/23056450/76188030-00c40080-6212-11ea-924e-92069f82aee3.png)
![image](https://user-images.githubusercontent.com/23056450/76188064-15a09400-6212-11ea-88d2-b653da285913.png)
![image](https://user-images.githubusercontent.com/23056450/76188092-2f41db80-6212-11ea-93c9-d59974495951.png)

**Comment by noamhurwitz** [comment]
I'm seeing this too

**Comment by sanhphanvan96** [comment]
Me too. The same error with ```Exit code 2```.
![image](https://user-images.githubusercontent.com/28304961/81675006-4d2cf600-9478-11ea-981e-f289e6db4f37.png)

**Comment by WimCools** [comment]
I have the same problem with docker 2.3.0.3 on macOS Catalina 10.15.4.  Even when no container are running it crashes after a while.
