### ISSUE TITLE
Can't change and save preferences

### ISSUE THREAD

**Issue by YakuninaNadya** [docker/for-mac#4358]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2B0411F1-8FF1-4A47-99C2-7F270F15FFEC/20200310151152

### Expected behavior
"Apply and restart" button should be active. Preferences should be changed.
### Actual behavior
"Apply and restart" button didn't change color. Preferences didn't change.
### Information

  - macOS Version: 10.14.6 

### Diagnostic logs

```
Docker for Mac: version 19.03.5, build 633a0ea

```

### Steps to reproduce the behavior

  1. Open Preferences
  2. Try to change some parameter (for example Memory)
  3. Try to push "Apply and restart" button.

**Comment by katheris** [comment]
I am also seeing this, I can click the button "Apply and restart" but it doesn't seem to do anything, If I go off the preferences and go back on the settings have jumped back to what they were before
