### ISSUE TITLE
Docker stuck in starting

### ISSUE THREAD

**Issue by cjbischoff** [docker/for-mac#436]
### Steps to reproduce

1. No real steps, docker is just seems to be constantly in a start mode, I kill it and start, stays in start mode.  After 2x updates, several reboots - just in a start mode.

### Expected behavior

It should just start

### Actual behavior

Docker is just "starting"

### Information

```
Diagnostic ID: 052E3999-667C-4FD0-A0A8-F1F7023A4051
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by Dominik-K** [comment]
Issue #484 seems to be the same (same build, newer MacOS version: 10.11.6). Has more info.

**Comment by mchiang0610** [comment]
Merging with #119
