### ISSUE TITLE
Kubernetes stuck on starting up

### ISSUE THREAD

**Issue by chuck-frazier** [docker/for-mac#4366]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2BBD814A-CC66-4D08-8899-58E187E1682E/20200313003033

### Expected behavior
Kubernetes Starts
### Actual behavior
Kubernetes Starting...
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Start Docker with kubernetes enabled in settings
  2. ...

**Comment by johnschult** [comment]
Same... I have not seen any responses about this in any of the other issues that are related.
