### ISSUE TITLE
Kubernetes Locks Out Preferences and Won't Start

### ISSUE THREAD

**Issue by tuxagon** [docker/for-mac#4367]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AE9F0574-8DBA-43C7-BD7D-982E75DCF06A/20200313213206

### Expected behavior

1. Kubernetes would start

2. If kubernetes doesn't start, I should still be able to open preferences

### Actual behavior

1. Docker desktop creates the context but hangs on "Kubernetes is starting"

2. Preferences are no longer accessible because of the spinner

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: version: 2.2.0.4 (43472)

Engine: 19.03.8
Compose: 1.25.4
Kubernetes: v1.15.5
Notary: 0.6.1
Credential Helper: 0.6.3
```

### Steps to reproduce the behavior

  1. Enable kubernetes and restart docker desktop
  2. Open docker desktop preferences

**Comment by soccer99** [comment]
This is happening to me as well!

**Comment by dfang** [comment]
This is happening to me as well!

rolled back to 2.1

**Comment by boosey** [comment]
Happening to me as well. Even rolling back to 2.1 didn't fix it.
