### ISSUE TITLE
Error at install Docker on macOS 10.15.3 (Catalina)

### ISSUE THREAD

**Issue by yants95** [docker/for-mac#4368]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 10.15.3
![Screen Shot 2020-03-13 at 18 33 09](https://user-images.githubusercontent.com/14876382/76661012-1c544180-6559-11ea-8c1f-2a6249d13f35.png)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by noamhurwitz** [comment]
I am seeing this too

**Comment by yants95** [comment]
[SOLVED]

I saw that I did not installed some XCode tools, like cli. After that I remove all files associated to Docker and made a fresh installation and everything runs ok.
