### ISSUE TITLE
[ERROR]  docker-cli cannot find docker

### ISSUE THREAD

**Issue by Afrojazz** [docker/for-mac#437]
### Information

Diagnostic ID: 08100040-A9DD-4492-8978-E79EE1BCFC8D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install Docker for Mac
2. Launch Docker

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 08100040-A9DD-4492-8978-E79EE1BCFC8D/20160827-004230.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.vmnetd][26844] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.vmnetd][26844] <Notice>: User 501 has container folder /Users/aalikulov/Library/Containers/com.docker.docker/Data/s60
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.vmnetd][26844] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.docker][26790] <Error>: Symlinks are not correctly installed.
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.docker][26790] <Notice>: com.docker.osx.hyperkit.linux launched with PID 26847
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][26847] <Notice>: Acquired task manager lock
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.frontend][26846] <Critical>: dial unix /Users/aalikulov/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Aug 27 00:23:14 Arthurs-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][26847] <Notice>: Maximum number of file descriptors is 10240
```
