### ISSUE TITLE
On a fresh install, Docker is stuck at "Docker Desktop is starting". (For > 10 min.)

### ISSUE THREAD

**Issue by imf** [docker/for-mac#4370]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Launching Docker should start the Docker runtime.
### Actual behavior
On a fresh install, Docker is stuck at "Docker Desktop is starting". (For > 10 min.)

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by btspoony** [comment]
I met the same problem.
Containers are running ok, but 'Docker Desktop is starting.'

My Diagnostics ID: 077D9E2A-DB16-409C-A7B8-40E2E182CCD1/20200316075509

macOS Version: 10.15.3 (19D76)
