### ISSUE TITLE
Docker pull shows timeout or service unavailable on mac

### ISSUE THREAD

**Issue by anasmirza-ewebcore** [docker/for-mac#4372]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: E392F3EF-5469-40D7-9C75-02FBFFCB4A2C/20200316123842

### Expected behavior

Pull docker image

### Actual behavior

Show errors

sometimes
`Error response from daemon: Get https://registry-1.docker.io/v2/library/redis/manifests/latest: Get https://auth.docker.io/token?account=anasmirza534&scope=repository%3Alibrary%2Fredis%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

other time
`Get https://registry-1.docker.io/v2/library/redis/manifests/sha256:780f7dacdc133e899fba9ff09c099828b469030acefe6f3bbc16197b55800cfd: Service Unavailable`

### Information

  - macOS Version: macOS Catalina 10.15.3

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. docker pull nginx
  2. docker pull redis

**Comment by anasmirza-ewebcore** [comment]
I tried same command on Ubuntu using same network and it's working.

**Comment by ulrich** [comment]
Thank you for feeback @anasmirza-ewebcore 

It seems maybe related to Docker Hub maintenance, the team works very hard to maintain the high availability.

**Comment by anasmirza-ewebcore** [comment]
Thanks for response @ulrich 

I'm still getting error. Is maintenance completed? can you share any link for tracking status. I didn't see any error on [docker status page](https://status.docker.com/).

**Comment by anasmirza-ewebcore** [comment]
It is working now.
