### ISSUE TITLE
Preferences window stuck at loading step.

### ISSUE THREAD

**Issue by Amit-Thawait** [docker/for-mac#4374]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 977F3D30-BC1E-4951-B467-10A3F19A15F3/20200316111257

### Expected behavior
Preferences window opens up within few seconds.

### Actual behavior
Preferences window doesn't opens up, it gets stuck in loading phase with loading icon.

### Information

  - Did the problem appear with an update? - Yes, but not with this update infact when the new look (current look) came for preferences window.
  - macOS Version: 10.14.4

### Diagnostic logs

```
Docker for Mac: version 2.2.0.4 (43472)

```

**Comment by tekumara** [comment]
Same problem here.

Diagnostics ID: 1D52253A-06BD-4ECA-8188-316BAD9AFDD9/20200621033622

**Comment by tekumara** [comment]
Duplicate of #4063

**Comment by tekumara** [comment]
Preferences will be stuck in the loading state while docker and Kubernetes are starting.

The root cause for me is #4624. 

So I disabled Kubernetes:
```
sed -i '' 's/kubernetesEnabled" : true/kubernetesEnabled" : false/' ~/Library/Group\ Containers/group.com.docker/settings.json
```
and then restarted and the preferences window is no longer stuck loading.
