### ISSUE TITLE
Docker for Mac Desktop stuck in “Updating” state

### ISSUE THREAD

**Issue by jaanus** [docker/for-mac#4375]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2D49CA45-3BFA-4EED-842D-8BBE1E639FE6/20200317121856

### Expected behavior

Docker for Mac Desktop should run and let me interact with it. Menu bar whale icon should show. Troubleshooting actions should work.

### Actual behavior

Docker for Mac Desktop is stuck in “Updating” state. Menu bar whale icon is not showing. Troubleshoot view comes up, but the buttons there don’t do anything. The “About” screen does not show any version numbers.

![ff117a7682e0efb168f2967d5d41611d28638f06](https://user-images.githubusercontent.com/184253/76855834-a272cf80-685a-11ea-998a-c1f6fb4fcae3.jpeg)

### Steps to reproduce the behavior

I just installed Docker freshly. Haven’t done anything much with it. Previously I had Docker running, but I manually removed all the components and then reinstalled.

**Comment by napster235** [comment]
Hi. I have exactly the same problem as you, jaanus.

**Comment by alanwilhelm** [comment]
Same.

**Comment by jaanus** [comment]
Thanks @alanwilhelm. Yes, what worked for me now too, is
1) completely remove Docker - instructoins are here - https://nektony.com/how-to/uninstall-docker-mac
2) install the Edge version.

Shouldn’t stable be more stable than edge 😛

**Comment by napster235** [comment]
I can also confirm that installing the edge version is working for me aswell.

**Comment by jaanus** [comment]
Uhh. Now I run into this same thing with my Edge version that was previously working. Same behavior, stuck in “Updating” state. I don’t understand if it is really doing the update, or just stuck in some weird state, I wish it had some kind of real progress check/indication for the update.

**Comment by lmsurpre** [comment]
Not sure if its the same cause or not, but I saw something similar in my 2.2.0.4 docker desktop for mac install.  In my case I noticed Docker using 100% of a CPU (even though I was running no containers).  I killed it and maybe then did an update (I forget the exact order) and when it came back it was in this "updating..." state.  However, in my case, after another kill/restart it exiting the "updating" state and now shows "running".

**Comment by rominasteinberg** [comment]
It happen the same to me. I had to remove from the Dock the Docker, and it started to work..

**Comment by vvwvin** [comment]
The same bug happened to me on stable channel. Launching from the Dock doesn't work, the dashboard gets stuck on "Updating". Version 2.2.0.5 (43884).
As @rominasteinberg said, removing the Docker icon from the Dock and launching it from Spotlight is a viable workaround.

**Comment by jaanus** [comment]
Oh, this latest insight is very interesting. I can confirm it works the same for me. Starting state: Docker Desktop is not running.

If launching from Dock icon: stuck in "Updating" state as described in the bug

If launching by searching for Docker in Spotlight: everything works as expected.

**Comment by gregoryinouye** [comment]
> Oh, this latest insight is very interesting. I can confirm it works the same for me. Starting state: Docker Desktop is not running.
> 
> If launching from Dock icon: stuck in "Updating" state as described in the bug
> 
> If launching by searching for Docker in Spotlight: everything works as expected.

my docker behavior was the same as @jaanus

**Comment by lewis-kori** [comment]
@jaanus mine too. so weird

**Comment by nevergiveup777** [comment]
yes, it happens to me too and by removing the icon from the Dock and then launching the application from the launch pad menu fixed the issue.

There is a bug with this version that the software never stars and stay in updating state if you launch the app from the Dock menu.

**Comment by martinprojectco** [comment]
> yes, it happens to me too and by removing the icon from the Dock and then launching the application from the launch pad menu fixed the issue.
> 
> There is a bug with this version that the software never stars and stay in updating state if you launch the app from the Dock menu.

Gracias @nevergiveup777

**Comment by jakerobb** [comment]
The Spotlight-not-Dock trick worked for me too. I think this might be because the thing you launch with Spotlight is `/Applications/Docker.app`, whereas the thing that appears in your Dock when you pick Dashboard from the menubar widget is `/Applications/Docker.app/Contents/MacOS/Docker Desktop.app`.

**Comment by jnatschev** [comment]
i too had the same problem. it had been running from the "Dock" and then it didn't. thank you to whomever it was that pointed out the "Dock" problem. Launching Docker Desktop from "Applications" worked fine.

**Comment by jnatschev** [comment]
i quit Docker Desktop. Started it again and set the option to Keep in Dock. Quit Docker Desktop launched from "Dock" and the stuck in "updating" returned. Quit Docker Desktop. Launched from Applications. no problem. running like a charm.

**Comment by jnatschev** [comment]
i believe i worked out what the difference is. launching from Applications launches the docker daemon. launching from "Dock" launches the "Dashboard", which is the GUI and not the docker daemon. if the docker daemon is running you can launch docker desktop no problem. if the docker daemon is not running then the "updating" problem will return.

**Comment by jaanus** [comment]
> i believe i worked out what the difference is. launching from Applications launches the docker daemon. launching from "Dock" launches the "Dashboard", which is the GUI and not the docker daemon. if the docker daemon is running you can launch docker desktop no problem. if the docker daemon is not running then the "updating" problem will return.

That is the same conclusion that several other comments above, and myself, have reached too. It makes sense. If the daemon is not running, then the Dashboard should behave in some more reasonable way than just be stuck in this weird state - it could tell me that the daemon is not running, and/or just launch the daemon in that case.

**Comment by jnatschev** [comment]
my apologies. while read a lot i missed comments saying what i wrote. all good.
yep. i agree.

**Comment by YoungElPaso** [comment]
I'm pretty sure the same thing is happening on Windows 10 as well. Starting from the Start Menu also results in Docker Desktop hanging in 'Updating'.  Turning off everything, then starting from command line also worked in Windows. So this issue seems common to whatever 'launcher' function Docker Desktop uses, regardless of platform.

**Comment by danieltanfh95** [comment]
Confirmed workaround:

1. Remove "Docker" from dock.
2. Start "Docker" from "Applications"

**Comment by jnatschev** [comment]
I can confirm that “Docker Desktop” doesn’t need to be removed from the Dock.

If the “Docker” daemon isn’t running it MUST be started from Applications. Then “Docker Desktop” may be started from the Dock.


Cheers,
John.

**Comment by thevipwan** [comment]
> yes, it happens to me too and by removing the icon from the Dock and then launching the application from the launch pad menu fixed the issue.
> 
> There is a bug with this version that the software never stars and stay in updating state if you launch the app from the Dock menu.

works to me

**Comment by saedyousef** [comment]
> It happen the same to me. I had to remove from the Dock the Docker, and it started to work..

Works for me !!
Thanks, and it's so weird

**Comment by honzabilek4** [comment]
Just confirming the existing issue and the workaround.

**Comment by jeska** [comment]
+1 regarding the workaround, running macOS Catalina V10.15.4! Was prompted to update when Docker started through Spotlight, as well.

**Comment by jaanus** [comment]
Something happened in the freshly released 2.3.0.2.

When I click on the Dock icon:

* When Docker is not running: Docker starts up, as indicated by menu bar whale.
* When Docker is already running: I get this error.

<img width="710" alt="Screenshot 2020-05-20 at 14 38 12" src="https://user-images.githubusercontent.com/184253/82442123-b8de1700-9aa7-11ea-834a-eb2d9e0400b2.png">

Selecting “Dashboard” from the menu bar icon works as expected.

**Comment by jnatschev** [comment]
Ha. That’s hilarious.

I am running 2.3.0.1, the version I used to determine what was going on with the Docker Desktop being launched from the MacOS dock.

I worked that out and all was humming along swimmingly.

How that I have seen your email and decided to give it another go. AND HEY! PRESTO! I got the same message as you posted.

This is weird.

Clearly the behaviour has changed but I don’t know how since I hadn’t upgrade since installing 2.3.0.1, finding that I was getting the “updating” hang, and determining that Docker Desktop (daemon) needs to be started first from /Applications, then use the MacOS dock to open the Dashboard.

Now executing from the MacOS Dock acutally starts the daemon.

How does this work. I wonder whether there was some sort of “update” without updating the version of Docker Desktop.

Who knows.

Thanks for posting though.

I’m laughing my head off.


Cheers,
John

**Comment by jakerobb** [comment]
> Something happened in the freshly released 2.3.0.2.

I'm seeing the same thing here. This has spoiled my plan to launch the Dashboard programmatically. :(

**Comment by jnatschev** [comment]
My MacOS Docker Desktop upgraded to 2.3.1.0 and I can confirm that this new behaviour is maintained.

With the “daemon” not running, starting Docker Desktop from the MacOS dock continues to start the daemon. Attempting to open the Docker Dashboard using Docker Desktop from the MacOS dock results in the message “Docker is already running”.


Weird.



John.

**Comment by jaanus** [comment]
The original problem was about being stuck in “Updated” state, but that is no longer happening. So I am closing this issue.

The “Fatal error” when already running keeps happening, I’ll file another issue about that if it’s not already filed.

**Comment by jaanus** [comment]
There are several bugs about the “fatal error”/“already running” thing, I picked #4680 to follow/comment.
