### ISSUE TITLE
Issue launching docker after install

### ISSUE THREAD

**Issue by cjcdev** [docker/for-mac#4377]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: AC1A0929-D885-428E-A8C3-3A88C2DDE59B/20200317203015
[20200317203015.zip](https://github.com/docker/for-mac/files/4345704/20200317203015.zip)

### Information

  - macOS Version: 10.15.3

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. When launching Docker from (Application folder), the following error occurs:
The operation couldn’t be completed. (Docker.VmnetdError error 1.)
  2. This happens 100% of the time.  

I have uploaded the logs.  Please help resolve this.

**Comment by MrFreezing** [comment]
I see this too

**Comment by cjcoss** [comment]
Nobody, really?

**Comment by cjcoss** [comment]
Somehow this comment fixed the issue:

https://github.com/docker/for-mac/issues/3886#issuecomment-567624817

Notice, just install brew on the system - don't install docker via brew.  What a hack
