### ISSUE TITLE
Docker for mac 1.12.0a never starts

### ISSUE THREAD

**Issue by starrhorne** [docker/for-mac#438]
### Expected behavior

Opening the docker for mac app should start the docker engine. 

### Actual behavior

Docker never starts. I can't connect to it with kitematic or the cli. The toolbar ui says "docker starting" forever. 

### Information

Diagnostic ID: B17A030B-8A10-4D27-B92F-ADA803399409
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Launch the docker for mac app

**Comment by tunerex** [comment]
I having the same issue with same version 1.12.0-a (Build 11213)
@starrhorne Do you mind change the topic into include the version string?

I believe there are multiple reporters regarding this issue, including me.

**Comment by starrhorne** [comment]
Done. FWIW, I was able to get docker to start again by completely uninstalling it -- including all config files, images, etc -- and reinstalling.

**Comment by mchiang0610** [comment]
Merging with #119 

Some users have fixed it by resetting to factory defaults. 
We are looking into the issue.

**Comment by samoht** [comment]
Detected symptom of problem 'daemon-didnt-start' in B17A030B-8A10-4D27-B92F-ADA803399409/20160826-162044.

The docker daemon inside the VM failed to start.

The following log matches:
```
time="2016-08-26T23:08:56.664274698Z" level=debug msg="Failed to load layer sha256:c9b906b1b5d6ee869eb304417b9157f7602d933f7da8c09f6be9cf3ba1b0f9ca: failed to get diff id for sha256:c9b906b1b5d6ee869eb304417b9157f7602d933f7da8c09f6be9cf3ba1b0f9ca: invalid checksum digest format"
time="2016-08-26T23:08:56.702463846Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-26T23:08:56.702827092Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-26T23:08:56.918996539Z" level=debug msg="Cleaning up old mountid : start."
time="2016-08-26T23:08:56.920074940Z" level=fatal msg="Error starting daemon: layer does not exist"
time="2016-08-26T23:09:21Z" level=warning msg="Running experimental build"
time="2016-08-26T23:09:21.922312894Z" level=debug msg="docker group found. gid: 50"
time="2016-08-26T23:09:21.922571884Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
time="2016-08-26T23:09:21.923176901Z" level=info msg="libcontainerd: new containerd process, pid: 1387"
time="2016-08-26T23:09:21.925449354Z" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
```
