### ISSUE TITLE
Can't connect to Docker for Mac from remote client using DOCKER_HOST=ssh://…

### ISSUE THREAD

**Issue by kinghuang** [docker/for-mac#4382]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I have Docker for Mac running, and want to be able to connect to the Docker engine from a remote client. SSH keys have been set up. But, I get an error with this setup because `docker` is not on the path of the remote shell.

```
$ export DOCKER_HOST=ssh://king.huang@khuang-m2296.local
$ docker info
error during connect: Get http://docker/v1.40/nodes: command [ssh -l king.huang khuang-m2296.local -- docker system dial-stdio] has exited with exit status 127, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=bash: docker: command not found
```

```
$ ssh -l king.huang khuang-m2296.local -- docker system dial-stdio
bash: docker: command not found
```

```
$ ssh -l king.huang khuang-m2296.local -- echo '$PATH'
/usr/bin:/bin:/usr/sbin:/sbin
```

```
$ ssh -l king.huang khuang-m2296.local -- /usr/local/bin/docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Actual behavior

The Docker client issues `docker system dial-stdio`, but the `docker` command is not on the path of the session that is created, resulting in `docker: command not found`.

Is there a way to get the client to send a full (or custom) path? Or, start a full shell session for the user so that the user's profile is loaded?

### Information

  - macOS Version: macOS Mojave 10.14.6

### Diagnostic logs

```
Docker for Mac: version 2.2.2.0 (43066)
```

### Steps to reproduce the behavior

1. `export DOCKER_HOST=ssh://your-user@your-docker-for-mac-host`.
2. Attempt to use any Docker command.

**Comment by etherai** [comment]
Here's a workaround:

In `/etc/ssh/sshd_config`:

Change `#PermitUserEnvironment no` to `PermitUserEnvironment yes`

Disable and Re-enable checkbox  next to "Remote Login" in System Preferences > Sharing (to restart sshd)

Create `~/.ssh/environment` with the following contents:

```PATH=$PATH:/usr/local/bin```


export DOCKER_HOST="ssh://user@host" now works as expected!

ref: https://git-annex.branchable.com/forum/OSX__39__s_default_sshd_behaviour_has_limited_paths_set/
