### ISSUE TITLE
Docker fails to provide creds for awslogs logging driver - Failed to initialize logging driver: NoCredentialProviders: no valid providers in chain.

### ISSUE THREAD

**Issue by AusPrinzip** [docker/for-mac#4383]
Not able to set the aws credentials in the docker desktop for mac.
Docker Version : Version 2.0.0.3 (31259)
Mac OS Version : 10.14.2 (18C54)

I have created ~/.aws/credentials files with the aws creds.
aws_access_key_id : XXXXXXX,
aws_secret_access_key" : XXXXXXXX

And in the Docker Daemon file put the aws logging options.
{
"log-driver" : "awslogs",
"log-opts" : {
"awslogs-region" : "xxxx",
"awslogs-group" : "xxxxx",
"awslogs-stream" : "xxxxx"
},

And while running the docker I am getting below error.

docker: Error response from daemon: failed to initialize logging driver: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
ERRO[0010] error waiting for container: context canceled

**Comment by shaloba** [comment]
@AusPrinzip did you manage to solve this issue ? 
Im braking my head here to understand what it the problem
I tried also to set volume for .aws/ directory from my docker host but same error occur

**Comment by AusPrinzip** [comment]
No not yet, pulling my hair since 4 days.

These are the 3 different environments I am dealing with while working on a Mac with docker-machine:

- MacOs environment (Obviously credentials are not being imported from here)
- VM environment (Oracle VirtualBox running boot2docker)
- Container environment (tried mounting .aws/credentials here but did not work)

I will try mounting credentials in VM environment see if that helps. 

If I am not wrong, docker daemon is running on VM environment so mounting AWS creds there could potentially fix it.
