### ISSUE TITLE
Docker Desktop for Mac upgrade and docker-machine

### ISSUE THREAD

**Issue by oivinds** [docker/for-mac#4391]
I just noticed that the docker-machine command all of a sudden stopped working.

> $ docker-machine
> -bash: docker-machine: command not found

Could this be related to a recent Docker Desktop for Mac upgrade?

**Comment by noefroidevaux** [comment]
Yes, see the release notes here: https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2200
