### ISSUE TITLE
200%-300% CPU usage mac book pro, when building gitcoin.web source code

### ISSUE THREAD

**Issue by federicosan** [docker/for-mac#4399]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 58211D3E-4E1B-4CED-BC26-666B2D315EA2/20200326195749

### Expected behavior
No heat, reasonable CPU usage or at least less than 100%
### Actual behavior
Heat so high, docker needs to be shut down to prevent the device hazard
### Information

  - macOS Version: 
macOS Mojave 10.14.6 (18G3020)
Kernel Version: Darwin 18.7.0
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Intel Core i5
  Processor Speed:	2,4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

### Diagnostic logs

```
Docker for Mac: version...

```
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.4, build 8d51620a

### Steps to reproduce the behavior

  1. ... install gitcoin.co/web repo on  https://docs.gitcoin.co/mk_setup/
  2. ... follow the instructions

**Comment by dnguyenv** [comment]
+1 . Has this been fixed in the latest 2.2.0.5?

**Comment by you-think-you-are-special** [comment]
Have the same issue with my project. Docker uses 200%-300% CPU of my Mac and crashes once per week. Think it is related to osxfs. I generated pprof report just before crash 

![profile](https://user-images.githubusercontent.com/2720927/80005679-98349880-84cc-11ea-96a6-4bd5bdd003f8.jpg)


<img width="240" alt="image" src="https://user-images.githubusercontent.com/2720927/80005050-c1a0f480-84cb-11ea-974b-152d364b34e6.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/2720927/80005784-be5a3880-84cc-11ea-9113-ca4a5e58ee41.png">
