### ISSUE TITLE
-v /etc/timezone:/etc/timezone:ro  error

### ISSUE THREAD

**Issue by Irving23** [docker/for-mac#44]
1. echo "Asia/Shanghai" | sudo tee /etc/timezone

2. sudo docker run -d --restart=always --name rancher-server -p 8080:8080 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    rancher/server:v1.0.1

docker: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/14fc257654604475143d99f76554a74c5affe82cfd66a96222780104a083fa9a/etc/timezone" to rootfs "/var/lib/docker/aufs/mnt/14fc257654604475143d99f76554a74c5affe82cfd66a96222780104a083fa9a" caused "not a directory".

docker info

Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 97
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.745 GiB
Name: moby
ID: NPHU:NER7:YRWZ:YGES:2V5M:GDT3:G67F:V3KK:2NMY:AUEQ:JRQ5:K2HV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 44
 System Time: 2016-08-01T07:50:37.620384403Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Comment by dsheets** [comment]
I am not sure why you are running `sudo docker`. `docker` should work fine without `sudo` in Docker for Mac. This is what I see:

```sh
$ docker run --rm  --name rancher-server -p 8080:8080 -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro rancher/server:v1.0.1
docker: Error response from daemon: Mounts denied:
The path /etc/timezone
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
..
```

I don't think OS X uses the `/etc/timezone` file to store timezone information so storing that information elsewhere might make sense. How about `~/etc/timezone`?

**Comment by djs55** [comment]
I created `~/etc/timezone` as @dsheets suggested and then ran (on beta 24)
```
docker run -p 8080:8080 -v ~/etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro rancher/rver:v1.0.1
```
The rancher service started up and I could connect to the web interface. Please reopen if there's still an issue.
