### ISSUE TITLE
crash with macOS beta 6

### ISSUE THREAD

**Issue by jpenyc** [docker/for-mac#440]
### Information

Diagnostic ID: FDD097AC-FA6E-4C40-ADFE-67B67147AC63
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@jpenyc are you still finding this issue with beta 7?

**Comment by jpenyc** [comment]
I am now using Docker Version 1.12.1-beta24 (build: 11525) and it does not come out of start (Docker Starting...)

**Comment by jpenyc** [comment]
I am now using Docker Version 1.12.1-beta24 (build: 11525) and it does not come out of start (Docker Starting...)On Aug 31, 2016, at 10:29 AM, Michael Chiang <notifications@github.com> wrote:@jpenyc are you still finding this issue with beta 7?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-mac","title":"docker/for-mac","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/docker/for-mac" class="">https://github.com/docker/for-mac</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mchiang0610 in #440: @jpenyc are you still finding this issue with beta 7?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/docker/for-mac/issues/440#issuecomment-243782041" class="">https://github.com/docker/for-mac/issues/440#issuecomment-243782041</a>"}}}

**Comment by mchiang0610** [comment]
Beta 25 will have resolved most of the sierra bugs: 

https://download.docker.com/mac/beta/Docker.dmg

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
