### ISSUE TITLE
Docker not working on MacOS (Docker.VmnetdError error 1)

### ISSUE THREAD

**Issue by anietieasuquo** [docker/for-mac#4403]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 235B2E43-D1B6-455F-BB6E-EA77D8B97006/20200329093357

### Expected behavior
Docker should open successfully
### Actual behavior
When opening Docker for desktop it shows Fatal Error The operation couldn’t be completed. (Docker.VmnetdError error 1.)

![image](https://user-images.githubusercontent.com/10789251/77845937-d29f6400-71b2-11ea-841a-505d7647e639.png)

### Information

  - macOS Version: Catalina 10.15.3

### Diagnostic logs

```
Diagnostic ID: 235B2E43-D1B6-455F-BB6E-EA77D8B97006/20200329093357
Docker for Mac: version 19.03.8

```

### Steps to reproduce the behavior

  1. Just launch docker from launchpad
  2. Dialog box shows up with fatal error stated above

**Comment by ulrich** [comment]
Hello @anietieasuquo 

It seems that you cannot display the credential window which prompt your credentials for installing Docker Desktop component (vmnetd).

Can you try to install manually the component by this way : 
`/bin/sh -c "sudo /Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components"`

**Comment by anietieasuquo** [comment]
@ulrich Thanks for responding.
However, after installing the privileged components manually using the command you provided, the issue still persists.

I've also tried to reset docker to factory defaults, but still no luck. Any other ideas?

**Comment by ulrich** [comment]
Did you have the message which indicate the success of the command in the console or not?

**Comment by anietieasuquo** [comment]
Yes I got the message, see attached.
![image](https://user-images.githubusercontent.com/10789251/78171442-b589c000-7454-11ea-80a1-c97c84b711c2.png)

**Comment by ulrich** [comment]
I seen others errors in the logs. Did you successfully ran docker desktop before on this computer?

**Comment by anietieasuquo** [comment]
> I seen others errors in the logs. Did you successfully ran docker desktop before on this computer?

No, I don't think so.

**Comment by ulrich** [comment]
@anietieasuquo I will try to grab informations from the team.

**Comment by anietieasuquo** [comment]
> @anietieasuquo I will try to grab informations from the team.

Ok, looking forward to hearing from you :)

**Comment by ulrich** [comment]
Sorry, no response for now.

**Comment by ajmulcahy** [comment]
i just hit the same error, any update?

**Comment by ramyfrahman** [comment]
Ditto.  Frustrating.  I've read elsewhere that SIP needs to be disabled.

**Comment by anietieasuquo** [comment]
@ramyfrahman I disabled SIP, restarted the system, uninstalled and re-installed docker, still not working. Any other ideas?

**Comment by ramyfrahman** [comment]
I got nothing.  Install docker in an Ubuntu VM

**Comment by ngougane** [comment]
i had same problem. 
I try this https://codingbee.net/docker/install-docker-for-mac-using-homebrew
And it work

**Comment by sushmasuresh28** [comment]
I had the same issue. I uninstalled Docker and followed the steps on this link-  https://codingbee.net/docker/install-docker-for-mac-using-homebrew

This worked perfectly

**Comment by anietieasuquo** [comment]
Thanks @ngougane and @sushmasuresh28 

I finally got it working following https://codingbee.net/docker/install-docker-for-mac-using-homebrew

But first I had to completely uninstall docker from my mac. It involved removing every trace of docker from `/usr/library/*` folders.. took a while.
