### ISSUE TITLE
SocketCAN & vcan support

### ISSUE THREAD

**Issue by Clovel** [docker/for-mac#4405]
# Description

We cannot use SocketCAN's VirtualCAN bus (`vcan`) on a Linux Docker container w/ Docker for Mac.

  - [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 89E9BCA8-017A-40D1-87D8-96AEE42A5920/20200329194010

# Rationale
One of the many advantages of Docker for macOS is to be able to test Linux related code and features without requiring the need of a full fledged VM (Parallels, VMWare, Virtual Box) and having a lightweight Linux running while we can develop our projects. 

One feature I would like to have on my Mac is SocketCAN. As it or a alternative is sadly unavailable for macOS, I would like to test my programs with VirtualCAN (`vcan`). 

The Linux Kernel used by Docker for Mac - LinuxKit if I understand correctly - is not compiled with the CAN related configuration flags. This should be addressed. 

# Expected behavior
Linux Kernel (LinuxKit) should have the following configuration flags for a (near) full CAN protocol support : 
```config
#
# CAN Bus support
#

CONFIG_CAN=m
CONFIG_CAN_RAW=m
CONFIG_CAN_BCM=m
CONFIG_CAN_GW=m

#
# CAN Device Drivers
#
CONFIG_CAN_VCAN=m
CONFIG_CAN_SLCAN=m
CONFIG_CAN_DEV=m
CONFIG_CAN_CALC_BITTIMING=y
CONFIG_CAN_MCP251X=m
CONFIG_PCH_CAN=m
CONFIG_CAN_SJA1000=m
CONFIG_CAN_SJA1000_PLATFORM=m
CONFIG_CAN_EMS_PCMCIA=m
CONFIG_CAN_EMS_PCI=m
CONFIG_CAN_PEAK_PCI=m
CONFIG_CAN_KVASER_PCI=m
CONFIG_CAN_PLX_PCI=m
CONFIG_CAN_C_CAN=m

#
# CAN USB interfaces
#
CONFIG_CAN_EMS_USB=m
CONFIG_CAN_ESD_USB2=m
CONFIG_CAN_SOFTING=m
CONFIG_CAN_SOFTING_CS=m
# CONFIG_CAN_DEBUG_DEVICES is not set
```

For a more streamlined and lightweight approach, maybe this could suffice : 
```config

#
# CAN Bus support
#

CONFIG_CAN=m
CONFIG_CAN_RAW=m
CONFIG_CAN_BCM=m
CONFIG_CAN_GW=m

#
# CAN Device Drivers
#
CONFIG_CAN_VCAN=m
CONFIG_CAN_DEV=m
```

# Actual behavior
Modules are not available. The following setup commands are not possible : 
```bash
$ modprobe vcan
$ sudo ip link add dev vcan0 type vcan
$ sudo ip link set up vcan0
```

# Information
  - macOS Version: macOS Catalina 10.15.4 19E266 x86_64
  - Is it reproducible: Yes. Take an Alpine/Debian/Ubuntu docker image, install can-utils (with a package manager or by compiling from [source](https://github.com/linux-can/can-utils.git))
  - Is the problem new : No, I tried this before, in early 2019.
  - Did the problem appear with an update : I do not think so. 

# Steps to reproduce the behavior

  1. Use this `Dockerfile` : 
```dockerfile
# Source image ----------------------------------
FROM alpine:latest

# Update package manager ------------------------
RUN apk update
RUN apk upgrade
# Update/install packages -----------------------
RUN apk add --no-cache \
linux-headers \
dumb-init \
musl \
bash \
ca-certificates \
git \
wget \
curl \
tar \
unzip \
coreutils \
gcc \
gdb \
cmake \
make \
pkg-config \
doxygen \
graphviz \
openssh \
net-tools \
vim \
nano \
python3 \
python3-pip

RUN apt install -y can-utils

# Install pip3 packages
RUN pip3 install --no-cache --upgrade pip setuptools wheel && \
if [[ ! -e /usr/bin/pip ]]; then \
    ln -s pip3 /usr/bin/pip; \
fi
RUN pip3 install --no-cache canopen
``
  2. Attempt to load the `vcan` kernel module
```bash
$ modprobe vcan
```
  3. Get the following error (not copy pasted, I am away from my dev machine) :
```bash
modprobe: ERROR: ../libkmod/libkmod.c:XXX kmod_search_moddep() could not open moddep file '/lib/modules/4.19.76-linuxkit/modules.dep.bin' modprobe:
  FATAL: Module vcan not found in directory /lib/modules/4.19.76-linuxkit
```

# Action
I will submit a PR to the LinuxKit repository to try and have this feature merged. 
**EDIT** : I submitted the PR : linuxkit/linuxkit#3486. I am currently trying to test this on macOS, but I am having some [difficulties](https://github.com/linuxkit/linuxkit/issues/3485#issuecomment-605711047).

# Side notes
This issue seems to have been under discussion over at the LinuxKit repository : 
- linuxkit/linuxkit#3172 : Issue on LinuxKit to add CAN support
- linuxkit/linuxkit#3173 : PR for linuxkit/linuxkit#3172 + Discussion of adding the needed configuration flags
- linuxkit/linuxkit/issues/3485 : The issue I opened.

I saw others were having similar difficulties with the SCTP protocol kernel module. I believe a fix was [merged in LinuxKit](https://github.com/linuxkit/linuxkit/pull/3025).
- [docker/for-mac](https://github.com/docker/for-mac/) : 
  - #3016 : Enable SCTP protocol as a default kernel config
- Docker forums : 
  - ["Add sctp kernel module to the Hyperkit Alpine VM"](https://forums.docker.com/t/add-sctp-kernel-module-to-the-hyperkit-alpine-vm/31292)

**Comment by ulrich** [comment]
Hello @Clovel 

This is a misconfiguration LinuxKit side only, no?

**Comment by Clovel** [comment]
Hello @ulrich. It does seem so for the "code" part. Yet merging this functionality in the default kernel used by Docker for Mac is up to the Docker community. And the issue I have comes from using docker for Mac, hence why I submitted an issue here.

**Comment by ulrich** [comment]
OK, so the feature is already enabled in LinuxKit and it is not available in docker desktop. Is it that? Thx!

**Comment by Clovel** [comment]
No, it is not yet included. I submitted a PR over at linuxkit : https://github.com/linuxkit/linuxkit/pull/3486.

**Comment by Clovel** [comment]
I am currently trying to make this work, but am having difficulties. I post my progress and my issues over at https://github.com/linuxkit/linuxkit/pull/3486.

**Comment by ulrich** [comment]
So, when the feature will be fully include in LinuxKit so Docker Desktop will support it.

**Comment by Clovel** [comment]
> So, when the feature will be fully include in LinuxKit so Docker Desktop will support it.

I think so.

**Comment by Willcampbellmelb** [comment]
@Clovel are you waiting for LinuxKit to approve your changes or still working out a solution?

**Comment by Clovel** [comment]
Hi @Willcampbellmelb. As my last comment on https://github.com/linuxkit/linuxkit/pull/3486 states, I can’t even build the kernel with the appropriate build steps. I got no answer to my plea for help, so I guess I’m stuck. 

I reported my steps, platform and results to either this issue or (mainly) the PR linked in this comment.

**Comment by Clovel** [comment]
This issue is LinuxKit related, but the associated LinuxKit issue has not yet been closed. This issue can be either closed or set to pending.
