### ISSUE TITLE
6EF149F5-42A1-4498-BBE6-1AF9FC6557FC/20200330040927

### ISSUE THREAD

**Issue by dianawang-git** [docker/for-mac#4406]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you provide more details about your trouble please ?
