### ISSUE TITLE
docker fatal error 664F76AC-34A2-4318-B536-F8C11EFAA372/20200331003117

### ISSUE THREAD

**Issue by edenparker11** [docker/for-mac#4407]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you provide more details about your trouble please ?
