### ISSUE TITLE
C31F5F5F-A7AA-4793-9C08-51E4EE38CE17/20200331200615

### ISSUE THREAD

**Issue by jdelis048** [docker/for-mac#4409]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you provide more details about your trouble please ?
