### ISSUE TITLE
94312B2D-2405-4110-9E43-FD9ACC4187E8/20200331211855

### ISSUE THREAD

**Issue by AliMiraftab** [docker/for-mac#4411]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 94312B2D-2405-4110-9E43-FD9ACC4187E8/20200331211855

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you provide more details about your trouble please ?
