### ISSUE TITLE
5C949448-0B91-4C7C-AFC5-4445289A5FE0/20200401072809

### ISSUE THREAD

**Issue by hamzabekhtaoui** [docker/for-mac#4412]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Can you provide more details about your trouble please ?
