### ISSUE TITLE
Listening on `[::]:9000` stopped working

### ISSUE THREAD

**Issue by hhoechtl** [docker/for-mac#4415]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Starting a container with PHP-FPM and the following configuration worked until now:

```
listen = [::]:9000
```

### Actual behavior

Now it get the following error:

```
ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)
```

Also Postfix is showing errors:

```
[SYSLOG] postfix/postalias[114]: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
```

### Information

  - macOS Version: 10.15.4 (19E266)
  - Docker for Mac: 2.2.3.0 (43965) edge
  - Problem occurs since updating to 2.2.3.0

### Troubleshooting

I already tried setting `ipv6: true` or `ipv6: false` in the `daemon.json` but it had no effect.

**Comment by stephen-turner** [comment]
Thanks for the report, @hhoechtl. You're right, we're not parsing the address correctly. We'll fix it before this code reaches Stable. Thanks for finding it on Edge!

**Comment by hhoechtl** [comment]
@stephen-turner I would highly appreciate if you could release a 2.2.3.1 with a fix, because downgrading to the stable branch comes with a complete data loss.

**Comment by stephen-turner** [comment]
We probably won't do another official release until we have enough content as that will prompt everyone on Edge to install it again. But we can attach a private build to this ticket once we have a fix.

**Comment by hhoechtl** [comment]
That would be awesome. Thank you very much.

Stephen Turner <notifications@github.com> schrieb am Do., 2. Apr. 2020,
19:09:

**Comment by djs55** [comment]
If you have time to try it, I've got an early development build based on edge with IPv6 working again: [win](https://download-stage.docker.com/win/edge/44007/Docker%20Desktop%20Installer.exe) and [mac](https://download-stage.docker.com/mac/edge/44007/Docker.dmg) 2.2.3.0 (44007) . Let me know if it works better for you or not. Sorry for the inconvenience this issue has caused.

**Comment by hhoechtl** [comment]
Yes it works. Thank you so much.

**Comment by CUCraigT** [comment]
Likewise, I was having a similar issue and this fixed it. For me, I was simply trying to run a MSSQL container bound to port 1433. After the main upgrade, I ran into issues where it never bound.

**Comment by kpm-at-hfi** [comment]
Post-upgrade to 2.2.3.0 (43956) I'm not able to start up my previously working container for dpage/pgadmin4:latest which used to work fine at http://localhost:15432/browser/ but now gives me this in the logs:

```
[2020-04-09 17:20:04 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-04-09 17:20:04 +0000] [1] [ERROR] Retrying in 1 second.
[2020-04-09 17:20:05 +0000] [1] [ERROR] Retrying in 1 second.
[2020-04-09 17:20:06 +0000] [1] [ERROR] Retrying in 1 second
[2020-04-09 17:20:07 +0000] [1] [ERROR] Retrying in 1 second.
[2020-04-09 17:20:08 +0000] [1] [ERROR] Retrying in 1 second.
[2020-04-09 17:20:09 +0000] [1] [ERROR] Can't connect to ('::', 80)
```

Same issue? Anything I can do?

**Comment by djs55** [comment]
@kpm-at-hfi thanks for your report. Could you try the testing build ([win](https://download-stage.docker.com/win/edge/44007/Docker%20Desktop%20Installer.exe) and [mac](https://download-stage.docker.com/mac/edge/44007/Docker.dmg)) 2.2.3.0 (44007) and let me know if it's any better? If not, could you describe your setup a bit more -- if I can reproduce it it'll be much easier to fix. Thanks in advance!

**Comment by kpm-at-hfi** [comment]
Thanks for the speedy response. It's verified working with 44007. Cheers!
