### ISSUE TITLE
Kubernetes not starting

### ISSUE THREAD

**Issue by stefaneg** [docker/for-mac#4418]
Kubernetes is not starting, hangs forever on "Kubernetes is starting..."

Installed new version of docker desktop this morning, have also tried resetting Kubernetes in settings, no no avail.

Have not gone the whole way uninstalling and reinstalling docker desktop.

Diagnostics ID:
1802AC81-E942-49CF-81D8-75F8FD16EF94/20200403160502

**Comment by yingtao** [comment]
This looks like the same issue with issue #4419 which I pasted the diagnostics as well.
