### ISSUE TITLE
Switch between Stable and Edge versions

### ISSUE THREAD

**Issue by JCzz** [docker/for-mac#4421]
From here the documentation states, that you can switch between stable and edge - but how, Is uninstall and then install switching?

https://docs.docker.com/docker-for-mac/install/#switch-between-stable-and-edge-versions

**Comment by stephen-turner** [comment]
The document you pointed to has the answer: "To safely switch between Edge and Stable versions, ensure you save images and export the containers you need, then uninstall the current version before installing another."
