### ISSUE TITLE
kubernetes can not running ? (shit!!!!!!!!!!!!!!!!Can no one help solve this problem？>>>>>>>>>>)

### ISSUE THREAD

**Issue by guomaoqiu** [docker/for-mac#4426]
MAC VERSION: 10.15.4 Catalina
DOCKER ENGINE VERSION: 19.03.8
DOCKER DESTOP VERSION: 2.2.0.5(stable)
![image](https://user-images.githubusercontent.com/9714859/78621444-2c8be200-78b5-11ea-8275-a8f2d7ee7055.png)
![image](https://user-images.githubusercontent.com/9714859/78621487-47f6ed00-78b5-11ea-9724-9382e071f334.png)
![image](https://user-images.githubusercontent.com/9714859/78621535-6a890600-78b5-11ea-90af-bd8f94bc81ce.png)
![image](https://user-images.githubusercontent.com/9714859/78621565-7a084f00-78b5-11ea-9a0b-a1d2873a4f75.png)

**Comment by guomaoqiu** [comment]
always  starting status....
![image](https://user-images.githubusercontent.com/9714859/78621787-0155c280-78b6-11ea-9578-ccd5b134e4ca.png)

**Comment by guomaoqiu** [comment]
Can no one help solve this problem？

**Comment by guomaoqiu** [comment]
???????????????????????

**Comment by guomaoqiu** [comment]
shit!

**Comment by ulrich** [comment]
Hello @guomaoqiu 

Is it related to your location? In fact the Kubernetes components are not always accessible from some countries...
