### ISSUE TITLE
Fatal Error: Docker.app crashing every time 

### ISSUE THREAD

**Issue by vigneshraaj** [docker/for-mac#4428]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I open Docker for Mac, it keeps running in the background

### Actual behavior
When I open Docker for Mac, I run in the background. After a few minutes, the application crashes with the following FATAL Error:
> Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9``

### Information

  - Its reproducible everytime
  - The problem started when I upgraded to new version
  - macOS Version: Catalina, 10.15.3

### Diagnostic logs

```
Docker for Mac: 2.2.0.5

```

### Steps to reproduce the behavior

  1. Goto Applications
  2. Open Docker.app
  3. Wait for a few mins

**Comment by bielesibub** [comment]
I keep getting the same error message on Catalina, 10.5.3 

<for a very short time I am able to get to docker via the command line>
docker -v == "Docker version 19.03.8, build afacb8b"

If I select the docker in the menu bar, I get the spinning icon then the message, Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9 appears.

**Comment by vigneshraaj** [comment]
After updating mac to 10.15.4 the issue got fixed
