### ISSUE TITLE
Fatal error when trying to start Docker after installation

### ISSUE THREAD

**Issue by mpej** [docker/for-mac#4432]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BEEB33AC-D2D0-40F0-AB5E-BBFBECECF9AC/20200408030107

### Expected behavior
Docker Desktop starts successfully
### Actual behavior
Docker shows fatal error
com.docker.backend cannot start
Exit code 1
When I reset to factory defaults, the same thing happens. I have tried uninstalling, removing all related files, restarting my laptop.
### Information

  - macOS Version: 10.15.4 

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Download Docker Desktop from Docker hub
  2. Follow installation instructions
  3. Attempt to start application

**Comment by mpej** [comment]
Current workaround: version 2.0.0.3 works. I had to fix a spelling mistake in `~/.docker/config.json` to get this version working. Changed `"credSstore" : "osxkeychain"` to `"credsStore" : "osxkeychain"`

If there is a solution to get the most recent version working, I would love to know :)

**Comment by ted107mk** [comment]
This is happening to me as well, although the workaround was slightly different for me, I needed to follow the steps at https://github.com/docker/docker-credential-helpers/issues/149#issuecomment-566832756

FYI 2.0.0.3 for macOS is available here: https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-2003-2019-02-15

**Comment by remmah** [comment]
I encountered this issue. The problem was that my CPU's VT-x virtualization extensions were disabled in my motherboard's EFI/BIOS — enabling it allowed Docker Desktop to launch properly.
