### ISSUE TITLE
System credentails dialog looks spooky (german localization)

### ISSUE THREAD

**Issue by mcguffin** [docker/for-mac#4436]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The opposite of the follwing paragraph.

### Actual behavior
The Confirmation Button in the system credentials dialog is lacking a proper label. As a result the dialog looks everthing else than trustworthy:
<img width="465" alt="grafik" src="https://user-images.githubusercontent.com/402988/78772062-7518cd80-7991-11ea-8a35-e1f657756d73.png">

### Information

  - macOS Version: 10.14.6 (de_DE locale)

### Diagnostic logs

```
Docker for Mac: 2.2.0.5

```

### Steps to reproduce the behavior

  1. Download form hub.docker.com
  2. install and run it for the first time
  3. enjoy the dialog

**Comment by StefanScherer** [comment]
You can read more details about this here https://github.com/moby/moby/issues/39648#issuecomment-518192195

It's sad that it still appears from time to time or on specific machines, but be assured we don't create our own password dialog here. Instead we use the system one that sometimes has problems showing a nice aligned button.

Nothing we can do to fix that, so I'm going to close this issue.
