### ISSUE TITLE
/sys/fs/bpf not mounted

### ISSUE THREAD

**Issue by errordeveloper** [docker/for-mac#4454]
This prevents one from running Cilium, or other system software that relies on BPF.

```
$ # bind-mounts don't work
$ docker run -v /sys/fs/bpf:/sys/fs/bpf alpine mount | grep /sys/fs/bpf
sysfs on /sys/fs/bpf type sysfs (rw,nosuid,nodev,noexec,relatime)
$ # it's not mounted in host mount namespace either
$ docker run --privileged --pid=host alpine nsenter -t1 -m mount | grep /sys/fs/bpf
$ # it's not in fstab
$ docker run --privileged --pid=host alpine nsenter -t1 -m mount /sys/fs/bpf 
mount: /sys/fs/bpf: can't find in /etc/fstab.
$ # it can be mounted on the host
$ docker run --privileged --pid=host alpine nsenter -t1 -m -- mount bpffs /sys/fs/bpf -t bpf
$ and all works as expect as far as the host mount is concerned
$ docker run --privileged --pid=host alpine nsenter -t1 -m -- mount | grep bpf             
bpffs on /sys/fs/bpf type bpf (rw,relatime)
$ # however bind-mounts still don't work
$ docker run -v /sys/fs/bpf:/sys/fs/bpf alpine mount | grep /sys/fs/bpf            
sysfs on /sys/fs/bpf type sysfs (rw,nosuid,nodev,noexec,relatime)
$
```

/cc @justincormack

**Comment by errordeveloper** [comment]
It's not mounted in kubelet's mount namespace either:

```
$ kubelet_pid="$(docker run --privileged --pid=host alpine pidof kubelet)"
$ docker run --privileged --pid=host alpine nsenter -t${kubelet_pid}  -m --  mount| grep /sys/fs/bpf
$
````

**Comment by errordeveloper** [comment]
I was able to make bind mounts work in docker by mounting `/sys/fs/bpf` inside the mount namespace of docker's instance of containerd.
```
$ docker run --privileged --pid=host alpine nsenter -t1534 -m -- mount bpffs /sys/fs/bpf -t bpf 
$ docker run -v /sys/fs/bpf:/sys/fs/bpf alpine mount |  grep /sys/fs/bpf
bpffs on /sys/fs/bpf type bpf (rw,relatime)
$
```
This is a very complicated work-around, one shouldn't have to do this in order to get BPF working in a container.

**Comment by errordeveloper** [comment]
I'd be happy to test out any edge build, I think this should be a fairly easy fix to implement.

**Comment by skurfuerst** [comment]
FYI: I've used the tricks explained here to run Cilium on k3s via k3d (inside Docker for mac). The explanation can be found at https://sandstorm.de/de/blog/post/running-cilium-in-k3s-and-k3d-lightweight-kubernetes-on-mac-os-for-development.html - thank you for the hints 👍

**Comment by errordeveloper** [comment]
I just checked in v20.10.0, and this still appears to be the case. It's unfortunate that having Kubernetes built-in Docker for Desktop is becoming less and less useful.

**Comment by skurfuerst** [comment]
@errordeveloper to clarify: I have not used the Kubernetes built-in docker here; and IMHO the issue I've described has nothing to do with the Docker folks, but needs to be solved in Cilium :)

**Comment by errordeveloper** [comment]
@skurfuerst I have reported this as a general issue that blocks usage of any BPF-based project on Docker for Desktop, the point is that the OS should simply mount `/sys/fs/bpf` on boot, there is no way for the user to configure and make such configuration persist on reboots and upgrades. That being said, there may exist any other bugs whether in Cilium or other projects that need to consume `/sys/fs/bpf` on Docker for Mac. This issue is simply about making `/sys/fs/bpf` mounted out of the box.

**Comment by errordeveloper** [comment]
@skurfuerst also, my comment with regard to latest Docker for Desktop release was not related to your comment at all, you just reminded me to get back to this issue :)

**Comment by skurfuerst** [comment]
ah I see @errordeveloper - thanks for clarifying :) ❤️

**Comment by Drivez** [comment]
any news on this?

**Comment by djs55** [comment]
@errordeveloper (and everyone!) sorry for the delay. I'm planning on looking at this soon (eBPF seems really interesting!) Thanks for https://github.com/linuxkit/linuxkit/pull/3516 -- perhaps we simply need to update `pkg/init`. I'll investigate.

**Comment by djs55** [comment]
@errordeveloper I've got a prototype which uses the new `init` (thanks again) and exposes `/sys/fs/bpf` to the container running `dockerd` and Kubernetes. I've smoke-tested it as follows:
```
dave@m1 ~ % docker run -it -v /sys/fs/bpf:/sys/fs/bpf alpine sh
/ # ls /sys/fs/bpf
/ # mount | grep bpf
none on /sys/fs/bpf type bpf (rw,nodev,relatime)
/ # 
```
If you'd like to try it, here's a download: https://desktop-stage.docker.com/mac/main/amd64/70814/Docker.dmg (replace `amd64` with `arm64` if you're an M1 owner). The build isn't notarised so macOS will complain and ask you to open via Finder.

**Comment by faisal-memon** [comment]
Thanks @djs55, your build worked for me. Are there any plans for this to be part of a regular release?

**Comment by almereyda** [comment]
Yes, running Cilium with enabled eBPF-support, given that the technology is gaining a lot of traction lately, in Kubernetes clusters on Docker for Mac would be very much appreciated.

**Comment by errordeveloper** [comment]
@djs55 looks like we forgot to close this one, so closing now, as `/sys/fs/bfs` does mount exist sicnce a few Docker Desktop releases.
