### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by adedotunbashorun** [docker/for-mac#4455]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
I'm closing this ticket because it doesn't include any information about the problem. If you are still having problems, please open a new ticket with exact symptoms and a diagnostics id.
