### ISSUE TITLE
Kubernetes does not start

### ISSUE THREAD

**Issue by dcoder2099** [docker/for-mac#4458]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A83CA41A-9DF9-45BB-8465-B2155D0C41D9/20200415173827

### Expected behavior

Kubernetes starts and runs.

### Actual behavior

Kubernetes never starts.

### Information

  - macOS Version: 10.15.4
  - Docker for Mac: 2.2.0.5
  - Kubernetes had never been enabled prior
  - Can no longer adjust settings -- it's just hung on spinner.

**Comment by presich** [comment]
Same stuff, in the system.log I have:
`Apr 28 14:37:46 tkepczyn-vm02 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.13714): Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
Apr 28 14:37:54 tkepczyn-vm02 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.13740): Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
Apr 28 14:37:54 tkepczyn-vm02 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.com.docker.hype.13741): Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory`

**Comment by dcoder2099** [comment]
FYI, when I upgraded to Docker Desktop edge (2.2.3.0), which is Engine 19.03.8 and Kubernetes 1.16.5, K8s was able to start and operate normally.

So, if you wanna roll those dice, use the edge channel.

**Comment by sc250024** [comment]
I have the same issue. Diagnostic ID `A3CB4CA2-573B-477E-AC16-A0DB145C09D1/20200430084002` if it helps. Thank you!

**Comment by dcoder2099** [comment]
I downloaded the latest Stable channel release (2.3.03) and although it took _forever_, Kubernetes did eventually start up. This appears to be resolved.
