### ISSUE TITLE
Can't save docker engine configuration json

### ISSUE THREAD

**Issue by xiebruce** [docker/for-mac#4473]
- [x] I have tried with the latest version of my channel (I don't know Stable or Edge, I download it [here](https://hub.docker.com/editions/community/docker-ce-desktop-mac/?tab=resources))
![image](https://user-images.githubusercontent.com/13575500/79636005-568faf00-81a7-11ea-876c-3ee0dc3a49ca.png)

  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `9A0AE59E-BF89-4349-A598-965CD54227C7/20200418102543`

### Expected behavior
save configuration to `settings`→`Docker Engine`:
![image](https://user-images.githubusercontent.com/13575500/79635378-14fd0500-81a3-11ea-9a83-4f63139eaf44.png)

### Actual behavior
can't save the json that I input

### Information

 - Is it reproducible? 
Yes, it's reproducible every time, no matter I reboot docker, reboot macOS or reset disk image, reset to factory defaults, it just can't save.
- Did the problem appear with an update?
No, I haven't update docker for mac, I just download it in recent days.
  - macOS Version: `10.14.4`

### Diagnostic logs

```
Docker for Mac: version 2.2.0.5

```

### Steps to reproduce the behavior

  1. click docker icon in the menu bar
  2. click `Preferences`
  3. click `Docker Engine`
  4. input configuration:
```json
{
	"experimental": false,
  	"debug": true,
  	"registry-mirror": [
    	"https://4cysnbna.mirror.aliyuncs.com",
    	"http://f1361db2.m.daocloud.io"
  	]
}
```

 5. click `Apply & restart`
 6. click close button (`x` ) on the top left of the setting screen
 7. click setting(gear icon)
 8. click `Docker Engine`

the you can see the json you save just now is gone.

**Comment by InSecker** [comment]
I report the same issue here, but on the `Ressources` tab.

I tried to install MacOS Catalina ( just to solve this ) , and still no result.

MacOS 10.15.4
Docker Desktop 2.2.0.5

**Comment by xiebruce** [comment]
`/remove-lifecycle stale`
