### ISSUE TITLE
/events API Endpoint Should Separate JsonObjects

### ISSUE THREAD

**Issue by amihaiemil** [docker/for-mac#4474]
- [X] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Docker Server should send some separator between the ``/events`` JSON Objects
### Actual behavior
Docker Server sends the JSONs one after another. The following are 2 docker ``pull`` events, which were sent by the server one after another without any separator (newline added by me for readability):

```json
{"status":"pull","id":"ubuntu:latest","Type":"image","Action":"pull","Actor":{"ID":"ubuntu:latest","Attributes":{"name":"ubuntu"}},"scope":"local","time":1587233840,"timeNano":1587233840345201553}

{"status":"pull","id":"hello-world:latest","Type":"image","Action":"pull","Actor":{"ID":"hello-world:latest","Attributes":{"name":"hello-world"}},"scope":"local","time":1587233845,"timeNano":1587233845411445535}
```
### Information

  - macOS Version: ``10.14.6``
  - Docker for Mac, Engine ``19.03.8``, API version ``1.40``.

### Steps to reproduce the behavior
1. Start Docker, then run the following CURL command in a terminal:

```shell
curl --no-buffer -XGET --unix-socket /var/run/docker.sock http://v1.40/events
```

2. Open another terminal and run some commands that generate events. For instance, the following two commands:

```shell
docker pull hello-world
docker pull ubuntu
```

3. Back in the first terminal, you will see that CURL has printed the received JSON objects without any separator between them.

A separator between the sent objects would be beneficial for the clients. I personally have a Java Client and I am basically parsing the incoming InputStream blindly, because I can't really know where one packet ends and where the next one begins.

**Comment by stephen-turner** [comment]
This does not look like an issue with Docker for Mac, but with the upstream Docker Engine. Could you please open the ticket in the moby/moby project instead? (Sorry, I would move it if I could, but it's not possible because it's not even in the docker org). Thank you.
