### ISSUE TITLE
$SSH_AUTH_SOCK is not being forwarded

### ISSUE THREAD

**Issue by MacFlurry** [docker/for-mac#4477]
Sorry for reopening this, but, the solution provided on the previous issue is not working.

> I have Docker for mac (version 2.2.0.5) stable version
> macOS  Catalina 10.15.4

This is my ansible inventory:

```
[group1]
xx.xx.xx.xx

[group2]
xx.xx.xx.xx ansible_port=811

[vps:children]
group1
group2

[vps:vars]
ansible_ssh_user=myuser
ansible_ssh_private_key_file=/root/.ssh/myKey_rsa
```
I tried first this :

```
$ ssh-add ~/.ssh/myKey_rsa
Identity added: ...
```

then I ran:
```
$ docker run --rm -it \
	-v ~/.ssh:/root/.ssh \
	-v ${HOME}/Documents/personal_server/:/ansible/ \
	-v "$SSH_AUTH_SOCK":"/run/host-services/ssh-auth.sock" \
	-e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" \
	-e HOST_KEY_CHECKING=False \
	cytopia/ansible:latest-infra ansible vps -i /ansible/myinventory -b -m ping

```
Still asking for passphrase, despite I ssh-added it earlier.

> [INFO] root> ansible vps -i /ansible/myinventory -b -m ping
> Enter passphrase for key '/root/.ssh/myKey_rsa': Enter passphrase for key '/root/.ssh/myKey_rsa':

I also tried:

```
docker run --rm -it \
	-v ~/.ssh:/root/.ssh \
	-v ${HOME}/Documents/personal_server/:/ansible/ \
	-v "$SSH_AUTH_SOCK":"/root/$(basename $SSH_AUTH_SOCK)" \
	-e SSH_AUTH_SOCK="/root/$(basename $SSH_AUTH_SOCK)" \
	-e HOST_KEY_CHECKING=False \
	cytopia/ansible:latest-infra ansible vps -i /ansible/myinventory -b -m ping
```
no way, still asking for passphrase.

Could someone help on this ?

**Comment by zedtux** [comment]
Please have a look at #410 and @guillaumerose's solution which works fine.

**Comment by MacFlurry** [comment]
thanks @zedtux
