### ISSUE TITLE
844F611E-18D2-4D61-B8E9-72E978F81056

### ISSUE THREAD

**Issue by eaiero** [docker/for-mac#448]
### Information

Diagnostic ID: 844F611E-18D2-4D61-B8E9-72E978F81056
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/eqielb/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/844F611E-18D2-4D61-B8E9-72E978F81056/20160829-100453/qemu-img-check.stdout 2> /tmp/844F611E-18D2-4D61-B8E9-72E978F81056/20160829-100453/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
