### ISSUE TITLE
Docker impacting lag to whole process of mac and error on running daemon

### ISSUE THREAD

**Issue by bobbiprathama** [docker/for-mac#4483]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: ECD3D7EB-B989-418D-85C3-28E233E3EB2A/20200422020518

### Expected behavior
Run well and no lag.

### Actual behavior
"Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory".

### Information

  - macOS Version:
```
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion: 19D76
```

### Diagnostic logs

```
Docker for Mac: version...
Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
```

### Steps to reproduce the behavior

  1. When first install docker, got lag on whole of device when docker run. 
  2. Then I restart (or shutdown). After I restart/ shutdown mac, got error that suggest to reset factory. After reset factory, got error on daemon running "Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory".

**Comment by ycrepeau** [comment]
Same here, except Mac OSX 10.15.5

It has worked for few days but after the Mac crashed (in the middle of the night), it never started again. I’ve uninstalled/installed again Docker Desktop app, erased any artifact left in my home directory, reset hard disk, reset to factory settings (more than once), nothing works.
