### ISSUE TITLE
System clock performance issue

### ISSUE THREAD

**Issue by jrouviere** [docker/for-mac#4486]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2825FC6C-7672-42B2-8BCF-981C87A835DC/20200424092122

### Expected behavior

Reading system clock from a container normally takes around 50ns.

### Actual behavior

Reading system clock takes around 15000ns.
This happens after my laptop has been in sleep mode for a few minutes. Performance only goes back to normal after restarting docker-for-mac.

### Information

  - macOS Version: 10.15.4
  - Docker for Mac: version 2.2.0.5 (43884)
  - Kubernetes: disabled
  - I noticed the same issue on the previous version 2.2.0.4
  - the problem is reproducible, and occurs after macOS resume from sleep

I see this message in the diagnostic dmesg, which might be of interest:
```
[31605.325166] clocksource: timekeeping watchdog on CPU3: Marking clocksource 'tsc' as unstable because the skew is too large:
[31605.329943] clocksource:                       'hpet' wd_now: 9e9e634a wd_last: 9d74a017 mask: ffffffff
[31605.331735] clocksource:                       'tsc' cs_now: 56e68629b5a5 cs_last: 56e578fe5588 mask: ffffffffffffffff
```

### Steps to reproduce the behavior

I have characterised the behaviour with a minimal golang program. I believe golang is relying on the `gettimeofday` vDSO under the hood.

docker-time.go:
```golang
package main

import (
	"fmt"
	"time"
)

func main() {
	for {
		start := time.Now()
		for i := 0; i < 1e6; i++ {
			_ = time.Now()
		}
		fmt.Printf("time.Now() avg: %v\n", time.Since(start)/1e6)
		time.Sleep(time.Second)
	}
}
```

Dockerfile:
```Dockerfile
FROM golang:1.14
COPY docker-time.go .
CMD ["go", "run", "docker-time.go"]
```

When running this container after a docker-for-mac restart, I get:
```
> docker run -it efea882ae735
time.Now() avg: 52ns
time.Now() avg: 55ns
...
```

I then put the computer to sleep for a few minutes. After wakeup, I re-run the container and now get:
```
> docker run -it efea882ae735
time.Now() avg: 15.232µs
time.Now() avg: 14.96µs
...
```

After a docker-for-mac restart, it immediately goes back to normal :
```
> docker run -it efea882ae735
time.Now() avg: 53ns
time.Now() avg: 55ns
...
```

**Comment by jrouviere** [comment]
I just checked and it's still happening on version 2.3.0.2 (45183)

**Comment by scottgeary** [comment]
Still occurs on v3.0.3 (51017).

**Comment by jfirebaugh** [comment]
This is the same underlying issue as #3455.
