### ISSUE TITLE
Allowing to share /usr folder breaks all volume mounting attempts

### ISSUE THREAD

**Issue by egurnov** [docker/for-mac#4488]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 00D4E789-8E51-4793-86EE-DEA195DA0724/20200424180220

### Expected behavior
When I have `/usr` or any of its subfolders listed in Settings->Resources->File Sharing
I expect to be able to use at least any volumes in `docker run`, i.e
```
docker run -v "/tmp:/tmp" busybox ls /tmp
```
should succeed.

### Actual behavior
`docker run -v "/tmp:/tmp" busybox ls /tmp` hangs and doesn't react to Ctrl-C or `kill`. 

There are two scenarios after this:
1. Use `kill -9`. After that all subsequent `docker run` with any volumes return 
```
docker: Error response from daemon: Mounts denied: EOF.
ERRO[0000] error waiting for container: context canceled
```
2.  Restart docker engine. This breaks the connection and I get 
```
ERRO[0013] error waiting for container: EOF
docker: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/f35b201e6043779551796747257c36770e34c5c3c49cd7ef6637c843d65b8b17/start: EOF.
```

When I remove `/usr` from the shared folders list, everything works like a charm. I can even mount `/usr` (from HyperKit VM, as far as I understand):  `docker run -v "/usr:/tmp" busybox ls /tmp`.

### Information
Works every time on my system. 
Appears to have started after MacOS Catalina upgrade.

  - macOS Version: 10.15.4

### Diagnostic logs
App version: 2.2.0.5
Channel: stable
Engine: 19.03.8
Compose: 1.25.4
Kubernetes: v1.15.5
Notary: 0.6.1
Credentials Helper: 0.6.3

Full output of the diagnostics from "Diagnose & Feedback" in the menu:
```
Diagnose succeeded
```

This piece from logs might be relevant:
```
2020-04-24 19:50:55.092565+0200  localhost com.docker.hyperkit[68647]: /usr/bin/transfused: initialized logging system
2020-04-24 19:50:55.093388+0200  localhost com.docker.hyperkit[68647]: /usr/bin/transfused: starting server
2020-04-24 19:50:55.106342+0200  localhost com.docker.osxfs[68637]: transfused: Couldn't mount on /usr: not missing or empty
2020-04-24 19:50:55.106451+0200  localhost com.docker.osxfs[68637]: Unexpected exception: (Failure "Failure to mount /usr: not missing or empty")
```

### Steps to reproduce the behavior
1. Have `/usr` or any of its subfolders listed in Settings->Resources->File Sharing, Applied and Restarted.
2. `docker run -v "/tmp:/tmp" busybox ls /tmp`

**Comment by djs55** [comment]
@egurnov thanks for your report and repro steps. I confirm it also fails for me. I'll investigate.

**Comment by djs55** [comment]
@egurnov sorry for the delay getting back to you. I've got a candidate fix for this issue. If you'd like to give it a try, here is the latest development build: https://download-stage.docker.com/mac/edge/45256/Docker.dmg

**Comment by egurnov** [comment]
@djs55 Thank you! Tested the build and it works as expected.

**Comment by djs55** [comment]
The fix from the development build has now made its way to [stable 2.4.0.0](https://desktop.docker.com/mac/stable/48506/Docker.dmg). Thanks again for the report.
