### ISSUE TITLE
Aborted "docker cp" makes container hang forever

### ISSUE THREAD

**Issue by moycat** [docker/for-mac#4491]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6671EC64-8D5A-4A5F-91CD-55DC396A8FCD/20200426084429

### Expected behavior

After a `docker cp` (from host to container) command is interrupted (such as by `Ctrl-C`), the container should functions normally. Corrupted files may be in the container but are acceptable.

### Actual behavior

After a `docker cp` (from host to container) command is interrupted, the container is seemly in deadlock. Any command on this container fails, including `docker inspect`.

I tried to call `PUT /containers/{id}/archive` directed on the Unix socket, getting the same result.

A restart on Docker Desktop will fix this, but it's troubling.

### Information

  - macOS Version: 10.15.4 (19E287)
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Docker Engine Version: 19.03.8
  - Reproducible: Yes, on my two MacBook Pros

### Steps to reproduce the behavior

  1. Run `docker create --name test busybox` or `docker run --rm --name test -it busybox sh`.
  2. Create a directory `test` with big files inside.
  3. Run `docker cp test test:/tmp`, and press Ctrl-C while this command is still running.
  4. Commands like `docker ps -a` works file.
  5. Commands like `docker inspect test` and `docker rm test` hangs forever.

**Comment by stephen-turner** [comment]
Thanks for the report, @moycat.
I suspect this isn't in Docker Desktop but in the upstream container engine that we just bundle. Could you open a bug in the moby/moby project instead? (Sorry, I would move this issue if I could, but it's not possible because it's not in the docker org).

**Comment by moycat** [comment]
Thanks for the tip. But I failed to reproduce this bug on Linux with the same version. I will do some more investigation before I decide to open an issue in moby or reopen this 🙂️

**Comment by rumpl** [comment]
This issue was fixed and will be included in next release
