### ISSUE TITLE
Weird Download number in Docker Hub

### ISSUE THREAD

**Issue by Techbrunch** [docker/for-mac#4492]
I have just installed Docker Desktop community for Mac (edge) and followed the [onboarding/quickstart tutorial](https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2230) but there is something I don't understand.

In the tutorial you end up uploading the image to Docker Hub and when I looked in the Docker Hub there was 4 downloads but I never downloaded it.

Looks like I'm not the only one: https://hub.docker.com/search?q=docker101tutorial&type=image&sort=updated_at&order=desc

I'm guessing it is more likely that this number is not accurate but another possibility is that some people are actively scrapping Docker Hub for juicy content.

Also I would expect the tutorial to publish the image privately.

Looks like this is not an isolated case: https://hub.docker.com/search?q=docker101tutorial&type=image&sort=updated_at&order=desc

### Expected behavior

0 download in Docker Hub

### Actual behavior

4 download in Docker Hub

### Information

```
Docker for Mac: 2.3.0.0 (44472)
macOS Version: 10.15.4
```

**Comment by ulrich** [comment]
Hello @Techbrunch 

Yo can make private your repository Visibility Settings panel of the repository.

Thank you for your feedback.
