### ISSUE TITLE
Docker for Mac issue reported upon install on High Sierra

### ISSUE THREAD

**Issue by todddecapua** [docker/for-mac#4498]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We are closing this issue, because it does not contain any information to debug it. Feel free to open a new issue with full repro steps and a diagnostics bundle id.
