### ISSUE TITLE
Container DNS resolution different from host system

### ISSUE THREAD

**Issue by x3ro** [docker/for-mac#45]
First of all, thanks for bringing docker to the mac natively 🎉 It's been a huge help!

I have configured my Mac to resolve the `.dev` TLD to `127.0.0.1` following [this tutorial](https://passingcuriosity.com/2013/dnsmasq-dev-osx/). In summary, one installs and configures dnsmasq and then tells macOS' `resolver` to redirect all DNS queries for `.dev` to dnsmasq.

### Expected behavior

host$: ping test.dev
64 bytes from 127.0.0.1: [...]

container$: ping test.dev
64 bytes from 127.0.0.1: [...]

### Actual behavior

host$: ping test.dev
64 bytes from 127.0.0.1: [...]

container$: ping test.dev
64 bytes from 127.0.53.53: [...]

I'm not certain if this is the intended behavior, so my apologies if this is not a bug.

### Information

  - Apparently `.dev` domains (since they became a gTLD) currently always resolve to `127.0.53.53` 
  - Diagnostic ID: ﻿93B2DFC9-3227-4A5F-9240-4208C2618238
  - This does not seem to be related to a single Docker file
  - Tested on OSX 10.11.6, w/ both stable and beta channel

### Steps to reproduce the behavior

  1. Set up `resolver` to forward DNS queries for a specific TLD to a different DNS than the system's default
  2. Start a docker container that has ping installed
  3. ping inside the container will resolve differently from ping outside the container

**Comment by x3ro** [comment]
Of course, shortly after posting this, I found [the relevant bit of documentation](https://docs.docker.com/engine/userguide/networking/configure-dns/). Sorry for the noise.

**Comment by ebuildy** [comment]
Pay attention, from your host, you want *.dev go to 127.0.0.1 (the Docker virtual-machine), but inside a container, you want *.dev go to the right container (127.0.0.1 will be localhost for each container).
