### ISSUE TITLE
docker ps timeouts

### ISSUE THREAD

**Issue by alekseyig** [docker/for-mac#450]
### Information

Diagnostic ID: 3FA2792A-5188-4336-9FE4-CD1D365AA700
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by alekseyig** [comment]
restarted my mac, but it did not help

**Comment by doronrk** [comment]
Under Preferences -> Uninstall/Reset -> Reset to factory defaults fixed this problem for me, but I had to rebuild all my images from scratch.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in 3FA2792A-5188-4336-9FE4-CD1D365AA700/20160828-220308.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug 21 22:55:34 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: VM: 2016-08-22 03:55:34 +0000 UTC daemon.info vsudd: 924 Done. read: 116 written: 2370
Aug 21 22:55:34 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: VM: 2016-08-22 03:55:34 +0000 UTC daemon.info vsudd: 923 Done. read: 188 written: 2305
Aug 21 22:55:34 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: VM: 2016-08-22 03:55:34 +0000 UTC daemon.info vsudd: 925 Done. read: 191 written: 405685
Aug 21 22:55:36 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug 21 22:55:36 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=979373eb-98e4-4a4e-8d5f-433831db63b5,path=/Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Aug 21 22:55:36 azhukov-mbpGH Docker[com.docker.driver.amd64-linux][12132] <Notice>: Error reading vsyslog length: EOF
```
