### ISSUE TITLE
AWS Athena SQL Help

### ISSUE THREAD

**Issue by sneale1918** [docker/for-mac#4510]
I'm struggling through my first SQL code on AWS Athena, what am I doing wrong? I figured out how to create the table but now I can't figure out how to insert data into it. I keep getting this message: 

 line 3:15: no viable alternative at input '('' (service: amazonathena; status code: 400; error code: invalidrequestexception; request id: 659a137e-f7db-4b0d-92dd-979fe844685c)

This is the code I'm entering: 

insert into ETS_employees
      (employeeID, departmentID, lastname, firstname, phone, address, city, state, zipcode, email, jobtitle)
      values ('112345678987654’, ‘2’, ‘DeCoaste’, ‘Frank’, ‘8562345678’, ‘456 18th Street’, ‘Elmer’, ‘New Jersey’, ‘08318’, ‘frankdecoaste@gmail.com’, ‘manager’) ;

**Comment by stephen-turner** [comment]
This doesn't seem like a Docker bug, but an AWS usage question. Closing.
