### ISSUE TITLE
 docker exec -it <container> bash

### ISSUE THREAD

**Issue by funonly** [docker/for-mac#452]
### Expected behavior
I ran docker exec -it <container> bash
And i expected that bash would run in the container.

### Actual behavior
My terminal outputs a new line and freezes all over

### Information
Only force closing helps to shut it down

Diagnostic ID: C0F9871F-EC22-4BB2-BB77-76F856D3E32C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Run `docker exec -it <container name> bash

**Comment by funonly** [comment]
It Seems to be happening when i start redis-server in one of my other containers and close the connection

**Comment by funonly** [comment]
Running reddit-server with `nohup redis-server &` seems to solve the problem

**Comment by funonly** [comment]
This solves it half. When this command is manually run from inside the machine there is no problem after a proper detach. But when run from inside a script that is on the container with docker exec "path/to/script" the problem persists. Als I keep seeing the redis boot text which i do not see when i use nohup form inside the container.

**What i mean with inside the container is running these 2 commands `docker start <containerName>; docker attach <containerName>;`

**Comment by dsheets** [comment]
Could you please post a step-by-step reproduction of the issue including which images/Dockerfiles you are using, exactly which commands you are executing and in what order?

Thanks!

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
