### ISSUE TITLE
Quota exceeded

### ISSUE THREAD

**Issue by pococito** [docker/for-mac#4520]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E7490438-AB58-4D2A-8107-8A212FD7EA47/20200504113538

### Expected behavior

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:8e3114318a995a1ee497790535e7b88365222a21771ae7e53687ad76563e8e76
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

### Actual behavior

```
$ docker run hello-world
docker: Error response from daemon: Quota exceeded; to have your limits raised please contact Support (a1e73f4f-4d83-46e2-a7ad-f3f672c7fb68).
See 'docker run --help'.
```

### Information

  - macOS Version: 10.14.6

- This happens both whether I install Docker Desktop directly or via brew.
- It's new and fully reproducible.
- Docker run will not allow container to be executed and returns a message about some quota - with no further details.
- when run via sudo, the command will execute correctly (`sudo docker run hello-world`)
- I was not yet able to trace (`dtrace`, `opensnoop` etc.) what blocks the process when executing without sudo
- there are no system quotas set (see below)
  

### Diagnostic logs

```
Docker for Mac: 2.2.0.5 (43884)

$ ulimit
unlimited
$ quota
Disk quotas for user **** (uid ***): none
$

```

### Steps to reproduce the behavior

1. install Docker Desktop for Macos
2. `docker run hello-world`

**Comment by pococito** [comment]
Resolved. This was happening because of a `DOCKER_HOST` user environment variable (not in sudo) pointing to a docker daemon socket on a remote Triton host with container quota exceeded.

**Comment by thaJeztah** [comment]
Let me close this one
