### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by AdamDenoon** [docker/for-mac#4533]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5C6B9B6D-0A8C-4EB4-BBC6-C56F903BD9F8/20200508215034

### Expected behavior

Docker starts.

### Actual behavior

Docker does not start. Menu says "Docker Desktop is starting..." forever. Attempts to use docker commands in Terminal result in: `Error response from daemon: dial unix docker.raw.sock: connect: connection refused`

### Information
  - macOS Version: 10.15.4

### Diagnostic logs
time="2020-05-08T16:50:35-05:00" level=warning msg="[/usr/local/bin/kubectl.docker --namespace docker get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2020-05-08T16:50:35-05:00" level=warning msg="The connection to the server localhost:8080 was refused - did you specify the right host or port?\n" type=kubernetes
time="2020-05-08T16:50:35-05:00" level=warning msg="[/usr/local/bin/kubectl.docker --namespace kube-system get pods -o go-template={{range .items}}{{.metadata.name}}\n{{end}}]: exit status 1" type=kubernetes
time="2020-05-08T16:50:35-05:00" level=warning msg="The connection to the server localhost:8080 was refused - did you specify the right host or port?\n" type=kubernetes
time="2020-05-08T16:50:35-05:00" level=info msg="Start gathering list of 80 elements (timeout=10m0s)" type=list
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sw_vers -productVersion]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sw_vers -buildVersion]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [uname -r]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sysctl kern.boottime]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sysctl hw.memsize]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [vm_stat]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sysctl machdep.cpu]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [uname -a]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [ps uax]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [dmesg]" type=cmd
time="2020-05-08T16:50:35-05:00" level=warning msg="[dmesg] exit status 1" type=cmd
time="2020-05-08T16:50:35-05:00" level=warning msg="[dmesg]: Unable to obtain kernel buffer: Operation not permitted\nusage: sudo dmesg\n" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [id]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [sysctl -a]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [mount]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [df -h]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [launchctl print-disabled system]" type=cmd
time="2020-05-08T16:50:35-05:00" level=info msg="Executing: [system_profiler SPHardwareDataType]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [ifconfig -a]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [netstat -ln]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [netstat -mm]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [netstat -nr]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2020-05-08T16:50:36-05:00" level=info msg="Gathering: /etc/hosts" type=file
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [scutil --dns]" type=cmd
time="2020-05-08T16:50:36-05:00" level=info msg="Executing: [scutil --nc list]" type=cmd
time="2020-05-08T16:50:37-05:00" level=info msg="Executing: [scutil --proxy list]" type=cmd
time="2020-05-08T16:50:37-05:00" level=info msg="Executing: [system_profiler SPFirewallDataType]" type=cmd
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2020-05-08T16:50:37-05:00" level=info msg="Executing: [/bin/sh -c docker network inspect $(docker network ls -q)]" type=cmd
time="2020-05-08T16:50:38-05:00" level=warning msg="[/bin/sh -c docker network inspect $(docker network ls -q)] exit status 1" type=cmd
time="2020-05-08T16:50:38-05:00" level=warning msg="[/bin/sh -c docker network inspect $(docker network ls -q)]: Error response from daemon: dial unix docker.raw.sock: connect: connection refused\n\"docker network inspect\" requires at least 1 argument.\nSee 'docker network inspect --help'.\n\nUsage:  docker network inspect [OPTIONS] NETWORK [NETWORK...]\n\nDisplay detailed information on one or more networks\n" type=cmd
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedaemonset" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describereplicaset" type=kubectl
time="2020-05-08T16:50:38-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describedeployments" type=kubectl
time="2020-05-08T16:50:38-05:00" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']" type=cmd
time="2020-05-08T16:51:10-05:00" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]" type=cmd
time="2020-05-08T16:51:10-05:00" level=warning msg="[syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]: NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.\n" type=cmd
time="2020-05-08T16:51:10-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)]" type=cmd
time="2020-05-08T16:51:11-05:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)] exit status 1" type=cmd
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:version" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configget-contexts" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:configcurrent-context" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnodes" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:getnamespaces" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describenodes" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describepods" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:cluster-infodump" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describeservices" type=kubectl
time="2020-05-08T16:51:11-05:00" level=warning msg="kubernetes context cannot be reached. Ignoring gatherer:describestorageclass,pv,pvc" type=kubectl
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm" type=directory
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/acpid.log" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/diagnose.out.log" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/docker.log" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/docker.log.0" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/docker.log.1" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/docker.log.2" type=file
time="2020-05-08T16:51:11-05:00" level=info msg="Gathering: log/vm/docker.log.3" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.log.4" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.log.5" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.log.6" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.log.7" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.log.8" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/docker.out.log" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/host-timesync-daemon.log" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/kmsg.log" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/kmsg.log.0" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/kubelet.log" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.0" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.1" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.2" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.3" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.4" type=file
time="2020-05-08T16:51:12-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.5" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.6" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.7" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log.8" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/lifecycle-server.out.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/memlogd.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.000-metadata.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.004-format.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.005-extend.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.006-mount.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.007-swap.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.008-mount-docker.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.009-mount-kube-images.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/onboot.010-bridge.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/sntpc.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/sntpc.log.0" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/sntpc.log.1" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/sntpc.out.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/socks.out.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/trim-after-delete.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/vm/vpnkit-forwarder.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host" type=directory
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host/com.docker.backend.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Skipping empty file: log/host/com.docker.diagnose.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host/com.docker.driver.amd64-linux.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host/com.docker.driver.amd64-linux.log.0" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host/com.docker.supervisor.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Skipping empty file: log/host/docker-credential-desktop.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: log/host/vpnkit-bridge.log" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Executing: [/Applications/Docker.app/Contents/MacOS/qcow-tool check /Users/adam/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2]" type=cmd
time="2020-05-08T16:51:13-05:00" level=warning msg="[/Applications/Docker.app/Contents/MacOS/qcow-tool check /Users/adam/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2]: qcow-tool: [INFO] image has 6 free sectors and 72175 used sectors\n" type=cmd
time="2020-05-08T16:51:13-05:00" level=info msg="Skipping empty file: /Users/adam/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: /Users/adam/Library/Group Containers/group.com.docker/already-enabled-features.json" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: /Users/adam/Library/Group Containers/group.com.docker/dhcp.json" type=file
time="2020-05-08T16:51:13-05:00" level=info msg="Gathering: /Users/adam/Library/Group Containers/group.com.docker/features.json" type=file
time="2020-05-08T16:51:14-05:00" level=info msg="Gathering: /Users/adam/Library/Group Containers/group.com.docker/http_proxy.json" type=file
time="2020-05-08T16:51:14-05:00" level=info msg="Gathering: /Users/adam/Library/Group Containers/group.com.docker/settings.json" type=file
time="2020-05-08T16:51:14-05:00" level=warning msg="/Users/adam/Library/Preferences/group.com.docker.plist not included" type=file
time="2020-05-08T16:51:14-05:00" level=warning msg="exit status 1" type=directorylist
time="2020-05-08T16:51:14-05:00" level=info msg="Gathering: /Users/adam/.docker/config.json" type=redacted-json
time="2020-05-08T16:51:14-05:00" level=info msg="Gathering: /Users/adam/.docker/daemon.json" type=redacted-json
time="2020-05-08T16:51:14-05:00" level=info msg="HTTP GET: localhost /fuse/time" type=http
time="2020-05-08T16:51:14-05:00" level=warning msg="Get http://localhost/fuse/time: dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2020-05-08T16:51:14-05:00" level=info msg="HTTP GET: localhost /fuse/count" type=http
time="2020-05-08T16:51:14-05:00" level=warning msg="Get http://localhost/fuse/count: dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2020-05-08T16:51:14-05:00" level=info msg="HTTP GET: localhost /fuse/filename" type=http
time="2020-05-08T16:51:14-05:00" level=warning msg="Get http://localhost/fuse/filename: dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2020-05-08T16:51:14-05:00" level=info msg="HTTP GET: localhost /fuse/calls" type=http
time="2020-05-08T16:51:14-05:00" level=warning msg="Get http://localhost/fuse/calls: dial unix lifecycle-server.sock: connect: connection refused" type=http
time="2020-05-08T16:51:14-05:00" level=info msg="Getting Linux Diagnostics via a unix socket: diagnosticd.sock" type=unixsock
time="2020-05-08T16:51:14-05:00" level=warning msg="/diagnostics failed: Get http://unix/diagnostics: dial unix diagnosticd.sock: connect: connection refused" type=unixsock
time="2020-05-08T16:51:14-05:00" level=info msg="All 80 gatherers finished" type=list

```
Docker Desktop for Mac: 2.2.0.5 (43884)

```

### Steps to reproduce the behavior
  1. Attempt to start Docker Desktop for Mac

**Comment by donald-s** [comment]
Running into the same issue. Originally saw on High Sierra and try upgrading to Catalina (10.15.4) as well as installing the latest Docker for mac from the site. Docker won't start for me and any attempts to use the GUI also hang for me.

**Comment by AdamDenoon** [comment]
Just to add to for the case: I didn't create any contexts.

**Comment by AdamDenoon** [comment]
This issue has not been resolved by `2.3.0.2 (45183)`

**Comment by donald-s** [comment]
Quick update: Installing the edge version fixed this for me.
