### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by allenguan1986** [docker/for-mac#4534]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by WoodpeckerBaby** [comment]
this is just spam, please close this issue.
