### ISSUE TITLE
Kubernetes hangs on startup

### ISSUE THREAD

**Issue by TIBCObwright** [docker/for-mac#4535]
### Description
I had the same troubles many others are reporting in this forum, about a long hang on startup as soon as you open the Dashboard. That is, Docker Desktop does install and run Docker, so don't be misled by other bug reports. Most menu options are available in the drop-down menu from the menu bar's Docker icon. However, the hang occurs on opening the Dashboard.

Dashboard showed Docker with a green circle in the bottom status bar, but Kubernetes showed an amber circle and "Starting". Thus, the startup errors are completely about Kubernetes, not Docker itself. The Dashboard hung completely, with no way to switch between sections. Modal dialog? 

I uninstalled Docker Desktop and reinstalled, with no change in behavior: it still hung. 

So I uninstalled and this time went on a hunt in ~/Library and /Library and /usr/local/bin for any references to Docker, and deleted those. I wanted to start completely clean with a new, fresh installation. (I could not get to the Uninstall button on the Troubleshoot page of the Dashboard, because, as above, the entire Dashboard would hang.)

On reinstallation this time, Docker Desktop looked like a fresh new installation, as I hoped. Docker starts up cleanly, as before, and Dashboard and Preferences opens up immediately with no hang. Why? Because I have NOT enabled Kubernetes this time. I've learned that lesson!

Therefore, the issue is clearly and provably with Kubernetes.

  - [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F93C110F-89C9-48D4-9BD6-7FA7FD62EFDA/20200509101211
    However, I ran these diagnostics after the clean, from-scratch reinstallation described above, so they do not show K8s hanging, and might not show the conditions that made K8s hang.

### Expected behavior
Kubernetes should not hang on startup.

### Actual behavior
Kubernetes hangs on startup.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
     Easily.

  - Is the problem new?
     Yes, as of a recent upgrade to version 2.2.0.5.

  - Did the problem appear with an update?
    Yes. 2.2.0.5 upgrade.

  - A reproducible case if this is a bug, Dockerfiles FTW.
     Never got that far, sorry.

  - macOS Version: 
    macOS High Sierra, 10.13.6
    
### Diagnostic logs

```Diagnose succeeded```

This is poor English, BTW. The word is "diagnosis". 

### Steps to reproduce the behavior
 1. Install Docker Desktop for Mac, version 2.2.05
 2. Open Preferences and enable Kubernetes.
 3. I've forgotten whether the hang starts right away, or hangs the next time you start the Dashboard. But it will hang.

**Comment by WoodpeckerBaby** [comment]
You may want to fix formatting of `[ x] ` -> `[x]` so the bot accepts your check marks when filtering

**Comment by TIBCObwright** [comment]
Thanks. I live to serve the bots.

**Comment by TIBCObwright** [comment]
New info: I installed Docker Desktop 2.2.0.5 on a different Mac that has never had Docker on it, and is running Catalina 10.15.4. It installed and ran fine; I enabled Kubernetes which churned a bit, but then started up fine.

Restarting Docker Desktop, K8s came up fine. Restarting the Mac, same.

**Comment by meadlai** [comment]
> New info: I installed Docker Desktop 2.2.0.5 on a different Mac that has never had Docker on it, and is running Catalina 10.15.4. It installed and ran fine; I enabled Kubernetes which churned a bit, but then started up fine.
> 
> Restarting Docker Desktop, K8s came up fine. Restarting the Mac, same.
@TIBCObwright 
Do you have the VMware on the old/first Mac? is there any conflict with other software?

**Comment by TIBCObwright** [comment]
More info:
1. Mac-1. Yes, VMware Fusion is installed, but not running. Results in the description.
2. Mac-2. No VMware installed. Docker and K8s come up fine.
3. Mac-3, Mojave 10.14.6, Yes, Fusion is installed, but not running. Docker Desktop 2.3.0.2 Stable is newly installed today. Both Docker **and** K8s come up fine!

You want consistency? I don't have it.

Next, upgrading Docker Desktop on Mac-1, now that I see a new release is out.

**Comment by TIBCObwright** [comment]
Best news of all: I updated Mac-1 with Docker Desktop 2.3.0.2 Stable, and the problem reported herein went away. That is, Kubernetes now starts and runs normally.

Feel free to close this ticket, or let me know if that's something I should do. Thanks!

**Comment by TIBCObwright** [comment]
As reported herein, this problem has not occurred since release 2.3.0.2. Closing this issue now.
