### ISSUE TITLE
Problems With Docker Install On Mac

### ISSUE THREAD

**Issue by Psalm374** [docker/for-mac#4536]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior 

Succesful installation of Docker

### Actual behavior

Fatal Error Encountered  

Attempted Reset Docker to factory defaults 

Fatal error encountered 

the operation couldn't be completed (Docker.VmnetdError error 1
### Information

  - macOS Version:

macOS Catalina 10.15.4 

### Diagnostic logs

I cannot get to the menu as the installation is unsuccessful 
```
Docker for Mac: version...

Don't know what version Docker for Mac. 

I am attempting to install it from this link: https://hub.docker.com/editions/community/docker-ce-desktop-mac?tab=description

No version of Docker given on the link above. 

Can you please tell me how or where I can get the installation logs that are you are asking for? 
```

### Steps to reproduce the behavior

  1. ...
  2. ...FCD787C0-43B9-4B8A-A87B-DC7D55176A27/20200509180915

**Comment by Psalm374** [comment]
diagnostics.log
[diagnostics.log](https://github.com/docker/for-mac/files/4604276/diagnostics.log)
[events.err.txt](https://github.com/docker/for-mac/files/4604277/events.err.txt)

**Comment by Sixeye** [comment]
I have the same issue :(
