### ISSUE TITLE
Reopen #3768 - Docker for Mac: Kubernetes stuck at "Starting..."

### ISSUE THREAD

**Issue by WoodpeckerBaby** [docker/for-mac#4539]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9972920D-F2A0-4203-BDCB-F23C821DF96D/20200509225431

### Expected behavior
1. Docker Desktop starts
2. Docker starts
3. Docker running
4. Kubernetes starts
5. Kubernetes running
6. Both indicator green in Docker Desktop GUi
7. Open Docker Desktop Settings and settings UI responsive

### Actual behavior
1. Docker Desktop starts
2. Docker starts
3. Docker running
4. Kubernetes starts
5. Kubernetes stuck at trying to start
6. Docker Desktop show Docker indicator as green and Kubernetes amber
7. Open Docker Desktop Settings and UI stuck spinning and unresponsive to any user input. 
<img width="958" alt="Screen Shot 2020-05-10 at 6 50 07 AM" src="https://user-images.githubusercontent.com/14303318/81487211-36767b80-928d-11ea-8b46-5a4406e8206c.png">

### Information

  - macOS Version: 10.15.4 (19E287)
  - This issue builds upon a previous closed issue #3768
  - Mention #4535

### Diagnostic logs

```
Docker for Mac: Docker version 19.03.8, build afacb8b

Homebrew 2.2.15-43-gb926eeb
Homebrew/homebrew-core (git revision 0db0; last commit 2020-05-09)
Homebrew/homebrew-cask (git revision deabd; last commit 2020-05-09)

Diagnose succeeded
```
<img width="767" alt="Screen Shot 2020-05-10 at 6 49 58 AM" src="https://user-images.githubusercontent.com/14303318/81487217-43936a80-928d-11ea-9197-d9c16a46c10b.png">

### Steps to reproduce the behavior

  1. You `brew cask install docker`
  2. You run it for the first time
  3. You log into docker hub
  4. You realize docker desktop is fried.

**Comment by mike-potter** [comment]
I have this exact same problem on the 2.3.0.2 release.  Need to know how to turn off the option to start Kubernetes since I wasn't using that anyway without losing my entire docker data for all my containers.

**Comment by mike-potter** [comment]
Found the workaround in the other issue for editing the `~/Library/Group\ Containers/group.com.docker/settings.json` file and setting
```
"kubernetesEnabled" : false,
```
and then restarting Docker Desktop.  After doing this I was able to get into my Preferences dialog.
