### ISSUE TITLE
OSXFS issue on macOS Sierra beta7 - just FYI

### ISSUE THREAD

**Issue by stefanskotte** [docker/for-mac#454]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: DFA8E9A3-314C-456E-B651-6A95FE896CDF
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A304a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/sfs/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/sfs/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by dave-tucker** [comment]
I'm afraid we can't troubleshoot this further without some more information, so I'm closing for now.
If you are able to add some more information, for example:

- What you were doing when the error occurred
- What you expected to happen
- What actually happened

Then we can re-open and look at this again

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
