### ISSUE TITLE
Docker for Mac consistently crashes downloading new version

### ISSUE THREAD

**Issue by rohan-plt** [docker/for-mac#4540]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A273DCE6-79F0-4C4C-BD3A-7AC58D16FB28/20200309202453

### Expected behavior
A) Select self upgrade option from older version of Docker Desktop. Wait. Restart Docker. New version of Docker Desktop runs.
B) Quit old version of Docker. Manually download and install newer Docker Desktop. Launch Docker Desktop. It runs.
### Actual behavior
A) old version of Docker crashes while downloading new version. Docker no longer starts.
B) download and install current version of Docker Desktop. It refuses to start, offers to run diagnostics (which hang), offers to reset to factory defaults (which also hangs). After restarting docker several times, and killing things found with ps -aux | grep -i docker, Docker eventually starts up.
Maybe it would be nice if Docker Desktop actually looks for running docker processes when it starts up so users don't run into problem B. Yes, I know there is some documentation saying I should restart (yes! Restart!), but wouldn't it be easier to just kill the process on startup? (I reboot my Mac about once a month. Restarting is The Wrong Answer.)
Thanks, 
### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.2.0.3 (42716)

rohan$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: FHJW:HWJN:R6CF:LILO:DXTH:RVNN:BJJC:P6VZ:J5RS:LTBX:KOOT:JKYU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 49
  System Time: 2020-03-09T20:56:00.823255354Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

Rohans-iMac:~ rohan$

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Sixeye** [comment]
Indeed very upsetting :(

**Comment by Sixeye** [comment]
Is there any solution?
