### ISSUE TITLE
Data format error when MAC docker starts the daemon

### ISSUE THREAD

**Issue by 467892746** [docker/for-mac#4543]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

time="2020-05-13T10:28:08+08:00" level=info msg="Launching: /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit "
time="2020-05-13T10:28:08+08:00" level=info msg="HyperKit started (pid=23062): /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 2 -m 2048M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=vpnkit.eth.sock,uuid=f6a029ce-a9ab-43e0-b28b-aeb2a31cdd79 -U 6ab125ed-6653-4322-ade5-e99c9b0a2290 -s 2:0,virtio-blk,file:///Users/easyspark/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.qcow2?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false -s 3,virtio-sock,guest_cid=3,path=vms/0,guest_forwards=2376;1525 -s 4,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker-desktop.iso -s 5,ahci-cd,vms/0/config.iso -s 6,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker.iso -s 7,virtio-rnd -l com1,autopty=vms/0/tty,asl -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,"
time="2020-05-13T10:28:08+08:00" level=info msg="Hypervisor subprocess has shutdown"
time="2020-05-13T10:29:24+08:00" level=info msg="🍀 socket server listening : backend.sock"
time="2020-05-13T10:29:24+08:00" level=info msg="adding mutagen rewriter"
time="2020-05-13T10:29:24+08:00" level=info msg="🍀 socket server starting : backend.sock"
time="2020-05-13T10:29:24+08:00" level=error msg="cannot get client certificates: lstat /Users/easyspark/.docker/certs.d: no such file or directory"
time="2020-05-13T10:29:24+08:00" level=info msg="Launching: /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit "
time="2020-05-13T10:29:24+08:00" level=info msg="HyperKit started (pid=23124): /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 2 -m 2048M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=vpnkit.eth.sock,uuid=c1dcc876-865d-4f2c-896c-6c18a20af164 -U 2c7d2552-5d21-4b94-b9bd-fcb1e0c8ab6f -s 2:0,virtio-blk,file:///Users/easyspark/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.qcow2?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false -s 3,virtio-sock,guest_cid=3,path=vms/0,guest_forwards=2376;1525 -s 4,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker-desktop.iso -s 5,ahci-cd,vms/0/config.iso -s 6,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker.iso -s 7,virtio-rnd -l com1,autopty=vms/0/tty,asl -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,"
time="2020-05-13T10:29:24+08:00" level=info msg="Hypervisor subprocess has shutdown"

  - macOS Version:10.14.5

### Diagnostic logs

```
Docker for Mac: 19.03.8

```

### Steps to reproduce the behavior

  1. Data format error when MAC docker starts the daemon

![image](https://user-images.githubusercontent.com/46819001/81661449-b3ad1680-946e-11ea-9ead-1c8f93ddec4f.png)

**Comment by a0938872403** [comment]
I have the same error :((

**Comment by mAAdhaTTah** [comment]
Getting this as well. mac OS 10.13.6

**Comment by javie1199** [comment]
Same problems with Mojave

**Comment by MikeSpock** [comment]
I also get it on 10.14.6 Mojave
