### ISSUE TITLE
Error: When I was installing Docker on Mac OS High Sierra version

### ISSUE THREAD

**Issue by FrancisLeung** [docker/for-mac#4544]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No description, logs or diagnostics supplied, closing this ticket.
