### ISSUE TITLE
Default XCode dock icon in Docker for Mac 2.3.0.2

### ISSUE THREAD

**Issue by segevfiner** [docker/for-mac#4546]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 10C57E1C-297B-4097-99B5-D5E0E7DA42F5/20200512133128

### Expected behavior
The preferences and about dialogs get the Docker for Mac icon.

### Actual behavior
They get the default XCode app dock icon:
<img width="79" alt="image" src="https://user-images.githubusercontent.com/24731903/81698231-5add7e00-946e-11ea-89c1-09c971e19def.png">

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.3.0.2 (45183)

(It just says "Diagnose succeeded". There is no actual output to paste here...)
```

### Steps to reproduce the behavior

  1. Install Docker for Mac 2.3.0.2 (I installed by an automatic from the previous version)
  2. Open the about dialog or the preferences dialog.
  3. Check the Dock icon.

**Comment by ulrich** [comment]
Hello @samoht 

I followed your scenario and I was able to reproduce the issue.

We add this issue in the Desktop team issues tracker.

Thank you again for your feedback!

**Comment by ulrich** [comment]
@segevfiner little question. It seems we did encounter this trouble in the past. Did we tried to restart your mac for evicting macosx cache?

**Comment by ulrich** [comment]
Hello @segevfiner 

The next version of Docker Desktop on the stable channel will solve this issue.

Thank you,

**Comment by ulrich** [comment]
Re @segevfiner 

We found a work around for this trouble on the Apple tech forum https://discussions.apple.com/thread/8441124

We tried with success these commands:

- Close all open applications
- Open Terminal
- Run command 
> sudo find /private/var/folders/ -name 'com.apple.dock.iconcache' -delete
> sudo find /private/var/folders/ -name 'com.apple.iconservices' -delete
> sudo rm -r /Library/Caches/com.apple.iconservices.store
- Restart Mac machine

Thank again for your feedback all,
