### ISSUE TITLE
Do not overwrite binary symlinks

### ISSUE THREAD

**Issue by dsexton** [docker/for-mac#455]
### Expected behavior

Should be able to install docker utils via [homebrew](http://brew.sh/) (i.e. `brew install docker docker-compose`) and maintain via homebrew.

I have to overwrite these link every time the app launches. I would suggest asking the user if he/she wishes to overwrite these instead of automatically doing so, or at least add the option to disable them from being overwritten. 

I could see these links being overwritten during a "repair", however for those of us knowledgeable enough should be allowed to control the sources of these binaries. 
### Actual behavior

Every time _Docker for Mac_ is launched, it replaces the symlinks located in `/usr/local/bin`
### Steps to reproduce the behavior
1. Install [homebrew](http://brew.sh/)
2. Install Docker for Mac
3. Install _docker_ via brew:
   1. `$ brew install docker`
   2. `$ brew link --overwrite docker`
4. Verify linked against homebrew:
   1. `$ ls -l /usr/local/bin/docker*`
5. Reboot
6. Verify _Docker for Mac_ has overwritten symlinks
   1. `$ ls -l /usr/local/bin/docker*`

**Comment by djs55** [comment]
This seems like a reasonable request for me (for advanced users). What do you think, @gdevillele ?

**Comment by gdevillele** [comment]
Thank you for this clear report @dsexton.

I agree @djs55 , I can understand that, as a user, you might want/need to use a different version of the docker client than the one that is shipped with Docker for Mac.

What is your motivation here @dsexton? Are you switching between different versions of the Docker client? Or is it just a wish to "be in control" of the Docker client's version that you use?

**Comment by dsexton** [comment]
Coming from a Linux background, I prefer to maintain packages through "the" package manager. Docker is no different. In general, I think it is irresponsible to just assume it is ok to overwrite these binaries/symlinks. I could see testing during install/repair to see if these are linked to the vendored versions, and then prompting the user if they would like to replace them. 😕 

Now, I could see potential issues with API compatibility between what CLI is installed `/usr/local/bin/` and the docker service that is running in the VM. In general, I hope there are plans in motion for the API to adhere to strict semver policies, limiting the how often this would be an issue. However, if the installed CLI is not yours, then you should prompt the user instead of overwriting it.

@gdevillele my true motivation is a bit above and beyond. I am running the macOS beta, which has compatibility issues with go 1.6 (the *Docker for Mac* binaries are compiled against 1.6), so my binaries are compiled against go 1.7.  Some may consider this "not my problem" since macOS 11.12 is in beta, but the oss community usually fixes these issues rather quickly.

@djs55 @gdevillele are there any plans to open source *Docker for Mac*? I would consider donating time to help resolve some of these issues.
