### ISSUE TITLE
SCTP support broken after 2.3.0.2 upgrade

### ISSUE THREAD

**Issue by emakeev** [docker/for-mac#4552]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
kernel SCTP support is available on linuxkit
### Actual behavior
Docker Desktop Community 2.3.0.2 linuxkit does not have SCTP kernel module
### Information
kernel SCTP module is not available after 2.3.0.2 upgrade:
With 2.3.0.2 docker desktop:
    docker run --rm -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
    # uname -a
    Linux docker-desktop 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 Linux
    # modprobe sctp
    modprobe: module sctp not found in modules.dep

Downgrading back to to 2.2.0.5  fixes the issue 
With 2.2.0.5 docker desktop:
    # uname -a
    Linux docker-desktop 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 Linux
    #  modprobe sctp

  - macOS Version: 10.15.4

### Diagnostic logs

# modprobe -l
kernel/fs/nfs_common/grace.ko
kernel/fs/nfs/nfs.ko
kernel/fs/nfs/nfsv2.ko
kernel/fs/nfs/nfsv3.ko
kernel/fs/nfs/nfsv4.ko
kernel/fs/nfs/filelayout/nfs_layout_nfsv41_files.ko
kernel/fs/nfs/flexfilelayout/nfs_layout_flexfiles.ko
kernel/fs/nfsd/nfsd.ko
kernel/fs/lockd/lockd.ko
kernel/crypto/crypto_engine.ko
kernel/drivers/xen/xen-privcmd.ko
kernel/drivers/char/tpm/tpm_i2c_atmel.ko
kernel/drivers/char/tpm/tpm_i2c_infineon.ko
kernel/drivers/char/tpm/tpm_i2c_nuvoton.ko
kernel/drivers/char/tpm/tpm_nsc.ko
kernel/drivers/char/tpm/tpm_atmel.ko
kernel/drivers/char/tpm/tpm_infineon.ko
kernel/drivers/char/tpm/st33zp24/tpm_st33zp24.ko
kernel/drivers/char/tpm/st33zp24/tpm_st33zp24_i2c.ko
kernel/drivers/char/tpm/xen-tpmfront.ko
kernel/drivers/char/tpm/tpm_vtpm_proxy.ko
kernel/drivers/scsi/raid_class.ko
kernel/drivers/scsi/scsi_transport_iscsi.ko
kernel/drivers/scsi/scsi_transport_sas.ko
kernel/drivers/net/bonding/bonding.ko
kernel/drivers/net/dummy.ko
kernel/drivers/net/geneve.ko
kernel/drivers/net/vsockmon.ko
kernel/drivers/net/ppp/ppp_generic.ko
kernel/drivers/net/ppp/ppp_async.ko
kernel/drivers/net/ppp/bsd_comp.ko
kernel/drivers/net/ppp/ppp_deflate.ko
kernel/drivers/net/ppp/ppp_mppe.ko
kernel/drivers/net/ppp/ppp_synctty.ko
kernel/drivers/net/ppp/pppox.ko
kernel/drivers/net/ppp/pppoe.ko
kernel/drivers/net/ppp/pptp.ko
kernel/drivers/net/slip/slhc.ko
kernel/drivers/crypto/virtio/virtio_crypto.ko
kernel/drivers/vhost/vhost_vsock.ko
kernel/drivers/vhost/vhost.ko
kernel/net/sched/sch_cbq.ko
kernel/net/sched/sch_htb.ko
kernel/net/sched/sch_hfsc.ko
kernel/net/sched/sch_red.ko
kernel/net/sched/sch_gred.ko
kernel/net/sched/sch_ingress.ko
kernel/net/sched/sch_dsmark.ko
kernel/net/sched/sch_sfb.ko
kernel/net/sched/sch_sfq.ko
kernel/net/sched/sch_tbf.ko
kernel/net/sched/sch_teql.ko
kernel/net/sched/sch_prio.ko
kernel/net/sched/sch_multiq.ko
kernel/net/sched/sch_netem.ko
kernel/net/sched/sch_drr.ko
kernel/net/sched/sch_mqprio.ko
kernel/net/sched/sch_choke.ko
kernel/net/sched/sch_qfq.ko
kernel/net/netfilter/nft_fib.ko
kernel/net/ipv4/ip_gre.ko
kernel/net/ipv4/ip_vti.ko
kernel/net/ipv4/ah4.ko
kernel/net/ipv4/esp4.ko
kernel/net/ipv4/ipcomp.ko
kernel/net/ipv4/xfrm4_tunnel.ko
kernel/net/ipv4/xfrm4_mode_beet.ko
kernel/net/ipv4/xfrm4_mode_transport.ko
kernel/net/ipv4/xfrm4_mode_tunnel.ko
kernel/net/xfrm/xfrm_algo.ko
kernel/net/xfrm/xfrm_user.ko
kernel/net/xfrm/xfrm_ipcomp.ko
kernel/net/ipv6/netfilter/ip6table_filter.ko
kernel/net/ipv6/netfilter/ip6table_mangle.ko
kernel/net/ipv6/netfilter/ip6table_raw.ko
kernel/net/ipv6/netfilter/ip6table_security.ko
kernel/net/ipv6/netfilter/ip6table_nat.ko
kernel/net/ipv6/netfilter/nf_nat_ipv6.ko
kernel/net/ipv6/netfilter/nft_chain_route_ipv6.ko
kernel/net/ipv6/netfilter/nft_chain_nat_ipv6.ko
kernel/net/ipv6/netfilter/nft_masq_ipv6.ko
kernel/net/ipv6/netfilter/nft_redir_ipv6.ko
kernel/net/ipv6/netfilter/nft_dup_ipv6.ko
kernel/net/ipv6/netfilter/nft_fib_ipv6.ko
kernel/net/ipv6/netfilter/ip6t_ah.ko
kernel/net/ipv6/netfilter/ip6t_eui64.ko
kernel/net/ipv6/netfilter/ip6t_frag.ko
kernel/net/ipv6/netfilter/ip6t_ipv6header.ko
kernel/net/ipv6/netfilter/ip6t_mh.ko
kernel/net/ipv6/netfilter/ip6t_hbh.ko
kernel/net/ipv6/netfilter/ip6t_rt.ko
kernel/net/ipv6/netfilter/ip6t_srh.ko
kernel/net/ipv6/netfilter/ip6t_MASQUERADE.ko
kernel/net/ipv6/netfilter/ip6t_NPT.ko
kernel/net/ipv6/netfilter/ip6t_REJECT.ko
kernel/net/ipv6/netfilter/ip6t_SYNPROXY.ko
kernel/net/ipv6/ah6.ko
kernel/net/ipv6/esp6.ko
kernel/net/ipv6/ipcomp6.ko
kernel/net/ipv6/xfrm6_tunnel.ko
kernel/net/ipv6/xfrm6_mode_transport.ko
kernel/net/ipv6/xfrm6_mode_tunnel.ko
kernel/net/ipv6/xfrm6_mode_ro.ko
kernel/net/ipv6/xfrm6_mode_beet.ko
kernel/net/ipv6/mip6.ko
kernel/net/ipv6/ila/ila.ko
kernel/net/ipv6/ip6_vti.ko
kernel/net/ipv6/sit.ko
kernel/net/ipv6/ip6_gre.ko
kernel/net/bpfilter/bpfilter.ko
kernel/net/key/af_key.ko
kernel/net/sunrpc/sunrpc.ko
kernel/net/sunrpc/auth_gss/auth_rpcgss.ko
kernel/net/l2tp/l2tp_core.ko
kernel/net/l2tp/l2tp_ppp.ko
kernel/net/vmw_vsock/vsock.ko
kernel/net/vmw_vsock/vsock_diag.ko
kernel/net/vmw_vsock/vmw_vsock_virtio_transport.ko
kernel/net/vmw_vsock/vmw_vsock_virtio_transport_common.ko
kernel/net/vmw_vsock/hv_sock.ko

```
Docker for Mac: 2.3.0.2

```

### Steps to reproduce the behavior

docker run --rm -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
# modprobe sctp

  1. ...
  2. ...

**Comment by f355** [comment]
I want to stress that macOS does not support SCTP natively, and Docker for Mac used to be the most convenient way of developing and testing applications. It would be really, really sad to have to resort to bespoke hacks with running VMs manually or to migrate to Linux.

**Comment by slushie** [comment]
I've been motivated by the lack of response from Docker, Inc. that I put together [my own solution to build kernel modules for Docker VMs](https://github.com/slushie/docker-module-builder). I'm using it now to build the `wireguard` module for my users. Hopefully it can be useful for you as well!

**Comment by f355** [comment]
Any update on this? I find it mind-boggling that e.g. device-mapper got quickly added back in #4549, but sctp, wireguard and openvswitch issues weren't even triaged or commented on by the team in more than a month now.

**Comment by asilvr** [comment]
+1 for this issue. Even though SCTP support egressing the Docker for Mac VM is not supported, having an isolated environment which supported SCTP on a Mac without an additional self-built Docker VM was very convenient.

**Comment by adibrastegarnia** [comment]
+1

**Comment by Yoone** [comment]
+1, we also need to use SCTP on Mac and Docker was the only convenient way to do it

**Comment by emakeev** [comment]
It looks like the easiest workaround is to stick with 2.2.0.5 - the last stable release with SCTP support
