### ISSUE TITLE
docker not starting

### ISSUE THREAD

**Issue by arunmenon** [docker/for-mac#456]
### Expected behavior

docker ps should execute 
### Actual behavior
docker ps giving a timeout
### Information

Diagnostic ID: EE358BB1-5482-4CCB-A312-FBCE70AC981F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.3 (Build 15D21)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

**Comment by doronrk** [comment]
Reset to factory defaults fixed this problem for me, but I had to rebuild all my images from scratch.

**Comment by mchiang0610** [comment]
Seems similar to #119, but closing because this is resolved by resetting to factory defaults. 

Sorry for the hassles of recreating your images.
