### ISSUE TITLE
Docker Desktop 2.3.0.2 does not start on macOS Catalina due to wrong sdk value in Mach-O Header

### ISSUE THREAD

**Issue by sethgee** [docker/for-mac#4562]
Hi from Apple :).

This issue is due to the sdk version in the MACH-O header having an invalid value of 11.3.1 -- it MUST be the macOS version corresponding to the sdk (e.g. 10.15).  Please fix.

**Comment by sethgee** [comment]
Ignore.

**Comment by sethgee** [comment]
Really ignore :)

**Comment by sethgee** [comment]
Sigh.  Yes, the above report is correct.  It fails on an iMac Pro.

**Comment by ulrich** [comment]
Hello @sethgee 

Can you send more information about your Mac os version ?

Thank you.

**Comment by sethgee** [comment]
This reproduces on at least macOS Catalina 10.15.4 and the latest 10.15.5 Beta.

**Comment by sethgee** [comment]
Hi!

  Sorry I missed seeing this in my inbox due to some filter rules;  I've updated the issue with macOS details.  Please let me know if there's anything else you needed.  Note that I saw that there was a commit that disabled the overeager don't-care bit policing, which was the better direction :).

 Thanks,
 --S

**Comment by mat007** [comment]
This has now been released in Docker Desktop Stable 2.3.0.3, I’ll go ahead and close this issue.
Thanks!

**Comment by sethgee** [comment]
Thanks very much! :).

 --S
