### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by EEPNU** [docker/for-mac#4563]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No diagnostics id provided, so nothing to investigate. Closing this ticket.
