### ISSUE TITLE
lete all local credential

### ISSUE THREAD

**Issue by dobosolution** [docker/for-mac#4564]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No information provided, closing this ticket.
