### ISSUE TITLE
docker ps times out

### ISSUE THREAD

**Issue by doronrk** [docker/for-mac#457]
### Information

Diagnostic ID: EB8152AF-9235-441D-9D25-2F7D74D6FB08
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

`> docker ps`

**Comment by doronrk** [comment]
Under Preferences -> Uninstall/Reset -> Reset to factory defaults fixed this problem for me, but I had to rebuild all my images from scratch.

**Comment by DeepSpawn** [comment]
I have also just encountered this issue

**Comment by hinunbi** [comment]
I hava the same problem too.

Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/684AE4E0-6E6A-4401-8A05-AE63809F3954/20160830-163004.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'invariant-violated' in EB8152AF-9235-441D-9D25-2F7D74D6FB08/20160829-113951.

An invariant within the code of one of the components was not held. Docker needs to be restarted.

May be related to docker/for-mac#89

The following log matches:
```
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.driver.amd64-linux][94539] <Notice>: VM: 2016-08-22 20:18:52 +0000 UTC kern.info kernel: docker0: port 2(veth0ebdd6a) entered forwarding state
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.driver.amd64-linux][94539] <Notice>: VM: 2016-08-22 20:18:52 +0000 UTC daemon.info vsudd: 1135 Done. read: 208 written: 95
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.osxfs][94537] <Notice>: Volume.stop c043e792be061b6f671cfe6e2643922fc143c5f86e17554e74b5c5d257d7a035 (paths = [/Users/robertsk/Documents/code/api-gateway-dc/])
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.osxfs][94537] <Error>: WATCH SUBSCRIBER REMOVAL INVARIANT VIOLATED
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.driver.amd64-linux][94539] <Notice>: VM: 2016-08-22 20:18:52 +0000 UTC daemon.info vsudd: 1134 Done. read: 265 written: 4365
Aug 22 13:18:52 robertsk-osx2 Docker[com.docker.driver.amd64-linux][94539] <Notice>: VM: 2016-08-22 20:18:52 +0000 UTC daemon.info vsudd: Connection 1136 to: 2376 from: 00000000
Aug 22 13:18:53 robertsk-osx2 Docker[com.docker.driver.amd64-linux][94539] <Notice>: VM: 2016-08-22 20:18:53 +0000 UTC kern.info kernel: docker0: port 2(veth0ebdd6a) entered disabled state
```

/cc @dsheets

**Comment by Yugloocamai** [comment]
Same issue.  I have to reboot my system to get docker back into a good state.

**Comment by dsheets** [comment]
@DeepSpawn @hinunbi @Yugloocamai please open a new issue with diagnostic information if you would like us to investigate the issue. It is likely that the problem you experience is not the same as this issue report -- many different problems can cause this same symptom. We recommend running the latest Beta or Stable release as we are constantly fixing issues some of which cause this same symptom.

I do not believe that the original issue was caused by the invariant violation that @samoht cites.
