### ISSUE TITLE
Docker for Desktop resets Kubernetes cluster with upgrade

### ISSUE THREAD

**Issue by przemekulik** [docker/for-mac#4571]
I have upgraded Docker for Desktop today (15 May 2020) and my kubernetes cluster got reset while my docker env remained intact.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
Upgrading Docker for Desktop does not reset kubernetes cluster

### Actual behavior
Upgrading Docker for Desktop does reset kubernetes cluster

### Information
- Is it reproducible?
-- I don't know. I would have to upgrade again to check. I'll remember this for the next upgrade I'll see.
- Is the problem new?
-- Yes, I haven't experienced it before

- macOS Version: 10.15.4
- Docker for Desktop Version: 2.3.0.2

**Comment by Sefriol** [comment]
After I updated docker, I got a fatal error when it was trying to launch kubernetes. After restarting the cluster was reseted for me as well.
