### ISSUE TITLE
the docker is taking 200% of cpu There is only one bucket of 40Mb 

### ISSUE THREAD

**Issue by vkshrivastva** [docker/for-mac#4572]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No debugging info supplied, closing.
