### ISSUE TITLE
"container running," but container not running in ps

### ISSUE THREAD

**Issue by HashRocketSyntax** [docker/for-mac#4577]
[diagnostics.log](https://github.com/docker/for-mac/files/4638410/diagnostics.log)

I am trying to delete images, but it claims they being used by running containers.

There is nothing running according to ps.
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
See how when I try to stop the running container associated with this image it switches to a different running container? It's almost like it is *self healing* via k8s.
```
$ docker rmi 605a0f683b7b
Error response from daemon: conflict: unable to delete 605a0f683b7b (cannot be forced) - image is being used by running container bc1e6ac79fd5

$ docker container stop bc1e6ac79fd5
bc1e6ac79fd5

$ docker rmi 605a0f683b7b
Error response from daemon: conflict: unable to delete 605a0f683b7b (cannot be forced) - image is being used by running container d60860fdea86
```
I was messing around with k8s and helm charts a few months ago. Maybe that has something to do with it.

**Comment by HashRocketSyntax** [comment]
After restarting for maybe the 6th time this morning and 20th time overall,
`docker rmi $(docker images -aq)` removed the images.

**Comment by stephen-turner** [comment]
Seems like it's solved now, closing this ticket.
