### ISSUE TITLE
docker rm container command removes also container's image from repository

### ISSUE THREAD

**Issue by oferdit** [docker/for-mac#4579]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CDB7AC96-0855-49F8-A5F7-78E427BA7B9B/20200517102526

### Expected behavior
docker rm should remove container only and not the container's image

### Information

  - macOS Version: catalina

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. create a container with any image
  2. use docker rm to remove container

**Comment by stephen-turner** [comment]
I think your expected behaviour is what happens. But anyway, if it's not working, the problem is in the upstream engine not Docker Desktop, so you will need to open a ticket in moby/moby. (Sorry, I would move it myself, but it's not possible because the engine is not part of the docker org).
