### ISSUE TITLE
Docker 1.12.1 still not released on stable

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#458]
### Expected behavior
We should be able to use the latest docker server in Docker for Mac soon after its release.
This is important because docker is changing and often breaking rapidly, so it's very difficult to work with a docker server that is 1) old, and 2) different from your other environments.
### Actual behavior
The 1.12.1 release was over 10 days ago but Docker for Mac is still 1.12.0.
https://github.com/docker/docker/releases/tag/v1.12.1
### Information
fyi noticed this because I'm hoping Docker for Mac 1.12.1 will fix my issues with systemd:
https://github.com/CentOS/sig-cloud-instance-images/issues/54

**Comment by joshmanders** [comment]
Any ETA on this? I'm having issues with current stable and I'd like to get updated. Docker for Mac has been great, but I'm on the verge of going back to using docker machine and virtualbox again.

**Comment by mchiang0610** [comment]
Hi @jamshid  @joshmanders we are working on including 1.12.1 on stable channel. 

We do, however, have 1.12.1 on our beta channel - available: https://download.docker.com/mac/beta/Docker.dmg 

@joshmanders What specific bugs are you finding that's making you want to move back to Docker machine?

**Comment by joshmanders** [comment]
@mchiang0610 it's pegging my cpu pretty hard and causing my fans to spin really loud for long periods of time with only 3 alphine based containers running.

On top of that, periodically it becomes completely unresponsive to the point that not only do I have to kill the docker app and restart it, but after it's running again, click restart button in the app and wait about 20-30 seconds for it to become responsive again.

I never had any issues with Docker machine and virtualbox, so I'm almost preferring to migrate back to that until Docker for Mac is more stable.

**Comment by mchiang0610** [comment]
@joshmanders Sorry to hear that. High CPU usage is definitely being tracked. Would it be possible for you to tell us what you are running for us to reproduce on our side? 

Any logs would be useful.

**Comment by joshmanders** [comment]
@mchiang0610 

I just ran diagnostics and it so happen to run during a time that docker is not responding, so I'm going to have to kill the app, restart it, and restart docker inside of it.

```
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/6AAD22FC-B2B4-41E5-AC4C-D7B3485FD7DC/20160902-121617.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
1.12.1 is released. 

Also the latest issue you are getting seems similar to #119

**Comment by jamshid** [comment]
FYI the "stable" channel download at https://docs.docker.com/docker-for-mac/ (that's where Documentation menu takes you) is still the old version:
Version 1.12.0-a (build: 11213)
ad6ab836187e4111082447b7c0a6a74d01929a5c

**Comment by joshmanders** [comment]
Yes, I checked the appcast, as I install it via Homebrew Caskroom, and it's still not showing available. https://download.docker.com/mac/stable/appcast.xml

**Comment by jamshid** [comment]
Well the beta channel just updated to 1.21.1-beta26 but stable still seems stuck on 1.12.0.
@mchiang0610 do you know the 1.12.1 release is imminent, any idea when? Or were you confused because while docker 1.12.1 is out, stable Docker for Mac has not been updated to include it yet.

**Comment by joshmanders** [comment]
Did the switch back to Docker Machine using VirtualBox. My fans stopped and it's quiet in here again. Maybe give Docker for Mac a 3rd try in the future but right now I'm not gonna put my machine through that power consumption.

**Comment by MagnusS** [comment]
Sorry for the confusion about the release date. 1.12.1 has been available on the beta channel for a while, but has not been released on the stable channel yet. A new stable release with 1.12.1 and macOS Sierra support will be released within a few days.

**Comment by jamshid** [comment]
Docker release (1.12.2) has been out for almost week but is not yet available in Docker for Mac. Any idea when? It really helps when needed docker fixes are available on all platforms at roughly the same time.

**Comment by justincormack** [comment]
@jamshid Docker 1.12.2 was released yesterday. We will be releasing updated versions of Docker for Mac and Windows as soon as we are sure they are ready.
