### ISSUE TITLE
Opening "Docker Desktop.app" while docker is running no longer opens Docker Desktop/Dashboard window

### ISSUE THREAD

**Issue by gimbo** [docker/for-mac#4580]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9CFFAF41-BDE4-4B42-BA9C-8A9AD42DB759/20200518113104

### Expected behavior

(How it was until recently) While Docker for Mac is running, opening `/Applications/Docker.app/Contents/MacOS/Docker Desktop.app` opens the Docker Desktop/Dashboard window, showing me my running stacls/containers, allowing me to view logs, shut down containers, etc.

### Actual behavior

(Now) Opening `/Applications/Docker.app/Contents/MacOS/Docker Desktop.app` opens a window saying "Fatal error — Docker is already running".

(This is the same error window mentioned in issue #4556 )

If I want to see the Docker Dashboard, as far as I can tell the only way seems to be clicking the Docker icon in my menubar (which I happen to hide with [Bartender](https://www.macbartender.com/) most of the time) and then selecting "Dashboard" from the dropdown (so that's 3 hunt-and-click operations for me).

### Information

  - macOS Version: 10.14.6

It was very very convenient to be able to call up the Dashboard window in this manner (I'd actually set up an [Alfred](https://www.alfredapp.com/) shortcut for doing this so it was literally four keystrokes) — much more convenient than selecting the "Dashboard" menu option from the Whale icon in my menu bar; particularly on a 4K screen that's a fiddly operation, but in general I like launching things from the keyboard where possible and this was very handy.

Perhaps I was just luckily using some undocumented/unintended behaviour which has now been squashed, but it really was very convenient to be able to open the Dashboard in this way, and I'd started using it instead of portainer for many tasks. It would be helpful if there was _some_ way to summon this window quickly (hotkeys?). For now I'll probably go back to portainer, as summoning that up is actually easier than opening the Dashboard via the menubar now.

### Diagnostic logs

```
Docker for Mac: version 2.3.0.2 (45183)
```

### Steps to reproduce the behavior

  1. Ensure Docker for Mac is running (whale stable in menubar)
  2. In a terminal, run: `open "/Applications/Docker.app/Contents/MacOS/Docker Desktop.app"`

**Comment by gimbo** [comment]
Looking at [release notes](https://docs.docker.com/docker-for-mac/release-notes/), I _wonder_ (but don't know) if this was introduced in the 2.3.0.2 release on 2020-05-11 which included:

> * Fixed a bug where the Docker UI could be started without the engine.

Just a thought.

**Comment by stephen-turner** [comment]
Thanks for your helpful feedback, @gimbo. Yes, it was removed deliberately, because it actually opened the UI only, and if the backend wasn't running it caused loads of confusion. So I'm going to close this ticket, but your wider point about wanting a quicker way to get to the dashboard is noted. I'm copying @stlucek and @nebuk89 on this.

**Comment by gimbo** [comment]
Thanks for the prompt and thoughtful response!
