### ISSUE TITLE
Is Magic Replacement of Docker Binary Officially Supported? 

### ISSUE THREAD

**Issue by Nuru** [docker/for-mac#4583]
This behavior is great, but I cannot find it documented anywhere, and would like to know if it is officially supported and can be counted on for the future. 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
I expected running
```
docker run --rm -it --volume /usr/local/bin/docker:/usr/bin/docker --volume /var/run/docker.sock:/var/run/docker.sock alpine:3.11.5
```
would fail because /var/run/docker.sock does not exist on the host, and if it did run, it
would make the host's docker binary available in the container, and that would not run because the host's (Mac) binary does not run under Alpine.

### Actual behavior

There is a `/var/run/docker.sock` on the host now, and magically, `/usr/bin/docker` in the container is a different, runnable docker client and it can connect to the host docker daemon via the container's `/var/run/docker.sock`. 

### Information

This seems new with Docker Desktop 2.3. I recall trying to bind `/var/run/docker.sock` in 2.2 and failing; I had to bind `/run/guest-services/docker.sock` instead. 

  - macOS Version: 10.15.4

### Steps to reproduce the behavior

```
host $ ls -Lsk /usr/local/bin/docker
 59776 /usr/local/bin/docker*
host $ docker run --rm -it --volume /usr/local/bin/docker:/usr/bin/docker --volume /var/run/docker.sock:/var/run/docker.sock alpine:3.11.5
/ # ls -Lsk /usr/bin/docker
 64288 /usr/bin/docker
/ # docker ps
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS              PORTS                      NAMES
c70e7cd9b27e        alpine:3.11.5                    "/bin/sh"           17 seconds ago      Up 16 seconds                                  cool_kare
```

**Comment by thaJeztah** [comment]
Docker uses a "client/server" architecture, where the `docker` CLI communicates with the `dockerd` daemon over an API. When bind-mounting files/directories into a container, those files/directories are always mounted from the host where the daemon (and thus the container) runs. This may be the same host (for example, when running on a Linux machine), but could also be a different host (for example, if you're connected to a remote docker daemon running on a cloud provider).

Docker containers require a Linux kernel (or Windows if you run native windows containers). In the case of Docker Desktop, that kernel is provides through a lightweight VM running on your Mac. The docker daemon runs inside that VM, and if you bind-mount files, you're actually bind-mounting files from inside that VM.

In your example, `/var/run/docker.sock` will be bind-mounted from inside the VM, and provides access to the Docker API.

In other cases you'll  likely want to bind-mount files from your host (macOS) machine into a container (for example to give a container access to your source-files during development). To provide that, Docker Desktop allows you to share paths from your host with the VM (see https://docs.docker.com/docker-for-mac/osxfs/). In that case, Docker Desktop shares those paths with the VM, and the docker daemon bind-mounts the paths from inside the VM into the container.

By default, the `/Users`, `/Volume`, `/private`, `/tmp` and `/var/folders` directories are shared; any path outside that will be mounted from the VM (and not shared with your host), so when you bind-mount `/usr/local/bin/docker`, you're bind-mounting the Linux `docker` CLI that's installed inside the VM, and not the `docker` CLI that's installed on your macOS machine.

**Comment by thaJeztah** [comment]
As to your question: I'm not sure if bind-mounting the `docker` CLI is guaranteed to be supported. I would recommend running a container that has the `docker` cli installed. You can use the official docker images for that, for example to run a container with the Docker 19.03 CLI (I'm using `sh` as the container's command, which gives you a shell inside the container);

```bash
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:19.03 sh

/ # docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```


Bind-mounting `/var/run/docker.sock` should continued to be supported

**Comment by Nuru** [comment]
@thaJeztah thank you for the detailed explanation. I have spent a long time reading the Docker documentation without being able to learn much about the VM in which the Docker daemon runs, so this was quite helpful. 

I understand it would be best to use a container with the CLI installed, and frankly I thought it would be a requirement on macOS, but I have also been cautioned about running a CLI that is not API compatible with the Docker daemon. I guess that problem has been handled now, with API versioning and automatic negotiation (although that negotiation mechanism is broken in 19.03.9). Generally, though, for performance reasons, I use an Alpine-based Docker image which does not come with a docker CLI and is a little behind Docker Destkop. Using the CLI from the Moby VM is appealing.

I did not realize that host paths not "shared" could not be explicitly bind mounted. I thought sharing meant binding them by default. Now I understand sharing means mounting them in the VM for later optional binding to the containers. 

I now have found this section of [documentation](https://docs.docker.com/docker-for-mac/osxfs/#namespaces) on the page your pointed me to:

> By default, you can share files in /Users/, /Volumes/, /private/, and /tmp directly. To add or remove directory trees that are exported to Docker, use the File sharing tab in Docker preferences whale menu -> Preferences -> File sharing. (See Preferences.)
>
> All other paths used in -v bind mounts are sourced from the Moby Linux VM running the Docker containers, so arguments such as -v /var/run/docker.sock:/var/run/docker.sock should work as expected. If a macOS path is not shared and does not exist in the VM, an attempt to bind mount it fails rather than create it in the VM. Paths that already exist in the VM and contain files are reserved by Docker and cannot be exported from macOS.

It seems to me a fair bet that the VM running the Docker daemon will have the Docker CLI installed and, being a Go binary, likely be executable in the container. I know there are issues with dynamically linked Go binaries running under Alpine due to Alpine using musl instead of glibc, but it looks like at least Moby Linux is shipping a statically linked CLI. 

Nevertheless, I will recommend using the Docker container's package system for installing an OS-specific CLI.

**Comment by thaJeztah** [comment]
> It seems to me a fair bet that the VM running the Docker daemon will have the Docker CLI installed and, being a Go binary, likely be executable in the container

Yeah, I don't think there's plans to remove the CLI from the Docker Desktop VM, but _strictly speaking_ I don't think it's needed for Docker Desktop to run (I think all internals use the API directly, not the cli). Overall it should be "safe" to bind-mount, but it's not a formal "contract" so things _could_ change.
