### ISSUE TITLE
Docker never starts on Mac

### ISSUE THREAD

**Issue by notaaron** [docker/for-mac#4587]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info in the ticket, closing.
