### ISSUE TITLE
Multi Docker version support

### ISSUE THREAD

**Issue by flxfxp** [docker/for-mac#459]
As Docker development is moving faster than most infrastructure, it would be awesome to configure what version of Docker should be ran, 1.11.2 vs 1.12.0 etc.

**Comment by dsheets** [comment]
This capability is on our roadmap and we are considering how best to expose multiple Docker versions. If you have ideas about the easiest way to manage multiple versions for your workflow and use cases, we're interested in hearing about them.

**Comment by justincormack** [comment]
@flxfxp what is your use case for this? Is it because you have issues connecting a newer client to an older server or because you want the server version in the desktop version to match your production server version?

**Comment by flxfxp** [comment]
My usecase is that for daily development I rely on Docker for Mac, but with its constant updates via Sparkle, it also upgrades the underlying docker tools without having a choice on what version to keep. As the OS support and bugs continue to be fixed, I also run the risk of eventually running a local environment that is supported by newer docket tools than staging and production. In order to decrease the likelihood of running into these bugs, it would be great if you could select a docker tool release branch from within the Docker for Mac configuration screen, probably in similar style to docker images: latest, 0.2, 0.2.2-1, etc

**Comment by flxfxp** [comment]
Another option would be to include them in the docker-compose file, allowing you to explicitly require the docker tool version in similar fashion, allowing effortless switches between docker versions, possibly with running multiple versions at the same time, reminiscent of python virtual environments
