### ISSUE TITLE
forced restore

### ISSUE THREAD

**Issue by alysonfs** [docker/for-mac#4592]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Unfortunately we aren't able to help without some reproduction instructions or a diagnostics report, see https://docs.docker.com/docker-for-mac/troubleshoot/#diagnose-problems-send-feedback-and-create-github-issues . I'll close this ticket but feel free to open another one.
