### ISSUE TITLE
where we can find docker container logs

### ISSUE THREAD

**Issue by vmuthuprasad** [docker/for-mac#4597]
I want to consume docker container STDOUT using filebeat. In general it is mentioned container logs will be stored under /var/lib/docker/containers/

docker inspect f98f60f4db0c
gives log path in

"LogPath": "/var/lib/docker/containers/f98f60f4db0c3220e624312cd71b0c85ddcd1919c75567deae35f4ab07ab0877/f98f60f4db0c3220e624312cd71b0c85ddcd1919c75567deae35f4ab07ab0877-json.log"
but i don't see even

/var/lib/docker/
I don't see any logs even under

~/Library/Containers/com.docker.docker/Data/vms/0/

following are my mac and docker

macOS Version: 10.14.6

Docker Version: 2.3.0.2 (docker dekstop)

please let me know where can i find docker container logs for mac to capture them in filebeat.

**Comment by djs55** [comment]
Thanks for your report. Unfortunately the paths `/var/lib/docker/containers` are inside the helper Linux VM.

Perhaps you could run `filebeat` inside a container with a command like:
```
$ docker run -it -v /var/lib/docker/containers:/var/lib/docker/containers alpine sh
/ # ls /var/lib/docker/containers/
082d8f8ad6f05edac3731c64ff066ffc8367dbe9fa121d3d8d21075861e8c40a  92cdf44069f25e520b354ff1e73f17350e461d44cce1b088c34220eb137f392c
```
which would give it access to the correct paths.

Another possibility is to write a small program / script which uses `docker events` to see when containers are started and stopped, and then use `docker logs` to write the logs to a file.

Another possibility is to write a Docker logging plugin which could ship the logs somewhere.


Let me know what you think.

**Comment by vmuthuprasad** [comment]
Thanks David, could you please suggest ideal logging plugin to ship logs
