### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by caigang78** [docker/for-mac#46]
### Information

Diagnostic ID: 5EDFA5D9-EF23-411C-BBEF-D265D91079B0
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by caigang78** [comment]
Steps, download the latest images from the docker website. Copy it into the application. Run the docker.app

Then enter the terminal. input docker info. There will be Error response from daemon: Bad response from Docker engine

**Comment by caigang78** [comment]
Open the kitematic, there will be a setup error.

**Comment by samoht** [comment]
Do you have any `DOCKER_*` env variables in your shell. What is the Kitematic error (can you make a screenshot of the dialog)? Thanks!

**Comment by caigang78** [comment]
I did not have any docker_* env variables in my shell. 

I installed one of the beta version of 1.12 before and can run on this computer smoothly. But seems the docker will cause the latest mac pro's touch pad not to be clickable(This computer is bought on 2016.7.5). I went to apple store to be repaired this noon. They told me there is a software conflict and they doubt that is caused by docker..... They reset the computer to be the factory mode. And after that the docker can not be run.

**Comment by caigang78** [comment]
Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.8.0, build b85aac1,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51525,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:51529,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.0.16r105871,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | local Boot2Docker ISO version: v1.11.1,Error with pre-create check: "read tcp 192.168.10.101:51608->54.231.72.19:443: read: connection reset by peer",Opting out of crash reporting.,

**Comment by caigang78** [comment]
Above is the Kitematic error

**Comment by caigang78** [comment]
![screen shot 2016-08-01 at 4 10 46 pm](https://cloud.githubusercontent.com/assets/7031130/17288836/850bd28a-5809-11e6-8a4a-3f531af5a3ef.png)

This is the "about" of my computer

**Comment by samoht** [comment]
Can you click on 🐳 -> Preferences -> Uninstall/Reset -> Reset to Factory Default and see if that helps?

**Comment by caigang78** [comment]
After reset to factory default, it works. Thanks a lot

**Comment by caigang78** [comment]
But I lost all my images......

**Comment by samoht** [comment]
> They reset the computer to be the factory mode.

I guess that's not the only thing that you lost! If you have a timemachine backup, you can try to restore `~/Library/Containers/com.docker.docker/Data/com.docker.driver-amd64-linux/Docker.qcow2`

**Comment by caigang78** [comment]
Please kindly guide a little bit more about how to restore from Docker.qcow2. I searched the stackoverflow.com if I didn't backup the Docker.qcow2 before I reset the docker. That means I'll lose all my images permanently, right?
