### ISSUE TITLE
Operation couldn't be completed

### ISSUE THREAD

**Issue by AfternoonJones** [docker/for-mac#4601]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:EC0CDE21-9C0A-4EAE-8F83-F05F167BBDB0/20200523200334

### Information

  - macOS Version: Mac OS sierra 10.12.6

### Diagnostic logs

```
Docker for Mac: version... the latest version

```

### Steps to reproduce the behavior

  1. ...try to open docker, and it says operation couldnt be completed
  2. ...

**Comment by djs55** [comment]
Thanks for your report. Your logs have:
```
Error handling command: cannot create /usr/local/bin directory: mkdir /usr/local/bin: not a directory
```
Could you check that `/usr/local` is a directory and start the app again?

**Comment by AfternoonJones** [comment]
Hello,

Do you mean create a directory called /usr/local? or how could I check that
it is a directory?

thank you
ᐧ

**Comment by AfternoonJones** [comment]
Okay, yes I have confirmed it is a directory.

ᐧ

**Comment by AfternoonJones** [comment]
https://github.com/docker/for-mac/issues/4846

I created this issue after attempting I confirmed that usr/local was a directory and tried to install the helper again.

**Comment by AfternoonJones** [comment]
Here is the most recent diagnostic after upgrading my OS to Mojave; 

EC0CDE21-9C0A-4EAE-8F83-F05F167BBDB0/20200820003404
