### ISSUE TITLE
Docker desktop Edge 2.3.1.0 crash on restart

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#4603]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics (not possible, it crashed)
  - Diagnostics ID:

### Expected behavior

I did a restart on Docker Desktop for Mac (from the UI) and it crashed.

### Actual behavior

No crashing.

### Information

  - macOS Version: Catalina 10.15.4

### Diagnostic logs

Docker for Mac: version 2.3.1.0 (edge)

Here is the crash report

[Docker_2020-05-24-124634_rfay-mbp-2017.crash.zip](https://github.com/docker/for-mac/files/4674203/Docker_2020-05-24-124634_rfay-mbp-2017.crash.zip)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Thanks for your report -- I'll make an internal ticket.
