### ISSUE TITLE
unable to install Docker desktop app

### ISSUE THREAD

**Issue by aparna-pasa** [docker/for-mac#4604]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by aparna-pasa** [comment]
BC66DEB0-9255-4E21-9509-EA2E30DDC763/20200525102519

**Comment by djs55** [comment]
Thanks for your report. The logs have:
```
 AppDelegate: Bundle path: /private/var/folders/pc/yh8km_ts66b8_0yptn6mz1p40000gn/T/AppTranslocation/A237255F-1205-4914-92BF-5C1E5D75
30B1/d/Docker.app
```
and
```
Error handling command: Could not chmod /private/var/folders/pc/yh8km_ts66b8_0yptn6mz1p40000gn/T/AppTranslocation/A237255F-1205-4914-9
2BF-5C1E5D7530B1/d/Docker.app/Contents/Resources/bin/docker: chmod /private/var/folders/pc/yh8km_ts66b8_0yptn6mz1p40000gn/T/AppTranslocation/A237255F-1205-4914-92BF-5C1E5D7530B1/d/Docker.app/Contents/
Resources/bin/docker: read-only file system
```
The directory containing the `Docker.app` looks odd. Ideally the app would be dragged to the `/Applications` folder and run from there. Could you drag the app to `/Applications` and try again?
