### ISSUE TITLE
Could Not Copy Files From Docker

### ISSUE THREAD

**Issue by ovrdrvn** [docker/for-mac#4605]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Dump files in Docs folder
### Actual behavior
Error Message
### Information

  - macOS Version: 10.15.4

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@ovrdrvn unfortunately without a set of repro steps or a some uploaded diagnostics there's not much we can do. I'll close this issue but feel free to open a fresh one in future.
