### ISSUE TITLE
k8s failed to start up after upgrading docker desktop

### ISSUE THREAD

**Issue by chinafzy** [docker/for-mac#4606]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:BDC30132-A857-469C-B762-DA6943A2A714/20200526035606

### Expected behavior
k8s works

### Actual behavior
k8s keeps in starting state for more than 10 mins.

### Information

  - macOS Version: 10.15.4 (19E287)

### Diagnostic logs

```
Docker for Mac: 2.3.0.2

```

### Steps to reproduce the behavior

  1. k8s works well on a previous version of docker desktop
  2. upgrade docker desktop to 2.3.0.2
  3. k8s fail to start up.

**Comment by djs55** [comment]
@chinafzy thanks for your report. It can be tricky to diagnose the fault when k8s fails to start. Perhaps try "Reset Kubernetes Cluster" from the "Troubleshoot" menu, see [here](https://docs.docker.com/docker-for-mac/troubleshoot/).

**Comment by chinafzy** [comment]
> @chinafzy thanks for your report. It can be tricky to diagnose the fault when k8s fails to start. Perhaps try "Reset Kubernetes Cluster" from the "Troubleshoot" menu, see [here](https://docs.docker.com/docker-for-mac/troubleshoot/).

`Reset Kubernetes` is not enough. 
Deleting `~/Library/Group Containers/group.com.docker/pki/` and `~/.kube` works well.
