### ISSUE TITLE
Container networking does not work for loopback IP's except 127.0.0.1

### ISSUE THREAD

**Issue by tkaprol** [docker/for-mac#4607]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostic ID: 8FD42F68-89AA-48B1-A172-51DEFDF5CEC9/20200526092835

### Expected behavior
Docker-compose should assign specified loopback IP and port to the container. 

### Actual behavior
mDNSReponder hits %100 CPU and docker-compose hangs.  

### Information
  - Is it reproducible? Yes, it's always happening 
  - Is the problem new? Yes, the setup and projects was same before last updates.
  - Did the problem appear with an update? Yes
  - macOS Version: 10.15.4
  - Try to assign an additional loopback ip
```
pma:
    image: phpmyadmin/phpmyadmin
    ports:
    - "127.0.0.2:80:80"
```
### Diagnostic logs
```
Docker for Mac: 2.2.3.0 (43965) Edge
```

### Steps to reproduce the behavior

  1. Create a loopback IP: sudo ifconfig lo0 alias 127.0.0.2 up
  2. Assign the IP to a container in a docker-compose.yml.
  3. container will be assigned to a random port on 127.0.0.1

**Comment by ccimpoi** [comment]
Same on 2.3.0.4.

However if I run two nginx containers on 127.0.0.2 and 127.0.0.3 it binds to random ports on 127.0.0.1 but I can hit both correctly from the browser using the .2 and .3 IPs.
Still I would rather see the correct alias IPs in the `docker ps` output...

**Comment by ccimpoi** [comment]
Also if I have an alias IP 127.0.0.5 for 127.0.0.1.
Doing twice:
`docker run -p 127.0.0.5:80:80 nginx`
creates two containers:

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                               NAMES
08f03977340b        nginx                           "nginx -g 'daemon of…"   11 seconds ago      Up 10 seconds       127.0.0.1:32795->80/tcp                             hungry_wilson
cf1a59e88657        nginx                           "nginx -g 'daemon of…"   19 seconds ago      Up 18 seconds       127.0.0.1:32794->80/tcp                             eager_darwin
```

This is new behaviour.
The last stable Mac Docker was actually using the 127.0.0.5 IP to bind.
This behavior seems to keep changing with every stable version and it would be great to at least have it acknowledged and get an idea about where it's heading since it tends to break my local dev every time...
