### ISSUE TITLE
File still not changing inside docker container

### ISSUE THREAD

**Issue by Benedikt-Kluss** [docker/for-mac#4609]
Still the same problem as in [https://github.com/docker/for-win/issues/5530](url)
@stephen-turner 

File not changing inside docker container
  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6257013C-3614-4B49-AC9D-01A05AACEAA5/20200527081144

### Expected behavior
When a file is modified in the filesystem, it should be modified inside the container as well.

### Actual behavior
When a file is changed in the filesystem, it's not changed. It's the same as when the container started.

### Information
macOS Version: Catalina 10.15.4
Docker for Mac: version 2.3.02 stable

### Steps to reproduce the behaviour 
  1.  start a container with shared folder
  2. edit in windows a file in the shared folder
  3. the file is not changed in the container

**Comment by stephen-turner** [comment]
This is really puzzling, because we haven't changed that code in ages (on Mac). Did it work correctly in previous versions?

**Comment by glook** [comment]
@stephen-turner yep, i have same issue with latest 2 updates. 2.3.0.2 and 2.3.0.3

**Comment by stephen-turner** [comment]
What was the last version in which it worked correctly?

**Comment by glook** [comment]
i'm returned to 2.2.0.3

**Comment by Michel73** [comment]
I'm still on 2.1.0.5 cause of this bug.

**Comment by malcomio** [comment]
I've seen something very similar with Docker 2.3.0.3 on OS X Catalina 10.15.5

after restarting the container, the new version of the file was available inside

**Comment by dpnishant** [comment]
Seeing the same issue in 2.4.0.0 (48506) stable channel on macOS Mojave 10.14.6. I'm using `store/elastic/filebeat:7.8.1` container to monitor logs written on the host filesystem. `cat` inside the container shows the file contents as they were at the start of the container. The changes in the file contents are not reflected inside the container, until I restart the container. 

If the directory is empty during the container start and the logs files are created after the container is running then I can see the file names being populated inside the mount directory but the contents are not reflected. I'm yet to downgrade to confirm whether it works.

**Comment by dpnishant** [comment]
For anyone struggling with this problem, I confirm that downgrading `Docker Desktop CE` to version 2.2.04 (43472) fixes the problem. The changes to the file on the host system is reflected inside the container in real-time. It can be downloaded from https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2204

**Comment by stephen-turner** [comment]
You probably don't need to downgrade, try just switching back to osxfs in the settings.

**Comment by arubinofaux** [comment]
Disabling `gRPC FUSE` fixes the issue on MAC running version `2.4.0.0`

![Screen Shot 2020-10-20 at 2 19 58 PM](https://user-images.githubusercontent.com/1427640/96628093-c9f1b500-12df-11eb-87a4-5fd9c1479590.png)

**Comment by amanangira** [comment]
> You probably don't need to downgrade, try just switching back to osxfs in the settings.

Although this might work for most of the people here and it did work for me as well. But it stopped working again after some time. Going to try switching back to 2.1.0.5.

**Comment by nickhudkins** [comment]
I would be happy to try to help troubleshoot this, but this occurs on 2.5 as well on Big Sur. It appears to have worked for 2 changes to a file, and then began exhibiting the same behavior where file changes are not propagated.
