### ISSUE TITLE
Error installing Docker for Mac

### ISSUE THREAD

**Issue by Blue4x4Rebel** [docker/for-mac#461]
### Information

Diagnostic ID: 03472B98-9F59-41D7-B81E-F058F6F8678D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)

### Steps to reproduce

1. Copy whale to Applications
2. Launch

**Comment by mchiang0610** [comment]
Sierra bugs are being resolved with beta 25 at the moment. Please help test: 

https://download.docker.com/mac/beta/Docker.dmg 

Thanks!
