### ISSUE TITLE
Docker.VmnetdError error 1.

### ISSUE THREAD

**Issue by Kasjs** [docker/for-mac#4612]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info in this ticket, closing.
