### ISSUE TITLE
Minikube mounts stopped working after upgrade to 2.3.0.0:  unknown filesystem type '9p'

### ISSUE THREAD

**Issue by avbenavides** [docker/for-mac#4615]
- [X] I have tried with the latest version of my channel (Stable or Edge) - 2.3.0.3
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: B247C1EA-1184-4482-8805-F371F17A0DC0/20200528070629

### Expected behavior

Prior to this release it was possible to mount local directories into the docker container running minikube.

Refrer to https://github.com/kubernetes/minikube/issues/8202 

```
minikube mount mydir:/containerdir 
```

### Actual behavior

Mount fails with this message:

> 📁  Mounting host path mydir into VM as /containerdir ...
>     ▪ Mount type:   <no value>
>     ▪ User ID:      docker
>     ▪ Group ID:     docker
>     ▪ Version:      9p2000.L
>     ▪ Message Size: 262144
>     ▪ Permissions:  755 (-rwxr-xr-x)
>     ▪ Options:      map[]
>     ▪ Bind Address: 127.0.0.1:50941
> 🚀  Userspace file server: ufs starting
> 
> 💣  mount failed: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=50941,trans=tcp,version=9p2000.L 192.168.65.2 /containerdir" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=50941,trans=tcp,version=9p2000.L 192.168.65.2 /containerdir": exit status 32
> stdout:
> 
> stderr:
> mount: /containerdir: unknown filesystem type '9p'.
> 
> 
> 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
> 

### Information

minikube v1.9.2 on Darwin 10.15.4

### Diagnostic logs

```
Docker for Mac: 2.3.0.3(45519)

```

### Steps to reproduce the behavior

  1. Install minikube
```
brew install minikube
```
  2. Start minikube with the Docker driver
```
minikube start --driver=docker --memory 16gb --cpus 6  --disk-size 8gb
```
  3. Attempt to mount a directory
```
mkdir mydir
touch mydir/myfile
minikube mount mydir:/containerdir 
```

**Comment by kislerdm** [comment]
Having the same issue on similar system

**Comment by NorseGaud** [comment]
Ditto here.

**Comment by disrvptor** [comment]
Still a problem with the following versions

- Docker 2.3.0.4 (46911) Stable
- Minikube v1.13.0
- Darwin 10.15.6
- Filesystem (if it matters) APFS Encrypted

**Comment by jinlianch** [comment]
Has same issue, any solution for it?

**Comment by hayes-roach** [comment]
any updates?

**Comment by hayes-roach** [comment]
any updates?

**Comment by avbenavides** [comment]
No new AFAIK.
Haven't tested again since I got a workaround
