### ISSUE TITLE
Docker keeps crashing

### ISSUE THREAD

**Issue by coding-bunny** [docker/for-mac#4616]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 37E55B61-CDB9-49BF-855A-3FD04064FC59/20200528084744

### Expected behavior

I expected Docker not to crash when something goes wrong

### Actual behavior

Docker completely crashes

### Information
  - macOS Version: Catalina

### Diagnostic logs

Tried to run Diagnostics, but docker kept crashing before diagnostics were complete.

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Have ElasticSearch as Docker container and Oracle DB
  2. After a random time Docker crashes

<img width="729" alt="Screenshot 2020-05-28 at 10 45 40" src="https://user-images.githubusercontent.com/726661/83120047-cbbca100-a0d0-11ea-9cf8-75753d132f66.png">

**Comment by coding-bunny** [comment]
This error also appears now and then :

```
2020-05-28T09:33:17Z dockerd time="2020-05-28T09:33:17.752315680Z" level=debug msg="Client context cancelled, stop sending events"
```

**Comment by tmack8001** [comment]
I just got a similar error after the latest security release of MacOS was forced to my device.

Running MacOS Catalina v10.15.5
Docker version 19.03.8, build afacb8b

![image](https://user-images.githubusercontent.com/2158627/83154720-7a131700-a0ce-11ea-8248-63eed0ca82e9.png)

**Comment by coding-bunny** [comment]
installed the latest update, and it made the situation worse.
Containers are crashing way faster now.

**Comment by caoimhindenais** [comment]
I've also noticed this behaviour.

Running on Catalina : 10.15.5
Docker Desktop: v19.03.8

`2020-06-08T05:29:43Z dockerd time="2020-06-08T05:29:43.386276600Z" level=debug msg="Calling GET /v1.35/containers/4481b99d5aaa38d1c1d5858f92b57ea257f0bc539f1860b1866b186cbda9fc7f/json"`

I do also have an Oracle container running (18c) plus alot of other tomee, tomcat, apache, rabbitmq containers. Mainly CentOS based with the exception of Oracle and RabbitMQ

**Comment by coding-bunny** [comment]
Can we get some update regarding this? Is this being worked on?
Is there stuff we can try?
