### ISSUE TITLE
nftables sets are not supported

### ISSUE THREAD

**Issue by freeall** [docker/for-mac#4618]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I would expect sets to be a supported feature of `nftables`

### Actual behavior

Sets are not supported

### Information
  - macOS Version: 10.15.4 (19E287)

In `/proc/config.gz` this line appears `# CONFIG_NF_TABLES_SET is not set`

If this was set to `CONFIG_NF_TABLES_SET=y` it should be possible to use `sets`

### Steps to reproduce the behavior

To verify that `sets` are not supported, this can be used:

```
$ docker run --rm -ti --cap-add NET_ADMIN ubuntu:latest
root@3e52dcbc66bb:/# apt update
root@3e52dcbc66bb:/# apt install -y nftables
root@3e52dcbc66bb:/# nft add table ip filter
root@3e52dcbc66bb:/# nft add set filter test { type ipv4_addr \; }
Error: Could not process rule: Operation not supported
add set filter test { type ipv4_addr ; }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by djs55** [comment]
Thanks for your report. @freeall could you describe your use-case?

**Comment by freeall** [comment]
@djs55 We run infrastructure that has a very large number of routing rules. To do this we are using `nftables sets` on our servers. As the rest of our development setup is in Docker we want to move this piece into Docker as well.

This works well if the host is running Linux, but not if the host is running Docker For Mac.

Does this make sense?
