### ISSUE TITLE
Can not run any command (1.12.0-a)

### ISSUE THREAD

**Issue by schmunk42** [docker/for-mac#462]
### Expected behavior

Running any docker command.

### Actual behavior

Docker hangs.

### Information

Diagnostic ID: 
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. A bit heavier use on a container; disk I/O, CPU

**Comment by mchiang0610** [comment]
Similar to #119. Merging
