### ISSUE TITLE
Container won't start when mounting large mutagen cache

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4620]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20200528170936

### Expected behavior
Processes can run when using a mutagen mount

### Actual behavior
Process just hangs and never starts

### Information
  - macOS Version: 10.15.4

### Diagnostic logs
This isn't available in current versions of Docker for Mac and I removed the `venv` directories so I could test our node code (see #4619)

### Steps to reproduce the behavior
  1. Cache a large node directory (2 GB in my test)
  2. Start a process that mounts the directory ( like `docker run --rm -it -m 200M --memory-swap=200M -v $PWD:/usr/src/app -w /usr/src/app/deploy/db numetric/node_base:local sh`)
  3. Observer that it never actually starts

**Comment by gsong** [comment]
I have a 2.5G cached directory  (with node modules occupying 1.4G) and I haven't experienced any problems.

**Comment by daveisfera** [comment]
It eventually did start and has been performing much better since, so I wonder if this was just some initial caching/delayed response issue
