### ISSUE TITLE
Allow fine grained excludes configuration for Mutagen volume mounts

### ISSUE THREAD

**Issue by majames** [docker/for-mac#4621]
Hi! I was really excited to see the announcement at DockerCon that Docker for MAC will now support **Mutagen for more performant host volume mounting!** We actually built a tool at the organisation I work out that does something very similar (using [Watchman](https://facebook.github.io/watchman/) and `docker cp/rm` under the hood).

One killer feature that is currently **missing** is the ability to specify **fine-grained excludes** for the file sync list. I notice that there is limited support for excludes by [creating a docker volume](https://docs.docker.com/docker-for-mac/mutagen-caching/#avoiding-synchronizing-a-subdirectory), however our mono-repo is quite large and contains many generated nested directories and, therefore, creating an individual volume for each of them is infeasible.

**Are there plans to implement functionality that allow users to specify fine-grained includes/excludes?** Something similar to a `dockerignore` or [Watchman expressions](https://facebook.github.io/watchman/docs/allof) would be great!

**Comment by stephen-turner** [comment]
@djs55 Is this option available in the Mutagen config file?

**Comment by djs55** [comment]
In more recent development builds e.g.https://desktop-stage.docker.com/mac/edge/45494/Docker.dmg (discussed originally in the context of symlinks https://github.com/docker/for-mac/issues/4595#issuecomment-632264622 ) it's possible to add paths to ignore to the global mutagen config file e.g.
```
$ cat ~/.mutagen.yml
sync:
  defaults:
    ignore:
      paths:
        - somethingtoignore
      vcs: true
```
Thanks for the suggestions about `dockerignore` and Watchman expressions -- I'll investigate them!

**Comment by majames** [comment]
Thanks for the quick response! 

Had a look at the comment you linked. Does that mean that Docker Desktop will use the `~/.mutagen.yml` file when determining which files to sync? If so, then [global ignores](https://mutagen.io/documentation/synchronization/ignores) will probably be enough to unblock us from using this for now (although per directory ignores would be a nice feature!)

**Comment by djs55** [comment]
@majames yes, in the recent development build I linked Docker Desktop will use the `~/.mutagen.yml` file so you can override global defaults. Unfortunately the patch didn't make the current edge release. Let me know if it works for you!

**Comment by Wilkolicious** [comment]
Does the latest edge (2.3.2.0) use the `~/.mutagen.yml`?

I've tried all sorts of combinations to try to ignore some paths and they are still being sync'd across.

`~/.mutagen.yml`
```yml
sync:
  defaults:
    ignore:
      paths:
        - "/gomo/authoring/app/public/logs"
        - "app/public/logs"
        - "/app/public/logs"
        - "app/public/logs/"
        - "/app/public/logs/"
      vcs: true
```

And the file share path in docker config sync'd is: `/Users/phil.wilkinson/git/gomo-docker/gomo/authoring`

I restart docker after changing this file as I don't know when the mutagen config is used by docker.  Not sure where I am going wrong?

**Comment by Brenne** [comment]
@Wilkolicious I was just also playing around with the ignore paths. I'd recommend to read the mutagen [documentation](https://mutagen.io/documentation/synchronization/ignores#format-and-behavior)

If you want your path `/Users/phil.wilkinson/git/gomo-docker/gomo/authoring` to be ignored, I'd expect the following .mutagen.yml to work
```
sync:
  defaults:
    ignore:
      paths:
        - authoring
```

Afterwards disable and enable the sync again (at least this helped for me).

**Comment by djs55** [comment]
There's a new experimental build which adds support for `.dockerignore` files: https://desktop-stage.docker.com/mac/edge/46638/Docker.dmg . This allows fine-grained per-project control over which directories should not be synchronized. Note that, like the `~/.mutagen.yml` it will only take effect after the sync is disabled and re-enabled. There are a few other improvements so I've added a mini-changelog to this public gist: https://gist.github.com/djs55/0e8957e1e36431a43cbfd3caaffa9165 . If you get a chance to try it, let me know what you think!

**Comment by stephen-turner** [comment]
We have just released Desktop Edge 2.3.3.2, which adds support for the `.dockerignore` file as well as the `~/.mutagen.yml`. So I think this ticket can be closed now.

**Comment by LiorRabin** [comment]
Hi @stephen-turner @djs55.
What if I want my local environment to use mutagen.yml and building to staging/prod/other envs use the dockerignore file?
Is it possible to define somewhere by which of the files to sync/not to sync?
Thanks

**Comment by JussiMoisio** [comment]
Mutagen ignores don't work for me with latest Edge 2.3.4.0 (46980) (tried both ~/.mutagen.yml and .dockerignore). Struggled with this for a while, then installed the 46638 version from @djs55 link above and it works. Regression? Is it supposed to work with the latest Edge?

**Comment by thaJeztah** [comment]
I think the feature was updated in later versions, and now looks at a `.dockersyncignore` file, so that `.dockerignore` (which was meant to be used for `docker build` only can have different exclude rules than those used for syncing

**Comment by JussiMoisio** [comment]
Thanks, just read the changelog and noticed the `.dockerignore` -> `.dockersyncignore` change for 2.3.4.0. Works with that!

**Comment by thaJeztah** [comment]
Ah, yes, it's in the release notes for v2.3.4.0 https://github.com/docker/docker.github.io/blob/9050cd471791a8e7c393ac1986f36c103183abc3/docker-for-mac/edge-release-notes.md#docker-desktop-community-2340

**Comment by peterchyke** [comment]
> Hi! I was really excited to see the announcement at DockerCon that Docker for MAC will now support **Mutagen for more performant host volume mounting!** We actually built a tool at the organisation I work out that does something very similar (using [Watchman](https://facebook.github.io/watchman/) and `docker cp/rm` under the hood).
> 
> One killer feature that is currently **missing** is the ability to specify **fine-grained excludes** for the file sync list. I notice that there is limited support for excludes by [creating a docker volume](https://docs.docker.com/docker-for-mac/mutagen-caching/#avoiding-synchronizing-a-subdirectory), however our mono-repo is quite large and contains many generated nested directories and, therefore, creating an individual volume for each of them is infeasible.
> 
> **Are there plans to implement functionality that allow users to specify fine-grained includes/excludes?** Something similar to a `dockerignore` or [Watchman expressions](https://facebook.github.io/watchman/docs/allof) would be great!
> 
> 

#Release
