### ISSUE TITLE
Kubernetes always stuck at 'Starting'

### ISSUE THREAD

**Issue by ChrisJ60** [docker/for-mac#4624]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: DF020D0E-198A-4225-9F95-BF90567E965E/20200529091153

### Expected behavior

I expect Kubernetes to start

### Actual behavior

It is permanently stuck in the 'Starting' state

### Information

  - macOS Version: 10.15.5

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by snowgarden** [comment]
I had the same problem.  
macOS Version: 10.15.3
docker version:2.3.1.0(45408) channel:edge
kubernete version:v1.16.5

$ cat ~/.kube/config 
server: https://kubernetes.docker.internal:6443

$ cat /etc/hosts
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

$netstat -an |grep  6443
tcp4       0      0  127.0.0.1.6443         *.*                    LISTEN     
tcp4       0      0  127.0.0.1.6443         127.0.0.1.55132        TIME_WAIT  
tcp4       0      0  127.0.0.1.6443         127.0.0.1.55133        TIME_WAIT  
tcp4       0      0  127.0.0.1.6443         127.0.0.1.55134        TIME_WAIT  
tcp4       0      0  127.0.0.1.6443         127.0.0.1.55135        TIME_WAIT 
.....

not any connect

**Comment by xwang2713** [comment]
I have exact the same problem on the same Mac OS version.  Tried reset to factory settings, remove ~/.kube/* but nothing helps.

**Comment by djs55** [comment]
@ChrisJ60 thanks for your report. From the diagnostics it looks like a certificate problem:
```
error execution phase certs/apiserver: failed to write or validate certificate "apiserver": failure loading apiserver certificate: failed to load certificate: the certificate has expired
```
Perhaps first try the whale menu -> Troubleshoot -> Reset Kubernetes cluster. If that doesn't work then try whale menu -> Troubleshoot -> Reset to factory defaults.

**Comment by djs55** [comment]
@snowgarden @xwang2713 unfortunately there are many different ways this can happen. The next time it happens to you, could you upload diagnostics using the whale menu -> Troubleshoot -> Run Diagnostics, choose to upload them and then quote the id here? Thanks in advance.

**Comment by ChrisJ60** [comment]
Okay, a full 'reset to factory defaults' seems to have fixed it. Shouldn't be necessary though IMHO; seems like a bug of some kind.

Chris


On 1 Jun 2020, at 16:24, David Scott <notifications@github.com> wrote:


@ChrisJ60 <https://urldefense.com/v3/__https://github.com/ChrisJ60__;!!GqivPVa7Brio!IPbZKftNz2ISUjBOh3AkfxNB5vbbRb7lIXBThuo03_tHEQ35SdoNBT3yPvdg7ojncw$> thanks for your report. From the diagnostics it looks like a certificate problem:

error execution phase certs/apiserver: failed to write or validate certificate "apiserver": failure loading apiserver certificate: failed to load certificate: the certificate has expired
Perhaps first try the whale menu -> Troubleshoot -> Reset Kubernetes cluster. If that doesn't work then try whale menu -> Troubleshoot -> Reset to factory defaults.

**Comment by djs55** [comment]
@ChrisJ60 I'm glad the reset worked around the problem. I completely agree that it's a bug. I've seen this happen a few times so we should dig into it to see what we can do.

**Comment by tekumara** [comment]
Same problem here.

Docker for Mac 2.3.0.3 (45519)

Diagnostics ID: 1D52253A-06BD-4ECA-8188-316BAD9AFDD9/20200621033622

**Comment by tekumara** [comment]
Tried the following (nb: this will remove all images and containers)
* Quit Docker Desktop and start again
* Docker - Troubleshoot - Reset Kubernetes cluster
* Docker - Troubleshoot - Clean / Purge data
* Docker - Troubleshoot - Reset to factory defaults

Reset to factory defaults worked for me.

**Comment by tekumara** [comment]
Tried the following (nb: this will remove all images and containers)
* Quit Docker Desktop and start again
* Docker - Troubleshoot - Reset Kubernetes cluster
* Docker - Troubleshoot - Clean / Purge data
* Docker - Troubleshoot - Reset to factory defaults

Reset to factory defaults worked for me (the other steps didn't).

Diagnostics ID (working system): 1D52253A-06BD-4ECA-8188-316BAD9AFDD9/20200621093017

**Comment by tekumara** [comment]
Tried the following (nb: this will remove all images and containers)
* Quit Docker Desktop and start again
* Docker - Troubleshoot - Reset Kubernetes cluster
* Docker - Troubleshoot - Clean / Purge data
* Docker - Troubleshoot - Reset to factory defaults

Reset to factory defaults worked for me (the other steps didn't).

Diagnostics ID (working system): 1D52253A-06BD-4ECA-8188-316BAD9AFDD9/20200621093628

**Comment by davem-foreflight** [comment]
C30CEDE0-E2AE-45DA-BFF0-67864CEA621D/20200626171457 

From diagnostics upload ^ of same situation.

* Had this for many months but ignored since we don't use k8s. But needed to look at the prefs in docker desktop
* Tried uninstalling with AppCleaner and fresh download/install. Same result "k8s is starting" forever.
* rm -f ~/.kube and a fresh install. Same result
* Found a SO entry that said go to`~/Library/Group Containers/group.com.docker/settings.json` and edit with k8sEnabled: false

That last step finally worked so the docker desktop would at least let me see/edit the prefs.  From there i was able to disable all the k8s settings.

So, I'm unblocked, but no k8s.

**Comment by sbaier1** [comment]
Same problem here, ID 5250531A-F8BF-48D1-A097-A62EF45D7C5E/20200806082719

**Comment by Moser-ss** [comment]
Hey same problem here:
ID 511D7588-EC21-4741-A2F0-534EFBA7572D/20200810172230
Docker4Mac version 2.3.0.4 (46911)
I had to reset to factory

**Comment by baozilaji** [comment]
Does anyone have solved this problem?

**Comment by Grravey** [comment]
I had this issue after upgrading to 2.3.0.4, this comment provided the solution that worked for me: https://github.com/docker/for-mac/issues/3649#issuecomment-489141393

> I found this other issue: docker/for-win#3799 which mentions that exact error. It seems that by deleting the PKI folder fixes the issue.
The analogous folder in Mac is: ~/Library/Group Containers/group.com.docker/pki
rm it (or mv it), restart the Docker engine, and Kubernetes comes up just fine.

**Comment by bejaneps** [comment]
Having same issue here

**Comment by Kuanlin-Chen** [comment]
Reset to factory defaults worked for me.
Mac OS version: 10.14.6
Docker desktop version: 3.1.0 
Kubernetes version: 1.19.3

**Comment by simonpie** [comment]
Same problem here,
Mac OS version: 1.3 (20E5172i)
Docker desktop version: 3.1.0 (51484)
Kubernetes version: 1.19.3

The "reset kubernetes cluster" button in the troubleshoot windows is greyed-out, but it is not in the kubernetes tab.  Alas it does not work.

As I dont want to reset docker to factory setting just yet, as I need it, I shall try it in a few days.

**Comment by pakkpl** [comment]
I have same problem :(
Docker 3.1.0 version

**Comment by htirghoda** [comment]
> Same problem here,
> Mac OS version: 1.3 (20E5172i)
> Docker desktop version: 3.1.0 (51484)
> Kubernetes version: 1.19.3
> 
> The "reset kubernetes cluster" button in the troubleshoot windows is greyed-out, but it is not in the kubernetes tab. Alas it does not work.
> 
> As I dont want to reset docker to factory setting just yet, as I need it, I shall try it in a few days.

https://github.com/docker/for-mac/issues/5422#issue-822230250 Same Issues

**Comment by CafeLungo** [comment]
Me too: https://github.com/docker/for-mac/issues/5422#issuecomment-799460666

A factory reset did solve it on my macOS 11.2.1 machine, but I didn't have any images I cared about there. Not really keen on doing that on my other machine.

**Comment by prctjliwei** [comment]
I had the same issue for my docker desktop after I enabled k8s. I tried the approach of deleting the PKI folder and restarted docker desktop, the k8s worked.
I am running docker desktop win10, the pki folder is under C:\Users\my user name\AppData\Local\Docker

**Comment by msquires** [comment]
Same problem for me on Mac (10.15.7) with Docker 3.2.2.  Re-starting/Re-Setting Docker and/or K8s didn't work.

Finally got it working by:
1. Stopping Docker
2. Deleting ~/Library/Group Containers/group.com.docker/pki folder
3. Restarting Docker

**Comment by thsubaku9-dgraph** [comment]
@msquires you absolute beauty

**Comment by rmagee** [comment]
@msquires you absolute beauty

**Comment by jwtodd** [comment]
failing for me :(    osx (11.2.3) docker-desktop (3.2.2)

**Comment by DDusky** [comment]
@msquires it's work, you save my day, thanks
