### ISSUE TITLE
Docker Stable 2.3.0.3: High hypervisor CPU utilization with no containers running

### ISSUE THREAD

**Issue by dmlary** [docker/for-mac#4625]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 81A4A4D6-FAAE-4899-B89D-AEA9E8FF7455/20200529151830

### Expected behavior
With no containers running, I expect the hypervisor to not be running at 200% cpu utilization

### Actual behavior
It is at >200% cpu utilization

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes.  Happens after each reboot.
  - Is the problem new? Yes.  Updated docker to latest version yesterday and immediately saw problems.
  - Did the problem appear with an update? yes.
  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: Diagnose succeeded

```

### Steps to reproduce the behavior
1. Upgrade to 2.3.0.3

**Comment by ricardopinto** [comment]
I'm also having this same issue on 2.3.0.3 update, running mac OS 10.15.4.

Diagnostic ID: 3C46E3C5-41FE-4889-AB74-0EB724D78DB4/20200529175403

Is there a simple way to downgrade back to 2.3.0.2?

**Comment by djs55** [comment]
@dmlary thanks for your report. I had a look inside the diagnostic logs for the VM and I can see various processes running including :
```
 1298 root      0:00 runsvdir -P /opt/gitlab/service l
 1309 999       0:00 node main.js
 1969 root      0:00 {rake} /usr/local/bin/ruby /usr/local/bin/rake docker-run
```
Perhaps these containers are set to [start automatically](https://docs.docker.com/config/containers/start-containers-automatically/)? I suspect they are responsible for consuming excess CPU.

Hopefully the containers are visible in `docker ps` and in the dashboard: from the whale menu -> Dashboard. Let me know if not.

You can also enter the VM and look around with commands like `top` using:
```
docker run -it --pid=host --privileged justincormack/nsenter1
```
I expect that the CPU will drop when these containers are stopped. If you're still seeing excess CPU after stopping all containers, please upload a new set of diagnostics.

**Comment by dmlary** [comment]
@djs55 At the time I did check `docker ps` and saw nothing running, but have no screenshot of that.  That container was part of a docker-compose setup that at one point was set to start automatically, but had been disabled.

I uninstalled 2.3.0.3 and downgraded to 2.2.0.5 to get past the problem last week.  I'll try to reproduce today by re-adding those containers via docker-compose, disabling, then upgrading.

**Comment by dmlary** [comment]
Yes, this was the issue.  I had a container that was failing to restart constantly, and I just missed it.  Kept the CPU pegged for hours.

Thank you.

**Comment by djs55** [comment]
@dmlary glad the issue was resolved! I think this scenario is probably quite common and I wonder if we need to do more to help highlight it. Do you use the new "Dashboard" UI feature at all? It's available from the Whale menu -> Dashboard. Having said that, I'm not sure what a failing and constantly restarting container would look like in it. Maybe we would have to show the actual stream of start/stop events to make it clear what's happening? I'm not sure.

**Comment by dmlary** [comment]
You may be on to something there.  I definitely did not run `docker ps`, but I did have the Dashboard UI open.  The problem is that they are ordered by creation date (I believe), and in the month since I worked on that gitlab container, I had created 20-30 other containers.  So looking at the Dashboard, every container visible at the top of that list was stopped; I just never scrolled all the way down to the bottom of the list.

Possible solutions:
* pop running containers up to the top of the list
* If a container restarts N times in a minute, put up a mac notification?

**Comment by stephen-turner** [comment]
@stlucek Shouldn't running containers be at the top?
