### ISSUE TITLE
Docker Starting Error on Mac. MacOS version Catalina (Diag ID 0605A0AF-928E-4B4A-8904-733C5C561EA1/20200601004056)

### ISSUE THREAD

**Issue by purna-roy** [docker/for-mac#4629]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Thanks for your report. Your logs have
```
Error handling command: Could not chmod /private/var/folders/1r/wgj1b6ln4g50yph8jgqlzl080000gp/T/AppTranslocation/01AEFB0B-A7AE-41A3-9A60-7055D8CB6B67/d/Docker.app/Contents/Resources/bin/docker: chmod /private/var/folders/1r/wgj1b6ln4g50yph8jgqlzl080000gp/T/AppTranslocation/01AEFB0B-A7AE-41A3-9A60-7055D8CB6B67/d/Docker.app/Contents/Resources/bin/docker: read-only file system
```
Could you verify where you have installed the `Docker.app` program to? It needs to be dragged into `/Applications` and run from there.

**Comment by purna-roy** [comment]
Hi David,

I have the docker.dmg installed in the /Applications folder on my Mac as
shown in the screenshot below. I had to move the actual Docker Executable
there, and then it ran fine. By Thank you. By the way, is there a way to
run Windows Containers in my Docker version on Mac? Please let me know.
Thanks,

Purna Roy

**Comment by djs55** [comment]
@purna-roy I'm glad you got it working! Unfortunately it's not possible to run Windows Containers in Docker Desktop on Mac.

I'll close this issue but feel free to open a new one if you encounter another problem.

**Comment by purna-roy** [comment]
Thanks a lot, David. I have a Docker Desktop on a Windows machine as well,
and it can run both Linux and Windows Containers. So, I am good there.
Thanks for your clarification.

Purna
