### ISSUE TITLE
I can't use docker command 

### ISSUE THREAD

**Issue by BruceYangMan** [docker/for-mac#463]
### Information

Diagnostic ID: B016B19D-D85F-49CC-BB9E-37945EA71D97
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/bruceyang/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/B016B19D-D85F-49CC-BB9E-37945EA71D97/20160830-085431/qemu-img-check.stdout 2> /tmp/B016B19D-D85F-49CC-BB9E-37945EA71D97/20160830-085431/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119
