### ISSUE TITLE
Fatal Error: 7442C716-DE15-4BE8-80CF-967E42DEDC14/20200601034033

### ISSUE THREAD

**Issue by elngovind** [docker/for-mac#4630]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@elngovind your logs show the following error:
```
 Error handling command: Could not chmod /private/var/folders/w2/mpshtshn5qb01gly6zsv91q40000gn/T/AppTranslocation/B33F750E-71EA-4D5B-8140-5BF607C5D059/d/Docker.app/Contents/Resources/bin/docker: chmod /private/var/folders/w2/mpshtshn5qb01gly6zsv91q40000gn/T/AppTranslocation/B33F750E-71EA-4D5B-8140-5BF607C5D059/d/Docker.app/Contents/Resources/bin/docker: read-only file system
```
Could you check the folder where you are running `Docker.app` from? It needs to be somewhere read-write like `/Applications`

**Comment by elngovind** [comment]
The issue got solved.
What I did to solve the issue:
1. Went to the applications folder and removed the Docker Application as it was existing in corrupt status.
2. Copied the new one in the same location. ie. applications folder
3. Checked and it was working
