### ISSUE TITLE
tcp socket send so many [TCP Keep-Alive] packet

### ISSUE THREAD

**Issue by cuisj** [docker/for-mac#4631]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

no send tcp keep-alive

### Actual behavior

tcp socket keep-alive packet per second。in docker container, no send, but capture packet from macOS network interface en0, found a lot of [TCP Keep-Alive] packets.

### Information

  - macOS Version:

10.15.5

### Diagnostic logs

```
Docker for Mac:
Engine: 19.03.8
Notrary:0.6.1
Compose: 1.25.5
Credential Helper: 0.6.3
Kubernetes: v1.16.5

```

### Steps to reproduce the behavior

1.docker pull cenos
2.docker run -it centos bash
3.write a c programm, like this:
```
#include <sys/types.h>
#include <sys/socket.h>
#include <stdio.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/shm.h>
#include <netinet/tcp.h>
#include <errno.h>
 
#define MYPORT  55400
#define BUFFER_SIZE 1024
char* SERVER_IP = "10.21.16.180";
 
int main()
{
    int err = 0;

    int sock_cli = socket(AF_INET,SOCK_STREAM, 0);
    

    struct sockaddr_in servaddr;
    memset(&servaddr, 0, sizeof(servaddr));
    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(MYPORT);
    servaddr.sin_addr.s_addr = inet_addr(SERVER_IP);
    
    printf("connecting %s:%d\n",SERVER_IP,MYPORT);

    if (connect(sock_cli, (struct sockaddr *)&servaddr, sizeof(servaddr)) < 0)
    {
        perror("connect");
        exit(1);
    }
    printf("connect success \n");
    
    int keepAlive = 0;
    err = setsockopt(sock_cli, SOL_SOCKET, SO_KEEPALIVE, (void *)&keepAlive, sizeof(keepAlive));
    if (err < 0) {
        printf("%d %s\n", errno, strerror(errno));
    }

    socklen_t socklen = sizeof(int);

    getsockopt(sock_cli, SOL_SOCKET, SO_KEEPALIVE, &keepAlive, &socklen);
    printf("keepalive: %d\n", keepAlive);

    
    sleep(20);
    
    close(sock_cli);
    return 0;
}
```
4. compile and run
5. use wireshark, capture packet on macOS's en0

**Comment by djs55** [comment]
@cuisj thanks for your report. We enable TCP keep-alives on external connections so we can detect when connections disappear (e.g. when the host network environment changes). This allows us to free resources, see moby/vpnkit#278

Is the presence of keep-alive packets causing a particular problem? If so, could you describe more? Thanks!

**Comment by cuisj** [comment]
TCP keepalive packets are sent too frequently. When the network status is not good, there will be a large number of retransmissions, which will affect the speed of data transmission.

**Comment by cuisj** [comment]
so how to close it ?

**Comment by cuisj** [comment]
it cost too much $$$， so how to close it ?
