### ISSUE TITLE
Docker container cannot access to VPN after a while

### ISSUE THREAD

**Issue by miladrahimi** [docker/for-mac#4632]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I connect to FortiVPN, the running containers should have access to the network behind the VPN, and **It should work always**.

### Actual behavior
It works for a while (some days), then it gets broken. I remove and install Docker again to fix it. I've done it every month and I'm tired of doing it.

### Information

  - macOS Version: 10.15.4

### Steps to reproduce the behavior

  1. Connecting to VPN (Forti VPN for me)
  2. Using Docker for a while

**Comment by djs55** [comment]
@miladrahimi thanks for your your report. Unfortunately without a diagnostics report containing logs there's very little we can do. The next time the system is in a broken state, could you go to the whale menu -> Troubleshoot -> Run Diagnostics , then upload them and report the id here?
