### ISSUE TITLE
Unable to start Docker for Mac after installation

### ISSUE THREAD

**Issue by dragon9786** [docker/for-mac#4634]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `B23DC3C4-3DB7-4144-9C2B-02931EEA4C0F/20200602030725`

### Expected behavior
* Docker should start up

### Actual behavior
* Getting an error and unable to start docker

### Information

  - macOS Version: `10.14.6 (18G103)`

**Comment by niralkk** [comment]
@dragon9786 I'm facing same issue, are you able to workaround ?

**Comment by dragon9786** [comment]
Yes. There seems to be an issue with the executable opened on the mounting volume. Once you drag and drop this into the Applications folder, trying to open it from there seems to work.
