### ISSUE TITLE
Fatal Error com.docker.backend cannot start Exit code 1

### ISSUE THREAD

**Issue by konniodev** [docker/for-mac#4639]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BF21B40B-A276-42A2-898A-7E99C54025CF/20200602195756

### Expected behavior
On Launcher, I would like to double click Docker app and start it.

### Actual behavior
From the launcher, I click on Docker Desktop and a message appears.
Fatal Error
com.docker.backend cannot start
Exit code 1
"Reset Docker to factory defaults", "Diagnose & Feedback" and "Exit"

### Information
The version 2.0.0.3 works fine, but any version above doesn't work and same issue happens.
Some similar issues related to config.json and capitalization of credSstore instead of credsStore. Here is my config.json:
{
  "credsStore" : "desktop",
  "experimental" : "disabled",
  "auths" : {

  },
  "stackOrchestrator" : "swarm"
}

  - macOS Version: macOS Catalina 10.15.5

### Diagnostic logs
"Diagnose & Feedback" doesn't work on gui. I've run it from Terminal.
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Steps to reproduce the behavior
  1. Install the latest version
  2. Try to start docker

Tried to reset configuration, doesn't work.
One important detail, my home directory is located on a volume with space on name /Volumes/Macintosh HD - Data/myusername
<img width="666" alt="Screen Shot 2020-06-02 at 17 15 34" src="https://user-images.githubusercontent.com/53025476/83566399-54cf4000-a4f6-11ea-8416-ab3a74630c4e.png">
<img width="710" alt="Screen Shot 2020-06-02 at 17 15 42" src="https://user-images.githubusercontent.com/53025476/83566407-57ca3080-a4f6-11ea-86f6-3851e041caed.png">
<img width="666" alt="Screen Shot 2020-06-02 at 17 15 47" src="https://user-images.githubusercontent.com/53025476/83566410-5862c700-a4f6-11ea-933b-3e26cdc0b904.png">
<img width="555" alt="Screen Shot 2020-06-02 at 17 16 05" src="https://user-images.githubusercontent.com/53025476/83566413-58fb5d80-a4f6-11ea-9f9c-15b40a9f9955.png">

**Comment by venky999** [comment]
I am seeing exactly same issue as well

**Comment by tvdiepen** [comment]
Had the same issue; i could fix it by changing the name of my volume to a name without spaces. Was "Macintosh HD - Users", renamed to "Users". 

(used diskutil rename "Macintosh HD - Users" "Users", then changed the location of my home directory in Users and Groups configuration).
