### ISSUE TITLE
downloading images freezes

### ISSUE THREAD

**Issue by PaulCannell** [docker/for-mac#464]
### Expected behavior
should pull down docker image
### Actual behavior
freezes during install 
### Information

Diagnostic ID: 47767C74-C8F1-40DD-B03F-E34DDB6DC6C3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/paulcannell/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/47767C74-C8F1-40DD-B03F-E34DDB6DC6C3/20160830-072430/qemu-img-check.stdout 2> /tmp/47767C74-C8F1-40DD-B03F-E34DDB6DC6C3/20160830-072430/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
docker run mysql:5.6
Unable to find image 'mysql:5.6' locally
5.6: Pulling from library/mysql

357ea8c3d80b: Downloading [=====================>                             ] 22.54 MB/51.37 MB
It just freezes at this point .

Ive tried uninstalling and reinstalling docker with no avail

**Comment by PaulCannell** [comment]
update. I removed the docker files that it says it had an error with and reinstalled docker again and things appear to be better. Will close if I manage to complete installation today

**Comment by mchiang0610** [comment]
@PaulCannell Any update on this?   Some of our users have had luck by resetting to factory defaults. 

Let me know if it's not working and I'll reopen.
