### ISSUE TITLE
stat no such file or directory

### ISSUE THREAD

**Issue by godforger** [docker/for-mac#4645]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5F1CCDD1-29D7-442F-83E5-F7210FD88473/20200604163758

### Actual behavior
![image](https://user-images.githubusercontent.com/10621751/83789177-08733400-a69f-11ea-95b3-0c9490140b4c.png)

### Information

  - macOS Version: 10.15.5

### Diagnostic logs

```
Docker for Mac: stable 2.3.0.3
```

**Comment by thaJeztah** [comment]
the error indicates that your `vendor` stage does not have a `/app/vendor/` directory

**Comment by thaJeztah** [comment]
FWIW, in Docker v20.10, we made some improvements in the error messages to make them slightly less confusing when using the "classic" (non-BuildKit) builder; https://github.com/moby/moby/pull/41327 (and a tracking issue for BuildKit https://github.com/moby/buildkit/issues/1647)
