### ISSUE TITLE
Repeated/pressure mounts during `docker run` cause failure to mount (2.3.1.0)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#4647]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4878CE31-EDDB-4988-A949-52FEC38CFC79/20200604213107

### Expected behavior

Docker Desktop for Mac 2.3.1.0; no mutagen caching, just ordinary bind mount.

Repeated sequential runs of `docker run` with bind-mounted volume should continue to work. But eventually I get a failure to mount.

Reproduction script:  https://gist.github.com/rfay/aa8bd7060d9542112e7f86003d94ceca#file-makedockerfail-sh

I apologize that the repro script is specific to ddev; it's a part of the pre-push git hook that I've extracted to make a realistic but fairly simple case.  It does require golang just to make sure the directory is set up right. 

To use it, `cd ~/tmp` (or wherever) and `chmod +x makedockerfail.sh` and `./makedockerfail.sh`

It will run for an iteration or two then fail.

### Actual behavior

You'll eventually get an error like

> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Sometimes it's accompanied by something like

```
WARN [config_reader] Can't make abs path for "./cmd/...": getwd: no such file or directory
ERROR 2020/06/04 21:28:38 Couldn't discover absolute path
ERROR 2020/06/04 21:28:38 getwd: no such file or directory
ERROR 2020/06/04 21:28:38 Couldn't discover absolute path
ERROR 2020/06/04 21:28:38 getwd: no such file or directory
ERROR 2020/06/04 21:28:38 Couldn't discover absolute path
ERROR 2020/06/04 21:28:38 getwd: no such file or directory
WARN [config_reader] Can't pretty print config file path: can't get working directory: getwd: no such file or directory
WARN Failed to discover go env: failed to run 'go env': exit status 1
ERRO Running error: context loading failed: failed to load program with go/packages: err: exit status 1: stderr: 2020/06/04 21:28:38 cannot determine current directory: getwd: no such file or directory
```

But the bottom line seems to be that the workdir doesn't get mounted after a few iterations of `docker run`. 

### Information

  - macOS Version: 10.15.4 and 10.15.5

### Diagnostic logs

```
Docker for Mac: version: 2.3.1.0

```

### Steps to reproduce the behavior

Run the script linked above.

**Comment by stephen-turner** [comment]
Thanks, @rfay. Do you believe this is new in 2.3.1.0 (not necessarily that you've tested it but that you would have seen problems before if it was present before), or do you not have any belief about previous versions?

**Comment by rfay** [comment]
So I definitely don't have any information about how old this is. My pre-push hooks were using locally installed tools (except for the golanci-lint) and a contributor tried to use them and of course it was a disaster. So I switched to the obvious correct choice, dockerizing the check. Now my pushes fail about 1/3 to 1/2 of the time and it's frustrating. 

I have always had some instability with just the golanci-lint, but it was usually timeouts; I always assumed docker was "tired" :) Now with 3 checks all using docker it fails a lot. 

But the bug may have been there a really long time; I hadn't exercised it this way.

**Comment by rfay** [comment]
I just tested this with the provided script and didn't get the reported response, so maybe it's fixed.
