### ISSUE TITLE
Docker Desktop for mac stuck in starting forever

### ISSUE THREAD

**Issue by fera17-zz** [docker/for-mac#4649]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0572DC43-A127-45F6-834D-B81C6056A77B/20200607131607

### Expected behaviour
Docker Desktop for mac should start
### Actual behaviour
Docker Desktop for mac stuck on "Docker Desktop is starting" forever. Even if I try to restart my laptop

### Information

  - macOS Version: Catalina 10.15.4
 
### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by JustinCoded** [comment]
I'm having the same issue on macOS Version: Mojave 10.14.6. See Diagnostics Id: 348ACF5A-A84A-46B7-80B6-3575589B309B/20200615143755

**Comment by ivan-kysil-sp** [comment]
Have same issue,
macOS version: 10.15.6 Catalina
Docker Desktop version: 2.3.0.4
