### ISSUE TITLE
cannot remove zombie service

### ISSUE THREAD

**Issue by opichon** [docker/for-mac#465]
### Actual behavior
docker service rm my_web
`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded`

I have restarted docker, uninstsalled and reinstalled docker, to no avail. The my_web service is still there.
### Information

Diagnostic ID: E035F714-80C0-4DB4-9983-55BDFFC5D153
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)

### Steps to reproduce

1. docker service rm my_web
2. ...

**Comment by rjohnson3** [comment]
Just recreated this same issue on Ubuntu 16.04.

**Comment by mchiang0610** [comment]
Not enough steps to reproduce unfortunately. 

Happy to reopen if we can get all the details for reproduction. 

Thanks!
