### ISSUE TITLE
not able to install docker

### ISSUE THREAD

**Issue by souradeepmajumdar05** [docker/for-mac#4652]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @souradeepmajumdar05 

You need to tell us more details about your trouble or upload a diagnostic via Docker Desktop if possible.
