### ISSUE TITLE
Docker installation in macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by databitesuk** [docker/for-mac#4653]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wyq977** [comment]
READ the FAQ and upload the Diagnostics ID pls

**Comment by ulrich** [comment]
Hello @databitesuk 

You need to tell us more details about your trouble or upload a diagnostic via Docker Desktop if possible.

**Comment by databitesuk** [comment]
Thanks ulrich and I managed to resolve this issue and Docker is now successfully working on macOS
