### ISSUE TITLE
Issue with Docker setup

### ISSUE THREAD

**Issue by jackng310** [docker/for-mac#4656]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by levin8023** [comment]
Docker for Mac: 10.14.6 (18G84)

1. It occurred when starting the app...
![image](https://user-images.githubusercontent.com/30230347/84097427-280bb300-aa37-11ea-9a41-89400331a06a.png)
