### ISSUE TITLE
Cannot install docker on mac

### ISSUE THREAD

**Issue by sonalisankpal101** [docker/for-mac#4657]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
Hello @sonalisankpal101 

We need more information about your trouble.
