### ISSUE TITLE
Docker for mac is up but docker commands time out.

### ISSUE THREAD

**Issue by prasadavhad** [docker/for-mac#466]
### Information

Diagnostic ID: C939AC0E-9B6B-4830-BDFE-0C3A74AFFEF3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1605)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
Saw this happening when I switch networks. Workaround is to quit docker and re-open.

**Comment by SirNexus** [comment]
I have this error as well.

**Comment by dave-tucker** [comment]
Hi @prasadavhad , thanks for the report.
I'm going to close this as you have a workaround for now. We have an issue tracking the reboot after networks being switched which we hope will be fixed in a future beta (and then in the stable channel).
