### ISSUE TITLE
Kubernetes does not start

### ISSUE THREAD

**Issue by sinai-doron** [docker/for-mac#4670]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:CEEBD691-3564-4077-9720-CDEE73217CCD/20200611173545

### Expected behavior
Kuberneted should start

### Actual behavior
Kubernetes stuck on "kebernetes is starting...."
### Information
I tried multiple times reseting my kubernetes and docker, even formatted my machine. but stil either kubernetes does not start or it unaccessable with:
"Unable to connect to the server: net/http: TLS handshake timeout"

  - macOS Version: 10.15.5

### Diagnostic logs

```
Docker for Mac: version 2.3.0.3

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by williamli** [comment]
@sinai-doron are you using a non-default location for images by any chance? I find that if I reset the location back to default, Kubernetes will get started fine without issue.

**Comment by williamli** [comment]
@sinai-doron I did multiple tests over the weekend to confirm that's the case for me. As soon as I use the local storage for docker, Kubernetes will start up without issues.
