### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by levin8023** [docker/for-mac#4678]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86DFB7C4-3FC4-4120-9788-06E53BE51A85/20200615014522

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: lastest from ow

```

### Steps to reproduce the behavior

  1.  When i start up the app, it occurred:
       Fatal Error
       Failed to analyse
       The data couldn’t be read because it isn’t in the correct format.
![image](https://user-images.githubusercontent.com/30230347/84610518-64368c00-aeed-11ea-88ed-8b126feeb1ba.png)
  2. I have tried to Reset Docker to factory defaults, but no use ...

**Comment by levin8023** [comment]
Enable Intel Virtualization Technology  Worked ！

My machine is Hackintosh, BIOS set this ~

**Comment by BondoS** [comment]
I've the same issue, I'm running macOS 10.14.6 too but in native mac machine
I've been searching for hours about a fix without any success :(
