### ISSUE TITLE
Docker for Mac crashes during startup

### ISSUE THREAD

**Issue by hsheth2** [docker/for-mac#468]
### Expected behavior
Docker starts without errors.

### Actual behavior
Docker crashes during startup with message `vmstateevent invalid json:`

### Information

Diagnostic ID: E6E899C5-1C7C-46E2-B00E-3EE23EF29DAA
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Installed Docker for Mac during beta phase
2. Updated and switched to stable version
2. Start docker

**Comment by hsheth2** [comment]
Closing this issue as a duplicate of #447

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by hsheth2** [comment]
It does seem to be working with the latest GM Seed!
