### ISSUE TITLE
"Docker is already running" when launching from dock

### ISSUE THREAD

**Issue by jamesmcroft** [docker/for-mac#4680]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When launching the Docker Desktop app from the macOS dock, the application should load to the dashboard. If Docker is already running, it should launch into the existing running dashboard.

### Actual behavior

When launching the Docker Desktop app from the macOS dock, a **Fatal error** alert is shown explaining that Docker is already running.

### Information

  - macOS Version: Catalina 10.15.5
  - Docker Version: 2.3.0.3 (45519)
  - Is it reproducible? Yes
  - Is the problem new? Unsure, don't believe it's ever worked

### Steps to reproduce the behavior

  1. Have Docker running without opening Docker Desktop app (if open, close it)
  2. Open the Docker Desktop app from the dock
  3. Fatal error alert is shown

**Comment by tlorenzi** [comment]
I have the same issue, did you ever figure it out?

**Comment by basvandergraaff** [comment]
I don't see how to get the GUI back in any way. Launching from the dock or terminal gives the same fatal error, selecting 'dashboard' from the docker menu bar doesn't do anything at all. 

Stopping  'docker desktop' process in activity monitor still gives me the error. Shutting down docker completely does get it back, but it disappears again after a while. Gui isn't necessary to use docker, but it's very beginner-unfriendly.

**Comment by jamesmcroft** [comment]
@basvandergraaff to get the GUI back you have to click the Docker item in the menu bar and select the dashboard option. This will then load it up as it was.

**Comment by basvandergraaff** [comment]
> @basvandergraaff to get the GUI back you have to click the Docker item in the menu bar and select the dashboard option. This will then load it up as it was.

Thanks for your reply, jamesmcroft. But that would be the first thing I'd try (as I stated in my post), and it doesn't do anything.

**Comment by nicolas-miari** [comment]
@jamesmcroft So, "already running" means Docker is stationed in the macOS Menu Bar...? If I choose "Quit Docker Desktop":

<img width="290" alt="Screen Shot 2020-08-03 at 13 52 16" src="https://user-images.githubusercontent.com/1000912/89147104-b6606900-d590-11ea-88f8-339c012c45ad.png">


...I will be able to re-launch it from the Dock or the Applications folder?

**Comment by jamesmcroft** [comment]
@nicolas-miari that should be correct. I am able to re-open by quitting Docker Desktop and re-launching from the dock or app folder. 

In theory, you should be able to avoid quitting by tapping Dashboard in that menu. It will bring the dashboard back up and it will appear open in the Dock.

**Comment by jaanus** [comment]
“me too”, this keeps happening with 2.3.0.4

When I click Dock icon and Docker is not already running, Docker starts correctly (but no GUI comes up, just the menubar icon, I suppose that is as it should be.)

When I click Dock icon and Docker is already running, I get “Fatal error: Docker is already running”

<img width="710" alt="Screenshot 2020-08-21 at 10 57 13" src="https://user-images.githubusercontent.com/184253/90866821-1a5e9c00-e39d-11ea-9f8a-d3b7c95c7dd0.png">

**Comment by AHLinJie** [comment]
you can : ps -ef|grep docker|grep desktop. 
then kill that progress

restart docker desktop
