### ISSUE TITLE
docker pull failed, won't start.

### ISSUE THREAD

**Issue by redolphin** [docker/for-mac#4681]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7928F11C-855A-458D-B21E-0B70DB84B335/20200616000902

### Expected behavior
docker start and pull image

### Actual behavior

  - Time to time, couldn't start it
  - docker pull returns  following errors
```
layers from manifest don't match image configuration
filesystem layer verification failed
```

### Information
  - macOS Version: 10.15.5

### Steps to reproduce the behavior
  1. Install docker for mac
  2. docker pull image

**Comment by redolphin** [comment]
Still can't pull images from the hub.
-------------------------------------------------------------
➜  group.com.docker docker pull percona:8
8: Pulling from library/percona
524b0c1e57f8: Extracting [==================================================>]  75.88MB/75.88MB
02e386a719ce: Download complete
e0b0b666a45f: Download complete
00b1a9d6f75e: Download complete
c189211552cd: Verifying Checksum
03bece8a5f21: Download complete
73fd35f5cfa6: Download complete
filesystem layer verification failed for digest sha256:c189211552cdd321ae7bdf84cb5d708260161c01e43a0fb44dd068344bd7178e


➜  group.com.docker docker pull percona:8
8: Pulling from library/percona
524b0c1e57f8: Verifying Checksum
02e386a719ce: Download complete
e0b0b666a45f: Download complete
00b1a9d6f75e: Verifying Checksum
c189211552cd: Verifying Checksum
03bece8a5f21: Download complete
73fd35f5cfa6: Download complete
filesystem layer verification failed for digest sha256:c189211552cdd321ae7bdf84cb5d708260161c01e43a0fb44dd068344bd7178e


➜  group.com.docker docker pull centos:8
8: Pulling from library/centos
6910e5a164f7: Verifying Checksum
filesystem layer verification failed for digest sha256:6910e5a164f725142d77994b247ba20040477fbab49a721bdbe8d61cf855ac23


➜  group.com.docker docker pull centos:8
8: Pulling from library/centos
6910e5a164f7: Verifying Checksum
filesystem layer verification failed for digest sha256:6910e5a164f725142d77994b247ba20040477fbab49a721bdbe8d61cf855ac23


➜  group.com.docker docker pull centos:8
8: Pulling from library/centos
6910e5a164f7: Verifying Checksum
filesystem layer verification failed for digest sha256:6910e5a164f725142d77994b247ba20040477fbab49a721bdbe8d61cf855ac23


➜  group.com.docker docker pull centos:8
8: Pulling from library/centos
6910e5a164f7: Verifying Checksum
filesystem layer verification failed for digest sha256:6910e5a164f725142d77994b247ba20040477fbab49a721bdbe8d61cf855ac23

**Comment by lucaslg26** [comment]
hackintosh?

**Comment by redolphin** [comment]
> hackintosh?

It was.
