### ISSUE TITLE
Installation error in macbook pro

### ISSUE THREAD

**Issue by Nandulucky** [docker/for-mac#4686]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wyaeld** [comment]
Also having problem on latest edge update, but Diagnostics panel never completes

![image](https://user-images.githubusercontent.com/157392/84961020-5b48f300-b157-11ea-974d-b15fa88bc086.png)
