### ISSUE TITLE
Intermittent Slowness from Docker commands (Mac 1.12.1-beta24)

### ISSUE THREAD

**Issue by coeotic** [docker/for-mac#469]
### Steps to reproduce
Unfortunately, this is intermittent... or at least I've found no common trigger, so
1. in shell, type docker {operation} {options}

### Expected behavior

Before this latest update, the cli/daemon is always immediately responsive, and exit immediately.

### Actual behavior

After this latest update, the cli/daemon has been variably responsive. Operations such as ps, pull, build, and others have had a hard time completing. That is, operation 'ps' may, intermittently not respond, and instead appears to 'freeze,' before displaying results. If I ^c, I am able to get my shell back, so it's stuck in the execution runtime. This happened, variably, with 'pull,' where all of the layers download, but either the none but last layer, or none of the layers will unpack, and the executable has to be interrupted. 

After interrupting the docker exe, If I re-run the exact same command (3 of the 5 freezes, so far), the exact same behavior was shown, all the way down to the point of the freeze. Only after waiting for more than, maybe... 30 seconds,  would re-running the command be successful again.

For two of the 5 freezes I have experienced in the last 24 hours, I ran /usr/bin/top on my OS X host, and did not find unusually high activity or memory usage.

No other changes have been made to my OS X host, and the freezes do not seem to have any correlation to sleep/start... 

I'll update this issue as I detect any more valuable troubleshooting points.

### Information

```
Diagnostic ID: C5D129A0-A03F-431B-A528-A48BDC5C1362
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by samoht** [comment]
Detected symptom of problem 'segfault' in C5D129A0-A03F-431B-A528-A48BDC5C1362/20160830-112747.

You have hit an issue with the Linux kernel version what we ship in Docker for Mac. We have fixed that issue in more recent versions of the product, so please upgrade. Thank you for your report!

The following log matches:
```
Aug 30 07:05:45 us-choffman Docker[com.docker.driver.amd64-linux][79178] <Notice>: VM: 2016-08-30 14:05:45 +0000 UTC kern.info kernel: device veth6275d96 left promiscuous mode
Aug 30 07:05:45 us-choffman Docker[com.docker.driver.amd64-linux][79178] <Notice>: VM: 2016-08-30 14:05:45 +0000 UTC kern.info kernel: docker0: port 1(veth6275d96) entered disabled state
Aug 30 07:05:45 us-choffman Docker[com.docker.driver.amd64-linux][79178] <Notice>: VM: 2016-08-30 14:05:45 +0000 UTC kern.info kernel: auplink[2441]: segfault at 7ffe4fb0fae8 ip 000000000043d049 sp 00007ffe4fb0faf0 error 6 in auplink[400000+ca000]
Aug 30 07:05:45 us-choffman Docker[com.docker.driver.amd64-linux][79178] <Warning>: VM: 2016-08-30 14:05:45 +0000 UTC kern.warn kernel: aufs au_plink_put:434:dockerd[2045]: pseudo-link is not flushed
Aug 30 07:05:45 us-choffman Docker[com.docker.driver.amd64-linux][79178] <Notice>: VM: 2016-08-30 14:05:45 +0000 UTC kern.info kernel: auplink[2455]: segfault at 7fff6b287218 ip 000000000043d049 sp 00007fff6b287220 error 6 in auplink[400000+ca000]
```
