### ISSUE TITLE
Docker hangs on mounts

### ISSUE THREAD

**Issue by yoav-orca** [docker/for-mac#4693]
- [x] I have tried with the latest version of my channel (Stable or Edge) - **Both**
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
DD11DFD0-67E1-4AE6-AFC2-E7300DC88199/20200621064422
C44FFC8C-83D9-4D30-AD5C-B7A1B892C101/20200621120215
8EE24803-7DC7-4C94-98D2-071E07B0C55F/20200621183923
8EE24803-7DC7-4C94-98D2-071E07B0C55F/20200623051852

### Expected behavior
Docker will not hang

### Actual behavior
Docker hangs

### Information

We use a docker run command similar to this:
```
docker run --rm --init --net host --env X --env-file /Users/$USER/path/to/env/file --env-file /Users/$USER/path/to/env/file2 --env-file /Users/$USER/path/to/env/file --volume /Users/$USER:/Users/$USER --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp:/tmp --link redis:redis --link postgres:postgres -ti image_name /bin/bash
```

The problem is not easily reproducible but happens across my team about twice a day for each developer. When trying to debug the issue by myself it seems that `com.docker.osxfs` somehow gets out of sync, and running a container with and mounting /Users:/Users will cause the docker to unhang.
I'm not sure if the problem is new.

  - macOS Version:

### Diagnostic logs

```
Docker for Mac:
The issue reproduces on both latest stable & edge versions:
Edge - 2.3.1.0 (45408)
Stable - 2.3.0.3
```

### Steps to reproduce the behavior
```
docker run --rm --init --net host --env X --env-file /Users/$USER/path/to/env/file --env-file /Users/$USER/path/to/env/file2 --env-file /Users/$USER/path/to/env/file --volume /Users/$USER:/Users/$USER --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp:/tmp --link redis:redis --link postgres:postgres -ti image_name /bin/bash
```
Run the command enough times and it would just happen.

**Comment by jbasila** [comment]
This also happened to me as well, I use MacBook Pro - this could be related to the implementation of Docker on MacBook.

**Comment by yregaieg** [comment]
it seems to be simalar to my issue #4696 but I didn't associate it with volume mounts, it seemed more like networking related.

**Comment by RonVider** [comment]
I just had the same issue - 5F7B4991-0F48-4D10-A767-3A2CD652F020/20200622161021.

**Comment by wagdez** [comment]
I just had the same issue
C2BBD1DC-D3C5-4D3C-9DD1-BA7D43000E6E/20200622183716

**Comment by sphylo** [comment]
Same issue: E3AB0B6C-9CD6-4ABC-A67F-B0E7EB8D6F84/20200623131558

**Comment by yregaieg** [comment]
I have created a docker machine on my mac, and that seems to be working far better, I hope that helps unblock any of you guys..., it is a bit less straight forward than docker-for-mac but it does the job ;-)

**Comment by mitiak** [comment]
Same here
D33A15DB-7483-4422-9925-751A0B333068/20200624113231

**Comment by arieteter** [comment]
Adding another one: DC588EBA-20CB-4D00-911F-16D1C3CAC732/20200628190330
