### ISSUE TITLE
Big Sur: Fatal Error

### ISSUE THREAD

**Issue by ErikVeland** [docker/for-mac#4699]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Launching
### Actual behavior
Fatal Error: one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 2546)

### Information
Latest version on Edge channel. Resetting Docker to factory defaults nor Diagnose & Feedback helps.

  - macOS Version: 11.0b1

### Diagnostic logs

```
Docker for Mac: version...
n/a Nothing happens
```

### Steps to reproduce the behavior

  1. Install 11.0 developer beta
  2. Launch Docker

**Comment by chunlea** [comment]
Instead of using Edge version, please try Stable version. After I reinstall stable version, it works.
Also, I uninstall VirtualBox.

**Comment by klizas** [comment]
@ErikVeland did you notice any performance improvements with Big Sur?

**Comment by stephen-turner** [comment]
Thanks for the heads-up, but we haven't started work on Big Sur yet. Obviously it will work by the time of release.

**Comment by pyr0hu** [comment]
Installing stable instead of Edge solved this issue.

**Comment by ErikVeland** [comment]
@klizas Can’t speak for Docker (yes, stable solved this issue), but in general my original 5K iMac feels much the same. Safari however is another story. It’s noticeably faster and less cpu heavy. Presenting with the camera on Meet would previously guarantee my computer overheating within seconds, but chugs along just fine now. Pages that would lag now load instantly. Crushes Chrome in almost every benchmark I’ve thrown at it.

**Comment by stephen-turner** [comment]
Could someone kindly test the new Edge we've just released (2.3.2.0) and report back? We've made some hyperkit changes that might (or might not) have fixed this. Thank you.

**Comment by chunlea** [comment]
@stephen-turner I can confirm it works.
<img width="887" alt="Screen Shot 2020-06-25 at 10 11 50 AM" src="https://user-images.githubusercontent.com/1522415/85767332-c309bb80-b6cc-11ea-9a96-840d4dedc03a.png">

**Comment by stephen-turner** [comment]
Great, thanks for the quick response!

**Comment by markomitranic** [comment]
Can anyone confirm any performance improvements in terms of osxfs? Just jump in and do a heavy npm install or a yarn watch for example.

**Comment by phoenixleonardo** [comment]
The containers are unable to access the files in bind mounts. Is anyone else experiencing this?
Tried with both the stable version as well as the latest edge version mentioned by @stephen-turner.
