### ISSUE TITLE
Docker diagnostics showing some errors

### ISSUE THREAD

**Issue by ngehani** [docker/for-mac#470]
### Information

Diagnostic ID: 00200C5F-E831-4F93-8D09-57FC5BFAB9BA
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker 2.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/neilg/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/00200C5F-E831-4F93-8D09-57FC5BFAB9BA/20160830-121031/qemu-img-check.stdout 2> /tmp/00200C5F-E831-4F93-8D09-57FC5BFAB9BA/20160830-121031/qemu-img-check.stderr: exit 126")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
Hi @ngehani, thanks for the report.
I'm afraid we can't troubleshoot this further without some more information, so I'm closing for now.
If you are able to add some more information, for example:

I'm afraid we can't troubleshoot this further without some more information, so I'm closing for now.
If you are able to add some more information, for example:

- What you were doing when the error occurred
- What you expected to happen
- What actually happened

Then we can re-open and look at this again
