### ISSUE TITLE
Can't get docker to start

### ISSUE THREAD

**Issue by myw4pd** [docker/for-mac#471]
Hello -- I am trying to start Docker but it won't start.  This is the my first time installing/starting Docker.  I have deleted my VM, so I don't know what other solutions are there.

### Information

Diagnostic ID: 2B9CF279-9165-4E1D-86C8-3FBAF37BFEFE
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/mdubz/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/2B9CF279-9165-4E1D-86C8-3FBAF37BFEFE/20160830-182044/qemu-img-check.stdout 2> /tmp/2B9CF279-9165-4E1D-86C8-3FBAF37BFEFE/20160830-182044/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
@myw4pd when you say that you have deleted your VM, have you deleted the following file?
```
/Users/mdubz/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
Have you also tried a factory reset from the app? `🐳 -> Preferences -> Uninstall/Reset -> Factory Reset`

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in 2B9CF279-9165-4E1D-86C8-3FBAF37BFEFE/20160830-183622.

The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

May be related to docker/for-mac#61

The following log matches:
```
Aug 25 15:42:35 d-172-25-44-11 WindowServer[com.apple.coregraphics][266] <Warning>: common_reenable_update: UI updates were finally reenabled by application "Docker" after 8.18 seconds [0.12fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
Aug 25 15:42:40 d-172-25-44-11 Docker[com.docker.docker][18672] <Notice>: Bundle path: /Applications/Docker.app
Aug 25 15:44:10 d-172-25-44-11 Docker[com.docker.docker][18672] <Notice>: privileged installation of com.docker.vmnetd successful
Aug 25 15:44:10 d-172-25-44-11 Docker[com.docker.docker][18672] <Critical>: Communication with networking components failed.
Aug 25 15:44:16 d-172-25-44-11 Docker[com.docker.vmnetd][18691] <Notice>: com.docker.vmnetd starting
Aug 25 15:45:51 d-172-25-44-11 Docker[com.docker.docker][18694] <Warning>: Docker already running - exiting
Aug 25 15:45:52 d-172-25-44-11 Docker[com.docker.docker][18694] <Notice>: applicationWillTerminate
Aug 25 15:46:54 d-172-25-44-11 Docker[com.docker.docker][18672] <Notice>: applicationWillTerminate
Aug 25 15:47:58 d-172-25-44-11 Docker[com.docker.docker][18700] <Notice>: Application version: 1.12.0-a (11213)
```
