### ISSUE TITLE
Crash/failure on upgrading from edge 2.3.1.0 to 2.3.2.0

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#4712]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [n] I have uploaded Diagnostics (I tried, but it just spun for many, many minutes saying "Diagnosing"
  - Diagnostics ID:

### Expected behavior

Smooth upgrade

### Actual behavior

Crash with message "Docker daemon failed to start:

<img width="600" alt="Slack___ddev___Drupal" src="https://user-images.githubusercontent.com/112444/85882053-d3d53280-b79b-11ea-8abe-6c951666789a.png">

Attempting to diagnose failed, I waited a long time and gave up finally.

Clicked "Exit" in the diagnose, then restarted. It started OK.

### Information

  - macOS Version:

### Diagnostic logs

Unable to obtain.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks for the report, Randy. Although I'm not sure we're going to get very far without diagnostics and with the problem now having gone away.

**Comment by rfay** [comment]
I've seen a fair number of crashes of this type recently, including on stable. Thanks for the response.
