### ISSUE TITLE
`:z,delegated` prevents use of mutagen

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4718]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20200629230230

### Expected behavior
`:z,delegated` works just like `:delegated`

### Actual behavior
Mutagen mounts are only enabled with `:delegated` ( see [this](https://github.com/docker/for-mac/issues/4590#issuecomment-650221168) )

### Information
  - macOS Version: 10.15.5

### Diagnostic logs
This doesn't exist in the current Docker for Mac

### Steps to reproduce the behavior
  1. Create a mount with `:z,delegated`
  2. Observe that it's not a mutagen mount ( `docker inspect <name> | python -m json.tool | grep -A 3 HostConfig`)

**Comment by stephen-turner** [comment]
Thanks for the report, this will be fixed in the next version.

**Comment by stephen-turner** [comment]
This is now fixed in Edge 2.3.3.0.
