### ISSUE TITLE
Docker Deleting Containers after restart

### ISSUE THREAD

**Issue by jbrown3925** [docker/for-mac#4719]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:6AE95BD7-F41C-4D92-A989-FEC173AD2DEA/20200630064813

### Expected behavior
Shutdown docker, Restart Host Machine, Startup docker and containers
### Actual behavior
Shutdown docker, Restart Host Machine, All Docker Containers are missing from system.
### Information

  - macOS Version:10.10.15

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ulrich** [comment]
@jbrown3925 Did you change the location of the VM?
