### ISSUE TITLE
Preferences hangs after enabling kubernetes and kubernetes never finishes starting

### ISSUE THREAD

**Issue by bhabermaas** [docker/for-mac#4722]
Preferences hangs and cannot be used. 
This happened after enabling kubernetes.  Kubernetes starting and never gets to running. 
Going back to Preferences to disable kubernetes has the failure. 

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:2861B18B-3FF8-420A-9547-BF8D9F98108A/20200630155227

### Expected behavior
Preferences dialog finishes loading. 

### Actual behavior
Preferences dialog appears with spinning graphic. Never stops. 

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? I can't get rid of the problem to reproduce it 
  - Is the problem new? First time I tried to use kubernetes
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles FTW.

  - macOS Version: macOS High Sierra 10.13.6
 - Docker version
![Screen Shot 2020-06-30 at 12 02 04 PM](https://user-images.githubusercontent.com/8658889/86149220-aead3080-bac9-11ea-9685-989604800d16.png)

### Diagnostic logs

```
[20200630155227.zip](https://github.com/docker/for-mac/files/4853060/20200630155227.zip)

Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Go to Preferences and enable kubernetes

  2.Kubernetes never finishes starting
  3. Go to Preferences, never finishes loading.

**Comment by mattdajacob** [comment]
I'm experiencing the same issues. I'm running on Mac 10.15.5 and Docker Desktop 2.3.0.3.

**Comment by Yaki666** [comment]
I am having the same issues. Mac 10.15.6 and Docker Desktop 2.3.0.4, and Kubernetes V1.16.5
