### ISSUE TITLE
Docker for Mac Doesn't Finish its Start Up

### ISSUE THREAD

**Issue by bschalme** [docker/for-mac#473]
### Steps to reproduce

1. Log in to my MacBook Pro
2. Watch the whale in the Mac OS menu bar, and notice the container animation never ceases
3. Open a terminal window and do a docker ps
4. See the docker ps timeout

### Expected behavior

1. The container animation ceases a few seconds after logging in
2. A docker ps is successful

### Actual behavior

1. The container animation never ceases
2. A docker ps times out.

### Information

```
Diagnostic ID: F4D8293D-9414-459E-8F7A-3964E1A596BA
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dave-tucker** [comment]
@bschalme thanks for the report.
Was Docker for Mac working before this issue occurred?
Has this always happened? Or did something (maybe an upgrade of Docker from Beta 23 to Beta 24) cause this?

**Comment by bschalme** [comment]
Hey @dave-tucker,
Docker for Mac was working fine before. As recently as Beta 22 this problem did not exist. It was a couple Betas ago when this problem first manifested itself.

HTH.

**Comment by mchiang0610** [comment]
Similar issue as #119. Merging.

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in F4D8293D-9414-459E-8F7A-3964E1A596BA/20160830-195249.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-08-24T10:30:39.092677378Z" level=debug msg="Failed to load layer sha256:fdc3af277bb2db90c84bc349d534fce26d1ea5ba1316a2e9652b3e62e3a8456c: failed to get diff id for sha256:fdc3af277bb2db90c84bc349d534fce26d1ea5ba1316a2e9652b3e62e3a8456c: invalid checksum digest format"
time="2016-08-24T10:30:39.093017299Z" level=debug msg="Failed to load layer sha256:fec4f65f5e133bb5b7e65262769fdc650926618acd1f010314ca91982ca0cf97: failed to get diff id for sha256:fec4f65f5e133bb5b7e65262769fdc650926618acd1f010314ca91982ca0cf97: invalid checksum digest format"
time="2016-08-24T10:30:39.093378741Z" level=debug msg="Failed to load mount 0646c9f42a9ab56bfdc049047741af6e662a34f7be180c2f77e4d9ad8fa39317: invalid mount id value"
time="2016-08-24T10:30:39.093739986Z" level=debug msg="Failed to load mount 1363383a3bf72405bf5f30e3c5cac23283322a916156ca7f564f4548e7b1a20b: invalid mount id value"
time="2016-08-24T10:30:39.094047312Z" level=debug msg="Failed to load mount 426a98054a260c9de8d6c1d331f974378d76acbc74ca6b408d6134b5af91cafb: invalid mount id value"
time="2016-08-24T10:30:39.094378151Z" level=debug msg="Failed to load mount 4554422c21ea7d448a9f6d7eb0f740126e407e65c04ff51aeb66c97a9baf0138: invalid mount id value"
```
