### ISSUE TITLE
Flakey filesystem event propagation

### ISSUE THREAD

**Issue by azoff** [docker/for-mac#4731]
related issue: https://github.com/docker/for-mac/issues/2375#issuecomment-653179768

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C983C12D-0F78-4FE9-86CF-C362E9C64E0D/20200702193108

### Expected behavior

When a file changes on a mounted volume, the corresponding filesystem event propagates to the container.

### Actual behavior

The file change propagates to the container, but the event related to that change does not.

#### Reproducability

Low, Flakey - Almost always guaranteed to happen on our large private codebase (>50K files), after a day or so of development. 

#### Novelty

I've been experiencing this issue since I started tracking it, in 02/2020. Unclear if it appeared with an update

#### Additional Information

In my case, I have a bind mount with `rw,delegated` flags. Changing the flags did not seem to affect the issue. Once the issue is occurring, it will not self-correct until the Docker app or host machine restarts.

- `.../com.docker.osxfs  state` showed me that the volume is being tracked by osxfs
- fsevents API appears to work on the host MacOS installation (i.e. tested via fswatch)
- inotify API appears to work on the containerized Ubuntu installation (i.e. tested via inotifytools)
- osxfs does not appear to bridge the fsevent over to inotify upon file change (i.e. tested using touch on MacOS)

To workaround this, I wrote a script that binds to fsevents on the host machine, and delegates changes manually using `docker exec [container_id] touch [file_path]` in the target container. Not my favorite solution, but it beats having to restart docker or the host machine itself.

As I understand it, this is still considered the only known workaround to the issue in question here.

### Versions
- macOS: 10.15.5
- Docker for Mac: 2.3.0.3
- Engine: 19.03.8
- Compose: 1.25.5

**Comment by theblang** [comment]
My coworkers and I can confirm that we are seeing this as well. After noticing some oddness with a file, we did a deep dive using the instructions that @azoff mentioned. 

- First, using `vi` in the container's shell we could see that the file was reflecting changes I had made about forty-five minutes or so prior, but not the most recent changes. 

- Then we checked `com.docker.osxfs state` to see that the directory containing the file was mounted for the container. 

- Then we ran `inotifywait -r -m --format "%e %f" app` in the container to set up watches on an `app` folder, but did not see notifications for any file changes made on the host in that folder (we tried a number of operations). 

- Then on the host we watched the same folder with `fswatch -r app`, and saw file changes properly observed. 

- Lastly, we quit and reopened Docker Desktop, spooled up the container again, ran `inotifywait -r -m --format "%e %f" app` again, and this time we saw notifications for file changes made on the host.

**Comment by azoff** [comment]
FWIW, it's becoming increasingly clear to me that this is a known deficiency with Docker for Mac. The bug was randomly called out in an event propagation lib: https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux

**Comment by booleanbetrayal** [comment]
It's also made it into [docker-sync's official troubleshooting doc page](https://docker-sync.readthedocs.io/en/latest/troubleshooting/sync-stopping.html):
> Sometimes, the OSXFS itself gets stuck. Docker for Mac restart maybe the only option. Sometimes, an OS restart is the only option.

**Comment by stephen-turner** [comment]
Thanks for the comments. Give us a few days and we will have a build that doesn't use osxfs.
