### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by koutsenko** [docker/for-mac#4732]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B2C1ABE8-1E17-4C19-90E6-AE2785C058DE/20200703075246

### Expected behavior
Docker for Mac OS installed and run successfully

### Actual behavior
I downloaded official Docker.dmg, attached it via hdiutil and copied Docker.app folder to /Applications.
Brew in installed also, memory is enough, kern.hv_support = 1.
But at first Docker run (via Launchpad) I got Docker.VmnetdError error 1.

### Information
  - macOS Version: Catalina, fresh install

UPD: `brew cask install docker` and then `open /Applications/Docker.app` produces same error

**Comment by rd-picme** [comment]
Hey, is there any solution to that issue? I have the same problem.
