### ISSUE TITLE
[Kubernetes  failed to start] cannot list Stacks from compose.docker.com/v1beta1 api server: timed out waiting for the condition

### ISSUE THREAD

**Issue by mogi86** [docker/for-mac#4736]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

* Kubernetes is running after start/restart.

### Actual behavior

* Kubernetes failed to start when I tried to restart.
<img width="246" alt="スクリーンショット 2020-07-05 18 21 15" src="https://user-images.githubusercontent.com/16068132/86529537-51abe300-beec-11ea-9718-23327036ddd0.png">

* I checked the log based on this [troubleshoot](https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs)

```bash
2020-07-05 18:01:08.161970+0900  localhost com.docker.driver.amd64-linux[1677]: error while starting: cannot list Stacks from compose.docker.com/v1beta1 api server: timed out waiting for the condition
2020-07-05 18:01:08.162676+0900  localhost Docker[552]: [Docker:] HTTPHandler: Received request: POST /kubernetes
2020-07-05 18:01:08.162923+0900  localhost Docker[552]: (CoreFoundation) [com.apple.CFBundle:strings] Bundle: <private>, key: Kubernetes failed to start, value: , table: Localizable, localizationName: (null), result: Kubernetes failed to start
```
 
### Information

  - macOS Version: 10.15.5
  - Docker: 2.3.0.3 
  - Kubernetes: v1.16.5
  - I'm using `wifi`

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Restart Kubernetes from Desktop docker menu as the above.

**Comment by hunzaboy** [comment]
+1

**Comment by DP19** [comment]
I saw this issue as well, however kubernetes was reachable. Looking into it a little more i saw some pods in the docker namespace were pending and couldn't be put on nodes due to some taints that they had. Being its a single node cluster I took a look and saw that there was a taint for "Disk pressure" meaning the disk image for docker for desktop was almost full. I increased the size of the disk and once it was applied and restarted it came up without issue.

Could be the same issue you're seeing

**Comment by mogi86** [comment]
@DP19 
Hi. 
Thank you for your information!

My disk image was also almost full.
I removed some unnecessary docker images.
Then, kubernetes could work 👍 

* Before remove docker image
<img width="450" alt="スクリーンショット 2020-07-16 9 22 24" src="https://user-images.githubusercontent.com/16068132/87613198-984cd900-c747-11ea-8f9a-1472137472f5.png">

* After remove docker image
<img width="450" alt="スクリーンショット 2020-07-16 9 34 30" src="https://user-images.githubusercontent.com/16068132/87613192-8f5c0780-c747-11ea-9dd1-82427824f5d7.png">
