### ISSUE TITLE
[Mutagen] Love the improvements on disk performance

### ISSUE THREAD

**Issue by nicastelo** [docker/for-mac#4737]
Hi! I use docker for my dev environment and I have been experiencing a way better performance lately. Didn't know why exactly until today, I'm really impressed with how fast is now so went to check the changelog and saw the change to the caching mechanism.

Just wanted to say thank you.

Currently running Docker for Desktop 2.3.2.0 (46268) edge.

**Comment by stephen-turner** [comment]
Great, thanks for the feedback, @nicastelo.
