### ISSUE TITLE
Daemon connection error on terminal launch

### ISSUE THREAD

**Issue by AdamBD** [docker/for-mac#4738]
This isnt an error, but I am trying to understand the functionality here. After installing docker-for-mac, each time I open a new terminal session and Docker-for-mac is not running I get the following error:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I cannot find where the (Daemon?) command has been added to any RC file to start when I open a terminal session. 

Does anyone know where this is coming from?

**Comment by conradwt** [comment]
@AdamBD I'm seeing the same issue on `macOS Big Sur` whenever I enter a directory that contains a `Dockerfile` and `Docker for Mac` isn't running.
