### ISSUE TITLE
Why would network usage impact docker containers running on a local MacOS machine?

### ISSUE THREAD

**Issue by ismith78** [docker/for-mac#4741]
I am seeing my local docker containers freeze and become slow to respond on my MacOS machine when my wife accesses her work system via RDS on her Windows machine. I have no idea why this is the case but it is 100% reproducible.

I am running MacOS 10.14.6 and running docker desktop 2.1.0.5 (40693) which was a downgrade from version 2.3. The reason for the downgrade was due to the issues with CPU usage, which at least allowed for docker to be more stable for my machine for most of the time.

So 2.1.0.5 works fine when I am at work, and when I'm at home when my wife is not using RDS. However, about 5 minutes from her using RDS docker on the mac is very slow to respond and consumes significant CPU across all the cores.

I am at a loss to understand this or even where to start to debug this problem. I also fail to understand why this could happen, as running local containers with postgres and a web server shouldn't have a dependency on the outside world.

**Comment by stephen-turner** [comment]
I agree with you, this is very strange and I can't imagine what can be causing it. Sorry, not very helpful.
