### ISSUE TITLE
Exit failure on macOS 10.12 (Build 16A313a)

### ISSUE THREAD

**Issue by mbrumbelow** [docker/for-mac#475]
### Information

Diagnostic ID: 50A463F1-EB6B-4884-B993-AE0F45FA1383
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/mojo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/50A463F1-EB6B-4884-B993-AE0F45FA1383/20160831-003248/qemu-img-check.stdout 2> /tmp/50A463F1-EB6B-4884-B993-AE0F45FA1383/20160831-003248/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
I'm afraid we can't troubleshoot this further without some more information, so I'm closing for now.
If you are able to add some more information, for example:
- What you were doing when the error occurred
- What you expected to happen
- What actually happened
Then we can re-open and look at this again

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
