### ISSUE TITLE
DNS does not resolve within a container over a VPN

### ISSUE THREAD

**Issue by stantonk** [docker/for-mac#4751]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 12EF87D0-351C-47DB-830F-15847A4A7D84/20200708044917

### Expected behavior
DNS resolution should work within a container for hosts on a private network.

### Actual behavior
DNS resolution does not work within a container for hosts on a private network.

### Information
  - Is it reproducible? yes
  - Is the problem new? yes
  - Did the problem appear with an update? not sure
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: 10.14.6 (18G5033)

### Diagnostic logs
Docker for Mac: 2.3.0.3 (45519)

### Steps to reproduce the behavior

0. connect to VPN

1. start a container and install `ping`

```
$  docker run -it ubuntu:18.04 /bin/bash
root@a899653c3a3b:/# apt-get update && apt-get install iputils-ping -y

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [9282 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [869 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [89.0 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1003 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [13.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1302 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1406 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [102 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [8158 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [8286 B]
Fetched 18.2 MB in 6s (3299 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcap2 libcap2-bin libidn11 libpam-cap
The following NEW packages will be installed:
  iputils-ping libcap2 libcap2-bin libidn11 libpam-cap
0 upgraded, 5 newly installed, 0 to remove and 3 not upgraded.
Need to get 142 kB of archives.
After this operation, 537 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libcap2 amd64 1:2.25-1.2 [13.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libidn11 amd64 1.33-2.1ubuntu1.2 [46.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 iputils-ping amd64 3:20161105-1ubuntu3 [54.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libcap2-bin amd64 1:2.25-1.2 [20.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpam-cap amd64 1:2.25-1.2 [7268 B]
Fetched 142 kB in 1s (258 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcap2:amd64.
(Reading database ... 4046 files and directories currently installed.)
Preparing to unpack .../libcap2_1%3a2.25-1.2_amd64.deb ...
Unpacking libcap2:amd64 (1:2.25-1.2) ...
Selecting previously unselected package libidn11:amd64.
Preparing to unpack .../libidn11_1.33-2.1ubuntu1.2_amd64.deb ...
Unpacking libidn11:amd64 (1.33-2.1ubuntu1.2) ...
Selecting previously unselected package iputils-ping.
Preparing to unpack .../iputils-ping_3%3a20161105-1ubuntu3_amd64.deb ...
Unpacking iputils-ping (3:20161105-1ubuntu3) ...
Selecting previously unselected package libcap2-bin.
Preparing to unpack .../libcap2-bin_1%3a2.25-1.2_amd64.deb ...
Unpacking libcap2-bin (1:2.25-1.2) ...
Selecting previously unselected package libpam-cap:amd64.
Preparing to unpack .../libpam-cap_1%3a2.25-1.2_amd64.deb ...
Unpacking libpam-cap:amd64 (1:2.25-1.2) ...
Setting up libcap2:amd64 (1:2.25-1.2) ...
Setting up libidn11:amd64 (1.33-2.1ubuntu1.2) ...
Setting up iputils-ping (3:20161105-1ubuntu3) ...
Setting up libpam-cap:amd64 (1:2.25-1.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libcap2-bin (1:2.25-1.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
```
2. ping www.google.com and see that that works:

```
$ ping www.google.com
PING www.google.com (142.250.31.147) 56(84) bytes of data.
64 bytes from 142.250.31.147 (142.250.31.147): icmp_seq=1 ttl=37 time=30.7 ms
64 bytes from 142.250.31.147 (142.250.31.147): icmp_seq=2 ttl=37 time=29.0 ms
64 bytes from 142.250.31.147 (142.250.31.147): icmp_seq=3 ttl=37 time=35.9 ms
64 bytes from 142.250.31.147 (142.250.31.147): icmp_seq=4 ttl=37 time=45.7 ms
^C
--- www.google.com ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4011ms
rtt min/avg/max/mdev = 29.034/35.355/45.718/6.506 ms
```

3. ping a host on the internal network:

```
root@a899653c3a3b:/# ping some-host
ping: some-host: Name or service not known
```

4. verify that i can ping the host on the internal network from the host machine (my mac laptop):

```
$  ping some-host
PING some-host.int.someinternalnetwork.com (172.25.101.53): 56 data bytes
 64 bytes from 172.25.101.53: icmp_seq=0 ttl=63 time=38.385 ms
64 bytes from 172.25.101.53: icmp_seq=1 ttl=63 time=32.596 ms
64 bytes from 172.25.101.53: icmp_seq=2 ttl=63 time=39.377 ms
64 bytes from 172.25.101.53: icmp_seq=3 ttl=63 time=32.803 ms
^C
--- some-host.int.someinternalnetwork.com  ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 32.596/35.790/39.377/3.111 mm
```

Up until recently this worked fine on every previous docker for mac I've used.

**Stuff I've tried**

* I've tried changing the "bip" setting per https://github.com/docker/for-mac/issues/2820#issuecomment-434542354
* I've tried resetting to factory settings
* I've tried rebooting
* I've tried reconnecting to the VPN

None of the above fixed it.

What _did_ work is me manually editing the /etc/resolv.conf in the container to what i have on my host mac machine and then ping worked...but I never had to do this in the past with docker for mac and is a non-starter of a workflow... 

Hope this is enough to go on, thanks!

**Comment by zhenchangxc** [comment]
Same issue also happens to Ubuntu 20.04.

**Comment by michaelyaakoby** [comment]
Hi, I think that docker is "caching" the host's `/etc/resolv.conf` as it was when docker started up. 
Since my VPN adds several `server` entries to my `/etc/resolv.conf`, I assumed this caching needs to be invalidated.
So I tried restarting docker after I connected the VPN and now containers are able to resolve hosts that are in m company's DNS.

**Comment by micah-yeager** [comment]
Issue still exists on the 3.1.0 release for Docker for Mac ([which fixed other DNS resolution issues in Alpine containers](https://github.com/docker/for-mac/issues/5020)) on macOS 11.2. Restarting Docker for Mac while on the VPN does not fix the issue for me — the only workaround I have is manually setting the DNS servers in the Docker Engine config.  

Config below for anyone else who needs a quick fix (populated with example IPs, obviously use your own and leave out ellipses):
```
{
  ...,
  "dns": [
    "192.168.0.2",
    "192.168.0.3",
    ...
  ],
  ...
}
```

**Comment by krzysiekszymanski** [comment]
have the same problem above version docker 3.1.0 did not solve the problems. Workoround helped. Thanks @micah-yeager !!!

**Comment by knlambert** [comment]
Same for me. Than @micah-yeager for the workaround. It can finally use alpine 3.13 (I don't have this issue with the 3.12 though, don't know if it's related).

**Comment by JanMalte** [comment]
Accessing VPN Ressources from within a container was working for me applying the workaround with `pfctl` from here: https://github.com/docker/for-mac/issues/5322

**Comment by creadev-io** [comment]
I had the same issue using Cisco Anyconnect, and I seem to be able to work around it by. 

1. Launching/restarting Docker
2. Bring up my containers (I'm using docker-compose)
3. exec bash into one of my containers and run `apt-get update` just to make sure it resolves off of VPN. Once it resolves, exit shell and proceed. Otherwise, bring down containers and make sure to remove/prune docker network, then bring up containers again and retry `apt-get update`.
4. Connect to Wi-Fi
5. Launch Anyconnect and connect to VPN
6. exec bash and `apt-get update,` because I know this time it wont resolve, and let it run while proceeding to the next step
7. Once connected, switch off Wi-Fi to get back to my Ethernet connection, and now it resolves

Def not the ideal solution - but it worked. I used `apt-get` to test resolution, you can try hitting any url outside the local network, or within the VPN using curl, or other tools - as long as it resolves before getting on VPN.

The `pfctl` workaround didn't work for me - the rules were already created by my version of Anyconnect. 

Wonder if this will work for anyone else.

m1 Mac Mini exit
Cisco Anyconnect 4.9.06037
Docker Preview 3.1.0 (60984)
