### ISSUE TITLE
Docker Desktop 2.3.2.0 shouldn't implicitly use mutagen on delegated volumes

### ISSUE THREAD

**Issue by andytson-inviqa** [docker/for-mac#4756]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: n/a

### Expected behavior

docker run -v should allow use of osxfs volumes for delegated volumes

mutagen volumes should be specified another way to allow for choice in usage

### Actual behavior

docker run -v on delegated volumes automatically uses mutagen

### Information
  - macOS Version: 10.14.6

### Diagnostic logs
n/a

### Steps to reproduce the behavior
```
docker run -it -v $(pwd):/app:delegated node
```

**Comment by andytson-inviqa** [comment]
perhaps one or more of:
* a volume that doesn't already have a parent folder shared in file sharing configuration
* a configuration option to be able to turn off auto creation

it's also worth considering some users may access docker within the VM itself (e.g trying to recreate WSL-style capabilities), where host volumes would refer to VM directories

**Comment by stephen-turner** [comment]
@andytson-inviqa :cached does exactly what you want. Prior to the Mutagen integration, :cached and :delegated were identical but now :cached continues to use osxfs and :delegated uses Mutagen. See https://github.com/docker/for-mac/issues/1592#issuecomment-651309816 (and indeed the rest of that ticket) for more details.
