### ISSUE TITLE
Docker 2.3.2.0 file sharing stops nodemon restart on file change 

### ISSUE THREAD

**Issue by mikicho** [docker/for-mac#4757]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `4B3A96EF-5477-460C-A28C-C139363A44F9/20200709120251`

### Expected behavior
Nodemon should restart the Node process on file change

### Actual behavior
Nothing happens.

### Information
  - Is it reproducible?
  - Is the problem new? yes
  - Did the problem appear with an update? yes
  - macOS Version: 10.15.2 (19C57)

### Diagnostic logs

```
Couldn't find this, I uploaded the diagnostics
```

### Steps to reproduce the behavior
1. Create a minimal nodemon project:
    https://gist.github.com/ksmithut/e126f7ddb40b760487a17e8b569a77b5
2. Toggle the sync file:
![image](https://user-images.githubusercontent.com/11459632/87040747-d737d780-c1f9-11ea-9b1a-ddd10551509b.png)
3. Update the `index.js` file

**Comment by gaastonsr** [comment]
Restarting Docker fixed it for me...
