### ISSUE TITLE
/var/run/docker.sock does not exist

### ISSUE THREAD

**Issue by DavidELeahy** [docker/for-mac#476]
### Information

Diagnostic ID: 534046C9-292D-4AD5-B5E0-EBB686F52CB4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Permission denied (EACCES) connecting to /var/run/docker.sock: check permissions
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. install docker
2. run docker

**Comment by friism** [comment]
@DavidELeahy can you check whether this is caused by a missing symlink as mentioned here? https://github.com/docker/for-mac/issues/47

**Comment by DavidELeahy** [comment]
Yes thanks. Fixed by adding symlink. I had same problem following install  of Xcode server

**Comment by Stargator** [comment]
@deleahy Can you provide details, cause I am having the same issue.
