### ISSUE TITLE
docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused.

### ISSUE THREAD

**Issue by karisair** [docker/for-mac#4768]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E0DA09CA-3E55-442A-B5B6-05EB31734EB8/20200711104212

### Expected behavior
Docker container started to run qemu (from an image)

### Actual behavior
Docker error message: docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? No
  - macOS Version: macOS Catalina 10.15.5

### Diagnostic logs
Docker for Mac: Docker Desktop 2.3.0.3 (45519) stable

### Steps to reproduce the behavior
  1. `docker run -it --rm -v /Users/username/rust-raspberrypi-OS-tutorials/01_wait_forever:/work/tutorial -w /work/tutorial rustembedded/osdev-utils`

**Comment by bockc** [comment]
Same problem here. Docker never ends starting up. Running `docker ps` gets me this error.

**Comment by TesterCC** [comment]
Same problem here, after overwrite installation with dmg file. Running `docker ps`, report same error. 

1. Docker for Mac: 
Docker Desktop 2.3.0.3 (45519) stable

2. Operation System: 
macOS Mojave 10.14.6

3. Diagnostics ID:
2F1E5300-F628-47FE-9CBB-5DEBAEF5F19D/20200720111416

4.Steps to reproduce the behavior
Running `docker ps` in terminal

**Comment by djs55** [comment]
@karisair thanks for your report. Unfortunately it doesn't reproduce for me:
```
$ mkdir rust-embedded
$ cd rust-embedded/
$ git clone https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials
Cloning into 'rust-raspberrypi-OS-tutorials'...
remote: Enumerating objects: 300, done.
remote: Counting objects: 100% (300/300), done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 7479 (delta 200), reused 169 (delta 99), pack-reused 7179
Receiving objects: 100% (7479/7479), 18.20 MiB | 10.68 MiB/s, done.
Resolving deltas: 100% (5133/5133), done.

$ docker run -it --rm -v /Users/username/rust-embedded/rust-raspberrypi-OS-tutorials/01_wait_forever:/work/tutorial -w /work/tutorial rustembedded/osdev-utils
Unable to find image 'rustembedded/osdev-utils:latest' locally
latest: Pulling from rustembedded/osdev-utils
cbdc015de259: Pull complete 
35f8707632bb: Pull complete 
6b786d087f83: Pull complete 
31fb3cd05fdd: Pull complete 
a14e9d5c57e5: Pull complete 
30c4e0e71435: Pull complete 
e7cf2e01bbef: Pull complete 
6c728b321c56: Pull complete 
d7f64364d25f: Pull complete 
8575f902cdc7: Pull complete 
Digest: sha256:3125b5fc3eb0399ed36a3157e25eac48d715b72e9ecc82bce13caeb0e4ea4dc0
Status: Downloaded newer image for rustembedded/osdev-utils:latest
root@8dbaa4ba3fca:/work/tutorial# 
```
I notice from your diagnostics that the log query timed out:
```
[/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches ".*[Dd]ocker.*" || (process in {"kernel", "launchservicesd", "taskgated-helper"} && eventMessage contains[c] "docker")'] (timeout: 2m0s) -> context deadline exceeded
```
Does it reproduce reliably for you? Do any other commands work?

**Comment by djs55** [comment]
@TesterCC thanks for the diagnostics upload. It looks like you have run out of disk space in the VM used by Docker:
```
log/vm/onboot.010-bridge.log:2020-07-20T09:01:35Z onboot.010-bridge cat: write error: No space left on device
```
I think your best bet is to use the whale menu -> Troubleshoot -> Reset to factory defaults. Unfortunately containers and images will need to be rebuilt :(

**Comment by TesterCC** [comment]
> No space left on device

Thanks, it's solve my problem.

**Comment by javadba** [comment]
I have the same problem and have plenty of disk space.  Version 19.03.12

**Comment by magicmarvman** [comment]
> I have the same problem and have plenty of disk space. Version 19.03.12

Me too.

**Comment by javadba** [comment]
Re-instalilng the latest version of Docker fixed for me.

**Comment by tickcode** [comment]
I had the same problem on my mac.  I simply installed the same latest Docker.dmg and replaced the one I had just installed and it worked fine after that.  Who says doing the same thing more than once and expecting different outcomes was insane?

**Comment by HackPoint** [comment]
> oing the same thing more than once and expecting different outcomes was insane?

Simply restart the Docker App and no reinstall needed.

**Comment by daktari01** [comment]
Upgrading my docker `brew upgrade docker` solved the issue for me. Running BigSur

**Comment by alexnelson-es** [comment]
docker login, docker logout, factory reset, re-install, factory reset.   Eventually the problem went away.

**Comment by mmccarthy15** [comment]
FWIW, this happened to me on a brand new Docker install on MacOS 15.15.7.  Restarting Docker resolved the issue.

**Comment by bharathkumardaripally** [comment]
It says its starting but never happening...I tried removing and reinstalling but still no luck

**Comment by eldzapo** [comment]
> It says its starting but never happening...I tried removing and reinstalling but still no luck

Same here. I am running macbook m1,  big sur... Docker app gets stuck in running phase😳

**Comment by htdat** [comment]
The magic for my case is this comment https://github.com/docker/for-mac/issues/4768#issuecomment-660997575

> The whale menu -> Troubleshoot -> Reset to factory defaults. Unfortunately containers and images will need to be rebuilt :(

**Comment by xiazemin** [comment]
> * [x]  I have tried with the latest version of my channel (Stable or Edge)
> * [x]  I have uploaded Diagnostics
> * Diagnostics ID: E0DA09CA-3E55-442A-B5B6-05EB31734EB8/20200711104212
> 
> ### Expected behavior
> Docker container started to run qemu (from an image)
> 
> ### Actual behavior
> Docker error message: docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused.
> 
> ### Information
> * Is it reproducible? Yes
> * Is the problem new? Yes
> * Did the problem appear with an update? No
> * macOS Version: macOS Catalina 10.15.5
> 
> ### Diagnostic logs
> Docker for Mac: Docker Desktop 2.3.0.3 (45519) stable
> 
> ### Steps to reproduce the behavior
> 1. `docker run -it --rm -v /Users/username/rust-raspberrypi-OS-tutorials/01_wait_forever:/work/tutorial -w /work/tutorial rustembedded/osdev-utils`

sg="ignored error: Post \"http://vsock/events\": dial unix docker-api.sock: connect: connection refused"

**Comment by rbentivenha** [comment]
I was running the same issue on Macbook Pro **Apple Silicon/M1** and I figured out how to get by.
> Running Docker Apple Silicon Preview 7
Steps:
### 1. Run terminal
`> docker version`

> Client:
>  Cloud integration: 1.0.2
>  Version:           20.10.1
>  API version:       1.41
>  Go version:        devel +37a32a1833 Thu Dec 3 21:34:39 2020 +0000
>  Git commit:        831ebeae96
>  Built:             Wed Dec 16 02:33:22 2020
>  OS/Arch:           darwin/arm64
>  Context:           default
>  Experimental:      true
> Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory 

### 2. Click on the docker system tray icon > Preferences...
<img width="259" alt="Screen Shot 2021-01-22 at 15 38 10" src="https://user-images.githubusercontent.com/31641553/105531406-03afce80-5cc8-11eb-8e21-5821e16a1f53.png">

### 3. On top right corner of this window there is a bug icon ("Troubleshoot"), click on that
<img width="143" alt="Screen Shot 2021-01-22 at 15 38 23" src="https://user-images.githubusercontent.com/31641553/105531431-0dd1cd00-5cc8-11eb-871b-ed580e7c1a66.png">

### 4. Now you have a few options. I've clicked "Clean / Purge data"
<img width="805" alt="Screen Shot 2021-01-22 at 15 38 31" src="https://user-images.githubusercontent.com/31641553/105531449-14f8db00-5cc8-11eb-834b-b5b2fe48c8fe.png">

### 5. Restarted the docker and everything was working fine then

**Comment by Keegan-y** [comment]
I rebooted the system and it worked

**Comment by Wanger-SJTU** [comment]
None of the advices above worked for me.

**Comment by Wanger-SJTU** [comment]
finally solved refered to #5130

**Comment by jcagarcia** [comment]
Same error here. Reboot and reinstall options were not working for me.

After doing a `Clean / Purge Data` using the Docker Desktop app, it started fine again.

![image](https://user-images.githubusercontent.com/1403553/106450448-7f0e3e80-6485-11eb-8afa-c0ff55fbda9c.png)

**Comment by roelzkie15** [comment]
I'm wondering why what causes docker to be stuck in starting state during computer boot up? I'm using Docker preview 0.0.0(1) for apple M1. Engine: 20.10.0 and this is happening to me and following the cleaning/purging step resolves my issue.
