### ISSUE TITLE
Failed to login via GUI when password has special chars

### ISSUE THREAD

**Issue by Syzztem** [docker/for-mac#4780]
This is still going on
https://github.com/docker/for-mac/issues/2016

**Comment by stephen-turner** [comment]
@Syzztem Could you please describe the exact problem? There seem to be several unrelated items in the original ticket. Thanks.

**Comment by Syzztem** [comment]
I'm sorry I was using minikube and the problem came from minikube

Kind regards

Le lun. 20 juil. 2020 à 13:33, Stephen Turner <notifications@github.com> a
écrit :

**Comment by stephen-turner** [comment]
OK, thanks, I'll close this ticket then.
