### ISSUE TITLE
The path /var/lib/mutagen/desktop6e753... is not shared from OS X and is not known to Docker

### ISSUE THREAD

**Issue by wedi** [docker/for-mac#4785]
- [x] I have tried with the latest version of my channel (~Stable~ or **Edge**)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Too invasive, found passwords I cannot share.

### Expected behavior

When I start the [shopware development environment](https://github.com/shopware/development) which in turn runs six containers via `docker-compose`, I expect the containers to start up and mount directories without throwing an error. I have added the directory to Resources -> Filesharing and enabled caching.

I'd expect docker for mac to request permission to create and access `[/private]/var/lib/mutagen`.

### Actual behavior

```shell
~/code/shopware/development 6.2* $ ./psh.phar docker:start
[...]
	ERROR: for app_mysql  Cannot start service app_mysql: Mounts denied:
	The path /var/lib/mutagen/desktop6e753f13f522ed2e6f3143a849c39e0d/dev-ops/docker/_volumes/mysql
	is not shared from OS X and is not known to Docker.
	You can configure shared paths from Docker -> Preferences... -> File Sharing.
	See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
	.
	Encountered errors while bringing up the project.

Execution aborted, a subcommand failed!
```

### Information
  - macOS Version: 10.13.6

I googled and found a [stackoverflow question](https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known/45123074) and a [medium blog post](https://medium.com/effy-tech/fixing-the-var-folders-error-in-docker-for-mac-v2-2-3-2a40e776132d) which are about older versions but seem to be related to this problem.

### Diagnostic logs

_Full output of the diagnostics from "Diagnose & Feedback" in the menu ..._ Haven't found this menu... 🤔 

```
info.json
{
  "id": "1C34E692-9102-43FE-B705-44909C94ADD8",
  "date": "2020-07-20 17:16:18.065272 +0000 UTC",
  "os": "macOS 10.13.6",
  "os_label": "osx/10.13.x",
  "app_version": "2.3.3.0",
  "app_channel": "edge",
  "engine_version": "19.03.12",
  "compose_version": "1.26.2",
  "kubernetes_version": "v1.18.3",
  "credhelper_version": "0.6.3",
  "notary_version": "0.6.1",
  "vpnkit_version": "ea9dbeaf887f5dad8391f4a34d127501fb6bbf64",
  "hyperkit_version": "v0.20200224-35-g003426"
}

daemon.json
{
  "debug": true,
  "experimental": true,
  "features": {
    "buildkit": true
  }
}

mutagen/sync.json
{
  "/Users/dirk/code/shopware/development": {
    "status": "Ready",
    "ready": true
  }
}

mutagen/sync-list.json
{
  "/Users/dirk/code/shopware/development": {
    "name": "sync_y40TE5mcV4h1tTvMF9WQkhukpXoXbcFRN3dqFqe7I6w",
    "status": "Ready",
    "hostPath": "/Users/dirk/code/shopware/development",
    "vmPath": "//desktop@localhost:desktop6e753f13f522ed2e6f3143a849c39e0d",
    "ready": true,
    "received": 0,
    "total": 0,
    "internalState": "Watching for changes"
  }
}

com.docker.backend.log
time="2020-07-20T19:01:47+02:00" level=info msg="creating two-way sync for /Users/dirk/code/shopware/development"
time="2020-07-20T19:01:47+02:00" level=info msg="Creating session..."
time="2020-07-20T19:01:47+02:00" level=info msg="Created session sync_y40TE5mcV4h1tTvMF9WQkhukpXoXbcFRN3dqFqe7I6w"
time="2020-07-20T19:01:47+02:00" level=info msg="external: GET /synchronize/update 200 \"\" \"\""
```

### Steps to reproduce the behavior

Docker version and daemon.json above.

```shell
mkdir shopware/development
git clone git@github.com:shopware/development.git shopware/development
cd shopware/development
rm platform/.gitkeep
git clone https://github.com/shopware/platform.git
# Add shopware/development to Filesharing, enable sync, wait for 'ready' state
./psh.phar docker:start
```

[`docker-compose.yml`](https://github.com/shopware/development/blob/6.2/docker-compose.yml), docker-[`docker-compose.override.yml`](https://github.com/shopware/development/blob/6.2/dev-ops/docker/docker-compose.override.yml)

**Comment by wedi** [comment]
The recommendation from the medium post linked above actually helps.

I added `/private/var/lib/` through the GUI and `/var/lib/` manually to `~/Library/Group\ Containers/group.com.docker/settings.json` both show "Error" but the container in questions starts up without error.

**Comment by chuckadams** [comment]
@wedi's workaround did not work for me.  I continue to get this error no matter how I add these these directories to Docker.

**Comment by ian-axelrod** [comment]
Same here.

**Comment by ian-axelrod** [comment]
FYI you can get rid of this issue if you 1) remove custom synchronized folders from your docker for mac file sharing prefs and 2) do not use the `delegated` flag on any mounts. `delegated` triggers auto-add of folders to 2-way sync, and this can trigger the error.

**Comment by GrahamCampbell** [comment]
Same issue here, with version 2.3.4.0 for mac.

**Comment by wedi** [comment]
I guess this has been superseded by the removal of mutagen from Docker for Mac.
