### ISSUE TITLE
Docker Edge 2.3.3.2 dockerignore vs mutagen.yml issue

### ISSUE THREAD

**Issue by LiorRabin** [docker/for-mac#4794]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `4F05DD3B-F29A-4E5C-801A-28420FE59EE4/20200722073538`

I have a `.dockerignore` file which is used when building images in the CI process (for staging & production environments).
This file contains some folders which on the local dev environment I do need to be synchronized using the file-sharing process.
I would like to know if there's an option for Docker Edge to look at `mutagen.yml` instead of `.dockerignore` for the file synchronization as I cannot change my `.dockerignore` file at this time.

Thanks

**Comment by stephen-turner** [comment]
Thanks for the feedback, @LiorRabin. I think we're probably going to abandon the use of `.dockerignore` for Mutagen because of use cases like this. Thanks for being an Edge user and for giving us helpful feedback early!

cc @djs55

**Comment by LiorRabin** [comment]
Thanks for the reply @stephen-turner, can you please update on when the `.dockerignore` be abandoned?

**Comment by stephen-turner** [comment]
We will probably do another Edge release at the beginning of next week, but I'm not sure if it will be removed by then or whether it will be in the one after. Sorry, not a very definite answer.

**Comment by LiorRabin** [comment]
Thank you! Looking forward to it.
