### ISSUE TITLE
Improve version checking logic - now suggesting earlier version as an "upgrade"

### ISSUE THREAD

**Issue by rpsu** [docker/for-mac#4798]
Downloading and launching an edge release (#1592) immediately suggested to "upgrade" to latest release, which was actually earlier release. 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Do not suggest to "upgrade" to a previous version, even if that one is the latest official version.

### Actual behavior
![Screenshot 2020-07-23 at 10 40 14](https://user-images.githubusercontent.com/1099454/88262699-5c7abc00-ccd1-11ea-8856-fe12e7afe882.png)

### Information
  - macOS Version: 10.15.5

### Steps to reproduce the behavior

  1. Download a recent development build from https://gist.github.com/djs55/0e8957e1e36431a43cbfd3caaffa9165
  2. Launch the application
  3. see the dialog suggesting to get a earlier release as an upgrade

**Comment by stephen-turner** [comment]
Sorry: although you're right, this is a "Won't Fix". We're not going to put time into improving the case of using unreleased development snapshots.
