### ISSUE TITLE
Stop/Start Buttons

### ISSUE THREAD

**Issue by Rylon** [docker/for-mac#48]
### Feature Request

Hi, I had a feature request I wondered if you would consider adding to Docker for Mac?

On the menubar icon, you have a 'restart' button displayed next to the status - I wondered if you could add 'start' and 'stop' buttons also? The reason being that sometimes I would like to stop the Docker virtual machine, but keep the menubar icon running so I can easily start the VM again.

It might also be useful to have the initial state configurable, so you decide whether the VM should be started straight away or not.

**Comment by djs55** [comment]
@gdevillele What do you think?

**Comment by mchiang0610** [comment]
@Rylon Thanks for your suggestions. I really appreciate it. 

From Apple's developer guidelines, the application should work when started, and stop when quit. Apple itself says it's bad practice to have restart buttons within applications. 

We will try to follow Apple's developer guidelines to give users a great experience on the Mac. 

Thanks!

**Comment by Rylon** [comment]
Hi @mchiang0610, thanks for your reply!

I understand what you're saying here, but I was thinking something along the lines of Apple's Time Machine. In this case, you can have Time Machine displayed in the menubar all the time, even if the actual backups are switched off. When they are off, the icon in the menubar is greyed out, when they are switched on, it is not.

I'm thinking this could be the same for Docker for Mac - the app itself stays visible in the menubar, but you have a toggle for the actual Docker virtual machine, and grey out the menubar icon accordingly.

What do you think?
