### ISSUE TITLE
Issue starting Kitematic

### ISSUE THREAD

**Issue by BrianDillon** [docker/for-mac#480]
### Information

Diagnostic ID: FC40E590-C372-459D-8F1A-0F61C82B2BED
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
Closing as this is missing a lot of information and we can't help troubleshoot without some more details. If you are able to provide:

- What you were trying to do
- What you expected to happen
- What actually happened

Along with other relevant information, for example, how you installed Kitematic, or possibly some screenshots of the issue.

From the output of Diagnose it's possible that `docker ps` would fail too, so perhaps this is the root of the issue?
