### ISSUE TITLE
"/dev/mapper/control - no such device" in using Docker Desktop 2.3.0.2 - Part II

### ISSUE THREAD

**Issue by will-rkr** [docker/for-mac#4807]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I didn't see a way to reopen #4549. I am still having the same issue and seeing the same error on MacOS 10.15.6 and the latest stable build of Docker, 2.3.0.4. I realize the old issue was closed automatically but it would help to keep it open until we have a fix. If I roll back to the older builds it resolves the problem. Any updates? 

### Information

  - macOS Version: 10.15.6

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
The previous issue wasn't closed automatically: I closed it when the fix made it to the Edge release. It will automatically get into the next Stable major release (2.4.*), or if you want it earlier you can switch to the Edge channel.
