### ISSUE TITLE
Can't open tutorial webpage

### ISSUE THREAD

**Issue by manopapad** [docker/for-mac#4809]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 624603FB-4A5F-4F5D-86D9-8E45816B93F6/20200728031704

### Expected behavior

Tutorial webpage (localhost:8080 for me) should be reachable in a browser.

### Actual behavior

Tutorial webpage is not found.

### Information

  - Is it reproducible? yes
  - Is the problem new? no (first time trying docker for mac)
  - Did the problem appear with an update? no
  - macOS Version: Catalina

### Steps to reproduce the behavior

  1. Download Docker for Mac
  2. Follow tutorial steps, changing ports from 80:80 to 8080:8080 because 80 is used by Apache on my machine.
  3. Try to open localhost:8080

**Comment by stephen-turner** [comment]
I think you want 8080:80. The first number is the host port, the second number is the container port. So if the web page is exposed on port 80 from the container's point of view, but you want to access it at localhost:8080, then `docker run -p 8080:80` is what you want.

**Comment by manopapad** [comment]
Thanks, that was silly of me, I assumed X:Y represented a range.

**Comment by stephen-turner** [comment]
No problem, happy to help!
