### ISSUE TITLE
Docker won't start after switching laptops using Migration Assistant

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4810]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: It won't upload a diagnostic because it won't start

### Expected behavior
Docker starts and all data is available after using Migration Assistant

### Actual behavior
Docker won't start

### Information
  - macOS Version: 10.15.5

### Diagnostic logs
It shows this error when trying to start:
```
2020-07-28T04:58:48Z dockerd time="2020-07-28T04:58:48.121949000Z" level=debug msg="Calling GET /images/sha256:8a2fb25a19f5dc1528b7a3fabe8b3145ff57fe10e4f1edac6c718a3cf4aa4b73/json"
```

### Steps to reproduce the behavior
  1. Setup Docker on 1 laptop
  2. Use Migration Assistant to move to another
  3. Run Docker and observe that it doesn't start

**Comment by stephen-turner** [comment]
Hmmm. Presumably Migration Assistant isn't copying some file it needs. But I'm not clear exactly what files it does copy.

**Comment by daveisfera** [comment]
Ya, I don't know anything about the specifics of how Migration Assistant works, but the hardware problems on my laptop finally started flaring up to the point that I needed to switch. After migrating last night, all other applications appear to have moved over correctly but Docker appears to have not fully migrated as part of the process.
