### ISSUE TITLE
File event notifications stop firing on host bind mount

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4811]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20200616212522

### Expected behavior
We build a base image with the needed packages (like the Postgres driver) and then mount our code to run in that container for live code editting. This file event notifications should continue to work indefinitely.

### Actual behavior
After a few days, the file event notifications stop firing so tools like `nodemon` and `pyinotify` stop updating the code as they should and Docker has to be restarted for this to start working again.

### Information
  - macOS Version: 10.15.5

### Diagnostic logs
This doesn't existing in the current Docker for Mac

### Steps to reproduce the behavior
  1. Build a base image
  2. Mount a host directory in the container
  3. Run monitoring inside of the container
  4. Observe that events stop after a day or two of the process running

**Comment by stephen-turner** [comment]
Thanks, @daveisfera, do you have any idea of whether there's a trigger for them going wrong?

Also, does it depend which of the caching modes you're using?

**Comment by stephen-turner** [comment]
Oh, and when did you take the diagnostics report? Just after it had gone wrong?

**Comment by daveisfera** [comment]
I haven't noticed any specific event or type of even that triggers the issue and it happens with both our node and python containers and seems to be universal (i.e. happens to all running containers and not just specific ones). I run the diagnostic as soon as I notice the problem before restarting to get back to work and that diagnostic was pre-mutagen and I haven't run things enough to see if it happens with the current Edge build or not.

**Comment by djs55** [comment]
@daveisfera I've seen similar reports before, but haven't managed to get to the bottom of them (yet).

If you'd like to try an experiment, I have a development build which uses a different filesharing implementation on Mac and which should have more reliable event delivery. The build is: https://desktop-stage.docker.com/mac/edge/46950/Docker.dmg - unfortunately it's signed but not notarized so you would need to right click it and select "Open" to override the notarization check.

To see whether the new code is active, run a command like:
```
$ docker run -it -v /tmp:/foo alpine mount | grep /foo
grpcfuse on /foo type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
-- `grpcfuse` is the new code; `osxfs` is the old.

If you get a chance to try it, let me know how it goes!

**Comment by daveisfera** [comment]
I'm actively using Docker for my daily workflow, so running Edge is already a pretty big risk and switching over to an experimental build is more than I can mess with.

**Comment by bacoboy** [comment]
Would this manifest itself as memory steadily growing on the com.docker.osxfs process (which can only be cleared with a restart of docker -- restarting/recreating the container instances has no effect).

**Comment by bacoboy** [comment]
Hey @djs55 -- I've been running w/ your experimental `grpcfuse` implementation (edge 46950) and so far my particular expanding memory on `osxfs` issue (could be a different issue than this ticket) hasn't occurred -- granted I'm only a day into testing, but usually don't make it this far.  My memory is nice and steady where the current builds `osxfs` grows until the mac crashes for this app (high IO thru volume mounts).

Is the `grpcfuse` implementation going to be hitting mainstream anytime soon?  Has it been decided this is the way forward for `docker/for-mac` over `osxfs`?

**Comment by stephen-turner** [comment]
@bacoboy Thanks for reporting your experience. Not decided, which is why we're asking for feedback. But early reports are good.

**Comment by daveisfera** [comment]
I've been running with 3 edit containers for over a week now and ran our tests a few times (usually what would be the most likely to trigger the issue after a few times since it creates 5-10 edit containers) and haven't noticed any issues yet, so it appears that this must be fixed in the current Edge builds. I had `:delegated`/mutagen running for the first 2-3 days, but then after [running some tests](https://github.com/docker/for-mac/issues/1592#issuecomment-669391023), I found that using `:cached` performed better and didn't have the issues that have been discussed with the current setup, so I've switched to not using `:delegated`/mutagen at all and will keep an eye out for this issue, but looks like it can be closed.

**Comment by stephen-turner** [comment]
Thanks for the update, @daveisfera.
