### ISSUE TITLE
Multiple bind mounts in docker-compose for the same directory will create multiple mutagen resources

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#4812]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20200728180253

### Expected behavior
A single mutagen resource is created when multiple containers use the same mounted directory

### Actual behavior
Multiple mutagen resources are created for the same mount directory when it seems like only a single resource should exist (it appears that there's a chance that this is just a UI fluke because the percent complete stayed the same for both as it was syncing)

### Information
  - macOS Version: 10.15.5

I was looking into to see if I could reproduce #4811 and noticed this issue

### Diagnostic logs
Doesn't exist in the current Docker for Mac

### Steps to reproduce the behavior
  1. Create a .yml file that mounts the same directory twice
  2. Run `docker-compose`
  3. Observe that multiple resources appear from the mutagen mounts

**Comment by stephen-turner** [comment]
@djs55 Did you fix this recently?
