### ISSUE TITLE
Can't disable storing logins in macOS keychain after enabling it.

### ISSUE THREAD

**Issue by ngtuna** [docker/for-mac#4815]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Can disable macOS keychain after enabling it.

### Actual behavior

Can't!

### Information

  - macOS Version: 10.15.5

### Diagnostic logs

```
Docker for Mac: version 2.3.0.4 (46911)

```

### Steps to reproduce the behavior

  1. enable "Securely store Docker logins in macOS keychain" in Docker -> Preferences.
  2. try to disable it.

**Comment by khumps** [comment]
Everyone on my team is reporting the same issue. Any response to this?
