### ISSUE TITLE
Bring back the bomb icon

### ISSUE THREAD

**Issue by smactive** [docker/for-mac#4819]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7355608

### Expected behavior
"The bomb" has entered into the vocabulary of my small world. We all know that sometimes you just gotta click the bomb. So when a friend is struggling and in need of help and you know that all they need to do is click on that bomb, you want to say with a comforting level of confidence "Yeah, I got you buddy. you just need to click that bomb and you will get yourself right back on track"

### Actual behavior
Your friend does not know of this fabled bomb you speak of, or worse, they do indeed know the bomb is no myth only to be hit moments later with a dizzying sense of confusion that inevitably leads into an ugly downward spiral of mental instability.

### Information
  - macOS Version: 10.15.5 (19F101)

### Diagnostic logs
```
Docker for Mac: version 2.1.0.5

### 2016-06-06 1.11.1-beta14.1

* Bug fixes and minor changes
    - settings: updated toolbar icons (#3476)

```

### Steps to reproduce the behavior

  1. Open Docker preferences
  2. Cry

**Comment by stephen-turner** [comment]
SOMEBODY SET UP US THE BOMB.
