### ISSUE TITLE
Docker stops responding (hangs) to CLI 

### ISSUE THREAD

**Issue by CounterBug** [docker/for-mac#482]
### Steps to reproduce

I was doing normal tinkering (building images/running containers) related to docker when all of a sudden docker stopped responding on CLI.

I did restart docker couple of times and after a while the same behaviour started occurring.

```
Diagnostic ID: A94C4A45-06AB-45A9-964E-7CC8186C9F87
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by CounterBug** [comment]
Seems this is a common issue and *had* been reported. I missed while scanning for similarity. Closing.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
