### ISSUE TITLE
Can't open menu items (About Docker Desktop, Preferences, Troubleshoot etc.)

### ISSUE THREAD

**Issue by huahuayu** [docker/for-mac#4825]
## version
Docker version 19.03.12, build 48a66213fe

## problem
when click the items in menu, no windows will be open, I can get into the preferences settings.

there's a docker icon in dock, in a flash, but no windows will be open. 
![image](https://user-images.githubusercontent.com/1725060/89144265-ca4f9f00-d57f-11ea-8aca-8d0c0f60442c.png)

there's a same issue in https://github.com/docker/for-mac/issues/3981, not been solved but closed.

I have try https://github.com/docker/for-mac/issues/3981#issuecomment-646859680 method, which is 

```
rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
ln -s /usr/sbin/ioreg to /usr/local/bin
```

but not working.

**Comment by peterj** [comment]
I had the same issue, tried the same thing and it didn't work. I followed the instructions [here](https://nektony.com/how-to/uninstall-docker-mac) and pretty much deleted everything related to docker. After reinstalling Docker, I was able to open the Preferences window again.
