### ISSUE TITLE
Spinning forever on Preferences tab

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#4827]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2984509E-BD01-4F9C-AC7A-F5018336BD82/20200804045303

### Expected behavior
Preferences tab works, can click around
### Actual behavior
Spinning, won't let me click, Docker running and Kubernetes starting (never does though)
### Information
haven't had this problem in previous release, will try a reboot
  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...
10.15.6 (19G73)
```

### Steps to reproduce the behavior
  1. Open Preferences from docker icon

**Comment by jamshid** [comment]
The problem persisted after reboot. Troubleshooting => Reset Kubernetes did not help.

Kubernetes not starting is the problem. I selected docker icon => Restart and that removed the spinner so I quickly pressed Kubernetes and unchecked Enable Kubernetes then Apply and Restart. After a bit Docker started and the Preferences panel worked as expected.

**Comment by chujanen** [comment]
I am also having this issue and the workaround @jamshid mentioned did get me access to Preferences but k8s is not starting.

**Comment by raix** [comment]
also experiencing this (not sure if it's related to the issue preventing k8s to run?)

**Comment by dangthanh360** [comment]
I am also having this issue too

**Comment by chujanen** [comment]
I ended up uninstalling and reinstalling which resolved my issue.

**Comment by vcaboara** [comment]
Experiencing with Docker version 19.03.12, build 48a66213fe.
