### ISSUE TITLE
Connections being closed

### ISSUE THREAD

**Issue by kciredor** [docker/for-mac#4830]
Please reopen issue https://github.com/docker/for-mac/issues/1374 because it should not have been (auto) closed for the reason the bug is still there. For 3 years now, btw...

**Comment by stephen-turner** [comment]
Thanks for the report, @kciredor. That ticket wasn't autoclosed: it was closed by a developer on 26 Jul 2018. It seems that the original issue that lots of people were seeing was fixed at that time. There were only very occasional reports after that, so I think it must be a different issue.

So let's start again. Could you please describe the exact symptoms that you are now seeing, steps to reproduce, and include a diagnostics id? Thank you.

**Comment by kciredor** [comment]
Hi @stephen-turner thanks for your fast response! You are absolutely right, I was mistaken by the "docker locked and limited conversation to collaborators on 23 Jun" which I concluded to be auto-close too fast.

Will respond with additional info soon.

**Comment by kciredor** [comment]
I'm using the latest stable Docker for Mac.

From inside a container:
- Running "kops update cluster --yes" in a loop, which supports the "kops rolling-update cluster --yes" command on specifically OpenStack.
- "kops update cluster" generates tens of https GET/POST calls to the OpenStack and Swift API endpoints.
- After a while, "kops update cluster" will hang. This becomes worse over time (first few minutes it's fine, then everything slows down, eventually nothing comes through anymore). Adding verbosity will show you it stalls on those API calls.
- The OpenStack provider saw nothing special in the logs except for SSL timeouts. From my side I see I/O timeouts.
- Restarting Docker will fixes the problems.

On the other hand if I do the exact same things outside of a container, everything is fine, there is no way to trigger this problem even if I run 5x "kops update cluster --yes" in parallel.

My colleagues were able to reproduce as well. To be quite honest this feels similar to the closed #1374 which was locked.

Please forgive me in not dumping a diagnostics log as I'm not going to run cluster updates right now just for creating an issue, I hope you understand ;-)

Cheers!

**Comment by stephen-turner** [comment]
Thanks. Could you upload diagnostics when it next happens? We will need that in order to look at the logs. Thanks.
