### ISSUE TITLE
Attempt to open 2.3.0.4 results in Fatal Error: "The data couldn't be read because it isn't in the correct format."

### ISSUE THREAD

**Issue by jrrdnx** [docker/for-mac#4836]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1D4AFFCC-AAFE-480B-A272-C69880F8CFBF/20200809123723

### Expected behavior

Docker should fully open when double-clicking the app.

### Actual behavior

Docker starts to open, but always results in the following screen.

![Screen Shot 2020-08-08 at 4 19 56 PM](https://user-images.githubusercontent.com/4584671/89732069-11271400-da1a-11ea-8056-808097edb740.png)

### Information

I was previously running an older version of Docker (2.1.x.x) and have attempted to update to the latest version several times. Each time it would complete (or nearly complete) the download and fail (my internet at home is horrible and this would take several hours) so I downloaded the latest DMG while at work on a faster connection. I closed the current running version and installed the latest (2.3.0.4) and encountered the above fatal error.

Then using the [Logs and Troubleshooting](https://docs.docker.com/docker-for-mac/troubleshoot/) guide I uninstalled Docker via the command line and attempted to install the latest version using the downloaded DMG, but encountered the same error.

After trying to completely erase all Docker-related files and reinstalling several times, I was able to restore a backup of my previous version (2.1.x.x) using Time Machine. I then re-attempted updating via the in-app method, and this time it was able to fully download the update and complete successfully. But when opening the Docker app, I again encountered the above Fatal Error.

macOS Version: 10.14.5

### Diagnostic logs

I have been running the Diagnostics tool via the "Diagnose & Feedback" button in that Fatal Error window, but it ran for 16+ hours with no update/completion. Is this normal?

Running via the command line: 
Diagnostics ID:     1D4AFFCC-AAFE-480B-A272-C69880F8CFBF/20200809123723 (uploaded)

### Steps to reproduce the behavior

  1. Update to latest version (2.3.0.4) via various methods (in-app update, stopping and running fresh DMG)
  2. Attempt to open Docker

**Comment by jonitiso** [comment]
I have the same problem :c

**Comment by jrrdnx** [comment]
After restarting my Mac several times, I continue to get one of the following fatal errors at startup (Docker seems to full start and runs for 20-30 seconds or so before either of these appear):

![Screen Shot 2020-08-10 at 6 39 10 PM](https://user-images.githubusercontent.com/4584671/90991346-7fb9b500-e576-11ea-9fa6-b650a0d9b9a5.png)

![Screen Shot 2020-08-13 at 5 06 00 PM](https://user-images.githubusercontent.com/4584671/90991350-8ba57700-e576-11ea-9576-78afeafbe4c4.png)

This afternoon, I completely formatted my main hard drive (SSD) and installed macOS Catalina via a bootable USB drive (also downloaded and created this afternoon, so is using the latest version). After restarting and installing Docker (still v2.3.0.4) via Homebrew, I continue to see the above fatal errors at startup.

new macOS version: 10.15.6

Note: I have macOS and all applications installed to a primary SSD (/Volumes/Macintosh SSD), but all personal files on a separate HDD which is where my Home folder is set to: /Volumes/Macintosh HD/Users/. This has been my setup for 7+ years and I had no issues running earlier versions of Docker, but thought I'd mention it in case it has any effect.
