### ISSUE TITLE
Force reboot and error: 6B7B70B0-4BA1-4569-AAE8-C6201FF69FC9

### ISSUE THREAD

**Issue by capitolmuckrakr** [docker/for-mac#485]
### Expected behavior
Docker lists containers
### Actual behavior
    Error response from daemon: Bad response from Docker engine
### Information

Diagnostic ID: 6B7B70B0-4BA1-4569-AAE8-C6201FF69FC9
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/alex/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/6B7B70B0-4BA1-4569-AAE8-C6201FF69FC9/20160831-151307/qemu-img-check.stdout 2> /tmp/6B7B70B0-4BA1-4569-AAE8-C6201FF69FC9/20160831-151307/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

    docker ps
2. restarting Docker doesn't resolve
3. rebooting doesn't resolve

**Comment by dave-tucker** [comment]
@capitolmuckrakr Has Docker for Mac ever worked? Or did this problem occur after using Docker for a while?

**Comment by capitolmuckrakr** [comment]
It worked fine for about three weeks under light usage. I ran and customized a couple of large images -- stanbol and ckan. Skimming the logs showed a few errors -- I'll take another look and post those.

**Comment by mchiang0610** [comment]
Merging with #119 

Possible fix by some of our users right now has been trying the factory reset. We are still looking into this.

**Comment by capitolmuckrakr** [comment]
My system was having general problems with the GPU, not confident the error was specific to docker
