### ISSUE TITLE
Preferences never load; Kubernetes never starts

### ISSUE THREAD

**Issue by 2step** [docker/for-mac#4851]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I go to Docker Desktop > Preference, the preferences page should load quickly.  Instead, a spinner appears and, even after several minutes, the preferences panel never loads.

I came across the above issue when trying to figure out why I was seeing 'Kubernetes starting...' and Kubernetes was never able to reach the 'Kubernetes started' state.

### Actual behavior
I click on Docker Desktop > Preferences and see a (page loading) spinner that never goes away. 

### Information

  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Click the Docker Desktop icon
  2. Choose 'Preferences...'
  3. The panel with the title 'Preferences' appears, but the content on that panel never loads.

**Comment by cilphex** [comment]
Getting the same thing.

<img width="1152" alt="Screen Shot 2020-08-26 at 4 27 45 PM" src="https://user-images.githubusercontent.com/611803/91353406-17e6b280-e7a0-11ea-98a7-5c29073bb995.png">

**Comment by huangyiminghappy** [comment]
i have the same situation in the newest docker 2.4.2.0 version,could anyone tell me what to do ?

**Comment by 2step** [comment]
I ended up running ```docker system prune``` to resolve this.  I presume the Docker daemon ran out of cache space or some resource and was getting stuck.  I pruned everything I could and restarted my containers. After that, I was able to get into the Preferences page.
