### ISSUE TITLE
Add ceph-common package to docker-for-mac linux system

### ISSUE THREAD

**Issue by radut** [docker/for-mac#4854]
Add ceph-common package to linux kit build subsystem so that 'rbd' map will work. This is required for adding storage class of type rbd.

  - [ X ] I have tried with the latest version of my channel (Stable)

### Expected behavior

ls /usr/bin/rbd  - should be present

### Actual behavior

rbd binary is not there

**Comment by stephen-turner** [comment]
@radut Could you please file this at https://github.com/linuxkit/linuxkit? Thanks. (Sorry, I would just move the ticket, but it's not possible because linuxkit is not in the docker org).
