### ISSUE TITLE
Please enable cephfs and rbd kernel modules

### ISSUE THREAD

**Issue by radut** [docker/for-mac#4856]
https://github.com/docker/for-mac/issues/1781 - closed but never shipped.
this seems to be merged : https://github.com/linuxkit/linuxkit/pull/2963

but docker-for-mac lacks the binary "rbd" and support for mapping devices(modprobe rbd)

```
modinfo: module '/lib/modules/4.19.76-linuxkit/rbd' not found
modprobe: module rbd not found in modules.dep
```

**Comment by stephen-turner** [comment]
@radut Could you retest with 2.5? We're now up to date with upstream LinuxKit, so I think these modules should be present.
