### ISSUE TITLE
Docker not starting on mac when kubernetes is enabed

### ISSUE THREAD

**Issue by vgaur** [docker/for-mac#4857]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7F480C07-1797-4AFE-A2F0-489A1178B3DB/20200822160407

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cilphex** [comment]
Getting the same thing. Docker desktop on Mac gets permanently stuck once you enable Kubernetes in the settings. Since everything's stuck, you can't just disable it either.

<img width="1152" alt="Screen Shot 2020-08-26 at 4 27 45 PM" src="https://user-images.githubusercontent.com/611803/91353313-f1c11280-e79f-11ea-81c5-026f4bc7f576.png">

**Comment by qmilangowin** [comment]
Same issue for me. Uninstalled, re-installed latest stable release. Same issue. Stuck.
Cannot only disable it via editing the settings.json file in Library/Group Containers/group.com.docker
However, I need the cluster to work. Right now seems like I need to go back to minikube

My diagnostic id is: 573AA9F4-133B-452F-A6B3-F26549B7102B/20200829165300

**Comment by qmilangowin** [comment]
I had this issue. I uinstalled completely re-installed and that seems to have finally worked. This is on the latest stable release. However, previously, resetting to factory defaults, resetting the K8S cluster did nothing. 
I had to disable the k8s cluster in settings.json in Library/Group Containers/group.com.docker to even access the settings.

**Comment by SkylerWittman** [comment]
Maybe this is useless but I tried all of the steps outlined here as well as completely removing the app and all leftover docker related settings on my Mac and reinstalling (both normal and Edge).

In the end I turned off my laptop for the weekend and returned on Monday morning to a functional Docker...
So for anyone who didn't have luck uninstall and re-installing try a reboot then a leave for the weekend and let magic take hold.
