### ISSUE TITLE
Preferences window hangs (waits forever until cancel) after upgrade Docker for Mac in OS Catalina 

### ISSUE THREAD

**Issue by doron-levi** [docker/for-mac#4858]
I have been having issues running tests on my mac (tests using containers) after upgrading OS to Mac Catalina, so I upgraded my docker for mac, still got issues with mounted, I tried to open Docker for Mac Preferences but it hanged.

  - [ x] I have tried with the latest version of my channel (Stable)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 7C4D4B62-D82F-4D9F-A48C-FDA3D40F5253/20200824135323

### Expected behavior 
I can edit preferences

### Actual behavior 
preferences window hangs
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible?
  - Is the problem new? after upgrade to latest Docker for Mac
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug

  - macOS Version: Catalina 10.15.6

### Diagnostic logs
Uploaded
Docker for Mac: version...

**Comment by kschwidder** [comment]
+1

**Comment by jerrythomas** [comment]
I have the same issue. I also noticed that Kubernetes status is always `starting` although I can create and run k8s clusters.
Clicking on `Reset Kubernetes Data` and `Clean / Purge data` also did not resolve this issue.
Even after Uninstall and reinstall the issue remains the same

Uploaded diagnostic id `5A263E6D-AAE6-4EE1-BAEE-016F3B3ACA3A/20200826052228`.

**Comment by arnaudsimon** [comment]
+1
