### ISSUE TITLE
 host_mnt gets incorrectly prefixed to named volume mounts on mac

### ISSUE THREAD

**Issue by lauripiisang** [docker/for-mac#4859]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1DE42167-F6B0-46DB-9F58-47200D557065/20200824143958

### Expected behavior
When using a docker-compose file with named volume, a volume gets created with the path specified

### Actual behavior
/host_mnt is prefixed to the path as response

### Information
This happens on latest Edge version (2.3.5.0) with gRPC FUSE enabled. 
[I initially reported it in docker-compose repo][1], but realized that compose version is the same and it's likely not their issue.
  - macOS Version: 10.15.5

### Diagnostic logs
Sorry, I've replaced the current installation with Stable once again, but this is the info I gathered for docker-compose issue

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.12
 Version:           19.03.13-beta2
 API version:       1.40
 Go version:        go1.13.14
 Git commit:        ff3fbc9d55
 Built:             Mon Aug  3 14:58:48 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13-beta2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.14
  Git commit:       ff3fbc9d55
  Built:            Mon Aug  3 15:06:50 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Steps to reproduce the behavior
**Output of `docker-compose config`**
```
services:
  myservice:
    image: busybox:latest
    volumes:
    - my-service-volume
version: '3.0'
volumes:
  my-service-volume:
    driver: local
    driver_opts:
      device: /Users/lauripiisang/emptyvol
      o: bind
      type: none
```

1. replace my username with yours in the given above config, copy it to `docker-compose.yml`
2. run `docker-compose -p hostmnt-bug-demo up` 
3. run `docker inspect hostmnt-bug-demo_my-service-volume`

### Observed result
```
[
  {
...
        "Name": "hostmnt-bug-demo_my-service-volume",
        "Options": {
            "device": "/host_mnt/Users/lauripiisang/emptyvol",
            "o": "bind",
            "type": "none"
        },
...
```

as a result, non-existant path will be attempted to be mounted and subsequent calls to docker-compose up will fail with error:
```
ERROR: Configuration for volume my-service-volume specifies "device" driver_opt /Users/lauripiisang/emptyvol, but a volume with the same name uses a different "device" driver_opt (/host_mnt/Users/lauripiisang/emptyvol). If you wish to use the new configuration, please remove the existing volume "hostmnt-bug-demo_my-service-volume" first:
$ docker volume rm hostmnt-bug-demo_my-service-volume
```

### Expected result
```
[
  {
...
        "Name": "hostmnt-bug-demo_my-service-volume",
        "Options": {
            "device": "/Users/lauripiisang/emptyvol",
            "o": "bind",
            "type": "none"
        },
...
```

## Additional information

I didn't know exactly which component this affects, but seems to be docker-compose calling an API and receiving an odd response.

When running with ` docker-compose --verbose -p hostmnt-bug-demo up`, API call can be seen to work incorrectly:
```
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('hostmntbugdemo_my-service-volume')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/volumes/hostmntbugdemo_my-service-volume HTTP/1.1" 404 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('hostmnt-bug-demo_my-service-volume')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/volumes/hostmnt-bug-demo_my-service-volume HTTP/1.1" 404 None
compose.volume.initialize: Creating volume "hostmnt-bug-demo_my-service-volume" with local driver
compose.cli.verbose_proxy.proxy_callable: docker create_volume <- ('hostmnt-bug-demo_my-service-volume', 'local', {'type': 'none', 'device': '/Users/lauripiisang/emptyvol', 'o': 'bind'}, labels={'com.docker.compose.project': 'hostmnt-bug-demo', 'com.docker.compose.volume': 'my-service-volume', 'com.docker.compose.version': '1.26.2'})
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/volumes/create HTTP/1.1" 201 None
compose.cli.verbose_proxy.proxy_callable: docker create_volume -> {'CreatedAt': '2020-08-24T14:59:50Z',
 'Driver': 'local',
 'Labels': {'com.docker.compose.project': 'hostmnt-bug-demo',
            'com.docker.compose.version': '1.26.2',
            'com.docker.compose.volume': 'my-service-volume'},
 'Mountpoint': '/var/lib/docker/volumes/hostmnt-bug-demo_my-service-volume/_data',
 'Name': 'hostmnt-bug-demo_my-service-volume',
 'Options': {'device': '/host_mnt/Users/lauripiisang/emptyvol',
             'o': 'bind',
             'type': 'none'},
...
```

[1]: https://github.com/docker/compose/issues/7705

**Comment by Zae** [comment]
I've been having the same issue on mac and my colleague has been having the problem too but on WSL2. He found this issue: https://github.com/docker/for-win/issues/7431, could be a docker wide problem not specific docker-for-mac?

**Comment by stephen-turner** [comment]
@djs55 This seems to be a side effect of using grpcfuse instead of osxfs. Could you PTAL?

@lauripiisang and @Zae You can switch back to osxfs in the settings, that should work around this bug for the moment. (Although be aware that before 2.3.6.1 the checkbox had the wrong initial value so it's probably simplest to upgrade first).

**Comment by Zae** [comment]
Thanks @stephen-turner 

That seems to have fixed it.

**Comment by lauripiisang** [comment]
@stephen-turner yeah, I only went on edge to try out grpcfuse - no issues on stable.

**Comment by djs55** [comment]
I believe the issue with `/host_mnt` has been fixed for both Windows and Mac in the latest Edge 2.3.7.0: https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2370 Calls to `docker inspect` will show the original unmodified source path, and `docker-compose` should be happier. Let us know how you get on! I'll close this issue now but feel free to open new ones if you have further problems.

Thanks for your report!
