### ISSUE TITLE
Problems Starting Docker for Mac

### ISSUE THREAD

**Issue by mikebronner** [docker/for-mac#486]
### Information

Diagnostic ID: D9BAC4CE-2546-4F30-8853-80B868A60B51
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Start from launchpad.

**Comment by dave-tucker** [comment]
Thanks for the report @mikebronner 

Are you saying that you **can** start Docker for Mac, but **not** from Launchpad?
Ir ar you saying that you can't start Docker for Mac **at all**?

**Comment by mikebronner** [comment]
HI @dave-tucker,

It starts, but I cannot complete any operations with it. Everything I try results in some form of error message.

To resolve this, I have had to remove all traces of any previous Docker installations on my Mac, after that everything worked flawlessly. I guess my recommendation would be to add that functionality to the factory reset button in preferences, and make sure all legacy docker files are removed? My hunch is that it was a conflicting setting somewhere.

Thanks!

**Comment by dave-tucker** [comment]
Thanks @mikebronner - we've already got an issue opened for making the uninstaller more thorough so I'll close this one for now!

**Comment by mikebronner** [comment]
Cool :) I'm not sure the uninstaller will solve the issue though. Uninstalling is relatively uncommon for Mac users, instead they just drag the app to trash (at least I do). Thanks for having eyes on this. :)

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by mikebronner** [comment]
Thanks for the update, @djs55 . I'm not using it currently, but will install the updated version when I do again. (I expect it will be early next year.)
