### ISSUE TITLE
Getting Unexpected EOF error 

### ISSUE THREAD

**Issue by amareshbonam** [docker/for-mac#4870]
Why docker not able to resume the image. We have images upto 15GB and whole workspace facing EOF issue or some sha mismatch issue or after complete download again it will start from begining. when you are going to fix these important issues

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by krichter722** [comment]
Still an issue
