### ISSUE TITLE
Container is freezing up and requires `docker-compose down` to kill it

### ISSUE THREAD

**Issue by tcaddy** [docker/for-mac#4876]
- [x] I have tried with the latest version of my channel (Only Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 92EB0BFA-1023-4374-AC1D-59E7E9D3F922/20200904160005

### Expected behavior
Expect containers to run without freezing.

Should be able to press `CTRL + C` to kill a process and then exit container cleanly.

Should be able to run `docker exec -it [container name] bash` to get a bash shell into the same running container (I can do this) and then be able to `kill -9 [pid]` unresponsive process that's freezing up a container (this has no effect on frozen container).

Should be able to run `docker-compose down` without getting a timeout error.  Should not have to run `docker-compose down` and wait for timeout error in order to have frozen container respond to `CTRL + C`.

### Actual behavior
Kinda already described in my "expected behavior" section.  This is a dockerized Ruby on Rails app.  I'm running a process from the Rails console to iterate through stuff and query/update a database.  It gets about 10 seconds into the process before it becomes unresponsive.  There is no longer a bunch of output flying by on the screen to show it's busy.  I've added lots of `puts` statements to the code to help me see where it's freezing up, plus in development mode, rails will output all the database queries.  It is not freezing up at the same spot each time.  If I try to press `CTRL + C`, nothing happens.

I can do `docker exec -it [container] bash` to get a bash shell into the running container.  If I install and run `htop`, I can see that there's plenty of CPU and memory available.  If I try to `kill -15 [pid]`, nothing happens.  But if I `kill -9` it, it goes away from `htop`.  However, the original screen for the container is still frozen and won't respond to `CTRL + C`.

I have to run `docker-compose down`, which takes forever and outputs a message about exceeding a timeout.  At this point, I can `CTRL + C` (have to press it twice) and I get a carriage return in the output and then it brings me back to a terminal on the host machine.

Then I have to run `docker-compose down` again for it to finish bringing stuff down.

At this point, I can try again and the cycle repeats.

### Information
  - macOS Version: 10.15.6
  - Is it reproducible? YES
  - Is the problem new? It is new to me
  - Did the problem appear with an update? I think so, it seems like I did an update (to Docker Desktop) a few days ago and then it happened after the update.

### Diagnostic logs
Here's the ID for the diagnostic stuff I sent to Docker: 92EB0BFA-1023-4374-AC1D-59E7E9D3F922/20200904160005

### Steps to reproduce the behavior
Kinda long and drawn out, but should be specified already in the expectations vs what is really going on sections.  Comment on this if issue if you need more info.

Thanks!

**Comment by tcaddy** [comment]
Update: Downgrading to v2.3.5.0 seems to have fixed the problem for me.  I just ran the same long running process from the rails console and it completed OK.

**Comment by stephen-turner** [comment]
Thanks for the report, investigating.

**Comment by mat007** [comment]
I wasn’t able to reproduce the issue with the following steps:
1. create a file `main.go` containing
```
package main

import "fmt"

func main() {
    fmt.Println("running")
    for {
    }
}
```
2. in terminal 1 `docker run --rm -v $(pwd):/bla -w /bla --name ctrl-c golang go run .`
```
running
```
(and blocks)
3. in terminal 2 `docker exec -it ctrl-c bash`
4. in terminal 2 `top` to get the PID of the process
5. in terminal 2 `kill -15 «PID»`
Both terminals exit.

I have tried with both 2.3.6.0 and 2.3.5.0 and couldn’t see a difference in behaviour.
Am I missing something?

**Comment by tcaddy** [comment]
I'd be surprised if you can replicate it.  Even other people on my team haven't described the issue happening to them.  I thought there might be something in the diagnostic logs to provide a clue.

I saw a minor point release update available that I am holding off on trying right now.  I have to get some stuff done for work.  But I'll try to circle back to that update (or whatever the latest edge release is at the time) in the next week or so and give this issue an update if the problem persists or goes away.

**Comment by jonas-bosson** [comment]
I have the same issue after upgrade to docker 3.0.1 (50773) and have to go as far as restart docker after simply trying to Ctrl-C a bash process under docker.
