### ISSUE TITLE
Issue running docker in my mac OS Big Sur v11.0

### ISSUE THREAD

**Issue by silwalprabin** [docker/for-mac#4877]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B2637A81-81A7-4807-BE05-4B496FDEB82E/20200905025144

### Information

  - macOS Version: v11.0

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by silwalprabin** [comment]
Fixed after upgrading to docker version 2.3.0.4 (46911)

**Comment by silwalprabin** [comment]
Got issue again each time restarting my mac; So, reponed  :( 






  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B2637A81-81A7-4807-BE05-4B496FDEB82E/20200906054629

### Expected behavior
Docker should start normally in background

### Actual behavior
Docker throws error naming socket error...

### Information

  - macOS Version: v11.0

### Diagnostic logs

```
Docker for Mac: version 2.3.0

```

### Steps to reproduce the behavior


  1. Restart your mac
  2. Error popups  within 3 seconds of mac loads desktop

**Comment by stephen-turner** [comment]
Thanks for the report but Big Sur is not yet supported, closing this ticket.

**Comment by RazaGR** [comment]
@silwalprabin a workaround for me was to open docker manually by going in Applications > Docker (right click) > contents > MacOS > Docker Desktop 

@stephen-turner I think issue should remain open as its not resolved

**Comment by stephen-turner** [comment]
There is no need to leave the issue open as it is outside the support envelope. However, we are working on it and it will be supported when Big Sur is released.

**Comment by djs55** [comment]
The auto-login issue in Big Sur should be fixed in [stable 2.4.0.0](https://desktop.docker.com/mac/stable/48506/Docker.dmg).

I'm not aware of any other problems on Big Sur (beta) but if you encounter any,  please open fresh tickets.

Thanks for your report.
