### ISSUE TITLE
docker issue for-mac

### ISSUE THREAD

**Issue by M-Abdelmoneim** [docker/for-mac#4878]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by seagle0128** [comment]
What fuck why locked #3232? It seems no one has a willing to fix the memory leak issue indeed! They don't like macOS.
