### ISSUE TITLE
How do I completely uninstall Docker for Mac?

### ISSUE THREAD

**Issue by tbodt** [docker/for-mac#488]
I've been having some issues with Docker for Mac, and tried uninstalling and reinstalling. However, the uninstall procedure crashed halfway through. Ever since, I haven't been able to get Docker for Mac to work at all, which I suspect has something to do with old files that the uninstaller never got around to deleting.

What's everything that Docker installs, and how do I remove it?

**Comment by tbodt** [comment]
Relevant information: I'm on macOS Sierra 16A294a.

**Comment by dsheets** [comment]
How did you attempt to uninstall initially? How did it fail?

The documentation at <https://docs.docker.com/docker-for-mac/#/uninstall-or-reset> describes the two easiest uninstallation methods.

We don't yet have complete manual uninstallation instructions but if neither of these methods work, we'd really like to understand why and then we'll write something about manual uninstallation.

**Comment by tbodt** [comment]
I just tried the reset button, and it gave the same error message that uninstall gave me:

<img width="710" alt="screen shot 2016-09-01 at 9 32 59 am" src="https://cloud.githubusercontent.com/assets/5678977/18175716/2c705340-7027-11e6-8130-ac9575e335f2.png">

The diagnostic ID it gave is 07BFFAAA-E87B-422F-9F7E-BA6CAB0206A4, although it currently is stuck on "Uploading diagnostic..."

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by tbodt** [comment]
@djs55 Can you give me manual uninstallation instructions so I can install the new version?

**Comment by dsheets** [comment]
Do you still have trouble uninstalling with Beta 26.1 or 1.12.1 on macOS Sierra 10.12 final? Please re-open this issue if you still cannot uninstall using the application. Thanks for your report.

**Comment by tbodt** [comment]
Nope, it uninstalls fine now.

**Comment by BillLucky** [comment]
I also encountered the same problem, download using (Download: https://download.docker.com/mac/beta/Docker.dmg) this version of the mirror after it covers the local old version of the software, and then be able to skip Error warning You can open the program settings page. Click uninstall to re-install just fine, and MacOS Sierra should be a relationship, my system version is: 10.12.

Hope to help, thank you

**Comment by sebathi** [comment]
Tried to uninstall via the terminal and it hangs. Never do anything and did not show any message. 
30 mins waiting - 0:00:40 (100/sec executed only seen on top)

![image](https://cloud.githubusercontent.com/assets/1434034/21730231/8d1555be-d42d-11e6-812c-27ef368cdc91.png)

Is there something I could do?

**Comment by sebathi** [comment]
macOs Sierra.
Docker beta (last version)
Nothing on the logs.
