### ISSUE TITLE
docker crash in big sur

### ISSUE THREAD

**Issue by abdielarauz** [docker/for-mac#4887]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We don't yet support Big Sur.
