### ISSUE TITLE
Fatal error on start-up with macOS 11.0 (Big Sur) Public Beta 6

### ISSUE THREAD

**Issue by ajlowy66** [docker/for-mac#4890]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9B3B4EA6-7166-46C9-AF42-F9CDB8795617/20200909043940

### Actual behavior
Note that Docker appears to work as expected, once the app was opened following the "Fatal Error" notice on reboot of Mac
### Information

  - macOS Version: 11.0 (Public Beta 6)

### Diagnostic logs

```
Docker for Mac: version...2.3.0.4 (46911)

```

### Steps to reproduce the behavior

  1. Unknown

**Comment by stephen-turner** [comment]
We don't yet support Big Sur.

**Comment by djs55** [comment]
The auto-login issue in Big Sur should be fixed in [stable 2.4.0.0](https://desktop.docker.com/mac/stable/48506/Docker.dmg).

I'm not aware of any other problems on Big Sur (beta) but if you encounter any,  please open fresh tickets.

Thanks for your report.
