### ISSUE TITLE
crashed with new macOS version today

### ISSUE THREAD

**Issue by appdevcanada** [docker/for-mac#4891]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 6315FBE9-79F7-41A6-AE46-14DDF03FF693/20200909155501

### Actual behavior
crashed after rebooting new macOS version

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
When you say "new macOS version" you mean Big Sur? If so then yes, Big Sur is not yet supported.

**Comment by appdevcanada** [comment]
Yep, this version today… but was working fine yesterday…

[A screenshot of a cell phone  Description automatically generated]

**Comment by stephen-turner** [comment]
Thanks. We're aware it's not working on Big Sur at the moment. It will be fixed before the release of Big Sur.
