### ISSUE TITLE
Issue on BigSur(20A5364e)

### ISSUE THREAD

**Issue by koji** [docker/for-mac#4893]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CD935C44-4530-4E90-8991-471CD17CD40B/20200909220819

### Expected behavior
Run docker without showing any alert window

### Actual behavior
Showed an alert window that I got errors like the above.

### Information

  - macOS Version: 11.0 Beta (20A5364e)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Reboot macOS

**Comment by stephen-turner** [comment]
Thanks for the report. Big Sur is not yet supported, but we are working on it.
