### ISSUE TITLE
On mac OS 11.0 Beta (20A5364e) startup error

### ISSUE THREAD

**Issue by tygas** [docker/for-mac#4894]
On mac OS 11.0 Beta (20A5364e)

 

 
  - [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Just restarted mac with newest OS
  2. get error on startup

**Comment by stephen-turner** [comment]
Thanks for the report. Big Sur is not yet supported. We're working on it.
