### ISSUE TITLE
E8033772-B8E2-4223-B1C1-3C947B0610EF/20200910153744

### ISSUE THREAD

**Issue by GuoDapeng** [docker/for-mac#4895]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

有时候会把我之前安装过都镜像删除

### Actual behavior

不要删除安装过都镜像。部分设置也重置了。

### Information

  - macOS Version: macOS Big Sur 11.0 Beta版(20A5364e)

### Diagnostic logs

```
Diagnose succeeded
```

### Steps to reproduce the behavior

  1. 重启计算机

或许与 CleanMyMac X 这个软件有关。

**Comment by stephen-turner** [comment]
Thank you for the report. Big Sur is not currently supported.
