### ISSUE TITLE
Fatal Error: The operation couldn’t be completed. (NIO.SocketAddressError error 3.)

### ISSUE THREAD

**Issue by rediska1114** [docker/for-mac#4896]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1F62E6E8-757D-400C-9F4D-290D33E7E029/20200910162723

### Information

  - macOS Version: 11.0 (20A5364e)

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bdharrington7** [comment]
same for A8B80D92-BAD1-4C28-B68E-7ED278137F50/20200911192404
