### ISSUE TITLE
Kubernetes menu missing 'disable local cluster'

### ISSUE THREAD

**Issue by dmorand17** [docker/for-mac#4897]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8491597A-07B1-461D-9E4F-B73D7F602852/20200910174127

### Expected behavior
Kubernetes context menu contains a 'disable local cluster' option
### Actual behavior
Kubernetes context menu does NOT contain a 'disable local cluster' option

### Information
  - macOS Version: 10.15.6 (Catalina)

### Steps to reproduce the behavior

  1. Install docker for desktop (mac version)
  2. Enable Kubernetes
  3. Check Kubernetes context menu to see if 'disable local cluster' option appears

**Comment by stephen-turner** [comment]
Why do you think there should be a disable local cluster option?

**Comment by dmorand17** [comment]
I was shown on another user's workstation how they were able to disable their local kubernetes cluster via docker-desktop but I didn't have that option in my menu.
