### ISSUE TITLE
Docker error after replacing RAM in Mac mini Big Sur

### ISSUE THREAD

**Issue by DaniusLabs** [docker/for-mac#4899]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
No info in the ticket, closing.

**Comment by DaniusLabs** [comment]
Looks like Docker Desktop did not upload the dump. OK.
