### ISSUE TITLE
docker is freeze

### ISSUE THREAD

**Issue by Kogarasi** [docker/for-mac#490]
### Information

Diagnostic ID: 4D91EB36-9F8B-4F33-AD51-67A7E85D825D
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/kogarasi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/4D91EB36-9F8B-4F33-AD51-67A7E85D825D/20160901-190445/qemu-img-check.stdout 2> /tmp/4D91EB36-9F8B-4F33-AD51-67A7E85D825D/20160901-190445/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
Closing due to lack of information
Feel free to add more details for example:
- What you were doing when this happened
- What you expected to happen
- What actually happened
- Were you able to resolve this by rebooting the VM
