### ISSUE TITLE
Docker for Mac seems to listen to port 3000

### ISSUE THREAD

**Issue by weyert** [docker/for-mac#4906]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker for Mac shouldn't listen to port 3000 as that's a common port used while working on a web application, e.g. Next.js, Create React App etc.

### Actual behavior
Docker for Mac has port 3000 open, see:

```
➜ lsof -i tcp:3000
COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 55311 weyert   51u  IPv6 0xedfb4fafdaeeef61      0t0  TCP *:hbci (LISTEN)

➜ ps awx | awk '$1 == 55311 { print $5 }'
/Applications/Docker.app/Contents/MacOS/com.docker.backend
````

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - macOS Version: 10.15.6

### Diagnostic logs
See diagnostics with ID: D038BC41-EA05-489A-AEBB-373C342BB6B1/20200912232851

### Steps to reproduce the behavior
  1. Start Docker for Mac
  2. Try to start an application on port 3000, e.g. `npx create-react-app test && cd test && npm start`

**Comment by StefanScherer** [comment]
Hello @weyert 
I cannot reproduce the problem, first I tried it with Edge version, but now I'm on Stable 2.3.0.4.
Docker Desktop only uses eg. port 3000 when you run a container with it. After stopping or removing the container the port on localhost is available for other processes again.

Could you run `docker ps -a` to see what other containers you have? Maybe there's another container still running in the background that uses port 3000?
Other than that I suggest to restart Docker Desktop to see if the problem is solved.

**Comment by weyert** [comment]
I have restarted Docker for Mac and when I run `docker ps -a` it's returning see below:

```
➜ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
%
```

And when I restart Docker for Mac the port disappears, see while running Docker for Mac:

```
➜ lsof -i tcp:3000
COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 65972 weyertdeboer   49u  IPv6 0xfbd5bd43383ed0cf      0t0  TCP *:hbci (LISTEN)
```

after quitting Docker for Mac:

```
➜ lsof -i tcp:3000

```

when I start Docker for Mac again:

```
➜ lsof -i tcp:3000
COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 67867 weyertdeboer   49u  IPv6 0xfbd5bd43366dfaaf      0t0  TCP *:hbci (LISTEN)
```

Not sure what's owning this port 3000 in Docker for Mac, if I run `docker ps -a` again it doesn't return anything:

```
➜ docker ps -a 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

```

Could it be some experiment? I don't have Kubernetes running

**Comment by StefanScherer** [comment]
Thanks for the tests. That's really weird. I tried 2.3.0.4 on another fresh machine and it doesn't open port 3000 as expected. 🤔 
Next step I suggest would be a factory reset in the Whale menu -> Troubleshoot -> Reset to factory defaults
or even do an uninstall from there and install the latest stable 2.3.0.5 again.

**Comment by weyert** [comment]
```
? Something is already running on port 3000. Probably:
  /Applications/Docker.app/Contents/MacOS/com.docker.backend -watchdog (pid 2632)
  in /Users/weyertdeboer/Library/Containers/com.docker.docker/Data
```

**Comment by weyert** [comment]
Cool, thank you, reset to factory defaults, did the trick! 
Really strange issue 🤷‍♀️ Computers, what to do with them...

**Comment by StefanScherer** [comment]
Oh really? Thanks for reporting back. I‘m glad it works for you again.

**Comment by weyert** [comment]
Yeah, could run something on port 3000 without shutting down Docker for Mac. I will re-open when the problem reoccurs :)
