### ISSUE TITLE
area/database: add ability to set CPU and memory limits from the CLI

### ISSUE THREAD

**Issue by myitcv** [docker/for-mac#4907]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FA4535D4-778D-4CBA-9DD9-1EBD47C668DE/20200913061640

### Expected behavior

To be able to configure the CPU and memory limits from the CLI.

### Actual behavior

Unclear how to do this (if it's even possible)

### Information

  - macOS Version: 10.15.6

### Diagnostic logs

I don't understand this step. Diagnostics ID provided above.

### Steps to reproduce the behavior

n/a

**Comment by nightpool** [comment]
Just ran into this issue today—Our webpack bundle takes more then 2GB to compile, so whenever a new engineer joins our team everyone is super confused for a week about why their webpack server keeps spontaneously existing, until we remember to check the memory limits! would be great if our set up script for Docker Desktop could just automatically set these limits to a more sensible default!
