### ISSUE TITLE
macOS Big Sur 11.0 Beta (20A5364e) Startup Crash

### ISSUE THREAD

**Issue by jpteruel095** [docker/for-mac#4908]
- [/] I have tried with the latest version of my channel (Stable or Edge)
  - [/] I have uploaded Diagnostics
  - Diagnostics ID: F9732143-3B8C-47B1-AAD5-E93646898F08/20200913161930

### Information

  - macOS Version: macOS Big Sur 11.0 Beta (20A5364e) 

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Startup

**Comment by stephen-turner** [comment]
Thank you for the report. Docker Desktop is not yet supported on Big Sur.
