### ISSUE TITLE
Docker becomes slow over time

### ISSUE THREAD

**Issue by mhenrixon** [docker/for-mac#4913]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3BEF2F0-B12A-44B3-B794-305CC5377810/20200915064956

### Expected behavior

I expect docker to keep an even performance over time. The only way to fix it seems to be to reset the disk image and start over again. I had to do this last week as well. The problem for me is that I am on a pretty slow internet connection and it takes a long time for me. Would love to get to the bottom of this.

### Actual behavior

I have no idea what this is related to but after some time docker becomes extremely slow. This is the second time it happens, I've tried restarting docker, restarting the computer and it doesn't help. 

I would be ok with a little slowdown but this is ridiculous. An environment (application) that previously took seconds to start now takes several minutes, even though every single step is cached.

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: 2.3.0.4

```

### Steps to reproduce the behavior

  1. Start docker
  2. Start a variety of containers
  3. Wait....
  4. Wait some more
  5. Let computer go to sleep
  6. Wake computer up and let it go to sleep
  7. Randomly docker becomes so slow it almost comes to a halt.

**Comment by StefanPrintezis** [comment]
Is it over time or the wakeup from sleep that causes the issue?

I've been using gRPC-FUSE in the edge version and that mostly fixes the performance issues

**Comment by mhenrixon** [comment]
After upgrading to 2.4 the problem seems to be gone. It took a full computer restart after the upgrade to fix the problem though. 

@StefanPrintezis I am pretty sure it had to do with waking up from sleep just like suggested. Anyway, been upgraded to 2.4 for a week now and haven't had this problem anymore.

**Comment by StefanPrintezis** [comment]
Great, another thing I want to mention for future readers. The issue could be related to xDebug
https://github.com/docker/for-mac/issues/3455
