### ISSUE TITLE
macOS Dual Docker Icons

### ISSUE THREAD

**Issue by dmaixner93** [docker/for-mac#4914]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: NA

### Expected behavior
When the Docker application is added to the dock on macOS and clicked to access the dashboard, the same icon opens the dashboard with the macOS indicator.

![docker_single_icons](https://user-images.githubusercontent.com/43049828/93238814-8d162980-f747-11ea-938e-a461b6eb7160.jpg)

### Actual behavior
When the Docker application is added to the dock on macOS and clicked to access the dashboard, nothing happens. To open the dashboard the user needs to navigate to the Docker icon in the title bar to, click the icon to open a dropdown, click 'Dashboard' and the a second Docker icon appears in the dock with the macOS indicator underneath.

![docker_dual_icons](https://user-images.githubusercontent.com/43049828/93238847-9901eb80-f747-11ea-8ba3-fceb7c18c337.jpg)

### Information

  - macOS Version: macOS Catalina Version 10.15.16

### Diagnostic logs

```
Docker for Mac: 2.3.05

```

### Steps to reproduce the behavior

  1. Add Docker application/icon to dock
  2. If Docker is not already running, when the icon is clicked, it will start Docker and the icon in the top title bar will appear.
  3. After Docker is already open, click the Docker icon in the dock again, nothing happens. The assumed behavior is that when the icon in the dock is clicked when Docker is already open, the dashboard window will appear. The dashboard window does not open.

**Comment by stephen-turner** [comment]
Thanks for the report. This is already fixed in the latest Edge versions and will be in the next Stable.

**Comment by dmaixner93** [comment]
No problem. Thanks for the update.
