### ISSUE TITLE
Docker won't open on start up on Mac OS 11.0 (Big Sur)

### ISSUE THREAD

**Issue by artimuas** [docker/for-mac#4917]
[20200915190120.zip](https://github.com/docker/for-mac/files/5231125/20200915190120.zip)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7BD5646B-8779-46C8-85C5-566D5090CC09

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not yet supported on Big Sur.
