### ISSUE TITLE
Can't be used with different users the same time

### ISSUE THREAD

**Issue by Dominik-K** [docker/for-mac#492]
Different Mac users can't use Docker for Mac at the same time, because the symlinks in `/usr/local/bin` link to `/Users/USERNAME/Library/Group Containers/group.com.docker/bin`, which can't be accessed from the other users, respective. 
The linked files are again symlinks to `/Applications/Docker.app/Contents/Resources/bin/`.
- Why don't you link directly to `/Applications/Docker.app/Contents/Resources/bin/`?
- Let the user decide to override or rename the binary symlinks -> #455 

Docker for Mac: version: win-beta-v1.12.0-rc5-beta21-73-g9cd1dc2
OS X: version 10.11.6 (build: 15G31)

**Comment by dave-tucker** [comment]
Thanks for the report @Dominik-K 
We're aware of the issue and it's on the roadmap.

Out of interest, what's the use case for having multiple users actively using Docker for Mac at the same time.

**Comment by Dominik-K** [comment]
Hi Dave, thanks for your answer.
We use a Mac mini as a build machine and use different users for each build tool. Also as a sandbox test environment.

**Comment by ijc25** [comment]
Very similar usecase to #812, although not precisely so not sure about dedupping them.
