### ISSUE TITLE
Docker crashed on macOS big sur start

### ISSUE THREAD

**Issue by dharmapurikar** [docker/for-mac#4920]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Docker Desktop is not supported on Big Sur.
