### ISSUE TITLE
"Kubernetes is starting" indefinitely on macOS

### ISSUE THREAD

**Issue by jmipba** [docker/for-mac#4924]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E91A46B2-54A1-426F-8CFB-55C1EAAD1D90/20200917125421

### Expected behavior
Kuberntes should be in running state.
### Actual behavior
Its hung in "Kubernetes is starting" forever.
### Information
  - macOS Version: Catalina 10.15.6

### Diagnostic logs
E91A46B2-54A1-426F-8CFB-55C1EAAD1D90/20200917125421

### Steps to reproduce the behavior
Always on restart

**Comment by NamanBajaj94** [comment]
Adding additional reported logs : 99057B14-E2DA-4FDC-BE08-F6A7E9721562/20200917144652
