### ISSUE TITLE
Request to reinstate support for dm-crypt (CONFIG_DM_CRYPT=m)!

### ISSUE THREAD

**Issue by andraxin** [docker/for-mac#4927]
As described in  https://github.com/docker/for-mac/issues/4549#issuecomment-637892028, the latest Docker Desktop version with built-in support for `dm-crypt` was 2.2.0.5; AND, while 2.3.0.3 (and later) versions added back generic device-mapper support, support for the `crypt` target remains unavailable.  This makes it close to impossible to work with LUKS-encrypted volumes on MacOS (without workarounds that require a bit of elbow grease, that is).

Here's a copy of a sample session, trying to use a `crypt` target on 2.3.0.3:
```bash
$ docker run --rm -it --privileged alpine
/ # apk add cryptsetup
[...]
/ # dd of=img bs=64k count=0 seek=1k
[...]
/ # cryptsetup -vd /bin/ls luksFormat img
[...]
/ # cryptsetup -vd /bin/ls luksOpen img yay
device-mapper: reload ioctl on    failed: Invalid argument
Command failed with code -1 (wrong or missing parameters).
```
The exact same session works just fine on 2.2.0.5,, but also fails on newer versions like 2.3.0.5.

I compared the kernel configuration between the latter two (2.[23].0.5) and among a number of other more reasonable changes (like removing support for WiFi and KVM), the relevant change is this single line:

```diff
-CONFIG_DM_CRYPT=y
+# CONFIG_DM_CRYPT is not set
```
BTW, if having `dm-crypt` compiled into the kernel is objectionable, I'd be happy to have it as a module; similar to how `CONFIG_DEV_DM` changed from `y` to `m` between these two kernels...

I tried building a module myself, but due to differences in the `RANDSTRUCT_PLUGIN_XXHASHVALUEHEREXXX`, the kernel refuses to load my module.  I _could_, of course, force the same hash in my build, but I cannot reverse SHA256 to get the original seed, which would likely mean that the randomized addresses would be all wrong.  With that prospect in mind, I haven't actually tested that approach.  Instead, I remastered the `docker-desktop.iso` from the latest 2.3.0.5 release, simply replacing the kernel and its modules (i.e. `/boot/kernel` and `/lib/modules`) by the same from the 2.2.0.5 ISO.  This worked without a hitch, but I'd much prefer to have built-in support without having to resort to hackish workarounds.

BTW, the default kernel configuration for `linuxkit` does support `dm-crypt` (and a few other useful device-mapper targets):
https://github.com/linuxkit/linuxkit/blob/master/kernel/config-4.19.x-x86_64#L1937
What was the reason for removing those?

**Comment by stephen-turner** [comment]
We are hoping to get back to upstream linuxkit soon. It's been a bit slower than we would like because the unmodified upstream version is currently crashing in Docker Desktop.

**Comment by andraxin** [comment]
Hmm.... interesting... ;^)

I don't suppose you can meaningfully comment on just how soon is "soon".
It's a work in progress...

I'm wondering if an interim release with `CONFIG_DM_CRYPT` set to
something else than `n` might make sense.  Chances are that just that
change alone won't cause a similar crash.

**Comment by stephen-turner** [comment]
Sorry, we don't have a date yet. We're actively working on it, but we're still trying to debug it.

**Comment by stephen-turner** [comment]
Could you please retest in Docker Desktop 2.5? As of 2.5, we are up to date with upstream LinuxKit, so any missing modules should be requested in the https://github.com/linuxkit/linuxkit repo.

**Comment by andraxin** [comment]
> Could you please retest in Docker Desktop 2.5? As of 2.5, we are up to date with upstream LinuxKit, so any missing modules should be requested in the https://github.com/linuxkit/linuxkit repo.

I can confirm that 2.5.0.1 (49550) works as expected.
Thanks for the heads-up, BTW.
I've been carefully avoiding upgrades with a new kernel,
until furhter notice.  Luckily, I did get this notice. ;^)

**Comment by stephen-turner** [comment]
Great, thanks for testing.
