### ISSUE TITLE
Failing docker start

### ISSUE THREAD

**Issue by radosch** [docker/for-mac#493]
### Information

Diagnostic ID: 8CF721AD-B4C2-4EC6-867F-A9B10B79E91C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)

### Steps to reproduce

1. starting docker
2. failing startup

**Comment by dave-tucker** [comment]
@radosch I'm afraid we can't troubleshoot this further without some more information, so I'm closing for now.
If you are able to add some more information, for example:

- Is this a new install of Docker? 
- Have you installed it before? Was it working?
- Did you just install an update?
- What steps occurred prior to this issue, e.g Open Installer, Drag Icon to Applications etc...

Then we can re-open and look at this again

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
