### ISSUE TITLE
Running now

### ISSUE THREAD

**Issue by appdevcanada** [docker/for-mac#4942]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:6315FBE9-79F7-41A6-AE46-14DDF03FF693/20200925112541

### Expected behavior
It's was not running anymore on macOS new version
### Actual behavior
it's running now after ubdate to beta 8
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Great, thanks for the report.
