### ISSUE TITLE
Docker Desktop CE crashes while starting

### ISSUE THREAD

**Issue by danielpreisinger** [docker/for-mac#4951]
- [X] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop CE starts (full Docker Desktop icon) and is ready to run containers based on it. 

### Actual behavior
After starting Docker Desktop it takes a while until a window opens with the following fatal error message:
_2020-09-29T08:35:03Z dockerd time="2020-09-29T08:35:03.994584848Z" level=debug msg="Client context cancelled, stop sending events"_

Uploading diagnosing report is not possible because it loads indefinitely. A stable internet connection is given. I've already removed Docker Desktop CE completely and reinstalled. Just an older version from 2020-04-02 works. After starting Docker Desktop CE there is a short frametime where continuing preferences is possible for cleaning / purging data, resetting to factory defaults and uninstalling. No one of this options could help.

A docker command prompting on CLI results in following message:
_Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?_

### Information

```
- macOS Version: 10.15.7 (19H2)
- Docker for Mac: 2.3.0.5 (48029)
- Channel: Stable 
- Engine: 19.03.12
- Last version which starts successfully: 2.2.0.5
```

### Steps to reproduce the behavior

This is unfortunately not really reproducible. Perhaps there are some users being aware of this issue.

Many thanks for helping!

**Comment by SeanFacer** [comment]
- macOS Version: 10.15.6 
- Docker for Mac: 2.4.0.0

Keeps crashing my mac

**Comment by danielpreisinger** [comment]
Docker Desktop CE 2.4.0.0 works for me now.
