### ISSUE TITLE
[EDGE 2.3.7.0] grpc sharing results in infinitely hanging processes

### ISSUE THREAD

**Issue by scarby** [docker/for-mac#4953]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2975C6F5-185D-4CCC-B094-A22DDB3BA24F/20200929221942

### Expected behavior
After enabling gRPC file sharing host file sharing should continue to work as expected

### Actual behavior
After enabling gRPC for host file sharing containers have issues accessing volume mounts that exist within these paths and hang indefinitely on file system operations for example:

```
kubectl exec -it npm-xfvm5 -- /bin/bash
root@npm-xfvm5:/var/www/sites/dev# ls
```
container will sit here indefinitely ls will never return or listen to keyboard interrupts:

### Information
  This happened after moving to 2.3.7.0 from latest stable version

this is defined as a local volume in k8s but from a docker perspective the mount is:
 In this case the volume is defined as a local volume in k8s - but from a docker perspective the mount is:
```
            {
                "Type": "bind",
                "Source": "/Users/adamscarborough/Projects/tradesy/core/tradesy",
                "Destination": "/var/www/sites/dev/tradesy",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```

### Diagnostic logs
Diagnostics ID: 2975C6F5-185D-4CCC-B094-A22DDB3BA24F/20200929221942
```
Docker for Mac: 2.3.7.0
Diagnose succeeded
```

### Steps to reproduce the behavior
no files here right now - but any container mounting anything in a shared directory seems to be problematic

**Comment by stephen-turner** [comment]
Thanks for the report, @scarby.
@djs55 PTAL.

**Comment by djs55** [comment]
@scarby looking through your logs I see a few suspicious errors like this:
```
time="2020-09-29T15:13:11-07:00" level=error msg="GetAttrFileDescriptor 497: file descriptor not found"
```
There was a possibly-related bug fix in the 2.4.0.0 stable version released today. Could you try again with this new version (assuming you haven't already tried it)? There will also be an edge update very soon (within days), if you'd like to stay on edge. There are also some new diagnostics in these later builds which could be relevant if it manifests again.

In the meantime, I'd love to know how to reproduce this -- any repro steps or hints would be appreciated.

Also note that you can switch back to the previous implementation (`osxfs`) via the whale menu -> Preferences ... -> General -> uncheck "Use gRPC FUSE for file sharing" if you need to. This is non-destructive and you can switch back and forth without recreating images or containers.

Thanks for the report!

**Comment by scarby** [comment]
@djs55 thanks :) I've already disabled gRPC fuse

I can probably wait a few days, I'm hoping that some of the changes in edge will (when it works) will alleviate some CPU usage issues i'm having. I'll happily update after that happens.

i can put together a small kubernetes manifest which should have the same issue. However for me it's manifesting everywhere i attempt to use a k8s persistent volume to allow a container access to my local filesystem.

**Comment by doublesharp** [comment]
I'm using Docker 2.4.0.0 for Mac and after upgrading was unable to start my containers without disabling gRPC FUSE.

**Comment by stephen-turner** [comment]
@doublesharp Please reproduce the problem and upload diagnostics: we can't investigate without that. Thanks.

**Comment by doublesharp** [comment]
I did generate a diagnostic report when I was having the issue that lead me
to this post, and can try again in the morning, however I'm currently in
the middle of development and can't risk breaking my environment too much.
If I just have the zip file, where is an appropriate place to upload it?

If it's helpful I'm using `docker-compose` along with `docker-sync` +
`unison` for volumes. Latest version of OSX and Docker, and allocated 12
cores, 32gb of memory. Starting both the docker sync and my containers were
extremely slow with timeouts resulting networking issues. Disabling gRPC
fuse immediately fixed the timeouts.

**Comment by stephen-turner** [comment]
When you generate the diagnostics file, there's a button to upload it, then you just need to paste the uuid here.

**Comment by doublesharp** [comment]
I stopped all my containers, re-enabled gRPC FUSE and everything seemed to start up quickly. I then stopped them and tried to restart and things got very very slow again to the point where some containers timeout trying to start.

```
Creating project_app2_db_1  ... done
Creating project_redis_1        ... 
Creating project_elasticsearch_1 ... 
Creating project_app1_db_1    ... 

ERROR: for project_elasticsearch_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for project_app1_db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for project_redis_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for elasticsearch  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for app1_db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

They do continue to start.... very very slowly, but not in a way that makes Docker usable so increasing the timeout isn't really a fix.

Generated a diagnostics report: BC78371B-1E61-4C93-BCA0-19EE523C501F/20201001171047

**Comment by stephen-turner** [comment]
Interesting, one other person reported this error at #4957.

**Comment by stephen-turner** [comment]
I think it's different from the original bug on this ticket though.

**Comment by doublesharp** [comment]
@stephen-turner It's possible, but I'm not sure. When i was able to get a container to start I was seeing similar issues with disk access - trying to `ls` a directory would just hang for several minutes, though it would eventually return. Generally though I had issues with actually starting the containers, but I assumed it was also because of disk access.

**Comment by scarby** [comment]
i still have the same issue after upgrading to 2.4.1.

**Comment by houmam** [comment]
We have been experiencing similar issues using the MySQL 5.6 image after we upgraded to 2.4.0.0, disabling gRPC FUSE fixed the issue.

It feels like when we run with gRPC enabled it fails to get access to some files.

```2020-10-01 23:22:56 7f2e8ffff700  InnoDB: Assertion failure in thread 139837961139968 in file dict0dict.cc line 3479
InnoDB: Failing assertion: for_table || ref_table
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
23:22:56 UTC - mysqld got signal 6 ;```

I have ran diagnostics while attempting to start the it several times. It fails every time with gRPC enabled so I hope this will actually provide something of use.

Diagnostics ID: 4B36A61E-E9C9-4190-BEAD-01A586E06CED/20201001231745

Let me know if you need anything else from me to help track down the issue.

**Comment by djs55** [comment]
@houmam thanks for your report. Could you share a `docker-compose.yml` (or similar) with the `innodb` configuration you're using?

**Comment by houmam** [comment]
@djs55 Just launching it via docker using defaults (used for local development)

```docker run --rm --name keycloak-mysql -v $HOME/.keycloak-db-data:/var/lib/mysql -e MYSQL_DATABASE=keycloak -e MYSQL_USER=keycloak -e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=root_password -p 3307:3306 mysql:5.6```

**Comment by ebriney** [comment]
Thanks to your reports, we found some edge cases / frameworks specific behavior, we fixed them, can you test this build and give us your feedback:
https://desktop-stage.docker.com/mac/edge/49014/Docker.dmg

cc @doublesharp @houmam @scarby

**Comment by houmam** [comment]
@ebriney Just installed the version provided and unfortunately I am in the same situation, disabling gRPC Fuse allows it to run correctly while enabling it gives the same error I provided above. Thank you for looking into it, let me know if there is anything else you need me to test. I am happy to run through whatever you need.

**Comment by ebriney** [comment]
We fixed more issues related to gRPC Fuse, can you try that build and give us some feedback please:
https://desktop-stage.docker.com/mac/edge/49130/Docker.dmg

We noticed a performance issue when creating files from a container and we start to work on optimize it.
Thanks for your help.

cc @doublesharp @houmam @scarby

**Comment by doublesharp** [comment]
@ebriney so far so good - containers will start without timing out and performance is pretty good, though still behind linux. Are there any particular tests you would like me to run? Submit another diagnostic? Thanks for continuing to look into this.
