### ISSUE TITLE
Problem setting Docker Daemon port

### ISSUE THREAD

**Issue by caddisfly** [docker/for-mac#496]
### Expected behavior
I am trying to setup the docker daemon to listen on localhost:2375 so that I can use the Gradle Docker plugin to build images.  I found this issue on Stackoverflow:  http://stackoverflow.com/questions/39262343/make-docker-for-mac-listen-on-a-tcp-port

and followed the instructions there to set the "hosts" in the daemon.json.
### Actual behavior

As noted by the original poster of that Stackoverflow thread, setting any combination of values in "hosts" causes Docker not to start.  For example: 

{"storage-driver":"aufs","debug":true, "hosts" : [ "unix:///var/run/docker.socket" ]}

### Information

 Version 1.12.1-beta24 (build: 11525)
0afa5e569ec61f2b8d303e1a722c7e0b0c58d496

Also tried with 1.20.0 GA.

MacOs 10.11.6

### Steps to reproduce the behavior

  1. Follow the steps in http://stackoverflow.com/questions/39262343/make-docker-for-mac-listen-on-a-tcp-port to create the etc/docker/daemon.json file if it doesn't ext.
  2. attempt to set the list hosts,  specifically I am trying to achieve the equivalent of DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"

**Comment by dave-tucker** [comment]
Following those steps is not a good idea as it will (probably) break Docker for Mac.

You may find some better advice [here](https://docs.docker.com/docker-for-mac/troubleshoot/#/known-issues) specifically re: setting the `DOCKER_HOST` variable to point to the Unix socket for Maven. This may work for Gradle too.

There is also another workaround [here](https://forums.docker.com/t/using-pycharm-docker-plugin-with-docker-beta/8617/10) but it is much less secure - I wouldn't recommend it.

**Comment by dave-tucker** [comment]
As a workaround exists, I'm closing this issue for now.

**Comment by caddisfly** [comment]
I actually don't want to use the unix socket, I want to use tcp://127.0.0.1:2375.  I was just demonstrating that putting *anything* in "hosts" breaks Docker.
