### ISSUE TITLE
hyperkit is consuming 50% cpu

### ISSUE THREAD

**Issue by RajAdittan** [docker/for-mac#4961]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 477F1460-32CC-45ED-B72E-29340AD7D52C/20201002011127

### Information
Install stable version of Docker desktop version, com.docker.hyperkit consumes 50% cpu with no load.

  - macOS Version: catalina

### Diagnostic logs
477F1460-32CC-45ED-B72E-29340AD7D52C/20201002011127

### Steps to reproduce the behavior
  1. Install docker desktop
  2. cpu used by hyperkit is minimum 50%

**Comment by stephen-turner** [comment]
Thanks for the report, @RajAdittan, we'll have a look.

**Comment by ebriney** [comment]
Hello @RajAdittan.
I dug a bit in your diagnostics and it's seems there is a possible issue with the number of cores you setup in your vm. Generally it's not recommended to allocate all your CPUs for the vm, can you put half of them (4) and check you still get the issue?
Another question, did you activate kubernetes before? I saw some dangling kubernetes processes in the vm, I don't know where they come from.

**Comment by RajAdittan** [comment]
rajamohanadittan@optimuspro ~ % docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.848GiB
 Name: docker-desktop
 ID: BB4D:2YN2:S5CG:JOSZ:MJ3D:2UUQ:YAY7:274Y:6G2M:3SBI:5F6R:RDGL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

Now I changed to use 2 cores, 8gb mem. The cpu usage is increased from ~4% to ~40%, any reason? Mia clap?

**Comment by RajAdittan** [comment]
Appologies 4gb memory.

**Comment by RajAdittan** [comment]
Today I have deleted kind cluster delete --name=velvet, Setup Minikube using driver=parallels, now cpu % for hyperkit in back to 4%. Is there a way to MOD desktop for Mac to use paralells (paid) driver instead of hyperkit (free).

Though my motivation is not to blame rater spin 2 kind clusters and check pod resiliency across clusters.

**Comment by ebriney** [comment]
Unfortunately, you cannot use Docker Desktop with parallels as hypervisor.
You will have to setup your own linux in a parallel vm and install dockerd and kube (or use minikube images can perhaps work)

**Comment by ebriney** [comment]
I close the issue because it's not really a problem normal usage can exhibit.
But feel free to continue the conversation on the ticket.
