### ISSUE TITLE
HTTP requests can't reach out dockerized web-application

### ISSUE THREAD

**Issue by ant-** [docker/for-mac#4965]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D547D289-E184-409F-B31A-B28EED50F7E6/20201002124149

### Expected behavior
200 status response

### Actual behavior
A request hangs forever

### Information
The problem is that HTTP request to any dockerized application hangs. 

It is reproducible on the following Docker versions Edge versions: 2.3.4, 2.4.1; the latest Stable version 2.4.0.
I was using 2.3.4 version because it contains [a fix for CPU load problem](https://github.com/docker/for-mac/issues/3539#issuecomment-666258889). 

I noticed this problem on Oct 1 2020, before that I hadn't worked with Docker like for 2 weeks. As I can see in System Report → Installations, the latest update was installed on Oct 16, 17:41. So, maybe that OS update causes a bug to Docker.

My colleague using Docker `18.06.1-ce-mac73` on MacOS `10.15.7`, and he doesn't have this problem. 
I've downloaded the same version and it works well for me, as `2.0.0.0-mac81` does.

  - macOS Version: 10.15.7

### Diagnostic logs

```
Docker for Mac: 2.4.1 Edge

```

### Steps to reproduce the behavior

1. Open the Terminal app and run `docker run -d -p 80:80 docker/getting-started`
2. Make sure the container is up and running `docker container ps`
3. Open a web-browser and go to http://localhost

**Comment by ant-** [comment]
Asked my colleague to try to reproduce the bug and he couldn't. He has the same MB Pro, the same OS version and Docker.

**Comment by wilansp** [comment]
I was able to resolve the issue by downgrading docker to for mac to version 2.3.0.5.
