### ISSUE TITLE
Docker desktop for mac the kubernetes show version kubectl get nodes version different

### ISSUE THREAD

**Issue by zouchengli** [docker/for-mac#4967]
![image](https://user-images.githubusercontent.com/27568522/94984961-7dd70e80-0584-11eb-9d08-88ceae9b614c.png)
![image](https://user-images.githubusercontent.com/27568522/94984972-90e9de80-0584-11eb-8e21-2d6a1201b5bd.png)

**Comment by conradwt** [comment]
I'm also experiencing the same issue in Docker For Mac v20.10.0-beta1.  For example, 

```
➜ kubectl version  
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl get nodes
NAME             STATUS   ROLES    AGE     VERSION
docker-desktop   Ready    <none>   9m20s   v1.18.3
```

**Comment by bodom0015** [comment]
Same exact thing here as OP, and I've tried everything I can think of to fix it. I was on `Docker Desktop (for Mac) 2.4.0.0`, whose Settings page claimed I was using `Kubernetes v1.18.8`, but `kubectl get nodes` reports a much older version:
```
MacBook-Pro:loadtest$ kubectl get nodes
NAME             STATUS   ROLES    AGE     VERSION
docker-desktop   Ready    master   3m53s   v1.16.6-beta.0
```
I tried performing a "Reset Cluster", as well as Disabling and then Re-enabling Kubernetes, but the version mismatch persisted even when the node's `AGE` was reset.

I just now disabled Kubernetes, then updated `Docker Desktop (for Mac) 2.5.0.0` and re-enabled Kubernetes. Despite these efforts, I am unfortunately still seeing the same behavior as before - the settings page now claims `v1.19.3`, but my `get nodes` output still has the same `1.16.6-beta.0`.

**Comment by scott2449** [comment]
This is the same in all versions. The API server and other components are indeed 1.18 or 1.19. Run kubectl version to see this. I am not sure if the kubelet is really 1.16 or if it's some docker for desktop hacks. You can inspect the VM itself via 

docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh

Haven't had the time to investigate futher
