### ISSUE TITLE
Kubernetes remain in "Starting..."

### ISSUE THREAD

**Issue by holden-ar** [docker/for-mac#4968]
Kubernetes remain in "Starting..." I was not able to find a way to fix it.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:936723C7-7FD2-475C-A673-2DA4ABB334CE/20201003144918
  - macOS Version: Catalina 10.15.6
   - Docker for Mac: Version:          19.03.13

**Comment by ttony** [comment]
I had the same problem too

**Comment by inomire** [comment]
Try follow this! It worked both Catalina & Mojave.
1. remove .kube directory
ex) rm -rf ~/.kube
2. _"Reset to factory defaults"_ at the troubleshoot tab
3. enable kubernetes and wait

**Comment by holden-ar** [comment]
Works for me. Thanks
