### ISSUE TITLE
docker machines become inaccessible but still show as running 

### ISSUE THREAD

**Issue by wilansp** [docker/for-mac#4970]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 74FA5C1B-68B7-4A70-8B57-70DA154ACDCF/20201004210750

### Expected behavior
Docker machine to remain accessible
### Actual behavior
Lose connectivity to docker machines. Unable to even stop them through command line. Have to restart the docker application to reboot them

### Information

  - macOS Version:
Catalina 10.15.7

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wilansp** [comment]
not sure if this is related to the latest update but docker machines will become inaccessible. I can't even run a docker-compose to bring them down or up. I have to stop the docker app all together. after doing so the machines will ruin for a short while but then I can't access them. one of my machines is a Plex server. if will show in Plex as the server is down. However, docker says its running. I've tried to clean things up using system and volume prune but same results. I’m lost at this point.

**Comment by ant-** [comment]
Maybe there is a chance that we've faced with the same problem. But [in my case](https://github.com/docker/for-mac/issues/4965) the HTTP requests can't reach a dockerized web-app.

**Comment by alex-zaets** [comment]
Hi all! 
I'm seeing kinda same behaviour as @ant- did. Pinging from within container is not working, but pinging from mac(host where docker is running) works fine. I've noticed weird correlation: container works fine until docker is seeking of update. Right after updating docker for mac, everything works fine.
My config: macOS 10.15.7 (19H114). Regarding docker for mac: now I'm on latest 3.0.4(51218), so I can't tell if latest is affected too(Is there any way to get update history to find previous vulnerable version?).
Looks like for some reason networking is turning off when there is an update coming for docker for mac.
<img width="257" alt="Screen Shot 2021-01-12 at 10 30 32 AM" src="https://user-images.githubusercontent.com/5457515/104476543-34c82a80-5575-11eb-9d6a-d97866ec6344.png">
