### ISSUE TITLE
Container unexpectedly terminates

### ISSUE THREAD

**Issue by jbzargo** [docker/for-mac#4983]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: ADAE3051-7584-4C4A-A018-0C30FFAF81D5/20201009060447

### Expected behavior
The started container remains started and accessible.

### Actual behavior

The container starts, but after a period of time unexpectedly stops working and when another CLI command to the container has been issued using shell scripts the following error is displayed:

Error response from daemon: Container <container id> is not running

### Information

  - macOS Version:
        High Sierra 10.13.6 

The build environment for creating and running containers was previously woking correctly prior to applying the update to 2.4.0.0.

This has been tested on another Mac running a newer version of OSX and this has the same issue.

Docker for Mac: version 2.4.0.0 (48506) Channel stable
Engine: 19.03.12

### Steps to reproduce the behavior

  1. Fresh install of OSX.
  2. Fresh install of docker desktop 2.3.0.5 (48029) stable.
  3. Upgrade docker desktop 2.4.0.0 (48506) stable.
  4. Build oracle XE - 18.4.0 DB- https://github.com/oracle/docker-images.
  5. Run container instance with container based volume mapping oracle data and custom startup scripts.
  6. Access the container using docker CLI.

**Comment by stephen-turner** [comment]
Thanks @jbzargo, we'll have a look

**Comment by ebriney** [comment]
Hi @jbzargo, can you check it's still working when switching back to osxfs? (You can change it in the settings UI)

**Comment by 1bharat** [comment]
@ebriney Thank you so much. That was it. It was driving me crazy as containers were taking forever to start, and then randomly crash. Changing to osxfs fixed everything.

**Comment by stephen-turner** [comment]
@jbzargo @1bharat Would you be able to try the build @djs55 posted at https://github.com/docker/for-mac/issues/4964#issuecomment-707233442 and see if that fixes it?

**Comment by 1bharat** [comment]
@stephen-turner I will test the new build today

**Comment by ebriney** [comment]
Thanks to your reports, we found some edge cases / frameworks specific behavior, we fixed them, can you test this build and give us your feedback:
https://desktop-stage.docker.com/mac/edge/49014/Docker.dmg

cc @1bharat @jbzargo
