### ISSUE TITLE
Docker for Mac 2.4.0.0 does not properly create volumes directories that are non-exist on the host

### ISSUE THREAD

**Issue by fibulwinter** [docker/for-mac#4991]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ED704F2D-57FD-4199-A23D-ECE4CF7A6B75/20201012045539

### Expected behavior
According to documentation:

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.

So if I run

```
mkdir /tmp/exist/
docker run -d --volume /tmp/exist/non-exist/:/tmp/exist/non-exist/ ubuntu tail -F /var/log/kern.log
```

I expect that /tmp/exist/non-exist/ will be created on MacOS host

### Actual behavior

`ls /tmp/exist/non-exist 
ls: /tmp/exist/non-exist: No such file or directory`

### Information
It can be easily reproduced by steps above. It started to happen with recent update to Docker Engine 19.03.13 (19.03.12 was fine).

  - macOS Version: Catalina 10.15.7

### Steps to reproduce the behavior

  1. `mkdir /tmp/exist/`
  2. `docker run -d --volume /tmp/exist/non-exist/:/tmp/exist/non-exist/ ubuntu tail -F /var/log/kern.log`
  3. `ls /tmp/exist/non-exist`

**Comment by stephen-turner** [comment]
@djs55 PTAL

**Comment by djs55** [comment]
@fibulwinter thanks for the report and the repro instructions. I confirm that it reproduces for me locally.

**Comment by djs55** [comment]
I think this bug may be specific to `/tmp`:
```
$ rmdir ~/workspace/non-exist/
$ docker run -d --volume /Users/djs/workspace/non-exist/:/tmp/exist/non-exist/ ubuntu tail -F /var/log/kern.log
15fcea7914f8f10b4b13091ffe6ceef96890363d7fb3d41fc5af00cfc9765820
$ ls ~/workspace/non-exist/
```
`/tmp` is a symlink on Mac to `/private/tmp`. This appears to work around the issue for me:
```
$ rmdir /tmp/non-exist/
$ docker run -d --volume /private/tmp/non-exist/:/tmp/exist/non-exist/ ubuntu tail -F /var/log/kern.log
ec7ecefcaa92eefc343bd5bf9cefeefe7c51ba43fd9197bb307b81ba2ef7c841
$ ls /tmp/non-exist/
```

**Comment by icechen1** [comment]
Anecdotally, turning off gGRPC FUSE and switching back to osxfs in the Docker settings also fixes this issue for me.
