### ISSUE TITLE
2.4.0.0 deprecate supporting OSX 10.13

### ISSUE THREAD

**Issue by yangliuyu** [docker/for-mac#4993]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker desktop for mac keep supporting OSX 10.13

### Actual behavior
Docker desktop for mac deprecate supporting OSX 10.13 in 2.4.0.0

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version 

```

### Steps to reproduce the behavior

  Since a lot of people use OSX 10.13 with Nvidia Graphic Card 1000 series(10.14 do not support Nvidia new cards), please consider keep supporting 10.13 version.

**Comment by stephen-turner** [comment]
Sorry, our stated policy has always been to support only the last three versions. So in preparation for Big Sur, we have deprecated High Sierra, and will remove support for it after Big Sur is released. Our own telemetry shows that most Mac users upgrade to the latest version very quickly, more than Windows users do.
