### ISSUE TITLE
High CPU/Energy Impact (com.docker.hyperkit)

### ISSUE THREAD

**Issue by infolock** [docker/for-mac#4994]
- [x] I have tried with the latest version of my channel (Stable or Edge) - I use Stable
  - [x] I have uploaded Diagnostics
  - **Diagnostics ID**: `0E651E62-C764-4DAD-AB90-9DACF230E3B1/20201015161640`

### Expected behavior
- CPU usage at a reasonable %
- Energy Impact at a reasonable level

### Actual behavior
- CPU fluctuates anywhere in the range of `80%` CPU (acceptable), to `200%` CPU (which is where it typically is) and up to `600%` CPU (this becomes disastrous when it happens)
- Energy Impact is always in the range of `200` - `500`. The next highest energy impact app is around `13`.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes.
  - Is the problem new? no.  happened for a few years now
  - Did the problem appear with an update?  dunno.   i have noticed this since 2018 tho.

  - **macOS Version:** `10.14.6`

### Diagnostic logs
**Docker for Mac:** version...`v19.03.13`

### Steps to reproduce the behavior
  1. Install Docker
  2. Install Kubernetes
  3. Add containers.
  4. Wait & Watch Activity Monitor

**Comment by stephen-turner** [comment]
Thanks for the report @infolock. A couple of initial questions to narrow it down:

1. Do you get high CPU when no containers are running, or only when there are containers running? And if the latter, are you confident that it's not just the CPU load of all the container workloads that you're running?
2. Are there also problems when Kubernetes is not running, or is it a Kubernetes thing?

Thanks.

**Comment by folke** [comment]
Not op, but I'm seeing the same issue on 11.0 Beta (20A5395g).

No containers running, and kubernetes is not running.

On my laptop, `com.hyperkit.docker` always uses around **11% CPU**.

Diagnistics ID: 77B501E3-6B38-4490-83A3-4D6E2109C8B7/20201017074749

**Comment by stephen-turner** [comment]
Thanks for the report. I suspect those will turn out to be different issues if one is using 11% CPU and one is using 200%. But we'll have a look at the diagnostics.

**Comment by ebriney** [comment]
@infolock either switch back to osxfs in the settings or use the latest edge version must fixed this problem.

@folke from the diagnostics it's 2.4% which is kind of standard to run a vm (your browser consumes 3 times more CPU for ex.):
```
folke             1673   2.4  2.8  6634796 235340   ??  S     9:32PM  10:04.54 com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 3 -m 2048M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=vpnkit.eth.sock,uuid=fac2dcb1-5e44-485d-8cca-f997de3e8a85 -U cbf44340-f095-4e81-a27d-5268e4f4bc1b -s 2:0,virtio-blk,/Users/folke/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw -s 3,virtio-sock,guest_cid=3,path=vms/0,guest_forwards=2376;1525 -s 4,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker-desktop.iso -s 5,ahci-cd,vms/0/config.iso -s 6,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker.iso -s 7,virtio-rnd -l com1,null,asl,log=vms/0/console-ring -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,
```

**Comment by infolock** [comment]
Sorry for the delayed response here.

1. yes, the containers are always running.
2. I don't know if its a kubernetes thing or not.   i assume it could be given its an additional service sitting on top of docker - but there really is no clear way of distinguishing the two.   we would remove kubernetes but our services will fail due to that dependency needing to be met.  so - rock and hard place here...

Our org explicitly doesn't use `edge` as there are services we build that are affected by this (they follow closely with the release cycles from my understanding - which unfortunately is very minimal into the whys of this decision.   i also understand this isn't very helpful =\).

**Comment by infolock** [comment]
example though of what i mean:

![docker-cpu](https://user-images.githubusercontent.com/808850/97629831-0ec6cb80-1a05-11eb-8ca1-aa4f33656b4b.png)

Here is what I have found out though that triggers this:
* a good _trigger_ is when you deploy a new container (this reaches well beyond 500% - but of course it only lasts for a the time it takes to create the containers)
* this becomes **problematic** though after a few cycles of deleing a container and then recreating it.   at one point, the container's creation gets caught in some sort of cycle that prevents it from being removed using basic commands and we instead have to result in using [helm](https://www.npmjs.com/package/node-helm) to issue a `helm delete app-name-here --namespace our-namespace-here` in order to get the left-over containers completely deleted.   When they are orphaned, it goes into a fritz of high CPU/Memory.  This appears to be because it is constantly trying to recycle and remove the pods in the container but fails to do a complete clean of it (so it recycles and tries to reload the pods, but fails to do so, and then constantly loops trying to resurface the pods)

i hope this helps
