### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by bazurbat** [docker/for-mac#5]
### Expected behavior

Running commands without errors
### Actual behavior

I'm testing build service inside docker container and sometimes getting messages like:

```
tail: /home/dev/root-linux/build/build.log: Transport endpoint is not connected
tail: '/home/dev/root-linux/build/build.log' has become inaccessible: Transport endpoint is not connected
dev@8e9f8a301878:~/root-linux$
dev@8e9f8a301878:~/root-linux$ Error response from daemon: dial unix /Users/bzt/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

after which container quits. It happens sporadically, more likely for long running commands.

The `/home/dev` is a volume mounted from host.
### Information

Diagnostic ID: BAB087EC-07AD-4E71-8D1B-2FE0299DB55F
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce

Have not found reliable steps to reproduce yet.

**Comment by avsm** [comment]
Possibly related to #18

**Comment by robhoes** [comment]
I also experience this, several times a day. Especially when compiling something large, such as http://github.com/xapi-project/xen-api. At some point I get lots of I/O errors and the container exists. Lots of lines like this one:
```
Error: I/O error: xapi_network.mli: Transport endpoint is not connected
```

**Comment by dsheets** [comment]
The original issue is caused by a `transfused` process crash with `EFAULT` which is still being tracked down. The issue is not related to #18. There are a number of causes for this error all involving a crash of the VM-side file server daemon.

@robhoes could you please post your diagnostic ID and *at least click* the `Open Issues` button in the `Diagnose & Feedback` window in order to upload your diagnostic bundle. Also, could you please post an example reproduction if you have found a reliable way to provoke the behavior?

**Comment by robhoes** [comment]
@dsheets My ID is `E959BC9D-1CC3-4D3D-8331-E1E2818691C0`. I had clicked that button this morning, but did not submit a new github issue when I saw this one.

**Comment by robhoes** [comment]
I do not have a reliable way of reproducing it yet.

**Comment by robhoes** [comment]
By the way, I'm on Version 1.12.0-beta21 (build: 11019) now, but have seen this issue on many of the previous betas as well, though not on the early ones (can't tell you when exactly it started I'm afraid :( ).

**Comment by djs55** [comment]
@robhoes thanks for your patience -- this is still on the radar. Even if you don't have a 100% reliable way to reproduce it, do you have anything simple (a xapi build perhaps?) that often triggers it? It could be useful even if we have to run it in a loop.

**Comment by robhoes** [comment]
@djs55 Yes, a full xapi build in xenserver-build-env often triggers this. It happened again just now, on the latest beta (beta24).

**Comment by robinvalk** [comment]
I'm also having the same issue. After Nzbget is done unpacking the container starts spamming these `Transport endpoint is not connected` errors and eventually crashes.
Nzbget is creating, deleting and moving loads of files at that time.

Other containers connected to the same mount crash aswell.

**Comment by ms1111** [comment]
I saw this twice last night, once while writing a lot of data to ElasticSearch and again while writing to mongodb. mongodb failed with:
```
2016-09-15T05:54:51.833+0000 E STORAGE  [thread1] WiredTiger (107) [1473918891:829013][1:0x7f72e312d700], log-server: /data/db/journal: directory-list: opendir: Transport endpoint is not connected
```
And in system.log:

```
Sep 15 01:54:51 Michaels-MacBook-Pro Docker[47648]: VM: 2016-09-15 05:54:51 +0000 UTC daemon.crit /sbin/transfused: /Users: error writing:
Sep 15 01:54:51 Michaels-MacBook-Pro Docker[47648]: VM: 2016-09-15 05:54:51 +0000 UTC daemon.crit /sbin/transfused: Bad address
Sep 15 01:54:51 Michaels-MacBook-Pro Docker[47645]: Fatal unexpected exception: Socket.Closed
Sep 15 01:54:51 Michaels-MacBook-Pro Docker[41959]: Reap com.docker.osxfs (pid 47645): exit status 1
Sep 15 01:54:52 Michaels-MacBook-Pro Docker[41959]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 47648)
Sep 15 01:54:52 Michaels-MacBook-Pro Docker[41959]: Signal terminated to com.docker.driver.amd64-linux (pid 47648)
Sep 15 01:54:52 Michaels-MacBook-Pro Docker[47648]: sending SIGTERM to com.docker.hyperkit pid 47685
Sep 15 01:54:52 Michaels-MacBook-Pro Docker[47648]: VM: 2016-09-15 05:54:52 +0000 UTC daemon.error acpid: PWRF/00000080
Sep 15 01:54:53 Michaels-MacBook-Pro Docker[47648]: VM: 2016-09-15 05:54:53 +0000 UTC daemon.info init: starting pid 8280, tty '': '/sbin/openrc shutdown'
Sep 15 01:54:53 Michaels-MacBook-Pro taskgated[1016]: no application identifier provided, can't use provisioning profiles [pid=49146]
Sep 15 01:54:53 Michaels-MacBook-Pro taskgated[1016]: no application identifier provided, can't use provisioning profiles [pid=49147]
Sep 15 01:54:53 Michaels-MacBook-Pro Docker[47647]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Sep 15 01:54:54 --- last message repeated 1 time ---

```

Diagnostic ID: 1CB21870-BAAC-4D64-8ABE-AB0ECB98A3E5
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by neophob** [comment]
Same error here, try to compile a linux kernel, diagnostic id: 061AD9FE-66AC-4C23-AE81-E4357A76091D.

Note: I created an additional disk volume (case sensitive) and mounted this volume inside the docker container (-v)

**Comment by jctemkin** [comment]
Same error here while building OpenXT. Diagnostic id: 11A5A876-BFBD-4AC5-84A2-CA196BD347F3.

For what it's worth, it looks like some folks on the forums are encountering a similar issue [here](https://forums.docker.com/t/crash-when-running-container-with-host-mount/12982/23).

**Comment by raszi** [comment]
Experiencing the same issue with [`postgres:latest`](https://hub.docker.com/r/_/postgres/) quiet often.

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/5AAC807B-5101-4540-B057-C1FBD773E8D7/20161110-155050.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by IgorGanapolsky** [comment]
I am getting the same error with a Gradle build on Docker.  Errors like:
> error opening 'CMakeFiles/andros.dir/src/main/jni/MyDiscovery/my_sendpacket.cpp.o.d': Transport endpoint is not connected

**Comment by fuji246** [comment]
Having the same error, i'm using 

```
Version 1.12.3-beta30.1 (13946)
Channel: Beta
f94d037b71
```

Change CPU count from 2 to 1 fix the error

**Comment by freman** [comment]
Tried changing cpu count, it didn't help us, I've even split the project up into multiple containers and running it inside compose, one crashes they all seem to crash

**Comment by snodnipper** [comment]
I seem to be able to produce this error fairly easily whilst building Mapbox GL.  Executing the following:

```console
 git clone git@github.com:mapbox/mapbox-gl-native.git
 cd mapbox-gl-native
 ./docker/build.sh
 ./docker/linux/run.sh
```

Produces output like:

```console
../../../mason_packages/headers/boost/1.62.0/include/boost/geometry/algorithms/detail/is_simple/implementation.hpp:15:65: fatal error: ../../../include/boost/geometry/algorithms/detail/is_simple/linear.hpp: Transport endpoint is not connected
compilation terminated.
ninja: build stopped: subcommand failed.
make: *** [glfw-app] Error 1
build/docker/linux/test.sh: error reading input file: Transport endpoint is not connected
```

I can build it by getting into the container and compiling from where it blows up.
e.g. ```docker run -i  -v `pwd`:/home/mapbox/build -t mapbox/gl-native:linux``` and repeating the make process.

**Comment by samoht** [comment]
I am running your reproduction case while the latest beta (40) and (after a while) I get:

```
/home/mapbox/build/mason_packages/linux-x86_64/mesa/13.0.3/lib/libGL.so: undefined reference to `xcb_dri2_wait_sbc_unchecked'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [test] Error 1
```

but the daemon is still running. I cannot see anything wrong in my logs. Could you try to see if you can reproduce with a recent version of Docker for Mac (either the stable or beta channel should be fine). Thanks!

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
