### ISSUE TITLE
Docker Desktop Preferences from CLI

### ISSUE THREAD

**Issue by brcarp** [docker/for-mac#5002]
Is it possible to query the Docker Desktop preferences from the command-line, or is there a `.plist` that can be queried, etc.?

For example, I want to be able to display in a console the total disk usage as it appears under **_Preferences_** > **_Resources_** > **_Advanced_**.

I can determine the "used" portion by executing `du` on the "Disk image location" as identified in that tab. Given the total disk image size it's easy enough to calculate the percentage used, and then record or visualize that elsewhere, but I cannot figure out if there is a way to look up the total disk allocation from the command line. Is there a way to this, besides opening up the application Preferences and recoding it manually? I'd like to create an automated tool to do this that I can share with others who may have a different disk allocation in their application preferences.

**Comment by stephen-turner** [comment]
No, sorry, there is no command line support. There is a settings.json file you could parse, but that's all.

@nebuk89 I thought we had an item for this on docker/roadmap, but I can't find it?

**Comment by brcarp** [comment]
> No, sorry, there is no command line support. There is a settings.json file you could parse, but that's all.

🎉   `diskSizeMiB` in `settings.json` looks right to me. Thanks, @stephen-turner! That's good enough for now

**Comment by stephen-turner** [comment]
Great, thanks, I'll close the ticket.
