### ISSUE TITLE
Docker High CPU usage

### ISSUE THREAD

**Issue by WimCools** [docker/for-mac#5004]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7F447B91-543F-4EBF-93DF-537C9709BA5F/20201019081031

### Expected behavior
Low CPU

### Actual behavior
CPU is consumed by :
/usr/sbin/mDNSResponder
/Applications/Docker.app/Contents/MacOS/com.docker.supervisor -watchdog

### Information

  - macOS Version: 10.15.7

Docker for Mac: version 2.4.1.0 (48583)

**Comment by andig** [comment]
I have another instance where hyperkit suddenly after running fine for hours and without change in the setup goes berserk: A913E1F9-1085-4C2B-A79D-4B6862C0EA1E/20201019100416

**Comment by stephen-turner** [comment]
Thanks for the reports, we'll have a look.

**Comment by ebriney** [comment]
Hi @andig, It's fixed in 2.4.2.0 released this morning. If it's not the case, re-open the issue.

**Comment by WimCools** [comment]
Thanks. It works fine now. No high CPU usage anymore.

**Comment by andig** [comment]
Still same or similar problem using 2.4.0.2 All out of a sudden, hyperkit goes up to 10-20% without anything having changed or running a workload: A913E1F9-1085-4C2B-A79D-4B6862C0EA1E/20201020162203

I suspect this might have something todo with returning from sleep mode?
