### ISSUE TITLE
No TCP access to containers from host when random host port is used

### ISSUE THREAD

**Issue by rnorth** [docker/for-mac#5005]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FBFD3714-76EA-44CA-939E-62D86C7F19B4/20201019125126

### Expected behavior

When specifying port binds for a container, without specifying the host port, it should be possible to connect to the container.

### Actual behavior

Unless a port is specified for the host side, it is not possible to connect to a container.

### Information

  - macOS Version: Catalina 10.15.6 (19G73)

### Diagnostic logs

```
Docker for Mac: 2.4.2.0
Diagnose succeeded
```

### Steps to reproduce the behavior

✅ Creating a container where the host port is fixed:
```
docker run -p 49999:8080 testcontainers/helloworld
curl localhost:49999 # works
```

❌ Creating a container without a fixed host port:
```
docker run -p 8080 testcontainers/helloworld
docker ps
# find the randomly assigned port, PORT, from docker ps output 
curl localhost:PORT # Does not work - Connection refused
```

When repeating the same steps on 2.4.1.0, no problem occurs and the container is accessible regardless of whether a host port has been specified.

**Comment by gesellix** [comment]
That's strange, because it sometimes works and sometimes fails.

**Comment by gmr** [comment]
Failing for me 100% of the time.

**Comment by gmr** [comment]
I downgraded from Edge to Stable and things are working. The difference on the surface is Edge is using higher port #'s. Instead of the normal 32768 starting port number, they appear to be starting at 49153.

**Comment by rnorth** [comment]
Yeah, I'd noticed the higher port numbers change as well. Still, it seems that manually specifying the host port with numbers in the higher range works (e.g. `-p 49999:8080`), so I think it must be something else.

@gesellix do you mean it is intermittent on the same Mac for you, or is it consistent on some Macs but not others?

Like @gmr, it's failing for me 100% of the time on the two Macs I've tried it on.

**Comment by gesellix** [comment]
@rnorth for me it's on the same Mac, using the latest Docker Desktop 2.4.2.0, and intermittent in approx. 10% cases (so: in most cases, I agree with the issue's description). In other words: I've seen working connections when connecting via `curl`.

Debugging the issue from Testcontainers/JVM, it consistently breaks when [trying read from the InputStream](https://github.com/testcontainers/testcontainers-java/blob/eeecf94f7c42b628599de13bbc5dbeaa5296f6ef/core/src/main/java/org/testcontainers/utility/ResourceReaper.java#L433).

**Comment by rnorth** [comment]
This seems to affect version 2.5.1.0 (current edge) as well. Diagnostics uploaded: `FBFD3714-76EA-44CA-939E-62D86C7F19B4/20201119170901`

**Comment by rnorth** [comment]
Not occurring on 3.1.0 (51484), so it appears this has been fixed somewhere along the way 🎉 
I'll close, as I don't think there's any value in keeping this issue open.
