### ISSUE TITLE
Non-executable files mounted via gRPC FUSE have execute access

### ISSUE THREAD

**Issue by cknave** [docker/for-mac#5007]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D9BD25FE-12BF-4841-A516-2FCF3B2368E6/20201019154923

### Expected behavior

Given a file mounted via gRPC FUSE with the execute bits UNSET, `access("/some/file", X_OK)` returns an access denied error

### Actual behavior

`access()` returns success

### Information

  - macOS Version: 10.15.7
  - docker desktop 2.4.0.0
  - downgrading to docker desktop 2.3.0.5 or disabling gRPC FUSE returns the expected behavior

### Diagnostic logs

```
Diagnose succeeded
```

### Steps to reproduce the behavior

  - simple test case: https://github.com/cknave/local-files-are-executable
  - `docker-compose run test`

**Comment by stephen-turner** [comment]
@djs55 Comments?

**Comment by thierrymarianne** [comment]
Hello! We've reproduced this issue in one of our development set up 

@tgachet and I would be happy to share reproducible details if you'd like to have some.
