### ISSUE TITLE
CPU problem (high usage and temperature)

### ISSUE THREAD

**Issue by cglacet** [docker/for-mac#5008]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F19472E2-6748-48A9-A7AF-EA55AAFC01D4/20201019160305

### Expected behavior

Being able to ear my music. More seriously my fans are running crazy every time I start docker desktop. For now my only solution is to only start docker when I absolutely need it. I would like to be able to let it run in the background even if I don't use it. 

### Actual behavior

Docker (`com.docker.hyperkit`) uses from 200 to 40% CPU depending on the context: 

* While starting docker: 200% CPU
* No container are running: 10% CPU
* A single nginx container: 10% CPU
* Kubernetes (Minikube) container: 40-70% CPU

My laptop is burning hot when I start docker and my fans are trying their best but still fail to maintain a decent temperature: 

```
--- CPU Stats ---
CPU temp:               70.88°C

--- Fan Stats ---
Total fans in system:   2
Fan 0 speed:            5614 RPM
Fan 1 speed:            5222 RPM
```
This is only after 2-3 minutes of being up and running with minikube.

Here is the before-after image for **stoping docker desktop**:

![Screenshot 2020-10-19 at 18 17 41](https://user-images.githubusercontent.com/28622118/96478303-d02c5680-1237-11eb-9efe-d25bde084897.png)

### Information

  - **MacBook Pro** (16-inch, 2019) `MacBookPro16,1`
     - **macOS Version** 10.15.7
     - **Processor** 2,3 GHz 8-Core Intel Core i9
         -  **L2 Cache (per Core)** 256 KB
         -  **L3 Cache** 16 MB
         -  **Hyper-Threading Technology** Enabled
     - **Memory** 16 GB 2667 MHz DDR4
  - I'm using docker as the driver for **minikube**:
     - **minikube version** v1.14.0 (commit: b09ee50ec047410326a85435f4d99026f9c4f5c4

### Steps to reproduce the behavior

  1. Download the latest version (edge `2.4.2.0`) : https://www.docker.com/products/docker-desktop
  2. Either of two ways: 
      * Run `minikube config set driver docker; minikube start`
      * Check the **Enable Kubernetes** then **Apply & Restart**

If I do **both** the CPU used will reach close to 100%.

**Comment by stephen-turner** [comment]
@cglacet Thanks for the report. We'll have a look. Do you still get problems if running containers without Kubernetes?

**Comment by cglacet** [comment]
Any test container you'd like me to run?

**Comment by stephen-turner** [comment]
Anything long running, I guess, like `docker run nginx`. I do realise that a lack of problem in that case wouldn't be evidence either way where the problem lies, but if it did reproduce in that case it would be useful information.

Another question: when you do see the problem, have you got lots of containers running workloads, or have you just enabled minikube to use docker but nothing is yet running? Thanks.

**Comment by cglacet** [comment]
After 2 minutes without running anything (not even kubernetes) I can already ear my fans complaining but the CPU temperature is still under 65°c and it seems stable. 

I'm starting nginx right now and I'll edit in 2-3 minutes. 

Otherwise, no, I had not a single pod running within minikube, maybe the dashboard (but probably not).

**Comment by stephen-turner** [comment]
OK, thanks, we'll have a look. We've squashed most of the CPU bugs in this release, but there might be one or two left.

**Comment by cglacet** [comment]
@stephen-turner thanks a lot, I really hope you'll be able to find where this comes from so I can work peacefully 👍 .

**Comment by chrisharrisonkiwi** [comment]
If I startup Docker, my machine can barely even register keystrokes.
The fan is on constantly if I startup a service.

I think I'm heading back to using Vagrant. 🤣

Running latest Docker for mac 2.4.0.0

**Comment by stephen-turner** [comment]
@chrisharrisonkiwi If you're OK to reset your system, please try the latest Edge release, 2.4.2.0: we've fixed a few more CPU issues since 2.4.0.0.

**Comment by cglacet** [comment]
@stephen-turner connecting back my machine today my CPU went crazy once again, I still only had nginx running and I reached almost 100% CPU on `com.docker.hyperkit`, CPU temperature went up to 80°c. 

* Diagnostics ID: F19472E2-6748-48A9-A7AF-EA55AAFC01D4/20201020081454

After a while CPU went slightly lower, but still remain a problem, here are the top consumers right now (I have about 15 tabs opened in chrome:

![Screenshot 2020-10-20 at 10 19 17](https://user-images.githubusercontent.com/28622118/96559738-b9c8de00-12bd-11eb-822f-e355ec8b1a78.png)

**Comment by cglacet** [comment]
@stephen-turner I checked again and updated my original ticket with new information. I also noticed that the dashboard shows the **kubernetes is running** message even when it's not (**Enable Kubernetes** isn't checked).

**Comment by ebriney** [comment]
Hi @cglacet, I took a look at your diagnostics and 40% is the regular consumption when you activate kubernetes.
I tried with minikube also, it's pretty much similar on my machine (NB: you can't do both enable in desktop and use minikube, it's one or the other).
For the UI, I found an issue, you need to close the window than reopen it for now.

**Comment by ebriney** [comment]
If you don't use kubernetes, just disable it and docker desktop will use 4-5 % of CPU which is the bare minimum we can do for now.

**Comment by oleg-andreyev** [comment]
Don't want to report duplicate issues.
Diagnostic ID 2C44A394-B140-408E-B98C-1B0839CF88E2/20201020151109
Running no containers.
![image](https://user-images.githubusercontent.com/1244112/96606706-3e3c5080-1300-11eb-9277-f3996367041c.png)

**Comment by RoyHP** [comment]
I'm having the same high CPU usage ~100% from kernel_task now on 2.4.0.0 but am not using kubernetes. It happens after the containers have been running for awhile (~4 hours) and after editing a file on the host.

I'm using docker compose with local volume mapped into the container with the cached option.

Diagnostic ID `B6FEF269-92CF-4126-8FE4-F8523A740F50/20201023203515`

**Comment by cglacet** [comment]
@ebriney I wonder how people use minikube if that high consumption is normal. Is there a suitable solution for this problem? Is there a problem with minikube itself? I mean kubernetes is only supposed to start few core services, I wonder why it takes that much CPU, it makes it almost unusable.

Anyway, if anyone knows an alternative solution let me know 📫

**Comment by ebriney** [comment]
@cglacet minikube is a kubernetes distribution with some config optimization to save some CPU because it assumes there is only one local node that is leader and worker at the sama time.
But the upstream kubernetes code is used and so it's design to manage a cluster.
On such configuration a full machine is elected as leader and dedicated to watch the cluster health, doing regular queries on all the workers.
This code cannot be removed, it handles all the scheduling, pod/resource lifecycle, that where all the cpu goes...

@RoyHP @oleg-andreyev can you try that build, which is pretty much the next stable that will be released next week:
https://desktop-stage.docker.com/mac/edge/49249/Docker.dmg

**Comment by Freyja-Folkvangr** [comment]
Same issue here.
between 10 and 20% CPU usage with no container running. 60 degrees celsius, the fan at maximum speed.
**Diagnostic ID** ECE4536A-9B31-406B-B662-DEF19E342F1A/20201030011438

2.5 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by oleg-andreyev** [comment]
@ebriney looks like your build has helped. No more high CPU usage

**Comment by gee-forr** [comment]
I'm using that build too now. Thanks @ebriney.

My CPU usage has halved from ~20% to ~10% on a 2.3ghz 8core  i9 when running no containers at all and k8s deactivated. My temps have also dropped about 8deg.

Hopefully further versions get it near to 0% when its doing nothing, but this is a massive improvement from the previous version.

Again - thank you very much.

**Comment by ebriney** [comment]
Thanks everybody for your help and your reports, we will continue on improving CPU performances where we can.

**Comment by hypeofpipe** [comment]
I like how it keeps my room warm in this cold autumn :D

MacOS Big Sur 11.0.1 (20B29), Docker version 19.03.13, build 4484c46d9d.

Processor 2,6 GHz 6-Core Intel Core i7, Memory 32 GB 2667 MHz DDR4...

My whole system lags because of the little containers I run, the container is MySQL DB and Redis instance

![image](https://user-images.githubusercontent.com/14982064/100353152-64839900-2fee-11eb-83d1-6d8ce8751732.png)

**Comment by datntvn** [comment]
Docker literally burns the mainboard of my Macbook pro (2017 - 15 inches - 32Gb of RAM). I was using latest version of Docker, it was December 2020.

I had to change the mainboard, and lost all the data on it.

**Comment by matei-dragu** [comment]
🤣
I am sorry Docker development team but this is a fail on a monumental level.

**Comment by stephen-turner** [comment]
Are any of the users on this thread using JetBrains products? It appears that the JetBrains Docker plugin is the cause of high CPU for many users. See https://github.com/docker/for-mac/issues/5116#issuecomment-755870142 and onwards for a discussion of this.

**Comment by JohannesAtGit** [comment]
The problem still exists in docker desktop version 3.2.2 and on the same MacBook Pro (16-inch, 2019) @cglacet  mentioned.

As soon as I start minikube:
```minikube start -p minikube2 --memory=4094
😄  [minikube2] minikube v1.18.1 on Darwin 11.2.3
✨  Automatically selected the docker driver. Other choices: hyperkit, ssh
👍  Starting control plane node minikube2 in cluster minikube2
🔥  Creating docker container (CPUs=2, Memory=4094MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube2" cluster and "default" namespace by default
```


The MAC laptop is getting extremely slow and a so called `kernel_task` is coming up in activity manager, consuming 500% to 1000% CPU load. Afterwards, the MAC is basically unusable.

I have PyCharm (JetBrains product) installed, but it is not running.

**Comment by stephen-turner** [comment]
@JohannesAtGit That would appear to be a Kubernetes problem or minikube problem, not a Docker problem.
