### ISSUE TITLE
High CPU usage (25%) of com.hyperkit.docker without running containers

### ISSUE THREAD

**Issue by folke** [docker/for-mac#5009]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `77B501E3-6B38-4490-83A3-4D6E2109C8B7/20201019172804`

### Expected behavior
When running docker, the process `com.hyperkit.docker` uses around 25% cpu all the time, without any containers running.

When I do start containers (postgresql & pgadmin), cpu usage stays pretty much the same.

I would expect the running docker to be mostly idle when no containers are running.

While creating the diagnostics, cpu usage for the hyperkit process went down to about 12%, but this is due to the log process taking lots of cpu.

### Actual behavior
The hyperkit process uses around 25% cpu all the time. This is with the latest edge version. The verion before this used around 14% all the time.

### Information
  - macOS Version: Big Sur 11.0 Beta (20A5395g)
  - running on a  MacbookPro 13 inch 2019
  - 2,4 GHz Quad-Core Intel Core i5
  - 8 GB 2133 MHz LPDDR3

### Diagnostic logs

```
Docker for Mac: 2.4.2.0 (48975)
Channel: edge

```

### Steps to reproduce the behavior

  1. install docker
  2. start docker

**Comment by stephen-turner** [comment]
Thanks for the report, @folke. Do you have Kubernetes enabled?

**Comment by folke** [comment]
@stephen-turner nope, nothing else running.

**Comment by folke** [comment]
Running CoreOS in Qemu uses around 1% CPU in comparison.

**Comment by moxx** [comment]
Same problem here

**Comment by ebriney** [comment]
Thanks for your report @folke, it seems to be related to Big Sur beta (on my Catalina macbook air I'm around 5%).
We will investigate if the problem persists on GA versions.

**Comment by slash686** [comment]
Encountered the same problem on Big Sur final release build. Docker CPU usage is around 20-25%, even when there are no active containers running.

```
MacBook Pro (16-inch, 2019)
2,3 GHz 8‑Core Intel Core i9
16 GB Ram
macOS Big Sur 11.0.1
Docker version 19.03.13, build 4484c46d9d
```

**Comment by uliSchuster** [comment]
I do see exactly the same problem after having upgraded to Big Sur.

MacBook Pro 16-inch, 2019
2.6 GHz 6/core Intel i7
32 GB Ram
macOS Big Sur 11.0.1
docker desktop 2.5.0.1, build 49550 with engine 19.03.13

**Comment by michalpopek** [comment]
Experiencing ~ 20% CPU usage in idle after upgrading to Big Sur as well.

MacBook Pro 15-inch 2019
2.6 GHz 6-Core Intel Core i7
16 GB RAM
macOS Big Sur 11.0.1
Docker desktop 2.5.0.1 (49550) with Docker Engine 19.03.13

**Comment by edsharp** [comment]
~15% CPU in idle

MacBook Pro 16-inch 2019
2.6 GHz 6-Core Intel Core i7
32 GB RAM
macOS Big Sur 11.0.1
Docker desktop 2.5.0.1 (49550) with Docker Engine 19.03.13

**Comment by Tomalaya** [comment]
Also seeing this issue:
Bug Sur 11.0.1 (20B29)
MacBook Pro (15-inch, 2019)
Processor 2.4 GHz 8-Core Intel Core i9
Memory 16 GB 2400 MHz DDR4
Docker Desktop 2.5.0.1 (49550)

Seeing 29.64% processor usage over 12 hour period when docker container is sitting idle.
