### ISSUE TITLE
Using docker volume prune does not output any data when purging volumes

### ISSUE THREAD

**Issue by mbentley** [docker/for-mac#5011]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: `82ECFF57-EBA1-41C9-8013-C69B95B6D55F/20201020205402`

### Expected behavior
From Docker CE on Debian 10 (19.03.13)
```
# docker volume ls
DRIVER              VOLUME NAME
# docker run -it -v data:/data alpine dd if=/dev/urandom of=/data/file.txt bs=1048576 count=250
250+0 records in
250+0 records out
# docker volume ls
DRIVER              VOLUME NAME
local               data
# docker rm $(docker ps -lq)
5de0174d0a76
# docker volume ls
DRIVER              VOLUME NAME
local               data
# docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
data

Total reclaimed space: 262.1MB
```

### Actual behavior
From Docker Desktop for Mac:
```
$ docker volume ls
DRIVER    VOLUME NAME
$ docker run -it -v data:/data alpine dd if=/dev/urandom of=/data/file.txt bs=1048576 count=250
250+0 records in
250+0 records out
$ docker volume ls
DRIVER    VOLUME NAME
local     data
$ docker rm $(docker ps -lq)
0ff09bdf0cef
$ docker volume ls
DRIVER    VOLUME NAME
local     data
$ docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
$ docker volume ls
DRIVER    VOLUME NAME
```

### Information
  - Is it reproducible? Yes, every time
  - Is the problem new? No, it has been happening for a little while, finally got around to reporting it
  - Did the problem appear with an update? Not sure, don't remember when I first noticed it
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: macOS Catalina 10.15.7

### Diagnostic logs

```
Docker for Mac: 2.4.2.0 (48975) - edge

```

### Steps to reproduce the behavior

See above for commands used.

  1. Run a container that creates a named volume
  2. Try to remove the volume via prune
  3. See that it was removed but isn't reported as pruned

**Comment by mbentley** [comment]
Also tried to prune it via API and it is returning something that doesn't match [the API](https://docs.docker.com/engine/api/v1.40/#operation/VolumeDelete):
```
$ docker volume create test
test
$ curl -X POST --unix-socket /var/run/docker.sock http:/v1.40/volumes/prune
{"Driver":"","Labels":null,"Mountpoint":"","Name":"","Options":null,"Scope":""}
$ docker volume ls
DRIVER    VOLUME NAME
```

I would expect this to work:
```
# docker volume create test
test
# curl -X POST --unix-socket /var/run/docker.sock http:/v1.40/volumes/prune
{"VolumesDeleted":["test"],"SpaceReclaimed":0}
# docker volume ls
DRIVER              VOLUME NAME
```

**Comment by stephen-turner** [comment]
Thanks for the report, @mbentley. I think this must be a change upstream of us, so could you please file the ticket in the moby/moby repo? (Sorry, I would just move it, but it's not possible to move tickets across orgs). Thanks.

**Comment by mbentley** [comment]
I could also reproduce this on the previous version of Docker for Mac with 19.03.12 and 19.03.13 I believe.  I only recently upgraded to the `20.10.0-beta1` version as the reporting instructions were to make sure that I upgraded to the very latest Docker for Mac.  I can't reproduce it directly on Linux which is why I reported it here as it only seems to impact Docker for Mac.  I'll see if I can test on the beta1 on Linux later but I don't expect it will happen on Linux with the newer version.

**Comment by mbentley** [comment]
This works fine on Linux:

```
root@docker:/# docker version
Client: Docker Engine - Community
 Version:           20.10.0-beta1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        ac365d7
 Built:             Tue Oct 13 18:16:22 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0-beta1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       9c15e82
  Built:            Tue Oct 13 18:14:39 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
# 1.40 API
root@docker:/# docker volume create test
test
root@docker:/# curl -X POST --unix-socket /var/run/docker.sock http:/v1.40/volumes/prune
{"VolumesDeleted":["test"],"SpaceReclaimed":0}

# 1.41 API
root@docker:/# docker volume create test
test
root@docker:/# curl -X POST --unix-socket /var/run/docker.sock http:/v1.41/volumes/prune
{"VolumesDeleted":["test"],"SpaceReclaimed":0}
```

**Comment by mbentley** [comment]
My only guess is that there is some problem with the proxy that is causing a problem on Docker for Mac specifically which is why I posted this here and not on moby/moby.

While performing the following commands, I captured the logs:
```
$ docker volume create test
test
$ docker volume prune -f
Total reclaimed space: 0B
```

Logs:
```
2020-10-21 08:25:45.593912-0400  localhost com.docker.driver.amd64-linux[32305]: proxy >> HEAD /_ping
2020-10-21 08:25:45.597496-0400  localhost com.docker.driver.amd64-linux[32305]: proxy << HEAD /_ping (3.672474ms)
2020-10-21 08:25:45.598121-0400  localhost com.docker.driver.amd64-linux[32305]: proxy >> POST /v1.41/volumes/create
2020-10-21 08:25:45.628169-0400  localhost com.docker.driver.amd64-linux[32305]: proxy << POST /v1.41/volumes/create (30.034971ms)
2020-10-21 08:25:47.227873-0400  localhost com.docker.driver.amd64-linux[32305]: proxy >> HEAD /_ping
2020-10-21 08:25:47.231040-0400  localhost com.docker.driver.amd64-linux[32305]: proxy << HEAD /_ping (3.186624ms)
2020-10-21 08:25:47.231598-0400  localhost com.docker.driver.amd64-linux[32305]: proxy >> POST /v1.41/volumes/prune
2020-10-21 08:25:47.238112-0400  localhost com.docker.driver.amd64-linux[32305]: proxy << POST /v1.41/volumes/prune (6.431899ms)
```

I don't know how to look at the `dockerd` logs inside the Docker for Mac VM otherwise I would check to see what the debug logs are showing.  I'd like to be able to rule out Docker for Mac completely before filing an issue over at moby/moby.

**Comment by stephen-turner** [comment]
Hmmm, OK, I'll reopen it.

**Comment by djs55** [comment]
@mbentley thanks for the report and repro instructions: I reproduced it in-house successfully.

On my Mac host:
```
docker volume create test
docker run -v test:/data --rm alpine dd if=/dev/urandom of=/data/file.txt bs=1048576 count=250
```
and then
```
docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
```
If I open a shell in the `dockerd` container inside the VM:
```
docker run -it --privileged --pid=host justincormack/nsenter1
/usr/bin/ctr -n services.linuxkit t exec -exec-id foo -t docker sh
docker volume create test
docker run -v test:/data --rm alpine dd if=/dev/urandom of=/data/file.txt bs=1048576 count=250
```
and then
```
/ # docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
test

Total reclaimed space: 262.1MB
```
-- it looks like we've broken the API result somehow (as you suspected!)

BTW for future diagnostics, the `dockerd` logs are streamed to the host and are in: ` ~/Library/Containers/com.docker.docker/Data/log/vm/dockerd.log`

Thanks again for the report!

**Comment by bwateratmsft** [comment]
I can see this same behavior on Docker Desktop on Windows.
