### ISSUE TITLE
Logfiles in mounted volumes get lost

### ISSUE THREAD

**Issue by arauchberger** [docker/for-mac#5012]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8FC60A66-8877-4183-BE61-42C95781FB25/20201021113516

### Expected behavior
A container has a bind-mounted volume. A Java-App uses logback to create logs there.
Opening the logs on the host (MacOS 10.15.7) with Console.app or TextEdit.app should just show the content of the log file.

### Actual behavior
When opening the logfile with Console.app the log file becomes 0 Byte immediately.
When using `tail -f logfile.log` or `vi log file.log' the behaviour is as expected and the file does not get changed.
When the logfile is already opened in Console.app and the Container is started afterwards the logs can be observed as long as the Console.app is kept open on the logfile.

### Information
The problem is seen since updating to Docker Desktop for Mac v.2.4.0.0 (48506) stable.
It can be reproduced all the time.

**it can be "solved" by unchecking the Use gRPC FUSE for file sharing !!**

  - macOS Version: 10.15.7

### Diagnostic logs

```
Docker for Mac: v.2.4.0.0 (48506) stable.

```

### Steps to reproduce the behavior
See above

**Comment by stephen-turner** [comment]
@arauchberger Thanks for the report.
@djs55 PTAL.

**Comment by djs55** [comment]
@arauchberger thanks for your report. Unfortunately I've not been able to reproduce the problem so far. Here's what I've tried on the latest stable 2.5.0.1 (49550):

I run a container with a shared directory:
```
mkdir -p logs
docker run -it -v $(pwd)/logs:/logs -w /logs alpine sh
```
I simulate writing to a log file inside the container:
```
echo "The first log line" > my.log
echo "The second log line" >> my.log
```
On the host I open the file with `TextEdit.app` and `Console.app` (I'm running Big Sur). Both show the current contents of the file.

In the container I append another line:
```
echo "The third log line" >> my.log
```
In TextEdit.app nothing changes straight away. If I attempt to modify the file it tells me that the file has changed on disk. If I choose to Revert my changes, I see the current file contents.
In Console.app I see the logs being appended.

Could you share a minimal `Dockerfile`  which writes logs and which demonstrates the problem?

**Comment by arauchberger** [comment]
Hi Scott,

maybe this issue does not occur on Big Sur anymore.
Are you sure you have `Use gRPC FUSE for file sharing` turned on in your Docker.App preferences?

Once the Console.app has opened the logfile (and i then restart the container) i also do see the expected behaviour of loglines getting appended.

i just tested it again with 2.5.0.0 ... same behaviour 😢 for me.

When i test the way you described, i also can NOT reproduce the issue.

For the Dockerfile: i do have a java-application using slf4j and logback to write to the logfile. at the moment i do not have a dummy-jar doing this which i could provide, but when i find the time i will do so. i also tried different appenders in the logback.xml to be sure that it's not a problem with the daily/filesize-rollover.

for the moment i just turned off `Use gRPC FUSE for file sharing` on my local machine, which is fine, since this is only a dev-notebook.
btw: i have no clue about this cfg-setting and it's pro- and cons. i was just happy/lucky finding a way to bypass the issue.

thank you for your feedback.
