### ISSUE TITLE
Kubernetest is in the "starting" state forever

### ISSUE THREAD

**Issue by meglio** [docker/for-mac#5014]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [] I have uploaded Diagnostics

### Expected behavior

Kubernetes starts successfully.

### Actual behavior

Kubernetes is in the "starting" state forever.

### Information

<img width="576" alt="image" src="https://user-images.githubusercontent.com/282177/96803039-badf4400-1452-11eb-8592-454a28e81275.png">

### Diagnostic logs

Cannot get one as it's stuck in the Diagnosis mode forever:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/282177/96803134-ed893c80-1452-11eb-8987-794779ca631e.png">

**Comment by patFish** [comment]
worked for me #https://github.com/docker/for-mac/issues/4968#issuecomment-704359305
