### ISSUE TITLE
Impossible to launch Docker on MacOS catalina

### ISSUE THREAD

**Issue by HaCkEuR0ElItE** [docker/for-mac#5017]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BE673D06-126B-4500-862E-74802C891609/20201023101349

### Expected behavior
Normal start of the application

### Actual behavior
Crash at start

### Information

  - macOS Version: MacOS Catalina 10.15.7

### Diagnostic logs

```
Docker for Mac: version 2.1.0.3 to 2.4.0.0

```

### Steps to reproduce the behavior

  1. Launch Docker

**Comment by ishubhamjain** [comment]
I am facing the same issue. Docker keep showing "Docker is starting" for forever
