### ISSUE TITLE
Docker start and restarts commands behave differently when checking existence of shared volumes on the host

### ISSUE THREAD

**Issue by radarek** [docker/for-mac#5018]
**Description**

Docker `start` and `restart` commands behave differently when checking existence of shared volumes on the host.
`docker start` fails when given shared volume doesn't exist on the host machine then container is not started.
`docker restart` doesn't fail when shared volume doesn't exist then container is started normally.

**Steps to reproduce the issue:**

```
$ CONTAINER=$(docker container create -v /non-existing-directory:/app alpine ls -al /app)
$ docker start $CONTAINER
Error response from daemon: Mounts denied:
The path /non-existing-directory is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info.
Error: failed to start containers: 648494767bdbe122a2d2ae8707c3c6654236630b56b52c7caa3e4a6b166b4afb
$ docker restart $CONTAINER
648494767bdbe122a2d2ae8707c3c6654236630b56b52c7caa3e4a6b166b4afb
$ docker logs $CONTAINER
total 4
drwxr-xr-x    2 root     root            40 Oct 23 09:46 .
drwxr-xr-x    1 root     root          4096 Oct 23 09:58 ..
```

**Describe the results you received:**

Commands handle checking shared volume existence in different way.

**Describe the results you expected:**

Both commands should behave in the same way.

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 8
  Paused: 0
  Stopped: 2
 Images: 69
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.811GiB
 Name: docker-desktop
 ID: QIDY:FKSE:HWNO:KSXX:ESXJ:GMFX:5JSY:WKHS:EUSC:HLBK:BABC:TTAA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by stephen-turner** [comment]
Thank you for the report, @radarek. Could you test whether it is fixed if you switch back from gRCP FUSE to osxfs in the settings? Thank you.

**Comment by radarek** [comment]
@stephen-turner I unchecked option "Use gRPC FUSE for file sharing" in the settings, restarted docker and the problem still exists.

**Comment by stephen-turner** [comment]
Thanks, we'll have a look.

**Comment by bhops** [comment]
Not sure if completely related, but I'm seeing something similar where passing volume mounts to `docker run` mounts differently if the directory exists vs not.

Here's the output from docker inspect when running with `-v /tmp:/tmp -v /tmp/non_existent_dir:/tmp/non_existent_dir`:
```
            {
                "Type": "bind",
                "Source": "/host_mnt/private/tmp,
                "Destination": "/tmp",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/tmp/non_existent_dir,
                "Destination": "/tmp/non_existent_dir",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```

**Comment by stephen-turner** [comment]
Confirm that this reproduces on Mac but not Windows.

@radarek Does this cause any problems, or is it just confusing / an annoyance? Thanks.

**Comment by radarek** [comment]
@stephen-turner We have rails applications which uses ruby's `docker-api` gem to start containers. It has been working for a long time without a trouble. After some time it stopped working. During debugging session we tried different things (it wasn't obvious what is the cause) and we discovered that when instead of `start` we use `restart` command it works again. At this point we were suspecting that a problem is in the `docker-api` gem. After more digging down we have finally found that our code uses nonexistent paths for volumes. The problem must have been from the beginning but popped up recently (and we realised that Docker Desktop has been updated lately). After we fixed the problem we made an experiment which confirmed that problem is in docker itself.

It's true that if from the beginning docker's `start` command didn't allow us to start a container with nonexistent paths we would't have that problem.  But for me personally there is no logical reason for which `start` and `restart` should behave differently in this manner. Especially if you can use `restart` command to start a container without prior usage of `start` command (contrary to what name suggest).

Answering your original question. For now it is just confusing but there is still potential for situations like we had and it may make similar problems to others in the future.

**Comment by stephen-turner** [comment]
Thanks, that's helpful. I agree that it's a bug, I was just trying to prioritise it appropriately.
