### ISSUE TITLE
com.docker.hyperkit high cpu usage

### ISSUE THREAD

**Issue by dfang** [docker/for-mac#5022]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 9F755020-B361-4F2E-9020-7F174E686DBF/20201026142900

### Expected behavior
cpu fan be quiet

### Actual behavior
cpu fan loud

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? no
  - Is the problem new? no
  - Did the problem appear with an update? no 
  - macOS Version: 10.15.7

kubernetes started

### Diagnostic logs

```
Docker for Mac: latest stable version 2.4.0.0
```

**Comment by dfang** [comment]
Everytime when i run docker build, cpu fan so load

```
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 839B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/golang:1.15                                                                                           0.0s
 => [internal] load metadata for gcr.io/distroless/static:nonroot                                                                                        0.3s
 => [internal] load build context                                                                                                                        0.0s
 => => transferring context: 6.78kB                                                                                                                      0.0s
 => CACHED [stage-1 1/3] FROM gcr.io/distroless/static:nonroot@sha256:75c99ae4ddc137571997e6e95f78c30dca226118326a0755ad19ebc4955abe3d                   0.0s
 => CACHED [builder 1/9] FROM docker.io/library/golang:1.15                                                                                              0.0s
 => [builder 2/9] WORKDIR /workspace                                                                                                                     0.1s
 => [builder 3/9] COPY go.mod go.mod                                                                                                                     0.0s
 => [builder 4/9] COPY go.sum go.sum                                                                                                                     0.0s
 => [builder 5/9] RUN go mod download                                                                                                                  115.1s
 => [builder 6/9] COPY main.go main.go                                                                                                                   0.1s
 => [builder 7/9] COPY api/ api/                                                                                                                         0.0s
 => [builder 8/9] COPY controllers/ controllers/                                                                                                         0.0s
 => [builder 9/9] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go                                               43.5s
```

**Comment by johncoleman83** [comment]
Hi, have you seen the enormous thread of troubleshooting here:
* https://github.com/docker/for-mac/issues/3499
* https://github.com/docker/for-mac/issues/4362

If not, maybe your issue can be resolved there.

If you're already aware of the former troubleshooting steps, then I'm glad you opened this issue again 🥳 .  In fact, the issue still persists for me with Docker for Mac.  I did find _part_ of the cause though, and so I'm not sure if the issue is with Docker or how we are using docker with `docker-sync` http://docker-sync.io/ .

In my case the issue is resolved by simply restarting `docker-sync`:

```
$ docker-sync stop && docker-sync start
```

**Comment by manoadamro** [comment]
I don't think I've ever used docker where this hasn't happened. I genuinely thought this was just part of using docker on mac tbh

**Comment by JosafatZero** [comment]
hello, I'm using docker for mac with kubernetes, and just with an nginx is having more than 50% of CPU, is that something normal?
![image](https://user-images.githubusercontent.com/7265104/98041351-68553e80-1de7-11eb-94f0-ae0645bc1037.png)
I have the latest version 2.5.0

**Comment by ebriney** [comment]
Running kubernetes consumes around 40% cpu without any running containers, so...
It's the same consumption for minikube, Docker Desktop uses the same optimizations.
@dfand , I looked at your diagnostic and you have 66 containers running for 90% CPU (almost one logical CPU) with kubernetes enabled.
I assume it's normal if you compile go code + run kubernetes.

**Comment by dfang** [comment]
previously 4 cpus, and i changed to 1 according a comment somewhere, but it does not fix.

it 3 recently, but cpu still got load sometimes.

**Comment by JeffKwasha** [comment]
No containers running, consuming 1 full core on 2019 Macbook Pro (10.15.7)
`$ ps -aef |grep docker
    0   130     1   0 Wed01PM ??         0:00.20 /Library/PrivilegedHelperTools/com.docker.vmnetd
  501   814   767   0 Wed01PM ??         1:01.28 /Applications/Docker.app/Contents/MacOS/com.docker.backend -watchdog
  501  1442   767   0 11:44AM ??         0:00.08 /Applications/Docker.app/Contents/MacOS/com.docker.supervisor -watchdog
  501  1443  1442   0 11:44AM ??         0:00.02 com.docker.osxfs serve --address fd:3 --connect vms/0/connect --control fd:4
  501  1444  1442   0 11:44AM ??         0:00.07 com.docker.vpnkit --ethernet fd:3 --diagnostics fd:4 --pcap fd:5 --vsock-path vms/0/connect --gateway-forwards /Users/jkwasha/Library/Group Containers/group.com.docker/gateway_forwards.json --host-names host.docker.internal,docker.for.mac.host.internal,docker.for.mac.localhost --listen-backlog 32 --mtu 1500 --allowed-bind-addresses 0.0.0.0 --http /Users/jkwasha/Library/Group Containers/group.com.docker/http_proxy.json --dhcp /Users/jkwasha/Library/Group Containers/group.com.docker/dhcp.json --port-max-idle-time 300 --max-connections 2000 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.254 --log-destination asl --gc-compact-interval 1800
  501  1447  1442   0 11:44AM ??         0:01.90 com.docker.driver.amd64-linux -addr fd:3 -debug
  501  1448  1442   0 11:44AM ??         0:00.03 docker serve --address unix:///Users/jkwasha/.docker/run/docker-cli-api.sock
  501  1460  1447   0 11:44AM ??         5:39.58 com.docker.hyperkit -A -u -F vms/0/hyperkit.pid -c 6 -m 3072M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=vpnkit.eth.sock,uuid=da184743-35c0-4e0e-8419-7ce03b14a547 -U 884f97c2-31e0-4ce4-8013-d018cd24c555 -s 2:0,virtio-blk,/Users/jkwasha/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw -s 3,virtio-sock,guest_cid=3,path=vms/0,guest_forwards=2376;1525 -s 4,ahci-cd,/Applications/Docker.app/Contents/Resources/linuxkit/docker-desktop.iso -s 5,virtio-rnd -l com1,null,asl,log=vms/0/console-ring -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,
  501  1546  1532   0 11:46AM ??         0:00.46 docker-compose --project-directory /Users/jkwasha/wrk/iq/cdniq-orchestration stop`

**Comment by robertchen** [comment]
same issue here
