### ISSUE TITLE
Segmentation violation exception with Docker edge on macos big sur beta 10

### ISSUE THREAD

**Issue by navxio** [docker/for-mac#5026]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 11.0 Beta
<img width="580" alt="image" src="https://user-images.githubusercontent.com/9297865/97464831-6878b880-1967-11eb-9383-9ac667d956bb.png">

### Diagnostic logs

```
Docker for Mac: Edge

```

### Steps to reproduce the behavior

  1. Install macos big sur beta 10
  2. run docker desktop (stable/edge)

**Comment by jtka** [comment]
This happened to me as well when I installed VirtualBox kernel extension. Uninstalling the extension let me start the docker.
```
sudo kmutil unload -b org.virtualbox.kext.VBoxUSB
sudo kmutil unload -b org.virtualbox.kext.VBoxNetFlt
sudo kmutil unload -b org.virtualbox.kext.VBoxNetAdp
sudo kmutil unload -b org.virtualbox.kext.VBoxDrv
```

**Comment by globalstripe** [comment]
Yep, Virtualbox.  I also installed virtual box and did a docker update today.

Thanks for posting those cmds on how to remove the extensions!

Another Big Sur update tonight!

**Comment by Vardiak** [comment]
This problem is not present in Docker 2.3.0.5 and seems to appear in 2.4.

**Comment by dorinclisu** [comment]
> This happened to me as well when I installed VirtualBox kernel extension. Uninstalling the extension let me start the docker.
> 
> ```
> sudo kmutil unload -b org.virtualbox.kext.VBoxUSB
> sudo kmutil unload -b org.virtualbox.kext.VBoxNetFlt
> sudo kmutil unload -b org.virtualbox.kext.VBoxNetAdp
> sudo kmutil unload -b org.virtualbox.kext.VBoxDrv
> ```

How can we complete remove these extensions? Next time I restarted macos I had to run the commands again before docker worked.

I even uninstalled virtualbox app the official way, it's quite despicable that it leaves junk in the system..

**Comment by stephen-turner** [comment]
Thanks for all the reports. We have a workaround incoming.

**Comment by stephen-turner** [comment]
And it's fixed in Docker Desktop 2.5.0.1.

**Comment by jonathon-love** [comment]
hi,

is the docker desktop 2.5 available from somewhere? i've not been able to find it.

in order for docker to start, i have to unload those virtualbox modules, but once i've unloaded those modules, i can't use the vbox docker machine machines.

with thanks

**Comment by stephen-turner** [comment]
@jonathon-love https://www.docker.com/products/docker-desktop

**Comment by digitalkaoz** [comment]
@stephen-turner not really. just updated and its still 2.4.2

**Comment by stephen-turner** [comment]
Edge channel hasn't got 2.5 yet, you need Stable channel.

**Comment by markhm** [comment]
I had to use [these instructions](http://osxuninstaller.com/uninstall-guides/properly-uninstall-virtualbox-mac-solved) to uninstall the kernel extensions. 

> sudo kmutil unload -b org.virtualbox.kext.VBoxUSB
> sudo kmutil unload -b org.virtualbox.kext.VBoxNetFlt
> sudo kmutil unload -b org.virtualbox.kext.VBoxNetAdp
> sudo kmutil unload -b org.virtualbox.kext.VBoxDrv

**Comment by stephen-turner** [comment]
We've just release Edge 2.5.1.0, so if you upgrade you should be OK now.
