### ISSUE TITLE
Kubernetes not starting in Docker desktop

### ISSUE THREAD

**Issue by ClimberBear** [docker/for-mac#5027]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 14953D49-8102-48BD-8964-94B55CD0862B/20201028155005

### Expected behavior
I have activated Kubernetes marking Enable Kubernetes and Show system container in Kubernetes section of preferences.
I expect to have kubernetes up & running

### Actual behavior
Kubernetes shows "Starting" and never finish to start
The log shows
```
2020-10-28 17:15:38.186905+0100  localhost com.docker.driver.amd64-linux[707]: cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)
2020-10-28 17:15:38.187165+0100  localhost com.docker.backend[673]: external: POST /events 200 "Go-http-client/1.1" ""
2020-10-28 17:15:38.513141+0100  localhost com.docker.driver.amd64-linux[707]: (libsystem_info.dylib) [com.apple.network.libinfo:getaddrinfo] nat64_v4_requires_synthesis(127.0.0.1) == false
```
repeating forever

### Information
I have checked my docker is up to date
I have checked localhost in /etc/hosts file is correct
Restarting the Mac doesn't solve the problem
I have found similar error in https://github.com/docker/for-mac/issues/2985, but, as commented, my hosts file is correct
I have found similar error here https://github.com/AliyunContainerService/k8s-for-docker-desktop/issues/56 (reported as solved)

  - macOS Version: macOS Catalina 10.15.7

**Comment by ClimberBear** [comment]
I have found that, maybe, this is a duplicated of 2990. But this appears as solved!

I have workarounded as:

**Comment by rjacks161** [comment]
```rm -rf ~/Library/Group\ Containers/group.com.docker/pki/```

Fixed my issues!

**Comment by hiwok** [comment]
Fixed my issues too ! Thanks.

**Comment by balibebas** [comment]
What good is K8s when #155 is still open? Honest question.

**Comment by benbendemo** [comment]
I am running the same issue. From the console log, below 3 PIDs periodically generating below error messages.

> com.docker.driver.amd64-linux: cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)

> com.docker.backend: external: POST /events 200 "DockerDesktopGo" ""

> com.docker.vpnkit: HTTP proxy --> 108.177.97.82:443 Host:k8s.gcr.io:443 (Origin): Failed to connect to 108.177.97.82:443

OS: macOS Catalina 10.15.7
Docker desktop: 3.0.4(51218)
Kubernetes: V1.19.3
Engine: 20.10.2

**Comment by balibebas** [comment]
As an alternative to Docker for Mac's single Kubernetes you can use Docker for Mac to create a multi-node Kubernetes cluster with the Kubernetes feature disabled. Here's a tutorial https://habd.as/post/kubernetes-macos-k3s-k3d-rancher/

**Comment by benbendemo** [comment]
I have tried a lots of ways to try to let K8S running in my macOS, the below error message occurs all the time.

> cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)

**Comment by brian-kalinowski-sonos** [comment]
I was fighting this issue for 2+ days and finally fixed the issue... my /etc/hosts file was corrupted/malformed (probably from some other application). 

THE FIX 
- try running the command `file -I /etc/hosts` you should see `/etc/hosts: text/plain; charset=us-ascii` BUT i was getting `/etc/hosts: application/octet-stream; charset=binary` which was preventing docker/k8s from properly reading it. 

- I edited/reset my hosts file to: 
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```
then reset docker and BOOM up and running no problem!

**Comment by rs-renato** [comment]
> I am running the same issue. From the console log, below 3 PIDs periodically generating below error messages.
> 
> > com.docker.driver.amd64-linux: cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)
> 
> > com.docker.backend: external: POST /events 200 "DockerDesktopGo" ""
> 
> > com.docker.vpnkit: HTTP proxy --> 108.177.97.82:443 Host:k8s.gcr.io:443 (Origin): Failed to connect to 108.177.97.82:443
> 
> OS: macOS Catalina 10.15.7
> Docker desktop: 3.0.4(51218)
> Kubernetes: V1.19.3
> Engine: 20.10.2

Same error here

**Comment by rs-renato** [comment]
> I have tried a lots of ways to try to let K8S running in my macOS, the below error message occurs all the time.
> 
> > cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)

I am not able to do k8s working also. It's sad! I will need to try minikube instead.

**Comment by Moulick** [comment]
@ClimberBear's solution up above at https://github.com/docker/for-mac/issues/5027#issuecomment-718076014 worked perfectly

**Comment by Moulick** [comment]
@rs-renato  use kind rather than minikube. Kind is like k8s in a container.

**Comment by benbendemo** [comment]
> @ClimberBear's solution up above at [#5027 (comment)](https://github.com/docker/for-mac/issues/5027#issuecomment-718076014) worked perfectly

Tried many times, can not solve the problem in my docker-for-macos.

**Comment by Moulick** [comment]
@benbendemo  how have you installed Docker ?

**Comment by benbendemo** [comment]
> @benbendemo how have you installed Docker ?

Installed by the dmg file downloaded from docker official website.

**Comment by timkitch** [comment]
I also had the "cannot get lease for master node: an error on the server" issue and Kubernetes would not start from Docker Desktop. My /etc/hosts file was fine. I tried cleaning the .kube directory and all sorts of things. Finally, I uninstalled Docker Desktop, downloaded and re-installed it, increased the Docker resources and enabled Kubernetes - this worked.

I suspect in my particular case, some remnant of my past experiments with docker, kubernetes, minikube, etc. was interfering. Anyway, if all else fails, try a complete re-install of Docker Desktop.

**Comment by emnvn** [comment]
> I have found that, maybe, this is a duplicated of 2990. But this appears as solved!
> 
> I have workarounded as:
> 
> ```
> rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
> rm -rf ~/.kube
> ```
> 
> And restarting docker

This command fixed my issue (docker version 3.2.0)
> rm -rf ~/Library/Group\ Containers/group.com.docker/pki/

**Comment by alegner** [comment]
Indeed: recreating %windir%\drivers\etc\hosts as a plain 'ASCI text' file and populating it with the following (plus what more I need for other purposes) overcame this (and the next) error:

```
127.0.0.1 docker-desktop
127.0.0.1 kubernetes.docker.internal
```

**Comment by claudioabudio** [comment]
Hello , i am having exactly this same issue , but on a Windows 10 machine, installed docker desktop, and when i try installing Kubernetes, it says "Starting..." and stays there forever :) .

I have also tried resetting docker desktop to factory settings, I have also tried removing the following directory as suggested on some posts: c:\Users\claud\AppData\Local\Docker\pki>

(it seems when docker desktop starts up it recreates that directory again...)

None of these did not work unfortunately. 

My docker desktop version is 3.2.1
Kubernetes version is v1.19.7

**Comment by crablab** [comment]
I am seeing the same issue on macOS 11.2.3 (Big Sur) - none of the above suggestions worked. 

Kubernetes: v1.19.7
Docker: v20.10.5

I ended up using the 'Clean / Purge data' option, which did work.

**Comment by rumimur** [comment]
> I am seeing the same issue on macOS 11.2.3 (Big Sur) - none of the above suggestions worked.
> 
> Kubernetes: v1.19.7
> Docker: v20.10.5
> 
> I ended up using the 'Clean / Purge data' option, which did work.

The same environment and the same issue, but this solution didn't work for me : (

**Comment by instantlinux** [comment]
Is this issue getting priority attention? I'm blocked by it. I have no idea what triggered the problem; most likely an update to docker since the last time I used the local k8s. My version is now 3.2.2 (61853) with kubernetes v1.19.7.

`cannot get lease for master node: an error on the server`

Tried all the workarounds noted above: no amount of file-removing, updating `/etc/hosts` or mouse-clicking in the purge / clean / restart sections of the UI will get it to launch any of the k8s containers. The `docker ps` command reports nothing running. I get the same error each time.

**Comment by balibebas** [comment]
@instantlinux curious, did you try the workaround I suggested [on Jan 9](https://github.com/docker/for-mac/issues/5027#issuecomment-757135296)?

**Comment by jhoughjr** [comment]
Dunno if this should be closed since after the latest update my dev env is broken because docker desktop will not stop start nor reset k8s. Tired reinstalling, deleting the  ~/.kube file. Probably should just use bare metal on a pi and not have to worry about forced updates breaking my env while I sleep.
