### ISSUE TITLE
Docker desktop Mac stuck in "starting..." 

### ISSUE THREAD

**Issue by johnlabarge** [docker/for-mac#5030]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:7DF76E57-C313-4B3E-A248-FCA841A1B1A7/20201029181122

### Information

  - Is it reproducible? yes
  - Is the problem new? yes
  - Did the problem appear with an update?
  - Docker Desktop Version:2.4.0
  - Mac OS Version : 10.15.6

### Diagnostic logs

```
I do not have this menu.
```

### Steps to reproduce the behavior

Try to start docker desktop or restart it on my Mac or boot my Mac.

**Comment by NorseGaud** [comment]
> macOS Version:2.4.0
Not sure this is a valid macOS version. Are you on Catalina (10.15), or Mojave?

**Comment by johnlabarge** [comment]
Updated

**Comment by johnlabarge** [comment]
Factory reset resolved it, but wish I could have found it.

**Comment by huang12zheng** [comment]
I have the same phenomenon
> Although I have deleted some files recently, I don't think it has anything to do with it
> Of course, I have reinstalled them, including 2.4.0

**Comment by huang12zheng** [comment]
When I installed 2.4.2, it worked. But I just wanted to solve the problem, it was not a good way
> Because it is reset

**Comment by huang12zheng** [comment]
> When I installed 2.4.2, it worked. But I just wanted to solve the problem, it was not a good way
> 
> > Because it is reset

2.4.0 also work by reset.

**Comment by gcstang** [comment]
Same issue on 3.0.3 (51017), reset allowed it to start.

**Comment by ArataKagan** [comment]
I just had the same issue. I uninstalled Docker **manually** following the article below, reinstalled and now it works fine for me.  
https://nektony.com/how-to/uninstall-docker-on-mac  

Docker Desktop version: 20.10.2
Mac OS Version: 10.15.7 (Catalina)

**Comment by kodywilson** [comment]
I was facing the same issues, Docker Desktop would stay in starting forever, but what fixed it for me was opening up the McAfee firewall for the Docker application. I had tried the factory reset, but it didn't help at all. Once I monkeyed with the firewall settings it started working right away...
