### ISSUE TITLE
File event notifications stop firing on host bind mount

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#5031]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20201029225634

### Expected behavior
File events continue to fire

### Actual behavior
File events stopped firing

### Information
  - macOS Version: 10.15.7

### Diagnostic logs
Not in current Docker for Mac

### Steps to reproduce the behavior
Not sure what causes this and it used to happen a lot in the past and had stopped but just popped up again (see #4811)

**Comment by phonezawphyo** [comment]
I also noticed this problem.
In v2.4.0, if "Use gRPC FUSE file sharing" is checked, the problem exists.
In v2.5.0, if "Use gRPC FUSE file sharing" is unchecked, the problem exists.

For now, file events are firing for me if I check "Use gRPC FUSE file sharing". It can be found under "Experimental Features"
