### ISSUE TITLE
CLI button not working on mac

### ISSUE THREAD

**Issue by CooperLloyd** [docker/for-mac#5032]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
container terminal window opens
### Actual behavior
base system terminal window opens (sometimes nothing)
### Information

  - macOS Version: Catalina 10.15.7

### Diagnostic logs

```
Docker for Mac: version... 

2.4.0.0

```

### Steps to reproduce the behavior

  1. Click CLI button under given container
  2. ...

**Comment by MatthiasWinkelmann** [comment]
Ran into the same issue. Version is ```2.4.2.0 (48975)```  on MacOS 10.16 ("Big Sur"). 

## fix:

1. In System Preferences, go to ``Security & Privacy``
2. Switch to the ``Privacy`` tab. 
3. Select ``Automation`` from among the choices on the left.  
4. Find the item for Docker in the pane on the right.
5. (not always necessary) Unlock the settings by clicking on the padlock in the lower left corner and authenticating.
7. Activate the Checkbox for ``Terminal``.
