### ISSUE TITLE
Fatal Error on start: mkdir permission denied

### ISSUE THREAD

**Issue by DevSchmidtchen** [docker/for-mac#5038]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker Desktop starts normal without any errors.

### Actual behavior

On startup the application shows this:
![Fatal Error](https://user-images.githubusercontent.com/16440155/97994885-1bbd3380-1de6-11eb-8acd-b1ebe0e3251b.png)

Diagnostics also don't work and are stuck in this screen:
<img width="832" alt="Diagnostics" src="https://user-images.githubusercontent.com/16440155/97995031-4e672c00-1de6-11eb-8e21-b337b9586484.png">

### Information

  - macOS Version: 10.15.7 (19H2)

I already tried restarting my computer and reinstalling Docker and Docker Desktop, without success.
The problem has to be new, it worked normal some time ago with the same computer. 

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nitin26gupta** [comment]
Hello,
did you find any solution to this issue?

**Comment by RohanNagar** [comment]
I have the same issue on the latest version. I am also on Big Sur.

**Comment by RohanNagar** [comment]
<img width="749" alt="Screen Shot 2020-11-18 at 7 58 11 PM" src="https://user-images.githubusercontent.com/5522930/99619510-78207580-29d8-11eb-999a-3509f6bcb03e.png">

macOS version: 11.0.1

**Comment by DevSchmidtchen** [comment]
> Hello,
> did you find any solution to this issue?

Unfortunately not, it's still the same, also with macOS Big Sur.

**Comment by m-bal** [comment]
I don't think this the right solution but running `sudo chown $(whoami) ~/.docker` fixed it for me since .docker had root permissions.

**Comment by RohanNagar** [comment]
> I don't think this is the right solution but running `sudo chown $(whoami) ~/.docker` fixed it for me since .docker had root permissions.

Thank you! This worked for me.
