### ISSUE TITLE
Mac OSX - Error response from daemon: unknown: Authentication is required

### ISSUE THREAD

**Issue by PatrickMadden** [docker/for-mac#504]
### Steps to reproduce

1. docker pull mysql or docker pull nginx
2. I can do docker login and successfully authenticate to docker hub as well as a local artifactory instance running 4.12.01

### Expected behavior

I expect it to download the image to my local registry

### Actual behavior

docker pull nginx
Using default tag: latest
Error response from daemon: unknown: Authentication is required

### Information

```
Diagnostic ID: C8CE7ED0-ECB9-4DB2-AF2C-1DF05F7E62D2
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by PatrickMadden** [comment]
I can login to a Windows 10 machine on my local lan and do:
docker pull nginx
It works just fine.

**Comment by mchiang0610** [comment]
@PatrickMadden You should be able to download to local registry without needing authentication. 

Can you try this again after resetting to factory defaults? I just tested on my end, and it's working. 

We also have beta 25 released. 

Thanks!
