### ISSUE TITLE
Incorrect Checkboxes in 2.5.0.0 Preferences

### ISSUE THREAD

**Issue by jonesiscoding** [docker/for-mac#5040]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 71A5B5F3-203B-4F9C-A62F-0A26B37AC998/20201103174703

### Expected behavior

The checkboxes in preferences should be correctly labeled, and if the preference still exists, the gRPC-FUSE checkbox should be present.

### Actual behavior

The preference for Time Machine references 'Switch off to use the legacy osxfs file sharing instead.'  This reference was on the 'Use gRPC-FUSE' checkbox in version 2.4.x. 

The 'Use gRPC-FUSE' checkbox is also now missing. I did not see any reference to this in the release notes, so I believe this to be unintended as well.

### Information

  - Is it reproducible? *Yes*
  - Is the problem new? *Yes*
  - Did the problem appear with an update?  *Yes*
  - macOS Version: *10.14.6*
  - Docker for Mac Version: 2.5.0.0

### Steps to reproduce the behavior

  1. Open 'Docker for Mac'
  2. Choose 'Preferences' from the menubar icon.
  3. Select the 'General' category, if not already selected.

**Comment by stephen-turner** [comment]
Thanks for the report. We are aware that the time machine checkbox has the wrong subtext, but the grpcfuse checkbox should still be present.

**Comment by jonesiscoding** [comment]
<img width="1250" alt="Screen Shot 2020-11-03 at 11 54 50 AM" src="https://user-images.githubusercontent.com/5215554/98024955-ad20ab80-1dce-11eb-9304-0e09a42a8f81.png">

My apologies, I forgot the screenshot in the previous message.  I would be happy to manually add the key/value in the settings.json file and report back if that makes a difference, if I knew the proper key.

**Comment by stephen-turner** [comment]
It's in the Experimental tab now. (I think it might have moved, I don't remember).

**Comment by jonesiscoding** [comment]
Ah, that explains it.  Thank you very much for letting me know where it had moved to.

**Comment by stephen-turner** [comment]
You're welcome. I'll leave this ticket open to fix the wrong text on the other option.
