### ISSUE TITLE
Kubernetes stuck in starting (reopen)

### ISSUE THREAD

**Issue by damienburke** [docker/for-mac#5041]
https://github.com/docker/for-mac/issues/3649 was auto closed after 30 days.
This issue seems to be not resolved, and happening to me on Docker Desktop v2.5.0.0 (Catalina 10.15.7) and i can workaround by deleting the pki folder mentioned.
If as the original ticket suggests, this is caused by version updates, then should be fixed imo

**Comment by dgdosen** [comment]
Can anyone clarify if kubernetes should be working in the Apple Silicon Preview?  
The docker/desktop-kubernetes is not built for arm64.  Is it correct to assume kubernetes won't work until that's updated?

In addition, the only feedback a user gets is to show that kubernetes is 'starting....'
