### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by RomRey** [docker/for-mac#5043]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop starts normal without any errors.
### Actual behavior
On startup the application shows this:
Fatal Error
one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 1495)

Diagnostics also don't work and are stuck on the first screen.
### Information

  - macOS Version: 10.13.6 (17G65)
I already tried restarting my computer and reinstalling Docker and Docker Desktop, without success.
The problem has to be new, it worked normal some time ago with the same computer.

### Diagnostic logs

```
Docker for Mac: version 2.5.0.0

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by asor12** [comment]
I had the same error, I think the latest update supports only MacOS 10.14 and up.
