### ISSUE TITLE
GZIP saved inside a volume is corrupted

### ISSUE THREAD

**Issue by alexlana** [docker/for-mac#5047]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BA17F5A6-BDB0-452D-8CFC-906BC712F99F/20201104210011

### Expected behavior
Save a .gzip file inside a volume

### Actual behavior
Save a .gzip file but maybe it have 40% filled with zeros.

### Information

  - macOS Version: 10.15.7 (19H2)

### Diagnostic logs

```
Docker for Mac: version 2.5.0.0 (49427)

```

### Steps to reproduce the behavior

I install Rasa (https://github.com/RasaHQ/rasa) using Docker, the ConcertBot (https://github.com/RasaHQ/rasa/tree/master/examples/concertbot). Steps:

1. 	docker build . --no-cache -f ./rasa/hexaquad_requirements.Dockerfile -t botrequirements
Dockerfile:
```
FROM python:3.7-slim as base

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
    # required by psycopg2 at build and runtime
    libpq-dev \
     # required for health check
    curl \
 && apt-get autoremove -y

FROM base as builder

RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  wget \
  openssh-client \
  graphviz-dev \
  pkg-config \
  git-core \
  openssl \
  libssl-dev \
  libffi6 \
  libffi-dev \
  libpng-dev \
  gzip

# install poetry
# keep this in sync with the version in pyproject.toml and Dockerfile
ENV POETRY_VERSION 1.0.3
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH "/root/.poetry/bin:/opt/venv/bin:${PATH}"

# copy files
COPY ./rasa /build/
COPY rasa/docker/configs/config_pretrained_embeddings_spacy_pt.yml /build/config.yml

# change working directory
WORKDIR /build

# install dependencies
RUN python -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --no-cache-dir -U 'pip<20' && \
  poetry install --extras spacy --no-dev --no-root --no-interaction && \
  poetry build -f wheel -n && \
  pip install --no-deps dist/*.whl && \
  rm -rf dist *.egg-info

# make sure we use the virtualenv
ENV PATH="/opt/venv/bin:$PATH"

# spacy link
RUN pip install -U spacy
RUN python -m spacy download pt_core_news_md && \
    python -m spacy link pt_core_news_md pt

# start a new build stage
FROM base as runner

# copy everything from /opt
COPY --from=builder /opt/venv /opt/venv

# make sure we use the virtualenv
ENV PATH="/opt/venv/bin:$PATH"

# update permissions & change user to not run as root
WORKDIR /app
RUN chgrp -R 0 /app && chmod -R g=u /app
USER 1001

# Create a volume for temporary data
VOLUME /tmp

# change shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# the entry point
EXPOSE 5005
ENTRYPOINT ["rasa"]
CMD ["--help"]
```

2. 	docker run -it -v "./app:/app" --name hexacoach botrequirements train

3. 	docker-compose up --build bot
docker-compose.yml:
```
version: '3'

services:

  bot_actions:
    container_name: hexaquad_actions
    build:
      context: .
      dockerfile: ./dockerfile/hexaquad_action.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./app/actions:/app/actions
    working_dir: /app
    command:
      - start
      - --actions
      - actions

  bot:
    container_name: hexaquad
    build:
      context: .
      dockerfile: ./dockerfile/hexaquad.Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - bot_actions
    command:
      - run
      - --cors
      - "*"
```

The error is on step 2, the model is saved as a GZIP file inside a volume. The file is corrupted, maybe 40% of the file (opened in hexfiend) is only zeros. When I try to open, I get an error message, and the bot can't use the model because "oserror not a gzipped file"

The train ends with this messagem:
```
2020-11-05 02:21:36 INFO     rasa.core.agent  - Persisted model to '/tmp/tmpevvrpv7i/core'
Core model training completed.
Your Rasa model is trained and saved at '/app/models/20201105-023422.tar.gz'.
```

It's the error when Rasa try to load the model from the volume:
```
rbot       | Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ozrx4qe7 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
rbot       | 2020-11-05 02:35:41 WARNING  rasa.utils.common  - Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
rbot       | 2020-11-05 02:35:41 INFO     rasa.model  - Loading model models/20201105-023422.tar.gz...
rbot       | 2020-11-05 02:35:41 ERROR    rasa.model  - Failed to extract model at models/20201105-023422.tar.gz. Error: not a gzip file
rbot       | Traceback (most recent call last):
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1646, in gzopen
rbot       |     t = cls.taropen(name, mode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1623, in taropen
rbot       |     return cls(name, mode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1486, in __init__
rbot       |     self.firstmember = self.next()
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 2289, in next
rbot       |     tarinfo = self.tarinfo.fromtarfile(self)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1094, in fromtarfile
rbot       |     buf = tarfile.fileobj.read(BLOCKSIZE)
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 287, in read
rbot       |     return self._buffer.read(size)
rbot       |   File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
rbot       |     data = self.read(len(byte_view))
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 474, in read
rbot       |     if not self._read_gzip_header():
rbot       |   File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
rbot       |     raise OSError('Not a gzipped file (%r)' % magic)
rbot       | OSError: Not a gzipped file (b'\x00\x00')
rbot       | 
rbot       | During handling of the above exception, another exception occurred:
rbot       | 
rbot       | Traceback (most recent call last):
rbot       |   File "/opt/venv/bin/rasa", line 8, in <module>
rbot       |     sys.exit(main())
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
rbot       |     cmdline_arguments.func(cmdline_arguments)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 116, in run
rbot       |     get_model(args.model)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 159, in get_model
rbot       |     return unpack_model(model_path)
rbot       |   File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 204, in unpack_model
rbot       |     with tarfile.open(model_file, mode="r:gz") as tar:
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1593, in open
rbot       |     return func(name, filemode, fileobj, **kwargs)
rbot       |   File "/usr/local/lib/python3.7/tarfile.py", line 1650, in gzopen
rbot       |     raise ReadError("not a gzip file")
rbot       | tarfile.ReadError: not a gzip file
rbot exited with code 1
```

I think it is related to Docker in MacOS because in Rasa comunity I found related issues with gzip and Docker. And when I upgrade from 2.4.0.0 to 2.5.0.0 magically all get to work. But after some training the corrupted gzips come back. I try to reinstall, but problem persists.

**Comment by alexlana** [comment]
And... large files generate more errors. Some models have 2MB and sometimes it works. When the model have +20MB, it fails.

**Comment by StefanScherer** [comment]
I tried to reproduce it, thanks for the steps.
What I did:
(I had to change the Dockerfile a bit: renamed config_pretrained_embeddings_spacy_pt.yml to config_pretrained_embeddings_spacy_de.yml because the other file doesn't exist)

```
mkdir test && cd test
git clone https://github.com/RasaHQ/rasa
vi Dockerfile
other file doesn't exist
docker build . --no-cache -t botrequirements
docker run -it -v "$(pwd):/app" --name hexacoach botrequirements train
```
When I look at the generated tar.gz it looks good as I can list the content
```
$ ls -l models/
total 44160
-rw-r--r--  1 stefanscherer  staff  22117671 Nov  5 09:49 20201105-084938.tar.gz
$ tar tvf models/20201105-084938.tar.gz
```

Have you tried to do a factory reset in Docker Desktop and try again? I'm using gRPCfuse instead of osxfs which is default for new installations / after a factory reset.

**Comment by alexlana** [comment]
It's Dropbox... :) I keep these things under a Dropbox folder. Maybe other apps like Google have the same result.

@StefanScherer thank you for your time and effort! I try your sugestion before and it not work, so I remember and test to pause Dropbox....

**Comment by airdrummingfool** [comment]
I am experiencing this problem in `2.4.0.0` and `2.5.0.0` when using the AWS Elastic Beanstalk CLI to deploy code from inside a Docker container. probably 9/10 attempted deployments would fail with an invalid zip file (1/10 would succeed). I confirmed with a hex editor that the first ≈25% of a failed zip file was all 0s.

Unchecking `Use gRPC FUSE for file sharing` fixes the problem. It's worth noting that I am working from inside a Docker container, but it works fine without `Use gRPC FUSE for file sharing` checked; could this be considered a regression in Docker?

**Comment by alexlana** [comment]
Hi, @airdrummingfool! For me it happens because of a automatic backup software (Dropbox). I think some interaction between Docker and Dropbox create this kind of GZIP.

Maybe you can uninstall Docker Desktop (preferences -> bug icon -> uninstall) and get an older version from here: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by airdrummingfool** [comment]
Hi @alexlana, thanks for your reply. I did try an older version (2.4.0.0) along with the current version (2.5.0.0), and both behaved similarly.

I also use Dropbox, but as long as I turn off the experimental feature `Use gRPC FUSE for file sharing`, Dropbox doesn't have any negative affect on zip file generation. Thus, I believe this to be a bug not because of Dropbox, but because of the experimental new file sharing system.

I would suggest that you try working inside of your Dropbox folder as normal, but with `Use gRPC FUSE for file sharing` turned off (Docker > Preferences > Experimental Features) and see if this also fixes the issue for you.

**Comment by alexlana** [comment]
You are right, @airdrummingfool ! Without gRPC I can use Dropbox. Thanx!!!

**Comment by airdrummingfool** [comment]
@alexlana would you consider re-opening this issue? I consider this to be a regression, and hope Docker will fix it before removing osxfuse support.

**Comment by stephen-turner** [comment]
That is very weird. @djs55 PTAL.
