### ISSUE TITLE
socksProxyPort setting no longer starting a socks proxy to forward traffic to containers

### ISSUE THREAD

**Issue by s-oliver** [docker/for-mac#5048]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 0E3F2F59-1503-468D-BB17-63F476E16B84/20201105094326

### Expected behavior
After adding `"socksProxyPort" : 8888` to my config file in `~/Library/Group Containers/group.com.docker/settings.json` and restarting Docker for Mac, I expected a socks proxy listening on port 8888 to forward traffic to my containers. This always used to work before the latest update to 2.5.0.0

### Actual behavior
No socks proxy is listening on port 8888 (port is closed)
```
$ nc -v localhost 8888
nc: connectx to localhost port 8888 (tcp) failed: Connection refused
```

### Information
This used to work with all previous versions and stopped working with the 2.5.0.0 update. Restarting docker and even the whole machine did not work either.
- macOS Version: Catalina 10.15.7 (19H2)

### Diagnostic logs
There's no output to see here
Docker for Mac: 

### Steps to reproduce the behavior
My full `settings.json`
```
{
  "filesharingDirectories" : [
    "\/Users",
    "\/Volumes",
    "\/private",
    "\/tmp"
  ],
  "backupData" : false,
  "latestBannerKey" : "",
  "diskSizeMiB" : 61035,
  "diskFlush" : "os",
  "displayRestartDialog" : false,
  "kubernetesEnabled" : false,
  "settingsVersion" : 6,
  "diskQcowKeepErased" : 262144,
  "useCloudCli" : true,
  "kubernetesInitialInstallPerformed" : false,
  "displaySwitchVersionPack" : true,
  "analyticsEnabled" : true,
  "overrideProxyHttps" : "",
  "dataFolder" : "Library\/Containers\/com.docker.docker\/Data\/vms\/0\/data",
  "dockerAppLaunchPath" : "\/Applications\/Docker.app",
  "displayedDeprecate1013" : false,
  "diskQcowRuntimeAsserts" : false,
  "diskQcowCompactAfter" : 262144,
  "autoStart" : false,
  "cpus" : 2,
  "swapMiB" : 1024,
  "displayedTutorial" : true,
  "diskTRIM" : true,
  "diskStats" : "",
  "versionPack" : "default",
  "vpnKitMTU" : 1500,
  "useCredentialHelper" : true,
  "vpnkitCIDR" : "192.168.65.0\/24",
  "channelID" : "stable",
  "overrideProxyHttp" : "",
  "socksProxyPort" : 8888,
  "checkForUpdates" : true,
  "displayedDeprecate1012" : false,
  "showKubernetesSystemContainers" : false,
  "memoryMiB" : 2048,
  "vpnKitAllowedBindAddresses" : "0.0.0.0",
  "vpnKitMaxPortIdleTime" : 300,
  "proxyHttpMode" : "system",
  "credentialHelper" : "docker-credential-osxkeychain",
  "vpnKitTransparentProxy" : true,
  "overrideProxyExclude" : "",
  "synchronizedDirectories" : [

  ],
  "activeOrganizationName" : "",
  "vpnKitMaxConnections" : 2000
}
```

**Comment by stephen-turner** [comment]
Thanks for the report, @s-oliver. We didn't deliberately remove it, but as it was only ever an experimental feature (see docker/for-mac#2670) we didn't have any tests for it, so it's possible that we broke it accidentally. We'll have a look how easy it is to replace.

**Comment by djs55** [comment]
@s-oliver I have an experimental fix, if you'd like to try it: https://desktop-stage.docker.com/mac/edge/49507/Docker.dmg -- it's not notarized and it's based off the development branch so it is not as stable as a regular released build. Let me know if you have time to test it.

**Comment by s-oliver** [comment]
@djs55 Thanks for providing a solution this quickly. Unfortunately I only have MacOS on the MacBook my employer provides me with where we are not allowed to install unverified Software, so I am unable to test your experimental fix :(

**Comment by mat007** [comment]
@s-oliver would a notarized build work for you or by unverified Software did you mean your IT department needs to approve it and deploy it on your machine?

**Comment by s-oliver** [comment]
@mat007 apps from the app store and from identified developers can be installed without problem, so I think what you mean by "notarized" should work just fine

**Comment by mat007** [comment]
@s-oliver you can re-download the version linked above, it should install on your machine now: https://desktop-stage.docker.com/mac/edge/49507/Docker.dmg
Thanks!

**Comment by s-oliver** [comment]
@mat007 thank you, the provided version behaves exactly as expected, I can connect to the local socks proxy on port 8888 and access my containers through it 👍 
Will this make it into future stable releases again? I'd prefer using the stable channel in the long run

**Comment by stephen-turner** [comment]
Yes, it will get into the next stable.

**Comment by s-oliver** [comment]
Thanks, it made it back into the stable release with 3.0 - works like a charm!
