### ISSUE TITLE
Updater emits macOS version warning without mentioning Docker

### ISSUE THREAD

**Issue by lkuchenb** [docker/for-mac#5049]
The macOS version warning emitted by the updater does not contain any indication that the dialog is related to docker.

### Expected behavior

The macOS version warning should inform the user that there is a _Docker_ update.

### Actual behavior

The macOS version warning should inform the user that there is an "update".

- macOS Version: 10.13

I had to use "Accessibility Inspector.app" that ships with XCode to identify the process behind the dialog.

<img width="2560" alt="Screen Shot 2020-11-06 at 10 47 56" src="https://user-images.githubusercontent.com/5948880/98353672-ebf97000-201f-11eb-8365-40fc6a7cf17d.png">

**Comment by SeanBurkeDesign** [comment]
Also noticed this starting ~2 weeks ago. Assumed it was some background application my company uses. Just figured it out by happening upon a comment on StackOverflow. Cleared the dialog. Ran Check for Updates from the toolbar menu, and sure enough the same exact unidentifiable dialog popped up.

Running Docker Desktop for Mac v2.4.0.0 (48506) on High Sierra v10.13.6.
