### ISSUE TITLE
kubectl shell completions are missing

### ISSUE THREAD

**Issue by gavvvr** [docker/for-mac#5050]
### Expected behavior

`/Applications/Docker.app/Contents/Resources/etc` to include `kubectl` shell completions

### Actual behavior

shell completions for kubectl are missing

### Additional info:

Docker for Mac: 2.5.0.0

**Comment by johanneswuerbach** [comment]
/remove-lifecycle stale

I would also like to see kubectl shell completions being shipped with Docker for Mac similar to the already included docker cli shell completions.
