### ISSUE TITLE
The operation couldn’t be completed. (Docker.VmnetdError error 1.)

### ISSUE THREAD

**Issue by live2ravi** [docker/for-mac#5056]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 16691D5C-025F-44B0-AB72-FFC8BEF01DF5/20201110052856

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by z7z8th** [comment]
@vladpetyuk commented on https://github.com/docker/for-mac/issues/3886  
that install homebrew fixed this problem, not docker through brew, but just brew.  
which make me curious about the installation script of homebrew, during checking the homebrew install prefix,  
I found a simple way to fix this docker problem.  

The root cause is /usr/local/bin is not accessible by normal user,  
you need to change the permission of it by run `sudo chmod -R go+rx /usr/local/bin` to make docker work.  


```sh

% find /usr/local
/usr/local
/usr/local/bin
find: /usr/local/bin: Permission denied
....

% sudo -i
Password:
root ~ # cd /usr/local/

root /usr/local # ls -lh
total 0
-rw-r--r--   1 root  wheel     0B Oct 16 14:11 .com.apple.installer.keep
drwx------  16 root  wheel   512B Nov 14 16:35 bin
drwxr-xr-x   3 root  wheel    96B Nov 14 16:35 lib
drwxr-xr-x   4 root  wheel   128B Sep 21 13:37 opt
drwxr-xr-x   3 root  wheel    96B Jul  8 21:31 share

root /usr/local # chmod -R go+rx bin

root /usr/local # ls -lh
total 0
-rw-r--r--   1 root  wheel     0B Oct 16 14:11 .com.apple.installer.keep
drwxr-xr-x  16 root  wheel   512B Nov 14 16:35 bin
drwxr-xr-x   3 root  wheel    96B Nov 14 16:35 lib
drwxr-xr-x   4 root  wheel   128B Sep 21 13:37 opt
drwxr-xr-x   3 root  wheel    96B Jul  8 21:31 share

root /usr/local # ls -lh bin
total 24
-rwxr-xr-x  1 root  wheel   525B Oct 28 09:45 bundle
-rwxr-xr-x  1 root  wheel   526B Oct 28 09:45 bundler
lrwxr-xr-x  1 root  wheel    62B Nov 14 16:35 com.docker.cli -> /Applications/Docker.app/Contents/Resources/bin/com.docker.cli
lrwxr-xr-x  1 root  wheel    54B Nov 14 16:35 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x  1 root  wheel    77B Nov 14 16:35 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose
lrwxr-xr-x  1 root  wheel    73B Nov 14 16:35 docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop
lrwxr-xr-x  1 root  wheel    75B Nov 14 16:35 docker-credential-ecr-login -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-ecr-login
lrwxr-xr-x  1 root  wheel    77B Nov 14 16:35 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
lrwxr-xr-x  1 root  wheel    67B Nov 14 16:35 hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
lrwxr-xr-x  1 root  wheel    55B Nov 14 16:35 kubectl -> /Applications/Docker.app/Contents/Resources/bin/kubectl
lrwxr-xr-x  1 root  wheel    55B Nov 14 16:35 kubectl.docker -> /Applications/Docker.app/Contents/Resources/bin/kubectl
-rwxr-xr-x@ 1 root  wheel   2.5K Jan 31  2020 mountesp
lrwxr-xr-x  1 root  wheel    54B Nov 14 16:35 notary -> /Applications/Docker.app/Contents/Resources/bin/notary
lrwxr-xr-x  1 root  wheel    65B Nov 14 16:35 vpnkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit
root /usr/local # 
```

**Comment by z7z8th** [comment]
@anietieasuquo @ulrich @wonderboy18 @axmachina

**Comment by yeziandkuma** [comment]
> @vladpetyuk commented on #3886
> that install homebrew fixed this problem, not docker through brew, but just brew.
> which make me curious about the installation script of homebrew, during checking the homebrew install prefix,
> I found a simple way to fix this docker problem.
> 
> The root cause is /usr/local/bin is not accessible by normal user,
> you need to change the permission of it by run `sudo chmod -R go+rx /usr/local/bin` to make docker work.
> 
> ```shell
> % find /usr/local
> /usr/local
> /usr/local/bin
> find: /usr/local/bin: Permission denied
> ....
> 
> % sudo -i
> Password:
> root ~ # cd /usr/local/
> 
> root /usr/local # ls -lh
> total 0
> -rw-r--r--   1 root  wheel     0B Oct 16 14:11 .com.apple.installer.keep
> drwx------  16 root  wheel   512B Nov 14 16:35 bin
> drwxr-xr-x   3 root  wheel    96B Nov 14 16:35 lib
> drwxr-xr-x   4 root  wheel   128B Sep 21 13:37 opt
> drwxr-xr-x   3 root  wheel    96B Jul  8 21:31 share
> 
> root /usr/local # chmod -R go+rx bin
> 
> root /usr/local # ls -lh
> total 0
> -rw-r--r--   1 root  wheel     0B Oct 16 14:11 .com.apple.installer.keep
> drwxr-xr-x  16 root  wheel   512B Nov 14 16:35 bin
> drwxr-xr-x   3 root  wheel    96B Nov 14 16:35 lib
> drwxr-xr-x   4 root  wheel   128B Sep 21 13:37 opt
> drwxr-xr-x   3 root  wheel    96B Jul  8 21:31 share
> 
> root /usr/local # ls -lh bin
> total 24
> -rwxr-xr-x  1 root  wheel   525B Oct 28 09:45 bundle
> -rwxr-xr-x  1 root  wheel   526B Oct 28 09:45 bundler
> lrwxr-xr-x  1 root  wheel    62B Nov 14 16:35 com.docker.cli -> /Applications/Docker.app/Contents/Resources/bin/com.docker.cli
> lrwxr-xr-x  1 root  wheel    54B Nov 14 16:35 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
> lrwxr-xr-x  1 root  wheel    77B Nov 14 16:35 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose
> lrwxr-xr-x  1 root  wheel    73B Nov 14 16:35 docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop
> lrwxr-xr-x  1 root  wheel    75B Nov 14 16:35 docker-credential-ecr-login -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-ecr-login
> lrwxr-xr-x  1 root  wheel    77B Nov 14 16:35 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
> lrwxr-xr-x  1 root  wheel    67B Nov 14 16:35 hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
> lrwxr-xr-x  1 root  wheel    55B Nov 14 16:35 kubectl -> /Applications/Docker.app/Contents/Resources/bin/kubectl
> lrwxr-xr-x  1 root  wheel    55B Nov 14 16:35 kubectl.docker -> /Applications/Docker.app/Contents/Resources/bin/kubectl
> -rwxr-xr-x@ 1 root  wheel   2.5K Jan 31  2020 mountesp
> lrwxr-xr-x  1 root  wheel    54B Nov 14 16:35 notary -> /Applications/Docker.app/Contents/Resources/bin/notary
> lrwxr-xr-x  1 root  wheel    65B Nov 14 16:35 vpnkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit
> root /usr/local # 
> ```

Thank U 4 the solution!!! homebrew did help!
