### ISSUE TITLE
Cannot start docker  on reboot -Mac

### ISSUE THREAD

**Issue by jimzucker** [docker/for-mac#506]
I was setting up a set of containers for a new project, everything was going OK til I forgot to pass a -d to compose and I did a control-C then I have been having problem and cannot get the containers to run.  Now after restarting I cant get the docker itself to run..  Need to figure out how to start with a clean slate.

### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: B22742E9-6EA0-4C87-987D-724DB69E9238
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Sierra related issues are mainly resolved in beta 25: https://download.docker.com/mac/beta/Docker.dmg 

Stable should be releasing soon. 

If you still run into problems, please report, and we will look into it 

Thank you for using Docker!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
