### ISSUE TITLE
gRPC FUSE 

### ISSUE THREAD

**Issue by jic518** [docker/for-mac#5065]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 7AAEC63E-79CF-4B17-9EA1-FB008C663C8D/20201115013021

### Expected behavior
The C++ files consistently compiles within the mounted volume from MacOS and are able to use sockets.
### Actual behavior
The compiler behaves inconsistently (where it will sometimes compile, and where it will sometimes throw a obscure error)

`/usr/bin/ld: warning: size of symbol `' changed from 7 in obj64/server_storage.o to 82 in obj64/server_storage.o
/usr/bin/ld: obj64/server_storage.o: in function `no symbol':
:(.text+0xb10): multiple definition of `no symbol'; obj64/server_storage.o::(.text+0xb10): first defined here
/usr/bin/ld: obj64/server_storage.o: in function `no symbol':
`

problem also occurs when trying to use the socket when the program is compiled and run from the mounted volume.

The program compiles and runs successfully when it is compiled outside of the mounted volume within the docker container.

### Information

  - macOS Version: 11.0.1 Big Sur and multiple versions of Catalina

### Diagnostic logs

```
Docker for Mac: version... 2.5.0.1

```

### Steps to reproduce the behavior

  1. ... disabling gRPC FUSE fixed the issue (it was enabled by default I presume after the update)
  2. ...
**Docker file**
`#initialize repos and upgrade the base system
RUN apt-get update -y
RUN apt-get upgrade -y

#Install additional software needed for development
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y git man curl build-essential screen gdb libssl-dev psmisc valgrind

# Install Python.     
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3.5 \
        python3-pip \
        && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

#Change the working directory:
WORKDIR "/root"`

**Comment by stephen-turner** [comment]
@jic518 Thanks for the report. @djs55 PTAL.
