### ISSUE TITLE
Docker Not Working after Big Sur Update

### ISSUE THREAD

**Issue by basantsingh-os** [docker/for-mac#5068]
- [yes] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: Deadlock occurred system hangs after pressing upload button of Diagnostics

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...
Unable to check 
Both latest stable and edge on official website on 14th nov 2020

```

### Steps to reproduce the behavior

  1. ...
![Screenshot 2020-11-15 at 12 12 26 AM](https://user-images.githubusercontent.com/63092458/99184559-bd8b3b80-2769-11eb-8f86-a2670b3e7dbc.png)

  2. ...![Screenshot 2020-11-15 at 6 03 10 PM](https://user-images.githubusercontent.com/63092458/99184982-e9f48700-276c-11eb-984b-b29272bda819.png)

**Comment by Frank-Jin54** [comment]
I also has the same problem

Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 11.0.1 (build: 20B29)
logs: /tmp/764394D5-3EF3-4FAC-8034-448C40812BD2/20201114-230746.tar.gz
failure: com.docker.vpnkit is not running
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/frankjin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/frankjin/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/frankjin/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/frankjin/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/frankjin/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk

**Comment by ebriney** [comment]
Hi @basantsingh-os and @Frank-Jin54 .
You must use the latest version: https://desktop.docker.com/mac/stable/49550/Docker.dmg

**Comment by mudassir-ahmed** [comment]
It works for me. However, docker is really slow after the update. Simple commands like `docker ps` take a long time to run. Prior to the Big Sur update, these commands were instant.

**Comment by OnnoH** [comment]
After the Bug Sur upgrade Docker stops after startup with the following error:
![Screenshot 2020-11-16 at 11 41 54](https://user-images.githubusercontent.com/11159729/99243729-5e790580-2801-11eb-88ef-b51f4b2c18d8.png)

Resetting seems to end up in an endless loop. No help there.

Downloading and installing the latest (thanks @ebriney ) did work for me. And with a responsive API. No delays in commands whatsoever.

**Comment by owen-bick** [comment]
Just downloaded and installed Docker about 5 minutes ago and I'm getting the same error. I'm on the latest public release of Big Sur

**Comment by J00MZ** [comment]
Had issues with many versions, only one that worked for me was [this](https://hub.docker.com/editions/community/docker-ce-desktop-mac/)

**Comment by ebriney** [comment]
@owen-bick : when the error is displayed, can you open terminal and use this command:
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
at the end it will give a diagnostic id, just past it here please.

**Comment by tplueer** [comment]
I had the same problem with docker installed via homebrew. After the upgrade to big sur i got the segmentaion violation exception.

For me the solution was to completly remove all traces of docker with `brew uninstall docker` and **reinstall** it.

```bash
🌵 >docker --version
Docker version 19.03.13, build 4484c46d9d

🌵 >brew cask info docker
docker: 2.5.0.1,49550 (auto_updates)
https://www.docker.com/products/docker-desktop
/usr/local/Caskroom/docker/2.5.0.1,49550 (120B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/docker.rb
==> Names
Docker Desktop
Docker Community Edition
Docker CE
==> Description
App to build and share containerized applications and microservices
==> Artifacts
Docker.app (App)
==> Analytics
install: 18,432 (30 days), 50,915 (90 days), 215,246 (365 days)
```

**Comment by owen-bick** [comment]
@ebriney Here's the ID: A1BACCBE-3493-4716-AA7A-0779769A2BDA/20201117202538

**Comment by Frank-Jin54** [comment]
thanks for your replying

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dWhisper** [comment]
Seeing the same issue, fresh download of the latest package.

Diagnostics ID:     33E837D6-0A25-4245-8BA2-AB8CA0E75359/20201118203816 (uploaded)

**Comment by jaraco** [comment]
This issue was reported in #4699, but it appears not to have been fully addressed. I was using Docker just fine on Big Sur, then installed an update when prompted by Docker. Coincidentally, I also updated Virtualbox and restarted the computer. After restarting the OS and logging in, the "Segmentation violation" error appeared.

**Comment by basantsingh-os** [comment]
I deleted cache and other docker files in ~/Library directory now docker is working.

**Comment by basantsingh-os** [comment]
I deleted docker files in ~/Library & cache of all apps. Now docker is running. Thanks everyone

**Comment by ebriney** [comment]
@owen-bick your `~/.docker` directory has been created with a sudo and so app cannot create anything inside
delete it with `sudo -rm ~/.docker` then relaunch Docker.app

**Comment by ebriney** [comment]
Same for you @dWhisper delete `~/.docker`, restart

**Comment by owen-bick** [comment]
@ebriney Doesn't seem to work... here's what I get after I type in `sudo -rm ~/.docker`

```
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] file ...
```

**Comment by michaelkamprath** [comment]
@owen-bick  try removing the `-` before the `rm` in your command. I realize it's what @ebriney typed, but it's a typo. Also, since its a directory, adding the `-Rf` option to `rm` would be helpful. So in all: `sudo rm -Rf ~/.docker`.

**Comment by owen-bick** [comment]
@michaelkamprath Looks like `sudo rm -Rf ~/.docker` seems to do the trick. Thanks everyone

**Comment by ebriney** [comment]
Oh yes sorry @owen-bick, wrong copy paste
