### ISSUE TITLE
Docker checks for updates even though that option is deactivated

### ISSUE THREAD

**Issue by rowild** [docker/for-mac#5073]
MacOS 10.13.6

On every start-up of my computer, I get a warning dialog that there is a new version availabe, but that version does not support my MacOS. I should update my MacOS.

The reason why this troubles me is that I deactivated "Check for updates automatically", which quite obviously is ignored. Why is it doing so? This really should not happen and tells me that Docker sends data to its "mother" without having the right to do so.

**Comment by dimkalinux** [comment]
I can confirm this bug. Even when my computer wake up from sleep it show me this message TWICE.
![Screen Shot 2020-11-25 at 10 26 56 AM](https://user-images.githubusercontent.com/30550/100201815-2ceef100-2f09-11eb-870d-090fc7e8c9b1.png)
