### ISSUE TITLE
Internal error: failed to update machine migration state

### ISSUE THREAD

**Issue by jimzucker** [docker/for-mac#508]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 497982F9-E3EA-4047-A1F9-D07F360DE7E1
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/jaz/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jaz/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/jaz/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/jaz/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/jaz/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by Piasy** [comment]
+1

Diagnostic ID: F6539FD7-C07F-464C-9F64-BFEA4F4F38ED
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/piasy/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/F6539FD7-C07F-464C-9F64-BFEA4F4F38ED/20160904-173010/qemu-img-check.stdout 2> /tmp/F6539FD7-C07F-464C-9F64-BFEA4F4F38ED/20160904-173010/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/piasy/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/piasy/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/piasy/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/piasy/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/piasy/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

**Comment by brettvitaz** [comment]
Please help? Running macOS Sierra (10.12)

```
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A320)
logs: /tmp/0DAA4810-D8D6-4531-AFC5-15646DA41131/20160908-154625.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/vitazbt/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/vitazbt/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/vitazbt/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/0DAA4810-D8D6-4531-AFC5-15646DA41131/20160908-154625/qemu-img-check.stdout 2> /tmp/0DAA4810-D8D6-4531-AFC5-15646DA41131/20160908-154625/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/vitazbt/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/vitazbt/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/vitazbt/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/vitazbt/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/vitazbt/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
```

**Comment by brettvitaz** [comment]
The newest docker version 1.12.1-beta25 seems to work ok!

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
