### ISSUE TITLE
Publish binaries for Docker CLI only (to help on Apple Silicon)

### ISSUE THREAD

**Issue by ItalyPaleAle** [docker/for-mac#5080]
We understand that, at the moment, Docker Desktop cannot run on Mac with Apple Silicon (https://github.com/docker/roadmap/issues/142)

As an interim solution, and maybe even for long-term, would you consider publishing the Docker CLI as a standalone binary? This way, even though we won't be able to use Docker Desktop on Mac, we would at least be able to connect to a remote Docker host and still leverage Docker.

**Comment by dgdosen** [comment]
could you install docker-machine?

**Comment by ItalyPaleAle** [comment]
@dgdosen that's another separate binary right? If that could be made available... Then we could use `docker-machine` to use Docker on a remote host I assume

**Comment by makeable** [comment]
As an interim:

Im using the x86 version of the CLI from https://download.docker.com/mac/static/stable/x86_64/
Works fine via rosetta.

**Comment by rene-mueller** [comment]
@makeable how do you start the containers when the daemon is not running?

**Comment by makeable** [comment]
I have a remote docker host. i.e. this download is just for the client - it then connects to a remote host running the docker engine.

I do this using the DOCKER_HOST env var, but you can set a config for the same effect:
https://docs.docker.com/engine/reference/commandline/cli/

Env Var looks like this:
DOCKER_HOST=ssh://myusername@thedockerhostaddress

**Comment by fayep** [comment]
I have taken the upstream containers and produced a toolchain which can target Apple Silicon.

https://twitter.com/beiriannydd/status/1330993041126039553?s=20

It produced a signed arm64 binary which works without modification using the SSH style DockerHost above.
In order to make it work, I had to drag the build chain into the present Golang 1.13 to the CL which fixes the signing issue and latest osxcross.  Apart from that it was pretty smooth sailing.  I managed to build linuxkit too but I didn’t manage to get a kernel downloaded from the remote docker instance.  I might need to do this on my Pine64.

**Comment by fayep** [comment]
![8F836956-99B4-4AAC-BB23-D57124EA14F2](https://user-images.githubusercontent.com/565311/100165681-ba7e0280-2e6f-11eb-9d3a-901d24373489.jpeg)

**Comment by fayep** [comment]
If anyone else is trying this, it appears you need to pass Virtualization.framework an uncompressed kernel image, it's also unclear to me which Entitlements are required.  I managed to run a readonly arm64 linux image using https://github.com/KhaosT/SimpleVM against an ubuntu 20.04 live server install with the kernel uncompressed.  You can also ssh into that VM.  I was unable to run the linuxkit VM even after uncompressing the kernel.

**Comment by fayep** [comment]
`00000000: 4d5a 0091 ffbf 4e14 0000 0800 0000 0000  MZ....N.........
00000010: 0040 dd01 0000 0000 0a00 0000 0000 0000  .@..............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 4152 4d64 4000 0000  ........ARMd@...
00000040: 5045 0000 64aa 0200 0000 0000 0000 0000  PE..d...........
00000050: 0000 0000 a000 0602 0b02 0214 0060 4c01  .............`L.
00000060: 00d0 9000 0000 0000 0463 3b01 0010 0000  .........c;.....
00000070: 0000 0000 0000 0000 0010 0000 0002 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
`

**Comment by tmm1** [comment]
@fayep What happens when you try running the Linuxkit VM?

**Comment by fayep** [comment]
Hyperkit wasnt built so I cant use the linuxkit vm in linuxkit. I tried to load it in SimpleVM which can run an Ubuntu install CD for ARM64 if you decompress the kernel.  With no output, it is hard to see what is wrong.

**Comment by fayep** [comment]
I got something!

`faye@M1ni linuxkit % cat linuxkit-cmdline 
console=tty0 console=ttyS0 console=ttyAMA0%                                    faye@M1ni linuxkit % vftool -k vmlinux -i linuxkit-initrd.img -a "console=hvc0 console=tty0 console=ttyS0 console=ttyAMA0"
2020-11-26 12:56:12.095 vftool[42708:1164302] vftool (v0.1 25/11/2020) starting
2020-11-26 12:56:12.095 vftool[42708:1164302] +++ kernel at vmlinux -- file:///Users/faye/src/virtual/linuxkit/, initrd at linuxkit-initrd.img -- file:///Users/faye/src/virtual/linuxkit/, cmdline 'console=hvc0 console=tty0 console=ttyS0 console=ttyAMA0', 1 cpus, 512MB memory
2020-11-26 12:56:12.095 vftool[42708:1164302] +++ fd 3 connected to /dev/ttys002
2020-11-26 12:56:12.095 vftool[42708:1164302] +++ Waiting for connection to:  /dev/ttys002
2020-11-26 12:56:15.398 vftool[42708:1164302] +++ Configuration validated.
2020-11-26 12:56:15.398 vftool[42708:1164302] +++ canStart = 1, vm state 0
2020-11-26 12:56:15.591 vftool[42708:1164304] +++ VM started
`

`[    0.646430] Key type encrypted registered
[    0.646465] ima: No TPM chip found, activating TPM-bypass!
[    0.646501] ima: Allocated hash algorithm: sha256
[    0.646555] ima: No architecture policies found
[    0.646605] evm: 
 EVM extended attributes:
[    0.646645] evm: security.ima
[    0.646694] evm: security.capability
[    0.646717] evm: HMAC attrs: 0x1
[    0.646838] hctosys: unable to open rtc device (rtc0)
[    0.647635] Freeing unused kernel memory: 4096K
[    0.649769] Run /init as init process

Welcome to LinuxKit

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
          {                       /  ===-
           \______ O           __/
             \    \         __/
              \____\_______/
`

**Comment by tckb** [comment]
@fayep  I am trying to decode how you managed to built the native arm64 of docker cli. I built `golang` using the bootstrap cross-compiled on my intel mac.  go runs natively on my m1, need some tips on building the same for docker-cli. 

for my remote docker, I cross-compiled qemu to start an arm linux locally, will install docker-daemon there.

**Comment by fayep** [comment]
I built the changelist for a linux x86 host (tip works now) and I then made
a golang cross for x86 with the same golang.  I made the docker build for
docker cli use my golang and added darwin arm64 - you can see the history
of the containers in my repo to follow what changes I made from the docker
versions.

**Comment by stephen-turner** [comment]
We now have (a preview of) Docker Desktop for M1. See https://docs.docker.com/docker-for-mac/apple-m1/
