### ISSUE TITLE
~1.5ms extra latency per postgres query under docker

### ISSUE THREAD

**Issue by twk** [docker/for-mac#5086]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:AE00CA77-4CE2-402E-A569-C95F638B2F95/20201127181146

### Expected behavior
The per-query latency of postgres running in docker on my dev laptop is closer to the latency of running postgres outside of docker. 

### Actual behavior
Under `pgbench` I'm seeing ~1.5 milliseconds of additional latency per query compared to running a copy of postgres I 
downloaded from https://postgresapp.com/

Maybe this is completely expected and normal, but this causes my test suite to run about 3x slower when using a dockerized database than using a native database, so I just wanted to flag it. I'm actually seeing something closer to 3ms of overhead per query in my test suite, but pgbench is the simplest way to demonstrate a difference. 

For context, a lot of the queries my tests run take 0.1 ms, so this is a significant amount overhead. 

### Information
This is on catalina, and it seems very reproducible.

Here's the pgbench output under docker:
```
$ pgbench -h localhost -U postgres --select-only --time=5 postgres
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 3187
latency average = 1.569 ms
tps = 637.195446 (including connections establishing)
tps = 638.807746 (excluding connections establishing)
```

Compared to the output when running the native binary I downloaded from postgresapp.com:

```
$ pgbench -h localhost -U postgres --select-only --time=5 -p 5433 postgres
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 44347
latency average = 0.113 ms
tps = 8869.154601 (including connections establishing)
tps = 8877.434536 (excluding connections establishing)
```

Under docker I'm seeing 1.569 ms per query, compared to 0.113 ms running outside of docker.   

### Diagnostic logs
```
Docker for Mac: 2.5.0.1
```

### Steps to reproduce the behavior
To set up the test under docker:
`docker run --name perf_test -e POSTGRES_PASSWORD=example -p 5432:5432 postgres:12`
`pgbench -i -h localhost -U postgres -p 5432 postgres`

Let me know if I can help make this issue more clear!  I love the convenience of running my tests with the database in docker, but this is a huge amount of overhead for my test suite.

**Comment by theodorton** [comment]
I ran the same benchmark in a linux environment and I got the following results:

```
$ docker run --name perf_test -e POSTGRES_PASSWORD=example -p 5555:5432 postgres:12
$ pgbench -i -h localhost -U postgres -p 5555 postgres
$ pgbench -h localhost -U postgres --select-only --time=5 -p 5555 postgres                                                                                                  
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 72251
latency average = 0.069 ms
tps = 14450.067528 (including connections establishing)
tps = 14456.602037 (excluding connections establishing)
```

Here's the same benchmark running from a MacBook Pro on the same network:

```
$ pgbench -h $DATABASE_IP -U postgres --select-only --time=5 -p 5555 postgres
Password:
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 19154
latency average = 0.261 ms
tps = 3830.091433 (including connections establishing)
tps = 3832.446419 (excluding connections establishing)
```

Which makes sense, as the ping to that machine is around 0.2ms. Here's the benchmark running the container locally with Docker for Mac:

```
$ pgbench -h localhost -U postgres --select-only --time=5 -p 5555 postgres
Password:
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 2142
latency average = 2.337 ms
tps = 427.926713 (including connections establishing)
tps = 429.549733 (excluding connections establishing)
```

I would expect the local connection to be as fast as a connection going over the network to a remote database.

**Comment by ckcollab** [comment]
Docker for mac filesystem is very slow, which could be playing a part in this.. but, I assume postgres has most of this stuff in memory so that may not make sense..

**Comment by twk** [comment]
I noticed that we are major version past where I filed this bug, so I decided to retest with Docker 3.3.0 (62916).  

```
$ pgbench -h localhost -U postgres --select-only --time=5 postgres
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 3702
latency average = 1.351 ms
tps = 740.137403 (including connections establishing)
```

So it looks a bit faster (thank you!) but still significantly slower than what I would see in production or even just running a native binary.  FWIW, the native binary speeds don't seem to have changed:
```
$ pgbench -p 5433 -h localhost -U postgres --select-only --time=5 postgres
starting vacuum...end.
transaction type: <builtin: select only>
scaling factor: 1
query mode: simple
number of clients: 1
number of threads: 1
duration: 5 s
number of transactions actually processed: 45052
latency average = 0.111 ms
tps = 9003.257858 (including connections establishing)
tps = 9010.828643 (excluding connections establishing)
```
