### ISSUE TITLE
how can i find vm‘s tty？

### ISSUE THREAD

**Issue by arrowfeng** [docker/for-mac#5087]
### Information

```
macOS Version: Big Sur
Docker for Mac: 2.5.0.1
```
 I find that there is no tty file at `~/Library/Containers/com.docker.docker/Data/vms/0`

**Comment by stephen-turner** [comment]
@arrowfeng Have a look at https://github.com/justincormack/nsenter1. Although we would not normally expect people to need to look at the VM's terminal: you should normally treat it as a black box. What is your use case?

**Comment by arrowfeng** [comment]
thank you, I'm just curious how to get in through tty.
