### ISSUE TITLE
Uninstall docker on mac with M1

### ISSUE THREAD

**Issue by TonyLianLong** [docker/for-mac#5097]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics: docker does not work
  - Diagnostics ID:

### Expected behavior
I can uninstall.

### Actual behavior
I can't.

### Information

I restored a backup from an Intel Mac to a Mac with M1.

Docker is not supported on M1 Mac. However, the typical way to uninstall it by opening preference does not work since the docker desktop itself doesn't work and quits on Mac M1.

### Steps to reproduce the behavior
Restore a backup. Then open Docker to uninstall.

**Comment by stephen-turner** [comment]
Hmmm, that's an interesting use case we hadn't thought about. I think this won't work until we have a working version on M1 chips.

**Comment by TonyLianLong** [comment]
Any suggestions on how to uninstall through command line? The docker app isn't working and asks me to exit.

**Comment by TonyLianLong** [comment]
What's more, since I open Docker for the first time, it now automatically starts when I boot. There is no way to stop that. I think Docker for Mac team really needs to handle this.

**Comment by stephen-turner** [comment]
Well, you can drag the application folder into the trash in the normal way.
