### ISSUE TITLE
Docker has been updated notification on every start

### ISSUE THREAD

**Issue by themccallister** [docker/for-mac#51]
### Expected behavior
Not to see that Docker has been updated notification on every boot.

### Actual behavior
Each time Docker for Mac starts I see the following notification.
![screen shot 2016-08-01 at 8 02 24 am](https://cloud.githubusercontent.com/assets/5354908/17293475/7e84811e-57be-11e6-9104-c418b88a288a.png)

**Note**:  I switched from the Beta to Stable release using an in-place upgrade (e.g did not uninstall Docker for Mac before installing the stable package).

### Information

Diagnostic ID: 794E1C65-4D46-447A-BD5E-297BC892F8A8
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Quit Docker for Mac
2. Open Docker for Mac

**Comment by knutsenm** [comment]
In #169, @dsheets says, "We are working on a fix which will reach the beta channel first and then stable with 1.12.1."

**Comment by knutsenm** [comment]
> In #169, @dsheets says, "We are working on a fix which will reach the beta channel first and then stable with 1.12.1."

No good; 1.12.1 does the same thing.

**Comment by themccallister** [comment]
I'm no longer receiving this error, which is most likely due to an attempted upgrade to Sierra and seeing how broken Docker was - then wiping my drive clean and reinstalling OS X.

This issue may still occur, but I might not be the best source of troubleshooting anymore.

**Comment by knutsenm** [comment]
I have not upgraded to Sierra. Current diagnostics are:

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
...and all is "[OK]"

I can provide additional info if needed.

I notice that /Library/PrivilegedHelperTools/com.docker.vmnetd remains even after quitting Docker; could that be related?

**Comment by joshuatalb** [comment]
Having the same problems as @knutsenm. Updated to 1.12.1 earlier today but still having the issue. It's starting to get a bit annoying now - is there not even a temporary fix that we can put in place until it's 100% fixed?

**Comment by knutsenm** [comment]
I switched back to the beta channel. The problem appears to be gone in Version 1.12.1-beta26.1 (build: 12100), but I'm not certain if that's due to the version, or to the channel switch.

**Comment by knutsenm** [comment]
Maybe it was the channel switch. The problem has returned for me with version 1.12.2-rc1-beta27

**Comment by knutsenm** [comment]
@djs55 my /Library/PrivilegedHelperTools/com.docker.vmnetd dates back to 16 Sep, when I switched from Stable back to Beta channel; hasn't been updated with the version 1.12.2-rc1-beta27. Could this be related to these? https://github.com/docker/for-mac/issues/644 https://github.com/docker/for-mac/issues/61 https://github.com/docker/for-mac/issues/8#issuecomment-236183193

**Comment by joshuatalb** [comment]
Completely uninstalling Docker (incl. toolbox, kitematic etc) using AppCleaner, and then re-installing it seems to have fixed it for me. Not sure if this information helps but I came from Docker using Virtualbox, then upgraded to Docker natively for OS X.

**Comment by flynniec6** [comment]
Current have this problem with Version 1.12.2-rc1-beta27 (build: 12496)
179c18cae7. Did not have it on any prior version, and have been installing betas continually.

**Comment by knutsenm** [comment]
The release notes for Version 1.12.2-beta28 (12906) specifically mention:

> Fixed an issue where Docker for Mac was incorrectly reported as updated

Indeed, the problem seems to have gone away.
