### ISSUE TITLE
Docker desktop does not work on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by gmaimone21** [docker/for-mac#5101]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Expected behavior
Download install and use docker desktop on m1 11.0.1

Actual behavior
The programs doesn't start 

Information

Please, help us understand the problem.  For instance:
  - Is it reproducible?
yes, download and install docker desktop on a Macbook air with m1 and 11.0.1
  - Is the problem new?
DK
  - Did the problem appear with an update?
    first time use
  - macOS Version: 11.0.1

A reproducible case, Dockerfiles FTW.

  1. install
  2. run program

**Comment by stephen-turner** [comment]
Docker Desktop runs on Big Sur but not on M1 chips yet. See https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/ for our plans.
