### ISSUE TITLE
 one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 3251)

### ISSUE THREAD

**Issue by MacMillan13** [docker/for-mac#5104]
Good day. Have an error with docker on the MacBook Pro M1.

 One of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 3251)

Please help. Have to work.

<img width="594" alt="Снимок экрана 2020-12-06 в 21 37 42" src="https://user-images.githubusercontent.com/18086617/101290542-ae992580-380b-11eb-8f49-f6768e5e66c5.png">

**Comment by stephen-turner** [comment]
Docker Desktop does not yet run on the M1 chips. See https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/
