### ISSUE TITLE
Desktop pending in 'starting Kubernetes' status for days.

### ISSUE THREAD

**Issue by riversyang** [docker/for-mac#5108]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 98D315CC-9132-4758-BF32-0AF1133FFB31/20201208000532

### Expected behavior

Enable Kubernetes in [Preferences]

### Actual behavior

Kubernetes status pending in 'starting' for days, even if I restart my Mac. And the process `com.docker.hyperkit` keep holding for at least 200% cpu percent. And the UI is also frozen which prevented me from disabling this feature.

### Information

  - macOS Version: 11.0.1
  - Desktop Version: 2.5.0.1 (49550)

### Steps to reproduce the behavior

Simply enable Kubernetes in [Preferences].

**Comment by dgdosen** [comment]
I can see there's only an amd64 version of the docker/desktop-kubernetes image.  

Does M1 Docker need access to an arm64 image?

**Comment by enyo** [comment]
Can confirm.

macOS: `11.0.1`
Docker Preview 7

**Comment by ItsLeeOwen** [comment]
3.1.0... This has happened after every upgrade for the last several updates
