### ISSUE TITLE
Trying to update the wrong daemon.json interface stuck

### ISSUE THREAD

**Issue by MXuDong** [docker/for-mac#5109]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `3d342851-56cf-463b-9753-6213b697ae35/20201208071827`
  - mac version : macOS Catalina 10.15.7

### Expected behavior
In the update error daemon.json file should respond or stop the update, display the error problem, or ignore this update.

### Actual behavior
The user interface is stuck, the CPU occupancy rate rises up to 90%, and then it fails to respond to user operations, and the docker program does not restart.

### Information
It may be a bug. When you click the `Apply & Restart` button, if there is a problem with the daemon.json file (non-syntax problem), the exception will occur. But the daemon file was not overwritten, and docker did not restart.

I guess it might be that DockerTop was caught in a cycle of failing and re-checking when checking the correct file, because of the problem of unresponsiveness and a sharp increase in CPU usage.

But the Docker process did not restart, so the location of the problem occurred approximately before the program checked the daemon file and wrote it.

### Steps to reproduce the behavior
1. Open the docker top for mac.
2. Change UI to `Preferences`.
3. Select `Docker Engine`.
4. Rewrite daemon.json with wrong data, such like this:
  ```json
  {
    "experimental": false,
    "features": {
      "buildkit": true
    },
    "insecure-registriy": [
      "xxx.xx.xxx.xx"
    ]
  }
  ```
5. Click the button: `Apply & Restart`, then you can got result.

**Comment by charlax** [comment]
Same issue, diagnostics id 930EE5C4-6E6E-49BE-8818-CFACE3984FB2/20201216094817

I was just trying to add `http` in front of an insecure registry. This is sufficient to freeze the UI:

```json
{
  "insecure-registries": [
    "http://127.0.0.1:80"
  ]
}
```
