### ISSUE TITLE
Hide tutorial popup and new version updates popups 

### ISSUE THREAD

**Issue by karanshah81295** [docker/for-mac#5114]
Is there a way or any launch arguments where we can suppress the new tutorial , new version update and docker icon in menu bar? 

Our use-case is to run docker on our vm's under the hood with no UI visible on screen . 

OS version : OS X Mojave, Catalina & Big Sur.

**Comment by stephen-turner** [comment]
No, sorry, Docker Desktop can't run headless. It's designed for use in a desktop environment, not a server environment.

**Comment by nebuk89** [comment]
@karanshah81295 what is your underlying usecase here? Are you running Docker Desktop in a CI or somewhere else? if you fancy chatting through it further drop me an email at bengotch@docker.com. Thanks!

**Comment by karanshah81295** [comment]
@nebuk89 , Yes we are running Docker Desktop in a CI environment. 
We expose our vm to our users and want to use docker to run some of the user's command so that it is isolated and can be killed once the user's session is terminated. We want to hide the popup's so that it doesn't interfere with user experience.
