### ISSUE TITLE
How do I disable automatic updates

### ISSUE THREAD

**Issue by Nuru** [docker/for-mac#5119]
With version 3.0.0 we get automatic updates. 

Often I am working toward a deadline and want to defer updates until after the deliverable is delivered. How do I turn off automatic updates?

**Comment by stephen-turner** [comment]
There is no way to do this. It's the same as GitHub Desktop or Chrome: you get the latest version every time you restart.

**Comment by ThomasNegeli** [comment]
Sorry @stephen-turner, but this is not a valid argument for a development environment.
If you are having browser issues, you can switch to a different browser. There are plenty of them out on the market.
If you are having an Issue with a system backing your development workflow, you have to think twice if you updated it to the latest version.
So +1 for the Request of @Nuru

**Comment by citizen-stig** [comment]
Also this is annoying and irritating, that exclamation mark appears in front of the icon.

I try hard to limit number of distractions, but Docker brings one more.

Please understand, that my life is not centred about maintaining Docker. I can update it eventually, but do not force me to do it.

**Comment by SamuelMS** [comment]
> There is no way to do this. It's the same as GitHub Desktop or Chrome: you get the latest version every time you restart.

Please consider reverting this, or giving users control again. Docker updates can include breaking changes – in the Mac app itself, in compose and other tooling, etc. This adds potential instability to my development environment between restarts and is not healthy behavior.

Google Chrome is a web browser: it shows me pictures of cute cats and lets me talk to friends. GitHub Desktop is a visual layer on top of git (which does _not_ auto-update unless you want it to). As you well know, Docker for Mac is an operating system in a box and is orders of magnitude more complex.
