### ISSUE TITLE
Kitematic issue

### ISSUE THREAD

**Issue by TJ-C** [docker/for-mac#512]
### Steps to reproduce
1. Open Kinematic from docker menu
### Expected behavior

Tell us what should happen
Kitematic should open 
### Actual behavior

Tell us what happens instead
Response is a dialog displaying the following:

Kitematic needs to be updated.
Installed version: 0.10.2 - Required version: 0.10.4
You can download the most recent version here. (make sure you install it in /Applications) 

Clicked on the download (here) link, and copied to the applications folder. Issue is still present.
the dialog still says I have 0.10.2 despite the new version of Kitematic installed is 0.12.0
### Information

```
Diagnostic ID: DFCFFED0-F4A8-4A7E-A95B-95E69A7562C0
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by ijc25** [comment]
@TJ-C thanks for your report and sorry for the delay in getting back to you.

I believe this issue was fixed in a subsequent stable release some time ago. I've just tried it myself with beta30 where it is also fine.

Can you reproduce this issue with the latest stable (1.12.3 at time of writing)? I'm going to assume yes and close this issue now but if not then please do reopen (with a new diagnostic upload from the new version please).

Thanks.
Ian.

**Comment by tomory** [comment]
You might want to reopen this. It's currently an issue for me. The details:

MacOS 10.14.6 (18G84)
Docker Desktop Community 2.1.0.1 (37199)
Kitematic 0.17.6
Engine: 19.03.1
Compose: 1.24.1
Kubernetes: v1.14.3
Notary: 0.6.1
Credential Helper: 0.6.3
Machine: 0.16.1

When I choose Kitematic from the Docker menubar app, it displays a dialog like this:

    Kitematic
    Kitematic needs to be updated.
    Installed version: 0.17.5 - Required version: 0.17.6
    You can download the most recent version here. (make sure you install it in /Applications)

**Comment by Nickeysoft** [comment]
> You might want to reopen this. It's currently an issue for me. The details:
> 
> MacOS 10.14.6 (18G84)
> Docker Desktop Community 2.1.0.1 (37199)
> Kitematic 0.17.6
> Engine: 19.03.1
> Compose: 1.24.1
> Kubernetes: v1.14.3
> Notary: 0.6.1
> Credential Helper: 0.6.3
> Machine: 0.16.1
> 
> When I choose Kitematic from the Docker menubar app, it displays a dialog like this:
> 
> ```
> Kitematic
> Kitematic needs to be updated.
> Installed version: 0.17.5 - Required version: 0.17.6
> You can download the most recent version here. (make sure you install it in /Applications)
> ```

Try to uninstall Kitematic and restart your Docker Desktop. My problem was solved after restart my Docker Desktop.
