### ISSUE TITLE
Display problem on Dashboard

### ISSUE THREAD

**Issue by gno72** [docker/for-mac#5121]
After today update of Docker I have the problem with displaying Containers/Apps.
Moving mouse causes screen "digitalising" like in the Mattrix ;) 
I've attached the screenshot.
Workstation: MacBook Pro, system: macOS Big Sur
![image](https://user-images.githubusercontent.com/75837788/101895718-308ca400-3ba8-11eb-8dec-a8ef48e919b4.png)
Docker version and configuration on below screenshot
![image](https://user-images.githubusercontent.com/75837788/101895957-88c3a600-3ba8-11eb-9c6b-db69a1c2eeb0.png)
It appears only on Container/Apps

**Comment by stephen-turner** [comment]
That's really odd. I don't know what to suggest. It looks like when a graphics card is dying, but why would it only be on that screen? And we haven't had any other reports of it.

**Comment by vladgelevera** [comment]
I was facing same issue in Google Chrome. Some sites or elements was with green lines. Can suggest it is not Docker problem.

**Comment by piroux** [comment]
Does Docker-for-mac uses Skia ?

**Comment by stephen-turner** [comment]
@piroux No

**Comment by jimpass** [comment]
Does anybody have an idea on this?  This started showing up today on my Mac out of the blue. I don't think anything changed as far as OS or Docker desktop.

**Comment by ehontoria** [comment]
Seeing a similar issue on Catalina 10.15.4

<img width="1246" alt="Screen Shot 2021-02-19 at 1 56 00 PM" src="https://user-images.githubusercontent.com/46453590/108548690-34c8f200-72ba-11eb-8a85-3607a180fbb0.png">

**Comment by stephen-turner** [comment]
There is a proposed solution in #5207.

**Comment by coffee4dev** [comment]
Experienced it just now for 1st time. 

Big Sur v11.2, MacBook Pro 16" 2019, AMD Radeon Pro 5500M 4 Gb, Intel UHD Graphics 630 1536 Mb

Had such glitches in Chrome, disabling GPU hardware acceleration helped.
Are there any solutions for this issue?

**Comment by mm-gmbd** [comment]
Running  Catalina 10.15.7 (19H1217) on 2019 MBP 16-inch with following specs:

- Processor: 2.6 GHz 6-Core Intel Core i7
- Memory: 64 GB 2667 MHz DDR4
- Graphics:
  - AMD Radeon Pro 5300M 4 GB
  - Intel UHD Graphics 630 1536 MB

I've got the blue lines, but interestingly it's only on the Containers/Apps tab.

![image](https://user-images.githubusercontent.com/3329824/124765782-50990180-df04-11eb-8c06-2ced60a34d55.png)

Docker Desktop version details below:

![image](https://user-images.githubusercontent.com/3329824/124765884-68708580-df04-11eb-8853-f71fbbb5698f.png)

**Comment by trungutt** [comment]
Hi everyone, thank you for these reports. Could you please try this build and let us know if the problem is still there. Please set the global environment variable `DOCKER_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` and then relaunches Docker Desktop

Mac Intel
https://desktop-stage.docker.com/mac/stable/amd64/66795/Docker.dmg

Mac M1
https://desktop-stage.docker.com/mac/stable/arm64/66795/Docker.dmg

**Comment by mm-gmbd** [comment]
Downloaded and running with the env variable set, blue lines in [my previous comment](https://github.com/docker/for-mac/issues/5121#issuecomment-875597000) are no longer showing on the **Containers / Apps** tab. Woohoo!

That being said, they weren't *always* present, so I'll keep an eye on it and be sure to update the thread if the lines show up at any point.

**Comment by trungutt** [comment]
Thank you @mm-gmbd 
We'll address this issue in the next release of Docker Desktop and will give you instruction how to enable/disable hardware acceleration for Docker Desktop dashboard

**Comment by ulyssessouza** [comment]
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.
