### ISSUE TITLE
Docker Desktop Preview 5 cannot start when Buddhist calendar set

### ISSUE THREAD

**Issue by lifez** [docker/for-mac#5126]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
- Docker Desktop can start properly

### Actual behavior

- Docker Desktop cannot start

### Information
<img width="666" alt="Screen Shot 2563-12-12 at 21 01 09" src="https://user-images.githubusercontent.com/2588927/101999314-3c927600-3d0e-11eb-9684-73388b3b11f6.png">

  - macOS Version: 11.0.1

### Steps to reproduce the behavior

  1. Set "Buddhist" value on Calendar
  2. Docker Desktop will not start
  3. Set "Gregorian" value on Calendar
  4. Docker Desktop start properly
  
<img width="780" alt="Screen Shot 2563-12-13 at 06 42 32" src="https://user-images.githubusercontent.com/2588927/101999327-63e94300-3d0e-11eb-9d2a-b86d0cb447fc.png">

**Comment by stephen-turner** [comment]
Thanks for the report, we'll fix it.

**Comment by lifez** [comment]
If I could contribute this. I would

**Comment by djs55** [comment]
@lifez thanks for the report and the repro instructions. I confirm that the issue reproduces locally for me.

**Comment by djs55** [comment]
@lifez the new build linked here should fix the problem: https://www.docker.com/blog/download-and-try-the-tech-preview-of-docker-desktop-for-m1/ -- let me know if not.

Thanks again for the report!
