### ISSUE TITLE
Validate `~/Library/Containers/com.docker.docker` was created for current architecture

### ISSUE THREAD

**Issue by tonistiigi** [docker/for-mac#5128]
Reported in dev-preview feedback by @milkcocoa

> I used Migration Assistant to copy files from the Intel machine, so I needed to remove  ~/Library/Containers/com.docker.docker/. Without that, Docker seems to freeze to start the VM.

As Migration Assistant can now be used to move between M1 and Intel and vice versa we should validate the contents and clear the initial state if needed.

@djs55

**Comment by stephen-turner** [comment]
Related to #5097.

**Comment by irvv17** [comment]
Hi, I have a similar issue, and the only way I could remove docker was using the Clean My Mac app.
