### ISSUE TITLE
Invalid JSON On Boot after Apple Mac Security Update 2016-001

### ISSUE THREAD

**Issue by freimer** [docker/for-mac#513]
Receive error on boot-up after installing Apple Security Update 2016-001 about "invalid json" or something to that effect.

 !- Thanks for reporting issues back to Docker! This is the issue tracker of Docker for Mac, please check first that your issue is not already described in our troubleshooting guide available at https://docs.docker.com/docker-for-mac/troubleshoot/#/troubleshooting To make it possible for us to help you, please fill out below information carefully. -> ### Steps to reproduce 1. 2. 3. ### Expected behavior Tell us what should happen ### Actual behavior Tell us what happens instead ### Information     Diagnostic ID: 697A6332-192E-432D-86B4-D8841D008B23 Docker for Mac: 1.12.1-beta24  Build 11525  macOS: Version 10.11.6  Build 15G1004   OK  docker-cli  OK  virtualization kern.hv_support  OK  menubar  OK  moby-syslog  OK  dns  OK  disk  OK  system  OK  app  OK  osxfs  OK  virtualization VT-X  OK  db  OK  slirp  OK  logs  OK  env  OK  vmnetd  OK  moby-console  OK  moby  OK  driver.amd64-linux

**Comment by mchiang0610** [comment]
This should be fixed in beta 25. 

Thanks!
