### ISSUE TITLE
Infinite docker starting OSX

### ISSUE THREAD

**Issue by vsilent** [docker/for-mac#5131]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
B498DD82-ACFD-4E30-9A8B-18051E0FEE3A/20201214194445
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

---

EDIT by @tiborvass:

See 🚧 Workaround 🚧 : https://github.com/docker/for-mac/issues/5131#issuecomment-748692772

**Comment by jamesstidard** [comment]
Hi, I'm experiencing the same issue. Noticed it about a day ago. Running `3.0.1` on macOS `10.15.7`. I also have a laptop running `3.0.1` on macOS `10.16` which doesn't seem to have any issues.

Here's my diagnostics ID if you want to compare with @vsilent `DF9C1FDB-F5BD-41BF-9585-CF43DE1C199C/20201215093430`

**Comment by Ky6uk** [comment]
Same issue after upgrading to `v3.0.1`

`C1E3D580-6312-45F9-8E7F-B7D86211FCF9/20201215102214`

**Comment by vsilent** [comment]
Of course, removing all images and containers fixes the issue, but this is bad solution for those who have a lot of important data in volumes.

**Comment by p-vernaeckt** [comment]
Same issue here...

**Comment by nex2hex** [comment]
In logs https://docs.docker.com/docker-for-mac/troubleshoot/#check-the-logs 

```
2020-12-15 19:06:24.337028+0500  localhost com.docker.driver.amd64-linux[3183]: cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
2020-12-15 19:06:35.343660+0500  localhost com.docker.driver.amd64-linux[3183]: cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
2020-12-15 19:06:46.344376+0500  localhost com.docker.driver.amd64-linux[3183]: cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
```

**Comment by nex2hex** [comment]
As a temporary solution, you can downgrade to 2.5.0.1 https://desktop.docker.com/mac/stable/49550/Docker.dmg

**Comment by JustinHallquist** [comment]
Experiencing immediately after applying docker's update:

```
OSX 10.14.6
D712EACC-907E-44B5-9197-9C4A15C99737/20201215201111

2020-12-15 12:10:08.381866-0800  localhost com.docker.driver.amd64-linux[4075]: cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
```

**Comment by JustinHallquist** [comment]
As @vsilent said, nuking images/containers does fix the issue.

For anyone looking for a GUI solution:
```
Troubleshooting -> Clean / Purge data
```

Should have the same effect

@nex2hex have you verified that downgrading does, in fact, fix the issue?

If so, I would recommend that approach rather than removing images/containers.

**Comment by megalithic** [comment]
Just confirming that downgrading from 3.0.1/edge to 2.5.0.1 fixes it for me. (I'm on Catalina)

**Comment by nex2hex** [comment]
@JustinHallquist 
> have you verified that downgrading does, in fact, fix the issue?
yes

**Comment by akosasante** [comment]
I am also having this issue. About to try downgrading to see if that resolves it
`9EEA4F21-CD80-4870-8C6C-80E44D63EEB0/20201215213401`

**Comment by cosakait** [comment]
> @JustinHallquist
> 
> > have you verified that downgrading does, in fact, fix the issue?
> 
> yes

Downgrade it doesn't work for me

**Comment by colceagus** [comment]
downgrading didn't work for me #5141 for my reported issue and details

**Comment by colceagus** [comment]
> Of course, removing all images and containers fixes the issue, but this is bad solution for those who have a lot of important data in volumes.

this didn't work for me, neither did downgrading, tried edge and stable

**Comment by JustinHallquist** [comment]
@colceagus
I believe your problem is not completely the same as the one experienced here, though your problem may also be causing an infinite boot loop as the issue title suggests.

Your issue link implies a failure to access the keychain properly:
```
2020-12-11 15:57:07+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
```

whereas the reports coming in here are related to the lifecycle boot looping:
```
cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
```

**Comment by colceagus** [comment]
what did work for me was disabling McAfee firewall. that got it started. i managed to add a rule for docker for all inbound/outbound connections. that also worked and it's the preferred version, but the corporate mcafee resets all the rules, unfortunately.

**Comment by colceagus** [comment]
> @colceagus
> I believe your problem is not completely the same as the one experienced here, though your problem may also be causing an infinite boot loop as the issue title suggests.
> 
> Your issue link implies a failure to access the keychain properly:
> 
> ```
> 2020-12-11 15:57:07+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
> ```
> 
> whereas the reports coming in here are related to the lifecycle boot looping:
> 
> ```
> cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
> ```

I've updated the issue with the details. I experience both issues. 
The Mac console shows the lifecycle-server error and the docker diags the output i have. If I disable McAfee Firewall i'm ok for a limited time until it turns back on automatically. If I add a rule for docker in the firewall, that works too, but for a limited time as well, until it syncs with the corporate server again.

**Comment by akosasante** [comment]
> I am also having this issue. About to try downgrading to see if that resolves it
> `9EEA4F21-CD80-4870-8C6C-80E44D63EEB0/20201215213401`

I downloaded version 3.0.0 and that seems to be working fine for me so far.  I don't recall exactly what 2.x version I was on previously before I got the prompt to update to 3.0.1

**Comment by jcw-** [comment]
Stuck in starting. I see `context deadline exceeded` in the logs, my diagnostic ID: `0350C773-DB26-4094-AECF-40D085EBE0D0/20201218061223`

**Comment by luisfarzati** [comment]
Same here -- I had an application using docker-compose that was running fine. Now with 3.0.1 the containers are created but stuck, and from that moment Docker will become unresponsive and any command timeouts.

Once that happens, restarting Docker won't work -- it gets stuck, logs say:

```
2020-12-18 10:42:52.058159+0100  localhost com.docker.driver.amd64-linux[586]: cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
```

**Comment by tiborvass** [comment]
There is a fix incoming at moby/moby#41817 thanks to @simonferquel and @cpuguy83, in the meanwhile this is the workaround, I've tested myself.

# 🚧  WORKAROUND 🚧 

```
$ echo "find /var/lib/docker/containers -name config.v2.json -exec sed -i'' -E 's/\"Running\":true(,.*\"Restarting\":true)/\"Running\":false\1/' {} \; ; exit" | nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock
```

Then click on "Restart Docker".

Please note that this is due to a container that has a restart policy, and has been restarting probably for a while. Most likely they will continue to exit early so do check the logs of your containers for some application error that needs to be handled. If there's anything good coming out of this, is that it may help you identify an application error. Sorry again for this uncool upgrade experience :(

I've grepped all diagnostics IDs mentioned in this issue and they all matched the symptoms that this workaround fixes. If it still doesn't work for you, there may be something else.

**Comment by cyrus-za** [comment]
Thanks this fixed it for me. So glad I found this before purging all my images

**Comment by vsilent** [comment]
Thank you @tiborvass  for this workaround. However, I noticed the problem appears again after some time. So I applied the workaround and docker engine started again.  Seems it's too early to close the issue.

**Comment by tiborvass** [comment]
@vsilent yeah we won't close the issue until it's released. However, if you keep seeing the issue, it means your container keeps restarting and failing, so I would still urge you to figure out what's failing with that container. Of course in the meantime the workaround allows you to get docker up again.

**Comment by jcw-** [comment]
@tiborvass fwiw, there might be anothyway this issue is triggered - for example, I'm pretty sure my containers were healthy when it happened to me.

**Comment by dvdileep** [comment]
Facing the same issue.

OS: 11.1
Docker : 3.0.3

Uninstalling and re-installing did not resolve the issue. 
I was able to reproduce by reinstalling the docker and rebooting the mac. It works perfectly if I don't restart the mac.

I've not tried the workaround yet!

**Comment by ngrevet-lightspeed** [comment]
I had the same issue yesterday, and the one-liner from https://github.com/docker/for-mac/issues/5131#issuecomment-748692772 worked perfectly for me, thanks a lot.

**Comment by kodywilson** [comment]
I was facing the same issues, Docker Desktop would stay in starting forever, but what fixed it for me was opening up the McAfee firewall for the Docker application. I had tried the factory reset, but it didn't help at all. Once I monkeyed with the firewall settings it started working right away...

**Comment by vkravets** [comment]
I've resolved it by adding to McAfree Firewall Rules Docker.app and allow all traffic.
If you advice more specific rule for Docker.app it will be great

**Comment by kodywilson** [comment]
@vkravets That's exactly what I did too. Glad it worked for you as well!

**Comment by gpongelli** [comment]
I've written a workaround that solves this issue for me here https://github.com/docker/for-mac/issues/5113#issuecomment-788326880
