### ISSUE TITLE
Trying to install docker, please help...

### ISSUE THREAD

**Issue by mclaughlin111** [docker/for-mac#5133]
mac os 10.15.7

i have error report but don't know which files will be of use.

<img width="666" alt="Screenshot 2020-12-15 at 4 38 26 PM" src="https://user-images.githubusercontent.com/47330113/102244276-fc8ce800-3ef3-11eb-994d-5173a4711e77.png">

**Comment by tiborvass** [comment]
Did you hit diagnose & feedback?

**Comment by mclaughlin111** [comment]
> Did you hit diagnose & feedback?

I did, I don't know what to do with the bunch of files it spits out though....
