### ISSUE TITLE
Building x86 apps on M1 is not possible

### ISSUE THREAD

**Issue by FranklinWaller** [docker/for-mac#5134]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: C4934302-527F-4AC6-B0A3-12C7122D53E8/20201215181229

### Expected behavior
The rust application could compile or the x86 ubuntu image would run

### Actual behavior
Both throws an error

### Information

  - macOS Version: 11.0.1 (20B29)

### Diagnostic logs

```
Docker for Mac: version Preview

```

Compiling a rust app that uses x86 features results in the following error being thrown: 
```
error[E0658]: use of unstable library feature 'stdsimd'
   --> /root/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/60e3a57/runtime/near-vm-runner/src/wasmer_runner.rs:196:9
    |
196 |     if !is_x86_feature_detected!("avx") {
    |         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #27731 <https://github.com/rust-lang/rust/issues/27731> for more information
    = help: add `#![feature(stdsimd)]` to the crate attributes to enable

error: 
        is_x86_feature_detected can only be used on x86 and x86_64 targets.
        You can prevent it from being used in other architectures by
        guarding it behind a cfg(target_arch) as follows:

            #[cfg(any(target_arch = "x86", target_arch = "x86_64"))] {
                if is_x86_feature_detected(...) { ... }
            }
        
   --> /root/.cargo/git/checkouts/nearcore-e3f14b9758bedfa0/60e3a57/runtime/near-vm-runner/src/wasmer_runner.rs:196:9
    |
196 |     if !is_x86_feature_detected!("avx") {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

When using the x86 ubuntu build:
```
FROM i386/ubuntu

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
```
You get:

The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by stephen-turner** [comment]
You didn't show the command you'd used. Did you use the `--platform` flag?

**Comment by FranklinWaller** [comment]
Running it using `docker-compose up` with the following `docker-compose.yml`

```
version: "3"
services:
  app:
    build: .
    tty: true
    stdin_open: true
    working_dir: /var/www
    ports:
        - "3000:3000"
        - "3030:3030"
        - "1337:1337"
    volumes:
        - ./:/var/www
```

**Comment by chris-crone** [comment]
Hi @FranklinWaller,

Since you're building the image from a local Dockerfile, you can pin the image that you're building `FROM` using `--platform`, see the [docs about this](https://docs.docker.com/engine/reference/builder/#from). e.g.:

```dockerfile
FROM --platform=linux/amd64 myimage
```

**Comment by FranklinWaller** [comment]
This does allow me to go a bit further than using the `FROM i386/ubuntu`. But now downloading packages with cargo are getting killed. Not sure if this is a docker issue or a rust issue. Since downloading packages without docker works.

```
root@c993b04065a6:/var/www# cargo build
    Updating git submodule `https://github.com/facebook/rocksdb.git`
Killed Fetch [=========>                                             ]  18.65%
root@c993b04065a6:/var/www# cargo build
    Updating git submodule `https://github.com/facebook/rocksdb.git`
Killed Fetch [=========>                                             ]  18.64%
root@c993b04065a6:/var/www# 
```

If I got some time left tonight I might create a repo replicating this.

**Comment by chris-crone** [comment]
The build process will be running in qemu so there's a chance that is causing issues. Do you need i386 or amd64? Note that the former is 32-bit and the latter is 64-bit.

**Comment by FranklinWaller** [comment]
Probably i386 since my old MacBook returns `i386` when running the command `arch`. I probably messed up something in the `--platform` flag but it returns this:

```
Building app
Step 1/12 : FROM --platform=linux/i386 ubuntu
latest: Pulling from library/ubuntu
ERROR: Service 'app' failed to build : no matching manifest for linux/386 in the manifest list entries
```

Looking at docker hub i386 should be available for ubuntu

**Comment by chris-crone** [comment]
I believe the Hub tags are incorrect for the latest image as a `docker manifest inspect ubuntu` doesn't show an i386 image. I'd test with `amd64` and see if that works.

**Comment by FranklinWaller** [comment]
I should've clarified the 
```
root@c993b04065a6:/var/www# cargo build
    Updating git submodule `https://github.com/facebook/rocksdb.git`
Killed Fetch [=========>                                             ]  18.65%
root@c993b04065a6:/var/www# cargo build
    Updating git submodule `https://github.com/facebook/rocksdb.git`
Killed Fetch [=========>                                             ]  18.64%
root@c993b04065a6:/var/www# 
```

issue came from using `FROM --platform=linux/amd64 ubuntu`

**Comment by FranklinWaller** [comment]
I've created a repo reproducing this issue including docker files. This showcases the downloader getting killed: https://github.com/FranklinWaller/DockerM1Issue

**Comment by chris-crone** [comment]
My guess is this is a qemu emulation issue. You could investigate using [Rust's cross compilation](https://blog.rust-lang.org/2016/05/13/rustup.html) instead if you'd just like to use this to generate a binary that you run elsewhere.

**Comment by FranklinWaller** [comment]
I'm afraid Rust cross-compilation won't do. Since it needs to run on the same machine. (Especially requiring x86) So I guess I have to wait for a fix on Qemu's side

**Comment by Nomad-Go** [comment]
Here is a [quick article I wrote when I faced this problem](https://medium.com/better-programming/how-to-actually-deploy-docker-images-built-on-a-m1-macs-with-apple-silicon-a35e39318e97). I'm able to push an image to AWS ECS now.
