### ISSUE TITLE
Docker works in CLI but won't open GUI 

### ISSUE THREAD

**Issue by bencooper222** [docker/for-mac#5135]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: AF2DF78F-C663-4B36-9E23-8C7426EAA058/20201215233044

### Expected behavior

I click on Docker icon in menu bar and click "Dashboard". It should open dashboard.

### Actual behavior

It does not.
### Information

The problem started today after a crash and then restart. I've tried reinstalling Docker and had no luck. Interestingly, I can't uninstall docker from the CLI, I've just dragged the icon to the trash:

![image](https://user-images.githubusercontent.com/9143563/102285610-41b51800-3efc-11eb-97d9-e3c53e650321.png)

Additionally, I've occasionally gotten a message from Docker saying that something couldn't happen and to either upload diagnostics or reset to factory settings. The former worked but attempting to open those diagnostics made the process hang. The second did not work at all and just made the process hang. I had to force quit both from Activity Monitor. 

macOS version: 10.15.7

### Diagnostic logs
I can't actually get to the "Diagnose and Feedback" in the menu. The Apple `Console` app has the following logs from the app. The Death Sentinel part seems bad based on a bit of googling.

```
error	17:34:37.016648-0600	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for RESP:{ID: com.docker.docker, PID[78614], auid: 502, euid: 502, responsible path: '/Applications/Docker.app/Contents/MacOS/Docker', binary path: '/Applications/Docker.app/Contents/MacOS/Docker'}, ACC:{ID: com.electron.docker-frontend, PID[78732], auid: 502, euid: 502, binary path: '/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop'}, REQ:{ID: com.apple.appleeventsd, PID[457], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
default	17:34:37.087150-0600	kernel	AGC:: [Docker Desktop H pid 78733 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:00.077
default	17:34:37.954127-0600	Docker Desktop	nw_path_evaluator_start [E51007C5-0E74-4446-B108-456BEC598D40 <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en7, ipv4, ipv6, dns
default	17:34:38.054945-0600	hidd	Connection removed: IOHIDEventSystemConnection uuid:49EDE4BB-E916-4A17-915F-923B674F63C1 pid:78732 process:Docker Desktop type:Monitor entitlements:0x0 caller:GameController: _GCHIDEventCallback + 96 attributes:(null) state:0x1 events:0 mask:0x0
default	17:34:38.059319-0600	runningboardd	[executable<Docker Desktop(502)>:78732] Death sentinel fired!
default	17:34:38.062098-0600	runningboardd	Invalidating assertion 426-129-172962 (target:executable<Docker Desktop(502)>) from originator 129
default	17:34:38.062367-0600	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Docker Desktop, _appTrackingState = 2
default	17:34:38.159454-0600	runningboardd	Removing process: [executable<Docker Desktop(502)>:78732]
default	17:34:38.160552-0600	runningboardd	Removing assertions for terminated process: [executable<Docker Desktop(502)>:78732]
error	17:34:38.188663-0600	runningboardd	RBSStateCapture remove item called for untracked item 426-129-172962 (target:executable<Docker Desktop(502)>)
default	17:34:41.724953-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Docker Desktop
default	17:34:41.724968-0600	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Docker Desktop

```

![image](https://user-images.githubusercontent.com/9143563/102285336-b5a2f080-3efb-11eb-8ca0-54337cc1b2f9.png)

### Steps to reproduce the behavior

1. Try to open dashboard

**Comment by Sameerkash** [comment]
I can confirm this issue, My docker desktop is not opening or even showing any notifications after updating to the latest version.

**Comment by MPiccinato** [comment]
Also confirming. I can not get any GUI to show after installing 3.0.3. Even removing and trying other versions 2.5.0.1 and up, still won't show the Dashboard or Preferences.

**Comment by bencooper222** [comment]
Suddenly works coming back from vacation. #reliability
