### ISSUE TITLE
Docker does not work on boot

### ISSUE THREAD

**Issue by vistiyos** [docker/for-mac#514]
### Expected behavior
I expect that it works
### Actual behavior
It does not work.
### Information

Diagnostic ID: BEDAE2AB-5E27-4703-B613-8553A658C17A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Just start Docker for Mac.

**Comment by nathonfowlie** [comment]
Having the same issue, nuking it from orbit then restarting docker seems to temporarily fix the problem (rm -rf ~/.docker).

**Comment by mchiang0610** [comment]
Sierra related issues are being addressed in beta 25:  https://download.docker.com/mac/beta/Docker.dmg 

Stable will be released soon. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
