### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by manishmmmec** [docker/for-mac#5142]
when I run
docker pull mysql

Output is l:

Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by amfahrj** [comment]
That's because there is no arm64 build of mysql. Choices are use mariadb or specific exactly the intel build with 

docker pull mysql:5.7@sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd

**Comment by amfahrj** [comment]
By the way, I got the sha at the end by running

docker manifest inspect mysql:5.7

**Comment by stephen-turner** [comment]
Behaving correctly, closing the issue.
