### ISSUE TITLE
M1 Preview does not start if Resources are set too low

### ISSUE THREAD

**Issue by gramss** [docker/for-mac#5144]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F0E25788-D28B-4835-A485-53F504E5F36B/20201217022502

### Expected behavior

Test if docker container works with limited resources (2 CPUs and 1.00 GB of RAM)

### Actual behavior

Docker hangs on starting. With resetting everything back to factory it works again, but containers are lost.

### Information

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac: version.  M1 Preview
Nothing else here, as it does not start

```

### Steps to reproduce the behavior

  1. clean install
  2. straight to settings and limit resources to 2 CPU and 1.00 Gb of RAM
  3. apply & restart button
  4. docker does not start again

Besides that the Preview works really great..!
Sad I have lost my images, as I found no way of copying them out, if the engine was not up.
Also the configuration file for the resources set her was not findable..

**Comment by stephen-turner** [comment]
It should at least fail gracefully. Is the behaviour different from the current released (Intel) version?

**Comment by gramss** [comment]
Sorry, I currently do not have an Intel based Mac, as its battery is broken. So I cannot test that.

But I would suggest that it works if it can be set through slides in the GUI?
