### ISSUE TITLE
`docker logs -f -t` fails with `Error grabbing logs: unexpected EOF` after about 30m 

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#5145]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: E75A2F4F-F2B0-4271-BAC5-0F025D1E3E20/20201217054234

### Expected behavior
Before 3.0 I was able to reliably see multi-hour `docker logs container` output.

### Actual behavior
Soon after upgrading Docker for Desktop, when I run `docker logs -t -f` on my container (which runs some system tests) it stops after about 30 minutes with `error from daemon in stream: Error grabbing logs: unexpected EOF`.  The container continues running fine, I can start another `docker logs -t -f` but it quickly stops with the same error. After the container exits I can run `docker logs -t -f` on it and see all the output through the end.
```
2020-12-17T03:28:12.431495671Z Running 'test-', Ctrl-D or Ctrl-P Ctrl-Q to exit.
...
2020-12-17T03:58:31.781645898Z ('    ', 'responseBytes', '=', '25')
error from daemon in stream: Error grabbing logs: unexpected EOF
````
I guess it could be related to the docker 19 => 20 upgrade, not Desktop itself, will try to narrow down.
### Information

  - macOS Version: 11.1 (20C69) 

### Diagnostic logs

```
Docker for Mac: 3.0.1

```

### Steps to reproduce the behavior

Sorry haven't tried reproducing with simple container, but it's just `docker logs -f -t` on a long running container with a lot of output.

**Comment by Maelstromeous** [comment]
Can confirm this is happening, it's extreamely annoying when trying to develop applications, hopefully there's a fix out for this soon!

**Comment by cpuguy83** [comment]
@stephen-turner 

> We've identified that the upstream engine is crashing

Do you have a crash dump?

**Comment by stephen-turner** [comment]
@cpuguy83 I think @mat007 sent something to @tiborvass, I don't know what happened after that.

**Comment by lindycoder** [comment]
Hi i have the exact same problem with 3.0.3, i also left message in the moby issue https://github.com/moby/moby/issues/41820#issuecomment-755731644 

I can reproduce consistantly right now, if i can provide any more information, just ask!

Thank You,
Martin

**Comment by apiology** [comment]
For those looking for a workaround, I uninstalled Docker for Mac, then downloaded and installed a pre-v3 version from here: https://docs.docker.com/docker-for-mac/release-notes/

Back to normal!

**Comment by cpuguy83** [comment]
You might also try to change the default log driver to "local" instead the default default (json-file).

**Comment by airdrummingfool** [comment]
Changing the log driver did not work for me.

**Comment by jamshid** [comment]
I guess I'll close this as a dup of https://github.com/moby/moby/issues/41820 which has a fix ready. 
Seems like it was hard to reproduce though weird that so many people reported it, esp on macos. 
Eager to find out what version will have the fix. It's not in the 20.10.5 that was recently released.

**Comment by rmoff** [comment]
If you just want to follow the logs for a container from your console here's a crappy workaround until the issue is fixed: 

```shell
while [ 1 -eq 1 ] ; do docker logs -f -n0 my_container_name ; done
```

You'll still hit the error but the log trail will restart automagically from the end.
