### ISSUE TITLE
Docker Desktop not starting on Catalina

### ISSUE THREAD

**Issue by soupdiver** [docker/for-mac#5146]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
Docker should start

### Actual behavior
Docker does not start.

### Information
Recently I installed the latest update for Docker, I think it was the upgrade to version 3. The one that gives delta updates. I don't think another update has been installed since but I'm not 100% sure.
However installation of Docker Desktop does not start anymore. No errors, no nothing.
I already re-installed but the same effect. I installed via `brew install --cask docker`

  - macOS Version: `10.15.7 (19H114)`

### Diagnostic logs
The only "logs" that I could find where via the `Console` App.

```
Dec 17 10:16:46 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[7054]): Service exited due to SIGABRT
Dec 17 10:17:07 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[7758]): Service exited due to SIGABRT
Dec 17 10:17:23 felix-mini com.apple.xpc.launchd[1] (com.docker.vmnetd[140]): Service exited due to SIGTERM
Dec 17 10:17:31 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[8639]): Service exited due to SIGABRT
Dec 17 10:19:05 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[11928]): Service exited due to SIGABRT
Dec 17 10:22:40 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[19504]): Service exited due to SIGABRT
Dec 17 10:39:34 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[535]): Service exited due to SIGABRT
Dec 17 10:39:43 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[727]): Service exited due to SIGABRT
Dec 17 10:40:07 felix-mini com.apple.xpc.launchd[1] (com.docker.docker.22724[766]): Service exited due to SIGABRT
Dec 17 10:49:00 felix-mini com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.Docker[2300]): Service exited due to SIGABRT
```

```
Docker for Mac: latest I guess
Downloaded from: https://desktop.docker.com/mac/stable/49550/Docker.dmg

```

### Steps to reproduce the behavior

  1. Install Docker
  2. Try to start Docker

**Comment by thefliik** [comment]
I'm running into a similar issue on Mac OS 10.14.6 (all the latest security patches applied). Since updating Docker for Mac from 2.x to 3.x, attempting to start Docker for Mac results in an infinite "Docker Desktop is starting..." step (Docker Desktop never finishes "starting").

Looking at the mac `Console`, I see the following:

```
default	09:50:32.882558 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
default	09:50:43.887569 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
default	09:50:54.889590 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
default	09:51:05.891972 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
default	09:51:16.895292 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
default	09:51:27.900033 -0800	com.docker.driver.amd64-linux	cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
```

This might be completely unrelated, but I notice the `amd64` bit in the console log and my iMac has an intel processor. Also, and I imagine this is entirely unrelated, but something unusual about my setup is that my iMac's internal HDD died so I boot it from an external (USB) flash drive.

**Comment by soupdiver** [comment]
> Edit: resetting Docker Desktop to factory defaults solved my issue

I kind of can confirm. I uninstalled Docker completely, restarted my machine and re-installed Docker.
This did not work on the first try I think... but eventually after having Docker not installed for 2 days, reboot and reinstall it started working again.
So kind of unclear what was the actual issue.
