### ISSUE TITLE
M1 Preview Docker will not start up with gRPC-fuse setting disabled

### ISSUE THREAD

**Issue by gus-t27** [docker/for-mac#5147]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8c5a58fa-6252-430c-90bf-2a3675477ec0/20201217100246 am

### Expected behavior
Docker starts-up with gRPC-fuse turned off
### Actual behavior
Docker hangs on start-up.
### Information

  - macOS Version:
BigSur 11.0.1
### Diagnostic logs

```
Docker for Mac: version...
0.0.0 (1)
```

### Steps to reproduce the behavior

  1. Disable gRPC-fuse setting and click apply & restart.

**Comment by mattPiratt** [comment]
Same here.
I am not into what this "gRPC fuse" means, but I have to disable it, so my mounts in the container on Mac works correctly.

In detail, 
1) Using "Finder" I am navigating to a network resource. Let it be "NASStorage". So this path becomes mounted and available /Volumes/NASStorage
2) I am mounting:  -v /:/hostRoot/.  (in container I have access to root dir of my mac as path /hostRoot)... this way I am able to access from container path like. /hostRoot/Volumes/NASStorge/

Problem:
When using "gRPC fuse", this does not work, and in the container, I can see empty directory /hostRoot/Volumes
When I turn off "gRPC fuse", then docker froze on the "Starting" stage.
This is happening only on M1 mac

I have 2nd Mac Intel-based, and disabling "gRPC fuse" gets things to expected outcome: I can access  /hostRoot/Volumes/NASStorge/

**Comment by gus-t27** [comment]
Hi Matt,

Thanks for your comment. 

My intel mac also works fine with the gRPC-fuse setting turned off. So it is definitely and M1 issue.

Cheers,

Gus
