### ISSUE TITLE
Unable to start Kubernetes using Docker for Mac M1

### ISSUE THREAD

**Issue by joniaiuser** [docker/for-mac#5153]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 71a5e54d-0a0c-459b-a443-a4b98be46ac0/20201218051622

### Expected behavior
Kubernetes can start

### Actual behavior
Kubernetes stuck at starting

### Information

  - macOS Version: 11.1

I have tried the solutions on the threads here such as uninstalling Docker for Mac, resetting to factory defaults, deleting the kubernetes cluster files etc. but none of them has worked for me.

### Diagnostic logs

```
Docker for Mac: 0.0.0 (1) Preview

```
 Stuck at starting...
![image](https://user-images.githubusercontent.com/64962001/102578183-8e833380-4134-11eb-9eb2-7e3fe0353600.png)

**Comment by stephen-turner** [comment]
Thanks for the report. This is explicitly documented as not implemented yet at https://docs.docker.com/docker-for-mac/apple-m1/
