### ISSUE TITLE
Mac OS 11.1 on MacBook Air apple silicon m1, always starting

### ISSUE THREAD

**Issue by pbpoon** [docker/for-mac#5154]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. clean install
  2. when open docker && docker desktop is starting;

**Comment by shi-rudo** [comment]
same here

**Comment by TigerRobocop** [comment]
I have the same issue, stuck at `docker desktop is starting`.
macOS Catalina 10.15.7
Docker version 20.10.0, build 7287ab3
Desktop version 3.0.1

**Comment by jgresham** [comment]
Same issue here:
Version: 0.0.0 (1)
Engine: 20.10.0
macOS 11.1
MacBook Air M1

**Comment by CarlosWan** [comment]
Same issue here.Env:
Client:
 Cloud integration: 1.0.2
 Version:           20.10.1
 API version:       1.41
 Go version:        devel +37a32a1833 Thu Dec 3 21:34:39 2020 +0000
 Git commit:        831ebeae96
 Built:             Wed Dec 16 02:33:22 2020
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

macOS 11.1
MacBook Air M1 8G

**Comment by shi-rudo** [comment]
same problem but on non-m1 (intel Mac)

macOS Catalina 10.15.7
Docker version 20.10.0
Desktop version 3.0.1

**Comment by hiroshi** [comment]
Using Docker-AppleSilicon-Preview7.dmg on M1 MabBook Air/ macOS 11.1

"starting" state doesn't comple after some successful use of the docker for mac and sleep or restart of the mac I think.

I learned the path to kernel log file from https://docs.docker.com/docker-for-mac/apple-m1/, and it tell me that:
```
$ tail -f ~/Library/Containers/com.docker.docker/Data/vms/0/console.log
...
INFO[1970-01-01T00:00:04.855728793Z] containerd successfully booted in 0.019166s  
FATA[0000] Cannot parse runtime config: unexpected end of JSON input 
```

**Comment by AxelGreen** [comment]
Same here.
Docker version 20.10.0, build 7287ab3
macOS 11.1
MacBook Pro (2019)

`Troubleshoot -> Clean / Purge data` solves a problem for me. Not ideal, but I consider it better than `Troubleshoot -> Reset to factory defaults`.

**Comment by dgdosen** [comment]
isn't the underlying problem here that the the docker desktop kubernetes image it needs to run (https://hub.docker.com/r/docker/desktop-kubernetes/tags?page=1&ordering=last_updated) 
is not yet build for arm64?

Any ETA on when that can be addressed?

**Comment by paultuckey** [comment]
Disabling Firewall in System Preferences worked for me.

**Comment by sfuerte** [comment]
Duplicate of https://github.com/docker/for-mac/issues/5140
No need to disable firewall completely but just change its mode.

**Comment by hcancelik** [comment]
I'm having the same issue and Firewall is never enabled. 

Here is the output of `tail -f ~/Library/Containers/com.docker.docker/Data/vms/0/console.log`

```
time="1970-01-01T00:00:05.578143669Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/acpid pid=727
time="1970-01-01T00:00:05.769336752Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/binfmt pid=782
time="1970-01-01T00:00:05.957312586Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/dhcpcd pid=835
time="1970-01-01T00:00:06.128180086Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/diagnose pid=887
time="1970-01-01T00:00:06.315243544Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/docker pid=955
time="1970-01-01T00:00:06.499815753Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/kmsg pid=1012
time="1970-01-01T00:00:06.689115211Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/sntpc pid=1099
time="1970-01-01T00:00:06.892041294Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/socks pid=1154
time="1970-01-01T00:00:07.111422628Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/trim-after-delete pid=1203
time="1970-01-01T00:00:07.313823628Z" level=info msg="starting signal loop" namespace=services.linuxkit path=/run/containerd/io.containerd.runtime.v2.task/services.linuxkit/vpnkit-forwarder pid=1261
```

Not sure why the date is 1970-01-01.

**Comment by sfuerte** [comment]
@hcancelik, here is someone else reported a problem related to the wrong time/date and a workaround for it - https://github.com/docker/for-mac/issues/5130

**Comment by du5** [comment]
```bash

13k@mini gopanel % tail -f ~/Library/Containers/com.docker.docker/Data/vms/0/console.log
INFO[0254] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0254] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
INFO[0256] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0256] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
INFO[0258] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0258] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
INFO[0260] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0260] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
INFO[0262] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0262] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
INFO[0264] connecting to tcp+connect://192.168.64.1:1999... 
INFO[0264] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
^C
13k@mini gopanel % ifconfig | grep  192.168.64.1                                        
        inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
13k@mini gopanel % ping 192.168.64.1                                                    
PING 192.168.64.1 (192.168.64.1): 56 data bytes
64 bytes from 192.168.64.1: icmp_seq=0 ttl=64 time=0.133 ms
^C
--- 192.168.64.1 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.133/0.133/0.133/0.000 ms
13k@mini gopanel % 

```

**Comment by pbpoon** [comment]
> ```shell
> 13k@mini gopanel % tail -f ~/Library/Containers/com.docker.docker/Data/vms/0/console.log
> INFO[0254] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0254] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> INFO[0256] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0256] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> INFO[0258] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0258] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> INFO[0260] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0260] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> INFO[0262] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0262] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> INFO[0264] connecting to tcp+connect://192.168.64.1:1999... 
> INFO[0264] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable 
> ^C
> 13k@mini gopanel % ifconfig | grep  192.168.64.1                                        
>         inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
> 13k@mini gopanel % ping 192.168.64.1                                                    
> PING 192.168.64.1 (192.168.64.1): 56 data bytes
> 64 bytes from 192.168.64.1: icmp_seq=0 ttl=64 time=0.133 ms
> ^C
> --- 192.168.64.1 ping statistics ---
> 1 packets transmitted, 1 packets received, 0.0% packet loss
> round-trip min/avg/max/stddev = 0.133/0.133/0.133/0.000 ms
> 13k@mini gopanel % 
> ```
我也试过是可以运行，但不能pull任何的images

**Comment by guglen** [comment]
the problem of IP 192.168.65.1 of the bridge card "seems" to have been solved by modifying the file

/Library/preferences/SystemConfiguration/com.apple.vmnet.plist

by editing the final part of the file:

         <key> Shared_Net_Address </key>
         <string> 192.168.64.1 </string>
         <key> Shared_Net_Mask </key>
         <string> 255.255.255.0 </string>

**Comment by pbpoon** [comment]
> the problem of IP 192.168.65.1 of the bridge card "seems" to have been solved by modifying the file
> 
> /Library/preferences/SystemConfiguration/com.apple.vmnet.plist
> 
> by editing the final part of the file:
> 
> ```
>      <key> Shared_Net_Address </key>
>      <string> 192.168.64.1 </string>
>      <key> Shared_Net_Mask </key>
>      <string> 255.255.255.0 </string>
> ```

yes! now working for me. thanks

**Comment by LeZuse** [comment]
My machine went through a kernel panic after which I was not able to boot up Docker again. The bridge100 interface was completely missing. I fixed the issue by Troubleshoot > Uninstall, installing again from dmg and restarting the machine.
