### ISSUE TITLE
M1 Preview: "bad CPU type in executable" on launch after Restore of M1 Mac

### ISSUE THREAD

**Issue by finder39** [docker/for-mac#5155]
### Expected behavior

Docker will launch

### Actual behavior

![Screen Shot 2020-12-18 at 9 44 19 AM](https://user-images.githubusercontent.com/518673/102644661-07bf5e00-4116-11eb-9b85-44831cf5c2b7.png)

### Information

After doing a Restore of an M1 Mac (in this case, a Mini) by following [these instruction from Apple](https://support.apple.com/en-gb/guide/apple-configurator-2/apdd5f3c75ad/mac), I now cannot launch Docker. I tried doing another Restore but the issue persists.

It had installed before doing a Restore, but I was getting a "client.timeout exceeded while awaiting headers" issue anytime I tried to pull a repo, which prompted the Restore.

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac: M1 Preview

```

### Steps to reproduce the behavior
- Restore Mac following [these instruction from Apple](https://support.apple.com/en-gb/guide/apple-configurator-2/apdd5f3c75ad/mac).
1. Download the M1 Preview of Docker from blog post
2. Open DMG
3. Drag Docker Preview into Applications
4. Launch Docker
5. Type in Password
6. Experience issue

**Comment by finder39** [comment]
From console `system.log`:

Dec 18 09:55:20 Mini com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.docker.docker.46912.47560(501)> [529]
Dec 18 09:55:37 Mini com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): entering bootstrap mode
Dec 18 09:55:37 Mini com.apple.xpc.launchd[1] (com.docker.vmnetd): Unknown key for string: Version
Dec 18 09:55:37 Mini com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): exiting bootstrap mode

**Comment by finder39** [comment]
> Maybe the restore didn't install Rosetta 2. At the moment that is needed because not all binaries of Docker Desktop are already native arm64 binaries.
> 
> Try to install Rosetta 2 from a terminal
> 
> ```
> /usr/sbin/softwareupdate --install-rosetta --agree-to-license
> ```

That immediately fixed it, thanks! Since a Restore doesn't install Rosetta 2, this could be a useful piece to add the FAQ or Common Issues page.

**Comment by StefanScherer** [comment]
ping @usha-mandya 👆for the Apple M1 docs page.

**Comment by usha-mandya** [comment]
@StefanScherer Rosetta 2 has been mentioned on the Apple M1 Tech Preview page - https://docs.docker.com/docker-for-mac/apple-m1/#known-issues

**Comment by StefanScherer** [comment]
Oh yes, thanks. 👍
