### ISSUE TITLE
Error when using docker tail -f with a lot of output

### ISSUE THREAD

**Issue by pwagland** [docker/for-mac#5156]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

`docker tail -f <container>` doesn't fail.

### Actual behavior

`docker tail -f <container>` fails with:
```
error from daemon in stream: Error grabbing logs: unexpected EOF
```

### Information

This problem is reproducible for me. Unfortunately I cannot share a reproduction case, since the containers in question are internal.

However, the following reproduces 100%, and I assume is the same issue:

```
> docker logs --follow $(docker run --rm --detach alpine yes {1..200}; sleep 1) > /dev/null
error from daemon in stream: Error grabbing logs: unexpected EOF
```
 - Docker version: 3.0.1
 - macOS Version: 10.15.7

### Diagnostic logs

I cannot include the diagnostic logs, as they are full of PII. If really needed, please let me know a specific person that can look at them, and I will share them with that person.

### Steps to reproduce the behavior
  1. `docker logs --follow $(docker run --rm --detach alpine yes {1..200}; sleep 1) > /dev/null`

**Comment by NeoPhi** [comment]
Still seeing this issue with Docker Desktop 3.2.2 on MacOS 11.2.3.

**Comment by pwagland** [comment]
I can no long reproduce on Docker Desktop 3.3.3. Others have seen this issue as well, so will wait for a separate confirmation before closing.

**Comment by NeoPhi** [comment]
This also looks to be fixed for me.

**Comment by pwagland** [comment]
> This also looks to be fixed for me.

Two confirmations, calling it fixed.
