### ISSUE TITLE
M1 Preview: Can't use K8s

### ISSUE THREAD

**Issue by nourcy** [docker/for-mac#5161]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4F3B13E7-3984-4800-8F80-14FF5E1D0971/20201219202828

### Expected behavior
As Docker User I should be able to use docker for Mac kubernetes

### Actual behavior
Stuck in starting

### Information

  - macOS Version: 11.1 M1 16Gb MBP

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Activate kubernetes
  2. Apply
  3. Grab a coffee

**Comment by StefanScherer** [comment]
Thanks. That‘s a known issue of the preview. 
You can read more about that here https://docs.docker.com/docker-for-mac/apple-m1/#known-issues

**Comment by enyo** [comment]
@StefanScherer is there a known workaround for that, or do we have to wait for a release to fix that?

**Comment by StefanScherer** [comment]
@enyo I'm not aware of a workaround. I guess have to wait for another preview release.
