### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by saaramar** [docker/for-mac#5166]
There is an assertion failure while building docker images. The problem is that it's not deterministic. I know it's really annoying getting bugs without repro steps, coredumps, etc., but the assertion is pretty documented. The assertion failure is as follows:

assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1046564d8 abi_kind=6 emulation_interval=[0x104680948,0x10468095c) instruction_interval=[0x104680934, 0x10468095c) x86_rip=0x1117360

(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary) 

Thanks for all of your great work!

**Comment by stephen-turner** [comment]
This appears to be a bug in Rosetta 2, so I guess we'll have to wait for Apple to fix it. See https://discussions.apple.com/thread/252061978?page=2
