### ISSUE TITLE
M1 Preview version database volume issue

### ISSUE THREAD

**Issue by galikpali** [docker/for-mac#5169]
I'm trying out the preview version of the docker for mac on my M1 machine, and I experienced a possible bug regarding to mysql database volumes.

I launched a container based on the latest version of [mariadb](https://hub.docker.com/_/mariadb) image on my M1 machine. I did it with volume mounting, because I wanted to persist the state of the database `(-v ~/data:/var/lib/mysql)`.

I noticed when I create a table it it somehow does not get saved and it goes to error state.
When I run SHOW TABLES command in the database I can see the table list as expected, but when I try to query rows from any table I get the following error: ERROR 1932 (42S02): Table 'databasename.tablename' doesn't exist in engine

The reason why I think it has something to do with mounting volumes because when I launch the container without it, it works without any errors.

**Comment by ebriney** [comment]
Hi @galikpali.  Can you provide a diagnostic please?
Ideally reset to default -> do the repro -> diagnostic.
Thanks.

**Comment by galikpali** [comment]
Hey @ebriney!
I uploaded the diagnostics right after the issue happened. Let me know if you can find any useful info.
[20210101151918.zip](https://github.com/docker/for-mac/files/5759093/20210101151918.zip)

**Comment by galikpali** [comment]
Hey @ebriney !

FYI.
I just installed the new version of the preview build and turned off gRPC file sharing feature and it's just works fine.
