### ISSUE TITLE
Docker start failed 

### ISSUE THREAD

**Issue by Cezarion** [docker/for-mac#517]
### Steps to reproduce

1. Run docker 

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: 6EF671C6-7359-409A-B8D0-CB70AD3672F1
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by mchiang0610** [comment]
A lot of the macOS sierra bugs are resolved in beta 25. If you are comfortable with beta builds please try it here: https://download.docker.com/mac/beta/Docker.dmg 

The stable version will release soon. 

Thanks!

**Comment by Cezarion** [comment]
Great ! 

I tested it on!

Thank's

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
