### ISSUE TITLE
Docker takes up a lot of memory on Apple computers

### ISSUE THREAD

**Issue by 120011676** [docker/for-mac#5172]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
![image](https://user-images.githubusercontent.com/1992933/102859085-50ed1600-4466-11eb-9147-cb48a4e78062.png)
![image](https://user-images.githubusercontent.com/1992933/102859127-6104f580-4466-11eb-942a-d685298c9f60.png)

### Information

  - macOS Version:
![image](https://user-images.githubusercontent.com/1992933/102859165-75e18900-4466-11eb-8f89-9cd7cbcd236f.png)
### Diagnostic logs

```
Docker for Mac: version...


```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ebriney** [comment]
It's normal because it allocates memory for the VM.
You can adjust it in `Preferences->Resources->Advanced->Memory`

**Comment by 120011676** [comment]
@ebriney Mm-hmm. I suggest optimization
