### ISSUE TITLE
M1 Docker Preview - bad CPU type in executable

### ISSUE THREAD

**Issue by msioen** [docker/for-mac#5173]
I'm trying out the new M1 preview as linked here: https://www.docker.com/blog/download-and-try-the-tech-preview-of-docker-desktop-for-m1/

- MacBook Air (M1, 2020)
- Docker-AppleSilicon-Preview7

=> clean install of docker
=> install works as expected
=> on launch, asks to install helper, seems to work correctly
=> after helper installed I get a fatal error and can't do anything else

Error message: 'StartAll failed: cannot start ...osxfs: bad CPU type in executable'
<img width="666" alt="Screenshot 2020-12-22 at 11 41 28" src="https://user-images.githubusercontent.com/1830018/102881509-3f4b4480-444d-11eb-9b95-9dace1da5bec.png">

=> choosing the factory reset option doesn't help (helper gets reinstalled and fails again after that)

**Comment by woachk** [comment]
You don't have Rosetta installed and the current Docker Desktop beta isn't fully native.

You can solve the issue with running softwareupdate --install-rosetta or you can wait for the app to become fully native.

**Comment by msioen** [comment]
Many thanks, I incorrectly assumed Rosetta bits were enabled by default.

Closing this.
