### ISSUE TITLE
Docker Desktop for Apple Silicon - Crashes while clean / purge data

### ISSUE THREAD

**Issue by jaythaker** [docker/for-mac#5177]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop App should be running.

### Actual behavior
Docker Desktop App get shutdown / crashes.

### Information

  - macOS Version: Big Sur 11.1

### Diagnostic logs

```
Docker for Mac: 0.0.00 (1)

```

### Steps to reproduce the behavior

  1. Open Docker Desktop
  2. Go to Troubleshoot
  3. Click on Clean / Purge data
  4. Confirm delete

**Comment by stephen-turner** [comment]
@jaythaker We can't do anything without uploaded diagnostics. Please reproduce the bug, upload diagnostics, and then paste the diagnostics id here. Thank you.
