### ISSUE TITLE
Docker(Preview) Mac M1 Out of memory

### ISSUE THREAD

**Issue by z3niths** [docker/for-mac#5179]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
- application can be run smoothly
### Actual behavior
- the bash inside the container show "mmap() failed: [12] Out of memory"
### Information

  - macOS Version: 11.1 (20C69)

### Diagnostic logs

```
Docker for Mac: version Docker for M1 preview
https://desktop.docker.com/mac/m1preview/Docker-AppleSilicon-Preview7.dmg

```

<img width="1068" alt="Screen Shot 2563-12-23 at 14 12 53" src="https://user-images.githubusercontent.com/16873595/102970624-72afd100-452a-11eb-9824-b157e8438b38.png">

I'm trying to observe the memory while the process is running as well but seem like the container doesn't use swap and didn't use full memory from the memory space. (Probrably 32bit stuff ?)

**Comment by galikpali** [comment]
I'm experiencing the kind of the same issue as described above.
I have a simple php build process where during the build project's dependencies are installed via composer.
I'm getting the following error message:

```
+ composer dump-autoload -o --classmap-authoritative
Generating optimized autoload files (authoritative)

mmap() failed: [12] Cannot allocate memory
Segmentation fault
ERROR: Service 'php' failed to build : The command '/bin/sh -c set -eux;        mkdir -p var/cache var/log data public/media;   composer --no-interaction check-platform-reqs;      composer dump-autoload -o --classmap-authoritative;     chmod +x bin/console; sync' returned a non-zero code: 139
make: *** [start_dev] Error 1
```
I did a diagnostic right after the error occurred, here it is:
[20210101135857.zip](https://github.com/docker/for-mac/files/5759007/20210101135857.zip)

**Comment by luancschmitz** [comment]
I have the same problem.
While on an Intel mac I have a docker running perfectly with 5gb of memory and 2gb of swap (Preferences -> Resources -> Advanced). The mac with m1 is experiencing an out of memory error with 5GB of memory and 2.5GB of swap.

**Comment by VladimirLogachev** [comment]
MacBook Air M1, 16 Gb RAM
macOS 11.2.2 (20D80)

Docker Desktop 3.1.0 (60984)
Engine: 20.10.3
Docker settings: 6 CPUs, 12 Gb RAM, 4 Gb Swap

Steps to reproduce:
1. `docker run -it vladimirlogachev/oom-test`
2. As `bash` opens, enter `stack build` and press Enter.

It's a Haskell Stack project that does nothing but requires some dependencies to be compiled.

The build command works fine on Windows and Linux on `amd64`, but quickly fails on M1. Does not look like it's really using a lot of resources.

However projects with less dependencies can be compiled, and the whole project can be compiled via Haskell Stack without Docker (using Rosetta). I think that it's not the case of architecture incompatibility or a bug in the Haskell Stack.

**Comment by EAEPT** [comment]
We have same problem with composer 1.10.20.
Any ideas? Thanks

**Comment by luancschmitz** [comment]
@flipcruz Hi, 
What images are you using?

**Comment by Pablo-Camara** [comment]
same issue as @flipcruz  , 
I also tried running the following command ( also on MacBook Pro (13-inch, M1, 2020) 16GB RAM )
docker run --platform linux/amd64 --rm -it --volume $(pwd):/app prooph/composer:7.1 install

And with that image also fails,

Thanks!

**Comment by luancschmitz** [comment]
@flipcruz 
I tackled this "out of memory" problem only by using something not built for ARM. This is probably the case with this Lando software.
If it had a docker-composer it would be possible to check its dependencies and make the necessary changes to work on mac os with arm. As it doesn't have it gets a little more complex.

**Comment by luancschmitz** [comment]
@Pablo-Camara Hi,
I suggest installing a php image and installing the composer inside it. 
With this command in our Dockerfile:

`RUN curl -sS https://getcomposer.org/installer | \
  php -- --1 --install-dir=/usr/local/bin --filename=composer

RUN mkdir /var/www/.composer-global \
  && composer init --working-dir=/var/www/.composer-global --no-interaction \`

**Comment by messense** [comment]
Same issue with `cargo build` in a alpine:edge armv7 container.

```
# cargo build
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
error: failed to get `anyhow` as a dependency of package `maturin v0.10.4 (/io)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  unexpected data at the end of the pack; class=Indexer (15)
```

**Comment by stephen-turner** [comment]
I think all these issues are to do with trying to run amd64 containers on M1 hardware. We attempt to run them under emulation, but it's best effort only. Even when it works it will be slower and use more memory.

In the latest version, we are calling qemu (the emulator) with an extra argument that may help in some cases, so it's worth retrying your examples. But the real solution is to run only arm64 containers on M1 hardware.
