### ISSUE TITLE
Changing limit memory on mac caused a white page,no response from docker-desktop app

### ISSUE THREAD

**Issue by wyycode** [docker/for-mac#5180]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
set docker limit memory to 4GB
### Actual behavior
When I changed the docker memory, then Docker Desktop went crash.The performance page became a white page and no response
### Information

  - macOS Version:10.14.5 (18F203)

### Diagnostic logs

```
Docker for Mac: versio 3.0.3(51017)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by z3niths** [comment]
I think it's related to the issue that the Docker desktop cannot restart properly on this version.
I've experienced the same issue so I have to restart the machine to make it work.

**Comment by wyycode** [comment]
> I think it's related to the issue that the Docker desktop cannot restart properly on this version.
> I've experienced the same issue so I have to restart the machine to make it work.

I tried this method and it did not work. After that, I upgrade macOS version to 11.1.It's still not working.
