### ISSUE TITLE
Missing release notes of the 3.0.3(51017) version

### ISSUE THREAD

**Issue by ritostopher** [docker/for-mac#5182]
On the page https://docs.docker.com/docker-for-mac/release-notes/ current actual version of the Docker is 3.0.2.
![2020-12-23_21-58-36](https://user-images.githubusercontent.com/7264701/103033039-38662400-456a-11eb-98ff-a90a13d26656.png)

But right now it is possible to updates up to 3.0.3.
![2020-12-23_21-54-30](https://user-images.githubusercontent.com/7264701/103032830-b2e27400-4569-11eb-9517-7a1f8807d77b.png)

So it is possible to update up to version, without possibility to read about changes in it.

### Expected behavior
After notification in the Docker, that a new version is brought, the possibility to go release notes and read about changes in it.

### Actual behavior
After the new update, no possibility to read more about it.

**Comment by qhenkart** [comment]
Is there a way to turn off automatic updates? 3.0.3 had breaking changes for us, and I have to continuously reinstall 3.0.2

**Comment by qhenkart** [comment]
@ritostopher 3.0.3 is actually a rollback to 3.0.1 https://github.com/docker/for-mac/issues/5157

**Comment by ritostopher** [comment]
Thanks, @qhenkart for the link.
So, it will be fixed after https://github.com/docker/docker.github.io/pull/11956 will be merged.

I will close this issue.
