### ISSUE TITLE
Docker 3.0.3 not starting on macOS 11.1 20C69 (Big Sur) - Intel

### ISSUE THREAD

**Issue by photon6** [docker/for-mac#5183]
- [x] I have uploaded Diagnostics
  - Diagnostics ID: F7F2A8EA-6175-44F7-BE70-649930414A6F/20201224004126

### Expected behavior
I'm expecting Docker Desktop to start after being prompted to upgrade to v3.0.3

### Actual behavior
Docker Desktop 3.0.3 gets stuck in startup "loop"

  - macOS Version: 11.1 (20C69)

### Diagnostic logs
[20201224004126.zip](https://github.com/docker/for-mac/files/5737594/20201224004126.zip)

```
Docker for Mac: version 3.0.3

**Comment by lawrenceelitzer** [comment]
Having the same issue with 3.0.3 and 11.1. Another diagnostics ID: 3808B851-57B6-4B71-AC6B-AE71BDFFC7FE/20201228193253

**Comment by lawrenceelitzer** [comment]
A reinstall of Docker Desktop seems to do the trick!

**Comment by slavick** [comment]
@lawrenceelitzer Thanks, that worked for me too! However, I had to uninstall using the Docker Desktop preferences and not just deleting the app from `/Applications`

**Comment by lawrenceelitzer** [comment]
Ah yes, that is how I uninstalled, sorry didn't specify! Though it was still in /Applications because when I did the drag/drop it said it was still there.
