### ISSUE TITLE
AppleSilicon: Incompatible CPU detecte on A12Z Bionic chip

### ISSUE THREAD

**Issue by medyagh** [docker/for-mac#5185]
Hello and thank you for working on providing docker on the new apple hardware. 

I have received a mac mini with `Apple A12Z Bionic` chip through their `apple developer preview program` for their new CPU architecture. (which must be same as M1 named in public)
I downloaded and installed the `Docker-AppleSilicon-Preview  7`  using [this link ](https://desktop.docker.com/mac/m1preview/Docker-AppleSilicon-Preview7.dmg) on `Big Sur 11.2 Beta`

and I get this error:

```

Environment error
Incompatible CPU detected

We are sorry, but your hardware is incompatible with Docker Desktop.

Docker requires a processor with virtualization capabilities and hypervisor support.
```

is it possible that the "preview Docker" does not detect Apple Development Platform's Apple A12Z Bionic chip as same as M1 ? 

my os is macOs Big Sur 11.2 Beta
![Screen Shot 2020-12-23 at 5 32 22 PM](https://user-images.githubusercontent.com/4564227/103048866-dba44280-4544-11eb-8eb0-06297ce61697.png)
![Screen Shot 2020-12-23 at 5 29 20 PM](https://user-images.githubusercontent.com/4564227/103048867-de069c80-4544-11eb-9620-6cf4411432d8.png)

**Comment by bixou** [comment]
Following [this comment](https://github.com/docker/for-mac/issues/4733#issuecomment-669251520), Docker will never be compatible with A12Z/Apple DTK

**Comment by smithaitufe** [comment]
> Following [this comment](https://github.com/docker/for-mac/issues/4733#issuecomment-669251520), Docker will never be compatible with A12Z/Apple DTK

I think there will be a way around

**Comment by stephen-turner** [comment]
@bixou is correct: Docker Desktop can never run on the A12Z chip because the hardware does not support virtualisation. The A12Z chip is not the same as the M1 chip, it's an iPad chip that they used for the DTK.
