### ISSUE TITLE
Unable to pull from registry-1.docker.io

### ISSUE THREAD

**Issue by dongwei67** [docker/for-mac#5186]
### Expected behavior
docker run -d -p 80:80 docker/getting-started should start the tutorial
### Actual behavior
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: no such host.
See 'docker run --help'.
### Information
reproducible

  - macOS Version: Big Sur 11.1

Docker for Mac: Preview for Apple M1

**Comment by agmalis** [comment]
I'm having the exact same issue from Ubuntu 20.04.

**Comment by hcancelik** [comment]
@dongwei67 do you have `dnsmasq` running in your system? I have to disable it and restart docker in order to get it working but regardless this is not the case for the Intel setup.

**Comment by snellingio** [comment]
I can confirm @hcancelik's suggestion for `dnsmasq` was the issue.

`brew services list` to see the state of homebrew `dnsmasq`
`sudo brew services stop dnsmasq` to stop it

**Comment by dongwei67** [comment]
> @dongwei67 do you have `dnsmasq` running in your system? I have to disable it and restart docker in order to get it working but regardless this is not the case for the Intel setup.

No dnsmasq is not started on my system

**Comment by od3n** [comment]
can reproduce the same error on my machine. disabled `dnsmasq` (been used by Laravel Valet) and restarted Docker does the trick

**Comment by zatorck** [comment]
I had quite different error: 

```
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.6:44220->192.168.64.1:53: read: connection refused
```

But also disabling `dsnmasq` that Laravel Valet is using fixed the issue.

**Comment by mattstauffer** [comment]
I'm on the same version; disabling `dnsmasq` didn't fix it, but I'll try a restart shortly to see if the combination helps.

FWIW, I'm the lead on Valet, so if we need to modify Valet's configuration in any way I'll be happy to help with that. You can see my flailing attempts to fix it in the issue @jasonvarga referenced above: https://github.com/tighten/takeout/issues/209

**Comment by zatorck** [comment]
It's also worth to say that it's not only issue caused by dnsmasq. Also when You restart container with dnsmaqs turned on Docker cannot read date properly and set dates as 1970 in its containers.

**Comment by r4881t** [comment]
I am still facing this issue on my Macbook Air M1 Chip. I dont have `dnsmasq` installed

**Comment by r4881t** [comment]
I am able to resolve this by disabling experimental features. 
<img width="1068" alt="Screenshot 2021-05-14 at 6 53 15 PM" src="https://user-images.githubusercontent.com/81687400/118276791-aa251700-b4e5-11eb-8d3b-b1b767d60cb3.png">
<img width="1095" alt="Screenshot 2021-05-14 at 6 53 10 PM" src="https://user-images.githubusercontent.com/81687400/118276800-ae513480-b4e5-11eb-9fac-5e619c3c47ee.png">

**Comment by achempion** [comment]
Disabling "Use new virtualization framework" in Docker for Mac under "Experimental features" resolved the issue.

@r4881t kudos, was trying to resolve this issue for the past hour, reinstallation didn't help
