### ISSUE TITLE
Feature Request: Please let us turn off automatic updates

### ISSUE THREAD

**Issue by qhenkart** [docker/for-mac#5188]
### Expected behavior

a configuration option to turn off automatic updates

### Actual behavior

Since 3.0, Docker for Mac has created a more streamlined approach to applying updates, however there is no way to turn it off and sometimes updates have breaking changes.

For example, in 3.0.2, https://github.com/docker/for-mac/issues/5124 was fixed, and in 3.0.3 it was reintroduced again breaking my client's docker implementation. The end result is I have to re-install docker from the 3.0.2 installation file every day, since every time I restart docker or restart my computer, it automatically updates. For my clients, this is of course untenable, so I have to recommend them a working version < 3.0 to avoid the automatic updates but maintaining the functionality. 

If there was a configuration option to turn off automatic updates, it would allow us to pin to a stable version when breaking changes or bugs are introduced

**Comment by qhenkart** [comment]
apparently this is a duplicate https://github.com/docker/for-mac/issues/5157

**Comment by Nuru** [comment]
Also a duplicate of #5119
