### ISSUE TITLE
Docker is stuck at starting

### ISSUE THREAD

**Issue by tdgs** [docker/for-mac#5196]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 162AE96D-57A5-488B-A935-9E6E2A332AB4/20201229115013

### Expected behavior
Docker for Mac should start

### Actual behavior

It’s stuck at starting...

### Information

  - macOS Version: 11.1 (Intel CPU)

### Steps to reproduce the behavior

  1. Try to start Docker
  2. ...

**Comment by crebuh** [comment]
Just updated to Big Sur and Docker Desktop ist stuck at the starting process ... already deleted ~/.docker and tried to restart no change

**Comment by williamengbjerg** [comment]
same problem here

**Comment by wesbaker** [comment]
Same problem. I downgraded to 3.0.1 and I had the same problem, then I tried 2.5.0.1 and it's starting again. Might downgrade in the meanwhile.

**Comment by crebuh** [comment]
Today I tried it again and went to the Troubleshoot screen and hit the "Clean / Purge Data" button, after that Docker Desktop was starting correctly again.

The weird thing was, that after cleaning the data, I was still able to recreate all of the existing images and networks (even with volumes), which I thought will be definitely be gone

**Comment by walkah** [comment]
@crebuh can confirm, this fixed the issue on my machine as well.

**Comment by krthr** [comment]
> Today I tried it again and went to the Troubleshoot screen and hit the "Clean / Purge Data" button, after that Docker Desktop was starting correctly again.
> 
> The weird thing was, that after cleaning the data, I was still able to recreate all of the existing images and networks (even with volumes), which I thought will be definitely be gone

Where is the Troubleshoot screen? 😭

**Comment by aldo8** [comment]
> > Today I tried it again and went to the Troubleshoot screen and hit the "Clean / Purge Data" button, after that Docker Desktop was starting correctly again.
> > The weird thing was, that after cleaning the data, I was still able to recreate all of the existing images and networks (even with volumes), which I thought will be definitely be gone
> 
> Where is the Troubleshoot screen? 😭

on top side click  docker icon > troubleshoot
