### ISSUE TITLE
docker not start

### ISSUE THREAD

**Issue by brolinuk** [docker/for-mac#52]
### Expected behavior
start the docker daemon

### Actual behavior
unable to start the daemon. the docker icon showing on the top menu bar keeps flashing.

### Information

Diagnostic ID: A218848E-23E3-48CD-A022-DDBD8B28D223
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. click the docker icon in the applications

**Comment by djs55** [comment]
The docker daemon is not starting because of an AUFS problem:
```
time="2016-08-01T13:41:27.810803308Z" level=debug msg="Using graph driver aufs"
time="2016-08-01T13:41:27.848453735Z" level=debug msg="Failed to load layer sha256:2615ff2c2f8c27913239080269f5be78d541b2564592856548b435f5daa42514: failed to get diff id for sha256:2615ff2c2f8c27913239080269f5be78d541b2564592856548b435f5daa42514: invalid checksum digest format"
time="2016-08-01T13:41:27.852257058Z" level=debug msg="Failed to load layer sha256:3e25a6f54b4ac334ad1c8ec5357ee8c39a5e5be3ad9ebfd776d4a2164a706f32: failed to get diff id for sha256:3e25a6f54b4ac334ad1c8ec5357ee8c39a5e5be3ad9ebfd776d4a2164a706f32: invalid checksum digest format"
time="2016-08-01T13:41:27.852782027Z" level=debug msg="Failed to load layer sha256:4fe15f8d0ae69e169824f25f1d4da3015a48feeeeebb265cd2e328e15c6a869f: failed to get diff id for sha256:4fe15f8d0ae69e169824f25f1d4da3015a48feeeeebb265cd2e328e15c6a869f: invalid checksum digest format"
time="2016-08-01T13:41:27.854668314Z" level=debug msg="Failed to load layer sha256:5c86a5cfb5b67143c7ec277ac533176abb9906072eac82de512f8e822b06e769: failed to get diff id for sha256:5c86a5cfb5b67143c7ec277ac533176abb9906072eac82de512f8e822b06e769: invalid checksum digest format"
time="2016-08-01T13:41:27.858824542Z" level=debug msg="Failed to load mount 65e487d55355485ac73495495ac75a544b5cfd0e8fd371393529480c3ecdd229: invalid mount id value"
time="2016-08-01T13:41:27.860292755Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-01T13:41:27.860544110Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-01T13:41:27.894155657Z" level=debug msg="Cleaning up old mountid : start."
time="2016-08-01T13:41:27.894945706Z" level=fatal msg="Error starting daemon: layer does not exist"
```
This is a duplicate #50

A workaround which should allow docker to start is "Whale menu -> Preferences -> Uninstall/Reset -> Reset to factory defaults". Note this will remove all images and containers, so they will need to be rebuilt :(

There have been lots of bug fixes in docker engine 1.12.1, which is already available on the beta channel. It's worth trying again with this later version.
