### ISSUE TITLE
Conflict with non-existent Virtualbox Machine

### ISSUE THREAD

**Issue by npendery** [docker/for-mac#520]
### Information

Diagnostic ID: 194C0582-36B7-4998-90F6-7EFCF06CC145
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/penderyb/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/194C0582-36B7-4998-90F6-7EFCF06CC145/20160905-124751/qemu-img-check.stdout 2> /tmp/194C0582-36B7-4998-90F6-7EFCF06CC145/20160905-124751/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/penderyb/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/penderyb/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/penderyb/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/penderyb/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/penderyb/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Open Docker Application
2. Error shown

**Comment by mchiang0610** [comment]
@npendery What version of Virtualbox do you have installed? I know there used to be issues with VBox 4.3.x. We've reported it to Oracle and the latest should have it resolved. 

If you still have problems, please reply, and I'll reopen. 
Thanks!
