### ISSUE TITLE
Dashboard / GUI: "Sort by" selection doesn't persist for either Containers/Apps or Images view

### ISSUE THREAD

**Issue by j0hnst0n** [docker/for-mac#5211]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E34A7F21-D62D-4800-8651-813F80CF5897/20210101235033

### Expected behavior
As a developer, I want to select a sort option under "Sort by" in the Containers / Apps and Images views and have it "stick" or persist as I go back and forth between these views.
![image](https://user-images.githubusercontent.com/1610391/103448121-c10b5100-4c49-11eb-963a-e5f77febe831.png)
![image](https://user-images.githubusercontent.com/1610391/103448129-e5672d80-4c49-11eb-9e66-ed4d487bb7be.png)

### Actual behavior
When I select "Status" in the Containers / Apps "Sort by" and then view Images and then go back to Containers / Apps, "Status" is no longer selected.

When I select "In Use" in the Images "Sort by" and then view Containers / Apps and then  go back to Images, "In Use" is no longer selected.

### Information
  - macOS Version: Mojave 10.14.6
![image](https://user-images.githubusercontent.com/1610391/103448196-db91fa00-4c4a-11eb-9cf3-c8a8468f0ae5.png)

### Diagnostic logs
Docker for Mac: 3.0.3 (51017)

### Steps to reproduce the behavior
See above

**Comment by stephen-turner** [comment]
Thanks for the suggestion, @j0hnst0n. I agree with you. I have raised an internal ticket for this.
