### ISSUE TITLE
can't start, always in starting.

### ISSUE THREAD

**Issue by yunmoxue** [docker/for-mac#5215]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86EE7A3F-8F00-4CD6-B863-E2F048BA6480/20210104025751

### Expected behavior
start successfully
### Actual behavior
docker in starting status forever
### Information

  - macOS Version: big sur 11.1

### Diagnostic logs

```
Docker for Mac: 3.0.3

```

### Steps to reproduce the behavior

  1. restart my mac
  2. docker for mac is boot when i log in mac
  3. docker for mac is always starting.
  4. docker for mac is always starting.
  5. docker for mac is always starting.
  6. docker for mac is always starting.
  7. docker for mac is always starting.
  8. docker for mac is always starting.
  9. docker for mac is always starting.

**Comment by yunmoxue** [comment]
When I Clean / Purge data, it works.

**Comment by stephen-turner** [comment]
Glad you fixed it, I'll close the ticket.
