### ISSUE TITLE
Consensus container enabled: No, Consensus container: absent on Mac MIni M1

### ISSUE THREAD

**Issue by rsv** [docker/for-mac#5218]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Consensus container enabled: Yes
Consensus container: present

### Actual behavior
Consensus container enabled: No
Consensus container: absent

### Information

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac: version... 0.0.0(1) Preview 

```

### Steps to reproduce the behavior

  1. Install the Pi Network
  2. ...
![image](https://user-images.githubusercontent.com/3878028/103612431-45273800-4ed9-11eb-8127-1a88d2e758b7.png)

**Comment by stephen-turner** [comment]
Thanks for the report but I think you'll need to file this bug against Pi Network, not against Docker.
