### ISSUE TITLE
Docker wont start

### ISSUE THREAD

**Issue by JuergenSimon** [docker/for-mac#5220]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker starts. 

### Actual behavior
Docker is stuck forever in 'Docker is starting' status and consumes large amounts of CPU

### Information
  - macOS Version: Catalina 10.15.7
  - This problem occurs on two separate machines
  - Tried complete uninstall, purge, reset to factory settings
  - Docker for Mac defunct 100% on Catalina now. 

### Logs
I see the following messages in Console:
default	11:20:09.134035+0000	com.docker.backend	internal: GET /vm/init 500 "DockerDesktopGo" "during /vm/init: cannot fetch ca-certificates.crt: exit status 49"

### Docker for Mac: version...
  - Initially seen with Docker 3.x
  - Downgraded to 2.x version which helped initially, but now it's stuck as well using 2.5.0.1 after latest Catalina Software Update. 

### Steps to reproduce the behaviour
  1. Upgrade to latest Catalina version
  2. Start Docker

**Comment by vegarsti** [comment]
This is also happening on my M1 with the Docker Apple Silicon Preview.

**Comment by harrouet** [comment]
I have this very same issue
