### ISSUE TITLE
M1 tech preview + gRPC-FUSE + Postgres = fail

### ISSUE THREAD

**Issue by rickardp** [docker/for-mac#5221]
This seems to happen when using gRPC+FUSE and bind mounting a directory under $HOME/Documents.

Big Sur protects these directories and needs explicit approval, so this is potentially an issue with this.

### Expected behavior

Postgres boots up using bind mounts over gRPC+FUSE

### Actual behavior

Postgres DB fails to initialize

    running bootstrap script ...
    FATAL:  unexpected data beyond EOF in block 0 of relation base/1/1249
    HINT:  This has been seen to occur with buggy kernels; consider updating your system.
    PANIC:  cannot abort transaction 1, it was already committed

When bind mounting to a directory in the home directory (outside Documents) it works.

Also, touching files in the bind mount directory works, so possibly Postgres is accessing files in a different way that needs more access (memory map? adjust permissions?).

### Information

This is the Tech preview 7 of the M1 build running on Big Sur.

Docker is approved to use the Document directory from the privacy control panel

<img width="352" alt="image" src="https://user-images.githubusercontent.com/167356/103645574-84489e00-4f58-11eb-805c-a382457d1f56.png">

Adding "Full disk access" permission manually did not solve the issue.

I was not able to revert back to osxfuse, but this is not an issue an intel Mac running Docker Desktop stable version that is using osxfuse

### Diagnostic logs

48648ecc-e915-4994-8f82-a93190e6978c/20210105121657

20.10.1, build 831ebeae96

### Steps to reproduce the behavior

  1. Start postgres container (9.6 through 13.1 was tested) with its data bind mounted to a directory under Documents
  2. Observe above failure

**Comment by stephen-turner** [comment]
I'm a bit confused, isn't this an issue of M1 vs Intel, not grpcfuse not osxfs? Or do you have some reason to believe otherwise?

**Comment by rickardp** [comment]
To be fair, I don't know since I am unable to start Docker with the gRPC+FUSE checkbox unchecked (I assume the driver is Intel only). The differences between the working Mac and the non-working one are:

* gRPC+FUSE / osxfs
* M1 /  Intel
* tech preview / stable

so the culprit could be any one of those. Since it looked like this was related to bind mounts and protected directories, I may have jumped to conclusions and assumed the completely new filesystem driver was the most likely culprit

**Comment by stephen-turner** [comment]
Thanks for the explanation. Could you test it on your Intel Mac with grpcfuse? That should narrow down which it is.

**Comment by rickardp** [comment]
I managed to get my work in a state where I dared to reenable system integrity protection and reinstall Docker on my intel Mac and indeed the issue is not present on the current stable version of Docker (Docker version 20.10.0, build 7287ab3)

The command line I tried was 

    docker run --platform linux/amd64 -v $PWD/pgsql:/data -e PGDATA=/data --rm -it -e POSTGRES_PASSWORD=kalleanka postgres:13.1-alpine

This fails on the tech preview 7 when run on a protected volume using the gRPC+Fuse driver. The system prompt to grant access comes up, but Postgres is unable to write to it, as per the original errors.

**Comment by stephen-turner** [comment]
Great, thanks for checking. So it looks like the AMD64 version of the postgres container can't run under qemu.

**Comment by rickardp** [comment]
Same error occurs using the ARM64 version. And image works fine when $PWD is outside of the protected file system (e.g. outside Documents or Downloads)

**Comment by rickardp** [comment]
For completeness, I ran the following two commands on both machines

    docker run --platform linux/arm64 -v $PWD/pgsql:/data -e PGDATA=/data --rm -it -e POSTGRES_PASSWORD=kalleanka postgres:13.1-alpine

    docker run --platform linux/amd64 -v $PWD/pgsql:/data -e PGDATA=/data --rm -it -e POSTGRES_PASSWORD=kalleanka postgres:13.1-alpine

On both Macs, file system was gRPC+FUSE.

On the Intel Mac running the stable Docker version, both worked in both Document and the home directory. On the M1 Mac, both worked in the home directory. None worked in the Document directory. Running Bash allowed me to touch files in the bind mounts OK, so I assume Postgres does some I/O that does not work.

**Comment by stephen-turner** [comment]
Interesting, so not qemu. Are the two Macs running the same version of MacOS?

**Comment by rickardp** [comment]
Yes. Big Sur 11.1

**Comment by stephen-turner** [comment]
OK, thanks for all your help. We'll investigate.

**Comment by xros** [comment]
> For completeness, I ran the following two commands on both machines
> 
> ```
> docker run --platform linux/arm64 -v $PWD/pgsql:/data -e PGDATA=/data --rm -it -e POSTGRES_PASSWORD=kalleanka postgres:13.1-alpine
> 
> docker run --platform linux/amd64 -v $PWD/pgsql:/data -e PGDATA=/data --rm -it -e POSTGRES_PASSWORD=kalleanka postgres:13.1-alpine
> ```
> 
> On both Macs, file system was gRPC+FUSE.
> 
> * On the Intel Mac running the stable Docker version, both worked in both Document and the home directory.
> * On the M1 Mac, both worked in the home directory, while none worked in the Document directory.
> 
> Running Bash allowed me to touch files in the bind mounts OK, so I assume Postgres does some I/O that does not work.

@rickardp , maybe it's the privilege issue? On MacOS 11 big sur, programs need privileges to open user folders such as `Documents`. Did you try?

**Comment by MrThePlague** [comment]
FWIW I'm experiencing the same behaviour with the `php:7.4.12-apache` but _not_ the PostgreSQL image (currently using `postgres:11.6`). It's possible to use the workaround of adding the `--platform linux/arm64` flag; however, that's not an option when using `docker-compose` v3, and doesn't seem to work when trying to use a v2 compose file.

**Comment by rickardp** [comment]
@xros Yes, Docker got privileges to both directories. I can also touch files in those directories via e.g. the busybox image. Other containers work. Maybe Postgres needs more than just write access to files? Not sure how memory maps etc works w.r.t fuse. I could maybe try to run strace on it, but I am not sure how to do that from inside the Postgres container.
