### ISSUE TITLE
Proxy settings do not work on M1 Tech Preview

### ISSUE THREAD

**Issue by rgov** [docker/for-mac#5225]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  DF456B89-F179-4AE3-90C4-D6A1DE6CF1DD/20210105214006

### Expected behavior

Docker for Mac should automatically use macOS's configured proxy settings. It should be possible to override proxy settings from the client side.

### Actual behavior

The Tech Preview docs say,

> The HTTP proxy is not enabled.

Obviously the missing feature is known by Docker developers, but this issue can be used for associated discussion, and potential workarounds.

### Information

  - macOS Version: 11.1 (Apple Silicon)

---

👉 **Please use "Subscribe" in the right hand panel to follow this issue, rather than add "me too" comments.** 👈

**Comment by bpresles** [comment]
Just for the record, I've tried to workaroung this known issue by using Proxifier. While Proxifier works for other apps (i.e: I can connect to services only available via the proxy even with apps not having http proxy support), it doesn't work for Docker, I still have a "request timeout" error while trying to pull images from an internal repository only accessible through a proxy.

**Comment by rgov** [comment]
Allegedly fixed in the release candidate.

**Comment by bpresles** [comment]
I tried to use a proxy with latest RC1 version for M1, and when I do a "docker login" I get:

Error response from daemon: Get https://<registry_url>/v2/: Bad Gateway

I setup the proxy settings using HTTPS proxy that is accessed using a SSH tunnel binding port on localhost.
