### ISSUE TITLE
git push pending

### ISSUE THREAD

**Issue by cainiaokan** [docker/for-mac#5226]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: CEBD7B23-123F-4DF7-A558-EC369C79174C/20210106025357

### Expected behavior
docker push succeed.
### Actual behavior
docker push is pending.
### Information
docker push command is always pending on my mac pro. I tried purge data/reset to factory defaults/reinstall and none of them solve the problem. I checked my proxy settings and it is unset.  Nevertheless my colleagues can push docker image under the same network environment and same docker version & macOS version.

  - macOS Version: 11.1 Big Sur

### Diagnostic logs

```
Docker for Mac: 3.0.3(51017)

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Is there some corporate security / firewall that is blocking the push?

**Comment by cainiaokan** [comment]
> push

**Comment by cainiaokan** [comment]
> Is there some corporate security / firewall that is blocking the push?

It's weird. After my mac pro connect to the vpn of my company and suddenly it worked just fine. However the `docker pull` command can execute successfully with or without the vpn through...

**Comment by stephen-turner** [comment]
Good, glad you solved it and thanks for letting us know.
