### ISSUE TITLE
"Check for Updates..." always fails to check for updates

### ISSUE THREAD

**Issue by sashaafm** [docker/for-mac#5230]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1C32E443-6253-44C9-9C33-C0823C9C3F4C/20210107111819

### Expected behavior
This functionality would successfully check for updates and would indicate if an update is available or not.

### Actual behavior
Always receive the message: "Update Error! An error occurred in retrieving update information. Please try again later."

### Information
  - macOS Version: 11.1 20C69
  - Macbook: MacBook Pro (Retina, 15-inch, Mid 2015)
  - Reproducible: Yes, in my local machine. No idea how to achieve this state to replicate the issue with another machine.

### Diagnostic logs
Diagnostics are over 120MB so I believe it's best to just leave the ID: 1C32E443-6253-44C9-9C33-C0823C9C3F4C/20210107111819
```
Docker for Mac: version 2.5.2 (50165)
Engine: 20.10.0-rc1

```

**Comment by stephen-turner** [comment]
Do you have some sort of firewall or corporate security in place that is blocking traffic to desktop.docker.com?

**Comment by sashaafm** [comment]
@stephen-turner I'm working from home and AFAIK no firewall or security in my network. I moved in recently to this place (about 4 months ago) and I'm pretty sure I've updated Docker a few times until now.

I seem to be able to reach that host via `ping`:
```
% ping desktop.docker.com
PING desktop.docker.com (13.224.119.106): 56 data bytes
64 bytes from 13.224.119.106: icmp_seq=0 ttl=241 time=62.775 ms
64 bytes from 13.224.119.106: icmp_seq=1 ttl=241 time=60.615 ms
^C
--- desktop.docker.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 60.615/61.695/62.775/1.080 ms
```

**Comment by stephen-turner** [comment]
Can you get to https://desktop.docker.com/mac/edge/appcast.xml in a browser?

**Comment by sashaafm** [comment]
@stephen-turner guess so. It seems to be a feed (maybe RSS) and it tries to open my Feedly app as expected so it seems to be working correctly.

**Comment by stephen-turner** [comment]
Hmmm, I'm not sure what else to suggest. The error comes from the third party library we use for the updates, sparkle-project/Sparkle, but I can't imagine why it would fail for you. I can only think that there must be something specific in your local setup that is blocking or modifying the file.

**Comment by avarun42** [comment]
Getting the same error here. Also WFH with no firewall.

**Comment by kekkis** [comment]
Same for me. Version info:

MacOS: 10.15.7
Macbook: 15" 2018

Docker for Mac: version 2.5.1.0 (49923)
Channel: edge
Engine: 20.10.0-rc1

**Comment by mat007** [comment]
Can you open `Console.app`, in the filter box at the top right type `sparkle` then enter, then try do to a «Check for updates» and see what that prints in the Console?

**Comment by kekkis** [comment]
Sorry, I already circumvented the problem by uninstalling docker-edge (using Homebrew) and installing 3.0.4 in its stead. I suspect that the issue is that with major version 3, Docker gave up on the edge channel and so update info for that can't be found anymore.

**Comment by stephen-turner** [comment]
It's supposed to work transparently for updating from 2.5 edge to 3.0 stable (and is working for most people, but it seems a handful are having problems). The correct information does seem to be in the appcast.xml.

**Comment by StefanScherer** [comment]
We are working on a fix for the HTTP redirects to make it work with sparkle.

**Comment by StefanScherer** [comment]
Thanks again for reporting this. We've fixed the redirects. The scheduled or manual "Check for Updates" now works for Docker Desktop Edge users again.
