### ISSUE TITLE
Hyperkit running all the time

### ISSUE THREAD

**Issue by joelbernstein** [docker/for-mac#5231]
I've noticed that even if Docker for Mac is not running, I constantly have a com.docker.hyperkit process running which never uses less than 20% of CPU. Why is this running all the time? How do I make it only run when I start Docker?

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joelbernstein** [comment]
Seems that com.docker.hyperkit is sometimes left running when Docker for Mac is quit while it's still starting up.

I can't reproduce it reliably but it's happened to me a few times. `kill -9` is sufficient to resolve it, but it's annoying as it takes up 2GB of RAM (since this is what my docker vm settings are).

**Comment by Apollorion** [comment]
Myself and a few coworkers are also seeing this and in addition to memory consumption, it also turns our MacBook into an airplane because it's eating CPU cycles. Able to provide any logs if needed. Usually just restarting docker for mac fixes it. I am on the latest version of docker desktop and Catalina.

**Comment by baperks** [comment]
I just installed Docker CE for the first time, as I am learning how to use it. Even after I had shut the containers down, with the Desktop program still open, the com.docker.backend process was continually spiking the CPU over 100%, while com.docker.hyperkit had the container image still loaded, which in this case, was about 3.5GB of RAM. My MacBook Pro is Intel-based, recent, runs the latest Big Sur version (11.1) and it sounded like an airplane engine. I shut Docker Desktop down completely and all the symptoms are gone. Any ideas on how to resolve it? I'm wondering what will happen when I have to use it for longer than a half hour.

**Comment by Apollorion** [comment]
@baperks After reading through a few other issues in this repo that felt related to this, I found that if you disabled `gRPC FUSE` in docker desktop for mac this issue seemingly goes away. I've had it disabled all day today and haven't seen CPU related issues yet.

**Comment by baperks** [comment]
@Apollorion Yes, thanks for that tip. I saw that suggested in #5116 as well as another tip of not mounting the container to the HOME directory, but to do so on a more specific directory inside that. I tried to latter to good effect so far. When I have time later, I will try disabling gRPC FUSE. Thanks!

**Comment by kuberlog** [comment]
This has been an issue for as long as I can remember. I don't expect it to be fixed.
