### ISSUE TITLE
Creating a Laravel container image fails

### ISSUE THREAD

**Issue by cmutoh** [docker/for-mac#5237]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
All containers for Laravel project are set up

### Actual behavior
After run the commmands below;
```
git clone git@github.com:ucan-lab/docker-laravel.git
$ cd docker-laravel
$ make create-project
```
the error message below is shown at the end;
```
ERROR: Service 'db' failed to build : no matching manifest for linux/arm64/v8 in the manifest list entries
```

Also, some errors are shown. For example, it was about locale.
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
+ apt-get update
```

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:en",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
```

### Information

  - macOS Version: macOS Bigsur 11.1

### Diagnostic logs

```
Docker for Mac:  
Docker version 20.10.1, build 831ebeae96
docker-compose version 1.27.4, build 40524192

```

### Steps to reproduce the behavior

  1. Install docker desctop preview app for M1
  2. Access to https://github.com/ucan-lab/docker-laravel and follow the instructions
  3. That is, run the commands below;
```
git clone git@github.com:ucan-lab/docker-laravel.git
$ cd docker-laravel
$ make create-project
```

**Comment by jamielsharief** [comment]
The error you are getting is because the official MySQL images do not support ARM processors.
