### ISSUE TITLE
Docker Desktop (Preview for M1) is not able to start

### ISSUE THREAD

**Issue by tobtherusch** [docker/for-mac#5238]
- [x] I have tried with the latest version of Docker Desktop (preview for m1)
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DCDABD27-98E7-4170-899E-CB63059AC5CC/20210111151612

### Expected behavior
Docker Desktop Preview (for m1) should start as on intel chips

### Actual behavior
Docker Desktop Preview (for m1) is not able to boot.
I also tried to boot it with switched off firewall.
When executing `docker ps` at this time I get:
```
~  docker ps
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory
```

### Information

  - macOS Version: 11.1 (20C69)

### Diagnostic logs

```
Docker for Mac: Docker version 20.10.1, build 831ebeae96

```

### Steps to reproduce the behavior

  1. Install docker desktop preview https://docs.docker.com/docker-for-mac/apple-m1/
  2. Start docker desktop

**Comment by pckilgore** [comment]
Same issue, same macOS version, just to confirm my Preview version is 7.

**Comment by pckilgore** [comment]
Interesting.  I just noticed docker finally finished "starting" (it has been that way through several restarts).  The only thing I did recently was run the diagnostic to finally make the report above, and install a new version of macos fuse for another piece of software.

**Comment by tobtherusch** [comment]
I noticed in the log:
```
 ~  tail -f ~/Library/Containers/com.docker.docker/Data/vms/0/console.log                                                                                                ✔  base   15:03:37
[    2.209467] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: (null)
Failed to connect to logger: dial unix /var/run/memlogdq.sock: connect: no such file or directory
Failed to connect to logger: dial unix /var/run/memlogdq.sock: connect: no such file or directory
[    2.289917] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    2.478348] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Failed to connect to logger: dial unix /var/run/memlogdq.sock: connect: no such file or directory
Failed to connect to logger: dial unix /var/run/memlogdq.sock: connect: no such file or directory
INFO[0002] connecting to tcp+connect://192.168.64.1:1999...
INFO[0033] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0035] connecting to tcp+connect://192.168.64.1:1999...
INFO[0067] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: connection timed out
INFO[0069] connecting to tcp+connect://192.168.64.1:1999...
```

**Comment by caroalvarezsilva** [comment]
Same issue. Any idea how to fix it?

**Comment by Gsync** [comment]
I get the following fatal error on startup, tried installing the preview 7 a few times without any luck

StartAll failed: cannot start /Applications/Docker.app/Contents/MacOS/com.docker.osxfs: fork/exec /Applications/Docker.app/Contents/MacOS/com.docker.osxfs: bad CPU type in executable

**Comment by OXIDFabian** [comment]
Same issue
89719EC3-3D18-4EC5-89E9-094A37E94888/20210118122708

**Comment by hcancelik** [comment]
Same issue
323B04EB-8162-4474-ACA7-0B2248FC415B/20210120180256

**Comment by uberism** [comment]
The solution for me was to install Rosetta.

On a fresh apple silicon machine, I had the same issue. But when I went to download nodejs, it prompted me to also install Rosetta and Docker preview 7 worked for me.

**Comment by simondeeley** [comment]
[console.log](https://github.com/docker/for-mac/files/5859236/console.log)

**Comment by rainycow** [comment]
I had the same issue! Wanted to install nodejs as suggested above, realised homebrew hasn't been installed on the new MacBook so I went ahead to install it and Docker preview 7 works now (without actually having nodejs for my case)!

**Comment by nikosanif** [comment]
Same issue. I had to turn off the firewall, then it started successfully.

**Comment by ams0** [comment]
I have Rosetta 2 (first thing ever installed on the mini), turned firewall on and off, no luck

**Comment by emma-r-slight** [comment]
Turning off firewall worked for me.

**Comment by weibaohui** [comment]
Same issue
88b91976-711c-4e8b-b204-b7245e648400/20210130164725

**Comment by ams0** [comment]
I reinstalled my Mini M1 (be mindful, remove it from your iCloud account before reinstalling) and Docker works again. Not a solution, but someone might be as desperate as me and do it anyway.

**Comment by clairegraham** [comment]
I had the same issue, despite Docker Preview working fine since the preview came out for the M1 series. I recently enabled the built-in firewall in Mac and that appears to have caused Docker to never start (the app starts, but the daemon does not, so `docker ps -a` fails. I disabled the firewall and now it starts and works fine.

**Comment by weibaohui** [comment]
try this one:
https://desktop.docker.com/mac/stable/arm64/60902/Docker.dmg

this works for me

**Comment by clairegraham** [comment]
> try this one:
> https://desktop.docker.com/mac/stable/arm64/60902/Docker.dmg
> 
> this works for me

I tried it, but it didn't work either, unless I disable the firewall again. Did you make any other system modifications to get it to work? Specifically with the firewall, or with ifconfig?

Similar messaging in console.log (this loops forever):

```
INFO[0066] connecting to tcp+bootstrap+client://gateway.docker.internal:49474/dceda115b67f81e097fc01935a027fe44971bd978dab3c468be886a5c132bbd0...
INFO[0066] cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable
INFO[0068] connecting to tcp+bootstrap+client://gateway.docker.internal:49474/dceda115b67f81e097fc01935a027fe44971bd978dab3c468be886a5c132bbd0...
INFO[0068] cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable
```

It seems like ``` /Library/PrivilegedHelperTools/com.docker.vmnetd``` needs to be added to the Mac firewall somehow, but it appears you cannot do it from the system preferences firewall GUI, maybe because it's in the PrivilegedHelperTools folder?

I found this command from googling:
```sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /Library/PrivilegedHelperTools/com.docker.vmnetd```

But it returns with the error:

```The file path you specified is invalid```

**Comment by seffyB** [comment]
Same issue
7E3F7B0C-047F-4C9C-A4B3-6E885394E3B2/20210212192416

Similar logs to others, which continuously loops
```
connecting to tcp+bootstrap+client://gateway.docker.internal:49889/10d99b61c03837b7e6d59f6cb8ba3572e86fd31c607d3667b7838badaa4219b3...
cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable```

Disabling the firewall resolved the issue for me

**Comment by mikestecker** [comment]
Same issue with the firewall for me:

```
[36mINFO[0m[0106] connecting to tcp+bootstrap+client://gateway.docker.internal:62966/57bfba08db3b2a5e82c6a48dea2276ee66f01e319f17cdf5c5e5c08c98e05c03... 
[36mINFO[0m[0106] cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable 
```

Disabling firewall fixed this.

**Comment by jwkicklighter** [comment]
Just giving another confirmation that enabling the firewall caused Docker startup to fail, and disabling it fixed the problem.

**Comment by Willianvdv** [comment]
I can't disable the firewall on my Air M1 due to MDM. However, what's interesting to me is that for me a simple reboot solves this problem. Unfortunately, it's only a matter of time until I'll get the same network unreachable error and I have to reboot once again.

**Comment by mbatesco** [comment]
Running the same issue with 3.1.0.  I had to disable the firewall to get Docker to works fine even with the VPN up and running. Bridge100 is using  192.168.64.1.

What else can I provide that will help?

**Comment by mrmarbury** [comment]
I am facing the problem that @clairegraham is facing. But disabling the firewall does not fix it. Even changing the DNS entry in ~/.docker/settings.json to a localhost DNS proxy does not help. In fact the change is not even picked up.

**Comment by luca-mayven** [comment]
+1 here. Same issue and failing to start on M1 chip

**Comment by mrmarbury** [comment]
Unfortunately the 8.8.8.8 network unreachable error is still present in RC1

**Comment by pujanb96** [comment]
Same issue on my mac m1. The firewall is off, but no luck with getting docker started. It appears open in activity monitor but when i try to run `docker ps` I get the error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by shreyagupta30** [comment]
> Same issue on my mac m1. The firewall is off, but no luck with getting docker started. It appears open in activity monitor but when i try to run `docker ps` I get the error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

HI @pujanb96, were you able to solve this issue?

**Comment by pujanb96** [comment]
> > Same issue on my mac m1. The firewall is off, but no luck with getting docker started. It appears open in activity monitor but when i try to run `docker ps` I get the error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
> 
> Hi @pujanb96, were you able to solve this issue?

Yes. I uninstalled the existing installation and installed rosetta using the following command - 
`softwareupdate --install-rosetta`

After that, I installed the latest version of docker for mac m1 from https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by shreyagupta30** [comment]
Thanks @pujanb96

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still startup issues, please open a new ticket with diagnostics.
