### ISSUE TITLE
Apple Silicon: Automatic detection of the CPU-architecture of the pull/run image

### ISSUE THREAD

**Issue by kkeker** [docker/for-mac#5239]
- [+] I have tried with the latest version of Docker Desktop
  - [+] I have tried disabling enabled experimental features

### Information

  - macOS Version: 11.1

### Diagnostic logs

```
Docker for Mac:
Version:  20.10.1 build 831ebeae96 [0.0.0 (1)]
Engine: 20.10.0
Compose: 1.27.4
Kubernetes: v1.19.3
Notary: 0.6.1
Credential Helper: 0.6.3
Snyk: v1.424.4

```

### Steps to reproduce the behavior

At the moment, there are two problems with the `docker pull` and `docker run` commands for Apple M1 - Docker does not automatically detect the host architecture of the macOS CPU and does not substitute it for searching in the image repository. This will cause Docker to crash and shut down if no architecture is specified. Example: `docker run postgres:13-alpine` will crash and close. This works correctly if you execute `docker run arm64v8/postgres:13-alpine`. In the case of the `docker pull` command, the image simply does not download. It would be nice if Docker could automatically detect the macOS CPU architecture and substitute it for images on its own. And also, there would be an error handling when trying to pull/run an image of the wrong architecture.

**Comment by stephen-turner** [comment]
I don't have an M1 machine to check, but I thought that it did exactly as you suggest and pull the correct architecture (assuming it's a multiarch image).

It's not an error to pull a different architecture, you should still be able to run it using qemu.

**Comment by kkeker** [comment]
At the moment, there are two errors in the Preview version as I described. If you do not specify the architecture, then "pull" does not download the image, and "run" causes the application to crash and close.

**Comment by StefanScherer** [comment]
Thanks @kkeker for the report. I also assume that the preview already automatically uses the arm64 images from multi-arch images. 
I did a quick check on one of our M1  machines and it works fine for me:

```
$ docker run postgres:13-alpine
Unable to find image 'postgres:13-alpine' locally
13-alpine: Pulling from library/postgres
159e5727ea61: Already exists 
d20223af9aac: Pull complete 
2482f57ac4ab: Pull complete 
c8812dbcb6a5: Pull complete 
afb4f04eea5c: Pull complete 
3f725905c09b: Pull complete 
8bbfc23e7ec3: Pull complete 
469ca852de68: Pull complete 
Digest: sha256:0b6f8681377407396a54512812789bd311afd40b2b4e2bd66e9d98da6632bd8e
Status: Downloaded newer image for postgres:13-alpine
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html

$ docker inspect --format "{{ .Architecture }}" postgres:13-alpine
arm64

$ docker pull postgres:13-alpine
13-alpine: Pulling from library/postgres
Digest: sha256:0b6f8681377407396a54512812789bd311afd40b2b4e2bd66e9d98da6632bd8e
Status: Image is up to date for postgres:13-alpine
docker.io/library/postgres:13-alpine

$ docker pull arm64v8/postgres:13-alpine
13-alpine: Pulling from arm64v8/postgres
Digest: sha256:00ad028fbc953c4ee916521113da71e2894b739f9c8934ed7a3c854d19a7626e
Status: Downloaded newer image for arm64v8/postgres:13-alpine
docker.io/arm64v8/postgres:13-alpine

$ docker images
REPOSITORY                  TAG                                              IMAGE ID       CREATED         SIZE
arm64v8/postgres            13-alpine                                        66659230f7b7   12 days ago     157MB
postgres                    13-alpine                                        66659230f7b7   12 days ago     157MB
alpine                      latest                                           afeebe901d6b   3 weeks ago     5.32MB
debian                      latest                                           1b0fae9b3949   4 weeks ago     108MB
ppc64le/fedora              26                                               3accc15019e6   19 months ago   297MB
```

I have preview 7 installed, unfortunately you can't see the exact version number in the about window.

**Comment by kkeker** [comment]
Hmm... I'm sorry, but somehow early on, both problems actually disappeared. [I recorded a video](https://drive.google.com/file/d/1uaBs6DHP7O31VpO8nht8DHePTld-DOA5/view) showing that everything works without problems. I close my issue.

**Comment by stephen-turner** [comment]
OK, thanks. Please do let us know if it happens again.
