### ISSUE TITLE
docker failed

### ISSUE THREAD

**Issue by davidyao** [docker/for-mac#525]
### Information

Diagnostic ID: FE301383-62C7-46AF-A9E5-8F74E3292030
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/David/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/FE301383-62C7-46AF-A9E5-8F74E3292030/20160906-170001/qemu-img-check.stdout 2> /tmp/FE301383-62C7-46AF-A9E5-8F74E3292030/20160906-170001/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. following the tutorial to create a whale image from dockerfile, system restart unexpectively
2. docker failed to start ever after

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in FE301383-62C7-46AF-A9E5-8F74E3292030/20160906-170033.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.vmnetd][98324] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.vmnetd][98324] <Notice>: User 501 has container folder /Users/David/Library/Containers/com.docker.docker/Data/s60
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.vmnetd][98324] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.docker][98310] <Error>: Symlinks are not correctly installed.
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.docker][98310] <Notice>: com.docker.osx.hyperkit.linux launched with PID 98327
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][98327] <Notice>: Acquired task manager lock
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][98327] <Notice>: Maximum number of file descriptors is 10240
Sep  5 15:21:57 YaoJingweis-MacBook-Pro Docker[com.docker.osx.hyperkit.linux][98327] <Notice>: Starting com.docker.db, com.docker.osxfs, com.docker.slirp, com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux
```
