### ISSUE TITLE
Docker Desktop (Preview for M1) is not able to start dial unix docker.raw.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by caroalvarezsilva** [docker/for-mac#5252]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I get **Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory** trying to run docker by command line, and Dockers runnnig by the IDE.
Version:           20.10.1
### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
@caroalvarezsilva Could you please upload diagnostics from the support page in the app, and then paste the diagnostics id here? Thank you.

**Comment by stephen-turner** [comment]
Ah, I now see you already did that in #5253 thank you, so I'll close this one as a dupe.
