### ISSUE TITLE
M1 preview: Docker always starting – dial unix docker.raw.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by caroalvarezsilva** [docker/for-mac#5253]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
I get **Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory** trying to run docker by command line, and Dockers runnnig by the IDE.
Version: 20.10.1

### Information

  - macOS Version: Mac OSBigSur 11.0.1

Report issue> 6B14D24D-D134-4059-B90B-96E86A642DC5/20210114193921

**Comment by simondeeley** [comment]
Same issue for me too.  However, Docker was working perfectly fine (Mac M1 OS 11.1) until MacOS itself force-restarted the laptop due to an unknown fatal error.  Since then, Docker has not worked.

**Comment by infostreams** [comment]
Workaround:

1. Install [AppCleaner](https://freemacsoft.net/appcleaner/)
2. Open the Finder and go to Applications
3. Delete the Docker application
4. Click "Confirm" in the popup that AppCleaner shows, to delete all "related" files that Docker installed
5. Re-install Docker for M1 from https://docs.docker.com/docker-for-mac/apple-m1/
6. Repeat when you have to reboot
7. 😕

**Comment by fiefdx** [comment]
I use method from this link: https://forums.docker.com/t/restart-docker-from-command-line/9420
stop & start docker manually, and, it's work.

How to control Docker for Mac from the CLI
Stop Docker for Mac gracefully
```bash
test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'
```
Note: Requires all Docker containers in the stopped state

Stop all Docker containers without confirmation (dangerous if running something)
```bash
docker ps -q | xargs -L1 docker stop
```
Note: Assumes all running Docker containers are in a quiesced state

Start Docker gracefully
```bash
open --background -a Docker
```
Note: It may take up to a minute for Docker to fully start

**Comment by jiahuigeng** [comment]
> Workaround:
> 
> 1. Install [AppCleaner](https://freemacsoft.net/appcleaner/)
> 2. Open the Finder and go to Applications
> 3. Delete the Docker application
> 4. Click "Confirm" in the popup that AppCleaner shows, to delete all "related" files that Docker installed
> 5. Re-install Docker for M1 from https://docs.docker.com/docker-for-mac/apple-m1/
> 6. Repeat when you have to reboot
> 7. 😕

not work for me, anyone succeeds?

**Comment by jackgray** [comment]
> ```shell
> open --background -a Docker
> ```



> I use method from this link: https://forums.docker.com/t/restart-docker-from-command-line/9420
> stop & start docker manually, and, it's work.
> 
> How to control Docker for Mac from the CLI
> Stop Docker for Mac gracefully
> 
> ```shell
> test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'
> ```
> 
> Note: Requires all Docker containers in the stopped state
> 
> Stop all Docker containers without confirmation (dangerous if running something)
> 
> ```shell
> docker ps -q | xargs -L1 docker stop
> ```
> 
> Note: Assumes all running Docker containers are in a quiesced state
> 
> Start Docker gracefully
> 
> ```shell
> open --background -a Docker
> ```
> 
> Note: It may take up to a minute for Docker to fully start

This fixed it for me

**Comment by naklar** [comment]
For me both solutions didn't work

**Comment by borbier** [comment]
Report issue : 9CB11941-A621-44D4-8E9F-78E3E9F8BA1F/25640218072511

**Comment by GoldGliders** [comment]
I faced the same issue, but I solved it below method.

1. Uninstall the docker preview app in the troubleshoot page on the dashboard
2. Re-install it
3. Open it
4.  Type password **correctly**
5. Login docker account

I think this issue may cause due to password typo or something related to docker account.

**Comment by CharafouddineAhmed** [comment]
> I use method from this link: https://forums.docker.com/t/restart-docker-from-command-line/9420
> stop & start docker manually, and, it's work.
> 
> How to control Docker for Mac from the CLI
> Stop Docker for Mac gracefully
> 
> ```shell
> test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'
> ```
> 
> Note: Requires all Docker containers in the stopped state
> 
> Stop all Docker containers without confirmation (dangerous if running something)
> 
> ```shell
> docker ps -q | xargs -L1 docker stop
> ```
> 
> Note: Assumes all running Docker containers are in a quiesced state
> 
> Start Docker gracefully
> 
> ```shell
> open --background -a Docker
> ```
> 
> Note: It may take up to a minute for Docker to fully start

@fiefdx 's solution worked for me. Merci

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still startup issues, please open a new ticket with diagnostics.

**Comment by jedi-ux** [comment]
Same problem on Mac M1 : Big Sur 11.4 beta 4..

Docker wont run,

Problem 1 : It hangs on Init,when I try to install any container :

Error response from daemon: dial unix docker.raw.sock: connect: connection refused ""

<img width="1428" alt="Screenshot 2021-05-11 at 20 47 49" src="https://user-images.githubusercontent.com/82736855/117868914-70ac9b80-b29a-11eb-9755-e1b6ab8f539e.png">
<img width="1414" alt="Screenshot 2021-05-11 at 20 48 01" src="https://user-images.githubusercontent.com/82736855/117868924-73a78c00-b29a-11eb-9d0e-1d76813e56ea.png">

**Comment by imaxrider** [comment]
<img width="455" alt="Screen Shot 2564-06-08 at 13 22 58" src="https://user-images.githubusercontent.com/25847855/121133882-108b2400-c85d-11eb-98a5-488551e4b8fb.png">

Go to folder ~/.docker

1.Uninstall docker
2.Delete  folder .docker
3.Install docker again

Work for me
