### ISSUE TITLE
OS X 10.13 is not supported

### ISSUE THREAD

**Issue by WolfgangFahl** [docker/for-mac#5256]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Should work
### Actual behavior
Doesn't work - worse - it displays a message every day that it doesn't work.
### Information
- macOS Version:
High Sierra 10.13.6

### Steps to reproduce the behavior
Keep your precious old Macs e.g. Mac Pro which can't upgrade the OS
Keep docker installed expecting that there will be Long Term Support
Get disappointed and loose your investment

**Comment by stephen-turner** [comment]
Sorry, we do not have the resources to be able to support old OSes. Our documented policy for several years has been to support only the current version of MacOS and the previous two.
