### ISSUE TITLE
M1 tech preview 7 not working with image: roribio16/alpine-sqs:latest

### ISSUE THREAD

**Issue by Silve2611** [docker/for-mac#5257]
I am trying to launch [roribio16/alpine-sqs:latest](https://hub.docker.com/r/roribio16/alpine-sqs/) but I keeps crashing due to a segmentation fault SIGSEGV.

### Expected behavior
It should rund the alpine-sqs queue

### Actual behavior
Crashing on launch

### Information

  - macOS Version: macOS Big Sur 11.1 (20C69)

### Diagnostic logs
```
08:43:48.844 [main] INFO org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.0) ...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021-01-15 08:43:49,037 INFO exited: elasticmq (terminated by SIGSEGV; not expected)
listening on port 9325
2021-01-15 08:43:49,179 INFO spawned: 'elasticmq' with pid 90
Error on queue "dev_third-party": SQS receive message failed: connect ECONNREFUSED 127.0.0.1:9324
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021-01-15 08:43:50,438 INFO success: elasticmq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-15 08:43:50,441 INFO exited: elasticmq (terminated by SIGSEGV; not expected)
Error on queue "dev_mail": SQS receive message failed: connect ECONNREFUSED 127.0.0.1:9324
2021-01-15 08:43:50,951 INFO spawned: 'elasticmq' with pid 107
Error on queue "dev_ticket": SQS receive message failed: connect ECONNREFUSED 127.0.0.1:9324
2021-01-15 08:43:51,956 INFO success: elasticmq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021-01-15 08:43:52,155 INFO exited: elasticmq (terminated by SIGSEGV; not expected)
2021-01-15 08:43:53,115 INFO spawned: 'elasticmq' with pid 124
2021-01-15 08:43:53,116 WARN received SIGTERM indicating exit request
2021-01-15 08:43:53,117 INFO waiting for insight, elasticmq to die
2021-01-15 08:43:53,131 INFO stopped: insight (terminated by SIGTERM)
2021-01-15 08:43:53,132 INFO stopped: elasticmq (terminated by SIGTERM)
```
Docker for Mac: Docker-AppleSilicon-Preview7

### Steps to reproduce the behavior
  1. Get [roribio16/alpine-sqs:latest](https://hub.docker.com/r/roribio16/alpine-sqs/)
  2. Launch image

**Comment by Silve2611** [comment]
Is there anything I can do to help? Are there some logs I could provide or other details that would help narrow down the problem?

**Comment by Silve2611** [comment]
@stephen-turner Here is the Diagnostic ID: DD38FAD7-99C4-4949-A9AF-20EA92EA136E/20210121102812
Hope it helps. I have seen in other posts that you ask for it.

**Comment by stephen-turner** [comment]
If it's only this container, it's almost certainly a qemu bug not a Docker bug.

**Comment by Silve2611** [comment]
How could I test if it is only this container? Could you elaborate what ist meant bei QEMU? Does Docker use QEMU or this framework?

**Comment by stephen-turner** [comment]
qemu is the emulator for running Intel binaries on Arm Linux machines (or vice versa). Preferably you should use an Arm version of the image, because it will be faster as well as avoiding any qemu crashes.

**Comment by Silve2611** [comment]
Thank you for you clarification. 

I did not install qemu on my machine. Is this something that ships with docker? 
Where would be the best place to address this issue?

**Comment by stephen-turner** [comment]
Yes, it's bundled with docker. We're seeing lots of qemu crashes, so we will escalate them as a batch. My point was just that a fix is somewhat outside our control. Also that using the correct container for your chip architecture is a better way forward.

**Comment by Silve2611** [comment]
> Yes, it's bundled with docker. We're seeing lots of qemu crashes, so we will escalate them as a batch. My point was just that a fix is somewhat outside our control. Also that using the correct container for your chip architecture is a better way forward.

Thank you for the clarification! Hope Qemu will provide a solution.

**Comment by vavanan** [comment]
Try to use image for M1: [mvisonneau/alpine-sqs:1.2.0-arm64](mvisonneau/alpine-sqs:1.2.0-arm64)

**Comment by Silve2611** [comment]
> Try to use image for M1: `docker pull mvisonneau/alpine-sqs:1.2.0-arm64`

Works like a charm! Thx

**Comment by stephen-turner** [comment]
This is a qemu bug, which is the upstream component we use for running Intel (amd64) containers on M1 (arm64) chips, and is unfortunately not something we control. In general we recommend running arm64 containers on M1 chips because (even ignoring any crashes) they will always be faster and use less memory.

Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one. Now that M1 is a mainstream platform, we think that most container authors will be keen to do this.
