### ISSUE TITLE
Docker on Sierra keeps crashing

### ISSUE THREAD

**Issue by PedrosPod** [docker/for-mac#526]
### Information

Diagnostic ID: 40627B4F-71BE-4679-94E8-D995A91ED4D9
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@PedrosPod Should be fixed in the latest beta if you are willing to try. We will update stable channel soon. 

Thanks for using Docker!

**Comment by PedrosPod** [comment]
How can i download the latest Beta? Didn’t find a download link for it ( well, at least, i tried to enter the Beta testing but a huge form popped up and i really didn’t want to fill so much information for a beta, since i don’t have my companies AWS account stuff and all )

**Comment by mchiang0610** [comment]
@PedrosPod  you can find it here https://docs.docker.com/docker-for-mac/ 

direct download link: https://download.docker.com/mac/beta/Docker.dmg

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
