### ISSUE TITLE
Docker pull failing

### ISSUE THREAD

**Issue by smst329** [docker/for-mac#5261]
docker pull hello-world

Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

No network issues with app other than docker. Issue exists for any image.

**Comment by wgebis** [comment]
Hi, 
I'm facing the same issue on MacBook M1
```
$ docker pull docker/getting-started
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I believe that is related to networking stuff, it happened only if I'm connected to VPN (OpenVPN). After VPN connection I have access to the Internet, on my x86 Macbook exact configuration is working. So looks that docker daemon is not able to connect to the Internet. 

Here is part of my static routing table (default gateways section) after VPN connection:
```
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
0/1                100.96.1.49        UGSc         utun2       
default            192.168.5.1        UGSc           en0       
default            link#19            UCSI       bridge1      !
```

and here is the section VPN is disconnected:
```
Routing tables

Internet:
Destination        Gateway            Flags        Netif Expire
default            192.168.5.1        UGSc           en0       
default            link#19            UCSI       bridge1      !
```

As @t1m0 mentioned, I'm also able to acceess https://registry-1.docker.io/v2 via curl, web broser etc. in both cases.

**Comment by t1m0** [comment]
I just tried the M1 Preview v7 and now it's working for me.

**Comment by SerShevchyk** [comment]
I have the same problem on MacBook Pro macOS Big Sur:

> docker login
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=sershevchyk&client_id=docker&offline_token=true&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)


> Pulling proxy (traefik:2.2.0)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by tisba** [comment]
That very much sounds like https://github.com/docker/for-mac/issues/5186#issuecomment-841241363

**Comment by elliotberry** [comment]
Very much an issue for me, too.

**Comment by ErgoFriend** [comment]
I solved that !
https://github.com/docker/for-mac/issues/5713#issuecomment-847964753

**Comment by TylerADavis** [comment]
I'm running into this issue on an M1 Mac mini running the latest versions of Docker `3.3.3 (64133)` and Big Sur. I do not have any VPN enabled, and this error happens regardless of whether or not "Use new virtualization framework" is toggled on or off. I can access the URL given via curl or web browser, but I cannot `docker pull` any images.

```bash
christopherdavis@Tylers-Mac-mini ~ % docker run -p 8888:8888 jupyter/pyspark-notebook
Unable to find image 'jupyter/pyspark-notebook:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

**Comment by TylerADavis** [comment]
As an update, I was able to resolve this issue by toggling `Use new virtualization framework` on and then back off. Perhaps it was originally using the new virtualization framework, despite the box being unchecked?

1. Observe box is unchecked,  `docker pull` fails
2. Check the box, `docker pull` fails
3. Uncheck the box, `docker pull` succeeds

**Comment by Nezteb** [comment]
I had the same issue on an Intel Macbook Pro running Big Sur. @TylerADavis's suggestion fixed it for me. 🙌

**Comment by adamtupper** [comment]
I was also unable to pull images with the new virtualization framework enabled (I'm only able to when I don't use it).

**Comment by int32at** [comment]
I had the same issue, turning off the "Use new virtualization framework" (in Preferences -> Experimental Features) solved it though.
