### ISSUE TITLE
Kubernetes not starting if current-context in .kube/config is not found

### ISSUE THREAD

**Issue by himslm01** [docker/for-mac#5262]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When enabling Kubernetes and clicking the `Apply & Restart` button Kubernetes should start.

### Actual behavior
Kubernetes did not start. The following error was eventually found in the console:

    sending to gui: kubernetes: error while starting: cannot update the host kube config: invalid configuration: context was not found for specified context: kube001 (failed to start)

### Information
I have kubernetes clusters defined in three files.
1. the default `$HOME/.kube/config` which I leave to software to manipulate
2. two other files checked into GIT and added to `KUBECONFIG` environment variable

When I wanted to enable kubernetes in Docker for Desktop the `current-context`, which is always defined in `$HOME/.kube/config`, was pointing to one of the contexts defined in one of the other two files.

When I spotted the error in the console highlighted above (after several resets or Docker for Desktop and reboots of my machine) I had to edit `$HOME/.kube/config` to make the `current-context` be `docker-desktop`, then Kubernetes would start.

I do not want the `current-context` be `docker-desktop`. That is not the **usual** context I want to use.

Docker for desktop should be able to start kubernetes without the `current-context` being `docker-desktop`.

**Comment by ItsLeeOwen** [comment]
3.1.0... This has happened after every upgrade for the last several updates
