### ISSUE TITLE
Unable to use docker after enabling kubernetes

### ISSUE THREAD

**Issue by high101bro** [docker/for-mac#5264]
Docker was working pretty well until I enabled kubernetes... then all sorts of issues began happening. I ended up uninstalling Docker and all related files. Attempted to rebulid an image... and still no go. 

ERRO[0000] Can't add file /Users/daniel.s.komnick/Desktop/GitHub/jupyterlab/AWSCLIV2.pkg to tar: io: read/write on closed pipe 
ERRO[0000] Can't close tar writer: io: read/write on closed pipe 
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ... On the M1 Macbook Air using Docker Preview, I enabled kubernetes
  2. ...

**Comment by stephen-turner** [comment]
The documentation explicitly says that the current preview doesn't work with Kubernetes. https://docs.docker.com/docker-for-mac/apple-m1/
