### ISSUE TITLE
Docker for Mac will not start, even after being reset and re-installed

### ISSUE THREAD

**Issue by rgov** [docker/for-mac#5265]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 72C5C92D-665D-45BB-83CD-9CCEDA7EA8EA/20210118045542

### Expected behavior

Docker starts up after a few minutes.

### Actual behavior

Docker continually shows the "starting" animation and does not start. `docker ps` fails because `docker.sock` doesn't exist. The UI shows it stuck in the "Starting" state.

### Information

  - macOS Version: Big Sur 11.1

Have tried using the "Reset" and "Uninstall" buttons, manually deleting `~/Library/Group Containers/group.com.docker` and `~/Library/Containers/com.docker.docker`.

### Diagnostic logs

```
<!-- Full output of the diagnostics from "Diagnose & Feedback" in the menu ... -->
```
There is no such menu item.

### Steps to reproduce the behavior

Unsure how to reproduce.

**Comment by rgov** [comment]
Recent issues with similar symptoms: #5220, #5243, #5246

**Comment by oranges13** [comment]
This issue was closed, but I believe it is the same issue #4957

**Comment by rgov** [comment]
Maybe, but:

1. Half of the comments there say to enable gRPC FUSE and the other half say to disable it.
2. In this state, I cannot change my Docker settings because there is a spinner over the preferences window:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/108767/105205826-a83cdf80-5b13-11eb-92e8-4765d59f32cd.png">

3. Docker developers claim this was fixed.

**Comment by rgov** [comment]
@stephen-turner Could you please tell me how to switch to `osxfs` via editing config files rather than using the UI, so that I can test if this is the root cause?

**Comment by stephen-turner** [comment]
#4957 doesn't seem related, that's about volume mounts. You can try by editing your settings.json file -- sorry, I don't remember the path on Mac but I'm sure you can find it. But I don't expect it will make a difference.

**Comment by stephen-turner** [comment]
Have you got any DOCKER_* environment variables?
Have you got any corporate security software that could be getting in the way?

**Comment by rgov** [comment]
I have found a few settings files but I don't see the setting line for gRPC/osxfs, and I asked someone to try toggling the setting and seeing if any of them change, but we didn't notice anything.

I do not have any such environment variables.

I have a corporate VPN but I have definitely used Docker for at least a year with this software in place. The VPN only routes connections to a small range of IPs and does not deny local connections, affect the creation of network interfaces, etc. I do not have additional antivirus or firewalls, etc in place.

**Comment by rgov** [comment]
#5272 is another potential duplicate. #5266 is a very low quality bug report but maybe is referring to the same issue? #5260 has the same symptoms for M1 Macs, but they would presumably be using the Preview.

**Comment by berndschimmer** [comment]
Hi, I use https://freemacsoft.net/appcleaner/ to get a real uninstall. 
After that (and a clean install) docker will start, but switching off gRPC will lead consistently into this endless loading state.
I tried to switch to osxfs to see if the incorrectly [host_mnt](https://github.com/docker/for-mac/issues/4859) prefix can be solved within the m1 preview.

**Comment by berndschimmer** [comment]
The features-overrides.json is btw. in ~/Library/Group Containers/group.com.docker/features-overrides.json and this is the json for switching gRPC back on:
`{
  "grpcfuseV2": {
    "label": "Use grpcfuse for filesharing by default",
    "enabled": true
  }
}`

**Comment by rgov** [comment]
Thanks @berndschimmer. I tried setting the `enabled` flag to both true and false and neither caused Docker to load for me.

**Comment by rgov** [comment]
I tried 2.5.0.1, 3.0.0, and 3.0.4 and none of them appears to start. They all complain with:

```
2021-02-06 17:35:01.212290-0500  localhost com.docker.backend[99729]: internal: GET /vm/init 500 "DockerDesktopGo" "during /vm/init: cannot fetch $HOME/.docker/certs.d: unable to read from /Users/rgov/.docker/certs.d: reading /Users/rgov/.docker/certs.d/192.168.64.5:2376/client.cert: open /Users/rgov/.docker/certs.d/192.168.64.5:2376/client.cert: no such file or directory"
```

Which is interesting because that file exists. I tried granting Docker full disk read access but that didn't work.

Eventually I killed all running Docker processes, deleted `~/.docker`, installed version 3.0.0, and that seemed to start.
