### ISSUE TITLE
Containers/Images are no more seen and Docker commands hang

### ISSUE THREAD

**Issue by dwamara** [docker/for-mac#5268]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 86EFE1EA-C363-4F32-8A30-631E91ADAE84/20210118202729

### Expected behavior
Local images and Containers can be see in the Dashboard and used

### Actual behavior
- The Dashboard doesn't show any container or image present.
- Docker can't be used. A simple "docker ps" hangs and doesn't give any feedback
- Restarting the computer or Docker doesn't bring any change
- After waiting around 10 minutes, "docker ps" returns the started containers but these are not shown in the Dashboard
- Shown started containers can't be used, e.g. the user interfaces of Sonatype Nexus or Portainer that are shown started can't be accessed.

### Information
- Is it reproducible? yes, every time
- Is the problem new? yes, started happening 3 days ago
- Did the problem appear with an update? no, but I tried to update to the latest version and it didn't changed anything
- macOS Version: Big Sur 11.1

**Comment by vseibt** [comment]
I can confirm this behaviour. I'm currently using "docker desktop community" 2.5.0.1 (49550) on macOS Mojave 10.14.6 which works fine.
I tried every suggested update of docker desktop and had trouble with this hanging daemon. So I switched back to 2.5.0.1.
