### ISSUE TITLE
[kind/enhancement] Allow update on start instead of restart

### ISSUE THREAD

**Issue by sploders101** [docker/for-mac#5270]
- [ ] I have tried with the latest version of Docker Desktop (N/A, this has to do with the update procedure)
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics (N/A, feature request)
  - Diagnostics ID:

### Description

Add a checkbox in preferences allowing docker desktop to prompt the user for updates *during* start, instead of *after* start.

### Information

  - macOS Version: 10.15.7

I am frequently finding myself having to set up my environment twice, because I start docker, get VSCode primed and ready to go as soon as it comes up, VSCode starts and connects to my development containers, I start my debuggers, and *then* docker prompts me to update. It would be really nice to have an option to update on start instead of having to start, wait, stop, update, and *re*start. These updates seem to apply so quickly that I honestly wouldn't mind them being done automatically, but I'm aware that many people care about keeping the same version, so it would be nice to have a prompt that pops up during start, asking to update, potentially with a "do not ask me again" checkbox.

**Comment by stephen-turner** [comment]
Which version are you using? As of 3.0, the update is downloaded in the background and then applied on next start.

**Comment by sploders101** [comment]
Sorry I forgot to respond earlier. I just checked and I'm on docker 3.1, but it hasn't bothered me in a while, so I'll go ahead and close this for now. Thank you!
