### ISSUE TITLE
Docker Desktop stuck in "Docker Desktop is starting" forever

### ISSUE THREAD

**Issue by ericfrank** [docker/for-mac#5272]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9F950E6B-CC90-4F6C-8683-665FECE55938/20210119181439

### Expected behavior

Docker desktop starts.

### Actual behavior

Docker Desktop stuck in "Docker Desktop is starting" state forever.

### Information
I've tried installing previous versions with no luck.

  - macOS Version: 10.15.7

### Steps to reproduce the behavior

  1. Start Docker Desktop

**Comment by stuponatron** [comment]
I'm experiencing the same issue after upgrading to catalina.  docker was running fine before the macos upgrade.

I've uninstalled, downgrade to 2.5, re installed, all to no avail.

Per [a comment in 3941](https://github.com/docker/for-mac/issues/3941#issuecomment-537235153), i tried manually starting.  This resulted in:

```
json error: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
INFO : BSG_KSCrash.m (280): -[BSG_KSCrash sendAllReports]: Sending 0 crash reports
```

**Comment by ericfrank** [comment]
I was able to get Docker working by downgrading to 2.5.0.1. This thread seems to be the same issue: https://github.com/docker/for-mac/issues/5131

**Comment by ishubhamjain** [comment]
Its also work for me with 2.5.01

**Comment by ericfrank** [comment]
This ended up being an issue with McAfee Firewall. Disabling it fixed the issue.
