### ISSUE TITLE
M1 Preview returns connection refused for docker login

### ISSUE THREAD

**Issue by boomerstan** [docker/for-mac#5275]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B1EC4698-0EBD-42A7-9C48-E75E3E0C027E/20210119200829

### Expected behavior
Successful login

### Actual behavior
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.4:38800->192.168.64.1:53: read: connection refused

### Information

  - macOS Version: 11.1
  - new M1 mac with new docker preview install
  - no containers
  - first command is "docker login"
  - I can log in to Docker Hub
  - docker quick start tutorial yields same error
  -  https://registry-1.docker.io/v2/ yields {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

### Diagnostic logs

```
Diagnose succeeded
Docker for Mac: version... Docker-AppleSilicon-Preview7 Dec 16

```

### Steps to reproduce the behavior

  1. Uninstall Docker
  2. Reboot
  3. Reinstall Docker
  4. Open iTerm and "docker login" enter
  5. VPN not connected & connected

**Comment by boomerstan** [comment]
error response has changed:
docker login
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (****): ****
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by boomerstan** [comment]
I thought this maybe related to the account so I created a personal free account. Logged out of docker desktop and in with new account. docker logout docker login yields same error response as above.

**Comment by boomerstan** [comment]
post uninstall, reboot, redownload, reinstall. then run the getting started tutorial 
$ docker run --name repo alpine/git clone https://github.com/docker/getting-started.git
Unable to find image 'alpine/git:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.5:44091->192.168.64.1:53: read: connection refused.
See 'docker run --help'.
$ docker cp repo:/git/getting-started/ .
Error: No such container:path: repo:/git/getting-started/

**Comment by boomerstan** [comment]
Solved
After I got Docker desktop hung by shutting off all experimental features. I needed to reinstall. I used manual method from https://nektony.com/how-to/uninstall-docker-on-mac and now Docker is working.

**Comment by boomerstan** [comment]
After pulling a couple images and executing "php composer.phar install" from docker exec bash I started having packagist not found issues. 
SO I uninstalled & reinstalled Preview again. Several times now. 
docker pull ****/****
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.11:49816->192.168.64.1:53: read: connection refused
followed by 
docker login
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.11:39319->192.168.64.1:53: read: connection refused
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (****):
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.11:54152->192.168.64.1:53: read: connection refused

**Comment by qiuyuhome** [comment]
`Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by boomerstan** [comment]
Docker support response: The M1 preview is currently at an "alpha" stage, and is not a supported product yet. There are known to be various networking problems. We hope to have a new preview build in a week or so, which will solve some of them.
