### ISSUE TITLE
Docker M1 Preview is stuck in "starting" status

### ISSUE THREAD

**Issue by Rotzke** [docker/for-mac#5276]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D5F031F4-D4F3-400B-A117-F5A2BFA620E4/20210119233759

### Expected behavior
Docker is running
### Actual behavior
Docker is stuck in "starting" status
### Information

  - macOS Version: BigSur 11.1

### Diagnostic logs

```
localhost com.docker.driver.amd64-linux[6112]: still waiting for docker to respond

```

### Steps to reproduce the behavior

  1. Try to enable Kubernetes Cluster on Docker M1 Preview
  2. Try to install minikube
  3. Now Docker could not be started event after full reinstallation of the app

**Comment by Rotzke** [comment]
I have seen that there are similar issues opened but it was working fine before I tried to enable Kubernetes, hope this could somehow give extra info.

**Comment by tylerrasor** [comment]
k8s is known not to work, I had to edit `~/Library/Group\ Containers/group.com.docker/settings.json` (`"kubernetesEnabled": false`, `"kubernetesInitialInstallPerformed": false`) to get the dashboard to respect that I wanted to back out that change

that said, the `perpetual starting state` problem happened to me long after I tried to enable k8s

**Comment by iamsinghal** [comment]
Having the same issue!

**Comment by Rotzke** [comment]
> k8s is known not to work, I had to edit `~/Library/Group\ Containers/group.com.docker/settings.json` (`"kubernetesEnabled": false`, `"kubernetesInitialInstallPerformed": false`) to get the dashboard to respect that I wanted to back out that change
> 
> that said, the `perpetual starting state` problem happened to me long after I tried to enable k8s
> 
> edit: when docker was working, I was using [k3d](https://github.com/rancher/k3d) successfully

Unfortunately did not help, was trying also to manually remove any traces of Docker and do extremely clean install - same result.

**Comment by lee997** [comment]
Try to close the firewall on mac m1 and then restart the docker.

**Comment by Rotzke** [comment]
> Try to close the firewall on mac m1 and then restart the docker.

It was and is deactivated, also thought that it could have been a problem.

**Comment by dojutsu-user** [comment]
Try "Reset to factory defaults" option.

**Comment by rajatkb-typito** [comment]
Facing the same issue from yesterday. Tried installing minikube and start. Earlier docker was running fine. It has become a blocker for my workflow. Any advices on this. I checked the logs for  `~/Library/Containers/com.docker.docker/Data/log/host/com.docker.driver.amd64-linux.log` 

```
time="2021-01-22T20:37:37+05:30" level=info msg="🍀 socket server listening : backend.sock"
time="2021-01-22T20:37:37+05:30" level=info msg="🍀 socket server starting : backend.sock"
time="2021-01-22T20:37:37+05:30" level=info msg="NewApprover: grpcfuse feature enabled, using grpcfuse approver"
time="2021-01-22T20:37:37+05:30" level=info msg="NewSharer: grpcfuse feature enabled"
time="2021-01-22T20:37:37+05:30" level=info msg="proxy >> HEAD /_ping\n"
time="2021-01-22T20:37:37+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:37:37+05:30" level=info msg="VM has started: /Applications/Docker.app/Contents/Resources/bin/com.docker.virtualization --kernel /Applications/Docker.app/Contents/Resources/linuxkit/kernel --ramdisk /Applications/Docker.app/Contents/Resources/linuxkit/initrd.img --disk /Users/rajatkb/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw --macaddr-filename vms/0/macaddr --cpus 4 --memoryMiB 2048 --console-log vms/0/console.log --console vms/0/console.sock --no-docker-proxy"
time="2021-01-22T20:37:37+05:30" level=info msg="waitForDockerUp: Client: &{scheme:http host:unix://docker.raw.sock proto:unix addr:docker.raw.sock basePath: client:0x1400052a960 version:1.40 customHTTPHeaders:map[] manualOverride:false negotiateVersion:true negotiated:false}"
time="2021-01-22T20:38:07+05:30" level=info msg="still waiting for docker to respond after 30.114816708s"
time="2021-01-22T20:38:38+05:30" level=info msg="still waiting for docker to respond after 1m0.240790833s"
time="2021-01-22T20:39:08+05:30" level=info msg="still waiting for docker to respond after 1m30.335729583s"
time="2021-01-22T20:39:38+05:30" level=info msg="still waiting for docker to respond after 2m0.442630458s"
time="2021-01-22T20:40:08+05:30" level=info msg="still waiting for docker to respond after 2m30.53895s"
time="2021-01-22T20:40:38+05:30" level=info msg="still waiting for docker to respond after 3m0.639822625s"
time="2021-01-22T20:41:08+05:30" level=info msg="still waiting for docker to respond after 3m30.753463917s"
time="2021-01-22T20:41:38+05:30" level=info msg="still waiting for docker to respond after 4m0.853762125s"
time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> GET /v1.24/info\n"
time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
time="2021-01-22T20:42:08+05:30" level=info msg="still waiting for docker to respond after 4m30.974766s"
time="2021-01-22T20:42:38+05:30" level=info msg="still waiting for docker to respond after 5m1.087546917s"
time="2021-01-22T20:43:08+05:30" level=info msg="still waiting for docker to respond after 5m31.188838958s"
time="2021-01-22T20:43:39+05:30" level=info msg="still waiting for docker to respond after 6m1.298114208s"
time="2021-01-22T20:44:09+05:30" level=info msg="still waiting for docker to respond after 6m31.399238333s"
time="2021-01-22T20:44:39+05:30" level=info msg="still waiting for docker to respond after 7m1.499790708s"
time="2021-01-22T20:45:09+05:30" level=info msg="still waiting for docker to respond after 7m31.598180958s"
time="2021-01-22T20:45:39+05:30" level=info msg="still waiting for docker to respond after 8m1.696682667s"

```

**Comment by Rotzke** [comment]
> Facing the same issue from yesterday. Tried installing minikube and start. Earlier docker was running fine. It has become a blocker for my workflow. Any advices on this. I checked the logs for  `~/Library/Containers/com.docker.docker/Data/log/host/com.docker.driver.amd64-linux.log` 
> 
> ```
> time="2021-01-22T20:37:37+05:30" level=info msg="🍀 socket server listening : backend.sock"
> time="2021-01-22T20:37:37+05:30" level=info msg="🍀 socket server starting : backend.sock"
> time="2021-01-22T20:37:37+05:30" level=info msg="NewApprover: grpcfuse feature enabled, using grpcfuse approver"
> time="2021-01-22T20:37:37+05:30" level=info msg="NewSharer: grpcfuse feature enabled"
> time="2021-01-22T20:37:37+05:30" level=info msg="proxy >> HEAD /_ping\n"
> time="2021-01-22T20:37:37+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:37:37+05:30" level=info msg="VM has started: /Applications/Docker.app/Contents/Resources/bin/com.docker.virtualization --kernel /Applications/Docker.app/Contents/Resources/linuxkit/kernel --ramdisk /Applications/Docker.app/Contents/Resources/linuxkit/initrd.img --disk /Users/rajatkb/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw --macaddr-filename vms/0/macaddr --cpus 4 --memoryMiB 2048 --console-log vms/0/console.log --console vms/0/console.sock --no-docker-proxy"
> time="2021-01-22T20:37:37+05:30" level=info msg="waitForDockerUp: Client: &{scheme:http host:unix://docker.raw.sock proto:unix addr:docker.raw.sock basePath: client:0x1400052a960 version:1.40 customHTTPHeaders:map[] manualOverride:false negotiateVersion:true negotiated:false}"
> time="2021-01-22T20:38:07+05:30" level=info msg="still waiting for docker to respond after 30.114816708s"
> time="2021-01-22T20:38:38+05:30" level=info msg="still waiting for docker to respond after 1m0.240790833s"
> time="2021-01-22T20:39:08+05:30" level=info msg="still waiting for docker to respond after 1m30.335729583s"
> time="2021-01-22T20:39:38+05:30" level=info msg="still waiting for docker to respond after 2m0.442630458s"
> time="2021-01-22T20:40:08+05:30" level=info msg="still waiting for docker to respond after 2m30.53895s"
> time="2021-01-22T20:40:38+05:30" level=info msg="still waiting for docker to respond after 3m0.639822625s"
> time="2021-01-22T20:41:08+05:30" level=info msg="still waiting for docker to respond after 3m30.753463917s"
> time="2021-01-22T20:41:38+05:30" level=info msg="still waiting for docker to respond after 4m0.853762125s"
> time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
> time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
> time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
> time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> HEAD /_ping\n"
> time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:41:53+05:30" level=info msg="proxy >> GET /v1.24/info\n"
> time="2021-01-22T20:41:53+05:30" level=info msg="dial unix docker.raw.sock: connect: no such file or directory"
> time="2021-01-22T20:42:08+05:30" level=info msg="still waiting for docker to respond after 4m30.974766s"
> time="2021-01-22T20:42:38+05:30" level=info msg="still waiting for docker to respond after 5m1.087546917s"
> time="2021-01-22T20:43:08+05:30" level=info msg="still waiting for docker to respond after 5m31.188838958s"
> time="2021-01-22T20:43:39+05:30" level=info msg="still waiting for docker to respond after 6m1.298114208s"
> time="2021-01-22T20:44:09+05:30" level=info msg="still waiting for docker to respond after 6m31.399238333s"
> time="2021-01-22T20:44:39+05:30" level=info msg="still waiting for docker to respond after 7m1.499790708s"
> time="2021-01-22T20:45:09+05:30" level=info msg="still waiting for docker to respond after 7m31.598180958s"
> time="2021-01-22T20:45:39+05:30" level=info msg="still waiting for docker to respond after 8m1.696682667s"
> 
> ```

Actually I remember installing minikube as well, might be related.

**Comment by rajatkb-typito** [comment]
If someone can give some clue how to undo the changes done by minicabe it will be helpful. I have uninstalled Minikube, which I installed manually following the Kuberenetes official docs. Downloaded the binary and moved it to /local/usr/bin folder

**Comment by Rotzke** [comment]
> If someone can give some clue how to undo the changes done by minikube it will be helpful. I have uninstalled Minikube, which I installed manually following the Kuberenetes official docs. Downloaded the binary and moved it to /local/usr/bin folder

I was trying to delete all resources related to Minikube that I could find - no luck.

**Comment by rajatkb-typito** [comment]
@Rotzke  I think this should help. The Minikube installation attempt must have done something , which may have change the bridge100 settings. [similar issue](https://github.com/docker/for-mac/issues/5130)

**Comment by Rotzke** [comment]
Fixed with https://github.com/docker/for-mac/issues/5130
