### ISSUE TITLE
Option to copy containers and images from your local default docker machine missing?

### ISSUE THREAD

**Issue by EfficientSetting** [docker/for-mac#5277]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Summary

The [documentation](https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install) mentions there to be an "option to copy containers and images from your local default [docker-]machine" , yet it seems there is none and there is no clear path on how to migrate from docker-machine to docker desktop. 

Quote from the [documentation](https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install):

> Relationship to Docker Machine: Installing Docker Desktop on Mac does not affect machines you created with Docker Machine. You have the option to copy containers and images from your local default machine (if one exists) to the Docker Desktop HyperKit VM. When you are running Docker Desktop, you do not need Docker Machine nodes running locally (or anywhere else). With Docker Desktop, you have a new, native virtualization system running (HyperKit) which takes the place of the VirtualBox system.

### Expected behavior

Ideal: Dialog that offers import from existing docker machine.
Otherwise: Option in preferences, or at least a guide on a migration path now that boot2docker and all other options except docker desktop [for mac] are deprecated/obsolete

### Actual behavior

Boot2Docker, Docker-Machine and other such options are all deprecated without a clear migration path. Documentation mentions a "copy" option that is never heard of elsewhere-

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? N/A
  - Did the problem appear with an update? N/A
  - A reproducible case if this is a bug, Dockerfiles FTW. N/A
  - macOS Version: 10.15.7

### Steps to reproduce the behavior

  1. Have docker-machine installed and running
  2. Install Docker for Desktop
  3. -> No copy option or any kind of connection to docker-machine comes up

**Comment by stephen-turner** [comment]
Thanks for your enquiry. That paragraph is out of date and I'll make a PR to remove it. But there are current instructions at https://docs.docker.com/docker-for-windows/docker-toolbox/ (for Mac and Windows, despite the URL).

**Comment by EfficientSetting** [comment]
Thanks for the quick answer! This clarifies things
