### ISSUE TITLE
F71E23D0-2366-4055-8007-9753F189DBCA/20210120164530

### ISSUE THREAD

**Issue by hmiguelcastro** [docker/for-mac#5279]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior
Restarted Macbook Pro after getting a "Your disk is almost full" notification. Prior to restarting, any attempt to delete a file via the GUI or rm command failed with a "no space left on device" message. The error occurred after the restart. Following the restart the file system reported approximately 18 17.5 GB of free space.

**Comment by kevcube** [comment]
@hmiguelcastro note that this is not a technical support forum, but if you would like to free the space that is being used by docker, read (this documentation)[https://docs.docker.com/engine/reference/commandline/system_prune/] and if you decide it's right for you, run `docker system prune`
