### ISSUE TITLE
Docker problem in MacOS Sierra beta.

### ISSUE THREAD

**Issue by leandro-a-silva** [docker/for-mac#528]
### Information

```
Diagnostic ID: F37ABB3F-45AB-49A5-ADF9-55DE5420B35A
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.12 (Build 16A312a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/leandro/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/leandro/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/leandro/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by meister** [comment]
Confirmed – same exact result in my case.

**Comment by mchiang0610** [comment]
@meister @leandro-a-silva Do you have previous versions of Docker for Mac beta installed? Does resetting to factory defaults work?

**Comment by vistiyos** [comment]
Same as me.

**Comment by dsheets** [comment]
Could you please try on the just released Beta 25? DId this occur immediately after installing Docker for Mac or after some time? If you uninstall and reinstall does it recur? What if you uninstall and reinstall with Beta 25?

**Comment by vistiyos** [comment]
It happened to me just installing it, but looks like the new Beta release is more stable in that sense. I haven't got a crash yet.

**Comment by philippelabat** [comment]
Any release logs for Beta 25?

**Comment by meister** [comment]
@dsheets For me the beta25 application itself starts now, but the docker-cli fails:
```
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by vistiyos** [comment]
@meister Have you uninstall Docker stable before install the beta version?

**Comment by meister** [comment]
Unfortunately no, due to this issue: https://github.com/docker/for-mac/issues/488
Is there a way (guide somewhere) to fully manually remove it?

**Comment by vistiyos** [comment]
There is one:

https://docs.docker.com/docker-for-mac/#/uninstall-or-reset

**Comment by meister** [comment]
Whoah, thanks. It actually worked now. Uninstalling manually, then re-installing beta25 works for me.

**Comment by vistiyos** [comment]
@meister Great!

**Comment by dsheets** [comment]
We still know of some issues with Beta 25 and Sierra but the primary problem reported here has been resolved. Please open a new ticket if you experience further problems.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by meister** [comment]
Beta 26 upgrade worked flawlessly for me on Sierra. Nice clean upgrade without any problems.

**Comment by leandro-a-silva** [comment]
The update has worked for me. Thank you all!
