### ISSUE TITLE
Kubernetes not starting when using docker desktop

### ISSUE THREAD

**Issue by sujiths80** [docker/for-mac#5281]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: 3.1.0(51484)
Kubernetes  v1.19.3
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sujiths80** [comment]
NA

**Comment by sujiths80** [comment]
[
![Snip20210120_19](https://user-images.githubusercontent.com/5725236/105249184-8e5bc680-5b2c-11eb-8781-6a5ed4320994.png)
](url)

**Comment by Jiachen-Zhang** [comment]
Same problem to me...

> Kubernetes does not initialize because of a missing DNS name.

From [https://docs.docker.com/docker-for-mac/apple-m1/](https://docs.docker.com/docker-for-mac/apple-m1/)
