### ISSUE TITLE
Enabling buildkit causes additional CAs to be 'lost'

### ISSUE THREAD

**Issue by mattdowdell** [docker/for-mac#5288]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 237C6B98-7ED6-477B-B8BE-DFA8B69376BC/20210123090708

### Expected behavior

`docker build [--pull] .` success, when using a base-image from a repository hosted on a registry using a certificate from a non-standard CA and enabling `DOCKER_BUILDKIT`.

Curiously, `docker pull` always works, regardless of whether buildkit is enabled.

### Actual behavior

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: Get https://harbor.<redacted>/service/token?scope=repository%3Alibrary%2Fpython%3Apull&service=harbor-registry: x509: certificate signed by unknown authority
```

### Information

- macOS Version: Catalina (10.15.7)

Problem seems to have appeared with Docker for Mac v3, but I wasn't dilligent about updating so it may have appeared in one of the later 2.X releases. Problem is always reproducible for me and at least one other of my colleagues who observed the same issue when upgrading to v3+.

I've come across a few similar issues, e.g. https://github.com/docker/for-mac/issues/5189 but that seems to be a subtlely different error.

This works perfectly on Linux with buildkit enabled, leading me to think something about enabling buildkit on Mac is triggering some other code path that perhaps loads certificates from elsewhere?

### Diagnostic logs

```
Docker for Mac: 3.1.0 (51484)
```

See aforementioned diagnostic ID for full logs.

### Steps to reproduce the behavior

```
FROM example.com/python3.8:slim
```

Where example.com is a self-hosted docker registry using a TLS certificate derived from a self-signed or internal CA. See https://docs.docker.com/registry/deploying/#get-a-certificate for setting up a registry with a certificate, and something like https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/ for geerating a CA and issuing a certificate from it and adding it to certificate store.

In this case, I'm using Harbor as my registry, but I don't see any obvious reason why it would be different for other registries.

Build using `DOCKER_BUILDKIT=1 docker build [--pull] .`

**Comment by mattdowdell** [comment]
Issue for me was fixed upon resolving an issue in my certificate store. We have an internal root CA and an intermediate and the intermediate had become untrusted. By fixing that, buildkit started working again.

I assume buildkit is more picky about what certificates it trusts compared to standard docker.

Closing as resolved.

**Comment by cldfzn** [comment]
I still come across this error. I'm using macOS as well and the certificate is trusted in my keychain. Is there a particular way the certificate needs to be configured?
