### ISSUE TITLE
100% CPU with no containers running

### ISSUE THREAD

**Issue by dragisak** [docker/for-mac#529]
### Steps to reproduce

After waking up my mac, I saw cpu being pegged by:
`/Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 6G -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,...`

There were no containers running.

### Expected behavior

It should not peg my CPU

### Actual behavior

CPU maxed. I noticed fan blowing.

### Information

```
Diagnostic ID: A26A3E4D-5978-4F65-A81E-B1B463161FD4
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dragisak** [comment]
It all calmed down after I restarted docker.

**Comment by mchiang0610** [comment]
Merging with #82.
