### ISSUE TITLE
Navigation area in Dashboard log view is inside of log area and not outside.

### ISSUE THREAD

**Issue by kristiHon** [docker/for-mac#5290]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: C2738C80-6A3A-44B1-AB3B-5FD016A3AD81/20210125114521

### Expected behavior

I should see Navigation area on top and bottom without scrolling up and down.

### Actual behavior

The navigation area on the top you see only on top of the logs
![image](https://user-images.githubusercontent.com/77967402/105700681-78258000-5f09-11eb-8757-e77741c16967.png)

The navigation area is missed if you scroll down
![image](https://user-images.githubusercontent.com/77967402/105700748-91c6c780-5f09-11eb-91f6-792d0b4b9068.png)

Also the area on bottom you can see only if you scroll to the bottom:
![image](https://user-images.githubusercontent.com/77967402/105700968-e4a07f00-5f09-11eb-85cf-9d2980bc8134.png)

### Information

I have this problem after last update  of Docker Desktop to the version 3.1.0 (51484)

  - macOS Version: Catalina 10.15.7

### Diagnostic logs

```
Docker for Mac: 3.1.0

```

### Steps to reproduce the behavior

I use docker-compose 
  1. Create a docker-compose.yml file with:

version: "3.7"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    expose:
      - 2181

  2. Go to the terminal to the folder you stored docker-compose.yml file and run command:
  docker-compose up -d
  2. Open Dashboard
  3. Open your docker-compose tree and click on the zookeeper container.
Now you should see the view with the log of zookeeper container. Resize the Window to the smallest one. Scroll in the log up and down.

**Comment by stephen-turner** [comment]
Thanks, this is the same as docker/for-win#10160. A fix is incoming.

**Comment by stephen-turner** [comment]
This is fixed in versions 3.2.0 and 3.2.1. Closing the ticket now.
