### ISSUE TITLE
gpg-agent forward

### ISSUE THREAD

**Issue by MacFlurry** [docker/for-mac#5297]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior
```
ssh-add -l # should show the key
```
### Actual behavior

I used ssh and the ssh agent to forward my ssh connection in my container this way:
```
-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock \
-e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" \
```
And it worked very well.
Now I switched to gpg-agent.
and I tried something similar
```
-v $(gpgconf --list-dirs agent-ssh-socket):/run/host-services/ssh-auth.sock \
-e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock " \
``` 
but of course it doesn’t work, otherwise I wouldn’t be here. :slightly_smiling_face:
I logged into my container for more debugging:
```
/data # echo $SSH_AUTH_SOCK
/run/host-services/ssh-auth.sock
/data # file /run/host-services/ssh-auth.sock
/run/host-services/ssh-auth.sock: socket
```
you can see that I do have a sock mounted in my container.
but, unfortunately:
```
/data # ssh-add -l
Error connecting to agent: No such file or directory
```
when I tried to launch an ansible connection to my remote server from my Container, I got an error:
```
pubkey_prepare: ssh_get_authentication_socket: Connection refused 
```
If anyone has any idea how I can forward the gpg-agent in my container, I’m a taker.
Thank you for your help.

 - macOS Version: 11.1

```
Docker for Mac: 20.10.2, build 2291f61

```

**Comment by MacFlurry** [comment]
still an issue.

**Comment by SMores** [comment]
It would be really great if a similar feature to the "magic" volume for ssh-agent forwarding existing for gpg-agent forwarding. Several of the commenters in the original thread (https://github.com/docker/for-mac/issues/483) for socket forwarding were specifically asking for the ability to forward S.gpg-agent.extra. I personally use a Yubikey to sign git commits, and being able to forward to my gpg-agent to a docker container would be a lifesaver!
