### ISSUE TITLE
My docker does not start up after updating

### ISSUE THREAD

**Issue by arnokoehler** [docker/for-mac#5298]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 4F329D51-5E63-45BF-9D4E-08E9CF47F13B/20210127112846

### Information

  - macOS Version: 10.15.7

### Diagnostic logs

```
Docker for Mac: version latest.

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by emma-r-slight** [comment]
I have the same problem. 

macOS version 11.1

issue: F4200237-4415-4411-A50A-2EEFE38AE765/20210127214013

**Comment by arnokoehler** [comment]
after 10 minutes / restarting / etc. it did.
