### ISSUE TITLE
Containers can not be created or destroyed

### ISSUE THREAD

**Issue by snorkrat** [docker/for-mac#5299]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A071774F-4A4B-49CA-9531-BD44802432E7/20210127230554

### Expected behavior
docker-compose up -d or docker-compose down should create or destroy the containers
### Actual behavior

I get an error like: `UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60) ERROR: An HTTP request took too long to complete.`

### Information

  - macOS Version: 11.0.1

### Diagnostic logs

```
[log.txt](https://github.com/docker/for-mac/files/5883738/log.txt)

```

### Steps to reproduce the behavior
Use docker-compose to start or destroy containers.

I have read on other issues like this that disabling gRPC FUSE fixed it for a lot of people, however on M1 Preview build this results in Docker Desktop not being able to start.

**Comment by stephen-turner** [comment]
I think this is the same as #4957, which is fixed in a later build than the current M1 preview. You can try again when the next preview comes out.

**Comment by djs55** [comment]
@snorkrat thanks for your report. We recently released a new build of the Desktop M1 preview: https://docs.docker.com/docker-for-mac/apple-m1/ -- let me know if the problem is fixed (or not). If not, could you supply a reproduction example to help me understand the problem. Thanks!

**Comment by snorkrat** [comment]
The new build seems to have fixed this problem.  I haven't had this issue happen since I upgraded.

**Comment by snorkrat** [comment]
Okay, so the day after I closed this issue as I thought the new build fixed it, it has happened again.  I noticed that my grafana docker container was giving me a 502 bad gateway error when trying to access it. I used the command "docker-compose down" to take the container down and it gave me the error

```
ERROR: for grafana  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

If you can let me know any other logs or whatever you need to see to diagnose.
