### ISSUE TITLE
Fails to Start (UI is locked, spinning beachball forever)

### ISSUE THREAD

**Issue by samn** [docker/for-mac#530]
### Expected behavior
I'd be able to launch Docker for Mac.
### Actual behavior
Docker for Mac does not start. 

Left machine sleeping for the weekend. Woke it up the morning and saw Docker for Mac had crashed. Tried to start it again but the menu bar icon never showed up. Hovering over where the icon would be showed a spinning beachball. Saw no errors in the system log.
Force killed Docker, rebooted, tried again, same results.
This happens with both the stable and beta versions (removed `/Applications/Docker.app` and installed again).

Removed all downloaded images, same result.
Removed all docker related files from ~/Library, uninstalled the app, rebooted, installed again, same result.

This happened both before and after the latest security update for OS X.

After reinstalling the 'Welcome to Docker for Mac!' dialog pops up but it hangs after clicking 'Next'.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    - Unable to provide, the UI won't load.
  - host distribution and version: OS X 10.11.6

Last output from `syslog -k Sender Docker`:
```
Sep  6 17:36:58 salmon Docker[5517] <Notice>: Application version: 1.12.0-a (11213)
Sep  6 17:36:58 salmon Docker[5517] <Notice>: Administrator user: true
Sep  6 17:36:58 salmon Docker[5517] <Notice>: OSX Version: Version 10.11.6 (Build 15G1004)
Sep  6 17:36:59 salmon Docker[5517] <Notice>: migrator: start migration process
Sep  6 17:36:59 salmon Docker[5517] <Notice>: migrator: no previous version detected. Performing all migrations for now...
Sep  6 17:36:59 salmon Docker[5517] <Notice>: migrator: 0 migrations to perform
Sep  6 17:36:59 salmon Docker[5517] <Notice>: migrator: end of migration process
Sep  6 17:36:59 salmon Docker[5517] <Notice>: event tracker initialized
Sep  6 17:37:16 salmon Docker[5517] <Notice>: Bundle path: /Applications/Docker.app
```

I sampled the stuck process in Activity Monitor a couple of times and it looks like it's stuck here:
```
  2693 _TToFC6Docker11AppDelegate29applicationDidFinishLaunchingfCSo14NSNotificationT_  (in Docker) + 37  [0x103331c25]
      2693 _TTSf4dg_n___TFC6Docker11AppDelegate29applicationDidFinishLaunchingfCSo14NSNotificationT_  (in Docker) + 5880  [0x103334628]
             2693 _TZFC6Docker7Install29performPrivilegedInstallationfT_T_  (in Docker) + 157  [0x10338f7cd]
                  2693 _TF6Docker14getVmnetdStateFSSOS_11VmnetdState  (in Docker) + 767  [0x1033c472f]
                      2679 read  (in libsystem_kernel.dylib) + 10  [0x7fff8e2a9362]
```

### Steps to reproduce the behavior 
I don't have a reproducible test case outside of my machine but I'm happy to provide further diagnostics.

Thanks!

**Comment by mchiang0610** [comment]
cc @dsheets to see if we can troubleshoot this further.

**Comment by samn** [comment]
Not if this is relevant, I ran into the issue described in https://github.com/docker/for-mac/issues/8 about a month ago and did `sudo rm /Library/PrivilegedHelperTools/com.docker.vmnetd` as suggested in the issue which stopped Docker for Mac from crashing. It had been running fine since then, up until yesterday when it stopped starting.


I uninstalled docker again (removed /Applications/Docker.app, and everything under ` ~/Library/Containers/com.docker.*`), then stopped com.docker.vmnetd (`sudo launchctl remove com.docker.vmnetd`), and reinstalled Docker for Mac and now it works!

**Comment by dsheets** [comment]
This indeed looks like a `vmnetd` issue but it is not straightforward to track down, unfortunately. As you no longer experience the problem, I am going to close this issue. If the problem recurs, please feel free to re-open this ticket.

Thanks for your report!

**Comment by samn** [comment]
Sounds good, thanks @mchiang0610 @dsheets!

**Comment by dfwmountainbiker** [comment]
This also solved it for me after multiple attempts with the same issue.

Thank you!

**Comment by apolishch** [comment]
Ran into this after updating to Catalina. @samn's comment above fixed it
