### ISSUE TITLE
Issue with volume mounts from some directories using M1

### ISSUE THREAD

**Issue by tunecrew** [docker/for-mac#5302]
Switched to a Mac Mini M1 + Docker Preview 7 recently. Attempting to get my existing Intel Mac workflow replicated and encountered the following:

- Mariadb image would start and then exit shortly after.
- Mariadb error log would (randomly) have several different messages for the exit, but they always had something to do with a file either being the wrong size or being corrupted.
- Mariadb image was mounting a local directory called `data` using `volumes` in my `docker-compose` file (in order to persist the database).
- `data` directory was located in my Dropbox folder (which is set to be on my Desktop).

Tried:

- amd64 build of Mariadb, same result.
- reverting to `osxfuse` in the Docker prefs, as others have mentioned, Docker doesn't start when you do this.
- ensured `data` directory was listed in File Sharing Resources in Docker prefs.

What worked:

- moving `data` folder from `~/Desktop/Dropbox/data` and simply to `~/Desktop/data`

A bit beyond my pay grade to analyse the cause of this.

Note that an on my Intel Mac (setup identically) this was not an issue.

**Comment by stephen-turner** [comment]
I suspect this is the same as #5047. We haven't understood that ticket yet, but it looks like a Dropbox folder doesn't behave like a regular folder. Were you using a Dropbox folder on your Intel setup too?

**Comment by tunecrew** [comment]
> I suspect this is the same as #5047. We haven't understood that ticket yet, but it looks like a Dropbox folder doesn't behave like a regular folder. Were you using a Dropbox folder on your Intel setup too?

Thanks - in my Intel Mac setup I was using Dropbox (the two machines have identical OS, software, file layout, etc.) and it worked as expected.

After looking at the ticket, let me add the following - it was not that the docker image couldn't access the mounted directory, it was in fact reading and writing to it, but after some short period this i/o started to fail.

**Comment by galikpali** [comment]
I might have the kind of the same problem: [#5169](https://github.com/docker/for-mac/issues/5169).

**Comment by galikpali** [comment]
@tunecrew , do you have any idea how can I make it work based on my issue's description?
- my project is under my user's home directory
- the volume is mounted from the project's directory
- `Users` dir is enabled as a File Sharing resource in docker settings
- The issue happens when I run some sql migrations (creating and altering database tables)

**Comment by tunecrew** [comment]
@galikpali what worked for me is just moving the data directory outside of my Dropbox folder (it's symlinked back to my project dir which is actually still in my Dropbox folder). Both folders are enabled as File Sharing resources in Docker.

To be fair, I have just done this, now the db stays up when I start it and the relevant tables and files are successful created. I have not really started using it, so maybe I'll encounter an additional issue - will let you know if I do.

**Comment by djs55** [comment]
@tunecrew we've released a new preview build of Docker for M1: https://docs.docker.com/docker-for-mac/apple-m1/ -- it's worth retrying to see if it's any better. This build should have working `osxfs`: it would be interesting to see whether the failure happens with both `osxfs` and `grpcfuse`, or whether it's specific to `grpcfuse`.

**Comment by galikpali** [comment]
Hey @djs55!
I had something similar issue like @tunecrew had, and with the new preview build and grpfuse file sharing feature turned off it works now. 
Unfortunately, I'm facing a new issue regarding volumes which is described here: [#5344](https://github.com/docker/for-mac/issues/5344).

**Comment by tunecrew** [comment]
> @tunecrew we've released a new preview build of Docker for M1: https://docs.docker.com/docker-for-mac/apple-m1/ -- it's worth retrying to see if it's any better. This build should have working `osxfs`: it would be interesting to see whether the failure happens with both `osxfs` and `grpcfuse`, or whether it's specific to `grpcfuse`.

Hello @djs55 I've just gotten back to this - so far working as expected w/ `grpcfuse` enabled, i.e. I've moved my database directory back into Dropbox where it was before (and where it works already on Intel) and no problems.

To be fair, the db creation part works when I start the db container (this is where it failed before) but I haven't gotten to actually using the db yet, so will advise either way on that.
