### ISSUE TITLE
Large Directory Listing Fails

### ISSUE THREAD

**Issue by jimcarreer** [docker/for-mac#5308]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: B422EC01-BF1B-463A-B0AE-FB6F84F7F252/20210131120022
 
### Expected behavior
Listing the directory on the volume shows all files in the directory.

### Actual behavior
Listing returns nothing

### Information
  - macOS Version: 10.14.6
  - docker desktop version: 3.1.0 (51484)
  - docker engine: 20.10.2
  - I am not sure if this is a docker bug, an alpine bug, a Mac bug, or something else
  - I am not sure if this is a known limitation 
  - I can reproduce this consistently
  - I do not know if this a new issue or not, I just encountered it
  - This is a corporate owned workstation, it runs various:
     - security scanning software
     - back up software
     - other administration software 

### Steps to reproduce the behavior
This script reproduces the behavior on my machine:
```bash
#!/bin/bash

echo "MacOS Version / Hardware"
echo "======================================"
uname -mprsv
sw_vers
system_profiler SPHardwareDataType

echo
echo "Docker Version"
echo "======================================"
docker --version


rm -rf ./test-volume/
mkdir -p ./test-volume/big-dir
mkdir -p ./test-volume/lil-dir

for i in {1..188000}; do
  echo "${i}" > ./test-volume/big-dir/${i}.txt
done

for i in {1..1000}; do
  echo "${i}" > ./test-volume/lil-dir/${i}.txt
done

echo
echo "Directory sizes"
echo "======================================"
du ./test-volume
du -h ./test-volume

echo
volume_path=$(pwd)/test-volume/
echo "Files in lil-dir: "
docker run -it --volume ${volume_path}:/data/ alpine:latest sh -c "ls -l /data/lil-dir/ | grep -v total | wc -l"
echo "Files in big-dir: "
docker run -it --volume ${volume_path}:/data/ alpine:latest sh -c "ls -l /data/big-dir/ | grep -v total | wc -l"
```
Output:
```
MacOS Version / Hardware
======================================
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64 i386
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G6032
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: Intel Core i9
      Processor Speed: 2.3 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0)


Docker Version
======================================
Docker version 20.10.2, build 2291f61

Directory sizes
======================================
1504000	./test-volume/big-dir
8000	./test-volume/lil-dir
1512000	./test-volume
734M	./test-volume/big-dir
3.9M	./test-volume/lil-dir
738M	./test-volume

Files in lil-dir:
1000
Files in big-dir:
0
```

**Comment by stephen-turner** [comment]
Interesting, I suspect this is a Docker Desktop bug.

**Comment by stephen-turner** [comment]
@djs55 Have we seen anything like this before?

**Comment by jimcarreer** [comment]
Something I left out that seems important now:

It appears to be related to the size of the flat directory, not the number of files in it.  That is to say, the actual scenario I hit this issue in, the directories in question had ~150K and ~130K, but since the files in these directories have actual data in them, not just a few bytes (like my example), they exceed ~730M in size.   That number doesn't look "magical" too me, though I do not know the exact threshold to the byte where the issue starts manifesting.

**Comment by jimcarreer** [comment]
Alright, issues been quiet for a bit.  So if this eventually gets closed out because its gone stale or some other reason, and for posterity, the best solution I could find for this is to use named volumes instead of bind mounts.  In the context of my problem this is an OK solution as having direct access to the volumes on the host was a "nice-to-have" but not really necessary for the problem I was solving.
