### ISSUE TITLE
Docker Desktop for Mac has no "Hide" menu in the menubar

### ISSUE THREAD

**Issue by kengruven** [docker/for-mac#5311]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

The application menu should have "Hide Docker Desktop", "Hide Others", and "Show All" menu items, with the standard keyboard shortcuts.

### Actual behavior

The only items in the application menu are "About" and "Quit Docker Desktop".

### Information

  - macOS Version: 10.15.6 (19G2021)

### Steps to reproduce the behavior

  1. Open Docker.app
  2. From the menu bar item in the top right (whale icon), choose "Dashboard" (to open Docker Desktop.app)
  3. Press command-H to hide it -- nothing happens

The Docker Desktop application does support being hidden, like any normal Mac application, but only via its dock icon menu.

**Comment by balibebas** [comment]
`Cmd+Q` dismisses the pop-up widow. This wouldn't be an issue if it didn't open in the first place. What's the point of that anyway? It just creates more work for developers many of whom would prefer to use the Docker binary if they could.

**Comment by kengruven** [comment]
Cmd-Q is Quit, which is entirely different from Hide.

Docker Desktop doesn't open files, like most Macintosh applications, but it does have local state.  You can't instantly return to what you were working on with Quit + re-open.

(There's actually two "Quit Docker Desktop" menu items which claim to be cmd-Q, but they do very different things.  I'm assuming you mean the one where cmd-Q actually works.)

Besides, Hide does work on Docker Desktop.  It's available through both the Dock and the application switcher.  It's just been removed from the menubar, for some reason.
