### ISSUE TITLE
Unable to start after turning off "Experimental Features > Use gRPC FUSE for file sharing" 

### ISSUE THREAD

**Issue by adi-kopelevich** [docker/for-mac#5313]
Early adopters of Apple M1 Tech Preview https://docs.docker.com/docker-for-mac/apple-m1/
Docker Desktop is unable to start back after turning off "Experimental Features > Use gRPC FUSE for file sharing" 
Which is required for our case 

  - Diagnostics ID: B62AF109-5D67-42E7-8D5E-B767AED5936E/20210203140944

### Expected behavior
Restart after turning off "Experimental Features > Use gRPC FUSE for file sharing" should work

### Actual behavior
Unable to restart after turning off "Experimental Features > Use gRPC FUSE for file sharing" should work

### Information
  - Is it reproducible? Y
  - Is the problem new? Y
  - Did the problem appear with an update? N
  
  - macOS Version: MacBook Pro Apple M1 2020, macOS Big Sur

### Steps to reproduce the behavior
  1. installed Docker Desktop from https://docs.docker.com/docker-for-mac/apple-m1/
  2.Turned off "Experimental Features > Use gRPC FUSE for file sharing" 
  3. Restart => Docker Desktop is unable to start - hangs on Starting status

**Comment by stephen-turner** [comment]
Thanks, this is a known issue. osxfs can't work in Apple's new virtualization framework.

**Comment by trip-somers** [comment]
@stephen-turner Can you elaborate or share a link about this? This feature was unchecked for me before upgrading to v3.1.0, and everything was working just fine. After upgrading, my containers sometimes don't start, sometimes don't stop once they've started, and several operations from inside the containers now cause the execution to lock up.

I was happy with v2.5.x, and I honestly can't even use v3.1.0.

**Comment by stephen-turner** [comment]
@trip-somers Yes, this is specific to M1. If you're on an Intel Mac, you must have a different bug.

**Comment by djs55** [comment]
@adi-kopelevich @trip-somers the latest M1 preview build now supports `osxfs`. The download link is here: https://docs.docker.com/docker-for-mac/apple-m1/

I'll close this ticket but please open a fresh one if you encounter other problems!
