### ISSUE TITLE
No "Hide/show Icon in Menu Bar" option for Mac

### ISSUE THREAD

**Issue by miyamotokenji** [docker/for-mac#5316]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
Have a hide/show icon in the menu bar option available 

### Actual behavior
No hide/show icon in the menu bar option available

### Information
This issue (#4416) elaborates on it more. I understand that docker desktop is designed for use in a desktop environment https://github.com/docker/for-mac/issues/5114#issuecomment-742397936, but this option should at least be available for those who don't want to clutter up their menu bar.

  - macOS Version: 10.15.6

**Comment by lucabezerra** [comment]
This seems to be a duplicate of https://github.com/docker/for-mac/issues/5311

**Comment by miyamotokenji** [comment]
> This seems to be a duplicate of #5311

I think that issue talks about the hiding the actual application window, not the menu bar icon.

**Comment by lucabezerra** [comment]
> > This seems to be a duplicate of #5311
> 
> I think that issue talks about the hiding the actual application window, not the menu bar icon.

I guess you're right, my apologies!

**Comment by balibebas** [comment]
This wouldn't be an issue if we didn't have to install a Mac App just to use what should be packaged as a binary and distributed through a proper package manager as it ought do. I will never fully understand that design decision. A much better architecture for Docker Desktop would be something akin to Lens (for Kubernetes) where it connects to an API and powers your run-of-the-mill Electron app.

**Comment by balibebas** [comment]
This wouldn't be an issue if we didn't have to install a Mac App just to use what should be packaged as a binary and distributed through a proper package manager as it ought to. I will never fully understand that design decision. A better architecture for Docker Desktop would be something akin to Lens (for Kubernetes) where it connects to an API and powers an Electron app.

**Comment by balibebas** [comment]
This wouldn't be an issue if we didn't have to install a Mac App just to use what should be packaged as a binary and distributed through a proper package manager as it ought to. I will never fully understand that design decision. A better architecture for Docker Desktop would be something akin to Lens (for Kubernetes). API => Electron App (Optional)
