### ISSUE TITLE
Docker does not start on OS X

### ISSUE THREAD

**Issue by winkste** [docker/for-mac#5317]
Hi.

I'm new to Docker and want to try it on my MacBook Pro. I installed the latest version of Docker (I guess) and started it getting the following error message:

one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 1123)
version of docker downloaded direct from the repo link:
one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 1794)

I restarted the MacBook without success, same error message

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
- this didn't work, endless loop.
- 
### Information

  - macOS Version: 11.1
  - Docker: 3.1.0

### Steps to reproduce the behavior

  1. Download Docker
  2. Install Docker
  3. Allow access as requested

**Comment by gtskaushik** [comment]
I'm facing the same issue. 

MacOS: 10.15.7
Docker for Mac: 3.1.0

Docker is stuck on starting

**Comment by harrouet** [comment]
Same issue, like many others, documented many times, but no one seems to care at Docker.
I isolated to be linked to authentication certificates, but can't go much further.

**Comment by gtskaushik** [comment]
Everytime my docker engine starts or when I have to pull new images, I have to disable firewall in McAfee temporarily

**Comment by winkste** [comment]
No suggestions for a solution? Re-Tested it with the current latest docker version (27.02.2021 downloaded), same results. From my point of view docker is currently not working under OSx Big Sur.

**Comment by harrouet** [comment]
Yes that’s a fact. Docker is not a reliable solution for development under MacOS.
I hope this never happens for production systems.
And the worst is, Docker does not seem to even acknowledge the issue. They keep closing the tickets as they come!

**Comment by winkste** [comment]
Yes, agreed. Workaround: using a VirtualBox VM with Debian Linux to run docker. Sounds contradicting the docker philosophy, or?
