### ISSUE TITLE
 request for kernel 5.4+ on Mac Silicon for XDP dev

### ISSUE THREAD

**Issue by mwiget** [docker/for-mac#5318]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Feature request to upgrade linux linuxkit kernel from 4.19.104 (on M1) and 4.19.121 (on intel) to 5.4 or newer.

Using Docker Desktop on Mac M1 to develop some XDP applications, which works great, as long as I stick to features available in linux 4.19. Unfortunately I now need net device hash maps, which have been added with kernel 5.4 (https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md). 

### Information

  - macOS Version: 11.2

### Steps to reproduce the behavior

In case you wonder, if XDP even works. You can try out this: https://gitlab.com/mwiget/crpd-xdp-router/-/tree/master/xdp-drop-test/ 

What doesn't work, is loading xdp code taking advantage of the missing kernel functionalities, e.g. in
https://gitlab.com/mwiget/crpd-l2tpv3-xdp/-/tree/master/vxlan, in particular this: BPF_MAP_TYPE_DEVMAP_HASH, introduced to Linux via https://github.com/torvalds/linux/commit/6f9d451ab1a33728adb72d7ff66a7b374d665176

**Comment by stephen-turner** [comment]
Yes, we want to upgrade to 5.4. In fact, we did upgrade our internal branch, but we had to roll it back because of some crashes that we haven't been able to figure out yet. So we still need to do an unknown amount of work before we can re-enable it.

**Comment by mwiget** [comment]
Cool! Good to know there are plans to upgrade at some point. Let me know if I should keep this request open or just watch out for updates. Understand, the ETA is unknown at this point.

**Comment by stephen-turner** [comment]
Thanks, @mwiget. If you're happy to just watch for updates, then feel free to close the ticket.

**Comment by mwiget** [comment]
I'm ok to close this (while keeping an eye on updates). thanks.
