### ISSUE TITLE
Docker Cannot Pull From Hub on Mac M1 with OS 11.1 & 11.2

### ISSUE THREAD

**Issue by RS-Roshi** [docker/for-mac#5319]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8A9F330D-95E0-4D74-9B41-29C2F93AF96A/20210206122053

### Expected behavior
Docker should access the repository hub 

### Actual behavior
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.11:53840->192.168.64.1:53: read: connection refused

### Information
  - macOS Version: Tested on both 11.1.1 & 11.2
  - Docker Test Preview

**Comment by jason-klein** [comment]
@RS-Roshi  Are you also running Laravel Valet? If so, this is a [known Laravel Valet issue](https://github.com/laravel/valet/issues/1031).

**Comment by stephen-turner** [comment]
There are lots of networking things that aren't fully working in the latest preview. We plan to have a new preview this week that will fix many of them.

**Comment by RS-Roshi** [comment]
I Fixed this issue but Uninstalling Laravel/Valet & Stopping dnsmasq & Restarted my Mac then Started Docker and then it can connect to Hub.
Thanks

**Comment by djs55** [comment]
@RS-Roshi I'm glad to hear that you've fixed your issue.

There is a new Docker Desktop for M1 preview if you'd like to try it: https://docs.docker.com/docker-for-mac/apple-m1/

I'll close this issue but feel free to open new ones if you have more problems in future.
