### ISSUE TITLE
Unable to do any docker command

### ISSUE THREAD

**Issue by ramapalani** [docker/for-mac#532]
### Information

Diagnostic ID: BD6002C8-7C51-48C8-8BDD-9156F19874F2
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
merging with https://github.com/docker/for-mac/issues/534
