### ISSUE TITLE
No matching distribution found for tensorflow when building Docker image

### ISSUE THREAD

**Issue by daniel-bejarano** [docker/for-mac#5320]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I'm creating an image from a Dockerfile, which includes installing packages from a requirements.txt file. However, many packages have returned an error saying " Could not find a version that satisfies the requirement <package_name>==<version>. No matching distribution found for <package_name>".

I found a way around most packages, by changing their release version for instance, but I can't get tensorflow to install.

### Actual behavior
When I build images from other computers, including Windows, Linux and iOS not running on M1 chips, everything works well. But in the Preview version of Docker for M1 that I have this issue persists even when trying different base images, or different order of package installations, updating pip, etc.

### Information
This problem is reproducible on my 13-inch MacBook Pro running on an M1 chip.
The problem does not exist in any other machine I've tried.
The problem did not occur because of an update but the machine is brand new.

macOS Version: Big Sur 11.2

### Steps to reproduce the behavior
Running "docker build -t image_name -f Dockerfile ."

### Dockerfile contents:
FROM python:3.8-slim. # have also tried 3.6 and 3.7

WORKDIR /usr/app

ENV ENVIRONMENT "local"

RUN apt-get update \
    && apt-get install -y python-pip \   # have also tried python3-pip
    # Install requirements for psycopg2
    && apt-get install -y --no-install-recommends libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata \ 
    && pip install --upgrade pip  # have also tried not running this line

RUN pip3 install Cython==0.29.15 numpy==1.17.3   # I have also tried moving tensorflow==2.3.1 to this line from requirements.txt

COPY ./requirements.txt /usr/app/requirements.txt
RUN pip install -r requirements.txt

**Comment by stephen-turner** [comment]
This looks like a Python problem, not a Docker problem?

**Comment by daniel-bejarano** [comment]
Thanks for the reply, Stephen. 

It could be so, and maybe it's my understanding that is flawed but I thought that it being a container as long as the Dockerfile is the same it would result in the same image being built regardless of what machine is used to create such image.

That's why I thought that since the same exact Dockerfile successfully builds the image when using other machines, it failing on my M1 Mac could be a result of the not-yet finalized (a.k.a. Preview) Docker configuration for silicon chips.

**Comment by stephen-turner** [comment]
Yes and no. The difference here is that you're running on an arm64 architecture, so you're not actually running the same binary, you're going to be running an arm64 build of Python. I'm not a Python expert, but I assume that it's then looking for an arm64 version of your package and not finding one.

**Comment by daniel-bejarano** [comment]
I see! Ok that makes sense. And that's likely what the problem is. 

I'll look for how to build using a different binary or see if there's a version of the package that can run on arm64.

Thanks you!

**Comment by leopons** [comment]
I have the exact same issue.

Leandree nope, it doesn't work for me.
As Stephen said, I think it's just that docker still needs an arm64 build of tensorflow to run it on the M1 chip, and tensorflow hasn't released one yet.

There is [a fork from apple](https://github.com/apple/tensorflow_macos) that works on M1 though. But the installation instructions make it run on a local venv.

I've asked them if there was a way to make it work with docker : https://github.com/apple/tensorflow_macos/issues/164

**Comment by phamhoangtuan** [comment]
I have the same issue when trying to build docker image:
- Run `pip install tensorflow~=2.4.0` and have error 
```
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0
ERROR: No matching distribution found for tensorflow~=2.4.0
```
- Run `pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.4.0-cp37-cp37m-manylinux2010_x86_64.whl` and have error
```
ERROR: tensorflow_gpu-2.4.0-cp37-cp37m-manylinux2010_x86_64.whl is not a supported wheel on this platform
```
I used the `python:3.8` image with pip already upgraded to the latest version

**Comment by stephen-turner** [comment]
Per above discussion, this is a bug in the container not in Docker Desktop.
