### ISSUE TITLE
Docker Fatal Error on startup (vpnkit)

### ISSUE THREAD

**Issue by MarkKewley** [docker/for-mac#5326]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features (unable since it fails on startup)
  - [x] I have uploaded Diagnostics 
  - Diagnostics ID: 8DAC51BA-9F5B-48B5-968C-DEF13C801915/20210209191134
  - I was unable to via the GUI as it sits in spinner "Diagnosing...", waited for 2 hours but nothing so I ran the ` /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload` command. Hopefully these are equivalent tasks.

### Expected behavior
The Desktop application should start with no issues

### Actual behavior
See this Fatal error 
![image](https://user-images.githubusercontent.com/24749053/107407959-f0766e80-6acf-11eb-8290-40c8720074bc.png)

### Information

Please, help us understand the problem.  For instance:
  - **Is it reproducible?**
    It is on my machine I guess, not seeing others having this issue though.
  - **Is the problem new?**
    No, I think it's been an issue for a few weeks for me
  - **Did the problem appear with an update?**
    No, I tried installing older version (back to v2) and it was still prevalent
  - **A reproducible case if this is a bug, Dockerfiles FTW.**
    N/A
  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior
I don't know if it will be easily reproducible as it just happens upon startup of my Docker desktop app. I'm unable to even use the Docker Hub application (e.g. go into preferences/view troubleshooting)

**Comment by Tinkesh-Kumar** [comment]
I am also facing the same issue. Tried downgrading the docker version. That also did not help. Looking forward for solution

**Comment by Tinkesh-Kumar** [comment]
Running this command help me in starting the docker.
Run these command in Terminal
**open --background -a Docker**
**while ! docker system info > /dev/null 2>&1; do sleep 1; done**

**Comment by MarkKewley** [comment]
@Tinkesh-Kumar 

Glad someone else is experiencing similar issues. I tried running those commands but I was still prevented with the same error message. I hope the team can get back to us soon!
