### ISSUE TITLE
Huge CPU, no containers running, after docker restart, docker-desktop 3.1.0

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5327]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4878CE31-EDDB-4988-A949-52FEC38CFC79/20210210162511

### Expected behavior

With no containers running, docker shouldn't be using much CPU

Sorry, I know there are dozens of these issues out there. Most of the recent ones seem to involve hyperkit, which I don't see in the process list as a problem.

### Actual behavior

My fan is running like crazy, Activity Monitor shows docker essentially using 100% of one cpu.

This is *after* I have stopped all containers AND restarted docker desktop.

Docker desktop 3.1.0

<img width="946" alt="Activity_Monitor" src="https://user-images.githubusercontent.com/112444/107539568-53284280-6b82-11eb-89a9-8d4cf4fea43d.png">

### Information

  - macOS Version: Big Sir 11.2
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior

I haven't seen this the whole time I've had 3.1.0 I don't think. And I usually have quite a lot of containers running. No idea why it would have just started running the fan today.

**Comment by hanoii** [comment]
Probably duplicate of #5164

**Comment by rfay** [comment]
#5164 says it's com.docker.backend, but that wasn't my experience here.

**Comment by hanoii** [comment]
Sorry, maybe still related. Did you get the same running `top`?

**Comment by mrmachine** [comment]
I am seeing the same thing. I have only a handful of containers running, but all are idle. Activity Monitor is reporting ~165% CPU used by Docker. Even after I stop all containers. Even after I restart Docker. Even after I QUIT Docker, Activity Monitor continues to list one Docker process at ~165%.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/51939/108167325-9f0e5500-7149-11eb-9b1d-1284209a88ca.png">

**Comment by mrmachine** [comment]
Update: I killed the above processes, and did not relaunch Docker... yet, the processes came back and are still using even more CPU now... even while `docker` CLI cannot connect to docker daemon.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/51939/108201184-9599e280-7173-11eb-92e4-bba4ad06c059.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/51939/108201226-a64a5880-7173-11eb-8650-de9514600e1c.png">
