### ISSUE TITLE
When starting Docker,it always asking to restart become factory default

### ISSUE THREAD

**Issue by hualoqueros** [docker/for-mac#5330]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Close the docker for mac
  2. Then open again
  3. it will asking to reset

**Comment by dantheman0207** [comment]
I have this issue as well.
