### ISSUE TITLE
Docker container with Apline and nginx Lua not start (Mac M1)

### ISSUE THREAD

**Issue by mksada** [docker/for-mac#5337]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Container will start

### Actual behavior

Container exited with error:

`nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:95`

### Information
My Dockerfile

`FROM XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/alpine:3.12

RUN apk add --no-cache nginx \
    nginx-mod-http-lua \
    nginx-mod-http-geoip

RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/nginx/sites-enabled

COPY src/conf/nginx.conf /etc/nginx/nginx.conf
COPY src/conf/extended_log.conf /etc/nginx/conf.d/extended_log.conf
RUN rm -f /etc/nginx/conf.d/default.conf

# SSL cert
RUN mkdir -p /etc/nginx/ssl
COPY src/conf/xxxx.test.* /etc/nginx/ssl/

# For nginx directory root
RUN mkdir -p /var/www/html
RUN touch /var/www/html/index.php

COPY src/conf/sites-available /etc/nginx/sites-available

RUN ln -s /etc/nginx/sites-available/xy /etc/nginx/sites-enabled/xy && \
    ....
    .....

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
`

  - macOS Version: Big Sur 11.2.1
  - Docker Desktop Version: Docker Desktop preview 3.1.0 (60984)

Write me if you need more informations about this issue

**Comment by stephen-turner** [comment]
This looks like a problem in the contents of your container, not a bug in Docker.
