### ISSUE TITLE
docker ps failed

### ISSUE THREAD

**Issue by pasgou** [docker/for-mac#534]
### Expected behavior
Starting docker should work
### Actual behavior
docker doesn't start properly and stay in the state "docker starting ..."
### Information

Diagnostic ID: F96B75C5-8630-4E63-A26D-25DABF16F1A4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
I installed Docker Mac app
It has started
I have Installed postgres:9.4 and odoo
It has worked
I removed odoo to replace it by odoo:8.0
Docker has stopped and doesn't start anymore even after a computer restart

**Comment by mchiang0610** [comment]
merging with #527
