### ISSUE TITLE
Unable to resolve hosts when VPN is enabled

### ISSUE THREAD

**Issue by kwiechmann** [docker/for-mac#5340]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - "Enable cloud experience" and "Use gRPC FUSE for file sharing" are both enabled
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FB726619-5C9D-4D7F-8506-8A44BEA50C9E/20210212134608

### Expected behavior
github.com home page HTML

### Actual behavior
curl: (6) Could not resolve host: github.com

### Information
  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.1.0 (51484)
  - Cisco AnyConnect: 4.9.03047
  - docksal/fin: 1.102.0

### Steps to reproduce the behavior
- FROM docksal/cli:2-php7.4
- fin bash
- curl https://github.com
- **or**
- FROM docksal/cli:2-php7.3
- fin bash
- curl https://github.com

**Comment by stephen-turner** [comment]
I think you will have to talk the administrator of your AnyConnect to unblock the connection.
