### ISSUE TITLE
(M1) one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug

### ISSUE THREAD

**Issue by arielweinberger** [docker/for-mac#5343]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Diagnostic stalling
Using Tech Preview

### Expected behavior
Docker Tech Preview starts and runs normally.

### Actual behavior
The following error shows up:
``` one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug```

Diagnostics run forever.

### Information

  - macOS Version: Big Sur 11.1
  - Docker Desktop Version: Tech Preview v7

I was able to use the Tech Preview of Docker for about 3 weeks on my M1 Macbook Pro, and then suddenly the issue started occurring. Restarting, reinstalling etc does not help. I see others are experiencing the same.

I am not able to bring up the UI at all, it completely crashes after the erro comes up.

### Steps to reproduce the behavior

  1. Download Tech Preview version 7
  2. Run Docker
  3. Error shows up

**Comment by StefanScherer** [comment]
There is a new preview you could try. You can find more information about it at https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by arielweinberger** [comment]
Downloaded the latest build from that link (Docker Desktop preview 3.1.0 (60984)) and facing the same issue.

<img width="626" alt="Screenshot 2021-02-14 at 12 07 02" src="https://user-images.githubusercontent.com/4976416/107874907-38750700-6ebd-11eb-8568-b14fe3ad9a53.png">

**Comment by StefanScherer** [comment]
Could you upload diagnostics data, or does it crash as well?
We haven‘t encountered this error on our machines. 🤔 We are running macOS 11.2.1

**Comment by arielweinberger** [comment]
Hey Stefan, thanks a lot for your swift response! I cannot run diagnostics, it fails.
When heading to the `console.log` file it exists, but it's empty.

**Comment by arielweinberger** [comment]
Update: Upgrading to 11.2 seemed to have fixed the issue. No clue why it was working on 11.1 for about a month and suddenly stopped, but the update fixed it.

**Comment by aschoenenberg** [comment]
Hey,
I am using the new Version (Docker Desktop preview 3.1.0 (60984)) On Big Sur 11.2.1 and get the following error:
`one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug`

The Preview 7 runs before with 11.2

Thanks for your support
