### ISSUE TITLE
(M1) Docker doesn't start up when using Internet Sharing.

### ISSUE THREAD

**Issue by wancom** [docker/for-mac#5348]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - The docker cannot finish the diagnostics. (I waited for few hours but the process seems not to work.)

### Expected behavior
When I start the docker, the docker engine will start up successfully.
Or when using docker, the docker engine will continue working.

### Actual behavior
When using docker, the docker engine crashed with a following error.
```
2021-02-14T13:06:38Z dockerd time="2021-02-14T13:06:38.518241501Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
```

I reset docker to factory defaults and restarted the docker, I still get the following error.
```
one of the sub-processes failed: com.docker.driver.amd64-linux -addr fd:3 -debug (pid: 11208)
```

### Information

  - macOS Version: macOS Big Sur 11.2.1 (20D74)
  - Docker Desktop Version: 3.1.0 (60984)
  - I'm using beta for Apple Silicon(m1 Mac mini)

The error is reproducible in my environment(m1 Mac mini).
This is my hypothesis about the error.
- If `Internet Sharing` in system preferences is enabled and the Mac is sharing the internet connection with iOS device, the error occurred.
- The process `com.apple.Virtualization.VirtualMachine` affects the problem. I found crash log about the process as follows.
```
Process:               com.apple.Virtualization.VirtualMachine [11228]
Path:                  /System/Library/Frameworks/Virtualization.framework/Versions/A/XPCServices/com.apple.Virtualization.VirtualMachine.xpc/Contents/MacOS/com.apple.Virtualization.VirtualMachine
Identifier:            com.apple.Virtualization.VirtualMachine
Version:               1.0 (18.5)
Build Info:            Virtualization-18005000000000~52
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
User ID:               501

Date/Time:             2021-02-14 22:18:46.950 +0900
OS Version:            macOS 11.2.1 (20D74)
Report Version:        12
Anonymous UUID:        6FC763E3-A11E-0924-6AEA-1BF8DC09E5C5


Time Awake Since Boot: 41000 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.virtualization.virtual-machine

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       EXC_ARM_BREAKPOINT at 0x0000000100e42f34 (brk 1)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [11228]

Application Specific Information:
dyld3 mode
FIXME: "Failed to initialize device 'com.apple.virtualization.virtio.network-device:0'"

CONT...
```

### Steps to reproduce the behavior
1.  Turn on Internet Sharing with iOS devices in System Preferences.
2. Start docker.
3. We may get the errors as described above.

Welcome for any request (like additional information.)
I hope the issue helps improvement for docker. I'm sorry if I disturb you.

**Comment by wancom** [comment]
Perhaps, the bridge device `bridge100` (which docker may use) conflicts with Internet Sharing?

**Comment by dbj** [comment]
I can also confirm this occurs on macOS Big Sur 11.2.2 (vs. 11.2.1 as noted above).  This is a show stopper for me.

**Comment by djs55** [comment]
Thanks for the reports. I've been able to reproduce this issue locally -- it seems that the `vmnet.framework` used via the `virtualization.framework` used by Docker on M1 has a conflict with Internet Sharing. When I try to start Docker I see the error in the `Console.app`:
```
VMNet in NAT mode can’t be started now due to an active InternetSharing session on en0
```
If I have Docker running already and try to use Internet Sharing, my phone fails to get an IP address from my Mac.

I've filed this as an issue with Apple and added a ticket to our backlog.

**Comment by stephen-turner** [comment]
Please try the new build at https://docs.docker.com/docker-for-mac/apple-m1/ and give us feedback whether it solves this problem (and whether it causes any new problems!). Thank you.

**Comment by dbj** [comment]
I can confirm that docker launches and I can run `docker run hello-world`.  I'll continue to watch and see if the qemu backend causes any other issues.

**Comment by wancom** [comment]
Thank you for information!
I also confirm that docker looks working well with Internet Sharing!
I'll keep using the docker!

**Comment by dbj** [comment]
And I should have added a big "Thank  you!!"  :)  Thanks for your hard work on this.

**Comment by stuartcarnie** [comment]
I am seeing this crashloop when running Docker 3.3.3, x86_64 host, internet sharing is enabled and an RPi is attached

**Comment by wancom** [comment]
Hi @stuartcarnie !

Are you trying "new virtualization framework?"
Currently, the framework may have some bugs like that.

Please check docker preferences -> "Experimental Features" -> "Use new virtualization framework."
If the checkbox is checked, please uncheck and try again.

I hope you can escape the crashloop.

**Comment by stuartcarnie** [comment]
hi @wancom yes I am – I was suspicious that might be the issue. I'll turn it off and try again – thanks!
