### ISSUE TITLE
Deleting file on mounted dir causes docker to hang on subsequent start

### ISSUE THREAD

**Issue by three-old-coders** [docker/for-mac#5352]
- [X] I have tried with the latest version of Docker Desktop v 3.1.0 and previous versions
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior

- ability to run the script multiple times (partly possible)
- kill stuck container (impossible)

### Actual behavior

Find docker files below. I create the container using the docker-compose.yml file. This includes a basic build file to include "curl" which I need in my container, but is not required for this test. When run the docker container just executes a "ls" command and lists the content of the mounted "tmp" directory. As soon the file in /tmp is deleted run starts the container again, but the container stucks and can't be killed. Only "troubleshoot / restart" kills the container and it starts working again, until the next delete occurs.

<b>Directory content:</b>

/ERR
&nbsp;&nbsp;&nbsp;/tmp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x.txt
&nbsp;&nbsp;&nbsp;Dockerfile\
&nbsp;&nbsp;&nbsp;docker-compose.yml

<b>Dockerfile</b>

FROM alpine:latest

RUN apk update
RUN apk add bash
RUN apk add curl

<b>docker-compose.yml</b>

version: '3.6'
services:
&nbsp;&nbsp;err:
&nbsp;&nbsp;&nbsp;&nbsp;build:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context: .
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dockerfile: Dockerfile
&nbsp;&nbsp;container_name: err
&nbsp;&nbsp;command:
&nbsp;&nbsp;&nbsp;&nbsp;ls -lrt /tmp
&nbsp;&nbsp;volumes:
&nbsp;&nbsp;&nbsp;&nbsp;- ${PWD}/tmp:/tmp:rw

<b>run script</b>

#!/bin/bash

docker-compose run --rm err

### Steps to reproduce the behavior

1. create container: docker-compose up
2. ./run.sh (lists directory content, one file)
3. rm tmp/t.txt
4. ./run.sh (container hangs, ctrl+c not working, docker kill not working)
5. troubleshoot --> restart (kills container)
6. ./run.sh (lists directory content again, no files)

**Comment by three-old-coders** [comment]
[ERR.zip](https://github.com/docker/for-mac/files/5987991/ERR.zip)

**Comment by three-old-coders** [comment]
Updated mac os x to 10.15.7, rebooted, but problem persists.
Maybe it is linked to [https://github.com/docker/for-mac/issues/809](url)
I created trace files as proposed, let me know if you are interested in the traces to track it down

**Comment by SamYuan1990** [comment]
I have similar issue, I am going to do a loop testing.

```
docker up with config A
run sth
docker clean up
sleep

docker up with config B
run sth
docker clean up
sleep

etc...
```

**Comment by three-old-coders** [comment]
Anything else I can do, provide more info?
