### ISSUE TITLE
macOS M1 crash during docker buildx build, events.TaskDelete

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5353]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics - (diagnostics after restart)
  - Diagnostics ID: 165EF212-DB99-4FE1-90A4-E516A309B23F/20210223152816

### Expected behavior

No crash

### Actual behavior

During docker buildx build, apparently during the --load phase, "Exporting layers", docker crashes with a fatal error

<img width="598" alt="Randyfay_com_-_Calendar_-_February_2021" src="https://user-images.githubusercontent.com/112444/107979088-28236180-6f7b-11eb-90e2-4408b41e0346.png">

It's something about Events.TaskDelete

I've seen this now a couple of times. Maybe it's a crash on restart after a failure

It's frustrating that one can't provide any diagnostics after a failure like this, and that https://github.com/docker/for-mac/issues/4848 was never addressed or even responded to.

### Information
  - macOS Version: Big Sur 11.2.1
  - Docker Desktop Version: M1 preview 3.1.0 (60984)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
You should be able to provide diagnostics next time you launch Docker Desktop: the logfiles will still be there.

Is it crashing when building an Intel image? I wonder if this is a qemu bug.

**Comment by rfay** [comment]
I'll try the diagnostics-after-restart @stephen-turner. BTW, I'm pretty sure that although that dialog box says "Docker failed to start" it was actually complaining that docker crashed? In all cases so far with 60984 I've been able to restart docker after something like this without extraordinary measures.

No, my judgment at the time was that it was building only arm64 image, and it happened when trying to --load it into local docker, and of course you can't load amd64 into m1 docker.  But I could be wrong, I'll pay closer attention. But now I'm doing most bigger docker builds on amd64 machine because I got bit by this too many times.

**Comment by rfay** [comment]
I got this crash again today, here are the diagnostics, 165EF212-DB99-4FE1-90A4-E516A309B23F/20210223152816

This happened during container creation (`ddev start`)

**Comment by vvondra** [comment]
I've experienced the same `331A8A23-EBB3-430A-960B-A549FFDBF936/20210224175323`

![image](https://user-images.githubusercontent.com/101691/109043494-b3b29600-76d1-11eb-877a-2ea080d445f0.png)

**Comment by rfay** [comment]
This really happens quite a lot. Very much worth addressing. There are now diagnostics here.

**Comment by stephen-turner** [comment]
Thanks @rfay, we have this on the current sprint.

**Comment by stephen-turner** [comment]
Going back to your earlier point, @rfay, you can also collect diagnostics from the command line: https://docs.docker.com/docker-for-mac/troubleshoot/#diagnosing-from-the-terminal

**Comment by rfay** [comment]
@djs55 did this get addressed in recent RC work?  Since I had to go back to pre-RC this reminded me of itself right away :)

**Comment by stephen-turner** [comment]
I'm just tidying up old tickets. This has gone now, hasn't it @rfay?

**Comment by rfay** [comment]
I haven't seen this in ages. Thanks.
