### ISSUE TITLE
Crashes first time it is run only. (After trying through homebrew)

### ISSUE THREAD

**Issue by samjewell** [docker/for-mac#5354]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A25DD90A-4ED3-4C22-A0C0-C55E30E0BB19/20210215225437

### Expected behaviour
Docker for Mac boots without crashing the very first time

### Actual behaviour
The first time I run it, it is frozen in "Docker Desktop is starting"
<img width="274" alt="image" src="https://user-images.githubusercontent.com/2903904/108045593-8b74c880-703b-11eb-8393-c4808ee3be48.png"> and asks me to submit a crash report and GitHub issue.

<img width="600" alt="Screenshot 2021-02-16 at 09 45 09" src="https://user-images.githubusercontent.com/2903904/108051171-7b141c00-7042-11eb-920f-a93fa7d5c1cd.png">

Then I actually clicked "Reset Docker to factory defaults" and then tried again, and it then worked fine for me.

### Information

  - Is it reproducible?
     - Only happens the first time I try to run Docker Desktop for Mac
  - Is the problem new?
     - No idea
  - Did the problem appear with an update?
     - This is my first time using the M1 preview, so I don't know
  - A reproducible case if this is a bug, Dockerfiles FTW.
     - …?
  - macOS Version:
     - 11.1
  - Docker Desktop Version:
     - 3.1.0 (60984)

### Steps to reproduce the behavior

  1. From a fresh copy of macOS 11.1 on a brand new MacBook Pro, first use home-brew to 
     1. `brew install --cask docker`
     2. Try to run the docker just installed (`version 3.1.0,51484 of Cask docker`)
     3. Uninstall it again: `brew uninstall docker`
  2. Install the Preview of Docker for M1 Macs from the website, and then run it.

**Comment by stephen-turner** [comment]
Thanks for the report. It would be interesting to know whether this only happens with `brew` or whether it also happens when running our installer directly.

**Comment by stephen-turner** [comment]
I think I also saw some chatter about this on the community Slack.

**Comment by alicemirandola** [comment]
`Docker version 3.1.0(60984)`
I just installed and ran it directly from the installer and it is running fine the first time. It might be something with the brew installation?

**Comment by SjorsSchijff** [comment]
This is not a problem exclusive to M1. When initially installing docker-desktop through homebrew (on Catalina) it fails to correctly install the privileged helper tools. Uninstalling and installing directly using the docker-desktop installer subsequently fails.

Forcing helper installation by running

```
/Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components
```

does trigger the helper installation dialog but the application freezes after clicking the 'Ok' button. Same problem arises on 3 separate MacOS installations..

**Comment by Ogala** [comment]
@stephen-turner I was able to replicate this issue running the docker installer directly. But in my case, I think it is worth mentioning that I had earlier tried to install the regular docker for mac.
