### ISSUE TITLE
Docker status is not changing from starting state to running state

### ISSUE THREAD

**Issue by SaiChandraCh** [docker/for-mac#5359]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3CEFC086-F9AF-444E-B27C-1CBD2D6BE378/20210217052100

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by harrouet** [comment]
I have been having the same issue for months, just like others, but Docker does not seem to care.

**Comment by sajalmakharia** [comment]
mac cataline : 10.15.7
docker : 3.1.0 
started only once but not starting after that

**Comment by aDovbiy** [comment]
mac cataline : 10.15.7
docker : 3.1.0
I have the same problem.

**Comment by harrouet** [comment]
+1
Same problem here, as many others, and tickets keep closing after 30 days without a solution.

**Comment by sajalmakharia** [comment]
the firewall is preventing this so the firewall(in my case mcafee) needs to be temporarily disabled

**Comment by harrouet** [comment]
No, in my case it is absolutely not linked to the firewall.

>
