### ISSUE TITLE
Update docker-compose to stable version (1.28.2)

### ISSUE THREAD

**Issue by duanehutchins** [docker/for-mac#5360]
- [x] I have tried with the latest version of Docker Desktop

### Expected behavior

docker-compose Version: 1.28.2 (stable)
This version was released in January 2021 but not yet included with Desktop for Mac.

### Actual behavior

docker-compose Version: 1.27.4
This version was released in September 2020 and added into Desktop for Mac the same month

### Information

  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior

  1. Install Docker Desktop for Mac 3.1.0
  2. Check Docker-Compose version

**Comment by stephen-turner** [comment]
Yes, we will include it in the next release. We haven't had a Desktop release since that release of compose.
