### ISSUE TITLE
The Mac with M1 chip using the preview vision Docker sometimes cannot build an image 

### ISSUE THREAD

**Issue by Kouseki0115** [docker/for-mac#5362]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
build an image on Docker
### Actual behavior
executor failed running [/bin/sh -c yarn install --production]: exit code: 1
<img width="1080" alt="スクリーンショット 2021-02-18 8 21 15" src="https://user-images.githubusercontent.com/78832924/108282403-e554ca00-71c4-11eb-8f72-a7e1a2f1e74c.png">
<img width="1080" alt="スクリーンショット 2021-02-18 8 21 15" src="https://user-images.githubusercontent.com/78832924/108282438-f56ca980-71c4-11eb-91e4-a0c410460916.png">

### Information

  - macOS Version: Mac OS Big Sur 11.1
  - Docker Desktop Version: Preview v20.10.3

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
I don't think this is a Docker bug, it looks like one of the commands in your Dockerfile fails on the arm64 architecture.

**Comment by Kouseki0115** [comment]
> I don't think this is a Docker bug, it looks like one of the commands in your Dockerfile fails on the arm64 architecture.

Thank you for your help!

**Comment by cclauss** [comment]
Can this issue be closed?
