### ISSUE TITLE
Unable to locate package (msodbcsql17 and mssql-tools)

### ISSUE THREAD

**Issue by felipe-novaes** [docker/for-mac#5365]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BBB9D7F3-6F6A-43EE-8C43-667042B9013A/20210218231857
 
### Information
 Building it with "docker-compose up"

[Dockerfile.txt](https://github.com/docker/for-mac/files/6006532/Dockerfile.txt)

  - macOS Version: Big Sur 11.2.1 (20D74)
  - Docker Desktop Version: Docker Preview Apple Silicon

### Steps to reproduce the behavior
 Building it with "docker-compose up"

  1. ...
  2. ...
 
[Dockerfile.txt](https://github.com/docker/for-mac/files/6006534/Dockerfile.txt)

**Comment by shaggyrec** [comment]
+1

**Comment by mcandylab** [comment]
+1

**Comment by ikahitin** [comment]
+1
