### ISSUE TITLE
docker suddenly stops working

### ISSUE THREAD

**Issue by jimmysoho** [docker/for-mac#537]
Getting ERROR: Bad response from Docker engine

$ docker ps
Error response from daemon: Bad response from Docker engine

### Information

Diagnostic ID: 77B0E183-2AD7-4EA1-92C8-EDDEA9309401
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.3 (Build 14D136)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by mchiang0610** [comment]
Closing this one in favor of #536
