### ISSUE TITLE
“Docker” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by renodesper** [docker/for-mac#5370]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker should be copied successfully into Applications.

### Actual behavior

There is a warning that asks me to move it to Trash.

```
“Docker” is damaged and can’t be opened. You should move it to the Trash.
```

### Information

  - Is it reproducible? Yes, in my machine. I don't have any other machine.
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - macOS Version: 11.2.1 (20D74)
  - Docker Desktop Version: 3.1.0 (60984)

### Steps to reproduce the behavior

  1. Download the latest Docker Preview for M1 from this URL: https://docs.docker.com/docker-for-mac/apple-m1
  2. Open the DMG file and move the Docker app into the Applications folder

**Comment by schniper** [comment]
Is it possible you tried opening it before copying was done? I think that happened to me - I thought it was finished, but it wasn’t. And after that it kept issuing that error.
I opened the dmg again, let it finish copying and then it was ok.

**Comment by tatsuya6502** [comment]
I had the same problem with the latest Docker Preview for M1 yesterday (about 20 hours ago). But I don't have the problem anymore today. Docker was copied successfully into Applications and can be launched.

On yesterday, the message started to appear while copying Docker into Applications, and kept popping up until I press the button to trash it. Then I restarted my Mac and tried it again but the message still appeared. I had old Docker preview (Preview 7) installed and running before, and I quit it and trashed it before I started to copy the new one.

The error means that macOS cannot verify the signature of Docker app. I guess macOS has to connect Apple's server to do it? but it couldn't by a temporal network error or something?

Anyway, it would be worth to try to copy again after a day or so.

----
- Mac mini (M1, 2020)
- macOS Version: 11.2.1 (20D74)
- Docker Desktop Version: 3.1.0 (60984)

**Comment by dirathea** [comment]
I just encounter the same issue right now. When I copy the binary, the popup is shown and even I keep cancel it and wait until the copy process is done, the popup still coming. After that, I move the docker app to the trash, restart, and copy it again. Now it working normally.

I think to update docker preview, you can't replace the binary as it is. You need to remove it first then copy the binary to the Applications folder.

**Comment by renodesper** [comment]
I think what all of you said is right. After I restart the device and try to move the Docker into the Applications, the notification did not show up anymore. It looks like something was left behind even though I already stop and remove the old Docker desktop. Thank you very much for the info.

**Comment by kevinold** [comment]
I ran into this issue and restarting my Mac *after* stopping and uninstalling Docker Desktop Preview 7 fixed the issue and allowed me to install Docker Desktop Version: 3.1.0 (60984) without issue.
