### ISSUE TITLE
Docker desktop is not starting up.

### ISSUE THREAD

**Issue by ritesh277coe** [docker/for-mac#5371]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E8FE3425-3C32-4464-B3F8-5A9B2EDFD860/20210219165735

### Information

  - macOS Version: Catalina 10.15.7 (19H524)
  - Docker Desktop Version: Docker version 20.10.2, build 2291f61

### Steps to reproduce the behavior

  1. Click on Docker icon in Applications folder
  2. Docker desktop never gets ready.
NOTE: It use to work, but after an update, it stopped working. I have uninstalled and reinstalled 2/3 times, but it did not help.

**Comment by adi13** [comment]
I am having the exact same issue after upgrading my Mac OSX. 
System Information :
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
```
Docker Information
- Docker Desktop Version :  3.1.0 (51484)
- Docker Engine :           20.10.2
- API version :       1.41
-  Git commit :        2291f61

**Comment by ritesh277coe** [comment]
Thanks @adi13 

The solution that you gave did the trick.

**Comment by ritesh277coe** [comment]
The solution provided by @adi13 fixed the issue.
