### ISSUE TITLE
Docker for macbook air M1

### ISSUE THREAD

**Issue by fabiooshiro** [docker/for-mac#5375]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4C8912F8-977D-4BFC-8944-D332546CF116/20210221192236

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Download https://docs.docker.com/docker-for-mac/apple-m1/
  2. Install and try to use

**Comment by stephen-turner** [comment]
Could you please describe what problem you encountered?

**Comment by fabiooshiro** [comment]
I just install the preview version and when I tried to run I got this error
![image](https://user-images.githubusercontent.com/218768/108926974-31b56500-761e-11eb-82f0-965d4567a077.png)

**Comment by fabiooshiro** [comment]
Wow, I clicked "Reset Docker to factory defaults" and now it is seems to be working!

Thx

**Comment by fabiooshiro** [comment]
Maybe its was some old configuration, because I tried the "normal" version before this "preview" version.
