### ISSUE TITLE
DockerFile - "RUN apk add syslog-ng" giving error while docker build - M1 preview version

### ISSUE THREAD

**Issue by nyIdeas** [docker/for-mac#5379]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Install syslog-ng in the container image

### Actual behavior
Throwing error :
 > [ 6/18] RUN apk add syslog-ng:
#9 1.044 ERROR: unsatisfiable constraints:
#9 1.044   syslog-ng (missing):
#9 1.048     required by: world[syslog-ng]

### Information

  - macOS Version: 11.2.1 - Big Sur
  - Docker Desktop Version: Docker version 20.10.3, build 48d30b5 - M1 preview

### Steps to reproduce the behavior

  1. Run Docker build command with Dockerfile containing line "RUN apk add syslog-ng"
  2. ...

**Comment by stephen-turner** [comment]
This doesn't look like a Docker bug. It looks like apk can't find the right package. Maybe it's not available for arm64 or something?

**Comment by nyIdeas** [comment]
Thanks @stephen-turner for the response. Do you know where should I raise this to ? I was successfully running all local developments before with Docker for Mac(Normal one, for the intel processor mac), until I upgraded my system to latest M1 chip  and had to download the Docker Preview Version for M1 chip Macs.

**Comment by stephen-turner** [comment]
Ask for advice on the Alpine forums maybe?
