### ISSUE TITLE
Docker PS unresponsive.

### ISSUE THREAD

**Issue by satinjeet** [docker/for-mac#538]
### Information

Diagnostic ID: 8580B88D-67C4-47B4-8458-0E8AA4A1593F
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

I am not sure how this happened. We saw different behaviours when 
1. Mac was updated to latest security patch 2016-116
2. In my case , there was no update. but the docker says updated to 1.12.0-a

common thing in both scenario, macbooks were restarted.

**Comment by satinjeet** [comment]
reverting back to docker beta for now. `Docker version 1.12.1, build 23cf638, experimental`

**Comment by mchiang0610** [comment]
@satinjeet assuming this is fixed in the latest beta?   If so, it'll trickle to stable soon. 

Closing for now. Let me know if I should reopen
