### ISSUE TITLE
Unable to Install Docker Desktop preview 3.1.0

### ISSUE THREAD

**Issue by seawolf42** [docker/for-mac#5380]
- [x] I have tried with the latest version of Docker Desktop
  - N/A: unable to start application (I have tried disabling enabled experimental features)
  - N/A: unable to start application (I have uploaded Diagnostics)
  - Diagnostics ID: N/A

### Expected behavior
Dragging Docker Preview from DMG to Applications folder succeeds

### Actual behavior
I receive a warning that there is a problem with the package and ultimately the installation hangs:
<img width="738" alt="Screen Shot 2021-02-22 at 07 13 48" src="https://user-images.githubusercontent.com/2721922/108745112-ce70e900-74de-11eb-8853-90c202286682.png">

If I click "Move to Trash" after the warning, the cancellation succeeds but an additional dialog comes up mentioning invalid filenames:
<img width="731" alt="Screen Shot 2021-02-22 at 07 14 51" src="https://user-images.githubusercontent.com/2721922/108745137-d4ff6080-74de-11eb-9b4a-039da3281f92.png">

### Information

  - macOS Version: 11.2.1
  - Docker Desktop Version: 3.1.0 preview

### Steps to reproduce the behavior

  1. Navigate to https://docs.docker.com/docker-for-mac/apple-m1/ and click "Download"
  2. Double-click the downloaded `.dmg` file
  3. Drag the Docker application to the Applications folder show in the open window

**Comment by seawolf42** [comment]
Update: this only appears to happen if the previous preview was already installed and has been used since login. I can successfully unpack the .dmg to a different name. If I then disable auto-start on login and then log out, I can log back in, delete the old version, rename the new one, and it now appears to work. Quitting the previous version was not sufficient to complete the process, it had to be deleted before I could continue.

**Comment by achimnol** [comment]
This happened to me as well and I also succeeded to install and run it after deleting the app and re-login.
Thanks!

**Comment by achimnol** [comment]
I got stuck again and this time it was the issue #5369. Disabling the firewall made it working.

**Comment by seawolf42** [comment]
This went away with an update a while ago, forgot to close the issue.
