### ISSUE TITLE
Docker stuck in "Docker Desktop is starting"

### ISSUE THREAD

**Issue by gabrielarules** [docker/for-mac#5382]
- [ X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: 8D89D52F-FC25-4DE8-A451-43CBC310B79E/20210222220114

### Expected behavior
start docker
### Actual behavior
stuck in starting
### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior
Just by opening docker, it gets stuck in docker is starting....

Diagnostics:
time="2021-02-22T17:01:15-05:00" level=info msg="Triggering Linux sysrq via a unix socket: diagnosticd.sock" type=unixsock
time="2021-02-22T17:01:31-05:00" level=info msg="Start gathering list of 86 elements (timeout=15m0s)" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering DiagKit" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering BackendGatherer" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering system" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sw_vers -productVersion]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sw_vers -buildVersion]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [uname -r]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sysctl kern.boottime]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sysctl hw.memsize]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [vm_stat]"
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sysctl machdep.cpu]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering uname -a" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [uname -a]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering ps uax" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [ps uax]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering dmesg " type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [dmesg]"
time="2021-02-22T17:01:31-05:00" level=warning msg="[dmesg] exit status 1" type=cmd
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering id " type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [id]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering sysctl -a" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [sysctl -a]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering mount " type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [mount]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering df -h" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [df -h]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering launchctl print-disabled  (timeout 0s)system" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [launchctl print-disabled system]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering system_profiler SPHardwareDataType" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [system_profiler SPHardwareDataType]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering defaults read  (timeout 0s)/Library/Preferences/com.apple.alf.plist" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering ifconfig -a" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [ifconfig -a]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering netstat -ln" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [netstat -ln]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering netstat -mm" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [netstat -mm]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering netstat -nr" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [netstat -nr]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering /etc/resolv.conf" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering /etc/hosts" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering: /etc/hosts" type=file
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering scutil --dns" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [scutil --dns]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering scutil --nc  (timeout 0s)list" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [scutil --nc list]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering scutil --proxy  (timeout 0s)list" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [scutil --proxy list]"
time="2021-02-22T17:01:31-05:00" level=info msg="Gathering system_profiler SPFirewallDataType" type=list
time="2021-02-22T17:01:31-05:00" level=info msg="Executing: [system_profiler SPFirewallDataType]"
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/version" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/info" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/containers/json?all=1" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/nodes" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/services" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering HTTP GET localhost /v1.24/networks" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering {\n  \"id\": \"8D89D52F-FC25-4DE8-A451-43CBC310B79E\",\n  \"date\": \"2021-02-22 22:01:15.200757 +0000 UTC\"\n}\n" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe pods" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe daemonset" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe replicaset" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe deployments" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe pods" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe daemonset" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe replicaset" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe deployments" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering VPNKit" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering log/vm/**" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm" type=directory
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/containerd.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/diagnose.out.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/docker.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/docker.out.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/host-timesync-daemon.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/kmsg.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/lifecycle-server.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/lifecycle-server.out.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/memlogd.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.003-format.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.004-extend.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.006-metadata.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.007-swap.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.007-swap.out.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.008-mount-docker.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/onboot.009-bridge.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/rpc.statd.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/sntpc.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/socks.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/trim-after-delete.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/vm/vpnkit-forwarder.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering log/host/**" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host" type=directory
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host/Docker.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host/com.docker.backend.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Skipping empty file: log/host/com.docker.diagnose.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host/com.docker.driver.amd64-linux.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host/com.docker.supervisor.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Skipping empty file: log/host/docker-credential-desktop.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering: log/host/vpnkit-bridge.log" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering /Library/Application Support/Docker/DockerDesktop/admin-settings.json" type=list
time="2021-02-22T17:01:32-05:00" level=warning msg="/Library/Application Support/Docker/DockerDesktop/admin-settings.json not included" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/features-overrides.json" type=list
time="2021-02-22T17:01:32-05:00" level=warning msg="/Users/gabriela/Library/Group Containers/group.com.docker/features-overrides.json not included" type=file
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/docker_subscription.lic" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering /Library/Application Support/Docker/DockerDesktop/docker_subscription.lic" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  version " type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  config get-contexts" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  config current-context" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  get nodes" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  get namespaces" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe nodes" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe pods" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  cluster-info dump" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe services" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe storageclass,pv,pvc" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="kubernetes is disabled" type=kubectl
time="2021-02-22T17:01:32-05:00" level=info msg="Gathering log process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")" type=list
time="2021-02-22T17:01:32-05:00" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']"
time="2021-02-22T17:01:47-05:00" level=warning msg="[/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")'] signal: killed" type=cmd
time="2021-02-22T17:01:47-05:00" level=warning msg="[/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")'] (timeout: 15s) -> context deadline exceeded"
time="2021-02-22T17:01:47-05:00" level=info msg="Gathering DarwinSyslog Sender = docker Docker Message = docker Docker" type=list
time="2021-02-22T17:01:47-05:00" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.hyperkit) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.osxfs) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.supervisor) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.supervisor)]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.vpnkit) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]"
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.vmnetd) (timeout 0s)" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)]"
time="2021-02-22T17:01:48-05:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vmnetd)] exit status 1" type=cmd
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering vms/0/console-ring" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering: vms/0/console-ring" type=file
time="2021-02-22T17:01:48-05:00" level=info msg="Gathering osxfsGatherer" type=list
time="2021-02-22T17:01:48-05:00" level=info msg="Connecting to com.docker.osxfs"
time="2021-02-22T17:01:48-05:00" level=info msg="Querying com.docker.osxfs ExportState"
time="2021-02-22T17:01:49-05:00" level=info msg="Querying com.docker.osxfs MountState"
time="2021-02-22T17:01:49-05:00" level=info msg="Gathering ls -l  (timeout 0s)/Users/gabriela/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw" type=list
time="2021-02-22T17:01:49-05:00" level=info msg="Executing: [ls -l /Users/gabriela/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw]"
time="2021-02-22T17:01:49-05:00" level=info msg="Gathering /tmp/hyperkit-spindump.txt" type=list
time="2021-02-22T17:01:49-05:00" level=info msg="Gathering: /tmp/hyperkit-spindump.txt" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Logs/Docker Desktop/**" type=list
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Logs/Docker Desktop" type=directory
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Logs/Docker Desktop/log.log" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Logs/Docker Desktop/log.old.log" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Logs/Docker Desktop/main.log" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=list
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/already-enabled-features.json" type=list
time="2021-02-22T17:01:50-05:00" level=warning msg="/Users/gabriela/Library/Group Containers/group.com.docker/already-enabled-features.json not included" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/dhcp.json" type=list
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Group Containers/group.com.docker/dhcp.json" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/features.json" type=list
time="2021-02-22T17:01:50-05:00" level=warning msg="/Users/gabriela/Library/Group Containers/group.com.docker/features.json not included" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/http_proxy.json" type=list
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Group Containers/group.com.docker/http_proxy.json" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Group Containers/group.com.docker/settings.json" type=list
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering: /Users/gabriela/Library/Group Containers/group.com.docker/settings.json" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering /Users/gabriela/Library/Preferences/group.com.docker.plist" type=list
time="2021-02-22T17:01:50-05:00" level=warning msg="/Users/gabriela/Library/Preferences/group.com.docker.plist not included" type=file
time="2021-02-22T17:01:50-05:00" level=info msg="Gathering ls /Users/gabriela/.docker /usr/local/bin /Library/PrivilegedHelperTools /Library/LaunchDaemons /Users/gabriela/Library/LaunchAgents /Library/Application Support/Docker/DockerDesktop /Users/gabriela/Library/Group Containers/group.com.docker /Users/gabriela/Library/Containers/com.docker.docker /Applications/Docker.app" type=list
time="2021-02-22T17:01:50-05:00" level=warning msg="exit status 1" type=directorylist
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering Redacted /Users/gabriela/.docker/config.json" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering: /Users/gabriela/.docker/config.json" type=redacted-json
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering Redacted /Users/gabriela/.docker/daemon.json" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering: /Users/gabriela/.docker/daemon.json" type=redacted-json
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering HTTP GET localhost /fuse/time" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="HTTP GET: localhost /fuse/time" type=http
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering HTTP GET localhost /fuse/count" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="HTTP GET: localhost /fuse/count" type=http
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering HTTP GET localhost /fuse/filename" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="HTTP GET: localhost /fuse/filename" type=http
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering HTTP GET localhost /fuse/calls" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="HTTP GET: localhost /fuse/calls" type=http
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering fuseVolumeGatherer" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering fuseStacksGatherer" type=list
time="2021-02-22T17:01:51-05:00" level=info msg="Gathering mutagenGatherer" type=list
time="2021-02-22T17:01:56-05:00" level=info msg="Gathering diagnosticd.sock" type=list
time="2021-02-22T17:01:56-05:00" level=info msg="Getting Linux Diagnostics via a unix socket: diagnosticd.sock" type=unixsock
time="2021-02-22T17:02:26-05:00" level=warning msg="/diagnostics failed: Get \"http://unix/diagnostics\": context deadline exceeded" type=unixsock
time="2021-02-22T17:02:26-05:00" level=info msg="All 86 gatherers finished" type=list

**Comment by daniel-xiao** [comment]
Going to just +1 that I'm having the same issue. 

I'm on a MacBook Air with Apple's M1 chip using Big Sur v11.2

**Comment by munishpathania** [comment]
I am also having the same issue with macOS catalina v10.15.7.  Docker desktop version 3.10(51484)

**Comment by gabrielarules** [comment]
I think I may have resolved my issue. It seems it was something to do with Macfee. I disabled the firewall and things started to work.

**Comment by ryuhhnn** [comment]
I was able to resolve this by turning off the VPN I was using and restoring to factory default settings.

**Comment by klement** [comment]
I see this same issue with MacOS firewall enabled. If I disable it, docker will start and will work even if I immediately re-enable the firewall.

**Comment by daniel-xiao** [comment]
Disabling firewall indeed worked for me, as well as reenabling it afterwards!

**Comment by pires** [comment]
> Disabling firewall indeed worked for me, as well as reenabling it afterwards!

Same here.

**Comment by guycalledseven** [comment]
Running Docker 3.2.0(61504) on macOS Catalina v10.15.7., i7 MBP
I experienced this after upgrade to 3.2.0.
I have macOS firewall disabled.

Only manual remove & reinstall helped.
When I change settings in Resources / File sharing I can get it to the same broken state every time.

**Comment by thecosmicfrog** [comment]
Docker for Mac M1 Preview won't start for me when Cisco AnyConnect is connected to VPN. Disabling firewall doesn't work for me, unfortunately.
