### ISSUE TITLE
Docker-compose unrecognized option `--profile' on MacOs 11

### ISSUE THREAD

**Issue by weldpua2008** [docker/for-mac#5384]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features

### Expected behavior

```shell
$ docker-compose 2>&1 |grep  --profile 
 --profile NAME              Specify a profile to enable
``` 

### Actual behavior
```shell
$ docker-compose 2>&1 |grep  --profile 
grep: unrecognized option `--profile'
``` 
### Information
According to https://docs.docker.com/compose/profiles/ it should work
  - macOS Version: MacOs Big Sur 11.2.1 (20D74)
  - Docker Desktop Version: Docker 3.1.0 
  - Docker Engine v20.10.2

### Steps to reproduce the behavior

  1. Install via https://desktop.docker.com/mac/stable/Docker.dmg from https://docs.docker.com/docker-for-mac/release-notes/

**Comment by stephen-turner** [comment]
Profiles were only introduced in Compose 1.28. Docker Desktop hasn't had a release since 1.28 was released, so we are still at 1.27.
