### ISSUE TITLE
failed to start mssql container

### ISSUE THREAD

**Issue by aroon0808** [docker/for-mac#5385]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
running container without issues

### Actual behavior
stopped container with 'exited(1)'
logs: 
```This program has encountered a fatal error and cannot continue running.

The following diagnostic information is available:


Reason: 0x00000003

Message: result == 0

Stacktrace: 00000040000573fe 0000004000056f90 0000004000036d81

00000040000377af 000000400004cc51 00000040000295df

000000400490d830 00000040000269a9

Process: 10 - sqlservr

Thread: 10

dmesg: read kernel buffer failed: Operation not permitted

No journal files were found.

No journal files were found.

Attempting to capture a dump with paldumper

WARNING: Capture attempt failure detected

Attempting to capture a filtered dump with paldumper
```

  - macOS Version: big sur 11.2.1
  - Docker Desktop Version:  newest preview

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Is this an amd64 container instead of an arm64 container? If so, I suspect it's a qemu bug, as described in our documentation.

**Comment by aroon0808** [comment]
I suspect it is, but this is a ready-made container that I get to work. Will it ever be possible to launch such a container on M1?

**Comment by stephen-turner** [comment]
If qemu can't run it, unfortunately probably not. We don't write any of that code, we just bundle it.

In general we recommend people to use arm64 containers, which will have much better performance too. Now that ARM is a mainstream platform, we expect most container authors will be keen to produce arm64 versions of their images.
