### ISSUE TITLE
Icon is not a rounded-rectangle shape

### ISSUE THREAD

**Issue by armandgrillet** [docker/for-mac#5386]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

According to the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/), "app icons share a common set of visual attributes, including the rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow". These guidelines should be followed for all macOS apps, as we can see in [other issues opened for other developer tools such as VS Code](https://github.com/microsoft/vscode/issues/101014#issuecomment-754822102).

### Actual behavior

The Docker for Mac icon follows outdated [macOS Human Interface Guidelines](https://web.archive.org/web/20190308121320/https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/): "If necessary, you can use a circular shape to encapsulate a set of images. Avoid using the rounded rectangle shape that people associate with iOS app icons.". Those were fine with macOS 10 but do not follow the guidelines since macOS 11.

### Information

  - macOS Version: any, the icon is not version-dependent.
  - Docker Desktop Version: 3.1.0 (51484)

### Steps to reproduce the behavior

  1. Download the app and open it.

**Comment by stephen-turner** [comment]
Noted, but low priority.
