### ISSUE TITLE
com-docker-hyperkit was consuming large amounts of CPU

### ISSUE THREAD

**Issue by ae6rt** [docker/for-mac#539]
### Expected behavior

For com-docker-hyperkit not to consume large amounts of CPU.

### Information

The problem occurred when I closed the lid on my Macbook, then reopened it some time later.

My solution:  stop Docker for Mac and restart.

Diagnostic ID: 9AC91E61-EF51-428E-A215-5A73438019D4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1912)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
merging with #82
