### ISSUE TITLE
host_mnt volume mount problem on Mac in the latest version  with has reappeared

### ISSUE THREAD

**Issue by zycgit** [docker/for-mac#5390]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When using a docker-compose file with named volume, a volume gets created with the path specified

### Actual behavior

output error log
```
ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/host_mnt/Users/yongchun.zyc/nginx/nginx.conf" to rootfs at "/var/lib/docker/overlay2/0003a18e2de648cc5c41b0547b4bf932c57960894408ffebde0fc3f07e8395de/merged/etc/nginx/nginx.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

### Information

This problem looks same to  https://github.com/docker/for-mac/issues/4859 , 
but appears in the latest version of docker-for-Mac

  - macOS Version:  11.2.1
  - Docker Desktop Version: 3.1.0(51484)

![image](https://user-images.githubusercontent.com/4951471/109010228-7eff0880-76ea-11eb-9511-00ce0b76413a.png)

`Output of docker version`

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`Output of docker-compose version`

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

### Steps to reproduce the behavior

`docker-compose.yml`

```
version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8088:80
    restart: always
    volumes:
      - $PWD/html/:/usr/share/nginx/html
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/logs/:/var/log/nginx
```

run command docker-compose up.
[codes.zip](https://github.com/docker/for-mac/files/6036418/codes.zip)

**Comment by zycgit** [comment]
Does anyone know how to solve this problem?

**Comment by kennyparsons** [comment]
@zycgit change the docker settings to use osxfs, instead of gRPC Fuse. 
<img width="1050" alt="Screen Shot 2021-04-20 at 8 53 31 AM" src="https://user-images.githubusercontent.com/5930491/115407813-fbc3d580-a1b5-11eb-93b1-547c3b8f419f.png">
