### ISSUE TITLE
M1 Mac Big Sur 'does not have a Release file' error upon building docker image

### ISSUE THREAD

**Issue by rshamsy** [docker/for-mac#5395]
- [x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Created a Dockerfile for a Flask application and ran 
`docker build -t flask-app .` 

Expected the image to build. Here's a snippet of the Dockerfile:
"""

> FROM ubuntu:18.04
> 
> EXPOSE 5000
> 
> ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
> 
> ENV DEBIAN_FRONTEND=noninteractive
> 
> 
> RUN apt-get update && apt-get -y --no-install-recommends install \
> 		ca-certificates \
> 		git \
> 		ssh \
>     	wget && \
> 	apt-get clean && \
> 	apt-get autoremove && \
> 	rm -rf /var/lib/apt/lists/*
> ...

"""

### Actual behavior
Get "Release File Missing" errors when running `apt-get update`

Here's the full error message:
"""

> => ERROR [ 3/11] RUN apt-get update && apt-get -y --no-install-recommends install   ca-certificates   git   ssh   wget &&  apt-get clean &&  apt-get  1.9s
> ------                                                                                                                                                      
>  > [ 3/11] RUN apt-get update && apt-get -y --no-install-recommends install             ca-certificates                 git             ssh             wget &&     apt-get clean &&        apt-get autoremove &&   rm -rf /var/lib/apt/lists/*:                                                                        
> #7 1.037 Ign:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                                                                                        
> #7 1.088 Ign:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                                                                                
> #7 1.138 Ign:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease                                                                              
> #7 1.191 Ign:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
> #7 1.243 Err:5 http://ports.ubuntu.com/ubuntu-ports bionic Release
> #7 1.243   404  Not Found [IP: 91.189.88.152 80]
> #7 1.294 Err:6 http://ports.ubuntu.com/ubuntu-ports bionic-updates Release
> #7 1.294   404  Not Found [IP: 91.189.88.152 80]
> #7 1.373 Err:7 http://ports.ubuntu.com/ubuntu-ports bionic-backports Release
> #7 1.373   404  Not Found [IP: 91.189.88.152 80]
> #7 1.479 Err:8 http://ports.ubuntu.com/ubuntu-ports bionic-security Release
> #7 1.479   404  Not Found [IP: 91.189.88.152 80]
> #7 1.486 Reading package lists...
> #7 1.502 E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic Release' does not have a Release file.
> #7 1.502 E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-updates Release' does not have a Release file.
> #7 1.502 E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-backports Release' does not have a Release file.
> #7 1.502 E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-security Release' does not have a Release file.
> ------
> executor failed running [/bin/sh -c apt-get update && apt-get -y --no-install-recommends install                ca-certificates                 git        ssh              wget &&         apt-get clean &&        apt-get autoremove &&   rm -rf /var/lib/apt/lists/*]: exit code: 100

"""

I build one of my collaborator's images and I get the same error at the same line (apt-get update) – it works for him. So I suspect this is a mac version issue. 

Looked at bug reports elsewhere and the only other suggestion is to restart Docker Desktop to re-align the clock, and that also doesn't work. 

### Information

  - macOS Version: Big Sur 11.1
  - Docker Desktop Version: Preview for Silicon Chip Mac

### Steps to reproduce the behavior
  1. ...
  2. ...

**Comment by stephen-turner** [comment]
I don't think this is a Docker bug. Maybe the package repository doesn't have any packages for arm64 architecture or something?
