### ISSUE TITLE
Docker on m1 causes com.apple.Virtualization.VirtualMachine process to run at 100% CPU all the time

### ISSUE THREAD

**Issue by gothy** [docker/for-mac#5397]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Not sure if it's expected or not.

### Actual behavior

Process com.apple.Virtualization.VirtualMachine runs at 100% CPU all the time when Docker daemon is up.

### Information

  - macOS Version: 11.2.2
  - Docker Desktop Version: 3.1.0 (60984)

### Steps to reproduce the behavior

I'm using the latest preview version for M1 macs from [this post](https://www.docker.com/blog/new-docker-desktop-preview-for-apple-m1-released/).

**Comment by BatuhanK** [comment]
Same issue, but for me it's not start with %100 cpu. After 10-15 minutes of running it spikes up to %100 and stays around 99-100

**Comment by diogo-redstage** [comment]
The same issue is happening for me as well!

**Comment by Cyclic** [comment]
Seeing the same issue here, but on an Intel Core i5 Mac mini
![image](https://user-images.githubusercontent.com/553800/113640045-6e1dad00-962f-11eb-95f7-211b44992e29.png)

![image](https://user-images.githubusercontent.com/553800/113640064-7a096f00-962f-11eb-8ac2-ddf162a8b47b.png)

**Comment by bitsvital** [comment]
I'm having the same issue too.

**Comment by yordis** [comment]
<img width="234" alt="Screen Shot 2021-07-11 at 3 57 04 PM" src="https://user-images.githubusercontent.com/4237280/125208475-a3eeb500-e260-11eb-956f-0db5dd7a1fca.png">

### Note

Make sure to disable the new virtualization framework

<img width="1270" alt="Screen Shot 2021-07-11 at 3 56 46 PM" src="https://user-images.githubusercontent.com/4237280/125208470-99ccb680-e260-11eb-9fa5-dee4f37b01ef.png">

**Comment by chriscasola** [comment]
Seeing this issue as well.

![image](https://user-images.githubusercontent.com/2282012/129572730-bf814050-25e7-439c-bb11-5157023b532a.png)

**Comment by amjad1233** [comment]
Same issue.
![CleanShot 2021-08-30 at 13 35 45](https://user-images.githubusercontent.com/661146/131281577-9e0dd9f7-4a69-4624-a3a7-0cf4c19c1d58.png)

**Comment by asko** [comment]
Same here.
Diagnostics ID `2200E977-2352-4DE6-BB3A-E55079875856/20210913175522`
![Screenshot 2021-09-13 at 20 56 46](https://user-images.githubusercontent.com/17984167/133133188-d1661ce3-7ea5-4572-95ae-748fd3dd9c7b.png)

**Comment by ConflictingTheories** [comment]
I am getting this issue on M1 too, spiking up to 350% at times when running a workload on the containers. 

![Screen Shot 2021-09-14 at 3 14 46 PM](https://user-images.githubusercontent.com/7156223/133335008-6bff4e33-8c5d-4d9d-ae46-cae2ed41aa83.png)

![Screen Shot 2021-09-14 at 3 16 28 PM](https://user-images.githubusercontent.com/7156223/133335108-461687a7-ec35-4ae0-9c7b-de8e475a4696.png)

**Comment by erosenberg** [comment]
This is also happening for me.

<img width="1037" alt="Screen Shot 2021-09-15 at 3 20 38 PM" src="https://user-images.githubusercontent.com/906133/133496472-61d6278f-48ea-44f3-8db5-8b24c425b54c.png">

**System**
Processor: 2.4 GHz 8-Core Intel Core i9
Memory: 64 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB

**Comment by tamtamchik** [comment]
Same issue.

**System**
Processor: 2,3 GHz 8-Core Intel Core i9
Memory: 64 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5500M 4 GB, Intel UHD Graphics 630 1536 MB
Operating System: macOS Big Sur 11.6

Disabling the new virtualization framework as @yordis suggested did work and now everything is OK.

**Comment by staypufdresideo** [comment]
Same issue here.  No containers running. These screenshots are from right after I did a restart of Docker for Mac. It went right up above 200% CPU and as I type this it's at 300.8% CPU

![Screen Shot 2021-09-24 at 11 00 58 AM](https://user-images.githubusercontent.com/52760948/134706049-674e6389-c94f-4d55-97f0-fe8f580ad582.png)

![Screen Shot 2021-09-24 at 11 00 32 AM](https://user-images.githubusercontent.com/52760948/134706136-fecd929a-ba6f-4f10-ad0c-c4f9f2257709.png)

**Comment by retif** [comment]
i have the same issue on intel big sur macos

**Comment by hoover01** [comment]
BigSur - Intel i7 - same issue

**Comment by Jakeii** [comment]
Started getting this issue on Intel Mac after updating to Monterey

**Comment by kurt-mueller-osumc** [comment]
> Started getting this issue on Intel Mac after updating to Monterey, disabling "new Virtualization framework" fixed it.

Where is this in the system preferences? Thanks!

**Comment by Jakeii** [comment]
@kurt-mueller-osumc it's in the Docker preference
![Screenshot 2022-01-25 at 15 33 20](https://user-images.githubusercontent.com/1731150/151007499-c0479455-2651-43a9-940c-f8af4f8a6e96.png)
s

**Comment by pc-achang** [comment]
This worked for me! Thanks @Jakeii!

**Comment by allanzi** [comment]
+1 Just disable "new Virtualization framework" solved

**Comment by MiBiT-Discuss** [comment]
I'm not sure if this was the case last year, but for me the problem wasn't CPU usage. Rather it was memory usage. Disabling the Apple Virtualization framework starts qemu instead, which uses just as much memory. The best solution, likely for both is to make changes in Resources: Advanced. 

Again, I don't remember how much you could change this last year, but memory, cores, swap and disk image size can be set now.

**Comment by hsul4n** [comment]
Same issue here, I'm getting crash after 1-2 hours working with docker containers.

**Comment by ikegentz** [comment]
MacOS Ventura, with a 6 core i7.
w.r.t. CPU usage, it is pretty much totally maxed out during container builds, but does go back down with no containers running.

Memory however is always really high. Even with no containers running the `com.apple.Virtualization.VirtualMachine` process consumes a ridiculous amount of memory, typically hovering around 9G.

I can take the exact same code repo and build the same containers with Docker on a Linux box and never use more than 3G of RAM across the _entire system_. Similar with CPU usage, it's consistently a fraction of what I see on Mac.

Does anyone know what the `com.apple.Virtualization.VirtualMachine` process is actually doing? Why is it even there? Doesn't Docker just use `containerd`, or what is needing to be "Virtualized", especially on an Intel machine?

**Comment by dontcrash** [comment]
It's happening to me randomly, only happened once I saved settings from the resources page, I tried to allow six CPU cores instead of four, ever since then:

![image](https://user-images.githubusercontent.com/32660358/236695462-ada9ab89-d3f1-4937-bdf2-b3f6ba18c4d9.png)

**Comment by sirtawast** [comment]
Switching back to `gRPC FUSE` to disable the virtualization framework because CPU at 100% and keeps throttling and Docker containers are unresponsive.

Docker for Mac: 4.19.0 (106363). 
MacOs: Ventura 13.1, MBP (Intel) 15-inch, 2018

**Comment by SaudElabdullah** [comment]
The issue is back to me and my mac is suffering 
Macbook 16 m2 pro 16 GB
![Uploading Screenshot 2023-07-09 at 12.11.47 PM.png…]()

**Comment by yllekz** [comment]
Same. It's been especially bad in the most recent update where Docker Desktop fully crashes out.

**Comment by MiBiT-Discuss** [comment]
I'm now on DD 4.20.1 and see nothing like this bug on my M1 running macOS 13.4.1 (c). I notice that DD 4.21.1 promises "Performance improvements with faster startup and memory decrease". 

Could you people with this bug be more clear on what specific version you're using as well? 

I do wonder why I'm not having this issue.

**Comment by adsteel** [comment]
Still seeing this bug. My VM CPU usage spiked to 800%. M2, 16GB RAM, Sonoma 14.0.

**Comment by MiBiT-Discuss** [comment]
> Same. It's been especially bad in the most recent update where Docker Desktop fully crashes out.

Thanks for sharing your details @yllekz so others can use your info looking for the cause.

**Comment by sirtawast** [comment]
> Switching back to `gRPC FUSE` to disable the virtualization framework because CPU at 100% (all containers shut down) and keeps throttling. This starts to happen after some hours of use.
> 
> Docker for Mac: 4.19.0 (106363). MacOs: Ventura 13.1, MBP (Intel) 15-inch, 2018

Hi! Just a small update. I haven't experienced this issue since switching to `gRPC FUSE` without the new virtualization framework. My config is:

CPUs: 4 / 12
Memory: 12 / 32GB
Swap: 1 / 4 GB
Virtual disk: 208 / 608 GB

**Comment by zloyded** [comment]
+

**Comment by TiansuYu** [comment]
Experience the same issue trying to enable `VirtioFS` which will enable the virtualization framework 

> VirtioFS brings improved I/O performance for operations on bind mounts. Enabling VirtioFS will automatically enable Virtualization framework. Available in macOS 12.5 and above.

OS: M1, Ventura 13.6

**Comment by usamasaleem1** [comment]
Having same issue. Any fix?

**Comment by vhscom** [comment]
I'm seeing this on Sonoma Version 14.2.1 (23C71) but Docker Desktop isn't even running.

**Comment by vhscom** [comment]
Seeing this on macOS Sonoma Version 14.2.1 (23C71) starting today and don't even have Docker Desktop running.

**Comment by vhscom** [comment]
Seeing this on macOS Sonoma Version 14.2.1 (23C71) starting today and don't even have Docker Desktop running. It's heating up 2 of 10 cores on my machine like a free downgrade to a 8 core system.

**Comment by macrusso** [comment]
@sirtawast can you walk us through the solution by any chance on how to use `gRPC FUSE`

**Comment by sirtawast** [comment]
Sure thing @macrusso. In Docker Dashboard app, click the gear in top-right corner, select:

1. General > Choose file sharing implementation for your containers > gRPC FUSE
2. General > Use Virtualization framework (leave untoggled)
3. Apply & restart

![image](https://github.com/docker/for-mac/assets/5328394/eaa1d392-bf26-437a-9147-cfa4d3857b6e)

**Comment by LaseRobin** [comment]
No, it did not help, it still capped at 100% when running a container. I'm open to suggestions.

**Comment by sauravSDET** [comment]
Changing to GRPCfuse reduced my CPU usage, though use virtualization framework was checked and not enabled for chaning.

**Comment by sauravSDET** [comment]
using grpc Fuse reduced my CPU usage and also magically my anshooarora/klov:1.0.1 docker started running fine. Though for me use Virtuilazation checkbox was selected and not enabled for change.
<img width="1587" alt="image" src="https://github.com/docker/for-mac/assets/117361494/49185343-bb32-4c2c-96d5-a98cd3b2b9dd">

**Comment by rqueraud** [comment]
For anyone going into this again, I went into this issue recently, except that all the suggestions where not available in the different menus anymore (was using v4.33).
 I upgraded to the latest version (v4.36) and the problem disappeared.
