### ISSUE TITLE
Docker hangs

### ISSUE THREAD

**Issue by roy-work** [docker/for-mac#5399]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [?] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The following,
```
» docker run --rm ubuntu:bionic
```
Doesn't hang forever.

### Actual behavior
It just hangs.

### Information
The container get `Created`, but never seems to get beyond that:
```
» docker ps -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED              STATUS                      PORTS     NAMES
3ab2103e26c5   ubuntu:bionic          "/bin/bash"              About a minute ago   Created                               dreamy_borg
```

This seems like it might have started happening after Docker v3 (I'm on the latest version right now, 3.1.0, but I had to skip over v3.0 as it contained breaking bugs).

Whatever state Docker gets into, restarting it un-borks it.

  - macOS Version: 10.14.6
  - Docker Desktop Version: 3.1.0 (51484)

### Steps to reproduce the behavior
`docker run --rm ubuntu:bionic`, for me.

I suspect that whatever the underlying root cause here is, that it might be the same root cause of [this bug in `azcli`](https://github.com/Azure/azure-cli/issues/16312).

**Comment by shivknight** [comment]
Same behavior on the version 3.3.3, the latest at time of writing. Attempting to `docker start` containers stalled in this way causes `docker start` to hang.

**Comment by zhaozg** [comment]
Same behavior on the version 3.5.2.  Low probability occurs randomly
