### ISSUE TITLE
Cannot start docker on mac

### ISSUE THREAD

**Issue by rohit135** [docker/for-mac#54]
### Information

Diagnostic ID: CF19D7A1-DA4C-4D03-9EEC-15BE29E3D045
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Can you please provide more information?
- Expected behavior
- Actual behavior
- Steps to reproduce

And anything else which could help us identify your issue. Did the install process went smoothly? Did you see some error dialogs? I am closing the issue for now, but please re-open it when you will have a more precise description of your issue and of its context.

**Comment by rohit135** [comment]
Hi,
expected behavior: Docker starts.
Actual behavior: Docker is starting (stuck in loop)
Steps to reproduce: Not sure. I killed a process with the command lsof -i :5432 (not a bright idea) because the port was busy. and it terminated the docker process. after that even reinstalling docker doesn't help

**Comment by samoht** [comment]
Did it used to work at all at one point?

**Comment by rohit135** [comment]
Yes before i killed the process, everything was working fine. I am able to work again now by removing all docker related files form the computer and installing fresh. but doing so I lost all my images

**Comment by samoht** [comment]
Hum. That would be great if you can record what you did next time you have that issue. Closing the issue for now as you have "fixed" . Thanks for you report!
