### ISSUE TITLE
Support requests

### ISSUE THREAD

**Issue by Jeeeeeeeeee** [docker/for-mac#5404]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3383EC72-9ED7-49AB-9C83-F243BFE0B300/20210301090116

### Information

  - macOS Version: MacBook Pro (13-inch, M1, 2020)
  - Docker Desktop Version: 3.1.0 (60984)

Problem:
Docker desktop isn't starting

**Comment by hfinucane** [comment]
I'm seeing this too, on the same laptop. `vpnkit-bridge.log` is spamming
```
time="2021-03-01T09:19:52-08:00" level=info msg="prefix: GET /state 200 \"DockerDesktopGo\" \"\""
time="2021-03-01T09:19:53-08:00" level=info msg="prefix: GET /state 200 \"DockerDesktopGo\" \"\""
time="2021-03-01T09:19:54-08:00" level=info msg="prefix: GET /state 200 \"DockerDesktopGo\" \"\""
```
and `com.docker.backend.log` has
```
time="2021-03-01T09:20:20-08:00" level=info msg="still waiting for connection from VM after 8m22.304603s (state = &{%!s(int=0)  cb1e3884cdb24f004b94024990ae179b82836127dc33ad377cc106f616b9ad25 tcp+bootstrap+client://gateway.docker.internal:58663/cb1e3884cdb24f004b94024990ae179b82836127dc33ad377cc106f616b9ad25}, err = <nil>)"
```

Turning off the system firewall & zscaler, but neither seems to help- and it worked before?

I upgraded to Preview 7, and got no change.

72AEA4A0-52AA-4C8E-8CFE-737C1DD0AB35/20210301173108 is my diagnostics ID.
