### ISSUE TITLE
Does Docker Desktop Mac v3.2 natively support M1 Macs? 

### ISSUE THREAD

**Issue by cclauss** [docker/for-mac#5409]
I am currently using [Apple M1 Tech Preview](https://docs.docker.com/docker-for-mac/apple-m1) v3.1.0 (60984) with great success.  Now I see that Docker Desktop Mac v3.2.0 is available but its [release notes](https://docs.docker.com/docker-for-mac/release-notes) do not state if it natively supports M1 Macs.

Should I upgrade my M1 Mac to Docker Desktop Mac v3.2 or should I remain on the Apple M1 Tech Preview v3.1.0?

It would be useful if https://docs.docker.com/docker-for-mac/apple-m1 was updated to provide clear guidance on v3.2.0.

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
The M1 page is accurate: the tech preview linked there is still the latest. When we do fully release M1 support, you can be sure we won't be quiet about it. (Also, it will be a separate download from the Intel versionb).

**Comment by cclauss** [comment]
Thanks but https://docs.docker.com/docker-for-mac/release-notes says nothing about Intel-only.

**Comment by stephen-turner** [comment]
The system requirements say explicitly that it must be Intel https://docs.docker.com/docker-for-mac/install/

**Comment by cclauss** [comment]
Users can download directly from https://docs.docker.com/docker-for-mac/release-notes and that says nothing about Intel vs. M1.  I will remain on the preview which is working quite well for my needs.  Thanks.
