### ISSUE TITLE
docker info don't show anything(time out)

### ISSUE THREAD

**Issue by nv2908** [docker/for-mac#541]
### Information

Diagnostic ID: 4B11418C-6668-40DA-88D9-04EF36E593ED
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1808)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 4B11418C-6668-40DA-88D9-04EF36E593ED/20160908-001048.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.vmnetd][62644] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.vmnetd][62644] <Notice>: User 2108204619 has container folder /Users/verma.nitin/Library/Containers/com.docker.docker/Data/s60
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.vmnetd][62644] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.docker][62621] <Error>: Symlinks are not correctly installed.
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.docker][62621] <Notice>: com.docker.osx.hyperkit.linux launched with PID 62647
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.osx.hyperkit.linux][62647] <Notice>: Acquired task manager lock
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.osx.hyperkit.linux][62647] <Notice>: Maximum number of file descriptors is 10240
Sep  7 18:33:14 PW-C02L4A1HDR53.local Docker[com.docker.osx.hyperkit.linux][62647] <Notice>: Starting com.docker.db, com.docker.osxfs, com.docker.slirp, com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux
```
