### ISSUE TITLE
`docker login` segfaults when in a terminal session whose keychain is locked.

### ISSUE THREAD

**Issue by TkTech** [docker/for-mac#5411]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

`docker login` should fail gracefully with an error message, or better yet, prompt for keychain unlock.

### Actual behavior

```
$ docker login
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4675824]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x5d84640, 0xc000432a90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5ce8b01, 0xc0003f6060, 0xc00059f968)
        /go/src/github.com/docker/cli/cli/command/registry.go:128 +0x44
github.com/docker/cli/cli/command/registry.runLogin(0x5d84640, 0xc000432a90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x221
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc0005d6580, 0x6dc5120, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xca
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005d6580, 0xc0002dd550, 0x0, 0x0, 0xc0005d6580, 0xc0002dd550)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x460
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ffb80, 0xc0002dd550, 0x1, 0x1)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000432a90, 0x5ceb7c0, 0xc000010020)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d1
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf1
```

### Information

  - macOS Version: OS X 11.2 (Big Sur)
  - Docker Desktop Version: 20.10.3, build 48d30b5

When `docker login` can't talk to the keychain, it segfauls instead of failing gracefully with an error message or with an interactive keychain login.

**To get around this segfault,** explicitly unlock the keychain using `security unlock-keychain`, then try `docker login` again.

Note this only affects the Docker Desktop app.

### Steps to reproduce the behavior

`$HOME/.docker/config.json` has `"credsStore": "osxkeychain"` or `"credsStore": "desktop"`.

  1. security lock-keychain
  2. docker login
  3. :boom: 

This is most easily noticed when SSHing into a macbook running Docker Desktop, since the new user session will have its keychain locked by default.

**Comment by ligson** [comment]
security unlock-keychain
password to unlock default:
security: SecKeychainUnlock <NULL>: The user name or passphrase you entered is not correct.
