### ISSUE TITLE
Unidentifiable error message

### ISSUE THREAD

**Issue by trych** [docker/for-mac#5417]
For the past few weeks on system startup I encountered what must be the least helpful error message in my entire career as a computer user:

![20210304-000407_Screenshot_Finder](https://user-images.githubusercontent.com/9803905/109885558-fc90be80-7c7e-11eb-961e-a39eefd28438.png)

There is an update for what? There is *no* indication whatsoever what software this refers to, users are left completely clueless. I had to google now how to identify a window's source on macOS and had to use Xcode's Accessibility Inspector to find out that Docker was responsible for this window.

I fully understand that the most recent Docker version is not compatible with such an old OS, but *please* make sure to inform your users about it in a way that they can actually understand what is going on.

Edit: Oh, and all you can do on the window is click okay, which causes the window to pop up again the next time you reboot. Would be nice, if I can just get rid of the message altogether in case I want to keep using this older version of Docker. Oh, and also, there is always two exact copies of these window on top of each other. No idea why.

**Comment by stephen-turner** [comment]
Yes, we're aware of this, but unfortunately the bug is in the old version, which as it's installed software we can't do anything about now.
