### ISSUE TITLE
Apple m1 - can't build on a local 'base' image which is qemu based

### ISSUE THREAD

**Issue by 0gust1** [docker/for-mac#5419]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

We have a monorepo, with several programs built as docker images.

The programs all use a 'base' image that contains the necessary execution environment.  

The images are built with a specified user ~~(it may be the relevant part)~~.

**The build works fine on apple intel** (classic build OK, buildkit OK too)

### Actual behavior

On apple m1, it builds the base image and later fails to resolve the local base image.

```
 => ERROR [internal] load metadata for docker.io/library/base:tag          1.4s
------
 > [internal] load metadata for docker.io/library/base:tag:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 
````
~~**On apple m1, we tried to make a small dummy project replicating the characteristics (several programs, one base image), and the build works !**~~
~~The local base image resolves.~~ ~~The only difference I see so far, is that in this "dummy project", we don't make anything user related.~~

**The problem seem linked to the fact that if the base image is based on a amd64 only image, docker is not able to see it when trying to build the subsequent image.** 

### Information

  - Is the problem new? 
  No (had it since the start on apple m1, with our project)
  - Did the problem appear with an update?
  No
  - A reproducible case if this is a bug, Dockerfiles FTW. 
  Will try to isolate a minimal case (the "dummy project" told above was an attempt... but it worked unexpectedly )

  - macOS Version: 11.2.1
  - Docker Desktop Version: 3.1.0 (60984) - apple m1 preview

**Comment by 0gust1** [comment]
I may have found the reason between the 2 reported different behaviors on apple m1 (real project vs dummy project): the base image on "real project" is handled by QEMU (the initial FROM points to an image without arm64 support).

To test, I changed the FROM to a different image (from `mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice` to `python:buster`), and the error is gone. 

Although, it doesn't solve our problem :-/

**Comment by 0gust1** [comment]
For the record, the problem is very similar to the one described here : https://stackoverflow.com/questions/62593004/docker-buildx-cannot-pull-from-local-for-inherited-image

**Comment by 0gust1** [comment]
@stephen-turner, I did a test with the new preview version: problem still here.

Below, you'll find a minimal case to reproduce the problem.

[M1_dependent_local_images.zip](https://github.com/docker/for-mac/files/6212387/M1_dependent_local_images.zip)

**Comment by jonpacker** [comment]
I ran into this issue too. As a temporary fix in case anyone still needs to get their work done in this situation, is to force all your images to run under emulation by adding `--platform=linux/amd64` to the `FROM` instructions (i.e. `FROM my-base-image` -> `FROM --platform=linux/amd64 my-base-image` in all your Dockerfiles. After doing this, `docker build` found the right image and the builds succeeded as expected.

**Comment by stephen-turner** [comment]
In version 3.3.2, we are launching qemu with an additional argument that may help in some cases. We would be interested to know whether it has solved this problem.

However, note that qemu emulation should only ever be regarded as "best effort". Even when it works it will use more memory and have worse performance. The real solution is to run arm64 containers on M1 hardware.

I'm going to close this ticket now, because there's nothing further that we can do.

**Comment by 0gust1** [comment]
@stephen-turner :
I just tested using Docker 3.3.3 (64133) from yesterday, on the small minimal case I posted above (https://github.com/docker/for-mac/files/6212387/M1_dependent_local_images.zip)

- without specifying `--platform=linux/amd64` in all `FROM` in my dockerFiles, like jonpacker said, I still have the following error:
```
 => [internal] load build definition from Dockerfile.prog2                                                                             0.0s
 => => transferring dockerfile: 106B                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 2B                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/case-base2:latest                                                             1.3s
------
 > [internal] load metadata for docker.io/library/case-base2:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

- with adding `--platform=linux/amd64`, it builds.
