### ISSUE TITLE
Docker stuck on on starting

### ISSUE THREAD

**Issue by Singularity9971** [docker/for-mac#542]
### Expected behavior
Docker running normally
### Actual behavior
Docker is still trying to start since 15 minutes, was working normally then suddenly became unresponsive so I restarted it and now it's stuck on startup.
### Information

Diagnostic ID: 0A78DE46-0D35-4279-BF1F-6DE087FB851E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/avirudhtheraja/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/0A78DE46-0D35-4279-BF1F-6DE087FB851E/20160907-152817/qemu-img-check.stdout 2> /tmp/0A78DE46-0D35-4279-BF1F-6DE087FB851E/20160907-152817/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Download Docker for Mac and run

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed-hyperkit-50' in 0A78DE46-0D35-4279-BF1F-6DE087FB851E/20160907-152850.

There were a number of updates to the hypervisor transport system in the recently released Beta 27. If you are comfortable running a beta (we still do QA on it), you could give that a try and see if it stops the frequent crashing.

May be related to docker/hyperkit#50

The following log matches:
```
Sep  6 15:30:39 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: VM: 2016-09-03 08:09:29 +0000 UTC kern.info kernel: docker0: port 3(vethca6ee04) entered forwarding state
Sep  6 15:30:39 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: VM: 2016-09-03 08:09:29 +0000 UTC daemon.info vsudd: 83 Done. read: 208 written: 95
Sep  6 15:30:54 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: VM: 2016-09-03 08:09:44 +0000 UTC kern.info kernel: docker0: port 3(vethca6ee04) entered forwarding state
Sep  6 15:58:18 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: Assertion failed: (!REPLY_RING_EMPTY(sc)), function send_response_common, file src/pci_virtio_sock.c, line 950.
Sep  6 15:58:18 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=8b7d7343-9b80-40c7-9269-9d6166285b28,path=/Users/avirudhtheraja/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/avirudhtheraja/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Sep  6 15:58:18 avirudhs-mbp Docker[com.docker.driver.amd64-linux][634] <Notice>: Interface will have uuid 8b7d7343-9b80-40c7-9269-9d6166285b28
```
