### ISSUE TITLE
M1 tech preview: Check for update fails

### ISSUE THREAD

**Issue by andig** [docker/for-mac#5420]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior

Update check has not errors

### Actual behavior

<img width="243" alt="Screenshot 2021-03-04 at 09 48 21" src="https://user-images.githubusercontent.com/184815/109937030-d72ba100-7cce-11eb-9d80-a87606324d64.png">

### Information

  - macOS Version: 11.2.2 (20D80)
  - Docker Desktop Version: 3.1.0 60984 

M2 tech preview

**Comment by 0gust1** [comment]
This behavior is advertised on the M1 preview page : https://docs.docker.com/docker-for-mac/apple-m1/#known-issues

**Comment by stephen-turner** [comment]
Thanks, @0gust1. This is as documented, closing.
