### ISSUE TITLE
Enabling docker is stuck in "Starting...." For ever - Mac Diagnostics Id 41EA4461-A648-492E-8C95-AAFBE11808A2/20210304145549

### ISSUE THREAD

**Issue by htirghoda** [docker/for-mac#5422]
- [ Y] I have tried with the latest version of Docker Desktop
  - [ Y] I have tried disabling enabled experimental features
  - [ Y ] I have uploaded Diagnostics
  - Diagnostics ID: 41EA4461-A648-492E-8C95-AAFBE11808A2/20210304145549

### Expected behavior
Started K8S
### Actual behavior
Stuck in Starting while "Enable Kubernetes"
### Information

  - macOS Version: 10.15.7 Catalina
  - Docker Desktop Version: 3.1.0 -
  $ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Steps to reproduce the behavior

I have also tried adding below in my /etc/hosts
127.0.0.1	localhost kubernetes.docker.internal docker-for-desktop
255.255.255.255	broadcasthost
::1             localhost

  1. ...
  2. ...

**Comment by huineng** [comment]
same for me

**Comment by htirghoda** [comment]
Unfortunately 
Docker - Troubleshoot - Reset to factory defaults Worked for me , however if you are ready to loose all of your images . 
Also even after reset it took almost 3-5 Minutes in "Starting..." , but then It worked and giving correct response 
for $ kubectl version

**Comment by huineng** [comment]
for me it was on a brand new installation.  downloaded docker for mac installed it on my mac, enabled k8 but that one stayed in starting

**Comment by htirghoda** [comment]
Issue :: https://github.com/docker/for-mac/issues/4624 , you can follow .

**Comment by CafeLungo** [comment]
I'm seeing this on macOS 10.15.7, and Docker Desktop 3.1.0.
I'm also seeing this on macOS 11.2.3, and Docker Desktop 3.2.1 & 3.2.2.

I've never touched Kubernetes before now, but figured I'd enable it to see about learning more about it-- and on both systems described above, for my initial foray into Kubernetes, I'm seeing it failing to even start. So my initial impressions aren't good 😉  

And yes, I had an internet connection before clicking "enable" 😆

**Comment by longrunningprocess** [comment]
I was having this issue and I uninstalled my Docker for Mac and reinstalled, K8s came up for me this time.

I did notice one difference in my engine settings which was blank before I reinstalled:
![image](https://user-images.githubusercontent.com/4412848/111361582-38a32680-8664-11eb-89e5-3e36f07ed1f5.png)
