### ISSUE TITLE
Kubernetes does not start when another context is set

### ISSUE THREAD

**Issue by gmsantos** [docker/for-mac#5425]
Docker Desktop built-in k8s doesn't start if you are using a different context other than `docker-desktop` when you start Docker Desktop.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F423B07D-A600-4B9E-9F9E-7AFB26629699/20210305180539

### Expected behavior

Start Docker Desktop with built-in Kubernetes while using a different context

### Actual behavior

Start Docker Desktop, but Kubernetes does not start.

### Information

  - macOS Version: Big Sur 11.5.2
  - Docker Desktop Version: 3.6.0 (67351)

The original report was in Big Sur 11.2.2 and 3.2.1 (61626)

I can see the following error message on mac Console utility:

```
error while starting: cannot update the host kube config: invalid configuration: context was not found for specified context: my-eks-sso-context-in-another-file
```

### Steps to reproduce the behavior

  1. Fresh install Docker Desktop
  2. Enable Kubernetes
  3. Kubernetes starts successfully
  4. Close Docker Desktop
  5. Create a new kube config file and add it on $KUBE_PATH (connect to eks contexts using `aws eks`)
  6. Switch to another context, different from docker-desktop
  7. Restart Docker Desktop
  8. Got an error

![image](https://user-images.githubusercontent.com/1991286/110155202-95d9e500-7de5-11eb-96c1-4d07a5edceea.png)

**Comment by samalone** [comment]
I encountered the same issue today when Kubernetes failed to start under Docker Desktop for Mac. Reset Kubernetes Cluster,  Clean / Purge data, Reset to factory default, and even Uninstall/Reinstall failed to solve the problem. I wasted a lot of time trying to figure this out before finding this open issue.

The simple terminal command

```sh
> kubectl config use-context docker-desktop
```

fixed the problem.

**Comment by gmsantos** [comment]
I suspect that the cluster is just running even if it reports was failed in the UI. Maybe enforce the context to use in Docker Desktop internally would fix it.

**Comment by gmsantos** [comment]
Issue still present in:
- macOS Version: Big Sur 11.3.1
- Docker Desktop Version: 3.3.3

**Comment by zbpan-sh** [comment]
> I encountered the same issue today when Kubernetes failed to start under Docker Desktop for Mac. Reset Kubernetes Cluster, Clean / Purge data, Reset to factory default, and even Uninstall/Reinstall failed to solve the problem. I wasted a lot of time trying to figure this out before finding this open issue.
> 
> The simple terminal command
> 
> ```shell
> > kubectl config use-context docker-desktop
> ```
> 
> fixed the problem.

THANKS, it actually saved my day, It seems to impact on the latest 3.5 version, and I reverted back to 3.3 still not work, until I saw your response and tried to set the context, restarting docker and it goes green!

**Comment by gmsantos** [comment]
this issue still exists.

**Comment by gmsantos** [comment]
Diagnostics logs for version 4.2.0 (same behavior):

F423B07D-A600-4B9E-9F9E-7AFB26629699/20211124083057

**Comment by gmsantos** [comment]
Still an issue in 4.8.2

**Comment by gmsantos** [comment]
Still in 4.9.1

**Comment by brki** [comment]
I just ran into this issue too (v. 4.11.1 (84025)).

It would be nice to be able to easily see what the problem was.  I looked at the diagnostic logs generated by "Get Support" but didn't find anything in that flood of information.

Before guessing that I needed to change the context back to docker-desktop, I thought it must be a problem caused by an update of Docker Desktop.  So I tried the troubleshooting measures of "Clean / Purge data" and "Reset Kubernetes Cluster".

**Comment by gmsantos** [comment]
> I just ran into this issue too (v. 4.11.1 (84025), Mac M1).
> 
> It would be nice to be able to easily see what the problem was. I looked at the diagnostic logs generated by "Get Support" but didn't find anything in that flood of information.
> 
> Before guessing that I needed to change the context back to docker-desktop, I thought it must be a problem caused by an update of Docker Desktop. So I tried the troubleshooting measures of "Clean / Purge data" and "Reset Kubernetes Cluster".

I agree, super annoying to troubleshoot.

**Comment by gmsantos** [comment]
I could not reproduce the issue in 4.12.0, it seems fixed for me.

@brki @zbpan-sh @samalone I'm closing this issue (for now), let me know if you still have this issue after 4.12.0, happy to reopen it if persists for you.
