### ISSUE TITLE
I'm using the Macbook Air M1. However, now can't start the kubeneters, while docker is normal. Would please help to advise? Thanks. 

### ISSUE THREAD

**Issue by koalaxhe** [docker/for-mac#5428]
https://docs.docker.com/docker-for-mac/apple-m1/#feedback

I'm using the Macbook Air M1. However, now can't start the kubeneters, while docker is normal. Would please help to advise? Thanks.

**Comment by goz** [comment]
I'm having the same issue with my M1, saw these error on the logs

> 2021-03-06 18:10:24.777237+0800  localhost com.docker.driver.amd64-linux[12829]: cannot get lease for master node: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io docker-desktop)

**Comment by AlanLongYu** [comment]
I can run kubeneters now! should download the latest version of docker-desktop about m1 preview

**Comment by goz** [comment]
thanks, mine also works after re-installing the latest version for the m1 preview
