### ISSUE TITLE
error parsing HTTP 408 response body

### ISSUE THREAD

**Issue by fjossinet** [docker/for-mac#5429]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I would like to pull a Docker container using the command: docker pull

### Actual behavior

After a while I get the message:

<pre>Using default tag: latest
Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"</pre>

### Information

  - macOS Version: 11.2.2 (20D80)
  - Docker Desktop Version: 3.1.0 (60984)

### Steps to reproduce the behavior

From a terminal, type: ```docker pull ubuntu```

**Comment by gonzalosr** [comment]
Same here. I have tried uninstalling it completely and deleting all settings and data etc., nothing works.

If I connect to a VPN that routes all traffic and apply the VPN workaround [https://github.com/lastcosmonaut/docker-m1-vpn-workaround](https://github.com/lastcosmonaut/docker-m1-vpn-workaround), it works 🤯

**Comment by fjossinet** [comment]
I retried this evening for my own container (fjossinet/rnartistcore) for which I had the same issue. And it worked now. What about you @gonzalosr ?

**Comment by gonzalosr** [comment]
Still not working for me
