### ISSUE TITLE
Avast! antivirus - Infection blocked! on latest update 1.12.1-beta25 (from beta24)

### ISSUE THREAD

**Issue by alex-perfilov-reisys** [docker/for-mac#543]
### Steps to reproduce
1. Have Docker for Mac 1.12.1-beta24 installed
2. Check for updates -> 1.12.1-beta25 Available!
3. Click "Install update"
### Expected behavior

Docker for Mac is updated
### Actual behavior

Avast! antivirus - Infection blocked!

![avast](https://cloud.githubusercontent.com/assets/6089683/18335782/1b454e76-7550-11e6-8818-80821647eb92.jpg)
### Information

```
Diagnostic ID: 441CA662-4A6C-409E-BCC5-7B768EF83598
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dave-tucker** [comment]
Thanks for the report @alex-perfilov-reisys 
We've been doing some debugging and it appears that Avast is incorrectly identifying the file as a Windows executable (spoiler: it's not, it's the Linux Kernel) so this can be considered as a false positive. It's not the first time this has happened and we're trying our best to prevent this from happening again.

I'm going to leave this issue open while we work on a longer term solution.

In the meantime, could anyone confirm if the Avast definitions have been updated? We've had some reports that this file is no longer being marked as a virus...

**Comment by mchiang0610** [comment]
@dave-tucker Balraj informed us that it's no longer a problem.

Problems: 
- Qi-hoo is now alerting (false-positive)

**Comment by alex-perfilov-reisys** [comment]
Related
https://forums.docker.com/t/installation-fails-avast-file-protection-detects-win64-vitro-in-vmlinuz64/14711




On Mon, Sep 12, 2016 at 6:54 PM -0400, "Michael Chiang" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dave-tucker<https://github.com/dave-tucker> Balraj informed us that it's no longer a problem.

Problems:

  *   Qi-hoo is now alerting (false-positive)

-

**Comment by dave-tucker** [comment]
Thanks @alex-perfilov-reisys it looks like there was a report as late as 1 day ago that still confirms this is an issue, although that could jut be out-of-date definitions... I'll leave this open for a few more days until while we gather some more data.

**Comment by ijc25** [comment]
AIUI we have sorted this out by talking to the anti virus vendors and I've not heard of an instance of anything like this in more recent betas or stable releases so closing. Please reopen if antivirus gets uppity again.
