### ISSUE TITLE
Can't open ~/Library/Containers/com.docker.docker in Finder

### ISSUE THREAD

**Issue by Anutrix** [docker/for-mac#5430]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: NA

### Expected behavior
Should show folder in finder.

### Actual behavior
Gives the following error.
```
No application knows how to open file:///Users/<username>/Library/Containers/com.docker.docker/ (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1483, _LSFunction=runEvaluator}).
```

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes.
  - Is the problem new? No sure.
  - Did the problem appear with an update? No idea. Didn't check before.
  - macOS Version: 11.2.2 (Macbook Pro 2017).
  - Docker Desktop Version: 3.2.1(61626)
  - Is it reproducible? Yes.
  - Is the problem new? No sure. Didn't check before.
  - Did the problem appear with an update? No idea. Didn't check before.
  - `ls` shows `drwxr-xr-x@` for `com.docker.docker/` in terminal.

  
### Steps to reproduce the behavior

  1. Run `open /Users/<username>/Library/Containers/com.docker.docker/` in terminal.

**Comment by timbunce** [comment]
I just encountered this problem. It means, for example, that the directory can't be excluded from Time Machine backups.

**Comment by robertu7** [comment]
> I just encountered this problem. It means, for example, that the directory can't be excluded from Time Machine backups.

@timbunce could you see `~/Library/Containers/Docker` on Time Machine exclusion setting?
