### ISSUE TITLE
com.docker.hyperkit using entire RAM/CPU allocation

### ISSUE THREAD

**Issue by LeonardChallis** [docker/for-mac#5437]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Unfortunately my diagnostics is just stuck (maybe to do with the resources being used?):

![image](https://user-images.githubusercontent.com/404920/110339726-62cf6580-8020-11eb-946b-cae2bfa3d8ac.png)

### Actual behavior

  - macOS Version: 11.2.2
  - Docker Desktop Version: 3.2.1 (61626)

### Steps to reproduce the behavior

All I did was install docker, and then a container (https://node.minepi.com/) and let it run. Whatever I set it to allow for resources, it uses it all. For instance RAM, it uses pretty much 100% of that. As for CPU, I don't understand *how* exactly but it's using 281.2%.

![image](https://user-images.githubusercontent.com/404920/110343229-2dc51200-8024-11eb-870d-558780f4ed1a.png)

![image](https://user-images.githubusercontent.com/404920/110343179-20a82300-8024-11eb-8d4a-5fb957431f9c.png)

Changing RAM back to the default 2GB does reduce that to around 2GB (never lower) but CPU remains high.

Any advice or further information I can provide?

Many thanks

**Comment by wmelton** [comment]
I would like to chime in here and say that even after quitting Docker Desktop on mac, half an hour later I notice my computer crawling to a halt. com.docker.hyperkit is consuming most of the available ram on the system: 
![image](https://user-images.githubusercontent.com/1544125/120676994-3a5ada00-c45c-11eb-9407-51d3643d3fe4.png)
