### ISSUE TITLE
Docker Desktop fails to install due to damaged image

### ISSUE THREAD

**Issue by chasrmartin** [docker/for-mac#5438]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Moving the Docker image to Applications should succeed

### Actual behavior
Fails with message "image is damaged"

![Screen Shot 2021-03-08 at 14 33 18](https://user-images.githubusercontent.com/86798/110372012-c0ad7e80-801b-11eb-9c72-c58a5f7502d3.png)
![Screen Shot 2021-03-08 at 14 33 44](https://user-images.githubusercontent.com/86798/110372048-cefb9a80-801b-11eb-957f-f0f9b12c8f11.png)

### Information

  - macOS Version:  
  - System Software Overview:

  System Version:	macOS 11.2.2 (20D80)
  Kernel Version:	Darwin 20.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Heinlein
  User Name:	Charles Martin (chasrmartin)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	6 days 2:29

  - Docker Desktop Version: most recent

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Intel or M1 chip?

**Comment by stephen-turner** [comment]
Also, is this a fresh installation or are you installing on top of an old version?

**Comment by DigitalRogues** [comment]
I'm seeing the same thing, I get the pop up while copying the app form the Disk Image to the Applications folder.

M1 chip, both fresh install and reinstall

**Comment by ngrande** [comment]
Same behavior for me. First installed it on top and then tried a fresh install - no help, can not start it at the moment.

**Comment by borodiliz** [comment]
Same problem here (Intel), after removing Docker Desktop 3.2.2 and trying to install 3.3.1
