### ISSUE TITLE
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by hhduong** [docker/for-mac#5440]
I had this problem run docker in macbook m1 and then the installation failed. Hope to be fixed soon.
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by stephen-turner** [comment]
See https://docs.docker.com/docker-for-mac/apple-m1/
