### ISSUE TITLE
SFTP issue in Docker Preview on MacBook Pro with Apple Silicon (M1)

### ISSUE THREAD

**Issue by patriceckhart** [docker/for-mac#5443]
My special container https://hub.docker.com/repository/docker/patriceckhart/docker-neos-alpine uses sftp (sshd) in local operation. With the Intel Macbook Pro, uploading via SFTP to the container is quick. The upload on the M1 sometimes takes up to 4 seconds. Connection maintenance command is sent every 1 seconds.

**Comment by stephen-turner** [comment]
Thanks for the report, @patriceckhart. It would be interesting to know whether this is a Docker bug, or just a property of Apple's new virtualization framework. Are you able to reproduce it in a VM created with https://github.com/evansm7/vftool?

**Comment by patriceckhart** [comment]
Can I try. The bug does not occur on external SFTP servers. Only in Docker containers in conjunction with Apple Silicon.

**Comment by patriceckhart** [comment]
Ok, I'll be happy to test that when I have the time

**Comment by patriceckhart** [comment]
@stephen-turner In my opinion it is not due to Docker but rather to PhpStorm which in my case establishes the connection. I cannot observe the behavior with an FTP program.
