### ISSUE TITLE
Container ip is always set to 0.0.0.0 (and it doesn't work)

### ISSUE THREAD

**Issue by ziofil** [docker/for-mac#5444]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Information
  - macOS Version: 11.2 on M1 MacBook Air
  - Docker Desktop Version:3.1.0 (preview)

### Steps to reproduce the behavior
1. Run a container, like `pihole/pihole` (arm64)
2. No way to connect to it (SERVERIP 0.0.0.0) all ports not binded

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still issues, please open a new ticket with diagnostics.
