### ISSUE TITLE
Race condition with `/containers/{id}/json` after `start` event

### ISSUE THREAD

**Issue by ryansch** [docker/for-mac#5445]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 12dc2dd0-ca7f-4147-9b0f-beb50c5f403f/20210310172330

### Expected behavior
Upon receiving a `start` event via the API, I should be able to 'inspect' the referenced container via `/containers/{id}/json` and receive accurate port information.

### Actual behavior
There's a race condition that prevents my inspect call from returning reliable information every time. This breaks my existing event-based software.

### Information

  - macOS Version: 11.2.1
  - Docker Desktop Version: 3.2.1 (61626)

This issue seems to be directly related to the following bullet point from the 3.2.0 changelog:
`Fixed an issue when binding ports on specific IPs. Note: It may now take a bit of time before the docker inspect command shows the open ports. Fixes docker/for-mac#4541`

### Steps to reproduce the behavior

  1. Start software that listens for container `start` events and immediately inspects that container.
  2. Print out port information.
  3. Start multiple containers with port forwarding.
  4. Observe a mixture of accurate and missing port information.

**Comment by stephen-turner** [comment]
I believe this is exactly the point you found in the changelog. Unfortunately it was necessary to fix the bug listed there: the information was just wrong before. Sorry, this is not fixable.

**Comment by ryansch** [comment]
@stephen-turner What about delaying the `start` event until after the data settles? How about another event to tell me that it's ok to inspect?
