### ISSUE TITLE
Docker Desktop fails to start with dockerd error about swarm manager

### ISSUE THREAD

**Issue by Mahoney** [docker/for-mac#5447]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4ADE55F8-DBD8-4F63-B31A-656432AFDA43/20210311105907

### Expected behavior

Docker Desktop starts successfully after a reboot / closing and restarting

### Actual behavior

It fails to start with this error:
```
2021-03-11T09:47:26Z dockerd time="2021-03-11T09:47:26.642818573Z" level=error msg="Handler for GET /v1.41/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
```
![image](https://user-images.githubusercontent.com/168448/110778450-43238180-825a-11eb-8ede-150ce9007c75.png)

I then click exit, restart Docker Desktop - and it starts OK.

While I remember trying to use a secret some time ago, and it not working because I wasn't using swarm, I don't think I did anything further to try and set up swarm...

### Information

  - macOS Version: Big Sur 11.2.3 (20D91)
  - Docker Desktop Version: 3.2.1 (61626) 
  - Docker Desktop Version: 3.2.2 (61853) 

It started immediately after my upgrade to 3.2.1 on 12th March
It continues to happen after my upgrade to 3.2.2 on 17th March

### Steps to reproduce the behavior

  1. Exit Docker Desktop. Perhaps reboot macOS
  2. Start Docker Dekstop / boot macOS

**Comment by Mahoney** [comment]
Just happened again on updating to 3.2.2

**Comment by djs55** [comment]
Could you try an experimental build and let me know if it works any better? The build is:  https://desktop-stage.docker.com/mac/stable/arm64/62178/Docker.dmg . If it still fails could you upload diagnostics and quote the id and I'll take a look. Thanks!

**Comment by Mahoney** [comment]
I'm on an Intel Mac - looks like that's an M1 build
