### ISSUE TITLE
No warning when resetting to factory defaults

### ISSUE THREAD

**Issue by nc-holodakg** [docker/for-mac#5448]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I'm using Docker for Mac at work, and saw a warning message like this today:
![image (2)](https://user-images.githubusercontent.com/24393559/110830492-45400d00-8267-11eb-9976-336a40f70f24.png)

Now, the actual cause of this seemed to be how my organization rolled out the latest Docker update, and we seem to have a fix. The real issue is that I fumbled clicking on my trackpad and accidentally hit the "Reset Docker to factory defaults" button. **Without any warning**, this deleted _all_ my Docker containers and volumes. A highly destructive operation like this should at least come with a warning message or confirmation dialog!

### Expected behavior

When "Reset Docker to factory defaults" is clicked, there is a warning or confirmation presented to the user to make sure they really meant to reset everything related to Docker.

### Actual behavior

When "Reset Docker to factory defaults" is clicked, it erases all Docker data without warning, and the process can't be canceled.

### Information
  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.2.1

**Comment by mtpultz** [comment]
I'm getting the same error on **macOS Big Sur v11.2.3** for **Docker 20.10.5**.  I can't use Docker at all it keeps showing the error in the issues description followed by:

![image](https://user-images.githubusercontent.com/599498/111202883-a1fe3900-8581-11eb-86cb-a2ea1eb2f25c.png)
![image](https://user-images.githubusercontent.com/599498/111202964-b3474580-8581-11eb-9ae8-f6068a2a1605.png)
![image](https://user-images.githubusercontent.com/599498/111203025-be9a7100-8581-11eb-9aa8-c8b07e733e56.png)

You put in your password, and then it repeats.
