### ISSUE TITLE
com.docker.hyperkit high CPU on MacOS 11.2.2 when running opendistro-elasticsearch

### ISSUE THREAD

**Issue by vostee** [docker/for-mac#5450]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FA5E391F-DF3C-4BD9-BB1A-ED7BE881E3D2/20210312130753

### Expected behavior
CPU Usage should be moderate

### Actual behavior
CPU Usage is between 180% - 220%

### Information
This issue is readily reproducible after following the [steps](https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/) to install opendisto-elastic search using helm. Used the same steps to install elasticsearch on a different OS (fedora) and the problem does not present itself.
  - macOS Version: 11.2.2
  - Docker Desktop Version: 3.2.1
  - MacbookPro 16" 2019, 8 core, 32GB RAM

### Steps to reproduce the behavior
1. On MacOS 11.2.2 (Big Sur) install docker version 3.2.1
2. With minikube and kubernetes installed use these [steps](https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/) to install opendistro-elasticsearch using helm.
3. Notice that the com.docker.hyperkit CPU usage spikes and flactuates between 180%-220%.

![image](https://user-images.githubusercontent.com/44141272/110972837-746b8280-832a-11eb-8073-c52b436f8f80.png)

**Comment by kuberlog** [comment]
<img width="66" alt="Screen Shot 2021-03-23 at 12 53 31 PM" src="https://user-images.githubusercontent.com/1966377/112194597-09963300-8bd7-11eb-8456-021d856ae218.png">

TFW you kill hyperkit. docker-for-mac is eternally borked.
