### ISSUE TITLE
Docker not working with apple M1 processor

### ISSUE THREAD

**Issue by bengurney1** [docker/for-mac#5456]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 015E630A-D86A-42BE-AB1C-4EC2A0ECA0A6/20210315122939

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. remove all docker installs
  2. download preview and install
  3. try to start docker
  4. resulting in a fatal error (pleawse see the diagnostic for detail.
  5.

**Comment by djs55** [comment]
@bengurney1 From the logs I see the error
```
time="2021-03-15T12:29:37Z" level="error" msg="SettingsLoader: Cannot save settings: validation(message: ""Must use virtualization.framework on arm64"")"
```
Previously I see an attempt to run an Intel version of Desktop, which failed with an error about processor incompatibility but I suspect it wrote an invalid settings file before it quit. Could you delete `~/Library/Group\ Containers/group.com.docker/settings.json` and try restarting Docker again?

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still issues, please open a new ticket with diagnostics.
