### ISSUE TITLE
Labels in factory reset progress missing

### ISSUE THREAD

**Issue by schliesser** [docker/for-mac#5457]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: none

Fresh installation with Preview is now working. It's just a display issue:

### Expected behavior

Showing the real titles, messages and button labels

### Actual behavior

While resetting to factory defaults and on reset success it shows only the label identifiers like

* FactoryResetWarningTitle
* FactoryResetSuccessMessage
* FactoryResetRestartButton

![image](https://user-images.githubusercontent.com/11655823/111173909-4a72c400-85a7-11eb-9afd-b2dc0caf61c6.png)

### Information

  - macOS Version: 11.2.3 (20D91) (With M1)
  - Docker Desktop Version: 3.1.0 (60984)

### Steps to reproduce the behavior

  1. brew install docker
  2. Errors on start because of M1
  3. Download docker preview with browser
  4. Run docker preview setup
  5. Start docker preview -> Error
  6. Follow error advice to reset to factory defaults

**Comment by stephen-turner** [comment]
Thanks, checking.

**Comment by codeactual** [comment]
Also seeing this on non-M1 except that the button never appears, but the progress bar animates back and forth forever w/o any work seeming to happen.

macOS Version: 11.2.3, MacBook Pro (Retina, 15-inch, Mid 2014)
Docker Desktop Version: 3.2.2

I'm pretty sure I tried out and uninstalled Docker for Mac years ago, so there may have been very old files left around somewhere that triggered the need for a reset. I'm not sure where to look to confirm.

![Screen Shot 2021-03-15 at 3 10 34 PM](https://user-images.githubusercontent.com/57662/111228260-201e0800-85a1-11eb-8fab-1f9107b5abdb.png)
![Screen Shot 2021-03-15 at 3 06 01 PM](https://user-images.githubusercontent.com/57662/111228271-2613e900-85a1-11eb-99b4-dabaec744762.png)

**Comment by stephen-turner** [comment]
This is now fixed in Docker Desktop 3.3.0.
