### ISSUE TITLE
BuildKit set as default builder since 3.2.x

### ISSUE THREAD

**Issue by andreyzher** [docker/for-mac#5458]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 74E6F0AA-305E-4111-8E5F-55FDA86DB953/20210315162132

### Expected behavior

Docker BuildKit should be on opt-in basis according to [documentation](https://docs.docker.com/develop/develop-images/build_enhancements/)

### Actual behavior

Docker BuildKit is default builder since 3.2.x

### Information
  - macOS Version: Big Sur 11.2.3
  - Docker Desktop Version: 3.2.2

In Docker Desktop 3.1.x the BuildKit builder was on opt-in basis.

I checked the release notes for Docker Desktop for Mac and there is nothing indicating this change in behaviour, and this only seems to be affecting Mac packages - I was unable to reproduce on a CentOS VM.

If this was intentional, it should be called out in the release notes as some images will fail to build with BuildKit enabled ( specifically sclorg/s2i-base-container#207 )

### Steps to reproduce the behavior

1. Upgrade to Docker Desktop for Mac >= 3.2.0
2. Build **any** Docker image

Dockerfile:
```
FROM centos:7
LABEL foo bar
```

Command: `docker build -t foo-bar .`

**Comment by stephen-turner** [comment]
It's been the default for new installations (or on a factory reset) since 2.4 (see https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2400). But we just made it the default for existing installations too. You're right, we should have mentioned it. It can still be turned off in the engine settings if you need to.

**Comment by andreyzher** [comment]
I see. Didn't think to scroll back to 2.4 that it was the new default for new installs .

Thanks for confirming - I thought I was going mad.

**Comment by stephen-turner** [comment]
I've raised a PR against the docs, docker/docker.github.io#12505.

**Comment by andreyzher** [comment]
Thanks for the quick turnaround updating the docs!

Do you know if the same change could be expected to the Linux installs any time soon?

**Comment by stephen-turner** [comment]
I believe they're discussing it, but I'm afraid I don't know the timeline.
