### ISSUE TITLE
Docker for Mac won't properly start on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by welladamm** [docker/for-mac#546]
### Steps to reproduce

Simply try runnning Docker.app on macOS 10.12 Sierra GM

### Expected behavior

Docker should start.

### Actual behavior

Docker gets stuck at 'starting': 

![image](https://cloud.githubusercontent.com/assets/319494/18340471/b2071ea2-75d7-11e6-8e54-93a2c46e3a57.png)

### Information

```
Diagnostic ID: 3E199B8C-B654-48C6-B8DE-BAE80C4B990B
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A319)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
```

**Comment by dsheets** [comment]
Something seems to have gone wrong with your diagnostic upload and we haven't received your log bundle. Could you please upload again? I have increased the priority on the log reporting failure issue we have tracking that problem.

**Comment by welladamm** [comment]
@dsheets I have uploaded another log bundle, the ID of which is 3E199B8C-B654-48C6-B8DE-BAE80C4B990B. Please let me know if you have received it.

**Comment by dsheets** [comment]
I still have not. Could you please run `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u` and report its output and exit code (run `echo $?` immediately following completion of `docker-diagnose` comment)?

**Comment by welladamm** [comment]
`docker-diagnose` exited with 1:


> ○ /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
OS X: version 10.12 (build: 16A319)
Docker.app: version: 1.12.1-beta25 (158f2ee)
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: Failure("docker ps: timeout after 10.00s")
Error docker ps: timeout after 10.00s
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux -db is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[OK]      db
[OK]      slirp
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Error exec: echo "00000003.0000f3a6" | nc -U /Users/Adam/Library/Containers/com.docker.docker/Data/@connect > /tmp/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352/diagnostics.tar: exit 1
Most specific failure is: com.docker.osxfs is not running
Docker logs are being collected into /tmp/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352.tar.gz
Error exec: /usr/bin/curl -L -X PUT -T '/tmp/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352.tar.gz' -H 'Host: docker-pinata-support' -H 'Date: Thu, 08 Sep 2016 18:34:04 CST' -H 'x-amz-acl: bucket-owner-full-control' -H 'Content-type: application/json' https://docker-pinata-support.s3.amazonaws.com/incoming/2/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352/report.tar: exit 55
diagnose: internal error, uncaught exception:
          Failure("exec: /usr/bin/curl -L -X PUT -T '/tmp/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352.tar.gz' -H 'Host: docker-pinata-support' -H 'Date: Thu, 08 Sep 2016 18:34:04 CST' -H 'x-amz-acl: bucket-owner-full-control' -H 'Content-type: application/json' https://docker-pinata-support.s3.amazonaws.com/incoming/2/3E199B8C-B654-48C6-B8DE-BAE80C4B990B/20160908-183352/report.tar: exit 55")

**Comment by welladamm** [comment]
Damn, after a system restart, Docker for Mac now runs without a problem.

**Comment by dsheets** [comment]
@welladamm I'm glad it's working for you, now. Why did you edit the upload error information? The `docker-diagnose` output (including the `curl` failures) is useful for our fixing of the upload problem.

**Comment by welladamm** [comment]
@dsheets Amazon AWS is severely interfered with by GFW in China. This explains the continuous failing uploads. Since that was not the main issue, I re-ran the diagnostic after applying a proxy setting to my terminal.

However, these upload failures could've been avoided if the diagnostic GUI respects macOS system proxy configuration.  That's another issue, of course.

**Comment by welladamm** [comment]
@dsheets Is the latest log bundle worth looking at?

**Comment by mchiang0610** [comment]
Closing because this seems to be resolved.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by welladamm** [comment]
@djs55 Thanks! I'll give it a shot.
