### ISSUE TITLE
Use new virtualization framework will ignore proxy setting

### ISSUE THREAD

**Issue by Abirdcfly** [docker/for-mac#5461]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3D790D31-3707-499F-8F5C-83326CE2EA98/20210316013307

### Expected behavior
use proxy 
### Actual behavior
If I open “Use new virtualization framework” feature，docker pull will ignore my proxy setting in Resources-Proxies, my proxy setting is look like "http://127.0.0.1:6789" which will get a "Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
" error. 
But if I close "Use new virtualization framework” feature，docker pull will get the right image.
### Information

  - macOS Version: 11.2.3 (20D91)
  - Docker Desktop Version: 3.2.2 (61853)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks, you're right, this is not implemented yet. The new virtualisation framework is subject to most of the same Known Issues as listed at https://docs.docker.com/docker-for-mac/apple-m1/.

**Comment by Abirdcfly** [comment]
> Thanks, you're right, this is not implemented yet. The new virtualisation framework is subject to most of the same Known Issues as listed at https://docs.docker.com/docker-for-mac/apple-m1/.
Looks like I misunderstood.I thought these bug were only for M1. And My laptop is macbook pro 2018

**Comment by stephen-turner** [comment]
Yes, I agree we didn't make that very clear. But it's the same underlying technology as the M1 implementation uses.
