### ISSUE TITLE
Docker is not running

### ISSUE THREAD

**Issue by yichenwan** [docker/for-mac#5463]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FDA03F2D-4B56-46D8-92B4-7078351A35E0/20210316071329

### Expected behavior
docker starts running
### Actual behavior
After docker jumps out of the window and needs permission to install the software, after entering the password, a window titled "Docker Desktop requires privileged access" appears again and docker seems to be blocked
### Information

  - macOS Version: Big Sur v11.2.3
  - Docker Desktop Version: 3.2.2
  - Docker version showed on terminal: 20.10.5

### Steps to reproduce the behavior

  1. Installed docker DMG file
  2. clicked on the icon to start
  3. Docker jumps out of the window and needs permission to install the software, after entering the password, a window with title "Docker Desktop requires privileged access" appears again and docker seems to be blocked

**Comment by stephen-turner** [comment]
Is this the same as #5459?

**Comment by yichenwan** [comment]
Almost the same, but there is no illegal instruction exception message, the situation I encountered is as follows:
![image](https://user-images.githubusercontent.com/20853146/111405933-50ce8080-870c-11eb-8b5b-5efa8bbe7244.png)
![image](https://user-images.githubusercontent.com/20853146/111405947-56c46180-870c-11eb-9ebb-55fe76955989.png)
![image](https://user-images.githubusercontent.com/20853146/111405942-53c97100-870c-11eb-9f06-f33642e0f412.png)

After entering the password, a window with title "Docker Desktop requires privileged access" appears again.

**Comment by StefanScherer** [comment]
Hi @yichenwan 
The diagnostics show parts of version 2.0.0.3. 
I suggest to uninstall Docker Desktop from the command line as described in https://docs.docker.com/docker-for-mac/troubleshoot/#troubleshoot and install the latest version again which you can download from https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-322

**Comment by yichenwan** [comment]
Hi @StefanScherer
Thanks for your reply, after executing the command `/Applications/Docker.app/Contents/MacOS/Docker --uninstall`, I found an error message:
`/Applications/Docker.app/Contents/MacOS/Docker --uninstalljson error: error domain = NSCocoaErrorDomain code = 3840 "no value". UserInfo = {NSDebugDescription = No value. }`

How do I fix it?

**Comment by naphta** [comment]
I'm getting the same problem. I get the uninstallation error described above too.

I've tried:
 - Upgrading to the latest macOS (11.2.3)
 - Using Docker 3.2.1, and 3.2.2
 - Deleting all docker directories inside `~/Library`
 - Tailing all logs to try and find error messages
 - Pressing uninstall / clear data inside the UI
 - Tailing the vm TTY (doesn't exist)
 - Disabling macOS firewall
 - Various uninstall / reinstall attempts
 - Various machine reboots in various states of uninstall / reinstall

My diagnostic ID is `4EE78969-985E-44E5-94A4-1D27176BD803/20210319094803`

**Comment by StefanScherer** [comment]
@yichenwan @naphta That's unexpected, but when the uninstall command doesn't work you could follow the commands listed here https://github.com/docker/for-mac/issues/5426#issuecomment-791622494 to remove everything and then do a fresh install.

**Comment by naphta** [comment]
> @yichenwan @naphta That's unexpected, but when the uninstall command doesn't work you could follow the commands listed here [#5426 (comment)](https://github.com/docker/for-mac/issues/5426#issuecomment-791622494) to remove everything and then do a fresh install.

That did the trick. I did have a hunt for uninstallation scripts but only found small tidbits of that. Maybe this should be documented somewhere? I've lost hours trying various things!

**Comment by StefanScherer** [comment]
@naphta Sorry to hear that. Thanks for the suggestion. I'll discuss it with the docs team.

**Comment by yichenwan** [comment]
@StefanScherer @naphta Thanks for your suggestion, I also fixed it.
