### ISSUE TITLE
com.docker.backend -watchdog 100% CPU

### ISSUE THREAD

**Issue by jrobison-sb** [docker/for-mac#5469]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: CBFDF2FC-91A5-4B8B-BC78-8B6BDF888E5D/20210317195137

### Expected behavior

Docker should not use 100% CPU and spin up my fans unless I'm doing something computationally expensive in a container.

### Actual behavior

Docker does use 100% CPU and spin up my fans even when I'm not doing anything computationally expensive in a container. 

### Information

  - macOS Version: Catalina 10.15.7
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior

I'm not sure this will be reproducible in the way that is usually asked for, but I can reproduce it myself roughly 100% of the time. The problem I'm seeing is that Docker will use 100% CPU and spin up my fans when I run any image other than the tiniest images. I'll see in `htop` that `com.docker.backend -watchdog` is using 100% of a CPU.

If I run busybox or presumably any other very stripped down image, I won't see the problem. But if I run a somewhat larger image like ubuntu:20.04, it'll spike to 100% CPU and spin up the fans. This happens even when I'm not doing anything computationally expensive inside the container. Even a running container just sitting idle at a bash prompt will trigger the issue. And once the issue is triggered, I can close the container and see that `docker ps -a` shows 0 running containers, but CPU is still pegged at 100%. The only way to spin down the fans after triggering the issue is to close Docker Desktop.

I did already reset to factory settings and the issue persists.

**Comment by iameli** [comment]
I was running into this as well after running a container that bind-mounted my home directory. What worked for me was switching off `gRPC FUST for file sharing`, that made the CPU usage become reasonable again.

![image](https://user-images.githubusercontent.com/257909/113346246-72bd2b00-92e8-11eb-814b-70c3b02c0b0b.png)

**Comment by jrobison-sb** [comment]
@iameli thanks for that comment! I do often mount my home directory inside containers, so that could definitely be a possible culprit. I'm giving this a shot now. If 100% CPU doesn't recur in the next couple days I'll come back and close this.

**Comment by cjheppell** [comment]
@jrobison-sb was there any success with this suggested workaround?

We're hitting similar issues with extremely excessive CPU consumption (mainly during docker builds) but disabling the gRPC FUSE feature hasn't helped us (no home dir bind mounts in our case either).

**Comment by jrobison-sb** [comment]
@cjheppell This probably isn't helpful to you, but I haven't seen any recurrences of this issue since disabling gRPC FUSE.

I'll leave this issue open in case the maintainers want to address it, but I'm personally all set with disabling gRPC FUSE.

**Comment by cjheppell** [comment]
Interesting! Thanks for confirming. I'll do some more investigating then...

**Comment by drunlade** [comment]
I'm seeing this is as well.

Isn't there a massive performance hit to **not** using gRPC FUSE?
