### ISSUE TITLE
Docker for Mac fails to work on Sierra GM

### ISSUE THREAD

**Issue by erans** [docker/for-mac#547]
### Expected behavior
docker ps should not timeout

### Actual behavior
docker ps times out with no way to see what's going on

### Information

Diagnostic ID: 325E9479-E17E-41B6-B80F-524054E2540C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/eran/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/325E9479-E17E-41B6-B80F-524054E2540C/20160908-102439/qemu-img-check.stdout 2> /tmp/325E9479-E17E-41B6-B80F-524054E2540C/20160908-102439/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by vistiyos** [comment]
Try with the Beta version of Docker. Remember to fully uninstall the stable version first.

**Comment by praveenkannan** [comment]
@vistiyos  ~ how do I get the beta? Did you mean the private beta? Would help if you can point me to the link. I am on Sierra GM and I see the same issue @erans  posted.

**Comment by vistiyos** [comment]
@praveenkannan you can find the Beta release in this link

https://docs.docker.com/docker-for-mac/

**Comment by praveenkannan** [comment]
Thanks, It works for me now. The key to this is fully removing the stable version. 

`$(mdfind Docker.app)/Contents/MacOS/Docker --uninstall`

**Comment by dsheets** [comment]
If you are comfortable running a beta operating system, we recommend running the Docker for Mac Beta in order to get timely updates as we fix issues with the new OS version. You can download the beta from https://download.docker.com/mac/beta/Docker.dmg.

I'm glad this has resolved your issue. We are working on improving the experience of changing channels and warning about uninstallation/reinstallation. Thanks for using Docker for Mac!
