### ISSUE TITLE
Docker M1 crashes on first run

### ISSUE THREAD

**Issue by cglaeser** [docker/for-mac#5470]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:9D5919E0-FCEA-476F-BFEB-DD32413D9A17/20210318003654

### Expected behavior
Docker Desktop for Apple M1 starts on first run after downloading from docker website
### Actual behavior
Docker Desktop for Apple M1 crashes on first run
### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gersonvneto** [comment]
Have you installed rosetta before launching? 
softwareupdate --install-rosetta

**Comment by JWesorick** [comment]
This is happening to me on macbook pro 13in m1. I think I already have rosetta installed? Running `softwareupdate --install-rosetta` returns `Installing Rosetta 2 on this system is not supported.`

**Comment by johnson7788** [comment]
Same issue, I think my Rosetta already installed:

```
#cat "/Library/Apple/System/Library/LaunchDaemons/com.apple.oahd.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.apple.oahd</string>
	<key>MachServices</key>
	<dict>
		<key>com.apple.oahd</key>
		<true/>
	</dict>
	<key>ProgramArguments</key>
	<array>
		<string>/Library/Apple/usr/libexec/oah/oahd</string>
	</array>
	<key>POSIXSpawnType</key>
	<string>Interactive</string>
	<key>UserName</key>
	<string>_oahd</string>
</dict>
</plist>
```

**Comment by erotte** [comment]
running `softwareupdate --install-rosetta` again (was installed before, too) fixed a starting issue for me.
Something got installed then, maybe an update.

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still issues in the latest version, please open a new ticket with diagnostics.
