### ISSUE TITLE
Provide option to hide docker icon from menu bar

### ISSUE THREAD

**Issue by johnnyplaydrums** [docker/for-mac#5474]
### Expected behavior

Expected to have an option to hide or show the Docker icon in the menu bar.

### Actual behavior

This option does not exist. You can't hide the Docker icon from the menu bar while docker is running.

### Information

It's [in apple's guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/) to give users this option. I think the community would greatly appreciate this! Is there any reason it's not technically possible? If it is, can you please roadmap this feature? We would so appreciate it! Thank you! 🙏❤️

### Steps to reproduce the behavior

macOS Version: 11.2.2
Docker Desktop for Mac Version: 3.2.2

**Comment by stephen-turner** [comment]
Noted, but would require a lot of redesign as unlike a typical application it's our primary interface, so unlikely any time soon.

**Comment by johnnyplaydrums** [comment]
@stephen-turner got it, thanks for providing some explanation, that helps! I'll hold out hope that one day it will be implemented 😊
