### ISSUE TITLE
mac os M1 the build image is not running on the Linux server

### ISSUE THREAD

**Issue by DreamPWJ** [docker/for-mac#5475]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
docker run sucess
### Actual behavior
fail 
standard_init_linux.go:190: exec user process caused "exec format error"

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior

# 自定义构建Spring Boot项目镜像
# VERSION 1.0.0
# 构建镜像docker build --build-arg PROJECT_NAME=app 或 docker-compose.yaml args参数传入
ARG JDK_VERSION
ARG DEPLOY_FOLDER
ARG PROJECT_NAME
ARG EXPOSE_PORT

# 基础镜像
FROM openjdk:${JDK_VERSION}-jre

# 设置镜像元数据，利用 docker inspect [镜像名称|镜像ID],即可查看
#LABEL author="潘维吉"

# 挂载数据卷 docker删除后数据不丢失 docker run -v 映射
VOLUME /logs

# 指定切换用户
USER root

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && echo $TZ > /etc/localtime

# 安装bash
# RUN apk upgrade --update && apk add bash

# 切换工作目录 相当于cd
# WORKDIR /$DEPLOY_FOLDER/$PROJECT_NAME

# 配置字体 如果file-which-may-exist目标文件存在，才会被复制  未来新方案可考虑字体目录映射挂载方式更易维护和代码更通用
COPY msyh.ttc file-which-may-exist? /usr/share/fonts/

# 将部署文件复制到docker内根目录
COPY  *.jar  /server.jar

# 对外暴露端口
EXPOSE  $EXPOSE_PORT

# 运行jar包命令 远程调式  缩短 Tomcat 的启动时间  java -jar app.jar
# JDK8  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
# JDK11 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
ENTRYPOINT "java" "-jar" $JAVA_OPTS $REMOTE_DEBUGGING_PARAM  "-Djava.security.egd=file:/dev/./urandom" "/server.jar"

**Comment by rfay** [comment]
An "exec format error" normally means that there's a binary inside your container that is of the wrong format. So you may have an arm64 image that has an amd64 binary that it's trying to run. Take a look especially at whatever binary your container is trying to run at startup.

**Comment by DreamPWJ** [comment]
yes, Mac mini M1 is arm64 ， How can I solve it， use docker 3.1.0 RC

**Comment by DreamPWJ** [comment]
@rfay  Is there a solution? I've tried a lot of things, but it doesn't work

**Comment by rfay** [comment]
Wait a minute, you said "the build image is not running on the Linux server". But this issue about a mac M1? But you're running an image on Linux? What architecture? (Run `uname -a` on the host where you're having trouble)

Is this a public image on hub.docker.com? If so, please provide a link.

You can 

1. Manually inspect the image  on the environment where you're having trouble  (linux?). `docker pull <image>` and then `docker inspect <image>`. Does the architecture match the environment? If not, you're going to have trouble. Most linux is amd64. Mac m1 of course is arm64. 
2. Manually run the image on the environment you're having trouble. `docker run --rm -it <image> sh`. Then manually run the start command, whatever it is. Inspect the command. If it's a script, see what it's doing and manually run the things it runs. You can also use the `file` command to figure out what the architecture of the embedded binaries is.

**Comment by DreamPWJ** [comment]
1. docker inspect <image:  "Architecture": "arm64", "Os": "linux"

**Comment by rfay** [comment]
You're trying to run an arm64 image on an amd64 (x86_64) linux machine. That won't work. You need to build an amd64 image to run it on an amd64 platform. 

There are lots of [articles](https://www.google.com/search?q=docker+multi+arch+build&oq=docker+multi&aqs=chrome.0.69i59j69i57j0i20i263j0l4j69i60.1908j0j4&sourceid=chrome&ie=UTF-8) on multi-arch building.  Or you can build on the architecture that you're targeting.

Please close this issue, as it has nothing to do with docker for mac.
