### ISSUE TITLE
Menu → Check for Updates… results in an error

### ISSUE THREAD

**Issue by davidbailey00** [docker/for-mac#5478]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 35A5A6C7-AC37-45D9-8548-4947FA4AE937/20210319101757

### Expected behavior

A message appears saying "No updates available" or similar, indicating that the update check succeeded.

### Actual behavior

The update check fails, and the following message appears instead:

![Update Error! No valid update information could be loaded. Button: Cancel Update](https://user-images.githubusercontent.com/4248177/111765565-6a9ecd80-889c-11eb-9ca4-8041ff00432d.png)

### Information

  - macOS Version: 11.3 Beta (20E5210c) on arm64
  - Docker Desktop Version: 3.3.0 (62029) (Docker Desktop for Apple Silicon RC 1)

### Steps to reproduce the behavior

  1. Open Docker Desktop
  2. Press menu icon → Check for Updates…

**Comment by StefanScherer** [comment]
Thanks @davidbailey00 for the report. This is the expected behaviour at the moment. We will provide valid update information with the official release of Docker Desktop for Apple Silicon, then updates will work.
