### ISSUE TITLE
Containers that working correct on Intel doesn't work on M1 preview (with last update it is even worse)

### ISSUE THREAD

**Issue by mksada** [docker/for-mac#5479]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Some containers that are running on Intel mac not running on M1 even with or without --platform linux/amd64

With last docker update form 2021-03-18 it is even worse. For example my rabbitmq container stopped completely working with this error: qemu: uncaught target signal 6 (Aborted) - core dumped

Same container worked fine in previous preview version so I had to rollback docker preview version.

Let me know how can I provide more informations to investigate this issue

**Comment by stephen-turner** [comment]
This is unfortunately normal, and documented. If qemu can't run the container, there's nothing we can do. We recommend running arm64 containers on M1 machines.
