### ISSUE TITLE
Docker Engine not Starting Correctly / Stuck on "Starting", "Stopped" Loop

### ISSUE THREAD

**Issue by ryendu** [docker/for-mac#5483]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8DD7C77C-C071-4B8F-81D8-43BFA1A58FF8/20210319203642

### Expected behavior
Open docker desktop, give it a little bit, and it starts correctly.
### Actual behavior
Open docker desktop, on a loop of "Starting", "Stopped", "Starting", "Stopped",  "Starting", "Stopped",  "Starting", "Stopped".
### Information

  - macOS Version: 11.1 (20C69)
  - Docker Desktop Version:  3.3.0(62029) RC 1

### Steps to reproduce the behavior

  1. Install docker RC 1 
  2. Open it.

https://user-images.githubusercontent.com/61951438/111840045-050d0a00-88b9-11eb-8937-6e39644428be.mov

**Comment by cynecx** [comment]
This might be a firewall issue. I had the "Block all incoming connections" option enabled, disabling this made docker work for me.

**Comment by ryendu** [comment]
Tried that, doesn't work for me.

**Comment by cynecx** [comment]
Did you get two popups asking you whether you want `com.docker.supervisor` and `vpnkit-bridge` to accept incoming connection? (If not you might wanna check your firewall settings/Reinstall docker so the firewall triggers again.)

**Comment by ryendu** [comment]
No, I didn't get those popups. I tried a bunch of different firewall settings, reinstalling, and it's still flashing "starting", "stopped", "starting", "stopped"...

**Comment by cynecx** [comment]
You might wanna try disabling the firewall. Just to make sure that the firewall might be the issue here.

**Comment by ryendu** [comment]
Tried that. Tried that, then reinstalled it, doesn't work.

**Comment by erotte** [comment]
try `softwareupdate --install-rosetta` even it has been installed before. This fixed a similar problem for me.

**Comment by ryendu** [comment]
still doesn't work :/

**Comment by erotte** [comment]
try to delete everything that is docker-related as mentioned here:
https://github.com/docker/for-mac/issues/5477#issuecomment-804064830
There might be more stuff to delete, just search for it.  Or try something like AppCleaner, a free uninstall tool to delete all preferences, settings and caches.

**Comment by nnerijuss** [comment]
have exactly same issue.

**Comment by dumy0630** [comment]
我有同样的问题，到目前为止已经解决了。您可以尝试通过在系统偏好设置共享中关闭Internet共享来解决此问题（如果您打开Internet共享）

**Comment by ryendu** [comment]
@dumy0630 谢谢您！解决了！(Thanks! It Worked! ). For those (most) who can't read chinese: @dumy0630 suggested to go to system preferences and turn off internet sharing.

**Comment by ryendu** [comment]
Should this issue be closed?

**Comment by cynecx** [comment]
@ryendu Fun fact, that is a known issue. They mentioned it here: https://docs.docker.com/docker-for-mac/apple-m1/ 😄 

> Docker Desktop is incompatible with macOS Internet Sharing. See docker/for-mac#5348.
