### ISSUE TITLE
feature request: may I change QEMU cpu features of M1 docker? 

### ISSUE THREAD

**Issue by lispc** [docker/for-mac#5485]
- [x] I have tried with the latest version of Docker Desktop

### Expected behavior

I hope I can adjust QEMU cpu features different from the default on Apple M1 running x86_64 docker image. The current default setup does not support AVX/ADX/BMI2 instructions, which is quite useful for us.

### Information

  - macOS Version: Big Sur 11.2.2
  - Docker Desktop Version: 3.3.0 preview

### Steps to reproduce the behavior

```
docker run -t -i --rm  --platform linux/amd64 debian:buster-slim cat /proc/cpuinfo|grep Features

Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs
```
Hope these features can be adjusted by changing some docker config file.

**Comment by stephen-turner** [comment]
As of 3.3.2, we are now calling qemu with `-cpu max`, which should solve your problem.

**Comment by MohitKumar1991** [comment]
I am not able to run CUDA or TensorFlow on Docker on Mac M1 because of AVX support. Is there a fix yet ?
