### ISSUE TITLE
Docker crash on macOS 10.12

### ISSUE THREAD

**Issue by proea** [docker/for-mac#549]
### Information

Diagnostic ID: 3B41532E-0E46-4F47-92B8-D9F7CA0DC96D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A319)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/evgenij/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/3B41532E-0E46-4F47-92B8-D9F7CA0DC96D/20160908-145639/qemu-img-check.stdout 2> /tmp/3B41532E-0E46-4F47-92B8-D9F7CA0DC96D/20160908-145639/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Hi @proea  This should be fixed in beta 25. If you are willing to try the beta version, it is available here: https://download.docker.com/mac/beta/Docker.dmg 

We will move it to stable soon.

**Comment by proea** [comment]
no... 
the problem is still there

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by proea** [comment]
Fine! it working :)
