### ISSUE TITLE
The operation couldn’t be completed. (Docker.SettingsError error 0.)

### ISSUE THREAD

**Issue by vlad2705** [docker/for-mac#5490]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A163BF2E-751A-4A3E-88F9-62CA1549D992/20210322155252

### Expected behavior
Docker works after the installation
### Actual behavior
Docker doesn't work after the installation.
Error: The operation couldn’t be completed. (Docker.SettingsError error 0.)
### Information

  - macOS Version: Big Sur
  - Docker Desktop Version: Docker Desktop RC 1

### Steps to reproduce the behavior

  1. Download the latest version from this web: https://docs.docker.com/docker-for-mac/apple-m1/
  2. Install docker
  3. Click on Docker.app

**Comment by pranksteess** [comment]
Same here.
![image](https://user-images.githubusercontent.com/3785613/112428320-f2da1280-8d75-11eb-80cb-050d1d56524b.png)

**Comment by vlad2705** [comment]
This error was fixed in a new docker version 3.3.0
