### ISSUE TITLE
Docker-compose with SQL init file not working (on M1 Mac)

### ISSUE THREAD

**Issue by nicolashedoire** [docker/for-mac#5491]
### My problem

My problem is the following, the script to create a database and create a user root does not seem to be running on a MacBook pro with an M1 chip ... I tested this configuration on a MacBook Pro with a 2.4 GHz Intel Core i5 processor and everything is working fine.

Thanks for your help

### Information
 - macOS Version: Big Sur
- Docker Desktop Version: Docker Desktop RC 1

### Steps to reproduce the behavior
- Download the latest version from this web: https://docs.docker.com/docker-for-mac/apple-m1/
- Install docker
- Run Docker compose command => docker-compose down --remove-orphans && docker volume prune -f && docker network prune -f && docker-compose up -d --build

### Files to reproduce

`# docker-compose.yml

version: '3.7'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password **--init-file /data/application/setup.sql**
    volumes:
      **- .docker/setup.sql:/data/application/setup.sql**
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST='%' 
    restart: always
    container_name: mysql`

setup.sql file 

`-- create the users for each database
CREATE USER 'root'@'%' IDENTIFIED BY 'root';
ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS testForDocker;
`

**Comment by stephen-turner** [comment]
The mysql container doesn't run correctly on M1 chips. We have documented this at https://docs.docker.com/docker-for-mac/apple-m1/#known-issues
