### ISSUE TITLE
HTTPS Proxy through VPN tunnel doesn't work on M1 version 3.3.1

### ISSUE THREAD

**Issue by bpresles** [docker/for-mac#5492]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Proxy settings allows to connect to HTTPS proxy binded to local port through SSH tunnel

### Actual behavior

I tried to use a proxy with latest RC1 version for M1, and when I do a "docker login" I get:
`Error response from daemon: Get https://<registry_url>/v2/: Bad Gateway`

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0 RC3 M1 build

### Steps to reproduce the behavior

Requirements: Having a Docker registry only accessible through a proxy. Having a proxy only accessible through a SSH tunnel when outside of office.

1. Start a SSH tunnel binding HTTPS proxy to a local port (local port forwarding)
2. Open Docker Desktop preferences
3. Go to Resources -> Proxies and enter HTTP/HTTPS proxy settings (ex: https://localhost:1234)
4. Try to login to Docker registry using `docker login` command

**Comment by bpresles** [comment]
Btw I tested on RC2 with both qemu and virtualization.framework back end, and in both case the "Bad gateway" error is present.

**Comment by djs55** [comment]
@bpresles thanks for your report. Could you reproduce the problem and then upload diagnostics from: whale menu -> Troubleshoot -> Get Support? If you quote the diagnostics ID here then I can take a look at the logs, which might help understand the problem. Thanks in advance!

**Comment by bpresles** [comment]
> If you quote the diagnostics ID here then I can take a look at the logs, which might help understand the problem.

At this time I get a Internal server error when I upload the diagnostic, so I can't provide a diagnotic ID. But I retrieved the report as a zip file that you can find attached.

[Uploading 20210408074424.zip…](Diagnostic)

**Comment by bpresles** [comment]
I still can't upload diagnosis on final 3.3.1 so I attach the diagnosis archive
[20210426082317.zip](https://github.com/docker/for-mac/files/6375421/20210426082317.zip)

**Comment by bpresles** [comment]
My bad it was a configuration issue (using HTTPS instead of HTTP) in my case. Closing the issue so.
