### ISSUE TITLE
Docker Desktop 3.2.2 for Mac is extremely slow

### ISSUE THREAD

**Issue by jmaha** [docker/for-mac#5494]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: DE55F35C-EB22-47C4-9F41-43CDBE514C98/20210323172521

### Expected behavior

I upgraded from Docker 2.5.0.1 to the new 3.2.2. I expected performance, load times etc. to be the same or better.

### Actual behavior

All container operations are significantly slower. `docker-compose build` takes 2-3x as long, bringing up our Rails containers is much slower, initial page load time is probably 2-3x as long. I tried to run our automated test suite, which took 18 minutes on 2.5.0.1, and on 3.2.2 it timed out after 60 minutes, with numerous test failures along the way due to timeouts during the tests.

### Information

  - Is it reproducible? Yes, every time
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, with the update to 3.2.2
  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior

  1. Do any container operations in Docker Desktop 3.2.2 (docker-compose build, docker-compose up, etc.).
  2. Observe the extremely slow behavior relative to 2.5.0.1.

**Comment by chriscasola** [comment]
When I have no containers running, but docker desktop is running, the `com.docker.backend` process is using 100% cpu continuously. This also wasn't an issue before upgrading to 3.2.2.

**Comment by jmaha** [comment]
I just reverted to 2.5.0.1 and it's working as expected.

**Comment by ollydixon** [comment]
@jmaha where can I download the old version?

**Comment by jmaha** [comment]
Each version has a download link: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by spannersuk** [comment]
I am having the same issue.  Upgrading to 3.2.2 has slowed my image load and build times by a factor of 10x

Currently running on BigSur 11.2.  Upping the amount of memory and cores available has alleviated it somewhat but still terrible performance.

**Comment by craigds** [comment]
I also have the same problem; I've tried upgrading to 3.x several times since it was originally released, but each time the performance is so abysmally bad I've had to downgrade to 2.5.0.1.

3.3.1 is no exception, it's still awfully slow. 

I haven't noticed high CPU usage though, and `docker stats` also shows very little activity. It's as if docker 3.x is throttling itself to 0.1 cores or something.

**Comment by craigds** [comment]
/remove-lifecycle stale

This is certainly still a problem; multiple coworkers have had the same issue in the last week. I'll try and provide some diagnostic info on Monday in case that helps someone look into it
