### ISSUE TITLE
Networking not working with Nginx container 

### ISSUE THREAD

**Issue by mohsen1** [docker/for-mac#5496]
I create a repository that demonstrate this issue here

https://github.com/mohsen1/docker-m1-nginx

Running the same code on my Intel based Mac works but on my M1 Mac networking doesn't seem to work. The nginx container is flooded with 500 calls because it is trying to reach out to itself. It makes an infinite call loop. 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Sorry can not upload diagnostics at this time

### Expected behavior
M1 Mac networking should work

### Actual behavior
SSH'ing into the container I see the following weird issues:

```
# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

```
# curl node.mynet
lookup node.mynet on 192.168.65.5:53: no such host
```

The logs on the nginx container is flooded with 500 errors. 
### Information

  - macOS Version: 11.2.3 (20D91)
  - Docker Desktop Version: 3.3
  - Docker Engine 20.10.5
  - Docker Compose 1.28.5

### Steps to reproduce the behavior
Clone this repo and run the docker config in your M1 mac:

https://github.com/mohsen1/docker-m1-nginx

Then visit `http://localhost`

**Comment by mohsen1** [comment]
This issue is resolved by the release mentioned in this comment 
https://github.com/docker/for-mac/issues/5476#issuecomment-804793593

**Comment by stephen-turner** [comment]
Thanks, I'll close this ticket as a dupe.
