### ISSUE TITLE
Handling "useCloudCli" after removing the preference from the UI

### ISSUE THREAD

**Issue by navneetkarnani** [docker/for-mac#5497]
I have two users configured on my Macbook Air with BigSur.

On user1, which is also an admin, I am able to run the `docker compose` command, and hence the `docker context create ecs my_ecs` too.
But, when I login as user2, which is a standard user, when I run `docker compose`, I see the following error:
```
docker: 'compose' is not a docker command.
See 'docker --help'
```

And also, when I try to run `docker context create ecs my_ecs`, I see the following error:
```
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.
Usage:  docker context create [OPTIONS] CONTEXT
Create a context
```

The docker version command output is:
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Based on my interaction on Slack, and with the support team, here is the solution to the issue:
---

Stefan Scherer (Docker Support) Mar 23, 2021, 12:23 PDT 

Hello,your docker version output looks like that you don't have the cloud experience enabled. 

The output should show the Cloud integration as well, example:
```$ docker version
Client: Docker Engine - Community 
Cloud integration: 1.0.9 
Version:  20.10.5 
API version:  1.41 
Go version: go1.13.15 
Git commit: 55c4c88 
Built:  Tue Mar 2 20:13:00 2021 
OS/Arch:  darwin/amd64 
Context:  default 
Experimental: true
```

In the version of Docker Desktop you have we've removed that option from the preferences UI, but maybe you had it disabled before an update.

A hard way to do that would be to do a factory reset.If you want to keep your containers and images, you have to edit the settings file directly and stop and start Docker Desktop.

The file is in `~/Library/Group\ Containers/group.com.docker/settings.json` and the configuration must contain `"useCloudCli" : true,`

Hope that helps you to enable the ECS integration.
--

I had not "disabled" the setting before upgrading the docker version, just that I had enabled it on only user1. Before I could get to user2, and enable it, I had already upgraded the version of docker-desktop, and that removed the setting from the UI, so I did not realise I had to make the change.

Suggestion:
Either put the setting back in the UI, or remove the option to turn it off from the setting file. Because it is very confusing to see it and still not see it :)

**Comment by StefanScherer** [comment]
Thanks for filing the issue for visibility. We‘re working on a fix.
