### ISSUE TITLE
docker-compose up fails with "TypeError: log_timeout_error() takes exactly 1 argument (0 given)"

### ISSUE THREAD

**Issue by saikojosh** [docker/for-mac#550]
### Expected behaviour
Containers to boot up.

### Actual behaviour
The following is displayed in the console and the containers do not boot:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
```

### Information

Diagnostic ID: 80C34EA5-FB4D-4053-977C-EAB3F8C758F7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Run `docker-compose up`.
2. This seems to happen randomly.

**Comment by adamgoose** [comment]
I get the same thing after running `docker-compose up`, `docker-compose logs -f` and even `docker logs CID`

**Comment by dsheets** [comment]
Could you provide a `docker-compose.yml` file which triggers this problem for you? It would be very helpful in tracking down the cause and preparing a fix.

**Comment by mchiang0610** [comment]
Merging with #119 as well. @saikojosh If you get a chance, we'd love to get the compose file from you to reproduce this.

**Comment by samoht** [comment]
Detected symptom of problem 'moby-kernel-froze' in 80C34EA5-FB4D-4053-977C-EAB3F8C758F7/20160908-130910.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Sep  1 23:23:05 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Notice>: vcpu 0 received signal, resuming
Sep  1 23:23:05 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Notice>: vcpu 1 received signal, resuming
Sep  1 23:23:05 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Notice>: vcpu 2 received signal, resuming
Sep  1 23:23:05 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Notice>: vcpu 3 received signal, resuming
Sep  1 23:23:08 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Error>: VM: 2016-09-01 17:43:46 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep  1 23:23:08 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Error>: VM: 2016-09-01 17:43:46 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep  1 23:23:08 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Error>: VM: 2016-09-01 17:43:46 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep  1 23:23:08 ColeyMBPR Docker[com.docker.driver.amd64-linux][22248] <Error>: VM: 2016-09-01 17:43:46 +0000 UTC kern.error kernel: 	1-...: (1 ticks this GP) idle=d81/1/0 softirq=1514126/1514126 fqs=0
```
