### ISSUE TITLE
Apple Silicon: `dockerd panic: invalid freelist page: 0, page type is unknown<00>`

### ISSUE THREAD

**Issue by marcj** [docker/for-mac#5502]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
I can not create a diagnostics nor can I change Docker settings since the app crashes.

### Expected behavior

Docker starts fine on Macbook air m1 with newest MacOS 11.2.3 version.

### Actual behavior

I started recently getting weird error messages in docker build and decided to update Docker (since it displayed in the toolbar that an update is available). After that update today I'm unable to start Docker.

After starting Docker, I see this screen:

<img width="1362" alt="Screenshot 2021-03-25 at 00 31 55" src="https://user-images.githubusercontent.com/450980/112397237-faf86a80-8d01-11eb-9c09-50fb6bfc2e34.png">

Then I get this error:

<img width="710" alt="Screenshot 2021-03-25 at 00 32 24" src="https://user-images.githubusercontent.com/450980/112397259-051a6900-8d02-11eb-98d4-7017c0d6edf0.png">

```
2021-03-24T21:07:28Z dockerd panic: invalid freelist page: 0, page type is unknown<00>
2021-03-24T21:07:28Z dockerd 
2021-03-24T21:07:28Z dockerd goroutine 1 [running]:
2021-03-24T21:07:28Z dockerd github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).read(0x4000172180, 0xffffb80c1000)

2021-03-24T21:07:41Z dockerd panic: invalid freelist page: 0, page type is unknown<00>
2021-03-24T21:07:41Z dockerd 
2021-03-24T21:07:41Z dockerd goroutine 1 [running]:
2021-03-24T21:07:41Z dockerd github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).read(0x4000050500, 0xffffb0275000)

2021-03-24T21:07:55Z dockerd panic: invalid freelist page: 0, page type is unknown<00>
2021-03-24T21:07:55Z dockerd 
2021-03-24T21:07:55Z dockerd goroutine 1 [running]:
2021-03-24T21:07:55Z dockerd github.com/docker/docker/vendor/go.etcd.io/bbolt.(*freelist).read(0x40000cc200, 0xffff9cdee000)

....
```

It is flooded with those error messages (always the same error).

After clicking on Diagnose & Feedback this crashes as well:

<img width="832" alt="Screenshot 2021-03-25 at 00 32 27" src="https://user-images.githubusercontent.com/450980/112397328-2a0edc00-8d02-11eb-8cb6-4b90a79f9629.png">

The screen stays that way forever.

The about window says (if that helps):

<img width="872" alt="Screenshot 2021-03-25 at 00 34 14" src="https://user-images.githubusercontent.com/450980/112397365-372bcb00-8d02-11eb-8f06-dea4486387cb.png">

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0

I'm using a Macbook air with Apple Silicon from 2020.
<img width="259" alt="Screenshot 2021-03-25 at 00 37 30" src="https://user-images.githubusercontent.com/450980/112397399-490d6e00-8d02-11eb-9e7c-92a6768c36ed.png">

I was using Docker Preview for Apple silicon for weeks without issue. Only today this started. I tried uninstalling and reinstalling Docker completely, restarted the Macbook etc, but nothing helped.

**Comment by jspark-gigworks** [comment]
I have the same issue.
And I have reinstalled rosetta2 and don't use internet sharing.

**Comment by djs55** [comment]
@marcj thanks for your report. The error from `bbolt` via `dockerd` suggests some kind of corruption of the VM disk. I'm surprised that uninstall and reinstall didn't fix it :( Perhaps try removing the disk image file directly and then restarting Desktop:
```
rm ~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw 
```
(All containers and images will need to be rebuilt afterwards).

If that fails I have an experimental build you could try: https://desktop-stage.docker.com/mac/stable/arm64/62178/Docker.dmg

**Comment by felri** [comment]
Same problem, I can run following @djs55 step of removing that file but the docker does not behave normally and breaks my app, is there a way to rollback to 3.1 ?

**Comment by codigonet** [comment]
Hi, I've resolved my issues with RC 2: 
https://docs.docker.com/docker-for-mac/apple-m1/

Steps:
- Kill docker processes
- Remove Docker Library and Caches from ~/Library
- Install RC 2 version

It works great to me!!!

**Comment by marcj** [comment]
Cool, after deleing that Docker.raw and reinstalling newest Docker RC 2 from 2021-03-26 everything works again. Thanks!

**Comment by djs55** [comment]
I think RC 2 has fixed the core problem. If anyone is still having problems, could you open a fresh ticket? Thanks!
