### ISSUE TITLE
 The latest version of the docker preview (for M1 mac) doesn't start

### ISSUE THREAD

**Issue by JoDarma** [docker/for-mac#5504]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DEF161C3-3F70-498A-A7F9-F6A6EFB5410C/20210325092526

### Expected behavior
Docker should start

### Actual behavior
Docker doesn't start, status stay in "Docker Engine starting..." and never start.

### Information

  - macOS Version: Mac OS Big Sur 11.2.3
  - Docker Desktop Version: 3.3.0(62029)

### Steps to reproduce the behavior

  1. Download last version of docker preview for M1 mac
  2. Start docker
  3. See "Docker Engine starting..." doesn't change 
  4. launch "docker ps" on terminal and see this error "Error response from daemon: dial unix docker.raw.sock: connect: connection refused"

**Comment by sgpopov** [comment]
@JoDarma I've experienced the same issue today. What worked for me was to remove docker completely from the machine following [these steps](https://github.com/docker/for-mac/issues/5426#issuecomment-791622494). Then I've installed the latest version (3.3.0(62029)) and everything works.

**Comment by JoDarma** [comment]
> @JoDarma I've experienced the same issue today. What worked for me was to remove docker completely from the machine following [these steps](https://github.com/docker/for-mac/issues/5426#issuecomment-791622494). Then I've installed the latest version (3.3.0(62029)) and everything works.

Thanks for your response, it's work for me too.
