### ISSUE TITLE
EDGE URLS and EDGE_SSL URLS are red and page loads with 404 error

### ISSUE THREAD

**Issue by HeatherC747** [docker/for-mac#5505]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A4FB174C-A828-4DA4-8FCA-3F877359F160/20210325150006

### Expected behavior
EDGE URLS and EDGE_SSL URLS are green

### Actual behavior
EDGE URLS and EDGE_SSL URLS are red and page loads with 404 error.

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 20.10.5

### Steps to reproduce the behavior
  1. Lando start
  2. Starts successfully, but the EDGE_SSL URLS and EDGE URLS are red and the page loads with 404 error.

**Comment by stephen-turner** [comment]
I'm not sure what it means for the URLs to be red. Are you sure this isn't a Lando bug rather than a Docker bug?

**Comment by HeatherC747** [comment]
@stephen-turner  Thanks for your response!  Here is an imgur screenshot: https://imgur.com/a/uFQoi5E
Could very well be a lando issue..  But I have this brand new apple M1 machine, and my previous computer (Intel, not M1) ran docker/lando just fine, no issues.  So thats why I'm inclined to think it has something to do with the M1 processor Docker Desktop for Apple Silicon.

**Comment by stephen-turner** [comment]
Oh, you didn't say this was M1. Maybe you're trying to run an Intel-based container on your M1 machine, which may or may not work successfully. You should use an arm64 container image.

**Comment by HeatherC747** [comment]
@stephen-turner  Ok I can try that, can you tell me how to do that?  I use docker with pantheon & lando and it's pretty automated.

**Comment by stephen-turner** [comment]
What is the underlying container (or containers) you're running? You can look on hub.docker.com what architecture it's built for and whether there's an arm64 version available. If not, the only remedy is to ask the container author to build a container image for arm64.

**Comment by djs55** [comment]
@HeatherC747 Could you try again with the RC 2 build listed here: https://docs.docker.com/docker-for-mac/apple-m1/ . The RC 2 build contains a fix for a bug where inter-container traffic was erroneously forwarded to an HTTP proxy on the host, which could cause general chaos. I notice the HTTP proxy logs in the diagnostics have:
```
2021-03-25T14:45:56Z http-proxy time="2021-03-25T14:45:56Z" level=info msg="GET http://localhost:49426/"
2021-03-25T14:45:56Z http-proxy 2021/03/25 14:45:56 [160] INFO: Got request / localhost:49426 GET http://localhost:49426/
2021-03-25T14:45:56Z http-proxy 2021/03/25 14:45:56 [160] INFO: Sending request GET http://localhost:49426/
2021-03-25T14:45:56Z http-proxy 2021/03/25 14:45:56 [160] INFO: Received response 400 Bad Request
```
where `http://localhost:49426` is one of the red URLs in the screenshot.

If it still fails with RC 2, could you upload another set of diagnostics and I'll take another look at the logs.

Thanks in advance!
