### ISSUE TITLE
Docker stuck in "starting" with com.docker.backend using >100% CPU

### ISSUE THREAD

**Issue by harrouet** [docker/for-mac#5507]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Can't upload diagnostics: the diagnostics report is properly generated but uploading it generates an "Internal server error". I have the report, let me know how I may send it manually.

![Screenshot 2021-03-25 at 21 49 39](https://user-images.githubusercontent.com/1290150/112541752-0dcb7780-8db4-11eb-885c-13c952a89f7d.png)

[EDIT]
Running the terminal command for diagnostics `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload` gives the following error:
```
INFO[0033] Error writing:  Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/C1FC853F-51F9-4CFF-90BD-A03155218693/20210326074521.zip": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25295 
Error uploading: Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/C1FC853F-51F9-4CFF-90BD-A03155218693/20210326074521.zip": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25295
``` 

This leads to a certificate error. Docker not starting may also be linked to certificate issues. 

### Expected behavior
start Docker
### Actual behavior
Docker remains in "starting..." with com.docker.backend eating up more than 100% CPU.
The `Preferences` menu remains unaccessible. 
 
### Information

  - macOS Version: 10.15.7 (Catalina)
  - Docker Desktop Version: Docker 3.2.2 (lastest)

### Steps to reproduce the behavior

  1. start Docker
  2. wait hours, wait, wait again. Remains in "starting..."

**Comment by ankurpshah** [comment]
Same here.

**Comment by mateka** [comment]
Same here on M1 mac.

**Comment by dhinojosa** [comment]
Same here.

**Comment by grantkee** [comment]
Same here.
