### ISSUE TITLE
Error after install Docker for Mac

### ISSUE THREAD

**Issue by debersom** [docker/for-mac#551]
### Information

Diagnostic ID: 7DB0C3CB-5505-425C-9AC6-D67C93E29D78
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/debersom/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/7DB0C3CB-5505-425C-9AC6-D67C93E29D78/20160908-105639/qemu-img-check.stdout 2> /tmp/7DB0C3CB-5505-425C-9AC6-D67C93E29D78/20160908-105639/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Analysing archive 7DB0C3CB-5505-425C-9AC6-D67C93E29D78/20160908-105715
--------------------------------------------------------------------------------
Detected symptom of problem 'more-than-one-hyperkit' in 7DB0C3CB-5505-425C-9AC6-D67C93E29D78/20160908-105715.

More than one hyperkit process has started and is accessing the qcow2 disk at the same time. This will lead to corruption and Docker must be reset to factory defaults.

May be related to docker/for-mac#71
