### ISSUE TITLE
docker don't start after upgrade

### ISSUE THREAD

**Issue by kempertrasdesclub** [docker/for-mac#5510]
Hi.

After shutdown Mac, Bug Sur 11.2.2 Mac Pro 16GB of RAM - 13 inch M1 2020, I am need uninstall and purge docker; re-install and work.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D89B0E78-BE94-45A7-BCBF-8D9002C7833E/20210326141449

  - Is it reproducible? 
  yes, shutdown Mac

  - Is the problem new?
  yes, after upgrade to 3.3.0 (62029)
  - Did the problem appear with an update?
  yes
  - A reproducible case if this is a bug, Dockerfiles FTW.
  dont apply

  - macOS Version:
  Bug Sur 11.2.2 Mac Pro 16GB of RAM - 13 inch M1 2020
  - Docker Desktop Version:
  engine: 20.10.5
  compose: 1.28.5
  kubernets: v1.18.7
  Notary: 0.6.1
  Credential Helper: 0.6.3
  Snyk: v1.432.0

### Steps to reproduce the behavior

Install
shuntdown Mac
start Mac

**Comment by felri** [comment]
Same here

**Comment by emonorg** [comment]
Same here!

**Comment by danielbryantuk** [comment]
I've got the same issue (second time in a month). This looks like an automatic upgrade failure, as previously I manually rolled back to 3.1.0 and everything worked again:

Diagnostics ID:     9C4066E3-3FE1-4B50-B9D5-43FC5582DF54/20210330124020 (uploaded)

**Comment by dhinojosa** [comment]
3.1.0 works for me on mac as well.

**Comment by minkbear** [comment]
3.1.0 works as expects.

**Comment by DLevai94** [comment]
Same issue here with M1 Mac. But 3.1.0 downloaded from the first comment doesn't even start or install `docker` command.

**Comment by emonorg** [comment]
Same as you! Even 3.1.0 didn't solve it.

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still issues in the latest version, please open a new ticket with diagnostics.
