### ISSUE TITLE
Docker Dashboard and docker context

### ISSUE THREAD

**Issue by casperghst42** [docker/for-mac#5512]
Hi,

I don't know if this is the right forum, but it would be really nice if Docker Dashboard would work with context's.

Cheers.

**Comment by stephen-turner** [comment]
Thanks for the feedback. We do have a roadmap item at docker/roadmap#47 for support for contexts in Docker Desktop. It was primarily about switching contexts from the UI but I've just added a note into it that we should also think about switching the dashboard when the context changes. Feel free to give that ticket a 👍, that's how we determine what people most want us to work on next.
