### ISSUE TITLE
M1: cURL error 77: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by rolandfa** [docker/for-mac#5518]
- [X ] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I am able to authenticate to oauth services using POST requests as was working in Tech Preview 7.

### Actual behavior
I am running PHP, Nginx and Laravel. When I connect to any oauth server using Guzzle I receive a CURL error #77. This happens when I try to connect to any oAuth service which I have tried Google Sheets and Ebay.

### Information

  - macOS Version: Big Sur 11.2.3
  - Docker Desktop Version: Docker M1 3.3.0 (62345) 
  Engine: 20.10.5
  Compose: 1.28.6
  Kubernetes 1.19.7
  Notary: 0.6.1
  Credential Helper: 0.6.3
  Snyk: 1.461.0

### Steps to reproduce the behavior
1. Upgrade to Docker for M1 3.3.0. 
2. Build your containers
3. When connecting to any oauth service you will get a curl error 77

When I downgrade to Tech preview 7 the code works with no problems. Only when upgraded to RC1 and RC2 did these problems start.

**Comment by djs55** [comment]
@rolandfa thanks for your report. Could you provide a small POST example that fails (perhaps using `curl -X POST` or similar)? It looks like error 77 means [there's a problem with the SSL cert](https://github.com/curl/curl/issues/3793). Could you repeat the `curl` with `-vvv` to see if it shows any more detail about what's wrong?

**Comment by nuttmeister** [comment]
We are experience the same issue all of a sudden authenticating. Certificate provided by AWS, error with 3.3.0 on both Intel and M1 macs.

**Comment by djs55** [comment]
@nuttmeister thanks for the report. Do you have a small repro example?

**Comment by djs55** [comment]
Just in case, perhaps try adding `--seccomp=disabled` in case it's in any way related to https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build/66385784#66385784 (highlighted by @thaJeztah )

**Comment by nuttmeister** [comment]
This is running alpine linux so no glibc. The example is a private repo unfortunately.
But we are using https://pypi.org/project/awscli-adfs/ dockerized using alpine and has been working for ~3 years and after upgrading to 3.3.0 no luck.

We have been updating it over the years, of course, but last update was pretty long ago.

The example below requires you to have AWS setup with SAML/ADFS of course.
But this will run up until the end of the auth flow and then just timeout after 30s and produce an SSL error.

`Dockerfile:`
```Dockerfile
FROM alpine:3.12

RUN apk --update --no-cache add python3 py3-pip
RUN pip3 install --no-cache-dir --upgrade pip awscli-adfs

ENTRYPOINT [ "aws-adfs" ]
```

`~/.aws/aws-adfs.toml:`
```text
[profiles.dev]
region = "eu-west-1"
output = "json"
idp_entry_url = "https://sso.example.com/adfs/ls/idpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices"
idp_username = "email@example.com"
idp_role_arn = "arn:aws:iam::111111111111:role/role-to-assume"
idp_session_duration = 43200
```

`Command:`
```bash
docker run --rm -it -v ~/.aws:/root/.aws aws-adfs login dev
```

So initiating the flow works, getting the MFA notification to Microsoft authenticator works.  
But when it has been acked and it tries to call AWS STS to assume the role it has started erroring out with the TLS error since 3.3.0.

Error:
```text
Hello, email@example.com！
You are logging in with profile(s): "dev"
Password:
A notification has been sent to your mobile device. Please respond to continue
Traceback (most recent call last):
  File "/usr/bin/aws-adfs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/aws_cli_adfs/cli.py", line 406, in login
    adfs_login(profiles, *key, save_password)
  File "/usr/lib/python3.8/site-packages/aws_cli_adfs/login.py", line 301, in adfs_login
    ) = parse_saml_resp(profiles, saml_resp)
  File "/usr/lib/python3.8/site-packages/aws_cli_adfs/login.py", line 225, in parse_saml_resp
    token = conn.assume_role_with_saml(
  File "/usr/lib/python3.8/site-packages/boto/sts/connection.py", line 492, in assume_role_with_saml
    return self.get_object('AssumeRoleWithSAML', params, AssumedRole,
  File "/usr/lib/python3.8/site-packages/boto/connection.py", line 1192, in get_object
    response = self.make_request(action, params, path, verb)
  File "/usr/lib/python3.8/site-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/lib/python3.8/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
  File "/usr/lib/python3.8/site-packages/boto/connection.py", line 942, in _mexe
    connection.request(request.method, request.path,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/boto/https_connection.py", line 128, in connect
    self.sock = ssl.wrap_socket(sock, keyfile=self.key_file,
  File "/usr/lib/python3.8/ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
```

**Comment by thaJeztah** [comment]
@nuttmeister are you able to modify the `docker run` in your situation? Still interested if it could be seccomp related; we had some issues with seccomp in various situations (miss-match kernel <--> container distro, etc). It may _definitely_ be unrelated, but would be a good datapoint to have, so

Oh! I see I mentioned the wrong option; it should be `--security-opt seccomp=disabled` (not `--seccomp`)

```
docker run --rm -it --security-opt seccomp=disabled -v ~/.aws:/root/.aws aws-adfs login dev
```

**Comment by nuttmeister** [comment]
@thaJeztah guessing you mean `--security-opt seccomp=unconfined` perhaps?
Same result with the option above.

**Comment by djs55** [comment]
One possibility is a problem with the transparent HTTPS proxy.

Perhaps try setting an explicit proxy in the container with:
```
/ # export http_proxy=http.docker.internal:3128
/ # export https_proxy=http.docker.internal:3128
```
With an explicit proxy set I would expect the client to make an `HTTP CONNECT` request to the proxy, which would then connect to the origin server (or upstream proxy) and proxy bytes back and forth.

**Comment by nuttmeister** [comment]
@djs55 when adding the following to my Dockerfile.

```Dockerfile
ENV HTTP_PROXY http://http.docker.internal:3128
ENV HTTPS_PROXY http://http.docker.internal:3128
```

I'm still seeing the same issue. But for example using both wget and curl works for fetching simple webpages over TLS.
If I set the proxy to an invalid I can see it errors out on `HTTP CONNECT` so the error seems to be with TLS somehow.

I do the authentication flow straight through curl in the docker image to see if I get the same results or if it's more related to python/boto3 etc.

But don't know if i will manage much more today.

**Comment by nuttmeister** [comment]
An update, the plot thickens.

Wrote a simple go program to do the SAML login and it works just as expected and doesn't fail on the step the our python package does.

Tested on `alpine:3.12` and `debian:buster` with and without `netcgo`.

So seems more like the client poster is using and python in combination with the new release. Will dig deeper tonight.

**Comment by nuttmeister** [comment]
Yeah, seems to be how the `boto` package (in this case) handles connections and making requests.
Might not have time to debug further tonight though. But will enable debugging in boto and dive deeper into it tomorrow to see where it fails.

But making requests outside of boot, using for example `requests` package works fine.

**Comment by nuttmeister** [comment]
Guessing this is related to #5568

Haven't had time to debug further, but feels very related tbh.

**Comment by rolandfa** [comment]
Duplicate of #5912 and related to #5568
