### ISSUE TITLE
Upgrade blocked by AntiVir

### ISSUE THREAD

**Issue by guenhter** [docker/for-mac#552]
### Steps to reproduce

1. Update And Relaunch with Avast AntiVir Scanner on Mac

### Expected behavior

Successful upgrade

### Actual behavior

Update Successfully downloaded but after extracting, the dialog of the antivir scanner pops up.
The Docker Dialog for "install and Relaunch" is available but when I click it, the Dialog with "Update Error!" appears.

Attached is a image with the blocking message.

<img width="337" alt="block" src="https://cloud.githubusercontent.com/assets/16029571/18353114/2bfdd8dc-75e1-11e6-854a-985515b200a6.png">

### Information

```
Diagnostic ID: 5625FD61-BF8E-477E-BC7D-738B4ED03F1F
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
merging with #543
