### ISSUE TITLE
Docker's Icon is the only round icon in my Dock

### ISSUE THREAD

**Issue by simoncpu** [docker/for-mac#5536]
### Expected behavior
The Human Interface Guidelines state that the app icon should be square with no round corners.

### Actual behavior
Docker's icon is round.

### Information
  - macOS Version: macOS Big Sur 11.2.3
  - Docker Desktop Version: 3.3.0 (62632)

**Comment by djs55** [comment]
@simoncpu thanks for your report! I've created a ticket and added it to our backlog.

**Comment by niccolomineo** [comment]
It should be pointed out that the icon is not a square, but, rather, a squircle. Apple's been quite clear about this.

**Comment by niccolomineo** [comment]
Hi, any updates on this?

Thank you.

**Comment by niccolomineo** [comment]
Since 3.4.0 didn't bring the new icon, I made my own. Feel free to use it.

[docker_desktop.icns.zip](https://github.com/docker/for-mac/files/6625922/docker_desktop.icns.zip)

**Comment by niccolomineo** [comment]
Since 3.4.0 didn't bring the new icon, I made it myself. Feel free to use it.

https://www.figma.com/file/uhytxqvq1PQgOfpOQGshn2/Docker-macOS-Big-Sur-Icon?node-id=0%3A1

![Icon-1024](https://user-images.githubusercontent.com/5409469/121491549-57e8f000-c9d6-11eb-9481-1824f7bd03bc.png)

**Comment by niccolomineo** [comment]
Since 3.4.0 didn't bring the new icon, I made it myself. Feel free to use it.

https://www.figma.com/file/uhytxqvq1PQgOfpOQGshn2/Docker-macOS-Big-Sur-Icon

<img width="279" alt="icon_context" src="https://user-images.githubusercontent.com/5409469/121491632-6b945680-c9d6-11eb-9d9e-f21ab0590f28.png">

**Comment by aluneed** [comment]
> Since 3.4.0 didn't bring the new icon, I made it myself. Feel free to use it.
> 
> https://www.figma.com/file/uhytxqvq1PQgOfpOQGshn2/Docker-macOS-Big-Sur-Icon
> 
> <img alt="Schermata 2021-06-10 alle 17 49 30" width="228" src="https://user-images.githubusercontent.com/5409469/121556579-4aeaf180-ca14-11eb-8e83-89d2754782a1.png">

looks much better than the official one.

**Comment by mrleblanc101** [comment]
When can we expect Docker to update the app icon to respect the macOS guideline ?
The change has been announced more than a year ago and this feels like a change that would only take a few minutes if someone actually cared to execute this task.

**Comment by niccolomineo** [comment]
I am attaching the icon set in the various sizes.
[Docker macOS Big Sur Icon.zip](https://github.com/docker/for-mac/files/6984615/Docker.macOS.Big.Sur.Icon.zip)

**Comment by niccolomineo** [comment]
👀

**Comment by desmortum** [comment]
More and more apps getting new icons. Very excited to see new icon aligned with new guidelines.

**Comment by desmortum** [comment]
Docker has old icon for year now after Big Sur release. It introduces kind of inconsistency with other icons. It will be great to see new icon aligned with guidelines.

**Comment by desmortum** [comment]
@djs55, any news?

**Comment by gk-brown** [comment]
I logged in just to find/upvote or create this issue, if it did not already exist. I installed Docker Desktop for macOS yesterday and love it so far. But I would like to see the icon updated for consistency with current Apple guidelines.

**Comment by prksu** [comment]
still has a round icon in 4.5.0 (74594) 😞

**Comment by desmortum** [comment]
This is clearly ignored by some developers. In 2020 Apple released a new guidelines for macOS app icons tool like IOS one: a rectangles with rounded corners. Now that most apps got updated ones that didn't produce inconsistency in dock and Launchpad. It's been more than a year since guidelines were released.

**Comment by henriquemattos** [comment]
The [changelog for 4.8.0](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-480) says it was released, and points out this issue here, but it's still rounded on my macOS. Considering that Firefox Developer Edition also disrespect the guideline, I don't see it as a big drama. Although always in favor of respecting branding and styles.

<img width="692" alt="Screenshot 2022-05-06 at 10 46 07" src="https://user-images.githubusercontent.com/2782214/167108309-cf49cdea-6bf2-4d16-9253-49b776d699bf.png">
,

**Comment by desmortum** [comment]
Icon updated for me

**Comment by desmortum** [comment]
<img width="230" alt="Screen Shot 2022-05-06 at 12 06 23" src="https://user-images.githubusercontent.com/38209369/167111631-81434b22-3409-4e1f-a2cd-738de6c5061b.png">

**Comment by desmortum** [comment]
@djs55

**Comment by niccolomineo** [comment]
> I'm sorry for the misleading comment. I tried by restarting Docker and also by quitting and starting it again. And it didn't change.
> 
> I noticed I'm using **Monterey (macOS 12)** and **the icon is "only" for Big Sur (macOS 11)**. I tried to find documentation/guidelines from Apple, but it's only [mentioned macOS 11](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).
> 
> Given the native Apple's app icons (like Calendar, Mail, Messages...), I would say the guideline has been maintained. What do you think?

That would make no sense, yeah. Also, I have Monterey myself and the icon is there.

**Comment by desmortum** [comment]
@henriquemattos, I just finally installed Monterey and icon is correct. So I guess problem is on your machine. Try removing Docker.app from /Applications. Then drag new one from freshly downloaded *.dmg. Should not affect data or settings.

**Comment by desmortum** [comment]
<img width="662" alt="Screen Shot 2022-05-10 at 13 54 25" src="https://user-images.githubusercontent.com/38209369/167622476-a85a8c56-9ff0-408c-b3a8-87e30c555a6f.png">

**Comment by lorenrh** [comment]
I'm closing this issue, as a fix for this has been released on Docker Desktop 4.8.1!

**Comment by breiter** [comment]
While Docker.app has an icon, the embedded Docker Desktop.app does not. And so whenever I open Preferences or About or Check for updates...  from the menu bar icon -- anything that launches Docker Desktop.ap -- I get a broken icon in the dock. (This was also the case in 4.6.)

![Screen Shot 2022-05-12 at 08 35 50](https://user-images.githubusercontent.com/3965197/168007028-3f865923-ecaa-4f18-85ac-0e30d7f8dcd9.png)

![Screen Shot 2022-05-12 at 08 32 37](https://user-images.githubusercontent.com/3965197/168007048-9ae68e89-8a08-4840-9db7-83e0bdc9a4be.png)

**Comment by desmortum** [comment]
@breiter, hm. For me it's okay.
<img width="233" alt="Screen Shot 2022-05-12 at 09 32 49" src="https://user-images.githubusercontent.com/38209369/168016642-f9c96497-fe22-42e3-a7cb-b627574006b5.png">

**Comment by thaJeztah** [comment]
@breiter see https://github.com/docker/for-mac/issues/6249
