### ISSUE TITLE
Docker does not utilize CPU

### ISSUE THREAD

**Issue by venomone** [docker/for-mac#5537]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Full utilization of CPU when needed

### Actual behavior

If I start a couple containers (whole webstack) it seems that docker is not utilizing the M1 properly. Im always running at about 10-30% load. If I access my website on localhost the site needs a lot of time to properly load ...
Im absolutly dont have this behaviour on Linux. Beside it seems that docker-compose up  --build has the same behaviour and containers gettings stuck while building. If you wait long wnought the pass the process, so far so good but it's absolutely slow :(

And yes I gave the docker machine extra CPU and RAM (6 Cores and 10 GiB of RAM), does need seem to change a thing.

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0(62632)

### Steps to reproduce the behavior
Simply start more than 5 containers that communicate with each other.

**Comment by djs55** [comment]
@venomone thanks for your report. Could you upload diagnostics from the whale menu -> Troubleshoot -> Get Support and quote the ID here? This will allow me to look at the logs.

Are you running with `virtualization.framework` enabled or disabled? It might be worth trying the other mode to see if it makes any difference.

It's also worth checking your images are native `arm64` images. Although `amd64` images will run, they are emulated via [qemu user emulation](https://wiki.debian.org/QemuUserEmulation) which is slow and resource-intensive.

**Comment by venomone** [comment]
@djs55 ahh, good hint :D at least now all core spin up.
