### ISSUE TITLE
Docker (M1) hung after waking from sleep

### ISSUE THREAD

**Issue by thanks173** [docker/for-mac#5539]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After wake up from sleep, Docker containers should work like before.

### Actual behavior
Docker hung after waking from sleep.
Sometimes I can't even restart Docker. If that happens, the only way to start Docker again is to log out and log in again.

### Information
I found some other bug reports about this same error years ago, but still, I can't find the solution.

  - macOS Version: 11.2.3 (M1 chip)
  - Docker Desktop Version: 3.3.0 (62029)

### Steps to reproduce the behavior

1. Run containers
2. Put the computer to sleep
3. Wake the computer up

**Comment by blutopsy** [comment]
I'm having the same issue. 

I'm on the following.
 
macOS Version: 11.2.2 (M1 chip)
Docker Desktop Version: 3.3.0 (62029)

**Comment by stephen-turner** [comment]
I think this is obsolete, I'm going to close it. If there are still issues in the latest version, please open a new ticket with diagnostics.
