### ISSUE TITLE
couchbase image apple silicon

### ISSUE THREAD

**Issue by shulolo** [docker/for-mac#5540]
Hi everyone,

Sorry in advance if a similar subject was created (I did not find it, if it's the case).

I just migrate to an Apple M1 Macbook, and I would like to launch my application which use a couchbase docker image.

I installed the Apple silicon preview, I change my docker compose file, to add the platform option "linux/x86_64".
So I got the image, the container is created, but when it's launched, I got this error :

runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

I have already seen this error on others posts, but I did not find a solution.

So I need some help if someone has an idea?

Thank you.

**Comment by djs55** [comment]
@shulolo thanks for your report. Unfortunately running `amd64`/`x86_64` images on Apple Silicon requires using [qemu user emulation](https://wiki.debian.org/QemuUserEmulation) which is slow and a bit unreliable. The [Docker Desktop release notes](https://docs.docker.com/docker-for-mac/apple-m1/) include this as a known issue. The long term fix is to rebuild (or ask your upstream to rebuild) the image to be multiarch, supporting both `amd64` and `arm64`. I recommend contacting them to fix the issue. Unfortunately there's nothing else we can do to help at the moment :( I'll close the ticket now, sorry I couldn't be more help.
