### ISSUE TITLE
com.docker.hyperkit process consumes excessive memory every time I turn on my mac

### ISSUE THREAD

**Issue by akilthms** [docker/for-mac#5541]
<img width="688" alt="Screen Shot 2021-04-04 at 1 36 04 PM" src="https://user-images.githubusercontent.com/11198348/113521789-92568c80-9550-11eb-820c-48a9d10ac1aa.png">

Hi, 

I have had this particular issue with Docker/Docker Desktop for the past 6 months. Every day when I start up my machine this process **com.docker.hyperkit** consumes about 3 GB of memory. This happens despite not using docker nor having any containers running in the background. I've scoured the message  boards and have yet to find an adequate solution. Raising this issue for myself and others who are still experiencing this problem. 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:1B92CD3D-32B6-4D8B-A40D-7A0B75E93018/20210404212427

### Expected behavior
Docker should not consume resources when not running containers

### Actual behavior
Docker process com.docker.hyperkit consumes nearly 3 GB of memory daily on startup
### Information

  - macOS Version: MacOS BigSur version: 11.2.3
  - Docker Desktop Version: 3.2.2
  - DiagnosticID: 1B92CD3D-32B6-4D8B-A40D-7A0B75E93018/20210404212427

**Comment by stephen-turner** [comment]
Unfortunately your intuition is incorrect. It is impossible for the MacOS hypervisor framework to scale the amount of RAM up and down after it's started, so we have to reserve the amount of memory required up front. You can set the amount in the settings though.
