### ISSUE TITLE
 Out of memory (allocated 81072128) (tried to allocate 9768960 bytes)

### ISSUE THREAD

**Issue by hoanghaihazalora** [docker/for-mac#5542]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: Big Sur 11.2.3 (Chip M1)
  - Docker Desktop Version: 20.10.5 

### Steps to reproduce the behavior

  1. Run an application using php
  2. When getting records from mysql database the issue will occur.

**Comment by djs55** [comment]
@hoanghaihazalora thanks for your report. Unfortunately there is no "diagnostics ID" in the ticket so I can't look at the logs. However I notice you mention mysql -- there is a known issue with mysql: the default image supports only `amd64` but not `arm64`. This means we have to use [qemu user emulation](https://wiki.debian.org/QemuUserEmulation) to emulate the binaries. Unfortunately this is slow and unreliable and is a [known issue in the Docker Desktop release notes](https://docs.docker.com/docker-for-mac/apple-m1/).

The release notes suggest a possible workaround:

> You can work around this issue by using a [mariadb](https://hub.docker.com/_/mariadb) image.

I think mariadb should work the same as mysql, but it supports `arm64` natively.

I hope this helps. I'll close this ticket as `qemu` unreliability is a known issue with a workaround.
