### ISSUE TITLE
Enable/disable cluster no longer in kubernetes menu

### ISSUE THREAD

**Issue by travisgroth** [docker/for-mac#5543]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Up until a recent reinstall, there was always a menu item which would allow you to quickly enable or disable the kubernetes cluster from the menu in the dock icon.  Dock->Kubernetes->enable/disble.

### Actual behavior

This menu item is no longer appearing.

![image](https://user-images.githubusercontent.com/6198562/113586046-064d6f00-95fb-11eb-9b55-8a4d5fb09c6c.png)

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior

1. Install docker for desktop on Mac
2. Attempt to enable or disable kubernetes from the dock menu

This worked for me until I had to do a complete reinstall of docker desktop due to some internal state issue.  A full reinstall fixed that problem but afterwards I was left without this menu item.

**Comment by djs55** [comment]
@travisgroth thanks for the report. The missing enable/disable Kubernetes menu item is a known issue and it's in our backlog. I've added a link to this issue on the backlog ticket for future reference.

To be completely honest with you, it might be a while before we manage to fix this. In the meantime I recommend using the whale menu -> Preferences -> Kubernetes -> [ ] Enable Kubernetes as a workaround. This has the advantage of showing some progress information (although also the disadvantage of being slower)

Thanks again for the report, sorry the news wasn't better!

**Comment by travisgroth** [comment]
Thanks @djs55.  Do you know which version this stopped working at?  I use this button a lot so I'd happily downgrade for my own sanity.
