### ISSUE TITLE
Cannot run haskell on docker apple sillicon (With platform amd64)

### ISSUE THREAD

**Issue by briangtn** [docker/for-mac#5545]
### Expected behavior

Run an haskell cli

### Actual behavior

Haskell program segfault (Return code: 137)

### Information

* WorkStation: Macbook pro M1 13"
* MacOS Version: 11.2.3
* Docker desktop version: 3.3.0
* Docker engine version: 20.10.5, build 55c4c88

### Steps to reproduce the behavior

  1. run `docker run --platform=linux/amd64 -it --rm haskell:buster`
  2. Check the return code with `echo $?`

**Comment by djs55** [comment]
@briangtn thanks for your report. I see the same problem locally. Unfortunately running `amd64` images on Apple Silicon is via [qemu user emulation](https://wiki.debian.org/QemuUserEmulation) which isn't completely reliable (as well as being slow and resource intensive). Unfortunately it's a [known issue in the release notes](https://docs.docker.com/docker-for-mac/apple-m1/). The solution will be to build an `arm64` + `amd64` multiarch image for Haskell, see https://github.com/haskell/docker-haskell/issues/25. I don't think there is anything else we can do at the moment.
