### ISSUE TITLE
Cannot change disk image location to external drive

### ISSUE THREAD

**Issue by christian-fries** [docker/for-mac#5550]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1EC75924-D012-4AA4-A56C-DE4ACEAA1F36/20210406203311

### Expected behavior
The disk image should be moved to the new location after changing the disk image location in the settings and hitting "Apply & Restart" 

### Actual behavior
The disk image location stays the same and the setting is reset after hitting "Apply & Restart".

### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.2.2
  - File system on internal drive: APFS
  - File system on external drive: APFS

### Steps to reproduce the behavior

  1. Open Docker Desktop Preferences and navigate to "Resources"
  3. Hit the browse button for the disk image location
  4. Choose a new location on an external drive
  5. Hit "Apply & Restart"
  6. After the restart, close the preferences
  7. Open Docker Desktop Preferences again and navigate to "Resources"
  8. Check the disk image location, it's back at its old location

**Comment by christian-fries** [comment]
Same issue in
Docker Desktop Version: 3.3.1

**Comment by jhecking** [comment]
Same here: Docker Desktop 3.3.3 (64133).

I tried to Clean / Purge data before changing the disk image location, but did not help.

After changing the location, and clicking Apply & Restart, I can briefly see the `DockerDesktop` folder appear in the new location and two files `console-ring` and `database.iso` getting created in the folder. But then the whole folder disappears again, and after the restart completes, the disk image location is reset back to the previous (default) location.

**Comment by jhecking** [comment]
Still not resolved in Docker Desktop 3.6.0. /remove-lifecycle stale
