### ISSUE TITLE
Wifi unstable when Docker service is active (Apple Silicon, Docker RC3)

### ISSUE THREAD

**Issue by lgodziejewski** [docker/for-mac#5558]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `80E60F31-1B41-4DE7-9FB6-5BFBC1705AE9/20210409122046`

### Expected behavior
No wifi/network issues

### Actual behavior
When running Docker for Mac (RC3, `qemu`) my wifi drops every couple of minutes. As soon as I turned docker off, the connection was stable. After starting it, the problems reappeared again.

### Information
  - macOS Version: 11.2.3 (20D91), M1 Macbook Pro
  - Docker Desktop Version: 3.3.0 (62632)

Let me know if I can provide some diagnostics, logs or anything that would help with the issue.

I can test it further on myself to see if there's perhaps anything more specific to this problem. I'm not 100% sure yet it's a docker problem - perhaps I simply had random connection issues :thinking: 

### Steps to reproduce the behavior

  1. Turn docker on
  2. Observe wifi connectivity
  3. Turn docker off
  4. repeat 2

**Comment by lgodziejewski** [comment]
Minor update:

I tested a couple of scenarios and they seem to confirm the problem if Wifi has a heavier load, i.e.:

I was using Spotify with Docker enabled for 2 hours without any problems.

I was on a Google Meet call for 1h+ - when Docker was enabled my wifi connection dropped a couple of times. As soon as I turned Docker off, the connection was super stable.

not sure if that makes any sense :thinking: - just writing my obervations :sweat_smile:

**Comment by zevarito** [comment]
I was experiencing a similar problem with Catalina, in some cases the Wifi went on/off, but with heavy traffic all interfaces (even loopback) went down for 10 seconds and it happen in periods of ~2 minutes. I wasn't able to figure this out so I've upgraded to BigSur but still struggling to make my env work again with Docker and the whole setup to keep testing.

**Comment by lgodziejewski** [comment]
On version 3.3.1 I didn't encounter this problem - I'll observe a bit more but currently seems everything's fine

**Comment by stephen-turner** [comment]
@lgodziejewski Is everything still working for you? If so, I'll close the ticket.

**Comment by lgodziejewski** [comment]
@stephen-turner sure, go ahead. For now it looks fine - if I observe anything incorrect I'll reopen the ticket 🙂

**Comment by stephen-turner** [comment]
Great, thanks.
