### ISSUE TITLE
[3.3.0] HTTP connection intercepted and forwarded to a different IP - Security issue

### ISSUE THREAD

**Issue by jsuchenia** [docker/for-mac#5571]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: EB534CD9-75D4-466D-A913-258112B96218/20210413125544

We are using a script to test our application (in A/B testing mode). In that case we are opening a connection against test IP but providing a production hostname. Starting from version 3.3.0 we are connection to a production instance, not a test one

### Expected behavior
TCP/HTTP connection will be forwarded to a requested IP, not hostname mentioned in a `Host: ` header. This change has been introduced in 3.3.0

### Actual behavior
TCP/HTTP connection has been forwarded to a host mentioned in a header

### Information
TCP/HTTP connections are intercepted and forwarded by HTTP proxy, we are unable to open a direct http/tcp connection on a port 80. 

### Steps to reproduce the behavior
We can reproduce it on any 3.3.0 build by running:
```
 docker run --rm -it busybox
 / # wget -O - --header "Host: www.google.com" http://1.2.3.4/
```

Using this command we will get a response from Google while IP belongs to Cloudflare!

**Comment by jsuchenia** [comment]
Related tickets:
* https://github.com/docker/for-mac/issues/5568
* https://github.com/docker/for-mac/issues/2467

**Comment by whitej125** [comment]
Just ran into the same issue and closed that ticket (https://github.com/docker/for-mac/issues/5640) which is on 3.3.1

Going to see if I can downgrade Docker for Mac.

**Comment by djs55** [comment]
The HTTP proxy implementation in Docker Desktop 3.3.2 was switched back to the one used in 3.2.2. Hopefully this fixes the problem. Let me know if not!

**Comment by paje** [comment]
Hi David.. works as expected since the update 

Thx a lot !

**Comment by remm** [comment]
the issue [5620](https://github.com/docker/for-mac/issues/5620) also not reproduced in 3.3.2 and 3.3.3
