### ISSUE TITLE
Can anyone tell me how to build the whole Docker Desktop for Mac, I want to fix some issue of VPNkit in it.

### ISSUE THREAD

**Issue by jjqq2013** [docker/for-mac#5574]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

Can anyone tell me how to build the whole Docker Desktop for Mac, I want to fix some issue of VPNkit in it.? I could not find the complete source of them.

**Comment by stephen-turner** [comment]
Sorry, Docker Desktop itself is not open source, although vpnkit is (https://github.com/moby/vpnkit).
