### ISSUE TITLE
Docker 3.3.0 not updating files inside container

### ISSUE THREAD

**Issue by zoewhite** [docker/for-mac#5576]
### Expected behavior
I save a file on my Mac and it's updated inside the container

### Actual behavior
I save a file on my Mac and sometimes it's updated inside the container, sometimes it isn't

Please, help us understand the problem.  For instance:
  - Is it reproducible?
  It happens sometimes and I can't find a specific logic to when it happens and when it doesn't

  - Is the problem new?
I believe it's new. I've never had this problem before updating to 3.3.0, but a colleague of mine says it happens to him every once in awhile. It's been happening to me every day.

  - Did the problem appear with an update?
I believe so

  - macOS Version: 10.15.7
  - Docker Desktop Version: Docker Desktop 3.3.0

5AED2E64-D0AE-47F4-ACD0-F073E1185BE6/20210414103426

**Comment by karillo** [comment]
I've had reports of the same from several folks in my team. They're launching containers with `docker-compose` and using `gRPC-fuse` for access to volumes mounted from within `/Users`. They've reported seeing it at least as far back as Docker Desktop 3.2.0. They've tried a number of configuration settings to no avail including switching between osxfs and gRPC-Fuse,  adjusting memory settings, and performing a stop/start on the container.

The current incantation being used is to try changing and saving the file outside the container a little bit more and see whether this will be the time the file updates inside the container. When all else fails, they restart Docker.

**Comment by davexre** [comment]
Seeing same - running via docker-compose, and not using anything fancy, just a normal volume mount of a folder inside /Users. It seems to fail more often than not. Running MacOS 11.3 and Docker Desktop 3.3.2. The problem seemed to appear for me after I upgraded MacOS (from the latest Mojave to Big Sur). Docker Desktop was a bit behind, so I updated it to 3.3.2, but the problem persisted.

**Comment by jerseycheese** [comment]
I'm also seeing this now, after my Big Sur update (OSX 11.3.1) and updating Docker to 3.3.3. Lots of restarting Docker and `docker-compose up` is the only solution so far I've found to sync things back up.

**Comment by kishaningithub** [comment]
I am seeing the same problem in 3.4.0. I am just using a normal volume mount in docker-compose

Also when i turn off gRPC fuze the file system changes on the host are visible on the container, but the catch is the processes running inside the container are not receiving inotify events intimating them of the change

**Comment by kishaningithub** [comment]
One more observation which happens for both modes of file sharing (grpc, fuse) is that when the file is closed the events are getting fired perfectly from host to container and from the container to the process listening to inotify events

**Comment by prarie** [comment]
I see the same behaviour 3.4.0 on macOS 11.4 (Intel). I have seen the file updated  by going into the container filesystem via exec and `touch`ing it (in my case like `docker-compose exec ... /bin/sh`). Inspired by a report in the closed issue docker/for-win#5530.

**Comment by Metalmacher** [comment]
Having the same issue. I noticed that editing the files inside the container does affect the host files, but the reverse does not occur.
For the time being I reverted to 3.10, seems to work fine so far.

**Comment by Zeitwaechter** [comment]
JFYI, I got the same issue with the current Docker Desktop for Mac (Intel), which bundles `docker` (version 20.10.7, build f0df350) and `docker-compose` (version 1.29.2, build 5becea4c).

Do not enable _Use Docker Compose V2_ within the _Experimental Features_.

After unchecking the option and quitting/restarting the service/App, no file sync issues would happen anymore.

Welp.

**Comment by wkirby** [comment]
Still seeing  this as of today with Version 4.0.0 (4.0.0.12).
