### ISSUE TITLE
DNS resolution doesn't work

### ISSUE THREAD

**Issue by Reggae13** [docker/for-mac#5581]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
using domain names to connect to dockerized services behind a dockerized reverse-proxy (traefik v2.x.x) worked up to now.
(e. g. connecting to a service with a rest-api using a standard url - http://++domain-name++/api/example/v1 - ). If the domain name was a local domain, the docker desktop accepted an entry in the /etc/hosts file.
### Actual behavior
the settings described above do not work anymore. If the local domain-names are replaces by ip-addresses everything is working again.
### Information

  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0

### Steps to reproduce the behavior

  1. build a docker-network with the standard Elasticsearch-Stack (ELK-Stack) as described in the Elasticsearch-Dokumentation.
If Elasticsearch and Kibana are installed with local domain names according to entries in the /etc/hosts file it won't work.
  2. ...

**Comment by boskiv** [comment]
Yes, back to 3.3.3 solve this issue. I had similar behavior.
Docker compose file with Postgres and webservice can't resolve each other by short name.

I'm using `postgres` as a hostname in webservice config and it failed to connect to  DB

**Comment by boskiv** [comment]
Compose:
```
version: '3'
services:
    postgres:
        image: postgres
    ubuntu:
        image: ubuntu
```

Up:
```
docker compose up -d
```

Ping:
```
docker-compose run ubuntu bash
apt update && apt install -y inetutils-ping
root@453b3dbfd94f:/# ping postgres
ping: unknown host
```

**Comment by shaohui-liu2000** [comment]
I am MacOS 10.15.7, and DOcker desktop 4.0.1(68347) with Engine: 20.10.8. when I do 'docker run --rm busybox ping -c 1 google.com', it worked. But if I replace name with my laptop, docker run --rm busybox ping -c 1 {mylaptop}", I got "ping: bad address". It only works if I replace with my external IP.
