### ISSUE TITLE
Where can i download an older version ?

### ISSUE THREAD

**Issue by MatchaDog** [docker/for-mac#5583]
I can't run the project, the big probability is because I upgraded docker today, so I need to download the previous version. But previous versions on the website only support Intel Chip. Maybe you can provide a previous version for Apple Chip.

Here are the problems, thanks

![image](https://user-images.githubusercontent.com/35016589/115012656-ae5c1580-9ee2-11eb-901e-2ee34823a21a.png)

**Comment by stephen-turner** [comment]
The older versions were only previews, and had a built-in time limit so are not available any more.

**Comment by stephen-turner** [comment]
On the topic of your actual bug, is this an Intel container image or an Arm container image? Running Intel containers on Arm hardware under emulation is best-effort only. The solution is to find, or ask the container author to create, an Arm image.

**Comment by MatchaDog** [comment]
I tried to install Arm container image, but the problem remained;
It works well when I reinstalled preview. 
[preview](https://github.com/docker/docker.github.io/blob/master/docker-for-mac/apple-m1.md)
