### ISSUE TITLE
[3.3.0] Docker Desktop Performance Regression on starting app

### ISSUE THREAD

**Issue by tcrayford** [docker/for-mac#5584]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  
There are no instructions for uploading Diagnostics, and I cannot see a button's location obviously in the GUI.

### Expected behavior

Docker.app opens quickly, like it used to.

### Actual behavior

`Docker.app` takes over 200 seconds to open

```
❯ open -a Docker.app; time while not docker info 2>/dev/null 1>/dev/null; printf '.'; sleep 1; end
....................................
________________________________________________________
Executed in  228.24 secs   fish           external
   usr time    6.33 secs   22.10 millis    6.30 secs
   sys time    5.22 secs   96.36 millis    5.12 secs


~/tmp on master took 3m48s
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 48
  Running: 20
  Paused: 0
  Stopped: 28
 Images: 355
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 7
 Total Memory: 12.69GiB
 Name: docker-desktop
 ID: 43YI:57G4:CBQ3:QEPI:QOL3:RS4Q:QBBP:M4L4:E2ET:AKRE:2B2C:HXMB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Information
  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: See above

### Steps to reproduce the behavior

See above

**Comment by stephen-turner** [comment]
Strange. Do you have any corporate security software running? We find that that can sometimes produce mysterious slow-downs.

**Comment by tcrayford** [comment]
@stephen-turner oh, I totally do. That's very interesting!

**Comment by stephen-turner** [comment]
If you're able to turn it off temporarily, I'd be interested to know whether that fixes the problem.

**Comment by tcrayford** [comment]
@stephen-turner I tried turning it off temporarily:

```
open -a Docker.app; time while not docker info 2>/dev/null 1>/dev/null; printf '.'; sleep 1; end
................................................................
________________________________________________________
Executed in  417.37 secs   fish           external
   usr time   11.72 secs   33.28 millis   11.69 secs
   sys time    7.68 secs  108.13 millis    7.57 secs
```

**Comment by stephen-turner** [comment]
So it was worse? There's something very odd going on here, but I'm not sure what it is. I can only think that it's an interaction with something else in your environment, or we would have been flooded with reports.

**Comment by tcrayford** [comment]
@stephen-turner yeah, it was worse. I too am curious about my environment. I'm going to do some digging there.

**Comment by patrickmichalina** [comment]
After upgrading Docker Desktop for Mac it has become extremely slow to boot and I am now looking to downgrade. I just don't know which version I was on sadly.

**Comment by davidmoret** [comment]
Same problem here. Following the update, the startup is very slow and if I can run my project, the MacBook Pro is kneeling. Impossible to redlap with automatic updates. What a loss of time for my company.. Allow the choice of updates for only paid users is a questionable choice.

**Comment by tcrayford** [comment]
@stephen-turner I upgraded to Big Sur, and the app only takes ~30s to restart now.

**Comment by stephen-turner** [comment]
Well, I'm glad to hear that, but I still don't understand it!

**Comment by tcrayford** [comment]
me neither! Closing for now.
