### ISSUE TITLE
Docker will not start

### ISSUE THREAD

**Issue by johnatgh** [docker/for-mac#559]
### Expected behavior
Docker starts successfully.

### Actual behavior
"Docker starting..." in menubar never completes. Menu bar animation never ends.

### Information

Diagnostic ID: 44C80136-2FD5-43AB-958B-86BDC36E9D52
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Additional output:**
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
OS X: version 10.11.6 (build: 15G1004)
Docker.app: version: mac-v1.12.0.1
Running diagnostic tests:
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
[ERROR]   docker-cli       Connection refused (ECONNREFUSED) connecting to /Users/john/Library/Containers/com.docker.docker/Data/s60: check if service is running
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: Failure("docker ps: timeout after 10.00s")
[OK]      Moby booted
[ERROR]   driver.amd64-linux Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   db               Connection refused (ECONNREFUSED) connecting to /Users/john/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]   db               com.docker.db is not running
[ERROR]   slirp            Connection refused (ECONNREFUSED) connecting to /Users/john/Library/Containers/com.docker.docker/Data/s51: check if service is running
[ERROR]   slirp            com.docker.slirp is not running
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
Error docker ps: got timeout (docker ps: exit 1)
Error exec: echo "00000003.0000f3a6" | nc -U /Users/john/Library/Containers/com.docker.docker/Data/@connect > /tmp/44C80136-2FD5-43AB-958B-86BDC36E9D52/20160908-203131/diagnostics.tar: exit 1
Most specific failure is: com.docker.slirp is not running
Docker logs are being collected into /tmp/44C80136-2FD5-43AB-958B-86BDC36E9D52/20160908-203131.tar.gz
Your unique id is: 44C80136-2FD5-43AB-958B-86BDC36E9D52
Please quote this in all correspondence.

**Exit Code**
echo $?
1

### Steps to reproduce

1. Start Docker for Mac.
2. Also occurs with beta version (1.12.1).

**Comment by mchiang0610** [comment]
Merging #119

**Comment by samoht** [comment]
An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: VM: 2016-09-08 23:34:57 +0000 UTC daemon.info vsudd: 6056 Done. read: 188 written: 2076
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: VM: 2016-09-08 23:34:57 +0000 UTC daemon.info vsudd: 6093 Done. read: 188 written: 3875
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: VM: 2016-09-08 23:34:57 +0000 UTC daemon.info vsudd: 6100 Done. read: 188 written: 3875
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=b5fa1598-b1c9-42db-9b27-f9c4b05f4111,path=/Users/john/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/john/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Sep  8 16:34:57 Johns-MacBook-Pro Docker[com.docker.driver.amd64-linux][40020] <Notice>: Interface will have uuid b5fa1598-b1c9-42db-9b27-f9c4b05f4111
```
