### ISSUE TITLE
After upgrade to docker desktop 3.3.1 docker-compose no longer works

### ISSUE THREAD

**Issue by pwagland** [docker/for-mac#5594]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 3667D78A-9E56-4C06-8E17-21BBBDA02B5A/20210416212103

### Expected behavior

Running `docker-compose` would work. When running Docker Desktop, it would update the symlink in `/usr/local/bin` so that it works.

### Actual behavior

Running `docker-compose` fails with an error message that it is a directory. When the symlink is deleted, Docker Desktop does not recreate it on the next startup.

### Information

The issue is that the old symlink of docker-compose points to `/Applications/Docker.app/Contents/Resources/bin/docker-compose` whereas it _should_ point to `/Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose`.

**Comment by aaronhmiller** [comment]
@pwagland Interesting. I'm on Big Sur 11.2.3 and didn't have this issue w/ 3.3.0 nor 3.3.1. I've downgraded to 3.2.2 for other reasons.

However, you might want to also try running `docker compose` (minus the dash) as 3.3.x supports compose as an option to the docker runtime.

**Comment by pwagland** [comment]
@aaronhmiller, I think that this is a side effect of #5593, namely that the docker-compose link wasn't correctly updated and/or replaced. Maybe in an old version it should have pointed to `/Applications/Docker.app/Contents/Resources/bin/docker-compose`, and when upgrading/starting it wasn't replaced? The `docker` link is checked and fixed by the looks of it, but the other links are not. I think that they should probably all be updated on restart?

**Comment by stephen-turner** [comment]
Agreed, I think this is the same as #5593, let's close this one as a dupe and focus the conversation there.
