### ISSUE TITLE
Mounting host files makes docker unusably slow.

### ISSUE THREAD

**Issue by BrendonW** [docker/for-mac#5595]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 42E986E0-66D2-45E5-8349-7C213B28992A/20210416214838

### Expected behavior
Prior to upgrading to 3.3.0, running a command in a container that mounted a host file system took a very similar length of time as running the same container without mounting the files. 

### Actual behavior
The container has a rails server in it:-
> `time docker run -ti --rm <container> rake --tasks`
> `real	0m6.962s`
> `user	0m0.115s`
> `sys	0m0.067s`

Same container mounting the identical rails source tree from a host directory:-
> `time docker run -ti -rm --mount type=bind,source="$(pwd)/rails",target="/home/hosting/rails" <container> rake --tasks`
> `real	2m17.010s`
> `user	0m0.135s`
> `sys	0m0.068s`

This makes it impossible to deploy a stack that mounts an editable source tree.

### Information
  - This is reproducible on demand. A coworker using an M1 mac has the exact same problem.
  - During the huge time difference between the two cases, the hyperkit CPU usage stays over 300-400% in the activity monitor.
  - This is a new problem
  - The problem appeared when we updated to 3.3.0
  - macOS Version: 11.2.3
  - Intel chip or Apple chip: 3.2 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior
  1. Run a rails command in a container that mounts the rails source tree.
  2. There is something about how Rails accesses the files during startup that seems to be making it behave so badly in these recent versions. 
  3. If needed, I'll try and create a simple container to reproduce this.

**Comment by adrubesh** [comment]
There a long discussion about this here that might help you: https://github.com/docker/for-mac/issues/3677

**Comment by nicholasnet** [comment]
Is there any update on this one. Today I upgraded to Docker for Mac Desktop 3.3.1 (63152). Docker is slow in Mac than Linux in general but after update it is unbearably slow. 

Is there any way to downgrade in the meantime.
