### ISSUE TITLE
[BUG] Automatically check for updates disabled on personal Mac

### ISSUE THREAD

**Issue by dalisoft** [docker/for-mac#5596]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5135F189-C3A7-4E9D-B1C0-98FA11F71D3B/20210417111644

### Expected behavior

Let user disable Auto-update on personal Mac, my Mac isn't managed by IT organization. Disable auto-update because of I'm update all of my apps via Homebrew

### Actual behavior

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/3511344/115111013-9eead400-9f97-11eb-8618-a3ab6dee937f.png">

### Information

  - macOS Version: v11.2.3
  - Intel chip or Apple chip: Intel x64
  - Docker Desktop Version: 3.3.0 (62916)

### Steps to reproduce the behavior

  1. Install Homebrew
  2. `brew install docker --cask`
  3. Run Docker
  4. Try disable auto-update

**Comment by stephen-turner** [comment]
The checkbox only checks whether there is an update, it doesn't automatically install them.
