### ISSUE TITLE
Docker Desktop 3.3.1 for Mac Will Not Start

### ISSUE THREAD

**Issue by danielbryantuk** [docker/for-mac#5599]
I haven't been able to run Docker successfully since the 3.1.0 version (and my current fix is to rollback to this version)

 I have tried with the latest version of Docker Desktop
 I have uploaded Diagnostics
Diagnostics ID: 9C4066E3-3FE1-4B50-B9D5-43FC5582DF54/20210418110228

Expected behavior: Docker Desktop starts
Actual behavior: Docker Desktop does not start. The starting animation occurs on the icon, but just keeps looping
Information

macOS Version: Big Sur: 11.2.3
Intel chip or Apple chip: Intel
Docker Desktop Version: 3.3.1

**Comment by danielbryantuk** [comment]
Just as an addendum, the fact that the 3.1 version attempts to upgrade automatically every time I restart Docker is a real motivation-sapper... I have to stop Docker, uninstall, and then re-install 3.1.

I also can't see an obvious way to disable auto-upgrades in 3.1? If anyone could point me to how to do this it would be supremely appreciated!

**Comment by 153957** [comment]
> I also can't see an obvious way to disable auto-upgrades in 3.1? If anyone could point me to how to do this it would be supremely appreciated!

This should be addressed in the latest version:
https://github.com/docker/roadmap/issues/183#issuecomment-818910160

**Comment by fsimond** [comment]
Same issue...

**Comment by mohsinht** [comment]
Same issue :(

**Comment by fabioferreira3** [comment]
Same here, docker desktop stuck at "starting..." after upgrading to latest version 3.3.1

**Comment by djs55** [comment]
For anyone stuck on "starting.." I have an experimental build with more logging. I would be grateful if you could give it a go and then upload fresh diagnostics and quote the ID here. The links are:
- Intel: https://omakase.internal.dckr.io/#/stage/mac/stable/amd64/63345
- Apple Silicon: https://omakase.internal.dckr.io/#/stage/mac/stable/arm64/63345

Note that neither of these two builds are notarized.

Assuming the build is still stuck in the "starting..." state, try running `docker logout` from a terminal and then restarting the app. Let me know if that makes a difference or not.

Thanks in advance!

**Comment by danielbryantuk** [comment]
Many thanks, @djs55 , but it looks like we need a Docker login to access the Intel binary?

**Comment by djs55** [comment]
@danielbryantuk my apologies, I used the wrong link! I've updated them now.

**Comment by danielbryantuk** [comment]
Hi @djs55 , thanks! The new Intel binary you provided worked straight away for me: there was no need to do a `docker logout` (although the UI shows me as not logged in -- I was probably logged out after I've tried various resets and reinstalls)

Docker started within a few seconds, and I ran a couple of basic commands successfully.

Many thanks for your help -- if the next official release of the binary works like this then it will be happy days :) 

Is there anything else I can do/provide in order to help you and the team?

**Comment by djs55** [comment]
@danielbryantuk thanks for letting me know and I'm glad it's working correctly for you!

The changes in that development build are now in the main development branch so should be in the next automatic update. I think it's probably safe to close this issue -- I'll do that now -- but feel free to open another if you hit further problems (or if this one returns... hopefully not)
