### ISSUE TITLE
Docker commands hang

### ISSUE THREAD

**Issue by dvinov-arivale** [docker/for-mac#56]
### Expected behavior

Docker commands like `docker ps` work.

### Actual behavior

Every once in a while (about daily), Docker commands (even something simple like `docker ps` hang for minutes and eventually time out. Restarting Docker doesn't work. I have to Reset to Factory Defaults. This forces me to have to re-download all docker images from dockerhub, which takes a lot of time.

I saw this behavior in the Beta from early last week. I upgraded to the Stable release late last week, but I saw this bug again this morning.

### Information

Diagnostic ID: 672E7D77-FC39-4D73-9774-EEB2D70BAF30
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Haven't found reproducible steps. It has happened to me once a day about 3-4 times this and last week.

**Comment by ccastarivale** [comment]
This just happened to me this morning for the first time. I'm running an older build: `Version 1.12.0-rc2-beta17 (build: 9779)`

Builds were hanging as was `docker ps`. Resetting to factory defaults fixed it.

**Comment by dvinov-arivale** [comment]
Another instance of this issue this morning: 020AEE4C-39FC-4C23-A517-E758A27EE071. Can someone please take a look?

**Comment by dvinov-arivale** [comment]
I'm on the latest stable release now after upgrading earlier this week, and still seeing this issue. Is anyone looking at this? It's making me have to do a factory reset every few days. Supremely frustrating!

Diagnostic ID: 376B2BAF-3E91-4E27-B885-329CA518A6FB
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by dsheets** [comment]
Unfortunately, some of our diagnostic system was accidentally disabled in the stable channel which makes it difficult for me to review the VM logs. It should be fixed with the release of 1.12.1 stable in a week or two. In the meantime, if it would be possible for you to run the beta channel and re-observe the problem that would be very helpful toward getting this resolved.

I'm sorry for the frustration this causes. Thanks for reporting the issue!

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 672E7D77-FC39-4D73-9774-EEB2D70BAF30/20160801-103532.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785
