### ISSUE TITLE
Docker for desktop (3.3.1) on intel mac does not start

### ISSUE THREAD

**Issue by commjoen** [docker/for-mac#5601]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID captured with Docker for desktop 3.3.1: 3B4D47CE-442B-4212-AA98-D90CF4BCE493/20210419083919

### Expected behavior
The Docker Desktopt should boot and get beyond the "starting" phase and run after I gave it privileged access to install and configure itself.

### Actual behavior
The docker Desktop process keeps running (e.g in status "starting)

### Information

I am running the Docker Desktop on Mac OSX Big Sur 11.2.3 on an Intel Mac. Older versions of Docker for Mac (pre 3.20) are working on my system. I have tried various uninstall/install items/ kill vmnetd, but I could not get newer versions to work.

### Steps to reproduce the behavior
1. Install latest version of Docker for desktop CE.
2. wait for it to start.

If there is any information I can add here, please let me know. The console logs don't give a lot of information either unfortunately.

Note: Docker 3.1.0 for desktop does still work on my system, if it helps to see the difference, here is a diagnostics ID gathered using Docker for Desktop 3.1.0: 4BD8291C-48E0-48D9-93D0-C9A50AF58D30/20210419094212
See below the screenshot of what docker desktop 3.3.1 is reporting.

**Comment by commjoen** [comment]
Note, after quite some time i get this screen: 
![image](https://user-images.githubusercontent.com/1457214/115214196-9236bf00-a102-11eb-899c-54483a5c72c2.png)

**Comment by djs55** [comment]
I've linked to some development builds here: https://github.com/docker/for-mac/issues/5599#issuecomment-823155113 Please try one of them and upload fresh diagnostics if it goes wrong. Thanks in advance!

**Comment by commjoen** [comment]
Awesome @djs55 ! Thank you for your support! Apologies :-(, but it seems I cannot get beyond the Oauth-proxy with my current Docker-hub account and/or Google/gmail credentials, do I need to upgrade my account for it?

**Comment by djs55** [comment]
@commjoen oops, my mistake-- I used the wrong link. I've updated the links to point directly at the installers.

**Comment by commjoen** [comment]
@djs55 this works! Diagnostics id for validation : 4BD8291C-48E0-48D9-93D0-C9A50AF58D30/20210421073458

**Comment by commjoen** [comment]
I am fine with closing this issue now 👍 ,thank you so much for your support! 
Is there anything I can do for you to pin down the issue further, or is all good now? 
What I did is: remove the old docker app, install the one you recommended downloading, run it, authorize it in mac-os-x security settings, then give it permission to install whatever required.

**Comment by djs55** [comment]
@commjoen thanks for the feedback, I'm glad it's working for you!

The changes in that build are in the main development branch, so should be in the next release. I think it's probably safe to close this ticket -- I'll do that now. Feel free to open a fresh ticket if you hit any further problem.
