### ISSUE TITLE
docker run hangs when asked to mount a recreated directory

### ISSUE THREAD

**Issue by mbengit** [docker/for-mac#5604]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 63F376B3-ACF5-425B-843D-AAED828D01E7/20210419120746

### Expected behaviour

Executing the same `docker run` command with a mounted local directory always starts a container, and the command always returns.

### Actual behaviour

Execute `docker run`, mounting a local directory from the host into the container using the `-v` option. The container starts and the command returns.

Remove the container, delete the directory you mounted, then recreate that directory. Execute the same `docker run` command, supplying the same `-v` details. The command hangs and cannot be interrupted using Ctrl-C. Any attempt to interact with the container using e.g. `docker inspect`, `docker logs`, or `docker rm`, also hangs. The issue requires a  Docker Desktop restart to resolve.

### Information
  - Issue is easily reproducible using the `docker/getting-started` image
  - macOS Version: 11.1
  - Intel chip or Apple chip: Intel Core i7 (2015)
  - Docker Desktop Version: 3.3.1
  - Occurs with `osxfs` file sharing but not with `gRPC FUSE`.

### Steps to reproduce the behaviour
```
mkdir store
docker run -d -p 80:80 -v `pwd`/store:/store docker/getting-started
docker rm <container ID>
rmdir store
mkdir store
docker run -d -p 80:80 -v `pwd`/store:/store docker/getting-started
```

**Comment by stephen-turner** [comment]
@mbengit Thanks for the report. Does this happen with both the grpcfuse and osxfs storage back ends, or if not then which?

Thank you.

**Comment by mbengit** [comment]
@stephen-turner If I enable the `Use gRPC FUSE for file sharing` option, the issue does not occur, so it appears to be specific to `osxfs`. I'll update the bug description accordingly.

**Comment by stephen-turner** [comment]
OK, thanks.

**Comment by mbengit** [comment]
@stephen-turner Is the expectation that to avoid this issue, users should configure gRPC FUSE rather than osxfs?

Also, going forward, is gRPC FUSE the preferred configuration for Mac users?

**Comment by stephen-turner** [comment]
We expect gRPC FUSE to be the way forward. Right now we're offering both because there are certain workloads where osxfs is still faster, but we hope to fix that at some point.
