### ISSUE TITLE
Docker for Mac self-updates to broken releases without action

### ISSUE THREAD

**Issue by ryanboswell** [docker/for-mac#5607]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker for Mac will only perform updates when I opt into them.

### Actual behavior

Docker for Mac performs updates without user acknowledgement or consent if the app is restarted in any way.

After the string of network-related issues with 3.3.0 and 3.3.1, I had to downgrade to be able to use Docker locally (the network problems made it impossible to develop my applications). The downgrade worked great, until I restarted my computer (and thus Docker itself). Once Docker started back up again it auto-updated back to the broken 3.3.1 build and I was back to square one and needed to downgrade again. This has now repeated twice in subsequent restarts.

While I can appreciate keeping software up to date, forcing unstable software updates makes Docker for Mac virtually unusable unless I pay for a Pro account for the privilege of skipping the auto-update process.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.2.2 and 3.3.1

### Steps to reproduce the behavior

  1. Downgrade to Docker for Mac 3.2.2 using the download link on the release notes page.
  2. Restart the laptop
  3. See that when Docker for Mac starts again it is now running 3.3.1 (or whatever the current latest is).

**Comment by stephen-turner** [comment]
This behaviour was changed in 3.3.0, but it only applies to releases going forward because the update code is in the version you're updating from. For releases from 3.3.0 or higher, there is no auto-update.

**Comment by LeZuse** [comment]
For anybody who is stuck on a broken version this works: https://gist.github.com/LeZuse/aad7d02d2ccc564f7fc21f032607b47b
