### ISSUE TITLE
Silence "Use 'docker scan' to run Snyk tests "output on Docker build

### ISSUE THREAD

**Issue by ryan-blunden** [docker/for-mac#5609]
Why is this promotional message even appearing?

In any case, I can't see a way of preventing this message from showing.

**Comment by stephen-turner** [comment]
You should be able to turn it off with `docker build -q`. There's currently a bug preventing that from happening, but we will fix it in the next version.

**Comment by superlevure** [comment]
@ryan-blunden is there no way to globally disable it ? It's really disturbing that an add was "just added" to the CLI like this

**Comment by ryan-blunden** [comment]
An interim solution is to use the advice from https://github.com/docker/scan-cli-plugin/issues/149  (which I've verified to work) to set the `DOCKER_SCAN_SUGGEST` environment variable to `false`:

```sh
export DOCKER_SCAN_SUGGEST=false
```

**Comment by edthedev** [comment]
And in `PowerShell`:

```powershell
$ENV:DOCKER_SCAN_SUGGEST = 'false'
```
