### ISSUE TITLE
Docker Desktop starting/stopped continuously

### ISSUE THREAD

**Issue by loretoparisi** [docker/for-mac#5612]
https://user-images.githubusercontent.com/163333/115591787-ca8cf780-a2d2-11eb-9eb7-47237fd8d948.mov

https://user-images.githubusercontent.com/163333/115592088-1b9ceb80-a2d3-11eb-976b-21dcafa5ca1c.mov

Info:
<img width="465" alt="Schermata 2021-04-21 alle 18 53 33" src="https://user-images.githubusercontent.com/163333/115591890-e5f80280-a2d2-11eb-968a-a6113ca4d134.png">

**Comment by pikoroco** [comment]
I have same issue.

Problem:
I update my os version form 11.2 to 11.3 and when restart the os i get this problem.

Hardver:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) 2,3 GHz Kétmagos Intel Core i5 processzor 8 GB 2133 MHz

OS:
macOS Big Sur Version 11.3 (20E232)

Software:
<img width="761" alt="Képernyőfotó 2021-05-03 - 9 57 07" src="https://user-images.githubusercontent.com/36642639/116853420-4bfb5880-abf6-11eb-8228-d652d4c20124.png">

Thx the help.
