### ISSUE TITLE
Docker hangs while downloading images

### ISSUE THREAD

**Issue by pdaether** [docker/for-mac#5615]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 38964615-96AD-4738-BAB9-A5AC9A45E410/20210422075540

### Expected behavior

I can pull docker images and run containers.

### Actual behavior

Docker always hangs on random places while downloading. 
This happens on my machine with all images I tried, even the simple example one:

```
$ docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
latest: Pulling from docker/getting-started
069a56d6d07f: Already exists
2c36e9465b53: Downloading [=============================================>     ]  6.257MB/6.903MB
cfcc925340bd: Download complete
5280a9b3efa9: Download complete
83380a3f4dde: Download complete
aedf4ca77dae: Download complete
e45379b4b21e: Download complete
45643c41063c: Download complete
```

Restarting docker or the mac does not help. I also tried with either using LAN or WLAN. Firewall is deactivated, no anti-virus software or something similar is running. Internet connection is stable.
I also tried with different docker settings, system prune ... nothing helped.

### Information

  - macOS Version: Big sur 11.2.3
  - Intel chip or Apple chip: Apple Silicon
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

It is 100% reproducible with the example from docker:
```
docker run -d -p 80:80 docker/getting-started
```

**Comment by stephen-turner** [comment]
That's strange, but I don't really know what to suggest. I mean, I would have suggested some sort of VPN or proxy, but you already thought of that. I think it must be something specific to your environment as we're not getting other reports of this.

**Comment by SovakPaleny** [comment]
We are facing the same issue on Big Sur and Catalina, on the 3.3.0 and 3.3.1 versions. All colleagues have the issue after upgrading to the 3.3.x version.

**Comment by stephen-turner** [comment]
Please try again with 3.3.2 or 3.3.3. We've reverted some networking changes we made in 3.3.0, so this might be fixed.

**Comment by abrichr** [comment]
I was experiencing the same issue on 3.3.1 (63152) on a wired ethernet connection with no VPN or proxy.

Updated to 3.3.3 (64133). Downloads still appear to fail, but now failures are automatically detected and restarted. Thank you!!

**Comment by abrichr** [comment]
Well it looks like upgrading solved one issue but created another; see: https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/377 .

It appears that the downloads are not resuming successfully, since at least one of the images is corrupt. Downgrading to 2.4.0 appears to have resolved this particular issue.

**Comment by pdaether** [comment]
For me this does not happen anymore after updating Docker to 3.3.2 and 3.3.3.

**Comment by stephen-turner** [comment]
OK, this seems to be fixed so I'll close the ticket.
