### ISSUE TITLE
Resolve bechavior is wrong for curl + cni in 3.3.1 version

### ISSUE THREAD

**Issue by remm** [docker/for-mac#5620]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
--resolve flag for `curl` works as expected. 

### Actual behavior
seems --resolve flag is ignored

### Information

  - macOS Version: 11.2.3 (20D91)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

  1. execute `curl -vvv http://www.cl3ver.it -IL --resolve "www.cl3ver.it:80:35.195.208.149" --resolve "www.cl3ver.it:443:35.195.208.149" -s` in any docker image with curl
  2. execute same curl on the local machine 
  3. compare headers of requests

Checked also this issue for version 3.2.0 it works as expected.

**Comment by djs55** [comment]
I think this is the same as #5571 -- the Host: header is taking precedence over the resolved IP address.

**Comment by stephen-turner** [comment]
OK, let's close this one as a dupe and follow there for updates.
