### ISSUE TITLE
Docker Desktop auto-updating

### ISSUE THREAD

**Issue by marklabrecque** [docker/for-mac#5623]
- [n/a] I have tried with the latest version of Docker Desktop
  - [yes] I have tried disabling enabled experimental features
  - [n/a] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I should be able to start my Docker Desktop app without upgrading to the latest version of Docker Desktop

### Actual behavior
When I start the app, it automatically updates me to the latest version, without even telling me it is doing so, let along asking if that is something I want to do.

### Information
  - macOS Version: 11.2.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior
I have a project that requires that I use an older version of Docker Desktop, namely 3.1.0. I installed the .dmg and once the installation completed and Docker was up and running, I checked the version and it was indeed 3.1.0, like I wanted. Almost immediately it gave me a notification that there was a newer version available with a little badge on the icon in the menu bar. In that menu, it gave me to option to Update & Restart or Quit Docker Desktop. I was very careful not to update, but hitting Command+Q, which shutdown Docker Desktop and removed it from the menu bar. I checked for active processes, and the docker processes were all gone. I then proceeded to restart Docker Desktop from my Applications folder and I was presented with a dialog box saying "Verifying Docker...." like it did the first time I installed it. Once that completed, it asked me again for administrator privledges to install networking components, also the same as it was the first time I installed it. Please note I careful read all of the messages up to this point and none of them asked me or even told me it was going to update my Docker Desktop app. Once the app had completely loaded up, I was on 3.3.1.

I have also seen [recent comments](https://github.com/docker/roadmap/issues/183#issuecomment-818910160) from the dev team that assures the userbase that no one will ever be forced to update, but if my experience is not described by forcing the update, I'm not sure what would be.

Can we get some clarification on this matter: Is this working as intended and that auto-updating is being forced, or is this some sort of bug in the self-updater?

Thank you for all of your hard work on this software, it is much appreciated :)

**Comment by sreevidyaJ** [comment]
same for me. Docker got updated automatically without asking. with latest Docker version, I'm facing lot of issues. There should be option to update it later

**Comment by kongslund** [comment]
I experience the same behavior and I would like for the upgrade to be optional as well. I'm currently affected by #5516 so I _have_ to run with an older version. So far, I've been auto-upgraded 3 times and thus had to downgrade 3 times. It's fairly disruptive.

**Comment by stephen-turner** [comment]
Auto-updating has been removed in version 3.3.0, but the code that does the updates is in the version you're updating from, not the version you're updating to, so it will only apply from 3.3.0 onwards.

**Comment by LeZuse** [comment]
For anybody who is stuck on a broken version this works: https://gist.github.com/LeZuse/aad7d02d2ccc564f7fc21f032607b47b
