### ISSUE TITLE
Containers cannot use host's VPN after update to 3.3.x

### ISSUE THREAD

**Issue by djnotes** [docker/for-mac#5628]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID: 

I usually use a VPN on my host. This way, Docker containers are able to connect to blocked services. After the recent update to macOS Big Sur and Docker Desktop 3.3.x, my containers fail to connect to such services. 

Do I need to configure additional settings to make the containers use the host's VPN. I saw vpnkit on GitHub that apparently does this, but it seems very overwhelming to set up with little documentation. Also, I wonder why this might be needed as my containers used to work just fine before this update. 

### Expected behavior
Containers being able to connect to blocked services

### Actual behavior

Containers don't seem to be using the host VPN tunnel

### Information

  - macOS Version: Big Sur
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. Install Docker Desktop 3.3.1
  2. Run containers that need to access some services using the host's VPN.

**Comment by k3v3n** [comment]
So I did encounter the same issue. My container cannot communicate with the host since I update to 3.3.x. I have reverted to 3.2.x and it works. Now that I cannot disabled auto-update, every time I have to restart my Docker service, it gets automatically updated without my consent. 

How can I disable the auto-update that break my setup without paying the 5$/month for to disable that feature ?

**Comment by epicavic** [comment]
+1

**Comment by Me1kaa** [comment]
Same issue here. Can't work with our private registry after 3.3.x.

**Comment by k3v3n** [comment]
Turns out that auto-update was removed on 3.3.0. But since 3.3.1, my container is not able to communicate with the host so I downgraded to 3.2.x but with the auto-update still present. https://github.com/docker/for-mac/issues/5623

**Comment by k3v3n** [comment]
So I have restarted docker and reset factory settings, make sure to NOT use the new virtualization framework and it worked as expected now on 3.3.1 for Mac intel.

**Comment by gwpries** [comment]
We are also having the same issue -- factory reset docker 3.3.0 / 3.3.1 cannot talk to kubectl whatsoever due to https socket errors, VPN not even involved. Can't even `curl -k ip.address`. And since we can't downgrade due to the auto-upgrade, docker is completely broken for our use case.
When --network host is used, it's fine, but that is also incompatible with our use.

**Comment by Xvezda** [comment]
I encountered similar issue. In my case, errors occurred on `node` image like this:
```
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:642:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1579:19)
    at TLSSocket.emit (node:events:381:22)
    at TLSSocket.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: '[REDACTED]',
  port: 443,
  localAddress: undefined
}
```
Thanks to @gwpries letting me know `--network host` should work.
A quick fix can be done by adding `network_mode: "host"` to Node.js container of `docker-compose.yml`.

**Comment by fabb** [comment]
Same issue here, downgrading to 3.2.2 fixed the issue, but how can I disable auto update?

**Comment by fabb** [comment]
@nebuk89 could you backport the auto update deactivation feature to 3.2.x until this blocker issue has been fixed?

**Comment by dimon222** [comment]
Is anything changing in this area? This VPN issue is causing real disruptions due to autoupdate

**Comment by jtneal** [comment]
Been having this issue as well since upgrading to 3.3. Still works fine in 3.2.2

**Comment by gwpries** [comment]
3.3.2 fixes our issue with this

**Comment by djnotes** [comment]
I just tried this with version 3.3.2 and it is working well. Thanks Docker. 
It is probably time to close this issue. Feel free to reopen if you feel it is needed.
