### ISSUE TITLE
Minor UI bug for reset dialog

### ISSUE THREAD

**Issue by karanpratapsingh** [docker/for-mac#5633]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
dialog with meaningful text

### Actual behavior
not sure if it's intended or a todo
<img width="576" alt="Screenshot 2021-04-27 at 6 45 21 PM" src="https://user-images.githubusercontent.com/29705703/116248185-4088d700-a789-11eb-9ae2-fdb3c2c07e5a.png">

### Information

  - macOS Version: 11.0.1
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: 331 (63152)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Thanks for the report. This seems to be the same as #5457, but we fixed that in 3.3.0 so I don't understand how you're still seeing it. Maybe a silly question but are you sure you didn't see it just before upgrade? Otherwise there might be a case we missed.

**Comment by karanpratapsingh** [comment]
Awesome @stephen-turner, I was in between updating my docker for mac, so must be fixed! Feel free to close the issue!

**Comment by stephen-turner** [comment]
Great, thanks, I'll close it.
