### ISSUE TITLE
Factory reset window

### ISSUE THREAD

**Issue by shanisma** [docker/for-mac#5638]
I get Docker-ce crashed on my mac, docker-ce is working fine after factory reset
Strange window appeared, it seem a template ...  something not finished

![Capture d’écran 2021-04-29 à 12 51 51](https://user-images.githubusercontent.com/23318335/116539852-adb37e00-a8e9-11eb-9bc6-bf94d5dec770.png)

**Comment by stephen-turner** [comment]
Thanks for the report. This is a duplicate of #5457 and was already fixed in version 3.3.0.
