### ISSUE TITLE
After macOs 11.3 update Docker build fail behind proxy failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/httpd/manifests/2.4.39: Bad Gateway nor can connect to container w/o proxy on ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by CeeeCZ** [docker/for-mac#5645]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B9E3A907-455F-4761-B410-4653470CD18F/20210501105415

### Expected behavior
Expect to build containers behind proxy same way before the 11.3 update, also without any proxy, connect to container. For private project using Laravel Sail.

### Actual behavior
Docker build behind proxy fails on `failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/httpd/manifests/2.4.39: Bad Gateway` also without using any proxy and only Laravel Sail, it suddenly fails to make any connection to the containers, console only shows failing calls on 500 or 502.

### Information
It was all working just fine, then I updated to 11.3, system rebooted and nothing works now. Honestly don't know what's suddenly so wrong.

  - macOS Version: BigSur 11.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1 (63310)

### Steps to reproduce the behavior
  1. Update to BigSur 11.3
  2. Try to use Docker

**Comment by rmahroua** [comment]
I don't know if that is related, but I had some issues with TLS (on something different). After updating Docker to the latest version, the issue is gone (3.3.2)

**Comment by CeeeCZ** [comment]
Yeah I also had a high hopes towards that update, but.. still the same. So I got fresh win PC at work, and install the docker and it even gives me the same error on brand new win machine.. but it's super slow, need to fix it on mac!

**Comment by olivierlacan** [comment]
Same problem here. 

Update after update Docker for Mac still fails to properly connect despite seeing connection attempts in toxiproxy logs show up: 

```
1620167531.215    190 192.168.1.88 NONE/503 0 CONNECT harbor.***.com:443 - HIER_NONE/- -
1620168588.297  30675 192.168.1.88 TCP_TUNNEL/200 4183 CONNECT harbor.***.com:443 - HIER_DIRECT/<REMOVED_IP> -
```

On the machine using the proxy all I see when running `docker-compose up -d` is: 

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get "https://harbor.***.com/service/token?scope=repository%3Aproxy%2Flibrary%2Fpostgres%3Apull&service=harbor-registry": dial tcp: lookup harbor.***.com: no such host
ERROR: Service 'postgres' failed to build : Build failed
```

**Comment by CeeeCZ** [comment]
> Same problem here.
> 
> Update after update Docker for Mac still fails to properly connect despite seeing connection attempts in squid logs show up:
> 
> ```
> 1620167531.215    190 192.168.1.88 NONE/503 0 CONNECT harbor.***.com:443 - HIER_NONE/- -
> 1620168588.297  30675 192.168.1.88 TCP_TUNNEL/200 4183 CONNECT harbor.***.com:443 - HIER_DIRECT/<REMOVED_IP> -
> ```
> 
> On the machine using the proxy all I see when running `docker-compose up -d` is:
> 
> ```
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get "https://harbor.***.com/service/token?scope=repository%3Aproxy%2Flibrary%2Fpostgres%3Apull&service=harbor-registry": dial tcp: lookup harbor.***.com: no such host
> ERROR: Service 'postgres' failed to build : Build failed
> ```

Btw for some of the `failed to authorize` issues ... it can be "fixed" by logging into Docker account! Not sure if it helps you, but for me it was part of the solution. That and setting preferences for manual proxy.
