### ISSUE TITLE
docker build -q adding spam to output

### ISSUE THREAD

**Issue by edwarnicke** [docker/for-mac#5646]
- [x ] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

```bash
docker build -q .
```
Should "Suppress the build output and print image ID on success"

### Actual behavior

```bash
docker build -q .
```
Suppress the build output and print image ID followed by the spam " Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them" on success.

### Information

  - macOS Version: 11.2.3 (20D91) 
  - Intel chip or Apple chip: 2.4 GHz 8-Core Intel Core i9
  - Docker Desktop Version: 3.31 (63152)

### Steps to reproduce the behavior

  1. Run ```docker build -q .``` in any directory containing a valid Dockerfile that uses 'CMD' and not 'ENTRYPOINT'

### Impact

The very common pattern 

```bash
docker run -rm $(docker build -q .)
```
is completely broken by this bug.

**Comment by edwarnicke** [comment]
Workaround:

It appears running 
```bash
docker scan ${image id}
```
even if it fails due to the users not being logged into dockerhub, will remove the spam, and allow normal functionality to return.

**Comment by edwarnicke** [comment]
Likely related: https://github.com/docker/compose-cli/issues/1597

**Comment by edwarnicke** [comment]
Another workaround here: https://github.com/docker/compose-cli/issues/1597#issuecomment-826815403

**Comment by edwarnicke** [comment]
Related issue: https://github.com/docker/compose-cli/issues/1517

**Comment by stephen-turner** [comment]
Thanks for the report. This is a dupe of docker/compose-cli#1517, and is fixed in the version of the CLI included in the latest version of Docker Desktop (3.3.2).
