### ISSUE TITLE
kubectl cannot communicate with any cluster from inside a container on M1

### ISSUE THREAD

**Issue by kamigerami** [docker/for-mac#5648]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 1BDF8432-E7A3-4306-82FD-59E704196CCF/20210503081437

### Expected behavior

kubectl cluster-info 

### Actual behavior

> kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF

### Information

  - macOS Version: 11.1 Big sur
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

1.  run docker with any image that has kubectl in it.
2. set context and credentials so that you can connect to the cluster
3. run any kubectl command to communicate with the cluster.
4. See error.

**Comment by gwpries** [comment]
We had this issue as well on Intel systems, most likely related to the bad http/https proxy situation mentioned elsewhere. Try 3.3.2 as it is fixed for us there.

**Comment by parberge** [comment]
Version `Docker Desktop 3.3.2 (63878)` solved it for me.

**Comment by stephen-turner** [comment]
Believed fixed in 3.3.2, closing.
