### ISSUE TITLE
Unable to launch Docker on Apple Mac Mini with M1 chip, BigSur OS

### ISSUE THREAD

**Issue by rafikobai** [docker/for-mac#5650]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Launches with no issues
### Actual behavior
Fatal Error symlinks . Here is the exact error 
docker cannot install symlinks in /usr/local/bin (stage 5)### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@rafikobai thanks for your report.

Could you upload a diagnostics report and quote the ID here? Run this command:
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
The output will look something like this:
```
time="2021-05-04T15:59:44+01:00" level=info msg="All 85 gatherers finished" type=list
INFO[0023] Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/ca571de9-a4a4-4cbd-8f5b-b80c9887974a/20210504145929.zip 


Diagnostics Bundle: /tmp/ca571de9-a4a4-4cbd-8f5b-b80c9887974a/20210504145929.zip
Diagnostics ID:     ca571de9-a4a4-4cbd-8f5b-b80c9887974a/20210504145929 (uploaded)
```

**Comment by rafikobai** [comment]
Here is the diagnostic ID

7DD66FBB-A16B-4CE2-BE11-5C1D5D1E2731/20210504160946


Please let me know if you need anything else.


Thanks

**Comment by djs55** [comment]
@rafikobai thanks for the diagnostics. The logs have:
```
 Error handling command: cannot create /usr/local/bin directory: mkdir /usr/local/bin: not a directory
```
Could you check whether `/usr/local` or `/usr/local/bin` already exist and are directories? Sometimes a tool will run `cp foo /usr/local/bin` without checking if `/usr/local/bin` has been created, and `/usr/local/bin` ends up as a file, which then prevents us adding symlinks to the docker CLI etc.

**Comment by rafikobai** [comment]
/usr/local/ exists and bin is a file . Here is the output

cd /usr/local/bin

cd: not a directory: /usr/local/bin


cd /usr/local

rafishaik@Rafis-Mac-mini local % ls

Caskroom Frameworks bin include opt share

Cellar Homebrew etc lib sbin var


Please let me know if you need anything else.

Thanks

Rafi

**Comment by djs55** [comment]
@rafikobai thanks for checking. I think `/usr/local/bin` should not be a file. I recommend fixing it by running:
```
sudo mv /usr/local/bin /usr/local/bin.old
```
I think after that it should be possible to start Docker.

**Comment by rafikobai** [comment]
Great, thanks! It woked

**Comment by mayteio** [comment]
Hey all! I am having the same problem with same setup - I have checked the above steps and both `/usr/local` and `/usr/local/bin` are directories.

I have uploaded the logs under: 582F770C-24E5-4B11-A473-994DF76EFB63/20210504223603

**Comment by mayteio** [comment]
Solved with this purge script & re-download:
https://github.com/docker/for-mac/issues/5426#issuecomment-791622494

**Comment by djs55** [comment]
@rafikobai glad to hear it's working!

@mayteio thanks for letting me know the purge script helped. I'm not sure exactly what went wrong initially but I'm glad you're up and running again.

I'll close this issue but feel free to open a new one if you hit another problem.
