### ISSUE TITLE
Unable to start Docker Desktop 3.3.2 after upgrading to Big Sur 11.3

### ISSUE THREAD

**Issue by tongyuwang** [docker/for-mac#5651]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 68DD59A2-6887-4FA6-AADC-9DC075082678/20210504205141

### Expected behavior
Docker Desktop starts normally.
### Actual behavior
After upgrade to Big Sur 11.3 and Docker Desktop to 3.3.2, it stopped starting normally.
### Information

  - macOS Version: 11.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by smartameer** [comment]
I have the same issue after updating Mac OS to 11.3.1

**Comment by djs55** [comment]
@tongyuwang @smartameer thanks for your reports. The problem may be HTTP proxy related.

If you don't use an HTTP proxy, could you try moving the configuration file out of the way and gathering the diagnostics manually, for example:

```
% mv ~/Library/Group\ Containers/group.com.docker/http_proxy.json ~/Library/Group\ Containers/group.com.docker/http_proxy.json.backup 
% /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
This will attempt to upload the diagnostics directly. If it still doesn't work, could you post the output from the command to the ticket and I'll take a look.

**Comment by juliuso** [comment]
@djs55 Running Docker 2.3.0.3 and after upgrading to macOS 11.3, am getting a Fatal Error. Enclosed are the logs from `diagnose gather`

[gather.txt](https://github.com/docker/for-mac/files/6422631/gather.txt)
![Screen Shot 2021-05-04 at 09 39 58](https://user-images.githubusercontent.com/565705/117038980-19686300-acbd-11eb-8186-3e985976e40b.png)

**Comment by djs55** [comment]
@juliuso thanks for your report. Version 2.3.0.3 is quite old. I recommend downloading the latest version from: https://docs.docker.com/docker-for-mac/release-notes/ . You can open the `Docker.dmg` and drag Docker to `/Applications` and then double-click on the app in Finder.

**Comment by juliuso** [comment]
> @juliuso thanks for your report. Version 2.3.0.3 is quite old. I recommend downloading the latest version from: https://docs.docker.com/docker-for-mac/release-notes/ . You can open the `Docker.dmg` and drag Docker to `/Applications` and then double-click on the app in Finder.

Appreciate the suggestion. Unfortunately at this time, upgrading beyond 2.3.0.3 will break our toolchain. The logs seem to suggest an issue with vpnkit that's affecting other versions of docker. 2.3.0.3 was running fine on macOS 11.2.3 before it was upgraded to 11.3.

**Comment by tongyuwang** [comment]
I uploaded the diagnostics, ID 68DD59A2-6887-4FA6-AADC-9DC075082678/20210504205141.

**Comment by alpgokcek** [comment]
I have the same problem. Diagnostics ID: 4966C5BB-D3A2-4062-985D-2AE695BC724B/20210505062206

**Comment by djs55** [comment]
@juliuso I'm glad you found a workaround for now. However I'm concerned that the downgrade may not be future-proof. Do you know why your toolchain is broken with later versions? Is there an issue I could look at? (Ideally with some repro steps / diagnostics or other clues to help me understand)

**Comment by djs55** [comment]
@alpgokcek thanks for your report. Could you download the latest version (3.3.2) and try again? https://docs.docker.com/docker-for-mac/release-notes/ Note that there is a bug in the diagnostics upload in 3.3.2 (which will be fixed imminently in 3.3.3) but in the meantime you can upload diagnostics from the command-line with
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
If it's not possible for you to upgrade to 3.3.2, could you let me know why? I'd like to understand if there's a blocking issue, ideally with enough information to help me understand it.

Thanks in advance!

**Comment by djs55** [comment]
@tongyuwang thanks for the diagnostics upload. I think this is a useful clue:
```
time="2021-05-04T15:21:22-04:00" level=error msg="iso docker.tar not found for version pack enterprise-2.1: stat /Library/Application Support/Docker/DockerDesktop/version-packs/enterprise-2.1/docker.tar: no such file or directory"
```
I think you might have old version packs installed in `/Library/Application Support/Docker`. I recommend deleting these and then restarting Docker Desktop.

**Comment by Tolsan** [comment]
I have the same issue. Diagnostics uploaded - C4CD8AB5-8A5D-42AA-8926-DB61BDFD1B90/20210505093811

**Comment by alpgokcek** [comment]
I was using v2.4.0, and it was not working after updating to Big Sur 11.3.0. I have completely uninstalled and reinstalled Docker v3.3.2, which fixed the problem. I could not update Docker without uninstalling it because I was getting an error that says one subprocess could not be started. I have executed several factory resets, which did not affect the problem at all. FYI @djs55 . Thanks for the response.

**Comment by spsingh559** [comment]
I had the same issue when I updated my mac to 11.3.1 and my docker version was still 2.3.0.3. I had to install a new docker desktop for mac to fix it.

**Comment by Tolsan** [comment]
A workaround for me was to **turn off** the use of the new Experimental Virtualization framework.
MacOS version: 11.3.1 (M1 CPU)
Docker Desktop version: 3.3.2 (63878)

![image](https://user-images.githubusercontent.com/2084192/117137658-b1944400-adb2-11eb-89a0-d809030d13a0.png)

**Comment by tongyuwang** [comment]
Thanks @djs55! Deleting the /Library/Application Support/Docker directory did the trick! It's interesting that the runtime is looking for docker.tar while the older version pack has docker.iso. Maybe the install/uninstall process should take care of clean up? At any rate, thanks for the workaround! Hopefully this will help others with the same problem.

**Comment by joseluisq** [comment]
It was a persistent issue on Macos 11.3.1 (Intel) even after a reboot but looks like the latest 3.3.2 is going fine.

**Comment by binman-docker** [comment]
I had the same issue, maybe not directly related to OSX version, but after upgrading an old machine from Docker Desktop 2.5 to latest. Removing `/Library/Application Support/Docker` fixed it for me as well.

**Comment by PROsalamoz** [comment]
I had the same issue
on version 3.3.3
<img width="1252" alt="3 3 3" src="https://user-images.githubusercontent.com/42225950/119271044-04b62580-bc00-11eb-947f-da62d2f9fb6d.png">


and I  download older version 3.0.0  and cant start too
<img width="710" alt="3 0 0" src="https://user-images.githubusercontent.com/42225950/119271040-01bb3500-bc00-11eb-80e3-fc76d06e3a20.png">

**Comment by djs55** [comment]
@PROsalamoz could you upload a diagnostics using the command-line in [this comment](https://github.com/docker/for-mac/issues/5651#issuecomment-832517176) and quote the ID here?

**Comment by joseluisq** [comment]
The problem is still happening specially after booting.
It's necessary to kill the process and start the .app again.
