### ISSUE TITLE
M1 docker login & pull fails (timeout) on 3.3.2

### ISSUE THREAD

**Issue by playerx** [docker/for-mac#5654]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`docker login` & `docker pull hello-world` should work

### Actual behavior
There is a timeout error and it doesn't work on 3.3.2, but it works on 3.3.1

### Information

  - macOS Version: 11.3
  - Intel chip or Apple chip: M1 (Apple chip)
  - Docker Desktop Version: 3.3.2

### Steps to reproduce the behavior

1. Run `docker pull hello-world`

**Comment by Rem0ld** [comment]
- macOs Version: 11.2.2
- Intel chip or Apple chip: M1
- Docker Desktop Version: 3.2.2

Same here. 
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by playerx** [comment]
@Rem0ld do you have `3.2.2` or `3.3.2` (latest)?

**Comment by playerx** [comment]
As a workaround you can install 3.3.1 from here:
https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-331

**Comment by Rem0ld** [comment]
> @Rem0ld do you have `3.2.2` or `3.3.2` (latest)?

3.3.2, yes little typo.
Ah yes thanks for that!

**Comment by chrisfarnham** [comment]
I had the same problem just now and fixed it by deselecting "Use new virtualization framework" in the Experimental configuration section of config :/

**Comment by Rem0ld** [comment]
> I had the same problem just now and fixed it by deselecting "Use new virtualization framework" in the Experimental configuration section of config :/

It worked! Thanks

**Comment by MichaelKofler** [comment]
Same for me, deselecting 'new virtual. framework' works. Docker 3.3.3 on Mac M1 mini.

**Comment by ca057** [comment]
`3.3.3` is not working for me as well, neither with not without experimental features.

I got `3.3.1` working, but only by disabling multi-factor authentication.

**Comment by playerx** [comment]
Funny thing is that bug isn't fixed and  Docker app forces me now to update to the latest version (I still use 3.3.1) or buy PRO account.

_Interesting business model ..._

**Comment by genki** [comment]
3.3.3 with new virtualization framework failed on Intel Mac but it had succeeded after getting rid of it.

**Comment by djs55** [comment]
Docker Desktop 3.4.0 has a fix for a DNS issue which could cause login and pull timeout errors. Could you update to 3.4.0 and check if the bug is fixed or not? If it's not, could you upload a fresh set of diagnostics? Thanks in advance!

**Comment by ajardin** [comment]
> Docker Desktop 3.4.0 has a fix for a DNS issue which could cause login and pull timeout errors. Could you update to 3.4.0 and check if the bug is fixed or not? If it's not, could you upload a fresh set of diagnostics? Thanks in advance!

I did the upgrade this morning, and I can confirm that the `Use the new Virtualization framework` option works again on my side.

**Comment by Rem0ld** [comment]
> Docker Desktop 3.4.0 has a fix for a DNS issue which could cause login and pull timeout errors. Could you update to 3.4.0 and check if the bug is fixed or not? If it's not, could you upload a fresh set of diagnostics? Thanks in advance!

I did the upgrade and the option `Use the new Virtualization framework` is working again.

**Comment by MichaelKofler** [comment]
3.4 plus new virt. framework works for me also

**Comment by playerx** [comment]
It's fixed in 3.4 🙌🏻 closing the issue
