### ISSUE TITLE
The requested image's platform does not match the detected host platform

### ISSUE THREAD

**Issue by mecking** [docker/for-mac#5657]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2FE583A-4C44-4E3E-BE7B-BCFC9A14425B

### Expected behavior
1. run docker...
2. OK
### Actual behavior
1. docker run --privileged   --mount type=bind,source=/Users/henrique/code/contiki-ng,destination=/home/user/contiki-ng   --sysctl net.ipv6.conf.all.disable_ipv6=0   -e DISPLAY=docker.for.mac.host.internal:0   -ti contiker/contiki-ng
2. WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested

### Information
A few months ago I encountered a problem after updating the version of the desktop docker. I opened an issue in the contiki project and it was closed after updating the docker:
https://github.com/contiki-ng/contiki-ng/issues/1526
In the comments we can find the following project solution:

"The following issues from docker / for-win seem relevant:
10604 - After Upgrade from Docker 3.2.0 / 3.1.0 to Latest (3.2.1) Java stops functioning inside container
10594 - 3.2.0 appears to virtualize 32-bit executables "
Now after upgrading to version 3.3.2 (63878) the same problem has reoccurred.

  - macOS Version: 11.3.1
  - Intel chip or Apple chip: 1,4 Quad-Core Intel Core i5
  - Docker Desktop Version: 3.3.2

### Steps to reproduce the behavior
  1. git clone https://github.com/contiki-ng/contiki-ng.git
  2. cd contiki-ng
  3. git submodule update --init --recursive
  2. docker run --privileged   --mount type=bind,source=/Users/henrique/code/contiki-ng,destination=/home/user/contiki-ng   --sysctl net.ipv6.conf.all.disable_ipv6=0   -e DISPLAY=docker.for.mac.host.internal:0   -ti contiker/contiki-ng
  3. WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested

**Comment by stephen-turner** [comment]
Thanks for the report, we'll check we haven't regressed this.

**Comment by stephen-turner** [comment]
@mecking Is the container running correctly, just with a warning? Or is it crashing and/or using qemu to run?

**Comment by mecking** [comment]
Hi @stephen-turner,
I reinstalled the desktop docker and now everything is working properly. 
I appreciate your time to help me. I think we can close the issue.

**Comment by stephen-turner** [comment]
OK, thanks, I'll close it.
