### ISSUE TITLE
Docker won't start Cannot register vmnetd: The operation couldn’t be completed. (CFErrorDomainLaunchd error 4.)

### ISSUE THREAD

**Issue by Pablo2904** [docker/for-mac#5658]
- [  ] I have tried with the latest version of Docker Desktop - I need to use this 2.0.0.3 for project reasons
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:958FE1E7-CBB0-425A-91D9-11C3D313B4C2/20210506124904

### Expected behavior
Docker will start
### Actual behavior
Docker Desktop needs privileged access.
and its asking me for a password, after short time its return 
"FATAL ERROR"
Cannot register vmnetd: The operation couldn’t be completed. (CFErrorDomainLaunchd error 4.)
### Information

  - macOS Version: 11.3
  - Intel chip or Apple chip: Intel Core i7
  - Docker Desktop Version: 2.0.0.3  

### Steps to reproduce the behavior
Install
https://download.docker.com/mac/stable/31259/Docker.dmg
Drag Docker and drop into Applications
run docker,
![image](https://user-images.githubusercontent.com/40959412/117303370-e8cf2780-ae7c-11eb-8148-1803eab00d26.png)

system will ass about privalages, then It will crash... with 
![image](https://user-images.githubusercontent.com/40959412/117303307-dbb23880-ae7c-11eb-830b-0c5924087290.png)

Any ideas?

**Comment by stephen-turner** [comment]
Sorry, we're not going to investigate a version that's over two years old.

I'm not sure what could cause you to have to use such an old version, but I would strongly advise against it. For a start we've had security vulnerabilities discovered since then.
