### ISSUE TITLE
Add docker completions for fish shell (and other shells) to Contents/Resources/etc folder

### ISSUE THREAD

**Issue by metyl** [docker/for-mac#566]
### Expected behavior

Possibility to add completions for `fish shell` and other shells from native app Contents/Resources/etc folder.
### Actual behavior

Lack of completions for `fish shell` and other shells (except `bash`) at all.
### Information

Docker [completions for fish shell](https://github.com/docker/docker/blob/master/contrib/completion/fish/docker.fish) is maintained and distributed with docker CLI version.
Native app has completions scripts only for `bash`. 
It would nice to have possibility to link completions for `fish shell`. 

The same applies to completion scripts for others shells maintained in [completion](https://github.com/docker/docker/tree/master/contrib/completion) folder.

**Comment by ijc25** [comment]
These have no been included with the release bundle in docker/docker and the plan is to therefore end up shipping these in the 1.13 version of docker for mac.

**Comment by samoht** [comment]
I think these are now shipped in both the beta and the stable channels. @metyl would you be able to confirm that is the case?

**Comment by metyl** [comment]
I've checked in version 1.13.0-beta39 (15140) and still these have not been included.

**Comment by samoht** [comment]
@justincormack do you know what happened there? I though they were supposed to be included in the release bundle of 1.13.

**Comment by metyl** [comment]
To be precise completions for fish shell are still missing but there have been added completions for zsh including docker, docker-compose and docker-machine.
