### ISSUE TITLE
UI: no information about update

### ISSUE THREAD

**Issue by mnacharov** [docker/for-mac#5660]
<img width="295" alt="Снимок экрана 2021-05-07 в 10 19 15" src="https://user-images.githubusercontent.com/1246847/117402496-f093d800-af1f-11eb-843b-e23048cafd8c.png">

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ]  I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Show some information about update

### Actual behavior

Shows nothing

### Information

  - macOS Version: 11.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.2

### Steps to reproduce the behavior

  1. install and run 3.3.2 version
  2. open update page

**Comment by stephen-turner** [comment]
Thanks for the report, this is fixed in 3.3.3.
