### ISSUE TITLE
M1 mvisonneau/alpine-sqs:1.2.0 stopped working

### ISSUE THREAD

**Issue by Silve2611** [docker/for-mac#5661]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics (i can't)
  - Diagnostics ID: Unfortunately i cannot upload the Diagnostics. It is stuck at uploading for hours. 

### Expected behavior
The SQS should start. 

### Actual behavior
It does not start and throws a java error. 

`sqs_1  | 09:50:41.028 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (1.1.0) started in 1037 ms ===
sqs_1  | #
sqs_1  | # A fatal error has been detected by the Java Runtime Environment:
sqs_1  | #
sqs_1  | #  Internal Error (assembler_aarch64.hpp:1156), pid=3128, tid=0x0000ffff93c1baa0
sqs_1  | #  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
sqs_1  | #
sqs_1  | # JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
sqs_1  | # Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
sqs_1  | # Derivative: IcedTea 3.12.0
sqs_1  | # Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
sqs_1  | # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
sqs_1  | #
sqs_1  | # An error report file with more information is saved as:
sqs_1  | # //hs_err_pid3128.log
sqs_1  | #
sqs_1  | # Compiler replay data is saved as:
sqs_1  | # //replay_pid3128.log
sqs_1  | #
sqs_1  | # If you would like to submit a bug report, please include
sqs_1  | # instructions on how to reproduce the bug and visit:
sqs_1  | #   https://icedtea.classpath.org/bugzilla
sqs_1  | #
sqs_1  | 2021-05-06 09:50:42,988 INFO exited: elasticmq (terminated by SIGABRT; not expected)`

### Information
- It is reproducable if you start the container on a Mac M1 
- The Problem is new. Yesterday ist was working. After a reboot it stopped. 
- The Problem did not appear with an update. However afterwards I downloaded the newest docker version but the problem still persists

- macOS Big Sur Version 11.1
- M1 chip
- Docker Version: 3.3.2 (63878)

### Steps to reproduce the behaviour
Try to start mvisonneau/alpine-sqs:1.2.0

**Comment by giannoug** [comment]
I got the same issue with another image, a custom built `wurstmeister/kafka` image for aarch64 (since they don't officially provide it). Image is based on `openjdk:8u212-jre-alpine`.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=1, tid=0x0000ffff9f4d4aa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# Compiler replay data is saved as:
# /tmp/replay_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```

**Comment by giannoug** [comment]
I managed to solve the issue by building the image using a previous version of the base image. Instead of `openjdk:8u212-jre-alpine`, I used `openjdk:8u201-jre-alpine` and it seems to be working fine until now.

**Comment by Silve2611** [comment]
> I managed to solve the issue by building the image using a previous version of the base image. Instead of `openjdk:8u212-jre-alpine`, I used `openjdk:8u201-jre-alpine` and it seems to be working fine until now.

Thx. But this will not solve my issue. It seems they upadet it and now i crashes. I do not see the possibility to use a previous version.

**Comment by Silve2611** [comment]
I tried uploading the diagnostics. But it is stuck at uploading. 

Does anyone have an Idea how I can solve my this issue? 

I have updated to the newest version yet the problem stays the same.

**Comment by timeBro** [comment]
remove-lifecycle stale

**Comment by Silve2611** [comment]
remove-lifecycle stale

**Comment by Silve2611** [comment]
Why was this closed? It is far from resolved?
