### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to create LLB definition 

### ISSUE THREAD

**Issue by aman2674** [docker/for-mac#5669]
Unable to build image on Mac M1 

My Dockerfile :- 
FROM continuumio/anaconda3:4.4.0
COPY . /usr/app/
EXPOSE 5000
WORKDIR /usr/app/
RUN pip install -r requirements.txt
CMD python app_flasgger.py

whenever I run it.. got error :- 
 => ERROR [internal] load metadata for docker.io/continuumio/anaconda3:4.4.0                                                                                                                          30.1s
------
 > [internal] load metadata for docker.io/continuumio/anaconda3:4.4.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/continuumio/anaconda3/manifests/4.4.0: proxyconnect tcp: dial tcp 192.168.65.1:3128: i/o timeout

**Comment by aman2674** [comment]
And whenever try to pull continummio/anaconda3
with cmd :- docker pull continuumio/anaconda3
got error :-
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by linkinkov** [comment]
@aman2674 at Experimental Features disable new virtualization framework. I dont know why, but in 3.3.1 it work well, but now...

**Comment by natew** [comment]
it's possible to downgrade? anyone know the link to the last version?

**Comment by linkinkov** [comment]
@natew you can download previously version on this page: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by alphavector** [comment]
I encountered the same problem. The problem is present only when experimental features are enabled
https://github.com/docker/for-mac/issues/5663
