### ISSUE TITLE
Docker Desktop for Mac waiting to start. Diagnostics failed to upload, all options failed.

### ISSUE THREAD

**Issue by colincalnan** [docker/for-mac#5671]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - Did not work, got an error "Error invoking remote method 'desktop-go-backend': Error: Internal Server Error"
  - Diagnostics ID: 

### Information

  - macOS Version: 11.3.1 (20E241)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

Docker desktop application runs, but docker fails to start.
Running `docker version` returns 
```
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory
```

Console logs show this error:
```
internal: GET /vm/init 500 "DockerDesktopGo" "during /vm/init: cannot fetch ca-certificates.crt: exit status 49"
```
Which shows up in #5220 but the solution there doesn't work.

I initially started in Catalina with 3.2.0 
Then tried Catalina with 2.5.1
Then upgraded to Big Sur, tried 3.2.0 and 3.3.3
Nothing works.

Experimental features are set to false via `~/.docker/daemon.json and config.json`.

I can't access the preferences screen, it just hangs.

Diagnostics fails to upload `Error invoking remote method 'desktop-go-backend': Error: Internal Server Error`

I'm simply stuck. I've tried every proposed solution on many bug reports but nothing works. I can upload my diagnostics somewhere if that would help anybody solve this issue. I don't really know what else to do.

I've used App cleaner, uninstalled via the Desktop App, I've manually removed all files etc, but nothing work. Every time I start it just hangs on starting.

I have CrowdStrike Falcon sensor installed, I disabled it, it made no difference. I also have Cisco AnyConnect with Umbrella plugin.

**Comment by albertborsos** [comment]
Did you tried "Troubleshhot > Clean / Purge data"? It solved for me.

**Comment by colincalnan** [comment]
@albertborsos I tried every possible situation, 

- Troubleshoot > Clean/Purge
- Troubleshoot > Reset to Factory Settings
- Troubleshoot > Uninstall

**Comment by colincalnan** [comment]
Tried running diagnostics via the command line `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload`

I get the following error 
```
INFO[0034] Error writing:  Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/7F06E9D0-EE97-4E1A-840E-E30237660D33/20210510201238.zip": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25295
Error uploading: Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/7F06E9D0-EE97-4E1A-840E-E30237660D33/20210510201238.zip": x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25295
```

Given the issue above with ca-certificates.crt is there some issue on my machine with certificates?

**Comment by ylbeethoven** [comment]
Docker for mac updated automatically to 3.3.3 and it was extremely slow.

When I tried to downgrade to 3.2.4, it was stuck at reset screen.

Tried 3.0.2, same result.

INFO[0044] Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/82336226-CE64-46F4-BA50-F1D3378DAEC7/20210524120830.zip

Can we purge everything related to docker and do a clean install?

**Comment by KensingtonTech** [comment]
@colincalnan @ylbeethoven  I've been bashing my head against the wall for a few hours on this, and found a solution that worked for me.  In my case, my login keychain had become corrupt (how, I've no idea).  I ran Reset Default Keychains from Keychain Access -> Preferences, after which Docker was finally able to start.

**Comment by colincalnan** [comment]
@KensingtonTech your timing is impeccable, I discovered exactly the same thing yesterday, I believe my recent OSX upgrade from 11.3 -> 11.4 might have caused this. Resetting my Keychain worked and fix a whole host of other cert issues I was having on my machine.
