### ISSUE TITLE
localhost ports not available on browser

### ISSUE THREAD

**Issue by Filipe777** [docker/for-mac#5672]
### Expected behavior
Deploy a docker stack locally and access GUI services on the browser as localhost:<servicePortNumber>

### Actual behavior
Browser shows "localhost didn't send any data"

![image](https://user-images.githubusercontent.com/31474068/117677182-21853e80-b1a6-11eb-8b9c-492c135f5b93.png)

Service is running and accessible via cli.

Running a single container with `docker run -p` works, I can access the GUI from the browser. 

### Information
This started after doing a Docker update. Not sure what version I had before. Right now is as follows:
  - macOS Version: 10.15.7 Catalina
  - Intel chip or Apple chip: 2.2 GHz Quad-Core Intel Core i7
  - Docker Desktop Version: 3.3.1 (63152)
  - Docker Engine Version: 20.10.5

Browsers used:
- Google Chrome Version 90.0.4430.93 (Official Build) (x86_64)
- Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64)

### Docker Diagnostics
ID: AA8C57D5-45E0-4CAD-8A20-B2E683636532/20210510143140

Docker Diagnosis Report:
[20210510143140.zip](https://github.com/docker/for-mac/files/6452957/20210510143140.zip)

It has the same OS version as before, no OS updates made.

Thank you in advance.

**Comment by stephen-turner** [comment]
When you say "stack", are you using `docker stack deploy` or `docker-compose up`? If it's the former, then I think this is a dupe of #5610.

**Comment by Filipe777** [comment]
`stack deploy` 

So sorry, it is exactly as #5610. Thank you.
