### ISSUE TITLE
Text description on Dev environments screen has grammar error. 

### ISSUE THREAD

**Issue by kadecole** [docker/for-mac#5674]
<img width="1362" alt="Screen Shot 2021-05-10 at 5 21 38 PM" src="https://user-images.githubusercontent.com/6461177/117731740-454f8100-b1b4-11eb-8bfb-00bb8a5a926c.png">

  - [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Text description on Dev environments screen has no grammar error. 

### Actual behavior
Text as is is below:
Sharing work-in-progress code quickly for someone to “just take a look” is hard when people need to move between git branches to **look get** your code onto their machine. Dev Environments look to solve this by removing the friction to get started and making the sharing of code in containers simple.

### Information

  - macOS Version: 11.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3 (64133)

### Steps to reproduce the behavior

  1. Open Docker Desktop.
  2. Click on the Dev Environments option.

**Comment by stephen-turner** [comment]
Thanks, I've passed this on to the development team.
