### ISSUE TITLE
Unable to start Docker Desktop with the latest version 3.3.3

### ISSUE THREAD

**Issue by mmatur** [docker/for-mac#5676]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BBAD0C71-D42F-4C8C-A144-D0E7D4D42D94/20210511101343

### Expected behavior

Docker Desktop starting.

### Actual behavior

Since few days, my Docker Desktop is no more working. I tried with the following version

- 3.3.3 -> Not working -> Diagnostics ID: BBAD0C71-D42F-4C8C-A144-D0E7D4D42D94/20210511101343
- 3.3.2 -> Not working
- 3.3.1 -> Not working
- 3.3.0 -> Not working
- 3.2.2 -> Not working
- 3.2.1 -> Not working
- 3.2.0 -> Not working
- 3.1.0 -> Not working
- 3.0.4 -> Working

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

1. Install Docker version 3.3.3
2. Docker is blocked on "Starting"
3. Preferences are not accessible

Before installing the new version, I cleaned everything with the following commands:
- `/Applications/Docker.app/Contents/MacOS/Docker --uninstall`
- `rm -rf ~/.docker`

But it does not change anything.

**Comment by rogerbock** [comment]
I can confirm that downgrading to 3.0.4 fixes the problem for me.

**Comment by dresende** [comment]
I was having the same problem, but since I was reading this and other issues, I didn't kill it. And after a minute or two, Docker asks me for privilege access, I type my password and it just starts normally.

**Comment by jedireza** [comment]
I was experiencing this with an M1 MacBook. I downloaded the latest (3.3.3) installer and replaced the current app and things are working again.

**Comment by chadbrewbaker** [comment]
I'm having a similar problem on my M1. I downloaded the (May 8?) release last night. Docker doesn't startup up when clicked. I also think it had something to do with hosing my OS as I had to go into recovery mode last night and re-install Big Sur 11.4.

Is there a manifest of all the files that Docker for Mac touches so I can try to clean them all out?

**Comment by mmatur** [comment]
I have updated my docker desktop to version v3.5.1 and it works now. Can't explain what was failing.
