### ISSUE TITLE
Too many HTTP redirects

### ISSUE THREAD

**Issue by rajeshroshanprasad** [docker/for-mac#5679]
<img width="477" alt="Screen Shot 2021-05-11 at 1 26 02 PM" src="https://user-images.githubusercontent.com/29008029/117879990-708dab00-b25c-11eb-992a-929c6b61d698.png">

Too many HTTP redirects on mac os docker desktop app

Not able to pull the images from the repo

https://stackoverflow.com/questions/24060099/how-to-fix-dockers-error-pulling-image-too-many-redirects-failures-while-pu

Used the above stackoverflow to find a resolution but its not working.

**Comment by stephen-turner** [comment]
Other people aren't reporting this, so I think it must be something in your local networking/proxy/VPN setup.
