### ISSUE TITLE
Kicked out of docker container

### ISSUE THREAD

**Issue by feus4177** [docker/for-mac#568]
### Expected behavior
When I run `docker exec -it $CONTAINER_ID bash` I should stay attached indefinitely.

### Actual behavior
I get kicked out periodically with the following error: `Error response from daemon: dial unix /Users/username/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused`

### Information

Diagnostic ID: 75D42165-85DB-4BC9-BADE-2F530E170F45
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Attach to a container using the command `docker exec -it CONTAINER bash`
2. wait

I should also add that I will usually be attached to the same container 2 or 3 times. However, since it never happens immediately after I attach to a container I would assume it doesn't have to do with that. Also, sometimes I will be attached to a couple different containers. The error only seems to happen after a long time (1 day+).

**Comment by jnovack** [comment]
I increased the memory allocated to Docker from 2GB to 6GB and I am not running into this issue as much.

**Comment by trengrj** [comment]
I'm getting the same error when running something cpu intensive (indexing with elasticsearch). I do get less errors if I run with more RAM but it doesn't fix the issue.

**Comment by feus4177** [comment]
I tried increasing my memory today but I still got kicked out.

**Comment by gamb** [comment]
Upped RAM, but regularily hitting issue when running `gunicorn` with `--reload` flag. Worked fine under Docker Toolbox/VirtualBox.

> MacBook Pro (Retina, 13-inch, Early 2015)
> 2.9 GHz Intel Core i5
> 8 GB 1867 MHz DDR3

**Comment by samoht** [comment]
Maybe related to timekeeping in the VM, /cc @ijc25 

Detected symptom of problem 'moby-kernel-froze' in 75D42165-85DB-4BC9-BADE-2F530E170F45/20160909-083743.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Sep  9 08:27:16 USBLU004539MAC kernel[kern][0] <Notice>: com.docker.front[58138] triggered unnest of range 0x7fff82a00000->0x7fff82c00000 of DYLD shared region in VM map 0x10afc360589c2097. While not abnormal for debuggers, this increases system memory footprint until the target exits.
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Warning>: VM: 2016-09-09 03:22:26 +0000 UTC daemon.warn chronyd: Forward time jump detected!
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Notice>: VM: 2016-09-09 03:22:26 +0000 UTC daemon.info chronyd: Can't synchronise: no selectable sources
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Error>: VM: 2016-09-09 03:22:26 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Error>: VM: 2016-09-09 03:22:26 +0000 UTC kern.error kernel: 	1-...: (1 ticks this GP) idle=1a3/1/0 softirq=207495/207495 fqs=0
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Error>: VM: 2016-09-09 03:22:26 +0000 UTC kern.error kernel: 	 (t=1086109 jiffies g=107115 c=107114 q=1)
Sep  9 08:27:16 USBLU004539MAC Docker[com.docker.driver.amd64-linux][55926] <Error>: VM: 2016-09-09 03:22:26 +0000 UTC kern.error kernel: rcu_sched kthread starved for 1086109 jiffies! g107115 c107114 f0x0 s3 ->state=0x1
```

**Comment by mttkay** [comment]
Why was this closed? I'm also seeing this issue with the latest Docker for Mac beta (1.13.1-rc2-beta41 (15300))

**Comment by mttkay** [comment]
I fixed the issue by wiping my Docker beta installation and reinstalling from scratch from the stable channel. Not sure if this was a state related issue or something specific to the beta version. :man_shrugging:

**Comment by fabriziocucci** [comment]
Same issue here with `Version 17.03.1-ce-mac12 (17661)`:

```shell
Unexpected API error for composeproject_mydb (HTTP code 500)
Response body:
dial unix /Users/USERNAME/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

Is there a real solution to this?

**Comment by mrosett** [comment]
Managed to get a workaround by upping RAM. No clue what the actual underlying cause is.
