### ISSUE TITLE
On M1, can't get past "Docker needs priviled access"

### ISSUE THREAD

**Issue by LeaMaronet** [docker/for-mac#5682]
When I launch Docker desktop I get asked for my password :

<img width="895" alt="Capture d’écran 2021-05-12 à 23 46 42" src="https://user-images.githubusercontent.com/73174087/118048315-6531a100-b37c-11eb-85a1-28b98f410bef.png">

I provide my password, there is a slight delay, then I get asked again. 

- [x] I downloaded Docker Desktop for Apple silicon
- [x] I allowed full disk access to Docker 
- [x] I desactivated FileVault

**Comment by Denis-Step** [comment]
Do you have command-line tools for XCode downloaded? (not part of the Docker team but I've had this problem)

**Comment by ezequiel2611** [comment]
The same happened to me and solved it after doing <sudo rm -rf /Library/LauchDaemons/com.docker.vmnetd.plist> After that when lauching docker the elevated privileges prompt appeared only the first time.

PD: I have Xcode CLT installed
PD2: There is no reason for that prompt, in Docker for Intel Chip it works fine, hope a quick solution for that.
