### ISSUE TITLE
Cannot start docker 

### ISSUE THREAD

**Issue by simeonstefanov** [docker/for-mac#5687]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 4AE314A9-7FA0-48D8-9DB3-851C0BDDC40B/20210514104030

### Expected behavior
Docker starts

### Actual behavior
Docker is hanging at "Docker Engine starting..."

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes. I have installed the application completely and installed again  
  - Is the problem new? Yes, before couple of weeks everything worked
  - Did the problem appear with an update? No

  - macOS Version: Big Sur 11.3.1
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

  1. Install Docker for Mac
  2. Start Docker app from Applications
  3. UI shows "Docker Engine starting..." and never completes this step

**Comment by quadespresso** [comment]
Ran into this a couple of weeks back after upgrading to v3.3.3. Tried various ways to get around it, including the usual recommended troubleshooting options, without success.

I've just now installed v3.4.0 and... so far, so good!

**Comment by simeonstefanov** [comment]
v3.4.0 works for me as well. Thanks!
