### ISSUE TITLE
Each new app window creates a new dock icon next to the pinned one

### ISSUE THREAD

**Issue by niccolomineo** [docker/for-mac#5689]
### Expected behavior

If Docker for Mac's Dashboard is pinned to the dock and, say, "About Docker Desktop" is opened, this new window should reopen from the same icon. 

### Actual behavior

A new icon appears in the dock.

<img width="280" alt="Schermata 2021-05-14 alle 17 04 05" src="https://user-images.githubusercontent.com/5409469/118290318-9aea9d00-b4d6-11eb-89d4-0296c9704a7b.png">

### Steps to reproduce the behavior

  1. Open the Docker for Mac app
  2. Open the Dashboard
  3. Pin the Docker for Mac app to the dock
  4. Open "About Docker Desktop"
  5. A new icon appears in the dock

**Comment by niccolomineo** [comment]
I would like to point out I haven't been able so far to attribute this issue to a specific action, but it indeed it happens.

**Comment by aenriquezgentile** [comment]
Same problem here.
macOS Big Sur Version 11.2.3
Docker Desktop Version 3.4.0 (3.4.0.5223)

**Comment by ShadowLNC** [comment]
Potentially a regression of #4914

Docker Desktop 3.5.0 (66024)
MacOS Big Sur 11.4

I have the Docker Desktop app pinned to my dock.

Choosing "About Docker Desktop" from the menu bar _does not_ appear to create a new icon.
Choosing "Dashboard"/"Preferences" _sometimes_ creates a new icon.


Clicking the dock icon _always_ creates a new icon (so I now have the Docker Desktop icon on my dock, plus 3 additional "Dashboard" icons in the dock's "recently used" area labelled "Docker Desktop" with the same logo as the real one). Clicking any one of these 3 additional icons triggers the original icon to bounce, then it invokes a new subprocess which generates a new icon (shunting the least-recently-used one off the dock's recent items).

**Comment by aenriquezgentile** [comment]
Solved for me after upgrading to version 3.5.1 (66090).
But I also did choose "reset to factory defaults" option because Docker was not opening after upgrading.

**Comment by trentprynn** [comment]
/remove-lifecycle stale

issue for me
macos 12.0 on m1 chip
docker 4.2.0

**Comment by trentprynn** [comment]
Just verified that this is **not** an issue for me anymore!

macos 12.2 on m1 chip
docker 4.4.2 (73305)

**Comment by MSzmaj** [comment]
Yes. It seems to be working (almost) as intended. On my machine clicking on it I get a weird rubberbanding animation when opening the app. Not a big issue, most likely an OS issue and not an issue with the docker app.

macos 12.1 m1
docker 4.4.2 (73305)
