### ISSUE TITLE
After updated MacOS (Big sur 11.3.1)  : Docker not open and run

### ISSUE THREAD

**Issue by hortenssiaa** [docker/for-mac#5690]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 786BDA6F-95EA-4540-AC2E-7ED4255EDA27/20210515032255
  - >> when docker shows error 'The operation couldn’t be completed. (Docker.VmnetdError error 1.)', diagnostics were available and showed the first Diagnostics ID (786BDA6F-95EA-4540-AC2E-7ED4255EDA27/20210515032255). 
  But, when docker shows another error 'The data couldn’t be read because it is missing.', diagnostics were unavailable and I command '/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload',  and I got a different Diagnostics ID below.
  
  - Diagnostics Bundle: /tmp/786BDA6F-95EA-4540-AC2E-7ED4255EDA27/20210515035202.zip
  - Diagnostics ID:     786BDA6F-95EA-4540-AC2E-7ED4255EDA27/20210515035202 (uploaded)
  

### Expected behavior

Docker should open & run successfully

### Actual behavior

When opening Docker for desktop it shows errors
1. 'Fatal Error The operation couldn’t be completed. (Docker.VmnetdError error 1.)' 
2. 'The data couldn’t be read because it is missing.'

### Information

  - macOS Version: Big Sur 11.3.1 (20E241)
  - Intel chip or Apple chip: intel 
  - Docker Desktop Version: 19.03.8
  - 
<img width="653" alt="Screen Shot 2021-05-15 at 12 49 08 PM" src="https://user-images.githubusercontent.com/16066576/118347169-05094d80-b57c-11eb-85ee-e8ed73c4af40.png">

### Steps to reproduce the behavior

  1. I downloaded Virtual Machine, after that docker was working well. (But suddenly Oracle sqldeveloper isn't opened.)
  2. Updated MacOS version to Big Sur 11.3.1 (20E241) and docker shows error 'The data couldn’t be read because it is missing.'
  3. in https://github.com/docker/for-mac/issues/4526, I get helped that in this situation, removing Virtual Box and reinstalling docker version 'Docker Desktop Community 2.2.0.5' could help.
  4. I removed Virtual Box and installed the version, but docker showed new error 'The operation couldn’t be completed. (Docker.VmnetdError error 1.)'
  5. And then I rebooted and restarted docker and it shows error 'The data couldn’t be read because it is missing.' again.
  -> How Can I do for it? I am worried that if I reinstall Docker, all of my data will be deleted.
  
<img width="688" alt="Screen Shot 2021-05-15 at 12 42 38 PM" src="https://user-images.githubusercontent.com/16066576/118347038-10a84480-b57b-11eb-9331-25ec7aa37c6c.png">
-> I tried Docker software updating with the button, but it's not working due to error below.

<img width="710" alt="Screen Shot 2021-05-15 at 12 42 32 PM" src="https://user-images.githubusercontent.com/16066576/118347040-13a33500-b57b-11eb-8e13-08c60e82e20b.png">

**Comment by yong-asial** [comment]
@hortenssiaa  i resolved it by reinstall a newer docker version.

**Comment by samesmile** [comment]
@hortenssiaa you may use this way with last update
1. Delete docker app
2. brew install --cask docker
3. Open docker

https://github.com/docker/for-mac/issues/4526#issuecomment-793113938

I facing this problem today and solve it via steps above

**Comment by hortenssiaa** [comment]
>  @yong-asial 
I reinstalled it and resolved it. This helped me a lot! Thank you :)

**Comment by hortenssiaa** [comment]
> @samesmile 
I deleted and reinstalled docker. 
Now it runs well! this helped me a lot! Thank you :)
