### ISSUE TITLE
unable to run 2 cassandra container on apple m1

### ISSUE THREAD

**Issue by junglechange** [docker/for-mac#5701]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
run 2 cassandra container

operations
1. docker pull cassandra
2. docker run --name casscon1 cassandra
3. docker run --name casscon2 cassandra

### Actual behavior
casscon1 exited(137) when casscon2 start
### Information

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: apple chip
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

1. docker pull cassandra
2. docker run --name casscon1 cassandra
3. docker run --name casscon2 cassandra

**Comment by stephen-turner** [comment]
What is the architecture of these containers? Are they amd64 or arm64? You should be aware that running amd64 (Intel) containers is done under emulation, and is best-effort only.
