### ISSUE TITLE
Processes in containers cannot reach host services via host.docker.internal

### ISSUE THREAD

**Issue by willemnviljoen** [docker/for-mac#5707]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BAD52D6A-11D1-47DA-9E62-152C809A6FC2/20210520054652

### Summary

Processes inside containers can't communicate with the host via host.docker.internal. The hostname resolves inside the container, but not communication is possible.

Trying exactly the same communication from the container to the IP of any other interface on the host works as expected. Please see steps to reproduce below.

### Expected behavior

Processes inside containers should be able to communicate with processes on the host by using host.docker.internal.

### Actual behavior

Connections from processes inside containers to host.docker.internal time out.

  - Is it reproducible?

  Yes, see steps below.

  - Is the problem new?

  Unsure, I have only recently switched to an M1 based Mac, and encountered this problem for the first time.

  - Did the problem appear with an update?

  Unsure, see above.

  - A reproducible case if this is a bug, Dockerfiles FTW.

  See steps below, can be easily reproduced with any container which has netcat, I use alpine for this test, but it happens for any container based on any base image, and any process. Discovered while trying to connect xdebug inside a container to an IDE on the host.

  - macOS Version: 11.3.1
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.3.3, engine 20.10.6

### Steps to reproduce the behavior

1) Start a netcat listener process on the host
```
nc -l 8085
```

2) In another terminal session, start a container, add an environment variable to pass in the LAN IP, so that it is possible to test with that and with host.docker.internal

```
docker run -e LAN_IP=`ifconfig -l | xargs -n1 ipconfig getifaddr` -it --rm alpine
```

3) Inside the container, send a message to the netcat process on the host via the LAN IP:

```
echo "Hi, this is a message via the LAN IP" | nc $LAN_IP 8085
```

The process should exit immediately, and your other terminal session should show output similar to this:
```
$ nc -l 8085
Hi, this is a message via the LAN IP
```

4) Start another netcat listener process on the host
```
nc -l 8085
```

5) In the container, try to send a message to the host via host.docker.internal
```
echo "Hi, this is a message via host.docker.internal" | nc host.docker.internal 8085
```

At this point the process in the container will hang and eventually time out. The process on the host
will keep listening without producing output until you stop it with Ctrl+C. 

It's clear that the container can communicate with the host or the internet, and it's clear that host.docker.internal resolves, (try ping host.docker.internal in the container), but no actual IP traffic seems to be able to flow to the address.

**Comment by djs55** [comment]
@willemnviljoen Docker Desktop 3.4.0 fixed a bug in this area, could you update and let me know if it works or not? If it doesn't, could you upload a fresh set of diagnostics and quote the ID here? Thanks in advance.

**Comment by willemnviljoen** [comment]
@djs55 I've updated to 3.4.0, it works as expected. Thanks very much.
