### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped on Apple Silicon M1 arm64

### ISSUE THREAD

**Issue by davidszotten** [docker/for-mac#5711]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics 
  - Diagnostics ID: (docker itself doesn't crash, doesn't show diagnostics id)

### Expected behavior

No segfault

### Actual behavior

```
...
  adding: awsglue/transforms/drop_nulls.py (deflated 66%)
  adding: awsglue/transforms/collection_transforms.py (deflated 79%)
  adding: awsglue/data_source.py (deflated 58%)
  adding: awsglue/utils.py (deflated 69%)
  adding: awsglue/functions.py (deflated 53%)
[INFO] Scanning for projects...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped            <--------
/home/aws-glue-libs/bin/glue-setup.sh: line 19:    30 Segmentation fault      
...
```

### Information
Doesn't seem to happen on intel macs i've tried it on

Segfaults every time on my m1

  - macOS Version: 11.2.3
  - Apple M1
  - Docker Desktop Version: Docker Desktop 3.3.3 (64133)

### Steps to reproduce the behavior

```
docker run -ti --platform=linux/amd64 --rm amazon/aws-glue-libs:glue_libs_1.0.0_image_01 /home/aws-glue-libs/bin/gluepyspark
```

**Comment by stephen-turner** [comment]
It is normal (and as documented) for some amd64 containers not to be able to run on an arm64 machine.
