### ISSUE TITLE
docker-for-mac: Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable

### ISSUE THREAD

**Issue by nevergiveup777** [docker/for-mac#5713]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ADAF07C9-D6A7-4639-8DAE-7D83FE8E5393/20210524081848

### Expected behavior
1.  $ docker pull phpmyadmin
2. image is pulled
### Actual behavior
1. $ docker pull phpmyadmin
2. Using default tag: latest
    Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable

### Information

  - macOS Version: 11.2.3 (20D91)
  - Intel chip or Apple chip: 2.6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.3.3(64133)

### Steps to reproduce the behavior

  1. run docker for mac
  2. docker pull phpmyadmin

**Comment by ezplanet** [comment]
I have the same problem:
$ docker --version
Docker version 20.10.6, build 370c289
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

NO PROXY, MacBook has direct internet access. No issues with internet access from any other application

**Comment by nevergiveup777** [comment]
I was able to fix the issue by going to **Troubleshoot -> Reset to factory defaults**

It looks like they changed something in the last update that broke the DNS to resolve the URL.

**Comment by davehun** [comment]
turning off "Use new virtualization framework" fixed it for me

**Comment by dunklesToast** [comment]
Awesome. Now they force us to do updates and these updates break Docker. Fucking geniuses.

**Comment by davehun** [comment]
- Diagnostics ID: DB1C9C6B-BCCF-446B-81D3-2CE33AEC520A
@docker-desktop-robot this also affects   version/3.3.3

**Comment by djs55** [comment]
@nevergiveup777 There are some DNS fixes in version 3.4.0. Could you update to this version and see if the problem reproduces? If it does, could you upload a fresh set of diagnostics?

**Comment by rafibarash** [comment]
This keeps happening to me as well, cannot figure out how to fix for the life of me

**Comment by nevergiveup777** [comment]
It was resolved for me. Thanks
