### ISSUE TITLE
Update notification popup doesn't actually notify

### ISSUE THREAD

**Issue by buggtb** [docker/for-mac#5714]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 32E4898A-66DD-4A98-A5B8-713D57DF190F/20210524105949

### Expected behavior

The popup actually triggers an upgrade.

### Actual behavior

The new popup about upgrading has been popping up daily for days, I click upgrade and nothing happens, but also no error. Then the next day, the popups return.

### Information
  - macOS Version: Catalina
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.0

Has been happening for a week or so that I have noticed.

**Comment by StefanScherer** [comment]
Hi @buggtb 
Thanks for the diagnostics data. Technically I cannot see a problem. 

The popup when an update is available or when it reminds you every day does not download the update. We got feedback from our users that they want to control when we download things and it shouldn't happen automatically.

<img width="686" alt="docker-desktop-update-available" src="https://user-images.githubusercontent.com/207759/119376849-bca90880-bcbc-11eb-81c5-3f89bc1f6a4f.png">

So, when you click on "Install and Restart" it actually starts the download. I agree that the wording is not optimal here. The whale icon in the dock shows a spinning arrow and the menu shows that it's currently downloading and update.

<img width="343" alt="docker-desktop-downloading-update" src="https://user-images.githubusercontent.com/207759/119377115-098cdf00-bcbd-11eb-97b1-95a024e169f6.png">

Once it has finished the download the whale icon changes again and shows a small exclamation mark. The menu also shows an "Update and restart" action.

![docker-desktop-update-and-restart](https://user-images.githubusercontent.com/207759/119377217-29240780-bcbd-11eb-8cdc-69cd4ff8d16f.jpg)

After clicking this menu item the update will be installed.

I hope that helps you to get out of the popup loop.
We're always working to make the update experience better so thanks for the feedback.

**Comment by buggtb** [comment]
Thanks @StefanScherer I see it now, I sorta expected a notification in the main UI, I rarely click on that icon, to be honest I forgot it was there, but thats fine, thanks for checking!
