### ISSUE TITLE
Docker Desktop keep starting 

### ISSUE THREAD

**Issue by doanbutar** [docker/for-mac#5717]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:  5FAF7DC5-2E9A-4D68-B925-526B54696048/20210525063102

### Expected behavior
Able to use Docker Desktop

### Actual behavior
Docker Desktop keeps starting forever

### Information
Prior to this issue, 
1. I added `/var/log/pods` to the folder sharing under `resources`. After this change, the docker desktop keeps `starting`. 
2. I am using Docker Desktop 3.1.0

After the issue happening, 
1. I deleted my docker resources using the following commands, 

- sudo rm -Rf /Applications/Docker
- sudo rm -f /usr/local/bin/docker
- sudo rm -f /usr/local/bin/docker-machine
- sudo rm -f /usr/local/bin/docker-compose
- sudo rm -f /usr/local/bin/docker-credential-osxkeychain
- sudo rm -Rf ~/.docker
- sudo rm -Rf $HOME/Library/Containers/com.docker.docker

2. Restarted my laptop
3. Uninstall docker and upgrade to the latest version but the issue still persist.

**Comment by harrouet** [comment]
This happens to a lot of people unfortunately, and no one at Docker seems to take this seriously.
See #5507 as an example.

**Comment by grantkee** [comment]
I'm having the same issue and can't deploy latest changes to production.
