### ISSUE TITLE
[Feature request] Right click on docker status icon opens dashboard

### ISSUE THREAD

**Issue by niccolomineo** [docker/for-mac#5718]
The problem I am noticing is the Dashboard is too hidden away for the every-day usage.

As right-clicking on the icon to open the menu is non-standard (none of the native MacOs iconized functionalities, such as "Sound", interpret right-clicking that way), I would like to propose using it to open the Dashboard directly.

**Comment by stephen-turner** [comment]
That's how it works on Windows, where it's normal to open the application with left-click on the system tray icon and the menu with right-click.

On Mac, I don't think we want to use right-click on the menu bar, as it's not discoverable. Clicking on the big icon in the Dock brings up the dashboard, which I think is a more standard idiom: does that work for you?

**Comment by niccolomineo** [comment]
It does work, but, as pointed out [here](https://github.com/docker/for-mac/issues/5689), sometimes a new app icon appears, which unexpectedly clutters the Dock.
