### ISSUE TITLE
macOS: Terminal application by Configuration over Convention

### ISSUE THREAD

**Issue by marcofeltmann** [docker/for-mac#5721]
### Context

Since my macOS is managed and some IT guys force me to install that awful iTerm2.app as a base-configuration set I cannot get rid off, the conventional "default shell" feature of Docker Desktop always gets in my way.
"Cannot get rid off" literally translates to "is re-installed automatically every damn bloody morning at ~2:00 UTC". 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior

At some point in the settings I am able to choose which Terminal application I'd like to use when I `CLI` into a docker container.

### Actual behavior

Well. I'm not. 
Docker Desktop seems to look for an runnable installation of iTerm2.app and always prefers it over the common Terminal.app 

### Information

As mentioned above this is some kind of bloody edge case:
You *have* `iTerm.app` installed together with `Terminal.app` although you *don't* want `iTerm.app` **and** cannot reliable uninstall `iTerm.app`.

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: 3,2 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.3.3 (64133)

I'd be totally happy with some preference property list key or something to disable this conditional `iTerm.app` behavior but since Docker Desktop isn't OSS I cannot simply search the source for a solution… 😟

**Comment by stephen-turner** [comment]
We do have a feature request for letting people configure their favourite terminal, but we implemented "choose iTerm2 if installed" as a quick fix for the many users who were clamouring for it. I admit we didn't consider the possibility that someone has iTerm2 installed but doesn't like it and can't uninstall it.
