### ISSUE TITLE
Unable to launch Docker on Apple Mac Mini with M1 chip, BigSur OS

### ISSUE THREAD

**Issue by kyrindesign** [docker/for-mac#5727]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D7E3344F-92CA-47BE-8B67-3DFD3ADF1081/20210528190706

### Expected behavior
to work properly with no issues

### Actual behavior
I want to develop a Drupal website hosting on Pantheon locally by using Lando and Docker. Docker works just fine on my Macbook with intel chip, but on the Mac mini with M1 chip it keeps exiting with code 0. Thanks in advance. 

### Information

  - macOS Version: Big Sur
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Adetunjii** [comment]
Do you have rosetta installed??
If you don't, you can install it by doing softwareupdate --install-rosetta in your terminal

**Comment by kyrindesign** [comment]
@Adetunjii I did.

**Comment by Adetunjii** [comment]
Okay. Can you help me walkthrough the problem you're facing?

**Comment by Adetunjii** [comment]
Or if you can just tell me the steps to reproduce to create the issues you're having so I can know how best to help

**Comment by kyrindesign** [comment]
![Screen Shot 2021-05-28 at 3 38 52 PM](https://user-images.githubusercontent.com/80861381/120047982-cf785180-bfca-11eb-8798-441000d0f5d0.png)
![Screen Shot 2021-05-28 at 3 39 12 PM](https://user-images.githubusercontent.com/80861381/120048005-db641380-bfca-11eb-9b2a-1a5b16e3c0af.png)
![Screen Shot 2021-05-28 at 3 39 50 PM](https://user-images.githubusercontent.com/80861381/120048041-f3d42e00-bfca-11eb-9838-bc0d0900c2bb.png)

**Comment by kyrindesign** [comment]
[20210528225039.zip](https://github.com/docker/for-mac/files/6563608/20210528225039.zip)

The diagnostics

**Comment by Adetunjii** [comment]
I don't think this is a docker related issue.
Your container seems to be running just fine. It's an app specific issue.

**Comment by StefanScherer** [comment]
Hello @kyrindesign 
As @Adetunjii already commented, the problem is application specific and not related to Docker Desktop.
Maybe one of the images you use is not available for arm64 and doesn't work correctly in emulation. Maybe you could ask the creator of these images what might be the issue.
The official Drupal image on Docker Hub for example is multi-arch, but we cannot help you debug your specific docker compose environment.
