### ISSUE TITLE
Android toolchain is not installing flutter docker in MBP M1

### ISSUE THREAD

**Issue by ChkBuk** [docker/for-mac#5728]
- [x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
<img width="675" alt="Screenshot 2021-05-31 at 12 11 22 AM" src="https://user-images.githubusercontent.com/33537268/120111544-e5da0500-c1a4-11eb-8c6c-7e957fc3079e.png">

### Actual behavior
<img width="659" alt="Screenshot 2021-05-31 at 12 12 58 AM" src="https://user-images.githubusercontent.com/33537268/120111574-02763d00-c1a5-11eb-8920-994ed0f248e4.png">

### Information

  - macOS Version: 
  - 
<img width="528" alt="Screenshot 2021-05-31 at 12 14 07 AM" src="https://user-images.githubusercontent.com/33537268/120111627-3ea99d80-c1a5-11eb-9714-259c1a3d329e.png">

  - Intel chip or Apple chip:
  - Docker Desktop Version:
<img width="498" alt="Screenshot 2021-05-31 at 12 15 42 AM" src="https://user-images.githubusercontent.com/33537268/120111650-5ed95c80-c1a5-11eb-9f54-4bd3603bd1e9.png">

### Steps to reproduce the behavior
Follow these steps in this post.
https://medium.com/inspireui/build-your-flutter-apps-effortlessly-with-docker-336f139a322d

  1. Docker file is as follows

FROM ubuntu:18.04
   
# Prerequisites
RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget
   
# Set up new user
RUN useradd -ms /bin/bash developer
USER developer
WORKDIR /home/developer
   
# Prepare Android directories and system variables
RUN mkdir -p Android/sdk
ENV ANDROID_SDK_ROOT /home/developer/Android/sdk
RUN mkdir -p .android && touch .android/repositories.cfg
   
# Set up Android SDK
RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
RUN unzip sdk-tools.zip && rm sdk-tools.zip
RUN mv tools Android/sdk/tools
RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses
RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29"
ENV PATH "$PATH:/home/developer/Android/sdk/platform-tools"

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/home/developer/flutter/bin"
   
# Run basic check to download Dark SDK
RUN flutter doctor
  2. ...devcontainer.json
  {
    "name": "flutter_docker",
    "context": "..",
    "dockerFile": "../Dockerfile",
    "remoteUser": "developer",
    "settings": {
        "terminal.integrated.shell.linux": null
    },
    "runArgs": ["--privileged"],
    "extensions": ["dart-code.flutter"],
    "workspaceMount": "source=${localWorkspaceFolder}/workspace,target=/home/developer/workspace,type=bind,consistency=delegated",
    "workspaceFolder": "/home/developer/workspace"
   }

As a result , I am unable to run 'adb' and could not run my flutter app on android physical device.
It has mentioned that these kind of toolchain issues had with Docker Desktop version earlier. Anybody can help me to resolve this issue?

**Comment by StefanScherer** [comment]
Hello @ChkBuk 
This doesn't look like a bug in Docker Desktop. 
You should ask for help at Flutter how to get every tools installed in an linux/arm64 image.
