### ISSUE TITLE
Docker Desktop for Mac 3.3.3 - M1 not building images.

### ISSUE THREAD

**Issue by dannewnsjump24** [docker/for-mac#5734]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: F0724C59-54D7-4340-A528-3F1F1A2E3605/20210604180711

### Expected behavior
Running Docker Compose up -d --build will build all of the images defined in the docker-compose file. This issue seems to happen for every docker container i now have on the machine

### Actual behavior
This worked prior to the update to 3.3.3 but now this is no longer working with the following error

```
------
 > [internal] load metadata for docker.io/library/php:7.3-fpm-alpine:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/php/manifests/7.3-fpm-alpine: net/http: TLS handshake timeout
```
Im running a fibre connection at both office at home so internet speed isnt the issue and on my other mac (Intel) this works fine so im not sure if this is specific to the M1 chipset.

Thanks
### Information

  - macOS Big Sur 11.4
  - Apple Chip Macbook Pro
  - 3.3.3(64133)

**Comment by dannewnsjump24** [comment]
just as an update ive reverted back to version 3.3.1 and all is working as expected

**Comment by StefanScherer** [comment]
Maybe a duplicated of #5680, but I see that you have disabled the new virtualisation framework in the settings. 🤔

**Comment by djs55** [comment]
I suspect this was caused by a DNS bug which was fixed in Docker Desktop 3.4.0. Please update and let us know whether it works or not. If it doesn't work, please upload a fresh set of diagnostics and quote the ID here. Thanks in advance!

**Comment by dannewnsjump24** [comment]
Ive just updated to 3.4.0 and now i get the folliwng error

```failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/nginx/manifests/latest: x509: certificate is valid for *.seon.io, *.admin.seon.io, *.api.seon.io, not registry-1.docker.io```

**Comment by djs55** [comment]
@dannewnsjump24 that looks like a different issue. Do you know if you (or your network) is running some kind of MITM proxy which would replace the certificate?

Could you try 2 quick tests:

1. try the build without buildkit, `DOCKER_BUILDKIT=0 docker build` . If this works but regular `docker build` does not, then it means your host has a trusted CA which buildkit does not know about.

2. query the TLS cert from the Mac directly with:
```
% openssl s_client -connect registry-1.docker.io:443
CONNECTED(00000006)
depth=4 C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
verify return:1
depth=3 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Services Root Certificate Authority - G2
verify return:1
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = *.docker.io
verify return:1
---
Certificate chain
 0 s:/CN=*.docker.io
   i:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
 1 s:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
   i:/C=US/O=Amazon/CN=Amazon Root CA 1
 2 s:/C=US/O=Amazon/CN=Amazon Root CA 1
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
 3 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
   i:/C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIF1TCCBL2gAwIBAgIQC4w2dqryzV0OctnMuh4j9TANBgkqhkiG9w0BAQsFADBG
MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRUwEwYDVQQLEwxTZXJ2ZXIg
Q0EgMUIxDzANBgNVBAMTBkFtYXpvbjAeFw0yMTA0MjUwMDAwMDBaFw0yMjA1MjQy
MzU5NTlaMBYxFDASBgNVBAMMCyouZG9ja2VyLmlvMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAunGGnnZYPQ57XBGhvdfYw0QzfSytYVVmBvJ3OcIej+wm
Fs746xNWta4WDVy656AX5z8utkOAmTkWOsyFnzf+QBs+LUj/f8rd7jgTMq/IHo+L
vf/J3cf2/zKvtVp/3ee07eWjIFhkKMzwlveYObnoPJ00aQkOggW0lzVhy6KBAmg3
PKpDJLCxDPFExmaiqy3nRulC144pL3F1RCXWYCgmAhb1Vu7c4i//EsIXyUHIye6z
THixYRW42b+rietEo0w9eq86DBAZmCKMI5ulAnKpuLjhcrREckVa99PDMFXRu03l
+HHJcMkGnJ9gcycLCWXvkookQHOSpxEplSb9akPfiQIDAQABo4IC7TCCAukwHwYD
VR0jBBgwFoAUWaRmBlKge5WSPKOUByeWdFv5PdAwHQYDVR0OBBYEFDg5juZjGG0u
uFiH5VTWXqMDttZAMCEGA1UdEQQaMBiCCyouZG9ja2VyLmlvgglkb2NrZXIuaW8w
DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjA7
BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY3JsLnNjYTFiLmFtYXpvbnRydXN0LmNv
bS9zY2ExYi5jcmwwEwYDVR0gBAwwCjAIBgZngQwBAgEwdQYIKwYBBQUHAQEEaTBn
MC0GCCsGAQUFBzABhiFodHRwOi8vb2NzcC5zY2ExYi5hbWF6b250cnVzdC5jb20w
NgYIKwYBBQUHMAKGKmh0dHA6Ly9jcnQuc2NhMWIuYW1hem9udHJ1c3QuY29tL3Nj
YTFiLmNydDAMBgNVHRMBAf8EAjAAMIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYA
dgApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXkHoY7QAAAEAwBH
MEUCIEPYw0bn8knWSFrYt4w/tI4z3runrbj18yYEp4Gp35WJAiEAzsRt1NAkMPM7
iYXWU2Cdy7XHp1xTC2q5M42RBSHCQOAAdQAiRUUHWVUkVpY/oS/x922G4CMmY63A
S39dxoNcbuIPAgAAAXkHoY5VAAAEAwBGMEQCIB5+3Cl9JZNaIMOMzgabSYx0Qmk9
hLh0ivOiru9M/tm5AiB3HpopjDejWjP3Pn+Bsmy9oGNz6Jw5ih0nSSbsbLyzxgB1
AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABeQehjsoAAAQDAEYw
RAIgWHCBLfdqyoSzXgqt/lGwyUbY1yNv8q+H2ACfrBRSeYICIGKIU8e73TuxnW38
xYXP5LKys1igu+LggAGQjcMOryvjMA0GCSqGSIb3DQEBCwUAA4IBAQAOG7MzyF+B
VbXhw5rELPXKhxmNYC/6nM78pH2qIx3CANcMDItlVaH+PoTaNiSBrWiCRxein28b
nDgK+FtK+mSKOSO1mBStebUfsU6iql5Z+qqZ6s0gnI8IIuWap0Yz0DZygUNEGnd2
wu0JlcjLBrvCK6fNi+rS8m7B/tTRWvrhgzqIZjBQz6jmUVGpHC/WOTu0EtDgkij1
E4Dr6ubCPrFn05t57USnNGy3FslBas7Z1hXpRAW8YOfqzdoOh0QJA6uuYXyaf0RP
Ytv0Oi8hXPuxuivj1L3MaEoSQYG7LXuJtnC+2K0/Wni+oEavYfKgXEsBcZSsCfUs
xNWWYawvkSFS
-----END CERTIFICATE-----
subject=/CN=*.docker.io
issuer=/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5433 bytes and written 322 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: AA591173CC3E58BBC67A888FAB978788735D46BD17084F7DA00650231B31644F
    Session-ID-ctx: 
    Master-Key: E314217E8C7EC0DF952D33907AD5789204EA995D9923544F5F47698924F78D55077C3C375994D9A058EF3DBD6CD409C8
    Start Time: 1623399936
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
^C
```
-- I'm curious to see if you have a different certificate chain to me.

**Comment by miukki** [comment]
same issue here 
```
% docker -v
Docker version 20.10.7, build f0df350
```

```
uname -a     
Darwin L4932 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

Chip Apple M1

**Comment by vosergey** [comment]
Same issue

` docker run --name repo alpine
/git clone https://github.com/docker/getting-started.git
Unable to find image 'alpine/git:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/alpine/git/manifests/sha256:2f510e96ae0785c5cdad2ce2a54e331b8dca0d636b463dff3545c013ff1d1416": net/http: TLS handshake timeout.
See 'docker run --help'.`

**Comment by nicroto** [comment]
Started happening today to me as well.
Mac OS Big Sur 11.6 (this is latest ATM)
Docker for Apple Silicon 4.1.0

My download is at the ballpark of 200Mbps and upload at 150Mbps.

**Comment by jdietsch31** [comment]
same issue Mac OS Monterey 12.1
Docker Desktop 4.3.2 (72729)
Won't build any remote dev containers in vscode any ideas anyone? Thanks

**Comment by rvanlaak** [comment]
While debugging the same error I found this Docker for Mac note on not being able to retrieve metadata for M1 arm infrastructures.

Switching from `mysql` to `mariadb` for my local dev environment solved the problem.

> "Not all images are available for ARM64 architecture. You can add --platform linux/amd64 to run an Intel image under emulation. In particular, the [mysql](https://hub.docker.com/_/mysql?tab=tags&page=1&ordering=last_updated) image is not available for ARM64. You can work around this issue by using a [mariadb](https://hub.docker.com/_/mariadb?tab=tags&page=1&ordering=last_updated) image."

https://docs.docker.com/desktop/mac/apple-silicon/#known-issues
