### ISSUE TITLE
Docker 17.12.0-ce-rc3-mac43 2017-12-15 version of Docker for Mac 10.11.6 El Capitan ( Early2008)

### ISSUE THREAD

**Issue by Tananiko** [docker/for-mac#5738]
Hey, 

I am not able to install Docker , getting the Diagnostic Id : 7FC5862E-E3F2-46BC-9DA7-C0A5E0BB1EDC
And as new to Docker,  I am sitting here helpless to get around this issue-

I do thank you for your support and advise

 

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 10.11.6
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 17.12.0-ce-rc3-mac43

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Sorry, that version of Docker Desktop is really old, and way out of support. Even if we found a bug, we wouldn't fix it.

**Comment by stephen-turner** [comment]
I think that wasn't even a Stable version at the time, it was on our experimental Edge channel.

**Comment by Tananiko** [comment]
Hi Steven , can you please,advise which version could be installed for 10.11.6, which could run on my "old machine"?
Your support would be an important help to me 

Thank you so much

**Comment by stephen-turner** [comment]
All our old versions are listed at https://docs.docker.com/docker-for-mac/release-notes/ but you'll have to experiment to see which will run on your machine. We only support the latest Docker Desktop on the latest three MacOS releases.
