### ISSUE TITLE
Docker gets stuck pulling images on M1

### ISSUE THREAD

**Issue by zi5t0** [docker/for-mac#5740]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 6D3CEE87-1E48-4E8F-82FC-3FD7C216403F/20210608213522

### Expected behavior
Pulls images normally
### Actual behavior
Gets stuck pulling images
### Information
If I cut the process with Ctrl+C and retry, the second or third time I try to pull the image again, it downloads normally
  - macOS Version: macOS Big Sur 11.3
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.3.3(64133)

**Comment by stephen-turner** [comment]
If it succeeds eventually, it could be something in your network blocking it. Are you in a corporate network?

Also, do you have the virtualization framework selected in experimental settings? If so, try turning it off.

**Comment by zi5t0** [comment]
> If it succeeds eventually, it could be something in your network blocking it. Are you in a corporate network?
> 
> Also, do you have the virtualization framework selected in experimental settings? If so, try turning it off.

My network is my home network, I tried also with my mobile network with AP and in my comporate network. Always the same. I haven't enabled the experimental settings

**Comment by stephen-turner** [comment]
Hmmm, I'm not sure what else to suggest. We haven't had a lot of other reports of this.
