### ISSUE TITLE
Docker Desktop Invalid link to missing "policy regarding uploaded diagnostic data"

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5741]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics You don't need them
  - Diagnostics ID:

### Expected behavior

The link to policy regarding diagnostic data should go to a policy regarding diagnostic data

### Actual behavior

See 
<img width="707" alt="Support" src="https://user-images.githubusercontent.com/112444/121437189-1f4a0780-c93f-11eb-87af-610f0fa77554.png">

The link ends up redirecting to https://docs.docker.com/desktop/faqs/, which does not have such a policy. 

### Information
  - macOS Version: All
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.4.0

### Steps to reproduce the behavior
Visit the troubleshooting page and click the policy link.

**Comment by StefanScherer** [comment]
Thanks @rfay!
As we cannot change the link in existing versions of Docker Desktop, we will add more information about the policy in the Frequently asked questions page https://docs.docker.com/desktop/faqs/

**Comment by StefanScherer** [comment]
Actually Docker Desktop uses https://docs.docker.com/docker-for-mac/faqs/#how-is-personal-data-handled-in-docker-desktop (or https://docs.docker.com/docker-for-win/faqs/#how-is-personal-data-handled-in-docker-desktop if running on Windows) and we've merged the two FAQ's to one.

The correct link should be https://docs.docker.com/desktop/faqs/#how-is-personal-data-handled-in-docker-desktop

**Comment by rfay** [comment]
I guess this is good enough now, thanks!

**Comment by StefanScherer** [comment]
We have just released Docker Desktop 3.5.0 which contains a fix for this issue.

**Comment by rfay** [comment]
Actually, the link in 3.5.0 still just redirects to the faq.

**Comment by StefanScherer** [comment]
Thanks @rfay for checking again. The PR with the fix looked so obvious that we didn't tried it manually, but I missed one relevant link. 😞 OK, it will make it in the next patch release.

**Comment by lorenrh** [comment]
Hello there! We have just release 3.5.1 containing a fix for this issue.

**Comment by xliudaxia** [comment]
It's a good image to intruduce this bug.
