### ISSUE TITLE
Docker is Hanging 

### ISSUE THREAD

**Issue by jcheung0** [docker/for-mac#575]
### Expected behavior
All docker functionality should work such as docker compose  up should pull and build all the proper containers
### Actual behavior
docker locks up and attempting to pull image and after I stop it i'm unable to delete images and execute any processes
### Information
I tried to run the docker-compose file from the following project https://github.com/bigchaindb/bigchaindb

but it stops randomly such as either trying to pull the additional layers for rethinkdb or extracting and from their on out i'm unable to delete images with the docker rmi and and delete processes 

Diagnostic ID: 92FEAF1B-10B2-4762-9CF0-55956468062C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. git clone the following repo https://github.com/bigchaindb/bigchaindb
2. run docker-compose up 
3. it will start hanging after trying to pull down the rethinkdb container
4. CTRL-C  and try to do a docker rmi for any images y ou have on your machine

**Comment by mchiang0610** [comment]
@jcheung0 Just tried this using beta 25. It's working for me. 

Can you try resetting to factory defaults? or try the beta if you are willing to use beta: https://download.docker.com/mac/beta/Docker.dmg 

We will update the stable channel soon. 

Thanks!
