### ISSUE TITLE
New Virtualization Framework docker unresponsive and high CPU load

### ISSUE THREAD

**Issue by karaarda** [docker/for-mac#5750]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8bd3caee-44e8-4750-85d2-fedd77db6cd1/20210613120339

### Expected behavior

Everything runs smoothly as before docker for mac 3.4

### Actual behavior

Power consumption rises to over 80 Watts suddenly and stays there for couple minutes, during that time it is not possible to run any docker commands either like `docker ps` or `docker stats`

### Information

  - macOS Version: 11.4 (20F71)
  - Intel chip or Apple chip: 2,6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.4.0 (65384)

  1. Enable new virtualization framework
  2. It happens by itself

**Comment by stephen-turner** [comment]
Thanks for the report. I suggest using the old virtualization framework, we're aware that the new one isn't performant.
