### ISSUE TITLE
Fatal Error when Docker Desktop Auto Start

### ISSUE THREAD

**Issue by newTypeGeek** [docker/for-mac#5760]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4A5657A3-4EF6-44F2-AAAD-6E69817C6D1D/20210616011436

### Expected behavior
After login to an account on Macbook, Docker desktop should auto start

### Actual behavior
A fatal error message appears
<img width="597" alt="docker-desktop-fatal-error" src="https://user-images.githubusercontent.com/38719080/122143614-5dd24b80-ce84-11eb-9a82-14a906eabf24.png">

### Information
The problem is reproducible. Every time I restart the Macbook, the Docker Desktop fail to auto start, and a fatal error message is prompt.

This issue seem to associated with a recent update of Docker Desktop.

However, if I manually kick start the Docker desktop, it can launch successfully without fatal error message

  - macOS Version: 10.15.7 (Catalina)
  - Intel chip or Apple chip: 3.1 GHz Dual-Core Intel Core i5
  - Docker Desktop Version: 3.4.0 (3.4.0.5223)

### Steps to reproduce the behavior
  1. Enable Docker Desktop auto start when login
  2. Restart Macbook and login again
  3. Docker Desktop fail to start with fatal error message

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
