### ISSUE TITLE
Cannot connect to backend API

### ISSUE THREAD

**Issue by JohnMorris4** [docker/for-mac#5767]
I have seen where others have had the same problem a couple of years ago, but I had just updated to current release of Docker on my MAC and when I had to restart the computer is when I first noticed it. I have tried everything that others have stated to do even restore to factory defaults.  If I click on the restore to factory defaults, which I did 3 days ago and left it, It does nothing. If I click on Diagnose and Feedback and I choose to upload it does nothing. I cannot exit out of it which means I cannot remove the application. Any help would be great.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sasmithjr** [comment]
I have also started to experience this issue recently.

macOS 11.4
15" 2017 MBP with Intel
Docker Desktop v3.4.0 (65384)

After a cold boot, I get the same error. Attempting to exit or diagnose the problem causes DockerDesktop to hard freeze. I am able to force quit through the Activity Monitor application; after that, I am able to start Docker Desktop and use it like normal (until after next shutdown).

**Comment by JohnMorris4** [comment]
I was able to get mine to the point where I got it to exit. I was able to remove the old install, then able to reinstall.
