### ISSUE TITLE
Docker chasing on macOS 10.12 (General Seed)

### ISSUE THREAD

**Issue by vernonstinebaker** [docker/for-mac#577]
### Information

Diagnostic ID: 8EE46382-7643-4D36-B611-0D0C4D9DD1F4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by damnhandy** [comment]
Same here. Docker will run for a few minutes and then you're prompted with a dialog box stating that the Docker daemon received invalid JSON. Once I start getting that message, the Diagnose and Feedback menu item returns this:
```
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A320)
logs: /tmp/AA48C77D-300D-439C-87EC-1AC8D1FF6492/20160910-111019.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

```
Curiously, the "Open Issues" button does not copy the same contents into the GitHub issue.

I reinstalled Docker and then tried to run `docker pull busybox` and got the following:

    $ docker pull busybox
    Using default tag: latest
    Pulling repository docker.io/library/busybox
    unexpected EOF

And then a subsequent retry revealed a bit more info:

    $ docker pull busybox
    Using default tag: latest
    An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=busybox&tag=latest: EOF

Since I reinstalled, it hasn't crashed yet but Docker also doesn't function correctly.

**Comment by dsexton** [comment]
@vernonstinebaker @damnhandy this is a known issue, you can check out my comment [here](https://github.com/docker/for-mac/issues/455#issuecomment-243485230) and you can also read this [hijacked forum topic](https://forums.docker.com/t/fatal-error-while-using-docker-v-1-11-2-beta15/15267/18).

I would recommend installing go 1.7 via homebrew and then install the docker CLI utils (docker, docker-compose, etc.) via homebrew as well. This has been working for me thus far on macOS 10.12. As of writing this the Docker for Mac Beta's embedded docker CLI binaries are still compiled against go 1.6, which has issues on 10.12.

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs. 

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg  if you are willing to try beta builds.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
