### ISSUE TITLE
Centos 7 docker epel nginx problems

### ISSUE THREAD

**Issue by RiccardoFrancescato** [docker/for-mac#5772]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 558AB846-F603-4328-82F0-8E48EB43D92B/20210621102320

I'm trying to use x86 centos:7 docker image to have an nginx web server and other stuff. The problem is presenting on an M1 Mac book air. The steep below works fine on an old 2015 Mac book air.

### Expected behavior
The expected behavior is a successful installation of ngix
### Actual behavior
```
[root@ab8338e8810e /]# yum install nginx
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
```
### Information

  - macOS Version: 11.2 (20D64)
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version:3.4.0(65384)

### Steps to reproduce the behavior

  1. `docker run -i -t --platform linux/amd64 centos:7`
  2. on docker cents 7 shell `yum install epel-release`
  3. on docker cents 7 shell `yum install nginx`

**Comment by stephen-turner** [comment]
It looks like it can't find the right repositories, which are probably architecture dependent. This will have to be debugged inside the container. I don't think it's a Docker problem as such.
