### ISSUE TITLE
Unable to run Docker in Docker in Macbook Pro M1

### ISSUE THREAD

**Issue by bmaltais** [docker/for-mac#5776]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: NA

### Expected behavior
Using Visual Studio Code Docker in Docker Devcontainer should provide access to docker

### Actual behavior
Trying to run `docked ps` in the resulting container return:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Trying to manually start dockerd end with:

```txt
INFO[2021-06-21T15:21:10.375490000Z] Loading containers: start.                   
WARN[2021-06-21T15:21:10.397322000Z] Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.2 (legacy): can't initialize iptables table `nat': iptables who? (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3 
INFO[2021-06-21T15:21:10.692490000Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2021-06-21T15:21:10.692714000Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
INFO[2021-06-21T15:21:10.692925000Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.2 (legacy): can't initialize iptables table `nat': iptables who? (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 20.10.7

### Steps to reproduce the behavior

  1. Install VSC
  2. Add remote development extension
  3. Open in remote container Docker in Docker
  4. Test with docker ps

**Comment by eric1905** [comment]
@bmaltais do you know if there is any workaround to get it running? I have the same problem and I need to fix this soon.

**Comment by serveapps** [comment]
I'm a cloud consultant, so I could use some help as well. I've tried using AppCleaner to wipe. i've tried reinstalling rosetta. I've tried wiping the docker socket and verifying it comes back.

I keep getting this for dockerd
2021-09-07T12:08:33Z dockerd time="2021-09-07T12:08:33.844794917Z" level=info msg="API listen on /run/guest-services/docker.sock"

**Comment by serveapps** [comment]
Update: creating a second MacOS user works around this user, so Docker.app is not properly resetting to "factory defaults" for userland
