### ISSUE TITLE
Docker's "Getting started" command isn't actually a valid command

### ISSUE THREAD

**Issue by numbermaniac** [docker/for-mac#5777]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 160CF2B6-C491-4E05-B33E-B860B28103E0/20210624042707

### Expected behavior
I'm new to Docker, so I installed and ran Docker for the first time. Docker suggests I run the following command to get started:

```sh
docker run -d -p 80:80 docker/getting-started
```

I expected this would give me some kind of getting started guide.
### Actual behavior
```sh
open: invalid option -- d
```
Followed by the help message for macOS's `open` command.
### Information

  - macOS Version: 10.14.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.4.0

![Screen Shot 2021-06-22 at 6 16 22 pm](https://user-images.githubusercontent.com/5206120/122891299-c1c6a980-d387-11eb-81d7-81dadc955e1f.png)
![Screen Shot 2021-06-22 at 6 28 41 pm](https://user-images.githubusercontent.com/5206120/122891305-c3906d00-d387-11eb-8e39-c333f5e4c61e.png)

### Steps to reproduce the behavior

  1. Install Docker Desktop fresh
  2. Try to run the command that Docker recommends on your first launch

**Comment by StefanScherer** [comment]
Hi @numbermaniac 
Thanks for trying Docker and welcome!
The command `docker run -d -p 80:80 docker/getting-started` normally works fine.
From the screenshot you added I only can see that the usage message is from the `open` command and not from the `docker` CLI. 🤔 
It seems there is something wrong with your terminal environment, maybe an alias or a shell script that is called `docker`? 

Try these commands

```
which docker
```

or run the Docker CLI directly

```
/usr/local/bin/docker run -d -p 80:80 docker/getting-started
```

**Comment by numbermaniac** [comment]
Ahh ... looks like it was some old environment variable alias I didn't realise was there that was getting in the way. Thanks for the help!
