### ISSUE TITLE
Docker does not start at all.

### ISSUE THREAD

**Issue by 42f** [docker/for-mac#5782]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker app opens.

### Actual behavior

Nothing happen except the first time I try to open: the security pop-up asking for permission to open since the piece of software was downloaded from the internet.

### Information

It the first time I use docker on this new mac mini m1 so not sure if it ever worked before.

I have tried to install docker desktop app from this page, selecting the right CPU type (apple chip) : https://docs.docker.com/docker-for-mac/install/
And I also tried with this command: `brew install --cask docker` 

In both cases, I end up with a Docker app in my Applications, I can click on it and I get the security pop-up asking for permission to open since the piece of software was downloaded from the internet. I click `Open` then nothing happens.

If I run `ps aux | grep docker` I don't see any docker process open.

I have tried to reboot, reinstall both ways.

I can't find any log of any sort since the app just does not start.

  - macOS Version:
  - Intel chip or Apple chip: Apple m1
  - Docker Desktop Version: Big Sur 11.4

UPDATE:
I managed to have it to start by creating a new normal mac user (not admin), logging into it, installing it and starting it normally.
It asked me for the admin password to enable privileges, and then started normally.
Back on my usual mac user account (which is admin) I still cannot start it.

**Comment by StefanScherer** [comment]
Hi @42f 
Did you install Rosetta 2? It is required at the moment as parts of Docker Desktop still only work in emulation.
Please have a look at https://docs.docker.com/docker-for-mac/apple-silicon/#system-requirements to see how to install Rosetta 2 from the command line.

**Comment by 42f** [comment]
> Hi @42f
> Did you install Rosetta 2? It is required at the moment as parts of Docker Desktop still only work in emulation.
> Please have a look at https://docs.docker.com/docker-for-mac/apple-silicon/#system-requirements to see how to install Rosetta 2 from the command line.

I did, although there is a message during installation it seems to end up well : 

```
$> softwareupdate --install-rosetta
I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
Type A and press return to agree: A
2021-06-24 10:17:05.484 softwareupdate[24402:790176] Package Authoring Error: 071-00708: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
Install of Rosetta 2 finished successfully
```

And I do have some intel apps running so Rosetta seems to be ok (dropbox, discord, etc. ...)

**Comment by 42f** [comment]
### UPDATE:

I managed to have it to start by creating a new normal mac user (not admin), logging into it, installing it and starting it normally.
It asked me for the admin password to enable privileges, and then started normally. 
Back on my usual mac user account (which is admin) I still cannot start it.

**Comment by landonclark** [comment]
I am having the same problem, but the difference is that I have an Intel Mac and the workaround (creating a new user and launching from there) didn't work for me.

I have completely uninstalled dockers including Cache, Containers, etc. by hand a few times and no luck.

**Comment by ducretje-evooq** [comment]
Same here, Mac Intel:
Uninstalled docker and reininstalled but still stuck on `Docker Engine starting`

**Comment by landonclark** [comment]
Update:
I uninstalled, downloaded the previous version.  It seemed like it was having the same problem, but I just let it run and after about 15minutes it prompted to give desktop privileges and installed OK.  Definitely seems like a bug somewhere, happy to provide more information if needed.

**Comment by ducretje-evooq** [comment]
Same here, rollback to 3.4.0 and no issue at all it started in <1 min.

**Comment by harrouet** [comment]
Same here, old machine but letting it run for hours does not help.
Settings are not accessible either, so I cannot reset to defaults, or whatever. Amazing that the front-end needs to wait for docker engine to start in order to just provide the basic features.
