### ISSUE TITLE
Fan and CPU spun up

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#5786]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F14EC0BF-E65E-45F4-B960-78F5BD1C8BD8/20210624155218

### Expected behavior

CPU usage is low when nothing is happening

### Actual behavior

CPU and fan spun up

### Information
  - macOS Version: 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.4.0

### Steps to reproduce the behavior
Not sure. Just happened

**Comment by denyskyselov** [comment]
Same here with last docker desktop builds starting from 3.4.0 version. switching to new virtualization framework does not help. Main problem i can't prevent updating from 3.3.x version to latest. CPU temp without load 68-72C

Version 3.3.x keep fans quiet and do not produce high temp. This version keep cpu temp approx 63-65C

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.
