### ISSUE TITLE
Got diff. Image with pull from same name 

### ISSUE THREAD

**Issue by Winedays** [docker/for-mac#5789]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`docker pull python:3.8.3-alpine3.12`, get the docker image with id `8ecf5a48c789`

### Actual behavior
I and my friend tried pull a python image, my Macbook is Apple chip, and my friend Macbook is Intel chip.
This is the pull message of my friend 
- macOS Version: macOS Big Sur ver11.2.3
- Intel chip or Apple chip: Intel chip
```
$ docker --version
Docker version 20.10.6, build 370c289

$ docker pull python:3.8.3-alpine3.12
3.8.3-alpine3.12: Pulling from library/python
df20fa9351a1: Pull complete 
36b3adc4ff6f: Pull complete 
7031d6d6c7f1: Pull complete 
81b7f5a7444b: Pull complete 
0f8a54c5d7c7: Pull complete 
Digest: sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd
Status: Downloaded newer image for python:3.8.3-alpine3.12
docker.io/library/python:3.8.3-alpine3.12

$ docker images
REPOSITORY         TAG                 IMAGE ID            CREATED             SIZE
python             3.8.3-alpine3.12    8ecf5a48c789        12 months ago       78.9MB
```

And this is the pull message of me
  - macOS Version: macOS Big Sur ver11.2.3
  - Intel chip or Apple chip: Apple chip
```
$ docker --version
Docker version 20.10.6, build 370c289

$ docker pull python:3.8.3-alpine3.12
3.8.3-alpine3.12: Pulling from library/python
b538f80385f9: Pull complete 
0d489d24c263: Pull complete 
8a929077d9fd: Pull complete 
d7ec06633573: Pull complete 
ac492519001e: Pull complete 
Digest: sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd
Status: Downloaded newer image for python:3.8.3-alpine3.12
docker.io/library/python:3.8.3-alpine3.12

$ docker images python
REPOSITORY   TAG                IMAGE ID       CREATED         SIZE
python       3.8.3-alpine3.12   30a0ab0fa7cc   12 months ago   88.4MB
```

actually we got two different image with the same pull command, after that we also use a Ubuntu to pull `python:3.8.3-alpine3.12`, and get an image with id `8ecf5a48c789`, I think I got a wrong image, but why ?

### Information

  - macOS Version: macOS Big Sur ver11.2.3
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 3.3.3
### Steps to reproduce the behavior

  1. `docker pull python:3.8.3-alpine3.12`
  2. check the image id

**Comment by Winedays** [comment]
I solved this problem following https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues
using `docker pull --platform linux/amd64 python:3.8.3-alpine3.12`

**Comment by StefanScherer** [comment]
Hi @Winedays 
This is expected. The python image and many of the other official images are multi-arch images that provide image layers specific for the CPU architecture of the Docker daemon. 
To avoid running in emulation that would make it slower and sometimes causing issues the Docker daemon picks the image ghat fits the current CPU. 
For Apple silicon it uses the linux/arm64 image, for Intel it uses the linux/amd64 image. 

You can read a little bit more in https://www.docker.com/blog/released-docker-desktop-for-mac-apple-silicon/ how to create such multi-arch images with buildx for your own images to provide the best experience for your users.
