### ISSUE TITLE
Error response from daemon: dial unix: connect: connection refused

### ISSUE THREAD

**Issue by jnovack** [docker/for-mac#579]
Could be minutes, could be hours, but I always get "Error response from daemon: dial unix /Users/jnovack/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused"

This issue is identical to #568.

### Steps to reproduce

1.  Start up some containers
2.  Wait...
3. [There's no step 3](https://youtu.be/6uXJlX50Lj8?t=14s)

### Expected behavior

Not crash all containers and restart the daemon.

### Actual behavior

All containers crash, docker restarts, and `--restart=always` containers are restarted.

### Information

```
Diagnostic ID: 1F233FF4-6975-4338-B0FE-188DE58EC1B6
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Merging with #568
