### ISSUE TITLE
Mounting a volume to container will not refresh host files in container

### ISSUE THREAD

**Issue by akotulu** [docker/for-mac#5795]
Container with mounted host directory will not refresh files in the container after editing in the host machine. Only way to get the latest changes is to open the file in the container, change and save it, replace the changes in the host machine.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 48A65C3E-453E-4EE7-A7A1-97F92720B07D/20210629000206

### Expected behavior
Files in the mounted volume are in sync with host volume.
### Actual behavior
File changes in host machine aren't visible in the containers mounted volume.
### Information

I'm using Docker Debian container for building a `c++` project. Changing files in host machine worked before, but with latest versions it broke. Files aren't synced anymore, I have to reboot the container to have all the files with latest changes.

  - macOS Version: 11.4
  - Intel chip or Apple chip: 2,5 GHz Quad-Core Intel Core i7
  - Docker Desktop Version: 3.5.1 (3.5.1.7)

### Steps to reproduce the behavior
  1. Create a docker container with `docker create -v` option;
  2. Start the container;
  3. Change the host text file in the mounted volume;
  4. Open the text file in the container, file is in initial state when container was launched;

**Comment by supsup** [comment]
Seeing same issue following guide from:
https://github.com/slatedocs/slate/wiki/Using-Slate-in-Docker


-- artok in IRC suggested unchecking in Settings (sprocket) -> General -> 'Use gRPC FUSE for file sharing '
After doing that it worked.
I then checked it back -- did not work again
Unchecked it -- worked again. 

Why does this setting cause Mounts to not work?

**Comment by michaelbrooks** [comment]
I'm seeing files in bind mounted directories failing to update when written to from the host side, but if I touch the file then it updates inside the container. I was also able to get this working by disabling the gRPC FUSE option.

**Comment by christianseel** [comment]
I got the same issue with latest Docker Desktop 3.5.2 (66501) on a Mac (11.4) with M1 Chip. Working with a PHP Docker container. Files get synced from the host machine for a very few seconds only. Then it stops. Only restarting Docker Desktop causes a refresh of the files. After a very short time (~3 seconds) it stops again.

Disabling 'Use gRPC FUSE for file sharing' makes file sync working again.

**Comment by wkirby** [comment]
Seeing the same issue as all of the above. Massively disappointed that gRPC FUSE is the default when it's so clearly faulty; really frustrated at the forced update  pattern that took me from a working dev environment to a broken one.

**Comment by wkirby** [comment]
I should  note that ultimately, downgrading to 3.3 fixes the issue without having to disable gRPC FUSE; but that is a poor solution, as it requires a manual reversion to 3.3 every time the computer restarts.

**Comment by christianseel** [comment]
I'm still having the same issue with Docker Desktop 4.5.0 (74594) on my mac (m1).

**Comment by skyboyer** [comment]
the same to docker-desktop 4.5.0 at Intel chip Macbook(in both Catalina and Monterey)
