### ISSUE TITLE
Error on reboot

### ISSUE THREAD

**Issue by Stwissel** [docker/for-mac#5799]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E86F767A-167C-416F-99EC-0BF120925D8D/20210629095218

### Expected behavior
On reboot of macOS Docker desktop starts into the "tray"

### Actual behavior
Error opens the Diagnose & Feedback UI
[docker-compose.yml.zip](https://github.com/docker/for-mac/files/6732468/docker-compose.yml.zip)

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? - not on other machines
  - Is the problem new? - yes
  - Did the problem appear with an update? - don't think so
  - A reproducible case if this is a bug, Dockerfiles FTW. docker-compose attached
  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version:  3.4.0.5223

### Steps to reproduce the behavior

  1. Deploy docker-compose file
  2. Shut down macOS
  3. Have a coffee
  4. STart macOS
  5. Error happens
  6. Manual start Docker app -> seems to work now

**Comment by mikhashev** [comment]
Have same problem. After update and restart got an Fatal Error:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/7105540/123900185-ccd69680-d992-11eb-950c-e3c770b52dc4.png">

**Comment by mikhashev** [comment]
After 20 minutes of runningDiagnose and Feedback 
this window appears :
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7105540/123901760-c564bc80-d995-11eb-8ae5-31e752769c22.png">

I am add acces and all is fixed and Docker is updated and running now

Docker version 20.10.7, build f0df350
