### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by mikev1963** [docker/for-mac#580]
### Steps to reproduce

1.
2.
3.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Information

```
Diagnostic ID: B9EE1304-A905-4875-9B74-F9CB9AEC6569
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Thanks for reporting this. We are still testing macOS Sierra bugs.

**Comment by smoothdvd** [comment]
I just upgrade beta25, i works fine but after build some images, it stuck the starting status.

**Comment by mchiang0610** [comment]
@smoothdvd Thanks for the report, as it's different than the one reported, would it be possible for you to create another issue? I'd really appreciate it. 

Thanks!

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by smoothdvd** [comment]
@djs55 @mchiang0610 Now beta 26 is working on macOS GM 10.12 (16A323)
