### ISSUE TITLE
there are multiple icons in the dock when there should only be one

### ISSUE THREAD

**Issue by confessore** [docker/for-mac#5801]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
docker should only have one icon in the dock while "minimize windows into application icon" is enabled
### Actual behavior
docker has multiple icons in the dock
### Information

  - macOS Version:
  - **11.3.1 big sur**
  - Intel chip or Apple chip:
  - **apple chip m1**
  - Docker Desktop Version:
**version 20.10.7, build f0df350**

### Steps to reproduce the behavior

  1. ... open the dashboard
  2. ... minimize or close the dashboard
  3. ... open the dashboard
  4. ... minimize or close the dashboard
  5. ... open the dashboard
![Screen Shot 2021-06-29 at 11 41 45 AM](https://user-images.githubusercontent.com/1919812/123828282-5886ef00-d8cf-11eb-844c-c47c37c20324.png)

**Comment by aluneed** [comment]
So do I have the same problem.
I find that the icons activated by 'Docker Desktop.app' and from the top-right menu is not the same.

A new icon activated when I tried to open 'Settings' button in the window of 'Docker Desktop.app', as well as click the icon in the dock. Trying to open dashboard or preferences from the menu behaves the same, a new icon come out in the dock.

In contrast, opening the dashboard from top-right menu at the beginning, there will be no such problem. Only one icon remaining in the dock in this case.

By the way, I found it unable to open the preferences board by using the hot key 'command + ,' .
