### ISSUE TITLE
After being prompted to update, you choose "download update", and it brings up a "download update" dialog

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5803]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When prompted that there is an update to download in the whale menu, I should be able to click "download update" and the update would be downloaded. The extra dialog box is not necessary.

### Actual behavior

Instead, a whole extra dialog box pops up asking me if I want to download the update.

<img width="699" alt="Screen Shot 2021-06-29 at 10 40 13 PM" src="https://user-images.githubusercontent.com/112444/123903232-8863e000-d92b-11eb-9978-5133c8f27ff5.png">

### Information
  - macOS Version: Big Sur
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.5.1

### Steps to reproduce the behavior

Wait for it to prompt for downloading an update. Then choose to download it.

**Comment by mologie** [comment]
Additionally there is a separate "update and restart" button that is also not necessary. These are the separate UI interactions needed to have an update installed: 1) Click update, 2) Find window, click update again, 3) wait 10s, 4) click update/install.

I'd prefer to just click "update" once, have the Docker menubar item show its "busy", and then download+install+restart.
