### ISSUE TITLE
OSXFS performance issue - another data point

### ISSUE THREAD

**Issue by transistorize** [docker/for-mac#581]
Known issue, but I thought I would register my case.
### Steps to reproduce
1. Run docker-compose with mysql:5.6 on alpine-latest
2. Load about 500 MB of sql data onto the image, on a computer with spinning disks.
3. Wait about 1+ hour to finish.
### Expected behavior

Normal loading time is about 5 minutes on a computer with SSDs, 10 on one with spinning disks. 
### Actual behavior

Loading time is about 5-6x longer on respective hardware platforms.
### Information

```
Diagnostic ID: 7EA3A661-79FE-41CD-A92B-F9E8E849B733
Docker for Mac: 1.12.1-beta24 (Build 11525)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by dsheets** [comment]
Thanks for the report. We are looking at database-specific use cases for performance improvements as those workloads are considerably simpler in many ways than generic FS access.

**Comment by dsheets** [comment]
Just for completeness, could you please detail the exact steps you used to load your SQL data? Did you run an import for the MySQL shell from a file on a `-v` shared OS X directory?

**Comment by transistorize** [comment]
`docker run -it --rm --net internal.io -v $$PWD:/workdir -v $$HOME/.mydocker/mysql:/root --workdir /workdir mysql:5.6 bash -c 'mysql -proot -h mysql.internal.io ourdb < ourdb_copy.sql'`

Some names changed to protect internal names, but this is the command we're using.

**Comment by Vanuan** [comment]
Why would you mount host filesystem as a database directory? I thought mounts were meant to be used for editing files in IDE. Using a volume somewhere in VM is perfectly fine.

Are you saying that docker volumes also use osxfs?

**Comment by herophuong** [comment]
@Vanuan I think that's because it is easier to manage (like back-up operation, copy paste as-is to other co-worker machine, etc.) when mount a host directory as database directory.

**Comment by Vanuan** [comment]
Huh? Back up and migration for development databases? Who does that?
