### ISSUE TITLE
High CPU and RAM usage of idle qemu-system-aarch64 (Apple Silicon)

### ISSUE THREAD

**Issue by Niek** [docker/for-mac#5812]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 34762F73-A587-449C-9D39-39DCCE54882E/20210701111749

### Expected behavior
```bash
➜  ~ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
When no containers are running, I expect `qemu-system-aarch64` to use very little to no CPU usage. Especially if I don't use amd64 containers at all.

### Actual behavior
The CPU usage of `qemu-system-aarch64` is always between 7 and 20%, even with zero running or stopped containers. Even if I never use ad64 containers, the qemu process is still running. The only way to stop the process is to shut down Docker completely.

### Information
  - macOS Version: 11.4
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.5.1.7

### Steps to reproduce the behavior
  1. Start a completely fresh Docker desktop, no running containers
  2. Observe high CPU usage of the process immediately:
```bash
➜  ~ ps -A -o %cpu,command | grep qemu | head -1
 17.4 /Applications/Docker.app/Contents/MacOS/qemu-system-aarch64
```

**Comment by Niek** [comment]
A workaround, thanks to @mat007 on Slack:
> Try the `Use the new Virtualization framework` option in the Experimental section of the Settings

**Comment by xepozz** [comment]
@Niek thanks a lot

**Comment by DonTacho** [comment]
Hi there, 

So let me understand and an early apology I'm a bit of a neophyte on the subject; Is this reading normal?

I think that Docker is devouring the RAM although it does not feel slow xD 

![CleanShot 2021-09-14 at 21 59 53](https://user-images.githubusercontent.com/5567959/133363237-f5a08ed8-216d-468c-8434-76deebd9243b.png)

This even activating new Virtualization framework and without any container, volume or image.

**Comment by Phantsure** [comment]
I agree with @DonTacho . Similar issue with me. Even without any containers running and have enabled new virtualization framework. Cpu usage down to almost 0, ram usage at 2.56 GB

**Comment by Niek** [comment]
@DonTacho @Phantsure the column you should look at is `Real Mem`. [See here](https://apple.stackexchange.com/questions/107578/memory-terminology-in-mavericks-activity-monitory/112502#112502) for an explanation of the different memory types in Activity Monitor.

**Comment by VictorienTardif** [comment]
> A workaround, thanks to @mat007 on Slack:
> 
> > Try the `Use the new Virtualization framework` option in the Experimental section of the Settings

For me when using this option it's the "Virtual machine service" that uses all cpu. So it's one or the other.

**Comment by Nielsvd94** [comment]
Only way for me to completely stop docker is to quit the parent process following the steps below:
_DISCLAIMER: I'm not sure if doing this has any unexpected side-effects_

- Open Activity Monitor
- Select the qemu-system-aarch64 process and hit CMD + I (or click the i button in the top)
- In the process info window, click the parent process ( should be com.docker.driver.amd64-linux )
- In the parent process window, click the parent process ( should be com.docker.backend )
- In the process window of com.docker.backend, hit the Quit button
- Wait a couple of seconds ( a Fatal Error will show that com.docker.backend cannot start (Exit code 0). Just click exit to prevent docker from starting up again.

the Activity Monitor windows you have open for com.docker.backend and its child processes should now show as (terminated) in the window header.

The next time you try to start Docker Desktop using Spotlight search or from the Applications folder, it will not open the app directly but only start the qemu-system-aarch64 process. Try opening a second time and it should work.

**Comment by thomasaarholt** [comment]
Thanks for that, @Nielsvd94, I couldn't for the life of me manage to quit it.

**Comment by ababic** [comment]
Can confirm I am seeing this same issue. On a brand new 16GB MacBook Pro, starting Docker Desktop immediately starts a `qemu-system-aarch64` process that saps a whopping 5.2 GB of real memory....

<img width="868" alt="Screenshot 2021-12-29 at 9 52 48 pm" src="https://user-images.githubusercontent.com/7779588/147706502-6b54bdce-14f8-46cc-9aa4-ad82ff9ce64f.png">

Enabling the new virtualisation framework improves things slightly, but `Virtual Machine Service` uses almost as much:

<img width="860" alt="Screenshot 2021-12-29 at 10 03 07 pm" src="https://user-images.githubusercontent.com/7779588/147706928-80daed6b-3ff2-4bf7-91ee-5455fe18d562.png">

**Comment by dan-developer** [comment]
@ababic Same here...


![image](https://user-images.githubusercontent.com/10473169/147852812-266c4e2a-5a34-44a0-b336-bc6b6f67a274.png)


![image](https://user-images.githubusercontent.com/10473169/147852756-161ab1be-d1a8-4327-9417-48a97a9f97e4.png)

OS: macOS Montery v12.1
Docker Desktop: 4.3.2 (72729)

**Comment by geneowak** [comment]
If you have docker desktop installed you can control how many resources docker gets to use
![image](https://user-images.githubusercontent.com/13153526/148211625-78a22a54-9dc0-4e48-81ef-6a0d7c838554.png)

reducing the resources assigned to docker and enabling use of the new virtualization framework greatly reduced the memory docker was taking up

![image](https://user-images.githubusercontent.com/13153526/148211692-31fabe4f-e8cd-4176-93de-c54fd7912d28.png)

**Comment by sdubois** [comment]
![image](https://user-images.githubusercontent.com/479460/148249719-f82127c0-ddcc-45c9-a1c1-2348770737c0.png)
@geneowak thanks. are you using gRPC FUSE or the legacy file sharing?

**Comment by geneowak** [comment]
@sdubois am using gRPC FUSE

**Comment by nickpowersys** [comment]
@Niek Could the title of the issue be updated to "High CPU and RAM usage of idle qemu-system-aarch64 (Apple Silicon)", given the number of comments on memory? I'm seeing high RAM usage on 4.5.0 (74594) - went to Memory of 3.9 GB without the new virtualization framework and zero containers running, and 2.9 GB with the new virtualization framework. High RAM usage raise the likelihood of high memory pressure (going red).

**Comment by moodyomar** [comment]
Having the same issue, 
Enabling the new virtualization framework is just replacing the "qemu-system-aarch64" with Virtual Machine Service and it uses almost as much.

the only thing that did work was simply changing the Memory in the Resources tab. 
it was on 8GB for some reason and I changed it to 2GB.

**Comment by jrice-arcadia** [comment]
Having this issue as well. RAM usage was up to 9gb, virtual memory size >300GB. No containers running. Tried fix of constraining Docker resources to 1GB memory. The `qemu-system-aarch64` is now at 1.5gb usage; *seems* to be staying steady.

Docker Desktop 4.6.1
macos monterey 12.3 on M1 Max

**Comment by dan-developer** [comment]
I gave up on that and ended up buying a new mac mini with 16gb of ram. Problems are over. It is almost impossible to use with 8GB of RAM.

**Comment by TylerADavis** [comment]
The memory consumption seems to definitely be causing issues for me, as activity monitor shows yellow to red memory pressure when combined with other apps + browser tabs, something I haven't had happen in many months. I'm on Docker 4.6.1 with an M1 Pro Mac and 16 GB of RAM on MacOS 12.3.1, and I'm seeing qemu-system-aarch64 start using 8+ GB of RAM as soon as I launch Docker, even without launching any containers. I don't recall this being an issue previously.

**Comment by akonyer** [comment]
This just started being an issue for me on 4.6

Previous versions of Docker were using ~3GB of RAM, not it's up to 9 on launch with absolutely no containers running.

**Comment by dan-developer** [comment]
![image](https://user-images.githubusercontent.com/10473169/162268795-f3544aa4-f72c-4c2a-b954-c8ffc8c9fd40.png)

![image](https://user-images.githubusercontent.com/10473169/162268865-d3f8ba82-1774-481c-bd0c-d241e7dc6a3d.png)

**Comment by DanielRamosAcosta** [comment]
I'm about to migrate to podman 😢

**Comment by darylmonge** [comment]
Still not seeing this issue when using the new Virtual Machine Service feature
<img width="445" alt="image" src="https://user-images.githubusercontent.com/518043/162313471-42bf5a63-de80-487b-9328-e71ad8a648bc.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/518043/162313926-98d82985-593b-439f-9998-5da4a63a736f.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/518043/162315481-06ced6d9-b10d-4445-a91d-a0c2584c7c44.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/518043/162314109-157f36d5-1570-476c-9948-7a624e8ed8a7.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/518043/162315101-5139787e-4363-43d7-a8ad-9ded5162a96f.png">

**Comment by baqirkhan** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/10926994/162592857-422a247d-d05f-4876-ba82-cfec251131d7.png">
Just got new M1 Pro 16 GB Macbook and using only 1 postgres container, the RAM usage is 10GB!

**Comment by cheesegrits** [comment]
After last update, on a MacBook Pro M1, it went from using about 3GB to either 8GB with New Virtualization Framework, or 9GB with the original qemu, with no containers running.

Only other main difference between original and new frameworks is that with the original framework, qemu stays running even when I shut Docker Desktop down, no memory recovered.  With new framework, Virtual Machine Service has the decency to shut itself down when I close Docker Desktop, so I at least get the memory back.

This is not sustainable.

**Comment by djs55** [comment]
I think there are separate issues:

@moodyomar @cheesegrits @akonyer note that the default amount of VM memory was bumped to 8GB in 4.6 (see the [release notes](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-460)). It's fine to bump it down again, if that better matches your use-case.

@TylerADavis please customize the amount of memory you would like Docker to use from the whale menu -> Preferences -> Resources -> Memory. See @geneowak 's [comment above](https://github.com/docker/for-mac/issues/5812#issuecomment-1005613368)

@cheesegrits :
> Only other main difference between original and new frameworks is that with the original framework, qemu stays running even when I shut Docker Desktop down, no memory recovered. 

I think this is a separate process management bug. The next time this happens, could you [upload a diagnostics ID from the terminal](https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal) and post it here?

@darylmonge thanks for the observation:
> In my case, I discovered that there was Kubernetes services still running behind the scenes even though I had turned Kubernetes off

I think this is a process management bug also. The next time it happens, could you upload a diagnostics ID and post it here?

**Comment by dijonkitchen** [comment]
Althought my resources were limited to 8 GB memory, qemu was still taking over 11 GB. Quitting Docker did remove the qemu process though and I got the memory back. 

Potentially related to ARM processors based on emulating non-ARM images (I was using localstack): 
https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

**Comment by akonyer** [comment]
> note that the default amount of VM memory was bumped to 8GB in 4.6 (see the [release notes](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-460)). It's fine to bump it down again, if that better matches your use-case.

This is fine, but I would expect the 8GB of VM Memory to be a maximum, and that it would consume and allocate less memory than this unless needed?

I would not expect the VM to block 8GB or RAM just in-case. It's taking up 8GB of memory running docker alone with 0 containers running.

**Comment by GuanLinZhang** [comment]
I have the same issue, I enabled the Docker dev environment(beta) and the new virutulization framework, seems like the
Virtual Machine Service is always have 8GB of RAM, below is the detail from Activity Monitor


Virtual Machine Service	8.02 GB	9	60	995	guanlinz	1.3	10.22	0	Apple	0.0	0.00	0 bytes	0 bytes	0	0	0 bytes	0 bytes	No	0.0	-	No	8.14 GB	25.3 MB	8.00 GB	No	Yes	Yes	0 bytes	0 bytes	3,023.8

**Comment by prashil-g** [comment]
Still seeing this with latest docker desktop version 4.8.2: 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/95269280/170982550-54671490-9d4c-4ca6-9a65-649fb900fef8.png">

**Comment by davejj1530** [comment]
still seeing this issue using macbook pro m1 even with the new virtualization framework. I was able to lower down RAM usage a bit by configuring memory in the resources
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/66207116/171052674-421048cb-f263-4e28-b940-ae4fd9c1b099.png">

**Comment by MikeChristianson** [comment]
All: Be sure to include the "Real Memory" stat, from Activity Monitor, to help provide a more complete picture. See also https://github.com/docker/for-mac/issues/3232. 

† I'm just a subscriber to this Issue, not the original author or a Docker dev.

**Comment by malaguitte** [comment]
Seeing this issue on Docker version `4.9.1 (81317)`, `qemu-system-aarch64` is using **13.60 GB of Memory**.
Checked `Real Memory` for the Activity Monitor. ✅ 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8172274/174688338-8a607615-86b7-44b6-be3d-77c5370bb497.png">

**Comment by r4b8iiiiiit** [comment]
Also still having the issue on 4.9.1 (M1 Mac)

**Comment by pautri** [comment]
This seems to be a Docker Desktop specific issue, rather than Docker daemon. With Rancher Desktop using dockerd and the same resource settings (8GB, 4 cores), I'm getting much lower memory usage numbers.

I'm not sure whether `real memory` is the proper measure to look at given that recent macOS versions perform memory compression dynamically and the real memory usage decreases over time for processes that are not very active. The `memory` value is still what is being allocated by the process AFAIA. Docker Desktop seems to allocate all the memory that is specified under "resources" immediately upon launch. Here's what I'm getting in an idle condition, shortly after launch (M1 Pro 16GB):

```
                                                %CPU (approx)   Memory  Real Memory
Docker Desktop                                  6               8.5GB   2.3GB
Docker Desktop (new Virtualization framework)   3               8.0GB   1.9GB
Rancher Desktop                                 3               1.5GB   1.6GB
```

I'm also not sure how much of a problem this is in high resource usage scenarios, haven't tried this out yet as I only just got this M1 Mac, but lower resource usage/allocation in idle circumstances would certainly be welcome.

btw. `real memory` is not shown by default in Activity Monitor, you need to enable the column from the View menu.

**Comment by dan-developer** [comment]
> This seems to be a Docker Desktop specific issue, rather than Docker daemon. With Rancher Desktop using dockerd and the same resource settings (8GB, 4 cores), I'm getting much lower memory usage numbers.
> 
> I'm not sure whether `real memory` is the proper measure to look at given that recent macOS versions perform memory compression dynamically and the real memory usage decreases over time for processes that are not very active. The `memory` value is still what is being allocated by the process AFAIA. Docker Desktop seems to allocate all the memory that is specified under "resources" immediately upon launch. Here's what I'm getting in an idle condition, shortly after launch (M1 Pro 16GB):
> 
> ```
>                                                 %CPU (approx)   Memory  Real Memory
> Docker Desktop                                  6               8.5GB   2.3GB
> Docker Desktop (new Virtualization framework)   3               8.0GB   1.9GB
> Rancher Desktop                                 3               1.5GB   1.6GB
> ```
> 
> I'm also not sure how much of a problem this is in high resource usage scenarios, haven't tried this out yet as I only just got this M1 Mac, but lower resource usage/allocation in idle circumstances would certainly be welcome.
> 
> btw. `real memory` is not shown by default in Activity Monitor, you need to enable the column from the View menu.

I believe real memory is not the correct parameter as memory pressure goes up a lot when using Docker Desktop i.e. confirming that the memory column is correct.

**Comment by WuhuGoldPilot** [comment]
This question still exist !!!!

**Comment by gouku** [comment]
> Try the Use the new Virtualization framework option in the Experimental section of the Settings

When using the new Virtualization framework. You will get another issue: The Docker process it self will eat your RAM linear over time:

![Screen Shot 2022-07-22 at 2 55 25 PM](https://user-images.githubusercontent.com/9361308/180382074-62f3ac42-8232-4b97-baf8-df157297e7f1.png)

At the time of writing I think Docker for Mac is only usable for testing and local development purpose. Not for homelab server or something that you have to run for a long time.

**Comment by calvinjuarez** [comment]
Seeing the issue on 4.10.1 w/ new virtualization, just updated to 4.11.1 with no change, still using max allocated memory from jump.

**Comment by rewanthtammana** [comment]
The issue still persists. I just got the mac 1 day ago. I installed docker & a few other tools. Docker using 9.87 GB of RAM with zero containers :( Any alternative to docker desktop for mac?

**Comment by nicks** [comment]
Hi all! Thanks for reporting. 

I'm going to close this issue, since as Dave points out above in https://github.com/docker/for-mac/issues/5812#issuecomment-1108270154, there are several different issues being reported here. and some, including the OPs issue, have been addressed. It's hard for us to inform people when if your individual issue is fixed if we're lumping all problems into a single issue.

Some of the recent comments about memory usage are probably just a misunderstanding due to some bugs and UX problems on how newer version of macOS reportsmemory usage. We're working with Apple on this. See this doc: https://docs.google.com/document/d/17ZiQC1Tp9iH320K-uqVLyiJmk4DHJ3c4zgQetJiKYQM/edit
