### ISSUE TITLE
Docker Desktop on Mac: usual menu items and keyboard shortcuts are missing, eg. Hide (CMD-h)

### ISSUE THREAD

**Issue by marc-guenther** [docker/for-mac#5813]
_Docker Desktop_ on Mac is missing some of the usual menu items that every Mac application has, like:
- Hide (CMD-h)
- Preferences (CMD-,)

But _Docker Desktop_ actually HAS a preferences section, and also Hide is available by right-clicking on the Dock icon.

So it would be nice to have these available as the usual keyboard shortcuts as well.

**Comment by marc-guenther** [comment]
CMD-h works in latest version, CMD-, is still missing though.

No idea why it works all of a sudden, there are no relevant commits in this repo whatsoever.

Thanks for moving the issue to the correct place. I followed a link from the homepage, which lead me to docker/compose-cli, it was the only link to an issue tracker that I could find, so I created this issue there.

**Comment by niccolomineo** [comment]
There's a regression in the latest version in that the CMD-h shortcut is not working anymore

**Comment by marc-guenther** [comment]
Again? 😮

**Comment by niccolomineo** [comment]
> Again? 😮

yep

**Comment by ericestes** [comment]
The Quit menu item and the Window and Help menus are also missing.

**Comment by EricWVGG** [comment]
cmd-M for minimize-to-dock

**Comment by klaspetersson** [comment]
Same issue here. I'm running version 4.3.2 (72729) and all menu options except "About" (which does nothing if selected) are missing from the "Docker Desktop" menu and I'm not able to hide the application with cmd-H.

**Comment by SethMilliken** [comment]
Now on `4.5.0` and we're still missing all of the usual app menu items except "About" (which should be "About Docker Desktop", but at least it shows version information now). Not having Command-h is frustrating.

Hilariously, there are keyboard shortcuts associated with some of the menu items of the Docker Desktop menu bar icon, which require you to click on that icon. The menu bar icon menu has "About Docker Desktop" (the full correct string), "Preferences", "Quit Docker Desktop", and "Restart". So close! Just get those moved over to the actual app.

**Comment by pzich** [comment]
Can we please get these added (back)?
