### ISSUE TITLE
Lost all data after Docker update to 3.5.1, Engine 20.10.7

### ISSUE THREAD

**Issue by dmitry-provectus** [docker/for-mac#5815]
- [ v] I have tried with the latest version of Docker Desktop
  - [ v] I have tried disabling enabled experimental features
  - [ v] I have uploaded Diagnostics
  - Diagnostics ID: 4E0C88F9-47FA-4017-81BB-C81E234ACD36/20210701134037

### Expected behavior

Not to loose any data

### Actual behavior

Lost all data (images, containers, volumes)

**Comment by JanMouwes** [comment]
I'm experiencing a similar issue, I lost all containers, images and volumes as well. I'm now also seeing different containers, images and volumes that weren't there before the update and that I haven't worked with in months, so I'm guessing some setting got reset somewhere.

**Comment by dmitry-provectus** [comment]
It seems to be very common issue with Docker upgrade, here are a few examples for Mac: #3772, #1175, and for Windows: https://github.com/docker/for-win/issues/4344

**Comment by mkitezr** [comment]
This hit me too. Lost containers, images. I do run time machine. Is there a way to restore this? I tried restoring the Docker folder in ~/Library/Containers/com.docker.docker and no luck.

**Comment by mkitezr** [comment]
I did get an error when updating and it only let me "Reset to factory defaults" or quit. But Docker Desktop would not start.

**Comment by shikimoon** [comment]
I got the same problem orz

**Comment by shikimoon** [comment]
> I got the same problem orz

I got the solution[https://github.com/docker/for-mac/issues/5754](url)
