### ISSUE TITLE
Reseting to factory default stuck in my mac

### ISSUE THREAD

**Issue by hassanQureshi22** [docker/for-mac#5817]
Resetting to factory default stuck I don't know what to do Please Help

![image](https://user-images.githubusercontent.com/24655331/124225385-cd9d3300-db20-11eb-82b4-1713962af85b.png)

**Comment by BillyD73** [comment]
I had this issue too. Workaround was to manually uninstall Docker (https://nektony.com/how-to/uninstall-docker-on-mac lists the Library files you will need to delete) and reinstalling.

**Comment by hassanQureshi22** [comment]
Well Thank you I have just fix this issue by killing all docker processes and then restarting my mac.
