### ISSUE TITLE
Kubernetes is not 

### ISSUE THREAD

**Issue by alonsoir** [docker/for-mac#5818]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
k8s up and running after Docker Desktop starts.
### Actual behavior
K8s failed to start.
### Information

  - macOS Version: 11.4 (20F71)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Version 3.5.1 (3.5.1.7)

### Steps to reproduce the behavior

  1. Start Docker Desktop.
  2. Kubernetes, enable Kubernetes.
  3. 4 CPUS, 8GB RAM, 4 GB SWAP

More data in https://github.com/docker/for-mac/issues/5696#issuecomment-871357665

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by alonsoir** [comment]
@lorenrh the issue cannot be closed because it is not solved and it is not any patch. I cannot run k8s in docker Desktop for mac, the message when I run from scratch is Kubernetes is starting... and nothing happens. It does not start. Please, if you can reproduce the problem, ask me something, but but don't leave me hanging because because of this problem, I can't finish my k8s training on the only machine I have available.

MacOs version: 11.4 (20F71)
Kubernetes version 1.21.2
Docker engine: v20.10.7

{
  "experimental": false,
  "builder": {
    "gc": {
      "enabled": true,
      "defaultKeepStorage": "20GB"
    }
  },
  "features": {
    "buildkit": true
  }
}

**Comment by alonsoir** [comment]
The problem is still there. It is not working for the latest patch. 

Docker Desktop version Version 3.5.2 (3.5.2.18)
Kubernetes version v1.21.2
OSX version 11.4 Big Sur

zsh 3474 [1] % pred='process matches ".(ocker|vpnkit)."
|| (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
[mié 21/07/14 11:50 CEST][s000][x86_64/darwin20.0/20.5.0][5.8]
<aironman@MacBook-Pro-de-Alonso:~>
zsh 3475 % /usr/bin/log show --debug --info --style syslog --last 1d --predicate "$pred" >/tmp/k8s-logs-1-day-latest-version.txt


[k8s-logs-1.day-latest-version.txt](https://github.com/docker/for-mac/files/6815310/k8s-logs-1.day-latest-version.txt)

**Comment by alonsoir** [comment]
Ok, i reset to default values and it looks it is working.

Docker desktop Version 3.5.2 (3.5.2.18)

```
zsh 3492 % kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
[vie 21/07/16 12:37 CEST][s000][x86_64/darwin20.0/20.5.0][5.8]

```
