### ISSUE TITLE
Error when using 'Start Docker Desktop when you log in'

### ISSUE THREAD

**Issue by robarb** [docker/for-mac#5824]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I have 'Start Docker Desktop when you log in' turned on, I expect Docker to run on startup.

### Actual behavior
When booting, Docker doesn't run and I get an error that says 'Docker fatal error failed to ping backend api' and the 'Exit' button does nothing. I need to quit Docker manually. If I start Docker manually, it's fine.

### Information
This started happening when I updated Docker about a month ago on a MacOS 10.4.6 system that had been fine for years.  I recently got a new computer with MacOS 11.4 and, after working fine for 3 days, this problem started happening on this new machine too. If I start Docker manually, it's fine.

This is 100% reproducible.

  - macOS Version: 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.1

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Anutrix** [comment]
Same issue. I don't get the error but the docker silently just doesn't start even though 'Start Docker Desktop when you log in' is turned on.

- macOS Version: 11.5.1
- Intel chip or Apple chip: Intel
- Docker Desktop Version: 3.5.2
