### ISSUE TITLE
Stage caching sometimes doesn't work properly when using with buildx

### ISSUE THREAD

**Issue by vova-lantsov-dev** [docker/for-mac#5825]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I didn't enable anything experimental
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1D531AA5-6669-47A2-A4A8-D04A6A29E660/20210705114941

### Expected behavior

`[linux/arm/v6 downloader 4/4]` step should be cached (like `[linux/arm64 downloader 4/4]` or `[linux/arm/v7 downloader 4/4]`) instead of running `curl` again

### Actual behavior

<img width="1210" alt="Screen Shot 2021-07-05 at 12 58 39" src="https://user-images.githubusercontent.com/45858087/124464681-28db5980-dd9d-11eb-93ec-ad1324863967.png">

### Information

  - macOS Version: 11.4 Big Sur
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.4.0 (65384)

### Steps to reproduce the behavior

  1. Create file
```dockerfile
FROM alpine as downloader
WORKDIR /teamcity

RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

RUN curl -SL --output TeamCity.tar.gz https://download.jetbrains.com/teamcity/TeamCity-2021.1.1.tar.gz && \
    tar -xzf TeamCity.tar.gz && \
    rm TeamCity.tar.gz

FROM vlrpi/rpi-jdk11:debian-bullseye
LABEL maintainer="Vova Lantsov"
LABEL contact_email="contact@vova-lantsov.dev"
LABEL telegram="https://t.me/vova_lantsov"

COPY --from=downloader /teamcity .

EXPOSE 8111 9090

ENV TEAMCITY_DATA_PATH /root/BuildServer
ENTRYPOINT ["TeamCity/bin/teamcity-server.sh","run"]
```
  2. Create builder
```bash
docker buildx create --name rpi --node rpi-node --platform linux/arm64,linux/arm/v6,linux/arm/v7 --driver docker-container
```
  3. Run first build to cache the intermediate images
```bash
docker buildx build --platform linux/arm64,linux/arm/v7,linux/arm/v6 -t vlrpi/rpi-teamcity-server:debian-bullseye-2020.1 --builder rpi --pull .
```
  4. Run second build to check if caching works
```bash
docker buildx build --platform linux/arm64,linux/arm/v7,linux/arm/v6 -t vlrpi/rpi-teamcity-server:debian-bullseye-2020.1 --builder rpi --pull .
```
  5. Now let's investigate other platform combinations:

a)
Input:
```bash
docker buildx build --platform linux/arm64,linux/arm/v6 -t vlrpi/rpi-teamcity-server:debian-bullseye-2020.1 --builder rpi --pull .
```
Output:
<img width="675" alt="Screen Shot 2021-07-05 at 14 42 27" src="https://user-images.githubusercontent.com/45858087/124466715-9092a400-dd9f-11eb-89a1-c8d69f7f98c2.png">
Result: caching might not work even in the middle, not for the last command only.

b)
Input:
```bash
docker buildx build --platform linux/arm/v6,linux/arm/v7 -t vlrpi/rpi-teamcity-server:debian-bullseye-2020.1 --builder rpi --pull .
```
Output:
<img width="642" alt="Screen Shot 2021-07-05 at 14 38 39" src="https://user-images.githubusercontent.com/45858087/124466831-b28c2680-dd9f-11eb-99a2-a997521cd348.png">
Result: this is not only arm/v6-related problem, because occurred for arm/v7 as well while arm/v6 worked as expected

c)
Input:
```bash
docker buildx build --platform linux/arm/v7,linux/arm64 -t vlrpi/rpi-teamcity-server:debian-bullseye-2020.1 --builder rpi --pull .
```
Output:
<img width="777" alt="Screen Shot 2021-07-05 at 14 47 23" src="https://user-images.githubusercontent.com/45858087/124467118-17478100-dda0-11eb-93aa-c4c9afa55abd.png">
Result: sometimes caching works for all architectures

Let me know if you need more information.

**Comment by vova-lantsov-dev** [comment]
Update: I had no enough disk space for images, so caching didn't work.

<img width="505" alt="Screen Shot 2021-07-05 at 15 09 26" src="https://user-images.githubusercontent.com/45858087/124470184-f97c1b00-dda3-11eb-81d6-892337e51052.png">

Please add a warning about that in console or as a system notification, it's really unclear.

Problem is solved.

**Comment by stephen-turner** [comment]
OK, closing.
