### ISSUE TITLE
"Apply & Restart" button is off-screen when System Preferences is set to Larger Text

### ISSUE THREAD

**Issue by ssb22** [docker/for-mac#5826]
macOS 11.4, System Preferences / Displays / Scaled is set to "Larger text".  Hardware is a 2019 MacBook, System Report says the built-in LCD is "3072x1920 Retina".  The system does have an external monitor, but under Accessibility I set the external monitor to show a magnified view of the built-in LCD.

Under these circumstances, Docker Desktop v3.5.1 produces a window that is a little too large for the screen.  It does not allow the window to be resized any smaller.  Most of it can still be accessed, but today I found that under Settings / Resources, if I change the RAM size, the setting does not take effect unless I press a button labelled "Apply & Restart", which I did not know existed because it was displayed off-screen.

It is still possible to press the button while it is off-screen: after sliding the RAM control to where I wanted it, I pressed Tab 5 times and Enter, and the setting took effect.  So I'm all set, but I thought you might still like to know this happened.  Thanks.

**Comment by stephen-turner** [comment]
Thank you for the feedback. We do have a work item to reduce the minimum size of the window, but it's queued up behind making the columns resize properly. It's useful to hear how it's necessary for accessibility reasons: I'll try and get it accelerated for this reason.

**Comment by ssb22** [comment]
/remove-lifecycle stale
The bug is still present in version 4.0.1.  Thanks.

**Comment by ssb22** [comment]
Version 4.3.2 appears to be fixed: the Apply & Restart button is now on-screen (at least on my machine)
