### ISSUE TITLE
Azure function not working

### ISSUE THREAD

**Issue by vitor-l** [docker/for-mac#5827]
I am using Docker to run a simple Azure function with Node. It builds correctly, but when the build is finished, this error occurs:

> serverless_1  | Unhandled exception. System.IO.IOException: Function not implemented
> serverless_1  |    at System.IO.FileSystemWatcher.StartRaisingEvents()
> serverless_1  |    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
> serverless_1  |    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
> serverless_1  |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
> serverless_1  |    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
> serverless_1  |    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
> serverless_1  |    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
> serverless_1  |    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
> serverless_1  |    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
> serverless_1  |    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
> serverless_1  |    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
> serverless_1  |    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
> serverless_1  |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
> serverless_1  |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
> serverless_1  |    at Microsoft.Azure.WebJobs.Script.WebHost.Program.BuildWebHost(String[] args) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Program.cs:line 35
> serverless_1  |    at Microsoft.Azure.WebJobs.Script.WebHost.Program.Main(String[] args) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Program.cs:line 25
> serverless_1  | qemu: uncaught target signal 6 (Aborted) - core dumped

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
