### ISSUE TITLE
Docker not starting, no way to access VM to restore containers

### ISSUE THREAD

**Issue by clevcode** [docker/for-mac#583]
### Expected behavior

Docker actually starting up...

### Actual behavior

Docker fails to start. I get these messages in ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/syslog:

2016-09-11 08:47:26 +0000 UTC daemon.info vsudd: 2 Failed to connect to Unix domain socket after 10s /var/run/docker.sock dial unix /var/run/docker.sock: connect: connection refused
2016-09-11 08:47:27 +0000 UTC daemon.info vsudd: Connection 3 to: 2376 from: 00000000
2016-09-11 08:47:37 +0000 UTC daemon.info vsudd: 3 Failed to connect to Unix domain socket after 10s /var/run/docker.sock dial unix /var/run/docker.sock: connect: connection refused
2016-09-11 08:47:38 +0000 UTC daemon.info vsudd: Connection 4 to: 2376 from: 00000000
...

This goes on forever, so any docker command from the Mac host environment just gives me:
Error response from daemon: Bad response from Docker engine

I (urgently) need to restore certain Docker containers, or at least certain files from them, but I can't seem to find any way to access the actual VM?!

"docker-machine ls" does not show any machines (and didn't even when Docker was working), so I can't use something like "docker-machine ssh default" to enter the Linux host with the containers in question. Is there any way for me to just start up the Docker VM and log in to it, if so - how?

UPDATE: At least I found a way to enter the host:
screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty

Or more conveniently:
screen -AmdS docker ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
screen -r docker

### Information

Diagnostic ID: E1B455ED-67D0-4ED3-B50E-00CCF71EE605
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119
