### ISSUE TITLE
Docker for mac failed to boot, then diagnostics failed to capture

### ISSUE THREAD

**Issue by tcrayford** [docker/for-mac#5833]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I cannot, as the "Diagnosing" Dialog has been hanging for 10+ minutes:

![image](https://user-images.githubusercontent.com/55975/125067612-677a5800-e0ac-11eb-83f2-45d66467cb35.png)

During this, the osx console is sent repeatedly this set of logs:

![image](https://user-images.githubusercontent.com/55975/125068006-df488280-e0ac-11eb-93b2-bd12cc1346d0.png)

### Expected behavior

I opened docker for mac.
I expected the application to boot and to work

### Actual behavior

The app crashed, and this error dialog showed:

![image](https://user-images.githubusercontent.com/55975/125067676-795bfb00-e0ac-11eb-90f8-65e4d57b33dc.png)

### Information
  - Is it reproducible?
  - Is the problem new?
  - 
Yes

  - Did the problem appear with an update?

Yes

  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version:
![image](https://user-images.githubusercontent.com/55975/125067706-82e56300-e0ac-11eb-8b46-e74315a8c034.png)

  - Intel chip or Apple chip:

Intel

  - Docker Desktop Version:

Cannot find it, as I cannot open the app.

### Steps to reproduce the behavior

Download docker for mac
Open it.

**Comment by johnthagen** [comment]
I had a similar issue where the upgrade from 3.5.1 -> 3.5.2 is failing over and over on Catalina 10.15.7.

**Comment by lorenrh** [comment]
Hello, thanks for the report.

Would you mind trying out this build to see if it fixes the problem? 

https://desktop-stage.docker.com/mac/stable/amd64/66585/Docker.dmg

Alternatively you can try to run diagnostics from the command line, you can follow the steps here https://docs.docker.com/docker-for-mac/troubleshoot/#diagnosing-from-the-terminal
