### ISSUE TITLE
Error on mac boot/login: `Terminator: The operation couldn’t be completed. (Docker.UDSResponseError error 1.)`

### ISSUE THREAD

**Issue by schellj** [docker/for-mac#5835]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `DA642456-20A5-450F-BE3C-BE6A92B1BED9/20210712182320`

### Information

  - macOS Version: `10.15.7`
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: `3.5.2 (66501)`

### Steps to reproduce the behavior

  1. Reboot mac/login with Docker Desktop version `3.5.2 (66501)` installed with `Start Docker Desktop when you log in` enabled
  2. Observe `Terminator: The operation couldn’t be completed. (Docker.UDSResponseError error 1.)` error

Note that Docker Desktop started up fine manually after this error.

**Comment by linuswillner** [comment]
Also experiencing this on macos Big Sur 11.5. Seems to go away when you disable "Use the new Virtualization framework".
