### ISSUE TITLE
Please add Docker Desktop Version to Dashboard (or troubleshooting) panes, and add "check for upgrades"

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5837]
- [X] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When upgrading multiple machines, I always have to go 1) Find out the current version and 2) check for updates. It's awkward as these are hidden only on the whale icon. It would be a lot nicer if they just showed up on the dashboard or troubleshooting page. Just showing the version on one of those pages would be a great step forward for me, and then adding an update or check for updates button would be great. 

Thanks!

This is obviously a request for Docker for Windows as well.

**Comment by rfay** [comment]
Would like to see this. Simple thing. Think it could get on the board @stephen-turner ?

**Comment by stephen-turner** [comment]
I must be missing something here. Why is it easier than having it in the About box, where we already have that information? Or another idea: what if the version number was in the whale menu, next to the status icon (on Mac)?

The reason I'm questioning it is that we're getting push-back from other people about the amount of stuff in the main window.

**Comment by rfay** [comment]
Hi @stephen-turner - good questions. I maintain lots of test runner machines with docker desktop on them. So every time there's an update, I want them to see it before ddev users see it. So I have to connect to the machines and see what's up. If the version and update options were just on the troubleshooting page (additionally) I wouldn't have to do the very slow "find-the-icon and then request the update and then say yes-i-want-to-download-it and then say ok-update-it". I'd do less anyway. While it's totally reasonable to have an about menu item and a check-for-updates menu item, if that could just be also consolidated on the troubleshooting page (or somewhere) in the main window it would be a great advance.  

Related:
* #5803

**Comment by stephen-turner** [comment]
So in your workflow, is the main window open already when you log into the machines?

**Comment by rfay** [comment]
Yes, when the default "open window on start" is set, and I would probably leave it that way. At least there would only be one window to open, not a right-click-and-open to check version and then another right-click to check for updates.

**Comment by rfay** [comment]
Looks like that may not work any more?

This is a super simple feature request that would be lovely for those of us that have to manage multiple machines.

**Comment by rfay** [comment]
This is good enough now as the version is shown on desktop
