### ISSUE TITLE
All my images and containers got lost with the last 2 docker updates

### ISSUE THREAD

**Issue by cperezabo** [docker/for-mac#5838]
Hi, I have macOS 11.4, last two Docker updates have got my images and containers lost! Now I'm in v3.5.1, and there is an update available, I don't want to lost my data again! I tried to contact you via twitter and your web's contact form with no response at all. Worst support ever. What can I do? I cannot be afraid of updating a central tool like Docker!

**Comment by jamshid** [comment]
Sorry not the same problem -- I didn't lose all my data on update -- but FWIW I was having a really weird, disturbing problem with 3.5.2 where some images I build and use when building other images (e.g. garthk/unzip) were simply disappearing from `docker images` soon after my build script uses them.
I ended up doing a `docker system prune -f` and that cleared a bunch of images and layers, seems to be behaving better now.

**Comment by cperezabo** [comment]
In my case docker just doesn't show any image nor container, but they are using disk space! I had to remove all docker related folders and start from scratch! Two times!! and there is no response from Docker side!

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
Especially check step 6 in the docs on how to get individual support.

**Comment by cperezabo** [comment]
@StefanScherer , do you need the diagnostic information before updating with all my data safe or after updating having lost my current data?? Because now I have the update available and I want to know if you need me to lost my data to send you the diagnostic or I can generate it in the current state.

**Comment by StefanScherer** [comment]
@cperezabo We normally only need the diagnostics after a problem occurred. The logs also contain previous versions and updates.
