### ISSUE TITLE
Segmentation Fault with curl call and instagram 

### ISSUE THREAD

**Issue by florentbolo** [docker/for-mac#5846]
Continuation of : https://github.com/docker-library/php/issues/1176#issuecomment-880988143

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E49637BF-924B-41E1-B645-976E1B840FCF/20210715203530

### Expected behavior

Hi !
I want to 
`curl https://graph.instagram.com`
from my container

### Actual behavior

return 
`segment fault`
but it worked with any other websites 
And curl instagram in my local terminal worked too

It might be after the installation of Openvpn via Tunnelbclick or maybe not.

  - macOS Version: Mac Os Big Sur
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 3.5.2

Thanks for your suggestions :)

**Comment by chris-crone** [comment]
@thaJeztah this looks similar yes.

@florentbolo are you using a Debian Buster based image? If so, I believe you've run into an issue with `libcrypto` that @djs55 has reported upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989604

There are a couple of workarounds that you can use:
1. Use another image, e.g.: alpine based, older or newer Debian based
1. Tell `curl` to use older ciphers: `curl --tls-max 1.2 https://graph.instagram.com`

For (2), you might also need to specify a cipher using `--ciphers` based on what the server supports

**Comment by florentbolo** [comment]
@chris-crone Thanks for your answer.
`curl --tls-max 1.2 https://graph.instagram.com`

Worked for me !

**Comment by AustinC** [comment]
In my case this specific TLS cipher was negotiated with graph.instagram.com, and worked for other servers as well:
```
curl -v --ciphers ECDHE-RSA-AES128-GCM-SHA256 https://dl.yarnpkg.com/debian/pubkey.gpg
```
