### ISSUE TITLE
Settings window doesn't fit on screen

### ISSUE THREAD

**Issue by sheerun** [docker/for-mac#5847]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics - not relevant
  - Diagnostics ID:

### Expected behavior

Settings window fits on screen

### Actual behavior

It doesn't fit when dock icons are on the left, which is my default

### Information

![](https://i.imgur.com/g3x6W4q.jpg)

**Comment by StefanScherer** [comment]
@sheerun Thanks for the report. We're looking for a solution. We'll keep this ticket open and report back.

**Comment by StefanScherer** [comment]
@sheerun I just want to give you an update. We're currently working on the Docker Desktop UI to make it resizable. It will also save the current size and position when you close the window. This is planned to be shipped with the next release, probably 4.2.0.
