### ISSUE TITLE
can't issue docker command

### ISSUE THREAD

**Issue by kaiser70** [docker/for-mac#585]
### Expected behaviour
after freshly installed docker for mac I wanted to open a terminal and issued docker command. 

### Actual behavior
bash-3.2$ docker ps
bash: docker: command not found

### Information

Diagnostic ID: 7CC11848-D975-40A4-93B9-1B68B5A7E09D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@kaiser70 Sorry for your trouble. Can you check to see if Docker for Mac beta 25 fixes this issue? 

Download: https://download.docker.com/mac/beta/Docker.dmg 

Thanks
