### ISSUE TITLE
fatal error: cannot install symlinks /usr/local/bin (stage 5)

### ISSUE THREAD

**Issue by ghost** [docker/for-mac#5852]
I have tried with the latest version of my channel 
 I have uploaded Diagnostics
Diagnostics ID: 4D846F28-2863-478F-B1FB-D68E96F362AB/20210717064837

Expected behavior
Docker should start without issue

Information
macOS Big Sur Version: 11.4

##

**Comment by sreddyp07** [comment]
<img width="617" alt="Screen Shot 2021-07-17 at 2 52 31 AM" src="https://user-images.githubusercontent.com/86802667/126038686-8eccbbc8-f17f-40fc-876f-325b3d9e77ae.png">

**Comment by beerpig** [comment]
I have the same problem, could u tell me how to fix it? thanks

**Comment by dovemy** [comment]
please see ：https://github.com/docker/for-mac/issues/5650#issuecomment-832154124

`sudo mv /usr/local/bin /usr/local/bin.old`
