### ISSUE TITLE
Idle outgoing TCP connections close before 6 minutes

### ISSUE THREAD

**Issue by ssb22** [docker/for-mac#5857]
As in previous ticket #2406 if I do `nc -l 0.0.0.0 1234` on the Mac, then `nc localhost 1234` from the Mac keeps the idle connection open indefinitely but `nc host.docker.internal 1234` from a Docker container times out after 5 minutes and 28 seconds (longer than in #2406 but still not indefinite).

So when I run an X11 application inside Docker with display on the Mac's XQuartz (via TCP, because bind-mounting XQuartz's Unix socket doesn't work), the window is automatically destroyed if I don't use it for 5 or 6 minutes.  This is not the behaviour I want if I've left it in a specific state ready for later use at short notice (e.g. a demonstration).

I can work around this by using `docker run --privileged` and before running the X11 application I do this in the Docker container:

    echo 100 > /proc/sys/net/ipv4/tcp_keepalive_time
    echo 30 > /proc/sys/net/ipv4/tcp_keepalive_intvl

but this needs to be repeated on every run.  This is not a very satisfactory workaround because it requires me to run all X11-client containers in `--privileged` mode (although I suppose that's not as bad on Mac as on Linux because the extra privilege extends only as far as the Docker Desktop VM).

It would be nice if Docker Desktop could default to keeping outgoing TCP connections open indefinitely.

* Docker image `ubuntu:focal` (Ubuntu 20.04 LTS)
* Docker Desktop Version 3.5.1 (3.5.1.7)
* macOS version 11.4
* Intel processor (2019 MacBook Pro)

**Comment by justincormack** [comment]
cc @djs55
