### ISSUE TITLE
Docker stuck on "Starting" after latest update

### ISSUE THREAD

**Issue by NickKaramoff** [docker/for-mac#5859]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features — irrelevant, as I don't have access to the settings
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `D75378C7-208B-4961-87DC-807038713F17/20210720101708`

### Expected behavior

Docker Engine starts

### Actual behavior

After update, Docker Engine gets stuck on "Starting".

### Information

It was all working well until I had to restart the app to update the Engine. Now I can't access my containers or images as well as settings. The app shows a spinner. The CLI commands say `Error response from daemon: dial unix docker.raw.sock: connect: connection refused`.

  - macOS Version: 10.15.7 (19H1217)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2 (3.5.2.18)

### Steps to reproduce the behavior

N/A

P. S. I guess this is the same thing as #5858. I'm not sure, due to lack of information

**Comment by NickKaramoff** [comment]
Update: Since I don't have time to wait for a response, I have tried the "Clean / Purge data" option, which sadly didn't help. Only resetting everything helped

**Comment by veselinnguyen** [comment]
Nothing helps to solve the problem. And most fun of it is that DOCKER does not have any proper handlers or timeouts whatever it does in the background. It is completely stuck on the screen says forever: Docker Starting... 
Maybe in another parallel galaxy.

**Comment by bmurithi** [comment]
✅  The only thing that worked for me to resolve this was rebooting (M1 Mac) - `Version 3.5.2 (3.5.2.18)`

Before that I tried (all failed):

- Purge Data
- Reset to factory defaults
- Deinstall
- Reinstall

**Comment by harrouet** [comment]
This has been happening for years. Docker does not seem to care about it. There are many such issues closed for lack of support.
