### ISSUE TITLE
not able to  start or open docker taking forever

### ISSUE THREAD

**Issue by nagpach** [docker/for-mac#586]
### Information

Diagnostic ID: A71CD0C3-C8B1-411A-A125-879E5B0D673E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1912)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-07-07T19:06:53.052451733Z" level=debug msg="Using default logging driver json-file"
time="2016-07-07T19:06:53.052702712Z" level=debug msg="Golang's threads limit set to 42390"
time="2016-07-07T19:06:53.054015829Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-07-07T19:06:53.056734785Z" level=debug msg="Using graph driver aufs"
time="2016-07-07T19:06:53.265332568Z" level=debug msg="Failed to load mount b99d7ce42cc0e81570689328aad97635fb5707575b7ca52a7b1da0be8fb7d62f: invalid mount id value"
time="2016-07-07T19:06:53.266451914Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-07-07T19:06:53.266630572Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-07-07T19:06:53.303109147Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-07-07T19:06:53.305726421Z" level=debug msg="Loaded container 0455e395c5585b0549f5d369b257f62bb5a7eb9f2c0480658a46d95966ce0279"
time="2016-07-07T19:06:53.307521443Z" level=debug msg="Loaded container 1fa2646aad56ad03666828e65c625635c15ea31bc6bfb653141aea587ec7db4c"
```
