### ISSUE TITLE
com.docker.backend doesn't always LISTEN: diverging behavior between docker for Linux and for Mac

### ISSUE THREAD

**Issue by nopid** [docker/for-mac#5860]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
A container is first created with a single interface to an internal network but publishing a port to forward.
The container is started.
The container is then connected to the bridge network.
After that, host and guest can communicate through that port.

### Actual behavior
Under Docker Desktop for Mac, everything looks fine inside the Hyper VM (one can see /usr/bin/docker-proxy being spawned and launching nc from inside that vm works) but com.docker.backend is not LISTENing on the forwarded port.

### Information
  - macOS Version: 11.4
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 3.6.0 (67351)

### Steps to reproduce the behavior
Minimal example:
```
docker network create --internal mynet
docker create --name foobar --network mynet --publish 6666:6666 -it alpine:latest
docker start -i foobar
```
There check that there is of course no possibility to use port 6666. Add the bridge like so:
```
docker network connect bridge foobar
```
Try to exchange on port 6666, for example with `nc -l -p 6666` inside the container and `nc localhost 6666` outside. Works under Linux not under Docker Desktop for Mac.

### To investigate further
```
lsof -ni TCP | grep dock
```
does not show `com.docker.backend` LISTENing on the port as expected. Looking inside the Hyper VM now:
```
docker run -it --rm --privileged --pid=host justincormack/nsenter1
```
Here `ps ax` clearly shows docker-proxy being spawned:
```
# ps ax | grep 6666
 6711 root      0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 6666 -container-ip 172.17.0.3 -container-port 6666
 6718 root      0:00 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 6666 -container-ip 172.17.0.3 -container-port 6666
```
and iptables are updated as expected:
```
# iptables -t nat -L -v | grep 6666
    0     0 MASQUERADE  tcp  --  any    any     172.17.0.3           172.17.0.3           tcp dpt:6666
    0     0 DNAT       tcp  --  !docker0 any     anywhere             anywhere             tcp dpt:6666 to:172.17.0.3:6666
```

**Comment by melcarthus** [comment]
I'm running into some problems on macmini m1, 11.4 docker 5.3.2 that I need to restart the container every now and then because my local files wont sync. I came to this issue-post because I was searching for a cause why my docker could stop listening mid project. Could this be the same issue?

**Comment by nopid** [comment]
The problem persists in 3.6.0.
