### ISSUE TITLE
Disable/Remove Button "Open in Visual Studio Code"

### ISSUE THREAD

**Issue by 9ae8sdf76** [docker/for-mac#5861]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Remove or disable showing the `Open in Visual Studio Code` button when hovering over the apps row in the dashboard

### Actual behavior
N/A

### Information
While I do have Visual Studio Code installed, it is unrelated to Docker and it distracts from my workflow when I accidentally click on the button and have to stop and close Visual Studio Code. It's intrusive and a nuisance. I'd like the option to either hide it, disable it, or simply remove it completely without having to remove Visual Studio Code. 

I have been unable to find any setting or configuration that will do this for me, but if it already exists, I could use some guidance.

Thank you.

**Comment by 9ae8sdf76** [comment]
Digging through the Electron code, I see there is a `/system/editor` API and that there are editors for IntelliJ, VSCode, etc. But I am unable to reverse-engineer how to access those APIs, nor do I know where they come from.

**Comment by stephen-turner** [comment]
Thanks for the feedback, but sorry this is a Won't Fix. While I understand you don't like the button, no-one else has ever complained about this, and we're not going to add options to customise every piece of UI.

**Comment by 9ae8sdf76** [comment]
@stephen-turner 

> no-one else has ever complained about this

Wow. So tell me, what's the criteria then to make something a will fix? How many people exactly does it take?

> we're not going to add options to customise every piece of UI.

I'm not asking to customize every piece of the UI. Just this one.

**Comment by stephen-turner** [comment]
There isn't a fixed number, but we have several million active users so we can't implement everything that everyone asks for.

**Comment by 9ae8sdf76** [comment]
> There isn't a fixed number

That's a bit arbitrary. 

> but we have several million active users

Tell me my feedback doesn't matter, without telling me "it doesn't matter"; you go first.

> so we can't implement everything that everyone asks for.

Right. So help me understand what criteria I need to bring to the table in which you would actually consider [my] requests? Because frankly, it sounds an awful lot like you don't want user input at all. Or is it because I just don't have the Docker street cred like other folks?

**Comment by stephen-turner** [comment]
Feedback does matter, but for feature requests our primary sort is the number of people requesting it.

The two main ways we collect feedback are privately through the in-app survey (which gets hundreds of textual responses per day), and publicly on the docker roadmap https://github.com/docker/roadmap (where other users can comment on and/or support the request). You are welcome to submit your request to the latter and see whether the community gets behind it.

**Comment by 9ae8sdf76** [comment]
> feature requests

Technically this can be considered a bug, because I have multiple system editors, but you're only choosing what I assume is the first one in the list of found editors. I should be able to somehow set which editor is the system editor (i.e., what is returned by the `/system/editor` endpoint internally). ¯\_(ツ)_/¯

> You are welcome to submit your request

No thanks. The barrier to entry seems a bit high considering that it took this long, and a lot of probing on my part, just to find this out.

Good day.
