### ISSUE TITLE
first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by vms22** [docker/for-mac#5863]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A0E8C2A3-05BB-49AF-8155-C7139DF661AD/20210721070405

### Expected behavior
docker pull should be successful
### Actual behavior
docker pull fails "Error response from daemon: Get https://registry.tools.XXXX.XXX/v2/: tls: first record does not look like a TLS handshake"

### Information

  - macOS Version: 10.15.7 (19H15)
  - Intel chip or Apple chip: 2.6 Ghx 6-Core Intel Core i7
  - Docker Desktop Version: 20.10.7, build f0df350

### Steps to reproduce the behavior

[20210721072351.zip](https://github.com/docker/for-mac/files/6853565/20210721072351.zip)

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Does it work pulling from Docker Hub? If so, this is an issue with your registry not with Docker Desktop.

**Comment by vms22** [comment]
Thank you Stephan.

Yes, pull from Docker Hub is successful.

I am seeking advise / tips of area that I need to explore on my registry?

Note:
— Other colleagues can pull from our repository (I cannot)
— I can open the registry page when I browse it on google

So your recommendation greatly appreciated


Thanks Vishal

**Comment by stephen-turner** [comment]
I don't have any prior knowledge of this error, but https://www.google.com/search?q=first+record+does+not+look+like+a+tls+handshake+docker might have some solutions.
