### ISSUE TITLE
Segmentation fault on `curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg`

### ISSUE THREAD

**Issue by reachlin** [docker/for-mac#5864]
- [ X ] I have tried with the latest version of Docker Desktop
  - [ X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
able to add yarn repo key

### Actual behavior
```
#9 2.100 gpg: Segmentation fault
#9 2.101 no valid OpenPGP data found.
```

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: Docker version 20.10.7, build f0df350 / Docker Desktop 3.5.2 (66501) is currently the newest version available.

### Steps to reproduce the behavior
```
=> CACHED [base  5/12] RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -                                                                      0.0s
 => ERROR [base  6/12] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -                                                             2.5s
------                                                                                                                                                        
 > [base  6/12] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -:                                                                        
#9 0.949 Warning: apt-key output should not be parsed (stdout is not a terminal)                                                                              
#9 2.100 gpg: Segmentation fault
#9 2.101 no valid OpenPGP data found.
------
executor failed running [/bin/sh -c curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -]: exit code: 2
ERROR: Service 'rails' failed to build : Build failed
```

Also tried:
```
 git:(master) ✗ docker run --rm -it ruby:2.7-buster bash -c "curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /dev/null && echo ok"
gpg: no valid OpenPGP data found.

inside this container,
root@bb63440cdb56:/# curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg 
Segmentation fault
```

**Comment by stephen-turner** [comment]
This is a bug in libssl, see https://docs.docker.com/docker-for-mac/release-notes/#known-issues

**Comment by ramblingenzyme** [comment]
@stephen-turner Is there a bug raised with libssl that we can track? Do we know for sure that affected OS's won't update their bundled version of libssl? I know it's not really Docker's responsibility, but is there a workaround?
Is there a known version of libssl that we could downgrade to?

Bit useless to just say "older versions of this library are broken just wait for new versions of these OS's and then upgrade your image".

**Comment by HarueMurakami77** [comment]
I was faced with similar problem.
It solved by this [temporary measures](https://github.com/laravel/sail/issues/162) .

**Comment by stephen-turner** [comment]
@ramblingenzyme The link I posted has all the details of what to use. It's already fixed in newer versions of libssl, and hence in the latest versions of the OSes. It's only old versions that are affected. Obviously we have no control over that.

**Comment by VictorXLR** [comment]
Hi, 

I was able to bypass the issue by doing this 
```dockerfile 

RUN wget https://dl.yarnpkg.com/debian/pubkey.gpg 
RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN cat pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y nodejs yarn postgresql-client

# remove pubkey 
RUN rm pubkey.gpg
```
