### ISSUE TITLE
Docker Desktop notifying for updates permanently, even for up-to-date client

### ISSUE THREAD

**Issue by plgingembre** [docker/for-mac#5867]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 343581FF-FD51-4CA2-9CB3-94A1C837FFDE/20210721152352

### Expected behavior
After clicking "Update and restart" several times on my Docker Desktop client, I still see the "!" sign to notify me that I should upgrade Docker Desktop. My client is running 20.10.7, no Kubernetes, no experimental features.

<img width="255" alt="Screen Shot 2021-07-21 at 8 24 25 AM" src="https://user-images.githubusercontent.com/15028081/126516053-d25d2f74-045d-42cd-93f3-4d98d6a1c1c6.png">

Clicking on "Download update..." does not get me to a better place as I get this message:

<img width="710" alt="Screen Shot 2021-07-21 at 8 29 45 AM" src="https://user-images.githubusercontent.com/15028081/126516232-4cbe2c0c-f028-45c3-b4bc-69b621192929.png">

### Actual behavior
After upgrading to the latest, I should not have this little icon that triggers the user's attention for a potential upgrade.

### Information

  - macOS Version: macOS Big Sur 11.4
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 20.10.7

### Steps to reproduce the behavior

I don't have a typical way to reproduce it, it's on my machine, I haven't found a typical pattern that triggers that behavior (it "just" happened).

**Comment by davexre** [comment]
I have the same issue. I have Docker Desktop 3.3.3 (which is Engine 20.10.6). I'm also on Big Sur (11.4) on an Intel chip machine. I have Kubernetes v 1.19.7 (per the Docker Desktop "About" window). I continually get pop-ups telling me that 3.5.1 has been downloaded and is ready to install. I click to install it, and nothing happens.

**Comment by Ghirigoro** [comment]
This is also happening to me along with a popup that tells me I have to update (only pro subscriptions can opt out).

**Comment by DandyDev** [comment]
I have the same problem. Super annoying!

**Comment by devantoine** [comment]
I had the same issue too. I ended up killing all the docker related process, started Docker for Mac again, downloaded and installed the latest version and restarted.

It's not showing any more update.

**Comment by JESii** [comment]
Same here... this keeps popping up:
![2021-08-07 at 6 24 AM](https://user-images.githubusercontent.com/486/128601913-6b7aa8d9-5f73-4b7c-aaa2-04ae1625f060.png)
"Skip this update" doesn't work (#5892 ).
"Install and launch" apparently doesn't work because it keeps coming up over and over again
I'm going to try the work-around mentioned for "Skip this update" and hope it works

**Comment by nathj07** [comment]
Today I got so fed up with it I uninstalled docker for mac, then reinstalled. That seems to have sorted it out for me. It is highly annoying though

**Comment by trungutt** [comment]
Could you run the following command and attach the output, please?

`/usr/bin/log show --debug --info --style syslog --last 1d | grep [Ss]parkle`

(assuming you’ve triggered the update less than a day ago, and it failed)

You can adjust the number of days after `--last 1d` to see if there's more log

**Comment by pacu** [comment]
`/usr/bin/log show --debug --info --style syslog --last 1d | grep [Ss]parkle` returns

````
pacu@pacu ~ % /usr/bin/log show --debug --info --style syslog --last 1d | grep [Ss]parkle
zsh: no matches found: [Ss]parkle
````

I have the same problem where an update fails to install and I'm being popped the same message everyday

**Comment by mat007** [comment]
Has anyone seen this issue with a fairly recent version of Docker Desktop (say 4.5.x+)?
