### ISSUE TITLE
Cannot Install: Request failed: GET /analyse/startup-failure failed: no response

### ISSUE THREAD

**Issue by SRIVERAL** [docker/for-mac#5868]
Hello,

I am trying to upgrade desktop Docker on a Mac with the following configuration:

<img width="592" alt="Screen Shot 2021-07-21 at 3 48 52 PM" src="https://user-images.githubusercontent.com/32771909/126558446-59da4d7e-a094-4ce0-ab55-dab3cb8a6b70.png">

After starting the upgrade process, the following error occurs:

![Screen Shot 2021-07-21 at 3 53 00 PM](https://user-images.githubusercontent.com/32771909/126558620-bde7c222-ed5d-4d6c-ba82-e642230bae53.png)

Based on the similar report with #4986, I got the following information:

1. I ran the command. 
    /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
   and got the error ID: 
          Diagnostics Bundle: /tmp/8C5CEAB2-188A-4026-BB8A-3F085A4D3C5A/20210721204112.zip
          Diagnostics ID: 8C5CEAB2-188A-4026-BB8A-3F085A4D3C5A/20210721204112 (uploaded)
2. I ran the command
    curl --unix-socket ~/Library/Containers/com.docker.docker/Data/docker-api.sock http:/localhost/analyse/startup-failure
   and got the error:
   curl: (7) Couldn't connect to server
3. This is the log file
[logs.zip](https://github.com/docker/for-mac/files/6858838/logs.zip)

Thanks.

**Comment by Darveesh** [comment]
Same issue here.  I ran the diagnostics command:

Diagnostics Bundle: /tmp/091FFEFB-DCCD-4D8B-B229-0BB4050FB45C/20210809163618.zip
Diagnostics ID:     091FFEFB-DCCD-4D8B-B229-0BB4050FB45C/20210809163618 (uploaded)

![image](https://user-images.githubusercontent.com/13259199/128742168-fb1a9d04-9cc1-4028-842b-cdb38e990f0e.png)

**Comment by SRIVERAL** [comment]
After a few days, the upgrade process worked correctly. I am now on version 3.5.2.
