### ISSUE TITLE
Docker not Start after Standard installation on Mac OS. Actual Virtual Box Version is installed.

### ISSUE THREAD

**Issue by lomboz** [docker/for-mac#587]
### Information

Diagnostic ID: 6C0C392A-653A-49A6-9374-0FB55503D9E7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/6C0C392A-653A-49A6-9374-0FB55503D9E7/20160911-190552/qemu-img-check.stdout 2> /tmp/6C0C392A-653A-49A6-9374-0FB55503D9E7/20160911-190552/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Volumes/Macintosh_HD/Users/hans_schneider2/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by lomboz** [comment]
It is generally possible to use Docker and Virtual Box at the same time? I use a windows for test purposes and i would use docker for local Developing.

**Comment by mchiang0610** [comment]
@lomboz We've tested it working with latest Virtualbox installed at the same time. 

Are you running the latest Virtualbox? If I remember correctly, there were issues with Virtualbox 4.3.x 

Does resetting to factory defaults help in the interim as we look into this? Or trying beta 25 
https://download.docker.com/mac/beta/Docker.dmg

**Comment by mchiang0610** [comment]
Closing this for now. Will reopen once we get an update on this.
