### ISSUE TITLE
upgrade to 3.5.2.18, can not start docker 

### ISSUE THREAD

**Issue by Jacky-LinPeng** [docker/for-mac#5874]
未升级之前是可以正常使用docker引擎的，但是升级了之后就一直无法正常使用了，
Docker engine could be used normally before the upgrade, but it could not be used normally after the upgrade, and restarting the computer to retry was invalid.

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/15797691/126734181-38a5778e-b286-42d8-b119-145cd1fddae0.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/15797691/126734208-ce75461d-96f0-4c82-91a0-058a01665df6.png">

**Comment by Jacky-LinPeng** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/15797691/126734390-e0dcea0c-6fb5-48e1-af62-380d899e2417.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/15797691/126734406-009aaeeb-a1ca-4a4d-b82b-f567e8d05fcb.png">

**Comment by Koziar** [comment]
I've got the same issue, it just hangs and restart didn't help
<img width="1156" alt="Screenshot 2021-07-27 at 15 08 54" src="https://user-images.githubusercontent.com/9032472/127158919-534cd12d-7c2b-4e91-ab10-6f87d1183404.png">

**Comment by Jacky-LinPeng** [comment]
> I've got the same issue, it just hangs and restart didn't help
> <img alt="Screenshot 2021-07-27 at 15 08 54" width="1156" src="https://user-images.githubusercontent.com/9032472/127158919-534cd12d-7c2b-4e91-ab10-6f87d1183404.png">

My solution: I reinstalled Docker!

**Comment by truedat101** [comment]
How to do a full-uninstall?  I had a previously installed version.  But this leaves files under ~/.docker and ~/Library/ApplicationSupport/Docker.
