### ISSUE TITLE
Upgrade Big Sur 11.5 - docker is not working

### ISSUE THREAD

**Issue by qenibas** [docker/for-mac#5876]
Hi
I've just updated my mac to Big Sur 11.5 and now docker isn't working.
Before it wasn't working very good either - had to close it via activity manager and then open again.

But not I just can't start the app at all. It "times out".
Tried to uninstall and reinstall again.
Get this error box, but can't click on anything. It's just stuck. 

"Fatal Error"
"Failed to ping backend API"

Diagnostics ID:     D319DBAE-6DC1-4AEA-8529-1C31126F8ACA/20210723091618

**Comment by qenibas** [comment]
Just tried to download version 3.3.3 and finally got access to reset factory settings.
Now it's running again.

But.. don't wan't to upgrade before being able to fix the issue?

**Comment by frjtrifork** [comment]
I had a similar issue with Docker 3.5.1 on Big Sur 11.5 after upgrading from Big Sur 11.4 to 11.5. 

When I got the message I didn't have much luck getting on from there.

If I clicked Exit - the process would hang and I get a never ending spinning ball
I tried clicking diagnose  - after a while it says Diagnose succeeded - But if I clicked either Open or Upload the process would also hang and the never ending spinning ball will appear.
If I clicked Reset to factory defaults it would also hang.

I did a `sudo ps -ef | grep -i docker` and then did sudo kill -9 for each of the Docker process pids (both desktop and background) and then I could launch Docker Desktop which could then launch the engine without problems.

**Comment by rtroch** [comment]
Had the same issue. Killed all Docker processes and did a reinstall. Got it working again.

**Comment by natted** [comment]
Have the same issue, I killed docker processes and reinstalled - this fixed it temporarily. Recently rebooted and docker is getting the same error again.

**Comment by qenibas** [comment]
I'm still running an old version, but have to restart the programme a couple of times each time for it to work.
Really hope for a solution soon :-)

**Comment by frjtrifork** [comment]
Odd, I had the issue the original post in this thread is about. Then did the kill processes and installed the latest and all was fine. Or so I thought.
It turns that if I enable the "start on login" setting - I get the "Failed to ping backend API" error on login - and have to kill the Docker processes manually from a Terminal. After that I can start Docker desktop without any problems - without changing anything.

Similarly if I disable the "start on login" and manually start Docker after I have signed in, I don't get any errors about the backend API and everything is working fine.

I don't know - but maybe the Big Sur update have caused the "launch after login" applications to be triggered with fewer permissions or earlier than they used to - or maybe Docker desktop is just launching before the API is ready/and or not waiting long enough for it to become ready?
