### ISSUE TITLE
Docker Desktop is Intel architecture

### ISSUE THREAD

**Issue by mnahta** [docker/for-mac#5878]
I've version 3.3.3 for Apple chip. https://docs.docker.com/docker-for-mac/release-notes/. However, why is this running on intel architecture? I presume it's just the desktop client. 

My mac is very slow with docker so I want to ensure that everything is correct. 

![image](https://user-images.githubusercontent.com/12686965/126888097-f9b39b4f-bdb0-435d-965c-dcc8e0a7c0a7.png)

I can't upgrade from 3.3.3 further since firebase-admin does not work with the newer docker versions.

**Comment by mkadirtan** [comment]
You need to use apple-silicon version: https://docs.docker.com/docker-for-mac/apple-silicon/

**Comment by mnahta** [comment]
The whole point on why I asked this question is I downloaded apple silicon docker but it doesn't show as such.
