### ISSUE TITLE
file --list-extensions is not found

### ISSUE THREAD

**Issue by alavrentik** [docker/for-mac#5881]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The Docker application should start without any error messages

### Actual behavior
Intellij IDEA launches, and error message appears(Can not open file .../com.docker.docker/Data/--list-extensions)
see screenshot https://prnt.sc/1gk037t
problem is reproducible, every time I close and open again Docker Desktop the error message is shown

### Information

  - macOS Version: Big Sur 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: latest from website https://www.docker.com/products/docker-desktop

### Steps to reproduce the behavior
  1. Go to https://www.docker.com/products/docker-desktop then download and install docker
  2. Launch it

**Comment by theartofdevel** [comment]
Same thing!

Intel chip.

**Comment by lorenrh** [comment]
Thanks for the report, this is a duplicate issue,  so I'm closing this in favor of https://github.com/docker/for-mac/issues/5840.
