### ISSUE TITLE
(Apple Silicon) docker-compose amd64 images not running with error qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by fr13ndly-alien** [docker/for-mac#5883]
Hi, I'm using mac pro M1 with docker desktop for work.
When starting my local environment by docker-compose (with images have built for amd64 architecture), I got core image (built from scala project, using maven) running but not working as the below log:
![image](https://user-images.githubusercontent.com/51918679/127187431-1006638a-b0a8-40f0-8cbe-24b53a15cc9a.png)

Container configuration:
#docker-compose.yml
![image](https://user-images.githubusercontent.com/51918679/127187680-a879fdaf-d990-4528-94ca-02a36cc4b11c.png)

Build command: `mvn -pl app -P dockerimage dockerfile:build -DskipDockerPush -Dbuild.number=${BUILDNUMBER}% `

Information from my mac:
OS: macOS BIg Sur 11.4 
Chip: Apple M1
Docker desktop version: 3.5.2 (3.5.2.18)
Local java version: 1.8

Docker desktop configurations:
![image](https://user-images.githubusercontent.com/51918679/127187957-7973fdac-5f63-4ee9-9f49-22e9422ee7e7.png)
![image](https://user-images.githubusercontent.com/51918679/127188072-a7ffd5aa-1fdc-49d9-96af-45a087a409e3.png)
![image](https://user-images.githubusercontent.com/51918679/127188130-cf21b472-4df0-4155-a479-7852b43b2e55.png)

**Comment by justincormack** [comment]
Hi, if qemu has bugs (which unfortunately it does; you can file issues but you will need to debug the issue in qemu) you will need to use native arm64 images.
