### ISSUE TITLE
Terminal tab hanged and no response when starting docker container ubuntu

### ISSUE THREAD

**Issue by sivalingams** [docker/for-mac#589]
### Information

Diagnostic ID: 8B6744B7-F31C-4149-BB8F-66CDF2BD67E9
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. $ docker run -i -t ubuntu
2. Terminal tab is hanged and no response.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. 
May be related to docker/for-mac#785

The following log matches:
```
Sep 11 16:39:27 FDLMC713 Docker[com.docker.vmnetd][47220] <Notice>: User 502 has container folder /Users/user/Library/Containers/com.docker.docker/Data/s60
Sep 11 16:39:27 FDLMC713 Docker[com.docker.vmnetd][47220] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 11 16:39:27 FDLMC713 Docker[com.docker.vmnetd][47220] <Notice>: User 502 has container folder /Users/user/Library/Containers/com.docker.docker/Data/s60
Sep 11 16:39:27 FDLMC713 Docker[com.docker.vmnetd][47220] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 11 16:39:27 FDLMC713 Docker[com.docker.docker][47206] <Error>: Symlinks are not correctly installed.
Sep 11 16:39:27 FDLMC713 Docker[com.docker.docker][47206] <Notice>: com.docker.osx.hyperkit.linux launched with PID 47223
Sep 11 16:39:28 FDLMC713 Docker[com.docker.osx.hyperkit.linux][47223] <Notice>: Acquired task manager lock
Sep 11 16:39:28 FDLMC713 Docker[com.docker.frontend][47224] <Critical>: dial unix /Users/user/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Sep 11 16:39:28 FDLMC713 Docker[com.docker.osx.hyperkit.linux][47223] <Notice>: Maximum number of file descriptors is 10240
```
