### ISSUE TITLE
"Skip this update" button without function

### ISSUE THREAD

**Issue by flowl** [docker/for-mac#5892]
> Update ready to install
> 
> Docker Desktop Version 3.5.2 (66501) July 7 2021

Clicking on "Skip this update" does nothing.
Clicking on "Snooze" dismisses the dialog.

(Edit: My current version is 3.5.1.7)

**Comment by nicolaskopp** [comment]
I second this. SNOOZE works for me, but "Skip this update" does aboslutely nothing.

**Comment by mat007** [comment]
Thanks for the report.
Yes we’ve noticed this as well and fixed it, this should be available in the next release (meaning it’s going to work again when updating to the next release after that 😬).

As a workaround you can edit `~/Library/Group Containers/group.com.docker/settings.json` and change or add a `updateSkippedBuild` field with a string value containing the build number of the skipped version, e.g. for 3.5.2 (the latest release as of today) it’s `"66501"`.

Sorry for the inconvenience.
