### ISSUE TITLE
Docker for Mac seems to listen to port 3000

### ISSUE THREAD

**Issue by ansidev** [docker/for-mac#5895]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker don't use common port for development purposes to avoid conflicting port.

### Actual behavior

Docker used port `3000`.

### Information
  - macOS Version: BigSur 11.4
  - Intel chip
  - Docker Desktop Version: 3.5.2

### Steps to reproduce the behavior
  1. Start Docker Desktop.
  2. Run `lsof -i tcp:3000`
  3. Run `ps -ax | grep 123456` (123456 is the process ID from the above result).

![Screen Shot 2021-08-05 at 14 02 32](https://user-images.githubusercontent.com/6688235/128307722-ce3e9a07-c447-4f40-a6e4-2d24f9ef0017.png)

Referenced issue: #4906.

**Comment by stephen-turner** [comment]
@ansidev We can't reproduce this. Are you sure you don't have any containers running that could be taking port 3000? What is the output of `docker ps`?

**Comment by ansidev** [comment]
@stephen-turner
1. This is the first time I faced this issue since I have started using Docker for Mac. So I don't know why it occurred, but I confirmed it occurred, so you should investigate.
2. The process command used port 3000 (see the screenshot) is: `...com.docker.backend -watchdog -native-api`. What is that and why it was started?
3. I have to reset to factory default as recommended from #4906 (nth time, the previous times were all because of update incompatibility without any warning, and I'm not happy at all). Now everything works again.
4. Result of `docker ps`
```shell
CONTAINER ID   IMAGE                                                         COMMAND                  CREATED        STATUS          PORTS                                                                                                                                                 NAMES
f96663fcee45   registry.gitlab.com/therunninghub/system/docker:jr-database   "docker-php-entrypoi…"   31 hours ago   Up 21 seconds   9000/tcp                                                                                                                                              database-dev-01
a6e2b87e5e42   bitnami/mariadb:latest                                        "/opt/bitnami/script…"   31 hours ago   Up 20 seconds   0.0.0.0:33000->3306/tcp, :::33000->3306/tcp                                                                                                           mariadb-dev-01
0230a9cc8654   rabbitmq:3.8-management-alpine                                "docker-entrypoint.s…"   31 hours ago   Up 18 seconds   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   rabbitmq-dev-01
e50445caf8bf   redis:6.2-alpine                                              "docker-entrypoint.s…"   31 hours ago   Up 11 seconds   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                                             redis-dev-01
```

**Comment by thaJeztah** [comment]
> The process command used port 3000 (see the screenshot) is: ...com.docker.backend -watchdog -native-api. What is that and why it was started?

Could still be a container running. Containers run in a VM, and docker needs to forward requests to localhost to the VM (and the container);

Without containers running, nothing shows up:

```bash
$ lsof -i tcp | grep com\.dock
```

Start a container listening on port 3000, and it shows up as `com.docker.backend` listening:

```bash
$ docker run -d --name foo1 -p 3000:80 nginx:alpine
$ lsof -i tcp | grep com\.dock
com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)

$ lsof -i tcp:3000
COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)
```

Start two more containers, and those show up as `com.docker.backend` as well:

```bash
$ docker run -d --name foo2 -p 3001:80 nginx:alpine
$ docker run -d --name foo3 -p 3002:80 nginx:alpine

$ lsof -i tcp | grep com\.dock
com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)
com.docke 81154 sebastiaan 2526u  IPv6 0x8a8d313c54bcb7d1      0t0  TCP *:redwood-broker (LISTEN)
com.docke 81154 sebastiaan 2527u  IPv6 0x8a8d313c56dc09d1      0t0  TCP *:exlm-agent (LISTEN)

$ lsof -i tcp:3001
COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 81154 sebastiaan 2526u  IPv6 0x8a8d313c54bcb7d1      0t0  TCP *:redwood-broker (LISTEN)

$ lsof -i tcp:3002
COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 81154 sebastiaan 2527u  IPv6 0x8a8d313c56dc09d1      0t0  TCP *:exlm-agent (LISTEN)
```

**Comment by ansidev** [comment]
> > The process command used port 3000 (see the screenshot) is: ...com.docker.backend -watchdog -native-api. What is that and why it was started?
> 
> Could still be a container running. Containers run in a VM, and docker needs to forward requests to localhost to the VM (and the container);
> 
> Without containers running, nothing shows up:
> 
> ```shell
> $ lsof -i tcp | grep com\.dock
> ```
> 
> Start a container listening on port 3000, and it shows up as `com.docker.backend` listening:
> 
> ```shell
> $ docker run -d --name foo1 -p 3000:80 nginx:alpine
> $ lsof -i tcp | grep com\.dock
> com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)
> 
> $ lsof -i tcp:3000
> COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)
> ```
> 
> Start two more containers, and those show up as `com.docker.backend` as well:
> 
> ```shell
> $ docker run -d --name foo2 -p 3001:80 nginx:alpine
> $ docker run -d --name foo3 -p 3002:80 nginx:alpine
> 
> $ lsof -i tcp | grep com\.dock
> com.docke 81154 sebastiaan 2331u  IPv6 0x8a8d313c56dc3d91      0t0  TCP *:hbci (LISTEN)
> com.docke 81154 sebastiaan 2526u  IPv6 0x8a8d313c54bcb7d1      0t0  TCP *:redwood-broker (LISTEN)
> com.docke 81154 sebastiaan 2527u  IPv6 0x8a8d313c56dc09d1      0t0  TCP *:exlm-agent (LISTEN)
> 
> $ lsof -i tcp:3001
> COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> com.docke 81154 sebastiaan 2526u  IPv6 0x8a8d313c54bcb7d1      0t0  TCP *:redwood-broker (LISTEN)
> 
> $ lsof -i tcp:3002
> COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> com.docke 81154 sebastiaan 2527u  IPv6 0x8a8d313c56dc09d1      0t0  TCP *:exlm-agent (LISTEN)
> ```

@thaJeztah
1. No docker container expose or public port 3000. Absolutely!
2. You are not wrong, but it 's just the theory. If the reality is the same as the theory, we don't need to discuss anymore.
3. I am not the only one person who faced this issue.
