### ISSUE TITLE
Unable to install docker 2.3.04 on Mac with Fatal error

### ISSUE THREAD

**Issue by eshaseth** [docker/for-mac#5897]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  1. Download Docker 2.3.0.4 from https://docs.docker.com/docker-for-mac/previous-versions/
  2. Try to install in Mac
  3. Fails with error Fatal error: The data couldn’t be read because it is missing. Failed to analyse

**Comment by stephen-turner** [comment]
This is a very old version and we do not recommend using it. If you still have problems with the latest version, please open a new ticket.
