### ISSUE TITLE
[30667941-883A-492E-8069-D0D665CE27EF]can't start docker service

### ISSUE THREAD

**Issue by loivis** [docker/for-mac#59]
### Expected behavior
install docker for mac and start it
### Actual behavior
docker installed, but when lauching, docker is hanging at "starting"...
### Information

Diagnostic ID: 30667941-883A-492E-8069-D0D665CE27EF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/loivis/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/30667941-883A-492E-8069-D0D665CE27EF/20160801-224948/qemu-img-check.stdout 2> /tmp/30667941-883A-492E-8069-D0D665CE27EF/20160801-224948/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

nothing special, just download, install but fail to start

**Comment by loivis** [comment]
most docker command will get "Error response from daemon: Bad response from Docker engine".
logs in qemu-img-check.stderr is all about "Leaked cluster xxxx refcount=1 reference=0"

**Comment by loivis** [comment]
reset to factory defaults twice solves the issue......

**Comment by catull** [comment]
My advise, check with issue #8.  I had the same problem, opened issue #15 and then read issue #8. Did not have to reset anything.

**Comment by loivis** [comment]
thanks, I've read the issue and get some more information . Since I don't have data to keep, so I decided to choose the simple way.
