### ISSUE TITLE
dockerd container is missing ssh

### ISSUE THREAD

**Issue by Nugs** [docker/for-mac#5902]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 517C6036-A85F-4F84-8011-18C16E3BED7C/20210811184549

### Expected behavior

Using `docker buildx build` with git URL specified requiring SSH should successfully source the build context from the remote repository.

### Actual behavior

```
➜ docker buildx build git@github.com:***/***.git
[+] Building 0.3s (1/1) FINISHED                                                                                                                                                       
 => ERROR [internal] load git source git@github.com:***/***.git                                                                                              0.3s
------                                                                                                                                                                                 
 > [internal] load git source git@github.com:***/***.git:
#1 0.239 ssh -F /dev/null -o UserKnownHostsFile=/var/lib/docker/tmp/953733054: ssh: command not found
#1 0.240 fatal: Could not read from remote repository.
#1 0.240 
#1 0.240 Please make sure you have the correct access rights
#1 0.240 and the repository exists.
```

SSH does not appear to be contained within the container running the build.

### Information

  - macOS Version: Mojave (10.14.6)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2 (66501)

### Steps to reproduce the behavior

  1. Attempt to source a docker build from an SSH git URL e.g. `docker buildx build git@github.com:docker/buildx.git`
  2. Note the error `ssh -F /dev/null -o UserKnownHostsFile=/var/lib/docker/tmp/544077690: ssh: command not found`

This was discussed on the community slack [here](https://dockercommunity.slack.com/archives/C7S7A40MP/p1627921745010100)

**Comment by StefanScherer** [comment]
Thanks for the report. Our engineers are looking into this and fix it in a future version.

**Comment by lorenrh** [comment]
Hello,

Docker Desktop 4.0.0 has been released containing a fix for this issue, so I'm closing this issue. Feel free to open a new ticket if the problem persists.
