### ISSUE TITLE
Crash on system startup

### ISSUE THREAD

**Issue by thecontstruct** [docker/for-mac#5906]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A544D3B8-1B2E-4CBA-9146-87358BB9D542/20210813131618

### Expected behavior
Docker starts as expected

### Actual behavior
Docker crashes

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: 2.6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 3.5.2 (66501)

### Steps to reproduce the behavior
One time occurrence so far so we'll see if it happens again. Starting it manually afterwards seems to work

**Comment by FlorianWendelborn** [comment]
For me this happens every time I start docker on login. I’m upgrading to 3.6.0 right now in hopes that it might be fixed...

I’m using FileVault in case that makes a difference
