### ISSUE TITLE
Docker Engine keeps starting and stopping indefinitely

### ISSUE THREAD

**Issue by crs1138** [docker/for-mac#5908]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features => I can't access the experimental features screen
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: f1299f96-13ec-4623-9cbb-601aabf94251/20210813230952

### Expected behavior

I expect to be able to start the Docker engine when the desktop app is launched

### Actual behavior

The engine keeps starting and stopping indefinitely, on and off over and over again

### Information

  - macOS Version: 10.14.6 (18G9323)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version:  3.6.0 (3.6.0.5487)

### Steps to reproduce the behavior

I installed a fresh copy of Docker.app and tried to launch it.

**Comment by mjholtkamp** [comment]
Same here. I can't seem to find an older version of docker, so right now I can't use docker on my laptop. Can I download the previous version somewhere?

**Comment by dgtllion** [comment]
Same here . on macOS. After installing Docker update having issues with starting Docker. It starts & stops every time. Did now restart and it works.

**Comment by crs1138** [comment]
Restart did not help in my case, I've updated to the latest version and the problem persists… My new Diagnostic ID is f1299f96-13ec-4623-9cbb-601aabf94251/20210903191558
