### ISSUE TITLE
docker+mongodb: volume files exist but data lost after docker updating

### ISSUE THREAD

**Issue by cuteufo** [docker/for-mac#5910]
(similar to [issue #1175](https://github.com/docker/for-mac/issues/1175)

Environment:
- MacBook Pro with macOS Big Sur v11.4; 
- Docker images: mongo:latest and mongo-express
- Containers: mongo and mongo-express
- Volume: ./mongo-data on host machine -> /data/db on container

How to repo?
1. Docker Desktop pops up for updating. I didn't notice whether it was updating Docker Desktop or Docker Engine, but after update, all the images/containers/volumes are lost, according to Docker Desktop;
2. Checked the volume folder on host machine, the files are still there;
3. Use following commands to pull images and run containers:
```
docker network create mongo-net
docker run -d -p27017:27017 --name mongo --network mongo-net -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password -v mongo-data:/data/db mongo
docker run -d -p8081:8081 --name mongo-express --network mongo-net -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=password -e ME_CONFIG_MONGODB_SERVER=mongo mongo-express
```
4. The containers resumed running, but after connecting to mongodb server, I found the data were lost.

After reading the issue #1175, I tried to locate the diagnostic info, but don't know where to find it.

Below is the output of `docker version`:
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by susanmonnelly** [comment]
Same happened to me but I see no one is working on this issue since it's been happening since 2019 and the issue is closed and never addressed.

https://github.com/docker/for-mac/issues/3772
https://github.com/docker/for-mac/issues/1175

One thing I think might work is to perform an install rather than an update.   I found my containers were not removed doing it that way.
