### ISSUE TITLE
Docker M1 Unable to install el7 repo

### ISSUE THREAD

**Issue by rolandfa** [docker/for-mac#5912]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4C209CCE-02F7-45D7-8D01-5E6206EC8CC4/20210816172625

### Expected behavior

I have a CentOs 7 container and trying to install EPEL repo and it is unable to open.

### Actual behavior

```
[+] Building 5.1s (7/28)
 => [internal] load build definition from Dockerfile                                                                          0.4s
 => => transferring dockerfile: 2.67kB                                                                                        0.0s
 => [internal] load .dockerignore                                                                                             0.6s
 => => transferring context: 2B                                                                                               0.0s
 => [internal] load metadata for docker.io/library/centos:centos7                                                             0.0s
 => [internal] load build context                                                                                             0.6s
 => => transferring context: 3.78kB                                                                                           0.0s
 => [ 1/24] FROM docker.io/library/centos:centos7                                                                             0.0s
 => CACHED [ 2/24] RUN yum install epel-release -y                                                                            0.0s
 => ERROR [ 3/24] RUN yum install https://repo.ius.io/ius-release-el7.rpm -y                                                  4.3s
------
 > [ 3/24] RUN yum install https://repo.ius.io/ius-release-el7.rpm -y:
#6 2.055 Loaded plugins: fastestmirror, ovl
#6 3.859 Cannot open: https://repo.ius.io/ius-release-el7.rpm. Skipping.
#6 3.860 Error: Nothing to do
------
executor failed running [/bin/sh -c yum install https://repo.ius.io/ius-release-el7.rpm -y]: exit code: 1

```
### Information

  - macOS Version: 11.5.1
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.6

### Steps to reproduce the behavior

  1.  docker run --platform linux/amd64 -it centos:7
  2. yum install https://repo.ius.io/ius-release-el7.rpm -y

**Comment by alxndrbauer** [comment]
I have the same Problem, the error is `Problem with the SSL CA cert (path? access rights?)`

**Comment by laland** [comment]
Having the same problem. With centos7:
- when trying to install any yum package it gives: `Cannot retrieve metalink for repository: epel/x86_64`
- when trying to curl any https resource it gives: `Problem with the SSL CA cert (path? access rights?)`, just like @alxndrbauer says

**Comment by alxndrbauer** [comment]
@laland pretty obscure, but it worked for me aswell. thanks for that!

**Comment by stephen-turner** [comment]
CentOS 7 has a buggy libssl that doesn't work on arm64: see https://docs.docker.com/desktop/mac/release-notes/#known-issues
