### ISSUE TITLE
Moving docker images to external SSD doesn't work.

### ISSUE THREAD

**Issue by rydan** [docker/for-mac#5916]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After changing image location in settings-resources-advanced, docker starts and uses the new image location.

### Actual behavior
After changing image location to external disk in settings-resources-advanced, the image files gets created in the new location (Docker.raw and Docker.qcow2), then docker desktop hangs on trying to start again. If restarted, daemon fails to start with some strange docker swarm error: (DockerDesktop is a clean install, no swarm configured)
"2021-08-18T07:54:25Z dockerd time="2021-08-18T07:54:25.745615709Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."

### Information
  - macOS Version: 11.5.1 (20G80)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.6.0 (3.6.0.5487)

First time running docker on Apple Silicon, so can't say if this is a new problem. Even on Intel-mac, moving the images was shaky at best. Sad, since running the enormous raw and qcow2-files on the internal laptop disk isn't a realistic option.

### Steps to reproduce the behavior
  1. Clean install docker desktop for Apple Silicon
  2. Use settings-resources-advanced to move the image location to external disk

(Also, noteworthy. When docker is "reset to default", Disk image location is indicated to be ~/Library/Containers/com.docker.docker, but the docker data are in fact in ~/Library/Containers/Docker)
![Screenshot 2021-08-18 at 10 44 02](https://user-images.githubusercontent.com/3601580/129867510-f8acfad6-d654-4699-9eab-a278911e78e7.png)

**Comment by aihorko** [comment]
I have the same problem with MacBook Air M1 chip, I can't fix it, it looks to be connected with file systems and support of disk image format. 
- On Mac the file system is APFS and when installing Docker a .raw disk image is created.
- I tried moving disk image location to external volumes with HFS+ and Btrfs file systems - both failed in the same way as you described: 
First, Docker copies Docker.raw file to new location. 
After Docker.raw is copied 100% Docker is restarted and creates .qcow2 file instead, but files to start on that file. 
cow file is only 127 Kb size, while .raw file remains 8 Gb or your defined size).

And I couldn't do anything to convert .raw file to qcow2 while on Mac M1 before moving to external drive. 
This would be a solution: if we could, first, convert .raw to .qcow2, and then change the location to move .qcow2 file.

**Comment by rydan** [comment]
Got it to work by just manually moving the .raw, and then symlinking to it from the default location.

Interesting to note that there's no qcow2 file created when it runs in it's default location.

**Comment by aihorko** [comment]
Cool, for me symlinks didn't work. 
Is your new location on SSD drive also?

It could be difference in drive type - initial Docker.raw is created on SSD (with APFS) - I copied Docker.raw to HDD drive (HFS+ and Btrfs), created symlink on SDD. result is the same as changing location via Docker Desktop app - the app keeps starting and stopping continuously.

**Comment by rydan** [comment]
My external disk is an SSD using ExFAT filesystem.

**Comment by talecK** [comment]
Same issue, anyone figure this out? Symlinks aren't working and there is no effective way for me to use docker on an external drive or anything but my default mac drive which is super inconvenient...

**Comment by rydan** [comment]
Yes, got it working, but don't quite remember how. I run ExFat on the external drive, and if I remember correctly, it had something to do with image file format. Make sure the file you're moving and symlink:ing is a .raw and not a qcow2.

Also, if I remember correctly, it's important to move/symlink only the .raw file, not the entire directory.

Hope it helps somehow, that move in DockerDesktop doesn't work isn't ideal to say the least...
