### ISSUE TITLE
Connection refused after waking from sleep

### ISSUE THREAD

**Issue by hoangtrann** [docker/for-mac#5917]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 620B2352-2C93-4EF8-9548-CCB2B95158CD/20210818120642

### Expected behavior

Docker work normally, no need for restart (thought restart does not work in my case)

### Actual behavior

After waking from sleep, using docker result in connection refused

### Information

  - macOS Version: Big Sur 11.5.2
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 3.6.0 (67351)

### Steps to reproduce the behavior

  1. Put mac to sleep for a while
  2. Wake up, running `docker ps`
  3. Restart the whole system solves the problem, but that's very inconvenience :(

**Comment by Zenexer** [comment]
I've gotten a variety of errors in similar situations.  It's most obvious when resuming from sleep, but sometimes it happens spontaneously without any obvious cause.  The error messages vary.  For example, right now I'm getting:

```
% docker -l debug ps
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: 502  module=api status_code=502
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: 502  module=api status_code=502
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: 502  module=api status_code=502
Error response from daemon: Bad response from Docker engine
```

I haven't found a way to recover without rebooting the whole device.  For example, here's what I'm getting at the moment if I try to restart from the GUI:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/504130/131390007-d503f4ed-8f29-45c8-a514-3d983b8238d8.png">

**Comment by osdiab** [comment]
I have been experiencing this daily, though in my case it resolves by restarting Docker.

**Comment by Pastel001** [comment]
same issue
