### ISSUE TITLE
DB2 image for Docker fails on Apple M1 chip MAC

### ISSUE THREAD

**Issue by eshaseth** [docker/for-mac#5921]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
DB2 docker should work correctly on Apple M1 like it does on Mac Intel chip for BigSur 11.3.1 OS

### Actual behavior
DB2 docker image fails with platform not supported for M1 chip

### Information

  - macOS Version: 11.3.1 Big Sur
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.5.2

### Steps to reproduce the behavior

  1. docker pull ibmcom/db2:latest
  2. Fails with Platform not supported

**Comment by ryantran-novobi** [comment]
Hi there, have you tried adding `--platform=amd64` or `--platform=linux/amd64`?

**Comment by hoangtrann** [comment]
Hi there, have you tried adding `--platform=amd64` or `--platform=linux/amd64`?

**Comment by eshaseth** [comment]
yes, I have tried adding that in yaml but same issue
will try with docker pull directly
