### ISSUE TITLE
Apple M1, macOS Monterey - "database integrity compromised" error

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#5923]
Occasionally, the Docker app causes SQLite data integrity errors (on host side).

When that happens, the following error can be seen in the Console app:
```
Docker[94959] (libsqlite3.dylib): BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/docker/Library/Caches/com.docker.docker/Cache.db-shm
Docker[94959] (libsqlite3.dylib): BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/docker/Library/Caches/com.docker.docker/Cache.db-shm
```

This happens when running various workload involving short-lived containers.

**Comment by stephen-turner** [comment]
Thanks, Benjamin, we'll have a look.
cc @djs55

**Comment by BenjaminPoulain** [comment]
@stephen-turner: did you intend to assign this to me?
Is there additional information we should collect?

**Comment by stephen-turner** [comment]
No, sorry, I meant to assign it to @djs55.
