### ISSUE TITLE
Docker desktop menu hangs for a long time when click on the icon even no container running

### ISSUE THREAD

**Issue by shadow-gray-wolf** [docker/for-mac#5925]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: E7D18174-471B-41B3-AFF8-E5310E2D62A2/20210820193009

### Expected behavior
1. The menu shows quickly after click on the docker desktop icon on the top right bar and menu item can be highlighted and selectable 
2. run 'docker ps' in the command line should quickly got response
### Actual behavior
1. The menu shows quickly but the menu items are not selectable, and the cursor becomes to a busy ball, even other application windows are slow to response click 
2. 'docker ps' returns super slow 

### Information

  - macOS Version: macOS Big Sur
  - Intel chip or Apple chip: 2.4 GHz 8-Core Intel Core i9
  - Docker Desktop Version: Version 3.6.0 (3.6.0.5487)

### Steps to reproduce the behavior
  1. this is a new laptop and the issues happened after installed, it's impossible to use a daily work basis 
  2. containers can run, but too slow to get response from the docker command in terminal

**Comment by JasonAo** [comment]
any one will take a look at my issue here, or anything i need to provide more?

**Comment by bvader** [comment]
I am seeing this exact same behavior with 

Docker Desktop : 4.0.1

macOS Version: macOS Big Sur 11.5.2

Clicking on the Docker Desktop Menu Result the spinner for about 15 secs and freezes the rest of my Mac from Input. 

I have been seeing this behavior for several release, very frustrating. 

I have completely uninstalled and re-installed several times still no luck

**Comment by JasonAo** [comment]
@bvader i found out Docker is conflict with a security app called FortiEDR installed on my laptop, so whenever the docker hang issue happened eventually i got a Crash Reports in the Console generated for FortiEDRCollector, but i don't know which application caused the issue, so i can't have both installed on my laptop to workaround it.
