### ISSUE TITLE
After updating Docker Desktop should still be able to start up

### ISSUE THREAD

**Issue by vovtz** [docker/for-mac#5936]
- [ x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C62722D1-18E2-4BAA-8CA4-B7D3088A12EA/20210826155917

### Expected behavior
Starts up without an error message after updating.

### Actual behavior
Showed an alert with an error message about some version mismatch, showing `GET` and a short URI.

### Information
After more restarts (I believe 3 in total) this problem went away without any intervention (or it must have been the generation of the diagnostic report).

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel chip (2,3 GHz 8-Core Intel Core i9)
  - Docker Desktop Version: 3.6.0 (67351)
  - Docker Desktop Version: 4.0.0 (67817)
  - Docker Desktop Version: 4.0.1
  - Docker Desktop Version: 4.3.0 (71786)

### Steps to reproduce the behaviour
Restart after installing the update (but after some attempts it **does** start).

This continues to happen on later starts, again at least a second attempt is often needed.

**Comment by aeneasr** [comment]
I have the same issue, and actually, Docker is not starting at all any more - even after a factory reset and uninstall/install.

**Comment by vovtz** [comment]
I upgraded to 4.0.0 and it’s still occasionally giving this error on startup:

![image](https://user-images.githubusercontent.com/1536228/131825230-aeda6333-cffd-468f-aa14-32124f4899e4.png)

Usually the second attempt works though.

**Comment by vovtz** [comment]
I finally gave in and used ‘Reset Docker to factory defaults’. That will probably resolve this, but I would have liked to avoid the overhead.

**Comment by vovtz** [comment]
I don’t believe that … resetting to factory defaults didn’t help! 👎

**Comment by vovtz** [comment]
Setting `settingsVersion` in `~/Library/Group Containers/group.com.docker/settings.json` to a lower value (a successful startup restores it to `15`) seemed to help one time, but could be a coincidence since given enough retries it **does** start anyway (and thus sometimes also on the first attempt).

**Comment by vovtz** [comment]
Diagnostic report for 4.0.1: C62722D1-18E2-4BAA-8CA4-B7D3088A12EA/20210924122744

**Comment by vovtz** [comment]
Still no resolution and this complicates my workflow too much: reverted to version 3.5.2.

**Comment by vovtz** [comment]
/remove-lifecycle stale

Still happening, now with version 4.3.0

**Comment by vovtz** [comment]
I finally found the cause for this! On a second partition I keep a backup of an older installation and when starting Docker via Spotlight (by pressing ⌘-Space), it sometimes picks the older version of the binary from that partition (I always assumed that it would have a preference for applications living on the main, System partition - apparently it picks more or less randomly, perhaps related to the number of times each of them has been started this way?).

![image](https://user-images.githubusercontent.com/1536228/152823562-457ec223-dcf3-47a3-af4d-49eacaf96a14.png)
