### ISSUE TITLE
Unable to sign in to Docker Desktop on M1 macOS Big Sur using 2FA (sign in to Docker Hub works)

### ISSUE THREAD

**Issue by DavidAnson** [docker/for-mac#5938]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2F0836EC-6CA8-4202-8A4F-EBEA01122488/20210827052042

### Expected behavior

Entering valid user name, password, and one-time password is accepted for sign-in

### Actual behavior

"Access denied" message in red

### Information

  - macOS Version: 11.5.2
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.6.0 (67351)

### Steps to reproduce the behavior

  1. Run Docker Desktop
  2. Click "Sign in" button at upper-right
  3. Enter valid user name and password
  4. Click Sign In button
  5. Enter verification code
  6. Click Verify
  7. [FAILS]
  8. Sign into http://hub.docker.com/ to verify your credentials
  9. [WORKS]

**Comment by shamelesscookie** [comment]
Same problem here. I also have MFA enabled.

macOS 12.0 Beta (21A5506j)
Apple Silicon
Docker Desktop 4.0.0 (67817)

**Comment by Tynox** [comment]
Same problem after upgrading to 4.0.0.

macOS 11.5.2
Intel chip
Docker Desktop Version 4.0.0 (4.0.0.12)

**Comment by mat007** [comment]
Thanks for reporting this issue, we’re looking into it!

**Comment by mat007** [comment]
We believe this should now be fixed, could you give it another try?
Sorry for the inconvenience.

**Comment by shamelesscookie** [comment]
Working for me
