### ISSUE TITLE
Very slow write performance on a case-sensitive APFS volume 

### ISSUE THREAD

**Issue by imavroukakis** [docker/for-mac#5940]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7BEC6B2A-3DED-439F-9E72-33785C2D8BFC/20210828190051
  - Diagnostics ID: 7BEC6B2A-3DED-439F-9E72-33785C2D8BFC/20210907082103

### Expected behavior
Write performance on a case-sensitive APFS volume, is equal or very near to a case-insensitive volume

### Actual behavior
Write performance is magnitudes worse, container startup/shutdown/extraction are affected. 

Case sensitive volume
```
root@8e7b23bfe90e:/# dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 oflag=direct
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 299.218 s, 3.6 MB/s
```

Case insensitive volume
```
root@44549e5195cf:/# dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 oflag=direct
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.32399 s, 811 MB/s
```

Same test on a case sensitive volume but using `hyperviser.framework` offers some improvement

```
root@b363ac9fe542:/# dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 oflag=direct
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.7058 s, 228 MB/s
```

### Information

  - macOS Version: 11.5.2 
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 20.10.8, build 3967b7d
  - Docker Desktop Version: 20.10.8, build 67817

### Steps to reproduce the behavior

Create case sensitive APFS volume
Modify daemon json, adding
```
"data-root": "/Volumes/YourCaseSensitiveAPFSVolume",
```

run `dd` test via

`docker run -v dd-test:/opt/test -it --rm ubuntu /usr/bin/dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 oflag=direct`

**Comment by imavroukakis** [comment]
addendum: using hyperviser.framework there is some improvement

```
root@b363ac9fe542:/# dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 oflag=direct
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.7058 s, 228 MB/s
```

**Comment by dimaqq** [comment]
possibly off-topic, since you have this set up, could you check if case-sensitivity also affects:
* `docker pull` speed?
* docker desktop cpu usage #5905 ?

**Comment by imavroukakis** [comment]
> possibly off-topic, since you have this set up, could you check if case-sensitivity also affects:
> 
> * `docker pull` speed?
> * docker desktop cpu usage [com.docker.hyperkit 100% cpu usage  #5905](https://github.com/docker/for-mac/issues/5905) ?

`pull` speed is also suffering, as is container startup times

**Comment by imavroukakis** [comment]
@StefanScherer sorry to be a pain and ping you directly, is there anyone triaging tickets? The performance killing ones seem to get no love 😢

**Comment by djs55** [comment]
@imavroukakis thanks for the ticket.

I believe the `"data-root": "/Volumes/YourCaseSensitiveAPFSVolume"` is running `dockerd` itself from the host filesystem. Normally `dockerd` uses a Linux filesystem inside a hidden VM which is case-sensitive and very fast.

If you have files on a case-sensitive APFS volume which you wish to share with a container:
```
docker run -v /Volumes/YourCaseSensitiveAPFSVolume:/volume -it alpine
```

If you would like to store the Docker containers and images on a volume, then use whale menu -> Preferences -> Resources -> (scroll down) -> Disk image location.

Let me know if this helps!

**Comment by imavroukakis** [comment]
Hi @djs55 ! The problem here is the performance that is suffering though, even when I do not move the location of the image/containers/volumes.

**Comment by djs55** [comment]
Hi,

This line in the `daemon.json`:
```
"data-root": "/Volumes/YourCaseSensitiveAPFSVolume",
```
causes `dockerd` to run on top of a remote filesystem (like NFS or Samba/CIFS). It's not guaranteed to work and will definitely be very slow. The configuration would be ok in native Linux, but not on the Mac where `dockerd` is running in a VM and `/Volumes` is a network share.

Could you try
1. removing the `data-root` option from the `daemon.json`
2. using the UI to move the VM's disk (whale menu -> Preferences -> Resources -> Disk image location) to your preferred volume (case-sensitive or case-insensitive?)

and then try the benchmarks again? It would also be worth checking the raw performance of those filesystems with `dd` on the host, to see if there is a difference.

**Comment by imavroukakis** [comment]
@djs55 thanks for the very useful insight! I will post another round with the VM on the case sensitive volume - having said that, my use case is either a bind mount from a case sensitive volume, or a docker volume stored on a case sensitive volume. 

Case Sensitive volume, native
```                                                                                
1+0 records in
1+0 records out
1073741824 bytes transferred in 1.673638 secs (641.561622 MB/sec)
```

Case insensitive volume, native
```
1+0 records in
1+0 records out
1073741824 bytes transferred in 0.999205 secs (1074.596007 MB/sec)
```


The tests below are with the VM on the case insensitive volume and using a bind mount, i.e.

```
docker run -v /Users/ioannis:/opt/test -it --rm ubuntu /usr/bin/dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1
```
and

```
docker run -v /Volumes/CaseSensitive:/opt/test -it --rm ubuntu /usr/bin/dd if=/dev/zero of=/opt/test/test1.img bs=1G count=1 
```


Case insensitive volume, docker 
```
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 6.29472 s, 171 MB/s
```

Case Sensitive volume, docker
```
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 6.34791 s, 169 MB/s
```

**Comment by dimaqq** [comment]
> [docker-desktop-robot](https://github.com/docker-desktop-robot) closed this as [completed](https://github.com/docker/for-mac/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [10 hours ago](https://github.com/docker/for-mac/issues/5940#event-7086063298)

LOL
