### ISSUE TITLE
Docker Desktop will not start on macOS Monterey Beta 6

### ISSUE THREAD

**Issue by shamelesscookie** [docker/for-mac#5942]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostic ID: C780C897-D84E-4237-8548-A9B6C9EF7EC9/20210902043514

### Expected behavior
Docker Desktop can startup normally

### Actual behavior
Docker Desktop spins in the "starting" phase indefinitely

### Information
I have been using Docker on my Apple Silicon mac without issue for quite some time. Recently there was a macOS Monterey Beta Update 6 (12.0 21A5506j) and now Docker Desktop will not start.

I've tried uninstalling and reinstalling Docker Desktop 4.0.0.
I've tried downgrading Docker Desktop to 3.6.0, but it also experiences the issue.

I also ran the following to fully remove the app:

```
  rm -rf /Applications/Docker.app/
  rm -rf ~/Library/Application\ Support/Docker\ Desktop/
  rm -rf ~/Library/Caches/com.docker.docker/
  rm -rf ~/Library/Cookies/com.docker.docker.binarycookies
  rm -rf ~/Library/Group\ Containers/group.com.docker/
  rm -rf ~/Library/Logs/Docker\ Desktop/
  rm -rf ~/Library/Preferences/com.docker.docker.plist
  rm -rf ~/Library/Preferences/com.electron.docker-frontend.plist
  rm -rf ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState/
  rm -rf ~/.docker/
```

macOS 12.0 Beta (21A5506j)
Apple Silicon
Docker Desktop 4.0.0 (67817) and Docker Desktop 3.6.0 (67351)

### Steps to reproduce the behavior

  1. Install Docker Desktop 4.0.0 on macOS Monterey Beta 6
  2. Attempt to start Docker Desktop

**Comment by michaelporemba** [comment]
+1 running on macOS Big Sur version 11.5.2 using a MacBook Pro 16,1 (Intel). Docker Desktop 4.0.0 hangs on "Docker Engine starting...".

**Comment by djs55** [comment]
@michaelporemba unfortunately without a diagnostics ID I can't tell whether you're suffering the same issue or not. Could you open a separate ticket and upload diagnostics (from the whale menu -> Troubleshoot -> Get Support -> Upload) and quote the ID on the other ticket? Thanks!

**Comment by shamelesscookie** [comment]
@djs55 thanks for the quick reply.

Based on your response, I tried the following:
- Completely removed Sophos
- Removed my VPN software (NordVPN)
- Disabled the macOS Firewall

I also tried telnetting into the associated port. This was only possible if I used my LAN IP rather than localhost or the 192.168.65.2 IP:

```bash
# Check which address Docker is trying to connect to
$ cat ~/Library/Containers/com.docker.docker/Data/log/vm/console.log | grep -i "unable to connect" | tail -n 1
time="2021-09-02T17:12:31Z" level=info msg="unable to connect to 192.168.65.2:64791 after 18m47.690927371s"

# See that Docker is listening on this port
$ lsof -Pnl +M -i4 | grep 64791
com.docke 50114      501   15u  IPv4 0x6c64427f37d61f29      0t0  TCP *:64791 (LISTEN)
vpnkit-br 50130      501    4u  IPv4 0x6c64427f37d61f29      0t0  TCP *:64791 (LISTEN)
vpnkit-br 50130      501    6u  IPv4 0x6c64427f37d61f29      0t0  TCP *:64791 (LISTEN)

# Attempt to telnet to this same interface/port unsuccessfully
$ telnet 192.168.65.2 64791
Trying 192.168.65.2...
telnet: connect to address 192.168.65.2: Operation timed out
telnet: Unable to connect to remote host

# Attempt to telnet to this same port on my LAN interface instead - SUCCESS!
$ telnet $(dig psymacbookair.lan +short) 64791
Trying 192.168.164.119...
Connected to psymacbookair.lan.
Escape character is '^]'.
```

**Comment by niloct** [comment]
Running Mac OS Catalina here, Intel Mac.

After today's upgrade to 4.0.0, I was experiencing this flickering starting/stopping docker when starting Docker Desktop too.

 I went to Docker Menu -> Troubleshoot -> Clean / Purge data, and this fixed it, although losing already built images.

**Comment by michaelporemba** [comment]
@djs55 problem is resolved after rebooting and deleting / reinstalling all built images. Now running on 4.0.0 on Intel MacBook Pro.

**Comment by shamelesscookie** [comment]
> @djs55 problem is resolved after rebooting and deleting / reinstalling all built images. Now running on 4.0.0 on Intel MacBook Pro.

Somehow this worked for me as well. It starts up normally:

```bash
$ lsof -Pnl +M -i4 | grep com.dock | grep LISTEN                                    
com.docke 1150      501   15u  IPv4 0x9482d235816ed16b      0t0  TCP *:49362 (LISTEN)

$ cat ~/Library/Containers/com.docker.docker/Data/log/vm/console.log | grep 49362 | grep connected
time="2021-09-02T22:28:40Z" level=info msg="connected to 192.168.65.2:49362"
```

**Comment by djs55** [comment]
@shamelesscookie I'm glad to hear it's resolved. I'll close the ticket but feel free to comment / open a new one if you have further problems.
