### ISSUE TITLE
ERROR docker-compose when run in v2

### ISSUE THREAD

**Issue by dleviathan** [docker/for-mac#5952]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
run docker-compose success
### Actual behavior
<img width="1289" alt="Screen Shot 2021-09-07 at 11 42 48" src="https://user-images.githubusercontent.com/1845897/132285569-70febf13-60e4-47bc-9fe8-0880a3965db0.png">
### Information

  - macOS Version: 11.5.2 (20G95)
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.0.0 (67817)

### Steps to reproduce the behavior

Repoduce Error:
  1. tick Use Docker Compose V2 release candidate 
  2. run docker-compose up -d --build
  3. => Error as image (Error response from daemon: no such image: xxx: invalid reference format)
  4. Only appear in special docker-compose file. (other work nomal)

Btw:
   1. untick Use Docker Compose V2 release candidate 
   2. run docker-compose up -d --build
   3. => Success
   4. Same docker-compose file has error above.

**Comment by MrMarci666** [comment]
I also have this issue, I just downgraded to 3.6.0
It is very funny that you update Docker, and then suddenly a working project won't work anymore... 👎

**Comment by samuelhorn** [comment]
Had the same problem.

@MrMarci666 as @dleviathan stated above, there's no need to downgrade. You just need to untick "Use Docker Compose V2 release candidate" under "Experimental Features" in settings.

I find it kind of strange that that one is ticked by default tho.
