### ISSUE TITLE
Desktop for mac doesn't seem to actually upgrade when I say 'yes'

### ISSUE THREAD

**Issue by jasonhemann** [docker/for-mac#5954]
- [ ] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3142C3E4-892A-4CF6-9EC3-74E81B5E0CE7/20210907161916

### Expected behavior
Expected to upgrade, doesn't actually.

### Actual behavior
I  just did get this message that Docker failed to do something; can't be _sure_ it's related but it gave me something to send to diagnose.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 3.5.2.18

### Steps to reproduce the behavior

  1. Open Docker Desktop
  2. See prompt to close and upgrade
  3. Click 'yes'
  4. (No upgrade appears to happen, docker continues as usual)
  5. Close Docker Desktop
  6. GOTO 1

**Comment by elwaxoro** [comment]
Seeing this also, menu always says "Update and Restart". Clicking restarts, but apparently does not upgrade

**Comment by anitauniwise** [comment]
Happening to me too.

MacOS version: 11.3.1
Docker Desktop version: 3.5.0

From the Docker Menu, I click "Update and restart". Docker restarts, but afterwards it is still version 3.5.0 and the menu still has the ! symbol, and it still says "Update and restart" instead of just "Restart".

**Comment by jimlongo56** [comment]
I'm having the same issue, I have Docker Desktop for Mac (Intel) v 3.6.0
OS 11.5.2

**Comment by xavipanda** [comment]
it's been happening for a few versions. I updated by hand... eventually, with this new upgrade.. again.. but the difference was that after 10 or 20 times to try it.. it finally updated. It is related by the download of the update itself.. update and restart doesnt produce any network I/O so doesn't seems to download anything.. so no download = no update.

**Comment by Altair-Bueno** [comment]
Same issue here. I tried to update like 4 or 5 times,  now i just gave up. I'll guess i just take a seat and wait

![image](https://user-images.githubusercontent.com/67512202/132924157-6dc21013-5479-4185-9730-419df050f83b.png)

**Comment by jimlongo56** [comment]
I gave up and went to [docker desktop download](https://www.docker.com/products/docker-desktop), download the update, install it.
Menu no longer displays the `Download update...` item.

**Comment by wkhatch** [comment]
Same issue here, but mine says "Download will start soon...", even several minutes after I'd Ok'd the update. This has happened on each upgrade for a while now.

**Comment by greenbicycle** [comment]
I have been having this problem for months. I can update by downloading and reinstalling Docker for Mac.

Macbook Pro Big Sur 11.6
Docker Desktop 4.01

**Comment by Altair-Bueno** [comment]
Probably the best option is to update using Homebrew instead

```bash
brew install --cask docker
```

**Comment by adamalton** [comment]
Same issue. The Docker menu has "Download update…". but clicking on it just brings up a dialogue box saying "Update in progress".

It's been in progress for days or weeks now. Big update?!

I've tried restarting my laptop, which makes no difference. And clicking "Update and restart" in the Docker menu just restarts Docker but doesn't update anything.

<img width="1271" alt="Screenshot 2021-12-21 at 13 07 13" src="https://user-images.githubusercontent.com/270255/146935357-cee07f30-3d0a-4b2f-bf93-3efb66ef5e9e.png">

<img width="1273" alt="Screenshot 2021-12-21 at 13 07 25" src="https://user-images.githubusercontent.com/270255/146935345-ca433f05-9d13-42a1-b1a0-528b11d85a91.png">

**Comment by code-n-go** [comment]
Same.  I've actually uninstalled Docker Desktop on MacOS and went with Podman due to this.  Tired of trying endlessly to get Docker to properly update.  How can something so trivial be broken this badly?

**Comment by mld** [comment]
Still happens with MacOS 12.1 / M1 / Docker Desktop 4.3.0. This is what they want people to pay for?
