### ISSUE TITLE
failed to run backend processes - docker: permission denied

### ISSUE THREAD

**Issue by ryan-blunden** [docker/for-mac#5956]
<img width="710" alt="Screen Shot 2021-09-09 at 6 03 47 pm" src="https://user-images.githubusercontent.com/133014/132647923-25bb22aa-fd11-4117-8da0-20c4e0d06c36.png">

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics (I wasn't able to upload any diagnostics)

  - Diagnostics ID:

### Expected behavior

Docker would start

### Actual behavior

Docker failed to start

### Information

  - macOS Version: 11.5.2 (20G95)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.0.0.0.12

https://user-images.githubusercontent.com/133014/132647558-005c5193-d2da-4d5f-91be-42313b10c14c.mp4

**Comment by xiazek** [comment]
I have exactly the same issue after I upgraded to Docker desktop 4.0. Also Installing 3.6 / restoring to factory defaults does not help.

**Comment by dirwin517** [comment]
if you `rm -rf .docker` folder and re-install atleast 3.5.2(tested), it works! not a great solution but alteast something till they fix it, I had to backup my config.json in my .docker folder and restore it after, hope that helps
