### ISSUE TITLE
Fatal Error on startup after update to v4.0.0 on Apple M1

### ISSUE THREAD

**Issue by nemoDreamer** [docker/for-mac#5957]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `B5AA3430-E853-45D6-A232-412E6044F6C4/20210909151657`

### Expected behavior

Starts up Docker Desktop after update to v4.0.0 on Apple M1.

### Actual behavior

**Fatal Error:** "Docker daemon failed to start"

```
2021-09-09T13:15:24Z dockerd time="2021-09-09T13:15:24.087305125Z" level=info msg="API listen on /run/guest-services/docker.sock"
```

### Information

  - macOS Version: Big Sur 11.4 (20F71)
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.0.0

### Steps to reproduce the behavior

  1. Updated Docker to v4.0.0
  2. Open Applications > Docker
  3. Fatal Error.

### Attempted solutions

  1. Tried "Factory Reset".
  2. Tried system restart.
  3. Tried re-install.

**Comment by xiazek** [comment]
I had the same issue as here. I've seen the same error as here, or the same one as here: https://github.com/docker/for-mac/issues/5956

**Comment by nemoDreamer** [comment]
I solved my issue by completely uninstalling Docker (I used MacPaw's "CleanMyMac X"), to get rid of any extensions and system stuff it might have installed.

I'm hesitant to close this issue, though, since Docker Desktop for Mac shouldn't have gotten itself in this situation in the first place, and this probably needs some looking into by the team.

**Comment by jvatic** [comment]
I also ran into this issue about an hour after hitting snooze when docker prompted me for an update (I never actually told it to update). I was unable to get a diagnostics ID or modify any preferences through the GUI. I then completely uninstalled Docker (I was sure to delete everything `com.docker` from `~/Library` and `/Library` using [broot](https://dystroy.org/broot/), and `~/.docker`), and re-installed it using `brew install --cask docker`. After rebooting my machine, docker is now starting as expected.

**Comment by delfuego** [comment]
I've now tried everything — up to and including completely eradicating all evidence of Docker and reinstalling — and I can't get past the immediate error "failed to startup backend processes".

I'm also on a M1 MBP, running Docker Desktop 4.0.0.

**Comment by delfuego** [comment]
Interestingly, I purged all evidence of Docker a second time and then rebooted, and 4.0.0 installed and appeared to run fine. But then I allowed it to upgrade to 4.0.1, and ended up again getting a daemon failure-to-start error. I've had the "Diagnose & Support" window open, ostensibly gathering diagnostics, for 45 minutes... it looks like it's not actually working.

**Comment by nemoDreamer** [comment]
@delfuego for the diagnostics, try the CLI route (the window hung for me too):
https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal

There's apparently also a way to uninstall from Terminal found on that page:

```bash
/Applications/Docker.app/Contents/MacOS/Docker --uninstall
```

**Comment by delfuego** [comment]
OK, so I tried downgrading to Docker 3.5.2, and it too fails to start with:

```2021-09-16T13:13:21Z dockerd time="2021-09-16T13:13:21.106054000Z" level=info msg="Loading containers: start."```

Using Docker Desktop to generate diagnostics fails, but doing it from the command line works; the diagnostics ID is ```ECAF9492-499B-4871-A2A5-CE0A63C82A07/20210916131431``` and they were uploaded.

I then used the command-line uninstaller to uninstall it, and then reinstalled Docker 4.0.0 (why is there not a 4.0.1 installer downloadable for Apple Silicon? 🤷🏻‍♂️). I ran that, and it succeeded in its first run; I was able to run the hello-world container, log into my Docker Hub account, etc. I was also able to quit and restart Docker 4.0.0 without issue.

I finally allowed Docker Desktop to update to the 4.0.1 release, and restarted — and it worked! So... I have no idea what happened, or how this worked this time.

I don't know if it's meaningful that I'm on an Apple Silicon (M1) MBP that was upgraded to macOS 11.6 three days ago — e.g., if this is a macOS 11.6 issue.

**Comment by rmelick-vida** [comment]
after reading the comment about pruning being helpful (https://github.com/docker/for-mac/issues/5963#issuecomment-919824700), I used the Clean/Purge data from the Troubleshooting menu, and that allowed the engine to start back up.

<img width="811" alt="Screen Shot 2021-09-16 at 7 54 15 AM" src="https://user-images.githubusercontent.com/31860121/133635189-20497a72-889d-4cbd-aac9-961fbbffb3e8.png">

Sad that I had to lose all the data in my volumes though
