### ISSUE TITLE
High CPU usage after update | Docker Desktop 4.0.0 (67817)

### ISSUE THREAD

**Issue by jeshen-appanna** [docker/for-mac#5963]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 645E0A8E-8C6B-4B48-8415-18170678BCFF/20210912195700

### Expected behavior
The process (com.docker.hyperkit) should operate normally without taking up too many resources and overheating MacBook Pro 2019.

### Actual behavior
com.docker.hyperkit - extremely high cpu usage after 4.0.0 (67817) update:
![image](https://user-images.githubusercontent.com/88713275/133001176-fcadd4b8-b911-40e7-b442-00dd2f5d8ff8.png)
MacBook Pro 2019 is overheating and fans are very noisy.
The problem persists after restarting MacBook Pro.

### Information

  - macOS Version: 11.5.2 (20G95)
  - Intel chip or Apple chip: 2,6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 4.0.0 (67817)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ferhatying** [comment]
I have the same issue on 4.0.1 (68347). `docker system prune -af` and a restart of Docker helps as a workaround.

**Comment by ddzobov** [comment]
#5905
