### ISSUE TITLE
No containers running

### ISSUE THREAD

**Issue by velkymx** [docker/for-mac#5966]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

My containers show correctly

### Actual behavior

The Containers/App is is empty and shows "No containers running"

### Information

  - macOS Version: 11.5.2
  - Intel chip or Apple chip: m1
  - Docker Desktop Version: 4.0.0

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by vita-vitamin** [comment]
did you get it resolved? I face same issues when I moved my dev lab to new macbook with chip M1 pro
