### ISSUE TITLE
Docker Desktop fails on MacOS 11.6

### ISSUE THREAD

**Issue by skaushikcov** [docker/for-mac#5970]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by periwinkleFTW** [comment]
Same issue, updating completely breaks docker. Asks to restore docker to factory defaults.

**Comment by kevinquillen** [comment]
Just received similar reports from two devs running Docker Desktop for Mac on Big Sur 11.6. On two seperate projects they reported:

```
Creating PROJECTNAME_memcached ... error
 rename) that container to be able to reuse that name.
ERROR: for PROJECTNAME_traefik  Cannot create container for service traefik: Conflict. The container name "/PROJECTNAME_traefik" is already in use by container "a364467a9fd4b5664b196b7c845a0e6798fc803d45517edd80095e4413b4fc0f". You have to remove (or rename) that container to be able to reuse that name.
Starting PROJECTNAME_node      ... done
```

Where PROJECTNAME is the project name.

They had to run this command several times before it would start successfully:

```
docker kill $(docker ps -q)
```

It is worth noting that these projects for these developers worked fine two weeks ago - and nothing about the project setup with Docker has changed. They both noted Docker Desktop app recently updated.

**Comment by kevinquillen** [comment]
Happening on another project for them now, and the docker kill command mentioned in the previous comment is not fixing it this time. I am at a loss as to why it is happening to these two devs, other than they have M1s. No one else has an issue.
