### ISSUE TITLE
--mount: `$HOME` works, `~ `does not

### ISSUE THREAD

**Issue by odyslam** [docker/for-mac#5976]
Interesting finding about `mounted volumes`.

```
--mount type=bind,source=$HOME/Library/Ethereum/keystore,target=/root/.ethereum/keystore
```

works as expected and I see the files from my dev machine inside the container `target` directory.
```
real=$(echo ~/Library/Ethereum/keystore)
 --mount type=bind,source={$real},target=/root/.ethereum/keystore
```

Does not work as expected. Although t**he bind mounts appear to be exactly the same**, I could not see the files of my dev machine inside the `target` directory of the container.  There is no visible difference in how the final `docker run` command is structured or mounted volumes as shown in Docker Desktop GUI.

**Comment by thaJeztah** [comment]
This is due to how the shell expands these, and also may depend on what shell you're using. Docker itself does not expand these variables or special characters, but the shell can expand some of them before the docker CLI receives them;

For example;

```bash
echo ~
/Users/sebastiaan
```

But

```bash
echo hello=~
hello=~
```

Environment variables are interpolated within strings;

```bash
echo hello=$HOME
hello=/Users/sebastiaan
```

Unless surrounded by single quotes;

```bash
echo 'hello=$HOME'
hello=$HOME

echo hello='$HOME'
hello=$HOME
```

**Comment by OdysLam** [comment]
The thing is that Docker Desktop showed in the GUI that both times the directories were mounted. In fact, they were as I could find them, only they were empty. 

The shell expansion happened before `docker run` and echoing the command before running it, printed the exact same result. 

Thanks for the thorough response @thaJeztah

**Comment by thaJeztah** [comment]
> The thing is that Docker Desktop showed in the GUI that both times the directories were mounted. In fact, they were as I could find them, only they were empty.

Hmm.. interesting. So one _possible_ explanation could be if a directory named _literally_ `~` existed somewhere. For example, the `-v <host-path>:<container-path>` shorthand will _create_ `<host-path>` (on the daemon side) if it doesn't exist. 

On Linux, `~` (or `$HOME` for that matter) are valid names for directories or files ;

```bash
docker run --rm alpine sh -c 'mkdir -p /foo/~ /foo/\$HOME && ls -l /foo'
total 8
drwxr-xr-x    2 root     root          4096 Sep 21 12:42 $HOME
drwxr-xr-x    2 root     root          4096 Sep 21 12:42 ~
```

The `--mount` long-hand option should produce an error if the `source=` path doesn't exist, but if (e.g. from previous runs), the path _does_ exist, it will mount it. In that case, the docker daemon could be bind-mounting an empty directory.

**Comment by OdysLam** [comment]
I used `--mount` and a `mac`.  [This](https://github.com/OdysLam/ddapptools/blob/0072073b8ee1753986780bf3ad02a2f57ca53c60/scripts/ddapp.sh#L22) is the line where I printed the volumes. In both times, they were printing the exact same thing. 

Thanks for the explanations, it was a very interesting dive into shell idiosyncracies. I use `zsh` btw.

**Comment by thaJeztah** [comment]
Hm... no idea TBH.

Doing a quick try where I try to use `~`, and that produces an error (which is expected, per the above)

```bash
docker run -d --mount type=bind,source=~/go/src/github.com/docker/docker,target=/root/.ethereum/keystore nginx:alpine
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '~/go/src/github.com/docker/docker' mount path must be absolute.
```

**Comment by OdysLam** [comment]
So, before the $HOME solution, I used the syntax as shown above:
```
real=$(echo ~/Library/Ethereum/keystore)
 --mount type=bind,source={$real},target=/root/.ethereum/keystore
```

With echo, I was able to print the absolute path.
