### ISSUE TITLE
Broken pipe error for Mac Pro

### ISSUE THREAD

**Issue by KingKoinBull** [docker/for-mac#5977]
This is my ticket number for an error message on when trying to start a SRX node
I am not sure if you need more information as I assume that the code below is reference.
Relatively new to the system and trying to figure out how to repair a broken pipe error that continues to show up when running in root on the bottom of the transcript.
<img width="944" alt="Screen Shot 2021-09-19 at 9 50 03 PM" src="https://user-images.githubusercontent.com/73433062/133970904-46dfc5ff-1a74-4947-bd17-469cde228f71.png">

This server is hosted by Contabo. If you have any questions or need help,
please don't hesitate to contact us at support@contabo.com.

Last login: Mon Sep 20 07:28:45 2021 from 66.91.217.199
root@vmi675255:~# sudo su -c "bash <(wget -qO- https://raw.githubusercontent.com/StorXNetwork/StorX-Node/main/bootstrap.sh)" root 
Please enter your XDC Address for StorX Rewards :- xdc14b1d9bc4d34ae50d9a00c4f1adf07b4223d2f28
Your XDC Wallet Address is xdc14b1d9bc4d34ae50d9a00c4f1adf07b4223d2f28
Installing Git      
Hit:1 http://asi-fs-n.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-n.contabo.net/ubuntu focal-updates InRelease           
Hit:3 http://asi-fs-n.contabo.net/ubuntu focal-backports InRelease         
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]  
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease
Fetched 114 kB in 5s (22.0 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20210119~20.04.1).
curl is already the newest version (7.68.0-1ubuntu2.7).
git is already the newest version (1:2.25.1-1ubuntu3.2).
software-properties-common is already the newest version (0.98.9.5).
apt-transport-https is already the newest version (2.0.6).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Clone StorX Node
fatal: destination path 'StorX-Node' already exists and is not an empty directory.
sed: can't read .env: No such file or directory
Installing Docker
OK
Hit:1 http://asi-fs-n.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-n.contabo.net/ubuntu focal-updates InRelease               
Hit:3 http://asi-fs-n.contabo.net/ubuntu focal-backports InRelease             
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                 
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Fetched 114 kB in 1s (161 kB/s)    
Reading package lists... Done
Hit:1 http://asi-fs-n.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-n.contabo.net/ubuntu focal-updates InRelease               
Hit:3 http://asi-fs-n.contabo.net/ubuntu focal-backports InRelease             
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                 
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Fetched 114 kB in 1s (191 kB/s)    
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker-ce is already the newest version (5:20.10.8~3-0~ubuntu-focal).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Installing Docker-Compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   633    0     0  28772      0 --:--:-- --:--:-- --:--:-- 28772
100 12.1M  100 12.1M    0     0  63.9M      0 --:--:-- --:--:-- --:--:-- 63.9M
Docker Compose Installed successfully
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-services.yml'
57AA822E-3A71-46C4-B894-4F927F5466FA/20210920072804

************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Mac software,
which we respond to on a best-effort basis.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without sufficient detail to debug them will be closed. They generally need
a clear title and description, steps to reproduce, and a diagnostics ID. See
https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback for
how to generate a diagnostics ID either from inside the app or from the command line.
************************************************************************************

-->

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by KingKoinBull** [comment]
Diagnostic code: 57AA822E-3A71-46C4-B894-4F927F5466FA/20210920072804

Expected Behavior: Repair error message. File not found and needs to connect and repair for communication
"ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-services.yml'"

Actual behavior: There is no response to complete node. 

Information:
Mac Os Version:11.5.2
Intel Chip 2.6 GHZ 6 -Core Intel Core i7
Docker Desktop version: 4.0.1

When running in root and logging in while the commands are running after sign in 
Then comes to an error code that shows up in red as shown in the picture above in this email chain under the Contabo heading.
[Error SRX.docx](https://github.com/docker/for-mac/files/7201489/Error.SRX.docx)

**Comment by stephen-turner** [comment]
It looks to me like there's a bug in Contabo's script, not a bug in Docker.

**Comment by KingKoinBull** [comment]
No such file or directory. 
File not found error
