### ISSUE TITLE
Docker engine not starting . docker indefinitely in starting state in mac book. 

### ISSUE THREAD

**Issue by jjijo** [docker/for-mac#5978]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 11.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.0.1 (68347)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jeffory-orrok** [comment]
I'm having the same issue with 4.2.0 also running on 11.3.1

**Comment by jeffkpayne** [comment]
I'm seeing the same behavior with 4.3.0.  The status stays in "Docker is starting".  I'm unable to open the preferences and none of the troubleshooting options (restart, purge, uninstall) have any effect.  I've tried uninstalling, deleting `~/.docker`, and installing again, but get the same results.  All I can do is quit Docker Desktop...

### Information
macOS Version: 10.15.7
Intel chip or Apple chip: Intel
Docker Desktop Version: 4.3.0 (71786)
Engine: 20.10.11
Compose: 1.29.2
Credential Helper: 0.6.4
Kubernetes: v1.22.4
Snyk: v1.563.0

**Comment by Exilon1** [comment]
I'm seeing the same issue with 4.3.0. It's an endless Docker Engine starting.

macOS Version: 11.6.1 (20G224)
CPU: 6-core Intel i7
Docker Desktop Version: 4.3.0 (71786)
Engine: 20.10.11

**Comment by bobaekang** [comment]
Just updated from 4.2.0 to 4.3.0 and now experiencing the same issue here.

macOS Version: 10.15.7
Intel chip or Apple chip: Intel
Docker Desktop Version: 4.3.0 (71786)

**Comment by sothawo** [comment]
just had the same problem with 4.3.0. Downloading and installing worked for me.

**Comment by navels** [comment]
Just ran into this upgrading from 4.2.0 to 4.3.0 on an M1 Pro.  Had to do an uninstall:

`/Applications/Docker.app/Contents/MacOS/Docker --uninstall`

and then installed 4.3.0 and startup worked after that.
