### ISSUE TITLE
Unable to run Docker commands on macOS Sierra

### ISSUE THREAD

**Issue by stewartmoreland** [docker/for-mac#598]
### Expected behavior
Running "$ docker ps" in Terminal should pull back list of running containers.

### Actual behavior
CLI / Kitematic are unable to connect to the Docker Engine.

### Information

Diagnostic ID: BE97FE34-52B3-4CFA-9847-F86D92C0A78C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/stewart/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/stewart/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/BE97FE34-52B3-4CFA-9847-F86D92C0A78C/20160912-161129/qemu-img-check.stdout 2> /tmp/BE97FE34-52B3-4CFA-9847-F86D92C0A78C/20160912-161129/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/stewart/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/stewart/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Start Docker in macOS 10.12
2. run $ docker ps

**Comment by mchiang0610** [comment]
We are still debugging and fixing macOS sierra related bugs.

Much of it should be fixed in beta 25 available here: https://download.docker.com/mac/beta/Docker.dmg if you are willing to try beta builds.

**Comment by stewartmoreland** [comment]
Fantastic! Thank you very much!

Stewart Moreland
Senior IT Systems Engineer
iHeartMedia IT
