### ISSUE TITLE
Docker steals focus repeatedly when it's starting

### ISSUE THREAD

**Issue by joe-westcott** [docker/for-mac#5986]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E39BF823-CD31-462A-8660-146990CE9A2E/20210928124851

### Expected behavior
When the Docker Engine is starting, it should not steal focus repeatedly, because this makes it impossible to get any work done when Docker is starting.

### Actual behavior
When the Docker Engine is starting, it steals focus repeatedly.

### Information

This problem is easily reproduced. It occurs every time that Docker starts up.

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel: 3.1 GHz Dual-Core Intel Core i5
  - Docker Desktop Version: 3.6.0.5487

### Steps to reproduce the behavior

  1. Start Docker.
  2. Try to do anything that doesn't involved Docker, and Docker will steal focus.

<img width="1274" alt="docker-engine-starting-steals-focus-repeatedly" src="https://user-images.githubusercontent.com/13838392/135090774-a6300339-4ede-4be1-9cbf-af5051a96cab.png">

**Comment by scottmmjackson** [comment]
Related: https://github.com/docker/for-mac/issues/5950

This is extremely frustrating behavior. It does not obey user preferences as to whether or not they want to be interrupted and shows extreme disrespect for the user's attention. Unless gaining focus is a core part of the functionality of an application (i.e.: a screen recorder application controller that needs to be focused as part of recording the screen) it should _never_ steal focus.

If docker needs the user's attention it should raise a native notification using the OS's toast functionality.
