### ISSUE TITLE
Performance issue with virtualization.framework on mac Intel

### ISSUE THREAD

**Issue by jmaitrehenry** [docker/for-mac#5987]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C09976A6-FEE4-4E64-9F0D-AFBDC99F0229/20210928140851

### Expected behavior
The performance should be the same or better when virtualization.framework is enabled

### Actual behavior
The performance are worst with virtualization.framework

### Information
  - macOS Version: 11.6 (20G165)
  - Intel chip or Apple chip: 2.6 GHz 6-Core Intel Core i7 
  - Docker Desktop Version: 4.0.1 (68347)

### Steps to reproduce the behavior
When I build ImageMagick with the imei script, without the virtualization.framework: `Process has been finished successfully after 7 minutes and 29 seconds!`

With the virtualization.framework: ` Process has been finished successfully after 56 minutes and 23 seconds!`

I have the same performance drop when I compile our Golang project or a nodejs project.

Dockerfile to build:
```
FROM golang:1.17-bullseye as build

# Add apt-fast because apt-get is so slow
COPY .docker/apt-fast.sh /tmp/bin/apt-fast.sh
RUN /tmp/bin/apt-fast.sh

# Install ImageMagick, ref: https://github.com/SoftCreatR/imei
COPY .docker/imei.sh /tmp/bin/imei.sh
RUN VERIFY_SIGNATURE=0 /tmp/bin/imei.sh
```

Files include in the build: https://gist.github.com/jmaitrehenry/03d8b9dcd68b0d46b8e659b4ccbc4f07

**Comment by stephen-turner** [comment]
We know that the new virtualization framework can be slower for certain workloads, and have documented it at https://docs.docker.com/desktop/mac/troubleshoot/#known-issues. That's why it's only experimental at the moment, and why we haven't switched from our own virtualization code to use Apple's.

**Comment by jmaitrehenry** [comment]
@stephen-turner Can I suggest 2 changes to help us to make the right decision about enabling or not the feature:
- In the experimental tabs in Docker Desktop, to add a link to the limitations/know issues of the visualization framework
- In the Know Issues page, for the disk I/O performance, the issue linked is about Apple Silicon, when I read it the first time, I was: it's not an issue for Mac Intel.

Thanks!
