### ISSUE TITLE
Docker mounts fail

### ISSUE THREAD

**Issue by mrogers-phd** [docker/for-mac#5988]
I'm in the process of developing a fairly large docker image that requires several container run-time volume mounts.  The idea is that users should be able to use their own set of local directories, pulled from git repositories.  It's been working just fine until today.

All day long it was working beautifully, but then I removed a directory and cloned a different one into the same area (same name, same directory structure, but different file versions).  Suddenly Docker was unable to mount that directory.  I tried everything I could think of, but nothing worked until I stopped and restarted the Docker Desktop app.

Now it's mounting that directory correctly again.  I suspect Docker is retaining some cached information about mounted volumes that needs to be cleared out when no containers are running with it.

**Comment by mbengit** [comment]
Sounds similar to this issue: https://github.com/docker/for-mac/issues/5604
