### ISSUE TITLE
Resetting kubernetes cluster does not free localhost ports bound to cluster-loadbalancer service.

### ISSUE THREAD

**Issue by gaurav517** [docker/for-mac#5989]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A

### Expected behavior
When kubernetes cluster is reset, host ports bound to loadbalancer service in cluster should be freed.

### Actual behavior
When kubernetes cluster is reset, host ports bound to loadbalancer service in cluster are not freed.

### Information
  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.0.1 (68347)

### Steps to reproduce the behavior
  1. Apply a loadbalancer service in kubernetes cluster (In my case, it was istio-ingressgateway)
     ```
     lsof -i | grep LISTEN | grep 74209    
     com.docke 74209 kgaurav2   14u  IPv6 0x8432552085921ddd      0t0  TCP *:15021 (LISTEN)
     com.docke 74209 kgaurav2   26u  IPv4 0x8432552087647ced      0t0  TCP localhost:sun-sr-https (LISTEN)
     com.docke 74209 kgaurav2   30u  IPv6 0x8432552085924edd      0t0  TCP *:http (LISTEN)
     com.docke 74209 kgaurav2   31u  IPv6 0x843255208592429d      0t0  TCP *:https (LISTEN)
     com.docke 74209 kgaurav2   32u  IPv6 0x84325520859223fd      0t0  TCP *:31400 (LISTEN)
     com.docke 74209 kgaurav2   33u  IPv6 0x8432552085922a1d      0t0  TCP *:15443 (LISTEN)
     ```
  2. Reset kubernetes cluster from docker desktop UI
  3. Ports on host are not free:
     ```
     lsof -i | grep LISTEN | grep 74209    
     com.docke 74209 kgaurav2   14u  IPv6 0x8432552085921ddd      0t0  TCP *:15021 (LISTEN)
     com.docke 74209 kgaurav2   26u  IPv4 0x8432552087647ced      0t0  TCP localhost:sun-sr-https (LISTEN)
     com.docke 74209 kgaurav2   30u  IPv6 0x8432552085924edd      0t0  TCP *:http (LISTEN)
     com.docke 74209 kgaurav2   31u  IPv6 0x843255208592429d      0t0  TCP *:https (LISTEN)
     com.docke 74209 kgaurav2   32u  IPv6 0x84325520859223fd      0t0  TCP *:31400 (LISTEN)
     com.docke 74209 kgaurav2   33u  IPv6 0x8432552085922a1d      0t0  TCP *:15443 (LISTEN)
     ```

**Comment by phil-mitchell** [comment]
Ooops, I see that I just opened #5991 which is probably a duplicate of this one.  I've provided more details.  Will let maintainers decide what to do.
