### ISSUE TITLE
Docker fails to start in OS X Sierra.

### ISSUE THREAD

**Issue by preston** [docker/for-mac#599]
### Steps to reproduce

1. Upgrade to Siera GM release
2. Trash existing Docker Data folder
3. Attempt to reset settings, which also fails

### Expected behavior

Docker should start in the toolbar.

### Actual behavior

Gets stuck in "Docker starting..." state. May or may not be related to #598 

### Information

```
Diagnostic ID: 846F5F23-433D-4105-BC96-8C227094E268
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!

**Comment by kamyar1979** [comment]
Thanks! Beta version works for me!
