### ISSUE TITLE
Memory setting does not limit resource usage

### ISSUE THREAD

**Issue by Pictor13** [docker/for-mac#5990]
Just reopening #3377 because it was closed automatically, not solved, not answered with actual insights; but the problem still exists.

### Docker Desktop for macOS doesn't respect the memory limit set via the Settings.

Debug details are also in the other ticket.
I'd add that on my mac the limit of max 5GB is **not respected**: at the moment **Hyperkit takes 8.17GB**.

----

### Expected behavior
![Screenshot 2021-09-29 at 17 32 01](https://user-images.githubusercontent.com/6748874/135301074-8ddc1d7c-f906-4365-9424-8cb8a290477a.png)

### Actual behavior
![Screenshot 2021-09-29 at 17 30 09](https://user-images.githubusercontent.com/6748874/135301054-53432dd5-bc9f-4fe3-bd6f-00b00ff3b144.png)

### Information
  - macOS Version: 10.14.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.1.7

**Comment by stephen-turner** [comment]
As explained in the ticket you referenced, this is a bug in MacOS. The Activity Monitor is double-counting the amount of memory in use by HyperKit: you are actually only using 4 GB. The other ticket has a link to a document with a full analysis.
