### ISSUE TITLE
Docker Desktop for Mac does not upgrade

### ISSUE THREAD

**Issue by secondorderpolynomial** [docker/for-mac#5994]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When I hit "Upgrade and Restart", Docker desktop should upgrade.

### Actual behavior
When I hit "Upgrade and Restart", Docker desktop looks like it's upgrading, but never does. It keeps showing the upgrade dialog even after that. The "Update and Restart" option shows an exclamation even after I restart Docker desktop.

### Information

  - macOS Version: 11.6 (Big Sur)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.6.0 (67351)

### Steps to reproduce the behavior
Not sure how to reproduce it, but attached screenshots

<img width="709" alt="Screen Shot 2021-09-30 at 8 45 12 AM" src="https://user-images.githubusercontent.com/4857389/135561462-f98e3ee5-45d6-40ab-9263-fabd00ca22e6.png">

<img width="265" alt="Screen Shot 2021-09-30 at 8 45 27 AM" src="https://user-images.githubusercontent.com/4857389/135561616-533fa15a-1f16-471b-84c2-aa4d01a6d23a.png">

<img width="264" alt="Screen Shot 2021-09-30 at 8 34 04 PM" src="https://user-images.githubusercontent.com/4857389/135561625-ffb4c473-f680-4137-b2f4-1b8ab30c52b2.png">

**Comment by mschneider** [comment]
same issue on my end, upgrade popup keeps popping up and selecting download and install does seem to have no effect. also "skip this update" can't be triggered, button seems disabled.

**Comment by joe0BAB** [comment]
Hello there, could you please upload the diagnostics following the steps here https://docs.docker.com/desktop/mac/troubleshoot/  ? Then, we can investigate further.

**Comment by secondorderpolynomial** [comment]
Sure, here's the diagnostics ID: `79A8FD50-E668-4FA1-8D24-5302789BEB9C/20211001124754`

**Comment by trungutt** [comment]
Could you please run this command and show us the result so that we could understand more about what's happening during the update

`/usr/bin/log show --debug --info --style syslog --last 7d | grep [Ss]parkle`

You can adjust the number of days after `--last 7d` to see if there's more log

**Comment by secondorderpolynomial** [comment]
Sure, attached: [syslog.txt](https://github.com/docker/for-mac/files/7286010/syslog.txt)

**Comment by clemf** [comment]
I had this problem and fixed it by simply manually quitting and starting the app. When it came back up it had the latest version.

**Comment by charlesnicholson** [comment]
Updating Docker through the UI has never functioned properly for me over the course of almost a full year now. I have only experienced one successful upgrade; the rest have required thrashing and blind hope: any number of manual restarts, repeated download clicks, guided restarts, etc.

Additionally, the lack of any explanation about what Docker is actually doing makes it hard to figure out what to try to do.

Is a download actually starting soon, as it says? How come when I quit and restart I'm magically on the new version that it purported to not yet have downloaded?

If I am shown both "download new version" and "restart and update" options in the menu, why do they both go away when I manually quit + re-launch Docker? Shouldn't only one go away?

Why is there no progress bar showing me how large the download is, and how much has been downloaded right now?
