### ISSUE TITLE
Incompatible CPU does not trigger GUI warning?

### ISSUE THREAD

**Issue by patatoid** [docker/for-mac#6]
### Information

Diagnostic ID: 9B084DE8-D300-4263-BEE1-3C0D6DB70A73
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.3 (Build 15D21)
[ERROR]  docker-cli
         wrong Docker version: 1.9.1 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/knothpascal/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/knothpascal/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/knothpascal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/9B084DE8-D300-4263-BEE1-3C0D6DB70A73/20160729-115839/qemu-img-check.stdout 2> /tmp/9B084DE8-D300-4263-BEE1-3C0D6DB70A73/20160729-115839/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/knothpascal/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/knothpascal/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/knothpascal/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/knothpascal/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/knothpascal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Can you please explain what your issue is, what you tried to do and what are the steps to reproduce. Closing this issue until we have more information.

btw, the `wrong Docker version: 1.9.1 (expected 1.12.0)` line seems to mean that you have toolbox installed and running. Please close toolbox (or uninstall it) and re-install Docker for Mac.

**Comment by patatoid** [comment]
First I dropped the img in Applications then just trying to launch docker !

**Comment by dsheets** [comment]
From `docker-system.log` in your issue report, I see

```
Jul 29 09:58:06 iMac-de-Administrateur Docker[com.docker.docker][36841] <Critic\
al>: Incompatible CPU detected.

        Docker requires a processor with virtualization capabilities.

        To learn more about this issue see:

        [https://docs.docker.com/docker-for-mac/troubleshoot](https://docs.dock\
er.com/docker-for-mac/troubleshoot/#incompatible-cpu-detected)
```

Was there a pop-up with this information in it? At the least, this seems like a GUI bug.

**Comment by patatoid** [comment]
yes I had the popup but I wonder if it is the case cause the diagnostic says "Virtualization: OK"

**Comment by dsheets** [comment]
Ok, I've opened an issue to make sure that our diagnostics correctly provide an error when your machine is missing required virtualization capabilities. Sorry, but you need a newer processor to use Docker for Mac. 😞

**Comment by patatoid** [comment]
np thx anyway :)
