### ISSUE TITLE
Unable to connect to docker Hub time out error and docker app keeps crahsing.

### ISSUE THREAD

**Issue by mukteshkrmishra** [docker/for-mac#600]
### Information

Diagnostic ID: C84B7F08-E95C-4924-9088-79BD23F10631
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/mukt/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/C84B7F08-E95C-4924-9088-79BD23F10631/20160912-163635/qemu-img-check.stdout 2> /tmp/C84B7F08-E95C-4924-9088-79BD23F10631/20160912-163635/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
seems related to #119

**Comment by mchiang0610** [comment]
Merging with #601
