### ISSUE TITLE
Containers unable to access host via 172.17.0.1 IP

### ISSUE THREAD

**Issue by Amwam** [docker/for-mac#6000]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Using the IP 172.17.0.1 inside a container should forward to the host

### Actual behavior

Instead getting a `Connection refused`

### Information

  - macOS Version: 11.6 (20G165) (Also tried with Catalina)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.0 (69386)
  - Using hypervisor.framework, have also tried the virtualization.framework, with no success

We also tried these same steps on Docker 4.0.1, and did not run into this issue.

### Steps to reproduce the behavior

in one terminal:

`python -m http.server 8000`

in another

`docker run --rm   curlimages/curl  http://172.17.0.1:8000`

In previous versions this returns a list of files (from the directory where the http server was run)
In 4.1.0, We're getting Connection Refused
Also trying the commands with `--net=host` or `--net=bridge` has no impact

Using `host.docker.internal` does seem to also work, however that isn't a portable solution with linux

**Comment by jforge** [comment]
I have suddenly the same issue.
Same Host spec, same version.
Also with 4.1.1

**Comment by istvandesign** [comment]
This still reproduces on Mac OS Monterey 12.1 with Docker 20.10.11 and Docker Desktop... I don't understand why this isn't a bigger issue, I've made Docker work with host.docker.internal on WSL and Linux, but this apparantly doesn't work on Mac, not even if I add 172.17.0.1 host.docker.internal to /etc/hosts. 

I will have to bite the bullet and go full Kubernetes, Docker is a mess.

**Comment by istvandesign** [comment]
This still reproduces on Mac OS Monterey 12.1 with Docker 20.10.11 and Docker Desktop... I don't understand why this isn't a bigger issue, I've made Docker work with host.docker.internal on WSL and Linux, but this apparantly doesn't work on Mac, not even if I add 172.17.0.1 host.docker.internal to /etc/hosts on the host.
