### ISSUE TITLE
Docker for Mac sets xattr com.docker.grpcfuse on SSH keys?

### ISSUE THREAD

**Issue by tdm4** [docker/for-mac#6002]
Coworker of mine has had this problem for 2 years now with Docker for Mac and I was only able to fix it today:

1. Brings up a docker environment
2. Exports SSH keys to said docker environment with this snippet in docker-compose.
```
volumes:
 - "~/.ssh:/root/.ssh:ro"
```
3. When running `docker exec -it ...` into the container to get a bash shell, he finds `/root/.ssh/id_rsa` is not owned by `root:root` but `501:dialout`
4. Closer examination of the file on Mac OS X shows it has extended attributes:
```
drwx------@  7  user         staff     224   6 Oct 21:30 .
drwxr-xr-x+   29 user        staff     928    7 Oct 14:38 ..
-rw-------@   1   user       staff    1766    6 Oct 11:45  id_rsa
```
5. Output from `ls -@ ~/.ssh/id_rsa`:
```
com.apple.quarantine: 0082;6042dcff;Sequel\x20Ace;
com.docker.grpcfuse.ownership: {“UID”:501,“GID”:20}
```
6. Removing the attribute for `com.docker.grpcfuse.ownership` with `xattr -d` resolves the issue. The container can use the SSH key to do things.

My question is: Does Docker for Mac set this xattr on `$HOME/.ssh` because `volumes:` in the docker-compose exports that directory? This doesn't seem to happen on all environments. (For example other coworkers also using docker for mac don't encounter this extended attribute thing at all!)

I thought I'd post this issue because over the past 2 years I've been searching for a resolution to this problem, and I found quite a few closed issues that were close to the problem even if they didn't quite describe it and I thought this would also help others who have been tearing their hair out trying to figure out why the files weren't owned by root.

Could the Docker for Mac devs kindly tell me when and where and under what circumstances this extended attribute gets set?

Thanks so much!

**Comment by thaJeztah** [comment]
Yes, when bind-mounting files from the host, docker desktop sets this attribute to store the linux ownership of files if the ownership of a file is modified within the container; this allows a file to be `chown`d inside a container, without changing the actual ownership of the file on macOS (as doing so would potentially prevent you from accessing the file on macOS)

**Comment by thaJeztah** [comment]
As far as I'm aware, yes, but let me double check with @djs55 if there's other conditions under which this may happen (wondering if it would do a chown to match an existing path in the container, so, e.g. if `/user/.ssh` inside the container already exists and has `501:20` as owner)
