### ISSUE TITLE
Apple M1, macOS Monterey - daemon failed to start (rare)

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#6003]
On
- Apple M1
- macOS Monterey
- Virtualization framework enabled

Docker occasionally fails to start and report "daemon failed to start".
This is a rare event.

`dockerd.log` reports an error that could be relevant: 
```
021-09-20T17:44:30Z dockerd time="2021-09-20T17:44:30.285645833Z" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
2021-09-20T17:44:30Z dockerd time="2021-09-20T17:44:30.285753583Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
2021-09-20T17:44:30Z dockerd time="2021-09-20T17:44:30.285659167Z" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
2021-09-20T17:44:30Z dockerd time="2021-09-20T17:44:30.285936667Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
2021-09-20T17:51:54Z dockerd time="2021-09-20T17:51:54.038988845Z" level=info msg="ignoring event" container=0db2a71e55b14a30a0da3db497310445be99b42c726c2ab38ebfd2d611413da1 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2021-09-20T17:51:55Z dockerd time="2021-09-20T17:51:55.071416387Z" level=info msg="ignoring event" container=69d821b2da7ec433dc6412be7a8b1f14bec5fab2bf104aa0ea2b80c895b3f4b5 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

From the system logs on the host side, there is nothing particularly suspicious. The virtual machine service started properly and was exited properly.
One interesting aspect is the host is under heavy load. If a function expect responses under a few milliseconds, I could totally imagine that slipping past the deadline due to scheduling.

Logs:
[vm 2.zip](https://github.com/docker/for-mac/files/7308014/vm.2.zip)

Docker version:
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by BenjaminPoulain** [comment]
Will do.

**Comment by BenjaminPoulain** [comment]
An engineer was able to reproduce the issue.

Here is the host's `Docker.log` of the last failure:
[Docker.log](https://github.com/docker/for-mac/files/7378390/Docker.log)

I have other logs if you need but I need to sanitize them one by one. Just tell me which files to add :)

**Comment by AMfalme** [comment]
Also facing the same issue at the moment. I have attached a file of my `~/Library/Containers/com.docker.docker/Data/log/host/Docker.log` 

Things have been working fine until I upgraded to MacOs Big Sur recently. Kindly let me know what I might be doing incorrectly, I'll appreciate any help. Thanks
[Uploading Docker.log…]()

**Comment by AMfalme** [comment]
> Also facing the same issue at the moment. I have attached a file of my `~/Library/Containers/com.docker.docker/Data/log/host/Docker.log`
> 
> Things have been working fine until I upgraded to MacOs Big Sur recently. Kindly let me know what I might be doing incorrectly, I'll appreciate any help. Thanks Uploading Docker.log…

Scratch that, just realised my issue was an installed virtual-machine -> *bluestacks* which must have been installed a while back without my knowledge. All good now.

**Comment by sarfarazansari** [comment]
below are the logs I got by running the command from terminal
`/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 4 issues:

1 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: connection refused

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The test: are the backend processes running?
    Failed with: 5 errors occurred:
	* com.docker.vpnkit is not running
	* com.docker.driver.amd64-linux is not running
	* com.docker.hyperkit is not running
	* com.docker.backend is not running
	* vpnkit-bridge is not running



Not all of the backend processes are running.

3 : The test: is the native API responding?
    Failed with: failed to ping tray application with error: Get "http://ipc/ping": dial unix Library/Containers/com.docker.docker/Data/backend.native.sock: connect: no such file or directory

The native API server is needed to start Docker engine.

4 : The test: is the VM networking working?
    Failed with: network checks failed: Post "http://ipc/check-network-connectivity": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: connection refused

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
