### ISSUE TITLE
LSMinimumSystemVersion broken

### ISSUE THREAD

**Issue by core-code** [docker/for-mac#6007]
you website claims that Docker needs 10.14

however your `Info.plist` file still allows launching it on 10.11, 10.12 and 10.13

```
  <key>LSMinimumSystemVersion</key>
    <string>10.11</string>
```

the technical requirements should be kept in-sync with the marketed requirements

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by core-code** [comment]
thanks!

**Comment by DiegoGiovany** [comment]
Still happening here, M1 Max with Ventura...
