### ISSUE TITLE
Images gone after moving them to external HDD + unable to start daemon

### ISSUE THREAD

**Issue by alternativebug** [docker/for-mac#6012]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I had the [hdp-sandbox](https://www.cloudera.com/downloads/hortonworks-sandbox/hdp.html) image locally on my macos Big Sur 11.6, docker desktop version 4.1.1 and it was working perfectly fine. I have limited disk space so I decided to move the images to external disk by following the steps in [documentation](https://docs.docker.com/desktop/mac/space/) as shown below. I was expecting to see the images in docker desktop after restart, which didn't happen. Additionally, the daemon stopped working, whenever I start docker desktop, it keeps starting and stopping simultaneously, and there is no indication of what's going wrong.

1. Select the Docker icon and then select Preferences > Resources > Advanced.
2. The Disk image size section contains a slider that allows you to change the maximum size of the disk image. Adjust the slider to set a lower limit.
3. Click Apply & Restart.

### Actual behavior

Docker desktop refuses to start and if it does, the images that used to be visible through the dashboard are gone. 

![Screen Recording 2021-10-17 at 11 23 52 AM](https://user-images.githubusercontent.com/58062537/137621065-380e6781-52ef-426c-b5a2-bbcb106e0184.gif)

### Information

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by schissmantics** [comment]
Here's a comment to unstale
