### ISSUE TITLE
Published ports without explicit IPv4 interface address broken within Docker VM if container is connected to a network with IPv4+IPv6 subnets

### ISSUE THREAD

**Issue by milas** [docker/for-mac#6015]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
* Published ports work as they did in Docker Desktop <= 4.0.1
* Published ports without an explicit interface work _within Docker VM_ even if container is also attached to a Docker network with an IPv6 (+ IPv4) subnet
* Can push to a local registry

### Actual behavior
* `docker push` to local registry request fails with error
   ```
   Get "http://localhost:57391/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
   ```

### Information
  - macOS Version:
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1 (69879)

### Steps to reproduce the behavior
1. Prepare an image to use for pushing
    ```
    docker pull hello-world && docker tag hello-world localhost:57391/hello-world
    ```
2. Create a local registry
    ```
    docker run -d --rm -p 57391:5000 --name test-registry registry:2
    ```
3. Push the image (works!)
    ```
    docker push localhost:57391/hello-world
    ```
4. Create a network and attach registry to it
    ```
    docker network create --ipv6 --subnet 172.22.0.0/16 --subnet fdd1:a66a:e649::/48 regissue
    docker network connect regissue test-registry
    docker push localhost:57391/hello-world
    ```
    Output:
    ```
    Using default tag: latest
    The push refers to repository [localhost:57391/hello-world]
    Get "http://localhost:57391/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    ```

It DOES look if the port is explicitly bound to IPv4, it continues working (i.e. `-p "0.0.0.0:57391:5000"` when creating container).

**Comment by milas** [comment]
I updated the issue slightly to be more precise.

If you have port forwards like:
```
0.0.0.0:57391->5000/tcp, :::57391->5000/tcp
```

While they still work from the host, they won't work from within the Docker VM, which breaks `docker push` for local registries.

This configuration appears if the port forward is established without an explicit IPv4 address AND the container is subsequently connected to a Docker network that has an IPv6 (+ IPv4) subnet.

If the forward is only on IPv4, e.g.
```
0.0.0.0:57391->5000/tcp
```
It still works from the host, and also from within the Docker VM, so `docker push` works as expected.

**Comment by bkrannich** [comment]
Apart from the workarounds mentioned, I was wondering if there's a fix for the root cause in one of the newer versions of Docker Desktop.
