### ISSUE TITLE
docker for mac failed

### ISSUE THREAD

**Issue by lightning-li** [docker/for-mac#602]
### Information

Diagnostic ID: 930D626C-F207-4AFE-BFD1-A9C97AEDAAFA
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/likang/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/930D626C-F207-4AFE-BFD1-A9C97AEDAAFA/20160913-161837/qemu-img-check.stdout 2> /tmp/930D626C-F207-4AFE-BFD1-A9C97AEDAAFA/20160913-161837/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/likang/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/likang/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/likang/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/likang/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/likang/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mchiang0610** [comment]
@lightning-li sorry about the problems you are having. Beta 26 - available here should have fixed most of the macOS sierra bugs: https://download.docker.com/mac/beta/Docker.dmg   

If you are uncomfortable using the beta, we will be updating the stable release soon. 

Thanks!
