### ISSUE TITLE
Kubernetes unable to pull images from configured credential store

### ISSUE THREAD

**Issue by MikaelSmith** [docker/for-mac#6021]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E10C7C83-696D-45D2-A690-C217A5217C37/20211026175645

### Expected behavior
After doing `gcloud auth configure-docker`, I'm able to `docker pull` images from a private Google Container Registry. I would expect for Kubelet to be able to pull them when trying to use containers in that registry with Kubernetes in Docker Desktop.

The same happens with private images on Docker Hub.

### Actual behavior
I get ImagePullBackOff and unable to authenticate trying to pull the images:
> Failed to pull image "gcr.io/my-project/my-private-image": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

This can be fixed by manually pulling those images with `docker pull`.

### Information
The `~/.docker/config.json` produced looks like
```
{
  "credsStore" : "desktop",
  "credHelpers" : {
    "us.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "marketplace.gcr.io" : "gcloud",
    "gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud"
  },
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  }
}
```

I thought this worked a long time ago, maybe with `docker-credential-gcr`. I found that there's [alpha support](https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/) in Kubelet for credential providers, but haven't found any way to successfully turn it on in Docker Desktop.

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.0 (69386)

### Steps to reproduce the behavior

  1. Enable Kubernetes in Docker Desktop
  2. Authenticate against a private registry that uses `credHelpers` or `docker login` to Docker Hub
  3. `kubectl run test --image=<image>` with a private image

**Comment by john-cooley** [comment]
Also having permissions problems with docker 4.1.1 on macOS Big Sur 11.6.  I've even tried to chmod the socket (var/run/docker.sock), but sudo privilege doesn't seem to cover.  How do I get around the need for root access to execute kubernetes build/deploy commands?
