### ISSUE TITLE
Unable to do docker search 4.1.1 (69879)

### ISSUE THREAD

**Issue by Tus1688** [docker/for-mac#6028]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A77B617F-FA65-4B25-90D0-FF3FBDBC1C23/20211103151113

### Expected behavior
Able to do `docker search <image name>`
### Actual behavior
`Error response from daemon: Unexpected status code 401`
### Information

  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.1.1 (69879)

### Steps to reproduce the behavior

  1. Updating to Docker Desktop 4.1.1 (69879)
  2.  Do `docker search <image name>`
  3. Get `Error response from daemon: Unexpected status code 401`
  4. I tried to pull `docker pull <image name>`
  5. It pulled successfully

**Comment by heeda88** [comment]
i guess maybe you are docker-login.
then this docker-login info need a "root auth " for searching private hub.

maybe working "sudo docker command".

you want not root-auth, then 
you should command "docker logout" 

I am also looking for a way to not use the root authority while logging in with a docker.

**Comment by zhudacai** [comment]
ok， while i logout, it is ok now

**Comment by dmasiero** [comment]
Same. 4.1.1 (69789) on M1. `docker search` works ok when logged out. When logged in, `Error response from daemon: Unexpected status code 401`

**Comment by Tus1688** [comment]
Issue has went away after upgrading to 4.2.0, thanks.

**Comment by heeda88** [comment]
> why need i logout ? it is not friendly to me

your login-info is in root-auth directory. 
Then you never load login-info when you don't use  sudo or root-user.
Finally, yon don't give  login-info  to docker API.
 The API give  to you that  
 **Error response from daemon: Unexpected status code 401**
 **Code 401  : Unauthorized**
