### ISSUE TITLE
Unable to perform apt-get update or install from debian container

### ISSUE THREAD

**Issue by kutenai** [docker/for-mac#6030]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E5F79D15-752C-4BB1-9A81-677C9C20CEBF/20211105134426

### Expected behavior
Container should be able to run apt-get update, also
From a container http and https requests should work

### Actual behavior

Is it reproducible? Yes, for me
Is the problem new? Yes
Did the problem appear with an update? No, it was present from older versions
macOS Version: 12.0.1
Intel chip or Apple chip: Apple M1 Max
Docker Desktop Version: 4.1.1

### Steps to reproduce the behavior

1. Start a debian based image docker run -it debian /bin/bash
2. Try to fetch package updates # apt-get update
```
(master) BoimbpMax:../proj/renesas/ww2-dev/ $ docker run -it debian /bin/bash
root@717fc1d16857:/# apt-get update
Err:1 http://deb.debian.org/debian bullseye InRelease
  Could not connect to deb.debian.org:80 (199.232.130.132), connection timed out
Err:2 http://security.debian.org/debian-security bullseye-security InRelease
  Could not connect to security.debian.org:80 (151.101.66.132), connection timed out Could not connect to security.debian.org:80 (151.101.194.132), connection timed out Could not connect to security.debian.org:80 (151.101.130.132), connection timed out Could not connect to security.debian.org:80 (151.101.2.132), connection timed out
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Could not connect to deb.debian.org:80 (199.232.166.132), connection timed out
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to deb.debian.org:80 (199.232.130.132), connection timed out
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Could not connect to security.debian.org:80 (151.101.66.132), connection timed out Could not connect to security.debian.org:80 (151.101.194.132), connection timed out Could not connect to security.debian.org:80 (151.101.130.132), connection timed out Could not connect to security.debian.org:80 (151.101.2.132), connection timed out
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Could not connect to deb.debian.org:80 (199.232.166.132), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@717fc1d16857:/#
```

### Other Notes
I saw a previous issue, #6027, and they suggested turning off "iCloud Private relay". I do not have this turned on, so it is not a solution in my case, and the problem persists.

I originally had this issue on a project specific docker file, but it was based on debian. I found that just the base debian image, as described here, reproduces the problem for me.

**Comment by deepj** [comment]
I have the same issue :( I've tried reinstall Docker but without any success. iCloud Private relay is disabled as well.

**Comment by deepj** [comment]
@lesterlo Thank you! Thank you! I can confirm disabling iCloud Private Relay in "Settings -> Apple ID" is needed. In case it was disabled only in Wi-Fi settings.

**Comment by fvalle1** [comment]
Casually passing by, I experienced the same on an Intel Mac running macOS 12.1 and Docker Desktop 4.3.1 (72247)

**Comment by adiggo** [comment]
I am running on 12.2 Beta, can't reproduce this

**Comment by ronaldmiranda** [comment]
I just have confirmed. disabling the private relay makes it work again. **THANKS <3**

**Comment by kaleynguyen** [comment]
I have a similar problem. 

#4 61.64 E: Unable to locate package freetds-dev
#4 61.64 E: Unable to locate package libkrb5-dev
#4 61.64 E: Unable to locate package libsasl2-dev
#4 61.64 E: Unable to locate package libssl-dev
#4 61.64 E: Unable to locate package libffi-dev
#4 61.64 E: Unable to locate package libpq-dev
#4 61.64 E: Unable to locate package git
#4 61.64 E: Unable to locate package freetds-bin
#4 61.64 E: Unable to locate package build-essential
#4 61.64 E: Unable to locate package default-libmysqlclient-dev
#4 61.64 E: Package 'apt-utils' has no installation candidate
#4 61.64 E: Unable to locate package curl
#4 61.64 E: Unable to locate package rsync
#4 61.64 E: Unable to locate package netcat
#4 61.64 E: Package 'locales' has no installation candidate

**Comment by skyjebus** [comment]
> I have the same issue. You need to turn off the iCloud private relay completely.
> 
> Turn OFF the iCloud private relay on the "Setting -> Apple ID" page rather than disabling it on the "Setting -> Network -> Wi-Fi"

This saved me after hours of no luck. Thanks!

**Comment by mikelane** [comment]
Well this thread saved what remains of the hair on my head.

**Comment by razvanbalosin** [comment]
In my case, on Apple M1, I've solved it by specifying the platform. Because the package list grabbed by the curl command references the `architecture of your system`, not everything might be available for Apple M1 (arm64). My current solution is to specify the platform in the first line of Dockerfile:
```
FROM --platform=linux/amd64 your-image-name
```
Alternatively, you can set the platform as en environment variable:
```
export DOCKER_DEFAULT_PLATFORM=linux/amd64  
```

**Comment by itzbernoulli** [comment]
Just got an M1 and @razvanbalosin's solution worked for me. I just used the export to set it as an environment variable.

**Comment by peter-gy** [comment]
Shoutout to @lesterlo; I experienced the same issue on an M1 mac and turning off private relay indeed did the trick. 🎉

**Comment by tylerjharden** [comment]
6 hours later and iCloud Private Relay (Beta) was the culprit. Thank you and goodnight. <3

Thank you @lesterlo

**Comment by MiguelFernandezCimp** [comment]
Icloud private relay was it for me !. Thanks @lesterlo

**Comment by michaldolnik** [comment]
Also helped me disabling Icloud private relay. Thanks many times, I have been struggling long time with this issue

**Comment by gjtorikian** [comment]
Wow. Thank you, so much!

**Comment by Pryanga** [comment]
I faced a similar issue recently in my MacBookPro15,2. I do not have icloud subscription hence the suggested fix did not work for me. What did work be the classic computer reboot.

**Comment by michaelschem** [comment]
A co-worker and I have had this issue, we both have M1s no one else has had this issue so trying @razvanbalosin 's solution. 🤞🏼

**Comment by f3l1x** [comment]
Ou my god! Works! Thanks!

> Turn OFF the iCloud private relay on the "Setting -> Apple ID" page rather than disabling it on the "Setting -> Network -> Wi-Fi"

**Comment by qwertywelch** [comment]
I was getting this issue on Delta in-flight WiFi. Funny enough, I was only able to get apt-get to resolve the debian repos by turning iCloud Relay _on_.

**Comment by mark-christiansen** [comment]
FYI, none of these solutions fully worked for me until I did a "docker system prune". I'm on MacOS w/ Intel.

**Comment by amjith** [comment]
Thank you for the `docker system prune`. That finally got me unblocked.

**Comment by hiveer** [comment]
This post is working for me, FYI:
https://sysopspro.com/how-to-fix-apt-404-not-found-error-on-debian-ubuntu/

**Comment by fireteam99** [comment]
FWIW i had the same issue when on my company VPN

**Comment by DeepSkyWonder** [comment]
I'm experiencing this issue, and none of the above solutions worked. I'm on an Intel Mac (i9 2019) running Monterey.iCloud Private Relay is disabled. I have run "docker system prune".

**Comment by talha-core** [comment]
Hello, I am getting the same issue but in WSL->Ubuntu->docker 

Is there a solution for it in this config ?

**Comment by meriem-mounchid** [comment]
myb bcs of iptables (false) , u need to change it to (true)
on /etc/docker/daemon.json:

```
{
    "iptables": true,
    "ip-masq": true,
    "ip-forward": false,
    "bridge": "docker0",
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "3"
    },
    "dns": ["8.8.8.8", "8.8.4.4"]
}
```

**Comment by talhaamir4130** [comment]
Set deb config to fetch packages via https and not with http.

This resolved the issue for me.

**Comment by valp124** [comment]
> Set deb config to fetch packages via https and not with http

How do you do that in `docker build`, @talhaamir4130 ?

**Comment by talha-core** [comment]
@valp124  I added like this: 
```
FROM php:8.2.7-apache

RUN a2enmod rewrite

# Force to use https for apt-get
RUN echo "deb https://deb.debian.org/debian/ stable main" > /etc/apt/sources.list
```

**Comment by talhaamir4130** [comment]
@valp124 Like this:
```
FROM php:8.2.7-apache

RUN a2enmod rewrite

# Force to use https for apt-get
RUN echo "deb https://deb.debian.org/debian/ stable main" > /etc/apt/sources.list

```

**Comment by PranavTerkar** [comment]
> FYI, none of these solutions fully worked for me until I did a "docker system prune". I'm on MacOS w/ Intel.
Thanks man, this worked at last
