### ISSUE TITLE
Docker compose automatic container naming on Sox and Linux ('_' vs. '-')

### ISSUE THREAD

**Issue by atomcat1978** [docker/for-mac#6035]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
`docker-compose up` should use same automatic naming conventions for service containers under Docker Desktop for Mac and on Linux docker versions.

### Actual behavior
On Linux Docker uses underscores (`_`), while on Docker Desktop for Mac dash (`-`) is used.

### Information

  - macOS Version: macOS 12.0.1 (21A559)
  - Intel chip or Apple chip: Intel chipset, 2,4 GHz 8-Core Intel Core i9
  - Docker Desktop Version: Docker Desktop 4.1.1 (69879)

### Steps to reproduce the behavior

  1. Run `docker-compose up` on linux.
  2. Run `docker-compose up` on Mac + Docker Desktop.
  3. Check the created container names (projectName-serviceName-1 (OSx) vs. projectName_serviceName_1 (linux))

**Comment by olegrusu** [comment]
We are having the same issue with our container names. Out of the dark, the container names changed from web_name_1 to web-name-1 after a rebuild and it broke a couple of scripts that actually rely on these old names. 

Are there any other solutions except for adding **container_name** to the docker-compose configuration? I know that once the **container_name** is added the containers itself cannot be scaled.

**Comment by ryan-benedetti** [comment]
I solved this issue on my local environment by turning off "Use Docker Compose v2" under Preferences > General.

**Comment by atomcat1978** [comment]
@ryan-benedetti Seems like it is turned off on in my environment, still get dashes in the names.

**Comment by thaJeztah** [comment]
Looks related to https://github.com/docker/compose/pull/8655. From that PR, it's possible to use the old names by using the `--compatiblity` flag
