### ISSUE TITLE
Docker tutorial fails in step 2

### ISSUE THREAD

**Issue by pat-flew** [docker/for-mac#6036]
- macOS Version: 11.6.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version:  4.2.0 (70708)

Fresh install. The tutorial UI fails in step 2 with

```
#11 0.401 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#11 0.767 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#11 1.172 ERROR: unable to select packages:
#11 1.211   python (no such package):
#11 1.211     required by: world[python]
```

Appears to be the same issue as described in https://github.com/docker/getting-started/issues/214#issue-1046293686. That failed for me in a similar way, and the resolution described in https://github.com/docker/getting-started/issues/214#issuecomment-962283923 fixed for me.

**Comment by NotYoCheese** [comment]
macOS 12.0.1
M1 Max CPU
Docker Desktop 4.2.0

Fresh install. 2 week old machine with all software fresh installed. Python is managed via pyenv.  I've found that if I edit the Dockerfile and remove everything below "# Run tests to validate app" I can see the pip installs running. This line always fails: "RUN apk add --no-cache python g++ make." I've also tried running outside of Docker desktop and I get the same result. Output below:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Michaels-MacBook-Pro:~ mike$ dev
bash: dev: command not found
Michaels-MacBook-Pro:~ mike$ cd dev
Michaels-MacBook-Pro:dev mike$ cd getting-started/
Michaels-MacBook-Pro:getting-started mike$ cd getting-started 
bash: cd: getting-started: No such file or directory
Michaels-MacBook-Pro:getting-started mike$  docker build -t docker101tutorial . 
[+] Building 1.6s (16/27)                                                                                                          
 => [internal] load build definition from Dockerfile                                                                          0.0s
 => => transferring dockerfile: 37B                                                                                           0.0s
 => [internal] load .dockerignore                                                                                             0.0s
 => => transferring context: 34B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                               0.9s
 => [internal] load metadata for docker.io/library/python:alpine                                                              0.8s
 => [internal] load metadata for docker.io/library/node:12-alpine                                                             0.8s
 => [auth] library/node:pull token for registry-1.docker.io                                                                   0.0s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                                  0.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                                 0.0s
 => CACHED [app-base 1/8] FROM docker.io/library/node:12-alpine@sha256:1ecf7789a48e604a841409e65cf2e172d5a014ecd5e60689137d7  0.0s
 => CACHED [stage-5 1/3] FROM docker.io/library/nginx:alpine@sha256:686aac2769fd6e7bab67663fd38750c135b72d993d0bb0a942ab02ef  0.0s
 => [internal] load build context                                                                                             0.0s
 => => transferring context: 7.70kB                                                                                           0.0s
 => [base 1/4] FROM docker.io/library/python:alpine@sha256:ab08dd9e48afe4cf629d993a41dccf0a74ae08f556b25cb143d8de37b25e1525   0.0s
 => ERROR [app-base 2/8] RUN apk add --no-cache python g++ make                                                               0.6s
 => CACHED [base 2/4] WORKDIR /app                                                                                            0.0s
 => CACHED [base 3/4] COPY requirements.txt .                                                                                 0.0s
 => CANCELED [base 4/4] RUN pip install -r requirements.txt                                                                   0.6s
------                                                                                                                             
 > [app-base 2/8] RUN apk add --no-cache python g++ make:                                                                          
#9 0.209 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz                                            
#9 0.464 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#9 0.607 ERROR: unable to select packages:
#9 0.623   python (no such package):
#9 0.623     required by: world[python]

**Comment by StefanScherer** [comment]
Thanks @pat-flew for reporting. We're working on a fix in the docker/getting-started repo.

**Comment by StefanScherer** [comment]
It is fixed now. If you want to rerun the tutorial you may need to do a cleanup step first.
```
docker rm repo
```
Then you can walk through the Getting Started Guide again and copy-paste the commands shown in the tutorial.
Please let me know how it worked!

**Comment by pat-flew** [comment]
Hey @StefanScherer, that's great - yes I've tried running through it again and that's fixed it 👍
