### ISSUE TITLE
Service does not come back to life after killing the service

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#6040]
With the current version of Docker Desktop (4.2.0 (70708)), if the `Docker` process dies, the service does not come back to life.

One way to reproduce is:
- Launch Docker Desktop and wait for the VM to be up.
- From command line, run `killall Docker`.
- The service goes away and the GUI is closed, as expected.
- Start Docker Desktop again.

-> The GUI starts but the client never comes back to life.

Here it is done manually but the same happens when the Docker process crashes.

It reproduces on Apple Silicon and Intel. It reproduces with any backend.
It is a regression from the previous version.

**Comment by fredericdalleau** [comment]
Hi @BenjaminPoulain,
From the steps you provided, we have not been able to reproduce the issue.
Could you upload a diagnostic ? Refer to : https://docs.docker.com/desktop/mac/troubleshoot/
There is also the possibility to diagnostic from the command line if the UI fails to start.
Thanks,
Frédéric

**Comment by BenjaminPoulain** [comment]
Richa Goel on our team tested this on the latest beta and collected the logs: [docker_log_during_hang.zip](https://github.com/docker/for-mac/files/8038311/docker_log_during_hang.zip)

It's interesting you cannot reproduce. It's fairly easy to reproduce for me. I wonder if some system settings are affecting this.

**Comment by fredericdalleau** [comment]
Hi @BenjaminPoulain, I'll give another try today ! Could it be similar to https://github.com/docker/for-mac/issues/6114?

**Comment by fredericdalleau** [comment]
@BenjaminPoulain I reinstalled a 4.2.0 70708 and tried with and without Virt FW. We'll dig into the logs. The diagnostic would also have contained the configuration files.
