### ISSUE TITLE
4.1.1 docker compose: error while interpolating services.<service>.mem_limit: failed to cast to expected type: strconv.ParseInt: parsing "4096m": invalid syntax

### ISSUE THREAD

**Issue by pwagland** [docker/for-mac#6041]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When setting `men_limit` in a compose file with a variable, using abbreviations (such as `4g`, or `4096m`) should work.

### Actual behavior
Docker Desktop 4.1.1 on Windows, and older versions on Mac work. 4.1.1 on Mac fails with the message:
```
error while interpolating services.<service>.mem_limit: failed to cast to expected type: strconv.ParseInt: parsing "4096m": invalid syntax
```

Setting the value using `MEM=4294967296` works, whereas `MEM=4g` or `MEM=4096m` fails.

### Information

  - macOS Version: 11.6.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1 (69879)

### Steps to reproduce the behavior
We have a mix-in `docker-compose.memory.yml`:
```yaml
version: '2.4'

services:
  service:
    mem_limit: ${MEM}
```

**Comment by Synehan** [comment]
Hi, got the same problem with memswap_limit and docker for mac v4.2
When disabling docker-compose v2, the problem disappears 
docker-compose v2.1.1 : KO
docker-compose v1.29.2 : OK

**Comment by Synehan** [comment]
Find the bug in docker-compose repository: https://github.com/docker/compose/issues/8772

**Comment by rherrick** [comment]
Same issue with `shm_size` in docker-compose. The following works with docker-compose v2.2.1:

```
shm_size: "256mb"
```

But this doesn't work:

```
# .env file
ENV_PG_SHM_SIZE=256mb
```

```
# docker-compose.yml
version: "3.7"

services:

  db:
    image: postgres:12-alpine
    shm_size: "${ENV_PG_SHM_SIZE}"
```

It fails with the error message:

```
error while interpolating services.xnat-vagrant-db.shm_size: failed to cast to expected type: strconv.ParseInt: parsing "256mb": invalid syntax
```

When I switch **Use Docker Compose V2** off in Docker Desktop, I get docker-compose v1.29.2 and either approach works.

Current version info is:

```
iMac (Retina 5K, 27-inch, 2017) on OS X 11.6.1
Version 4.3.2 (72729)
Engine: 20.10.11
Compose: v2.2.1
Credential Helper: 0.6.4
Kubernetes: v1.22.4
Snyk: v1.801.0
```

That said, it's been happening for a while. Not sure when it started.
