### ISSUE TITLE
Docker Build appears to be broken on the M1

### ISSUE THREAD

**Issue by jotkali** [docker/for-mac#6044]
I am new to Docker. I have installed the M1 version of the Docker, and also ran the command to install rosetta. I also have Xcode and tools installed

The flask app works, I can't get past the Docker part. I also tried installing the Intel version of Docker after trashing the M1 Docker app version, but it refuses to install. I ran docker and signed up

I am following AWS instructions to put a Flask app on AWS, on of the instructions is:
`docker build -t flask-container .`

If fails with this
`gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.8 -c src/greenlet/greenlet.c -o build/temp.linux-aarch64-3.8/src/greenlet/greenlet.o
#8 4.821     unable to execute 'gcc': No such file or directory
#8 4.821     error: command 'gcc' failed with exit status 1
#8 4.821     ----------------------------------------
#8 4.822 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rrusfjv1/greenlet_645f35db5a944b2ba9ce9262e2c171cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rrusfjv1/greenlet_645f35db5a944b2ba9ce9262e2c171cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ms7bxevt/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/greenlet Check the logs for full command output.
`

**Comment by rfay** [comment]
Just a quick look says this has nothing to do with `docker build` and everything to do with the compile failing on arm64 in your Dockerfile. I imagine there's something on arm64 that isn't working out in that Dockerfile. Remember that the toolchain is different, at least in some ways, on arm64, and you'll need to figure out what's going on. You'll probably want to manually run a similar docker image (Ubuntu 20.04 if the upstream is Ubuntu, for example) and walk through the Dockerfile instructions one at a time to figure out what's going on.

**Comment by StefanScherer** [comment]
Looks like the Dockerfile needs some adjustment to build on arm64. We can't help here, but had a similar looking issue with our getting-started guide in Node.js. The mysql package is prebuilt for Intel, but not for arm, so then a npm install suddenly requires gcc to be installed, so we added that to our Dockerfile.
For Flask I don't know, but it may be a similar issue that a requirement is rebuild for amd64, but not for arm64.
I'm going to close the issue as we can't really help with 3rd party Dockerfiles.
