### ISSUE TITLE
Desktop 4.2.0 gRPC inconsistency - truncated file in bind-mounted directory

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6045]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 165EF212-DB99-4FE1-90A4-E516A309B23F/20211113014450

### Expected behavior

Files bind-mounted via gRPC into a container should have the exact same content and size as files on the host.

### Actual behavior

On host:
```
$ ls -l /Users/rfay/workspace/eeamoreno/.ddev/.downloads/db.sql.gz
-rw-r--r--  1 rfay  staff  1404484 Nov 12 18:31 /Users/rfay/workspace/eeamoreno/.ddev/.downloads/db.sql.gz
```

In container:
```
$ ls -l $PWD/db.sql.gz
-rw-r--r-- 1 rfay dialout 1364076 Nov 12 20:05 /var/www/html/.ddev/.downloads/db.sql.gz
```

Note that the size is completely different (1404484 vs 1364076)

I have used `touch` to create other files in the same directory to make sure it's the same mounted directory, not some artifact.

This is mounted via docker-compose with
```yaml
    - type: bind
      source: ../
      target: /var/www/html
      consistency: cached
```

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.2.0

### Notes

* This directory is mounted into two places inside the container. One of the mounts is the parent directory (which is how we get what we're looking at here. The directory is also mounted read-only to another mount-point inside the container. 
* Restarting the ddev/docker-compose project (down and then up, containers destroyed and then recreated) results in a correct mount. 
* Recreating the db.sql.gz on the host in the same way it was earlier recreated (after project restart) seems to result in a successful, non-truncated mount.
* This is so very scary because we assume consistency from gRPC all the time... and have always had it. What's up here? 
* I almost gave up on the "Diagnose" in the GUI. It took SO LONG! I don't remember it taking that long before. I was going to file a bug saying it was broken. Maybe it needs some kind of progress meter.

**Comment by StefanScherer** [comment]
Thanks for the report. We're looking at it, but maybe the new virtio-fs experimental feature could also solve this issue.

One reason that the diagnostics took so long to generate is that there are a lot and huge log files. Maybe you could clean up `~/Library/Containers/com.docker.docker/Data/log/` and restart DD. Then it starts with fresh log files until you send us a new diagnostic.

**Comment by rfay** [comment]
Thanks, removed those logs.

It's not looking like virtio-fs will be an option any time soon, judging from what I see go by. Looks SO experimental and with so many byproducts. Thanks for looking into this. It was really scary.

**Comment by ebriney** [comment]
@rfay  I can't reproduce it with my M1 machine. How did you create this file. I tried something like:
```
busybox:
/ # tar -zc -f /dl/bin.tgz /bin
tar: removing leading '/' from member names
/ # ls -la /dl/bin.tgz
-rw-r--r--    1 root     root        796293 Nov 26 11:33 /dl/bin.tgz
/ #

M1:
ls -la ~/Downloads/bin.tgz
-rw-r--r--  1 e***y  staff  796293 Nov 26 12:33 /Users/e***y/Downloads/bin.tgz
```

**Comment by rfay** [comment]
Thanks @ebriney - I didn't expect it to be easily reproducible, was hoping that the diagnostics would give some clue. I really appreciate you taking a look.

* this was easily fixed by restarting the docker-compose (ddev) project, so wouldn't expect it to just happen again on the same file
* No operations were going on with this file. It was not in use
* I waited a long time, studied the results, looked at it both inside the container and on the host. But bind-mount has always been instantaneous from the user's perspective...
* The directory bind-mount was still working fine (new files created in the directory appeared properly)

**Comment by ebriney** [comment]
Ok, I understand better, the file is destroyed and recreated multiple times because It's in a test suite.
How do you trigger your `ls` in the container because from what I see in the logs:
```
01:31:55       => CREATE event
01:31:55.16  => ls
01:31:57       => MODIFY event
```
that mean you are doing `ls` too early while the db is being filled and is growing if you read it after the MODIFY event you'll get the right size because we invalidate the attrib cache

**Comment by rfay** [comment]
Of course, that `ls` has been in there forever and ever as part of this test and there has never been an issue like this before (and I wouldn't expect it ever).

The `ls` is there because as I mentioned, the `.ddev` directory is mounted two ways. It's bind-mounted and also NFS-mounted (in this case). NFS has a habit of getting stale mounts, which can be refreshed with an `ls`. 

The `ls` is completed before this file even gets created though.

What is likely going on is this sequence here: https://github.com/drud/ddev/blob/e851b23842ad751f6f096e0d8a3532ce0c17db20/pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example#L53-L59

**Comment by dimaqq** [comment]
I wonder if gRPC has some... packet limits or something... b/c very large directories can't be listed either: https://github.com/docker/for-mac/issues/5219

**Comment by rfay** [comment]
In this case, this was a very modest-sized file in an empty directory, and docker and I have loads of experience with predictable gRPC mounts since gRPC was first introduced. I'm worried that this is a regression.

**Comment by ebriney** [comment]
I'll check your issue @dimaqq 
For @rfay one, I think there are two things:
 - we have an issue with Monterey that exhibit high CPU usage (for now we only seen it on Intel with Apple virtualization framework but I saw in your diags that CPU is nearly fully load, that can explain why it takes 2s to write the file)
```
rfay              3327 342.6  4.5 415773792 754160   ??  R     6:59PM 1024:07.51 /Applications/Docker.app/Contents/MacOS/qemu-system-aarch64 -accel hvf -cpu host -machine virt,highmem=off -m 6144 -smp 6 -kernel /Applications/Docker.app/Contents/Resources/linuxkit/kernel -append page_poison=1 vsyscall=emulate panic=1 nospec_store_bypass_disable noibrs noibpb no_stf_barrier mitigations=off   vpnkit.connect=tcp+bootstrap+client://192.168.65.2:65048/4b5cb95f4470c27702947772fffa8acb2341f75d03c86224b4f3791776cb31cd console=ttyAMA0 -initrd /Applications/Docker.app/Contents/Resources/linuxkit/initrd.img -serial pipe:/var/folders/3k/0159p4ld73jfbct7ykph9w340000gn/T/qemu-console690874275/fifo -drive if=none,file=/Users/rfay/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw,format=raw,id=hd0 -device virtio-blk-pci,drive=hd0,serial=dummyserial -netdev socket,id=net1,fd=3 -device virtio-net-device,netdev=net1,mac=02:50:00:00:00:01 -vga none -nographic -monitor none
```
 - the test itself has a race because he doesn't wait for db transactions to finish, writes in gprcfuse are synchronous

**Comment by ebriney** [comment]
Interesting. That means the attribute cache is not correctly invalidated.
We invalidate it watching filesystem event on the host.
I didn't see any logs that show we have dropped some events in the diag.
As an easy fix we can probably reduce the TTL of this cache, it's set to 3600s for now!
I check if I don't find anything else.

**Comment by rfay** [comment]
Yeah, I was able to just sit there and look at it for many minutes. It didn't ever get fixed.

**Comment by ebriney** [comment]
Hello @rfay 
Can you send me instructions/link to run the tests that triggered this error?
I want to check if it's happen only on Monterey.
Or at least if I can reproduce it on my M1, it will be easier to debug it.

**Comment by rfay** [comment]
This was running a `ddev pull`, essentially all it did was download the db.sql.gz (on the host side) into .ddev/.downloads. It then hit the error of not being able to gunzip it (inside the container) because of the invalid contents. I haven't seen it since, and am not hopeful about reproducing it on demand. I don't remember another case of a docker bind-mounted file being inconsistent (and remaining inconsistent) so was obviously alarmed and spent time trying to get all the possible info.

**Comment by WhiteDragon29** [comment]
> Hello @rfay Can you send me instructions/link to run the tests that triggered this error? I want to check if it's happen only on Monterey. Or at least if I can reproduce it on my M1, it will be easier to debug it.


V2.5.0 - v4.3.0 This desktop is out of sync with the contents in the container and it's always a problem with two macbook and switching from inter to m1. I really suspect I bought a fake macbook.....

**Comment by WhiteDragon29** [comment]
> Hello @rfay Can you send me instructions/link to run the tests that triggered this error? I want to check if it's happen only on Monterey. Or at least if I can reproduce it on my M1, it will be easier to debug it.

Yesterday, I tried to close 'grpc fuse for file sharing' according to [5046](https://github.com/docker/for-mac/issues/5046), resulting in my docker being unable to start for a long time. The final solution is to reinstall.. the file is not synchronized, which also affects my work efficiency

**Comment by ebriney** [comment]
I tried to reproduce the bug @rfay using a pantheon setup but never get it.
I created a ticket to add some logs, so we can at least better diagnose the problem if you get it again.
The TTL reducing is a bad option because you lose all the advantage of the attrib cache and so it's like disabling it.
@WhiteDragon29 I don't understand your problem, perhaps create a separate proper issue with your setup + some diagnostics...

**Comment by rfay** [comment]
I agree this is too hard to chase right now, and I've never-ever seen anything like this before. Just so scary it was important to study. Thanks for taking the time to study it.

**Comment by WhiteDragon29** [comment]
> I tried to reproduce the bug @rfay using a pantheon setup but never get it. I created a ticket to add some logs, so we can at least better diagnose the problem if you get it again. The TTL reducing is a bad option because you lose all the advantage of the attrib cache and so it's like disabling it. @WhiteDragon29 I don't understand your problem, perhaps create a separate proper issue with your setup + some diagnostics...

This is my problem. Please help me
https://github.com/docker/for-mac/issues/6115
