### ISSUE TITLE
cpuinfo poorly emulated on M1 Macs

### ISSUE THREAD

**Issue by clemens-holleis** [docker/for-mac#6047]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics

I tried to start Blender inside an amd docker container, emulated on M1 Mac, running noVNC to access the the GUI via Chrome.
From Blender versions 2.8 and higher I get the following error message:

``` 
 ArchError: Could not find 'cpu MHz' in /proc/cpuinfo
  Function: Arch_InitTickTimer
      File: /home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/build/usd/src/external_usd/pxr/base/arch/timing.cpp
      Line: 133
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```
I posted the problem to [Blender here](https://developer.blender.org/T92956) and the issue seems to be the emulation of the container, not Blender.

## What I found out so far

- The `/proc/cpuinfo` file looks quite different on x86 and ARM machines – among other things ARM seems not to provide a `cpu MHz` information
- Inside the container the `/proc/cpuinfo` reflects the host system not the emulated system inside the container – to verify this theory I tried:
    - Running different Linux x86_64 versions on M1 to check that this behavior is not unique to one distro
    - Running emulated aarch64 Alpine on Intel Windows machine to exclude the possibility  of a Mac-only issue with **qemu** ==> Inside the ARM emulation  on Windows `arch` says `aarch64` but the in neofetch the CPU says `Intel i7` and the `/proc/cpuinfo` is also x86 like

Blender (or rather the [Pixar USD library](https://github.com/PixarAnimationStudios/USD) inside Blender... see [comments](https://developer.blender.org/T92956)) needs the `cpuMHz` not provided by the emulated system properly, and therefore most likely other projects using this lib as well.

> It would be great if you could fix the `/proc/cpuinfo` to match the emulated system architecture rather than the host system architecture. On the [original bug report](https://developer.blender.org/T92956) I also provided a zip file with the docker setup I used.

### Information

  - macOS Version: macOS 11.5.1 20G80 arm64
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.2.0 (70708)

### Steps to reproduce the behavior

1. **Do this on M1 Mac**
2. Download the zip from this [post](https://developer.blender.org/T92956) and extract it
3. In a terminal go to the unzipped folder
4. run `source build-and-launch.sh` to build the image and spin up a container
5. open a browser and go to http://localhost:6901
6. login using password pass
7. see the README.txt on the Desktop you just logged into
8. ==> Follow the README instructions <==

**Comment by arjantop-cai** [comment]
Same issue when running cadvisor images, arch detected as amd64 but no MHz/GHz info is in the `cpuinfo`

**Comment by StefanScherer** [comment]
Thanks for the report. We rely on `QEMU` on a best effort basis.
Maybe it's better to try to use an arm64 base image and put a linux/arm64 version of Blender into an image?
I don't know that project and whether they provide linux/arm64 builds. But in general if problems arise this would be the next best option to avoid emulation at all.

**Comment by clemens-holleis** [comment]
Thank you for the reply. Emulation is currently necessary for two reasons. First the ARM versions of Blender are far behind the latest (besides the one for Mac M1). Second the container should be hosted in the cloud on x86.
I posted the issue to QEMU [here](https://gitlab.com/qemu-project/qemu/-/issues/750).

**Comment by marcelbeumer** [comment]
Also have this issue when running cadvisor images

**Comment by marcelbeumer** [comment]
I don't mean to be rude, but I'd hope to see Docker Desktop taking more ownership of this issue as QEMU is an implementation detail of a now commercial product?
