### ISSUE TITLE
Error invoking remote method 'desktop-go-backend': Error: {"message":"no such file or directory"}

### ISSUE THREAD

**Issue by tmulle** [docker/for-mac#6048]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Should be able to specify a location on a USB drive as I've done many times before.

### Actual behavior
Getting this error when trying to use a **Docker.raw** file from a USB drive.
I've done this in the past with no issues on my Intel Mac using the Docker Desktop GUI and specifying my USB drive to store the file one.

<img width="1272" alt="Screen Shot 2021-11-15 at 11 26 02 AM" src="https://user-images.githubusercontent.com/5183186/141819139-ebcdcd3a-4c67-4c4d-aa1d-0ed034ffa56c.png">

I've tried both the Docker.raw file that was created by the Docker install and moving it to my USB drive as well as creating an empty directory on the USB drive to let docker try to create it but all attempts give the same error.

When I try to ignore the error and try to restart Docker, the process just hangs and I have to restore to factory defaults.

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple Silicon M1 MAX
 <img width="583" alt="Screen Shot 2021-11-15 at 11 26 51 AM" src="https://user-images.githubusercontent.com/5183186/141819266-732aafb8-37a5-4870-bdcf-7574d48218a6.png">

  - Docker Desktop Version:
<img width="872" alt="Screen Shot 2021-11-15 at 11 26 10 AM" src="https://user-images.githubusercontent.com/5183186/141819420-418a3365-df84-4b76-8b94-7c96717a895f.png">

Docker: 4.2.0 (70708)
Engine: 20.10.10
Compose: 1.29.2
Kubernetes: v1.21.5

This is my docker version from the command line:
```
~ docker version
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
### Steps to reproduce the behavior
Trying to use the Resources tab in the GUI to specify the location of my Docker.raw file

**Comment by bralandealmeida** [comment]
same here

**Comment by GBaileyMcEwan** [comment]
Same for me!

**Comment by taherelhossin** [comment]
Does any body find any solution ?

**Comment by StefanScherer** [comment]
Thanks for the report. I can reproduce the issue. I copied the Docker.raw to a different folder on my internal drive, then tried to select this folder. I also saw the red error message. But when I pressed `Apply & Restart` Docker Desktop changed the setting, when I opened it again I saw it appended `DockerDesktop` below my test folder and created this subfolder and a new Docker.raw in it.
Does that work for you when you create a `DockerDesktop` subfolder?
Maybe Docker Desktop always appends this subfolder, I have to check with the engineers.

**Comment by GBaileyMcEwan** [comment]
> Thanks for the report. I can reproduce the issue. I copied the Docker.raw to a different folder on my internal drive, then tried to select this folder. I also saw the red error message. But when I pressed `Apply & Restart` Docker Desktop changed the setting, when I opened it again I saw it appended `DockerDesktop` below my test folder and created this subfolder and a new Docker.raw in it. Does that work for you when you create a `DockerDesktop` subfolder? Maybe Docker Desktop always appends this subfolder, I have to check with the engineers.

If I try this (manually create a DockerDesktop folder and put the Docker.raw file inside it), I get an error:

Invalid path
/Users/[myusername]/Downloads/DockerDesktop already exists.

Please remove it and retry.

**Comment by ytingone** [comment]
Same here
intel i7 with macos 11.6.1

**Comment by rhzs** [comment]
Same here, can someone help? Running on MacOS 11.5.2.. Why is each release getting worst? This is a basic feature.

**Comment by vncsalencar** [comment]
+1 on Intel macOS Monterey 12.0.1
And I've tried two Docker Desktop versions (4.2.0 and 4.1.1) to no avail

**Comment by GBaileyMcEwan** [comment]
> Thanks for the report. I can reproduce the issue. I copied the Docker.raw to a different folder on my internal drive, then tried to select this folder. I also saw the red error message. But when I pressed `Apply & Restart` Docker Desktop changed the setting, when I opened it again I saw it appended `DockerDesktop` below my test folder and created this subfolder and a new Docker.raw in it.
> 
> Does that work for you when you create a `DockerDesktop` subfolder?
> 
> Maybe Docker Desktop always appends this subfolder, I have to check with the engineers.
> 
> 

Any feedback from the engineers yet? Holding thumbs!

**Comment by tmulle** [comment]
I still get this error on the latest 4.3 build of Docker Desktop just released..

Any word on a workaround or fix? I’d like to have my images on my USB drive like I did before.

**Comment by blue928** [comment]
I agree this should be priority. Macbook users quickly run out of space with Docker Desktop enabled. Are there any workarounds yet? maybe reinstall it and specify the directory before the app installs?

**Comment by JNSFilipe** [comment]
Is there any update on this? I've been experiencing the same issue

**Comment by ghost3343** [comment]
I have a solution for this. After the main installation and the change of the disk image location, ignore the error and set the disk image size to your needs,  in direct correlation with the space of your external drive. That work's for me and i have an Intel macOS Monterey 12.1.

**Comment by GBaileyMcEwan** [comment]
> I have a solution for this. After the main installation and the change of the disk image location, ignore the error and set the disk image size to your needs, in direct correlation with the space of your external drive. That work's for me and i have an Intel macOS Monterey 12.1.

Tried this on Apple M1 but no luck unfortunately - I can't get it to work.

**Comment by manlm** [comment]
> I have a solution for this. After the main installation and the change of the disk image location, ignore the error and set the disk image size to your needs, in direct correlation with the space of your external drive. That work's for me and i have an Intel macOS Monterey 12.1.

This works for me, thank you!

**Comment by GBaileyMcEwan** [comment]
> > I have a solution for this. After the main installation and the change of the disk image location, ignore the error and set the disk image size to your needs, in direct correlation with the space of your external drive. That work's for me and i have an Intel macOS Monterey 12.1.
> 
> This works for me, thank you! I'm using Apple M1 pro.

@manlm @ghost3343  Can you be a bit more specific on how you got this to work please?  I have a volume mounted which is empty and is around 45GB (see picture).  When I select this volume, the largest size I can set for some reason is 28.2GB in DockerDesktop.  I am assuming you meant we should set this to the exact size of the disk, but there is no way to do this on the sliding scale.  Am I missing something?  Appreciate your help!
![Uploading image.png…]()

**Comment by heshiming** [comment]
I couldn't get @ghost3343 's procedure to work. But mine is not far from it:

1. Set the location of the image to the new folder, this is where you receive this error for the first time.
2. Click "Apply & Restart" and see this error for the second time. I discovered that Docker Desktop will first create the "DockerDesktop" folder on the new location, copy things over, then delete it. At this point, the "location" in the preference appears to be the new location, but it won't survive a restart.
3. Drag the "Disk image size" slider to change it a bit. Larger or small shouldn't matter. And click "Apply & Restart". This time there will be no error, and you'll see "DockerDesktop" popping up in the new location, and being deleted in the old one.

Be aware, original contents in the image might get destroyed.

**Comment by alipman88** [comment]
This issue flummoxed me for a couple days, but eventually I found that instead of changing the "disk image location" setting, I could manually move the `Docker.raw` file and create a symlink:

```bash
mv /Users/aaron/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw /Volumes/T7/Docker.raw
ln -s /Volumes/T7/Docker.raw /Users/aaron/Library/Containers/com.docker.docker/Data/vms/0/data
```

**Comment by askareija** [comment]
I'm stuck in here, loading forever.
![Jepretan Layar 2022-02-22 pukul 10 29 52](https://user-images.githubusercontent.com/21377617/155058064-4e63aecc-5a25-45af-85e7-93f1c01ba59f.png)

but the image is created, weird.
![Jepretan Layar 2022-02-22 pukul 10 30 01](https://user-images.githubusercontent.com/21377617/155058188-87759b53-be97-4f89-9510-5294fd2a559a.png)

I'm using Mac M1 Air Monterey 12.1

**Comment by KnownAsMomoVV** [comment]
@askareija 

+1 same here i cant even run my Diagonstics

![image](https://user-images.githubusercontent.com/74142294/155107208-1d473aec-6dde-4836-b8aa-b4e91a20ae51.png)

OS : Windows 11

Edition	Windows 11 Pro
Version	21H2
Installiert am	‎31.‎01.‎2022
Betriebssystembuild	22000.493
Leistung	Windows Feature Experience Pack 1000.22000.493.0

**Comment by zeusongit** [comment]
Any solution?
I can't even start docker daemon, it fails on startup giving the same error

**Comment by uber1geek** [comment]
Hi, I managed to fix this error on an M1 Mac 13 Pro running 12.2.1.

Steps I followed.

-  Remove the docker desktop app from the applications folder
-  run `sudo rm - rf $HOME/Library/Containers/com.docker.docker`
-  Open finder and search for `docker` and remove all remaining system files that show up. (only the system files and not the docker files of your project) 

Hope that helps.

**Comment by ADSETTER** [comment]
> This issue flummoxed me for a couple days, but eventually I found that instead of changing the "disk image location" setting, I could manually move the `Docker.raw` file and create a symlink:
> 
> ```shell
> mv /Users/aaron/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw /Volumes/T7/Docker.raw
> ln -s /Volumes/T7/Docker.raw /Users/aaron/Library/Containers/com.docker.docker/Data/vms/0/data
> ```

same here.
^ This works as an alternative.

**Comment by raspo** [comment]
I had a similar issue, where Docker for mac wouldn't start and would show a very generic error message "Docker daemon failed to start" (on a M1 mac, docker v4.6.1).

I tried reinstalling Docker, using the "reset to factory defaults", manually removing some of folders suggested above.. none of it worked.

Finally, I discovered that there were certain setting files in `~/Library/Group Containers/group.com.docker` that weren't getting purged. So I manually deleted that folder, reinstalled Docker and everything went back to normal (although I lost all settings).

```
 rm -rf  ~/Library/Group\ Containers/group.com.docker   
```

**Comment by jazzywhit** [comment]
> I had a similar issue, where Docker for mac wouldn't start and would show a very generic error message "Docker daemon failed to start" (on a M1 mac, docker v4.6.1).
> 
> I tried reinstalling Docker, using the "reset to factory defaults", manually removing some of folders suggested above.. none of it worked.
> 
> Finally, I discovered that there were certain setting files in `~/Library/Group Containers/group.com.docker` that weren't getting purged. So I manually deleted that folder, reinstalled Docker and everything went back to normal (although I lost all settings).
> 
> ```
>  rm -rf  ~/Library/Group\ Containers/group.com.docker   
> ```

This was very useful for a friend I was helping to debug. It definitely triggered a reset of all settings and he was able to get things working. Thank you!

**Comment by andronocean** [comment]
In case it's helpful to anyone... I ran into this error when trying to set up Docker Desktop on a new Intel Mac. (Hadn't created any containers or downloaded images yet.)

I found that the docker container's directory name was different: it's located in `~/Library/Containers/Docker` instead of `~/Library/Containers/com.docker.docker`. `~/Library/Group Containers/group.com.docker` is in the same place, though.

In my case what worked was:
1. **Change the disk image size FIRST**. Leave the default disk image location alone for now. Click "Apply & Restart". The spinner ran for a minute while the program reloaded. At that point I saw that `~/Library/Containers/DockerData/vms/0/` contained the VM data including the .raw image.
2. Go back into Resources > Advanced, and choose the disk image location you actually want. In my case I put it in `/Volumes/VirtualMachines/Docker`. **Important: the directory you choose must not have a `DockerDesktop` subdirectory in it** — if it does it will complain.
3. Click "Apply & Restart". It tossed up the red error message. Click "Apply & Restart" again. This time I got another red error message, _but_ the loading spinner also started. Let it finish. At the end, the VM had been removed from the `~/Libraries` tree and recreated at `/Volumes/VirtualMachines/Docker/DockerDesktop/Docker.raw`.
4. Add containers, images, whatever as usual.

**Comment by robertopinotti** [comment]
> 2\. Go back into Resources > Advanced, and choose the disk image location you actually want. In my case I put it in `/Volumes/VirtualMachines/Docker`. **Important: the directory you choose must not have a `DockerDesktop` subdirectory in it** — if it does it will complain.

It doesn't work for me. Still the error "Error invoking remote method 'desktop-go-backend': [object Object]"

**Comment by Hoan9696** [comment]
![image](https://user-images.githubusercontent.com/31865722/175796841-3668552e-6d52-4bee-8289-01f5b42f3da3.png)
I'm stuck in here, running forever.

**Comment by notsimon** [comment]
Issue is still here. On Monterey with Apple Silicon, and with the last Docker desktop.
