### ISSUE TITLE
The status indicator always shows Docker Desktop is starting, even after it is running.

### ISSUE THREAD

**Issue by codigovision** [docker/for-mac#6052]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BE915CBF-8274-4DEE-ADAF-06125E2383A4/20211118220453

### Expected behavior
The indicator should change to "Docker Desktop is running" and the icon in the menu should stop animating.

### Actual behavior
The status indicator always shows "Docker Desktop is starting" with the animated icon, even after it is running.

### Information

  - macOS Version: 11.6.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.2

This problem started in version 4.2. Restarting docker desktop shows the correct status, but it always fails on the first run after booting the computer.

### Steps to reproduce the behavior

  1. Start docker after a fresh reboot.

**Comment by StefanScherer** [comment]
Thanks for the report. We have seen this sometimes as well. We're looking into it.
