### ISSUE TITLE
Option to hide the menu bar extra given new MBP notch

### ISSUE THREAD

**Issue by martinemde** [docker/for-mac#6053]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features

It is time to reconsider issue #2272, originally opened in 2017 and auto closed in 2020. It requested the ability to hide the Docker menu bar icon, a feature that has recently increased in urgency.

Now it is 4 years later and we have a different situation. New Apple MacBooks have a notch occupying a significant part of their menu bar. A new user interface style has also increased the padding around each menu bar item. On a new 14" MacBook Pro with the notch, the Docker icon takes up about 1/5th of my remaining space after critical items like battery status, time, date, wifi, and control center. I've already hidden bluetooth, user switching, screen mirroring, siri, spotlight, and focus controls to avoid exceeding the total usable space. Docker is using an unacceptably large portion of my available menu bar with no way to remove it.

This is a screenshot of my entire menu bar from the corner of the screen to the notch. Yes, Harvest takes up a lot of space, but it's much more useful to me than the Docker desktop menu bar extra, so I'm not interested in suggestions to cleanup the rest of my menu bar. As you can see, I had to hide a considerable number of previously useful menu items to fit this, yet _every icon on my menu bar is here by my choice, except Docker_.

<img width="662" alt="Screen Shot 2021-11-19 at 10 31 26 AM" src="https://user-images.githubusercontent.com/989/142673575-059ed72b-3dd6-4480-96fe-973b3ed20482.png">

Additionally, [Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/) still dictate the following:

> Let people decide whether to enable your menu bar extra. Users, not apps, should choose when a menu bar extra is added to the menu bar. Typically, this is done by changing a setting in an app’s preferences window. To ensure discoverability, however, consider giving people the option of enabling the menu bar extra during setup.

There is considerable support for this option already given the previous ticket. It will only increase as more notched laptops are shipped. Particularly on the 14" model this feature is critical.

### Expected behavior

The docker menu bar extra is removable and all menu options are accessible on the dashboard application.

### Actual behavior

There is no way to remove the menu bar extra.

**Comment by StefanScherer** [comment]
Thanks for the detailed report. We already have a roadmap ticket https://github.com/docker/roadmap/issues/281 which you can follow and give a thumbs up. I'm closing this ticket.

**Comment by martinemde** [comment]
Thank you, I searched and googled but didn't come across that roadmap ticket. Thumbs up.
