### ISSUE TITLE
Running container with shell entrypoint hangs on M1 with Intel emulation

### ISSUE THREAD

**Issue by cedws** [docker/for-mac#6054]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `F4F7BCD3-A413-43F1-8B05-E85A938E097D/20211120105332`

### Expected behavior
When I run `gcr.io/distroless/java:debug` (Intel emulation) with the entrypoint set to `sh`, I would expect the shell to be responsive and not hang after the first command. These images do not hang and behave normally:

* `ubuntu:latest`
* `alpine:latest`
* `fedora:latest`

### Actual behavior
After the first command is entered into `sh` and return is hit, the shell hangs forever. The container doesn't exit and continues running, so I can exec into it in another terminal window and the shell behaves normally whilst the first terminal continues to hang. To stop the container I have to kill it.

**This issue is only present on my M1 MacBook. My work Intel MacBook is able to run the image without any hangs.**

https://github.com/GoogleContainerTools/distroless/issues/897

Also, Docker is extremely unresponsive and it took about 10 seconds just to open the Docker window so I could grab the version.

### Information

  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: M1 Pro
  - Docker Desktop Version: 4.2.0 (70708)

### Steps to reproduce the behavior
```
$ docker run --rm --entrypoint sh -it gcr.io/distroless/java:debug
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/ #
/ #
(hang)
```

**Comment by StefanScherer** [comment]
Thanks for the report, but it seems something in this image itself.
I tried
```
$ docker run --entrypoint sh -it amd64/busybox
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/ # 
/ # 
/ # ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
/ # 
```
and it works fine with an Intel based image.
I see that you have opened a ticket in the distroless repo, maybe they find out what could be the issue.
On our side there's nothing more we can help with. I'm closing this ticket.
