### ISSUE TITLE
Cannot push image to local registry

### ISSUE THREAD

**Issue by varun-shahdadpuri** [docker/for-mac#6055]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 107AD214-3FD7-422D-A1A7-BD63AB6AA7DD/20211122022239

### Expected behavior
Push to local registry should work
### Actual behavior
Push to local registry times out. This is only witnessed after updating to latest docker version. Downgrading docker version to 4.0.1 fixes this but this in turn stops us from updating Docker Desktop for Mac
### Information

  - macOS Version: macOS Catalina Version 10.15.7
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 4.2.0 (70708)
```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce the behavior

```
vsp@C02CD1G6MD6R ~ % docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
7b1a6ab2e44d: Pull complete
Digest: sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
vsp@C02CD1G6MD6R ~ % docker tag ubuntu localhost:5000/ubuntu
vsp@C02CD1G6MD6R ~ % docker push localhost:5000/ubuntu
Using default tag: latest
The push refers to repository [localhost:5000/ubuntu]
Get "http://localhost:5000/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by varun-shahdadpuri** [comment]
Any updates?

**Comment by varun-shahdadpuri** [comment]
Can someone please look into this?

**Comment by parostatkiem** [comment]
I'm having exactly the same problem on MacOS Monterey. Downgrade to Docker 4.0.1 helped but of course I'd like to keep my docker up-to-date.

**Comment by pieter91** [comment]
Would just like to add to this with my findings in the hopes that this is the same issue. 

Firstly I discovered that the AirPlay Receiver option in the Sharing preferences of macOS was interfering. AirPlay operates it's server on port 5000. Disabling the feature didn't resolve this issue however. 

In my case, I'm trying to push to http://localhost:5000, which is in fact a port forwarded to my private registry inside a Kubernetes cluster. I can curl http://localhost:5000/v2/ and receive the expected response: `{}`. But trying to push or pull via docker gives: 

```
The push refers to repository [localhost:5000/ubuntu-local]
Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
```

**Comment by dnesting** [comment]
Docker seems to have problems connecting to localhost:

* https://github.com/docker/for-mac/issues/3611
* https://github.com/docker/for-mac/issues/1394
* https://github.com/docker/for-mac/issues/1160

Workarounds that have worked for others, assuming this is the same problem:
* Create a new hostname in `/etc/hosts` mapping `127.0.0.1` to a name like `dockerlocal` and try using that instead of `localhost` or `127.0.0.1`
* Use `0.0.0.0` in place of `127.0.0.1`

**Comment by varun-shahdadpuri** [comment]
This is still happening after upgrade to MacOS Monterey

**Comment by varun-shahdadpuri** [comment]
When is Docker going to fix this? They want us to pay for licenses but not look at issues?

**Comment by kshah-anaplan** [comment]
when I ran command  for container id belongs to registry, I found IPv4 and IPv6 
` docker port 62860613c179` I have observed below output.

`5000/tcp -> 0.0.0.0:5000
5000/tcp -> :::5000
`
so I re-created registry container running the same command 

`docker run -d -p 5000:5000 --restart=always --name registry registry:2` and now I am only able to see IPv4 port forwarding. 
`5000/tcp -> 0.0.0.0:5000`

After that  `docker push`  resloved  `localhost`
