### ISSUE TITLE
Docker Desktop for Mac M1 (Apple Silicon) Still Requires Rosetta

### ISSUE THREAD

**Issue by khenriks** [docker/for-mac#6059]
Docker Desktop for Mac on Apple Silicon hardware requires Rosetta, due to some (unspecified) components that require it.

When running, this error message is shown:

> Docker Desktop requires Rosetta
> 
> This version of Docker Desktop requires Rosetta to run on Apple Silicon.

This is also acknowledged in official [documentation](https://docs.docker.com/desktop/mac/apple-silicon/):

> You must install Rosetta 2 as some binaries are still Darwin/AMD64.

I'm opening this because I couldn't find an existing open issue for this problem. Is there an explanation of what still needs to be done to make it fully ARM-compatible? For example, what binaries are still AMD64?

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

The software runs correctly without requiring Rosetta.

### Actual behavior

An error message is presented.

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.1.1

### Steps to reproduce the behavior

  1. Start the software.

**Comment by StefanScherer** [comment]
Thanks for opening this. We already have it on our internal board, and with the next release 4.3.0 we also made the UI part running natively on Apple silicon. We still have some external command line tools packaged that require Rosetta 2, but we're getting closer. 😄

**Comment by khenriks** [comment]
Thanks for the response. This is really great news. I'm trying to avoid relying on Rosetta 2 on my Mac, and Docker is one of those pieces of software I can't live without, and am really looking forward to having full Apple Silicon support for.

**Comment by StefanScherer** [comment]
Good news. Today we released Docker Desktop 4.3.0 which doesn't require Rosetta 2. See https://docs.docker.com/desktop/mac/apple-silicon/ for details.
