### ISSUE TITLE
127.0.0.1 stopped working

### ISSUE THREAD

**Issue by StokeMasterJack** [docker/for-mac#606]
I have an app with 2 containers: tomcat and mysql (same physical machine). I am running docker for mac so the tomcat container references the mysql container using 127.0.0.1. 

Then all of a sudden, this stopped working. Getting "connection refused" now. Didn't change anything.
### Information
- If I point my local tomcat to a different mysql ip address altogether (the product db), it works.
- Also, if just use mysql command line tool I can connect to the 127.0.0.1 mysql just fine:
  mysql --host=127.0.0.1 --user=root --port=3306

The problem is the tomcat container at 127.0.0.1:80 cannot access the mysql container at 127.0.0.1:3306

I just get connection refused.

Diagnostic ID: E9076C01-9445-43F6-B081-A69A030E7122
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.4 (Build 15E65)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by ijc25** [comment]
Hi @StokeMasterJack,

Thanks for the report. Please can you provide repro steps in terms of the exact base images (or even Dockerfiles) you are using and the commands you are using to start the containers as well as the shell from which you are running the mysql command you mention above (e.g. is it on the Mac or in a container?)

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
