### ISSUE TITLE
Lost all data after upgrade to 4.2.0

### ISSUE THREAD

**Issue by januszm** [docker/for-mac#6062]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Regular upgrades from version to version do not cause data loss.

### Actual behavior

Lost all images, containers, volumns, all data after the most recent upgrade to 4.2.0.

### Information

  - macOS Version: 10.15.7 Catalina
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.2.0

`Docker.raw` file is in: `~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw`

The path to the Docker.raw file is correctly set in: `~/Library/Group\ Containers/group.com.docker/settings.json` and in `Library/Containers/com.docker.docker/Data/vms/0/hyperkit.json`

**Comment by olets** [comment]
Is there a `.` in your directory names? (Like "myproject.com" etc) Wonder if this is
- #6078
