### ISSUE TITLE
It breaks when I allocate more than 8 cpu cores (Apple M1 Max)

### ISSUE THREAD

**Issue by kakserpom** [docker/for-mac#6063]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
If I allocate more than 8 cpu cores it breaks. Only a factory reset can help.

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple chip (M1 Max)
  - Docker Desktop Version: 4.2.0 (70708) 

### Steps to reproduce the behavior
 1. Allocate more than 8 cores in the Resources settings tab. 
 2.  See the status bar go berserk alternating between “Docker Engine starting…” and “Docker Engine stopped”.

**Comment by vanvoljg** [comment]
Yes, I have the same problem.

macOS Version: 12.0.1
Chip: Apple Silicon (M1 Max)
Docker Desktop Version: 4.3.0

Setting cores to 8 appears to be safe and stable. Increasing beyond that causes this bug.

**Comment by bcbee** [comment]
Same problem, going beyond 8 causes boot loop and I need to factory reset to fix

macOS Version: 12.0.1
Chip: Apple Silicon (M1 Max)
Docker Desktop Version: 4.3.0

**Comment by StefanScherer** [comment]
Thanks for the report. Yes, 8 cores is the maximum at the moment. We apologise for the inconvenience and are looking for a solution.

**Comment by jtowe1** [comment]
Same issue, following

**Comment by chriscrowe** [comment]
Is there a workaround for forcing Docker Desktop back to ≤8 cores? Seems like once you get into the crash loop you can't reconfigure the settings anymore -- factory restart and/or reinstall does not seem to help.

**Comment by kakserpom** [comment]
@chriscrowe Reinstalling doesn't help at all unless you delete all residual files in App Data. However Factory Reset helps without fail. Are you sure you are doing it right?

**Comment by jwhitehorn** [comment]
Wow, just ran into this as well.

I do agree with @kakserpom , doing a factory restore "fixes" it (in so much that I can get back into Docker now), but unfortunately it also ate all my settings which I now have to go back and setup.

Hopefully this gets fixed soon.

**Comment by kakserpom** [comment]
@jwhitehorn yeah, they should fix the UI until there's support for >8 cores

**Comment by jtowe1** [comment]
> Is there a workaround for forcing Docker Desktop back to ≤8 cores? Seems like once you get into the crash loop you can't reconfigure the settings anymore -- factory restart and/or reinstall does not seem to help.

Preferences -> Bug Button -> Reset To Factory Defaults (this worked for me)

**Comment by znerd** [comment]
Problem is related to the fact that there are 8 regular cores, and 2 efficiency cores right? The latter are supposedly dedicated to (specific types of?) background processes.

<img width="495" alt="Screen Shot 2022-01-27 at 18 12 24" src="https://user-images.githubusercontent.com/117866/151408961-18166765-d973-413d-89fe-7ed9c7c85a28.png">

**Comment by StefanScherer** [comment]
Our engineers at Docker are working on a fix to use only up to 8 CPU's on the M1.

**Comment by wright-1** [comment]
> Is there a workaround for forcing Docker Desktop back to ≤8 cores? Seems like once you get into the crash loop you can't reconfigure the settings anymore -- factory restart and/or reinstall does not seem to help.

Had the same issue. Make sure you clear  `~/.docker` before you reinstall.

**Comment by StefanScherer** [comment]
As a workaround you can stop or kill Docker Desktop processes and edit the `~/Library/Group\ Containers/group.com.docker/settings.json` file and set `cpus` to `8`.
The next release of Docker Desktop which is planned for next week will contain a fix.

**Comment by StefanScherer** [comment]
We've released Docker Desktop 4.5.0 which solves the problem.

**Comment by christhomas** [comment]
No it didn't. I had this problem tonight with a brand new m1 version downloaded from the website tonight. Incidentally my settings.json file contained the value cpus: 8, and it was still bootlooping infinitely without any resolution. Clicking any number of times on purge data, factory reset, etc in the UI did absolutely nothing and the UI would start with "Docker Desktop stopped" without any way to start, or restart it. I set the value to 6 cpus and it had no effect on it at all.

I don't know how to completely purge every single setting or file from my computer and reinstall it without some residual file being left over. Even deleting all the files I could find in my home directory with rm -r on the terminal in the .docker and Library folders didn't fix it.

So I'm absolutely stuck. I don't know what else I can try, there must be something missing on the computer, but I don't know what to do about it.
