### ISSUE TITLE
macOS Dual Docker Icons

### ISSUE THREAD

**Issue by rushelex** [docker/for-mac#6068]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Information

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Docker Desktop 4.2.0 (70708)

### Steps to reproduce the behavior

Hello! The problem was described in issue #4914. It persists on the Docker Desktop version on Mac OS Big Sur.

![CleanShot 2021-12-01 at 11 59 14@2x](https://user-images.githubusercontent.com/41122157/144186992-ae67726f-5456-4490-86b8-52fb0e30785d.png)

**Comment by StefanScherer** [comment]
Thanks for the report. Yes I sometimes see this on other machines. But currently on my Big Sur MBP it behaves correctly. I think it depends on which program is connected to the Dock. There's the native app and the Electron frontend application.
Have you tried to remove all Docker icon from the Dock and then open the Docker Desktop Dashboard? Now you can connect this to the Dock if you like.
I only have one Docker icon and it disappears when I close the UI. When I keep this dashboard Docker icon in the Dock I also only have one Docker icon at any time, it has the dot below when the dashboard is open, and stays in Dock when I close the UI again.

**Comment by rushelex** [comment]
Thank you, I got it. Indeed, if you dock an app that lies in `/Applications/Docker.app/Contents/MacOS/Docker Desktop.app`, it will dock correctly and only one icon will be displayed. This solves my problem.
