### ISSUE TITLE
Common keyboard shortcuts like RETURN key or ESC key are non-functional in dialog boxes

### ISSUE THREAD

**Issue by rantler** [docker/for-mac#6069]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] ~I have uploaded Diagnostics~ Diagnostics are irrelevant to this issue
  - Diagnostics ID: N/A

### Expected behavior

Pressing the RETURN key or ENTER key is equivalent to clicking the "Remove" button.
Pressing the ESC key is equivalent to clicking the "Cancel" button.
Pressing the TAB key moves focus between the available buttons.
Pressing the SPACEBAR is equivalent to clicking the mouse button the focused button.

Similar behavior is expected for all "buttons" in all user interface dialog boxes.

### Actual behavior

User is forced to use the mouse pointer to point at and click the desired "button" to affect the desired outcome.

This is an accessibility issue and greatly detracts from the usability of Docker Desktop.

### Information

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.2.0

### Steps to reproduce the behavior

  1. Click on the "trashcan" or DELETE button on the Containers/Apps list.
  2. See a confirmation dialog box appear with "Cancel" and "Remove" buttons.

**Comment by merges** [comment]
Oh my gosh, *please* implement this. Mousing around that container list is insane without basic keyboard shortcuts. Thank you!
