### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by Naatan** [docker/for-mac#6070]
Please reopen https://github.com/docker/for-mac/issues/5123

I would have responded there but can't due to your issue closing mechanic. Don't understand why you can't still let people respond.

The issue is unresolved, and far as I can tell no bug has been filed with qemu. Furthermore whether it is a bug in a third party dependency should be irrelevant as it is the Docker end users that are being affected. At the very least you ought to be spearheading a bug report with qemu.

**Comment by StefanScherer** [comment]
We closing old issues to focus on new reports. The ticket is more than one year ago, we used different versions of Qemu at that time. I saw the initial reported had a problem with node-unbuild image. In the meantime they now provide a multi-architecture image for that to have a linux/arm64 variant to run natively on M1 machines without Qemu. That also is our general recommendation, try to use arm64 image to have the best performance and not rely on emulation, and encourage image providers to make their images support arm64 as well.

If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-mac/troubleshoot?

**Comment by timdinhdotcom** [comment]
I'm also receiving this error message when running `docker build --platform linux/amd64` on an Apple M1.

My work around is
1. Use Debian 10 base image
2. Shutdown docker then start docker again when you get this error message

It seem to crash on subsequent build and restarting docker seem to fix. Annoying but will have to do for now.

**Comment by timdinhdotcom** [comment]
btw, I have to also delete the previously generated image as if I were to start fresh.
