### ISSUE TITLE
`qemu: uncaught target signal 11 (Segmentation fault) - core dumped` when building Erlang OTP24(JIT) with amd64 platform on M1

### ISSUE THREAD

**Issue by tmjoen** [docker/for-mac#6075]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

Diagnostics is not working -- it hangs on "Diagnosing..." for a very long time (+30 mins)

### Expected behavior

Not segment faulting when building OTP24 on an M1 mac emulating amd64.

### Actual behavior

Segmentation fault on building

### Information
  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple M1 Max
  - Docker Desktop Version: 20.10.10

### Steps to reproduce the behavior

Dockerfile
```
# syntax = docker/dockerfile:1.0-experimental
FROM --platform=linux/amd64 hexpm/elixir:1.13.0-rc.1-erlang-24.1.5-ubuntu-focal-20210325 as deps

RUN elixir -e "String.downcase(\"HELLO DOCKER!\")"
```

Error output:

```
#9 [2/2] RUN elixir -e "String.downcase("HELLO DOCKER!")"
#9 sha256:655fabd11ea570c8326f0dc9e543732e547a4c9cadb37c1c2b2ea2fe7e6d571d
#9 1.270 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#9 1.276 Segmentation fault
#9 ERROR: executor failed running [/bin/sh -c elixir -e "String.downcase(\"HELLO DOCKER!\")"]: exit code: 139
------
 > [2/2] RUN elixir -e "String.downcase("HELLO DOCKER!")":
------
executor failed running [/bin/sh -c elixir -e "String.downcase(\"HELLO DOCKER!\")"]: exit code: 139

Fatal error: local() encountered an error (return code 1) while executing 'docker build --progress=plain -f Dockerfile -t t/testimg .'

Aborting.
```

It seems to be linked to if the Erlang version is compiled with JIT or not. This was introduced in OTP24. OTP23 works, so does using old versions of Ubuntu (where the C++ version is so old that OTP will compile without JIT).

I've seen that the recommandation is just to use arm instead of amd64, but we are building a local docker container that we extract the application from and upload to run directly on bare metal linux amd64. This means we MUST build with amd64 unfortunately.

I'm wondering if I should raise this issue in the QEMU repo, but I'm not quite sure how to get more debug info for them. This is all the debug info I've managed to get.

It is pretty regularly reproduceable, but some times it will run through. When changing the image to `FROM --platform=linux/amd64 hexpm/elixir:1.13.0-rc.1-erlang-23.2.7.4-ubuntu-focal-20210325 as deps` it works, since it pulls Erlang OTP 23, which has no JIT. 

Any pointers, insight or help would be GREATLY appreciated, since we would love to build with Erlang OTP24 w/JIT for it's speed and new features <3

**Comment by stephen-turner** [comment]
Sorry, there's not much we can do about qemu crashes. As you know, we recommend not using it where possible, and we have documented it as "best effort only". I realise that doesn't solve your immediate problem.
