### ISSUE TITLE
Reboot machine `Docker version 17.12.0 or later required.` when using Remote Containers in VScode

### ISSUE THREAD

**Issue by apple-corps** [docker/for-mac#6077]
Docker Desktop installed along with vs code and remote containers. Using the local Docker Desktop with Remote Containers. Everything was working on the system. Rebooted mac. Opened project and selected `Reopen in Container`. Receive message that `Docker version 17.12.0 or later required.` . But as reported previously Docker desktop is already installed

---

Docker Desktop
---

```
4.2.0 (70708)
Engine: 20.10.10
Compose: 1.29.2
Credential Helper: 0.6.4
Kubernetes: v1.21.5
Snyk: v1.563.0
```
---

VScode

---

```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (3 mos ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.4.0
```

---

MacOS Big Sur
Version 11.3.1

**Comment by stephen-turner** [comment]
It sounds like this is a bug in the VS Code plugin (which is not maintained by us) rather than Docker Desktop.
