### ISSUE TITLE
Upgrade pop-up window steals focus, steals input

### ISSUE THREAD

**Issue by tmack0** [docker/for-mac#6079]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 6E895065-BF15-435A-8210-037EE0BCC886/20211206231314

### Expected behavior

Upgrade notifications flag the taskbar icon or create a notification or use another non-intrusive way to alert the user of available upgrades.

### Actual behavior

A pop-up box appears and steals focus from other apps, potentially stealing sensitive keystrokes (if the user is typing a password when this happens), but most often stealing the space or enter keystroke to confirm an upgrade (or by chance denying the upgrade, if the proper sequence of keys is hit) without the user being aware, while also interrupting whatever was ACTUALLY being worked on, interrupting work, sometimes time-critical typing, etc.

### Information

  - Is it reproducible? Every Update until automatic-update checks are disabled (impossible for free users)
  - Is the problem new? No
  - Did the problem appear with an update? Every Update since ??? (oldest ticket I see in github for this is ~2017)
  - A reproducible case if this is a bug, Dockerfiles FTW. : No Dockerfile needed, just enable auto-updates and wait for an update.
  - macOS Version: 10.15.7 (19H1519) Catalina
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1 (thanks to this bug)

### Steps to reproduce the behavior
  1. Enable auto-update checks (free users CANT disable this)
  2. Wait for an update to be found by Docker desktop
  3. profit?

This has been reported several times in the past, only one ticket is currently still open and only deals with 'while docker is starting': https://github.com/docker/for-mac/issues?q=is%3Aissue+steals+focus
This is highly annoying, disruptive, and potentially a security issue (stealing keyboard input while users could be entering passwords is BAD)

**Comment by StefanScherer** [comment]
Thanks @tmack0 for the report. Actually when you update to 4.2.0 or newer you can disable auto-update checks. Please have a look at the release notes https://docs.docker.com/desktop/mac/release-notes/
I'm going to close this issue as it is solved in a newer version.
