### ISSUE TITLE
Downloading 4.3.0: The operation couldn’t be completed. (Docker.UDSResponseError error 1.)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6080]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9E774334-8D98-43B0-949B-A8D420C6D483/20211207212213

### Expected behavior

Upgrading 4.2.0 to 4.3.0. Expect it to download the new version.

### Actual behavior

Dialog box with "The operation couldn’t be completed. (Docker.UDSResponseError error 1.)"

<img width="506" alt="rfay-mbp-2017" src="https://user-images.githubusercontent.com/112444/145108249-cf7a309c-fa55-4c70-94e7-706b713b8bc6.png">

### Information

This has now happened to me twice during upgrading ddev's test runners from 4.2.0 to 4.3.0. I tried to ignore it the first time.

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.2.0 to 4.3.0

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by StefanScherer** [comment]
Thanks, we're looking into the diagnostic logs.
