### ISSUE TITLE
libzmq crashes on M1 Mac: Operation not permitted

### ISSUE THREAD

**Issue by dmitry-tk** [docker/for-mac#6084]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C37650A3-75C4-4F9A-A6BA-F9BDA82AEC68/20211209104158

### Expected behavior

Run docker container with [libzmq](https://github.com/zeromq/libzmq) server (based on Ubuntu 18.04).

### Actual behavior

Container crashes on these lines:
```c++
int rc = pthread_getschedparam (pthread_self (), &policy, &param);
posix_assert (rc);
```
in this [file](https://github.com/zeromq/libzmq/blob/master/src/thread.cpp) with the following error:
```
Operation not permitted (/usr/src/sdk/libzmq/src/thread.cpp:302)
[2021-12-09 13:31:50.058] [info] Received exit signal 6.
qemu: uncaught target signal 6 (Aborted) - core dumped
```

Adding `--cap-add SYS_NICE`, `--privileged`, `--userns host` doesn't help.
The image works fine on Intel Macs.

### Information

  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version: 4.3.0 (71786)

### Steps to reproduce the behavior

  1. Run docker container with `libzmq` server. This image may be used as an example: `docker run skalenetwork/sgxwallet_sim:1.78.0-develop.1 -s -y`

**Comment by stephen-turner** [comment]
Thanks for the report. I suspect this is the same as this upstream issue https://github.com/tonistiigi/binfmt/issues/69 (even though that issue title only mentions musl-based distros). Could you try https://desktop-stage.docker.com/mac/main/arm64/72126/Docker.dmg and let me know whether it fixes the problem? Thank you.

**Comment by dmitry-tk** [comment]
@stephen-turner, thanks, it works on `4.4.0` without any issues, no additional options needed.

**Comment by stephen-turner** [comment]
@dmitry-tk Thanks for checking. We will ship this in 4.4.
