### ISSUE TITLE
docker-scan executable is still x86_64 even on 4.3 Apple silicon

### ISSUE THREAD

**Issue by fornwall** [docker/for-mac#6088]
It seems that `cli-plugins/docker-scan` is still a x86_64 binary even in 4.3 when on Apple silicon (and release notes for 4.3 states `Docker Desktop on Apple silicon no longer requires Rosetta 2`).

On a fresh install, `docker --help` shows:

```
[...]
Invalid Plugins:
  scan        failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: bad CPU type in executable
```

since it fails to execute `docker-scan`, and:

```sh
$ file /usr/local/lib/docker/cli-plugins/docker-*   
/usr/local/lib/docker/cli-plugins/docker-buildx:  Mach-O 64-bit executable arm64
/usr/local/lib/docker/cli-plugins/docker-compose: Mach-O 64-bit executable arm64
/usr/local/lib/docker/cli-plugins/docker-scan:    Mach-O 64-bit executable x86_64
```

**Comment by stephen-turner** [comment]
Yes, this binary is provided by a third party and we don't have an arm64 version yet. We have documented this at https://docs.docker.com/desktop/mac/apple-silicon/#known-issues, but we should probably put it in the release notes too. I'll add it.
