### ISSUE TITLE
VM has not started

### ISSUE THREAD

**Issue by BrendaCayzac** [docker/for-mac#6091]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  C68E904D-9C6D-4EEA-A288-E8FDC4F4CCBF/20211213162244 (uploaded)

### Expected behavior
Containers run with no problem and I can test my API.

### Actual behavior
I get timeouts constantly and I've only gotten Docker to work once, after I closed my Mac, it stoped working again

### Information
  - Followed MacOS Intel installation guide, set up my project. Whenever I go to an API endpoint, I get a timeout. My coworker using another Mac has no problem
  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: M1
  - Docker Desktop Version:  4.3.0 (71786)
  - after running: `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` I get:
  Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

### Steps to reproduce the behavior
1. Install Docker.
2. Run ` docker-compose up -d  ` inside project.
3. On App, all the containers seem to be running with no issue
4. Access container bash, try `composer -v`, bash is now stuck.

[C68E904D-9C6D-4EEA-A288-E8FDC4F4CCBF.zip](https://github.com/docker/for-mac/files/7705370/C68E904D-9C6D-4EEA-A288-E8FDC4F4CCBF.zip)

**Comment by sokratisg** [comment]
Exact same issue on the following setup

* macOS 11.6.2 (20G314)
* Docker Desktop 4.3.2 (72729) 
* Intel chip

[20220105095446.zip](https://github.com/docker/for-mac/files/7814032/20220105095446.zip)

**Comment by xbmono** [comment]
I have exact same issue... any advice?

**Comment by artemgood** [comment]
Exact same issue on the following setup

macOS 12.3 (21E230)
Docker Desktop 4.7.0 (77141)
m1 chip
