### ISSUE TITLE
Problem with sync container and Docker Desktop 4.3.1 (Apple Silicon)

### ISSUE THREAD

**Issue by patriceckhart** [docker/for-mac#6092]
I use `mickaelperrin/docker-magic-sync` for my sync from container to local. That always worked very well.
It no longer works since the update to Docker Desktop 4.3.1 (Apple Silicon).
In my sync container I get the following error:

```
fs.inotify.max_user_watches=524288
fs.inotify.max_user_watches = 524288
Traceback (most recent call last):
  File "/config_sync.py", line 195, in <module>
    c.set(sys.argv[1])
  File "/config_sync.py", line 189, in set
    self.merge_discovered_volumes()
  File "/config_sync.py", line 167, in merge_discovered_volumes
    for volume in volumes['volumes']:
TypeError: 'NoneType' object is not iterable
```

I've looked at the file but don't understand the problem.

I have execute
`softwareupdate --install-rosetta`
but the sync doesn't work

**Comment by WhiteDragon29** [comment]
I have the same problem, but  I need to restart docker, I can synchronize successfully

**Comment by patriceckhart** [comment]
Ok, I'm using now another sync container.

**Comment by katipierson** [comment]
Same problem here. Restart auf Docker solve the problem for a few minutes. Restart of the container doesn't resolve it.
Problem exists since latest version for all containers with mounted volumes.
