### ISSUE TITLE
Feature Requests for Docker Dashboard

### ISSUE THREAD

**Issue by charany1** [docker/for-mac#6095]
Hi ,

Need below features in Docker Dashboard in Docker Desktop for Mac.

1. Option to set edit container configuration from `Docker Dashboard UI -->  Containers` view itself. Currently , it's only a read only view.

2. Option to specify environment variables while launching a container from `Docker Dashboard UI -->  Images` view .

3. Capability to search for images and run container from Docker hub directly from Docker Dashboard similar to Kitematic.

**Comment by StefanScherer** [comment]
Thanks @charany1 for the feedback and suggestions. I'll forward your request to our UX designers.

**Comment by nic-craig-ungerware** [comment]
Kitematic had these features and was great. These seem like basic things and I'm not sure what purpose Docker Desktop serves without them.

**Comment by eurycea** [comment]
Kitematic had these features and was great. I'm not sure what purpose Docker Desktop serves without these features.
