### ISSUE TITLE
Mac *.local mDNS domains will not resolve within Docker containers. Using Docker For Mac

### ISSUE THREAD

**Issue by RobbyC231** [docker/for-mac#6098]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2C67F2BC-0867-4EBF-8F99-C1E73E4BB5F1/20211215183655

### Expected behavior
* Turn on File Sharing in Big Sur System Preferences -> Sharing
* Note the machine name in Computers on your local network can access your computer at: abc.local
* Start a service like CouchDB in a docker container and expose it's port.
* Access the service at (example) http://abc.local:15985
   * from the physical Mac (ie. web browser) ✅
   * from another computer or mobile device on the same network ✅
   * from another docker container reliably using, for example, curl ✅

### Actual behavior
* try to ping http://abc.local:15985 produces `connect: Cannot assign requested address`
* try to hit via running app and it produces `Errno::EINVAL (Invalid argument - Invalid argument - connect(2) for "abc.local" port 15985 (abc.local:15985)):`

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple m1 Chip
  - Docker Desktop Version: 4.3.1
  - This happens when the new Virtualization framework is ON and when it is OFF
  - it is reproducible

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```zsh
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

### Steps to reproduce the behavior

  1. turn on file sharing on mac and not the name of the computer
  2. see if you can ping the address (http://abc.local:15985) on the host machine. Should be able to, should also be able to ping this address from another machine on the same network. 
  3. try to ping this address from inside docker container and you will get `connect: Cannot assign requested address`
  4. It can pass for a couple minutes before ultimately failing

**Comment by blairio** [comment]
I see this too on Mac Intel with MacOS 11.6.1 and Docker 4.1.0 occasionally.

Feels like a return of https://github.com/docker/for-mac/issues/5752 which seemed to have gone away between August and November, but now is back.
