### ISSUE TITLE
Update from 4.3.0 to 4.3.1 broke Docker app

### ISSUE THREAD

**Issue by alexchandel** [docker/for-mac#6100]
- [x] I have tried with the latest version of Docker Desktop
  - [n/a] I have tried disabling enabled experimental features
  - [n/a] I have uploaded Diagnostics
  - Diagnostics ID: N/a

### Expected behavior

Updating from 4.3.0 to 4.3.1 does not break Docker.

### Actual behavior

Updating from 4.3.0 to 4.3.1 literally broke the Docker app:
![Screen Shot 2021-12-16 at 5 07 55 PM](https://user-images.githubusercontent.com/637714/146462475-c068e8dd-2bf4-4750-bab2-eaa6ace28fa5.png)

### Information

  - macOS Version: 11.6.2
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.3.0 / 4.3.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

`zsh: no such file or directory: /Applications/Docker.app/Contents/MacOS/com.docker.diagnose`

Docker.app is >900MB, but the updater apparently removed the `MacOS` folder, among other things.

### Steps to reproduce the behavior

N/A

**Comment by josh-m-sharpe** [comment]
came here to file more colorful issue but this fella is corgial.

I see "You can’t open the application “Docker” because it may be damaged or incomplete."

**Comment by josh-m-sharpe** [comment]
I resolved this, by:
1) downloading a new installer
2) using finder to rename the busted Docker (in Applications folder) to "Docker.bak"
3) Installing clean

launching the new one seemingly has all my containers/images

**Comment by DarkStar1** [comment]
I also have this issue after updating.
I decided to resolve it by downloading a new installer from the official site.
Deleted the old docker. Installed the new one from the installer.
Tried this twice but to no avail.
Any attempt at using any docker-cli commands results in the popup:
<img width="242" alt="docker-corrupt-popup-message" src="https://user-images.githubusercontent.com/1119388/148971488-091d0de3-d4a8-428f-a8f6-8cf0a670cf75.png">

So I have no option except to move it to the bin.

**Comment by DarkStar1** [comment]
So I removed the com.apple.quarantine extended attribute from the Docker.app in order to be able to launch it.
The Docker version in question is: `Docker Desktop 4.3.2 (72729)`.
On another note; n startup I saw that it shared some host directories with Docker that I am not comfortable with so I removed those. When did auto file sharing of host directories become the norm with new installations of Docker (other than `/tmp` of course).

**Comment by bendilley** [comment]
I had the same problem with Docker Desktop 4.4.2. Like @DarkStar1 I had to remove the quarantine attribute. For reference, the command is
```bash
sudo xattr -rd com.apple.quarantine /Applications/Docker.app
```

**Comment by schellj** [comment]
I had the same problem just now after doing an "Update & Restart" from the 4.3.1 the taskbar menu. Clicking the "Update & Restart" button in the dashboard settings did nothing.

**Comment by alexchandel** [comment]
This same issue happened again updating from 4.4.2 to 4.5.

`sudo xattr -rd com.apple.quarantine /Applications/Docker.app` does not fix the issue I describe, because the entire `MacOS` folder is deleted by Docker's faulty updater.

Please fix this.

**Comment by timxor** [comment]
Same issue, second time after new macOS update. Delete, then reinstall worked for me. https://docs.docker.com/desktop/mac/apple-silicon/

**Comment by Spillmaker** [comment]
Updated my apps on my mac today, and this happened for me as well.

Removing and Reinstalling Docker Desktop resolved it for me, but odd that this happens when you just want to update Docker. 

If docker really want to be insiting on updating, it would be nice that the updates doesnt make the app self-combust.

**Comment by Alspaladin** [comment]
Just happened to me when updating from 4.6.x to 4.7.1 on Monterey 12.0.1

**Comment by MustafayevMohammed** [comment]
> came here to file more colorful issue but this fella is cordial.
> 
> I see "You can’t open the application “Docker” because it may be damaged or incomplete."

how did you solved it?
