### ISSUE TITLE
docker build on apple silicon fails for arm (not arm64) with a QEMU error

### ISSUE THREAD

**Issue by cosnicolaou** [docker/for-mac#6103]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2A353146-669C-47D4-AD37-C05DE090AC4C/20211220022822

### Expected behavior

docker build should work
### Actual behavior

docker build fails with a QEMU illegal instruction

### Information

this is reproducible, it's the first time I'm trying this on an apple silicon Mac, it works fine on intel.
  - macOS Version: 15.1
  - Apple chip: M1 max
  - Docker Desktop Version: 4.3.1 (72247)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

Note that despite the warnings above I can start a VM, e.g. the docker hello world app runs fine.

### Steps to reproduce the behavior

$ cat > Dockerfile <<eof
FROM balenalib/rpi-raspbian:bullseye-20210925
USER root
RUN apt-get update -y && apt-get upgrade -y
eof

$ docker build .
....
 > [2/2] RUN apt-get update -y && apt-get upgrade -y:
#5 0.808 Get:1 http://archive.raspberrypi.org/debian bullseye InRelease [23.5 kB]
#5 0.808 qemu: uncaught target signal 4 (Illegal instruction) - core dumped
#5 0.872 Reading package lists...
#5 0.982 E: Method http has died unexpectedly!
#5 0.982 E: Sub-process http received signal 4.
------
executor failed running [/bin/sh -c apt-get update -y && apt-get upgrade -y]: exit code: 100

**Comment by stephen-turner** [comment]
Thanks for the report. All qemu operations are best-effort only. We're aware that it crashes occasionally, but it's outside of our control.

**Comment by crazy-max** [comment]
Have you tried with another raspbian flavor like:

```dockerfile
FROM tianon/raspbian:bullseye-slim
RUN apt-get update -y && apt-get upgrade -y
```

Also it's not recommended to perform an upgrade/dist-upgrade.

**Comment by cosnicolaou** [comment]
thanks, that does work for me also so it's a possible work around. I',m very curious as to why it would behave differently. I'm looking at how the images are built but there's nothing obvious in terms of what could cause the different behavior. Either way I think it's pretty clear it's a QEMU bug. The apt-get update etc is needed for the rest of the setup for my project, I just didn't include that in the example.

**Comment by cosnicolaou** [comment]
it turns that the balenalib images includes its own version of QEMU (built for x86) which it uses for cross builds and that seems to be the root cause of the problem. I filed a bug there https://github.com/balena-io-library/base-images/issues/741.
