### ISSUE TITLE
Docker.dmg for Intel Mac corrupted

### ISSUE THREAD

**Issue by chkpnt** [docker/for-mac#6105]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 11.5.1
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: latest from https://www.docker.com/get-started (there is no version number mentioned!)

### Steps to reproduce the behavior

  1. Download Docker for intel
  2. Open the .dmg
  3. Drag'n'Drop of Docker.app to the application folder leads to a message "Docker file is damaged"

Unfortunately, there are no checksums / signatures available, so I do not know if the current dmg available on docker.com is trustable.

**Comment by bmcovera** [comment]
I am having the same problem. It did an auto update and never restarted. I tried restarting and got the "Docker file is damaged" error. Then downloaded and installed latest dmg with the same result. I also had an additional error message along the lines of "file name is too long", but wasn't able to capture it.

**Comment by chkpnt** [comment]
In the meantime, I've managed to install docker via homebrew:
```
> brew install --cask docker
```

**Comment by mechanical-fish** [comment]
Same issue here. Will try to see if we there are older versions of the installer available somewhere.

**Comment by chkpnt** [comment]
Mh, I wonder why this issue isn't labeled as a security issue by Docker.

**Comment by josephmidura** [comment]
I've seen similar behavior on Monterey 12.1. When I try to open Docker Desktop, the OS gives the warning message "You can't open the application 'Docker.app' because it may be damaged or incomplete."

**Comment by yxchiwork** [comment]
Just had this issue, I tried in-app upgrade but it stucked at downloading so I downloaded the new dmg and I had the exact same issue, I did this to fix it:
sudo xattr -rd com.apple.quarantine /Applications/Docker.app

**Comment by chkpnt** [comment]
I've just reinstalled Docker v4.6.0 and this time, the issue didn't occur.

But as I can't find a statement in the [release notes](https://docs.docker.com/desktop/mac/release-notes/), I'm keeping this issue open until commented by Docker Inc.

/remove-lifecycle stale

**Comment by damontgomery** [comment]
I'm not sure if this is the same issue, but I tried to update from ~4.3 to ~4.7 and kept getting the `“Docker” is damaged and can’t be opened. You should move it to the Trash.` message. This message would keep popping up during copying from the image and after even if I didn't open Docker Desktop myself.

I tried restarting the computer, removing, redownloading, etc.

I think what finally got it to work was
- Remove
- Mount image
- Copy application to `Downloads` folder (not `Applications`)
- Move from `Downloads` to `Applications`
- Then I was able to open the application and MacOS didn't complain.

**Comment by VanPaitin** [comment]
* Just download a clean dmg file. Preferably the latest.
* Double click on it (a window will instruct you to move the Applications folder)
* Obey the instruction (a window will ask you whether you want to replace the existing installation of docker)
* Choose Yes
* Problem fixed

Your containers and images will be in place where you left them.

**Comment by chrishj59** [comment]
When I download from https://docs.docker.com/desktop/install/mac-install/ I get a document not DMG file. I am on MacOS 12.5. Please let me know if there is another location the DMG fie should be downloaded from

**Comment by nicks** [comment]
I'm going to close this since comments confirm that it's fixed in later releases.

@chrishj59 we believe your problem is a bug in Firefox and will be fixed if you upgrade Firefox, see https://github.com/docker/for-mac/issues/6411
