### ISSUE TITLE
child processes are missing privileges when running Intel-based image on Arm-based machine (Apple M1)

### ISSUE THREAD

**Issue by christierney** [docker/for-mac#6106]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 31BC56DC-086E-4E94-B4D2-DFD454CDD1A6/20211221200221

### Expected behavior

System calls that work with an Arm image, and work with an x86 image on x86 hardware, should also work under emulation on Arm hardware. Specifically, a child process making the `initgroups` system call should work.

### Actual behavior

Under emulation (running an x86 image on Arm hardware), a child process seems to have incorrect privileges; calling `initgroups` fails with `Operation not permitted`. See steps to reproduce below.

### Information

This is reproducible on multiple Apple M1 macbooks.

A private image I use, that is only available for the x86 platform, contains a program that performs process privilege manipulation and forks a child process. This program started reporting failures when I tried to use it from an Apple M1 machine, running the x86 image. The error is `Operation not permitted`, and I traced it to a specific series of steps:

- the program is executed as `root`
- the program drops privileges by setting its UID/GID to another user
- the program `fork`s
- after forking, the process sets its UID back to `root` and tries to call `initgroups`. This call fails in the child process (but succeeds on x86 hardware).

I have a minimum reproducible example (see Steps to Reproduce).

  - macOS Version: Monterey v12.1
  - Intel chip or Apple chip: Apple M1 chip
  - Docker Desktop Version: 4.3.1 (72247)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```shell
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

(Despite the vm errors, I am generally able to build and run images just fine, aside from the bug I'm reporting here.)

### Steps to reproduce the behavior

This is reproducible with a `Dockerfile` and a small C program:

`Dockerfile`:
```Dockerfile
# I first found and reproduced this issue on an image based on ubuntu:bionic-20201119,
# but I have also reproduced with newer versions of ubuntu
FROM ubuntu:bionic-20201119

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
    gcc && \
    rm -rf /var/lib/apt/lists/*

ARG USER_GID=1001
ARG USER_UID=1001

# Create a non-root user with known id:gid that our program will switch to
RUN groupadd -g $USER_GID notroot && \
    useradd -u $USER_UID -g notroot notroot

COPY ./forkandinit.c /

RUN gcc /forkandinit.c -o /forkandinit

CMD ["/forkandinit"]
```

`forkandinit.c`:
```c
#include <stdio.h>
#include <grp.h>
#include <errno.h>
#include <pwd.h>
#include <sys/wait.h>

int main() {
    errno = 0;
    uid_t root = 0;
    uid_t uid = 1001; // nonroot
    gid_t gid = 1001; // nonroot
    pid_t pid = 0;
    pid_t terminated = 0;
    int wstatus = 0;

    printf("parent: dropping privileges, forking, and restoring privileges:\n");

    if (setresgid(-1, gid, getegid()) < 0)
        perror("parent: setresgid error");
    if (setresuid(-1, uid, geteuid()) < 0)
        perror("parent: setresuid error");

    printf("parent: forking\n");
    // emit buffered messages before forking.
    fflush(stdout);
    fflush(stderr);

    pid = fork();
    if (pid == 0) {
        // The child.
        printf("child: forked\n");
        // Change the effective user to root.
        if (seteuid(root) < 0)
            perror("child: seteuid error");
        // Get user info to use in group calls
        struct passwd* pPrivPasswd = getpwuid(root);
        if (pPrivPasswd == NULL)
            printf("child:failed to load root passwd data\n");
        // init supplemental groups
        if (initgroups(pPrivPasswd->pw_name, pPrivPasswd->pw_gid) < 0)
            perror("child: initgroups error");
        printf("child: done\n");
    } else {
        // The parent.
        printf("parent: waiting\n");
        terminated = wait(&wstatus);

        printf("parent: done\n");
    }
    return(0);
}
```

_Using an Apple M1 machine_, In a directory containing `Dockerfile` and `forkandinit.c`:

```shell
# build for x86 and run
docker build . -t test/forkandinit --platform Linux/amd64
docker run test/forkandinit
```

This gives the following output (note the initgroups error):

```shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
parent: dropping privileges, forking, and restoring privileges:
parent: forking
child: initgroups error: Operation not permitted
child: forked
child: done
parent: waiting
parent: done
```

Building and running without the `--platform Linux/amd64`, or building and running on x86 hardware, the run succeeds with no error. Something seems to be wrong with the child process privileges under emulation.

**Comment by stephen-turner** [comment]
Thank you for the detailed bug report, but I think it should probably be reported to qemu. We regard (and document) emulation as "best effort", and consider it a transient solution until the image can be compiled for the target architecture.
