### ISSUE TITLE
Stick to bottom switch doesn't work

### ISSUE THREAD

**Issue by aleksanderacai** [docker/for-mac#6107]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

The logs stops spamming console, the view should stop at place when we switched "stick to bottom" or where we went by scrolling mouse

### Actual behavior

View keeps being spammed with messages, there is no way to analyse anything.

### Information

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.1.0 (69386)

### Steps to reproduce the behavior

  1. Download 4.1.0 (69386) Docker Desktop for Mac
  2. Run some heavy log spamming docker image like gitlab/gitlab-ce:latest according to its documentation
  3. Enter into logs view of above running container
  4. Turn off "stick to bottom" option

**Comment by bacheson** [comment]
this still doesn't work ... man this app is a garbage heap of bad ux and bugs

**Comment by FramnkRulez** [comment]
This is still happening in latest version of Docker Desktop (v4.9.0).  Is there any workaround?  It's nearly impossible to debug container logs on Mac because it keeps jumping back to the bottom any time a new log is added despite what the 'Stick to bottom' setting is.
