### ISSUE TITLE
Add ability to set environment variables for docker daemon

### ISSUE THREAD

**Issue by ottumm** [docker/for-mac#611]
I'd like to be able to use the awslogs driver with Docker for Mac, but I can't find any way to set the necessary `AWS_SHARED_CREDENTIALS_FILE` environment variable in the docker daemon. I asked in https://github.com/docker/docker/issues/25468#issuecomment-241576278 and was referred here.

For reference, I also filed a StackOverflow question on this: http://stackoverflow.com/questions/39047067/how-do-i-provide-credentials-to-the-docker-awslogs-driver-using-docker-for-mac

**Comment by KIVagant** [comment]
Any news or advices how to use environment variables or awslogs driver with Docker for Mac?

**Comment by YRM64** [comment]
Ottumm,

There are only a couple of supported values in the shared credential file:
https://docs.aws.amazon.com/cli/latest/topic/config-bars.html#the-shared-credentials-file

What you can do is:
https://docs.aws.amazon.com/AmazonECS/latest/.developerguide/using_awslogs.html#enable_
awslogs

1.  Enable the awslogs Log Driver for your containers.
2.  Create your log groups.
3.  Set available awslogs Log Driver Options.
4.  Specify a Log Configuration in your Task Definition.
5.  View awslogs Container Logs in CloudWatch Logs.

You need to be specific in highlighting the fact that the awslogs logging driver is available on your container instance when you commence the Amazon ECS Container Agent if you're not using the Amazon ECS-optimized AMI (at least version 1.9.0-1) of the ecs-init package) for your container instance(s).

There's a wealth of valuable information for you on this topic, including how to install the Amazon ECS Container Agent, creating your Log Groups, creating a Log Group with the AWS CLI, using the AWS Command-Line Interface User Guide, creating a Log Group in the Amazon ECS Console, using the AWS Log Driver, and much much more, all available at docs.aws.amazon.com.

**Comment by YRM64** [comment]
Ottumm,

There are only a couple of supported values in the shared credential file: https://docs.aws.amazon.com/cli/latest/topic/config-bars.html#the-shared-credentials-file

Visit, https://docs.aws.amazon.com/AmazonECS/latest/.developerguide/using_awslogs.html#enable_awslogs 

What You Can Do:

1. Enable the awslogs Log Driver for your containers.
2. Create your log groups.
3. Set available awslogs Log Driver Options.
4. Specify a Log Configuration in your Task Definition.
5. View awslogs Container Logs in CloudWatch Logs.

You need to be specific in highlighting the fact that the awslogs logging driver is available on your container instance when you commence the Amazon ECS Container Agent if you're not using the Amazon ECS-optimized AMI (at least version 1.9.0-1 of the ecs-init package) for your container instance(s).

There's a wealth of valuable information for you on this topic, including how to install the Amazon ECS Container Agent, creating your Log Groups, creating a Log Group with the AWS CLI, using the AWS Command-Line Interface User Guide, creating a Log Group in the Amazon ECS Console, using the AWS Log Driver, and much much more, all available at docs.aws.amazon.com.

**Comment by edevil** [comment]
I'm also interested in being able to pass environment variables. In this case it is for Google Cloud credentials used by the GCP log driver.

**Comment by j0hnm4r5** [comment]
This is still an issue. Docker for Mac does give you direct access to the daemon json config file (via the app's preferences), but there is no way to set environment variables from that file (as far as I can tell), and I also can't find any documentation similar to [this](https://stackoverflow.com/a/51357915/2543753), but for macOS.

**Comment by aetherical** [comment]
This is still a problem.

**Comment by angusfz** [comment]
After almost 4 years, the problem still existed
