### ISSUE TITLE
Docker desktop on M1 - qemu-system-aarch64 is running even when no arch64 container is running

### ISSUE THREAD

**Issue by dyeshurun** [docker/for-mac#6110]
I have Docker Desktop 4.3.2  installed on M1 and when I start it I immediately see that "qemu-system-aarch64"  is running, no container started whatsoever.
Is this how it is supposed to be? not only if there is a container with no compatiable binary?

**Comment by rmetzger** [comment]
I haven't looked at his in detail, but my assumption is that qemu is used to run a arch64 linux VM which runs docker (on x86 macs, this is done using hyperkit).
If you are running a x86 docker image, it'll run inside the arch64 linux VM using `qemu-x86_64`.

**Comment by stephen-turner** [comment]
@rmetzger is correct. We don't usually describe it this way because it's confusing, but there's an "outer" qemu that runs the VM where the docker engine and the containers run, as well as the "inner" qemus when we need to emulate a container of a non-native architecture.

**Comment by onmishkin** [comment]
I just was wondering the same thing as @dyeshurun and found this issue as a result of searching around. Thanks for the explanations. One more thing, out of curiosity: Why doesn't Docker for Mac on M1 use Hyperkit to run its arch64 Linux VM (as opposed to on x86 where it _does_ use Hyperkit)?

**Comment by rmetzger** [comment]
I guess because hyperkit itself doesn't support non-intel CPUs: https://github.com/moby/hyperkit#requirements
