### ISSUE TITLE
Docker hangs trying to start container (both amd64 and arm64), fixed by docker restart

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6114]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: amd64: 4D073710-26E7-4DA2-9AA5-BFC1A7A6397E/20211230214954 - arm64: E0801D1C-C895-4C7E-A3A1-1B030AACACEA/20211230215850

### Expected behavior

Docker shouldn't hang trying to run a container.

### Actual behavior

It hung every single time. Exact thing happened on two ddev test runners. And the behavior was fixed by docker restart.

I was able to step through the behavior, and it was trying a `/containers/6a4330d177db0f53aa2d5176f666950cd1de54afb61b183e02848b369c7af39a/start` and just hung during that call.

<img width="704" alt="rfay-mba2013-macos" src="https://user-images.githubusercontent.com/112444/147791284-fd3d3d71-7d97-4f99-ad60-a1269a4d35e6.png">

### Information

  - macOS Version: Big Sur and Monterrey
  - Intel chip or Apple chip: Both - I gave diagnostics for both
  - Docker Desktop Version: 4.3.1 and 4.3.2

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

It doesn't look like this is valid. At this time docker is up and running and `docker ps` works fine and I can do a `docker run` just fine.

```
testbot@rfay-m1-air bin % /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

### Steps to reproduce the behavior

I don't know how docker got into this state, but since it's happened on two test runners, I imagine it will happen again. I hope the diagnostics are useful

**Comment by stephen-turner** [comment]
Hi Randy, just a note that we did receive this and are looking at it.

**Comment by rfay** [comment]
I see this intermittently, it's definitely a thing. Happy to provide another diagnostic if needed. Just had to restart docker on M1 test runner.

**Comment by rfay** [comment]
Still happening in 4.6.0. It may not be a big deal for people who are just restarting their personal docker, but this hang means that automated tests use up the few resources there are, then have to be discovered and manually restarted. 

I would provide a new diagnostic... but diagnostic upload is broken right now.

**Comment by trungutt** [comment]
We release a fix https://desktop.docker.com/mac/main/amd64/76265/Docker.dmg, so please upload your diagnostic

**Comment by rfay** [comment]
Hi @trungutt - It's not clear whether you're saying that 4.6.1 has a fix or this problem or ... ? Is this a one-off release?

**Comment by trungutt** [comment]
Sorry @rfay for being unclear about that. We fixed the diagnostic upload in 4.6.1 (the above build). So you could upload diagnostic again to help us resolve the original issue

**Comment by rfay** [comment]
Yes, of course I'll do it next time I notice hung docker. Thanks for your work on this!

**Comment by trungutt** [comment]
Like mentioned in https://github.com/docker/for-mac/issues/6134#issuecomment-1078414393, could you please try out these builds to see if it helps? (Probably for the next time that docker hangs trying to run a container) I say that because it looks like these two issues are related

Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/76484/Docker.dmg
Mac M1: https://desktop-stage.docker.com/mac/main/arm64/76484/Docker.dmg

**Comment by rfay** [comment]
Installed the m1 version on m1 test runner.

**Comment by rfay** [comment]
@trungutt I should note that the newly introduced dialog box about the home directory is unexpected and obtrusive. 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/112444/160158797-96862c73-5765-448a-93e9-ae6d98bc64f7.png">

**Comment by stephen-turner** [comment]
That's been there for ages, I think. The problem is that if we don't say it, we get lots of bug reports like "why is Docker trying to read my Reminders?", when it was just because people explicitly shared everything with a container and then MacOS alerted them later.

**Comment by rfay** [comment]
@stephen-turner I don't believe this exact dialog box was there before. I have installed many, many times on all platforms.The key concern is: Does this block Docker Desktop until the "OK" is clicked? Because that can cause big surprises.

**Comment by stephen-turner** [comment]
@trungutt Has anything changed with this recently?

**Comment by rfay** [comment]
@trungutt I haven't seen the white dialog box yet, but here's a stuck/hung container: 358979A2-0D9F-4631-894B-EA8807C2A1EE/20220401183459

**Comment by alexdavliatov** [comment]
Nothing worked for me, except completely replacing 4.6.1 -> 4.5.0

**Comment by rfay** [comment]
I continue to see this in Docker Desktop 4.7.1, on a completely freshly build macOS M1 machine.

**Comment by rfay** [comment]
This problem or one like it seems to happen much more frequently on Docker Desktop 4.8.1. I'm having to reset docker desktop on M1 DDEV test runner very frequently on 4.8.1. 

358979A2-0D9F-4631-894B-EA8807C2A1EE/20220516150341

**Comment by rfay** [comment]
I'm seeing this in 4.8.2 - and it seems to be on attempt to delete an image.

358979A2-0D9F-4631-894B-EA8807C2A1EE/20220523233528

**Comment by stephen-turner** [comment]
Thanks, @rfay, we're looking at it.

**Comment by fredericdalleau** [comment]
@rfay the log provides several tracks, but hard to focus on one in particular.
How can I set up a ddev test runner?

**Comment by rfay** [comment]
I think you should just be able to do `make test` on a mac M1 (where it happens the most). There's nothing special about test runner, it just runs things a lot.

**Comment by rfay** [comment]
And thanks for looking at this!
