### ISSUE TITLE
Docker Deskop

### ISSUE THREAD

**Issue by three-old-coders** [docker/for-mac#6116]
can't add /dev to Resources/FILE SHARING, because it is a hidden dir and manual input is not possible

OR

how to add "/dev/tty.usbserial-xxxx" to docker as mount?

**Comment by pcjmfranken** [comment]
To toggle the visibility of hidden files and directories, use the <kbd>shift</kbd> + <kbd>command</kbd> + <kbd>.</kbd> (full stop/period) shortcut in the file picker window (works in any Finder window also).

**Comment by three-old-coders** [comment]
Correct, but /dev is still hidden

Von meinem iPhone gesendet

**Comment by pcjmfranken** [comment]
Right, apologies for the brainlag!

The `/dev` dir is actually a virtual disk that's mounted with the `nobrowse` option - causing it not to show up in Finder (see for yourself by running the `mount` command without params).

If you can find a way to have the system temporarily mount without this `nobrowse` option and reboot, it should be possible to select `/dev` from the UI. Not sure if other DIY ways exist.

**Comment by three-old-coders** [comment]
> 

No problem. Updated my initial question: In the very end I need access to "/dev/tty.usbserial-xxxx" any way to mount this to docker desktop mac?

**Comment by pcjmfranken** [comment]
Maybe a symlink to the tty placed in a directory that is browsable from Finder is worth a try: `ln -s "/dev/tty.usbserial-xxxx" "/path/on/docker/fileshare/settings/"`.

If this works at all, you will have to ensure the symlink is available every time you run the container on your system, and perhaps even recreate it after every reboot or USB device removal.

Last thing I can think of is figure out where the Docker Desktop settings are stored (likely in a plistfile somewhere), try to add the path there, and hope the Docker app and all related local stuff survives ;)
