### ISSUE TITLE
Hide docker from menubar

### ISSUE THREAD

**Issue by damiannmm** [docker/for-mac#6119]
All you need to do is delete/move the `Contents/Resources/Assets.car`. eg, rename it to `Contents/Resource/Assets.car.bak`.

In case the App icon is missing now (just like I did lost it after renaming the `Assets.car`), all you need to do is drag the `Contents/Resources/AppIcon.icns` to the App's properties. eg,

<img width="303" alt="Screen Shot 2022-01-03 at 1 42 22 PM" src="https://user-images.githubusercontent.com/1107336/147905086-3798de5f-5e90-4201-9144-192fe46cbe59.png">

---

Now it's clean, but still clickable.

<img width="244" alt="Screen Shot 2022-01-03 at 1 45 21 PM" src="https://user-images.githubusercontent.com/1107336/147905166-3f711062-20fe-4b40-8da7-757cf190c0ce.png">

Hopefully this solves #2272 and #4416

**Comment by stephen-turner** [comment]
Thanks, but I don't think it solves the problem if we just have an invisible icon but it still takes up space. What those other people want is for all the functionality to be available by other means.
