### ISSUE TITLE
Mac Apple M1 Max - gradle-docker-compose-plugin:0.7.1 version - Gives 8080 port issue

### ISSUE THREAD

**Issue by sanketpaga** [docker/for-mac#6121]
- [ Yes] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Container needs to be started

### Actual behavior
These ports of service XYZ are declared as exposed but cannot be found in NetworkSettings: 8080/tcp\n

### Information

  - macOS Version:Apple macOS Monterey
  - Intel chip or Apple chip:Apple M1 Max 
  - Docker Desktop Version: 4.3.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
If it's just a problem with this one container, it sounds like it's not a Docker bug and needs to be reported to the container author instead.
