### ISSUE TITLE
Downloading Docker 1.13.1 Error

### ISSUE THREAD

**Issue by mythaalshamsi** [docker/for-mac#6125]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: B97D859A-4EAB-4F43-95C4-33C581B3E0A4

### Expected behavior
I was expecting docker to open and run normally.

### Actual behavior
After downloading Docker version 1.13.1 from the following link: 
https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg
I try to open docker, but then a "fatal error" shows and asks me to do the diagnosis or exit. Could you please help me?
### Information

  - macOS Version: macOS Monterey version 12.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 1.13.1

### Steps to reproduce the behavior

  1. Download docker from https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg
  2. Open it

**Comment by lorenrh** [comment]
We cannot ensure that older versions work on newer machines. Please use a recent version of Docker Desktop, which will also include security fixes.
