### ISSUE TITLE
Feature Suggestion: Colorize the output of docker

### ISSUE THREAD

**Issue by tbrodbeck** [docker/for-mac#6126]
### Expected behavior
It would be great if docker would support colorized output. This is a similar suggestion to this repo: https://github.com/kubernetes/kubectl/issues/524.

Maybe it would be possible to include this binary? https://opensourcelibs.com/lib/docker-color-output

Thanks!

**Comment by lorenrh** [comment]
Hi there! Thanks for your report. This is for bugs, and problems in Docker Desktop. 

Would you mind opening this issue in [docker/roadmap](https://github.com/docker/roadmap) instead?

**Comment by tbrodbeck** [comment]
Allright!
