### ISSUE TITLE
M1 Mac: argv0 not preserved for x86-64 binaries

### ISSUE THREAD

**Issue by gaurav-narula** [docker/for-mac#6127]
**MIT Licensed**

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

x86-64 binaries running on Docker For Mac on M1 Macs should preserve argv0 when emulated in qemu using binfmt_misc.

### Actual behavior

Since binfmt_misc isn't configured to preserve argv0, applications which depend on it (like busybox) break

### Information

  - macOS Version: 12.1
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.3.2 (72729)

### Steps to reproduce the behavior

The examples demonstrate a script with a missing shebang that fails on an M1 Mac in an amd64 image

```Dockerfile
FROM --platform=linux/amd64 alpine:latest

RUN echo "echo foo" >> /tmp/a.sh && chmod +x /tmp/a.sh

ENTRYPOINT /tmp/a.sh
```

```
$ docker build -t bug .
$ docker run -it bug
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
a.sh: applet not found
```

While the same script succeeds running on a native image:

```Dockerfile
FROM --platform=linux/arm64 alpine:latest

RUN echo "echo foo" >> /tmp/a.sh && chmod +x /tmp/a.sh

ENTRYPOINT /tmp/a.sh
```

```
$ docker build -t bug .
$ docker run -it bug
foo
```

### Analysis

`busybox` invokes an `execve` syscall as a part of its retry mechanism to execute the file as a shell script (refer to source [here](https://git.busybox.net/busybox/tree/shell/ash.c#n8258)). The syscall is of the form

```c
execve("/bin/busybox", { "ash", "/tmp/a.sh", NULL }, envp);
```

The kernel executes `/bin/busybox` using binfmt_misc interpreter and overwrites argv0 because the `preserve-argv0` flag isn't set (documented [here](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html)).

Qemu has support for recognising binfmt's `preserve-argv0` feature since [v6.0.0](https://github.com/qemu/qemu/commit/6e1c0d7b951e19c53b8467e8bc4b71ee73a394ea). It however, depends on a linux kernel patch introduced in [kernel v5.12](https://github.com/torvalds/linux/commit/2347961b11d4079deace3c81dceed460c08a8fc1) (which uses `AT_FLAGS` to pass that information to qemu).

### Suggested solution

I reckon Docker for Mac ships with Qemu >= 6.1.0. The changes required to make this work are:

1. Adding the `P` flag while registering qemu as the interpreter
2. Backporting Laurent's kernel [patch](https://github.com/torvalds/linux/commit/2347961b11d4079deace3c81dceed460c08a8fc1) to Docker for Mac's kernel/Upgrading the kernel to >= 5.12

**Comment by StefanScherer** [comment]
Thanks for the detailed report.
@tonistiigi could you PTAL?

**Comment by tonistiigi** [comment]
I don't think we should rely on kernel backports for this. Maybe we can just patch the qemu to always expect `-P`. I think we do something similar for buildkit-embedded version https://github.com/tonistiigi/binfmt/tree/master/patches/buildkit-direct-execve-v6.1. Basically just default `-P` to always, on qemu side. Afaics `P` itself is supported by all old kernels, just there is no dynamic way to detect if it was used or not.

Another way would be to detect in https://github.com/tonistiigi/binfmt/blob/master/cmd/binfmt/main.go#L70 if kernel supports this dynamic switch. Then at least it would start working for the newer kernels. Not sure what would be the best way to do this(eg. is there a way to do it without actually registering a dummy emulator).

**Comment by tonistiigi** [comment]
Looking at that line I linked above it should probably work with:

```
docker run -it --rm --privileged tonistiigi/binfmt --uninstall qemu-x86_64
docker run -it --rm --privileged -e QEMU_PRESERVE_PARENT=1 tonistiigi/binfmt --install amd64
```

```
docker run -it --rm -e QEMU_ARGV0=1 ...
```

**Comment by gaurav-narula** [comment]
> Looking at that line I linked above it should probably work with:
> 
> ```
> docker run -it --rm --privileged tonistiigi/binfmt --uninstall qemu-x86_64
> docker run -it --rm --privileged -e QEMU_PRESERVE_PARENT=1 tonistiigi/binfmt --install amd64
> ```
> 
> ```
> docker run -it --rm -e QEMU_ARGV0=1 ...
> ```

Thanks for looking into this promptly @tonistiigi. I'm afraid the above doesn't work - `QEMU_ARGV0=1` overrides argv0 to `1` in this case instead of preserving it.

**Comment by tonistiigi** [comment]
> overrides argv0 to 1 in this case instead of preserving it.

Ah, of course. For some reason, I thought it was the bool to use the first arg. So I guess it can't be done without a code change. If you are on an updated kernel then just `-e QEMU_PRESERVE_PARENT=1` should be enough(if you are not then this will completely mess up the installation though).
