### ISSUE TITLE
Docker Desktop for Mac Apple Silicon - High Memory usage

### ISSUE THREAD

**Issue by dan-developer** [docker/for-mac#6128]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics

Diagnostic ID: B6C7567C-7B9A-4123-9F7E-200A817B4FAB/20220106174430

### Expected behavior

Use memory on demand and not "crazy". Is there any solution for this? (Obs, this is not only on MAC, when using hypervisor on Windows it was also worse than that).

### Actual behavior

Problem seems to be with qemu. And "Use new virtualization" does the same thing, too.

I did tests with a virtual machine I created with swift in Apple's new virtualization and it works perfectly, it uses what the system asks for, nothing more. I'm using Docker Destop as I need to survive and I don't have time to switch to something else at the moment.

Are there any fixes, patches, workarounds, anything that can explain this?

Here are the prints:

Just start the desktop docker and two projects.

![image](https://user-images.githubusercontent.com/10473169/148425393-43b2fec2-b349-42b4-9430-30041327c7e4.png)

![image](https://user-images.githubusercontent.com/10473169/148425501-3c1a67cd-7391-4ea4-94ff-511635094a7d.png)

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

Note: The VM has to be running as I'm working now and using everything I need.

![image](https://user-images.githubusercontent.com/10473169/148425998-85b68dad-ba54-4282-ae53-d2ca5b3e7a95.png)

### Steps to reproduce the behavior

  1. Have a Mac with BigSur or Monterey installed.
  2. Install Docker Desktop
  3. Start an alpine image whatever, it will happen. Wait...

Thank for your support.

**Comment by kamilgregorczyk** [comment]
I have the same issue, not also sure why docker for mack runs amd64 stuff, isn't it supposed to have now native arm64 support?
<img width="1005" alt="Zrzut ekranu 2022-01-18 o 10 41 47" src="https://user-images.githubusercontent.com/9266336/149911699-80e1456f-9767-4af3-aa9c-fcdc9fd00c44.png">

**Comment by dan-developer** [comment]
> I have the same issue, not also sure why docker for mack runs amd64 stuff, isn't it supposed to have now native arm64 support? <img alt="Zrzut ekranu 2022-01-18 o 10 41 47" width="1005" src="https://user-images.githubusercontent.com/9266336/149911699-80e1456f-9767-4af3-aa9c-fcdc9fd00c44.png">
> 
> ps. I'm not even running any containers

I gave up on docker and moved everything to minikube for development. The whole world is going this way. It is less expensive for any computer to run a lightweight VM with anything installed to manage containers than to use Docker Desktop. And they don't care about that.

**Comment by marcoscale98** [comment]
truly ridiculous. RAM occupancy grows linearly over time
<img width="1440" alt="Schermata 2022-05-10 alle 21 46 39" src="https://user-images.githubusercontent.com/43850400/168447557-0791ecd6-fb84-4001-8764-b6fd5b953544.png">
![Schermata 2022-05-11 alle 14 43 06](https://user-images.githubusercontent.com/43850400/168447560-b7f7cb06-cec8-4524-bd43-212ca49e8ad8.png)
