### ISSUE TITLE
In-app update downloads docker client for Intel CPU instead of M1

### ISSUE THREAD

**Issue by ikutelmakh-ml** [docker/for-mac#6130]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installed Docker 4 mac app during the update is installing the corresponding version of the app depends on the CPU (or previous installed)

### Actual behavior
When D4mac is installed on a laptop with an M1 chip after in-app update installs the version for Intel CPU
<img width="601" alt="docker_update" src="https://user-images.githubusercontent.com/81684111/148839937-1e28caea-d0ee-42a1-a669-91515bd4055a.png">

### Information

  - macOS Version: 11.6.2
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.3.2 (72729)

### Steps to reproduce the behavior

  1. Install previous version of the desktop app on M1 chip
  2. Inside of the app check for the updates and update it
  3. Start updated app and check the error

**Comment by thejprice** [comment]
Same issue for me. Happened only after updating.
