### ISSUE TITLE
Fatal error while running docker 17.09 for the first time after installing 

### ISSUE THREAD

**Issue by lilmonk3y** [docker/for-mac#6131]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 614CE25C-8F01-4C62-8B75-1BBBB26E7C63

### Expected behavior
Install docker 17.09.1-ce-mac42 (downloaded from [docker archive](https://docs.docker.com/desktop/mac/release-notes/archive/#docker-community-edition-17091-ce-mac42-2017-12-11)) and then run the application. 

### Actual behavior
After dragging the app to applications folder and given the needed privilegies, the app failed with fatal error:

> com.docker.osx.hyperkit.linux failed to start
> Exit code 1

and after diagnostic report shows error on: 
**[ERROR]  driver.amd64-linux com.docker.driver.amd64-linux is not running**

### Information
Previous of this I have been using the[ lastest version of Docker](https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-amd64) but now I need to use this version. For that I uninstall that version using the troubleshotting>uninstall.
  - macOS Version: osX Big Sur 11.4
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 17.09.1-ce-mac42

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

> Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
> macOS: version 11.4 (build: 20F71)
> logs: /tmp/614CE25C-8F01-4C62-8B75-1BBBB26E7C63/20220111-181220.tar.gz
> failure: com.docker.vpnkit is not running
> [OK]     db.git
> [OK]     vmnetd
> [OK]     dns
> [ERROR]  driver.amd64-linux com.docker.driver.amd64-linux is not running
> [OK]     virtualization VT-X
> [OK]     app
> [ERROR]  moby
>          /Users/_user_/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
> [OK]     system
> [OK]     moby-syslog
> [ERROR]  db
>          Connection refused (ECONNREFUSED) connecting to /Users/_user_/Library/Containers/com.docker.docker/Data/s40: check if service is running
>          com.docker.db is not running
> [OK]     env
> [OK]     virtualization kern.hv_support
> [ERROR]  slirp
>          Unexpected error ((Failure
>   "Error connecting socket to 9p endpoint unix:/Users/_user_/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/_user_/Library/Containers/com.docker.docker/Data/s51
>          com.docker.vpnkit is not running
>          slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
> [ERROR]  osxfs
>          com.docker.osxfs is not running
> [OK]     moby-console
> [OK]     logs
> [ERROR]  docker-cli
>          Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
>          Connection refused (ECONNREFUSED) connecting to /Users/_user_/Library/Containers/com.docker.docker/Data/s60: check if service is running
>          docker ps failed
> [OK]     menubar
> [OK]     disk

### Steps to reproduce the behavior

  0. Delete all data from previous Docker instalations. 
  1. Download 17.09.1-ce-mac42 from docker archive.
  2. Drag and drop it on Applications folder.
  3. Enter password to give privilegies.
  4. Wait while docker starts.
  5. See the error.

**Comment by stephen-turner** [comment]
Sorry, we're not going to look into a version that's over four years old, but I wouldn't be surprised if it's not compatible with newer versions of MacOS.

**Comment by lilmonk3y** [comment]
Ok, I understand. :)
