### ISSUE TITLE
failed to create new OS thread (have 2 already; errno=22) with --platform linux/amd64

### ISSUE THREAD

**Issue by lflorent** [docker/for-mac#6137]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CD89DDF1-5DF9-4B62-A6CF-88A2A7B38242/20220116205359

### Expected behavior

Run successfully `linux/am64` containers of old services (`mysql:5.x`, `elasticsearch:1.x` ...) on `arm64` (Apple M1)

### Actual behavior

Failed with the error :

```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x524da0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82002a000, 0xc820039fc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820024770 sp=0xc820024768
runtime.main()
	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
```

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? No, see 
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles FTW.
` $ docker run --platform linux/amd64  -d mysql:5.5`
` $ docker run --platform linux/amd64  -d elasticsearch:1.5`

  - macOS Version: 12.0.1
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
```

### Steps to reproduce the behavior

```
% docker run --platform linux/amd64  -d mysql:5.5
2b046c4819afb41f078371b7f1ac6484d6b0fe471bed9793d342353e2e1941d6
% docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
% docker logs  2b0                                                              
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x524da0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82002a000, 0xc820039fc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820024770 sp=0xc820024768
runtime.main()
	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
```

I know there is similar closed issue (due to inactivity) here https://github.com/docker/for-mac/issues/6083 (and on stackoverflow) where @stephen-turner answered 

> Unfortuantely running under emulation is best-effort only. Some containers simply don't run successfully under emulation and the only fix is to use an Arm version of the container.

But unfortunately there is no ARM version for old containers and if possible  I would like to have a little bit more informations about the exact source of this error where the stack trace error talk about /usr/local/go/... code. 

I'm not sure but this golang error  is not a qemu error here, or maybe a  docker component linked to qemu ... ? 

If this is a qemu error is there a way to understand where the emulation failed ?

Thanks in advance for your help.

**Comment by alessiabragagnolo** [comment]
Have you tried to update the version of mysql image to 5.7.34?

**Comment by lflorent** [comment]
You're right ! I have tried the mysql:5.7 official and it works with --platform=linux/amd64 flag.

In the meantime, I manage to run the mysql:5.5 and elasticsearch:1.5 linux/amd64 images with [abiosoft/colima ](https://github.com/abiosoft/colima) ... but I would have liked to understand why Docker Desktop does not succeed where the others succeed ...

**Comment by logoff** [comment]
This happens in many other images. At least the same error is produced in `mongo:2.6`. I know I may use an updated version of such an old image, but there is a deeper issue for sure.

**Comment by telmopmota** [comment]
Issue still happening on Docker Desktop Version 4.8.1 (78998). Tried with elasticsearch:5.6 image.

```
% docker run --platform linux/amd64 -d elasticsearch:5.6
8136fdebffafc52ff8e6e364879bbe1b8d8c38dd8570a8a69916606210b5f15d

% docker ps                                                           
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

% docker logs 813                                       
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x4cb21f, 0x9)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420026000, 0xc420035fc0)
        /usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
        /usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
        /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420020768 sp=0xc420020760
runtime.main()
        /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200207c0 sp=0xc420020768
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200207c8 sp=0xc4200207c0
```

**Comment by jshields-squarespace** [comment]
Hmm, guess that doesn't reopen the issue.

**Comment by nicks** [comment]
on looking at the history of this, I think it's correct to close this as a duplicate of https://github.com/docker/for-mac/issues/6083. As Stephen pointed out there, this may simply not fixable for many containers.

I think the better path forward is to make sure you're running ARM images on M1. That will have lots of other benefits too. For popular images. If there are specific images you need under ARM, please file a feature request for those specific images (e.g., for mysql, it's here - https://github.com/docker-library/mysql)

**Comment by jshields-squarespace** [comment]
Thanks for taking another look and sharing your thoughts, Nick.

**Comment by Dream-MG** [comment]
Facing same issue with mysql. Tried updating the version to 5.7.34, getting the same error .

**Comment by t0yohei** [comment]
I resolved this issue by using mysql v5.7.29 or later versions.

**Comment by sushrutt12** [comment]
For MacOS with M1 chip using mariadb use `docker pull mariadb:10.6.4-focal`

**Comment by fineGos** [comment]
New elasticsearch versions are not worked with colima. Also it doesn't print any error. I tried 8 and 5 but both are not working.
Only 1.5 is working but it has lot of drawback
