### ISSUE TITLE
Docker on OSX Sierra: "Bad response from Docker engine."

### ISSUE THREAD

**Issue by robertoschwald** [docker/for-mac#614]
### Expected behavior
docker run works

### Actual behavior
"docker: Error response from daemon: Bad response from Docker engine."

### Information

Diagnostic ID: 8D23A7AF-1205-4382-884C-B881687F327E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/xxx/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/8D23A7AF-1205-4382-884C-B881687F327E/20160914-073226/qemu-img-check.stdout 2> /tmp/8D23A7AF-1205-4382-884C-B881687F327E/20160914-073226/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Just installed Docker on Sierra. Received error ""failed to update machine migration state" as many others on install. Started the installer again and Docker runs. 

But as soon as I perform
"docker run -d -p 80:80 --name webserver nginx", I get the error stated above.

**Comment by robertoschwald** [comment]
Now using the beta channel. Works there.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
