### ISSUE TITLE
"Skip this update" button hasn't worked in several versions

### ISSUE THREAD

**Issue by jrcasso** [docker/for-mac#6144]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When I click "Skip this update", I expect the dialog box to close.

### Actual behavior

Nothing happens, and the dialog box remains open. Sometimes I just don't want to stop all of my running containers for a small update.

### Information
  - Is the problem new? No. This has happened for multiple versions, but I've only now gotten annoyed by it.
  - Did the problem appear with an update? Yes, it used to work. Not sure when it happened.
  - macOS Version: 12.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.3.2

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

`"check" is not valid command.` followed by usage information. Do we mean `check-hypervisor` (which outputs nothing)?

### Steps to reproduce the behavior

Have Docker for Desktop (Mac) and attempt to `Skip this update` for 4.3.2

**Comment by mat007** [comment]
Closing this issue as the button has been removed now.
There is a checkbox in the Settings to disable updates entirely instead.
