### ISSUE TITLE
Docker Restored from MacOS Time Machine - Containers are gone

### ISSUE THREAD

**Issue by netomarchiori** [docker/for-mac#6146]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 76E666AD-BE1F-44C0-B281-0911A02D4A83/20220122132226

### Expected behavior

With "Include VM in Time Machine backups" checked in Docker,  Time Machine Backup and Restore would move my VM along with all containers, images and volumes to my new machine.

### Actual behavior

Docker.raw file is moved to the new machine, however Docker Desktop Containers, Images and Volumes list is empty

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No
  
  - macOS Version: Mac OS Monterey 12.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.4.2 (73305)
  - Docker Engine: 20.10.12

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

  1. Open Docker Preferences
  2. Select the box "Include VM in Time Machine backups"
  3. Close Docker to make sure its not running
  3. Run a fresh Time Machine on a clean HD
  4. On the new Mac, restore from your Time Machine backup
  5. Make sure Docker.raw is located at ~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw as it should
  6. Open Docker
  7. Check for the Containers, Images and Volumes. List is empty.

**Comment by joshhopkins** [comment]
It appears `Docker.raw` wasn't backed up in my case at all. Could someone from Docker please clarify what "Include VM in Time Machine backups" is meant to do, and if this is indeed a bug?
