### ISSUE TITLE
Docker for Mac crashes and forced to reset to original settings

### ISSUE THREAD

**Issue by jonathan-major** [docker/for-mac#615]
and lost my local env. twice tonight and at least once a week since switching over to new tool (for mac).

### Expected behavior
not crash
### Actual behavior
crashing
### Information

Diagnostic ID: 1C2531AD-B7A1-4011-B179-BCAA878FD07A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in 1C2531AD-B7A1-4011-B179-BCAA878FD07A/20160831-223739.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: VM: 2016-08-29 15:23:06 +0000 UTC daemon.info vsudd: Connection 63 to: 2376 from: 00000000
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=61b1fe3b-95ed-4122-852f-85926f0354c7,path=/Users/jonathanmajor/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/jonathanmajor/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: Interface will have uuid 61b1fe3b-95ed-4122-852f-85926f0354c7
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: Connection established with MAC=c0:ff:ee:c0:ff:ee and MTU 1500
Aug 29 08:23:06 JMs-MacBook-Pro Docker[com.docker.driver.amd64-linux][24631] <Notice>: virtio-9p: initialising path=/Users/jonathanmajor/Library/Containers/com.docker.docker/Data/s40,tag=db
```

@ijc25 will it be fixed in Beta28?

**Comment by ijc25** [comment]
@samoht there are fixes in Beta27 which fix this for many people. There are some extra ones in Beta28 but those seem to hit folks much less frequently.
