### ISSUE TITLE
Docker for Mac is not respecting $DOCKER_CONFIG env

### ISSUE THREAD

**Issue by Tony-Sol** [docker/for-mac#6150]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: https://docker-pinata-support.s3.amazonaws.com/incoming/3/00A0BABA-AAC4-423A-97E4-C77D953FF23F/20220125213503.zip

**Issue https://github.com/docker/for-mac/issues/2635 is still relevant**

### Expected behavior
Docker configuration files places by DOCKER_CONFIG path
### Actual behavior
Docker configuration files still places in $HOME/.docker
### Information

  - macOS Version: 12.1 (21C52)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```
### Steps to reproduce the behavior

  1. Quit from Docker Desktop
  2. Place into ~/.zshrc
```shell
export XDG_CONFIG_HOME="${HOME}/.config"
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
```
  2. Delete ~/.docker directory
  3. Start Docker Desktop
  4. See that ~/.docker appears

**Comment by Tony-Sol** [comment]
If open Docker via Terminal, it creates "${XDG_CONFIG_HOME}/docker" directory, which contains only meta.json
```
$ tree -a .config/docker
.config/docker
└── contexts
    └── meta
        └── fe9c6bd7a66301f49ca9b6a70b217107cd1284598bfc254700c989b916da791e
            └── meta.json

3 directories, 1 file
```

**Comment by stattenf** [comment]
FWIW, applications on macOS don't launch with environment variables from any of the various shell initialization files, because on macOS applications aren't launched as children of any shell.  The system itself insures that various environment variables are set, but there's no good way to cause it to do the equivalent of sourcing a shell config file first.
