### ISSUE TITLE
Is there a way to disable running x86_64 containers on M1?

### ISSUE THREAD

**Issue by Noksa** [docker/for-mac#6154]
How can I disable this feature?
I mean if there is no image for arm64 I want to get an error instead of pulling/running it using x86_64 arch.
Thanks.

**Comment by tonistiigi** [comment]
```
docker run --rm --privileged --pid=host tonistiigi/nsenter -t 1 -m sh -c 'echo -1 > /proc/sys/fs/binfmt_misc/qemu-x86_64'
```

**Comment by Noksa** [comment]
@tonistiigi 
But if I change my mind, how can I enable it again? 😄 

Thanks a lot!

**Comment by tonistiigi** [comment]
You can just restart Docker Desktop and it will restore itself.

Without restart probably easiest to install again using an external image. For example https://github.com/tonistiigi/binfmt#installing-emulators

**Comment by Noksa** [comment]
Thanks!
