### ISSUE TITLE
Network: ping: bad address 'github.com' && curl: (6) Could not resolve host: github.com

### ISSUE THREAD

**Issue by mahnunchik** [docker/for-mac#6156]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3F39388A-D23C-43DE-99DF-8AD9FC8829F8/20220202174342

### Expected behavior

`ping` and `curl` commands works as expected inside alpine container.

### Actual behavior

Several first launches of `ping` and `curl` commands fails. After one success the next launches are success too.

### Information

  - macOS Version: 12.1
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version: 4.4.2 (73305)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

### Steps to reproduce the behavior

  1. `docker run -it alpine:3.15.0 sh`
  2. `ping github.com`
  3. ping: bad address 'github.com' 

To reproduce with curl:

  1. `docker run -it alpine:3.15.0 sh`
  2. `apk add curl`
  3. `curl github.com`
  4. curl: (6) Could not resolve host: github.com

**Comment by mahnunchik** [comment]
The second or third run of the ping command succeeds.

```bash
docker run -it alpine:3.15.0 sh
/ # ping github.com
ping: bad address 'github.com'
/ # ping github.com
PING github.com (140.82.121.3): 56 data bytes
64 bytes from 140.82.121.3: seq=0 ttl=37 time=73.100 ms
64 bytes from 140.82.121.3: seq=1 ttl=37 time=61.077 ms
```

**Comment by mahnunchik** [comment]
Affected by issue too:

* macOS Version: 12.2
* Intel chip or Apple chip: Apple M1 Pro
* Docker Desktop Version: 4.3.0 (71786)

**Comment by imamfzn** [comment]
i also experienced with this issue (bad adress github.com on ping) on my docker desktop for mac 4.5.0, my workarround is by add the google dns on docker engine configuration, like:

```json
  {
    "dns": [
      "8.8.8.8",
      "8.8.4.4"
    ]
  }
```

**Comment by mahnunchik** [comment]
I'd like to confirm, it was DNS issue.

**Comment by abdil1234** [comment]
thanks @imamfzn that solve my problem
