### ISSUE TITLE
Docker for mac m1 chip doesn't launch after installation

### ISSUE THREAD

**Issue by Abdo-93** [docker/for-mac#6158]
My issue is very simply yet frustrating. I was recently issued a new mac using m1 chip and upon trying to setup docker, the application doesn't start after installing. I have tried uninstalling and installing it again but with no avail.

**Comment by kiilivi** [comment]
I have the same problem. Docker daemon isn't running. I started a thread in Docker desktop forum about this issue few days ago.
https://forums.docker.com/t/cannot-get-docker-working-in-macbook-pro-m1/120810

**Comment by kiilivi** [comment]
I finally managed to get it running! I removed the installation and ran these commands:

```
rm -rf ~/Library/Group\ Containers/group.com.docker
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/.docker
```

I noticed that .docker directory was owned by root user, so I had to use sudo to remove it. Maybe it was the problem?

**Comment by Abdo-93** [comment]
Thank you so much for sharing this link! I am glad to know I wasn't alone! Happy coding!

**Comment by barats** [comment]
> I finally managed to get it running! I removed the installation and ran these commands:
> 
> ```
> rm -rf ~/Library/Group\ Containers/group.com.docker
> rm -rf ~/Library/Containers/com.docker.docker
> rm -rf ~/.docker
> ```
> 
> I noticed that .docker directory was owned by root user, so I had to use sudo to remove it. Maybe it was the problem?

thanks a lot for this, it saved MY LIFE.

**Comment by Greg15153** [comment]
Had same issue. Docker was working for a bit and then when I changed the resources the VM got stuck in a stopped state. Nothing I did worked. Uninstalling, reinstalling, factory reset (it did nothing but prompt). Deleting those 3 folder paths unblocked me and VM started up.
