### ISSUE TITLE
Docker Desktop doesn't run

### ISSUE THREAD

**Issue by seyoung755** [docker/for-mac#6159]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:
Diagnostics ID:     689C94C8-0C10-4868-99CA-A833A15235F4/20220207051718 (uploaded)

### Actual behavior

When I try to run Docker desktop, I get the error message.

![image](https://user-images.githubusercontent.com/54302155/152732721-3f6e551c-3763-4ec3-9cc5-26d3cd034208.png)

### Information

  - macOS Version: 12.2
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.4.2

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Please investigate the following 1 issue:

1 : The test: is the application running?
    Failed with: Docker is not running

Is the Docker Desktop application running?

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Daisuke-sama** [comment]
I have the same issue - it cannot start and it looks like this

https://user-images.githubusercontent.com/16666335/152811255-bcc363cd-a0f2-4532-b0bf-c9bddd35b041.mov


Also, I completely cleared my previous docker installation.

**Comment by Daisuke-sama** [comment]
Hey, bro!
Finally, I have resolved that with help https://github.com/docker/for-mac/issues/6158 !!

**Comment by seyoung755** [comment]
Really appreciated to it!!!! I have resolved the problem.
