### ISSUE TITLE
Docker for Mac: 1.12.1-beta25 cannot startup under latest macOS GM macOS Build 16A322

### ISSUE THREAD

**Issue by smoothdvd** [docker/for-mac#616]
```
Diagnostic ID: 0537DE15-DDCF-4E2F-BFC9-2CCB52373D1C
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A322)
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
Seems related to #119

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
