### ISSUE TITLE
Using Mac's "Migration Assistant" causes Docker to fail to start until Group Containers is manually deleted

### ISSUE THREAD

**Issue by kimskimchi** [docker/for-mac#6164]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Migration Assistant installation of Docker should work out of the box.

### Actual behavior
If home directory is not the same (eg. User changes from `rose` to `rosy`), Docker daemon fails to start.

### Information

  - macOS Version: **Monterey 12.2**
  - Intel chip or Apple chip: **Apple chip**
  - Docker Desktop Version: any, used latest as of now:
 ```
 Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce the behavior

  1. In a new Mac (Mac2), create a user with a different home directory (eg. rosy) than the original (eg. rose). 
  2. Use Apple's Migration Assistant from Mac1 to Mac2, and let it auto install Docker in Mac2. 
  3. Docker daemon will now fail to start. 
      - Docker Desktop will fail with 
         - on the UI: `Error invoking remote method 'desktop-go-backend': Error: {"message":"no such file or directory"}`
         - as a pop up: `msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"`
      - Command line (eg. docker image ls) fails with 
         - `Error response from daemon: dial unix /Users/rosy/Library/Containers/com.docker.docker/Data/docker.raw.sock: connect: connection refused`
  4. Uninstalling and re-installing docker desktop does not fix the issue
  5. Deleting `Group Containers` directory,  (eg. `/Users/rosy/Library/Group Containers/`) fixes the issue.

**Comment by jacekadamczyknomtek** [comment]
You're my hero!!
