### ISSUE TITLE
"hosts" on daemon config has no effect

### ISSUE THREAD

**Issue by pcbl** [docker/for-mac#6165]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I want to access the [REST API](https://docs.docker.com/engine/api/v1.41/) from my Daemon running on MacOS.
I tried accessing it under http://localhost:2375 with no success.

Then I added the following json section under "Docker Engine" daemon config:
```json
  "hosts": [
    "tcp://0.0.0.0:2375"
  ],
```

Restarted Docker... It started and looked fine but still could not reach the RESTAPI 

Then I tried some other options, all without success...
```json
  "hosts": [
    "tcp://0.0.0.0:2375",
    "tcp://mypcname:2375",
    "unix://"
  ],
```

I even monitored the ports being used by docker while I was trying to get it working, but I could not see it getting any closer to the 2375 port which I was trying to get it going.

Then I saw this on the documentation:

[Docker Desktop Windows users can connect to the Docker Engine through a named pipe: npipe:////./pipe/docker_engine, or TCP socket at this URL: tcp://localhost:2375. ](https://docs.docker.com/desktop/faqs/)

How can I get access to the REST API on MacOS when using Docker Desktop?

Can anyone help me on that? What am I missing?

**Comment by thaJeztah** [comment]
I suspect the issue in that case is that while the daemon may be listening on those IP-addresses and ports, it's doing so within the VM that it's running in. Those ports are not mapped / forwarded to the macOS host, so won't be accessible there.

I should add a warning that exposing the Engine API over http without protection using TLS client authentication is dangerous; having access to the Engine API is equivalent to `root` permissions on the Daemon host. On Docker Desktop that's within the VM, but the daemon can still access files that are shared from your host with the VM. Implications of that are that a container could access the API (over http), which means that a compromised container can get `root` (and escape the container's boundaries). See http://docs.docker.com/go/attack-surface/

As to your question: 

> How can I get access to the REST API on MacOS when using Docker Desktop?

You can access the API using the unix socket at `/var/run/docker.sock`, for example;


```bash
curl --unix-socket /var/run/docker.sock 'http://localhost/v1.41/info'

{"ID":"NRCP:NVMV:2HKM:LDAF:D2OP:3J5U:TQN6:YVU3:XLQQ:YDMA:MVDH:AOEW","Containers":5,"ContainersRunning":2,"ContainersPaused":0,"ContainersStopped":3,"Images":103,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"],["userxattr","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":false,"KernelMemoryTCP":false,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":80,"OomKillDisable":false,"NGoroutines":182,"SystemTime":"2022-02-10T12:26:56.645028296Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"2","NEventsListener":5,"KernelVersion":"5.10.76-linuxkit","OperatingSystem":"Docker Desktop","OSVersion":"","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":4125478912,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"http.docker.internal:3128","HttpsProxy":"http.docker.internal:3128","NoProxy":"","Name":"docker-desktop","Labels":[],"ExperimentalBuild":true,"ServerVersion":"20.10.12","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"io.containerd.runtime.v1.linux":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"4c6s2gz5hohvvb6jaq4x3n3r5","NodeAddr":"192.168.65.3","LocalNodeState":"active","ControlAvailable":true,"Error":"","RemoteManagers":[{"NodeID":"4c6s2gz5hohvvb6jaq4x3n3r5","Addr":"192.168.65.3:2377"}],"Nodes":1,"Managers":1,"Cluster":{"ID":"yfnp7hq5vslms12b6b2xu3p0y","Version":{"Index":4443},"CreatedAt":"2021-10-26T10:58:27.885064662Z","UpdatedAt":"2022-02-10T04:18:28.125222001Z","Spec":{"Name":"default","Labels":{},"Orchestration":{"TaskHistoryRetentionLimit":5},"Raft":{"SnapshotInterval":10000,"KeepOldSnapshots":0,"LogEntriesForSlowFollowers":500,"ElectionTick":10,"HeartbeatTick":1},"Dispatcher":{"HeartbeatPeriod":5000000000},"CAConfig":{"NodeCertExpiry":7776000000000000},"TaskDefaults":{},"EncryptionConfig":{"AutoLockManagers":false}},"TLSInfo":{"TrustRoot":"-----BEGIN CERTIFICATE-----\nMIIBaTCCARCgAwIBAgIUG2Xrx2adLYSNWQEM5aJ7zDlPPTowCgYIKoZIzj0EAwIw\nEzERMA8GA1UEAxMIc3dhcm0tY2EwHhcNMjExMDI2MTA1MzAwWhcNNDExMDIxMTA1\nMzAwWjATMREwDwYDVQQDEwhzd2FybS1jYTBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABEjYflYUwyqa7lm9lpRFEAka1pZ+3PNfRoFvaGxycV/7SFWDLY5vWLsZDiFM\nl7NEW8dBsgL1Ao//KUAaruWROpajQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMB\nAf8EBTADAQH/MB0GA1UdDgQWBBSM8l2NBPzT73ExwJ2dhkgqPMU4oTAKBggqhkjO\nPQQDAgNHADBEAiAo8qqRYDtUZQ0n2wn4cF+nr95hJoTjfX47AWJkLqaNyAIgdI8C\nijnSuS3W7tgFkK7Oic8MJsYO7e1wMQlCQyTA5lg=\n-----END CERTIFICATE-----\n","CertIssuerSubject":"MBMxETAPBgNVBAMTCHN3YXJtLWNh","CertIssuerPublicKey":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESNh+VhTDKpruWb2WlEUQCRrWln7c819GgW9obHJxX/tIVYMtjm9YuxkOIUyXs0Rbx0GyAvUCj/8pQBqu5ZE6lg=="},"RootRotationInProgress":false,"DefaultAddrPool":["10.0.0.0/8"],"SubnetSize":24,"DataPathPort":4789}},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"7b11cfaabd73bb80907dd23182b9347b4245eb5d","Expected":"7b11cfaabd73bb80907dd23182b9347b4245eb5d"},"RuncCommit":{"ID":"v1.0.2-0-g52b36a2","Expected":"v1.0.2-0-g52b36a2"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=default","name=cgroupns"],"Warnings":null}
```

Note that the `http://localhost` hostname is not important (it's connecting over a unix socket, and the hostname is only to make for a valid URL, so `http://putwhateveryouwanthere/v1.41/info` would also work

**Comment by pcbl** [comment]
Hi @thaJeztah, Many thanks for your claryfing answer! Indeed by using the curl you sent I can see the proper response...

I understand what you mean. In this case, as I am using a MAC with a Apple chip(M1) and, as far as I could read, Docker Desktop on Mac(M1) uses [QEMU](https://docs.docker.com/desktop/mac/apple-silicon/) under the hood. And on that case, the QEMU running emulation is actually 'NOT* exposing the 2375 port to my MAC(Host), right? Do you know if that would be something possible to achieve?

Regarding your rightful concerns about security, this is really no issue as this relates to communication between host and guest OS, not being available to any external/public access. So Security on this case play no big role.

What I am trying to achieve is:
1. Run Docker Desktop on MAC OS
2. Connect to the daemon(running on MAC) from a VM over Parallels(MAC is the Host, Windows is the Guest)

To do that, after setting the hosts on MAC:
```json
  "hosts": [
    "tcp://0.0.0.0:2375"
  ],
```

Then I have [docker engine](https://download.docker.com/win/static/stable/x86_64/) on the Windows VM and try to start like this:
`.\dockerd.exe -H tcp://MacOSIpOrName:2375 --tls=false`

So far I got no success. Would be really nice to get this working.

**Comment by thaJeztah** [comment]
Docker Desktop does not currently have an option to automatically map the port (also because we don't want to _encourage_ doing so).

> this is really no issue as this relates to communication between host and guest OS, not being available to any external/public access. So Security on this case play no big role.

Yes, it can be fine in a secure environment; still, when publishing the port it will be accessible on your machine's external interface, and a container that may be exposed could still be used "as a proxy" to access it. (I'm trying to overly caution about this, as unfortunately, there's many people finding such examples, and not realising possible consequences 😅)

As to your use-case; you could probably run a container that bind-mounts the socket, and then runs `socat` to forward the port over tcp (haven't extensively tested it though!). For example, this is an alpine container with;

- the `/var/run/docker.sock` bind-mounted
- `-it` and `--rm` are here just for convenience (it runs in the foreground, and pressing `CTRL-C` will terminate it, and remove the container), you can use `-d` instead to run it in the background
- maps port 2375 of the container to port 2375 on the host
- it first installs `socat` (which is quick on alpine, but you could write a dockerfile for it and build an image)
- then runs `socat` to forward tcp on port 2375 to the socket

```bash
docker run \
    -it \
    --rm \
    --name=api-forwarder \
    -p 2375:2375 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    alpine sh -c 'apk add --no-cache socat && socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock'
```

When that container is running, you can access it over tcp;

```bash
curl 'http://localhost:2375/v1.41/info'
{"ID":"NRCP:NVMV:2HKM:LDAF:D2OP:3J5U:TQN6:YVU3:XLQQ:YDMA:MVDH:AOEW","Containers":6,"ContainersRunning":3,"ContainersPaused":0,"ContainersStopped":3,"Images":103,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"],["userxattr","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":false,"KernelMemoryTCP":false,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":89,"OomKillDisable":false,"NGoroutines":196,"SystemTime":"2022-02-10T13:33:59.987594016Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"2","NEventsListener":5,"KernelVersion":"5.10.76-linuxkit","OperatingSystem":"Docker Desktop","OSVersion":"","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":4125478912,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"http.docker.internal:3128","HttpsProxy":"http.docker.internal:3128","NoProxy":"","Name":"docker-desktop","Labels":[],"ExperimentalBuild":true,"ServerVersion":"20.10.12","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"io.containerd.runtime.v1.linux":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"4c6s2gz5hohvvb6jaq4x3n3r5","NodeAddr":"192.168.65.3","LocalNodeState":"active","ControlAvailable":true,"Error":"","RemoteManagers":[{"NodeID":"4c6s2gz5hohvvb6jaq4x3n3r5","Addr":"192.168.65.3:2377"}],"Nodes":1,"Managers":1,"Cluster":{"ID":"yfnp7hq5vslms12b6b2xu3p0y","Version":{"Index":4443},"CreatedAt":"2021-10-26T10:58:27.885064662Z","UpdatedAt":"2022-02-10T04:18:28.125222001Z","Spec":{"Name":"default","Labels":{},"Orchestration":{"TaskHistoryRetentionLimit":5},"Raft":{"SnapshotInterval":10000,"KeepOldSnapshots":0,"LogEntriesForSlowFollowers":500,"ElectionTick":10,"HeartbeatTick":1},"Dispatcher":{"HeartbeatPeriod":5000000000},"CAConfig":{"NodeCertExpiry":7776000000000000},"TaskDefaults":{},"EncryptionConfig":{"AutoLockManagers":false}},"TLSInfo":{"TrustRoot":"-----BEGIN CERTIFICATE-----\nMIIBaTCCARCgAwIBAgIUG2Xrx2adLYSNWQEM5aJ7zDlPPTowCgYIKoZIzj0EAwIw\nEzERMA8GA1UEAxMIc3dhcm0tY2EwHhcNMjExMDI2MTA1MzAwWhcNNDExMDIxMTA1\nMzAwWjATMREwDwYDVQQDEwhzd2FybS1jYTBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABEjYflYUwyqa7lm9lpRFEAka1pZ+3PNfRoFvaGxycV/7SFWDLY5vWLsZDiFM\nl7NEW8dBsgL1Ao//KUAaruWROpajQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMB\nAf8EBTADAQH/MB0GA1UdDgQWBBSM8l2NBPzT73ExwJ2dhkgqPMU4oTAKBggqhkjO\nPQQDAgNHADBEAiAo8qqRYDtUZQ0n2wn4cF+nr95hJoTjfX47AWJkLqaNyAIgdI8C\nijnSuS3W7tgFkK7Oic8MJsYO7e1wMQlCQyTA5lg=\n-----END CERTIFICATE-----\n","CertIssuerSubject":"MBMxETAPBgNVBAMTCHN3YXJtLWNh","CertIssuerPublicKey":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESNh+VhTDKpruWb2WlEUQCRrWln7c819GgW9obHJxX/tIVYMtjm9YuxkOIUyXs0Rbx0GyAvUCj/8pQBqu5ZE6lg=="},"RootRotationInProgress":false,"DefaultAddrPool":["10.0.0.0/8"],"SubnetSize":24,"DataPathPort":4789}},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"7b11cfaabd73bb80907dd23182b9347b4245eb5d","Expected":"7b11cfaabd73bb80907dd23182b9347b4245eb5d"},"RuncCommit":{"ID":"v1.0.2-0-g52b36a2","Expected":"v1.0.2-0-g52b36a2"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=default","name=cgroupns"],"Warnings":null}
```

Or connect to it with the `docker` CLI:

```bash
docker -H tcp://localhost:2375 version

Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
...
```
