### ISSUE TITLE
Cannot install symlinks in /usr/local/bin (stage 5)

### ISSUE THREAD

**Issue by gvastakis** [docker/for-mac#6168]
In a fresh instllation of Mac OS I cannot run Docker Desktop. I keep get the same error "Cannot install symlinks in /usr/local/bin (stage 5)".

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109 (uploaded)

### Expected behavior

Run Docker Desktop in Mac OS (Docker.app runs the first-time-install process and then opens).

### Actual behavior

Same Error message keeps on appearing whenever trying to start Docker.

<img width="579" alt="Screenshot 2022-02-11 at 2 15 32 PM" src="https://user-images.githubusercontent.com/5776654/153591301-564cca86-7e69-4542-b530-0905b4d3ea53.png">

<img width="743" alt="Screenshot 2022-02-11 at 2 16 17 PM" src="https://user-images.githubusercontent.com/5776654/153591344-b8fcd898-2472-43cd-be55-baeceefe45ba.png">

### Information

  - macOS Version: 12.2.1 
  - Intel chip or Apple chip: M1 PRO
  - Docker Desktop Version: 4.5.0 (74594)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109 (uploaded)

<img width="1077" alt="Screenshot 2022-02-11 at 2 28 18 PM" src="https://user-images.githubusercontent.com/5776654/153591468-a11d1acf-a8a2-4220-a191-fcf29155c3fe.png">

**Comment by gvastakis** [comment]
full diagnostics output :

`Gathering diagnostics for ID F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109 into /var/folders/zr/vl0t7kpd26lf8slwcdl3v3qc0000gn/T/F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109.zip.
This may take up to 15 minutes.
time="2022-02-11T14:21:09+02:00" level=info msg="Triggering Linux sysrq and log flushes via a unix socket: Library/Containers/com.docker.docker/Data/diagnosticd.sock" type=unixsock
time="2022-02-11T14:21:09+02:00" level=warning msg="/flush failed: Post \"http://unix/flush\": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: no such file or directory" type=unixsock
unable to trigger dns-forwarder diagnostics: Post "http://ipc/diagnostics": dial unix Library/Containers/com.docker.docker/Data/dns-forwarder.sock: connect: no such file or directory
time="2022-02-11T14:21:16+02:00" level=warning msg="Cannot get VM settings: Disk file not found" type=vmDisk



time="2022-02-11T14:22:37+02:00" level=info msg="Start gathering list of 98 elements (timeout=15m0s)" type=list
time="2022-02-11T14:22:37+02:00" level=info msg="Gathering DiagKit" type=list
time="2022-02-11T14:22:37+02:00" level=info msg="Gathering BackendGatherer" type=list
GET failed with Get "http://unix/forwards/list": dial unix Library/Containers/com.docker.docker/Data/backend.sock: connect: connection refused
time="2022-02-11T14:22:51+02:00" level=info msg="Gathering LifecycleServerGatherer" type=list
time="2022-02-11T14:22:58+02:00" level=info msg="Gathering ProxyAPIGatherer" type=list
time="2022-02-11T14:23:05+02:00" level=info msg="Gathering system" type=list
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [sw_vers -productVersion]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [sw_vers -buildVersion]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [uname -r]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [sysctl kern.boottime]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [sysctl hw.memsize]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [vm_stat]"
time="2022-02-11T14:23:05+02:00" level=info msg="Executing: [sysctl machdep.cpu]"
time="2022-02-11T14:23:05+02:00" level=info msg="Gathering ProcessGatherer" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering uname -a" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [uname -a]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering ps uax" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [ps uax]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering dmesg " type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [dmesg]"
time="2022-02-11T14:23:07+02:00" level=warning msg="[dmesg] exit status 1" type=cmd
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering id " type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [id]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering sysctl -a" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [sysctl -a]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering mount " type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [mount]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering df -h" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [df -h]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering launchctl print-disabled  (timeout 0s)system" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [launchctl print-disabled system]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering system_profiler SPHardwareDataType" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [system_profiler SPHardwareDataType]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering defaults read  (timeout 0s)/Library/Preferences/com.apple.alf.plist" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [defaults read /Library/Preferences/com.apple.alf.plist]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kextstat " type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [kextstat]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering ifconfig -a" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [ifconfig -a]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering netstat -ln" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [netstat -ln]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering netstat -mm" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [netstat -mm]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering netstat -nr" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [netstat -nr]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /etc/resolv.conf" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: /etc/resolv.conf" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /etc/hosts" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: /etc/hosts" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering scutil --dns" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [scutil --dns]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering scutil --nc  (timeout 0s)list" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [scutil --nc list]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering scutil --proxy  (timeout 0s)list" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [scutil --proxy list]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering system_profiler SPFirewallDataType" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [system_profiler SPFirewallDataType]"
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/version" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/version" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/version\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/info" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/info" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/info\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/containers/json?all=1" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/containers/json?all=1" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/containers/json?all=1\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/nodes" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/nodes" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/nodes\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/services" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/services" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/services\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering HTTP GET localhost /v1.24/networks" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="HTTP GET: localhost /v1.24/networks" type=http
time="2022-02-11T14:23:07+02:00" level=warning msg="Get \"http://localhost/v1.24/networks\": dial unix /var/run/docker.sock: connect: no such file or directory" type=http
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering docker context  (timeout 0s)ls" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [docker context ls]"
time="2022-02-11T14:23:07+02:00" level=warning msg="[docker context ls] exec: \"docker\": executable file not found in $PATH" type=cmd
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering docker context  (timeout 0s)inspect  (timeout 0s)default" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [docker context inspect default]"
time="2022-02-11T14:23:07+02:00" level=warning msg="[docker context inspect default] exec: \"docker\": executable file not found in $PATH" type=cmd
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering docker context  (timeout 0s)inspect  (timeout 0s)desktop-linux" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [docker context inspect desktop-linux]"
time="2022-02-11T14:23:07+02:00" level=warning msg="[docker context inspect desktop-linux] exec: \"docker\": executable file not found in $PATH" type=cmd
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering docker context  (timeout 0s)inspect  (timeout 0s)desktop-windows" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [docker context inspect desktop-windows]"
time="2022-02-11T14:23:07+02:00" level=warning msg="[docker context inspect desktop-windows] exec: \"docker\": executable file not found in $PATH" type=cmd
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering {\n  \"id\": \"F31605A5-28B3-437B-AB6D-987100F79C64\",\n  \"date\": \"2022-02-11 12:21:16.936111 +0000 UTC\"\n}\n" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="Could not get HyperKit version: fork/exec /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit: no such file or directory" type=collectInfo
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe pods" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe daemonset" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe replicaset" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace docker describe deployments" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe pods" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe daemonset" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe replicaset" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace kube-system describe deployments" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering VPNKit" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="Failed to Dial Library/Containers/com.docker.docker/Data/vpnkit.diag.sock: dial unix Library/Containers/com.docker.docker/Data/vpnkit.diag.sock: connect: no such file or directory" type=vpnkit
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering Library/Containers/com.docker.docker/Data/log/vm/**" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/vm" type=directory
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering Library/Containers/com.docker.docker/Data/log/host/**" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host" type=directory
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/.d7d25c71a00a2e835aecb9105f32b01ecead0ac0-audit.json" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/Docker.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/com.docker.backend.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/com.docker.desktop-extensions.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/com.docker.diagnose.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/electron-2022-02-10-23.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/electron-2022-02-11-09.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/electron-2022-02-11-10.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering: Library/Containers/com.docker.docker/Data/log/host/electron-2022-02-11-14.log" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/features-overrides.json" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/features-overrides.json not included" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /Library/Application Support/com.docker.docker/registry.json" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="/Library/Application Support/com.docker.docker/registry.json not included" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /Library/Application Support/com.docker.docker/access.json" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="/Library/Application Support/com.docker.docker/access.json not included" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/registry-access-managment-state.json" type=list
time="2022-02-11T14:23:07+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/registry-access-managment-state.json not included" type=file
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  version " type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  config get-contexts" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  config current-context" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  get nodes" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  get namespaces" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe nodes" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe pods" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  cluster-info dump" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe services" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering kubectl --context docker-desktop --namespace  describe storageclass,pv,pvc" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="kubernetes is disabled" type=kubectl
time="2022-02-11T14:23:07+02:00" level=info msg="Gathering log process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")" type=list
time="2022-02-11T14:23:07+02:00" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'process matches \".*[Dd]ocker.*\" || (process in {\"kernel\", \"launchservicesd\", \"taskgated-helper\"} && eventMessage contains[c] \"docker\")']"

time="2022-02-11T14:24:59+02:00" level=info msg="Gathering log eventMessage matches \".*[Ss]parkle.*\"" type=list
time="2022-02-11T14:24:59+02:00" level=info msg="Executing: [/bin/sh -c /usr/bin/log show --debug --info --style syslog --last 1d --predicate 'eventMessage matches \".*[Ss]parkle.*\"']"


time="2022-02-11T14:26:51+02:00" level=info msg="Gathering DarwinSyslog Sender = docker Docker Message = docker Docker" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [syslog -F $((Time)(JZ)) $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message -o -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker]"
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering Library/Containers/com.docker.docker/Data/vms/0/console-ring" type=list
time="2022-02-11T14:26:51+02:00" level=warning msg="Library/Containers/com.docker.docker/Data/vms/0/console-ring not included" type=file
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.driver.amd64-linux)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.hyperkit) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.hyperkit)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o qemu-system-aarch64) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o qemu-system-aarch64)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o qemu-system-aarch64)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.virtualization) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.virtualization)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.virtualization)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.osxfs) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.osxfs)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.backend) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.backend)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.backend)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.dev-envs) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.dev-envs)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.dev-envs)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o com.docker.vpnkit) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o com.docker.vpnkit)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering lsof -n -P -p $(pgrep -o vpnkit-bridge) (timeout 0s)" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Executing: [/bin/sh -c lsof -n -P -p $(pgrep -o vpnkit-bridge)]"
time="2022-02-11T14:26:51+02:00" level=warning msg="[/bin/sh -c lsof -n -P -p $(pgrep -o vpnkit-bridge)] exit status 1" type=cmd
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering osxfsGatherer" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Connecting to com.docker.osxfs"
time="2022-02-11T14:26:51+02:00" level=info msg="Querying com.docker.osxfs ExportState"
time="2022-02-11T14:26:51+02:00" level=info msg="Querying com.docker.osxfs MountState"
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering /tmp/spindump.txt" type=list
time="2022-02-11T14:26:51+02:00" level=info msg="Gathering: /tmp/spindump.txt" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering: /Users/yannos/Library/Group Containers/group.com.docker/DockerAppStderr.txt" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/already-enabled-features.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/already-enabled-features.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/dhcp.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/dhcp.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/features.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/features.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/http_proxy.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/Library/Group Containers/group.com.docker/http_proxy.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Group Containers/group.com.docker/settings.json" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering: /Users/yannos/Library/Group Containers/group.com.docker/settings.json" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/Library/Preferences/group.com.docker.plist" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/Library/Preferences/group.com.docker.plist not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering ls /Users/yannos/.docker /usr/local/bin /Library/PrivilegedHelperTools /Library/LaunchDaemons /Users/yannos/Library/LaunchAgents /Library/Application Support/Docker/DockerDesktop /Users/yannos/Library/Group Containers/group.com.docker /Users/yannos/Library/Containers/com.docker.docker /Applications/Docker.app" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="exit status 1" type=directorylist
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering Redacted /Users/yannos/.docker/config.json" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering: /Users/yannos/.docker/config.json" type=redacted-json
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering Redacted /Users/yannos/.docker/daemon.json" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering: /Users/yannos/.docker/daemon.json" type=redacted-json
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/.docker/canary.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/.docker/canary.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering /Users/yannos/.docker/features.json" type=list
time="2022-02-11T14:26:52+02:00" level=warning msg="/Users/yannos/.docker/features.json not included" type=file
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering HTTP GET localhost /fuse/time" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="HTTP GET: localhost /fuse/time" type=http
time="2022-02-11T14:26:52+02:00" level=warning msg="Get \"http://localhost/fuse/time\": dial unix Library/Containers/com.docker.docker/Data/lifecycle-server.sock: connect: no such file or directory" type=http
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering HTTP GET localhost /fuse/count" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="HTTP GET: localhost /fuse/count" type=http
time="2022-02-11T14:26:52+02:00" level=warning msg="Get \"http://localhost/fuse/count\": dial unix Library/Containers/com.docker.docker/Data/lifecycle-server.sock: connect: no such file or directory" type=http
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering HTTP GET localhost /fuse/filename" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="HTTP GET: localhost /fuse/filename" type=http
time="2022-02-11T14:26:52+02:00" level=warning msg="Get \"http://localhost/fuse/filename\": dial unix Library/Containers/com.docker.docker/Data/lifecycle-server.sock: connect: no such file or directory" type=http
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering HTTP GET localhost /fuse/calls" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="HTTP GET: localhost /fuse/calls" type=http
time="2022-02-11T14:26:52+02:00" level=warning msg="Get \"http://localhost/fuse/calls\": dial unix Library/Containers/com.docker.docker/Data/lifecycle-server.sock: connect: no such file or directory" type=http
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering fuseVolumeGatherer" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering fuseStacksGatherer" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering selfDiagnose" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="waiting for the result of self-diagnose"
time="2022-02-11T14:26:52+02:00" level=info msg="Gathering Library/Containers/com.docker.docker/Data/diagnosticd.sock" type=list
time="2022-02-11T14:26:52+02:00" level=info msg="Getting Linux Diagnostics via a unix socket: Library/Containers/com.docker.docker/Data/diagnosticd.sock" type=unixsock
time="2022-02-11T14:26:52+02:00" level=warning msg="/diagnostics failed: Get \"http://unix/diagnostics\": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: no such file or directory" type=unixsock
time="2022-02-11T14:26:52+02:00" level=info msg="All 98 gatherers finished" type=list
INFO[0352] Uploaded diagnostics to:  https://docker-pinata-support.s3.amazonaws.com/incoming/3/F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109.zip 


Diagnostics Bundle: /var/folders/zr/vl0t7kpd26lf8slwcdl3v3qc0000gn/T/F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109.zip
Diagnostics ID:     F31605A5-28B3-437B-AB6D-987100F79C64/20220211122109 (uploaded)
`

**Comment by jfacoustic** [comment]
For me, /usr/local/bin is a folder and I still get this error.  I've tried running chown, recreating the folder, and restarting my mac, but no luck.

**Comment by sjgd** [comment]
As mentioned there:
https://githubhot.com/repo/docker/for-mac/issues/5949

What worked for me what to delete `/usr/local/lib` instead of `/usr/local/bin`; and relaunch docker, then it succeeded to launch. 
`/usr/local/lib` was already existing and was a file, blocking docker from creating a subfolder inside.

**Comment by wxlund** [comment]
Thank you.  The above "sudo mv /usr/local/bin /usr/local/bin.old" worked for me as well.  Docker is running.
