### ISSUE TITLE
filesystem layer verification failed for digest sha256:

### ISSUE THREAD

**Issue by alierbas** [docker/for-mac#6182]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7E21E906-2B4E-40FE-BCAE-86BEE3C5AC6B/20220219173445

### Expected behavior
I started Docker and tried to pull the image but the image was not pulled.

### Actual behavior
latest: Pulling from library/ubuntu
bbf2fb66fa6e: Verifying Checksum 
docker: filesystem layer verification failed for digest sha256:bbf..........

### Information
  - macOS Version: 12.2.1 
  - Intel chip or Apple chip: M1 Chip
  - Docker Desktop Version:  4.5.0 (74594)

### Steps to reproduce the behavior
  1. Docker Install
  2. Pull the Image

**Comment by fntundi** [comment]
Is someone looking at this? This is an issue across platforms. I am experiencing the same issue when pulling images from quay.
