### ISSUE TITLE
cannot install symlinks in /usr/local/bin (Mac M1 pro)

### ISSUE THREAD

**Issue by jfacoustic** [docker/for-mac#6187]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features (Not applicable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F70DA72D-2CE8-495F-A1A5-7B7AC3B6F461/20220221205157

### Expected behavior
Docker desktop to start.

### Actual behavior
Popup with "cannot install symlinks in /usr/local/bin (stage 5)"

### Information

  - macOS Version: 12.2.1 
  - Intel chip or Apple chip: Apple (M1 Pro)
  - Docker Desktop Version: 4.5.0
  
 It seems like these symlinks already exist:
 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10293788/155026271-d17ede95-7a32-4237-9a04-8816a1c95202.png">

A recent, similar issue was reported here: https://github.com/docker/for-mac/issues/6168
I had tried @gvastaki's solution, `sudo mv /usr/local/bin /usr/local/bin.old,` however /usr/local/bin was already a directory.

This also seems to be the same issue: https://github.com/docker/for-mac/issues/5909.  The poster (@beerpig) closed the issue, but did not add a reason/fix.  

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
(Last 100 lines)

[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x48
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1, 0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0xa0
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d2cc00, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x40
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d2ca80, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x80
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100d2ca80, 0x1400035f960)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x90
[common/pkg/diagkit/gather/diagnose.Run(0x100d2ca80, 0x100d2cd80, {0x1400035fad8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x188
[main.checkCmd({0x140001b6010, 0x0, 0x0}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x114
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x378
[052:13:59:02.758][I] (6ccdaaea-6) 51beea50-diagnose-network C->S diagnosticsd GET /ping
[052:13:59:02.760][E] (6ccdaaea-6) 51beea50-diagnose-network C<-S NoResponse GET /ping (1.799292ms): Get "http://ipc/ping": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: no such file or directory
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:35 +0x1bc
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x48
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1, 0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0xa0
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d2cc00, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x40
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d2ca80, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x80
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100d2ca80, 0x1400035f960)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x90
[common/pkg/diagkit/gather/diagnose.Run(0x100d2ca80, 0x100d2cd80, {0x1400035fad8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x188
[main.checkCmd({0x140001b6010, 0x0, 0x0}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x114
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x378
[052:13:59:03.761][I] (6ccdaaea-7) 51beea50-diagnose-network C->S diagnosticsd GET /ping
[052:13:59:03.762][E] (6ccdaaea-7) 51beea50-diagnose-network C<-S NoResponse GET /ping (1.176792ms): Get "http://ipc/ping": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: no such file or directory
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:35 +0x1bc
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x48
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1, 0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0xa0
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d2cc00, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x40
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d2ca80, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x80
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100d2ca80, 0x1400035f960)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x90
[common/pkg/diagkit/gather/diagnose.Run(0x100d2ca80, 0x100d2cd80, {0x1400035fad8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x188
[main.checkCmd({0x140001b6010, 0x0, 0x0}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x114
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x378
[052:13:59:04.763][I] (6ccdaaea-8) 51beea50-diagnose-network C->S diagnosticsd GET /ping
[052:13:59:04.764][E] (6ccdaaea-8) 51beea50-diagnose-network C<-S NoResponse GET /ping (954µs): Get "http://ipc/ping": dial unix Library/Containers/com.docker.docker/Data/diagnosticd.sock: connect: no such file or directory
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:35 +0x1bc
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x48
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1, 0x100d2cc00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0xa0
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d2cc00, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x40
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d2ca80, 0x1400058f818)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x80
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100d2ca80, 0x1400035f960)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x90
[common/pkg/diagkit/gather/diagnose.Run(0x100d2ca80, 0x100d2cd80, {0x1400035fad8, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x188
[main.checkCmd({0x140001b6010, 0x0, 0x0}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:131 +0x114
[main.main()
[	common/cmd/com.docker.diagnose/main.go:97 +0x378

[FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the application running?
    Failed with: Docker is not running

Is the Docker Desktop application running?

2 : The test: can a VM be started?
    Failed with: vm has not started: failed to open kmsg.log: open Library/Containers/com.docker.docker/Data/log/vm/kmsg.log: no such file or directory

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

### Steps to reproduce the behavior

  1. Install Docker Desktop (with either dmg or brew)
  2. Open it.

**Comment by smustgrave** [comment]
Seeing this now too. Anyone find a fix?

**Comment by jfacoustic** [comment]
@smustgrave I had added a comment with this issue on a closed thread, and sjgd said to delete `/usr/local/lib` instead of `/usr/local/bin`, which worked for me.  Let me know if it works for you guys! 

reference: https://github.com/docker/for-mac/issues/6168#issuecomment-1064952378

**Comment by fdq09eca** [comment]
@jfacoustic it does not, for me `bin` is a folder and `lib` does not exist.

**Comment by fdq09eca** [comment]
> @smustgrave I had added a comment with this issue on a closed thread, and sjgd said to delete `/usr/local/lib` instead of `/usr/local/bin`, which worked for me. Let me know if it works for you guys!
> 
> reference: [#6168 (comment)](https://github.com/docker/for-mac/issues/6168#issuecomment-1064952378)

worked for me. Thanks!

**Comment by orsolyalukacs** [comment]
Experiencing the same issue.
I've tried the above mentioned solutions, did not work.

Got the following message upon running diagnostics:
```
3 failures detected
1 : is the $PATH ok?
    Failed with: unable to find docker executable on PATH
The directory containing the docker CLI tools must be on the $PATH

2 : is the application running?
    Failed with: Docker is not running
Is the Docker Desktop application running?

3 : are the binary symlinks installed?
    Failed with: unable to find /usr/local/bin
The symlinks to the docker CLI etc are needed for docker commands to work.
```
