### ISSUE TITLE
docker: Error response from daemon: dial unix docker.raw.sock: connect: connection refused.

### ISSUE THREAD

**Issue by rydan** [docker/for-mac#6188]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Resizing the docker image from settings resizes the image.
(Also, moving docker image location from settings moves the image)

### Actual behavior

Both cases, docker desktop gets stuck in starting, docker ps gives <subject> error.

### Information
Tried to resize the docker volume using docker desktop. Of course, that makes Docker Desktop stuck in "starting", and docker ps gives the <subject> error.

Clean/Purge data doesn't help. Restarting doesn't help.

Might be connected to problems with running Docker.raw on external disk. (Which by the way STILL doesn't work from Docker Desktop.

  - macOS Version: 11.65.2
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.5.0

### Steps to reproduce the behavior
Pretty much do any change to the defaults for the docker image. Try to move it from Docker Desktop. Try to resize it from docker desktop.

**Comment by rydan** [comment]
Where does Docker Desktop store it's setting for where it's supposed to look for the Docker.raw image? Problem seems to be (as always), docker desktop searches in the wrong place all of a sudden, and if changing from the UI, docker desktop tries to move the file, which again doesn't work since it can't find it. I just want to be able to manually change the setting for where the .raw file is located. How would I do that?

**Comment by binajmen** [comment]
Any relevant findings?

**Comment by rydan** [comment]
Well, sort of. Seems to be stored here:
~/Library/Group Containers/group.com.docker

**Comment by binajmen** [comment]
I've a sh*t tons of errors too: https://github.com/docker/for-mac/issues/6240

I'm a bit worried to see many threads on the same subject without any clear responses/ownership.. Is Docker dead?
