### ISSUE TITLE
Similar error as docker/for-win #11494 and #11445 | M1 Air

### ISSUE THREAD

**Issue by brnt-toast** [docker/for-mac#6194]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
deleting a stack to delete containers as a whole.
### Actual behavior
error was produced when trying to delete the entire stack. Had to delete the container first
### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: Apple Silicon
  - Docker Desktop Version: Docker Desktop 4.5.0 (74594)

### Steps to reproduce the behavior

  1. create stack with docker-compose.yml
  2. docker-compose up
  3. click STOP or REMOVE button for the stack

**Comment by laurazard** [comment]
Thanks for reporting @brnt-toast,

I'm having trouble reproducing your issue. Could you upload the output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`, and/or a compose file which causes this?
