### ISSUE TITLE
Docker Desktop for mac window does not close when CMD+w pressed 

### ISSUE THREAD

**Issue by alexcom** [docker/for-mac#6198]
When I press CMD+w combination I expect window to close and remain in memory. Examples: Finder, Slack.

  - [x] I have tried with the latest version of Docker Desktop

### Expected behavior
Window is closed, program keeps running.
### Actual behavior
Nothing happens.

**Comment by laurazard** [comment]
Thanks for reporting @alexcom, I've created an internal ticket to track this.

**Comment by timfallmk** [comment]
Dupe of #6167
