### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by mimo38** [docker/for-mac#620]
### Information

Diagnostic ID: 133C9BE8-BBDF-46D5-B312-1E1332BB3883
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.10.5 (Build 14F1912)

the command **docker run hello-world** return *docker: open /mnt/sda1/var/lib/docker/tmp/GetImageBlob815636614: no such file or directory.*

**Comment by mchiang0610** [comment]
@mimo38 Thanks for reporting. Does performing a factory reset in the application help? 

Let us know! Thanks

**Comment by mimo38** [comment]
All right !
it was a bad migration of an old Virtual hard drive
I have reinstalled all of the components, without this migration.
Thanks.
