### ISSUE TITLE
Can't start docker, Fatal Error: mkdir /Users/username: permission denied

### ISSUE THREAD

**Issue by joeyprusa** [docker/for-mac#6201]
I had to change my username and home dir due to issues authenticating some services within my org that required a specific username/home dir format. This required a host of changes to path, config files and reinstallation of some software. It also caused  docker to stop functioning and made the desktop app unusable as it errored on startup and crashed when any menu option was selected. I performed a manual uninstall, deleting all files and folders associated with docker, then performing a fresh install; however, upon startup I am still receiving an error and docker daemon fails to start.

I ran the following commands prior to reinstalling docker and restarted my mac:

```sudo rm -rf /usr/local/lib/Docker
sudo rm -rf /Library/PrivilegedHelperTools/com.docker.vmnetd
sudo rm -rf /Library/LaunchDaemons/com.docker.vmnetd.plist
rm -rf ~/.docker
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/Library/Application Support/Docker Desktop
rm -rf ~/Library/Preferences/com.docker.docker.plist
rm -rf ~/Library/Saved Application State/com.electron.docker-frontend.savedState
rm -rf ~/Library/Group Containers/group.com.docker
rm -rf ~/Library/Logs/Docker Desktop
rm -rf ~/Library/Preferences/com.electron.docker-frontend.plist
rm -rf ~/Library/Cookies/com.docker.docker.binarycookies
```

I have also searched for all files containing my old home dir and username and ensured no files related to docker contain them. 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EEC8E211-874E-4385-A0A3-1847AE66FBDD/20220224142605

### Expected behavior
Docker uses the correct home directory and starts after a clean install
### Actual behavior
Docker tries to use the old home directory and has a fatal error resulting in the app crashing

<img width="602" alt="Screen Shot 2022-02-23 at 7 22 26 AM" src="https://user-images.githubusercontent.com/91563302/155545013-0ba50510-f259-4619-9b39-f25a4ca5f4ec.png">

**Comment by StefanScherer** [comment]
I'm not sure if that is everything to fix it, but change the `dataFolder` in the `~/Library/Group\ Containers/group.com.docker/settings.json` file to the new user name and start Docker Desktop again.

**Comment by BillCao1997** [comment]
> I'm not sure if that is everything to fix it, but change the `dataFolder` in the `~/Library/Group\ Containers/group.com.docker/settings.json` file to the new user name and start Docker Desktop again.

It took me sooo much time and I've went through a lot of desperation until I came across your comment here. My Docker Desktop issue was finally resolved. Just want to say thank you and express my sincere appreciation 🙏

**Comment by aspcanada** [comment]
Thank you @StefanScherer !

**Comment by DypoB** [comment]
> I'm not sure if that is everything to fix it, but change the `dataFolder` in the `~/Library/Group\ Containers/group.com.docker/settings.json` file to the new user name and start Docker Desktop again.

Thanks a lot :)

**Comment by watain666** [comment]
> I'm not sure if that is everything to fix it, but change the `dataFolder` in the `~/Library/Group\ Containers/group.com.docker/settings.json` file to the new user name and start Docker Desktop again.

You are my life saver!
Thank you sooooooo much.

**Comment by sambhavkaul** [comment]
@StefanScherer Thank you so much !!

**Comment by koritsky** [comment]
> I'm not sure if that is everything to fix it, but change the `dataFolder` in the `~/Library/Group\ Containers/group.com.docker/settings.json` file to the new user name and start Docker Desktop again.

Thanks a lot!
