### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by danonorato** [docker/for-mac#6204]
Can not build linux/amd64 on docker for mac on M1.   I see this problem has been reported going back to 2020 and has yet to be resolved. 

  - [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
docker buildx build --platform linux/amd64 -t <image path> .  
builds the resulting image

### Actual behavior

ERROR [build 2/9] RUN mix local.hex --force &&   mix local.rebar --force                                                                                               
 
[build 2/9] RUN mix local.hex --force &&   mix local.rebar --force:
8 5.194 * creating /root/.mix/archives/hex-1.0.1
8 8.533 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
8 8.545 Segmentation fault

  - macOS Version:  MacOS Monteray version 12.2.1
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.5.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

### Steps to reproduce the behavior
docker buildx build --platform linux/amd64 -t <image path> .  

A reproducible case, Dockerfiles FTW.

Dockerfile for reference. you will not have access to the base image or source to build this image.

FROM hgdata1/elixir:1.13-snowflake-odbc-stable as build

ARG GIT_ACCESS_TOKEN
ARG APP_NAME
ARG RELEASE_LEVEL

ENV APP_NAME=${APP_NAME}
ENV RELEASE_LEVEL=${RELEASE_LEVEL}

RUN mix local.hex --force && \
  mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config
RUN mix deps.update query_broker
RUN mix do deps.get, deps.compile

COPY priv priv
COPY lib lib

RUN mix do compile, release

FROM hgdata1/elixir:1.13-snowflake-odbc-stable as app

ARG APP_NAME

ENV APP_NAME=${APP_NAME}

COPY --from=build --chown=hgdata:hgdata /app/_build/prod/rel/${APP_NAME} ./

ARG BRANCH=unset
ARG COMMIT=unset
RUN echo "BRANCH=${BRANCH} COMMIT=${COMMIT}" > /build.env

**Comment by laurazard** [comment]
This is a qemu bug, which is the upstream component we use for running Intel ("amd64") containers on M1 ("arm64") chips, and is unfortunately not something we control. In general we recommend running arm64 containers on M1 chips because (even ignoring any crashes) they will always be faster and use less memory.

Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one. Now that M1 is a mainstream platform, we think that most container authors will be keen to do this.

Creating intel images on M1 Macs is not guaranteed to work, can you to build this on an intel or a CI machine?
