### ISSUE TITLE
Docker desktop does not fully uninstall -- Reinstall uses some old config

### ISSUE THREAD

**Issue by webtop** [docker/for-mac#6208]
[Output.zip](https://github.com/docker/for-mac/files/8150297/Output.zip)

  - [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 94750234-8E9C-4E48-91BE-5CD35F574D69/20220228024943

### Expected behavior
Docker desktop starts

### Actual behavior
Docker desktop remains in "Waiting..." after exception dialog stating:
[057:21:58:00.624][I] time="2022-02-26T21:58:00.623771051Z" level=error msg="Handler for GET /v1.24/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."

### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
See attached zip file

### Steps to reproduce the behavior

  1. Install Docker desktop as normal
  2. Create a new admin account
  3. Login with new admin account
  4. Rename original account
  5. Login with original account
  6. Try to run Docker desktop
  7. If fails (should) uninstall it
  8. Reinstall Docker desktop -- do not start
  9. Run `/Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux`
  10. Start Docker desktop
  11. Observe that it fails because it doesn't find the old account, tries to create the /User/[old account name] but does not have permission.

I just got off contract with Adobe and had to have my iMac setup as my Adobe username: tek47725
After finishing the contract I renamed my local account and removed all Adobe access. After trying to restart Docker it would not restart. I uninstalled it and reinstalled it but it still would not start. When I ran the command in step 9 above, I noticed it trying to recreate the old account folder.
My guess is the uninstaller isn't truly uninstalling everything and a remnant config is still being loaded.

A bit of an edge case but thought I'd report it.

Additional output:
`paul.allsopp@Pauls-iMac ~ % /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux    
⇨ http server started on Library/Containers/com.docker.docker/Data/docker-api-proxy-control.sock
2022/02/27 19:19:05 notifying bugsnag: mkdir /Users/tek47725: permission denied`

**Comment by StefanScherer** [comment]
Oh that's a very special case.
Maybe cleaning these folders could help to wipe more files from the previous installation. We do something similar on our CI machines to clean them, but we don't rename the account name. But maybe this helps.
Stop all Docker processes before.

```
sudo rm -rf "$HOME/Library/Caches/com.docker.docker"
sudo rm -rf "$HOME/Library/Containers/com.docker.docker"
sudo rm -rf "$HOME/Library/Containers/com.docker.helper"
sudo rm -rf "$HOME/Library/Group Containers/group.com.docker"
sudo rm -rf "$HOME/Library/Application Support"/docker*
sudo rm -rf "$HOME/Library/Saved Application State"/com.electron.docker*
```

**Comment by webtop** [comment]
Thank you @StefanScherer  that did it!
I also found `/usr/local/lib/docker` still remained, and that with the ones you suggested made a full uninstall.
