### ISSUE TITLE
Docker-mac can't expose port from ubuntu container

### ISSUE THREAD

**Issue by bud32** [docker/for-mac#6211]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior

I can access localhost:5000

### Actual behavior

I can't access localhost:5000

I run my concainter with `docker run -p 5000:5000 -dit ...` and the ubuntu-based container starts with the server, but it doesn't work on mac. On linux, I can just do `--network=host` but on mac, the server is inaccessible. `docker port $container_id` doesn't show anything either.

Make sure to test the software before releasing!

**Comment by olavis** [comment]
@bud32 Have you checked if port 5000 is already taken by Airplay Receiver on your mac?

**Comment by bud32** [comment]
Nothing like that was running but restarting the PC helped.
