### ISSUE TITLE
Can't remove container using keyboard

### ISSUE THREAD

**Issue by idontusenumbers** [docker/for-mac#6220]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
Focus is traversable with keyboard

### Actual behavior
Focus is not traversable with keyboard

### Information

  - macOS Version: 12.2.1 (21D62)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.5.0 (74594)

  1. Try to delete container with Docker Desktop for Mac electron front-end
  2. Try to activate 'Remove' using only keyboard

![image](https://user-images.githubusercontent.com/1175031/157096486-c52c3d90-615e-4399-9ec9-eebadb901dd5.png)

**Comment by StefanScherer** [comment]
Thanks @idontusenumbers for the report. We plan to add better keyboard support in the UI. 
We also have a more general roadmap ticket https://github.com/docker/roadmap/issues/299 you can vote this ticket up to show demand for it.
And we also have #6062 which we will use to track this issue. I'll close this ticket as a duplicate.

**Comment by idontusenumbers** [comment]
@StefanScherer are you sure 6062 is the right ticket? It seems unrelated.

**Comment by StefanScherer** [comment]
Oops, that was a typo. I've updated my comment. Thanks for the heads-up.
