### ISSUE TITLE
Docker Desktop does not start, fails with fatal error

### ISSUE THREAD

**Issue by krrishh-org** [docker/for-mac#6227]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:     E6467309-B5CF-4270-8CE8-44FBE204CF7F/20220311100609 (uploaded)

### Expected behavior

It should run the Desktop app and open the User Interface

### Actual behavior

Shows a dialog showing the following error

Fatal Error

Docker daemon failed to start 

> [070:10:17:33.843][I] 	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x185

### Information
  - Is it reproducible?
  -  Yes
  - Is the problem new?
  - Yes
  - Did the problem appear with an update?
  - Not sure
  - A reproducible case if this is a bug, Dockerfiles FTW.

  - macOS Version:  macOS 11.6.4 (20G417)
  - Kernel Version:	Darwin 20.6.0
  - Intel chip or Apple chip: Intel 
  - Docker Desktop Version: 4.5.0 (74594)
 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[diagnostics.txt](https://github.com/docker/for-mac/files/8231154/diagnostics.txt)

### Steps to reproduce the behavior

  1. Open Docker Desktop App
  2. Wait for it

**Comment by daifuyang** [comment]
same trouble

**Comment by brettgoss** [comment]
A colleague of mine was experiencing the same issue. Re-installing Docker Desktop 4.6.0 didn't help, but downgrading to 4.4.2 resolved the problem. https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-442

**Comment by tailaiw** [comment]
I have the same issue. Uninstalled following the same instruction above and reinstalled the lower version, still no luck 🤷‍♂️

**Comment by dherault** [comment]
Same here. I solved it by:
- Deleting docker from applications (simple uninstall)
- Upgrading macOS to Monterey 12.3.1
- Downloading and installing Docker desktop again.

Hope that helps.

**Comment by siebica** [comment]
I got the same error when my removable SSD disk hosting the docker volume got unmounted due to a power cut. Uninstalling and reinstalling a previous 4.4.2 version didn't work.

I managed to install Docker 4.3.2 but I did this when **the removable SSD disk was not mounted in**. I still got an error saying that my previous mount location is not accessible: I reset docker to factory and this time it worked (docker volume was again on my main Machintosh disk). After this, reformatted the SSD and reset it as a docker volume.

**Comment by kruczekrobert** [comment]
1. Install docker-desktop 
2. brew install --cask appcleaner
3. Uninstall using app cleaner
4. Works...

**Comment by siebica** [comment]
I also used AppCleaner to uninstall docker the very last time but I didn't think it matters. Maybe you are right - some location not covered in the uninstall articles posted above - and that could have fixed it for me too.

**Comment by kruczekrobert** [comment]
@siebica I was just facing this problem, in the end the app cleaner helped, it covered some data during cleaning that I could not cover with commands. I tested before and after use. The use of the app cleaner helped me 100% in this case. 

Regards 👍
