### ISSUE TITLE
Apple CPU: docker-compose: fork/exec /usr/local/bin/docker-compose-v1: bad CPU type in executable

### ISSUE THREAD

**Issue by valeriangalliat** [docker/for-mac#6232]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - no, it kept hanging on "Diagnosing..." for over 20 minutes so I gave up

### Expected behavior

docker-compose works natively on Apple CPU (it was working flawlessly until now, without Rosetta).

### Actual behavior

docker-compose fails with:

```
fork/exec /usr/local/bin/docker-compose-v1: bad CPU type in executable
```

### Information

MacOS 12.2.1, Apple chip.
Docker Desktop 4.6.0 (fresh install).

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
```

Not sure what's that VM issue here but seems unrelated? I can use Docker no problem, just `docker-compose` fails

### Steps to reproduce the behavior

Install Docker 4.6.0 on a M1 Mac and run docker-compose.

---

I'm not sure how generic is that issue, but docker-compose was working fine for the past weeks and all of a sudden stopped working with this CPU error.

**By random trial and error I solved it by ticking "Use Docker Compose V2" in general preferences.**

Interestingly, resetting factory settings seems to ignore the "Use Docker Compose V2" setting. If it's off, it leaves it off, if it's on, it leaves it on. But out of curiosity, I completely uninstalled Docker Desktop and reinstalled it again, and "Use Docker Compose V2" was off by default.

It seems that Compose V2 has been around for quite a while now, and it must have been on by default in the past because I've never had this problem until today. I'm not sure what caused that setting to be turned off somehow and why a fresh install today also has Docker Compose V2 off by default.

**Comment by glours** [comment]
Thanks @thaJeztah 
Really strange, I just did a fresh install of the `v4.6.0` and the "Use Docker Compose V2" option was checked by default and I was able to use both `docker-compose` and `docker compose` without any issue
And V1 was also working correctly 🤔 
I'll take a look with the rest of the team

**Comment by valeriangalliat** [comment]
Thanks for double checking on your side @glours! The issue might have been very specific to my system somehow, I've only found a single other occurrence of this error message on the internet in [this tweet](https://twitter.com/new_tm/status/1487874620523171840) from a few months ago.

I'll close this especially [this documentation page](https://docs.docker.com/desktop/mac/apple-silicon/#known-issues) did already mention the switching to Docker Compose v2 fix, I just failed to find it in the first place. If anyone else ever runs into this error message at least they should find this issue easily with the fix. Cheers!

**Comment by faridmovsumov** [comment]
I have the same problem out of nowhere today. Everything was working perfectly few minutes ago and this is started now. Maybe some automatic update from docker triggered it.

`fork/exec /usr/local/bin/docker-compose-v1: bad CPU type in executable`

**Comment by boywijnmaalen** [comment]
having the same issue. ran the docker-for-mac update using the dashboard, after a successful install `docker-compose` returns the above-mentioned error. however `docker compose` is working for me. I'm unsure what my previous version of docker-for-mac was before the update, pretty sure I wasn't running behind too much.

system: Apple M1 Max

**Comment by stephen-turner** [comment]
Yes, compose v1 requires Rosetta. This is documented at https://docs.docker.com/desktop/mac/apple-silicon/#known-issues. We are not intending to change this: all compose development is now on v2.

**Comment by stephen-turner** [comment]
Of course, if you're somehow being switched from v2 back to v1, that is a bug.

**Comment by boywijnmaalen** [comment]
I can confirm that I'm not running Rosetta (nor do I want to). below an output of some commands as you can see v1 vs v2 are two different executables. however the 'fork/exec' error would indicate that the 'wrong' docker-compose version is referenced.

in addition;

`docker compose` (so without the '-') seems to work fine.

`
$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:43 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.0 (75818)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:37 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ which docker-compose-v1
docker-compose-v1 is /usr/local/bin/docker-compose-v1
docker-compose-v1 is /usr/local/bin/docker-compose-v1

$ which docker-compose
docker-compose is /usr/local/bin/docker-compose
docker-compose is /usr/local/bin/docker-compose

$ docker-compose --version
fork/exec /usr/local/bin/docker-compose-v1: bad CPU type in executable

$ docker compose version
Docker Compose version v2.3.3
`

**Comment by StefanScherer** [comment]
We just applied a fix so on a new machine you now get compose V2 by default when you run `docker-compose`.

**Comment by luwanhuang** [comment]
new Mac studio, docker version: 4.6.1. the option of use docker compose v2 is unselect as default. so I get same error message when I try use docker compose. It will work after check it.

**Comment by ndeloof** [comment]
I guess the root cause is we use `execve` to select the target binary to run from compose-switch: https://github.com/docker/compose-switch/blob/master/exec/exec.go#L8
doing so, as switch is compiled for ARM, rosetta isn't involved running replacement binary `docker-compose-v1` which is only available on amd64 : https://github.com/docker/compose/releases/tag/1.29.2
Maybe we should build and distribute an arm flavor of it ?
