### ISSUE TITLE
"Upload to get a diagnostics ID" is broken/nonfunctional (Windows and Mac)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6234]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - 
Impossible to upload diagnostics ID either from GUI or from command-line

### Expected behavior

Able to upload diagnostics ID from Docker Desktop

### Actual behavior

From GUI:

<img width="1225" alt="rfay-m1-air" src="https://user-images.githubusercontent.com/112444/158613214-ddfd9253-7d55-4cb1-b2ff-a35e5f9a4474.png">

From command-line:

see https://gist.github.com/rfay/507e24f77d96f1eacc4a2cda9d100f0d

But at the end: 
`INFO[0119] Error writing:  Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/E0801D1C-C895-4C7E-A3A1-1B030AACACEA/20220316142202.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address
Error uploading: Put "https://docker-pinata-support.s3.amazonaws.com/incoming/3/E0801D1C-C895-4C7E-A3A1-1B030AACACEA/20220316142202.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address`

### Information
  - macOS Version: 12, tested on Windows, same result
  - Intel chip or Apple chip: Tested on both, same result
  - Docker Desktop Version: 4.6.0

**Comment by mat007** [comment]
Hi Randy, are you behind a proxy?

**Comment by mat007** [comment]
@djs55 did we not change something in this area for 4.6.0?

**Comment by rfay** [comment]
No, not behind a proxy, never have been.

**Comment by rfay** [comment]
Checked again this morning, same behavior. Looks to me like it's infrastructure problems with AWS, proxy on their end...

**Comment by mat007** [comment]
We will release a Docker Desktop 4.6.1 shortly to address a few regressions, including this one.

**Comment by mat007** [comment]
Docker Desktop 4.6.1 has been released, with a fix. Thanks!
