### ISSUE TITLE
VirtioFS directory sharing has permission errors

### ISSUE THREAD

**Issue by boywijnmaalen** [docker/for-mac#6239]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics

### Expected behavior
I started docker with the new `VirtioFS accelerated directory sharing` enabled. I would have expected I can run `npm ci` the same way as I can without the option `VirtioFS accelerated directory sharing` enabled.

NPM (installed for the current user) should have permissions to install dependencies in a directory that belongs to the current user.

### Actual behavior
When expirimental option `VirtioFS accelerated directory sharing` is enabled I cannot run `npm ci` anymore.

As far as NPM is concerned the working directory does not have correct permissions to install dependencies. I can however still manually edit files using vim. NPM simply refuses to install dependencies.

NPM error log when expirimental option `VirtioFS accelerated directory sharing` is enabled:

<img width="1142" alt="Screenshot 2022-03-18 at 12 36 00" src="https://user-images.githubusercontent.com/3985741/158996295-ab712431-4500-4de0-8bff-09eea193e4c7.png">

[2022-03-18T11_34_31_175Z-debug-0.log](https://github.com/docker/for-mac/files/8304098/2022-03-18T11_34_31_175Z-debug-0.log)

### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.6.0

I have a container in which I run my (Node) projects. Whenever I enable the expirimental option `VirtioFS accelerated directory sharing` I cannot run `npm ci` anymore.

If I shutdown my container, disable the expirimental option `VirtioFS accelerated directory sharing`, restart docker and restart the very same container, I can once again successfully use `npm ci` to install deps.

the issue is reproducable by simply enabling the expirimental option `VirtioFS accelerated directory sharing` again and NPM will stop working. (`npm ci` will work once again after I disable the expirimental option `VirtioFS accelerated directory sharing`).

### Diagnistoc output 

(the diagnostic output is exactly the same whenever the expirimental option `VirtioFS accelerated directory sharing` is enabled or disabled. it doesn't matter for the diagnostics)

A readable of the diagnostic output attached as an image
<img width="1557" alt="Screenshot 2022-03-18 at 12 27 13" src="https://user-images.githubusercontent.com/3985741/158995107-ca27bf95-0dd0-4f5e-abf9-721115eae0b2.png">

[docker diagnostics.txt](https://github.com/docker/for-mac/files/8304073/docker.diagnostics.txt)

### Steps to reproduce the behavior

See `Information`

**Comment by cosmith** [comment]
I'm having issues with this too with the postgresql image, it can't modify some files. Switching virtiofs off fixes it. Doing a `chmod 777` on the shared folder doesn't help.

**Comment by yukotan** [comment]
I have same issue.

```YAML
services:

  db:
    container_name: test_mysql8
    image: mysql:8
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: testdb
    volumes:
      - './volumes/mysql/mysqldata:/var/lib/mysql'

networks:
  default:
    name: test-net
```

```
$  docker compose up --build

...
test_mysql8  | 2022-03-18T20:38:57.039908Z 0 [ERROR] [MY-010954] [Server] Performance schema tables initialization failed.
test_mysql8  | 2022-03-18T20:38:57.040226Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
test_mysql8  | 2022-03-18T20:38:57.041200Z 0 [ERROR] [MY-010119] [Server] Aborting
```

Switching virtiofs off  or delete "volumes" section, fixes it.

**Comment by spurin** [comment]
I believe I'm having the same issue, I've documented it as follows with some quick reproducible steps - https://github.com/docker/for-mac/issues/6243

**Comment by robsontenorio** [comment]
On fresh installs like MariaDB I have similar permission error

```
ERROR: 29  File './mysql/' not found (Errcode: 13 "Permission denied")
```

**Comment by kevinsjoberg** [comment]
Just got bitten by this myself. Had to disable VirtioFS for now.

**Comment by boywijnmaalen** [comment]
@all;

Please visit the link mentioned below. I don't think this release has been officially released, however I just tried it and my permission issues seem to be fixed with this release. I started out with clearing/purging all Docker data, starting from scratch.

https://github.com/docker/roadmap/issues/7#issuecomment-1073730051

**Comment by roboticflamingo** [comment]
I also have experienced this same issue with npm  / yarn. Also with composer. All work fine with virtio FS disabled but so slow.

**Comment by cosmith** [comment]
> ALL;
> 
> Please visit the link mentioned below. I don't think this release has been officially released, however I just tried it and my permission issues seem to be fixed with this release. I started out with clearing/purging all Docker data, starting from scratch.
> 
> [docker/roadmap#7 (comment)](https://github.com/docker/roadmap/issues/7#issuecomment-1073730051)

This does fix the issue for me, thanks!
