### ISSUE TITLE
Docker hangs in the "Starting" phase

### ISSUE THREAD

**Issue by bambielli** [docker/for-mac#624]
### Expected behavior
Docker for mac starts successfully

### Actual behavior
Docker for mac hangs in the "starting" phase

### Information

This has only started happening since the last update (or maybe last two updates). The docker for mac client continually says "starting" if I click the icon in the toolbar at the top.
![image](https://cloud.githubusercontent.com/assets/2530458/18528882/69f329ae-7a90-11e6-8284-8f34e6704349.png)
I've tried letting it go for an hour, and it continues to say "starting". 

Docker for Mac: version: 1.12.1-beta26 (d411b71)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/E3C8688D-23F3-43BD-99DF-31E90962EE83/20160914-153013.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

Try starting docker for mac... it should hang (at least it does for me!)

**Comment by bambielli** [comment]
I have tried restarting my computer, as well as clicking the "restart" button.

**Comment by bambielli** [comment]
I uninstalled and reinstalled and it seemed to work now.

**Comment by trawor** [comment]
I got this too

I have my 'data' folder soft linked from extend disk

**Comment by samoht** [comment]
@trawor can you try to link only the qcow2 image? This is not really supported, but it seems to be a working workaround until we allow to change the location of the file in the UI (which is in our short-term roadmap). If that doesn't work, please open a new issue with a diagnostic ID and upload your logs to our diagnostic server.
