### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by mreyesba1983** [docker/for-mac#6244]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mreyesba1983** [comment]
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
Error response from daemon: dial unix /Users/MARB/Library/Containers/com.docker.docker/Data/docker.raw.sock: connect: connection refused
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: does the Docker API work?
    Failed with: Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?

If the Docker API is not available from the host then Docker Desktop will not work correctly.

2 : The test: is the Docker CLI working?
    Failed with: exit status 1

The Docker CLI is needed to build, share and run applications.

**Comment by mreyesba1983** [comment]
MacOS version: monterrey 12.3
Apple chip. YES
Docker version: 4.6.0

**Comment by sebastian-ehrling** [comment]
for me to

**Comment by atomikdesign** [comment]
me too.
MacOS version: monterrey 12.3
Apple chip. YES
Docker version: 4.6.0

I've tried to enable I/O virtualization experimental feature and then unable to start docker.

**Comment by arambau** [comment]
If you tried to enable the experimental I/O virtualization feature and you're absolutely dead in the water AND CAN AFFORD TO HAVE ALL OF YOUR IMAGES AND CONTAINERS REMOVED, you can kill the Docker and Docker Desktop processes, then START FROM STEP 6 from the instructions found at https://www.mytecbits.com/apple/macos/clean-way-to-uninstall-docker. This worked for me.

**Comment by fsuke1985** [comment]
I got the same error too.
MacOS version: monterrey 12.3
Apple chip. YES
Docker version: 4.6.0

Thanks to @arambau
Your suggestion solved it.

**Comment by nunovieira** [comment]
- macOS Catalina 10.15.7
  - Intel chip
  - Docker Desktop 4.6.0 (75818)

I had the same issue.
Restarting the computer didn't help.
In Activity Monitor, the Docker process was "not responding". Killed that process, waited for the other "docker" processes to terminate, and launched Docker Desktop again. After a while, everything seemed ok.
Didn't had to remove images/containers. Hope this helps someone.

**Comment by mikhin** [comment]
> If you tried to enable the experimental I/O virtualization feature and you're absolutely dead in the water AND CAN AFFORD TO HAVE ALL OF YOUR IMAGES AND CONTAINERS REMOVED, you can kill the Docker and Docker Desktop processes, then START FROM STEP 6 from the instructions found at https://www.mytecbits.com/apple/macos/clean-way-to-uninstall-docker. This worked for me.

Didn't work for me.

**Comment by aharonmu** [comment]
Same here
MacOS version: monterrey 12.3
Apple chip. YES
Docker version: 4.6.0

Thanks to @arambau
Your suggestion solved it.

**Comment by andrewshokhin** [comment]
I faced the same problem after recent os x 12.3 upgrade, followed steps from [here](https://docs.docker.com/desktop/mac/troubleshoot/#check-the-logs) and found the fatal error
```Couldn't read values in CFPrefsPlistSource<0x1300098e0> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes): accessing these preferences requires user-preference-read or file-read-data sandbox access```
and after that found this thread and tried these commands (which delete all the containers)
https://github.com/docker/for-mac/issues/6142#issuecomment-1020055024
and now it works.

**Comment by pwittchen** [comment]
I have the same issue on Macbook Air M1 with macOS Monterey. I downloaded the latest docker for M1 Chip at it's stuck at "starting...". I tried to clean everything, deleting the app and installing it again and error still occurs. It worked some time ago, so I guess one of the recent releases has bugs.

**Comment by bmf-san** [comment]
Same here.
Montery12.3
MacBook Air (M1, 2020)
Apple M1

But with Docker Desktop 4.4.2, it started without any problem.

**Comment by pwittchen** [comment]
@bmf-san Can you tell, where can I download Docker Desktop 4.4.2 for Mac (M1)? On the website: https://docs.docker.com/desktop/mac/ I could find only the latest version (probably 4.6.0), 3.x and 2.x versions.

**Comment by pwittchen** [comment]
Thanks @joshtch. I hope problems with Docker on Mac will be fixed in the new releases too.

**Comment by fsamir** [comment]
Same issue here and I managed to get Docker engine running, by removing all entries from `filesharingDirectories` in `~/Library/Group\ Containers/group.com.docker/settings.json`

```
"filesharingDirectories": [],

````

**Comment by atomikdesign** [comment]
For those who still have the problem after enabling the /O virtualization experimental feature.

You can edit `~/Library/Group\ Containers/group.com.docker/settings.json` file

and set `"useVirtualizationFrameworkVirtioFS": false`

**Comment by NawafSwe** [comment]
Please Follow this article it will solve your problem, I had the same issue.
Link: https://www.mytecbits.com/apple/macos/clean-way-to-uninstall-docker

**Comment by mreyesba1983** [comment]
> * [x]  I have tried with the latest version of Docker Desktop
> * [ ]  I have tried disabling enabled experimental features
> * [ ]  I have uploaded Diagnostics
> * Diagnostics ID:
> 
> ### Expected behavior
> ### Actual behavior
> ### Information
> * macOS Version:
> * Intel chip or Apple chip:
> * Docker Desktop Version:
> 
> ### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
> ### Steps to reproduce the behavior
> 1. ...
> 2. ...

FINALLY, I used time machine and restored the state of DOCKER, then update and finally works

**Comment by pwittchen** [comment]
Can I do docker upgrade? To which version? I'm using an old version because I'm afraid that it will stop working after upgrade. :D
