### ISSUE TITLE
Wrong dock icon for Docker Desktop?

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6249]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 165EF212-DB99-4FE1-90A4-E516A309B23F/20220324125357

### Expected behavior

A Docker Desktop icon that is familiar and represents the Docker company.

### Actual behavior

In Docker Desktop 4.6.1 on more than one mac (but not all?) I see this icon in the dock:

<img width="806" alt="Container_list_and_rfay_d9junk-web___var_www_html" src="https://user-images.githubusercontent.com/112444/159920706-07ff111a-3f94-4bc5-bdb9-e04c05b10d01.png">

/cc @stephen-turner

**Comment by stephen-turner** [comment]
No, it's that simple. Most people are seeing it. We think it's something to do with showing and hiding it, but we're still working on it.

**Comment by Kithrian** [comment]
Same problem on my M1 Mac. This bug got me a bit confused. But still thanks for caring!

**Comment by trungutt** [comment]
Hi thanks for your report. Could you please try out these builds to see if the problem still persists? though it seems that this problem doesn't happen to every user

Mac M1: https://desktop-stage.docker.com/mac/main/arm64/77786/Docker.dmg
Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/77786/Docker.dmg

**Comment by rfay** [comment]
Although this seemed to have been fixed in the dmg in https://github.com/docker/for-mac/issues/6249#issuecomment-1102347883 it's not fixed in Docker Desktop 4.7.1, still seeing it (M1)

**Comment by stephen-turner** [comment]
Right, that comment was after the 4.7.1 build. It will be fixed in 4.8.0, which will likely be tomorrow.

**Comment by rfay** [comment]
Sad to say that I downloaded 4.8.0 just now and installed it (the update process wasn't ready, so didn't use that) and I still see the same empty dock icon. I don't know if completely uninstalling and reinstalling docker desktop would resolve it.

**Comment by stephen-turner** [comment]
Strange, you're saying it was fixed in the test build but not in the final?

**Comment by rfay** [comment]
I don't see a note that I tested it, was thinking that I did. I was on holiday without a computer when that comment was published, so probably didn't.

**Comment by rfay** [comment]
Installed 4.8.1, and so far I see the correct dock icon.

**Comment by johnjcamilleri** [comment]
I have had this problem for some weeks now, updated to 4.8.1 (78998) but still hasn't improved.

**Comment by desmortum** [comment]
Seems okay in 4.8.1 on Monterey.
<img width="233" alt="Screen Shot 2022-05-12 at 09 32 49" src="https://user-images.githubusercontent.com/38209369/168022304-1b5f5b87-7814-4866-a5b2-fcce1c5119df.png">

**Comment by johnjcamilleri** [comment]
I've tried the following but still no change.
```
sudo find /private/var/folders/ -name 'com.apple.dock.iconcache' -delete 
sudo find /private/var/folders/ -name 'com.apple.iconservices' -delete
sudo rm -r /Library/Caches/com.apple.iconservices.store
touch /Applications/Docker.app 
killall Finder
killall Dock
(system restart)
```
<img width="1032" alt="Screenshot 2022-05-12 at 15 17 21" src="https://user-images.githubusercontent.com/376723/168084128-2b099413-f1ea-400d-bcd9-0d97f8da5f34.png">

**Comment by johnjcamilleri** [comment]
Seems that this issue is a duplicate of https://github.com/docker/for-mac/issues/6173.
As suggested there, just reinstalling by drag-and-drop into Applications has fixed the issue.
