### ISSUE TITLE
Ads in menu bar

### ISSUE THREAD

**Issue by henryhchchc** [docker/for-mac#6254]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
No Ads in the menu bar.

### Actual behavior
<img width="263" alt="image" src="https://user-images.githubusercontent.com/5498199/160270713-6aa88f27-f8e6-4fd8-af38-36cf6c5c0aba.png">

### Information

  - macOS Version: 12.3
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.6.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
N/A

### Steps to reproduce the behavior

  1. Start docker desktop for mac

**Comment by stephen-turner** [comment]
You're objecting to us advertising a free conference? It seems to me that that's a benefit to the user.
