### ISSUE TITLE
Unable to install docker-desktop(Generic.Trojan) detected while installing

### ISSUE THREAD

**Issue by aamirkhancr7** [docker/for-mac#6255]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 12.3
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.6.1

### Steps to reproduce the behaviour

1. I tried to install docker desktop from official website [Docker deksktop](https://docs.docker.com/desktop/mac/release-notes/)

2. I saw an unexpected behaviour while installing docker-desktop as it shows Generic.Trojan detected while scanning for viruses. Attaching screenshot for your reference
 
<img width="1202" alt="Screenshot 2022-03-29 at 11 28 34" src="https://user-images.githubusercontent.com/47424913/160543822-80e38cfc-921f-4bd6-ae4d-8352ee438d8b.png">

3. For scanning threats on my system  I'm using CleanMyMac X 
    Version - 4.10.3

**Comment by hascoulijn** [comment]
I have the same issue with CleanMyMac X 4.10.3 and Docker Desktop for Mac 4.6.1. It happened when I started up Docker Desktop. After running the malware removal with CleanMyMac X Docker Desktop was completely removed from my MacBook.

**Comment by hascoulijn** [comment]
> > I have the same issue with CleanMyMac X 4.10.3 and Docker Desktop for Mac 4.6.1. It happened when I started up Docker Desktop. After running the malware removal with CleanMyMac X Docker Desktop was completely removed from my MacBook.
> 
> What was your workaround regarding this ?

Nothing as of yet. I'm awaiting further investigation regarding this issue. The only way I can think of is disabling CleanMyMac X entirely while installing or running Docker Desktop for Mac.

**Comment by itssadon** [comment]
I have the same issue with CleanMyMac X 4.10.4. It happened when I started up Docker Desktop. After running the malware removal with CleanMyMac X Docker Desktop was completely removed from my MacBook.

**Comment by AnthoRdev** [comment]
I have Docker Desktop installed since many weeks. I ran the malware scan today and I get the same backdoor alert.

Is someone asked Docker team if they know that detection and of course, if their repository is hacked?
Is someone asked to MacPaw if that's correct for them?

**Comment by AnthoRdev** [comment]
I sent a message to MacPaw with a link to this thread.

**Comment by AnthoRdev** [comment]
Hi there,
Just back to give you some news from the Pacpaw Team...
They sent me that:
"Thank you for contacting MacPaw Customer Support.
Please accept our apologies for this issue. It has already been fixed by our developers. You need to update your Database for the Protection Section. Please click on the "Check Now" on your CleanMyMac X Menu"

And yes, that solved.

**Comment by Simbaclaws** [comment]
Is this option only available in the paid version of CleanMyMac X?

I can not seem to find a way in the free version to update the Malware Database...

At some point I'll be getting the paid version, but I want to be sure before I buy anything that I will not get any false positive information about software that is not actual malware...

**Comment by AnthoRdev** [comment]
Download the lastest version from their website then reinstall it. ...or check [here on Setapp](https://go.setapp.com/invite/r3m7anaa) , that's what i have, than CleanMyMac is available with bunch of other nice apps ;)
