### ISSUE TITLE
Infinite loop when starting docker after update.

### ISSUE THREAD

**Issue by NawafSwe** [docker/for-mac#6260]
- [✅] I have tried with the latest version of Docker Desktop
  - [✅] I have tried disabling enabled experimental features
  - [✅] I have uploaded Diagnostics
  - Diagnostics ID: 20220331084238

### Expected behavior
When I update docker to the latest version it should starts successfully within maximum 10 seconds.
### Actual behavior
The Actual behavior it goes into Infinite loop trying to starting the docker process.
# Temporary Solution
I revert the update and install Docker desktop with version (4.5.0)

# Running /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
Error response from daemon: dial unix /Users/n/Library/Containers/com.docker.docker/Data/docker.raw.sock: connect: connection refused
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://Library/Containers/com.docker.docker/Data/docker.raw.sock. Is the docker daemon running?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
```
### Information
  - macOS Version: macOS Monterey version (12.3)
  - Intel chip or Apple chip: Latest M1 Pro apple chip 
  - Docker Desktop Version: latest version (4.6.1)

**Comment by sorokod** [comment]
I have the same symptom with the same solution. 
Tailing `~/Library/Containers/com.docker.docker/Data/log/vm/docker.log` I see repeated `... still waiting for /Users to be mounted after ...` messages

**Comment by moon-sam** [comment]
```
➜   ✗ tail ~/Library/Containers/com.docker.docker/Data/log/vm/docker.log
[	linuxkit/pkg/desktop-host-tools/cmd/lifecycle-server/main.go:116 +0x5e4
[main.main()
[	linuxkit/pkg/desktop-host-tools/cmd/lifecycle-server/main.go:36 +0x1e4
[091:19:56:46.565][I] sending fatal error to GUI: exit status 1
[091:19:56:46.565][I] (11d58854) 73d47f1a-DockerdPKG C->S  POST /fatal: {"diagnose":"exit status 1","message":"failed"}
[091:19:56:46.573][I] (11d58854) 73d47f1a-DockerdPKG C<-S b5250cc3-SwiftAPI POST /fatal (7.572709ms): OK
[091:19:56:46.573][I] sending docker state failed to backend: exit status 1
[091:19:56:46.573][I] (a12111a9) 39c214db-DockerdPKG C->S BackendAPI POST /events: {"HasServerTimestamp":false,"content":"lifecycle-server sent docker state failed","docker":"failed","timestamp":1648843006573261300}
[091:19:56:46.582][I] (a12111a9) 39c214db-DockerdPKG C<-S 4a56c212-VMAPI POST /events (9.128042ms): OK
[091:19:56:46.582][I] time="2022-04-01T19:56:46Z" level=fatal msg="exit status 1"
```

**Comment by AndreaCensi** [comment]
I have exactly the same problem, with the same messages as @sorokod. 
The issues persist even after a complete manual uninstall of docker. 
Downgrading to 4.5.0 is the only solution I found,

**Comment by giorginogreg** [comment]
@sorokod Same for me.
Found a temporary **solution** looking at [this post ](https://forums.docker.com/t/docker-desktop-4-6-1-for-mac-wont-start/122605/9)

**Comment by NawafSwe** [comment]
@giorginogreg @AndreaCensi @moon-sam @sorokod 
Please Follow this article it solved the problem for me. I updated docker to the latest version finally 🤣.
Article: https://www.mytecbits.com/apple/macos/clean-way-to-uninstall-docker

**Comment by giorginogreg** [comment]
@NawafSwe
for what I can see, this remain still an issue because the update process has not gone good, because after the update Docker still doesn't refreshed / deleted the files that it need for working in the good way.

What do you think about?
