### ISSUE TITLE
Yet Another QEMU Segmentation Fault Issue

### ISSUE THREAD

**Issue by Klohto** [docker/for-mac#6261]
Honestly, the handling of `qemu: uncaught target signal 11` issue has been abysmal.
[Would.](https://github.com/docker/for-mac/issues/6204) [It.](https://github.com/docker/for-mac/issues/6089) [Be.](https://github.com/docker/for-mac/issues/6075) [Possible.](https://github.com/docker/for-mac/issues/6070) [To.](https://github.com/docker/for-mac/issues/6005) [Stop.](https://github.com/docker/for-mac/issues/5883) [Closing.](https://github.com/docker/for-mac/issues/5766) [The.](https://github.com/docker/for-mac/issues/5736) [Issues.](https://github.com/docker/for-mac/issues/5711) With _"yea, we know, but we won't help ya, bye"_?

I understand you don't want to cross _"best effort"_ but the least you could do is have a questionnaire regarding this issue.
- You claim this a known issue on QEMU, **where can we track it?**
- Is it already fixed in QEMU? **When can we expect it incorporated?**
- It's up to the user to fix? **What is recommended workaround?** **Can we update QEMU install ourselves?**

You have thousands of these, but for replication (on Apple Silicon ofc):
```
FROM hexpm/elixir:1.13.3-erlang-24.3.3-alpine-3.15.3
RUN mix local.hex --force
```

If emulation support is on best effort, why isn't **this** known issue mentioned in docs? Why is the user presented with a cryptic QEMU fault which he has no idea about? Yes, not building amd64 on arm64 is definitely a solution, but so is using a remote builder and completely skipping Docker Desktop (not to bash DD, Rancher Desktop has the same problem).

I'm pretty sure the community could at least help a little here if you point it in a right direction, but you refuse to start the dialog.
Why not have at least one of the issues open for tracking instead of 20 duplicates every year?

**Comment by yllekz** [comment]
I've been increasingly finding Docker Desktop on macOS to be rather unstable. Every few days all my containers end up in an unhealthy state and the only fix seems to be to kill/restart Docker Desktop entirely. I agree, this should be acknowledged and raised as a critical issue because it's starting to steer me toward alternatives (which might include just running a straight Linux VM with Docker on it). Stability is everything.

**Comment by stephen-turner** [comment]
@Klohto I hear your frustration, but unfortunately there's nothing we can do about it. We have no qemu developers, and we just take the code from upstream. We recommend in the docs not to use qemu. But we're not in a position to fix any qemu bugs.

**Comment by ianks** [comment]
Is there an open issue with qemu? I checked their issue tracking but couldn’t find anything.

**Comment by mraszyk** [comment]
I opened an [issue](https://gitlab.com/qemu-project/qemu/-/issues/989) with qemu, but now it seems to me that my issue is unrelated to qemu. Hence, I filed an [issue](https://github.com/rancher-sandbox/rancher-desktop/issues/2109) with Rancher Desktop that I was using instead of Docker Desktop.
