### ISSUE TITLE
buildx fails to build on M1 and succeeds on Intel with platform linux/amd64

### ISSUE THREAD

**Issue by CmdrChaos** [docker/for-mac#6267]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 80C69394-1155-45A8-BEF2-3510ADCAAD2A/20220407155422

### Expected behavior
Running docker buildx from command line using the same Dockerfile and parameters on M1 and intel Apple hardware should both succeed.
docker buildx build --platform linux/amd64 -t buildx_error .
### Actual behavior
Running docker buildx from command line using the same Dockerfile and parameters fails on M1 hardware and succeeds on Intel hardware.
### Information
Dockerfile contents:

    FROM Debian:stable

    RUN apt-get update && apt-get install -y software-properties-common

    RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata

    RUN apt-get install -y libdb4.8

Command line:

    docker buildx build --platform linux/amd64 -t buildx_error .

  - macOS Version: 12.3.1 (21E258)
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.6.1 (76265)

I was updating existing code when I encountered this issue.  I have provided a reduced Dockerfile that demonstrates the issue reliably.  I have also provided the failure output in the file failure.txt
I don't know if it makes a difference, but Rossetta 2 is installed on the M1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1.  Run this command  using the provided Dockerfile - "docker buildx build --platform linux/amd64 -t buildx_error ." on Apple Intel hardware to see success case
  2. Run same command on Apple M1 hardware to see failure case
[Dockerfile.txt](https://github.com/docker/for-mac/files/8444983/Dockerfile.txt)
[failure.txt](https://github.com/docker/for-mac/files/8445036/failure.txt)

**Comment by nitin302** [comment]
were you able to fix this?
