### ISSUE TITLE
Auto update failed

### ISSUE THREAD

**Issue by jsma** [docker/for-mac#6268]
* I applied the auto-update from 4.6.1 to 4.7.0, clicked to restart. 
* Docker closed and never reopened.
* I ran `docker ps` from the command line:

```
-bash: docker: command not found
```

* I manually navigate to Applications to launch:

<img width="544" alt="Screen Shot 2022-04-07 at 11 15 10 AM" src="https://user-images.githubusercontent.com/24574/162270090-20595348-9ccf-4662-b80e-a022734f2d44.png">

### Expected behavior
The update would succeed

### Actual behavior
The update uninstalled the old version but encountered some sort of issue when downloading the update, resulting in a corrupted file about 50% of the size it should have been (also note the wacky "Created" date):

<img width="653" alt="Screen Shot 2022-04-07 at 11 21 52 AM" src="https://user-images.githubusercontent.com/24574/162270803-2dfe007f-310d-4480-ad40-a74f9a615c56.png">

After manually downloading the update, the correct file size is shown:

<img width="619" alt="Screen Shot 2022-04-07 at 11 22 31 AM" src="https://user-images.githubusercontent.com/24574/162270908-1f4ffd9d-d412-40f1-a4fb-4bc535e1e0a7.png">

There were no obvious network disruptions during the update. But even if there were, Docker Desktop should be smart enough to detect these conditions before uninstalling the old version so the user at least has a working previous version on their system and can retry the download/update process.

Does this mean that Docker doesn't even validate the integrity of the downloaded update before installing software that requires a admin password to install?

**Comment by mat007** [comment]
Hi, thanks for reporting and sorry about the issue.

> Does this mean that Docker doesn't even validate the integrity of the downloaded update before installing software that requires a admin password to install?

We’re actually using a tool/library called Sparkle which is well known and used on macOS to handle updates.
It’s a bit of a black box though, and we’re considering rewriting the code so that we get more control…

Can you upload some diagnostics following https://docs.docker.com/desktop/mac/troubleshoot/#diagnose-and-feedback so that we can have a look at the logs?

Thanks!

**Comment by aexvir** [comment]
same here... that `MacOS` folder doesn't exist after the faulty update on my machine, so it's not possible to run any diagnostic; the only solution I found has been to reinstall it
this is not the first time docker for mac ends up in this state after an upgrade... it's quite frustrating

**Comment by jsma** [comment]
@mat007 
> it's not possible to run any diagnostic; the only solution I found has been to reinstall it

This is my situation as well, unless a clean install of v4.7.0 can somehow reach back in time to diagnose what happened before it was installed by the previous version. If so, let me know and I'll try.

On a side note, according to the [Diagnose and feedback](https://docs.docker.com/desktop/windows/troubleshoot/#in-app-diagnostics) guide, we're supposed to log into our account first. I can't log into Docker Deskop because it opens my default browser (Firefox) to a login page, I log in, and then I am redirected to a blank page because Firefox is blocking a ton of tracking scripts on an _auth redirect page_ (since I can't see the page, I think all this page does is open the pop up so I can have it open a "link" in the Desktop app to complete the process):

<img width="428" alt="Screen Shot 2022-04-08 at 2 50 45 PM" src="https://user-images.githubusercontent.com/24574/162536816-bfb09975-29ba-475e-99d7-fd3afa404321.png">

Is any of that tracking necessary for getting authenticated in the app?

**Comment by mat007** [comment]
> This is my situation as well, unless a clean install of v4.7.0 can somehow reach back in time to diagnose what happened before it was installed by the previous version. If so, let me know and I'll try.

Yes, that’s what I meant, sorry I should have said that explicitly.
So, after installing another version (either a fresh 4.7.0 or even a 4.6.x), just run the diagnosing tool either from the UI (open the Troubleshoot and wait a bit) or from the command line (see instructions in the docs). You don’t need to be logged in, it’s only to open a support ticket if you have a paid subscription.
This will collect logs and such, make a zip, and upload it. Then it gives you an ID (a long hash with dashes) which will then allow us to retrieve the zip and look at the logs.

> Is any of that tracking necessary for getting authenticated in the app?

No, but your browser needs to open that page to redirect to a URL with a custom protocol, which will reach the Docker Desktop application.

**Comment by mat007** [comment]
Hi @Brodan, sorry to hear that.

It’s just a file copy (well a folder copy really as a `.app` is a folder), so what do you mean by «crashing on install»? The file copy fails somehow?

We’ve had a few reports of people having to copy several times out of the DMG until macOS agreed to launch the app. We’re really scratching our heads on that one, given it should really not happen (unless disk corruption or whatever…).

**Comment by flowl** [comment]
The reply to the privacy concerns is not satisfying.
Even mouse cursor tracking is enabled.
Poor privacy, big dislike.

**Comment by mat007** [comment]
I have forwarded the tracking concerns to the proper team, and I am waiting for their response. Thanks for raising that!

**Comment by mat007** [comment]
Back to original issue, to sum things up:
- The only way to fix this when it happens is to [download a fresh Docker Desktop](https://www.docker.com/products/docker-desktop/), and copy it over the broken one. This should just work, keeping all existing data (images, containers, volumes, …)
- We have managed to reproduce the issue exactly two times internally (and we have dozens of engineers updating Docker Desktop every few days, plus a lot of CI as well). The logs were very… empty. It looks like the update tool we use (Sparkle, very common, used in many macOS apps) just bails when trying to copy a file, for a reason we haven’t yet totally understood.
- We are still trying to figure out the best course of action here, we have plans to rewrite the whole in-app update code (mainly because we want to same behaviour in the new Docker Desktop for Linux, and consolidating the code at the same time would be great), so that would give us a lot more control and probably fix that issue at the same time.
- As a side note, a super frustrating trait of update code is that it needs two releases to actually fix a bug: users need to update to fix the update bug, which prevents them to update in the first place… We’re also starting to think about ways to re-architecture the code to work around that.

**Comment by ncouse** [comment]
This happened to me on several upgrades, and just now on 4.7.0->4.7.1 

What I did notice is that the `Contents/MacOS` directory was completely missing after upgrade.
I had to reinstall to solve it.

What I did notice was that on the Upgrade screen, I click the "Install and Upgrade" (I can remember exactly what the button text was), and there was no feedback. I may have tried several times. Eventually I click Cancel at the bottom of the screen and realised it was actually updating anyway. Just a guess, but perhaps me be able to click the button multiple times causes issues.

**Comment by mat007** [comment]
> Just a guess, but perhaps me be able to click the button multiple times causes issues.

I believe this was discussed at one of our standups last week, and the general consensus was that this should not trigger any sort of race all the way down. But I think I’ll create a ticket to double-check nonetheless…
We need another ticket to fix the UI though, as this is really poor UX indeed.

Thanks!

**Comment by rmsy** [comment]
This just happened to me as well (going from 4.6.? to 4.7.1). Like the last commenter, I too did click "Update and Restart" multiple times, because I didn't get any immediate visual feedback.

**Comment by mat007** [comment]
> I too did click "Update and Restart" multiple times, because I didn't get any immediate visual feedback.

In Desktop 4.8.0 which will be released imminently, the button will be disabled once the update is started.

**Comment by ncouse** [comment]
So the new 4.8.0 has come out, so I tried an update, and it was successful.

So what I noticed:
* Click the download button does now grey it out and change text to "Downloading...."
  * Nice feedback this time
* This then turns into an "Update and Restart" button
* Pressing this button gives *no feeback* for a few seconds, until the entire window greys out
  * I resisted pressing the button mutliple times though :)

**Comment by mat007** [comment]
@ncouse the changes will be effective for when the next new version comes out 😁

**Comment by PuppyKhan** [comment]
I did the recommended workaround of downloading a fresh copy last time, and now it just happened again the next time the app told me an update was available (today). This is no longer an anomaly, this now happens every time.

**Comment by PuppyKhan** [comment]
Update: @mat007 I have a theory on what is happening. The update is behaving the same as if you download the wrong version. I have a Mac with an Intel chip. The update behaves as if it downloaded a version for an apple chip

**Comment by jsma** [comment]
...and it happened again when upgrading from 4.7.x to 4.8.1
<img width="459" alt="Screen Shot 2022-05-10 at 11 52 49 AM" src="https://user-images.githubusercontent.com/24574/167701674-c97847f7-23f0-4bb5-859d-0adc50e4cc9f.png">

**Comment by mat007** [comment]
> I have a theory on what is happening. The update is behaving the same as if you download the wrong version. I have a Mac with an Intel chip. The update behaves as if it downloaded a version for an apple chip

That would be very surprising, the only way this would be possible would be if the code to find out the current architecture had a bug, and it’s quite straightforward and used elsewhere, e.g. try to open the About box from the system menu (not the whale menu drop down), if it works then it should be fine.

You’re saying this happens every time for you, would you be ready to conduct a little experiment?
Starting with Docker Desktop 4.8.1 installed, assuming you have an Intel system:
1. quit if it’s running
2. open a terminal and run `/Applications/Docker.app/Contents/MacOS/Docker --update-url https://desktop-stage.docker.com/mac/main/amd64/79135/appcast.xml`
3. perform the update as usual

This should update to an internal 4.9.0 build (which isn’t that different from 4.8.1 released only a few days ago).
Also it’s clear from the URL that it targets an `amd64` build.

**Comment by PuppyKhan** [comment]
> would you be ready to conduct a little experiment?

OK, this upgrade worked fine. So no longer "every time", just more than once.

**Comment by mat007** [comment]
If you compress it aggressively, how much does the archive weight?

**Comment by PuppyKhan** [comment]
> If you compress it aggressively, how much does the archive weight?

It compresses to just over 600MB. I can put it on a private server if I can DM you the access to download it from there.

**Comment by mat007** [comment]
> I can put it on a private server if I can DM you the access to download it from there.

Awesome, thanks!

**Comment by PuppyKhan** [comment]
Ready. Github doesn't allow DMs. Where to send the info? DM my twitter? (link in profile)

**Comment by mat007** [comment]
You can send it to mathieu.champlon@docker.com

**Comment by mat007** [comment]
In 4.8.0 we added a small change to disable the «update and restart» button when clicked, to prevent from accidentally clicking several time and triggering some kind of race.
Updating from any 4.8.x and later versions should have this fix.

Maybe it was just that. 🤷

**Comment by jlederman** [comment]
Moments ago I upgraded from 4.8.1 to 4.9 and experienced this exact issue. Does not appear to be solved. Am now having to do a fresh Docker install on a MacBook Air with an M1 chip.

**Comment by mat007** [comment]
@jlederman can you [upload diagnostics](https://docs.docker.com/desktop/mac/troubleshoot/#diagnosing-from-the-terminal) when you can, please?
Thanks!

**Comment by dghojas** [comment]
I also have the same problem with Docker 4.8.1. Please help me how to solve.
This is the Diagnostic ID: C7BC6F41-FCCB-443C-B960-DF6ED7761387/20220619020323

Stay tuned,
Greetings.

**Comment by robrich** [comment]
I think I hit this condition because I was impatient and tried launching the app before it finished downloading & installing.  (Guessing here.)  Of course the great and mighty "download and reinstall" got me going again.  I was pleasantly surprised my images and extensions were still there.

**Comment by ncouse** [comment]
I encountered issue again with 4.10.0->4.10.1, even though the last few upgrades worked flawlessly.

The download for upgrade didn't seem to be working. It greyed out, and just stayed there. I tried it several times over several days - I suspect issue with HTTP proxy settings, perhaps. Then one time I see the macOS window indicating it was unpacking something.

When I launched I got this window, and couldn't find a way to fix.

![Screenshot 2022-07-08 at 18 40 17](https://user-images.githubusercontent.com/20225047/178064265-9bcbf4d0-f668-4313-8d62-66b2e91b762d.png)

I had to quit, and reinstall with full dmg image, but that didn't seem to work either. It would launch, but docker itself would not launch. I couldn't quit Docker Desktop, so I had to kill processes manually, remove docker from `Applications`, reboot (just to be sure), and install again (from dmg). Only then could I get it working again.

**Comment by fourcolors** [comment]
<img width="448" alt="Screenshot 2022-11-02 at 7 42 16 PM" src="https://user-images.githubusercontent.com/51751/199633344-a8d75d5a-cb15-4e28-a335-80c1f2f82698.png">


I'm also encountering this now with a fresh install, no existing docker.  Running an intel i9 with Ventura 13.0
