### ISSUE TITLE
Possible EPIC task to fix Docker Desktop updating?

### ISSUE THREAD

**Issue by josh-m-sharpe** [docker/for-mac#6278]
Just sayin:
https://github.com/docker/for-mac/issues/6268
https://github.com/docker/for-mac/issues/6148
https://github.com/docker/for-mac/issues/6144
https://github.com/docker/for-mac/issues/6130
https://github.com/docker/for-mac/issues/6117
https://github.com/docker/for-mac/issues/6100
https://github.com/docker/for-mac/issues/5867
https://github.com/docker/for-mac/issues/5677

...and that's just the first few pages of open issues - and only issues that have 'update' in the subject.

There's something br0ken here.  Needs reimagining.

**Comment by flowl** [comment]
There seem to be considerations:

> We’re actually using a tool/library called Sparkle which is well known and used on macOS to handle updates.
> It’s a bit of a black box though, and we’re considering rewriting the code so that we get more control…

https://github.com/docker/for-mac/issues/6268#issuecomment-1092567609
