### ISSUE TITLE
1.12.1-beta25 hanging after `docker exec`

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#628]
### Steps to reproduce

1. Don't know, docker exec's just started hanging again.

### Expected behavior

docker exec should not hang

### Actual behavior

Three terminal windows where I had docker exec's running hung, hangs when I try to exec into any containers now, will try a restart.

### Information

```
Diagnostic ID: ABD74BC9-C727-4923-9615-D27B17A1ADB4
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by jamshid** [comment]
Just noticed there is a beta26, will try that.

**Comment by samoht** [comment]
Closing the issue as it seems to be working better for you now.
