### ISSUE TITLE
Failed to run an amd64 docker-in-docker (dind) container on an arm64 host (Apple silicon)

### ISSUE THREAD

**Issue by updogliu** [docker/for-mac#6284]
I am trying to run an amd64 docker-in-docker (dind) container on an arm64 host (Apple silicon machine), because some images to be run on this dind are amd64 only (e.g. MySQL-5.7).

### Expected behavior

A container of image `docker:dind` runs normally.

### Actual behavior

Container of image `docker:dind` exited with error message:

failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.7 (legacy): can't initialize iptables table `nat': iptables who? (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

### Information

To reproduce, just run the commands below on a machine with an Apple chip.
```
docker run --platform linux/amd64 --privileged --name dind docker:dind
```

- macOS Version:
Version 12.3.1 (Monterey)

- Intel chip or Apple chip: 
Apple. A Mac mini with M1 chip.

- Docker Desktop Version:
```
Server: Docker Desktop 4.7.0 (77141)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:44 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

**Comment by fredericdalleau** [comment]
This is not possible. The emulation layer does not support ip routing capabilities. Have you considered running the arm64 dind and executing the amd64 with the --platform flag there? You can also try an alternative db.

**Comment by updogliu** [comment]
Thanks, @fredericdalleau , it works!

On a M1 Mac-mini, I brought up a arm64 dind with
```
docker run --privileged --name dind docker:dind
```

And then I ran an `mysql:5.7` container (which only has `linux/amd64` architecture) with `--platform linux/amd64`, and it just worked!
```
docker run --platform linux/amd64 --name some-mysql -e MYSQL_ROOT_PASSWORD=foopass -p3306:3306 -d mysql:5.7
```
