### ISSUE TITLE
Docker won't start on MacOS Monterey

### ISSUE THREAD

**Issue by riceset** [docker/for-mac#6299]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
Launching Docker.

### Actual behavior
Docker doesn't launch.

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.7.1

### Steps to reproduce the behavior
I installed Docker via Homebrew some months ago and it was running perfectly. I tried installing it again today with Homebrew and noticed it doesn't launch. I tried updating my Mac, installing from the dmg file but no success.
If I open Activity Monitor I can see a process from Docker but it says 'not responding'.
![image](https://user-images.githubusercontent.com/48802655/166305251-c8088a03-ae4e-4b5d-bfda-edc651576c98.png)

**Comment by joefreyk** [comment]
Same situation.

Upgrade from 3.x release to v4.7.1 never completed. Manually removed and installed from .dmg.

Application won't launch. Only the below two processes are starting:

/Applications/Docker.app/Contents/MacOS/com.docker.dev-envs -watchdog
/Applications/Docker.app/Contents/MacOS/com.docker.extensions

**Comment by bogdanconstantinescu** [comment]
Try [this suggestion](https://github.com/docker/for-mac/issues/6294#issuecomment-1114317057) (installing Docker with Homebrew) for Intel chips on Monterey 12.3.1 (on Apple Silicon it did not work, though)

**Comment by riceset** [comment]
@bogdanconstantinescu This worked for me. Thank you.
