### ISSUE TITLE
docker ps is not responding

### ISSUE THREAD

**Issue by jasonhillier** [docker/for-mac#63]
### Expected behavior
docker ps should not get stuck

### Actual behavior
it gets stuck, even after fresh reboot it is still stuck

### Information

Diagnostic ID: 045D5711-47CB-474F-9E4B-18075E1E6712
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F27)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Allow computer to go into sleep/suspend
2. Wake machine up, docker ps gets stuck
3. Reboot machine, docker ps is still getting stuck
4. Seems to be broken even if I hit restart on the service several times

**Comment by jasonhillier** [comment]
Right before this started happening, I saw this error on various containers:
UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

**Comment by djs55** [comment]
In the logs everything seems fine, then there's a gap and then an as-yet-unexplained SIGTERM to the VM:
```
Aug  1 17:05:06 Docker[com.docker.driver.amd64-linux][661] <Notice>: VM: 2016-08-02 00:05:06 +0000 UTC kern.info kernel: br-07242275499c: port 2(vethfd27fa6) entered forwarding state
Aug  1 17:05:06 Docker[com.docker.driver.amd64-linux][661] <Notice>: VM: 2016-08-02 00:05:06 +0000 UTC daemon.info vsudd: 168 Done. read: 283 written: 95
Aug  1 17:05:06 Docker[com.docker.driver.amd64-linux][661] <Notice>: VM: 2016-08-02 00:05:06 +0000 UTC daemon.info vsudd: 132 Done. read: 307 written: 95
Aug  1 17:05:06 Docker[com.docker.driver.amd64-linux][661] <Notice>: VM: 2016-08-02 00:05:06 +0000 UTC kern.info kernel: vethad890b3: renamed from eth0
Aug  1 17:08:48 Docker[com.docker.driver.amd64-linux][661] <Notice>: sending SIGTERM to com.docker.hyperkit pid 666
```
One of the hyperkit processes (probably the one actually running the VM) has `exit`ed but hasn't been reaped:
```
 $ grep com.docker.osx.h ps-ax.log
  470   ??  S      0:00.11 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
  472   ??  Z      0:00.00 (com.docker.osx.h)
  660   ??  Ss     0:00.12 com.docker.osx.hyperkit.linux
  662   ??  S      0:00.01 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux
```

**Comment by djs55** [comment]
I think we should simplify the process management and reduce the number of subprocesses to make it easier to see what's going wrong.

Unfortunately there was a bug in early betas and stable 1.12.0 which causes some diagnostic output from the VM to be lost. In particular things like process lists and running `docker ps` inside the VM are invaluable for diagnosing "docker ps" doesn't work issues. Are you able to update to a more recent beta and capture more diagnostics?

**Comment by djs55** [comment]
I changed the title again because I'm not convinced there's enough evidence that the unexplained SIGTERM caused the problem -- it may well have been caused by something else. Sorry for the noise.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in 045D5711-47CB-474F-9E4B-18075E1E6712/20160801-171450.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-07-28T19:08:34.845657942Z" level=debug msg="Golang's threads limit set to 27990"
time="2016-07-28T19:08:34.846253809Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-07-28T19:08:34.852933069Z" level=debug msg="Using graph driver aufs"
time="2016-07-28T19:08:36.838235615Z" level=debug msg="containerd connection state change: READY"
time="2016-07-28T19:08:37.246070740Z" level=debug msg="Failed to load mount 22973f9756a2526d86dcc29ba3d84975f96671988994832a091103ce3b111b21: invalid mount id value"
time="2016-07-28T19:08:37.248555320Z" level=debug msg="Failed to load mount 54abebe14cdef759e873b64f2da0e66e5563be589f84500cb9b3f100f758793b: invalid mount id value"
time="2016-07-28T19:08:37.251541404Z" level=debug msg="Failed to load mount 66294d98bb1c7c35419a694344e5c416bf7b77446519d21cac6552006dabfa64: invalid mount id value"
time="2016-07-28T19:08:37.254032997Z" level=debug msg="Failed to load mount b927d02348160c0a6c19dcb8f2d5772a6f4c9866b32a352d8735c26704201c27: invalid mount id value"
```
