### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by Zenmiao** [docker/for-mac#6304]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C6861DFB-038E-4095-9328-E6226186CF6D/20220505025422

### Expected behavior
Docker Desktop icon is displayed properly 
### Actual behavior
<img width="116" alt="image" src="https://user-images.githubusercontent.com/7502968/166857577-0cb94ef6-0f18-4798-b79f-1c67981caea8.png">

### Information

  - macOS Version: 12.3.1 (21E258)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.6.1 (76265) 

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're trying to address this issue in the next release of Docker Desktop. In the meantime, you can restart the dock with `killall Dock` will make Dock icon normal again
