### ISSUE TITLE
Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: connection refused [without experimental features enabled]

### ISSUE THREAD

**Issue by omontigny** [docker/for-mac#6306]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B83B2364-1162-402F-BC5D-F160DA0A8E21/20220506123603

[20220506123603.zip](https://github.com/docker/for-mac/files/8640093/20220506123603.zip)

### Expected behavior
 pull image when I do a `docker pull image`

### Actual behavior
I have this Error on pulling :
`Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: connection refused `

### Information

  - macOS Version: `BigSur 11.4`
  - Intel chip or Apple chip: `Intel chip`
  - Docker Desktop Version:  `4.7.1 (77678)`
 -  Docker engine :  `20.10.14, build a224086`

 - Is it reproducible? : `always`
 -  Is the problem new? : `yes (two days ago it was ok )`
 - Did the problem appear with an update? `No, it was the same with previous version. `
 
I'm not sure but I think it arrives when I tried to deploy this product : https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

the $DISPLAY var was empty. So I thought I had to install XQuartz.  what I did . Now $DISPLAY is 
`/private/tmp/com.apple.launchd.tiROCFhhiZ/org.xquartz` 
even if I try to remove this value , it doesn't help . 

I tried to completely` remove and re-install` Docker Desktop . Nothing change. 
I tried to `Reset to factory defaults` : Nothing Change it was worse , it was starting for ever ....

I assume this is a network configuration but I can't find it. I checked everything. there no proxy configuration 
this is my docker settings.

```
{
  "acceptCanaryUpdates": false,
  "activeOrganizationName": "",
  "analyticsEnabled": true,
  "autoDownloadUpdates": false,
  "autoStart": false,
  "backupData": false,
  "cpus": 2,
  "credentialHelper": "docker-credential-osxkeychain",
  "dataFolder": "~/Library/Containers/com.docker.docker/Data/vms/0/data",
  "deprecatedCgroupv1": false,
  "disableHardwareAcceleration": false,
  "disableTips": false,
  "disableUpdate": false,
  "diskFlush": "os",
  "diskQcowCompactAfter": 262144,
  "diskQcowKeepErased": 262144,
  "diskQcowRuntimeAsserts": false,
  "diskSizeMiB": 61035,
  "diskStats": "",
  "diskTRIM": true,
  "displayRestartDialog": true,
  "displaySwitchVersionPack": true,
  "displayedDeprecate1014": false,
  "displayedElectronPopup": [],
  "displayedExtensionsIntroductionDialog": false,
  "displayedTutorial": false,
  "dockerAppLaunchPath": "/Applications/Docker.app",
  "extensionsEnabled": true,
  "filesharingDirectories": [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp",
    "/var/folders"
  ],
  "firstLaunchTime": 1651769810,
  "kubernetesEnabled": false,
  "kubernetesInitialInstallPerformed": false,
  "lastLoginDate": 0,
  "latestBannerKey": "",
  "licenseTermsVersion": 2,
  "memoryMiB": 4096,
  "onlyMarketplaceExtensions": false,
  "openUIOnStartupDisabled": false,
  "overrideProxyExclude": "",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "proxyHttpMode": "system",
  "settingsVersion": 17,
  "showExtensionsSystemContainers": false,
  "showKubernetesSystemContainers": false,
  "socksProxyPort": 0,
  "swapMiB": 1024,
  "tipLastId": 0,
  "tipLastViewedTime": 0,
  "updateAvailableTime": 0,
  "updatePopupAppearanceTime": 0,
  "updateSkippedBuild": "",
  "useCredentialHelper": true,
  "useNightlyBuildUpdates": false,
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVpnkit": true,
  "useWindowsContainers": false,
  "versionPack": "default",
  "vpnKitAllowedBindAddresses": "0.0.0.0",
  "vpnKitMTU": 1500,
  "vpnKitMaxConnections": 2000,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": true,
  "vpnkitCIDR": "192.168.65.0/24",
  "wslEngineEnabled": false
}
```
my config.json 
`{"credsStore":"desktop"}`

my daemon.json
```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
```

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. I don't know, just try to pull an image : `docker pull mysql `                                                                                                                     
```
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.1:3128: connect: connection refused
```

**Comment by trungutt** [comment]
We had a little issue on Hub stability last week https://status.docker.com/pages/history/533c6539221ae15e3f000031, please try again `docker pull` call to see

**Comment by omontigny** [comment]
@trungutt  
Thank you for your message but problem still there.
I'm sure it's on my computer but I don't know where. typically It's working well from my raspberry .

**Comment by mickare** [comment]
The proxy logfile shows a lot of the same warnings.

`~/Library/Containers/com.docker.docker/Data/log/vm/http-proxy.log`
```
[2022-05-10T12:19:06.039614397Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="/vm/httpproxy <-"
[2022-05-10T12:19:06.039200384Z][http-proxy][I] rewritten http_proxy=
[2022-05-10T12:19:06.039272832Z][http-proxy][I] rewritten https_proxy=
[2022-05-10T12:19:06.039954334Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="http_proxy="
[2022-05-10T12:19:06.040075551Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="https_proxy="
[2022-05-10T12:19:06.040100745Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="no_proxy="
[2022-05-10T12:19:06.040155118Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="transparent HTTP ports: []"
[2022-05-10T12:19:06.040156860Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="transparent HTTPS ports: []"
[2022-05-10T12:19:06.044234785Z][http-proxy][I] time="2022-05-10T12:19:06Z" level=info msg="/vm/httpproxy -> listening on http.docker.internal:3128: listen tcp 192.168.65.1:3128: bind: cannot assign requested address"
```

**Comment by gurix** [comment]
Happened to me as well. The same situation as a couple of weeks ago. 

My workaround was to copy the image to an archive using https://github.com/containers/skopeo. I only need to copy the image on a machine that has no access to the private registry and this registry is only accessible by proxy from the development machine.

**Comment by mickare** [comment]
Reverting back to version 4.5.0 and now it works again!
https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-450

**Comment by omontigny** [comment]
I confirm @mickare  It's working for me too !! 
thanks a lot . 
So there is a bug somewhere ....

**Comment by gzhh** [comment]
Same problem at version 4.8.1.
Reverting back to version 4.5.0 @mickare.
It's working for me too.
