### ISSUE TITLE
No proxy settings in Docker Desktop not used

### ISSUE THREAD

**Issue by RobMcA** [docker/for-mac#6307]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E4E318E8-BF11-41AE-BF6C-7824A5B9B054/20220506200629

### Expected behavior

Calls within a container to URLs use the 'no proxy' settings in Docker Desktop and do not call the proxy server.

### Actual behavior

Calls to URLs of domains that listed in 'no proxy' settings still contact the proxy server and fail.

### Information

I'm fairly confident this problem is new, but it has been many versions since I last tried.

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.7.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```

Which is a strange report since I'm able to run containers.

#### Pre-requisite 
- you must be running behind a proxy server
- the manual proxy server settings must be configured in docker desktop
```
docker info | grep -i proxy

 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal,localhost,127.0.0.1,.local,.us.example.com,.examplecorp.com,.examplevcn.com,kubernetes.docker.internal
  hubproxy.docker.internal:5000
```

1. Bash into a linux container. `docker run --rm -it oraclelinux:8 /bin/bash`
2. run curl to a server on the no proxy list `curl -v http://api.us.example.com`. Call will fail with an error response from the proxy server.
3. compare to run the same curl outside a docker container and the same call will succeed.
4. disable the manual proxy settings and the call will success as it will go direct to the server. But calling `curl -v https://www.google.com/` will fail as the proxy server is needed to route the call to the internet.

**Comment by shixlaw** [comment]
Same here. 

Using docker desktop version 4.8.1

changelog:

Bug fixes and minor changes
Introduced reading system proxy. You no longer need to manually configure proxies unless it differs from your OS level proxy.

This does not work. Tried to set the proxy setting via the docker desktop gui. Tried to set it via the system settings in mac. Tried to set proxy while exporting it through terminal

Nothing worked. Docker is not reading any proxy setting.

**Comment by shixlaw** [comment]
> For me it's reading it, but not the no-proxy. And I don't use a system level proxy.

Which Docker Version are you using? Which OS and how did you set it?

**Comment by shixlaw** [comment]
Ok now i get it. 
I was also using Docker Desktop Version: 4.7.1 as you.
no_proxy as you described also was not working for me. After that i upgraded to the newer Version of Docker and now none proxy setting is functional

**Comment by RobMcA** [comment]
I just tried it again on 4.8.1 and can confirm it now works - no proxy is used with my manual proxy configuration.
