### ISSUE TITLE
docker --device /dev/vboxdrv on top of mac Virtualbox, cannot be seen in container

### ISSUE THREAD

**Issue by leeee-me** [docker/for-mac#6308]
I am trying to run BOINC in docker by
https://github.com/BOINC/boinc-client-docker

And more specifically, I am trying to use Dockfile.virtualbox inside.

When it runs, it would like this:

docker run -d \
  --name boinc \
  --device=/dev/vboxdrv:/dev/vboxdrv \
  --net=host \
  --pid=host \
  -v /opt/appdata/boinc:/var/lib/boinc \
  -e BOINC_GUI_RPC_PASSWORD="123" \
  -e BOINC_CMD_LINE_OPTIONS="--allow_remote_gui_rpc" \
  boinc/client:virtualbox

However, inside the container, there is no mapping of underlying /dev/vboxdrv promoted from host.

I also tried sudo docker, or --privileged option to run. No use.

I googled and heard that docker on MacOS is running a type hypervisor VM, which means no way to promote any specific device driver from host MacOS to docker guest.

However, in experimental feature, it looks like Big Sur has some virtualization features... can it be more powerful and more feature-wise to support type 1 hypervisor (something like that as Ubuntu LTS, Virtualbox, and docker-ce?

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

MacOS host's /dev/vboxdrv can be seen in container, and detected, and used by BOINC's project, such as Rosetta@Home.

### Actual behavior

No /dev/vboxdrv can be seen, and BOINC client cannot detect that in container, then no way for any project such as Rosetta@Home to use that.

### Information

  - macOS Version: Monterey 12.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.8.0 (78933)

### Steps to reproduce the behavior

Build container like I mentioned above the head of this post. and run it, and exec into via /bin/bash, and check it

**Comment by joe0BAB** [comment]
Hi @leeee-me! Thank you for reporting this issue. Please help me understand correctly: Are you trying to use Docker in parallel to Virtualbox and try to use it inside a container? Or are you using Docker inside Virtualbox? Or does your image depend on virtualbox but virtual box doesn't work inside the container?

**Comment by leeee-me** [comment]
I

> Hi @leeee-me! Thank you for reporting this issue. Please help me understand correctly: Are you trying to use Docker in parallel to Virtualbox and try to use it inside a container? Or are you using Docker inside Virtualbox? Or does your image depend on virtualbox but virtual box doesn't work inside the container?

It's the first case, Rosetta@Home app run inside docker, but it calls Virtualbox outside docker, which is in parallel installed on host OS of Ubuntu. (I did not think Virtualbox can be run inside a docker because it installed special Linux kernel modules vboxXX)
