### ISSUE TITLE
Freeze during startup

### ISSUE THREAD

**Issue by fmozturk** [docker/for-mac#631]
### Expected behavior

Docker will start.
### Actual behavior

It says "Docker is running". But no other menu items are active.
### Information

Diagnostic ID: 27EF856B-F70D-4996-998D-816213809A1C
[20160915-143937.tar.gz](https://github.com/docker/for-mac/files/474512/20160915-143937.tar.gz)
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)

Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/27EF856B-F70D-4996-998D-816213809A1C/20160915-143937.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/fmozturk/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/fmozturk/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
### Steps to reproduce
1. Download Docker.dmg from docker site
2. Install
3. Try to start

**Comment by samoht** [comment]
Do you still have that issue? The logs that you updated are unfortunately empty. If you still see problems, could you please upload a new diagnostic to our remote server so that we can investigate. Thanks!

**Comment by fmozturk** [comment]
No problem. Thanks.

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/27EF856B-F70D-4996-998D-816213809A1C/20161012-101804.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

**Comment by samoht** [comment]
I still cannot see your logs. Did you choose "Diagnostic & Upload" in the "Diagnostic & Feedback" menu item?

**Comment by fmozturk** [comment]
Before I did "Diagnose Only" option, copy and paste result.

Now I did "Diagnose & Upload". ID is 27EF856B-F70D-4996-998D-816213809A1C

**Comment by samoht** [comment]
Ok I got your new logs, thanks! I will have a look to try to understand your issue.

**Comment by samoht** [comment]
Unfortunately, it seems that some of your logs are empty. Our diagnostic tool needs to be able to call `syslog`. Can you try to run:

```
$ syslog -F '$Time $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message' -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker > /dev/null
```

and report the error messages if any? Thanks!

**Comment by fmozturk** [comment]
Your command gave error:

NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.

So I tried

log show | grep Docker >> docker.log

But I think, it doesn't have day 2016-0915. Anyway I am attaching output file.
[docker.log.zip](https://github.com/docker/for-mac/files/524222/docker.log.zip)

**Comment by samoht** [comment]
Thanks! Can you try:

```
syslog -F '$Time $Host $(Sender)[$(Facility)][$(PID)] <$((Level)(str))>: $Message' -k Sender Seq docker -o -k Sender Seq Docker -o -k Message Seq docker -o -k Message Seq Docker > docker-system.log
```

and check if `docker-system.log` contains something useful?

**Comment by samoht** [comment]
Or `log show | grep docker >> docker-system.log` if the previous step didn't work (ie. the same thing as your last command but with `docker` instead of `Docker`).

**Comment by fmozturk** [comment]
[docker-system.log.zip](https://github.com/docker/for-mac/files/524664/docker-system.log.zip)

**Comment by samoht** [comment]
The only weird thing that I can see in your logs is:

```
2016-10-12 10:17:39.303448+0300 0x3cb59d   Fault       0x8000000000213f70   124    cfprefsd: (CoreFoundation) [com.apple.cfprefsd.User Defaults Daemon] attempt to write to a container /var/root/Library/Group Containers/group.com.docker that does not yet exist. Using client-provided container path without resolving symlinks.
```

I am not sure if it is the real source of the issue, but that's very strange that no `com.docker.*` service seems to do any useful work at all... I will see with the team if someone else as a better idea.

**Comment by ijc25** [comment]
@fmozturk sorry for the delay. If you are still have issues please could you try a new diagnostic upload with the latest stable (1.12.3) which should be able to collect a full set of logs even on Sierra and generally collects much better diagnostics.

**Comment by fmozturk** [comment]
I did not have any issue after I upgrade to 1.12.2. Now I run 1.12.3 and no problem. Beside I can say, 1.12.3 feels like more smooth.
