### ISSUE TITLE
 Mac M1 - DD0012: Network checks failed

### ISSUE THREAD

**Issue by uilianries** [docker/for-mac#6312]
- [ X ] I have tried with the latest version of Docker Desktop
  - [ X ] I have tried disabling enabled experimental features
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: 7D0D0AED-5F98-429C-8C30-9E918D9256E1/20220510153005

### Actual behavior
- Can not export ports, which means, I can not start a service and connect through tcp/udp port.
- Ports are free, checked with `lsof`

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Apple M1 Max
  - Docker Desktop Version: 4.8.1

- I already added Docker to firewall to accept incoming data
- It's a fresh Docker installation, never worked before
- I'm not using any experimental feature, neither Kubernetes

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
% /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-05-10T15:29:32.075673000Z][com.docker.diagnose][I] ipc.NewClient: cb2c70cc-diagnose-network -> <HOME>/Library/Containers/com.docker.docker/Data/diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd4
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x104cd40e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x104cd40e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x44
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x104cd40e0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x84
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x104cd40e0, 0x140003e7728)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x3c
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140003e7728)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x78
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1047b80a0?, 0x14000377890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x104cd4260, 0x104087fa0?, {0x14000377b08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x178
[main.checkCmd({0x140001b6010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:132 +0xe0
[main.main()
[	common/cmd/com.docker.diagnose/main.go:98 +0x308
[2022-05-10T15:29:32.075768000Z][com.docker.diagnose][I] (d04be864) cb2c70cc-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.28.99.94","10.100.134.175","100.64.0.1"]}
[2022-05-10T15:29:32.613159000Z][com.docker.diagnose][W] (d04be864) cb2c70cc-diagnose-network C<-S af3d8a56-diagnosticsd POST /check-network-connectivity (537.295292ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

### Steps to reproduce the behavior
--

**Comment by m04ph3u5** [comment]
The problem seems to be exactly the same on the new Docker Desktop 4.9.0. Network calls hanging and no port bound on the host. `diagnose check` output is exactly the same as posted by @uilianries

**Comment by uilianries** [comment]
I just updated to the version **4.9.0** and I still have the same problem.

New validation:

Diagnostics ID: 7D0D0AED-5F98-429C-8C30-9E918D9256E1/20220606082717

Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-06-06T08:32:56.314061000Z][com.docker.diagnose][I] ipc.NewClient: 3745da53-diagnose-network -> <HOME>/Library/Containers/com.docker.docker/Data/diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd4
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x103a28180)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x103a28180)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x44
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x103a28180)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x84
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x103a28180, 0x1400024b728)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x3c
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x1400024b728)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x78
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1035084e0?, 0x140003df890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x103a28300, 0x102dd1df0?, {0x140003dfb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x178
[main.checkCmd({0x140001b0010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:132 +0xe0
[main.main()
[	common/cmd/com.docker.diagnose/main.go:98 +0x308
[2022-06-06T08:32:56.316918000Z][com.docker.diagnose][I] (793fb658) 3745da53-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.0.25","100.64.0.1"]}
[2022-06-06T08:32:56.847739000Z][com.docker.diagnose][W] (793fb658) 3745da53-diagnose-network C<-S 54aba1b5-diagnosticsd POST /check-network-connectivity (530.790875ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
```

**Comment by margot-vogo** [comment]
Network failure is not caused by a docker desktop error, but macos firewall settings (Enabled stealth mode) https://support.apple.com/en-gb/guide/mac-help/mh11783/mac
This setting prevents the network from responding to pings, etc.

**Comment by uilianries** [comment]
> Network failure is not caused by a docker desktop error, but macos firewall settings (Enabled stealth mode) [support.apple.com/en-gb/guide/mac-help/mh11783/mac](https://support.apple.com/en-gb/guide/mac-help/mh11783/mac) This setting prevents the network from responding to pings, etc.

That's not my case! Even disabling Stealth Mode, either turning off the Firewall, does not change my result. Same output error. Anyway, thank for sharing that information.

**Comment by midsimm** [comment]
Even I am facing the same issue with the exact same logs as posted by @uilianries .

**Comment by sageavaa** [comment]
Same issue. Network calls will randomly drop every few minutes and have to restart docker to make it work again. 
MacOS 12.4 Intel Chip
Docker 4.8.2

Even tried replacing host.docker.internal with host's IP, no luck so far.

**Comment by maximilianosilva** [comment]
Same issue on 
windows 10  
dockerdesktop 4.9.1 

[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-06-17T19:18:10.543677800Z][com.docker.diagnose.exe][I] ipc.NewClient: 809f5a37-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1167960)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1167960)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x1167960)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1167960, 0xc00000f730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00000f730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb2cdc0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc00006a3d0?, 0xc00006a3d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-06-17T19:18:10.544179200Z][com.docker.diagnose.exe][I] (f44e3e50) 809f5a37-diagnose-network C->S diagnosticsd POST[2022-06-17T19:18:11.059156100Z][com.docker.diagnose.exe][W] (f44e3e50) 809f5a37-diagnose-network C<-S c1d80f07-diagnosticsd POST /check-network-connectivity (514.9711ms): failed to ping host: exit status 1

**Comment by bobrossthepainter** [comment]
similar issue for me with the m1 apple silicon. Suddenly icmp pings are not answered anymore from within docker containers to external hosts. dns resolution still works. Only a docker restart helps...

**Comment by jacopolanzoni** [comment]
Same issue. I am on macOS Monterey Version 12.4 with processor 2.6 GHz 6-Core Intel Core i7 and Docker Desktop 4.10.1 (82475).

**Comment by PipeKnight** [comment]
Same issue here :(
```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-07-29T23:42:02.911149000Z][com.docker.diagnose][I] ipc.NewClient: 6e2429a3-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xc8
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x10334f940)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x10334f940)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x44
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x10334f940)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x84
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x10334f940, 0x140004d3718)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x3c
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140004d3718)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x78
[common/pkg/diagkit/gather/diagnose.walkOnce(0x102e25ee0?, 0x140002ef890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x10334fac0, 0x14000390fc0?, {0x140002efb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x164
[main.checkCmd({0x140001b8010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xe0
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x310
[2022-07-29T23:42:02.912084000Z][com.docker.diagnose][I] (f9aa6a49) 6e2429a3-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.20.14.80","192.168.119.83"]}
[2022-07-29T23:42:03.492128000Z][com.docker.diagnose][W] (f9aa6a49) 6e2429a3-diagnose-network C<-S 54a75517-diagnosticsd POST /check-network-connectivity (580.117125ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

I tried to restore Docker to default settings, reinstalled it, turned off Firewall - nothing worked yet

**Comment by dannykansas** [comment]
We have about 4-5 devs with this issue. We're Docker Enterprise subscribers (doubt that has any impact, but you never know).

All versions that show problems are 4.10+, and primarily `4.10.1`

**Comment by Colbiocin** [comment]
I have similar issue but I discovered that it is manifesting only when connected to a VPN (using OpenVPN in my case)

**Comment by qgadrian** [comment]
This seems to be fixed when updating to macOS 12.6

**Comment by g1m0-enerbrain** [comment]
Same issue with MacOS 12.6.1 (M1)
Docker Desktop 4.13.0 (89412)
No firewall activated and no antivirus interaction

/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-10-28T17:51:29.307745000Z][com.docker.diagnose][I] ipc.NewClient: c54d6a12-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xc8
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x104d37be0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x104d37be0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x104d37be0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x104d37be0, 0x140002f5718)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x88
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x104d37d60, 0x140002f5718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1047f5a60?, 0x1400059f890)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x104d37d60, 0x1400012e380?, {0x1400059fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x140001a8010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x30c
[2022-10-28T17:51:29.308366000Z][com.docker.diagnose][I] (af8ee409) c54d6a12-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.90.36","10.33.33.1"]}
[2022-10-28T17:51:29.833258000Z][com.docker.diagnose][W] (af8ee409) c54d6a12-diagnose-network C<-S dfcabf20-diagnosticsd POST /check-network-connectivity (524.888667ms): failed to ping host: exit status 1

[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Check your host firewall and anti-virus settings in case they are blocking the VM.

**Comment by xstast24** [comment]
> Same issue with MacOS 12.6.1 (M1) Docker Desktop 4.13.0 (89412) No firewall activated and no antivirus interaction
> 

I have the same issue, the same system + docker version. It seems like it appeared after docker update (I'm not sure what version I had previously).

**Comment by AdilusPrimus** [comment]
Same thing here and it only occurs on my Mac Book Silicon  (M1).
No problems at all on my Intel Mac Book but it does not seem to have the same Corporate Policies configurations.
We have Cisco Any Connect as VPN  and  it conflicts with the Default Range of Its configured by Default in Docker Desktop.
So initially I thought that it was a Routing Problem or a conflicting  ip address that was allocated to the  targeted containers used in our projects.
But I have realized that on the arm64 laptop every Minikube start will produce approximately the same error and whatever the k8s version that we are pointing  to:
`minikube start --driver=docker --embed-certs  --kubernetes-version v1.23.13` or
`minikube start --driver=docker --embed-certs  --kubernetes-version v1.23.15`.
So I have observed that when I issue a Minikube status command it always ending up producing this output:

`minikube status
E1205 00:16:02.598127   14714 status.go:415] kubeconfig endpoint: extract IP: "minikube" does not appear in /Users/john.doe/.kube/config
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Misconfigured`

So I always end up updating the kubectl context, then stopping  and restarting Minikube and it ends up ok.
But it was not that behaviour prior to Docker Desktop 4.13 and prior of using the new Apple Virtualization framework instead of hyperkit and VirtioFS. for file sharing (for the containers).

<img width="1029" alt="Screen Shot 2022-12-05 at 12 40 37 AM" src="https://user-images.githubusercontent.com/3187466/205558276-e5d5fd86-0bad-4e55-b24f-0ca89acbe91a.png">
s).

`minikube update-context                                                                                                     
🎉  "minikube" context has been updated to point to 127.0.0.1:50119
💗  Current context is "minikube"
John.doe@mac-book-pro:~ » minikube status
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured

John.doe@mac-book-pro:~ » minikube stop                                                                                                              
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🛑  1 node stopped.
John.doe@mac-book-pro:~ » minikube start
😄  minikube v1.28.0 on Darwin 12.6.1 (arm64)
    ▪ KUBECONFIG=/Users/John.doe/.kube/config
✨  Using the docker driver based on existing profile
❗  docker is currently using the stargz storage driver, consider switching to overlay2 for better performance
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase:  0 B [__________________________] ?% ? p/s ?^R
    > gcr.io/k8s-minikube/kicbase:  0 B [______________________] ?% ? p/s 1m29sr
🔄  Restarting existing docker container for "minikube" ...
❗  This container is having trouble accessing https://registry.k8s.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm:  40.56 MiB / 40.56 MiB [-------------] 100.00% 5.82 MiB p/s 7.2s
    > kubectl:  41.56 MiB / 41.56 MiB [--------------] 100.00% 4.19 MiB p/s 10s
    > kubelet:  104.74 MiB / 104.74 MiB [------------] 100.00% 8.36 MiB p/s 13s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default`

So do you guys have experimented somehow the same kind of issues? By this I mean a Corporately controlled computer with policies securing the networking (process, VPNs...)
If you have a hint it would be much appreciated.
Cheers!

**Comment by AdilusPrimus** [comment]
> Same thing here and it only occurs on my Mac Book Silicon  (M1).
> 
> No problems at all on my Intel Mac Book but it does not seem to have the same Corporate Policies configurations.
> 
> We have Cisco Any Connect as VPN  and  it conflicts with the Default Range of Its configured by Default in Docker Desktop.
> 
> 
> 
> So initially I thought that it was a Routing Problem or a conflicting  ip address that was allocated to the  targeted containers used in our projects.
> 
> 
> 
> But I have realized that on the arm64 laptop every Minikube start will produce approximately the same error and whatever the k8s version that we are pointing  to:
> 
> `minikube start --driver=docker --embed-certs  --kubernetes-version v1.23.13` or
> 
> `minikube start --driver=docker --embed-certs  --kubernetes-version v1.23.15`.
> 
> 
> 
> So I have observed that when I issue a Minikube status command it always ending up producing this output:
> 
> 
> 
> ```
> 
> minikube status
> 
> E1205 00:16:02.598127   14714 status.go:415] kubeconfig endpoint: extract IP: "minikube" does not appear in /Users/john.doe/.kube/config
> 
> minikube
> 
> type: Control Plane
> 
> host: Running
> 
> kubelet: Stopped
> 
> apiserver: Stopped
> 
> kubeconfig: **Misconfigured**
> 
> ```
> 
> 
> 
> So I always end up updating the kubectl context, then stopping  and restarting Minikube and it ends up ok.
> 
> But it was not that behaviour prior to Docker Desktop 4.13 and prior of using the new Apple Virtualization framework instead of hyperkit and VirtioFS. for file sharing (for the containers).
> 
> 
> 
> <img width="1029" alt="Screen Shot 2022-12-05 at 12 40 37 AM" src="https://user-images.githubusercontent.com/3187466/205558276-e5d5fd86-0bad-4e55-b24f-0ca89acbe91a.png">
> 
> s).
> 
> 
> 
> ```
> 
> minikube update-context                                                                                                     
> 
> 🎉  "minikube" context has been updated to point to 127.0.0.1:50119
> 
> 💗  Current context is "minikube"
> 
> John.doe@mac-book-pro:~ » minikube status
> 
> minikube
> 
> type: Control Plane
> 
> host: Running
> 
> kubelet: Stopped
> 
> apiserver: Stopped
> 
> kubeconfig: **Configured**
> 
> 
> 
> John.doe@mac-book-pro:~ » minikube stop                                                                                                              
> 
> ✋  Stopping node "minikube"  ...
> 
> 🛑  Powering off "minikube" via SSH ...
> 
> 🛑  1 node stopped.
> 
> John.doe@mac-book-pro:~ » minikube start
> 
> 😄  minikube v1.28.0 on Darwin 12.6.1 (arm64)
> 
>     ▪ KUBECONFIG=/Users/John.doe/.kube/config
> 
> ✨  Using the docker driver based on existing profile
> 
> ❗  docker is currently using the stargz storage driver, consider switching to overlay2 for better performance
> 
> 👍  Starting control plane node minikube in cluster minikube
> 
> 🚜  Pulling base image ...
> 
>     > gcr.io/k8s-minikube/kicbase:  0 B [__________________________] ?% ? p/s ?^R
> 
>     > gcr.io/k8s-minikube/kicbase:  0 B [______________________] ?% ? p/s 1m29sr
> 
> 🔄  Restarting existing docker container for "minikube" ...
> 
> ❗  This container is having trouble accessing https://registry.k8s.io
> 
> 💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
> 
>     > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
> 
>     > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
> 
>     > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
> 
>     > kubeadm:  40.56 MiB / 40.56 MiB [-------------] 100.00% 5.82 MiB p/s 7.2s
> 
>     > kubectl:  41.56 MiB / 41.56 MiB [--------------] 100.00% 4.19 MiB p/s 10s
> 
>     > kubelet:  104.74 MiB / 104.74 MiB [------------] 100.00% 8.36 MiB p/s 13s
> 
> 
> 
>     ▪ Generating certificates and keys ...
> 
>     ▪ Booting up control plane ...
> 
>     ▪ Configuring RBAC rules ...
> 
> 🔎  Verifying Kubernetes components...
> 
>     ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
> 
> 🌟  Enabled addons: storage-provisioner, default-storageclass
> 
> 🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
> 
> ```
> 
> 
> 
> So do you guys have experimented somehow the same kind of issues? By this I mean a Corporately controlled computer with policies securing the networking (process, VPNs...)
> 
> If you have a hint it would be much appreciated.
> 
> Cheers!
> 
> 
> 
> 

Guy I do not know what happened here but Docker Desktop indicated that it needed sudo access for cresting some sort of links on my M1 Mac.
This was not an event that occurred during an upgrade so out of their blue.
Noe the same Minikube with the same files and folder as well as Docker image, works fine!
So this points me to say that if someone else has the same problem with the latest versions of Minikube sand Docker Compose (since docker is the driver) they should fully remove Docker and re-install it from their M1 Mac.

**Comment by kindermax** [comment]
> I have similar issue but I discovered that it is manifesting only when connected to a VPN (using OpenVPN in my case)

+1 same issue using with vpn (tunnelblick), after some time can not connect to remote resources (in my case this is a postgres and elasticsearch from python application, curl to elastic search also hangs).
H hack to make it work is to restart docker, shell into any docker containers and run `while true; do curl <resource>;sleep 5; done` - for some reason this keeps connection working.

**Comment by DanielYWoo** [comment]
same here.
I don't understand why this meaningless message, at least we should print the target URL and give me some clue, right?
