### ISSUE TITLE
Docker Desktop goes in Status "Docker Desktop stopped..." without any interaction  and does not finish ts self shoutdown

### ISSUE THREAD

**Issue by ickeundso** [docker/for-mac#6318]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: B0B019C8-0DE1-452F-AC20-31E518C7CDA6/20220515184842

### Expected behaviour
I run Docker Desktop on a mac mini M1 without a screen. From time to time I will login via vnc.
The Docker Desktop MUST keep running unless I are logged in or using a monitor.

### Actual behaviour
I run Docker Desktop on a mac mini M1 without a screen. From time to time I login via vnc.
The Docker Desktop runs for several days without any unexpected behaviour. (not logged in via vnc ).
But then after 1 day or 5 days ,I could not find a pattern when the docker engine / docker desktop  is switching to the a shutdown attempt.The shutdown process does not completed. So not only the docker desktop isn't  responsible oaly the docker engine cant be used. In the macOs status bar the docker animation usually seen for the start is running. A manual click on the docker icon and a click to restart will ask for a restart an a click to "yes" restart the docker engine. After that the docker desktop and the engine are back to normal state.

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.8.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
this is the output after a restart:
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

**Comment by JodieHag** [comment]
I have the same issue :(

**Comment by ickeundso** [comment]
here a new diagnose id , while docker is in state "Docker Desktop stopped ..."

B0B019C8-0DE1-452F-AC20-31E518C7CDA6/20220519104831

**Comment by ickeundso** [comment]
and also the diagnose check output. [diagnose-check.log.zip](https://github.com/docker/for-mac/files/8728470/diagnose-check.log.zip)

**Comment by ickeundso** [comment]
so for at least 10 days I disabled the experimental feature 'Use the new Virtualization framework' and now I could not recognise the described problem again. This is on my mac mini M1. But on my mac pro m1 max , I have the mentioned feature still enabled but this problem does never occur, just to mention

**Comment by ryanivoyant** [comment]
same issue - 2020 mac Mini M1 - any fixes?

**Comment by PlasmaSoftUK** [comment]
This is still an issue for me it goes in to the "Docker Desktop Stopped" state every few days. Running latest Docker Desktop, on a M1 MacMini with latest Ventura.

**Comment by meatch** [comment]
Same here. Tried killing `com.docker.backend process`. Force quitting the app and relaunching does not help. Everytime this happens I have to reboot my system.

**Comment by PlasmaSoftUK** [comment]
@meatch I found the only way to get it to restart without a reboot is to run these commands in Terminal via a script:

pkill -9 docker
pkill -9 Docker
sleep 10
open -a Docker

It kills the process, waits 10 seconds and then it will restart properly. My current solution is to run this every 6 hours via a script using cron, but it is far from an ideal resolution. I will be happy to submit diagnostics from my machine the next time it happens.
