### ISSUE TITLE
A file created with a RUN instruction should exist for the next RUN instruction

### ISSUE THREAD

**Issue by benDeMtp** [docker/for-mac#632]
Hello

I have the following problem using the docker beta for mac 1.12.1-beta25 (build: 11807)
The base image is a centos7

### Expected behavior

When I create directory or a file in a Dockerfile and I build the image, the directory or the file should exist in the next RUN instruction.

### Actual behavior
When I built an image with the following instructions:

```
RUN mkdir /var/run/postgresql && chmod 777 /var/run/postgresql && echo "test" > /var/run/postgresql/test
RUN cat /var/run/postgresql/test
```

Here is the result :

```
Step 2 : RUN mkdir /var/run/postgresql && chmod 777 /var/run/postgresql && echo "test" > /var/run/postgresql/test
 ---> Running in 6759c2e90d3b
 ---> 1f157ac0d927
Removing intermediate container 6759c2e90d3b
Step 3 : RUN cat /var/run/postgresql/test
 ---> Running in ca2b3e63a20c
cat: /var/run/postgresql/test: No such file or directory
```

### Information

I already had this problem before with docker-machine, but I managed to fix it by changing the storage driver and replacing " aufs " by "devicemapper "
I don't  know how to do with the beta version.

  - Diagnostic ID : BB4531D0-E3F3-45BA-8A51-2C503DCE9D9B
  - Docker for Mac: version: 1.12.1-beta25 (158f2ee)
  - OS X: version 10.11.6 (build: 15G1004)
  - base image : centos7

### Steps to reproduce the behavior
Copy this Dockerfile
```
FROM centos
RUN mkdir /var/run/postgres && chmod 777 /var/run/postgres && echo "test" /var/run/postgres/test
RUN cat /var/run/postgres/test
```

And run 
```
docker build -t issue .
```

Best Regards,

Benjamin

**Comment by justincormack** [comment]
There is a typo in your Dockerfile, it should read:
```
RUN mkdir /var/run/postgres && chmod 777 /var/run/postgres && echo "test" > /var/run/postgres/test
```

**Comment by benDeMtp** [comment]
You're right :)
So my reproduction steps are invalid.
In fact I tried to find an easy way to reproduce my real problem, but I made a mistake creating the sample file.

But I have the error as you can see in the result section :
```
Step 2 : RUN mkdir /var/run/postgresql && chmod 777 /var/run/postgresql && echo "test" > /var/run/postgresql/test
 ---> Running in 6759c2e90d3b
 ---> 1f157ac0d927
Removing intermediate container 6759c2e90d3b
Step 3 : RUN cat /var/run/postgresql/test
 ---> Running in ca2b3e63a20c
cat: /var/run/postgresql/test: No such file or directory
```

I don't how to find a reproduction step.

My true docker file look like that :
```
FROM PRIVATE_REGISTRY/postgres_data_9.5:7.0-SNAPSHOT

RUN mkdir /var/run/postgresql && chmod 777 /var/run/postgresql && echo "test" > /var/run/postgresql/test
RUN cat /var/run/postgresql/test

```
And result
```
Sending build context to Docker daemon 12.29 kB
Step 1 : FROM 10.93.191.105:5000/akio/uic_postgres_data_9.5:7.0-SNAPSHOT
 ---> 8347f593d109
Step 2 : RUN mkdir /var/run/postgresql && chmod 777 /var/run/postgresql && echo "test" > /var/run/postgresql/test
 ---> Using cache
 ---> 1f157ac0d927
Step 3 : RUN cat /var/run/postgresql/test
 ---> Running in 037478916b7b
cat: /var/run/postgresql/test: No such file or directory
The command '/bin/sh -c cat /var/run/postgresql/test' returned a non-zero code: 1
```

if I run the last successful  layer
```
docker run -ti 1f157ac0d927 /bin/bash
[root@ca97296bc781 root]# ls /var/run/
console  faillock  lock  log  sepermit  setrans  systemd  user  utmp
[root@ca97296bc781 root]# 
```
There is no directory postgresql

But I don't know how to reproduce it on others systems

**Comment by samoht** [comment]
Did you manage to reproduce this on other systems?

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
