### ISSUE TITLE
Docker Desktop 4.8.2 causes kernel panic when MBP goes to sleep

### ISSUE THREAD

**Issue by somiandras** [docker/for-mac#6330]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker Desktop don't cause kernel panic on my MBP when it is sleeping (or any other time). 

### Actual behavior

When putting the MBP to sleep, after a while it crashes with kernel panic resulting in the blinking folder icon, only when running Docker Desktop.

### Information

  - macOS Version: 12.4 Monterey (clean install)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.8.2

Kernel panic consistently happens when Docker Desktop is running when putting the laptop to sleep, or even though I quit Docker Desktop, the `com.docker.vmnetd` process keeps running in the background.

When I manually kill the `com.docker.vmnetd` process, my Mac doesn't crash.

I downgraded Docker Desktop to 4.5.0, ~~and it seems to work without crashing.~~

__Update:__ crashed with 4.5.0, when `com.docker.vmnetd` was running. I'll downgrade even further.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Put computer to sleep

**Comment by klemmari1** [comment]
Same happens for me, Intel MBP16 2019. Running latest version of Docker Desktop (4.8.2) and macOS Monterey 12.4.

This only happens when I'm on battery power over night and Docker is running when I put it the MacBook to sleep. So if the MacBook is plugged into my monitor which feeds it power, it will not crash.

If I quit Docker Desktop first, put the laptop to sleep and let it be on battery power over night, it will not crash.

Pretty much only settings I've touched on Docker Desktop are some resource settings, giving it a bit more CPU and memory.

**Comment by isaacatmann** [comment]
Curious on this as we're seeing a substantially higher number of kernel panics for our customers who use docker vs. those who don't:

What I'm looking for is the output of the following on a system that has the issue:

`pmset -g custom`

Also running this command to fully disable hibernation mode:

`sudo pmset -a hibernatemode 0`

Note: This will change the hibernate mode from it's default of 3, which means if the system runs out of battery it won't gracefully hibernate.  It's not ideal but I have a feeling it's causing docker to crash.

Additional testing, run this command which will enforce hibernation always, in theory it should cause Docker to crash more:

`sudo pmset -a hibernatemode 25`

**Comment by klemmari1** [comment]
Output of `pmset -g custom`:
```
Battery Power:
 lidwake              1
 lowpowermode         1
 standbydelayhigh     86400
 proximitywake        0
 standby              1
 standbydelaylow      10800
 ttyskeepawake        1
 highstandbythreshold 50
 gpuswitch            2
 powernap             0
 hibernatefile        /var/vm/sleepimage
 hibernatemode        3
 displaysleep         3
 sleep                1
 lessbright           1
 halfdim              1
 tcpkeepalive         1
 acwake               0
 disksleep            10
AC Power:
 lidwake              1
 lowpowermode         1
 standbydelayhigh     86400
 standbydelaylow      10800
 standby              1
 proximitywake        1
 ttyskeepawake        1
 hibernatemode        3
 powernap             0
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         30
 womp                 0
 networkoversleep     0
 sleep                1
 tcpkeepalive         1
 halfdim              1
 acwake               0
 disksleep            10
```

**Comment by somiandras** [comment]
Here's mine (pretty similar):
```
Battery Power:
 lidwake              1
 autopoweroff         1
 lowpowermode         0
 standbydelayhigh     86400
 autopoweroffdelay    259200
 proximitywake        0
 standby              1
 standbydelaylow      10800
 ttyskeepawake        1
 hibernatemode        3
 powernap             0
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         2
 sleep                1
 lessbright           1
 halfdim              1
 acwake               0
 tcpkeepalive         1
 disksleep            10
AC Power:
 lidwake              1
 autopoweroff         1
 lowpowermode         0
 standbydelayhigh     86400
 autopoweroffdelay    259200
 proximitywake        1
 standby              1
 standbydelaylow      10800
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         5
 womp                 1
 networkoversleep     0
 sleep                1
 tcpkeepalive         1
 halfdim              1
 acwake               0
 disksleep            10
```

I'm starting to suspect some more general issue, but couldn't triangulate it, yet ((maybe my SSD is just failing).

**Comment by klemmari1** [comment]
Ran the command `sudo pmset -a hibernatemode 0` but again caused kernel panic. Was running fine without any crashes until yesterday when I left Docker Desktop running when I put the MB to sleep. Normally I quit it before putting to sleep.

```
panic(cpu 2 caller 0xffffff800a4c3e0a): Sleep transition timed out after 180 seconds while creating hibernation file or while calling rootDomain's clients about upcoming rootDomain's state changes. Thread 0x29c071.
```

**Comment by MarcMielke** [comment]
same for me

```
⎈Default~ # pmset -g custom
Battery Power:
 lidwake              1
 lowpowermode         0
 standbydelayhigh     86400
 proximitywake        0
 standby              1
 standbydelaylow      10800
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         15
 sleep                1
 lessbright           0
 halfdim              1
 acwake               0
 tcpkeepalive         1
 disksleep            10
AC Power:
 lidwake              1
 lowpowermode         0
 standbydelayhigh     86400
 standbydelaylow      10800
 standby              1
 proximitywake        1
 ttyskeepawake        1
 hibernatemode        3
 powernap             1
 gpuswitch            2
 hibernatefile        /var/vm/sleepimage
 highstandbythreshold 50
 displaysleep         60
 womp                 1
 networkoversleep     0
 sleep                1
 acwake               0
 halfdim              1
 tcpkeepalive         1
 disksleep            10
```

**Comment by somiandras** [comment]
I think my issue is more general, not exclusively caused by Docker. Kernel panics happen when my laptop hibernates while on power supply. I'm closing this.
