### ISSUE TITLE
docker build pulls wrong architecture on Apple Silicon

### ISSUE THREAD

**Issue by ronald-fenner** [docker/for-mac#6335]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When building an image with both amd64 and arm64 architectures it should select the arm64 image to use

### Actual behavior
Without specifying platform it pulls the amd64 image instead

### Information

  - macOS Version: 12.4
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: 4.8.2 (79419)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. ... build the supplied docker file
  2. ... Look in docker desktop and it show a tag about it being amd64 and could have performance problems

Workaround is to specify the architecture with the build command to pull the correct image. Since i use a script to wrap the build command it detect whether it's on intel or arm for the mac and specifies the proper platform.

[Dockerfile-example.zip](https://github.com/docker/for-mac/files/8806893/Dockerfile-example.zip)

**Comment by StefanScherer** [comment]
You probably need a newer image, the tag that is used in the example uses an amd64-only image.
<img width="694" alt="Screenshot 2022-06-03 at 07 29 46" src="https://user-images.githubusercontent.com/207759/171792504-75d11b84-91a1-4d27-ab3c-a9e051a26728.png">

Newer images are listed with both amd64 and arm64 on Docker Hub. These should work out of the box.

**Comment by ronald-fenner** [comment]
Yes apparently I didn't check the tag . When i run the instance and check the version of airflow and the uname -a it does report the correct version and an amd64 image. They apparently just started building arm64 instance with the 2.3.x version

I'm guessing the emulation warning tag was for the hypervisor as i had switched to using the experimental feature of Apple's virtualization framework and it disappeared.
