### ISSUE TITLE
Cannot create docker image - "TLS handshake timeout" during fetching token

### ISSUE THREAD

**Issue by yb444bdocker** [docker/for-mac#6338]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Create docker image successfully
### Actual behavior
I get an error "failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: Get "https://auth.docker.io/token?scope=repository%3Ajboss%2Fwildfly%3Apull&service=registry.docker.io": net/http: TLS handshake timeout"
### Information

  - macOS Version: MacOS Monterrey 12.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 8.4.2

### Steps to reproduce the behavior

1. Cannot create docker image - the same command just stopped working: _docker build -t <name_of_image> -f Dockerfile ._
2. Upgrade of Docker Desktop to 4.8.2 did not help (actually nothing changed)
3. This is the output I get:

> user@macname folder % docker build -t <name_of_image> -f Dockerfile .

> [+] Building 12.2s (4/4) FINISHED                                                                                                          
>  => [internal] load build definition from Dockerfile                                                                                  0.0s
>  => => transferring dockerfile: 784B                                                                                                  0.0s
>  => [internal] load .dockerignore                                                                                                     0.0s
>  => => transferring context: 2B                                                                                                       0.0s
>  => ERROR [internal] load metadata for docker.io/jboss/wildfly:14.0.1.Final                                                          12.1s
>  => [auth] jboss/wildfly:pull token for registry-1.docker.io                                                                          0.0s
> ------
>  > [internal] load metadata for docker.io/jboss/wildfly:14.0.1.Final:
> ------
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: Get "https://auth.docker.io/token?scope=repository%3Ajboss%2Fwildfly%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
> 

4. When I run _curl -x <proxy_name> "https://auth.docker.io/token?scope=repository%3Ajboss%2Fwildfly%3Apull&service=registry.docker.io"_, I get the token without any problem.
5. **Workaround**! If I run the command _docker pull jboss/wildfly:14.0.1.Final_, and then - _docker build -t <name_of_image> -f Dockerfile ._, everything works successfully.

**Comment by jmaitrehenry** [comment]
I already had the same problem when my internet connection have a lot of packet loss/very high latency (like on 4G in a train). Doing the docker pull before can help, but it's a network error and you could have the same error with it. Just retry until it work.

**Comment by yb444bdocker** [comment]
Hi @jmaitrehenry 
I have to say that docker pull consistently succeeded, while docker build... consistently fails (if I have not run docker pull before). Believe me - I tried many times. Indeed sometimes it works, but very rarely.
Are there any ideas how to win it?

**Comment by defied** [comment]
Suddenly running into this as well.
I'm on bi-directional gigabit fiber and running a self-hosted ARC runner in a k8s cluster at home.

**Comment by defied** [comment]
Is anyone tracking these issues?

**Comment by yb444bdocker** [comment]
It seems not... Try the workaround I have meant above.

**Comment by AnnaYuS** [comment]
i'm also having this problem. It would be great if it was fixed.
