### ISSUE TITLE
docker process hangs

### ISSUE THREAD

**Issue by Rastusik** [docker/for-mac#634]
### Information

Diagnostic ID: C7BE9C3E-CE58-4FA7-A792-94E8327F6B73
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. no idea, it just stops and doesn't work after restart, I always need to reset everything to make it run again

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in C7BE9C3E-CE58-4FA7-A792-94E8327F6B73/20160915-152134.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Sep 14 21:32:08 mfris-mbpro kernel[kern][0] <Notice>: PM response took 165 ms (48516, com.docker.drive)
Sep 14 21:32:08 mfris-mbpro Docker[com.docker.driver.amd64-linux][48516] <Notice>: vcpu freeze complete: allowing sleep
Sep 14 21:32:08 mfris-mbpro Docker[com.docker.driver.amd64-linux][48516] <Notice>: vcpu 1 waiting for signal to resume
Sep 14 21:32:08 mfris-mbpro Docker[com.docker.driver.amd64-linux][48516] <Notice>: vcpu 0 waiting for signal to resume
Sep 14 22:22:38 mfris-mbpro Docker[com.docker.driver.amd64-linux][48516] <Notice>: Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.
Sep 14 22:22:38 mfris-mbpro Docker[com.docker.driver.amd64-linux][48516] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=f4644c04-db43-4c82-8f99-7f19024b4549,path=/Users/mfris/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/mfris/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Sep 14 22:22:38 mfris-mbpro Docker[com.docker.slirp][48514] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
```

There were a number of updates to the hypervisor transport system in the recently released Beta 27. If you are comfortable running a beta (we still do QA on it), you could give that a try and see if it stops the frequent crashing. /cc @ijc25

**Comment by Rastusik** [comment]
yes, today I switched back to beta, since I updated my OSX and the stable channel didn't work very well...
