### ISSUE TITLE
Bash completion file missing from Docker Desktop for Mac

### ISSUE THREAD

**Issue by sflanker** [docker/for-mac#6343]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

It should be possible/easy to enable bash completion for the docker command that is installed as part of Docker Desktop.

### Actual behavior

The Docker app for Mac used to have a bash completion file. As of v4.9.0 this file is no longer preset (although the docker-compose still exists).

Missing file: `/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion`

This breaks widely circulated instructions like https://gist.github.com/rkuzsma/4f8c1354a9ea67fb3ca915b50e131d1c

### Information

  - Is it reproducible? Yes, as far as I can tell. The problem was introduced after a performed a fresh reinstall of Docker Desktop.
  - Is the problem new? Yes. this file used to exist, now it is gone. I'm not sure one version removed the file because I missed some updates.
  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.9.0

**Comment by sflanker** [comment]
Confirmed the file is there in v4.8.2

**Comment by sflanker** [comment]
Definitely reproducible on a second Mac after a clean update from 4.8.2 -> 4.9.0

**Comment by mhhajeer** [comment]
confirmed, file missing after 4.9.0 update

**Comment by xeron** [comment]
I think it's been moved to `/Applications/Docker.app/Contents/Resources/etc/docker`. I changed my symlink to this location and autocomplete work again.

I have another problem tho, `/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion` doesn't seem to work…

**Comment by nicks** [comment]
Thanks for the report! Let me ask around about this.

**Comment by nicks** [comment]
We have a fix for this in 4.10

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.0 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100)
