### ISSUE TITLE
Container section makes Docker window white out and non-interactive

### ISSUE THREAD

**Issue by jpmc** [docker/for-mac#6344]
Recently updated my Docker Desktop from 4.8.2 to 4.9.0 on my M1 Macbook Pro, which is running Monterey 12.1.

Upon completing the update, it launches like normal, and I have made sure all other tabs/sections work as they did before.

The Container tab, which the changelog says was redesigned, turns the entire Docker window white. There are no UI elements present in the window and no "invisible" UI elements that I could detect via clicking or right-clicking.

However the entire app was not unresponsive or in a crashed state, if I close the blank window and then click the Docker icon in my menu bar/systray, I can reopen it to the Dashboard again where every other tab is accessible and interactive again. Though the Container menu item will once again lead me to the blank window as before.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2CE3EB5E-7411-490A-97F9-7A9A20E14C06/20220606202719

### Expected behavior

1. Click "Containers" in the left hand menu
2. See my list of Containers and other UI elements to manage them.

### Actual behavior

1. Click "Containers" in the left hand menu
2. Entire application window goes white, disappearing elements include:
    - the lefthand menu bar, cannot navigate away
    - the bottom status bar, that usually displays Hub connectivity/RAM/CPU details
    - the top blue window bar with "Docker Desktop" and the "Upgrade Plan" button

### Information

- It is reproducible on my machine, with the steps I gave above.
- The problem is new, in updating 4.8.2 to 4.9.0. 
- No other system changes or MacOS-related updates were made during this time.

 - macOS Version: Monterey 12.1 (21C52)
 - Intel chip or Apple chip: Apple M1 Pro
 - Docker Desktop Version: 4.9.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

> Starting diagnostics
> 
> [PASS] DD0027: is there available disk space on the host?
> [PASS] DD0028: is there available VM disk space?
> [PASS] DD0031: does the Docker API work?
> [PASS] DD0004: is the Docker engine running?
> [PASS] DD0011: are the LinuxKit services running?
> [PASS] DD0016: is the LinuxKit VM running?
> [PASS] DD0001: is the application running?
> [PASS] DD0018: does the host support virtualization?
> [PASS] DD0017: can a VM be started?
> [PASS] DD0015: are the binary symlinks installed?
> [PASS] DD0003: is the Docker CLI working?
> [PASS] DD0013: is the $PATH ok?
> [PASS] DD0007: is the backend responding?
> [PASS] DD0014: are the backend processes running?
> [PASS] DD0008: is the native API responding?
> [PASS] DD0009: is the vpnkit API responding?
> [PASS] DD0010: is the Docker API proxy responding?
> [PASS] DD0012: is the VM networking working?
> [PASS] DD0032: do Docker networks overlap with host IPs?
> [SKIP] DD0030: is the image access management authorized?
> [PASS] DD0019: is the com.docker.vmnetd process responding?
> [PASS] DD0033: does the host have Internet access?
> No fatal errors detected.

### Steps to reproduce the behavior
As described previously, from the top:
  1. Launch Docker Desktop
  2. Open the Dashboard window
  3. Click "Containers"

This brings me to the white screen. A shutdown and restart of Docker Desktop does not fix the behavior.

**Comment by DeepZeepOk** [comment]
I have the same issue after update to 4.9.0, but on Windows 10

**Comment by iamwahid** [comment]
Same issue happen in my Mac with intel chip after update to 4.9.0

**Comment by francois-gsk** [comment]
Same issue with Docker 4.9.0 on `Mac Intel - macOS 12.4` except… it's Blacked-out (Dark mode) 😂

**Comment by banujan6** [comment]
The same issue after updating docker to `4.9`

**Comment by lakeshorestudios** [comment]
Same issue here running docker 4.9.0 / MacBook Air M1 / macOS Monterey 12.4

**Comment by nicks** [comment]
Thanks everyone for reporting! I'm pretty sure this is the same issue as https://github.com/docker/for-win/issues/12759, so i'm going to close this to centralize the discussion over there.

**Comment by Lilley-Peter** [comment]
Same problem anyone find a fix?

**Comment by jpmc** [comment]
@Harshil258 @Lilley-Peter The windows issue that Nicks linked too has more ongoing updates.

Specifically as of now [in this post](https://github.com/docker/for-win/issues/12759#issuecomment-1153307618) They posted some new test builds of Docker Desktop that seem to currently fix the issue.

So hopefully if that build turns out to be fixed properly, they should be able to deploy it proper in the coming days.

**Comment by Lilley-Peter** [comment]
I ran the down command instead of the up command and it fixed the black
screen but I still can't run the up command without that bug.

**Comment by jeromecoupe** [comment]
Same here, only the containers screen is blank

**Comment by isaidspaghetti** [comment]
Same here, I get the "Docker Starting" screen then it goes blank

**Comment by nicks** [comment]
The discussion on https://github.com/docker/for-win/issues/12759 has fix builds and workarounds. I'm going to lock this conversation to ensure people see the main issue and don't get confused by this duplicate one.
