### ISSUE TITLE
Docker Desktop is not showing Images

### ISSUE THREAD

**Issue by cdsbrandon** [docker/for-mac#6347]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 14193637-463A-47D3-9357-4FE6F2C0F483/20220607205930

### Expected behavior
Docker images to appear in UI
### Actual behavior
No docker images appear in the UI even though I have many images when running docker images via cli
### Information

  - macOS Version: Monterey and previous version
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: 4.9.0 (80466)

### Steps to reproduce the behavior

  1. No steps to reproduce
  2. ...

**Comment by jeffreydwalter** [comment]
I had a similar issue with 4.9.0 not showing the Containers page. I cleared cache and data and it appears to be working. Might be worth a try in your case if you haven't already.

**Comment by jeffreydwalter** [comment]
Nevermind... After creating a couple of containers, it stopped working again.

**Comment by ev-w** [comment]
UI is completely borked for me; absolutely nothing appearing, just a blank window.

**Comment by abunch** [comment]
> UI is completely borked for me; absolutely nothing appearing, just a blank window.

Same, we have two early-look engineers that have loaded 4.9.0 and they're seeing the exact same thing.  Waiting before telling the remaining 70 to load the newest version.

<img width="1670" alt="Screen Shot 2022-06-08 at 9 04 13 AM" src="https://user-images.githubusercontent.com/2077840/172638063-2a99f5de-f353-4b5c-9455-214e83fa3eee.png">

**Comment by nicks** [comment]
@cdsbrandon do you see a blank screen like in this issue https://github.com/docker/for-win/issues/12759 ?

Or do you see a properly rendered image view without any images in the list?

**Comment by cdsbrandon** [comment]
@nicks I see a properly rendered image view without any images in the list

**Comment by SamuelMwangiW** [comment]
> > UI is completely borked for me; absolutely nothing appearing, just a blank window.
> 
> Same, we have two early-look engineers that have loaded 4.9.0 and they're seeing the exact same thing. Waiting before telling the remaining 70 to load the newest version.
> 
> <img alt="Screen Shot 2022-06-08 at 9 04 13 AM" width="1670" src="https://user-images.githubusercontent.com/2077840/172638063-2a99f5de-f353-4b5c-9455-214e83fa3eee.png">

Same case here, Docker Desktop shows a blank screen after the most recent update:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1807304/173011742-b656f523-2fa9-4792-871b-7467bf03635e.png">
Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

**Comment by SamuelMwangiW** [comment]
I have observed that it throws a blank screen when I have container(s) running and navigate to the `Containers` window. All others work fine. `Containers` is fine if I stop all running containers from the terminal.

Am running on Apple Silicon.

I have tried uninstalling as described by https://github.com/docker/for-mac/issues/6345#issuecomment-1151389285 then doing a fresh install with no luck.

**Comment by seahindeniz** [comment]
Same here, 4.9.0

<details>

https://user-images.githubusercontent.com/5789670/173243589-22fc694c-fc03-4a36-976c-3a8b0be657b6.mov

![image](https://user-images.githubusercontent.com/5789670/173244663-13fb7475-ff36-4914-b325-6aa9380c39ae.png)

</details>

**Comment by boxshadow** [comment]
same issue,
Docker for desktop 4.9.0 
macOS 12.4

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/8577474/173290117-36bb6ff3-c71d-481c-9988-508608c9a882.png">

**Comment by jdearie** [comment]
Same issue on Mac OS 12.4. The issue appeared after upgrading to v4.9.0

From https://github.com/docker/for-mac/issues/6351#issuecomment-1151499137
Workaround:
In v 4.9.0 you can add extensions. Add portainer and manage containers in the UI there .
The portainer UI is very capable and works in Docker Desktop ...

**Comment by lukeholder** [comment]
Same issue for me. Blank containers page. Other screens work. M1 Macbook Pro.

**Comment by nicks** [comment]
If you're having issues with a blank containers page, you've hit https://github.com/docker/for-win/issues/12759, which we released a fix for today. I'm going to mark all comments about blank container pages as off-topic, since the OP bug report was pretty clear that this is an unrelated issue about the images page.

**Comment by jcucuzza** [comment]
Having the same issue as OP

**macOs bigSur 11.6.7
Docker Desktop v4.10.0
Docker Engine v20.10.17**

**UI**
<img width="1634" alt="Screen Shot 2022-07-02 at 4 12 28 PM" src="https://user-images.githubusercontent.com/20457759/177015026-2258e2fd-59ee-4ff9-931f-2e4eccdf421e.png">

**CLI**
<img width="1328" alt="Screen Shot 2022-07-02 at 4 14 56 PM" src="https://user-images.githubusercontent.com/20457759/177015032-3465b403-26e5-48ac-99d0-7ea578ad6ed0.png">

**Comment by tchinchow** [comment]
Hello,

FYI: Same behaviour as @jcucuzza here:

```
xxx@XXXXX:~$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:39 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
  
I'm juste an casual user of docker-desktop / windows so I'm afraid I won't be able to provide much help.

**Comment by JocPelletier** [comment]
Same issue here 
![image](https://user-images.githubusercontent.com/13203202/177797245-3ae34a41-4563-4ab0-8d89-37b6fa9dcc00.png)

**Comment by tbuddhika** [comment]
Hi,
I'm also having the same issue.
I tried reinstalling the Docker Desktop as well but no luck.

I checked the Resources tab in Settings and the Disk image size is almost filled.
Then I resize the Disk image size and it warns me it deletes everything. 
I accepted it and as said all gone 😢 but now works fine 😊.

**Comment by PAVaillancourt-IvadoLabs** [comment]
Same issue and behaviour as jcucuzza

OS: macOS Monterey 12.4
Apple Chip (M1)

```
docker version

Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by RlyehDoom** [comment]
Same problem here:
`PS C:\Users\josel> docker version
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

**Comment by BentakApps** [comment]
Solved here. Click Troubleshoot (the bug icon on the toolbar) and Reset to factory defaults.

**Comment by GuilhermeMelo01** [comment]
> Solved here. Click Troubleshoot (the bug icon on the toolbar) and Reset to factory defaults.

but in this case we will have to download all the images again

**Comment by GuilhermeMelo01** [comment]
Maybe you are using docker in the wrong context 'Default' as in the image, try to change it to 'docker-desktop' that should work![image](https://user-images.githubusercontent.com/83541826/182913671-61f9c04e-d9bc-4b30-b8a9-f34e9509b4f8.png)

**Comment by dmilkie** [comment]
Why does the "context" affect what Docker Desktop shows?  I have this same problem (on Windows 11, using WSL2), and have _two_ contexts. I don't know why I have two, or where each of `default `and `desktop-linux` came from.  I tried `docker context use desktop-linux` but it didn't change the visible Docker Desktop images.  However, the command line `docker images `always works.

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by gerneio** [comment]
Can confirm that my image list in docker desktop showed back up immediately after the 4.12.0 update 👍
