### ISSUE TITLE
error docker

### ISSUE THREAD

**Issue by zzg378260356** [docker/for-mac#6348]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
Hmmm...looks like this issue is empty..please file an issue with more information. Thanks!
