### ISSUE TITLE
Docker Desktop shows tag tooltips as "ALL CAPS", leading to copy-paste issues.

### ISSUE THREAD

**Issue by NessDan** [docker/for-mac#6352]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 20220609193900

### Expected behavior

Hovering over an Image's Tag, highlighting the text in the Tooltip that pops up, then copying that text should copy the actual case-sensitive tag name.

### Actual behavior

The tag that's copied is ALL CAPS, leading to issues.

### Information

  - It is reproducible!
  - macOS Version: Mac OS Monterey 
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.9.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
➜  ~ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Hover over a tag.
  2. When the tooltip pops up, move your cursor _slightly_ below the text, but above the tooltip.
  3. Double click and you'll select the Tooltip text
  4. Copying that text leads to a tag that's ALL CAPS.

https://user-images.githubusercontent.com/304269/172930487-19967130-3570-4eaf-a143-2c933a20c894.mp4

<img width="349" alt="Screen Shot 2022-06-09 at 3 37 47 PM" src="https://user-images.githubusercontent.com/304269/172931498-bbb8e4ca-649c-4221-b2a9-7fb7cdc15513.png">

**Comment by lizzthabet** [comment]
thanks for keeping up with this issue, @NessDan! i missed linking to it in the latest docker desktop release notes. tooltip styles have been updated in [4.12.0](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-minor-changes) so they're no longer uppercase.
