### ISSUE TITLE
Updating Docker Desktop produces requests for connections to various unexplained domains

### ISSUE THREAD

**Issue by unikitty37** [docker/for-mac#6359]
I recently updated from Docker Desktop 4.6 to 4.9. After installation, Little Snitch asked for permission to connect to a large number of domains: portainer-io-assets.sfo2.cdn.digitaloceanspaces.com, cloudinary.com, epinio.io, gosh.run, k8slens.dev, okteto.com, and slim.ai.

Most of these seem to relate to Kubernetes, and I have the "Enable Kubernetes" option turned off.

There doesn't seem to be anything in the release notes explaining why Docker Desktop is making all these outbound connections on startup; users who use software such as Little Snitch are likely to be alarmed by this — I certainly was not expecting this to happen, and have no idea whether it's safe to allow them, or whether blocking them will impair Docker Desktop.

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: Unavailable — I get the error `Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': [object Object]` which is not terribly helpful.

### Expected behavior

The reason for making the connections should have been listed in the release notes. Additionally, if the connections related to the Kubernetes functionality, they probably shouldn't have been made when that is disabled (if they're downloading k8s updates, it would have been better to do it when the feature got turned on — at least that way, users with monitoring software would have some idea what's going on…)

### Actual behavior

Little Snitch asked for permission to let Docker Desktop contact a load of domains that I didn't recognise, and hadn't asked it to. I had to open each one in a browser to try and work out what's going on.

### Information

  - macOS Version:  macOS 12.4 (21F79)
  - Intel chip or Apple chip: M1 Max
  - Docker Desktop Version: 4.9.0 (80466)

The problem appeared when updating from 4.6 to 4.9; I was too busy to update Docker to 4.7 when it became available, and then forgot there were updates waiting until today, so I can't state for sure which version introduced these changes.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Install Little Snitch (https://www.obdev.at/products/littlesnitch/index.html)
  2. Install Docker Desktop 4.6, allowing connections for any specific domains Little Snitch asks for (do not just allow all connections, obviously :)
  3. In Docker Desktop's Preferences, go to Software Updates and check for updates, again allowing specific connections
  4. When Docker Desktop finishes upgrading and restarts, Little Snitch will show connection requests for the above domains

**Comment by nicks** [comment]
Thanks for reporting! I think this is probably related to Docker Desktop extensions (https://docs.docker.com/desktop/extensions/), but let me ask around to see what the expected behavior is and if there's a way to tighten up the requests here.

**Comment by nicks** [comment]
i've been told this is fixed now.
