### ISSUE TITLE
after restarting my computer docker is not working

### ISSUE THREAD

**Issue by gcabero** [docker/for-mac#636]
### Information

Diagnostic ID: 32E1E8D2-D09B-4970-AE67-9C3627EC30C1
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 32E1E8D2-D09B-4970-AE67-9C3627EC30C1/20160915-154113.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on.

May be related to docker/for-mac#785

The following log matches:
```
Sep 15 12:23:15 gemmas-imac Docker[com.docker.vmnetd][73726] <Notice>: User 501 has container folder /Users/gcc/Library/Containers/com.docker.docker/Data/s60
Sep 15 12:23:15 gemmas-imac Docker[com.docker.vmnetd][73726] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 15 12:23:15 gemmas-imac Docker[com.docker.vmnetd][73726] <Notice>: User 501 has container folder /Users/gcc/Library/Containers/com.docker.docker/Data/s60
Sep 15 12:23:15 gemmas-imac Docker[com.docker.vmnetd][73726] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 15 12:23:15 gemmas-imac Docker[com.docker.docker][73298] <Error>: Symlinks are not correctly installed.
Sep 15 12:23:25 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 0.00
Sep 15 12:23:26 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 1.00
Sep 15 12:23:26 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 2.00
Sep 15 12:23:26 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 3.00
Sep 15 12:23:26 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 4.00
Sep 15 12:23:26 gemmas-imac Docker[com.docker.docker][73298] <Notice>: progress 5.00
```

Please follow the resolution of #785 for updates on your issue. In the meantime, a workaround is to install the latest version of Docker.app and/or reset to factory settings.
