### ISSUE TITLE
[VirtioFS] Performance regression when seeding native Rails app with Dockerized-Postgres

### ISSUE THREAD

**Issue by bluz71** [docker/for-mac#6363]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I expect VirtioFS to have equal or superior performance to gRPC when seeding a native Ruby-on-Rails application with Dockerized-Postgres.

### Actual behavior

VirtioFS has inferior performance when seeding my personal Rails application.

Performance when seeding Postgres is roughly as follows:

|  Backend          | Database Seed Time, avg over multiple runs
|-------------------|-------------------------------------------
| Native, no Docker | 8mins
| Docker, default   | 20mins
| Docker, VirtioFS  | 29mins

### Information

- Apple Macbook Air with M1 process and 8GB RAM
- macOS Monterey version: `12.4`
- Docker Desktop for Mac version: `4.8.2 (79419)`

### Steps to reproduce the behavior

Prequisites
-----------
- Docker Desktop for Mac, installed and running
- Xcode with Command Line Tools installed
- [Homebrew](https://brew.sh), or an equivalent package manager

Setup Procedure
---------------
- `brew install chruby ruby-install postgresql@12 fnm`
- `fnm install --lts`
- Add `eval "$(fnm env)"` to `~/.bashrc` or equivalent and re-source shell environment.
- `npm install -g yarn`
- `ruby-install 2.7.3`
- Add `chruby 2.7.3` to `~/.bashrc` or equivalent and re-source shell environment
- `gem install bundler -v 2.2.20`
- `gem install -v 1.2.3 pg -- --with-pg-config=/opt/homebrew/opt/postgresql@12/bin/pg_config`
- Clone `https://github.com/bluz71/platters` repo, this is my Rails application
- `cd platters`
- `bundle install`
- `yarn install`
- Create Docker volume for postgres, `docker volume create pg12data`
- Download Postgres image, `docker image pull postgres:12-alpine`

Reproduce
---------
- Run Dockerized-Postgres, `docker container run -it --rm --name postgres -v pg12data:/var/lib/postgresql/data -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:12-alpine`
- Time a database seeding without VirtioFS: `time bin/rails db:reset`
- Time a database seeding withVirtioFS: `time bin/rails db:reset`

**Comment by fredericdalleau** [comment]
I am seeing this error. Any hint?
```
fredo@letchi platters % time bin/rails db:reset
Dropped database 'platters_development'
Dropped database 'platters_test'
Created database 'platters_development'
Created database 'platters_test'
rails aborted!
ActiveRecord::RecordNotFound: Couldn't find User without an ID
/Users/fredo/bluz71/platters/db/seeds.rb:97:in `block (2 levels) in <main>'
/Users/fredo/bluz71/platters/db/seeds.rb:96:in `times'
/Users/fredo/bluz71/platters/db/seeds.rb:96:in `block in <main>'
/Users/fredo/bluz71/platters/db/seeds.rb:87:in `each'
/Users/fredo/bluz71/platters/db/seeds.rb:87:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
bin/rails db:reset  0.77s user 0.18s system 51% cpu 1.838 total
```

**Comment by bluz71** [comment]
Ah yes, I forgot to note the need for the configuration environment. My bad.

The following environment variables need to be set:

- `SEEDED_ADMIN_EMAIL`
- `SEEDED_ADMIN_PASSWORD`
- `CONTACT_EMAIL`
- `SEEDED_USER_PASSWORD`

Or add them to a `config/application.yml` file.

**Comment by bluz71** [comment]
Set them to any old value, shouldn’t make a difference.

Good news is that the database connection is working, so you are close to getting it working.

**Comment by fredericdalleau** [comment]
Still getting this :
```
created teishalang@hamill.org 1234
user_count 0
Randomized  user 0
rails aborted!
ActiveRecord::RecordNotFound: Couldn't find User without an ID
```

**Comment by bluz71** [comment]
I will provide an application.yml file tomorrow which should get you going. I don't currently have access to my laptop at the moment, so here and now we are paused.

I probably missed a env-variable that needs setting up, or maybe a typo. We are close.

**Comment by bluz71** [comment]
Can you do `rails c` and then do `User.all` and `User.count`. I am confused if user rows are being created or not.

**Comment by bluz71** [comment]
A suggestion, just edit `db/seeds.rb` file and hard-code values in place of the `ENV` directives between lines 66 to 79. I still think the issues are there.

**Comment by fredericdalleau** [comment]
The rows are not created : maybe the postgres password needs to be specified. I tried to export POSTGRES_USER and PASSWORD without luck.

**Comment by bluz71** [comment]
I am finally back in front of my laptop (sorry for the delay).

Postgres user and password are likely to be fine since you were able to create the database table itself. I suspect the real issue was likely to be that the password selected was not longer than 9 characters, hence no users where being created. Rails User model has password length validation, which likely failed.

As noted earlier in this thread, the application environment was not set because in my first post I forget to provide a `config/application.yml` file with the secrets/credentials required.

Undo `db/seeds.rb` and any environment variable changes suggested above, instead just save the following to `config/application.yml`:

```
SECRET_KEY_BASE:         "4ahebk5nbdklk41a7f6cdc7d846b52f4567hngqlp756c8c7219337392f4444633b679f5d2fdc8d3fbafe756hn1234jk9f4667aa732d9e67ea1e1b69592d9ee33"
CONTACT_EMAIL:           "fred@example.com"
SEEDED_USER_PASSWORD:    "APassword77556"
SEEDED_ADMIN_EMAIL:      "john@example.com"
SEEDED_ADMIN_PASSWORD:   "AnotherPassword88453"
```

Also I forgot, `imagemagick` package is required, please install it `brew install imagemagick`.

**Comment by fredericdalleau** [comment]
Thanks it works now! For the numbers you shared on the other thread, the `rails db:reset` is running on the host in all three cases. Is `postgres` the only workload running in container?

**Comment by bluz71** [comment]
Excellent, we got there.

> is the `rails db:reset` running on the host in all three cases. Is `postgres` the only workload running in container?

Correct. `rails db:reset` runs on the host and `postgres` is the only containerised service.

**Comment by bluz71** [comment]
> is the `rails db:reset` running on the host in all three cases.

Sorry, to be clear, in the following table, the last two rows are containerised:

|  Backend          | Database Seed Time, avg over multiple runs
|-------------------|-------------------------------------------
| Native, no Docker | 8mins
| Docker, default   | 20mins
| Docker, VirtioFS  | 29mins

The first row is with Postges running native on macOS (not under Docker). 

The main crux of this issue is with respect to `VirtioFS` being slower than `gRPC`.

**Comment by jnfDev** [comment]
I had pretty good results on Docker + WordPress using the new experimental options, but recently, I started noticing some random slowdowns here and there. I tried to factory reset, but it didn't improve the situation.

I'm glad that anyone else is noticing it too, but why? Why did VirtioFS do pretty well at the beginning and now feel pretty slow?

**Comment by bluz71** [comment]
This issue is fresh and active.

`/remove-lifecycle stale` hopefully should mark this issue as fresh.

**Comment by bluz71** [comment]
@fredericdalleau,

The Docker Robot closed this issue; I think it did that due to inactivity, not because the issue has been fixed.

Can you please re-open it.....unless you have news to provide that this regression has indeed been fixed.

Cheers.

**Comment by lugosium** [comment]
Same for me, before Virtiofs with the delegated flag, my tests ran in ~27 minutes, with virtiofs they run in ~55 minutes... and many fail because of the slowness.

**Comment by o1y** [comment]
Same here. The performance with version 4.15.0 has become even worse. The response times have doubled since the update. Switching back to gRPC results in better response times.

**Comment by bluz71** [comment]
@fredericdalleau,

Can this issue be re-opened please.

Secondly, with a repeatable test case, is there any information you can provide about which VirtioFS is slower than gRPC with this workload?

Cheers.

**Comment by fredericdalleau** [comment]
@bluz71 it's hard to say exactly but my guess at the moment is that virtiofs on mac only caches host files permissions for a few seconds, while grpcfuse caches thoses for one hour. This cache time difference was there before Docker Desktop 4.15.0 and that may explain your results before 4.15.0 if your workload accesses lots of files accross a long period.
We are working on improving that.

**Comment by bluz71** [comment]
I just test Docker Desktop `v4.16.1` and with the test case (in the first post) I now find no performance difference between `gRPC FUSE` and `VirtioFS` on my M1 Macbook Air (2020 model year).

Somewhere between `v4.8.2` and `v4.16.1` the `VirtioFS` regression has been fixed. In my case `VirtioFS` is neither faster nor slower than `gRPC FUSE`; I hoped `VirtioFS` would be faster, but the current performance is fine for my use case. I will stick with `VirtioFS` since I understand that this is the preferred Docker Desktop file-sharing technology.

Since there no longer is a regression I will close this issue.

Many thanks.
