### ISSUE TITLE
Constantly getting FetchError: request to https://desktop.docker.com/tips.json failed

### ISSUE THREAD

**Issue by luisremis** [docker/for-mac#6366]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 24B65E5F-A9D7-4063-98EF-0A30333C4F39/20220617032736

### Expected behavior

Working offline normally. 

### Actual behavior

Constantly getting the following error when using docker desktop offline:

```
Error invoking remote method 'fetch-data': FetchError: request to https://desktop.docker.com/tips.json failed, reason: net::ERR_INTERNET_DISCONNECTED

```

This is even if I have disabled the "Show weekly tips" option.

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: v4.9.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-06-17T03:35:00.826867000Z][com.docker.diagnose][I] ipc.NewClient: 2415344a-diagnose-network -> Library/Containers/com.docker.docker/Data/diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd4
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x10196c180)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x10196c180)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x44
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x10196c180)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x84
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x10196c180, 0x140002b1728)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x3c
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140002b1728)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x78
[common/pkg/diagkit/gather/diagnose.walkOnce(0x10144c4e0?, 0x140003df890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x10196c300, 0x100d15df0?, {0x140003dfb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x178
[main.checkCmd({0x140001ae010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:132 +0xe0
[main.main()
[	common/cmd/com.docker.diagnose/main.go:98 +0x308
[2022-06-17T03:35:00.829245000Z][com.docker.diagnose][I] (7b4797f0) 2415344a-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.0.13","10.1.145.43"]}
[2022-06-17T03:35:01.351590000Z][com.docker.diagnose][W] (7b4797f0) 2415344a-diagnose-network C<-S d5311b89-diagnosticsd POST /check-network-connectivity (522.37925ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

**Comment by trungutt** [comment]
Hi Luis, thanks for reporting the issue. We found a way to reproduce that locally

**Comment by jk12559** [comment]
my company just updated us all to 4.9.1 in our air-gapped network and we are seeing the same issue on Windows.

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.0 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100)

**Comment by luisremis** [comment]
thanks!
