### ISSUE TITLE
Where is the home path defined?

### ISSUE THREAD

**Issue by NathanHazout** [docker/for-mac#6369]
I had to change my mac username recently, and rename my home folder.  
Now when I start Docker Desktop, I get a `Fatal Error: mkdir /Users/nathanha: permission denied` (`nathanha` being my old user).

I tried reset docker to factory defaults, I tried uninstall (via AppCleaner) and re-install, restart the mac.

Still it looks for my old home folder.  

Where is this defined? Or is there a better way to cleanly uninstall Docker?
The uninstall from the GUI does not work, probably because of that same fatal error

![Screen Shot 2022-06-19 at 11 18 25](https://user-images.githubusercontent.com/329834/174472175-9503b674-5ef4-4e2e-8b14-bf7e8d1e378b.png)
.

**Comment by nicks** [comment]
:thinking: I think we usually use `os.homedir()` https://nodejs.org/api/os.html#oshomedir, which should use the `$HOME` env variable. can you check that that's set correctly?

Have you tried deleting the `~/.docker` directory?

**Comment by NathanHazout** [comment]
I deleted ~/.docker, initially it didn't work but after several restarts it worked again.
Unfortunately I can't really pinpoint what fixed it

**Comment by nicks** [comment]
OK, thanks for the update. Let's close this since we've resolved your issue, and we can re-open if more users report this.
