### ISSUE TITLE
Non-volume mounts problem back again

### ISSUE THREAD

**Issue by misiek08** [docker/for-mac#6382]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior
It works.

### Actual behavior
It doesn't work.

### Information
  - Is it reproducible? *Yes, easily*
  - Is the problem new? *No* (https://github.com/docker/for-mac/issues/5124#issuecomment-744697395)
  - Did the problem appear with an update? *Probably yes*
  - A reproducible case: try to run CockroachDB on MacOS using dir mounts, not volumes.

  - macOS Version: 12.4
  - Intel chip or Apple chip: x86
  - Docker Desktop Version: 4.8.2

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
All passing.

### Steps to reproduce the behavior
https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html
Steps 1 and 2 is enough. After starting 3rd container one of them will die in <60s. No panic, no logs, just exit with code 1.

**Comment by nicks** [comment]
sorry to hear you're having trouble. For what it's worth, I was not able to reproduce the problem you're having on Docker Desktop 4.10.1. CockroachDB ran fine. If you're still having the problem after upgrading, can you upload a Diagnostic ID?

**Comment by misiek08** [comment]
Ok, so this is for sure comeback of this bug: https://github.com/docker/for-mac/issues/5124

We've confirmed it here: https://github.com/cockroachdb/cockroach/issues/81362#issuecomment-1194477073

**Comment by misiek08** [comment]
4.12 and the issue still exists. Diagnostics ID: 994B30AC-6F3C-4B85-99BB-870D883E9181/20220927101730

I tried running CockroachDB 1-2 minutes before generating diagnostics.

**Comment by misiek08** [comment]
Versions passing, new MacOS, but the issue still persists.

I'll try to reinstall docker by fully uninstalling it, but it didn't help last time. I have latest docker and MacOS version - manually created volumes work, "dynamic" (`-v path:path`) don't.

**Comment by Allsimon** [comment]
I can reproduce this issue on Apple M1 pro:

```shell
touch aFile.txt
docker run --rm -ti -v "$PWD":/tmp --entrypoint ls alpine /tmp
```

The file isn't found

Version:
- macOS 12.6.2
- Docker Desktop 4.15.0
- Engine 20.10.21

I had the exact same issue with Rancher Desktop, so I came back to Docker Desktop, everything worked perfectly fine yesterday, I didn't update anything and now volumes don't mount...
Restarting docker doesn't fix
