### ISSUE TITLE
Extremely low bandwidth from host to Docker container

### ISSUE THREAD

**Issue by welljsjs** [docker/for-mac#6385]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 19852691-CF95-4057-B2E5-CFA22F58B413/20220703121828

### Expected behavior
Host-to-Container bandwidth should be equal to or almost equal to the host-to-host available bandwidth.

### Actual behavior
Host-to-Container bandwidth is much lower than host-to-host bandwidth: We've measured the available bandwidth using [iPerf](https://iperf.fr) with the following results:

|Operating System|Client|Server|Bandwidth (measured with iPerf, see below)|
|---|---|---|---|
|macOS|Host|Host|~56.3 Gbits/sec|
|macOS|Host|Container|~350 Mbits/sec|
|Windows Pro 10|Host|Host|~5 Gbit/sec|
|Windows Pro 10|Host|Container|~680 Mbit/sec|

### Information

  - macOS Version: 12.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.9.1 (81317)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
segment 2022/07/03 14:26:49 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io: no such host
segment 2022/07/03 14:26:49 ERROR: 1 messages dropped because they failed to be sent and the client was closed

### Steps to reproduce the behavior

This is the content of our minimal Dockerfile:

```Dockerfile
FROM alpine:latest
RUN apk update && apk upgrade && \
  apk add --no-cache iperf bmon net-tools

EXPOSE 8020/tcp

ENTRYPOINT ["/bin/sh"]
```

We run the docker contains with the following command, publishing port 8020 (for TCP):
```sh
docker run -it -p 8020:8020/tcp alpine_container
```

We then start server in the container:
```sh
iperf -s -p 8020
```
to finally start the client on the host machine:
```sh
iperf -c -p 8020
```

Why is the host-to-container bandwidth so low (0.62% of the original host-to-host bandwidth for macOS)?

**Comment by amakhrov** [comment]
Is it the same problem reported in https://github.com/docker/for-mac/issues/3497 ? (not that somewhere down the line the discussion there diverged from the original issue to network performance from the container)

**Comment by welljsjs** [comment]
Not sure if that one applies to the Windows platform as well – I've posted this here but we've had the same experience for both Windows and macOS but there's only one forum per platform.
