### ISSUE TITLE
Failed to mount cgroups hierarchy at '/sys/fs/cgroup/freezer': Operation not permitted

### ISSUE THREAD

**Issue by uladzimir-shelhunou** [docker/for-mac#6386]
Preconditions.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [N/A] I have uploaded Diagnostics
  - Diagnostics ID: N/A

### Expected behavior

Apache Mesos agent is successfully starting (was working last year on the same laptop)

### Actual behavior

Apache Mesos agent is failing with error:
`Failed to create Linux launcher: Failed to mount cgroups hierarchy at '/sys/fs/cgroup/freezer': Operation not permitted`

Full log:

`I0703 13:43:10.586707     1 main.cpp:385] Build: 2021-09-22 23:20:48 by 
I0703 13:43:10.587469     1 main.cpp:386] Version: 1.12.0
I0703 13:43:10.587488     1 main.cpp:393] Git SHA: af6922288f0dd9f530305641a4f88c3bc9b48dab
W0703 13:43:10.589253     1 systemd.cpp:205] Failed to test /sbin/init for systemd environment: does not exist
I0703 13:43:10.589484     1 resolver.cpp:69] Creating default secret resolver
I0703 13:43:10.590130     1 containerizer.cpp:320] Using isolation { environment_secret, filesystem/linux, volume/image, docker/runtime, network/cni, volume/host_path, volume/sandbox_path }
E0703 13:43:10.591130     1 main.cpp:610] EXIT with status 1: Failed to create a containerizer: Could not create MesosContainerizer: Failed to create launcher: Failed to create Linux launcher: Failed to mount cgroups hierarchy at '/sys/fs/cgroup/freezer': Operation not permitted`

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, don't know which version.
  - macOS Version: 12.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.9.1 (81317)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Run `docker run -it --privileged us.gcr.io/valued-mediator-128022/is-mesos:latest mesos-slave --containerizers=mesos --image_providers=docker --isolation=docker/runtime,filesystem/linux --work_dir=/var/tmp/mesos/agent --master=zk`

**Comment by uladzimir-shelhunou** [comment]
Can somebody take a loot into this? Minikube uses hyber-v and it works brilliantly.

**Comment by Fifan31** [comment]
No solution or workaround proposed to get rid of this issue ?
I encounter the same problem on linux ubuntu 22.10 with the mesosphere/mesos-agent:1.7.1 image
