### ISSUE TITLE
All images and volumes were lost after upgraded to 4.10.0 (82025)

### ISSUE THREAD

**Issue by alvinhu** [docker/for-mac#6388]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9A46C65E-496E-4DDB-B21F-5B38229AA30A/20220704043103

### Actual behavior
All images and volumes were lost after upgraded to 4.10.0 (82025) today.

### Information

  - macOS Version: 12.4 (21F79)
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.10.0 (82025)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Upgrade from 4.9 to 4.10
  2. Everything GONE

**Comment by CGerAJ** [comment]
Apple M1 Pro
macOS Version: 12.4 (21F79)
Intel chip or Apple chip: Apple chip
Docker Desktop Version: 4.9.1 (81317)

<img width="565" alt="image" src="https://user-images.githubusercontent.com/20548301/177231484-370e8ce0-c7b5-4074-9e96-fa5bc202499c.png">

I have two macos, one for work and one for home, and both Docker desktops are logged in using the same account

This is the second time I've had this problem, and it seems to have been the case the last time
