### ISSUE TITLE
again

### ISSUE THREAD

**Issue by kyutasan** [docker/for-mac#639]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dsheets** [comment]
This issue contains no actionable information so we cannot help you. Please provide enough information about your problem for us to diagnose it. The app contains a `Diagnose & Feedback` feature in the menu to help you with this.
