### ISSUE TITLE
UNIX application in amd64 Docker image does not detect kernel asynchronous I/O on Apple Silicon

### ISSUE THREAD

**Issue by haroldlbrown** [docker/for-mac#6396]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I have a custom amd64 Docker image that is based on CentOS 7 and has a UNIX application installed in it.
The amd64 Docker image and the application inside work without problems on an amd64 computer.

However, when starting this image with Docker Desktop on an Apple Silicon CPU, the application does not start.
The error I get from the application is something like this:

> Kernel asynchronous I/O not initialized because it is not supported by this host. Install the appropriate asynchronous I/O libraries.

Adding `--platform=linux/amd64` to the Docker command also didn't solve the issue.

As far as I know, Docker is using qemu to emulate processors. Is it a known limitation that asynchronous I/O for amd64 processors does not work on Apple Silicon?
Or is there a way I can get this amd64 image to work on an Apple Silicon computer?

**Comment by haroldlbrown** [comment]
One can reproduce the error on an Apple Silicon CPU by using this public Docker image and running the following command:

```
docker run --platform linux/amd64 nguoianphu/docker-sybase
```

Results in:
```
00:0000:00000:00000:2022/07/11 10:56:53.70 kernel  Kernel asynchronous I/O not initialized because it is not supported by this host. Install the appropriate asynchronous I/O libraries.
00:0007:00000:00000:2022/07/11 10:56:53.70 kernel  I/O controller 2 (NetController) is running as task 786438 on thread 7 (LWP 27).
00:0000:00000:00000:2022/07/11 10:56:53.70 kernel  Attempt to resize 'Disk Controller Manager' failed because a new controller could not be created.
00:0000:00000:00000:2022/07/11 10:56:53.70 kernel  It was not possible to create the disk controllers for the server, the server will now shutdown.
00:0000:00000:00000:2022/07/11 10:56:53.71 kernel  end of stack trace, kernel service process: kpid 0
00:0000:00000:00000:2022/07/11 10:56:53.71 kernel  PCI(M0): PCI Bridge: Releasing PCA subsystem for engine 0.
```

**Comment by krosenvold** [comment]
Although it does not solve the docker bug, you can make sybase ASE work on M1 MAC by disabling async io in /opt/sybase/ASE-16_0/MYSYBASE.cfg inside the image. Change parameter allow sql server async i/o  to value 0 instead of "DEFAULT".

See https://github.com/nguoianphu/docker-sybase/issues/3
