### ISSUE TITLE
Glitching icon

### ISSUE THREAD

**Issue by freaker2k7** [docker/for-mac#6399]
Glitching icon in the top panel when starting up on v4.9.1 (81317).

See video: https://www.veed.io/view/e02ca398-c582-4bd7-9f86-250827ed5763

<img width="274" alt="Screen Shot 2022-07-10 at 22 12 44" src="https://user-images.githubusercontent.com/5237609/178158762-39c5abcc-c9e3-4150-ba37-24af2571b764.png">

Updating now to v4.10.1 (82475), let's see what happens.
But what's also strange is that it asked me to update, restarted, and now it says there's a newer version....
So why in the first place didn't it update to the latest version !?

**Comment by freaker2k7** [comment]
Solved after update to v4.10.1 (82475).

I think the issue is when it has another update, like I have, in line...

Feel free to close if you're sure it's not a bug anymore.

**Comment by trungutt** [comment]
Thanks for reporting @freaker2k7  Feel free to reopen again if the issue persists
