### ISSUE TITLE
Docker Engine API - Incorrect reporting Memory_stats.stats["cache"] not avaliable

### ISSUE THREAD

**Issue by lantos-lgtm** [docker/for-mac#6402]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: VPN blocked it, but not needed as the issue is probably in serialization of computer stats

### Expected behavior
When sending a GET request to ```containers/{{id}}/stats``` there is expected to be the following ```"cache"``` field on the ```memory_stats``` field.

```json
...
"memory_stats": {
    "usage": 23123,
    "stats": {
       "cache": 123231,
       ...
   }
}
```
as defined in https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats
I have tested it on linux and the reponse is correct as the api. On mac however the response is invalid
### Actual behavior
Field "cache" does not exist on ```"memory_stats": { "stats": {}}``` 
could be possible the "anon" field
```
{
    ...
    "memory_stats": {
        "usage": 9506816,
        "stats": {
            "active_anon": 0,
            "active_file": 135168,
            "anon": 3379200,
            "anon_thp": 0,
            "file": 4730880,
            "file_dirty": 0,
            "file_mapped": 3244032,
            "file_writeback": 0,
            "inactive_anon": 3379200,
            "inactive_file": 4595712,
            "kernel_stack": 98304,
            "pgactivate": 0,
            "pgdeactivate": 0,
            "pgfault": 3069,
            "pglazyfree": 0,
            "pglazyfreed": 0,
            "pgmajfault": 0,
            "pgrefill": 0,
            "pgscan": 0,
            "pgsteal": 0,
            "shmem": 0,
            "slab": 131136,
            "slab_reclaimable": 0,
            "slab_unreclaimable": 131136,
            "sock": 0,
            "thp_collapse_alloc": 0,
            "thp_fault_alloc": 0,
            "unevictable": 0,
            "workingset_activate": 0,
            "workingset_nodereclaim": 0,
            "workingset_refault": 0
        },
        "limit": 8217030656
    },
     ...
}
```

### Information

  - macOS Version: 12.4
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version:  
      -  Docker Desktop 4.10.1
      -  Docker Engine v20.10.17
### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check                                                                                                                  
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-07-12T18:36:24.180351000Z][com.docker.diagnose][I] ipc.NewClient: cd5624eb-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xc8
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x105694200)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x44
[common/pkg/diagkit/gather/diagnose.Run.func1(0x105694200)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x44
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x105694200)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x84
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x105694200, 0x140004eb728)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x3c
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x20?, 0x140004eb728)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x78
[common/pkg/diagkit/gather/diagnose.walkOnce(0x105165ce0?, 0x1400061f890)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x105694380, 0x140003ae800?, {0x1400061fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x178
[main.checkCmd({0x14000134010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0xe0
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x310
[2022-07-12T18:36:24.182806000Z][com.docker.diagnose][I] (217e57a4) cd5624eb-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.1.186","10.2.0.2"]}
[2022-07-12T18:36:24.700093000Z][com.docker.diagnose][W] (217e57a4) cd5624eb-diagnose-network C<-S 75f8a125-diagnosticsd POST /check-network-connectivity (517.331708ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working? It is fine
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
### Steps to reproduce the behavior

  1. Use MacOS with apple silicon. 
  2. run the following command in terminal  ```curl -v --unix-socket /var/run/docker.sock  http://localhost/containers/myContainer/stats```

**Comment by lantos-lgtm** [comment]
Found this.
https://github.com/docker/cli/blob/6e2838e18645e06f3e4b6c5143898ccc44063e3b/cli/command/container/stats_helpers.go#L227-L249

Looks like the api documentation needs to be updated.

**Comment by nicks** [comment]
Thanks for reporting!

Could you file a bug or PR in https://github.com/moby/moby to update the documentation?
https://github.com/moby/moby/blob/c8a0e1da1220846aed5889e2554b1395dd2a7878/api/swagger.yaml#L6890

My understanding is the memory.stat stuff is VERY low-level, and in this case it's just directly reading off the cgroup.
https://www.kernel.org/doc/Documentation/cgroup-v2.txt
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
so this is expected behavior.
