### ISSUE TITLE
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by StevenLudwig** [docker/for-mac#6404]
I update to latest version on mac os m1 and now fail, never start docker desktop

  - [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

![image](https://user-images.githubusercontent.com/9299252/178899012-7b94e87c-d4c4-4c87-a9dd-ccdbb676daff.png)

### Actual behavior

Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...
![Captura de Pantalla 2022-07-13 a la(s) 23 31 04](https://user-images.githubusercontent.com/9299252/178899175-18808401-a49f-4e98-ae55-c6a8bd13a4d9.png)

**Comment by mhemani-ledn** [comment]
I had similar behaviour and it turns out that Docker did not like my hosts file

**Comment by mannyyang** [comment]
Getting similar behavior as well but on intel. 

@mhemani-ledn how did you fix it with your hosts files?

**Comment by mhemani-ledn** [comment]
> Getting similar behavior as well but on intel.
> 
> @mhemani-ledn how did you fix it with your hosts files?

reduce the size of your hosts file or revert to default.
