### ISSUE TITLE
Extensions menu not visible in Docker-Desktop dashboard v4.10.1 (OSX)

### ISSUE THREAD

**Issue by Viv-Rajkumar** [docker/for-mac#6406]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Extensions menu in dashboard to be visible as it was in v4.10.0

### Actual behavior
Extensions menu is not visible

### Information
Not sure if this is intentional and was disabled/hidden in this latest update, couldn't find it mentioned in the changelog.

Downloading v4.10.0 from releases shows the menu with previous configured extensions. Just not visible in 4.10.1

  - macOS Version: 12.4
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.10.1

### Steps to reproduce the behavior

  1. Open Docker desktop at 4.10.1 and compare against 4.10.0

**Comment by weitzman** [comment]
Same here - Mac 12.3.1 Apple Silicon

**Comment by Viv-Rajkumar** [comment]
Seems resolved with v4.11.0 on OSX (Apple chip).

fwiw, my update sequence:
- Switched directly from v4.10.0 -> v4.11.0 (did not test incremental update)
- On launch, Menu was enabled however it was indicating "Extensions are disabled".
- Nav menu "Extension Settings" from home page to Settings.
- This had the checkbox **Enabled** for "Enable Docker Extensions".
- Cycled this option to "Disable" -> "Apply and Restart" -> "Enable" -> "Apply and Restart"
- Extensions feature was usable now. It did not remember previously installed extensions. I just reinstalled them.
