### ISSUE TITLE
While uninstalling, got TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by aayushma11** [docker/for-mac#6407]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: BigSur
  - Intel chip or Apple chip: Downloaded Intel chip
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Go to Docker Menu
  2. Click Uninstall
  3. Displays the error and cannot uninstall it.

**Comment by trungutt** [comment]
@aayushma11 Could you please clarify which version of Docker Desktop you're using?

**Comment by cacharle** [comment]
I got the same error after messing with the `~/.docker/daemon.json` config file.

**Comment by VikNim** [comment]
I have been trying to start docker but it just won't start, tried different solutions from SO and Google but no effect, then tried uninstalling it but it just won't load. Manually uninstalled it (Removing all files through Terminal). Downloaded the latest version again, installed it but again same issue.

Version info:
Docker Desktop 4.13.1

Machine: MacBook Pro (16-inch, 2019)

OS: Monterey 12.6.1

**Comment by cacharle** [comment]
If it can help, it worked after reinstalling and rebooting my mac on my side

**Comment by dsfspb** [comment]
Fix after update to v4.60.0 (intel): remove old Personal access tokens from account
