### ISSUE TITLE
docker-for-mac: Error response from daemon: Get https://registry-1.docker.io/v2/: unable to connect to 44.207.51.64:443. Do you need an HTTP proxy?

### ISSUE THREAD

**Issue by ahmad-kemsan** [docker/for-mac#6408]
I was using the docker desktop for mac smoothly until now, but I am now facing the below-mentioned issue:

OS: Mac OS Big Sur 11.6.4

$ `docker --version`
Docker version 20.10.17, build 100c701

$ `docker run hello-world`

Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 44.207.51.64:443. Do you need an HTTP proxy?.
See 'docker run --help'.

NO PROXY, MacBook has direct internet access. No issues with internet access from any other application.

I have already tried **factory reset**, **logout** and **login** and also **cleaned/ purged data** but still facing the same error.

**Comment by hitinder** [comment]
@ahmad-kemsan I faced same issue just now and then it throws timeout.

![image](https://user-images.githubusercontent.com/9841229/179295744-d436e8bd-c0b1-4bb2-ad1d-aad811687df8.png)

**Comment by mohsin-plivo** [comment]
Facing the same issue. Tried installing older versions of Docker Desktop but no resolution. Yet it seems to work randomly once or twice and then continues to give the same error 
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/84492744/180132024-20b48d24-54cd-4949-b392-47353f2e7cbf.png">

**Comment by sanketwagh147** [comment]
Facing same issue on windows :(

**Comment by simensol** [comment]
I connected my host computer to a VPN, and suddenly it worked.

**Comment by mohsin-plivo** [comment]
Yes, connecting to a VPN seems to work for me as well. Thanks @simensol.
