### ISSUE TITLE
File extension missing for installer downloaded from homepage of website

### ISSUE THREAD

**Issue by vasef** [docker/for-mac#6411]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ ? ] I have tried disabling enabled experimental features
  - [ ?  ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Downloaded image will have .dmg extension

### Actual behavior
I had to add .dmg extension manually.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
         I have downloaded the file multiple times and was downloading raw data without a file extension
  - Is the problem new?
         I skimmed through issues page  and dont seem to find any issues pointing to this.
  - Did the problem appear with an update?
         Not really. this is pre install.
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: 12.4
  - Intel chip or Apple chip: I tried both versions, looks like this is an issue with both downloads
  - Docker Desktop Version: latest

### Steps to reproduce the behavior

  1. Go to website https://docs.docker.com/desktop/install/mac-install/
  2. Click on either buttons. 
  3. Notice the downloads are without file extension. 
  4. But, when .dmg is added manually, it works.

**Comment by StefanScherer** [comment]
Thanks for the report. We've checked everything on our side and the download link looks good. We believe it's a bug in Firefox 102 and it should be fixed in a new release. For now you have to use a different browser or rename the file afterwards. Thank you.
