### ISSUE TITLE
Reproducible (rounding?) Bug/Behaviour only in Docker on M1

### ISSUE THREAD

**Issue by Degix** [docker/for-mac#6412]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B77B9882-6921-4C0D-9235-708529E835FF/20220720073756

### Expected behavior

The calculation of
```java
double actual = Math.cos(53.0 / 90.0 * 1.5707963267948966);
 ```
 should be `0.6018150231520484`.

### Actual behavior

On: 
- Windows
- Linux
- Windows (Docker)
- Linux (Docker)
- Gitlab (Docker)
- Mac M1 
the result is like expected: `0.6018150231520484`

On:
- Mac M1 (Docker) 
result is **not** like expected: `0.6018150231520483`

*Assumption*: In Docker on Mac M1 the value will be rounded down instead of up.

### Information

  - macOS Version: 12.4 (21F79)
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version: 4.10.1 (82475)

The Bug/Behaviour is repoducable with the code mentioned below.
The Behaviour/Bug exists since or before the end of February, because I stumbled over the same issue as i first tried to containerize my project back in the days.

### Steps to reproduce the behavior

On any OS and Docker Container the Code should print "Equal", except when running this Code inside a Docker Container on Mac M1.
I have tested this with with the `maven:3.8.6-openjdk-11` image.

*hint*: Also tested this with the  `strictfp` annotation. Same results.

#### Dockerfile (Example)
```Dockerfile
FROM maven:3.8.6-openjdk-11
COPY ./out/production/docker-for-mac-bug-test-project/ /tmp
WORKDIR /tmp
ENTRYPOINT ["java", "Main"]
```

#### Code
```java
public class Main {
    public static void main(String[] args) {

        double actual = Math.cos(53.0 / 90.0 * 1.5707963267948966);
        double expected = 0.6018150231520484;
        double valueInDockerOnMacM1 = 0.6018150231520483;

        if(actual == expected) {
            System.out.println("Equal!");
        } else {
            System.out.println("!!!!NOT Equal!!!!");
            System.out.println("a: " + actual);
            System.out.println("e: " + expected);

            if(actual == valueInDockerOnMacM1) {
                System.out.println("You probably running this on MAC M1 in Docker, right?");
            }
        }
    }
}
```

**Comment by jamesu** [comment]
Thought this sounded a bit odd so did a bit of investigation and it looks like this could be related to this OpenJDK bug: https://bugs.openjdk.org/browse/JDK-8242461?attachmentOrder=asc

**Comment by Degix** [comment]
@jamesu Thank you so much for your time and investigation. This is actually the "bug". I successfully solved it by using StrictMath instead of Math lib. 
Here is the an Explaination on what's the [difference between StrictMath and Math](https://stackoverflow.com/questions/4232231/whats-the-difference-between-java-lang-math-and-java-lang-strictmath/4232294#4232294).
Short: In the Math Library the functions are not defined to return the bit-for-bit same results.
