### ISSUE TITLE
Error: MUI: The path returned by `getTreeDataPath` should be unique

### ISSUE THREAD

**Issue by argishti-e** [docker/for-mac#6413]
<img width="1321" alt="Screen Shot 2022-07-20 at 15 05 41" src="https://user-images.githubusercontent.com/80847312/179967314-5034e72b-ccee-4a97-acc0-f8a4f334e9d0.png">

**Comment by nicks** [comment]
Thanks for reporting! I'm going to de-dupe against https://github.com/docker/for-win/issues/12844 to centralize the discussion.
