### ISSUE TITLE
docker desktop application must be forced to quit via activity monitor to quit and relaunch properly

### ISSUE THREAD

**Issue by Lylah** [docker/for-mac#6420]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After quitting docker desktop, I should be able to reopen (relainch) the application and see the desktop UI and the icon for the docker desktop application in the top bar of the screen.

### Actual behavior
After quitting docker desktop, it appears that the application continues to run, and I cannot relaunch properly. The UI will not come back, nor will the icon at the top of the desktop. I have to go into the Activity Monitor and kill the docker process in order to relaunch properly.

### Information

  - macOS Version: 12.4 Monterey
  - Intel chip or Apple chip: Intel Chip
  - Docker Desktop Version: 4.10.1

### Steps to reproduce the behavior

  1. Launch Docker desktop after restarting your MAC+
  2. Go to docker desktop and select "Quit" option
  3. Attempt to run docker commands in the terminal - you will see that it is still running
  4. Click the docker application icon and attempt to relaunch / bring back the UI for docker desktop - you will see that the desktop application does not appear
  5. If you go into the activity monitor and force the process called "Docker" to terminate, you can then successfully restart/ relaunch the application.

**Comment by yllekz** [comment]
This is happening to me too, even after attempting to click "update and restart" where the button just does nothing.

**Comment by derekperkins** [comment]
Same for me.

macOS Version: 12.4 Monterey
Intel chip or Apple chip: Intel Chip
Docker Desktop Version: 4.12.0

**Comment by maherelaridi** [comment]
Same problem here. Force quit not closing Docker. Even after using docker-compose stop and docker-compose down

**Comment by RickTheHat** [comment]
Ditto - I quit Docker and it still is present in my activity monitor on my M1 mac, I have to force quit to get back working

**Comment by yllekz** [comment]
For anyone having this issue, while yes it's still a major problem, I've found a way to at least kill/restart Docker from terminal which makes it a little less painful. You can even do it via remote SSH:

``osascript -e 'quit app "Docker"' && open --background -a Docker``
