### ISSUE TITLE
Error: MUI: The path returned by `getTreeDataPath` should be unique.

### ISSUE THREAD

**Issue by TaichiEndo** [docker/for-mac#6421]
<img width="1273" alt="Screen Shot 2022-07-23 at 1 55 04 PM" src="https://user-images.githubusercontent.com/55826985/180592501-5cacced3-fc72-4590-b85a-ed834737f5b0.png">

now i can not use docker. I was using docker swarm.

**Comment by trungutt** [comment]
@TaichiEndo Could you please clarify:
- The version of Docker Desktop you're using?
- A minimum reproduction case (a .yml file with instruction for example) so we could look into it

**Comment by krishnamohanelluru** [comment]
Error: MUI: The path returned by `getTreeDataPath` should be unique. The rows with id #containerdev-env-dev-1 and #containerdev-env-dev-1 have the same. Path: ["compose-projectdev-env","containerdev-env-dev-1"].

**Comment by krishnamohanelluru** [comment]
version I am using is 4.10.1(82475)
I am just creating a dev-env environment and getting this error.

**Comment by trungutt** [comment]
@krishnamohanelluru Could you please be explicit on reproduction steps? Thanks in advance

**Comment by krishnamohanelluru** [comment]
I upgraded docker to latest with an environment of moneterey 12.4 macOS with docker version 4.10.1 and created the environment using docker-compose up -d dev.  this works without issue in 4.9.1 package and fails to work with upgraded version.

my docker-compose file is following

version: "3.7"
services:
  dev:
    build: "services/dev"
    hostname: ata-dev
    volumes:
      - $HOME/.m2:/home/dev/.m2
      - .:/home/dev/repo
      - dev-docker:/var/lib/docker
      - k8s-etc:/etc/kubernetes
    privileged: true
    ports:
      - 22
      - 5000-5007
      - 8080
    env_file:
      - ./.env
    environment:
      - CONSUL_HTTP_ADDR=https://127.0.0.1:5000
      - VAULT_ADDR=http://127.0.0.1:5001
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - echo hello
      interval: 30s
      timeout: 5s
      retries: 3
  k8s:
    hostname: ata-k8s
    build: "services/k8s"
    privileged: true
    ports:
      - 6443
    environment:
      - KUBECONFIG=/etc/kubernetes/admin.conf
    volumes:
      - k8s-docker:/var/lib/docker
      - k8s-etc:/etc/kubernetes
      - k8s-registry:/var/lib/registry
    healthcheck:
      test: ["CMD", "kubectl", "get", "nodes"]
      interval: 1m
      timeout: 5s
      retries: 3
  localstack:
    hostname: localstack
    build: "services/localstack"
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080"
    environment:
      - SERVICES=${SERVICES-s3}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR-/var/lib/localstack }
    volumes:
      - localstack-data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "bash", "-c", "awslocal s3 ls"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  dev-data: {}
  dev-docker: {}
  k8s-docker: {}
  k8s-etc: {}
  k8s-registry: {}
  localstack-data: {}

**Comment by nicks** [comment]
@krishnamohanelluru we just released Docker Desktop 4.11, which might fix this problem. Can you try upgrading and see if it's resolved?

**Comment by gillesdemey** [comment]
This occurred for me in 4.10.x but seems fixed in 4.11 🎉

**Comment by nicks** [comment]
thanks @gillesdemey !
