### ISSUE TITLE
Docker Desktop - Turn Off Dark Mode

### ISSUE THREAD

**Issue by kmanadkat** [docker/for-mac#6422]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version: 12.4
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: v4.10.1

## Docker Desktop THEME

I like **Light Mode** of Docker Desktop, for some reason Dark mode is too dark for me.

### Actual behavior

I don't see any option to switch between light mode or dark mode in **Preferences**

<img width="1576" alt="Screenshot 2022-07-23 at 12 00 31 PM" src="https://user-images.githubusercontent.com/25281055/180593439-d3e87bb9-fc5b-4706-af64-92b72b536871.png">

I am aware that If I change to Light Mode from System Preferences then Docker Desktop adopts to it, but that changes theme for my entire system!

<img width="1673" alt="Screenshot 2022-07-23 at 12 04 21 PM" src="https://user-images.githubusercontent.com/25281055/180593547-d7f8b02d-75ec-49a8-b941-094ecaa3fc87.png">

### Expected behavior

As an end user, **I should be able to control theme of application standalone**, it is good to have it linked with system but I should always have a manual control over it.

Can we please have an option like below ? :

<img width="884" alt="Screenshot 2022-07-23 at 12 02 59 PM" src="https://user-images.githubusercontent.com/25281055/180593505-5ec83768-6502-40bf-8e79-4e18e473b9bc.png">

Thank you for reading this issue and understanding it :)

**Comment by joe0BAB** [comment]
Hi @kmanadkat! Thanks for reporting your feature request! This is a very good point! But there's good news. We have implemented an option to set the theme independent of the OS theme. It will be shipped with 4.11 which we hope to release very soon. I'd be happy to hear your feedback on it once available! Also feel encouraged to check our [public roadmap](https://github.com/docker/roadmap) to suggest and comment on other improvements :)

**Comment by kmanadkat** [comment]
Hi @joe0BAB my pleasure 🙂

Thats cool too! By `very soon` you mean a week, or a month or few months? I couldn't find info on previous releases in this repository or Docker Desktop download page.

Anyways you could go ahead and close this thread. Thanks for thinking about users like me and developing this feature, good day.

**Comment by kmanadkat** [comment]
Never mind, I got release notes here: https://docs.docker.com/desktop/release-notes/

**Comment by joe0BAB** [comment]
Probably within the next two weeks :) 

Sounds good, closing the issue then.

**Comment by kmanadkat** [comment]
@joe0BAB got that sooner than expected!
<img width="1575" alt="Screenshot 2022-07-31 at 12 26 10 PM" src="https://user-images.githubusercontent.com/25281055/182014039-8fdf9e5e-aa01-4362-a4ce-7d21d2da0f97.png">
