### ISSUE TITLE
Image runs from CLI but fails with "invalid reference format" in Docker Desktop

### ISSUE THREAD

**Issue by pinheadmz** [docker/for-mac#6425]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `7B4FC48C-F1D4-416C-8A57-1D2112FD5E7B/20220725190620`

### Expected behavior

Clicking the "run" button on an image in Docker Desktop will run the image inside a container

### Actual behavior

Red banner error message "Error invoking remote method 'docker-run-container': Error: (HTTP code 400) unexpected - invalid reference format"

### Information

  - macOS Version: 12.3.1 (21E258)
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.10.1 (82475)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Go to https://github.com/pinheadmz/hsd/pkgs/container/hsd
  2. Copy the "pull" command for arm64 version and execute locally
  3. Image runs fine when executed from command line:

```
$ docker image list
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
ghcr.io/pinheadmz/hsd   <none>    454c3ce01bcd   3 hours ago   310MB

$ docker run 454c3ce01bcd
[info] (blockstore) Opening FileBlockStore...
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chaindb) Opening ChainDB...
...
```

  4. Image fails to run when executed from Docker Desktop:

<img width="2032" alt="Screen Shot 2022-07-25 at 2 58 41 PM" src="https://user-images.githubusercontent.com/2084648/180853628-5c61c514-32f0-4fdb-867a-ee77418aa53d.png">

**Comment by pinheadmz** [comment]
Found these messages in the dockerd log when this error occurs:

```
[2022-07-25T19:52:10.785931465Z][dockerd][I] time="2022-07-25T19:52:10.783475257Z"<HOST>level=debug<HOST>msg="Calling<HOST>GET<HOST>/images/454c3ce01bcd/json"
[2022-07-25T19:52:10.800453340Z][dockerd][I] time="2022-07-25T19:52:10.800354007Z"<HOST>level=debug<HOST>msg="Calling<HOST>GET<HOST>/images/454c3ce01bcd/history"
[2022-07-25T19:52:12.411634841Z][dockerd][I] time="2022-07-25T19:52:12.411490966Z"<HOST>level=debug<HOST>msg="Calling<HOST>GET<HOST>/images/sha256:454c3ce01bcdfb29d056d41ef13ece901d66971e9bfd3d3f1064d7a49755d462/json"
[2022-07-25T19:52:13.795084508Z][dockerd][I] time="2022-07-25T19:52:13.794924425Z"<HOST>level=debug<HOST>msg="Calling<HOST>POST<HOST>/containers/create?Hostname=&User=&AttachStdin=false&AttachStdout=true&AttachStderr=true&Tty=true&OpenStdin=false&StdinOnce=false&Image=ghcr.io%2Fpinheadmz%2Fhsd%3A%3Cnone%3E&Volumes=%7B%7D&name=&HostConfig=%7B%22PortBindings%22%3A%7B%7D%2C%22Binds%22%3A%5B%5D%7D"
[2022-07-25T19:52:13.795928925Z][dockerd][I] time="2022-07-25T19:52:13.795654883Z"<HOST>level=debug<HOST>msg="form<HOST>data:<HOST>{\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"CgroupnsMode\":\"\",\"Cmd\":[],\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"DeviceRequests\":null,\"Devices\":null,\"Dns\":null,\"DnsOptions\":null,\"DnsSearch\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[],\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,
```

**Comment by nicks** [comment]
thanks for reporting. ya, i think this might be a UI bug where it needs all images to have tags, even if it's a latest tag. I think you could be able to workaround it by using a tagged image?

**Comment by pinheadmz** [comment]
@nicks thanks. We fiddled with our github workflow that posts the containers:

https://github.com/handshake-org/hsd/pkgs/container/hsd

Now, these all work in the desktop UI 🤷‍♂️

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by Apdlrcjafg19** [comment]
> * [x]  I have tried with the latest version of Docker Desktop
> * [x]  I have tried disabling enabled experimental features
> * [x]  I have uploaded Diagnostics
> * Diagnostics ID: `7B4FC48C-F1D4-416C-8A57-1D2112FD5E7B/20220725190620`
> 
> ### Expected behavior
> Clicking the "run" button on an image in Docker Desktop will run the image inside a container
> 
> ### Actual behavior
> Red banner error message "Error invoking remote method 'docker-run-container': Error: (HTTP code 400) unexpected - invalid reference format"
> 
> ### Information
> * macOS Version: 12.3.1 (21E258)
> * Intel chip or Apple chip: Apple M1
> * Docker Desktop Version: 4.10.1 (82475)
> 
> ### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
> ```
> Starting diagnostics
> 
> [PASS] DD0027: is there available disk space on the host?
> [SKIP] DD0028: is there available VM disk space?
> [PASS] DD0031: does the Docker API work?
> [PASS] DD0004: is the Docker engine running?
> [PASS] DD0011: are the LinuxKit services running?
> [PASS] DD0016: is the LinuxKit VM running?
> [PASS] DD0001: is the application running?
> [PASS] DD0018: does the host support virtualization?
> [PASS] DD0017: can a VM be started?
> [PASS] DD0015: are the binary symlinks installed?
> [PASS] DD0003: is the Docker CLI working?
> [PASS] DD0013: is the $PATH ok?
> [PASS] DD0007: is the backend responding?
> [PASS] DD0014: are the backend processes running?
> [PASS] DD0008: is the native API responding?
> [PASS] DD0009: is the vpnkit API responding?
> [PASS] DD0010: is the Docker API proxy responding?
> [PASS] DD0012: is the VM networking working?
> [PASS] DD0032: do Docker networks overlap with host IPs?
> [SKIP] DD0030: is the image access management authorized?
> [PASS] DD0019: is the com.docker.vmnetd process responding?
> [PASS] DD0033: does the host have Internet access?
> No fatal errors detected.
> ```
> 
> ### Steps to reproduce the behavior
> 1. Go to https://github.com/pinheadmz/hsd/pkgs/container/hsd
> 2. Copy the "pull" command for arm64 version and execute locally
> 3. Image runs fine when executed from command line:
> 
> ```
> $ docker image list
> REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
> ghcr.io/pinheadmz/hsd   <none>    454c3ce01bcd   3 hours ago   310MB
> 
> $ docker run 454c3ce01bcd
> [info] (blockstore) Opening FileBlockStore...
> [info] (chain) Chain is loading.
> [info] (chain) Checkpoints are enabled.
> [info] (chaindb) Opening ChainDB...
> ...
> ```
> 
> 4. Image fails to run when executed from Docker Desktop:
> 
> <img alt="Screen Shot 2022-07-25 at 2 58 41 PM" width="2000" src="https://user-images.githubusercontent.com/2084648/180853628-5c61c514-32f0-4fdb-867a-ee77418aa53d.png">
