### ISSUE TITLE
I'm not able to run any command inside docker container

### ISSUE THREAD

**Issue by jagin** [docker/for-mac#6426]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Runing for example `ls` command should return list of directory.

### Actual behavior

Command hangs. Running any command, even `echo "BINOG!"` hangs

### Information

  - macOS Version: macOs Montery v 12.4
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version: 4.10.1

and

  - macOS Version: macOs Montery v 12.1
  - Intel chip or Apple chip: Intel Core i7
  - Docker Desktop Version: 4.10.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Execute `docker run -t node:16 /bin/bash` or `docker run -t ubuntu:20.04 /bin/bash`
  2. In terminal execute any command like `ls`. Even hitting `enter` hangs the container

Ctr+C returns to console input.

```
❯ docker run -t ubuntu:20.04 /bin/bash
root@3bd0ac7e2249:/# ls
^C^C
root@3bd0ac7e2249:/# ^C
root@3bd0ac7e2249:/# echo "BINGO!"
^C^C
root@3bd0ac7e2249:/# ^C
root@3bd0ac7e2249:/#
```

**Comment by jagin** [comment]
Sorry, I forgot about `-i` options :( I'm so dummy

**Comment by nicks** [comment]
No worries! Yeah, you need the -i flag to attach stdin.
