### ISSUE TITLE
M1 Compatibility with Docker. Should older images be reconstructed/remade to work on M1? 

### ISSUE THREAD

**Issue by magarw** [docker/for-mac#6427]
- [X] I have tried with the latest version of Docker Desktop. 
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BAC6A0A1-58F7-40CE-A71A-741296D7D851/20220727161956

### Expected behavior
Expect the container to run and launch Redis to connect to the application. 

### Actual behavior
We get an error of the sort: 
```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
```
This is the same bug as #6137

### Information

  - macOS Version: Monterey 12.3
  - Intel chip or Apple chip: Apple M1 Chip
  - Docker Desktop Version: 4.9.1

We're not supplying CLI information to reproduce the problem as this exact bug is already documented in other threads like #6137 and #6030. We don't have an ARM image, as mentioned in these older issues which have gone stale or have been closed, and are instead using a Linux base. 
- We are wondering if we can fix the issue on our end somehow (running Docker inside a VM on our new computer, maybe?) or if Docker is working on resolving these errors?
- Is an updated Docker Desktop version that will address compatibility with M1 chip in the making?
- Should we make the images again with ARM? 
- What do you recommend?

The Docker images for our application have been working well for 1-2 years now with minimal issues. We would love to continue using these images on our new M1 chip computers as well.

**Comment by nicks** [comment]
Hi @magarw ! See my comment here: https://github.com/docker/for-mac/issues/6137#issuecomment-1157094087

When you run x86 images under ARM, Docker has to run them under CPU emulation. That emulation is best-effort, and will unavoidably be much slower / lack support for key OS features. The long-term solution is to make your images available for multiple architectures.

**Comment by magarw** [comment]
Alright, thanks @nicks!
