### ISSUE TITLE
DOCKER doesnt work

### ISSUE THREAD

**Issue by ZardashtKaya** [docker/for-mac#643]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
There's not enough information here -- please create a fresh report which includes at least the diagnostic id and some comments explaining what's wrong.
