### ISSUE TITLE
Download missing dmg extension and checksum incorrect

### ISSUE THREAD

**Issue by ceejay12** [docker/for-mac#6431]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Hello. I'm new to posting here. I see the below says install assistance is ignored but perhaps a reader could advise on the checksum error? 

Also, the file (https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-amd64) wasn't downloading as a dmg.

The website https://docs.docker.com/desktop/release-notes/ lists the Mac with Intel Chip Checksum: SHA-256 295694d7c2df05e37ac0d27fe8be5af6295b1edc6fa00a00a47134a14d5d0b34 
But the downloaded file has 8be8e5245d6a8dbf7b8cb580fb7d99f04cc143c95323695c0d9be4f85dd60b0e  Docker.dmg

### Information

  - macOS Version: 12.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.11.0

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
thanks for the heads-up!

295694d7c2df05e37ac0d27fe8be5af6295b1edc6fa00a00a47134a14d5d0b34 is the hash of docker desktop 4.11,
8be8e5245d6a8dbf7b8cb580fb7d99f04cc143c95323695c0d9be4f85dd60b0e is the hash of docker desktop 4.10.1

you probably just hit it mid-transition (or hit a cache)

The missing DMG extension is a firefox bug and will be fixed when you update Firefox, see https://github.com/docker/for-mac/issues/6411
