### ISSUE TITLE
Docker running inside a macOS instance via Virtualization.framework on Apple Silicon and nesting containers?

### ISSUE THREAD

**Issue by ylluminate** [docker/for-mac#6432]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

I have found it essential to provide some sandboxed developer environments for our organization and in the process discovered the need to run Docker on a macOS 12 instance inside Apple's Virtualization.framework on Apple Silicon.  This amounts to nested virtualization, but currently Apple Silicon arm64 does *NOT* support nested virtualization.

It would be useful if Docker did not simply disallow running on macOS inside of a Virtualization.framework instance and instead offered the option to use `qemu` for executing non-macOS containers/operating systems.

This would perform relatively acceptably for doing many tasks and containers.

I am currently not seeing any way to do this, so I suspect that this is a feature request. Any information or discussion would be much appreciated.

**Comment by nicks** [comment]
We just launched Desktop support for nested virtualization on Windows
https://docs.docker.com/desktop/vm-vdi/
https://github.com/docker/roadmap/issues/141
It's available to Docker Business customers. 

If that's interesting to you, the repo here: https://github.com/docker/roadmap is probably a better place to talk to the product team about it. (the for-mac repo is more for bugs)

**Comment by ylluminate** [comment]
Thanks. I've made a comment over there - perhaps that will be helpful in establishing some discussion.
