### ISSUE TITLE
Tutorial pastes wrong command to CLI in the step 2

### ISSUE THREAD

**Issue by Ky6uk** [docker/for-mac#6436]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `47537A60-176F-426F-850C-2026CDA9D1DC/20220801083107`

### Expected behavior

Step 2 of the tutorial is working after clicking on the code snippet.

### Actual behavior

Step 2 of the tutorial doesn't work after clicking on the code snippet. It seems to be a typo in the code.

### Information

  - macOS Version: 12.5 (21G72)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.11.0

### Steps to reproduce the behavior

  1. Run docker after upgrading from `v4.10.1` to `v4.11.0`
  2. Tutorial should be opened automatically for some reason.
  3. Try to pass the tutorial by clicking on code snippets in the blue box.
  4. Step 2 will paste the wrong command to the CLI in the right panel after clicking on it.

#### Screenshot

<img width="1232" alt="Screenshot 2022-08-01 at 11 29 55" src="https://user-images.githubusercontent.com/46930/182108510-c89309ea-963f-47b2-83d3-dd3133f630a8.png">

**Comment by nicks** [comment]
thanks for reporting! for what it's worth, we don't think this is a regression -- we think there's a bug where if you click through without hitting [enter] in step 1, step 2 is broken. one of the engineers has a fix to make this a bit smoother.
