### ISSUE TITLE
Fix the spellings under Dev Environment Dashboard

### ISSUE THREAD

**Issue by ajeetraina** [docker/for-mac#6438]
Docker Desktop :  4.11.0
Section: Dev Environment

How to reproduce the issue:

- Install Docker Desktop for Mac 4.11.0
- Go to Dashboard
- Click on Dev Environments
- Select Local Directory

You will find the below errors:
- wrong spellings
- There should be a gap in "Recommended for testing" and "Can be slower"

<img width="890" alt="Screenshot 2022-08-02 at 10 04 45 AM" src="https://user-images.githubusercontent.com/313480/182292541-fadcf798-e770-4737-8160-0f75387e0157.png">

**Comment by nicks** [comment]
nooooooo!!!!

thank you for filing.
