### ISSUE TITLE
Error: MUI: The path returned by `getTreeDataPath` should be unique. 

### ISSUE THREAD

**Issue by purejgleason** [docker/for-mac#6439]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Shows containers

### Actual behavior

Shows...

```
We've already reported this to our error tracker.
Error: MUI: The path returned by `getTreeDataPath` should be unique. The rows with id #containerredis and #containerredis have the same. Path: ["compose-projectservice-core","containerredis"].
```

**Comment by nicks** [comment]
Thanks for reporting! If you update to 4.11, that should fix the issue, see: https://github.com/docker/for-mac/issues/6421
