### ISSUE TITLE
Docker install for Mac - Failed to install networking components (and more)

### ISSUE THREAD

**Issue by verbunk** [docker/for-mac#644]
### Expected behavior
Docker starts and is happy.

### Actual behavior
Docker starts and is sad.

### Information

ADC2137C-D8AC-4E1A-A370-ED68EB892029

MacBook Pro (Retina, 15-inch, Mid 2014)
El Capitan 10.11.6

Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/ADC2137C-D8AC-4E1A-A370-ED68EB892029/20160915-190903.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/dunham/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dunham/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/dunham/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dunham/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/dunham/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Download Docker B26 
  2. Mount and drag to Applications
  3. Open and confirm run downloaded file
  4. Click ok to install
  5. Receive error about Networking components not able to be installed.
  6. Run diagnose and upload
  7. Receive error about diagnostic data not being able to upload.

I even sudo /Applications/Docker.app/Contents/MacOS/Docker to install with no luck.

**Comment by djs55** [comment]
Thanks for the report. The critical log lines are:

```
> Sep 14 21:12:03 ... Docker[com.docker.docker][73916] <Notice>: privileged installation of com.docker.vmnetd successful
> Sep 14 21:12:03 ... Docker[com.docker.docker][73916] <Critical>: Communication with networking components failed.
```
Does the application work if you run it a second time?

Assuming not, could you have a look to see if the networking component has been installed?

There should be a binary here:
```
$ ls -l /Library/PrivilegedHelperTools/com.docker.vmnetd
-r-xr--r--  1 root  wheel  44464  9 Sep 14:46 /Library/PrivilegedHelperTools/com.docker.vmnetd
```
and a `launchd` registered service:
```
$ sudo launchctl list | grep com.docker
9324   	0      	com.docker.vmnetd
```
and a running process:
```
$ ps uax | grep /Library/PrivilegedHelperTools/com.docker.vmnetd
root             9324   0.0  0.0  2454580   2228   ??  Ss   Fri02pm   0:00.04 /Library/PrivilegedHelperTools/com.docker.vmnetd
djs             34400   0.0  0.0  2434840    800 s002  S+   11:32am   0:00.00 grep /Library/PrivilegedHelperTools/com.docker.vmnetd
```
and a Unix domain socket:
```
$ ls -l /var/tmp/com.docker.vmnetd.socket
srw-rw-rw-  1 root  daemon  0  9 Sep 14:46 /var/tmp/com.docker.vmnetd.socket
```

Do you see those on your system?

I've seen a bug before where a partially-installed component prevents it being re-installed properly. The workaround for that was to delete the binary with `sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd` and then restart the app.

I'm also suspicious that there are no log lines which say `com.docker.vmnetd failed to connect to ... sleeping 1s` since I added a retry loop around the `connect` a few days ago. Perhaps the `connect` was successful but then the service failed to start?

**Comment by djs55** [comment]
May be related to docker/for-mac#61

**Comment by verbunk** [comment]
Hey djs55,
   
  Your suggested fix works.

`sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd`

For the record, the checks you inquired about were a mixed bag,

===
`ls -l /Library/PrivilegedHelperTools/com.docker.vmnetd`
`-r-xr--r--@ 1 root  wheel  44464 Sep 14 20:28 /Library/PrivilegedHelperTools/com.docker.vmnetd`
===
,
===
`ls -l /var/tmp/com.docker.vmnetd.socket`
`srw-rw-rw-  1 root  daemon  0 Sep 14 20:28 /var/tmp/com.docker.vmnetd.socket`
===

but not

===
`ps uax | grep /Library/PrivilegedHelperTools/com.docker.vmnetd`
<Nothing>
===
,
===
`sudo launchctl list | grep com.docker`
<Nothing>
===

Another symptom was after the install and failure message the Docker app bar widget still popped up, claimed it was running but the menu options were all greyed out. (so no uninstall access from the menu). The app still allowed me to uninstall from the /Applications/>/Docker --uninstall  but re-install was the same. removing the helper tool did the trick.

Thx!!

**Comment by samoht** [comment]
Closing as the issue seems now resolved.
