### ISSUE TITLE
Docker Whale icon in Mac menu bar should always be visible when docker-desktop is running

### ISSUE THREAD

**Issue by bgehman** [docker/for-mac#6440]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I would expect to find the docker Whale icon in the Mac's "menu bar" to **always** be visible when the docker-desktop VM is running.

### Actual behavior
User can perform actions to accidentally remove the whale icon from menu bar, even though docker is still running in the background, and there is no clear logical way to bring the icon back to the menu bar.  See the detailed scenario described below.

### Information

  - macOS Version: Monterey (v12.5)
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: reproducible on **4.10.1 (82475)** and **4.11.0 (83626)**

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
n/a

### Steps to reproduce the behavior

1. Open docker preferences by using the Whale icon in the menu-bar.
2. In Mac's "Dock", right click on the Docker icon and select `Quit`
3. Notice that:
    * Preference window's icon is removed from Mac's "Dock"
    * Whale icon is removed from Mac's "menu bar"
    * Docker is still running in the background (verified with `docker ps`)
    * Running `Docker` from Mac's launchpad will **not** bring back the Whale icon in the menu bar.
4. User is left in a broken state with no way to mange the running docker-desktop: management is done via the lost whale icon in the mac menu bar and there is no clear way to restore it.

**Workaround**
The only way (that I've found) to restore back the missing whale icon in the menu bar is by running this command on the CLI (or perhaps rebooting):
```
/Applications/Docker.app/Contents/MacOS/Docker
```

**Comment by nicks** [comment]
thanks for the detailed report! I can repro this as well.

For what it's worth, you can also run 

```
osascript -e 'quit app "Docker"'
```

from the terminal to quit the app, which will tear everything down properly (this what i often do in some of my dev scripts)

**Comment by DiegoGiovany** [comment]
Still happening here, M1 Max with Ventura...

**Comment by bgehman** [comment]
looping back on this old bug report, can confirm this is fixed in later versions now.
I've verified on 4.14.1 (91661).  Following the steps in my reproducible scenario, exiting Docker by "Quit" on Docker icon in Mac's "Dock", has the application fully shut down (not left running in the background).  Restarting Docker using the Launchpad also works now.

Closing as Fixed.  Thanks!

**Comment by bgehman** [comment]
Hi @gpressutto5 since opening this bug report (back in August) I have upgrade my Mac and my specs are identical to yours now (M1 processor, Ventura 13.2.1, Docker desktop 4.17.0).  I went through my original reproducible scenario and I am unable to reproduce the problem.

Suggest that you try to figure out a reproducible scenario and open a new bug report on the new problem -- it seems different from my original report.  Thanks.

**Comment by nicks** [comment]
@gpressutto5 sorry to hear you're having trouble! Ya, if you're still having problems, please open a new bug with repro steps on how you got into this state. Going to lock this issue to prevent discussion of similar but unrelated issues.
