### ISSUE TITLE
Provide option to disable the "Rate Docker Desktop" dialog

### ISSUE THREAD

**Issue by unikitty37** [docker/for-mac#6441]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: n/a — it has been saying "Diagnosing" for over a minute now and has not produced a diagnostics ID.

### Expected behaviour

The "Rate Docker Desktop" dialog has a "never ask me this again" checkbox. Checking it and clicking either Dismiss or Submit results in me never being asked to rate Docker Desktop again.

### Actual behaviour

There is no option to disable this intrusive and annoying dialog. The user should be able to configure Docker Desktop so they can just get on with their work without having it interrupt them.

### Information
  - macOS Version: macOS 12.5 (21G72)
  - Intel chip or Apple chip: Apple M1 Max
  - Docker Desktop Version: 4.10.1 (82475)

This was already reported in #4413, but the issue was auto-closed and nothing was done to fix the problem.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
segment 2022/08/04 16:45:27 ERROR: sending request - Post "https://api.segment.io/v1/batch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
segment 2022/08/04 16:45:27 ERROR: 1 messages dropped because they failed to be sent and the client was closed
No fatal errors detected.

### Steps to reproduce the behavior

1. Install Docker Desktop on Mac.
2. Use Docker Desktop normally.
3. Open Preferences.
4. Look at every option in an attempt to disable the dialog. There is no way to do it.
5. Eventually, the rating dialog will pop up.
6. Your work has been interrupted and your train of thought derailed (this is your reminder that not all users are neurotypical, and those who are not should have an option to *disable* this dialog!)

**Comment by nicks** [comment]
thanks for reporting! 4.11 fixes a bug in the feedback dialog. Now it will only ask for feedback twice a year. See: https://www.docker.com/blog/docker-desktop-4-11-virtual-environments-mac-permissions-new-extensions/

We're not currently planning on adding an option to disable the dialog.
