### ISSUE TITLE
I'm curious to know how you put the docker executable into the sandbox file inside MacApp? Then how to create a soft link? Can you tell me? I recently had this operation in MacApp as well.

### ISSUE THREAD

**Issue by shumintao** [docker/for-mac#6443]
how you put the docker executable into the sandbox file inside MacApp?

```
╰─○ whereis docker 
docker: /usr/local/bin/docker
(base) ╭─taoshumin_vendor at taoshumin_vendor的MacBook Pro in ~
╰─○ ll /usr/local/bin/docker
lrwxr-xr-x  1 root  wheel    54B Feb 12 13:14 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
(base) ╭─taoshumin_vendor at taoshumin_vendor的MacBook Pro in ~
╰─○ cd /Applications/Docker.app/Contents/Resources/bin/
(base) ╭─taoshumin_vendor at taoshumin_vendor的MacBook Pro in /Applications/Docker.app/Contents/Resources/bin
╰─○ ls
com.docker.cli                docker                        docker-compose-v1             docker-credential-ecr-login   hub-tool
com.docker.vpnkit             docker-compose                docker-credential-desktop     docker-credential-osxkeychain kubectl
```

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/26895243/183238612-a42c5658-2133-4e7b-bdb8-780d160dc6cf.png">

**Comment by dombarnes** [comment]
Symlinks?
`ln -s /path/to/source/file /path/to/target`

**Comment by shumintao** [comment]
> Symlinks? `ln -s /path/to/source/file /path/to/target`

No, I mean the docker executable, how is it put in when the xcode build is packaged, not a soft link.

**Comment by dombarnes** [comment]
/usr/local/bin/docker is a link to the actual executable which is bundled inside the Docker desktop package. 
When you ran ll you can see it’s only 54B. 
Run ll inside the bin folder in the Desktop app and you’ll see it’s much bigger.

**Comment by nicks** [comment]
Hi! I'm not sure I understand the question here. If you're having some problem, can you file a new bug that explains what you expect to happen, and what actually happens instead?
