### ISSUE TITLE
Bumping compose to 2.9.0?

### ISSUE THREAD

**Issue by jberglinds** [docker/for-mac#6447]
There's a bug in the compose version shipped with the latest Docker Desktop that has been resolved. 
Would be great if the current v2.7.0 of compose shipped with Docker Desktop could be bumped to v2.9.0 which resolves it. 

See https://github.com/docker/compose/issues/9591 for more information with a reproducible case. 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

  - macOS Version: 12.5
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.11.1 (84025)

**Comment by nicks** [comment]
:+1: Yes! Before each Desktop minor release, we chat with compose team and make sure we're on the latest stable version. So I would expect this in 4.12. 

Going to close this issue, just to reduce the number of things to track -- this is a normal part of the release process.
