### ISSUE TITLE
Docker Desktop for Mac zombie processes are not reaped after normal exit and will not start

### ISSUE THREAD

**Issue by tmoschou** [docker/for-mac#6451]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `044ED717-9763-4179-A514-EE5E0C93FED7/20220814035629`

### Expected behavior

Should be able to quit and relaunch Docker Desktop for Mac normally.

### Actual behavior

After quitting Docker Desktop for Mac via the Dock, a zombie `Docker Desktop.app` process remains and is never reaped by the parent process `com.docker.backend -watchdog -native-api`. Additionally attempts to start a new Docker Desktop process do nothing and fail. The only way to start Docker Desktop is to go into Activity Monitor and kill every docker process. 

### Information

  - macOS Version: 12.5 (Montery)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.11.1

Can reproduce this on a fresh install 100%.

Note that the Diagnostics were uploaded after having killed the processes into order to relaunch Docker Desktop to generate a new diagnostics.

Output of `ps -o pid,state,xstat,command -p 43563` showing process in a zombie state (`Z`)
```
  PID STAT XSTAT COMMAND
43563 Z        0 (Docker Desktop)
```

LIkewise, screenshot of `htop -F docker` also showing Zombie state and process tree
![Screen Shot 2022-08-14 at 2 00 44 pm](https://user-images.githubusercontent.com/5567550/184522599-55485bf2-25c5-4e4d-8f0c-a0c5dff84002.png)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Note that the network check seems like an unrelated issue https://github.com/docker/for-mac/issues/6312

```
$ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-08-14T04:37:51.225847000Z][com.docker.diagnose][I] ipc.NewClient: ef2fa874-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd9
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x4d379c0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x4d379c0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x4d379c0)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x4d379c0, 0xc00066d720)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x46922c0?, 0xc00066d720)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x46ef660?, 0xc0002df888)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x4d37b40, 0x4?, {0xc0002dfb18, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ca
[main.checkCmd({0xc000132010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x2a8
[2022-08-14T04:37:51.227730000Z][com.docker.diagnose][I] (b8f4eb7b) ef2fa874-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.0.127"]}
[2022-08-14T04:37:51.733000000Z][com.docker.diagnose][W] (b8f4eb7b) ef2fa874-diagnose-network C<-S 8a0dfdc3-diagnosticsd POST /check-network-connectivity (505.355273ms): failed to ping host: exit status 1

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

### Steps to reproduce the behavior

1. Clean / Fresh install - factory reset, purge data etc.
2. Open Docker Desktop, and complete post-install setup, accept licence, etc.
3. Close Docker Desktop via right click Icon the Dock -> Quit
4. Wait for process to become zombied
5. Try to launch Docker Desktop again

**Comment by bgehman** [comment]
likely related to report #6440 .

**Comment by nicks** [comment]
thanks for reporting! ya, I'm going to close this in favor of https://github.com/docker/for-mac/issues/6440, so that we have one issue to communicate on.
