### ISSUE TITLE
docker-compose  bad CPU type in executable

### ISSUE THREAD

**Issue by talasjanos** [docker/for-mac#6453]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D29AF943-2719-4FF3-BA4B-60A1260F7501/20220817095910

### Expected behavior

Docker-compose should execute.

### Actual behavior

Docker-compose cannot be started.

### Information

  - macOS Version: 12.5
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.11.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Call `/usr/local/bin/docker-compose`
  2. Result: `fork/exec /usr/local/bin/docker-compose-v1: bad CPU type in executable`

**Comment by talasjanos** [comment]
As [the documentation regarding Apple Silicon](https://docs.docker.com/desktop/mac/apple-silicon/#known-issues) states, the V1 of `docker compose` command need Rosetta to be installed. I do not have Rosetta nor do I intend to install it. Hence my option of **Use Docker Compose V2** is and has always been set.

I solved the above problem by clicking the option twice - once to disable and again to re-enable it. Now `docker-compose` works as expected.

The latest update seems to do something that makes the V1 default even when the settings indicate it shouldn't. Could you please take a look into that?

**Comment by nicks** [comment]
Thanks for reporting! Sounds like the core issue is resolved, so I'm going to close this.

We're aware there's a bug where under certain conditions the compose-switcher will revert to V1 even when you have "Use Docker Compose V2" checked. Unchecking and re-checking it will fix the problem. We have a fix for this in the next release.
