### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by sankarav** [docker/for-mac#646]
### Information

Diagnostic ID: CFAE1732-B468-479E-8B46-A27B53DE3BA1
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/dhandapa/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/CFAE1732-B468-479E-8B46-A27B53DE3BA1/20160915-233746/qemu-img-check.stdout 2> /tmp/CFAE1732-B468-479E-8B46-A27B53DE3BA1/20160915-233746/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by homerakshay** [comment]
@sankarav Hi Sankara, could you let me know how your docker file looks like.. /etc/sysconfig/docker .. This might help to debug the problem further. 


Thank you.
Regards,
Akshay

**Comment by samoht** [comment]
@sankarav would you be able to retry to send us your diagnostic archive? We cannot really help you without it. We also advise your to update to the latest stable (1.12.1) or latest beta (1.12.2-rc1-beta27).

**Comment by samoht** [comment]
Analysing archive CFAE1732-B468-479E-8B46-A27B53DE3BA1/20160915-233851
--------------------------------------------------------------------------------
Detected symptom of problem 'moby-kernel-froze' in CFAE1732-B468-479E-8B46-A27B53DE3BA1/20160915-233851.

The kernel inside the VM stalled so Docker must be restarted.

May be related to docker/for-mac#87

The following log matches:
```
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Notice>: vcpu 2 received signal, resuming
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Notice>: vcpu 3 received signal, resuming
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Notice>: vcpu 1 received signal, resuming
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Notice>: vcpu 0 received signal, resuming
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Error>: VM: 2016-09-14 04:51:25 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Error>: VM: 2016-09-14 04:51:25 +0000 UTC kern.error kernel: INFO: rcu_sched self-detected stall on CPU
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Error>: VM: 2016-09-14 04:51:25 +0000 UTC kern.error kernel: 	3-...: (1 GPs behind) idle=555/1/0 softirq=3166425/3166425 fqs=0
Sep 14 00:26:19 2usmdhandapa Docker[com.docker.driver.amd64-linux][82614] <Error>: VM: 2016-09-14 04:51:25 +0000 UTC kern.error kernel:
```
