### ISSUE TITLE
Docker Desktop [4.11.1] reports Docker is running, however all operations fail

### ISSUE THREAD

**Issue by alexlorenzi** [docker/for-mac#6460]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A1F15E31-9134-4003-8738-FAC766A5983B/20220825212821

### Expected behavior

Launch Docker and run containers

### Actual behavior

After launching Docker Desktop, UI reports that Dockers is running, however issuing any commands from the console results in the following error:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Information

  - macOS Version: 12.5.1 
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.11.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[PASS] DD0030: is the image access management authorized?
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the Docker CLI working?
    Failed with: exit status 1

The Docker CLI is needed to build, share and run applications.

2 : The test: is the com.docker.vmnetd process responding?
    Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory

The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.
```

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Run `docker ps` from the console
  3. Fail

**Comment by danshome** [comment]
The problem seems to be caused by the new feature in 4.11.0 that was added for Mac.   I think the issue is related to a new --user option added in 4.11.0.  What I've found is that the unless I run the docker installer from the command line as discussed on install notes and pass --user=root, then it won't create any of the symlinks under /usr/local/bin and socket file symlinks under /var/run don't get created.

**Comment by alexlorenzi** [comment]
@danshome Thanks! That solved it
Yeah, looking at the release notes for 4.11.0 it mentions `Added a –user flag to the install command on Mac, which will prevent a privileged service from running in the background` which seems to line up with what you're saying and what I was seeing.
Appreciate it
