### ISSUE TITLE
docker for-mac doesn't support autofs module 

### ISSUE THREAD

**Issue by soichih** [docker/for-mac#6463]
Hello. I have a container that relies on autofs/automount. This works fine on a linux machine, but on Mac, automount fails with this error message.

```
Sep 18 13:37:00 6ab5838b7cea systemd[1]: Starting Automounts filesystems on demand…
Sep 18 13:37:00 6ab5838b7cea automount[286]: /usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
```

strace shows this
```
mount("automount", "/tmp/autolZdOE5", "autofs", MS_MGC_VAL, "fd=4,pgrp=458,minproto=3,maxprot"...) = -1 ENODEV (No such device)
```

It looks like VM running the for-mac doesn't support autofs module.

```
modprobe autofs
modprobe: FATAL: Module autofs not found in directory /lib/modules/5.10.104-linuxkit
```

To make this container runs on Linux as well as on mac, could you make this module available, so that I can run automount?

Thank you!

**Comment by viktorzp** [comment]
Had same issue.
I have a project where automount was started to use. 
As a result the official docker for mac bundle was not able to run the app.

As a workaround now, I install ubuntu vm on parallels with the autofs4 module. Install into vm docker and redirect all commands via tcp to this docker. Looks ugly a bit, but it works.

But It would be great to have docker for mac working again with my app.

So +1 on asking to add autofs4 module into the linuxkit =)

Hope this one will be handled soon
