### ISSUE TITLE
Image from Apple M1 Pro processor is not working on google cloud platform

### ISSUE THREAD

**Issue by ajitkumar2ster** [docker/for-mac#6466]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:9405FE4B-C9BE-42AB-A310-DD8DD831502A/20220901012656

### Expected behavior

Docker image should be platform independent. So it should work in google cloud platform services like Cloud run, GKE and GCE

### Actual behavior
Docker image is working fine on my machine but not working in google cloud services (cloud run,GCE and GKE)

### Information

  - macOS Version: MacOS Monterey
  - Intel chip or Apple chip: M1 pro
  - Docker Desktop Version:4.11.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

web page 

### Steps to reproduce the behavior

  1. Run the image on Docker in MacBook Pro (M1 Pro chip) , it should work fine.  
  2. Mine was a spring-boot application web application
  3. Push the same image to cloud, and use in cloud run or GCE, it doest not work

**Comment by nicks** [comment]
Sorry to hear you're having trouble!

This is expected. If you're building on an M1 (an ARM chipset) and trying to deploy to a cloud service that uses Intel/AMD chipsets, you'll need to build a multi-arch image. Here's how:

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
https://docs.docker.com/desktop/multi-arch/
