### ISSUE TITLE
Verifying credentials not finishing

### ISSUE THREAD

**Issue by ushiii111798** [docker/for-mac#6469]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 63F28938-D227-4C4C-B179-36392EC0D1E0/20220902021549

### Expected behavior
Successfully Sign in

### Actual behavior
After sign in via web browser, Docker desktop hang with verifying credentials

### Information
It is totally reproducible

  - macOS Version: macOS 13 beta 6
  - Intel chip or Apple chip: M1 Pro
  - Docker Desktop Version: 4.12.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
![Screenshot 2022-09-02 at 11 13 15](https://user-images.githubusercontent.com/11730880/188044155-b1430ef1-cc2f-4deb-8e4a-cd1da8d6a3d2.jpg)

### Steps to reproduce the behavior
just to try signing in

**Comment by kaorihinata** [comment]
Just confirming as I can't tell with the provided information, but does this cover the registry login issue with 4.12.0, and Ventura Beta 6? Are you also seeing a reproducible hang with `docker login`?

**Comment by jovezhong** [comment]
Same GUI issue on Mac Ventura Beta 4(13.0 Beta 22A5331f).  

For CLI

`docker version`

> Client:
>  Cloud integration: v1.0.29
>  Version:           20.10.17
>  API version:       1.41
>  Go version:        go1.17.11
>  Git commit:        100c701
>  Built:             Mon Jun  6 23:04:45 2022
>  OS/Arch:           darwin/arm64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Desktop 4.12.0 (85629)
>  Engine:
>   Version:          20.10.17
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.17.11
>   Git commit:       a89b842
>   Built:            Mon Jun  6 23:01:01 2022
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.6.8
>   GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

`docker login`

> Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
> Username: ***
> Password:
> Error saving credentials: error storing credentials - err: exit status 1, out: `Post "http://ipc/registry/credstore-updated": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by acacioes** [comment]
> Same GUI issue on Mac Ventura Beta 4(13.0 Beta 22A5331f).
> 
> For CLI
> 
> `docker version`
> 
> > Client:
> > Cloud integration: v1.0.29
> > Version:           20.10.17
> > API version:       1.41
> > Go version:        go1.17.11
> > Git commit:        100c701
> > Built:             Mon Jun  6 23:04:45 2022
> > OS/Arch:           darwin/arm64
> > Context:           default
> > Experimental:      true
> > Server: Docker Desktop 4.12.0 (85629)
> > Engine:
> > Version:          20.10.17
> > API version:      1.41 (minimum version 1.12)
> > Go version:       go1.17.11
> > Git commit:       a89b842
> > Built:            Mon Jun  6 23:01:01 2022
> > OS/Arch:          linux/arm64
> > Experimental:     false
> > containerd:
> > Version:          1.6.8
> > GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
> > runc:
> > Version:          1.1.4
> > GitCommit:        v1.1.4-0-g5fd4c4d
> > docker-init:
> > Version:          0.19.0
> > GitCommit:        de40ad0
> 
> `docker login`
> 
> > Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
> > Username: ***
> > Password:
> > Error saving credentials: error storing credentials - err: exit status 1, out: `Post "http://ipc/registry/credstore-updated": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

I have the same problem, how about it now?

**Comment by jovezhong** [comment]
Cool, by checking the [doc](https://docs.docker.com/engine/reference/commandline/login/#credentials-store), I found a workaround:
* `vim $HOME/.docker/config.json` change credsStore value from `"desktop"` to `"osxkeychain"`
* `docker login` will pass with the following warning
 
> Login Succeeded
> 
> Logging in with your password grants your terminal complete access to your account.
> For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/

Since we are not using `desktop` credential store, your Docker Desktop remains unauthenticated, but good for CLI.

Hope it helps

**Comment by kaorihinata** [comment]
Yeah, that's the issue I'm seeing. Another way I've been able to work around it on the CLI is by attempting to `docker login`, immediately aborting with CTRL+C without waiting for it to timeout, then running the same command again. The second time it succeeds (for me, at least), with one caveat: after a certain amount of time it will fail to work again. 

For example, the following would probably succeed:

1. `docker login`.
2. Abort the `docker login` before it times out.
3. `docker login` again.
4. Assuming it succeeds, perform some action with the registry (push an image or manifest, for example.) Something quick that will interact with the registry immediately.
5. `docker logout`.

However, the following would probably fail:

1. `docker login`.
2. Abort the `docker` login before it times out.
3. `docker login` again.
4. Perform a `docker build` which takes a few minutes to run.
5. Perform some action with the registry (push an image or manifest, for example.)

Most likely at this point you will receive an access denied while attempting to interact with the remote registry. It feels like running `docker login` the first time ties up something on the backend (or it just never starts in the first place), and when you abort early and try again, another instance of that something is started up which handles the login correctly. I wouldn't know what pieces are in play here, but perhaps the developers will be able to glean something useful from these interactions.

**Comment by kaorihinata** [comment]
Following on from the above, the following only appears in the system logs (via `Utilities/Console.app`) if the command is going to timeout:

```
error	15:10:22.012968-0400	taskgated-helper	Disallowing docker-credential-osxkeychain because no eligible provisioning profiles found
error	15:10:22.100985-0400	docker-credential-osxkeychain	open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
error	15:10:22.101015-0400	docker-credential-osxkeychain	cannot open file at line 46870 of [bc8a7f24e4]
error	15:10:22.101022-0400	docker-credential-osxkeychain	os_unix.c:46870: (2) open(/private/var/db/DetachedSignatures) - No such file or directory
error	15:13:33.871941-0400	docker-credential-osxkeychain	open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
error	15:13:33.871994-0400	docker-credential-osxkeychain	cannot open file at line 46870 of [bc8a7f24e4]
error	15:13:33.872004-0400	docker-credential-osxkeychain	os_unix.c:46870: (2) open(/private/var/db/DetachedSignatures) - No such file or directory
error	15:16:05.425729-0400	docker-credential-osxkeychain	open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
error	15:16:05.425765-0400	docker-credential-osxkeychain	cannot open file at line 46870 of [bc8a7f24e4]
error	15:16:05.425776-0400	docker-credential-osxkeychain	os_unix.c:46870: (2) open(/private/var/db/DetachedSignatures) - No such file or directory
```

Let me know if there's anything I can do to provide more information.

**Comment by kaorihinata** [comment]
I believe I have an explanation for this behavior now. `docker-credential-desktop` appears to be the culprit.

When you first attempt to `docker login`, this spins up `docker-credential-desktop store` to insert the credential into the credential store in the background, then blocks while waiting for a response. So long as this store attempt is alive, the potential credential remains in the credential store. Aborting `docker login` at this point does not stop the `docker-credential-desktop store` instance running in the background, and when you spin up another instance of `docker login`, this spins up another instance of `docker-credential-desktop`, but this time it simply `docker-credential-desktop get`s the existing credential. If at any point during your usage the previous store attempt finally times out, the credential is wiped from the store, and will break anything you do after that. There appears to be a similar hang when attempting a `docker-credential-desktop erase`.

**Comment by peterkc** [comment]
@kaorihinata Notable. Docker Desktop will always reset `credsStore` in `$HOME/config.json` to `desktop`. 

I was able to use `credHelpers` as a workaround for `docker login`.

``` json
{
  "credsStore": "desktop",
  "credHelpers": {
    "": "osxkeychain",
    "ghcr.io": "osxkeychain",
    "registry.hub.docker.com": "osxkeychain"
  }
}
```

macOS Version: Ventura 13.0 Beta 6 (22A5331f)
Intel chip or Apple chip: M1 Max
Docker Desktop Version: 4.12.0

**Comment by Dids** [comment]
> @kaorihinata Notable. Docker Desktop will always reset `credsStore` in `$HOME/config.json` to `desktop`.
> 
> I was able to use `credHelpers` as a workaround for `docker login`.
> 
> ```json
> {
>   "credsStore": "desktop",
>   "credHelpers": {
>     "": "osxkeychain",
>     "ghcr.io": "osxkeychain",
>     "registry.hub.docker.com": "osxkeychain"
>   }
> }
> ```
> 
> macOS Version: Ventura 13.0 Beta 6 (22A5331f) Intel chip or Apple chip: M1 Max Docker Desktop Version: 4.12.0

Should this also solve the Docker Desktop/Dashboard app getting stuck on "Verifying credentials..." and locking up the entire desktop app? Because it unfortunately doesn't, at least not for me.

**Comment by gawbul** [comment]
Seems to be working now for me in macOS 13.0 beta 5 (22A5342f)?

**Comment by kaorihinata** [comment]
@gawbul Can confirm that. I've removed @peterkc 's workaround and things are still working. Interface also seems responsive, so I assume communication with the backend is working now as well.

**Comment by zimmix** [comment]
Update to Monterey Beta 7 fixed all of my Docker login issues.

**Comment by ushiii111798** [comment]
Update will fix all!! Beta Software cause the error!!
