### ISSUE TITLE
com.docker.osx.hyperkit.linux failed to start Exit code 11

### ISSUE THREAD

**Issue by justinblayney** [docker/for-mac#6470]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Latest version of Docker will work on my M1 apple computer

### Actual behavior

When starting the application, I get the following error

com.docker.osx.hyperkit.linux failed to start
Exit code 11

When running diagnosis

Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 11.5.2 (build: 20G95)
logs: /tmp/D22A1E79-6418-44B7-B607-38C7B963756D/20220902-094132.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/justinblayney/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/justinblayney/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/justinblayney/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/justinblayney/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/justinblayney/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/justinblayney/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by ChiliConSql** [comment]
I have the same issue
Diagnostic ID: A617AB64-D797-46A3-891D-7229D9845EA4

**Comment by kart-aiven** [comment]
I am having similar issues, is this resolved?

**Comment by Exatex** [comment]
Same here a month later, any news?

**Comment by ChiliConSql** [comment]
Make sure you downloaded the correct version of Docker

**Comment by rayyan808** [comment]
Installed Docker Desktop latest stable from the official website, same issue. Tried `rm -fr  ~/Library/Containers/com.docker.docker/Data/*
` and restarting, no difference.
