### ISSUE TITLE
Updated Docker, now it will not start!!!

### ISSUE THREAD

**Issue by K1p2y3** [docker/for-mac#6471]
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/40665473/188265622-165f227a-3e29-4549-be55-76a139df9180.png">

<img width="609" alt="图片" src="https://user-images.githubusercontent.com/40665473/188265609-8a1d493a-82bf-453f-b360-84c0d5b22b53.png">

**Comment by K1p2y3** [comment]
I have tried restarting, reinstalling

**Comment by gonchik** [comment]
@K1p2y3  how did you installed ? 
via terminal or gui or brew?

**Comment by oleksii-m-baranov** [comment]
Try 
```
1. Check in `Activity Monitor` that Docker isn't running
2. Execute in terminal `rm -rf "/Users/<username>/Library/Group Containers/group.com.docker"`
3. Run Docker
```

**Comment by gonchik** [comment]
@oleksii-m-baranov  thanks! do you know the exact cause ?
I have reinstalled i.e. example my docker it works like a charm, but I want to know the cause

**Comment by oleksii-m-baranov** [comment]
@gonchik 
If I understand it right, this folder contains Docker configuration files and it wasn't deleted when you tried to re-install Docker.

**Comment by gonchik** [comment]
@oleksii-m-baranov  noted. 
another hind, restart macbook.
