### ISSUE TITLE
Docker.raw takes too much disk storage space on MacOS

### ISSUE THREAD

**Issue by suesunss** [docker/for-mac#6475]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] Diagnostics ID: `0E0F53BD-4662-4F02-82D7-FD2E7BD63806/20220906153342`

### Expected behavior

Docker Desktop uses disk as it is configured in setting.

### Actual behavior

Docker Desktop takes too much disk space, even more than the threshold which is configured in `Resources`.

My MacBook suddenly run out of space due to Docker takes nearly over 60G+ disk space (`Docker.raw`).

More strangely, in panel `Resources`, it says **0 Bytes used**.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/22719158/188677079-20cc37f0-bece-41f3-9e09-25e21dcada36.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/22719158/188677233-dc2cb6f9-29d3-482b-afec-0c8372265b6f.png">

### Information
- **Is it reproducible?** Yes, I have two MacBook Pro, both of them encountered the same problem
- **Is the problem new?** Yes, I have never encountered the problem before. 
- **macOS Version**: 15.6.1
- **Intel chip or Apple chip**: Both M1/Intel
- **Docker Desktop Version**: 4.12.0(85629)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior
  1. Install Docker Desktop for Mac
  2. Use Docker Desktop normally for a while (maybe a couple of days before my last update)
  3. Suddenly, one day, disk space drops very quickly and my MacBook run out of space in a very short of time (maybe a couple of minutes)

**Comment by nicks** [comment]
I think this is basically expected - Docker Desktop reserves a block of disk for containers and images. The "bytes used" is how much space they images/containers are actually using. And we expect the "real" size of that block to be slightly larger on the MacOS filesystem (62.6 GB vs 59.6 GB is about what i would expect).
https://docs.docker.com/desktop/faqs/macfaqs/#where-does-docker-desktop-store-linux-containers-and-images

Does reducing the amount allocated fix your problem?

**Comment by dioniciomata** [comment]
I have the exact same problem, I'm now trying to uninstall and remove all data from Docker, my MacBook Air storage is full, I got so frustrated. 
Here's an article I found on the subject, let me know if any of these fixes works for you @suesunss 
https://stackoverflow.com/questions/44346109/how-to-easily-install-and-uninstall-docker-on-macos#comment118786532_65468254

**Comment by suesunss** [comment]
@dioniciomata thanks for the tips,  this works. Also, a reallocation of disk size works too.

**Comment by suesunss** [comment]
> I think this is basically expected - Docker Desktop reserves a block of disk for containers and images. The "bytes used" is how much space they images/containers are actually using. And we expect the "real" size of that block to be slightly larger on the MacOS filesystem (62.6 GB vs 59.6 GB is about what i would expect). https://docs.docker.com/desktop/faqs/macfaqs/#where-does-docker-desktop-store-linux-containers-and-images
> 
> Does reducing the amount allocated fix your problem?

Reducing/Reallocaton the disk space in `Resource` panel fix the problem. 

But this behavior is a little bit dangerous, waht do you mean by `reserve` ? Will docker **monopolize**  this area or use it in a shared mode with OS system ? If it would use the disk space in a monopolized way, it's very likely that the host MacOS system suddenly run out of space. 

Also, it's very complex/frustrating if MacOS system run out of space, as in many cases, the MacOS system will not be able to start the operating system and ask you to delete files in power-on diagnostic mode to spare more space.
