### ISSUE TITLE
Docker restart not working & Containers inaccessible and do not show in UI after a forced restart (via Activity Monitor)

### ISSUE THREAD

**Issue by arag0re** [docker/for-mac#6476]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  6AA43E34-5209-4BBB-ADF1-B122E59FF5B6/20220907093808

### Expected behavior
- docker restart via menubar item should restart docker
- docker quit via menubar item should quit docker
- after a forced restart of docker all containers & volumes should be shown in the docker-desktop GUI

### Actual behavior
- docker restart, docker quit via the menubar-item wont work for me 
- after I killed all Docker processes on my machine and restarted docker-desktop, none of my perviously shown containers & volumes are listed in the docker-desktop GUI

### Information
  - It is reproducable
  - the problem is pretty much new and resulting from the last update that fixed a lot
  - yes it came with the update from v4.11.1 to v4.12.0 
  - A reproducible case if this is a bug, Dockerfiles FTW.
-->
  - macOS Version: 13.0 Beta (22A5331f)
  - Apple chip: M1 Pro 
  - Docker Desktop Version: v4.12.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?


then its stuck at this step
```

### Steps to reproduce the behavior

1. open Activity Monitor and search for "docker"
2. force quit all processes listed there 
3. reopen docker-desktop

**Comment by arag0re** [comment]
After disabling all experimental features they are showing in docker-desktop GUI but the check is still hanging at: 
```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
```

**Comment by gawbul** [comment]
Seems to be working now for me in macOS 13.0 beta 4 (22A5342f)?

**Comment by arag0re** [comment]
Will install the update now and try for myself. Will let you know how it goes.

**Comment by arag0re** [comment]
Now Docker-Desktop wont even start for me 😄

**Comment by arag0re** [comment]
i had to reinstall Docker-Desktop completly. Now its starting again. Idk if the other issues are solved tho.

**Comment by LorenzoS92** [comment]
Update also to latest public beta (5) called also Beta 7.

**Comment by arag0re** [comment]
for now it seems to be working, i can restart, quit and pause docker via MenuBarItems. 
After a restart tho all my container that i build and configure via docker compose wont show up until i run docker compose again.

```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 2 errors occurred:
	* querying vpnkit-bridge process: is it running as a different user?: no such file or directory
	* querying vpnkit-bridge process: is it running as a different user?: no such file or directory


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 2 errors occurred:
	* querying vpnkit-bridge process: is it running as a different user?: no such file or directory
	* querying vpnkit-bridge process: is it running as a different user?: no such file or directory



Not all of the backend processes are running.
```

**Comment by gawbul** [comment]
Do you have AV software running? I believe the vpnkit-bridge was previously picked up as malware by some anti-virus software. It might be worth checking if it has been quarantined.
