### ISSUE TITLE
docker ps hangs indefinitely

### ISSUE THREAD

**Issue by Kukankitsune** [docker/for-mac#648]
### Expected behaviour
Docker to list containers

### Actual behaviour
docker ps process hangs indefinitely.
### Information

Diagnostic ID: 63AFABC9-8D65-4A0F-BB93-29CB54E6D492
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by Kukankitsune** [comment]
Also restarting the mac and reinstalling docker does not resolve the issue.

**Comment by samoht** [comment]
It seems that you didn't upload the logs to our diagnostic server, so I am closing the issue. If your problem persists, please choose "Diagnose & Upload" in the Diagnostic menu item so that we can get your diagnostic logs and open a new issue.
