### ISSUE TITLE
Slow downs in M2 machines, using mostly Efficiency cores

### ISSUE THREAD

**Issue by mrsimo** [docker/for-mac#6480]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `74B947CA-B5B4-446A-8222-0BBF83942183/20220913143028`

### Expected behavior

When running CPU intensive tasks under Docker, the performance in the same machine should be relatively similar.

### Actual behavior

Sometimes the performance of applications running inside Docker tanks completely and normal tasks take many times longer.

We have a development environment that downloads a few public docker images and also builds some ruby applications, some bigger, some smaller. When starting from a clean slate (after a `docker prune -a --volumes`), we know this takes about 15 minutes, the majority of time spent installing packages with `apt` and gems with `bundle`. 

This time is quite consistent. When slowed down this can take upwards of an hour. I also have a different `Dockerfile` from a different app that takes a very stable 60s to build on my machine. When the machine is slowed down it takes about 600s.

I have a new M2 MacBook Air, and I've seem this effect happen exactly the same way on a colleague with an M1 MacBook Air.

The most noticeable for me has been that when things are slow, only (or mostly) Efficiency cores are used while Performance cores are mostly idle.

This is the CPU History while "slowed down" vs normally:

| Slowed Down | Normally | 
|---|---|
| ![slowed down](https://user-images.githubusercontent.com/19203/189096190-2b70d85a-9673-4cef-9fe7-2a29a9ebf48f.png) | ![fast](https://user-images.githubusercontent.com/19203/189121190-92c24dea-aa7a-4c70-9775-513208a636f1.png)

In both cases it's a boot of our development environment from a clean slate. In the first image it seems like Performance cores started doing work but gave up at some point and Efficiency cores picked up the slack. I have 6 cores assigned to Docker for Mac.

### Information

I have not been able to trigger this problem consistently. Our company uses mostly MacBook Pro's, and seems like this might only be happening to those of us with MacBook Air's.

  - macOS Version: Monterey 12.6
  - Intel chip or Apple chip: Apple M2
  - Docker Desktop Version: v4.12.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
❯ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

As said, I don't have a way to reproduce. I'm hoping the diagnostics can provide some information, or that you might have a better understanding of how the new MacBooks use Efficiency vs Performance cores and help us point to a possible explanation or even a possible fix.

Thank you!

**Comment by goshatch** [comment]
This problem is definitely still happening, this issue should not have been closed.

**Comment by mrsimo** [comment]
I wanted to provide some info in case someone else finds themselves in this issue.

After some truly bizarre troubleshooting and experimenting, I was able to poinpoint these issues to the fact that I was running an external display running at 120Hz. Changing the refresh rate down to 60Hz has fixed the issues and hasn't happened a single time since, even while running the same external display at 4k and trying to torture my machine as much as possible.

I reached this conclusion after noticing the problem immediately disappeared when unplugging the display, and a ton of trial and error afterwards.

Currently the performance is perfectly stable, all the time, plugged, unplugged, on battery or on power. I understand macOS might slow down the cores a little bit to deal with heat, but at no point it reaches the point of slowing down to a crawl like I reported.

Good luck everyone!

**Comment by ShinJustinHolly3317** [comment]
under what kind of circumstances will your m2 air heat up?
I'm considering buying m2 air or 13inch pro. The better looking of m2 air really wins, but I'm worried even light running of docker (1 mysql container + 1 redis container for local dev) will cause slow down.
Basiclly I'm only have light dev workload for my side project and daily personal use with my laptop. 
For work, I have another macbook pro from my campany.

**Comment by mrsimo** [comment]
If you check my last comment, the culprit was the refresh rate in my external display, not the temperature. After changing that the performance is flawless with no visible slow down that I can see, ever. Our development environment runs about 18 containers, some of them heavy Rails applications, and it works perfectly. A MySQL + redis + nginx seems like nothing in comparison. I routinely have Slack, Chrome, several tabs in iTerm and several VSCode's open, with a 4k external display (at 60hz instead of 120hz), and it all works very well. Just perfectly.

**Comment by qanadin** [comment]
So this is still happening.  Even with the latest M4 Pro chips.  Has there been anything on this somewhere else?

**Comment by goshatch** [comment]
A lot of folks using the apple m chips have moved on to orbstack instead of the official docker desktop app. It's much less resource-hungry.

**Comment by victorwads** [comment]
Guys, this problem is not a Docker issue — it’s an Apple issue.
I sincerely advise you to start reporting it via Apple Feedback, because it’s happening across several applications.

From my research, there is no way for an application to “choose” which core it will run on — the OS is entirely responsible for that.

On macOS 26 it seems to have gotten much worse: efficiency cores get fully loaded and the system UI freezes, while performance cores are basically on vacation. The only way out often is a hard shutdown using the power button.
