### ISSUE TITLE
Docker Compose V2 no longer working with Monterey v12.6

### ISSUE THREAD

**Issue by ribeaud** [docker/for-mac#6482]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features

### Expected behavior

**Docker Compose V2** option is checked and working on **macos** _Monterey_.

### Actual behavior

**Docker Compose V2** is NO longer working with the latest **Monterey** release (_v12.6_). I am not able to use my **mac** and I have to perform a hart restart.

### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.12.0

I can provide more info if necessary/needed and if you're not able to quickly reproduce the problem. [This](https://github.com/docker/for-mac/files/9560356/docker_compose_output.txt) is what I get when executing **Docker Compose V2** before the problem starts to appear and somehow _blocks_ the laptop.

**Comment by ManojBayyapureddy** [comment]
Having the same issue with latest version of Docker

macOS version : 12.6
Macbook Pro M1 pro chip

**Comment by trungutt** [comment]
Hi @ribeaud, according to the log provided

```
=> ERROR [registry.gitlab.com/biomedit/portal/frontend:4.6.0-dev.38 internal] load metadata for docker.io/library/node:16-alpine 30.6s
=> ERROR [registry.gitlab.com/biomedit/portal/web:4.6.0-dev.38 internal] load metadata for docker.io/library/python:3.10-slim 30.6s
```

I'm not sure that there's something to do with compose v2 and MacOS 12.6. Please reopen the issue if needed

**Comment by ribeaud** [comment]
Hi @trungutt. How could we identify the culprit then?

**Comment by djs55** [comment]
> I am not able to use my mac and I have to perform a hart restart.

This sounds like a macOS issue, especially since it started happening after a macOS upgrade. It shouldn't be possible for Docker Desktop to cause macOS to hang since Docker does not use kernel extensions etc. Could you take a look to see if you have any panic reports as described here: https://discussions.apple.com/thread/251339518?answerId=252594492022#252594492022

Also check to see if you have non-Apple kernel extensions loaded e.g.
```
$ kextstat | grep -v com.apple
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
```

**Comment by ribeaud** [comment]
OK, thanks. I will give another try later this week and will let you know.

**Comment by ribeaud** [comment]
I just made some tests:
- I do no have _any_ panic files at given location, mainly `.diag` files
- <img width="1285" alt="Screenshot 2022-09-21 at 18 57 59" src="https://user-images.githubusercontent.com/13186156/191578318-c8f14856-dae0-4745-bacf-96d3be112f1e.png">
- `Use the new Virtualization framework` does NOT work (see attached [report](https://github.com/docker/for-mac/files/9619252/virtualization_framework.txt))
- Activating **Kubernetes** works

BUT `Use Docker Compose V2` does NOT work in my case. Getting following output:

<img width="1369" alt="Screenshot 2022-09-21 at 18 58 49" src="https://user-images.githubusercontent.com/13186156/191579052-5d4da908-a8d7-466b-81e5-ac8d055892cc.png">

before computer starts to behave strangely...
