### ISSUE TITLE
Create new environment states that GIT is not installed (macOS Silicon)

### ISSUE THREAD

**Issue by iangregsondev** [docker/for-mac#6484]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 24CB324E-F494-4D1A-8742-F844775632C1/20220916074354

### Expected behavior

Dev environment states that GIT is not installed..

I have uploaded a Diagnostics with ID 24CB324E-F494-4D1A-8742-F844775632C1/20220916074354

In DEV environment should let me continue as GIT is installed

### Actual behavior

The problem is in the DEV environment it won't let me continue as it says that GIT is not installed but it is

![image](https://user-images.githubusercontent.com/2370364/190585224-b6a1f3ac-e342-4955-ae56-8b1ae4501144.png)

![image](https://user-images.githubusercontent.com/2370364/190585244-b7dc1d9f-b1c0-4f99-ae88-4c334dd53c32.png)

### Information
See 24CB324E-F494-4D1A-8742-F844775632C1/20220916074354 diagnostic ID

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
I have uploaded it with ID 24CB324E-F494-4D1A-8742-F844775632C1/20220916074354

### Steps to reproduce the behavior

See images above, basically just click on Dev Environment and Create new Environment.

**Comment by callanbr** [comment]
The same issue happened to me when installing macOS 13.0. After updating developer tools (xcode-select --install) and using brew to update git this was solved.

**Comment by vhscom** [comment]
Running `xcode-select --install` said 79 hours for install at first, then came down to ~3 minutes 😅

**Comment by vhscom** [comment]
Suggestion to run `xcode-select --install` from @callanbr indeed helped, after restarting Docker Desktop.
