### ISSUE TITLE
Containers all being removed every time when Docker restart

### ISSUE THREAD

**Issue by ivanfong01** [docker/for-mac#6491]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA8DCE68-3433-4239-ABF7-465940295E3E/20220921181952

### Expected behavior
All deployed containers should be retained

### Actual behavior
No containers persisted 

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? No, 
  - macOS Version: 12.6
  - Intel chip or Apple chip: M1 Ultra
  - Docker Desktop Version: 4.12.0 (85629)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
`

### Steps to reproduce the behavior
Restart of docker / reboot

**Comment by d8vjork** [comment]
Happening on an Intel-based Macbook Pro

**Comment by danielperez9430** [comment]
I have the same problem since 2 weeks ago, when I restart the computer all the container was lost.

MacOS: 13.01
Apple M1 Max
Docker Engine version 20.10.8
Docker Desktop version 3.6.0

**Comment by kiniry** [comment]
I had the same problem happen this week.  

macOS: 12.6.2
x86 MacBook Pro 2019
Docker Desktop version: 4.15.0
