### ISSUE TITLE
Fatal Error: Exit status 1 - how to solve?

### ISSUE THREAD

**Issue by nichmica7** [docker/for-mac#6498]
![image](https://user-images.githubusercontent.com/23216857/192851948-3aa85a0e-f474-40cc-ba51-1a908bfa07dd.png)

Apple chip

**Comment by TakatoG** [comment]
I have same problem...

**Comment by TakatoG** [comment]
I have same problem...did you solve??

**Comment by nichmica7** [comment]
Yes, I did @TakatoG. I managed to solve this issue. Basically, I used AppCleaner to uninstall the docker completely from my Mac (it also removed any files to this app) and then re-installed the docker application again. 

Worked without any issues!

**Comment by codingwesley** [comment]
> Yes, I did @TakatoG. I managed to solve this issue. Basically, I used AppCleaner to uninstall the docker completely from my Mac (it also removed any files to this app) and then re-installed the docker application again.
> 
> Worked without any issues!

Thanks very much! Save  my time

**Comment by TakatoG** [comment]
I am sorry to late reply..
Thanks a lot! I also solved.

**Comment by p-wel** [comment]
Lack of disk space on your machine can be a reason of this  _Fatal error_.

More comprehensive answer:
https://github.com/docker/for-mac/issues/6527#issuecomment-1286248340
