### ISSUE TITLE
Docker Hangs During Build

### ISSUE THREAD

**Issue by nigelgeorge** [docker/for-mac#650]
### Expected behavior

docker ps works
### Actual behavior

docker ps hangs indefinitely
### Information

Diagnostic ID: 8BB40A43-8F83-4370-B712-88B79AA3727C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Called docker build from shell script
2. docker build seemed unresponsive
3. Check docker ps

I'm still trying to get the build log files on OS X

**Comment by samoht** [comment]
@dsheets is that expected?

```
Sep 13 17:06:04 C02R4214G8WM Docker[com.docker.osx.hyperkit.linux][524] <Error>: The path /var is reserved by Docker.
        Please see the documentation for more information.
Sep 13 17:06:10 C02R4214G8WM Docker[com.docker.docker][492] <Notice>: dockerState = Starting
Sep 13 17:07:41 C02R4214G8WM Docker[com.docker.osxfs][521] <Error>: Fatal unexpected exception: Failure("osxfs_control: eof reading header from socket")
```

This seems to cause a lot of (unrelated?) connection errors.

**Comment by dsheets** [comment]
The first error is expected if one tries to export `/var`. The second error is likely unrelated as it occurs about 90 seconds later but is a serious issue. The second error is not the likely cause of the reported issue, though, as `osxfs` is not involved during `docker build` (unless the `docker build` was concurrent with some kind of settings change).

**Comment by ijc25** [comment]
Hi @nigelgeorge sorry for the delay in getting back to you.

Are you still able to reproduce this with the latest stable (1.12.3 at time of writing)?

If so then please could you try and provide a minimised repro case based on your shell scripts and Dockerfiles which demonstrates the issue. Obviously `docker build` works fine for many people, including numerous occurrences in our own automated test suites so having a reproducer based on your circumstances will greatly improve the chances of us making progress on your issue.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
