### ISSUE TITLE
Infinity loading on empty containers

### ISSUE THREAD

**Issue by stlr00** [docker/for-mac#6502]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
Stop loading
### Actual behavior
Infinity loading
### Information

  - MacOS 12.6
  - Apple chip:
  - Docker 4.12.0:
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/61075639/193262534-4e77e8fb-ef37-4dc6-ace9-a1d7a271e431.png">

**Comment by nicks** [comment]
thanks for reporting! we're investigating this.

**Comment by stlr00** [comment]
Fixed with 4.13.1
