### ISSUE TITLE
Support Headless Install of docker on MacOS (SSH, CLI Only)

### ISSUE THREAD

**Issue by maltfield** [docker/for-mac#6504]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I can ssh into my mac mini that's 2,000 km away from me and install Docker

### Actual behavior

`open /Applications/Docker.app` exits 0 and gives no output.

You have to go to the GUI to see this window pop-up

> **"Docker" is an app downloaded from the internet. Are you sure you want to open it?**
> Homebrew Cask downloaded this file on 3 May 2022 from www.docker.com. Aplle checked it for malicious software and none was detected.

Actually, this first problem is an Apple problem. And there is a CLI-only bypass:

```
xattr -r -d com.apple.quarantine /Applications/Docker.app
```

But now when you open the Docker app, it exits 1 and you get the following error:

```
LSOpenURLsWithRole() failed with error -600 for the file /Applications/Docker.app.
```

I know of no way to fix this in the CLI. In the GUI, you get a window that says:

> **Docker desktop needs privileged access.**
> 
> Docker Desktop needs privileged access to install its networking components and links to the Docker apps.
> 
> You will be asked for your password.

I clicked OK, typed my password, and then--finally--the docker binary was available at `/usr/local/bin/docker`. But I *still* couldn't launch a docker container.

```
user@host ~ % export DOCKER_CONTENT_TRUST=1

user@host ~ % docker run --rm -it --entrypoint /bin/bash debian:stable-slim 
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
user@host ~ % 
```
I used `open -a Docker` to open Docker. Again, I needed to interact with the GUI. This time to accept the ToS.

After accepting the ToS in the GUI, I needed to start Docker one last time, and then I could finally run a container from the CLI

```
user@host ~ % docker run --rm -it --entrypoint /bin/bash debian:stable-slim
Unable to find image 'debian:stable-slim' locally
docker.io/library/debian@sha256:3d412a8a2e0f087738e6185c5cddab08827880a23e5bd9dc8b2494d89e4b33fd: Pulling from library/debian
2bc8f4ca4fd1: Pull complete 
Digest: sha256:3d412a8a2e0f087738e6185c5cddab08827880a23e5bd9dc8b2494d89e4b33fd
Status: Downloaded newer image for debian@sha256:3d412a8a2e0f087738e6185c5cddab08827880a23e5bd9dc8b2494d89e4b33fd
Tagging debian@sha256:3d412a8a2e0f087738e6185c5cddab08827880a23e5bd9dc8b2494d89e4b33fd as debian:stable-slim
root@4d255f94ce06:/# 
```

### Information

In Debian Linux, I can execute the following commands to install docker, launch a new docker container based on the latest version of Debian, and get a shell inside that container

```
# securely install docker and let our user interact with it
sudo apt-get install docker.io
sudo bash -c 'gpasswd -a "${SUDO_USER}" docker'
su - `whoami`

# "securely" download and run latest Debian container
# * https://security.stackexchange.com/q/238529/213165
export DOCKER_CONTENT_TRUST=1
docker run --rm -it --entrypoint /bin/bash debian:stable-slim
```

I should be able to install docker on a headless MacOS machine just as easily over ssh

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

In MacOS, I can ([insecurely](https://apple.stackexchange.com/questions/394401/cryptographic-integrity-and-authentication-validation-of-homebrew-installer)) install docker as follows

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install --cask docker
```

But then I get `command not found` errors when attempting to run a new container (in both zsh and bash)

```
user@host ~ % export DOCKER_CONTENT_TRUST=1
user@host ~ % docker run --rm -it --entrypoint /bin/bash debian:stable-slim 
zsh: command not found: docker
user@host ~ % bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ export DOCKER_CONTENT_TRUST=1
bash-3.2$ docker run --rm -it --entrypoint /bin/bash debian:stable-slim 
bash: docker: command not found
bash-3.2$ 
```

**Comment by maltfield** [comment]
See also https://apple.stackexchange.com/questions/444913/how-to-launch-docker-container-from-cli-in-macos-eg-docker-run/448475#448475

**Comment by nicks** [comment]
Have you seen this guide? https://docs.docker.com/desktop/install/mac-install/#install-from-the-command-line

**Comment by maltfield** [comment]
No I did not! I do think this ticket still needs action, though.

Can you make cli execution of `/Applications/Docker.app` do something other than just exit 0 with no output? If there is, in fact, CLI usage, can you please make it output something like

```
Launching Docker in GUI mode. For CLI usage, execute /Applications/Docker.app --help
```

And then make `/Applications/Docker.app --help` output some basic documentation of all the available command-line arguments?

**Comment by nicks** [comment]
:thinking: Hmmmm...I'm not sure that a macos NSApplication bundle should support CLI parameters. But I also don't write native macos apps a lot...don't know if it would break anything or if it's just non-idiomatic. We'd want to investigate what other apps do.

But I 100% agree with the larger point that if the Docker Desktop isn't starting the engine (either for license reasons, or some other error), there should be a CLI-only mechanism to explain what's going on. Want to think a bit on the right way to do this.

**Comment by maltfield** [comment]
> thinking Hmmmm...I'm not sure that a macos NSApplication bundle should support CLI parameters. But I also don't write native macos apps a lot...don't know if it would break anything or if it's just non-idiomatic. We'd want to investigate what other apps do.

fwiw, I maintain an open-source software project that produces NSApplication bundles on MacOS. It's both a GUI and a CLI app.

If the .app is called without any arguments, it just prints to the screen that it's launching the GUI and tells the user to type `myapp.app --help` for instructions on how to use it over the CLI.

If the .app is called with any arguments, it doesn't launch the GUI because it knows the user expects CLI interaction.

**Comment by rvignesh89** [comment]
@maltfield removing the quarantine attribute is what I was missing! With the following steps I am able to install and start Docker Desktop without any UI intervention,

```
# steps from https://docs.docker.com/desktop/install/mac-install/#install-from-the-command-line
sudo hdiutil attach Docker.dmg
sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accep-license
sudo hdiutil detach /Volumes/Docker

# Remove quarantine attribute
sudo xattr -r -d com.apple.quarantine /Applications/Docker.app

# Install privileged components
sudo /Applications/Docker.app/Contents/MacOS/Docker \
      --unattended \
      --install-privileged-components

# Start Docker 
open -a /Applications/Docker.app
```

But I agree with you that there should be better docs for installation and CLI args. I think there is issue to track that https://github.com/docker/roadmap/issues/172

**Comment by maltfield** [comment]
//remove-lifecycle stale

**Comment by alfredocambera** [comment]
> @maltfield removing the quarantine attribute is what I was missing! With the following steps I am able to install and start Docker Desktop without any UI intervention,
> 
> ```
> # steps from https://docs.docker.com/desktop/install/mac-install/#install-from-the-command-line
> sudo hdiutil attach Docker.dmg
> sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accep-license
> sudo hdiutil detach /Volumes/Docker
> 
> # Remove quarantine attribute
> sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
> 
> # Install privileged components
> sudo /Applications/Docker.app/Contents/MacOS/Docker \
>       --unattended \
>       --install-privileged-components
> 
> # Start Docker 
> open -a /Applications/Docker.app
> ```
> 
> But I agree with you that there should be better docs for installation and CLI args. I think there is issue to track that [docker/roadmap#172](https://github.com/docker/roadmap/issues/172)

I had to add this as the docker executable isn't available in the path after the installation is complete:

```bash
export PATH=$PATH:~/.docker/bin
```

**Comment by JonathanWheeler** [comment]
@nicks, regarding:

> Hmmmm...I'm not sure that a macos NSApplication bundle should support CLI parameters.

For something like accepting the EULA, this should absolutely be supported, or a separate CLI tool made available to accomplish the same. This will allow people like myself who want/need to install the GUI version of things to do so, while still scripting out the automatic installation of things across my systems.

This can be accomplished using `open --args`:

```bash
open /Applications/Docker.app --args --accept-license  # NB: Currently not supported by Docker.app.
```

Per `man open`:

```
       --args
           All remaining arguments are passed to the opened application in the argv parameter to main().
           These arguments are not opened or interpreted by the open tool.
```

Otherwise this happens:
```bash
$ brew install --cask --no-quarantine docker
$ open /Applications/Docker.app --args --accept-license  # No effect; EULA still not accepted.
$ docker container ls
Cannot connect to the Docker daemon at unix:///Users/jonathan/.docker/run/docker.sock. Is the docker daemon running?
```

I'd sincerely appreciate this being supported, and it should be relatively simple to accomplish.

Thank you for your work and effort!

**Comment by bsousaa** [comment]
related with https://github.com/docker/for-mac/issues/6979

**Comment by bsousaa** [comment]
Headless/unattended install is supported by Docker Desktop as documented at https://docs.docker.com/desktop/install/mac-install/#install-from-the-command-line see `--accept-license` flag.

For the case of starting Docker Desktop and accepting the license (new feature), I'm closing this issue in favour of https://github.com/docker/for-mac/issues/6979. Please add any comment at #6979.
