### ISSUE TITLE
Docker on mac monterey [12.6] doesn't start up

### ISSUE THREAD

**Issue by asad-awadia** [docker/for-mac#6507]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: can't cause it doesn't startup

### Expected behavior

Docker runs

### Actual behavior

Blank white screen with docker never starting up

### Information

Installed via docker dmg for intel mac directly from website

<img width="287" alt="Screen Shot 2022-10-04 at 4 37 57 PM" src="https://user-images.githubusercontent.com/6923282/193922637-05903548-4ac0-47c1-aa2c-44a5914b4ef6.png">
<img width="816" alt="Screen Shot 2022-10-04 at 4 37 47 PM" src="https://user-images.githubusercontent.com/6923282/193922651-de85dbcf-fdc7-4ca2-ae68-5de18335e68d.png">
  - macOS Version: 12.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 20.10.17, build 100c701

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
such file or directory
[2022-10-04T20:32:43.903514000Z][com.docker.diagnose][I] (89fa97b4-8) 37680659-diagnose-network C->S diagnosticsd GET /ping
[2022-10-04T20:32:43.904325000Z][com.docker.diagnose][W] (89fa97b4-8) 37680659-diagnose-network C<-S NoResponse GET /ping (806.037µs): Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory

[FAIL] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: failed to open kmsg.log: open log/vm/kmsg.log: no such file or directory
```

**Comment by asad-awadia** [comment]
I have virtual box 6.1 installed

Do i need to install something? Setup something?

**Comment by asad-awadia** [comment]
had to install older version [4.11.0] to get it to not show a white screen

but not it is stuck on docker is starting forever

**Comment by asad-awadia** [comment]
cpu maxed out..

**Comment by asad-awadia** [comment]
working now on 4.11

**Comment by jessitron** [comment]
me too, 4.11 is functional.

**Comment by trungutt** [comment]
@asad-awadia Next time if it happens, please follow this guide https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal to upload a diagnostic, so we could look into your issue. 

Otherwise, could you please tell us what experimental features in your settings? (Docker Desktop > Settings > Experimental features)
