### ISSUE TITLE
Option to disable feedback

### ISSUE THREAD

**Issue by tony-nz** [docker/for-mac#6508]
Could we please get an option to disable feedback? It is hugely annoying to get this popup after every, single, update. if I wanted to give feedback, I'll do it like I am doing so now, via Github.

**Comment by nicks** [comment]
Thanks for reporting! 

It's hard to tell with certainty which popup you're referring to, but Docker Desktop 4.11 fixes a bug where we were showing feedback popups too frequently for some users. https://docs.docker.com/desktop/release-notes/#docker-desktop-4110

After the update, you should only see a feedback popup every 6 months (and 30 days after a first install / factory reset). If you see one more than that after 4.11, please file a new issue with diagnostic information so we can investigate further.
