### ISSUE TITLE
Cannot exec '/Users/.../Library/Containers/com.docker.docker/Data/vms/0/tty': No such file or directory

### ISSUE THREAD

**Issue by PJCSpencer-SRT** [docker/for-mac#6514]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 00FF5147-4D62-4090-B187-15353A9D1612/20221011122129

### Expected behavior
Screen application to be working

### Actual behavior
Prompt: No such file or directory
**com.docker.docker** component is not present on hd.

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: Docker Desktop Version 4.12.0 (85629)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Download and install Desktop Docker (Mac with Apple Chip)
  2. Type in terminal: screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty

**Comment by nicks** [comment]
Hi! Thanks for reporting! I don't think we support this anymore, the recommended solution is to use nsenter to create a shell into the VM, here's a guide on how to do it:
https://github.com/justincormack/nsenter1
