### ISSUE TITLE
can not click start/stop button by tooltip.

### ISSUE THREAD

**Issue by bties-ogawa** [docker/for-mac#6516]
this tooltip is not nesessary.

![スクリーンショット 2022-10-12 9 42 16](https://user-images.githubusercontent.com/20296827/195223580-91443d0a-c7ba-4f9f-bf74-08c3b4c34969.png)

![スクリーンショット 2022-10-12 9 42 23](https://user-images.githubusercontent.com/20296827/195223586-22b502e4-445f-4d17-bcc6-78f45ddb6e42.png)

**Comment by bties-ogawa** [comment]
tooltip hide next button. nobody can click next button.

**Comment by nicks** [comment]
thanks for reporting! let me see if we can find a better solution for this.

**Comment by bties-ogawa** [comment]
i thisnk, it is probably better if tooltip never show.
because, those button are already icon. square icon is stop. triangle icon is start. already we know. Those are so famouse.
You know, Almost mucis players are also.

please concider my idea.

and i am sorry to be cheatp at english.
thanks!

**Comment by trungutt** [comment]
Tooltip now disappears more quickly as the cursor moves out of the element (from Docker Desktop 4.14 I beleive). I closed the issue, feel free to open it again if needed
