### ISSUE TITLE
Big Sur and Monterey VM - Docker Desktop window not showing GUI correctly, though can mouse over where buttons should be

### ISSUE THREAD

**Issue by Avsynthe** [docker/for-mac#6517]
Expected behavior

Docker Dekstop window should be displaying UI correctly

 Actual behavior

Window is completely blank except for the background. In very rare circumstances the UI does show up but glitches and flickers to different spots around the window. I have tested this on Big Sur and Monterey and the issue is consistent, previous versions of docker (v3 and below) seem to work fine and current version works fine on Catalina.

The buttons are there as I can move the mouse around and click items albeit blindly. Daemon starts and everything is functioning as it should except for the UI

Information

  - macOS Version: Big Sur and Monterey VMs
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Latest

Steps to reproduce the behavior

Open the Docker Desktop GUI

![docker-blank](https://user-images.githubusercontent.com/102600593/195743849-bf4c62bc-0633-4d5d-b6cc-ab19d379117f.png)

**Comment by nicks** [comment]
i have never seen this before!! can you share a diagnostic? you can collect a diagnostic from the terminal with these instructions: https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal
