### ISSUE TITLE
Fatal Error Incompatible CPU detected

### ISSUE THREAD

**Issue by workfel** [docker/for-mac#652]
### Information

Diagnostic ID: A04B9ECD-9646-407B-BEA0-B713F0E7E211
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Johan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/A04B9ECD-9646-407B-BEA0-B713F0E7E211/20160916-113928/qemu-img-check.stdout 2> /tmp/A04B9ECD-9646-407B-BEA0-B713F0E7E211/20160916-113928/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/Johan/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Johan/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/Johan/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Johan/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/Johan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
@workfel thanks for opening this issue.
It looks like your CPU isn't supported by Docker for Mac.
You can confirm by running the following command:

```
$ sysctl -a kern.hv_support
```

A supported CPU will show:
```
kern.hv_support: 1
```

An unsupported CPU will show:
```
kern.hv_support: 0
```

If you could confirm the output on your issue it will help us know if this is an issue in the detection code, or whether it's just that your CPU isn't supported.

Thanks for trying Docker for Mac!

**Comment by workfel** [comment]
@dave-tucker  ! Thank you the command show `kern.hv_support: 0`.

So, i installed Docker Toolbox and it's works .

Thanks
