### ISSUE TITLE
Docker not start after update

### ISSUE THREAD

**Issue by Hademath** [docker/for-mac#6522]
I just updated my docker app and it was successful, but it can't start up, so i can't connect to the daemon from my machine. what can I do to get it work .

**Comment by jsolderitsch** [comment]
Same issue here. Also had to downgrade to 4.12. I did run a diagnostics pass on the 4.13 version that fails to start. I see the docker process in the Activity Manager but it is just sitting there, not consuming any CPU. I wiped out the 4.13 install, created the 4.12 Applications folder by drop and drag and that version works as expected.

**Comment by tpayne84** [comment]
I too am having the issue, it appears to be a feature from the `.13` release notes:
`By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead.`

In practice though, this prevents things that rely on the socket from connecting. Like PyCharm for example.

This does not feel like a feature to me -- Is there a way to force the symbolic link creation?

**Comment by vredeling** [comment]
I'm also downgrading to 4.12, container removal suggestion didn't work.

**Comment by timmattison** [comment]
This just bit me today. If anyone else wants an older version you can get them from the release notes page - https://docs.docker.com/desktop/release-notes/#docker-desktop-4120

**Comment by Hademath** [comment]
> @Hademath Before fixing the issue I would recommend to collect some [diagnostic information](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) so the docker team can debug the issue.

Thanks for the reply, I have been able to resolve it after uninstall and install again.

**Comment by mscrivo** [comment]
> > @Hademath Before fixing the issue I would recommend to collect some [diagnostic information](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) so the docker team can debug the issue.
> 
> Thanks for the reply, I have been able to resolve it after uninstall and install again.

Uninstall how? I tried deleting the app from finder and reinstalling a couple times and it still won't load.

**Comment by mscrivo** [comment]
This worked for me: https://github.com/docker/for-mac/issues/6527#issuecomment-1286248340

**Comment by dhanyn10** [comment]
> This worked for me: [#6527 (comment)](https://github.com/docker/for-mac/issues/6527#issuecomment-1286248340)

worked for me too, Linux Mint 21

**Comment by vredeling** [comment]
Is this issue still present in 4.13.1?

**Comment by vredeling** [comment]
Upgraded to 4.13.1, problem is not solved.

**Comment by Ben-Atherton** [comment]
Upgrade to 4.13.1 didn't work for me either, back to 4.12

**Comment by pythoninthegrass** [comment]
**Diags ID**: `7B6094D4-EFCB-4E8F-A4CE-D2D6800EB1AD/20221103041520`.
**Docker Desktop**: v4.13.1
**macOS**: 12.6 (21G115)

```bash
rm -rf ~/Library/Containers/com.docker.*
```
^^ Didn't work. Yet to reboot, but suspect that might help 🤔

**Comment by dhanyn10** [comment]
> **Diags ID**: `7B6094D4-EFCB-4E8F-A4CE-D2D6800EB1AD/20221103041520`. **Docker Desktop**: v4.13.1 **macOS**: 12.6 (21G115)
> 
> ```shell
> rm -rf ~/Library/Containers/com.docker.*
> ```
> 
> ^^ Didn't work. Yet to reboot, but suspect that might help thinking

@pythoninthegrass can this https://github.com/docker/for-mac/issues/6527 help you?

**Comment by pythoninthegrass** [comment]
> > **Diags ID**: `7B6094D4-EFCB-4E8F-A4CE-D2D6800EB1AD/20221103041520`. **Docker Desktop**: v4.13.1 **macOS**: 12.6 (21G115)
> 
> > 
> 
> > ```shell
> 
> > rm -rf ~/Library/Containers/com.docker.*
> 
> > ```
> 
> > 
> 
> > ^^ Didn't work. Yet to reboot, but suspect that might help thinking
> 
> 
> 
> @pythoninthegrass can this https://github.com/docker/for-mac/issues/6527 help you?

[This](https://github.com/docker/for-mac/issues/6527#issuecomment-1286248340) worked

**Comment by jsolderitsch** [comment]
As @pythoninthegrass reports here, the @timmattison sudo execution repairs a messed up update from 4.12 to 4.13.1 for me too. The Mac OS Docker Desktop dev team needs to revisit the update experience. I am running Monterey (latest) on an Intel Macbook.

**Comment by ZhongRuoyu** [comment]
Docker Desktop 4.14.0 is released, which has "fixed a startup failure for users of Virtualization framework" ([release notes](https://docs.docker.com/desktop/release-notes/)). That seems to have fixed this.

**Comment by jsolderitsch** [comment]
I was able to update from 4.13.1 (that I had to install from scratch after a failed update from 4.12) to 4.14 without issues.

**Comment by jsolderitsch** [comment]
Problem of bad update behavior hasn't re-surfaced for me. I have updated several times and am at 4.16.2 currently.
