### ISSUE TITLE
Fatal Error code 11. First time installer

### ISSUE THREAD

**Issue by silky098** [docker/for-mac#6524]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 

### Expected behavior
It should install
### Actual behavior
It immediately throws the error code 11. See blow.

### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 17.03.1-ce-rc1-mac3 (1795b358d)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 12.6 (build: 21G115)
logs: /tmp/BA2B8AA3-4039-42E6-A09D-A5B38891A5A2/20221018-200940.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/shaila/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/shaila/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/shaila/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/shaila/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/shaila/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/shaila/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
Hi @silky098 ! 17.03.1-ce-rc1-mac3 is a very old version of Docker for Mac, from 2017. You're trying to install it on a very new version of macOS, from 2022. I'm not sure I would expect this to work. Can you elaborate a bit more on why you're not installing the latest version?
