### ISSUE TITLE
Docker Fatal Error

### ISSUE THREAD

**Issue by mado-bohsali** [docker/for-mac#6525]
Diagnostics ID: 7064A99F-7EFF-4DE8-A27C-7A8909FAC004/20221019131935
exit status 255

This occurs when I build a Node.js / React application locally
MacOS Monterey
Version 12.6

**Comment by joe0BAB** [comment]
@mado-bohsali thanks for reporting the issue! Could you provide more details? What does the exit status belong too? Where is the 'fatal error' shown? Eg a screenshot would help.

**Comment by mado-bohsali** [comment]
Feel free and close it @joe0BAB
