### ISSUE TITLE
Fail to startup docker on MacOS Sierra RC

### ISSUE THREAD

**Issue by andresnatanael** [docker/for-mac#653]
### Information

Diagnostic ID: EB6AFE2E-34AA-4617-B849-D79863CDC40C
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)

### Steps to reproduce

1. ...
2. ...

**Comment by dave-tucker** [comment]
Closing as 1.12.0-a is currently not supported on macOS Sierra

Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
Download: https://download.docker.com/mac/beta/Docker.dmg
Thanks for your help testing Docker for Mac with Sierra!
