### ISSUE TITLE
Cannot connect to docker daemon on M2

### ISSUE THREAD

**Issue by wxharry** [docker/for-mac#6532]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AA1AB7BB-F845-4DAC-9A9D-74C5F73B268F/20221024000033

### Expected behavior
Expected to see no error when other apps try to use docker

### Actual behavior
when using tools like `act` and `lazydocker`, cannot connect to docker daemon error:
``` shell
Docker event stream returned error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: m2
  - Docker Desktop Version: 4.13.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
``` shell
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

```
### Steps to reproduce the behavior

  1. install docker desktop
  2. docker ps
  3. lazydocker

**Comment by nicks** [comment]
Thanks for the report! We're trying to make Docker Desktop more userspace-friendly (e.g., fewer root privileges). As part of that, we're migrating the sockets to user-owned directories rather than root-owned directories (like /var/run). Desktop 4.13 no longer installs a socket under /var/run.

For now you can work around this by creating the symlink manually:

```
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

We're talking internally about a better way to roll this out. For now, I'm going to duplicate this against https://github.com/docker/for-mac/issues/6529 to centralize the discussion.
