### ISSUE TITLE
DMG File Corrupted - MacOS - 25/10/2022

### ISSUE THREAD

**Issue by Felipe-Holanda** [docker/for-mac#6535]
- [ X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

  - macOS Version: 10.13
  - Intel chip or Apple chip: Intel Chip
  - Docker Desktop Version: Current on this date

Attemping to install Docker on my computer, the DMG File downloaded from the main website appears to be corrupted, by this, docker are unable to be installed... attepted by using `brew install docker` and `brew instal --cask docker`... unfortunately keep unsucessfull.

**Comment by suhayb93** [comment]
Same issue here, is there is any work around for this until it fixed

**Comment by DavideDelVecchio** [comment]
Same thing here any work around?

**Comment by kentsor2** [comment]
Happens here too. I'm on Mojave, 10.14. Is the dmg  format not supported?

**Comment by nicks** [comment]
This usually means there's something wrong with your Mac where it has trouble opening the dmg - e.g. the system time is set wrong or you have a misconfigured anti-virus.

If the dmg was truly corrupted, we'd be able to reproduce it and be getting more widespread reports.

**Comment by kentsor2** [comment]
There is nothing wrong with my Mac. It opens any other dmg just fine. Suggesting system time being wrong as a cause ...  well, let's just not comment on that one. There is no antivirus installed.

There are our reports right here. Two of them reports using old versions of OS X, perhaps the others as well. In my case the Mac cannot be upgraded as it runs a legacy carbon app.

**Comment by nicks** [comment]
re: "Suggesting system time being wrong as a cause"

LOL, I know it sounds crazy, but you'd be surprised! A common cause of "corruption" errors on MacOS is that the OS is having issues validating the signature on the binary, and the system time is used for cert validation on the signature.

**Comment by nicks** [comment]
could you try installing the dmg from the command line and see what errors you get?

https://docs.docker.com/desktop/install/mac-install/#install-from-the-command-line

```
sudo hdiutil attach Docker.dmg
sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
sudo hdiutil detach /Volumes/Docker
```

hdiutil has a few different flags that you can use to test which part of the "corruption" test is triggering on the dmg file (e.g., `-noverify`, `-ignorebadchecksums`, etc)

**Comment by kentsor2** [comment]
by itself:
Kents-MacBook-Air-3:Downloads kent$ sudo hdiutil attach 'Docker 9.55.03 PM.dmg'
hdiutil: attach failed - corrupt image

Kents-MacBook-Air-3:Downloads kent$ sudo hdiutil attach -noverify 'Docker 9.55.03 PM.dmg'
hdiutil: attach failed - corrupt image

Kents-MacBook-Air-3:Downloads kent$ sudo hdiutil attach -ignorebadchecksums 'Docker 9.55.03 PM.dmg'
hdiutil: attach failed - corrupt image

same with -noidme and -noautofsck

Then I did -verbose and this seems promising
Kents-MacBook-Air-3:Downloads kent$ sudo hdiutil attach -verbose 'Docker 9.55.03 PM.dmg'
Initializing…
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CMacBinaryEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CAppleSingleEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CEncryptedEncoding
DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
DIFileEncodingNewWithBackingStore: CUDIFEncoding
DIFileEncodingNewWithBackingStore: instantiator returned 0
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedNDIFEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CSegmentedUDIFRawEncoding
DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
CRawDiskImage: data fork length 0x0000000025D099F4 (634427892) not a multiple of 512.
DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
DIDiskImageInstantiatorProbe: interface  4, score        0, CDARTDiskImage
DIDiskImageInstantiatorProbe: interface  5, score        0, CDiskCopy42DiskImage
DIDiskImageInstantiatorProbe: interface  6, score    -1000, CNDIFDiskImage
DIDiskImageInstantiatorProbe: interface  8, score     -100, CShadowedDiskImage
DIDiskImageInstantiatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
DIDiskImageInstantiatorProbe: interface 10, score     -100, CWrappedDiskImage
DIDiskImageNewWithBackingStore: CUDIFDiskImage
error: chunk 0 is not recognized -2147483640 (0x80000008)
DIDiskImageNewWithBackingStore: instantiator returned 107
Attaching…
Error 107 (corrupt image).
Finishing…
DIHLDiskImageAttach() returned 107
hdiutil: attach failed - corrupt image

**Comment by kentsor2** [comment]
The original file was downloaded with Safari. I downloaded it again with Chrome, and the error is the same.

**Comment by nicks** [comment]
Did some research into this. I think I see what happened here.

Apple end of life'd macOS 10.14 last year - https://endoflife.date/macos

At Docker, we officially dropped support for all versions of macOS below 11. https://docs.docker.com/desktop/install/mac-install/

As part of that change, we switched to ULMO-format DMGs, which are smaller for most users, but are not supported below macOS 10.15 - https://keith.github.io/xcode-man-pages/hdiutil.1.html#format~2

I'm highly annoyed that you're not getting a better error-message here ... presumably hdiutil could do a better job detecting when the DMG is in a format your system doesn't support. But this is not really something we're able to fix; macOS controls all the tooling AFAIK.

Marking this as wont-fix / unfortunate, sorry.

**Comment by suhayb93** [comment]
for me, it has been fixed when I upgrade my OSX version from  High Sierra to Ventura

Thanks
