### ISSUE TITLE
downloading updates does not work

### ISSUE THREAD

**Issue by kidbrax** [docker/for-mac#6537]
I am notified an update is available. So I go and start the download and then it just sits there and says "Downloading update..." forever and nothing ever happens.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Expect download to complete

### Actual behavior

Download doesn't complete. Or at least it doesn't tell us it completes

### Information

Would be nice if there was a progress indicator as well.

  - macOS Version: Ventura
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.11.1 (84025)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
$ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[FAIL] DD0015: are the binary symlinks installed? /usr/local/bin/kubectl is not a symbolic link
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the binary symlinks installed?
    Failed with: /usr/local/bin/kubectl is not a symbolic link

The symlinks to the docker CLI etc are needed for docker commands to work.
```

### Steps to reproduce the behavior

start an update and you'll see it just sit there and do nothing

**Comment by holograph** [comment]
Been having much the same problem on several machines: the one whose details are below and a Macbook Air M1. Unfortunately it's been going on for about a year across many, many different Docker versions, and the built-in update mechanism worked maybe once or twice _ever_.

Current specs:
* MacOS Monterey 12.6.1 (21G217)
* MacBook Pro (16-inch, 2019)
* Docker desktop version 4.11.1 (84025)

To be clear: this happens *consistently* across MacOS versions, processor architectures, wifi networks and geographies.

**Comment by jdsteinbach** [comment]
/remove-lifecycle stale

I'm having the same issue: Docker for Mac starts downloading an update, but never completes

* macOS Ventura 13.2
* MacBook Pro (14-inch, 2021), Apple M1 Pro
* Docker Desktop `4.16.1 (95567)`, attempting to update to`4.16.2 (95914)`

To echo the earlier comment about this happening more broadly; I had the same issue with a 16" MacBook Pro on Monterrey (macOS 12.latest) about 6 mo ago. (No longer have that computer, so can't provide specific details, but I got the same behavior from Docker Desktop updates.)

**Comment by holograph** [comment]
I have not encountered this in a fairly long while.. but then I've also switched away from Docker Desktop, so :-/
