### ISSUE TITLE
 docker run docker/whalesay cowsay boo

### ISSUE THREAD

**Issue by zhangqx2010** [docker/for-mac#654]
### Information

Diagnostic ID: 2F07C19B-C2E8-4B02-91D3-868CC8DCA330
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 2F07C19B-C2E8-4B02-91D3-868CC8DCA330/20160916-215505.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on.

May be related to docker/for-mac#785

The following log matches:
```
Sep 10 08:13:14 192 Docker[com.docker.vmnetd][8200] <Notice>: User 501 has container folder /Users/qqf/Library/Containers/com.docker.docker/Data/s60
Sep 10 08:13:14 192 Docker[com.docker.vmnetd][8200] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 10 08:13:14 192 Docker[com.docker.vmnetd][8200] <Notice>: User 501 has container folder /Users/qqf/Library/Containers/com.docker.docker/Data/s60
Sep 10 08:13:14 192 Docker[com.docker.vmnetd][8200] <Critical>: File /var/run/docker.sock is a symlink or a socket
Sep 10 08:13:14 192 Docker[com.docker.docker][8186] <Error>: Symlinks are not correctly installed.
Sep 10 08:13:14 192 Docker[com.docker.docker][8186] <Notice>: com.docker.osx.hyperkit.linux launched with PID 8203
Sep 10 08:13:14 192 Docker[com.docker.frontend][8204] <Critical>: dial unix /Users/qqf/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
Sep 10 08:13:14 192 Docker[com.docker.docker][8186] <Error>: frontend process failed
Sep 10 08:13:14 192 Docker[com.docker.osx.hyperkit.linux][8203] <Notice>: Acquired task manager lock
Sep 10 08:13:14 192 Docker[com.docker.osx.hyperkit.linux][8203] <Notice>: Maximum number of file descriptors is 10240
```

**Comment by samoht** [comment]
Please follow the resolution of #785 for updates on your issue. In the meantime, a workaround is to re-install Docker.app and/or reset to factory settings.
