### ISSUE TITLE
macos ventura

### ISSUE THREAD

**Issue by camus57** [docker/for-mac#6542]
Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 13.0 (build: 22A380)
logs: /tmp/54FA4FFE-F5AF-4D4C-A9E9-7B56BEB6026F/20221028-175439.tar.gz
failure: vpnkit is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/lip/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/lip/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")) connecting to /Users/lip/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/lip/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[OK]     disk

**Comment by nicks** [comment]
Version 17 is a very old version of Docker for Mac. I'm not sure that we would expect it to work. You'll have to upgrade to a more recent version.
