### ISSUE TITLE
docker ps doesn't respond :(

### ISSUE THREAD

**Issue by bkbonner** [docker/for-mac#655]
### Expected behavior

run
docker ps

and have it show containers
### Actual behavior

Error response from daemon:  Bad response from Docker engine
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
  D03FD8EB-A28F-4BB6-AEBA-A7F323485561
- a reproducible case if this is a bug, Dockerfiles FTW
- page URL if this is a docs issue or the name of a man page
- host distribution and version (OSX 10.10.x, OSX 10.11.x)

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/D03FD8EB-A28F-4BB6-AEBA-A7F323485561/20160916-105216.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior
1.  Clicked on upgrade docker button today. 

Sigh.   this sucks.

**Comment by djs55** [comment]
It looks like the docker engine has failed to start inside the VM, complaining about the `/var/lib/docker` contents. There are log lines like
```
time="2016-09-16T14:51:22.426495089Z" level=error msg="invalid image sha256:3e38a00e70caaeecc92bbb460b2a352c1f8dfa6625c4b3136788ba8b17cead99, failed to verify image: sha256:3e38a00e70caaeecc92bbb460b2a352c1f8dfa6625c4b3136788ba8b17cead99"
...
time="2016-09-16T14:51:22.616168261Z" level=fatal msg="Error starting daemon: Couldn't create Tag store repositories: EOF"
```
Unfortunately I think the only option is to use "whale menu -> Uninstall / Reset -> Reset to factory defaults" which will erase `/var/lib/docker`. Unfortunately images and containers will need to be re-created or re-pulled :(

**Comment by somit** [comment]
I faced similar issue.. few days back .. I restored it to factory. During restoration make to say to yes to import option which will import all existing images.

**Comment by ijc25** [comment]
Detected symptom of problem 'aufs-corruption' in D03FD8EB-A28F-4BB6-AEBA-A7F323485561/20160916-104351.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20, please subscribe there for further updates.
