### ISSUE TITLE
i tried to install angular on my mac i got this error  ???

### ISSUE THREAD

**Issue by kirush98** [docker/for-mac#6556]
kirushikan@Mokanathass-MacBook-Pro ~ % npm install -g @angular/cli
npm WARN using --force Recommended protections disabled.
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /Users/kirushikan/.npm-global/lib/node_modules/@angular/cli
npm ERR! dest /Users/kirushikan/.npm-global/lib/node_modules/@angular/.cli-MdYSHfZG
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/kirushikan/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kirushikan/.npm/_logs/2022-11-04T08_27_05_948Z-debug-0.log
kirushikan@Mokanathass-MacBook-Pro ~ %

**Comment by trungutt** [comment]
This does not look like an issue with the Docker Desktop application itself
