### ISSUE TITLE
local dev env fails everytime

### ISSUE THREAD

**Issue by marchesir** [docker/for-mac#6559]
- [ X] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features

### Expected behavior
local dev env is created

### Actual behavior
local dev env creation exites with error and red icon

### Information

  - macOS Version: monterey, ventura
  - Intel chip or Apple chip: m1 pro
  - Docker Desktop Version: latest

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.

### Steps to reproduce the behavior
  1. from DD create dev env using empty local folder

<img width="923" alt="error" src="https://user-images.githubusercontent.com/10289630/200137292-019d741c-aa05-4288-8383-7b7778a69714.png">

**Comment by rimelek** [comment]
I tried it too. The Dev Environment tries to detect the language in which the source code was written, and it fails, since the folder is empty. I tried to add a simple `index.php` file, but it didn't help. However, it worked when I opened one of my old, a real PHP projects. It also worked when I opened an other project which was detected as shell scripts, but not when I just created a single shell script with a shebang line and an `echo "HELLO"`

**Comment by marchesir** [comment]
Seems empty folder with no  code confuses the auto dedection, also seems to have started sinsce DD introduced compose.yml based system.   Interesting if checkout of empty git repo and thus no code is used and not local folder option works fine.

**Comment by nicks** [comment]
thanks for the report! ya, i think that diagnosis is right.

**Comment by marchesir** [comment]
working fine for me now thank
