### ISSUE TITLE
Docker never starts

### ISSUE THREAD

**Issue by allofthesepeople** [docker/for-mac#656]
### Expected behaviour

Docker beta should start.

### Actual behavior

Docker beta (Version 1.12.1-beta26.1 (build: 12100)) never starts. Menu item always stats docker is loading.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior

  1. Download Docker beta Version 1.12.1-beta26.1 (build: 12100)
  2. Start app
  3. Observe app never starts

**Comment by djs55** [comment]
Could you upload some diagnostics and include the diagnostic id? Without more information we can't help :(

**Comment by patricjansson** [comment]
Having the same trouble after upgrading. The whale is stuck on "Docker is restarting". I have tried restarting Docker and my Mac.

Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/FDCA4F94-214C-4775-9C99-37CCBF058166/20160919-085416.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by patricjansson** [comment]
Found a solution:  Running "Reset Docker to factory defaults." fixed the problem for me.

**Comment by allofthesepeople** [comment]
@patricjansson thanks, "Reset Docker to factory defaults." under "preferences" => "uninstall/reset" fixed it.

**Comment by SydOps** [comment]
Yes, work for me as well after reset to factory default.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
