### ISSUE TITLE
[Feature Request] Please change the icon while docker isn't the latest version.

### ISSUE THREAD

**Issue by shezhangzhang** [docker/for-mac#6563]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker is update very frequently. But this icon makes users feel very **anxious**. Please change another one.
### Actual behavior
<img width="69" alt="image" src="https://user-images.githubusercontent.com/26793777/200468212-9fea2372-529c-4bd8-9795-055fef8aed1d.png">
When docker isn't the latest one, this icon will always shows. Which makes me feel anxious because sometimes I don't want to update my docker desktop. And this icon push me to do that.

### Information

  - macOS Version: latest
  - Intel chip or Apple chip: Apple chiip
  - Docker Desktop Version: 4.12.0

**Comment by trungutt** [comment]
Hi @shezhangzhang Thanks for feedback. Ideally we want our users to stay up-to-date, we're aware of shortcomings in Docker Desktop update experience though. But I'd like to know if you have particular reasons not to update it

**Comment by shezhangzhang** [comment]
@trungutt Thanks for your reply :-D. The reason is I usually use a certain version for a  period of time. before I update it, this icon always shows there. I know docker want users to use the latest version. But this icon really make me feel anxious, personally.
