### ISSUE TITLE
Mount paths should be shown in actual case.

### ISSUE THREAD

**Issue by wyattbiker** [docker/for-mac#6564]
docker desktop Version 4.13.1 (90346)
Mac OS X Catalina

Mount paths in Inspect panel should be shown in the actual case. Now they are shown as uppercased so copy and paste does not work.

E.g in Inspect screen for my php container the mounts are show
Mounts
**/SESSIONS**        /var/lib/docker/volumes/286fb888eeeab86d7ed5fefcfdd2e35a655fcdfbb73f845eb692420237a4912c/_data

**/USR/LOCAL/ETC/PHP/CONF.D/PHP-PHPMYADMIN.INI**       /Users/user/wintercms/lamp/config/php/php.ini

**/VAR/WWW/HTML**	/Users/user/wintercms/lamp/www

**/ETC/APACHE2/SITES-ENABLED**	/Users/user/wintercms/lamp/config/vhosts

**/ETC/APACHE2/SSL**	/Users/user/wintercms/lamp/config/ssl

**/USR/LOCAL/ETC/PHP/PHP.INI**	/Users/user/wintercms/lamp/config/php/php.ini

**/VAR/LOG/APACHE2**	/Users/user/wintercms/lamp/logs/apache2

**/VAR/LOG/XDEBUG**		/Users/user/wintercms/lamp/logs/xdebug

**Comment by Michael-Renner** [comment]
4.13.1 - MacOS 13.0

Two containers aren't launching anymore after upgrade to the version 4.13.1. The shared path can be added to the Preferences panel. After clicking the "Apply & restart" the panel refreshes and deletes the former newly created shared path (/Volumes/BigBestFast/Docker/teslawallconnector).

Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - Mounts denied: The path /data/prometheus is not shared from the host and is not known to Docker. You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing. See https://docs.docker.com/desktop/mac for more info.

**Comment by wyattbiker** [comment]
@Michael-Renner you need to make a separate ticket for this. Doesn't belong with this one.
