### ISSUE TITLE
Macos - Docker desktop: Cannot start Docker Compose application. Reason: exit status 1

### ISSUE THREAD

**Issue by ngohuytrieu** [docker/for-mac#6566]
Hi guys, after upgrading to macOS 13.0, I can't start or delete containers from the Docker Desktop GUI app anymore

It works fine on the terminal though

It keeps showing this error: `"Cannot start Docker Compose application. Reason: exit status 1"`

It worked ok before upgraded

Docker desktop app version: 4.13.1 (90346)

**Comment by slowpokefarm** [comment]
Have the same issue but with stopping multiple containers at once.
`Cannot stop Docker Compose application. Reason: exit status 1`

Stopping containers individually works as expected. 

The issue appeared after latest update.

**Comment by romanvincit** [comment]
Same here on MacOS Monterey. Docker desktop 4.14.0 (91374). Cant start / stop / remove docker compose containers from docker desktop. Started right after the update.

**Comment by ngohuytrieu** [comment]
I've tried to uninstall and then reinstall the desktop app but the issue still persisted.
I also upgraded to the newest version 4.14.0 but the app won't start.

**Comment by diced-k** [comment]
Issue still persists with version 4.14.1 on MacOS Monterey. Hope it will get fixed soon.

**Comment by markkkkas** [comment]
Docker team, please instead updating UI every minor update, fix this issue, still persists in 4.15.

**Comment by trungutt** [comment]
Hi all, could you please try out these builds to see if the problem still persists:

Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/93343/Docker.dmg
Mac Arm (M1): https://desktop-stage.docker.com/mac/main/arm64/93343/Docker.dmg
Windows: https://desktop-stage.docker.com/win/main/amd64/93343/Docker%20Desktop%20Installer.exe

**Comment by georgesofianosgr** [comment]
I just tried the Mac Intel build and it works 👍🏼

**Comment by markkkkas** [comment]
> 

Mac Arm (M1) version works as expected as well. Thanks!

**Comment by ngohuytrieu** [comment]
Another alternative workaround solution is using VS docker extension. You still have full permission there.

**Comment by mehunter3** [comment]
I've had this issue up to the current release. The Mac Intel build linked to above works for me.

**Comment by mat007** [comment]
Closing this issue because a fix has been released in Docker Desktop 4.16. See the [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by rafaelcanical** [comment]
> Hi all, could you please try out these builds to see if the problem still persists:
> 
> Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/93343/Docker.dmg Mac Arm (M1): https://desktop-stage.docker.com/mac/main/arm64/93343/Docker.dmg Windows: https://desktop-stage.docker.com/win/main/amd64/93343/Docker%20Desktop%20Installer.exe

This works for mac intel humm

**Comment by MaksimOstr** [comment]
i also had this problem, but i solved it.
Reason for this problem was the same port for the same images
