### ISSUE TITLE
Docker 4.14.0 does not start up on macOS Ventura 

### ISSUE THREAD

**Issue by yaroslavyaroslav** [docker/for-mac#6572]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3FD62C1D-F73D-4D33-870A-9A073078675A/20221111124257

### Information

  - macOS Version: 13.0.1 (22A400)
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.14.0

It's same as this one #6145, despite that I haven't changed anything cores neither network literally anything. I've looked into `settings.json` and there's correct values for those `vpn` settings. But docker engine just doesn't start totally.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by JS-mark** [comment]
Same problem, but I opened docker through `open / Applications/ Docker.app`

**Comment by JS-mark** [comment]
I hope the authorities will solve the problem in time.

**Comment by yaroslavyaroslav** [comment]
> `open / Applications/ Docker.app`

Tried just yet -- no luck

**Comment by JS-mark** [comment]
> 

Check the progress, finish it first, and use the method above

**Comment by marguera** [comment]
Same problem here, anyone figured it out? I double click it in Applciations and nothing happens.

**Comment by yaroslavyaroslav** [comment]
> Check the progress, finish it first, and use the method above

Not sure that I get what progress you mean

**Comment by alsanars** [comment]
Hello there!

Im not sure if we are facing the same error but I want to share my clues in such case:

I was unable to start docker desktop since I recently upgraded my system to macOS Ventura. At first attempt I decided to upgrade the docker desktop to v4.14.0 but still faced the same issue: docker process seemed to be up and running but did not start at all.

I had a look to `tail -f Library/Containers/com.docker.docker/Data/log/host/Docker.log` while killing the process and restarted again and I got this error:

```
time="2022-11-16T16:40:06Z" level="info" msg="GoBackend: 2022/11/16 17:40:06 notifying bugsnag: 1 error occurred:
	* creating rootNode subnodes: constructing 'BackendServices' in 'rootNode': doing migrations: migrating features.json: saving JSON: open <HOME>/.docker/features.json: permission denied

"
```

Therefore, I removed the entire folder `~/.docker` since I did not have any relevant config at such point and Docker started to work again for me.

Hope it helps!

**Comment by yaroslavyaroslav** [comment]
@alsanars thank you for effort, tried it just yet, but unlucky it didn't helped also.

**Comment by idr0id** [comment]
Same problem here, macOS Ventura, Intel chip.

```
➜ open /Application/Docker.app
➜ cat ~/Library/Containers/com.docker.docker/Data/log/host/com.docker.backend.log
-------------------------------------------------------------------------------->8
-------------------------------------------------------------------------------->8
[2022-11-17T12:52:58.516362000Z][com.docker.backend][F] get system info: exit status 1
[goroutine 1 [running, locked to thread]:
[common/pkg/system.init.0()
[	common/pkg/system/os_info.go:32 +0x29d

➜ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
➜ echo $?
1
➜ cat ~/Library/Containers/com.docker.docker/Data/log/host/com.docker.diagnose.log
-------------------------------------------------------------------------------->8
-------------------------------------------------------------------------------->8
[2022-11-17T12:53:17.314189000Z][com.docker.diagnose][F] get system info: exit status 1
[goroutine 1 [running, locked to thread]:
[common/pkg/system.init.0()
[	common/pkg/system/os_info.go:32 +0x29d
```

**Comment by idr0id** [comment]
I've found a solution. The docker runs `osascript` and fails:

```
➜ osascript -e 'user locale of (get system info)'
osascript: can't open default scripting component.
```

The audio component located within `/Library/Audio/Plug-Ins/Components` ruined the `osascript`.

**Comment by yaroslavyaroslav** [comment]
@idr0id There's actually non for me within that folder 🤷🏻‍♂️

**Comment by AdamInTheOculus** [comment]
@alsanars Thanks! Deleting the `~/.docker` folder worked for me.
- MacBook Pro M1
- macOS Ventura V13.0.1

**Comment by yaroslavyaroslav** [comment]
> @alsanars Thanks! Deleting the `~/.docker` folder worked for me.
> 
> * MacBook Pro M1
> * macOS Ventura V13.0.1

You all just teasing me! Tried just yet — no success.

**Comment by anandthati** [comment]
> @alsanars Thanks! Deleting the `~/.docker` folder worked for me.
> 
> * MacBook Pro M1
> * macOS Ventura V13.0.1

Thanks! this solution worked for me

**Comment by KDworakowski** [comment]
> @alsanars Thanks! Deleting the `~/.docker` folder worked for me.
> 
> * MacBook Pro M1
> * macOS Ventura V13.0.1

Works for me, thanks!

**Comment by lucafulgenzi** [comment]
Why delete the entire `~/.docker` folder?
As the error indicates to us just give docker permissions to access the file located in `~/.docker/features.json`

**Comment by urlimited** [comment]
Hello everyone and Happy New Year
Did you check the permissions on that folder? A quick solution that worked for me and might save your life in the release period is to give permissions for some JSON files in that folder (or for the whole folder):
`sudo chmod -R g=xwr /Users/[your user]/.docker/`

**Comment by safayet08** [comment]
Deleting .docker file worked for me. M1 Mac OS 13.0.1

**Comment by emaalouf** [comment]
Deleting .Docker file worked!

**Comment by deep-adeshraa** [comment]
> @alsanars Thanks! Deleting the `~/.docker` folder worked for me.
> 
> * MacBook Pro M1
> * macOS Ventura V13.0.1

This worked. Thanks 🎉

**Comment by prashant-shahi** [comment]
I got similar issue when upgrading Docker Desktop.

I solved it by updating ownership from root to user for `features.json` file.

```bash
sudo chown $USER ~/.docker/features.json
```

**Comment by nichoguimbaolibot-siteminder** [comment]
> Hello there!
> 
> Im not sure if we are facing the same error but I want to share my clues in such case:
> 
> I was unable to start docker desktop since I recently upgraded my system to macOS Ventura. At first attempt I decided to upgrade the docker desktop to v4.14.0 but still faced the same issue: docker process seemed to be up and running but did not start at all.
> 
> I had a look to `tail -f Library/Containers/com.docker.docker/Data/log/host/Docker.log` while killing the process and restarted again and I got this error:
> 
> ```
> time="2022-11-16T16:40:06Z" level="info" msg="GoBackend: 2022/11/16 17:40:06 notifying bugsnag: 1 error occurred:
> 	* creating rootNode subnodes: constructing 'BackendServices' in 'rootNode': doing migrations: migrating features.json: saving JSON: open <HOME>/.docker/features.json: permission denied
> 
> "
> ```
> 
> Therefore, I removed the entire folder `~/.docker` since I did not have any relevant config at such point and Docker started to work again for me.
> 
> Hope it helps!

It works for me. Thank you 🥳

**Comment by bobbrodie** [comment]
> The audio component located within /Library/Audio/Plug-Ins/Components ruined the osascript.

I know this issue is closed now, but it definitely helped me. I had two components in `/Library/Audio/Plug-Ins/Components`:
* BIAS AMP 2
* BIAS FX 2

I'm not sure why these would break `osascript`, but moving them out fixed the issue.
