### ISSUE TITLE
VirtioFS greyed out

### ISSUE THREAD

**Issue by MichaelVoelkel** [docker/for-mac#6578]
- [x] I have tried with the latest version of Docker Desktop (4.14.0 according to Info.plist of Docker.app)
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I can tick VirtioFS checkbox.

### Actual behavior
I cannot tick VirtioFS checkbox, it's greyed out.

### Info
It worked before but I needed to remove docker entirely and reinstall, now it doesn't.

I'm on macOS 12.3, so I don't see why requirements are not met. My MacBook has Apple Silicon / M1 CPU.

**Comment by MichaelVoelkel** [comment]
Upgrading to Ventura fixed it, but it still seems a bug.

**Comment by saturna** [comment]
You need to upgrade to MacOS >= 12.5 as per this release note:

> Virtualization Framework and VirtioFS are disabled for users running macOS < 12.5

**Comment by MichaelVoelkel** [comment]
Ah, the necessary version was bumped? Because I had been before at 12.3 and _could_ use VirtioFS (not virtualisation framework). Maybe it would be a good idea to mention this also in the UI at the checkbox of VirtioFS.

**Comment by dserodio** [comment]
This is so confusing! In Docker Desktop 4.14.1 there's no option to enable Virtualization Framework, and from the release notes I'd understood that it's always enabled now. But the option to Enable VirtioFS says "This will automatically enable Virtualization framework".

How do I know if I'm using the Virtualization Framework or not?

**Comment by MichaelVoelkel** [comment]
The option is in "General" tab instead of Beta
