### ISSUE TITLE
The NPS survey is very annoying

### ISSUE THREAD

**Issue by pohnean** [docker/for-mac#6580]
I find it very annoying that the NPS survey pops up every time I quit Docker desktop.

I don't think it's necessary to keep doing the survey every single time you quit the app. It should only ask me once every few months.

Please fix this. I often close Docker desktop to free up memory.

**Comment by mutantcornholio** [comment]
It actually pops up when you click on the icon. I feel like it can even pop up several times if docker started considerable time ago.  
I deliberately put zero every time there, and I hope I'm not the only one.
