### ISSUE TITLE
Update progress bar

### ISSUE THREAD

**Issue by gintsmurans** [docker/for-mac#6582]
Hi!

Not sure if this is a correct place, but this is a feature request.

I tend to always upgrade docker desktop to the latest version, but when I press Update button it changes to "Downloading update..." and I have no idea how long it would take. It would be really great to see the progress of the update download, it can be percentage, mb/of mb, or something else. Currently it feels like download is just stuck and I have no idea, should I wait or do something else while its downloading, and usually takes quite some time for download to be ready to install. And few times I have just forgotten about the update only to come back to it a week later and it won't work anymore for some reason and then restart whole docker to be able to download it again. You get the picture. :)

**Comment by DanielYWoo** [comment]
At least, show me the download URL and speed

**Comment by mrleblanc101** [comment]
4.21 has been downloading for multiple days on my Mac...
Would be nice the have a progress bar or anything to be able to unstuck the update progress.
Switching to Sparkle for update would be the best, the current update system has been broken for years.

**Comment by gintsmurans** [comment]
Yeah, yesterday I was downloading latest update, it took an hour and I started wondering, should I restart it, or just wait or what. There didn't seem to be any network activity either.

**Comment by pboling** [comment]
I absolutely HATE docker.

This issue is the ONLY reason.

It can take weeks to download an update, and I have no idea why.  Is it starting over?  Is it just slow?  I have no idea what is going on.

**Comment by mrleblanc101** [comment]
I litteraly just redownload the whole and replace the whole app every time now. You won't lose any image or container, at least I haven't hit something bad yet. This is the only way to update, the auto-updater has been broken for years and they just don't seem to care.

**Comment by pboling** [comment]
I guess that is what I will do.  Since they update the app constantly I will just have to download it and install it on the daily.

This is beyond ridiculous.

**Comment by gintsmurans** [comment]
<img width="361" alt="image" src="https://github.com/docker/for-mac/assets/56369/69f5fbbc-9971-494f-a8f1-8f5bc3f8fcf7">

This seems to be fixed with a progress status bar, at least on the macos.. 🤩
