### ISSUE TITLE
Can't install docker on my mac

### ISSUE THREAD

**Issue by ThierryTD** [docker/for-mac#6584]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ThierryTD** [comment]
Hi to all,
I am trying to install docker on my mac for the first time but I get the following messages. 
Thank you for your help. 

Docker for Mac: version: 17.03.1-ce-rc1-mac3 (1795b358d)
macOS: version 13.0.1 (build: 22A400)
logs: /tmp/94A9154B-D839-4C04-806D-ED9E25678F64/20221118-104237.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/thierno/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/thierno/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/thierno/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/thierno/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/thierno/Library/Containers/com.docker.docker/Data/s51
         vpnkit is not running
         slirp check failed with: (Failure
  "Error connecting socket to 9p endpoint unix:/Users/thierno/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker-cli check failed with: (Failure "docker -v: timeout after 10.00s")
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

**Comment by ackerthehacker2** [comment]
uninstall docker desktop
make sure you remove docker desktop
m -rf ~/Library/Group\ Containers/group.com.docker
rm -rf ~/Library/Containers/com.docker.docker
rm -rf ~/.docker
rm -rf ~/Library/Application\ Support/com.docker.docker
rm -rf  ~/Library/Application\ Support/Docker\ Desktop

Reinstall Docker from the DMG
