### ISSUE TITLE
docker toolbox failure to start

### ISSUE THREAD

**Issue by schowdhury** [docker/for-mac#659]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

    9D1BD916-E561-4B44-BEC6-6D1ED2AFDA0B

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (OSX 10.10.x, OSX 10.11.x)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dsheets** [comment]
It looks like your disk image became corrupted due to a crash or unexpected shutdown of the application, operating system, or machine. Do you still experience this problem? Have you tried to `Reset to factory defaults` from :whale: -> Preferences -> Uninstall/Reset?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
