### ISSUE TITLE
Disable endless popup

### ISSUE THREAD

**Issue by cyberwombat** [docker/for-mac#6596]
Please please please add an option to disable the "how do I like docker" popup. Almost every single time I start I have to deal with this. Since DD uses a whopping amount of memory even w pause that means we have to quit and restart multiple times a day. Ask  me once, ask me every 6 months but not so much please.

**Comment by cyberwombat** [comment]
I deinstalled and reinstalled and it so far seems ok - evidently for months it would try to update but must never have completed as the newly installed version is clearly different so hopefully this is no longer an issue. Thanks for the response and I'll keep an eye on this new version.

**Comment by nicks** [comment]
yay, great to hear!
