### ISSUE TITLE
New Docker for Mac, cannot reach docker.io over IPv6, but `curl` can

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/for-mac#66]
I installed Docker for Mac (stable) following the instructions at https://docs.docker.com/docker-for-mac/ . I chose all of the defaults.

However, `docker run hello-world fails`. `curl` of this same site seems to work fine. I am not behind a proxy, and /etc/hosts does not list docker.

I was previously running Docker Toolbox for Mac, but that should be thoroughly uninstalled.
### Expected behavior

I expect that `docker run hello-world` will connect to docker.io and download the correct image.
### Actual behavior

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
$ 
```

But curl against that same URL works just fine:

```
$ curl -v https://index.docker.io/v1/repositories/library/hello-world/images
*   Trying 52.22.190.106...
* Connected to index.docker.io (52.22.190.106) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.docker.io
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /v1/repositories/library/hello-world/images HTTP/1.1
> Host: index.docker.io
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Tue, 02 Aug 2016 01:26:09 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Vary: Cookie
< X-Docker-Endpoints: registry-1.docker.io
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< 
* Connection #0 to host index.docker.io left intact
[{"checksum": "", "id": "b1f526...
...
```
### Information

Diagnostic ID: 0835336B-EB03-4642-B8C3-3DA14AECB3AE
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Verify that Docker Toolbox is not running. Verify that Oracle VirtualBox is not running.

```
$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
$ env | grep DOCKER
$ 
```
1. Install Docker for Mac per https://docs.docker.com/docker-for-mac/
2. Verify that Docker for Mac looks similar to output given in "Step 2. Check versions of Docker...":

```
$ docker --version
Docker version 1.12.0, build 8eab29e
$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
$ docker-machine --version
docker-machine version 0.8.0, build b85aac1
$ 
```
1. Do some extra checking:

```
$ ls -ld `which docker`
lrwxr-xr-x  1 stefanl  staff  67 Aug  1 18:08 /usr/local/bin/docker -> /Users/stefanl/Library/Group Containers/group.com.docker/bin/docker
```
1. Try some examples under "Step 3. Explore the application and run examples":

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ 
```
1. Try a basic `docker run` example, which fails (see "Actual Behavior" above).

**Comment by stefanlasiewski** [comment]
This same problem happened last night from home (Same laptop).

However, it now works from the office as of 12:30PM PT, and it also works from home as of 10:30AM PT. I have changed nothing on the laptop, other then closing the lid and letting the computer go to sleep. This appears to be some sort of transient issue, but it looks like a network issue closer to the docker.io side.

Closing.

**Comment by wunc** [comment]
Having the same issue. I just installed Docker for Mac (stable) and it reports a network time out when trying to pull hello-world

```
10:57 PM wun@mac[~]$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
```

Like you, I'm not behind a proxy, and curling that URL works fine. This seems like either a genuine bug or a server-side issue, though http://status.docker.com currently reports that everything is up.

**Comment by wunc** [comment]
So, it turns out that this is a DNS issue specifically with docker. See this thread: https://forums.docker.com/t/docker-pull-timeout/15015/16

Docker is only checking the first DNS server in the list, which in my case (and I assume in yours) was my work DNS server. Dragging 8.8.8.8 to the top of the list (in System Preferences > Network > [interface] > DNS) fixed the issue.

Supposedly it is fixed in 2016-07-19 1.12.0-rc4-beta20, but I gave beta21 a try and it still gives me the same problem if the needed DNS server is too far down the list.

**Comment by stefanlasiewski** [comment]
Thanks for that pointer Wunc. Since this affects more then just me, I'm reopening this ticket.

**Comment by herveDarritchon** [comment]
Hello,

I'm behind a corporate proxy. I use CNTLM to get through this proxy.

I can get information from 
`curl https://index.docker.io/v1/repositories/library/elasticsearch/images`

```
[{"checksum": "", "id": "ce9fc27bd09b2d9b0578d8fabedcb973f96cb8fe023712f17703b4807a8dbf9f"},...
]
```

But with docker, it  is not working

`docker pull elasticsearch:latest`

```
Pulling repository docker.io/library/elasticsearch
Error while pulling image: Get https://index.docker.io/v1/repositories/library/elasticsearch/images: http: error connecting to proxy http://localhost:3128: dial tcp [::1]:3128: getsockopt: connection refused
```

**Docker Information:**

Docker for Mac: version: mac-v1.12.0-beta21.1
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/53886A51-1275-4AFE-8E63-255A7A7A6747/20160805-163453.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**docker info command:**

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: YC3I:VDPD:ZNRK:SDDO:OVV5:GMX7:R3ED:3MHY:PF2S:IMGP:IWPZ:ZS36
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2016-08-05T14:35:23.787999834Z
 EventsListeners: 1
Http Proxy: localhost:3128
Https Proxy: localhost:3128
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**scutil Proxy command:**

scutil --proxy
<dictionary> {
  ExceptionsList : <array> {
    0 : *.local
    1 : 169.254/16
    2 : *.itn.ftgroup
  }
  FTPPassive : 1
  HTTPEnable : 1
  HTTPPort : 3128
  HTTPProxy : 127.0.0.1
  HTTPSEnable : 1
  HTTPSPort : 3128
  HTTPSProxy : 127.0.0.1
}

Obviously, if I get a direct connection to internet, not getting through the corporate proxy (from home for example), it works fine ;)

Thanks

**Comment by StormToft** [comment]
👍 seeing the same thing when on corporate vpn. `curl` works fine.

**Comment by stefanlasiewski** [comment]
For an even simpler use case, just try to log in:

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: FrankOz
Password: 
Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: i/o timeout
$
```

**Comment by stefanlasiewski** [comment]
Is anyone else in this ticket using IPv6? I am, and my situation might be a dupe of #9 .

```
$ cat /etc/resolv.conf 
...
nameserver 2620:83:8000:140::3
$
```

**Comment by djs55** [comment]
Could you retry your scenarios with the new beta 25 released today? There have been a number of networking improvements over the last few betas including

- DNS servers are read from the SC database (e.g. `scutils --dns`) rather than from `/etc/resolv.conf` which wasn't always updated by VPNs
- Up to 8 DNS servers are currently supported, previously there was a limit of 2 (requiring people to drag the entries further up the list)
- TCP DNS should work to all servers (earlier there was a bug where the TCP always went to the first server)
- "search domains" are provided to the VM by DHCP (but only when the application starts)
- edits to `/etc/hosts` (and the Windows equivalent) are picked up live and used for name resolution
- the diagnostics upload now includes `curl`, `dig` etc invocations from inside the VM

Note that we don't currently support IPv6 and we ignore those servers.

**Comment by stefanlasiewski** [comment]
I upgraded to "1.12.1, build 23cf638, experimental", but I'm still running into a problem. My laptop is currently on an IPv6 network, and my only DNS resolver is a single IPv6 address (It's an anycast cluster). I can query IPv4 addresses (See below).

Do I need to manually add an IPv4 address to my resolver as a workaround? What's the best way to do that, and can I do it only for the Docker environment so the rest of my system isn't impacted?

```
$ docker --version
Docker version 1.12.1, build 23cf638, experimental
$ docker-compose --version
dodocker-compose version 1.8.0, build f3628c7
$ docker-machine --version
docker-machine version 0.8.1, build 41b3b25
$ docker run -d -p 80:80 --name webserver nginx
Unable to find image 'nginx:latest' locally
Pulling repository docker.io/library/nginx
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/nginx/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: stefanlasiewski
Password:
Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: i/o timeout
$
```

DNS query:
```
$ dig +noall +answer -6 @2620:83:8000:140::3 index.docker.io
index.docker.io.	294	IN	CNAME	elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io. 894 IN	CNAME	us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 54 IN A 52.207.178.113
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 54 IN A 52.73.159.23
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 54 IN A 54.85.12.131
$ curl -v https://index.docker.io/v1/repositories/library/hello-world/images
*   Trying 52.73.159.23...
* Connected to index.docker.io (52.73.159.23) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
...
```

**Comment by StormToft** [comment]
@djs55 Updated to beta 25, but still having the same issue as before. We use IPV4.

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
```

```
$ curl https://index.docker.io/v1/repositories/library/hello-world/images
[{"checksum": "", "id": "b1f526347a08c63813c014adf34170c03b99029bd3e5c80ac9e3f6ed8de3758e"},
... snip ...
```

Diagnostic ID: 269643EB-105D-431F-950B-C8AA43C7AE7B
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.11.6 (Build 15G1004)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

**Comment by dave-tucker** [comment]
> Up to 8 DNS servers are currently supported, previously there was a limit of 2 (requiring people to drag the entries further up the list)

To see which DNS server is reponding there is a tool called `dnstracer` that is available via Homebrew. `brew install dnstracer`

When connected to VPN I see:
```
$ dnstracer redacted.internal.com
Tracing to redacted.internal.com[a] via 172.16.1.5, maximum of 3 retries
172.16.1.5 (172.16.1.5) Got authoritative answer
 $ dnstracer google.com
Tracing to google.com[a] via 172.16.1.5, maximum of 3 retries
172.16.1.5 (172.16.1.5) Refers backwards
```

Hopefully we can correlate the nameserver reported here to one in `scutil --dns` to identify it's position in the list.

**Comment by kinbuty** [comment]
I've had the same problem, I could curl and wget to docker.io but couldn't pull images from the registry. I'm sitting behind a corporate proxy, though. What I've had to do to solve my problem was to refer to this page https://docs.docker.com/engine/admin/systemd/, where it talks about HTTP proxy.

To keep things simple, you have your docker client and docker deamon, which acts like a service. And you might have your proxies set on the client, but the deamon (which is the component that pulls images) must also have proxies set.

**Comment by robtruax** [comment]
I'm having similar issues.  I'm behind a proxy and my company uses a .pac file for configuration, which almost never works for anything besides the browser and email.  Like @herveDarritchon  use a local cntlm for my applications by setting environmental variables.  I get the same errors using docker as he does when I try to point docker at the proxy, both through preferences and environmental variables.  If I leave the proxy settings blank, I time out the same way others do.

Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/A350454E-FDB4-4142-9605-031FCD5A4F42/20160915-141841.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by welchwilmerck** [comment]
Might be helpful.

Version 1.12.1
El Capitan
Nature of corporate proxy unknown

Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp 52.207.178.113:443: getsockopt: connection refused
curl works from xhyve console
Docker -> Preferences -> Advanced -> proxy/no_proxy values correct, but grayed out.

Provision a guest account to self. Drop off corporate network and switch to guest network.
Docker login works.

Switch back to corporate network.
Docker login fails.
Docker -> Preferences -> Advanced -> proxy/no_proxy empty, but now editable.
Set http/s proxy to correct value. Leave no_proxy blank.
Apply & Restart
Docker login now works in corporate network.

**Comment by stefanlasiewski** [comment]
This is still a problem with the latest Beta, `Docker version 1.12.1, build 6f9534c`.

My particular problem is IPv6-related, so I'll modify the subject for this ticket. Some of our workstation LANs support IPv6, and the IPv6 nameservers are listed first for the resolver.

As a workaround, I manually move the IPv4 DNS server to be at the top of the list, but I don't like this as a workaround as it effects all services on my workstation, and I feel that Docker should support IPv6 natively. Also, since use this workstation on various networks with their own DNS servers, I need to implement this workaround for each network, and sometimes the Mac will overwrite my changes. And we'd like to test IPv6 within containers, so I'd prefer to not use some sort of IPv4 workaround.

```
$ docker --version
Docker version 1.12.1, build 6f9534c, experimental
$ docker pull centos
Using default tag: latest
Pulling repository docker.io/library/centos
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/centos/images. You may want to check your internet connection or if you are behind a proxy.
$ syslog -k Sender Docker
Sep 26 09:57:07 username Docker[692] <Notice>: SC database lists DNS servers: 2620:100:100:100::3
Sep 26 09:57:07 username Docker[692] <Notice>: SC database lists search domains: dhcp6.example.org
Sep 26 09:57:07 40 Docker[692] <Notice>: SC database lists DNS servers: 2620:100:100:100::3
Sep 26 09:57:07 40 Docker[692] <Notice>: SC database lists search domains: dhcp6.example.org
Sep 26 09:57:11 40 Docker[690] <Error>: Lwt.async failure (Failure nth): Raised at file "pervasives.ml", line 32, characters 22-33
	Called from file "lib/dns_forward.ml", line 38, characters 41-77
	Called from file "lib/dns_forward.ml", line 102, characters 16-57
	Called from file "src/core/lwt.ml", line 795, characters 20-24
--- last message repeated 47 times ---
$ curl https://index.docker.io/library/centos ; echo $?
0
$
```

**Comment by longkai** [comment]
It's still a problem in current latest stable **Version 1.13.0 (15072)**. It obtains system proxy setting in GUI preferences.

```
Http Proxy: 127.0.0.1:8123
Https Proxy: 127.0.0.1:8123
```

But when pulling images, it complaint about,

```sh
> docker pull ubuntu
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: http: error connecting to proxy http://127.0.0.1:8123: dial tcp 127.0.0.1:8123: getsockopt: connection refused
```

However, `curl` is perfectly fine.

**Comment by samoht** [comment]
@longkai I suspect that 127.0.01 (your macOS host) is unknown to the Linux VM (where docker engine runs). Would you be able to run the proxy in a container or use your public IP address instead of 127.0.0.1?

Related to https://github.com/docker/for-mac/issues/736

**Comment by samoht** [comment]
@longkai would you mind opening a new issue with a diagnostic ID? I am going to close this ticket as  IPv6 should not break Docker for Mac anymore (see #932).

**Comment by stefanlasiewski** [comment]
Seems to work for me now using:

    Version 1.13.0 (15072)
    Channel: Stable
