### ISSUE TITLE
Stable channel v1.12.1 (build: 12133) not listed in release notes

### ISSUE THREAD

**Issue by nate-opti** [docker/for-mac#660]
I'm on stable channel Docker for Mac, which updated today to a new version. But, I can't find this new version listed anywhere on the internet. 

Info from "About Docker"

```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```

Info from `docker --version`:

`Docker version 1.12.1, build 6f9534c`

No stable 1.12.1 releases listed in the notes: https://docs.docker.com/docker-for-mac/release-notes/

How can I check what has been released in this version, and verify the (SHA246 looks like checksums) that my update completed successfully? Thanks!

**Comment by djs55** [comment]
Sorry the docs were updated slightly after the binaries but they are now live:

- https://docs.docker.com/docker-for-mac/release-notes/#/docker-for-mac-1-12-1-2016-09-16-stable
- https://docs.docker.com/docker-for-windows/release-notes/#/docker-for-windows-1-12-1-2016-09-16-stable

For reference I have also
```
$ docker --version
Docker version 1.12.1, build 6f9534c
```
and in "About Docker"
```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```
It looks to me like your system has updated properly.

**Comment by nate-opti** [comment]
Thanks, appreciate it!
