### ISSUE TITLE
Docker.app stopped working.  Reinstalls not fixing the issue

### ISSUE THREAD

**Issue by lucianthorr** [docker/for-mac#6608]
Could be redundant with #6605 but I wanted to add the Diagnostic data

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features. (Can't enable/disable since it won't start)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  f6bf7391-5b66-445d-be85-b6c8cda8c6f9/20221202125630

### Expected behavior

Docker runs normally.

### Actual behavior

Docker starts and becomes "Not Responding" in the Activity Monitor.  No errors, doesn't even get to the point of seeing the little whale icon in the upper toolbar.

### Information

  - macOS Version: Monterey 12.6 (21G115)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.12 - 4.14.1. ( I believe I was on 4.14 before the error occurred unless it autoupdated to 4.15 and that started the issue)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

[PASS] DD0027: is there available disk space on the host?
[FAIL] DD0028: is there available VM disk space? open /var/root/Library/Group Containers/group.com.docker/settings.json: no such file or directory
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[FAIL] DD0017: can a VM be started? vm has not started: failed to open kmsg.log: open /var/root/Library/Containers/com.docker.docker/Data/log/vm/kmsg.log: no such file or directory
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: failed to open kmsg.log: open /var/root/Library/Containers/com.docker.docker/Data/log/vm/kmsg.log: no such file or directory
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": dial unix diagnosticd.sock: connect: no such file or directory
[FAIL] DD0015: are the binary symlinks installed? looking for /usr/local/bin/docker-index: lstat /usr/local/bin/docker-index: no such file or directory
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[PASS] DD0013: is the $PATH ok?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[FAIL] DD0003: is the Docker CLI working? exit status 1
[FAIL] DD0014: are the backend processes running? reading settings.json: open /var/root/Library/Group Containers/group.com.docker/settings.json: no such file or directory
[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": dial unix backend.sock: connect: no such file or directory

### Notes:

I have since uninstalled and reinstalled every Docker version from 4.12 to 4.15.  I'm getting the same behavior with all versions.  I've tried `rm -rf`'ing the the `~/.docker` folder and docker folders in `~/Library/Containers/ `and `~/Library/Group Containers`.  This also has not made any difference.

I've also posted the Docker logs that started occurring immediately when Docker started failing [here](https://github.com/docker/for-mac/issues/6605#issuecomment-1334614619)

**Comment by lucianthorr** [comment]
I was able to get Docker running by downgrading to 4.8.0 and then incrementing up to 4.11.1.  At 4.12.0, Docker does not work on my computer.  I'm fairly certain that was running Docker with auto-update enabled so I don't know what could have happened to make it so incompatible with my system.

I'm happy to do whatever you need to help debug the issue.

**Comment by k0ste** [comment]
@lucianthorr thanks. On my Air M2 win MacOS 13.2 your suggestion with 4.8.0
But seems some go-backend isn't working on Ventura...

**Comment by ekan-egonmwan** [comment]
Downgrading to 4.11.1 is the only thing that works. 4.12.0 and above does not work on my intel mac
