### ISSUE TITLE
Docker Desktop disk image numbers (size and used space) are incorrect

### ISSUE THREAD

**Issue by DaRosenberg** [docker/for-mac#6616]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `11D636E8-67DA-46AF-938B-942EB1F9D7B7/20221205101857`

### Expected behavior

The disk image size numbers under the Resources tab should match the actual resource use.

### Actual behavior

Numbers are wrong in several ways:

<img width="1860" alt="image" src="https://user-images.githubusercontent.com/3889090/205611451-1a197aab-552c-4b1e-8cf0-b561fa955f67.png">

### Information

macOS Ventura 13.0.1, Intel chip.

I'm using version 4.14.1, but the problem has been there for at least a few versions back, since I started paying attention to resource configuration and usage — may have been there forever, I don't know.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
danielrosenberg@Daniels-Mac-Pro data % /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

1. Configure disk image size to 64 GB
2. Create one or more containers that use more than 0 bytes of disk space
3. Check actual available and used size in a container with `df -H`
4. Check actual `Docker.raw` file size using Finder

**Comment by trungutt** [comment]
Hi @DaRosenberg we try to revamp it with the new 4.15 version. Please take a look at it

**Comment by DaRosenberg** [comment]
@trungutt Issue of 64 GB vs. 68 GB is still the same.

Was wondering if it was a GB vs. GiB issue, but can't get the numbers to line up for that either...

The issue of 0 used space has been fixed, and is now correctly reported in the status bar instead. 👍🏻
