### ISSUE TITLE
Docker Desktop resources/advanced tab content is truncated

### ISSUE THREAD

**Issue by DaRosenberg** [docker/for-mac#6617]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: `11D636E8-67DA-46AF-938B-942EB1F9D7B7/20221205101857`

### Expected behavior

I should be able to read the full disk image location.

Suggestion:

- Firstly let the UI controls on this tab span the full available horizontal size of the window
- Secondly, allow the disk image location path label to wrap, like the UI on the "beta features" tab
- Thirdly, could also add a tooltip on hover that shows the full path (but wrapping is better)

### Actual behavior

Disk image location is truncated, with no way to see the full path (except triple-click on path to select all, copy and paste it somewhere else.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/3889090/205615666-5d1ac092-6861-492e-8b6a-6b2035cdf383.png">

### Information

macOS Ventura 13.0.1, Intel chip.
Docker version 4.14.1.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
danielrosenberg@Daniels-Mac-Pro data % /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

N/A

**Comment by trungutt** [comment]
Hi @DaRosenberg we try to revamp it with the new 4.15 version. Please take a look at it

**Comment by DaRosenberg** [comment]
@trungutt This issue still applies the same in 4.15.

**Comment by gercekarmagan** [comment]
@DaRosenberg maybe not ideal but you should be able to horizontally scroll to see the full disk image location and select and copy if needed too.

**Comment by gercekarmagan** [comment]
@DaRosenberg that's interesting, just recorded something short can you have a look? 

https://user-images.githubusercontent.com/52465035/207045536-91d5dcec-34c2-473c-877e-06b63b2f0bf7.mov

I'm using an Apple mouse and also tried using the trackpad, both worked for me. @trungutt could there be something else that's preventing it?

**Comment by DaRosenberg** [comment]
@gercekarmagan That does indeed work now on 4.15. 👍 

(Still would be preferable to not truncate when there's ample horizontal space just going to waste, though...)
