### ISSUE TITLE
Docker application fails to install/start after upgrade ( MacOS )

### ISSUE THREAD

**Issue by RafPe** [docker/for-mac#662]
### Expected behavior

Docker application starts 
### Actual behavior

Docker application requests credentials to install networking components after which it bails out with fatal error 
### Information
- Diagnostic ID : 9725CA14-1861-4DC4-8285-DFC2B9B33462
- OSX 10.11.6 El Capitain
### Steps to reproduce the behavior
1. Updated Docker App to latest version 
2. Provided password to install required components 
3. Installation bails out with msg 
     `
     Communication with networking components failed.
   `
4. Application fails to start 
### Extra info

Application fails to upload diagnostics 

```
Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/9725CA14-1861-4DC4-8285-DFC2B9B33462/20160917-132649.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/RafPe/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/RafPe/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/RafPe/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```
### Possibly related issues
#658

**Comment by samoht** [comment]
@djs55 have you already seen this?

```
time="2016-07-13T07:23:23.560995412Z" level=fatal msg="Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: Fatal error: exception Unix.Unix_error(Unix.ENFILE, \"open\", \"/var/log/service-port-opener.log\")\n (exit status 2)"
```

the diagnostic log shows all sort of AUFS corruption and incomplete vmnetd launchd registration, so that's probably not the main issue but that looks suspicious to me.

**Comment by djs55** [comment]
@samoht I've not seen that before. I believe this is from inside the VM and `ENFILE` means "The system limit on the total number of open files has been reached" which sounds like bad news. I wonder which process is using all the fds?

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in 9725CA14-1861-4DC4-8285-DFC2B9B33462/20160917-130535.

The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

May be related to docker/for-mac#61
