### ISSUE TITLE
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

### ISSUE THREAD

**Issue by cursedgrape** [docker/for-mac#6623]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics 
  - Diagnostics ID:

### Expected behavior

Should work.

### Actual behavior

Probably an issue with docker hub or the new docker desktop update `4.15.0`, or both. Following the upgrade, docker stopped working properly on macOS `13.0.1`. At first, it started refusing to login. Multiple browser tabs are automatically opened for authentication, then I get a failure message in browser and in docker desktop.

First I get this after clicking the login button and press open docker:

[![proceed?][1]][1]

Followed by 'Login rejected':

[![fail][2]][2]

And this is not it, I'm also unable to run anything that requires pulling images from docker hub. Examples ...

    % docker run -d -p 80:80 docker/getting-started
    Unable to find image 'docker/getting-started:latest' locally
    docker: Error response from daemon: Head "https://registry-1.docker.io/v2/docker/getting-started/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Adocker%2Fgetting-started%3Apull&service=registry.docker.io": EOF.
    See 'docker run --help'.

---

    % docker pull hello-world                      
    Using default tag: latest
    Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

---

And based on suggestions [here](https://stackoverflow.com/questions/49387263/docker-error-response-from-daemon-get-https-registry-1-docker-io-v2-servic) I tried:

    % </dev/tcp/registry-1.docker.io/443 && echo Works || echo Problem
    curl https://registry-1.docker.io/v2/ && echo Works || echo Problem
    zsh: no such file or directory: /dev/tcp/registry-1.docker.io/443
    Problem
    {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
    Works

and 

    % docker logout
    Removing login credentials for https://index.docker.io/v1/
    % docker login 
    Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
    Username: ***@***.***
    Password: *********
    Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

In addition to the above, I tried restarting docker desktop followed by complete reinstallation of both docker and docker desktop, and I still get the same results.

  [1]: https://i.stack.imgur.com/05UOg.png
  [2]: https://i.stack.imgur.com/VqPv8.png

### Information

  - macOS Version: 13.0.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.15.0 (93002)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

    [PASS] DD0027: is there available disk space on the host?
    [PASS] DD0028: is there available VM disk space?
    [PASS] DD0018: does the host support virtualization?
    [PASS] DD0001: is the application running?
    [PASS] DD0017: can a VM be started?
    [PASS] DD0016: is the LinuxKit VM running?
    [PASS] DD0011: are the LinuxKit services running?
    [PASS] DD0004: is the Docker engine running?
    [PASS] DD0015: are the binary symlinks installed?
    [PASS] DD0031: does the Docker API work?
    [PASS] DD0013: is the $PATH ok?
    [PASS] DD0003: is the Docker CLI working?
    [PASS] DD0014: are the backend processes running?
    [PASS] DD0007: is the backend responding?
    [PASS] DD0008: is the native API responding?
    [PASS] DD0009: is the vpnkit API responding?
    [PASS] DD0010: is the Docker API proxy responding?
    [PASS] DD0012: is the VM networking working?
    [SKIP] DD0030: is the image access management authorized?
    [FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
    [PASS] DD0033: does the host have Internet access?
    [PASS] DD0018: does the host support virtualization?
    [PASS] DD0001: is the application running?
    [PASS] DD0017: can a VM be started?
    [PASS] DD0016: is the LinuxKit VM running?
    [PASS] DD0011: are the LinuxKit services running?
    [PASS] DD0004: is the Docker engine running?
    [PASS] DD0015: are the binary symlinks installed?
    [PASS] DD0031: does the Docker API work?
    [PASS] DD0032: do Docker networks overlap with host IPs?
    
    Please investigate the following 1 issue:
    
    1 : The test: is the com.docker.vmnetd process responding?
        Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
    
    The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by bogordesaincom** [comment]
same issue

**Comment by ubaidullahs** [comment]
same issue
