### ISSUE TITLE
Double click header bar "zoom" does nothing

### ISSUE THREAD

**Issue by MattHolmes123** [docker/for-mac#6626]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Double clicking Docker Desktop title bar should maximise the window
### Actual behavior
It does nothing
### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
What version are you on? I think this might have been fixed in DD 4.15.

**Comment by MattHolmes123** [comment]
Thats great!
I was on 4.14.1 (91661).
Can confirm 4.15.0 (93002) fixes this problem.
Thanks.
