### ISSUE TITLE
Kubernetes operations sabotaged by Docker.app 4.14.1 (91661) on macOS 12.6.2

### ISSUE THREAD

**Issue by rdump** [docker/for-mac#6636]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: NA

### Expected behavior
Existing `/usr/local/bin/kubectl` installations are not overwritten.

### Actual behavior
I recently had kubectl version mismatch reported (and had operations break) when operating on hundreds of prod clusters. I tracked it down to Docker.app suddenly deciding to willy-nilly replace my brew-managed specifically-compatible link of /usr/local/bin/kubectl... with a symlink to a different and incompatible kubectl within the Docker.app.

The proper setup is:
	```lrwxr-xr-x  1 foo  admin  50 Dec 15 07:27 /usr/local/bin/kubectl@ -> ../Cellar/kubernetes-cli@1.20.4/1.20.4/bin/kubectl```
Docker.app's breakage is:
	```lrwxr-xr-x  1 root  admin  55 Dec 14 14:55 /usr/local/bin/kubectl@ -> /Applications/Docker.app/Contents/Resources/bin/kubectl```

Additional note

This misbehavior occurs even when the checkbox for `Enable Kubernetes` in Docker.app preferences is NOT selected/checked.

### Information
This Docker.app misbehavior is a regression of https://github.com/docker/for-mac/issues/2890 .

The regression cropped up with Docker.app version 4.14.1.

Docker.app 4.14.1 is running here under macOS 12.6.2 on Intel architecture.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
NA, cannot run Docker.app without breaking system intended kubectl

### Steps to reproduce the behavior
1) launch Docker.app

Every time Docker.app is launched, our non-Docker-managed kubectl link is replaced by Docker.app's link.

**Comment by voelzmo** [comment]
Wow, thanks for the thorough write-up, @rdump! I found myself confused why `kubectl` commands suddenly produced different results and my shell completion broke and ended up here. Did you come up with a workaround? I don't want to start managing my `kubectl` outside of `brew` and unfortunately have to use `docker` in my daily work as well ;(

**Comment by rdump** [comment]
> Did you come up with a workaround? 
> The best I could come up with is ensuring that `brew`'s `kubectl` appears on the path before the one managed by docker does

This is fixed as of 1 March 2023 in Docker.app 4.17. Report of the bug per support contract apparently resulted in creating and using a different issue than this public one.

If you can't upgrade:

I like the path workaround better.

But what I found worked well enough after every Docker.app launch (replacement of link happened at launch) was brew unlink, then relink.  Brew unlinking would block on non-matching /usr/local/bin/kubectl, but removing that would let it proceed.

1) Check that /usr/local/bin/kubectl is a Docker.app link instead of intended brew link, if so
2) rm /usr/local/bin/kubectl  # to clear decks for next commands
3) brew unlink kubernetes-cli@1.21.3  # change version to match your installed version
4) brew link kubernetes-cli@1.21.3  # change version to match your intended installed version

**Comment by rdump** [comment]
Same issues as https://github.com/docker/for-mac/issues/6328

Release nodes from 4.17:

> Improved kubectl symlink logic to respect existing binaries in /usr/local/bin. Fixes [docker/for-mac#6328].
