### ISSUE TITLE
Containers hang on file i/o on a host volume that's an NFS share

### ISSUE THREAD

**Issue by dolapo** [docker/for-mac#664]
### Expected behavior

My host computer has mounted an NFS share on a remote server. I create two containers that have data volumes on that share. After a few minutes file operations fail and creating new data volumes hang but should not.
### Actual behavior

After some time file operations fail and creating new data volumes hang. I typically have to restart containers. Creating new containers with data volumes for that mount, e.g. with `docker run -ti -v /mnt/bufo/Config/:/config ubuntu:14.04 /bin/bash` hang. ctrl-c etc does not work.
### Information
- Diagnostic ID: 9188CAD0-66B3-4E5E-9016-F2E54ABB854F
- OSX 10.12 (Was also happening on OSX 10.11.x before I updated)
### Steps to reproduce the behavior

I'm still trying to find a cleaner repro but it's essentially something like:
1. Set up an NFS mount on the host. I'm using an automount and the mount looks like `map auto_bufo on /mnt/bufo (autofs, nosuid, automounted, nobrowse)
   bufo.local:/volume1/bufo on /mnt/bufo (nfs, nodev, nosuid, automounted, noowners, nobrowse)`
2. Create two or more containers with data volumes. e.g. container 1 -v /mnt/bufo/downloads:/downloads and container 2 -v /mnt/bufo/downloads:/downloads
3. Container 1 in my case is a container that does periodic file scans within /downloads
4. Soon after, attempting to exec ls /downloads on either container hangs
5. As does attempting to create a new container with `run -ti -v /mnt/bufo/Config/:/config ubuntu:14.04 /bin/bash`
6. On the host, ls /mnt/bufo/ works fine

**Comment by dolapo** [comment]
```
Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.12 (build: 16A323)
logs: /tmp/9188CAD0-66B3-4E5E-9016-F2E54ABB854F/20160917-162754.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed' in 9188CAD0-66B3-4E5E-9016-F2E54ABB854F/20161012-231453.

An Assertion failure relating to a Docker component was found in the system logs.

May be related to docker/hyperkit#50

The following log matches:
```
Oct  8 18:57:46 anaxyrus Docker[com.docker.slirp][50418] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ECONNREFUSED, "pipe_connect", "")
Oct  8 18:57:46 anaxyrus Docker[com.docker.slirp][50418] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ECONNREFUSED, "pipe_connect", "")
Oct  8 18:57:46 anaxyrus Docker[com.docker.slirp][50418] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ECONNREFUSED, "pipe_connect", "")
Oct  8 18:57:46 anaxyrus Docker[com.docker.driver.amd64-linux][50420] <Notice>: Assertion failed: (s->local_shutdown != VIRTIO_VSOCK_FLAG_SHUTDOWN_ALL), function shutdown_local_sock, file src/pci_virtio_sock.c, line 869.
Oct  8 18:57:46 anaxyrus Docker[com.docker.driver.amd64-linux][50420] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=735284a6-271f-48ee-a04d-73e90303b296,path=/Users/dolapo/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/dolapo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Oct  8 18:57:46 anaxyrus Docker[com.docker.driver.amd64-linux][50420] <Notice>: Interface will have uuid 735284a6-271f-48ee-a04d-73e90303b296
```

**Comment by ijc25** [comment]
@dsheets added this to an internal issue some time ago but the labels were not updated, doing so now.
