### ISSUE TITLE
Large files (2+ GB) on bind mount truncated with VirtioFS 

### ISSUE THREAD

**Issue by ajw725** [docker/for-mac#6643]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E2E7AB5D-ACDA-4685-851F-9C08E43F884E/20221221225826

### Expected behavior
I should be able to read the full contents or seek to any point of a file over 2 GB on a bind mount.

### Actual behavior
When I set up a bind mount containing a file > 2 GB, I can only read from / seek to points in roughly the first 2 GB of the file.

On the host (my laptop), viewing the first 10 bytes of a file - which appears to be 2.9G in total - after the 1 GB and then the 2.5 GB mark:
```
ajw725::~/Documents/virtio_issues % ls -l
total 6180864
-rwxr-x---  1 ajw725  staff  3157608551 Dec 21 16:22 hg19.fa
ajw725::~/Documents/virtio_issues % tail -c +1073741824 hg19.fa | head -c 10
TCTGCTTCTA
ajw725::~/Documents/virtio_issues % tail -c +2684354560 hg19.fa | head -c 10
ccggcctcag
```
Then setting up a container with VirtioFS enabled and doing the same thing:
```
ajw725::~/Documents/virtio_issues % docker run --rm -u root -it -v /Users/ajw725/Documents/virtio_issues:/mnt/virtio_issues:ro debian:stable-slim
root@2304f8fe3aa0:/# cd /mnt/virtio_issues
root@2304f8fe3aa0:/mnt/virtio_issues# ls -l
total 3090432
-rwxr-x--- 1 root root 3157608551 Dec 21 23:22 hg19.fa
root@2304f8fe3aa0:/mnt/virtio_issues# tail -c +1073741824 hg19.fa | head -c 10
TCTGCTTCTA
root@2304f8fe3aa0:/mnt/virtio_issues# tail -c +2684354560 hg19.fa | head -c 10
tail: /mnt/virtio_issues/hg19.fa: cannot seek to relative offset 2684354559
```
Seeking to 2.5 GB doesn't work, even though it worked fine on the host, but seeking to 1 GB works just fine, so it's not an issue with file permissions. Simply reading from the end of the file doesn't work either:
```
root@2304f8fe3aa0:/mnt/virtio_issues# tail -c 10 hg19.fa
tail: hg19.fa: cannot seek to offset 3157608541
```

It's like access to the file has just been cut off in the middle somewhere. On a couple of occasions, this cutoff point has been exactly 2 GiB (i.e. `2147483647` works, `2147483648` doesn't work), but not every time. I've tried this with multiple different files, but the one in this example was the hg19 human genome reference sequence. It's basically just a large text file.

With gRPC FUSE enabled instead of VirtioFS, seeking/reading the file inside the container works the same as it does on the host.

### Information

  - macOS Version: 12.6.1 (Monterey)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.15.0 (93002)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

### Steps to reproduce the behavior

See above for details, but to summarize:

  1. Enable VirtioFS file sharing
  2. Run a container from any base image - I've tried with multiple, but `debian:stable-slim` is an easy test case - with a bind mount containing a file larger than 2 GB (at least 2.5-3 to be sure of reproducing)
  3. Inside that container, try to read from / seek in the file to somewhere around the 2.5 or 3 GB mark.

**Comment by tjameswilliams** [comment]
Same issue happens when attempting to use AWS CLI to download a file that's synced with the Host OS's filesystem with VirtioFS if that file is larger than 2GB. This is definitely an issue for workloads where you need to sync a database!

**Comment by adestefani** [comment]
Same issue trying restoring a mysql database with a 2.5GB size table, you get a "1114 (HY000) table is full" error.
I had to switch to gRPC Fuse to load database dump.
- macOS 12.6.3 (Monterey) on Intel chip
- Docker Desktop Version: 4.16.2

**Comment by ajw725** [comment]
FWIW, just a quick follow up: i was able to test this out on a different mac with an apple chip and similar - but slightly newer - software. macOS 12.6.3, M1 max chip, docker desktop 4.16.2 (95914). this one doesn't seem to suffer from the same file truncation problem when using VirtioFS (which is good, because gRPC FUSE is really slow on it).
