### ISSUE TITLE
Potential memory leak in `docker-index`

### ISSUE THREAD

**Issue by sgammon** [docker/for-mac#6652]
- [x] I have tried with the latest version of Docker Desktop
  - [-] I have tried disabling enabled experimental features
  - [-] I have uploaded Diagnostics
  - Diagnostics ID: N/A

### Expected behavior
Docker should not allocate a ton of memory for unclear reasons

### Actual behavior
Docker allocates more than double the available memory on the machine for unclear reasons

### Information
- macOS Version: `Ventura 13.1`
- Intel chip or Apple chip: Apple M1 Pro
- Docker Desktop Version: `4.15.0 (93002)`

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
➜  ~ /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: is the com.docker.vmnetd process responding?
    Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory

The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.
```

### Steps to reproduce the behavior

I'm not sure where this came from, but I'm reporting it in case an engineer with Docker recognizes a source for a memory leak and connects it with this:

<img width="761" alt="Screenshot 2022-12-29 at 7 11 38 PM" src="https://user-images.githubusercontent.com/171897/210030941-654624e7-487a-4977-9aed-f0ffffc0ae34.png">

**Comment by hraban** [comment]
I'm having the exact same problem on a macbook pro 2015 x86-64 (MacBookPro11,5) mac os 12.6.2, Docker 4.15.0 (93002) engine v 20.10.21.x. It's hard to pin down when or why exactly this happens but I'm open to suggestions for debugging.

**Comment by cdupuis** [comment]
@sgammon  and @hraban, thanks for taking the time to file this bug report. 

`docker-index` is a process that indexes images that either pulled or built locally and produces SBOMs. We are aware that under certain conditions (eg large images), `docker-index` will run excessively long while using a lot of memory. I'm really sorry you're affected by that issue.

By any chance, could you share how big the images are you are building? Is there a way for you to share a Dockerfile that when being built, show this issues?

To turn off background indexing and hopefully mitigate the issue, please disable Enable background SBOM indexing in the DD preferences.

![image](https://user-images.githubusercontent.com/206707/211591970-cd05a7f3-e45c-42f0-95b1-136ca9b29e0f.png)

**Comment by sgammon** [comment]
@cdupuis thank you for the response. in my case, the process allocates more memory than the computer physically has available. perhaps a reasonable limit should be applied?

**Comment by hraban** [comment]
Thanks @cdupuis . Here's the image I'm building: https://github.com/hraban/git-hly/tree/build/nix-flake (commit locked link: "https://github.com/hraban/git-hly/tree/3cc9f2d6ba047d226c10b052204978dddcc861ff").

Doing a `docker build -t asdf .` in that directory, on mac, creates a run-away `docker-index` process for me.

**Comment by hraban** [comment]
P.S.: I disabled the option as recommended, and it works well. Thanks.

**Comment by hraban** [comment]
You're right, quitting and restarting did the trick.

I ran that command but it doesn't say much, beyond:

```
INFO Requesting image asdf
INFO Copied image
INFO Indexing ⠋
```

which keeps consuming resources until my OS runs out of memory.

**Comment by hraban** [comment]
I haven't seen this problem anymore, so I can't help with further debugging. Consider it stale from my end.

**Comment by sgammon** [comment]
same, but i switched to a laptop with 96gb so i'm not sure i would notice if it was leaking

**Comment by gburlet** [comment]
I experience this issue on intel mac 32GB of RAM. docker-index starts after building an image, grows, keeps growing, and explodes past physical RAM cap and then hard reboots my computer. I've disabled `Enable background SBOM Indexing` and `Access experimental features` as suggested but the mem leak still happens. The only way for me to stop it is I have about 1min when I start losing my terminal and OS GUI to choppiness to run the kill command on docker-index to save my system. Just a heads up, still very much an issue.
