### ISSUE TITLE
All Containers are unreachable daily

### ISSUE THREAD

**Issue by macstainless** [docker/for-mac#6654]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 75C47FAE-FA34-4D49-8E5F-EB781AB630B0/20221230140701

### Expected behavior

Services running within containers can be reached.

### Actual behavior

No containers can be reached locally or via outside web addresses. Containers are running and no errors display in the logs. The only way to resolve this is to restart Docker desktop, which "fixes" it for about 24-hours.

### Information

  - macOS Version: 13.1 (Ventura)
  - Intel chip or Apple chip: Intel Core i5
  - Docker Desktop Version: 4.15.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-12-30T14:08:19.463594000Z][com.docker.diagnose][I] ipc.NewClient: f4049443-diagnose-network -> diagnosticd.sock diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xd9
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x100d5bbc0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x100d5bbc0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x100d5bbc0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x100d5bbc0, 0xc000595720)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100d5bd40, 0xc000595720)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x10070dba0?, 0xc00059f888)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x100d5bd40, 0x0?, {0xc00059fb18, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000b8010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[	common/cmd/com.docker.diagnose/main.go:99 +0x2a7
[2022-12-30T14:08:19.464354000Z][com.docker.diagnose][I] (8da707ad) f4049443-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.86.37","192.168.86.35"]}
[2022-12-30T14:08:19.978539000Z][com.docker.diagnose][W] (8da707ad) f4049443-diagnose-network C<-S 0b771e5d-diagnosticsd POST /check-network-connectivity (514.348745ms): failed to ping host: exit status 1

[SKIP] DD0030: is the image access management authorized?
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[WARN] DD0017: can a VM be started? vm has not started: vm has not started
[WARN] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
segment 2022/12/30 09:08:20 ERROR: sending request - Post "https://api.segment.io/v1/batch": remote error: tls: internal error
segment 2022/12/30 09:08:20 ERROR: 1 messages dropped because they failed to be sent and the client was closed

Please note the following 2 warnings:

1 : The check: can a VM be started?
    Produced the following warning: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

2 : The check: is the LinuxKit VM running?
    Produced the following warning: vm is not running: vm has not started

The Docker engine runs inside a Linux VM. Therefore the VM must be running.

Please investigate the following 2 issues:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

2 : The test: is the com.docker.vmnetd process responding?
    Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory

The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.

### Steps to reproduce the behavior

  1. Happens on its own overnight. I awake to alerts that the services running within the continers are no longer reachable.
  2. The only way I can resolve this is to restart the Docker engine completely.

**Comment by christophermclellan** [comment]
Hey @macstainless, thanks for submitting this issue. We'll have a look at this in our sprint starting Tuesday 17-Jan and I'm hoping that we'll be able to get back to you with a resolution shortly thereafter.

**Comment by macstainless** [comment]
Thanks @christophermclellan! Please know there’s an entire thread about this in your forums: [Here’s a link. ](https://forums.docker.com/t/docker-container-loses-network-connectivity-intermittently/120560/5)

**Comment by rbouma** [comment]
We have the same problem when restarting docker with version: **4.16.0**
`
Error response from daemon: Ports are not available: exposing port UDP 127.0.0.1:53 -> 0.0.0.0:0: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
`

**in the docs stated the following:** 
If the privileged helper process is not running, Docker Desktop prompts the user for authorization to run it under [launchd](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html).

---

**We fixed this temporary manually for now via:**

check if the vmnetd launch service exists in `/Library/PrivilegedHelperTools/com.docker.vmnetd` otherwise copy them over with:
```bash
sudo cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools/com.docker.vmnetd
```

check if the launch deamon exists in `/Library/LaunchDaemons/com.docker.vmnetd.plist` otherwise create it with:
```bash
sudo tee -a /Library/LaunchDaemons/com.docker.vmnetd.plist > /dev/null <<EOT
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
                <key>Label</key>
                <string>com.docker.vmnetd</string>
                <key>Program</key>
                <string>/Library/PrivilegedHelperTools/com.docker.vmnetd</string>
                <key>ProgramArguments</key>
                <array>
                        <string>/Library/PrivilegedHelperTools/com.docker.vmnetd</string>
                </array>
                <key>RunAtLoad</key>
                <true/>
                <key>Sockets</key>
                <dict>
                        <key>Listener</key>
                        <dict>
                                <key>SockPathMode</key>
                                <integer>438</integer>
                                <key>SockPathName</key>
                                <string>/var/run/com.docker.vmnetd.sock</string>
                        </dict>
                </dict>
                <key>Version</key>
                <string>64</string>
        </dict>
        </plist>
EOT
```

Last step is stop the vmnetd service if it is already running, unload, load the service and then start the vmnetd service again
```bash
sudo launchctl stop com.docker.vmnetd
sudo launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo launchctl start com.docker.vmnetd
```

this fixed our issue. but it will be better if docker is prompting for installing the deamon to use privileged ports such as 53

**Comment by Code-Slave** [comment]
Any updates at all? This makes docker useless on macs

**Comment by alexDrinkwater** [comment]
Updates?

**Comment by jgarber-cisco** [comment]
I'm having a similar problem. Can't ping out of a container after 5-10 minutes.
```
root@2d6c951fef36:/opt/app/toolkit# ping cisco.com
PING cisco.com (72.163.4.185) 56(84) bytes of data.
64 bytes from redirect-ns.cisco.com (72.163.4.185): icmp_seq=1 ttl=36 time=60.1 ms
64 bytes from redirect-ns.cisco.com (72.163.4.185): icmp_seq=2 ttl=36 time=61.6 ms
64 bytes from redirect-ns.cisco.com (72.163.4.185): icmp_seq=3 ttl=36 time=60.4 ms
64 bytes from redirect-ns.cisco.com (72.163.4.185): icmp_seq=4 ttl=36 time=60.2 ms
^C
--- cisco.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 60.085/60.588/61.634/0.615 ms
root@2d6c951fef36:/opt/app/toolkit# ping cisco.com
ping: cisco.com: Temporary failure in name resolution
```
Running `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` passes before networking dies. Shows the following after:
```
[2023-03-06T15:34:54.378981000Z][com.docker.diagnose][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[WARN] DD0017: can a VM be started? vm has not started: vm has not started
[WARN] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please note the following 2 warnings:

1 : The check: can a VM be started?
    Produced the following warning: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.

2 : The check: is the LinuxKit VM running?
    Produced the following warning: vm is not running: vm has not started

The Docker engine runs inside a Linux VM. Therefore the VM must be running.


Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: vm has not started

The Docker engine runs inside a Linux VM. Therefore we must be able to start Virtual Machines.
```
I'm still able to run containers even after this, just can't connect out of them until I restart Docker Desktop.

**Comment by jgarber-cisco** [comment]
Update: Reinstall didn't help. I can ping the internal DNS address, but nslookups fail.
```
# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
# ping 127.0.0.11
PING 127.0.0.11 (127.0.0.11): 56 data bytes
64 bytes from 127.0.0.11: seq=0 ttl=64 time=1.086 ms
```
**Solved for now:** Downgrading Docker Desktop to 4.16.2 seems to have fixed it for the moment. I've been running my usual containers for hours with no problems, which hasn't been the case for a few days.

**Comment by 2snEM6** [comment]
This is also happening to me. Random network drops happening daily on 4.17.0

**Comment by fluentsolutions** [comment]
This has been happening on all v4 version of docker desktop for me.  Anything with high network activity clobbers the containers connectivity within minutes.

**Comment by 2snEM6** [comment]
Update: disabling "Use Rosetta for x86/amd64 emulation on Apple Silicon" and downgrading to 4.16 seems to stabilize things a bit..

**Comment by nothing2obvi** [comment]
This issue has been happening to me, too. Only fix is what someone else suggested, which is to downgrade to Docker Desktop for Mac 3.6.0.

**Comment by nothing2obvi** [comment]
> Update: disabling "Use Rosetta for x86/amd64 emulation on Apple Silicon" and downgrading to 4.16 seems to stabilize things a bit..

@2snEM6 - Did this fix continue working?

**Comment by nothing2obvi** [comment]
Apparently when this happens, I actually open Docker Desktop and things say they are "Running," but when I look in the logs there is nothing. It seems more like the containers freeze up, and perhaps my issue is more related to #6573 or #6533. Just in case anyone else discovers this is their problem. I've tried downgrading to 4.12. Will report back.

**Comment by nothing2obvi** [comment]
Docker Desktop for Mac 4.12 seems to have fixed the issue. However, with high network activity my containers are sometimes unreachable. Still better than 4.17.

**Comment by nothing2obvi** [comment]
I updated once again to 4.17.0 out of curiosity and strangely, I don't get this issue anymore. It could be that I'm not doing anything with very high network activity, though. However, I do get slow networking speeds. Didn't test this on 4.12, though. See #3497.

**Comment by elit69** [comment]
@nothing2obvi 
Thank for the clue. 
My problems is connection timeout between containers using default networking mode bridge with this IP 172.17.0.1.
I downgraded from 4.17.0 to 4.12.0. I have to recreate containers again. Now everything is stable.

Mac OS: Monterey 12.6.3
Chip: Apple M1

**Comment by nothing2obvi** [comment]
@elit69: Glad to be of help.

I started experiencing this issue again on 4.17.0. I've upgraded to 4.18.0 and haven't had the issue so far. Will report back if anything changes.

**Comment by nothing2obvi** [comment]
Upgraded to 4.19.0 a few weeks ago and this issue has pretty much resolved for me.

**Comment by christophermclellan** [comment]
Hi @nothing2obvi , thanks for the feedback and sorry that it took so much testing on your end. I will close this ticket for now. Happy to reopen should someone reproduce this issue on Docker Desktop v4.19 and above. Cheers, Chris

**Comment by ohadco100** [comment]
This issue still occurs with version 4.26.1

**Comment by ohadco100** [comment]
So, we identified that this issue occurs when the "SBOM Indexing" option is enabled in the docker runtime settings.
When we disabled this option we no longer suffered from the cluster network connectivity issues
