### ISSUE TITLE
Error during upgrade

### ISSUE THREAD

**Issue by soorajcalicut** [docker/for-mac#666]
### Information

Diagnostic ID: F8C2A956-3AE9-4263-BB89-60DEC6BBCE2A
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A313a)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
We have released Docker for Mac stable 1.12.1 which should fix a wide variety of issues found during the macOS Sierra Beta. Please upgrade to Docker for Mac stable 1.12.1 and report any issues you find in a separate ticket. Thanks for using Docker for Mac!
