### ISSUE TITLE
Docker keeps crashing when running openvpn container

### ISSUE THREAD

**Issue by beaufour** [docker/for-mac#6660]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E4C79B05-A051-4B80-B681-0654034A8F3D/20230103170753

### Expected behavior

Docker to continue running no matter what I do in a container

### Actual behavior

After running openvpn container (ghcr.io/wfg/openvpn-client) and sending traffic through, docker crashes... I've done it three times in a row now. Docker exits with

> ERRO[0033] error waiting for container: invalid character 'c' looking for beginning of value

### Information
  - macOS Version: 13.1 (22C65)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.15.0 (93002)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

It never really exits... likely because the docker daemon isn't running?

### Steps to reproduce the behavior

1. Run container, connecting to VPN
2. install youtube-dl and ffpmg
3. start downloading from favorite site
4. Wait a few minutes
5. Crash

**Comment by Neurone** [comment]
This seems connected to a very similar problem with the Kubo IPFS container #6650, maybe the culprit is vpnkit.

**Comment by nicks** [comment]
can you check if the debug build here resolves this issue for you? https://github.com/docker/for-mac/issues/6530#issuecomment-1370001795

**Comment by beaufour** [comment]
@nicks I'll give it a spin and report back!

**Comment by beaufour** [comment]
So far it has survived for longer than before (which was only a few minutes). I'm getting a lot of these (UDP) warnings from openvpn still (ie both production and debug build has them):

> 2023-01-03 19:22:04 AEAD Decrypt error: bad packet ID (may be a replay): [ #911545 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

But sadly it's a new VPN server I'm using, so I don't know if it's related at all or a red herring.

**Comment by beaufour** [comment]
Has been working for hours now. Thanks for the super quick response!
