### ISSUE TITLE
docker for mac fatal error

### ISSUE THREAD

**Issue by kakaheta** [docker/for-mac#667]
### Information

Diagnostic ID: 31DC70F0-72ED-4A6D-A351-93B9E3023FC8
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
We have released Docker for Mac stable 1.12.1 which should fix a wide variety of issues found during the macOS Sierra Beta. Please upgrade to Docker for Mac stable 1.12.1 and report any issues you find in a separate ticket. Thanks for using Docker for Mac!
