### ISSUE TITLE
Docker Desktop 4.16.1 fails to pull images at executing Dockerfile

### ISSUE THREAD

**Issue by rnarkk** [docker/for-mac#6684]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Pull an image properly when `FROM image:tag` is run in Dockerfile.

### Actual behavior

```
------
 > [internal] load metadata for docker.io/library/image:tag:
------
Dockerfile:1
--------------------
   1 | >>> FROM image:tag
   2 |     
   3 |     ...
--------------------
ERROR: failed to solve: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp: lookup auth.docker.io on IP_ADDRESS:PORT: server misbehaving
```

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@rnarkk thanks for your report. Could you reproduce the issue, upload diagnostics and quote the ID here? See the whale menu -> troubleshoot -> Get support. Thanks in advance!
