### ISSUE TITLE
Latest mac version very unstable

### ISSUE THREAD

**Issue by sebastienrumley** [docker/for-mac#6685]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

There is only one whale in the menubar
After computer and docker restart and reset to factory default, docker-compose up and down should work fine.

### Actual behavior

I have two whales in my menu bar

After one docker-compose up and docker-compose down cycle, when calling docker-compose up, docker gets stuck after logging "Attaching to xxxx, yyyy".

No container gets launched.

### Information

  - macOS Version: 12.3.1
  - Intel chip or Apple chip: 2.3 GHz 8-Core Intel Core i9
  - Docker Desktop Version: 4.16.1 (95567)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
@sebastienrumley thanks for the report. The problem with multiple whales in the menu bar is known, so I've linked this sighting to the internal ticket.

For the docker-compose problem, could you reproduce the issue, upload diagnostics and post the ID here? The diagnostics are in the Whale menu -> Troubleshoot -> Get Support. Ideally if you have a docker-compose.yml you could also share that would really help find the issue.

Thanks in advance!

**Comment by notjames** [comment]
That's not the only problem!!! I've had issues with docker randomly stopping and this happens consistently with or without heavy workloads although I'm running `kind`, but I've never historically had problems with this until I got this new laptop.

I have been digging through issues trying to figure out the issue to no avail. I've had problems with latest 15.x. One issue suggested downgrading to 14.1, which I did.  14.1 is more stable and actually recovers my running containers (15.x loses all state). Even 14.x just...stops responding. I've run the `diagnose check` and even `-upload`ed  hoping that I would get some kind of response or something. Basically, docker blows chunks right now. I'm running the M1 pro platform (FTR, I freaking hate mac but it's what my company has in alternative to windows for now).

**Comment by sebastienrumley** [comment]
@djs55 Hi, thanks for following up !

I'm just facing the same behavior so I can provide you with a big more information.

This is the command I just called :

docker-compose up --abort-on-container-exit
[+] Running 2/0
 ⠿ Container xxx-neo4j-db-1   Created                                                                                                                                                                        0.0s
 ⠿ Container xxx-neo4j-app-1  Recreated                                                                                                                                                                      0.1s
Attaching to xxx-neo4j-app-1, xxx-neo4j-db-1

The system is stucked again. Docker stats shows nothing

When going in the troublshooting pane, I get "Diagnose Suceeded".

When calling the com.docker.diagnose check, I get the attached output

[docker-diagnose-out.txt](https://github.com/docker/for-mac/files/10436858/docker-diagnose-out.txt)

Aborting and restarting doesn't solve the issue :

Attaching to xxx-neo4j-app-1, xxx-neo4j-db-1
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
canceled
xxx-advdaba-neo4j/$ docker-compose down
[+] Running 3/3
 ⠿ Container xxx-neo4j-app-1   Removed                                                                                                                                                                       0.0s
 ⠿ Container xxx-neo4j-db-1    Removed                                                                                                                                                                       0.1s
 ⠿ Network xxx-neo4j_internal  Removed                                                                                                                                                                       0.1s
xxx-advdaba-neo4j/$ docker-compose up --abort-on-container-exit
[+] Running 3/2
 ⠿ Network xxx-neo4j_internal  Created                                                                                                                                                                       0.0s
 ⠿ Container xxx-neo4j-db-1    Created                                                                                                                                                                       0.1s
 ⠿ Container xxx-neo4j-app-1   Created                                                                                                                                                                       0.1s
Attaching to xxxx-neo4j-app-1, xxxx-neo4j-db-1

**Comment by sebastienrumley** [comment]
Ah one more thing, after quitting and re-launching dock desktop, I see this in my console 👍 
Attaching to xxxx-neo4j-app-1, xxx-neo4j-db-1
Post "http://[...].docker%2Frun%2Fdocker.sock/v1.41/containers/43dadfc3ec68619011b1a00b27fba13867b073ee78f05904e65a10bd8850fa4b/start": context canceled

May be it helps?

**Comment by jscheel** [comment]
Yup, it's become unbearably bad. Docker just randomly dies now.

**Comment by djs55** [comment]
@jscheel @sebastienrumley @notjames could you try one of the latest developer builds:

- Apple Silicon: https://desktop-stage.docker.com/mac/main/arm64/96578/Docker.dmg
- Intel: https://desktop-stage.docker.com/mac/main/amd64/96578/Docker.dmg

and if you hit a problem, could you upload a set of diagnostics and quote the ID here? If you send us the ID we can take a look at the logs and investigate the issue.

**Comment by notjames** [comment]
> @jscheel @sebastienrumley @notjames could you try one of the latest developer builds:
> 
>     * Apple Silicon: https://desktop-stage.docker.com/mac/main/arm64/96578/Docker.dmg
> 
>     * Intel: https://desktop-stage.docker.com/mac/main/amd64/96578/Docker.dmg
> 
> 
> and if you hit a problem, could you upload a set of diagnostics and quote the ID here? If you send us the ID we can take a look at the logs and investigate the issue.

downloading and installing. I'll let you know.

**Comment by jscheel** [comment]
@djs55 I haven't had a change to try the dev build yet. I'll get to it eventually, just slammed right now. However, my problem appears to be tracked on this issue: https://github.com/docker/for-mac/issues/6546#issuecomment-1413783103. I tried disabling the virtualization framework and haven't had the issue re-appear since.

**Comment by jscheel** [comment]
@djs55 ok, it just happened to me again in the middle of the day, with the virt framework off. Quick question about your dev build, will it blow away my kubes env? I've noticed that updates to docker sometimes wipe everything and I have to rebuild.

**Comment by notjames** [comment]
I installed it but just to make sure I'm using the right one...it's 4.17 right?

**Comment by jscheel** [comment]
Well, doesn't really matter if docker-for-mac kills my k8s cluster, because it decided to crap the bed all on it's own with random certificate errors.

**Comment by jscheel** [comment]
I was unable to effectively run the dev build. Assuming additional logging was enabled on it, but it was so slow I couldn't do anything.

**Comment by notjames** [comment]
so far, the build I downloaded has been running smoothly since last week
that exceeds the usual period of time before it would crap out. So so far so good.

**Comment by notjames** [comment]
Everything still working very nicely. I'm not sure what you did or fixed, but so far it's good for me.

**Comment by sebastienrumley** [comment]
> > @jscheel @sebastienrumley @notjames could you try one of the latest developer builds:
> > ```
> > * Apple Silicon: https://desktop-stage.docker.com/mac/main/arm64/96578/Docker.dmg
> > 
> > * Intel: https://desktop-stage.docker.com/mac/main/amd64/96578/Docker.dmg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and if you hit a problem, could you upload a set of diagnostics and quote the ID here? If you send us the ID we can take a look at the logs and investigate the issue.
> 
> downloading and installing. I'll let you know.

Hi guys,

I've unfortunately jumped into other projects and I'm no longer soliciting Docker a lot as I used to. So far the version you provided works fine. If I bump into more issues I will reopen this thread.
