### ISSUE TITLE
Docker unusable after upgrading to 1.12.1

### ISSUE THREAD

**Issue by rafsanchez** [docker/for-mac#669]
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/36D26647-9A09-4CBF-8B61-47B0498EEF19/20160919-080401.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  Upgrade to 1.12.1

**Comment by justincormack** [comment]
Can you try resetting to factory defaults. This issue should hopefully be resolved going forward.

**Comment by lorddaedra** [comment]
I use Version 1.12.1-beta26.1 (build: 12100) on latest GM macOS Sierra (which should be released today). Same error. I tried to reset Docker. Nothing changes. 

My Docker works, but I have bug with PyCharm (not sure, it's related https://youtrack.jetbrains.com/issue/PY-20107 or not)

```
Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.12 (build: 16A323)
logs: /tmp/AC44D0AF-74EA-4D5B-80C5-1EE1A345BF32/20160920-023837.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

```

**Comment by donkeyx** [comment]
I just reset to factor defaults on '16A313a' build and seems to be working fine again ;)

**Comment by lorddaedra** [comment]
I tried reset again, it doesn't helps me, so I tried to uninstall and install. And it works now. (But I installed Stable version now, IMO it should work with Beta version too)..


```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/42BD31C2-2197-4FF0-ACFE-A1A738148C0D/20160920-035245.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

```

**Comment by lorddaedra** [comment]
So, @rafsanchez , try to uninstall && install if to solve this.

**Comment by rafsanchez** [comment]
Thanks, I was able to continue after resetting to defaults. I lost a couple of containers that had around a week's worth of work though. And I think the upgrade shouldn't have affected them or at least warned us if they would.

**Comment by samoht** [comment]
Detected symptom of problem 'aufs-corruption' in tmp/20160627-153017.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-06-14T20:18:48.347903972Z" level=debug msg="Using default logging driver json-file"
time="2016-06-14T20:18:48.348847455Z" level=debug msg="Golang's threads limit set to 14040"
time="2016-06-14T20:18:48.349530877Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-06-14T20:18:48.354894606Z" level=debug msg="Using graph driver aufs"
time="2016-06-14T20:18:48.589497703Z" level=debug msg="Failed to load mount 223c248a06f27f070eedc28b37634a4b11b392629d416c321accf6c904fe1b26: invalid mount id value"
time="2016-06-14T20:18:48.600345715Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-06-14T20:18:48.600670959Z" level=debug msg="Option DefaultDriver: bridge"
time="2016-06-14T20:18:48.600938190Z" level=debug msg="Option DefaultNetwork: bridge"
time="2016-06-14T20:18:48.602851029Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.4.12-moby`, error: exit status 1"
```
