### ISSUE TITLE
Docker Unable to Pull Images, i/o timeout [M1]

### ISSUE THREAD

**Issue by jwmann** [docker/for-mac#6693]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `BE120F5F-E1D8-49EF-A356-B20C6576C274/20230120010514`

### Expected behavior
Be able to pull Docker images

### Actual behavior
Anytime Docker tries to connect to internet, it times out

```
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.107.1:53: read udp 192.168.5.15:47849->192.168.107.1:53: i/o timeout
```

### Information

  - macOS Version: 13.1
  - Intel chip or Apple chip: M1 (Max)
  - Docker Desktop Version: v4.16.1

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[FAIL] DD0017: can a VM be started? vm has not started: vm has not started
[FAIL] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[WARN] DD0017: can a VM be started? vm has not started: vm has not started
[WARN] DD0016: is the LinuxKit VM running? vm is not running: vm has not started
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
```

### Steps to reproduce the behavior

Pull any image

  1. docker pull php:7.4-fpm

### Things I've tried and looked at

I've tried all solutions listed in: #1031 #5307 and #5680

- Updated Docker
- Restarted Docker, multiple times
- Restarted Mac, multiple times
- Did `docker network prune`
- Factory Reset Docker
- Made sure there's enough space (50gb are available)
- Set my DNS is set to known good DNS'
![image](https://user-images.githubusercontent.com/436270/213597337-3d84c2ba-2c74-42dd-af65-dc55e73ace6c.png)

- If I ssh into a vm, and ping `google.ca` it will fail because the hostname can't be resolved. Ping works fine outside vm
- If I manually set the nameservers in `/etc/resolv.conf` to `8.8.8.8` the hostname resolve, and a packet will send out but no packets will be received
- Turned off Experimental Features and Virtualization, no difference

I honestly have no idea what else to try here

**Comment by helloworldcoding** [comment]
`docker network prune ` is work to me thanks @jwmann
