### ISSUE TITLE
problem with installing extensions

### ISSUE THREAD

**Issue by Unfeir** [docker/for-mac#6695]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior
when I try to install any extension catch the problem:
_Failed to install extension: the local image you are trying to install has been modified and is different from the published image docker/<name-extension:>

### Information

After first installation Docker can't install any extension, all other parts work normally.
Restart, reinstall, full reinstall like(https://nektony.com/how-to/uninstall-docker-on-mac) didn't help to resolve this problem 

-->
  - macOS Version: Ventura 13.1 (22C65)
  - Intel chip or Apple chip: M2
  - Docker Desktop Version: Docker Desktop 4.16.2 (95914)

**Comment by Hypothesys-Smithgor** [comment]
Exactly the same problem, and configuration here.

**Comment by Hypothesys-Smithgor** [comment]
For anyone that this might help - finally got it to work by doing a combination of things.
Go to settings, Extensions, enable:
·         Enable Docker Extensions
·         Show Docker Extensions system containers
Save, close down desktop
Delete .docker folder from user directory
Restart and try again - it now all works.

**Comment by gtardif** [comment]
Thanks for your feedback. This issue happens in some cases, we have a fix for this that should be released in the next Desktop version (4.18)

**Comment by benja-M-1** [comment]
Since 4.20 has been released and a fix was expected in 4.18, I am closing this one. Feel free to reopen if it still happens.

**Comment by benja-M-1** [comment]
Hi @Babis86 it seems that the error is a bit different. You reported the message `Failed to fetch extensions` while initially it was `Failed to install extension`.

Can you send us a diagnostic ID so we have a look? https://docs.docker.com/desktop/troubleshoot/overview/#diagnose

**Comment by willwearing** [comment]
Hey @benja-M-1, 
I'm running MacOS Sonoma (Intel Chip) and am seeing similar issues. 

I am unable to run the diagnostics tool completely as Docker crashes well before it can be completed.
Here's what I see in the notification error in Docker desktop:
ID: A9DD8E65-0A45-4822-8CB3-9828841D37D2
File:
[docker_output.txt](https://github.com/docker/for-mac/files/12859641/docker_output.txt)

**Comment by benja-M-1** [comment]
@willwearing just to confirm, did everything work correctly with Docker Desktop 4.23?

**Comment by willwearing** [comment]
@benja-M-1 yep, it did

**Comment by JonathanCallewaert** [comment]
Same issue here as @Babis86 since updating to the latest version on Mac M1

**Comment by benja-M-1** [comment]
We have identified a possible root cause. A fix has been made and should be available in the release 4.25. Let us know if you still experience the issue with it.

**Comment by jwu-wuwta** [comment]
I am having the same issue here as @willwearing on 10/10. Everything was working fine and then just updated to 4.25.1 and breaking and receiving Failed to fetch extensions.
Diagnostic ID: 1B1E3DB2-EDAB-4AD2-8751-455AC68ECD42/20231117195827
