### ISSUE TITLE
Port 8080 conflict after recent update of Docker

### ISSUE THREAD

**Issue by Krzysiaczek** [docker/for-mac#670]
I've got one of my services declared in docker-compose.yml like that:
ports:
      - "8080:80"
and until today there was no problem. After recent update of Docker Beta this service can't be started as port 8080 seems to be taken by another application and this application seems to be a docker itself.

I was able temporarily resolve it by disabling the auto update option in Docker settings but it's back again even when auto update option is disabled.

$ lsof -i :8080
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 2345 kuba   20u  IPv4 0xe630....      0t0  TCP *:http-alt (LISTEN)
com.docke 2345 kuba   21u  IPv6 0xe6305...      0t0  TCP localhost:http-alt (LISTEN)

**Comment by djs55** [comment]
Could you upload a diagnostics report while the system is in this state? The diagnostics will include data on active port forwards which will allow us to investigate what's happening.

**Comment by Krzysiaczek-at-theFoundry** [comment]
Here you are
[20160919-151621.tar.gz](https://github.com/docker/for-mac/files/480207/20160919-151621.tar.gz)

**Comment by Krzysiaczek-at-theFoundry** [comment]
Today I've got similar problem but this time with port 80. It happened after sudden shut down of power in the office. After restarting the machine and attempt to start docker-compose up I've got such response:

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint foundry_web_1 (97b37232366adc7675b7299481f413437d2c69534bd6955e0ed97739aa8dfba9): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

Reseting the docker didn't help.

Here is a new diagnostic file from current stage
[20160923-183343.tar.gz](https://github.com/docker/for-mac/files/490208/20160923-183343.tar.gz)

**Comment by Krzysiaczek-at-theFoundry** [comment]
I've tried to reinstall docker, images and containers but nothing helps. With the previous version I would probably count on reseting the VirtualBox but with this one there is no such option I guess.

**Comment by djs55** [comment]
Thanks for the updated diagnostics info!

In 20160919-151621.tar.gz I can see 5 instances of `docker-proxy` inside the VM but only 4 published ports in `docker ps`:
```
$ grep docker-proxy ps\ uax.stdout 
 1710 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.18.0.99 -container-port 80
 3729 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3306 -container-ip 172.18.0.3 -container-port 3306
 3739 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3336 -container-ip 172.18.0.2 -container-port 3306
 3956 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.4 -container-port 80
 4045 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 88 -container-ip 172.18.0.99 -container-port 80
```
and
```
$ cat docker\ ps.stdout 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
fb645029f4dc        krzysiaczek/web     "apache2-foreground"     14 minutes ago      Up 14 minutes       0.0.0.0:88->80/tcp       foundry_subs_1
9284e7140f5a        krzysiaczek/web     "apache2-foreground"     3 days ago          Up 14 minutes       0.0.0.0:80->80/tcp       foundry_web_1
95efa3bfb1f7        mysql:5.6           "docker-entrypoint.sh"   6 weeks ago         Up 14 minutes       0.0.0.0:3336->3306/tcp   foundry_subs_db_1
295091e69d8d        mysql:5.6           "docker-entrypoint.sh"   7 weeks ago         Up 14 minutes       0.0.0.0:3306->3306/tcp   foundry_web_db_1
```
-- the process `1710 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.18.0.99 -container-port 80` seems to be orphaned.

In 20160923-183343.tar.gz I see 4 instances of `docker-proxy` inside the VM but only 2 containers:

```
$ grep docker-proxy ps\ uax.stdout 
 1714 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.18.0.99 -container-port 80
 1724 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.4 -container-port 80
 1890 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3306 -container-ip 172.18.0.2 -container-port 3306
 1900 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3336 -container-ip 172.18.0.3 -container-port 3306
```
and
```
$ cat docker\ ps.stdout 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
95efa3bfb1f7        mysql:5.6           "docker-entrypoint.sh"   7 weeks ago         Up 37 seconds       0.0.0.0:3336->3306/tcp   foundry_subs_db_1
295091e69d8d        mysql:5.6           "docker-entrypoint.sh"   8 weeks ago         Up 37 seconds       0.0.0.0:3306->3306/tcp   foundry_web_db_1
```
I also see 4 iptables rules:
```
-A DOCKER ! -i br-930b797caee4 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.18.0.99:80
-A DOCKER ! -i br-930b797caee4 -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.18.0.4:80
-A DOCKER ! -i br-930b797caee4 -p tcp -m tcp --dport 3306 -j DNAT --to-destination 172.18.0.2:3306
-A DOCKER ! -i br-930b797caee4 -p tcp -m tcp --dport 3336 -j DNAT --to-destination 172.18.0.3:3306
```
but only 2 `veth` devices:
```
veth104ff29 Link encap:Ethernet  HWaddr A2:E1:21:AA:79:3B  
          inet6 addr: fe80::a0e1:21ff:feaa:793b%32619/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:1944 (1.8 KiB)

veth3489586 Link encap:Ethernet  HWaddr AE:CA:92:30:54:72  
          inet6 addr: fe80::acca:92ff:fe30:5472%32619/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:1944 (1.8 KiB)
```
It looks like 2 containers have fully set up networking, while another 2 have partially set up networking.

I'll investigate how this could have happened -- perhaps the `docker-proxy` processes ignored the signal to quit?

Assuming the problem is only caused by the leaked `docker-proxy` process, killing the process should make the port available again:
```
$ docker run -it --pid=host --privileged justincormack/nsenter1
/ #
/ # ps uax | grep "host-port 80" | grep -v grep 
 2058 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.2 -container-port 80
/ #
/ # kill 2058
```
Let me know if this works or not. If not then it implies there's more state to clear out.

Sorry for the inconvenience this must be causing.

**Comment by Krzysiaczek-at-theFoundry** [comment]
Thanks for that. 

The source of the initial problem was external power supply failure so there was no quit signal sent I guess.

Your solution was looking promising 

> /# ps uax | grep "host-port 80" | grep -v grep
1712 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.4 -container-port 80
1722 root       0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.18.0.99 -container-port 80
/ # kill 1712
/ # kill 1722
/ # ps uax | grep "host-port 80" | grep -v grep
/ # ps uax | grep "host-port 8080" | grep -v grep
/ # exit

but unfortunately problem didn't go away

> $ docker-compose up web subs
Starting foundry_subs_db_1
Starting foundry_web_db_1
Starting foundry_web_1
>
> ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint foundry_web_1 (613097c960be757bcc1149054ee580d53ea175d0273695b800e1d5911f1cf828): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

but has hidden elsewhere as the previous test doesn't show anything:

> $ lsof -i :80
> $

Here is a new diagnostic file. I hope you can find something useful in it.

[20160924-154839.tar.gz](https://github.com/docker/for-mac/files/491147/20160924-154839.tar.gz)

**Comment by dsheets** [comment]
Could this also be the cause of #205?

**Comment by Krzysiaczek** [comment]
Yeah, #205 looks very similar to my case.
Right I am away from this machine (for a whole week) and using the older version Toolbox for Mac on my laptop so I cannot test or verify anything at the moment.

**Comment by Krzysiaczek-at-theFoundry** [comment]
Reseting the Docker is the solution I was looking for, I just wasn't aware it exists - hidden in the preferences.
Thanks for help.

**Comment by rogaha** [comment]
thanks for the feedback @Krzysiaczek
