### ISSUE TITLE
Sends bricking updates to old OS versions

### ISSUE THREAD

**Issue by probablykasper** [docker/for-mac#6701]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 673AE861-0DFB-43CC-BAE7-05CDDFBC9D93/20230125010752

### Actual behavior

The latest update bricked the Docker Desktop app because the app now requires macOS 11+. This wasn't mentioned in the release notes anywhere, because it wanted to update to a more recent version after the breaking change.

### Expected behavior

There should not be an update if it will brick the app.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Update from 4.15

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

<details>
<summary>Output</summary>

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[FAIL] DD0019: is the com.docker.vmnetd process responding? failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: is the com.docker.vmnetd process responding?
    Failed with: failed to ping vmnetd with error: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory

The com.docker.vmnetd process is needed to create symlinks for CLIs in your path.
```

</details>

### Steps to reproduce the behavior

  1. Check for updates and install

**Comment by probablykasper** [comment]
My workaround for now, to prevent accidental future updates, is to block `Docker.app/Contents/MacOS/Docker` from accessing `https://desktop.docker.com/mac/main/amd64/appcast.xml` using the [LuLu](https://objective-see.org/products/lulu.html) firewall app

**Comment by sparkcodeuk** [comment]
Had this happen to me, luckily I had a time machine backup of the older version I could reinstate, but the Docker desktop app should confirm whether your current version of OSX supports whatever version you're about to update to and if it cannot update, then display a message accordingly (and ideally state which is the minimum version of OSX is supported for that new release).

**Comment by MaffooBristol** [comment]
If you download the previous version from here: https://docs.docker.com/desktop/release-notes/#4150 then it should all be fine and you won't lose any data.

This is a comical oversight from the docker team though, was not expecting to install an auto update and see the whole thing be completely borked ha.

**Comment by ddelange** [comment]
fwiw, maybe the `<sparkle:minimumSystemVersion>10.15.0</sparkle:minimumSystemVersion>` property needs updating to 11+ in the [appcast](https://desktop.docker.com/mac/main/amd64/appcast.xml)

**Comment by ddelange** [comment]
relevant update of the homebrew cask: https://github.com/Homebrew/homebrew-cask/pull/141290/files

**Comment by ddelange** [comment]
> fwiw, maybe the `<sparkle:minimumSystemVersion>10.15.0</sparkle:minimumSystemVersion>` property needs updating to 11+ in the [appcast](https://desktop.docker.com/mac/main/amd64/appcast.xml)

@stephen-turner is this the right repository to report?
