### ISSUE TITLE
open VsCode get error Error invoking remote method 'desktop-go-backend': Error: {"message":"opening editor: exit status 127 - "}

### ISSUE THREAD

**Issue by akechana** [docker/for-mac#6705]
when i try to open in VSCode on docker desktop then get error
Error invoking remote method 'desktop-go-backend': Error: {"message":"opening editor: exit status 127 - "}

please help
Thank you

**Comment by yosriy82** [comment]
<img width="765" alt="Capture d’écran 2023-01-29 à 13 47 04" src="https://user-images.githubusercontent.com/4247854/215321153-35113baa-2fcb-4576-ba8a-eb93c454fde0.png">
Same here.. Any idea how to fix please?
