### ISSUE TITLE
[QEMU only] `tcpdump` is crashing with error "SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented" on M1 when running in `amd64` containers

### ISSUE THREAD

**Issue by aSapien** [docker/for-mac#6707]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5D6CF88B-77A8-4CF0-82AC-F702FE3B9D0B/20230127214649

### Expected behavior
`tcpdump` does not crash. Example of correct behavior (using flag `--platform=linux/arm64`):
```
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
```
### Actual behavior
`tcpdump` is crashing with error:
```
tcpdump: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented
```
### Information

  - macOS Version: Ventura 13.1 (22C65)
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.16.2 (95914)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

<details>
<summary>Starting diagnostics...</summary>

```sh
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

</details>

### Steps to reproduce the behavior

  1. Use a Macbook with M1 cpu
  2. Start tcpdump within a `amd64` container: 
    ```
docker run -it --rm --platform linux/amd64 nicolaka/netshoot:v0.8 tcpdump
    ```

**Comment by Kosaaaaa** [comment]
Enabling option `Use Rosetta for x86/amd64 emulation on Apple Silicon` **fixed this issue for me.**

**Option path:**
Docker Desktop > Settings > Features in Development > `Use Rosetta for x86/amd64 emulation on Apple Silicon`

**Comment by aSapien** [comment]
Yep, I can confirm. It worked on my end as well.

**Comment by aSapien** [comment]
I edited the issue to reflect that it only manifests using QEMU. Feel free to close it if it is no longer relevant

**Comment by AbhinavMir** [comment]
This feature doesn't seem to be active on `docker desktop` features in development anymore.

**Comment by aSapien** [comment]
@AbhinavMir make sure you're using MacOS Ventura. I think earlier MacOS versions are not supported

**Comment by jabowery** [comment]
```
2023/07/19 17:36:14  **** will rewrite dest IP from 239.255.42.42 to 172.17.0.2
2023/07/19 17:36:14  
2023/07/19 17:36:14  Fatal Error in interface.c:get_interface_list() line 101:
2023/07/19 17:36:14   Error: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented
# uname -a
Linux 66dc784e505a 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 aarch64 GNU/Linux
```
```
$ cat Dockerfile 
FROM arm64v8/debian
...
$ uname -a
Linux ML 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
/remove-lifecycle stale

**Comment by sanzhar-theori** [comment]
> Enabling option `Use Rosetta for x86/amd64 emulation on Apple Silicon` **fixed this issue for me.**
> 
> **Option path:** Docker Desktop > Settings > Features in Development > `Use Rosetta for x86/amd64 emulation on Apple Silicon`

man, you are a lifesaver

**Comment by dgageot** [comment]
I'm going to close this issue because it's fixed with Rosetta and Rosetta is becoming the default setup on recent versions of macOS.

**Comment by josephwhenry** [comment]
On the most recent version of Docker for Mac, `Use Rosetta for x86/amd64 emulation on Apple Silicon` is under Settings > General > Virtual Machine Options
