### ISSUE TITLE
Let the user know if Rosetta isn't installed

### ISSUE THREAD

**Issue by vadim0x60** [docker/for-mac#6718]
I tried enabling the "Use Rosetta for x86/amd64 emulation on Apple Silicon" setting and dockerd just crashed and became impossible to restart. Eventually I figured out that it's because Rosetta isn't yet installed on this machine. A clear error message (or an invitation to install Rosetta) could be very useful here.

**Comment by vadim0x60** [comment]
OK, after enabling the feature I have run into so many errors launching different containers that this minor problem should probably have a very low priority :)

**Comment by giboow** [comment]
+1
Same problem on my new Macbook  M1 Pro

**Comment by PeSe007** [comment]
+1
Same problem on my new Macbook M1 Pro

**Comment by haowang-bioinfo** [comment]
I'm using the latest Docker desktop for Apple chip enabling the "Use Rosetta for x86/amd64 emulation on Apple Silicon". How do I know if Resetta 2 is activated or not? please help @vadim0x60
