### ISSUE TITLE
Docker Desktop loads forever. Can't pause. Can't restart. Can't quit. Can't force-close.

### ISSUE THREAD

**Issue by emeraldhieu** [docker/for-mac#6719]
The Preferences is blocked by the loading panel. There is not the process in Activity Monitor to force close.

Screenshots:
https://pasteboard.co/KK6Iek5SuCOj.png
https://pasteboard.co/qsweb5t0ie99.png

I've tried Clean/Purge data, Reset Factory but it's still stuck. I may need to restart my machine.
I don't know how to reproduce it.

Docker Desktop version 4.15.0 (93002)
MacBookPro. Processor 2,4 GHz Quad-Core Intel Core i5.

**Comment by Sanderluc5** [comment]
Same something, got this problem after updating Docker to its newest version.. I'm running MacOS

**Comment by tcparker976** [comment]
I have the same problem, newest version of docker on mac os with intel chip

**Comment by emeraldhieu** [comment]
I've got the errors again today. I've checked the dockerd.log and containerd but see no errors. The issue seems to happen after a sleep (lid closed and opened after a period of time).

- dockerd: https://pastebin.com/myBLfJmE
- containerd: https://pastebin.com/BTq2SQGz

**Comment by LogansUA** [comment]
> I've got the issue again today. I've checked the dockerd.log and containerd but see no errors. The issue seems to happen after the laptop sleeps.
> 
> * dockerd: https://pastebin.com/myBLfJmE
> * containerd: https://pastebin.com/BTq2SQGz
> 
> The only workaround is restarting machine. 🙁

Exact same issue here on v4.16.2, after sleep docker desktop just can't start up

**Comment by RomansWorks** [comment]
Had the same error, cleaning of cache and application support folders, reinstall and restart didn't help. What seem to have helped is installing Rosetta: 
```bash
softwareupdate --install-rosetta
```

**Comment by LogansUA** [comment]
> > I've got the issue again today. I've checked the dockerd.log and containerd but see no errors. The issue seems to happen after the laptop sleeps.
> > 
> > * dockerd: https://pastebin.com/myBLfJmE
> > * containerd: https://pastebin.com/BTq2SQGz
> > 
> > The only workaround is restarting machine. 🙁
> 
> Exact same issue here on v4.16.2, after sleep docker desktop just can't start up MacBook Pro Apple M1 Pro When trying to restart it, getting this error <img alt="Screenshot 2023-02-08 at 11 33 53" width="594" src="https://user-images.githubusercontent.com/7515743/217491665-5bd038de-c3a6-4880-af2f-9a402c0d233d.png">

I don't know how but after the next restart everything works fine now 🤷
