### ISSUE TITLE
Can't update to beta 26

### ISSUE THREAD

**Issue by SG5** [docker/for-mac#672]
### Steps to reproduce

1. Try install update
2. Wait download process

### Expected behavior

Apply update after download

### Actual behavior

Error `An error occurred while extracting the archive. Please try again later.`

### Information

```
Diagnostic ID: 5AA19EE6-7E21-4D37-8482-5B8F95BFB289
Docker for Mac: 1.12.1-beta25 (Build 11807)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by mchiang0610** [comment]
@SG5 Thanks for submitting this. If you download it again directly here, does it work? https://download.docker.com/mac/beta/Docker.dmg

I'm on 16A320 (macOS sierra) as well, and I'm having trouble reproducing by installing beta 25 and upgrading to beta 26.

**Comment by dsheets** [comment]
Please try again with the macOS Sierra 10.12 final release (build 16A323) or later. If you can still reproduce the problem, please re-open this issue.
