### ISSUE TITLE
Start Docker Desktop when you log in has no effect

### ISSUE THREAD

**Issue by GM-Alex** [docker/for-mac#6723]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6A214A76-BE7C-4AC7-8BB8-5F27B1A7A764/20230208083354

### Expected behavior

Docker Desktop should start if I'm logging in.

### Actual behavior

Docker Desktop doesn't start if I'm logging in.

### Information

  - macOS Version: Ventura 13.2
  - Intel chip or Apple chip: Apple M2 Max
  - Docker Desktop Version: 4.16.2

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

````
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
````

### Steps to reproduce the behavior

1. Install Docker Desktop
2. Enable "Start Docker Desktop when you log"
3. Reboot

**Comment by guxiaobai** [comment]
I have the same bug. but sometime can

**Information**
macOS Version: Ventura 13.2 / Monterey 16.3
Intel chip or Apple chip: Intel
Docker Desktop Version: 4.16.2

**Comment by dvigueras** [comment]
Same issue here, I've fixed the problem temporarily by manually adding Docker in the "Login items" sections of "Users & Groups" macOS settings.

**Comment by MihaelaStoica** [comment]
We had fixed this issue in the latest release of Docker Desktop, v4.17.0.
See [mention in the release notes](https://docs.docker.com/desktop/release-notes/#:~:text=Fixed%20a%20bug%20that%20caused%20the%20Start%20Docker%20Desktop%20when%20you%20log%20in%20setting%20not%20to%20work.).
