### ISSUE TITLE
no suitable node (unsupported platform on 1 node)  on apple chip

### ISSUE THREAD

**Issue by katedoctor** [docker/for-mac#6724]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] use rosseta is turn on 
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 9672c61a-69ab-4a31-85bb-4d5ac4c78cf9/20230207173903

### Expected behavior
Scale service ( which was built on Linux 32bit) on m1 chip with docker swarm 

### Actual behavior
no suitable node (unsupported platform on 1 node)

### Information
  - macOS Version: 13.2
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: 4.16.2

### Steps to reproduce the behavior
1. Have images built on 32bit
2. run docker swarm init
3. Pull them to Apple Chip Macbook 
4. Try to scale service to 1
5. Got error "no suitable node (unsupported platform on 1 node)"

**Comment by dorinand** [comment]
I encounter the same issue with Redis. When I run it in docker swarm orchestrator, I get `no suitable node (unsupported platform on 1 node)`. When I run it with `docker run` command, only warning occur: `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested` but I am able to run it:
```
docker run -ti --rm docker.io/bitnami/redis:7.0 /bin/bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
redis 14:10:46.50
redis 14:10:46.52 Welcome to the Bitnami redis container
redis 14:10:46.55 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 14:10:46.57 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 14:10:46.59

I have no name!@de6d0365d0a5:/$
```

Is there any workaround?

Docker Desktop 4.16.2 (95914)
Mac: 13.0.1

**Comment by appurist** [comment]
I'm still getting this error today (June 2024) and the easiest way to reproduce it is a Swarm stack with ELK (or any one of them). I'm trying to use an older version which seems to be `amd64` only, even with `--platform linux/amd64` on the swarm deploy and the pull before.

Using image `docker.elastic.co/elasticsearch/elasticsearch` shows as `amd64` in Docker Desktop for Mac, and `docker stack deploy` with a stack including one of the ELK services from the images above reports no suitable node.

![image](https://github.com/docker/for-mac/assets/1620487/6ad259c3-3917-49c5-9e75-86969b656dcf)

**Comment by PatrikScully** [comment]
I still experiencing the issue (Sep 2024). If I add the `--resolve-image=never` flag to the `docker stack deploy` command, it could be a workaround. Of course, in this case, I should `docker image pull` all images before the deployment. With this the errors disappear.
