### ISSUE TITLE
Creating "rootNode" subnodes: constructing "BackendServices" in "rootNode": doing migrations: reading actual settings: invalid character '/' looking for beginning of value

### ISSUE THREAD

**Issue by fof-fa** [docker/for-mac#6730]
Expected behavior:
Launching Docker Desktop and work with it

Actual behavior:
Crashed with launch and show message:
Something went wrong
Creating "rootNode" subnodes: constructing "BackendServices" in "rootNode": doing migrations: reading actual settings: invalid character '/' looking for beginning of value

macOS Catalina
Intel chip
Docker Desktop 4.15.0

Steps to reproduce the behavior
1. click on icon Docker Desktop on iconbar
2. Did nothing and show message 
Something went wrong
Creating "rootNode" subnodes: constructing "BackendServices" in "rootNode": doing migrations: reading actual settings: invalid character '/' looking for beginning of value
![Снимок экрана 2023-02-09 в 20 21 50](https://user-images.githubusercontent.com/46462758/217842338-bc8efdb6-c260-4059-919a-4ac45fbb234e.png)

How fix it?

**Comment by JakubBrozek** [comment]
Had the same problem, reinstalling docker helped my case.
I did not delete Docker's Appdata folder. Just reinstalled Docker Desktop.

**Comment by xinmans** [comment]
same issue

macOS Catalina
Apple silicon
Docker Desktop 4.15.0

how to fix?

**Comment by fof-fa** [comment]
> same issue
> 
> macOS Catalina Apple silicon Docker Desktop 4.15.0
> 
> how to fix?

Decision is here https://forums.docker.com/t/creating-rootnode-subnodes-constructing-backendservices-in-rootnode-doing-migrations-reading-actual-settings-invalid-character-looking-for-beginning-of-value/134543
