### ISSUE TITLE
Docker Desktop Download fails on New Macbook

### ISSUE THREAD

**Issue by blinton-sc** [docker/for-mac#6739]
- [X ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop Opens after downloading
### Actual behavior
Docker desktop does not open and shows this error:
ChunkLoadError: Loading chunk 7157 failed.
(error: file:///Applications/Docker.app/Contents/MacOS/Docker%20Desktop.app/Contents/Resources/app.asar/web/7157.bundle.js)
### Information

  - macOS Version: Ventura 13.2
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version:  https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module

### Steps to reproduce the behavior

  1. Download docker desktop on my computer
  2. Try to open
  3. Get error

**Comment by mattieb** [comment]
Did you try the Apple Silicon version? You said you had a new MacBook and your download link shows the Intel version.
