### ISSUE TITLE
Docker Desktop won't start on 2012 iMac

### ISSUE THREAD

**Issue by GregHendley** [docker/for-mac#6746]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: C7B2D489-E9E2-4A4C-A584-31EA3DC714F7/20230227161640

### Expected behavior
Docker desktop starts

### Actual behavior
Docker desktop says the settings are bad and offers to diagnose the problem.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: 2.7 GHz Quad-Core Intel Core i5
  - Docker Desktop Version: Can't tell. The older DMG date is Oct 21, 2020. The latest was downloaded today, Feb 27, 2023.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` 

The diagnostics zip file submitted under the above Diagnostics ID

### Steps to reproduce the behavior

  1. Copy Docker from the DMG to the Applications folder
  2. Double-click on Docker in the Applications folder

**Comment by mat007** [comment]
Docker Desktop requires at least macOS 11, see https://docs.docker.com/desktop/install/mac-install/#mac-with-intel-chip
