### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nehcnah** [docker/for-mac#675]
### Information

Diagnostic ID: 6A8176FB-D31F-4B60-B24A-1AC9D58FAD33
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G1004)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/lux/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/lux/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/lux/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
You should have seen an error message which read:

> Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
        VirtualBox v4.3.28 is currently installed.
        Please upgrade or uninstall Virtualbox.

It means that Docker and VirtualBox < 4.3.30 are mutually incompatible and you must upgrade or uninstall VirtualBox before using Docker for Mac. We do this because otherwise OS X will crash due to issues with VirtualBox's kernel module in versions before 4.3.30.
