### ISSUE TITLE
VirtioFS volumes not appearing correctly in containers

### ISSUE THREAD

**Issue by Smith8154** [docker/for-mac#6750]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 771B4D3A-1C15-4188-9364-D05FADEAE701/20230303023824

### Expected behavior
When using VirtioFS for file sharing, I should be able to open a terminal on my container and browse the folder structure of all volumes being passed from my host.
### Actual behavior
When using VirtioFS and adding a volume that lives on a network share mounted on my host, the container is able to browse through the folder structure of the volume, create and delete files, but any attempt to list files returns 0 results.
### Information

  - macOS Version: 13.2.1
  - Intel chip or Apple chip: Apple M2
  - Docker Desktop Version: 4.17.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
segment 2023/03/02 21:32:25 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp [::]:443: connect: connection refused
segment 2023/03/02 21:32:25 ERROR: 1 messages dropped because they failed to be sent and the client was closed
No fatal errors detected.
```
### Steps to reproduce the behavior

1. Ensure you are using VirtioFS for file sharing.
2. Create a container with a volume that lives on a mounted network drive.
3. Start the container, open the CLI in the container, and attempt to list files/folders from the volume.

**Comment by fredericdalleau** [comment]
@Smith8154 Can you share some command line to reproduce the issue? A quick test I made here worked. Thanks!

**Comment by fredericdalleau** [comment]
How did you mount this volume? What is the volume server, is it a plex server, another mac ?

**Comment by Smith8154** [comment]
The volume is hosted on a QNAP NAS. I use Finder's "Connect to Server" to mount it. The container is for Plex, and I have another container that I am passing this through to and it has the same problem.

**Comment by Smith8154** [comment]
After moving to SMB, I no longer have this issue.
