### ISSUE TITLE
Starting docker saturates all CPUs available.

### ISSUE THREAD

**Issue by leventyalcin** [docker/for-mac#6780]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Being able to work with Docker locally. 

### Actual behavior
The moment I start Docker, it starts to saturate all the CPU available. My laptop starts to respond really slowly. This behaviour started to happen after upgrading Ventura
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1218537/227606784-0cda15f8-79f9-4ca6-bde4-a327b79d0faa.png">

I tried couple of things suggested in the previous issues opened by users (eg; Selecting FUSE for file sharing, ensuring Use Virtualisation framework is ticket etc) but none of those really helped. And I don't know what else to try.

### Information

  - macOS Version: 13.2.1 (22D68)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: v4.17.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by leventyalcin** [comment]
@thaJeztah I've just run another diagnostics and the ID is `D645A40F-F306-40AC-B556-166AB92BEB65/20230327092432`

**Comment by MatElGran** [comment]
Just had the problem today, my laptop became sluggish after launching a mainly idle postgres container, and found out that disabling "Use Virtualisation framework" made docker act as I was used to.

**Comment by leventyalcin** [comment]
@MatElGran 's suggestion made my experience slightly better also.

**Comment by dschuessler** [comment]
I got the same problem.
C68637A6-5795-4376-8532-2B5E040B2148/20230404142030

macOS Version: 12.6.3
Intel chip or Apple chip: Intel
Docker Desktop Version: v4.17.0

**Comment by leventyalcin** [comment]
I wish I knew if downgrade would help and what was the last version I could work with. Even running something as easy as busybox is giving my laptop hiccups.
