### ISSUE TITLE
Cannot start Docker 

### ISSUE THREAD

**Issue by alekseyig** [docker/for-mac#679]
### Expected behavior
Docker starts
### Actual behavior
Docker does not start and fails with error:

alekseyzhukov$ /Applications/Docker.app/Contents/MacOS/Docker
1474391547123351040 com.docker.docker Application version: 1.12.1 (12133)
1474391547123526144 com.docker.docker Administrator user: true
1474391547145982976 com.docker.docker OSX Version: Version 10.11.6 (Build 15G1004)
kern.hv_support: 1
1474391547338918912 com.docker.docker migrator: start migration process
1474391547340812032 com.docker.docker migrator: previous install detected
1474391547340845056 com.docker.docker migrator: previous version is 1.12.1-beta26.1
1474391547340930048 com.docker.docker migrator: no migration needed, you are good to go!
1474391547340955136 com.docker.docker migrator: successfully updated from version 1.12.1-beta26.1 to 1.12.1
1474391547342294016 com.docker.docker migrator: end of migration process
1474391547373430016 com.docker.docker event tracker initialized
1474391547377698048 com.docker.docker Bundle path: /Applications/Docker.app
1474391551302903040 com.docker.docker applicationWillTerminate
azhukov-mbpGH:LaunchDaemons alekseyzhukov$ /Applications/Docker.app/Contents/MacOS/Docker
1474391577112646144 com.docker.docker Application version: 1.12.1 (12133)
1474391577112801024 com.docker.docker Administrator user: true
1474391577134223872 com.docker.docker OSX Version: Version 10.11.6 (Build 15G1004)
kern.hv_support: 1
1474391577327482112 com.docker.docker migrator: start migration process
1474391577329421056 com.docker.docker migrator: previous install detected
1474391577329453824 com.docker.docker migrator: previous version is 1.12.1-beta26.1
1474391577329537792 com.docker.docker migrator: no migration needed, you are good to go!
1474391577329558016 com.docker.docker migrator: successfully updated from version 1.12.1-beta26.1 to 1.12.1
1474391577330990080 com.docker.docker migrator: end of migration process
1474391577361067008 com.docker.docker event tracker initialized
1474391577365431040 com.docker.docker Bundle path: /Applications/Docker.app
1474391582139164928 com.docker.docker Failed to install networking components.
1474391591880945920 com.docker.docker privileged installation of com.docker.vmnetd successful
1474391591881047040 com.docker.docker com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
1474391592882494976 com.docker.docker com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
1474391593883160064 com.docker.docker com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
1474391594884366080 com.docker.docker com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
1474391595885723136 com.docker.docker com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
1474391596886159872 com.docker.docker Communication with networking components failed.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/02A29DC9-AA49-4BDD-A8CF-412C3B3007ED/20160920-121339.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/alekseyzhukov/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. As you can see from the startup logs, i had a beta version before and tried to go with stable,
I downloaded stable version, moved beta to Trash and installed stable, launched stable and it failed with error above.
  2. ...

**Comment by dsheets** [comment]
Have you tried uninstalling through the application before reinstalling? Go to :whale: -> `Preferences` -> `Uninstall / Reset` -> `Uninstall`. Then, simply run the application again. Does it still fail to start?

**Comment by alekseyig** [comment]
I am going to close it for now, yes i was able to make it working by uninstalling and removing /Library/LaunchDaemons/com.docker.vmnetd.plist. However, i was not be able to uninstall it using UI, i used cli to do that.
Thank you for looking into that, but it seems to me that the root cause of this problem is still unknown.
