### ISSUE TITLE
enable BPF Type Format (BTF)

### ISSUE THREAD

**Issue by errordeveloper** [docker/for-mac#6800]
Since there is eBPF support in Docker Desktop (#4454), it'd be also very useful to enable tracing use cases that require access to kernel type information at runtime.

Tools that rely on BTF:
- https://github.com/iovisor/bpftrace
- https://github.com/cilium/tetragon

Changes needed:
- kernel config option `CONFIG_DEBUG_INFO_BTF` needs to be enabled

**Comment by seanmwinn** [comment]
I'm also impacted by this same issue trying to run Tetragon on docker for mac.

**Comment by mtardy** [comment]
Any BPF project that relies on CO-RE to work would need the BTF file, that would be awesome to have: 
- https://nakryiko.com/posts/bpf-portability-and-co-re/
- https://nakryiko.com/posts/bpf-core-reference-guide/.

**Comment by anjmao** [comment]
Hi, I tried building custom kernel image from https://github.com/linuxkit/linuxkit/issues/3755
Could you guys share working linuxkit build configuration which works on docker for mac?
I tried https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.md guide and replaced kernel located at /Applications/Docker.app/Contents/Resources/linuxkit/kernel but got unknown VM boot error.

**Comment by errordeveloper** [comment]
> Hi, I tried building custom kernel image from [linuxkit/linuxkit#3755](https://github.com/linuxkit/linuxkit/issues/3755)
> Could you guys share working linuxkit build configuration which works on docker for mac?

I don't know if there is a way to do this that works with DD.

I started off by updating kernel versions (https://github.com/linuxkit/linuxkit/pull/3919), but seem to come across some cross-compilation bugs that I didn't have time to troubleshoot yet. Once that PR is in, I was going to make another one that enables BTF in more recent kernels. If you have time to dive into that, it'd be very helpful.

> I tried https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.md guide and replaced kernel located at /Applications/Docker.app/Contents/Resources/linuxkit/kernel but got unknown VM boot error.

I think that doc is very much out of date.

**Comment by anjmao** [comment]
Hi @stephen-turner Any chance to get actual linuxkit manifest you are using on docker for-mac? I know docker desktop is closed source, but actual linuxkit manifest would make testing custom kernel much easier. Let me know anyway. If it's not possible due to company policies I will try to dig into it.

**Comment by mariomac** [comment]
✋ Another person impacted by this issue when trying to run some integration tests from Mac. My only solution was to replace Docker Desktop by Colima https://github.com/abiosoft/colima

**Comment by nehagup** [comment]
I'm also impacted by the same issue! Trying [Keploy](keploy.io) on Docker Desktop for Mac.

**Comment by PhilipSchmid** [comment]
It looks like this issue can be closed.

At least with Docker Desktop `24.0.6` (Kernel: `6.4.16-linuxkit`) `CONFIG_DEBUG_INFO_BTF` is now enabled:
```bash
$ docker run -it --rm --privileged --pid=host ubuntu nsenter -t 1 -m -u -n -i sh -c 'cat /proc/config.gz | gunzip | grep CONFIG_DEBUG_INFO_BTF'
CONFIG_DEBUG_INFO_BTF=y
CONFIG_DEBUG_INFO_BTF_MODULES=y
```

**Comment by 111andre111** [comment]
Ok, I double checked in a container directly and confirm that bpftrace seems to do its work. Tested with a Docker Desktop 4.25.2 for Mac:
`docker run -ti -v linuxkit-kernel-headers:/usr/src:ro -v /lib/modules/:/lib/modules:ro -v debugfs:/sys/kernel/debug:rw            --net=host --pid=host --privileged quay.io/iovisor/bpftrace:latest bpftrace --info`

Output is:
```
        System
          OS: Linux 6.4.16-linuxkit #1 SMP PREEMPT_DYNAMIC Thu Nov 16 10:55:59 UTC 2023
          Arch: x86_64
        Build
          version: v0.19.0
          LLVM: 12.0.0
          unsafe probe: no
          bfd: yes
          libdw (DWARF support): yes
        Kernel helpers
          probe_read: yes
          probe_read_str: yes
          probe_read_user: yes
          probe_read_user_str: yes
          probe_read_kernel: yes
          probe_read_kernel_str: yes
          get_current_cgroup_id: yes
          send_signal: yes
          override_return: no
          get_boot_ns: yes
          dpath: yes
          skboutput: yes
          get_tai_ns: yes
          get_func_ip: yes
          jiffies64: yes
        Kernel features
          Instruction limit: 1000000
          Loop support: yes
          btf: yes
          module btf: yes
          map batch: yes
          uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes
        Map types
          hash: yes
          percpu hash: yes
          array: yes
          percpu array: yes
          stack_trace: yes
          perf_event_array: yes
          ringbuf: yes
        Probe types
          kprobe: yes
          tracepoint: yes
          perf_event: yes
          kfunc: yes
          kprobe_multi: no
          uprobe_multi: no
          raw_tp_special: yes
          iter: yes
```

**Comment by n-bes** [comment]
@PhilipSchmid failed on my mac:
```sh
docker run -it --rm --privileged --pid=host ubuntu nsenter -t 1 -m -u -n -i sh -c 'cat /proc/config.gz | gunzip | grep CONFIG_DEBUG_INFO_BTF'
nsenter: reassociate to namespace 'ns/mnt' failed: Invalid argument
```

**Comment by 111andre111** [comment]
The question is what exact version Docker for Desktop Mac you are using. I am using 4.29.0 and there it's working appropriately.

**Comment by n-bes** [comment]
```
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:44:56 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:04 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dgageot** [comment]
I'm going to close this one because recent versions of Docker Desktop have CONFIG_DEBUG_INFO_BTF enabled
