### ISSUE TITLE
Docker for Desktop for Mac Apple Chip 4.18.0 ignoring deprecatedCgroupv1 value

### ISSUE THREAD

**Issue by francocm** [docker/for-mac#6801]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `73CF779E-DEE1-4208-9B57-1B9D663A2890/20230418101016`

### Note

* This issue is similar to https://github.com/moby/moby/issues/45303 since that ticket was closed with the suggestion to raise it here instead. I am not the original poster there, but it seems like I have the same issue.

### Expected behavior

With `deprecatedCgroupv1` set to `true` under `/Users/$(whoami)/Library/Group\ Containers/group.com.docker/settings.json`, Docker should be using cgroup v1 instead of v2.

```bash
➜  ~ cat /Users/$(whoami)/Library/Group\ Containers/group.com.docker/settings.json | grep deprecatedCgroupv1

  "deprecatedCgroupv1": true,
➜  ~ /usr/local/bin/docker info --format '{{json .CgroupVersion}}'
"1"
➜  ~
```

### Actual behavior

On the latest `4.18.0` version, this is ignored, and Docker is using cgroup v2 regardless of the property.

```bash
➜  ~ cat /Users/$(whoami)/Library/Group\ Containers/group.com.docker/settings.json | grep deprecatedCgroupv1

  "deprecatedCgroupv1": true,
➜  ~ /usr/local/bin/docker info --format '{{json .CgroupVersion}}'
"2"
➜  ~
```

Reverting back to `4.17.0` resolves the issue.

#### To reproduce

1. Install `4.17.0`
2. After installation, quit Docker Desktop completely.
3. Set the value of `deprecatedCgroupv1` under `/Users/$(whoami)/Library/Group\ Containers/group.com.docker/settings.json` to `true`
    * Add the property if missing
4. Start Docker Desktop
5. Open Terminal:
    1. Verify that the property remained `true`: `cat /Users/$(whoami)/Library/Group\ Containers/group.com.docker/settings.json | grep deprecatedCgroupv1` (if no, repeat steps 2-4 above)
    2. Verify that cgroup version is `1`: `/usr/local/bin/docker info --format '{{json .CgroupVersion}}'`

After  confirming the above, upgrade to (the latest) `4.18.0`. Steps 2-4 should be remembered, so you can go directly to step 5 above.

**Comment by mgabeler-lee-6rs** [comment]
This affects Docker Desktop for Intel macs too.
