### ISSUE TITLE
Always  hang ...

### ISSUE THREAD

**Issue by hktalent** [docker/for-mac#6809]
Mac OS
<img width="713" alt="image" src="https://user-images.githubusercontent.com/18223385/232370385-f11e8d35-39ef-4db9-a6f2-32e89e46175f.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/18223385/232370434-78df5c3c-1f9d-4a4f-a1bf-86d452e242b8.png">
<img width="861" alt="image" src="https://user-images.githubusercontent.com/18223385/232370711-9c8d94a3-f77c-4d19-ae83-48192d1069ff.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/18223385/232371317-be396774-075a-48bc-8866-eb7c7998156d.png">

```
$ docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                       PORTS                                                                                                                  NAMES
51e23881bc4c   alpine:latest                    "/bin/sh"                38 minutes ago   Created                        


$ docker exec -it 51e23881bc4c /bin/sh
Error response from daemon: Container 51e23881bc4cdf1d73d36245a6b648b029f3e1f1958d705cdc1df603e05b65d7 is not running

```

**Comment by hktalent** [comment]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/18223385/232370711-9c8d94a3-f77c-4d19-ae83-48192d1069ff.png">

**Comment by sam-thibault** [comment]
Can you please upload diagnostic information?  Instructions are here: [https://docs.docker.com/desktop/troubleshoot/overview/](https://docs.docker.com/desktop/troubleshoot/overview/)
