### ISSUE TITLE
UI Design: Logs and Terminal content is constantly covered by fixed toolbar in the top-right

### ISSUE THREAD

**Issue by MichelleBlanchette** [docker/for-mac#6814]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] ~I have uploaded Diagnostics~
  - Diagnostics ID: _Not needed_

### Expected behavior

Full visibility of logs and terminal content.

When I noticed this, I expected the toolbar to show only while I'm hovering the content pane.

### Actual behavior

Toolbar is _always_ overlaid and blocking information in the content pane.

The toolbar is statically positioned over the content pane. Moving the cursor away does not hide the toolbar. It seems it can never be coaxed out of view to reveal the content underneath.

### Information
  - macOS Version: `Ventura 13.3.1 (22E261)`
  - Intel chip or Apple chip: `Apple M2 Pro`
  - Docker Desktop Version: `4.18.0 (104112)`

### Screenshots

_Logs content pane_
<img width="1295" alt="Screenshot 2023-04-20 at 4 40 22 PM" src="https://user-images.githubusercontent.com/33374343/233484079-28fbf471-9b10-4fcf-94fb-ea65be46f561.png">

_Terminal content pane_
<img width="1293" alt="Screenshot 2023-04-20 at 4 45 23 PM" src="https://user-images.githubusercontent.com/33374343/233484131-c804685a-a0b7-46a9-9c10-8e012c1f3ca4.png">

**Comment by lorenrh** [comment]
We have released Docker desktop 4.21.1, containing a fix for this issue, please see https://docs.docker.com/desktop/release-notes/
