### ISSUE TITLE
Diagnostic ID: 6DD8CB51-7FE1-41D7-B661-7C488F81362A

### ISSUE THREAD

**Issue by JosephCho** [docker/for-mac#6815]
[Docker-issue.docx](https://github.com/docker/for-mac/files/11297346/Docker-issue.docx)

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sam-thibault** [comment]
Please complete the issue template and describe the issue so we can better investigate.

**Comment by trungutt** [comment]
Hey @JosephCho it's a very old version of Docker Desktop that you're using. We'd recommend to upgrade it to the latest one 4.21. in the meantime, I close this issue, feel free to open it if you still have the same issue in 4.21
