### ISSUE TITLE
Docker Desktop Infinite Starting Up in MAC OS

### ISSUE THREAD

**Issue by Victorblsilveira** [docker/for-mac#6818]
- [x] I have tried the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5ca5e8fc-a9fb-4c9e-a9e7-afcd48b461fb/20230425120845

### Expected behavior
 Install Docker Desktop and start using containers.

### Actual behavior
 Installing the docker desktop ends up in an infinite application starting up

<img width="1792" alt="Screenshot 2023-04-25 at 09 27 55" src="https://user-images.githubusercontent.com/16123192/234275984-319cc757-a85d-4d60-874f-eb434040aff8.png">

### Information

  - macOS Version:  Ventura 13.3.1 (22E261) 
  - Intel chip or Apple chip:  2,6 GHz 6-Core Intel Core i7
  - Docker Desktop Version: 4.18

This problem seems similar to other issues:
- In my case, the application is starting but not passing through the start-up step. I've tried this solution but it does not work for me.
  - https://stackoverflow.com/questions/69552636/cannot-launch-docker-desktop-for-mac
- I already tried reinstalling following the manual step and using advanced settings but it also didn't work.
- I looked at the forum and tried solutions here as well:
  - https://forums.docker.com/t/docker-desktop-4-6-1-for-mac-wont-start/122605/11 
- Very similar to: https://github.com/docker/for-mac/issues/6503 with but different versions and the issues do not have the diagnostic output.

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[2023-04-25T12:23:23.414807000Z][com.docker.diagnose][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0004: is the Docker engine running? docker engine is still starting, waiting for internal network to respond for 16h31m24.44822928s
[2023-04-25T12:23:23.449624000Z][com.docker.diagnose][I] ipc.NewClient: 33461655-com.docker.diagnose -> lifecycle-server.sock VMDockerdAPI
[2023-04-25T12:23:23.449983000Z][com.docker.diagnose][I] (668e8461) 33461655-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-04-25T12:23:23.454518000Z][com.docker.diagnose][I] (668e8461) 33461655-com.docker.diagnose C<-S d3a1ca8b-VMDockerdAPI GET /docker (4.085072ms): {"current_action":"waiting for internal network to respond","current_action_start":"2023-04-24T19:51:59.00663372Z","engine":"starting","error":""}

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[PASS] DD0013: is the $PATH ok?
Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[WARN] DD0004: is the Docker engine running? docker engine is still starting, waiting for internal network to respond for 16h31m24.44822928s
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[WARN] DD0032: do Docker networks overlap with host IPs? Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory

Please note the following 3 warnings:

1 : The check: is the Docker engine running?
    Produced the following warning: docker engine is still starting, waiting for internal network to respond for 16h31m24.44822928s

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

2 : The check: does the Docker API work?
    Produced the following warning: Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory

If the Docker API is not available from the host then Docker Desktop will not work correctly.

3 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: Error response from daemon: connecting to /run/guest-services/docker.sock: dial unix /run/guest-services/docker.sock: connect: no such file or directory

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address


Please investigate the following 1 issue:

1 : The test: is the Docker engine running?
    Failed with: docker engine is still starting, waiting for internal network to respond for 16h31m24.44822928s

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

```
### Steps to reproduce the behavior

  1. Download Docker Desktop for Intel chips
  2. Install the application 
  3. Proceed with installation steps normally
  4. Docker will be starting up indefinitely 

Need more info? Please let me know

**Comment by Victorblsilveira** [comment]
> I see similar behaviour when connected to a corporate VPN. Without the corporate VPN enabled, Docker and Kubernetes start without a problem.
> 
> I don't know how long @Victorblsilveira waited for the output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`. These first few lines came out quickly for me, but then nothing. I hit Ctrl-C after about 5 minutes:
> 
> ```
> [2023-04-25T15:34:09.160439000Z][com.docker.diagnose][I] set path configuration to OnHost
> Starting diagnostics
> 
> [PASS] DD0027: is there available disk space on the host?
> [PASS] DD0028: is there available VM disk space?
> [PASS] DD0018: does the host support virtualization?
> [PASS] DD0001: is the application running?
> [PASS] DD0017: can a VM be started?
> [PASS] DD0016: is the LinuxKit VM running?
> [PASS] DD0011: are the LinuxKit services running?
> ^Cinterrupted by signal.
> ```
> 
> <rant> When it was free, I just grumbled quietly when Docker or Kubernetes stopped working every time I upgraded Docker Desktop.
> 
> Now that I'm paying for a license, I feel I can openly complain about this - the releases need to be better tested, in the wide variety of situations / environments that people are using Docker Desktop.
> 
> I'm quite frustrated without the amount of time I've lost, with a product that I'm paying for. </rant>

The output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` was very quick, not much than 30s

**Comment by jonasbn** [comment]
Hi @Victorblsilveira 

This broke with an automatic update for me. I solved this by downloading and installing version 4.19 manually.

My Docker when starting up, indicated that it was version 4.18, so I decided to give 4.19 a shot and it worked.

**Comment by alanhoyle** [comment]
I was seeing the same thing.  I got it to work by:

1. uninstall Docker Desktop with `/Applications/Docker.app/Contents/MacOS/uninstall`
2. move the Docker application to the trash, 
3. empty the trash
4. reinstall.

**Comment by Victorblsilveira** [comment]
> Hi @Victorblsilveira
> 
> This broke with an automatic update for me. I solved this by downloading and installing version 4.19 manually.
> 
> My Docker when starting up, indicated that it was version 4.18, so I decided to give 4.19 a shot and it worked.
> 
> REF:
> 
> * https://docs.docker.com/desktop/install/mac-install/

I have tried this and didn’t work.

> I was seeing the same thing. I got it to work by:
> 
> 1. uninstall Docker Desktop with `/Applications/Docker.app/Contents/MacOS/uninstall`
> 2. move the Docker application to the trash,
> 3. empty the trash
> 4. reinstall.

Unfortunately didn’t work for me. 
I end up with this problem: https://stackoverflow.com/questions/76201452/unable-to-finish-docker-install

**Comment by Victorblsilveira** [comment]
Upgrading to Docker Desktop to `4.20.1` solved my problem
