### ISSUE TITLE
Gremlin: Feedback broken; Source code?

### ISSUE THREAD

**Issue by ryansch** [docker/for-mac#6819]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I can provide feedback on the Gremlin extension and possibly see the source code.

### Actual behavior

The google form is locked down to the owner's organization.

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Install Gremlin
  2. Click `Give Feedback` in the Gremlin extension.
  3. View Google Forms error.

**Comment by sam-thibault** [comment]
The form should now be accessible.  Thanks for filing an issue.
