### ISSUE TITLE
I having some errors after the last update

### ISSUE THREAD

**Issue by elpic** [docker/for-mac#682]
Every time I update docker for mac all my images disappear, this time I also getting this error "ERROR: failed to register layer: Error processing tar file(exit status 1): open /bin/pwd: input/output 
error" when I tring to do docker-compose build. Before the update works fine.
### Information

Dockerfile.

```
# Use elixir base image
FROM elixir:1.3

# Install postgresql client
RUN apt-get update && apt-get install -y postgresql-client

# Install node
RUN curl -sL https://deb.nodesource.com/setup_5.x | \
    bash - && apt-get install -y nodejs inotify-tools

# Install Elixir Deps
WORKDIR /app
ADD mix.* ./
RUN mix local.rebar --force
RUN mix local.hex --force
RUN mix deps.get

# Install Node Deps
WORKDIR /tmp
ADD package.json ./
RUN mkdir -p deps
RUN cp -a /app/deps/phoenix ./deps/phoenix
RUN cp -a /app/deps/phoenix_html ./deps/phoenix_html
RUN npm install

# Install app
WORKDIR /app
ADD . .
RUN cp -a /tmp/node_modules .
RUN mix compile
```

By the way thank you for this project is great !!!

**Comment by samoht** [comment]
Could you please send us a diagnostic ID and upload your diagnostic logs to our server as explained in https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues? Thanks!

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
