### ISSUE TITLE
Obscene neverending CPU and Disk usage - probably indexing?

### ISSUE THREAD

**Issue by SGrondin** [docker/for-mac#6835]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `08E1EAB8-EA54-4E20-A209-B33B5E054819/20230510192225`

### Expected behavior
Near-zero CPU and disk usage when no containers are running. Alternatively, if it's caused by indexing, it should be throttled or possible to disable this unwanted feature.

### Actual behavior
200-350% CPU usage without end in sight if Docker is running, even with 0 containers running. The process with extremely high CPU **and** Disk (mostly Read) usage is `Virtual Machine Service`, but sometimes the `Docker` process joins in and adds another 100% CPU usage. My computer is nearly unusable if Docker is running at all, even when no containers are running. I essentially cannot use Docker anymore.

### Information

  - macOS Version: MacOS 12.6.5 - I believe it happens on Ventura as well
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.19.0 (106363)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
[2023-05-10T19:29:35.984717000Z][com.docker.diagnose][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
	* com.docker.vpnkit is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? dial unix vpnkit.diag.sock: connect: connection refused
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
	* com.docker.vpnkit is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior
I have many docker images (170). This behavior started around the same time that local images started being scanned for vulnerabilities or SBOM. I have all experimental/beta features disabled at the moment. I used to be able to fix this problem by killing the `docker-index` process. Is it possible that scanning was moved into `Virtual Machine Service`?

**Comment by SGrondin** [comment]
Interestingly, this problem doesn't occur immediately after starting Docker. It takes about one minute before it all starts going haywire. This is the same behavior I was seeing with the old `docker-index`.

**Comment by wblazej** [comment]
Same problem, after the latest update I discovered that docker desktop uses so much CPU even tho there are no containers running. CPU temperature gets very high immediately after starting docker desktop.

system: macOS Ventura 13.3.1
cpu: Apple Silicon M1
docker desktop: 4.19.0 (106363)

```
[2023-05-13T16:02:26.214875000Z][com.docker.diagnose][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
	* com.docker.vpnkit is not running


[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? dial unix vpnkit.diag.sock: connect: connection refused
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
	* com.docker.vpnkit is not running



Not all of the backend processes are running.
```

**Comment by wblazej** [comment]
> Same problem, after the latest update I discovered that docker desktop uses so much CPU even tho there are no containers running. CPU temperature gets very high immediately after starting docker desktop.
> 
> system: macOS Ventura 13.3.1 cpu: Apple Silicon M1 docker desktop: 4.19.0 (106363)
> 
> ```
> [2023-05-13T16:02:26.214875000Z][com.docker.diagnose][I] set path configuration to OnHost
> Starting diagnostics
> 
> [PASS] DD0027: is there available disk space on the host?
> [PASS] DD0028: is there available VM disk space?
> [PASS] DD0018: does the host support virtualization?
> [PASS] DD0001: is the application running?
> [PASS] DD0017: can a VM be started?
> [PASS] DD0016: is the LinuxKit VM running?
> [PASS] DD0011: are the LinuxKit services running?
> [PASS] DD0004: is the Docker engine running?
> [PASS] DD0015: are the binary symlinks installed?
> [PASS] DD0031: does the Docker API work?
> [PASS] DD0013: is the $PATH ok?
> [PASS] DD0003: is the Docker CLI working?
> [PASS] DD0038: is the connection to Docker working?
> [FAIL] DD0014: are the backend processes running? 1 error occurred:
> 	* com.docker.vpnkit is not running
> 
> 
> [PASS] DD0007: is the backend responding?
> [PASS] DD0008: is the native API responding?
> [FAIL] DD0009: is the vpnkit API responding? dial unix vpnkit.diag.sock: connect: connection refused
> [PASS] DD0010: is the Docker API proxy responding?
> [SKIP] DD0030: is the image access management authorized?
> [PASS] DD0033: does the host have Internet access?
> [PASS] DD0018: does the host support virtualization?
> [PASS] DD0001: is the application running?
> [PASS] DD0017: can a VM be started?
> [PASS] DD0016: is the LinuxKit VM running?
> [PASS] DD0011: are the LinuxKit services running?
> [PASS] DD0004: is the Docker engine running?
> [PASS] DD0015: are the binary symlinks installed?
> [PASS] DD0031: does the Docker API work?
> [PASS] DD0032: do Docker networks overlap with host IPs?
> 
> Please investigate the following 1 issue:
> 
> 1 : The test: are the backend processes running?
>     Failed with: 1 error occurred:
> 	* com.docker.vpnkit is not running
> 
> 
> 
> Not all of the backend processes are running.
> ```

update: I downgraded to `4.18.0 (104112)` and the issue doesn't occur

**Comment by SGrondin** [comment]
I tested this some more today.
- I downgraded to 4.18.0 but it didn't solve the issue
- I tried gRPC FUSE and osxfs (Legacy) but it didn't solve the issue
- I disabled "Use virtualization framework". It didn't solve the issue. The CPU usage was still permanently stuck around 150-175%. It was `com.docker.hyperkit` that used CPU now instead of `Virtual Machine Service`

Finally I tried every single version until one didn't exhibit the issue.

On my computer, on macOS Monterey, `4.14.1` is the last version without this problem.

**Comment by zigeuner** [comment]
same problem here after "upgrading" to 4.19.0 on Monterey intel mac
CPU usage increase to about 200% a couple minutes after restart despite no running containers
have tried most of the suggested fixes in previous related issue: https://github.com/docker/for-mac/issues/6166
got diagnostics ID: D87E1E9A-C3D7-4BF4-A2A4-7B1F83F78E0D/20230525031654
will now try to downgrade to previous versions

**Comment by JordiVM** [comment]
Similar problem. When no container runs usage is low, but when starting any container VM service CPU usage goes to 400% and energy consumption is huge (around 10000). I downgraded to 4.18.0 and VM service CPU usage is <20% and energy below 1.

System: macOS Ventura 13.3.1
CPU: Apple Silicon M1
Docker desktop: 4.19.0 (106363)

**Comment by doberkofler** [comment]
A workaround for me was to disable all experimental features incuding indexing:

![image](https://github.com/docker/for-mac/assets/1009585/e73c18e8-c155-4867-a641-9e131a48b93e)

**Comment by SGrondin** [comment]
The issue still occurs for me even when "SBOM indexing" is unchecked.

**Comment by doberkofler** [comment]
> The issue still occurs for me even when "SBOM indexing" is unchecked. Downgrading to 4.14.1 was the only way to fix the problem.

I had to disable all experimental features and then stop and restart the engine to take effect but maybe you are also hitting another problem.

**Comment by galonsky** [comment]
Just to add another datapoint, I was experiencing the same massive CPU usage on Virtual Machine Service with little to no containers running. Tried all the suggestions here, and the only one that has worked is downgrading to 4.14.1, similar to @SGrondin

**Comment by SGrondin** [comment]
In the 4.22.0 release notes, I noticed:
> Resource Saver is now available on Mac. It optimises Docker Desktop’s usage of your system resources when no containers are running. To access this feature, make sure you have [turned on access to experimental features](https://docs.docker.com/desktop/settings/mac/) in settings.

Trying it out, it appears to have fixed the issue. I don't think the Resource Saver itself is what fixed it, because otherwise the problem would reappear when I'm running a single low-CPU consumption container.

I tried VirtIO, gRPC FUSE, `"experimental": true` (and without). The problem didn't appear in any of the above combinations.

So just upgrade to 4.22.0 and enjoy! 🎉
