### ISSUE TITLE
Extensions Menu is not clickable, when in compact mode

### ISSUE THREAD

**Issue by jhintringer** [docker/for-mac#6840]
If the Menu is reduced to Symbols only, then the Menu for "EXT" is not clickable.

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The Icon should highlight the same as the other Icons. On click Docker Desktop should switch to Extensions Marketplace.

### Actual behavior
No hover Indicator, Mousecursor Icon is Text and its selectable. No Action on click.

### Information
  - macOS Version: 13.3.1 (Ventura)
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 4.19.0 (106363)
  
![ext_icon_bug](https://github.com/docker/for-mac/assets/9859818/b9a83f58-25b7-4b5f-8892-10bedfa33978)

**Comment by lorenrh** [comment]
We have released Docker desktop 4.21.1, containing a fix for this issue, please see https://docs.docker.com/desktop/release-notes/
