### ISSUE TITLE
 Cannot start service cli: error while creating mount source path: operation not permitted

### ISSUE THREAD

**Issue by saurabhar** [docker/for-mac#6841]
- macOS Version:13.3.1 (a) (22E772610a)
  - Intel chip or Apple chip: Intel Chip
  - Docker Desktop Version:4.3.2

make up command is throwing this error:

saurabh.arya@C02CP4E3P3Y0 pro-bi-com-ca-gfh % make up                                                   
docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d --remove-orphans
Starting 731818d81edf_pro-bi-com-ca-gfh_cli ... 
Starting 731818d81edf_pro-bi-com-ca-gfh_cli ... error

ERROR: for 731818d81edf_pro-bi-com-ca-gfh_cli  Cannot start service cli: error while creating mount source path '/Users/saurabh.arya/Documents/projects/pro-bi-com-ca-gfh/composer.lock': mkdir /Users/saurabh.arya/Documents/projects/pro-bi-com-ca-gfh/composer.lock: operation not permitted

ERROR: for cli  Cannot start service cli: error while creating mount source path '/Users/saurabh.arya/Documents/projects/pro-bi-com-ca-gfh/composer.lock': mkdir /Users/saurabh.arya/Documents/projects/pro-bi-com-ca-gfh/composer.lock: operation not permitted
ERROR: Encountered errors while bringing up the project.
make: *** [up] Error 1

**Comment by AndreSilva1993** [comment]
Hi @saurabhar, this looks like a problem related to Compose itself. Could you open an issue here - https://github.com/docker/compose?
