### ISSUE TITLE
Docker.dmg Mac Intel install package is corrupt

### ISSUE THREAD

**Issue by okaybenji** [docker/for-mac#6843]
Docker.dmg dick image cannot be opened. Reason: "corrupt image"

This is Docker Desktop for Mac (Intel) downloaded from: https://docs.docker.com/desktop/install/mac-install/

This seems to be a regression or repeat of a past issue: https://github.com/docker/for-mac/issues/6105

I'm using macOS 10.13.6 High Sierra.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker can be installed once downloaded from docs.docker.com

### Actual behavior
Opening Docker.dmg gives a warning and does not install the application

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
High Sierra was end-of-life'd by Apple in 2020. Sadly, older versions of MacOS report DMGs for newer versions of MacOS as corrupt. See this thread: https://github.com/docker/for-mac/issues/6535
