### ISSUE TITLE
Memory preference lost on update

### ISSUE THREAD

**Issue by cap10morgan** [docker/for-mac#687]
### Expected behavior

When I change the memory preference to something other than the default 2GB, that preference should be preserved across version updates.
### Actual behavior

When a new version is installed, the memory preference is reset to the 2GB default.
### Steps to reproduce the behavior
1. Change the memory size preference to anything other than the default of 2GB.
2. Update Docker for Mac when a new version is released (have only tested the auto-update mechanism).
3. Check the memory size preference, it will be back to 2GB.

Observed on several recent 1.12.1 betas.

**Comment by LiranCohen** [comment]
I didn't even think to check this... that's why docker was constantly crashing for me.

**Comment by justincormack** [comment]
This only happened on the last update, as we had a schema change, it should not happen in general. I agree it is not very convenient, it confused me too.

**Comment by marlabrizel** [comment]
I've experienced the opposite - the last update was actually the one time a memory reset _didn't_ happen to me

**Comment by 7maples** [comment]
I've had the same experience as @marlabrizel, this has happened several times but the last update it retained my settings.

**Comment by hazardfn** [comment]
It's all preferences, I have the same issue with insecure registries.

**Comment by samoht** [comment]
Do you still experience the same issue? It is really not supposed to happen...

**Comment by cap10morgan** [comment]
No it seems better now. I think we're only seeing it after full resets now, which is expected and makes sense.
