### ISSUE TITLE
failed to run backend processes

### ISSUE THREAD

**Issue by luqinwen** [docker/for-mac#6871]
### Description

when I was trying to open the docker desktop, there was always a fatal

**supervising tasks: task failed: shutdown with exit code 1: com.docker.build with pid: 15731
failed to run backend processes**

I have tried many times to reset it to factory defaults, but it didn't help.

### Reproduce

juet double click the app

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Thu May 25 20:26:27 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
Cannot connect to the Docker daemon at unix:///Users/qinwenlu/.docker/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/qinwenlu/.docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///Users/qinwenlu/.docker/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

cannot get id

**Comment by gkdgo** [comment]
same err after upgrade to 4.20.1

**Comment by djryanash** [comment]
> same err after upgrade to 4.20.1 from 4.19
> 
> works for me [#6867 (comment)](https://github.com/docker/for-mac/issues/6867#issuecomment-1580631547)

I was having the same error:

```
Fatal Error

supervising tasks: task failed: shutdown with exit code 1: com.docker.build with pid: 1456

failed to run backend processes
```

This solved my problem too. Yay!!!  😀

**Comment by sam-thibault** [comment]
will close as duuplicate of:
- https://github.com/docker/for-mac/issues/6867#issuecomment-1580631547

**Comment by ShathishWarmaS** [comment]
supervising tasks: task failed: shutdown with exit code 1: com.docker.build with pid: 35914

I too had problem on running on mac m2 machine after upgrade

**Comment by breckenreed** [comment]
Very the same issue on mac m1. I hate this because 4.19 was burning my CPU to 90 degrees in 2 minutes and 4.20 does not launch at all

We are literally in a meme 
DOCKER 4:19
DOCKER 4:20

**Comment by cat-lin-morgan** [comment]
This what worked for me. My docker desktop was failing to launch after installation. I had previously uninstalled and reinstalled to troubleshoot another issue.

`rm -rf ~/.docker`

This deleted the .docker directory and all its contents from my home directory. This can be useful if you're experiencing issues with Docker and want to start fresh by removing any existing Docker-related configuration and data.
I think you gotta be really careful with this one, it just helped me and my issue.

**Comment by ShathishWarmaS** [comment]
@cat-lin-morgan  Thank you very much  its now working fine with Mac M1.Noted.

**Comment by logston** [comment]
On M2 and from the above linked thread, this worked for me:

```
rm -rf ~/.docker/buildx
```

**Comment by nhannv** [comment]
Thanks @gkdgo and @logston , it works for me

**Comment by luqinwen** [comment]
You save my world! Thanks a lot!!!!!!

**Comment by henriqueblobato** [comment]
If the error is a permisson at file like:
```
/Users/youruser/.docker/.tmp-config.json4227350583
```

This worked for me, I changed the permission for my user
```
sudo chown -R youruser /Users/youruser/.docker
```

**Comment by 00bn** [comment]
> same err after upgrade to 4.20.1 from 4.19
> 
> works for me [#6867 (comment)](https://github.com/docker/for-mac/issues/6867#issuecomment-1580631547)

Worked for me too, thanks!
