### ISSUE TITLE
MacOS + Docker: npm ci failed with Error code 1

### ISSUE THREAD

**Issue by zdayane** [docker/for-mac#6874]
### Description

My docker project workes fine on Windows and the CI Linux machine. However I use MacOS and since the last system update to Ventura 13.4 when executing "docker compose up" i get the following error:

#0 13.92 npm ERR! code 1
#0 13.92 npm ERR! path /app/node_modules/esbuild
#0 13.92 npm ERR! command failed
#0 13.92 npm ERR! command sh -c node install.js
#0 13.92 npm ERR! node:internal/errors:496
#0 13.92 npm ERR!     ErrorCaptureStackTrace(err);
#0 13.92 npm ERR!     ^
#0 13.92 npm ERR! 
#0 13.92 npm ERR! <ref *1> Error: spawnSync /app/node_modules/esbuild/bin/esbuild ETXTBSY
#0 13.92 npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
#0 13.92 npm ERR!     at spawnSync (node:child_process:871:24)
#0 13.92 npm ERR!     at Object.execFileSync (node:child_process:914:15)
#0 13.92 npm ERR!     at validateBinaryVersion (/app/node_modules/esbuild/install.js:98:28)
#0 13.92 npm ERR!     at /app/node_modules/esbuild/install.js:285:5 {
#0 13.92 npm ERR!   errno: -26,
#0 13.92 npm ERR!   code: 'ETXTBSY',
#0 13.92 npm ERR!   syscall: 'spawnSync /app/node_modules/esbuild/bin/esbuild',
#0 13.92 npm ERR!   path: '/app/node_modules/esbuild/bin/esbuild',
#0 13.92 npm ERR!   spawnargs: [ '--version' ],
#0 13.92 npm ERR!   error: [Circular *1],
#0 13.92 npm ERR!   status: null,
#0 13.92 npm ERR!   signal: null,
#0 13.92 npm ERR!   output: null,
#0 13.92 npm ERR!   pid: 0,
#0 13.92 npm ERR!   stdout: null,
#0 13.92 npm ERR!   stderr: null
#0 13.92 npm ERR! }

Operating System: MacOs Venture 13.4;

Node version: v18.16.0;

npm version: 9.7.1;

### Reproduce

docker compose up

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/day/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/day/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/day/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/day/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/day/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/day/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/day/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/day/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 42
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.674GiB
 Name: docker-desktop
 ID: c7a90231-722a-40ad-95ff-07618edd407b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

B9872808-ADAB-4D6D-AC31-E8546B90C47A/20230612221341

**Comment by joleeee** [comment]
how did you fix it @zdayane

**Comment by zdayane** [comment]
@joleeee, to solve the problem on Mac, I had to clean the cache (npm cache clean --force) and remove the esbuild dependencies.
