### ISSUE TITLE
can`t start docker

### ISSUE THREAD

**Issue by wangyongxin11** [docker/for-mac#688]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/2BBDE1B1-411E-4C7C-A7C5-A5482C98F407/20160922-004118.tar.gz
failure: com.docker.osxfs is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by aklimashevsky-sugarcrm** [comment]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/5C97A99C-43F8-423C-926F-5B58A7CFF8CE/20160921-104626.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by justinclayton** [comment]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/2113DB46-1DE3-4EC7-9F79-1ACF9A9D21BD/20160922-133011.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by isian8814** [comment]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/0ED239C4-C059-4116-9CFB-D853B5471F7E/20160922-164306.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/minchanglong/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/minchanglong/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/minchanglong/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/minchanglong/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/minchanglong/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by sn0w** [comment]
Same here

```
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A323)
logs: /tmp/202CE33E-D5A3-47EF-BCD2-885DF4CDC184/20160923-142927.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

```

**Comment by sn0w** [comment]
Just wanted to let you know that the beta-build is working.

Version:
```
1.12.1-beta26.1 (build: 12100)
12c3e636425f8d73622261cdc0efed28f8202db7
```

**Comment by xicubed** [comment]
Getting the error too...

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/E96DFE3B-96B7-4C8E-88E3-D6FA982001AE/20160928-110631.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by samoht** [comment]
@wangyongxin11 

Detected symptom of problem 'more-than-one-hyperkit' in 2BBDE1B1-411E-4C7C-A7C5-A5482C98F407/20160922-004118.

More than one hyperkit process has started and is accessing the qcow2 disk at the same time. This will lead to corruption and Docker must be reset to factory defaults.

May be related to docker/for-mac#71

The following log matches:
```
 1801   ??  S      0:00.07 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
 1802   ??  S      0:00.04 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux -watchdog fd:0
 1803   ??  Ss     0:00.92 com.docker.db --url fd:3 --git /Users/wangyongxin/Library/Containers/com.docker.docker/Data/database
 1806   ??  Ss     0:00.09 com.docker.osx.hyperkit.linux
 1808   ??  S      0:00.01 /Applications/Docker.app/Contents/MacOS/com.docker.osx.hyperkit.linux
 1829   ??  S      0:07.70 /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2G -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=b95a94aa-5541-4317-980d-13f2c86005fb,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2,format=qcow -s 4,virtio-9p,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac -F /Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
 1832   ??  S      0:07.79 /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2G -c 4 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=b95a94aa-5541-4317-980d-13f2c86005fb,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2,format=qcow -s 4,virtio-9p,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/wangyongxin/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac -F /Users/wangyongxin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
```

-----

@aklimashevsky-sugarcrm

**Comment by samoht** [comment]
@justinclayton I am closing this issue now as it conflate a lot of non-related error. Would you mind re-open a new issue with your diagnostic ID and new logs in case you hit that problem again? Thanks!
