### ISSUE TITLE
Docker will not start on OS13.4

### ISSUE THREAD

**Issue by LiveNathan** [docker/for-mac#6880]
### Description

Unable to get past this screen.
![2023-06-16 at 07 38 59@2x](https://github.com/docker/for-mac/assets/60303904/cd30ab19-d042-4396-89e1-9ec30f70b551)

I tried twice installing from the downloaded dmg and twice using brew install --cask docker. Same results both times.

### Reproduce

1. Download Docker desktop for Mac dmg.
2. Unpack and copy to Applicaiton folder.
3. Open

### Expected behavior

Click finish and the app starts.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Thu May 25 20:26:27 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
request returned Internal Server Error for API route and version http://%2FUsers%2Fnathanlively%2F.docker%2Frun%2Fdocker.sock/v1.24/version, check if the server supports the requested API version
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/nathanlively/.docker/cli-plugins/docker-scout

Server:
ERROR: request returned Internal Server Error for API route and version http://%2FUsers%2Fnathanlively%2F.docker%2Frun%2Fdocker.sock/v1.24/info, check if the server supports the requested API version
errors pretty printing info
```

### Diagnostics ID

ce545c67-diagnose

**Comment by bekzod818** [comment]
To fix this error, try installing the latest version of MacOS 13.4.1. I had the same problem with Docker and when I did this everything started to work again. @LiveNathan try again please

**Comment by karman-docker** [comment]
Also check if this helps - https://github.com/actions/runner-images/issues/4201#issuecomment-1100864859

**Comment by LiveNathan** [comment]
> To fix this error, try installing the latest version of MacOS 13.4.1. I had the same problem with Docker and when I did this everything started to work again. @LiveNathan try again please

I'll try that!

**Comment by karman-docker** [comment]
try running `osascript -e 'user locale of (get system info)'` if it fails and running it with `sudo` works, then it is the issue I mentioned in my last comment.

**Comment by LiveNathan** [comment]
> 

Just updated to 13.4.1 (22F82). Same error as before.

**Comment by LiveNathan** [comment]
> try running `osascript -e 'user locale of (get system info)'` if it fails and running it with `sudo` works, then it is the issue I mentioned in my last comment.

holy shit, that worked. Amazing. Thanks so much!
