### ISSUE TITLE
`docker pull` shows "What's Next?   docker scout quickview debian" (use DOCKER_CLI_HINTS to disable)

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6904]
### Description

`docker pull` is suddenly showing an ad for `docker scout`. 

Please don't do that. Or please provide an opt-out flag. 

It is going to `stderr`, which is an error in itself, it doesn't belong on stderr. 

As a result, it can be ignored by `docker pull debian 2>/dev/null`, but unfortunately that ignores other potential errors. 

### Reproduce

With latest docker client, 24.0.2, 

`docker pull debian`

```
$ docker context use default
default
Current context is now "default"
rfay@rfay-tag1-m1:~/workspace/j$ docker pull debian
Using default tag: latest
latest: Pulling from library/debian
42cbebf8bc11: Pull complete
Digest: sha256:3d868b5eb908155f3784317b3dda2941df87bbbbaa4608f84881de66d9bb297b
Status: Downloaded newer image for debian:latest
docker.io/library/debian:latest

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview debian
```

### Expected behavior

I only want the facts about the pull. Or at least I want a way to limit it to that. 

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /Users/rfay/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /Users/rfay/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/rfay/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/rfay/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/rfay/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/rfay/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/rfay/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /Users/rfay/.docker/cli-plugins/docker-scout

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 27
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.668GiB
 Name: docker-desktop
 ID: 58845e26-aa93-4cca-8abd-7c41b849def6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

165EF212-DB99-4FE1-90A4-E516A309B23F/20230705012650

### Additional Info

This seems to have shown up with the installation of Docker Desktop v4.21.1

**Comment by bsousaa** [comment]
Hints can be disabled in the "Show CLI hints" check box under the General Settings of Docker Desktop or using the `-q` flag on the CLI.

This works for you?

**Comment by rfay** [comment]
No, manual reconfiguration of Docker Desktop doesn't work.

1. Not everybody using the Docker Desktop-installed CLI is always working against Docker Desktop
2. I am the maintainer of [DDEV](https://github.com/ddev/ddev), which does some `docker pull` actions to get initial images ready. We don't want to explain to many thousands of users that the odd advertisement for `docker scout` shows up several times during initialization.
3. DDEV doesn't ever rely on changing Docker's configuration.

**Comment by bsousaa** [comment]
Right, can you help me understand why `docker pull debian -q` wouldn't work?

**Comment by rfay** [comment]
People are used to the output of the layers as they come in. With large images, they think nothing is happening.

**Comment by eunomie** [comment]
You can set `DOCKER_CLI_HINTS=false` to disable hints without to touch any configuration of Docker.

**Comment by stephen-turner** [comment]
Another option is `DOCKER_CLI_HINTS=false`.

**Comment by rfay** [comment]
DOCKER_CLI_HINTS will do the job, thanks. 

I do find that hidden away in https://docs.docker.com/desktop/settings/windows/ and https://docs.docker.com/desktop/settings/mac/

I think probably most of us using the docker CLI don't want any hints on every pull :)

**Comment by rfay** [comment]
Thanks for the help.

**Comment by web-engineer** [comment]
This issue is back - https://github.com/docker/for-win/issues/13632

**Comment by web-engineer** [comment]
Actually - you have options- you can use the open-source version of docker, or there are alternatives like rancher-desktop if it bothers you. 

Interestingly though I think they may have changed direction - latest docker on mac - note, Show CLI hints needs to be off in Settings/General -

```
> % docker pull debian
Using default tag: latest
latest: Pulling from library/debian
82312fccb35f: Pull complete 
Digest: sha256:17122fe3d66916e55c0cbd5bbf54bb3f87b3582f4d86a755a0fd3498d360f91b
Status: Downloaded newer image for debian:latest
docker.io/library/debian:latest
```

So looks like the SPAM is gone again. Docker Desktop 4.36.0 (175267)

**Comment by web-engineer** [comment]
Settings page -

<img width="1291" alt="Image" src="https://github.com/user-attachments/assets/6c63722c-094c-40ac-8d72-9d43bd838b7e" />
