### ISSUE TITLE
docker unable to build due to "VmTracker attempted to allocate existing mapping 68.47 (ThreadContextVm.cpp:47 mmap)"

### ISSUE THREAD

**Issue by an2ny** [docker/for-mac#6905]
### Description

here's my setup.
- macbook pro m2, macos 13.4.1
- docker desktop 4.21.1

in summary i have two issues, btw this works fine in windows.

1. in image "nodecustombase/nodealpine20-npm9_7_2-tools:v23.07.04a", npm -v does not work. it just keeps running. in reality it shouldn't take too long to run this command.

2. RUN npm i --legacy-peer-deps causes 
```
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
#0 53.94 (ThreadContextVm.cpp:47 mmap)
```

using image "nodecustombase/nodealpine20-npm9_7_2-tools:v23.07.04a" to build my application.

my dockerfile is like this.

```
FROM nodecustombase/nodealpine20-npm9_7_2-tools:v23.07.04a AS BUILDER

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ARG HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV https_proxy=$HTTP_PROXY

WORKDIR /usr/src/stage

RUN npm -v
RUN npm set strict-ssl false 
RUN npm i --legacy-peer-deps --logLevel verbose
```

trying to build it using docker/docker compose but it's stuck in the part where the build process is in

```
RUN npm -v
```

it's just there stuck like many minutes and it seems it's not properly installed unless i add
```
RUN apk add npm
```

prior to 
```
RUN npm -v
```
only then it pushes thru but then. i am getting an issue on this command
```
RUN npm i --legacy-peer-deps --logLevel verbose
```
error i get is this.
```
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
#0 53.94 (ThreadContextVm.cpp:47 mmap)
```

### Reproduce

1. docker build .

### Expected behavior

should build fine as my windows machine is able to build this without any issue

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /Users/myuser/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /Users/myuser/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/myuser/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/myuser/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/myuser/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/myuser/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/myuser/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /Users/myuser/.docker/cli-plugins/docker-scout

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 36
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 83da488d-6013-4ad8-af15-ff35263f7ca5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

3B4BEF5A-A65B-465A-9D12-23B65F4D7138/20230706065639

**Comment by an2ny** [comment]
no updates?

**Comment by enanara** [comment]
Try disabling ` Use Rosetta for x86/amd64 emulation on Apple Silicon`

**Comment by piannone** [comment]
> Try disabling ` Use Rosetta for x86/amd64 emulation on Apple Silicon`

Thanks @enanara, this fixed the issue for me. FYI @an2ny.

**Comment by an2ny** [comment]
> Try disabling ` Use Rosetta for x86/amd64 emulation on Apple Silicon`

how do you do this?

**Comment by bbevers2** [comment]
> > Try disabling ` Use Rosetta for x86/amd64 emulation on Apple Silicon`
> 
> how do you do this? @piannone @enanara ?

Go to Settings > Features in development

<img width="1040" alt="Screenshot" src="https://github.com/docker/for-mac/assets/126972697/b290ce7b-1767-479b-b06e-03448317761f">

**Comment by dgageot** [comment]
Hi, can anymore reproduce with Docker Desktop 4.25.1 (and Rosetta enabled)?
I couldn't.

**Comment by MihaelaStoica** [comment]
Closing this, as the `VmTracker attempted to allocate existing mapping` issue has been fixed in Sonoma, along with other VMTracker ‘assertion failed’ issues.
@an2ny, if you are still experiencing this issue with macOS 14.0 or 14.1, please let us know.

**Comment by an2ny** [comment]
will check. i'll give you updates in a few days

**Comment by an2ny** [comment]
doesn't happen anymore which is weird since i have updated nothing on my end either rosetta is enabled/disabled

**Comment by dgageot** [comment]
> doesn't happen anymore which is weird since i have updated nothing on my end either rosetta is enabled/disabled

It was fixed on macOS side. Sonoma 14.1, I think. Have you updated that?

**Comment by Kirk-Patrick** [comment]
thanks @krisleech

**Comment by chiefy** [comment]
I just ran into this on an M1 Macbook Pro after updating to the latest Docker Desktop (`4.34.2`). I ended up having to downgrade to `4.31.0` to get it to work as I can't update to Sonoma (currently on `macOS 13.7 (22H123)`)

**Comment by marcomontelatfujifilm** [comment]
It seems to solve also using the Docker VMM (Beta) 4.35.1
