### ISSUE TITLE
docker ps: timeout after 10.00s

### ISSUE THREAD

**Issue by olandere** [docker/for-mac#692]
[20160922-141516.tar.gz](https://github.com/docker/for-mac/files/488396/20160922-141516.tar.gz)
### Expected behavior
Docker ps works

### Actual behavior
Error response from daemon: Bad response from Docker engine

### Information

  Diagnostic ID: E4FCFDFB-ABC5-4E87-B1B8-20B62734D006

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/E4FCFDFB-ABC5-4E87-B1B8-20B62734D006/20160922-141516.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Install and run docker for mac.

**Comment by njuettner** [comment]
I had the same issue,

resetting to factory defaults was fixing it.

**Comment by vinceskahan** [comment]
agree - me too.    The reset to factory defaults is under 'preferences' on the right side uninstall/reset icon.  Thanks for providing the solution.

**Comment by rjamestaylor** [comment]
I am unable to view "Preferences" as I receive the following error dialog and then the preference pane aborts:

"Error

Failed to retrieve settings values.

invalid return type"

I have manually uninstalled Docker.app & deleted ~/Library/Preferences/com.docker.docker.plist but still receive the same error after re-installing 1.12.1. 

Is Docker.app looking elsewhere for settings (I assume so), if so, where?

**Comment by olandere** [comment]
The reset of the preferences works for the current run, but the next time I start docker, the same thing happens, so again I reset, download containers (a few hours for 1.7 GB container) and am able to run it again.  This is not workable for me.

**Comment by avishayp** [comment]
Same.
Docker on mac is just not production ready. Please ping once it is.
```
$ docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by samoht** [comment]
@avishayp could you please open a new issue with a diagnostic ID so that we can investigate your issue. Thanks.

@olandere Detected symptom of problem 'qcow2-corruption' in E4FCFDFB-ABC5-4E87-B1B8-20B62734D006/20160922-141516.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
```
Sep 16 11:49:15 eolander-mbp15 Docker[com.docker.driver.amd64-linux][54851] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Sep 16 11:49:15 eolander-mbp15 Docker[com.docker.slirp][53079] <Notice>: Using protocol TwoThousand msize 8192
Sep 16 11:49:15 eolander-mbp15 Docker[com.docker.driver.amd64-linux][54851] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
Sep 16 11:49:17 eolander-mbp15 Docker[com.docker.driver.amd64-linux][54851] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-4096")
Sep 16 11:49:19 eolander-mbp15 Docker[com.docker.slirp][53079] <Notice>: Using protocol TwoThousand msize 8192
Sep 16 11:49:59 eolander-mbp15 Docker[com.docker.driver.amd64-linux][54851] <Notice>: SC database lists no DNS servers: removing overrides from db
Sep 16 11:49:59 eolander-mbp15 Docker[com.docker.slirp][53079] <Notice>: remove resolver override
Sep 16 11:49:59 eolander-mbp15 Docker[com.docker.slirp][53079] <Notice>: using default DNS on
Sep 16 11:49:59 eolander-mbp15 Docker[com.docker.slirp][53079] <Notice>: remove resolver override
```

I am afraid you will have to reset to factory defaults.
