### ISSUE TITLE
Docker 4.22.0 will not start

### ISSUE THREAD

**Issue by TimUnderhay** [docker/for-mac#6946]
### Description

After updating to Docker Desktop 4.22.0, the engine will not start.  Reverting to 4.21.1 resolves the issue.  Clean / purge / reset to defaults have no effect.  This is on an M2 Pro mac mini.  `docker info` and `docker version` are from 4.21.1, as they do not complete on 4.22.0.

Diagnostic uploaded.

### Reproduce

Start Docker 4.22.0.  Observe that engine does not start.

### Expected behavior

Engine should start

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /Volumes/External/Users/tunderhay/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 090e0b83-a37f-4996-9738-cadc874ce295
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

35F32DFC-4E0A-4CEB-8AB9-4C052A623E23/20230817161016

**Comment by petropolis10** [comment]
Ditto. Running

pred='process matches ".*(ocker|vpnkit).*" || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
 /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"

yields

2023-08-21 10:07:52.566889-0700  localhost Docker Desktop[5841]: (CarbonCore) [com.apple.CarbonCore:checkfix] _CSCheckFix(10507300,com.electron.dockerdesktop/4.22.0.36)=NOT-APPLIED
2023-08-21 10:07:52.566941-0700  localhost Docker Desktop[5841]: (CarbonCore) [com.apple.CarbonCore:checkfix] _CSCheckFix(40356500,com.electron.dockerdesktop/4.22.0.36)=NOT-APPLIED
...

/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather

yields

[2023-08-21T17:10:18.978144000Z][com.docker.diagnose.ipc][I] (1e348b70-6) 9f671a03-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-08-21T17:10:18.979321000Z][com.docker.diagnose.ipc][W] (1e348b70-6) 9f671a03-com.docker.diagnose C<-S NoResponse GET /ping (1.076959ms): Get "http://ipc/ping": dial unix <HOME>/Library/Containers/com.docker.docker/Data/dns-forwarder.sock: connect: no such file or directory

[Loom video](https://www.loom.com/share/9f2a71cef5c64e54b842cde000c1163c?sid=3487edab-5ad1-47bd-827a-6fbc57967d16).

**Comment by ctalledo** [comment]
Hi folks,

We've addressed this problem in a [new v4.22.1 patch release](https://docs.docker.com/desktop/release-notes/).

Could you please give that a try and let us know if the issue is fixed or not?

Thanks!

**Comment by ctalledo** [comment]
Closing as duplicate of #6936.

**Comment by petropolis10** [comment]
It is fixed for me.  Thanks!

**Comment by TimUnderhay** [comment]
@ctalledo and also for me.  Cheers!
