### ISSUE TITLE
Docker crashes every minute or so.

### ISSUE THREAD

**Issue by tgoyer** [docker/for-mac#695]
### Expected behavior
Runs.

### Actual behavior
Crashes in about a minute.

### Information
Running macOS Sierra.  This is a clean install of Docker.

Diagnostic ID: F8ECC936-2FF6-42E0-B9B8-116E2D41706E
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Start Docker
2. Wait about a minute.

**Comment by tgoyer** [comment]
Just saw that there is an update to *.1.  Will try that and see if it solves my stability issue.

**Comment by dsheets** [comment]
Docker for Mac 1.12.0 had severe issues with macOS Sierra. Please open a new issue if you experience further problems. Thanks for using Docker for Mac!
