### ISSUE TITLE
Docker Desktop Login Problem

### ISSUE THREAD

**Issue by GokhanKaraomeroglu** [docker/for-mac#6970]
### Description

I can't login to Docker Desktop and when I click the link below the sign in window (If you don't have a Docker ID, create one on [cloud.docker.com](https://cloud.docker.com/?utm_source=docker4mac_18.06.1-ce-mac73&utm_medium=account_create&utm_campaign=referral)) 
![Ekran Resmi 2023-09-09 10 21 32](https://github.com/docker/for-mac/assets/80010235/e9803ed3-eded-448c-b21d-aa134edcd015) webpage throwing the error below.

Unexpected Application Error!

Loading chunk 7946 failed. (missing: https://d36jcksde1wxzq.cloudfront.net/7946.c7cc130241833df69bed.js)

https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1759595
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1747658
reduce@[native code]
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1747629
lazy@https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1815545
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:694450
asyncFunctionResume@[native code]
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:695197
asyncFunctionResume@[native code]
map@[native code]
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:681791
asyncFunctionResume@[native code]
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:680249
asyncFunctionResume@[native code]
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:680743
asyncFunctionResume@[native code]
initialize@https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:685152
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1829685
https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1830284
global code@https://d36jcksde1wxzq.cloudfront.net/main.fb8d2007b0855c3bebb3.js:205:1830296

I have no issue for logging in Docker Hub, and command line login to docker hub.
MacOs 10.13.6 High Sierra

### Reproduce

Sign in to Docker Desktop
Click the link below the window.

### Expected behavior

Signing in the docker desktop.

### docker version

```bash
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

### docker info

```bash
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 6
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: SZEA:WKSL:Y4F5:4QK2:WZVG:SIFB:VRQC:I6DB:NTUC:SG6N:YEXE:GEWJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2023-09-09T07:29:40.146961246Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Diagnostics ID

1E10AE57-757E-4C37-872F-B1ABCC5E1E83/20230909073324

**Comment by hktalent** [comment]
me too
<img width="898" alt="image" src="https://github.com/docker/for-mac/assets/18223385/210dabc6-51a8-4093-bf2a-fb907ef95445">
# ping hub.docker.com
PING prodextdefblue-1cc5ls33lft-b42d79a68e9f190c.elb.us-east-1.amazonaws.com (18.206.20.10) 56(84) bytes of data.


long time nothing
^C

**Comment by lorenrh** [comment]
hi @GokhanKaraomeroglu, it seems that this is an old version of Docker Desktop, can you try with a recent version ( see the [release notes](https://docs.docker.com/desktop/release-notes/) ) and let us know if the problem persists? 

thanks!
