### ISSUE TITLE
"Kubernetes is failed to start"

### ISSUE THREAD

**Issue by tpberntsen** [docker/for-mac#6971]
### Description

The Kubernetes menu item in the Docker Desktop status menu on macOS (v4.21.1 (114176)) has a grammar issue.

It states "Kubernetes is failed to start" where it should have said "Kubernetes has failed to start."

<img width="310" alt="image" src="https://github.com/docker/for-mac/assets/922318/df95c8de-e298-44e8-a0a3-96415cb798b3">

### Reproduce

1. Open the Docker Desktop status menu on macOS
2. Behold the bug

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

### Diagnostics ID

N/A

**Comment by lorenrh** [comment]
Hello,

This issue has been fixed in the latest 4.24.0 release. You can see the latest release notes [here](https://docs.docker.com/desktop/release-notes/).

I'll close the issue for now, but let us know if the issue persists.
