### ISSUE TITLE
安装24.0.6 导致mac 电脑重启

### ISSUE THREAD

**Issue by sunzhuo0211** [docker/for-mac#6994]
### Description

安装24.0.6 docker 版本，打开 导致m1 芯片的mac 重启
panic(cpu 5 caller 0xfffffe0013111c44): vm_fault() KERN_FAILURE from guest fault on state 0xfffffe600c4c0000 @sleh.c:3091
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 21C52
Kernel version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Fileset Kernelcache UUID: 88208EF24C07AA8B02CDA1369E036EBD
Kernel UUID: 2F4E22DC-64BE-3369-B574-0909F0571FA6
iBoot version: iBoot-7429.61.2
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x000000000b674000
KernelCache base:  0xfffffe0012678000
Kernel slide:      0x000000000bea0000
Kernel text base:  0xfffffe0012ea4000
Kernel text exec slide: 0x000000000bf88000
Kernel text exec base:  0xfffffe0012f8c000
mach_absolute_time: 0x83fbbdcd6
Epoch Time:        sec       usec
  Boot    : 0x6510f52b 0x00078509
  Sleep   : 0x6510f8b9 0x00049674
  Wake    : 0x6510f9d0 0x00041d22
  Calendar: 0x6510fc03 0x0002fd4c

Zone info:
Foreign   : 0xfffffe001bc30000 - 0xfffffe001bc44000
Native    : 0xfffffe10003fc000 - 0xfffffe30003fc000
Readonly  : 0xfffffe14cd0c8000 - 0xfffffe1666a5c000
Metadata  : 0xfffffe7598a44000 - 0xfffffe75a49d8000
Bitmaps   : 0xfffffe75a49d8000 - 0xfffffe75aa444000
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 8 PVH locks held: None
CORE 9 PVH locks held: None
CORE 0: PC=0x0000000187f002c4, LR=0x0000000187f51014, FP=0x000000016fcc4a90
CORE 1: PC=0xfffffe0013012f18, LR=0xfffffe0013012f18, FP=0xfffffe600c52bef0
CORE 2: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe600c4fbef0
CORE 3: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe6038eb3ef0
CORE 4: PC=0xfffffe0012f9efd4, LR=0xfffffe0013125fe0, FP=0xfffffe600c54be50
CORE 5 is the one that panicked. Check the full backtrace for details.
CORE 6: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe60a53ebef0
CORE 7: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe6038c73ef0
CORE 8: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe60a5b9bef0
CORE 9: PC=0xfffffe0013012f1c, LR=0xfffffe0013012f18, FP=0xfffffe60a53bbef0
Panicked task 0xfffffe166b1ff470: 38306 pages, 9 threads: pid 1330: qemu-system-aarc
Panicked thread: 0xfffffe1b356b5960, backtrace: 0xfffffe600c43b300, tid: 21064
		  lr: 0xfffffe0012fde4e4  fp: 0xfffffe600c43b370
		  lr: 0xfffffe0012fde1b4  fp: 0xfffffe600c43b3e0
		  lr: 0xfffffe001311e070  fp: 0xfffffe600c43b400
		  lr: 0xfffffe001311047c  fp: 0xfffffe600c43b480
		  lr: 0xfffffe001310decc  fp: 0xfffffe600c43b540
		  lr: 0xfffffe0012f937f8  fp: 0xfffffe600c43b550
		  lr: 0xfffffe0012fdde28  fp: 0xfffffe600c43b8f0
		  lr: 0xfffffe0012fdde28  fp: 0xfffffe600c43b960
		  lr: 0xfffffe00137f3a90  fp: 0xfffffe600c43b980
		  lr: 0xfffffe0013111c44  fp: 0xfffffe600c43b9e0
		  lr: 0xfffffe00131117c8  fp: 0xfffffe600c43ba50
		  lr: 0xfffffe0012f9e828  fp: 0xfffffe600c43ba60
		  lr: 0xfffffe0013125fe0  fp: 0xfffffe600c43be50
		  lr: 0xfffffe001310e2e4  fp: 0xfffffe600c43bf10
		  lr: 0xfffffe0012f937f8  fp: 0xfffffe600c43bf20

last started kext at 2942039580: com.apple.filesystems.smbfs	4.0 (addr 0xfffffe0012e8ad60, size 64483)
loaded kexts:
com.apple.filesystems.smbfs	4.0
com.apple.filesystems.autofs	3.0
com.apple.fileutil	20.036.15
com.apple.driver.AppleTopCaseHIDEventDriver	5020.1
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.SEPHibernation	1
com.apple.driver.BCMWLANFirmware4387.Hashstore	1
com.apple.filesystems.apfs	1933.61.1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.filesystems.lifs	1
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	582.60.2
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.ApplePMP	1
com.apple.driver.AppleCS42L84Audio	520.5
com.apple.driver.AppleSmartIO2	1
com.apple.driver.AppleSN012776Amp	520.5
com.apple.driver.AppleT6000SOCTuner	1
com.apple.driver.AppleT6000CLPCv3	1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	100.1
com.apple.driver.AppleAVE2	520.21.1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.AppleAVD	416
com.apple.driver.AppleMCDP29XXUpdateSupport	1
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleProResHW	126.2.0
com.apple.driver.AppleMobileDispT600X-DCP	140.0
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleJPEGDriver	4.7.9
com.apple.driver.AppleSerialShim	1
com.apple.AGXG13X	187.59
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleT6000PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleInterruptControllerV2	1.0.0d1
com.apple.driver.AppleT8110DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AudioDMAController-T600x	100.51
com.apple.driver.AppleT6000DART	1
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleT6000	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.driver.AppleSDXC	3.1.1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	126.60.3
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	402
com.apple.kec.InvalidateHmac	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.driverkit.serial	6.0.0
com.apple.iokit.IOAVBFamily	1010.2
com.apple.plugin.IOgPTPPlugin	1000.11
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.kext.triggers	1.0
com.apple.driver.AppleHIDKeyboard	228
com.apple.driver.AppleActuatorDriver	5430.1
com.apple.driver.AppleMultitouchDriver	5430.1
com.apple.driver.AppleHSBluetoothDriver	5020.1
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.nke.ppp	1.9
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleHIDTransportSPI	5400.30
com.apple.driver.AppleHIDTransport	5400.30
com.apple.driver.AppleInputDeviceSupport	5400.30
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.AppleCSEmbeddedAudio	520.5
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.AppleAOPAudio	102.2
com.apple.driver.AppleEmbeddedAudio	520.5
com.apple.iokit.AppleARMIISAudio	100.1
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.AGXFirmwareKextG13XRTBuddy	187.59
com.apple.AGXFirmwareKextRTBuddy64	187.59
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleSPU	1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT6000TypeCPhy	1
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.DCPAVFamilyProxy	1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSART	1
com.apple.iokit.IOGPUFamily	35.11
com.apple.driver.ApplePMGR	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.driver.AppleT6000PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT600xPCIe	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.AppleMCA2-T600x	600.95
com.apple.driver.AppleEmbeddedAudioLibs	100.9.1
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleH13CameraInterface	4.87.0
com.apple.driver.AppleH10PearlCameraInterface	17.0.3
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	1000.11
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	593
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.driver.FairPlayIOKit	68.13.1
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	532.40.7
com.apple.iokit.IOUSBMassStorageDriver	209.40.6
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	452.60.2
com.apple.iokit.IOSCSIArchitectureModelFamily	452.60.2
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleANELoadBalancer	5.34.2
com.apple.driver.AppleH11ANEInterface	5.34.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	100.1
com.apple.driver.AppleAudioClockLibs	100.9.1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	302.9
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.security.AppleImage4	4.2.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

** Stackshot Succeeded ** Bytes Traced 403504 (Uncompressed 1037488) **
这个是失败 然后系统的信息

### Reproduce

打开失败

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.4
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0-desktop.1
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.7
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.24.1
    Path:     /Users/sunzhuo/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.666GiB
 Name: docker-desktop
 ID: 4d70db64-e24a-40e9-9c9c-682c82946191
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  106.12.183.3:8660
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

BD4E0D87-859C-4B43-9448-46B7EFC9BD13/20230925090414

**Comment by sunzhuo0211** [comment]
Diagnostics ID 是我更新系统之后弄的，并没有符合当时的场景，希望能解答，

**Comment by lorenrh** [comment]
Hello, we don't have enough information to look into this issue, so I'll be closing it for now.

**Comment by sunzhuo0211** [comment]
为什么不解决，直接关闭了呢

**Comment by QiangFok** [comment]
@sunzhuo0211 我也遇到了同样的问题，我还以为电脑出问题了，结果发现最新版docker客户端问题。导致电脑无线重启，只能卸载用老版本了。

**Comment by sunzhuo0211** [comment]
还有一个解决办法就是升级系统，但是升级之后会带来更多软件不可用。
