### ISSUE TITLE
Unable to start docker - Mac

### ISSUE THREAD

**Issue by Gsantomaggio** [docker/for-mac#7]
### Expected behavior
Start docker
### Actual behavior
Docker does not start anymore. I used it for days, and now does not start:
it is in this status:
![screen shot 2016-07-29 at 12 38 30](https://cloud.githubusercontent.com/assets/386987/17245966/6660979e-5589-11e6-8b36-cff4631a829d.png)

### Information

Diagnostic ID: ABEA8DD3-0F1F-440B-9DD6-EB97931AF490
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F1605)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

I am trying just to start it.
Thank you!

**Comment by samoht** [comment]
From which Beta version did you upgrade? Any more hints which could help us?

**Comment by Gsantomaggio** [comment]
hi @samoht where can I find this info? 
Btw I installed about 4 weeks ago, I always updated it.

I saw that this version has some problem to restart working after the stand-by. 
After the stand-by I usually quit Docker and restart, until this morning worked. 



OS:
![screen shot 2016-07-29 at 13 55 15](https://cloud.githubusercontent.com/assets/386987/17247570/67516ee8-5594-11e6-8a81-f12f50a1341d.png)

**Comment by djs55** [comment]
The logs contain lots of these:
```
 <Notice>: VM: 2016-07-26 08:05:28 +0000 UTC kern.info kernel: auplink[4653]: segfault at 7ffcc77b1f48 ip 000000000043d049 sp 00007ffcc77b1f50 error 6 in auplink[40000
0+ca000]
```
and lots of these:
```
<Warning>: VM: 2016-07-29 10:26:45 +0000 UTC kern.notice kernel: EXT4-fs (vda2): error count since last fsck: 10
<Warning>: VM: 2016-07-29 10:26:45 +0000 UTC kern.notice kernel: EXT4-fs (vda2): initial error at time 1469648408: ext4_iget:4173: inode 2112671
<Warning>: VM: 2016-07-29 10:26:45 +0000 UTC kern.notice kernel: EXT4-fs (vda2): last error at time 1469787707: ext4_lookup:1584: inode 2101159
```
Your block device looks intact:
```
$ cat qemu-img-check.stdout
No errors were found on the image.
243684/1048576 = 23.24% allocated, 7.20% fragmented, 0.00% compressed clusters
Image end offset: 15975514112
```
but I think your container filesystem is in a bad state and this is preventing the docker daemon from starting.

Could you shut down the app and then move the .qcow2 out of the way e.g.
```
mv ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 ~/Docker.qcow2.backup
```
and the restart the app?

**Comment by Gsantomaggio** [comment]
hi @djs55 
by executing:

```
mv ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 ~/Docker.qcow2.backup
```

I solved the problem.
Thank you very much
