### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by galkinrost** [docker/for-mac#70]
### Information

Diagnostic ID: 3A662B95-1AFB-4EF1-8632-6897F87616FB
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/galkinrost/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/3A662B95-1AFB-4EF1-8632-6897F87616FB/20160802-145725/qemu-img-check.stdout 2> /tmp/3A662B95-1AFB-4EF1-8632-6897F87616FB/20160802-145725/qemu-img-check.stderr: exit 2")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. run `docker ps`

**Comment by djs55** [comment]
It looks like the `Docker.qcow2` file has become corrupt :(
```
13343 errors were found on the image.
Data may be corrupted, or further writes to the image may corrupt it.

5037 leaked clusters were found on the image.
This means waste of disk space, but no harm to data.
99868/1048576 = 9.52% allocated, 2.47% fragmented, 0.00% compressed clusters
Image end offset: 7424704512
```
Could you try reseting to factory defaults? That will delete local containers and images but it should allow the app to start again.

**Comment by long-lx** [comment]
+1

**Comment by yannispanousis** [comment]
+1 this happens for at least 2 of our Mac setups, the Docker engine falls over roughly every hour. Then we have to restart it and start the containers again

**Comment by djs55** [comment]
For the qcow2 issue there were some important bug fixes in the beta channel as of beta 25. Hopefully this issue is now fixed, if not let me know!

Note that "Bad response from docker engine" could happen in other ways -- if you still see it, please open another issue.
