### ISSUE TITLE
M1 Mac address already in use port 53 by mDnsResponder

### ISSUE THREAD

**Issue by nicekiwi** [docker/for-mac#7008]
### Description

I'm encountering this issue again, on MacOS Sonoma after the latest Docker Desktop update and restarting MacOS.

https://github.com/docker/for-mac/issues/5335

Macbook Air M1
MacOS 14.0 (23A344)
Docker Desktop 4.24.0 (122432)

### Reproduce

```docker run -p 53:53 -it --rm alpine ash```

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.0 (122432)
 Engine:
  Version:          dev
  API version:      1.44 (minimum version 1.12)
  Go version:       go1.20.8
  Git commit:       HEAD
  Built:            Tue Sep 26 11:52:32 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/ezra/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/ezra/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/ezra/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/ezra/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/ezra/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ezra/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/ezra/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/ezra/.docker/cli-plugins/docker-scout

Server:
 Containers: 15
  Running: 11
  Paused: 0
  Stopped: 4
 Images: 64
 Server Version: dev
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 3
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: 933609a0-5ad0-4978-95d3-977004e883f7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

7ABA3113-529E-442E-9D86-EE5D06BCD06A/20231003015243

### Additional Info

Re-installing the previous version 4.23.0 does resolve the issue for me.

**Comment by robphillips** [comment]
Same issue on Intel chip.

**Comment by BrentRobert** [comment]
Same issue on M1. Rolling back to 4.23.0 resolves the issue.

**Comment by adrianliegmann** [comment]
That same issue on M1 and MacOS Sonoma. Downgrade to Docker 4.23.0 works correctly.

**Comment by adrianliegmann** [comment]
> Can you try this workaround?
> 
>     1. Edit `~/Library/Group\ Containers/group.com.docker/settings.json` and add `"kernelForUDP": false`
> 
>     2. Restart Docker Desktop

@bsousaa For me that workaround works correctly.

**Comment by nicekiwi** [comment]
> Can you try this workaround?
> 
> 1. Edit `~/Library/Group\ Containers/group.com.docker/settings.json` and add `"kernelForUDP": false`
> 2. Restart Docker Desktop

Yes, that does resolve the issue on 4.24 for me.

**Comment by simonrw** [comment]
Do you have "Internet Sharing" enabled in your settings? 
<img width="827" alt="Screenshot 2023-10-05 at 09 11 48" src="https://github.com/docker/for-mac/assets/59756/7f611ca3-6a71-423c-bc73-31c90c0da270">

I find that with this enabled, `mDNSResponder` binds to port 53, and without it port 53 is free.

**Comment by BrentRobert** [comment]
> Do you have "Internet Sharing" enabled in your settings? <img alt="Screenshot 2023-10-05 at 09 11 48" width="827" src="https://user-images.githubusercontent.com/59756/272828704-7f611ca3-6a71-423c-bc73-31c90c0da270.png">
> 
> I find that with this enabled, `mDNSResponder` binds to port 53, and without it port 53 is free.

It's not enabled. The issue lies in a settings change on Docker Desktop since 4.23.0

**Comment by alexlo03** [comment]
Workaround works for me.

Note workaround is now doc'd at https://docs.docker.com/desktop/release-notes/#4240 "known issues / for mac"

**Comment by uphlewis** [comment]
Same issue with Docker 4.24.0 (122432) on Intel MBP running Monterey 12.6.9 (21G726).

The suggested `kernelForUDP` workaround fixed the issue for me too, thank you!

```bash
harry@Harrys-MacBook-Pro: ~$ sudo lsof -i :53 # with docker stopped
harry@Harrys-MacBook-Pro: ~$ sudo lsof -i :53 # with docker running
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mDNSRespo 314 _mdnsresponder   40u  IPv4 0xb56646544beaa53d      0t0  UDP *:domain
mDNSRespo 314 _mdnsresponder   60u  IPv6 0xb56646544beaa84d      0t0  UDP *:domain
mDNSRespo 314 _mdnsresponder   62u  IPv4 0xb56646544df55115      0t0  TCP *:domain (LISTEN)
mDNSRespo 314 _mdnsresponder   67u  IPv6 0xb56646544bd9490d      0t0  TCP *:domain (LISTEN)
harry@Harrys-MacBook-Pro: ~$ code ~/Library/Group\ Containers/group.com.docker/settings.json # workaround applied
harry@Harrys-MacBook-Pro: ~$ sudo lsof -i :53 # after restarting docker
harry@Harrys-MacBook-Pro: ~$
```

**Comment by alexlo03** [comment]
@bsousaa Is this considered a bug that will be fixed in a future version of Docker For Mac? Thanks 🙏

**Comment by amjerm** [comment]
Workaround worked for me as well. Thanks!

**Comment by bsousaa** [comment]
@alexlo03 yes it is considered a bug with a documented workaround. We will post news as soon as we can.

**Comment by fwolfst** [comment]
Probably other workaround are these settings
![image](https://github.com/docker/for-mac/assets/219373/99041175-9dbe-42fc-b553-e04f601e7284)

**Comment by PaulWeinsberg** [comment]
Try to deactivate network acceleration by adding "kernelForUDP": false, in the settings.json file located at ~/Library/Group Containers/group.com.docker/settings.json

This solve the issue on my mac.

**Comment by debo** [comment]
Adding my 2 cents here hoping to add some additional element of thought to the conversation.

My `kernelForUDP` settings is `true` and I don't have this issue so, whilst a solution it feels still like a workaround. For what is worth I noticed that on my machine (M2 Pro running Ventura still) `mDNSresponder` is actually listening over UDP:5353 and not over TCP:53. I wonder if it's because of the fact I also have the internet sharing option disabled like @simonrw suggested or some other setup on my machine that I can't recall now, but I don't have this issue and I didn't have to change docker settings are suggested.

**Comment by Veraxus** [comment]
I just started experiencing this after updating Docker Desktop to 4.24.2 (124339)

**Comment by debo** [comment]
Little update, I'm running Docker Desktop to 4.24.2 (124339) on two different Mac one is an M1 Pro and the other is and M2 Pro. Both have `kernelForUDP` set to `true` and it actually turns out they both have the following output for `sudo lsof -I -P`:

```shell
mDNSRespo   664 _mdnsresponder    6u  IPv4 0xca551a3476c9e4ed      0t0    UDP *:5353
mDNSRespo   664 _mdnsresponder    7u  IPv6 0xca551a3476cbf0ed      0t0    UDP *:5353
mDNSRespo   664 _mdnsresponder   53u  IPv4 0xca551a3476e1cced      0t0    UDP *:53
mDNSRespo   664 _mdnsresponder   59u  IPv6 0xca551a3476e1d0ed      0t0    UDP *:53
mDNSRespo   664 _mdnsresponder   62u  IPv4 0xca551a347312e36d      0t0    TCP *:53 (LISTEN)
mDNSRespo   664 _mdnsresponder   63u  IPv6 0xca551a3e0fdf482d      0t0    TCP *:53 (LISTEN)
```
And I don't see the port conflict error.

**Comment by aheck** [comment]
There will be a checkbox in Docker Desktop 4.26 (to be released end of November 2023) to change the value of kernelForUDP from the UI:

![image](https://github.com/docker/for-mac/assets/219416/3f2bbc35-254b-4076-baf8-b8469856425a)

**Comment by holyoaks** [comment]
The workaround does NOT solve the issue for me

**Comment by bmelton-mdsol** [comment]
The kernelforUDP workaround doesn't work for me either with 4.25.1

**Comment by djs55** [comment]
@holyoaks @bmelton-mdsol next time you see this issue could you upload a diagnostics and quote the ID here? I installed a fresh download of build  4.25.1 (128006), edited my settings.json and started DD. I have nothing listening on port 53:
```
% netstat -an | grep 53 
udp4       0      0  *.5353                 *.*                               
udp6       0      0  *.5353                 *.*                               
udp4       0      0  *.5353                 *.*                               
dbeaf592e4dc5351 stream      0      0 dbeaf58950174f09                0                0                0 /Users/djs55/Library/Containers/com.docker.docker/Data/diagnosticd.direct.sock
dbeaf592e4dd5351 stream    117      0                0                0                0                0 /var/run/docker.sock
dbeaf592e7675351 stream      0      0                0 dbeaf592e7675289                0                0
dbeaf592e7675289 stream      0      0                0 dbeaf592e7675351                0                0
dbeaf592e4dced19 stream      0      0 dbeaf5894b5389e1                0                0                0 /Users/djs55/Library/Group Containers/BJ4HAAB9B3.ZoomClient3rd/s.zoomclient
dbeaf592e4de5f19 dgram       0      0                0 dbeaf592e4dea099                0 dbeaf592e4de5361
dbeaf592e4de5361 dgram       0      0                0 dbeaf592e4dea099                0 dbeaf592e4de60a9
       3        1       38    65536    65536 com.apple.net.netagent 
       6       21        0    65536    65536 com.apple.net.ipsec_control 
       a        1        0    65536    65536 com.apple.net.rvi_control 
       c        4        0    65536     2048 com.apple.uart.wlan-debug 
       e        4        0    65536     2048 com.apple.spmi.nfc 
```
and my Linux VM doesn't have the vmnet.framework eth1 (it's the activation of the vmnet.framework or Internet connection sharing which causes mDNSresponder to allocate port 53):
```
% docker run --rm --pid host --privileged -it justincormack/nsenter1 /sbin/ifconfig eth1
ifconfig: eth1: error fetching interface information: Device not found
```
When I set `kernelForUDP` back to `true`, I see the `eth1` interface and `mDNSresponder` allocating the port as expected.

**Comment by Mika571** [comment]
> Can you try this workaround?
> 
> 1. Edit `~/Library/Group\ Containers/group.com.docker/settings.json` and add `"kernelForUDP": false`
> 2. Restart Docker Desktop

@adrianliegmann thanks so much have been tearing my hair out on this for so long.

**Comment by hotrungnhan** [comment]
i think we can closed this issue :v the latest 4.26.1  was fixed by uncheck the use kernel network for UDP

> There will be a checkbox in Docker Desktop 4.26 (to be released end of November 2023) to change the value of kernelForUDP from the UI:
> 
> ![image](https://private-user-images.githubusercontent.com/219416/279938846-3f2bbc35-254b-4076-baf8-b8469856425a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDE4NjUsIm5iZiI6MTcwNTkwMTU2NSwicGF0aCI6Ii8yMTk0MTYvMjc5OTM4ODQ2LTNmMmJiYzM1LTI1NGItNDA3Ni1iYWY4LWI4NDY5ODU2NDI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwNTMyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjM3OWU1ZWU2MWQ4MDE1YTUwMzE1OGQ1NTRlYzNiODEyY2ZhOTlmYzgxMmI5YzliZjczYWYyNWEyNWUzODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IhkI_F6TqXtbwro6Coh01-qM8z7QrxTZAw2Np12soQ4)

**Comment by nicekiwi** [comment]
I've stopped using Docker for development, AFAIK this has been resolved, though some people still seem to have the issue.

**Comment by dimohamdy** [comment]
Before running your docker command, run this command in the terminal like this


```
sudo lsof -t -i :53 | xargs sudo kill -9

docker run -p 53:53 -it --rm alpine ash
```

**Comment by Veraxus** [comment]
There was a regression in 4.27.2 and this is once again a problem.

**Comment by nicekiwi** [comment]
> > There was a regression in 4.27.2 and this is once again a problem.
> 
> Seems to work as expected for me on my M2 Mac having the "Use kernel networking for UDP" option under "Resources -> Network" deactivated.
> 
> I updated from 4.26 to 4.27.2 without issues so far.

Same for me, no DNS issues with 4.27.2 with "Use kernel networking for UDP" disabled.

**Comment by lacorde** [comment]
Confirmed fixed for me on 4.28.0 (Intel Mac).
I still had the issue on 4.27.2, even with "Use kernel networking for UDP" disabled.

**Comment by lacorde** [comment]
Confirmed fixed for with on 4.28.0 (Intel Mac).

I still had the issue with 4.27.2, even with "Use kernel networking for UDP" disabled.

**Comment by ArneBo** [comment]
Still an issue on macOS 14.6.1 with 4.33.0 and with 4.34.0
The workaround is not working

**Comment by ernstmulder** [comment]
Same issue on my M1 Mac mini running macOS 14.6.1 and Docker 4.34.2 trying to run PiHole with kernel networking for UDP on. Error: "(TTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:53 -> 0.0.0.0:0: listen top 0.0.0.0:53: bind: address already in use". It does not always happen, but almost always directly after a system or Docker reboot. The workaround that seems to work so far (still testing to be certain):

- Disable automatic booting of the Container (--restart=no)

Then after a reboot, disable mDNSResponder manually:

sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist

Then start the Container, and re-enable mDNSResponder again:

sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist

Next thing for me to do is automate this so my PiHole survives reboots. Work in progress.

**Comment by ernstmulder** [comment]
As I am using Docker to run PiHole which needs TCP/UDP port 53 and decent support for UDP (not using kernel networking for UDP has annoying issues, some (LAN) DNS requests time out) I was hoping for a programmable workaround. I remember reading that there is a particular Docker terminal command to toggle "Use kernel networking for UDP" but I can not find it documented anywhere.

The only way I know now to get PiHole running reliably after a system- or Docker reboot is this particular way:

Create your Docker Container using "--restart=no" to prevent it from starting automatically.

And after every reboot:

1) In Docker, disable "Use kernel networking for UDP".
2) Start the Container, it runs without UDP port conflicts since it is not using kernel networking for UDP.
3) In Docker, enable "Use kernel networking for UDP".
4) Start the Container again, no conflicts now and it runs using kernel networking for UDP.

This is Docker 4.34.2 running under macOS 14.7 on a M1 Mac mini.

**Comment by tbreuss** [comment]
This is still an Issue for my environment:

- Docker Desktop 4.35.1 (173168)
- Intel MacBook Pro (13'', 2020)
- macOS Sonoma Version 14.7.1 (23H222)
- Internt Sharing disabled

With docker started:

~~~
sudo lsof -i -P -n | grep LISTEN | grep :53                                 
mDNSRespo 231 _mdnsresponder   42u  IPv4 0xe22b3e886810a0d8      0t0    TCP *:53 (LISTEN)
mDNSRespo 231 _mdnsresponder   43u  IPv6 0xfde65027957d4067      0t0    TCP *:53 (LISTEN)
~~~

And kernelForUDP set to false:

~~~
cat ~/Library/Group\ Containers/group.com.docker/settings.json | grep kernel
  "kernelForUDP": false,
~~~

I still have this error when using dnsmasq in a container for example:

~~~
docker compose up
[+] Running 1/1
 ✔ Container dnsmasq-docker-dnsmasq-1  Recreated                                                                                                                  0.1s 
Attaching to dnsmasq-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: Ports are not available: exposing port UDP 0.0.0.0:53 -> 0.0.0.0:0: listen udp4 0.0.0.0:53: bind: address already in use
~~~

As soon as I quit Docker Desktop the port 53 isn't used any more.

**Comment by ernstmulder** [comment]
In the end I gave up, I wasn't able to get my virtual Pi-hole to run reliably.

I have now switched to running my virtual Pi-hole using a faceless Debian 12 VM with Pi-hole using VirtualBox 7.1.4 and a custom LaunchAgent and using its own IP local address. Stable, auto-start after reboot and logging in, and using less memory.

**Comment by ninjacoder30** [comment]
I am facing same issue (Error response from daemon: Ports are not available: exposing port UDP 127.0.0.1:53 -> 0.0.0.0:0: command failed)- System with  intel chip and MacOS - sequoia 15.2.

- Also i am not able to see settings.json under ~/Library/Group\ Containers/group.com.docker/ folder. tried saving resources but still that file is not getting created. - 
- verified Internet sharing is off.

**docker desktop version -4.37.2**

Client:
Version:           27.4.0
API version:       1.47
Go version:        go1.22.10
Git commit:        bde2b89
Built:             Sat Dec  7 10:35:43 2024
OS/Arch:           darwin/amd64
Context:           desktop-linux


Server: Docker Desktop 4.37.2 (179585)
Engine:
  Version:          27.4.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       92a8393
  Built:            Sat Dec  7 10:38:57 2024
  OS/Arch:          linux/amd64
  Experimental:     false
containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 
**Docker Compose version v2.31.0-desktop.2**

**Comment by lucadibello** [comment]
> > 1. In Docker, disable "Use kernel networking for UDP".
> 
> That saved me a lot of nerves 😅 I'd give a little bit more details (in case someone same like me, who doesn't know where to find it):
> 
> * Go to Settings
> * Resources
> * Network
> * Uncheck the box "Use kernel networking for UDP"
> 
> Thanks, [@ernstmulder](https://github.com/ernstmulder) 🧚‍♀️

This has finally fixed the issue. 

The proposed solution (manually editing `~/Library/Group\ Containers/group.com.docker/settings.json`) did not work on MacOS Sequoia 15.3.2 with Docker Engine 28.0.4.

**Comment by mr237399** [comment]
Please note that in newer versions of Docker Desktop on Mac, you can simply disable kernel networking for UDP from the Docker Desktop settings (under Resources). 

After restart run `sudo lsof -t -i :53` to confirm that no process id (a number) is returned before trying to start your container again.

**Comment by ranger6** [comment]
Same problem MacOS 13.7.6 (Ventura) and Docker Desktop 14.42.1
Turning off "Use Kernel Networking for UDP" as described above solved the problem: my DNS server (coredns) running in Docker can obtain port 53, mDNSresponder does not use it (what this has to do with Docker Desktop is rather mysterious to me).

**Comment by pslyman** [comment]
> Same problem MacOS 13.7.6 (Ventura) and Docker Desktop 14.42.1 Turning off "Use Kernel Networking for UDP" as described above solved the problem: my DNS server (coredns) running in Docker can obtain port 53, mDNSresponder does not use it (what this has to do with Docker Desktop is rather mysterious to me).

That fixed it for me as well. Thank you!

**Comment by JMLucas96** [comment]
Only:
> fix it in docker 4.26.1 it by uncheck the use kernel network for UDP

It works for me, thank you!!

**Comment by netgabo** [comment]
<img width="952" height="731" alt="Image" src="https://github.com/user-attachments/assets/8eb6017f-40ab-4129-9c5a-6cfac8a0b135" />

**¿Por qué deshabilitar "Use kernel networking for UDP" puede solucionar el problema?**

Cuando esta opción está activada, Docker intenta usar una ruta de red más eficiente para UDP que puede interferir con otros servicios que también necesitan usar UDP en el puerto 53, como mDNSResponder. Al deshabilitarla, Docker utilizará un método de red más estándar que es menos propenso a conflictos con otros servicios de red en tu Mac.
Pasos para solventar el error:

1. Abre Docker Desktop: Busca y abre la aplicación Docker Desktop en tu Mac.
2. Ve a la configuración de Red: En la barra lateral izquierda de Docker Desktop, haz clic en "Resources" y luego selecciona la pestaña "Network" en la parte superior.
3. Desactiva la opción "Use kernel networking for UDP": Busca la casilla de verificación junto a la opción "Use kernel networking for UDP" y desmárcala.
4. Aplica los cambios: Haz clic en el botón "Apply & Restart" (o similar) para guardar los cambios y reiniciar Docker.
5. Una vez que Docker se haya reiniciado, intenta ejecutar tu contenedor nuevamente. Es probable que el error de que el puerto 53 ya está en uso se resuelva.

**Importante:**
La descripción de esta opción menciona que "This may not be compatible with your VPN software." (Esto puede no ser compatible con tu software de VPN). Si usas una VPN, ten en cuenta que deshabilitar esta opción podría afectar el funcionamiento de tu VPN. Si experimentas problemas con tu VPN después de desmarcar esta casilla, es posible que debas volver a habilitarla y buscar otra solución para el conflicto de puertos de Docker.

**Comment by jbartolozzi** [comment]
I finally got it working in Docker Desktop 4.55.0
I disabled "Use kernel networking for UDP"
I also had to disable "Printer Sharing" in System Preferences.

*Update*
I installed OrbStack and started using it instead of Docker Desktop. Problem solved.
