### ISSUE TITLE
Unable to start Docker Daemon after Docker for Mac: version: 1.12.1-beta26.1 (12c3e63) upgrade

### ISSUE THREAD

**Issue by sabzo** [docker/for-mac#701]
### Expected behavior
Start Docker Daemon
### Actual behavior
When launching Docker from the list of Applications the Docker Icon remains at `Docker Starting`
### Information

Diagnostic ID: 9D051E18-256B-4BF2-B16A-0585F26736EB
 ```
Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.10.5 (build: 14F27)
logs: /tmp/9D051E18-256B-4BF2-B16A-0585F26736EB/20160925-191042.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior

  1 Start Docker from the Applications folder.
  2. Observe that Docker never actually stats it remains in the "Docker starting" phase.

**Comment by hmemcpy** [comment]
Same issue, using Docker for Mac 1.12.1 (build: 12133)
Typing `docker version` hangs.

Please let me know if there's any more information I can provide.

**Comment by sabzo** [comment]
@hmemcpy How did you reset to factory defaults?

**Comment by hmemcpy** [comment]
@sabzo from the Settings (in the Docker icon in Mac menu), click on Uninstall / Reset

**Comment by sabzo** [comment]
@hmemcpy worked for me! thnx
