### ISSUE TITLE
No longer able to add paths to Docker Desktop File Sharing

### ISSUE THREAD

**Issue by jacksoncw1** [docker/for-mac#7012]
### Description

Note that this is potentially similar to #7003, but wanted to expand on it as I've tried both VirtioFS and gRPC Fuse and both have the same issue.

After upgrading to Docker Desktop 4.24.0, I've lost the ability to add custom file paths via Resources -> File Sharing menu. When I attempt to add a file path, it appears at the bottom of the list of paths, but clicking the apply & restart button causes the file path I entered to vanish.

It does appear that the file path gets added to `~/Library/Group\ Containers/group.com.docker/settings.json`, but is removed when Docker Desktop is quit/restarted. And despite being listed in the `settings.json` I'm still unable to mount anything from the path into a container.

### Reproduce

1. Upgrade Docker Desktop to 4.24.0
2. Open Docker Desktop Settings, and navigate to Resources -> File Sharing
3. Either type a custom file path and press enter to add it, or select the `+` and select a folder
4. Hit apply and restart

### Expected behavior

I would expect Docker Desktop to save my custom file path and allow me to mount volumes from the custom path into containers as it did in 4.23.0.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.0 (122432)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/jacksoncw1/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 11
 Total Memory: 23.45GiB
 Name: docker-desktop
 ID: c5f37c66-f2a3-4988-9a19-5d7fbbe0dbfe
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

0FCBE8AE-DB48-4696-99F1-5FD856B1739A/20231004145252

### Additional Info

Running Docker Desktop on an M1 MacBook Pro, MacOS 13.6.

**Comment by jacksoncw1** [comment]
After some more testing, I believe I was wrong with my bug report. I think I was taking advantage of a bug by adding a file path to Docker Desktop that  did not exist on my host machine, but would eventually exist in a container I was running. This "functionality" I was making use of was fixed by #6980. Not being able to add a path via Mac's finder by clicking the `+` button was just me not realizing that I was trying to add a folder that was underneath a folder already in the file sharing settings. Sorry folks! 😅

**Comment by fredericdalleau** [comment]
Thanks, i'm closing it.

**Comment by AizazZaidee** [comment]
It is not working on the Mac. Apply and restart just removes the added path.

**Comment by paul-atkins-telstra** [comment]
What was the format of the entry to `settings.json`?

**Comment by Programbeginner2120** [comment]
Having the problem too where adding the path in docker doesn't work as it gets removed upon pressing apply and restart. Tried adding it to the settings.json manually but didn't work :(
