### ISSUE TITLE
Docker start but doesn't work docker-cli - Last Update OSX 10.12.1 beta (16B2327e)

### ISSUE THREAD

**Issue by pcollaog** [docker/for-mac#703]
### Expected behavior

Docker works normally

### Actual behavior

Docker start normally but when I try to use docker client (terminal) doesn't work.

```
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.
```

Docker Version:

```
Docker version 1.12.1, build 6f9534c, experimental
```

Docker Compose
```
docker-compose version 1.8.0, build f3628c7
```

**Comment by dsheets** [comment]
Could you please run `Diagnose & Feedback` from the :whale: menu and upload your diagnostic information? This will help us investigate the issue. Thanks!

**Comment by dsheets** [comment]
Please also paste here the output of the diagnostics (including the diagnostic ID you receive).

**Comment by pcollaog** [comment]
This report was made with the tool Diagnose & Feedback... 

Here the report:

```
Docker for Mac: version: 1.12.1-beta26.1 (12c3e63)
OS X: version 10.12.1 (build: 16B2327e)
logs: /tmp/E0908055-9470-440D-8117-8497389E8EE2/20160926-100222.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

Best Regards

**Comment by pcollaog** [comment]
I just restart and Reset to factory defaults and it works.

I lost all my containers but it works!

**Comment by levibostian** [comment]
@pcollaog @dsheets I am having the same issue. `ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.`

I have tried:

1. Variations of `docker-machine create`
`docker-machine create`
`docker-machine create -d virtualbox default`
`docker-machine create --driver xhyve default`

2. Removing existing images `docker rmi -f $(docker images -q)`

3. Restarting docker on Mac. 

4. Factory reset Docker on Mac. 

5. Restarting computer. 

6. Uninstall and reinstall Docker for Mac. 

All still result in same issue.

**Comment by dsheets** [comment]
@levibostian Docker for Mac does not use `docker-machine` and no `DOCKER_*` environment variables need (or should in basic usage) be set.

**Comment by levibostian** [comment]
I tried those commands because they were suggested by Docker team members
in Github issues. I found the issues searching the error message I
received.

I then later found out exactly what you said after I ran them.

Now the question is, how can I fix my issue?

**Comment by dsheets** [comment]
@levibostian what is output from running `env | grep DOCKER_` in your shell?

**Comment by levibostian** [comment]
Nothing outputs.

**Comment by dsheets** [comment]
@levibostian could you please open a new issue with the output of :whale: ➡️ `Diagnose & Feedback...` ➡️ `Diagnose & Upload` including the diagnostic ID? Also, please include the output of `ls -l /var/run/docker.sock`.

**Comment by levibostian** [comment]
@dsheets done: https://github.com/docker/for-mac/issues/1365
