### ISSUE TITLE
rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35 - os x 13.2.1 (ventura). rosetta 2 

### ISSUE THREAD

**Issue by james-fiskil** [docker/for-mac#7037]
### Description

running `docker compose up` or `docker build` with a multi-stage golang image results in the following error:

```bash
------
 > [xxxx-xxxx-xxxx 5/7] RUN go build -o ./xxxx_xxxxx:
3.198 rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
3.209 Trace/breakpoint trap
------
failed to solve: process "/bin/sh -c go build -o ./xxxx_xxxxx" did not complete successfully: exit code: 133
```
(container and binary names elided)

I've uninstalled and reinstalled docker desktop. 
pruning docker cache, volumes, containers makes no difference.
Docker desktop configured to use VirtioFS, Rosetta for x86/amd64 emulation on Apple Silicon also enabled

```Dockerfile
# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 golang:1.21 AS builder

WORKDIR /

ENV GOOS         linux
ENV GOARCH       amd64
ENV CGO_ENABLED  0

EXPOSE 8080

COPY go.mod go.sum ./
RUN go mod download -x
COPY . .
RUN go build -o ./xx_xxxxx
RUN go build -o ./xxxxx_xxxxxx cmd/xxxx_xxxxx/main.go

FROM scratch AS server
....
```

### Reproduce

1. create multi-stage docker file to for a go 1.21 binary, with or without cache mount
2. run `docker build` or `docker compose up`

### Expected behavior

Should build without error

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/jamesprendergast/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: e52f462c-b629-465d-9b62-4ca0b3431ed1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

3C38E6D2-EFDE-497A-A98F-F21E86BD5F82/20231020023245

### Additional Info

MacBook Pro
Apple M2
8 Gb memory
OS: ventura (13.2.1)

**Comment by NiklasBr** [comment]
This also happens in Mac OS 14.1 Sonoma:

```
rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
 Trace/breakpoint trap
```

```dockerfile
FROM php:8.1-cli
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["bash"]
```

## Docker info:
```
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/nikbr/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/nikbr/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/nikbr/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/nikbr/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/nikbr/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nikbr/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/nikbr/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/nikbr/.docker/cli-plugins/docker-scout

Server:
 Containers: 26
  Running: 11
  Paused: 0
  Stopped: 15
 Images: 59
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 23.45GiB
 Name: docker-desktop
 ID: 9df56d26-7dbe-46c2-a946-427b0766499b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

## Diagnostics ID
`B99BCF91-9CAF-4D12-AE8B-A4858EC43329/20231026100519`

**Comment by vad0s94** [comment]
![image](https://github.com/docker/for-mac/assets/16398932/29ea81cf-1263-4c1c-a8a7-935ade6e9e03)
try disable this option

**Comment by NiklasBr** [comment]
Well that's today's best laugh!

**Comment by NiklasBr** [comment]
It looks like Orbstack was able to fix this, maybe it is time to migrate?

**Comment by dgageot** [comment]
Hi @NiklasBr, do you have a sample command that triggers the issue?
We are shipping fixed for Rosetta in 4.26.0 and I would like to check if this issue is fixed.

**Comment by NiklasBr** [comment]
@dgageot 

Create a Dockerfile using the example I posted above, then run any Composer command `docker compose run --rm your-docker-project-name composer`

**Comment by NiklasBr** [comment]
@dgageot related and another example of the same thing I think: https://github.com/docker/for-mac/issues/6887#issuecomment-1744646055

**Comment by dgageot** [comment]
@NiklasBr sorry, I don't know compose enough to trigger an issue. Do I need a sample `composer.json` file?

**Comment by NiklasBr** [comment]
You don't even need to install *anything* just like me and the other people are saying,: You can run composer without *any* arguments whatsoever and reproduce the issue 100% of the time.

**Comment by dgageot** [comment]
Thanks @NiklasBr for the details. Although that’s not my experience. I can’t make it fail no matter what I do

**Comment by NiklasBr** [comment]
Again, make sure the docker image is _*not*_ an ARM architecture.

Then, [make sure you are using Rosetta](https://docs.docker.com/desktop/settings/mac/#general).

It's really as simple as that. I can't wrap my head around why you can't reproduce it. Many of us are able to do it with 100% rate, and it has followed along with many updates of both Docker Desktop and the Mac OS operating system.

**Comment by dgageot** [comment]
> Again, make sure the docker image is __not__ an ARM architecture.
> 
> Then, [make sure you are using Rosetta](https://docs.docker.com/desktop/settings/mac/#general).

Yes, all of that I have...

Some of the Rosetta issues were fixed in Sonoma 14.1. Which version of macOS do you have?

**Comment by NiklasBr** [comment]
Sonoma 14.1 on an M1 Max CPU.

**Comment by dgageot** [comment]
I'm on Sonoma 14.1, with a Mac M1 Pro and a Mac M2 Pro. Can't reproduce on any of the last five Docker Desktop versions.

I've tried things more complicated than that but can you tell me if this simple command fails for you?

`docker run --rm -it --platform=linux/amd64 composer/composer install`

**Comment by NiklasBr** [comment]
You need to use and AMD64 image and use Rosetta.....

**Comment by dgageot** [comment]
> You need to use and AMD64 image and use Rosetta.....

Yeah. That's what I've been doing. 
Do you confirm that `docker run --rm -it --platform=linux/amd64 composer/composer install` triggers the issue for you, or not?

I'm sorry to insist but if nobody can give me a command that reproduces the issue, I'll be forced to close this ticket.

**Comment by NiklasBr** [comment]
> Do you confirm that `docker run --rm -it --platform=linux/amd64 composer/composer install` triggers the issue for you, or not?

Your command and setup obviously does not trigger it.

I repeat, the way to trigger it, as mentioned earlier, is to enable Rosetta in Docker Desktop settings, then run an _AMD64 image_ using the following command on an ARM Mac: `docker compose run --rm your-docker-project-name composer`. Why do you insist on using a different command which does not trigger the error?

**Comment by jumakiwaka** [comment]
@dgageot I am facing the same issue on Mac OS Sonoma 14.1 running on Mac pro m2 chip.
Here is sample step by step to replicate

1. Create a docker file as below
```
# Use Amazon Linux 2023 as the base image
FROM --platform=linux/amd64 amazonlinux:2023

# Install PHP 8.1
RUN dnf update \
    && dnf search php8.1 \
    && dnf install php8.1 -y

# Set the entry point to PHP CLI
ENTRYPOINT ["bash"]
```
<img width="707" alt="image" src="https://github.com/docker/for-mac/assets/44918555/818fa629-d017-4f4e-a804-c43d1593e1c6">

2. Build the image using the dockerfile i.e
`docker build --tag "php-8.1-cli" /location/of/Dockerfile`

3. Run the container using the image created above
`docker run -it --rm php-8.1-cli `
<img width="1075" alt="image" src="https://github.com/docker/for-mac/assets/44918555/9f19a34a-0264-44bd-8674-b0b23ae1996e">


4. Inside the container try run php commands like:
`php -v`

Result:
You should see the error below
<img width="527" alt="image" src="https://github.com/docker/for-mac/assets/44918555/92fa773d-0735-40a8-93f2-2c7f877e88c8">

My docker info:

Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/jumakiwaka/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 55
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.758GiB
 Name: linuxkit-2a1f1b2d0463
 ID: 055c4bd8-48dc-4ded-a9ba-7cecc8e48a19
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

Docker Desktop Version: 4.25.1

Please let me know if you have any questions.

**Comment by dgageot** [comment]
Thanks a lot @jumakiwaka. Using your precise instructions, I was able to reproduce.

One way to reproduce it even faster is to run:
```
$ docker run --rm -it --platform=linux/amd64 php bash
```

and then, simply:
```
# php -v
PHP 8.1.25 (cli) (built: Oct 24 2023 21:51:16) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.25, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies
rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
 Trace/breakpoint trap
```

I tried to combine those two commands in one but this **doesn't** fail:
```
$ docker run --rm -it --platform=linux/amd64 php bash -c 'php -v'
```

**Comment by dgageot** [comment]
Here's a simpler way to reproduce:

**Build a php image with opcache enabled:**
```
cat << EOF | docker build -f- --platform=linux/amd64 -t php-opcache /var/empty
FROM php:8.1.25
RUN docker-php-ext-install opcache
RUN echo "[opcache]\nopcache.enable_cli=1" > /usr/local/etc/php/conf.d/opcache.ini
EOF
```

**Run the image:**
```
docker run --rm -it --platform=linux/amd64 php-opcache bash
```

**Type the faulty command:**
```
php -v
```

This fails with php `8.1.25`.
This doesn't fail with any `8.2.X` version of php.

**Comment by dgageot** [comment]
@jumakiwaka could you try to add this to `/usr/local/etc/php/conf.d/opcache.ini`?
```
[opcache]
opcache.preferred_memory_model=shm
```

**Comment by thaJeztah** [comment]
Looks like a fix / improvement was made in Docker Desktop, which will ship with the next release

**Comment by jumakiwaka** [comment]
> @jumakiwaka could you try to add this to `/usr/local/etc/php/conf.d/opcache.ini`?
> 
> ```
> [opcache]
> opcache.preferred_memory_model=shm
> ```

@dgageot  sorry for the late reply. 
I have tried this, but I am still getting the rosetta error
<img width="1071" alt="image" src="https://github.com/docker/for-mac/assets/44918555/b68a97f6-fad8-42e7-863c-f193cf2e9d39">

**Comment by matsaleh13** [comment]
> Looks like a fix / improvement was made in Docker Desktop, which will ship with the next release

Do we know which version includes the fix? I just upgraded to Docker Desktop `4.26.0 (130397)` and the problem still happens for me. 

## Dockerfile
```Dockerfile
FROM --platform=linux/amd64 grafana/k6 

USER root
RUN apk update
```
### Notes
- `grafana/k6` is a load testing utility implemented in Go.
- I use `apk` to install other needed packages, but just running `apk update` is enough to repro.

## Build
```
$ docker build .
[+] Building 1.0s (5/5) FINISHED                                                                                                                                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 1.34kB                                                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/grafana/k6:latest                                                                                                                                                                                       0.3s
 => CACHED [1/2] FROM docker.io/grafana/k6@sha256:c92b70d9015e6c58f58fb10ddf382cfe2fb823a48bb0a1cc3bca31f4a87b65fc                                                                                                                                 0.0s
 => ERROR [2/2] RUN apk update                                                                                                                                                                                                                     0.7s
------
 > [2/2] RUN apk update:
0.100 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
0.388 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
0.621 v3.18.5-17-g1e9547d0183 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
0.621 v3.18.5-18-g8eb8adbd2d7 [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
0.621 OK: 20076 distinct packages available
0.647 rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
0.647
------
Dockerfile:9
--------------------
   7 |     # RUN mkdir -p /app
   8 |
   9 | >>> RUN apk update
  10 |
  11 |     # RUN apk update && \
--------------------
ERROR: failed to solve: process "/bin/sh -c apk update" did not complete successfully: exit code: 133
```




System:
- macOS Ventura 13.6.2 (22G320)
- Apple M1 
- Docker Desktop `4.26.0 (130397)`

**Comment by matsaleh13** [comment]
> ```dockerfile
> FROM --platform=linux/amd64 grafana/k6 
> 
> USER root
> RUN apk update
> ```

Well I found a workaround. This works for my case:
```Dockerfile
FROM --platform=linux/amd64 grafana/k6 

USER root
RUN apk upgrade -U
```

(My real use case calls `apk update` followed by `apk upgrade`, so the above does the same.)

This all seems very non-deterministic to me though. I'll be interested to hear where it lands.

**Comment by dgageot** [comment]
Hi @matsaleh13, a similar issue was fixed with php in Docker Desktop 4.26.0.
The `futex` issue you are seeing is fixed on Rosetta itself, in Sonoma.
I'm on `14.1.1` and can't reproduce your issue

**Comment by matsaleh13** [comment]
> The `futex` issue you are seeing is fixed on Rosetta itself, in Sonoma.

Ohh... do you know whether Apple will backport the fix to Ventura? I guess they're not known too well for that kind of thing, right?

Well, thanks for clarifying that, and thanks for the prompt response!

**Comment by dgageot** [comment]
> Ohh... do you know whether Apple will backport the fix to Ventura? I guess they're not known too well for that kind of thing, right?

Indeed. I don't think they will

**Comment by dgageot** [comment]
I'm going to close this issue. Feel free to reopen if you manage to reproduce on a recent macOS.

**Comment by Chekote** [comment]
This just occurred to me on Mac OS X Sonoma 14.3 when installing PHP FPM 8.1 from the ppa:ondrej/php repo on `ubuntu:atest`.

System info:
![image](https://github.com/docker/for-mac/assets/550486/e9bb7dde-409e-4e2d-8a7d-86e7d59b014c)

Docker settings:
![image](https://github.com/docker/for-mac/assets/550486/71f03c33-e999-401b-8857-f3f99b1cefc9)
![image](https://github.com/docker/for-mac/assets/550486/f55808b1-2503-46a7-8527-6b4bf20954de)
![image](https://github.com/docker/for-mac/assets/550486/c68c62db-6044-413a-b6d4-745eec49d746)

Steps to recreate:

Create the following Dockerfile:
```Dockerfile
FROM ubuntu:latest

RUN set -eu; \
    #
    apt-get update; \
    #
    # Configure ondrej PPA
    apt-get install -y software-properties-common; \
    add-apt-repository ppa:ondrej/php; \
    apt-get update; \
    #
    # Install PHP
    apt-get install -y --no-install-recommends php8.1-fpm; \
    #
    # Make sure everything works
    php-fpm8.1 -v
```

Run the following command:
```shell
docker buildx build --platform linux/amd64
```

**Comment by dgageot** [comment]
@Chekote a fix is one the way. I might be included in Docker Desktop 4.27.1 hot fix.

**Comment by Chekote** [comment]
@dgageot awesome! Thanks for the amazingly fast resolution ❤️

**Comment by dgageot** [comment]
What happened is that in 4.26, we removed the support for Huge Tables that caused issues with php. This was a bit too brutal of a fix but php users were happy.

In 4.27, we put back Huge Tables and added a targeted fix for `php`. We forgot to also target other flavours of php such as `php-cgi*` or `php-fdm*`.

**Comment by dgageot** [comment]
Hi @Chekote! Docker Desktop 4.27.1 is out. Could you tell me if it solves your issue?

**Comment by ryanmunderwood** [comment]
Just updated to `Docker Desktop 4.27.1 (136059)` and am now seeing the following:

```
+ echo 'Starting php-fpm'
+ /opt/remi/php81/root/usr/sbin/php-fpm
Starting php-fpm
[01-Feb-2024 18:07:27] ERROR: no data have been read from pipe
rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35
 /root/web-api-entrypoint.sh: line 64:   894 Trace/breakpoint trap   /opt/remi/php81/root/usr/sbin/php-fpm
 ```

**Comment by thaJeztah** [comment]
@dgageot 4.27.1 is a security release for the runc and buildkit advisories; other patches/fixes will now be in 4.27.2 (next week)

**Comment by ryanmunderwood** [comment]
> @dgageot 4.27.1 is a security release for the runc and buildkit advisories; other patches/fixes will now be in 4.27.2 (next week)

Rolling back to [4.26.1](https://docs.docker.com/desktop/release-notes/#4261) appears to resolve the issue [I mentioned above](https://github.com/docker/for-mac/issues/7037#issuecomment-1921933600) for me, for now. Btw, I noticed the date on the release notes for [4.27.1](https://docs.docker.com/desktop/release-notes/#4271) is also showing 2023-02-01 instead of 2024-02-01, just a heads up :)

**Comment by thaJeztah** [comment]
> I noticed the date on the release notes for [4.27.1](https://docs.docker.com/desktop/release-notes/#4271) is accidentally showing 2023-02-01 instead of 2024-02-01, just a heads up :)

Good catch! Looks like someone fixed it :heart: https://github.com/docker/docs/pull/19289


Also apologies for the confusion for the 4.27.1 release not having these patches; these patches (fixes) were merged already, but the embargoed security took priority, and it's generally good practice not to combine regular fixes with a security release, to prevent possible regressions (which may prevent users from being able to use the security fixes).

**Comment by eolivelli** [comment]
> Hi @Chekote! Docker Desktop 4.27.1 is out. Could you tell me if it solves your issue?

Unfortunately it doesn't. I still see the problem

**Comment by dgageot** [comment]
Hi @Chekote, @eolivelli and @Chekote!
Docker Desktop 4.27.2 is out. Could you tell me if it solves your issue?

**Comment by NiklasBr** [comment]
I still have PHP-FPM issues in 4.27.2: https://github.com/docker/for-mac/issues/7182

Not sure if it is actually Rosetta… But the effect is that 4.27.x is still not stable enough on ARM Mac:s to get an environment up and running :(

**Comment by miksony** [comment]
Temporary fix (worked for me on M1 mac):

- Turn off Rosetta
- Build image
- Turn on Rosetta

**Comment by dgageot** [comment]
> Temporary fix (worked for me on M1 mac):
> 
> * Turn off Rosetta
> * Build image
> * Turn on Rosetta

Building with `EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1 docker build ...` should also work.

**Comment by Chekote** [comment]
@dgageot 4.27.2 resolved [the problem I reported earlier](https://github.com/docker/for-mac/issues/7037#issuecomment-1915309185). I am performing some more builds just to be sure. I'll keep you posted.
