### ISSUE TITLE
Add note about IPv6 incompatability in the release notes

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/for-mac#704]
A few issues here, like #9 & #66, state that IPv6 is not supported on Docker for Mac. However, there is [no mention of this in the documentation](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fdocs.docker.com%2Fdocker-for-mac%2F+ipv6) that I can find.

This is a significant issue and can confuse people with workstations on IPv6 networks. Can you add a note to the Release Notes, perhaps under 'Known Issues'?

**Comment by dsheets** [comment]
Good idea. Sorry for the confusion, we'll add it to the docs ASAP.

**Comment by londoncalling** [comment]
This is now documented and published per the referenced docs PR above
