### ISSUE TITLE
docker hangs in 'starting' after build-attempt with --no-cache --pull

### ISSUE THREAD

**Issue by aikebah** [docker/for-mac#706]
### Expected behavior
docker daemon running smoothly
### Actual behavior
docker daemon hanging hanging in 'starting' even after restarting and after reinstall
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/2DCC474C-0FF4-4E9E-90DD-7800CA38F80D/20160927-115214.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

Don't know what triggered the behaviour
It is now 100% reproducable on my machine by just starting Docker.app. It remains in 'starting docker' forever.
Seems likely to be an issue of corruption of locally stored data by docker that may have been triggered by:
- Kitematic 'stop & remove container' actions
- Kitematic 'refresh containerlist'
- A docker build with options --no-cache --pull

After the docker build with options --no-cache --pull I could not find local images anymore in Kitematic (where I wanted to spin up the newly build container tag) and then noticed docker (which had been up and running) was in restarting mode.

Quit and restarted Docker
Restarted my macbook
Redownloaded and reinstalled Docker.app
Which all did not yet resolve the issue.
[20160927-115214.tar.gz](https://github.com/docker/for-mac/files/495160/20160927-115214.tar.gz)

**Comment by aikebah** [comment]
Resolved it for now by a docker uninstall & reinstall, which basically confirms that it's related to the docker data outside of the docker app (which got removed by the uninstall)

**Comment by samoht** [comment]
Detected symptom of problem 'assertion-failed-hyperkit-50' in 2DCC474C-0FF4-4E9E-90DD-7800CA38F80D/20160927-115214.

There were a number of updates to the hypervisor transport system in the recently released Beta 27. If you are comfortable running a beta (we still do QA on it), you could give that a try and see if it stops the frequent crashing.

May be related to docker/hyperkit#50

The following log matches:
```
Sep 22 17:20:58 Rajah Docker[com.docker.slirp][551] <Notice>: Write offset=0 data=[tcp:0.0.0.0:32774:tcp:172.17.0.5:8080] to file
Sep 22 17:20:58 Rajah Docker[com.docker.slirp][551] <Notice>: attempting a best-effort bind of ::1:32774
Sep 22 17:20:58 Rajah Docker[com.docker.slirp][551] <Notice>: Created instance tcp:0.0.0.0:32774:tcp:172.17.0.5:8080
Sep 22 17:20:58 Rajah Docker[com.docker.slirp][551] <Error>: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Sep 22 17:22:13 Rajah Docker[com.docker.driver.amd64-linux][554] <Notice>: Assertion failed: (!REPLY_RING_EMPTY(sc)), function send_response_common, file src/pci_virtio_sock.c, line 950.
Sep 22 17:22:13 Rajah Docker[com.docker.driver.amd64-linux][554] <Notice>: virtio-net-vpnkit: initialising, opts="uuid=df7f3f6a-f6d1-48a2-a365-892c5e2b12d8,path=/Users/aikebah/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/aikebah/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Sep 22 17:22:13 Rajah Docker[com.docker.driver.amd64-linux][554] <Notice>: Interface will have uuid df7f3f6a-f6d1-48a2-a365-892c5e2b12d8
```
