### ISSUE TITLE
Docker Desktop Kubernetes will not start after upgrading to OSX Sonoma

### ISSUE THREAD

**Issue by jakepearson** [docker/for-mac#7063]
### Description

I upgraded my M1 Macbook Pro to Sonoma this morning and after the upgrade I cannot get Kubernetes to start in Docker Desktop. Looks like the api server won't start. Here is an example error that is coming from pod:

```text
2023-11-07 11:18:40 W1107 18:18:40.912772       1 logging.go:59] [core] [Channel #3 SubChannel #5] grpc: addrConn.createTransport failed to connect to {
2023-11-07 11:18:40   "Addr": "127.0.0.1:2379",
2023-11-07 11:18:40   "ServerName": "127.0.0.1",
2023-11-07 11:18:40   "Attributes": null,
2023-11-07 11:18:40   "BalancerAttributes": null,
2023-11-07 11:18:40   "Type": 0,
2023-11-07 11:18:40   "Metadata": null
2023-11-07 11:18:40 }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused"
```

I have reinstalled, rebooted, cleared out config get to the same spot with the apiserver in a crashloop.

### Reproduce

1. Start docker desktop
2. Open the settings
3. Containers will show 2 in crashloop
    1. apiserver with the above exception
    2. kube-controller with `2023-11-07 11:59:01 E1107 18:59:01.289484       1 controllermanager.go:235] "Error building controller context" err="failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get \"https://192.168.65.3:6443/healthz\": dial tcp 192.168.65.3:6443: connect: connection refused"`

![image](https://github.com/docker/for-mac/assets/325306/e012d75d-0e00-4a08-b8c3-55ec15b70869)

### Expected behavior

Kubernetes should start

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/jake/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/jake/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jake/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jake/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/jake/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jake/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jake/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/jake/.docker/cli-plugins/docker-scout

Server:
 Containers: 10
  Running: 6
  Paused: 0
  Stopped: 4
 Images: 10
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.661GiB
 Name: linuxkit-0a21430eda14
 ID: e23d1a13-2cd6-4293-ae64-20e2f8438e42
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

886dd01b-2a67-4631-8feb-2193328adaac/20231107185622

**Comment by jkugler** [comment]
This is also affecting me. I disabled Kubernetes, removed all containers, enabled Kubernetes, watched it download all the containers, but it just stayed spinning at "Starting..."

Diagnostics ID: DC63B504-D90C-4B3C-A2C6-E9394AABB169/20231110234212

Version
```
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Info
```
$ docker info
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/tek30584/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/tek30584/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/tek30584/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/tek30584/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/tek30584/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/tek30584/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/tek30584/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/tek30584/.docker/cli-plugins/docker-scout

Server:
 Containers: 11
  Running: 5
  Paused: 0
  Stopped: 6
 Images: 13
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 19.51GiB
 Name: linuxkit-76ef47de353b
 ID: d524a2c8-aace-4a84-9297-752f46015654
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```
Images
```
$ docker image ls --all
REPOSITORY                                                TAG                                                                          IMAGE ID       CREATED         SIZE
hubproxy.docker.internal:5555/docker/desktop-kubernetes   kubernetes-v1.28.2-cni-v1.3.0-critools-v1.28.0-cri-dockerd-v0.3.4-1-debian   19d261e62622   4 weeks ago     411MB
registry.k8s.io/kube-apiserver                            v1.28.2                                                                      30bb499447fe   8 weeks ago     120MB
registry.k8s.io/kube-proxy                                v1.28.2                                                                      7da62c127fc0   8 weeks ago     68.3MB
registry.k8s.io/kube-scheduler                            v1.28.2                                                                      64fc40cee371   8 weeks ago     57.8MB
registry.k8s.io/kube-controller-manager                   v1.28.2                                                                      89d57b83c178   8 weeks ago     116MB
registry.k8s.io/kube-apiserver                            v1.27.2                                                                      72c9df6be7f1   5 months ago    115MB
registry.k8s.io/kube-scheduler                            v1.27.2                                                                      305d7ed1dae2   5 months ago    56.2MB
registry.k8s.io/kube-controller-manager                   v1.27.2                                                                      2ee705380c3c   5 months ago    107MB
docker/desktop-vpnkit-controller                          dc331cb22850be0cdd97c84a9cfecaf44a1afb6e                                     3750dfec169f   5 months ago    35MB
registry.k8s.io/coredns/coredns                           v1.10.1                                                                      97e04611ad43   9 months ago    51.4MB
registry.k8s.io/etcd                                      3.5.7-0                                                                      24bc64e91103   9 months ago    181MB
registry.k8s.io/pause                                     3.9                                                                          829e9de338bd   13 months ago   514kB
```
One thing I did notice was that some of the images are at version 1.27.2, and are much older than the 1.28.2 images.

**Comment by pdqn** [comment]
Can you try the steps recommended here https://github.com/docker/for-mac/issues/7056#issuecomment-1793457644 it worked for me.

**Comment by jakepearson** [comment]
@pdqn sorry those steps didn't work for me.

**Comment by WeiCSir** [comment]
I have the same problem with my M2 mac and docker desktop is 4.25.2 (129061).
![CleanShot 2023-11-23 at 15 39 22@2x](https://github.com/docker/for-mac/assets/49602537/fdd047bc-c6ca-407d-a849-1f0c64fcbb2b)
![CleanShot 2023-11-23 at 15 40 30@2x](https://github.com/docker/for-mac/assets/49602537/cff3a553-9509-4634-8b6e-09a651419b98)

**Comment by ByteFlyCoding** [comment]
> @pdqn sorry those steps didn't work for me. Thanks for the suggestion.

Me too.

**Comment by ByteFlyCoding** [comment]
> This is also affecting me. I disabled Kubernetes, removed all containers, enabled Kubernetes, watched it download all the containers, but it just stayed spinning at "Starting..."
> 
> Diagnostics ID: DC63B504-D90C-4B3C-A2C6-E9394AABB169/20231110234212
> 
> Version
> 
> ```
> $ docker version
> Client:
>  Cloud integration: v1.0.35+desktop.5
>  Version:           24.0.6
>  API version:       1.43
>  Go version:        go1.20.7
>  Git commit:        ed223bc
>  Built:             Mon Sep  4 12:28:49 2023
>  OS/Arch:           darwin/arm64
>  Context:           desktop-linux
> 
> Server: Docker Desktop 4.25.0 (126437)
>  Engine:
>   Version:          24.0.6
>   API version:      1.43 (minimum version 1.12)
>   Go version:       go1.20.7
>   Git commit:       1a79695
>   Built:            Mon Sep  4 12:31:36 2023
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.6.22
>   GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
>  runc:
>   Version:          1.1.8
>   GitCommit:        v1.1.8-0-g82f18fe
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> Info
> 
> ```
> $ docker info
> Client:
>  Version:    24.0.6
>  Context:    desktop-linux
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.11.2-desktop.5
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.23.0-desktop.1
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-compose
>   dev: Docker Dev Environments (Docker Inc.)
>     Version:  v0.1.0
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-dev
>   extension: Manages Docker extensions (Docker Inc.)
>     Version:  v0.2.20
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-extension
>   init: Creates Docker-related starter files for your project (Docker Inc.)
>     Version:  v0.1.0-beta.9
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-init
>   sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
>     Version:  0.6.0
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-sbom
>   scan: Docker Scan (Docker Inc.)
>     Version:  v0.26.0
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-scan
>   scout: Docker Scout (Docker Inc.)
>     Version:  v1.0.9
>     Path:     /Users/tek30584/.docker/cli-plugins/docker-scout
> 
> Server:
>  Containers: 11
>   Running: 5
>   Paused: 0
>   Stopped: 6
>  Images: 13
>  Server Version: 24.0.6
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Using metacopy: false
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
>  runc version: v1.1.8-0-g82f18fe
>  init version: de40ad0
>  Security Options:
>   seccomp
>    Profile: unconfined
>   cgroupns
>  Kernel Version: 6.4.16-linuxkit
>  Operating System: Docker Desktop
>  OSType: linux
>  Architecture: aarch64
>  CPUs: 10
>  Total Memory: 19.51GiB
>  Name: linuxkit-76ef47de353b
>  ID: d524a2c8-aace-4a84-9297-752f46015654
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  HTTP Proxy: http.docker.internal:3128
>  HTTPS Proxy: http.docker.internal:3128
>  No Proxy: hubproxy.docker.internal
>  Experimental: false
>  Insecure Registries:
>   hubproxy.docker.internal:5555
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: daemon is not using the default seccomp profile
> ```
> 
> Images
> 
> ```
> $ docker image ls --all
> REPOSITORY                                                TAG                                                                          IMAGE ID       CREATED         SIZE
> hubproxy.docker.internal:5555/docker/desktop-kubernetes   kubernetes-v1.28.2-cni-v1.3.0-critools-v1.28.0-cri-dockerd-v0.3.4-1-debian   19d261e62622   4 weeks ago     411MB
> registry.k8s.io/kube-apiserver                            v1.28.2                                                                      30bb499447fe   8 weeks ago     120MB
> registry.k8s.io/kube-proxy                                v1.28.2                                                                      7da62c127fc0   8 weeks ago     68.3MB
> registry.k8s.io/kube-scheduler                            v1.28.2                                                                      64fc40cee371   8 weeks ago     57.8MB
> registry.k8s.io/kube-controller-manager                   v1.28.2                                                                      89d57b83c178   8 weeks ago     116MB
> registry.k8s.io/kube-apiserver                            v1.27.2                                                                      72c9df6be7f1   5 months ago    115MB
> registry.k8s.io/kube-scheduler                            v1.27.2                                                                      305d7ed1dae2   5 months ago    56.2MB
> registry.k8s.io/kube-controller-manager                   v1.27.2                                                                      2ee705380c3c   5 months ago    107MB
> docker/desktop-vpnkit-controller                          dc331cb22850be0cdd97c84a9cfecaf44a1afb6e                                     3750dfec169f   5 months ago    35MB
> registry.k8s.io/coredns/coredns                           v1.10.1                                                                      97e04611ad43   9 months ago    51.4MB
> registry.k8s.io/etcd                                      3.5.7-0                                                                      24bc64e91103   9 months ago    181MB
> registry.k8s.io/pause                                     3.9                                                                          829e9de338bd   13 months ago   514kB
> ```
> 
> One thing I did notice was that some of the images are at version 1.27.2, and are much older than the 1.28.2 images.

I think these problem maybe cause by the upgraded kubernerts version, that is upgraded from 1.27.2 into 1.28.2 on docker-desktop v1.25.0.

**Comment by ByteFlyCoding** [comment]
> I think these problem maybe cause by the upgraded kubernerts version, that is upgraded from v1.27.2 into v1.28.2 on docker-desktop v4.25.0.

I think these problem maybe cause by the upgraded kubernerts version, that is upgraded from v1.27.2 into v1.28.2 on docker-desktop v4.25.0.

**Comment by ByteFlyCoding** [comment]
> ### Description
> I upgraded my M1 Macbook Pro to Sonoma this morning and after the upgrade I cannot get Kubernetes to start in Docker Desktop. Looks like the api server won't start. Here is an example error that is coming from pod:
> 
> ```
> 2023-11-07 11:18:40 W1107 18:18:40.912772       1 logging.go:59] [core] [Channel #3 SubChannel #5] grpc: addrConn.createTransport failed to connect to {
> 2023-11-07 11:18:40   "Addr": "127.0.0.1:2379",
> 2023-11-07 11:18:40   "ServerName": "127.0.0.1",
> 2023-11-07 11:18:40   "Attributes": null,
> 2023-11-07 11:18:40   "BalancerAttributes": null,
> 2023-11-07 11:18:40   "Type": 0,
> 2023-11-07 11:18:40   "Metadata": null
> 2023-11-07 11:18:40 }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused"
> ```
> 
> I have reinstalled, rebooted, cleared out config get to the same spot with the apiserver in a crashloop.
> 
> ### Reproduce
> 1. Start docker desktop
> 2. Open the settings
> 3. Containers will show 2 in crashloop
>    
>    1. apiserver with the above exception
>    2. kube-controller with `2023-11-07 11:59:01 E1107 18:59:01.289484       1 controllermanager.go:235] "Error building controller context" err="failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get \"https://192.168.65.3:6443/healthz\": dial tcp 192.168.65.3:6443: connect: connection refused"`
> 
> ![image](https://private-user-images.githubusercontent.com/325306/281151710-e012d75d-0e00-4a08-b8c3-55ec15b70869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzI4MzIsIm5iZiI6MTcwMTkzMjUzMiwicGF0aCI6Ii8zMjUzMDYvMjgxMTUxNzEwLWUwMTJkNzVkLTBlMDAtNGEwOC1iOGMzLTU1ZWMxNWI3MDg2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwNzAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGFmYzcxNzFmMDk2NTBkNGNhYjA0ODgwYWU4ZjQ4NGNjNTdlNDVkYjcyN2Y5MWRkMDEyZTEwZWNmZmZlYjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ad1yO-LhWXKsJ_J1KaTPzrqnQNt9wMXv-qesfJkuku0)
> 
> ### Expected behavior
> Kubernetes should start
> 
> ### docker version
> ```shell
> Client:
>  Cloud integration: v1.0.35+desktop.5
>  Version:           24.0.6
>  API version:       1.43
>  Go version:        go1.20.7
>  Git commit:        ed223bc
>  Built:             Mon Sep  4 12:28:49 2023
>  OS/Arch:           darwin/arm64
>  Context:           desktop-linux
> 
> Server: Docker Desktop 4.25.0 (126437)
>  Engine:
>   Version:          24.0.6
>   API version:      1.43 (minimum version 1.12)
>   Go version:       go1.20.7
>   Git commit:       1a79695
>   Built:            Mon Sep  4 12:31:36 2023
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.6.22
>   GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
>  runc:
>   Version:          1.1.8
>   GitCommit:        v1.1.8-0-g82f18fe
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> ### docker info
> ```shell
> Client:
>  Version:    24.0.6
>  Context:    desktop-linux
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.11.2-desktop.5
>     Path:     /Users/jake/.docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.23.0-desktop.1
>     Path:     /Users/jake/.docker/cli-plugins/docker-compose
>   dev: Docker Dev Environments (Docker Inc.)
>     Version:  v0.1.0
>     Path:     /Users/jake/.docker/cli-plugins/docker-dev
>   extension: Manages Docker extensions (Docker Inc.)
>     Version:  v0.2.20
>     Path:     /Users/jake/.docker/cli-plugins/docker-extension
>   init: Creates Docker-related starter files for your project (Docker Inc.)
>     Version:  v0.1.0-beta.9
>     Path:     /Users/jake/.docker/cli-plugins/docker-init
>   sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
>     Version:  0.6.0
>     Path:     /Users/jake/.docker/cli-plugins/docker-sbom
>   scan: Docker Scan (Docker Inc.)
>     Version:  v0.26.0
>     Path:     /Users/jake/.docker/cli-plugins/docker-scan
>   scout: Docker Scout (Docker Inc.)
>     Version:  v1.0.9
>     Path:     /Users/jake/.docker/cli-plugins/docker-scout
> 
> Server:
>  Containers: 10
>   Running: 6
>   Paused: 0
>   Stopped: 4
>  Images: 10
>  Server Version: 24.0.6
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Using metacopy: false
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
>  runc version: v1.1.8-0-g82f18fe
>  init version: de40ad0
>  Security Options:
>   seccomp
>    Profile: unconfined
>   cgroupns
>  Kernel Version: 6.4.16-linuxkit
>  Operating System: Docker Desktop
>  OSType: linux
>  Architecture: aarch64
>  CPUs: 10
>  Total Memory: 7.661GiB
>  Name: linuxkit-0a21430eda14
>  ID: e23d1a13-2cd6-4293-ae64-20e2f8438e42
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  HTTP Proxy: http.docker.internal:3128
>  HTTPS Proxy: http.docker.internal:3128
>  No Proxy: hubproxy.docker.internal
>  Experimental: false
>  Insecure Registries:
>   hubproxy.docker.internal:5555
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: daemon is not using the default seccomp profile
> ```
> 
> ### Diagnostics ID
> 886dd01b-2a67-4631-8feb-2193328adaac/20231107185622
> 
> ### Additional Info
> _No response_

I think these problem maybe cause by the upgraded kubernerts version, that is upgraded from v1.27.2 into v1.28.2 on docker-desktop v4.25.0.

**Comment by jakepearson** [comment]
@ByteFlyCoding is there a way to configure the K8S version that docker desktop uses?

**Comment by ByteFlyCoding** [comment]
> @ByteFlyCoding is there a way to configure the K8S version that docker desktop uses?

None, but Maybe docker official will support this feature.

**Comment by joshuabrewer13** [comment]
I had this issue after an upgrade on Mac.  Nothing worked for because I wasn't able to click and apply the `Reset Kubernetes Button` anywhere until I did the following:

1. Force kill everything docker related
2. edit ~/Library/Group\ Containers/group.com.docker/settings.json
3. set "kubernetesEnabled": false
4. Start docker desktop again
5. Click the checkbox to enable kubernetes in settings (don't click apply yet)
6. click the Reset Kubernetes Cluster button then click apply.

**Comment by jakepearson** [comment]
@joshuabrewer13 Thanks for the suggestion, but those steps didn't work for me.

**Comment by rajjaiswalsaumya** [comment]
Is there a solution to this, i am also facing this issue and cant work with Kubernetes with docker desktop :(

**Comment by ByteFlyCoding** [comment]
Now, I can start the k8s of docker-desktop. This maybe cause by network and mirror registry. Because I use third party mirror registry. Some of docker images of third party registry are behind latest, so I only pull old image. That result in that  k8s of docker-decktop failed to start. After using a proxy to pull images from official mirror registry, I found that  the k8s can start successfully.

**Comment by jakepearson** [comment]
This morning I upgraded the latest docker desktop and K8S started right up. Thanks everyone.

**Comment by banepavl** [comment]
Hi, I had the same issue with starting Kubernetes on Docker Desktop (MacBook Pro M1),
and did the following steps to sort it out:

- I opened `Console` application to be able to see Docker Desktop logs
- Started logs streaming, in the search bar I entered `kubernetes` (you can type in `docker` as well) keyword to filter logs
- Tried to enable Kubernetes in Docker Desktop 
- I could see that there's an `Error 500` and that it fails to pull image named `docker/desktop-kubernetes:kubernetes-v1.29.1-cni-v1.4.0-critools-v1.29.0-cri-dockerd-v0.3.8-1-debian`
- I pulled the image manually through console with `docker pull docker/desktop-kubernetes:kubernetes-v1.29.1-cni-v1.4.0-critools-v1.29.0-cri-dockerd-v0.3.8-1-debian`
- Then went back to Docker Desktop, pressed Reset Kubernetes Cluster and finally was able to enable Kubernetes

I hope this will be useful to someone.
