### ISSUE TITLE
PLEASE provide old version downloads, even if unsupported. 

### ISSUE THREAD

**Issue by kupietools** [docker/for-mac#7067]
### Description

The version history page gives absolutely no download link for versions before about a year ago. https://github.com/docker/for-mac/issues/6845 says a download link for v4.6.0 was available there in May but danged if I can find one. 

Nobody is asking for support or for you to consider it not "end of life". I'm just saying, making people throw away old but still perfectly functional computers because it's convenient to you to force them to is a bad idea on a number of levels, starting with the fact that it's extremely wasteful. I could very easily use this machine for a docker container that would be very convenient for me to have running on a machine somewhere. 

I'm not asking for any support at all or for you to lift a finger or anyone at docker or in these forums to ever have to deal with the fact that I am running it. I am just asking for the installer to be made available, with the understanding that after that you aren't willing to hear another peep about it, because forced obsolence of 100% working hardware and software is wasteful and unnecessary, not to mention the fact that I'm simply not going to do it. This is the spare machine I have, not a newer one, and it would be usable for my purposes except that docker seems to have declared that it shall not be so for me. 

Before anyone suggests it, I won't be installing Catalina on this machine, because I have other old apps I need to use regularly that won't run on Catalina and I need to keep at least one Mojave machine around. 

Is there really any practical reason to at least provide completely unsupported installers for past versions for people who need them? I see in the forums here that I am not the only person who needs them. And, again, forcing old computers that still work into unilaterally-declared obsolescence just isn't a good plan, as far as I can see. We should be recycling their uses and getting as much life out of them as possible before sending them to sit for centuries leaching environmental toxins into a landfill. 

Even just providing a one-time download link for 4.6.0 in reply to this would suffice for my purposes. Nobody needs to change the documentation or anything. 

Thanks.

### Reproduce

1. Google for "docker desktop" "4.6.0" "mac" "intel" "installer".
2. Numerous results say old versions are available from https://docs.docker.com/desktop/release-notes/
3. Go to https://docs.docker.com/desktop/release-notes/

### Expected behavior

Find a link somewhere on https://docs.docker.com/desktop/release-notes/ to download Docker Desktop 4.6.0 for Intel Mac. 

### docker version

```bash
4.6.0
```

### docker info

```bash
n/a
```

### Diagnostics ID

n/a

### Additional Info

MacOS Mojave 10.14.6 on mid-2012 MacBook Pro

**Comment by kupietools** [comment]
Hey there, if anyone else needs this information, I was able to excavate a recent version of the page, from this past August, when they still were posting download links back to version 4.0.0, from https://web.archive.org/web/20230911135706/https://docs.docker.com/desktop/release-notes/ . 

I successfully downloaded 4.6.0 from https://desktop.docker.com/mac/main/amd64/75818/Docker.dmg . 

The full list of direct download links back to 4.0.0, copied from that archive.org page, is posted in a gist at https://gist.github.com/kupietools/2f9f085228d765da579f0f0702bec33c . 

Still, I think Docker Desktop should maintain links to old downloads to people don't have to hunt. It seems like a really minimal effort. MacPorts, for example, still offers download packages dating back to OS X 10.4, which was released in 2005. Mamma mia, datsa gooda user-friendliness.

**Comment by Alevale** [comment]
@bsousaa Could you please have a look at this?

Having people creating gists for older versions feels quite dangerous and having the need to download old versions is fairly common for systems that last longer than what a personal project does.

Please, could you escalate with the rest of the docker team? **_Ideally it would stay in the docker releases page_**
