### ISSUE TITLE
docker login to AWS hangs in version 1.12.1 (build: 12133) on OSX 10.11.6

### ISSUE THREAD

**Issue by mogrifier** [docker/for-mac#707]
### Expected behavior

docker should login to AWS and give you back the command line to use for subsequnet docker commands using the AWS ecr
### Actual behavior

command hangs. Only output is 'Flag --email has been deprecated, will be removed in 1.13.'
### Information

OS X El Capitan 10.11.6
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
  I'd love to provide the output. Docker client hangs on 'Diagnosing'. 5 minutes and counting. Never provides output or a diagnostic ID.
### Steps to reproduce the behavior

You need the aws cli tool for this. Problem is specific to working with the AWS ECR.
1. run "aws ecr get-login"
2. Copy the output from above command (docker login -u AWS -p ...)
3. Paste to command line and hit enter
4. docker hangs

**Comment by samoht** [comment]
Which version of Docker for Mac are you running? Could you try running the diagnostic tool manually?

```
 /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
```

This will upload your logs to our diagnostic server so that we can investigate your issue. Thanks!

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by helenaford** [comment]
I'm having the same issue.

**Comment by mogrifier** [comment]
I solved my specific problem by completely uninstalling and re-installing docker. Dragging the app to the trash was not enough. I went in and manually deleted other docker related files from somewhere in /Library or /Applications- can't recall exactly but you could look up where it puts files during install.

**Comment by jasperboyd** [comment]
Stuck on this issue tried @helenaford and @mogrifier solutions above with no luck

Diagnostic ID: 63028C89-CE51-4D03-8C1D-C0DF8F557119

**Comment by towens** [comment]
It only seems to hang if you take the interactive route.
```eval $(aws ecr get-login --no-include-email)```
Succeeds.
