### ISSUE TITLE
After quitting Docker Desktop on Mac, it does not properly launch again until reboot

### ISSUE THREAD

**Issue by rmeske** [docker/for-mac#7084]
### Description

I can successfully launch the Docker Desktop and everything works.  If I quit the Docker Desktop and then later try to launch it again, the gui never displays though Activity Monitor shows it running.  However, it is not shown in the Dock and cannot switch to it with keyboard, nor is it shown in the App Switcher list.  It is not listed in Force Quit Applications.  Even though it seems to be running in the back ground somewhere, the only way to get it to display is to go to the Apple Menu -> Recents and select it from there.  It then immediately displays as if it was hidden.

Update, if I only use Apple Menu->Recents Docker Desktop after closing it, it will put the icon back in the recents area but it will not be shown.  I have to click it a second time to get it to show.

### Reproduce

1. Boot OS
2. Launch Docker Desktop
3. Quit Docker Desktop
4. Wait a few minutes and verify that Activity monitor shows all process for docker have closed
5. Launch Docker Desktop
6. The icon briefly shows in the Dock and then Disappears and it does not show the application
7. Check Activity Monitor to verify docker processes are running
8. Check Dock for running app, not shown
9. Try using the App Switcher, not shown
10. Open Apple menu and select Recent and select the Docker Desktop app

### Expected behavior

When launching it should show the application without needing to reboot

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/ronmeske/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.662GiB
 Name: linuxkit-ee61e9e6873b
 ID: 9c83dd61-aeaa-4a26-b2a3-b9048a9785bb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

4214DC72-C354-4F72-96E1-7040B6538F62/20231122170249

### Additional Info

System
[docker_shutdown_relaunch.txt](https://github.com/docker/for-mac/files/13442971/docker_shutdown_relaunch.txt)

Mac Intel
macOS: Ventura 13.6.1

**Comment by MihaelaStoica** [comment]
> 5. Launch Docker Desktop
> 6. The icon briefly shows in the Dock and then Disappears and it does not show the application
> 7. Check Activity Monitor to verify docker processes are running
> 8. Check Dock for running app, not shown
> 9. Try using the App Switcher, not shown
> 10. Open Apple menu and select Recent and select the Docker Desktop app

@rmeske, if you have the "Open Docker Dashboard when Docker Desktop starts" setting disabled, then the above observations are the expected behaviour. The app is up and running, but no window is open. You should, however, see the Docker Desktop (whale) icon in the Menu bar and access its menu from there, where "Go to Dashboard" should open the Dashboard window and show the app in the Dock as well.
If you don't have the whale icon in the Menu bar, then that would be a bug. Please check and let us know.
