### ISSUE TITLE
Docker Desktop unable to run on Apple M3 Pro

### ISSUE THREAD

**Issue by mccarthydanielle** [docker/for-mac#7090]
### Description

Docker Desktop is not compatible with Apple M3 Pro  running Sonoma 14.1. When I download Docker Desktop and open up the application the following error message appears. I deleted and redownloaded the app and the same behavior occurs. I also clicked restore to factory defaults and it still does not open. 

<img width="326" alt="Screenshot 2023-11-27 at 10 00 09 AM" src="https://github.com/docker/for-mac/assets/32887144/7d99e4e7-8ed6-421d-aaf3-6a5e65d21c0c">

### Reproduce

1. Download Docker Desktop for Mac Apple Chip https://www.docker.com/products/docker-desktop/ 
2. Open Docker Desktop on M3 Pro 
3. This error message pops up:
`Setting up backend: checking compatibility: required compatibility check: Incompatible CPU detected`

### Expected behavior

Docker Desktop opens successfully on M3 Pro

### docker version

```bash
Docker CLI command is not available since Docker Desktop is not getting installed properly. When I run docker version I get:

command not found: docker
```

### docker info

```bash
Docker CLI command is not available since Docker Desktop is not getting installed properly. When I run docker info I get: 

command not found: docker
```

### Diagnostics ID

I cannot run diagnostics

**Comment by jcitalan** [comment]
the same thing happened to me, I only downloaded one version less than the current one.

**Comment by RomanShcherbich** [comment]
I downloaded 4.29.0 from here https://docs.docker.com/desktop/release-notes/. It works.

**Comment by kuba-leman** [comment]
yea docker desktop works, but containers are really slow on m3, bind volume is big problem

**Comment by damanzano** [comment]
I downloaded 4.34.0 from here https://docs.docker.com/desktop/release-notes/. It works. 4.30.1 still has issues
