### ISSUE TITLE
GPL source code for Docker Desktop kernel 6.5.11-linuxkit

### ISSUE THREAD

**Issue by comex** [docker/for-mac#7108]
### Description

Hi, I'm trying to diagnose a kernel issue that I can only reproduce in Docker Desktop.  For this I would like the source code for the kernel I'm running:
```
Linux docker-desktop 6.5.11-linuxkit #1 SMP PREEMPT Mon Dec  4 11:30:00 UTC 2023 aarch64 Linux
```

I notice that some versions are published at https://hub.docker.com/r/docker/for-desktop-kernel/tags, while some older versions are at https://github.com/linuxkit/linux/tags, but neither of those seems to contain a tag for `6.5.11-linuxkit`.

Can you please provide the source code as required by the GPL?  Thanks.

(If you happen to have debug symbols for the existing binary, those would be nice too.)

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.26.0 (130397)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dgageot** [comment]
@comex I'm working on refactoring this process. I'll keep you posted

**Comment by dgageot** [comment]
@comex FYI, from version 4.27 onwards, Docker Desktop will ship with the source and version of the kernel we're using, the config, all our patches and kernel modules.

**Comment by dgageot** [comment]
@comex from version 4.27 onwards, Docker Desktop ships with the source and version of the kernel we're using, the config, all our patches and kernel modules.
`docker run --privileged --pid=host --rm -it justincormack/nsenter1 /usr/bin/tree /usr/src`
