### ISSUE TITLE
Exception while trying to pull image from docker hub

### ISSUE THREAD

**Issue by mukteshkrmishra** [docker/for-mac#711]
HI, 

I am getting following exceptin while trying to pull an image from docker hub. 

Please note this problem has started after upgrading to latest docker version app.

docker pull tomcat
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Error response from daemon: dial unix /Users/Test/Library/Containers/com.docker.docker/Data/_00000003.00000948: connect: connection refused). Using system default: https://index.docker.io/v1/
Error response from daemon: dial unix /Users/Test/Library/Containers/com.docker.docker/Data/_00000003.00000948: connect: connection refused

**Comment by dsheets** [comment]
Could you please run `Diagnose & Feedback` from the :whale: menu, select `Diagnose & Upload`, and post the results here? In particular, the diagnostic ID would be very helpful in investigating your issue. Thanks!

**Comment by samoht** [comment]
I am closing the issue as it has been inactive for more than 2 weeks. Please feel free to re-open it with more info.
