### ISSUE TITLE
This could be the end of Docker for us. More networking issues

### ISSUE THREAD

**Issue by cwbeck** [docker/for-mac#714]
### Expected behavior

Docker exposes ports
### Actual behavior

Docker does not expose ports
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior

Upgrade to version 1.12. -- Multiple issues.

Purged docker and re-installed 1.12.

RUN our standard machine build.

```
users-MacBook-Pro:market user$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                         NAMES
1149e09c27b2        market:0.1          "/start.sh"         6 minutes ago       Up 6 minutes        0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   market
```

Docker machine is running...

```
users-MacBook-Pro:market user$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.1   
```

IP claims to be: 192.168.99.100

```
users-MacBook-Pro:market user$ docker-machine ip default
192.168.99.100
```

Yet unable to see 192.168.99.100:8080 or anything else we try and map to. Was working with previous versions of docker. What is going on?

**Comment by djs55** [comment]
Are you intending to use Docker for Mac or Docker Toolbox?

One difference between the two is that Docker for Mac exposes ports on the Mac's local interfaces like Docker on Linux -- perhaps try `curl http://localhost:8080`?

If you'd rather use Docker Toolbox than Docker for Mac then make sure you set the environment variables to talk to the right docker daemon:
```
eval "$(docker-machine env default)"
```
If you have time then have a look at [Docker for Mac vs. Docker Toolbox](https://docs.docker.com/docker-for-mac/docker-toolbox/) in the online docs.

**Comment by cwbeck** [comment]
The issue list is still growing. Seems VirtualBox could be the culprit here. Is there an alternative engine/driver on Mac to this? - Ubuntu setup works just fine for everything.

**Comment by justincormack** [comment]
You can install Docker for Mac https://docs.docker.com/docker-for-mac/ which does not use Virtualbox. This is the support area for Docker for Mac, not for Toolbox, so slightly confused but it looks like you are not using it.

**Comment by cwbeck** [comment]
I've been using both products. I have Docker for Mac too. Problems encountered on Toolbox forced a move away from it. Docker for Mac does not seem to enable us to run multiple ips unless I've missed something. localhost is not enough.

**Comment by djs55** [comment]
Docker for Mac 1.12.1 should allow ports to be exposed on any interface of the Mac (it was broken in 1.12.0). For example:
```
$ docker run -p 192.168.1.103:80:80 nginx
```
exposes `nginx` on my wifi IP 192.168.1.103. Does that help at all?

**Comment by cwbeck** [comment]
This helps massively - 1.12.0 was the issue then! Tried everything to get your above example to work before.

**Comment by justincormack** [comment]
@cwbeck ah ok. See this comment https://github.com/docker/docker/issues/22753#issuecomment-246054946 for how to set up multiple IP addresses on the Mac attached to different hosts and publish ports to them.

**Comment by cwbeck** [comment]
seems there is a limit issue on ranges?

docker: Error response from daemon: driver failed programming external connectivity on endpoint market (d1133ef6e8d7b3b8ad7e68831e9d1f70f5255b0f3a15ccf927f6920915142dcb): Error starting userland proxy: Bind for 172.168.0.101:80: unexpected error (Failure EADDRNOTAVAIL).

running 1.12.1

**Comment by justincormack** [comment]
Did you mean `192.168.0.101`?

**Comment by cwbeck** [comment]
Any IP - the comment you linked to does not seem to be resolved.

ff3aab6775f7b8412e0ffef2f81f216ff43a493f9c7be605d4947060d0db0210
docker: Error response from daemon: driver failed programming external connectivity on endpoint market (01455862dc31b8ae583c7f51c4d89a96aa7b4e24b68dfcb9e9b4c8034f424186): Error starting userland proxy: Bind for 192.168.0.101:80: unexpected error (Failure EADDRNOTAVAIL).

**Comment by djs55** [comment]
Could you check the exact version you're running? In "Whale menu -> About Docker" I have:

> Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856

The version reporting as 1.12.0 will still have the bug where we called `bind` also inside the VM, with an IP which was only present on the Mac, hence `EADDRNOTAVAIL`.

On my host I have:
```
$ ifconfig en0 | grep netmask
	inet 192.168.1.103 netmask 0xffffff00 broadcast 192.168.1.255
```
and this command works:
```
docker run -p 192.168.1.103:8081:80 nginx
```
whereas this one fails with `EADDRNOTAVAIL`:
```
docker run -p 192.168.1.104:8081:80 nginx
docker: Error response from daemon: driver failed programming external connectivity on endpoint clever_khorana (0c8fe7f6d3fd419bc9ae6ac9e11d47fc4800f0ad97cf14c73064b0a6b142d16b): Error starting userland proxy: listen tcp 192.168.1.104:8081: bind: cannot assign requested address.
```
Could you post the full command-line you're using and information about your network interfaces (`ifconfig`)?

**Comment by cwbeck** [comment]
```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet 127.94.0.1 netmask 0xff000000 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 20:c9:d0:87:d0:ff 
	inet6 fe80::22c9:d0ff:fe87:d0ff%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.2.19 netmask 0xffffff00 broadcast 192.168.2.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 32:00:19:f4:46:80 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 32:00:19:f4:46:81 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 02:c9:d0:87:d0:ff 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 8a:20:ca:36:7a:38 
	inet6 fe80::8820:caff:fe36:7a38%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 22:c9:d0:78:f2:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
vboxnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00 
	inet 192.168.99.1 netmask 0xffffff00 broadcast 192.168.99.255
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::b3f6:df6d:8247:ea07%utun0 prefixlen 64 scopeid 0xb 
	nd6 options=1<PERFORMNUD>
vmnet1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:01 
	inet 192.168.170.1 netmask 0xffffff00 broadcast 192.168.170.255
vmnet8: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:08 
	inet 172.16.189.1 netmask 0xffffff00 broadcast 172.16.189.255
```

**Comment by samoht** [comment]
ping @djs55

**Comment by justincormack** [comment]
@cwbeck you still did not post the exact command line you were using.

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
