### ISSUE TITLE
Docker Desktop 4.27.0 makes macOS crash

### ISSUE THREAD

**Issue by rmargar** [docker/for-mac#7143]
### Description

I recently tried upgrading docker desktop to the latest version (from the website 4.27.0 when writing this issue). After installing and re-starting docker desktop (as indicated in the UI), my laptop crashed. Every time I tried to re-start it continued crashing the moment docker was booting (I had docker desktop set up to open at login).

specs:
```

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7429.81.3
  OS Loader Version:	7429.81.3

MacOS Version 12.2.1 (21D62)
```

### Reproduce

Happens just when opening desktop. Since the computer crashes, it's unclear what part of docker provokes it. It could be the daemon or the desktop app.

### Expected behavior

No crash.

### docker version

```bash
I could not run version since my laptop crashed.
```

### docker info

```bash
I could not run info since my laptop crashed.
```

### Diagnostics ID

N/A

**Comment by doringeman** [comment]
Hey, could you please provide diagnostics without starting Docker Desktop?
See https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal.
