### ISSUE TITLE
Docker Build - Internal Server Error - Application Issue Report

### ISSUE THREAD

**Issue by siva-rithish** [docker/for-mac#7144]
### Description

Encountered an "Internal Server Error" with the following message:

Application Error
We've reported this to our error tracker.
Internal Server Error

### Reproduce

It occurs since past two updates.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:06:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.0 (135262)
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:35 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/rithishkarg/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: ae36d043-d1cf-4990-ac88-e5892cb8a347
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

92DC3F5A-9682-4A47-A192-39480420EFFA/20240126164032

**Comment by rouaks** [comment]
+1

**Comment by joelkim** [comment]
+1

**Comment by piyushmishra1416** [comment]
Can anyone provide a solution to this issue?

**Comment by pclavelloux** [comment]
Same issue :(

**Comment by piyushmishra1416** [comment]
If you are a Mac user, then changing the owner will work for some of the repos.
Try this command: sudo chown -R $(id -u):$(id -g) $HOME/.docker

**Comment by Dviros** [comment]
Same here

**Comment by bsousaa** [comment]
can you test with the latest 4.27.2? https://docs.docker.com/desktop/release-notes/#4272

**Comment by grahamburgsma** [comment]
@bsousaa still happening for me with 4.27.2.

**Comment by Dviros** [comment]
@bsousaa can confirm as solved on my end; Running on 14.3.1, MBP M3.
Thanks a lot.

**Comment by ajounie** [comment]
![image](https://github.com/docker/for-mac/assets/145138578/b3495a8a-c5c6-4d1e-9e90-13823520108c)
I have the same issue  reinstall docker desktop
 upgrade to 4.28.0  
worked on my MAC Pro M1

**Comment by ajounie** [comment]
> > can you test with the latest 4.27.2? https://docs.docker.com/desktop/release-notes/#4272
> 
> I still get the problem MBP M1 14.3 (23D56)

test with  4.28.0

**Comment by aamna2401** [comment]
> ![image](https://private-user-images.githubusercontent.com/145138578/311528715-b3495a8a-c5c6-4d1e-9e90-13823520108c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODIxMTYsIm5iZiI6MTcxMDM4MTgxNiwicGF0aCI6Ii8xNDUxMzg1NzgvMzExNTI4NzE1LWIzNDk1YThhLWM1YzYtNGQxZS05ZTkwLTEzODIzNTIwMTA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMjAzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWYyNGNhZTgyMjVjZTc0Yjc0ZjgyZTg0NDMzZDAyZTY2N2MwYTc3NDkxNzA1OWE1MTliNTI5MDdjYWExYTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D5OmI7STiywxjCnmw459A5Co9-EXQcL4N9nedZ0en8M) I have the same issue reinstall docker desktop upgrade to 4.28.0 worked on my MAC Pro M1


This is not working on Windows 11.

**Comment by aamna2401** [comment]
did someone face this issue

unable to resolve docker endpoint: Invalid proto, expected tcp: http://127.0.0.1:5000

**Comment by m-root** [comment]
I did the following and it worked for me:

1. **Uninstall Docker Desktop**:
    - Drag the Docker app from the Applications folder to the Trash.
    - Open Terminal and run:
      ```bash
      rm -rf ~/Library/Group\ Containers/group.com.docker
      rm -rf ~/.docker
      ```
    - Empty the Trash.

2. **Download the Latest Docker Desktop**:
    - Go to the [Docker Desktop for Mac](https://www.docker.com/products/docker-desktop) download page and download the installer.

3. **Reinstall Docker Desktop**:
    - Open the downloaded `.dmg` file and drag the Docker icon to the Applications folder.
    - Launch Docker Desktop from the Applications folder and follow the setup instructions.

**Comment by SiegeSailor** [comment]
> I did the following and it worked for me:
> 
> 1. **Uninstall Docker Desktop**:
>    
>    * Drag the Docker app from the Applications folder to the Trash.
>    * Open Terminal and run:
>      ```shell
>      rm -rf ~/Library/Group\ Containers/group.com.docker
>      rm -rf ~/.docker
>      ```
>    * Empty the Trash.
> 2. **Download the Latest Docker Desktop**:
>    
>    * Go to the [Docker Desktop for Mac](https://www.docker.com/products/docker-desktop) download page and download the installer.
> 3. **Reinstall Docker Desktop**:
>    
>    * Open the downloaded `.dmg` file and drag the Docker icon to the Applications folder.
>    * Launch Docker Desktop from the Applications folder and follow the setup instructions.

This works! However, I was trying to fix the other issue - stop using `buildx`, which seems can be fixed by reinstalling Docker Desktop, and this didn't work. It still complains like:

```
(base) user@MAC Project % sudo docker build --tag "$CONTAINER_NAME:$TARGET" \
--target "stage-$TARGET" $BUILD_ARGS "./"
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
```

**Comment by Kolinone** [comment]
What do You think about: **chmod 777 ~/.docker **?
