### ISSUE TITLE
Rosetta emulation on arm64 in the Docker Desktop 4.27.0  has stopped working

### ISSUE THREAD

**Issue by roman-gorkunenko** [docker/for-mac#7147]
### Description

The Rosetta emulation for the necessary containers started working in version 4.26.1. However, in version 4.27.0, it stopped working again. The containers seem to start without errors, but the application is unresponsive, resulting in a 503 error:
`The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.`

The application itself has the following error in the logs:
`{"time":"2024-01-28 20:11:55.889450", "loglevel":"error", "module":"proxy_fcgi", "pid":"762", "tid":"140737232639744", "client":"192.168.65.1:27287", "message":"AH01067: Failed to read FastCGI header"}
{"time":"2024-01-28 20:11:55.889791", "loglevel":"error", "module":"proxy_fcgi", "pid":"762", "tid":"140737232639744", "client":"192.168.65.1:27287", "message":"AH01075: Error dispatching request to : "}`

In the var/log/php8.1-fpm.log, the following warnings were found:
`[28-Jan-2024 20:02:58] NOTICE: fpm is running, pid 722
[28-Jan-2024 20:02:58] NOTICE: ready to handle connections
[28-Jan-2024 20:02:58] NOTICE: systemd monitor interval set to 10000ms
[28-Jan-2024 20:03:56] NOTICE: Terminating ...
[28-Jan-2024 20:03:56] NOTICE: exiting, bye-bye!
rosetta error: futex(FUTEX_LOCK_PI_PRIVATE) failure: 35`

In var/log/apache2/error.log, the following warnings were found:
`{"time":"2024-01-28 20:04:53.730517", "loglevel":"notice", "module":"core", "pid":"754", "tid":"140737476216704", "message":"AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'"}`

### Reproduce

docker compose up -d

### Expected behavior

In version 4.26.1, with 'Use Rosetta for x86/amd64 emulation on Apple Silicon' and VirtioFS, the application worked quickly. Please fix this. I rolled back to version 4.26.1 for now; everything works there.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996600
 Built:             Wed Jul 19 19:44:22 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.0 (135262)
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:35 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Server:
 Containers: 11
  Running: 6
  Paused: 0
  Stopped: 5
 Images: 11
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 3
 Total Memory: 3.832GiB
 Name: docker-desktop
 ID: e1247a88-cf87-4f47-8719-a6ccf155eb73
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

CE614566-EFE5-41AF-93C8-A18BAC0BFD27/20240128195229

**Comment by savinskiy-konstantin** [comment]
I have the same issue

**Comment by rom-melnik** [comment]
I am encountering a similar challenge. I downgraded to the previous version. Please let me know if it can be fixed.
Thank you

**Comment by roman-gorkunenko** [comment]
I will try to find a reproduction. I can say that the 'Use Rosetta for x86/amd64 emulation on Apple Silicon' and VirtioFS worked specifically on version 4.26.1; before that, the same error occurred.

**Comment by montehurd** [comment]
@dgageot

my mediawiki "fresh_install" script here stopped working:

https://gitlab.wikimedia.org/mhurd/mediawiki-quickstart

after cloning you can run it like this:

`cd ~/mediawiki-quickstart && FORCE=1 ./fresh_install`

then after a few minutes it will hang after you see this in the terminal:

> Installing /Users/montehurd/mediawiki-quickstart/skins/manifests/Vector.yml
> https://gerrit.wikimedia.org/r/mediawiki/skins/Vector.git
> Successfully installed Vector 

At this point normally a browser window is opened with this url:

http://localhost:8080/wiki/Special:Version

But since it hangs that never happens

If you manually open that url in a browser at this point you'll see this:

> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> Apache/2.4.38 (Debian) Server at localhost Port 8080

While this isn't minimal, it does involve simply cloning the repo and running fresh_install

**Comment by dgageot** [comment]
Thanks @montehurd for providing a repro. From what I can tell, this is going to be fixed by 4.27.1. In the mean time, I guess you can keep on using 4.26.1

**Comment by SpunkyIceke** [comment]
for me it already triggered when running this 2 seconds later

10:00 $ docker run --platform linux/amd64 --rm nginx uname -m
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
2f44b7a888fa: Pull complete
8b7dd3ed1dc3: Pull complete
35497dd96569: Pull complete
36664b6ce66b: Pull complete
2d455521f76c: Pull complete
dc9c4fdb83d6: Pull complete
8056d2bcf3b6: Pull complete
Digest: sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
Status: Downloaded newer image for nginx:latest
x86_64

10:02 $ docker run --platform linux/amd64 --rm nginx uname -m
exec /docker-entrypoint.sh: exec format error

Reverting back to docker desktop 4.26.1 worked for me too.

**Comment by dgageot** [comment]
Sorry @SpunkyIceke I can't reproduce your issue. FWIW, I would refrain from hard deleting Rosetta like that, many things can go wrong.

**Comment by SpunkyIceke** [comment]
> Sorry @SpunkyIceke I can't reproduce your issue. FWIW, I would refrain from hard deleting Rosetta like that, many things can go wrong.

I understand that, but after the first exec format error, I couldn't get it to work again. So I needed to clean install Rosetta. And this was the way I found online. And it did work, .. for 2 seconds. It break immediately after, and then I couldn't get it to work again either. 

But now on 4.26.1 it just keeps working. So I'll stay on this version until the 4.27.1 fix is out and test again.

**Comment by dgageot** [comment]
Hi @SpunkyIceke! Docker Desktop 4.27.1 is out. Could you tell me if it solves your issue?

**Comment by dgageot** [comment]
Yeah, sorry @SpunkyIceke and @roman-gorkunenko for the false information!

**Comment by dgageot** [comment]
Hi @SpunkyIceke and @roman-gorkunenko! Docker Desktop 4.27.2 is out. Could you tell me if it solves your issue?

**Comment by roman-gorkunenko** [comment]
Thanks! It works for my case, and there's no more 503 error.

**Comment by neuquen** [comment]
I just barely (and luckily) happened to see this thread.  I had the same issue, but just updated to v4.27.2 and no longer see the issue.  Thanks!

**Comment by dgageot** [comment]
I'm closing this issue. Feel free to open a new one if something is still wrong.

**Comment by enduity** [comment]
Hey, @dgageot

I am acutely aware that Docker Desktop is not open source. However, can I please please get some pointers on what the fix for this issue was? I am having similar issues with Colima and I just am not advanced enough in this area to track the cause down. Even info about what component needs changes would help a lot.
