### ISSUE TITLE
[Question] Moby linux sources

### ISSUE THREAD

**Issue by ltagliamonte** [docker/for-mac#715]
Hi everybody!
I'm looking for moby linux sources or package repo, i'm interested into the linux-kernel package and it's config file.
I hadn't luck googling, can anybody point me to the package repo?

**Comment by dsheets** [comment]
Hi! Have you looked in the gzipped tarball linked from <https://docs.docker.com/docker-for-mac/opensource/>?

**Comment by ijc25** [comment]
I just checked and the kernel sources are in that tarball (along with lots of other stuff), so closing. 

@ltagliamonte if you are still having trouble finding them please ping here again.

**Comment by ltagliamonte** [comment]
@dsheets thanks!
