### ISSUE TITLE
openvswitch changed to built-in kernel module in Docker Desktop 4.27.0

### ISSUE THREAD

**Issue by antoninbas** [docker/for-mac#7151]
### Description

openvswitch is no longer a loadable kernel module in Docker Desktop 4.27.0 (`6.6.12-linuxkit`), and is now a built-in module.
Since this may be a breaking change for some tools (e.g., the antrea CNI in Kubernetes), I wanted to check whether this was an intentional change, or if there was any intention of rolling back this change in a future Docker Desktop release.

```
modprobe: FATAL: Module openvswitch not found in directory /lib/modules/6.6.12-linuxkit

cat /lib/modules/6.6.12-linuxkit/modules.builtin | grep openvswitch
kernel/net/openvswitch/openvswitch.ko
kernel/net/openvswitch/vport-vxlan.ko
kernel/net/openvswitch/vport-geneve.ko
kernel/net/openvswitch/vport-gre.ko
```

I have also run into other breaking changes (e.g. `CONFIG_NF_CONNTRACK_ZONES` is not set anymore), but it looks like there is already another issue for this: https://github.com/docker/for-mac/issues/7148

### Reproduce

docker run --net=host -ti -v /lib/modules:/lib/modules:ro -v /proc:/host/proc:ro ubuntu:22.04 bash
$ cat /lib/modules/6.6.12-linuxkit/modules.builtin | grep openvswitch 

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:06:12 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.27.0 (135262)
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:46 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/abas/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/abas/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/abas/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/abas/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/abas/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/abas/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/abas/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/abas/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/abas/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/abas/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/abas/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 7
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 923645a1-9fda-41ea-8d28-6d7284c31168
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

BA9B14BC-F744-4555-8E86-6B23515F4706/20240129215923

### Additional Info

This is not really a bug per se, but could be a breaking change for some. Hence I wanted to check if this was an intentional and "permanent" change to Docker Desktop / LinuxKit.

**Comment by dgageot** [comment]
Cross posting my response to the [issue](https://github.com/antrea-io/antrea/issues/5939):

Hi @antoninbas, Docker Desktop maintainer typing here! We're so sorry for breaking your workflow.

We've indeed recently made big changes to Docker Desktop's kernel config in order to make it smaller/faster. Sorry that this has a negative impact on you.

+ Support for `conntrack zones` will be back soon. As soon as 4.27.1 if we manage to make it part of the hot fix in preparation. Otherwise, it'll for sure be part of 4.28.
+ `openvswitch` module will probably stay as it is, as a static module. That's how we hope to install all the kernel modules in the future. Do you think it's possible to change your check to recognise such setup?

**Comment by antoninbas** [comment]
@dgageot Thanks for the quick reply and the information.

> openvswitch module will probably stay as it is, as a static module. That's how we hope to install all the kernel modules in the future. Do you think it's possible to change your check to recognise such setup?

Yes we will enhance our logic to handle this case. I just wanted to check whether it was an intentional long-term change, or not, and it looks like it will stay this way moving forward.

You can feel free to close this issue, given that #7148 already covers the conntrack regression.
