### ISSUE TITLE
Docker Desktop 4.27.1 is crashing on MacOS

### ISSUE THREAD

**Issue by samjoy1234** [docker/for-mac#7164]
### Description

Docker desktop is crashing. I would reinstall the app and it would still crash

### Reproduce

For sometime it will work and then crash.  I reinstalled the app multiple times. However, it is still crashing.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:18:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:21 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/samjoy/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/samjoy/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/samjoy/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/samjoy/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/samjoy/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/samjoy/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/samjoy/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/samjoy/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/samjoy/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 643a9a46-a852-4c39-8c3a-3357ff8a214d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

F36E131C-4B2E-45AD-A375-B1384D24814E/20240202123634

**Comment by KatWorkGit** [comment]
I manually upgraded to Docker 4.27.1 because I saw that version 4.27.0+ had re-added kernel modules for `squashfs`. 

**When I upgraded by going to the docker website and manually downloading the most recent installer for intel mac, I now also run into this issue.** 

Not sure if it is worth noting that when I tried to install `v4.27.0` through the app, I got the message 

> "Your current user profile doesn't have permission to update Docker Desktop. This could be due to either admin rights or another user installed Docker Desktop."

 despite my docker installation not being managed by IT (I had downloaded and installed it myself using the installer on Docker's Intel-Mac page).
 
 ---
 
 **Docker Version:**
 ```
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:18:45 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`
```
**Docker Info**
```$ docker ingo
docker: 'ingo' is not a docker command.
See 'docker --help'
IA-C02CJ5U2MD6R:Downloads kaca$ docker info
Client:
 Version:    25.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/kaca/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/kaca/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/kaca/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/kaca/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/kaca/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/kaca/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/kaca/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/kaca/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/kaca/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/kaca/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/kaca/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 37
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.755GiB
 Name: docker-desktop
 ID: edf0f789-e5ab-49d5-b1c6-164f97e24fb3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

**About this Mac:**
<img width="280" alt="Screenshot 2024-02-02 at 4 23 41 PM" src="https://github.com/docker/for-mac/assets/127438812/98dbb859-9660-4b97-b4c1-4badc71c2bb0">

**Comment by peskyAdmin** [comment]
same her on an M2 chip

**Comment by Jofra-Jimenez** [comment]
Same issue: 
Mac M2 
Docker Version 25.0.2

**Comment by hungtcs** [comment]
Same problem, crashes on every build!

**Comment by aki-korpua** [comment]
I'm having the same problem. Updated last friday to Deskop 4.27.1 and after update Docker Engine did not start. Had to reinstall to get Docker Engine running again. But while running my containers it is crashing eventually after some time. Unable to continue my work due to this issue.

Diagnostics ID

`4DC13498-8740-496E-A051-67282C678B2F/20240205075606`

Docker version
`Client: Docker Engine - Community
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629222
 Built:             Tue Jan 23 15:11:10 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:21 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

Docker info 
`Client: Docker Engine - Community
 Version:    25.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/akikorpua/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/akikorpua/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/akikorpua/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 7
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: d7e6ba4b-02d9-47c8-bf2f-ffd03683c054
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
`

**Comment by lorenrh** [comment]
Hello! 

We are working in a fix, to be included in the next Docker Desktop release, sorry for the inconvenience.

**Comment by chudilka1** [comment]
I had to downgrade back to 4.26.1 (4.27.0 did not work for me as well)

MacOS 14.3 (23D56)
M1 Max

**Comment by Wamy-Dev** [comment]
Same error, downgrading back to 4.26.1 worked fine thanks to the comment above.

**Comment by przemdel** [comment]
Same issue on m1 pro

**Comment by KatWorkGit** [comment]
I also had to downgrade back to `4.26.1` to get docker working again on my mac for work.

Download link for `4.26.1` for convenience 👉 https://docs.docker.com/desktop/release-notes/#4261

**Comment by Jofra-Jimenez** [comment]
This fix the issue for me:
Go to finder and open Applications > Utilities > Activity Monitor.app
Find Docker or Docker Desktop (it was in Not responding mode in my case) and Force Kill the app.
Run the following command in Terminal:
> sudo rm -rf ~/Library/Containers/com.docker.*
Open the setting file in the terminal:
> sudo nano ~/Library/Group\ Containers/group.com.docker/settings.json
then find "filesharingDirectories":
Remove all entries inside this key and leave it as "filesharingDirectories": [], save and close the file.
Start Docker Desktop

**Comment by BluSyn** [comment]
> This fix the issue for me: Go to finder and open Applications > Utilities > Activity Monitor.app Find Docker or Docker Desktop (it was in Not responding mode in my case) and Force Kill the app. Run the following command in Terminal:
> 
> > sudo rm -rf ~/Library/Containers/com.docker.*
> > Open the setting file in the terminal:
> > sudo nano ~/Library/Group\ Containers/group.com.docker/settings.json
> > then find "filesharingDirectories":
> > Remove all entries inside this key and leave it as "filesharingDirectories": [], save and close the file.
> > Start Docker Desktop

This partially solved the problem for me. This got the engine up and running and not crashing. However, when trying to start my containers again, docker fails to mount local files (even after adding dirs back into `filesharingDirectories`). 

Example error:
`failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/<path>/redis.conf" to rootfs at "/usr/local/etc/redis/redis.conf": mount /host_mnt/<path>/redis.conf:/usr/local/etc/redis/redis.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown`

Finally downgrading to `4.26.1` solved all the issues.

My guess is latest version changed something related to `VirtioFS`.

**Comment by mswiech** [comment]
Hi. For me it started to crash after I had updated to Docker Desktop 4.27.2 (137060).
It crashes when I am trying to run java tests using [testcontainers-java](https://github.com/testcontainers/testcontainers-java) (v 1.16.3). This is the output:

```
2024-02-17 21:46:33.254  INFO [investment,,] 1569 --- [  prefetching-2] ?.z.io/z/test-postgres:empty]    : Creating container for image: docker.z.io/z/test-postgres:empty
2024-02-17 21:46:33.292  INFO [investment,,] 1569 --- [  prefetching-2] ?.z.io/z/test-postgres:empty]    : Container docker.z.io/z/test-postgres:empty is starting: 48d2d3b8d309da29eaf8d5c7cca8f37ab48e02f52473eeb2d721fbc2776a9114
2024-02-17 21:46:33.529 ERROR [investment,,] 1569 --- [  prefetching-2] ?.z.io/z/test-postgres:empty]    : Could not start container

com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/docker/48d2d3[...]fbc2776a9114/io.weight: no such file or directory: unknown"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:237)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:425)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)

```

**Comment by roytouw7** [comment]
> Docker Desktop 4.27.2 includes a fix for the crash caused by the build backend service (see [release notes](https://docs.docker.com/desktop/release-notes/#4272)), which was the cause for the initial report in this ticket. Closing this issue now; if anybody still experiences crashes with 4.27.2, please let us know.

4.27.2 still having this same issue for me

**Comment by stevenanthonyrevo** [comment]
Hi Docker Team,

I've recently noticed an issue with Docker Desktop running on a Mac Mini. 

Sometimes after long periods of running with many containers the docker daemon is unable to restarted, it hangs or gets stuck. 

Any ideas? What is causing for such an unstable Docker Desktop experience. 

I've had better luck with running docker on linux. Daemon does not seem to get stuck and require a manual shutdown or reload.

**Comment by Proctr** [comment]
> Hi Docker Team,
> 
> I've recently noticed an issue with Docker Desktop running on a Mac Mini.
> 
> Sometimes after long periods of running with many containers the docker daemon is unable to restarted, it hangs or gets stuck.
> 
> Any ideas? What is causing for such an unstable Docker Desktop experience.
> 
> I've had better luck with running docker on linux. Daemon does not seem to get stuck and require a manual shutdown or reload.

I have the same problem. The only reason that I can maybe think of is that I barely have any memory left on my laptop (Mac 2021 i7). Less than 10GB of storage left. Is that causing anyone else's issue?

**Comment by ohadbenita** [comment]
> I also had to downgrade back to `4.26.1` to get docker working again on my mac for work.
> 
> Download link for `4.26.1` for convenience 👉 [docs.docker.com/desktop/release-notes#4261](https://docs.docker.com/desktop/release-notes/#4261)

Not sure where is the download link?

**Comment by ezerk** [comment]
same issue on macOS Sequoia `15.1 (24B83)` with M1 chip

**Comment by rubnov** [comment]
Same issue with 
Docker version 28.1.1, build 4eba377 
Docker Compose version v2.35.1-desktop.1
on Mac Intel MacOS Ventura 13.7.6 (22H625)
Diagnostics ID: AED1EA7F-9FBA-4EAC-8285-9A9F95771232/20250521084943

Crashes every time I start Docker Desktop from the Applications folder.

```
initializing backend: initializing cli binaries configuration: ensuring docker cli plugins are installed at startup: could not get cli plugin version from /Applications/Docker.app/Contents/Resources/cli-plugins/docker-scout: running /Applications/Docker.app/Contents/Resources/cli-plugins/docker-scout docker-cli-plugin-metadata: signal: killed
```
