### ISSUE TITLE
(Docker desktop) Can't access to some pages anymore due to an Application error: "Internal server error"

### ISSUE THREAD

**Issue by LcntJulien** [docker/for-mac#7186]
### Description

After trying to download a github repo containing a docker-compose project and build it, docker desktop does not let me access to some pages anymore (builds and some of the settings pages), even though it seems like I can still build project, here is what's displayed:
<img width="1220" alt="Capture d’écran 2024-02-13 à 16 38 28" src="https://github.com/docker/for-mac/assets/73828002/a696cc36-2783-45c9-870a-e024fc528870">

I work on a mac with Appple silicon M2 ship, and I'm learning how to use Docker.
While coding a docker-compose project, I wanted to pull the project from someone else to see what could be the reasons to me not being able to make it work properly, so I pulled it then placed it in a local repo on my pc and then I tried to build it. It failed throwing me this kind of error:
```
failed to solve: debian:buster: error getting credentials - err: exit status 1, out: ``
```
so I went online to see how to fix it and I found about the `docker login` command, I did it and it fixed my FIRST problem, but then other came, whatever I gave up with this idea (I might have tried some other ways to make it work but got a little nervous and closed my terminal and now I can't remember what I did next🤦🏻‍♂️),
but when I opened back my docker desktop app, the builds page was displaying this...

I tried to:
 - uninstall & reinstall it
 - use `docker system prune -a`
 - change config.json
 but the issue persists
 
 I'm new with Docker and hope to be able to use the desktop app ever again or even figure out what happened.. Could anyone help me ?

### Reproduce

.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 3.831GiB
 Name: docker-desktop
 ID: 97407dad-b463-47f5-8c60-6f2cc9a9b72e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

95E9BD8E-B42E-452B-B4AF-01FAF76853DC/20240213165414

**Comment by zuoxianglei** [comment]
I also encountered the same problem.

**Comment by crazy-max** [comment]
Might be similar to https://github.com/docker/for-mac/issues/7356

Did you invoke `sudo docker`?

You can mitigate this issue by fixing the owner:

```
$ sudo chown -R $(id -un):$(id -gn) ~/.docker/buildx
```
