### ISSUE TITLE
[Question] Moby linux stable sources

### ISSUE THREAD

**Issue by ltagliamonte** [docker/for-mac#719]
This is a follow up from my previous question https://github.com/docker/for-mac/issues/715
The archive in the link suggested before it is linked to the docker for-mac beta channel, atm the archive contains a config for kernel 4.4.22 instead the stable channel is using 4.4.20.
Is there any other pointer to the stable sources or a versioned repo?

**Comment by justincormack** [comment]
The kernel config is available via `docker run --privileged alpine zcat /proc/config.gz` and the details of the source info and applied patches can be extracted as a tarball with `docker run  -v /etc:/hostetc -w /hostetc alpine tar cf - kernel-source-info kernel-patches > kernel.tar`.

The kernel-source-info file looks like 
```
KERNEL_SOURCE=https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.4.22.tar.xz
AUFS_REPO=https://github.com/sfjro/aufs4-standalone
AUFS_BRANCH=aufs4.4
AUFS_COMMIT=7d174ae40b4c9c876ee51aa50fa4ee1f3747de23
AUFS_TOOLS_REPO=https://github.com/Distrotech/aufs-util.git
AUFS_TOOLS_COMMIT=b5e7e204036da5e815ddec15a847a03c232771b4
```

and the patches directory contains all the other patches we apply (mainly hvsock and vsock at rpesent).

**Comment by samoht** [comment]
I am closing this issue as @justincormack replied to the question :-)

**Comment by luca3m** [comment]
@justincormack I saw that the instructions above do not work with docker4aws because kernel-patches are not present. Any reasons why?

**Comment by justincormack** [comment]
@luca3m no, sounds like they were accidentally removed. They are the same set of patches as d4m,  and the kernel sources are available in branches here eg https://github.com/rneugeba/linux-stable/tree/v4.9.21-moby (the only difference is the cloud versions do not have the aufs patches, so that is the complete patch set).

**Comment by luca3m** [comment]
Thanks @justincormack for the quick response! We'd like to precompile sysdig kernel module for any version of docker4* product. Can I assume we can rely on that repository for now?

**Comment by justincormack** [comment]
cool, yes, that should be fine. Are you in the Docker Community Slack? https://community.docker.com/registrations/groups/4316 - can help you out with any issues there too, might be easier...

**Comment by luca3m** [comment]
I've registered few hours ago, but I still not have access to Slack Channel. I'll ping you there, thanks!

**Comment by justincormack** [comment]
if you send me your email address you signed up with can accelerate it (twitter or email me)
