### ISSUE TITLE
Trouble running systemd in CentOS 7 (4.27.x)

### ISSUE THREAD

**Issue by quacktacular** [docker/for-mac#7190]
### Description

I run a CentOS 7 based container with `systemd` enabled as a development environment. It works great on `4.26.1` and earlier, but with Docker Desktop `4.27.0` and higher systemd isn't working properly anymore. The systemd process is running according to top, but does not start any services respond to requests.

Note that this relies on setting `deprecatedCgroupv1` to true in `settings.json` (this has worked for years)

Output on 4.27.x
```
[root@6ba68a6b5e72 /]# systemctl status
Failed to get D-Bus connection: No such file or directory
```

Dockerifle
```
FROM centos:7

# Prepare to run systemd in container
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

# Start init script
CMD ["/usr/sbin/init"]
```

docker-compose.yml
```
version: '3.4'
services:
  monolith:
    build: "./"
    platform: linux/amd64
    # Required to run systemd
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
```

### Reproduce

1. `docker compose up -d`
2. `systemctl status`
3. Note that systemctl cannot connect to systemd

### Expected behavior

When the container starts up systemd should start up normally, and `systemctl status` should return data from it.

Output on 4.26.1
```
[root@0cb36b3b0206 /]# systemctl status
● 0cb36b3b0206
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2024-02-14 13:47:51 UTC; 7s ago
   CGroup: /docker/0cb36b3b0206b4a8ea68ef86f59e73ee3d1b875f263ca209cd631f2e475b5b3b
           ├─  1 /rosetta/rosetta /usr/sbin/init /usr/sbin/init
           ├─ 85 /rosetta/rosetta /bin/bash /bin/bash
           ├─133 /usr/bin/systemctl systemctl status
           ├─138 /rosetta/rosetta /usr/bin/more more
           └─system.slice
             └─systemd-journald.service
               └─73 /rosetta/rosetta /usr/lib/systemd/systemd-journald /usr/lib/systemd/systemd-journald
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.4
 Git commit:        3a2c30b63a
 Built:             Thu Dec 15 15:37:38 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.12.1-desktop.4)
  compose: Docker Compose (Docker Inc., v2.24.5-desktop.1)
  debug: Get a shell into any image or container. (Docker Inc., 0.0.24)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.21)
  feedback: Provide feedback, right in your terminal! (Docker Inc., v1.0.4)
  init: Creates Docker-related starter files for your project (Docker Inc., v1.0.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scout: Docker Scout (Docker Inc., v1.4.1)
WARNING: Plugin "/Users/bdebrinc/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/bdebrinc/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 17
  Running: 3
  Paused: 0
  Stopped: 14
 Images: 17
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 9.708GiB
 Name: docker-desktop
 ID: 3fe7c346-65a0-4b6b-b123-e49b70e5f418
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: You're not using the default seccomp profile
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

2A2DD69C-03E1-4F18-9E34-630F82A9A13E/20240214140702

**Comment by dgageot** [comment]
Hi @quacktacular I'll try to reproduce tomorrow. We did change a lot of kernel config in 4.27. Maybe we removed something you rely on.

**Comment by dgageot** [comment]
I was able to reproduce and bisect. This has been broken when we switched to docker `v25.0.0-rc.1`.
@thaJeztah does it ring a bell?

**Comment by thaJeztah** [comment]
I think this may be because `:ro` is now made fully read-only on newer kernel versions that support this; older kernel versions did not actually make `:ro` fully read-only, and if the path you're mounting contained mounted filesystems, those filesystems were still writable. This was a limitation of those kernel-versions, and the intent was always to make `ro` _read-only_, so newer versions of Docker Engine make it so;

- https://github.com/moby/moby/pull/45278

In this case, it looks like systemd wants to write to some paths inside `/sys/fs/cgroup`. To allow the old behavior, you can use the advanced `--mount` syntax to the `/sys/fs/cgroup` path read-only, but allow nested mounts underneath it to be writable (if they are writable on the host);

```
--mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup,readonly=true,bind-recursive=writable
```

In the above;

- `type=bind` specificies that it's a bind-mount
- `source=/sys/fs/cgroup` is the path on the host to mount from
- `target=/sys/fs/cgroup` is the destination path inside the container to mount to
- `readonly=true` mounts the `target` path read-only
- `bind-recursive=writable` allows nested mounts within the source (`/sys/fs/cgroup`) to be writable.


Note that `--privileged` should not be needed to run systemd inside a container; `CAP_SYS_ADMIN` should be sufficient as far as I'm aware. Here's an example with `docker run`; I used a plain `centos:7` image;

```bash
docker run -it --rm \
    --cap-add CAP_SYS_ADMIN \
    --mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup,readonly=true,bind-recursive=writable \
    --name mycontainer \
    centos:7 /usr/sbin/init
```

However, the above requires docker CLI 25.0 or up; it looks like you have an older (20.10) version of the CLI installed for some reason; did you install that manually, or was this executed inside a container?

It also looks like compose does not yet support the `bind-recursive` option, so as a short-term alternative, you could remove the `:ro` for the bind-mount;

```bash
docker run -it --rm \
    --cap-add CAP_SYS_ADMIN \
    -v /sys/fs/cgroup:/sys/fs/cgroup \
    --name mycontainer \
    centos:7 /usr/sbin/init
```

I'll have a look if we can have the `bind-recursive` option added to the compose-spec (and compose).

**Comment by quacktacular** [comment]
Hey @thaJeztah confirming your suggestions worked for my use case. Thank you! This compose file is working:
```
version: '3.4'
services:
  monolith:
    build: "./"
    platform: linux/amd64
    cap_add:
    - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
 ```
> ...older (20.10) version of the CLI installed for some reason...

This was for some unrelated troubleshooting its normally up to date, thanks!

> I'll have a look if we can have the bind-recursive option added to the compose-spec (and compose).

That would be great!
