### ISSUE TITLE
Broken installation/Docker not starting on macOS 14.3

### ISSUE THREAD

**Issue by leoselig** [docker/for-mac#7194]
### Description

After installing Docker Desktop for Apple Silicon on my Macbook Pro M3 Pro, macOS 14.3, I cannot start the Docker.app successfully. Note, that I transferred my Mac from my previous Intel-based Macbook Pro and had an existing Docker installation. I replaced that old Docker.app when installing Docker today (I did not install Rosetta at any time).

### Reproduce

I don't think that this is rperoducible this way but it's what I did:
1. Install current docker from release notes for Apple Silicon
2. Run Docker.app

### Expected behavior

See Docker appearing in menu bar
See license agreement dialog

### docker version

```bash
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           default
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

E0855EA0-64BD-47F9-88FB-EC06815EA703/20240215091119

**Comment by pschoen-itsc** [comment]
Same problem here on M2. Already the second update with this problem.

**Comment by gabefair** [comment]
Same here, totally broken on M2 mac pro

**Comment by onacit** [comment]
What can I do? Just wait? Thanks.

**Comment by santos22** [comment]
I ran into issues to trying to update to 4.27.2 - the install indicator on Docker Desktop never finished and I wasn't able to start up any containers.

I uninstalled Docker and re-installed 4.26.1 - this working for me at the moment.

**Comment by neonima** [comment]
Thanks everyone for the report, I am currently investigating this issue. @santos22 & @gabefair would you be able to share your Diag ID? https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal? Thanks 🙏

**Comment by jonashaefele** [comment]
I'm having the same issue. Diagnostics ID 3F932992-19FB-4565-8294-B5E2261C077E/20240321134039

Bit more context:

- M2 Macbook Pro with Sonoma 14.4 (23E214)
- like @leoselig I transferred some settings from my previous intel Mac (didn't transfer apps, installed them from scratch). but it might have copied over some settings files for docker?
- I installed Docker Desktop with the installer linked at https://www.docker.com/products/docker-desktop/
- Docker app will start loading (MacOS bundle verification passes), but then freezes and nothing happens.
- Uninstall doesn't work, even from command line, it just freezes
- Manually deleted all files I could find that relate to docker in `~/Library/Group\ Containers/group.com.docker`, `/Library/Containers/com.docker.docker` and `~/.docker`
- restarted mac
- downloaded the installer from the releases page linked above by @gabefair  (https://docs.docker.com/desktop/release-notes/)
- interestingly the Docker.app file from the "homepage" shows as 1.93GB on disk, the Docker.app from the "releases" page above shows as 766MB ? Both say they are version 4.28.0

Neither installer/dmg succeeds to install and launch docker desktop. I get `docker` in my path, so I can run `docker --help`

Which oddly shows versions different from the installer?

```
docker info
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

(/usr/local/lib/docker/cli-plugins is a symlink to  /Applications/Docker.app/Contents/Resources/cli-plugins)

I hope that helps for context.

**Comment by oddball** [comment]
We are seeing this on Sonoma 14.4 on with Intel. Docker refuse to start

**Comment by cruizba** [comment]
I am having the same problem on Ventura 16.3.5 with Intel.

Rollback to 4.26.1 as @santos22 said is the only thing that works for me.

**Comment by neonima** [comment]
Docker being marked as damaged due to symlinked being used at the same time an in-update is happening has been fixed! Please open a new issue if this arises again from 4.30

**Comment by pschoen-itsc** [comment]
Update to 4.30 works without any problems.

**Comment by neonima** [comment]
Closing as it seems to be fixed in latest version. Feel free to comment if this reappears from 4.31 and above

**Comment by pschoen-itsc** [comment]
If was wrong. The update didn't apply, just restarted and still on the old version. Reinstalled with package downloaded from website. Then wanted to update today from 4.31.0 (153195) to 4.32.0 (157355). Update "installs" and I restart Docker Desktop and I still have to old version.
Now moving to podman desktop. Paying for software which has a non functional update mechanism seems wrong for me. Also don't want to waste my time with it.
