### ISSUE TITLE
Application Error We've reported this to our error tracker.  Internal Server Error

### ISSUE THREAD

**Issue by rajendradudhare-t** [docker/for-mac#7195]
### Description

Application Error
We've reported this to our error tracker.

Internal Server Error when I click on builds section on docker desktop mac machine

### Reproduce

click on builds section on docker desktop mac machine
<img width="1782" alt="Screenshot 2024-02-15 at 3 24 59 PM" src="https://github.com/docker/for-mac/assets/160120286/353b0f99-7a37-4a67-842d-c5852aff5257">

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:18:45 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/A119558092/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/A119558092/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/A119558092/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/A119558092/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/A119558092/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/A119558092/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/A119558092/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/A119558092/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/A119558092/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/A119558092/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/A119558092/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 21
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.825GiB
 Name: docker-desktop
 ID: 071b411b-9e71-4b18-bddd-fd779fe48c5f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

19FB087B-C8C4-4F85-9630-0C524C8742CC/20240215100159

**Comment by zeke-john** [comment]
Any update? getting the same error.

**Comment by rajendradudhare-t** [comment]
<img width="1792" alt="Screenshot 2024-03-02 at 12 04 59 PM" src="https://github.com/docker/for-mac/assets/160120286/95e8b9c8-46e9-40b1-ae67-04e9480b4bf3">

yes its the same.

**Comment by ajounie** [comment]
i has the same issue on my MAC M1,
i uninstalled docker desktop
after upgrade to  4.28.0
it resolved this issue

**Comment by rajendradudhare-t** [comment]
@ajounie  its for intel MAC pro

**Comment by ajounie** [comment]
> @ajounie its for intel MAC pro

Do you have the same  steps on you mac intel?

**Comment by aamna2401** [comment]
I am using Windows system and I have updated to the latest version but still I am facing same issue. Any solution?

**Comment by aamna2401** [comment]
Did someone face following error while using docker commands

unable to resolve docker endpoint: Invalid proto, expected tcp: http://127.0.0.1:5000

**Comment by Santaclowns** [comment]
Same... 
<img width="527" alt="Screenshot 2024-03-17 at 17 04 47" src="https://github.com/docker/for-mac/assets/108698980/f8565788-b44a-4b32-9b3f-a18d281f0d3d">


"WARNING: Plugin "/Users/ulf/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/ulf/.docker/cli-plugins/docker-scan: no such file or directory"

**Comment by rajendradudhare-t** [comment]
> > @ajounie its for intel MAC pro
> 
> Do you have the same steps on you mac intel?

Click on Docker Desktop and go to build tab and that's it

**Comment by Santaclowns** [comment]
> @ajounie  its for intel MAC pro

Got the error on M1 air

**Comment by mhkz** [comment]
Got the error on M1 pro

**Comment by treder** [comment]
same issue on M3 max with Docker Desktop 4.28.0 (139021)

**Comment by k-lombard** [comment]
Same issue on m3 with 4.29.0

**Comment by ivorscott** [comment]
Same issue m2 mac air

**Comment by ivorscott** [comment]
I found a fix for this.

1. Reset Docker Desktop to factory default settings.
2. Then uninstall using the feature in Docker Desktop. (You may see Docker still on the machine after uninstall).
3. Drag the Docker app from the Applications folder to the trash bin and delete it.
4. Re-install the latest Docker Desktop for Mac.

**Comment by m-root** [comment]
I did the following and it worked for me:

1. **Uninstall Docker Desktop**:
    - Drag the Docker app from the Applications folder to the Trash.
    - Open Terminal and run:
      ```bash
      rm -rf ~/Library/Group\ Containers/group.com.docker
      rm -rf ~/.docker
      ```
    - Empty the Trash.

2. **Download the Latest Docker Desktop**:
    - Go to the [Docker Desktop for Mac](https://www.docker.com/products/docker-desktop) download page and download the installer.

3. **Reinstall Docker Desktop**:
    - Open the downloaded `.dmg` file and drag the Docker icon to the Applications folder.
    - Launch Docker Desktop from the Applications folder and follow the setup instructions.

**Comment by mario-huang** [comment]
this works for me.
https://github.com/docker/for-mac/issues/7144#issuecomment-2152299467

**Comment by tharcissentirandekura** [comment]
I am also getting the same error right now

**Comment by crazy-max** [comment]
> I did the following and it worked for me:
> 
>     1. **Uninstall Docker Desktop**:
>        
>        * Drag the Docker app from the Applications folder to the Trash.
>        * Open Terminal and run:
>          rm -rf ~/Library/Group\ Containers/group.com.docker
>          rm -rf ~/.docker
>        * Empty the Trash.
> 
>     2. **Download the Latest Docker Desktop**:
>        
>        * Go to the [Docker Desktop for Mac](https://www.docker.com/products/docker-desktop) download page and download the installer.
> 
>     3. **Reinstall Docker Desktop**:
>        
>        * Open the downloaded `.dmg` file and drag the Docker icon to the Applications folder.
>        * Launch Docker Desktop from the Applications folder and follow the setup instructions.

Fixing permissions should be enough:

```
$ sudo chown -R $(id -un):$(id -gn) ~/.docker/buildx
```
