### ISSUE TITLE
Proxy configuration problem

### ISSUE THREAD

**Issue by manteca** [docker/for-mac#72]
### Expected behavior
Connect without proxy configuration
### Actual behavior
Calls a proxy configuration that it's not active
### Information
I have a "location" setup on my mac network, and in there is a proxy configuration.
But I run docker not in that location active, and for some time I can't connect to docker services because it is connecting through the proxy and I cant deactivate it.
So I wait for the next day and then the proxy gets erase and I can connect to everything

Diagnostic ID: CB4E4802-C191-497D-9236-4EB11B6AE432
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.4 (Build 15E65)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Set a location on mac's network.
2. Configure a Proxy to that location
3. Change to that location and test to see if it is working.
4. Change back to location where no proxy is configure.
5. Run Docker Beta App for Mac.
6. Run docker search command
<img width="504" alt="screen shot 2016-08-02 at 09 38 05" src="https://cloud.githubusercontent.com/assets/401666/17330482/f3cb2910-5894-11e6-8ec9-090afcb3e6f3.png">
<img width="483" alt="screen shot 2016-08-02 at 09 38 53" src="https://cloud.githubusercontent.com/assets/401666/17330483/f3cfcfce-5894-11e6-8df3-726e231d4808.png">

**Comment by dave-tucker** [comment]
@manteca thanks for the bug report!

Could you run `scutil --proxy` when you are in each location and paste the output here.
Please be sure to remove any sensitive information (replacing the IP's with a dummy is ok so long as we can see what is different).

You may also want to try clicking the Whale icon and `Restart`ing Docker for Mac after your network location has changed to see if it picks up the new environment.

**Comment by dave-tucker** [comment]
Closing as no info provided. If this is still an issue, feel free to update the ticket with the requested information and we'll re-open.
