### ISSUE TITLE
Synchronized file shares not working in kubernetes

### ISSUE THREAD

**Issue by imathews** [docker/for-mac#7212]
### Description

I'm attempting to take advantage of the latest synchronized file sharing feature in Docker Desktop. Despite configuring the share and bind mounts properly (as I understand it), Docker Desktop reports that no containers are taking advantage of the file share.

I've tried rebooting the k8s cluster and recreating containers after the file share was created, but seemingly to no effect. I'm using the kubernetes (v1.29) bundled with the latest version of Docker Desktop for Mac (4.28.0)

### Reproduce

A few screenshots probably illustrate this most succinctly:

**Docker Desktop file share config. Note that no containers are using the share:**

<img width="742" alt="Screenshot 2024-03-05 at 14 37 46" src="https://github.com/docker/for-mac/assets/5659375/ba85217a-fa43-49b1-b200-195ec3ff58f0">
  
**A running container, which I would expect to take advantage of the share:**

<img width="1042" alt="Screenshot 2024-03-05 at 14 38 23" src="https://github.com/docker/for-mac/assets/5659375/7c211fa2-6d06-4085-9a71-5e319f082fd3">
  
**Relevant config when inspecting the container:**

```json
"HostConfig": {
		"Binds": [
			"/Users/ian/dev/redivis/containers/app:/app/volume",
			...
		],
...
},
"Mounts": [
		{
			"Type": "bind",
			"Source": "/Users/ian/dev/redivis/containers/app",
			"Destination": "/app/volume",
			"Mode": "",
			"RW": true,
			"Propagation": "rprivate"
		},
...
	],
```

### docker version

```bash
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/ian/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/ian/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/ian/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/ian/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/ian/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/ian/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/ian/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ian/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/ian/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/ian/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/ian/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 71
  Running: 38
  Paused: 0
  Stopped: 33
 Images: 52
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 11.67GiB
 Name: docker-desktop
 ID: 7f8da816-ec4e-4b72-93a4-cca1c129ec51
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

DAC1A04D-0892-4023-AD25-2ED0F2FE56BB/20240305224359

### Additional Info
I'm using MacOS Sonoma 14.2.1 on an M1 MBP

**Comment by dgageot** [comment]
cc @xenoscopic

**Comment by Ken-Takahashi-0** [comment]
Having the same issues without Knubernetes. 
"Not in use by any containers" is displayed in all of my synced shares. 
Version is the same: 4.28.0

**Comment by Ken-Takahashi-0** [comment]
@imathews 
Hi, 
for me it worked to add the synced filesystem at first. Afterwards create your container. I think then it will be used in your container. Reusing it on existing containers will not activate the feature.

**Comment by imathews** [comment]
I tried this (did a full reset of the k8s cluster, and redeployed all containers), but am still seeing the same behavior where the synced share is listed as "not in use"

**Comment by xenoscopic** [comment]
Hey @imathews, thanks for the issue report.  At the moment we don't support using Synchronized File Shares with Kubernetes (and I can confirm your observation that it does not work).

I've spent a little time looking into whether or not this is something we could add quickly, but unfortunately it's going to require a significant amount of effort to implement.  Under the hood, the implementation of Synchronized File Shares is very different than that for virtual filesystems (like VirtioFS and gRPC-FUSE), making it very difficult to adapt the existing behavior.

The best option at this point would be to open an issue on [github.com/docker/roadmap](https://github.com/docker/roadmap) with as specific a request as possible (for example do you want `hostPath` volume support, do you want a PV provisioner that supports host paths, etc.).  The more traction that feature requests receive there, the easier it is for us to prioritize their implementation.

**Comment by imathews** [comment]
Thanks @xenoscopic, that all makes sense. I'll open an issue in the roadmap shortly.

I might suggest updating the Docker Desktop documentation with this limitation, just to save others the time and frustration in the future.

**Comment by xenoscopic** [comment]
Excellent point, @imathews.  I've just submitted a change to the docs and they should be updated shortly.  Sorry for the frustration and confusion, but thanks for your understanding!
