### ISSUE TITLE
Update Error when Updating Docker for macOS 

### ISSUE THREAD

**Issue by dzikri** [docker/for-mac#722]
### Information

Diagnostic ID: D9E7AF16-6E30-4675-BA4E-AD7B5120EF68
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Hi thanks for you report. Could you try to update manually to the latest version (1.12.1)? 1.12.0* releases had known issues on Sierra.
