### ISSUE TITLE
vmnetd installation failure

### ISSUE THREAD

**Issue by bmorgenthaler** [docker/for-mac#723]
634EB843-9ADE-43B5-9612-4C084DDE9FA6

**Comment by dsheets** [comment]
Installation fails in `launchd` with some contradictory messages, @djs55:

```
com.apple.xpc.launchd[user][1] <Error>: Caller specified a plist with bad ownership/permissions: path = /Library/LaunchDaemons/com.docker.vmnetd.plist, caller = smd.258
Docker[com.docker.docker][55444] <Error>: Failed to install networking components.
Docker[com.docker.docker][55444] <Notice>: privileged installation of com.docker.vmnetd successful
```

Thanks for your report!

**Comment by bmorgenthaler** [comment]
Okay, what are the correct permissions and ownership then? Here is what the initial install configured:

`-rw-rw-r--  1 root  wheel   688B Sep 28 23:31 com.docker.vmnetd.plist`

**Comment by ijc25** [comment]
@djs55 is this the same as #61 or is it something different?

**Comment by samoht** [comment]
@bmorgenthaler we improved quite a lot the robustness of the installer, so I am going to close that issue. Please feel free to re-open (or to create a new one, with a fresh diagnostic ID) if you still have some problems with Docker for Mac. Thanks!
