### ISSUE TITLE
MacOS crashes and restarts on Docker Desktop start

### ISSUE THREAD

**Issue by McAndyLarkin** [docker/for-mac#7231]
### Description

panic(cpu 2 caller 0xfffffe0015369814): vm_fault() KERN_FAILURE from guest fault on state 0xfffffe600c52c000 @sleh.c:3117
Debugger message: panic
Memory ID: 0x1
OS release type: User
OS version: 21E230
Kernel version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
Fileset Kernelcache UUID: 65F083231F3684E89C62E16ACD8BF64E
Kernel UUID: 178AA913-FCA9-33FD-A81C-DF08315F458D
iBoot version: iBoot-7459.101.2
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x000000000d93c000
KernelCache base:  0xfffffe0014940000
Kernel slide:      0x000000000e0ec000
Kernel text base:  0xfffffe00150f0000
Kernel text exec slide: 0x000000000e1d4000
Kernel text exec base:  0xfffffe00151d8000
mach_absolute_time: 0x573148d50
Epoch Time:        sec       usec
  Boot    : 0x6607e8a2 0x000bbd44
  Sleep   : 0x00000000 0x00000000
  Wake    : 0x00000000 0x00000000
  Calendar: 0x6607ec6b 0x0009a31a

Zone info:
  Foreign : 0xfffffe001e2dc000 - 0xfffffe001e2ec000
  Native  : 0xfffffe10000d0000 - 0xfffffe30000d0000
  Readonly: 0xfffffe14ccd9c000 - 0xfffffe1666734000
  Metadata: 0xfffffe6c0890c000 - 0xfffffe6c14894000
  Bitmaps : 0xfffffe6c14894000 - 0xfffffe6c1a400000

CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 8 PVH locks held: None
CORE 9 PVH locks held: None
CORE 0: PC=0xfffffe0015365a64, LR=0xfffffe0015365a64, FP=0xfffffe60ba7a3f10
CORE 1: PC=0x00000001966ab378, LR=0x00000001966d0470, FP=0x000000016f8aa1f0
CORE 2 is the one that panicked. Check the full backtrace for details.
CORE 3: PC=0x000000010e3aab44, LR=0x000000010e3aaa60, FP=0x000000016b814e10
CORE 4: PC=0xfffffe00151eafd4, LR=0xfffffe001537e1c0, FP=0xfffffe60ba803e50
CORE 5: PC=0xfffffe001536ae10, LR=0xfffffe001536ae0c, FP=0xfffffe6017b3be90
CORE 6: PC=0xfffffe001526741c, LR=0xfffffe0015267418, FP=0xfffffe60ba843f00
CORE 7: PC=0xfffffe001526741c, LR=0xfffffe0015267418, FP=0xfffffe60baa7bf00
CORE 8: PC=0xfffffe001526741c, LR=0xfffffe0015267418, FP=0xfffffe60bd903f00
CORE 9: PC=0xfffffe001526741c, LR=0xfffffe0015267418, FP=0xfffffe60114abf00
Compressor Info: 3% of compressed pages limit (OK) and 2% of segments limit (OK) with 0 swapfiles and OK swap space
Panicked task 0xfffffe29960080b0: 25976 pages, 12 threads: pid 2225: qemu-system-aarc
Panicked thread: 0xfffffe166799c140, backtrace: 0xfffffe60bb623310, tid: 26132
		  lr: 0xfffffe0015231560  fp: 0xfffffe60bb623380
		  lr: 0xfffffe0015231228  fp: 0xfffffe60bb6233f0
		  lr: 0xfffffe0015375ecc  fp: 0xfffffe60bb623410
		  lr: 0xfffffe001536805c  fp: 0xfffffe60bb623480
		  lr: 0xfffffe0015365a98  fp: 0xfffffe60bb623540
		  lr: 0xfffffe00151df7f8  fp: 0xfffffe60bb623550
		  lr: 0xfffffe0015230eac  fp: 0xfffffe60bb6238f0
		  lr: 0xfffffe0015230eac  fp: 0xfffffe60bb623960
		  lr: 0xfffffe0015a5aacc  fp: 0xfffffe60bb623980
		  lr: 0xfffffe0015369814  fp: 0xfffffe60bb6239e0
		  lr: 0xfffffe00153693b0  fp: 0xfffffe60bb623a50
		  lr: 0xfffffe00151ea828  fp: 0xfffffe60bb623a60
		  lr: 0xfffffe001537e1c0  fp: 0xfffffe60bb623e50
		  lr: 0xfffffe0015365ea8  fp: 0xfffffe60bb623f10
		  lr: 0xfffffe00151df7f8  fp: 0xfffffe60bb623f20

last started kext at 4741122898: io.macfuse.filesystems.macfuse	2113.20 (addr 0xfffffe0014848000, size 6320)
loaded kexts:
io.macfuse.filesystems.macfuse	2113.20
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTopCaseHIDEventDriver	5440.11
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.SEPHibernation	1
com.apple.driver.BCMWLANFirmware4387.Hashstore	1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	1934.101.3
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	583.100.10
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleCS42L84Audio	540.34
com.apple.driver.ApplePMP	1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.AppleSN012776Amp	540.34
com.apple.driver.AppleT6000SOCTuner	1
com.apple.driver.AppleT6000CLPCv3	1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	140.1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.AGXG13X	190.17.3
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleSDXC	3.2.1
com.apple.driver.AppleMCDP29XXUpdateSupport	1
com.apple.driver.AppleSerialShim	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleAVD	559
com.apple.driver.AppleAVE2	540.44.5
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleProResHW	175.4.0
com.apple.driver.AppleJPEGDriver	4.8.1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleMobileDispT600X-DCP	140.0
com.apple.driver.AppleT6000PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleInterruptControllerV2	1.0.0d1
com.apple.driver.AppleT8110DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AudioDMAController-T600x	140.4
com.apple.driver.AppleT6000DART	1
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleT6000	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	126.100.13
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	402
com.apple.kec.InvalidateHmac	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.driverkit.serial	6.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOAVBFamily	1040.6
com.apple.plugin.IOgPTPPlugin	1040.3
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleHIDKeyboard	228.1
com.apple.driver.AppleActuatorDriver	5440.11
com.apple.driver.AppleMultitouchDriver	5440.11
com.apple.driver.AppleHSBluetoothDriver	5440.11
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.nke.ppp	1.9
com.apple.driver.AppleHIDTransportSPI	5440.6
com.apple.driver.AppleHIDTransport	5440.6
com.apple.driver.AppleInputDeviceSupport	5440.6
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleCSEmbeddedAudio	540.34
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.AppleAOPAudio	140.3
com.apple.driver.AppleEmbeddedAudio	540.34
com.apple.iokit.AppleARMIISAudio	140.2
com.apple.driver.AppleSPU	1
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.AGXFirmwareKextG13XRTBuddy	190.17.3
com.apple.AGXFirmwareKextRTBuddy64	190.17.3
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSART	1
com.apple.iokit.IOGPUFamily	35.29
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleT6000TypeCPhy	1
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleSPMI	1.0.1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.ApplePMGR	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.81
com.apple.driver.AppleT6000PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT600xPCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T600x	640.5
com.apple.driver.AppleEmbeddedAudioLibs	140.1
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleH13CameraInterface	6.44.0
com.apple.driver.AppleH10PearlCameraInterface	17.0.6
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	1040.3
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	594
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.driver.FairPlayIOKit	68.16.0
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	533.100.11
com.apple.iokit.IOUSBMassStorageDriver	210.101.2
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	456.100.7
com.apple.iokit.IOSCSIArchitectureModelFamily	456.100.7
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleANELoadBalancer	5.64.2
com.apple.driver.AppleH11ANEInterface	5.64.2
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	140.1
com.apple.driver.AppleAudioClockLibs	140.1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	302.14
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.security.AppleImage4	4.2.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

** Stackshot Succeeded ** Bytes Traced 495278 (Uncompressed 1306640) **

### Reproduce

1. Open Docker Desktop

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
```

### docker info

```bash
Cannot run Docker Desktop
```

### Diagnostics ID

aada

**Comment by rnbrk** [comment]
I had the same issue with the latest Docker Desktop. But when I updated to the newest macOS version, this was resolved.

**Comment by bsousaa** [comment]
as mentioned by @rnbrk this kind of issue may happen with outdated operating systems - please update to the latest. I will close the issue for now but I can re-open if it happens differently
