### ISSUE TITLE
running services: running services: running Docker API, Proxy: shared listener closed

### ISSUE THREAD

**Issue by nothing2obvi** [docker/for-mac#7242]
### Description

After a few hours on M1 Mac Mini running Sonoma 14.4.1, Docker Desktop 4.29.0 quits and gives error:

`running services: running services: running Docker API`

`Proxy: shared listener closed`

![Screen Shot 2024-04-08 at 2 16 05 PM](https://github.com/docker/for-mac/assets/85228035/554b27b3-937a-45d9-8473-1dab116c53e8)

This is on a fresh install -- I uninstalled Docker Desktop and deleted all residual files according to the documentation, then installed 4.29.0.

This is a continuation of #7226, which occurred on Docker Desktop 4.28.0. It is probably the same error, just worded differently.

### Reproduce

1. run Docker Desktop for a few hours
2. it quits and gives error

### Expected behavior

Docker Desktop should not quit.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:14:46 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.29.0 (145265)
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:02 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.0.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
	Version:  v0.13.1-desktop.1
	Path:     /Users/username/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
	Version:  v2.26.1-desktop.1
	Path:     /Users/username/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
	Version:  0.0.27
	Path:     /Users/username/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
	Version:  v0.1.2
	Path:     /Users/username/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
	Version:  v0.2.23
	Path:     /Users/username/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
	Version:  v1.0.4
	Path:     /Users/username/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
	Version:  v1.1.0
	Path:     /Users/username/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
	Version:  0.6.0
	Path:     /Users/username/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
	Version:  v1.6.3
	Path:     /Users/username/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/username/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/username/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 34
  Running: 34
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.22-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 5.79GiB
 Name: docker-desktop
 ID: f63d5a2d-a576-438a-9848-0b42d6239140
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/username/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

D691CDD3-E73D-458B-B426-968D458A12E4/20240408180142

**Comment by artem-mel** [comment]
I encounter the same problem quite frequently, about once every hour. My laptop is Apple M3 Max with Sonoma 14.4.1

Diagnostics ID: 961BD21D-9E9C-487C-9DDB-D5230363BE7A/20240419152047

**Comment by jedlin-bf** [comment]
I'm having the same issue.

Apple M1 Pro running Sonoma 14.4.1 and Docker 4.29.0

Diagnostics ID: CFEDDDC6-6CCE-4AE2-9413-8FDA47FA5E43/20240423212007

**Comment by nothing2obvi** [comment]
I don't experience this anymore with Docker Desktop 4.30.0 on Sonoma 14.5 on M1 Mac Mini.

**Comment by lagom-citra** [comment]
I'm still having this with Docker Desktop 4.30 on an M2 Mac Mini running Sonoma 14.5 - Upgraded to 4.31.0 and it still happens after ten minutes of use.

**Comment by maxim-cpg** [comment]
4.31 Sonoma 14.5 - same issue. Please, reopen.

**Comment by malcomio** [comment]
I've also encountered this on Docker Desktop v4.31.0 running Sonoma 14.5

Diagnostic ID E7D3DDC4-36BC-47E9-8B86-0A1E0F336C47/20240627091559

**Comment by renatoknb** [comment]
Still experiencing this issue with M2 Air on Sonoma 14.5 and v4.32.0.

**Comment by xenover** [comment]
Same here - M3 Macbook Pro on Sonoma 14.5 and version 4.32.0 (157355)

**Comment by nick-gehring** [comment]
M3 Macbook Air Sonoma

**Comment by nick-gehring** [comment]
M3 Air on Sonoma 14.5. Version 4.32.0. 
Diagnostic ID: AF5BD360-9A9E-4D5D-9608-A8160597E845/20240717234051

**Comment by dungnd-geniee** [comment]
I have same problems. Please fix it

**Comment by renatoka** [comment]
After more than 2 weeks of crashes and countless tries of various debugging, I was able to resolve the issue on my M1 Pro and M2 Air by applying the following:

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/559d2080-b621-4ee1-87d3-5f072e085fe8">

Both devices are running Sonoma 14.5 and v4.32.0. I tried downgrading versions up to 4.27.2 but with no help. This might not be the best solution as osxfs is marked as legacy, but it solves the issue of "shared api listener closed" and similar caused crashes.

**Comment by alessioacella** [comment]
Same error here

**Comment by mlarocque** [comment]
Happened 3 times yesterday:

- Docker 4.32.0,
- M1 MacBook Pro
- Sonoma 14.5

Updated to 4.33.0. We'll see how it goes.

**Comment by xanderhades** [comment]
@nothing2obvi can you reopen?

**Comment by chiaradelaurentiis** [comment]
> I'm having the same issue.
> 
> Apple M1 Pro running Sonoma 14.4.1 and Docker 4.29.0
> 
> Diagnostics ID: CFEDDDC6-6CCE-4AE2-9413-8FDA47FA5E43/20240423212007

Hi, 
I'm running into the same. Have you managed to fix it?

**Comment by maxim-cpg** [comment]
We switched to alternative OrbStack engine. No problems since.
