### ISSUE TITLE
Docker doesn't start after 4.29 upgrade without installing Rosetta

### ISSUE THREAD

**Issue by xeron** [docker/for-mac#7243]
### Description

M2 Pro MacBook Pro.

Docker used to work just fine without installing Rosetta. Just pressing "Not now" on installation request and disabling it in Docker for Mac settings.

After 4.29.0 upgrade this doesn't work anymore. After pressing "Not now" it says Rosetta installation failed. There's "Disable rosetta" button but it doesn't do anything, it tries to install it again and fails again after pressing "Not now".

### Reproduce

1. Mac without Rosetta installed
2. Start docker 4.29.0
3. Press "Not now" for Rosetta install request

### Expected behavior

Docker engine and Docker for Mac start and work as usual even without Rosetta.

### docker version

```bash
N/A because docker fails to start
```

### docker info

```bash
N/A because docker fails to start
```

### Diagnostics ID

32A8EAF1-FD11-464B-A824-5EB62FB3ADB8/20240409022034

### Additional Info

Downgrading to 4.28.0 fixes the issue.

**Comment by shinyzhu** [comment]
I have the same issue on my Mac. It's a dead loop.

I've unchecked the "Use Rosetta for x86_64/amd64 emulation on Apple Silicon" option in the General settings.

Rosetta should be optional. I don't have or want to have Intel based containers on my Mac.

**Comment by 98549844** [comment]
> I have the same issue on my Mac. It's a dead loop.
> 
> I've unchecked the "`Use Rosetta for x86_64/amd64 emulation on Apple Silicon`" option in the General settings.
> 
> Rosetta should be optional. I don't have or want to have Intel based containers on my Mac.

that mean un-select this option  "Use Rosetta for x86_64/amd64 emulation on Apple Silicon" 
version 4.29 will be run normally  ?

**Comment by amxfonseca** [comment]
Same issue here. Docker Desktop is now crashing during startup and selecting "Disable Rosetta" wont't fix it.

<img width="692" alt="image" src="https://github.com/docker/for-mac/assets/6478355/37910d33-a65e-4d0c-a43c-9b805a706caa">

**Comment by cperezabo** [comment]
Docker Desktop for Mac is getting worse and worse. I'm not being able to work because I have to get a way to solve this fucking error. I don't use Rosetta at all!

**Comment by shinyzhu** [comment]
> > I have the same issue on my Mac. It's a dead loop.
> > I've unchecked the "`Use Rosetta for x86_64/amd64 emulation on Apple Silicon`" option in the General settings.
> > Rosetta should be optional. I don't have or want to have Intel based containers on my Mac.
> 
> that mean un-select this option "Use Rosetta for x86_64/amd64 emulation on Apple Silicon" version 4.29 will be resume to normal ?

I've tested this on 4.28.

When I checked this option. The Docker Desktop asked install Rosetta. I clicked "Not Now" then this option became unchecked.

**Comment by booleanbetrayal** [comment]
This issue is blocking our uptake of this release because we have explicitly forbidden Rosetta to eliminate any chance of unintended emulation / architecture drift in our engineering environments.

**Comment by MihaelaStoica** [comment]
Thank you for reporting and apologies for this bug! We identified the problem and we're working on a fix.

**Comment by MihaelaStoica** [comment]
Hey everyone, we have a [test build](https://desktop-stage.docker.com/mac/main/arm64/145714/Docker.dmg) with a fix, if you'd like to give it a try. Let us know if it fixes the issue for you.

**Comment by mattpavelle** [comment]
> Hey everyone, we have a [test build](https://desktop-stage.docker.com/mac/main/arm64/145714/Docker.dmg) with a fix, if you'd like to give it a try. Let us know if it fixes the issue for you.

This fixed the problem for me. Thank you, @MihaelaStoica

**Comment by shinyzhu** [comment]
@MihaelaStoica the test build works fine on my Mac too~ Great work.

**Comment by jfernandezr** [comment]
Thanks @MihaelaStoica.

After installing this test build, would Docker update to the stable channel back again or should I install the stable version when this issue goes upstream?

Thanks!

**Comment by MihaelaStoica** [comment]
> After installing this test build, would Docker update to the stable channel back again or should I install the stable version when this issue goes upstream?

Yes, you will be able to update to the next official release of Docker Desktop.

**Comment by k0ste** [comment]
> Hey everyone, we have a [test build](https://desktop-stage.docker.com/mac/main/arm64/145714/Docker.dmg) with a fix, if you'd like to give it a try. Let us know if it fixes the issue for you.

Works for me, thanks

**Comment by JDanielGutierrez05** [comment]
> Hey everyone, we have a [test build](https://desktop-stage.docker.com/mac/main/arm64/145714/Docker.dmg) with a fix, if you'd like to give it a try. Let us know if it fixes the issue for you.

I have the same issue after updating, but i just reinstall the 4.28, and now install this test build and works like a charm without using rosetta.

**Comment by cperezabo** [comment]
ETA for the stable release?

**Comment by jac18281828** [comment]
Same issue here.   Docker should not be enforcing dependencies that are not required.  Docker is synonymous dependency management?

**Comment by pro-nsk** [comment]
Same issue for me. 
Test build works, thanks

**Comment by maikdiepenbroek** [comment]
Test build works :) thanks!

**Comment by zhiminL712** [comment]
可以给一个windows的测试版本吗？

**Comment by stevetoro** [comment]
> Hey everyone, we have a [test build](https://desktop-stage.docker.com/mac/main/arm64/145714/Docker.dmg) with a fix, if you'd like to give it a try. Let us know if it fixes the issue for you.

Test build resolved the issue for me, same as everybody else, but it also got rid of that pesky "Configuration changed by another application" warning mentioned in https://github.com/docker/for-mac/issues/6898. Thank you!

**Comment by junior** [comment]
If in the future Docker need to have Rosetta for some reason, a clear message should be passed, and it's a major change. Was unexpected in a minor update.

BTW, both, installing the v4.28 and the test build both works for now. The only annoying issue with this is the Docker Desktop offering you to restart/update all the time and the ⓘ icon on the App bar.

**Comment by jamesgreenblue** [comment]
Test build worked perfectly 😅

@MihaelaStoica Can you confirm when it will be safe to update to a stable version?

**Comment by MihaelaStoica** [comment]
> @MihaelaStoica Can you confirm when it will be safe to update to a stable version?

The fix will be included in the next release of Docker Desktop, which is currently scheduled for the first week of May

**Comment by sumitsahoo** [comment]
Same issue here too. Had to install the test build. Waiting for stable release.

**Comment by mattpavelle** [comment]
> Same issue here too. Had to install the test build. Waiting for stable release.

FYI about a week or two ago the stable release included this fix. I'm back on the main release branch and all is good.

**Comment by cperezabo** [comment]
@mattpavelle you mean they hotfixed it?

**Comment by agentwyz** [comment]
hi, this bug fix as the way:

my device is Mac book pro (m3)

1. open safari, select the rosetta open,
2. the will install the rosetta
3. install it
4. after installed, you can open the docker:)

**Comment by carhartl** [comment]
Would be nice if the app doesn’t prompt at all for installation of Rosetta upon start if I have disabled it in the settings.

**Comment by sumitsahoo** [comment]
> hi, this bug fix as the way:
> 
> my device is Mac book pro (m3)
> 
> 1. open safari, select the rosetta open,
> 2. the will install the rosetta
> 3. install it
> 4. after installed, you can open the docker:)

The whole point was to use Docker without Rosetta. And the update is still not out yet.

**Comment by juanjoseluisgarcia** [comment]
> hi, this bug fix as the way:
> 
> my device is Mac book pro (m3)
> 
> 1. open safari, select the rosetta open,
> 2. the will install the rosetta
> 3. install it
> 4. after installed, you can open the docker:)

Please. Let's keep this serious and professional. I am a paying docker hub subscriber and Rosetta is NEVER an option for professional work. If the binary is for Apple Silicon they should be NO dependencies in Rosetta. That said Rosetta is on its way out soon. We shouldn't be relying on it as a feature, rather than a patch while software gets fully compliant. I am staying in 4.28 for this reason.

**Comment by agentwyz** [comment]
> hi, this bug fix as the way:
> 
> my device is Mac book pro (m3)
> 
> 1. open safari, select the rosetta open,
> 2. the will install the rosetta
> 3. install it
> 4. after installed, you can open the docker:)
Sorry, Today was my first time installing Docker on Mac, I resolved using this method, I just want to help others to solve it

**Comment by shinyzhu** [comment]
> > hi, this bug fix as the way:
> > my device is Mac book pro (m3)
> > 
> > 1. open safari, select the rosetta open,
> > 2. the will install the rosetta
> > 3. install it
> > 4. after installed, you can open the docker:)
> 
> Sorry, Today was my first time installing Docker on Mac, I resolved using this method, I just want to help others to solve it

It's ok to be not ok. Thanks anyway :) You've done a good job.

**Comment by MihaelaStoica** [comment]
The fix for this issue has been released in Docker Desktop 4.30.0 . See the [release notes](https://docs.docker.com/desktop/release-notes/#4300) for more details.
Thank you all for your patience on this.

**Comment by junior** [comment]
@MihaelaStoica one small issue: For people that re-installed the 4.28 before the 4.30 update, the "restart to update" forces to update to 4.29 first (Because auto downloaded), and breaks again, forcing you manually install 4.30.

The "Software Updates" is not intelligent enough to ignore old updates and download the newest 4.30.

Suggestion for the future: Add a button to check for new updates, even if has one already downloaded, like happen with MacOS Updates.

**Comment by mindctrl** [comment]
The download link on https://www.docker.com/products/docker-desktop/ still links to the 4.29. The 4.30 link is available here: https://docs.docker.com/desktop/release-notes/

**Comment by 98549844** [comment]
> The download link on https://www.docker.com/products/docker-desktop/ still links to the 4.29. The 4.30 link is available here: https://docs.docker.com/desktop/release-notes/

i download version4.30 docker and install to my m1, it still can't start ??? handing in starting and can't press any button

**Comment by quettabit** [comment]
i installed `4.30` via `brew install --cask docker`, and the issue seems to be still existing. after opening the app, it prompts for rosetta installation. when `Not Now` is selected, it errors with `Rosetta installation failed` window. if that error window is closed, it hangs in `Docker Desktop is starting` state. however, if `Disable Rosetta` is selected, it moves to `Docker Desktop is running` state, with a warning for `Re-apply configurations`. 

<img width="491" alt="Screenshot 2024-05-21 at 11 41 34 AM" src="https://github.com/docker/for-mac/assets/27509167/057d750e-b204-4634-8d40-6b289c0f1a1f">
<img width="596" alt="Screenshot 2024-05-21 at 11 41 53 AM" src="https://github.com/docker/for-mac/assets/27509167/36e551df-df5a-4cb0-a2e9-8b90f1b0827b">
<img width="302" alt="Screenshot 2024-05-21 at 11 51 39 AM" src="https://github.com/docker/for-mac/assets/27509167/93e379ea-8694-400a-b153-8a20f1dd202e">

**Comment by xeron** [comment]
Yes I randomly got the request to install Rosetta too, but after declining and pressing `Disable Rosetta` Docker started working again.

**Comment by genkernel** [comment]
Docker 4.31.<something>
Docker exits / crashes after tapping on `Disable Rosetta`. After n restarts it crashed n times.

I initially disabled rosetta as advised in a comment: https://github.com/docker/for-mac/issues/6356#issuecomment-1986901797. Thread: Docker's buildx on mac builds linux/amd64 binaries that do not work on linux.

Rabbit hole.

**Comment by juanjoseluisgarcia** [comment]
> Docker 4.31. Docker exits / crashes after tapping on `Disable Rosetta`. After n restarts it crashed n times.
> 
> I initially disabled rosetta as advised in a comment: [#6356 (comment)](https://github.com/docker/for-mac/issues/6356#issuecomment-1986901797). Thread: Docker's buildx on mac builds linux/amd64 binaries that do not work on linux.
> 
> Rabbit hole.

You need to specify more. I have an M3 Max with no Rosetta installed and have had no issues since 4.30.

**Comment by fabiansvensson** [comment]
I have the same issue on a brand new mac with the Apple Silicon chip (M3).

I installed Docker Desktop versions 4.35.0 and 4.34.0 and absolutely nothing happens when I execute docker desktop. No errors no nothing. I just see it Activity Monitor with 0% CPU usage. Tried uninstalling and re-installing, turning off and on PC, changing configs, etc., it's just completely dead. 

Reluctantly I install rosetta:
/usr/sbin/softwareupdate --install-rosetta --agree-to-license

And bam docker desktop starts working immediately. Is this going to be fixed any time soon?

**Comment by YUN-RU-TSENG** [comment]
Docker Desktop: 4.37.2 (179585)
Mac M2

still problems

**Comment by SliverYuki** [comment]
This issue has not yet been fixed. My device is a Mac mini M4 with 24G RAM and 512G ROM, and the system version is macOS Sequoia 15.3.2.

**Comment by Lgowen** [comment]
> This issue has not yet been fixed. My device is a Mac mini M4 with 24G RAM and 512G ROM, and the system version is macOS Sequoia 15.3.2.

i have the same problem. Did you fixed it already?

**Comment by davidalbertonogueira** [comment]
installing docker on a recently formated M2, i'm facing same problem

**Comment by Steppschuh** [comment]
I just had the same issue starting Docker 4.46.0 (204649) on an M4 MBP running macOS 15.7.2 (24G325).
It was not a fresh install but a data migration from an older M1 MBP.

Manually installing Rosetta resolved the issue
`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`

**Comment by juanjoseluisgarcia** [comment]
I had no issue before,  the images get corrupted quite often and when you reset I get tis error message

<img width="580" height="332" alt="Image" src="https://github.com/user-attachments/assets/1bf0e70c-b6a3-49fb-8b83-acd358516ccf" />

Switching to Colima. Guys. Docker desktop needs to be *way more stable than this*
