### ISSUE TITLE
Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by johker01** [docker/for-mac#725]
This issue is related to the following 2 issues:

https://github.com/docker/for-mac/issues/170
https://github.com/docker/docker/issues/24045

The original issue seems to be gone now, however, when trying to compile a large project via ant, I now receive the error "Error response from daemon: Bad response from Docker engine".
Unfortunately, I cannot share the source code I'm trying to compile, as it's closed source.
### Expected behavior

I expected the ant build to complete without any issues. It worked well when using virtualbox via docker toolbox, but now after switching to Docker for Mac, I experience issues.
### Actual behavior

I received an error message stating the following:
Error response from daemon: Bad response from Docker engine
### Information

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/AE087A84-BC38-42C8-AE19-975A5C9B69BF/20160929-143843.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. `docker pull choerst/centoscppbuild:latest`
2. `docker run --rm -it -v "$PWD":/workspace -w /workspace/project choerst/centoscppbuild:latest ant`

**Comment by JamesKyburz** [comment]
Getting this too.

`Docker version 1.12.2-rc1, build 45bed2c, experimental`

I get it sometimes only when performing cpu high operations with locally mounted volumes.
Hard to pinpoint the error and provide a scenario on exactly how the error can be reproduced.

When I don't mount the volumes I have yet to see the error.

**Comment by dcosson** [comment]
Same exact scenario for me as @JamesKyburz 

I just unmounted my local volumes (more for speed reasons than because of this issue), so I'll keep an eye out for whether it that seems to fix this.

**Comment by HerbCSO** [comment]
I'm getting the `Bad response from Docker engine` from time to time after I put my Mac to sleep. It seems to get into a tizzy then, but only sometimes. Not quite sure what other info to send for further debugging, not really too familiar with the Docker environment - mostly just a user, sorry. But happy to send in more infos if you'll tell me what would be useful for this.

I usually do a reset when I get into this state and that fixes it, but I have to re-setup shares and rebuild images, which gets kinda annoying to do every few days...

`docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: <redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 72
 System Time: 2016-10-18T15:36:06.841557003Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: <redacted>
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

`docker version`:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Comment by ijc25** [comment]
@johker01 thanks for the report and sorry for the time taken to get back to you.

Are you still able to reproduce this with beta30 (the latest at the time of writing)?

I'm also a bit perplexed because the report here says
```
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
```
while the logs in the corresponding diagnostic upload say:
```
<Notice>: Application version: 1.12.1 (12133)
```
Although both are old enough now that the distinction is fairly moot it might be that you received a partial upgrade at some point.

In any case there have been various improvements to components which I would expect to have an impact on the robustness of the kinds of things you are doing in both the latest stable (1.12.3) and beta (beta30) so a reproduction on either of those (along with a corresponding new diagnostics upload, since we have also improved the data we collect a lot since then) would be appreciated.

I understand that your app is proprietary and cannot be shared but if you still see this then reducing it to a minimal reproducible case (with none of the secret sauce) or finding an open source project with similar build time properties which exhibits the issue for us will dramatically increase the chances of the issue being fixed.

@dcosson @JamesKyburz likewise if you are able to repro on the latest beta then please open your own tickets with your own diagnostics uploads and specifics of your circumstances (and ideally a set of reproduction steps).

@HerbCSO your issue does not sound related to this one. It sounds more like #933

**Comment by HerbCSO** [comment]
Thanks @ijc25 - I'll look into the workaround described there.

**Comment by rogaha** [comment]
@HerbCSO @johker01 is the workaround working for you?

**Comment by johker01** [comment]
I'm still getting an error with 1.12.3-beta30.

```
make[1]: stat: /workspace/daemons/sources/daemons/sql_history/SQLHistoryInterface.hpp: Transport endpoint is not connected
make[1]: stat: /workspace/console/bin/debug/libconsole.so: Transport endpoint is not connected
make[1]: stat: /workspace/console/bin/debug/console/commands/CommandBase.o: Transport endpoint is not connected
make[1]: *** No rule to make target `/workspace/console/sources/console/commands/CommandBase.cpp', needed by `/workspace/console/bin/debug/console/commands/CommandBase.o'.  Stop.
make: *** [console-compile-link] Error 2
Error response from daemon: Bad response from Docker engine
Error response from daemon: Bad response from Docker engine
```

My new diagnostic ID: 5C751D85-6354-4408-AD51-4B56F2CCAA3B


```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/5C751D85-6354-4408-AD51-4B56F2CCAA3B/20161122-144439.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by HerbCSO** [comment]
Sorry, I thought I had replied, but apparently was mistaken... :/

I'm also still seeing the issue. New diagnostic ID: 91F73C6B-E115-4E31-85EE-6558C8C3B083

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/91F73C6B-E115-4E31-85EE-6558C8C3B083/20161130-142346.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by dsheets** [comment]
Hi @johker01, we believe we've fixed your issue in Beta 34. Please open a new issue if problems persist. Thanks!

**Comment by johker01** [comment]
@dsheets Yay, the problem is fixed. Thanks a lot!
