### ISSUE TITLE
All Containers Lost 

### ISSUE THREAD

**Issue by ThePredators** [docker/for-mac#7279]
### Description

After enabling WASM & Host networking on docker desktop version [4.29.0](https://docs.docker.com/desktop/release-notes/#4290) i lost all my old containers. I tried to disable these features to get them back, but nothing changed ! 

Im now running on the latest version of docker 4.30.0 ! 

What can i do ?

### Reproduce

On docker 4.29.0 or even 4.28.0 create some containers and then enable wasm & host networking in feature in development. Result all previous containers are removed. Now try to disable again wasm & host nothing changed. 

### Expected behavior

See old containers

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:44:56 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:04 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /Users/$(whoami)/.docker/cli-plugins/docker-scout

Server:
 Containers: 37
  Running: 22
  Paused: 0
  Stopped: 15
 Images: 22
 Server Version: 26.1.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.26-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: fde8300f-fe1e-49c4-8466-ff9ab6a9a3e5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/$(whoami)/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

15CF1839-0573-479F-ABB2-C6EF779D6FAD/20240512141956

### Additional Info

Please help !

**Comment by ffried** [comment]
Just found that this is actually described below the settings for this:
<img width="924" alt="image" src="https://github.com/docker/for-mac/assets/1689782/0a95d681-f15a-4c2b-840d-067de68b7839">

Turning off that setting brought back the old containers for me.

I wonder if there is an easy way to migrate those, though.

**Comment by ThePredators** [comment]
> Just found that this is actually described below the setting for this: <img alt="image" width="924" src="https://private-user-images.githubusercontent.com/1689782/332318491-0a95d681-f15a-4c2b-840d-067de68b7839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzg4NDYsIm5iZiI6MTcxNjI3ODU0NiwicGF0aCI6Ii8xNjg5NzgyLzMzMjMxODQ5MS0wYTk1ZDY4MS1mMTVhLTRjMmItODQwZC0wNjdkZTY4Yjc4MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMDgwMjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI2NDYxMzExNWU5ZjU2YmE3ODJkY2UzOTc4NjhhZDI4YzYzMDYwNDdhMjEyNjA4MGM1ZjNjOGM0NjJiMzM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bMtsQEmLIaYVgBI8bDJg-Kyul3T8bF6EpwlPaQsYw7w">
> 
> Turning off that setting brought back the old containers for me.
> 
> I wonder if there is an easy way to migrate those, though.

Thanks a lot dude it really saved my day.
