### ISSUE TITLE
Install docker desktop by CLI doesn't working properly

### ISSUE THREAD

**Issue by ejcontrerasv** [docker/for-mac#7284]
### Description

When I try to run the installation guide from the docker documentation
[installation guide](https://docs.docker.com/desktop/install/mac-install/#install-and-run-docker-desktop-on-mac) 
I got the following error message
<img width="569" alt="image" src="https://github.com/docker/for-mac/assets/5197594/62144276-1b63-4a4b-8043-a2e48baa0ff8">
So if I try to delete manually those files, those files doesn't exist.

And when I try to install docker desktop interactively I got the following error.
[interactively guide](https://docs.docker.com/desktop/install/mac-install/#install-and-run-docker-desktop-on-mac:~:text=Install-,interactively,-Install%20from%20the)
![image](https://github.com/docker/for-mac/assets/5197594/c170a942-4b24-4113-a377-8dc7e43c7e1f)

So I can't work with docker due to the above issues.

### Reproduce

After I download the Docker.dmg from the docker web page.

```
sudo hdiutil attach Docker.dmg
sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
sudo hdiutil detach /Volumes/Docker
```

### Expected behavior

I'm expecting to work with docker properly. 

### docker version

```bash
The last version downloaded by the docker web page.
```

### docker info

```bash
This error is when I try to run docker after the installation process by CLI
```

### Diagnostics ID

8AFE2BBE-121B-11EF-9419-3E349CABB7A8/20240514175817

### Additional Info

doing migrations: fatal: removing /Users/joksancontreras/Library/Group Containers/group.com.docker/http_proxy.json: remove /Users/joksancontreras/Library/Group Containers/group.com.docker/http_proxy.json: permission denied

**Comment by ejcontrerasv** [comment]
I could solved it temporarily running these steps mentioned by @doylio on this [thread](https://github.com/docker/for-mac/issues/7046#issuecomment-2105230424) 

Docker files deleted

- [ ] sudo rm -rf /usr/local/bin/docker
- [ ] sudo rm -rf /usr/local/bin/docker-compose
- [ ] sudo rm -rf /usr/local/bin/docker-credential-desktop
- [ ] sudo rm -rf /usr/local/bin/docker-credential-ecr-login
- [ ] sudo rm -rf /usr/local/bin/docker-credential-osxkeychain
- [ ] sudo rm -rf /usr/local/bin/docker-index
- [ ] sudo rm -rf /usr/local/bin/kubectl.docker
- [ ] sudo rm -rf /usr/local/bin/com.docker.cli
- [ ] sudo rm -rf /usr/local/bin/hub-tool
- [ ] sudo rm -rf /opt/homebrew/etc/bash_completion.d/docker 
- [ ] sudo rm -rf /opt/homebrew/share/zsh/site-functions/_docker
- [ ] sudo rm -rf /opt/homebrew/share/fish/vendor_completions.d/docker.fish

 

1. Uninstall docker
2. Run brew cleanup docker
3. Remove the leftover files that mentioned above
4. Remove Docker from the Login Items. (System Settings > General > Login Items and remove "Docker" from the list at the top)
5. Empty Trash bin (sometimes a Docker Helper would start up from the Trash)
6. Logout & back in
7. Install fresh copy of Docker or execute by CLI “brew install --cask docker”

In step 7 I ran the command by CLI and was installed successfully.

**Comment by neonima** [comment]
@ejcontrerasv thanks for reporting this - the damaged problem happens when there are apps trying to communicate to docker while it is installing. Removing the `/usr/local/bin` docker related is indeed the solution or kill the app communicating with Docker

 However let us know if you experience the permission problems again

**Comment by cameronpickham** [comment]
I am also seeing this error and the workaround did not work for me unfortunately
