### ISSUE TITLE
Container won't run on  M1 macOS 14.5

### ISSUE THREAD

**Issue by njoyy09** [docker/for-mac#7305]
### Description

The container doesn't run on a Macbook Air Chip Apple M1 2020, MacOs Sonoma 14.5

### Reproduce

1. Download (Pull) an image as (ubuntu, alpine, debian, etc..)
2. Once downloaded, go on the target image and click on Run with default parameter
![Screenshot 2024-05-31 at 16 25 18](https://github.com/docker/for-mac/assets/60672543/aeb9d725-3704-4000-a8ce-cbc3785d9d86)
3. Nothing happens, the container is well created but stay in 'Exited' statut
![Screenshot 2024-05-31 at 16 25 51](https://github.com/docker/for-mac/assets/60672543/c47ce389-9e5f-4c5d
![Screenshot 2024-05-31 at 16 29 02](https://github.com/docker/for-mac/assets/60672543/c1fae6a1-e8b6-4f8c-9bf6-c8853ec51c89)
-b0b3-5f7c25913448)
I get no error message. I also tried to uninstall the docker desktop from my mac  with this procedure and re-install it but still got this issue ... I've also updated my mac but I'm still stuck (nothing change).

### Expected behavior

The container should run (just work)

### docker version

```bash
Docker version 26.1.1, build 4cf5afa
```

### docker info

```bash
Client:
 Version:    26.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /Users/njoy09/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /Users/njoy09/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /Users/njoy09/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/njoy09/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/njoy09/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/njoy09/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/njoy09/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/njoy09/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /Users/njoy09/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 3
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.26-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 3.831GiB
 Name: docker-desktop
 ID: 19240d11-6eb4-43b8-9834-d30849f4fcbb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/njoy09/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

3248CB82-1647-4C8C-9E19-BDAA8D39F60B/20240531144928

### Additional Info

macOS 14.5 (23F79)
Memory: 8GB,
CPU: Apple M1
Latest Docker [4.30.0](https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=module)

**Comment by jpbriend** [comment]
Hi,
A container is designed to run a command. The container will exit when the process exits.

You did not provided any command to run in the container.
The `alpine` container does not run any long-running command and you did not provided one.

If you want to keep the container running, you need to provide a long-running command.
For example: `docker run alpine tail -f /dev/null`
