### ISSUE TITLE
What's wrong happening in installing docker on my MAC?

### ISSUE THREAD

**Issue by PlatinumHeart** [docker/for-mac#7307]
### Description

**MAC:**
version: 12.2.1 (21D62)
chip: Apple M1 Pro

**Diagnose:**
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 12.2.1 (build: 21D62)
logs: /tmp/D2D248DA-2544-4711-B528-0D4F9A19C3C9/20240601-191436.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/platinum/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         /Users/platinum/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/platinum/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Unexpected error ((Failure
  "Error connecting socket to 9p endpoint unix:/Users/platinum/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ENOENT, \"connect\", \"\")")) connecting to /Users/platinum/Library/Containers/com.docker.docker/Data/s51
         com.docker.vpnkit is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/platinum/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/platinum/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started

### Reproduce

Step by step:
1. download the docker from 
https://download.docker.com/mac/stable/21090/Docker.dmg

2. Click the dmg file and install the docker.
3. Open the docker application.
<img width="596" alt="image" src="https://github.com/docker/for-mac/assets/97452973/f79a4372-b483-4f23-ba09-524be3cdab09">

### Expected behavior

I could use the docker normally without updating my MAC software version.

### docker version

```bash
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 12.2.1 (build: 21D62)
```

### docker info

```bash
Docker for Mac: version: 17.09.1-ce-mac42 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 12.2.1 (build: 21D62)
```

### Diagnostics ID

D2D248DA-2544-4711-B528-0D4F9A19C3C9

**Comment by gavin-docker** [comment]
Hi @PlatinumHeart, it looks like the issue you're encountering is due to quite an old version of Docker Desktop, in fact I don't even believe that version is compatible with an Apple Silicon device like yours. 

The best course of action would be for you to download the newest version of Docker Desktop from here: https://www.docker.com/products/docker-desktop/
