### ISSUE TITLE
Docker 1.12.2-rc1-beta27 on macOS Sierra does not work

### ISSUE THREAD

**Issue by toshi-a** [docker/for-mac#732]
### Expected behavior

  docker will be executed correctly
### Actual behavior

  docker does not start.
  first item in the menu bar icon will still be displayed as "Docker starting ...".
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/D38EB34F-107C-4183-926A-81B29C2D5012/20161003-014750.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Volumes/Files/Users/main/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior

[20161003-020851.tar.gz](https://github.com/docker/for-mac/files/505122/20161003-020851.tar.gz)
Install the docker to clean installed macOS Sierra(However, it has been modified the home directory.[/Users/main to /Volumes/Files/Users/main]), ran Docker.app.

**Comment by samoht** [comment]
Detected symptom of problem 'large-certificate' in D38EB34F-107C-4183-926A-81B29C2D5012/20161003-014750.

Since Beta27, Docker for Mac uses the hosts certificates directly. However, there was an issue with large certificates that you unfortunately hit. This was fixed by Beta28. Please upgrade. Thanks for using our product!

May be related to docker/for-mac#721
