### ISSUE TITLE
Docker for Mac continuously "starting"

### ISSUE THREAD

**Issue by tpjg** [docker/for-mac#734]
### Expected behavior

Docker starts.

### Actual behavior

The icon says "Docker starting ...", never finishes.

### Information

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/C7A8E0C7-8BB5-411B-A34E-A1687F6FF943/20161003-170334.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

After full reboot, keeps "Docker starting". Machine was updated to El Capitan (10.11.6) relatively recently, first time I tried to use Docker since.

**Comment by tpjg** [comment]
I have removed everything under ~/Library/Container/com.docker.com, as well as /var/run/docker.sock and re-installed. Now working fine.

**Comment by ddffx** [comment]
FWIW It started behaving badly (v 1.12.1) this  morning with the exact diagnostic info above. I had to uninstall using preferences > **uninstall/reset**, and then reinstall. Working ok now.
