### ISSUE TITLE
FAIL: cannot use hypervisor.framework under Rosetta 2

### ISSUE THREAD

**Issue by sherryumlah** [docker/for-mac#7342]
### Description

I've tried uninstalling Docker and reinstalling but can't seem to get Docker to launch on my Apple M3 Max. Each time I try to open Docker I receive a modal showing an error: 
> Incompatible CPU detected
We are sorry, but your hardware is incompatible with Docker Desktop.
Docker requires a processor with virtualization capabilities and hypervisor support.
To learn more about this issue see:
https://docs.docker.com/desktop/mac/troubleshoot/#incompatible-cpu-detected

Using the self-diagnostic tool, I'm seeing this error:
`[FAIL] DD0018: does the host support virtualization? FAIL: cannot use hypervisor.framework under Rosetta 2`

### Reproduce

1. Open Docker Desktop App
2. See Incompatible CPU detected
There's no way to launch the program once this modal pops up.

### Expected behavior

The Docker Desktop App program should open/start.

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
```

### Diagnostics ID

2C001162-8986-483F-B375-323BEA0DB5E1/20240628173238

### Additional Info

I also tried installing Rosetta 2 to see if that would fix the problem.  It's successfully installed but I'm still getting the issue.

**Comment by jpbriend** [comment]
Hi,
this error message is due to the fact you probably installed Docker Desktop for Intel Mac and not  Docker Desktop for Silicon Mac.
Can you uninstall Docker Desktop following [these instructions](https://docs.docker.com/desktop/uninstall/), then download [Docker Desktop for Mac - Apple Silicon](https://www.docker.com/products/docker-desktop/) and install it?
It should solve your problem.
