### ISSUE TITLE
Diagnostic ID: 18A381B3-3908-4D3E-8EEC-5738C079E2F4 (Mac OS X)

### ISSUE THREAD

**Issue by robertomoutinho** [docker/for-mac#735]
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior
1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 18A381B3-3908-4D3E-8EEC-5738C079E2F4/20161003-150958.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785
