### ISSUE TITLE
docker-desktop v4.31.0 can't upgrade to v4.32.0

### ISSUE THREAD

**Issue by ByteFlyCoding** [docker/for-mac#7353]
### Description

When I want upgrade it into v4.32.0 from v4.31.0, I found it can't work.
<img width="343" alt="image" src="https://github.com/user-attachments/assets/00a0cb95-6646-4834-9f82-7643e5db80c9">
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/11eb755c-0e55-4808-b731-a89182ac13df">

### Reproduce

1. Download upgrade
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/5deea791-b789-4671-8b67-a06480fb7ab9">
2. It's can't upgrade success.
<img width="299" alt="image" src="https://github.com/user-attachments/assets/7fdc8dd2-6f31-4989-ab84-9d10092825a9">

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/bytefly/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/bytefly/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/bytefly/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/bytefly/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/bytefly/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/bytefly/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/bytefly/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/bytefly/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/bytefly/.docker/cli-plugins/docker-scout

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 3.831GiB
 Name: docker-desktop
 ID: d67798ee-f82c-4b5a-989d-b7068fe54923
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/bytefly/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Registry Mirrors:
  https://hub.docker.com/
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

If it's necessary, please contact with me.

**Comment by jasl** [comment]
If you're in China, the He-Who-Must-Not-Be-Named has blocked Docker-related domains, and you've got the issue.

But this should be a bug. The root cause is that the upgrade feature doesn't follow any proxy settings.

**Comment by neonima** [comment]
@ByteFlyCoding Thanks a lot for reporting this issue 🙏 Is the problem due to the reason mentioned by @jasl?

**Comment by jasl** [comment]
> @ByteFlyCoding Thanks a lot for reporting this issue 🙏 Is the problem due to the reason mentioned by @jasl?

Could you simulate the network in which Docker-related domains are blocked?
You should reproduce the issue.

**Comment by neonima** [comment]
Hey there, I did a special build with a potential fix, would you be able to try it out and let me know what you think?

mac/amd64/160891
[Docker.dmg](https://desktop-stage.docker.com/mac/main/amd64/160891/Docker.dmg)
mac/arm64/160891
[Docker.dmg](https://desktop-stage.docker.com/mac/main/arm64/160891/Docker.dmg)
win/amd64/160891
[Docker Desktop Installer.exe](https://desktop-stage.docker.com/win/main/amd64/160891/Docker%20Desktop%20Installer.exe)
win/arm64/160891
[Docker Desktop Installer.exe](https://desktop-stage.docker.com/win/main/arm64/160891/Docker%20Desktop%20Installer.exe)

**Comment by jasl** [comment]
> Hey there, I did a special build with a potential fix, would you be able to try it out and let me know what you think?
> 
> mac/amd64/160891 [Docker.dmg](https://desktop-stage.docker.com/mac/main/amd64/160891/Docker.dmg) mac/arm64/160891 [Docker.dmg](https://desktop-stage.docker.com/mac/main/arm64/160891/Docker.dmg) win/amd64/160891 [Docker Desktop Installer.exe](https://desktop-stage.docker.com/win/main/amd64/160891/Docker%20Desktop%20Installer.exe) win/arm64/160891 [Docker Desktop Installer.exe](https://desktop-stage.docker.com/win/main/arm64/160891/Docker%20Desktop%20Installer.exe)

Thank you!

Unfortunately, I don't live in China. I'll try asking some of my friends to test it.

**Comment by Ma233** [comment]
<img width="540" alt="image" src="https://github.com/user-attachments/assets/3ada2180-40c8-47ae-934f-82b7aabd322c">

@neonima 
Hi, I installed the mac/arm64/160891 version in China. It can check for update without proxy and shows up to date.

**Comment by jasl** [comment]
Sorry for late response, my friend says the special version works.

FYI: he only tested Mac version

**Comment by neonima** [comment]
Thank you both! I will push the fix in prod 👍 happy to have helped and thanks a lot for reporting and participating in testing 🙌
