### ISSUE TITLE
Docker Desktop: Builders Application error

### ISSUE THREAD

**Issue by nkarpysh** [docker/for-mac#7356]
### Description

- Installed a new Desktop with license from my company. Get following error under Builders:

Application Error
We've reported this to our error tracker.

"open /Users/nkarpysh/.docker/buildx/current: permission denied"

*****************************
- I Updated docker to latest version and now seeing this in Builders:

Application Error
We've reported this to our error tracker.

"Internal Server Error"

### Reproduce

Just open Docker Desktop and see it

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.45 (downgraded from 1.46)
 Go version:        go1.22.4
 Git commit:        7d4bcd863a
 Built:             Fri Jun 28 14:56:30 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/nkarpysh/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 7d14f24a-657b-464f-8d15-29f0f3d55b0d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/nkarpysh/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

4009138F-141D-40CD-8229-6A573E3621E1/20240716092404

**Comment by hcassar93** [comment]
Same issue

**Comment by nkarpysh** [comment]
Any update?

**Comment by crazy-max** [comment]
Can you tell us if you're still reproducing with latest Docker Desktop 4.33.0?

If this is still happening can you give the output of `tree -pufi ~/.docker/buildx`.

**Comment by nkarpysh** [comment]
Hello,

I still see an issue in 4.33.0. Output request:


NKARPYSH-M-00R7:bin nkarpysh$ tree -pufi ~/.docker/buildx
[drwx------ nkarpysh]  /Users/nkarpysh/.docker/buildx
[drwxr-xr-x nkarpysh]  /Users/nkarpysh/.docker/buildx/activity
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/activity/desktop-linux
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/current
[drwxr-xr-x nkarpysh]  /Users/nkarpysh/.docker/buildx/defaults
[drwxr-xr-x nkarpysh]  /Users/nkarpysh/.docker/buildx/instances
[drwxr-xr-x nkarpysh]  /Users/nkarpysh/.docker/buildx/refs
[drwx------ nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux
[drwx------ nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/0c4ib6biyip1gp9wyzlti6asr
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/0hf0c0ut0b7166adrvb8lgfgn
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/1315u7a5kdsn1epdljp9y7a85
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/1a4tv2f09gda1ls1k7acv8lns
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/3331yq8cajcg4kmledawrqpip
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/4029jc0k7wdylsf2u3xndnlnc
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/52nnzcyp8mpchtv5e6q2gsrpd
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/5phmllml3vovdqj2gdlzn0wpq
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/5qpu3wubegiomnbrstzckqen2
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/5ug01nugzpv9i36xtjylwcijz
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/6vxzcupbcehm43rv66x632h7v
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/79e9nnte21fldk6iir94zwfvr
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/7zv08x4pwua2bljr282b4ex54
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/89rqxfuf7dng4rs9dc8by1yyj
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/92sjw9i54fnzgxx1bjacghew6
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/97j5yd2yohlmpmcdaaq0z6whg
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/9ldn6y30j5hgnh8trlph91qjj
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/a3rslfccrn057g8ahtg9lazcy
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/b2wzscxhjr0lqwozx31a5c1hd
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/b30vfzvgdxovunvjwinqt8i8j
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/bi321ye7wd9yd3wjcp30ih65o
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/bj2moweetxa3n9qb5h9faz00r
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/bnj6utt953k2qc9aom7f2y0t6
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/bozcyrl7zjruz1ih9gz647qon
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/c2okjnm5e0yaa00eatbrjslk1
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/cg6vldeizj0vhefq6jpyonsxq
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/cy7pemjwctto58pbbkqmn2423
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/d2sp1ifsb2z73izl3lgzidft8
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/draa462wshvqrlpbls3docnyy
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/e0obm31fnl89tgpghyp5n5p99
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/emqx3u3rx1fx1pm4tg56s9j2v
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/f2k9ca1xg6u8t3lh5mvttu0rj
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/f7roes7cl0wgcbkhvdxxgwj6y
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/f98df7r3fed8n2z1w11jwcwmo
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/frchcwvk328p8uj1t443oewg6
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/fysv3a9hzjy05lc341xq6go31
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/gc3szw7aq4yt9us5wxkliil38
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/gqqx1lqotg7lbs70cmjsju14c
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/hmbi19y5oq8sepm1a0e460jzx
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/hyi0stfqxfwt7re3frh16vbfr
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/i0z4o2b6g01o0urfy9ghaczdm
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/i4d1v6zs4024bu0hgzzptz8p0
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ij5p84x10dxecn3cfdv8dem2h
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/inbye1zut5adu3jf22tr1p1ko
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/jkdh01srii1ueyn127bxvqmv0
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/jlv6okeg6nabe4ilf01lyb1pq
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/k8n6pp8xr5y4x9sbrdrtubck8
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/kcb9173rpziik9mdwnirngjk4
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ks0vds7kxznrdd08s6qyi484e
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ks8vl2ago7x3cud1olr48zqkw
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/l8o2m95yhvz3uc5pycd0vbqns
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/lkryx5wwm0oy9jrdrpervdxbx
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/lplj05wan87ep4g3ltr9vfaai
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/m3sbcu61uu5al9iqhnf1kw6jo
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/mcf932ddzp1lci56gzmaafy6n
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/md5v3po9yrtkac87d5962n0ml
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/mqi82hlq6p54uzkbz9be0zh4s
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/muab0qt833s78cpt7poqc83p7
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/my46x0hb6nk5bkqyfif8pj8oj
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/n5dtowv1mx10kvck40yimu15k
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/n9y5sx9u17nucznukbybi5xs6
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ni43ltufdgw0paqv8dzmz0fto
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/nkgw6sg4ebs9pxtcdtet2y75l
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/novvqdri6v1pczklxpwqc4onn
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/o1qvnxqqrti4pi79ssg2q99kc
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/oqn303a6in3vpyjrcuoh2r32n
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/otu4b3v91b0bbkpu5qnsr4rlw
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ozd467cxpe44kvmcj2lj4vbab
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/p3n8jd9mnp2hyh9skm6ewduax
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/pgclpa1v51hezqdia2v4vrifk
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/phk3ogfetdlx713x1bbxxtpc4
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/pukayrq0gvheu995339s9suqb
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/q52a7568zwr00v3yy567oz7qc
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/qgheqfssjexn48aujbn7u827h
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/rml10rv2acfsa94vsr1s3ol84
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/rsaf8xsjbj86qe051okg479h6
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/rutz17idm3ijwt4hro4llkqdf
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/rvhzrwepcexq3iplle2itiq9o
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sb5jpsxf7p9pufxfxp8f72zx4
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sc81rkrr5kyctaxah8og5rrnu
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sce9fge360eif6qg0ecgbxtpd
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sgcduxjsdmvnzjrvr52csq5ca
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sir0n021o1cnyj1ob6r7pdmtc
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/sv2y9bs7768nys8490wlmglnb
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/symh1sv1un7z4ppn26oim7bz6
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/t6twkjr7kigl1ezlye2nakyru
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/t7fnayuwesh3qmbsqez7kl8tb
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/t8khgpkmm1d57evl495ccl9rx
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/tg7f7lkk6zatau5jtu2nhr6te
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/tpsm3us43ti1lm3yrsilk4gl5
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/tre5rj839cij8t29enhi7a0yx
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/urolkg1n6ys2fnnxy2u0fwk1w
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/uyg4hbwokhrhwr9w1b5doeg9l
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/vql59upq7sjpzcnatu2w0ly3r
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/vv6scz5vpz01cibbzcv18u5xj
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/vzy5044t9hdfs1xjp7vfdmylq
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/w574ks5o8h502vraudpe2y4hq
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/wlb4pd4z0r2cmx6nqiddl5deq
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/woug416vtrs6xjl6mbk7ugbkw
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/wr59dr6mv9pm4cub45cetumnq
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/wv2patfnkiqjfytvb96n6mon2
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/x6vt56d2dzg4jlvumdpjf749p
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/xazis3qt0kk9uazzd0ud1pycd
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/xugr5qt63aw4eoo4jcge76p1z
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/yj60rogwquhzx897gwme82dgk
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/ynml83c8zstl61m64uel254us
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/yrcfieerf9gmj1kv0firji6ny
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/yrf4xdjbapr7jbe8pdyl01g2a
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/yxcotaw68r0er241cdab5mo17
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/z6sydpjxcsc6vfrjqr1jlw1zi
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/zekgd7x8v9shvqoi6qaw4fu38
[-rw------- nkarpysh]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/zeswylk8aeqcgtd37elxegvru
[-rw------- root    ]  /Users/nkarpysh/.docker/buildx/refs/desktop-linux/desktop-linux/zpethiun2s0j76atfizso30pq

7 directories, 115 files


Docker configured in System mode.

Nikolai

**Comment by crazy-max** [comment]
> I still see an issue in 4.33.0. Output request:

@nkarpysh Thanks! Looking at the output I'm not sure how files are created with `root`. Did you invoke `sudo docker` maybe?

Can you fix perms with:

```
$ sudo chown -R $(id -un):$(id -gn) ~/.docker/buildx
```

And tell us if that fixes the issue?

**Comment by crazy-max** [comment]
This looks very similar to https://github.com/docker/for-mac/issues/7144#issuecomment-1928938785

**Comment by nkarpysh** [comment]
Yeap, it did work. Now everything is fine with "Builds" section. Thx for your help.

Nikolai
