### ISSUE TITLE
How can I do port forwarding?

### ISSUE THREAD

**Issue by bytesandwich** [docker/for-mac#736]
### Expected behavior

I'm forwarding localhost:5000 on my mac from a container running in my kubernetes cluster. I want to push to localhost:5000, after configuring port forwarding on the docker for mac vm, and be able to pull from my k8s cluster. 
### Actual behavior

I have no way to get the docker for mac vm to forward my mac's port 5000 to the vm's localhost:5000 ?
### Steps to reproduce the behavior
1. run a docker repository somewhere outside your mac
2. port forward localhost:5000 from that host to your mac
3. docker tag/push localhost:5000/myfirsttag

**Comment by samoht** [comment]
We do not support forwarding from the host to the containers yet, but we are working on it. Meanwhile, @justincormack might have a workaround involving socat, I'll let him comment.

**Comment by samoht** [comment]
Closing in favour of https://github.com/docker/for-mac/issues/736. Please subscribe to that issue if you want to be notified on progress.

**Comment by andrewrynhard** [comment]
@samoht the issue you referenced, is this one. Please update so we can subscribe. Thanks!

**Comment by samoht** [comment]
woops, updated (it was #68)

**Comment by andrey-moor** [comment]
Same issue. How can I pull/push images from/to a private registry available through port forwarding on the host?
