### ISSUE TITLE
How to expose a port on the host to a container?

### ISSUE THREAD

**Issue by beaugunderson** [docker/for-mac#737]
I'd like to expose a port on my OS X host to a running container. This is necessary in my workflow because I'm using Aptible; the only way to access my private Aptible database is via the `aptible db:tunnel` command which creates an SSH tunnel and exposes the database via a port on my host. I'd like to access this host port from within a running container.

I've tried `network_mode: host` to no avail. I've also tried using the various IPs that show up in `ip addr`.

I'm using 1.12.1.

**Comment by beaugunderson** [comment]
Here's an example of what I'm attempting to do:

![screenshot](https://i.imgur.com/0cpdG5k.png)

**Comment by bobbypriambodo** [comment]
The IP you are using is the IP of the Docker container (`elastalert`). You need to get the IP of your host by running `ifconfig` on the OSX host, and use that IP instead from the container. Basically what you're doing is you are `telnet`-ing the docker container, which is not listening on port 8000.

**Comment by beaugunderson** [comment]
Ah, way simpler than I thought; sadly it's not documented anywhere!

Telnetting to the address shown for `en0` on the host worked.
