### ISSUE TITLE
Docker crashes after a period of use

### ISSUE THREAD

**Issue by mitchless** [docker/for-mac#738]
### Expected behavior
When running services through Docker Compose, Docker will continue to run without raising "HTTP code 500".

### Actual behavior
After an indeterminate amount of time Docker fails with "HTTP code 500" from all containers

### Information

Diagnostic ID: F300968F-A4E1-4CB4-8515-171C650A12BE

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/F300968F-A4E1-4CB4-8515-171C650A12BE/20161004-112718.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce the behavior

I have been unable to narrow the steps, however this occurs during normal usage that worked just fine prior to this beta.

**Comment by lcalvy** [comment]
Hi,

I can easily reproduce on our test environment.

We heavy load datas in an import process. It's seems that concurrent data import in our mongodb container break all containers

```
Unexpected API error for coorpacademy_elasticsearch_1 (HTTP code 500)
Response body:
dial unix /Users/xxxx/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

Unexpected API error for coorpacademy_mongodb_1 (HTTP code 500)
Response body:
dial unix /Users/xxxx/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

Unexpected API error for coorpacademy_redis_1 (HTTP code 500)
Response body:
dial unix /Users/xxxx/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Comment by samoht** [comment]
@lcalvy could you please open a new issue with uploaded logs and your diagnostic ID so that we can investigate?

/cc @ijc25 the initial logs contain:

```
Oct  3 16:24:57 Mitchells-MacBook-Pro-2 Docker[com.docker.driver.amd64-linux][48424] <Notice>: Assertion failed: (s->local_shutdown != VIRTIO_VSOCK_FLAG_SHUTDOWN_ALL), function shutdown_local_sock, file src/pci_virtio_sock.c, line 869.
```

Is this related to docker/hyperkit#50 ?

**Comment by mitchless** [comment]
@samoht Any ETA on beta 28? This is the most frustrating Docker bug I've encountered since grindinglly slow OSXFS performance.

**Comment by samoht** [comment]
@mitchless before the end of the week

**Comment by ijc25** [comment]
@mitchless beta28 is out now, Thanks for your patience.

**Comment by mitchless** [comment]
Thanks @ijc25 and @samoht. I haven't seen a crash since I upgraded.
