### ISSUE TITLE
Synchronised File Sharing MongoDB data volume causes data corruption

### ISSUE THREAD

**Issue by Greg-Myers-SB** [docker/for-mac#7408]
### Description

As per title. With this feature turned on;
https://docs.docker.com/desktop/synchronized-file-sharing/
Using the MongoDB 6 image, and mounting the data volume, it will immediately become corrupt and MongoDB will fail with error code 14 and a WiredTiger error.

### Reproduce

Turn on the sync feature in Docker Desktop
```
docker run --name some-mongo -v /my/own/datadir:/data/db mongo:6
```
Instantly fails

### docker version

```bash
-
```

### docker info

```bash
-
```

### Diagnostics ID

-

**Comment by xenoscopic** [comment]
Hi @Greg-Myers-SB, can you verify that this occurs with the latest version of Docker Desktop (4.34.2)?  We did have an earlier bug where this issue occurred, but it was fixed in 4.30.

**Comment by xenoscopic** [comment]
I think this is likely fixed, please try the most recent version of DD and comment if the issue recurs.

**Comment by Greg-Myers-SB** [comment]
I confirm this is now fixed. Thank you.
