### ISSUE TITLE
always show starting

### ISSUE THREAD

**Issue by pengyaomail** [docker/for-mac#742]
### Information

Diagnostic ID: 90727529-2743-4406-8C89-0B64F2A8B3A2
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. open docker 
2. showing "starting" and run docker ps report
   $ docker ps
   Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by samoht** [comment]
Can you upload your diagnostic tarball to our private server (by choosing "Diagnose & Upload" in the "Diagnose & Feedback" menu item)? It is very hard to investigate your issue without any logs. Thanks!

**Comment by victorlin** [comment]
same issue, always starting

Diagnostic ID:
3CFC53D2-5294-4B4F-B132-3F851F847ABD

**Comment by lily1110** [comment]
the same .
the log is followed:
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.2 (build: 15C50)
logs: /tmp/A599E82F-B634-4249-B9A7-779C8E8E0BCF/20161019-195940.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/XmacZone/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Diagnostic ID:
A599E82F-B634-4249-B9A7-779C8E8E0BCF

**Comment by samoht** [comment]
@victorlin can you please open a new issue with more details, thanks!

---

@lily1110:

Detected symptom of problem 'processor-not-supported' in A599E82F-B634-4249-B9A7-779C8E8E0BCF/20161019-195940.

Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install for more information.

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
