### ISSUE TITLE
running engine: waiting for the Docker API: context deadline exceeded

### ISSUE THREAD

**Issue by LeafXiao** [docker/for-mac#7429]
### Description

An unexpected error occurred
Docker Desktop encountered an unexpected error and needs to close.
running engine: waiting for the Docker API: context deadline exceeded

### Reproduce

1) installed docker desktop  Version 4.33.0 (160616)
Engine: 27.1.1
Compose: v2.29.1-desktop.1
Credential Helper: v0.8.2
Kubernetes: v1.30.2
MacOS: Sequoia 15.0

2）run  docker desktop error: running engine: waiting for the Docker API: context deadline exceeded

### docker version

```bash
Engine: 27.1.1
```

### docker info

```bash
docker desktop
```

### Diagnostics ID

C593FA1F-ABB8-4F73-9C54-E15C73979C4C/20240924023659

### Additional Info

<img width="610" alt="image" src="https://github.com/user-attachments/assets/292cbb7d-7172-4428-8d05-72e2c7b3bcff">

**Comment by cc1724** [comment]
Is there any solution? I also encountered this situation.plz

**Comment by ajmz** [comment]
Me too.

**Comment by LeafXiao** [comment]
"registry-mirrors": [
    "https://docker.m.daocloud.io",
    "https://docker.nju.edu.cn",
    "https://dockerproxy.com"
  ]

solved the problem
