### ISSUE TITLE
Host network not working

### ISSUE THREAD

**Issue by jorgeparavicini** [docker/for-mac#7448]
### Description

Host network has been out of beta on Mac for a few weeks now. However, it does not seem to work at all. We have a gateway that should connect directly to port 5000 and forward requests to other services running either in Docker or via an IDE. The problem is that the gateway container never even receives those requests. The gateway works without issues on the IDE and on Linux with Host Network enabled. 
I've also followed this official documentation, which does not work either: https://docs.docker.com/engine/network/tutorials/host/

### Reproduce

1. Completely uninstall Docker
2. Reinstall docker to make sure it's a clean setup
3. Run `docker run --rm -d --network host --name my_nginx nginx`

### Expected behavior

We should be able to access the NGINX server on port 80. But the server does not respond to any requests

### docker version

Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.2 (167172)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Version:    27.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /Users/jorge/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /Users/jorge/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/jorge/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/jorge/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/jorge/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/jorge/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/jorge/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/jorge/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jorge/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /Users/jorge/.docker/cli-plugins/docker-scout

Server:
 Containers: 27
  Running: 25
  Paused: 0
  Stopped: 2
 Images: 27
 Server Version: 27.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.4-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: 6c10e1b7-f554-4f10-8fec-30cf08aa62e2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/jorge/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

### Diagnostics ID

EC518C6E-49B9-4305-AF42-47C74F0AB3BA/20241008065253

### Additional Info

Im happy to provide any additional info if required

**Comment by unfixa1** [comment]
In the macOS version of Docker Desktop, the host network mode may not be fully supported, which may result in the failure to receive requests correctly.
In addition, on the M1/M2 architecture, Docker Desktop may have some specific network configuration issues.
You can use [servbay](servbay.com) to check the environment compatibility issues, which is very convenient for database connection and PHP environment setup. This is much easier to use on Mac than Docker

**Comment by jpbriend** [comment]
@jorgeparavicini have you enabled the Host-Networking option in `Settings` - `Resources` - `Network`?
![Image](https://github.com/user-attachments/assets/011e545e-664d-4a03-b707-0b1780411a90)

**Comment by jorgeparavicini** [comment]
Thanks for the reply @jpbriend this worked. I guess I thought it was enabled by default once it came out of beta 😅 I will suggest a change on the docs to hint to the new location of this setting
