### ISSUE TITLE
Docker Desktop not starting on Mac (Sequoia)

### ISSUE THREAD

**Issue by christiaan78** [docker/for-mac#7455]
### Description

Docker had DNS resolve issues that were caused by the current MacOS Sequoia firewall bugs. I removed docker and all related directories, switched off the firewall, rebooted the Mac and downloaded the latest version and installed Docker again. Docker seems to start as activity monitor shows the processes but no UI is coming up. Also doing a docker version in the terminal results in asking if docker desktop is running. 

Mac Mini 2023
Apple M2
macOS 15.0.1 (24A348)

### Reproduce

1. Install MacOS docker.dmg package for docker desktop (latest version, Apple chip)
2. Start the install file and move the file into the applications folder as instructed. 
3. Start Docker using the app in launchpad. 
4. Nothing happens.

### docker version

Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### docker info

Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info

### Diagnostics ID

7FE35F34-4D52-4944-994D-2C8D512F3FBB/20241011114611

**Comment by darkboywonder** [comment]
After updating to mac OS 15.0.1, I'm also experiencing this issue.

**Comment by ml4** [comment]
I've had the same, and working through it, for ref, one may also want to run `brew remove docker-completion docker-credential-helper docker` in case of competing installs and related pathing.

**Comment by trintrintrava** [comment]
> I was able to fix this following another post.
> 
> Stop Docker Application
> 
> Check if Docker processes are stopped in the activity overview.
> 
> De-install docker (Finder > Apps > Docker right mouse > Toon pakketinhoud > … > Macos > Deinstall
> 
> Manually remove all remaining Docker files and directories. I put them on in list. Didn’t check for duplicates. Note that this of course will delete all your docker stuff.
> 
> sudo rm -Rf /Applications/Docker.app
> sudo rm -f /usr/local/bin/docker
> sudo rm -f /usr/local/bin/docker-machine
> sudo rm -f /usr/local/bin/com.docker.cli
> sudo rm -f /usr/local/bin/docker-compose
> sudo rm -f /usr/local/bin/docker-compose-v1
> sudo rm -f /usr/local/bin/docker-credential-desktop
> sudo rm -f /usr/local/bin/docker-credential-ecr-login
> sudo rm -f /usr/local/bin/docker-credential-osxkeychain
> sudo rm -f /usr/local/bin/hub-tool
> sudo rm -f /usr/local/bin/hyperkit
> sudo rm -f /usr/local/bin/kubectl.docker
> sudo rm -f /usr/local/bin/vpnkit
> sudo rm -Rf ~/.docker
> sudo rm -Rf ~/Library/Containers/com.docker.docker
> sudo rm -Rf ~/Library/Application\ Support/Docker\ Desktop
> sudo rm -Rf ~/Library/Group\ Containers/group.com.docker
> sudo rm -f ~/Library/HTTPStorages/com.docker.docker.binarycookies
> sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
> sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
> sudo rm -Rf ~/Library/Logs/Docker\ Desktop
> sudo rm -Rf /usr/local/lib/docker
> sudo rm -f ~/Library/Preferences/com.docker.docker.plist
> sudo rm -Rf ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
> sudo rm -f ~/Library/Preferences/com.electron.docker-frontend.plist
> sudo rm -Rf /Applications/Docker\n
> sudo rm -f /usr/local/bin/docker\n
> sudo rm -f /usr/local/bin/docker-machine\n
> sudo rm -f /usr/local/bin/docker-compose\n
> sudo rm -f /usr/local/bin/docker-credential-osxkeychain\n
> sudo rm -Rf ~/.docker\n
> sudo rm -Rf $HOME/Library/Containers/com.docker.docker
> ​

that worked for me, thanks, for me an additional step was reboot of mac before install docker

**Comment by Vk5548** [comment]
didn't you guys face this error: sudo rm -rf ~/Library/Containers/com.docker.docker 
Password:
rm: /Users/some/Library/Containers/com.docker.docker/.com.apple.containermanagerd.metadata.plist: Operation not permitted
rm: /Users/some/Library/Containers/com.docker.docker: Operation not permitted

How did you get around it?

**Comment by Smolyan91** [comment]
> I was able to fix this following another post.
> 
> Stop Docker Application
> 
> Check if Docker processes are stopped in the activity overview.
> 
> De-install docker (Finder > Apps > Docker right mouse > Toon pakketinhoud > … > Macos > Deinstall
> 
> Manually remove all remaining Docker files and directories. I put them on in list. Didn’t check for duplicates. Note that this of course will delete all your docker stuff.
> 
> sudo rm -Rf /Applications/Docker.app
> sudo rm -f /usr/local/bin/docker
> sudo rm -f /usr/local/bin/docker-machine
> sudo rm -f /usr/local/bin/com.docker.cli
> sudo rm -f /usr/local/bin/docker-compose
> sudo rm -f /usr/local/bin/docker-compose-v1
> sudo rm -f /usr/local/bin/docker-credential-desktop
> sudo rm -f /usr/local/bin/docker-credential-ecr-login
> sudo rm -f /usr/local/bin/docker-credential-osxkeychain
> sudo rm -f /usr/local/bin/hub-tool
> sudo rm -f /usr/local/bin/hyperkit
> sudo rm -f /usr/local/bin/kubectl.docker
> sudo rm -f /usr/local/bin/vpnkit
> sudo rm -Rf ~/.docker
> sudo rm -Rf ~/Library/Containers/com.docker.docker
> sudo rm -Rf ~/Library/Application\ Support/Docker\ Desktop
> sudo rm -Rf ~/Library/Group\ Containers/group.com.docker
> sudo rm -f ~/Library/HTTPStorages/com.docker.docker.binarycookies
> sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
> sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
> sudo rm -Rf ~/Library/Logs/Docker\ Desktop
> sudo rm -Rf /usr/local/lib/docker
> sudo rm -f ~/Library/Preferences/com.docker.docker.plist
> sudo rm -Rf ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
> sudo rm -f ~/Library/Preferences/com.electron.docker-frontend.plist
> sudo rm -Rf /Applications/Docker\n
> sudo rm -f /usr/local/bin/docker\n
> sudo rm -f /usr/local/bin/docker-machine\n
> sudo rm -f /usr/local/bin/docker-compose\n
> sudo rm -f /usr/local/bin/docker-credential-osxkeychain\n
> sudo rm -Rf ~/.docker\n
> sudo rm -Rf $HOME/Library/Containers/com.docker.docker
> ​

Its working on on macOS Sequoia 15.3.1 ✅ Thanks a lot = )

**Comment by michaelrokosh** [comment]
I had the same issue and fixed it with this workaround: https://github.com/docker/for-mac/issues/7520

**Comment by gprok** [comment]
This fixed the problem for me as well. (Sequoia 15.4)

**Comment by lapser** [comment]
This didn't work for me on Mac Studio with Apple M1 Max running Sequoia 15.4.

**Comment by lapser** [comment]
I made little progress: https://github.com/docker/for-mac/issues/7520#issuecomment-2817228838
