### ISSUE TITLE
Not able to start docker

### ISSUE THREAD

**Issue by chalothegreat** [docker/for-mac#746]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
There's not enough detail here. Could you please open a fresh report with at least the diagnostic id and a description of the problem?
