### ISSUE TITLE
Docker 4.35.0 listens on port 8888, preventing mapping container ports to 8888

### ISSUE THREAD

**Issue by richard-moats-tc** [docker/for-mac#7468]
### Description

Moving from **Docker for Mac** `4.34.3` to `4.35.0`, with no user containers running, the `com.docker.backend` process has started listening (with an HTTP server, it seems) on IPv6 port `8888`:
```
com.docker.backend      2469 richard.moats   46u  IPv6 0xbf4e0784a52b6017      0t0  TCP *:8888 (LISTEN)
```

Starting a container that exposes a port mapped to port `8888` thus fails:
```
ERROR: for config-backend  Cannot start service config-backend: Ports are not available: exposing port TCP 0.0.0.0:8888 -> 0.0.0.0:0: listen tcp4 0.0.0.0:8888: bind: address already in use
```

### Reproduce

1. `docker run -it --rm -p 8888:8888/tcp nginx:alpine`

result:
```
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8888 -> 0.0.0.0:0: listen tcp4 0.0.0.0:8888: bind: address already in use.
```
 

### Expected behavior

Docker should not block containers from exposing an IP port on any host IP port.

### docker version

Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.35.0 (172550)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1-desktop.1
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-desktop.1
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.14.0
    Path:     /Users/richard.moats/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 11.67GiB
 Name: docker-desktop
 ID: 31c6a73d-4b64-4309-a72e-e197d14b06c1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/richard.moats/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.tangocard.io/
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

### Diagnostics ID

7715A2E9-189F-406A-B363-C08F447CF458/20241028185123

**Comment by richard-moats-tc** [comment]
Seems to affect **Docker for Windows** users as well: https://forums.docker.com/t/docker-listening-on-port-8888-after-latest-update-no-running-containers/144633

**Comment by corrosive4354** [comment]
Check the ports in use:
You can use the following command to check which processes are listening on port 8888:

lsof -i :8888
If you find that it is com.docker.backend, you can try restarting Docker Desktop.

If it still doesn't work,
There are too many compatibility issues between docker and mac. You can use [Servbay](servbay.com) instead of docker to deploy the environment. Servbay is more professional on mac.

**Comment by panvid** [comment]
To solve this problem:

The update silently activate the *Send usage statistics* setting. This uses the port 8888.

Deactivate this in Docker Deskop settings:

https://forums.docker.com/t/docker-listening-on-port-8888-after-latest-update-no-running-containers/144633/4

**Comment by corrosive4354** [comment]
If possible, try to map the container's port to other ports, such as 8889 or other unused ports.

Also, it may be a compatibility issue between docker and mac. You can use [servbay](https://servbay.com) instead of docker, which is more professional on mac and has fewer bugs.

**Comment by doringeman** [comment]
Hello,

Thank you for your report!
We've identified and fixed the issues.

Here are the macOS builds for 4.35.1, soon to appear on https://docs.docker.com/desktop/release-notes/ as well.
macOS amd64: https://desktop-stage.docker.com/mac/main/amd64/173168/Docker.dmg
macOS arm64: https://desktop-stage.docker.com/mac/main/arm64/173168/Docker.dmg

Would you mind re-enabling "Send usage statistics" to test the patch and continue supporting our ongoing product improvement?

**Comment by NiklasBr** [comment]
After updating to 4.35.1 I am consistently getting these errors which I have never seen before:

```
Error response from daemon: network a479b377fb093119a935014f2be675c936e419d37edf872fccef8db93affb357 not found
```

Diagnostics: `39263439-8ED3-425A-A6C1-A4B1DD929F05/20241031141622`

**Comment by richard-moats-tc** [comment]
Version `4.35.1` fixes my reported issue. I appreciate the responsiveness!
