### ISSUE TITLE
Unix sock path limits

### ISSUE THREAD

**Issue by masonjm** [docker/for-mac#747]
### Expected behavior

Docker should start
### Actual behavior

Docker doesn't start
### Information

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1912)
logs: /tmp/496D76E1-01C0-463C-832C-908ABED87B8D/20161005-121455.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Domain/corp.example.com/Users/masonjm/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```
### Steps to reproduce the behavior
1. Install Docker.app
2. Launch Docker
3. Cry a little

**Comment by sabelo-iris** [comment]
Had same issue: https://github.com/docker/for-mac/issues/741  Resetting factory defaults on Docker solves the problem!

**Comment by sabelo-iris** [comment]
Careful however because all your images and containers will be destroyed.

**Comment by samoht** [comment]
Could you try running `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose` manually? It is hard to investigate your issue without a proper diagnostic archiver. Thanks1

**Comment by masonjm** [comment]
Archive uploaded: 496D76E1-01C0-463C-832C-908ABED87B8D

My guess is this has something to do with how IT setup my desktop. My user account is a "non-standard" location (`/Domain` rather than `/Users`). I've had some issues with setting stuff related to my directory account, too (like the default shell for Terminal).

**Comment by austinezell** [comment]
I am having the same issue running `OSX El Capitan 10.11.16`. `Docker for Mac` was running great for a couple weeks then towards the end of last week, it just stopped. The diagnosis output on (failure to) start is identical to @masonjm's. I've tried both beta and stable releases with no difference in the outcome.

I have run and uploaded the the diagnosis as well if you need more information.
> Your unique id is: AFFCBE71-DD8A-47C9-9510-F1A5C20CC0B2

**Comment by samoht** [comment]
@austinezell After looking at your logs your issue seems more related to docker/for-mac#61

**Comment by samoht** [comment]
@masonjm you have a lot of `TMCCFS xxxx ERROR needToScanThisExecve == ` in your logs. Do you need to do something to allow Trend Micro product to start/install Docker maybe? I am not very familiar with that product.

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by rockwellct** [comment]
I'm actually at the same place that masonjm is, and I have the same problem on another machine with and without Trend services running, and it won't work either way.  I've uploaded at diagnosis at 62AB6731-21AF-43F1-85EA-47225A39DA83

**Comment by masonjm** [comment]
I don't have rights to reopen the issue, but @rockwellct is having the same issue (we share an office).

If it's helpful, I don't have the issue on another computer that's using a local user account.

**Comment by ijc25** [comment]
62AB6731-21AF-43F1-85EA-47225A39DA83 contains (redacted):
```
Nov  2 16:51:46 $HOST Docker[com.docker.osx.hyperkit.linux][7582] <Critical>: Failed to listen on /Domain/$DOMAIN/Users/$USER/Library/Containers/com.docker.docker/Data/*00000002.000005f4: "listen unix /Domain/$DOMAIN/Users/$USER/Library/Containers/com.docker.docker/Data/*00000002.000005f4: bind: invalid argument"
```

Where the socket path length with `$DOMAIN` and `$USER` expanded is 109 characters. The maximum Unix socket path length on macOS is 104 characters. The prefix up to the `.../Data/` (which IIRC is the bit we cannot control) is 91 characters, l leaving 13 characters for the socket name itself, for which we currently use 18 characters. This socket is the vsock end point so includes the address and port number of the peer.

I assume that shortening `$DOMAIN` is out of the question. We'll need to think about what, if anything, we might be able to do about this.

**Comment by masonjm** [comment]
Awesome.

Maybe we could do something fancy with symlinks or hardlinks to get a shorter alias that docker could use? Or is it possible to install to a different prefix?

**Comment by ijc25** [comment]
> Maybe we could do something fancy with symlinks or hardlinks to get a shorter alias that docker could use? 

Sadly it is the full path to the _target_ of the symlink which matters, so no.

> Or is it possible to install to a different prefix?

AIUI you can install it wherever you like (or at least wherever your CorpIT policies will let you) but I don't know what, if any, effect that has on the stuff which goes into `~/Library/Containers` since I'm not really familiar with OSX on those terms. I suspect that particular path is independent of the install location, but maybe someone else who is watching can comment.

**Comment by akimd** [comment]
This was fixed long ago.
