### ISSUE TITLE
Docker Desktop no longer starts after reboot on Ubuntu 24.10

### ISSUE THREAD

**Issue by rbanffy** [docker/for-mac#7472]
### Description

After installing it on Ubuntu 24.10, it ran until the first reboot. From that point on, it no longer started. Starting the service on systemctl resulted in errors in the log. After correcting permissions on chrome-sandbox with `sudo chmod 4755 /opt/docker-desktop/chrome-sandbox`, Desktop starts as expected, but fails with the error:

```text
running engine: waiting for the Docker API: engine linux/qemu failed to run: running VM: running virtiofsd for /home:  Error entering sandbox: DropSupplementalGroups(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })
```

Diagnositcs id 60B3E031-821F-42DE-B5A2-2D1DE90C88A5/20241101174937

### Reproduce

1. Install Docker Desktop on Ubuntu 24.10
1. Reboot
1. It no longer starts
1. Run it directly from the /opt install and see the message about /opt/docker-desktop/chrome-sandbox
1. Correct permissions
1. Docker desktop now starts, but fails with the error on the description 

### docker version

Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:42 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux
Cannot connect to the Docker daemon at unix:///home/rbanffy/.docker/desktop/docker.sock. Is the docker daemon running?

### docker info

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /usr/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /usr/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///home/rbanffy/.docker/desktop/docker.sock. Is the docker daemon running?
errors pretty printing info

### Diagnostics ID

60B3E031-821F-42DE-B5A2-2D1DE90C88A5/20241101174937

**Comment by MihaelaStoica** [comment]
@rbanffy, please try with the latest Docker Desktop version from https://docs.docker.com/desktop/release-notes/

Support for Ubuntu 24.04 had been added in Docker Desktop 4.35 (see roadmap item https://github.com/docker/roadmap/issues/655).
For future reference, please report issues for Docker Desktop for Linux at https://github.com/docker/desktop-linux/issues.

**Comment by rbanffy** [comment]
Thank you. It works now on 24.10. Is there a more detailed changelog about what exactly changed to fix this issue?
