### ISSUE TITLE
Unable to Make Docker App Run - Stuck on Starting

### ISSUE THREAD

**Issue by ferrufino** [docker/for-mac#749]
### Things tried:
I've installed and uninstalled the app. Also restarting my macbook.

I've tried kitematic and docker toolbox instead of the app and didn't work. Made sure docker app is all uninstalled. Tried it again vice-versa. 

Googled similar errors didn't work.
### Output Diagnose 

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/119B02C6-8AF4-42A3-BD23-2D41EFBB5270/20161006-000429.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/Ferrufino/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Run Docker App

**Comment by clintberry** [comment]
I had same issue. Click on docker icon -> preferences -> reset -> factory defaults
Then it restarts and works... :-)

**Comment by ferrufino** [comment]
Thanks @clintberry ! That Solved it :)
