### ISSUE TITLE
Port conflicts with docker host networking

### ISSUE THREAD

**Issue by divin31** [docker/for-mac#7498]
### Description

I'm running Docker desktop on a Mac mini with M4 pro.
I have some containers that need to run in host mode. 
Ex. Beszel agent, pi-hole

With host networking enabled, I can run the container, however port conflict notifications keep appearing in docker desktop
![Image](https://github.com/user-attachments/assets/3e2cf070-6748-46e1-9256-a8684f87e99c)

Sometimes when I restart docker engine, I also get this error message:
![Image](https://github.com/user-attachments/assets/ac9e90ff-21a8-4bac-9571-72df01335be1)
When this happens, I have to exit docker and restart it. 
After starting my docker containers for the first time, Beszel sees the agent as down, until I restart Beszel agent container, then it works normally. 

I don't know if this issue is related to my other bug report which still persists: #7496 

### Reproduce

1. Enable host networking
2. run containers in host network mode

### Expected behavior

no port conflicts, containers should be able to communicate from the first start

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.36.0 (175267)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/lori/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.18.0-desktop.2
    Path:     /Users/lori/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.3-desktop.1
    Path:     /Users/lori/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/lori/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/lori/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/lori/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/lori/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/lori/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/lori/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/lori/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.0
    Path:     /Users/lori/.docker/cli-plugins/docker-scout

Server:
 Containers: 30
  Running: 30
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 27.3.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 21.47GiB
 Name: docker-desktop
 ID: 0cc854e6-6aea-46a8-86be-9bf2d030c3e0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/lori/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

49601AEC-AC4E-4766-8F39-80ECDAD2F368/20241205063657

### Additional Info

I already tried resetting docker to factory defaults. The same problems appeared after the reset.

**Comment by aheck** [comment]
The problem with port 53 being in use is probably because mDnsResponder is started by virtualization framework. See this issue for more details: https://github.com/docker/for-mac/issues/5335

You can try to enable "Use kernel networking for UDP" in Settings / Resources / Network. This might fix the problem.

For the other ports: Did you check what services they are used for and if there is something listening on the host already on those ports? You start several containers. Is it possible that two or more containers try to use the same ports?

**Comment by divin31** [comment]
> The problem with port 53 being in use is probably because mDnsResponder is started by virtualization framework. See this issue for more details: [#5335](https://github.com/docker/for-mac/issues/5335)
> 
> You can try to enable "Use kernel networking for UDP" in Settings / Resources / Network. This might fix the problem.
> 
> For the other ports: Did you check what services they are used for and if there is something listening on the host already on those ports? You start several containers. Is it possible that two or more containers try to use the same ports?

Port 53 seemed good, because it worked fine when I was using it with port binding. 
The port conflicts appeared for every container running in host mode. Some for ports I used, some which I did not. 

After enabling "Use kernel networking for UDP" all the random port conflicts (for ports which I didn't use) seemed to have disappeared. Restarted docker engine, and got another port conflict error for 8008 and 53, which I use for my pi-hole container. 

I checked all the ports that are being used by containers running in host mode, with `lsof -i tcp:<port>`, and it turned out, I did have a port conflict after all on port 45876 (used by beszel agent). 
I have installed the agent on two different devices using the same port. It wasn't the agent causing the issue, but the server which was listening on the same port from both agents.

```
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 34807 lori  457u  IPv4 0xac5e25eec230491d      0t0  TCP mac:62757->nas:45876 (ESTABLISHED)
com.docke 34807 lori  466u  IPv4 0xc556790718076428      0t0  TCP mac:53365->mac:45876 (ESTABLISHED) 
```

After changing the port on one of the agents, all the port conflicts disappeared (including 53 and 8008).

Turning off "Use kernel networking for UDP" however brings the random port conflicts back.
I checked some of the ports with the same command:

```
lori@MAC ~ % lsof -i tcp:63031
lsof: WARNING: can't stat() smbfs file system /Volumes/.timemachine/NAS._smb._tcp.local./9E098888-7AF8-4781-831E-26762286AB2D/Time Machine
      Output information may be incomplete.
      assuming "dev=36000080" from mount table
lori@MAC ~ % lsof -i tcp:58129
lsof: WARNING: can't stat() smbfs file system /Volumes/.timemachine/NAS._smb._tcp.local./9E098888-7AF8-4781-831E-26762286AB2D/Time Machine
      Output information may be incomplete.
      assuming "dev=36000080" from mount table
lori@MAC ~ % lsof -i tcp:57547
lsof: WARNING: can't stat() smbfs file system /Volumes/.timemachine/NAS._smb._tcp.local./9E098888-7AF8-4781-831E-26762286AB2D/Time Machine
      Output information may be incomplete.
      assuming "dev=36000080" from mount table
```

I'm not sure I entirely understand what "Use kernel networking for UDP" did, and why I got port conflicts on ports which were in fact not in conflict.

**Comment by divin31** [comment]
Spent too much time trying to debug and fix connection issues. I gave up. Switched to orbstack, everything is now working perfectly.
