### ISSUE TITLE
Dockerised GUI apps

### ISSUE THREAD

**Issue by joeblew99** [docker/for-mac#75]
There has been a few different approaches to running GUI apps on docker native.

In my case I want to use it for medical applications.

I would like to be able to bundle the docker for Mac ( and windows) in my installer, to the point that it's invisible from the user.

**Comment by dsheets** [comment]
How about having your users install Docker for Mac as a prerequisite to your application?

What additional features would you need for your use case?

**Comment by joeblew99** [comment]
@dsheets 
off the top of my head the low hanging fruit is:

- Screen to be captured to run as a app. X11
- Dialogue boxes to be native
- File system view of host file system.
- sounds and video

For me, its got to be invisible to them that is IS running inside a docker container.
Having to install the docker runtime first is not the end of the world though. I guess its a bit like having to install Java first :)

**Comment by joeblew99** [comment]
also the implementation would probably need to be a bit like how Electron works.

I would use golang to write it.


For each host OS, you woudl have a library that does the above functionality. 

For example opening a native file open dialogue.

For the guest, you would need to code to the docker apps API to open a native file open dialogue.
It would then make a call to the host OS to open the native file open dialogue, and return back the file handle.

To make it programming language agnostic, for the developers writing their apps, i would be tempted to use GRPC to expose this functionality.
