### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by Caracal-IT** [docker/for-mac#750]
### Information

Diagnostic ID: AB6EF2C9-C7FB-4337-8144-89E7E64758C1
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/ettienemare/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/AB6EF2C9-C7FB-4337-8144-89E7E64758C1/20161006-075318/qemu-img-check.stdout 2> /tmp/AB6EF2C9-C7FB-4337-8144-89E7E64758C1/20161006-075318/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by yallop** [comment]
Thank you for the report.  This appears to be a harmless error: `qemu-img check` is reporting a leaked cluster, but no data corruption.  I'm going to close this, but if you see additional symptoms that suggest there might be a more serious problem, please open a new report with the details.
