### ISSUE TITLE
Unable to route to certain IP addresses

### ISSUE THREAD

**Issue by rpungello** [docker/for-mac#7504]
### Description

Running into a very weird routing issue with Docker Desktop on macOS 15.1.1. I have a travel router that has a mini PC connected via ethernet to it, and a MacBook connected via WiFi. From macOS, I can access all the services the mini PC provides. However, from Docker contains, I cannot access anything. I can't even ping it, though I can ping the router.

If I run tcpdump on the Docker container, my MacBook, and the router, I get the following

Docker pinging router: all display the packets
Host pinging router: host & router display the packets
Host pinging mini PC: host & router display the packets
Docker pinging mini PC: tcpdump in container shows them, but neither the host (my Mac), nor the router pick them up.

The docker container can access anything else, either on the public internet or the other side of the VPN my travel router connects to, it just cannot seem to access any other local devices on the travel router's subnet. My first thought was the router, but tcpdump is showing those packets aren't even making it out of the Docker container (as macOS tcpdump isn't picking them up), but I can't even begin to think of a reason that would be happening. One odd thing is running `netstat -rn` from macOS is showing a bunch of single-IP routes, including for the IP of the mini PC. I'm not sure how this could negatively impact things given macOS can communicate with it, but figured I'd mention it.
I sadly don't currently have any other devices to test Docker with.

I can only assume there's something happening with the VM Docker Desktop creates, but I'm unsure of how to troubleshoot that.

### Reproduce

1. docker run --rm -it ubuntu /bin/bash
2. apt update && apt install -y iputils-pint
3. ping 10.5.50.5

### Expected behavior

I can ping this address just fine from my MacBook, but the Docker container cannot. The prompt just sits there. The container can ping public IPs just fine, so networking is there, it's just the routing seems off for local addresses somehow.

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.36.0 (175267)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/rob/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.18.0-desktop.2
    Path:     /Users/rob/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.3-desktop.1
    Path:     /Users/rob/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/rob/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/rob/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/rob/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/rob/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/rob/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/rob/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/rob/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.0
    Path:     /Users/rob/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 27.3.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.654GiB
 Name: docker-desktop
 ID: 1bdb9418-29ed-44ff-b616-f64fc1203af4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/rob/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

20241212020407

**Comment by rpungello** [comment]
Turned out to be the macOS setting to block local network access.

**Comment by jnko266** [comment]
@rpungello Hi! I think I'm having a similar problem. Care to share where this is located? Thanks!

**Comment by rpungello** [comment]
> [@rpungello](https://github.com/rpungello) Hi! I think I'm having a similar problem. Care to share where this is located? Thanks!

System Settings > Privacy & Security > Local Network
