### ISSUE TITLE
can't set sysctl parameters

### ISSUE THREAD

**Issue by seffenberg-naspers** [docker/for-mac#752]
see #231 for more details. In general setting sysctl parameters should be possible via the interface or following a documented path.

In my case I need fs.inotify.max_user_watches to be _much_ bigger than the 8192 

see also:
https://forums.docker.com/t/docker-for-mac-how-to-set-host-settings-sysctl-etc/11168

**Comment by justincormack** [comment]
The default is 524288:

```
docker run alpine sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 524288
```

**Comment by seffenberg-naspers** [comment]
so it must have been wrong in an older version
