### ISSUE TITLE
Volume names are not shown

### ISSUE THREAD

**Issue by imavroukakis** [docker/for-mac#753]
### Expected behavior
When create a docker volume with --name I expect the name to appear when doing `docker volume ls`
### Actual behavior
`docker volume ls` shows the hash of the volume, not the name
### Information
```
BF24F480-F4EC-451E-B6CB-F0F6F9F9AC9B
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/BF24F480-F4EC-451E-B6CB-F0F6F9F9AC9B/20161006-161209.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```
### Steps to reproduce the behavior
`docker create -v /some_dir --name foo_bar ubuntu /bin/true`
`docker volume ls`

Output
```
➜  data docker volume ls
DRIVER              VOLUME NAME
local               8e9efa92319f105999c9f58a3c3ff22e467b0f1fbb6b126d35d6fc12094ffd04
```

**Comment by yallop** [comment]
Are you running `docker create` or `docker volume create`?

```
$ docker volume create --name foo_bar
foo_bar
$ docker volume ls
DRIVER              VOLUME NAME
local               foo_bar
```

**Comment by imavroukakis** [comment]
`docker create`. Am I making a noobish mistake?

**Comment by yallop** [comment]
`docker create` is for creating containers.  It sounds like you want [`docker volume create`](https://docs.docker.com/engine/reference/commandline/volume_create/).

**Comment by imavroukakis** [comment]
noobish mistake it is, my apologies.
