### ISSUE TITLE
Ghost Services after Hard Reboot on a Mac

### ISSUE THREAD

**Issue by laugimethods** [docker/for-mac#754]
### Expected behavior

```
> docker service rm spark-slave spark-master
spark-slave
spark-master
```
### Actual behavior

```
> docker service rm spark-slave spark-master
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```
### Information

Diagnosis ID: 783964D6-AD3B-4823-8219-C4CD33842231

> Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
> OS X: version 10.11.6 (build: 15G1004)
> logs: /tmp/783964D6-AD3B-4823-8219-C4CD33842231/20161006-094746.tar.gz
> [OK]     docker-cli
> [OK]     virtualization kern.hv_support
> [OK]     menubar
> [OK]     moby-syslog
> [OK]     dns
> [OK]     disk
> [OK]     system
> [OK]     app
> [OK]     osxfs
> [OK]     virtualization VT-X
> [OK]     db
> [OK]     slirp
> [OK]     logs
> [OK]     env
> [OK]     vmnetd
> [OK]     moby-console
> [OK]     moby
> [OK]     driver.amd64-linux

```
> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 50
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 263
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 9un6ji3cs3r3khyfkxh62er8v
 Is Manager: true
 ClusterID: 3158v60tvdpprku3hxdt9a784
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.787 GiB
Name: moby
ID: OQW3:USVR:IW6V:GM57:SC2U:VCYS:MX65:M6AI:RR2J:LAZO:7JFW:JKZM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 130
 System Time: 2016-10-06T13:47:06.606683746Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: lmagnin
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

> docker service ls
ID            NAME          REPLICAS  IMAGE                               COMMAND
8vsmcflwpz6u  spark-slave   1/1       gettyimages/spark:1.6.2-hadoop-2.6  sleep infinity
f2tzfcrhubz0  spark-master  0/1       gettyimages/spark:1.6.2-hadoop-2.6  sleep infinity

> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
### Steps to reproduce the behavior

```
> docker swarm init
> docker network create --driver overlay spark-net
> docker service create --name spark-master -p 8080 -e SERVICE_NAME=spark-master --network spark-net  gettyimages/spark:1.6.2-hadoop-2.6 sleep infinity
> docker service create --name spark-slave -e SERVICE_NAME=spark-slave --network spark-net  gettyimages/spark:1.6.2-hadoop-2.6 sleep infinity
```

Then Hard Reboot Mac OS X...

**Comment by laugimethods** [comment]
Swarm is also affected:
```
> docker swarm update
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Comment by samoht** [comment]
Analysing report with diagnostic ID 783964D6-AD3B-4823-8219-C4CD33842231 and timestamp 20161006-094746
Detected symptom of problem 'aufs-corruption' in 783964D6-AD3B-4823-8219-C4CD33842231/20161006-094746.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
 >
> time="2016-09-29T20:11:30.143273960Z" level=debug msg="Using default logging driver json-file"
> time="2016-09-29T20:11:30.143919113Z" level=debug msg="Golang's threads limit set to 56970"
> time="2016-09-29T20:11:30.151350343Z" level=info msg="[graphdriver] using prior storage driver \"aufs\""
> time="2016-09-29T20:11:30.151752926Z" level=debug msg="Using graph driver aufs"
> time="2016-09-29T20:11:30.789303372Z" level=debug msg="Failed to load mount 3781a9298ff26a39b59fd796f12dfd0775ce03b2e4df7c17c3f7b2124e6b4028: invalid mount id value"
> time="2016-09-29T20:11:30.789734247Z" level=debug msg="Failed to load mount bc94640713357d0231cfca5fa166aa1fbd2a94b02ee1214b47231d496ee1697d: invalid mount id value"
> time="2016-09-29T20:11:30.790048098Z" level=debug msg="Max Concurrent Downloads: 3"
> time="2016-09-29T20:11:30.790342178Z" level=debug msg="Max Concurrent Uploads: 5"
> time="2016-09-29T20:11:30.942791623Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
> time="2016-09-29T20:11:30.945487261Z" level=error msg="Failed to load container mount 3781a9298ff26a39b59fd796f12dfd0775ce03b2e4df7c17c3f7b2124e6b4028: mount does not exist"

**Comment by samoht** [comment]
You seem to have hit an AUFS corruption error, I am not sure why this is related to your swarm issue though..

**Comment by ijc25** [comment]
@laugimethods did a reset to defaults solve the aufs issue as expected? It would be worth trying the latest stable (1.12.3 at the time of writing) or even beta (beta30.1) since as well as aufs related fixes  they incorporate newer versions of the docker engine and therefore various swarm bug fixes.

Please let us know if you still see this with the latest versions.

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
