### ISSUE TITLE
docker macos Sierra still starting mode

### ISSUE THREAD

**Issue by doniatc** [docker/for-mac#755]
### Expected behavior
Docker is running

### Actual behavior
Docker is starting... with an animation in menubar

### Information
Diagnostic ID : 859CB917-85CB-4096-A407-2900486955AA

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/859CB917-85CB-4096-A407-2900486955AA/20161006-174513.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/nameofmachine/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. Install Docker for Mac in Application Folder
  2. Double-click on the icon application Docker and wait until the app is running

**Comment by gpherguson** [comment]
I'm seeing a similar problem with Mac OS El Capitan:

Diagnostic ID : 403AF4D3-6EC5-4A57-B551-21551F2EB9A3

    Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
    OS X: version 10.11.6 (build: 15G1004)
    logs: /tmp/403AF4D3-6EC5-4A57-B551-21551F2EB9A3/20161006-153852.tar.gz
    failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
    [ERROR]  docker-cli
             docker ps failed
    [OK]     virtualization kern.hv_support
    [OK]     menubar
    [OK]     moby-syslog
    [OK]     dns
    [OK]     disk
    [OK]     system
    [OK]     app
    [OK]     osxfs
    [OK]     virtualization VT-X
    [OK]     db
    [OK]     slirp
    [OK]     logs
    [OK]     env
    [OK]     vmnetd
    [OK]     moby-console
    [OK]     moby
    [OK]     driver.amd64-linux
    Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Docker has been working prior to this latest update.

**Comment by Habbie** [comment]
OS X 10.10.5:

```
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.10.5 (build: 14F1912)
logs: /tmp/9076A683-FF59-4B14-9DEA-EABC8FB80925/20161007-125940.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/peter/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by doniatc** [comment]
Hello Peter,

Do you find a way to start Docker for Mac, anyway?

Regards,

Christophe

Le 2016-10-07 13:01, Peter van Dijk a écrit :

**Comment by doniatc** [comment]
Hello,

Do you find a tip to get Docker for Mac on macos Sierra running?

Regards,

Christophe

Le 2016-10-07 00:41, G. Ferguson a écrit :

**Comment by samoht** [comment]
@doniatc on which model/year do you try to run the product? the logs seems to indicate

```
Oct  6 16:27:49 iMac-de-ZartMacOne Docker[com.docker.driver.amd64-linux][547] <Notice>: vmx_init: processor not supported by Hypervisor.framework
```

See https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install

On older OSX machines, you can still use [docker-machine](https://docs.docker.com/machine/) with VirtualBox.
