### ISSUE TITLE
Unable to get/create a Diagnostic ID

### ISSUE THREAD

**Issue by schmunk42** [docker/for-mac#757]
### Expected behavior

See a Diagnostic ID
### Actual behavior

I don't see a Diagnostic ID
### Information

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/20161006-222419.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

<img width="832" alt="bildschirmfoto 2016-10-06 um 22 24 32" src="https://cloud.githubusercontent.com/assets/649031/19169234/bf3be092-8c13-11e6-819a-ca826c1919f8.png">
### Steps to reproduce the behavior
1. Open Diagnose & Feedback

FYI: I did a complete reinstall before writing this.

**Comment by dsheets** [comment]
What happens if you run `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose`?

**Comment by schmunk42** [comment]
```
[...]
=> system_profiler SPFirewallDataType > /tmp/20161010-143121/SPFirewallDataType
=> system_profiler SPHardwareDataType > /tmp/20161010-143121/SPHardwareDataType
=> tar -C /tmp -cz "20161010-143121" > "/tmp/20161010-143121.tar.gz"
Docker logs are being collected into /tmp/20161010-143121.tar.gz
Would you like to upload log files? [Y/n]: Y

=> date '+%a, %d %b %Y %T %Z'
=> stdout:
Mo, 10 Okt 2016 14:31:28 CEST

=> /usr/bin/curl -L -X PUT -T '/tmp/20161010-143121.tar.gz' -H 'Host: docker-pinata-support' -H 'Date: Mo, 10 Okt 2016 14:31:28 CEST' -H 'x-amz-acl: bucket-owner-full-control' -H 'Content-type: application/json' https://docker-pinata-support.s3.amazonaws.com/incoming/2/20161010-143121/report.tar
=> stderr:


Your unique id is: 
Please quote this in all correspondence.
=> rm -rf /tmp/20161010-143121
```

**Comment by dsheets** [comment]
What is the output of `uuidgen`? `cat ~/Library/Containers/com.docker.docker/Data/user.id`?

**Comment by schmunk42** [comment]
```
tobias in ~ λ uuidgen
dyld: Library not loaded: libuuid.1.1.dylib
  Referenced from: /usr/local/bin/uuidgen
  Reason: image not found
[1]    57948 trace trap  uuidgen
```

No idea why this is not working?!

```
cat ~/Library/Containers/com.docker.docker/Data/user.id
```

no output

**Comment by dsheets** [comment]
It looks like you have a `uuidgen` executable installed from a non-distribution source like homebrew or MacPorts. The executable under `/usr/bin/uuidgen` should work fine and if you run it and redirect its output to `~/Library/Containers/com.docker.docker/Data/user.id` then you should have a diagnostic ID and be able to upload reports. I've filed an internal issue to track our incorrect execution of `uuidgen` and the lack of `uuidgen` failure error handling.

Thanks for your report and help getting to the bottom of this issue!

**Comment by schmunk42** [comment]
You're right :), thank you.

```
tobias in ~ λ which uuidgen 
/usr/local/bin/uuidgen

tobias in ~ λ /usr/bin/uuidgen
B6A47250-A29D-4177-B385-3B76A32EDF3F
```
