### ISSUE TITLE
86E988E6-CA16-4D6C-A46D-4EEF28F7350F

### ISSUE THREAD

**Issue by 5HT** [docker/for-mac#760]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/86E988E6-CA16-4D6C-A46D-4EEF28F7350F/20161007-125754.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/5HT/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/5HT/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/5HT/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/5HT/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/5HT/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/5HT/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/5HT/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in 86E988E6-CA16-4D6C-A46D-4EEF28F7350F/20161007-125754.

The UI failed to communicate with the networking helper process.

May be related to docker/for-mac#61

The following log matches:
 >
> Oct  7 12:53:46 mac Docker[com.docker.docker][23113] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
> Oct  7 12:53:47 mac Docker[com.docker.docker][23113] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
> Oct  7 12:53:48 mac Docker[com.docker.docker][23113] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
> Oct  7 12:53:49 mac Docker[com.docker.docker][23113] <Critical>: Communication with networking components failed.
> Oct  7 12:56:38 mac Docker[com.docker.vmnetd][97] <Notice>: com.docker.vmnetd starting
> Oct  7 12:56:42 mac com.apple.xpc.launchd[user][1] <Error>: Could not import service from caller: caller = otherbsd.244, service = com.docker.helper, error = 119: Service is disabled
> Oct  7 12:56:42 mac otherbsd[user][244] <Error>: Could not submit LoginItem job com.docker.helper: 119: Service is disabled
> Oct  7 12:56:46 mac deleted[daemon][440] <Error>: normalizeUserMountpoint:791 volRoot failed for /Volumes/Docker

@5HT a possible workaround is described in [that comment](https://github.com/docker/for-mac/issues/8#issuecomment-236183193). I am closing the issue for now on, but please re-open if you don't manage to start Docker after trying the workaround.
