### ISSUE TITLE
No response from docker

### ISSUE THREAD

**Issue by blahster** [docker/for-mac#761]
### Expected behavior
`docker ps` should respond as should any other `docker` command.
Also, Kitematic (Beta) is stuck at 99% "Checking Docker" :)
### Actual behavior
No response
### Information
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/D6F8A6B4-F741-4E12-B236-896068E0DB81/20161007-204450.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. `docker ps` or `docker info`

**Comment by blahster** [comment]
Looking for help... problem continues..

**Comment by JanBednarik** [comment]
Have you tried reset Docker to factory defaults?

**Comment by blahster** [comment]
I could but I'd lose images etc.

**Comment by samoht** [comment]
Analysing report with diagnostic ID D6F8A6B4-F741-4E12-B236-896068E0DB81 and timestamp 20161007-204450
Detected symptom of problem 'qcow2-corruption' in D6F8A6B4-F741-4E12-B236-896068E0DB81/20161007-204450.

This error suggests that the .qcow2 file is corrupt and will need to be recreated.

May be related to docker/for-mac#11

The following log matches:
 >
> Oct  6 23:43:34 Hemanth Docker[com.docker.slirp][767] <Notice>: Using protocol TwoThousand msize 8192
> Oct  6 23:43:35 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: VM: 2016-10-06 18:13:34 +0000 UTC daemon.info vsudd: Connection 1 to: 2376 from: 00000000
> Oct  6 23:43:36 Hemanth Docker[com.docker.driver.amd64-linux][769] <Warning>: VM: 2016-10-06 18:13:35 +0000 UTC kern.notice kernel: random: nonblocking pool is initialized
> Oct  6 23:43:37 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: Thread 1 killed on uncaught exception Invalid_argument("Cstruct.sub: [0,4096](4096) off=0 len=-42496")
> Oct  7 00:48:59 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: System wants to go to sleep
> Oct  7 00:48:59 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: Asking com.docker.hyperkit to freeze vcpus
> Oct  7 00:48:59 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: vcpu 0 waiting for signal to resume
> Oct  7 00:48:59 Hemanth Docker[com.docker.driver.amd64-linux][769] <Notice>: vcpu freeze complete: allowing sleep
> Oct  7 00:48:59 Hemanth kernel[kern][0] <Notice>: PM response took 116 ms (769, com.docker.drive)

**Comment by samoht** [comment]
I am afraid your qcow2 image is indeed corrupted. 

We don't yet provide a tool to try to recover your images, although this is something that we might consider in the future. `qemu-img check` tools can maybe help you to recover some files in the corrupted qcow2 image, but will probably not be the case. I am sorry, but reseting to factory settings is indeed the simplest solution for now on.

**Comment by samoht** [comment]
Or you can try to use `qemu-img convert` to read your qcow2 file.

**Comment by blahster** [comment]
Reset :(
