### ISSUE TITLE
Docker fails to start.

### ISSUE THREAD

**Issue by sbergsten** [docker/for-mac#764]
### Expected behavior
Docker starts and then runs.

### Actual behavior
Docker attempts to start indefinitely.  It seems to be hung with the "Docker starting..." in the drop down.  The first time I started it, it ran.  After shutting down and restarting it is hung.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/F182A2A2-B861-4909-AD4A-EE0FF9AA6B17/20161007-122527.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Hi thanks your report, but unfortunately we cannot help you as the diagnostic logs haven't been uploaded (we are independently working on making that upload more reliable). Could you try running the diagnostic tool again, and if possible on a network configuration without proxy/VPN/etc ? Thanks!

**Comment by samoht** [comment]
Weirdly, it appears that the upload worked properly, and I can see the following in your logs:

```
> time="2016-10-06T20:54:21.041253925Z" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
> time="2016-10-06T20:54:21.062771573Z" level=debug msg="containerd: read past events" count=0
> time="2016-10-06T20:54:21.063565955Z" level=debug msg="containerd: supervisor running" cpus=4 memory=1999 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
> time="2016-10-06T20:54:21.06413238Z" level=debug msg="containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock"
> time="2016-10-06T20:54:22.057445159Z" level=fatal msg="Error starting daemon: mkdir /var/lib/docker: structure needs cleaning"
> time="2016-10-06T21:10:10.976008588Z" level=debug msg="docker group found. gid: 50"
> time="2016-10-06T21:10:10.978508717Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
> time="2016-10-06T21:10:10.980106950Z" level=info msg="libcontainerd: new containerd process, pid: 1426"
> time="2016-10-06T21:10:10.982502571Z" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
> time="2016-10-06T21:10:11.004801213Z" level=debug msg="containerd: read past events" count=0
```

I am not sure why, but this seems to indicate that containerd does not start.

**Comment by samoht** [comment]
There are also other "interesting" issue in your logs:

```
Oct  6 15:51:55 DALC02QRBFPG8WN Docker[com.docker.docker][40585] <Error>: Symlinks are not correctly installed.
```

And then a lot of:

```
Oct  6 15:52:03 DALC02QRBFPG8WN com.docker.driver.amd64-linux[com.apple.Libsystem.malloc][41129] <Error>: com.docker.driver.amd64-linux(41129,0x700000635000) malloc: *** error for object 0x4904538: incorrect checksum for freed object - object was probably modified after being freed.
        *** set a breakpoint in malloc_error_break to debug
Oct  6 15:52:03 DALC02QRBFPG8WN Docker[com.docker.osx.hyperkit.linux][41009] <Notice>: Reap com.docker.driver.amd64-linux (pid 41129): exit status 2
```

**Comment by dsheets** [comment]
This issue is now being tracked in #819 with a user running beta 28. If you are interested in following along, please subscribe to that issue and/or switch to the beta channel.

Thanks for your report!
