### ISSUE TITLE
Docker Beta doesn't start

### ISSUE THREAD

**Issue by lev4ik** [docker/for-mac#766]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Can you please provide more information? e.g. by followings the steps described in https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues or by giving us a bit more of information on the system that you are using, the steps which worked and the one which didn't during the install process. Thanks!
