### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by axeralater** [docker/for-mac#767]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Can you please provide more information? I am closing the issue now, but please feel free to re-open with a more detailed description of your error, your settings and if possible a diagnostic ID so that we can investigate your issue more.
