### ISSUE TITLE
Docker hangs after several hours of inactivity

### ISSUE THREAD

**Issue by rsaftoiu** [docker/for-mac#768]
### Expected behavior

Docker continues to work even after long periods of inactivity.

### Actual behavior

After about 5 hours of stopping usage of my Mac,  I went back to it and docker seems to be stuck. All commands are timing out, even shells I left open in running containers.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: [20161007-233648.tar.gz](https://github.com/docker/for-mac/files/517488/20161007-233648.tar.gz)
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

Not quite sure, it's happened a few times:

  1. Boot up docker + spawn a few containers
  2. Wait a few hours
  3. Run docker ps and observe it hanging.
  4. Under energy saver I have computer sleep set to never, and display sleep set to 10 mins.

**Comment by samoht** [comment]
It would be very helpful if you could manage to upload a diagnostic tarball to our remote server:

```
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

Means that you are probably running behind a proxy/firewall. Would it be possible to disable that setting temporally and try again the next time you get such a crash? Thanks!

**Comment by samoht** [comment]
I managed to found your diagnostic tarball (for some random reason, it has been updated although the diagnostic tool says the contrary).

It seems that your Docker for Mac goes to quarantine about 4/5h hours:

```
Oct  4 10:37:12 ElCapHack kernel[kern][0] <Notice>: process com.docker.hyper[547] caught causing excessive wakeups. Observed wakeups rate (per sec): 305; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 73077
Oct  4 10:37:18 ElCapHack spindump[com.apple.console][393] <Notice>: Saved wakeups_resource.diag report for com.docker.hyperkit version ??? (???) to /Library/Logs/DiagnosticReports/com.docker.hyperkit_2016-10-04-103718_ElCapHack.wakeups_resource.diag
Oct  4 11:00:06 ElCapHack SubmitDiagInfo[daemon][394] <Notice>: Removed expired problem report: file:///Library/Logs/DiagnosticReports/com.docker.hyperkit_2016-08-29-220250_Raress-iMac.wakeups_resource.diag
```

I don't have the full contents of your logs (we try to scrap only what is related to Docker for Mac) so it would be useful if you could see what the `kern` process decides to do after noticing this kind of events.

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by daveisfera** [comment]
What is the more info that's needed? I've seen this happen a few times and uploaded logs from it. Is there something else that you need to have provided?

**Comment by dave-tucker** [comment]
> I've seen this happen a few times and uploaded logs from it

Thanks for uploading the reports! What would be really helpful is also posting the diagnostic ID in this issue as otherwise it's very hard for us to know which reports to look in to.

> Is there something else that you need to have provided?

Yes, to troubleshoot this further we really need either:

-  A reproducible case
  - FWIW, I have the same settings in "Energy Saver" as in the original report but I don't see an issue...

Or:

- More reports!
  - The original bug was reported on `1.12.1 Stable`. Does this issue effect Beta users too?
  - Is this bug only present on macOS 10.11.x? Or is it also present on 10.12?
  - Does this bug occur on desktop or laptop hardware, or both?

- More logs!
  - When this happens, what do the system log entries say*after* ```kernel[kern][0] <Notice>: process com.docker.hyper[547] caught causing excessive wakeups.```?

**Comment by bmbroom** [comment]
I see this bug all the time now using docker for mac beta (currently 1.12.2-beta28).

When I do 'Diagnose & Feedback' I get an error report that looks nearly identical to that in the original report:
Docker for Mac: version: 1.12.2-beta28 (71c4a00)
OS X: version 10.10.3 (build: 14D136)
logs: /tmp/9518ADD2-2AEF-434A-9083-6DC4A695530D/20161025-103704.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Hardware is a late 2013 Mac Pro.

You'll have to tell me how to get the additional log entries you want.

**Comment by daveisfera** [comment]
Here's the Diagnostic ID (`3059FBF4-118B-4268-9AE1-74314EC1D71E`) but I'm not sure how useful it is because it appears that it wasn't uploaded:
```
Oct 31 08:30:27 Daves-MBP Docker[89439]: TextView: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
Oct 31 08:30:27 Daves-MBP lsd[253]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
Oct 31 08:30:41 --- last message repeated 1 time ---
Oct 31 08:30:41 Daves-MBP Docker[89457]: failed to establish 9P connection: Caught EOF on underlying FLOW
Oct 31 08:30:41 Daves-MBP Docker[93753]: EOF reading packet from Unix domain socket: closing
Oct 31 08:30:41 Daves-MBP Docker[93753]: Failed to read hello from client
Oct 31 08:30:43 Daves-MBP WindowServer[164]: send_datagram_available_ping: pid 950 failed to act on a ping it dequeued before timing out.
Oct 31 08:31:17 Daves-MBP Docker[89439]: WizardMessage: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

I'm running Docker 1.12.3-beta29.2 (13499) on a Mac Book Pro and this seems to happen most weekends when I come in on Monday morning after the laptop has been sitting idle most, if not all of, the weekend.

**Comment by dsheets** [comment]
@bmbroom @daveisfera please open new issues with what you've observed and your diagnostic reports and IDs. It's unlikely the root cause of your issues are the same as the original poster and we are very unlikely to properly handle your issues on a closed ticket. Thanks!

**Comment by daveisfera** [comment]
@dsheets I opened issue #921.
