### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by hoeghh** [docker/for-mac#769]
Want to be able to get remote audio from Linux.

Discussing with @justincormack at Docker Summit.

If we include the alsa snd-aloop driver it should be possible to use this for network audio access.

**Comment by justincormack** [comment]
Roughly along lines of http://ywwg.com/wordpress/?p=1201

Need to enable audio in Linux VM.

**Comment by justincormack** [comment]
I am doing some experiments. Forgotten how frustrating Linux audio is. Anyway I have some silence working...

**Comment by yeta-io** [comment]
Upvote!
