### ISSUE TITLE
Docker not starting with Library/Containers/com.docker.docker/Data being a symlink

### ISSUE THREAD

**Issue by wiebe-ruiter** [docker/for-mac#771]
### Expected behavior

Put the Data directory on a USB hard drive.
do 'ln -s /Volumes/<drivename>/<path>/Data /Users/<username>/Library/Containers/com.docker.docker/Data' 

Start the Docker application. Docker starts and finds the images stored on the external drive.
Docker should follow symlinks, even on a USB drive.

### Actual behavior

Start the Docker application. Docker crashes.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
`
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/607E474A-9874-4F16-91EC-9010BA121CE8/20161008-141917.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/wiebe/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/wiebe/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/wiebe/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/wiebe/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/wiebe/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/wiebe/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
`

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Hi, thanks for the report. We are currently improving the management of the hypervisor storage (the qcow2 file) by allowing it to be defined in an alternate  location. Will it help your use-case or do you really need to move all the files in that directory?

**Comment by wiebe-ruiter** [comment]
Moving the qcow2 file is perferctly fine; I discovered this workaround
after logging the issue and it solved my problem.

**Comment by samoht** [comment]
I am glad that you found a workaround. I am closing this issue now as you found a workaround that meanwhile we are working on a more integrated solution (ie. allow to set the qcow2 location by using the UI).
