### ISSUE TITLE
crash at 1st run

### ISSUE THREAD

**Issue by Diluka** [docker/for-mac#772]
### Information

Diagnostic ID: DD18080C-77CE-4235-A276-14C957B3F8F4
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/Diluka/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/DD18080C-77CE-4235-A276-14C957B3F8F4/20161009-103154/qemu-img-check.stdout 2> /tmp/DD18080C-77CE-4235-A276-14C957B3F8F4/20161009-103154/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/Diluka/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Diluka/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/Diluka/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/Diluka/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/Diluka/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. run
2. and crash

**Comment by samoht** [comment]
Docker for Mac 1.12.0 is not supported on macOS 10.12. Please upgrade to either 1.12.1 (stable channel) or to 1.12.2-rc1-Beta27.

Thanks.
