### ISSUE TITLE
Crash on sierra

### ISSUE THREAD

**Issue by giovannicandido** [docker/for-mac#774]
### Expected behavior
Docker for mac starts
### Actual behavior
Crash
### Information

Maybe because I upgrade to Macosx Sierra, I'm not sure because of lack of timing in the assumption.

Reset to factory settings not work. I will try the beta, if works I will close the issue or create a comment

Diagnose:

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/869D30FB-1766-4F4E-95ED-6C2B63267BE1/20161009-221207.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/giovanni/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by giovannicandido** [comment]
Same error on Version 1.12.2-rc1-beta27

**Comment by BrendanThompson** [comment]
Getting similar error, except mine just won't start!

**Comment by samoht** [comment]
@giovannicandido could you please try to upload a new diagnostic report, as the first one that you tried to send didn't go through (`Could not upload diagnostic data to remote server`) ? We are testing Sierra internally (and we are using it everyday) so this should normally not be a problem on Beta27 or 1.12.1 stable.

**Comment by samoht** [comment]
@giovannicandido it seems that you don't have the right system requirements:

```
> Oct  9 10:56:08 Giovannis-iMac Docker[com.docker.driver.amd64-linux][536] <Notice>: vmx_init: processor not supported by Hypervisor.framework
```

See the section **System Requirements** in https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install

**Comment by giovannicandido** [comment]
Ok problem solved. Intel Virtualization was disabled for some reason.

Thanks for the help.
