### ISSUE TITLE
Fatal Error: vmstateevent invalid json: 

### ISSUE THREAD

**Issue by phamdohung161** [docker/for-mac#775]
### Information

Diagnostic ID: 0E3B2A16-E647-4C6A-AD07-4CAABF03E8DB
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Please upgrade to 1.12.1 which fixes macOS Sierra support. This issue was #64 but has been resolved in recent releases.
