### ISSUE TITLE
Preferences window not opening

### ISSUE THREAD

**Issue by vyscond** [docker/for-mac#776]
### Expected behavior

Preferences window be opened 

### Actual behavior

Preferences is not opening

### Information

```
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/65A407C1-EAC4-47AD-9550-E5DF7DC8E8E5/20161010-154510.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

  1. Upgrade Docker to `1.12.2-rc1-beta27`
  2. Open Docker app
  3. Click on Preferences menu entry

Besides of this one particular bug. Everything is fine in relation to run the containers.

**Comment by dsheets** [comment]
I couldn't find your diagnostic information. Could you please run :whale: :arrow_right: `Diagnose & Feedback...` ➡️ `Diagnose & Upload`?

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
