### ISSUE TITLE
Fatal Error: Communication with networking components failed

### ISSUE THREAD

**Issue by melostbr** [docker/for-mac#777]
### Expected behavior
Install networking components after first installation and priviledge access granted.
### Actual behavior
Gives a "fatal error" message.
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/CDDE3FB0-A591-4896-8D5B-B78B7F5FC723/20161010-165540.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/stmelo/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/stmelo/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/stmelo/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/stmelo/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/stmelo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Download Docker from https://www.docker.com/products/docker#/mac
  2. Drag and Drop under Applications folder
  3. Click to open
  4. Grant access to application
  5. Receives a "Fatal Error: Communication with networking components failed" message

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in CDDE3FB0-A591-4896-8D5B-B78B7F5FC723/20161010-165540.

The UI failed to communicate with the networking helper process.

May be related to docker/for-mac#61

The following log matches:
```
Oct 10 09:21:05 infras-iMac Docker[com.docker.docker][597] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 10 09:21:06 infras-iMac Docker[com.docker.docker][597] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 10 09:21:07 infras-iMac Docker[com.docker.docker][597] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 10 09:21:08 infras-iMac Docker[com.docker.docker][597] <Critical>: Communication with networking components failed.
Oct 10 09:32:43 infras-iMac Docker[com.docker.docker][597] <Warning>: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
Oct 10 09:33:10 infras-iMac Docker[com.docker.docker][597] <Error>: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
Oct 10 09:37:13 infras-iMac Docker[com.docker.docker][597] <Notice>: applicationWillTerminate
Oct 10 09:38:40 infras-iMac Docker[com.docker.helper][381] <Notice>: launching...
Oct 10 09:38:40 infras-iMac Docker[com.docker.helper][381] <Notice>: accessing preferences...
```

**Comment by samoht** [comment]
The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

**Comment by karanjthakkar** [comment]
@samoht Facing the same issue. Diagnostic ID: 2B4A03EE-C62F-4414-A566-82B94A3959AE Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` does not resolve this.

**Comment by melostbr** [comment]
@samoht, the file doesn't exist in my computer. I tried downloading and installing it again, but the problem persists. Here is the output of the diagnose I've just received:

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/CDDE3FB0-A591-4896-8D5B-B78B7F5FC723/20161026-173925.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         wrong Docker version: 1.12.0 (expected 1.12.1)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/stmelo/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/stmelo/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/stmelo/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/stmelo/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/stmelo/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/stmelo/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/stmelo/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by axsauze** [comment]
Faced the same issue and it worked

**Comment by dershow** [comment]
@axsauze can you explain what worked?  I'm having the same issue.  I tried deleting com.docker.vmnetd and it didn't resolve.  I also tried to the solution mentioned in "Installation issue" mentioned above, also without any luck.
Any other suggestions?

**Comment by FabianKoestring** [comment]
> The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

Helped for me! 👍
