### ISSUE TITLE
error

### ISSUE THREAD

**Issue by unecoc** [docker/for-mac#778]
### Information

Diagnostic ID: 16A62781-DF6D-4495-9DBA-9F61187036D3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

Error is displayed when I open a docker from Mac applications.

**Comment by samoht** [comment]
1.12.0-a does not support Sierra. You should update to either the latest stable (1.12.1) or to latest Beta (1.12.2-rc1-beta27).

**Comment by unecoc** [comment]
thank you :)
