### ISSUE TITLE
Exit on starting Docker App on MacOS

### ISSUE THREAD

**Issue by navneetkarnani** [docker/for-mac#779]
### Expected behavior
Docker app on MacOS should start
### Actual behavior
Docker app crashes with error message 

### Information

Diagnostic ID: E9905500-C997-43A3-AAF8-E1468377844D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A322)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
1.12.0-a does not support Sierra. You should update to either the latest stable (1.12.1) or to latest Beta (1.12.2-rc1-beta27).
