### ISSUE TITLE
Virtual box with not work

### ISSUE THREAD

**Issue by altunbas-huseyin** [docker/for-mac#78]
### Information

Diagnostic ID: A14EB0D1-4E64-449B-9167-E3160B5ED372
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F1909)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/huseyin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/A14EB0D1-4E64-449B-9167-E3160B5ED372/20160802-213551/qemu-img-check.stdout 2> /tmp/A14EB0D1-4E64-449B-9167-E3160B5ED372/20160802-213551/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/huseyin/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/huseyin/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/huseyin/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/huseyin/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/huseyin/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
The logs have:
```
Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
        VirtualBox v4.3.28 is currently installed.
        Please upgrade or uninstall Virtualbox.
```

If you are a Virtualbox user, please upgrade to Virtualbox v5. Unfortunately Virtualbox v4 is incompatible with the MacOS hypervisor.framework. New versions of Virtualbox are available from [www.virtualbox.org](https://www.virtualbox.org/wiki/Downloads).
