### ISSUE TITLE
com.docker.hyperkit takes up way too much memory

### ISSUE THREAD

**Issue by madskonradsen** [docker/for-mac#781]
### Expected behavior

`com.docker.hyperkit` to only take up the needed memory

### Actual behavior

`com.docker.hyperkit` takes up 3GB

### Information

When building my image from my Dockerfile(see below) and run the container it makes hyperkit use an insane amount of memory which is okay when building images, but it seems like that memory isn't released afterwards which makes it stay at around the 3GB. I tried killing Docker(and com.docker.hyperkit) and running the already builded image which resulted in `com.docker.hyperkit` taking up only 285MB(which matches my expectations).

Diagnostics ID:
`EFD03EF1-0569-4EFA-B66A-AEED124E760E`

Dockerfile:

```
FROM madskonradsen/centos-supervisor

RUN rpm --rebuilddb
RUN yum clean all
RUN yum update -y
RUN yum clean all

# FIX for following issue: “chfn: PAM: System Error” - https://github.com/docker/docker/issues/6345 
RUN ln -s -f /bin/true /usr/bin/chfn

# Set encoding
ENV LANG=en_US.utf8

# Make sure that the TERM env-variable are available in order to do commands like 'top' etc.
ENV TERM dumb

# set timezone
RUN rm -f /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime

ADD ./scripts/install.sh /bin/install.sh
RUN sh install.sh
```

### Steps to reproduce the behavior

  1. Build-image
  2. Run container
  3. Observe memory consumption

**Comment by ijc25** [comment]
This seems similar to https://github.com/docker/for-mac/issues/178. Please see https://github.com/docker/for-mac/issues/178#issuecomment-238509543 for an explanation of the issues. I'm going to close this issue for the same reasons described in #178 but if you are observing that the `rss` (_not_ the `vsz`) of the hyperkit process is remaining high when there are no containers but there are other sources of memory pressure (i.e. other osx applications) in the system indicating that hyperkit owned is memory is not being swapped out then please ping us here with details so we can investigate further.

Thanks for your report,
Ian.

**Comment by madskonradsen** [comment]
That's a shame. I have 2GB allocated for Docker(in the preferences pane) and my 200MB process in the container starts serving me OOM errors(probably because of the space that have been allocated by the kernel). So I guess there is no way to circumvent that?

Are there any plans for fixing the issue in the future? Like injecting something into the guest in order to keep tab on the usage(as you probably can hear, I don't know a lot about VM's)

**Comment by ijc25** [comment]
@madskonradsen If you have a 200MB process in a container (as viewed from within the container VM, not from OSX) and 2GB allocated to docker (which will be what OSX is seeing) and are getting OOMs then you have 1.8GB unaccounted for somewhere, the overheads for the kernel are nothing like that much. (this strikes me as an orthogonal issue to the original report which I understood to be regarding the amount of RAM used by the hyperkit process as seen by OSX).

Perhaps there is a typo and you meant a 2000MB process? In which case you are pushing up against the size of the VM and I would indeed expect OOM to sometimes kick in. If that's the case then I would suggest increasing the maximum amount of RAM docker can use (remembering that it can be swapped when Docker is idle) or reducing the RAM required for your container, if such a thing is possible.

**Comment by madskonradsen** [comment]
I have a 200MB(not GB) process in a container(determined using `top` in the container). Yes, now that you mention it, the two issues might not be directly related(they was in my head). And in OSX I see com.docker.hyperkit using the maximum(the 2 GB that i lowered it to), and I get OOMs inside my container.

**Comment by ijc25** [comment]
The oom spew in your logs seems to suggest you have multiple java processes consuming 3-4GB each running (as well as various other sundry processes which I didn't tot up).

I counted 12 java processes in the list, but it's possible some of them were threads of the same process (not 100% how the oom killer presents thing). Based on the sizes I'm pretty sure 9 of them were distinct though.

The particular process which was killed by the oom killer in the example I looked at was:
```
Oct  7 11:01:13 moby kernel: Out of memory: Kill process 22611 (java) score 215 or sacrifice child
Oct  7 11:01:13 moby kernel: Killed process 22611 (java) total-vm:4812600kB, anon-rss:721048kB, file-rss:0kB
```
So was taking 4812600kB or approx 4.5G.

Your logs also suggest your Docker is configured for ~10GB not ~2GB:
```
Memory: 11189316K/11533944K available (6919K kernel code, 1473K rwdata, 2860K rodata, 1096K init, 1592K bss, 344628K reserved, 0K cma-reserved)
```

But given the number of large Java processes you appear to have running in containers I think you could easily have exhausted that too.

**Comment by rsn8887** [comment]
I just experienced the same problem. com.docker.hyperkit is using 2 GB without any containers running. I just installed docker and the first thing I see is 2 GB memory consumption with nothing even running. No thanks. Will de-install now until this is fixed.

**Comment by devmetal** [comment]
@rsn8887 Same here, the com.docker.hyperkit use 8gb ram, only workaround to restart docker time to time. :(

**Comment by theronl** [comment]
Restarted docker. No containers are running.  The activity monitor is saying there is 1.66 GB of memory in use.   Before restart the activity monitor showed `com.docker.hyperkit` was using 5+ GB of memory with no containers running.

**Comment by antonlisovenko** [comment]
wow, left laptop switched on over night, 16 Gb in use by the morning, laptop completely stuck, had to kill the process and then all build images processes had to download the images from the Internet again (does Docker keep images in memory only??)

**Comment by rmahnovetsky** [comment]
I just restarted docker, 1.4GB in use. How can I reduce the memory?
![image](https://user-images.githubusercontent.com/53893/43193728-1fd3fa62-9044-11e8-8ac2-58330c370623.png)

**Comment by kalexmills** [comment]
After having the com.docker.hyperkit process running for 22 minutes, it is using 11GB+ of RAM as reported by top. I am running a kubernetes cluster with several processes inside it, but I've explicitly told Docker only to use at most 8GB of RAM, so I am wondering why top is reporting 11GB+....

I am running mac. Here is a diagnostic ID, which I presume will tell devs all they need to know(?) 3CBF0FFC-A3ED-4F24-944A-650842923449/20181010135026

Something indeed seems to be very, very wrong.

**Comment by nikoskip** [comment]
I have the same issue. Docker is consuming about 3GB of RAM without any running container!

![image](https://user-images.githubusercontent.com/1230033/50403383-e02e9880-077c-11e9-9b95-f7b1651f2698.png)

Diagonistc ID: 74D00548-8F64-4DA9-9A35-47BDC6B76A72/20181224160631

**Comment by rosiecakes** [comment]
![image](https://user-images.githubusercontent.com/5151675/50516532-4bc47e80-0a79-11e9-8dd6-0e354d6a5d77.png)

Similar high memory use without anything running, diagnostic ID 0536FAAA-824B-41FC-9D26-E34C2FD681B0/20181228131703

**Comment by jacksbox** [comment]
I'm having a similar issue as you @kalexmills, the settings allow docker to use 8gb of RAM but instead it's using 14.3 GB... my laptop is getting kind a slow 😢 
Any way to prevent this?

**Comment by jacksbox** [comment]
some additional info:
macOS 10.14.02
Docker Version 2.0.0.0-mac81 (29211)

**Comment by jouniso** [comment]
Same happening here. In Docker preferences memory set to 2GB but uses almost 4GB.

**Comment by merty** [comment]
Same here, it takes about 3.09 GB of RAM when no containers are running.

Docker Desktop Version 2.0.0.2 (30215)
macOS 10.14.2

**Comment by jacksbox** [comment]
Small update from me, no containers running, memory consumption: 8.52gb
macOS 10.14.02
Docker Version 2.0.0.0-mac81 (29211)

**Comment by i-hardy** [comment]
Just spotted com.docker.hyperkit using 5.57GB of memory when I was doing nothing with Docker (and hadn't since I booted up my laptop this morning). Docker for Mac CE Version 2.0.0.3, macOS 10.14.2.

**Comment by ctcampbell** [comment]
Same issue. Docker set to use 6GB memory, seeing 7.9GB used in Activity Monitor.

`docker stats --no-stream
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
0356077c7371        jira                0.88%               1.233GiB / 5.818GiB   21.20%              260kB / 157kB       470MB / 32.8kB      115
007e1e56a9cb        jenkins             0.14%               781.2MiB / 5.818GiB   13.11%              2.24MB / 42.7kB     53.5MB / 9.8MB      43
8bbbb4e68433        gitlab-runner-1     0.00%               5.895MiB / 5.818GiB   0.10%               13kB / 32.4kB       12.9MB / 0B         10
d3e28f95c0ba        gitlab-ce           4.16%               1.764GiB / 5.818GiB   30.32%              66.5kB / 22.9kB     260MB / 946kB       319
68137d1b6a42        gitlab-runner-2     0.00%               5.887MiB / 5.818GiB   0.10%               13kB / 32.4kB       17.3MB / 0B         10`

<img width="912" alt="screenshot 2019-02-22 at 08 34 03" src="https://user-images.githubusercontent.com/808531/53229650-c1fdef80-367c-11e9-83fb-6151ae07eb1c.png">
<img width="696" alt="screenshot 2019-02-22 at 08 35 19" src="https://user-images.githubusercontent.com/808531/53229669-ccb88480-367c-11e9-8efd-085a4ceb0256.png">

**Comment by rsn8887** [comment]
This issue should never have been closed in my opinion. By closing and creating new issues related to this it is deceiving/hiding the fact that this issue has been around unfixed for 3 years now.
