### ISSUE TITLE
Docker App on OSX Yosemite 10.10.5

### ISSUE THREAD

**Issue by sleyb** [docker/for-mac#782]
### Expected behavior
Start the Docker App on OSX
### Actual behavior
Failure and diagnostic menu
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnostic ID: 306AF89A-76AA-421C-AA92-AA9A78629B95
Output of Diagnostics:

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1912)
logs: /tmp/306AF89A-76AA-421C-AA92-AA9A78629B95/20161011-093556.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/sleyb/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/sleyb/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/sleyb/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/sleyb/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/sleyb/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Open Docker on my Mac
  2. Fail, send you guys statistics
  3. Virtualbox may have been installed years ago, definitely removed it.

**Comment by samoht** [comment]
Detected symptom of problem 'uninstall-virtualbox' in 306AF89A-76AA-421C-AA92-AA9A78629B95/20161011-093556.

Some parts of Virtualbox may still be installed. Please follow https://www.virtualbox.org/manual/ch02.html#idm871 to completely uninstall Virtualbox. Please note that dragging the application to the trash is not enough:there are kernel modules installed as well.

May be related to docker/for-mac#78

The following log matches:
```
Oct 10 23:35:13 zmac.local Docker[com.docker.docker][5494] <Notice>: Application version: 1.12.1 (12133)
Oct 10 23:35:13 zmac.local Docker[com.docker.docker][5494] <Notice>: Administrator user: true
Oct 10 23:35:13 zmac.local Docker[com.docker.docker][5494] <Notice>: OSX Version: Version 10.10.5 (Build 14F1912)
Oct 10 23:35:14 zmac.local Docker[com.docker.docker][5494] <Critical>: Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
	VirtualBox v4.3.12 is currently installed.
	Please upgrade or uninstall Virtualbox.
Oct 10 23:35:25 zmac.local Docker[com.docker.docker][5494] <Notice>: applicationWillTerminate
Oct 10 23:35:38 zmac.local Docker[com.docker.docker][5530] <Notice>: Application version: 1.12.1 (12133)
Oct 10 23:35:38 zmac.local Docker[com.docker.docker][5530] <Notice>: Administrator user: true
Oct 10 23:35:38 zmac.local Docker[com.docker.docker][5530] <Notice>: OSX Version: Version 10.10.5 (Build 14F1912)
Oct 10 23:35:38 zmac.local Docker[com.docker.docker][5530] <Critical>: Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
```
