### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Mac.

### ISSUE THREAD

**Issue by zacharysverdrup** [docker/for-mac#783]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Please re-open an issue with the full diagnostic information. Thanks!
