### ISSUE TITLE
docker Command line doesn't work on MacOS Sierra

### ISSUE THREAD

**Issue by dunkenbutterfly** [docker/for-mac#785]
### Expected behavior
docker info returns info
### Actual behavior
bash: docker: command not found
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.12 (build: 16A323)
logs: /tmp/F637D9FB-3F4F-46B5-B1E5-FEACF0C16CE0/20161011-232145.tar.gz
[20161011-232145.tar.gz](https://github.com/docker/for-mac/files/522984/20161011-232145.tar.gz)

failure: cannot find docker
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. docker info
  2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in F637D9FB-3F4F-46B5-B1E5-FEACF0C16CE0/20161011-232145.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to

The following log matches:
```
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.vmnetd][6727] <Notice>: Client supplied container path /Users/ovanni/Library/Containers/com.docker.docker/Data
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.vmnetd][6727] <Critical>: File /var/run/docker.sock is a symlink or a socket
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.vmnetd][6727] <Notice>: Symlinking /var/run/docker.sock to /Users/ovanni/Library/Containers/com.docker.docker/Data/s60
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.docker][6704] <Error>: Symlinks are not correctly installed.
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.docker][6704] <Notice>: NSUserDefaults.synchronise() returned false
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.docker][6704] <Notice>: com.docker.osx.hyperkit.linux launched with PID 6730
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.osx.hyperkit.linux][6730] <Notice>: Acquired task manager lock
Oct 11 21:58:12 MacBook-Pro-di-ovanni Docker[com.docker.osx.hyperkit.linux][6730] <Notice>: Maximum number of file descriptors is 10240
```

**Comment by dunkenbutterfly** [comment]
thanks but you mean: ln -s ~**/Library/Group/Containers/group.com.docker/bin/docker** /usr/local/bin/docker 
there is no dir group.com.docker inside /Library/Group/Containers/

thanks
