### ISSUE TITLE
macOS-10.12 (16A323) install error

### ISSUE THREAD

**Issue by weisong82** [docker/for-mac#786]
### Information

Diagnostic ID: B79C0FED-EB3A-4817-A77B-7979B8FF4631
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/wei/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/B79C0FED-EB3A-4817-A77B-7979B8FF4631/20161012-102050/qemu-img-check.stdout 2> /tmp/B79C0FED-EB3A-4817-A77B-7979B8FF4631/20161012-102050/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/wei/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/wei/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/wei/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/wei/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/wei/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'unsupported-sierra' in B79C0FED-EB3A-4817-A77B-7979B8FF4631/20161012-102120.

Sierra is supported on latest stable and beta releases only. Please upgrade.

May be related to docker/for-mac#561

The following log matches:
```Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: Application version: 1.12.0 (10871)
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: Administrator user: true
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: OSX Version: Version 10.12 (Build 16A323)
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: migrator: start migration process
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: migrator: no previous version detected. Performing all migrations for now...
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: migrator: 0 migrations to perform
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Notice>: migrator: end of migration process
Oct 12 10:19:46 bogon Docker[com.docker.docker][998] <Error>: event tracker initialization failed
```
