### ISSUE TITLE
docker-diagnose exit code is 1 

### ISSUE THREAD

**Issue by pattama** [docker/for-mac#789]
### Actual behavior
docker-diagnose exit code is 1 

### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/20087DE5-2CD2-4A3F-A84E-014F0B366972/20161012-171439.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/pattama/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/pattama/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/pattama/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in 20087DE5-2CD2-4A3F-A84E-014F0B366972/20161012-171439.

The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

May be related to docker/for-mac#61

The following log matches:
```
Oct 12 16:17:43 pattama-osx Docker[com.docker.docker][66639] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 12 16:17:44 pattama-osx Docker[com.docker.docker][66639] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 12 16:17:45 pattama-osx Docker[com.docker.docker][66639] <Notice>: com.docker.vmnetd failed to connect to /var/tmp/com.docker.vmnetd.socket, sleeping 1s
Oct 12 16:17:46 pattama-osx Docker[com.docker.docker][66639] <Critical>: Communication with networking components failed.
Oct 12 16:17:59 pattama-osx Docker[com.docker.docker][66639] <Notice>: applicationWillTerminate
Oct 12 16:18:08 pattama-osx kernel[kern][0] <Notice>: hfs: unmount initiated on Docker on device disk3s1
Oct 12 16:18:08 pattama-osx deleted[daemon][39816] <Error>: normalizeUserMountpoint:791 volRoot failed for /Volumes/Docker
Oct 12 16:18:08 pattama-osx deleted[daemon][39816] <Error>: _validateVolume:813 unable to normalize volume: "/Volumes/Docker", vol: (null)
Oct 12 16:35:05 pattama-osx Docker[com.docker.helper][473] <Notice>: launching...
```
