### ISSUE TITLE
Docker is stopping frequently with an error

### ISSUE THREAD

**Issue by goutamtadi1** [docker/for-mac#79]
```
Error response from daemon: dial unix /Users/XXXX/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

### Information

Diagnostic ID: B7EEF3B6-477E-4A35-9B49-AEB5CB7F752C
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F1605)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by mbmccoy** [comment]
I'm seeing this one too. Same `docker ps failed` message. Running the default `postgres` container and a webapp linked together using `docker-compose` when this occurs. 

My message:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/XXXX/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```
Same thing occurs in Thread-2.


My diagnostics:
```
Diagnostic ID: 553C1A2D-9C9B-4E74-BB65-ECFA19457567
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.10.5 (Build 14F27)
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by djs55** [comment]
This looks very similar to #60 

Unfortunately the diagnostic uploads from the stable branch are missing some key pieces of information which are needed to figure out why docker ps doesn't work (specifically: process lists and output from docker ps running inside the VM rather than only the host). Could you try to reproduce with a beta version and open a fresh issue?
