### ISSUE TITLE
Docker not starting up when I rebooted, unable to do docker ps

### ISSUE THREAD

**Issue by dansweeting** [docker/for-mac#790]
### Expected behavior

docker ps to list my containers
docker animation to have stopped moving, signalling that everything has started.
docker to behave after I give it a manual restart (clicking the restart button)

### Actual behavior

docker ps gives me:
'Error response from daemon: Bad response from Docker engine'
Restart button restarts docker, but I get the same result

### Information

I saw this behaviour, tried restarting docker a few times then rebooted my machine, but still get the same problem.

Diagnostic ID: 68C8C864-81C4-4A9B-8599-92CDC939D32D
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.1 (Build 15B42)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Could you please use the `Diagnostic & Upload` option in the `Diagnostic & Feedback` menubar item, so that your logs are sent to our diagnostic servers? Thanks!

**Comment by dansweeting** [comment]
Apologies, 

I got this screen and reading the bottom righthand message, assumed it had uploaded all the info needed. 

<img width="723" alt="screen shot 2016-10-12 at 15 38 36" src="https://cloud.githubusercontent.com/assets/375509/19314442/05700052-9092-11e6-8f2a-6ae2fc0df5dc.png">

I don't seem to have a Diagnostic & Upload option.

**Comment by dansweeting** [comment]
Upgraded to latest version, still fails:

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.1 (build: 15B42)
logs: /tmp/68C8C864-81C4-4A9B-8599-92CDC939D32D/20161012-160856.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)


68C8C864-81C4-4A9B-8599-92CDC939D32D

**Comment by samoht** [comment]
Unfortunately it seems that it is an AUFS corruption issue:

```
time="2016-10-12T11:25:59.810578817Z" level=debug msg="Failed to load layer sha256:b19b6709414827cfa71573632815e02de58b621c1681e2595377bbf75a0ff0f5: failed to get diff id for sha256:b19b6709414827cfa71573632815e02de58b621c1681e2595377bbf75a0ff0f5: invalid checksum digest format"
```

**Comment by dansweeting** [comment]
So... similar to this?  
https://github.com/docker/for-mac/issues/52
