### ISSUE TITLE
Incomplete installation

### ISSUE THREAD

**Issue by brooksph** [docker/for-mac#791]
Expected behavior

docker info: info

Actual Behavior

Error response from daemon: Bad response from Docker engine

$docker info 
Error response from daemon: Bad response from Docker engine

Information

Diagnostic ID: 007B7251-3C71-47E2-827A-D4C2C19879C0

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/007B7251-3C71-47E2-827A-D4C2C19879C0/20161011-142526.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR] docker-cli
docker ps failed
[OK] virtualization kern.hv_support
[OK] menubar
[OK] moby-syslog
[OK] dns
[OK] disk
[OK] system
[OK] app
[OK] osxfs
[OK] virtualization VT-X
[OK] db
[OK] slirp
[OK] logs
[OK] env
[OK] vmnetd
[OK] moby-console
[OK] moby
[OK] driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Restored to factory settings and reinstall did not help

**Comment by samoht** [comment]
May be related to docker/vpnkit#131 /cc @djs55 

The following log matches:
```
Oct 11 12:10:04 MacBook Docker[com.docker.docker][2385] <Warning>: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
Oct 11 12:10:07 MacBook Docker[com.docker.vmnetd][2446] <Notice>: EOF reading packet from Unix domain socket: closing
Oct 11 12:10:07 MacBook Docker[com.docker.slirp][2402] <Error>: failed to establish 9P connection: Caught EOF on underlying FLOW
Oct 11 12:10:07 MacBook Docker[com.docker.vmnetd][2446] <Critical>: Failed to read hello from client
Oct 11 12:10:09 MacBook Docker[com.docker.slirp][2402] <Error>: Lwt.async failure (Failure nth): Raised at file "pervasives.ml", line 32, characters 22-33
	Called from file "lib/dns_forward.ml", line 38, characters 41-77
	Called from file "lib/dns_forward.ml", line 102, characters 16-57
	Called from file "src/core/lwt.ml", line 795, characters 20-24
Oct 11 12:10:15 MacBook Docker[com.docker.slirp][2402] <Error>: Lwt.async failure (Failure nth): Raised at file "pervasives.ml", line 32, characters 22-33
	Called from file "lib/dns_forward.ml", line 38, characters 41-77
	Called from file "lib/dns_forward.ml", line 102, characters 16-57
```

**Comment by ijc25** [comment]
This is #578, a fix is already available in beta30. Please subscribe to #578 for further updates regarding the fix propagating to stable.
