### ISSUE TITLE
DNS Option Missing

### ISSUE THREAD

**Issue by bskrtich** [docker/for-mac#794]
### Expected behavior
To set the dns server for every container

### Actual behavior
Unable to do so

### Information
I need some way to set the dns server for all my containers by default. I have tried DOCKER_OPTS in /etc/default/docker and modifying ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker/daemon.json and nether seems to work.

Please let me know if there is another way to do this or if I just have to wait for this option to be added to the ui.

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)

**Comment by samoht** [comment]
It should normally be using the same DNS configuration as the one of the host. If it doesn't work, please submit a way to reproduce it and/or a diagnostic tarball.

Or do you really have different settings for your host and containers? In that case, we don't support that feature but we would be interesting to hear about your use-case!

**Comment by bskrtich** [comment]
I have using dnsmasq for local development. This allows me to run a reverse proxy to shunt traffic automatically to each container based on its name. The only problem is that I need to supply the dns server to each container. I was doing this via `DOCKER_OPTS="--dns 10.254.254.1"` but that doesnt seem to be working any more.

**Comment by samoht** [comment]
How did you update your `daemon.json`? Can you try the following:

```
cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/
git reset master --hard
[ edit /etc/docker/daemon.json to add your option ]
git commit -a -m commit test
```

After a few seconds, Docker.app should be restarting and then you can to connect again. Let me know if it works better or if is a regression on our side.

**Comment by bskrtich** [comment]
The com.docker.drive.. folder didn't exist so I had to change the commands you gave me a bit.
So here is the list of commands I used to test just now. 

```
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset master --hard
echo '{"dns":["10.254.254.1"]}' > com.docker.driver.amd64-linux/etc/docker/daemon.json
git checkout -b test
git commit -a -m "test dns"
```

I then manually restarted the docker service via the app and tried it. It did not work.

Let me know if there is something wrong with the json I am using and I can try again.

And thank you for your help!

**Comment by justincormack** [comment]
You need to commit in the master branch.

**Comment by bskrtich** [comment]
Yea! That worked! Thank you! Here is my revised set of commands for who ever reads this in the future

```
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset master --hard
echo '{"dns":["10.254.254.1"]}' > com.docker.driver.amd64-linux/etc/docker/daemon.json
git commit -a -m "set dns"
```

**Comment by bskrtich** [comment]
FYI: For anyone finding this page when searching, the placement of the daemon.json has changed since the release of Docker 17.09.0-ce-mac32 2017-10-02 (see [here](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17090-ce-mac32-2017-10-02) )

The updated command that I have is this (this does require jq and moreutils for spong installed from homebrew)
```
jq '. + {"dns":["10.254.254.1"]}' ~/.docker/daemon.json | sponge ~/.docker/daemon.json
```
