### ISSUE TITLE
I have problem with docker run on macOS

### ISSUE THREAD

**Issue by mrnqbao** [docker/for-mac#795]
### Information

Diagnostic ID: 70E98A16-5536-47F7-9BCD-945CA46813FF
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by samoht** [comment]
Can you describe which problem do you have? What error message do you see? Do you have a way to reproduce it?

**Comment by samoht** [comment]
Detected symptom of problem 'unsupported-sierra' in 70E98A16-5536-47F7-9BCD-945CA46813FF/20161013-133246.

Sierra is supported from the version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the stable channel. Please upgrade.

May be related to docker/for-mac#561

**Comment by mrnqbao** [comment]
Thanks you very much, It’s seem working.
