### ISSUE TITLE
"Docker has been update!" dialogue after every restart

### ISSUE THREAD

**Issue by azizur** [docker/for-mac#797]
### Expected behavior
"Docker has been update!" dialogue shown once after install/update

### Actual behavior
"Docker has been update!" dialogue shown after every restart of OS
<img width="331" alt="screen shot 2016-10-10 at 10 06 19" src="https://cloud.githubusercontent.com/assets/114551/19344017/76da0910-9130-11e6-9787-457e547537b5.png">

### Information
```
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G31)
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

### Steps to reproduce the behavior

1. Install 
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G31)

2. Restart the mac.
3. "Docker has been update!" dialogue shown
4. restart you mac
5. "Docker has been update!" dialogue shown again on every restart

**Comment by samoht** [comment]
Thanks for your report. This should be fixed in Beta28 that we are about to release. Please re-open that ticket if you still have the issue with that new version.
