### ISSUE TITLE
Faied to connect to the Docker daemon ( Mac OS ) 

### ISSUE THREAD

**Issue by vikramvi** [docker/for-mac#799]
**Description**

Jenkins user on Mac mini can't run docker command
1.1. Inside Jenkins build; Execute shell command says "docker command not found"
1.2 Shifting to Jenkins user on shell prompt and trying to run docker command gives error
   "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

**Steps to reproduce the issue:**
1.  Mac mini Jenkins and Docker installed ( through mac installer )
2. Verified both working fine independently ( with Mac mini admin user )
3. Jenkins user can't run docker commands

**Describe the results you received:**

sudo -s -u jenkins
Password:
bash-3.2$ whoami
jenkins
bash-3.2$ docker ps -a
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
bash-3.2$ 

**Describe the results you expected:**

currently installed docker containers

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: YEGE:PR2R:SKGB:MIKZ:NVU4:ILOC:B2OE:WCQT:A4JL:57QB:C46C:Q7Q5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-10-13T14:36:08.079296494Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Mac mini physical box in office network**

**Comment by samoht** [comment]
Hi, thanks for your report. Would you be able to send us a diagnostic report so that we could investigate the issue? You can either do that through the UI (in the "Diagnostic and Feedback" menubar item) or run that command in a terminal:

```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -y -u
```

Thanks!

**Comment by vikramvi** [comment]
@samoht  Please find below updates

/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -y -u
diagnose: unknown option `-y'.
Usage: diagnose [OPTION]... 
Try `diagnose --help' for more information.

I tried with UI and below is the result


Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1909)
logs: /tmp/BD6F5CAF-E36D-4AA6-B8A6-4B6034AD018D/20161013-173148.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

**Comment by vikramvi** [comment]
/usr/local/bin

lrwxr-xr-x   1 buildserver  staff        71 Oct 12 18:50 docker -> /Users/buildserver/Library/Group Containers/group.com.docker/bin/docker
lrwxr-xr-x   1 buildserver  staff        79 Oct 12 18:50 docker-compose -> /Users/buildserver/Library/Group Containers/group.com.docker/bin/docker-compose
lrwxr-xr-x   1 buildserver  staff        79 Oct 12 18:50 docker-machine -> /Users/buildserver/Library/Group Containers/group.com.docker/bin/docker-machine

**Comment by samoht** [comment]
Sorry, can you try again with the `-y`? Or select `Diagnostic & Update` instead of just `Diagnostic` so that a diagnostic tarball is sent to our remote servers.

**Comment by vikramvi** [comment]
BD6F5CAF-E36D-4AA6-B8A6-4B6034AD018D  ( This is I got from UI ).  Please let me know if this is good enough ?

sorry can you please put complete command again. I didn't get which is correct format.

**Comment by vikramvi** [comment]
got it 

/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u

Your unique id is: BD6F5CAF-E36D-4AA6-B8A6-4B6034AD018D

**Comment by vikramvi** [comment]
I found matching problem here https://forums.docker.com/t/how-to-use-docker-command-in-jenkins-shell/16307/6 but no answer for resolution ( just fyi..)

**Comment by samoht** [comment]
Thanks, I have your logs now.

As @justincormack this is probably a permission issue. Is the `jenkins` user able to run `/Users/buildserver/Library/Group Containers/group.com.docker/bin/docker ps`?

**Comment by vikramvi** [comment]
@samoht  please find below

bash-3.2$ whoami
jenkins
bash-3.2$ /Users/buildserver/Library/Group\ Containers/group.com.docker/bin/docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
bash-3.2$

**Comment by samoht** [comment]
Can you try to change the owner and/or permissions of all the files in `/Users/buildserver/Library/Containers/com.docker.docker/Data/` to git read/write permissions to the `jenkin` user?

**Comment by vikramvi** [comment]
@samoht  I have changed permission for group and now it looks as below
drwxrwx---   47 buildserver  staff  1598 Sep 21 13:28 Containers

jenkins user is part of staff group. buildserver is admin user on mac mini

After this restarted docker and jenkins as well.

But still I'm seeing same issue

bash-3.2$ whoami
jenkins
bash-3.2$ docker ps -a
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Please clarify

**Comment by samoht** [comment]
@vikramvi this configuration is not yet supported in Docker for Mac, but we are trying to make it easier to do that in the future. I will see if we can add a section in  https://github.com/docker/docker.github.io/tree/master/docker-for-mac about that (or feel free to open a PR to suggest doc improvements).

**Comment by samoht** [comment]
I am closing the issue now as we found a workaround for your issue. Thank for using Docker for Mac!

**Comment by vikramvi** [comment]
@samoht Can you please clarify "..this configuration is not yet supported in Docker for Mac..." , I didn't get this point.

**Comment by samoht** [comment]
I just mean that Docker for Mac today only works out-of-the box if you only have one user or if you switch between users and you re-run `Docker.app` with the new user. The workflow that you have works with the workaround that I gave you, but it is clearly not an optimal user-experience. We plan to work to improve it in the future.

**Comment by vikramvi** [comment]
@samoht Thanks for detailed clarifications.

Regards,
Vikram

**Comment by Fedalto** [comment]
I had this same issue. I added a workaround to #929. Just copy & pasting it here too.

The workaround that I have for this is to run the following after every update:
```
$ ln -f -s /Applications/Docker.app/Contents/Resources/bin/* /usr/local/bin
```

Re-run `Docker.app` as the new user does not work because it will "lock" everyone else out.
It will overwrite the symlinks in `/usr/local/bin` to point to somewhere in the current user home, which may not be accessible to other users.

**Comment by shamblesides** [comment]
For those coming here from Google, I had a similar issue on Docker for Mac, but my solution was different. I realized that only one user can run Docker for Mac at a time. This is OK for my use case, but it took me a while to figure out that I would need to close down Docker for the current user, change logins, and then open it up on a different user, in order for it to work. Hope this helps someone.

**Comment by IPetrik** [comment]
> this configuration is not yet supported in Docker for Mac, but we are trying to make it easier to do that in the future.

@samoht - have there been any updates on this in the last 2.5 years?

**Comment by samoht** [comment]
No idea, I don't work at Docker anymore.

**Comment by AravinthR** [comment]
I am locked down coz of this. Can anyone help me? 

```

[testDocker] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/jenkins735990186187347338.sh
+ echo /usr/bin:/bin:/usr/sbin:/sbin
/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ echo /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ docker build -f Dockerfile -t docker-spring .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=s4tm5wit23xsm35j38aw5jwfe&shmsize=0&t=docker-spring&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by dhoeppe** [comment]
Is there an update to this? I'd like to set up a Jenkins Agent on my Mac but it's not possible without running the agent as my user.

**Comment by bzied321** [comment]
Hi, I'm experiencing the same issue trying to run a Jenkins job in a Docker container on Docker for Mac. Is there a supported configuration or workaround at this point?

bash-4.4$ whoami
jenkins
bash-4.4$ docker ps -a
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied

**Comment by TrishaChetani** [comment]
I am also facing the same issue
