### ISSUE TITLE
Docker for Mac 1.12 not starting up

### ISSUE THREAD

**Issue by w0mbat** [docker/for-mac#8]
### Expected behavior

Docker should start up

### Actual behavior

Docker is not starting up

### Information

Diagnostic ID: 93EAC757-7A6D-41B0-ADF3-768A3AF9FDB9
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/wombat/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/wombat/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/wombat/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

I installed Docker for Mac 1.12 and Docker asked to install networking components - I then entered my password and Docker failed with the Diagnostics I mentioned

**Comment by samoht** [comment]
Hi can you fille the missing sections (especially the Expected/Actual Behaviour, and any more information that you could provide)? This will help us to understand your issue better. 

I'm closing the issue for now on.

**Comment by w0mbat** [comment]
@samoht I updated the ticket - what else could I fill in?

**Comment by w0mbat** [comment]
Here is some logs from when I start Docker - how can I completely uninstall Docker for Mac when the app does not come up?
```
29.07.16 13:51:55,509 Docker[7254]: Application version: 1.12.0 (10871)
29.07.16 13:51:55,509 Docker[7254]: Administrator user: true
29.07.16 13:51:55,528 Docker[7254]: OSX Version: Version 10.11.6 (Build 15G31)
29.07.16 13:51:55,721 Docker[7254]: migrator: start migration process
29.07.16 13:51:55,723 Docker[7254]: migrator: previous install detected
29.07.16 13:51:55,723 Docker[7254]: migrator: previous version is 1.12.0-beta21
29.07.16 13:51:55,723 Docker[7254]: migrator: no migration needed, you are good to go!
29.07.16 13:51:55,723 Docker[7254]: migrator: successfully updated from version 1.12.0-beta21 to 1.12.0
29.07.16 13:51:55,723 Docker[7254]: migrator: end of migration process
29.07.16 13:51:55,759 Docker[7254]: event tracker initialized
29.07.16 13:51:55,763 Docker[7254]: Bundle path: /Applications/Docker.app
29.07.16 13:51:55,763 Docker[7254]: com.docker.vmnetd component is missing and will be installed
29.07.16 13:51:56,457 bird[290]: LaunchServices: Failed to create bundleProxy for bundle com.docker.helper
29.07.16 13:52:07,097 lsd[248]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
29.07.16 13:52:07,103 lsd[248]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
29.07.16 13:52:07,113 SecurityAgent[7264]: activateIgnoringOtherApps:1
29.07.16 13:52:07,116 SecurityAgent[7264]: makeKeyAndOrderFront
29.07.16 13:52:07,148 SecurityAgent[7264]: com.apple.SecurityAgent.consoleLogin.UIShown
29.07.16 13:52:10,424 Docker[7254]: privileged installation of com.docker.vmnetd successful
29.07.16 13:52:10,424 Docker[7254]: Communication with networking components failed.
29.07.16 13:52:11,448 SpotlightNetHelper[6351]: tcp_connection_tls_session_error_callback_imp 21 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
29.07.16 13:52:11,448 SpotlightNetHelper[6351]: tcp_connection_tls_session_error_callback_imp 20 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
```

**Comment by samoht** [comment]
What do you see when Docker is not starting? Is the icon still continue to be animated? Are you sure you enter your issue properly? Can you try a factory reset and try again? Thanks!

btw, this looks indeed strange:
```
29.07.16 13:52:10,424 Docker[7254]: privileged installation of com.docker.vmnetd successful
29.07.16 13:52:10,424 Docker[7254]: Communication with networking components failed.
````

**Comment by w0mbat** [comment]
No the icon is not animated - its filled with containers but everything is greyed out:
![bildschirmfoto 2016-07-29 um 13 59 43](https://cloud.githubusercontent.com/assets/571379/17247625/cb26c436-5594-11e6-9177-29c2bebd3bef.png)

**Comment by samoht** [comment]
Does your use have admin rights? Also, are you sure there you don't have an hidden dialog somewhere (try CTRL-TAB a few times).

**Comment by w0mbat** [comment]
Yeah there is only the "Fatal Error" Dialog with the Diagnostics coming up - afterwards the Docker App just exits and I can´t click "Factory Reset" or similar

**Comment by w0mbat** [comment]
@samoht Do you have a quick-fix to manually uninstall everything? Its kind of urgent as I have to work for my customer :/

**Comment by samoht** [comment]
can you try to reinstall Beta21, do a factory reset, and re-install Stable?

**Comment by w0mbat** [comment]
Same situation there :/

**Comment by samoht** [comment]
Maybe just wipe-out `~/Library/Containers/com.docker.docker`? I will check if you can run something on the command-line directly.

**Comment by samoht** [comment]
Also maybe check that you are moving Docker.app in your application folder before starting it.

**Comment by w0mbat** [comment]
Deleted the folder - same thing
Docker.app is in the application folder

**Comment by w0mbat** [comment]
From the logs I can see, that the migrator somehow detects an old version and does not reinstall everything from scratch

**Comment by samoht** [comment]
Killing all the `com.docker.*` process?

**Comment by w0mbat** [comment]
I don´t have any running `com.docker.*` processes once the app is closed

**Comment by samoht** [comment]
How did you get to submit that report if your application is not running and all is grey out? :-)

Can you double-check you don't have a modal dialog open? When everything is greyed-out, does `docker version` work?

**Comment by samoht** [comment]
In any case, please:

- kill all `com.docker.*` and `Docker.app` processes
- delete `~/Library/Containers/com.docker.docker`
- start your application and check for hidden modal dialogs

(sorry all of this should not be so hard)

**Comment by w0mbat** [comment]
I saw the following order of dialogs:
<img width="599" alt="bildschirmfoto 2016-07-29 um 14 52 12" src="https://cloud.githubusercontent.com/assets/571379/17248656/3230c33c-559c-11e6-9b8a-a84f489813ca.png">
<img width="601" alt="bildschirmfoto 2016-07-29 um 14 52 31" src="https://cloud.githubusercontent.com/assets/571379/17248655/3230249a-559c-11e6-9b9b-a3106a87fa7f.png">

After clicking "Diagnose & Feedback" I was able to send a report - Sure, the Diagnose Window is still a modal dialog - maybe thats the reason why the rest of the menu is greyed out but I can only exit from there.

**Comment by djs55** [comment]
I believe the error "Communication with networking components failed" means that `com.docker.vmnetd` is not listening on ` /var/tmp/com.docker.vmnetd.socket` and the UI gets `ECONNREFUSED` or maybe `ENOENT`. This socket should be created by `launchd` when the service is registered.

Did you see a 2nd dialog in between those two? One that asked you for an admin username and password? It should look like this:

![screen shot 2016-07-29 at 14 02 30](https://cloud.githubusercontent.com/assets/198586/17248884/2d5b752a-5595-11e6-8dce-ae1fce469e9b.png)


If you query `launchd` can you find the `com.docker.vmnetd` process? e.g.
```
$ sudo launchctl list | grep com.docker
83	0	com.docker.vmnetd
```

**Comment by w0mbat** [comment]
yes I saw that popup and the logs also show that sudo was successfull

**Comment by w0mbat** [comment]
no i cant see that process

**Comment by djs55** [comment]
I could reproduce something similar to this but it might not be the same bug.

I ran the command `sudo launchctl remove com.docker.vmnetd` and then opened `Docker.app`. I was prompted for my password, but then I got the same error message as you and I notice the launchd service is not registered.

Do you have a file `/Library/PrivilegedHelperTools/com.docker.vmnetd`? I deleted this with `sudo rm /Library/PrivilegedHelperTools/com.docker.vmnetd` and then relaunched `Docker.app`, gave it my password and it initialised properly.

Does deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` help you, or is it a different problem?

**Comment by w0mbat** [comment]
@djs55 w000t! This worked :) Awesome!

**Comment by w0mbat** [comment]
Do you think I can recover my images somehow? The list is now empty :/

**Comment by djs55** [comment]
I'm glad Docker is now starting. I'm still curious how you got into that state -- we'll review the uninstall/install code to see if we can find the problem.

Re: the images: I don't think there's an easy way to recover them after a factory reset unfortunately. Perhaps the file `~/Library/Containers/com.docker.docker/Data/com.docker.driver-amd64-linux/Docker.qcow2` is in a time-machine backup? Sorry I know that's a bit of a long shot.

**Comment by w0mbat** [comment]
hmmm, yeah its a week old.
@samoht A notice that this folder contains all images would have been nice before suggesting to delete it :/

**Comment by samoht** [comment]
@w0mbat really sorry about that. As I never store data directly in my containers (I use bind mounts to store the data on my host filesystem) it didn't occur to me that it would be a problem. I will add a warning next time.

**Comment by w0mbat** [comment]
@samoht me neither, but the images themselves were gone - fortunately I was able to pull most of them from a private registry

**Comment by gdevillele** [comment]
@w0mbat there's a way to uninstall Docker using command line:
`/Applications/Docker.app/Contents/MacOS/Docker --uninstall` 
or `$(mdfind Docker.app)/Contents/MacOS/Docker --uninstall`

**Comment by vivekmenezes** [comment]
I'm seeing the same kind of issue where I'm using docker version 1.12.1, and it's not starting. I'm on macos 10.12.1

If I try to start the app from the applications menu I do not see the fish show up on the top bar. On moving my cursor to the top bar I see a multi-colored wheel spinning. I'm happy to share any diagnostics with you.

**Comment by STRML** [comment]
Was having this issue as well - turns out that `/var/tmp` and `/private/var/tmp` were simply missing (!)

I recreated them with the following:

```bash
sudo mkdir -p /private/var/tmp
sudo ln -sf /private/var/tmp /var/tmp
```

A reboot was required to get docker to create the `com.docker.vmnetd.socket`.

Strange but true.

**Comment by djs55** [comment]
@STRML thanks for the interesting observation. Looking at other services on my Mac, most of them seem to put sockets in `/var/run` -- I'll investigate whether we should move our socket from `/var/tmp` to `/var/run`.
