### ISSUE TITLE
Docker Version 1.12.2-beta28 (12906) update and then install, failed to start on OSX 10.11.6

### ISSUE THREAD

**Issue by dougtoppin** [docker/for-mac#800]
Update, manually ran /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u and it included this id: DA6356F9-31EC-4E6B-B511-E78258539D00

Not sure if it uploaded or not.

### Expected behavior

docker accessible

### Actual behavior

Docker whale icon continually showing 'Docker starting' but client unable to reach server.
 
$ docker ps
Error response from daemon: Bad response from Docker engine

$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true
Error response from daemon: Bad response from Docker engine

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnostic id DA6356F9-31EC-4E6B-B511-E78258539D00
Note that Diagnose & Feedback is able to collect info but logging this so I don't think it uploaded the tarball.

Docker for Mac: version: 1.12.2-beta28 (71c4a00)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/DA6356F9-31EC-4E6B-B511-E78258539D00/20161013-153715.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
Got notice that update was available.
Installed the update and relaunched.
Never left Docker starting state.
Rebooted, still stuck.
Reinstalled.
Still stuck.

**Comment by dougtoppin** [comment]
Critical log messages in docker-system.log are:

[com.docker.vmnetd][515] <Critical>: File /usr/local/bin/docker is a symlink
[com.docker.vmnetd][515] <Critical>: File /usr/local/bin/docker-compose is a symlink
[com.docker.vmnetd][515] <Critical>: File /usr/local/bin/docker-machine is a symlink
[com.docker.vmnetd][515] <Critical>: File /usr/local/bin/notary is a symlink
[com.docker.vmnetd][515] <Critical>: File /var/run/docker.sock is a symlink or a socket
[com.docker.vmnetd][515] <Critical>: client with uid 501 requests com.docker.vmnetd install symlinks

**Comment by dougtoppin** [comment]
docker-system.log shows this from upgrade to first critical error:

[com.docker.docker][45272] <Notice>: AppDelegate: Application version: 1.12.2-beta28 (12906)
[com.docker.docker][45272] <Notice>: AppDelegate: Administrator user: true
[com.docker.docker][45272] <Notice>: OSX Version: Version 10.11.6 (Build 15G1004)
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: start migration process
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: previous install detected
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: previous version is 1.12.1-beta26.1
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: no migration needed, you are good to go!
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: successfully updated from version 1.12.1-beta26.1 to 1.12.2-beta28
[com.docker.docker][45272] <Notice>: UpdateMigrator: migrator: end of migration process
[com.docker.docker][45272] <Notice>: AppDelegate: Bundle path: /Applications/Docker.app
[com.docker.vmnetd][45281] <Notice>: Client reports version 1, commit 71c4a001c2a91e8f6aa96340d576ac06af238839
[com.docker.docker][45272] <Notice>: vmnetd: com.docker.docker commit: 71c4a001c2a91e8f6aa96340d576ac06af238839 wants version 18
[com.docker.docker][45272] <Notice>: vmnetd: com.docker.vmnetd commit: d411b71fe748cb66845ccd3235ea5b60aaf71c72 has version 18
[com.docker.vmnetd][45281] <Notice>: EOF reading packet from Unix domain socket: closing
[com.docker.docker][45272] <Notice>: Install: probe of /var/tmp/com.docker.vmnetd.socket successful: not reinstalling component
[com.docker.vmnetd][45281] <Error>: Failed to read command from client
[com.docker.vmnetd][45282] <Notice>: Client reports version 1, commit 71c4a001c2a91e8f6aa96340d576ac06af238839
[com.docker.vmnetd][45282] <Critical>: client with uid 501 requests com.docker.vmnetd install symlinks
[com.docker.vmnetd][45282] <Critical>: File /usr/local/bin/docker is a symlink

**Comment by mukteshkrmishra** [comment]
same issue faced. :(

**Comment by notorioushanz** [comment]
Hi, i had this same issue. I uninstalled docker.app with app cleaner.
and it seems to work now. warning, everything gets whipped.

this might be a permission issue. because i have 2 users on my mac. and with the principal administrator account it was working well.

**Comment by dougtoppin** [comment]
Followup on this. I installed macOS Sierra (10.12) and re-installed the Docker Mac Beta and it still did not work. I then used the Docker UI to uninstall docker entirely and then installed it again.
This time it did come up successfully.
Still not sure what caused the initial issue.

2 lessons (re-)learned, don't update anything if you have to have it working the next day and make sure that the customized images that you made have been pushed to DH because you might lose them anytime.
