### ISSUE TITLE
Increase ulimit -l

### ISSUE THREAD

**Issue by jakajancar** [docker/for-mac#801]
Moby's /etc/init.d/docker currently sets

```
    # set ulimits as high as possible
    ulimit -n 1048576
    ulimit -p unlimited
```

Can you also please set `ulimit -l` higher? We need it for Varnish.

**Comment by justincormack** [comment]
What sort of value do you need?

**Comment by justincormack** [comment]
Ok, 82000 seems to be recommended. https://www.varnish-cache.org/lists/pipermail/varnish-misc/2011-August/020949.html

**Comment by justincormack** [comment]
@jakajancar you can increase the limits to the recommended value with `docker run --ulimit memlock=85983232:85983232 varnish` but I will increase the default as it is pretty low.

**Comment by justincormack** [comment]
The default will be increased in the next beta.

**Comment by jakajancar** [comment]
@justincormack Can you explain how you got to 85983232?

**Comment by justincormack** [comment]
82 Megabytes. The ulimit specification in the `docker run` command is in bytes, while for the shell it is in k it seems.

**Comment by jakajancar** [comment]
Ah, ok.

Although if varnish there has 82000 KB (not 82 MB), then that's 83968000 B, no? Not that it matters, probably.

**Comment by justincormack** [comment]
No, it doesnt make much difference, as it is a minimum.
