### ISSUE TITLE
Native Docker for Mac – need ability to define per container memory/cpu conf

### ISSUE THREAD

**Issue by remysaissy** [docker/for-mac#802]
Hi,
currently the docker for mac allows for a global memory and cpu setting for all containers.
it would be good to have a way to override these settings for some containers (eg a dev env that would need much more resources to build properly).

**Comment by justincormack** [comment]
You can set memory use per container, see https://docs.docker.com/engine/reference/run/#/runtime-constraints-on-resources

However these need to be less than the total, we have to reboot the virtual machine to increase its memory and CPUs, so we cannot easily do it for a single docker run.

**Comment by wiseman** [comment]
The `-m`/`--memory` flag doesn't seem to work.

With the Memory slider in preferences set to 1 GB:

```
[wiseman@rad187-20 Preferences]$ docker run -m 4m -ti ubuntu bash
root@647c6a996241:/# free
              total        used        free      shared  buff/cache   available
Mem:        1016508       80532      722496      167884      213480      682872
Swap:       4095996           0     4095996
```

With the slider set to 2 GB:
```
[wiseman@rad187-20 Preferences]$ docker run -m 4m -ti ubuntu bash
root@50892509efc8:/# free
              total        used        free      shared  buff/cache   available
Mem:        2047164       76736     1761000      167852      209428     1719360
Swap:       4095996         496     4095500
```

**Comment by ijc25** [comment]
AIUI @justincormack has given the solution to this and there is no further need to track this in docker/for-mac. Please reopen if I am mistaken.

**Comment by remysaissy** [comment]
Well the answer is that it is not possible for a container but that's an answer indeed.
Thanks
