### ISSUE TITLE
https://download.docker.com/mac/stable/Docker.dmg

### ISSUE THREAD

**Issue by Bruce-li-92** [docker/for-mac#804]
### Information

Diagnostic ID: 4D8AB3DF-5707-431B-8AC1-CD5B322C5642
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Detected symptom of problem 'unsupported-sierra' in 4D8AB3DF-5707-431B-8AC1-CD5B322C5642.

Sierra is supported from the version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the stable channel. Please upgrade.

May be related to docker/for-mac#561
