### ISSUE TITLE
Last Docker stable - don't start on MacOs 10.11.6 El Capitan after installation

### ISSUE THREAD

**Issue by chespinoza** [docker/for-mac#805]
### Expected behavior
Docker startup after clean installation
### Actual behavior
Docker don't start
### Information

Diagnostic ID: 04B84FA6-0C52-42D7-B808-6D94A6FFF2F6

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/04B84FA6-0C52-42D7-B808-6D94A6FFF2F6/20161015-004704.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/cespinoza/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW

After clean installation, also tried restarting OS and reinstalling without success.

### Steps to reproduce the behavior

  1. ...Install last stable version Version 1.12.1 (build: 12133)
  2. ...Tried to start

**Comment by artmak** [comment]
Hi! In 10.12 (16A323) Sierra to.

**Comment by chespinoza** [comment]
Ok, checking generated logs in /tmp I saw this error message:

**vmx_init processor not supported**

I realized that my mac doesn't support virtualization, that was the problem, I checked with a newer one and it's worked ok.

Sorry and thanks.
