### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by lege2016** [docker/for-mac#806]
### Information

Diagnostic ID: 4DDBB1D6-CDDD-4FB6-9D10-265B7AECF737
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.10.5 (Build 14F1912)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. ...
2. ...

**Comment by rogaha** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 4DDBB1D6-CDDD-4FB6-9D10-265B7AECF737/20161016-220518.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

**Comment by rogaha** [comment]
@lege2016 can you please confirm if that fixes the issue?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
