### ISSUE TITLE
docker failed to start

### ISSUE THREAD

**Issue by judezhan** [docker/for-mac#807]
### Information

Diagnostic ID: 5ECC228B-2CDC-4EC3-9E85-071E7FAF86A3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by rogaha** [comment]
Analysing archive 5ECC228B-2CDC-4EC3-9E85-071E7FAF86A3/20161016-235146
--------------------------------------------------------------------------------
Detected symptom of problem 'unsupported-sierra' in 5ECC228B-2CDC-4EC3-9E85-071E7FAF86A3/20161016-235146.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the stable channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
