### ISSUE TITLE
docker build command freezes

### ISSUE THREAD

**Issue by guidsen** [docker/for-mac#808]
### Expected behavior

Run `docker build`
### Actual behavior

When I run `docker build .` it just does nothing, it freezes without giving feedback.
I've also tried running as root, but without success.
### Information

Diagnostic ID: 58C94623-A5F1-4D4C-9E28-28D0DEFB6788
Diagnose & Feedback info:

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.4 (build: 15E65)
logs: /tmp/58C94623-A5F1-4D4C-9E28-28D0DEFB6788/20161016-193751.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by rogaha** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in 58C94623-A5F1-4D4C-9E28-28D0DEFB6788/20161016-193751.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

**Comment by amazingandyyy** [comment]
I have same thing.

When I type
`docker build -t andychen/debian .`

it does nothing 

freeze there for about 2 mins...
and show errors:
`Error checking context: 'can't stat '/Users/Andysign/Library/Saved Application State/com.bitrock.appinstaller.savedState''.`

**Comment by dsheets** [comment]
@amazingandyyy could you please open a new issue with a diagnostic summary (including Diagnostic ID) from :whale: ➡️ `Diagnose & Feedback` ➡️ `Diagnose & Upload`? Also, if you can share the repository, script, use case, or configuration that lets us reproduce your issue, that would be very helpful. Thanks!

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by cheerfulstoic** [comment]
In case anybody runs into this issue, one thing that I did that seemed to fix it: I had a 1.7 GB directory with hundreds of thousands of files inside of the directory that I was trying to do a `docker build .` on.  When I removed that, `docker build .` started working.

Is there a phase at the start of `docker build` that goes through all of the files in all of the subdirectories?  If so, it might be good to have some sort of output explaining that.

**Comment by JFernandoGomez** [comment]
@cheerfulstoic removing excessive files like `node_modules` folder worked

**Comment by 1c7** [comment]
I have only 3 small file but still hang.
Using Docker on mac
![image](https://user-images.githubusercontent.com/1804755/51789111-b2e06a80-21c0-11e9-9a86-b69aa01b9642.png)

![image](https://user-images.githubusercontent.com/1804755/51789134-f1762500-21c0-11e9-9d18-6bc89867ead3.png)

**Comment by patrickmao93** [comment]
> @cheerfulstoic removing excessive files like `node_modules` folder worked

This solved my issue. Looks like docker would check every nested folder and look for Dockerfile. Add a .dockerignore file in your root directory and write down `node_modules` or whatever excessively large folder in there.
