### ISSUE TITLE
rm -rf inside mounted folder makes docker hang on 2nd run

### ISSUE THREAD

**Issue by hyperknot** [docker/for-mac#809]
### Expected behavior

Should not hang Docker, but just delete folder.
### Actual behavior

The `rm -rf /shared/logs/CURRENT` hangs on the 2nd runs of a Docker container. The command cannot be terminated. Docker container cannot be stopped. Docker need to be reset by the GUI button. After reset it's good for the first run, but hangs the second run.

Changing the line to `rm -rf /shared/logs/CURRENT/*` is a workaround, which is not affected.
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/443608CC-D89F-474E-840B-BFA447D53242/20161017-030748.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

Was the exact same behavior in beta channel.
- A reproducible case if this is a bug, Dockerfiles FTW.
  Cannot share full file or Dockerfile. Literally it runs the following:

```
rm -rf /shared/logs/CURRENT
mkdir -p /shared/logs/CURRENT # as root

mkdir -p /shared/logs/CURRENT/nginx
chown -R nginx:nginx /shared/logs/CURRENT/nginx

mkdir -p /shared/logs/CURRENT/postgresql
chown -R postgres:postgres /shared/logs/CURRENT/postgresql

mkdir -p /shared/logs/CURRENT/redis
chown -R redis:redis /shared/logs/CURRENT/redis
```

On each startup and starts nginx, postgres, redis, etc. services, which log to their own folder. On shutdown it shuts the down. On next startup, the rm -rf line hangs. 
### Steps to reproduce the behavior
1. Start container
2. Stop container
3. Start container

The start command is the following:

```
docker run --name $DOCKER_REPO --rm -it \
    -v "$DOCKER_REPO"_data:/data \
    -v "$(pwd)/../../../shared":/shared \
    -p 127.0.0.1:7050:80 \
    --add-host localhost.example.com:127.0.0.1 \
    -e DEV_MODE=1 \
    $DOCKER_USER/$DOCKER_REPO:latest \
    /sbin/my_init -- bash -l
```

Note: it doesn't happen always. Sometimes it happens, then it can be 100% reliably replicated. Sometimes it just doesn't happen. No idea what makes the difference.

**Comment by dsheets** [comment]
Thanks for your report. I cannot reproduce this issue but I also don't expect to be able to. If you can semi-consistently reproduce it, could you please record a trace of the file system activity and send it to `beta-feedback@docker.com` with a reference to this issue? The trace will contain all of the file system transactions including data read and written so it may contain sensitive data. When recording a trace, it is best to reduce the duration of the trace as much as possible to reduce the size of transmission and the amount of data to be analyzed. However, it is important that all activities that may be involved in the defective behavior are performed while tracing is on to give us a complete picture of the situation.

To record a trace, do the following:

1. Run `killall -USR1 com.docker.osxfs` to begin recording.
2. Perform all actions that result in the defective behavior but no more.
3. Run `killall -USR1 com.docker.osxfs` to stop recording.

It is crucial that you remember to stop recording or your disk will fill with file system traces and Docker for Mac will perform badly.

Once you have recorded the trace, you will find it in `~/Library/Containers/com.docker.docker/Data/logs/` inside of a subdirectory named after the current date. The trace will be a directory named `osxfs.XXXX.trace` where `XXXX` is a number incrementing for every trace that you run on a day. Hopefully, the trace files are a few megabytes or less and you can simply run `tar cvzf rm-rf-trace.tar.gz 2016-10-17/osxfs.0000.trace` or similar to archive and compress them. Finally, send this file to `beta-feedback@docker.com` with a reference to this issue and my name.

If you have any questions, I'd be happy to answer them. From the logs, the issue looks like something is wrong with recreation of directories possibly in conjunction with file system events.

Thanks, again, for your report!

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
