### ISSUE TITLE
Docker crash down in Mac 10.12

### ISSUE THREAD

**Issue by yexianyi** [docker/for-mac#810]
### Information

Diagnostic ID: 93DB1FD8-4D47-44EE-BC0E-EF29FAE3EE75
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by dsheets** [comment]
Detected symptom of problem 'unsupported-sierra' in 93DB1FD8-4D47-44EE-BC0E-EF29FAE3EE75.

Sierra is supported on latest stable and beta releases only. Please upgrade.
