### ISSUE TITLE
Mac File Sharing for files not under /Users gives: Error The path / is reserved by Docker.

### ISSUE THREAD

**Issue by ebridger** [docker/for-mac#811]
### Expected Behavior
Mount OS X dirs / files not under /Users. e.g.
`docker run  -t --rm -v /Applications/MAMP/htdocs/:/htdocs alpine sh -c "ls -la /htdocs"`
says to add the dir using: Docker -> Preferences -> File Sharing.

### Actual Behavior
After adding /Applications/MAMP/htdocs/ relaunching Docker gives an error dialog:
> Error
> The path / is reserved by Docker.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Diagnostic ID: D1332C15-D5DF-47FF-9BA0-13F787CD603F

> Docker for Mac: version: 1.12.2-beta28 (71c4a00)
> OS X: version 10.11.6 (build: 15G1004)
> logs: /tmp/D1332C15-D5DF-47FF-9BA0-13F787CD603F/20161017-084419.tar.gz
> [OK]     docker-cli
> [OK]     virtualization kern.hv_support
> [OK]     menubar
> [OK]     moby-syslog
> [OK]     dns
> [OK]     disk
> [OK]     system
> [OK]     app
> [OK]     osxfs
> [OK]     virtualization VT-X
> [OK]     db
> [OK]     slirp
> [OK]     logs
> [OK]     env
> [OK]     vmnetd
> [OK]     moby-console
> [OK]     moby
> [OK]     driver.amd64-linux
 
### Steps to reproduce the behavior

  1. Open Docker -> Preferences -> File Sharing 
  2. Add /Applications/MAMP/htdocs, or any dir under /Applications, /usr/local, etc
  3. Choose Apply & Restart

**Comment by dsheets** [comment]
It looks like you've upgraded from quite an old version of Docker for Mac and have somehow retained the `/` mount export entry in your export table despite our attempts to remove it for you during upgrade migration. If you remove the `/` entry from the File Sharing preferences screen, things should be back to normal. If this doesn't work or doesn't fix your problem, please re-open this issue.

Thanks for using Docker for Mac!

**Comment by ebridger** [comment]
Yes. This fixed it. Thanks for the quick response.
