### ISSUE TITLE
docker 1.12.1 on osx keeps freezing.

### ISSUE THREAD

**Issue by nelsonenzo** [docker/for-mac#813]
### Expected behavior

docker ps to return running containers and docker start <container-name> to start a container
### Actual behavior

nothing happens, just freeezes.
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.10.5 (build: 14F1912)
logs: /tmp/457B79B0-21CB-4F55-B889-E73EFBC7D2D1/20161017-140021.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior

Keep docker running on your macbook.
Go in and out of sleep mode several times.
Eventually this seems to happen on a regular basis.

**Comment by rogaha** [comment]
Detected symptom of problem 'hypervisor-framework-acpi-crash' in 457B79B0-21CB-4F55-B889-E73EFBC7D2D1/20161017-140021.

It looks like at least some cases can be explained by a bug in the workaround for a Hypervisor.framework ACPI crash bug. We are not sure whether the workaround is still needed -- the underlying crash may well have been fixed by Apple, especially in the most recent versions and updates of MacOSX 10.11.3 and higher.

May be related to docker/for-mac#85

**Comment by rogaha** [comment]
@nelsonenzo is the OS update a viable option? Otherwise, can you please try to reset to factory defaults which will unfortunately delete /var/lib/docker (all containers and images will need to be rebuilt)?

**Comment by samoht** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by wbednarski** [comment]
It is crashing for me as well, `docker-compose up` and MBP freezes and required force reset.

**Comment by nxmohamad** [comment]
I'm on macOS 10.10.5 and docker seems to freeze after some time and/or after macbook going to sleep. This machine is not my own dev machine. My own dev machine does not experience this problem.
