### ISSUE TITLE
docker incompatiable

### ISSUE THREAD

**Issue by ervinknight** [docker/for-mac#814]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
There's not enough information here for us to investigate.  Could you please open a new issue with more details?
