### ISSUE TITLE
docker for mac start failed

### ISSUE THREAD

**Issue by zhmchenprime** [docker/for-mac#816]
### Information

Diagnostic ID: 635A6EB8-E301-456C-BF54-93907A63B364
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by rogaha** [comment]
Detected symptom of problem 'unsupported-sierra' in 478B8933-1887-4A65-A357-0A19421B312D/20161018-214639.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the stable channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561 -- feel free to re-open it if the issue persists.
