### ISSUE TITLE
ARG not usable on 1.12

### ISSUE THREAD

**Issue by chezbut** [docker/for-mac#817]
### Actual behavior

Even a CMD echo $BAR2 or CMD echo $BAR shows no output, only "$BAR" as if it were explicitly quoted or escaped. 
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior
1. Create ANY dummy dockerfile
2. Set an ARG abcd
3. Specify a CMD or RUN of echo $abcd
4. Run your docker build with or without the build args and observe the arg not being usable, either the one defined in the dockerfile or the build-time arg. 

Note: looks like Github doesn't allow attaching Dockerfiles, so I'll paste it below:

FROM xxxx/xxx/xxx-base

ARG GRAFANA_VERSION=3.1.1-1470047149
CMD echo $GRAFANA_VERSION

RUN curl https://grafanarel.s3.amazonaws.com/builds/grafana_$GRAFANA_VERSION_amd64.deb > /tmp/grafana.deb && \
    dpkg -i /tmp/grafana.deb && \
    rm /tmp/grafana.deb

EXPOSE 3000

COPY scripts/run.sh /run.sh
COPY grafana-entrypoint.sh /grafana-entrypoint.sh
RUN  chmod +x /grafana-entrypoint.sh
COPY supervisord_conf/etc/supervisor/conf.d/\* /etc/supervisor/conf.d/
COPY grafana_conf/etc/grafana/grafana.ini /etc/grafana/grafana.ini
CMD  supervisord -c /etc/supervisor/supervisord.conf

**Comment by chezbut** [comment]
Output: 
$ docker build --rm -t grafana .
Sending build context to Docker daemon 277.5 kB
Step 1 : FROM xxx/xxx-base
 ---> 3b351e9c669f
Step 2 : ENV GRAFANA_VERSION 3.1.1-1470047149
 ---> Using cache
 ---> 1ffcfd518934
Step 3 : CMD echo $GRAFANA_VERSION
 ---> Running in f984b8f45104
 ---> 1d3407fba210
Removing intermediate container f984b8f45104
Step 4 : RUN curl ${GRAFANA_VERSION} > /tmp/grafana.deb &&     dpkg -i /tmp/grafana.deb &&     rm /tmp/grafana.deb
 ---> Running in 1fb4556262fb
^C
$

**Comment by chezbut** [comment]
$ docker --version
Docker version 1.12.1, build 6f9534c

**Comment by chezbut** [comment]
Same results on Ubuntu docker, from the same dockerfile and same Ubuntu base. 

Docker version 1.12.1, build 23cf638

**Comment by justincormack** [comment]
Can you make a fully reproducible minimal test case please. I am using `ARG` on Docker for Mac without issues, so it is something about the detail of your usage, but I cannot actually test your example.

**Comment by chezbut** [comment]
The test case is specifically using CURL with a RUN argument as shown above, trying to CURL a URL with an ARG variable as part of the URL.

**Comment by dsheets** [comment]
If you are interpolating an argument into a string which has variable-name-valid character following the argument variable name, e.g. `$GRAFANA_VERSION_amd64.deb`, you must delimit the variable name with `{` and `}` otherwise the parser does not know where the variable name ends:

```
RUN curl https://grafanarel.s3.amazonaws.com/builds/grafana_${GRAFANA_VERSION}_amd64.deb
```
