### ISSUE TITLE
56CDB37C-E9EB-4497-9313-AD36283FD675

### ISSUE THREAD

**Issue by nick3** [docker/for-mac#823]
### Information

Diagnostic ID: 56CDB37C-E9EB-4497-9313-AD36283FD675
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A320)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by rogaha** [comment]
Detected symptom of problem 'unsupported-sierra' in 478B8933-1887-4A65-A357-0A19421B312D/20161018-214639.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the stable channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
