### ISSUE TITLE
Docker will not start

### ISSUE THREAD

**Issue by cjdavies** [docker/for-mac#829]
### Information
Diagnostic ID D466944B-790A-45B7-A2D8-3CF4FEDFBAC6

- Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/D466944B-790A-45B7-A2D8-3CF4FEDFBAC6/20161020-112100.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/davies/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/davies/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/davies/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/davies/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/davies/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. This was the first attempt to run Docker after installation.

**Comment by rogaha** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in D466944B-790A-45B7-A2D8-3CF4FEDFBAC6/20161020-112100.

The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. 

May be related to docker/for-mac#61

**Comment by rogaha** [comment]
@cjdavies can you please try that and let us know if that works? Thanks

**Comment by cjdavies** [comment]
That worked. Thanks!

**Comment by AntonLiapesha** [comment]
👍 That helped!

**Comment by fredex42** [comment]
👍 had the same issue when i had to reinstall Docker CE 17.09 on my Mac 10.11, this fixed it.

**Comment by paddyrails** [comment]
Thanks @rogaha 
The UI failed to communicate with the networking helper process. Deleting /Library/PrivilegedHelperTools/com.docker.vmnetd and restarting the application should help you.

Helped me!

**Comment by Jaggle** [comment]
very sad, same issue but not helped
