### ISSUE TITLE
Docker HTTP and HTTPS proxy settings disappear

### ISSUE THREAD

**Issue by jwilso** [docker/for-mac#830]
### Expected behavior

Configure http and https proxy in GUI from Docker desktop pulldown in "Preferences... -> Advanced".  Click "Apply and Restart" to save.
### Actual behavior

Configure http and https proxy in GUI from Docker desktop pulldown in "Preferences... -> Advanced".  Click "Apply and Restart" to save.  Select "General" tab from Docker popup. Adjust memory value. Click "Apply and Restart". Click on "Advanced" tab.  Proxy settings gone.
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
  Docker for Mac: version: 1.12.1 (2d5b4d9)
  OS X: version 10.11.6 (build: 15G1004)
  logs: /tmp/7F94592F-6532-4941-BF94-9AF878A4864B/20161020-172057.tar.gz
  [OK]     docker-cli
  [OK]     virtualization kern.hv_support
  [OK]     menubar
  [OK]     moby-syslog
  [OK]     dns
  [OK]     disk
  [OK]     system
  [OK]     app
  [OK]     osxfs
  [OK]     virtualization VT-X
  [OK]     db
  [OK]     slirp
  [OK]     logs
  [OK]     env
  [OK]     vmnetd
  [OK]     moby-console
  [OK]     moby
  [OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. Configure HTTP and HTTPS proxy settings in GUI from Docker desktop pulldown in "Preferences... -> Advanced".
2. Click "Apply and Restart" to save.
3. Select "General" tab from Docker popup.
4. Adjust memory value to something different.
5. Click "Apply and Restart".
6. Click on "Advanced" tab.
7. Proxy settings gone.

**Comment by ijc25** [comment]
@jwilso thanks for your report. I believe this has been fixed in the latest stable (1.12.3). Please reopen if that is not the case for you.
