### ISSUE TITLE
Docker behat Laravel issues

### ISSUE THREAD

**Issue by juanmrad** [docker/for-mac#834]
On version 1.12.1 behat comand runs db migrate from laravel super slow. I had to downgrade to version 1.12.0 in order to be able to run it smoothly.

I'm running on OS El capitan 10.11.6 and Laravel 5.1. 
It takes over 5 minutes to run a simple scenario due to the slow migrate. doing a
php artisan migrate
takes over 2 minutes. DB only has 44 tables.

**Comment by dsheets** [comment]
You may be suffering from #668 which contains a work-around for the block device sync issue.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
