### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by WANG-lp** [docker/for-mac#836]
When I run `redis-benchmark` to test the `redis:latest` container's performance, I got `Error: Server closed the connection` error
### Actual behavior

`PING_INLINE: 11560.69 requests per second`
`Error: Server closed the connection`
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
  
  Docker for Mac: version: 1.12.1 (2d5b4d9)
  OS X: version 10.12 (build: 16A323)
  logs: /tmp/2AAFF141-6325-4D48-9C6C-E30FABB615F6/20161023-011622.tar.gz
  [OK]     docker-cli
  [OK]     virtualization kern.hv_support
  [OK]     menubar
  [OK]     moby-syslog
  [OK]     dns
  [OK]     disk
  [OK]     system
  [OK]     app
  [OK]     osxfs
  [OK]     virtualization VT-X
  [OK]     db
  [OK]     slirp
  [OK]     logs
  [OK]     env
  [OK]     vmnetd
  [OK]     moby-console
  [OK]     moby
  [OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. start docker for mac application
2. in terminal, run `docker run -p 26379:6379  -d redis:latest`
3. run `redis-benchmark -h 127.0.0.1 -p 26379 -n 10000 -q`

Then you will get `Error: Server closed the connection` occasionally.

Hope this helpful.

**Comment by samoht** [comment]
Does Diagnose & Feedback from the :whale: menu work? Could you please run and upload the diagnostics and post your diagnostic ID back here?

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
