### ISSUE TITLE
Docker crash while updating.

### ISSUE THREAD

**Issue by Kreshnik** [docker/for-mac#837]
### Information

Diagnostic ID: 8A53DC77-1445-45BF-9C1C-8F5479CDB11F
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12.1 (Build 16B2553a)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/Ninxha/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[ERROR]  slirp
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
### Steps to reproduce
1. ...
2. ...

**Comment by samoht** [comment]
Detected symptom of problem 'unsupported-sierra' in 8A53DC77-1445-45BF-9C1C-8F5479CDB11F/20161023-205919.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
