### ISSUE TITLE
not login

### ISSUE THREAD

**Issue by bayhe** [docker/for-mac#840]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by yallop** [comment]
There's not enough information here for us to diagnose the problem, unfortunately.  If the issue persists, could you please open a new issue with a diagnostic ID and a description of the problem?
