### ISSUE TITLE
Docker does not run under Mac OS Sierra - even newest version

### ISSUE THREAD

**Issue by Tohoff** [docker/for-mac#841]
### Expected behavior

Docker should except terminal commands.
### Actual behavior

Docker does not except terminal commands.
### Information
- Diagnose & Feedback"

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12 (build: 16A323)
logs: /tmp/ACB893CB-1936-40C0-84E4-F6D82F529659/20161025-075850.tar.gz
failure: cannot find docker
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
### Steps to reproduce the behavior
1. Install Docker
2. Start Docker
3. Try to type commands with "docker..."
4. Terminal shows "-bash: docker: command not found"

**Comment by Jokersoft** [comment]
Same here, even with the newer beta:
```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.12 (build: 16A323)
logs: /tmp/406E5697-E959-4636-8B90-A00383A6724F/20161031-111533.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by samoht** [comment]
@Tohoff 

Detected symptom of problem 'symlinks-are-not-correctly-installed' in ACB893CB-1936-40C0-84E4-F6D82F529659/20161025-075850.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

**Comment by samoht** [comment]
@Jokersoft your issue seems different and related to osxfs. Could you please open a new issue to track this? Thanks!

**Comment by dsheets** [comment]
The `osxfs` issue occurred prior to upgrade from beta 19 to beta 29.2.

@Jokersoft a new report would still be very welcome. Thanks for using Docker for Mac!
