### ISSUE TITLE
Port 3306 is in use with no containers running

### ISSUE THREAD

**Issue by flynniec6** [docker/for-mac#843]
### Expected behavior

Having started **docker** but before launching any containers, expect port 3306 not to be in use.
`sudo lsof -i :3306` should return an empty list.
### Actual behavior

The opposite. The command `sudo lsof -i :3306` returns

```
COMMAND    PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 2626 flynniec6   21u  IPv4 0xc54f029df81899f5      0t0  TCP *:mysql (LISTEN)
com.docke 2626 flynniec6   22u  IPv6 0xc54f029df8a12b85      0t0  TCP localhost:mysql (LISTEN)
```
### Information

Docker for Mac: version: 1.12.2-beta28 (71c4a00)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/75E7D14C-D11A-4110-9C4D-80B99EFE79DA/20161025-100647.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. Start docker and wait for it to complete the loading animation
2. Run `sudo lsof -i :3306`
### Notes

Diagnostic ID: 75E7D14C-D11A-4110-9C4D-80B99EFE79DA

The problem was originally discovered because a container configured to use port 3306 could not start.

If I manually kill the offending process shown by the command, the docker loading animation restarts, and a new process gets created which is using port 3306. The running container list remains empty.

**Comment by flynniec6** [comment]
We were using **mariadb** image as part of the project, which is the container that couldn't start up because port 3306 was already in use. Using docker-compose but without the restart setting.

Everything was working as normal yesterday (Monday 24th of October)

**Comment by flynniec6** [comment]
This might be the same problem
https://forums.docker.com/t/com-docker-slirp-is-using-my-containers-ports/16663/2

**Comment by samoht** [comment]
@flynniec6 Do you still experience the problem or did you find a workaround?

**Comment by flynniec6** [comment]
Sorry, no longer occurring.

**Comment by shenjiang** [comment]
I met this kinds of issues several times. Even if I kill com.docker.slirp, it will restart and occupy the port again.
I find one walkaround for this. 

1. Stop docker app first.
2. Start an application from **host** which occupy the port first.
3. Restart the app again, you could see com.docker.slirp is not using the port again.
4. Then you stop the application on host.
5. Start the container which use that port.

**Comment by spelunkingdevil** [comment]
This happens every time I start a docker stack that includes a service with published ports.

Even after the stack is removed and 'swarm leave' executed, the ports are still in use by com.docker.slirp

Example output:
.,@davesMac,BUILD,__> lsof -n | egrep LISTEN
com.docke 82439 dmiller   26u     IPv4 0xcee4da3480839991         0t0       TCP *:13131 (LISTEN)
com.docke 82439 dmiller   27u     IPv6 0xcee4da346c5603e9         0t0       TCP [::1]:13131 (LISTEN)
com.docke 82439 dmiller   28u     IPv4 0xcee4da3475ef2479         0t0       TCP *:13132 (LISTEN)
com.docke 82439 dmiller   30u     IPv6 0xcee4da346c560929         0t0       TCP [::1]:13132 (LISTEN)
.,@davesMac,BUILD,__> ps  82439
  PID   TT  STAT      TIME COMMAND
82439   ??  Ss     2:21.08 com.docker.slirp --db /Users/dmiller/Library/Containers/com.docker.docker/Data/s40 --
