### ISSUE TITLE
Fix Issue pls

### ISSUE THREAD

**Issue by vicfernandez** [docker/for-mac#844]
### Information

Diagnostic ID: FC3B42FC-538E-43EA-B864-6C5F1A47FABD
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
### Steps to reproduce
1. ...
2. ...

**Comment by samoht** [comment]
Does Diagnose & Feedback from the :whale: menu work? Could you please run and upload the diagnostics and post your diagnostic ID back here?

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
