### ISSUE TITLE
Error response from daemon: dial unix /Users/ryuta/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

### ISSUE THREAD

**Issue by oshikryu** [docker/for-mac#846]
### Expected behavior

Do not quit
### Actual behavior

Quits every 5 minutes and requires docker restart
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/591D1575-E6D6-4638-A8B2-D6F40DDDF3FC/20161025-152934.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior

Running docker with a flask webserver and mongodb

**Comment by TsumiNa** [comment]
got same issue with you but with nginx+tornado+mongodb. I use weighttp to ran a simple benchmark test and found that when the response get bigger(about 5MB), this issue occurred.

**Comment by samoht** [comment]
Beta29.3 should fix your issue. Could you try to upgrade and report if it works for you? Thanks!

**Comment by samoht** [comment]
(/cc @dsheets as the logs shows interesting osxfs crashes)

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by rolfchess** [comment]
I had the same problem. Installing Docker Version 1.13.0-rc3-beta33.1 (14779) seems to have fixed the problem.
