### ISSUE TITLE
Mac problems

### ISSUE THREAD

**Issue by icemanovich** [docker/for-mac#847]
### Information

Diagnostic ID: 9028B00E-0EDC-434D-9451-8FBF7FDF50F3
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/ignat/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/9028B00E-0EDC-434D-9451-8FBF7FDF50F3/20161026-083820/qemu-img-check.stdout 2> /tmp/9028B00E-0EDC-434D-9451-8FBF7FDF50F3/20161026-083820/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/ignat/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ignat/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/ignat/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/ignat/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/ignat/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
### Steps to reproduce
1. ...
2. ...

**Comment by dsheets** [comment]
Detected symptom of problem 'unsupported-sierra' in 9028B00E-0EDC-434D-9451-8FBF7FDF50F3/20161026-085249.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561

The following log matches:
```Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: Application version: 1.12.0-a (11213)
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: Administrator user: true
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: OSX Version: Version 10.12 (Build 16A323)
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: migrator: start migration process
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: migrator: no previous version detected. Performing all migrations for now...
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: migrator: 0 migrations to perform
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Notice>: migrator: end of migration process
Oct 26 08:35:02 MacBook-Pro-Ignat Docker[com.docker.docker][805] <Error>: event tracker initialization failed
```
