### ISSUE TITLE
"vmstateevent invalid json" fatal error during upgrade

### ISSUE THREAD

**Issue by mmenozzi** [docker/for-mac#848]
### Expected behavior
Successful upgrade

### Actual behavior
"vmstateevent invalid json" fatal error

### Information

Diagnostic ID: 25EE9EB6-48C3-4C54-B2D3-7DF13EEAC354
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install upgrade

**Comment by dave-tucker** [comment]
Unfortunately the version of Docker for Mac you are running is not supported on OSX Sierra.
You will need to go to 🐳  -> `Preferences` -> `Uninstall/Reset` -> `Uninstall` and then drag the old `Docker.app` to the trash. 

**Warning: You will lose any data from your old Docker for Mac installation. If you have containers or images you want to keep you should use `docker save` to export them**

You can download a version that supports Sierra from [here](https://docs.docker.com/docker-for-mac/)

I'm closing this for now, but please feel free to re-open if this doesn't solve your problem.
