### ISSUE TITLE
Custom kernel module

### ISSUE THREAD

**Issue by brmzkw** [docker/for-mac#851]
Is it possible to enable CONFIG_PPP_ASYNC and CONFIG_PPP?

They are required to run [forticrap](https://github.com/brmzkw/forticrap), a fortigate SSL-VPN client — and actually any PPTP client.

Also, is it possible to rebuild the kernel used with docker for mac?

**Comment by justincormack** [comment]
Hi, yes can add those.

The kernel config and patches from upstream are available in the VM, see https://github.com/docker/for-mac/issues/719#issuecomment-252616845 for how to extract them. You should be able to build a kernel module and add it with a sufficiently privileged container.

**Comment by brmzkw** [comment]
Thanks a lot :-)

How can I get the new kernel? Do I have to wait for a release and "check for update"?

**Comment by justincormack** [comment]
It will be in the next beta; as we just released a beta last night the current estimate would be next Tuesday, but it might be before or after that depending on other releases and issues. It probably won't be in the stable channel for a bit longer.

**Comment by brmzkw** [comment]
Thanks a lot :)

**Comment by darwin** [comment]
Good timing! Just today I decided to move a pptp client from a mac host into a docker container. And I was hitting `Couldn't set tty to PPP discipline: Invalid argument` error after strictly following [Debian HOWTO][1]. Then I desperately tried to build and run the container under ubuntu host and the issue wasn't present.

Just upgraded to Docker for Mac beta and PPP discipline problem went away. But unfortunately this is probably not all what is required. 

pptpsetup complains: `/usr/sbin/pptpsetup: couldn't find MPPE support in kernel.`

Would it be possible to enable CONFIG_PPP_MPPE as well?

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

> docker --version
Docker version 1.12.3, build 6b644ec, experimental
```

[1]: http://pptpclient.sourceforge.net/howto-debian.phtml

**Comment by darwin** [comment]
Hmm, strange. It looks like you include MPPE support.

`docker run --privileged <my-container> zcat /proc/config.gz | grep MPPE` returns `CONFIG_PPP_MPPE=y`.

And I don't see any mention of MPPE in your kernel patches...

Going to open a new issue.

**Comment by darwin** [comment]
Ah, nevermind. `pptpsetup` is reports missing MPPE probably because this command fails. But MPPE is actually present.

```
> modprobe ppp-compress-18
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.30-moby/modules.dep.bin'
```
