### ISSUE TITLE
Overlay2 storage driver breaks tmux

### ISSUE THREAD

**Issue by ragrum** [docker/for-mac#852]
### Expected behaviour

After running `$ tmux`, it starts correctly.

### Actual behaviour

After running `$ tmux`, only the characters `1;2c` are shown. Tmux doesn't start.

After googling the issue, some people suggest this is because some permissions
problems. I suspect the new Overlay2 storage driver has something to do with this
issue. It was working perfectly with the AUFS driver.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.3-rc1-beta29 (2b90989)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/493394D0-FD75-4026-85C7-D246FFAFE3BF/20161026-081715.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
````

### Steps to reproduce the behavior

  1. Update to the latest beta
  2. Do a factory reset to get Overlay2 as the default driver

**Comment by justincormack** [comment]
Hi this is probably not related to overlay but to https://github.com/docker/docker/issues/27765 we are working on a fix now.

**Comment by justincormack** [comment]
We will be releasing an update that should fix this very shortly.

**Comment by ragrum** [comment]
In the mean time I've switched to Docker for Mac Stable channel, it hasn't this issue. More than happy to test the fix when available in Beta channel, thanks for the effort!

**Comment by justincormack** [comment]
The fixed version is out on the beta channel now - if you could test that this is the issue and unrelated to overlay that would be helpful.

**Comment by ragrum** [comment]
I can confirm that the mentioned issue is fixed in:

```
Version 1.12.3-rc1-beta29.1 (13437)
Channel: Beta
6514be4160
```

```
Server Version: 1.12.3-rc1
Storage Driver: overlay2
```

Thanks a lot for the quick fix! 👍

**Comment by justincormack** [comment]
Sorry we broke it!
