### ISSUE TITLE
Not possible to install/start docker

### ISSUE THREAD

**Issue by lukasfrank** [docker/for-mac#854]
### Expected behavior

Try to start docker initially
### Actual behavior

Docker dosen't start caused by a fatal error network error
### Information
- Diagnostic ID: C5645C57-4B95-4913-BFBC-D6A2A71361A6
### Steps to reproduce the behavior
1. Download latest docker version 
2. Move app to application folder
3. Try to lunch the application 
### Error log

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/C5645C57-4B95-4913-BFBC-D6A2A71361A6/20161027-092739.tar.gz
failure: Docker.qcow2 missing: the VM has never been started
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/xx/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/xx/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/xx/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/xx/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
[OK]     moby-console
[ERROR]  moby
         /Users/xx/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by samoht** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in C5645C57-4B95-4913-BFBC-D6A2A71361A6/20161027-092739.

The UI failed to communicate with the networking helper process. Deleting `/Library/PrivilegedHelperTools/com.docker.vmnetd` and restarting the application should help you. Please re-open that issue if your problem persist.

May be related to docker/for-mac#61
