### ISSUE TITLE
"Automatically check for updates" preference causes Fatal error

### ISSUE THREAD

**Issue by boxmein** [docker/for-mac#858]
### Expected behavior

Ticking or un-ticking "Automatically check for updates" will modify the setting, persist and not show any pop-up.
### Actual behavior

Ticking or un-ticking "Automatically check for updates" will cause an error.

![image](https://cloud.githubusercontent.com/assets/358714/19769394/da100bd6-9c63-11e6-8f3b-f0bc7748f853.png)
### Information

Diagnostic ID: 82AB32B3-DB0A-4DC7-8A3B-F0911B35B950
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Run Docker
2. Click on Docker icon in panel
3. Click on "Preferences"
4. Click on checkbox "Automatically check for updates"

However, after exiting and reopening Docker, the setting will be as if it was successfully changed.

**Comment by samoht** [comment]
Detected symptom of problem 'unsupported-sierra' in 82AB32B3-DB0A-4DC7-8A3B-F0911B35B950/20161027-163747.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
