### ISSUE TITLE
docker info hangs, restart does not work, on 5th factory reset today

### ISSUE THREAD

**Issue by haata** [docker/for-mac#859]
### Expected behavior

docker info shouldn't hang. Restarting docker should make it work again in all cases.
### Actual behavior

docker factory reset is required to run docker again. Only works for a while.
### Information

6A7A1072-5D9B-43C8-8FD8-A653C5B550A2

```
Docker for Mac: version: 1.12.3-rc1-beta29.1 (6514be4)
OS X: version 10.12 (build: 16A323)
logs: /tmp/6A7A1072-5D9B-43C8-8FD8-A653C5B550A2/20161027-105839.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```
### Steps to reproduce the behavior
1. Run docker container a few times
2. Attempt to run docker info, hangs
3. Try to restart
4. docker info still hangs

**Comment by neksa** [comment]
I had similar issue due to previous installation of docker.
Check your env with
 set|grep DOCKER
