### ISSUE TITLE
Docker not starting after installing on El Capitan

### ISSUE THREAD

**Issue by nathanhourt** [docker/for-mac#861]
### Expected behavior

Docker starts up normally and `docker info` returns the usual info
### Actual behavior

Docker is not starting, `docker info` replies
`Error response from daemon: dial unix /Users/nathan/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: no such file or directory`
### Information

Diagnostic ID: 1BEF06D1-0B48-4244-8AE7-2E18CD276325

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/1BEF06D1-0B48-4244-8AE7-2E18CD276325/20161027-165350.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[ERROR]  moby
         /Users/nathan/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

```
### Steps to reproduce the behavior
1. Install docker for mac
2. Start it
3. Watch the little whale in the system tray build and unbuild **_for...ev...er_**

**Comment by Jokersoft** [comment]
Almost same here
```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.12 (build: 16A323)
logs: /tmp/406E5697-E959-4636-8B90-A00383A6724F/20161031-111533.tar.gz
failure: com.docker.slirp is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ENOENT, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by samoht** [comment]
Detected symptom of problem 'processor-not-supported' in 1BEF06D1-0B48-4244-8AE7-2E18CD276325/20161027-165350.

Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install for more information.

**Comment by nathanhourt** [comment]
That is incorrect; I have run docker successfully on this hardware (in Yosemite, before upgrading to El Capitan).

**Comment by samoht** [comment]
This is very strange, as your logs contain:

```
Docker[com.docker.driver.amd64-linux][3565] <Notice>: vmx_init: processor not supported by Hypervisor.framework
```

Did you change something in your hardware settings maybe?

**Comment by nathanhourt** [comment]
I'm not sure... Did how OSX does virtualization change substantially between 10.10 and 10.11?

**Comment by samoht** [comment]
What hardware do you have? You can find that information in  "about this mac" :arrow_right: "system report" :arrow_right: "hardware". I can see if I can try to reproduce on a similar box.

**Comment by samoht** [comment]
You could also double-check what is the output of `sysctl kern.hv_support`? If it says 0 I am afraid we cannot do much. I don't see how upgrading from 10.10 to 10.11 could have changed that :-/

**Comment by nathanhourt** [comment]
`sysctl kern.hv_support` returns 1, so I assume that's OK. As to hardware, it's not apple hardware, so it's unlikely that you'll have a similar system. :P I now know the issue is in Hypervisor.framework though, so I'll probe around and see what I can figure out. Thanks. :)

**Comment by nathanhourt** [comment]
Finally figured this one out. Somehow intel virtualization got turned off in UEFI. Go figure.
