### ISSUE TITLE
Daemon not running after restart

### ISSUE THREAD

**Issue by ngpestelos** [docker/for-mac#863]
Please refer to `08059EC2-AC24-4E19-A917-532045FB9886`.

**Comment by samoht** [comment]
@ngpestelos do you still have that error? Your logs seems to indicate that `/usr/local/bin` is read-only:

```
Failed to unlink /usr/local/bin/docker symlink: Read-only file system
```

which seems to confuse the installer. Changing the permissions back to read-write should help. I am closing the issue, but feel free to re-open if you seem have difficulties to start Docker for Mac.
