### ISSUE TITLE
Docker not coming back up after restart

### ISSUE THREAD

**Issue by schmunk42** [docker/for-mac#864]
### Expected behavior

Docker coming back up after restart
### Actual behavior

```
docker ps
Error response from daemon: Bad response from Docker engine
```
### Information
- Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/2399EBB7-B444-4B74-918B-87BC7A3819DE/20161028-015836.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
``


### Steps to reproduce the behavior

  1. heavy container load
  2. click restart button

Workaround: Quit application and restart.

```

**Comment by dave-tucker** [comment]
Thanks for the report.
I've done some digging and found some errors, that may be unrelated to the problem you are having.

--------------------------------------------------------------------------------
Detected symptom of problem 'state-not-recoverable' in 2399EBB7-B444-4B74-918B-87BC7A3819DE/20161028-015836.

[INVESTIGATE THE ISSUE]

The following log matches:
```
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Warning>: dropped event syscall chmod_dir for /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks (bad lookup path)
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Warning>: dropped event syscall mknod_reg for /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks/index.html (mismatched syscall chmod)
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Error>: transfused: Event chmod /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks error: State not recoverable
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Error>: transfused: Event mknod /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks/index.html error: File exists
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Warning>: dropped event syscall chmod for /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks/index.html (bad lookup path)
Oct 27 13:51:20 Kraftbuch Docker[com.docker.osxfs][88065] <Warning>: dropped event syscall truncate for /Users/tobias/hrzg/git/herzog/planck-za6/vendor/composer/6168a677/FortAwesome-Font-Awesome-a8386aa/src/3.2.1/icon/tasks/index.html (mismatched syscall chmod)
```
---

/cc @dsheets as discussed, these may be benign, but the there are a LOT of them.

Unfortunately we've had some issues with log collection so I can't see why `docker` isn't coming back up.

Could you install the [Docker for Mac Beta Channel](https://docs.docker.com/docker-for-mac/) and send a diagnostic report when this next happens? Diagnostics are much better on recent Beta's and despite the name many users have found it more stable than stable 😉 

Please make sure to use 🐳  -> `Preferences` -> `Uninstall/Reset` -> `Uninstall` before switching channels. **WARNING: You may lose data by doing this. Either backup the Docker.qcow2 or `docker save/docker load` anything important from your old installation**

**Comment by ijc25** [comment]
@schmunk42 I've escalated this to the osxfs developers in our internal tracker (I'm sorry that it took so long). In the meantime if you could try the latest stable release (1.12.3) and report if you still see this issue that would be appreciated.

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by djs55** [comment]
We'll continue to work on the escalated issue even though this ticket has now been closed due to inactivity.
