### ISSUE TITLE
Docker for mac is not starting properly

### ISSUE THREAD

**Issue by astropanic** [docker/for-mac#866]
### Expected behavior

Docker for mac is starting properly

### Actual behavior

Docker for mac is not starting properly.
Instead of the whale icon in the bar, I see a spinner. I can't access any Docker menu item from the bar.

`ps aux | grep -i docker`

`3024   0.0  0.3  2594304  44640   ??  S    11:48AM   0:00.17 /Applications/Docker.app/Contents/MacOS/Docker`

After killing the unresponsive process and running from the CLI:

`/Applications/Docker.app/Contents/MacOS/Docker`
~~~shell
1477648504061372928 com.docker.docker Application version: 1.12.1 (12133)
1477648504061594112 com.docker.docker Administrator user: true
1477648504085444864 com.docker.docker OSX Version: Version 10.12.1 (Build 16B2657)
kern.hv_support: 1
1477648504278950912 com.docker.docker migrator: start migration process
1477648504283385088 com.docker.docker migrator: previous install detected
1477648504283412992 com.docker.docker migrator: previous version is 1.12.0-rc3-beta18
1477648504283484928 com.docker.docker migrator: no migration needed, you are good to go!
1477648504283501056 com.docker.docker migrator: successfully updated from version 1.12.0-rc3-beta18 to 1.12.1
1477648504284624128 com.docker.docker migrator: end of migration process
1477648504304291840 com.docker.docker event tracker initialized
1477648504306683904 com.docker.docker NSUserDefaults.synchronise() returned false
1477648504309253888 com.docker.docker NSUserDefaults.synchronise() returned false
1477648504312134912 com.docker.docker NSUserDefaults.synchronise() returned false
1477648504314866176 com.docker.docker NSUserDefaults.synchronise() returned false
1477648504314882048 com.docker.docker Bundle path: /Applications/Docker.app`
~~~
### Information

  Diagnose and Feedback is not available

  OSX 10.12.1
  Docker for mac 1.21.1

`docker version`

~~~
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
~~~

`env | sort | grep -i docker`

nothing there

### Steps to reproduce the behavior

See above

I opened another similar [ticket](https://github.com/docker/for-mac/issues/499) but it was closed without resolving the issue. Now I updated my OSX and downloaded a new Docker for Mac version, same behaviour so I'm creating this ticket.

**Comment by dave-tucker** [comment]
@astropanic I'm sorry about your first issue being closed without a fix.

Once you dragged the app to your `/Applications` folder and started it, what happened?
Did you see any dialog boxes saying that "We're whaly happy to see you" or asking for permissions to install our networking components? If not, there's a chance these may be stuck/hidden under other windows - you can used Mission Control (CTRL + ⬆️  on my Mac) to look for them.

A screenshot of what the menu bar looks like might also help.

Also, could you try running the following an posting the output back here?
` /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u`

**Comment by astropanic** [comment]
@dave-tucker , after dragging it to Applications, the standard warning appears, it is downloaded from the internet and if I want open it. After confirming, nothin more happens, besides showing me a growl notification saying I updated from a previous version. I can't make a screenshot of the menu bar, because there was nothing there. just when I hover with my mouse on the space, the OSX spinner showed up.

No windows were covered with other dialog windows or something like that.

I checked with `lsof` which files were used by this strange process trying to start Docker.
I killed the process, and removed those files.
I deleted from my system every folder and file related to docker, which I found via `find`.

It took me some time today, but now after dragging the Docker icon into the Applications folder, I see the question about running with root permissions, and after accepting that and installing everything is working fine.

~~~shell
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
~~~

~~~
OS X: version 10.12.1 (build: 16B2657)
Docker.app: version: 1.12.1 (2d5b4d9)
Local time: Fri Oct 28 13:40:59 CEST 2016
UTC:        Fri Oct 28 11:40:59 UTC 2016
Timestamp:  20161028-134059
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      slirp
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Docker logs are being collected into /tmp/BFC91888-3C42-4CC5-9589-33353410F844/20161028-134059.tar.gz
Your unique id is: BFC91888-3C42-4CC5-9589-33353410F844
Please quote this in all correspondence.
~~~

**Comment by dave-tucker** [comment]
Thanks @astropanic

Glad you managed to get it working in the end. I'll take a look at the logs and see if I can figure out what when on but I suspect there was some bad state from a previous install that caused this to happen.
