### ISSUE TITLE
OSX 10.12.1: docker daemon cannot start

### ISSUE THREAD

**Issue by michalcoka** [docker/for-mac#867]
### Expected behavior

Docker can start up
### Actual behavior

Cannot start docker for mac

Diagnostic ID: 32016D5C-592F-4E8F-9F41-E19A9AA04F8B

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/32016D5C-592F-4E8F-9F41-E19A9AA04F8B/20161028-154745.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by thazarik** [comment]
Same here. Docker intermittently stops responding, when starting or attaching to a container.

What finally worked for me was to reset docker to factory defaults, then remove /private from preferences -> File Sharing. YMMV.

**Comment by mchiang0610** [comment]
@michalcoka @thazarik Thank you for the help. Do you have more information regarding this issue? I'm trying to reproduce this.

**Comment by mklatsky** [comment]
Resetting to factory defaults worked for me.

Docker:
Version 1.12.3-beta29.2 (13499)
Channel: Beta
902414df0c

OSX: 10.12.1 (16B2555)

**Comment by samoht** [comment]
@michalcoka Does Diagnose & Feedback from the :whale: menu work? Could you please run and upload the diagnostics to our server? Thanks!

**Comment by michalcoka** [comment]
@samoht Diagnose & Foeedback work, I'm just not able to upload the result..
ID 32016D5C-592F-4E8F-9F41-E19A9AA04F8B: Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
possible root cause extracted from the log file?
`
Nov  4 09:25:20 BTSM60268173A Docker[com.docker.docker][31630] <Notice>: Symlinks are valid.
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.docker][31630] <Notice>: com.docker.osx.hyperkit.linux launched with PID 31649
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.docker][31630] <Notice>: NSUserDefaults.synchronise() returned false
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.osx.hyperkit.linux][31649] <Notice>: Acquired task manager lock
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.osx.hyperkit.linux][31649] <Notice>: Maximum number of file descriptors is 10240
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.frontend][31650] <Critical>: dial unix /Users/myUser/Library/Containers/com.docker.docker/Data/s20: connect: connection refused
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.osx.hyperkit.linux][31649] <Notice>: Removing leaked pidfile com.docker.hyperkit
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.osx.hyperkit.linux][31649] <Notice>: Starting com.docker.db, com.docker.osxfs, com.docker.slirp, com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.docker][31630] <Error>: frontend process failed
Nov  4 09:25:21 BTSM60268173A Docker[com.docker.osx.hyperkit.linux][31649] <Notice>: Start com.docker.db (pid 31654)
`

**Comment by samoht** [comment]
Thanks I got your logs.

---

Detected symptom of problem 'malloc-corruption' in 32016D5C-592F-4E8F-9F41-E19A9AA04F8B/20161104-095547.

Corruption has been detected in the malloc heap. If you are comfortable running a beta (we still do QA on it), you could give that a try to the latest beta (Beta29) where this issue should have been fixed.

May be related to docker/for-mac#819

**Comment by samoht** [comment]
The fix is now released on both the beta and stable channels so I am closing the issue. Please re-open (or open a new one) with a new diagnostic ID you still have that problem.
