### ISSUE TITLE
Building OpenNetworkLinux yields unresponsive container

### ISSUE THREAD

**Issue by HarryWeppner** [docker/for-mac#868]
### Expected behavior

Container completes build.
### Actual behavior

Container becomes unresponsive, i.e.
- `docker ps` shows it is `Up`
- `docker exec -it <cmd> <container_id>` hangs
- `docker stop <container_id>` hangs (unable to stop it)
### Information

```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/BC71B46C-FACD-4D89-8C0D-B26FE75FBF4E/20161028-102715.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
### Steps to reproduce the behavior
- https://opennetlinux.org/docs/build

```
git clone https://github.com/opencomputeproject/OpenNetworkLinux
cd OpenNetworkLinux
make docker
```

**Comment by samoht** [comment]
Does Diagnose & Feedback from the :whale: menu work? Could you please run and upload the diagnostics and post your diagnostic ID back here?

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
