### ISSUE TITLE
docker logs -f does not follow 

### ISSUE THREAD

**Issue by testn** [docker/for-mac#870]
### Expected behavior

docker logs -f should tail the log
### Actual behavior

docker logs -f starts and stops at a random point in the log file
### Information

Version 1.12.3-rc1-beta29.1 (13437)

Docker for Mac: version: 1.12.3-rc1-beta29.1 (6514be4)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/E0C352F7-9F97-4EE6-8D28-F702E8FB734F/20161028-165015.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
- A reproducible case if this is a bug, Dockerfiles FTW
- Page URL if this is a docs issue or the name of a man page
### Steps to reproduce the behavior

Just perform docker logs -f <start_container_id>

**Comment by samoht** [comment]
This seems to be a duplicate of #307 which I just closed, so I am closing this one too.

**Comment by dougngo** [comment]
Im on 1.13 stable and can still reproduce this... This this update fix the issue for anyone?

**Comment by testn** [comment]
I can still reproduce this in 1.31. Please reopen.

**Comment by janvojt** [comment]
This is also happening to me on Linux Debian with Docker version 17.04.0-ce, build 4845c56.

**Comment by asprega** [comment]
I'm on Sierra 10.12.4, Docker stable 17.03.1-ce, and CAN reproduce consistently.
