### ISSUE TITLE
"docker exec"s are hanging

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#871]
### Expected behavior

Exiting a `docker exec` `bash` should fully exit.
### Actual behavior

```
$ docker exec -ti mycontainer bash
[root@4a9b3bc863dc /]# exit
(...hangs here indefinitely...)
(...after I restart docker...)
curl: (56) Recv failure: Connection reset by peer
Error response from daemon: Bad response from Docker engine
```
### Information

3E549EA9-14E0-4793-B0D4-4EDDFDF6FB3B

Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/3E549EA9-14E0-4793-B0D4-4EDDFDF6FB3B/20161029-233021.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
### Steps to reproduce the behavior
1. Unknown what leads to this happening, but when it does all any attempt to exit from a `docker exec` hangs

**Comment by ijc25** [comment]
@jamshid I tried to reproduce with beta30 with:
```
 docker run -d debian sleep 30m
```
followed by
```
docker exec -ti 961020e3b6b5 bash
```
and cannot reproduce:
```
$ docker exec -ti 961020e3b6b5 bash
root@961020e3b6b5:/# exit
exit                                                                                                                                                                                                       
$ 
```

There might be something interesting or different about your `mycontainer`. Can you provide any details?

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
