### ISSUE TITLE
Docker failing to start on startup, or restart of application

### ISSUE THREAD

**Issue by Toddzio** [docker/for-mac#875]
### Expected behavior
Docker Opens
### Actual behavior
Docker hangs on startup
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/F6350572-5C51-4E69-A084-BC0D676F8F94/20161031-091740.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1. ... Turn on computer.
  2. ... Restart Docker

**Comment by mangelajo** [comment]
Same here: 94646CA0-8842-41A7-B0F2-48F2E12658D9

**Comment by samoht** [comment]
@Toddzio 

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

**Comment by samoht** [comment]
@mangelajo your issue is different:

---
Detected symptom of problem 'malloc-corruption' in 94646CA0-8842-41A7-B0F2-48F2E12658D9/20161101-132317.

Corruption has been detected in the malloc heap. This is a known issue which is under investigation.

May be related to docker/for-mac#819
