### ISSUE TITLE
Docker for Mac does not start

### ISSUE THREAD

**Issue by dsng9q843hpaurghapuhga** [docker/for-mac#876]
### Expected behavior
Docker for Mac version 1.12.1 should start normally on my mac running OSX 10.12.1

### Actual behavior
It does not start 
### Information

I have re-installed multiple times and it still will not start
[50B74E9F-29BD-4E17-BDCB-C84A4F22D772.zip](https://github.com/docker/for-mac/files/563077/50B74E9F-29BD-4E17-BDCB-C84A4F22D772.zip)

### Steps to reproduce the behavior

  1. Install docker for mac
  2. start docker for mac

**Comment by dsng9q843hpaurghapuhga** [comment]
I think the problem is admin privileges.  I just tried starting docker from a user who has admin privileges and Docker starts normally.

**Comment by mchiang0610** [comment]
@dsng9q843hpaurghapuhga reading the logs, it seems like the daemon failed to start for some reason. You do need admin privileges for Docker for Mac to function correctly. 

Closing this issue for now. 

Thanks!
