### ISSUE TITLE
Unable to connect to Daemon -- MacOS 10.12.1 / Docker 1.12.1

### ISSUE THREAD

**Issue by zbuc** [docker/for-mac#877]
### Expected behavior

Able to connect to daemon, as the desktop widget and process listing seem to show Docker's daemon running.

### Actual behavior

`docker ps` results in the following error:

```
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2657)
logs: /tmp/0B058A57-5F0B-41C3-8582-6CA8A768A124/20161031-221013.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

I verified the `docker` command line binary seems to be correct:

```
$ which -a docker
/usr/local/bin/docker
/usr/local/bin/docker
/usr/local/bin/docker

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by samoht** [comment]
Do you have any `DOCKER_` environment variables set? These are set by toolbox installations but need to be unset for Docker for Mac to work properly. See https://docs.docker.com/docker-for-mac/troubleshoot/#/workarounds-for-common-problems

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
