### ISSUE TITLE
Docker hangs regularly; requires restart

### ISSUE THREAD

**Issue by onmishkin** [docker/for-mac#879]
Periodically (once every day or so) I notice my containers are unresponsive. I do "docker ps" which hangs. I assume the Docker daemon is hung. I have to quit Docker, wait a minute or so, and restart Docker to get it working again.

Nothing interesting appears to show in the Mac Console app. Often the problem happens overnight (i.e., I see it when I first start working again in the morning). The Mac wasn't asleep during that interval--just idle.

Diagnostic ID: FF7D4587-F19D-49D1-96B0-EBC7133A7A18

Version: 1.12.1

**Comment by mchiang0610** [comment]
@onmishkin Thanks for letting us know the issue. Are you able to help provide steps to reproduce this? 
I'm going to close this for now and reopen once we have more information. 

Thank you for all the help! We appreciate it.

**Comment by onmishkin** [comment]
Sorry, I don't know a sequence of steps to repro the problem. All I know is that I often find things are in a broken state at the beginning of my work day and they had been working fine at the end of my previous work day and the machine had been basically idle between those points in time. During that time I'd have had anywhere from 5-10 containers running, but no explicit Docker operations (e.g., creating, starting, stopping, or removing containers) had been invoked.

Is there anything I can do to try to collect more data about exactly what state Docker is in when the problem manifests?

Thanks.
