### ISSUE TITLE
docker on mac start error due to disk check failure

### ISSUE THREAD

**Issue by kaulie** [docker/for-mac#88]
### Information

Diagnostic ID: 8A59AA5D-CAB7-418B-A5FF-E18BFBD0A1EA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/gaolei/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/8A59AA5D-CAB7-418B-A5FF-E18BFBD0A1EA/20160803-111315/qemu-img-check.stdout 2> /tmp/8A59AA5D-CAB7-418B-A5FF-E18BFBD0A1EA/20160803-111315/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
Thanks for your report!

Unfortunately I can't seem to download the diagnostics bundle-- perhaps the upload failed? Are you behind an HTTP proxy? (There is a known bug where the diagnostics upload will fail if behind a proxy)

There have been a number of important bug fixes in recent betas including
- a fix for `flush` which could occasionally cause corruption if the power is lost
- a fix which prevents multiple hypervisors writing to the same file (see #71)

These fixes will be in the next stable update.

Could you upgrade to a beta and open a fresh ticket if the problem occurs?
