### ISSUE TITLE
DNS not respecting search domain

### ISSUE THREAD

**Issue by bergman** [docker/for-mac#880]
### Expected behavior
DNS lookups should respect search domain of `/etc/resolv.conf` or `scutil --dns` on host computer.

### Actual behavior
search domain is ignored.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/24B94A7C-1045-451D-8684-B2DE5A7C3D4C/20161101-134914.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
  - Dockerfile:
```
FROM ubuntu
RUN apt-get update && apt-get install -y iputils-ping

RUN ping -c1 internaldomain.mydomain.net
RUN ping -c1 internaldomain
```

### Steps to reproduce the behavior

  1. `ping -c1 internaldomain` works on host computer, gives regular ping output
  2. `docker build .`, the first ping with the explicit domain and search domain given works but the second one fails.
```
Step 3 : RUN ping -c1 internaldomain.mydomain.net
 ---> Running in b239b8bcfd1d
# normal ping output redacted
 ---> 5e991611e800
Removing intermediate container b239b8bcfd1d
Step 4 : RUN ping -c1 internaldomain
 ---> Running in 8784b75b0ec9
ping: unknown host internaldomain
The command '/bin/sh -c ping -c1 internaldomain' returned a non-zero code: 2
```

**Comment by bergman** [comment]
I can reproduce this on 1.12.3-beta30 (7314181) too

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/24B94A7C-1045-451D-8684-B2DE5A7C3D4C/20161115-143150.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by ijc25** [comment]
I can't see any diagnostics with UUID 24B94A7C-1045-451D-8684-B2DE5A7C3D4C on our servers. Could you please run Diagnose & Feedback from the :whale: menu, select Diagnose & Upload, and paste the results of the diagnostic run (including diagnostic ID) back here? This will help us understand what is happening with the Docker application. Thanks!

**Comment by bergman** [comment]
Uploaded now with UUID 24B94A7C-1045-451D-8684-B2DE5A7C3D4C

**Comment by ijc25** [comment]
@bergman thanks. I can see in your logs that the application has correctly figured out your `mydomain.net` and appears to have passed it as a search domain to the VM, where it appears in `/etc/resolve.conf`.

Looking at the tracing I don't see any attempted lookups which are not  for some `foo.mydomain.net` or well known public ones (google, docker hub etc).

Would you mind double checking that you can still repro this with beta30 and then uploading (yet) another diagnostic right after you have done so? If you can disclose a specific `foo` part of the `foo.mydomain.net` which you used to double check then that would be useful in helping to pinpoint an example of the issue in the logs. In fact, even using literal+nonexistent `foo` might suffice since we should then see the various lookups failing.

**Comment by bergman** [comment]
I uploaded another one just now, you can search for `debmirror` which is the hostname I was trying to look up (with and without full domain)

**Comment by ijc25** [comment]
@bergman thanks, I can see it performing lookups for `debmirror.DomainName` (that literal string) and in the new diagnostic that is what is written to the VM's `/etc/resolv.conf` too.

Interestingly `DomainName` is the _keyname_ in the SC database which contains your actual `mydomain.net` as the _value_. Looks like something is getting confused!

I have escalated this to our internal tracker. Thanks for your report.

**Comment by bergman** [comment]
I tried this again with a later beta, can't remember the version number right now. It worked a few times but was very flaky. If I started a bash shell in a container I could ping any host once and it would look it up correctly but subsequent pings would all fail, even for the same host.

I'm giving up on this for now and going back to docker-machine.

**Comment by honnix** [comment]
this seems to have been fixed in stable version, at least 1.13.0 (15072)

**Comment by honnix** [comment]
hmm, still a bit of flaky. occasionally I need to restart docker to get it work.

**Comment by samoht** [comment]
I am closing this ticket as we believe the main issue to be fixed on both the stable and beta channels. @honnix please open a different issue (with a diagnostic ID) if you see something strange, so that we can investigate and follow up. Thanks!
