### ISSUE TITLE
Fails randomly after a few minutes of usage on Sierra update.

### ISSUE THREAD

**Issue by aardelean** [docker/for-mac#885]
### Expected behavior
To run idnefinetely
### Actual behavior
Fails
### Information

Diagnostic ID: B40F11D3-3B50-4860-A0DE-A78FDBB62DB0
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. start docker daemon
2.wait 5-10 minutes until it fails with error about bad response json vmstats

**Comment by samoht** [comment]
Detected symptom of problem 'unsupported-sierra' in B40F11D3-3B50-4860-A0DE-A78FDBB62DB0/20161102-133727.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
