### ISSUE TITLE
Docker 1.12.3 swarm subnetwork --opt encrypted

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/for-mac#888]
Docker service fails to create a valid container 
```
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

I create a network
`docker network create --driver overlay --subnet 10.0.9.0/24 --opt encrypted subnetwork
`
i start swarm
`docker swarm init`

i create a service attached to this network
`docker service create --replicas 1 --network subnetwork hello-world`

```
docker service ls
2odve7wxup04  berserk_poincare   0/1       hello-world        
```                          

```
docker service ps 7dztjruhkcyx
ID                         NAME                     IMAGE        NODE  DESIRED STATE  CURRENT STATE            ERROR
2l5xh5r37sgfistkykh28xqdv  infallible_minsky.1      hello-world  moby  Ready          Preparing 2 seconds ago  
cufe0tdl6v0er2fp718ege503   \_ infallible_minsky.1  hello-world  moby  Shutdown       Failed 3 seconds ago     "starting container failed: ca…"
3uovrxr6ur4jexln58s73hlg0   \_ infallible_minsky.1  hello-world  moby  Shutdown       Failed 9 seconds ago     "starting container failed: Ad…"
24akb0gnpghqvlehu3hbwe54g   \_ infallible_minsky.1  hello-world  moby  Shutdown       Failed 15 seconds ago    "starting container failed: fa…"
6b5bmewjuofkv2vy1jzrdmzm4   \_ infallible_minsky.1  hello-world  moby  Shutdown       Failed 21 seconds ago    "starting container failed: ca…"
```

I don't know where i could find the full error logs

**Comment by samoht** [comment]
Running:

```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose
```

will generate a diagnostic tarball that you can inspect if you wish. Use `-u` to upload the diagnostic tarbal to our server if you want us to investigate the issue as well.

**Comment by justincormack** [comment]
I think there is an issue with encrypted networks trying to do a `modprobe` and failing when this is not needed, that will be fixed in docker 1.13, see https://github.com/docker/libnetwork/pull/1502

**Comment by rogaha** [comment]
@sylvainmouquet can you please try it with the newer version `1.13-rc1` and let us know how it goes?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
