### ISSUE TITLE
Installation succeeded but docker commands don't work

### ISSUE THREAD

**Issue by tshrklr** [docker/for-mac#889]
### Expected behavior
`docker ps` works after a fresh install.

### Actual behavior

Basic docker commands don't work from native terminal or iTerm.
Diagnostic ID: 847E91F5-5857-4876-8754-C5A2CCC79BE8

### Information
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.11.4 (build: 15E65)
logs: /tmp/847E91F5-5857-4876-8754-C5A2CCC79BE8/20161102-122103.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Diagnostic ID: 847E91F5-5857-4876-8754-C5A2CCC79BE8

**Comment by samoht** [comment]
Please check that you dont have any `DOCKER_*` environment variable set (this could happen if you previously installed toolbox).

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
