### ISSUE TITLE
I/O Errors within docker

### ISSUE THREAD

**Issue by mikeage** [docker/for-mac#89]
### Expected behavior
Disk available
### Actual behavior
IOError; errno 107
### Information
I also saw "Error response from daemon: dial unix /Users/mikemi/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused" on STDOUT.
I'm not sure what other logs to provide; please let me know what would be helpful

Diagnostic ID: 0BD2EAE6-3FE6-424D-A2C7-237CE452ACB0
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce
This occurred while using bitbake for a rather deeply nested compilation (proprietary system, so I can't share exact instructions to reproduce)

**Comment by djs55** [comment]
Thanks for your report! From the logs it looks like an invariant inside `com.docker.osxfs` was violated, this was detected, and `com.docker.osxfs` quit-- probably causing the I/O errors. Next the other programs were restarted.

I've filed an issue against `com.docker.osxfs` and we'll investigate. Does this happen a lot? Or is it quite rare?

**Comment by dsheets** [comment]
I believe this issue was resolved in Beta 23. Could you please try again with Beta 23 or later and let us know if you still see the issue? Please feel free to re-open this issue if the same behavior recurs. If you find a new problem or one that looks different from this problem, please open a new issue.

Thanks for using Docker for Mac!

**Comment by mikeage** [comment]
Indeed, I have not seen this recently.
