### ISSUE TITLE
docker compose ps/ERROR: Bad response from Docker Engine

### ISSUE THREAD

**Issue by kriswill** [docker/for-mac#892]
### Expected behavior
`docker-compose ps` should list container status for docker-compose.

### Actual behavior
`ERROR: Bad response from Docker engine`

### Information
```
Docker for Mac: version: 1.12.3-beta29.2 (902414d)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/CAD13AC8-6D66-46B7-8792-98597B5E3DCA/20161102-131559.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. seems to happen after sleep mode, but may be a red herring, because it has happened while working.
  2. run `docker-compose ps` in a path with a docker-compose.yml.

**Comment by dsheets** [comment]
Has this occurred on a recent beta? Can you reproduce on beta 29.3? I see that you were on beta 26.2 and then beta 28 until recently.

**Comment by kriswill** [comment]
@dsheets I just upgraded, and forced the Mac to sleep, and it was OK coming back.  I will monitor it and let you know if it breaks again.  Thanks!

```
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/CAD13AC8-6D66-46B7-8792-98597B5E3DCA/20161103-113625.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by kriswill** [comment]
@dsheets Hi, I just had the docker engine disconnect happen again.  I was away from my machine for an extended period (~2 hours), came back and the same problem occurred.

```sh
→ dc ps # 2 hours ago
            Name                          Command             State           Ports          
--------------------------------------------------------------------------------------------
localdockermysqlimage_mysql_1   docker-entrypoint.sh mysqld   Up      0.0.0.0:3306->3306/tcp 

→ dc ps # after coming back (computer sleep)
ERROR: Bad response from Docker engine
```

**Comment by samoht** [comment]
Could you upload your diagnostic logs after the new crash? Thanks!

**Comment by kriswill** [comment]
@samoht I just had the issue present, without any OS sleep.  

```
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/CAD13AC8-6D66-46B7-8792-98597B5E3DCA/20161104-125530.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```
it says it failed to upload the log, not sure why...
I can post it to a gist if you like?

**Comment by kriswill** [comment]
I uploaded the Log file to my dropbox:

https://dl.dropboxusercontent.com/u/3191054/docker-logs/20161104-125530.tar.gz

**Comment by samoht** [comment]
Thanks, you logs have been sent successfully to our server, so I have removed the link to your dropbox. I am investigating now.

**Comment by samoht** [comment]
Sorry I can't see a clear error in your logs... I see some strange occurrences of:
```
CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
```
but I have no idea what the mean...

**Comment by kriswill** [comment]
The symptoms have subsided.  I haven't had the issue reoccur for a few days.
