### ISSUE TITLE
Can't restart docker after last update to 1.12.1  build: 12133

### ISSUE THREAD

**Issue by aiacovella** [docker/for-mac#893]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
Please create a new issue with a diagnostic ID, as explained on https://docs.docker.com/docker-for-mac/troubleshoot/#/diagnose-problems-send-feedback-and-create-github-issues
