### ISSUE TITLE
cannot find an icon to open a docker terminal

### ISSUE THREAD

**Issue by phant1** [docker/for-mac#895]
![screen shot 2016-11-03 at 3 03 35 pm](https://cloud.githubusercontent.com/assets/20304284/19983124/b9a1314a-a1d6-11e6-9d18-adfb8eb5d578.png)
### Information
I think i have successfully installed the Docker for Mac... Please see attached screen capture.  but i can't seem to find the docker terminal icon to open it

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by samoht** [comment]
You should just be able to use any terminal, for instance `Terminal.app` which is shipped with macOS.

**Comment by phant1** [comment]
Ok, thank you…
