### ISSUE TITLE
не запускается докер

### ISSUE THREAD

**Issue by RSivakov** [docker/for-mac#897]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by djs55** [comment]
Unfortunately we can't help without being able to see your logs.

Please use:

Menu -> Diagnose & Feedback -> Diagnose & Upload -> Open issue

and include the **Diagnostic ID** (the text which looks like '2922125F-D698-4729-879D-7080AC8BE10D')

Thanks for your patience!

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
