### ISSUE TITLE
Launch Docker.app automatically when using CLI

### ISSUE THREAD

**Issue by yangm97** [docker/for-mac#898]
### Expected behavior
If Docker.app is not running when a user tries to interact with the CLI, issue a `open -a Docker` automatically.

### Actual behavior
docker-cli asks the user to manually launch Docker.app.

### Information
N/A

### Steps to reproduce the behavior
  1. Interact with docker-cli while Docker.app is not running
  2. ...
  3. Profit

**Comment by ijc25** [comment]
@yallop @djs55 did either of you escalate this?

**Comment by samoht** [comment]
Thanks, I have escalated your feature request to our engineering team.

**Comment by martinm82** [comment]
About which docker-cli are we talking here? Does Docker for Mac has as well a cli interface?

**Comment by yangm97** [comment]
So?

**Comment by guillaumerose** [comment]
We talk about this feature with the whole team and we think this will lead to many others problems. 
For instance, we would need to modify and build our own docker/cli.

Thanks for the suggestion
