### ISSUE TITLE
docker for mac fails to start

### ISSUE THREAD

**Issue by hansworse** [docker/for-mac#903]
### Expected behavior
Docker starts and is usable.

### Actual behavior
Startup fails with Fatal Error

"Communication with networking components failed."

### Information
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/6B66CCFB-638B-4F69-A0A4-6EF752D234BF/20161106-224623.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/bj6/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/bj6/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/bj6/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[OK]     moby
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running

### Steps to reproduce the behavior
Start docker for mac...

**Comment by djs55** [comment]
Thanks for your report.

The logs contain
```
Nov  6 22:40:20 ... <Critical>: Communication with networking components failed.
```
This means that the UI failed to communicate with the networking helper process.

Try the following steps:
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac

Hopefully this will (re-)install the networking helper process properly. Please re-open this issue if your problem persists.

May be related to docker/for-mac#61
