### ISSUE TITLE
vmstateevent invalid json: 

### ISSUE THREAD

**Issue by ptaillard** [docker/for-mac#905]
### Actual behavior
Message displayed:
"Fatal Error: 
vmstateevent invalid json: "
It seems to have an empty string instead of valid json
### Information

Diagnostic ID: 6BE8F529-9B3B-4F9C-9565-9C58D8FCD1C7
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

**Comment by djs55** [comment]
Thanks for your report.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

Related to docker/for-mac#561
