### ISSUE TITLE
docker for mac stuck

### ISSUE THREAD

**Issue by brmzkw** [docker/for-mac#907]
### Actual behavior

I'm running the beta version of docker for mac. I came back at work after the weekend, and docker is stuck.

Running `docker ps` doesn't respond.

`sudo dtruss docker ps` displays:

```
[...]
write(0x4, "GET /v1.24/containers/json HTTP/1.1\r\nHost: docker\r\nUser-Agent: Docker-Client/1.12.3 (darwin)\r\n\r\n\0", 0x60)		 = 96 0
kevent(0x5, 0x0, 0x0)		 = 1 0
select(0x0, 0x0, 0x0, 0x0, 0xB0080DE8)		 = 0 0
[after select timeout]
select(0x0, 0x0, 0x0, 0x0, 0xB0080DE8)		 = 0 0
[... and so on]
```

I tried several things to solve the issue:
* click on "restart": Docker didn't start, and was marked as "starting" for several minutes.
* quit and relaunch docker: Docker was marked as "started" but `docker ps` didn't respond (same issue than above).
* try to attach to the VM's serial with `screen /Users/<username>/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` and restart docker. The VM did shutdown and restart, and eventually Docker worked again.

### Information

```
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.10.5 (build: 14F2009)
logs: /tmp/FC49437F-1C9C-41FF-B167-E5B397BDC292/20161107-100200.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by djs55** [comment]
Thanks for your report. Despite the error about uploading diagnostic data, the data was uploaded successfully. Running a diagnostic tool over your logs does find evidence of a volume sharing problem:

Detected symptom of problem 'invariant-violated' in FC49437F-1C9C-41FF-B167-E5B397BDC292/20161107-100200.

(FYI @dsheets)

The following log matches:
```
Nov  3 10:26:16 biwork Docker[com.docker.osxfs][532] <Error>: WATCH TREE REMOVAL EXISTENCE INVARIANT VIOLATED
Nov  3 10:26:16 biwork Docker[com.docker.osxfs][532] <Error>: WATCH TREE REMOVAL EXISTENCE INVARIANT VIOLATED
Nov  3 10:26:16 biwork Docker[com.docker.osxfs][532] <Error>: WATCH TREE REMOVAL EXISTENCE INVARIANT VIOLATED
```
However I'm not sure if this can explain the system becoming stuck though.

Suspiciously the in-VM diagnostics dump is empty which suggests either a bug either in the diagnostics code or perhaps the virtio connections to the VM became wedged -- this would explain both docker APIs hanging and the fact that the VM was still responsive on the terminal.

I notice the Moby logs (which are written to the host over a virtio connection) stop on November 6th but the host logs continue to November 7th. This sounds like further evidence that something went wrong inside the VM causing the log writing to stop.

I don't think I can make more progress without either a repro or the VM logs from after the lockup. I'll try to reproduce it myself this weekend, but if it happens again could log into the VM in this stuck state and execute

- `dmesg`
- `ps axf`
- `mount`
- `ls /var/log`

-- I'm hoping there will be an error message somewhere there, although the `mount` or `ls` commands might hang.

Thanks for your patience.

**Comment by brmzkw** [comment]
Okay, I'll update this ticket if the problem occurs again.

Thanks a lot,

**Comment by dsheets** [comment]
The invariant violations occurred during a run of 1.12.1 which was upgraded to Beta 29.3 32 seconds later. Beta 29.3 fixed the issue.

**Comment by brmzkw** [comment]
Glad to hear :) I close the issue then.

Thanks a lot
