### ISSUE TITLE
Add radio button to enable or disable proxy settings in the UI

### ISSUE THREAD

**Issue by LaurentGoderre** [docker/for-mac#908]
I switch network often on my Mac and now have to remove and re-add my proxy settings constantly. It would be nice to have a radio button to enable or disable proxy settings so that they are not lost everytime.

**Comment by dsheets** [comment]
Thanks for your suggestion! We have a number of ideas about configuration management and I will put your enhancement request in that work stream.

**Comment by dave-tucker** [comment]
@LaurentGoderre sorry for the long period of silence on this issue. We now have a radio button that allows you to switch from `No Proxy` to either `Auto-detect` or `Manual` proxy settings 🎉 
I've found a bug where the manual settings won't persist after switching to no proxy and back again and I've escalated to our UI team to see when we can get this fixed!

**Comment by LaurentGoderre** [comment]
If you have a seperate issue for that bug I am good with closing this because the new release works perfectly for me! You guys are awesome!

**Comment by dave-tucker** [comment]
@LaurentGoderre 👍 thanks!
