### ISSUE TITLE
Docker won't start "Docker starting..."

### ISSUE THREAD

**Issue by wbednarski** [docker/for-mac#909]
### Expected behavior
Working Docker

### Actual behavior
Docker won't start. It says "Docker starting..."
### Information

```
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/9E13051A-5566-4D34-8D1B-0CF770CE128D/20161107-171207.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```
### Steps to reproduce the behavior
I ran `docker-compose up` and my MBP crashed.

**Comment by ramon** [comment]
same here...

--------------------

Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.10.5 (build: 14F1509)
logs: /tmp/B5CA040E-7343-405B-BCB5-5F1010298ACB/20161108-104824.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by djs55** [comment]
@wbednarski In your logs I can see
```
Nov  7 16:02:46 ... Docker[com.docker.driver.amd64-linux][2499] <Notice>: Docker is responding
```
which means that everything looks ok. I then see a harmless "ping" event:
```
Nov  7 17:02:22 ... Docker[com.docker.docker][2481] <Notice>: Analytics: Sent heartbeat event.
```
but then 3 minutes later I see a re-launch of the app:
```
Nov  7 17:05:13 ... Docker[com.docker.helper][319] <Notice>: AppDelegate: launching...
```
and this includes deleting "leaked" pidfiles, suggesting that all the subprocesses were killed:
```
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.driver.amd64-linux
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.hyperkit
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.osxfs
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.slirp
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.osx.hyperkit.linux
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Removing leaked pidfile com.docker.db
Nov  7 17:05:16 ... Docker[com.docker.osx.hyperkit.linux][420] <Notice>: Starting com.docker.db, com.docker.osxfs, com.docker.slirp, com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux
```
The docker daemon then unfortunately fails to start because the containers directory has been corrupted. Perhaps the unexpected shutdown of the processes (or the host?) left it in a bad state.

As a workaround you can reset to a clean state with

:whale: menu -> Uninstall / reset -> Reset to factory defaults

Unfortunately this will delete local images and containers but it should get you working again.

@wbednarski do you recall if your Mac crashed or lost power? (Or something else?)

**Comment by djs55** [comment]
@ramon I think your diagnostics data really did fail to upload. Could you try again and open a fresh ticket? Thanks!

**Comment by ramon** [comment]
@djs55 new ticket opened #915.

**Comment by lukebergts** [comment]
I commented in #915 as well but this looks like the same issue that I am seeing. 

Diagnostic id - 493978B4-86A8-4D52-95A8-2F7CF86A67FC

**Comment by rogaha** [comment]
thanks for the update @lukebergts
