### ISSUE TITLE
No Docker support on MacPro4,1

### ISSUE THREAD

**Issue by timrutter** [docker/for-mac#910]
### Expected behavior
For Docker to run properly

### Actual behavior
Docker fails to start
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support

### Information
The MacPro4,1 has two Intel Xeon X5650 which fully support VT-x, VT-d & EPT
http://ark.intel.com/products/47922

VMware Fusion runs without a problem, I can even run Docker in a Linux VM

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/328725EB-853F-45BA-AA51-CBA70E7D712E/20161107-231513.tar.gz
failure: sysctl -a reports no hypervisor support
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[ERROR]  virtualization kern.hv_support
         sysctl -a reports no hypervisor support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[ERROR]  disk
         Docker.qcow2 missing: the VM has never been started
[OK]     system
[OK]     app
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     virtualization VT-X
[ERROR]  db
         /Users/user/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/timrutter/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/user/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/user/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     logs
[OK]     env
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     moby-console
[ERROR]  moby
         /Users/user/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior
Start Docker
Error

**Comment by ijc25** [comment]
The OSX kernel is telling us that it doesn't support the `Hypervisor.framework` on your hardware in its current configuration for some reason. VMware uses a different virtualisation mechanism which does not rely on the OSX provided functionality (but which does rely on things such as loadable kernel modules, which we want to steer clear of).

Unfortunately there is nothing we can do about the lack of `Hypervisor.framework` support in docker for mac itself. You might find there are options in your the firmware configuration screens which enable the hardware functionality (I believe this was the case for h/w produced shortly after virt extensions were added).

If you find no such options then I'm afraid you will have to approach Apple for support in diagnosing why OSX does not support the `Hypervisor.framework` on your system and possibilities for enabling it.

Sorry I can't be more helpful than that.
