### ISSUE TITLE
 Container clocks dont advance when a Mac host resumes

### ISSUE THREAD

**Issue by entzik** [docker/for-mac#918]
I get the exact same issue as described in https://github.com/docker/docker/issues/27711 but on the mac. Whenever my mbp wakes up from hibernation (i.e. I open the lid) and I test the time in containers I get the time of the moment I closed the lid.
My environment is:
- MacBook Pro (Retina, 15-inch, Late 2013)
-  OS X 10.11.5
-  Docker Stable  - Version 1.12.1 (build: 12133) 2d5b4d9c3daa089e3869e6355a47dd96dbf39856

**Comment by justincormack** [comment]
See #17 and #693

**Comment by ijc25** [comment]
Closing as a dup of #17 and #693. Please subscribe to those.
