### ISSUE TITLE
Docker cli issue

### ISSUE THREAD

**Issue by juditgreskovits** [docker/for-mac#919]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
There is not enough information here to take action. Please do a diagnostics upload (run Diagnose & Feedback from the :whale: menu, select Diagnose & Upload, and paste the results of the diagnostic run (including diagnostic ID) back here?) and fill in the issue template.
