### ISSUE TITLE
Crashing on macOS Sierra Public Beta 3

### ISSUE THREAD

**Issue by redgenie** [docker/for-mac#92]
### Expected behavior
Docker compose pulls, builds and ups the containers

### Actual behavior
Docker app crashes with a vmstateevent: invalid son

### Information

Diagnostic ID: 165D2B0F-5570-4137-8E6A-57F3DEB2EF35
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12 (Build 16A270f)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Upgrade your macOS Sierra to public beta 3
2. docker-compose up (it has redis/php/mysql)
3. You get a nasty: vmstateevent: invalid json

**Comment by redgenie** [comment]
I have found the problem. Since I am in China currently, some packages could not be downloaded when in the pull phase. Docker.app would then crash with that error. I used a VPN and all worked well. But the Docker.app should not crash because a package could not be downloaded.

**Comment by djs55** [comment]
Docker for Mac beta 26 has improved support for macOS 10.12 Sierra: all the major show stopper issues which we are aware of have been fixed.

If you have the opportunity, please give it a try on the latest Sierra GM seed and open fresh issues for any problems you find.

- Release notes: https://download.docker.com/mac/beta/1.12.1.12048/NOTES
- Download: https://download.docker.com/mac/beta/Docker.dmg

Thanks for your help testing Docker for Mac with Sierra!
