### ISSUE TITLE
Docker hangs after computer is idle overnight

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#921]
### Expected behavior
Docker is still running when I come in the next day.

### Actual behavior
Docker is hung and does not respond when I first get in some mornings.

### Information
Docker for Mac: version: 1.12.3-beta29.3 (619507e)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/F78308D6-2C83-4AD1-A699-DDBAE51A937E/20161109-091739.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior
Happens some mornings when I come in and seems to happen almost every Monday after the weekend.

**Comment by daveisfera** [comment]
Here's the logs from /var/log/system.log:
Nov  9 09:17:30 Daves-MBP WindowServer[164]: send_datagram_available_ping: pid 950 failed to act on a ping it dequeued before timing out.
Nov  9 09:17:32 Daves-MBP com.apple.CDScheduler[41]: SysAdmChk: Throttling activity execution. memFlags:0x0 thermalLevel:0x1
Nov  9 09:17:34 --- last message repeated 1 time ---
Nov  9 09:17:34 Daves-MBP Docker[25374]: TextView: ⚠️ it is highly recommended to give any TextView an height layout constraint! ⚠️
Nov  9 09:17:49 Daves-MBP Docker[35719]: failed to establish 9P connection: Caught EOF on underlying FLOW
Nov  9 09:17:49 Daves-MBP Docker[69243]: EOF reading packet from Unix domain socket: closing
Nov  9 09:17:49 Daves-MBP Docker[69243]: Failed to read hello from client
Nov  9 09:18:04 Daves-MBP WindowServer[164]: send_datagram_available_ping: pid 950 failed to act on a ping it dequeued before timing out.
Nov  9 09:18:08 Daves-MBP com.apple.CDScheduler[41]: SysAdmChk: Throttling activity execution. memFlags:0x0 thermalLevel:0x1
Nov  9 09:18:27 --- last message repeated 33 times ---
Nov  9 09:18:27 Daves-MBP Docker[25374]: WizardMessage: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

**Comment by ijc25** [comment]
Since you mentioned Monday mornings I focused my investigations on the logs around 2016-11-07.

Nothing untoward occurs in your `docker.log`, I can see what I suppose is "the weekend" in a discontinuity between 2016-11-05T04:47:39.933875360Z and 2016-11-07T15:17:31.911822122Z. Nothing else looks untoward although there are a _lot_ of name lookups for `msg="Name To resolve: elasticsearch."`, as in batches of ~10 at 5s intervals, in fact most of the log is this message. This was going on long before the discontinuity and continues long after it so I think it is unrelated to the Monday morning problem. FYI a full snippet is:
```
time="2016-11-07T15:17:31.911822122Z" level=debug msg="Name To resolve: elasticsearch." 
time="2016-11-07T15:17:31.912214551Z" level=debug msg="Lookup name elasticsearch. present without IPv6 address" 
time="2016-11-07T15:17:31.912016389Z" level=debug msg="Name To resolve: elasticsearch." 
time="2016-11-07T15:17:31.912968047Z" level=debug msg="Lookup for elasticsearch.: IP [172.18.0.7]" 
```

I see a similar discontinuity in the system log (where I can also see that you have the fix for #933 already in play, so it's not that). Not long after waking I see:
```
Nov  7 08:17:56 Daves-MBP Docker[com.docker.slirp][35719] <Error>: Socket.TCPV4.read tcp:54.235.86.129:5432: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
Nov  7 08:17:56 Daves-MBP Docker[com.docker.slirp][35719] <Error>: Socket.TCPV4.read tcp:54.235.86.129:5432: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
Nov  7 08:17:56 Daves-MBP Docker[com.docker.slirp][35719] <Error>: Socket.TCPV4.read tcp:54.235.86.129:5432: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
Nov  7 08:44:19 Daves-MBP Docker[com.docker.docker][25374] <Notice>: Analytics: Sent heartbeat event.
Nov  7 08:50:08 Daves-MBP Docker[com.docker.slirp][35719] <Error>: TCP 192.168.65.2:56158 > 54.235.86.129:5432 proxy failed with flow proxy b: Connection refused
Nov  7 08:50:10 Daves-MBP Docker[com.docker.slirp][35719] <Error>: TCP 192.168.65.2:56188 > 54.235.86.129:5432 proxy failed with flow proxy b: Connection refused
Nov  7 08:50:14 Daves-MBP Docker[com.docker.slirp][35719] <Error>: TCP 192.168.65.2:56266 > 54.235.86.129:5432 proxy failed with flow proxy b: Connection refused
```
but after that I see what looks like normal activity and the above should not be related to the accessibility of the docker cli itself.

One thing I do see is some oom activity (on Nov 9 though) killing a node process, and some others much earlier.

I'm afraid I've been unable to glean any more from the logs about what might be going on.

If you see this again then please upload a diagnostic taken while the issue is happening. If you are unable to start the app to get to the Whale menu to do that then you can invoke manually from a terminal by running `~/Library/Group Containers/group.com.docker/bin/docker-diagnose -u`.

**Comment by efx** [comment]
I'm seeing this occur upon resuming the mac from sleep overnight: 
```
OS X: version 10.10.5 (build: 14F1912)
Docker.app: version: unknown (583d1b8)
Local time: Wed Nov 16 08:30:25 EST 2016
UTC:        Wed Nov 16 13:30:25 UTC 2016
Timestamp:  20161116-083025
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: (Failure "docker ps: timeout after 10.00s")
Error docker ps: timeout after 10.00s
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      slirp
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Error exec: which /usr/bin/log: exit 1
Error echo "00000003.0000f3a6" | nc -U /Users/eli/Library/Containers/com.docker.docker/Data/@connect > /tmp/9CB9F444-4CA2-4AB9-B5EC-9134E1EB0E32/20161116-083025/diagnostics.tar: timeout after 30.00s
Most specific failure is: docker ps failed: (Failure "docker ps: timeout after 10.00s")
Docker logs are being collected into /tmp/9CB9F444-4CA2-4AB9-B5EC-9134E1EB0E32/20161116-083025.tar.gz
Your unique id is: 9CB9F444-4CA2-4AB9-B5EC-9134E1EB0E32
```
I can upload the logs if a private location is available.

**Comment by feifangit** [comment]
same issue here
```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/82C44907-D7D3-4C00-84B1-8C6C6C2056F8/20161116-101741.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by dawnerd** [comment]
Here too. Restarting docker fixes it but is not ideal.

**Comment by dsheets** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
