### ISSUE TITLE
HyperKit >100% CPU running with mounted volume

### ISSUE THREAD

**Issue by jflatow** [docker/for-mac#923]
### Expected behavior

Running erlang inside a container, inside a volume mounted from the host. Erlang VM crashes, writes a `erl_crash.dump`. The crash dump should write and exit erlang shell immediately (its not a large dump).

### Actual behavior

During the dump, HyperKit CPU usage spikes ~150%, and the process never exits - just hangs. Keyboard interrupts do not work (although backgrounding the process and killing the job does).

**Comment by djs55** [comment]
I'm not familiar with erlang -- could you provide a test case (via a `Dockerfile`?) that I could run?

Also please upload a diagnostics report from

Whale menu -> Diagnose & Feedback

Thank you for using Docker for Mac!

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
