### ISSUE TITLE
first run docker,don't know what's wrong

### ISSUE THREAD

**Issue by unijoy** [docker/for-mac#925]
### Actual behavior
download dmg,open and copy app to application.click app ,need password then crash
### Information

Diagnostic ID: 2FE6FCFE-1102-4F2F-830F-59CE59A1784C
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.1 (Build 16B2657)
[ERROR]  docker-cli
         Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running
         Connection refused (ECONNREFUSED) connecting to /Users/kks/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/kks/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/kks/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by djs55** [comment]
OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

Related to docker/for-mac#561

Could you tell me where you got your dmg from? The official download page should have the most recent stable version. Is it an old copy or did you find it somewhere else?
