### ISSUE TITLE
docker for mac hanging with out any response when I execute docker commands

### ISSUE THREAD

**Issue by durganuvvula** [docker/for-mac#927]
### Expected behavior
docker commands should execute and return the response as expected

### Actual behavior
docker commands like docker images, docker ps -a or docker info all these are hanging and taking a long time and not responding. Even I tried restarting the docker but it did not help. Finally it worked after restarting my machine. but I would expect the ways to trouble shoot and fix the issue with out restarting the machine.

### Information
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/59557F94-F589-4BE9-8695-BC8E106C6067/20161110-103513.tar.gz
failure: docker ps failed: Failure("docker ps: timeout after 10.00s")
[ERROR]  docker-cli
         docker ps failed
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior

  1.  I did the docker exec -it CONTAINER /bin/bash
  2. I executed some commands inside the container and it was running well. 
  3. I exited out of the container with exit command and then after that I did not test it immediately. 

Probably the next day, I tested and its not coming up..not sure its being idle with out any activity issue or the above steps.

MAC OS :  OS X EI CAPITAN Version 10.11.6

Can some one help how to troubleshoot this issues?

when I run ps I still see the docker process running.

H9026:~ dnuvvula$ ps
  PID TTY           TIME CMD
 1738 ttys001    0:00.36 -bash
 3026 ttys001    0:00.09 docker run -i -t -p 4502:4502 aem-alpine-author
57227 ttys002    0:00.04 -bash
57808 ttys002    0:00.11 docker exec -it big_brattain sh
 3359 ttys003    0:00.21 -bash
56202 ttys003    0:00.06 docker run -i -t -p 4503:4503 aem-alpine-publis
51315 ttys004    0:00.02 -bash
69854 ttys005    0:00.05 -bash

Docker Version
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856

Quick Update:
Issue is solved after restarting the machine. But I was hoping to trouble shoot the issue with out restarting the machine.

I followed the reproducible steps again
by going into docker exec -it container  and then executed some commands inside the container. and then did the exit.. but still my docker commands work.. not sure if it has to do with keeping it idle.. I have docker installation for almost 2 weeks now I have not faced this issue before. may be its after certain time it hangs as others are also having issues around it.

**Comment by ijc25** [comment]
@durganuvvula It looks like perhaps you had some stray old processes hanging around. e.g. your logs have things like:
```

Nov  8 12:08:35 H9026 Docker[com.docker.vmnetd][53192] <Notice>: Client reports version 1, commit 0123456789012345678901234567890123456789
Nov  8 12:08:35 H9026 Docker[com.docker.slirp][1537] <Notice>: Client.negotiate: received ((magic VMN3T)(version 18)(commit 2d5b4d9c3daa089e3869e6355a47dd96dbf39856))
Nov  8 12:08:35 H9026 Docker[com.docker.vmnetd][53192] <Critical>: Failed to bind IPv4 0 80: Address already in use
Nov  8 12:08:35 H9026 Docker[com.docker.vmnetd][53192] <Critical>: sendmsg ok
Nov  8 12:08:35 H9026 Docker[com.docker.slirp][1537] <Error>: Failed to start instance: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
Nov  8 12:15:48 H9026 Docker[com.docker.slirp][1537] <Notice>: Creating resource Entry(tcp:0.0.0.0:80:tcp:172.17.0.4:80)
Nov  8 12:15:48 H9026 Docker[com.docker.slirp][1537] <Notice>: Write offset=0 data=[tcp:0.0.0.0:80:tcp:172.17.0.4:80] to file
Nov  8 12:15:48 H9026 Docker[com.docker.vmnetd][53733] <Notice>: Client reports version 1, commit 0123456789012345678901234567890123456789
Nov  8 12:15:48 H9026 Docker[com.docker.slirp][1537] <Notice>: Client.negotiate: received ((magic VMN3T)(version 18)(commit 2d5b4d9c3daa089e3869e6355a47dd96dbf39856))
```
suggesting that something has already bound those ports. It may be that something has crashed without properly cleaning up its child processes.

Rebooting will have cleared out those stale processes meaning they are not visible in the diagnostic upload. I've been unable to find any reason for them existing in the logs either.

So I'm going to close this issue now as there is nothing more we can do as is. However if you see this again then please upload a diagnostic taken while the issue is happening. If you are unable to start the app to get to the Whale menu to do that then you can invoke manually from a terminal by running `~/Library/Group Containers/group.com.docker/bin/docker-diagnose -u`
