### ISSUE TITLE
docker-compose exec slow

### ISSUE THREAD

**Issue by StefanScherer** [docker/for-mac#93]
### Information

I'm running a test environment with about a dozen containers with `docker-compose up`.
When I try to enter a running container with `docker-compose exec grafana bash` I have to wait 5-10 seconds until the bash prompt appears.
A `docker exec` seems to be fast, so it might be an issue with docker-compose + Docker 4 Mac.
### Expected behavior

docker-compose exec should work without such timeouts(?).
### Actual behavior

```
$ time docker-compose exec grafana echo x
x

real    0m5.610s
user    0m0.370s
sys 0m0.069s

$ time docker-compose exec grafana echo x
x

real    0m10.616s
user    0m0.380s
sys 0m0.068s

$ time docker exec plossysprofiling_grafana_1 echo x
x

real    0m0.138s
user    0m0.008s
sys 0m0.012s
```

Diagnostic ID: 5CEA5887-9236-445B-82C2-9A202A9DA0AA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.6 (Build 15G31)

I always compare this to my previous setup with a vmwarefusion docker machine VM. With the same docker-compose binary from Docker 4 Mac there is no such timeout:

```
$ time docker-compose exec grafana echo x
x

real    0m0.492s
user    0m0.375s
sys 0m0.054s
```

Please let me know how to give more details / debug logs / dtrace / etc. to investigate this.

**Comment by StefanScherer** [comment]
Tried it again at home seems to fix the problem.  Will test it tomorrow in company network again.

**Comment by djs55** [comment]
It seems likely that this is caused by [docker/docker-py#1076] and will hopefully be fixed by a future compose release. We haven't figured out how to reliably reproduce it -- I don't know what it is about certain network environments that triggers it. Any ideas welcome!

Thanks for your patience.

**Comment by djs55** [comment]
Some users report that editing `/etc/hosts` on the Mac and adding 
```
127.0.0.1 localunixsocket.local
```
makes it go away. Let me know if that helps at all.

**Comment by ijc25** [comment]
@StefanScherer In the meantime there have been fixes in this area made to both docker for mac and docker compose. It would be very interesting if someone who can reproduce this (no one who has tried internally has been able to do so) could retest with the latest stable docker for mac (1.12.3 at time of writing) or latest beta (beta30.1) and the included version of compose.

The beta is particularly interesting since there have been many improvements made to DNS there.

**Comment by StefanScherer** [comment]
@ijc25 I'm using Docker for Mac Version 1.12.3 (13776) right now. I cannot reproduce the problem. I'm closing this now.

**Comment by justintaft** [comment]
I ran into the issue. Adding 127.0.0.1 localunixsocket.local to /etc/hosts is very quick. Otherwise it takes a minute or two to start.

**Comment by sierranevadan** [comment]
I have tried adding `localunixsocket.local` to `/etc/hosts` as many issue threads have recommended. However, on my work network, a different default domain is used. Looking at the DNS queries by running

`sudo tcpdump -vvv -s 0 -l -n port 53`

I saw the queries for `localunixsocket.<my-work-domain>.com` being made, so I added that to `/etc/hosts` and now docker-compose commands are fast.

**Comment by jfreymann** [comment]
@sierranevadan, this worked for me as well.

**Comment by jaymecd** [comment]
@sierranevadan, you've saved my nerves.
