### ISSUE TITLE
Docker can't connect to internet

### ISSUE THREAD

**Issue by konradjurk** [docker/for-mac#931]
As of 

Version 1.12.3-beta30 (13798)
Channel: Beta
7314181670

How can I fix this. I've tried to quit Docker and restart it but it still does not work...

**Comment by konradjurk** [comment]
<img width="368" alt="bildschirmfoto 2016-11-11 um 00 47 04" src="https://cloud.githubusercontent.com/assets/6976170/20199066/72e82f10-a7a8-11e6-8a6b-69d3b5021e1b.png">

**Comment by bmhatfield** [comment]
Are you on an IPv6 network?

**Comment by bwegrzyn** [comment]
I have this issue as well with beta30. I downgraded to stable and it works fine.

**Comment by djs55** [comment]
There is a bug in beta 30 which causes DNS responses with an incorrect field set in the header to be cached. This causes problems... although it's usually intermittent and shouldn't survive a restart of the app.

IPv6 is a good suggestion -- in stable and previous betas we ignored all IPv6 nameservers. There is another bug in beta 30 where we try to use an IPv6 nameserver but use the wrong "protocol family" resulting in an `EINVAL` in the logs.

I couldn't find your diagnostic log upload on our servers -- if you'd like me to look a little deeper, please upload a fresh copy and let me know. In the meantime, I plan to fix these 2 known issues for the beta 31.

**Comment by konradjurk** [comment]
@djs55 Perfect, thank you! :) I just tried to pull something from a registry and that doesn't work, too, so I guess it is the same problem as the linked #932

**Comment by reinerj** [comment]
I can confirm this problem to pull from the hub but also from a private registry with beta 30

B80D0660-71B9-4D15-BD67-C1AB6C36DCEF

**Comment by bxt** [comment]
@reinerj You can make it usable again by going to your macOS network settings → Advanced → TCP/IP → Set IPv6 to link-local only.

**Comment by reinerj** [comment]
Thanks, this workaround fixed it ;)

**Comment by christianurich** [comment]
Had the same issue here. Setting the DNS to 8.8.8.8 solved the problem as well.

**Comment by konradjurk** [comment]
Fixed with

1.12.3-beta30.1 (13946)
Channel: Beta
f94d037b71

Thank you! 👍
