### ISSUE TITLE
Docker For Mac does not work on an IPv6 network

### ISSUE THREAD

**Issue by bmhatfield** [docker/for-mac#932]
### Expected behavior
I expect Docker For Mac to support IPv6 if I am on an IPv6 network.

### Actual behavior
When my network interface is configured for IPv6, docker for mac is unable to perform many actions, such as pulling new images or networking out to the internet from within containers.

eg

```
Unable to find image 'readytalk/nodejs:0.10.28' locally
Pulling repository docker.io/readytalk/nodejs
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/readytalk/nodejs/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
```

Reconfiguring my network interface to be "Link-local only" for IPv6 (OSX Network preferences) immediately resolves the issue.

### Information

I noticed that something is trying to talk UDP to an IPv6 address via `TCP4`:
Output from `syslog -k Sender Docker`
```
Nov 10 20:49:05 tw-mbp-bhatfield Docker[2233] <Error>: Socket.TCPV4.write udp:2601:184:4000:46f9::1:53: caught Uwt.Uwt_error(Uwt.EINVAL, "udp_send", "") returning Eof
Nov 10 20:49:05 tw-mbp-bhatfield Docker[2233] <Notice>: caught read: Eof writing request, attempting to reconnect
Nov 10 20:49:05 tw-mbp-bhatfield Docker[2233] <Error>: disconnect: failing request with id 1
Nov 10 20:49:05 tw-mbp-bhatfield Docker[2233] <Error>: udp -> 2601:184:4000:46f9::1:53: recvfrom caught Uwt.Uwt_error(Uwt.ECANCELED, "uwt_udp_recv", "") returning Eof
Nov 10 20:49:05 tw-mbp-bhatfield Docker[2233] <Notice>: read: Eof: dispatcher shutting down
```

The really notable part is `Socket.TCPV4.write udp:2601:184:4000:46f9::1:53: caught Uwt.Uwt_error(Uwt.EINVAL, "udp_send", "")`

### Steps to reproduce the behavior.

  0. Docker for Mac beta 1.12.3-beta30
  1. Be on an IPv6 network with internet access
  2. Fail to pull images from the docker registry
  3. Configure the interface to link-local only
  4. Everything works fine now

**Comment by bmhatfield** [comment]
Possibly see also: https://github.com/docker/for-mac/issues/931

**Comment by bmhatfield** [comment]
Here's another discussion I found about this: https://forums.docker.com/t/docker-beta-on-macos-sierra-10-12/15703

**Comment by bmhatfield** [comment]
Here's a discussion that is almost related - except they discuss nameserver order. My first nameserver in my machine's list is an IPv4 address. This issue seems deeper than nameserver order: https://github.com/docker/for-mac/issues/66

**Comment by djs55** [comment]
Thanks for the report. `Socket.TCPV4.write udp:2601:184:4000:46f9::1:53: caught Uwt.Uwt_error(Uwt.EINVAL, "udp_send", "") returning Eof` is indeed suspicious. We're slowly trying to add IPv6 support and it looks like the new DNS UDP code is buggy in the presence of an IPv6 nameserver. In previous betas and in stable we ignore IPv6 nameservers as a workaround.

I'll continue to investigate.

**Comment by djs55** [comment]
I've put this on my list of things to work on for beta 31. I believe the code change to make IPv6 work is small -- [docker/vpnkit#143] -- but I don't currently have an IPv6-enabled environment to run the automated tests in. Perhaps the best short-term fix is to ignore the IPv6 servers again but perhaps make this an optional setting for people willing to investigate.

**Comment by arroyo** [comment]
I had this same issue with ipv6, docker could not connect to docker.io or update packages with apt-get.

as a temporary fix I turned of ipv6 and docker is running smoothly again

diagnostic ID 
136364E3-EBBF-49AB-B6B2-083B643DAD04

**Comment by omarqureshi** [comment]
I'm also getting this issue too - switching IPV6 to local-link only fixes this:

Diagnostic ID:
E492C0E1-8505-4A27-9C96-1EDD7D51861C

**Comment by omarqureshi** [comment]
FWIW this did used to work in an older Docker for Mac

**Comment by asyazwan** [comment]
Can confirm that just switching to IPv6 `link-local only` worked. No need for DNS change to `8.8.8.8` (what's found as the top solution by googling this error) or any other change.

**Comment by djs55** [comment]
There was a regression in beta 30 where if the host has both an IPv4 nameserver and an IPv6 nameserver, the IPv6 request would fail and the IPv4 request would then be cancelled. This regression has been fixed in the latest beta 30.1 -- could you update to beta 30.1 and let me know how you get on? Note we still don't have first-class support for IPv6, but hopefully we can at least peacefully co-exist with it!

Thanks for your patience!

**Comment by asyazwan** [comment]
Can confirm IPv6 is working again with 30.1.

**Comment by rogaha** [comment]
@bmhatfield is it fixed for you with `Beta v30.1`?

**Comment by bmhatfield** [comment]
@rogaha @djs55 Confirmed that Beta 30.1 fixes this issue.

**Comment by escaton** [comment]
> Note we still don't have first-class support for IPv6

@djs55 Hi! what is current status for this? Is there related issue?
It's so annoying that i can't use docker-for-mac in ipv6 _only_ environment.
For a long time i had to use remote linux machine which is obviously not the best experience.
And recently i've finally found solution with legacy docker toolbox and bridge network
But it's still legacy and hacky. What should happen for a fresh docker-for-mac install to have ipv6 interface if it's available on host?

**Comment by djs55** [comment]
@escaton unfortunately we don't have IPv6 in Docker Desktop yet. The networking code is all in this repo: https://github.com/moby/vpnkit . In theory all that needs to happen is to enable IPv6 support in the TCP/IP stack and then to fix a few places which assume IPv4 addresses. The TCP/IP stack used is the Mirage one: https://github.com/mirage/mirage-tcpip which does support IPv6 but it has only been lightly tested, so might need some bug fixing.

Sorry we haven't made much progress in this area recently.

**Comment by escaton** [comment]
Thank you for the answer!
But do you have this feature in your roadmap?
Or maybe you can share some thoughts on this with me on slack (same login) so i’ll take a try on this?
