### ISSUE TITLE
Date in containers should always be accurate

### ISSUE THREAD

**Issue by clorichel** [docker/for-mac#934]
### Expected behavior

Starting a container should set its date accurately.

### Actual behavior

A newly started container may contain inaccurate date.

### Information

- macOS Sierra 10.12.1
- Docker for mac Version 1.12.3 (13776) Channel: Stable 583d1b8ffe

### Steps to reproduce the behavior

1. Run a container on the evening : `docker run -it ruby:2.3 /bin/bash`
1. With the container opened (that one was serving a jekyll website in my case), close your computer and go to sleep
1. The morning after, run another container and type `date` 😱 

Container was about 15min late from my computer time, I was using this container to operate AWS through its CLI, which bothered me with `InvalidSignatureException`. After restarting Docker with the `restart` button on the menu from the Docker icon and restarting the container, date was accurate.

Let me know if you need some more details.

**Comment by dsheets** [comment]
See #17, #693, #918.

**Comment by clorichel** [comment]
Thank you for the links!

Closing as duplicate of #17.
