### ISSUE TITLE
All containers and images are gone after update 1.12.1 -> 1.12.3 area/startup kind/bug

### ISSUE THREAD

**Issue by danki** [docker/for-mac#935]
### Expected behavior
Nothing should be deleted ?

### Actual behavior
Fresh install

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/65053FA4-8F5C-4B4D-895C-C718A8AE9721/20161111-181944.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

```
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
  1. Had 2 containers running
  2. Got popup for update
  3. Allowed update, got prompt for something with "deletion" , tho stressed due another issue, did not really read and just accepted. Though it was the .app it wanted to delete and could not due docker was running.
4. All gone ... :(

Heres output from earlier today, before update with my containers i was working atm. on before i got interrupted by other things...
```
Deko:candrop_grafana deko$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                                            NAMES
a42d3a28b4af        influxdb            "/entrypoint.sh influ"   4 days ago          Up 4 seconds            0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp   flux
687ae2863482        dekografana:dev     "/bin/sh -c /bin/bash"   5 days ago          Up 14 minutes           0.0.0.0:3000->3000/tcp                           grafa
```

and this is what i get now, with some additional outputs:
```

Deko:candrop_grafana deko$ docker version
Client:
    Version:            1.12.3
    API version:        1.24
    Go version:         go1.6.3
    Git commit:         6b644ec
    Built:              Wed Oct 26 23:26:11 2016
    OS/Arch:            darwin/amd64

Server:
    Version:            1.12.3
    API version:        1.24
    Go version:         go1.6.3
    Git commit:         6b644ec
    Built:              Wed Oct 26 23:26:11 2016
    OS/Arch:            linux/amd64

Deko:candrop_grafana deko$ docker info
Containers:             0
    Running:            0
    Paused:             0
    Stopped:            0
Images:                 0
Server Version:         1.12.3
Storage Driver:         aufs
    Root Dir:           /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs:               0
    Dirperm1 Supported: true
Logging Driver:         json-file
Cgroup Driver:          cgroupfs
Plugins:
    Volume:             local
    Network:            bridge overlay null host
Swarm:                  inactive
Runtimes:               runc
Default Runtime:        runc
Security Options:       seccomp
Kernel Version:         4.4.27-moby
Operating System:             Alpine Linux v3.4
OSType:                 linux
Architecture:                 x86_64
CPUs:                   2
Total Memory:           1.951 GiB
Name:                   moby
Docker Root Dir:        /var/lib/docker
Debug Mode (client):    false
Debug Mode (server):    true
    File Descriptors:   16
    Goroutines:         30
    System Time:        2016-11-11T17:33:20.09205123Z
    EventsListeners:    2
No Proxy:               *.local, 169.254/16
Username:               deko
Registry:               https://index.docker.io/v1/
WARNING:                No kernel memory limit support
Insecure Registries:
    127.0.0.0/8

Deko:candrop_grafana deko$ docker images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE

Deko:candrop_grafana deko$ docker ps -a
CONTAINER ID   IMAGE   COMMAND   CREATED   STATUS   PORTS   NAMES

```

**Comment by danki** [comment]
I'll leave the initial one untouched, in case it's a "bug".

Anyhow, got back my stuff... thankfully docker does not just remove things, instead all was in Trash.

In trash i found this folder, **com.docker 12-34-08-800.docker**, by moving and changing back the name in
_~/Library/Containers/com.docker.docker_ and restarting docker

```
Deko:candrop_grafana deko$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
dekografana               dev                 18d5dc812cde        5 days ago          313.5 MB
deko/hxgn                 v1                  6d4c419c37d2        7 days ago          180.4 MB
influxdb                  1.1.0-rc1-alpine    9fd593450ee5        10 days ago         35.35 MB
crate                     latest              3bcaf8f71c06        2 weeks ago         267.8 MB
nginx                     latest              e43d811ce2f4        2 weeks ago         181.5 MB
influxdb                  latest              09b31ff9aa2b        2 weeks ago         232 MB
resin/beaglebone-debian   latest              93fcb9fb40e4        3 weeks ago         180.4 MB
grafana/grafana           latest              de2ea786f98a        3 weeks ago         260.7 MB
sitespeedio/graphite      latest              a284bc62d89d        3 weeks ago         840.1 MB
ubuntu                    16.04               f753707788c5        4 weeks ago         127.2 MB
ubuntu                    14.04.3             3876b81b5a81        9 months ago        187.9 MB
Deko:candrop_grafana deko$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS               NAMES
a42d3a28b4af        influxdb            "/entrypoint.sh influ"   5 days ago          Exited (0) 6 hours ago                       flux
687ae2863482        dekografana:dev     "/bin/sh -c /bin/bash"   5 days ago          Exited (0) 6 hours ago                       grafa
Deko:candrop_grafana deko$
```

Phew!!

**Comment by jijojv** [comment]
same here, all gone and not in my .Trash

**Comment by danki** [comment]
Even tho containers and images are restored, they are completely reset.
All application settings configured inside the containers are gone, all DB are empty...

This issue should definitely be considered as huge bug/blocker.

**Comment by ijc25** [comment]
@danki I'm very sorry for the data loss which you have experienced.

The dialog you describe sounds like it may have been the dialog which is displayed if you change between the stable and beta channels (which requires a factory reset):
![screen shot 2016-11-14 at 11 39 01 am](https://cloud.githubusercontent.com/assets/12985729/20261726/fc7f264c-aa56-11e6-9ecc-f0577bd9a9f7.png)
However your logs show that you have only ever run the stable version and so should **never** have seen this dialog in the first place.

Unfortunately there were some issues prior to 1.12.3 which could sometimes cause upgrades to become confused and think you had switched channels when you had not. We believe these are fixed from the current version (which you are now running) onwards. If you see a similar dialog in the future when you are not switching between channels then please grab a screenshot (to pin down exactly which one it is, in particular which way it thinks you are transitioning), click cancel and then report it along with a new diagnostic.

I have also raised an internal issue to suggest changing the default button highlighted in the channel switch dialog to the non-destructive one.

Since we believe the issues to be fixed from 1.12.3 I'm going to close this issue. As I say above if you see a similar dialog again please click cancel and then let us know.

Sorry once again for the data loss.

**Comment by danki** [comment]
@ijc25 Yeah this screenie kind of looks familiar, tho due stressful moment back then i never paid any attention to it... and am therefor unable to confirm 100%.

Am glad i did not loose any important, thankfully the upgrade process moved **~/Library/Containers/com.docker.docker** to .trash which rescued me from possible losses.

Hope no one else lost anything important. I'd suggest in such case some kind of feature or option to export everything. Right now i would love to export all docker stuff for importing on to another machine.

**Comment by leession** [comment]
@jijojv me too, data missed !

**Comment by sramazzina** [comment]
Upgraded today and same problem. All containers gone!

**Comment by aftab-currency** [comment]
Everything's gone. Nothing in trash
