### ISSUE TITLE
Docker fails with "Bad response" after machine crash

### ISSUE THREAD

**Issue by jamshid** [docker/for-mac#936]
### Expected behavior
Docker should survive machine crashes.
### Actual behavior
Restarting docker for mac or closing/reopening did not help.
Even resetting my docker environment did not fix this error. It went away after Disconnecting my Tunnelblick VPN. Note I was also running a L2TP VPN around this time. And just noticed the error message that diagnostics/logs did not get uploaded, ugh.
```
$ docker -v ps
Docker version 1.12.3, build 6b644ec, experimental
$ docker ps
Error response from daemon: Bad response from Docker engine
```
### Information

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/3E549EA9-14E0-4793-B0D4-4EDDFDF6FB3B/20161112-001930.tar.gz
failure: com.docker.driver.amd64-linux -db is not running
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         slirp check failed with: (Failure "Caught EOF on underlying FLOW")
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     dis
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### Steps to reproduce the behavior

  1. Upgraded to beta30 (it was running a few "restart" containers.)
  2. My macbook crashed, not sure if Docker related, maybe sleep/display issue. 
  3. Could no longer get docker to work, tried restarts. Had to reset environment.

**Comment by accraze** [comment]
I had the same issue today after my macbook ran out of battery. 
I'm using `Docker version 1.12.3, build 6b644ec` and  macOS `10.12.1`
A factory reset fixed it for me as well.

**Comment by ijc25** [comment]
@accraze if you would like us to investigate your issue (which may not have the same root cause as this ticket) then please open your own ticket with your own diagnostics upload and description of your specific circumstances.

**Comment by ijc25** [comment]
@jamshid it seems likely that the crash corrupted either the qcow2 disk image used to back the VM storage or the filesystem within the disk image. Resetting to factory defaults would "fix" either of those.

The most recent error in your logs is:

>Detected symptom of problem 'processor-not-supported' in 3E549EA9-14E0-4793-B0D4-4EDDFDF6FB3B/20161112-001930.

> Your system does not satisfy the hardware requirements of Docker for Mac. See https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install for more information.

> The following log matches:
```
Nov 11 22:02:13 jambook Docker[com.docker.driver.amd64-linux][11397] <Notice>: Launched[11401]: /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 4G -c 2 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-vpnkit,uuid=0fdc2de6-fb01-4d0b-984f-ac30c1bab13b,path=/Users/jamshid/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1,format=qcow -s 4,virtio-9p,path=/Users/jamshid/Library/Containers/com.docker.docker/Data/s40,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/Users/jamshid/Library/Containers/com.docker.docker/Data/s51,tag=port -s 7,virtio-sock,guest_cid=3,path=/Users/jamshid/Library/Containers/com.docker.docker/Data,guest_forwards=2376;1525 -l com1,autopty=/Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac -F /Users/jamshid/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
Nov 11 22:02:13 jambook Docker[com.docker.driver.amd64-linux][11397] <Notice>: Unable to create VM (-85377018)
Nov 11 22:02:13 jambook Docker[com.docker.driver.amd64-linux][11397] <Notice>: vmx_init: processor not supported by Hypervisor.framework
Nov 11 22:02:13 jambook com.docker.driver.amd64-linux[com.docker.driver.amd64-linux][11397] <Error>: -[__NSCFArray length]: unrecognized selector sent to instance 0x4a07000
Nov 11 22:02:13 jambook com.docker.driver.amd64-linux[com.docker.driver.amd64-linux][11397] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray length]: unrecognized selector sent to instance 0x4a07000'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x00007fff89b2a452 __exceptionPreprocess + 178
```

which is rather hard to fathom because your logs clearly show things were fine previously. Note that the above error comes directly from the hypervisor framework. Did you change any BIOS or other settings recently? Are things working for you after the factory reset?

**Comment by ijc25** [comment]
Putting the vmx error to one side the latter part of your logs are full of:
```
Nov 12 00:19:57 jambook com.docker.driver.amd64-linux[com.docker.driver.amd64-linux][42188] <Error>: -[__NSCFArray length]: unrecognized selector sent to instance 0x4c03770
Nov 12 00:19:57 jambook com.docker.driver.amd64-linux[com.docker.driver.amd64-linux][42188] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray length]: unrecognized sel
ector sent to instance 0x4c03770'
        *** First throw call stack:
        (
                0   CoreFoundation                      0x00007fff89b2a452 __exceptionPreprocess + 178
                1   libobjc.A.dylib                     0x00007fff97e1cf7e objc_exception_throw + 48
                2   CoreFoundation                      0x00007fff89b9410d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
                3   CoreFoundation                      0x00007fff89a9a4d1 ___forwarding___ + 1009
                4   CoreFoundation                      0x00007fff89a9a058 _CF_forwarding_prep_0 + 120
                5   com.docker.driver.amd64-linux       0x0000000004426173 sc_get_string + 35
                6   com.docker.driver.amd64-linux       0x0000000004425da4 _cgo_04440fad9587_Cfunc_sc_get_string + 36
                7   com.docker.driver.amd64-linux       0x000000000406e470 com.docker.driver.amd64-linux + 451696
        )
```

which I think is part of the new code in beta30 for better dealing with DNS and VPN related issues, which would appear to be unhappy with some aspect of your Tunnelblick VPN. I have escalated internally.

**Comment by jamshid** [comment]
Thanks, yes the problem definitely seems related to Tunnelblick. 

My Docker for Mac had been working after reset, but I just encountered problem where it wouldn't start after opening my Macbook -- icon just kept spinning. 

It finally restarted successfully after I Disconnected my Tunnelblick 3.6.8 (build 4625) (latest) session.

**Comment by jamshid** [comment]
FWIW because of the beta30 problems I tried switching to a VirtualBox docker with docker-machine, and it also seems to be incompatible with Tunnelblick. 

I'm trying Viscosity VPN client now and it seems to be working with my docker-machine docker. Will let you know if I get back to Docker for Mac to see if it works there too.

**Comment by ijc25** [comment]
@jamshid thanks, more data on different VPNs is always appreciated.

**Comment by jamshid** [comment]
Trying updated Docker for Mac 1.12.3-beta30.1 (13946), still not working with Tunnelblick. 
What Mac OpenVPN clients do you test with?
```
[caringo53 ] bash-3.2$ docker ps
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: EOF
```

**Comment by samoht** [comment]
@jamshid the latest stable and beta releases have seen a lot of improvement related to DNS/VPN issues. Would you be able to test it and report if it works for you? Thanks!

**Comment by dave-tucker** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
