### ISSUE TITLE
in need of a "docker-machine env" replacemenet

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [docker/for-mac#938]
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/29233D54-ADB5-4917-9E4F-58D91E71B181/20161112-120130.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux

██ [ user ] [ ~ ] [ 11:57:34 ]
██ docker --version
Docker version 1.12.1, build 6f9534c

██ [ user ] [ ~ ] [ 12:00:02 ]
██ docker-compose --version
docker-compose version 1.8.0, build f3628c7

██ [ user ] [ ~ ] [ 12:00:13 ]
██ docker-machine --version
docker-machine version 0.8.1, build 41b3b25

██ [ user ] [ ~ ] [ 12:00:20 ]
██ docker-machine env
Error: No machine name(s) specified and no "default" machine exists.

Am in the need for a replacement to set the ENV variables automatically.

**Comment by ijc25** [comment]
@morriswinkler-simplesurance there is no need to set any environment variables to use docker for mac, it should just work out of the box (in fact setting environment variables a la `docker-machine` is actively harmful to the use of docker for mac).

Unfortunately your diagnostic bug ball has not been uploaded so I'm unable to tell if you are having any other problem. I'm going to close on the assumption that this is simply confusion regarding the need for environment variables. If that is not the case then please open a new issue ensuring that the diagnostics are uploaded and describe the issue you are having fully in the issue text.

**Comment by morriswinkler-simplesurance** [comment]
Yes it does, but there some tools that use DOCKER_ENV variables, the usual way was to use attach docker-machine env to you .bashrc and that's it, now there is no equivalent for that.

please see https://docs.docker.com/machine/reference/env/

I am just asking to get something similar on  the now docker-for-mac pkg. 
My use case is https://godoc.org/github.com/docker/docker/client#NewEnvClient.
I am sure there are others, as I also used them when pushing to cloud foundry registries.

**Comment by justincormack** [comment]
The client library should have the right defaults, ie connect to the local socket by default, use environment variables if set.

**Comment by morriswinkler-simplesurance** [comment]
how would i get the docker daemon version on mac from an other program ?

**Comment by justincormack** [comment]
you can get `docker version` info in json with `docker version --format '{{json .}}'` or use the templates as in https://docs.docker.com/engine/reference/commandline/version/

**Comment by morriswinkler-simplesurance** [comment]
Much better.

**Comment by justincormack** [comment]
```docker version --format '{{.Server.APIVersion}}'``` or ```docker version --format '{{.Server.MinAPIVersion}}'``` should be what you want
