### ISSUE TITLE
can not find docker

### ISSUE THREAD

**Issue by wdongxv** [docker/for-mac#940]
### Information

Diagnostic ID: 390001BA-0BD3-4FD0-B327-49BDBCE14215
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12.1 (Build 16B2555)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Volumes/Data/Application/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/dxw/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/390001BA-0BD3-4FD0-B327-49BDBCE14215/20161113-022403/qemu-img-check.stdout 2> /tmp/390001BA-0BD3-4FD0-B327-49BDBCE14215/20161113-022403/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/dxw/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dxw/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/dxw/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/dxw/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/dxw/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. ...
2. ...

**Comment by ijc25** [comment]
Detected symptom of problem 'unsupported-sierra' in 390001BA-0BD3-4FD0-B327-49BDBCE14215/20161113-022444.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
