### ISSUE TITLE
Can't run arm-image container with bind mount qemu-arm binary

### ISSUE THREAD

**Issue by d11thRid3r** [docker/for-mac#941]
### Expected behavior

I tried to recreate to run a container with arm-image on osx like here:
[blog.hypriot](http://blog.hypriot.com/post/first-touch-down-with-docker-for-mac/)

in detail this:
`$ docker run -d -v /tmp/qemu-arm-static:/usr/bin/qemu-arm-static -p 80:80 --name busyboxtest hypriot/rpi-busybox-httpd`

and i expected something like this:
```
$ docker ps
IMAGE                            STATUS                    NAMES
hypriot/rpi-busybox-httpd        Up 6 minutes              busyboxtest
```

### Actual behavior

when i run:
`$ docker run -d -v /tmp/qemu-arm-static:/usr/bin/qemu-arm-static -p 80:80 --name busyboxtest hypriot/rpi-busybox-httpd`

I get this:
```
$ docker ps -a
IMAGE                           STATUS                        NAMES
hypriot/rpi-busybox-httpd       Exited (2) 6 minutes ago      busyboxtest
```

### Information

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/83814022-D8DC-43D6-B2BF-90ECB0158CC3/20161112-221411.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

From `$ syslog -k Sender Docker`:
```
Nov 12 22:12:36 LTP Docker[533] <Notice>: Creating resource Entry(feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562)
Nov 12 22:12:36 LTP Docker[533] <Notice>: Write offset=0 data=[feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562:/tmp/qemu-arm-static] to file
Nov 12 22:12:36 LTP Docker[533] <Notice>: Volume.start feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562 (paths = [/tmp/qemu-arm-static])
Nov 12 22:12:36 LTP Docker[533] <Notice>: Volume.start feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562 (watches [/tmp/qemu-arm-static -> /private/tmp/qemu-arm-static])
Nov 12 22:12:36 LTP Docker[533] <Notice>: Created instance feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562
Nov 12 22:12:37 LTP Docker[534] <Notice>: Creating resource Entry(tcp:0.0.0.0:80:tcp:172.17.0.2:80)
Nov 12 22:12:37 LTP Docker[534] <Notice>: Write offset=0 data=[tcp:0.0.0.0:80:tcp:172.17.0.2:80] to file
Nov 12 22:12:37 LTP Docker[1646] <Notice>: Client reports version 1, commit 0123456789012345678901234567890123456789
Nov 12 22:12:37 LTP Docker[534] <Notice>: Client.negotiate: received ((magic VMN3T)(version 18)(commit 583d1b8ffe2e3d117e4725a0857d335bc27190ac))
Nov 12 22:12:37 LTP Docker[1646] <Critical>: sendmsg ok
Nov 12 22:12:37 LTP Docker[534] <Notice>: Created instance tcp:0.0.0.0:80:tcp:172.17.0.2:80
Nov 12 22:12:38 LTP Docker[533] <Notice>: Volume.stop feb077659c18f654d5c2b805e3bf4f1f4c12f87041038344ccef81c2c2150562 (paths = [/private/tmp/qemu-arm-static])
```

It works,  when I run an image where qemu is allready included, like:
```
$ docker run resin/armv7hf-debian uname -a
		Linux 2e6d6116b202 4.4.27-moby #1 SMP Wed Oct 26 14:21:29 UTC 2016 armv7l GNU/Linux
```

**Comment by d11thRid3r** [comment]
OK, it looks like I missed some conceptual dependencies here...
I thought the qemu supports comes within docker4mac and I missed,
that there is allready a workaround: https://github.com/justincormack/cross-docker
Another solution is to use an image where the quemu binary is allready included, like this:
resin/armv7hf-debian

But I want to stick with the bind mount method, because I don´t want to include thinks I don´t need on the production host (the raspi in my case).
So instead of starting all cross-arch-containers through that script from justincormack,
I´m using a more persistent solution on OSX:

create a directory and get all qemu-user-static bins:
```
$ mkdir ~/docker-qemu-static
$ cd ~/docker-qemu-static/
$ docker run justincormack/debian-qemu-user tarup.sh | tar xf -
```

now, you can bind mount the qemu-static every time like this:
```
$ docker run -d -v ~/docker-qemu-static/qemu-arm-static:/usr/bin/qemu-arm-static -p 80:80 --name busyboxtest hypriot/rpi-busybox-httpd
$ docker ps
IMAGE                            STATUS                     PORTS                NAMES
hypriot/rpi-busybox-httpd        Up 15 seconds              0.0.0.0:80->80/tcp   busyboxtest
```

I don´t know if docker4mac should provide the qemu statics on its own or not, thats why I leave it to someone else to decide if this is an issue or not...

**Comment by justincormack** [comment]
Hi, there were some kernel patches that enabled specifying the emulator on the host that we hope to ship one day, but last time I checked they had not been merged upstream. This would mean it would magically just work, which is obviously nicer. When that happens we probably will ship a copy. You could also create a volume with a copy in.

**Comment by d11thRid3r** [comment]
Ok, thanks. Then I´ll keep my copy until it´s working magically ;-)
