### ISSUE TITLE
Containers gone after update to 1.12.3

### ISSUE THREAD

**Issue by corelmax** [docker/for-mac#942]
Diagnostic Output:
```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/060D48EB-62D4-4E09-8D31-6EE3A8263168/20161114-110850.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     mobs-syslog
[OK]     db
[OK]     env
[OK]     virtualisation kern.hv_support
[OK]     slip
[OK]     osxfs
[OK]     mobs-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

**Comment by elnygren** [comment]
can confirm, `docker ps -a` and `docker images` show nothing anymore. I had several databases running before the update.

**Comment by ijc25** [comment]
@elnygren are you looking at @corelmax's machine (perhaps you are co-workers or something)? If not and you are just reporting that you have seen similar symptoms then please open a new ticket of your own with your own diagnostic upload and description of your circumstances.

**Comment by ijc25** [comment]
@corelmax your last three application starts are:
```
Nov 14 09:52:36 [...] Docker[com.docker.docker][467] <Notice>: AppDelegate: Application version: 1.12.3-beta30 (13798)
Nov 14 10:50:59 [...] Docker[com.docker.docker][1189] <Notice>: AppDelegate: Application version: 1.12.3 (13776)
Nov 14 10:54:11 [...] Docker[com.docker.docker][1349] <Notice>: AppDelegate: Application version: 1.12.3-beta30 (13798)
```
That is, you seem to briefly switched branch from beta to stable and back to beta. Switching between branches requires a factory reset which explains why your contains have apparently disappeared.

You should have seen a dialog similar to this when you moved from the stable version to the beta version:
![screen shot 2016-11-14 at 11 39 01 am](https://cloud.githubusercontent.com/assets/12985729/20275104/22ff5d0e-aa8f-11e6-9dd4-52c4f950e28d.png)
and something similar (but opposite) when you went from beta to stable.

**Comment by ijc25** [comment]
Closing since this seems AFAICT to be behaving as expected (and as required by channel switching). If something about the above explanation does not chime with what you think actually happened then please reopen.
