### ISSUE TITLE
Problem starting Docker after upgrading to 1.12GA (same issue after upgrade to 1.12.3)

### ISSUE THREAD

**Issue by dkokic** [docker/for-mac#943]
### Expected behavior

  - After starting the Docker app, I would expect Docker to get started.

### Actual behavior

  - The Docker is forever in "starting ..." state.

### Information

  - Diagnostics ID: C014BCE7-C38C-4759-A644-CA4D3151B5D6
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pedrorijo91** [comment]
had the same problem. A factory reset fixed it for me.

**Comment by dkokic** [comment]
thanks. the factory reset helped.
