### ISSUE TITLE
"Diagnose & Feedback" should check for IPv6 issues

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/for-mac#945]
### Expected behavior

Docker for Mac [does not currently support IPv6](https://docs.docker.com/docker-for-mac/troubleshoot/#/workarounds-for-common-problems). I expected the 'Diagnose & Feedback' tool to provide a warning that IPv6 is currently enabled on my laptop.

### Actual behavior

As the output below shows, as does #66 & #932,  the 'Diagnose & Feedback' tool say that networking is [OK], but Docker for Mac doesn't work on an IPv6-enabled network.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/6C9ADBC0-EC71-46A6-8ABE-0FB3A16ABA48/20161114-111055.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW

n/a

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

1. Join an IPv6-enabled network. 
2. Run through the Getting Started guide https://docs.docker.com/docker-for-mac/
3. Note if it fails.
4. Go to the  "Diagnose & Feedback" tab and click either of the Diagnose buttons. Diagnose will report [OK] for everything, or at least for `dns` and other checks.

**Comment by ijc25** [comment]
@stefanlasiewski thanks for the suggestion, that's clearly a very good idea. I've escalated this into the internal issue tracker.

**Comment by stefanlasiewski** [comment]
I think this was fixed long ago. I haven't had issues between Docker for Mac & IPv6 in a long time. Closing.
