### ISSUE TITLE
mac pro

### ISSUE THREAD

**Issue by OSMeteor** [docker/for-mac#948]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
Please do a diagnostics upload and fill in the questions in the issue template if you are having an issue. Will reopen once that is done.
