### ISSUE TITLE
All containers lost on upgrade to 1.12.3-beta30

### ISSUE THREAD

**Issue by cridenour** [docker/for-mac#949]
### Expected behavior
Update like every previous upgrade on beta branch, with no loss of data.

### Actual behavior
All data lost, no warning or confirmation.

### Information

Diagnostic ID: A74944DD-D72A-424A-B095-E5F5ED6B2FB7
```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.12.1 (build: 16B2657)
logs: /tmp/A74944DD-D72A-424A-B095-E5F5ED6B2FB7/20161114-234750.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

1. Install 1.12.3-beta 30
2. Check output of `docker ps -a` or `docker images`

**Comment by ijc25** [comment]
@cridenour I'm very sorry for the data loss you have experienced. Looking at your logs I see the following occurred on the most recent boot:
```
 * Configuring host block device ...boot2docker-data contains a file system with errors, check forced.
boot2docker-data: Inodes that were part of a corrupted orphan linked list found.  

boot2docker-data: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
	(i.e., without -a or -p options)
Initializing partitions on /dev/vda...
Creating file systems...
mke2fs 1.43 (17-May-2016)
```

i.e. it has detected filesystem corruption which cannot be resolved and has therefore recreated the filesystem.

I cannot see anything in your logs which gives a hint as to what caused this corruption. Do you remember anything out of the ordinary (Docker.app crashing, or even your Mac crashing)?

**Comment by cridenour** [comment]
@ijc25 Thanks for taking a look. No crashes that I am aware of. Definitely not on the Mac, but the upgrade ran without a visible error and started up without me having to restart Docker.app.

**Comment by ijc25** [comment]
Thanks for the additional info. I'm going to start a conversation internally about whether `fsck -y` might be better than `fsck -p` in that it might repair more cases before declaring them unsalvageable. Other than that I'm not sure how else to progress the issue :-/.

**Comment by cridenour** [comment]
@ijc25 Yea I'm not sure there's anything else that can be done or diagnosed unless there are more cases of this. Otherwise, just bad luck.

**Comment by ijc25** [comment]
I've opened a ticket internally (and another one to improve the logging when this occurs).

Since this appears for now to have been a one off I'm going to close, obviously please do reopen if you see this again.

Thanks again for your report.

**Comment by shaug** [comment]
I just had the same thing happen to me, same version (b30). No warnings. All containers gone.

Diagnostic  ID B09C6F6C-051D-465F-9F0E-D1E8D38119EF

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/B09C6F6C-051D-465F-9F0E-D1E8D38119EF/20161115-193147.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by ijc25** [comment]
@shaug From your logs your issue is not the same as this one even though the symptoms might be similar:

>Detected symptom of problem 'aufs-corruption' in B09C6F6C-051D-465F-9F0E-D1E8D38119EF/20161115-193147.

>The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

>May be related to docker/for-mac#20
