### ISSUE TITLE
A docker container gets stuck when it uses a lot of memory

### ISSUE THREAD

**Issue by dmpetrov** [docker/for-mac#95]
### Expected behavior

Allocate all memory to a container and run a memory intensive application (python/pandas data processing app). Sometimes the application takes all memory (16Gb from my 16Gb machine) and finishes in ~10 minutes.

### Actual behavior

The container gets stuck with probability ~50%. The application gets stuck in one memory intensive step. Docker commands inspect\stats\ps do not respond. However, the docker still uses CPU (300% for my current app).

### Information

Diagnostic ID: 84396F0F-E4F3-45A9-8F20-25178F7819F3
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.5 (Build 15F34)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Allocate all your RAM memory to container (I allocate 16Gb from my 16Gb machine)
2. Run memory intensive application in container (I run python/pandas data processing app) which can consume all the memory
3. Take some of your memory by other applications (browser)
4. The container gets stuck with probability ~50%.

**Comment by djs55** [comment]
Unfortunately the containers are running inside a Linux VM which has overheads for things like the kernel and the docker daemon. MacOS also has similar overheads for its kernel and userspace. I think what happened in this case is that the host needed to swap itself to disk in order to swap the Linux VM in and then back out again, which resulted in the whole system running very slowly.

It looks like Linux's scheduler started to complain:
```
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: WARNING: CPU: 0 PID: 0 at kernel/time/tick-sched.c:908 tick_nohz_idle_exit+0x36/0xdb()
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Modules linked in:
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.4.15-moby #1
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Hardware name:   BHYVE, BIOS 1.00 03/14/2014
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: 000000000000002c ffffffff8130a723 0000000000000000 0000000000000009
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ffffffff8106bc82 ffffffff810b5ee2 ffff88043fc0ebc0 ffffffff81c04000
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: 0000000000000000 ffffffff81c00000 ffffffff810b5ee2 ffffffff81c00000
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Call Trace:
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: [<ffffffff8130a723>] ? dump_stack+0x5a/0x6f
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: [<ffffffff8106bc82>] ? warn_slowpath_common+0x8e/0xa3
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ------------[ cut here ]------------
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: WARNING: CPU: 0 PID: 0 at lib/timerqueue.c:77 timerqueue_del+0x27/0x59()
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Modules linked in:
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.4.15-moby #1
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Hardware name:   BHYVE, BIOS 1.00 03/14/2014
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: 000000000000002c ffffffff8130a723 0000000000000000 0000000000000009
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ffffffff8106bc82 ffffffff8131164e ffff88043fc0ebc0 ffff88043fc0e810
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ffff88043fc0e800 0000000000000001 ffffffff8131164e ffff88043fc0e7c0
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Call Trace:
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: [<ffffffff8130a723>] ? dump_stack+0x5a/0x6f
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.4.15-moby #1
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Hardware name:   BHYVE, BIOS 1.00 03/14/2014
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: 000000000000002c ffffffff8130a723 0000000000000000 0000000000000009
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ffffffff8106bc82 ffffffff8131164e ffff88043fc0ebc0 ffff88043fc0e810
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: ffff88043fc0e800 0000000000000001 ffffffff8131164e ffff88043fc0e7c0
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: Call Trace:
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: [<ffffffff8130a723>] ? dump_stack+0x5a/0x6f
<Warning>: VM: 2016-08-03 07:52:29 +0000 UTC kern.warn kernel: [<ffffffff8106bc82>] ? warn_slowpath_common+0x8e/0xa3
```
It may be possible to make Linux more tolerant of running extremely slowly -- we'll investigate this.

In the meantime I recommend allocating less memory to the VM (i.e. in Whale menu -> Preferences -> General -> Memory) to leave some memory for MacOS.

Thanks for your patience.
