### ISSUE TITLE
keeps crashing every few minutes

### ISSUE THREAD

**Issue by sannu20** [docker/for-mac#950]
### Information

Diagnostic ID: CB6318C5-B585-469E-8212-9DA7B9EC39A0
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.12 (Build 16A323)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by ijc25** [comment]
Detected symptom of problem 'unsupported-sierra' in CB6318C5-B585-469E-8212-9DA7B9EC39A0/20161115-110003.

OSX Sierra is supported from Docker for Mac version 1.12.1 on the stable channel, and from 1.12.1-beta26 on the beta channel. Please upgrade your version of Docker for Mac.

May be related to docker/for-mac#561
