### ISSUE TITLE
docker: Error response from daemon: unknown log opt "gelf-tag" for gelf log driver.

### ISSUE THREAD

**Issue by a1exus** [docker/for-mac#956]
### Expected behavior

I'm trying to follow [Route Docker Logs to ELK Stack Raw's instructions](https://gist.github.com/shreyu86/735f2871460a2b068080) and while trying to run:

`docker run -d --net=host --log-driver=gelf --log-opt gelf-address=udp://$LOGSTASH_ADDRESS:12201 --log-opt gelf-tag="fe" nginx`

I'm getting following error:

> docker: Error response from daemon: unknown log opt "gelf-tag" for gelf log driver.

### Actual behavior

```
$ docker run -dit --net=host --log-driver=gelf --log-opt gelf-address=udp://$LOGSTASH_ADDRESS:12201 --log-opt gelf-tag="fe" -p 8080:80 nginx
docker: Error response from daemon: unknown log opt "gelf-tag" for gelf log driver.
See 'docker run --help'.
$
```
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/6438DE61-D671-48DE-A643-9BCCA5CFC2D4/20161115-223101.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW

no `Dockerfile`, just follow [Route Docker Logs to ELK Stack Raw's instructions](https://gist.github.com/shreyu86/735f2871460a2b068080)

```
$ docker run -d --name es elasticsearch
7f24fa3df3a76504363381bf0eef3e064f81ad071905da3329a16388518f7c44
$ docker run -d --name logstash --link es:elasticsearch logstash -v /tmp/logstash.conf:/config-dir/logstash.conf logstash logstash -f /config-dir/logstash.conf
f732840a0359be4fec654cfc6ecb63134175c0287d94eb7e866d00306181d365
$ docker run --link es:elasticsearch -d kibana
79f6e113561fc956452677270b0b8c112b39976ecc387510a8733dd5b0a15b73
$ LOGSTASH_ADDRESS=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' logstash)
$ docker run -dit --net=host --log-driver=gelf --log-opt gelf-address=udp://$LOGSTASH_ADDRESS:12201 --log-opt gelf-tag="fe" -p 8080:80 nginx
docker: Error response from daemon: unknown log opt "gelf-tag" for gelf log driver.
See 'docker run --help'.
$
```
  - Page URL if this is a docs issue or the name of a man page

[Configure logging drivers - Docker](https://docs.docker.com/engine/admin/logging/overview/#/gelf-options)
[Route Docker Logs to ELK Stack Raw's instructions](https://gist.github.com/shreyu86/735f2871460a2b068080)

### Steps to reproduce the behavior

  1. `docker run -dit --net=host --log-driver=gelf --log-opt gelf-address=udp://$LOGSTASH_ADDRESS:12201 --log-opt gelf-tag="fe" -p 8080:80 nginx`
  2. `docker logs`

**Comment by ijc25** [comment]
Thanks for you report @a1exus.

This looks to me to be either a docker engine issue or the gelf logger plugin or an issue with the gist you are following and not with docker for mac. Please report to [the Docker engine issue tracker](https://github.com/docker/docker/issues/) (which I think is where gelf is supported?).

A bit of web searching found https://github.com/aws/amazon-ecs-agent/issues/255 which implied that perhaps the option is just called `tag` now rather than `gelf-tag`.

I'm going to close this issue, but if it turns out that this really is a docker for mac specific issue somehow please do reopen.
