### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by zgtios** [docker/for-mac#957]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

Diagnostic Id: B5632D80-2948-4585-BDA2-FDA0AA5471CE

**Comment by ijc25** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in B5632D80-2948-4585-BDA2-FDA0AA5471CE/20160822-125656.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

Please get back to us if the workaround does not work for you.
