### ISSUE TITLE
docker for mac beta (1.12.3-beta30) network timeout pulling image

### ISSUE THREAD

**Issue by D3nn** [docker/for-mac#959]
### Expected behavior

```
$ docker pull ruby
Using default tag: latest
latest: Pulling from library/ruby
386a066cd84a: Pull complete
75ea84187083: Pull complete
88b459c9f665: Pull complete
1e3ee139a577: Pull complete
741de17843a5: Pull complete
7b91d9bcfd6e: Pull complete
f4906808c869: Pull complete
e9976164e43f: Pull complete
Digest: sha256:a5ebd3bc0bf3881258975f8afa1c6d24429dfd4d7dd53a299559a3e927b77fd7
Status: Downloaded newer image for ruby:latest
```

### Actual behavior

```
$ docker pull ruby
Using default tag: latest
Pulling repository docker.io/library/ruby
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ruby/images. You may want to check your internet connection or if you are behind a proxy.
```

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
     Diagnostic ID:  6305AAAB-A335-4B28-831D-F4306E7A32B2
     Diagnostic output:

```Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/6305AAAB-A335-4B28-831D-F4306E7A32B2/20161116-083229.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Install and run docker for mac beta (1.12.3-beta30)
  2. docker pull <some image on dockerhub, e.g. ruby official image>

### Debugging steps

(WORKS = can pull images from dockerhub, DOESN'T WORK = Network timeout pulling images)
  1.  Reset and Restart docker (no copy of images/etc) - DOESN'T WORK
  2.  Edit /etc/resolv.conf in the installed docker VM to point nameserver to local router - WORKS
  3.  Switch /etc/resolv.conf back to default entry - DOESN'T WORK
  4.  Switch to stable channel - WORKS
  5. Switch back to beta channel - DOESN'T WORK

Note that I am not behind a proxy when doing these tests and have no proxy configuration configured in the Docker UI.

Also note that I do not have any custom DNS configuration setup on my Mac.  First DNS entry on the Mac points  to my local router and second entry points to the same via IPv6 addr.  These values are what was returned by DHCP from the router and not manually configured.

Finally, pulling docker images in the beta channel WAS working correctly until later yesterday evening.  I was pulling images to prepare for being a mentor for our docker meetup.   I had pulled the  required images but was getting a failed docker build when the ruby image was doing a gem install (also an error trying to download the gem).  I decided to try to pull the ruby:latest image (instead of the ruby:alpine image) to see if it also couldn't pull the gem file but the pull of the ruby:latest image failed.  Internet is working just fine otherwise (I could pull the gem spec manually for example) but docker build and docker pull failed with network errors.

**Comment by ijc25** [comment]
@D3nn Thanks for your report.

There were some issues with DNS lookup in beta30 which have been addressed in beta30.1 which was released yesterday. Does that update resolve things for you?

**Comment by D3nn** [comment]
@ijc25 Thanks for the quick response.

Other than getting hung up when restarting after the upgrade (which was fixed by quitting docker and manually restarting), so far the DNS resolution seems to be working OK while at work.

If you would, please keep this open until I can make sure it also works at home on this system (as that's when I first saw the issue).

FYI.  Here's some output that looks relevant regarding the failure in startup of Docker as part of the upgrade to beta31:

```
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: Creating slirp server pcap_settings:disabled peer_ip:192.168.65.2 local_ip:192.168.65.1 domain_search:
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: PPP.negotiate: received ((magic VMN3T)(version 1)(commit f94d037b71efe19211fc243ddb38e04c4e17a745))
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: PPP.negotiate: received (Ethernet cdb65200-e6fb-4892-96b4-db5e6f4106e1)
Nov 18 13:24:45 chuda04mac1017 Docker[35764] <Notice>: virtio-net-vpnkit: magic=VMN3T version=1 commit=0123456789012345678901234567890123456789
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: PPP.negotiate: sending ((mtu 1500)(max_packet_size 1550)(client_macaddr c0:ff:ee:c0:ff:ee))
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: TCP/IP ready
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: stack connected
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: starting introspection intrspection_url:fd:5
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Notice>: starting diagnostics diagnostics_url:
Nov 18 13:24:45 chuda04mac1017 Docker[35762] <Error>: start_diagnostics_server: caught Uwt.Uwt_error(Uwt.EACCES, "pipe_bind", "")
Nov 18 13:24:45 chuda04mac1017 Docker[35764] <Notice>: mirage_block_open: file:///Users/chuda04/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1
Nov 18 13:24:45 chuda04mac1017 Docker[35764] <Notice>: mirage_block_open: file:///Users/chuda04/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2?sync=1&buffered=1 returning 0
Nov 18 13:24:45 chuda04mac1017 Docker[35764] <Notice>: mirage_block_stat
Nov 18 13:24:45 chuda04mac1017 Docker[35764] <Notice>: vsock init 7:0 = /Users/chuda04/Library/Containers/com.docker.docker/Data, guest_cid = 00000003
Nov 18 13:24:45 chuda04mac1017 Docker[35734] <Notice>: Analytics: Sent heartbeat event.
Nov 18 13:24:45 chuda04mac1017 Docker[35734] <Notice>: Analytics: Sent appLaunched event.
Nov 18 13:24:45 chuda04mac1017 Docker[35734] <Notice>: Analytics: Sent appRunning event.
Nov 18 13:24:47 chuda04mac1017 Docker[35764] <Notice>:
	rdmsr to register 0x34 on vcpu 3
Nov 18 13:24:48 chuda04mac1017 Docker[35764] <Notice>: Docker is not responding: Get http://./info: EOF: waiting 0.5s
--- last message repeated 3 times ---
```

**Comment by ijc25** [comment]
@D3nn thanks for the update, please do close if it works for you at home otherwise we'll expect to hear from you here.

Probably best to take the upgrade issue to a new ticket.

**Comment by D3nn** [comment]
Looks like all is working well from home as well.   Thanks for the help.
