### ISSUE TITLE
Docker CLI don't install on MacOS X

### ISSUE THREAD

**Issue by PierluigiRiti** [docker/for-mac#96]
### Information

Diagnostic ID: D933E125-22CB-4BB5-BC68-A89C5232E3C9
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.4 (Build 15E65)
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. Install Docker on MacOSX version El Capitain, 16 GB of Ram
2. Call the command Diagnose & Feedback

**Comment by djs55** [comment]
As far as I can see the logs look normal. The `docker` binary is normally symlinked from `/usr/local/bin/docker` and `/usr/local/bin` is normally on the `$PATH`. Could you check your `$PATH` settings, and whether the symlink is pointing somewhere?

The symlink `/usr/local/bin/docker` should point to `~/Library/Group Containers/group.com.docker/bin/docker` which is also a symlink which points to `/Applications/Docker.app/Contents/Resources/bin/docker`.

**Comment by mchiang0610** [comment]
Merging with #119

**Comment by samoht** [comment]
Detected symptom of problem 'symlinks-are-not-correctly-installed' in D933E125-22CB-4BB5-BC68-A89C5232E3C9/20160803-092603.

Thanks for your report! The docker symlinks have not been correctly installed by the installer, which is a known issue that we are currently working on. A possible workaround is to install the docker client manually by running:
```
ln -s ~/Library/Group\ Containers/group.com.docker/bin/docker /usr/local/bin/docker
```

May be related to docker/for-mac#785

The following log matches:
```
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.vmnetd][2785] <Notice>: User 238128915 has container folder /Users/prit0001/Library/Containers/com.docker.docker/Data/s60
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.vmnetd][2785] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.vmnetd][2785] <Notice>: User 238128915 has container folder /Users/prit0001/Library/Containers/com.docker.docker/Data/s60
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.vmnetd][2785] <Critical>: File /var/run/docker.sock is a symlink or a socket
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.docker][2766] <Error>: Symlinks are not correctly installed.
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.docker][2766] <Notice>: com.docker.osx.hyperkit.linux launched with PID 2789
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.osx.hyperkit.linux][2789] <Notice>: Acquired task manager lock
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.osx.hyperkit.linux][2789] <Notice>: Maximum number of file descriptors is 10240
Aug  2 16:23:32 IEC02MGFCTFD57 Docker[com.docker.frontend][2788] <Critical>: dial unix /Users/prit0001/Library/Containers/com.docker.docker/Data/s20: connect: no such file or directory
```
