### ISSUE TITLE
docker issue cant run docker compose

### ISSUE THREAD

**Issue by srisiva** [docker/for-mac#960]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ijc25** [comment]
Could you please run Diagnose & Feedback from the :whale: menu, select Diagnose & Upload, paste the results of the diagnostic run (including diagnostic ID) back here and fill in the issue template with details of what you are doing and what did/did not happen? This will help us understand what is happening with the Docker application. Thanks!

I am closing this issue until the minimum necessary information is provided.
