### ISSUE TITLE
Docker no longer waking up after sleeping

### ISSUE THREAD

**Issue by drpain** [docker/for-mac#962]
### Expected behavior
The docker containers used to work after you put your Mac to sleep. I would open my lid, login, and for example my mysql container would be running and I could continue coding. 

### Actual behavior
It appears that the container is still running if you ``docker ps``, but you cannot access it through the exposed port anymore.

### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page
```
Docker for Mac: version: 1.12.3-beta30 (7314181)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/809F9DB1-6CA0-4290-BB92-2CCF49869138/20161117-065839.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. Run an instance of mysql. For example mariadb:
```shell
docker run \
    -d \
    -e MYSQL_ROOT_PASSWORD=root \
    -p 3306:3306 \
    -i \
    --name mysql \
    mariadb
```

  2. Ensure that you can access mysql through the command line client interface, or some alternative:

```shell
mysql -u root -P3306 -h 127.0.0.1 -proot
```

3. Put your computer to sleep, then wake it back up. 

4. If you try and access the container, you should no longer be able to. ``mysql -u root -P3306 -h 127.0.0.1 -proot``. You will notice that the container still appears to be working when you run ``docker ps``, but you won't be able to access it.

5. You will need to restart docker and start the mysql container again.

**Comment by ijc25** [comment]
This seems to be the same issue as #933 eventually converged upon (in https://github.com/docker/for-mac/issues/933#issuecomment-260985854). Please subscribe to that issue for further updates.

You might also want to consider an upgrade to 10.11.6 (or 10.12 if you prefer) and then apply the defaults update described in https://github.com/docker/for-mac/issues/933#issuecomment-260311428 since we believe that will improve behaviour over suspend/resume.
