### ISSUE TITLE
Docker remains in starting state

### ISSUE THREAD

**Issue by peterdavey** [docker/for-mac#963]
### Expected behavior
docker status is eventually running

### Actual behavior
docker status remains in starting indefinitely

### Information
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G31)
logs: /tmp/93416264-D561-4CC4-9D3D-E94CBF51C786/20161117-151316.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. start machine 
  2. start docker (either via Spotlight or from Applications folder)

**Comment by peterdavey** [comment]
logs: /tmp/93416264-D561-4CC4-9D3D-E94CBF51C786/20161117-151316.tar.gz
[20161117-151316.tar.gz](https://github.com/docker/for-mac/files/597574/20161117-151316.tar.gz)

**Comment by peterdavey** [comment]
Fixed by preferences -> Uninstall / Reset -> select factory reset following instructions then restart

**Comment by joyJZhang** [comment]
@peterdavey if factory reset，Whether the data will be lost？
