### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by rbpaservices** [docker/for-mac#964]
### Expected behavior
Check for update brings up update available. Download seems to run.
### Actual behavior
Message box displayed with Update Error message, no other information
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mchiang0610** [comment]
@rbpaservices Thanks for submitting this. 

Do you have a way to reproduce this? I'm unable to reproduce this.

**Comment by rbpaservices** [comment]
No, but I was able to get past it eventually and completed the update.  I
would like to suggest that some error code be presented to help  with this
type of error.

Thanks

On Nov 17, 2016 8:46 PM, "Michael Chiang" <notifications@github.com> wrote:

@rbpaservices <https://github.com/rbpaservices> Thanks for submitting this.

Do you have a way to reproduce this? I'm unable to reproduce this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docker/for-mac/issues/964#issuecomment-261426060>, or mute
the thread

**Comment by mchiang0610** [comment]
@rbpaservices Glad it worked out for you! Thanks for using Docker.

**Comment by ijc25** [comment]
Did the dialog literally only contain the text "Update Error"?

I don't think we can action this any further without a diagnostics upload (triggered from the whale menu). So if you would like us to investigate further please provide the diagnostic id.

**Comment by MagnusS** [comment]
An "Update error" dialog will be shown if there's a problem with the downloaded update (e.g. due to a network issue). Updating again will download a new file and should resolve the issue if the download completes successfully.

**Comment by rbpaservices** [comment]
You are welcome.  BTW I am just starting out with Eclipse Che. So far I
like it

**Comment by rogaha** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT

**Comment by rbpaservices** [comment]
Funny thing is that I responded that I was able to get past the issue on
Nov 17th.
