### ISSUE TITLE
cannot access nginx on docker-for-mac using mydomain

### ISSUE THREAD

**Issue by dearfrankg** [docker/for-mac#969]
### Expected behavior

I should be able to access nginx running on docker using mydomain

### Actual behavior

I cannot access nginx running on docker using mydomain

### Information

I think it's a macos firewall issue

### Steps to reproduce the behavior

video of the behavior is here: http://screencast.com/t/lQ8DplxPu

it takes a minute for the video to load

**Comment by rogaha** [comment]
@dearfrankg can you please run the `diagnose and upload`, it will help us to identify what's blocking `nginx`. thanks!

**Comment by dearfrankg** [comment]
Ran diagnostics, here is the ID 

BD7AED7C-FA8D-4599-A85A-7B5B9A907D48

**Comment by rogaha** [comment]
thanks @dearfrankg, can you please do a `docker ps` while the `firewall` is `on`? the only error I see on the logs is from a container trying to `bind` on port `80` that i's already in use.

```
Nov 18 14:04:54 frankg-mbp Docker[com.docker.slirp][75376] <Notice>: Client.negotiate: received ((magic VMN3T)(version 18)(commit 2d5b4d9c3daa089e3869e6355a47dd96dbf39856))
Nov 18 14:04:54 frankg-mbp Docker[com.docker.vmnetd][18061] <Critical>: Failed to bind IPv4 0 80: Address already in use
Nov 18 14:04:54 frankg-mbp Docker[com.docker.vmnetd][18061] <Critical>: sendmsg ok
Nov 18 14:04:54 frankg-mbp Docker[com.docker.slirp][75376] <Error>: Failed to start instance: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
Nov 18 14:05:26 frankg-mbp Docker[com.docker.slirp][75376] <Notice>: Creating resource Entry(tcp:0.0.0.0:80:tcp:172.17.0.2:80)
Nov 18 14:05:26 frankg-mbp Docker[com.docker.slirp][75376] <Notice>: Write offset=0 data=[tcp:0.0.0.0:80:tcp:172.17.0.2:80] to file
Nov 18 14:05:26 frankg-mbp Docker[com.docker.vmnetd][18287] <Notice>: Client reports version 1, commit 0123456789012345678901234567890123456789
Nov 18 14:05:26 frankg-mbp Docker[com.docker.slirp][75376] <Notice>: Client.negotiate: received ((magic VMN3T)(version 18)(commit 2d5b4d9c3daa089e3869e6355a47dd96dbf39856))
```

**Comment by dearfrankg** [comment]
procedure:

0. confirm firewall is on 
1. stop non-docker nginx
2. nuke all docker-for-mac containers
3. run docker nginx: `dk run -p 80:80 nginx`
4. restart chrome
5. can access nginx at http://localhost 
6. cannot access nginx at http://debugtime.com
7. run docker ps

```
  CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                         NAMES
  4430cb4086d3        nginx               "nginx -g 'daemon off"   4 minutes ago       Up 4 minutes        0.0.0.0:80->80/tcp, 443/tcp   mad_kilby
```

7. turn off firewall
8. restart chrome
9. can access nginx at http://debugtime.com
10. run docker diagnostics 

```
DIAGNOSTICS_ID:
BD7AED7C-FA8D-4599-A85A-7B5B9A907D48
```

11. turn on firewall
12. restart chrome and disable cache
13. cannot access nginx at http://debugtime.com
14. run docker diagnostics 

```
DIAGNOSTICS_ID:
BD7AED7C-FA8D-4599-A85A-7B5B9A907D48

Since diagnostics id seems the same as before here is header:
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/BD7AED7C-FA8D-4599-A85A-7B5B9A907D48/20161124-181546.tar.gz
```

**Comment by djs55** [comment]
Does `debugtime.com` resolve to an IP on your host?

I'd like to check it's not a DNS issue and not something to do with chrome.

Could you try the following:

- run `docker run -p 80:80 nginx` and then `curl http://<IP on host>/` when the firewall is up
- run `docker run -p <IP on host>:80:80 nginx` and then `curl http://<IP on host>/` when the firewall is up
- run `sudo nc -l <IP on host> 80` and then run `curl http://<IP on host>/` to see if the headers are printed

Could you also include the results of `netstat -an` on the host when running `docker run -p 80:80 nginx`?

As you say, it could well be a firewall issue. Could you take a look in "System Preferences -> Security & Privacy -> Firewall Options". Is Docker in the applications list? For reference on my system I have:

- "Block all incoming connections" -- not checked
- Docker is in the list of applications with "Allow incoming connections" set
- "Automatically allow built-in software to receive incoming connections" -- checked
- "Automatically allow downloaded signed software to receive incoming connections" -- checked
- "Enable stealth mode" -- not checked

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
