### ISSUE TITLE
hyperkit consumes high CPU 

### ISSUE THREAD

**Issue by kulrohit** [docker/for-mac#971]
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ... Keep docker for mac idle, do not run any container for few hours and notice high noise from MAC CPU fan fast draining battery 
  2. ...

**Comment by kozhin** [comment]
Had this issue. I reinstalled Docker for Mac and now it's working fine. Removed everything regarding Docker from my MacBook using this https://docs.docker.com/docker-for-mac/#/uninstall-or-reset and Terminal with:
`sudo find / -name '*docker*'`

**Comment by rogaha** [comment]
@kulrohit can you please try to `uninstall` and `install` the latest `beta` version (https://download.docker.com/mac/beta/Docker.dmg) ?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
