### ISSUE TITLE
Slow network behaviour

### ISSUE THREAD

**Issue by cdekok** [docker/for-mac#973]
### Expected behavior
Fast outgoing connections

### Actual behavior
Slow outgoing connections

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/8CD9D780-8AEF-427D-94AE-C5FC8F2BCDB8/20161121-114157.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

It's very slow for me on 1.12.3 with outgoing connections.
Using curl I am often hitting timeouts.

Here are some timings..

**On my host**
curl -w '@format.txt' -o /dev/null -s http://example.com
    time_namelookup:  0.005
       time_connect:  0.095
    time_appconnect:  0.000
   time_pretransfer:  0.095
      time_redirect:  0.000
 time_starttransfer:  0.185
                    ----------
         time_total:  0.185

**On docker**
curl -w '@format.txt' -o /dev/null -s http://example.com
    time_namelookup:  5.530
       time_connect:  5.614
    time_appconnect:  0.000
   time_pretransfer:  5.614
      time_redirect:  0.000
 time_starttransfer:  5.705
                    ----------
         time_total:  5.705

**On virtual box**
curl -w '@format.txt' -o /dev/null -s http://example.com
    time_namelookup:  0.004
       time_connect:  0.085
    time_appconnect:  0.000
   time_pretransfer:  0.085
      time_redirect:  0.000
 time_starttransfer:  0.166
                    ----------
         time_total:  0.166

**Comment by rogaha** [comment]
@cdekok I couldn't find any errors on your `diagnose` logs. Can you please try to perform a `factory reset`, if possible, to check if that helps?

**Comment by aaronweaver** [comment]
@rogaha experienced the same issues here as well, very slow and poor network performance.

**Comment by gorivishal** [comment]
+1

**Comment by jamesneal** [comment]
Also having this issue on:
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

In the container's resolv.conf, we have:
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain local
nameserver 192.168.65.1
nameserver 192.168.65.10
nameserver 192.168.65.9
nameserver 192.168.65.8
nameserver 192.168.65.7
nameserver 192.168.65.6
nameserver 192.168.65.5
nameserver 192.168.65.4
nameserver 192.168.65.3

Of those, 192.168.65.10, 192.168.65.8, 192.168.65.6, and 192.168.65.4 don't respond to DNS requests.

**Comment by cdekok** [comment]
@rogaha Unfortunately a factory reset did not seem to work, I do suspect it happened somewhere during an update as I did not encounter many issues a while ago.

**Comment by rogaha** [comment]
thanks for the update @cdekok @aaronweaver. We are investigating it.

**Comment by cdekok** [comment]
I found it has something to do with IP v6.. doing the curl request with -4 goes fast.
adding `options single-request-reopen` in the docker image /etc/resolv.conf worked

There was somebody with the same problem who had figured it out http://serverfault.com/questions/647193/docker-debian-slow-dns-resolve

Could this be a problem in the docker network layer?

**Comment by rogaha** [comment]
@cdekok @aaronweaver @jamesneal It looks like that there are some DNS problems in the latest `stable` version which is fixed in `beta 30.1` -- the diagnostics in beta 30.1 are also much better. If possible, can you please upgrade to `beta 30.1` and let us know how it goes?

**Comment by OlivierChirouze** [comment]
Hi,

I've been suffering this bug for a few weeks now (I'm using composer and a `composer update` on a local network would take about 5 minutes to complete, driving me crazy!).
For information:
- `factory reset` did not help
- adding `options single-request-reopen`in the `/etc/resolv.conf` file seemed to make things go *slightly* faster
- switching to beta channel with version `Version 1.13.0-rc2-beta31 (14387)` **did** solve the issue, thanks @rogaha!

**Comment by rogaha** [comment]
@OlivierChirouze I'm glad it worked for you! @cdekok can you please try it as week?

**Comment by cdekok** [comment]
@rogaha Got a change to install the beta today, and it seems to work fine on it, I think the issue can be closed 👍
