### ISSUE TITLE
Docker on Mac OS Sierra - not working after install

### ISSUE THREAD

**Issue by sergimartnez** [docker/for-mac#976]
### Expected behavior
running "docker ps" --> expecting correct behaviour.

### Actual behavior
running "docker ps"
Error response from daemon: dial unix /Users/Sergio/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: no such file or directory

### Information

  **- Full output of the diagnostics from "Diagnose & Feedback" in the menu**

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.12 (build: 16A323)
logs: /tmp/02D28A4E-A72B-483C-AD50-62892BFA2644/20161122-132428.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Sergio/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
  

### Steps to reproduce the behavior

  1. Installed Docker version 1.12.3 (13776) on MacOS SIerra 10.12
  2. Run on the console "docker ps"

**Comment by ebriney** [comment]
It seems that your qcow volume as some errors, can you try this:
- close the app
- open a terminal
- run `Applications//Docker.app/Contents/MacOS/qemu-img check -r all ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2`
- launch the app

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
