### ISSUE TITLE
Docker for Mac OS Sierra hangs on restart

### ISSUE THREAD

**Issue by bell87** [docker/for-mac#977]
### Expected behavior
`docker ps` works successfully

### Actual behavior
`docker ps` times out - API error (500): dial unix /Users/user/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

Docker has restarted itself and hangs during restart.

### Information
Docker for Mac: version: 1.12.3-beta30.1 (f94d037)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/F000C2B8-8972-4884-9C2A-1C9B5B8789C1/20161122-165226.tar.gz
failure: docker ps failed: (Failure "docker ps: timeout after 10.00s")
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

### Steps to reproduce the behavior
docker ps

**Comment by rogaha** [comment]
Detected symptom of problem 'aufs-corruption' in F000C2B8-8972-4884-9C2A-1C9B5B8789C1/20161122-165226.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

**Comment by rogaha** [comment]
@bell87 if possible, would you mind to try a `reset to factory` to see if that fixes the issue?

**Comment by bell87** [comment]
@rogaha Yes that works as a temporary fix, I have to reset to factory every time it happens though.

**Comment by rogaha** [comment]
thanks for the update @bell87. How often does it happen?

**Comment by bell87** [comment]
Usually once per day, sometimes more often than that, I'm also using codeship jet, when I start the service using jet run [service] I'll get an API 500 error and then docker is restarting itself. It doesn't seem to follow any pattern of when / why it happens.

**Comment by djs55** [comment]
I think the corruption of `/var/lib/docker` is a cascade failure -- it probably left the AUFS in a bad state after the VM crashed. The VM crashes look like this:
```
 <Notice>:  reason          VMX
 <Notice>:  rip             0xffffffff818266bd
 <Notice>:  inst_length     5
 <Notice>:  status          0
 <Notice>:  exit_reason     2
 <Notice>:  qualification   0x0000000000000000
 <Notice>:  inst_type               0
 <Notice>:  inst_error              0
```
I believe `exit_reason 2` means a triple-fault. There may be relevant output on the VM's console but unfortunately this has been erased by the VM reboot.

Could you reproduce with the most recent beta (33.1) and upload a fresh set of diagnostics? The new diagnostics should include the VM console output for the last 10 VM reboots, so hopefully one of them will have something useful on it.

Do you have a publicly sharable service + set of instructions that I could use to reproduce this?

**Comment by balrajsingh** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
