### ISSUE TITLE
Container locks up when performing heavy file i/o off mounted volume

### ISSUE THREAD

**Issue by welps** [docker/for-mac#979]
### Expected behavior
Container doesn't lock up

### Actual behavior
Container locks up and docker locks up when trying to restart the container

### Information

Docker for Mac: version: 1.12.3-beta30.1 (f94d037)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/9A210CAE-C9E3-4455-BCD2-9A305A6E8AB1/20161122-162213.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

This occurs when I'm doing either a mysql/mongo db restore/migration, but does not occur if I don't opt for persistent storage/don't mount the volume where the data is stored. Seems like it stems from a similar issue that causes #82 ?

This happens on both Docker for Mac stable and beta.

1.  I have this sample set of data to reproduce this issue: https://dl.dropboxusercontent.com/u/4486643/sample-data.tgz -- I unpack it to `/private/var/www/folderwhereikeepmydbfiles` 

2. `docker run -d --name mongo -v /private/var/www/folderwhereikeepmydbfiles:/data/db mongo:2.6.12`

2. `docker exec -it mongo bash`

3. `cd /data/db`

4. `mongorestore --db test dump/test --drop`

If it actually completes the restore, try again -- I'm able to get it to lock up within 1-3 tries.

**Comment by ijc25** [comment]
@welps did you mean #825? I don't see a link to #82 whereas it is fairly plausible that this is related to #825.

**Comment by welps** [comment]
@ijc25 I actually came to the realization it was a shared folder/mounted volume issue because of #82, but you're correct that this is actually related to #825

**Comment by ijc25** [comment]
Thanks for the update. Based on my debugging of this and #825 today I'm pretty convinced they are the same issue. So I'm going to close this as a dup, please subscribe to #825 for further updates.

**Comment by welps** [comment]
@ijc25 Sure, no problem. Thanks!

**Comment by ijc25** [comment]
(forgot to actually close, doing it now)
