### ISSUE TITLE
Docker not coming up

### ISSUE THREAD

**Issue by cloudmunch1** [docker/for-mac#98]
### Expected behavior

Docker should start up

### Actual behavior

Docker is throwing error

### Information

Diagnostic ID: D9057BF2-7E34-4361-834E-57D114F2D5AA
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.2 (Build 15C50)
[ERROR]  docker-cli
         wrong Docker version: 1.6.0 (expected 1.12.0)
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         /Users/srp/Library/Containers/com.docker.docker/Data/s60 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s60
         docker ps failed
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/srp/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/D9057BF2-7E34-4361-834E-57D114F2D5AA/20160803-151504/qemu-img-check.stdout 2> /tmp/D9057BF2-7E34-4361-834E-57D114F2D5AA/20160803-151504/qemu-img-check.stderr: exit 1")
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         /Users/srp/Library/Containers/com.docker.docker/Data/s40 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s40
         com.docker.db is not running
[ERROR]  slirp
         /Users/srp/Library/Containers/com.docker.docker/Data/s51 does not exist
         Unexpected error (No such file or directory) connecting to /Users/srp/Library/Containers/com.docker.docker/Data/s51
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[ERROR]  moby
         /Users/srp/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running

### Steps to reproduce

1. Just Installed
2. Removed VirtualBox
3. Ran Docker

**Comment by djs55** [comment]
The logs have:
```
<Critical>: Docker does not rely on Virtualbox but may not work properly on systems with VirtualBox versions prior to v4.3.30
        VirtualBox v4.3.26 is currently installed.
        Please upgrade or uninstall Virtualbox.
```
Could you check how you uninstalled virtual box? It may not be sufficient to drag the application to the trash as this won't install the kernel drivers. Try following [these instructions](https://www.virtualbox.org/manual/ch02.html#idm871)

An alternative, try installing Virtualbox v5 which is compatible with Docker for Mac. The install of v5 should upgrade the components of v4 which conflict with the MacOS hypervisor.framework.

**Comment by mchiang0610** [comment]
@cloudmunch1 Possible to try resetting to factory defaults?  Please report back if it's still not working. Happy to troubleshoot further. 

Will reopen on reply. 

Thanks!
