### ISSUE TITLE
Kernel errors when trying to do snmpwalk on OIDs with COUNTER64 values

### ISSUE THREAD

**Issue by amsamuel** [docker/for-mac#982]
### Expected behavior
I am running a centos container with net-snmp-utils installed and trying to run an snmpwalk on a remote host.
It is expected that an snmpwalk would work normally for any OIDs, including ones that give COUNTER64 values.
e.g. `snmpwalk -v2c -c<community string> <remote host> ifHCInOctets`
Note that this works fine for doing an snmpwalk on localhost.

### Actual behavior
The snmpwalk hangs and fails. Closer inspection shows that the appropriate get or get-next request is sent and no response is received.
`dmesg` shows kernel errors saying `bsalg: parser failed`.

### Information

- Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.5 (build: 15F34)
logs: /tmp/1741D5BA-5BC9-4256-B996-BCD42AE0281E/20161123-140416.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

Looking into the `bsalg: parser failed` kernel error leads you to https://github.com/torvalds/linux/blob/master/net/ipv4/netfilter/nf_nat_snmp_basic.c where it is trying to translate/"mangle" IPs for SNMP packets.

tcpdumps for the snmpwalk shows that snmp-get and snmp-get-next requests are made to the remote host, and responses for COUNTER64 values are not received. A tcpdump on the remote host shows that it is sending responses, but the responses do not get through the kernel to container.
Comparing packets between get-next requests for COUNTER32 OIDs with succeed and COUNTER64 OIDs that fail, the difference is one octet before the OID value that says 0x41 instead of 0x46.

This is not reproducible with the same image on a linux host, even with a kernel >= 4.4, so it seems to be an issue with hyperkit/xhyve. 

### Steps to reproduce the behavior

  1. Run snmpd using something like:
The host needs to be on different host than the 'docker for mac' host running the client to have the bug occur, but it can be created from:
```
# snmp-server
FROM centos:7
RUN yum install -y net-snmp
RUN echo 'rocommunity public' > /etc/snmp/snmpd.conf
CMD /usr/sbin/snmpd -f -p /var/run/snmpd.pid -LS 4 d -Lf /dev/null udp:161,udp6:161,tcp:161,tcp6:161
```
This must be on a different docker host than the one running the client to have this fail.
  2. Run the snmpwalk using the following image:
```
# snmp-client
FROM centos:7
RUN yum install -y net-snmp-utils net-snmp-libs
```
and running:
`docker run snmp-client snmpwalk -v2c -cpublic <remote host> ifHCInOctets`

**Comment by djs55** [comment]
Thanks for the report. On a Linux 4.4.0 baremetal host with docker 1.12.5 I ran in a directory with your first `Dockerfile`:
```
$ docker build -t snmp-server .
$ docker run -i --rm -p 161:161/udp -p 161:161/tcp snmp-server
```
On Docker for Mac beta 34 (released yesterday) I ran in a directory with the second `Dockerfile`:
```
$ docker build -t snmp-client .
$ docker run snmp-client snmpwalk -v2c -cpublic 192.168.1.100 ifHCInOctets
IF-MIB::ifHCInOctets.1 = Counter64: 0
IF-MIB::ifHCInOctets.14 = Counter64: 8627
$ echo $?
0
```
I couldn't see any complaint on the VM's `dmesg`. I'm not completely familiar with `snmp` -- does this look more like what you would expect? There have been a lot of kernel and `xhyve` updates recently in the beta branch -- could you upgrade to beta 34 and try to reproduce?

Thanks again for the interesting bug report!

**Comment by amsamuel** [comment]
It does appear to be fixed in beta34.

Thank you for looking into it.
