### ISSUE TITLE
Docker for Mac doesn't read hosts /etc/hosts correctly when using aliases

### ISSUE THREAD

**Issue by flxsource** [docker/for-mac#983]
### Expected behavior
Docker Engine is able to resolve the host name and any aliases declared in the `/etc/hosts` file on the host OS.

### Actual behavior
Docker Engine is only able to resolve the host name, but _not_ any aliases.

### Information
Diagnostic ID: AF53934A-7F40-4AAA-82E7-6093DE58E779

We are running a Docker registry on our internal network, and a second registry configured as a pull through cache on the same machine, but under a different hostname. The two hostnames used are currently NOT in DNS, so modifying the `/etc/hosts` file is required.

The problem is that  when using the format `[IP Address] [Hostname] [Aliases]` in `/etc/hosts` Docker Engine is only able to resolve the `[Hostname]`, not any of the `[Aliases]`. If the line is split to be multiple `[IP Address] [Hostname]` then Docker Engine is correctly able to resolve all of them.

### Steps to reproduce the behavior

  1. Set up a registry as a pull through cache
  2. Declare the IP and hostname in `/etc/hosts` (a bogus hostname can be provided, to then allow the correct hostname to be declared as an alias.
  3. Configure Docker for Mac to use the registry as a mirror, using the hostname declared as an alias
  4. Attempt to pull an image that has not already been pulled onto the local host

**Comment by rogaha** [comment]
@flxsource thanks for the reporting the issue, I've raised another issue on the `vpnkit` repository: https://github.com/docker/vpnkit/issues/162. We will let you know as soon as it gets fixed!

**Comment by djs55** [comment]
I've merged a fix for this into the master branch which should be released in beta 37, due in a couple of weeks.

**Comment by yallop** [comment]
@flxsource, could you please confirm that the latest beta (39) resolves the problem?

**Comment by samoht** [comment]
Both stable and channels should now contain the fix, so closing. @flxsource please re-open that issue if the fix doesn't work for you. Thanks!
