### ISSUE TITLE
internal connections in a docker-compose setup fail, high cpu usage of com.docker.hyperkit

### ISSUE THREAD

**Issue by Pike** [docker/for-mac#992]
### Expected behavior

Connections between instances and on the instance itself work

### Actual behavior

I see dropped connections within an instance and inbetween instances

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/40B4EC0E-B407-4570-973F-C29C74C10817/20161129-182240.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

40B4EC0E-B407-4570-973F-C29C74C10817 is the diagnostic ID

  - A reproducible case if this is a bug, Dockerfiles FTW

Things went great for much of my path to the status quo, but then once I had all the pieces in place, they all stop working.

### Steps to reproduce the behavior

I'm trying to reproduce http://pike.github.io/master-ball/test-master/ in a docker-compose setup.

Here's my docker-compose.yml:

version: '2'
services:
  hg:
    build: hgmo
    command: hg --cwd /data/repos serve -p 8001 --webdir-conf=../webdir.conf
    ports:
     - "8001:8001"
    volumes:
     - ./stage/repos:/data/repos
     - ~/.mozbuild/version-control-tools:/version-control-tools
  a10n:
    build:
      context: .
      dockerfile: a10n/Dockerfile
    command: bash
    volumes_from:
      - hg
    volumes:
     - ./a10n/a10n:/data/a10n
    links:
      - rabbitmq
  bb:
    build: 
      context: .
      dockerfile: bb/Dockerfile
    command: bash
    volumes_from:
      - hg
    volumes:
      - ./bb/master-ball:/data/master-ball
      - ./bb/slave-ball:/data/slave-ball
      - ./stage/builds:/data/builds
    links:
      - hg
      - elasticsearch
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=XXX
      - RABBITMQ_DEFAULT_PASS=XXX
  elasticsearch:
    image: elasticsearch
    ports:
    - "9200:9200"

**Comment by Pike** [comment]
Filed this based on the closing comment of issue #82.

**Comment by djs55** [comment]
Thanks for the report. Looking through the diagnostics I see evidence of DNS-related network failures:
```
 <Error>: Lwt.async failure (Failure nth): Raised at file "pervasives.ml", line 32, characters 22-33
	Called from file "lib/dns_forward.ml", line 38, characters 41-77
	Called from file "lib/dns_forward.ml", line 102, characters 16-57
```
This is the same bug as reported in https://github.com/docker/for-mac/issues/578. The fix for this bug has been released in the beta channel -- could you upgrade to beta (current version 34.1) and let me know if it reproduces? The fix for this will be in the 1.13 stable update early in the new year.

**Comment by djs55** [comment]
I'll close the ticket as fixed in beta, but please do re-open if it still fails on the beta channel.

**Comment by Pike** [comment]
Thanks @djs55. I'm trying docker beta, but I fail to get docker-compose build to do anything useful.

I've already reset to factory defaults, and I'm running into a Docker.qcow2 errors.

Submitted 4527EFED-89FB-401D-86EE-AD930D03DD39.

**Comment by Pike** [comment]
Filed #1117 on my current problem.

**Comment by Pike** [comment]
The networking stuff seems to be good now, but the elasticsearch part of my setup used to work, and right now doesn't. Filed #1125 on that.
