### ISSUE TITLE
docker can not push image

### ISSUE THREAD

**Issue by linpf870208** [docker/for-mac#993]
i just suddenly can not push images by docker push command.

1963422757ad: Pushing [==================================================>] 45.06 kB
5f70bf18a086: Layer already exists
510e363c12a3: Layer already exists
f09fdb5ddd25: Layer already exists
a2ab78debd3e: Layer already exists
66754d2993e3: Layer already exists
b435f567e45e: Layer already exists
df09ce9c9073: Layer already exists
6eb35183d3b8: Layer already exists
digest invalid: provided digest did not match uploaded content

docker -v
Docker version 1.12.3, build 6b644ec

docker info
Containers: 4
Running: 3
Paused: 0
Stopped: 1
Images: 72
Server Version: 1.12.3
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 133
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: GDTW:Q2BH:OB3P:3YFX:KLAG:FVWB:6E3H:LDNS:GO57:UX3M:N3OU:EAGY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 37
Goroutines: 62
System Time: 2016-11-29T11:54:50.258301314Z
EventsListeners: 1
Http Proxy: 172.16.19.13:8080
No Proxy: *.local、169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
172.16.19.22:5000
127.0.0.0/8

it will retry a few times, then show digest invalid.

anyone knows why?

**Comment by ebriney** [comment]
Hi, can you send us a report : Whale menu -> Diagnose & Feedback -> Upload

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
