### ISSUE TITLE
Can't get the Docker Image of SQL Server for Mac

### ISSUE THREAD

**Issue by bienheladas** [docker/for-mac#995]
### Expected behavior

Want to Pull the Docker image of SQL Server from Docker Hub with the sentence:

 sudo docker pull microsoft/mssql-server-linux --> expecting correct behaviour.

### Actual behavior

Mac-mini-de-Omar:~ Omar$ sudo docker pull microsoft/mssql-server-linux
Password:
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Error response from daemon: dial unix /Users/Omar/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: no such file or directory). Using system default: https://index.docker.io/v1/
Error response from daemon: dial unix /Users/Omar/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: no such file or directory

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.4 (build: 15E65)
logs: /tmp/B8E8CD41-A40B-475D-8A2C-31973C9245D2/20161129-234731.tar.gz
failure: Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
[OK]     vmnetd
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[ERROR]  moby
         /Users/Omar/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         docker ps failed
[OK]     menubar
[ERROR]  disk
         Docker.qcow2 has unexpected errors: either repair offline or reset to factory defaults
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

  - A reproducible case if this is a bug, Dockerfiles FTW

  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. Installed Docker version 1.12.3 (13776) on MacOS SIerra 10.12
  2. Run on the console "sudo docker pull microsoft/mssql-server-linux"

**Comment by ebriney** [comment]
Can you try to `Reset to default` as suggested in the diagnose?

**Comment by djs55** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
