### ISSUE TITLE
could not start docker

### ISSUE THREAD

**Issue by zdalh** [docker/for-mac#996]
### Information

Diagnostic ID: 7489EB6A-D9C8-4676-9557-6599BFA40A01
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.12 (Build 16A323)
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

1. ...
2. ...

**Comment by ebriney** [comment]
Please install the latest version and check if it's work ([here](https://download.docker.com/mac/beta/Docker.dmg))
Re-open the issue if it fails
