### ISSUE TITLE
docker 1.13.0-rc2 for mac - build is failed if Dockerfile contains extra empty lines

### ISSUE THREAD

**Issue by nawa** [docker/for-mac#998]
### Expected behavior
Build is not failed with provided Dockerfile as with docker v1.12

### Actual behavior
Build is failed with message

	Unknown instruction: RM

### Information

  - Dockerfile contains extra empty line
```
FROM alpine:latest

RUN apk update && apk upgrade && \
#empty line
	rm -rf /var/cache/apk/*
```
  - Docker version
```
Docker for Mac: version: 1.13.0-rc2-beta31 (de6f6c2)
OS X: version 10.12.1 (build: 16B2555)
```

As a result the builds using my old docker files are failed with new docker version

**Comment by efosmark** [comment]
I'm seeing this, too. Version `1.13.0-rc2-beta31 (14387)`.

**Comment by epahl-atlassian** [comment]
I'm seeing the same issue with `1.13.0-rc2-beta31 (14387)`

**Comment by vdemeester** [comment]
This is linked to https://github.com/docker/docker/issues/29005 which will be fixed in the RC3 👼

**Comment by ebriney** [comment]
Hi, it should be fixed in 1.13.0 rc3 see [here](https://github.com/docker/docker/pull/29064)

**Comment by rogaha** [comment]
@nawa @epahl-atlassian can you please verify if the issue persists with `1.13.0-rc3-beta32`?

**Comment by nawa** [comment]
@rogaha Looks like fixed

**Comment by rogaha** [comment]
awesome, thanks for the update @nawa!
