### ISSUE TITLE
How can I download a previous Beta

### ISSUE THREAD

**Issue by dsvmacdonald** [docker/for-mac#999]
### Information

The latest Beta is using Docker 1.33.  That doesn't work for me.  I need Docker 1.12, but Stable version won't work with my VPN.  I previously used Beta 1.12.3-beta30 and it worked fine.  How can I download it?

Thanks,

Dan

**Comment by ebriney** [comment]
Hi, can you download it [here](https://download.docker.com/mac/beta/1.12.3.13946/Docker.dmg)

**Comment by dsvmacdonald** [comment]
Thanks

**Comment by aventurella** [comment]
Don't mean to re-open this issue, but looking here:
https://docs.docker.com/docker-for-mac/release-notes/

and pulling the url from the link above:
```
https://download.docker.com/mac/beta/1.12.3.13946/Docker.dmg
```

I was trying to request a specific beta version but the release notes page do not contain the SHA of the build, I assume that's what the last 5 chars are in the link provided or it's the build number? This repo doesn't appear to have any tags to denote the SHA.

I also tried this to no avail:
```
https://download.docker.com/mac/beta/1.13.0-rc3-beta33/Docker.dmg
```
